### ISSUE TITLE
SDK path does not work with spaces

### ISSUE THREAD

**Issue by jrote1** [Dart-Code/Dart-Code#100]
When the dart sdk path has spaces you get the following problem.

```
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
exit code 1
```

**Comment by DanTup** [comment]
Whoops!

At what point does this occur; for the normal analysis or when pressing F5 to run?

**Comment by jrote1** [comment]
Ah sorry is when am running `pub get`

**Comment by jrote1** [comment]
@DanTup have you started working on this?

**Comment by DanTup** [comment]
I have not; still not will so probably won't get anything done before tomorrow evening, so go for it :)
