### ISSUE TITLE
No Intellisense for Constructors When Not Using "new" to Instantiate Class

### ISSUE THREAD

**Issue by ciw1973** [Dart-Code/Dart-Code#1007]
Dart 2.0 no longer requires the use of "new" when instantiating classes, but if it's omitted, Intellisense doesn't suggest available constructors for the class, as it does when "new" is used.

**Comment by DanTup** [comment]
Can you provide a concrete example/screenshot and check which version of Flutter you're on? This should've been fixed by Dart a while back:

https://github.com/dart-lang/sdk/issues/32947

**Comment by ciw1973** [comment]
I'm running Flutter 0.4.4, with the latest VS Code:

![1](https://user-images.githubusercontent.com/2350088/41310050-47dd6388-6e78-11e8-9b29-bfb2b7bbadc3.png)

If I instantiate with "new", I get the expected suggestions as I enter the class name:

![2](https://user-images.githubusercontent.com/2350088/41310102-73a45698-6e78-11e8-892f-a4cc39880b1f.png)

And as expected, the named constructors appear as suggestions once I've entered the full class name:

![3](https://user-images.githubusercontent.com/2350088/41310140-93676a06-6e78-11e8-945b-01fa909ab20f.png)

However, without "new", I don't see the constructors as suggestions when I enter the class name:

![4](https://user-images.githubusercontent.com/2350088/41310157-a73a8e3c-6e78-11e8-9825-8b9b1b4a9f95.png)

Or having entered the full class name:

![5](https://user-images.githubusercontent.com/2350088/41310166-b0c8590c-6e78-11e8-8eba-ee2a45c326ec.png)

**Comment by DanTup** [comment]
Ok, following the chain... Flutter v0.4.4 has engine 06afdfe54ebef9168a90ca00a6721c2d36e6aafa which has Dart 46ab040e589adc5200370dec7952ce5150850822, which is first in release 2.0.0-dev.55.0

The fix linked above was first released in ... 2.0.0-dev.56.0. Doh!

So, I'm afraid it's fixed but it hasn't made the Flutter beta channel yet. You could switch to a channel that's updated more recently (though may be less stable - though you can always change back if you get blocked) or wait until the next beta release.
