### ISSUE TITLE
Flutter VSC Plugin – Remember device preferences

### ISSUE THREAD

**Issue by lukepighetti** [Dart-Code/Dart-Code#1045]
I have a Simulator and my iPhone and even if I've been using the Simulator all day sometimes Flutter will pick my iPhone to use for debugging. I would like the plugin to remember which of the two I am using and select it first.

**Comment by DanTup** [comment]
Currently we'll automatically switch to any newly-connected device (assuming if you connect a device, you wish to use it next). There are two options we currently have for controlling this:

1. Set the `dart.flutterSelectDeviceWhenConnected` setting to `false`. This will disable the behaviour of switching to the newly-connected device
2. Use a `launch.json` and explicitly set a `deviceId` in the launch config

I think `1` might solve your problem; but let me know if you think that's not enough and we can review other options.
