### ISSUE TITLE
VS Code: Support `flutter attach`

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#1056]
In the same way that we have a `Debug: Attach to Dart Process` command, there should be a `Debug: Attach to Flutter Process` command. Running this command should attempt to attach to the "current device" (as shown in the status bar) using `flutter attach --machine`. If there is no current device, `flutter attach` should be run without the device parameter (which should result in `waiting...` and allow the user to launch the emulator/app while it's waiting).

Once attached, the debug session should behave the same as if launched the app, including:

- breakpoints
- expression evaluation/watch/variables
- hot reloading and restarting (does attach support restart?)
- service extensions such as debug banner, time dilation
- Inspect Widget if the app was launched with `--track-widget-creation`

Stopping the debug session should cleanly detach and leave the app running on the device (and, if possible, allow re-attaching).

It should also be possible to configure an `attach` launch config in `launch.json` (including allowing the device ID to be configured there) to allow easier attaching with `F5`.

**Comment by matthew-carroll** [comment]
@DanTup is this ticket completed?  Or are you still testing/verifying?

**Comment by DanTup** [comment]
It's currently still on a branch (this is the VS Code implementation issue) because although it works it requires you do things up in a certain order (the device must be running before you run Attach but the flutter view must not be created until after). It's useable but I'm not sure whether we want to ship it before we have the ability to attach to an already-visible view (this is related to the recent email chain about finding ports).
