### ISSUE TITLE
Dart in VS Code doesn't debug and can't read the inital flutter app that was created by the system

### ISSUE THREAD

**Issue by gregrtardif** [Dart-Code/Dart-Code#1057]
I was creating an app and was able to run on my Pixel yesterday today went to run before I started editing and it kicked back. so I opened up a new flutter app to make sure it wasn't just me and it kicked back as well. 
[Dart-Code-Log2.txt](https://github.com/Dart-Code/Dart-Code/files/2160725/Dart-Code-Log2.txt)

**Comment by DanTup** [comment]
Looks like you've hit a bug in the analysis server :(

https://github.com/dart-lang/sdk/issues/33485

If your project is public, it may be worth sharing on that issue above so that it can be easily reproduced.

**Comment by gregrtardif** [comment]
How do I go about that? And what can I do to fix it?

**Comment by gregrtardif** [comment]
[https://github.com/gregrtardif/weatherproof ](url)

**Comment by DanTup** [comment]
I don't know if there's a way to workaround it before it's fixed. If you know what triggered it, maybe you can undo it. It looks pretty severe though, so hopefully it'll be fixed quickly.

**Comment by gregrtardif** [comment]
Thanks, I did uninstall dart and flutter and reinstalled them to no avail. I wish, I knew. same happens in android studio as well. 
3:49 PM	Dart Analyzer Error
				Encountered a Dart Analysis Server error.
				Open issue submission form?

**Comment by DanTup** [comment]
Can you ensure the code in GitHub matches what you're using to repro this exactly, and post the commit hash? It'll be easier to fix with an easy repro.

**Comment by DanTup** [comment]
Closing this as the issue is open in the SDK repo linked above. If you can provide me with a good repro though, I'm happy to do some investigation to see if I can help get it fixed.
