### ISSUE TITLE
Support auto-importing from code completion

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#1060]
Requires some work in the server first:

- https://github.com/dart-lang/sdk/issues/27220
- https://github.com/dart-lang/sdk/issues/25298
- https://github.com/dart-lang/sdk/issues/21931
- https://github.com/dart-lang/sdk/issues/25820

**Comment by DanTup** [comment]
> (@sandangel) I don't see typescript auto import has this performance issue although the number of files to scan in node_modules is much larger than dart package I think. I'm curious how did typescript team solve this problem.

> I don't see typescript auto import has this performance issue

I didn't say issue, just implication. It's possible they're pre-filtering server-side to return less traffic to the editor. I'm not saying it's a reason not to do it, just something to bear in mind (we've previously had perform issues when providing large amounts of data to VS Code, such as https://github.com/Microsoft/vscode/issues/51236).

> the number of files to scan in node_modules is much larger than dart package I think

It's not scanning the files I was referring to; the server is already doing that - it was the JSON serialisation/deserialisation and VS Code handling huge numbers of objects.

I don't think anything here is a blocking issue; just some things for us to bear in mind when implementing. It will need server support though so there's a little more to it than just adding a feature to Dart code (it needs to be non-breaking and the API changes need to be agreed/documented for all editors using the server).

I would like to see this, so I don't mind getting involved with the server changes if required; however there are other big jobs I'd rather tackle there than this (such as signature information, which has been near the top of my list of priorities forever!).

**Comment by fluxsaas** [comment]
for anyone else wondering, there is a solution in place:

You will see a bulb in line number , then click it or

press the shortcut ⌘ + . (Quick Fix)

that will pop up a import hint window , as follows

![Image of Quickfix](https://i.stack.imgur.com/JbDjr.png)

from: https://stackoverflow.com/a/43662512
