### ISSUE TITLE
Support Go-to-Implementation from call sites, not just definitions

### ISSUE THREAD

**Issue by charafau** [Dart-Code/Dart-Code#1064]
When I try to jump to method implementation from object, it says `No implementation for getMyMethod()` but I can jump to definition and form there jump to implementation

ex: Invoking jump to implementation on site, like something.myMethod() and trying to jump to myMethod() implementation.

**Comment by DanTup** [comment]
I've implemented this, though in Dart v1 I seem to not get all of the expected results (I've had to skip the test in Dart v1). Unless someone is hitting this for real I'm gonna merge as-is though; most people are using v2 (either via Flutter, or using a dev SDK) since v1 is so old.
