### ISSUE TITLE
Allow disabling showing the test runner automatically at the start of a test run

### ISSUE THREAD

**Issue by twistedinferno** [Dart-Code/Dart-Code#1076]
The test panel opens by default when a test is run in debug mode.  Is there a way to disable the test panel opening automatically when I run my test in debug mode?  I really love the new test panel but because I code on a laptop and only one instance of my project can be open at one time screen real estate is problem; therefore I need to close my test panel every time and I run a test in debug mode, which gets a bit repetitive.

Many thanks

**Comment by DanTup** [comment]
vNext has an option called `dart.openTestView` which will allow you to configure when to show the test view. It's an array so you can provide multiple options; the default is just on test start. You can set it to on failure, or an empty array to never show it automatically.

![screen shot 2018-07-10 at 4 16 33 pm](https://user-images.githubusercontent.com/1078012/42519858-d4dee924-845c-11e8-9996-c4233c997057.png)

**Comment by twistedinferno** [comment]
This is great 👍
