### ISSUE TITLE
When a package is imported via ctrl+. in split screen mode, another file opens in the left hand window

### ISSUE THREAD

**Issue by twistedinferno** [Dart-Code/Dart-Code#1078]
If you are editing a file in the right hand split screen window during split screen mode and ctrl+. to import a package automatically the same file will open in the left hand window.

To recreate problem
1. Open two different dart files
2. AltGr+right to view both files at the same time in a split window
3. Add code to dart file in the right split screen
4. Do ctrl+. to add a package reference and automatically insert the import statement
5. Observe that the same file gets open in the left hand window

I don't think this is expected behaviour (I couldn't recreate this in VSCode JS)

**Comment by DanTup** [comment]
I'm unable to reproduce this - are you able to give a screenshot and the exact code you're editing/quick-fix you're running?

Here's how I tested it:

![screen shot 2018-07-11 at 1 13 53 pm](https://user-images.githubusercontent.com/1078012/42570596-52d5c9f6-850c-11e8-8e1b-8865b72e88b2.png)

And here's what it looked like after running the quick-fix:

![screen shot 2018-07-11 at 1 14 02 pm](https://user-images.githubusercontent.com/1078012/42570612-5c62ee04-850c-11e8-97f8-49a526969203.png)

**Comment by DanTup** [comment]
We do have code here that calls `showTextDocument` but we don't specify the column, and the docs say:

> A view column in which the editor should be shown. The default is the active, other values are adjusted to be Min(column, columnCount + 1), the active-column is not adjusted. Use ViewColumn.Beside to open the editor to the side of the currently active one.

So it should always open where you active editor is.

Are you on the latest stable versions of VS Code and Dart Code? Do you have any other extensions that might do anything with open files/tabs/etc.?

**Comment by twistedinferno** [comment]
I was on the latest version of dart-code but one release behind of vsCode...updating to 1.25.0 fixed it for me (apologies, I thought I was on the latest VSCode)

@DanTup in your screenshot you have an 'open editors' section in your left hand panel.  I don't see that, I was showing two files by selecting AltGr + (right arrow).  How do you get the 'open editors' section?

Many thanks

**Comment by DanTup** [comment]
Glad it's solved! There were changes in 1.25 to do with the grid layout, so I wonder whether the behaviour for selecting the column was modified in that version and it was buggy (or less defined) before. vNext of Dart Code requires 1.25 so I won't worry about investigating if it seems fixed.

The `Open Editors` list is standard functionality - it shows your open editors. I'm sure it's visible by default, but you can toggle it by right-clicking at the top of the `Explorer` side bar panel or `View -> Open View -> Open Editors` :-)

**Comment by twistedinferno** [comment]
Thanks!  I just worked out the Open Editors...its available when I open individual folders but not when I open in folder view.  That might be handy to me though :-)

**Comment by DanTup** [comment]
Hmmm, I'm not sure why - it definitely appears for me when I open a folder normally - it's how I switch between my open files:

<img width="389" alt="screen shot 2018-07-12 at 8 13 11 am" src="https://user-images.githubusercontent.com/1078012/42617960-7e95f724-85ab-11e8-940f-fdde1f386a00.png">
