### ISSUE TITLE
Cannot Hot Restart, i get this notification "There is already a debug configuration "Flutter" running"

### ISSUE THREAD

**Issue by rajeshzmoke** [Dart-Code/Dart-Code#1085]
I'm on macOS, After starting debugging using `F5` i'm unable to initiate a Hot restart using the shortcut keys `ctrl+F5` / `^ F5`.. i get a notification at the bottom of Vscode  "There is already a debug configuration "Flutter" running"
<img width="528" alt="screen shot 2018-07-12 at 12 17 20 pm" src="https://user-images.githubusercontent.com/30038668/42625299-08ab65aa-85e5-11e8-9d02-41622efcc4c0.png">

But using the Command palette, i'm able to initiate the hot restart

**Comment by DanTup** [comment]
Can you confirm which version of VS Code and Dart Code you're on?

Could you also open your keybindings (`Preferences: Open Keyboard Shortcuts` command from palette), type `F5` into the search box and then post a screenshot?

It seems like for some reason when you're pressing `Ctrl+F5` it's trying to run the `Start Without Debugging` command; however the default keybind for this only applies when `!inDebugMode` so this seems strange (I can't repro):

<img width="1152" alt="screen shot 2018-07-12 at 10 49 29 am" src="https://user-images.githubusercontent.com/1078012/42626085-463878be-85c1-11e8-94fa-b81727fa7d64.png">

**Comment by rajeshzmoke** [comment]
Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2 (from`flutter doctor`)
Dart VM version: 1.24.3 (Wed Dec 13 23:26:59 2017) on "macos_x64" (`dart --version`)
Vscode Version 1.25.0 (1.25.0)
<img width="1440" alt="screen shot 2018-07-12 at 12 15 48 pm" src="https://user-images.githubusercontent.com/30038668/42628574-28374034-85ee-11e8-8107-74284278a9b1.png">

**Comment by DanTup** [comment]
Very strange :/ This seems like it might be a VS Code bug, but I'm not sure how - if you weren't in a debug session then Hot Restart wouldn't appear in the palette. Can you click Help -> Toggle Dev Tools and see if there's a stack trace?

Do you know if you have anything else (eg. extensions) that might affect keybindings?

**Comment by rajeshzmoke** [comment]
Help -> Toggle Dev Tools -> Console and saved the log, is this what you're asking? 
[-1531409538070.log](https://github.com/Dart-Code/Dart-Code/files/2189254/-1531409538070.log)
[-1531409538071.log](https://github.com/Dart-Code/Dart-Code/files/2189260/-1531409538071.log)

i don't use any additional Keybinding extensions (i dont even change the default bindings), i use whatever is there by default

**Comment by DanTup** [comment]
Hmmm, this is puzzling. I'll have to do some more digging.

Out of curiosity, do you have any other extensions installed at all (for ex., the VS Live Share one? That has to do some funky things to work and has broke a couple of things in the past).

**Comment by rajeshzmoke** [comment]
<img width="559" alt="screen shot 2018-07-13 at 11 29 33 am" src="https://user-images.githubusercontent.com/30038668/42675104-2ab8759c-8690-11e8-88a0-97b61c6d903a.png">
This is all the extensions i have installed

**Comment by SteveAlexander** [comment]
I'm seeing this too, in similar circumstances.

A workaround is to select "Flutter: Hot Restart" from the Command Palette (command+shift+P).

Strange that this would work when the shortcut key fails.

**Comment by DanTup** [comment]
I'm not really sure what's going on here. I've opened https://github.com/Microsoft/vscode/issues/54378 in the VS Code repo to hopefully get some help. Please 👍/subscribe to that issue.

**Comment by DanTup** [comment]
Are either of you able to test if this still occurs in the latest VS Code Insiders? There's a possible fix [see here](https://github.com/Microsoft/vscode/issues/54378#issuecomment-405575921) but since I can't repro in Stable I can't confirm if it helps.

**Comment by rajeshzmoke** [comment]
I tried with the VSC insider
`Version 1.26.0-insider (1.26.0-insider)`
I don't get the error notification anymore but instead it just restarts without Debugging..still not able to `Hot restart` with shortcut keys...but works from command palette

**Comment by DanTup** [comment]
Hmm strange. Just to confirm - just before you press this, you do see the floating Debug toolbar at the top was well as the Orange status bar, right?

**Comment by rajeshzmoke** [comment]
yes

**Comment by SteveAlexander** [comment]
I just tried with Version 1.26.0-insider.

I see no change from what I reported with the release of VSC. I still get the error notification, and no hot restart on ctrl+F5. And I can still hot restart from the command palette.

**Comment by DanTup** [comment]
Another change has been made, if you update to latest insiders:

https://github.com/Microsoft/vscode/issues/54378#issuecomment-406538939

Could you also try disabling all other extensions (you can choose `Disable for Workspace` so that the only disable for that one folder) just to eliminate any possibility they're interfering.

**Comment by SteveAlexander** [comment]
Just tried the latest insiders. No change.

**Comment by DanTup** [comment]
Doh, looks like the most recent changes were 5 changesets after that hash, so I guess it missed the last insiders build. There hasn't been a build since so I'd say try again later today or tomorrow.

**Comment by SteveAlexander** [comment]
Tried the latest again. Still no change.

Version: befea2253626b1918352df04477cae83eee618ac
2018-07-24T05:05:27.065Z

**Comment by DanTup** [comment]
Bah :(

I guess we need to try what's written [here](https://github.com/Microsoft/vscode/issues/54378#issuecomment-406538939)

> 1. Does your hot restart command get triggered?

I presume the answer here is no (you don't see a message in the Debug Console saying we hot reloaded, even though the error appeared?)


> 2. Does the Start Without Debugging get triggered (put a breakpoint [here](https://github.com/Microsoft/vscode/blob/0ef2155f02aa4bc77e97841fd63427819308ced7/src/vs/workbench/parts/debug/browser/debugActions.ts#L137))

I'm sure the answer to this is yes, since that message is appearing, but it's worth putting a breakpoint there to verify (see below).

> 3. If a wrong command is triggered we need to figure out why the contexts are not correct. For that put breakpoints [here](https://github.com/Microsoft/vscode/blob/f07a19895b50dd49f7250528eec80713a099cdd8/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L560) and check what is the last value that context is set to

Again, see below for adding breakpoints. This may get hit a few times, but if you make a note of the values, especially the last value that gets set after you start the debug session before you press Ctrl+F5.

** Setting a Breakpoint **

- Open VS Code
- Open dev tools (Help -> Toggle Developer Tools)
- Press `Cmd`+`P` for the file picker (not sure what the key combo is on Windows?)
- Enter the name of the `.ts` file(s) linked above
- Add a breakpoint to the referenced line (note: line numbers may be slightly different if the code he linked to isn't the same version as VS Code, so just set it on the code that looks the same around that area)

It may be worth posting the results directly in https://github.com/Microsoft/vscode/issues/54378 to avoid delays in me picking it up and posting back over there.

**Comment by rajeshzmoke** [comment]
Any improvements or fix on this?

**Comment by DanTup** [comment]
Check the linked VS Code bug above. This seems like it may be a VS Code issue, but the attempted fixes haven't worked so far.

**Comment by momoadeli** [comment]
Although I've been using this for weeks, this exact problem started happening to me today.

**Comment by DanTup** [comment]
I believe this has been fixed in VS Code by https://github.com/Microsoft/vscode/issues/57255. If anyone is able to repro this and wants to try it in Insiders, please post back to confirm.
