### ISSUE TITLE
Analyzer issues grouped by workspace folder

### ISSUE THREAD

**Issue by jimmyff** [Dart-Code/Dart-Code#1087]
I think it would be really useful if the analyzer issues/'Problems' tab were grouped by workspace folder (separate dart projects/packages) allowing me to collapse the ones that I'm not working on to hide it's problems. I think this would make it clearer to see the problems relating to the project you're currently working on and generally reduce clutter / noise.

**Comment by DanTup** [comment]
This would need to be implemented by VS Code; we don't get to control the rendering from an extension. Please raise [over here](https://github.com/Microsoft/vscode) and post the link back so people that find this issue can easily go and 👍 it :-)
