### ISSUE TITLE
incorrect warning: [dart] The asset assets/ does not exist.

### ISSUE THREAD

**Issue by SteveAlexander** [Dart-Code/Dart-Code#1090]
I'm using VC Code 1.25.1 with the Dart + Flutter extensions version 2.15.0.

In Flutter, it is possible to specify assets in the pubspec.yaml file either explicitly by the path to the file, or implicitly by giving an assets directory ending in a slash.

For example:
```
flutter:
  assets:
    - datafile.json
    - assets/
```

I don't think the Dart extension knows about this though, because I get a warning in the Problems panel like:  `warning: [dart] The asset assets/ does not exist.`

This is documented here: https://flutter.io/assets-and-images/#specifying-assets

Thanks!

**Comment by DanTup** [comment]
Thanks for the report! This warning comes from the analysis server which ships inside the SDK; whether it works depends on the version of the Flutter SDK you have. The current `master` branch should include the fix but `beta` does not (I'm not sure about `dev`).

Some more info about this, including a workaround until you get the fix are in here:

https://github.com/flutter/flutter/issues/4890#issuecomment-400405854
