### ISSUE TITLE
"Fatal signal 11" when running flutter app from visual studio code debug mode

### ISSUE THREAD

**Issue by abacaj** [Dart-Code/Dart-Code#1099]
I am experiencing a strange issue.

I see this error when trying to run my app in visual studio code:

```
F/libc    ( 4177): Fatal signal 11 (SIGSEGV), code 1, fault addr 0xb82c297c in tid 4193 (Thread-2)
Lost connection to device.
Exited (sigterm)
```

But when I run the flutter app with `flutter run` it runs correctly and never gets that error.

Anyone know what that means? I haven't been able to find a solution.

**UPDATE:**
Interestingly enough, when I run app with `ctrl+F5 (run without debugging)` it does not crash.
It seems to crash only when trying to run with debugging enabled `F5`

**Comment by DanTup** [comment]
This seems like a crash in Flutter. There have been some that only occur with a debugger attached which is why you don't see it with `flutter run`.

Can you post a note on https://github.com/flutter/flutter/issues/11227 and include the output of `flutter doctor -v`?
