### ISSUE TITLE
Intellisense on import/parts do not behave as expected

### ISSUE THREAD

**Issue by jrote1** [Dart-Code/Dart-Code#110]
There is no intellisense when adding part in a library file

**Comment by DanTup** [comment]
Closing this as there's nothing we (easily) do, will need fixing in the server.

**Comment by DanTup** [comment]
Probably makes sense to keep external issues open until they're dealt with to avoid duplicates being opened (and as a reminder that we're waiting on something else so we can prompt if it doesn't get done!).

**Comment by DanTup** [comment]
Related SDK case: https://github.com/dart-lang/sdk/issues/27020

**Comment by DanTup** [comment]
This was actually fixes age ago (not sure exactly which version, so guessing for the label).
