### ISSUE TITLE
Sync code outline to cursor position in editor

### ISSUE THREAD

**Issue by xster** [Dart-Code/Dart-Code#1102]
In the new Outline sidebar, clicking an outline item and having the code in the editor scroll works great. Being in a method in the editor and knowing where I am in the outline would be great. 

This is useful in Dart when a whole bunch of classes are in the same file and I can't tell whose method I'm currently in.

**Comment by DanTup** [comment]
This already exists, but maybe it's not on by default. Click the little dots in the Outline header and make sure "Follow Cursor" is ticked :)

![follow](https://user-images.githubusercontent.com/1078012/43025469-da702744-8c69-11e8-946f-5cdc97f1c661.png)

**Comment by DanTup** [comment]
If this doesn't work for you, re-open this and I'll investigate!

**Comment by xster** [comment]
Doh, I was looking at an entirely different sidebar item but turns out it came from another extension. My bad. The outline section of the Explorer works when I turn the follow cursor option on. 

Thanks
