### ISSUE TITLE
Don't use dart.sdkPath in preference to Flutter-shipped version of Dart for a Flutter project

### ISSUE THREAD

**Issue by bimbo1989** [Dart-Code/Dart-Code#1110]
Hi,
I'm getting an issue with the code.
I downloaded the example from VSCode running "Flutter: New Project" and it immediately marked as an error a part of code that Android Studio does not.
The incriminated part is
```
floatingActionButton: new FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: new Icon(Icons.add), //this line
      )
```

![errore_flutter](https://user-images.githubusercontent.com/1078012/43091359-cf97638e-8ea1-11e8-8805-0fe49d162a39.png)

It can't be an error because it compiles and runs just fine.
Also I get plenty of similar errors in another test project I made, errors I don't get in Android Studio.
Is there a way to solve this? Am I missing something? The debugger works fine.

I'm running VSCode x64 1.25.1 on Windows 10 Pro

**Comment by DanTup** [comment]
Hmm, that does seem weird (especially since Android Studio uses the same analysis server that Dart Code does).

Have you made any modifications from the `New Project` project at all? Can you confirm the versions of the Dart extension and of Flutter (it'll be shown in the status bar).

**Comment by bimbo1989** [comment]
No, no modifications at all. As default as it gets :)
Flutter SDK 0.5.1
Dart and Flutter extensions of VSCode both 2.16.0

**Comment by DanTup** [comment]
@bwilkerson @scheglov Ever seen anything like this? The FAB constructor takes `Widget`, but this warning is suggesting it wants a `Row`. It's Flutter beta so a little old now, but I don't know if that's related; I've not seen any reports of anything similar.

@bimbo1989 Can you try the following:

- Run the `Dart: Capture Logs` command (pick a filename, leave everything ticked)
- Open your `User Settings` file (there's a command for it)
- Add `"dart.closingLabels": false` and hit `Save` (this is just to force a server restart - we don't have an explicit way to do it but modifying certain settings will trigger it)
- Wait for analysis to finish and the error to appear
- Click the `Stop Logging` button

Attach the log or email it to logs@dartcode org.

**Comment by scheglov** [comment]
No, I have never seen anything like this.
Unless FAB was changed, or something else was imported instead of the standard one, it should work.

**Comment by DanTup** [comment]
@bimbo1989 Also, could you hover your mouse over the word `FloatingActionButton` in your code and attach a screenshot of the tooltip, and also then Go-to-Definition on it, and show what the signature of that constructor looks like?

**Comment by bimbo1989** [comment]
Hello,
[this](https://ibb.co/gsghOo) is the screenshot of the FloatingActionButton tooltip.

And this is the whole class code (I know that you only needed the signature but who knows 🙂 ).

I'll let you have the logs as soon as possible.

```
class FloatingActionButton extends StatefulWidget {
  /// Creates a circular floating action button.
  ///
  /// The [elevation], [highlightElevation], [mini], [notchMargin], and [shape]
  /// arguments must not be null.
  const FloatingActionButton({
    Key key,
    this.child,
    this.tooltip,
    this.foregroundColor,
    this.backgroundColor,
    this.heroTag: const _DefaultHeroTag(),
    this.elevation: 6.0,
    this.highlightElevation: 12.0,
    @required this.onPressed,
    this.mini: false,
    this.notchMargin: 4.0,
    this.shape: const CircleBorder(),
    this.isExtended: false,
  }) :  assert(elevation != null),
        assert(highlightElevation != null),
        assert(mini != null),
        assert(notchMargin != null),
        assert(shape != null),
        assert(isExtended != null),
        _sizeConstraints = mini ? _kMiniSizeConstraints : _kSizeConstraints,
        super(key: key);

  /// Creates a wider [StadiumBorder] shaped floating action button with both
  /// an [icon] and a [label].
  ///
  /// The [label], [icon], [elevation], [highlightElevation]
  /// [notchMargin], and [shape] arguments must not be null.
  FloatingActionButton.extended({
    Key key,
    this.tooltip,
    this.foregroundColor,
    this.backgroundColor,
    this.heroTag: const _DefaultHeroTag(),
    this.elevation: 6.0,
    this.highlightElevation: 12.0,
    @required this.onPressed,
    this.notchMargin: 4.0,
    this.shape: const StadiumBorder(),
    this.isExtended: true,
    @required Widget icon,
    @required Widget label,
  }) :  assert(elevation != null),
        assert(highlightElevation != null),
        assert(notchMargin != null),
        assert(shape != null),
        assert(isExtended != null),
        _sizeConstraints = _kExtendedSizeConstraints,
        mini = false,
        child = new Row(
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            const SizedBox(width: 16.0),
            icon,
            const SizedBox(width: 8.0),
            label,
            const SizedBox(width: 20.0),
          ],
        ),
        super(key: key);

  /// The widget below this widget in the tree.
  ///
  /// Typically an [Icon].
  final Widget child;

  /// Text that describes the action that will occur when the button is pressed.
  ///
  /// This text is displayed when the user long-presses on the button and is
  /// used for accessibility.
  final String tooltip;

  /// The default icon and text color.
  ///
  /// Defaults to [ThemeData.accentIconTheme.color] for the current theme.
  final Color foregroundColor;

  /// The color to use when filling the button.
  ///
  /// Defaults to [ThemeData.accentColor] for the current theme.
  final Color backgroundColor;

  /// The tag to apply to the button's [Hero] widget.
  ///
  /// Defaults to a tag that matches other floating action buttons.
  ///
  /// Set this to null explicitly if you don't want the floating action button to
  /// have a hero tag.
  ///
  /// If this is not explicitly set, then there can only be one
  /// [FloatingActionButton] per route (that is, per screen), since otherwise
  /// there would be a tag conflict (multiple heroes on one route can't have the
  /// same tag). The material design specification recommends only using one
  /// floating action button per screen.
  final Object heroTag;

  /// The callback that is called when the button is tapped or otherwise activated.
  ///
  /// If this is set to null, the button will be disabled.
  final VoidCallback onPressed;

  /// The z-coordinate at which to place this button. This controls the size of
  /// the shadow below the floating action button.
  ///
  /// Defaults to 6, the appropriate elevation for floating action buttons.
  final double elevation;

  /// The z-coordinate at which to place this button when the user is touching
  /// the button. This controls the size of the shadow below the floating action
  /// button.
  ///
  /// Defaults to 12, the appropriate elevation for floating action buttons
  /// while they are being touched.
  ///
  /// See also:
  ///
  ///  * [elevation], the default elevation.
  final double highlightElevation;

  /// Controls the size of this button.
  ///
  /// By default, floating action buttons are non-mini and have a height and
  /// width of 56.0 logical pixels. Mini floating action buttons have a height
  /// and width of 40.0 logical pixels.
  final bool mini;

  /// The margin to keep around the floating action button when creating a
  /// notch for it.
  ///
  /// The notch is an arc of a circle with radius r+[notchMargin] where r is the
  /// radius of the floating action button. This expanded radius leaves a margin
  /// around the floating action button.
  ///
  /// See also:
  ///
  ///  * [BottomAppBar], a material design elements that shows a notch for the
  ///    floating action button.
  final double notchMargin;

  /// The shape of the button's [Material].
  ///
  /// The button's highlight and splash are clipped to this shape. If the
  /// button has an elevation, then its drop shadow is defined by this
  /// shape as well.
  final ShapeBorder shape;

  /// True if this is an "extended" floating action button.
  ///
  /// Typically [extended] buttons have a [StadiumBorder] [shape]
  /// and have been created with the [FloatingActionButton.extended]
  /// constructor.
  ///
  /// The [Scaffold] animates the appearance of ordinary floating
  /// action buttons with scale and rotation transitions. Extended
  /// floating action buttons are scaled and faded in.
  final bool isExtended;

  final BoxConstraints _sizeConstraints;

  @override
  _FloatingActionButtonState createState() => new _FloatingActionButtonState();
}

```

**Comment by bimbo1989** [comment]
Just to be sure, you mean I should try and download the 0.5.7 dev sdk from [here](https://flutter.io/sdk-archive/#windows), right?

**Comment by DanTup** [comment]
You should be able to just run `flutter channel dev` and then `flutter upgrade`. See https://github.com/flutter/flutter/wiki/Flutter-build-release-channels

**Comment by bimbo1989** [comment]
Oook, ALMOST fixed.
Now I have no errors in all files, except one, where I still get the other error I got before on all files.
In a few words. I have to explicit the "new" keyword when creating an object.
The fun thing is that this problem is solved in all of the files, except one (that is simply a small class for making post calls that works fine when launched).

**Comment by bimbo1989** [comment]
No, wait.
Still problems 😅
Now, everytime I write a single character in the editor, VSCode gives me a warning "The Dart Analyzer has terminated", and it generates a huge log you can read [here](http://www.heypasteit.com/clip/0IJQ6A).

**Comment by DanTup** [comment]
Have you set the `config.sdkPath` setting in VS Code? It seems like the Dart SDK path is being overridden so it's not using the Flutter version:

```
Returning SDK path D:\Programmi\flutter for flutter.bat
[10:43:57 GMT 0200 (ora legale Europa occidentale)] [General] [Info] Searching for dart.exe
[10:43:57 GMT 0200 (ora legale Europa occidentale)] [General] [Info]     Looking in:
[10:43:57 GMT 0200 (ora legale Europa occidentale)] [General] [Info]         D:\Programmi\Dart\dart-sdk\bin
[10:43:57 GMT 0200 (ora legale Europa occidentale)] [General] [Info]         D:\Programmi\flutter\bin\cache\dart-sdk\bin
```

The only path we insert before the Flutter SDK path comes from `config.sdkPath`. Generally, you shouldn't override the Dart SDK location for Flutter projects (though I realise now sometimes people set this setting when working on non-Flutter Dart projects if the PATH search failed).

I think if you clear out `dart.sdkPath` in your VS User Settings (or Workspace Settings for that folde rif that's where it comes from) things should work better,

**Comment by bimbo1989** [comment]
Clearing both dart.sdkPath and dart.flutterSdkPath finally fixed the issue!
Sorry for wasting your time, I didn't think of looking at the VS User Settings.

**Comment by DanTup** [comment]
No worries, I think you've hit a legit issue. Setting `dart.sdkPath` has become more common due to all sorts of `PATH` issues (setting `PATH` so that it applies outside of the terminal turns out to be complicated on some OSes) so us using it ahead of the Flutter version is probably a bad idea. It was handy for me in the past for testing, but having them mismatch causes other issues anyway.

So, I'm going to use this issue as a task to stop prioritising `dart.sdkPath` over the embedded one. If anyone wants to change the Flutter Dart SDK version (which they almost certainly don't), they can rig it themselves internally.

Thanks for the help debugging; and do shout if you have any other issues!
