### ISSUE TITLE
Projects within projects

### ISSUE THREAD

**Issue by jimmyff** [Dart-Code/Dart-Code#1111]
If you use `package:firebase_functions_interop` it requires you to create a new dart project in `functions/`, I've also had this situation when I've shipped demos or example projects in a folder such as: `demo/`. VS Code really doesn't like this. I think it confuses the analyzer and also the VS Code tasks.  Could these somehow be better supported? Ideally they would be treated as separate projects entirely.

**Comment by DanTup** [comment]
There were changed in v2.16 to better support projects in sub-folders. If you're still having issues, please provide some specifics (or a repro project) so I can take a look.

**Comment by jimmyff** [comment]
So I was seeing packages available to the parent project within the child project. However I realised I was missing `analysis_options.yaml` in the child project which fixed it.

**Comment by DanTup** [comment]
Great, thanks for confirming and glad it's sorted! 👍

**Comment by jimmyff** [comment]
Okay I think I found one: `tasks.json` from a child project aren't indexed/available

**Comment by DanTup** [comment]
That one is a VS Code thing - I think it only loads them from workspace folders but I think I remember seeing an issue in their tracker about searching the tree. Dart Code doesn't do any scanning/parsing of any of the `.vscode` folder, everything is provided through APIs.

**Comment by jimmyff** [comment]
Ah okay, by chance do you know if there is a way to tell VS code to ignore a folder (dart analyzer, search indexing etc). That way I could ignore the sub folder and add the child project as a workspace folder?

**Comment by DanTup** [comment]
You can just add it as a workspace folder and it should work. You'll get it duplicated (it'll show at the top-level, and also in it's real position in the other workspace tree) but otherwise it should be handled fine.

There's an issue in the VS Code tracker about not duplicating a folder at the top level here:

https://github.com/Microsoft/vscode/issues/45470

Please 👍 it, as I think it'll make this work much better :)

**Comment by jimmyff** [comment]
Okay, will follow that issue. Thanks
