### ISSUE TITLE
Auto-complete indentation issue

### ISSUE THREAD

**Issue by xster** [Dart-Code/Dart-Code#1112]
![jul-23-2018 18-14-31](https://user-images.githubusercontent.com/156888/43111094-547e2c16-8ea4-11e8-9d75-81d8683ab04a.gif)

I'm using the method override auto-complete feature. The indentation past the first line is incorrect though.

**Comment by DanTup** [comment]
This seems like a dupe of #584/#700/#947 which I believe is a bug in Code. I've opened Microsoft/vscode#44200 but it's not had much traffic (seems like you've already 👍'd it!).

I'll add another comment to it so someone gets a ping to see if it's going to be looked at.
