### ISSUE TITLE
Dart stays 99% cpu all the time

### ISSUE THREAD

**Issue by greatGregLiu** [Dart-Code/Dart-Code#1114]
Since I installed Futter and Dart plugin, everytime I open vscode Dart stays 99% of cpu and fans go crazy. The computer goes very hot. At the end I can't use Vscode with Flutter.

Webstorm with flutter is ok though.

<img width="606" alt="2018-07-24 10 36 46" src="https://user-images.githubusercontent.com/12220010/43113630-bae56a9e-8f2d-11e8-8317-5f1539582b35.png">

<img width="611" alt="2018-07-24 10 45 03" src="https://user-images.githubusercontent.com/12220010/43113845-b08efec4-8f2e-11e8-8d5d-395ff89a8705.png">

Any ideas to resolve this problem? thanks.

**Comment by DanTup** [comment]
Can you run `ps <pid> -w -w` (where `<pid>` is one of the troublesome Dart processes) to get the full command line for the process (we may spawn multiple depending on your project).

Also can you confirm the size of the project you're opening in VS Code? Is it something large?

If you set the [`dart.analyzerLogFile`](https://dartcode.org/docs/logging/#analyzer) setting, that will generate a log file that might show whether or not analysis is getting stuck (not completing) too.

**Comment by greatGregLiu** [comment]
Just found the solution. I used to put flutterApp folders into VSCode Workspace which means any flutter app folder is under the name of workspace "XXXX". I guess it causes some problem on how flutter works on these folders (In each folder is a project). I open the flutter app folder directly in VSCode. It works without any problem now!

Thanks @DanTup for the great work!

**Comment by DanTup** [comment]
Everything should work fine even with workspace folders - I use them when working on Flutter:

<img width="327" alt="screen shot 2018-07-24 at 11 03 36 am" src="https://user-images.githubusercontent.com/1078012/43131560-3f9c7c8e-8f31-11e8-8116-514244a928bd.png">

If you can provide more info about the structure and a log, I'd love to try and resolve it - no matter what you do, we shouldn't leave you with a process consuming your machine.

**Comment by greatGregLiu** [comment]
The following messages might help? 

1.$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.4 17E199, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
[✓] Android Studio (version 3.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.5)
[!] VS Code (version 1.25.1)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.



2.when I click "Run Code" button. It got this message:

[Running] dart "/Users/gregliu/data/src/git.coding.net/greatLIU/sbt-App/lib/main.dart"
The built-in library 'dart:ui' is not available on the stand-alone VM.
'package:flutter/src/material/animated_icons.dart': error: line 9 pos 1: library handler failed
import 'dart:ui' as ui show Paint, Path, Canvas;
^

[Done] exited with code=254 in 0.199 seconds

**Comment by DanTup** [comment]
@greatGregLiu The most useful thing initially would be the command line args so we can tell which Dart process is consuming the CPU (it's likely the analysis one, but we should check):

> Can you run ps <pid> -w -w (where <pid> is one of the troublesome Dart processes) to get the full command line for the process (we may spawn multiple depending on your project).

Also an analysis log file and some info about the structure of your project as mentioned above would help.

This error:

> The built-in library 'dart:ui' is not available on the stand-alone VM.

Happens when you try to run Flutter code on the Dart VM. This happens if the root if your flutter project is not a workspace folder in VS Code, so we don't detect it as Flutter correctly. We should handle projects in sub-folders reasonable well now though, so if you can open a new issue about that one with some details about the structure of your open folder, we can investigate.

**Comment by greatGregLiu** [comment]
$ ps 75525 -w -w
  PID   TT  STAT      TIME COMMAND
75525   ??  S      1:17.26 /Users/gregliu/Downloads/flutter/bin/cache/dart-sdk/bin/dart /Users/gregliu/Downloads/flutter/bin/cache/flutter_tools.snapshot daemon



$ ps 75506 -w -w
  PID   TT  STAT      TIME COMMAND
75506   ??  S      0:24.21 /Users/gregliu/Downloads/flutter/bin/cache/dart-sdk/bin/dart /Users/gregliu/Downloads/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --client-id=Dart-Code.dart-code --client-version=2.16.0

**Comment by chengzixian** [comment]
@DanTup I also encountered the same problem, which is caused by the workspace of the CPU 100%, using a separate folder to solve, which puzzled me for a long time.

**Comment by DanTup** [comment]
@chengzixian if you can reproduce this, please open a new issue so we can collect some info to understand what it is (please include the output of `code --status` in a terminal while it's happening, so we can see which process(es) are consuming the CPU).

**Comment by JCzz** [comment]
Same problem

code --status:

```
Version:          Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS Version:       Darwin x64 19.0.0
CPUs:             Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)
Memory (System):  8.00GB (0.29GB free)
Load (avg):       7, 7, 8
VM:               0%
Screen Reader:    no
Process Argv:     /Users/<user>/Development/projects/weekcan/app.code-workspace
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  multiple_raster_threads:       enabled_on
                  native_gpu_memory_buffers:     enabled
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_deferred_display_list:    disabled_off
                  skia_renderer:                 disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  enabled
                  viz_display_compositor:        disabled_off
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %	Mem MB	   PID	Process
    0	    66	   799	code main
    0	    25	   800	   gpu-process
    0	    82	   802	   window (app.dart — app (Workspace))
    0	    33	   805	     extensionHost
    0	    16	   825	       electron_node server.js 
   85	   147	   827	       /Users/<user>/Development/tools/sdk/flutter/bin/cache/dart-sdk/bin/dart /Users/<user>/Development/tools/sdk/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --client-id=Dart-Code.dart-code --client-version=3.5.1
    0	     0	   828	       bash /Users/<user>/Development/tools/sdk/flutter/bin/flutter daemon
    0	    57	   842	         /Users/<user>/Development/tools/sdk/flutter/bin/cache/dart-sdk/bin/dart --packages=/Users/<user>/Development/tools/sdk/flutter/packages/flutter_tools/.packages /Users/<user>/Development/tools/sdk/flutter/bin/cache/flutter_tools.snapshot daemon
    0	     0	   806	     /bin/zsh -l
    0	    16	   809	     watcherService
    0	    16	   813	     searchService
    0	    41	   810	   shared-process
    0	     0	  3199	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=

Workspace Stats: 
|  Window (app.dart — app (Workspace))
|    Folder (flutter): 0 files
|      File types:
|      Conf files:
|    Folder (working): 5 files
|      File types: DS_Store(2) gitmodules(1)
|      Conf files:
|    Folder (weekcan): more than 22251 files
|      File types: go(5699) sample(902) info(346) md(336) lock(264) dart(225)
|                  DS_Store(219) mod(199) png(197) yaml(152)
|      Conf files: makefile(22) launch.json(12) settings.json(5) tasks.json(5)
|                  package.json(1) tsconfig.json(1) tslint.json(1)
|      Launch Configs: PowerShell(2)
|    Folder (app): 1587 files
|      File types: png(165) dart(150) h(107) plist(60) java(36) m(30) md(29)
|                  gradle(28) json(25) xml(25)
|      Conf files: launch.json(2)
|      Launch Configs: dart



```

**Comment by DanTup** [comment]
@JCzz can you reproduce this on-demand? Does the status bar in VS Code show "analyzing" while this is happening, or does it persist after that completes (assuming it completes).

Can you reproduce it on other projects or does it only happen when you open this workspace? If only this workspace, does it happen for any if you open each of those folders individually, or only with that combination?

Could you also confirm which version of Flutter you're on (`flutter --version`)?

Thanks!

**Comment by yuyi012** [comment]
same problem:

PID   TT  STAT      TIME COMMAND
  575   ??  R      5:38.85 /Users/yuyi/development/flutter/bin/cache/dart-sdk/bin/dart /Users/yuyi/development/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --client-id=Dart-Code.dart-code --client-version=3.7.0

It seem dart analysis is running for a long time, and vscode dart pragma completion is not working until the analysis service is done.

**Comment by DanTup** [comment]
@yuyi012 thanks for the info - are you able to answer the questions from the [comment above](https://github.com/Dart-Code/Dart-Code/issues/1114)? Thanks!

**Comment by yuyi012** [comment]
> @yuyi012 thanks for the info - are you able to answer the questions from the [comment above](https://github.com/Dart-Code/Dart-Code/issues/1114)? Thanks!

<img width="721" alt="屏幕快照 2019-12-10 下午3 39 06" src="https://user-images.githubusercontent.com/1808716/70505574-49ace000-1b63-11ea-9219-62268e3d92c5.png">

Every flutter workspace can cause this. Moreover when I can open two flutter workspace, there are two dart processes cpu high.
![屏幕快照 2019-12-10 下午3 42 21](https://user-images.githubusercontent.com/1808716/70505731-adcfa400-1b63-11ea-8373-22e2c08410aa.png)

It sometimes works fine, but when I run  ### **flutter pub get**  then the cpu high comes.

**Comment by yuyi012** [comment]
> @yuyi012 thanks for the info - are you able to answer the questions from the [comment above](https://github.com/Dart-Code/Dart-Code/issues/1114#issuecomment-545909846)? Thanks!

When the cpu percent is hight, code format and completions doesn't work at all. I can't code anything without them.

**Comment by DanTup** [comment]
Thanks - a few more:

- Can you reproduce it on a small sample created with `flutter create`, or does it only happen on your other projects?
- How long does it stay high for?
- Could you capture an [analysis server instrumentation log](https://dartcode.org/docs/logging/#analyzer-instrumentation)? (note: this log file may include parts of your source code)
- How big is the folder you're opening in VS Code? Is it just the Flutter project, or are you opening a much larger folder? Might there by any symlinks that point outside of the folder?

> Moreover when I open two flutter workspace, there are two dart processes cpu high.

Having two processes is normal. Separate VS Code instances get their own extension hosts, so we can't share processes. It's usually better to open multiple folders in a single VS Code window (using `File -> Add Folder to Workspace` to create a "multi-root workspace").

High CPU can also be normal while it's busy - but it shouldn't take too long (depending on the size of your project).

**Comment by yuyi012** [comment]
> Thanks - a few more:
> 
> * Can you reproduce it on a small sample created with `flutter create`, or does it only happen on your other projects?
> * How long does it stay high for?
> * Could you capture an [analysis server instrumentation log](https://dartcode.org/docs/logging/#analyzer-instrumentation)? (note: this log file may include parts of your source code)
> * How big is the folder you're opening in VS Code? Is it just the Flutter project, or are you opening a much larger folder? Might there by any symlinks that point outside of the folder?
> 
> > Moreover when I open two flutter workspace, there are two dart processes cpu high.
> 
> Having two processes is normal. Separate VS Code instances get their own extension hosts, so we can't share processes. It's usually better to open multiple folders in a single VS Code window (using `File -> Add Folder to Workspace` to create a "multi-root workspace").
> 
> High CPU can also be normal while it's busy - but it shouldn't take too long (depending on the size of your project).

- It works fine on some small demo project. But when I open my company project, it's reproduced.
- It stays for hours, a fews days ago it stays for about half an hour. But today it has stay for two hours.
- The log is attached. But there is only one line. It seems get stuck and unable to log anymore.
[analyzerInstrumentation.txt](https://github.com/Dart-Code/Dart-Code/files/3943687/analyzerInstrumentation.txt)
- The company project doesn't contain other things. It has 15+ flutter plugin sub project in it. And it relies on 30+ third party plugins.

**Comment by DanTup** [comment]
Can you run `code --status` from a terminal while you have the company project open and post the output here?

Could you also check if there are symlinks in the folder (eg. something like `find . -type l -ls`) that might be causing cycles?

**Comment by yuyi012** [comment]
> Can you run `code --status` from a terminal while you have the company project open and post the output here?
> 
> Could you also check if there are symlinks in the folder (eg. something like `find . -type l -ls`) that might be causing cycles?

Finally, I got this problem resolved. 
Re install the mac os system.
Flutter analysis work fine in the same company project.

**Comment by DanTup** [comment]
That seems like an extreme fix, but I'm glad you got it sorted! If it happens to come back, please do let me know so we can try and understand what was happening (and try the things above - checking for symlinks and getting `code --status`). Thanks!

**Comment by yuyi012** [comment]
> That seems like an extreme fix, but I'm glad you got it sorted! If it happens to come back, please do let me know so we can try and understand what was happening (and try the things above - checking for symlinks and getting `code --status`). Thanks!

I have found the reason for this issue.
There is an encryption software installed on my mac, it is required in the corporate institutions.
The encryption software runs whole directory and files scan sometimes.

I use mac time machine to backup my mac system, the flutter analysis works fine when I recovered from time machine. But once I login into the encryption software. The dart 99% issue comes again.

**Comment by DanTup** [comment]
@yuyi012 out of interest, are you able to provide any details on which encryption software you're using that's causing this?

**Comment by nkoroste** [comment]
I'm experiencing the same issue and I don't even have an active dart/flutter project open in either vscode nor android studio

**Comment by DanTup** [comment]
@nkoroste please open a new issue and if possible include the full command line of the Dart process that is consuming CPU. Thanks!

**Comment by nkoroste** [comment]
https://github.com/Dart-Code/Dart-Code/issues/2219

**Comment by easazade** [comment]
i'm still facing this issue. making coding basically a pain. doesn't matter which version of Flutter i run or what device i use to run my app. same result. after like half an hour of coding vs code consumes like 40 percent of my cpu. and delay in typing starts.

here is the result of `code --status`

```
$ code --status

Version:          Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS Version:       Windows_NT x64 10.0.18363
CPUs:             Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz (8 x 2195)
Memory (System):  15.92GB (8.41GB free)
VM:               0%
Screen Reader:    no
Process Argv:     --crash-reporter-id 2555c6bd-61eb-417c-a68c-23d5829cf155
GPU Status:       2d_canvas:                  enabled
                  flash_3d:                   enabled
                  flash_stage3d:              enabled
                  flash_stage3d_baseline:     enabled
                  gpu_compositing:            enabled
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          disabled_off
                  opengl:                     enabled_on
                  protected_video_decode:     unavailable_off
                  rasterization:              enabled
                  skia_renderer:              disabled_off_ok
                  video_decode:               enabled
                  vulkan:                     disabled_off
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %   Mem MB     PID  Process
    0       62   10484  code main
    1      119    3000     gpu-process
    0       10    8076     crashpad-handler
    0       63    8768     shared-process
    8      216   14740     window (trainer_edit_profile_page.dart - matjoy_app - Visual Studio Code)
    0       22    5388       searchService
    0        6    8560       console-window-host (Windows internal process)
    0       15   11396       watcherService
    0        6   14036         console-window-host (Windows internal process)
   21      868   12412       extensionHost
    0        3    2112         C:\WINDOWS\system32\cmd.exe /d /s /c ""C:\flutter_dev\bin\flutter.bat" "daemon""
    0      164    1992           "C:\flutter_dev\bin\cache\dart-sdk\bin\dart.exe"  --disable-dart-dev --packages="C:\flutter_dev\packages\flutter_tools\.packages"  "C:\flutter_dev\bin\cache\flutter_tools.snapshot" "daemon"
    0        6    3372           console-window-host (Windows internal process)
    0       22    3804         electron_node languageserver.js
    0        3    5108         C:\WINDOWS\system32\cmd.exe /d /s /c ""C:\flutter_dev\bin\cache\dart-sdk\bin\dart.exe" "C:\flutter_dev\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot" "--client-id=VS-Code" "--client-version=3.18.0""
    0        6    9380           console-window-host (Windows internal process)
   18     1208   13348           "C:\flutter_dev\bin\cache\dart-sdk\bin\dart.exe"  "C:\flutter_dev\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot" "--client-id=VS-Code" "--client-version=3.18.0"
    0       30   14052         electron_node server.js
    0       34   15048         electron_node debug.js
    0        3   14928           C:\WINDOWS\system32\cmd.exe /d /s /c ""C:\flutter_dev\bin\flutter.bat" "run" "--machine" "--target" "lib\main.dart" "-d" "windows" "--dart-define=flutter.inspector.structuredErrors=true" "--start-paused" "--web-server-debug-protocol" "ws" "--web-server-debug-backend-protocol" "ws" "--web-allow-expose-url""
    0        6    6820             console-window-host (Windows internal process)
    0       96    8368             "C:\flutter_dev\bin\cache\dart-sdk\bin\dart.exe"  --disable-dart-dev --packages="C:\flutter_dev\packages\flutter_tools\.packages"  "C:\flutter_dev\bin\cache\flutter_tools.snapshot" "run" "--machine" "--target" "lib\main.dart" "-d" "windows" "--dart-define=flutter.inspector.structuredErrors=true" "--start-paused" "--web-server-debug-protocol" "ws" "--web-server-debug-backend-protocol" "ws" "--web-allow-expose-url"
    0      472    2992               C:\flutter_dev\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\flutter_dev\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\flutter_dev\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -Ddart.developer.causal_async_stacks=true -Dflutter.inspector.structuredErrors=true --output-dill C:\Users\easa\AppData\Local\Temp\flutter_tools.20eacb1\flutter_tool.a6fa1d90\app.dill --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --initialize-from-dill build\f872507f30e2ff2523f0f1d19160266e.cache.dill.track.dill
    5      813   16060               C:\workspace\flutter\projects\matjoy_app\build\windows\runner\Debug\matjoy_app.exe
    0        4   14264       "C:\Program Files\Git\bin\bash.exe"
    0        9   11460         "C:\Program Files\Git\bin\..\usr\bin\bash.exe"
    0       23   15180     utility

Workspace Stats:
|  Window (trainer_edit_profile_page.dart - matjoy_app - Visual Studio Code)
|    Folder (matjoy_app): 18049 files
|      File types: xml(3516) flat(1955) json(1782) class(798) png(421)
|                  dex(283) dart(270) ttf(226) txt(190) jar(188)
|      Conf files: cmake(9) sln(3) launch.json(1)
|      Launch Configs: dart
```

**Comment by DanTup** [comment]
@easazade Are you able to share a project that reproduces this? (Please file a new issue for it as this one is closed). Also, it's worth testing if it reproduces with the LSP Preview enabled, as there are some performance improvements when using LSP. Thanks!

**Comment by easazade** [comment]
> @easazade Are you able to share a project that reproduces this? (Please file a new issue for it as this one is closed). Also, it's worth testing if it reproduces with the LSP Preview enabled, as there are some performance improvements when using LSP. Thanks!

thanks, I created a new issue [here](https://github.com/Dart-Code/Dart-Code/issues/3037). I'm going to enable LSP preview and see what happens. I post the result there. I can't share the project here since it's client's. although I think I can send you something, of course only if you are interested to look at it

**Comment by malikjaved** [comment]
> > @yuyi012 thanks for the info - are you able to answer the questions from the [comment above](https://github.com/Dart-Code/Dart-Code/issues/1114)? Thanks!
> 
> <img alt="屏幕快照 2019-12-10 下午3 39 06" width="721" src="https://user-images.githubusercontent.com/1808716/70505574-49ace000-1b63-11ea-9219-62268e3d92c5.png">
> 
> Every flutter workspace can cause this. Moreover when I open two flutter workspace, there are two dart processes cpu high. ![屏幕快照 2019-12-10 下午3 42 21](https://user-images.githubusercontent.com/1808716/70505731-adcfa400-1b63-11ea-8373-22e2c08410aa.png)
> 
> It sometimes works fine, but when I run ### **flutter pub get** then the cpu high comes.

I was facing the same issue. When i checked in Activity monitor, There were 2 instances of Dart running. I force quit both instances of dart, closed VS Code and opened VS Code again! Issue was resolved.

**Comment by malikjaved** [comment]
I was facing the same issue. When i checked in Activity monitor, There were 2 instances of Dart running. I force quit both instances of dart, closed VS Code and opened VS Code again! Issue was resolved.
