### ISSUE TITLE
Do not pause PubTest debugger on exceptions in the pub isolate

### ISSUE THREAD

**Issue by bergwerf** [Dart-Code/Dart-Code#1117]
Continuing on https://github.com/Dart-Code/Dart-Code/issues/1105, I think it would be useful if the PubTest debugger does not pause on uncaught exceptions that occur in the pub isolate when setting 'All exceptions'. I think that most of the time a developer is interested in all exceptions inside the project.

**Comment by DanTup** [comment]
I think we can fix this by not sending `setExceptionPauseMode` to the pub isolate?

**Comment by DanTup** [comment]
Got a PR for this at https://github.com/Dart-Code/Dart-Code/pull/1260, just waiting for some sanity checking.
