### ISSUE TITLE
Uri does not exists 'package:shared_preferences/shared_preferences.dart' in flutter

### ISSUE THREAD

**Issue by sixscorpions** [Dart-Code/Dart-Code#1131]
import 'package:shared_preferences/shared_preferences.dart';

pubspec.yaml
dependencies:
  flutter:
    sdk: flutter
    shared_preferences: ^0.4.2

**Comment by DanTup** [comment]
Can you try funning `Flutter: Get Packages` from the command palette and see whether any errors are reported in the Debug Console?

**Comment by DanTup** [comment]
I'm unable to investigate this with more details as mentioned above so I'm going to close it. I'm happy to reopen it if you can provide some additional info.
