### ISSUE TITLE
New 'Inpect Widget' command jumps too deep into the Widget  hierarchie

### ISSUE THREAD

**Issue by escamoteur** [Dart-Code/Dart-Code#1136]
When reading about the new Inpect Widget function I was thrilled first but when test I was quite disappointed to realize that it has only limited usefullness because it jumps into the source far too deep into the widget hierarchie int the Flutter framework instead showing me the widget inside my project.

So jumps tapping on a FAB here:

![image](https://user-images.githubusercontent.com/16635729/43673797-11f41b34-97c9-11e8-88f3-e57449033210.png)

Which might be helpful if you want to debug into the framework but not if you focus on your own App.

So unless we get a whole treeview from this Widget upwards this function is only of limited help.

**Comment by DanTup** [comment]
It shouldn't step into any framework code, it should only consider your own code.

Are you able to capture an Observatory log for this? Also - do you happen to have the Flutter framework code open as part of your workspace?

**Comment by DanTup** [comment]
This turned out to be https://github.com/flutter/flutter-intellij/issues/2217. I've put a workaround in that should fix this, and I'll put a note on that issue to find out if the fix will be non-breaking.

**Comment by DanTup** [comment]
Please try the fix out in v2.18.0 Beta 1:

https://github.com/Dart-Code/Dart-Code/releases/tag/v2.18.0-beta.1
