### ISSUE TITLE
Enable asserts by default in Dart VM debugger

### ISSUE THREAD

**Issue by bergwerf** [Dart-Code/Dart-Code#1143]
This is just a suggestion, I think asserts were always turned on before (in checked mode), but some things changed and today I found myself wondering why something was not detected earlier by asserts only to realize I had to add an `--enable-asserts` flag to my launch configuration (PubTest does enable asserts by default).

P.S. Please do not feel pressured by my issues :). I love your work, this extension is one of the reasons I enjoy programming in Dart so much! I suppose this is not a very high priority thing since most people are not debugging vm applications.

**Comment by DanTup** [comment]
I think this makes total sense. We used to use checked mode by default, and this did catch me out a while ago and I meant to come back to it. It seems intuitive to create an empty program with `assert(1==2)` and have it not fail even when debugging!

Glad you like the extension, and do keep raising issues even if they just seem like little niggles - I don't write enough Dart myself to know all of the things that bug people, and I'd like very much to minimise those things!
