### ISSUE TITLE
Data Inspection: Variable - Please sort list values by index number, not alphabetically.

### ISSUE THREAD

**Issue by rootext** [Dart-Code/Dart-Code#1147]
Steps to reproduce:
1. Debug application and move cursor over list variable
2. List values are sorted as [0],[10],[11],...,[1],[2],...

Expected: List values are sorted as [0],[1],...,[9],[10],[11]

![image](https://user-images.githubusercontent.com/1571180/44090693-c67a4206-9fd3-11e8-9ba8-8e0f687c29d2.png)

**Comment by DanTup** [comment]
Please try the fix out in v2.18.0 Beta 1:

https://github.com/Dart-Code/Dart-Code/releases/tag/v2.18.0-beta.1

**Comment by rootext** [comment]
Works. Thank you.

**Comment by DanTup** [comment]
Great, thanks for confirming! :-)
