### ISSUE TITLE
Data Inspection: Variable - Object inspection is empty or has random fields

### ISSUE THREAD

**Issue by rootext** [Dart-Code/Dart-Code#1148]
Steps to reproduce:

1. Add `Object o = new Object()` variable and Debug application
2. Open Debug -> Variables and expand the variable
3. It has random field inside (every time new):
![image](https://user-images.githubusercontent.com/1571180/44091947-bb6ee480-9fd7-11e8-99c2-36928af69254.png)
Expected: Variable has no fields.

4. Move cursor over Object variable in Editor
5. Data Inspection Popup is empty
![image](https://user-images.githubusercontent.com/1571180/44091995-dd9b4382-9fd7-11e8-8657-0f9977d6e55c.png)
Expected: Title is _Instance of Object_ or something like that

**Comment by rootext** [comment]
@DanTup, It isn't reproduced with SDK 2.0.0-dev.54.0 but reproduced with SDK 2.0.0-dev.69.5 and 2.0.0 (stable)

**Comment by DanTup** [comment]
It's 2.0.0 stable that I'm testing with. Can you share a complete code example and capture an Observatory log? Here's what I tried:

<img width="684" alt="screen shot 2018-08-14 at 14 26 34" src="https://user-images.githubusercontent.com/1078012/44094465-24713f3c-9fce-11e8-9a4c-a5d7d6c81458.png">

<img width="229" alt="screen shot 2018-08-14 at 14 27 22" src="https://user-images.githubusercontent.com/1078012/44094478-319b0cd8-9fce-11e8-85b6-644c5d6eac27.png">

**Comment by rootext** [comment]
Exactly the same code. Expand o.
![image](https://user-images.githubusercontent.com/1571180/44095317-2dceb8bc-9fe1-11e8-90d6-883bfd4d1ebb.png)

[Dart-Code-Log-2018-07-02 16-41.txt](https://github.com/Dart-Code/Dart-Code/files/2287133/Dart-Code-Log-2018-07-02.16-41.txt)

**Comment by DanTup** [comment]
Hmm, nothing obvious in the logs - but there are some expression evaluation errors that I don't see here. I'm on macOS here, so I'll do some testing on Windows when I'm at a PC. I presume there aren't any interesting errors/warnings in the developer console (Help -> Toggle Developer Tools)?

**Comment by rootext** [comment]
There is
`console.ts:136 [Extension Host] {"code":113,"message":"Expression compilation error","data":{"details":"NoSuchMethodError: The getter 'className' was called on null.\nReceiver: null\nTried calling: className\n#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)\n#1      serializeProcedure (package:front_end/src/fasta/kernel/utils.dart:82)\n#2      _processExpressionCompilationRequest (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/vm/bin/kernel_service.dart:296)\n<asynchronous suspension>\n#3      _processLoadRequest (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/vm/bin/kernel_service.dart:367)\n<asynchronous suspension>\n#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)\n"}}`
I can check on Linux too in few hours.

**Comment by DanTup** [comment]
Yeah, that's the error in the logs that I didn't expect (and don't see here). Don't think it's the cause of this though.

In any case, inexplicably, I can now repro this somewhat!

<img width="519" alt="screen shot 2018-08-14 at 15 42 05" src="https://user-images.githubusercontent.com/1078012/44098667-b495f22e-9fd8-11e8-9a5e-1b74f97f2e20.png">

Seems to always be `o` in my testing. I'll see what I can find (though might not be till next week, I'm on vacation this week). Thanks for the info!

**Comment by rootext** [comment]
As I can see, this field depends on code, which was run before. Like random field from random object  in memory?

Thank you. Enjoy vacation.

**Comment by DanTup** [comment]
Ah yes, that makes sense. When we get variables back we stash them in a list and provide the index to VS Code (`variablesReference`), and then later when it asks us for the variable by index, we can give it back. Something must be going bad here such that we're ending up with a bad index, so we're reading some other variable.

**Comment by DanTup** [comment]
I believe this may be a VS Code issue - I've opened an issue at https://github.com/Microsoft/vscode/issues/56996. I'll keep this one open for now in case it turns out we're doing something wrong.

**Comment by rootext** [comment]
@DanTup It seems it is fixed. It isn't reproduced in VS 1.37.1

**Comment by DanTup** [comment]
Great! Looks like I was supposed to do some digging, but it slipped through the net. I think they moved over to a new tree implementation since we opened that, so maybe that resolved these quirks. If you do see it again, please let me know and I can do some more digging. Thanks!
