### ISSUE TITLE
Searcheable debug console

### ISSUE THREAD

**Issue by xster** [Dart-Code/Dart-Code#1150]
Might not be doable but worth a try.

F5 in widget tests outputs to the debug console. Sometimes, to debug tests, one would run debugDumpApp or some such to print the whole tree but it's hard to find what one's looking for without search and debug console doesn't search.

**Comment by DanTup** [comment]
It's not super discoverable, but if you click on a test in the tree on the left, we also create an Output channel and write its output there. If you put focus in there and hit Ctrl+F you should get a search box:

<img width="1385" alt="screen shot 2018-08-14 at 22 06 01" src="https://user-images.githubusercontent.com/1078012/44118511-4c93d98a-a00e-11e8-8dc4-f88aa205540a.png">

**Comment by DanTup** [comment]
@xster Does this satisfy your need?

**Comment by DanTup** [comment]
@xster ping!

**Comment by DanTup** [comment]
If the above isn't sufficient, lmk and we can discuss :-)
