### ISSUE TITLE
Add possibility to pass env variables to debug script

### ISSUE THREAD

**Issue by enyo** [Dart-Code/Dart-Code#1151]
In the `launch.json`, setting an `env` argument yields: "Property env is not allowed". To run some dart scripts, it's necessary to pass ENV variables to it, so it would be great to support this.

**Comment by DanTup** [comment]
There's an ad-hoc build with this implemented for the VM here:

https://github.com/Dart-Code/Dart-Code/releases/tag/v2.18.0-alpha.1.env

I'll merge and ship properly in the next release.

**Comment by DanTup** [comment]
v2.18.0 Beta 1 includes this fix (and others):

https://github.com/Dart-Code/Dart-Code/releases/tag/v2.18.0-beta.1
