### ISSUE TITLE
Default directory for running tests is not the root directory

### ISSUE THREAD

**Issue by liboz** [Dart-Code/Dart-Code#1156]
Currently, when running `flutter test`, one has to run it in the root directory of a Flutter project, but the working directory when running the test is the directory of the test file. When running tests through Dart-Code via the GUI interface in the code/Running tests inside VS Code in general, the working directory is instead the root directory.

Repro Steps: 
1. Create a new Flutter project called `testing` in VS Code via the command palette.
2. In the default `widget_test.dart` file created, import `dart:io`  and add the following print statement inside the default test `print(Directory.current);`
3. Run the test inside VS Code either through the circled `Run` button 
![code_2018-08-16_21-36-35](https://user-images.githubusercontent.com/13482895/44243374-c82a8500-a19c-11e8-90fc-d4c7fd1bf6f8.png) or from the panel on the left.
4. The output in the Debug Console is `testing`.
5. Running `flutter test` through the flutter console manually in the root directory results in the output being `testing/test`

Is there a reason for this difference in behavior?

**Comment by DanTup** [comment]
I don't think there's a good reason for this, it's just an oversight (I didn't realise current directory doesn't match the project root when running from the command line). I think it should be an easy fix, thanks!

**Comment by DanTup** [comment]
Ok, this seems to be a flutter inconsistency. Depending on whether you run with a filename or a test name, the directory is different:

```
dantup-macbookpro:flutter_hello_world dantup$ flutter test --plain-name 222
00:04 +0: /Users/dantup/Dev/Dart-Code/test/test_projects/flutter_hello_world/test/widget_test.dart: 222Hello world test                                        
Directory: '/Users/dantup/Dev/Dart-Code/test/test_projects/flutter_hello_world/test'

                                                                                                                                    
dantup-macbookpro:flutter_hello_world dantup$ flutter test test/widget_test.dart 
00:04 +0: 222Hello world test                                                                                                                                  
Directory: '/Users/dantup/Dev/Dart-Code/test/test_projects/flutter_hello_world'
```

I've moved this over to https://github.com/flutter/flutter/issues/20907 so you may wish to subscribe over there.
