### ISSUE TITLE
Option to disable pub test buttons

### ISSUE THREAD

**Issue by bergwerf** [Dart-Code/Dart-Code#1157]
I now get Run/Debug buttons over my pub test. I don't really use them since nowadays Dart/Pub have such a heavy startup time (like 5x that of all my tests) that is doesn't really matter that much if I run all.

I also encountered an issue where the position of the buttons was moving up and down by one or two pixels while typing which can be annoying.

**Comment by DanTup** [comment]
This can be disabled with the `dart.showTestCodeLens` setting :-)

**Comment by bergwerf** [comment]
Ok, cool.

I found that for me the buttons moving is reproducible with this snippet:

```dart
import 'package:test/test.dart';

main() {
  //
  // <type random characters here>

  test('test', () {
    //
  });
}
```

**Comment by DanTup** [comment]
Hmm, I can't repro with that by typing where you marked (either with the line commented or not); can you get a GIF? I presume something is causing the test market to be removed from the outline, which causes us to add/remove, but I can't actually repro it. We could probably fix it by just reducing how often we update - but I'd like to be sure it's this (and hopefully repro it) before doing it so I can ensure it does the job.

**Comment by bergwerf** [comment]
I managed to record some of it.
[vokoscreen-2018-08-17_16-03-21.zip](https://github.com/Dart-Code/Dart-Code/files/2297498/vokoscreen-2018-08-17_16-03-21.zip)

**Comment by DanTup** [comment]
Wow, that is weird! I've opened an issue in the VS Code repo about it, since I don't think this is anything to do us (I don't think we could make it do this if we wanted!).

https://github.com/Microsoft/vscode/issues/56688
