### ISSUE TITLE
Can't change dart-sdk version on vscode

### ISSUE THREAD

**Issue by RevHounds** [Dart-Code/Dart-Code#1158]
I really want to change dart-sdk version built-in inside of flutter cache folder into the latest version, how can i achieve this? I have tried changing the Workspace Setting inside the VSCode but it didn't work. Can you solve this?

**Comment by DanTup** [comment]
The version of the Dart SDK being used by Flutter should match the version the Engine was built with, so changing it ad-hoc might cause issues. Can you clarify your use case? If you use Flutter's `master` channel you should be on a relatively recent Dart SDK anyway?

**Comment by DanTup** [comment]
I'm unable to investigate this without more details as mentioned above so I'm going to close it. I'm happy to reopen it if you can provide some additional info.
