### ISSUE TITLE
Exclude pub cache folder from analysis if a user opens their entire home directory in VS Code

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#1164]
It's come up a few times, most recently here:

https://twitter.com/truthmast/status/1027555592531922944?s=09

Opening your home directory definitely isn't recommended (you really need to open a project root for the debugger to start at the right place), but I think it should be easy to just exclude this to avoid a bad experience if people do it.

**Comment by DanTup** [comment]
@bwilkerson I'm now wondering if this is best handled in the analyzer? In the server docs it says:

> A file is implicitly excluded if it is in a subdirectory of one of the root paths where the name of the subdirectory starts with a period (that is, a hidden directory).

So on macOS/Linux, the pub-cache would be excluded automatically (because it's `.pub-cache`) but on Windows it doesn't start with a `.` so is scanned.

Would it make sense for the code that handles excluded dot-folders to also exclude the pubcache so it behaves the same across platforms? (or, exclude special or hidden folders like AppData?).

**Comment by DanTup** [comment]
> we thought the same thing about the `packages` directory. Then we had a user that used a directory named packages to hold all of the packages they were working with.

Valid, but I think that one is a bit less specific - having a folder with a particular name seems like an odd thing to avoid. But in this case, doesn't the analysis server already know exactly where the pubcache is? (it's possible it doesn't, because it just reads paths from .packages, in which case maybe this isn't so different..)

> But I have to wonder whether it's worth the effort at this point given the number of people hurt by this bug compared to many others that are waiting to be addressed.

Yeah, that's also valid. I've seen people mention it a few times (in the context of VS Code) so I was looking for an easy fix (people don't read docs so if they think it's a valid thing to do, they'll just open it and then complain performance sucked or something).

I did also think of just refusing to start up for this case and show a warning. It's pretty trivial in VS Code to open multiple folders in the same window (just shift-click them in the Open dialog instead of selecting the parent) so I'm happy to guide users down that path if we don't think it's worth effort here and/or only affects VS Code.

**Comment by bwilkerson** [comment]
Correct. Server does not know where the pub cache is, it just uses the paths in the `.packages` file.

**Comment by DanTup** [comment]
Ugh, ok, maybe I'll handle this locally. I wonder if I can just add the default PubCache location to the `excludes` set when calling setAnalysisRoots. Need to ensure that doesn't stop stop it being looked at to resolve things in the users project (I presume not, since otherwise it'd probably happen because of the dotfiles filter on Linux/Mac).

**Comment by DanTup** [comment]
I tried excluding this at my end, however it seems if I explicitly exclude the pubcache, then no packages resolve and you get a project full of errors. I'm not sure why this doesn't happen if they're ignored for starting with dots on macOS/Linux, but I'll have to come back to it for next version.

**Comment by bwilkerson** [comment]
I would have expected that excluding the pub cache would have worked (assuming that users don't try to open directories nested inside it). Analyzer should be ignoring the exclude list when it needs to read a file in order to analyze a non-excluded file.

**Comment by DanTup** [comment]
I can't repro the issue - analysis is pretty slow because there are a lot of folders, but the only errors I see are legit. So, I'm merging the fix as it was.
