### ISSUE TITLE
Support integratedTerminal

### ISSUE THREAD

**Issue by lyquocnam** [Dart-Code/Dart-Code#1167]
Dear author, the vscode `debug console` is too bad, i want use with `integratedTerminal` like nodejs can do.
Please support this.

**Comment by DanTup** [comment]
There's an open issue for this at #99. It's not been a priority due since nobody has really been asking for it. Please add a 👍 to #99 and some notes on why you want it (and/or why the debug console is bad) to help prioritise :-)
