### ISSUE TITLE
Make `editor.formatOnType` work

### ISSUE THREAD

**Issue by ikhwanhayat** [Dart-Code/Dart-Code#117]
Right now auto-format doesn't work even when `editor.formatOnType` set to `true`.

**Comment by DanTup** [comment]
This requires giving Code a provider that formats part of a document (it sends a request to format only the current line). [Related discussion here](https://groups.google.com/a/dartlang.org/d/msg/analyzer-discuss/I2FPL23_yXs/eN7KOkzWBwAJ).

**Comment by DanTup** [comment]
I'm interested in feedback on this - I've pushed to `master`. Whenever you type `}` or `;` it will automatically save (if you've enabled `editor.formatOnType` in your settings).

To me, this seems to work well; but I haven't written a lot of Dart with it.

I'd be interested to know what you think (and whether you think the choice of characters is good or should be changed).

**Comment by DanTup** [comment]
@devoncarew

**Comment by devoncarew** [comment]
> I'm interested in feedback on this - I've pushed to master. Whenever you type } or ; it will automatically save 

Automatically save or automatically format?

**Comment by DanTup** [comment]
Whoops, format!
(btw, format-on-save works in Insiders now too)
