### ISSUE TITLE
request: would be possible highlight components inside widget

### ISSUE THREAD

**Issue by cocodrino** [Dart-Code/Dart-Code#1174]
Hi, I was thinking today would be nice if vscode would highlight (with different background) the components when you're building them...

so in the next code Scaffold, AppBar,Text,Builder, IconButton,Icon would have a differnt background...this would help tracking the hierarchy between components and would be much more simple understand in a speed check how the widget is builded...

```dart

 Widget build(BuildContext context) {
    return new DefaultTabController(
      length: demos.length,
      child: new Scaffold(
        appBar: new AppBar(
          title: new Text(title),
          actions: (actions ?? <Widget>[])..addAll(
            <Widget>[
              new Builder(
                builder: (BuildContext context) {
                  return new IconButton(
                    icon: const Icon(Icons.code),
                    tooltip: 'Show example code',
                    onPressed: () {
                      _showExampleCode(context);
                    },
                  );
                },
              )
            ],
          ),

```

do you think would be possible and is it a good idea???

thank you......

**Comment by DanTup** [comment]
I think this is covered by https://github.com/Dart-Code/Dart-Code/issues/606. There are no solid plans but there are some interesting ideas in there you may want to read through (and maybe comment on).
