### ISSUE TITLE
Function is imported but doesn't exist

### ISSUE THREAD

**Issue by lukepighetti** [Dart-Code/Dart-Code#1176]
This may be a VM problem, I'm not sure. It's also a hell of a bug to describe, so bare with me.

1. `utils.dart` has function `launchUrl()`
2. `library.dart` has `export utils.dart`
3. `main.dart` has `import library.dart` and `launchUrl()` "is not defined"

if I place `launchUrl()` inside `main.dart` it still says `launchUrl()` "is not defined"

I had this problem in another file and the problem was solved by merely cut&paste the line containing `launchUrl()` to the line above it.

I have not been able to find any way to reproduce this.

And the project fails to run as it agrees with the errors provided by VSC. (Probably a VM problem, huh?)

**Comment by DanTup** [comment]
I can't reproduce this. If you see the same error when trying to *run* the application, that rules out any weird state issue in the analysis server.

If you're able to repro this and can attach a copy of the project (or get an [analysis server log](https://dartcode.org/docs/logging/#analyzer)) that would help a bunch!

**Comment by lukepighetti** [comment]
Hi Dan, I'm closing this because I'm 99% sure it's not in your wheelhouse. The reference above goes into it more. Thanks.
