### ISSUE TITLE
VS Code: Support creating a new Flutter module project

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#1178]
`flutter create` has a new project type for creating modules to embed in existing apps. Similar to the `Flutter: New Project` command, we should have a way of creating this type of project.

It should function the same as the `New Project` command:

- Prompt the user for a name/location for the project
- Create the folder and open it in a new VS Code window
- Execute `flutter create` with the supplied arguments showing progress in an Output pane
- Show the user a notification once complete guiding them on how to proceed (which is most likely along the lines of moving to Android Studio/Xcode and running some steps to add a reference to the module into their existing app)

Since users aren't editing the Android/iOS apps in VS Code (or at least, if they are, it's unrelated to the Dart/Flutter plugins) this implementation is relatively basic.

**Comment by matthew-carroll** [comment]
@DanTup would you mind prefixing the title of this ticket with "VSCode: "?  Each time I read it in the project I confuse myself and assume it's a low level CLI ticket...

**Comment by DanTup** [comment]
Sure, I did think it might be a little confusing with it listed on the Flutter project.

**Comment by DanTup** [comment]
Based on https://github.com/flutter/flutter/issues/22344#issuecomment-426168061 I don't think this is required anymore. The same template works for both, so the `Flutter: New Project` command will cover this once those changes land.
