### ISSUE TITLE
color and icon preview extension in VSCode for Flutter

### ISSUE THREAD

**Issue by MoSala7** [Dart-Code/Dart-Code#1181]
I'am using Visual Studio Code for Flutter Developing and i really like to have a feature that exist in Intelij IDE Which it is showing the **Color of Color's Name** and showing the **Icon of the Icon's Name** beside the code like in the picture .. 
![screenshot_10](https://user-images.githubusercontent.com/32467495/44741131-84b90a80-aafc-11e8-9613-36fd2cc9d6f5.png)

**Comment by DanTup** [comment]
This is something I'd definitely like to do, but we don't currently have enough information from the analyzer to implement it.

There's already an issue at #807 so I'll close this as a dupe - you can click the `Subscribe` button on that one to received updates.

It's not perfect, but if you hover over the colours/icons in the code, there should at least be a preview in the tooltips.

**Comment by nileshchavan0611** [comment]
kindly check this extension

https://marketplace.visualstudio.com/items?itemName=circlecodesolution.ccs-flutter-color
