### ISSUE TITLE
Having the dart extensions active, breaks the built-in git extension.

### ISSUE THREAD

**Issue by dragonfax** [Dart-Code/Dart-Code#1198]
If I open a flutter project in vscode, vscode can no longer work with git. The source control tab just shows "no source control providers".

If I open a non flutter/dart project then the source control tab work just fine. And just to confirm, if I disable extensions, or just disable this one extension, then opening the same flutter project, the source control works again.

Any advice? I'm not seeing anyone else complain of this. I have ruby projects, and golang projects, and other various projects, and only dart projects breaks the git extensions in vscode for me.

**Comment by DanTup** [comment]
If you click Help -> Toggle Developer Tools, are there any errors or warnings listed in the console?

**Comment by dragonfax** [comment]
Thanks for checking on your machine.

Here is the issue in vscode, before I figure out it was this extension causing it.
https://github.com/Microsoft/vscode/issues/58017#issuecomment-419007881

No, there is nothing notable in the dev tools.

**Comment by DanTup** [comment]
Very strange. I'm not really sure I should be able to break the built-in Git even if I tried and there's nothing in Dart Code relating to Git (or source control providers), so I think there may be a VS Code bug here in any case, it may be worth re-opening your issue there.

Just to be sure - you don't have Git disabled in your Workspace settings for the Dart project(s) or in your User settings for only Dart projects?

**Comment by dragonfax** [comment]
From the console "[Extension Host] Git installation not found."

My settings.json is empty.

**Comment by dragonfax** [comment]
Seems to be fixed since I added `"git.ignoreMissingGitWarning": false`. Weird.

**Comment by dragonfax** [comment]
Thanks for the help.
