### ISSUE TITLE
Improve SDK version check to look up real last release

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#120]
#76 is a naive implementation that just has a hard-coded value we'll update periodically. We should figure out a reliable way to get the version from Google.

**Comment by ikhwanhayat** [comment]
How can we ensure that newer Dart version won't break our extension? I think the hard-coded value is good enough, we just simply state the latest known Dart version that works with our extension.

**Comment by DanTup** [comment]
We can't be sure, but the intention is for Dart and the Analyzer to not have breaking changes.

Originally, with DartVS, we shipped our own SDK/Analyzer specifically for that reason, but it becomes inflexible for other reasons (we have to do a new release and get everyone to update on every SDK update, people can't switch to nightly SDKs to test bugs, etc.).

My plan is that if any breaking changes are announced on the analyzer-discuss list, we could add code to handle them and push a release out before the next SDK ships. Though I suspect there won't be many, there are lots of IDEs using this so it's likely stable. Many things could be added behind options/flags to remain backwards-compatible.

That said, I think you're right that the current behaviour is good enough, so this case isn't a priority for me. My main concern was notifying people on really old versions (there was an 8month old version showing up in the analytics).
