### ISSUE TITLE
Folding for constructor with optional arguments

### ISSUE THREAD

**Issue by Simpler1** [Dart-Code/Dart-Code#1201]
As seen in the following image, I would expect to be able to fold the MyHomePage constructor since it has optional arguments on multiple lines.

![2018-09-17 16_23_16-main dart - flutter_assets - visual studio code](https://user-images.githubusercontent.com/5922273/45648370-65c3ed80-ba96-11e8-868b-8c2dac24fda1.png)

In vscode, the following is set:
`"editor.foldingStrategy": "auto"`

(Excellent extension by the way.  :) )

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/d3082bcb3ec640ed9d74194f8144fee7e5ce3fd1. As it's in the language server, it'll show up in a future Dart/Flutter SDK release (not the VS Code extension release).
