### ISSUE TITLE
fail to detect /dev/kvm from flatpak

### ISSUE THREAD

**Issue by chengjk84** [Dart-Code/Dart-Code#1205]
Anyone facing this problem?

`Failed to launch emulator: emulator: ERROR: x86 emulation currently requires hardware acceleration!
Please ensure KVM is properly installed and usable.
CPU acceleration status: /dev/kvm is not found: VT disabled in BIOS or KVM kernel module not loaded`

`› ll /dev/kvm
crw-rw-rw-. 1 root kvm 10, 232 Sep 18 19:00 /dev/kvm`

**Comment by DanTup** [comment]
This seems like an issue with your Android SDK set up and not something Dart Code can affect.

Based on the error, it sounds like you need to install KVM in order to get hardware acceleration to use an x86 emulator. There's some info here that might be useful (see the "Configuring VM acceleration on Linux" section):

https://developer.android.com/studio/run/emulator-acceleration

**Comment by chengjk84** [comment]
kvm is installed and running fine on the machine... emulator even running fine on vscode which i installed using rpm package... but it not seem to be running on flatpak version of vscode... look like it might not be dart extension problem... will wait for flatpak version maintainer to see if there got any update... thanks for the reply anyway...

**Comment by DanTup** [comment]
> emulator even running fine on vscode which i installed using rpm package...
> but it not seem to be running on flatpak version of vscode...

I'm afraid I don't know much about any of this, I haven't used much Linux in a long time, and never flatpak (or kvm, or the Android emulator on Linux!).

If there's anything you think I can do to help, do shout - though I suspect it's outside of my area. For launching emulators, the Dart extension basically does the same as running `flutter emulator --launch (name)` so you may be able to debug a little by running that in the terminals of each and trying to see what the difference is (for ex., if there are `PATH` or other environment differences).
