### ISSUE TITLE
Use analysis.getLibraryDependencies to avoid parsing .package file client-side

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#1207]
@bwilkerson @pq While investigating a bug in my code that parses .packages I noticed this method in my generated files. Am I right in thinking this could remove the need for me to parse the file myself? (We use it for mapping uris for breakpoints and to display package names in hover tooltips).

**Comment by bwilkerson** [comment]
It sounds reasonable to me, based on your description and the limited documentation. If it doesn't work for you, let us know and maybe we can make it work.

**Comment by DanTup** [comment]
Well, it doesn't work - but not in the way you might've had in mind:

```
==> {
	"id": "23",
	"method": "analysis.getLibraryDependencies"
}
<== {
	"id": "23",
	"error": {
		"code": "UNSUPPORTED_FEATURE",
		"message": "Please contact the Dart analyzer team if you need this request."
	}
}
```

Looks like the code was commented out a while ago, so I don't know whether it'd be a simple fix or not:

https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/lib/src/domain_analysis.dart#L133-L153

It'd definitely be nice to not be parsing the file in Dart Code (just to remove something that could be fragile or where I've not interpreted the format perfectly) but since there have been no complaints, I don't think it's that important if it's non-trivial.

**Comment by DanTup** [comment]
Much of the code that used this has gone away, and what remains is now using new (more reliable) code to parse `packages_config.json`, so this isn't required.
