### ISSUE TITLE
Flutter plugin runs into trouble when installed in directory with "bin" in path

### ISSUE THREAD

**Issue by tabinnorway** [Dart-Code/Dart-Code#1213]
So, I installed Flutter in the following directory: $HOME/bin/flutter
Set my path to $HOME/bin/flutter/bin

Result, not so good. From the command line everything worked like charm, but the Flutter plugin in VSCode didn't work at all. Here are the problems it ran int

- Could not find the Dart SDK
- When running Flutter: New Project, it tried to run $HOME/bin/flutter to create the project (should have run $HOME/bin/flutter/bin/flutter (yeah, yeah).

Just some observations.

To fix
mv $HOME/bin/flutter $HOME/flutter
fix path
Everything is OK

**Comment by DanTup** [comment]
I can't repro this - is it possible you can click the `Show Log` button on the `Can't find SDK` notification and attach the log here?

Also - did it say it can't find the *Dart* SDK or *Flutter* SDK? If it said Dart, that also suggests it didn't think you had a Flutter project open. Hopefully a log will show what's up.

**Comment by DanTup** [comment]
Please post back if you're able to provide any more info on this.

**Comment by blueframes** [comment]
Here is a solution for Could not find the Dart SDK:

In the flutter project directory, locate .idea/libraries/Dart_SDK.xml
Open the file and see the path where Dart sdk is downloaded. Here is a line from the file for reference: `<root url="file:///[path to your flutter installation directory]/bin/cache/dart-sdk/lib/async" />`

Use locate SDK prompted by the VSCode [reopen the project in vscode, it will ask again for Dart SDK], navigate to dart-sdk as given by above line. Set it as Dart SDK directory. That's all to get it working.

**Comment by DanTup** [comment]
@blueframes When working on Flutter projects it's best *not* to explicitly set the Dart SDK path as it should be found automatically from your Flutter SDK. If you find you need this, please open an issue with a log file (as mentioned above) so I can check what's gone wrong. Thanks!
