### ISSUE TITLE
VS Code flutter extension: hide comments

### ISSUE THREAD

**Issue by flddr** [Dart-Code/Dart-Code#1214]
Today most lines in code are comments, and (with coloring or not) it becomes harder and harder to concentrate (and view) the code itself - thats to all software, not especially flutter - but i would like to have an distraction free mode only for hiding all comments - i am sure, many people would like to have that and reduce their filtering and scrolling...

So, if it would be possible to have a switch **hide comments** to work and view with only code i think it would make programming a lot easier.

Same for android studio..

Maybe, thats probably more a question for the IDE itself, about VS Code i am not sure.

Thanks :)

**Comment by DanTup** [comment]
There's not really a good way we could provide this from the plugin so this would really need some sort of support from VS Code so should be raised there.

That said, if there are comments make the code harder to read, maybe they should be pruned (or improved)?

**Comment by flddr** [comment]
I have requested that at VS Code, makes sense.

No, i think, we really need this for future. Today, docs are generated from source code comments in more and more software-packs - so, i do not want to read those docs while coding - and this would definitively be the next step in development - hide the docs in source codes ;)

Thanks for your fast response and awesome software :100:

**Comment by flddr** [comment]
BTW: i have issued that initially here because of the extra-added tag-ending comments which will be inserted by flutter vs code app while coding - on the one side they helps really a lot - on the other side there are more comments as code overall.

**Comment by flddr** [comment]
Thanks, yes, i know them all - long time ago i issued that already for Windows UWP Apps in Visual Studio - here we have 80% of comments and 20% code - but folding isnt helpfull - between every line of code is again: a folded line of comment. (BTW: Visual Studio had no idea how to change that). In Android Studio its the same for me. Nearly everywhere ;)

But, it was a little kind of mistake to issue that here - this was just of the extra insertions done by flutter - most of my time i need them - and i really love them :100: 

Thank you.

I would like to close this issue, because its more a general question for an IDE and not for you, but i am not sure to interprete your label `is enhancement` correct :)

**Comment by DanTup** [comment]
I tagged it as a feature request for hiding comments (but blocked on VS Code). Based on the `Collapse Comments` command in VS Code, I think probably VS Code won't implement more (though feel free to request it). I'll close this since I don't think it's likely we'll be able to do it, but I'm happy to revisit this if you think there's something we can do here (either without support from VS Code, or if VS Code add support).

**Comment by flddr** [comment]
Everything is fine - thanks for the great conversation :) :+1:
