### ISSUE TITLE
tooltip should show the source package / library

### ISSUE THREAD

**Issue by devoncarew** [Dart-Code/Dart-Code#122]
The tooltip for an element should show the package it's from. So hovering over `FooClass` should show `package:foo/bar.dart`.

**Comment by DanTup** [comment]
We already have some code in the debug folder to handle these mappings (currently only in debug branch); I suggest we move that to a `shared` folder for code that's valid to use in both client and debug adapter and then call it in `DartHoverProvider.getHoverData`.
