### ISSUE TITLE
DEBUG CONSOLE does not print the full STRING length, ends with <…>

### ISSUE THREAD

**Issue by rajeshzmoke** [Dart-Code/Dart-Code#1223]
Im trying to print an access token that i can send it to backend ( not via service request, manual copy paste) to verify but the token is truncated with <...>

`eyJhbGciOiJSUzI1NiIsImtpZCI6ImEzMjJiNjhiY2U0MzExZTg2OTYzOTUzM2QzYTFhMjU1MWQ1ZTc0YzYifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXN0cm9sb2d5LTgyZmVlIiwibmFtZSI6ImFkYXNkIiwicGljdHVyZSI6Imh0dHBzOi8vbGg0Lmdvb2dsZXVzZXJjb250ZW50LmNvbS8tYzR5TmpSNng5Q1EvQUFBQUFBQUFBQUkvQUFBQUFBQUFBQUEvQVBVSUZhTUtjTXYtNnhIZkNuazZnWTdETWNna2FKT29uZy9zOTYtYy9waG90by5qcGciLCJhdWQiOiJhc3Ryb2xvZ3ktODJmZWUiLCJhdXRoX3RpbWUiOjE1MzgwNTQ0NDIsInVzZXJfaWQiOiJkUFdwQ3R6enI4Zkw3V2p1cHczOHYyRUZaMnMxIiwic3ViIjoiZFBXcEN0enpyOGZMN1dqdXB3Mzh2MkVGWjJzMSIsImlhdCI6MTUzODEyMTI5OSwiZXhwIjoxNTM4MTI0ODk5LCJlbWFpbCI6InJhamVzaGhwc3dAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZ29vZ2xlLmNvbSI6WyIxMTY1MDAyNTA5NDg5Njk2MzcyMTIiXSwiZW1haWwiOlsicmFqZXNoaHBzd0BnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJnb29nbGUuY29tIn19.iY_QAL1X4WNNQErO7V3vbXEYnWTMQMde-YMqJL5Y1pkiDSOaOwZ5YU2PU3f5DOksb6jowOYYegk99B8NdM1bUJbGKJRIEF-YTBvaNaz7YVjky6zwzsuZ2dLPhAhHSOCE9Yg5CE8lP5hEhse7P4nz_DPhELlfjlmVJjtRKng1qf9BLs<…>`

VSCode Version:
`VS Code (version 1.27.2)`

**Comment by DanTup** [comment]
How are you printing this? I just tried printing 26,000 characters in a script and it came through in full:

![screen shot 2018-10-01 at 9 04 16 am](https://user-images.githubusercontent.com/1078012/46276782-129f6f80-c559-11e8-8a8f-fd8658349441.png)

**Comment by rajeshzmoke** [comment]
i'm using `print()` to print 
<img width="1122" alt="screenshot 2018-10-04 at 1 00 09 pm" src="https://user-images.githubusercontent.com/30038668/46459131-9d8c9e00-c7d5-11e8-8b78-c69438883650.png">

actual token is 
`eyJhbGciOiJSUzI1NiIsImtpZCI6ImEzMjJiNjhiY2U0MzExZTg2OTYzOTUzM2QzYTFhMjU1MWQ1ZTc0YzYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXN0cm9sb2d5LTgyZmVlIiwibmFtZSI6ImFkYXNkIiwicGljdHVyZSI6Imh0dHBzOi8vbGg0Lmdvb2dsZXVzZXJjb250ZW50LmNvbS8tYzR5TmpSNng5Q1EvQUFBQUFBQUFBQUkvQUFBQUFBQUFBQUEvQVBVSUZhTUtjTXYtNnhIZkNuazZnWTdETWNna2FKT29uZy9zOTYtYy9waG90by5qcGciLCJhdWQiOiJhc3Ryb2xvZ3ktODJmZWUiLCJhdXRoX3RpbWUiOjE1Mzg1NzQ4NTUsInVzZXJfaWQiOiJkUFdwQ3R6enI4Zkw3V2p1cHczOHYyRUZaMnMxIiwic3ViIjoiZFBXcEN0enpyOGZMN1dqdXB3Mzh2MkVGWjJzMSIsImlhdCI6MTUzODYzNTEwMiwiZXhwIjoxNTM4NjM4NzAyLCJlbWFpbCI6InJhamVzaGhwc3dAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZ29vZ2xlLmNvbSI6WyIxMTY1MDAyNTA5NDg5Njk2MzcyMTIiXSwiZW1haWwiOlsicmFqZXNoaHBzd0BnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJnb29nbGUuY29tIn19.fFEVXcRsyu0Oc0B-lBD-onuZfRYc50TCDpWbJz9-1wO0FufT0q3wN73v6UFaNsXf_SArAC32ZdbNkGVi8NcLiCQouD3UCLlWk4gzYErFB6uYip16Ur-8O4UIjc1CKhwuni-f6_qWrdrlwm9R6zNESxrBJO7a3eUvjzQFJQ7TZJJQF8gLgTIcb3fRvuhYhnEHMBbXGan8jxaE3jxpMNTYWWljpfbkmpict5NEa57f-cuszjND_eGJeV8lYfxPGPHq2ge-dfVjZw06bv85y5sxC9By9t52WDf8SLtTJn57-lifxuIlyIIJhZ1COXtkJdAUWdrlesDQOxQ6iz_ss5FHxw`

**Comment by DanTup** [comment]
Gotcha - I can repro. It happens with `flutter run` at the terminal, so it must be upstream. I'm not sure if it's Flutter or the way the logs are coming from the device; but I guess if it's intended to support this then Flutter may need to get the output differently.

I've moved this to https://github.com/flutter/flutter/issues/22665.

**Comment by dieudonnecostes** [comment]
@rajeshzmoke 
import  @**'dart:developper';**
then use:  log('$yourString');
