### ISSUE TITLE
Editing and Saving code causes an Unhandled Exception 

### ISSUE THREAD

**Issue by rajeshzmoke** [Dart-Code/Dart-Code#1224]
```
Dart Error: Unhandled exception:
setState() called after dispose(): _ChatScreenState#23017(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback. The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
#0      State.setState.<anonymous closure> (package:flutter/src/widgets/f<…>
```

This problem occurs when editing and saving the code (cmd + s)

VSCode Version 1.27.2 (1.27.2)

**Comment by DanTup** [comment]
I think this is going to be very dependent on the code in your app. Are you able to provide a small repro?

**Comment by DanTup** [comment]
It's hard to diagnose without some code, but I think if you're calling APIs from within build methods/constructors of StatelessWidgets this would happen. Can you share a small sample of code that shows your issue?

**Comment by rajeshzmoke** [comment]
> It's hard to diagnose without some code, but I think if you're calling APIs from within build methods/constructors of StatelessWidgets this would happen. Can you share a small sample of code that shows your issue?

No i'm not doing it...let me see if i can give a sample code.. this is happening after i updated flutter...same code worked fine but after update this is happening

**Comment by DanTup** [comment]
If you can easily share some code that repros this, I can look. It may be better raising at [flutter/flutter](https://github.com/flutter/flutter) though as it seems to be a Flutter issue rather than a VS Code Plugin issue (presumably you'll be able to repro from the terminal with `flutter run`).

**Comment by DanTup** [comment]
I'm unable to investigate this without more details as mentioned above so I'm going to close it. I'm happy to reopen it if you can provide some additional info.
