### ISSUE TITLE
Unable to hit breakpoints debugging analysis server tests

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#123]
Running code from `debugger` branch, with a checkout of the `dart-lang/stable` branch of https://github.com/dart-lang/sdk:

1. Open up the folder `pkg\analysis_server`
1. Hit `F5` and allow `launch.json` to be created
1. Set `program` to `${workspaceRoot}\\test\\services\\refactoring\\rename_import_test.dart`
1. Put a breakpoint in `refactoring.dart` around line 370 (just inside the `RenameRefactoring` factory constructor)
1. Add a `print("something")` line just next to the breakpoint
1. Press `F5`

The print commands work, but the breakpoint is not hit

**Comment by DanTup** [comment]
Possibly this is another Windows path issue:

```
==> {"id":"3","method":"addBreakpointWithScriptUri","params":
  {"isolateId":"isolates/849603178","scriptUri":"package:analysis_server/src\\services\\refactoring\\refactoring.dart","line":371}
}
```

**Comment by DanTup** [comment]
@devoncarew Do you know if there's info on the format of `scriptUri` being passed to `addBreakpointWithScriptUri`? I can't find any references to it in [the spec](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#addbreakpointwithscripturi).

I've tried updating our `debug\util.ts:convertFileToPackageUri` method to use `path.sep` instead of a hard-coded `/` but that didn't make any difference :(

(Also, maybe worth checking to see if you see the same behaviour in the original comment here to confirm it is indeed a Windows path issue).

**Comment by devoncarew** [comment]
From some quick testing, I do hit the breakpoint:

<img width="462" alt="screen shot 2016-08-23 at 4 59 57 pm" src="https://cloud.githubusercontent.com/assets/1269969/17913969/1c2b8d72-6953-11e6-9ba6-b5334c7b539a.png">

So I suspect a path issue?

You can try importing the `dart:developer` library in that file, and calling the debugger() method (https://api.dartlang.org/stable/1.18.1/dart-developer/debugger.html). It'll force a break there, and you can see what script uri the VM is using.

**Comment by devoncarew** [comment]
The uri we're sending in is `package:analysis_server/src/services/refactoring/refactoring.dart`; I think it should use forward slashes on both OSes.

**Comment by devoncarew** [comment]
(I did resuscitate an older windows machine to test this :) )

**Comment by DanTup** [comment]
> You can try importing the dart:developer library in that file, and calling the debugger() method (https://api.dartlang.org/stable/1.18.1/dart-developer/debugger.html).

Aha, that's good to know - thanks!

> (I did resuscitate an older windows machine to test this :) )

Great; thanks! I'll give it a whirl this week :-)

**Comment by DanTup** [comment]
Works great; thanks! :)
