### ISSUE TITLE
Region/folding is not supported?

### ISSUE THREAD

**Issue by stt106** [Dart-Code/Dart-Code#1232]
I see that VS Code supports region/folding for some language e.g.
 //#region My Region 
`some code`
//#endregion

But dart is not supported. Am I doing something wrong or this will be added later?

**Comment by DanTup** [comment]
This is not currently supported. As far as I'm aware, `//#region` is not a Dart construct so these are just treated as comments and won't generate foldable regions.

We implemented folding in the Dart Analysis Server in the SDK so that it can be re-used across editors so supporting this would have to come from the SDK, so this should be raised in the [SDK repo](https://github.com/dart-lang/sdk).

**Comment by stt106** [comment]
ok thanks.

**Comment by angelopolotto** [comment]
`//#region` and `//#endregion` work in the Android Studio and Intellij as well.

**Comment by engmsaleh** [comment]
@angelopolotto Didn't work in VCode

**Comment by angelopolotto** [comment]
@engmsaleh Don't work in VSCode, only Android Studio and Intellij.

**Comment by ModProg** [comment]
Not the real solution for the problem, but for those just searching for a workaround:
https://marketplace.visualstudio.com/items?itemName=maptz.regionfolder
Its a Addon that works for many languages, including dart.

**Comment by ali80** [comment]
> 
> 
> Not the real solution for the problem, but for those just searching for a workaround:
> https://marketplace.visualstudio.com/items?itemName=maptz.regionfolder
> Its a Addon that works for many languages, including dart.

It's a real solution for me :), works very well.

**Comment by philanderson888** [comment]
> Not the real solution for the problem, but for those just searching for a workaround: https://marketplace.visualstudio.com/items?itemName=maptz.regionfolder Its a Addon that works for many languages, including dart.

This one worked for me also, and I really love regions, so thank you very much for mentioning.

**Comment by Hixie** [comment]
(breadcrumbs for the next person: https://github.com/dart-lang/sdk/issues/34795)

**Comment by DanTup** [comment]
FWIW, it's not what was asked here but it's related.. VS Code now allows folding of arbitrary blocks of code (regardless of language), but you need to create them through a command, they're not marked in the source code:

https://github.com/Dart-Code/Dart-Code/assets/1078012/0f656e35-e148-445b-a0a2-b192d12adac3
