### ISSUE TITLE
Live Saas compiler (3.0.0) possibly interfering with the creation of a new flutter project.  

### ISSUE THREAD

**Issue by Ashwin-Shenoy-NITK** [Dart-Code/Dart-Code#1241]
I have the Dart plugin vs 2.19.0 (the latest) installed in VS Code and after installing, reloading and closing & opening the editor again, I am facing with the issue `command 'flutter.createProject' not found`. 
None of the other flutter commands like `Flutter : New Project` or `Flutter : Run Flutter Upgrade` are working. 
This issue has been discussed in https://gitter.im/dart-code/Dart-Code. 

This is the output I get after running `flutter doctor -v` in the flutter console. 
```
[ΓêÜ] Flutter (Channel beta, v0.8.2, on Microsoft Windows [Version 6.1.7601], lo
cale en-IN)
    ΓÇó Flutter version 0.8.2 at C:\flutter
    ΓÇó Framework revision 5ab9e70727 (4 weeks ago), 2018-09-07 12:33:05 -0700
    ΓÇó Engine revision 58a1894a1c
    ΓÇó Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[ΓêÜ] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    ΓÇó Android SDK at C:\Users\user\AppData\Local\Android\sdk
    ΓÇó Android NDK location not configured (optional; useful for native profili
ng support)
    ΓÇó Platform android-28, build-tools 28.0.3
    ΓÇó Java binary at: C:\Program Files (x86)\Java\jdk1.8.0_181\bin\java
    ΓÇó Java version Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
    ΓÇó All Android licenses accepted.

[X] Android Studio (not installed)
    ΓÇó Android Studio not found; download from https://developer.android.com/st
udio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instruction
s).

[ΓêÜ] VS Code, 64-bit edition (version 1.27.2)
    ΓÇó VS Code at C:\Program Files\Microsoft VS Code
    ΓÇó Flutter extension version 2.19.0

[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.
```
I was suggested by @DanTup to disable all other extensions and then check. Doing that successfully created a flutter project and I was successfully able to run all other flutter commands from command palette. 

I stared enabling & disabling plugins and found that Live Saas compiler was possibly not allowing the creation of a new flutter project. 

This is the error from the console (after installing the plugin and running the create project command)
```
C:\Users\user\.vscode\extensions\ritwickdey.live-sass-3.0.0\node_modules\sasslib\sass.sync.js:61
var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}Module["arguments"]=[];Module["thisProgram"]="./this.program";Module["quit"]=(function(status,toThrow){throw toThrow});Module["preRun"]=[];Module["postRun"]=[];var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("Module['ENVIRONMENT'] value is not valid. must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScri

Error: unable to verify the first certificate
	at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
	at emitNone (events.js:106:13)
	at TLSSocket.emit (events.js:208:7)
	at TLSSocket._finishInit (_tls_wrap.js:637:8)
	at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)
```
```
Error: command 'flutter.createProject' not found
    at t._tryExecuteCommand (/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3019)
    at /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3019
    at n.Class.derive._oncancel.then (/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:161)
    at t.executeCommand (/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3019)
    at t.run (/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1369)
    at t.run (/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1370)
    at /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2968
```
Disabling the Saas compiler makes everything work again.

I am running everything on a Windows 7 Machine, 64 bit OS.

**Comment by DanTup** [comment]
I had a quick look at this, but even with those extensions installed, I can't repro.

I did have a look through their code to see if there's anything obvious that might interfere, however that extension appears to have 3.5 MB of minified (Emscripten-compiled?) JS in it which is apparently https://www.npmjs.com/package/sasslib, however the GitHub repro for that project is now a 404. This means it's difficult to review (or even trust!) all that code.

At a guess, I wonder if the error in the Saas extension is causing some code in Dart Code not to run. I think the best thing would be to try and track down that error first because a) fixing it may solve the issue and b) if we figure out what's failing there, it may allow me to reproduce and see if there's anything I can do to improve it.

Could you try opening an issue against that extension for the error, and post the link back here?

**Comment by DanTup** [comment]
Since I can't repro this and the repo for the other extension is gone, I can't really do much with it. If it's still an issue with an actively-developed extension let me know and I'm happy to engage the developers so we can figure out what's up.

**Comment by Ashwin-Shenoy-NITK** [comment]
Hey @DanTup Sorry for not getting on this earlier. Been some time since I have gotten back to trying flutter because of some issues with my system. Strangely though it works just fine and there's no issue anymore. Even though the extension I have mentioned where causing some definite issues earlier (not sure why it's not reproducible though ?), now those issues no longer seem to create any problems and creating a flutter project or hot reloading it is not a problem anymore.

**Comment by DanTup** [comment]
@Ashwin-Shenoy-NITK thanks for the update. If you do see anything like it again, do let me know. Thanks!
