### ISSUE TITLE
Flutter projects in sub-folders do not result in Flutter's Dart SDK being used

### ISSUE THREAD

**Issue by lukepighetti** [Dart-Code/Dart-Code#1248]
Hi Dan, 

When Flutter is part of a monorepo for some reason `/test/widget_test.dart` will not handle its imports properly. 

I created an example here for you to review when you have a moment. As a note, `flutter test` still runs perfectly regardless.

https://github.com/lukepighetti/flutter-vsc-monorepo-mvce

**Comment by lukepighetti** [comment]
And also

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.9.6, on Mac OS X 10.13.6 17G65, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.28.0)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by lukepighetti** [comment]
Also, screenshot of the issue

<img width="1162" alt="screen shot 2018-10-09 at 9 40 13 am" src="https://user-images.githubusercontent.com/666539/46673283-6a685700-cba7-11e8-97a0-30900816ae9a.png">

**Comment by lukepighetti** [comment]
As a point of interest, if I add this sub-folder with "add folder to workspace" it actually resolves the errors in both locations!

**Comment by lukepighetti** [comment]
Hey Dan, I'm playing around with this more and I don't have enough experience to know if this is a dart-code issue or if I should be constructing my mono-repos as multiple folders in a workspace. Any help is appreciated on understanding best practices here.

**Comment by DanTup** [comment]
Sorry for the delay! This is sadly a bit of a known case. Because you've opened the parent folder, we've deemed that your project is plain Dart, not Flutter, and we've loaded the non-Flutter version of the SDK.

I've seen this come up a few times recently, so I'll see what I can do. I think at a bare minimum, we could walk into the top-level folders when making the decision about the project type. You won't get the best experience if you don't add the folder as a workspace folder though - please 👍 on https://github.com/Microsoft/vscode/issues/45470 because it's blocking us from automatically upgrading folders.

**Comment by lukepighetti** [comment]
Thanks Dan. Been setting the folder as a project folder and its working for now. Only complaint is that I don't have a good way to see top level files, such as a top level .gitignore without using the console. But aside from that its working well. Thanks for all the work you do and enjoy your week!

**Comment by DanTup** [comment]
You can open both the root folder *and* the child folders. However, you'll see the children twice in the tree then (once as a child of the root folder, and then also as their own root). That's what the VS Code issue linked above is about fixing - allowing us to have multiple "workspace folders" within a tree without duplicating them at each level.

**Comment by DanTup** [comment]
vNext will look in the first level of folders for a Flutter project and if found, go into Flutter-mode. I believe that'll solve this issue (as long as you have a Flutter project in the first level of folders - we don't walk down the entire tree).

I'll try and make a beta build this week for testing.

**Comment by DanTup** [comment]
Beta here if you'd like to test it before it's released -> https://github.com/Dart-Code/Dart-Code/releases/tag/v2.20.0-beta.1
