### ISSUE TITLE
Breakpoint in global lambda not hit

### ISSUE THREAD

**Issue by kentcb** [Dart-Code/Dart-Code#1249]
Per the following code:

```dart
import 'package:flutter/scheduler.dart';
import 'package:test/test.dart';

void main() {
  final workingCase = SomeClass(() {
    // set a breakpoint on the following line and it will be hit
    print("Executing");
  });

  test("breakpoint works", () async {
    workingCase.execute();
  });

  test("breakpoint does not work", () async {
    nonWorkingCase.execute();
  });
}

class SomeClass {
  final VoidCallback execute;

  SomeClass(this.execute);
}

final nonWorkingCase = SomeClass(() {
  // set a breakpoint on the following line and it will not be hit
  print("Executing");
});
```
A breakpoint in the globally defined `nonWorkingCase` is not hit, whereas a breakpoint in the locally defined `workingCase` is.

[Observatory logs](https://gist.github.com/kentcb/3f8bec0ffd5eb6d7f3d0b096e6222d62)

**Comment by DanTup** [comment]
Thanks for the report and log! I've moved this to https://github.com/dart-lang/sdk/issues/34742 since this seems like a Dart issue.

**Comment by DanTup** [comment]
Tidying up the issue tracker - since this looks entirely an upstream issue and there's an SDK open, I'm going to close this one.
