### ISSUE TITLE
Debugger tweaks

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#125]
Moving these out of #112 since they're buried away in a comment somewhere. Probably not worth creating separate issues for each one yet (many may also have the same fix).

1. ~~Pressing `F10` (step over) on the last line of `main` breaks me into `dart:isolate-patch/isolate_patch.dart` at the end of `port.handler`~~ See #135 
1. ~~Probably related, the call stack lets me walk up into the same file; again seems a bit weird, but possibly this is expected (seems a little weird to expose non-user Dart code to them though?)~~ See #135
1. ~~Pressing `F11` steps into SDK functions; I both like and dislike this. In C# this is an option you can enable (off by default) so that you can easily `F11` into your own code without constantly dipping into framework stuff and have to drop back out; I know Dart is a bit different but presumably the same frustration would exist without an option?~~ See #135 
1. Watch window shows `\n`, not sure if this can be improved (not sure we can fit newlines in there, but this looks weird - screenshot below)
1. ~~Some values in watch window/repl don't seem to work (maybe async related - see screenshot below)~~ See #136
1. ~~Hovering over some variables in the editor when at a breakpoint doesn't seem to do anything (maybe async related - see previous)~~ See #136

**Comment by DanTup** [comment]
(comment made by @devoncarew in #112)

> Re: stepping into dart: library code, this can be controlled by sending a call to make that library not debuggable. A step in then would become a stepover for method in those libraries. Possibly something to expose as a user option.
> 
> And yeah, expression evaluation does not for for async methods. This is a bug, and does have a lot of impact on the usability of debugging async methods. Tooltips, the repl, and watchpoints are all impacted. Even something like trying to eval 1+2 when at a breakpoint in an async method won't work.

**Comment by DanTup** [comment]
Found some details on [setLibraryDebuggable](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#setlibrarydebuggable), though doesn't look like it's going to be easy to invert the default - we'll have to send every library ID (I guess including `isolate-patch`?)

**Comment by DanTup** [comment]
@devoncarew is there an issue in the SDK project for the async evaluation issue I can subscribe to? I've searched but can't find one :(

**Comment by devoncarew** [comment]
I'm not aware of one - this debugger may be pushing the boundaries more than others :) Feel free to open an issue - I think that single issue hits us in watchpoints, the repl, and value tooltips.

**Comment by DanTup** [comment]
Ok, I've raised https://github.com/dart-lang/sdk/issues/27167. There's not much info (feel free to add comments if you can explain it better :)) but I'll add more if it's not obvious.

**Comment by DanTup** [comment]
I've pulled these issues out into their own cases (the watch one I think is probably by design, I think that's how things would appear in VS for C# too).
