### ISSUE TITLE
Intellisense should be hidden when inside new function brackets

### ISSUE THREAD

**Issue by nklayman** [Dart-Code/Dart-Code#1254]
when you write a new function, intellisense suggestions pop up as soon as you finish `myFunc()`. They stay up when you add curly braces `myFunc() {}`. This means when you press enter to create a multiline function, the intellisense snippet item is inserted instead.
![screenshot from 2018-10-15 21-07-28](https://user-images.githubusercontent.com/12448243/46992404-c27aee00-d0be-11e8-86ac-6cd3de55c9d1.png)
Pressing enter gives:
![screenshot from 2018-10-15 21-11-02](https://user-images.githubusercontent.com/12448243/46992416-db839f00-d0be-11e8-9672-e9dc210d516f.png)
intellisense should be hidden here, so that you can add a line w/out triggering a snippet.

**Comment by nklayman** [comment]
Looks like this shouldn't happen because of [this line](https://github.com/Dart-Code/Dart-Code/blob/master/src/providers/dart_completion_item_provider.ts#L40). However, as you can see in the image, the suggestions still show.

**Comment by DanTup** [comment]
Thanks for the report! I can repro something, but I'm not sure if it's exactly what you're seeing. The issue I see is when pressing `<space>` after the parens:

Eg.:

```dart
myFunc()/* press space here, ready to type { */
```

Though I see much more than just the snippets:

<img width="511" alt="screen shot 2018-10-16 at 10 12 48 am" src="https://user-images.githubusercontent.com/1078012/47005631-11ab3800-d12c-11e8-9585-fee2de9fceb2.png">

The reason the snippet provider doesn't have code like you linked, is that it's related to trigger characters. For the non-Snippet provider, we register it like this:

```ts
context.subscriptions.push(vs.languages.registerCompletionItemProvider(filter, completionItemProvider, ...triggerCharacters));
```

The last parameter there is a set of characters that will automatically trigger the completion. We include characters like `{` in there, but we don't want completion to open when typing that inside strings (for example), so the code you found is to bail out if we think we're somewhere that completion wouldn't make sense.

However, the snippet provider is registered differently:

```ts
context.subscriptions.push(vs.languages.registerCompletionItemProvider(DART_MODE, new SnippetCompletionItemProvider("snippets/flutter.json", (uri) => util.isFlutterWorkspaceFolder(vs.workspace.getWorkspaceFolder(uri)))));
```

These don't have any trigger characters, so won't cause the completion list to open on its own.

That all said - the snippets in your list are Dart snippets, and those are provided to VS Code in a JSON file that doesn't go through any of our code at all:

https://github.com/Dart-Code/Dart-Code/blob/master/package.json#L62-L67

Is there anything in the completion list besides the Dart snippets? Could you post a full list of compare it to the [snippets file](https://github.com/Dart-Code/Dart-Code/blob/master/snippets/dart.json)?

(Also, please confirm your VS Code and Dart extension versions).

**Comment by nklayman** [comment]
For some reason, i'm not getting the issue anymore, even without the new changes. I have no idea why it started working all of a sudden. Anyway, I will close this issue. Thanks for the quick response!

**Comment by nklayman** [comment]
I remember it working fine in JS though. Anyway, it works now.

**Comment by DanTup** [comment]
No worries - thanks for reporting anyway; I'd rather a report that turns out to be nothing than not know about a possible bug (and also without this I wouldn't have fixed the bug I spotted above)!

Glad it's sorted anyway, if you do see it again, do let me know. Insiders releases can be a bit volatile, but we've been hit with breaking changes in them before, so I'd still encourage raising issues you find when using it! 👍
