### ISSUE TITLE
Trailing comma doesn't affect the formatting of assert()

### ISSUE THREAD

**Issue by apaatsio** [Dart-Code/Dart-Code#1273]
To reproduce:

1. Write line: `assert(foo != null, 'hello',);` (Note the trailing comma after 'hello')
2. Run "Format Document"

Expected output:

```dart
assert(
  foo != null,
  'hello',
);
```

Actual output:
```dart
assert(foo != null, 'hello',);
```

**Comment by DanTup** [comment]
@bwilkerson Is this one for sdk or dart_style?

**Comment by bwilkerson** [comment]
That would be for dart-style.

**Comment by DanTup** [comment]
@apaatsio Thanks for the report!

As you probably guessed from the above, the formatting in VS Code is provided by [`dart_style`](https://github.com/dart-lang/dart_style). I've copied your report to https://github.com/dart-lang/dart_style/issues/745. Once fixed there, it'll be included in a future Dart SDK where VS Code will pick it up automatically.
