### ISSUE TITLE
Debug console - custom methods

### ISSUE THREAD

**Issue by szotp** [Dart-Code/Dart-Code#1276]
Is it possible to define a method that will be always accessible in debug console? for example I have `dumpJson(dynamic jsonObject)` that turns object into json, and I would like to use that method sometimes from debug console, without needing to import it in my file.

**Comment by DanTup** [comment]
@devoncarew do you know of anything that might help with this? I can't see anything obvious (we're using `evaluateInFrame`).

**Comment by devoncarew** [comment]
I'm not certain - perhaps defining `dumpJson()` at the top level of a library, and importing that into the current library being debugged?

**Comment by szotp** [comment]
I will let you know if @devoncarew's suggestion works, I need to read on how to setup my Flutter project to have this common library. 

In Swift or C# I would not have this problem because these languages do not have a concept of importing a file. In ObjC I would use a precompiled header.

**Comment by DanTup** [comment]
By common library, I just meant a file that is already imported. There are probably files you already have imported in most of your other files, so adding it to that will make it available and if the file is used by other code it won't be removed if you run `Organize Imports`?

**Comment by szotp** [comment]
Alright. I will make base class for all my json encodable models and put dumpJson there. Thanks for support.
