### ISSUE TITLE
Code actions adds import at bottom of library

### ISSUE THREAD

**Issue by jrote1** [Dart-Code/Dart-Code#128]
![import_1](https://cloud.githubusercontent.com/assets/4202486/17968713/2fce09a8-6ac6-11e6-8839-b4bee34d11ff.png)
![import_2](https://cloud.githubusercontent.com/assets/4202486/17968714/2feebf04-6ac6-11e6-9aa5-bea62613ca9d.png)

**Comment by DanTup** [comment]
@jrote1 Did you get anywhere debugging this (or raise it against the analyzer)? Are you able to repro in a small sample?

**Comment by jrote1** [comment]
I have not managed to find out how to output from WebStorm, I will write an issue to analyzer later and link this issue.

**Comment by DanTup** [comment]
Are you able to repro it in a small sample?

**Comment by DanTup** [comment]
@jrote1 Could you try getting a log of the response when this happens? (details [here](https://github.com/Dart-Code/Dart-Code/issues/156#issuecomment-244473983))

It'd be good to check whether it's definitely the AS returning a bad offset, or something bad happening at our end.

**Comment by DanTup** [comment]
Removed analyzer tag until we have a log so we can raise with Google.

**Comment by DanTup** [comment]
I'm tidying up open issues that I can't repro and need more info. If you still have this issue and can provide the info above then please post back and I'll re-open and investigate this.
