### ISSUE TITLE
Handle errors from build_runner tasks

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#1284]
For ex. if `pub get` hasn't been run or you delete `.dart_tool` and leave generated files, it shouldn't just act as if everything was successful and silently run.

**Comment by DanTup** [comment]
Pushed some changes that detect when the build fails (or rather, than it finished with failure - whereas before it just didn't realise the build had finished), and also parses errors out to make squiggles (note: it's not as slow as the badly-converted gif makes it seem!).

![build_runner](https://user-images.githubusercontent.com/1078012/48419638-643e3b00-e750-11e8-98cd-a1ba6363c99d.gif)

@jakemac53 @natebosch this relies on parsing the output with regex (see https://github.com/dart-lang/build/issues/1167#issuecomment-438266501) but since this feature is still behind a flag (and requires you invoke the command manually or from a `preLaunchTask`) I'm probably going to include this update in the next release. It'd be good if we could agree something less fragile before it's un-flagged though (it's really neat if you're using it for things like JSON having it build-on-save and show errors directly in the editor :-))

**Comment by jakemac53** [comment]
It is pretty trivial to do custom reporting, what format would you like?

Essentially inside the [build](https://github.com/dart-lang/build/blob/master/build_runner/lib/src/generate/build.dart#L87) and [watch](https://github.com/dart-lang/build/blob/master/build_runner/lib/src/generate/watch_impl.dart#L66) methods we create a `stdIOLogListener` today unless you provide a custom `onLog(LogRecord record)` method.

We could either add another named argument to those methods (maybe a new `LogFormat` enum?) and create a different logger, or we can handle it inside the command implementations via the [SharedOptions](https://github.com/dart-lang/build/blob/master/build_runner/lib/src/entrypoint/options.dart#L36) and pass the custom `onLog` method.

The actual implementation of the logger could live either in build_runner_core or build_runner.

If you wanted to send a PR  yourself we could help get that through, or if you could give us your desired format that works also.

**Comment by DanTup** [comment]
Any format that's easily parseable would be fine but the less ambiguous the better.

Looking at the [docs](https://code.visualstudio.com/docs/editor/tasks#_defining-a-problem-matcher), the fields I can parse are:

- file
- line/column or full location (must be in form `startLine,startColumn,endLine,endColumn`)
- message
- severity (a string of "error", "warning" or "info")
- code

Something similar to the current output but a bit more structured could be:

```
[INFO] Build Started // Consistent start marker
[ERROR]
    file: some/file/path.dart
    location: 1,1,1,30
    code: error_code
    message: You did something wrong
[WARNING]
    file: some/file/path.dart
    location: 1,1,1,30
    code: warn_code
    message: You did something slightly wrong
[INFO] Build Complete // Consistent end marker, whether it was success or fail
```

There could be additional summaries if you want it more user-friendly (the user will see this output in their Terminal pane in VS Code as well as us parsing it) that just won't match our regex:

```
[INFO] Build succeeded after blah...
[SEVERE] Build failed after blah...
```

It's a bit sucky that the location and the error/warning/info need to be in specific formats (since it makes this output somewhat controlled by VS Code) but for the improved integration maybe it's worthwhile.

If it's easy for you to do and you have the capacity, you might be quicker at it than me getting up to speed, but if you're busy I don't mind having a go if you can point me in the right direction (and decide which way you'd prefer from the options you listed).

**Comment by DanTup** [comment]
I'm removing the preview flag for build_runner work in the next release. I'm going to ship this as-is (with a few tweaks) for now. If a better way to get errors is possible in future, we can update it - but it seems to work fine for now with my testing.
