### ISSUE TITLE
Properties with getter/setters show as setter functions in completion (+ symbol lists)

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#130]
When there's a property with a getter/setter, it appears like this:

![Property](https://cloud.githubusercontent.com/assets/1078012/18008642/c92994e8-6ba0-11e6-8399-4cb6267fe4fd.png)

We should show this as a property (not `setter`) and even in the case of setting, we shouldn't show it like a method.

**Comment by DanTup** [comment]
@devoncarew Do you have this same issue in Atom? I can't see anything in your completion code to handle properties. I've also noticed we [don't seem to actually get getters back from the AS](https://groups.google.com/a/dartlang.org/forum/#!topic/analyzer-discuss/khC6SJfg1-M)?

**Comment by DanTup** [comment]
This issue seems to affect the document/workspace symbol lists too.

**Comment by DanTup** [comment]
@devoncarew Do these changes seem reasonable to you? We basically show the type of a property as the detail now. We have to do some string parsing to get it from a setter but it seems solid.

Additionally, I've added `(readonly)` to get-only properties, but the way that works relies on the bad AS behaviour (we don't get getters if there are setters) so we may need to change that in future (though I'm not married to this, I'll remove it if you think it's weird).

![Properties](https://cloud.githubusercontent.com/assets/1078012/18034180/0019749e-6d2e-11e6-8249-febd0d82c01f.png)

**Comment by devoncarew** [comment]
Definitely an improvement! The display looks a little odd for setters - they have a type, but don't return a value.

**Comment by DanTup** [comment]
We don't show "setters" anymore, we only show "properties". The type just shows the type of the property (eg. the value you will get, or must set). The right side of the screenshot is a property that gets/sets a function (that was really just me testing my parsing of the string worked correctly since they can have spaces in them and I had to parse from a string).

I don't think it makes sense to show them as methods at all, since a) you can't call them as methods and b) we only have one entry that represents a property (get and/or set), not an entry for a setter?

**Comment by DanTup** [comment]
I guess my goal is for properties and fields to appear the same; since that's really how they appear from the outside. However, I've noticed some other weird quirks relating to this, I'll raise some more cases.

**Comment by DanTup** [comment]
It turns out, fields don't appear this way as I thought they did... they appear like this:

![Field](https://cloud.githubusercontent.com/assets/1078012/18035122/bcfc823c-6d46-11e6-8dbc-a56eab8187f1.png)

I think it'd be best to drop "field ->" from this so it also appears just as "String" (this makes it consistent with what I did to properties, and I don't think the field adds anything). Though there may be other stuff showing types there that I'd then also want to remove for consistency!

What do you think? I think the icons are good enough to show the types of things, I think it's a bit noisy to have in the text as well?

**Comment by devoncarew** [comment]
Yup, +1 to a more terse display (dropping the `field`).

I may be a bit unclear, but that screenshot over shows a setter displayed w/ the type `(String) => String`. We may want to adjust that, as setters don't return a value, and you don't invoke them w/ parans, so just displaying as `String` - the same as a getter - might be better.

**Comment by DanTup** [comment]
Yeah, the `String -> String` on the rigt of my screenshot is because the property is actually of type `DannyFunc` (see the two red boxes highlighted above it). A normal string property just renders `String`.

That was just me testing that if a property happened to to set/get a function I parsed it correctly, since I have to extract the type of a setter from a string. Eg. a string property setter has a `parameters` value of `(String value)" and we just want `String`. I have to split on spaces, so that made me wonder what happened if the property was a type that had nested spaces (eg. it takes/returns a function via a typedef).

Hope this makes sense!?

**Comment by DanTup** [comment]
Ok, here's my current plan:

**ClassName()** _() → classType_
**ClassName(…)** _(String blah, int blah2) → classType_
**methodName()** _() → returnType_
**methodName(…)** _(String blah, int blah2) → returnType_
**propertyName** _type_
**fieldName** _type_

**Comment by DanTup** [comment]
Here's how it looks in completion:

![Completion](https://cloud.githubusercontent.com/assets/1078012/18054113/739caf40-6dfa-11e6-8283-e3f76933d7c9.gif)

**Comment by DanTup** [comment]
I've tweaked document completion to now show `get` or `set` for properties, as previously the setters looked like methods: 

![Document symbols](https://cloud.githubusercontent.com/assets/1078012/18054391/86718bbc-6dfb-11e6-9ba8-d3522f78c9b3.png)

**Comment by DanTup** [comment]
Ugh, then we hit a problem... where to put get/set in workspace, since the filename is there. Prefixing it looks really bad, so I'm going with adding to the end. I don't think it's ideal; but open to changes if anyone has ideas.

![Workspace search](https://cloud.githubusercontent.com/assets/1078012/18054778/2116f2a0-6dfd-11e6-93a2-b024b3b16424.png)

**Comment by DanTup** [comment]
Although it's slightly inconsistent (get/set is white in workspace, grey in document) the only way to make them consistent is to make them white in the document symbol list, and I don't think that will be as good.

@devoncarew Please review (and/or test - change are in master) and see if this all feels reasonable to you. I did my testing in Insiders due to the weird bugs in stable (like the container name getting mashed).

**Comment by DanTup** [comment]
Oh, also, ignore the bad icons in completion in my first animation - seems to be a Stable bug; Insiders displays the correct icons:

![Icons](https://cloud.githubusercontent.com/assets/1078012/18054889/a839b178-6dfd-11e6-8761-3fe99969c399.png)

**Comment by DanTup** [comment]
I think current behaviour is reasonable; we can raise new issues and tweak based on feedback from using this more.
