### ISSUE TITLE
Add a command to run/debug test that spans current cursor position

### ISSUE THREAD

**Issue by stt106** [Dart-Code/Dart-Code#1301]
It's nice that it's possible to run all tests which can also bind a shortcut. But it would be equally nice to be able to run a single test, as sometimes one can work on one test for a while and just want to re-run it.

**Comment by DanTup** [comment]
@stt106 You should be able to do this with the `Run`/`Debug` links in the editor:

https://dartcode.org/releases/v2-17/#testing-improvements

and if you've moved to another file, you can re-run the `Dart: Rerun Last Debug Session` command which is bound to `Ctrl`+`Shift`+`F5` (macOS: `Cmd`+`Shift`+`F5`) .

Let me know if these don't work for you.

**Comment by stt106** [comment]
Yes, I can. Sorry wasn't being clear. I was hoping to be able to bind a shortcut to running a single test. Doesn't seem to be possible right now though it's possible to define a custom shortcut for running all tests.

**Comment by DanTup** [comment]
How will you define which test it will run? Based on the cursor location?

**Comment by stt106** [comment]
> How will you define which test it will run? Based on the cursor location?

Yes, exactly.

**Comment by stt106** [comment]
wow, this is awesome! Thanks for fixing this!

**Comment by DanTup** [comment]
Not a problem, it's a nice feature! It'd be good to get some testing before release, so if you're interested in installing a preview build with it enabled to try it out and give feedback, please let me know!

**Comment by stt106** [comment]
yes, I will be happy to test it.
I am a .net guy and this is a standard feature from Visual Studio for running tests:)

**Comment by DanTup** [comment]
@stt106 Great!

There's info on how to install a preview release here: https://dartcode.org/docs/installing-a-preview-release/
And the version you want is here: https://github.com/Dart-Code/Dart-Code/releases/tag/v2.22.0-alpha.2

It's relatively simple to install, and you'll automatically move back to the stable version once it's published. Once installed and reloaded, there will be a `Dart: Run Test At Cursor` command in the command palette and you can also add a keybinding by editing your VS Code keybindings file:

<img width="521" alt="screenshot 2019-01-02 at 4 35 16 pm" src="https://user-images.githubusercontent.com/1078012/50601563-7153ec80-0eac-11e9-9612-bbb4c69c9ce6.png">

(note: there are actually two commands - Run and Debug... the first will run without debugger, second will run with it).

Please try it out and if you have any problems, just open new issues here on GH and I'll take a look. Thanks!

**Comment by stt106** [comment]
@DanTup Just tested and it works just as expected, great stuff!
If I am a QA, I would sign it off :)

**Comment by DanTup** [comment]
Great, thanks for testing! 👍 The next release is likely to be around the end of the month, so you'll probably want to stick on this version to keep this functionality and it'll automatically move you back to stable when it releases.
