### ISSUE TITLE
When a test is deleted or renamed, it still shows in Test sections

### ISSUE THREAD

**Issue by stt106** [Dart-Code/Dart-Code#1305]
Sorry if this is known, it seems that if I delete or rename a test, the "old" test still appears in the 'Test'. In the screenshot below, the highlighted test has been moved to a different file.

![image](https://user-images.githubusercontent.com/10818648/48500479-dedf8700-e832-11e8-8d1c-145caf7f8307.png)

**Comment by DanTup** [comment]
This is unfortunately expected. At least, until you next run the whole `my_drawer_test.dart` file (or all test suites). Does it disappear when you do that?

**Comment by stt106** [comment]
Yes it does disappear so I have closed this. Thanks for looking into this.

**Comment by DanTup** [comment]
Thanks for confirming! Hopefully in the future we can improve it :-)
