### ISSUE TITLE
Regex errors in pubspec don't show the line number in dart-code

### ISSUE THREAD

**Issue by vinicioslc** [Dart-Code/Dart-Code#1307]
Print of error without line number.

![dart-import](https://user-images.githubusercontent.com/10997022/48628596-b8d6f580-e99e-11e8-8511-51887a682812.PNG)

**Comment by DanTup** [comment]
The error in the screenshot isn't actually coming from Dart Code, but this extension:

https://marketplace.visualstudio.com/items?itemName=luanpotter.dart-import

The GitHub repo for that extension appears to be this one:

https://github.com/luanpotter/vscode-dart-import

If you raise it there, hopefully they can resolve this. Thanks!

**Comment by vinicioslc** [comment]
oh im so sorry  🦆
