### ISSUE TITLE
Import statement quick fix from function

### ISSUE THREAD

**Issue by twistedinferno** [Dart-Code/Dart-Code#1318]
If I have a class defined in fileA and I press `ctrl + .` on the class name in fileB, dart-code will offer me a quickfix to import the fileA reference into fileB. However, if I try the same on a function the quick fix won't offer an import. This makes refactoring quite difficult (especially when using things like redux). Is this possible with Dart-Code or worthy of a potential update?

**Comment by DanTup** [comment]
It seems to already work ok for me:

<img width="1148" alt="screen shot 2018-11-21 at 12 55 13 pm" src="https://user-images.githubusercontent.com/1078012/48842667-bb659080-ed8c-11e8-8017-9548609fb24f.png">

The fixes come from the Dart SDK, so it may depend on your version (I'm using a nightly from a few days ago). Can you confirm what version you're on and provide a small code repro for me to debug?

Thanks!

**Comment by twistedinferno** [comment]
Ah, that is exactly what it was, I was using an old version of Dart, I've updated and it all works now.

**Comment by DanTup** [comment]
Great, thanks for confirming!
