### ISSUE TITLE
VM app debugging broken?

### ISSUE THREAD

**Issue by bergwerf** [Dart-Code/Dart-Code#1322]
It seems debugging is completely broken even with the current stable Dart (it is possible this is not the fault of Dart-Code but I decided to report it anyway). A few issues I noticed:

With Dart Run all tests I get:
```
Failed to precompile test:test:
file:///home/herman/.pub-cache/hosted/pub.dartlang.org/front_end-0.1.4/lib/src/fasta/kernel/expression_generator.dart:740:14: Error: The method 'ErroneousExpressionGenerator::buildCompoundAssignment' has fewer named arguments than those of overridden method 'KernelExpressionGenerator::buildCompoundAssignment'.
  Expression buildCompoundAssignment(Name binaryOperator, Expression value,
             ^
file:///home/herman/.pub-cache/hosted/pub.dartlang.org/front_end-0.1.4/lib/src/fasta/kernel/kernel_expression_generator.dart:177:14: Context: This is the overridden method ('buildCompoundAssignment').
  Expression buildCompoundAssignment(Name binaryOperator, Expression value,
             ^
file:///home/herman/.pub-cache/hosted/pub.dartlang.org/front_end-0.1.4/lib/src/fasta/kernel/kernel_expression_generator.dart:1424:7: Context: Override was introduced when the mixin 'ErroneousExpressionGenerator' was applied to 'KernelGenerator'.
class KernelUnresolvedNameGenerator extends KernelGenerator
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
file:///home/herman/.pub-cache/hosted/pub.dartlang.org/front_end-0.1.4/lib/src/fasta/kernel/expression_generator.dart:740:14: Error: The method 'ErroneousExpressionGenerator::buildCompoundAssignment' doesn't have the named parameter 'isPostIncDec' of overridden method 'KernelExpressionGenerator::buildCompoundAssignment'.
  Expression buildCompoundAssignment(Name binaryOperator, Expression value,
             ^
file:///home/herman/.pub-cache/hosted/pub.dartlang.org/front_end-0.1.4/lib/src/fasta/kernel/kernel_expression_generator.dart:177:14: Context: This is the overridden method ('buildCompoundAssignment').
  Expression buildCompoundAssignment(Name binaryOperator, Expression value,
             ^
file:///home/herman/.pub-cache/hosted/pub.dartlang.org/front_end-0.1.4/lib/src/fasta/kernel/kernel_expression_generator.dart:1424:7: Context: Override was introduced when the mixin 'ErroneousExpressionGenerator' was applied to 'KernelGenerator'.
class KernelUnresolvedNameGenerator extends KernelGenerator
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
file:///home/herman/.pub-cache/hosted/pub.dartlang.org/front_end-0.1.4/lib/src/fasta/kernel/expression_generator.dart:894:14: Error: The method 'ContextAwareGenerator::buildCompoundAssignment' has fewer named arguments than those of overridden method 'KernelExpressionGenerator::buildCompoundAssignment'.
  Expression buildCompoundAssignment(Name binaryOperator, Expression value,
             ^
file:///home/herman/.pub-cache/hosted/pub.dartlang.org/front_end-0.1.4/lib/src/fasta/kernel/kernel_expression_generator.dart:177:14: Context: This is the overridden method ('buildCompoundAssignment').
  Expression buildCompoundAssignment(Name binaryOperator, Expression value,
             ^
file:///home/herman/.pub-cache/hosted/pub.dartlang.org/front_end-0.1.4/lib/src/fasta/kernel/kernel_expression_generator.dart:1513:16: Context: Override was introduced when the mixin 'ContextAwareGenerator' was applied to 'KernelGenerator'.
abstract class KernelContextAwareGenerator extends KernelGenerator
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
file:///home/herman/.pub-cache/hosted/pub.dartlang.org/front_end-0.1.4/lib/src/fasta/kernel/expression_generator.dart:894:14: Error: The method 'ContextAwareGenerator::buildCompoundAssignment' doesn't have the named parameter 'isPostIncDec' of overridden method 'KernelExpressionGenerator::buildCompoundAssignment'.
  Expression buildCompoundAssignment(Name binaryOperator, Expression value,
             ^
Exited (1)
```

It is no longer possible to enable snapshots due to some issue with snapshots:
```
Snapshot not compatible with the current VM configuration: the snapshot requires 'release strong no-type_checks no-asserts no-error_on_bad_type sync_async reify_generic_functions use_field_guards use_osr x64-sysv' but the VM has 'release strong no-type_checks asserts no-error_on_bad_type sync_async reify_generic_functions use_field_guards use_osr x64-sysv'
```
For VS code launch configuration:
```
    {
      "name": "Dart",
      "program": "${file}",
      "request": "launch",
      "type": "dart",
      "vmAdditionalArgs": [
        "--enable-asserts"
      ]
    },
```

Sometimes instead of throwing the dart front_end exception the debugger pauses in some weird place:
![screenshot_20181129_220944](https://user-images.githubusercontent.com/4458965/49252183-9ecbf700-f423-11e8-9490-cbdecbcb0e4a.png)

**Comment by bergwerf** [comment]
What I tried so far: downgrade to Dart stable, `pub global activate test` (which successfully pre-compiles test).

**Comment by bergwerf** [comment]
Ok this issue is a bit silly since `pub run test` is itself broken (at least for me even in Dart stable). If you want to close this issue that is fine.

**Comment by bergwerf** [comment]
Ok it turns out`pub run test` is itself broken (at least for me even in Dart stable) because for some reason the version of the Dart `front_end` is outdated (even though I cannot find any dependency that directly depends on an older version of `front_end`). The other issue with incompatible snapshots is still interesting because I like to enable asserts when debugging.

**Comment by DanTup** [comment]
> Ok it turns out `pub run test` is itself broken

This doesn't sound good. Can you repro on a small sample or something public that can be shared? It may be worth opening an issue in the pub or sdk repo with details.

(@devoncarew @jakemac53 - does this sound familiar to anyone?)

**Comment by bergwerf** [comment]
Have you tried to run pub get on any repos?

It depends on the front_end version. There seems to be in issue in an older
version. Although no dependency (afaik) directly depends on front_end, it
apparently was stuck on an older version. Now I believe the issue is fixed
by adding and removing the newest front_end to my dependencies (which I
guess is similar to pub upgrade which I forgot to do so I think front_end
was stuck on an older version in the pubspec).

The snapshot issue (i.e. I cannot enable asserts when running the dart
debugger) is still relevant.

**Comment by bergwerf** [comment]
It turns out the snapshot issue does not appear when running non-test files. Maybe some of the automagic PubTest stuff causes it. To reproduce add this configuration to launch.json and try to run a test file (by hitting F5)

```

    {
      "name": "Dart",
      "program": "${file}",
      "request": "launch",
      "type": "dart",
      "vmAdditionalArgs": [
        "--enable-asserts"
      ]
    },
```

**Comment by pschiffmann** [comment]
I have the same "incompatible snapshot" issue. In my case, I have `"dart.vmAdditionalArgs": ["--enable-asserts"]` in my `.vscode/settings.json` and try to debug a unit test by clicking the CodeLens "debug" button. The error message reads:

> Snapshot not compatible with the current VM configuration: the snapshot requires 'release strong no-type_checks no-asserts no-error_on_bad_type sync_async reify_generic_functions use_field_guards use_osr x64-sysv' but the VM has 'release strong no-type_checks asserts no-error_on_bad_type sync_async reify_generic_functions use_field_guards use_osr x64-sysv'
> Exited (255)

I'm using VS Code version 1.29.1, Dart Code 2.21.0, Dart 2.1.0, and the test package is on version 1.5.1. Running `pub run --enable-asserts test` on the command line works fine.

**Comment by DanTup** [comment]
Actually, in my  testing just now, asserts appear enabled by default. So I think you can just remove `vmAdditionalArgs`? If there's something that doesn't work if you do that, let me know what so I can repro here and I'll investigate.

**Comment by DanTup** [comment]
I've opened https://github.com/Microsoft/vscode/issues/64193 to try and improved the experience of breaking on asserts though - seems like we get dumped into a "no source" error by default and you need to walk the stack.

LMK if anyone is still having issues with anything here (ideally with a small repro project).

**Comment by DanTup** [comment]
> but I often run test and other programs (like a web server) using the same launch configuration which is why I encountered this issue.

Since v2.18, asserts should be enabled by default on the VM too (see #1143). If you remove your `--enable-asserts` flag and see asserts not working, I consider that a bug and will aim to fix :-)

**Comment by bergwerf** [comment]
Indeed I confirmed this works for me. As far as I am concerned this issue can be closed.

As a side note, the test runner still takes a ridiculous startup time (like 2 or 3x that of running my actual tests). This is really starting to be annoying during quick testing iterations. I believe at least a significant part of this is due to the startup time of the Dart VM (which used to be almost instant in 1.0 but I guess the type system added some overhead).

**Comment by DanTup** [comment]
>  As far as I am concerned this issue can be closed.

Great, thanks for confirming!

> As a side note, the test runner still takes a ridiculous startup time

Yeah, I've noticed it too. There's an open issue about the speed of it at https://github.com/flutter/flutter/issues/15767 you may wish to subscribe to or chip in.
