### ISSUE TITLE
VSCode HMR not working with Flutter while Debugging

### ISSUE THREAD

**Issue by deadcoder0904** [Dart-Code/Dart-Code#1324]
HMR works with `flutter run` & then pressing `r` & even `R` for Live Reloading but does not work with Debugger when pressed with `fn+F5` on Mac

My simple code is -

# lib/main.dart

```dart
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text("Hello, Universe!"),
        ),
        body: Container(
          decoration: BoxDecoration(
            color: Colors.red,
          ),
          child: Text("One"),
        ),
      ),
    ));
```

And I change `One` to `Two` to test HMR but it doesn't work. The below is a log for running app & changing `One` to `Two` in the `Text` widget.

[Dart-Code-Log-2018-11-00 15-36-50.txt](https://github.com/Dart-Code/Dart-Code/files/2636827/Dart-Code-Log-2018-11-00.15-36-50.txt)

**Comment by DanTup** [comment]
> but does not work with Debugger when pressed with `fn`+`F5` on Mac

The shortcut for Hot Restart is `Ctrl`+`F5` and Hot Reload is bound to the Debugger Restart option (`Shift`+`Command`+`F5`). Whether you need to press `fn` or not may depend in your OS settings (I have mine set to always be the F keys by default). `F5` on its own is just `resume`, for example when you're at a breakpoint.

FWIW, we also hot reload on save by default (which did trigger during the session in your log).

Let me know if this solves the issue or not.

Thanks!

**Comment by deadcoder0904** [comment]
Weird works now. Again, I did `fn + F5` & nothing else you said. Thank you for making this one :)

**Comment by DanTup** [comment]
Hmm, I think pressing `fn`+`F5` may start a second debug session. If you end up with a dropdown on the end of your debug toolbar:

<img width="359" alt="screen shot 2018-12-03 at 10 31 53 am" src="https://user-images.githubusercontent.com/1078012/49368466-abcc3d00-f6e6-11e8-85b2-cade7f031e3d.png">

Then this means you have multiple debug sessions (which could result in very strange things). In this case, you should stop all of the sessions and relaunch but use the shortcuts mentioned above for restart/reload.

Let me know if you have any other issues!

**Comment by deadcoder0904** [comment]
Yes, I see the dropdown every time.

I just started Fluttering yesterday so don't know a lot about this stuff.

So I've opened up Genymotion Emulator & VSCode. Then I type

`Ctrl+F5` which does nothing.

Both `fn+F5` & `Shift+CMD+F5` do the same thing ,i.e, open the debugger with the dropdown.

There is no other session running now AFAICT. What to do now?

There is also another weird issue (only on Genymotion) which shows blank app if I try to press `fn+F5` but works if I do `flutter run --enable-software-rendering`. It also doesn't work if I put it in `.vscode/launch.json`. But I think this might not be related to your repo :)

**Comment by DanTup** [comment]
> `Ctrl`+`F5` which does nothing.

This will "Start without Debugging" which means it'll run the app, but functionality like breakpoints will not work. I suspect that you didn't leave it long enough for the debug toolbar to appear (VS Code waits for some initial initialisation to happen before showing it).

> Both `fn`+`F5` & `Shift`+`CMD`+`F5` do the same thing ,i.e, open the debugger with the dropdown.

Is it possible you pressed something twice, or the first session came from the `Ctrl`+`F5` you pressed above that appeared to not do anything?

`Shift`+`Cmd`+`F5` is to restart once you're already in a debug session. So you want to use `F5` to launch your session (and give it a second, and a debug toolbar should appear). Then when you're in a session (eg. can see the debug toolbar) you want to use:

- `Shift`+`Cmd`+`F5`: Hot Reload (same as the restart button on the toolbar)
- `Ctrl`+`F5`: Hot Restart

Note: You may need to press `fn` for all of these keypresses depending on your OS settings (whether the F keys behave as F keys by default or not - I think the default is that you need to press it, but I changed my settings to always treat F keys as F keys when in VS Code :-))

> works if I do `flutter run --enable-software-rendering`. It also doesn't work if I put it in `.vscode/launch.json`. But I think this might not be related to your repo :)

If putting `--enable-software-rendering` in the `args` property in `launch.json` doesn't work, then open an issue about that - it should work :)

Whether it should be required though, I'm not sure. That might be something to raise in flutter/flutter. I don't know whether Flutter tries to use the correct rendering for the device or not (if so, it may be fixable).

**Comment by deadcoder0904** [comment]
> I suspect that you didn't leave it long enough for the debug toolbar to appear (VS Code waits for some initial initialisation to happen before showing it).

I left it open for 30 mins now but still didn't work.

> Is it possible you pressed something twice, or the first session came from the Ctrl+F5 you pressed above that appeared to not do anything?

Nope, not possible.

> If putting --enable-software-rendering in the args property in launch.json doesn't work, then open an issue about that - it should work :)

Yeah I'll open an issue on Flutter repo, thanks :)

**Comment by deadcoder0904** [comment]
Okay, so the last one worked now. I was putting additional arguments which I found in Flutter Repo's issues but now this works

# .vscode/launch.json

```js
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Flutter",
      "request": "launch",
      "type": "dart",
      "args": ["--enable-software-rendering"]
    }
  ]
}
```

**Comment by MuhammamdArslanKhan** [comment]
the same issue, its not debugger just work by the command (flutter run) restart r, Hot reload (R). vscode' debugger (F5 and cntl+f5) both not working

**Comment by DanTup** [comment]
@MuhammamdArslanKhan if you're having issues, please file a new issue. You can capture logs using the [capture logs command](https://dartcode.org/docs/logging/#capture-logs-command) - you can untick **Analysis Server** but leave everything else ticked.
