### ISSUE TITLE
Syntax highlighting in dartdocs is bad for code blocks

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#1325]
Spotted by @timsneath 

![Code](https://user-images.githubusercontent.com/1078012/49369819-3e221000-f6ea-11e8-9e4f-8971c4d1b329.png)

The issue here is that we highlight references in `[brackets]` inside dart docs, but it's also applying to Code. When the code contains arrays, it gets highlighted as if it's a variable name.

**Comment by DanTup** [comment]
Ok, this turned out not to be the brackets, but because the TextMate grammar that we borrowed did everything as single lines and treated indented content in comments as code. That means any line of code that was indented enough was considered code, but code that was no indented (even though in a fenced block) was just comment.

Now we will detect the comments as blocks, and the fenced code blocks within them the same - this should result in all code being coloured the same (I don't know if it's a bit strong like this though):

![screen shot 2018-12-03 at 12 09 59 pm](https://user-images.githubusercontent.com/1078012/49373247-35830700-f6f5-11e8-8228-33620208c5c7.png)
![screen shot 2018-12-03 at 12 10 40 pm](https://user-images.githubusercontent.com/1078012/49373249-35830700-f6f5-11e8-9606-b06f4fd4a1dd.png)

With my new found understanding of TextMate I may try and fix up some of the other colouring issues we have (it turns out to be slightly more powerful than I previously believed).

@devoncarew @pq I'm not sure if you're also using a grammar from the same place this one came from, if so you might have the same bug and wish to update. My fix is in #1326 if you want to diff - it switches the comments to begin/while so they're all treated as one block (instead of lines) and then sues begin/end for the fenced code blocks and colours them the same as other references/indented code.

**Comment by devoncarew** [comment]
Danny, do you mind opening an issue for this on the dart atom plugin repo? We'll want to fix this there (and, I believe that grammar is used for the GitHub highlighting?)
