### ISSUE TITLE
Add an opt-in setting that will restart the analysis server when .packages changes

### ISSUE THREAD

**Issue by cokobware** [Dart-Code/Dart-Code#1334]
In a Flutter 1.0 project, when I update the pubspect.yaml file and add a dependecy in the `dependencies:` section, the plugin runs `flutter packages get` but any .dart file that then adds `import` directives for the dependency package shows that it can't locate the target URI. Any use of the package classes also show error squiggles in the editor.

I'm assuming that this is a dart-code and not a flutter issue.

Currently, restarting vscode resolves the problem.

Using:

Version: 1.29.1 (system setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

dart-code.dart-code: 2.21.1
dart-code.flutter 2.21.1

**Comment by DanTup** [comment]
Thanks for the report! Unfortunately this is currently a known issue in the SDK, tracked here -> https://github.com/dart-lang/sdk/issues/30845

I'll close this as a dupe - but also add a comment there to see if there's any update. Thanks!

**Comment by cokobware** [comment]
I tried finding if this was a duplicate issue with the plugin... sorry for
the inconvenience! Thanks for looking into it

**Comment by DanTup** [comment]
Not a problem! It's often hard to know what to search for - I'd rather people opened dupes than didn't open issues when the hit problems :-)

**Comment by DanTup** [comment]
I've going to look at adding an option as a workaround, since it seems like the bug might take a while to fix in the server.

**Comment by DanTup** [comment]
This was fixed in the server by https://github.com/dart-lang/sdk/issues/30845.
