### ISSUE TITLE
Code Snippet (Open Code Completion) Jump to the wrong position when I press Down key

### ISSUE THREAD

**Issue by sgon00** [Dart-Code/Dart-Code#1337]
OS: MacOS
VSCode: 1.29.1
Dart-Code: 2.21.1

Hi, I provide an example to show what I mean here:
In flutter code, when I type `margin:`, the code snippet popup window will come up and show a list like:

```
EdgeInsets.all()
EdgeInsets.fromLTRB()
EdgeInsets.fromWindowPadding()
etc..
```

But, when I press the `Down` key from the keyboard to select the first one, The list cursor will jump to some random places such as `CastError`. 

This is NOT specific to `magin:` and it happens to all code snippet (code completion). Btw, This is not 100% reproducible. If I use mouse to select `EdgeInsets.all()` and press enter, next time when I press `Down` key, it will jump to the correct place. 

I have no idea when this will happen, but it happens constantly (99%) of my coding history in vscode. Everytime, I hate myself to first fail using keyboard button and then call Open Code Completion again and then use Mouse to select it. Everytime, when the popup window appears, I have to think many seconds to decide if I should use Mouse or Down key. This is driving me crazy. I really hate Mouse. 

Thanks a lot.

**Comment by DanTup** [comment]
Sorry you're having trouble - are you able to capture a video/GIF showing the issue that might help me see what's happening? Is it possible that when the completion list opens that the "selected" item is off-screen?

Can you also confirm the versions of VS Code, the Dart plugin and the Dart/Flutter SDK you're using?

Thanks!

**Comment by sgon00** [comment]
I thought I had made it clear... 
Please check the recording video: [vscode_dart_issue.mp4.zip](https://github.com/Dart-Code/Dart-Code/files/2656853/vscode_dart_issue.mp4.zip)
I am not sure if the way I use vscode is correct or not. I supposed I should be able to select the first item from the popup window by keyboard. 
Regarding the versions, I have mentioned some of them. More detail:

* Dart-Code vscode plugin: 2.21.1

```
 flutter doctor -v
[✓] Flutter (Channel master, v0.11.10-pre.7, on Mac OS X 10.13.6 17G65, locale en-CN)
    • Flutter version 0.11.10-pre.7 at /Users/user/opt/flutter
    • Framework revision 57849e8285 (11 days ago), 2018-11-26 14:23:02 -0800
    • Engine revision eebc6a5895
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1
```

Thanks a lot for the quick reply.

**Comment by sgon00** [comment]
@DanTup there was actually a setting in vscode to solve this issue which I never knew before: `"editor.suggestSelection": "first",`. Thanks and closing this one.

**Comment by DanTup** [comment]
@sgon00 I think this is still a bug. Even if the completion is pre-selecting a different item by  default, it should be visible. I see the VS Code issue was closed as a dupe, but I'm not sure what of - I can't find another case that seems to describe that issue. Any ideas?

**Comment by sgon00** [comment]
@DanTup I think he means this one: https://github.com/Microsoft/vscode/issues/47102

**Comment by DanTup** [comment]
Ok, I've added a note to your (closed) issue, since if it's that, I think there's still a bug. It's possible there's another one covering the bug and I just can't find it, but we'll see what they say. Thanks!
