### ISSUE TITLE
Suggestion: Setting for automatically running 'Flutter Clean'

### ISSUE THREAD

**Issue by alantbarlow** [Dart-Code/Dart-Code#1340]
Currently when you run your flutter project, it will frequently fail requiring you to manually delete your build folder or run 'Flutter Clean'. if there was a setting that could be turned on to let you automatically run flutter clean every time you ran your project, that problem would no longer matter.

**Comment by DanTup** [comment]
Please let me know if you can provide some additional info and I'll re-open this. I'd much rather reduce/eliminate bugs that result in needing to clean frequently than just add this feature and it gets swept under the carpet. Thanks!
