### ISSUE TITLE
Support debugging "just my code" and not external libraries

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#135]
- Pressing `F10` (step over) on the last line of `main` breaks me into `dart:isolate-patch/isolate_patch.dart` at the end of `port.handler`
- Probably related, the call stack lets me walk up into the same file; again seems a bit weird, but possibly this is expected (seems a little weird to expose non-user Dart code to them though?)
- Pressing `F11` steps into SDK functions; I both like and dislike this. In C# this is an option you can enable (off by default) so that you can easily `F11` into your own code without constantly dipping into framework stuff and have to drop back out; I know Dart is a bit different but presumably the same frustration would exist without an option?

This can be fixed using [setLibraryDebuggable](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#setlibrarydebuggable).

**Comment by DanTup** [comment]
I've added some interfaces for this and implemented some code that just sets all libraries not debuggable by default, but it doesn't seem to work as expected.

Details here:
https://groups.google.com/a/dartlang.org/d/msg/vm-dev/z05DC53bxJU/Kccnl38LBAAJ

@devoncarew - maybe you've used this before? I noticed [this](https://groups.google.com/a/dartlang.org/d/topic/observatory-discuss/m8Eg7C4a3fc/discussion) when searching but couldn't find any code in dart-atom that used it. There's a [`debug-just-my-code`](https://github.com/Dart-Code/Dart-Code/tree/debug-just-my-code) branch with the tweaks I've made so far if you'd like to have a look.

**Comment by DanTup** [comment]
https://github.com/dart-lang/sdk/issues/27370

**Comment by devoncarew** [comment]
I have used this in the past (not for atom; last for the dart editor I believe). There, at isolate load I iterated on the list of libraries and set specific `dart:` ones to not debuggable. There are some that user's almost always want to set into - `dart:convert` is really more like a package: in nature - and some that may be more unlikely, like `dart:core`.

I would definitely see this as an opt-in feature myself; I've gotten used to being able to just step into everything.

Older code here (using a previous protocol):

https://github.com/dart-lang/eclipse3/blob/master/tools/plugins/com.google.dart.tools.debug.core/src/com/google/dart/tools/debug/core/server/VmConnection.java#L171

https://github.com/dart-lang/eclipse3/blob/master/tools/plugins/com.google.dart.tools.debug.core/src/com/google/dart/tools/debug/core/server/VmLibraryRef.java#L83

So, really just disabling debugging on targeted libraries.

**Comment by DanTup** [comment]
@devoncarew Hmm, that looks like a different API (calling `debuggingEnabled`), I presume an older version of the debugger API? (You also seem to only ever set it to true, but in our case the default seems to be true and I'm setting false).

Maybe it's just a bug, I'll see what comes back from the SDK Issue I opened.

> I would definitely see this as an opt-in feature myself; I've gotten used to being able to just step into everything.

Yeah, I'm happy to make it opt-in (even though I think the default behaviour is crazy); I posted in dart-misc to get some opinions before deciding, but nothing useful so far.

**Comment by devoncarew** [comment]
Yup, same functionality, but a different (now deprecated) API to access it. I don't recall exactly, but it does seem like the default was flipped from the current API.

**Comment by DanTup** [comment]
Related SDK case confirms this is a bug :(
Hoping for a fix in 1.20!

**Comment by DanTup** [comment]
I posted a poll on Twitter about whether to default this one/off. I don't know how many of the people voting actually use Dart, but I'm surprised by the results so far (note: one of the Yes votes is me!):

https://twitter.com/DartVSCode/status/777128085766467585

Currently there are 23 votes, 91% say debug just-my-code by default.

I think it might also be a more friendly option for beginners; so I might use that as the default. Will see how it feels once it's all working.

**Comment by DanTup** [comment]
This is generally working now - I've replaced the `sdkPath` passed to the debugger with a `DebugSettings` class (converted to JSON for transmission) so we can pass more options to the debugger without having to pollute `launch.json`.

I think the only remaining thing is making sure the logic for SDK libs vs Pub libs vs local libs is correct.. I'm worried about classifying things imported from the users local lib folder the same as external pub libraries. @devoncarew Do you know the best way to tell?

Current implementation looks like this:

```ts
let isSdkLibrary = (l: VMLibraryRef) => l.name.startsWith("dart.");
let isExternalLibrary = (l: VMLibraryRef) => !isSdkLibrary(l) && l.name != "";
```

This change will likely require wiping out `launch.json` (in order to replace `sdkPath` with `debugSettings`); will need to do some testing to see what the user sees here (and probably call it out in the release notes).
