### ISSUE TITLE
Exhaustive switch within function warns of bad return value

### ISSUE THREAD

**Issue by joaoritter** [Dart-Code/Dart-Code#1352]
The function is guaranteed to return a string since the switch is exhaustive. Thanks!

![image](https://user-images.githubusercontent.com/5597861/50026632-840a8e00-ff9e-11e8-9efe-959016728c3f.png)

![image](https://user-images.githubusercontent.com/5597861/50026668-9dabd580-ff9e-11e8-8613-4bd5f63cca5c.png)

**Comment by DanTup** [comment]
Unfortunately this is correct, since you can call `_routePath(null)`.

(Sorry! 😔)
