### ISSUE TITLE
Unable to list devices. Unable to discover Fuchsia devices. Please run "flutter doctor" to diagnose potential issues

### ISSUE THREAD

**Issue by deadcoder0904** [Dart-Code/Dart-Code#1357]
Every time I open VSCode with a Flutter project I get this notification

`Unable to list devices. Unable to discover Fuchsia devices. Please run "flutter doctor" to diagnose potential issues`

I have an emulator open but still it gets this notification through this extension

**Comment by DanTup** [comment]
Looks like this has been fixed by https://github.com/flutter/flutter/pull/25440 so should disappear with the next Flutter update. If not, please let me know!
