### ISSUE TITLE
Watch/hover/repl evaluation doesn't work in methods using await

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#136]
- Some values in watch window/repl don't seem to work (maybe async related - see screenshot below)
- Hovering over some variables in the editor when at a breakpoint doesn't seem to do anything (maybe async related - see previous)

Related SDK case: https://github.com/dart-lang/sdk/issues/27167

**Comment by DanTup** [comment]
Possibly related - doesn't seem to pause on exceptions in these methods unless I pause on all exceptions?

**Comment by DanTup** [comment]
@devoncarew Should've raised this sooner, it's been fixed already :) If you're running an SDK from latest code it'd be worth testing this now resolves all the issues.

Note: I also discovered that unhandled exceptions also weren't breaking, so will need to check whether that's also fixed by this (and raise a new case if not).

I don't suppose there are nightly build or something of SDKs to allow mortals like me to test without having to manually build the SDK?

**Comment by DanTup** [comment]
Oh, [dev channel](https://www.dartlang.org/install/archive) already has a `1.20.0-dev`! Can't see when it was built though?

**Comment by devoncarew** [comment]
You can see when releases were cut here: https://github.com/dart-lang/sdk/releases. Running from the dev channels would be easiest, I think.

**Comment by DanTup** [comment]
Aha, cool; didn't realise they went there too. I'll give this a test once there's another update after that fix was committed.

**Comment by devoncarew** [comment]
FYI, 1.20 is stable now. The fix for this should be available (and for the other https://github.com/Dart-Code/Dart-Code/issues?q=is%3Aissue+is%3Aopen+label%3A%22fixed+externally%3A+dart+1.20%22 issues).

**Comment by DanTup** [comment]
Good point! I've just tested, and two of them with that tag still don't work so I've removed the tag and commented back on the SDK cases.

I'm gonna push out a small release with that formatOnType thing (after a little more testing) so I can include these in release notes.
