### ISSUE TITLE
End of line being deleted when suggestion is accepted

### ISSUE THREAD

**Issue by degroote22** [Dart-Code/Dart-Code#1368]
My versions of Dart and Flutter vscode extensions are both: **2.21.1**
I'm using Flutter **1.0.0**, Dart **2.1.0**, VSCode **1.30.1**.

Let's say I'm doing this and hit enter.
![captura de tela 2018-12-28 as 17 44 13](https://user-images.githubusercontent.com/12750442/50526310-6a059b00-0ac8-11e9-9fa3-444b90063357.png)

**Sometimes** I'll end up with this:
![captura de tela 2018-12-28 as 17 46 39](https://user-images.githubusercontent.com/12750442/50526347-902b3b00-0ac8-11e9-8832-b1db1df51352.png)

Is someone else having the same issue?
Thanks 👍

**Comment by DanTup** [comment]
@degroote22 I can't repro this, but I don't have your exact code. Could you try making a small isolated example, and also run the **Dart: Capture Logs** command (tick only the `Analysis Server` option), then reproduce the issue, then click **Stop Logging** and provide the log (ensure there's nothing sensitive in it first).

Thanks!

**Comment by degroote22** [comment]
I had this:
![captura de tela 2019-01-03 as 22 17 11](https://user-images.githubusercontent.com/12750442/50668304-57e29b80-0fa5-11e9-8300-8c9aef86ac21.png)


It became this:
![captura de tela 2019-01-03 as 22 12 32](https://user-images.githubusercontent.com/12750442/50668233-ec98c980-0fa4-11e9-8a49-e21f2e41dc6f.png)

The logs: https://gist.github.com/degroote22/27c2f213b2614d0db7164457fbd04389


I believed I started recorded too early but stopped as soon as the error happened.
At around [this line](https://gist.github.com/degroote22/27c2f213b2614d0db7164457fbd04389#file-dart-code-log-txt-L229) I could see relevant content to the error.

**Comment by DanTup** [comment]
Thanks - I think the log is fine (it's better to have too much than too little, I can find the important bits easily). I'll see what I can find, thanks!

**Comment by DanTup** [comment]
Hmmm, I'm still struggling to repro. I though I knew what might be causing it, but even with fabricated code I can't trigger it.

Could you try:

1. Set the `"dart.maxLogLineLength"` setting in VS Code to something really high, like `"dart.maxLogLineLength": 99999999,`
2. Reproduce (while capturing a log) it in the smallest possible project you can (ideally a folder with just a single simple Dart file)

Then provide me with the log and the exact project you used. Don't forget to remove `maxLogLineLength` afterwards.

Thanks!

**Comment by degroote22** [comment]
I'm having a hard time reproducing it with a small project.
This bugs seems to happen only when my system is under stress and the Dart language server is somewhat slow.

I could reproduce the issue when VSCode was loading (and the language server was slow) but by the time I started logging I could no longer reproduce it.
Is there a way to start logging before VSCode was opened?

Thanks 👍

**Comment by DanTup** [comment]
> This bugs seems to happen only when my system is under stress and the Dart language server is somewhat slow.

That's what I suspected. I believe the issue may be a result of the completion being computed, but then interpreted by VS Code after you've made a change. I tried to simulate this here:

https://github.com/DanTup/dart-code-repro-1368/blob/master/src/extension.ts

However VS Code seems to handle it in all cases in my testing.

You can enable logging from startup by setting the corresponding log path and then reloading VS Code. For example, in this case you can set the `dart.analyzerLogFile` setting:

https://dartcode.org/docs/logging/#analyzer

Note: This will overwrite the existing log, so having multiple VS Code windows open will result in only the last one being logged. And the logs can also get long (esp with `"dart.maxLogLineLength": 99999999`) so be sure to remove it when you don't need it.

**Comment by DanTup** [comment]
@degroote22 Did you manage to capture a better log?

If you can reliably reproduce this on a specific item in the completion list, I could give you a build that logs more information for that specific completion that may help understand what's happening.

**Comment by DanTup** [comment]
If you're still able to reproduce this and can provide a log, please let me know.

**Comment by DanTup** [comment]
I have a better understanding of this now as a result of #1627, so will try to find a fix.
