### ISSUE TITLE
No intellisense provided calling super constructor

### ISSUE THREAD

**Issue by marcoms** [Dart-Code/Dart-Code#1369]
With the following code as an example:

```dart
class ReportCardRow extends TableRow {
  final String name;
  final int value;

  ReportCardRow(
    this.name,
    this.value,
  ): super(children: [
    TableCell(
      child: Text(name),
    ),

    TableCell(
      child: Text(value.toString()),
    ),
  ]);
}
```

Everything after the colon and before the opening square bracket gets ignored, and I'm not shown the constructor docs as I would expect.

**Comment by DanTup** [comment]
Which completion are you referring to? In testing, I did seem to get completion for things like the arg names:

<img width="640" alt="screenshot 2019-01-02 at 8 30 05 am" src="https://user-images.githubusercontent.com/1078012/50584650-c241f180-0e68-11e9-94cd-f26a93326bfd.png">

However

**Comment by DanTup** [comment]
Gotcha, thanks!

**Comment by DanTup** [comment]
I've moved this to https://github.com/dart-lang/sdk/issues/35546 since this will need fixing in the analysis server in the SDK. Thanks for the report!

**Comment by DanTup** [comment]
(I've updated the SDK issue to note that this also seems to affect hovers and signature information too)
