### ISSUE TITLE
Support user-configured folders to exclude from analysis

### ISSUE THREAD

**Issue by chalin** [Dart-Code/Dart-Code#1373]
Context: flutter/website with a flutter submodule. It would be nice to be able to exclude the flutter submodule from analysis.

**Comment by DanTup** [comment]
We already do this for PUB_CACHE, APP_DATA etc. on Windows so having a setting shouldn't be difficult.

**Comment by DanTup** [comment]
As a heads up, [I plan to remove](https://github.com/Dart-Code/Dart-Code/issues/2680) the `dart.analysisExcludedFolders` setting that was added here, as it won't work with the new LSP server. I did however fix the server not to send analysis errors for files excluded in analysis_options (https://github.com/dart-lang/sdk/commit/0aed132f4d73503dad79c6f491a993ffe58fd20c).

If you think that fix doesn't apply here and removing this will cause issues, please let me know (ideally with an example project that I can use for testing). Thanks!
