### ISSUE TITLE
Improve IntelliSense/autocomplete for types with static/constants

### ISSUE THREAD

**Issue by gabrc52** [Dart-Code/Dart-Code#1375]
When an argument of a certain type is required, suggest classes with static getters or constants of that type, for example:

```dart
ThemeData(
  primarySwatch: 
)
```

Here, the suggestion is `MaterialColor(`, but what the user probably needs is `Colors.`, so this should be the first suggestion.

```dart
Container(
  alignment: 
)
```

In this example, `Alignment.bottomCenter`, `Alignment.bottomLeft` etc should also appear as suggestions.

**Comment by DanTup** [comment]
(Note: I've edited your comment to strike out the other things that have their own issues to avoid confusion - it's better to keep a GH issue per-suggestion/issue so it's clearer when it's been done and can be closed).

The items in (and ranking of) completion items actually comes from the analysis server so this would need to be implemented in there - so it would be best to open an issue at https://github.com/dart-lang/sdk (please post the link back here).

While testing this, I noticed that values that are enums do at least appear completion list:

<img width="495" alt="screenshot 2019-01-07 at 9 29 20 am" src="https://user-images.githubusercontent.com/1078012/50760110-c1d99a00-125e-11e9-9435-58b0b200ac76.png">

It's just those using statics/consts that do not:

<img width="665" alt="screenshot 2019-01-07 at 9 29 29 am" src="https://user-images.githubusercontent.com/1078012/50760138-d6b62d80-125e-11e9-9294-959b028cd126.png">

**Comment by gabrc52** [comment]
https://github.com/dart-lang/sdk/issues/35587

**Comment by DanTup** [comment]
Great, thanks! I don't think there's anything to do in the plugin here - if changes are made in the SDK you'll get them automatically when moving to that version, so I'll resolve this as an upstream issue. Thanks!
