### ISSUE TITLE
Use flutter attach when possible to avoid rebuilds

### ISSUE THREAD

**Issue by gabrc52** [Dart-Code/Dart-Code#1377]
(For Flutter)

When the connection to the device is lost, or the Flutter app is closed or crashes, to continue debugging and hot restarting and reloading, the app has to be rebuilt.

Here, Flutter attach could be used automatically to improve the developer experience. 

If the app is run while it's installed in debug mode, it should attach to it instead of rebuilding it.

If it's open, the app should be closed and relaunched via adb while #1189 is fixed.

**Comment by DanTup** [comment]
I don't think this is currently possible because we must run `flutter attach` *before* the app launches. However, that may change in future so I'll keep this around to revisit. Thanks!

**Comment by DanTup** [comment]
The above comment is no longer accurate - you can now use the **Debug: Attach to Flutter** commands for an already-running app. If you have any issues with those, feel free to comment below or file new issues. Thanks!
