### ISSUE TITLE
Order of generic type parameters is in reverse order in debugger

### ISSUE THREAD

**Issue by justinStratis** [Dart-Code/Dart-Code#1382]
Using Dart 2.1.0, the order of any generic type parameters displayed by the debugger is in reverse order.  For clarity, the code executes correctly.  This appears to be an issue with the debugger only.

Using the following code, you will see that the types of the generic parameters are correctly printed by the program.  But, if you put a breakpoint in `genericMethod`, and either add a watch variable or hover the cursor over one of the generic types, the order they are displayed in is reversed.  For example, hovering the cursor over `TBool` shows information about `TString`.

I can reproduce this in both VS Code and Android Studio.

```dart
void main() {
  genericMethod<bool, double, int, String>();
}

void genericMethod<TBool, TDouble, TInt, TString>() {
  print('TBool: ' + TBool.toString());
  print('TDouble: ' + TDouble.toString());
  print('TInt: ' + TInt.toString());
  print('TString: ' + TString.toString());
}
```

Here is the log file.
[Dart-Code-Log-2019-00-01 12-36-12.txt](https://github.com/Dart-Code/Dart-Code/files/2733710/Dart-Code-Log-2019-00-01.12-36-12.txt)

**Comment by DanTup** [comment]
Thanks for the detailed into and log! This seems to be an issue in the Dart debugger rather than the VS Code extension so I've moved it over to https://github.com/dart-lang/sdk/issues/35581 (you may wish to Subscribe for updates).

Thanks!

**Comment by DanTup** [comment]
This has been fixed in the SDK. I've verified with the current nightly build. It might take a little while to make it to Stable releases though.
