### ISSUE TITLE
Dart icon in file browser sidebar

### ISSUE THREAD

**Issue by patarapolw** [Dart-Code/Dart-Code#1384]
Currently, it's not beautiful...

![screen shot 2019-01-09 at 09 43 25](https://user-images.githubusercontent.com/21255931/50873567-1dd52780-13f3-11e9-80db-8bee629a944d.png)

I would like to change it to

![](https://avatars1.githubusercontent.com/u/1609975?s=200&v=4)

Do you have a plan of this? Is this a right place for this?

Edit: I managed to find https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme and then, I pressed F1 and disabled folder icons.

**Comment by DanTup** [comment]
I believe that VS Code ships with Seti UI icons. I opened a request to add Dart to them here:

https://github.com/jesseweed/seti-ui/issues/325

I think if they're added there they'd make their way into the VS Code default icon set, though I haven't dug into it myself.

**Comment by DanTup** [comment]
The icons library wasn't being maintained, but someone from MS has gotten access and started merging PRs. The Dart icon has been merged and will be included in the next update (it's already available in Insiders) 🎉

**Comment by monajafi** [comment]
If you look at the following video the icon is available in older versions of VSCode or maybe the owner of that video fixed it himself
[https://www.youtube.com/watch?v=8F2uemqLwvE&list=PLJbE2Yu2zumDjfrfu8kisK9lQVcpMDDzZ](url)

**Comment by DanTup** [comment]
I believe that video is using a different icon pack to the Seti UI icons that are default in VS Code.

The update that included the icon was reverted in VS Code due to some issues but I don't know what the current status is.. @orta - do you know? were you able to resolve the issues and re-land the updates?

**Comment by monajafi** [comment]
I added the material file icon in which dart icon has included

**Comment by orta** [comment]
We figured it out and the latest release should be up to date with seti-ui

**Comment by monajafi** [comment]
@orta great job, the vscode-icons brsides dart icon has a lot of cool icons for many languages and folders etc

**Comment by orta** [comment]
Great!

**Comment by DanTup** [comment]
@orta Yep, I see the new Dart icon in latest stable - thanks! 👍
