### ISSUE TITLE
functions with types don't match functions without types' highlighting color

### ISSUE THREAD

**Issue by lukepighetti** [Dart-Code/Dart-Code#1385]
<img width="1051" alt="screen shot 2019-01-08 at 11 01 45 pm" src="https://user-images.githubusercontent.com/666539/50876133-9909ef80-1399-11e9-95d8-9351c23773f0.png">

I've noticed that functions and method with generics do not get the same color format as functions/methods without. Is this intentional? Is this a Dart-Code issue or an issue with my color palette?

Thank you!

**Comment by DanTup** [comment]
Looks like a bug to me!

**Comment by DanTup** [comment]
```dart
main() {}

void func1() {
  func2<String>();
}

void func2<T>() {
  func1();
}

class Class1 {}

class Class2<T> {}
```

Before:
![screenshot 2019-01-15 at 1 47 20 pm](https://user-images.githubusercontent.com/1078012/51184399-1965ae80-18cc-11e9-8d01-d569e8216ca5.png)

After:
![screenshot 2019-01-15 at 1 46 56 pm](https://user-images.githubusercontent.com/1078012/51184382-0c48bf80-18cc-11e9-8e70-33cd612bc1e5.png)

The only slight niggle is that if you type a `<` immediately after some text (without whitespace) it'll also trigger (for ex `if (a<10`) but we can't really fix that without "real" colouring from the server (which VS Code does not currently support).

**Comment by lukepighetti** [comment]
LGTM! Thanks Dan for the hard work. :)

**Comment by DanTup** [comment]
Np, thanks for finding/opening the issues! :-)

I think my email rules need some work - this notification should up with an "Approved" tag because it contained "LGTM" 😆

![screenshot 2019-01-15 at 3 18 34 pm](https://user-images.githubusercontent.com/1078012/51189893-ed9cf580-18d8-11e9-963c-d630ee835fcc.png)
