### ISSUE TITLE
Organize imports action moves ignore comments

### ISSUE THREAD

**Issue by sestegra** [Dart-Code/Dart-Code#1387]
Before calling `Organize imports` action, imports are as following:
```
// ignore: implementation_imports
import 'package:foo/src/foo_utils.dart';
import 'package:bar/bar.dart';
```
After calling `Organize imports` action, imports are as following:
```
import 'package:bar/bar.dart';
import 'package:foo/src/foo_utils.dart';
// ignore: implementation_imports
```

I suggest that comments with `ignore` should be considered as metadata annotation.

**Comment by DanTup** [comment]
Thanks for the report! This behaviour comes from the SDK and it seems like there's an open issue describing exactly this case:

https://github.com/dart-lang/sdk/issues/26728

I'll close this as a dupe - you may wish to subscribe and/or 👍 that issue. Thanks!
