### ISSUE TITLE
Feedback on VS Code proposed Code Action Auto Fix APIs

### ISSUE THREAD

**Issue by mjbvz** [Dart-Code/Dart-Code#1393]
Hi, I'm on the VS Code team. We are exploring extending VS Code's code actions to support automatic fixes and auto fix on save. You can find the two current proposal [here](https://github.com/Microsoft/vscode/issues/62110#issuecomment-454182230)

Your extension is a large user of code actions so we'd appreciate your feedback on these API proposals. Here are example use cases for these two areas:

- For auto fix: I delete some and now have an unused variable. This is shown as a red squiggly in the editor. I F8 to the error and then use a single keyboard shortcut to auto remove the unused variable. This fix has been marked as the preferred auto fix by your extension. Other alternative fixes could be provided in the existing lightbulb menu

- For fix all: I have a bunch of code that uses `await` outside of `async` functions. Thankfully, I've enabled `"editor.codeActionsOnSave": { "source.autoFix": true }` and your extension provides an `autofix` code action. This autofix action looks through the entire document and fixes all trivial errors (such as adding `async` modifiers safe places) in a single pass. So all I need to do is save the document and many of the simple errors are addressed

[This guide](https://code.visualstudio.com/api/advanced-topics/using-proposed-api) covers how to use VS Code's proposed APIs. Please let me know if you have any questions about these proposals, feedback on the API, or ideas for other auto-fix scenarios that you would like to see supported in VS Code

**Comment by DanTup** [comment]
@mjbvz Thanks for the info!

These ideas sound good to me, there are definitely some fixes in Dart I'm forever executing that feel like they could be automated! Some initial thoughts on the proposal:

---

It's not clear to me how the two interact. Does setting `canAutoApply` only apply to single-diagnostic fixes or will it be used by fix-all-on-save? I think these should be separate but I think the name `canAutoApply` is misleading as it seems to apply it'll run in the auto-fix-on-save. Eg.:

> I delete some  \[code\] and now have an unused variable. This is shown as a red squiggly in the editor. I F8 to the error and then use a single keyboard shortcut to auto remove the unused variable.

I presume in this case you'd be setting that fix to `canAutoApply=true` however if I write some code that creates a variable that I haven't used yet and I hit save (I'm in the habit of saving often :-)) then I wouldn't expect the variable to vanish. Something along the lines of `isPreferredFix` may be a better name?

---

> auto fix all errors of type X

In the updated proposals it seems like this isn't mentioned. Is this going to be left to the extensions as it is today?

---

I'm not sure we'd be able to test out the proposed API soon as it'd need changes in the Dart language server, but I do think it's something we may be able to make good use of.

(cc @devoncarew @bwilkerson)

**Comment by bwilkerson** [comment]
We've actually had some lengthy discussions about such a feature and have wanted to add it to our server for quite awhile. Mostly we haven't done so because other work has taken precedence, but this is a promising approach.

**Comment by mjbvz** [comment]
@DanTup Thanks for taking a look and for the feedback!

1. I really like the name `isPreferredFix` as it seems to better capture the intention of the API. Maybe just `isPreferred` so that we could potentially use this flag for other code actions types like refactorings too.

     This flag will only used for single diagnostic fixes. We thought about using it for fix-all as well, but it gets complicated to coordinate potentially overlapping fixes in VS Code. That's where the `Source.autoFix` action comes in. An extension could certainly implement `Source.autoFix` by combining the edits from all of the preferred quick fixes in a file, but I don't think we want to do this in core VS Code.

1. Yes the current proposal does not cover a `fix all errors of type X`. It wasn't as high as a priority for us since languages can provide a fairly reasonable solution by just adding another code action to the lightbulb menu.  The JS/TS, tslint, and eslint extensions do this for example. We may revisit this in the future though.

**Comment by DanTup** [comment]
> This flag will only used for single diagnostic fixes. We thought about using it for fix-all as well, but it gets complicated to coordinate potentially overlapping fixes in VS Code.

Yeah, that's what I thought - which is why I think tweaking the name would avoid some confusion. `isPreferred` seems good to me :-)

> Yes the current proposal does not cover a `fix all errors of type X`. It wasn't as high as a priority for us since languages can provide a fairly reasonable solution by just adding another code action to the lightbulb menu. 

Yeah, we're doing that in some cases in Dart too. This may make it trickier to add in future without them overlapping so if you do decide to do it, please let me know :-)

**Comment by DanTup** [comment]
Tidying up issues - I don't think there's anything to do here, but I opened two SDK issues to add support for the server (and if/when they're done, we can update Dart-Code and/or the LSP implementation).

- https://github.com/dart-lang/sdk/issues/37227: Add support for preferred-fix in analysis server 
- https://github.com/dart-lang/sdk/issues/37228: Add support for "fix all" in the analysis server
