### ISSUE TITLE
Newlines don't appear in debug console

### ISSUE THREAD

**Issue by gabrc52** [Dart-Code/Dart-Code#1400]
I'm using the Flutter attach command and v2.22.0-beta.1

![image](https://user-images.githubusercontent.com/24363938/51413178-9d6d9f80-1b33-11e9-8f16-f9fd08a142d4.png)

**Comment by DanTup** [comment]
![screenshot 2019-01-21 at 5 38 44 pm](https://user-images.githubusercontent.com/1078012/51490543-7fa67180-1da3-11e9-9538-4bfb953c4a9b.png)
<img width="1175" alt="screenshot 2019-01-21 at 5 38 48 pm" src="https://user-images.githubusercontent.com/1078012/51490544-7fa67180-1da3-11e9-9a81-5409db7785d2.png">

This isn't complete - flutter errors are still coming through mixed together.

**Comment by DanTup** [comment]
Fixed that one in a92a87e31df260b3928f614a1ca307dfa6dcd5ac. Tests might need fixing up though :-)
