### ISSUE TITLE
Refactoring: Wrap with Visibility(visible: false)

### ISSUE THREAD

**Issue by pouledodue** [Dart-Code/Dart-Code#1401]
Sometimes I just want to hide temporarly a widget while i'm coding but i want the code to stay there 

So it would be great to add to Refactorings contextual menu a  `Wrap with Visibility(visible: false)` option
so example a `Container()` would become `Visibility(visible:false, child: Container())`

It would be faster than selecting block and comment/de-comment it

**Comment by DanTup** [comment]
Thanks for the suggestion! The refactors all come directly from the SDK so this would need implementing there (and would automatically appear in both VS Code and Android Studio if it was).

I've moved the request to https://github.com/flutter/flutter/issues/26880. Thanks!
