### ISSUE TITLE
Cannot run with config flutterMode "profile"

### ISSUE THREAD

**Issue by skybur** [Dart-Code/Dart-Code#1402]
When I run my project with config flutterMode "profile", I got this error
```
Could not find an option named "track-widget-creation".
```
Here is the log file:
[Dart-Code-Log-2019-00-01 13-58-15.txt](https://github.com/Dart-Code/Dart-Code/files/2777832/Dart-Code-Log-2019-00-01.13-58-15.txt)

Note:
When I run command
```
flutter run --profile
```
from terminal it works

**Comment by DanTup** [comment]
Thanks for the report! This is fixed for the next version, but in the meantime you should be able to workaround it by explicitly disabling it for your profile/release build config:

```
"dart.flutterTrackWidgetCreation": false,
```

To avoid having to uncomment/re-comment, you could create two launch configs to make it easy to switch between these:

### launch.json

```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Flutter (Debug)",
			"type": "dart",
			"request": "launch"
		},
		{
			"name": "Flutter (Profile)",
			"type": "dart",
			"request": "launch",
			"flutterMode": "profile",
			"flutterTrackWidgetCreation": false
		}
	]
}
```

Note: VS Code will give you a squiggle to tell you `flutterTrackWidgetCreation` is not a valid option. You can ignore it in this case - we don't normally encourage overriding debug settings in this way, but it will work for something like this (and you can remove it once the next version ships).
