### ISSUE TITLE
Tooltips show hyperlinks that don't work

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#141]
The blue text here are links, but clicking them does nothing.

Maybe we can make these open the docs in the browser? Maybe even add a link at the bottom for the item this tooltip is for to do the same (since we truncate it)?

![Links](https://cloud.githubusercontent.com/assets/1078012/18033479/14a85ac0-6d1e-11e6-9072-8218b4a85d98.png)

**Comment by DanTup** [comment]
@devoncarew I'm just trying to tweak this slightly, but I can't actually figure out what these lines are doing:

```typescript
doc = doc.replace(/\[:\S+:\]/g, (match) => `[${match.substring(2, match.length - 2)}]`);
doc = doc.replace(/(\[\S+\])([^(])/g, (match, one, two) => `${one}()${two}`);
```

Could you clarify? I'm thinking anything that's just in `[brackets]` we should change the brackets to backticks and remove them (so they don't appear as links)?

Ideally, I'd love to make them hyperlinks that go to the docs, but I don't know how easily we can could get stable urls to docs (for third party packages, anyway; possibly we could do something clever with the SDK?)

**Comment by devoncarew** [comment]
The first line if change `[:foo:]` references to `[foo]` - the colon style is an older syntax, and still in use in some dart: core libs.

I can't puzzle out the second line; I should have doc'd it! Feel free to remove it.

+1 to changing to code references - the links are misleading, if we're not actually linking to anything :)

**Comment by DanTup** [comment]
@devoncarew It looks like the second one was maybe trying to parse links `[foo](bar)` but it doesn't seem to match them in my testing, or at least, it doesn't seem to do what it looks like it should (`[foo]()bar`). However, I'm not sure why that behaviour would make sense.

I'll remove it for now and make links remain as they are, and links with no destination (eg. references to other elements) get converted to code. Obviously if you see anything wonky in the future, let me know!

**Comment by DanTup** [comment]
Maybe that's what you intending? The original code and my new code aren't that different:

```typescript
doc = doc.replace(/(\[\S+\])([^(])/g, (match, one, two) => `${one}()${two}`);
doc = doc.replace(/\[(\S+)\]([^(]|$)/g, (match, one, two) => `\`${one}\`${two}`);
```
