### ISSUE TITLE
Reflow doc comments

### ISSUE THREAD

**Issue by dnfield** [Dart-Code/Dart-Code#1413]
I really enjoy using VSCode with the Flutter/Dart plugins.  I also enjoy using [Reflow Markdown](https://marketplace.visualstudio.com/items?itemName=marvhen.reflow-markdown).

One headache I have is that when I'm editing doc comments, I have to manually reflow them.  It'd be really nice if this plugin could help with that - so if I hit alt(opt) + q (or whatever hot key), it would automatically reflow the text in that doc comment block, e.g.:

```dart
/// Lorem ipsum dolor sit amet, ut mei impetus voluptaria reprimique. Timeam fastidii eos ei, malorum philosophia mei an. Ut oratio intellegam eos. Sale atomorum nec eu, detracto nominati voluptatibus nam ad. Ea falli ubique cetero per, ex sea pericula petentium repudiare. Partem rationibus interesset ei ius, ne argumentum definitiones mei.
```

Would become

```dart
/// Lorem ipsum dolor sit amet, ut mei impetus voluptaria reprimique. Timeam
/// fastidii eos ei, malorum philosophia mei an. Ut oratio intellegam eos. Sale
/// atomorum nec eu, detracto nominati voluptatibus nam ad. Ea falli ubique cetero
/// per, ex sea pericula petentium repudiare. Partem rationibus interesset ei ius,
/// ne argumentum definitiones mei.
```

And if I added a bunch of words to one of those lines later, I could again easily reflow the paragraph.

I'm not sure if this would make more sense as a separate plugin, or perhaps as a special fork of the linked existing Markdown plugin (since Dartdoc comments are basically markdown).

**Comment by DanTup** [comment]
I'd love this too! :) I think it'd make most sense in the server as a code-action (maybe that appears when the cursor is in a comment that has lines that are over 80 characters?).

@bwilkerson WDYT? Worth moving to the SDK tracker?

**Comment by bwilkerson** [comment]
I would love to have that functionality, but I want it to happen automatically on save.

Server doesn't know much about markdown, so it might be a significant implementation effort, but I think it's entirely appropriate to open an enhancement request to track it.

**Comment by dnfield** [comment]
That's fine with me.  The main reason I opened it here was the thought that somehow using the existing typescript implementation in the plugin I linked might speed things up, but this sounds like it would end up helping other editors as well (?)

**Comment by DanTup** [comment]
We could do it "client-side", but we try to avoid things that involve parsing/understanding semantics and modifying code since to do it reliable we'd end up needing to write a Dart parser on the client (and keeping it updated with language changes). And yeah, putting it in the server means other editors all get it too (and with LSP, that could be a growing number).
