### ISSUE TITLE
[FR?] highlight overridden members

### ISSUE THREAD

**Issue by lukepighetti** [Dart-Code/Dart-Code#1414]
Hi Dan, love the work you do with Dart-Code.

I had an idea that I wanted to ask you about. In Dart it is recommended to override members with the `@override` decorator, but this is optional. The reason I've heard is that you should mark your own code so that you know what is an overridden member.

Would it be possible to give overridden members their own color or maybe a little `overridden` annotation like how the tests have their own little button?

As someone who spends a lot of time in Typescript I personally have never felt the need to annotate overridden members. I have some classes in flutter where 6-7 properties are overridden and I just omit the decorator, but it would be cool to have some little visual marker to remove doubt.

Just a thought, would love to hear what you think.

Cheers,  
Luke

**Comment by DanTup** [comment]
I'm tempted to close this and instead suggest people use the lint to enforce the @override annotation. @lukepighetti wdyt? Is there any significant reason to have something injected in the editor rather than this?

**Comment by lukepighetti** [comment]
We can close this!
