### ISSUE TITLE
build_runner: add a setting for --delete-conflicting-outputs

### ISSUE THREAD

**Issue by pouledodue** [Dart-Code/Dart-Code#1415]
build_runner: add a setting for `--delete-conflicting-outputs`

Probably we could just add a setting (like `dart.vmAdditionalArgs`) that would unconditionally be appended.

**Comment by DanTup** [comment]
This can be set in your settings now:

```js
"dart.buildRunnerAdditionalArgs": [
	"--delete-conflicting-outputs"
]
```

![screenshot 2019-01-29 at 2 03 52 pm](https://user-images.githubusercontent.com/1078012/51913617-d6790000-23ce-11e9-82a3-aa1ae7dd585c.png)

**Comment by pouledodue** [comment]
beautiful

**Comment by DanTup** [comment]
There's a new beta build here that includes this functionality. Please try it out and let me know if you have any issues!

https://github.com/Dart-Code/Dart-Code/releases/tag/v2.23.0-beta.2
