### ISSUE TITLE
Strip dartdoc {@macro's from tooltips

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#1420]
It doesn't make sense to show these to users. Ideally the server would be able to give us the correct content (as the website gets) but that's a big job, so for now we should just strip the text.

![unnamed 1](https://user-images.githubusercontent.com/1078012/51621546-aba12e80-1f2c-11e9-9bf3-535baaf4c35d.png)

**Comment by dnfield** [comment]
Would you mind repurposing this to acutally display the content rather than hiding it completely?  I was about to open an issue to display it :)

One thought I have is to have something in the Flutter repo scan for Dartdoc macros like this and create a (JSON?) file the IDE could use to do these.  Would that work?

**Comment by DanTup** [comment]
> One thought I have is to have something in the Flutter repo scan for Dartdoc macros like this and create a (JSON?) file the IDE could use to do these. Would that work?

It would, but we don't have it today. This issue is to be a quick-fix to hide some useless content. There are some ideas about how to fix it properly, but they're significant work. Today dartdoc is just a one-off execution, but for this to work properly we need you to be able to modify those dartdocs, and then see the new content when you hover over it (it should work for all users own code, not just Flutter).

**Comment by DanTup** [comment]
Turns out the code we had was supposed to do this, but it was just a bit buggy because of how we handled newlines (and this didn't have any).

**Comment by DanTup** [comment]
(FWIW, this is fixed in the SDK and will be enabled in vNext -> https://github.com/Dart-Code/Dart-Code/issues/1444)

![Screenshot 2019-04-08 at 10 41 01 am](https://user-images.githubusercontent.com/1078012/55714689-00f8c200-59eb-11e9-9bd8-a9af49b89419.png)
