### ISSUE TITLE
Colored text in debug console (feature request)

### ISSUE THREAD

**Issue by n7nexus** [Dart-Code/Dart-Code#1425]
Debug console doesn't support colored text output now. 
Is there any chance to see that functionality?

For text coloring I use ansicolor package (https://pub.dartlang.org/packages/ansicolor).

**Comment by DanTup** [comment]
Can you provide some sample code and a screenshot of what's happening? Is it a Dart or Flutter project?

You say it doesn't support it "now" - does this mean it used to work? (I would assume so, but since you wrote Feature Request in the title, I'm not so sure).

**Comment by DanTup** [comment]
Thanks, I'll see what I can find. I think VS Code might only support a small set of colours, but I'll do some testing.

**Comment by DanTup** [comment]
Ok, after some digging I've found that VS Code seems to ignore colours when in the 256-color format. These should be the same colour:

```ts
// tested with TS to eliminate Dart as a variable
const t1 = "\x1B[32m       test   \x1B[0m";
const t2 = "\x1B[38;5;2m   test   \x1B[0m";
console.log(t1);
console.log(t2);
```

Outputs:

<img width="139" alt="screenshot 2019-01-28 at 10 01 09 am" src="https://user-images.githubusercontent.com/1078012/51828713-1adba180-22e4-11e9-8f76-43d5e3cad697.png">

So I've opened an issue with VS Code, please add a 👍!

https://github.com/Microsoft/vscode/issues/67217

**Comment by n7nexus** [comment]
Thanks for looking into this)

**Comment by DanTup** [comment]
No problem, I would've expected it to work!

I'll close this since it's a VS issue and once they fix it it should just working here. You may wish to subscribe to that issue for updates. If it seems like it's not being fixed in a while, then ping me back here and we can investigate whether we could put some workaround in (for ex. squishing them into the 8-color palette) to at least get some colour.

**Comment by DanTup** [comment]
FYI - there's an open PR against Code that fixes this issue. Sound like it won't make the next release though, so it's probably early May at best.

https://github.com/Microsoft/vscode/pull/70935

![image](https://user-images.githubusercontent.com/1078012/54929314-43130580-4f0d-11e9-8a31-d6bb250e325d.png)

**Comment by DanTup** [comment]
The VS Code changes have landed so this should be fixed in vNext (and in Insiders from later today/tomorrow?):

https://github.com/Microsoft/vscode/issues/67217

**Comment by Ivan-Kouznetsov** [comment]
This is definitely a Dart-specific issue. I can right now, on Windows 8.1, start cmd.exe, run node and print color text with no problems. 
![Screenshot 2020-05-03 01 48 46](https://user-images.githubusercontent.com/52215050/80909843-42d46480-8ce0-11ea-9f48-749170c23fa2.png)

Would you consider looking into how it is done in Node?
