### ISSUE TITLE
Converting stateless widget to stateful does not produce the same code as creating a stateful widget

### ISSUE THREAD

**Issue by MichaelPriebe** [Dart-Code/Dart-Code#1438]
Creating a stateful widget produces this:
```dart
class MyWidget extends StatefulWidget {
  @override
  _MyWidgetState createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  @override
  Widget build(BuildContext context) {
    return Container(
      
    );
  }
}
```

Creating a stateless widget and then converting it to stateful produces this:
```dart
class MyWidget extends StatefulWidget {
  @override
  MyWidgetState createState() {
    return new MyWidgetState();
  }
}

class MyWidgetState extends State<MyWidget> {
  @override
  Widget build(BuildContext context) {
    return Container(
      
    );
  }
}
```

The differences are:
```dart
  _MyWidgetState createState() => _MyWidgetState();
```
and
```dart
  MyWidgetState createState() {
    return new MyWidgetState();
  }
```
Which looks to be using old semantics, and not using the private variable.

**Comment by DanTup** [comment]
> Is it standard practice in Flutter to make the state class private?

I don't know for sure (I just copied from IntelliJ) but it seems that way on the website page about creating a stateful widget:

https://flutter.io/docs/development/ui/interactive#creating-a-stateful-widget

It seems quite deliberate, as there's this:

**Note:** Members or classes that start with an underscore (_) are private

> Does the method createState normally consist of a single invocation of a constructor, or does it normally require multiple statements?

The page above and all the samples I found in the Flutter repo (searching for `extends StatefulWidget`) seem to be just the constructor invocation (I guess the constructor would include any initialisation?). I'm not sure if that's a big enough sample to be reliable though!

**Comment by scheglov** [comment]
The fix landed as 460d69d08f258072a1a5c0d5b9dc70a38f9688f1.

**Comment by DanTup** [comment]
@scheglov Thanks! Though I think that change only covers one of the differences (the state class being private), the other was changing the initState method to a simple expression (I'm not sure what Dart calls these, C# called them "expression-bodied members"):

```
 _MyWidgetState createState() => _MyWidgetState();
```

**Comment by scheglov** [comment]
@DanTup Yes, one more fix should have been done.
Doing it now.
https://dart-review.googlesource.com/c/sdk/+/92101

**Comment by DanTup** [comment]
@scheglov Perfect, thanks! 👍
