### ISSUE TITLE
Support @macro on documentation comments

### ISSUE THREAD

**Issue by gabrc52** [Dart-Code/Dart-Code#1444]
For example, `MaterialApp.color`, should show 

> The primary color to use for the application in the operating system
interface.
> 
> For example, on Android this is the color used for the application in the
application switcher.

instead of

> {@macro flutter.widgets.widgetsApp.color}

See https://github.com/dart-lang/dartdoc#macros

**Comment by DanTup** [comment]
It's not currently possible to resolve these from the editor, though the `{@macro` text should at least be stripped out (see #1420). If you're still seeing the macro text in the latest version, let me know and I'll take another look.

Long-term we need to find a better way to handle this, but there sadly isn't a quick fix.

**Comment by DanTup** [comment]
This has been resolved in vNext when using a new enough version of the SDKs. It's really an SDK fix, however it currently only enables with SuggestionSets, which are on by default in v2.26.

![Screenshot 2019-04-08 at 10 40 15 am (2)](https://user-images.githubusercontent.com/1078012/55714604-d7d83180-59ea-11e9-987a-384e97ea9a13.png)

![Screenshot 2019-04-08 at 10 41 01 am](https://user-images.githubusercontent.com/1078012/55714605-d7d83180-59ea-11e9-801b-3f017920b620.png)
