### ISSUE TITLE
Dart Code seems to be confused by periodic iOS Firebase messages

### ISSUE THREAD

**Issue by kika** [Dart-Code/Dart-Code#1453]
```

console.ts:134 [Extension Host] Unexpected non-JSON message, assuming normal stdout (SyntaxError: Unexpected token C in JSON at position 2)

SyntaxError: Unexpected token C in JSON at position 2
	at JSON.parse (<anonymous>)
	at FlutterRun.handleMessage (/Users/kika/.vscode/extensions/dart-code.dart-code-2.22.3/out/src/services/stdio_service.js:96:24)
	at processMessageBuffer.fullBuffer.split.filter.forEach (/Users/kika/.vscode/extensions/dart-code.dart-code-2.22.3/out/src/services/stdio_service.js:84:83)
	at Array.forEach (<anonymous>)
	at FlutterRun.processMessageBuffer (/Users/kika/.vscode/extensions/dart-code.dart-code-2.22.3/out/src/services/stdio_service.js:84:63)
	at Socket.createProcess.process.stdout.on (/Users/kika/.vscode/extensions/dart-code.dart-code-2.22.3/out/src/services/stdio_service.js:37:22)
	at Socket.emit (events.js:187:15)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:260:13)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)

	[C2738.1 56AF2642-B129-4592-9268-EC19CE251738 2601:647:5800:9018:8920:d5d1:f423:355e.61971<->2607:f8b0:4005:80a::200a.443]
```

This is apparently being caused by messages printed to debug console regularly by the Firebase iOS module. Like:
```
[C2747.1 86B731BC-6101-4AAD-B778-2F76C21C57B5 2601:647:5800:9018:8920:d5d1:f423:355e.62367<->2607:f8b0:4005:80a::200a.443]
	Connected Path: satisfied (Path is satisfied), interface: en1
	Duration: 0.275s, DNS @0.000s took 0.002s, TCP @0.004s took 0.011s, TLS took 0.057s
	bytes in/out: 4984/1891, packets in/out: 11/9, rtt: 0.010s, retransmitted packets: 0, out-of-order packets: 0
```

**Comment by DanTup** [comment]
Thanks! This is sort-of a known issue. Flutter's messages come surrounded in brackets so we see this, try JSON parsing it to see if it's a command, and warn if it's not.

I'll try making the check more strict so it will pass-through more messages without trying to parse them (for ex surrounded by `[{` and `}]`) which should solve this (seemingly common) case.

@devoncarew we talked about this some time ago; routing stdout into JSON would be the ideal fix, as there's no ambiguity. We've had issues before where JSON has been printed in brackets from the flutter app which just looks like the communication protocol to us (#483).

**Comment by DanTup** [comment]
@kika There's a new Beta for v2.23 with this fix if you'd like to try it out:

https://github.com/Dart-Code/Dart-Code/releases/tag/v2.23.0-beta.4

There's more info on installing previews [here](https://dartcode.org/docs/installing-a-preview-release/) if you need it. You'll automatically switch back to stable releases when the next release goes out.

**Comment by kika** [comment]
@DanTup Would love to. Do you know if the VSIX file will be posted there later or I should try to build it myself?

**Comment by DanTup** [comment]
Whoops! Gimmie a min :)

**Comment by DanTup** [comment]
Strange... When I edit that release, the file is there with an exclamation mark and a tooltip saying to delete it and upload it again. No idea why it didn't work! At least it wasn't just that I forgot 🙃

Anyway, after re-uploading it seems to have persisted. Let me know how you get on!

**Comment by kika** [comment]
@DanTup looks good so far! Thanks a lot!

**Comment by DanTup** [comment]
Great, thanks for confirming :-)
