### ISSUE TITLE
firebase_appbc14040

### ISSUE THREAD

**Issue by zeeshan-ali** [Dart-Code/Dart-Code#1459]
when i am launching a flutter app into my android app these errors occure 

Launching lib\main.dart on J7 Pro in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew null'...

The Gradle project does not define a task suitable for the requested build.
Review the android/app/build.gradle file and ensure it defines a debug build type.
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

FAILURE: Build failed with an exception.

* What went wrong:
Task 'null' not found in root project 'android'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
         *********************************************************
WARNING: This version of cloud_firestore will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************
Finished with error: Gradle build failed: 1

**Comment by DanTup** [comment]
Do you see the same failure if you run `flutter run` from the terminal (outside of VS Code)? If so, it would be better raising this at https://github.com/flutter/flutter since it doesn't seem like this is fixable in the VS Code plugin.

Thanks!

**Comment by BrainstormLimitless** [comment]
It looks like the warning about migrating to [AndroidX](https://developer.android.com/jetpack/androidx/).
In your pubspec.yaml file  under dependencies fix the version of the cloud_firestore to the following:

cloud_firestore: 0.8.2+3 

This will avoid needing to migrate to AndroidX as per 
https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility

I hope that helps.

**Comment by DanTup** [comment]
@BrainstormLimitless Thanks for the info!

@zeeshan-ali Can you confirm if this resolves your issue?

**Comment by DanTup** [comment]
Closing this as it seems unrelated to the VS Code plugin and there was no response above. Please let me know if you think this is something that does looking into.
