### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by srgbrito** [Dart-Code/Dart-Code#1462]
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `2.22.3`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/sergio/Dart-Code.dart-code-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by DanTup** [comment]
@srgbrito Thanks for the report! In the message it says:

> Make sure to **attach** this file from your _home_-directory

Are you able to attach that file?

Could you also test if this beta version solves the issue (assuming you can reliably repro):

https://github.com/Dart-Code/Dart-Code/releases/tag/v2.23.0-beta.4

It has some fixes to address some performance issues (like #1441) that I wonder if are the cause.

**Comment by DanTup** [comment]
Please let me know if you're able to provide the file mentioned in the first message. Unfortunately I can't investigate this without it (though I really would like to).
