### ISSUE TITLE
Visual Studio Code - Dart - how to place open brace on new line?

### ISSUE THREAD

**Issue by nadjibnet** [Dart-Code/Dart-Code#1463]
How to configure visual studio code to place open brace on new line?

Thanks

**Comment by DanTup** [comment]
Unfortunately this isn't currently possible (for Dart), the formatting is using [dart_style](https://github.com/dart-lang/dart_style).

There's an open request for a customisable formatter at #914 though it's not considered a priority right now. You can subscribe to the issue for updates and add a 👍 to show support!

**Comment by tarunmali** [comment]
Any updates?

**Comment by nicolasmol** [comment]
In the opposite way : is there a way to automatically typing on a new line when opening brace/parenthesis ?

**Comment by DanTup** [comment]
@nicolasmol that is not supported, you'd need to press `<enter>` yourself. It would be difficult to do this reliably without doing it in cases where it should not happen (such as when typing inside a string). Analyzing the code is asynchronous and we cannot stall the editor after you press `{` while figuring out whether to insert a newline (at least not without forcing all keystrokes through the VS Code extension host [which leads to bad performance](https://github.com/microsoft/vscode/issues/75627)).
