### ISSUE TITLE
Intellisense sometimes takes forever to load

### ISSUE THREAD

**Issue by samuelsonokoi** [Dart-Code/Dart-Code#1464]
Been having issues lately with the dart intellisense, on my lucky days it loads in like 5 to 10mins of launching my vscode but these days it takes forever and most times I have to code without intellisense. I don't know if it's an issue for Linux users also but I use an Ubuntu 16.04LTS

**Comment by DanTup** [comment]
Could you try running the "Dart: Capture Logs" command, then reproducing the issue a little and then clicking "Stop Logging" and attaching the log (note: it may contain contents from your files so review before attaching).

Also click Help -> Toggle Developer Tools and check if there are any errors warnings listed in the console tab.

**Comment by samuelsonokoi** [comment]
Thank you @DanTup for responding.

Running the "Dart: Capture Logs" command i got the following results below

[Dart-Code-Log-2019-01-05 11-22-29.txt](https://github.com/Dart-Code/Dart-Code/files/2868870/Dart-Code-Log-2019-01-05.11-22-29.txt)

Also i took a snapshot i got from the "Toggle Developer Tools"

![toggle-console-snapshot](https://user-images.githubusercontent.com/12806939/52851326-1ef62480-3116-11e9-8ecf-d24ce850c3d6.png)

I hope this helps.

**Comment by samuelsonokoi** [comment]
[console-log-file.log](https://github.com/Dart-Code/Dart-Code/files/2868940/console-log-file.log)

that might also help.

**Comment by DanTup** [comment]
Something definitely seems wrong in that log file, since in 20 seconds there are lots of requests sent but 0 responses. Could you try enabling the [extension log](https://dartcode.org/docs/logging/#extension) and the [analysis server log](https://dartcode.org/docs/logging/#analyzer) then restart VS Code and reproduce, then take a copy of the logs? (be sure to remove the log settings afterwards to avoid reduced performance from lots of logging).

Btw, as an aside, in your console log it shows a warning that the extension host is not responding, and that the vscode-icons is consuming a lot of CPU (twice as much as Dart Code - and I think Dart Code is probably using more than it should right now, there are some fixes in the upcoming release). You may want to raise an issue against that extension with a copy of that console so they can do some profiling.

**Comment by samuelsonokoi** [comment]
Thank you so much for bringing that to my notice, i will raise an issue with a copy of the console as advised. I just updated the dartcode extension.

here is what i had from the extension log
[extension-log.txt](https://github.com/Dart-Code/Dart-Code/files/2872221/extension-log.txt)

the analysis server log file contains this
[analysis-log.txt](https://github.com/Dart-Code/Dart-Code/files/2872223/analysis-log.txt)

**Comment by DanTup** [comment]
This does look very slow. How big is the folder `/home/samuelson/Projects`? Does it have a large number of folders/files inside there? If you just open the project you're working on directly do you see an improvement?

**Comment by samuelsonokoi** [comment]
The Projects folder has a lot of folders in it, it turns out opening the project folder i'm working on fires the intellisense in no time, i will still test this further and revert back to you.

**Comment by DanTup** [comment]
@samuelsonokoi Any progress on this? Opening bigger folders will definitely slow things down, but the performance in your log is very bad. How big is the folder?

**Comment by samuelsonokoi** [comment]
Yes it's works well with opening fewer projects or just the current project folder. the folder was big though but it's okay now, it seems the problem was with opening too many folders in the same folder workspace.

**Comment by DanTup** [comment]
Ok cool. Though are you able to give an idea of how big the folder was (file size, of number of files)? It'd be good to make sure our ideas of big are similar. We don't want to fall over on folders that aren't actually that big. Thanks!

**Comment by samuelsonokoi** [comment]
Well i found out that it's really huge like above 10GB file size

**Comment by DanTup** [comment]
Ah, ok - then assuming that's come lots of files rather than just big files, I think probably it is bigger than we'd expect to handle quickly. Thanks!

**Comment by samuelsonokoi** [comment]
You're welcome, thank you so much for the help. I really appreciate the
work you're doing.


Best Regards,
Samuelson Okoi
+2348184193891 / +2348161142911
hello@samuelsonokoi.com -www.samuelsonokoi.com

Software Developer | Entrepreneur | Dart / GoLang | AngularDart / Angular |
Firebase | Ionic | Fullstack Dev | Remote / Part Time / Freelance |
GitHub - https://github.com/samuelsonokoi
