### ISSUE TITLE
Hide errors in generated files in .dart_tool

### ISSUE THREAD

**Issue by bergwerf** [Dart-Code/Dart-Code#1465]
Angular generates a lot of files in .dart_tool that have issues such as parent libraries that do not exist or variable naming that does not follow conventions. I can hide these by typing `!.dart_tool` in the filter, but still the high problem count displayed in the problem tab is somewhat annoying. I can, unfortunately, not tell the analyzer to exclude the dart tool directory since https://github.com/dart-lang/sdk/issues/33778 (and it seems like this bug might be around for another while). What do you think about adding a secondary filter in the dart vs code plugin?

**Comment by DanTup** [comment]
> What do you think about adding a secondary filter in the dart vs code plugin?

It's kinda hacky, but honestly the more important thing to me is that things work well for users, so assuming there are no negative effects of this, I think it's a reasonable fix. I've asked for some more confirmation at https://github.com/dart-lang/sdk/issues/33778#issuecomment-464672762 though since I'm not entirely familiar with what goes into this folder and whether you'd ever want to see the errors.

**Comment by bergwerf** [comment]
You could make it opt-in with a pop-up asking if you want to opt-in when an
error occurs in dart_tool for the first time.

I believe in principle errors should not occur there, but when you have to
debug dependencies (in particular builders) you might want to take a look
there.

**Comment by DanTup** [comment]
Sorry for the lack of response here - I started looking at the related Dart issues, but I got stuck/confused. If we can get it fixed there reasonable soon, I think we can avoid any workaround here. If not, I'll see what I can do though.

**Comment by bergwerf** [comment]
@DanTup no problem, this is a minor issue. More pressing was the debugger that didn't pause on breakpoints ;P (I think they fixed something but it's not yet released).

**Comment by DanTup** [comment]
If you mean breakpoints in Parts, that has indeed been fixed :) You can grab a nightly from https://gsdview.appspot.com/dart-archive/channels/be/raw/latest/sdk/ to use until it hits dev/stable.

**Comment by DanTup** [comment]
This was fixed in https://github.com/dart-lang/sdk/issues/33778 :-)
