### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Bristonmekus** [Dart-Code/Dart-Code#1467]
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `2.22.3`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/mac/Dart-Code.dart-code-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by DanTup** [comment]
@Bristonmekus 

> Make sure to **attach** this file from your _home_-directory: `/Users/mac/Dart-Code.dart-code-unresponsive.cpuprofile.txt`

Are you able to supply this file?

**Comment by DanTup** [comment]
Could you also try upgrading to v2.23.0 of the extensions as there were some performance improvements in there.

**Comment by DanTup** [comment]
Please let me know if you're able to provide the file mentioned in the first message. Unfortunately I can't investigate this without it (though I really would like to).
