### ISSUE TITLE
The Dart Analyzer has terminated when dart code in symlink directory.

### ISSUE THREAD

**Issue by shazhou** [Dart-Code/Dart-Code#1471]
Flutter: 1.0
Dart: 2.1.0

Here's log:
![image](https://user-images.githubusercontent.com/1773436/53001816-7c67d980-3466-11e9-9a78-4c91969095ef.png)

I found this issue only when dart code in .symlink directory. Once I delete .symlink directory, the dart analyzer works fine. BUT without .symlink directory, I cannot run flutter code correctly.

**Comment by DanTup** [comment]
Can you clarify what you mean by a ".symlink directory"? If I have a working project, what steps should I perform to reproduce what you've done? Thanks!

**Comment by shazhou** [comment]
Thanks for replying.
I found this problem only happened in certain project.
In flutter demo and other projects the analyzer works fine.
I will close this issue and relocate the problem.

**Comment by DanTup** [comment]
I had a quick search for this error, and found that the Dart VM may have issues if there are characters using different encodings in filenames, could that be it?

In any case, if you're unable to figure it out but can provide some steps to reproduce I'm happy to take a look and see if I can figure out what's up. Thanks!
