### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Gamaliel** [Dart-Code/Dart-Code#1476]
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `2.23.1`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.31.1`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by Gamaliel** [comment]
I recibe this warning message... I don't know what it is, the plugin looks operate fine

**Comment by DanTup** [comment]
When this happens, did it give you a CPU profile file? The other reports  like this included lines like this:

> ⚠️ Make sure to **attach** this file from your _home_-directory: `/Users/mac/Dart-Code.dart-code-unresponsive.cpuprofile.txt` ⚠️

I'm unable to reproduce the issue so need a CPU profile in order to investigate.

**Comment by DanTup** [comment]
I can't do anything here without the CPU profile, so if you're able to provide one when this happens please do, and I'll re-open this.
