### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by sylvesterdas** [Dart-Code/Dart-Code#1481]
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `2.23.1`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/sylvesterdas/Dart-Code.dart-code-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by DanTup** [comment]
@sylvesterdas in the message above it has:

> ⚠️ Make sure to **attach** this file from your _home_-directory: `/Users/sylvesterdas/Dart-Code.dart-code-unresponsive.cpuprofile.txt` ⚠️

Are you able to supply this file? I can't reproduce this issue so need the profiling file to investigate (there have been a few issues raise like this, but none have yet supplied the file).

Thanks!

**Comment by sylvesterdas** [comment]
/Users/sylvesterdas/Dart-Code.dart-code-unresponsive.cpuprofile.txt

This file seems to be corrupted
How can I fix this?

**Comment by DanTup** [comment]
@sylvesterdas What do you mean by corrupted? It's not actually a text file, it's binary profiling data. You can use the instructions in the link in your post to open it (using Dev Tools -> JavaScript profiler) if you want to review it.

I believe it's been stripped of all sensitive info/PII by VS Code but if you'd rather share it with me privately than post it here, you could zip it up and email it to logs @ dartcode.org.

Thanks!

**Comment by sylvesterdas** [comment]
Reinstalled the software. No more load issue.

**Comment by DanTup** [comment]
I'm not sure a reinstall would fix an issue like this, so it might just be intermittent. If you do see it again, please do supply the profile file. I've had many reports of this and no files, so I'm unable to look at what's taking a long time :(
