### ISSUE TITLE
Autocomplete removing preceding space

### ISSUE THREAD

**Issue by mayorbyrne** [Dart-Code/Dart-Code#1483]
When I try and set a value using autocomplete, sometimes the editor removes the preceding space. If I want something that looks like `note.x = dropAreaBG.x`, if I autocomplete on `dropAreaBG`, the end results looks like `note.x =dropAreaBG.x`.

I've added a gif that illustrates what I'm seeing. Since this doesn't seem to happen when editing js, it feels like a dart extension issue.

![autocomplete gif](https://i.stack.imgur.com/ZLLfh.gif)

**Comment by DanTup** [comment]
Yep, definitely a bug! Possibly related to us putting a space in `filterText` (suggested at https://github.com/Microsoft/vscode/issues/66860#issuecomment-456208542). I'll see what I can find. Thanks!

**Comment by DanTup** [comment]
Unfortunately VS Code doesn't handle what we were trying to do here very well, so I've had to remove `=` and `:` as trigger completion characters. This means completion won't open automatically after typing those (but will when you type another character, or manually invoke with Ctrl+Space).

**Comment by alex9153** [comment]
I have the same problem. Is there any solution?

**Comment by DanTup** [comment]
@alex9153 What version of the Dart extension do you have? This should be fixed in the latest release.

**Comment by alex9153** [comment]
Just updated to 2.25.0 ... seems like error is gone.
