### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by kamel912** [Dart-Code/Dart-Code#1484]
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `2.23.1`
- OS Version: `Darwin x64 18.0.0`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/mohamedkamel/Dart-Code.dart-code-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by DanTup** [comment]
@kamel912 in the message above it has:

> ⚠️ Make sure to **attach** this file from your _home_-directory: `/Users/mohamedkamel/Dart-Code.dart-code-unresponsive.cpuprofile.txt` ⚠️

Are you able to supply this file? I can't reproduce this issue so need the profiling file to investigate (there have been a few issues raised like this, but none have yet supplied the file).

Thanks!

**Comment by DanTup** [comment]
I can't do anything here without the CPU profile, so if you're able to provide one when this happens please do, and I'll re-open this.
