### ISSUE TITLE
Add build-number and build-name for flutter in launch.json

### ISSUE THREAD

**Issue by Noyal** [Dart-Code/Dart-Code#1486]
This is current launch.json,
```json
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Flutter",
            "request": "launch",
            "type": "dart",
            "program": "lib/main.dart",
            "args": [
                "--flavor",
                "development"
            ]
        }
    ]
```

How can I setup build-number and build-name for Flutter.

**Comment by DanTup** [comment]
Looking at the code, I think `build-number` only applies when running `flutter build`? The launch config here is for `flutter run`. Can you clarify what you're trying to do with it?

**Comment by Noyal** [comment]
I added versionCode and versionNumber  as required in the build.gradle file. After I have upgraded the flutter to 1.2, it is clearing the existing values in local.properties file in each flutter run in debug mode.

**Comment by Noyal** [comment]
> I added versionCode and versionNumber as required in the build.gradle file. After I have upgraded the flutter to 1.2, it is clearing the existing values in local.properties file in each flutter run in debug mode.

**Comment by DanTup** [comment]
I'm not familiar with these values, but as far as I can tell the `flutter.versionName` field is being generated from the value in `pubspec.yaml` when you build. So I think you're supposed to update it there.

I think this is more of a Flutter question than related to the VS Code plugin though, so there may be people with more knowledge about this in the Flutter repo, or in the Flutter Gitter room: https://gitter.im/flutter/flutter

**Comment by Noyal** [comment]
We have the defaultConfig in build.gradle, which has the versionCode and versionName. Which need to changed for every successful build to push to store, 
By default it is fetched from pubspec.yaml file, but when we need to change automatically, hence we used flutter build command, using that we can pass in the build-name and build-number.
But this affects the running the app from vs code, as I cannot find a way to pass build number.
If you think its a Flutter question. I will report it there.

**Comment by DanTup** [comment]
I'm not sure I totally understand. Do you want the pubspec version *not* to overwrite what's in the file?

Do you see the same issue if you run outside of VS Code (eg. using `flutter run` from the terminal)?

**Comment by Noyal** [comment]
Because of Pubspec i m not able to override the when using flutter build. So I comment the version from pubspec.

**Comment by keshava19** [comment]
* Error running Gradle:
ProcessException: Process "SomePath\android\gradlew.bat" exited abnormally:

FAILURE: Build failed with an exception.

* Where:
Build file 'SomePath\android\app\build.gradle' line: 16

* What went wrong:
A problem occurred evaluating project ':app'.
> versionCode not found. Define flutter.versionCode in the local.properties file.

**Comment by DanTup** [comment]
@Noyal I'm not sure I'm a very good person to advise on this. If the issue is reproducible by using `flutter run` outside of VS Code, then it would be best raise at flutter/flutter or asking the the Gitter room/StackOverflow.

If running outside of VS Code does *not* reproduce the same issue, and it only occurs within VS Code, then I'm happy to try and track down why. Just let me know exactly what you did and what happened both in the terminal, and when running from VS Code.

Thanks!

**Comment by Noyal** [comment]
It is throwing error when using flutter run. I have to take it up in Flutter repo. Thanks for your help
