### ISSUE TITLE
Dart DevTools (Widget Inspector) looks broken

### ISSUE THREAD

**Issue by Sh1d0w** [Dart-Code/Dart-Code#1487]
Just updated to the latest version 2.24 and this is how it looks when I launch the Dart DevTools:

<img width="1779" alt="screenshot 2019-02-27 at 11 12 10" src="https://user-images.githubusercontent.com/5074917/53478983-bd707700-3a80-11e9-855c-5239e106043b.png">

The widget attributes seems to overflow the widget name and everything becomes unreadable.

**Comment by DanTup** [comment]
Thanks for the report! I've moved this over to the DevTools repo at https://github.com/flutter/devtools/issues/367. Could you add some notes to that issue about what OS/browser/version you're using, and whether there are any errors in the developer console? Thanks!
