### ISSUE TITLE
Embed DevTools inside the VS Code window

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#1488]
There are other extensions doing things like this:

https://marketplace.visualstudio.com/items?itemName=nrwl.angular-console

I've done a little testing and managed to get the DevTools to render, but we may hit restrictions of running inside this window. We may also want to wait until VS Code supports [multiple-windows/monitors](https://github.com/Microsoft/vscode/issues/2686) to avoid having two ways to launch from within VS Code.

**Comment by jacob314** [comment]
We have made sure all the code in `package:devtools` run in both a light and dark theme to make this integrate be seamless.

**Comment by DanTup** [comment]
This is shipping behind a preview flag (`dart.previewEmbeddedDevTools`) in the next version. There's a beta version with it included at https://github.com/Dart-Code/Dart-Code/releases/tag/v3.12.0-beta.1.
