### ISSUE TITLE
"No tests match regular expression" when running tests with "Dart: Run Test At Cursor" command

### ISSUE THREAD

**Issue by zenkimoto** [Dart-Code/Dart-Code#1492]
When calling the `Dart: Run Test At Cursor` command and the selected test is inside of a `group()`, the test runner errors out with `No tests match regular expression "^widget tests$".`.

The following code reproduces the error.  _(Just add a group to the default generated test and add a `group()` and run the `Dart: Run Test At Cursor` command.)_

```
// This is a basic Flutter widget test.
//
// To perform an interaction with a widget in your test, use the WidgetTester
// utility that Flutter provides. For example, you can send tap and scroll
// gestures. You can also use WidgetTester to find child widgets in the widget
// tree, read text, and verify that the values of widget properties are correct.

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:radial_menu/main.dart';

void main() {
  group("widget tests", () {
    testWidgets('Counter increments smoke test', (WidgetTester tester) async {
      // Build our app and trigger a frame.
      await tester.pumpWidget(MyApp());

      // Verify that our counter starts at 0.
      expect(find.text('0'), findsOneWidget);
      expect(find.text('1'), findsNothing);

      // Tap the '+' icon and trigger a frame.
      await tester.tap(find.byIcon(Icons.add));
      await tester.pump();

      // Verify that our counter has incremented.
      expect(find.text('0'), findsNothing);
      expect(find.text('1'), findsOneWidget);
    });
  });
}
```

In the debug console, you'll see:

```
No tests match regular expression "^widget tests$".
Exited (1)
```

**Comment by DanTup** [comment]
Thanks for the report! This turns out to be a bug in Flutter, though coincidentally one I added 😱

When fixing #1421, I apparently only tested bare tests. I've opened https://github.com/flutter/flutter/pull/28638 with a fix in Flutter, which will fix this, and I've also added some additional integration tests in Dart Code that will enable once the fix lands in Flutter.

**Comment by zenkimoto** [comment]
Sounds great!  Thanks @DanTup!

**Comment by DanTup** [comment]
I've landed the fix in Flutter, so if you're on `master` and re-sync, it should work as you'd expect (otherwise, you'll get the fix when whatever channel you're on next updates). Let me know if you still have issues (or find any others). Thanks!

**Comment by danwulff** [comment]
Sadly this did not land in v1.2.1. So us Stable channel folks have to wait until the next Stable release 😢

**Comment by DanTup** [comment]
That's right, it was merged after the that build. However, the `beta` branch does have the fix and is usually pretty stable - you could try temporarily switching to that until the next release.
