### ISSUE TITLE
Consider showing commands like "Open DevTools" when not debugging, and open a message when run

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#1495]
A few people have mentioned not being able to find this command. It may make sense to keep it in the palette and just show a message if people run it without a debug session explaining they should launch the app first.

**Comment by sollematthew** [comment]
For some context: [confused people](https://www.reddit.com/r/FlutterDev/comments/avrjwr/vs_code_extension_adds_dart_devtools_integration/).
