### ISSUE TITLE
Support launching DevTools with the dark theme

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#1496]
Similar to #1050.

**Comment by audkar** [comment]
> If we add support, it may have to be a user setting in VS Code to let you choose which theme you want?

Dark theme is worth my effort to change user setting manually :)

**Comment by DanTup** [comment]
Dark theme will be default from vNext. There's a new setting that lets you set the theme:

```"dart.theme": "light" // or "dark"```

This controls both the icons in tooltips and the DevTools theme. If it turns out that people would like to use different themes for VS Code/icons than DevTools, we can add a separate setting in future.

**Comment by DanTup** [comment]
Not totally happy with how the Dark theme looks right now, so undoing this and re-opening, and will re-evaluate before this version ships.

**Comment by DanTup** [comment]
There are two settings in vNext:

dart.theme (defaults to dark)
dart.devToolsTheme (defaults to light)

When the Dark Theme is more polished, I'll change the default of `dart.devToolsTheme`, but for now you can opt-in to it manually.
