### ISSUE TITLE
Nested /* multi-line */ comments do not colour properly

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#1498]
Looks like our original fix for this only covered those starting with `/**`, see https://github.com/Dart-Code/Dart-Code/issues/456#issuecomment-468921252 (@apaatsio).

---

I think this should be reopened. I'm still experiencing this.

![vscode_dart_nested_comments_highlighting](https://user-images.githubusercontent.com/195210/53682639-04b46d00-3cf8-11e9-8074-07b77c3e6586.png)

Dart Code: 2.24.0
Dart VM version: 2.1.2-dev.0.0.flutter-0a7dcf17eb (Tue Feb 12 01:59:15 2019 +0000) on "linux_x64"
VSCode: 1.31.1

**Comment by DanTup** [comment]
Before/after:

<img width="588" alt="Screenshot 2019-03-11 at 1 10 38 pm" src="https://user-images.githubusercontent.com/1078012/54126289-16d09280-43ff-11e9-8025-034fcfba0e6a.png">

**Comment by DanTup** [comment]
@devoncarew FYI - in case you think Atom should be updated. Once again, I don't know if I've done this correctly, but it appears to have done the right thing.

I'm wondering whether we could generate this from something like [this file](https://github.com/chalin/dart-spec-and-grammar/blob/master/doc/grammar-AUTOGENERATED-DO-NOT-EDIT.txt) to have it always in-sync and correct 🤔

**Comment by devoncarew** [comment]
Thanks! I opened https://github.com/dart-atom/dart/issues/1185.
