### ISSUE TITLE
Intellisense does not respect space after equal sign

### ISSUE THREAD

**Issue by richardchui** [Dart-Code/Dart-Code#1501]
Steps to Reproduce:
1. In a .dart file, after typing '=', Intellisense will pop up.
2. Press the space key to place a space after the equal sign, the suggestion box will be closed.
3. Continue typing and the suggestion box will pop up again.
4. Now select anything, and the space after the equal sign will be gone.

**Comment by DanTup** [comment]
Thanks for the report! I believe this is the same issue as #1483 which has been fixed for the next release.

If you'd like to test the fix, there's a preview build [here](https://github.com/Dart-Code/Dart-Code/releases/tag/v2.25.0-alpha.1) and instructions on installing it [here](https://dartcode.org/docs/installing-a-preview-release/).

Thanks!
