### ISSUE TITLE
P0: VS Code: Delegate launching browser to DevTools to always get Chrome

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#1505]
Requires https://github.com/flutter/devtools/issues/463

**Comment by DanTup** [comment]
This will be handled in the server instead.

**Comment by skybur** [comment]
Sorry for commenting in this closed issue. So how do I start devtools in chrome if it's not my default browser? Thanks

**Comment by DanTup** [comment]
Currently you'd have to open Chrome manually and copy the URL from the default browser that is launched. This will be fixed, but requires https://github.com/flutter/devtools/issues/463.

I'm re-opening this, since there will be work today when that lands which I forgot about.

**Comment by devoncarew** [comment]
From the above comments, it sounds like this is in progress?

**Comment by DanTup** [comment]
@devoncarew Yeah, DevTools now allows you to send it VM service URIs while it's running (over stdin, like `{ method: vm.register, params: { uri: <vm-service-uri> } }` and it'll connect to them and register a `launchDevTools` service. If you call it, it'll spawn the browser for you.

It's not ready to go yet, but here's how it works in Dart Code (on a branch):

Register VMs with DevTools when a debug session starts (and for any existing sessions at start time):

https://github.com/Dart-Code/Dart-Code/commit/83f2eeb5e52427a6b74cca92fcd3279b42c4236e#diff-5611b1bb550fbff23450e8dd4f2dfb2aR98

Call the service when we need to open the browser:

https://github.com/Dart-Code/Dart-Code/commit/83f2eeb5e52427a6b74cca92fcd3279b42c4236e#diff-5611b1bb550fbff23450e8dd4f2dfb2aR62

It needs some additional changes landing in DevTools (https://github.com/flutter/devtools/pull/563) and also some tweaks to support arguments for `theme`/`hide` - they're not done yet though.

**Comment by devoncarew** [comment]
Interesting - we don't ask the devtools server to open a browser tab? We ask it to register with the vm service protocol, then ask over the vm service protocol to open a browser?

I'm curious why that is - it seems more straightforward to ask the devtools server to open a browser tab directly.

**Comment by DanTup** [comment]
@jacob314 can probably answer this best, but I believe it's because some of the things we'll ask from the DevTools server (eg. to provide data for widget rebuilds, etc.) will need it to have connected to the VM service anyway (so this keeps those things working the same).

I think we could potentially expose it over stdin too if you think it makes sense (for ex. if IntelliJ won't make use of the other services, that would probably simplify things a little for it).

**Comment by jacob314** [comment]
Yes this design seems very odd without context of what we will do with the server next.
If this was the only feature we needed from the server for then passing in the VM service port would be overkill.
The next uses for the server are:
1. Rebuild indicator stats tracked on the server and consumed by VSCode & DevTools.
2. Triggering opening DevTools from the device itself by clicking on the debug banner or a debug gesture.
3. Database of memory profiling data.
4. Record log messages sent before devtools opens. Currently all such log messages are lost resulting a confusing experience.

All these use cases are easier or only possible if the server knows about all running apps.

**Comment by devoncarew** [comment]
Gotcha. That all makes sense - adding more functionality into the server, so that its logic can serve multiple clients.

For some clients, it may be difficult to use devtools in this manner to launch chrome however (this would look like: tell devtools about the new service protocol url; devtools registers a 'launchDevTools' service with the service protocol; IntelliJ waits for a 'launchDevTools' service to be available on the service protocol and uses it to open a browser). That would be a lot of async programming for a platform where that's a bit cumbersome.

We may want the devtools server to support a stdio command along the order of `devtools.openBrowser: serviceProtocolUrl`. IntelliJ could call that and pass in the url for a service protocol connection. Devtools could open a browser configured to connect to the service protocol connection (and possibly, optionally register the service protocol url with the known list of running vms).

**Comment by jacob314** [comment]
Yes adding a 'devtools.openBrowser' api on stdio makes sense. It should be very little work to support both.

**Comment by DanTup** [comment]
I've opened https://github.com/flutter/devtools/issues/611 in the DevTools repo for supporting this from  stdin (since this issue will soon be closed). If it's urgent, let me know.

**Comment by DanTup** [comment]
I'm disabling this for v2.26.1 because I'd like to release the other fixes and there are complications with this. If it fails - most likely because Chrome isn't installed - it seems to unregister the service unexpectedly. I'll put it back in another patch once I'm sure we can handle the failure in a reasonable way.
