### ISSUE TITLE
Auto import feature always uses fully qualified package imports

### ISSUE THREAD

**Issue by grouma** [Dart-Code/Dart-Code#1519]
When using a member from a relative file the auto import feature always uses the fully qualified import name, e.g. `import "package:my_package/src/relative_file.dart"`. This goes against common convention.

**Comment by DanTup** [comment]
This comes from the analysis server - I've opened an issue in the past about it here: https://github.com/dart-lang/sdk/issues/32916. However it's not clear (to me) how common each is. I thought relative paths were more common, but more recently I've seen a lot more package-uris.

Anyway, I'll close this as upstream, as it's not something controlled by the VS Code extension, so if we change it (there has been suggestion of making it follow convention from your files, or maybe have a setting somewhere) it'll need to come from there.

**Comment by grouma** [comment]
Thanks for the info. I +1'd the SDK issue. You can run into issues if you aren't consistent as Dart will treat members as different if they aren't from the same path import. I can't remember the exact details but I have hit a few times. I wish Dart Style would explicitly call this out.

**Comment by DanTup** [comment]
Yeah, Flutter uses relative paths so I have to manually correct them. I also wish there was a clear preference for one or the other, that way it's less likely to vary between projects and therefore easier for the server to make a consistent choice. I wonder if we can scan all the repos on GitHub to see what the breakdown is like 😁
