### ISSUE TITLE
Add parameters when completing method/constructors

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#152]
I think @devoncarew was asking for this; seems it's possible - see this comment:

https://github.com/Microsoft/vscode/issues/6874#issuecomment-235606255

**Comment by devoncarew** [comment]
Wow, I didn't realize!

```
foo(${value}, ${another}); ${_}
```

Seems like a good thing to experiment with :)

**Comment by DanTup** [comment]
Yeah; will help a lot while we don't have the signature help too!

**Comment by DanTup** [comment]
@devoncarew I've added this in master; it'll populate all required param names. I'd be interested to hear how this feels to you. Seems good to me, though there are some minor annoyances:

1. `<Tab>`/`<Enter>` seem to behave differently - if you use `<Tab>` to move through the placeholders, when you get to the last one you have to hit `<Enter>` twice to get a newline. Using `<Enter>` to move through them doesn't seem to do this. Does this seem weird to you?
2. Since we put the cursor after the closing paren, if you need to pass an optional/named arg, you'll have to move back. We don't know what the user is going to want to do so we could be wrong whatever we do - is current behaviour best?

Other than that, I think this is a big help while we don't have proper sig help! :)

**Comment by devoncarew** [comment]
Awesome re: populating the required params!

And for optional params, I think for now it's best to ignore them. The user would need to move backwards in order to populate, but I think any attempt to add placeholder for optional args (we briefly did this very early on) would distract from the more common case of not needing opt. params.
