### ISSUE TITLE
Notifications not showing after VS Code update

### ISSUE THREAD

**Issue by cujslive** [Dart-Code/Dart-Code#1522]
Flutter notifications are not showing after updating VS Code to Version `1.32.1`.
Notifications working well with other languages and projects

## Using Versions
- Flutter: `1.2.1`
- Dart Code: `2.24.0`
- Flutter VS Code Plugin: `2.24.0`

**Comment by DanTup** [comment]
Can you clarify what you mean by notifications?

**Comment by cujslive** [comment]
Sorry I mean the notifications of VS Code. Bottom right corner. 
![image](https://user-images.githubusercontent.com/35224957/54084003-4f199780-4351-11e9-8f6d-c1767979a753.png)

**Comment by RazaGR** [comment]
It is a known issue see 
https://github.com/Dart-Code/Dart-Code/issues/1518

**Comment by DanTup** [comment]
@cujslive 

> I mean the notifications of VS Code. Bottom right corner.

There are many different notifications, can you be more specific? Do you mean during Flutter builds? If so, that's likely related to the issue @RazaGR mentioned above.

**Comment by cujslive** [comment]
@DanTup yeh. i also have the same issue @RazaGR mentioned above. what i meant by notifications means, previously when we do a hot reload or hot restart, vs code will show a notification in the bottom right corner like "reloading..", "syncing files with..", etc. now those are not showing. also i can’t perform hot reload. only hot restarting. i think this is a duplicate. ill close the issue. thanks.

**Comment by DanTup** [comment]
Yep, if you specifically mean notifications for things like reload, then that is indeed #1518 - the problem is that hot reload isn't working rather than the notifications. Notifications for things other than the debugging features that are broken should work fine.

Downgrading to 1.31 until the next VS Code release is the best option.

**Comment by DanTup** [comment]
(v1.32.2 of VS Code is live and contains the fix)
