### ISSUE TITLE
VS Code freezes when debugging an external package

### ISSUE THREAD

**Issue by rubensdemelo** [Dart-Code/Dart-Code#1523]
When I debug an external package with "Debug External Libraries" unchecked, VS Code just freezes and don't execute my code. I need force execution by step over or continue.

<img width="403" alt="Screenshot 2019-03-10 05 27 38" src="https://user-images.githubusercontent.com/1351177/54082496-75a9e500-42f5-11e9-9edc-d76edff15bfe.png">

**Comment by DanTup** [comment]
I think you're probably seeing https://github.com/Dart-Code/Dart-Code/issues/1497 and/or https://github.com/Dart-Code/Dart-Code/issues/1502 which are fixed for next version.

If you want to test it out, there's a preview build here: https://github.com/Dart-Code/Dart-Code/releases/tag/v2.25.0-alpha.2

Let me know if you still have issues with that version.

**Comment by rubensdemelo** [comment]
It works @DanTup . Thank you.

<img width="534" alt="Screenshot 2019-03-12 05 55 19" src="https://user-images.githubusercontent.com/1351177/54187087-8ab87c80-448b-11e9-8067-b817e5e495e5.png">

**Comment by DanTup** [comment]
@rubensdemelo Great, thanks! Do let me know if you hit any other issues.
