### ISSUE TITLE
Include function stubs in completion

### ISSUE THREAD

**Issue by DeRealMorgan** [Dart-Code/Dart-Code#1526]
Why not add a feature where the important pieces of a widget are created right away?

When creating an Align() I of course want to use the alignment: property.
Same goes for any widget that has a child/children.

This will speed up the coding process a bit (making it smoother for the developer).

More important for me is an event implementation.
Lets take a GestureDetector as an example:
GestureDetector(onPanStart: ...)

If I want to use the onPanStart: event, I of course want to create the correct lambda like this:
(DragStartDetails dragStart) { }

This one line of code could be inserted automatically.

**Comment by DanTup** [comment]
Thanks for the suggestions! To implement something like this, it would need to be done in the SDK. The VS Code plugin doesn't provide the completion items directly, it just relies on the language server in the SDK to figure then out. It would probably be best raised in the flutter/flutter repository or dart-land/sdk.

Some thoughts though:

> When creating an `Align()` I of course want to use the `alignment:` property.

The alignment property is optional and defaults to `center`. I don't know if it's common, but it's valid to omit it. Always inserting it might be annoying if you wanted `center` and want to rely on the default to reduce some noise.

> If I want to use the onPanStart: event, I of course want to create the correct lambda like this:
> `(DragStartDetails dragStart) { }`

It's possible you might want to put your code in another method (and for big build methods, it may be more readable to do so):

```dart
GestureDetector(
  onPanStart: handlePanStart,
);
```

I also think inserting some of the parameters and not others may make it a bit awkward to move around to insert the extra ones you want in the places you want them. Of course, you could have something that can be enabled/disable, but for something like this you might end up with a lot of flags, or having to choose to have all of it vs none of it.

As well as raising with the SDK, if there are specific things you find tedious, you may be able to create some [VS Code snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets). They're pretty flexible and we already have a few built-in (like for creating stateful/stateless widgets). It could also be a good way to try out some of your ideas and refine them (or allow others to try them) for discussion in the SDK repo.

Thanks!

**Comment by DeRealMorgan** [comment]
> The alignment property is optional and defaults to center
I did not know about that. (But I am new too)

> It's possible you might want to put your code in another method (and for big build methods, it may be more readable to do so):

There I think I have a solution which works for both.
I do heavily rely on the auto completion feature - in Android Studio and VS Studio.
E.g. when I type `Pad` it suggest `Padding` and I press Tab to insert it right away.

Why not make that work for the right lambda too.
```
GestureDetector(
  onPanStart: 
```
and it should suggest to place `(DragStartDetails dragStart) { }` in there right away.

**Comment by DanTup** [comment]
Do you mean after typing `onPanStart: ` that in the completion list there should be an entry for `(DragStartDetails dragStart) { }`?

**Comment by DeRealMorgan** [comment]
Yes (didnt find the right words apparently :D)

**Comment by DanTup** [comment]
Great, thanks for confirming. I think that's a reasonable suggestion. I don't know if we can implement it here (it may need to go to the SDK repo to be considered for the server), but I'll do a little investigation. Thanks!

**Comment by DanTup** [comment]
It looks like @pq has been working on this directly in the analyzer (which means VS Code and other editors will get it "for free" without any work here):

https://github.com/dart-lang/sdk/issues/40013#issuecomment-574422203

So I'll close this as being fixed there (you'll need a new enough SDK that includes that change to see it - which most likely is nightly/master builds right now). If you try it out and hit any issues, it would be best to raise them in the SDK repo. Thanks!
