### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by DEVRAJ13** [Dart-Code/Dart-Code#1534]
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `2.24.0`
- OS Version: `Linux x64 4.15.0-46-generic`
- VSCode version: `1.32.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/xornor-pc/Dart-Code.dart-code-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by DanTup** [comment]
> Make sure to attach this file from your home-directory: `/home/xornor-pc/Dart-Code.dart-code-unresponsive.cpuprofile.txt`

Are you able to attach this file? I'm unfortunately unable to repro this issue so can't investigate without the profile data (it's been posted a few times, but unfortunately nobody has ever supplied a file).

Thanks!

**Comment by DanTup** [comment]
Unfortunately I can't investigate this without a CPU profile. Please let me know if you can provide one (either publicly here, or by email) and I'll take a look.
