### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by odanicola** [Dart-Code/Dart-Code#1535]
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `2.24.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/odanicola/Dart-Code.dart-code-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by DanTup** [comment]
@odanicola 

> ⚠️ Make sure to attach this file from your home-directory: /Users/odanicola/Dart-Code.dart-code-unresponsive.cpuprofile.txt ⚠️

Are you able to attach this file?

**Comment by DanTup** [comment]
Unfortunately I can't investigate this without a CPU profile. Please let me know if you can provide one (either publicly here, or by email) and I'll take a look.
