### ISSUE TITLE
Multiline String causes dart file to break

### ISSUE THREAD

**Issue by Hitman7987** [Dart-Code/Dart-Code#1548]
This is my first issue report so please bare with me.
The issue appears in VS Code; Using only the Dart & Flutter extensions with Material Theme.
To reproduce:
The below code works without a hitch:
```dart
String _url(someParam) {
  String data = 'a'
                'b'
                'c$someParam';
}
```
Placing a comma after the 2nd last line like so:
```dart
String _url(someParam) {
  String data = 'a'
                'b',
                'c$someParam';
}
```
Causes VS Code to seemingly "not recognize" the dart file. Code completion stops working, and no error or warning is shown.

It's by no means a HUGE issue, opening the project inside of Android Studio allows you to quickly solve the problem, however, it is annoying and hopefully unexpected.

**Comment by DanTup** [comment]
Thanks for the report! I tried your sample code, but I didn't have any issues:

<img width="423" alt="Screenshot 2019-03-20 at 6 27 21 pm" src="https://user-images.githubusercontent.com/1078012/54709664-d9c27980-4b3d-11e9-9ea6-350bffb4ed4d.png">

Could you reproduce this while capturing logs?

- Press `Cmd`+`Shift`+`P` (`Ctrl` in place of `Cmd` if not on a Mac) to open the VS Code command palette
- Type "Capture Logs" to filter the command list until you can see **Dart: Capture Logs**
- Select **Dart: Capture Logs** and press `<enter>`
- Untick everything except **Analysis Server**
- Click **OK** or press `<enter>`
- *At this point, you'll see a notification in the bottom right corner saying logs are being captured*
- Type your comma to reproduce the issue
- Try (and presumably fail) to invoke code completion
- Click the **Stop Logging** button on the notification (if it's disappeared, click the bell icon in the bottom right to find it again)

This will present you with a log file that you should attach here. Note: It may have the contents of your open files in it, so it's best to reproduce this on a small isolated project, or review it for anything sensitive before attaching (you can also email it to logs@dartcode.org if you'd rather not post it here).

Thanks!

**Comment by Hitman7987** [comment]
Hi, please try with the following code snippet:
(Make a new Flutter project using flutter create..., then just add a new dart file called whatever.dart)
```dart
import 'package:flutter/material.dart';

String _url(someParam) {
  String data = "a"
      "b",
      "c$someParam";
  return data;
}
```
Here is a log file:
[Dart-Code-Log-2019-02-04 09-27-54.txt](https://github.com/Dart-Code/Dart-Code/files/2991146/Dart-Code-Log-2019-02-04.09-27-54.txt)

**Comment by DanTup** [comment]
I'm afraid I still can't repro with those instructions. The log file you attached doesn't seem to include any calls for completion - though I can see you typing and removing the comma.

Could you re-capture the log, including some attempts to open completion with `Ctrl`+`Space`?

Also, can you open the dev tools (Help -> Toggle Developer Tools) and see if there are any warnings or errors listed?

**Comment by Hitman7987** [comment]
Hi, I apoligize for taking so long to respond.
I checked Dev Tools, no errors are shown in the console when I add or remove the comma.
I attempted: `Ctrl` + `Space`, `Ctrl` + `.`
I also tried making a new String variable, which seemed to work. From what I can see the problem doesn't appear to be with Dart specifically but with Flutter widgets not being recognized. But I am no expert. 
Please find attached a new Log File. 
[Dart-Code-Log-2019-02-00 20-13-17.txt](https://github.com/Dart-Code/Dart-Code/files/3000683/Dart-Code-Log-2019-02-00.20-13-17.txt)
Regards

**Comment by DanTup** [comment]
@Hitman7987 Thanks! I found an error in your log:

```
[20:13:42 GMT+0200 (SAST)] [General] [Error] [Analyzer] Internal problem: Compiler cannot run without a compiler context.
Tip: Are calls to the compiler wrapped in CompilerContext.runInContext?
[20:13:42 GMT+0200 (SAST)] [Analyzer] [Error] #0      CompilerContext.current (package:front_end/src/fasta/compiler_context.dart:111:7)
#1      internalProblem (package:front_end/src/fasta/problems.dart:45:25)
#2      unhandled (package:front_end/src/fasta/problems.dart:58:10)
#3      analyzeQuote (package:front_end/src/fasta/quote.dart:54:10)
#4      AstBuilder.endLiteralString (package:analyzer/src/fasta/ast_builder.dart:240:21)
#5      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:4797:14)
#6      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:4722:13)
#7      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:3997:14)
#8      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:3930:12)
#9      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3742:13)
#10     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3714:13)
#11     Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3679:13)
#12     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5191:16)
#13     Parser.parseExpressionStatementOrDeclaration (package:front_end/src/fasta/parser/parser.dart:5112:12)
#14     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3584:14)
#15     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3503:20)
#16     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3408:15)
#17     Parser.parseTopLevelMethod (package:front_end/src/fasta/parser/parser.dart:2338:13)
#18     Parser.parseTopLevelMemberImpl (package:front_end/src/fasta/parser/parser.dart:2241:14)
#19     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:489:14)
#20     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:348:15)
#21     ParserAdapter.parseCompilationUnit2 (file:///b/rr/tmpmr462B/w/src/third_party/dart/pkg…
```

@bwilkerson @scheglov any ideas about this? It seems to have happened in response to a request to format the document. This is the SDK version:

```
Dart SDK:
    Loc: /home/username/development/flutter/bin/cache/dart-sdk
    Ver: 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36
Flutter SDK:
    Loc: /home/username/development/flutter
    Ver: 1.2.1
```

I can't find any SDK cases with this error message in them.

**Comment by bwilkerson** [comment]
I looked at the code, and it appears that the parser is trying to parse a string literal that does not start with a valid sequence of quotes. I have no idea why.

The person most familiar with the parser is on vacation this week, but I'll send him a link to this issue to look at when he gets back.

**Comment by DanTup** [comment]
Cool, thanks!

While re-testing, I found another issue (which I don't think is related), but the above code (which is invalid - the assignment to `data` has multiple strings separated by commas) reports all errors on Line 1 (the offset is correct, but the line/col seems to just use line 1 and then a column for the offset). I've opened https://github.com/dart-lang/sdk/issues/36340.

**Comment by DanTup** [comment]
@bwilkerson lmk if it'd be better moving this to the SDK repo than here.

**Comment by danrubel** [comment]
I believe this is fixed by https://github.com/dart-lang/sdk/commit/5dd89ef9a0008ec52fcb9b09c301e9f828eb2b45.

**Comment by DanTup** [comment]
Yep, the error appears in the right place using the current nightly. Thanks!
