### ISSUE TITLE
Callback completion

### ISSUE THREAD

**Issue by efreibe** [Dart-Code/Dart-Code#1551]
Hello!

It is possible to enable autocomplete of callback functions in the context menu?

Example:

```
return Expanded(
  child: ListView.separated(
    itemCount: 3,
    separatorBuilder: (BuildContext context, int index) {
    },
    itemBuilder: [Context Menu -> Implement Callback or Closure or whatever ;)]
  ),
)
```

Thank you

**Comment by DanTup** [comment]
Thanks! I think this is covered by #1526 (if you think that's not the case, let me know!).
