### ISSUE TITLE
Support launching custom emulators

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#1553]
See comment at https://github.com/Dart-Code/Dart-Code/issues/490#issuecomment-471246344 by @nmfisher and the following comments.

This could be useful for:

- Allowing launching of any third party emulator that Flutter doesn't know how to handle
- Changing the command run when launching a known emulator (by allowing reusing the same ID and overriding)

**Comment by DanTup** [comment]
Here's an example that overrides an existing emulator to force `-gpu host` (the ID matches the one returned by `flutter emulators`, so it gets merged).

<img width="716" alt="Screenshot 2020-04-15 at 15 20 11" src="https://user-images.githubusercontent.com/1078012/79348217-a31b8600-7f2c-11ea-8bb6-09af0d0a315c.png">

Note: You can create your own emulators (with unique IDs), but they must still show up in `flutter devices` after being launched, otherwise VS Code will sit for 60 seconds and then say the emulator did not launch.

**Comment by neiljoseph9** [comment]
Where are we supposed to type this in??

**Comment by DanTup** [comment]
@neiljoseph9 the code above is a VS Code setting. You can open your VS Code User Settings by running the **Preferences: Open Settings (JSON)** command from the VS Code command palette.
