### ISSUE TITLE
Add an option to auto-launch DevTools when starting a debug session

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#1557]
Probably we should allow the user to specify which types to do this for (Dart, webdev daemon, Flutter).

@jacob314 I think this requires the ability to launch the DevTools from the DevTools server (so it can track the process it spawned). Do you know if there are issues open to track that?

**Comment by jacob314** [comment]
Added a devtools issue to track the server piece of this.
https://github.com/flutter/devtools/issues/463

I would only suggest launching automatically for flutter_web and flutter.

**Comment by DanTup** [comment]
I don't think this works very well right now, as every time you stop/start a session, you get a new browser tab. Maybe we should try a querystring param in DevTools to have it close its tab when the VM connection drops (assuming we can), and then we could pass that in the case where the tools are being auto-launched at the start of each session?

@csells @jacob314 WDYT?

**Comment by DanTup** [comment]
@jacob314 I've opened https://github.com/flutter/devtools/issues/612

I wonder if we should also have an option for when we call `launchDevTools` to say "if it's already open, just bring the browser+tab to the front"? (I don't think it'll work for the ChromeOS native-browser case, but maybe for those we own the processes for?).

FWIW, unless anyone shouts, I'm going to move this to a future release. I think it's non-critical and I want to stop making changes for vNext ASAP (ideally today).
