### ISSUE TITLE
Problems with Intillisense in VSCode on Flutter 1.3.8

### ISSUE THREAD

**Issue by Ibtesam-Mahmood** [Dart-Code/Dart-Code#1565]
I recently updated to Flutter version 1.3.8, after updating the auto completion on VSCode stopped working. However, this was working before the update.

<img width="637" alt="Screen Shot 2019-03-26 at 6 17 18 PM" src="https://user-images.githubusercontent.com/29645101/55037232-6f08b680-4ff3-11e9-92db-e039f4d297fe.png">

I'm on Dart version 2.2.1 I don't know what else to include in this issue. Please let me know if I need to attach anything, Thank You.

**Comment by DanTup** [comment]
Can you check the developer console for any errors/warnings (Help -> Toggle Developer Console) and also try enabling the [analysis server](https://dartcode.org/docs/logging/#analyzer) logging and restart VS Code, repro the issue and then grab that log file?

**Comment by Ibtesam-Mahmood** [comment]
So this is my developer console:
<img width="799" alt="Screen Shot 2019-03-31 at 2 43 17 PM" src="https://user-images.githubusercontent.com/29645101/55293320-561d4e00-53c3-11e9-809c-420627c89866.png">

I enabled the Analysis server, however no log file was printed to the folder.

I have also upgraded flutter and tried changing the version, this didn't change anything concerning my issue.

My flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.3.8, on Mac OS X 10.14.2 18C54, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
[✓] VS Code (version 1.32.3)
[!] Connected device
    ! No devices available

**Comment by DanTup** [comment]
The log file should always be written to during analysis server startup. You may need to restart VS Code after setting it.

It should look something like this:

<img width="756" alt="Screenshot 2019-03-31 at 20 06 12" src="https://user-images.githubusercontent.com/1078012/55293640-83342580-53f0-11e9-8e0f-57f32baac4f7.png">

I can't remember for sure, but you may need to make sure the folder already exists (though it should create the file).

**Comment by Ibtesam-Mahmood** [comment]
I got it, this is my analyzer file

[analyzer.txt](https://github.com/Dart-Code/Dart-Code/files/3027071/analyzer.txt)

**Comment by DanTup** [comment]
@Ibtesam-Mahmood Thanks, the log worked but it doesn't include much. Could you try invoking completion a few times (such that you see "Loading...") and then take a copy of the log? There aren't any completion requests in this one so it's hard to see the server response.

Thanks!

**Comment by Ibtesam-Mahmood** [comment]
So I ran intellisense a couple times along with building the project. it seems to build and deploy fine, however the intellisense is still stuck on loading. Here is the analyzer file, not sure what is changed within it.

[analyzer.txt](https://github.com/Dart-Code/Dart-Code/files/3031300/analyzer.txt)


Note: this isn't an issue when programming with other languages, this is a dart only issue

**Comment by Ibtesam-Mahmood** [comment]
This is my detailed Flutter Doctor by the way.

[✓] Flutter (Channel unknown, v1.3.8, on Mac OS X 10.14.2 18C54, locale en-CA)
    • Flutter version 1.3.8 at /Applications/flutter
    • Framework revision e5b1ed7a7f (4 weeks ago), 2019-03-06 14:23:37 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ibtesamm/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5215

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.0

[!] Connected device
    ! No devices available

**Comment by DanTup** [comment]
How big is the folder `/Users/ibtesamm/Documents/Programming/Flutter/random_projects/boxgame`? Does or contain any symbolic links?

Could you try again, but capturing an [analysis server instrumentation log](https://dartcode.org/docs/logging/#analyzer-instrumentation)? This one is captured by the server (rather than the client) so may include more info.

@bwilkerson @scheglov based on the client logs, the server seems to have just stopped responding here during initial analysis (after reporting no errors in the pubspec):

```
[3:43:48 PM]: <== {"event":"server.connected","params":{"version":"1.24.0","pid":75654,"sessionId":""}}
[3:43:48 PM]: ==> {"id":"3","method":"analysis.setAnalysisRoots","params":{"excluded":[],"included":["/Users/ibtesamm/Documents/Programming/Flutter/random_projects/boxgame"]},"clientRequestTime":1554061428559}
[3:43:48 PM]: ==> {"id":"4","method":"analysis.updateContent","params":{"files":{"/Users/ibtesamm/Documents/Programming/Flutter/random_projects/boxgame/lib/main.dart":{"edits":[{"offset":0,"length":0,"replacement":"","id":""}],"type":"change"}}},"clientRequestTime":1554061428560}
[3:43:48 PM]: ==> {"id":"5","method":"analysis.setPriorityFiles","params":{"files":["/Users/ibtesamm/Documents/Programming/Flutter/random_projects/boxgame/lib/main.dart"]},"clientRequestTime":1554061428561}
[3:43:48 PM]: ==> {"id":"6","method":"analysis.setSubscriptions","params":{"subscriptions":{"CLOSING_LABELS":["/Users/ibtesamm/Documents/Programming/Flutter/random_projects/boxgame/lib/main.dart"],"FOLDING":["/Users/ibtesamm/Documents/Programming/Flutter/random_projects/boxgame/lib/main.dart"],"OCCURRENCES":["/Users/ibtesamm/Documents/Programming/Flutter/random_projects/boxgame/lib/main.dart"],"OUTLINE":["/Users/ibtesamm/Documents/Programming/Flutter/random_projects/boxgame/lib/main.dart"]}},"clientRequestTime":1554061428562}
[3:43:48 PM]: <== {"id":"1"}
[3:43:48 PM]: <== {"id":"2","result":{}}
[3:43:49 PM]: <== {"event":"analysis.errors","params":{"file":"/Users/ibtesamm/Documents/Programming/Flutter/random_projects/boxgame/pubspec.yaml","errors":[]}}
[4:10:01 PM]: ==> {"id":"7","method":"completion.getSuggestions","params":{"file":"/Users/ibtesamm/Documents/Programming/Flutter/random_projects/boxgame/lib/main.dart","offset":460},"clientRequestTime":1554063001557}
[4:10:12 PM]: ==> {"id":"8","method":"analysis.getHover","params":{"file":"/Users/ibtesamm/Documents/Programming/Flutter/random_projects/boxgame/lib/main.dart","offset":476},"clientRequestTime":1554063012653}
```

3:43:49 is the last entry from the server (the rest of the log is only sending, none of which are responded to). Any additional ideas for tracking down what's happening?

**Comment by bwilkerson** [comment]
You might be able to find the problem by connecting a debugger to the process and pausing it to see what it's doing. It's possible that it's stuck in a loop somewhere and hence unable to respond to requests.

**Comment by DanTup** [comment]
Makes sense!

@Ibtesam-Mahmood if you can answer the other questions above (about symblinks and folder size) and get an instrumentation log, if neither of those help I'll add some notes on attaching a debugger to the analyzer to try and see what's happening.

**Comment by Ibtesam-Mahmood** [comment]
To answer your initial question, the folder boxgame is 254.9 MB.

This is my updated analyzer and analyzer instrumentation file:
[analyzerInstrumentation.txt](https://github.com/Dart-Code/Dart-Code/files/3044747/analyzerInstrumentation.txt)
[analyzer.txt](https://github.com/Dart-Code/Dart-Code/files/3044748/analyzer.txt)

**Comment by Ibtesam-Mahmood** [comment]
I tried pausing the debugger, I don't know what this changed. No update was given on the file

**Comment by DanTup** [comment]
The instrumentation file only contains one line (the version), so it seems like something else went wrong there.

> To answer your initial question, the folder boxgame is 254.9 MB.

Is this all Dart code, or just some assets? How many files are there? And how many of them are Dart?

Is this a project you can share? Or can you trim it down do something that still has the issue that you can share?

> I tried pausing the debugger, I don't know what this changed

Brian was referring to attaching a debugger to the analysis server. Is that what you did? If not, here's how to do that:

1 Run the `Preferences: Open Workspace Settings` command in VS Code
2 Set the `dart.analyzerObservatoryPort` setting to a valid port number and save

![Screenshot 2019-04-08 at 11 14 25 am](https://user-images.githubusercontent.com/1078012/55716708-939b6000-59ef-11e9-8d5b-ee785fc107cf.png)

3 Wait a minute or so, to ensure analysis has had enough time to complete (to be sure it's gotten stuck wherever it's getting stuck)
4 Open your browser at `http://localhost:(port)`, for example `http://localhost:8123/` to find the debugger web app
5 Click on the `debug` link in the lower right side of the page
6 Click the `Pause Isolate` link at the top of the page

This should then show you a call stack - if you paste a screenshot or copy/paste of as much info on that page as possible, hopefully it will help us understand what the server is doing.

**Comment by Ibtesam-Mahmood** [comment]
Update: I switched over to flutter version 1.4.11 and this didn't seem to fix anything, I'm guessing this problem is version independent. I believe that while I was updating to version 1.3.8 something had been broken with the dart sdk.

**Comment by Ibtesam-Mahmood** [comment]
So, I went to the Dart observatory and it seems like there are 2 isolates the Isolate 940339254 (_cacheCleanUpFunction) and the Isolate 176727101 (main). I'm assuming that you want to to pause the main isolate. however, it is stuck on loading.

<img width="1407" alt="Screen Shot 2019-04-08 at 7 24 36 PM" src="https://user-images.githubusercontent.com/29645101/55763196-f878a980-5a33-11e9-8775-ca706ccd4739.png">

**Comment by DanTup** [comment]
@Ibtesam-Mahmood thanks for the info! 

Is the folder all Dart code, or some assets? How many files are there? And how many of them are Dart?

Is this a project you can share? Or can you trim it down do something that still has the issue that you can share?

@bwilkerson I'm not very familiar with this - any idea what could cause the isolate not to load or how we can get more info?

**Comment by bwilkerson** [comment]
No, I don't think I've seen this before. We should create an issue in the sdk repo and ask `a-siva`, referencing this issue for context.

**Comment by DanTup** [comment]
Done, I've opened https://github.com/dart-lang/sdk/issues/36558.

**Comment by DanTup** [comment]
Sounds like it may be stuck in sync file access here (native functions can't be interrupted by the debugger).

@Ibtesam-Mahmood see my comments [here](https://github.com/dart-lang/sdk/issues/36558#issuecomment-481996021). I think the easiest way to track this down may be to copy your project, then try stripping it down (first, removing any non-Dart/pubspec files, to see if that stops the issue, but then maybe selectively removing those too).

**Comment by DanTup** [comment]
@Ibtesam-Mahmood let me know if you're able to repro this with a smaller folder, or something you're able to share with me.

**Comment by Ibtesam-Mahmood** [comment]
Sorry for the late reply, So i did a couple things that might clarify the issue.

I tried creating a dart program that consisted of only 1 main file. The intellisense seems to be working here. So I believe this might be an issue with flutter.

I also tried creating a brand new flutter file. It seems that the intellisense is broken here and is stuck on loading.

**Comment by Ibtesam-Mahmood** [comment]
Update: Intellisense has stopped working on the new project. this happened shorty after I opened the old project and reopening the new one

**Comment by Ibtesam-Mahmood** [comment]
Update: So after I switched over to the old project and reopened the new on. Intellisense stopped working

**Comment by Ibtesam-Mahmood** [comment]
Here are the updated analytics files on the folder with 1 dart file in it (4KB):

[analyzer.txt](https://github.com/Dart-Code/Dart-Code/files/3099336/analyzer.txt)
[analyzerInstrumentation.txt](https://github.com/Dart-Code/Dart-Code/files/3099337/analyzerInstrumentation.txt)

This is the debug console for the main isolate in the observatory:

Frame 0_GrowableList.add ( libgrowable_array.dart:153:3 )
No source
this	_GrowableList (0)


Frame 1_Directory._fillWithDirectoryListing ( bindirectory_patch.dart:31:3 )

Frame 2_Directory.listSync ( directory_impl.dart:243:3 )

Frame 3_PhysicalFolder.getChildren ( physical_file_system.dart:317:3 )

Frame 4_OverlayFolder.getChildren ( overlay_file_system.dart:331:3 )

Frame 5ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 6ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 7ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 8ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 9ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 10ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 11ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 12ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 13ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 14ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 15ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 16ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 17ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 18ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 19ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 20ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 21ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 22ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 23ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 24ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 25ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 26ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 27ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 28ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 29ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 30ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 31ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 32ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 33ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 34ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 35ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 36ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 37ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 38ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 39ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 40ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 41ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 42ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 43ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 44ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 45ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 46ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 47ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 48ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 49ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 50ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 51ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 52ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 53ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 54ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 55ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 56ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 57ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 58ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 59ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 60ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 61ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 62ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 63ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 64ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 65ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 66ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 67ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 68ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 69ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 70ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 71ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 72ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 73ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 74ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 75ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 76ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 77ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 78ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 79ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 80ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 81ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 82ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 83ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 84ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 85ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 86ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 87ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 88ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 89ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 90ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 91ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 92ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 93ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 94ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 95ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 96ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 97ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 98ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 99ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 100ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 101ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 102ContextManagerImpl._addPreviouslyExcludedSources ( context_manager.dart:763:3 )

Frame 103ContextManagerImpl.setRoots ( context_manager.dart:659:3 )

Frame 104AnalysisServer.setAnalysisRoots ( analysis_server.dart:517:3 )

Frame 105AnalysisDomainHandler.setAnalysisRoots ( domain_analysis.dart:362:3 )

Frame 106AnalysisDomainHandler.handleRequest ( domain_analysis.dart:296:3 )

Frame 107AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> ( analysis_server.dart:345:67 )

Frame 108_PerformanceTagImpl.makeCurrentWhile ( utilities_general.dart:255:3 )

Frame 109AnalysisServer.handleRequest.<anonymous closure> ( analysis_server.dart:344:14 )

Frame 110_rootRun ( zone.dart:1119:1 )

Frame 111_CustomZone.run ( zone.dart:1016:3 )

Frame 112_runZoned ( zone.dart:1513:1 )

Frame 113runZoned ( zone.dart:1460:1 )

Frame 114AnalysisServer.handleRequest ( analysis_server.dart:342:3 )

Frame 115ByteStreamServerChannel._readRequest.<anonymous closure> ( byte_stream_channel.dart:165:64 )

Frame 116_PerformanceTagImpl.makeCurrentWhile ( utilities_general.dart:255:3 )

Frame 117ByteStreamServerChannel._readRequest ( byte_stream_channel.dart:160:3 )

Frame 118ByteStreamServerChannel.listen.<anonymous closure> ( byte_stream_channel.dart:110:9 )

Frame 119_rootRunUnary ( zone.dart:1130:1 )

Frame 120_CustomZone.runUnary ( zone.dart:1024:3 )

Frame 121_CustomZone.runUnaryGuarded ( zone.dart:929:3 )

Frame 122_BufferingStreamSubscription._sendData ( stream_impl.dart:330:3 )

Frame 123_BufferingStreamSubscription._add ( stream_impl.dart:259:3 )

Frame 124_SinkTransformerStreamSubscription._add ( stream_transformers.dart:64:3 )

Frame 125_EventSinkWrapper.add ( stream_transformers.dart:14:3 )

Frame 126_StringAdapterSink.add ( string_conversion.dart:237:3 )

Frame 127_LineSplitterSink._addLines ( line_splitter.dart:137:3 )

Frame 128_LineSplitterSink.addSlice ( line_splitter.dart:105:3 )

Frame 129StringConversionSinkMixin.add ( string_conversion.dart:164:3 )

Frame 130_SinkTransformerStreamSubscription._handleData ( stream_transformers.dart:118:3 )

Frame 131_rootRunUnary ( zone.dart:1130:1 )

Frame 132_CustomZone.runUnary ( zone.dart:1024:3 )

Frame 133_CustomZone.runUnaryGuarded ( zone.dart:929:3 )

Frame 134_BufferingStreamSubscription._sendData ( stream_impl.dart:330:3 )

Frame 135_BufferingStreamSubscription._add ( stream_impl.dart:259:3 )

Frame 136_SinkTransformerStreamSubscription._add ( stream_transformers.dart:64:3 )

Frame 137_EventSinkWrapper.add ( stream_transformers.dart:14:3 )

Frame 138_StringAdapterSink.add ( string_conversion.dart:237:3 )

Frame 139_StringAdapterSink.addSlice ( string_conversion.dart:241:3 )

Frame 140_Utf8ConversionSink.addSlice ( string_conversion.dart:310:3 )

Frame 141_Utf8ConversionSink.add ( string_conversion.dart:306:3 )

Frame 142_ConverterStreamEventSink.add ( chunked_conversion.dart:73:3 )

Frame 143_SinkTransformerStreamSubscription._handleData ( stream_transformers.dart:118:3 )

Frame 144_rootRunUnary ( zone.dart:1130:1 )

Frame 145_CustomZone.runUnary ( zone.dart:1024:3 )

Frame 146_CustomZone.runUnaryGuarded ( zone.dart:929:3 )

Frame 147_BufferingStreamSubscription._sendData ( stream_impl.dart:330:3 )

Frame 148_BufferingStreamSubscription._add ( stream_impl.dart:259:3 )

Frame 149_SyncStreamController._sendData ( stream_controller.dart:763:3 )

Frame 150_StreamController._add ( stream_controller.dart:638:3 )

Frame 151_StreamController.add ( stream_controller.dart:584:3 )

Frame 152_Socket._onData ( binsocket_patch.dart:1770:3 )

Frame 153_rootRunUnary ( zone.dart:1130:1 )

Frame 154_CustomZone.runUnary ( zone.dart:1024:3 )

Frame 155_CustomZone.runUnaryGuarded ( zone.dart:929:3 )

Frame 156_BufferingStreamSubscription._sendData ( stream_impl.dart:330:3 )

Frame 157_BufferingStreamSubscription._add ( stream_impl.dart:259:3 )

Frame 158_SyncStreamController._sendData ( stream_controller.dart:763:3 )

Frame 159_StreamController._add ( stream_controller.dart:638:3 )

Frame 160_StreamController.add ( stream_controller.dart:584:3 )

Frame 161_RawSocket._RawSocket.<anonymous closure> ( binsocket_patch.dart:1323:15 )

Frame 162_NativeSocket.issueReadEvent.issue ( binsocket_patch.dart:827:5 )

Frame 163_microtaskLoop ( schedule_microtask.dart:35:1 )

Frame 164_startMicrotaskLoop ( schedule_microtask.dart:45:1 )

Frame 165_runPendingImmediateCallback ( libisolate_patch.dart:110:1 )

Frame 166_RawReceivePortImpl._handleMessage ( libisolate_patch.dart:166:3 )

message 0_IOService._ensureInitialize.<anonymous closure> ( binio_service_patch.dart:79:30 )

message 1_IOService._ensureInitialize.<anonymous closure> ( binio_service_patch.dart:79:30 )

message 2_Timer._handleMessage._handleMessage ( libtimer_impl.dart:406:3 )

message 3_NativeSocket.multiplex.multiplex ( binsocket_patch.dart:874:3 )

message 4_NativeSocket.multiplex.multiplex ( binsocket_patch.dart:874:3 )

message 5_NativeSocket.multiplex.multiplex ( binsocket_patch.dart:874:3 )

message 6_NativeSocket.multiplex.multiplex ( binsocket_patch.dart:874:3 )

message 7_StreamController.add.add ( stream_controller.dart:584:3 )

message 8_NativeSocket.multiplex.multiplex ( binsocket_patch.dart:874:3 )

message 9_NativeSocket.multiplex.multiplex ( binsocket_patch.dart:874:3 )

message 10_NativeSocket.multiplex.multiplex ( binsocket_patch.dart:874:3 )

message 11_NativeSocket.multiplex.multiplex ( binsocket_patch.dart:874:3 )

message 12_NativeSocket.multiplex.multiplex ( binsocket_patch.dart:874:3 )

message 13_NativeSocket.multiplex.multiplex ( binsocket_patch.dart:874:3 )

message 14_NativeSocket.multiplex.multiplex ( binsocket_patch.dart:874:3 )

message 15_NativeSocket.multiplex.multiplex ( binsocket_patch.dart:874:3 )

**Comment by DanTup** [comment]
@Ibtesam-Mahmood thanks for digging into this! It seems strange to have so many nested calls to `_addPreviouslyExcludedSources` if the folder only contains one item. Are there any hidden files or folders (or symlinks?) inside `/Users/ibtesamm/Documents/Programming/Dart/TEST/`?

**Comment by Ibtesam-Mahmood** [comment]
There appears to be 1 hidden folder created so that i can easily navigate from any file to my "programming" folder through terminal.
![Screen Shot 2019-04-22 at 5 20 17 PM](https://user-images.githubusercontent.com/29645101/56531971-f24df700-6522-11e9-8f90-ccdc1f277a26.png)

**Comment by Ibtesam-Mahmood** [comment]
So I deleted this nested folder and it appears to have fixed the issue. thank you for your time. I'll repost an issue if this continues to happen

**Comment by DanTup** [comment]
@Ibtesam-Mahmood thanks for tracking this down! Is this folder a symlink? I guess the server is getting stuck in a loop if it points back at an ancestor folder.

@bwilkerson do you think this is something we could/should handle in the server? Either by not following it, or noticing when it's looping?

**Comment by bwilkerson** [comment]
I suppose that we _could_ handle it, but in general the dart tooling doesn't handle symlinks. We moved away from a `packages` directory to a `.packages` file in order to avoid having to deal with symlinks. So unless there's a strong need for symlinks, I suspect that we won't spend the resources on solving the problem.
