### ISSUE TITLE
After version v2.25.0 the debugger gives error

### ISSUE THREAD

**Issue by alvinpedo** [Dart-Code/Dart-Code#1569]
Error debugging:

Launching lib\main.dart on ASUS Z01KD in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  C:\Users\ALVIN\Desktop\fluttervscode\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml:27: AAPT: error: attribute android:appComponentFactory not found.

  C:\Users\ALVIN\Desktop\fluttervscode\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml:63: AAPT: error: resource xml/flutter_image_picker_file_paths (aka com.example.fluttervscode:xml/flutter_image_picker_file_paths) not found.

  C:\Users\ALVIN\Desktop\fluttervscode\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml:72: AAPT: error: resource xml/flutter_image_picker_file_paths (aka com.example.fluttervscode:xml/flutter_image_picker_file_paths) not found.

  error: failed processing manifest.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by DanTup** [comment]
Thanks for the report! This is probably not related to the VS Code extension update as a build error coming from Flutter. If you run `flutter clean` from your project directory, does it make a difference?

Which channel/version are you on (the output of `flutter doctor -v` will show this).

**Comment by alvinpedo** [comment]
Microsoft Windows [versão 6.3.9600]
(c) 2013 Microsoft Corporation. Todos os direitos reservados.

C:\Users\ALVIN\Desktop\fluttervscode>flutter clean
Deleting 'build\'.
Deleting 'C:\Users\ALVIN\Desktop\fluttervscode\.dart_tool\'.




C:\Users\ALVIN\Desktop\fluttervscode>flutter doctor -v
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [versÃ£o 6.3.9600], locale pt-BR)
    • Flutter version 1.2.1 at C:\flutter
    • Framework revision 8661d8aecd (6 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\ALVIN\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code (version 1.32.3)
    • VS Code at C:\Users\ALVIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.25.0

**Comment by alvinpedo** [comment]
I do not know exactly what happened, how the computer went back to normal.
