### ISSUE TITLE
VS Code: Use URIs for VM Service connections instead of ports

### ISSUE THREAD

**Issue by devoncarew** [Dart-Code/Dart-Code#1572]
We should ensure the debugger uses a service protocol url (instead of a service protocol port) to connect.

Related to https://github.com/flutter/flutter-intellij/issues/3341.

@DanTup, not sure if this is already done

**Comment by DanTup** [comment]
I've only been able to test with the VM so far, and it *seemed* to work ok (then I noticed DevTools, and got side-tracked). It'll need support from Flutter before I can be sure whether there's anything else left though - and there are some places I know only accept ports (like `flutter attach`) - not sure if they're all in-scope for this work though.

**Comment by DanTup** [comment]
I believe the only part left to this, is fixing up `flutter attach` to not use `--debug-port`, so I've opened a specific issue for that (https://github.com/Dart-Code/Dart-Code/issues/1632), however that'll require some Flutter tooling changes (which I think @bkonyi is looking at).
