### ISSUE TITLE
Way to suppress errors detected in local Flutter SDK 

### ISSUE THREAD

**Issue by wprater** [Dart-Code/Dart-Code#1577]
I have a `vendor/flutter` with a local checkout of the Flutter SDK we wish to use.  Dart seems to be detecting a ton of errors.  Im wondering if there is a way to suppress this?  Maybe a config option?

<img width="936" alt="image" src="https://user-images.githubusercontent.com/10452/55520982-a26ec500-5633-11e9-8bd7-cd1164b7caa5.png">

**Comment by DanTup** [comment]
You could try using the [dart.analysisExcludedFolders](https://dartcode.org/docs/settings/#dartanalysisexcludedfolders), though having the SDK inside your project folder isn't something we've explicitly tried to support. Is there a reason you don't have the SDK alongside the project, rather than inside it?

**Comment by wprater** [comment]
I tried that just now, and does not seem to have any affect.

`"dart.analysisExcludedFolders": ["${workspaceFolder}/vendor/flutter"]`

We put our SDK in the project folder so we can ensure version across our team.  Similar to the example here https://github.com/flutter/flutter/issues/3770#issuecomment-358745241

**Comment by DanTup** [comment]
Try removing `${workspaceFolder}/`. We don't do any variable resolution on these values (VS Code doesn't expose an API for us to handle all the variables it supports elsewhere), but we do support relative paths and stitch them on:

https://github.com/Dart-Code/Dart-Code/blob/master/src/extension.ts#L517-L526

**Comment by wprater** [comment]
@DanTup thanks for code sample, that's very helpful!  

We could just open the `lib` dir, but we may have tests and utils outside of that and I like to have the workspace :)

```
⟩ tree . -L 1
.
├── README.md
├── analysis_options.yaml
├── android
├── assets
├── build
├── flutterw
├── ios
├── lib
├── node_modules
├── pubspec.lock
├── pubspec.yaml
├── test
└── vendor
```

Changing to the relative path did the trick tho!  Sorry I did not see that option earlier, I think I had filtered the settings pane by Flutter and not Dart.

**Comment by DanTup** [comment]
@wprater Cool, glad it works! When using the Settings UI you can see all of the "Dart & Flutter" ones together in a section on the left (under Extensions) that is easier to browse. There are quite a few things that apply to Dart without Flutter, so might not show up by searching for Flutter. (That said, I agree that things might not be as discoverable as they could be, and will try to work on that).

If you hit any other issues, please don't hesitate to open issues. Even if they turn out to be easily solvable like this, it's good to have them written up for other people searching for answers to similar things :-)
