### ISSUE TITLE
Add additional Flutter search locations: ./.flutter and ./vendor/flutter

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#1589]

**Comment by wprater** [comment]
Ref https://github.com/passsy/flutter_wrapper which puts a vendorized Flutter SDK into `.flutter`

**Comment by DanTup** [comment]
Probably makes sense to tackle this with #1442 to avoid adding more sync filesystem checks during startup (esp. given we never got to the bottom of the reports of VS Code performance warnings).
