### ISSUE TITLE
Go to Definition replaces open file if it is not main.dart

### ISSUE THREAD

**Issue by wyattbiker** [Dart-Code/Dart-Code#1596]
```
Version 1.33.0 (1.33.0)
0dd516dd412d42323fc3464531b1c715d51c4c1a
2019-04-04T15:01:38.042Z
```

If you right click and open a class with **Go to Definition**, then in that new open file window you open another class using **Go to Definition**, the current file window is replaced with the new file. Is this by design? I would prefer it keeps opening new ones and let me close them as needed. Unless there is an option for that, I couldn't find it.

**Comment by DanTup** [comment]
My guess is what're seeing is "preview mode" in VS Code, see:

https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode

If you have a file open in preview (the tab is italic) then it's replaced when something else is opened. There is a setting to disable it (it's VS Code-wide, not Dart-specific) in the info above.

Let me know if this solves your issue!

**Comment by wyattbiker** [comment]
Yep it has to do with Preview. After reading the doc link you supplied, I found the way to keep it open, if required, by right click on the tab and select Keep Open. Very nice. Thanks!

**Comment by DanTup** [comment]
Great, thanks for confirming!
