### ISSUE TITLE
Debugging not pausing when rethrowing

### ISSUE THREAD

**Issue by bergwerf** [Dart-Code/Dart-Code#1597]
Well, its that time of the month again :S, it looks like I found another bug in the debugger (or perhaps in pub test). This may not be a bug with Dart code but I hope you can look into it :)

```dart
import 'package:test/test.dart';

main() {
  test('test', () {
    throws();
  });
}

void throws() {
  try {
    num.parse('a');
  } on Exception {
    rethrow;
  }
}
```

This should pause on the num.parse throwing a format exception but instead pub test terminates.

**Comment by DanTup** [comment]
Yep, I can repro this with a recent build. Commenting out the try/catch does result in an unhandled exception that breaks the debugger:

<img width="354" alt="Screenshot 2019-04-08 at 11 41 21 am" src="https://user-images.githubusercontent.com/1078012/55718275-415c3e00-59f3-11e9-8430-2718e184c666.png">

But with the `rethrow` it just carries on. This happens regardless of the `setLibraryDebuggable` settings.

@jakemac53 @bkonyi any ideas about this? Does this seem like a pub/test issue, or a VM issue?

**Comment by DanTup** [comment]
I've opened https://github.com/dart-lang/sdk/issues/36907 since this very much looks like a VM issue (though from https://github.com/dart-lang/sdk/issues/29550 it seems like the expected behaviour is not entirely clear).

**Comment by DanTup** [comment]
This has been fixed in the SDK and I've verified in the nightly build :-)
