### ISSUE TITLE
import display unused warning and cannot use it inside the code

### ISSUE THREAD

**Issue by korakotlee** [Dart-Code/Dart-Code#1603]
![Screenshot (2)](https://user-images.githubusercontent.com/23171381/55745296-c4799600-59eb-11e9-9e45-279c8267b38e.png)

The import statement define class CCard but it shows `unused import`, but I use it in the code and it show error `CCard isn't a type`

**Comment by DanTup** [comment]
I think the issue is that on line 10 you have something that looks like a symbol named `CCard`, which I suspect is conflicting with the class you've imported.

**Comment by korakotlee** [comment]
indeed, sorry, closing issue now

**Comment by DanTup** [comment]
Great, glad it was something simple! 👍
