### ISSUE TITLE
Debug console is limited to 10000 lines

### ISSUE THREAD

**Issue by kinex** [Dart-Code/Dart-Code#1613]
It seems that debug console is now limited to max 10000 lines. I am wondering was there this kind of limit earlier or am I just logging now more than before. Anyway, is there a way to change this limit (preferably to unlimited)? I really need to get full log from the beginning of the debug session.

Other related issue: I think debug console auto-scrolling behavior has changed in the latest update. Now the auto-scrolling stops working occasionally and you have to manually scroll to the end to see the latest log lines again. I think there was not this kind of issue earlier.

**Comment by DanTup** [comment]
I wasn't aware of this limitation, but it's something controlled by VS Code, not extensions.

I found [this comment](https://github.com/Microsoft/vscode/issues/68100#issuecomment-464642902) which confirms it is hard-coded at 10,000 lines (there's no indication that it has been reduced - so I would guess maybe you're just logging more).

I don't know exactly what your use case is, but could you write to a file or something instead? If not, it may be worth opening a VS Code request to make it configurable.

> Other related issue: I think debug console auto-scrolling behaviour has changed in the latest update. Now the auto-scrolling stops working occasionally and you have to manually scroll to the end to see the latest log lines again. 

I've seen this too, though it's also VS Code behaviour - there's an open issue about it in the VS Code repo here:

https://github.com/Microsoft/vscode/issues/71737

**Comment by DanTup** [comment]
(I don't think there's anything to do in the Dart extension here, but do shout if you think that may not be the case!).

**Comment by DanTup** [comment]
The scrolling issue should be fixed in tomorrow's Insiders build of VS Code - do give it a try and post feedback at https://github.com/Microsoft/vscode/issues/71737 if you still see issues!
