### ISSUE TITLE
Cursor moved to the end of file after auto format by saving

### ISSUE THREAD

**Issue by skybur** [Dart-Code/Dart-Code#1615]
So I have format on save turned on, and while debugging when I make an edit to a Flutter-related file (contains Stateless/Stateful Widget) that triggers a format (e.g. add a trailing comma) and saved somehow the cursor moved to the end of file. This bug affected currently opened Flutter-related files and still persists after debugging stops.

tl;dr **How to reproduce:**
1. Turn on Format on Save
1. Open a Flutter-related file (contains Stateless/Stateful Widget)
1. Start a debug session
1. Edit the file to trigger formatting (e.g. add a trailing comma)
1. Save the file
 
This is not a major bug but still annoying.
I don't know if this issue is for VS Code, Dart Server, or this plugin, though.

**VSCode version 1.33.0**
**Dart Code version 2.25.0**
flutter doctor
```
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.437], locale en-US)
    • Flutter version 1.2.1 at D:\Devs\Flutter\flutter
    • Framework revision 8661d8aecd (8 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\AndroidSDK
    • ANDROID_SDK_ROOT = D:\AndroidSDK
    • Java binary at: D:\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.2)
    • Android Studio at D:\AndroidStudio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code, 64-bit edition (version 1.33.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.25.0

[√] Connected device (1 available)
    • Redmi 3S • c37ae0927d63 • android-arm64 • Android 6.0.1 (API 23)

! Doctor found issues in 1 category.
```

**Comment by DanTup** [comment]
@skybur I can't repro this anymore - there has been a VS Code patch release - can you confirm if it seems fixed for you?

Note: There is another issue with the selection moving (but not to the end of the file, and not only when saving), I'm going to open a new VS Code issue about that now.

**Comment by skybur** [comment]
> 
> 
> @skybur I can't repro this anymore - there has been a VS Code patch release - can you confirm if it seems fixed for you?
> 
> Note: There is another issue with the selection moving (but not to the end of the file, and not only when saving), I'm going to open a new VS Code issue about that now.

Yup after updating this doesn't happen anymore. Thanks for passing it to the VS Code team

**Comment by DanTup** [comment]
Great, thanks for confirming!
