### ISSUE TITLE
Update "flutter attach" support to use full VM service URIs

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#1632]

**Comment by DanTup** [comment]
This requires Flutter to support something other than `--debug-port` so we can pass a full URI.

**Comment by jonahwilliams** [comment]
This should be available as `--debug-uri`

**Comment by DanTup** [comment]
Great, thanks! I'll need to add a version check to ensure we don't try to send it when it's not supported. Looks like it was added in https://github.com/flutter/flutter/commit/3764cb851572dd92b82e0d0b0c24e34d17c043b9 but there isn't a version tag on it, so I'll have to fill that in once the next version is tagged.
