### ISSUE TITLE
Update notification is shown even after first install

### ISSUE THREAD

**Issue by Tyriar** [Dart-Code/Dart-Code#1633]
I saw this on my first install:

<img width="453" alt="Screen Shot 2019-04-18 at 2 47 25 PM" src="https://user-images.githubusercontent.com/2193314/56393340-fe674b00-61e8-11e9-958c-70c56354b683.png">

It could help reduce spammy notifications by suppressing the notification on install and only showing it when updates occur.

**Comment by DanTup** [comment]
@Tyriar thanks! I hadn't considered that - we basically just check in the extension context whether we've every shown a notification for the current version. I'll see if I can detect when it's the first run, and if not, just add another flag to track this.

**Comment by Tyriar** [comment]
@DanTup :+1: the strategy we've used for this sort of thing is to store the last version the update notification was shown, if that value doesn't exist in local storage that means it's the first run and doesn't need to show

**Comment by DanTup** [comment]
Good idea, that makes more sense than my flag-per-version. I think mine came from already having a "Don't show this again" message that just took a key, so I just stuck reused it with the version number 😄

Thanks!
