### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by mickeymond** [Dart-Code/Dart-Code#1636]
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `2.25.1`
- OS Version: `Linux x64 5.0.0-13-generic`
- VSCode version: `1.33.1`

**Comment by DanTup** [comment]
I'm guessing this is a dupe of #1628, but I can't be sure without the CPU profile file that was generated as part of this message.
