### ISSUE TITLE
Support "Debug: Attach to Flutter Process" workflow for desktop

### ISSUE THREAD

**Issue by stuartmorgan** [Dart-Code/Dart-Code#1638]
STR:
- Set `ENABLE_FLUTTER_DESKTOP` to `true` in `dart.env`
- Clone https://github.com/google/flutter-desktop-embedding.git
- Open flutter-desktop-embedding/example in VS Code
- From a terminal, `flutter run` in flutter-desktop-embedding/example to launch the process outside of VS Code
- Attempt to attach with `Debug: Attach to Flutter Process`

The desired behavior in this case is to prompt for a URI, but instead it goes directly into a mode where it waits for a connection (based on previous discussion, it sounds like it's scanning for a log message that's never going to arrive).

I have tested with a launch.json config using the URI (using 2.26b1) and it works fine, but that's a fairly painful process now that the auth token system prevents just hard-coding an observatory URI in both the app and the config and leaving it alone; every new run requires editing the launch.json again.

**Comment by DanTup** [comment]
I'm re-purposing the `Flutter: Attach to Process` command to prompt for a VM Service. The original command will be called `Flutter: Attach to Device`.

All the new command does, is creates a launch config that includes this:

```js
"observatoryUri": "${command:dart.promptForVmService}"
```

And `dart.promptForVmService` is a new command that prompts for a URI, validates it, and returns it.

For vNext, using the command will or manually adding the above to your `launch.json` will be the only way to do this, but for a future release we'll have a "configurationSnippet" that pre-populates it for you in launch.json (to do this, we need to migrate from package.json configuration snippets to handling them in code - I've opened #1727 for this).
