### ISSUE TITLE
Dart: New Project Plugin does not create .packages file.

### ISSUE THREAD

**Issue by wyattbiker** [Dart-Code/Dart-Code#1646]
```
VS Code: Version 1.33.1 (1.33.1)
51b0b28134d51361cf996d2f0a1c698247aeabd8
2019-04-11T08:14:39.158Z

Plugin
Name: Dart
Id: dart-code.dart-code
Description: Dart language support and debugger for Visual Studio Code.
Version: 2.25.1
Publisher: Dart Code
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

```
Mac OS X. How to reproduce.
```
Shift+Cmd+P and select Dart: New Project. 
Select Console Application type project
Enter a project name and create it.
```

Will not create the .packages file. You need to Right click on pubspec.yaml and select `Get Packages` to create the .packages file and fixes the issue. See attachment.

![Screen Shot 2019-04-25 at 7 26 49 PM](https://user-images.githubusercontent.com/930478/56774653-b2d91200-6791-11e9-8b26-d9f3279716bd.png)

**Comment by DanTup** [comment]
Thanks for the report! This issue was been fixed in #1450 and will ship in v2.26. Provisional release notes are at https://dartcode.org/releases/v2-26/ and the release is imminent :-)
