### ISSUE TITLE
Update emulator name in status bar.

### ISSUE THREAD

**Issue by TheHemantKaushik** [Dart-Code/Dart-Code#1648]
Issue Type: <b>Feature Request</b>

Currently my emulator name is showing as 'Android SDK built for x86 (android-x86 Emulator)' in status bar.

Please show actual name of emulator I set at the time of creating it, that is 'xhdpi-27'.

Extension version: 2.25.1
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

**Comment by DanTup** [comment]
This name comes from `flutter devices`, so this needs to be improved there.

Looks like there's already open an issue at https://github.com/flutter/flutter/issues/11850 so I'll close this as a dupe - subscribe to that one for updates. Thanks!
