### ISSUE TITLE
Convert extension to Dart

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#166]
It's a long-term goal to have the extension written in Dart instead of TypeScript. I have no idea how much work it'll be or how feasible it'll be, but this case is to collect notes on it.

Some things that immediately spring to mind:
- `DDC` or `dart2js`?
- Will require background compiling to make development easier
- How would we debug it? Our debugger is for the Dart VM, not Node
- Can we easily get/create reliable VS Code bindings for Dart (that can be easily updated)?
- Can we do a progressive conversion or would the interop just add loads more work?

In the first instance, we should build a "Hello World" extension that just does some basic things in Code before trying to convert any real functionality.

**Comment by DanTup** [comment]
I want to work on web support first, but this will likely be the next big dev after that.

@pulyaevskiy made the VS Code Hello World extension work:

https://github.com/DanTup/vscode-hello-world-dart

Need to think about how best to port the VS Code API definitions from TypeScript to Dart reliably (must be automated, since it changes every month!) and probably third party libs. I think there's already a nodejs binding somewhere.

Also need to port all the stuff we currently script to ts (from the analyzer spec). It might be possible to reuse that from an analyzer package or something, but if not we can just change the codegen to create Dart.

(@matanlurey FYI)

**Comment by matanlurey** [comment]
I imagine we could use https://github.com/dart-lang/js_facade_gen?

**Comment by matanlurey** [comment]
@DanTup:

> Some things that immediately spring to mind:

> *   `DDC` or `dart2js`?

Likely you will want DDC for edit-refresh cycle and dart2js to deploy to the marketplace, but on the other hand, dart2js doesn't have a great story for exporting APIs for use _from_ JavaScript - though if the API surface isn't huge then maybe it won't matter.

> *   Will require background compiling to make development easier

What does this mean?

> *   How would we debug it? Our debugger is for the Dart VM, not Node

DDC is pretty readable JS, plus ships with source map support.

> *   Can we easily get/create reliable VS Code bindings for Dart (that can be easily updated)?

Perhaps via https://github.com/dart-lang/js_facade_gen?

> *   Can we do a progressive conversion or would the interop just add loads more work?

Good question. A progressive conversion might be possible. But...

> In the first instance, we should build a "Hello World" extension that just does some basic things in Code before trying to convert any real functionality.

Yup, should definitely do this first.

**Comment by DanTup** [comment]
> Likely you will want DDC for edit-refresh cycle and dart2js to deploy to the marketplace, but on the other hand, dart2js doesn't have a great story for exporting APIs for use from JavaScript

I figured we'd use both, but I don't totally know the reasons for normally avoiding DDC for production. There's not going to be any redundant code so tree-shaking doesn't really matter. The output needs to interact with node modules heavily.

> > Will require background compiling to make development easier
> 
> What does this mean?

When making code-changes and hitting save, we'd really want DDC to recompile before we hit F5 (to minimise the time waiting for compilation after every change). I don't know whether DDC has some "watch" mode or will still require Bazel, or whatever - I've not really been following what's going on here.

> DDC is pretty readable JS, plus ships with source map support.

Yeah, I need to look into what the options are here. There's a node debugger already and part of the web work will likely involve using the Chrome debugger.. I need to investigate whether Dart Code can piggy-back another debug adapter (to avoid us re-implementing what already exists in an MS extension) and if that works with source maps, it'll probably be usable for both the web and extension stuff :-)

> Perhaps via https://github.com/dart-lang/js_facade_gen?

I think that's what @pulyaevskiy was suggesting; haven't played with it yet though!

> > Can we do a progressive conversion or would the interop just add loads more work?
> 
> Good question. A progressive conversion might be possible.

I think this might actually not be too tough. Most of the stuff is really isolated (eg. all the providers), so if we can get Dart and TypeScript output node classes for each of them, we can probably host them in the extension together. The complicate bits might be where they need to call the same code (eg. Analyzer), but maybe we can can have a binding/facade over that for the language it's not written in during the transition.

> Yup, should definitely do this first.

That's actually done now in the repo I linked above. It uses [this package](https://pub.dartlang.org/packages/vscode) which isn't being maintained though; so might need to look at forking/updating it.

**Comment by mit-mit** [comment]
cc @devoncarew who I believe has experience with this from atom?

**Comment by devoncarew** [comment]
Yes, it would be a fairly similar undertaking. It would be a non-functional requirement (but a nice to have feature) for the extension it to be written in Dart. Interop would likely be the biggest issue. I used dart2js to compile at the time (DDC was not quite ready then).

This is likely low-priority given other things we could do instead, but something we could explore if we wanted a large project to help push on JS interop improvements.

**Comment by DanTup** [comment]
Yeah, I understand this is high effort for low gain. It's just something I'd like to do long term. My main motivations are:

- I started Dart Code in part because I wanted to write Dart, but I ironically ended up writing TypeScript! (this can be fixed other ways though; like having a Dart side-project, which I hope to have time for soon!)
- It seems weird to write in what's arguably a competitor to Dart (open to questions like "If Dart is so good, why is this written in TypeScript?!")
- It'd be good dog-fooding - the more I use Dart Code, the more I'll notice its issues and hopefully improve it :)

None of these are massive; but I don't want to give up on the idea long-term. Possibly this will tie in a little with web support (something I also really want to get to, but isn't a priority and is best done after all web tooling changes are done) since it'll use DDC/dart2js.

I suspect it's something that could be done progressively. Eg. once the "infrastructure" stuff works (which I think is basically scripting conversion of vscode.d.ts to a Dart equiv and being able to register a Dart provider from the existing TypeScript activation) it could open the door to doing new work in Dart without having to port all existing code. I expect I could get the Dart/TS code to both wrap the same analyzer process (to avoid increased overhead); though some of this may go away if switched to LSP.

**Comment by devoncarew** [comment]
> It'd be good dog-fooding - the more I use Dart Code, the more I'll notice its issues and hopefully improve it :)

I've found that to be extremely useful myself in the past :)

> though some of this may go away if switched to LSP.

Perhaps some of the conversion work could be done as part of a move to LSP? You're communicating across a wire, so our end could be written in Dart. The parts of the plugin that we can't move across a wire could stay in typescript for now.

**Comment by DanTup** [comment]
Yeah, I think if I'm spending some time doing Dart (whether it be analyzer, LSP implementation or even a side project if I end up with some free time outside of work), that'll satisfy some of my needs so porting everything will be less important to me (especially given it's added risk for not much benefit to users).

Will see how things go; I'm not in a rush to go all-dart. More interesting things might come up anyway, and there's always the possibility that doing interop with a big non-Dart project like Code might turn out to be rather complicated.

**Comment by DanTup** [comment]
I don't think this is a worth goal anymore. With LSP much of the logic will move to the server anyway, and the overhead of trying to convert/maintain the VS Code bindings in Dart for what's left seems seems not worthwhile.

(Though if things significantly change, we can revisit!).
