### ISSUE TITLE
Allow hover content reorder

### ISSUE THREAD

**Issue by xster** [Dart-Code/Dart-Code#1671]
This may or may not actually come from the dart-code plugin. 

The hover currently shows the signature, then the dartdoc, then the error on the hovered entity if applicable. But often the dartdoc is long. It would be nice to show the error first, then the signature, then the dartdoc.

**Comment by DanTup** [comment]
Yeah, I've noticed this a lot lately too. It's VS Code doing this. I've opened https://github.com/Microsoft/vscode/issues/73120 with a TypeScript example to show it's not just us.

Thanks!
