### ISSUE TITLE
change flutter channel from vscode

### ISSUE THREAD

**Issue by jagdishjadeja** [Dart-Code/Dart-Code#1680]
can we have a option in command palette of vscode to change flutter channel  ?

**Comment by DanTup** [comment]
This wouldn't be difficult to do, but I'm weary about ending up with every flutter command reproduced in the VS Code command palette (and then having to maintain them, and ensure they work across multiple SDKs).

How often are you changing channel, and for what reasons? We do have a way to easily switch between multiple SDK folders (the `flutter.sdkPaths` setting) so I wonder if for your use case it'd be better to have multiple Flutter clones and switch between them? (this would also prevent re-downloading everything on each switch).

**Comment by jagdishjadeja** [comment]
I think having multiple clone is better solution for this
