### ISSUE TITLE
Extension enables itself after each upgrade

### ISSUE THREAD

**Issue by SharakPL** [Dart-Code/Dart-Code#1690]
I have this extension disabled globally in my VSCode on Windows 10 Pro x64 and use it only on Flutter workspaces (the same with Flutter extension), but every time it gets updated it enables itself globally. [Flutter](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter) and other extensions don't have that problem.

**Comment by DanTup** [comment]
@SharakPL Can you confirm how you're disabling it? If you're using the feature in VS Code, I don't believe there's anything we can do to bypass that, so this could be a VS Code bug and may need reporting at https://github.com/Microsoft/vscode (feel free to CC me on an issue if you open one there).

**Comment by DanTup** [comment]
I've opened https://github.com/microsoft/vscode/issues/73484 asking for help from the VS Code team, since this feels like a bug there.

**Comment by DanTup** [comment]
This issue has been fixed in the next  release of VS Code (which I suspect should be released in the next week or so):

https://github.com/microsoft/vscode/issues/71752

**Comment by SharakPL** [comment]
@DanTup great! thanks for the info
