### ISSUE TITLE
Analyzing is not stopping when a syntax error occurred

### ISSUE THREAD

**Issue by skybur** [Dart-Code/Dart-Code#1692]
So when I make a syntax error (e.g. typing a widget that doesn't exist/not imported) analyzing is not stopping. This broke autocomplete, hover preview, and formatting. Restarting VSCode or reopening the project folder fixed this, but that's quite annoying since syntax error is (always) gonna happen when coding.

I think this happens after I updated to version 3.0.0 earlier and also updated flutter to 1.5.4, because before I updated this didn't happen.

VSCode version 1.33.1
Dart-Code version 3.0.0
Output of flutter doctor:
```
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.475], locale en-US)
    • Flutter version 1.5.4-hotfix.2 at D:\Devs\Flutter\flutter
    • Framework revision 7a4c33425d (9 days ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\AndroidSDK
    • ANDROID_SDK_ROOT = D:\AndroidSDK
    • Java binary at: D:\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at D:\AndroidStudio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code, 64-bit edition (version 1.33.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.0.0

[√] Connected device (1 available)
    • Redmi 3S • c37ae0927d63 • android-arm64 • Android 6.0.1 (API 23)

• No issues found!
```
Log File
[Dart-Code-Log-2019-04-03 15-18-19.txt](https://github.com/Dart-Code/Dart-Code/files/3156358/Dart-Code-Log-2019-04-03.15-18-19.txt)
![2019-05-08_15-19-21](https://user-images.githubusercontent.com/11155424/57361640-12c6b400-71a7-11e9-8a65-3e436aaeac34.gif)

**Comment by larssn** [comment]
In general, the analyzer seems overly eager. My colleagues and I constantly run into this behavior, where eventually we have to restart VSCode in order for it to start performing decently again.

**Comment by DanTup** [comment]
Looks like an error is occurring and the server is pausing on the exception (cc @bwilkerson @scheglov)

```
[15:18:32 GMT+0700 (SE Asia Standard Time)] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
[15:18:33 GMT+0700 (SE Asia Standard Time)] [Analyzer] [Error] vm-service: isolate (332
[15:18:33 GMT+0700 (SE Asia Standard Time)] [Analyzer] [Error] 584260) 'main' has no debugger attached and is paused due to exception.  Connect to Observatory to debug.
```

Can you try running the **Dart: Open Analyzer Diagnostics** command when this happens, then in the web app it launches, see if any Exceptions are logged on the left?

If not, then enable [analysis server logging](https://dartcode.org/docs/logging/#analyzer) then run **Open Workspace Settings** in VS Code, then add this to the JSON:

```js
"dart.analyzerObservatoryPort": 8123
```

Then open the analysis server log and look for a line like this:

Observatory listening on http://127.0.0.1:8123/Zk1IGhwQ8dc=/

Then paste that link into your browser. Hopefully somewhere you'll see a list of isolates and one of them will have something like "paused by exception" on the right side with a **debug** link. Click that link and please attach a screenshot of what is shows.

**Comment by DanTup** [comment]
@larssn 

> In general, the analyzer seems overly eager. My colleagues and I constantly run into this behavior, where eventually we have to restart VSCode in order for it to start performing decently again.

If you're seeing serious issues like this, *please* do file bugs for investigation. Having to restart your editor or the server is not acceptable and we'd definitely like to get to the bottom of any issues causing this. First we need to know about them though :-)

**Comment by larssn** [comment]
@DanTup I understand that, but we're basically in crunch mode, so time is sparse, and these things usually end up consuming a fair bit of time. But I'll see if I can squeeze in some diagnostics for you guys.

**Comment by skybur** [comment]
Sorry not in front of my pc right now. Will try what you suggested later.

**Comment by DanTup** [comment]
Understood - though even just opening an issue with a short description would help - at least we'd know there's a potential issue. Sometimes these perf issues turn out to be trivial to diagnose. I have tried to make it as simple as possible to gather logs with the **Dart: Capture Logs** command (which aggregates logs from analyzer, debugger, flutter, pub, etc. into one), but I'm always open to improving this if people have ideas.

For ex. https://github.com/microsoft/vscode/issues/71165 was huge lockup in VS Code's UI that a user reported (but I'd never experienced). It took me a while to get a log (he was also very busy and figured it'd be lots of effort), but from the log it was immediately obvious he had thousands of errors and I was able to easily reproduce. I reported it to VS Code and it was fixed the same day (and available to the user in Insiders the following day!).

So if you do get some time when you're not so busy, please do open a new issue (it might not be the same as this one, so easier to investigate separately) and with the info you can easily get, and we'll go from there.

**Comment by scheglov** [comment]
I saw sometimes cases when an exception, even a caught one causes Observatory to stop the app. So, I also add `--pause_isolates_on_unhandled_exceptions=false`. But I was not able to reproduce this stopping behavior on the bleeding edge SDK.

**Comment by DanTup** [comment]
@skybur thanks, that helps!

How reliably can you reproduce this? Is it on a specific project? (If so, is it shareable, or can you trim it down such that it is?).

@scheglov 

> I saw sometimes cases when an exception, even a caught one causes Observatory to stop the app

That does sound concerning. In the call stack shown above, frame 13 appears to show that we're inside the `makeCurrentWhile` handler and calling `handleRequest`. The call to `handleRequest` is inside a `try`/`catch` block as far as I can tell 🙀

How recently did you see it? This looks like a relatively recent SDK:

> Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

**Comment by skybur** [comment]
I can always reproduce it on a freshly created project. Lemme try if this
also happens with flutter 1.2.1, so we can narrow it down.

**Comment by skybur** [comment]
Just tried to reproduce this on flutter 1.2.1 and it didn't happen.

**Comment by DanTup** [comment]
@skybur Can you remove the port number setting I told you to add above, then enable the [analysis server log](https://dartcode.org/docs/logging/#analyzer) and repro, then attach that log?

**Comment by DanTup** [comment]
Is GitHub seriously messed up for anyone else? Comments are coming through with times in the future, and affecting how the comments are sorted? :/

**Comment by DanTup** [comment]
(@skybur I made some comments, but because GH seems messed up and stamped the wrong time on your comment, my replies appear above it - so if you clicked through from notifications and can't see my comments, scroll up! 🤷‍♂️)

**Comment by scheglov** [comment]
@DanTup I first started seeing stopping on exceptions when Observatory is turned on at least a couple of years ago. Found the flag to disable it, configured my IDEA and forgot about it. So, it is not something new, I think.

**Comment by DanTup** [comment]
@scheglov you mean you started passing `--pause_isolates_on_unhandled_exceptions=false` and have had it on since?

I could pass that in from VS Code, but that flag has the word "unhandled" in it, and as far as I can tell, these are being handled. Something doesn't seem to add up.

**Comment by skybur** [comment]
So here's some funny thing. After I switched to flutter 1.2.1 to reproduce this and switched back to 1.5.4, somehow I cannot reproduce this again 🤷‍♂
Since it's currently 1 am in my timezone, I'm gonna close this for now and reopen it if I encountered this again tomorrow at work.
Thanks @DanTup for bearing with me.

**Comment by scheglov** [comment]
@DanTup Yes, I added it once and keep it thee. Yes, that surprised me too.
Maybe someone from Dart VM team (@a-siva maybe?) could comment on whether it is a known problem that Observatory stops when an exception would be caught, and whether `--pause_isolates_on_unhandled_exceptions=false` should affect this case.

**Comment by DanTup** [comment]
Ok, I can reproduce this and I think I understand what's happening.

I believe that when @skybur hit this, the `dart.analyzerObservatoryPort` setting may have already been set, which means we had run the server with `--observe=x`. This causes the server to break on *unhandled* exceptions.

So, I made the server throw in the same location, and when it stopped responding, I attached VS Code to it:

![Screenshot 2019-05-09 at 2 35 06 pm](https://user-images.githubusercontent.com/1078012/57457571-b081b800-7267-11e9-8027-12137249e713.png)

So I walked up the stack and I noticed this... `getFixes` is `async`:

![Screenshot 2019-05-09 at 2 36 18 pm](https://user-images.githubusercontent.com/1078012/57457667-da3adf00-7267-11e9-8332-01edb25affea.png)

Yet the call is not `await`ed:

![Screenshot 2019-05-09 at 2 36 09 pm](https://user-images.githubusercontent.com/1078012/57457690-e3c44700-7267-11e9-9d6f-4d655a60978f.png)

This means the exception is happening "later", after the `try`/`catch` here has completed.

So I believe this is a server bug - if we're going to start async work and not `await` it inside a `try/catch`, I think it needs to have its own `try`/`catch` inside the async handling.

(I'll open an SDK issue with the notes for this anyway - in the meantime I'm going to show a warning whenever we start the server with `--observe` since it should only be used for specific troubleshooting and not all the time).

**Comment by skybur** [comment]
Ah yeah I just remembered, it's fixed after I removed the dart observatory
port. Yeah previously I have the observatory port set to 9200.

**Comment by DanTup** [comment]
Ha, scratch that - I didn't review the stack correctly. It's handled here:

![Screenshot 2019-05-09 at 2 41 30 pm](https://user-images.githubusercontent.com/1078012/57458045-95fc0e80-7268-11e9-9570-079237b2d04c.png)

Which is frame 8/9/10 in the stack above :(

I'll see if I can extract a small repro (though I'll also still make VS Code warn when running in this mode).

**Comment by DanTup** [comment]
Actually, forget the warning - I'll just not use `--observe` and just specific only the port, as that way we'll get the usual error report code fire and generate a log with the stack etc.

**Comment by DanTup** [comment]
> we'll get the usual error report code fire and generate a log with the stack etc.

Actually, even better - because of the loop, it just re-analyzed and tries again. So stopping the pause solves the issue for VS Code.

Still, I'll try to make a small example as this does seem like a VM bug.

**Comment by DanTup** [comment]
Ok, I've opened https://github.com/dart-lang/sdk/issues/36911 for the pausing issue, and I've changed VS Code to never use `--observe` which should prevent it ever stopping the server (I've confirmed it doesn't pause with this change - instead it just retries, and then eventually deliver the results :-)).
