### ISSUE TITLE
Breakpoints in external code not behaving correctly

### ISSUE THREAD

**Issue by kentcb** [Dart-Code/Dart-Code#1697]
Whilst attempting to debug external code with `dart.debugExternalLibraries` unset (defaulting to `false`), I encountered the following behavior:

* breakpoints explicitly set in the target method aren't always hit. I haven't worked out the heuristics around this, but may be something to do with debug-dependent code. I've included the actual code below with some notes on what was hit and what wasn't
* once a breakpoint _was_ hit, pressing `F10` to step over would actually step out of the method

Example target code (from `firebase_crashlytics`):

```dart
  Future<void> onError(FlutterErrorDetails details) async {
    print('Error caught by Crashlytics plugin:');

    bool inDebugMode = false;
    if (!enableInDevMode) {
      assert(inDebugMode = true);
    }

    if (inDebugMode && !enableInDevMode) {
      print(Trace.format(details.stack));
    } else {
      // Report error
      final List<String> stackTraceLines =
          Trace.format(details.stack).trimRight().split('\n');
      final List<Map<String, String>> stackTraceElements =
          _getStackTraceElements(stackTraceLines);
      final dynamic result =
          // TODO(amirh): remove this on when the invokeMethod update makes it to stable Flutter.
          // https://github.com/flutter/flutter/issues/26431
          // ignore: strong_mode_implicit_dynamic_method
          await channel.invokeMethod('Crashlytics#onError', <String, dynamic>{
        'exception': details.exceptionAsString(),
        // FlutterErrorDetails.context has been migrated from a String to a
        // DiagnosticsNode. Coerce it to a String here in a way that will work
        // on both Strings and the new DiagnosticsNode values. See https://groups.google.com/forum/#!topic/flutter-announce/hp1RNIgej38
        'context': '${details.context}',
        'stackTraceElements': stackTraceElements,
        'logs': _logs.toList(),
        'keys': _prepareKeys(),
      });
      print(result);
    }
  }
```
Alas, it seems GitHub markdown does not include support for line numbers in code blocks, so I'll refer to code instead:

* `print('Error caught by Crashlytics plugin:');` : hit
* `bool inDebugMode = false;` : hit
* `assert(inDebugMode = true);` : not hit
* `if (!enableInDevMode) {` : hit
* `if (inDebugMode && !enableInDevMode) {` : not hit
* `print(result);` : hit

**Comment by DanTup** [comment]
After re-reading the VM service spec, I'm not convinced my understanding of this functionality was correct. The spec says that non-debuggable won't be steppable nor will breakpoints work. So the observed behaviour appears to match neither the spec nor my understanding.

I've opened https://github.com/dart-lang/sdk/issues/36914 to see if the expected behaviour can be clarified, and we'll go from there!

**Comment by DanTup** [comment]
As part of #2428, we'll now show a warning when adding breakpoints that will not be hit due to debug settings. I think that addresses the issue described here, but let me know if you think anything still doesn't add up!
