### ISSUE TITLE
hot reload not working 

### ISSUE THREAD

**Issue by chandu0101** [Dart-Code/Dart-Code#1700]
I updated my flutter and vscode now hot reload not working . when i saved a file i can see message `Reloaded 1 of 440 libraries in 157ms.` but nothing changed in iphone Simulator , same issue when i clicked on hotreload icon from debug toolbar.

```
flutter --version
Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (11 days ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
```

```
VS code : Version 1.33.1 (1.33.1)
```

**Comment by chandu0101** [comment]
same with android studio also , looks like flutter issue!

**Comment by DanTup** [comment]
@chandu0101 if this reproduces in Android Studio too, please open an issue in the flutter/flutter repo.

Please include a description of the type of change you're making (and ensure it's not a [known limitation](https://flutter.dev/docs/development/tools/hot-reload#limitations)).

Thanks!
