### ISSUE TITLE
Intellisense lists items from all packages.

### ISSUE THREAD

**Issue by madqueendany** [Dart-Code/Dart-Code#1704]
Hey all, so, before the most recent update, VSCode's intellisense works perfectly, after the update though, it started to list items from other packages... with packages that aren't even imported.

<img width="696" alt="Screen Shot 2019-05-13 at 9 12 14 PM" src="https://user-images.githubusercontent.com/47292665/57640626-19e52c00-75c4-11e9-947f-63e9d8cd5f63.png">
<img width="765" alt="Screen Shot 2019-05-13 at 9 12 18 PM" src="https://user-images.githubusercontent.com/47292665/57640627-1a7dc280-75c4-11e9-9565-145eb82ebbe1.png">
<img width="727" alt="Screen Shot 2019-05-13 at 9 12 23 PM" src="https://user-images.githubusercontent.com/47292665/57640630-1a7dc280-75c4-11e9-8496-336914406ad9.png">
<img width="699" alt="Screen Shot 2019-05-13 at 9 12 26 PM" src="https://user-images.githubusercontent.com/47292665/57640631-1b165900-75c4-11e9-86bf-999b237278ec.png">
<img width="688" alt="Screen Shot 2019-05-13 at 9 11 49 PM" src="https://user-images.githubusercontent.com/47292665/57640632-1b165900-75c4-11e9-9cdd-1c309f52ca35.png">

**Comment by DanTup** [comment]
This is a new feature! You'll note the ones that aren't imported will say "Auto import" in their descriptions.

There's in about this in the v2.26 release notes here:

https://dartcode.org/releases/v2-26/#auto-importing-from-code-completion

You can disable this with the `dart.autoImportCompletions` settings if you don't like it.

If you like it but don't think it's working right (or as well as it could), please file specific issues and we can try to improve it!

**Comment by madqueendany** [comment]
I feel like a fool for not reading the release notes. 🙄

I guess the feature is neat but I've been noticing a slight lag when I'm typing.

I've disabled the feature and the lag is gone.

Thanks @DanTup. ❤️

**Comment by DanTup** [comment]
@madqueendany heh, no worries, less people read them than you'd think 😄

If you're seeing lagging while typing, that's definitely not good though. If you could [capture a log](https://dartcode.org/docs/logging/#capture-logs-command) while this is happening and open an issue, I'd definitely like to take a look.

**Comment by madqueendany** [comment]
Will do. 👍🏼
