### ISSUE TITLE
Hot Reload not working in VS code but works in other IDE such as Intelij Idea & Android Studio . only hot restart is working on VS code

### ISSUE THREAD

**Issue by unknown1101** [Dart-Code/Dart-Code#1708]
Issue Type: <b>Bug</b>

**Hot reload** not working in **VS code** but works in **Android studio** & **Intelij Idea** ..
here in **VS code** i have to use **hot restart** to make the app run throw **emulator** or throw the **real device** .. so why this happened ? 

> If anyone will ask for debug result that's it :-    

Reloaded 0 of 432 libraries in 3,578ms.

>  If anyone will ask for **Flutter doctor** result that's it :- 

[flutter] flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 6.1.7600], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] Android Studio (version 3.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] IntelliJ IDEA Community Edition (version 2019.1)
[√] VS Code (version 1.33.1)
[√] Connected device (1 available)

! Doctor found issues in 2 categories.
exit code 0
> I uninstalled **Dart&Flutter** plugin on **Android Studio** so this **[!]** appear on the result of **Flutter Doctor**

> **My system info** :-

Extension version: 3.0.2
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 6.1.7600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2294)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|3.89GB (0.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by DanTup** [comment]
Can you confirm how you're hot reloading - are you using hot-reload-on-save, or clicking the thunderbolt icon on the debug toolbar, or running the command from the VS Code command palette?

Could you also [capture a log](https://dartcode.org/docs/logging/#capture-logs-command) (ticking Observatory and Flutter Run) when reproducing this and attach it?

Thanks!

**Comment by bsr203** [comment]
hi @DanTup I am a new user, and I too was surprised that hot reloading is not working by saving the file while `flutter run` is executing. Reading the description of the setting `dart.flutterHotReloadOnSave` and your comment, it feels that hot reload is only active during debug session. Is there a way to trigger it on file save, while running from terminal (inside vscode)

**Comment by DanTup** [comment]
It's not possible to user hot-reload-on-save if you run from the terminal (well not unless you attach, but that would be a clunky workflow).

Can I ask why you're running from the terminal and not using the built-in support for running/debugging?

**Comment by bsr203** [comment]
:-) I just started with flutter today; and didn't quite read about it yet. Just following how I used to with wed dev (create react app) workflow. I will read the doc about running through UI. thanks for your time.

**Comment by DanTup** [comment]
If you go through the [Getting Started](https://flutter.dev/docs/get-started/editor?tab=vscode) of the website it should help you set up and run your first app. Running through VS Code (by pressing F5) should be much simpler than from the terminal, and you'll get full functionality of the debugger, hot-reload-on-save, and things like the debug toggles (switching platform, showing frame render times, etc.).

If you hit issues with this, please do open issues here. Running with F5 should be the simplest way (and give most functionality), so if it doesn't seem that way, there may be room for improvement! Thanks!

**Comment by DanTup** [comment]
@unknown1101 closing this since there was no response to the questions above. Please let me know if you're still having issues and need assistance.

@bsr203 glad it's working! If you do hit problems, feel free to open new issues!
