### ISSUE TITLE
Classes and members navigation

### ISSUE THREAD

**Issue by sestegra** [Dart-Code/Dart-Code#1712]
I miss one feature from Webstorm.

In following example, I can easily navigate with 
- Has subclasses
- Is overriden in subclasses
- Overrides method 'run' in 'Foo'
- Implements method 'something' in X

![image](https://user-images.githubusercontent.com/109060/57794818-c9e1a300-7744-11e9-8589-3c6249d8881d.png)

**Comment by DanTup** [comment]
Coincidentally, this feature was just being discussed in https://github.com/dart-lang/sdk/issues/36896#issuecomment-492703021 !

We do already have some commands that provide most (maybe all?) of this functionality:

- Go to Definition
- Go to Implementation
- Find References
- Go to Super

Unfortunately I don't believe there's a way for us to add clickable gutter icons in VS Code though, so I would recommend opening an issue at https://github.com/Microsoft/vscode requesting this (it could be implemented as a language-agnostic VS Code feature). Tjhanks!

**Comment by sestegra** [comment]
Issue created on VS Code
https://github.com/microsoft/vscode/issues/73784

**Comment by DanTup** [comment]
Cool thanks, I added a 👍 . It may be worth adding your screenshot from above too :-)

**Comment by sestegra** [comment]
Done

**Comment by sestegra** [comment]
Issue microsoft/vscode#73784 closed
