### ISSUE TITLE
Dart Analyzer stuck on analyzing after autocomplete

### ISSUE THREAD

**Issue by Ibtesam-Mahmood** [Dart-Code/Dart-Code#1713]
This problem started recently, After I auto complete a term in dart using intellisense, the portion that I had originally typed begins to show an error.

The problem is that the analyzer seems to get stuck on this error and becomes stuck. This prohibits be from using intellisense further.

image:
<img width="208" alt="Screen Shot 2019-05-16 at 4 53 38 AM" src="https://user-images.githubusercontent.com/29645101/57840430-97f92c80-7796-11e9-9794-ea899b312be3.png">

After running its course the analyzer terminates and the issue is fixed temporarily. This has become a recurring problem for me while developing in flutter since I use intellisense very liberally to create application. Please let me know if there is anything I can do to fix this issue, thank you!

Dart Analyzer Files:
[analyzer.txt](https://github.com/Dart-Code/Dart-Code/files/3186199/analyzer.txt)
[analyzerInstrumentation.txt](https://github.com/Dart-Code/Dart-Code/files/3186200/analyzerInstrumentation.txt)

Log File:
[dart-code-startup-log-1163.txt](https://github.com/Dart-Code/Dart-Code/files/3186204/dart-code-startup-log-1163.txt)

**Comment by DanTup** [comment]
Thanks for the report and logs! This looks like the issue described in #1698 which seems to be a VM bug (https://github.com/dart-lang/sdk/issues/36911). In the next version I've changed how we enable Analyzer diagnostics to avoid this.

In the meantime, please remove the `dart.analyzerObservatoryPort` setting from your settings and it should stop the issue from happening. If that doesn't help, please let me know!
