### ISSUE TITLE
Formatting always wraps words

### ISSUE THREAD

**Issue by duzenko** [Dart-Code/Dart-Code#1715]
VSCode Version 1.33.1 (1.33.1)
Dart 3.02

Whenever code formatting is invoked, it wraps my dart code even if I checked all settings I could find
I don't think it's a general VSCode issue because the same code in a .m files does not get wrapped.

```
{
    "dart.flutterSdkPath": "/Applications/flutter",
    "workbench.colorTheme": "Visual Studio Light",
    "editor.formatOnSave": true,
    "editor.minimap.enabled": false,
    "editor.codeLens": false,
    "editor.folding": false,
    "editor.highlightActiveIndentGuide": false,
    "editor.insertSpaces": false,
    "editor.lightbulb.enabled": true,
    "editor.renderIndentGuides": false,
    "editor.overviewRulerBorder": true,
    "editor.hideCursorInOverviewRuler": true,
    "editor.wordWrapColumn": 999,
    "editor.formatOnType": true,
    "editor.wrappingIndent": "none",
    "[dart]": {
        "editor.rulers": [
            0
        ]
    },
}
```

```
      final existingEvents = (await deviceCalendar.retrieveEvents(calendar.id, RetrieveEventsParams())).data;
      final newEvents = list.where((x)=>existingEvents.firstWhere((y)=>y.title == x['text']) == null);
```
Becomes
```
      final existingEvents = (await deviceCalendar.retrieveEvents(
              calendar.id, RetrieveEventsParams()))
          .data;
      final newEvents = list.where((x) =>
          existingEvents.firstWhere((y) => y.title == x['text']) == null);
```

**Comment by duzenko** [comment]
@DanTup Is there anyway to configure this per-project?
I.e. keep wrapping at 80 for flutter & flutter/plugins forks but wrap at 200 for everything else?

**Comment by DanTup** [comment]
@duzenko It's possible in VS Code with "Workspace Settings" but I'm not familiar with config in Android Studio. Maybe @pq knows if this can be set per-project?

**Comment by pq** [comment]
I don't believe this is configurable currently in IDEA.

@alexander-doroshko @jwren may know more?

**Comment by alexander-doroshko** [comment]
That's the only survived code style setting but it's there.
![image](https://user-images.githubusercontent.com/4499789/83794202-550e3d80-a6a6-11ea-9e7c-89d7eb17136e.png)

**Comment by pq** [comment]
Ah!  I was looking in the wrong place.  Excellent.  Thanks @alexander-doroshko!

**Comment by emri99** [comment]
Wish this setting could be shared with teammates.

We use `editorconfig`, however the line length defined in screenshot above overrides property in `.editorconfig` file. 

Have tried such config:
```
[*]
max_line_length = 120
```
or 

```
[*.dart]
max_line_length = 120
```

None is functional.

Is there anything to do to make editorconfig configuration take precedence over dart editor setting ?
Any alternative way to share this setting ?

Thanks ;)

**Comment by DanTup** [comment]
> We use `editorconfig`, however the line length defined in screenshot above overrides property in `.editorconfig` file.

I don't think it's being overridden - the issue is likely that the Dart formatter does not support `editorconfig` and therefore what you're setting in your editorconfig is just not being read at all by the Dart formatter. There's a related issue at https://github.com/Dart-Code/Dart-Code/issues/914.

In the meantime, you should be able to set `dart.lineLength` and commit it to your `.vscode/settings.json` file if you want to share it in the repo.

**Comment by emri99** [comment]
I forgot to mention explicitely that we are using Android Studio ^^ thanks anyway ;)

**Comment by DanTup** [comment]
Oh, gotcha! I'm afraid I don't know much about AS so don't know how you would share settings there. Perhaps someone above may jump in if there's a way though!

**Comment by alexander-doroshko** [comment]
@emri99 In IntelliJ IDEA and Android Studio, to share code style settings with teammates through Version Control System, you'll need to commit `.idea/codeStyles/codeStyleConfig.xml` and `.idea/codeStyles/Project.xml` files. 

But first, make sure that you are using project-level code style settings (Scheme: Project in Settings/Preferences -> Editor -> Code Style):
![image](https://user-images.githubusercontent.com/4499789/101461760-67ff1480-394c-11eb-90ac-d26a791234cf.png)

Contents of these files will be like this:
```
<component name="ProjectCodeStyleConfiguration">
  <state>
    <option name="USE_PER_PROJECT_SETTINGS" value="true" />
  </state>
</component>
```
```
<component name="ProjectCodeStyleConfiguration">
  <code_scheme name="Project" version="173">
    <codeStyleSettings language="Dart">
      <option name="RIGHT_MARGIN" value="120" />
    </codeStyleSettings>
  </code_scheme>
</component>
```

**Comment by anthonyorona** [comment]
Why is dart wrapped at 80 chars? It is not 1980 ;)

**Comment by om-ha** [comment]
`dart.lineLength` is super useful.

For VS Code, it can be enabled on a workspace/repo level and tracked by git.

Importance if this settings item: 
1. It affects dart auto-formatting, the entire team should use the same `dart.lineLength` or else every time a member auto-formats a class, it gets changed unnecessarily.
2. This is particularly annoying when you do renaming **without refactoring**. You expect text to be on the same line when you rename stuff, but no it's wrapped! This ends up in incorrect renaming results.

**Comment by rimedar** [comment]
> You're right, this is a Dart setting. For formatting, we use the SDK-supplied [dart_style](https://github.com/dart-lang/dart_style) library which wraps lines at 80 characters, but you can control this with the `"dart.lineLength"` setting.
> 
> Let me know if this doesn't work for you.

Not, it don´t work, ever wrap to 80.

**Comment by DanTup** [comment]
> Not, it don´t work, ever wrap to 80.

If it's not working for you, please _file a new issue_ and include a screenshot showing where you have updated the setting, and a log captured by:

- run the **Dart: Capture Analysis Server Logs** command
- format the document
- click **Cancel** on the logging notification to stop logging and open the log

Please do this in a new sample app, because the log will contain parts of your source code. Thanks!

**Comment by RobinBijo** [comment]
Hey, @DanTup I put the line length to 130 yet the issue ain't resolved. Could it be because of git? I have it installed
