### ISSUE TITLE
F5 in VSCode can't lunch app in iOS Emulator!

### ISSUE THREAD

**Issue by kondongx** [Dart-Code/Dart-Code#1718]
# F5 in VSCode can't lunch app in iOS Emulator

F5 in VSCode keep notifying "Running Xcode build...", but never finish. Here is the screen shot:

<img width="1391" alt="屏幕快照 2019-05-17 16 06 02" src="https://user-images.githubusercontent.com/28899471/57912858-ebb26580-78bd-11e9-90c7-a41afb8ffd87.png">

The weird thing is in debugger console, it says "Xcode build down.  14s". BTW, everything is ok when I use `flutter run` in the terminal to lunch the app.

I keep waiting for 10 minutes but the app is still blank in the Emulator. 

 I love the widget when press F5:

<img width="258" alt="屏幕快照 2019-05-17 16 14 41" src="https://user-images.githubusercontent.com/28899471/57913307-ebff3080-78be-11e9-9405-66ce10be989d.png">

Need help!

Other informations:

```bash
$ flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226,
    locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version
    28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[!] Android Studio (version 3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Ultimate Edition (version 2019.1.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.34.0)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

**Comment by kondongx** [comment]
That's also means I can't debug my app

**Comment by DanTup** [comment]
Can you capture some logs using the [**Dart: Capture Logs**](https://dartcode.org/docs/logging/#capture-logs-command) command? Tick the **Debuger** and **Flutter Run** Categories. Thanks!

**Comment by mradamclark** [comment]
I am having a similar problem, when trying to debug from vscode on a real device. 

This is the error that I get, then the debugging sessions dies, but the app is still running as a white screen.
Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:1033/wjjCSbtdZqg=/ws

My phone get the application installed, but doesn't fully launch. Only stays as a white screen, while the debugging sessions ends on VSCode. The app stays running on the phone, its also not able to launch successfully if i try to run the install app on the phone.

I have included a Dart: Capture Logs.
[DebugLog.txt](https://github.com/Dart-Code/Dart-Code/files/3193523/DebugLog.txt)

Thanks.

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-CA)
    • Flutter version 1.5.4-hotfix.2 at /Users/adamclark/Developement/flutter
    • Framework revision 7a4c33425d (3 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.34.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.0.2

[✓] Connected device (1 available)
    • Not Your Phone • 4b6c5499721127c9202dae014078acad18635da4 • ios • iOS 12.3

! Doctor found issues in 2 categories.
```

**Comment by kondongx** [comment]
> Can you capture some logs using the [**Dart: Capture Logs**](https://dartcode.org/docs/logging/#capture-logs-command) command? Tick the **Debuger** and **Flutter Run** Categories. Thanks!

[Dart-Code-Log.txt](https://github.com/Dart-Code/Dart-Code/files/3193620/Dart-Code-Log.txt)

**Comment by DanTup** [comment]
Seems to be hanging trying to connect to the device:

```
[11:36:02 GMT+0800 (CST)] [FlutterRun] [Info] <== [   +5 ms] Observatory URL on device: http://127.0.0.1:53718/mhYxwYwkhTw=/
[11:36:02 GMT+0800 (CST)] [FlutterRun] [Info] <== [   +5 ms] Connecting to service protocol: http://127.0.0.1:53718/mhYxwYwkhTw=/
Sat May 18 2019 [11:36:42 GMT+0800 (CST)] Log file ended
```

Can you see whether WiFi syncing is enabled in iTunes, and if so try disabling it (or just turning off WiFi) to see if that helps? (seems to have fixed this for other people, for ex. https://github.com/flutter/flutter/issues/27019).

**Comment by kondongx** [comment]
> Seems to be hanging trying to connect to the device:
> 
> ```
> [11:36:02 GMT+0800 (CST)] [FlutterRun] [Info] <== [   +5 ms] Observatory URL on device: http://127.0.0.1:53718/mhYxwYwkhTw=/
> [11:36:02 GMT+0800 (CST)] [FlutterRun] [Info] <== [   +5 ms] Connecting to service protocol: http://127.0.0.1:53718/mhYxwYwkhTw=/
> Sat May 18 2019 [11:36:42 GMT+0800 (CST)] Log file ended
> ```
> 
> Can you see whether WiFi syncing is enabled in iTunes, and if so try disabling it (or just turning off WiFi) to see if that helps? (seems to have fixed this for other people, for ex. [flutter/flutter#27019](https://github.com/flutter/flutter/issues/27019)).

I didn't do anything and it works today.

**Comment by kondongx** [comment]
## Problem still there
I just hit this problem again. Last time, I thought machine reboot solve the problem. Now I reboot my mac and problem still here.

## Things I tried

**Use F5 in VS Code**

* **real device**: I tried debug on my iPhone8 plus, not working.
* **simulator**: I tried iPhone8 plus, iPhone XR, Android pixel, not working.

**Use `flutter run` in terminal**

Work.

## About WiFi syncing is enabled in iTunes
It is disabled. I also tried turn off WiFi connection both on Mac and iPhone.

## Log file
[Dart-Code-Log-2019-06-06 18-36-24.txt](https://github.com/Dart-Code/Dart-Code/files/3388709/Dart-Code-Log-2019-06-06.18-36-24.txt)

## Flutter doctor

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132,
    locale zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version
    28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[!] Android Studio (version 3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.36.1)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

## VS Code plugins' version
Dart: 3.2.0
Flutter: 3.2.0

Want help, thanks!

**Comment by kondongx** [comment]
I just figure it out. The `http.proxy` lives in my VS Code settings. I delete it. Then it works.

Hope this will be helpful to other people.

**Comment by willardjansen** [comment]
flutter clean

**Comment by danilocubos** [comment]
Clear VS code cache:

Press F1 > type `Clear Editor History` > Enter.

This fixed the issue for me.
