### ISSUE TITLE
Errors after downgrading Flutter

### ISSUE THREAD

**Issue by nalnir** [Dart-Code/Dart-Code#1722]
I downgraded the flutter version from latest to stable 1.2.1 and got bunch of errors. The app runs just fine on both ios and android, but the highlights are just incredibly annoying. 
I restarted the vs code, uninstalled and installed the dart code extension again, but nothing helps. Any suggestions what can I do to fix this?
I don't want to upgrade the flutter version to latest again, cause that would just break unnecessarily break the app. 

<img width="1280" alt="Screen Shot 2019-05-18 at 12 30 40 PM" src="https://user-images.githubusercontent.com/28774583/57969777-92a00b80-7969-11e9-8709-7208a44ac745.png">

<img width="1280" alt="Screen Shot 2019-05-18 at 12 30 55 PM" src="https://user-images.githubusercontent.com/28774583/57969782-9af84680-7969-11e9-9053-8713848de18a.png">

<img width="1280" alt="Screen Shot 2019-05-18 at 12 31 17 PM" src="https://user-images.githubusercontent.com/28774583/57969813-a0ee2780-7969-11e9-84c8-dd4f15caa484.png">

**Comment by DanTup** [comment]
It seems like something may have gone wrong when you downgrade. I would try:

- Closing your IDEs
- Deleting your `.packages` and `pubspec.lock` files
- Deleting the `cache` folder from inside the Flutter SDK's `bin` folder
- Run `flutter doctor` and let it re-download everything
- Re-open your project in VS Code and click the popup that offers to fetch packages
- Restart VS Code

If you still have issues after, let me know.

FWIW though, I think you'd be better tracking down the issues using the latest stable one, as at some point you'll need to upgrade (for bug fixes or new features) and have to figure them out then. If you think the errors reported are a bug, please open an issue in flutter/flutter with some examples and we can figure out what's going on.

**Comment by nalnir** [comment]
I checked the latest stable. It's 1.5.4-hotfix.2. Upgraded it and now it's all good :)
