### ISSUE TITLE
Add completion for edit "old-style" multiline comments

### ISSUE THREAD

**Issue by Blimster** [Dart-Code/Dart-Code#173]
When pressing Enter in a multiline comment like this

```
/**
 * some comment
 */
```

a * should be inserted automatically in the new line.

**Comment by DanTup** [comment]
In 0.11 I've added support to handle this for triple-slash comments though I didn't do this one because I was under the impression this style was being phased out.

I don't think it'll be hard to add though, so I'll have a quick look before I build 0.11 and see if I can get it in.

**Comment by DanTup** [comment]
Sorted. Not only does it do what you asked, it'll also put the `*/` onto a newline if you press `<ENTER>` in the middle of `/** */` :)

(I just stole the TypeScript implementation :grin:)
