### ISSUE TITLE
Flutter UI Guides preview feedback

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#1731]
For info on the Flutter UI Guides preview, see the [v3.31 release notes](https://dartcode.org/releases/v3-1/#preview-flutter-ui-guidelines). This thread is for collecting feedback on the guides (including the `customTracking` setting).

**Comment by digitalhurricane-io** [comment]
I have both dart.previewFlutterUiGuides and dart.previewFlutterUiGuidesCustomTracking enabled.

I've restarted vscode.

When I write new code, the guidelines appear. 

But they don't appear on code that I've already written.

Is that expected behavior?

**Comment by DanTup** [comment]
@digitalhurricane-io it's not expected behaviour :( Do you have any syntax errors in the file/code that isn't working? Would you mind opening a new issue specifically for this, and include screenshots of the code that's not working? Thanks!

**Comment by digitalhurricane-io** [comment]
I'm nesting widgets inside a ternary operator on the offending code. Perhaps this is why?

**Comment by windwp** [comment]
UI guides do not work inside the builder.

**Comment by marcoms** [comment]
Guide formatting breaks when using tabs for indentation

**Comment by DanTup** [comment]
@marcoms good cath - I opened https://github.com/Dart-Code/Dart-Code/issues/1791 specifically for that and will fix for vNext.

**Comment by jckpn** [comment]
Only works in some files for me... not sure why or what I'm doing wrong.

Here it works great: 
![image](https://user-images.githubusercontent.com/14837124/60353363-cedf7680-99c1-11e9-809f-4901af297a99.png)


Here it doesn't seem to work (at least not how I would expect):

![image](https://user-images.githubusercontent.com/14837124/60353336-bcfdd380-99c1-11e9-8e71-d4c8f423a1f9.png)

(Both are files I wrote before enabling the UI guides)

This is such a great idea in theory though, will make writing code in Flutter so much nicer.

**Comment by DanTup** [comment]
@jckpn the second screenshot uses builders, which didn't support these. I believe that's been improved in a later SDK, but hasn't made the Flutter stable channel yet. Hopefully it'll just start working when it does :-)

**Comment by a-eid** [comment]
not sure why it looks like that for me..

<img width="748" alt="Screen Shot 2019-12-25 at 13 56 09" src="https://user-images.githubusercontent.com/19273413/71444956-506c5300-271e-11ea-8bda-576f1a58213f.png">

**Comment by a-eid** [comment]
could be the  custom line height I think..

**Comment by DanTup** [comment]
@a-eid what is your line-height set to?  Custom line heights will cause gaps (see https://github.com/Dart-Code/Dart-Code/issues/1902) but it shouldn't have such large spaces unless you've set your line height really high.

**Comment by emme1444** [comment]
Italic multiline comments causes the guidelines within the comment to also tilt. 
See screenshot:
![Screenshot 2020-02-08 at 15 59 42](https://user-images.githubusercontent.com/23585909/74087404-313a4280-4a8c-11ea-8048-5f7e2158eb79.png)

**Comment by DanTup** [comment]
@emme1444 looks like that's been filed at https://github.com/Dart-Code/Dart-Code/issues/2239 - thanks!

**Comment by DanTup** [comment]
Thanks for all the feedback. I don't think there's much more to collect from this issue so I'll close it. The UI guides feature remains behind a preview flag because it's method of rendering is not too reliable but there are currently no other available APIs.

If VS Code gets a better API for this in the future (https://github.com/microsoft/vscode/issues/73780), we can move them over and hopefully have something good enough to ship on-by-default.
