### ISSUE TITLE
Improve failure if sdkPath is not a string

### ISSUE THREAD

**Issue by shariarrazm** [Dart-Code/Dart-Code#1732]
I installed Dart, flutter and PATH but when i want to create new flutter project from command palette i have this error "command 'flutter.createProject' not found" Even if i open a ready project the syntax is not working

**Comment by DanTup** [comment]
@shariarrazm could you click Help -> Toggle Developer Tools and see if there are errors in the Console tab about failing to activate the extension?

If you open an existing project (for example `flutter_gallery` from the `flutter/examples` folder), do you see any errors for that too? Do you get a popup with a "View Logs" button on it?

**Comment by shariarrazm** [comment]
i have this two errors

Activating extension 'Dart-Code.dart-code' failed: p.startsWith is not a
function.
_logMessageInConsole @ /Applications/Visual Studio
Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3855

[Extension Host] Activating extension `Dart-Code.dart-code` failed:
p.startsWith
is not a function
t.log @ /Applications/Visual…rkbench.main.js:238

**Comment by DanTup** [comment]
@shariarrazm Do you have any `dart.` settings in your VS Code user settings? If so, could you post the, here?

**Comment by shariarrazm** [comment]
How can i find this?

**Comment by DanTup** [comment]
Press `Cmd`+`,` (cmd+comma) to open your VS Code settings. It's a JSON file. See if you have "dart.sdkPath" anywhere in there.

**Comment by shariarrazm** [comment]
{
    "dart.sdkPath": [
        "/Users/ShariarRazm1/Desktop/Flutter/flutter"
    ],
    "[dart]": {},
    "files.associations": {
        "*.dart": "dart"
    }
}

**Comment by DanTup** [comment]
@shariarrazm remove the `[square brackets]` from around `dart.sdkPath`, like this:

```js
"dart.sdkPath": "/Users/ShariarRazm1/Desktop/Flutter/flutter",
```

That value should be a `string` not a `string[]` array.

Let me know if that helps!

**Comment by DanTup** [comment]
Actually, that's probably not a valid path - you've put a Flutter SDK in `dart.sdkPath`. Change it to `flutter.sdkPath`:

```js
"flutter.sdkPath": "/Users/ShariarRazm1/Desktop/Flutter/flutter",
```

Note: If you have added Flutter's `bin` folder to your `PATH` env variable, you might not need that setting at all.

**Comment by shariarrazm** [comment]
i have this in my .bash_profile export 
PATH=/Users/ShariarRazm1/desktop/flutter/bin:$PATH

**Comment by DanTup** [comment]
In that case, you *might* not need to set `dart.flutterSdkPath`, but it depends whether the PATH in your bash profile applies to your desktop. The simplest way is just to probably add the setting - but if you ever move Flutter from your desktop, you'll need to update it.

The setting you want is:

```js
"dart.flutterSdkPath": "/Users/ShariarRazm1/Desktop/Flutter/flutter",
```

If you want to set the Dart SDK too, it should be:

```js
"dart.sdkPath": "/Users/ShariarRazm1/Desktop/Flutter/flutter/bin/cache/dart-sdk",
```

Let me know if these resolve your issue.

**Comment by shariarrazm** [comment]
still i have this problem 
![Screenshot 2019-05-21 at 17 01 41](https://user-images.githubusercontent.com/15120130/58107481-37c91700-7bea-11e9-8dec-7456cf2ec989.png)

**Comment by DanTup** [comment]
@shariarrazm can you click Help -> Toggle Dev Tools and check the console again, to see if there's a different error?

**Comment by shariarrazm** [comment]
![Screenshot 2019-05-21 at 17 42 15](https://user-images.githubusercontent.com/15120130/58110471-e0c64080-7bef-11e9-90db-f65620338f91.png)

**Comment by DanTup** [comment]
@shariarrazm that looks like the same error. Can you try restarting VS Code, and if you see the same issue, run the **Open Workspace Settings** command in VS Code and ensure that your current workspace doesn't also have a bad `dart.sdkPath` value set.

**Comment by shariarrazm** [comment]
Now its working! Thank you very much!

**Comment by DanTup** [comment]
Great! Do open issues if you have any other problems :-)

**Comment by DanTup** [comment]
I'm gonna reopen this to improve the failure since it seems like VS Code wasn't giving you a warning when you had an array in that setting.

**Comment by DanTup** [comment]
Seems like VS Code is validating this for me:

<img width="509" alt="Screenshot 2019-05-22 at 9 11 16 am" src="https://user-images.githubusercontent.com/1078012/58158095-a43b2900-7c71-11e9-9feb-8ff68eaa6836.png">

However in addition, `resolvePath` now has a check for strings so will treat non-strings as `undefined` in the next  version - which would avoid the original failure (instead, just notifying that it can't find the SDK). So nothing to do here now.

**Comment by chubutin** [comment]
> In that case, you _might_ not need to set `dart.flutterSdkPath`, but it depends whether the PATH in your bash profile applies to your desktop. The simplest way is just to probably add the setting - but if you ever move Flutter from your desktop, you'll need to update it.
> 
> The setting you want is:
> 
> ```js
> "dart.flutterSdkPath": "/Users/ShariarRazm1/Desktop/Flutter/flutter",
> ```
> 
> If you want to set the Dart SDK too, it should be:
> 
> ```js
> "dart.sdkPath": "/Users/ShariarRazm1/Desktop/Flutter/flutter/bin/cache/dart-sdk",
> ```
> 
> Let me know if these resolve your issue.

with both sdk configured and flutter in my path the issue was resolved. Thanks man
