### ISSUE TITLE
[Flutter][Web]Using F5 to compile fails with error "CreateProcessW fai led 2 Exited (1)"

### ISSUE THREAD

**Issue by NicTanghe** [Dart-Code/Dart-Code#1735]
When i use F5 to compile it runs to the entire process seemingly succesfully and then after serving the website it fails with the error CreateProcessW fai led 2 Exited (1)

Below is the console feedback.

```
Connecting to the build daemon...
Generating build script...
Generating build script completed, took 336ms
Starting daemon...
BuildDefinition: Initializing inputs
BuildDefinition: Reading cached asset graph...
BuildDefinition: Reading cached asset graph completed, took 309ms
BuildDefinition: Checking for updates since last build...
BuildDefinition: Checking for updates since last build completed, took 2.8s
BuildDefinition: Initializing inputs
BuildDefinition: Reading cached asset graph...
BuildDefinition: Reading cached asset graph completed, took 309ms
BuildDefinition: Checking for updates since last build...
BuildDefinition: Checking for updates since last build completed, took 2.8s
build_runner: Setting up file watchers...
build_runner: Setting up file watchers completed, took 3ms
Registering build targets...
Starting initial build...
Serving DevTools at http://127.0.0.1:6368
Starting resource servers...
Serving `web` on http://localhost:6361
CreateProcessW fai
led 2
Exited (1)
```

evrything works when i use.

`webdev serve -r`

in the console.

**Comment by DanTup** [comment]
@NicTanghe I guess you're on Windows? Do you have Google Chrome installed? If so, what is the location of `chrome.exe`?

**Comment by bayardkalyan** [comment]
@DanTup Yes, I have Google Chrome Dev installed. It is in my C drive.

**Comment by DanTup** [comment]
@bayardkalyan can you give the exact path? My guess is that webdev is failing to launch Chrome, and I think it has some assumptions about where it's installed.

**Comment by bayardkalyan** [comment]
@DanTup The path is C:\Program Files (x86)\Google\Chrome Dev\Application

**Comment by DanTup** [comment]
Thanks for confirming - that's definitely not a path that webdev is looking in:

https://github.com/dart-lang/webdev/blob/bd7b5f12907c4be9ab8fcca6c7ea4e86e0f686bc/webdev/lib/src/serve/chrome.dart#L18

Can you try setting the `CHROME_EXECUTABLE` environment variable to be the full path to `chrome.exe` (you may need to restart after adding it, I can't remember how good Windows is at updating env vars) and try again?

I think the handling of this needs improving in webdev, so I'll open an issue there too.

**Comment by DanTup** [comment]
I've opened https://github.com/dart-lang/webdev/issues/398 about improving the failure. Let me know if `CHROME_EXECUTABLE` helps in the meantime and I think we can close this one in favour of the webdev issue.

**Comment by NicTanghe** [comment]
Hello i'm using brave wich is chrome based when i create the variable in in user variables and point it to brave it doesn't function.

**Comment by DanTup** [comment]
@NicTanghe it's not clear what "doesn't function" means exactly, but the current preview of Flutter for web only supports Chrome for development (see https://github.com/flutter/flutter_web#important-notes).

**Comment by bayardkalyan** [comment]
@DanTup` webdev serve` is too working in my case but still not being able to debug flutter web in windows. Tried setting `CHROME_EXECUTABLE` and restarting but still facing the same problem. I think there is a bug in the framework itself.

**Comment by DanTup** [comment]
@bayardkalyan my understanding is that `webdev serve` doesn't launch the browser for you, but going via VS Code does? 

> Tried setting `CHROME_EXECUTABLE` and restarting but still facing the same problem

Did you restart after setting it? Environment variables don't update for existing processes.

In a Powershell window can you run:

```ps
$env:CHROME_EXECUTABLE
pub global run webdev daemon
```

and post the full output?

**Comment by NicTanghe** [comment]
For me at first it ran using webdev serve but not using vscode then after a while it stopped auto launching a brave tab.

Restarting did not help.
exit


```
>> pub global run webdev daemon
[{"event":"daemon.connected","params":{"version":"0.4.2","pid":13208}}]
[{"event":"daemon.log","params":{"log":"Connecting to the build daemon..."}}]
[{"event":"daemon.log","params":{"log":"Generating build script..."}}]
[{"event":"daemon.log","params":{"log":"Generating build script completed, took 298ms"}}]
[{"event":"daemon.log","params":{"log":""}}]
[{"event":"daemon.log","params":{"log":"Starting daemon..."}}]
[{"event":"daemon.log","params":{"log":"BuildDefinition: Initializing inputs"}}]
[{"event":"daemon.log","params":{"log":""}}]
[{"event":"daemon.log","params":{"log":"BuildDefinition: Reading cached asset graph..."}}]
[{"event":"daemon.log","params":{"log":""}}]
[{"event":"daemon.log","params":{"log":"BuildDefinition: Reading cached asset graph completed, took 260ms"}}]
[{"event":"daemon.log","params":{"log":""}}]
[{"event":"daemon.log","params":{"log":""}}]
[{"event":"daemon.log","params":{"log":"BuildDefinition: Checking for updates since last build..."}}]
[{"event":"daemon.log","params":{"log":""}}]
[{"event":"daemon.log","params":{"log":"BuildDefinition: Checking for updates since last build completed, took 800ms"}}]
[{"event":"daemon.log","params":{"log":""}}]
[{"event":"daemon.log","params":{"log":""}}]
[{"event":"daemon.log","params":{"log":"BuildDefinition: Initializing inputs"}}]
[{"event":"daemon.log","params":{"log":"BuildDefinition: Reading cached asset graph..."}}]
[{"event":"daemon.log","params":{"log":"BuildDefinition: Reading cached asset graph completed, took 260ms"}}]
[{"event":"daemon.log","params":{"log":""}}]
[{"event":"daemon.log","params":{"log":"BuildDefinition: Checking for updates since last build..."}}]
[{"event":"daemon.log","params":{"log":"BuildDefinition: Checking for updates since last build completed, took 800ms"}}]
[{"event":"daemon.log","params":{"log":""}}]
[{"event":"daemon.log","params":{"log":"build_runner: Setting up file watchers..."}}]
[{"event":"daemon.log","params":{"log":"build_runner: Setting up file watchers completed, took 2ms"}}]
[{"event":"daemon.log","params":{"log":""}}]
[{"event":"daemon.log","params":{"log":"Registering build targets..."}}]
[{"event":"daemon.log","params":{"log":"Starting initial build..."}}]
[{"event":"daemon.log","params":{"log":"Serving DevTools at http://127.0.0.1:11184\n"}}]
[{"event":"daemon.log","params":{"log":"Starting resource servers..."}}]
[{"event":"daemon.log","params":{"log":"Serving `web` on http://localhost:11177\n"}}]
CreateProcessW failed 2
```

Or should i stop replying as long as brave is not supported ?
(for now maybe you could prevent breaking if the launching of the browser doesn't work)

**Comment by DanTup** [comment]
I don't think `webdev serve` launches the browser, which is why that doesn't fail. `webdev daemon` is essentially what VS Code is running, which will launch the browser at the end (and output will be JSON, since it's designed for tools to consume).

I don't know enough about Brave to know if you could get it to work. Chrome is spawned with special flags to allow the webdev daemon to control it better (for things like debugging functionality - which isn't complete yet). If Brave is mostly compatible with these flags, maybe you could get it to work, but I'm not sure any effort is going into supporting it right now (nor am I sure what the long-term goal is with browser support for the development path).

**Comment by NicTanghe** [comment]
i'l just use serve till later version arrives
