### ISSUE TITLE
Disable functionality that will only work on a local machine if running remotely

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#1738]
https://github.com/microsoft/vscode/issues/74188

Anything that doesn't make sense in a remote context should be disabled:

- [x] launching emulators
- [x] creating emulators
- [x] opening Xcode/Android Studio
- [ ] launching Flutter mobile apps (this is useable for things like ADB over TCP?)
- [ ] device manager (this is useable for things like ADB over TCP?)
- [x] launching DevTools via service (we should fall back to launching ourselves for remote scenarios)
- [x] launching Flutter Web apps

**Comment by audkar** [comment]
Hey @DanTup :wave: I have question to you on this topic. (probably you are the only person in the world who has most knowledge on this symbiosis between vscode, vscode-remote over ssh, flutter and mobile frameworks) :)))

At which layer limitations exists for this "Anything that doesn't make sense in a remote context should be disabled"? I have huge hopes for developing on remote mac when/if it is supported from vscode side. I imaged that I could run automation tests while developing. Or maybe have rdp/vnc connection for simulator, but develop on local vscode. In these cases managing simulators (start/list/stop) would be quite useful IMO. Do you know any insight why this might not work?

**Comment by DanTup** [comment]
Right now it's not possible to use VS Code remoting to a Mac over SSH (see https://github.com/microsoft/vscode-remote-release/issues/24 - and please put a 👍  on it!). I don't know the reason for this limitation so it's hard to guess whether it may be lifted in the future or not.

If it was supported then I would expect (though I can't be certain without testing!) that it would work as you describe - though as you say, you'd need VNC or something to see the simulator - or to have a physical device connected and within reach. If you're mostly interested in running tests (and don't need to see the screen) then I guess that should be easier.

Hope this helps!
