### ISSUE TITLE
Provide parameter info for functions and methods.

### ISSUE THREAD

**Issue by Blimster** [Dart-Code/Dart-Code#174]
When I want to call a function and I don't know the exact signature, it is helpful to get info about its parameters.

Here a description of this feature in IntelliJ: https://www.jetbrains.com/help/idea/2016.2/viewing-method-parameter-information.html

**Comment by DanTup** [comment]
I think this is covered by a few existing cases:

- #152 - auto-complete parameters
- #163 - add placeholders for named params
- #15 - add signature completion

The first two are done and will be in 0.11 (which I'm hoping to release shortly) and the last one requires some work from the Dart Team so might be a little while longer (though in the background I'm trying to find a way to do it without needing their implementation in case it's not done soon).

Feel free to re-open with comments if you don't think these cover it.

And thanks for the feedback!
