### ISSUE TITLE
Unable to install 'Dart-Code.flutter'

### ISSUE THREAD

**Issue by leonardo-sj** [Dart-Code/Dart-Code#1744]
I was unable to install the plug-in in VS Code 1.21.0 in Mac OS 10.14.3.
The error message below was shown.
"Unable to install 'Dart-Code.flutter'; there is no available version compatible with VS Code '1.21.0'."

In Windows OS, everything has gone fine.

**Comment by DanTup** [comment]
> there is no available version compatible with VS Code '1.21.0'."

The message is correct. VS Code 1.21 is over a year old and is not supported by any recent versions of the Dart extension or any version of the Flutter extension (1.21 was already old when the Flutter extension was first created). You should upgrade to the latest VS Code (currently 1.34) and try again.

Let me know if you have any problems when on the current version!
