### ISSUE TITLE
I hate analysis server

### ISSUE THREAD

**Issue by dudochkin-victor** [Dart-Code/Dart-Code#1746]
I have very important question.
How to disable static analysis at all?
Analysis server just will kill my hardware. It takes so much time and uses my hard drive as a slave owner. I do not need this "Analysis".
PLEASE HEEEEELP

**Comment by DanTup** [comment]
You cannot disable the analysis server, it powers most of the functionality of the extension. If you really want to disable the analysis server you would need to disable the extension.

It would be much better to open issues for the performance issues you see though, so they can be investigated and hopefully improved/resolved.
