### ISSUE TITLE
Intellisense allows multiple imports of same package

### ISSUE THREAD

**Issue by Zaph-x** [Dart-Code/Dart-Code#1759]
**The issue is:**
When writing properties for a class, the Visual Studio extension is able to import the same package multiple times. Furthermore the extension will suggest what is actually on the line.

![Error](https://x0.at/8dK.png)

**Steps to reproduce:**
1. Create a class.
2. Write each property, but instead of ending with a `;` end with a `,`.
   * I did String then int.
3. Change the `,` to `;`.
4. Intellisense will now suggest importing `dart:core` as well as suggest to change `int` to `int`

**What was expected to happen:**
The extension should not suggest to change the type from `int` to `int`. It should only suggest that `dart:core` is imported once.

**Extension version:**
Dart extension: 3.0.2
Flutter extension: 3.0.2

**VSCode version:**
Version: 1.34.0 (user setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by DanTup** [comment]
I'm unable to to repro this. Can you still repro it?

Would you mind capturing a log? You can run the **Dart: Capture Logs** command, the untick everything except Analysis Server (keep that ticked). Then reproduce (including the initial typing and causing the error), then click **Stop Logging** on the notification (which may have collapsed into the bell icon), and provide the log.

Thanks!

**Comment by DanTup** [comment]
@Zaph-x can you still reproduce this? If so, could you capture a log (see above)? Thanks!

**Comment by Zaph-x** [comment]
Sorry for not responding earlier. I've been caught up in work. I'll give it a check tomorrow first thing

**Comment by Zaph-x** [comment]
As of version 3.1.0 I am no longer able to reproduce this issue
