### ISSUE TITLE
Dart extension is full of lag and sudden termination on latest build

### ISSUE THREAD

**Issue by simjounhax** [Dart-Code/Dart-Code#1762]
Issue Type: <b>Bug</b>

As mentioned above, in the latest build, VSCODE stops abruptly or stops responding for a while, and then terminated. it happens per 10 minutes, only when I'm working on the dart project.

Dart VM version: 2.3.1 (Tue May 21 19:28:38 2019 +0200) on "windows_x64"
Extension version: 3.0.2
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (19.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by DanTup** [comment]
@simjounhax When you say not responding, do you mean the VS Code UI locks up, or just the Dart functionality doesn't work?

Does it happen right away, or only after you've had the editor open a for a while? I found [a memory leak in VS Code](https://github.com/microsoft/vscode/issues/74446) yesterday that was causing poor performance (and eventually an extension host crash) that could explain it if the editor was open for a while. The fix is in the VS Code Insiders build and should ship in the next VS Code update.

**Comment by simjounhax** [comment]
I apologize for the delayed reply.
'Not responding' is the second case, that Dart functionality doesn't work, and Intellisense code completion function keeps waiting for a while, then terminated by displaying a message, 'extension host is terminated(I don't know how it displayed in English)'.

it happens after the VScode has opened and used for some time.
I'll try VScode Insider build and if the same issue happens again, then I'll report.

Thanks for helping.

**Comment by DanTup** [comment]
> extension host is terminated

This does sound like the memory leak, so hopefully you'll find it's fixed in Insiders (I believe that version of VS Code is planned for release on 6th June).

If you still see any issues in Insiders (or in stable once VS Code 1.35 releases), please do let me know. Thanks!
