### ISSUE TITLE
Update import statements when file is renamed

### ISSUE THREAD

**Issue by YourAppNerds-Admin** [Dart-Code/Dart-Code#1764]
It would be nice if when a file's name gets changed, any import statements referring to that file get automatically updated.

**Comment by DanTup** [comment]
Thanks for the suggestion! There's actually an open issue (#548) and PR (#1740 - which needs a few tweaks) but we need to wait for VS Code to land https://github.com/microsoft/vscode/issues/43768 to be able to ship it. Once VS Code ships the API, I hope to include this in the following release :-)
