### ISSUE TITLE
Debugger appears as "runtime: node" in extension contribution section

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#177]
![Dart debugger runtime](https://cloud.githubusercontent.com/assets/1078012/18362896/a9b5cab4-75ff-11e6-9985-0d51fa39309f.png)

**Comment by DanTup** [comment]
https://github.com/Microsoft/vscode/issues/11896

**Comment by devoncarew** [comment]
fixed:

<img width="667" alt="screen shot 2016-10-10 at 7 41 31 pm" src="https://cloud.githubusercontent.com/assets/1269969/19257082/9aef556e-8f21-11e6-8266-5c5af65488ff.png">

**Comment by DanTup** [comment]
👍
