### ISSUE TITLE
refactor.extractClass does not work or ever show up

### ISSUE THREAD

**Issue by craig006** [Dart-Code/Dart-Code#1770]
I see that extracting a class to a new file is supported in the docs here: https://dartcode.org/docs/refactorings-and-code-fixes/

This does not show up at all for me. I have tried different keybindings as well as different selections in the source file but nothing seems to bring this refactoring up as an option.

**Comment by DanTup** [comment]
Unfortunately we don't currently have this function. It looks like when I compiled the list of IDs from the server, I didn't check that they were all implemented. The one you mention was subsequently removed in a cleanup:

https://github.com/dart-lang/sdk/commit/9a7168a2bf80348be2f021f7228427fa7d6de2a6#diff-5448f1817720cc73f9221560f3e0f2ee

It's not very common to have a file-per-class in Dart, which might be why this wasn't implemented (I thought the Dart style guide specifically called it out, though I couldn't find it in a quick search). Anyway, I'll remove it from the page - sorry for the confusion!
