### ISSUE TITLE
No UI guides on some code

### ISSUE THREAD

**Issue by digitalhurricane-io** [Dart-Code/Dart-Code#1771]
I have both dart.previewFlutterUiGuides and dart.previewFlutterUiGuidesCustomTracking enabled.

I've restarted vscode.

When I write new code, the guidelines appear.

They appear on some code I've already written, but some other code they do not appear.

Perhaps it's not even supposed to have guidelines on this code. I'm not sure. But it seems to me like it should.

Here's a screenshot of the code without UI guidelines.

![noUiGuides](https://user-images.githubusercontent.com/17537278/58751847-b5e6b280-8461-11e9-8b71-2ca9f29e504b.png)

**Comment by DanTup** [comment]
It looks like this has been fixed in the server so will be supported in a future release:

https://github.com/flutter/flutter-intellij/issues/3446

:-)
