### ISSUE TITLE
Icons Preview no longer working.

### ISSUE THREAD

**Issue by CoonHouse** [Dart-Code/Dart-Code#1772]
Hi,
I no longer see the Icons Preview when scrolling trough the icons. Maybe it's related to #1204 but it worked for me until lately. I think it broke after update 3.1.

![Annotation 2019-06-01 204200](https://user-images.githubusercontent.com/20111438/58752384-54006a00-84ae-11e9-8624-bf6f1ffe650f.png)

Hovering over an selected icon still works.

![image](https://user-images.githubusercontent.com/20111438/58752402-9033ca80-84ae-11e9-90f9-4256c2678d40.png)

Regards,

Wilco

**Comment by DanTup** [comment]
It looks like this is just the "collapsed" view of the completion list. If you press `Ctrl`+`Space` to open completion, then press it again, it'll toggle between the view above, and one with the help expanded to the right:

<img width="635" alt="Screenshot 2019-06-01 at 20 01 38" src="https://user-images.githubusercontent.com/1078012/58752529-21ec0980-84a8-11e9-984e-af4f8c8b23b2.png">
<img width="631" alt="Screenshot 2019-06-01 at 20 01 42" src="https://user-images.githubusercontent.com/1078012/58752530-21ec0980-84a8-11e9-8ecf-7f2d28d20ecb.png">

Let me know if this doesn't seem to be the case!

**Comment by CoonHouse** [comment]
@DanTup, 

Yes! that is the case, I didn't know I could "toggle" this behavior.
Thanks for helping out!

**Comment by DanTup** [comment]
Great, thanks for confirming! This is VS Code functionality, so not something we can tweak in any way unfortunately!
