### ISSUE TITLE
Support debugging for Flutter web projects

### ISSUE THREAD

**Issue by pouledodue** [Dart-Code/Dart-Code#1773]
```
Breakpoints and stepping are not currently supported in VS Code for Flutter web projects, please use your browser tools if you need to break or step through code
```
2 questions: 
- ETA :-) ?
- what are those `browser tools`?

**Comment by DanTup** [comment]
> ETA :-) ?

This requires support from the `webdev` package before we can implement it. There are some open issues in the issue tracker like https://github.com/dart-lang/webdev/issues/352 that you can subscribe to. Once it's supported there, there will be a little work here to ensure it works, but I don't think much.

> what are those browser tools?

Whoops, that message isn't worded very well. It should say "browser developer tools". For example the [dev tools in Chrome](https://developers.google.com/web/tools/chrome-devtools/) (Menu -> `More Tools` -> `Developer Tools`).

I'll keep this issue open for tracking supporting debugging once it's unblocked.

**Comment by pouledodue** [comment]
thanks!!

**Comment by annaacc** [comment]
Hello, 
I see all tasks from dart-lang/webdev#352 has been closed. Do we have ETA now ?

**Comment by DanTup** [comment]
There has been some progress, but it's still not fully working (for ex I found https://github.com/dart-lang/webdev/issues/629 while testing debugging this week).

I can't say when it'll be done, but it is being worked on :-)

**Comment by DanTup** [comment]
The tweaks needed in the VS Code extension are done (for the next release). The functionality is still very dependent on the Flutter/webdev versions (Flutter's web support [is still in preview](https://flutter.dev/web)). As Flutter/webdev support additional functionality, it should just work without more changes here.

There will be some info in the release notes about what does/doesn't work when the release goes out.
