### ISSUE TITLE
how to get an object memory address

### ISSUE THREAD

**Issue by chenfanfang** [Dart-Code/Dart-Code#1794]
how to get an object memory address

**Comment by DanTup** [comment]
Do you mean in programatically in Dart code or from VS Code? I'm not sure if either are possible - what is it you're trying to do?

**Comment by DanTup** [comment]
I can't do anything here without more info. I'm happy to re-open this if you can provide some :-)

**Comment by Stitch-Taotao** [comment]
In C a variable like `int i =0`; we can get i's address from `&i`;
How Can I get a var's address in Dart?

**Comment by DanTup** [comment]
Please see https://stackoverflow.com/a/59726800.
