### ISSUE TITLE
Build takes forever

### ISSUE THREAD

**Issue by duzenko** [Dart-Code/Dart-Code#1796]
Every so often (too often I'd say) build takes forever to complete in my MacOS/iOS dev environment.
I can Ctrl+C out of it only to bump into it a few minutes later.

![image](https://user-images.githubusercontent.com/1481807/59427851-4d45f100-8de4-11e9-8a27-57293bef7e75.png)

**Comment by DanTup** [comment]
The VS Code plugin isn't really involved here, this is just running standard Flutter in the terminal, so this is something that would need looking at in Flutter.

Could you gather verbose logs using `-v` and attach them to the issue (I'll move this to flutter/flutter, so attach there).

/move flutter/flutter

**Comment by duzenko** [comment]
> 
> 
> The VS Code plugin isn't really involved here, this is just running standard Flutter in the terminal, so this is something that would need looking at in Flutter.
> 
> Could you gather verbose logs using `-v` and attach them to the issue (I'll move this to flutter/flutter, so attach there).
> 
> /move flutter/flutter

Thanks, will attach that next time it plays up
