### ISSUE TITLE
Dart Analyzer terminating on incorrect syntax

### ISSUE THREAD

**Issue by dawidjk** [Dart-Code/Dart-Code#1797]
Hi,

The Dart Analyzer terminates repeatedly when I write 
`get favorites: () => _favorites;`
favorites being a map.

I know it's incorrect syntax, but it still strikes me as odd. Here is the error log that occurs: https://pastebin.com/BUsCmKL3

I hope this helps!

**Comment by DanTup** [comment]
Thanks for the report! I believe this is the same as https://github.com/dart-lang/sdk/issues/36961 which has been fixed, but might not be in the version you have yet.

If you're using Flutter, you could try switching to a more recent branch (for ex Beta or Dev) to confirm it's fixed, or for Dart then it might be in the latest stable version (if not, you could also try the Dev version).

If you do still have issues in more recent code, it's worth pinging on the issue linked above.
