### ISSUE TITLE
Expose analyser to other extensions

### ISSUE THREAD

**Issue by szotp** [Dart-Code/Dart-Code#1799]
I want to extend another VSCode extension with functionality to localize string literal under cursor (convert it from `'foo'` to`I18n.of(context).foo`) . For this I need to determine range of the string literal in the text document, and ideally, string interpolation values. 

Would it be possible to expose Analyzer in DartExtensionApi? Then I could call editGetAssists to get needed data.

**Comment by DanTup** [comment]
`DartExtensionApi` is designed really for the Flutter extension - we don't really provide a public API so it's not guaranteed to keep working (for example if we switch to LSP, the analyzer interface will go entirely).

What data is it you're trying to get from getAssists? Maybe there's another way you could get it (eg. by calling VS Code's commands (for example `vscode.executeCodeActionProvider`)? (That said, again, this is not a published API and the results may change at any time).

Would your feature make more sense inside the analysis server? That way other editors (and LSP) could benefit from it too, and there's less chance of it breaking with other internal changes.

**Comment by szotp** [comment]
I think `executeCodeActionProvider` will do the job, thanks.

I'm adding this functionality to https://github.com/esskar/vscode-flutter-i18n-json plugin, so extending the analysis server would not be very practical. 

To get the range of string I'm going to run `executeCodeActionProvider` and look for "convert to multiline string". I know that it's lame but seems way easier than alternatives.

**Comment by DanTup** [comment]
Ah, got it. Using `executeCodeActionProvider` should be *more* stable, because it should work if we switch to LSP too. It's not *guaranteed* not to break (since the fixes that come back aren't designed as an API), but hopefully will be good for what you need.
