### ISSUE TITLE
Wifi or Wireless Debugging

### ISSUE THREAD

**Issue by jazzbpn** [Dart-Code/Dart-Code#1806]
Issue Type: <b>Feature Request</b>

As a full stack mobile app developer the debugging comes in every steps. In android studio there is a feature for WIFI-DEFUGGING or Wireless-Debugging but in vs-code I didn't find any thing like that. This is the most useful features the mobile developer needs.

Extension version: 3.1.0
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.6.0

**Comment by DanTup** [comment]
Can you clarify exactly what you'd like to see? You can do Android debugging over WiFi by:

- connecting your device with USB
- run `adb tcpip` (this tells the phone to listen on a port)
- disconnect the phone
- run `adb connect <phone-ip>:<port>`

This will cause the ADB server to connect over TCP/IP, and it'll show up in VS Code the same as if connected via USB. I don't know if this differs from Android Studio. On some devices, apparently there's an "ADB over network" setting that allows you to skip the top 3 steps and just enabled it on the phone (I don't know what the requirements/phones are for that though).

For iPhone I'm not so sure - I think Flutter currently has some issues debugging iOS over WiFi.

Let me know if this isn't what you're asking for.

**Comment by DanTup** [comment]
I can't do anything here without more info. I'm happy to re-open this if you can provide some :-)
