### ISSUE TITLE
Provide setting to disable adding of placeholders for method/constructor completion.

### ISSUE THREAD

**Issue by battousai999** [Dart-Code/Dart-Code#181]
Version 0.11 added:

- Completion for methods/constructors now adds placeholders for mandatory arguments
- Completion for named arguments now adds a placeholder for the value

Consider adding a setting to allow the adding of placeholders (during method/constructor completion) to be disabled.

**Comment by DanTup** [comment]
I'm curious; why would you like this disabled? If there's something bad about how it works, I wonder if it could be improved instead?

**Comment by battousai999** [comment]
Well, I wouldn't say that there's anything bad about how it works.  Personally, I'm just used to quickly typing out some familiar method calls (where the placeholders jolt me out of my reflex memory).  

I'm sure I could get used to tabbing through the placeholders instead of typing out commas (and may even learn to like it better).  I just routinely need to jump between several other code editors where method completion placeholders aren't supported or where I don't have them enabled, and I would disable them in vscode to keep one more thing uniform between the different editors I have to use.

**Comment by DanTup** [comment]
Understood; thanks for the info! Will add an option for the next release :-)

I actually implemented this mainly because of lack of signature help (this requires some work in the Dart analysis server) so it was hard (for a Dart noob like me) to know what to pass. Once that's done, I think I might prefer this off too!

**Comment by DanTup** [comment]
@battousai999 Sorry for the delay; I've had much less time to work on Dart-Code this week than I hoped.

I've just pushed out a small update with this option included. Press `Ctrl`+`Shift`+`X` in Code to get to the extensions list to update. There's not much in the update, but full notes are [here](https://github.com/Dart-Code/Dart-Code/releases/tag/v0.11.1).
