### ISSUE TITLE
Permission denied on installation

### ISSUE THREAD

**Issue by KevinBurton** [Dart-Code/Dart-Code#1811]
I type

brew install dart

on my Mac and I get

Error: Permission denied @ unlink_internal - /usr/local/lib/node_modules/@angular/cli/node_modules/.bin/in-install

**Comment by DanTup** [comment]
This repository is for the VS Code extension, for issues with Dart via brew you should raise an issue here:

https://github.com/dart-lang/homebrew-dart

Thanks!
