### ISSUE TITLE
Support: code autosuggestion

### ISSUE THREAD

**Issue by NarHakobyan** [Dart-Code/Dart-Code#1816]
It's very hard to guess all class names, I don't know what it is actually suggesting me, is there any way for better autocomplete?

![image](https://user-images.githubusercontent.com/1781506/59980209-96c3e680-9603-11e9-916f-aa5791f275c7.png)

**Comment by DanTup** [comment]
When using newest versions of the extension with a recent Dart/Flutter SDK (this might not include Flutter stable yet) completion will show unimported symbols and automatically import them when you select them:

https://dartcode.org/releases/v2-26/#auto-importing-from-code-completion
