### ISSUE TITLE
Update references when moving files.

### ISSUE THREAD

**Issue by JSANL** [Dart-Code/Dart-Code#1818]
Sorry for this dumb question, but should file paths after the `import` statement be updated if I move a referenced file? I'm not sure if this is of course implemented and just a bug on my site or if this not in the vscode plugin (maybe because of vscode restrictions).

**Comment by DanTup** [comment]
There's work in progress for this:

- https://github.com/Dart-Code/Dart-Code/issues/548
- https://github.com/Dart-Code/Dart-Code/pull/1740

However it's currently blocked on VS Code finalising an API (https://github.com/microsoft/vscode/issues/43768). It looks like that might happen for the July release (which is not the one in a fortnights time, but a month after that).

Once the API is finalised, I'll finish off the work for it and merge it for the next release.
