### ISSUE TITLE
"Extension causes high cpu load" warning at startup for slow filesystems and large folders

### ISSUE THREAD

**Issue by jordanlesson** [Dart-Code/Dart-Code#1819]
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `3.1.0`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.35.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/jordanlesson/Dart-Code.dart-code-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by DanTup** [comment]
> ⚠️ Make sure to attach this file from your home-directory:
> ⚠️/Users/jordanlesson/Dart-Code.dart-code-unresponsive.cpuprofile.txt

Thanks for the report, but you need to attach this file for this to be investigated.

If you saw the issue at startup, I suspect it's https://github.com/Dart-Code/Dart-Code/issues/1628 which is fixed for the next version (which you can try out a beta release of from https://github.com/Dart-Code/Dart-Code/releases).

**Comment by Ero-Raghav** [comment]
Same Issue. [Dart-Code.dart-code-unresponsive.cpuprofile.txt](https://github.com/Dart-Code/Dart-Code/files/3341353/Dart-Code.dart-code-unresponsive.cpuprofile.txt)

**Comment by DanTup** [comment]
@Ero-Raghav how many folders are in the top 3 levels of your project? And how fast is your machine/disk?

Your profile shows it sometimes taking 100ms to check a folder on disk, and we do this quite a lot while scanning looking for Dart/Flutter projects. It quickly adds up to 3 seconds, which causes VS Code to show this message (which is slightly misleading - it's not high CPU, it's time spent blocking the thread on I/O).

**Comment by DanTup** [comment]
I did some testing on a folder that contains 1088 projects in the top 3 levels, but my times are so fast it's hard to optimise. I tried several other options (including making the search parallel/async and using the `glob` package) but they were all much slower.

I'll investigate removing some `exists` checks which did have an improvement, but I'll need more info about your setup to do much more (things that are likely to be a factor are the number files/folders in the top 3 levels of the folder you opened in VS Code, the speed of your filesystem, and whether the filesystem may have been under load while this was happening).

<img width="319" alt="Screenshot 2019-07-09 at 11 51 51 am" src="https://user-images.githubusercontent.com/1078012/60882575-1b3b7980-a240-11e9-9987-87aff9e6d246.png">

**Comment by Ero-Raghav** [comment]
@DanTup 

It may be possible that it's because of slow HDD, because i never got this problem on my other system which have relatively faster HDD.

**Comment by DanTup** [comment]
What sort of disk is in the one this occurred on? Is the machine generally really slow to use? I'd like to support as many machines as possible, but the numbers in that trace seem particularly slow (in my test above I scanned thousands of folders to find 1088 projects in 88ms, but your trace shows individual file-exists checks taking over 100ms).

**Comment by Ero-Raghav** [comment]
its ATA Hitachi HTS72503 320GB HDD,  and Yes its Generally slow to use because of CPU bottleneck.

**Comment by DanTup** [comment]
And how big is the folder you're opening? (how many folders at the top, 2nd, 3rd levels?).

**Comment by Ero-Raghav** [comment]
around 1.3 GB and there are 16 folder at top level and level 2 and 3 have variable number of folders ranging from 4 to 40

**Comment by DanTup** [comment]
Ok, it does at least seem like it may have had a lot of folders to scan. I'd prefer not to make this code async just to avoid this warning (since it gets slower for everyone) if it's only on slow machines and large folders. I think either you could ignore the message (it's not causing any harm - and despite the text, it's not using high CPU) or try to open smaller portions of your tree.

I will try to eliminate some of the redundant exists checks though, that should help a little.

**Comment by DanTup** [comment]
I managed to shave around a 3rd of the time off (on my machine) by using `withFileTypes` to avoid the extra exists+stat checks:

<img width="252" alt="Screenshot 2019-07-10 at 11 53 25 am" src="https://user-images.githubusercontent.com/1078012/60963767-9c127800-a309-11e9-9755-90272b3053ed.png">

This should improve things but if you (or anyone else) seems to hit this on reasonable disks and/or with fairly small folders, please do shout!

**Comment by Ero-Raghav** [comment]
@DanTup Thank You
