### ISSUE TITLE
Deleted/renamed tests are not updated in "Test" section  after executing Dart: Run all tests

### ISSUE THREAD

**Issue by audkar** [Dart-Code/Dart-Code#1823]
Very similar issue to this one https://github.com/Dart-Code/Dart-Code/issues/1305

However as per your comment https://github.com/Dart-Code/Dart-Code/issues/1305#issuecomment-438758943:

> This is unfortunately expected. At least, until you next run the whole my_drawer_test.dart file (or all test suites). Does it disappear when you do that?

Tests gets updated only if executing particular tests in file. However this doesn't work when running `Dart: Run all tests`

plugin version `3.1.0`

**Comment by DanTup** [comment]
Good spot, thanks!
