### ISSUE TITLE
VS Code crashed if error on iPhone

### ISSUE THREAD

**Issue by YAPPDEF** [Dart-Code/Dart-Code#1833]
When I'm debugging my Flutter app on my iPhone via VS Code and got an error (red screen), VS Code freezes and I cannot do anything in VS Code anymore (cannot stop debugging or reload, ..).
The only way is then to close VS Code and start the app again, but this is taking quite long..
I also have to kill the processes `lldb` and `idevicesyslog`

macOS Mojave `v10.14.5`

Flutter doctor:
```
project: flutter doctor -v
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale de-CH)
    • Flutter version 1.5.4-hotfix.2 at /Users/user/Development/Tools/flutter
    • Framework revision 7a4c33425d (10 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/user/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/user/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.36.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (1 available)
    • iPhone • 00008020-000A615C11E2002E • ios • iOS 12.3.1

• No issues found!
```

**Comment by DanTup** [comment]
> VS Code freezes and I cannot do anything in VS Code anymore (cannot stop debugging or reload, ..).

Can you clarify what you see here - when you say you can't do anything anymore, can you interact with the editor? What happens when you click the Stop button on the debug toolbar? Does it stop if you click it twice?

Could you try capturing a log:

- run the **Dart: Capture Logs** command from the VS Code command palette, ticking only the **Flutter Run** and **Debugger** categories
- run your app and reproduce the issue
- click **Stop Logging** in the notification (which may have collapsed into the bell icon)
- paste the log into a [gist](https://gist.github.com/) and then paste the link here

Thanks!

**Comment by DanTup** [comment]
I can't do anything here without more info. I'm happy to re-open this if you can provide some :-)
