### ISSUE TITLE
Duplicate enumeration values in overflow autocomplete

### ISSUE THREAD

**Issue by timsneath** [Dart-Code/Dart-Code#1835]
More clips and fades in this screenshot than at a men's hair salon :)

![image](https://user-images.githubusercontent.com/2319867/60743526-e7eaa900-9f26-11e9-938d-37a92fce7623.png)

Running Dart and Flutter 3.2.0 plug-ins on VSCode 1.36.0. `flutter doctor` reports:
```
[√] Flutter (Channel master, v1.8.1-pre.22, on Microsoft Windows [Version 10.0.18362.207], locale en-US)
    • Flutter version 1.8.1-pre.22 at C:\git\flutter
    • Framework revision 93edc014ae (26 hours ago), 2019-07-04 11:26:19 -0700               
    • Engine revision 3c51a7bfff                                                                                     
    • Dart version 2.5.0 (build 2.5.0-dev.0.0 b5aeaa6796)
```

**Comment by DanTup** [comment]
Do you already have an import that includes them? If not, this may be by design - if `TextOverflow` is re-exported by `material.dart`, `widgets.dart`, `cupertino.dart` it will appear three times - one as an auto-import for each (if you move your selection down over them, it should show). Once you import one of those files, the others should then no longer show in the completion (this is a [recent change in v3.2](https://dartcode.org/releases/v3-2/#code-completion-improvements)).

If you still see dupes once you've imported one, that's definitely a bug.

**Comment by timsneath** [comment]
I import just `material.dart`, not `widgets.dart` or `cupertino.dart`. 
![image](https://user-images.githubusercontent.com/2319867/60745606-086b3100-9f30-11e9-8d49-c7d5628556aa.png)

The first four entries are _not_ auto-imported:
![image](https://user-images.githubusercontent.com/2319867/60745572-d6f26580-9f2f-11e9-949b-3667873250bc.png)

but the remainder are auto-imported by `rendering.dart`, `cupertino.dart`, and `widgets.dart`:
![image](https://user-images.githubusercontent.com/2319867/60745594-f4273400-9f2f-11e9-930a-3883044ad4b9.png)

**Comment by timsneath** [comment]
Current file is here: for reference: https://github.com/timsneath/cambridge/commit/6fb6af34da9dbbd52a5694e41b6173a0730c33ff

(and please don't look at the code too much -- it's embarrassing 😃)

**Comment by DanTup** [comment]
Ah yes, I overlooked "values" in the title - the duplicate enum definition (`TextOverflow`) is being removed, but its values are not.

@scheglov my guess is these aren't in `existingImports`. Is that a bug, or should we be splitting on the `.` and only checking for the first segment in `existingImports`?

**Comment by DanTup** [comment]
I've put a fix in here since even if it's changed in the server it'll take a while to get out.

I'll also make an equiv fix in LSP shortly.

**Comment by DanTup** [comment]
LSP didn't have this issue because its implementation wasn't complete (enum values didn't appear at all). That's fixed, and includes code to avoid hitting this.

(@lambdabaa FYI - not sure whether IntelliJ may need an equiv change - I think it'd affect named constructors as well as enums)
