### ISSUE TITLE
No devices found with name or id matching 

### ISSUE THREAD

**Issue by kevinmustaqim** [Dart-Code/Dart-Code#1836]
C:\Users\nurulhuda>adb devices
List of devices attached
98efd58e        device

C:\Users\nurulhuda>flutter devices
No devices detected.

Run 'flutter emulators' to list and start any available device emulators.

Or, if you expected your device to be detected, please run "flutter doctor" to
diagnose potential issues, or visit https://flutter.dev/setup/ for
troubleshooting tips.

C:\Users\nurulhuda>

No devices found with name or id matching '98efd58e'
Exited (1)

**Comment by DanTup** [comment]
The commands above are for the `flutter` command line tool, so this doesn't seem like an issue with the VS Code extension. I'll move this to the Flutter repo.

/move flutter/flutter
