### ISSUE TITLE
Vscode does not give code completion suggestion

### ISSUE THREAD

**Issue by mausamRayamajhi** [Dart-Code/Dart-Code#1846]
Code suggestion works fine in intellij but does not in vscode.
Black backgraound image from Vscode and other is intellij
Flutter 1.7.8+hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2e540931f7 (7 hours ago) • 2019-07-09 13:14:38 -0700
Engine • revision 54ad777fd2
Tools • Dart 2.4.0

![60895662-c2420480-a284-11e9-98cc-1d5479a5d505](https://user-images.githubusercontent.com/28975010/60936203-061c2480-a2ec-11e9-9ba6-9f771dbad551.png)
![60895665-c2da9b00-a284-11e9-8f98-ece15c1b5449](https://user-images.githubusercontent.com/28975010/60936205-061c2480-a2ec-11e9-805f-a3ad49868faa.png)

**Comment by DanTup** [comment]
@mausamRayamajhi if you start typing `BoxDecoration`, is it in the list (just further down)?

If so, I think this may be the same as #1742?
