### ISSUE TITLE
Encoding(?) issue in string dartdoc

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#185]
Hovering `string` has this... Not sure if an encoding issue or maybe just the font not having the character.
![string encoding](https://cloud.githubusercontent.com/assets/1078012/18582984/e91bee6c-7bff-11e6-8006-a02c32e51faa.png)

**Comment by devoncarew** [comment]
I see this in vscode insiders on a mac:

<img width="227" alt="screen shot 2016-09-22 at 10 16 00 pm" src="https://cloud.githubusercontent.com/assets/1269969/18774899/64b681f6-8112-11e6-9d8e-5c86f489f774.png">

so, perhaps an issue with the font on windows?

**Comment by DanTup** [comment]
Yup, looks like I just don't have this char on Windows (I presume it's smart enough to fall back to other fonts if they have it, so presume this means none of my fonts have it). If the treble-clef exists on all platforms I wonder if it's worth updating the SDK to use one that works "out of the box" in more places (like the treble-clef?).

![Unicode clef](https://cloud.githubusercontent.com/assets/1078012/18842994/e6b4da8c-840e-11e6-9ff1-1b5992f8801b.png)
