### ISSUE TITLE
Cannot attach on iPhone after I add assets

### ISSUE THREAD

**Issue by lukepighetti** [Dart-Code/Dart-Code#1851]
Hey Dan, I've been struggling with an issue on my iPhone 8+ (iOS 12) with not being able to attach and failing during the "syncing files to device" portion of the launch process.

It seems that after I add a couple assets VSC will attach in debug with a 15% success rate. This seems to happen across all projects.

During this time XCode will launch with 100% success rate, and `flutter run --debug` will launch with 100% success rate.

I am just now coming to you with this issue because I'd like to know if you have any thoughts.

Sometimes I get no error in console before sigterm, sometimes I get a code 54 error before sigterm.

Thanks for your time and hope things are well.

```
Launching lib/main.dart on Luke's iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: xyzabc
Xcode build done.                                           12.3s
Could not update files on device: OS Error: Connection reset by peer, errno = 54
Exited (sigterm)
```

https://github.com/flutter/flutter/issues/34959

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.7.8+hotfix.2, on Mac OS X 10.14.5 18F132, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.36.1)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by DanTup** [comment]
Unfortunately this seems like a Flutter issue and I don't really know enough about what goes on there to have any suggestions.

There is a suggestion in the Flutter issue that it may be space related, and Ben's change to surface fs errors is not in the version of Flutter you're using. If you can repro on latest master, then that might surface any errors coming back.

**Comment by lukepighetti** [comment]
Hey Dan, I played around with it and I agree it's not VSC, since `flutter run --debug` only attaches sometimes.

**Comment by DanTup** [comment]
Yeah, VS Code doesn't do much here except ferry the output back to the debug console. Did you try and latest `master` to see if the filesystem changes are writing any errors?
