### ISSUE TITLE
Configurable delay before diagnostics are made visible

### ISSUE THREAD

**Issue by masliu** [Dart-Code/Dart-Code#1853]
Hello, I would like to request a feature that would allow me to configure the delay before the decorations are shown since I find the current delay -- if one even exists -- to be too eager and as such, distracting; i.e. I want to be able to type keywords without having errors pop up before I've finished typing. I would honestly prefer having vscode standardize this option but they seem averse to the idea and would rather have language providers implement it themselves.

**Comment by DanTup** [comment]
Do you have any links to VS Code issues about this? It does feel weird to do per-extension - and there are many questions I don't have answers to (like, if there is already an error on the code were you're typing and we get an update, should we still delay updating it, so we're showing a potentially old and unstable error?).

I think it would be much better if VS Code had an option to just hide any errors for the range you're typing in until you've stopped typing for x amount of time. I've be interested to see what they've said and whether any other extensions are working around this.

**Comment by masliu** [comment]
[Here is the issue](https://github.com/microsoft/vscode/issues/63737).

I don't know of any other extension that provides this option, but then again most of the extensions that I've installed (ex. C/C++, JS/TS) debounce by default. Since I want something consistent with these other extensions I think your questions might be better answered by referencing their implementation.

**Comment by DanTup** [comment]
@mjbvz how does TS handle this? It definitely seems to debounce the errors, but I'm not sure where.

It feels really weird to me to make this a per-language implementation, especially with LSP (a generic language server deliberately withholding errors for a time specifically to influence VS Code's editor behaviour is weird).

I think it would make much more sense as a VS Code setting to hide squiggles for the current line during typing (with a small timeout that brings them back when it expires).

**Comment by DanTup** [comment]
I made a start on this, but it occurs to me that doing it locally in the extension would result in it being lost in the migration to LSP. We could try to push this logic to the LSP server, but it doesn't really feel like it belongs there - whether this is visually distracting is somewhat editor-specific- so having the server artificially delay sending diagnostics to all editors feels a bit strange.

Additionally, LSP is considering moving [to a pull model for errors](https://github.com/microsoft/language-server-protocol/issues/737) which I think would prevent this anyway (though it might accidentally fix this, as editors may debounce the requests for errors).

On the flip side, it does seem quite aggressive for the server to immediately tell you you have an error as you start typing a keyword. @bwilkerson do you have any thoughts on this?

**Comment by bwilkerson** [comment]
I agree that we don't want to do this in server because it _is_ very client specific.

Server's original protocol already has the ability for clients to use a pull model if they want, so it shouldn't be difficult to support it via LSP.

**Comment by DanTup** [comment]
Cool, that should simplify things if it does change then.

Closing this then, as it doesn't seem to make sense to do in the old Dart-Code code nor LSP.
