### ISSUE TITLE
Feature request - separate self packages

### ISSUE THREAD

**Issue by lukepighetti** [Dart-Code/Dart-Code#1854]
Hi there, it appears that the language server has removed support for local imports, so I suggest grouping them below other imports automatically.

eg

```dart
import 'dart:math';

import 'package:flutter/material.dart';

import 'package: myapp/models/score.dart';
import 'package: myapp/theme/colors.dart';
import 'package: myapp/theme/fonts.dart';
import 'package: myapp/theme/localization.dart';
```

**Comment by DanTup** [comment]
Sounds reasonable to me - though this would need to be done in the analysis server, as all the sorting and inserting of them is done by it (or at least, it tells us where to insert, and what edits to make to sort). So this should be raised at https://github.com/dart-lang/sdk :-)

**Comment by lukepighetti** [comment]
Ahhhh thanks!
