### ISSUE TITLE
No remove widget Option

### ISSUE THREAD

**Issue by denniarems** [Dart-Code/Dart-Code#1855]
There is no remove widget option in vscode show fixes (bulb) button.
OS: Linux

**Comment by DanTup** [comment]
Please provide a concrete example of some code where you expect to see it but are not.

**Comment by Kuukyo3** [comment]
> Please provide a concrete example of some code where you expect to see it but are not.

Doesn't matter what code, the option simply doesn't exist for **any** widget in **any** position.

**Comment by DanTup** [comment]
Oh sorry, I think this option was renamed from "Remove Widget" to "Replace widget with its children" to try and be more explicit about what it does:

<img width="519" alt="Screenshot 2019-07-13 at 21 58 57" src="https://user-images.githubusercontent.com/1078012/61176479-8034fd80-a5b9-11e9-8a8a-54b40b14131d.png">

**Comment by denniarems** [comment]
I think better is Remove Widget

**Comment by DanTup** [comment]
The text comes from the Dart SDK rather than the VS Code plugin. It was changed after discussion in https://github.com/Dart-Code/Dart-Code/issues/1647 though, as it was confusing because it only sometimes shows up (eg. when the children will fit in the place of the widget being removed).
