### ISSUE TITLE
About dart plug-in running in vscode, CPU 99%

### ISSUE THREAD

**Issue by chengzixian** [Dart-Code/Dart-Code#1858]
@DanTup DanTup After testing, it is found that if the Flutter project is in the workspace, it will lead to 99% of the CPU, and the fan of the computer will turn very fast, the sound is very loud, and the heat is serious. If the Flutter project uses a separate folder to open in vscode, then there is no problem. Here are the screenshots I used and the sample files of the CPU.
![image](https://user-images.githubusercontent.com/23517357/61194739-0eae9980-a6f6-11e9-9bad-016b6accb65f.png)
![image](https://user-images.githubusercontent.com/23517357/61194774-47e70980-a6f6-11e9-9259-5cc34dddbf6a.png)
![image](https://user-images.githubusercontent.com/23517357/61194777-4b7a9080-a6f6-11e9-91b8-ffb43b02097f.png)

The following is when a Flutter project opens with a separate folder
![image](https://user-images.githubusercontent.com/23517357/61194790-6a792280-a6f6-11e9-9878-b8545bc3dd75.png)

**Comment by chengzixian** [comment]
This is a sample of the CPU of my computer.
[https://iguxuan.oss-cn-hangzhou.aliyuncs.com/Uploads/Editor/%E2%80%9Cdart%E2%80%9Dcpu.txt](https://iguxuan.oss-cn-hangzhou.aliyuncs.com/Uploads/Editor/%E2%80%9Cdart%E2%80%9Dcpu.txt)

**Comment by DanTup** [comment]
@chengzixian a few questions:

- Are there any symlinks in the folders you're opening?
- Can you also confirm the version of Flutter you have?
- Does it ever stop if you leave it (eg. for 10 minutes)?
- How big are the folders you're opening when this happens?

**Comment by avdept** [comment]
Having same issue, even when working on non dart projects

**Comment by DanTup** [comment]
@avdept can you answer the above questions? Also please include the output of running `code --status` from a terminal when the CPU is high. Thanks!

**Comment by DanTup** [comment]
Closing this due to no response, but if anyone is having CPU issues and can provide some of the information above, I'm happy to re-open and do more digging.
