### ISSUE TITLE
Trying to connect to firebase, app crashes after successfully running and connecting to firebase

### ISSUE THREAD

**Issue by KamalPatra** [Dart-Code/Dart-Code#1865]
Error:
Launching lib/main.dart on Android SDK built for x86 in debug mode...
[{"event":"app.progress","params":{"appId":"2bcfac62-cf46-4016-9611-845d75d49a99","id":"0","progressId":null,"message":"Initializing gradle..."}}]Initializing gradle...

[{"event":"app.progress","params":{"appId":"2bcfac62-cf46-4016-9611-845d75d49a99","id":"1","progressId":null,"message":"Resolving dependencies..."}}]Resolving dependencies...

[{"event":"app.progress","params":{"appId":"2bcfac62-cf46-4016-9611-845d75d49a99","id":"2","progressId":null,"message":"Running Gradle task 'assembleDebug'..."}}]Running Gradle task 'assembleDebug'...

registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
[{"event":"app.progress","params":{"appId":"2bcfac62-cf46-4016-9611-845d75d49a99","id":"4","progressId":null,"message":"Syncing files to device Android SDK built for x86..."}}]Syncing files to device Android SDK built for x86...

I/example.rent_m(31865): Background concurrent copying GC freed 10712(783KB) AllocSpace objects, 9(260KB) LOS objects, 49% free, 2039KB/3MB, paused 9.260ms total 3.359s
I/Choreographer(31865): Skipped 323 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation(31865): eglMakeCurrent: 0xe0197c60: ver 3 0 (tinfo 0xe01f0bd0)
I/flutter (31865): _opacity.value: 0.0
D/EGL_emulation(31865): eglMakeCurrent: 0xe2b858a0: ver 3 0 (tinfo 0xe2b83940)
Failed to send request: {"jsonrpc":"2.0","id":"4","method":"streamListen","params":{"streamId":"Extension"}}
Failed to send request: {"jsonrpc":"2.0","id":"5","method":"getVM","params":{}}
Lost connection to device.
E/DartVM  (31865): vm-service: Error: Unhandled exception:
E/DartVM  (31865): Unrecognized response: null
E/DartVM  (31865): #0      new Response.from (dart:_vmservice/message_router.dart:70:7)
E/DartVM  (31865): #1      Message._setResponseFromPort (dart:_vmservice/message.dart:244:29)
E/DartVM  (31865): #2      Message.sendToVM.<anonymous closure> (dart:_vmservice/message.dart:216:7)
E/DartVM  (31865): #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
E/DartVM  (31865): 
E/flutter (31865): [ERROR:flutter/runtime/dart_isolate.cc(814)] Unhandled exception:
E/flutter (31865): Unrecognized response: null
E/flutter (31865): #0      new Response.from (dart:_vmservice/message_router.dart:70:7)
E/flutter (31865): #1      Message._setResponseFromPort (dart:_vmservice/message.dart:244:29)
E/flutter (31865): #2      Message.sendToVM.<anonymous closure> (dart:_vmservice/message.dart:216:7)
E/flutter (31865): #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
Failed to send request: {"jsonrpc":"2.0","id":"6","method":"getVM","params":{}}

**Comment by KamalPatra** [comment]
Does anyone have any solution cause I am unable to solve it? tried searching it on google. Nothing helps.

**Comment by DanTup** [comment]
Does this happen if you run `flutter run -v` from the terminal, or only from VS Code?

**Comment by KamalPatra** [comment]
I am running it on Android Studio.

**Comment by KamalPatra** [comment]
The app remains on the phone but the IDE says it lost connection to the device. It happens on both android and ios.

**Comment by KamalPatra** [comment]
Launching lib/main.dart on iPhone Xʀ in debug mode...
[{"event":"app.progress","params":{"appId":"b9a1fffb-612c-4d5d-ac2f-6e436ccef626","id":"0","progressId":null,"message":"Running pod install..."}}]Running pod install...

Running Xcode build...
Xcode build done.                                           36.8s
6.4.0 - [Firebase/Analytics][I-ACS023007] Analytics v.60003000 started
6.4.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
Syncing files to device iPhone Xʀ...
flutter: _opacity.value: 0.0
	[C1.1 B81B7F19-FCDC-4AB9-A769-19BBC4F3333F 192.168.2.205:50427<->216.58.221.42:443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 1.863s, DNS @0.005s took 0.026s, TCP @0.036s took 0.009s, TLS took 0.779s
	bytes in/out: 4565/1072, packets in/out: 10/9, rtt: 0.006s, retransmitted packets: 0, out-of-order packets: 0
	[C2.1 4E44E6E6-41F9-41BA-B206-3F417CC8F092 192.168.2.205:50446<->216.58.221.46:443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.298s, DNS @0.001s took 0.001s, TCP @0.006s took 0.005s, TLS took 0.106s
	bytes in/out: 3664/789, packets in/out: 9/8, rtt: 0.003s, retransmitted packets: 0, out-of-order packets: 0
	[C3.1 5120B8E8-A138-4639-B370-4D3031E1C058 192.168.2.205:50447<->216.58.221.46:443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.256s, DNS @0.001s took 0.003s, TCP @0.008s took 0.005s, TLS took 0.162s
	bytes in/out: 3617/1457, packets in/out: 9/9, rtt: 0.004s, retransmitted packets: 0, out-of-order packets: 0
vm-service: Error: Unhandled exception:
Unrecognized response: null
#0      new Response.from (dart:_vmservice/message_router.dart:70:7)
#1      Message._setResponseFromPort (dart:_vmservice/message.dart:244:29)
#2      Message.sendToVM.<anonymous closure> (dart:_vmservice/message.dart:216:7)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
[VERBOSE-2:dart_isolate.cc(814)] Unhandled exception:
Unrecognized response: null
#0      new Response.from (dart:_vmservice/message_router.dart:70:7)
#1      Message._setResponseFromPort (dart:_vmservice/message.dart:244:29)
#2      Message.sendToVM.<anonymous closure> (dart:_vmservice/message.dart:216:7)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
Lost connection to device.
Failed to send request: {"jsonrpc":"2.0","id":"3","method":"streamListen","params":{"streamId":"Extension"}}
Failed to send request: {"jsonrpc":"2.0","id":"4","method":"getVM","params":{}}
Failed to send request: {"jsonrpc":"2.0","id":"5","method":"streamListen","params":{"streamId":"Debug"}}

**Comment by KamalPatra** [comment]
I am trying to make google sign in, it works on the android but not on the ios. I do not know the reason behind it as both the devices(Android and iOS) get disconnected after running.

**Comment by DanTup** [comment]
This repository is for the VS Code plugin - if you're seeing this in Android Studio then this it's not something that can be fixed here - it would be better raised at https://github.com/flutter/flutter. Thanks!
