### ISSUE TITLE
can't open dart extension in vs code after upgrading to MacOs Catalina beta10.15

### ISSUE THREAD

**Issue by supeng123** [Dart-Code/Dart-Code#1873]
I could not run flutter project after upgrading to MacOS Catalina 10.15 Beta, even if I clicked the Open anyway button in Settings for Security&Privacy
<img width="676" alt="Screen Shot 2019-07-17 at 10 41 45 PM" src="https://user-images.githubusercontent.com/14172633/61385230-92c67400-a8e4-11e9-8913-70edc866171d.png">

**Comment by DanTup** [comment]
There are some issues using Flutter on Catalina currently, there's an issue tracking these at https://github.com/flutter/flutter/issues/36290.

I would advise against using a beta OS for production work (often public betas are the first opportunity for bugs like this to be discovered and then fixes developed), though I have no idea how easy/possible it us to revert.

Please subscribe to the Flutter issue for updates. Thanks!
