### ISSUE TITLE
Dart do not get path on the 3.2.1 version, even when you set manually 

### ISSUE THREAD

**Issue by angeloghiotto** [Dart-Code/Dart-Code#1874]
I recently installed the Dart extension to 3.2.1 and it do not found the flutter bin, even when i manually set it when it asks to me ( dialogue box ) to set the bin, then i installed the 3.0 ( both flutter and dark extensions ) version and then it works when i set manually through  from the dialogue box.

**Comment by DanTup** [comment]
There should be a button that says "Show Log" on the message when we can't find an SDK, could you attach that log (after you've set it using the `Locate SDK` button) and also confirm the location of where you have Flutter? Thanks!

**Comment by angeloghiotto** [comment]
I updated it now to the latest version, and ran a "Fluttler Doctor" through VS, and now its working fine, i even uninstalled the extensions and installed again, and works fine from the first try.

I was since yesterday trying to fix this and I've taken a look into this log, it was saying that the extension were looking in a lot of "bin" folders but was not able to find flutter, also are not keeping the location I've pointed in the dialog box. 

I've looked also in this thread : https://github.com/Dart-Code/Dart-Code/issues/1423, from there i came up with the idea of downgrade my version, since i did the downgrade it was fixed even for the latest version and i can't reproduce the issue anymore.

**Comment by DanTup** [comment]
If you see it again, please grab a copy of the log and I'll take a look. We scan `PATH` looking for Flutter at startup, but we should always check the location you specify in the file browser (it should be written to your VS Code User Settings).
