### ISSUE TITLE
Analysis  server has terminated 

### ISSUE THREAD

**Issue by OOMROO** [Dart-Code/Dart-Code#1875]
I use Android Studio. When I open one of my projects, I report that the Analysis server has terminated, Dart Analysis without log output. When I open another project, Dart Analysis is good, which can test my Dart code. I don't know what went wrong with the first project. Can you help me?

Because doctor is ok
"✓" Flutter (Channel stable, v1.7.8 + hotfix. 3, on Mac OS X 10.14.5 18 f132, locale useful - Hans - CN)

[✓] Android toolchain to develop for Android devices, the Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.36.1)
[✓] Connected device available (1)

**Comment by DanTup** [comment]
This repository is for the VS Code extension, not Android Studio. Can you reproduce it in VS Code? If so, can you click the Show Log button and attach the log? Thanks!

**Comment by OOMROO** [comment]
The dart Analysis TAB at the bottom of the Flutter project developed by Android Studio that I used indicates that Analysis server has terminated. I don't know what relationship it has with VS code. I deleted the project and re-opened clone after this error disappeared, I do not know why. I'll close this issuse. Thank you very much for your reply

**Comment by DanTup** [comment]
Glad it's working now, if you do see it again it's probably best to raise at https://github.com/flutter/flutter-intellij (Android Studio uses the same plugin as IntelliJ for Flutter) and someone should be able to help get logs (I'm afraid I don't know how). I do know how to get logs if you can repro it using VS Code and the Dart/Flutter extensions there though (that's what this repo is for).
