### ISSUE TITLE
Pass client id and version to Dart analysis server

### ISSUE THREAD

**Issue by skybrian** [Dart-Code/Dart-Code#188]
For example, IDEA passes these flags when starting up the analysis server:
--client-id=IntelliJ_IDEA --client-version=IU-145.1617

Seems like the Dart-Code extension should pass these flags as well? That way the client id and version appear in the analysis server's instrumentation logs.

**Comment by DanTup** [comment]
Didn't know about these, but it makes sense. Will add for next version, thanks!

**Comment by DanTup** [comment]
@skybrian These switches don't seem to be mentioned in the [API spec](https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html); is it worth me raising a case in SDK to have details added?

**Comment by skybrian** [comment]
Yes, documenting these flags seems like a good idea. Thanks!

**Comment by DanTup** [comment]
These now get passed as args. I don't know if I confirm they're doing what they should, but I presume there's not much to do wrong here (as long as I haven't used any invalid characters or anything?).

![Client ID](https://cloud.githubusercontent.com/assets/1078012/19186229/30f669d2-8c7d-11e6-9881-5cf1bc1c9779.png)

**Comment by skybrian** [comment]
I verified that it's working for me, with some custom (non-open-source) analytics. Thanks!

I'm guessing it might show up for you in the log file if you use the analysis server's --instrumentation-log-file flag.

**Comment by DanTup** [comment]
Great; thanks for confirming! :-)
