### ISSUE TITLE
Private variable value is not displayed when hovered in debugging

### ISSUE THREAD

**Issue by skybur** [Dart-Code/Dart-Code#1880]
I don't know if this is normal behavior, but IIRC previously I can hover private variable to see its value when debugging (CMIIW). 
If it's the normal behavior, is it possible to make private variable can be accessed when debugging?
Thank you.

**Comment by DanTup** [comment]
I can't repro this in v2.4.0 either inside the same file where the private variable is referenced in the editor, not when it's in another file and I'm viewing it in the hover for the parent class.

<img width="499" alt="Screenshot 2019-07-19 at 09 35 05" src="https://user-images.githubusercontent.com/1078012/61521609-8804ff80-aa08-11e9-86fd-5abb2622575a.png">
<img width="424" alt="Screenshot 2019-07-19 at 09 35 12" src="https://user-images.githubusercontent.com/1078012/61521611-8804ff80-aa08-11e9-84cb-5f56bedb10e2.png">

Can you provide a small sample that reproduces and confirm the version of the SDK you're using (+ VS Code and Dart extension versions). Thanks!

**Comment by skybur** [comment]
Ah sorry, forgot to include versions.
I tried with project created with flutter create, here is the gif
![2019-07-19_16-43-31](https://user-images.githubusercontent.com/11155424/61526462-a557bf00-aa44-11e9-89e5-20ae44b42b39.gif)

DartCode version 3.2.1
Flutter extension version 3.2.0
VSCode version 1.36.1
```
[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.17763.615], locale en-US)
    • Flutter version 1.7.8+hotfix.3 at D:\Devs\Flutter\flutter
    • Framework revision b712a172f9 (10 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\AndroidSDK
    • ANDROID_SDK_ROOT = D:\AndroidSDK
    • Java binary at: D:\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at D:\AndroidStudio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code, 64-bit edition (version 1.36.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (1 available)
    • Redmi 3S • android-arm64 • Android 6.0.1 (API 23)

• No issues found!
```

**Comment by DanTup** [comment]
Strange, I still can't repro.

<img width="270" alt="Screenshot 2019-07-23 at 9 56 38 am" src="https://user-images.githubusercontent.com/1078012/61697959-38884180-ad30-11e9-92ab-4d2ff98dd0cf.png">

Could you run **Dart: Capture Logs** and tick only the **Debugger** option, then reproduce the issue, and attach the logs? Thanks!

**Comment by skybur** [comment]
Here is the log. I also tried adding logpoint instead of breakpoint but I get error  `Debugger failed to evaluate expression print("""$_counter""")`
[Dart-Code-Log-2019-06-02 16-08-36.txt](https://github.com/Dart-Code/Dart-Code/files/3421201/Dart-Code-Log-2019-06-02.16-08-36.txt)

**Comment by DanTup** [comment]
Ok, I can repro this on Flutter's `stable` channel but not on `master`, so I think it's already been fixed. Could you try temporarily switching to `master` and see if the problem is resolved for you?

**Comment by skybur** [comment]
Alright lemme try it with master branch

**Comment by skybur** [comment]
Yup you're right, I can access the private variable. Looks like this is flutter problem. Gonna close this then. Thank you @DanTup

**Comment by DanTup** [comment]
Great, thanks for confirming!
