### ISSUE TITLE
Support a configuration attribute 'program' for 'flutter.attach'

### ISSUE THREAD

**Issue by Drakirus** [Dart-Code/Dart-Code#1881]
With the flutter CLI we can run:
```
$ flutter attach --device-id=flutter-tester --debug-uri=http://[....] --target=lib/main_desktop.dart 
```
The `target` flag is used to select `The main entry-point file of the application, as run on the device`, if omitted, it default to "lib/main.dart").

Currently the extension doesn't support custom entry-point, [ref](https://github.com/Dart-Code/Dart-Code/blob/87fcd00d5c31c59008a012cf9be6f6786e4a7edd/package.json#L1475-L1492), "lib/main.dart" is always used.

**Comment by Drakirus** [comment]
Awesome! Thanks.

**Comment by DanTup** [comment]
I'm planning to make a beta build today that will include this if you want to test it, just gotta sort a few things out first.

**Comment by DanTup** [comment]
There's a beta build here:

https://github.com/Dart-Code/Dart-Code/releases/tag/v3.3.0-beta.2

Release notes aren't done yet (but hopefully will be done today). Please let me know if you try it out if you have any issues.

**Comment by Drakirus** [comment]
After testing I didn't found any issues!

**Comment by DanTup** [comment]
Great, thanks for confirming! 👍
