### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by geente** [Dart-Code/Dart-Code#1883]
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `3.2.1`
- OS Version: `Linux x64 4.15.0-54-generic`
- VSCode version: `1.36.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/gianto/Dart-Code.dart-code-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by DanTup** [comment]
> ⚠️ Make sure to attach this file from your home-directory:
> ⚠️/home/gianto/Dart-Code.dart-code-unresponsive.cpuprofile.txt

Are you able to attach this file? Thanks!
