### ISSUE TITLE
Dart: Dev Tools activation fails

### ISSUE THREAD

**Issue by PrashantKeswani** [Dart-Code/Dart-Code#1884]
I am new to Flutter development. I am using VSCode v1.36.
Dart: Devtools appears in the command pallette. On opening Dev tools first time, it asks to Activate DevTools in a popup. On clicking the Activate DevTools button, I am getting an error. The error shown in the Toggle Developer Tools console is as below. I am not sure which directory it is trying to rename?

Failed to rename directory because access was denied.
This may be caused by a virus scanner or having a file
in the directory open in another application.
notificationsAlerts.ts:40 Command 'Dart: Open DevTools' resulted in an error.

**Comment by DanTup** [comment]
Can you provide a full screenshot of what you see, and also if the messages has a "Show Log" button on it, the output shown when you click it? Thanks!

**Comment by PrashantKeswani** [comment]
**Versions**
![Versions](https://user-images.githubusercontent.com/53167258/61682833-d3811b80-ad30-11e9-9246-bbf7b33ac6d7.jpg)



**Error message (No "Show Log" button)**
![ErrorMessage](https://user-images.githubusercontent.com/53167258/61682834-d3811b80-ad30-11e9-8cef-4fe6f05c270f.jpg)



**On opening Toggle Developer Tools from Help**
![ToggleDeveloperTools](https://user-images.githubusercontent.com/53167258/61682832-d2e88500-ad30-11e9-97d1-396ad6aafaf6.jpg)

**Comment by DanTup** [comment]
Thanks - it looks like this is occurring while devtools is activating. Can you try closing all instances of VS Code, ensure you don't have any `dart` processes still running in the background, and then run this from the terminal:

```
pub global activate devtools
```

If that works, then re-open VS Code and try again. If it fails with the same error from the command line, let me know and we may need to raise this with `pub`. Thanks!

**Comment by PrashantKeswani** [comment]
Thanks. I tried activating devtools from the command prompt as per your suggestion. I still get the same error. While running the command VS Code was not running neither was any dart process running in background. Below is the content from the command prompt.

C:\Users\kprashant>flutter pub global activate devtools
Resolving dependencies...
+ args 1.5.2
+ async 2.3.0
+ boolean_selector 1.0.5
+ browser_launcher 0.1.2
+ charcode 1.1.2
+ codemirror 0.5.7+5.48.0
+ collection 1.14.11
+ convert 2.1.1
+ crypto 2.0.6
+ devtools 0.1.4
+ devtools_server 0.1.4
+ http 0.12.0+2
+ http_parser 3.1.3
+ intl 0.15.8
+ js 0.6.1+1
+ logging 0.11.3+2
+ matcher 0.12.5
+ meta 1.1.7
+ mime 0.9.6+3
+ mockito 4.0.0 (4.1.0 available)
+ octicons_css 0.0.1
+ path 1.6.2
+ pedantic 1.8.0+1
+ platform_detect 1.3.5
+ plotly_js 0.0.1
+ polymer_css 0.0.1
+ primer_css 0.0.2
+ pub_semver 1.4.2
+ rxdart 0.22.1
+ shelf 0.7.5
+ shelf_static 0.2.8
+ shelf_web_socket 0.2.3
+ source_span 1.5.5
+ split 0.0.2
+ stack_trace 1.9.3
+ stream_channel 2.0.0
+ stream_transform 0.0.19
+ string_scanner 1.0.4
+ term_glyph 1.1.0
+ test_api 0.2.6
+ typed_data 1.1.6
+ vm_service_lib 3.21.0 (3.22.2 available)
+ web_socket_channel 1.0.14
+ webkit_inspection_protocol 0.4.2 (0.5.0 available)
Downloading devtools 0.1.4...
Downloading plotly_js 0.0.1...
**Failed to rename directory because access was denied.
This may be caused by a virus scanner or having a file
in the directory open in another application.
pub failed (1)**

**Comment by DanTup** [comment]
@PrashantKeswani it looks like the same issue reported at https://github.com/dart-lang/pub/issues/1798. Unfortunately this is entirely outside of the VS Code extension since it happens at the terminal too.

If you haven't already, it's worth trying a reboot - Windows seems to be quite bad at releasing file locks, and it seems like something might have the file locked. Otherwise, it could be anti-virus as described in the message.

Other than that, I don't have any suggestions - but if you post on the Pub issue linked, the Pub developers might have more ideas about what to try. Hope this helps!

**Comment by PrashantKeswani** [comment]
Thanks Danny for all the help!!!
It turns out it was the virus scanner. I had installed a trial version long back and was under the impression that it must have stopped working by now. But it was blocking the activation.
On disabling the scanner, devtools is working.

Thanks again!!

**Comment by DanTup** [comment]
Great! You may wish to check that AV didn't disable Windows Defender when you installed it, leaving you without protection now. Glad it's sorted though!

**Comment by skykrishnadon** [comment]
You mean we all need to disable antivirus even the licensed one ?

**Comment by DanTup** [comment]
> You mean we all need to disable antivirus even the licensed one ?

I wouldn't generally recommend disabling any antivirus. However, if your antivirus software is blocking execution of programs like DevTools, there's not really anything we can do from the VS Code extension. It would be better if you could find a way to specifically DevTools than disabling it, but what options you have will depend on which antivirus software it is (and potentially on rules that may have been set by administrators).

**Comment by diegosayron** [comment]
Oh, god! just add an exclusion!

**Comment by diegosayron** [comment]
It's not necessary to disable the antivirus.
EVERY antivirus has a way to add exclusions. Just do it.
Because of disabling firewall, antivirus, UAC, sharing folders with everyone, many people say that MS Windows is insecure...
