### ISSUE TITLE
No Devices available in vs code, even if flutter lists two devices. Ubuntu 18.04.

### ISSUE THREAD

**Issue by oppsig** [Dart-Code/Dart-Code#1885]
- VSCode Version: 1.36.1
- OS Version: Ubuntu 18.04

**Steps to Reproduce:**

1. git clone https://github.com/google/flutter-desktop-embedding
2. open example folder in vs code.
3. install flutter / dart extentions.
4. edit settings.json file:
```
{
    "dart.env": {
        **"FLUTTER_DESKTOP_EMBEDDING": true,**
        "dart.flutterSdkPath": "/home/kodi/development/flutter/bin/flutter", 
        "dart.sdkPath": "/usr/lib/dart/bin/dart",
    },
}
```
5. try to build lib/main.dart with F5 menu.

**Issue:**
I'cant select flutter device linux within vs code on my Ubuntu 18.04 install.
Even if flutter doctor detects two devices, and one of them is linux, vs code shows No Devices.
This is however not a problem in my archlinux install.
The only difference i can tell is that my archlinux install runs clang 8 and GNU make 4.2.1.
That shouldn't matter should it?

**Output of flutter doctor -v**
```
➜  project git:(master) flutter doctor -v
[✓] Flutter (Channel master, v1.8.2-pre.125, on Linux, locale en_US.UTF-8)
    • Flutter version 1.8.2-pre.125 at /home/kodi/development/flutter
    • Framework revision 4bc2bf67c1 (18 hours ago), 2019-07-21 10:47:27 -0400
    • Engine revision fc68f6abc2
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 a089199b93)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /home/kodi/development/android-sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /usr/lib/jvm/java-8-oracle/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang++ 6.0.0
    • GNU Make 4.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.36.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.2.0

[✓] Connected device (2 available)
    • Linux  • Linux  • linux-x64      • Linux
    • Chrome • chrome • web-javascript • Google Chrome 75.0.3770.142 
```

**Comment by oppsig** [comment]
Ok this was solved in my case by setting,
export ENABLE_FLUTTER_DESKTOP=true in .zshrc. 
Doesn't seam like vscode cares about the "dart.env" in settings.json.

**Comment by DanTup** [comment]
```js
 "dart.env": {
        **"FLUTTER_DESKTOP_EMBEDDING": true,**
        "dart.flutterSdkPath": "/home/kodi/development/flutter/bin/flutter", 
        "dart.sdkPath": "/usr/lib/dart/bin/dart",
    },
```

FWIW, `dart.flutterSdkPath` and `dart.sdkPath` are VS Code settings, not environment variables, you should not put them inside `dart.env`. If Dart/Flutter already work like this, then you can just delete them from there as they're not doing anything.

> export ENABLE_FLUTTER_DESKTOP=true in .zshrc.

This should do the same thing. I wonder if the `dart.flutterSdkPath` etc. might be confusing things? Try again after removing them - but also be sure to restart VS Code, as changes to `dart.env` might not apply to the daemon if made after it starts.

**Comment by oppsig** [comment]
So first i removed dart.flutterSdkPath and dart.sdkPath from dart.env.
Then kept "FLUTTER_DESKTOP_EMBEDDING": true, in "dart.env" and commented out ENABLE_FLUTTER_DESKTOP=true in .zshrc.
Restarted vscode and No Devices.

Then i enabled ENABLE_FLUTTER_DESKTOP again in .zshrc and commented out "FLUTTER_DESKTOP_EMBEDDING": true,
Linux (linux-x64) device connected.
So works with or without FLUTTER_DESKTOP_EMBEDDING in dart.env?

As you said the dart sdk lines in dart.env didnt have anything to say.

**Comment by DanTup** [comment]
I tried this here, but it always seems to work as expected :(

Could you try enabling the [Flutter Daemon](https://dartcode.org/docs/logging/#flutter-daemon) log and restart VS Code, then see what it captures?

**Comment by stuartmorgan** [comment]
Your issue is that `FLUTTER_DESKTOP_EMBEDDING` is not the right variable, and hasn't been for some time. It was changed to `ENABLE_FLUTTER_DESKTOP` in the `flutter` tooling. Whatever instructions you were following to set your `dart.env` were out of date.

However, as of very recently the preferred approach is to use `flutter config` as [described here](https://github.com/flutter/flutter/wiki/Desktop-shells#tooling), at which point you don't need to use `dart.env` any more.

**Comment by DanTup** [comment]
@stuartmorgan thanks!

@oppsig please let me know if following the updated instructions above doesn't resolve the issues.

**Comment by oppsig** [comment]
yes you can close this issue. no need for flutter daemon log is there?

**Comment by DanTup** [comment]
If the issue is solved by the above, there's no need for a log - seems like the issue is understood. If you're using the new config, you should not need to set any env variables in the VS Code settings anymore and can remove them.
