### ISSUE TITLE
better error handling for analysis server crash

### ISSUE THREAD

**Issue by skybrian** [Dart-Code/Dart-Code#189]
I managed to trigger a fatal error that caused the analysis server to die. When this happens, there's no indication that it stopped working. If I open the console, I see repeated stack traces:

```
shell.ts:428This socket has been ended by the other party: Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:278:12)
    at Analyzer.sendMessage ([redacted]/.vscode/extensions/DanTup.dart-code-0.11.1/out/src/analysis/analyzer.js:78:36)
    at [redacted].vscode/extensions/DanTup.dart-code-0.11.1/out/src/analysis/analyzer.js:111:19
    at Analyzer.sendRequest ([redacted]/.vscode/extensions/DanTup.dart-code-0.11.1/out/src/analysis/analyzer.js:108:16)
    at AnalyzerGen.analysisUpdateContent ([redacted]/.vscode/extensions/DanTup.dart-code-0.11.1/out/src/analysis/analyzer_gen.js:491:21)
    at FileChangeHandler.onDidChangeTextDocument ([redacted].vscode/extensions/DanTup.dart-code-0.11.1/out/src/file_change_handler.js:34:27)
    at [redacted]/.vscode/extensions/DanTup.dart-code-0.11.1/out/src/extension.js:90:109
    at e.invoke (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:13653)
    at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:15829)
    at t.$acceptModelChanged (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:11:13505)e.onUnexpectedError @ shell.ts:428
4threadService.ts:217[Extension Host] This socket has been ended by the other party(anonymous function) @ threadService.ts:217
```

I'd hope to see some visual indicator that it's not working and a button to restart it.

**Comment by DanTup** [comment]
Makes sense!

If you're able to repro the crash, could you raise another issue about that so I can investigate that? A button to restart is a good fallback, but it's a feature of love to try and avoid anybody needing!

**Comment by DanTup** [comment]
When re-launching the AS, will need to be sure to re-send any open file buffers. This work might go will with an open issue about re-launching the AS if the sdkPath in settings is modified.

**Comment by DanTup** [comment]
I've put a simple change in for now that catches errors writing to the servers STDIN and prompts the user to reload the project.

I don't know if this is sufficient (it doesn't catch when we can write to STDIN but the AS is broken in another way and if we failed to start the AS entirely this might be misleading), but I don't know if those are things that could happen (though happy to investigate if they ever do come up).

**Comment by DanTup** [comment]
@skybrian I've pushed out 0.11.2 with this tweak included. If you still see crashes this doesn't detect, you can execute (`Ctrl`+`Shift`+`P` for command palette) the `Reload Window` command manually to reset things.

That said; if you're seeing frequent crashes please let me know. Ideally nobody will ever experience this, but if it happens a lot and it seems unavailable, adding a "silent" restart mechanism for the analyser could be worthwhile.

**Comment by skybrian** [comment]
Thanks! For this sort of thing it seems more efficient to report it directly to the Dart Analyzer team, particularly if it's happening in an unreleased version of the Dart SDK. But if it seems to be somehow VS Code-related then I will report it here.

**Comment by DanTup** [comment]
Sure! I guess to you it'll be obvious where the issue lies, though for many users it might be unclear where the split in responsibility is (or that this even backs onto a Dart Team-authored service) so I'm happy to help debug :-)

Non-bug feedback is welcome too! I don't do a lot of Dart myself (hopefully Dart Code will help increase that) so knowing the pain points or what can generally improved is really helpful!
