### ISSUE TITLE
vscode adb instants kills any other existing instants (no adb wireless)

### ISSUE THREAD

**Issue by wrussell1999** [Dart-Code/Dart-Code#1894]
When I start debugging in vscode, it creates an adb instants to connect to the device. This stops any existing adb instants running. This means you can't debug wirelessly, like you can with Android Studio.

**Comment by DanTup** [comment]
Can you clarify exactly what you're seeing? I've used wireless debugging without any issues before. VS Code doesn't spawn ADB itself (except for on ChromeOS if you set `dart. flutterAdbConnectOnChromeOs`) it just runs the Flutter device daemon (so in theory it should be the same Android Studio).

Can you give steps I can use to reproduce exactly what you're seeing? Thanks!

**Comment by wrussell1999** [comment]
I will run through this a little later and post screenshots and more detail. It might be to do with the Flutter extension but I am not sure

**Comment by DanTup** [comment]
This issue tracker covers both the Dart and Flutter extensions - though the Flutter extension doesn't do much on its own (right now all the functionality is in the Dart extension). It may be useful to capture logs ([extension](https://dartcode.org/docs/logging/#extension) and [daemon](https://dartcode.org/docs/logging/#flutter-daemon)) too, though a clear description of what you're seeing and the steps to try and repro are most important. Thanks!

**Comment by wrussell1999** [comment]
Will try and post details tonight

**Comment by wrussell1999** [comment]
If I open a terminal with vscode open with a Flutter project:

```bash
$ adb kill-server
$ adb tcpip 5555
adb server version (41) doesn't match this client (39); killing...
```

This doesn't happen once I've closed vscode. Maybe the extension and my terminal are using different versions?? Maybe this isn't extension specific but would be neat if the extension gave you an option to connect to device via IP when selecting device to connect to in the drop down.

**Comment by DanTup** [comment]
This sounds like you have two different versions of adb - one being detected by Flutter and one that you're calling here in the terminal.

If you fun `flutter doctor -v` it should show you the Android SDK path it is using, and you can try calling adb from there (though it's probably worth trying to also eliminate one of your SDK versions to avoid future confusion).

> Maybe this isn't extension specific but would be neat if the extension gave you an option to connect to device via IP when selecting device to connect to in the drop down.

Do you mean somewhere to enter an IP that will just run `adb connect (ip)` for you? Am I right in thinking your workflow is currently:

- open terminal
- run `adb tcpip 5555`
- run `adb connect (phone ip):5555`

?

**Comment by wrussell1999** [comment]
I'm gonna try and fix the adb problem.

And yes that is my current workflow

**Comment by wrussell1999** [comment]
I got `flutter devices` to detect my device over wireless, however when pressing F5 I got this in the Debug Console.

```
Unable to locate a development device; please run 'flutter doctor' for information about installing additional components.
```

I ran `flutter run` in the terminal and it works fine over wireless

**Comment by DanTup** [comment]
> However, being to start the adb server inside vscode would be a neat feature.

Can you clarify what you mean? The server should be started automatically. Do you mean automatically run `adb connect`?

If so, you should be able to do this already with a task (in your `.vscode/tasks.json`):

```js
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "adb connect",
			"type": "shell",
			"command": "adb",
			"args": [
				"connect",
				"192.168.0.0:5555"
			],
			"runOptions": {
				"runOn": "folderOpen"
			},
			"problemMatcher": []
		}
	]
}
```

You may need to run the **Allow Automatic Tasks in Folder** command to allow it to run automatically when you open the folder.

**Comment by wrussell1999** [comment]
Yeah sorry, I meant `adb connect`. Thanks, I'll give that a go.
