### ISSUE TITLE
"Locate SDK" button may not be saving SDK path correctly

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#1896]
I've seen reports this might not be working correctly before, but never really got a concrete example. Today @ClassicNations mentioned the same thing in Gitter, that selecting the Flutter SDK folder with "Locate SDK" didn't seem to persist the setting.

This needs some testing (and if I can't repro, the code reviewing for any obvious reasons it might not save).

**Comment by mcachopas** [comment]
Having the same issue, im trying alot, if i found sothing i will post here

**Comment by mcachopas** [comment]
Solved here 

Just downloading the SDK installer for Windows [http://www.gekorm.com/dart-windows](url) from the webpage [https://dart.dev/get-dart](url), and instaled on my PC

Try out

**Comment by craigoha** [comment]
Same issue = "_... selecting the Flutter SDK folder with "Locate SDK" didn't seem to persist the setting._"

Like @ClassicNations, installed Flutter originally in programs directory but then moved it to another directory for organization reasons. 

@DanTup Is there a way to manually change the path via VS Code > File > Preferences > Settings > Dart: Flutter Sdk Path? Current path is displayed after opening _Edit in settings.json_ but cannot be changed.

![image](https://user-images.githubusercontent.com/53590199/62358501-3310cf80-b558-11e9-91a5-0c3aafb1a024.png)

**Comment by DanTup** [comment]
@craigoha you should definitely be able to edit the setting in your Settings json editor - just add a comma to the end of that existing line, then start typing `dart.flutterSdkPath` and it should be in the auto-complete.
