### ISSUE TITLE
How to change named parameters color in color theme?

### ISSUE THREAD

**Issue by JCKodel** [Dart-Code/Dart-Code#1900]
![image](https://user-images.githubusercontent.com/379339/62300272-dd033580-b44c-11e9-862d-b367fb017f65.png)

It is possible (and if yes, how) to colorize only the named parameters in VSCode?

(notice in the example above that common text still white, while only named parameters are yellow)

**Comment by DanTup** [comment]
I don't think it's currently possible - though is your screenshot from VS Code or IntelliJ? If VS Code, which theme is it that shows them in yellow?

**Comment by JCKodel** [comment]
The screenshot is VSCode (I've painted yellow using an image editor, just
for illustration purposes).

**Comment by DanTup** [comment]
Oh, I see :-)

In theory, I think it shouldn't be difficult to assign these a different scope so they could be coloured differently. In practice, every time I change the grammar file I break stuff 😄 I'll see what I can do though.

**Comment by DanTup** [comment]
Upon reviewing the syntax file, I don't think this would be easy. I think there may be upcoming changes to how syntax highlighting works in VS Code (switching to another format from textmate grammars) so I think it would be better to handle this then (since the new format may be better, and may be more easily testable!).

**Comment by SoKamil** [comment]
https://github.com/microsoft/vscode/pull/95958
They did something and also they introduced semantic highlighting for TS and JS, and have announced it for Java and C++

**Comment by DanTup** [comment]
I do plan to support semantic highlighting - but it will be using LSP (which we're migrating to, but it doesn't have semantic highlighting support yet - the API is still only proposed).

**Comment by DanTup** [comment]
Once https://dart-review.googlesource.com/c/sdk/+/179769 lands (and you're on an SDK that uses it and have the LSP Preview enabled), you'll be able to set the colours of parameter names at call sites with the following settings:

```js
	"editor.semanticTokenColorCustomizations": {
		"rules": {
			"parameter.label": "#990",
		},
	},
```

![Screenshot 2021-01-19 at 10 35 26](https://user-images.githubusercontent.com/1078012/105022798-10bb8c00-5a42-11eb-91ae-c0b902e3421e.png)
