### ISSUE TITLE
for symbol search[cmd + t], add option to hide symbols from sdk

### ISSUE THREAD

**Issue by lwky** [Dart-Code/Dart-Code#1903]
I want to be able to only list the symbols from files in my workspace, to speed up the search and greatly reduce the number of irrelevant results.

**Comment by DanTup** [comment]
SDK work is done in https://github.com/dart-lang/sdk/commit/41b5ba16290729b17af4cfeb83903e687a2d2491, but it'll need the setting exposing in the VS Code extension when that's closer to shipping.
