### ISSUE TITLE
The device selector does not show the full name of the emulators before they are launched

### ISSUE THREAD

**Issue by toby3000** [Dart-Code/Dart-Code#1904]
The previous version of the dart plugin in vs code shows the full name that i have entered in the AVD Manager e.g. "Nexus 4 API 23 Android 6". 

Now in the current version it shows only "Nexus 4" in the device selector. The full name is gone.

Why and can this please changed?

**Comment by MaikuB** [comment]
Running into a usability issue here as well. I have a number of emulators that emulate a Nexus 5X but have different versions of Android so they are give names like "Nexus 5X API <x>". When the device selection prompt appears, all of them appear as "Start Nexus 5X" with no other details to help differentiate between the emulators

**Comment by DanTup** [comment]
Thanks for the report - I'm not sure if this is related to [this change](https://github.com/flutter/flutter/pull/34785) I made recently in Flutter, or the device picker changes here.

Are you able to post a screenshot of:

1. The devices shown in the VS Code device picker
2. The output of `flutter devices` and `flutter emulator`
3. How the emulators appear in the Android Studio AVD dialog

Thanks!

**Comment by toby3000** [comment]
![2019-08-04 17_10_44-Window](https://user-images.githubusercontent.com/11464255/62425482-dab60b00-b6da-11e9-995a-72eac3323dad.png)
![2019-08-04 17_10_12-Window](https://user-images.githubusercontent.com/11464255/62425483-dab60b00-b6da-11e9-8709-50ec25ab9e89.png)
![2019-08-04 17_09_54-Window](https://user-images.githubusercontent.com/11464255/62425484-dab60b00-b6da-11e9-97aa-7738d8f2e942.png)

**Comment by MaikuB** [comment]
Mine is similar so haven't added screenshots but can do if needed. For me it occurred after updating the extension to 3.3.0. I was on stable (1.7.8+hotfix-4) before and after the update.

**Comment by DanTup** [comment]
Yeah, this does look like an oopsie in the latest changes. I'll fix, thanks!

**Comment by DanTup** [comment]
Ok, I did some digging - and I think there may be some confusion here around the new functionality. The device list that opened from clicking in the status bar used to *only* list connected devices - not emulators. For an emulator to show up here, it must have already been launched (and we'd get its name from `flutter devices`).

In the latest version, we started showing *not-launched emulators* in the list too (so you can more easily launch them). However the names of them are less useful - and that's what https://github.com/flutter/flutter/pull/34785 was for (however unfortunately that change wasn't in the latest stable Flutter release).

So, I think if an emulator is running, you'll see the name you expect. And once you get a newer Flutter (or if you switch to `dev` or `master` temporarily), you should also see the full names for not-launched emulators too.

Let me know if this doesn't make sense, or you still see bad names when using Flutter's `dev` or `master` channel and I'll take a look.

**Comment by MaikuB** [comment]
Looks good in the new stable release (1.9) :)

**Comment by MaikuB** [comment]
Actually not sure I've spoke too soon as I've never tried to do this scenario in the past, when there are no emulators running and device selection is open, I can see the full names of both emulators (note: identical to what I see in Android Studio) such that the options are

- Start Pixel 2 API 28
- Start Pixel 2 API 29

When I select to debug one of the devices, after it is launched and show the device selection menu again, the name is replaced with "Android SDK built for x86"
