### ISSUE TITLE
Right Click pubspec.yaml no longer showing context menu for packages

### ISSUE THREAD

**Issue by mayorbyrne** [Dart-Code/Dart-Code#1912]
After upgrading to 3.3.0, right-clicking a pubspec.yaml file no longer seems to show the dependencies context menu (Get Packages, Upgrade Packages). Downgrading back to 3.2.1 shows it again. Am I missing something, or have I stumbled onto a bug here?

**Comment by DanTup** [comment]
It sounds like a bug - though I'm unable to repro:

<img width="341" alt="Screenshot 2019-08-06 at 2 25 06 pm" src="https://user-images.githubusercontent.com/1078012/62543564-07daf880-b856-11e9-8afe-2e928c535be2.png">

Are there any warnings/errors in the dev console (Help -> Toggle Developer Tools -> Console tab)? Do you see the **Pub: Get Packages** command in the VS Code command palette?

**Comment by mayorbyrne** [comment]
Ah, looks like it was because I had some old folders in my workspace that had recently been removed by me. Removing the old/invalid folders seems to have fixed the issue using `3.3.0` -- you can close it out if you need to, seems like this one was mainly caused by me

**Comment by DanTup** [comment]
I don't know what your old/invalid folders were, but if they were causing the extension not to activate correctly (or similar), I'd be interested to know if it's something I could handle better.

Let me know if you think it's something I might be able to repro here (otherwise, feel free to close this!).

**Comment by mayorbyrne** [comment]
I've tried, and I simply can't replicate the issue now, so I'll close it out. If I notice it happen again, I'll let you know with more details!
