### ISSUE TITLE
Some quick-fixes doesn't create brackets

### ISSUE THREAD

**Issue by ktoosiu** [Dart-Code/Dart-Code#1923]
Hi there, I realised that somethimes when I'm using snippets like automatic overrides creation It doesn't create brackets, 
![1](https://user-images.githubusercontent.com/2962223/62919821-1cfade80-bda4-11e9-9025-6999196bff7c.PNG)
![2](https://user-images.githubusercontent.com/2962223/62919822-1cfade80-bda4-11e9-8375-125defd65935.PNG)

**Comment by DanTup** [comment]
Thanks, I've moved this to https://github.com/dart-lang/sdk/issues/37903 since the quick fixes come from the SDK. Thanks!
