### ISSUE TITLE
Debug /example if editing a package

### ISSUE THREAD

**Issue by lukepighetti** [Dart-Code/Dart-Code#1927]
Currently if you're working on a package with an `/example` folder, if you hit F5 for debug, it will show a blank `launch.json` instead of attaching to the example project. Since I don't know how to set up the `launch.json` file it would be nice if it would just automatically debug example.

**Comment by DanTup** [comment]
If you put `cwd: "example"` in your launch config, that should work.

However, it does seem like if we can detect it's a patch that looking in `example` automatically (similar to how we find other well-known entry points) is a reasonable guess.
