### ISSUE TITLE
New feature "Preview: Flutter Outline" in 3.3 is not working

### ISSUE THREAD

**Issue by winsonet** [Dart-Code/Dart-Code#1929]
I have upgrade the Dart plugin to latest version(3.3), but I can't use the new outline feature, I have set the `"dart.previewFlutterOutline": true` but nothing happen :(

![image](https://user-images.githubusercontent.com/1869995/63267806-688e1a80-c2c5-11e9-9aec-0f78f51b8773.png)
![image](https://user-images.githubusercontent.com/1869995/63267827-717eec00-c2c5-11e9-9c42-7ef1aee75570.png)

and my VSCode version is ( in MacOS ):

Version: 1.37.0
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T01:22:37.660Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

thanks!

**Comment by DanTup** [comment]
@winsonet the Flutter outline is on its own button on the Sidebar. We can't put the Flutter widgets into the standard outline view (for a few reasons, including not supporting custom icons, and not supporting node that don't also appear in the Document Symbols list).

<img width="447" alt="Screenshot 2019-08-19 at 2 18 25 pm" src="https://user-images.githubusercontent.com/1078012/63268544-4f1cac80-c28c-11e9-8aed-b43da1ba81a4.png">

Let me know if you don't have it there either.

**Comment by winsonet** [comment]
oh~~~sorry, I ignored this button, it's ok, that's working and it's great!!
Thank you so much!

**Comment by DanTup** [comment]
Great, glad you like it! 👍
