### ISSUE TITLE
find type dialog doesn't always show results

### ISSUE THREAD

**Issue by devoncarew** [Dart-Code/Dart-Code#193]
I often see cases where it runs indefinitely and doesn't show results. I don't know if we have some issue interpreting the results from the analysis server, or the server itself isn't returning results.

**Comment by DanTup** [comment]
Do you have your logging on? Is it possible to find an example?

I tend to always keep my logging on, so if something happens like this I always have it to hand!

**Comment by devoncarew** [comment]
I'll turn it on and see if I can narrow the issue down -

**Comment by DanTup** [comment]
I haven't seen it, but I'm probably using Dart Code the least out of anyone with it installed right now!

IIRC, I put code in to merge results (wait for two promises); seems like the sort of thing that could go wrong (I think you may have mentioned an issue like this before, but maybe couldn't repro).

If you can see any obvious pattern, or it's on a codebase I can clone and test with, let me know and I'm happy to dig into it.

**Comment by DanTup** [comment]
@devoncarew Have you seen this at all since?

**Comment by devoncarew** [comment]
Not, not since the initial report.

**Comment by DanTup** [comment]
Ok, gonna close this as no-repro, but if you see it again and can get a log, do post back!
