### ISSUE TITLE
Missing code actions for refactoring key binds

### ISSUE THREAD

**Issue by marko** [Dart-Code/Dart-Code#1931]
The keybinding below worked well until recently. Now it displays a "No code actions available" message.

```
{
    "key": "cmd+. w",
    "command":  "editor.action.codeAction",
    "args": {
         "kind": "refactor.flutter.wrap.generic"
    },
    "when": "editorLangId == 'dart' && dart-code:anyFlutterProjectLoaded && editorHasCodeActionsProvider && editorTextFocus && !editorReadonly"
}
```

**Comment by DanTup** [comment]
Do the code actions appear in the normal editor list (eg. with `Cmd`+`.`)? This sounds a bit like #1926 which I can't reproduce. Could you provide the info asked for [here](https://github.com/Dart-Code/Dart-Code/issues/1926#issuecomment-522489251)?

**Comment by marko** [comment]
They appear and work in the normal list. 

Flutter 1.9.0
VS Code 1.37.1
Dart Code 3.3.0
No errors in console

**Comment by DanTup** [comment]
Ok, not the same. I can reproduce however. W're definitely returning matching code actions:

<img width="446" alt="Screenshot 2019-08-19 at 4 22 51 pm" src="https://user-images.githubusercontent.com/1078012/63277696-b1ca7400-c29d-11e9-9bff-97ed07fe9577.png">

But they don't show up in the list... I'll do some digging.

**Comment by DanTup** [comment]
This looks like a VS Code bug to me, so I've opened https://github.com/microsoft/vscode/issues/79455 with a repro hoping for some input.

**Comment by DanTup** [comment]
This turned out to be my bug... There's filtering in code actions (to avoid requesting unrelated code actions) but it didn't correctly handle when the filter was a sub-kind of Refactor (eg. when VS Code asked for `refactor`s it worked, but when asked for `refactor.foo` it did not.
