### ISSUE TITLE
Feature Request: Code Action to create constructor 

### ISSUE THREAD

**Issue by kjeremy** [Dart-Code/Dart-Code#1936]
I have a lot of flutter widgets that could have `const` constructors and it would be nice to go to the class definition and have a code action that inserted a constructor. If there is a base class it could automatically called `super` with stubbed arguments mirroring the base class's constructor.

For instance (where <|> is the cursor)

```dart
class Splash extends StatelessWidget {
  <|>

  @override
  Widget build(BuildContext context) {
    return const Material(child: Center(child: Text("Splash Screen")));
  }
}
```

After applying the action:

```dart
class Splash extends StatelessWidget {
  const Splash({ Key key }) : super(key: key);<|>

  @override
  Widget build(BuildContext context) {
    return const Material(child: Center(child: Text("Splash Screen")));
  }
}
```

**Comment by DanTup** [comment]
I thought there was already something like this, but I can't seem to find anything 🤔

The code actions all come from the analysis server, so this would need to be implemented there (they're called "assists" in the SDK). Would you mind opening an issue at https://github.com/dart-lang/sdk with the details from above and posting the link back here? Thanks!

**Comment by kjeremy** [comment]
Issue in SDK repo https://github.com/dart-lang/sdk/issues/37921

**Comment by DanTup** [comment]
Great, thanks! I'll close this as upstream, since if it's implemented there it'll just appear in VS Code without any additional work - it's good to have the link to the issue here in case others stumble across it and want to 👍 it though.
