### ISSUE TITLE
Unable to find reference & find definition

### ISSUE THREAD

**Issue by mikhdzam** [Dart-Code/Dart-Code#1938]
Hi, I'm experiencing this issue. I've tried to find it on setting but got no solution. I've no idea how to get this working. Please help me?

Thanks

**Comment by DanTup** [comment]
You shouldn't need to do anything to make this work, just choosing the options from the context menu or pressing the keybindings should work. If this isn't the case, please provide information on what you're seeing, and an example of code you're trying it in.

You can also run [**Dart: Capture Logs**](https://dartcode.org/docs/logging/#capture-logs-command) command to capture an Analysis Server log that might be useful of it's not working. Thanks!

**Comment by mikhdzam** [comment]
Hi,
I've tried **Dart: Capture Logs** but vscode says **"no commands matching"**. No context menu available for that functionality, only "change all occurrences", cut, copy, paste, "commands palette". I've tried also F12 and alt+F12 but nothing came up. I've also restarted the VS Code many times. The version installed is 3.3.0. Any other thing I can try?

**Comment by DanTup** [comment]
It sounds like the extension hasn't activated correctly. Have you opened a folder that contains Dart files, or only a single loose Dart file (that's not currently supported).

If you've opened a folder, then check Help -> Toggle Developer Tools and click the Console tab to see if there are any errors about failing to activate.

**Comment by mikhdzam** [comment]
I just tried uninstalling & reinstalling the extension, but the problem still there. There is only one command available: "Dart: New Project". The following some details about the VS Code version.

Version: 1.37.1 (user setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

One error from Console:
notificationsAlerts.ts:40 Could not find a Flutter SDK. Please ensure flutter is installed and in your PATH (you may need to restart).

Does dart extension require flutter SDK?

Text coloring appears after reinstalling the dart extension. And currently I open folder I cloned from github.

**Comment by DanTup** [comment]
If the SDK is not found, it should also show a toast notification with a "Locate SDK" button to help you find it (however there's an issue with that button in the current release).

> Does dart extension require flutter SDK?

No, it doesn't. But if the project you opened looks like a Flutter project, we will look for a Flutter SDK.

If you're doing standard Dart, please make sure the Dart SDK's `bin` folder is in your `PATH`. You will likely need to reboot after doing that as Windows doesn't seem to apply PATH changes to things launched from explorer. Then make sure the folder you open does not reference Flutter in its `pubspec.yaml` and let me know if that works. Thanks!

**Comment by mikhdzam** [comment]
On my 2nd laptop I can peek definition that located in the same file, but when the definition is in other file it doesn't work. Is it normal or it should also be able to show the definition that is located in other file?

Back to my 1st laptop, the project I clone can be found here: https://github.com/SAGARSURI/Goals.
I will try to install Flutter SDK, set the PATH, and reboot, and then will let you know the result.

Thanks! :)

**Comment by mikhdzam** [comment]
Update on my 2nd laptop, now the peek definition is working for other files also. I'm not sure what's the problem. My VS Code showed me toast notification to download/install/update (I forgot) the package and I clicked the button, and then I updated the VS Code, rebooted the VS Code, and it's now working on my 2nd laptop.

**Comment by mikhdzam** [comment]
Hi, back to my 1st laptop. I've installed Flutter SDK, set the PATH to bin folders, rebooted Windows, run "flutter doctor" that automatically install Dart SDK, and then rebooted the VS Code, and finally it's working now. I got the same toast notification from Dart extension "Some packages are missing or out of date, would you like to get them now?", but I ignored it, and it's still working.

**Comment by DanTup** [comment]
> finally it's working now

Great! It was probably just a `PATH` issue then. The general advice on Windows is to reboot after changing `PATH` to ensure you nothing is getting the old version.

> I got the same toast notification from Dart extension "Some packages are missing or out of date, would you like to get them now?", but I ignored it, and it's still working.

This prompt is slightly aggressive - it may sometimes appear when it's not needed (it checks whether `pubspec.yaml` is newer than `.packages`), but if you click it then it should run `pub get` (or `flutter packages get` if it's a Flutter project) and then you won't see it until you modify the pubspec again.

If you have any other issues, please shout!

**Comment by mikhdzam** [comment]
Alright, great support! Thanks!
