### ISSUE TITLE
flutter_test any from sdk which doesn't exist (the Flutter SDK is not available), version solving failed.  Flutter users should run `flutter pub get` instead of `pub get`.

### ISSUE THREAD

**Issue by Balajiomsakthi** [Dart-Code/Dart-Code#1939]
Hi, I tried to delete the bin/cache/ directory in my flutter. After that I am facing this issue. I can't able to run my app or start or stop.

![Screenshot 1941-05-31 at 13 57 52](https://user-images.githubusercontent.com/24551909/63499181-f72cb280-c4e4-11e9-8202-ecbd7dbefe71.png)

**Comment by DanTup** [comment]
This repository is for the VS Code extension, but this looks like an IntelliJ issue. It seems like something is running `pub get` that should be running `flutter packages get`, but I don't know enough about the IntelliJ plugin to know why that is.

I'll move this to the other repo where someone may be able to investigate.

/move flutter/flutter-intellij
