### ISSUE TITLE
Less suggestions in refactor menu while condition exists in List

### ISSUE THREAD

**Issue by mirkancal** [Dart-Code/Dart-Code#1941]
Refactor menu shows less when condition exists in the list as seen below.

With condition
![When condition exists](https://user-images.githubusercontent.com/26160059/63517548-d883e700-c4f7-11e9-999f-bd887a595673.png)

Without condition
![Without condition](https://user-images.githubusercontent.com/26160059/63517593-e76a9980-c4f7-11e9-888a-002487056a6a.png)

**Comment by DanTup** [comment]
Thanks for the report! These come from the analysis server, so I've moved this to the SDK repo to be looked at:

https://github.com/dart-lang/sdk/issues/37951
