### ISSUE TITLE
Add a setting for using --androidx flag when creating a new Flutter project

### ISSUE THREAD

**Issue by nickmeinhold** [Dart-Code/Dart-Code#1943]
It seems like `flutter create` will [use androidx by default](https://github.com/flutter/flutter/issues/27792) at some stage but in the meantime it would be great to have a setting we can use.  Thanks!

**Comment by DanTup** [comment]
There's a new beta build here if you'd like to try it out:

https://github.com/Dart-Code/Dart-Code/releases/tag/v3.4.0-beta.2

Release notes aren't ready yet, but the list of issues here covers what's in it:

https://github.com/Dart-Code/Dart-Code/milestone/97?closed=1

If you try it out, let me know if you hit any issues.
