### ISSUE TITLE
Refactoring to extract final variable

### ISSUE THREAD

**Issue by audkar** [Dart-Code/Dart-Code#1949]
In our code base we prefer to have all variables with `final` modifier. 
It would be super helpful if `Extract local variable` would add `final` with every refactoring.

- Add vscode preference for `Extract local variable`
or
- Add separate refactoring `Extract final variable`

Thought I am not sure how to achieve this in most elegant way without overfilling refactoring menu with similar options or adding very rarely used preference. :)

In Intellij it is possible to add options for refactoring :)
![image](https://user-images.githubusercontent.com/1947112/63772211-4a39a780-c8e1-11e9-9cc9-d6f41ffeb974.png)

**Comment by DanTup** [comment]
These refactors come from the SDK's analysis server, so this would need to be first implemented there (https://github.com/dart-lang/sdk).

> In Intellij it is possible to add options for refactoring :)

In the screenshot this shows `final` - does IntelliJ already support this?

**Comment by audkar** [comment]
> In the screenshot this shows final - does IntelliJ already support this?

No. This is for Java :)

> These refactors come from the SDK's analysis server

Ohhh. Sad new then :)

**Comment by DanTup** [comment]
> No. This is for Java

Ah, got it =D

> Ohhh. Sad new then

It means there's a longer trip, but it doesn't mean it can't happen - it's worth raising the request over there and posting the link back here and people can add 👍 if it's something they'd like to see supported.

It's possible it could also do this automatically based on lints (for ex. there's [this lint](https://dart-lang.github.io/linter/lints/prefer_final_fields.html) which I think is only fields, but having a similar one for local variables and using as a hint that users might prefer final fields might work - @pq wdyt?)/

**Comment by DanTup** [comment]
Cool, thanks! I'll close this since there's nothing to do here. @audkar you may wish to subscribe to the SDK issue for updates.

**Comment by DanTup** [comment]
The SDK was updated to use `final` when the `prefer_final_locals` lint is enabled so this should just start working for you in an upcoming release 👍
