### ISSUE TITLE
uri doesnt exist

### ISSUE THREAD

**Issue by ranabhawana** [Dart-Code/Dart-Code#1954]

**Comment by DanTup** [comment]
Can you provide more information about the problem? Where are you seeing this message, for example?

**Comment by nabiloo19** [comment]
![FLUTTER1](https://user-images.githubusercontent.com/45761185/64044000-6dc55200-cb6e-11e9-89ac-62d664c55954.png)
I found this problem once I forked and cloned a git repo ..

**Comment by nabiloo19** [comment]
It also states that there's no package.json

**Comment by DanTup** [comment]
@nabiloo19 this will happen after opening a new project if you haven't run **Flutter: Get Packages**. You should be prompted to do this when opening the project though (a toast popup in the bottom right corner).

Did you see this? Did it help?

@ranabhawana is your issue the same?

**Comment by DanTup** [comment]
> It also states that there's no `package.json`

Can you provide more info? `package.json` is for NodeJS, not Dart. Where do you see this?

**Comment by DanTup** [comment]
Please let me know if you're still seeing this and can provide more info requested above. Thanks!
