### ISSUE TITLE
error when importing dart:ffi

### ISSUE THREAD

**Issue by imerkle** [Dart-Code/Dart-Code#1956]
```
Target of URI doesn't exist: 'dart:ffi'.
Try creating the file referenced by the URI, or Try using a URI for a file that does exist.dart(uri_does_not_exist)
```

`flutter run` works

**Comment by mit-mit** [comment]
@imerkle which version of flutter/dart are you using (what's the output of `flutter --version`)?

**Comment by DanTup** [comment]
I think this is probably:

- https://github.com/dart-lang/sdk/issues/37141
- https://github.com/flutter/engine/pull/10282

The fix hasn't made the beta or stable channels of Flutter yet, but should work fine on `dev`/`master` (I tried it with the SDK in current master and don't see any issues).

**Comment by imerkle** [comment]
might be that i switched to dev but didn't upgrade

**Comment by ir2pid** [comment]
I'm facing this issue after updating flutter to 2.0.
I'm on dev channel, what am I doing wrong?

```
Flutter 2.1.0-10.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision cc9b78fc5c (11 days ago) • 2021-02-25 13:26:03 -0800
Engine • revision a252ec09b7
Tools • Dart 2.13.0 (build 2.13.0-77.0.dev)
```

**Comment by DanTup** [comment]
@ir2pid could you attach a screenshot showing exactly what you're seeing? Please include the import statement, the Problems window showing the full error and the status bar including the SDK version VS Code has picked up, like:

<img width="1054" alt="Screenshot 2021-03-08 at 18 29 04" src="https://user-images.githubusercontent.com/1078012/110364905-45a89000-803c-11eb-8265-a2d9b05d15b4.png">

Thanks!
