### ISSUE TITLE
Ability to use `Flutter: New Project` offline

### ISSUE THREAD

**Issue by geneus** [Dart-Code/Dart-Code#1957]
Hello team.

I'm currently struggling to configure the extension to prefer using the cache over hitting the network due to a spotty connection.

### Current workflow:
Creating a project with the `New Project` command keeps retrying `pub get` indefinitely. Due to unresolved dependencies, the UI hangs until the user cancels. The last time I checked, it retried 236 times before I quit. Running `pub get` via the `Get Packages` command produces the same results.

### Expectation:
Hit the pub registry, but resolve to cache if/when packages have already been cached as per CLI or 
Exit after x number of retries

### Current workflow:
Cancelling the running command seems to only dismiss the toast as it still attempts to get packages.

### Expectation:
Cancel the running command as the action implies or 
Check cache then quit if not resolved

Initially thought `"dart.pubAdditionalArgs": [ "--offline" ]` or `"dart.flutterAdditionalArgs": [ "--offline" ]` would produced the desired outcome but that is not the case. The settings are saved but do not seem to do anything. A setting similar to [this previous suggestion](https://github.com/Dart-Code/Dart-Code/issues/618#issuecomment-368351176) is an ideal method for those who want to configure offline usage. Either that or passing the `--offline` flag to `dart.pubAdditionalArgs` / `dart.flutterAdditionalArgs`, but I prefer the latter as they are already implemented settings.

PS: Although the [`dart.flutterAdditionalArgs` setting](https://dartcode.org/docs/settings/#dartflutteradditionalargs) is documented, VS Code says it's an unknown configuration setting. 

Cheers!

**Comment by DanTup** [comment]
Would a `dart.flutterCreateAdditionalArgs` setting that you can add `--offline` do what you want?

> PS: Although the `dart.flutterAdditionalArgs` setting is documented, VS Code says it's an unknown configuration setting.

This is a new setting in the upcoming version (you can get a beta from https://github.com/Dart-Code/Dart-Code/releases). I updated the website in preparation, not expecting anyone to find it and try and use it before this release goes out - sorry 😄

(though FWIW, adding `--offline` there will probably result in many other things failing due to not understanding the flag).
