### ISSUE TITLE
Smarter code branching detection

### ISSUE THREAD

**Issue by dancojocaru2000** [Dart-Code/Dart-Code#1964]
Not really an important thing, but when detecting if the function doesn't return, detecting code branching could be smarter.

![Code screenshot describing how if else branches cover all cases, therefore the need for an extra return outside of them is unnecessary](https://user-images.githubusercontent.com/9626761/64220780-de4fd400-ceca-11e9-8966-152eba421953.png)

As you can see, the if else if else if branches cover all cases. However, in order to satisfy the "function doesn't return", the last branch needs to be an else.  
I think saying `else` rather than describing all cases takes out of the readability. I think Dart Code should be able to understand that I'm covering all possible cases of the branch, therefore not needing an extra return.

**Comment by DanTup** [comment]
The analysis in Dart-Code comes from the SDK's analyzer, so this would need to be raised/fixed at https://github.com/dart-lang/sdk. I don't know how feasible it is to handle though.

In the meantime, I'd probably move the `== 0` to the `else` and write it like this to avoid it:

```dart
if (delay > 0)
  return Text("...");
else if (delay < 0)
  return Text("...");
else
  return Container();
```
