### ISSUE TITLE
Wrong indentation when using Wrap with new widget

### ISSUE THREAD

**Issue by dancojocaru2000** [Dart-Code/Dart-Code#1965]
When using "Wrap with new widget", the indentation is doubled on the next line.

![image](https://user-images.githubusercontent.com/9626761/64221033-bb71ef80-cecb-11e9-8b16-619d993af450.png)

**Comment by DanTup** [comment]
Unfortunately this is a VS Code bug (but has been tagged as a feature):

https://github.com/microsoft/vscode/issues/63129

I already have an issue open tracking it, so I'll close this as a dupe of https://github.com/Dart-Code/Dart-Code/issues/584. Feel free to add a 👍  and/or comment to the VS Code issue - it's not clear why it won't be fixed, there has been no response to my last few comments :(

**Comment by dancojocaru2000** [comment]
VS Code seems to have a tradition already to mark bugs as features because VS Code is definitely smarter than the language server...
