### ISSUE TITLE
Trying to run a group of tests fails with "Unable to start test for node with no test or group name"

### ISSUE THREAD

**Issue by toddabel** [Dart-Code/Dart-Code#1971]
Trying to run a group of tests by clicking on Dart & Flutter in the VS Code test section fails with a popup notification of "Unable to start test for node with no test or group name".

![image](https://user-images.githubusercontent.com/4468495/64296165-2cdf8b80-cf28-11e9-878b-f73470dc5584.png)
![image](https://user-images.githubusercontent.com/4468495/64296183-3ff25b80-cf28-11e9-9156-f5593c02ba9a.png)

Dart extension: 3.4.1
Flutter extension: 3.4.1
VSCode: 1.3.8
Flutter : 1.7.8+hotfix4

**Comment by DanTup** [comment]
Thanks for the report! This is fixed for the next version - there's a build here that contains the fix if you want to use it:

https://github.com/Dart-Code/Dart-Code/releases/tag/v3.5.0-alpha.1

Notes on installing a preview release are [here](https://dartcode.org/docs/installing-a-preview-release/). You'll be automatically moved back to stable when the next release is published (if you have VS Code set to auto-update extensions).
