### ISSUE TITLE
automatically run flutter generate

### ISSUE THREAD

**Issue by szotp** [Dart-Code/Dart-Code#1974]
I would like to have something similiar to `promptToRunPubGet` that asks user to run `flutter generate`, maybe it could be even done in the same operation?

1. User agrees to download packages.
2. After packages have been downloaded, DartCode checks if `builders:` option exists in pubspec.
3. If that option exists, it runs `flutter generate` and updates the prompt message.
4. After that we assume that, assuming #1970 was fixed, the error will disappear.

The goal is: a newbie clones the project, follows prompts, and has project that compiles and shows no errors.

Example project is available here: https://github.com/Dart-Code/Dart-Code/issues/1970#issuecomment-528333884

**Comment by DanTup** [comment]
@jonahwilliams is there a good way to tell if `flutter generate needs running? For `pub get` we check if `pubspec.yaml` has a newer timestamp than `.packages` (or that `.packages` doesn't exist), though I presume in this case changes to any source files could potentially invalidate the generated code? (I'm not very familiar with `flutter generate` so if there are docs anywhere, let me know!).

**Comment by jonahwilliams** [comment]
flutter generate is always run automatically by `flutter run`, so there shouldn't be any required action. In general, there isn't a good way to know besides running it though, as both the set of builders and the code they run on can have changed

**Comment by DanTup** [comment]
I'm not very familiar with the type of code being generated here. The thing we were trying to fix was analysis errors caused by `flutter generate` having not been run (eg. you open the project in the IDE, and it has errors that would be fixed by running `flutter generate`).

Can you think if any better way to handle this?

**Comment by jonahwilliams** [comment]
In general this is a big problem with source generation, often times code will be importing/interacting with other generated source code. There isn't much that we can do besides run flutter generate again.

**Comment by DanTup** [comment]
Sure - but it'd be good if we could detect it and guide the user. When cloning someone elses repo and opening it, it'd be nice to get you to 0 errors without you having to know to run commands first.

Maybe a slightly simpler challenge - can we tell whether

- a) the project uses generation
- b) it's *never*  been previously run

This would at least capture the "newly cloned project" case even if we can't detect stale generated files. Does `flutter generate` leave any well-known files around?

**Comment by jonahwilliams** [comment]
You can tell if it has run before by checking if there is a `.dart_tool/build/generated` directory in the project root.

**Comment by jonahwilliams** [comment]
And for flutter generate to work, the user must have at least one `builders: ` entry in the pubspec.

**Comment by DanTup** [comment]
Great, that sounds like it would allow us to prompt in the fresh-repo case at least. Thanks!

**Comment by szotp** [comment]
Closing this because flutter generate will be removed :(
