### ISSUE TITLE
PATH Flutter not found  issue on vscode fix on ubuntu 18.04 (Bionic Beaver)

### ISSUE THREAD

**Issue by isagoutama** [Dart-Code/Dart-Code#1979]
For future visitors :)

I had the same problem, in my Terminal flutter doctor or in general flutter was recognized, but VSCode couldn't recognize my SDK location so flutter doctor for instance didn't work.

The first thing to do is to follow the steps in flutter documentation: Flutter Doc
If it didn't work, change the environment variables directly.

`sudo nano /etc/environment`

Now add the location of the bin folder of your flutter SDK, The folder that you downloaded from here.

For example, you extracted it here: /Home/User/Software

Add /Home/User/Software/flutter/bin to the PATH variable. Paths are separated by a colon(:)

After a few solutions I tried, this one worked.

source : [https://stackoverflow.com/questions/56845375/vscode-could-not-find-a-flutter-sdk](url)

**Comment by DanTup** [comment]
The usual problem here is that people set `PATH` in a location that doesn't expose it to VS Code, and therefore the extension can't find it. The reason it works in the built-in terminal is that it runs your terminal startup scripts, which set the `PATH`.

The simplest fix is to just click the **Locate SDK** button on the dialog and browser to the SDK. This will save it in the `dart.sdkPath`/`dart.flutterSdkPath` user setting which is always searched.

Hope this helps!
