### ISSUE TITLE
Everytime when saving changes to pubspec.yaml asks if packages should be gotten 

### ISSUE THREAD

**Issue by escamoteur** [Dart-Code/Dart-Code#1988]
Normally this Dialog that asks should only appear when opening a project.

Currently if you have project with a nested `example` project it will query every time you change any pubspec file

**Comment by DanTup** [comment]
I haven't been able to repro this - I have an `example` sub-folder, with a `pubspec.yaml` in it, but editing either pubspec only runs `pub get` for that particular project.

Anything else about your project that might be relevant? Does it repro if you run **Dart: New Project** , then copy paste a copy of itself into an `example` folder?

I tried it when `example` has no `.packages` or `pubspec.lock` files too, thinking that might trigger it, but I still see the same.

**Comment by escamoteur** [comment]
I just tried it again, it only happens when I open the project with a workspace.
This is the project https://github.com/escamoteur/rx_widgets where I see it

**Comment by DanTup** [comment]
Got it, thanks! It happens when you have a project that's in "two workspace folders" (here example is in its own, but also as a child of the parent folders workspace) so we found it twice, and thought there were multiple folders we needed to run for.
