### ISSUE TITLE
Error in latest insider

### ISSUE THREAD

**Issue by octref** [Dart-Code/Dart-Code#199]
Just FYI:

This error is for opening angular.dart's `Filter.dart` file:

![image](https://cloud.githubusercontent.com/assets/4033249/19782903/bb5a06e8-9c44-11e6-869b-0c4cb846aec2.png)

This is for opening dart-lang/sdk's `future.dart` file:

![image](https://cloud.githubusercontent.com/assets/4033249/19782982/0775712a-9c45-11e6-970b-6651dbf5052a.png)

**Comment by DanTup** [comment]
Thanks for reporting, I'll take a look tomorrow. Very strange issue; code looks like this:

```ts
function checkIsDevelopment() {
	return extensionVersion.endsWith("-dev") || env.machineId == "someValue.machineId";
}
```

Where env is imported from `vscode`:

```ts
import { env, workspace, window, Position, Range, TextDocument, commands, Uri } from "vscode";
```

Is it possible something broke in Code? I wouldn't have expected `env` to ever be `undefined`?

**Comment by DanTup** [comment]
Btw, how did you get the dev tools? I didn't realise they would work (I did try pressing `F12` previously but it didn't work?)

**Comment by DanTup** [comment]
And finally.. was this the latest released version of Dart Code (0.13)?

**Comment by octref** [comment]
It is 0.13.

You need help -> toggle developer tools.

Actually Python extension failed to activate too. I think it's our issue. Let me take a look.

**Comment by octref** [comment]
Tracked at https://github.com/Microsoft/vscode/issues/14632

It's not your extension's fault. Python extension also failed. Thanks for your quick response!

**Comment by DanTup** [comment]
Great, thanks for investigating!
