### ISSUE TITLE
Debugger missing inner structure of objects

### ISSUE THREAD

**Issue by treyerl** [Dart-Code/Dart-Code#1992]
When debugging an aqueduct.io project in VSCode I miss a few values as shown in the screenshot below:

<img width="336" alt="Bildschirmfoto 2019-09-15 um 09 14 15" src="https://user-images.githubusercontent.com/1533260/64918063-3aeba280-d799-11e9-8be5-e2db7c7da014.png">

When debugging with IntelliJ it works fine, which might be the reason the creators of aqueduct recommend IntelliJ. I created a demo project to test with: https://github.com/treyerl/hello

**Comment by DanTup** [comment]
The sample repro looks somewhat complicated - it requires setting up a database. Is it possible to reproduce this with a smaller example that doesn't have this?

**Comment by rajeshzmoke** [comment]
i get the same issue in Flutter project

Vscode version
```
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:31:32.854Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.6.0
```
<img width="977" alt="Screenshot 2019-09-22 at 1 04 53 AM" src="https://user-images.githubusercontent.com/30038668/65378391-411bda80-dcd5-11e9-8748-8c0ac5ffb6f6.png">

flutter doctor -v
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.5 18F132, locale en-IN)
    • Flutter version 1.9.1+hotfix.2 at /Users/rajeshkumar/Desktop/flutter
    • Framework revision 2d2a1ffec9 (2 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/rajeshkumar/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/rajeshkumar/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • HighPeaksw iPhone X • 76fd22d0d6fe8432a90a895351b60bd1d159e8ef • ios • iOS 12.4.1

• No issues found!
```

**Comment by DanTup** [comment]
I can't reproduce this, everything seems to work correctly for me:

<img width="423" alt="Screenshot 2019-10-01 at 11 55 32 am" src="https://user-images.githubusercontent.com/1078012/65956500-6b426a80-e442-11e9-9aa6-3587d35b477f.png">

Can anyone provide a small repro project with exact instructions on where they're breaking so I can try with the same code? A log file would also help (run **Dart: Capture Logs** and tick only the Observatory/Debugger option).

**Comment by rajeshzmoke** [comment]
[Dart-Code-Log-2019-09-03 11-25-43.txt](https://github.com/Dart-Code/Dart-Code/files/3679671/Dart-Code-Log-2019-09-03.11-25-43.txt)

Will try to reproduce in a new project but for now I've attached log

**Comment by DanTup** [comment]
@rajeshzmoke thanks - is it possible to get a log that includes the whole debug session (start logging before launching the app)? The log will be much larger, but there are things missing from this one that might be useful (such as if there are multiple isolates spawning).

A repro I can run without dependencies would definitely help though - I haven't seen this error before and I'm not sure what's different in your setup.

**Comment by treyerl** [comment]
> The sample repro looks somewhat complicated - it requires setting up a database. Is it possible to reproduce this with a smaller example that doesn't have this?

I created a [version](https://github.com/treyerl/hello/tree/mockup) of my sample repro that doesn't require postgres.

**Comment by DanTup** [comment]
@treyerl Thanks! I was able to track down the issue. We're hitting an error when looking at what one the fields (`_lastController`) but weren't handling it, so it was failing the whole request for the fields. If I handle errors for each field individually, then this doesn't happen:

![Screenshot 2019-10-03 at 3 31 41 pm](https://user-images.githubusercontent.com/1078012/66136213-037f5180-e5f3-11e9-96c5-957e11237931.png)

There are quite a few code paths here so I'll go through them all and check there aren't other places that might do this too.

**Comment by DanTup** [comment]
I made a preview build with this fix if you want to try it (otherwise it's the same as v3.5.1):

https://github.com/Dart-Code/Dart-Code/releases/tag/v3.6.0-alpha.1
