### ISSUE TITLE
Plugin can't handle generic function aliases properly

### ISSUE THREAD

**Issue by lucasccustodio** [Dart-Code/Dart-Code#1993]
After testing with the new syntax for generic function type alias I found that the plugin can't handle most scenarios where it's applied and revealed some inconsistencies on how it deals with type inference for generics, sometimes displaying signatures correctly but making parameters dynamic and treating as Object, ignoring completely what type was inferred and failing to propagate to parameters (return value works as expected) or showing confusing errors like 'type' is not a 'type'.

```dart
main() {
  var test;

  /*test = Test(<Any>(value) => Any<int>()); //'Any' isn't a function.
  //Try correcting the name to match an existing function, or define a method or function named 'Any'.
  */

  test = Test(
      <Any>(value) => value,
      (value2) =>
          0); // valid, but value2 is dynamic despite signature correctly displaying as int.

  /*
  test = Test(
      <Any<int>>(value) => value,
      (value2) =>
          0); // expected to find >
  */

  test = Test(
      <int>(value) => value,
      (bool value2) =>
          false); // valid, both values match signature and T is inferred as bool

  /* test = Test<int>(<int>(value) => value + 1); value is correctly inferred as int, but analyzer says operator + isn't defined for class Object */

  /*
  test = Test(
    <bool>(value) => false,
    (value2) => false,
  ); // invalid, The return type 'bool' isn't a 'bool', as defined by anonymous closure.
  */

  /*
  test = Test(
  <int>(int value) => 0,
  ); //invalid, The return type 'int' isn't a 'int', as defined by anonymous closure. */
}

class Any<T> {
  Any();
}

typedef TestFn = T Function<T>(
    T value); // new syntax for generic function type alias

typedef TestFn2<T> = T Function(T value); // old syntax

class Test<T> {
  final TestFn fn;
  final TestFn2<T> fn2;

  Test(this.fn, [this.fn2]);
}
```

**Comment by DanTup** [comment]
@bwilkerson I'm not very familiar with these syntax changes - are you a good person to comment on this? I've not seen syntax like `<bool>((value) => false` before, though it does seem strange to me that this code:

```dart
var test1 = Test(
  <bool>(value) => value,
  (bool value2) => false,
);

var test2 = Test(
  // invalid, The return type 'bool' isn't a 'bool', as defined by anonymous closure.
  <bool>(value) => false,
  (bool value2) => false,
);
```

products the error that it does.

**Comment by bwilkerson** [comment]
I think there might be some confusion here. First, on a minor note, the new syntax is

> typeAlias ::= typedef typeIdentifier typeParameters? ‘=’ functionType ‘;’

Both `TestFn` and `TestFn2` are using the new syntax. The old syntax, which is still valid, is

> typeAlias ::= typedef type? identifier formalParameterPart ‘;’

`TestFn2`, for example, could be written using the old syntax as
```
typedef T TestFn2<T>(T value);
```

Second, you might be misunderstanding what the `<Any>` in `<Any>(value) => value` is doing. It is actually a type _parameter_, not a type _argument_. That is, it defines a new type parameter named `Any`; it doesn't refer to the class named `Any`. What you wrote is equivalent to writing `<S>(value) => value` (equivalent in the sense that if you replaced the two the semantics would remain unchanged).

Third, type inference is inferring the type argument `T` that is defined by the class `Test` in the constructor invocation. It isn't, and I believe it isn't suppose to be, inferring the type of `value2`. Inference will infer the types of local variable, for example, when there is an initializer (in `var x = 0`, the type of `x` will be inferred as `int`), but won't infer a type without an initializer (as in the case of this parameter). When you hover over `Test` in that constructor invocation what you're seeing is the result of replacing all occurrences of `T` in the constructor's signature with `int`.

So the compiler knows that the type of the second parameter is `int Function(int)`, and that the type of the argument is `int Function(dynamic)` and will compare the two to determine whether the argument is valid (which it is).

Hope that helps.

**Comment by lucasccustodio** [comment]
I see, thanks for clarifying that, I'll close the issue now as there's nothing to be done here, thanks again.
