### ISSUE TITLE
Hot Restart doesn't resume debugger state

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#1994]
See https://github.com/flutter/flutter/issues/13396#issuecomment-531249556

When we handle Hot Restart, we never tell VS Code we've continued, so it gets stuck in a pause state.

**Comment by DanTup** [comment]
@escamoteur @nickmeinhold

Alpha build here if you want to try it out to ensure it solves all your issues:

https://github.com/Dart-Code/Dart-Code/releases/tag/v3.5.0-alpha.3

**Comment by escamoteur** [comment]
Tomorrow 😁Am 16.09.2019 17:23 schrieb Danny Tuppeny <notifications@github.com>:@escamoteur @nickmeinhold
Alpha build here if you want to try it out to ensure it solves all your issues:
https://github.com/Dart-Code/Dart-Code/releases/tag/v3.5.0-alpha.3

**Comment by maks** [comment]
@DanTup and @escamoteur thanks for following up on this! 
Sorry I didnt follow up my original comment on 13396. I'm pretty sure this is the issue I was seeing, I'm trying out the alpha.3 build now.

**Comment by szotp** [comment]
Issue persists if the breakpoint was to be reached multiple times, here is minimal sample:

```dart
import 'package:flutter/material.dart';

void main() {
  foo();
  foo();
  runApp(SizedBox());
}

void foo() {
  // put breakpoint here
  print('foo');
}
```

Tested on stable
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.2 19C57, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[!] Android Studio (version 3.6)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.44.0)
[✓] Connected device (1 available)
```

And master
```
[✓] Flutter (Channel master, v1.18.0-5.0.pre.46, on Mac OS X 10.15.2 19C57, locale en-GB)
```

Should I create ticket here or in flutter repo?

**Comment by DanTup** [comment]
@szotp please create an issue here, including exact details of the actions you're performing. Thanks!
