### ISSUE TITLE
An unknown error occurred. Please consult the log for more details.

### ISSUE THREAD

**Issue by ggherghelau** [Dart-Code/Dart-Code#1998]
Issue Type: <b>Bug</b>

I get this error when I try to create an emulator 

Extension version: 3.4.1
VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (8.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>

**Comment by DanTup** [comment]
Could you provide a screenshot of where you're seeing this error? Thanks!

**Comment by DanTup** [comment]
Please let me know if you're still seeing this and can provide more info requested above. Thanks!
