### ISSUE TITLE
Swapping Flutter SDKs via IDE doesn't work with web builds.

### ISSUE THREAD

**Issue by gskinner** [Dart-Code/Dart-Code#2012]
I just got off a chat with @DanTup, who asked me to file an issue on this.
Set up:
I have three Flutter SDKs installed:
/stable - my main SDK, which my PATH points to
/ dev - downloaded from https://flutter.dev/docs/development/tools/sdk/releases
/master - checked out via git

I want to be able to use the stable SDK for my mobile app, and the dev SDK for playing around with flutter web.

If I use `flutter channel dev` to change my main SDK, and then debug a web project, then it will compile and launch correctly.

However, if my main SDK is on the `stable` channel, and I use the SDK chooser in VSCode (bottom bar) to select the `dev` channel SDK, then it will generate the following errors when I debug:
`Error: Error when reading '../../_SDKs/dev/packages/flutter_tools/.packages': No such file or directory`

I checked, and that file does not exist. It _does_ exist in my main SDK if I use `flutter channel` to swap it to dev. I did run 'Flutter: Run Flutter Upgrade` against the /dev SDK, but that didn't fix anything. Both are SDK v1.10.4.

Given all of that, I'm not sure if this is an issue with the VSCode plugin, the package from the SDK download page, or if I should be running some command against the downloaded SDK in order to generate the `.packages` file.

**Comment by gskinner** [comment]
Ok. I got it working by copying over the version of the SDK pulled by using `flutter channel dev`. So it appears it is _probably_ a problem with the version distributed on the releases page.

I'll leave this open for review in case it's a symptom of another problem.

**Comment by DanTup** [comment]
Yeah, I can reproduce this - and only with web. @jonahwilliams - does this seem like a Flutter bug? You can repro with console if you have two Flutter versions:

```
cd /tmp
~/Dev/Google/flutter/bin/flutter create test_web
cd test_web
~/Dev/Google/flutter/bin/flutter packages get
~/Dev/Google/flutter/bin/flutter run -d chrome
# App loads fine

# Now using a different SDK

```
~/Desktop/flutter-dev/bin/flutter packages get
# Warning! The 'flutter' tool you are currently running is from a different Flutter repository
~/Desktop/flutter-dev/bin/flutter run -d chrome
```

You get this crash:

```
Error: Error when reading '/Users/dantup/Desktop/flutter-dev/packages/flutter_tools/.packages': No such file or directory
Error: Could not resolve the package 'analyzer' in 'package:analyzer/dart/analysis/results.dart'.
Error: Could not resolve the package 'analyzer' in 'package:analyzer/dart/analysis/utilities.dart'.
Error: Could not resolve the package 'analyzer' in 'package:analyzer/dart/ast/ast.dart'.
Error: Could not resolve the package 'build' in 'package:build/build.dart'.
Error: Could not resolve the package 'build_config' in 'package:build_config/build_config.dart'.
Error: Could not resolve the package 'build_modules' in 'package:build_modules/build_modules.dart'.
Error: Could not resolve the package 'build_modules' in 'package:build_modules/builders.dart'.
Error: Could not resolve the package 'build_modules' in 'package:build_modules/src/module_builder.dart'.
Error: Could not resolve the package 'build_modules' in 'package:build_modules/src/platform.dart'.
Bad state: Unable to start build daemon.                                
#0      _handleDaemonStartup (package:build_daemon/client.dart:82:5)    
```

Doing the same thing for non-web works fine (you get the warning about changing SDK, but it still works, and updates the references in the packages file to point to the new Flutter version).

Running `flutter packages get` and `flutter clean` from the new folder doesn't seem to resolve it.

**Comment by DanTup** [comment]
I tried deleting .dart_tool, build, .packages, pubspec.lock and still have the same issue - I can't figure out what's still left over (yet creating the project from the dev release directly works fine) 🤷🏼‍♂️

**Comment by DanTup** [comment]
No, that was a lie - I was using the wrong SDK. It seems like this is entirely unrelated to the SDK version - it's just the zip release. Steps to repro:

- Download the dev build zip file from the page above and extract
- Run /path/to/flutter-dev/bin/flutter create test_thing
- cd test_thing
- /path/to/flutter-dev/bin/flutter run -d chrome

You'll see the same error.

**Comment by jonahwilliams** [comment]
I have not tried this out, but it sounds like the zip archive does not have the .packages file in `flutter/packages/flutter_tools` that build runner uses to resolve these package names. One fix would be to explicitly pub get in the tool directory when spawning the build daemon

**Comment by jonahwilliams** [comment]
One way to verify this would be to run `flutter update-packages` and then re-run, it should work

**Comment by DanTup** [comment]
Yeah, spot on. Running `update-packages` for that version of Flutter solves the issue.

I've opened https://github.com/flutter/flutter/issues/41681 to track this, since I presume this should be handled inside Flutter (either automatically, or by the packages file being in zips).
