### ISSUE TITLE
Running tests with "All Exceptions" breakpoints setting doesn't work

### ISSUE THREAD

**Issue by knopp** [Dart-Code/Dart-Code#2013]
Happens with latest dart code (3.4.1) and vscode insiders (575062278d181c075ea8dce345ab3d20a127309c)

Running any test fails with 
```
Exception has occurred.
FormatException (FormatException: Scheme not starting with alphabetic character (at character 1)
<data:application/dart>
^
)
```

Unfortunately for whichever reason "Copy call stack" in vscode doesn't seem to be working, but it should be straightforward to reprouce (happens with any basic dart project)

**Comment by DanTup** [comment]
Thanks for the report. This is the same issue described in https://github.com/Dart-Code/Dart-Code/issues/1576. It's breaking on an exception inside the Pub code. If you click the Resume button, then it should continue and run your tests, pausing on real exceptions:

![Untitled](https://user-images.githubusercontent.com/1078012/65335075-a54a7b80-dbbb-11e9-9114-cc81798ae80f.png)
