### ISSUE TITLE
Nested packages seems not handled correctly

### ISSUE THREAD

**Issue by pd4d10** [Dart-Code/Dart-Code#2016]
## Reproduce steps

```sh
git clone https://github.com/bytedance/flutterdoc.git
cd flutterdoc
git checkout 670fdf3704b150d4dcaf2bacde3cbf28ba1963dd
code . # Open VSCode editor
```

Then it would run `pub get` automatically (Triggered by Dart Code).

After that, seems Dart Code does not work correctly for the nested package, which is a Flutter project located at `template/gallery`

## Used versions

OS: macOS
Dart extension: 3.4.1
Flutter extension: 3.4.1
VSCode: 1.38.1

## Screenshots

![image](https://user-images.githubusercontent.com/9524411/65384658-7f59de00-dd57-11e9-87db-f1ee9f987e4f.png)
![image](https://user-images.githubusercontent.com/9524411/65384729-43734880-dd58-11e9-8fe5-360a634499ce.png)

**Comment by DanTup** [comment]
@pd4d10 sorry for the delay, I was OOO. Did you resolve this? What was the problem?

**Comment by pd4d10** [comment]
@DanTup I solve it by moving the nested package outside.

**Comment by DanTup** [comment]
What you had should still work (with some caveats). I cloned your project and opened it, and when it prompted me to fetch packages - I accepted. This caused all the squiggles to go away and only 4 problems remained (just lints/warnings).

This is a supported layout, so if you do still have issues please let me know and I'd like to fix them :-)

**Comment by pd4d10** [comment]
@DanTup I tried to run the same steps and it seems work now. Not sure what happened then.

If it happens again I'll report it here. Thanks!
