### ISSUE TITLE
Hint that constructor can be const

### ISSUE THREAD

**Issue by MichaelPriebe** [Dart-Code/Dart-Code#2018]
It would be pretty handy to have the plugin hint that a constructor can be const. Currently its hard to tell if a constructor is a const constructor or not, without trying.

**Comment by DanTup** [comment]
This is already possible with a lint :-)

https://dart-lang.github.io/linter/lints/prefer_const_constructors.html

For info on enabling lints, see the example `analaysis_options.yaml` file here:

https://github.com/dart-lang/linter#usage

Please let me know if this doesn't work for you!
