### ISSUE TITLE
intelisense not working

### ISSUE THREAD

**Issue by pstjvn** [Dart-Code/Dart-Code#202]
When working on a really small project (only one file - library) the auto-completion it not working properly.

VSCode: 1.6.1
DC: 0.13.0

What happens:

I think image will describe it best: 

![screenshot_2016-11-02_12-42-19](https://cloud.githubusercontent.com/assets/729251/19925871/8daee596-a0fa-11e6-8002-175a016ed7ff.png)

![screenshot_2016-11-02_12-42-37](https://cloud.githubusercontent.com/assets/729251/19925868/88a67500-a0fa-11e6-9c3c-488494e1bd52.png)

Theoretically I can assume that on that line paths is not defined (as I did not initialise it, but same happens with this:

![screenshot_2016-11-02_12-49-46](https://cloud.githubusercontent.com/assets/729251/19925976/ed866d72-a0fa-11e6-9954-5adffae5b38c.png)

I hope this is enough, if more info is needed, I am ready to help as much as I can, just let me know what else is needed.

**Comment by DanTup** [comment]
Thanks for the info. I forgot to ask for Dart SDK version, but I can see in the screenshots you're on 1.20.0 (someone keeps using Dart Code with 1.13!).

When this happens, is it just intellisense that's broken, or is everything (like if you choose one of those quickfixes - like `insert ;` - does it work? or Go to Definition)?

It would help to get an analysis server log. If you open the VS Code user settings and add a setting for `dart.analyzerLogFile` with a full path for a log file then all communication between Dart Code and the analysis server will be logged. If you can review the log immediately after this happened there might be some errors. If you're able to attach the last part of this log (be sure to review there's no sensitive info as it will include file buffer changes) that might help.

Also, if your project is open source or you're happy to share (either here, or with me privately) I can try to repro/debug myself.

Thanks!

**Comment by pstjvn** [comment]
* go to definition still works when the issue re-appears (just to make sure it is not an analyzer issue I re-test everything in atom, the completion works there).
* I did record a log, I am trying to understand it, but I am not sure what I am looking for, it contains very little, I just start the editor and type two letters and that it is: the log indicates the changes (the letters added, the offset etc) and then completion results come in (I suspect those are not really relevant for some reason it tried to complete do DIV??) but right after the errors come in (unrecognized identifier, missing ; etc), the pop-up completion menu stays as 'Loading...'

I am attaching the log and the source file, it is not open source, but it is not secret either, just a small attempt to port a JS lib to dart and see how it feels to reason about similar code in two different languages - file are here: https://gist.github.com/pstjvn/ad56fee0f840d2fd520793019c17e75a

**Comment by DanTup** [comment]
This seems to be because of an assumption in Dart Code that completion results for setters will always have `parameters` (this seemed to makes sense, they're just functions that take an argument, and without the argument we don't know the type). For some reason in your file we don't get that (yet if I extract the function to a new file, it does!).

I've raised a case against the analysis server to see if this is a bug but in the meantime I'm going to try and make our code tolerate this missing (since even if it's a bug and gets fixed, people may use Dart Code with old SDKs) and push out an update.

Related SDK case: https://github.com/dart-lang/sdk/issues/27747

**Comment by DanTup** [comment]
> for some reason it tried to complete do DIV??

By the way, the analysis server returns way more completions than are relevant (for compatibility with IDEs that don't re-request the completion list as the user is typing). In our case, Code handles this nicely and automatically filters them for us so you won't see them in the completion list even though the analysis server returned them.

**Comment by DanTup** [comment]
@pstjvn I've pushed out v0.13.1 which should resolve this issue. Please test and let me know (and of course, if you see any other issues, please do raise Issues!). Thanks!
