### ISSUE TITLE
Dart files with `_test.dart` in the `lib` folder at the end make Code run tests instead of launching the App when you try to run it

### ISSUE THREAD

**Issue by escamoteur** [Dart-Code/Dart-Code#2021]
@DanTup As we chatted this morning.

**Comment by DanTup** [comment]
This was done because because when we just looked for `/test/` in the path we got issues like this:

https://github.com/Dart-Code/Dart-Code/issues/1165

Maybe we can check for a project root, and then check if it's in `/test/` from there or similar.
