### ISSUE TITLE
Unable to attach to remote device

### ISSUE THREAD

**Issue by galvesribeiro** [Dart-Code/Dart-Code#2025]
Hello folks!

I'm trying to attach the debugger to an external device running flutter (a Raspberry PI fyi) and I'm unable to get the debugger to work.

This is my launch.json:

```json
        {
            "name": "Flutter Attach",
            "request": "attach",
            "type": "dart",
            "observatoryUri": "http://192.168.196.46:32973/Wc46BiJPvSo=/",
            "deviceId": "flutter-tester"

        }
```

The device is showing the correct observatory uri:

```
flutter: Observatory listening on http://192.168.196.46:9090/vpYcsJD0H98=/
```

When I start the debug it keeps waiting forever:

![image](https://user-images.githubusercontent.com/4714040/65822300-fee42300-e217-11e9-84dc-8e3467cda312.png)

After a while, then the waiting popup disappear and nothing happens.

Can someone shed a light? Attached the logs.

Thank yoU!

[Dart-Code-Log-2019-08-06 17-48-34.txt](https://github.com/Dart-Code/Dart-Code/files/3665988/Dart-Code-Log-2019-08-06.17-48-34.txt)

**Comment by DanTup** [comment]
> When I start the debug it keeps waiting forever:

How long is forever?

The log looks normal - it shows that we connected to the device and started setting things up, and then we got the `app.started` event from Flutter - which is what is supposed to hide the "Waiting for application to connect" dialog. It's not clear why this wouldn't happen.

Is there anything in the debug console if you click Help -> Toggle Developer Tools in VS Code?

If you try to attach to something else (like an emulator of mobile phone), do you see the same behaviour or does that work?

**Comment by DanTup** [comment]
Are you still seeing this? Are you able to check the things mentioned above? If so, please post back. Thanks!
