### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by r0lnd0** [Dart-Code/Dart-Code#2027]
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `3.4.1`
- OS Version: `Linux x64 5.3.1-arch1-1-ARCH`
- VSCode version: `1.38.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/r0lnd0/Dart-Code.dart-code-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by DanTup** [comment]
@r0lnd0 are you able to attach this file?

> ⚠️ Make sure to attach this file from your home-directory:
> ⚠️/home/r0lnd0/Dart-Code.dart-code-unresponsive.cpuprofile.txt

**Comment by DanTup** [comment]
Please let me know if you're still seeing this and can provide the file requested above. Thanks!
