### ISSUE TITLE
Flutter - autocompleting field jumps cursor past trailing comma

### ISSUE THREAD

**Issue by mccadi** [Dart-Code/Dart-Code#2029]
After upgrading to 3.5.0, I noticed that whenever accepting the auto-completer's suggestion when pressing the "return" key, the cursor will jump to the end of the line and past the comma. The usual behavior would stop the cursor immediately to the left of the comma, allowing you to define the field's value.

**Comment by Toolenaar** [comment]
This is seriously impacting my coding flow atm.

**Comment by DanTup** [comment]
Thanks for the report! I'm able to reproduce this - trying to track down where it's come from and I'll get a patch out. Sorry for the inconvenience!

**Comment by DanTup** [comment]
A fix has been published in v3.5.1. Please let me know if you still have any issues like this.

I've also opened https://github.com/Dart-Code/Dart-Code/issues/2030 about extending the tests to check the cursor position for this sort of completion.
