### ISSUE TITLE
"createMethod" wreaks the formattings

### ISSUE THREAD

**Issue by nbros** [Dart-Code/Dart-Code#2032]
Before create method:
![image](https://user-images.githubusercontent.com/141089/66214823-bbc7fb00-e6c2-11e9-9b54-bf2a3c4c5db3.png)

After create method:
![image](https://user-images.githubusercontent.com/141089/66214997-fcc00f80-e6c2-11e9-9ed8-d75fc0cecc60.png)

**Comment by DanTup** [comment]
This is the same as https://github.com/Dart-Code/Dart-Code/issues/584.

It's a "feature" in VS Code that assumes language servers produce incorrect indenting and then "fixes" it. I opened an issue about it at https://github.com/microsoft/vscode/issues/63129 but it's had no response. I may try to see if I can find a workaround that isn't fragile (which guesses what indenting VS Code will add, and then subtracts it from the edit), but I haven't tried it yet so can't promise.

Subscribe to those issues for updates, I'll close this one as a dupe. Thanks!
