### ISSUE TITLE
Error: Not found: 'dart:ui'

### ISSUE THREAD

**Issue by david97wong** [Dart-Code/Dart-Code#2038]
Please help
![Screenshot 2019-10-08 at 10 54 46 PM](https://user-images.githubusercontent.com/43961405/66406731-b221f880-ea1e-11e9-9709-71d20bae108a.png)
![Screenshot 2019-10-08 at 10 54 31 PM](https://user-images.githubusercontent.com/43961405/66406740-b3532580-ea1e-11e9-913d-f1319e1e9d55.png)

**Comment by david97wong** [comment]
I dont know how to change the dart sdk to flutter sdk

**Comment by DanTup** [comment]
@david97wong the extension should select the right SDK automatically. What folder do you have open in the Explorer pane, and do you see "Flutter" written in the status bar when you have a Dart file open?

**Comment by david97wong** [comment]
![Screenshot 2019-10-10 at 1 19 48 PM](https://user-images.githubusercontent.com/43961405/66541094-adfdf400-eb60-11e9-92a0-8b3ac4845ed3.png)
Hi DanTup, do you mean this one?

**Comment by DanTup** [comment]
@david97wong that looks like Android Studio or IntelliJ? This issue tracker is for the VS Code extension - unfortunately I'm not familiar with how that works, though I did find this:

https://github.com/flutter/flutter-intellij/blob/master/README.md#quick-start

Which says 

- configure the Flutter SDK setting
  - Preferences on macOS, File>Settings on Linux, select Languages & Frameworks > Flutter, and set the path to the root of your flutter repo

Please try that, and if you still have issues it may be best to open an issue in https://github.com/flutter/flutter-intellij (which covers both IntelliJ and Android Studio).

**Comment by JoelOvien** [comment]
I'm having the same problem but on VS code...I'm not seeing flutter written on the status bar when I open a dart file...what should I do?

**Comment by JoelOvien** [comment]
@DanTup @david97wong

**Comment by DanTup** [comment]
@JoelOvien if `Flutter` doesn't appear in the status bar, it suggests your project wasn't detected as a Flutter project. Can you confirm your `pubspec.yaml` contains `sdk: flutter` and where it is in relation to the root folder opened in VS Code? We'll only walk a few levels down looking for Flutter projects when deciding which mode to use.

You could also enable to [extension log](https://dartcode.org/docs/logging/#extension) which logs some info as it scans projects when deciding which mode to use which may be useful. Also check there are no notifications in VS Code (bell icon in bottom right) that might be advising the SDK wasn't found, or similar.

**Comment by DanTup** [comment]
Are you still having this issue? Are you able to get the log described above?

**Comment by JoelOvien** [comment]
yes, i am still having the issue and i have not been able to get the log
you told me about

**Comment by DanTup** [comment]
@JoelOvien there are some instructions at https://dartcode.org/docs/logging/#extension. You need to open your VS Code User Settings and set the mentioned setting to a file path. That will cause the extension to restart and log to that file. Check the file doesn't contain anything sensitive, and attach it here/in a gist or email to logs@dartcode.org.

Thanks!

**Comment by JoelOvien** [comment]
okay, Thank you

**Comment by JoelOvien** [comment]
The code works now, Thank you for your help

**Comment by DanTup** [comment]
Great, glad to hear!

**Comment by gaetaneferon** [comment]
Hi, I have the same problem but I didn't undestand what to do exactly. Can you help please.

many thanks

**Comment by DanTup** [comment]
@gaetaneferon could you post a screenshot showing the issue, and including the full VS Code status bar?

**Comment by david97wong** [comment]
i give up, sorry bro.

**Comment by noordawod** [comment]
How hard can it be to add a setting to VS Code that enables the *dumb* developer (us) to set the Dart mode manually (`dart`, `flutter`). That would have fixed this and enable cross-developer interoperability easily.

**Comment by DanTup** [comment]
@noordawod please don't spam the same comment on multiple issues. If you'r ehaving problems, raising a single new issue is sufficient.

**Comment by noordawod** [comment]
> @noordawod please don't spam the same comment on multiple issues. If you'r ehaving problems, raising a single new issue is sufficient.

Removed.
