### ISSUE TITLE
Status bar does not show Simulator correctly

### ISSUE THREAD

**Issue by ssbaval** [Dart-Code/Dart-Code#2043]
I am using VSCODE latest version and have noticed that the Status bar no longer shows the specific version of the iOS Simulator : 

![image](https://user-images.githubusercontent.com/56350563/66481521-0c5f9f80-ea99-11e9-80ac-eab8812c65b5.png)

and here : 

![image](https://user-images.githubusercontent.com/56350563/66481561-197c8e80-ea99-11e9-87c8-75dd4467b239.png)

I have also upgraded to Catalina and have the same issue.

**Comment by DanTup** [comment]
Thanks for the report! This happened with the recent changes to use emulator names. For Android the emulator names are better, but I didn't realise for iOS they were worse :(

**Comment by sallymariehollywood** [comment]
Flutter 1.9.1 hotfix 6 also has this issue - only happens with iOS . Is there any other way for identifying which simulator is the correct one in VS CODE ?

**Comment by DanTup** [comment]
The issue is in the VS Code extension, not Flutter. It's fixed for the next version, which you can try the beta release of here:

https://github.com/Dart-Code/Dart-Code/releases/tag/v3.6.0-beta.1
