### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by JHONYS05** [Dart-Code/Dart-Code#2045]
- Issue Type: `Bug`
- Extension Name: `dart-code`
- Extension Version: `3.5.1`
- OS Version: `Darwin x64 19.0.0`
- VSCode version: `1.38.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by DanTup** [comment]
> ⚠️ We have written the needed data into your clipboard. Please paste! ⚠️

You need to paste the information about the issue for us to be able to tell what's happened here.

**Comment by Lisenish** [comment]
Looks like this can be closed

**Comment by DanTup** [comment]
Yeah, thanks! If anyone is still having issues, please open new issues and include the information from the clipboard.
