### ISSUE TITLE
CacheImageNetwork for flutter web

### ISSUE THREAD

**Issue by RanABI** [Dart-Code/Dart-Code#2050]
Hi,
I am migrating my project to flutter web, all is working fine but the cached images.
On mobile devices, I receive and view the image with no problem.
On web, it gets stuck on Circular progress indicator .
Since there is no debugging support for web, I do not know where the problem is, unless flutter web just doesn't support CachedNetworkImage.
If it doesn't - is there an alternative?

Here is my code:
 ```
 CachedNetworkImage getCachedImage(index, url, headers) {
    var cachedImage = new CachedNetworkImage(
      imageUrl: url,
      httpHeaders: headers,
      placeholder: (context, url) => new CircularProgressIndicator(),
      errorWidget: (context, url, error) => new Icon(Icons.error),
      imageBuilder: (context, imageProvider) => Container(
        decoration: BoxDecoration(
          image: DecorationImage(
            image: imageProvider,
            fit: BoxFit.cover,
          ),
        ),
      ),
    );
    return cachedImage;
  }
```

This is the call:
```
 var cachedImage = getCachedImage(i, getUrl(i), headers);
        return GestureDetector(
          child: Hero(
              tag: 'imageHero',
              child: Container(
                padding: EdgeInsets.only(left: 10,right: 10),
                height: deviceSize.height * 0.3,
                width: deviceSize.width * 0.4,
                child: Center(
                  child: cachedImage,
                ),
              )
```

here is ouput of flutter doctor:

> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel master, v1.10.15-pre.23, on Microsoft Windows [Version 10.0.18362.418], locale en-US)
>  
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
> [√] Chrome - develop for the web
> [√] Android Studio (version 3.4)
> [!] IntelliJ IDEA Community Edition (version 2017.3)
>     X Flutter plugin not installed; this adds Flutter specific functionality.
>     X Dart plugin not installed; this adds Dart specific functionality.
> [√] VS Code (version 1.39.1)
> [√] Connected device (3 available)
> 
> ! Doctor found issues in 1 category.

Thanks !

**Comment by shashwatadi** [comment]
Any reason for closing this @RanABI ?

**Comment by shilangyu** [comment]
While a valid question this seems to have nothing to do with this repo
