### ISSUE TITLE
"Rewind" in debugger

### ISSUE THREAD

**Issue by nbros** [Dart-Code/Dart-Code#2052]
The Dart debugger has a "rewind" feature that allows moving back the execution to the beginning of the current frame (or another frame on the call stack, given a `count` parameter).

But currently this feature seems impossible to use with Dart Code: when I right-click a stack frame all I see is "Copy Call Stack". I also tried typing "rewind" in the debugger view, and I got "Getter not found: rewind". And when we open the Dart DevTools from Dart Code, the Debugger tab is disabled so we can't enter the rewind command there either.

This is a feature request to add the "Rewind" feature in Dart Code in the context menu of a selected stack frame in the Call Stack view (in the Debug sidebar).
A **Debug: Rewind** command that can be bound to a key combination would be nice too (for quickly rewinding the current frame with a keystroke).

see also: https://github.com/dart-lang/sdk/issues/38852
and: https://github.com/dart-lang/sdk/blob/master/runtime/observatory/lib/src/elements/debugger.dart#L418

**Comment by DanTup** [comment]
Thanks for the issue! VS Code has a concept of "Step back" - I wonder if these match up. I did look for an equiv in Dart a while back, but somehow didn't come across Rewind. I'll do some digging to see what would be involved in supporting it.

**Comment by DanTup** [comment]
This is easy enough to implement, but VS Code has bundled two features ("StepBack" and "ReverseContinue") under one flag, which means to enable this we end up with a broken button that says "Reverse" on the toolbar :(

I've opened https://github.com/microsoft/vscode/issues/85215 to see if these can be separated. For now I will ship this being an opt-in flag so you can have it if you want it, but most users won't get this confusing extra broken button.
