### ISSUE TITLE
Remove `gem install cocoapods` hard-coded version

### ISSUE THREAD

**Issue by jmagman** [Dart-Code/Dart-Code#2058]
https://github.com/Dart-Code/Dart-Code/commit/18f18fbab3d8e7e5e67c10d3d2cf4b07447560f5 can be reverted.  https://github.com/flutter/flutter/issues/41253 has been promoted to flutter stable as v1.9.1+hotfix.5.

**Comment by jmagman** [comment]
\cc @DanTup

**Comment by DanTup** [comment]
Great, I'll swap it back and test - thanks!

**Comment by DanTup** [comment]
Turns out I'd already removed that change, and instead temporarily moved the test to the Flutter dev channel. I've updated back to master now. Thanks!
