### ISSUE TITLE
Errors from running Flutter are not surfaced in the UI well

### ISSUE THREAD

**Issue by rifleman89** [Dart-Code/Dart-Code#2071]
Issue Type: <b>Bug</b>

I am trying to create a new project, but i keep getting this message, "flutter create --ios-language swift --android-language kotlin .: running..." I have the updated versions of everything but I cant seem to get it to work.

Extension version: 3.5.1
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (5.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by DanTup** [comment]
Can you provide a screenshot of exactly what you see? Also, if you open the dev tools (Help -> Toggle Developer Tools) are there any errors listed in the Console tab when this happens?

If you run `flutter create --ios-language swift --android-language kotlin my_test_app` from the terminal, does that work?

**Comment by rifleman89** [comment]
![Capture526](https://user-images.githubusercontent.com/50912334/67618868-907d8b00-f7ec-11e9-86af-6e955bda8b96.PNG)
No it doesnt work

**Comment by rifleman89** [comment]
have a look at the bottom right corner. the progress bar keeps moving but never ends. hope this helps

**Comment by DanTup** [comment]
> No it doesnt work

It's not clear what that means - do you mean it doesn't work from the terminal either? If so, it seems like it's unrelated to the VS Code extension and we should raise it at flutter/flutter. The output of running it in verbose mode (with `-v`) may help too.

If it does work from the terminal, then could you check the VS Code developer console (Help -> Toggle Developer Tools then click console) and see if any errors are listed? Thanks!

**Comment by rifleman89** [comment]
Many thanks for your response, I have raised the issue on flutter. Hopefully, I get a response. Thanks once again.

**Comment by DanTup** [comment]
Thanks for opening the issue in Flutter. The real issue is shown in the screenshot at https://github.com/flutter/flutter/issues/43571#issuecomment-546901109, but this should've been propagated to the UI somewhere in VS Code rather than just hanging, so I'll also keep this issue open to improve that.

**Comment by DanTup** [comment]
I think this has been fixed somewhere along the line. When I cause an access denied message in Flutter, the progress bar disappears and I get a clear error shown in the output pane.
