### ISSUE TITLE
Hot reload not working with custom entrypoints

### ISSUE THREAD

**Issue by danielnovograd** [Dart-Code/Dart-Code#2072]
Issue Type: <b>Bug</b>

Hey there,

I'm having an issue where onSave in debug mode, my project will always Hot Restart rather than Hot Reload. I've set the following in my `settings.json`: 

```
  "dart.flutterHotReloadOnSave": true,
  "dart.flutterHotRestartOnSave": false,
```
The only non-standard thing about my flutter project is that I have it split into two main.dart files: `main_development.dart` and `main_production.dart`. I've added launch configurations for both of these in `.vscode/launch.json`:

```
    {
      "program": "lib/main_development.dart",
      "name": "development",
      "request": "launch",
      "type": "dart",
      "args": ["--flavor", "development"]
    },
   {
      "program": "lib/main_production.dart",
      "name": "production",
      "request": "launch",
      "type": "dart",
      "args": ["--flavor", "production"]
    }
```
When I use the command palette to select the `Developer: Toggle Developer Tools`, I see this output in the console upon running one of my configurations with 'Start Debugging':

```
  ERR File not found (/main_development.dart): Error: File not found (/main_development.dart)
    at v.resolve (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1535:605)

log.ts:196   ERR File not found (/lifecycle.): Error: File not found (/lifecycle.)
    at v.resolve (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1535:605)

```
and then when I save a change in a flutter file:

```
  ERR File not found (/lifecycle.): Error: File not found (/lifecycle.)
    at v.resolve (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1535:605)
```
This results in a hot restart that brings me to the entrypoint of the application every time, without hot reloading anywhere.

EDIT: This Hot Restart behavior also occurs when I select `Select Widget Mode` in the Dart DevTools.

Thanks for the help!

Extension version: 3.5.1
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.7.0

**Comment by DanTup** [comment]
Does this happen if you run from the terminal with `flutter run -t lib/file.dart` and press `r` to reload?

If so, it's likely a Flutter bug and we should raise at flutter/flutter.

If not, could you capture a log (run the **Dart: Capture Logs** command, then tick only **Flutter Run**, then launch the app and perform some saves) and attach it here (or link to it in a gist)? Thanks!

**Comment by danielnovograd** [comment]
Thanks for the quick response, @DanTup !

It does still happen when running the flutter command directly.

**Comment by danielnovograd** [comment]
Sorry, @DanTup, we figured out what was causing the app to re-render. Had to do with GlobalKeys being generated in widget constructors and not with the dart code plugin. Thanks anyway!

**Comment by DanTup** [comment]
Glad you got it sorted!
