### ISSUE TITLE
flutter.selectDevices should reflect `flutter devices`

### ISSUE THREAD

**Issue by danielnovograd** [Dart-Code/Dart-Code#2073]
Issue Type: <b>Feature Request</b>

When you have multiple iOS simulators open and run `Flutter: Select Devices` from the command palette, you see a list with multiple ios Simulator entries. It would be much more helpful if the name of the device were used (as is shown with `flutter devices`) rather than the generic name for all ios simulators.

Thanks!

Extension version: 3.5.1
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.7.0

**Comment by DanTup** [comment]
Thanks for the report! This is unfortunately a regression introduced in the latest release. It's fixed for the next release (see #2043) which hopefully isn't too far off (I'm hoping to publish a beta release early next week).

**Comment by DanTup** [comment]
There's a beta release with the fix here if you'd like to test it out:

https://github.com/Dart-Code/Dart-Code/releases/tag/v3.6.0-beta.1
