### ISSUE TITLE
Auto-complete package versions in pubspec.yaml

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#2078]

**Comment by pumano** [comment]
would love to see that feature as package.json for nodejs show latest available version of dependency when hovered or selected

**Comment by pumano** [comment]
@DanTup any news about that feature? Would live to see that. Just hovering mouse to package version or auto complete and get latest available package for pub.dev in tooltip popup. It's very useful for updating packages to latest.

![dependencyintellisense](https://user-images.githubusercontent.com/17675259/94554576-f11a1100-0262-11eb-8da6-1127e233b056.png)

**Comment by DanTup** [comment]
No news though I haven't forgotten about it, it pops into my head frequently when I'm editing pubspecs! I need to understand a bit more about the completion internals if I was to implement it, but haven't had the time to do so yet.

**Comment by DanTup** [comment]
Part of https://github.com/dart-lang/sdk/commit/9cbc497d0ada365617f29fd923ad11066ea5a4ea.
