### ISSUE TITLE
Debug console hijacks focus from Find Widget

### ISSUE THREAD

**Issue by osharaki** [Dart-Code/Dart-Code#2084]
While developing in Flutter with the debug console open, the Find Widget doesn't respond to the default keyboard shortcuts as it normally should. 
_Ctrl+F_ still opens up the Find Widget and I can type inside it, but Enter and _Shift+Enter_ no longer perform **Find Next** and **Find Previous**, respectively. I'm also unable to close the Find Widget with _Escape_ (the same goes for the Replace Widget). Once I close/minimize the debug console, however, everything is back to normal. 
I couldn't find any keyboard shortcuts specific to the debug console that may be overriding the find widget shortcuts. Also, all find widget shortcuts are set to default.

**Comment by DanTup** [comment]
Did you resolve this?

Things like keyboard shortcuts are generally handled by VS Code, so this might be an issue that needs fixing there. If you do open an issue there (or found a resolution), it's worth noting here in case anyone else stumbles across this issue hitting the same problem :-)

**Comment by osharaki** [comment]
Thanks for the hint. You can follow the issue [here](https://github.com/microsoft/vscode/issues/83829#issue-516110740).
