### ISSUE TITLE
DartCode thinks the SocketException is uncaught even though the try-catch works as expected

### ISSUE THREAD

**Issue by MateusRodCosta** [Dart-Code/Dart-Code#2085]
Hello, I am having issue with the following method:

```dart
  Future<void> initialSync() async {
    _isLoading = true;
    notifyListeners();
    try {
      final result = await http.read('https://vip.aersia.net/roster.xml');

      _trackList = PlaylistXmlUtils.parseData(result);
      _isSuccess = true;
    } catch (ex) {
      _isSuccess = false;
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }
```

I parse a xml from a remote server to have a list of tracks. However I wanna show a error message if it fails either parsing the xml or if it can't even get the xml.

So, for my testing I run that method with wifi turned off.

When I run the code with the breakpoints in Uncaught Exceptions options enabled I always get:

Exception has occurred.
SocketException (SocketException: Failed host lookup: 'vip.aersia.net' (OS Error: No address associated with hostname, errno = 7))

As seen here:
![Screenshot from 2019-11-02 13-39-41](https://user-images.githubusercontent.com/24463334/68074113-63922080-fd76-11e9-941b-929cf80e38c3.png)

However after I press "Step Into" enough times to get rid of the Uncaught Exception message I get the following:

![Screenshot from 2019-11-02 13-43-00](https://user-images.githubusercontent.com/24463334/68074155-d4393d00-fd76-11e9-8f68-48a2a44c4b57.png)

Which simply appears to mean that the exception was actually caught.

**Comment by DanTup** [comment]
Thanks for the report! There's an existing issue about this at https://github.com/Dart-Code/Dart-Code/issues/2063 so I'll close this one as a dupe.
