### ISSUE TITLE
Windows does not show up as a device in VSCode on the latest master w/ config set properly

### ISSUE THREAD

**Issue by csells** [Dart-Code/Dart-Code#2090]
Notice that enable-windows-desktop is set in the terminal window and Windows is not one of the available devices in the VSCode drop-down but that it is returned from `flutter devices`:

![image](https://user-images.githubusercontent.com/2568253/68231488-041f5500-ffb0-11e9-91fd-da98c6edce92.png)

**Comment by csells** [comment]
I created the windows subfolder AFTER the project was loaded; stopping and restarting VSC on that same project caused Windows to be recognized as an available device. Apparently the extension is caching; should it be?

**Comment by DanTup** [comment]
> Apparently the extension is caching; should it be?

We cache it for 10 seconds, mainly to avoid re-requesting it lots during startup when the devices come through one at a time (we don't know when we've got the last one, so we initially would fetch it for every device):

https://github.com/Dart-Code/Dart-Code/blob/597e4da9f906089dff525f2dbbf0d80fa4742c52/src/shared/vscode/device_manager.ts#L195

I'll do some testing on Windows though - it's possible the caching isn't working correctly, or the info we got from Flutter didn't update. If I can't repro and you still can, a log (using **Capture Logs** and then ticking **Flutter Device Daemon**) might help.

**Comment by DanTup** [comment]
@csells when did you enable desktop (using `flutter config`)? Was it in the terminal within VS Code, or before you opened the project?

If it was in the terminal, then I think what's happened here is that the Flutter daemon was already running (and thus read the old config). I don't think there's an easy way to handle that (VS Code doesn't know when it should restart the daemon, and Flutter probably doesn't want to read the config from disk every time).

(cc @jonahwilliams in case he has any ideas to handle this better)

If it wasn't that, let me know and I'll dig some more.

**Comment by csells** [comment]
Yes. I enabled Windows in the VSC terminal.

**Comment by DanTup** [comment]
Ah, that does explain that then. I don't think we can handle this from the VS Code side. I think the only possible option (though I'm not sure if we'd want to maintain the complexity of it for this edge case) could be for the Flutter daemon to watch the config file, so if another Flutter process modifies it, it can re-read the settings. I'll defer to @jonahwilliams on whether that seems worthwhile (though I don't mind implementing it if it does seem reasonable).

**Comment by jonahwilliams** [comment]
There is a lot of one-time setup that is run at initialization based on the config that I don't think we could repeat.

One solution might be to watch the file and a print a status message if it changes

```
flutter config has updated, please restart all editors/instances to see new settings
```

**Comment by DanTup** [comment]
If you mean in the daemon, the message would need to be machine-friendly and the editors respond to it (otherwise the editors would need to know where the config is stored - which we kinda do for the survey, but it seems a bit weird).

What about if we just tag the message onto the end of the output of running `flutter config` so it's visible there in the terminal after you set it?

<img width="574" alt="Screenshot 2019-11-07 at 2 15 27 pm" src="https://user-images.githubusercontent.com/1078012/68396193-11337400-0169-11ea-95cd-cd502357893f.png">
