### ISSUE TITLE
没有语法提示

### ISSUE THREAD

**Issue by T-toghter** [Dart-Code/Dart-Code#2091]
Issue Type: <b>Bug</b>

开发flutter，没有任何的语法提示，有安装flutter和Dart插件，也有重启编辑器，但就是没有任何语法提示，只能一个个字母敲

Extension version: 3.6.0
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (3.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by DanTup** [comment]
Thanks for the issue! I used Google Translate to try to understand the problem, but it's not very clear from the translation.

Are you able to provide a screenshot or [capture a log](https://dartcode.org/docs/logging/#capture-logs-command) to illustrate the issue?

**Comment by w3cmark** [comment]
In the VScode editor, after install the flutter and Dart plugins and restart editor, it still no syntax tips.
For example, when we write JavaScript, We can get the syntax tips as shown below:
![image](https://user-images.githubusercontent.com/7434649/71555663-6ef98380-2a69-11ea-869f-8288f0f59c2a.png)

**Comment by DanTup** [comment]
Are there any messages shown in the Notifications in VS Code (bell icon in bottom right corner of the status bar) or in the developer console (Help -> Toggle Developer Tools -> Console)?

**Comment by w3cmark** [comment]
> Are there any messages shown in the Notifications in VS Code (bell icon in bottom right corner of the status bar) or in the developer console (Help -> Toggle Developer Tools -> Console)?

yes, there some messages shown in developer console: 
```
ERR 无法读取文件(EntryNotFound (FileSystemError)): Error: 无法读取文件(EntryNotFound (FileSystemError))
    at _.doReadAsFileStream (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1591:434)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by DanTup** [comment]
That one seems probably unrelated to this issue.

Can you take a screenshot of the whole of VS Code (be sure to include the full status bar and Explorer tree)? Also make sure you opened a folder, and not just a single `.dart` file.

**Comment by w3cmark** [comment]
I record a gif:
![flutter](https://user-images.githubusercontent.com/7434649/71942827-72270900-31f9-11ea-8f69-bc0feb366aa5.gif)

I have tow questions:
1.  no syntax tips
2. the dart process take up a high cpu each time and each time vscode is restarted, one more dart process is added

**Comment by DanTup** [comment]
Can you run `code --status` in a terminal while VS Code is open and this is happening and post the output here?

**Comment by w3cmark** [comment]
Such as, in the iTerm terminal and under any path run `code --status`?
output:
```
command not found: code
```
what is `code` command?

**Comment by w3cmark** [comment]
Such as, in the iTerm terminal and under any path run `code --status`?
output:
```
command not found: code
```
what is `code` command?

**Comment by DanTup** [comment]
@w3cmark ah sorry, this might only work if you have got `code` on `PATH`. `code` is a binary that just launches VS Code (see https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line).

**Comment by w3cmark** [comment]
```
Version:          Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS Version:       Darwin x64 18.7.0
CPUs:             Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)
Memory (System):  16.00GB (0.31GB free)
Load (avg):       3, 3, 2
VM:               0%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  metal:                         disabled_off
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_renderer:                 disabled_off
                  surface_control:               disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  enabled
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %	Mem MB	   PID	Process
    1	    98	 45358	code main
    0	    49	 45359	   gpu-process
    0	   229	 45362	   window (demo01.dart — 无标题 (工作区))
    0	    82	 45405	     extensionHost
   97	   344	 45429	       /Users/jun85.li/Documents/flutter/bin/cache/dart-sdk/bin/dart /Users/jun85.li/Documents/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --client-id=Dart-Code.dart-code --client-version=3.7.1
    0	     0	 45430	       bash /Users/jun85.li/Documents/flutter/bin/flutter daemon
    0	   197	 45447	         /Users/jun85.li/Documents/flutter/bin/cache/dart-sdk/bin/dart --packages=/Users/jun85.li/Documents/flutter/packages/flutter_tools/.packages /Users/jun85.li/Documents/flutter/bin/cache/flutter_tools.snapshot daemon
    0	     0	 45711	       bash /Users/jun85.li/Documents/flutter/bin/flutter upgrade
    0	   180	 45725	         /Users/jun85.li/Documents/flutter/bin/cache/dart-sdk/bin/dart --packages=/Users/jun85.li/Documents/flutter/packages/flutter_tools/.packages /Users/jun85.li/Documents/flutter/bin/cache/flutter_tools.snapshot upgrade
    0	     0	 45740	           /Applications/Xcode.app/Contents/Developer/usr/bin/git pull --ff
    0	     0	 45741	             /Applications/Xcode.app/Contents/Developer/usr/libexec/git-core/git fetch --update-head-ok
    0	     0	 45742	               /Applications/Xcode.app/Contents/Developer/usr/libexec/git-core/git-remote-https origin https://github.com/flutter/flutter.git
    0	    33	 45406	     watcherService
    0	    33	 45407	     searchService
    0	    33	 45412	   utility
    2	   131	 45481	   shared-process
    1	     0	 45936	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=

Workspace Stats:
|  Window (demo01.dart — 无标题 (工作区))
|    Folder (node): 63 files
|      File types: js(17) json(7) md(4) vue(4) gitignore(2) DS_Store(1)
|                  eslintrc(1) lock(1) log(1) ico(1)
|      Conf files: package.json(3)
|    Folder (host): more than 27330 files
|      File types: php(5604) js(3681) json(987) md(960) vue(683) png(502)
|                  css(375) xml(306) html(239) ts(214)
|      Conf files: package.json(159) makefile(8) tsconfig.json(7) gulp.js(5)
|                  jsconfig.json(4) tslint.json(3) webpack.config.js(3)
|                  launch.json(2) grunt.js(2) settings.json(1)
|      Launch Configs: dart
|    Folder (w3cmark): 1951 files
|      File types: js(331) md(217) html(132) styl(112) vue(97) png(96)
|                  scss(93) swig(92) ts(69) svg(45)
|      Conf files: package.json(5) makefile(1) gulp.js(1)
```

@DanTup

**Comment by DanTup** [comment]
Are you still seeing this? Are you able to capture the log mentioned above?
