### ISSUE TITLE
VsCode should provide quickfix to add / remove method return type

### ISSUE THREAD

**Issue by vogella** [Dart-Code/Dart-Code#2095]
Would be nice to a have a quickfix which allows to add / remove the return type of a method, e.g.,:

````
List<Widget> _createChildren() {
  return [Text("Hello"), Text("Lars"), Text("Testing")];
````

````
_createChildren() {
  return [Text("Hello"), Text("Lars"), Text("Testing")];
````

**Comment by DanTup** [comment]
The code fixes come from the analysis server, so this would need implementing in the SDK (https://github.com/dart-lang/sdk/issues). If you open an issue there, please post the link back here for anyone that comes across this issue and wants to go add a 👍 

Thanks!

**Comment by vogella** [comment]
https://github.com/dart-lang/sdk/issues/39277

**Comment by DanTup** [comment]
Great, thanks! I'll close this one as there's nothing to do in VS Code - if it's added to the server it'll appear automatically.

**Comment by vogella** [comment]
Thank you

Danny Tuppeny <notifications@github.com> schrieb am Do., 7. Nov. 2019,
13:34:
