### ISSUE TITLE
VS Code, Flutter: New Project, always uses com.example.project_name

### ISSUE THREAD

**Issue by opalr** [Dart-Code/Dart-Code#2097]
Issue: The command Flutter: New Project sets the applicationId to com.example.crystal. I want it to use com.custom_name.crystal.

This applicationId is used in several different files. Is it correct to update all instances of com.example.crystal to com.custom_name.crystal?

![image](https://user-images.githubusercontent.com/50309714/68521046-137df700-026b-11ea-92f4-ae1f69a52a3e.png)

**Comment by DanTup** [comment]
There are some settings that begin `dart.flutterCreate...` that let you control this, see:

https://dartcode.org/docs/settings/#dartfluttercreateandroidlanguage

Let me know if anything isn't clear or this doesn't work as expected.

**Comment by opalr** [comment]
Thanks. This will help next time I create a new project. To fix the project I have already created, is it correct to update all the instances of com.example.crystal in the image?

**Comment by DanTup** [comment]
Honestly I'm not sure - I would expect so, but it's not something I'm totally familiar with. This [StackOverflow question] seems to have conflicting answers about it https://stackoverflow.com/questions/51534616/how-to-change-package-name-in-flutter

If it doesn't work, the easiest way may be to create a new project and then copy your Dart files over to it (assuming you haven't customised the native mobile parts).
