### ISSUE TITLE
Is it possible to have dart in a subfolder

### ISSUE THREAD

**Issue by JCzz** [Dart-Code/Dart-Code#2104]
In VCCode I have a project(workspace), 
is it possible to have a folder containing a dart project(Stagehand package-simple)?

```
Project(workspace)
- folderA
- folderB
- dartcode << Stagehand package-simple
```

The problem is that the package references do not work(`Target of URI doesn't exist`). Just for infor. the references do work if I open the dartcode folder.

**Comment by DanTup** [comment]
Yes, this should all work fine. Can you reproduce this with simple folders that you could share in a repo? (include files like `.packages` and `pubspec.lock` in the repro if possible).

**Comment by DanTup** [comment]
@JCzz did you resolve this? If it was something you had setup wrong, it'd be good to note here so if others have the same issue and find it they'll know what to try :-)
