### ISSUE TITLE
Debug mode hangs on 'Waiting for observatory port to be available...'

### ISSUE THREAD

**Issue by danielnovograd** [Dart-Code/Dart-Code#2105]
Issue Type: <b>Bug</b>

Hi there,

I'm having trouble running a flutter debugging session on iOS specifically using either `launch.json` or a manual `flutter run` command. Android works just fine.

When I start the debugging session, the console output ends here:

```
Launching lib/main_development.dart on iPhone 11 in debug mode...
log: Must be admin to run 'stream' command
Script started, output file is /dev/null
Script done, output file is /dev/null
Xcode build done. 
```

When I run the command with the verbose flag, the output seems to be hanging here:

[        ]  Waiting for observatory port to be available...

I'm assuming the `Must be admin to run 'stream' command` is relevant, but I'm not sure what would have caused this to suddenly happen and couldn't find a related issue for a fix.

Thanks for your help!

Extension version: 3.6.0
VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:09:34.601Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|16.00GB (1.36GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

`flutter doctor -v`
```
[✓] Flutter (Channel beta, v1.10.7, on Mac OS X 10.14.6 18G95, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.40.0)
[✓] Connected device (2 available)

• No issues found!
➜  merlin git:(setup-all-tasks) ✗ flutter doctor -v
[✓] Flutter (Channel beta, v1.10.7, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.10.7 at /usr/local/flutter
    • Framework revision e70236e36c (6 weeks ago), 2019-10-02 09:32:30 -0700
    • Engine revision 9e6314d348
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 1103600280)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/dnovograd/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/dnovograd/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 10 (API 29) (emulator)
    • iPhone 11                 • E6015000-C367-4086-AF56-07BC10DF4298 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)
```

**Comment by DanTup** [comment]
Thanks for the report! If the issue happens from the terminal with `flutter run` then this is best raised at [flutter/flutter](https://github.com/flutter/flutter). This issue tracked is for the VS Code extension.

That said, I think this issue already has an issue open at https://github.com/flutter/flutter/issues/18409 you can subscribe to for updates.
