### ISSUE TITLE
No device definitions are available

### ISSUE THREAD

**Issue by vogella** [Dart-Code/Dart-Code#2106]
If I try to create emulator with Dart code, I get the error "No device definitions are found".

See screenshot.

![image](https://user-images.githubusercontent.com/139910/69050763-fd0e3300-0a02-11ea-8d51-f88d5c0eee52.png)

"flutter emulator --create" works after I switch to Java 8 on the command line.

**Comment by DanTup** [comment]
> "flutter emulator --create" works after I switch to Java 8 on the command line

Can you clarify what this bit means? (I'm not very familiar with java :-))

Do you see the same error on the command line if you don't do that?

**Comment by vogella** [comment]
I use sdk man to manage my Java runtime and if I try to run "flutter emulator --create" (my default Java runtime) I receive the error above.

Switching to Java 8 on the command line with the following solves that:
sdk use java 8.0.232.hs-adpt

I would expect that if I start code via the same command line the same JRE is used, not sure if that is true.

**Comment by DanTup** [comment]
Which runtime are you using when it fails? I have some recollection of having to install an older version of the Java runtime for the Android SDK to work, though I'm failing to find anything on this now.

In Flutter we run `avdmanager list device -c` to get a list of definitions - that seems to be what's failing here. Can you try running that command directly with both versions of Java and post the output?

**Comment by vogella** [comment]
Sounds like this is a general issue  with the avdmanager and sdkmanager which should at some point be fixed. See https://issuetracker.google.com/issues/67495440#comment13 

I close this issue, sorry for the noise.

**Comment by DanTup** [comment]
Ah cool, thanks for the link! Seems like there's a fix on the way so it's probably not worth adding special handling for this now - hopefully if anyone hits it they'll find the info in this thread in the meantime until that rolls out :-)

**Comment by th38amorim** [comment]
I have the same problem, I did not understand the way to fix what was given, could you explain again?

**Comment by DanTup** [comment]
@th38amorim I believe the issue was caused by running the Android SDK using the wrong version of Java. I think I remember having to install an older version of Java on my Windows box to get the Android SDK tools working correctly. Installing Android Studio is likely the simplest way though.

**Comment by gabrielmlinassi** [comment]
For me, the problem was because I had not created the emulator on Android Studio. Once I did, it worked without errors.

**Comment by adityaharist** [comment]
when 

> For me, the problem was because I had not created the emulator on Android Studio. Once I did, it worked without errors.

seems still show "No device definitons are available" to me. I had tried by Ctrl+Shift+P, choose Flutter: Launch Emulator, Create Android Emulator, and like :
Flutter: Select Device ,then choose Create Android Emulator"
I'm a new in Dart and Flutter. I don't know how to fix this one.
