### ISSUE TITLE
Code completion for identifiers for pubspec.yaml/analysis_options.yaml

### ISSUE THREAD

**Issue by vogella** [Dart-Code/Dart-Code#2110]
I see issue #101 and #2078 but I don't think the static identifiers are covered by this. Can you also add code completion for example for dependencies.

Would be nice to be able to type: d-> ctrl +space and get dependencies as suggestion.

**Comment by DanTup** [comment]
The server has gained some basic support for this - got CL to expose it in LSP at https://dart-review.googlesource.com/c/sdk/+/173000/.

**Comment by DanTup** [comment]
Fixed (in LSP) by https://github.com/dart-lang/sdk/commit/db263169e5b6f3e20d38e6933fa63497e52dcdda.
