### ISSUE TITLE
No tooltip for warning while debuggin

### ISSUE THREAD

**Issue by vogella** [Dart-Code/Dart-Code#2112]
Looks like the tooltips are not available for warnings / errors if I'm debugging.

Would be nice to still be able to see the messages.
In my example, I hovered a while over the http package without any result. I realized I'm debugging, and had to kill the session to see the warning text.

![image](https://user-images.githubusercontent.com/139910/69139958-debb3c80-0ac1-11ea-96da-a72e6891e36e.png)

**Comment by DanTup** [comment]
This is unfortunately a VS Code limitation. There's an open issue you can 👍 here:

https://github.com/microsoft/vscode/issues/84561
