### ISSUE TITLE
Can't step through external packges after setting breakpont

### ISSUE THREAD

**Issue by bsutton** [Dart-Code/Dart-Code#2114]
Sometimes I need to be able to step through the code of an external package when using the vscode debugger.

I've found that I can set a break point in the external package but when I try to step through the code in the external package the code immediately 'steps out' to the next non-external package line of code.

Once I set a break point in an external package I'm expecting to be able to step through the external package code line by line.

flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Linux, locale en_AU.UTF-8)
    • Flutter version 1.9.1+hotfix.6 at /home/bsutton/apps/flutter
    • Framework revision 68587a0916 (10 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/bsutton/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/bsutton/apps/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/bsutton/apps/android-studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at /home/bsutton/apps/intellij/idea-IC-183.5912.21
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270

[!] Connected device
    ! No devices available

**Comment by DanTup** [comment]
There are two settings that allow you to enable debugging in external libraries and the SDK:

```js
{
"dart.debugExternalLibraries": true,
"dart.debugSdkLibraries": true,
}
```

These are `false` by default so you only step through your code. There's an open issue about making it quicker to toggle this at https://github.com/Dart-Code/Dart-Code/issues/1291.

Let me know if this doesn't work for you!

**Comment by alexandru-daniel-rosca** [comment]
Hi. I have these enabled but it doesn't work for me

**Comment by DanTup** [comment]
@alexandru-daniel-rosca please open a new issue, and include steps to reproduce the issue you're seeing. Thanks!
