### ISSUE TITLE
Debug console inserts extra newlines

### ISSUE THREAD

**Issue by knopp** [Dart-Code/Dart-Code#2119]
Possibly related to https://github.com/Dart-Code/Dart-Code/issues/2118. After updating to latest insiders

Same code sample:
```dart
void main() async {
  print("Hello");
  await Future.delayed(Duration(seconds: 1));
  print("World");
  await Future.delayed(Duration(seconds: 10));
}
```

Outputs
```
Hello

World
```

Note the extra empty line. If `Future.delayed` is removed, output is as expected.

```
Version: 1.41.0-insider
Commit: a825aaaa909ef33eee11cb1d322e9a64981978d2
Date: 2019-11-21T06:40:30.733Z
Electron: 6.1.4
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0
```

**Comment by DanTup** [comment]
Yeah, I noticed that while testing too. I mentioned it at https://github.com/microsoft/vscode/issues/83906#issuecomment-556974066 and that's been fixed - it'll be in tomorrows Insiders :-)
