### ISSUE TITLE
Error hover shows error /warning after the documentation

### ISSUE THREAD

**Issue by vogella** [Dart-Code/Dart-Code#2126]
If I have an error or a warning the error / warning message should be above the documentation, as this is the most important information the user is most likely interested in.

![image](https://user-images.githubusercontent.com/139910/69541012-699bab80-0f88-11ea-813e-0f5b70d1997b.png)

**Comment by DanTup** [comment]
Yeah, this is pretty awful. It's VS Code and I raised it a while back but it's not clear what the plan is (I've added another comment today in the hope of some discussion):

https://github.com/microsoft/vscode/issues/73120

**Comment by DanTup** [comment]
I'll close this since there's nothing we can do here, but please do add a 👍's to the issue above! :-)
