### ISSUE TITLE
Dart DevTools exited with code 66

### ISSUE THREAD

**Issue by advancedtw** [Dart-Code/Dart-Code#2128]
dart tools fails to launch on vscode was working the morning and still works fine with android studio.
vscode 1.40.1  
dart ext 3.6

**Comment by DanTup** [comment]
Could you try capturing a log by running the **Dart: Capture Logs** command, ticking **Command Processes** and **DevTools** then reproducing the issue?

Thanks!

**Comment by advancedtw** [comment]
i was not aware of capture logs and thanks to that i fixed it. i copied devtools-0.1.11 from an other user and now it's working as expected but still I'm wondering what is the recommended way to repopulate  this directory `.pub-cache/hosted/pub.dartlang.org/`
also is it is it normal that my log shows :  Flutter extension: 3.6.0 (not activated)
thanks a bunch 


> [5:57:23 AM] [DevTools] [Info] Spawning /Users/adtw/flutter/bin/cache/dart-sdk/bin/pub with args ["global","run","devtools","--machine","--enable-notifications","--try-ports","10"]
> [5:57:23 AM] [DevTools] [Info]     PID: 556
> [5:57:23 AM] [DevTools] [Error] Could not find a file named "pubspec.yaml" in "/Users/adtw/.pub-cache/hosted/pub.dartlang.org/devtools-0.1.11".
> [5:57:23 AM] [DevTools] [Error] 
> [5:57:24 AM] [DevTools] [Info] Process terminated! 66, null
> [5:57:24 AM] [General] [Error] Dart DevTools exited with code 66
> [5:57:24 AM] [General] [Error] Dart DevTools exited with code 66

**Comment by DanTup** [comment]
Weird - I'm not sure how that folder would end up without a pubspec.

The easiest way to fix is probably running `pub global deactivate devtools` then `pub global activate devtools` (though the second step will be run by the VS Code extension if you try to launch DevTools and it's not activated).

> also is it is it normal that my log shows : Flutter extension: 3.6.0 (not activated)

If you've opened a folder that isn't a Flutter app, this is normal. If it is a Flutter app, then it suggests for some reason we might not be detecting it correctly. If that's the case, please file a new issue with a screenshot showing your folder layout (where the Flutter project is in relation to the top folder you opened) and an [extension log](https://dartcode.org/docs/logging/#extension).

Thanks!

**Comment by bsutton** [comment]
For other readers, I managed to get into this state because I managed to deleted my entire .pub-cache/hosted/pub.dartlang.org/ directory.

The same approach (deactivate/activate) solved the problem.

**Comment by sagarkhurana00786** [comment]
@advancedtw @DanTup @bsutton 
Can Anyone help me I'm getting this issue Dart Dev Tools exited with code 225

**Comment by DanTup** [comment]
@sagarkhurana00786 can you include a screenshot/description of where you're seeing this? If in VS Code, can you capture a log (see https://github.com/Dart-Code/Dart-Code/issues/2128#issuecomment-558306435)? Thanks!

**Comment by sgehrman** [comment]
same issue today.  I did just upgrade flutter.  This worked:  deactivate devtools then pub global activate devtools

**Comment by DanTup** [comment]
A new version of DevTools was released that doesn't have a build suffix, so I would not expect anyone to still see this.

If you do still see it when launching DevTools from within VS Code, please let me know (or [ping me in Discord](https://gitter.im/dart-code/Dart-Code)), I'd like to understand why it's not updating.
