### ISSUE TITLE
No code actions available ever in Python

### ISSUE THREAD

**Issue by rafwaf** [Dart-Code/Dart-Code#2129]
I'm writing code in Python, and I was hoping to refactor out a method. I searched for a way to do that, and that's when I realized that Code actions are never available, regardless of what code I select, even when I click 'ctrl+.'

I don't know what minimal code would replicate this, and I suspect it's not in my own code, so there is probably no point in including it.

I'm wondering if this is happening to me because of something in my local environment/setup or is every Python/VSCode user seeing this bug, and what can I do about it. Let me know what further info you might need.
Thank you.

**Comment by DanTup** [comment]
This repository is for the Dart and Flutter extensions for VS Code. Unfortunately I'm not familiar with the Python extensions - you'd would need to raise in the repo responsible for the relevant Python extension.

Thanks!
