### ISSUE TITLE
Print not working with async

### ISSUE THREAD

**Issue by altherat** [Dart-Code/Dart-Code#2130]
Not sure if this is the correct place to report this issue, but given a simple Dart application that prints a timestamp every second:
```
main(List<String> arguments) async {
  for (int i = 0; i < 10; i++) {
    print(DateTime.now());
    await Future.delayed(const Duration(seconds: 1));
  }
}
```

VSCode is only printing out the first timestamp and then prints the remaining 9 when the program finishes. Also, switching between the debug console and other tabs like "Terminal" during execution will cause the missed print statements to show, so it appears that the debug console is just not refreshing beyond the first time. Using `log` from the `dart:developer` library doesn't have this problem.

Dart version 2.6.1 (stable)
VSCode version 1.40.1
Windows 10

Have tried reinstalling Dart (was using the dev release before) and VSCode and Dart Code plugin but it has not helped.

**Comment by DanTup** [comment]
This is unfortunately a VS Code bug that we started triggering with some recent changes. It's been fixed (https://github.com/microsoft/vscode/issues/83906) but not released yet. You can try the fix out in the VS Code Insiders build to ensure it covers your cases though.
