### ISSUE TITLE
Are there plans to support Wi-Fi debugging?

### ISSUE THREAD

**Issue by ifredom** [Dart-Code/Dart-Code#2135]
Are there plans to support Wi-Fi debugging ?

**Comment by DanTup** [comment]
This is something that would need to be implemented in Flutter.

For iOS, I believe this is a known issue: https://github.com/flutter/flutter/issues/15072

For Android, I think this is already possible - but you need to have `adb` listening over the network. Some phones let you do this directly in their developer settings, but others you need to connect to your machine with a cable and then run `adb tcpip 5555` (where 5555 is the port you want it to listen on).

Then you should be able to run `adb connect <phone ip>:5555` and your device should start showing up in `flutter devices`, and it should work from VS Code the same way as if it was connected with a cable.

**Comment by DanTup** [comment]
Let me know if this doesn't answer the question or anything isn't clear!

**Comment by ifredom** [comment]
> Let me know if this doesn't answer the question or anything isn't clear!

thanks for u replay。i understand,but it's hard to me 。。。。
