### ISSUE TITLE
Linux build on Travis is broken since TS2 upgrade (fails to get @types/mocha)

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#214]
@devoncarew I just saw your name was also on [this page](https://docs.travis-ci.com/user/languages/dart) so maybe you know how this works?

Our Linux build has a really old Node version (`0.10`). I suspect that's not normal on Travis (else others would complain) so I wonder if it's a result of the `language: dart` setting. I don't know what this actually does - is it using some pre-built image that may need updating, or is it just a script that downloads Dart?

I tried [setting the node version](https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Choosing-Node-versions-to-test-against) in the config file but it didn't work (probably because it only works if using `language: node`?).

Maybe we can just take `language; dart` out and use a script similar to we have on AppVeyor to download Dart (that one was written in PowerShell so isn't directly usable). I might give that a go next week if nobody has any ideas.

cc @sethladd @a14n

**Comment by a14n** [comment]
Basically you can not mix `language` in your travis file. It's like a predefined image.

To use another version of node in a `language: dart` setup, you have to install it in the `before_install` section. `apt update && apt install node` should get the last version available on ubuntu 12.04.

**Comment by DanTup** [comment]
I'll give that a go - thanks!

**Comment by DanTup** [comment]
@a14n That failed :(

[code]
/home/travis/build.sh: line 57: apt: command not found
[/code]

Do you know who created the `language: dart` thing for Travis (and how?). Maybe it could be updated, or I could just take the clever part (setting up the latest SDK correctly) and use it outside of that image?

**Comment by a14n** [comment]
`apt` is perhaps to young for ubuntu 12.04 (the underliing os). Please try instead : `apt-get update && apt-get install node`. (I don't think your .travis.yml is valid because of https://github.com/Dart-Code/Dart-Code/blob/63352aefc1264ef79dd5bf656ee1dcac2cc74ee9/.travis.yml#L12-L16 ; you should use a single line or extract it into a script file)

I'm not really sure apt-get will work because you don't have sudo inside container (re. https://github.com/Dart-Code/Dart-Code/blob/63352aefc1264ef79dd5bf656ee1dcac2cc74ee9/.travis.yml#L1)

>Do you know who created the language: dart thing for Travis (and how?).

It's me :)

**Comment by DanTup** [comment]
> Please try instead : `apt-get update && apt-get install node`
> I'm not really sure apt-get will work because you don't have sudo inside container

I removed the `sudo: false` and tried that, seems to have installed node, yet `node --version` was still old:

https://travis-ci.org/Dart-Code/Dart-Code/jobs/177050807

Seems to be using node from `/home/travis/.nvm/v0.10.36/bin/node`. I can't find any way online to change this without using `language: node` :(

> I don't think your .travis.yml is valid

This does seem to work ok, comes through in the "View Config" section in Travis all on one line. It was copied from the [VS Code docs](https://code.visualstudio.com/Docs/extensions/testing-extensions#_running-tests-automatically-on-travis-ci-build-machines).

> It's me :)

So how did you build it? Is it just some scripts that fetch/download Dart, or is it built as a machine image? (I presume the former, else you'd have to keep updating it?). If it's scripts, would you be able to share them so I could drop the `language: dart` and just fetch Dart? (This is what we do for AppVeyor but I don't have easy access to a Linux box to port it, and the round-trip times debugging on Travis are super-slow!).

**Comment by DanTup** [comment]
Fixed in #217.

**Comment by a14n** [comment]
`language: dart` is implemented at https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/dart.rb

**Comment by DanTup** [comment]
Cool, thanks. Looks like we don't need it for now though, thanks for all your help!
