### ISSUE TITLE
Tweak Observatory port regex to include full URL

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#215]
There's a breaking change coming in the Observatory URLs - our current regex won't handle this and needs updating:

https://groups.google.com/a/dartlang.org/d/msg/announce/VxSw-V5tx8k/wPV0GfX7BwAJ

> In Dart 1.22 the URL to the service protocol and Observatory will change.
> 
> The message printed by the VM will change:
> 
> Current base URL:
> 
> `Observatory listening on http://127.0.0.1:54804/`
> 
> New base URL:
> 
> `Observatory listening on http://127.0.0.1:54804/<token>/`
> 
> For example:
> 
> `Observatory listening on http://127.0.0.1:54804/PTwjm8Ii8qg=/`
> 
> Clients of the service protocol will need to be updated to scrape the whole URL instead of just the host + port.

**Comment by devoncarew** [comment]
+1, I came here to create an issue for this and found one already existed :)

**Comment by DanTup** [comment]
Fixed it, but the lack of trailing slash in current SDKs made it a little dirty (I went with adding the slash to the uri, so there was an opposite change where we construct the uri to `ws`).

**Comment by devoncarew** [comment]
I think this is the first client to convert over to the new url format :)

**Comment by DanTup** [comment]
Heh, cool. I figured it was best to do sooner rather than later to minimise chances of someone grabbing a new SDK and debugging being broken. Dart Code users tend to update fairly quickly though, so probably not a big deal.
