### ISSUE TITLE
Autocomplete doesn't work with generic vars

### ISSUE THREAD

**Issue by llooz** [Dart-Code/Dart-Code#2155]
Autocomplete doesn't work for variables of generic type and if a cast is used a warning is generated

e.g.

```dart
abstract class MyItem {
  String field1;
}

void myMethod<T extends MyItem>(T item) {
  var field1 = (item as MyItem).field1;

}
```

gives
```
{
	"resource": "/Users/lucalooz/repos/generics-dart/bin/main.dart",
	"owner": "dart",
	"code": "unnecessary_cast",
	"severity": 2,
	"message": "Unnecessary cast.\nTry removing the cast.",
	"source": "dart",
	"startLineNumber": 30,
	"startColumn": 17,
	"endLineNumber": 30,
	"endColumn": 31,
	"tags": []
}
```

**Comment by DanTup** [comment]
Thanks for the report! This appears to be an SDK issue (the code completion comes from the analysis server, which is part of the SDK). I think it's already been reported here:

https://github.com/dart-lang/sdk/issues/24255

I'll close this as a dupe - please 👍  and/or subscribe to that issue for updates. Thanks!
