### ISSUE TITLE
Change "Step Back" to use "RestartFrame"

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#2171]
Turns out the DAP has a message for RestartFrame, and using StepBack for this wasn't necessary:

https://github.com/microsoft/vscode-debugadapter-node/issues/43

**Comment by nbros** [comment]
VS Code v1.41 also has a new inline action in the **call stack** view that seems like a good place to put this action:
![restart frame](https://code.visualstudio.com/assets/updates/1_41/restart-frame.png)
https://code.visualstudio.com/updates/v1_41#_restart-frame-as-an-inline-action-in-the-call-stack-view

**Comment by DanTup** [comment]
It was that release note that made me realise I'd used the wrong thing 😄 I believe by moving it to use the correct request, it will automatically appear here :-)

**Comment by nbros** [comment]
Good 🙂
Would that allow restarting from any selected frame even the current one? Currently the "Step Back" command seems to restart from the parent frame instead of the current frame, with confusing results when the top method in the stack is async (the whole stack changes instead of just the top frame when stepping back through an async gap).

**Comment by DanTup** [comment]
> Would that allow restarting from any selected frame even the current one?

Yep!

> Currently the "Step Back" command seems to restart from the parent frame instead of the current frame

Hmm, I'm not sure this would change. Currently [we send Rewind](https://github.com/Dart-Code/Dart-Code/blob/master/src/debug/dart_debug_impl.ts#L1102) with no frame offset which means it defaults to 1, which is the lowest value allowed (see [docs](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#resume)). In my testing, it moved you up a frame, but such that "step into" would go back into the function you were previously in?

> confusing results when the top method in the stack is async (the whole stack changes instead of just the top frame when stepping back through an async gap)

I'm not sure I understand what you mean, butI suspect this feature is acting upon the real stack rather than the "async stack" we show (which is simplified to make async code easier to understand).

**Comment by nbros** [comment]
Thank you for your explanation, I hadn't realized that the Step Back action was rewinding to the call site in the parent frame instead of the beginning of the current frame.

> I'm not sure I understand what you mean, but I suspect this feature is acting upon the real stack rather than the "async stack" we show (which is simplified to make async code easier to understand).

That is a good explanation, thanks!

**Comment by DanTup** [comment]
I've changed this over and it now works from the calls stack. However, the thing mentioned above is weird (you can only restart parent frames) and trying to do it on the current frame fails because Rewind doesn't support restarting from the current stack frame. VS Code also fails to render the error (I've opened https://github.com/microsoft/vscode/issues/87605) so this failure is currently silent.
