### ISSUE TITLE
dio_cookie_manager package is not being imported

### ISSUE THREAD

**Issue by obsessedwithperfection** [Dart-Code/Dart-Code#2173]
Compiler message:                                                       
lib/form.dart:4:8: Error: Error when reading '/usr/flutter/.pub-cache/hosted/pub.dartlang.org/dio_cookie_manager-1.0.0/lib/cookie_manager.dart': No such file or directory
import 'package:dio_cookie_manager/cookie_manager.dart';   

Tried flutter packages get
Tried restarting emulator and vs studio

**Comment by DanTup** [comment]
Does the file mentioned in the path exist?

If the path is incorrect, can you try deleting the `.packages` file and run `flutter packages get` again to see if that helps?

**Comment by obsessedwithperfection** [comment]
No It is not working
- Deleted .packages file
- rerun flutter packages get
- reopen the vs code
- vs code version 1.41.0

This is how I have installed the package.
dependencies:
dio_cookie_manager: 1.0.0

This is how I am importing it
import 'package:dio_cookie_manager/cookie_manager.dart';

Thank you

**Comment by DanTup** [comment]
In the error message there is a full path:

> /usr/flutter/.pub-cache/hosted/pub.dartlang.org/dio_cookie_manager-1.0.0/lib/cookie_manager.dart'

Is there a file at that location?

**Comment by obsessedwithperfection** [comment]
Exactly. There is no file named "cookie_manager.dart" in location /usr/flutter/.pub-cache/hosted/pub.dartlang.org/dio_cookie_manager-1.0.0/lib/.

There is actually a file named "dio_cookie_manager" and in lib folder.There is another folder "src" in lib folder and in that src folder there is a file named "cookie_mgr.dart"

Now there is no error in importing the package.

**Comment by DanTup** [comment]
I just downloaded v1.0.0 of `dio_cookie_manager` and it does have have a file at `lib/dio_cookie_manager.dart` so I think the one in your pub cache is broken. Please try running `flutter packages cache repair` and see if the file appears once that completes.

**Comment by DanTup** [comment]
(you should be importing the one from `lib` directly and not the one from the `src`. It's bad practice to import from another packages `src` folder - that is intended to be private)

**Comment by obsessedwithperfection** [comment]
I got it. Thank you

**Comment by DanTup** [comment]
Great - to confirm - `flutter packages cache repair` that fixed it?

**Comment by obsessedwithperfection** [comment]
you know this is exactly what I am saying there is a file name dio_cookie_manager.dart not just cookie_manager.dart. Do you want to say that there should be cookie_manager.dart file in lib folder?

**Comment by DanTup** [comment]
Yep, there should. And I think running `flutter packages cache repair` should bring it back (it will repair any missing packages in that folder).

If that does not work, you could try deleting the `/usr/flutter/.pub-cache/hosted/pub.dartlang.org/dio_cookie_manager-1.0.0` folder, and then run `flutter packages get` from your project and it should be downloaded again.

**Comment by obsessedwithperfection** [comment]
ok flutter packages cache repair is running

**Comment by DanTup** [comment]
Ok, it shouldn't take long - let me know if it worked (and if not, try removing the one folder I mentioned and re-run `flutter packages get`).

**Comment by obsessedwithperfection** [comment]
it is still running

**Comment by DanTup** [comment]
Oh, that doesn't sound very good - it only took a minute or two for me (though it may depend how many packages and versions you've used in total). Is it showing output on the screen as it checks each package?

It may be faster to cancel (`Ctrl`+`C`) and just try with the one package (delete the folder mentioned above and re-run `flutter packages get`) instead.

**Comment by obsessedwithperfection** [comment]
- deleted dio_cookie_manager-1.0.0
- ran flutter packages get

still can not find cookie_manager.dart in lib folder

**Comment by obsessedwithperfection** [comment]
![flutter dio](https://user-images.githubusercontent.com/32835974/71094496-14426b00-21d1-11ea-9dab-1696b7cf8d90.png)

**Comment by DanTup** [comment]
Sorry, I mixed up the filenames `dio_cookie_manager` and `cookie_manager`. The file in the package is named `dio_cookie_manager` so I think the import should be `package:dio_cookie_manager/dio_cookie_manager.dart` - I think the readme has a mistake.

**Comment by DanTup** [comment]
(I realise you actually pointed this file out above - I did not read it properly 🙈). If you import that file, does everything work? The source code looks like https://github.com/flutterchina/dio/tree/cbf5bbce05415344af06d98c37c162267fbef23e/plugins/cookie_manager/lib, which also only contains the `dio_` version of that file.

**Comment by obsessedwithperfection** [comment]
This is exactly what I was saying when I import  this
 "import 'package:dio_cookie_manager/dio_cookie_manager.dart';"

then it works

when i  import this "import 'package:dio_cookie_manager/cookie_manager.dart';" then it does not work. it gives error message.

**Comment by obsessedwithperfection** [comment]
and yes I think dio_cookie_manager team has a mistake in their readme file.

**Comment by DanTup** [comment]
Got it - sorry for the confusion. I think that is the correct fix, I think `dio_cookie_manager/cookie_manager.dart';` as listed in their readme is a mistake and should say `_dio`.

**Comment by obsessedwithperfection** [comment]
Thank you very much for confirming. So should I contact them or you will?

**Comment by DanTup** [comment]
Go ahead - it's probably better coming from a user of the plugin :-)
