### ISSUE TITLE
Prompts to fetch packages appear much more often than expected

### ISSUE THREAD

**Issue by stepankuzmin** [Dart-Code/Dart-Code#2174]
I'm constantly getting `promptToGetPackages`, although I didn't modify `pubspec.yaml` contents. Perhaps it is worth checking hashes instead of the modified time?

**Comment by DanTup** [comment]
I'm not sure how this would work - the files have different contents so hashes would never match. Checking the package names/versions would be complicated because we'd have to both parse the files and figure out the correct versions.

The current mechanism can result in false-positives, but it shouldn't happen constantly. Can you check the timestamps on the two files next time you see this and we can try to understand why they look out-of-date if they're not? Thanks!

**Comment by stepankuzmin** [comment]
Yep, I've tried to bump modified time with touching `.packages`, and checked `fs.statSync().mtime` for both `pubspec.yaml` and `.packages`. Despite that the `.packages` where modified after `pubspec.yaml` I'm still getting `promptToGetPackages`.

**Comment by DanTup** [comment]
If I add some additional logging to capture the reason why this code believes `pub get` needs running and upload a build, would you mind running it to see what's logging?

**Comment by stepankuzmin** [comment]
> If I add some additional logging to capture the reason why this code believes `pub get` needs running and upload a dev build, would you mind running it to see what's logged?

Sure

**Comment by DanTup** [comment]
Ok there's a vsix file here:

https://github.com/Dart-Code/Dart-Code/releases/tag/v3.7.1-dev.log-get-packages

Download it and install by running the *Extensions: Install from VSIX* command in VS Code ([more details here](https://dartcode.org/docs/installing-a-preview-release/)). It's the same build as v3.7.1 but it will log some info to the console (Help -> Toggle Developer Tools) as warnings when checking if packages need fetching:

![Screenshot 2019-12-17 at 3 11 44 pm](https://user-images.githubusercontent.com/1078012/71007838-905c8600-20df-11ea-9fcb-befd2a260863.png)

Please let me know what this shows. Thanks!

**Comment by stepankuzmin** [comment]
```shell
ls -las .packages pubspec.yaml
24 -rw-r--r--  1 stepankuzmin  ...  9803 Dec 18 12:11 .packages
 8 -rw-r--r--  1 stepankuzmin  ...  3127 Dec 18 12:07 pubspec.yaml
```

<img width="1135" alt="2019-12-18_12-15-49" src="https://user-images.githubusercontent.com/533564/71072774-38318c80-2190-11ea-9fd2-d58e8d0db3fa.png">

**Comment by DanTup** [comment]
@stepankuzmin Thanks! It looks like the code found 4 folders that have no `.packages` files and thinks they need to have packages fetched. Do you know what the paths for those folders are? Are they Dart projects? If so, do you know why they don't have `.packages` files?

**Comment by stepankuzmin** [comment]
That's project dependencies that are listed in the root `pubspec.yaml`

```yaml
package:
  path: ./path-to-package
```

**Comment by DanTup** [comment]
Ok, so if they're packages and have `pubspec.yaml`'s that list dependencies, they also need to have `pub get` run? If you accept the prompt and let it run `pub get`, then it should create `.packages` files for each of those, and then the prompts should stop.

**Comment by stepankuzmin** [comment]
I'm using `flutter` and then I run `flutter pub get` it doesn't create `.packages` file in subdirectories. Maybe this is because of the packages using only `dev_dependencies` 🤔

**Comment by DanTup** [comment]
Are you running it inside the subdirectory? I don't think it recurses by default. When I run `flutter pub get` in a package even with no dependencies (or dev_dependencies) it still creates a `.packages` file that has the package itself in it:

```
# Generated by pub on 2019-12-18 13:28:50.192758.
sub_proj:lib/
```

Clicking the button on the VS Code prompt should automatically run it in each of the 4 folders though, which should then create each `.packages` file.

**Comment by DanTup** [comment]
Closing this due to no response, but if you still see this and can answer the question above, let me know and I'm happy to do some more debugging.
