### ISSUE TITLE
Type inferrence is good enough to avoid the list hint

### ISSUE THREAD

**Issue by shyndman** [Dart-Code/Dart-Code#2176]
When code-completing a typed list in an argument list, a type annotation is included. ie

```
Stack(
  children: /* !!! */ <Widget>[],
)
```

 As far as I can tell, this not required in the general case. I'd consider getting rid of it, as it's a little noisy.

**Comment by DanTup** [comment]
@pq I tracked this back to https://github.com/flutter/flutter-intellij/issues/832 but it's not clear why it's needed (maybe in the past this was necessary?). I'd agree it seems unnecessary and noisy (at least for those not using lints for explicit types everywhere). WDYT?

**Comment by nbros** [comment]
FWIW [Effective Dart](https://dart.dev/guides/language/effective-dart/usage#collections) allows both `[]` and `<Widget>[]`
Maybe make it an option?

**Comment by DanTup** [comment]
@pq ping! Do you know if this is required? If it's to satisfy the always_specify_types lint, maybe it could be conditional based on that?

**Comment by pq** [comment]
Hey @DanTup.  Sorry for the slow  reply!  This should now be fixed as of https://github.com/dart-lang/sdk/issues/41303 and https://github.com/dart-lang/sdk/issues/41517.

**Comment by DanTup** [comment]
@pq perfect, thanks!
