### ISSUE TITLE
How can I config working directory in lauch.json

### ISSUE THREAD

**Issue by taojigu** [Dart-Code/Dart-Code#2177]
In Android Studio  , I can config a working directory (for example : 
    /Users/gujitao001/Documents/temp/demo_plugin/example),  when debugging flutter_tools.dart.

How could I setting working directory in lauch.json of  VSCode ?
"cwd" seems not help, its value is concated with "program"(flutter_tools.dart) ,which is not the working directory

**Comment by DanTup** [comment]
`"cwd"` is the correct thing, but if `"program"` is relative, it's assumed to be relative to `"cwd"`. You can fix this by using an absolute path, or a variable like `${workspaceFolder}`. For example, this `launch.json` inside `flutter_tools/.vscode` allows me to debug the flutter_tools code while analyzing the gallery.

```js
"configurations": [
	{
		"name": "flutter_tools",
		"type": "dart",
		"request": "launch",
		"program": "${workspaceFolder}/bin/flutter_tools.dart",
		"cwd": "/Users/danny/Dev/flutter/examples/flutter_gallery",
		"args": ["analyze"]
	}
]
```

Let me know if you still have issues!

**Comment by taojigu** [comment]
Thank you . It works.
