### ISSUE TITLE
VS Code "Open in Xcode" does nothing

### ISSUE THREAD

**Issue by jmagman** [Dart-Code/Dart-Code#2178]
### Steps to Reproduce
Open Flutter directory in VS Code on Mac OS X 10.14.6.
Context-click on ios directory > Open in Xcode

Nothing happens.

### Logs
I see this log when I reproduce:
```
error	10:34:19.546912 -0800	Code Helper (Renderer)	nw_path_close_fd Failed to close guarded necp fd 48 [9: Bad file descriptor]
```

Flutter extension is marked "not activated" when I Capture Logs (no actual log lines when I reproduced) but I'm not sure if that's related.  It looks enabled in the Extensions UI.
```
Dart Code extension: 3.7.1
Flutter extension: 3.7.1 (not activated)
VS Code: 1.41.0
Platform: mac
Workspace type: Flutter
Multi-root?: false
Dart SDK:
    Loc: /Users/m/Projects/flutter/bin/cache/dart-sdk
    Ver: 2.8.0-edge.fe9f30c3896e7146195ea52434c5082b309b6ee0
Flutter SDK:
    Loc: /Users/m/Projects/flutter
    Ver: 1.13.3-pre.59
HTTP_PROXY: undefined
NO_PROXY: undefined
```
<img width="454" alt="Screen Shot 2019-12-18 at 10 44 36 AM" src="https://user-images.githubusercontent.com/682784/71113943-8ab87c00-2183-11ea-91e2-184057fb37b9.png">

**Comment by DanTup** [comment]
I can't repro this - it seems to work ok. We look in the folder for `xcworkspace`/`xcodeproj` files (preferring `xcworkspace`) and then open it with:

```
open -a Xcode [path-to-file]
```

If you try running that command from a terminal, does it work?

**Comment by jmagman** [comment]
> If you try running that command from a terminal, does it work?

Ah, my Xcode is named Xcode_11-3.
```
open -a Xcode [path-to-file]
Unable to find application named 'Xcode'
```
You could change it to `open [path-to-file]` since that should also open in Xcode.
I'm okay with you closing this, too, since I'm not using the default app name.

**Comment by DanTup** [comment]
If opening the file works directly, I'll change it to do that. I'll also see if I can improve how it fails if it doesn't work (silently doing nothing isn't a good experience - seems like we should be able to detect this and display a message).
