### ISSUE TITLE
Can't create Flutter web project

### ISSUE THREAD

**Issue by xFabifont** [Dart-Code/Dart-Code#2186]
I want to create a web project with flutter with vscode. I installed the flutter extension but I only have "New Project" instead of "New web Project".

**Comment by DanTup** [comment]
This is expected - the `Flutter: New Web Project` command was temporary while Flutter's web support was forked from Flutter. Now that it's been un-forked, you should just use the standard `New Project` command.

You'll need to be on the dev/master channel for web support right now (and opt-in by running `flutter config --enable-web`) as t's still in preview. There's more info on this here:

https://flutter.dev/docs/get-started/web

**Comment by DanTup** [comment]
Let me know if you have any problems getting this to work!
