### ISSUE TITLE
Dart Code Completion not working VS code

### ISSUE THREAD

**Issue by Chaitanyabsprip** [Dart-Code/Dart-Code#2188]
I have set path to Dart SDK and Flutter SDK, and I am currently writing a dart script in a standalone file which is not in any kind of project.  VS code doesn't show any code completion suggestion and even when I press Ctrl+Space it doesn't show any in context to dart language.

**Comment by DanTup** [comment]
Are you opening a folder, or just a file? If you open a folder, things should still work (if not, it's a bug). If you're opening a file directly (without opening its containing folder in VS Code) then this is a known limitation, but you should see this notification when you open the first file:

<img width="555" alt="Screenshot 2019-12-26 at 21 20 44" src="https://user-images.githubusercontent.com/1078012/71490938-99f39580-2825-11ea-8e04-a6faa0364dcc.png">

Can you confirm which it is - and if the latter, whether the notification appears or not? Thanks!

**Comment by Chaitanyabsprip** [comment]
> Are you opening a folder, or just a file? If you open a folder, things should still work (if not, it's a bug). If you're opening a file directly (without opening its containing folder in VS Code) then this is a known limitation, but you should see this notification when you open the first file:
> 
> <img alt="Screenshot 2019-12-26 at 21 20 44" width="555" src="https://user-images.githubusercontent.com/1078012/71490938-99f39580-2825-11ea-8e04-a6faa0364dcc.png">
> 
> Can you confirm which it is - and if the latter, whether the notification appears or not? Thanks!

I was using a dart file out of its folder.  This helped. Thank you
