### ISSUE TITLE
VS Code IntelliSense: Builder class Refactoring

### ISSUE THREAD

**Issue by triethyl** [Dart-Code/Dart-Code#2189]
Most widgets have the option to **Remove this Widget** which very nicely removes the widget and adds it's child/body into the parent Widget.

But while working with the **Builder** class, I did not find such a thing. It would be helpful if we added the utility to Remove the Widget for Builder as well.

![https://imgshare.io/images/2019/12/27/aa.png](https://imgshare.io/images/2019/12/27/aa.png)

**Comment by DanTup** [comment]
These refactors all come directly from the SDK, so this would need to be implemented there (and it' would show up automatically when using an SDK that supported it). Could you re-raise the issue at https://github.com/dart-lang/sdk? Thanks!

**Comment by triethyl** [comment]
It's raised!
