### ISSUE TITLE
can't detect devtools correctly

### ISSUE THREAD

**Issue by mingoal** [Dart-Code/Dart-Code#2191]
`devtools` can be started successfully from *command line*, but can't be detected by dart vscode plugin.
<img width="597" alt="devtools-vscode-plugin-bug" src="https://user-images.githubusercontent.com/15058046/71551317-c07d2080-2a1f-11ea-9985-14ce3f892667.png">

The possible reason is I manually copy `devtools` as the `pub` command fail to do it. After that, the `devtools` is installed correctly. Not sure some actions are missed or not during installation. But `devtools` works from command line and the service works correctly. The only thing matters is **don't know which port is for flutter debug session** to be connected manually.

`flutter pub global activate devtools` output
```
Precompiling executables...
Precompiled devtools:bin\devtools.
Installed executable devtools.
Activated devtools 0.1.13.
```

```
> flutter --version
Flutter 1.12.13+hotfix.5 • channel stable •
https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (3 weeks ago) • 2019-12-10 18:15:01
-0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0
```
Dart VScode plugin version: 3.6.0.

**Comment by DanTup** [comment]
Depending on how you installed Flutter, you may have two Pub cache folders (the standard Dart one, and one in the Flutter installation folder). This means there are two sets of globally-activated packages.

The best thing is just to click the "Activate DevTools" button in VS Code and it will activate for the Pub Cache it's using and everything should work fine. If this doesn't work, please let me know exactly what the issue you see is.

**Comment by mingoal** [comment]
Happy New Year.
Thanks for your response.

The "Activate DevTools" doesn't work on my computer (windows 10). I solved this by:
1. install dart-sdk
2. manually resolve problem with installation of 'pub global activate devtools'

There should two copies of devtools, but it works so I am fine with it.

I guess in windows, 'flutter pub global activate devtools' is required but some installation scripts calls 'pub global activate devtools'.

**Comment by DanTup** [comment]
> The "Activate DevTools" doesn't work on my computer (windows 10). I

Can you clarify what "doesn't work" means? Did it give an error? If so, what was it?

> I guess in windows, 'flutter pub global activate devtools' is required but some installation scripts calls 'pub global activate devtools'.

It depends on how you installed Flutter. If you used the zip file, then `flutter` will have its own Pub cache, so you will have two copies of "globally activated" packages. `flutter` will write to one and `pub` will use the other.

This shouldn't cause a problem other than you may end up activating twice. If the "Activate DevTools" button in VS Code is not working, then that's a bug regardless (but I need more info on how/why it's not working). Thanks!

**Comment by mingoal** [comment]
Yes. I use the zip file of flutter.

The command used by "Activate DevTools" has one bug which fails to install the DevTools on Windows 10. Something wrong with the copy action. So I need to manually copy those files to finish the installation. After that, devtools works correctly.

On windows, to install devtools, it should use `flutter pub global activate devtools`, but this plugin always uses `pub global activate devtools`. I assume it's the root cause why it fails.

**Comment by DanTup** [comment]
> The command used by "Activate DevTools" has one bug which fails to install the DevTools on Windows 10. Something wrong with the copy action. 

Are you able to provide more details (for example the exact error message/screenshot)?

> this plugin always uses `pub global activate devtools`. I assume it's the root cause why it fails.

This should be fine, it will just activate in the standard pub cache instead of the Flutter-specific one.

**Comment by mingoal** [comment]
@DanTup more details, please refer to 
https://github.com/flutter/flutter/issues/40331#issuecomment-569462615

**Comment by DanTup** [comment]
@mingoal that seems like a permissions or file locking error when installing packages. I don't think that's related to VS Code. If you're not activating DevTools with `pub` when VS Code will fail to find it. If you do activate with `pub` (or manually copy it if you have permissions issues with the pub cache) then VS Code should detect it.

If running `pub global list` shows DevTools and VS Code does not consider it installed, that's a bug (though it's not clear if that's the case). If it's not listed in `pub global list` then I think this is working as expected.

**Comment by DanTup** [comment]
>  the issue with this plugin on windows is: it should use `flutter pub global activate devtools` instead of `pub global activate devtools`

We use `pub` in the extension because we use DevTools for both Flutter and Dart CLI. It should make no difference unless you used the Zip version of Flutter (in which case you have two sets of globally-activated packages, though it should still not cause any problems).

Switching to the `flutter` version could result in users seeing prompts to install or upgrade DevTools multiple times if they switch between Flutter and non-Flutter projects, and I'd like to avoid that unless there are concrete issues with using this (but so far I don't believe you issues are related to this).

If the issue is intermittent (you mentioned sometimes `flutter pub get` gives permissions errors) and you have not put Flutter somewhere that requires elevated permissions, could it be antivirus software locking files (for example see https://github.com/dart-lang/pub/issues/1798)

**Comment by mingoal** [comment]
Thanks for your response.

Is it possible to detect what is used on current running machine. The official recommendation on Windows is unzipping way. It maybe run into same situation.

The installation should not caused by anti-virus application. because there have two ways make it work.

manually copy files without admin rights and sometimes re-run 'flutter pub get' works after encounter this error

**Comment by DanTup** [comment]
> Is it possible to detect what is used on current running machine

I'm not sure what you mean. I don't see a good reason to change how this works though, as it will introduce other issues with no obvious benefits. It's entirely acceptable to install DevTools with `pub global activate devtools` and then run it with `pub global run devtools`, as this is exactly how you would install/run it if you were not using Flutter (see https://dart.dev/tools/dart-devtools#1-install-devtools).

If you get an error when running `pub global activate devtools` then you may be hitting an issue like https://github.com/dart-lang/pub/issues/1798 and it would be better to track down the cause of that issue than to change the VS Code extension. If you can reproduce it consistently from the command line (without VS Code) then it may be worth filing an issue with pub (or commenting on the one linked above).
