### ISSUE TITLE
High cpu usage when edit dart code using macvim on mac os.

### ISSUE THREAD

**Issue by fftyjw** [Dart-Code/Dart-Code#2194]
I profile the dart process with instruments. It looks like there is an endless loop.
![image](https://user-images.githubusercontent.com/14770930/71581714-79874c00-2b41-11ea-890b-c22a648c11af.png)
![image](https://user-images.githubusercontent.com/14770930/71581734-97ed4780-2b41-11ea-9a11-667d05bddc5f.png)

**Comment by DanTup** [comment]
Are you using the Dart SDK's LSP server? Can you reliably repro this and provide instructions?

FWIW, this repository is for the VS Code extension, so if you're using Vim and the LSP server, this should be raised at https://github.com/dart-lang/sdk (though please CC me, as I'm wondering whether this may be related to other crashes on the analyzer I've seen reports of but been unable to repro/track down).

**Comment by fftyjw** [comment]
Tanks for you reply. Yes , I am using dart LSP server. I have raised an new issue here: 
https://github.com/dart-lang/sdk/issues/39967

**Comment by DanTup** [comment]
Closing this as it was moved to the SDK repo above and doesn't seem related to the VS Code extension.
