### ISSUE TITLE
Code completion does not behave correctly

### ISSUE THREAD

**Issue by fusion44** [Dart-Code/Dart-Code#2197]
Hi!

I have a problem with code completion with my project. It worked up until a certain point but then stopped working. I first noticed the issue some time during the holidays. I can't pinpoint to a specific version of VSCode, Dart-Code or the Flutter SDK as I've tried several different version and combinations by downgrading.

TLTR; Dart-Code can analyze my code but fails to provide quick fixes.

### What doesn't work:
* Code completion with classes from within my project
* Quick Fixes (missing import statements, remove unused imports, surround with new widget, etc)
  
<a href="https://user-images.githubusercontent.com/503952/71763642-79d76c80-2ede-11ea-9929-b5889a0a75a4.png"><img src="https://user-images.githubusercontent.com/503952/71763642-79d76c80-2ede-11ea-9929-b5889a0a75a4.png" height="150"></a><a href="https://user-images.githubusercontent.com/503952/71763646-82c83e00-2ede-11ea-849d-9bbb318fcea6.png"><img src="https://user-images.githubusercontent.com/503952/71763646-82c83e00-2ede-11ea-849d-9bbb318fcea6.png" height="150"></a><a href="https://user-images.githubusercontent.com/503952/71763647-82c83e00-2ede-11ea-8e77-c7496c5db778.png"><img src="https://user-images.githubusercontent.com/503952/71763647-82c83e00-2ede-11ea-8e77-c7496c5db778.png" height="150"></a>

### What works:
* Code completion of external packages from pub
* Code formatting
* Static analysis (using pedantic rules)
* Refactoring like renaming classes
* Classes are found without problem once I add the import statements manually

### What I've tried (and didn't fix the problem)
* Downgrading versions of VSCode, Dart-Code and Flutter SDK
* Deleting all generated files:
  ```sh 
  rm -rf .dart_tool/ build/ .flutter-plugins .flutter-plugins-dependencies .packages
  ```
Strange occurrence: Deleting the files worked once and the next morning code completion the problem magically reappeared. Deleting doesn't work anymore.
* Checkout a fresh copy of the repository on another PC and try again
* Remove pedantic code analyzer
* I've looked at https://github.com/Dart-Code/Dart-Code/issues/1846 and https://github.com/Dart-Code/Dart-Code/issues/1742. Both seem unrelated to me.
* Check out an older version of my code

The problem doesn't appear when I create a new project using `flutter create myproject`. I've added the analyzer logs to this gist: https://gist.github.com/fusion44/87bf104afba4cf1edcecf80781a75522.

My repository: https://github.com/fusion44/sendmany

Any idea what might cause this? Thank you!

**Comment by DanTup** [comment]
Could you give a concrete example for something that isn't working ("stopped working" is a bit vague - it's not clear if you get no completions, not the things you expect, etc)? Ideally:

- A zip of the project as it is on your disk (including hidden folders like `.dart_tool`
- The exact version of Flutter you're using (output of `flutter doctor -v` or `flutter --version`)
- The exact location you're invoking completion/checking code actions in which file
- A specific item that is not appearing but should
- A log file (using **Dart: Capture Logs** and ticking only the Analyzer option)

If you're collecting a log for code actions, be aware that VS Code requests code actions when the cursor moves, and not when you open the menu - so you need to start logging and then move the cursor to the location (rather than just opening the code action menu)

Something else to try would be deleting your `~/.dartServer` folder. It has some caches for the analysis server. Usually it maintains and versions them itself, but I have seen issues where deleting it seemed to fix some strange issues.

Thanks!

**Comment by fusion44** [comment]
Above I wrote
> ### What doesn't work:
> * Code completion with classes from within my project
> * Quick Fixes (missing import statements, remove unused imports, surround with new widget, etc)

maybe it wasn't clear enough, sorry. :) I've created a small video showing the problem with some commentary from me. I've sent a link to my GDrive with the archive and the video to logs@dartcode.org as I don't want to post it publicly here.

Here's the logfile captured by DartCode:
https://gist.github.com/fusion44/914b035cb435fb7ea6c04e0a5e90ce68
I can't see any big difference than whats in the other log files posted earlier. 

Here's the flutter doctor output:
```
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_GB.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

• No issues found!

sendmany on  master [!?] 
❯ flutter --version
Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (4 weeks ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0
```

> * The exact location you're invoking completion/checking code actions in which file
> * A specific item that is not appearing but should
> * A log file (using Dart: Capture Logs and ticking only the Analyzer option)

In the video you can see that I try to use the Int64 and the LightningAddress class in my main.dart file as an example. It doesn't really matter where I invoke the command as Flutter and Dart specific items are missing everyhere within the project.

I've tried again with deleted `~/.dartServer` but this didn't help. I've also completely removed every Dart and Flutter config file and reinstalled the SDK from scratch, but the problem persists.

**Comment by DanTup** [comment]
Thanks! I was able to repro this from your video and code.

I traced the issue back to the `analysis_options.yaml` file in your `lib` folder. I believe what's happening is the analysis server is finding that file in `lib` and then treating that folder as the project root - which means it doesn't find the referenced packages. If you rename this file away and reload VS Code, the quick-fixes seem to appear.

As far as I can tell, the `analysis_options.yaml` file should be alongside the `pubspec.yaml` (see https://dart.dev/guides/language/analysis-options#the-analysis-options-file), though I do recall seeing discussion about it being nested. It's slightly strange that if you manually add the `import` then things work - so it's possible this is a bug - @bwilkerson might be able to confirm.

**Comment by bwilkerson** [comment]
Yes, I consider it to be a bug, though honestly there's no spec for how it ought to work. It ought to work that analyzer continues to look up the directory structure until it finds a packages file, but it appears that it doesn't currently do that.

**Comment by fusion44** [comment]
Thanks! You're correct. I removed `lib/analysis_options.yaml` and added all rules to root folders `analysis_options.yaml` and everything works as it should. The main repo for pedantic which I used as a guide does it this way too, see: https://github.com/dart-lang/pedantic

P.s. this made me realize how much more productive I can be with proper tooling, so thanks gain! :)

Should I keep the issue open? I'd consider the problem fixed for my usecases.

**Comment by DanTup** [comment]
@fusion44 based on Brian's comment above, it sounds like this can be considered an analysis server bug, so it should be raised at https://github.com/dart-lang/sdk/issues. If the SDK is updated to handle this, it won't require any changes in the VS Code extension.

Thanks!
