### ISSUE TITLE
Cannot set breakpoint for "Debug in Browser" test

### ISSUE THREAD

**Issue by PavelPZ** [Dart-Code/Dart-Code#2199]
### Files
I have this configuration in launch.json:
```
        {
            "name": "Debug in Browser",
            "request": "launch",
            "type": "dart",
            "template": "debug-test",
            "args": [
                "-p",
                "chrome"
            ]            
        }
```
and this test file:

```
import 'package:test/test.dart';
void main() {
    test('read write', () async {
      expect(1, 1);
    });
}
```

### Actions
- I can see ```Debug in browser``` command in my test file as expected.
- I set a breakpoint at ```expect(1, 1)``` line.
- When I click on the ```Debug in browser``` command I can see following compilation message in command window but **no breakpoint hits**

```
Compiled 9,009,955 characters Dart to 1,035,479 characters JavaScript in 8.44 seconds
...
✓ read write
Exited
```

### Doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.13.6-pre.44, on Microsoft Windows [Version 10.0.18362.535], locale cs-CZ)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    X No Java Development Kit (JDK) found; You must have the environment variable JAVA_HOME set and the java binary      in your PATH. You can download the JDK from https://www.oracle.com/technetwork/java/javase/downloads/.       
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.4.0)
[!] Android Studio (version 3.5)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X Unable to determine bundled Java version.
[√] VS Code (version 1.41.1)
[√] Connected device (3 available)
```

**Comment by DanTup** [comment]
This is a known limitation. `package:test` supports running in the browser, but it doesn't connect a debugger interface, so there's no control of the debugging.

Now that Flutter can run and debug in a browser, I wonder if using `flutter test` might allow this. I'll need to do some testing.

**Comment by PavelPZ** [comment]
@DanTup thanks a lot for info. 

I found only those infos regarding debugging dart for javascript (or Flutter for Web):
- https://dartcode.org/releases/v3-4/ (which I am using in this issue)
- https://dartcode.org/releases/v3-7/ with general link to Flutter site and to #1773
- https://github.com/dart-lang/webdev/issues/352 (no info how to make it work)
- https://github.com/Dart-Code/Dart-Code/issues/1773#issuecomment-560501930: We are waiting for **next release of VS Code extension**?

**Comment by DanTup** [comment]
@PavelPZ the info in those links is currently only for running your Flutter application, not for tests. The `Run in Browser` link you created is using `package:test`'s support for running in the browser and not using Flutter's web support (and as far as I know, `package:test`'s browser support does not set up the web debug proxy mentioned in those links).

It would be nice if this could be made to work, but I don't know how feasible it is. If the project is a Flutter project, then if Flutter supported `flutter test` running in the browser (with the web proxy set up), maybe this could work. I don't know if that's planned though (@jonahwilliams - does this seem likely?).

**Comment by jonahwilliams** [comment]
Unit testing flutter applications within a browser environment, including isn't in any short term plans iirc. It would be interesting if it could be made to work, but in terms of testing most efforts are going towards integrations tests that can in more browsers than chrome

**Comment by DanTup** [comment]
Got it - thanks for the info!

@PavelPZ for now, I would recommend either trying to use the browser debugger, or calling the code from within your app so you can debug it by running the app. If I can think of any way to make this better, I'll post back here (though I don't have any ideas currently).

**Comment by PavelPZ** [comment]
Thanks a lot for clarification. 
I redesign my libraries (solving another problem in https://github.com/flutter/flutter/issues/44583) and this helped me with debugging too.

**Comment by PavelPZ** [comment]
@DanTup, sorry for contact you again, not all is clear. I stilll cannot debug flutter for web app from vs code.

I created new project in **vs code** by ```flutter create web_project```.
Command ```flutter run -d chrome``` works well, but how do I achieve your mentioned **calling the code from within your app so you can debug it by running the app**?

- are we waiting for next release of VS Code extension (mentioned in https://github.com/Dart-Code/Dart-Code/issues/1773#issuecomment-560501930)?
- are some launch.json necessary? This does not work for me.
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch web app",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:8080/index.html",
            "webRoot": "${workspaceFolder}/web",
            "smartStep": true
        }
    ]
}
```

Thanks a lot for help.

**Comment by PavelPZ** [comment]
Problem solved, when I create project from vs code ```ctrl + shift + p => Flutter: Create project```, everything work as expected.
Sorry for trouble you.

**Comment by PavelPZ** [comment]
Or this launch.json configuration makes the trick:
```
        {
            "name": "Launch Flutter web",
            "request": "launch",
            "type": "dart",
            "deviceId": "chrome",
        },
```

**Comment by DanTup** [comment]
Sorry for the delay in responding! The `launch.json` you posted is good, though you don't really need it - if you delete the `launch.json`, when you press `F5` it will launch on whichever device is selected in the status bar:

<img width="322" alt="Screenshot 2020-01-13 at 16 53 06" src="https://user-images.githubusercontent.com/1078012/72275103-3048f900-3625-11ea-898d-09774f44da3b.png">

Clicking the device name there allows you to switch between devices (whereas the `launch.json` you showed will always run on Chrome, regardless of what's selected here).

If you have any issues with this (or questions), do shout!

**Comment by PavelPZ** [comment]
@DanTup, thanks a lot. I missed this vs code feature, everything is now easier.
