### ISSUE TITLE
"Create missing overrides" will only create one overrides when there's "extends" and "with"

### ISSUE THREAD

**Issue by FaridAhamat** [Dart-Code/Dart-Code#2206]
Steps to reproduce:
1. Create a class such as:

`class _MyClassState extends State<MyClass> with AutomaticKeepAliveClientMixin {}`

2. Click Ctrl + . , or hit the lightbulb for quick help.
3. Click "Create 1 missing override(s)".

Actual:
VS Code will generate the override for wantKeepAlive, but totally missing out on build function.

Expected:
VS Code should generate all the necessary overrides, both for State's build and Mixin's function.

**Comment by DanTup** [comment]
Thanks for the report! These fixes are powered by the analysis server that lives in the SDK. I've moved this issue to https://github.com/dart-lang/sdk/issues/40191. Thanks!
