### ISSUE TITLE
hot reload & hot restart did not work for changing app icon

### ISSUE THREAD

**Issue by rtanzifi** [Dart-Code/Dart-Code#2207]
Hello to all.
I just found very nice flutter tutorial. In one of the videos the guy change the icon of the app and hot reload it on emulator and the app icon change. But on real device even hot restart did not have any affect on app icon change. So i have to uninstall the app from device and reinstall it.
Maybe that's a bug.
Just wana know what's wrong.
Thanks.

**Comment by DanTup** [comment]
Can you provide an example of the code you have, and what you're changing? There are some limitations (https://flutter.dev/docs/development/tools/hot-reload#recent-ui-change-is-excluded and https://flutter.dev/docs/development/tools/hot-reload#limitations) on what can be reloaded, but I would expect hot restart to work.

If you can provide a sample, I can try to reproduce here and debug.

**Comment by DanTup** [comment]
If you're still seeing this and are able to provide an example, let me know and I'll re-open this and investigate.
