### ISSUE TITLE
Autocompletion includes dart extensions of unrelated types

### ISSUE THREAD

**Issue by BendixMa** [Dart-Code/Dart-Code#2208]
Hey,

when I declare a dart extension like so:

```dart
extension StringExtensions on String {
  bool get definitelyNotAnInt => false;

  void dontShowThisFunctionOnAnInt() {}
}
```

and use it subsequently in code like so:

```dart
main(List<String> args) {
  int integer = 0;
  integer. // and let vs-code show autocompletions here
}
```

then the suggestion list will include the extensions declared on the `String` class as shown below.

![dart-code-issue](https://user-images.githubusercontent.com/43601200/72103816-4fe0d880-332a-11ea-9318-fb39a58a94f6.png)

Especially when you have multiple extensions declared on multiple types than this will quickly make autocompletion almost useless as there are so many unrelated suggestions and you cannot find the functions/fields in the list that the class actually defines.

Dart-Code version is `3.7.1`.

**Comment by DanTup** [comment]
Thanks for the report! I've moved this over to https://github.com/dart-lang/sdk/issues/40062 since this appears to be an analysis server issue.
