### ISSUE TITLE
Auto completion not working with yield

### ISSUE THREAD

**Issue by Tokenyet** [Dart-Code/Dart-Code#2210]
![demo](https://user-images.githubusercontent.com/6420527/72199593-094dc400-3479-11ea-9849-24754fa7256b.gif)

The class that I wanted to use is in the same file (.dart), but the completion can't find any, even If It's own class methods.

```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale zh-TW)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code, 64-bit edition (version 1.41.1)
[√] Connected device (1 available)

• No issues found!
```

If there is something info not provided, I'll provide It asap.

**Comment by DanTup** [comment]
Thanks! I've moved this to https://github.com/dart-lang/sdk/issues/40099 since it seems like an analysis server issue.
