### ISSUE TITLE
Auto Completion is not working with alias

### ISSUE THREAD

**Issue by Tokenyet** [Dart-Code/Dart-Code#2211]
![ezgif-3-c37857e9f620](https://user-images.githubusercontent.com/6420527/72200095-e8d53800-347f-11ea-8def-632f8412d3bb.gif)

Use alias to prevent nameing conflict, but not working in this specified scenario.

```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale zh-TW)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code, 64-bit edition (version 1.41.1)
[√] Connected device (1 available)

• No issues found!
```

If there is something info not provided, I'll provide It asap.

**Comment by DanTup** [comment]
Thanks for the report! I've moved this to https://github.com/dart-lang/sdk/issues/40098 as this seems like an issue in the analysis server (which powers the code completion).
