### ISSUE TITLE
Converting from generic StatelessWidget to StatefulWidget omits type arguments

### ISSUE THREAD

**Issue by shyndman** [Dart-Code/Dart-Code#2213]
When converting a generic `StatelessWidget` subclass to a `StatefulWidget`, necessary type arguments are omitted from the generated `createState()`.

Example:
```dart
class Foo<T> extends StatelessWidget {
  Widget build(BuildContext) => ...
}

// when run through "Convert to StatefulWidget" becomes

class Foo<T> extends StatefulWidget {
  @override
  _FooState createState() => _FooState(); //! Missing type annotations
}

class _FooState<T> extends State<Foo<T>> {
  @override
  Widget build(BuildContext context) => ...;
}
```

As a result, the runtime type of the `State` subclass is `_FooState<dynamic>`, and its widget, `Foo<dynamic>`. When the state accesses fields whose types involve the type argument `T`, runtime type checks can fail.

**Comment by DanTup** [comment]
Thanks for the report! I've moved this to the SDK repo and CC'd you on the issue (https://github.com/dart-lang/sdk/issues/40095) since the quick-fixes come from the SDK's language server.

**Comment by shyndman** [comment]
Thanks!
