### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by oshanshrestha** [Dart-Code/Dart-Code#2215]
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `3.7.1`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.41.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\oshan\Dart-Code.dart-code-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by oshanshrestha** [comment]
[Dart-Code.dart-code-unresponsive.cpuprofile.txt](https://github.com/Dart-Code/Dart-Code/files/4052418/Dart-Code.dart-code-unresponsive.cpuprofile.txt)

**Comment by DanTup** [comment]
@oshanshrestha how big is the folder you opened in VS Code? It looks like we're spending a lot of time enumerating the folders looking to see if they contain `pubspec.yaml` files. This code is currently mostly synchronous (this was faster than async in my testing, but means we're blocking the thread a bit).

Also - do the projects live on an SSD or mechanical hard drive? (I've only tested on SSD, so the impact of latency on a mechanical drive may have been underestimated).

Thanks!

**Comment by avdept** [comment]
Have the same issue, even in non dart-based projects. Any way to disable scans on per project basis?

**Comment by DanTup** [comment]
@avdept the extension shouldn't activate if you don't have any Dart projects open. Are you sure there aren't any Dart files or pubspecs open anywhere in the tree? Could you post the output of `code --status`?

**Comment by DanTup** [comment]
@avdept also see the comment I just made at https://github.com/Dart-Code/Dart-Code/issues/2219#issuecomment-582844874 which might explain why it's incorrectly activating for large workspaces.

**Comment by oshanshrestha** [comment]
[Consider this comment](https://github.com/Dart-Code/Dart-Code/issues/2215#issuecomment-582845036) by @DanTup
