### ISSUE TITLE
Support coloured gutter icons for Color.fromARGB/RGBO()

### ISSUE THREAD

**Issue by ogierm** [Dart-Code/Dart-Code#2218]
This could be useful since the shorter `Color(int value)` constructor not only takes up less space, but also because the extension generates small color swatches on the left hand side when such a constructor is being used. The conversion is easy to do, but pretty laborious per hand as the opacity needs to be first scaled into a 0-255 range and then converted into hex.

The output would look like this:
before: `Color.fromRGBO(78, 63, 93, .1)`
after: `const Color(0x1A4E3F5D)`

So this would generally help with refactoring and cleaning up by saving time.

**Comment by DanTup** [comment]
The refactors shown in VS Code come from the analysis server, so this would need to be requested there (https://github.com/dart-lang/sdk).

> but also because the extension generates small color swatches on the left hand side 

These are just regexes, so if the pattern is consistent I think we can support this here too:

https://github.com/Dart-Code/Dart-Code/blob/597e4da9f906089dff525f2dbbf0d80fa4742c52/src/shared/vscode/color_range_computer.ts#L6-L7

I'll keep this issue open to see if we can support that in the gutters (for the refactor, please file an SDK issue if you still think it's worthwhile after this change).

**Comment by DanTup** [comment]
More formats of colours should work now:

![Screenshot 2020-03-11 at 10 55 06](https://user-images.githubusercontent.com/1078012/76409840-df385580-6386-11ea-88d9-f6dcfc991a0a.png)
