### ISSUE TITLE
Unable to debug using breakpoints

### ISSUE THREAD

**Issue by ms747** [Dart-Code/Dart-Code#2220]
I have set multiple breakpoints it straight up ignores it and continues to run.

**Comment by ms747** [comment]
Started working after deleting the .vscode folder

**Comment by DanTup** [comment]
I'm not sure why deleting the `.vscode` folder would affect this, but if you see it again, please shout.

A good way to help debug would be to put a `throw` on the line after your breakpoint, and then capture a log (run *Dart: Capture Logs** and tick only the Debugger option) of the breakpoint being missed, but the debugger breaking on the exception. From that, hopefully I can figure out why the breakpoint was missed.
