### ISSUE TITLE
Dart formatter puts curly braces too close to arguments

### ISSUE THREAD

**Issue by awarmfastbear** [Dart-Code/Dart-Code#2227]
Can someone help me understand why the Dart formatter is auto formatting my curly braces next to my arguments in Visual Studio Code? Disabling the prettier format extension doesn't seem to make a difference. I looked through the Dart VS Code settings and I don't see anything relevant to this..

What I am seeing:
```
  Transaction(
      {@required this.id,
      @required this.title,
      @required this.amount,
      @required this.date});
}
```

What I want:
```
  Transaction({
      @required this.id,
      @required this.title,
      @required this.amount,
      @required this.date
      });
}
```

Video example:
https://drive.google.com/open?id=1jypsIZ-_aS1sjkvTxnna3ILp1cP4L9nT

My VS code user settings: https://pastebin.com/raw/bxaVwQd0

**Comment by DanTup** [comment]
Formatting is all handled by [dart_style](https://pub.dev/packages/dart_style), however in this case you just need to add a trailing comma after `this.date` to indicate to the formatter that you want each argument on its own line, then it will format like this:

```dart
class Transaction {
  String id, title, amount, date;
  Transaction({
    @required this.id,
    @required this.title,
    @required this.amount,
    @required this.date,
  });
}
```

Hope this helps!

**Comment by awarmfastbear** [comment]
You're the best, thank you.

**Comment by awarmfastbear** [comment]
@DanTup Out of curiosity, is there a plugin or option that would add this intelligent comma adding for me? :) I've noticed I need to end up using the comma key more than I think is necessary.

**Comment by DanTup** [comment]
@awarmfastbear I'm afraid I don't. Generally I find that I my code is quite mixed (for some short calls/constructors I don't want to take up lots of lines) so I'm not sure automatically inserting them would be ideal either (I think I'd end up use delete a lot!).

There's a bit of discussion about this formatting at https://github.com/dart-lang/dart_style/issues/687 with some suggestions around rules for auto-inserting commas, but nothing that everyone agreed on.
