### ISSUE TITLE
Quick hint creates a new method inside a method even if i comment that method

### ISSUE THREAD

**Issue by Capoutcha** [Dart-Code/Dart-Code#223]
VSCode Version: Code 1.7.2 (7ba55c5, 2016-11-21T22:06:37.428Z)
OS Version: Windows_NT ia32 10.0.14393

Quick hint creates a new method inside a method even if i comment that method looks like he add the new method in that specific ligne

i am using DART as language

![image](https://cloud.githubusercontent.com/assets/9768420/20564147/1e4a2754-b18c-11e6-9e8b-4eda31e61795.png)

it creates a mthod inside another one:

![image](https://cloud.githubusercontent.com/assets/9768420/20564154/282fc6c0-b18c-11e6-8540-4c381c8fc17a.png)

it is like it want to always add the method at that line

**Comment by DanTup** [comment]
I can't seem to repro this. Can you reproduce it in a small sample that you could share?

**Comment by DanTup** [comment]
@Capoutcha Is it possible you can share a code sample that repros this? Can you also confirm the SDK version you're using?

**Comment by DanTup** [comment]
Please shout if you can still repro this and confirm SDK/Dart Code versions.
