### ISSUE TITLE
Can't use Backspace when using Terminal mode for Debugging

### ISSUE THREAD

**Issue by gogoIsComing** [Dart-Code/Dart-Code#2230]
- VSCode Version: 1.41.1
- OS Version: Windows 10 Pro 64-bit (10.0, Build 18362)

Steps to Reproduce:

1. create launch.json
2. write `"console": "terminal"` in your `configurations`
3. write the following code that take an input from user : 
```
import 'dart:io';

main() {
  stdout.writeln('what is Your Name ?');
  String name = stdin.readLineSync();
  print('Welcome $name');
}
```
4. start debugging

then i can input value , but i can't use `backspace` key to undo the text while i write in console.

![Untitled](https://user-images.githubusercontent.com/33967218/72965434-f914dd80-3dc4-11ea-8df6-58883b34f354.png)

**Comment by DanTup** [comment]
@gogoIsComing I was (literally!) just looking at this! I can repro in both Stable and Insiders - what's the reason you closed it?

**Comment by DanTup** [comment]
This happens even using the VS Code "local echo" sample code in the docs, and it's not clear whether it's fixable in the extension. I've opened https://github.com/microsoft/vscode/issues/90618.

Re-opening this issue because it seems a certain bug, and it's not clear if we need to do work here yet.

**Comment by gogoIsComing** [comment]
@DanTup i already opened an issue [ microsoft/vscode#89139](https://github.com/microsoft/vscode/issues/89139#issue-553991652) (before current issue)
and they closed it , cause they thought it is extension issue

**Comment by DanTup** [comment]
@gogoIsComing ah, thanks! It may be an extension issue, but the sample code fails in the same way and I can't see a way in the API for us to handle it. I'll keep this open while waiting for a response though. Thanks!

**Comment by DanTup** [comment]
Ok, looks like this is by-design in VS Code, so we'll need to fix another way. It seems silly to implement it as suggested (we'd end up with a lot of code just to pretend to be a terminal) so I'm going to switch from the pseudoterminal to a real terminal and use https://github.com/dart-lang/sdk/issues/38418 to connect the debugger.
