### ISSUE TITLE
Extension issuedart was not working

### ISSUE THREAD

**Issue by vamsikrishna874** [Dart-Code/Dart-Code#2235]
- Issue Type: `Bug`
- Extension Name: `dart-code`
- Extension Version: `3.7.1`
- OS Version: `Linux x64 5.3.0-26-generic`
- VSCode version: `1.41.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by DanTup** [comment]
It's not clear from the report what's wrong here. I think you may have had something in your clipboard that you were supposed to paste here:

> ⚠️ We have written the needed data into your clipboard. Please paste! ⚠️

Can you give more details about what you're seeing/saw?
