### ISSUE TITLE
Indicator Lines get Tilted when using /**/ type comments when using SynthWave84 Theme and Fira Code Font

### ISSUE THREAD

**Issue by matthiaszarzecki** [Dart-Code/Dart-Code#2239]
I added `/* */` comments to a code-block to temporarily disable an element, and it resulted in the indicator-lines ALSO being tilted, on the Dart-VSCode-Plugin release v3.8, and VSCode 1.41.1.

Screenshot:
![Screenshot 2020-01-30 at 13 32 39](https://user-images.githubusercontent.com/2097526/73450236-49f87900-4365-11ea-94e4-98c4fc4a3ea2.png)

I am using the SynthWave84 theme, with custom css enabled in VSCode (necessary to get the theme running), using Fira Code as Font set to size 15.

And then had a short conversation on twitter with @DanTup about it ;) https://twitter.com/DanTup/status/1222532898294763522

It happened on this code-block:
```
Widget _buildPanel() {
  return ExpansionPanelList(
    expansionCallback: (int index, bool isExpanded) {
      setState(
        () {
          _data[index].isExpanded = !isExpanded;
        },
      );
    },
    children: _data.map<ExpansionPanel>(
      (Item item) {
        return ExpansionPanel(
          headerBuilder: (BuildContext context, bool isExpanded) {
            /*return ListTile(
              title: Text(item.headerValue),
            );*/
            return Card(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: <Widget>[
                  Text("asdsa"),
                ],
              ),
            );
          },
          body: ListTile(
            title: Text(item.expandedValue),
            subtitle: Text('To delete this panel, tap the trash can icon'),
            trailing: Icon(Icons.delete),
            onTap: () {
              setState(
                () {
                  _data.removeWhere((currentItem) => item == currentItem);
                },
              );
            },
          ),
          isExpanded: item.isExpanded,
        );
      },
    ).toList(),
  );
}
```

Would love if you could take a look at this! :)

**Comment by DanTup** [comment]
I'm unable to reproduce this using the SynthWave84 theme:

![Screenshot 2020-08-25 at 14 33 59](https://user-images.githubusercontent.com/1078012/91180843-0fc73e00-e6e0-11ea-90bf-a85aaaa36f6c.png)

So I think this might be being caused by your custom CSS. If you can reproduce it without custom CSS, please let me know which theme and how to repro and I'll take a look. If it only happens with your custom CSS, I think you'd need to fix it there.

**Comment by matthiaszarzecki** [comment]
@DanTup Thanks for looking into this! I did some further experimentation enabling other extensions. Apparently this happens when using both SynthWave '84 as theme AND Fira Code as font. It doesn't matter in that case if custom CSS is enabled.

Synthwave 84, Fira Code, No Custom CSS
<img width="564" alt="Screenshot 2020-09-08 at 15 08 32" src="https://user-images.githubusercontent.com/2097526/92480537-52f7d580-f1e5-11ea-92c3-5b2af606402a.png">

Synthwave 84, Fira Code, With Custom CSS ### This is the only combo that breaks
<img width="579" alt="Screenshot 2020-09-08 at 15 08 56" src="https://user-images.githubusercontent.com/2097526/92480556-57bc8980-f1e5-11ea-80f9-3a9011b6fd71.png">

Synthwave 84, Default Font, With Custom CSS
<img width="370" alt="Screenshot 2020-09-08 at 15 10 36" src="https://user-images.githubusercontent.com/2097526/92480649-7e7ac000-f1e5-11ea-9631-b5bb6ad5a542.png">
<img width="564" alt="Screenshot 2020-09-08 at 15 10 45" src="https://user-images.githubusercontent.com/2097526/92480653-7fabed00-f1e5-11ea-9370-5cb932e71866.png">

Default Theme, Fira Code, No Custom CSS
<img width="540" alt="Screenshot 2020-09-08 at 15 12 16" src="https://user-images.githubusercontent.com/2097526/92480835-bd107a80-f1e5-11ea-8200-0959e29811ee.png">

Seeing as this is a weird conflict between 2 niche (?) settings/extensions I'd be totally fine with not putting energy and seeing this as weird edge-case, but that's up to you :)

Also updating the title of this ticket to better reflect the nature of the bug.

**Comment by DanTup** [comment]
Hmm, I'm still not seeing this using Fira Code and SynthWave '84 theme (also on macOS) :(

<img width="792" alt="Screenshot 2020-09-09 at 11 59 15" src="https://user-images.githubusercontent.com/1078012/92590324-f1db0b00-f293-11ea-991b-0f1d2cb4e232.png">

I've included a => in the screenshot so you can see it's using Fira Code+ligatures, and you can tell them theme from the colours.

Does it happen all the time? Can you provide a full file (copy/pasted, so I can copy it) that shows the issue (and ensure if you close/re-open the file it remains like that). Thanks!

**Comment by DanTup** [comment]
<img width="1205" alt="Screenshot 2020-09-29 at 10 02 59" src="https://user-images.githubusercontent.com/1078012/94537650-00856400-023b-11eb-894c-1bd2786a972a.png">

Still not seeing it 🤷‍♂️

Do you have all of the parts of the Fira Code font installed and are you on the latest version?

<img width="351" alt="Screenshot 2020-09-29 at 10 05 38" src="https://user-images.githubusercontent.com/1078012/94538019-6245ce00-023b-11eb-9f0a-eff1942595c4.png">

<img width="665" alt="Screenshot 2020-09-29 at 10 06 36" src="https://user-images.githubusercontent.com/1078012/94538112-81446000-023b-11eb-9361-a9cdfa08e890.png">

**Comment by matthiaszarzecki** [comment]
Yup, Fira Code is the newest. Old ones uninstalled, fresh download, used the ttf's, looks the same as on your side.
<img width="240" alt="Screenshot 2020-10-06 at 23 38 37" src="https://user-images.githubusercontent.com/2097526/95262862-3626e000-082d-11eb-9384-d3d71c7c3412.png">
<img width="304" alt="Screenshot 2020-10-06 at 23 39 04" src="https://user-images.githubusercontent.com/2097526/95262868-37580d00-082d-11eb-9517-21d863d5fcbc.png">

Do you have any other ideas? :D

**Comment by DanTup** [comment]
> Do you have any other ideas? :D

Hmmm, no :-)

Do you have access to any other machine to test there to maybe help identify if it's just you, or just me?

If not, could you try with VS Code Insiders to see which behaviour that has? Or launching VS Code with a temporary `--user-data-dir` (to clear all settings/extensions) and see if you can repro there to eliminate any other settings/extensions interfering?

**Comment by matthiaszarzecki** [comment]
Good ideas!

The previous reports were run on my Work-mac (16 inch 2019), now I tried it on my private one (13 inch 2019).

Then I started code with the --user-data-dir command, removed all plugins (except synthwave and dart) and set the settings to the minimally necessary settings again

```
{
    "dart.previewFlutterUiGuides": true,
    "workbench.colorTheme": "SynthWave '84",
    "editor.fontLigatures": true,
    "editor.fontFamily": "'Fira Code'",
}
```

<img width="359" alt="Screenshot 2020-10-11 at 23 42 56" src="https://user-images.githubusercontent.com/2097526/95690929-83cf8e00-0c1b-11eb-86f3-a179835333fd.png">

Still get tilted lines :(

**Comment by DanTup** [comment]
Very strange. I still can't reproduce - however @BootBlock is able to (on Windows!). He's going to take a look if he can fix. Thanks!

**Comment by matthiaszarzecki** [comment]
Sweet, glad to hear I am not the only one! :D
