### ISSUE TITLE
add additional info about the analysis server to bug reports

### ISSUE THREAD

**Issue by devoncarew** [Dart-Code/Dart-Code#224]
We can add a bit more info to bug reports - the analysis server has a diagnostic call:

https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html#domain_diagnostic

That can return info like the number of analysis context, the size of each context, and some other metadata.

**Comment by DanTup** [comment]
I saw that a few days ago (possibly following one of your commits on sdk!) and made a note to have a look at the data that came back (hasn't happened yet though!).

I presume it'll only work after non-fatal errors though; but would've been useful on fatal ones! ;(

If it's cheap to call, we could possibly call it periodically so if a fatal error does occur, we could at least have some "fairly recent" stats?

**Comment by devoncarew** [comment]
Even on fatal errors the analysis server is often still around to query (we should be defensive about the call not returning however).

**Comment by devoncarew** [comment]
We should probably update the spec docs re the behavior on fatal errors.
