### ISSUE TITLE
The Dart analyzer terminates automatically.

### ISSUE THREAD

**Issue by saurabhguptarock** [Dart-Code/Dart-Code#2244]

**Comment by DanTup** [comment]
Can you provide more info?  Does the error message have .a **Show Log** button you can get the log for?

Are you using Flutter? If so, which version? There was a recent issue that may be fixed on master (https://github.com/flutter/flutter/issues/46616).

Thanks!

**Comment by Akash4097** [comment]
i faced this same issue when using latest hotfix (flutter 1.12.13+hotfix.7) but not with flutter latest master branch, i think the problem still persist in stable release...

**Comment by anwarsayyad** [comment]
Why dart and flutter extension not available in vs studio

**Comment by DanTup** [comment]
@anwarsayyad I presume by "VS Studio" you mean standard "Visual Studio"? This project is for VS Code - it has very different APIs to Visual Studio and cannot share the same extensions. To use Flutter in Visual Studio someone would need to build a new extension for it but it's not something I/this project current intend to cover.

**Comment by DanTup** [comment]
Without more info, I'm assuming this is the Flutter issue linked above which has been mostly resolved in Flutter, with the remaining known crash raised at https://github.com/dart-lang/sdk/issues/40348.

**Comment by yinxulai** [comment]
mybe: https://github.com/Dart-Code/Dart-Code/issues/2704#issuecomment-683528952
