### ISSUE TITLE
Remove VS Code dependency from debug adapter

### ISSUE THREAD

**Issue by LinArcX** [Dart-Code/Dart-Code#2246]
Hi. I'm a neovim user and currently we have an awesome project that brings DAP in vim/neovim universe called: [vimspector](https://github.com/puremourning/vimspector).

Anyway, tonight i tried to check it out if it possible to debug dart applications with vimspector or not. But me and ben found out that it's impossible due to hard dependency of Dart-Code to vscode:
https://github.com/puremourning/vimspector/issues/4#issuecomment-581180467

**Comment by DanTup** [comment]
Thanks - this is definitely a bug! The debug adapters were brought in-process a while back to work around some limitations in VS Code (and ended up with many accidental dependencies on extension code). The plan is to move them back out-of-process (https://github.com/Dart-Code/Dart-Code/issues/1876) and those dependencies will need to be removed (there should be lints to enforce this but I think they're on an unmerged branch).

That said, FWIW the debug adapters that live here are written specifically for use in the VS Code extension and make use of custom messages not defined in the DAP protocol so I don't know how compatible they'll be with another DAP client out of the box. If there are minor changes we can make (or accept PRs for) to improve this without interfering with the VS Code functionality, I think that would be reasonable (@jonas-jonas might also be interested in that).

Long-term, it'd be nice to have a standalone DAP (probably written in Dart so it can use the vm service libraries). There's an issue related to this (that you opened 😄) at https://github.com/dart-lang/sdk/issues/35717, though I think initially it could be built as a standaone Dart package.

**Comment by DanTup** [comment]
I had a quick look and removed a few dependencies but there are two remaining:

- `getLogHeader`
- `safeSpawn`

These are both currently used directly from the extension as they use some shared global state (`safeSpawn` reads an environment object to allow overriding env vars, and `getLogHeader` is a string built to prefix into any log files that has some useful info). All this data should be serialisable so I think should be possible to also move into the `args` (so the functions can be moved into shared files) but they're less straight-forward than the others.

**Comment by DanTup** [comment]
I believe I've removed the last of these dependencies. Please let me know if you still hit this issue and feel free to open new issues if you hit other problems. Running this debug adapter outside VS Code is not strictly supported, but if there are minor issues preventing it I'm happy to take a look. Thanks!

**Comment by DanTup** [comment]
Scratch that - I still see some issues... Working on them though!
