### ISSUE TITLE
Handle unsupported VM commands gracefully

### ISSUE THREAD

**Issue by annagrin** [Dart-Code/Dart-Code#2247]
Currently, when running with VM that does not support some operations (such as logging, setting library debuggable, settng flags, etc),  Dart-code lets unsupported exceptions fail the containing operation. Would it be possible to fail gracefully and continue performing the current workflow, given that failing calls to those API are not breaking any functionality?

See:

Why is this change necessary?

_Originally posted by @grouma in 
https://github.com/dart-lang/webdev/pull/879#discussion_r374351584

**Comment by DanTup** [comment]
Can you provide more specifics about the problem? The link you included doesn't seem to work for me. As far as I can tell, the things you mention are already handled with `catch`:

Logging:

https://github.com/Dart-Code/Dart-Code/blob/2b27c32632c256861918133826261eee7d942a39/src/debug/dart_debug_impl.ts#L448-L452

setLibraryDebuggable:

https://github.com/Dart-Code/Dart-Code/blob/caa7fb31b5d467f7e2e870aa758e4db4d475fe81/src/debug/threads.ts#L111-L128

**Comment by DanTup** [comment]
Oh, I found the comment at https://github.com/dart-lang/webdev/pull/879#discussion_r374351584.

> causes failures in flutter vscode extension that makes it impossible to debug the rest

The `catch` above should handle this - can you describe the issue you're seeing when this fails? It will show up in the logs, but should only be once and that's expected (it's useful info when debugging and someone sends a log if some things didn't work).

There is an open issue for supporting Logging in dwds at https://github.com/dart-lang/webdev/issues/498, though I'm not sure how involved it is.

**Comment by annagrin** [comment]
I am not sure I am correct here - I am was working on the eval prototype for flutter debugger, and I couldn't make setting breakpoints work, so I kept removing all throwing statements until I got `addBreakpointWithScriptUri` to execute. 
I saw a few exceptions, on "Logging" and "_Logging" events, and on `setFlag` and `setLibraryDebuggable` calls. I am not sure which one prevented the `addBreakpointWithScriptUri` call. 

Now I am working on the first non-prototype implementation, I still need to check in a few preliminary changes to SDK, flutter engine and webdev before I can try connecting it all again with flutter and VSCode, so I might take me some time to create a repro.

If you would like I can close this issue for now until I have a confirmation (or the opposite).

**Comment by DanTup** [comment]
We can leave this open for now so it doesn't get forgotten. I can't see an obvious reason `addBreakpointWithScriptUri` would be skipped (though I did recently fix an issue that could prevent breakpoints from working if imports had `../` - https://github.com/dart-lang/webdev/pull/877).

Let me know if you manage to get a repro (or if you hit any other issues), thanks!

**Comment by DanTup** [comment]
@github-actions so much for waiting for 10 days! 😄

@annagrin that said, I'm not sure there was anything to do here - but let me know if you want me to take another look at anything here.

**Comment by annagrin** [comment]
I think we are good now - I haven't seen anything lately. Either I was wrong from the beginning or it is fixed now:)
