### ISSUE TITLE
Dart extensions are available for wrong data type in Visual Studio Code

### ISSUE THREAD

**Issue by bambinoua** [Dart-Code/Dart-Code#2251]
There are two extensions for different types `String` and `DateTime`. Why extensions for `String` and `DateTime` (as mentioned above) are visible in suggestions for `int` (and any other) type?

```dart
extension StringHelper on String {
  String dummyString => this;
}

extension DateTimeHelper on DateTime {
  String dummyDate => this;
}

void test() {
  int thisIsInt = 0;
  thisIsInt.dummyDate() // !!! must not be available for `int`
}

```

Link on stackoverflow.com with image
https://stackoverflow.com/q/60060242/1798328

**Comment by DanTup** [comment]
Thanks for the report! This is a bug in the SDK and has been fixed in https://github.com/dart-lang/sdk/issues/40062. The fix probably hasn't made stable builds of Dart/Flutter yet, but should be in dev/master builds if you want to try it out.

**Comment by bambinoua** [comment]
Thanks for a quick answer.

>  but should be in dev/master builds if you want to try it out.

Do you mean to switch `flutter channel`?

**Comment by DanTup** [comment]
Yep, if you want the fix now you could switch to a newer channel (of course, there may be more bugs in non-stable channels).

Otherwise, you'd have to wait for the fix to make it to the stable channel.
