### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by YoSalcido** [Dart-Code/Dart-Code#2255]
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `3.8.1`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.42.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\ld_gr\Dart-Code.dart-code-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by YoSalcido** [comment]
`{
    "nodes": [
        {
            "id": 1,
            "callFrame": {
                "functionName": "(root)",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 0,
            "children": [
                2
            ]
        },
        {
            "id": 2,
            "callFrame": {
                "functionName": "o",
                "scriptId": "262",
                "url": "file:///c:/Users/ld_gr/.vscode/extensions/dart-code.dart-code-3.8.1/out/dist/extension.js",
                "lineNumber": 0,
                "columnNumber": 1166
            },
            "hitCount": 0,
            "children": [
                3
            ]
        },
        {
            "id": 3,
            "callFrame": {
                "functionName": "",
                "scriptId": "262",
                "url": "file:///c:/Users/ld_gr/.vscode/extensions/dart-code.dart-code-3.8.1/out/dist/extension.js",
                "lineNumber": 0,
                "columnNumber": 2621
            },
            "hitCount": 0,
            "children": [
                4
            ]
        },
        {
            "id": 4,
            "callFrame": {
                "functionName": "",
                "scriptId": "262",
                "url": "file:///c:/Users/ld_gr/.vscode/extensions/dart-code.dart-code-3.8.1/out/dist/extension.js",
                "lineNumber": 0,
                "columnNumber": 2717
            },
            "hitCount": 1,
            "children": [
                5,
                11,
                16
            ],
            "positionTicks": [
                {
                    "line": 1,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 5,
            "callFrame": {
                "functionName": "h",
                "scriptId": "262",
                "url": "file:///c:/Users/ld_gr/.vscode/extensions/dart-code.dart-code-3.8.1/out/dist/extension.js",
                "lineNumber": 0,
                "columnNumber": 2011
            },
            "hitCount": 0,
            "children": [
                6,
                7
            ]
        },
        {
            "id": 6,
            "callFrame": {
                "functionName": "join",
                "scriptId": "38",
                "url": "path.js",
                "lineNumber": 363,
                "columnNumber": 6
            },
            "hitCount": 4,
            "positionTicks": [
                {
                    "line": 364,
                    "ticks": 2
                },
                {
                    "line": 426,
                    "ticks": 1
                },
                {
                    "line": 373,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 7,
            "callFrame": {
                "functionName": "fs.existsSync",
                "scriptId": "82",
                "url": "electron/js2c/asar.js",
                "lineNumber": 430,
                "columnNumber": 20
            },
            "hitCount": 1,
            "children": [
                8,
                24
            ],
            "positionTicks": [
                {
                    "line": 433,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 8,
            "callFrame": {
                "functionName": "fs.existsSync",
                "scriptId": "82",
                "url": "electron/js2c/asar.js",
                "lineNumber": 430,
                "columnNumber": 20
            },
            "hitCount": 0,
            "children": [
                9,
                30
            ]
        },
        {
            "id": 9,
            "callFrame": {
                "functionName": "existsSync",
                "scriptId": "76",
                "url": "fs.js",
                "lineNumber": 230,
                "columnNumber": 19
            },
            "hitCount": 0,
            "children": [
                10,
                21
            ]
        },
        {
            "id": 10,
            "callFrame": {
                "functionName": "access",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 27,
            "positionTicks": [
                {
                    "line": 238,
                    "ticks": 27
                }
            ]
        },
        {
            "id": 21,
            "callFrame": {
                "functionName": "hidden",
                "scriptId": "16",
                "url": "internal/errors.js",
                "lineNumber": 232,
                "columnNumber": 24
            },
            "hitCount": 1,
            "children": [
                22
            ],
            "positionTicks": [
                {
                    "line": 241,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 22,
            "callFrame": {
                "functionName": "",
                "scriptId": "77",
                "url": "internal/fs/utils.js",
                "lineNumber": 435,
                "columnNumber": 41
            },
            "hitCount": 1,
            "children": [
                23,
                47
            ],
            "positionTicks": [
                {
                    "line": 438,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 23,
            "callFrame": {
                "functionName": "toPathIfFileURL",
                "scriptId": "35",
                "url": "internal/url.js",
                "lineNumber": 1384,
                "columnNumber": 24
            },
            "hitCount": 3,
            "positionTicks": [
                {
                    "line": 1385,
                    "ticks": 1
                },
                {
                    "line": 1386,
                    "ticks": 2
                }
            ]
        },
        {
            "id": 47,
            "callFrame": {
                "functionName": "hidden",
                "scriptId": "16",
                "url": "internal/errors.js",
                "lineNumber": 232,
                "columnNumber": 24
            },
            "hitCount": 0,
            "children": [
                48
            ]
        },
        {
            "id": 48,
            "callFrame": {
                "functionName": "",
                "scriptId": "77",
                "url": "internal/fs/utils.js",
                "lineNumber": 423,
                "columnNumber": 37
            },
            "hitCount": 0,
            "children": [
                49
            ]
        },
        {
            "id": 49,
            "callFrame": {
                "functionName": "hidden",
                "scriptId": "16",
                "url": "internal/errors.js",
                "lineNumber": 232,
                "columnNumber": 24
            },
            "hitCount": 0,
            "children": [
                50
            ]
        },
        {
            "id": 50,
            "callFrame": {
                "functionName": "",
                "scriptId": "77",
                "url": "internal/fs/utils.js",
                "lineNumber": 195,
                "columnNumber": 34
            },
            "hitCount": 0,
            "children": [
                51
            ]
        },
        {
            "id": 51,
            "callFrame": {
                "functionName": "isUint8Array",
                "scriptId": "20",
                "url": "internal/util/types.js",
                "lineNumber": 18,
                "columnNumber": 21
            },
            "hitCount": 1,
            "children": [
                52
            ],
            "positionTicks": [
                {
                    "line": 20,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 52,
            "callFrame": {
                "functionName": "",
                "scriptId": "11",
                "url": "internal/per_context/primordials.js",
                "lineNumber": 22,
                "columnNumber": 9
            },
            "hitCount": 1,
            "positionTicks": [
                {
                    "line": 23,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 30,
            "callFrame": {
                "functionName": "splitPath",
                "scriptId": "82",
                "url": "electron/js2c/asar.js",
                "lineNumber": 43,
                "columnNumber": 20
            },
            "hitCount": 3,
            "positionTicks": [
                {
                    "line": 55,
                    "ticks": 3
                }
            ]
        },
        {
            "id": 24,
            "callFrame": {
                "functionName": "splitPath",
                "scriptId": "82",
                "url": "electron/js2c/asar.js",
                "lineNumber": 43,
                "columnNumber": 20
            },
            "hitCount": 3,
            "children": [
                25,
                33
            ],
            "positionTicks": [
                {
                    "line": 55,
                    "ticks": 3
                }
            ]
        },
        {
            "id": 25,
            "callFrame": {
                "functionName": "",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 3,
            "positionTicks": [
                {
                    "line": 55,
                    "ticks": 3
                }
            ]
        },
        {
            "id": 33,
            "callFrame": {
                "functionName": "normalize",
                "scriptId": "38",
                "url": "path.js",
                "lineNumber": 261,
                "columnNumber": 11
            },
            "hitCount": 1,
            "positionTicks": [
                {
                    "line": 270,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 11,
            "callFrame": {
                "functionName": "d",
                "scriptId": "262",
                "url": "file:///c:/Users/ld_gr/.vscode/extensions/dart-code.dart-code-3.8.1/out/dist/extension.js",
                "lineNumber": 0,
                "columnNumber": 1951
            },
            "hitCount": 0,
            "children": [
                12,
                43
            ]
        },
        {
            "id": 12,
            "callFrame": {
                "functionName": "fs.existsSync",
                "scriptId": "82",
                "url": "electron/js2c/asar.js",
                "lineNumber": 430,
                "columnNumber": 20
            },
            "hitCount": 0,
            "children": [
                13,
                28
            ]
        },
        {
            "id": 13,
            "callFrame": {
                "functionName": "fs.existsSync",
                "scriptId": "82",
                "url": "electron/js2c/asar.js",
                "lineNumber": 430,
                "columnNumber": 20
            },
            "hitCount": 1,
            "children": [
                14,
                57
            ],
            "positionTicks": [
                {
                    "line": 433,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 14,
            "callFrame": {
                "functionName": "existsSync",
                "scriptId": "76",
                "url": "fs.js",
                "lineNumber": 230,
                "columnNumber": 19
            },
            "hitCount": 1,
            "children": [
                15,
                44
            ],
            "positionTicks": [
                {
                    "line": 238,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 15,
            "callFrame": {
                "functionName": "access",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 192,
            "positionTicks": [
                {
                    "line": 238,
                    "ticks": 192
                }
            ]
        },
        {
            "id": 44,
            "callFrame": {
                "functionName": "hidden",
                "scriptId": "16",
                "url": "internal/errors.js",
                "lineNumber": 232,
                "columnNumber": 24
            },
            "hitCount": 0,
            "children": [
                45
            ]
        },
        {
            "id": 45,
            "callFrame": {
                "functionName": "",
                "scriptId": "77",
                "url": "internal/fs/utils.js",
                "lineNumber": 435,
                "columnNumber": 41
            },
            "hitCount": 0,
            "children": [
                46
            ]
        },
        {
            "id": 46,
            "callFrame": {
                "functionName": "toPathIfFileURL",
                "scriptId": "35",
                "url": "internal/url.js",
                "lineNumber": 1384,
                "columnNumber": 24
            },
            "hitCount": 2,
            "positionTicks": [
                {
                    "line": 1386,
                    "ticks": 2
                }
            ]
        },
        {
            "id": 57,
            "callFrame": {
                "functionName": "splitPath",
                "scriptId": "82",
                "url": "electron/js2c/asar.js",
                "lineNumber": 43,
                "columnNumber": 20
            },
            "hitCount": 2,
            "positionTicks": [
                {
                    "line": 55,
                    "ticks": 2
                }
            ]
        },
        {
            "id": 28,
            "callFrame": {
                "functionName": "splitPath",
                "scriptId": "82",
                "url": "electron/js2c/asar.js",
                "lineNumber": 43,
                "columnNumber": 20
            },
            "hitCount": 1,
            "children": [
                29
            ],
            "positionTicks": [
                {
                    "line": 55,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 29,
            "callFrame": {
                "functionName": "",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 2,
            "positionTicks": [
                {
                    "line": 55,
                    "ticks": 2
                }
            ]
        },
        {
            "id": 43,
            "callFrame": {
                "functionName": "join",
                "scriptId": "38",
                "url": "path.js",
                "lineNumber": 363,
                "columnNumber": 6
            },
            "hitCount": 2,
            "children": [
                58
            ],
            "positionTicks": [
                {
                    "line": 370,
                    "ticks": 1
                },
                {
                    "line": 426,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 58,
            "callFrame": {
                "functionName": "normalize",
                "scriptId": "38",
                "url": "path.js",
                "lineNumber": 261,
                "columnNumber": 11
            },
            "hitCount": 1,
            "positionTicks": [
                {
                    "line": 39,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 16,
            "callFrame": {
                "functionName": "p",
                "scriptId": "262",
                "url": "file:///c:/Users/ld_gr/.vscode/extensions/dart-code.dart-code-3.8.1/out/dist/extension.js",
                "lineNumber": 0,
                "columnNumber": 2094
            },
            "hitCount": 0,
            "children": [
                17,
                53
            ]
        },
        {
            "id": 17,
            "callFrame": {
                "functionName": "fs.existsSync",
                "scriptId": "82",
                "url": "electron/js2c/asar.js",
                "lineNumber": 430,
                "columnNumber": 20
            },
            "hitCount": 0,
            "children": [
                18,
                26
            ]
        },
        {
            "id": 18,
            "callFrame": {
                "functionName": "fs.existsSync",
                "scriptId": "82",
                "url": "electron/js2c/asar.js",
                "lineNumber": 430,
                "columnNumber": 20
            },
            "hitCount": 0,
            "children": [
                19,
                31
            ]
        },
        {
            "id": 19,
            "callFrame": {
                "functionName": "existsSync",
                "scriptId": "76",
                "url": "fs.js",
                "lineNumber": 230,
                "columnNumber": 19
            },
            "hitCount": 1,
            "children": [
                20,
                34,
                42
            ],
            "positionTicks": [
                {
                    "line": 237,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 20,
            "callFrame": {
                "functionName": "access",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 32,
            "positionTicks": [
                {
                    "line": 238,
                    "ticks": 32
                }
            ]
        },
        {
            "id": 34,
            "callFrame": {
                "functionName": "hidden",
                "scriptId": "16",
                "url": "internal/errors.js",
                "lineNumber": 232,
                "columnNumber": 24
            },
            "hitCount": 0,
            "children": [
                35
            ]
        },
        {
            "id": 35,
            "callFrame": {
                "functionName": "",
                "scriptId": "77",
                "url": "internal/fs/utils.js",
                "lineNumber": 435,
                "columnNumber": 41
            },
            "hitCount": 0,
            "children": [
                36
            ]
        },
        {
            "id": 36,
            "callFrame": {
                "functionName": "hidden",
                "scriptId": "16",
                "url": "internal/errors.js",
                "lineNumber": 232,
                "columnNumber": 24
            },
            "hitCount": 0,
            "children": [
                37
            ]
        },
        {
            "id": 37,
            "callFrame": {
                "functionName": "",
                "scriptId": "77",
                "url": "internal/fs/utils.js",
                "lineNumber": 423,
                "columnNumber": 37
            },
            "hitCount": 0,
            "children": [
                38
            ]
        },
        {
            "id": 38,
            "callFrame": {
                "functionName": "hidden",
                "scriptId": "16",
                "url": "internal/errors.js",
                "lineNumber": 232,
                "columnNumber": 24
            },
            "hitCount": 0,
            "children": [
                39
            ]
        },
        {
            "id": 39,
            "callFrame": {
                "functionName": "",
                "scriptId": "77",
                "url": "internal/fs/utils.js",
                "lineNumber": 195,
                "columnNumber": 34
            },
            "hitCount": 0,
            "children": [
                40
            ]
        },
        {
            "id": 40,
            "callFrame": {
                "functionName": "isUint8Array",
                "scriptId": "20",
                "url": "internal/util/types.js",
                "lineNumber": 18,
                "columnNumber": 21
            },
            "hitCount": 0,
            "children": [
                41
            ]
        },
        {
            "id": 41,
            "callFrame": {
                "functionName": "",
                "scriptId": "11",
                "url": "internal/per_context/primordials.js",
                "lineNumber": 22,
                "columnNumber": 9
            },
            "hitCount": 1,
            "positionTicks": [
                {
                    "line": 23,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 42,
            "callFrame": {
                "functionName": "toNamespacedPath",
                "scriptId": "38",
                "url": "path.js",
                "lineNumber": 545,
                "columnNumber": 18
            },
            "hitCount": 2,
            "positionTicks": [
                {
                    "line": 546,
                    "ticks": 1
                },
                {
                    "line": 555,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 31,
            "callFrame": {
                "functionName": "splitPath",
                "scriptId": "82",
                "url": "electron/js2c/asar.js",
                "lineNumber": 43,
                "columnNumber": 20
            },
            "hitCount": 1,
            "children": [
                32,
                54
            ],
            "positionTicks": [
                {
                    "line": 55,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 32,
            "callFrame": {
                "functionName": "",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 2,
            "positionTicks": [
                {
                    "line": 55,
                    "ticks": 2
                }
            ]
        },
        {
            "id": 54,
            "callFrame": {
                "functionName": "normalize",
                "scriptId": "38",
                "url": "path.js",
                "lineNumber": 261,
                "columnNumber": 11
            },
            "hitCount": 1,
            "positionTicks": [
                {
                    "line": 60,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 26,
            "callFrame": {
                "functionName": "splitPath",
                "scriptId": "82",
                "url": "electron/js2c/asar.js",
                "lineNumber": 43,
                "columnNumber": 20
            },
            "hitCount": 0,
            "children": [
                27
            ]
        },
        {
            "id": 27,
            "callFrame": {
                "functionName": "",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 4,
            "positionTicks": [
                {
                    "line": 55,
                    "ticks": 4
                }
            ]
        },
        {
            "id": 53,
            "callFrame": {
                "functionName": "join",
                "scriptId": "38",
                "url": "path.js",
                "lineNumber": 363,
                "columnNumber": 6
            },
            "hitCount": 1,
            "children": [
                55
            ],
            "positionTicks": [
                {
                    "line": 417,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 55,
            "callFrame": {
                "functionName": "normalize",
                "scriptId": "38",
                "url": "path.js",
                "lineNumber": 261,
                "columnNumber": 11
            },
            "hitCount": 0,
            "children": [
                56
            ]
        },
        {
            "id": 56,
            "callFrame": {
                "functionName": "normalizeString",
                "scriptId": "38",
                "url": "path.js",
                "lineNumber": 51,
                "columnNumber": 24
            },
            "hitCount": 1,
            "positionTicks": [
                {
                    "line": 98,
                    "ticks": 1
                }
            ]
        }
    ],
    "startTime": 1340112000,
    "endTime": 1345450000,
    "samples": [
        5,
        6,
        10,
        15,
        15,
        10,
        20,
        15,
        15,
        15,
        10,
        20,
        20,
        15,
        15,
        23,
        15,
        15,
        10,
        15,
        15,
        15,
        20,
        15,
        13,
        15,
        15,
        10,
        15,
        20,
        15,
        15,
        25,
        15,
        15,
        15,
        15,
        15,
        15,
        10,
        27,
        29,
        15,
        15,
        15,
        15,
        15,
        15,
        15,
        15,
        10,
        20,
        15,
        15,
        15,
        15,
        27,
        15,
        15,
        20,
        15,
        15,
        30,
        20,
        32,
        15,
        15,
        15,
        15,
        15,
        15,
        15,
        10,
        20,
        15,
        15,
        33,
        10,
        15,
        15,
        15,
        20,
        15,
        15,
        15,
        15,
        15,
        30,
        41,
        15,
        20,
        15,
        15,
        10,
        42,
        15,
        30,
        4,
        15,
        10,
        15,
        15,
        15,
        15,
        27,
        15,
        15,
        10,
        43,
        15,
        20,
        20,
        20,
        20,
        15,
        15,
        15,
        15,
        15,
        15,
        15,
        15,
        15,
        15,
        15,
        15,
        20,
        15,
        20,
        15,
        15,
        10,
        15,
        10,
        15,
        24,
        15,
        46,
        15,
        15,
        52,
        43,
        15,
        15,
        15,
        10,
        15,
        15,
        53,
        28,
        15,
        15,
        10,
        15,
        31,
        15,
        24,
        29,
        15,
        10,
        15,
        15,
        20,
        15,
        15,
        20,
        15,
        15,
        23,
        20,
        15,
        21,
        15,
        15,
        6,
        20,
        15,
        15,
        23,
        15,
        15,
        15,
        27,
        15,
        15,
        10,
        15,
        15,
        15,
        15,
        14,
        54,
        15,
        20,
        15,
        15,
        56,
        15,
        15,
        32,
        15,
        15,
        10,
        15,
        57,
        15,
        15,
        15,
        57,
        15,
        15,
        20,
        15,
        15,
        15,
        10,
        20,
        15,
        15,
        10,
        15,
        15,
        7,
        42,
        15,
        15,
        10,
        15,
        15,
        22,
        15,
        20,
        15,
        15,
        15,
        15,
        15,
        6,
        15,
        15,
        10,
        15,
        15,
        51,
        15,
        15,
        15,
        20,
        15,
        15,
        20,
        15,
        15,
        20,
        15,
        15,
        24,
        10,
        15,
        15,
        20,
        15,
        15,
        10,
        20,
        15,
        15,
        25,
        25,
        20,
        15,
        15,
        15,
        15,
        58,
        15,
        15,
        15,
        15,
        10,
        46,
        15,
        15,
        15,
        15,
        15,
        15,
        19,
        15,
        15,
        20,
        15,
        15,
        15,
        15,
        15,
        15,
        10,
        15,
        15,
        6
    ],
    "timeDeltas": [
        321000,
        1000,
        1000,
        1000,
        28000,
        1000,
        1000,
        31000,
        25000,
        1000,
        1000,
        1000,
        1000,
        6000,
        31000,
        1000,
        26000,
        19000,
        1000,
        1000,
        46000,
        33000,
        1000,
        31000,
        1000,
        5000,
        18000,
        1000,
        25000,
        1000,
        56000,
        23000,
        1000,
        21000,
        20000,
        1000,
        28000,
        17000,
        1000,
        1000,
        1000,
        1000,
        1000,
        15000,
        1000,
        17000,
        30000,
        1000,
        29000,
        86000,
        1000,
        1000,
        1000,
        32000,
        1000,
        22000,
        1000,
        41000,
        24000,
        1000,
        43000,
        67000,
        1000,
        1000,
        1000,
        10000,
        21000,
        1000,
        1000,
        48000,
        1000,
        27000,
        2000,
        1000,
        58000,
        25000,
        1000,
        1000,
        1000,
        12000,
        21000,
        1000,
        38000,
        1000,
        36000,
        77000,
        39000,
        1000,
        1000,
        84000,
        2000,
        35000,
        35000,
        1000,
        1000,
        27000,
        2000,
        1000,
        29000,
        1000,
        31000,
        1000,
        54000,
        46000,
        1000,
        12000,
        35000,
        1000,
        1000,
        39000,
        1000,
        32000,
        59000,
        1000,
        131000,
        40000,
        1000,
        1000,
        1000,
        1000,
        16000,
        40000,
        1000,
        15000,
        1000,
        25000,
        1000,
        35000,
        1000,
        1000,
        29000,
        1000,
        19000,
        1000,
        21000,
        1000,
        157000,
        1000,
        10000,
        19000,
        1000,
        1000,
        6000,
        1000,
        31000,
        1000,
        1000,
        40000,
        1000,
        1000,
        43000,
        33000,
        1000,
        50000,
        2000,
        31000,
        1000,
        1000,
        42000,
        1000,
        34000,
        24000,
        1000,
        13000,
        47000,
        1000,
        13000,
        17000,
        1000,
        1000,
        37000,
        1000,
        1000,
        25000,
        1000,
        1000,
        12000,
        30000,
        1000,
        1000,
        1000,
        54000,
        1000,
        26000,
        28000,
        1000,
        10000,
        48000,
        1000,
        1000,
        1000,
        1000,
        46000,
        1000,
        50000,
        28000,
        1000,
        16000,
        11000,
        1000,
        12000,
        26000,
        1000,
        44000,
        1000,
        31000,
        26000,
        1000,
        1000,
        10000,
        97000,
        1000,
        33000,
        26000,
        1000,
        1000,
        1000,
        4000,
        29000,
        1000,
        33000,
        21000,
        1000,
        1000,
        1000,
        34000,
        1000,
        1000,
        45000,
        1000,
        25000,
        1000,
        18000,
        22000,
        1000,
        14000,
        17000,
        1000,
        45000,
        34000,
        1000,
        43000,
        19000,
        1000,
        1000,
        32000,
        18000,
        1000,
        48000,
        41000,
        1000,
        47000,
        21000,
        1000,
        11000,
        36000,
        1000,
        1000,
        1000,
        22000,
        1000,
        78000,
        34000,
        1000,
        1000,
        53000,
        64000,
        1000,
        1000,
        1000,
        5000,
        38000,
        54000,
        1000,
        1000,
        4000,
        27000,
        16000,
        26000,
        1000,
        1000,
        13000,
        17000,
        1000,
        1000,
        31000,
        26000,
        1000,
        1000,
        48000,
        1000,
        6000,
        1000,
        2000,
        1000,
        28000,
        39000,
        1000,
        43000,
        1000,
        1000
    ]
}`

**Comment by DanTup** [comment]
Thanks for the report - is the above the *full* contents of the file?

How big is the folder that you opened in VS Code when you saw this? Could you run `code --status` when you have that folder open? Thanks!

**Comment by DanTup** [comment]
Let me know if you still see this and you're able to provide the info requested above and I'll re-open this and do some more digging. Thanks!
