### ISSUE TITLE
Support camelCase deletion with CtrlBackspace

### ISSUE THREAD

**Issue by vogella** [Dart-Code/Dart-Code#2257]
Assume I have a method called Widget getStrangeFelixible() {

Cursor is behind Felixible. Now if press ctrl+backspace the whole identifier is deleted, I think it is common practise to delete only until the next camelCase break.

Current result:

Widget [CURSOR] () {

Expected result:

Widget getStrange[CURSOR]() {

**Comment by DanTup** [comment]
This behaviour is from the VS Code editor. `Ctrl+Backspace` is bound to "deleteAllLeft". There's another command called "deleteWordPartLeft" which is bound to Ctrl+Option+Backspace on Mac and seems to do what you want.

If you run **Preferences: Open Keyboard Shortcuts" from the command palette and then type `deleteWordPartLeft` in the search bar you should be able to view/change the binding.

Hope this helps!

**Comment by vogella** [comment]
Thanks @DanTup, works perfectly.
