### ISSUE TITLE
Closing labels are not visible!!

### ISSUE THREAD

**Issue by Rajdeep100** [Dart-Code/Dart-Code#2258]
Closing labels are not visible in VS Code [Windows 10], I am sure that it is enabled in settings but still they're not visible, I am a beginner in flutter app development and it's really confusing coding without labels. Is this a bug or can I make it work?

**Comment by DanTup** [comment]
Could you temporarily enable [analysis server logging](https://dartcode.org/docs/logging/#analyzer) and then restart VS Code and open a file where you'd expect to see them and then provide the log (and a screenshot).

Note: The log will contain parts of your source code, so you may want to capture the log from a clean `flutter create` project.

Thanks!
