### ISSUE TITLE
 getTextBeforeCursor on inactive InputConnection, and other issue

### ISSUE THREAD

**Issue by rachidev84** [Dart-Code/Dart-Code#2261]
I get these message in terminal
I build this code: Friendlychat 
https://codelabs.developers.google.com/codelabs/flutter/#8

Flutter version: 1.12.13 + hotfix 8
minSdkVersion 21
targetSdkVersion 28

-----the----message----

I/SurfaceView(27097): Punch a hole(dispatchDraw), this = io.flutter.embedding.android.FlutterSurfaceView{ce7f8eb V.E...... ........ 0,0-1080,1920}
I/SurfaceView(27097): updateWindow -- UPDATE_WINDOW_MSG, this = Handler (android.view.SurfaceView$1) {b745178}
I/Choreographer(27097): Skipped 2 frames!  The application may be doing too much work on its main thread.
V/PhoneWindow(27097): DecorView setVisiblity: visibility = 0, Parent = ViewRoot{f9079bf com.englishinarabic.english_arabic/com.englishinarabic.english_arabic.MainActivity,ident = 0}, this = DecorView@c92ba06[MainActivity]
D/FlutterView(27097): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@e56388c
D/Surface (27097): Surface::connect(this=0x7558c8b400,api=1)
W/libEGL  (27097): [ANDROID_RECORDABLE] format: 1
D/mali_winsys(27097): EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
I/Choreographer(27097): Skipped 1 frames!  The application may be doing too much work on its main thread.
D/GraphicBuffer(27097): register, handle(0x7558de8200) (w:1080 h:1920 s:1088 f:0x1 u:0x000b00)
D/ViewRootImpl(27097): swipeFromBottom mIgnoring true downY 1868 mScreenHeight 1920 mStatusBarHeight 54
D/ViewRootImpl(27097): swipeFromBottom mIgnoring true downY 1868 mScreenHeight 1920 mStatusBarHeight 54
D/ViewRootImpl(27097): swipeFromBottom mIgnoring === false downY 1868 mStatusBarHeight 54
D/GraphicBuffer(27097): register, handle(0x756a992d80) (w:1080 h:1920 s:1088 f:0x1 u:0x000b00)
I/SurfaceView(27097): updateWindow -- setFrame, this = io.flutter.embedding.android.FlutterSurfaceView{ce7f8eb V.E...... ......I. 0,0-1080,1920}
I/SurfaceView(27097): Punch a hole(dispatchDraw), this = io.flutter.embedding.android.FlutterSurfaceView{ce7f8eb V.E...... ........ 0,0-1080,1920}
W/IInputConnectionWrapper(27097): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27097): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(27097): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(27097): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(27097): getTextBeforeCursor on inactive InputConnection
D/GraphicBuffer(27097): register, handle(0x7558dd7300) (w:1080 h:1920 s:1088 f:0x1 u:0x000b00)
W/IInputConnectionWrapper(27097): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27097): finishComposingText on inactive InputConnection
D/FlutterView(27097): Detaching from a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@e56388c
D/Surface (27097): Surface::disconnect(this=0x7558c8b400,api=1)
D/GraphicBuffer(27097): unregister, handle(0x7558dd7300) (w:1080 h:1920 s:1088 f:0x1 u:0x000b00)
D/GraphicBuffer(27097): unregister, handle(0x756a992d80) (w:1080 h:1920 s:1088 f:0x1 u:0x000b00)
D/GraphicBuffer(27097): unregister, handle(0x7558de8200) (w:1080 h:1920 s:1088 f:0x1 u:0x000b00)
D/Surface (27097): Surface::disconnect(this=0x7558c8b400,api=1)
V/PhoneWindow(27097): DecorView setVisiblity: visibility = 4, Parent = ViewRoot{f9079bf com.englishinarabic.english_arabic/com.englishinarabic.english_arabic.MainActivity,ident = 0}, this = DecorView@c92ba06[MainActivity]
I/SurfaceView(27097): updateWindow -- onWindowVisibilityChanged, visibility = 8, this = io.flutter.embedding.android.FlutterSurfaceView{ce7f8eb V.E...... .......D 0,0-1080,1920}
D/Surface (27097): Surface::disconnect(this=0x7558c8b400,api=-1)
D/Surface (27097): Surface::disconnect(this=0x758cc55c00,api=1)
D/GraphicBuffer(27097): unregister, handle(0x756a901140) (w:1080 h:1920 s:1088 f:0x1 u:0x000b00)
D/GraphicBuffer(27097): unregister, handle(0x756444f380) (w:1080 h:1920 s:1088 f:0x1 u:0x000b00)
D/GraphicBuffer(27097): unregister, handle(0x75644501c0) (w:1080 h:1920 s:1088 f:0x1 u:0x000b00)
D/Surface (27097): Surface::disconnect(this=0x758cc55c00,api=1)
W/IInputConnectionWrapper(27097): reportFullscreenMode on inexistent InputConnection
W/IInputConnectionWrapper(27097): finishComposingText on inactive InputConnection

**Comment by DanTup** [comment]
This output is coming from Flutter, so I don't think there's anything wrong in the VS Code extension here.

Do you see the same thing if you run from a terminal window with `flutter run`?

**Comment by rachidev84** [comment]
@DanTup  same issue with Android Studio, as you said it is coming from Flutter, can you please report this is to flutter team

**Comment by DanTup** [comment]
@rachidev84 Flutter issues should be raised at https://github.com/flutter/flutter/issues. It's better for you to raise the issue since that way if the Flutter team need more info it's easier for them to ask you (and you'd also get notifications of updates).

In this case however, it seems like there may already be an open issue that covers this:

https://github.com/flutter/flutter/issues/9471

You may wish to Subscribe to that issue for updates. I'll close this one since there's nothing to do in the VS Code extension. Thanks!
