### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by loveintowind** [Dart-Code/Dart-Code#2263]
- Issue Type: `Bug`
- Extension Name: `dart-code`
- Extension Version: `3.8.0`
- OS Version: `Darwin x64 18.0.0`
- VSCode version: `1.41.1`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 57,
		"activateCallTime": 23,
		"activateResolvedTime": 185,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "Dart-Code.dart-code",
				"_lower": "dart-code.dart-code"
			},
			"activationEvent": "onLanguage:dart"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Illegal argument: character must be non-negative"
		},
		{
			"name": "Error",
			"message": "Illegal argument: character must be non-negative"
		},
		{
			"name": "Error",
			"message": "Illegal argument: character must be non-negative"
		}
	]
}
```
:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by DanTup** [comment]
@loveintowind can you provide more details about exactly what's happening here? It's not very clear from the info above what the problem is.

Also, your message includes:

> ⚠️ We have written the needed data into your clipboard. Please paste! ⚠️

Is the info above from the clipboard, or was there additional information not included?

Thanks!
