### ISSUE TITLE
Creating a launch.json

### ISSUE THREAD

**Issue by ejthayer** [Dart-Code/Dart-Code#2265]
Where is this drop down menu on the debug side bar with the Add Configuration button? That option does not exist or is very poorly explained.

**Comment by DanTup** [comment]
Can you clarify where the instructions are that refer to the Add Configuration button?

VS Code has recently updated its debug side bar. If you don't already have a launch.json, there is now a link that says "create a launch.json":

<img width="282" alt="Screenshot 2020-02-21 at 15 34 37" src="https://user-images.githubusercontent.com/1078012/75047986-b297c900-54bf-11ea-9448-a52b111d130f.png">

Once you have a launch.json, the deubg side bar will look different and have a drop-down with an Add Configuration option:

<img width="404" alt="Screenshot 2020-02-21 at 15 35 28" src="https://user-images.githubusercontent.com/1078012/75048048-ce9b6a80-54bf-11ea-9b11-beb909b73ab5.png">

If you can let me know where the bad instructions are, I can try to have them updated to better reflect the new VS Code side bar.

Thanks!

**Comment by DanTup** [comment]
It's not clear what needs to be done here. I'll re-open it if you're able to provide some additional info. Thanks!
