### ISSUE TITLE
Debugger breaks on assert in the Flutter framework but does show only the stackframes in the app project

### ISSUE THREAD

**Issue by escamoteur** [Dart-Code/Dart-Code#2273]
I just got an exception in the Flutter project and wasn't able to jump to the place where the assert had happened because VS code jumped to the function call in my code and didn't show the full stack trace to the origin of the exception that I can see in the debug console see here

![image](https://user-images.githubusercontent.com/16635729/75365185-1efa3a00-58bd-11ea-8721-922dbbc18870.png)

Please find attached the observatory log
[Dart-Code-Log-2020-01-03 17-20-06.txt](https://github.com/Dart-Code/Dart-Code/files/4256907/Dart-Code-Log-2020-01-03.17-20-06.txt)

**Comment by DanTup** [comment]
@devoncarew @bkoni when this exeption occurs, the stack we get back from the VM starts with the frame at `#3` in the debug console which prevents the user from navigating to the source where the `assert` is.

I thought it might be because we're showing the async frames on the left, but even the standard `frames` collection starts from that frame too:

```
==> {
	"id": "726",
	"method": "getStack",
	"params": {
		"isolateId": "isolates/3287690600338143"
	}
}
<== {
	"jsonrpc": "2.0",
	"result": {
		"type": "Stack",
		"frames": [
			{
				"type": "Frame",
				"kind": "Regular",
				"location": {
					"type": "SourceLocation",
					"script": {
						"type": "@Script",
						"fixedId": true,
						"id": "libraries\/@80172494\/scripts\/package%3Aexample%2Fmain.dart\/17082491a9d",
						"uri": "package:example\/main.dart",
						"_kind": "kernel"
					},
					"tokenPos": 2233
				},
				// ...
```

Does this seem like a bug, or is there a reason for it?

**Comment by escamoteur** [comment]
Just found out this even happens with asserts in my own package that is open in VS Code

**Comment by devoncarew** [comment]
(I think you wanted to cc @bkonyi above)

**Comment by DanTup** [comment]
@devoncarew whoops, thanks!

@escamoteur do you mean when the top frames aren't in the SDK? Can you post a screenshot showing both the debug console and the shown stack in the debug side bar? (also, the Dart/Flutter version may be useful to repro if it's considered a bug).

**Comment by escamoteur** [comment]
![image](https://user-images.githubusercontent.com/16635729/75371930-ea3fb000-58c7-11ea-9e8a-9bd36bc95953.png)

Flutter 1.15.4-pre.169 • channel master • https://github.com/flutter/flutter
Framework • revision 492fb6381e (14 hours ago) • 2020-02-25 22:29:16 -0500
Engine • revision 888a62cf22
Tools • Dart 2.8.0 (build 2.8.0-dev.10.0 73f6d15665)

**Comment by escamoteur** [comment]
InteractionManager is still my own package that if in the same workspace and open in VS code and not even the call to `InteractionManager.showRegisteredDialog ` is part of the stack trace in the debug panel

**Comment by DanTup** [comment]
Looking again - maybe this is correct - I think it's only breaking at the point that the future (which completed with an error) is `await`ed? The stack trace printed by Flutter is coming from where the error was created, but the VM is only pausing when it's `await`ed. I think if you enabled breaking on `All exceptions` it will probably pause with the top frames intact?

**Comment by escamoteur** [comment]
Hmm why does it only break if you await it? I try the all exceptions the next time I'm facing that problem.

**Comment by DanTup** [comment]
> Hmm why does it only break if you await it? 

I was thinking that if no code is trying to use the result of the future, then the error would never be noticed. However, I'm not sure if that's accurate.. If the break occurs when the exception is *thrown* (and the VM looks up the stack to decide if it is handled or not), then I would expect this to still break (the exception is thrown, there's no code in the stack that handles it - therefore should break).

Maybe @ZichangG could confirm this (or whether this seems like a bug).

**Comment by ZichangG** [comment]
I haven't touched debugger some time. But I don't think `await` will affect how VM pauses on `exceptions`. VM pauses when `exception` is thrown(it has to be unhandled).

**Comment by DanTup** [comment]
> I don't think `await` will affect how VM pauses on exceptions. VM pauses when exception is thrown.

Thanks - that makes sense (and my initial understanding was likely wrong).

I'm still unsure whether this is a VM bug though - does anyone know who would be able to confirm?

**Comment by DanTup** [comment]
@zichangg @bkonyi any ideas about the original issue here - why the debugger breaks further up the stack than expected (in the original screenshot, I'd at least have expected it to break inside the `showCustomDialog` method)?

**Comment by zichangg** [comment]
@cskau-g Do you mind taking a look? Looks like you are working closely with debugger recently.

**Comment by cskau-g** [comment]
Just to verify my understanding of the issue:
The issue is that the `Call Stack` seen on the left is missing the last couple of frames seen in the `DEBUG CONSOLE` at the bottom, correct?

I'm not particularly familiar with this, but I'm guessing VS Code gets both stacks from the service protocol, and the stacks are presumably two of {'frames', 'asyncCausalFrames', 'awaiterFrames'}?

If we have a small reproducing example I can check the stacks returned through the service protocol.

**Comment by DanTup** [comment]
@cskau-g yep, your understanding is right. However I'm unable to reproduce this, I always seem to break where I'd expect.

@escamoteur can you still repro this on a recent Flutter?

**Comment by escamoteur** [comment]
I just tried by forcing an assert in a Text widget and it was fine. I really should keep branches of reported errors. Was anything on on this matter?
The debugger jumped exactly to the assert and I had the full stack frame.

**Comment by DanTup** [comment]
@escamoteur great, thanks for confirming. I'm not sure what might have fixed it, but it's good that it's fixed 😄

If you do happen to see it again, please do try to grab a copy of the code to repro with. Thanks!
