### ISSUE TITLE
Dev tools command not showing.

### ISSUE THREAD

**Issue by bsutton** [Dart-Code/Dart-Code#2274]
Issue Type: <b>Bug</b>

So recently the dev tools option has gone missing from my debug menu.
I've been doing dart only work for a piece and have gone through a few upgrade/re-install cycles since I last tried to user the flutter dev tools.

Of note I still have the 'inspect widget' 'turn on debug paint' and other options in the command menu and these options work.
However there is no option for the Dev tools and as noted the debug menu icon is missing.

Extension version: 3.8.1
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 5.3.0-40-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3490)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|15.53GB (0.22GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by DanTup** [comment]
> as noted the debug menu icon is missing

Do you mean in the VS Code command palette? DevTools doesn't usually appear on the Debug menu.

The only requirement for it to show up in the command palete is `dartProjectLoaded`:

```js
{
	"command": "dart.openDevTools",
	"when": "dart-code:dartProjectLoaded"
},
```

This context is set to true during activation of the extension. The only reason I could think for this not to happen is if there's an error during extension activation (which throws, causing the code to be skipped). If this happens though, I think it should show up in the developer console (click Help -> Toggle Developer Tools) as an error activating. Is anything shown there?

**Comment by bsutton** [comment]
So I found (broadly) the source of the problem.
I was using a workspace in vscode.
When I debug the flutter project from within the workspace the Dev tools option is missing.
If I use Open Folder and directly open the flutter project then dev tools is available in the command pallet and on the debug tool bar (the blue flutter magnifying glass):

![image](https://user-images.githubusercontent.com/900408/75637250-6bf15e00-5c79-11ea-80bd-f316c963e40e.png)

I also note that the Hot reload 'lightening' icon is missing if I load the project from a workspace.

**Comment by DanTup** [comment]
Oh, I see what you mean by debug menu now, sorry!

The condition on that one is:

```
dart-code:anyFlutterProjectLoaded && inDebugMode && debugType == dart && dart-code:isInFlutterDebugModeDebugSession"
```

- dart-code:anyFlutterProjectLoaded - checks if we found any Flutter projects when scanning at startup
- inDebugMode - means a debug session is running (which it is)
- debugType == "dart" is the active debug session type (which it should be dart here)
- dart-code:isInFlutterDebugModeDebugSession - checks you're in a debug mode and not profile/release mode

It doesn't seem likely either of the middle two. The top one should match whether you see "Flutter" or "Dart" in the status bar with the version number (bottom right). If it shows "Flutter" then this should also be true. If it does not show Flutter, then that's why this would also fail.

The bottom one is based on the debug mode - this can be set in `launch.json`. It's possible for a workspace to have this set differently than opening the folder (since it can be set in the workspace folder, or the .vscode folder from the folder opened directly) so that could explain the difference.

Could you check those two, and let me know if neither explains it?

Thanks!

**Comment by bsutton** [comment]
So it looks like item 4 was the problem.
In the folder my launch config is:

```json
{
			"name": "SquarePhone - Debug - (sbs)",
			"type": "dart",
			"request": "launch",
			"program": "lib/main.dart"
		},
```

The same launch file is used from both the folder and the workspace.

However when I change my launch.json and add an explicit flutterMode then the workspace works correctly:
```json
{
			"name": "SquarePhone - Profile (sbs)",
			"type": "dart",
			"request": "launch",
			"program": "lib/app/debug_sbs_nowizard.dart",
			"flutterMode": "debug"
},
```
So it appears that a folder defaults to 'flutterMode':'debug' whilst a workspace does not.

**Comment by DanTup** [comment]
Strange - the default should always be `"debug"`:

https://github.com/Dart-Code/Dart-Code/blob/74e0e902755abcc512ae90be1c5a254f71414883/src/extension/providers/debug_config_provider.ts#L485

https://github.com/Dart-Code/Dart-Code/blob/699c291b3f6424753ffde81ba7724e04fcb25c70/src/extension/commands/debug.ts#L290-L291

Is there any where else this could come from (for example is it set to something else in another open project, or in the `.code-workspace` file)?

**Comment by DanTup** [comment]
Also - just to confirm, you *do* see "Flutter" and the version number in the status bar when opening the workspace?

**Comment by bsutton** [comment]
> Also - just to confirm, you _do_ see "Flutter" and the version number in the status bar when opening the workspace?

Yes.

**Comment by bsutton** [comment]
> Is there any where else this could come from (for example is it set to something else in another open project, or in the `.code-workspace` file)?

The contents of the workspace file are:
```
{
        "folders": [
                {
                        "path": "appname"
                }
        ],
        "settings": {}
}
```

**Comment by bsutton** [comment]
So I just tried experimenting in the workspace.
I added the flutterMode:debug statement to the launch script and started the debugger in the workspace and it started in flutter debug mode as expected.
The odd thing was that when I then removed the setting the workspace again launched the app in flutter debug mode.  
Even after restarting vscode the workspace will now always start in the correct mode.

I went hunting for some sort of 'settings cache' wondering if the vscode had 'save' the mode somewhere but couldn't find anything that looked like it might.

So essentially now I can't reproduce the problem :<

**Comment by DanTup** [comment]
Strange - I can't think of any explanations for that. This option isn't a "setting" as such, but part of the launch configuration. It's possible VS Code had some cached the launch configuration and not reloaded a change, though I would expect when you switched between workspace/folder it would've had to reload them.

I'll close this if you can't repro, but if you see it again do shout. I could try adding some extra logging to the launching to see if we can find at what point it becomes bad.

Thanks!
