### ISSUE TITLE
Is there any repl tool for dart.

### ISSUE THREAD

**Issue by liudonghua123** [Dart-Code/Dart-Code#2277]
I am a beginner for dart language, is there some repl tools for dart like node / browser console in js, python, ruby and so on. And I also want to know the advantages and disadvantages of each one.

**Comment by liudonghua123** [comment]
I found a online one https://dart.dev/#try-dart, but my network is not google, I would like to use a offline one running in my computer.

**Comment by DanTup** [comment]
When running a Dart script locally from VS Code and stopped at a breakpoint, you can type expressions into the Debug Console to have them evaluated:

<img width="462" alt="Screenshot 2020-02-29 at 12 03 16" src="https://user-images.githubusercontent.com/1078012/75607107-8a295380-5aeb-11ea-95ab-c8d2b74d5220.png">

I don't know if this does everything you wanted (it's only expressions, so you can't declare classes - for example). I don't know of anything currently that'll work like DartPad but offline.

**Comment by liudonghua123** [comment]
@DanTup Thanks for your tips. Is there any easier methods for starting this, like without a dart script and directly start from terminal via command.

**Comment by DanTup** [comment]
@liudonghua123 not that I know of. To use the debug console to evaluate expressions, you'd need to be running through the debugger. It should be as simple as creating a simple script (as I did above - it's just a simple `print`) and then run with `F5`.

**Comment by HerrNiklasRaab** [comment]
Is this dup of https://github.com/Dart-Code/Dart-Code/issues/906?

**Comment by DanTup** [comment]
#906 would still require you to run a script to have a live VM. I think this request was to be able to just have a REPL without running anything. I'm not sure that's really possible without it being a feature of the Dart VM though - for example in a REPL you may expect to be able to run `a = "foo";` and then reference `a` later, but I don't think that would work just using expression evaluation, as `a` wouldn't be accessible in future evaluations.

**Comment by DanTup** [comment]
Closing this as the question is answered and I think building a REPL is out of scope for the VS Code project. There's an open issue in the SDK project that would be a good place to follow/add 👍 s:

https://github.com/dart-lang/sdk/issues/39965

**Comment by fzyzcjy** [comment]
Seems that I have made a full-featured Dart REPL: https://github.com/fzyzcjy/dart_interactive :)

**Comment by lukehutch** [comment]
There's a Jupyter kernel for Dart: https://github.com/vickumar1981/jupyter-dart-kernel
