### ISSUE TITLE
`Wrap with Builder` fix

### ISSUE THREAD

**Issue by aloisdeniel** [Dart-Code/Dart-Code#2278]
It would be great to have `Wrap with builder` in default fixes.

There's a lot of cases where a builder is needed (list views, animations, MobX's observer, ...).

#### Before the fix :

```dart
return Container();
```

#### After the fix :

```dart
return Builder(
  builder: (context) => Container(),
);
```

Ideally the `Builder` class would be editable (just like `Wrap with widget`).

**Comment by DanTup** [comment]
Thanks for the suggestion! This would need to be added to the SDK (that's where the refactors come from) and it looks like there's already an open issue at https://github.com/dart-lang/sdk/issues/33957. Please subscribe there for updates. Thanks!
