### ISSUE TITLE
[Arch Linux]: Flutter hangs during installing app onto device

### ISSUE THREAD

**Issue by jchand99** [Dart-Code/Dart-Code#2279]
VSCode Info:
![image](https://user-images.githubusercontent.com/18605513/75597112-88b34900-5a61-11ea-84f8-8737e5ea2fc6.png)

Using the arch package 'visual-studio-code-bin.'

Version of Dart plugin trying to install: 3.8.1

Tried in both VSCode and VSCode Insiders.

Basically I'm trying to just install the extension so I can then debug an issue where the debugger hangs on trying to install the SDK. All I'm doing to have this initial problem is just open vscode, search "dart" in the extension search tab, and then hit the install button. It hangs on "Installing" for an insurmountable amount of time. If there is any more information that can be given that you might need just let me know (i.e. vscode logs for installing extensions if those exist and I can enable them while trying to install the extension then let me know how to and I'll send the logs).

Also slight side note...
On arch linux, the "Flutter" extension is supposed to go hand in hand with the "Dart" pluggin no? So when installing the "Flutter" extension it should also install the "Dart" extension along side it. For me the "Flutter" extension hangs as well on installing for what seems like an insurmountable time scale, but shows as installed after closing and re-opening vscode. It also doesn't install "Dart" along side it after re-opening vscode.

Thanks.

**Comment by DanTup** [comment]
Installing an extension is done entirely by VS Code, so if it's hanging during the install phase then this will need to be raised at https://github.com/microsoft/vscode (no code from the extension runs until after installation is complete). Please post the link back here so if anyone else has the same issue they can find it.

It's worth clicking Help -> Toggle Developer Tools to see if any errors are listed.

> On arch linux, the "Flutter" extension is supposed to go hand in hand with the "Dart" pluggin no? So when installing the "Flutter" extension it should also install the "Dart" extension along side it.

That's correct - the Flutter extension has a dependency on Dart, so it should install Dart automatically when you install Flutter.

Thanks!

**Comment by jchand99** [comment]
Tried installing the Flutter extension on VSCode Insiders edition and it (after a little while longer than windows) was able to install both the flutter extensioin and dart extension. Now the issue is that the extension when running with F5 hangs on "Installing build/app/outputs/apk/app.apk..."

Debug console output:
![image](https://user-images.githubusercontent.com/18605513/75613605-9cac8880-5afd-11ea-8ce3-18511ffd660c.png)

Notification output:
![image](https://user-images.githubusercontent.com/18605513/75613608-a635f080-5afd-11ea-9dca-674ac3dc6029.png)

**Comment by DanTup** [comment]
I suspect you may be running into https://github.com/flutter/flutter/issues/49185. Are you able to try on Flutter's `master` channel to see if the issue is fixed there?

**Comment by jchand99** [comment]
I have two systems running arch, an MSI Laptop and a custom built PC. On my laptop I already had the flutter/dart extensions installed in VSCode so I was able to test the updated flutter repo by uninstalling the flutter package 'flutter-git' from my system.

```
$ yay -Rcns flutter-git
# rm -rf /opt/flutter
```

and re-install the flutter package

```
$ yay -S flutter-git
```

After re-installing, on kernel version 5.5.6-arch1-1, the extension was able to load the app onto my device and allowed the hot reloads.

**Comment by DanTup** [comment]
Great, thanks for confirming!
