### ISSUE TITLE
Don't switch to Output tab when automatically installing packages

### ISSUE THREAD

**Issue by tp** [Dart-Code/Dart-Code#2280]
This extension seems to always the Output tab when it finds the packages are not up to date with `pubspec.yaml` and hence auto-fetches the latest packages. (I assume it's an extension issue and not a general VS Code behavior from this comment: https://github.com/Microsoft/vscode/issues/34221#issuecomment-329176447)

In my case this happens always when I am actively doing something in the integrated terminal, but makes it especially jarring as it breaks my flow: E.g. after checking out another Git branch with a different `pubspec` it switches to the Output tab and I have to manually switch back before continuing in the terminal (for example in this case often creating a new branch).

![image](https://user-images.githubusercontent.com/52437/75607158-6fa7a800-5af4-11ea-9711-2a5b3a170095.png)

## Proposed Solution

Either

- Offer an option to disable the automatic switching
- Just show a notification in the usual success case instead

Thanks!

**Comment by DanTup** [comment]
Yep, this is [done by the extension](https://github.com/Dart-Code/Dart-Code/blob/7970612504a692b3d9e2e591bc82d941b599f331/src/extension/commands/sdk.ts#L426-L428) and I think it's fair to not force this - we could add each line to the existing notification status and then just switch to the output window if the exit code is non-zero (or if possible, add a button for "Show Output"). Same probably applies for the other commands that run through the same code.

**Comment by uniquejava** [comment]
Hello.

I am mad about this.

I am working on TERMINAL tab (say. entering some git commands)

 but this plugin constantly disturbs me.

it's auto switching to the OUTPUT tab(even I hide it )

with the following messages from OUTPUT

```
exit code 0
[sales_anchor_app] flutter packages get
Running "flutter pub get" in sales_anchor_app...                    0.5s
exit code 0
[sales_anchor_app] flutter packages get
Running "flutter pub get" in sales_anchor_app...                    0.5s
exit code 0
```

 I can't find any settings about this. Can I temporarily disable the output.

**Comment by fbettag** [comment]
It's almost 6 years later and this issue is still happening.

**Comment by DanTup** [comment]
@fbettag please file an issue with more details if you think something isn't working correctly. I've just tested and the output pane was not shown (the code change that closed this issue set it to only show if there is a non-zero exit code).

**Comment by fbettag** [comment]
> [@fbettag](https://github.com/fbettag) please file an issue with more details if you think something isn't working correctly. I've just tested and the output pane was not shown (the code change that closed this issue set it to only show if there is a non-zero exit code).

which happens every 5 seconds when you're using agentic coding. from an UX perspective this is absolutely terrible to just switch views without the user asking for it. other languages/frameworks can do it too.

**Comment by DanTup** [comment]
@fbettag it's not clear to me why using agentic coding would result in a failed `pub get` every 5 seconds.

Not switching to the output tab when `pub get` fails could also be a considered terrible UX because it would be unclear why a package you just added is not working.

I'm happy to look at this, but you need to file a new issue and provide some more details, because there's not enough here for me to understand or fix the problem. Thanks!
