### ISSUE TITLE
Add suggestion for import extension methods.

### ISSUE THREAD

**Issue by benzsuankularb** [Dart-Code/Dart-Code#2281]
We may want to see a suggestion to import the extension method file when hitting `cmd+.` during the cursor was on an unimported method.

I'm not sure if we have created this issue yet but I've not found it.

**Comment by DanTup** [comment]
Thanks for the suggestion! The quick-fixes come from the analyzer in the SDK, so this would need to be implemented there. It seems like there's already an open request for it at https://github.com/dart-lang/sdk/issues/38894 that you can subscribe to for updates. Thanks!
