### ISSUE TITLE
Debugger sometimes get stuck in "running" state even though it's paused

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#2282]
Moving from https://github.com/dart-lang/sdk/issues/40725.

If you run this:

```dart
void main() {
  var steps = 0;
  while (true) {
    steps++; // Breakpoint here
    print('Has run $steps steps');
  }
}
```

Then keep pressing `F5`, you'll quickly end up in a state where VS Code thinks the app is running (it has a Pause button) but it is stopped at the breakpoint.

The issue seems to be that we process the response to the `resume` command sent to the VM *after* the `PauseBreakpoint` event, resulting in the UI being left in the "running" state when it's actually paused.

<img width="354" alt="Screenshot 2020-03-02 at 16 26 40" src="https://user-images.githubusercontent.com/1078012/75696575-b4257600-5ca3-11ea-997b-4c1906d6b9b1.png">

The events in the log are in the correct order (suggesting they came from the VM in the correct order):

![Screenshot 2020-03-02 at 16 26 50](https://user-images.githubusercontent.com/1078012/75696611-c3a4bf00-5ca3-11ea-853d-0149319701e4.png)

**Comment by DanTup** [comment]
When we get a response to a request, we resolve/request the promise. However the code waiting on it won't be executed until we next field. If the "next message" (the `PauseBreakpoint` event) is already received before this, then it may be in the queue before this, and it then gets called synchronously.

<img width="1008" alt="Screenshot 2020-03-02 at 16 38 56" src="https://user-images.githubusercontent.com/1078012/75696998-62312000-5ca4-11ea-8997-611957afa26c.png">

Forcing a yield in the event callback (for ex `setTimeout) may resolve it, though I don't know if it may introduce other subtle timing issues. This also sounds familiar like it's come up before...

**Comment by DanTup** [comment]
We hit this before here:

https://github.com/Dart-Code/Dart-Code/issues/471#issuecomment-350853000

The fix was quite specific to the streamed results from the analysis server though. Until I have a better fix, I'm going to add a `setTimeout(0)` around the events to and get them back in the correct order.

**Comment by DanTup** [comment]
Fix seems to work in my testing, and doesn't seem to have broken anything else.

@shyndman @jensjoha if nothing breaks on CI, I'll merge this and make a new build that you can use to check it seems fixed for you too.

**Comment by DanTup** [comment]
There's a dev build at https://github.com/Dart-Code/Dart-Code/releases/tag/v3.9.0-alpha.3 if anyone wants to try it out (you'll automatically be moved back to stable releases when the next version is released).

**Comment by shyndman** [comment]
Amazing! I'll use it for the day and report back.

**Comment by shyndman** [comment]
So far so good :)
