### ISSUE TITLE
The Dart Analyzer could not be started in vscode on Mac

### ISSUE THREAD

**Issue by crypto-maria** [Dart-Code/Dart-Code#2288]
<img width="1088" alt="Screenshot 2020-03-05 at 3 19 36 PM" src="https://user-images.githubusercontent.com/61719568/75972285-f8f41b80-5ef4-11ea-9723-9c8a0be9cacf.png">

On Mac, I am getting this error kind to help me solve it. I am new to Macintosh.

**Comment by DanTup** [comment]
Can you try opening a terminal and running `flutter doctor` and posting the output here?

It's possible this is macOS blocking executables downloaded from the web. If you open the "Security & Privacy" section of the macOS settings, on the General tab does it say Flutter was blocked and have an option to allow it?

**Comment by crypto-maria** [comment]
I don't see flutter anywhere in there

**Comment by crypto-maria** [comment]
`apple@MacBook-Pro ~ % flutter doctor
Waiting for another flutter command to release the startup lock...
`
i get this

**Comment by DanTup** [comment]
Ok, I would wait until `precache` has completed and then try again. Close VS Code too (as it may also try to spawn `flutter`). Post the full output of running `flutter doctor -v` (`-v` is verbose and includes more info), and also try VS Code again afterwards to ensure it wasn't fixed by a restart (or other `flutter` processes running).

**Comment by crypto-maria** [comment]
this is, my flutter precache is failing too even if I used `sudo`

**Result for `fluter precache`**

`apple@MacBook-Pro ~ % flutter precache          
Failed to download the Android dependencies                             
Downloading Android Maven dependencies...                           2.9s`

**Result for `sudo fluter precache`**

`apple@MacBook-Pro ~ % sudo flutter precache
Password:
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
Downloading Android Maven dependencies...                               
Failed to download the Android dependencies                     
Downloading Android Maven dependencies...                         666.2s (!)`

**Result for `fluter doctor -v`**

`apple@MacBook-Pro ~ % flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76,
    locale en-GB)
    • Flutter version 1.12.13+hotfix.8 at /Users/apple/Documents/flutter
    • Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.8.0 (build 2.8.0-dev.11.0)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with
        is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see
        https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1
      (API 25) (emulator)

! Doctor found issues in 1 category.
`

**Comment by DanTup** [comment]
I've not seen that before. I don't think it's related to the VS Code extension though so it would be better to ask at flutter/flutter (I see you have an open issue at https://github.com/flutter/flutter/issues/52007).

Once that's been resolved and Flutter seems to be working correctly from the command line, if you're still having issues with VS Code post back and we can try to troubleshoot that.

**Comment by crypto-maria** [comment]
Thanks.
