### ISSUE TITLE
Simulator doesnt stop in iOS

### ISSUE THREAD

**Issue by bpaul7101** [Dart-Code/Dart-Code#2291]
Hi - if I run vscode for a Flutter App attached to an iOS simulator - I have noticed that now , when I stop debugging - unlike the Android simulators - the iOS simulators do not stop (i.e the app still runs) - This never used to happen. Now everytime I run / debug my app, I notice that because the simulator doesnt stop - memory leakage occurs and the process gradually increases each time - ultimately forcing me to kill off the iOS simulator and restart.

I am running VS CODE 1.42.1

**Comment by DanTup** [comment]
Thanks for the info - I can repro this, both in VS Code and in Android Studio, so I've moved this to the Flutter repo at https://github.com/flutter/flutter/issues/52232 (you may wish to subscribe for updates).

Thanks!
