### ISSUE TITLE
Quickfix "Import Library" not showing for some package

### ISSUE THREAD

**Issue by skybur** [Dart-Code/Dart-Code#2294]
Recently I have been encountering this more so decided to report it.

I have some packages installed for my flutter project. When I tried to use classes from a package before importing it, the quick fix dialog doesn't show import option for that package. 

I've seen other issue mentioning this and tried restarting the project like mentioned, but I'm still experiencing this.

This is example using package [flutter_svg](https://pub.dev/packages/flutter_svg)

Before importing

![image](https://user-images.githubusercontent.com/11155424/76194023-decd7c80-6217-11ea-9a3d-56851909c2bd.png)

After manually importing

![image](https://user-images.githubusercontent.com/11155424/76194057-ef7df280-6217-11ea-8b41-ba272c2052e4.png)

Other package (dio) working
![image](https://user-images.githubusercontent.com/11155424/76194596-112ba980-6219-11ea-837b-8d8f897a3d1d.png)

VSCode 1.41.1
DartCode 3.8.1
```
[flutter] flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.17763.1039], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at D:\Devs\Flutter\flutter
    • Framework revision 27321ebbad (3 months ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = D:\AndroidSDK
    • ANDROID_SDK_ROOT = D:\AndroidSDK
    • Java binary at: D:\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[√] Android Studio (version 3.5)
    • Android Studio at D:\AndroidStudio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.41.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.8.1

! Doctor found issues in 1 category.
exit code 0
```

**Comment by skybur** [comment]
I'm also seeing this behavior during plugin development when trying to import class in the example project.

**Comment by DanTup** [comment]
I'm struggling to repro this, it seems to work ok when I added it to `flutter_gallery`:

<img width="441" alt="Screenshot 2020-03-09 at 10 20 44" src="https://user-images.githubusercontent.com/1078012/76204121-af0a7e80-61ef-11ea-91cf-d62d84217426.png">

Are you able to provide a sample project where you're seeing this? Ideally, a zip that includes things like your `.packages` and `package.json` files, and also the exact version of Flutter or Dart SDK you're using.

Thanks!

**Comment by skybur** [comment]
[repro_2294.zip](https://github.com/Dart-Code/Dart-Code/files/4306084/repro_2294.zip)
[repro_2294_2.zip](https://github.com/Dart-Code/Dart-Code/files/4306119/repro_2294_2.zip)


The first one is a plugin project. To repro this issue, open the project, then open `main.dart` in example folder then try to quickfix the error.

The second one I somehow also cannot reproduce with `flutter_svg` but I added `built_value` and in `repro.dart` I tried to instantiate a `BuiltMap` and `BuiltList`. Try to quickfix the error.

**Comment by DanTup** [comment]
Thanks - I was able to repro with your second project, but I believe that this is the issue described in https://github.com/Dart-Code/Dart-Code/issues/1978. You do not have `built_collection` referenced in your pubspec.yaml, only `built_value`. The quick-fixes only appear for dependencies listed in the pubspec and not transient dependencies.

There's an open issue about having a lint to pick up imports for transient dependencies here:

https://github.com/dart-lang/linter/issues/29

My interpretation is that you should not import packages that are transient dependencies (this could cause your code to break if your main dependency removes that transient dependency, for example).

**Comment by skybur** [comment]
Aaah so that's why. Previously I defined `flutter_svg` in my project, back then I could still import it normally. Then I removed it because one of my other package also depends on it, thinking it's enough. Mkay then, looks like I need to add back those deps I need. Thanks @DanTup, gonna close this issue since it's intended!

**Comment by DanTup** [comment]
@lreardon I don't believe all of the quick-fixes are documented anywhere but if it's not working correctly for you please file an issue with details and a screenshot of where you expect to see it but don't so I can take a look. Thanks!
