### ISSUE TITLE
Bulk refactor for Linter

### ISSUE THREAD

**Issue by amreniouinnovent** [Dart-Code/Dart-Code#2295]
I wonder if there is a way for bulk refactor to the lint issues
For example, 1000 issue requires `const` keyword _prefer_const_constructors_ how could I click auto fix all?

**Comment by DanTup** [comment]
Thanks for the suggestion! There's an open issue in the SDK about this here:

https://github.com/dart-lang/sdk/issues/37228

The fixes all come from the analyzer in the SDK so this would need implementing there. Please 👍 and/or subscribe to that issue for updates. Thanks!
