### ISSUE TITLE
Search results inside packages directories are duplicated for all copies

### ISSUE THREAD

**Issue by jacehensley-wf** [Dart-Code/Dart-Code#230]
When opening a file with <kbd>CMD</kbd> + <kbd>p</kbd> it will search all the `/packages` directories. Which is really noisy.

![image](https://cloud.githubusercontent.com/assets/12398382/21019801/0c91a524-bd2f-11e6-914e-aba7d7f9f5df.png)

**Comment by DanTup** [comment]
I was going to consider this a bug; but I'm wondering if people might like this (eg. find a class in a package they've pulled in so they can view it/read docs). I don't know if we can change it dynamically (eg. based on an option) though.

Will try and have a play around and see what I think.

**Comment by jacehensley-wf** [comment]
Hmm, good point. Maybe it should search based on the `.packages` file instead of the `packages` directory, so it doesn't get a whole lot of copies.

**Comment by DanTup** [comment]
Good point; didn't pay attention to the screenshot correctly! I think the packages folders are going away, but then we probably need to ensure this is searching the real location of them to preserve the ability to search.

**Comment by jacehensley-wf** [comment]
While the packages folders are going away, there are currently some projects that need them. The reason I need to keep them around is no sass transformer supports `package:` imports. Which will be solved by `dart-sass`, but that's besides the point.

Also would be nice to at least not search the current project in the `packages/` directories.

**Comment by DanTup** [comment]
I didn't realise some things still needed them, but I did re-mark this as a bug and think it should be fixed.

> Also would be nice to at least not search the current project in the packages/ directories.

Also a good point!

You can fix this yourself for now by [adding `search.exclude` to your user settings](https://code.visualstudio.com/docs/customization/userandworkspace), but I'll investigate if we can influence the default behaviour.

**Comment by DanTup** [comment]
I cannot repro this anymore; I wonder if Code has been updated not to show duplicates when the resolved paths are identical (I can't find a case about this to confirm unfortunately).

I'm marking this as fixed in Code, but feel free to post back if anyone still sees this (though without `--packages-dir` it might not be an issue anyway).

![Search results](https://cloud.githubusercontent.com/assets/1078012/24291317/6266c2be-1080-11e7-80f0-695a03a202a6.png)
