### ISSUE TITLE
Code formatting causes Chinese character coding confusion in dart files.

### ISSUE THREAD

**Issue by yangfanyu** [Dart-Code/Dart-Code#2302]
Issue Type: <b>Bug</b>

When I execute the code format operation shift + option + F in some dart files with Chinese characters, the Chinese character code of these files will become confused.

Extension version: 3.8.1
VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (3.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by yangfanyu** [comment]
、
<img width="453" alt="截屏2020-03-18下午5 31 53" src="https://user-images.githubusercontent.com/17940584/76946192-9eb87900-693e-11ea-886f-190f8c9758ca.png">
<img width="286" alt="截屏2020-03-18下午5 32 55" src="https://user-images.githubusercontent.com/17940584/76946198-a1b36980-693e-11ea-9f98-bfe7fa1fdb09.png">
<img width="378" alt="截屏2020-03-18下午5 33 14" src="https://user-images.githubusercontent.com/17940584/76946205-a4ae5a00-693e-11ea-9db9-13d45db09f2a.png">

**Comment by DanTup** [comment]
Thanks for the report! This was raised in #2140 and is fixed for the next release.

There's an alpha build at https://github.com/Dart-Code/Dart-Code/releases/tag/v3.9.0-alpha.3 that contains the fix if you would like to use that while waiting for the stable release.
