### ISSUE TITLE
Prevent generated files from opening when renaming

### ISSUE THREAD

**Issue by HerrNiklasRaab** [Dart-Code/Dart-Code#2303]
Currently, when I am using the reflectable library and I rename for example a class name, every generated file who needs to be changed get's opend. But because they are generated, it doesn't need to be that way.

**Comment by DanTup** [comment]
I don't know if the analyzer has enough knowledge to know that these files are generated - but assuming it did and it excluded them from the rename, you'd end up with a lot of compile errors until you saved all files and then re-generated the files.

Is this causing any problems (beyond the files being opened as background tabs) in the editor?

**Comment by HerrNiklasRaab** [comment]
Hey @DanTup,

it's annoying. Imagine the following scenario: Renaming a class. Renaming affects also 10 generated files.

VS Code now opens all 10 files, but in preview mode (with that not saved indicator).
- Problem: Having 10 files opened disturbed your workflow because you don't need them open.

Now you can close them (without saving) one by one.
- Problem: For every one of the 10 files there comes this popup that there are unsaved changes and you need to confirm that you want to save without changes.

You can close them by using the "Close all editors" button in VS Code and select that you don't want to save them.
- Problem: If you have unsaved changes in other files they get lost. 
- Problem 2: You close all open files, even non-generated.


> I don't know if the analyzer has enough knowledge to know that these files are generated - but assuming it did and it excluded them from the rename, you'd end up with a lot of compile errors until you saved all files and then re-generated the files.

They should be renamed, but the files shouldn't open in the editor.


Can you understand why this behavior is very stressful and not a Flutter like experience? All the steps above shouldn't be part of developing because you don't need them.

Thanks,

Niklas

**Comment by DanTup** [comment]
> They should be renamed, but the files shouldn't open in the editor.

Unfortunately there's no way we can apply changes to the files without them being opened in the editor. The changes are not written to disk immediately, they are made in-memory in VS Code. There's no way to modify files in-memory in VS Code without them being open (since you would have no way to save them, discard them, etc.).

Is there a reason you can't just press Save All after doing the rename and allow the files to be saved? Does this cause other issues?

**Comment by HerrNiklasRaab** [comment]
This can be closed, because we removed all of the code generation from our project. The time we saved with Hot Reload, we spent fixing issues with code generation.
