### ISSUE TITLE
Question: How do you disable Widget Code Hints?

### ISSUE THREAD

**Issue by danielezra** [Dart-Code/Dart-Code#2308]
Hi, I'm not very sure how do you call those bits with `// Column`, `// Scaffold` etc. but these are basically making it harder for me to code rather than help me.

How do I turn it off?

![image](https://user-images.githubusercontent.com/57745964/77184090-3d450580-6b0a-11ea-9acc-be398ab5b500.png)

**Comment by DanTup** [comment]
These are called "Closing labels" and can be disabled with the `"dart.closingLabels"` setting in VS Code:

<img width="886" alt="Screenshot 2020-03-20 at 16 30 49" src="https://user-images.githubusercontent.com/1078012/77184763-2e3d6380-6ac8-11ea-853b-27e369753c66.png">

If you have any problems with this, let me know!
