### ISSUE TITLE
[feature request] community icons gutter preview

### ISSUE THREAD

**Issue by pd4d10** [Dart-Code/Dart-Code#2309]
Coming from this issue: https://github.com/pd4d10/flutter-vector-icons/issues/4

It would be great if community icons could have a gutter preview.

**Comment by DanTup** [comment]
Are the icons available as SVGs inside the package?

Currently the existing icon files are shipped inside the VS Code extension and it has specific knowledge of them. I think to support community icons it would be best to come up a some generic way for packages to declare a list of their icons (and paths to SVG files) so the VS Code extension could include them (it wouldn't scale very well if we maintained specific code for each package with icons in the VS Code extensions).

For example, if your package had some sort of JSON manifest (at an agreed location) that includes all icon names and paths to SVGs (in an agreed format that other packages could also copy), maybe we could parse that.

Does it seem feasible?
