### ISSUE TITLE
Invalid log paths (eg. copied from other platforms) may result in activation failures without a helpful error message

### ISSUE THREAD

**Issue by mukhsin** [Dart-Code/Dart-Code#2310]
Hi,

I have an error when running flutter extensions in vscode
I always get "command 'flutter.blaBla' not found
I opened developer tools and I got this error
<img width="801" alt="Screen Shot 2020-03-21 at 21 55 08" src="https://user-images.githubusercontent.com/9584947/77229221-23b1c580-6bbf-11ea-8c36-bb653ccaa4f5.png">

I'm sure this error comes from another extension I'm using (for syncing extensions)
https://github.com/shanalikhan/code-settings-sync

It says that it cannot create a directory inside /home/ubuntu, which is in my old laptop
Currently, I'm using macos

What I tried:
1. uninstall and reinstall flutter and dart extensions from extensions sidebar
2. manually remove extension folder inside .vscode/extensions then reinstall from extensions sidebar
3. open developer tools and got that error

Thanks

**Comment by DanTup** [comment]
Can you try expanding the top error ("Activating failed") and post the stack?

If that doesn't have much more info, also try clicking Help -> Toggle Developer Tools and then check the Console tab to see if there's any more info there on what went wrong.

**Comment by mukhsin** [comment]
Here what I got
<img width="799" alt="Screen Shot 2020-03-22 at 10 02 35" src="https://user-images.githubusercontent.com/9584947/77241438-a325b000-6c24-11ea-9e04-4ae201cf13ec.png">

**Comment by DanTup** [comment]
> But I'm sure this is caused by sync extension I'm using

Ah - are you syncing between machines that have different file system paths for your settings? For example SDK paths? It could be that these paths have been synchronised so we're trying to make folders in the wrong place.

If so, can you tell which paths have been synchronised? And also confirm whether you're using a third-party settings sync, or the built-in VS Code behaviour (this might only be in Insiders?).

**Comment by mukhsin** [comment]
Yes, I installed Ubuntu on my old machine and currently I'm using macbook

I'm not sure which folder the sync extension I'm using uses
It might ~/.vscode/extensions

I tried to uninstall both flutter and dart extension
Then resync my extensions so flutter and dart should be removed on my gist
Then uninstall vscode and reinstall it
Then install sync extension and pull my extensions from my gist
But it doesn't work and I still got the error

This is my last error after I did steps above
<img width="800" alt="Screen Shot 2020-03-23 at 10 01 10" src="https://user-images.githubusercontent.com/9584947/77316259-a1024500-6d3b-11ea-8952-bce5c04519e1.png">

**Comment by DanTup** [comment]
Which sync extension are you using? Is it synchronising just the installed extensions, or also the *settings* for them?

Can you open your VS Code Settings (press `Cmd`+`,`) and see if any of the settings have invalid paths (that may have been copied from Ubuntu), eg. starting with `/home`?

**Comment by mukhsin** [comment]
Ah, I got it
Here I found dart.extensionsLogFile which points to /home/ubuntu/extension.txt
![image](https://user-images.githubusercontent.com/9584947/77321062-33a6e200-6d44-11ea-92dc-98ff81ce3b4a.png)

I removed that line and now I can fun flutter doctor from Cmd+Shift+P
![image](https://user-images.githubusercontent.com/9584947/77321535-e8d99a00-6d44-11ea-8320-218b36908e18.png)

Thank you so much

**Comment by DanTup** [comment]
Great, glad you sorted it!

We should handle this a bit better though, to make the error less cryptic. I'll keep this issue open to try and come up with some improvements.

**Comment by mukhsin** [comment]
Ok
Now I can run flutter and dart normally on vscode
Thanks
