### ISSUE TITLE
Support running all tests whilst debugging

### ISSUE THREAD

**Issue by tomgilder** [Dart-Code/Dart-Code#2312]
I don't know if this is a VS Code or Dart Code issue, but currently you can't access the "Run All Tests" command whilst debugging an app.

You can still run individual tests, so I don't see why you can't run them all. I sometimes want to check all tests are passing without existing the debugging session.

**Comment by DanTup** [comment]
I don't think there's a great reason to prevent this (it was done to avoid you hitting the button twice and spawning two lots of them all). I've removed the restriction and confirmed I can run tests while an app is running. Thanks for the suggestion!
