### ISSUE TITLE
Request: Add easy way to create launch config from test run

### ISSUE THREAD

**Issue by shyndman** [Dart-Code/Dart-Code#2316]
Hello!

I run tests directly from VSCode quite a bit, and I've identified a slowdown in my workflow that might be encountered by others. 

The slowdown is having to think about the name of the file containing the test(s) I want to run. I have to think of the file name, open it via the command palette, then click on one of the inline run links (they might be called codelens links?).

In general this is great for one off runs, and while writing tests, but in this specific flow of repeatedly debugging a single piece of code I'm finding that I'm losing my place. I'll be very deep in the debugging process, and every time I need to restart the test I have to think about it. It's a noticeable context switch.

My suggestion is that right clicking on a previous test run test/group in the VSCode "Test" panel displays a "Add launch config" context menu item. When pressed, a launch config will be added to the containing project's `launch.json`, and `launch.json` will be displayed in the focused editor tab. This way I can repeatedly run the tests without having to find anything. All muscle memory.

I think it would be especially great because I'm not clear on what the launch config for a test even looks like (and I'm sure I'm not alone.) A bit of codegen there would be a valuable learning experience.

Another possibility? A menu item that reruns the most recent launch. I feel like this must already exist, but I can't find it.

Thanks!

**Comment by DanTup** [comment]
> A menu item that reruns the most recent launch. I feel like this must already exist, but I can't find it.

In the command palette we have a **Dart: Rerun Last Debug Session** command that will re-run the previous debug session. It should be bound to `cmd+shift+f5` / `ctrl+shift+f5` by default.

The launch config for running a test file is just the same as a script, but with the path to the test script:

```
{
	"name": "Dart",
	"program": "test/foo_test.dart",
	"request": "launch",
	"type": "dart"
}
```

When you run a single specific test, we just add an argument that filters:

```
{
	"name": "Dart",
	"program": "test/foo_test.dart",
	"request": "launch",
	"type": "dart",
	"args": ["--name", "my test name"]
}
```

Adding this to the context menus for tests feels a little weird (it doesn't seem like creating test-specific launch configs should be encouraged), but if the above doesn't solve your need maybe we can come up with something.

**Comment by shyndman** [comment]
That's more than good enough. Thanks @DanTup

**Comment by DanTup** [comment]
Great! If you hit any issues with them of it feels awkward, do let me know and we can revisit. Thanks!
