### ISSUE TITLE
Debugging a Flutter Web App doesn't show variable value when hovered

### ISSUE THREAD

**Issue by kunit1** [Dart-Code/Dart-Code#2318]
The debugging experience when debugging a Flutter Web app is not on par with debugging a mobile app.
Issues when debugging a Web App:
- Placing mouse pointer over a variable will not display its value when on a breakpoint
- Local Datetime variables don't display in human readable format (e.g. _value: 1585227422694.0) in the debug pane

**Comment by tomgilder** [comment]
Is this fixed now? I noticed it's started working 🎊

**Comment by jovesharma** [comment]
Any updates so far on this?

**Comment by DanTup** [comment]
@jovesharma the behaviour isn't something that comes from the extension, but from `dwds` (which is part of webdev). I'm not familiar with the current status so if you have specific examples of things that aren't working correctly, I would recommend filing issues at https://github.com/dart-lang/webdev with very specific examples/screenshots.

(it's also worth ensuring you're on the latest version of Flutter, as it will be the version of `dwds` included in Flutter that matters here).
