### ISSUE TITLE
Debug toolbar doesn't always show flutter specific debug tools when toolbar is docked

### ISSUE THREAD

**Issue by unknowledgeable** [Dart-Code/Dart-Code#2321]
The debug toolbar infrequently opens the hot reload, reload and DevTools Widget Inspector buttons when debug is started.

I have my settings.json configured with `"debug.toolBarLocation": "docked",`

I frequently have to disable this setting and re-enable it for the dart/flutter tools to show up.

**Comment by DanTup** [comment]
I don't seem to be able to repro this. When it happens and you toggle the setting, does the button appear immediately, or do you need to restart the debugging session?

If it shows immediately, then this sounds like a VS Code bug (we can't do anything when the debug toolbar moves - VS Code controls what's visible and what's not). If you need to restart the debug session, then maybe there's a bug that is causing us not to set the button up correctly for some launches (though this should not be any different based on the location of the debug toolbar).

**Comment by unknowledgeable** [comment]
From your description it seems it's a VS Code bug then. Here's a gif of the behaviour. All I'm doing is uncommenting and saving the setting in settings.json.

![flutter-vscode-docked](https://user-images.githubusercontent.com/43091756/77925454-c8f22b00-729c-11ea-817f-6dbdbb531f48.gif)

Also, I've realised I'm on the stable releases for Dart and Flutter so apologies if it's already been fixed in more recent updates. I don't really want to go messing about with my setup at the moment.

**Comment by DanTup** [comment]
@unknowledgeable I think the buttons are just hidden in the overflow ("...") menu initially? For reasons I can't explain, when you're undocking/docking, it seems to move to the left more, so that more buttons fit on before it overflows into the menu?

**Comment by unknowledgeable** [comment]
@DanTup Unfortunately they're not in there, I only see "Start Additional Session", "Open launch.json" and "Debug Console".

The buttons don't appear if I resize the sidebar either.

**Comment by DanTup** [comment]
Oh, if the overflow menu is just those options and not the debug toolbar buttons, then yes - this seems like a VS Code bug to me.

**Comment by DanTup** [comment]
Closing this as I don't think there's anything to do here, sounds like a VS Code bug. If you raise an issue with them, please post the link back here for anyone else that stumbles across this issue having the same problem. Thanks!
