### ISSUE TITLE
Symbols are doubled in VSCode's cmd+shift+O outline popover if additionalAnalyzerFileExtensions includes Dart/duplicates

### ISSUE THREAD

**Issue by shyndman** [Dart-Code/Dart-Code#2323]
<img width="605" alt="Screen Shot 2020-03-27 at 12 10 30 PM" src="https://user-images.githubusercontent.com/42326/77776348-3d6e6500-7024-11ea-8b90-4d7048f4c5c1.png">

The outline view embedded in the VSCode Explorer does not demonstrate the same problem.

**Comment by shyndman** [comment]
Ah, it could very well be related to this: https://github.com/microsoft/vscode-cpptools/issues/4445

I am using a multi-root workspace.

**Comment by shyndman** [comment]
Yes, insiders fixes this. I'm closing this off.

**Comment by DanTup** [comment]
Hmm, interesting - that issue looks like i's describing an insiders version of the C++ extension, not VS Code? I wouldn't expect that to affect this.

If you manage to repro this again, please let me know!

**Comment by shyndman** [comment]
You tried with a multi-root workspace? Happens every time for me. Never with Insiders.

It sounds like it's being encountered with C++, but is related to the multi-root workspace.

**Comment by DanTup** [comment]
> You tried with a multi-root workspace?

I did - one with flutter_tools and flutter_test in it. If you can reliably repro in Stable and not in Insiders, then it doesn't sound like it could be a VS Code bug (so not sure why C++ did an extension update to fix it).

Happy to do some digging if you can make a small repro though to be sure. Thanks!

**Comment by shyndman** [comment]
This is happening to me consistently when opening any two or more Dart projects. I just tried across a variety of input, and symbols double up regardless.

Next, I disabled all of my installed extensions, except for Dart and Flutter. The issue persists.

Thoughts?

**Comment by shyndman** [comment]
Ah, interesting. Happens outside of multi-root projects too. Any Dart project is displaying this behaviour.

**Comment by DanTup** [comment]
Weird, not sure why I don't see it. Can you reproduce in a really simple project like a new `flutter create` project? And could you capture a log for this (with **Dart: Capture Logs**) for me to review?

**Comment by shyndman** [comment]
Here you go. What I did:

1. Created a new Flutter project
2. Opened it from the command line `code DartCode_double_symbols`
3. Dart: Capture Logs
4. Navigated to main.dart
5. cmd+shift+O

Result:
<img width="608" alt="Screen Shot 2020-03-31 at 9 30 54 AM" src="https://user-images.githubusercontent.com/42326/78032018-5a5fac80-7332-11ea-8e4a-7c1c29029232.png">

[Dart-Code-Log-2020-02-02 09-26-41.txt](https://github.com/Dart-Code/Dart-Code/files/4409307/Dart-Code-Log-2020-02-02.09-26-41.txt)

**Comment by shyndman** [comment]
I decided to see if anything stood out in my settings as potentially being related, and noticed that I had `dart.additionalAnalyzerFileExtensions` set with one of the extensions as...dart.

Removing it solved the issue. 😳

Sorry for the false alarm. I was working on an analyzer plugin a few weeks back and was poking at things to see how they worked.

**Comment by DanTup** [comment]
Good catch! This is a bug - I think it's causing us to register the provider twice (once for the hard-coded Dart, and once for the one you added), which means VS Code is asking both for results and concatenating them.

Even though this shouldn't be common, we should fix this. Thanks!

**Comment by DanTup** [comment]
We should probably distinct the whole list, so if you also added another extension to the list multiple times, it wouldn't cause the same thing.
