### ISSUE TITLE
Add import folding (language aware)

### ISSUE THREAD

**Issue by lukepighetti** [Dart-Code/Dart-Code#2324]
IntelliJ has import folding and it's super nice when working in a file with a lot of imports. It acts like block folding in VSCode but it also works on lists of imports.

Would it be possible for us to get import folding using the VSCode folding provider API?

https://code.visualstudio.com/updates/v1_23#_folding-provider-api

**Comment by DanTup** [comment]
This should already work, implemented in #578 (shipped in v2.13 -> https://dartcode.org/releases/v2-13/#improved-folding).

I tested and it seems to work ok for me:

<img width="290" alt="Screenshot 2020-03-28 at 11 10 26" src="https://user-images.githubusercontent.com/1078012/77821788-c5b43f00-70e4-11ea-85d8-1de0c06883f8.png">

Is it a specific file you don't see it in? Are you on a recent Dart SDK and haven't disabled `dart.analysisServerFolding` or changed `editor.foldingStrategy`?

**Comment by lukepighetti** [comment]
I'm on v3.8.1 and I don't have it in any of my files and never have. This is my global settings file

```json
{
    "workbench.colorTheme": "Atom One Dark",
    "editor.fontFamily": "FiraCode-Retina",
    "editor.fontLigatures": true,
    "editor.fontSize": 14,
    "explorer.confirmDelete": false,
    "git.enableSmartCommit": true,
    "explorer.confirmDragAndDrop": false,
    "dart.debugExternalLibraries": false,
    "dart.debugSdkLibraries": false,
    "[jsonc]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[javascript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[json]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    }
}
```

**Comment by DanTup** [comment]
Do you get any folding at all? I noticed you need to hover your mouse in the gutter before the folding icons appear.

**Comment by lukepighetti** [comment]
Oh my goodness it was actually there. Somehow I missed it even when I was looking for it explicitly.

**Comment by DanTup** [comment]
Yeah, it caught me out too :)

> Is there any way to have the import fields collapsed in all files by default?

Not that I know of. I don't think there are even VS Code APIs for extensions to expand/collapse specific ranges like that. It wouldn't be a bad feature for TypeScript either though =)

<img width="845" alt="Screenshot 2020-03-30 at 11 01 44" src="https://user-images.githubusercontent.com/1078012/77900410-e6f86500-7275-11ea-876c-37d89c3d8d68.png">

**Comment by lukepighetti** [comment]
No problem! I'm comfortable keeping this closed. Thanks Dan.
