### ISSUE TITLE
VS Code not hot reloading Flutter app running on iOS simulator/Android emulator after saving current editing file

### ISSUE THREAD

**Issue by shatyajeet** [Dart-Code/Dart-Code#2328]
VS Code: 1.43

I have been using VS Code's hot reload for quiet some time now. Somehow suddenly it has stopped hot reloading the app on the simulator/emulator after saving the file.

The Flutter Hot Reload on Save and Flutter Hot Restart on Save settings are enabled too. Clicking on the thunderbolt icon logs:
[        ] Hot reload performed in 67ms.
[        ] Reloaded 0 of 478 libraries in 69ms.
Only clicking on the green restart icon, restarts the app and then the changes are being reflected.

I have attached the log file for the same below.

[Flutter Hot reload issue in VS Code](https://pastebin.com/5gKTtCrT)

**Comment by shatyajeet** [comment]
Never mind. Dart doesn't hot reload non class Widget in the runApp function. Closing this.

**Comment by DanTup** [comment]
Sorry for the delay but glad you figured this out. For anyone else that may come across this issue looking for an answer, there's some info about the things that can't be hot reloaded on the Flutter site here:

https://flutter.dev/docs/development/tools/hot-reload
