### ISSUE TITLE
Add diagnostics to error logs for new driver

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#233]
Lots of errors showing in analytics:

> (diagnostic.getDiagnostics) Bad state: Should not be used with the new analysis driver

This is all the information we record. @devoncarew I'm guessing it's probably you or someone on the Dart team using this. I don't know a lot about the new driver so it's unclear if this is a temporary limitation or this method going away? If the new driver won't support this and it's imminent, we should probably just remove this call and the associated error reporting code, otherwise we should probably detect it (this might mean parsing the additional args or this error coming back) and avoid calling again.

**Comment by devoncarew** [comment]
It's this guy: https://github.com/dart-lang/sdk/issues/28068. `diagnostic.getDiagnostics` is not yet implemented with the new driver -

**Comment by DanTup** [comment]
Doh, how did I not find that issue when I looked?

If it's just NYI and likely to turn up soon, maybe it's not worth doing anything with. Is it causing issues (like spamming you with notifications)? I could just stick a check for `--enable-new-analysis-driver` in the error report generator for now and push a fix out (and we can remove it later).

**Comment by devoncarew** [comment]
It means that every error is reported, and then followed up with a report the the exception from getDiagnostics. Not great; hopefully a transitory problem.

**Comment by DanTup** [comment]
I've put in a temporary fix (https://github.com/Dart-Code/Dart-Code/commit/589b8939a8fd5508d1b518afde78179846450e35) and pushed out an update (`v0.14.6`). Should show up code in a few minutes.

Will leave this issue open as a reminder to remove the exclusion or migrate to an equiv API once it's sorted.

**Comment by DanTup** [comment]
We may need to do a version check here to ensure we don't try to call it for the SDKs that didn't have it.

**Comment by DanTup** [comment]
Added a check for analysis server version 1.18.1 (which isn't in latest stable, but was added a few months ago). Not bothering with handling old (old driver) SDKs for this now, since it's unlikely there's any significant use.
