### ISSUE TITLE
Emulator 

### ISSUE THREAD

**Issue by NomanManiyar** [Dart-Code/Dart-Code#2331]
Issue Type: <b>Bug</b>

can't connect emulator 
emulator is launched but it failed to connect the vscode editer

Extension version: 3.9.0
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by DanTup** [comment]
When the emulator is launched, does it show up in the list if you run `flutter devices` from the terminal?

**Comment by NomanManiyar** [comment]
The problem has resolved sir 
I think that it was Emulator Accelerator(HAXM installer) problem.
I have updated it so it is now working properly.

**Comment by NomanManiyar** [comment]
The problem has resolved sir 
I think that it was Emulator Accelerator(HAXM installer) problem.
I have updated it so it is now working properly.

**Comment by DanTup** [comment]
Great, glad to hear!
