### ISSUE TITLE
Editing external code

### ISSUE THREAD

**Issue by ViniciusSossela** [Dart-Code/Dart-Code#2332]
Would be possible to have some intelligence on editing external code using VSCode?

We have developed some internal packages and we use them in our main project. When we need to make some changes to the packages, we can't do it running the main project on VSCode because it hasn't any intelligence.

Example:

<img width="451" alt="Screen Shot 2020-04-04 at 08 57 27" src="https://user-images.githubusercontent.com/4993276/78450154-f3ecce00-7652-11ea-9414-3682bb62d487.png">

<img width="343" alt="Screen Shot 2020-04-04 at 08 59 19" src="https://user-images.githubusercontent.com/4993276/78450152-edf6ed00-7652-11ea-8244-fdbc9433f152.png">

As you can see in the image, VSCode doesn't warn about any issue/error on the code.

**Comment by DanTup** [comment]
We currently analyze only the folders that you've opened in VS Code. The recommended approach would be for you to open the packages you're working on in VS Code too. You can do this with multi-root workspaces (for ex. click **File -> Add Folder to Workspace** and open the package too).

Is there anything preventing you from working this way?

**Comment by ViniciusSossela** [comment]
@DanTup This is just awesome! :tada: :tada: I didn't know about that.

You are the man!  Kkkkk. 
Thank you so much!

**Comment by DanTup** [comment]
Glad it works for you! If you have any issues working that way, do file issues. Thanks!
