### ISSUE TITLE
When running Flutter app, old version of app launches on emulator

### ISSUE THREAD

**Issue by uzairleo** [Dart-Code/Dart-Code#2346]
Hi there ! can someone plz fix the bug i faced from almost a month each time i debug my code and run the application in debug mode the first screen on the emulator will always be the old one instead of the new one i did some changes and therefore almost all the time i run twice the application and then problem solved.:(

**Comment by DanTup** [comment]
Thanks for the report! This sounds like a Flutter issue (VS Code simply calls `flutter run` which should build and install the new version). There are some open issues in the Flutter issue tracker that describe the same issue, for example:

https://github.com/flutter/flutter/issues/54280

I would recommend posting on there with as much detail as you can to help track it down.

Thanks!
