### ISSUE TITLE
break point not hitting 

### ISSUE THREAD

**Issue by Lokeswara-betha** [Dart-Code/Dart-Code#2347]
When I put some breakpoints in editor , they are not stopping while debugging my app.

![image](https://user-images.githubusercontent.com/60268240/79044367-59782600-7c22-11ea-9b27-48e59638bb27.png)

Below is my config code:
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Flutter",
            "request": "launch",
            "type": "dart",
            "flutterMode": "debug"
        }
    ]
}

**Comment by DanTup** [comment]
How are you launching your app? (Which keyboard shortcut/menu item)?

Could you capture a log:

- Run the **Dart: Capture Logs** command from the VS Code command palette
- Untick Analysis Server, but leave the rest ticked
- Launch your app and try to hit the breakpoint
- After it doesn't hit the breakpoint, click **Cancel* on the logging prompt to stop logging and open the log file
- Ensure there's nothing sensitive in the log (it may contain info from your project) and paste in a Gist or similar, and paste the link back here

Thanks!
