### ISSUE TITLE
add command "run current dart file in terminal"

### ISSUE THREAD

**Issue by kzhui125** [Dart-Code/Dart-Code#2348]
This is very useful. Then I can assign a keybinding for the command.

Now I have to type "dart main.dart" every time.

Like the python extension:

<img width="430" alt="1" src="https://user-images.githubusercontent.com/11925432/79050088-42edc100-7c5a-11ea-887a-ad505f993fe9.png">

<img width="348" alt="2" src="https://user-images.githubusercontent.com/11925432/79050094-484b0b80-7c5a-11ea-9878-3ce9725d4bf2.png">

**Comment by DanTup** [comment]
The preferred way to run scripts is using the Run menu in VS Code (pressing `F5` or `Cmd`+`F5`). This adds more functionality (such as full debugging and DevTools integration).

By default, this will use your current script if it looks like it's a valid Dart executable script (generally this means it's inside `bin` folder or `tool` folder).

If you want to *always* run your current script, you can create a launch configuration that contains:

```
   "program": "${file}"
```

Let me know if you have any issues with this, or it doesn't address your need. Thanks!

**Comment by kzhui125** [comment]
@DanTup 
I have to write make a launch.json every time I start a new main.dart in another project.
This is not convenient.

**Comment by DanTup** [comment]
@kzhui125 as long as your script is inside a `bin` or `tool` folder (see https://dart.dev/tools/pub/package-layout), you shouldn't need to a `launch.json` at all, you can just press `F5` / `Ctrl`+`F5` and it will run the current script.

Let me know if this doesn't work for you. Thanks!

**Comment by kzhui125** [comment]
@DanTup Thanks, I will put my scripts to bin folder.
