### ISSUE TITLE
Allow starting tests from the tests tree and "run test at cursor" while debugging app

### ISSUE THREAD

**Issue by HerrNiklasRaab** [Dart-Code/Dart-Code#2349]
If the app is running you can't start tests from this view (via Context Menu):

![image](https://user-images.githubusercontent.com/28401593/79050645-c643ee00-7c2b-11ea-812a-45289d250d53.png)

This might be related to this: https://github.com/Dart-Code/Dart-Code/issues/2312

**Comment by HerrNiklasRaab** [comment]
Also I can't start the app, while the tests are running.

**Comment by DanTup** [comment]
Good catch. I've updated the context menu so it's not disabled when in a debug session, and the same for the **Run/Debug tests at Cursor** commands.

> Also I can't start the app, while the tests are running.

I'm not sure what's causing this one - could you file a separate issue, including exactly how you're trying to run the app (which command/keybind/whatever) and what behaviour you see? Thanks!
