### ISSUE TITLE
Can't start the app with F5 while tests are running.

### ISSUE THREAD

**Issue by HerrNiklasRaab** [Dart-Code/Dart-Code#2352]
How to reproduce:

- Run "Dart: Run all Tests"
- Press F5 doesn't start the app

This are my keybindings:
![image](https://user-images.githubusercontent.com/28401593/79206112-25c61780-7e3f-11ea-9532-03d987ab0a3d.png)

Our launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Flutter Development",
            "request": "launch",
            "type": "dart",
            "program": "lib/main.dart",
            "args": ["--flavor", "development"]
        },
        {
            "name": "Flutter Staging",
            "request": "launch",
            "type": "dart",
            "program": "lib/main.dart",
            "args": [
                "--flavor",
                "staging"
            ]
        },
        {
            "name": "Flutter Production",
            "request": "launch",
            "type": "dart",
            "program": "lib/main.dart",
            "args": [
                "--flavor",
                "production"
            ]
        }
    ]
}
```

**Comment by DanTup** [comment]
In your key bindings screenshot, it shows that when you're already in debug mode (which sets the `inDebugMode` context shown in the **When** column), `F5` is bound to `Continue`, and it's only bound to `Start Debugging` when you are not already in debug mode.

If you want `F5` to launch a new debug session when you're already debugging, you'll need to bind it without the `!inDebugMode` context.

Hope this makes sense!

**Comment by HerrNiklasRaab** [comment]
Got it. Thanks!
