### ISSUE TITLE
Add the code lens to start the test also for the main function

### ISSUE THREAD

**Issue by HerrNiklasRaab** [Dart-Code/Dart-Code#2356]
At the moment I see everywhere in our code, that in every file there is a dummy group, just to be able to run all test of that file through those code lenses who appear. Would be awesome if vs code would detect if there are tests inside the main, and if so, show also a code lens at the main method.

``` dart
import 'package:fazua_domain/fazua_domain.dart';
import 'package:fazua_domain/src/entities/bike.dart';
import 'package:test/test.dart';

import '../test_serialization_util.dart';

// Here I should see "Run | Debug" code lens to start all test in the file.
void main() {
  setUp(() {});

  group('Bike', () {
    test('is bike serializable', () {
      isSerializable(BikeFactory().getBike(), (map) {
        return Bike.fromMap(map);
      });
    });
    test('if bikeName is not set, name should return mac adress', () {
      expect(Bike("mac").name, "mac");
    });

    test('if bikeName is set, name should return bikeName', () {
      expect(Bike("mac").copyWith(name: "Julian's Bike").name, "Julian's Bike");
    });
  });
}

```

**Comment by DanTup** [comment]
Great idea! I don't think this needs to be specific to tests, it could be handy for Flutter and Dart CLI apps too - especially with the same template support that tests have. This would allow you to quickly run different run configurations:

![Screenshot 2020-04-15 at 16 12 38](https://user-images.githubusercontent.com/1078012/79354161-f6450700-7f33-11ea-8f71-3e750be1965f.png)

![Screenshot 2020-04-15 at 16 12 44](https://user-images.githubusercontent.com/1078012/79354173-f9d88e00-7f33-11ea-8a8d-f0a8bfbd46eb.png)
