### ISSUE TITLE
Flutter debugger does not work

### ISSUE THREAD

**Issue by carlossilver1997** [Dart-Code/Dart-Code#2366]
When I try to start the debugger two alerts pop on, first says "Cannot launch without an active device", and second says "The Flutter Daemon has terminated."
I've tried a lot of solutions but anything works. I executed the flutter doctor but All works fine. I've read others issues but nothing similar has happend, then I use the capture logs. This is that captures:

Dart Code extension: 2.15.0
Flutter extension: 2.21.1
Platform: mac
Workspace type: Flutter
Multi-root?: false
Dart SDK:
    Loc: /usr/local/Cellar/dart/2.7.2/libexec
    Ver: 2.7.2
Flutter SDK:
    Loc: /Applications/flutter
    Ver: 1.0.0

Sat Apr 18 2020 [21:54:43 GMT-0500 (CDT)] Log file started
[21:54:53 GMT-0500 (CDT)] [FlutterDaemon] ==> [{"id":"2","method":"emulator.getEmulators"}]
[21:54:53 GMT-0500 (CDT)] [General] ERR: {"message":{"code":"EPIPE"}}

I tried to debbug with others ide's like intellj and android studio but there works fine, but I really like vscode

**Comment by Matt-Gleich** [comment]
Does it run fine in the command line with `flutter run`?

**Comment by carlossilver1997** [comment]
Yeah, it works fine, no problem with flutter run and flutter doctor there are no issues or warnings even like I said flutter debugger works fine in intellij or android studio, it seems the problem with be only in vscode.
I hope someone can help me because in the past worked fine but now it does not work.

**Comment by DanTup** [comment]
```
Flutter SDK:
Loc: /Applications/flutter
Ver: 1.0.0
```

This looks like a fairly old version of Flutter (from around Dec 2018) - can you try upgrading it to the latest version and see if you still have the problem?

**Comment by DanTup** [comment]
```
Dart SDK:
Loc: /usr/local/Cellar/dart/2.7.2/libexec
Ver: 2.7.2
```

Actually, I'm curious why it's showing Dart v2.7.2 with Flutter v1.0.0. These don't seem to match up. Can you post the output of running `flutter --version` too?

**Comment by carlossilver1997** [comment]
Now I updated the flutter version, i run de flutter doctor and all works fine, I run the application with flutter run and it works like in the past and the issue is the same, even I tried to use the flutter launch emulator and flutter create new project and they don't work but if I tried on terminal all the commands works fine and make what I need, but It is a problem use flutter without the debugger.

**Comment by DanTup** [comment]
Can you try running `flutter emulators -v` from the terminal and see if you have any errors with that?

**Comment by carlossilver1997** [comment]
![Captura de Pantalla 2020-04-20 a la(s) 12 39 26](https://user-images.githubusercontent.com/46036644/79782075-17c33b80-8304-11ea-84af-17f94b1f6e2d.png)

**Comment by carlossilver1997** [comment]
After upgrading flutter, the output for flutter --version is:
Flutter 1.12.13+hotfix.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f139b11009 (3 weeks ago) • 2020-03-30 13:57:30 -0700
Engine • revision af51afceb8
Tools • Dart 2.7.2

**Comment by DanTup** [comment]
Can you try in a terminal:

- Run `flutter -v daemon`
- Wait until you see the `daemon.connected` text
- Paste `[{"id":"2","method":"emulator.getEmulators"}]` and press `<enter>`

Paste the full output for the whole process here. Thanks!

**Comment by carlossilver1997** [comment]
carlosflores@MacBook-Pro-de-Carlos-2 ~ % flutter -v daemon

[  +21 ms] executing: [/Users/carlosflores/development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +126 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] f139b11009aeb8ed2a3a3aa8b0066e482709dde3
[        ] executing: [/Users/carlosflores/development/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +54 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.9-0-gf139b1100
[  +11 ms] executing: [/Users/carlosflores/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[   +1 ms] executing: [/Users/carlosflores/development/flutter/] git ls-remote --get-url origin
[   +9 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +90 ms] executing: [/Users/carlosflores/development/flutter/] git rev-parse --abbrev-ref HEAD
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +94 ms] executing: sw_vers -productName
[  +23 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +26 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.4
[        ] executing: sw_vers -buildVersion
[  +25 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19E287
[  +43 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +43 ms] Starting device daemon...
[{"event":"daemon.connected","params":{"version":"0.5.3","pid":63568}}]
[{"id":"2","method":"emulator.getEmulators"}]
[{"id":"2","result":[{"id":"Pixel_2_XL_API_28","name":"Pixel 2 XL API 28","category":"mobile","platformType":"android"},{"id":"apple_ios_simulator","name":"iOS Simulator","category":"mobile","platformType":"ios"}]}]

**Comment by DanTup** [comment]
@carlossilver1997 in your last log, it looks like Flutter is at `/Users/carlosflores/development/flutter/` however in the first post it says Flutter is at `/Applications/flutter`. Is it possible you have two differetnt copies of Flutter on your machine?

**Comment by carlossilver1997** [comment]
Yeah, I tried it but it does not work then I change de settings of dart plugin in vscode and after I restored them and now it works. Thanks for the support.

**Comment by DanTup** [comment]
Ok, I'm not sure what the issue was, but I'm glad it's solved. If you see it again do post back!
