### ISSUE TITLE
object type not colorized

### ISSUE THREAD

**Issue by kzhui125** [Dart-Code/Dart-Code#2368]
Hello, object type is not colorized in my theme. I expect `String` / `int` and others are colorized, other languages work fine.

dart:

<img width="305" alt="1_dart" src="https://user-images.githubusercontent.com/11925432/79726778-ea838700-831d-11ea-8a7c-b09523f5759e.png">

go:

<img width="291" alt="1_go" src="https://user-images.githubusercontent.com/11925432/79726796-f2432b80-831d-11ea-9f1a-f1e9a5bdac0f.png">

cs:

<img width="400" alt="1_cs" src="https://user-images.githubusercontent.com/11925432/79726807-f8390c80-831d-11ea-803a-689e488be5e0.png">

java:

<img width="454" alt="1_java" src="https://user-images.githubusercontent.com/11925432/79726828-ff601a80-831d-11ea-879e-c99c9d256734.png">

<details>
  <summary>here is my theme config</summary>
  <pre><code>
{
	"name": "Light+ Tweaked",
	"type": "light",
	"colors": {
		"breadcrumb.background": "#E1E4E8",
		"breadcrumb.foreground": "#646464",
		"breadcrumb.focusForeground": "#000000",
		"breadcrumb.activeSelectionForeground": "#000000",
		"gitDecoration.modifiedResourceForeground": "#0073c0",
		"gitDecoration.conflictingResourceForeground": "#ff0000",
		"gitDecoration.deletedResourceForeground": "#a00000",
		"gitDecoration.ignoredResourceForeground": "#00000044",
		"gitDecoration.untrackedResourceForeground": "#66a500",
		"focusBorder": "#fafbfc",
		"scrollbar.shadow": "#00000000",
		"editor.background": "#ffffff",
		"editor.foreground": "#24292e",
		"editorIndentGuide.background": "#a8a8a8",
		"editorIndentGuide.activeBackground": "#a8a8a8",
		"editorLineNumber.foreground": "#cccccc",
		"editorBracketMatch.background": "#f1f8ff",
		"editorBracketMatch.border": "#c8e1ff",
		"editorPane.background": "#e7eaeb",
		"tab.activeBackground": "#ffffff",
		"tab.inactiveBackground": "#fafbfc",
		"tab.border": "#e1e4e8",
		"tab.activeBorderTop": "#e36209",
		"tab.unfocusedActiveBorderTop": "#099ee388",
		"tab.activeForeground": "#000000",
		"tab.inactiveForeground": "#000000aa",
		"tab.unfocusedActiveForeground": "#000000ee",
		"tab.unfocusedInactiveForeground": "#00000099",
		"editorGroupHeader.tabsBackground": "#f2f4f5",
		"editorGroupHeader.tabsBorder": "#e1e4e8",
		"statusBar.foreground": "#444444",
		"statusBar.noFolderForeground": "#24292e",
		"statusBar.background": "#f2f4f5",
		"statusBarItem.prominentBackground": "#00000000",
		"statusBarItem.prominentHoverBackground": "#dddddd",
		"statusBar.noFolderBackground": "#fafbfc",
		"statusBar.border": "#e1e4e8",
		"activityBar.background": "#f2f4f5",
		"activityBar.foreground": "#8e979c",
		"activityBar.border": "#e1e4e8",
		"activityBarBadge.background": "#54a3ff",
		"sideBar.background": "#fafbfc",
		"sideBar.foreground": "#586069",
		"sideBar.border": "#e1e4e8",
		"sideBarTitle.foreground": "#24292e",
		"sideBarSectionHeader.background": "#f1f2f3",
		"sideBarSectionHeader.foreground": "#24292e",
		"titleBar.activeForeground": "#444444",
		"titleBar.activeBackground": "#f2f4f5",
		"titleBar.border": "#e1e4e8",
		"statusBar.debuggingBackground": "#fafbfc",
		"statusBar.debuggingForeground": "#24292e",
		"editorLineNumber.activeForeground": "#00000088",
		"peekViewEditor.matchHighlightBackground": "#00000011",
		"terminal.ansiBrightYellow": "#795e26",
	},
	"tokenColors": [
		{
			"scope": ["meta.embedded", "source.groovy.embedded"],
			"settings": {
				"foreground": "#000000ff"
			}
		},
		{
			"scope": "emphasis",
			"settings": {
				"fontStyle": "italic"
			}
		},
		{
			"scope": "strong",
			"settings": {
				"fontStyle": "bold"
			}
		},
		{
			"scope": "meta.diff.header",
			"settings": {
				"foreground": "#000080"
			}
		},
		{
			"scope": "comment",
			"settings": {
				"foreground": "#6a737d"
			}
		},
		{
			"scope": "constant.language",
			"settings": {
				"foreground": "#0000ff"
			}
		},
		{
			"scope": [
				"constant.numeric"
			],
			"settings": {
				"foreground": "#09885a"
			}
		},
		{
			"scope": "constant.regexp",
			"settings": {
				"foreground": "#811f3f"
			}
		},
		{
			"name": "css tags in selectors, xml tags",
			"scope": "entity.name.tag",
			"settings": {
				"foreground": "#800000"
			}
		},
		{
			"scope": "entity.name.selector",
			"settings": {
				"foreground": "#800000"
			}
		},
		{
			"scope": "entity.other.attribute-name",
			"settings": {
				"foreground": "#ff0000"
			}
		},
		{
			"scope": [
				"entity.other.attribute-name.class.css",
				"entity.other.attribute-name.class.mixin.css",
				"entity.other.attribute-name.id.css",
				"entity.other.attribute-name.parent-selector.css",
				"entity.other.attribute-name.pseudo-class.css",
				"entity.other.attribute-name.pseudo-element.css",
				"source.css.less entity.other.attribute-name.id",
				"entity.other.attribute-name.attribute.scss",
				"entity.other.attribute-name.scss"
			],
			"settings": {
				"foreground": "#800000"
			}
		},
		{
			"scope": "invalid",
			"settings": {
				"foreground": "#cd3131"
			}
		},
		{
			"scope": "markup.underline",
			"settings": {
				"fontStyle": "underline"
			}
		},
		{
			"scope": "markup.bold",
			"settings": {
				"fontStyle": "bold",
				"foreground": "#000080"
			}
		},
		{
			"scope": "markup.heading",
			"settings": {
				"fontStyle": "bold",
				"foreground": "#800000"
			}
		},
		{
			"scope": "markup.italic",
			"settings": {
				"fontStyle": "italic"
			}
		},
		{
			"scope": "markup.inserted",
			"settings": {
				"foreground": "#09885a"
			}
		},
		{
			"scope": "markup.deleted",
			"settings": {
				"foreground": "#f9e64f"
			}
		},
		{
			"scope": "markup.changed",
			"settings": {
				"foreground": "#0451a5"
			}
		},
		{
			"scope": [
				"punctuation.definition.quote.begin.markdown",
				"punctuation.definition.list.begin.markdown"
			],
			"settings": {
				"foreground": "#0451a5"
			}
		},
		{
			"scope": "markup.inline.raw",
			"settings": {
				"foreground": "#800000"
			}
		},
		{
			"name": "brackets of XML/HTML tags",
			"scope": "punctuation.definition.tag",
			"settings": {
				"foreground": "#800000"
			}
		},
		{
			"scope": "meta.preprocessor",
			"settings": {
				"foreground": "#0000ff"
			}
		},
		{
			"scope": "meta.preprocessor.string",
			"settings": {
				"foreground": "#f9e64f"
			}
		},
		{
			"scope": "meta.preprocessor.numeric",
			"settings": {
				"foreground": "#09885a"
			}
		},
		{
			"scope": "meta.structure.dictionary.key.python",
			"settings": {
				"foreground": "#0451a5"
			}
		},
		{
			"scope": "storage",
			"settings": {
				"foreground": "#0000ff"
			}
		},
		{
			"scope": "storage.type",
			"settings": {
				"foreground": "#0000ff"
			}
		},
		{
			"scope": "storage.modifier",
			"settings": {
				"foreground": "#0000ff"
			}
		},
		{
			"scope": "string",
			"settings": {
				"foreground": "#a44185"
			}
		},
		{
			"scope": [
				"string.comment.buffered.block.pug",
				"string.quoted.pug",
				"string.interpolated.pug",
				"string.unquoted.plain.in.yaml",
				"string.unquoted.plain.out.yaml",
				"string.unquoted.block.yaml",
				"string.quoted.single.yaml",
				"string.quoted.double.xml",
				"string.quoted.single.xml",
				"string.unquoted.cdata.xml",
				"string.quoted.double.html",
				"string.quoted.single.html",
				"string.unquoted.html",
				"string.quoted.single.handlebars",
				"string.quoted.double.handlebars"
			],
			"settings": {
				"foreground": "#0000ff"
			}
		},
		{
			"scope": "string.regexp",
			"settings": {
				"foreground": "#811f3f"
			}
		},
		{
			"name": "String interpolation",
			"scope": [
				"punctuation.definition.template-expression.begin",
				"punctuation.definition.template-expression.end",
				"punctuation.section.embedded"
			],
			"settings": {
				"foreground": "#0000ff"
			}
		},
		{
			"name": "Reset JavaScript string interpolation expression",
			"scope": [
				"meta.template.expression"
			],
			"settings": {
				"foreground": "#000000"
			}
		},
		{
			"scope": [
				"support.constant.property-value",
				"support.constant.font-name",
				"support.constant.media-type",
				"support.constant.media",
				"constant.other.color.rgb-value",
				"constant.other.rgb-value",
				"support.constant.color"
			],
			"settings": {
				"foreground": "#0451a5"
			}
		},
		{
			"scope": [
				"support.type.vendored.property-name",
				"support.type.property-name",
				"variable.css",
				"variable.scss",
				"variable.other.less",
				"source.coffee.embedded"
			],
			"settings": {
				"foreground": "#ff0000"
			}
		},
		{
			"scope": [
				"support.type.property-name.json"
			],
			"settings": {
				"foreground": "#0451a5"
			}
		},
		{
			"scope": "keyword",
			"settings": {
				"foreground": "#0000ff"
			}
		},
		{
			"scope": "keyword.control",
			"settings": {
				"foreground": "#0000ff"
			}
		},
		{
			"scope": "keyword.operator",
			"settings": {
				"foreground": "#000000"
			}
		},
		{
			"scope": [
				"keyword.operator.new",
				"keyword.operator.expression",
				"keyword.operator.cast",
				"keyword.operator.sizeof",
				"keyword.operator.instanceof",
				"keyword.operator.logical.python"
			],
			"settings": {
				"foreground": "#0000ff"
			}
		},
		{
			"scope": "keyword.other.unit",
			"settings": {
				"foreground": "#09885a"
			}
		},
		{
			"scope": [
				"punctuation.section.embedded.begin.php",
				"punctuation.section.embedded.end.php"
			],
			"settings": {
				"foreground": "#800000"
			}
		},
		{
			"scope": "support.function.git-rebase",
			"settings": {
				"foreground": "#0451a5"
			}
		},
		{
			"scope": "constant.sha.git-rebase",
			"settings": {
				"foreground": "#09885a"
			}
		},
		{
			"name": "coloring of the Java import and package identifiers",
			"scope": [
				"storage.modifier.import.java",
				"variable.language.wildcard.java",
				"storage.modifier.package.java"
			],
			"settings": {
				"foreground": "#000000"
			}
		},
		{
			"name": "this.self",
			"scope": "variable.language",
			"settings": {
				"foreground": "#0000ff"
			}
		}
	]
}
</code>  </pre>
</details>

**Comment by DanTup** [comment]
I'm not completely familiar with TextMate grammars (the one used here was taken from the Atom plugin), but when I run the **Developer: Inspect Editor Tokens and Scopes** command in VS Code and then click on a class name, I see a scope of `support.class.dart`. I think your theme should include `support.class`. This is included in the TextMate docs here:

https://www.sublimetext.com/docs/3/scope_naming.html#support

> While also used for base frameworks, many syntaxes apply these to scopes unrecognized classes and types, effectively scoping all user constructs.
> 
> `support.class`

Let me know if this doesn't work!

**Comment by kzhui125** [comment]
Thanks @DanTup 

Ather adding the "support" setting, it works now.

Although I think "String" and "int" should be "storage".

```json
{
    "scope": "support",
    "settings": {
        "foreground": "#0000ff"
    }
}
```

**Comment by DanTup** [comment]
There are plans to switch to server-generated syntax colouring (to allow types/variables to be highlighted accurately instead of based on the casing of the first character) so I the current grammar will probably be reviewed (and likely simplified somewhat) soon. Thanks!
