### ISSUE TITLE
Dart ext is not working on my VSC why ? pls help.

### ISSUE THREAD

**Issue by babu00** [Dart-Code/Dart-Code#2372]
Issue Type: <b>Bug</b>

i installed dart extencion and when i tried to open with comand palet dart proyect it doenst find dart and brings a error. also when i do manualy the terminal also brings a error bunch of red letter on the terminal. pls help.

Extension version: 3.9.1
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1800X Eight-Core Processor          (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by DanTup** [comment]
Please include a screenshot or copy/paste of the messages you're seeing. Thanks!
