### ISSUE TITLE
Is there a width setting in VSCode code format?

### ISSUE THREAD

**Issue by HeebeLee** [Dart-Code/Dart-Code#2382]
I find that no matter how big my screen is, the code will be in a very small width after formatting.

For example:
```
                ValueListenableBuilder(
                    valueListenable: this.buttonValueNotifier,
                    builder: (context, bool value, child) {
                      return VWButton.generic(
                          child: Text(S.of(context).registerAccountNextStepButtonText),
                          onPressed: value == false ? null : () {
                                  this.clickButton(context);
                                });
                    }),
```
After formatting:

```
                ValueListenableBuilder(
                    valueListenable: this.buttonValueNotifier,
                    builder: (context, bool value, child) {
                      return VWButton.generic(
                          child: Text(
                              S.of(context).registerAccountNextStepButtonText),
                          onPressed: value == false
                              ? null
                              : () {
                                  this.clickButton(context);
                                });
                    }),
```
It looks very messy. The style in front is what I want.

I hope we can have more settings about this, so it's more readable.

thx.

**Comment by DanTup** [comment]
There is a setting, `dart.lineLength` that lets you customise the wrap length. Eg.:

```
"dart.lineLength": 500,
```

This should do what you want, though you might find that this also "unwraps" some code you wanted wrapped. Unfortunately there isn't fine-grain control for this, [dart_style](https://github.com/dart-lang/dart_style) which is used for formatting is deliberately not very customisable.

There's an open issue about having a more flexible formatter at https://github.com/Dart-Code/Dart-Code/issues/914 that you can add 👍 's to, though it's not something that's planned short-term.

Let me know if you have any questions or can't get the above to work!
