### ISSUE TITLE
Error when click activate dart DevTools button.

### ISSUE THREAD

**Issue by YoneChen** [Dart-Code/Dart-Code#2383]
![image](https://user-images.githubusercontent.com/16669610/79951002-84783a80-84aa-11ea-8276-c9b6ff2e5f68.png)

![image](https://user-images.githubusercontent.com/16669610/79950895-5692f600-84aa-11ea-907b-1aac00fdef7f.png)

**Comment by DanTup** [comment]
If you're using Dart or Flutter from China, you may need to use some mirrors to access Pub/Flutter resources:

https://flutter.cn/#cn-mirror

In this case, it's setting `PUB_HOSTED_URL` that should fix this. You'll need to ensure the environment variable is visible to VS Code (if you're not sure how to do this, let me know what operating system you're using).
