### ISSUE TITLE
Proposal: long press continue button to skip through breakpoints

### ISSUE THREAD

**Issue by szotp** [Dart-Code/Dart-Code#2388]
When working with asyn code, and exception happens, the current handling is really annoying because breakpoint will be reached for every place where future is being awaited, example:

```dart
Future<void> nested(int counter) async {
  if (counter <= 0) throw 'lol';

  await nested(counter - 1);
}

// enable exception breakpoints and run this
void main() {
  nested(100);
  // you will have to disable breakpoints or click continue 100 times to reach this
}
```

It may be a bug, but there is a simple feature that could improve this: if I want to skip through all breakpoints for certain time period, I would like to long press the continue button, which would disable all breakpoints until long press ends.

This could be also useful in other situations, for example when you are waiting for certain situation to happen and you want to skip through few first pauses.

Let me know if this is sensible, I could try implementing it myself.

**Comment by DanTup** [comment]
Unfortunately it's not possible for extensions to handle things like long-press on buttons in VS Code. VS Code simply sends the debug adapter a "Continue" request when you click the button.

I'm not sure the suggested fix would work great anyway - how would you know when to let go of the button? It seems like timing would be important.

It does feel a little weird to me for the debugger to break 100 times here though when using break-on-unhandled exception. It feels a little similar to https://github.com/dart-lang/sdk/issues/37645, but that was based on `finally` statements. I wonder if the same sort of change would be appropriate here? (@zichangg what do you think?)

**Comment by zichangg** [comment]
What fits your description most is a "conditional breakpoint". You can evaluate the `counter` before hitting the breakpoint.
I thought we had some discussions on that a year ago. Considering we have `evaluate` RPC available, it should be feasible to implement a "conditional breakpoint". I haven't looked this area for a while but I don't think this is on our current plan.

**Comment by DanTup** [comment]
We do already support conditional breakpoints (by evaluating the expression and resuming based on its result), however the issue here is breaking on exceptions, not breakpoints. The debugger pauses on every trip to the `await` as the exception propagates back up the 100 stack frames.

**Comment by zichangg** [comment]
> It feels a little similar to dart-lang/sdk#37645, but that was based on finally statements. I wonder if the same sort of change would be appropriate here? 

This is different. In that case, compilation adds additional "throw"s but this case "throw" is user-written. VM should pause on the exception.


The problem for this issue is how users can tell VM/Debugger how much exceptions or how long they want to skip. What if other exceptions pop in the middle of skipping?

@DanTup I think this sounds like a pretty general questions for all debuggers. Do you know how others handle this problem?

**Comment by DanTup** [comment]
@zichangg I don't know how it's implemented, but in nodejs the debugger only breaks once for what I think is equivalent code:

```
async function nested(counter) {
	if (counter <= 0)
		throw new Error("lol");

	await nested(counter - 1);
}

async function main() {
	await nested(100);
}

main();
```

**Comment by zichangg** [comment]
We can do something like "unpause if exceptions have the same stack trace as the previous exception". Probably a flag is needed to control?
@DanTup What do you think?

**Comment by DanTup** [comment]
Do you mean as another action from the editor to unpause, or a flag to the VM that tells it not to break in the first place if the stack is the same as the last one? If the latter, that sounds sensible to me, though it's unclear to me what the value is in the current behaviour - would this not be a better default?

**Comment by szotp** [comment]
Another alternative would be option to ignore certain kind of exceptions, for example I don't care at all about MissingPluginException thrown by OptionalMethodChannel.

**Comment by DanTup** [comment]
@szotp that seems like a different request. There are already checkboxes to choose between breaking on all exceptions or just unhandled exceptions. Generally I wouldn't recommend breaking on all exceptions unless you're specifically trying to track something down - however in Flutter, exceptions caught by the framework are treated as unhandled. I've opened an issue about that at https://github.com/flutter/flutter/issues/17007, since I think that makes it much more difficult to debug code in Flutter.

**Comment by DanTup** [comment]
@zichangg not sure if you saw [my comment above](https://github.com/Dart-Code/Dart-Code/issues/2388#issuecomment-626604908).

Though now I'm thinking if it was just skipped if the exception had the same stack, exceptions in code that runs in a loop might be missed? Probably only *the exact same exception instances* would want to be skipped?

**Comment by szotp** [comment]
I have found a decent alternative: instead of using exception breakpoints, use "debugger" function from developer package. Example:

```dart 
void dlogError(dynamic message, [StackTrace st, dynamic sender]) {
  if (!kDebugMode) {
    return;
  }

  String stFormatted = '';
  if (st != null) {
    var lines = st.toString().split('\n');
    if (lines.length > 5) {
      lines = lines.sublist(0, 5);
      lines.add('...');
    }

    stFormatted = lines.join('\n');
  }

  dlog('❌❌❌❌ $message $stFormatted');

  if (LogSettings.breakOnError ||
      message is Error && LogSettings.breakOnProgrammingError) {
    d.debugger();
  }
}

```

So when interesting error happnes IDE will pause and I can click on stack trace URL to jump where I want.

**Comment by DanTup** [comment]
Interesting idea - by handling it in code you can control the conditions precisely as you'd like. It does require you to modify code to add additional positions though.

I wonder if you could call `dlogError` from a [logpoint](https://code.visualstudio.com/blogs/2018/07/12/introducing-logpoints-and-auto-attach) which would allow calling it without modifying the code? 🤔

**Comment by szotp** [comment]
I don't mind writing dlogError in all places where error happens, I may some filtering in my LogSettings and modify if as needed in my debugging entry file (which is gitignored).

Although this logpoint feature seems useful for other situations, thanks for the link.

**Comment by DanTup** [comment]
Sounds good.

I'll close this, as I don't think there's a way to do the original request (and I don't think it's the best way to address this). There are some other open issues in this area (for ex. https://github.com/flutter/flutter/issues/17007) that I think could improve the behaviour around exceptions somewhat.

Of course, if you still find friction and think there are other things to look at, do shout!
