### ISSUE TITLE
Add to watch and evaluate in debug console, doesn't work with multiline selection

### ISSUE THREAD

**Issue by HerrNiklasRaab** [Dart-Code/Dart-Code#2391]
If I select multiple lines to evaluate in console or for adding it to the watch, it only evaluates the first line: https://imgur.com/5M7WzJH

Edit: Just tried in Android Studio, there it works.

**Comment by DanTup** [comment]
When I evaluate in the debug console, it seems to work ok:

![Screenshot 2020-04-23 at 16 52 11](https://user-images.githubusercontent.com/1078012/80120467-f623b780-8582-11ea-9ddb-1c4752d36f67.png)

For the watch window, the label only shows the first line, but if I double-click in it, it does expand and has the full amount (and the value shown when expanding it is also correct for all of the lines).

Are you able to reduce your code to a standalone script that still repros that I can run here? Thanks!

**Comment by HerrNiklasRaab** [comment]
I reinstalled macOS, now it works again. Don't know what caused this.

**Comment by DanTup** [comment]
Weird - if you see it again and can capture a log, let me know!

**Comment by HerrNiklasRaab** [comment]
Hey @DanTup,

I can reproduce again. The logs are attaached, I did evaluate two expression in the debug console. One with `test.stream` and one with:

``` dart
test.stream
      .skipWhile((int i) => i < 2)
```

The interesting thing was, that I was only able to reproduce in a flutter project or a library that had flutter in it's pubspec.yaml. Did you tried your code in a pure dart library? So if you try to reproduce, try a flutter project.

Create a new **Flutter** project and add this to the main:

``` dart
import 'dart:async';

import 'package:flutter/material.dart';

void main() {
  StreamController<int> test = StreamController<int>();
  test.add(1);
  test.add(2);
  test.add(3);
  test.add(4);
  var test2 = test.stream
      .skipWhile((int i) => i < 2)
      .skipWhile((int i) => i > 3)
      .map((int i) => i + 1);

  runApp(MyApp());
}
```

These are the logs: 
[Dart-Code-Log-2020-03-06 00-17-46.txt.zip](https://github.com/Dart-Code/Dart-Code/files/4531826/Dart-Code-Log-2020-03-06.00-17-46.txt.zip)

**Comment by DanTup** [comment]
@HerrNiklasRaab Thanks! You were right, I only tested with Dart. Can easily repro in Flutter by just pasting a multiline expression into the debug console.

I believe this is a Flutter issue - expression evaluation is a little different for Flutter, as the expression has to be compiled and sent over to the device for evaluation - I suspect the issue is in the Flutter code that handles this.

I've opened https://github.com/flutter/flutter/issues/55731 about this, and also https://github.com/dart-lang/sdk/issues/41671 because I noticed trailing semicolons cause issues too. You can subscribe to them for updates.

Thanks!

**Comment by DanTup** [comment]
Closing this as it seems entirely a Flutter issue and once fixed in https://github.com/flutter/flutter/issues/55731 it'll work here in VS Code without any further changes. Subscribe there for updates - thanks!

**Comment by DanTup** [comment]
This was fixed in https://github.com/flutter/flutter/pull/190722 and will be included in a future Flutter SDK.
