### ISSUE TITLE
Unable search key worlds from Debug console control panel

### ISSUE THREAD

**Issue by LongXiangGuo** [Dart-Code/Dart-Code#2394]
When i use flutter extension debug in `viscode`, could not search key words from the `Debug console` control panel,when i am try android studio it works well anyone have idea fix it?

**Comment by DanTup** [comment]
There is a search in the Debug Console, though it's not very obvious. If you press `Cmd`+`F5` (or `Ctrl`+`F5` if Windows/Linux) and then start typing, it will search and show the search term on the right side:

<img width="792" alt="Screenshot 2020-05-04 at 17 43 54" src="https://user-images.githubusercontent.com/1078012/80990803-e469cc00-8e2e-11ea-89f4-047c7654c836.png">

This feature comes from VS Code and can't be enhanced by extensions, so if you think it can be improved it's worth raising at https://github.com/microsoft/vscode. Thanks!
