### ISSUE TITLE
"The Dart Analyzer could not be started" in VSCode.

### ISSUE THREAD

**Issue by ashish-chougule** [Dart-Code/Dart-Code#2395]
When i am trying to create new flutter project, I get this warning message & the whole project-creation is stuck. 

Kindly help me reslove this. 

![image](https://user-images.githubusercontent.com/4499373/80210449-6b5dbe00-8651-11ea-9323-143ba952cff3.png)
I looked at the logs there are no errors or issues i could find but still i get these warrning messages. 
I am unable to create a Flutter Project.
Log File : [log-db3a.txt](https://github.com/Dart-Code/Dart-Code/files/4528737/log-db3a.txt)

OS : Windows 
Flutter SDK : flutter_windows_v1.12.13+hotfix.9-stable.zip
VS Code : 1.44.2

VSCode Plugin Versions 
Flutter : 3.9.1
Dart : 3.9.1

**Comment by hillpates123** [comment]
same here ..

**Comment by ashish-chougule** [comment]
### Run all the Development tools as admin! - this worked for me. 
I have switched to Android Studio(IDE) as we need it for the emulator.  This also had similar problems with creating projects. - Same fix! - Run as administrator. 

Flutter main website : Suggesting a [online course](https://www.appbrewery.co/p/intro-to-flutter?utm_source=google&utm_medium=website%20banner&utm_campaign=app_brewery) : Its very good & has helped me understand Flutter concepts. 

Happy Coding! :

**Comment by DanTup** [comment]
> Run all the Development tools as admin! - this worked for me.

This is not the best solution. If it works, it may be that the permissions on the Flutter SDK are not set correctly (for example if you moved it from Program Files, it might still have some permissions set).

Please try running VS Code as normal (**not** as Admin), then go to the VS Code terminal and try running `flutter doctor` and post back what happens here. Thanks!

**Comment by ashish-chougule** [comment]
> > Run all the Development tools as admin! - this worked for me.
> 
> This is not the best solution. If it works, it may be that the permissions on the Flutter SDK are not set correctly (for example if you moved it from Program Files, it might still have some permissions set).
> 
> Please try running VS Code as normal (**not** as Admin), then go to the VS Code terminal and try running `flutter doctor` and post back what happens here. Thanks!

Thanks for responding. 
I am unable to launch the terminal on the VSCode as normal user. The terminal is only working for me when i launch VSCode as admin. This is strange as earlier versions(i recently upgraded my vscode) it worked fine without any issues i was able to launch a terminal without admin.

So this seems to be the root problem. I tried uninstalling my VSCode & cleaned all the settings & extension folders but this isn't working for me.

**Comment by DanTup** [comment]
> I am unable to launch the terminal on the VSCode as normal user.

It's hard to debug without more info on exactly what this means - do you see an error message?

Do you have anything in your terminal startup scripts that may require admin permissions? If so, that may be the cause. If not, it may be worth raising an issue in the vscode repo.
