### ISSUE TITLE
The Dart Analyzer could not be started in VS Code

### ISSUE THREAD

**Issue by Alloco225** [Dart-Code/Dart-Code#2396]

**Comment by DanTup** [comment]
(from #1829):

> > When I try delete the flutter/bin/cache folder I get that win10 popup saying I need authorisation from admin to delete it, and I can't get around it.

It sounds like the permissions on this folder might not be set properly. Did you move the folder from somewhere like Program Files previously? Try checking the permissions on the Flutter folder (right-click -> properties -> security) and perhaps reset them on all child files/folders.

**Comment by Alloco225** [comment]
The folder is at C:/src/flutter, I changed the permissions and checked all the "authorize" boxes but the error keeps poping up

**Comment by Alloco225** [comment]
The only way that seems to work is deleting the whole flutter folder in safe mode and reinstalling the whole thing. That's what I did to temporarily solve it the first time, but it's not a viable solution as the problem will come back after I shut my computer..

**Comment by Alloco225** [comment]
What worries me the most is that the flutter commands don't work.

**Comment by Alloco225** [comment]
**Update**

Aight, so I went into safe mode and was able to delete the flutter/bin/cache. And flutter doctor just downloaded the dart sdk n I ran flutter upgrade --force. 

**Annd everything works for now.**

But I'm worried the problem will come back when I restart my pc.
Should I reboot to see if it the problem is definitely solved ?

**Comment by DanTup** [comment]
> and checked all the "authorize" boxes but the error keeps poping up

If you see these again, can you post a screenshot?
