### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by rajesh703** [Dart-Code/Dart-Code#2397]
- Issue Type: `Bug`
- Extension Name: `dart-code`
- Extension Version: `3.9.1`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.44.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by rajesh703** [comment]
i need solution

**Comment by DanTup** [comment]
Can you provide more information about the problem you're having? In your message it says:

> ⚠️ We have written the needed data into your clipboard. Please paste! ⚠️

But it doesn't seem like this information was included.

Thanks!
