### ISSUE TITLE
Add option for completeFunctionCalls

### ISSUE THREAD

**Issue by HerrNiklasRaab** [Dart-Code/Dart-Code#2399]
For Typescript and Javascript, there exists the setting `typescript.suggest.completeFunctionCalls` and `javascript.suggest.completeFunctionCalls`. 

It seems there is already partial support for optional parameters, but not for required once (And they don't let you tap through).

It's difficult for me to estimate what's possible right now, but this would be my ideal world scenario:

Having a function with the following signature: `int test(Function(int i, String s) test)`
Now calling `test(` autocomplete opens with those options:
- `(i, s) =>`
- `(i, s) {  }`
- `(i, s) { return ; }`
- `create method in class "int functionName(int i, String s) {  }"`
- `create method in class "int functionName(int i, String s) { return ; }"`

Also you should be able to tap through the parameter:
- `($pos1, $pos1) => $end`
- `($pos1, $pos2) { $end }`
- `($pos1, $pos2) { return $end; }`
- `create method in class "int $pos1(int $pos2, String $pos3) { $end }"`
- `create method in class "int $pos1(int $pos2, String $pos3) { return $end; }"`

Any plans to support something like this? Does this need to come from the server?

**Comment by DanTup** [comment]
Yeah, this would need to come from the server (it's possible we could do some of it in the client, but the goal is to move to LSP which will push all completion back into the server and that work would be lost and need doing in the server anyway). There has been some work similar to this at https://github.com/dart-lang/sdk/issues/40013#issuecomment-574422203/https://github.com/dart-lang/sdk/issues/36112 but it doesn't cover as much as this. I don't know how easy it'd be though.

**Comment by HerrNiklasRaab** [comment]
Ok, should I create an Issue in https://github.com/dart-lang/sdk ? Or do you think if you create this Issue it adds more voice.

Is there anything we need to do in dart-code, once this feature is added to the server? Otherwise we can close this issue.

**Comment by DanTup** [comment]
I generally encourage others to file the issues, that way if things aren't clear or someone has questions, it's easier for them to be discussed without me seeming like a proxy.

I don't *think* we'd need to do anything in Dart-Code, but it depends a little on whether the request fits entirely within the existing API. I'd probably suggest closing this one, and if it's implemented in the SDK and it doesn't show up in VS Code, we can re-open and look into it (though most likely VS Code will have moved over to LSP so if it didn't work I'd likely need to fix that up in the SDK).

Thanks!

**Comment by HerrNiklasRaab** [comment]
Issue created: https://github.com/dart-lang/sdk/issues/43571

**Comment by DanTup** [comment]
Thanks - I'll close this one in favour of that. I don't know if the completion handler currently has enough information to do this, but I'll have a dig around when I can. Thanks!
