### ISSUE TITLE
Selecting an item from the auto complete menu comes with a default selection prevents showing the auto complete menu again till pressing esc

### ISSUE THREAD

**Issue by AlaaEldeenYsr** [Dart-Code/Dart-Code#2406]
When i select an item from the auto complete menu, The code result is set with a default selection that prevents showing the auto complete menu again till pressing esc.
In the first gif i started typing directly after selecting the padding and the auto complete menu doesn't get shown.
In the second gif after selecting the padding i pressed esc to remove the default selection so the auto complete menu get shown when start typing
It whould be great if there is an option to remove that default selection that prevents showing the auto complete menu.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/52201392/80555768-8756bc00-89d1-11ea-8eec-98af2b7ee987.gif)

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/52201392/80555912-14017a00-89d2-11ea-9b6a-64121faf8559.gif)

**Comment by DanTup** [comment]
This is the default behaviour in VS Code when completions have placeholders that you can tab to. I would recommend setting `"editor.suggest.snippetsPreventQuickSuggestions": false,` in your user settings (there are other [recommended settings](https://dartcode.org/docs/recommended-settings/) you may want to review - you can use the **Dart: Use Recommended Settings** command to easily apply them all).

Please let me know if this doesn't solve your issue!

**Comment by AlaaEldeenYsr** [comment]
Thank you, I think your suggestion did well.
@DanTup

**Comment by DanTup** [comment]
Glad to hear!
