### ISSUE TITLE
Launching with Web Server device hangs on "Syncing to Web Server..."

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#2407]

**Comment by DanTup** [comment]
Seems like the `app.webLaunchUrl` event is not arriving from Flutter:

```
    _logger.printStatus('Sending webLaunchUrl event via ${_logger.runtimeType}!');
    _logger.sendEvent('app.webLaunchUrl', <String, dynamic>{'url': url, 'launched': false});
    _logger.printStatus('Done sending webLaunchUrl event!');
```

The middle event never arrives, and the logged `runtimeType` of the logger is `StdOutLogger` which doesn't implement `sendEvent`.

**Comment by DanTup** [comment]
I think this might be related to https://github.com/flutter/flutter/commit/f2761b6b041fc78a0de2fd8831b14847e65477eb - it may be capturing the log before it's overriden?

https://github.com/flutter/flutter/commit/f2761b6b041fc78a0de2fd8831b14847e65477eb#diff-098fe4c01d0b201571cc05cf4d9e2f36R93

(cc @jonahwilliams)

**Comment by DanTup** [comment]
Yep, the daemon code runs some code in a context that replaces the logger:

https://github.com/flutter/flutter/blob/4605b51a7ea78d161043278aafebc3c17933c7b5/packages/flutter_tools/lib/src/commands/daemon.dart#L1022-L1031

However the `WebDevices()` class is constructed before this, and captures the original logger.

@jonahwilliams I can't think of a way to make this work (without either making the device reach out to the global logger again, or trying to rework this so the AppRunLogger is constructed and set up before the WebDevices() constructors run).

**Comment by jonahwilliams** [comment]
Interesting! I did not consider logger replacement before. I think If I make the WebDevices constructed lazily it should always resolve to the latest logger.

**Comment by DanTup** [comment]
> I think If I make the WebDevices constructed lazily it should always resolve to the latest logger

Yeah, that should work (as long as nothing outside of `WebDevices` writes logs that expect to go via the Daemon logger - though I didn't notice anything while investigating this).

Let me know if/when you want me to test a fix. Thanks!

**Comment by DanTup** [comment]
Fixed by https://github.com/flutter/flutter/issues/59463.
