### ISSUE TITLE
Wrap with Column/Row which use children not support

### ISSUE THREAD

**Issue by liudonghua123** [Dart-Code/Dart-Code#2409]
I use vscode to develop flutter apps a lot. The `quick fix` is awesome. In many usage scenario, I frequently use wrap with widgets/Container/Padding. What's missing here is I can't wrap with Column/Row/Stack which have children instead of child.

![image](https://user-images.githubusercontent.com/2276718/80667734-8b1e3780-8ad2-11ea-8f60-7594dc984bc7.png)

**Comment by DanTup** [comment]
@liudonghua123 In your screenshot it shows "Wrap with Column" and "Wrap with Row" so I'm a bit confused about the request. Where do you want to use these that they don't currently show up?

**Comment by liudonghua123** [comment]
@DanTup Hi, I could not remember where they don't show up, However I do have a slight impression about this, I will pay more attention to it, and reopen this issue if I can reproduce.
Thanks!

**Comment by DanTup** [comment]
@liudonghua123 ok cool. It would be best to raise this at https://github.com/dart-lang/sdk when you find it. Those quick-fixes are all coming from the analysis server (in the SDK) so where they appear is determined by that. Thanks!
