### ISSUE TITLE
generic types fields can not be visible by the editor

### ISSUE THREAD

**Issue by mo-ah-dawood** [Dart-Code/Dart-Code#2412]
```dart

class A {
  int id;
}

class B<T extends A> {
  void printItem(T item) {
    print(item.id);//The id field is not auto visible for vs code editor
  }
}
```

**Comment by DanTup** [comment]
Thanks for the report! The completion comes from the analyzer in the SDK so this needs ficing there. There's an existing open issue for it in the SDK repo you can subscribe to here: https://github.com/dart-lang/sdk/issues/24255
