### ISSUE TITLE
Show test duration in debug console or test panel 

### ISSUE THREAD

**Issue by hashemp206** [Dart-Code/Dart-Code#2417]
When I run tests, I don't see the duration for each test case never in debug console and nor in test panel.
is there any plan to add duration for tests?
<img width="1079" alt="Screen Shot 2020-05-04 at 3 36 02 PM" src="https://user-images.githubusercontent.com/3206748/80960023-402b5980-8e1d-11ea-89b6-a6f56c40ca9c.png">

**Comment by DanTup** [comment]
Times will appear on the end of the nodes from the next version. Thanks for the suggestion!

![Screenshot 2020-05-13 at 16 51 12](https://user-images.githubusercontent.com/1078012/81836241-1c61c500-953b-11ea-98fa-241cf18f4394.png)
