### ISSUE TITLE
Check whether type hiearchy could be better implemented with new Code explorer API

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#243]
It's possible #133 could be done using the new tree API now:

https://github.com/Microsoft/vscode/issues/12163#issuecomment-256813193
https://github.com/Microsoft/vscode-extension-samples/tree/master/tree-explorer-sample

**Comment by DanTup** [comment]
There have been many improvements to the tree in the last few releases - I suggest we leave this until all the changes are live as we might be able to do this better (currently we've adding more and more trees to the explorer and it's becoming a bit busy).

**Comment by DanTup** [comment]
Having tried to implement a tree for Outline, I think we'd be much better waiting for VS Code to gain this functionality natively. Custom trees lack a lot of the functionality of the built-in Symbols tree, so it's hard to get a good/consistent experience if for a tree showing Symbols.

**Comment by chalin** [comment]
Any update on this? Are we likely to get a type hierarchy view any time soon?

**Comment by DanTup** [comment]
Not really - there's no great way for us to implement it without cooperation for VS Code. There's an open issue at https://github.com/microsoft/vscode/issues/15533 requesting it. Recently they added a call hiearachy so maybe it'll come (do add a 👍 to that issue!)

**Comment by chalin** [comment]
Thanks for the update. Done: 👍 added!
