### ISSUE TITLE
setPriorityFiles may be called before setAnalysisRoots and does not correctly apply

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#2438]
While investigating #2231 I noticed that the open file was not in the priority list, which was resulting in results not being cached, and lots of requests triggering a lot of additional analysis.

This seems to be because at startup, we send priority files immediately, without waiting for `setAnalysisRoots` to complete. The server code copies priority files to the drivers in setAnalysisRoots:

https://github.com/dart-lang/sdk/blob/c1edd26d974b38362f3c3c3d9699981096d5df4f/pkg/analysis_server/lib/src/analysis_server.dart#L465

But if they've not been created by that time, they won't be set.

@bwilkerson I'll fix the orders of these here, but I wonder if it's worth explicitly setting analysis files on the driver when it's created/added to the map on the server?

https://github.com/dart-lang/sdk/blob/c1edd26d974b38362f3c3c3d9699981096d5df4f/pkg/analysis_server/lib/src/analysis_server.dart#L780

I'm happy to send a CL if you think it's a reasonable change.

**Comment by bwilkerson** [comment]
> I'll fix the orders of these here, but I wonder if it's worth explicitly setting analysis files on the driver when it's created/added to the map on the server?

Yes. The documentation for the protocol implies (though it should be made explicit) that if a file is made a priority file before it is being analyzed, and is later included in an analysis root, that it will still be a priority file at that time. You shouldn't need to change the order on your side.

A CL to fix the bug would be very welcome.

**Comment by DanTup** [comment]
Great, I've sent https://dart-review.googlesource.com/c/sdk/+/147183/.

I was going to still fix here (since it'll be a while before that SDK change is in a stable Flutter release, for ex.), however I think the impact is probably short-lived since as soon as the user changes the visible files in VS Code (switching between them or opening a new file), it would send priority files again anyway. This would only be an issue for the specific files opened at startup until the first change.
