### ISSUE TITLE
vs code keeps 'forgetting' my packages 

### ISSUE THREAD

**Issue by imepnja** [Dart-Code/Dart-Code#2440]
When I create a new Project with `flutter create MyApp `, I get an error on the first import line (`import 'package:flutter/material.dart';`) then i run `flutter packages get` and it resolves the Issue.

But after some time it kind of 'forgets' my packages and I have to run `flutter packages get` again.
The error resolves automatically when i do a hot restart but in the mean time i can't really write code because the error messages keep getting in my way.

Is there some kind of way to automatically run `flutter packages get` ?

And is there some way to globally load `import 'package:flutter/material.dart';`  that i don't have to run `flutter packages get` immediately when I create a new project?

**Comment by DanTup** [comment]
> When I create a new Project with `flutter create MyApp` , I get an error on the first import line (`import 'package:flutter/material.dart';`) then i run `flutter packages get` and it resolves the Issue.

When you run `flutter create MyApp`, it should run `flutter packages get` for you:

```
danny@Dannys-MBP /tmp % flutter create foo
Creating project foo...
  foo/ios/Runner.xcworkspace/contents.xcworkspacedata (created)
  // SNIP ...
  foo/.idea/workspace.xml (created)
Running "flutter pub get" in foo...                                 1.1s
Wrote 102 files.
```

Is this not the behaviour you see? FWIW, if you're inside VS Code it may be better to run the **Flutter: New Project** command instead.

> The error resolves automatically when i do a hot restart

Triggering a hot restart shouldn't really affect analysis, as these are handled by two different processes.

Are you able to reliably reproduce this? Could you enable the [analysis server log](https://dartcode.org/docs/logging/#analyzer) with the `dart.analyzerLogFile` setting and grab a copy of this when it happens?

**Comment by imepnja** [comment]
Yes when I create a project i get exactly that output, but when i open it I immediately get those errors
After some time I noticed that its more random. It forgets my packages after a short amount of time.
But it really gets annoying when i use more files because i forgets it for all my files in different time intervals. 

For example this is what happened last: So I modified my `home.dart`, it forgot my packages, then i used `flutter packages get` to remove the error.
After that I edited some other file. And in the mean time I got an error in my `main.dart` again so I had to run `flutter packages get` for a file where nothing was even remotely changed.

**Comment by imepnja** [comment]
I found the solution!
I didn't open just the project folder. I opened the folder above. This apparently confuses vscode. So i just opened the folder itself and now everything runs smoothly! :)

**Comment by DanTup** [comment]
How far from the folder you opened is your Flutter project? When you open a project, we can through the top 3 levels of the folder to try to detect whether your project is a Flutter or Dart project. If it's further than that, then it could cause us to use the Dart SDK (instead of Flutter). However if your Flutter project is within 3 levels of the folder you open, I would expect it to be found.
