### ISSUE TITLE
Duplicates in autocompletion (classes / methods and functions)

### ISSUE THREAD

**Issue by tanguyMichardiere** [Dart-Code/Dart-Code#2441]
VSCode suggests every possible widget class twice, one with parentheses (purple box, "methods and functions" according to https://code.visualstudio.com/docs/editor/intellisense) and one without (orange symbol, "classes"). I have found that if I write "new" before it doesn't suggest classes anymore, but I don't really want to write "new" everywhere just for that reason.
Is there any way to prevent it from suggesting "classes" in this case? I didn't find a way to disable classes suggestions entirely but that wouldn't be a solution either because they are useful after "extends".
![Screenshot_2020-05-09_18-51-28](https://user-images.githubusercontent.com/54041658/81479947-cb925980-9226-11ea-90bb-33717b996f36.png)
Thanks

**Comment by DanTup** [comment]
I don't believe there's any way to prevent classes showing up here unless you type `new`. It's valid to have classes here as it's not guaranteed that you're calling constructors. It would be equally valid to access static members from classes like `MyFooWidget.fromSomeThing(foo)` or some static/constant fields on a class.

Hiding them entirely would affect places other than just `extends`, as class names are also valid in many other places, for example:

```dart
FooWidget foo = FooWidget();
foo.runtimeType == FooWidget
foo is FooWidget
FooWidget.statcMethod()
```

**Comment by DanTup** [comment]
I believe this is working as intended (see descriptions above), but let me know if this causes significant friction (with an example) and I'll think more about the options (for example, if you have `insertArgumentPlaceholders: false` then I think they will always complete to the same, in which case merging them together may be more reasonable).

Thanks!
