### ISSUE TITLE
[VS Code] Default parameters missing

### ISSUE THREAD

**Issue by miguelpruivo** [Dart-Code/Dart-Code#2442]
Looks like we lost default parameters with latest update. Is this intended?

Thanks!

**Comment by DanTup** [comment]
@miguelpruivo I'm not sure what this refers to - can you provide some more info or a screenshot describing what's wrong?

**Comment by miguelpruivo** [comment]
Sure @DanTup.

Right now, when you hover on a method, it will show it's params, like so:
<img width="411" alt="Captura de ecrã 2020-05-11, às 13 59 55" src="https://user-images.githubusercontent.com/27860743/81564549-d0265180-938f-11ea-8749-33566fb76210.png">

Where previously, it would also display the default parameters (when applicable). For example, `SizedBox.expand()` has default parameters for both `width` and `height`, but now I can only see them by inspecting the source:
<img width="379" alt="Captura de ecrã 2020-05-11, às 14 00 10" src="https://user-images.githubusercontent.com/27860743/81564665-0237b380-9390-11ea-9e96-9cbdad1bbbf8.png">

**Comment by DanTup** [comment]
This seems like a change in the latest SDK, I've moved it over to https://github.com/dart-lang/sdk/issues/41844. Thanks!

**Comment by DanTup** [comment]
Fixed this in the SDK, so should be back from the next version. Thanks for noticing!
