### ISSUE TITLE
Dart SDK not recognized on raspberry pi

### ISSUE THREAD

**Issue by igotyou** [Dart-Code/Dart-Code#2445]
I've installed a dart sdk(armv7 architecture) on my raspberry pi 4b, and i am using vs code remote explorer to connect to the raspberry pi to develop some dart files. I have installed the dart extension on the vs code server running on the linux server, but the extension does not want to recognize the dart sdk. I have attached the full log bellow, and have included the parts i believe are relevant. The dart-sdk is installed in /usr/lib/dart

[log.txt](https://github.com/Dart-Code/Dart-Code/files/4609561/log.txt)

```
[14:28:40] [General] [Info] Searching for dart
[14:28:40] [General] [Info]     Looking for dart in:
[14:28:40] [General] [Info]         /usr/lib/dart/bin
[14:28:40] [General] [Info]     Found at:
[14:28:40] [General] [Info]         /usr/lib/dart/bin
[14:28:40] [General] [Info]     Candidate paths to be post-filtered:
[14:28:40] [General] [Info]         /usr/lib/dart
[14:28:40] [General] [Info]     Returning SDK path undefined for dart
```

**Comment by DanTup** [comment]
Are you able to run `find /usr/lib/dart/bin` on the Pi and post the results back here?

**Comment by igotyou** [comment]
Here you go 

[find_output.txt](https://github.com/Dart-Code/Dart-Code/files/4610287/find_output.txt)

**Comment by DanTup** [comment]
Your SDK seems to be missing the file `bin/snapshots/analysis_server.dart.snapshot` which we need to run analysis. What version of the SDK is it (`dart --version`) and where did you get it from?

**Comment by igotyou** [comment]
Oh i see. dart --version returns
`Dart VM version: 2.7.2 (Mon Mar 23 22:11:27 2020 +0100) on "linux_arm"`
I downloaded it from https://dart.dev/tools/sdk/archive , more specifically this link https://storage.googleapis.com/dart-archive/channels/stable/release/2.7.2/sdk/dartsdk-linux-arm-release.zip

**Comment by DanTup** [comment]
Thanks - I've moved this over to https://github.com/dart-lang/sdk/issues/41845 as it seems like that SDK is incomplete. In the meantime, if your Pi supports ARMv7, that SDK does include the analysis_server snapshot. Otherwise you might be able to clone the SDK repo and build the snapshot from the source (or run the server from source using the `dart.analyzerPath` setting).

**Comment by igotyou** [comment]
Thanks for the help Dan 👍
