### ISSUE TITLE
Can we show the library a name came from?

### ISSUE THREAD

**Issue by sethladd** [Dart-Code/Dart-Code#245]
I'm looking at code, and I'm curious where SourceCode came from. I hover, and I see a nice description of the API but I don't see the library name.

![screen shot 2017-01-06 at 12 19 43 pm](https://cloud.githubusercontent.com/assets/5479/21731713/91a81ed6-d40a-11e6-9ff8-88ad2ce5e9ba.png)

**Comment by DanTup** [comment]
Looks like this should be quite simple; the `getHover` response from the analysis server has `containingLibraryName` but we don't currently use it in [DartHoverProvider](https://github.com/Dart-Code/Dart-Code/blob/master/src/providers/dart_hover_provider.ts).

**Comment by sethladd** [comment]
Cool, good to hear

**Comment by DanTup** [comment]
@sethladd Is there source for SourceCode available? I just came to work on this and noticed your tooltip is weird, the top line looks like it's showing source code (there's a brace on the end, and an ellipsis). I can't repro that and it doesn't look right!

![hover](https://cloud.githubusercontent.com/assets/1078012/22368996/64d04b54-e481-11e6-9e10-1a658c245bed.png)

**Comment by DanTup** [comment]
Sorry for the delay; this change has been released!

**Comment by sethladd** [comment]
Thanks!

**Comment by DanTup** [comment]
@sethladd See [my earlier comment](https://github.com/Dart-Code/Dart-Code/issues/245#issuecomment-275642770); though screenshot seems to show code in the top line of the tooltip which doesn't seem right (and I couldn't repro). If you still see this and you don't think it's right, could you open a new case about it?
