### ISSUE TITLE
extention methods not discoved automaticly

### ISSUE THREAD

**Issue by mo-ah-dawood** [Dart-Code/Dart-Code#2457]
If i created extention method in file a 
Vs code can not auto import it in file b
I have to import it manualy to be discovered

**Comment by DanTup** [comment]
Thanks for the report! Completion comes from the analyzer in the SDK - there's an open issue tracking this here:

https://github.com/dart-lang/sdk/issues/38894

Please subscribe there for updates. Once implemented there, it should (in theory) "just work" in VS Code when using the newer SDK.

Thanks!
