### ISSUE TITLE
reducing location permission on Android emulator causes Exit from debug session

### ISSUE THREAD

**Issue by gkrawiec** [Dart-Code/Dart-Code#2463]
If testing apps response to different permissions, things work correctly if in app location settings I change from deny to only when in use and also to allow...but if I go the other way, reducing the level of permission it quits the debuggin session with
```
Lost connection to device.
Exited (sigterm)
```

I don't know if this is a vscode/dart-code issue or a flutter issue.
Currently using
```
VS Code Version: 1.45.1
Flutter extension: 3.10.1

[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.1)
[✓] Connected device (1 available)
• No issues found!
```
but....i has always done this.

If this is a flutter issue, let me know and I will post it in the flutter repo.
thank you.

**Comment by DanTup** [comment]
If this is a bug, I think it would be in Flutter or the emulator. All Dart-Code does is run `flutter run`.

To confirm it's not Dart-Code, can you try running from the terminal with `flutter run` and see if you see the same behaviour?

**Comment by gkrawiec** [comment]
seems like you are correct. I tried from the terminal and the same thing happened.
I will post on  flutter issues.
thank you.
