### ISSUE TITLE
Show full documentation

### ISSUE THREAD

**Issue by AntiqPeace** [Dart-Code/Dart-Code#2468]
![Screenshot 2020-05-19 at 11 18 08 AM](https://user-images.githubusercontent.com/59781377/82289697-ff0d7a80-99c2-11ea-9b7d-39ad49b3fc73.png)

In above screenshot, for `int x`, we can see that only the documentation which doesn't have line breaks. The description `Some more description.....` isn't showed.
This gets more difficult if we are quickly skimming through an API's functions and their usage.

Many of the Flutter Widgets provide an example below them.
It would be excellent to show the full documentation.

**Comment by DanTup** [comment]
I've fixed the examples given here:

![Screenshot 2020-05-19 at 08 49 45](https://user-images.githubusercontent.com/1078012/82299945-1130ee00-99ae-11ea-94fe-8ad02f6d49c1.png)

However, the docs won't currently show on many completions due to https://github.com/dart-lang/sdk/issues/37816. This may be fixable for the LSP version though (which will ultimately become the default mode) so I'll take a look there.

**Comment by DanTup** [comment]
Apparently I already did it for LSP 🙂

![Screenshot 2020-05-19 at 08 57 12](https://user-images.githubusercontent.com/1078012/82300447-c368b580-99ae-11ea-86a1-613dd5c13dc8.png)

**Comment by AntiqPeace** [comment]
@DanTup thanks.

> This may be fixable for the LSP version though (which will ultimately become the default mode

I don't understand these lines. LSP mode? Do I have to do anything for this?

**Comment by DanTup** [comment]
Sorry, I should've been more explicit :-)

LSP is a [common protocol](https://microsoft.github.io/language-server-protocol/) for language servers. The Dart extension is in the process of migrating to it but it's not completely finished yet.

When it's finished, and we move over to it, you will see the full documentation (as in my last screenshot).

If you want to try it out early, you can enable the `.dart.previewLsp` setting (added in v3.9 https://dartcode.org/releases/v3-9/#preview-lsp) to use that mode. There are some known issues with the LSP mode [documented here](https://github.com/Dart-Code/Dart-Code/issues/2286).

If anything isn't clear let me know!
