### ISSUE TITLE
Analyzing... never ends and nothing happens.

### ISSUE THREAD

**Issue by mezoni** [Dart-Code/Dart-Code#247]
Analyzing... never ends and nothing happens.
I can send you source code and you can see this in action.
Why this happens I did not know.
![screenshot at 2017-01-19 20-28-18](https://cloud.githubusercontent.com/assets/2311549/22112788/201d4760-de86-11e6-8272-3da021a18ded.png)

**Comment by DanTup** [comment]
Can you confirm:

- What OS/version this is
- What VS Code version
- What Dart SDK version
- What Dart Code version

Does this happen for all projects, or just this one? Did you get any popup asking if you would send an error report?

Also, if you open your VS Code User Settings and add a setting called `dart.analyzerLogFile` that is a full path for a file to save logs (note: you won't get completion and the editor may say this option is not valid; it's not, it's just a debug setting) and reload VS Code and try again, is there anything useful in that log?

If you're happy to share the folder, I'm happy to try and repro here (though I'm on Windows).

Thanks!

**Comment by mezoni** [comment]
Sorry, but this issue should not be addressed to the your project because you are not responsible for the work of the Dart analyzer.
I tried to use a command line `dart-sdk/bin/dartanalyzer` and it can not complete the analysis of specified source code.
You should reject this issue and close it as incorrect.
Problem in the tools supplied with the Dart SDK.

**Comment by DanTup** [comment]
That's valid, but even if I can't fix the issue I think it'd be great if Dart Code handled this better (like informed you that the Dart Analyzer is not responding as expected). I'd be very interested to know exactly what's happening to see if I could easily make Dart Code give more info to the user about what's wrong 🙂

**Comment by mezoni** [comment]
Unfortunately, I have no desire to help programmers to Google Dart Team.
They are professionals. I think they can cope well without my help.
Especially considering the fact that they added me in the black list on https://github.com/dart-lang.
In gratitude for what I have added at least a hundred of bug track items (issues) on this group of the projects called "Dart".

**Comment by DanTup** [comment]
I'm not on the Google Dart Team, nor do I work for Google. I'd love if you could help me improve the experience when this issue occurs for other Dart Code users.

I don't the reason you've been blacklisted (and I don't really want to get involved); but if you change your mind and choose to help me/other Dart Code users out then you're always welcome to post back here with more info. Thanks!

**Comment by mezoni** [comment]
Oh no thanks.
This will not help making Dart code better only because Dart will remains a bleeding edge technology developed software.
This is a cheapest approach for developing software.
This looks not a very serious for a very serious company such as Google.
Why Google decided to save money on the development of serious software as Dart Web Platform?
Where we can find in a Google Dart Team a professional software testers?
Who are these persons?
I do not know them.
Why I should perform these works for Google if Google develops Dart not for me, nor for you, nor for everyone but Google develops Dart for its own requirements and gets from this a profit.
You do not know then I can say you that Google does not perceives Dart as a serious instrumentation for professional software development.
The proof is in that the Google never provide standard SDK or API implemented in Dart language for well known and popular protocols, services, frameworks and other wide used software.
Google always avoided Dart.
Why I should do that (or similar) for Google?
