### ISSUE TITLE
Parens not being brought when using autocomplete

### ISSUE THREAD

**Issue by sollymay** [Dart-Code/Dart-Code#2477]
So lately I've been experiencing this issue were if I select a widget/function or whatever has a set of parens in the suggestions, when I tab or enter to select that option, I get the selection stripped out of the parens.

Screenshot 1: Selecting the DropdownButton() option that includes parens (second option on the suggestions dropdown)

![Screen Shot 2020-05-19 at 4 17 02 PM](https://user-images.githubusercontent.com/6496698/82373842-2d538000-99ec-11ea-913a-ab925b5a63ff.png)

Screenshot2: When I press tab/enter, the DropdownButton without the parens () gets autocompleted

![Screen Shot 2020-05-19 at 4 18 27 PM](https://user-images.githubusercontent.com/6496698/82373963-6390ff80-99ec-11ea-9049-d7c836fd278e.png)

**Comment by DanTup** [comment]
Can you check whether you have this setting enabled or not?

<img width="686" alt="Screenshot 2020-05-20 at 09 25 04" src="https://user-images.githubusercontent.com/1078012/82423555-d1383c80-9a7b-11ea-9c22-2f032b84f438.png">

**Comment by sollymay** [comment]
hey @DanTup, thank you for your quick reply! I think its enabled.

![Screen Shot 2020-05-20 at 10 21 49 AM](https://user-images.githubusercontent.com/6496698/82457761-cda8b380-9a83-11ea-915f-df7a099de6ca.png)

**Comment by sollymay** [comment]
hey @DanTup, thank you for your quick reply! I think its enabled.

![Screen Shot 2020-05-20 at 10 21 49 AM](https://user-images.githubusercontent.com/6496698/82457761-cda8b380-9a83-11ea-915f-df7a099de6ca.png)

I think the issue was having enableCompletionCommitCharacters also enabled 🗡️ . Not sure why or when I did enable that option, but once I disabled it, it started working. I'm closing this issue now.

**Comment by DanTup** [comment]
> I think the issue was having enableCompletionCommitCharacters also enabled

Ah, yes - that will automatically disable this. The idea with commit chars is that you should type the `(` to commit the function instead of tab/enter (since tab/enter would be used if you wanted to just reference the function). Really, in that situation we should not show both entries in the completion since they would be the same. This behaviour should be tidied up, but will likely be in the LSP version in future.
