### ISSUE TITLE
Autocompletion deleting the next character

### ISSUE THREAD

**Issue by ShardulNalegave** [Dart-Code/Dart-Code#2480]
When I use the Autocomplete options the next character of the line gets deleted. This has started to happen recently.

For example:-

````dart

Mater();

````

turns to

````dart

Material);

````

**Comment by DanTup** [comment]
This sounds a lot like #1627 (and #1368). Where sometimes requests are being processed in the wrong order in the language server.

I think this may be solved in the (upcoming) LSP version of the server, as it should be passing document versions around.

If you can usually reproduce this reliably, could you try setting `"dart.previewLsp": true` in your VS Code settings and restarting, and seeing whether the issue goes away?

**Comment by RobPFarley** [comment]
I've run across a similar problem with autocompletion just generally messing up, and adding the above flag fixed it for me. 

An example of the issue I came across was implementing inherited functions, for example in the following code WeatherRepository is an abstract class with 2 functions:

``` dart
class MockWeatherRepository extends WeatherRepository {
  
}
```

And hitting 'Create 2 missing override(s)' in the ctrl+. menu gave me the following:

``` dart
class MockWeatherRepository extends WeatherRepository {
  @override
  Future<Weather> fetchDetailedWeather(String cityName) {
      // TODO: implement fetchDetailedWeather
      throw UnimplementedError();
    }
  
    @override
    Future<Weather> fetchWea(Strint cityNamyName) {
    // TODO: implement fetchWeather
    throw UnimplementedError();
  }
  
}
```

I found that after doing the autocomplete, pressing ctrl+z to undo would change it to the correct output:

``` dart
class MockWeatherRepository extends WeatherRepository {
  @override
  Future<Weather> fetchDetailedWeather(String cityName) {
    // TODO: implement fetchDetailedWeather
    throw UnimplementedError();
  }

  @override
  Future<Weather> fetchWeather(String cityName) {
    // TODO: implement fetchWeather
    throw UnimplementedError();
  }
  
}
```

Like I said though, settings the ```"dart.previewLsp": true``` flag seems to have fixed it for me. I'll post here if I come across any more hiccups that it doesn't fix. Also if you'd like the code I was working on at the time it can be found [here](https://github.com/RobPFarley/reso_coder_bloc_tutorial). Cheers

**Comment by DanTup** [comment]
That's weird, I can't explain that issue - though if things are working ok in the LSP version, that's good - the goal is to move everything over to the LSP version in time. If you find any issues in the LSP mode that aren't listed in https://github.com/Dart-Code/Dart-Code/issues/2286, please do file bugs for them.

Thanks!
