### ISSUE TITLE
Support folder renames/moves

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#2483]

**Comment by tmaihoff** [comment]
Hi, do we have an update here about folder renaming in dart?

**Comment by DanTup** [comment]
No update yet, though I would like to try and get back to this soon.

**Comment by DanTup** [comment]
I have been been working on this, but it's currently blocked by an issue in VS Code/LSP where clicking "cancel" on the notification for slow refactors does not pass the message to the server (which means if you rename a large folder then click cancel, the server will continue to perform the rename in the background).

Fixes are in progress for that, but not released. Once they are, I hope to complete this.

**Comment by DanTup** [comment]
This has landed in the server and is available in the current Flutter beta channel.
