### ISSUE TITLE
Support for the new faststart option

### ISSUE THREAD

**Issue by bsutton** [Dart-Code/Dart-Code#2484]
With the release of flutter 1.17 and the new --faststart switch I'm trying to work out how to get the vcscode plug to use the faststart option.

The fast state reduces my start time from 40sec down to 30sec so have access to this option would be really useful.

**Comment by DanTup** [comment]
You should be able to pass any arbitrary flags to Flutter using the `args` field in a `launch.json`:

```js
{
	"name": "Flutter",
	"request": "launch",
	"type": "dart",
	"args": [
		"--fast-start"
	]
}
```

I'm not sure it's worth having a specific flag/feature for in VS Code though.
