### ISSUE TITLE
Quick Fix for local packages offers 'package' import.

### ISSUE THREAD

**Issue by bsutton** [Dart-Code/Dart-Code#2485]
When performing a quick fix for a missing import dart-code mostly only offers the 'package' import syntax rather than the relative import syntax.

Effective Dart recommends using the relative import.

I do sometimes get offered a relative import but mostly I'm offered the package import.
I've not worked out a pattern as to why it does this.
I do mostly work in a workspace if this makes any difference.

Even if both are offered the relative import should be at the top of the list.

**Comment by DanTup** [comment]
> Even if both are offered the relative import should be at the top of the list.

I think there are differing opinions on this, why is why things have been a bit mixed. There's an open issue tracking this at https://github.com/dart-lang/sdk/issues/32916 and the most recent comment suggests that both should always be available now - however the auto-imports have not been updated.

I'll close this as a dupe here, and ping on that issue to see whether it's likely user preferences (or lints) will be taken into account.

**Comment by bsutton** [comment]
I've been applying the effective dart lints such recommend relative paths.

In not certain how official effective dart lints are but if they are for
endorsed it would seem sensible to follow those.

**Comment by DanTup** [comment]
I couldn't see anything in Effective Dart: Style that said to prefer relative paths. There is a lint for the opposite (avoid_relative_lib_imports). The Dart SDK codebase (in the analysis server, at least) uses `package:` imports, and Flutter's SDK uses relative. I don't think there's a clear preference for either, so just going with one will  likely upset some not-insignificant number of developers 😞 

In any case, the fix needs to be in the server rather than here so the issue linked above is the best place to watch/subscribe to for updates :-)

**Comment by bsutton** [comment]
I'm using effective dart and the lint I'm getting is
prefer_relative_imports.
You can see the merge for this rule here:
https://github.com/tenhobi/effective_dart/pull/21

I'm not suggesting that we only offer relative paths. (unless you can
detect that the lint rule is enabled).
The problem is that relative paths aren't being offered when the imported
library is further up the tree.

**Comment by DanTup** [comment]
> You can see the merge for this rule here:
> tenhobi/effective_dart#21

Ah, got it - I wasn't aware of that package :-)

> The problem is that relative paths aren't being offered when the imported library is further up the tree.

Understood. These come from the server, so this will need fixing there - I see you've noted it on the SDK issue, so this can he handled there. Thanks!
