### ISSUE TITLE
dev tools

### ISSUE THREAD

**Issue by guoxiaoqiang** [Dart-Code/Dart-Code#2486]
Dart DevTools exited with code 66 error, any help appreciate!

**Comment by DanTup** [comment]
Can you try:

- Running the **Dart: Capture Logs** command (untick Analysis Server, but you can leave everything else ticked and click OK)
- Try to launch DevTools
- Click **Cancel** on the logging notification to open the log
- Attach the log here

Thanks!

**Comment by guoxiaoqiang** [comment]
@DanTup 

Here you are Sir:

!! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.10.2
Flutter extension: 3.10.2 (activated)
VS Code: 1.45.1
Platform: win
Workspace type: Flutter
Multi-root?: false
Dart SDK:
    Loc: D:\Flutter\FlutterVer\flutter_v1.12.13\bin\cache\dart-sdk
    Ver: 2.7.0
Flutter SDK:
    Loc: D:\Flutter\FlutterVer\flutter_v1.12.13
    Ver: 1.12.13+hotfix.8
HTTP_PROXY: undefined
NO_PROXY: undefined

Sat May 23 2020 [16:55:24 GMT+0800 (中国标准时间)] Log file started
[下午4:55:24] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224123854,"extensionData":{"number":3,"startTime":9313219119,"elapsed":1415374,"build":1358923,"raster":55911}}}}
[下午4:55:25] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224125360,"extensionData":{"number":4,"startTime":9315996610,"elapsed":315603,"build":300118,"raster":14754}}}}
[下午4:55:27] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224126880,"extensionData":{"number":5,"startTime":9317406905,"elapsed":217032,"build":184923,"raster":31282}}}}
[下午4:55:27] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224127244,"extensionData":{"number":6,"startTime":9317708559,"elapsed":380939,"build":357251,"raster":23063}}}}
[下午4:55:29] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224128890,"extensionData":{"number":7,"startTime":9319815918,"elapsed":131823,"build":112714,"raster":18288}}}}
[下午4:55:30] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Error","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224129396,"extensionData":{"description":"Exception caught by rendering library","type":"_FlutterErrorDetailsNode","allowWrap":false,"objectId":"inspector-0","valueId":"inspector-1","properties":[{"description":"The following assertion was thrown during layout:","type":"ErrorDescription","showSeparator":false,"showName":false,"style":"flat","allowNameWrap":true,"objectId":"inspector-2","valueId":"inspector-3","properties":[],"children":[],"defaultValue":"null","missingIfNull":false,"propertyType":"List<Object>","defaultLevel":"info"},{"description":"A RenderFlex overflowed by 0.420 pixels on the bottom.","type":"ErrorSummary","showSeparator":false,"level":"summary","showName":false,"style":"flat","allowNameWrap":true,"objectId":"inspector-4","valueId":"inspector-5","properties":[],"children":[],"defaultValue":"null","missingIfNull":false,"propertyType":"List<Object>","defaultLevel":"summary"},{"description":"","type":"ErrorSpacer","name":"","showName":false,"style":"singleLine","allowNameWrap":true,"objectId":"inspector-6","valueId":null,"properties":[],"children":[],"missingIfNull":false,"propertyType":"void","defaultLevel":"info","value":null},{"description":null,"type":"DiagnosticsBlock","name":"The relevant error-causing widget was","style":"whitespace","hasChildren":true,"allowWrap":false,"objectId":"inspector-7","valueId":null,"properties":[],"children":[{"description":"Column file:///D:/FlutterCode/flutter_shop/lib/pages/home_page.dart:395:16","type":"ErrorDescription","showSeparator":false,"showName":false,"style":"flat","allowNameWrap":true,"objectId":"inspector-8","valueId":"inspector-9","properties":[],"children":[],"defaultValue":"null","missingIfNull":false,"propertyType":"Li…
[下午4:55:30] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Error","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224129750,"extensionData":{"description":"Exception caught by rendering library","type":"_FlutterErrorDetailsNode","allowWrap":false,"objectId":"inspector-124","valueId":"inspector-125","properties":[{"description":"The following assertion was thrown during layout:","type":"ErrorDescription","showSeparator":false,"showName":false,"style":"flat","allowNameWrap":true,"objectId":"inspector-126","valueId":"inspector-127","properties":[],"children":[],"defaultValue":"null","missingIfNull":false,"propertyType":"List<Object>","defaultLevel":"info"},{"description":"A RenderFlex overflowed by 0.420 pixels on the bottom.","type":"ErrorSummary","showSeparator":false,"level":"summary","showName":false,"style":"flat","allowNameWrap":true,"objectId":"inspector-128","valueId":"inspector-129","properties":[],"children":[],"defaultValue":"null","missingIfNull":false,"propertyType":"List<Object>","defaultLevel":"summary"},{"description":"","type":"ErrorSpacer","name":"","showName":false,"style":"singleLine","allowNameWrap":true,"objectId":"inspector-130","valueId":null,"properties":[],"children":[],"missingIfNull":false,"propertyType":"void","defaultLevel":"info","value":null},{"description":null,"type":"DiagnosticsBlock","name":"The relevant error-causing widget was","style":"whitespace","hasChildren":true,"allowWrap":false,"objectId":"inspector-131","valueId":null,"properties":[],"children":[{"description":"Column file:///D:/FlutterCode/flutter_shop/lib/pages/home_page.dart:395:16","type":"ErrorDescription","showSeparator":false,"showName":false,"style":"flat","allowNameWrap":true,"objectId":"inspector-132","valueId":"inspector-133","properties":[],"children":[],"defaultValue":"null","missingIfNull":fals…
[下午4:55:30] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224129782,"extensionData":{"number":8,"startTime":9320102208,"elapsed":636488,"build":597134,"raster":38341}}}}
[下午4:55:30] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224130003,"extensionData":{"number":9,"startTime":9320828459,"elapsed":231925,"build":192609,"raster":38004}}}}
[下午4:55:30] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Error","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224130335,"extensionData":{"description":"Exception caught by rendering library","type":"_FlutterErrorDetailsNode","allowWrap":false,"objectId":"inspector-229","valueId":"inspector-230","properties":[{"description":"The following assertion was thrown during layout:","type":"ErrorDescription","showSeparator":false,"showName":false,"style":"flat","allowNameWrap":true,"objectId":"inspector-231","valueId":"inspector-232","properties":[],"children":[],"defaultValue":"null","missingIfNull":false,"propertyType":"List<Object>","defaultLevel":"info"},{"description":"A RenderFlex overflowed by 0.420 pixels on the bottom.","type":"ErrorSummary","showSeparator":false,"level":"summary","showName":false,"style":"flat","allowNameWrap":true,"objectId":"inspector-233","valueId":"inspector-234","properties":[],"children":[],"defaultValue":"null","missingIfNull":false,"propertyType":"List<Object>","defaultLevel":"summary"},{"description":"","type":"ErrorSpacer","name":"","showName":false,"style":"singleLine","allowNameWrap":true,"objectId":"inspector-235","valueId":null,"properties":[],"children":[],"missingIfNull":false,"propertyType":"void","defaultLevel":"info","value":null},{"description":null,"type":"DiagnosticsBlock","name":"The relevant error-causing widget was","style":"whitespace","hasChildren":true,"allowWrap":false,"objectId":"inspector-236","valueId":null,"properties":[],"children":[{"description":"Column file:///D:/FlutterCode/flutter_shop/lib/pages/home_page.dart:395:16","type":"ErrorDescription","showSeparator":false,"showName":false,"style":"flat","allowNameWrap":true,"objectId":"inspector-237","valueId":"inspector-238","properties":[],"children":[],"defaultValue":"null","missingIfNull":fals…
[下午4:55:31] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224130405,"extensionData":{"number":10,"startTime":9321150531,"elapsed":158782,"build":87321,"raster":70517}}}}
[下午4:55:31] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224130623,"extensionData":{"number":11,"startTime":9321365288,"elapsed":287310,"build":231892,"raster":54067}}}}
[下午4:55:31] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224130756,"extensionData":{"number":12,"startTime":9321741039,"elapsed":98588,"build":71836,"raster":26099}}}}
[下午4:55:31] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224130864,"extensionData":{"number":13,"startTime":9321902048,"elapsed":81811,"build":52931,"raster":28347}}}}
[下午4:55:31] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224131314,"extensionData":{"number":14,"startTime":9322367278,"elapsed":82953,"build":59417,"raster":22387}}}}
[下午4:55:32] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224131666,"extensionData":{"number":15,"startTime":9322760876,"elapsed":39023,"build":16576,"raster":20936}}}}
[下午4:55:32] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224131669,"extensionData":{"number":16,"startTime":9322814529,"elapsed":47448,"build":24354,"raster":21992}}}}
[下午4:55:32] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224131822,"extensionData":{"number":17,"startTime":9322868217,"elapsed":68073,"build":37200,"raster":30240}}}}
[下午4:55:32] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224131825,"extensionData":{"number":18,"startTime":9322921894,"elapsed":51628,"build":19634,"raster":28831}}}}
[下午4:55:32] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224131832,"extensionData":{"number":19,"startTime":9322957695,"elapsed":53338,"build":23857,"raster":28722}}}}
[下午4:55:32] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224131837,"extensionData":{"number":20,"startTime":9323011362,"elapsed":46980,"build":23362,"raster":21987}}}}
[下午4:55:32] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224131987,"extensionData":{"number":21,"startTime":9323065046,"elapsed":68658,"build":46126,"raster":21301}}}}
[下午4:55:33] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224132406,"extensionData":{"number":22,"startTime":9323512381,"elapsed":42565,"build":9640,"raster":31865}}}}
[下午4:55:33] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224132406,"extensionData":{"number":23,"startTime":9323548171,"elapsed":47017,"build":10078,"raster":36156}}}}
[下午4:55:34] [General] [Info] Spawning D:\Flutter\FlutterVer\flutter_v1.12.13\bin\cache\dart-sdk\bin\pub.bat with args ["global","list"]
[下午4:55:34] [CommandProcesses] [Info] (PROC 4804) Logging data for process...
[下午4:55:35] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224134630,"extensionData":{"number":24,"startTime":9325740742,"elapsed":29234,"build":8371,"raster":19320}}}}
[下午4:55:35] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224134633,"extensionData":{"number":25,"startTime":9325757418,"elapsed":50364,"build":12901,"raster":36653}}}}
[下午4:55:35] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224134635,"extensionData":{"number":26,"startTime":9325790712,"elapsed":46959,"build":15999,"raster":25558}}}}
[下午4:55:35] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224134639,"extensionData":{"number":27,"startTime":9325824041,"elapsed":55429,"build":19611,"raster":34236}}}}
[下午4:55:35] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224134834,"extensionData":{"number":28,"startTime":9325851828,"elapsed":72217,"build":22732,"raster":43854}}}}
[下午4:55:35] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224134835,"extensionData":{"number":29,"startTime":9325888684,"elapsed":63698,"build":21807,"raster":27619}}}}
[下午4:55:35] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224134836,"extensionData":{"number":30,"startTime":9325925525,"elapsed":55299,"build":16133,"raster":27997}}}}
[下午4:55:35] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224134836,"extensionData":{"number":31,"startTime":9325943940,"elapsed":79711,"build":13982,"raster":42399}}}}
[下午4:55:35] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224134836,"extensionData":{"number":32,"startTime":9325980785,"elapsed":80515,"build":37405,"raster":37150}}}}
[下午4:55:35] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224134950,"extensionData":{"number":33,"startTime":9326035991,"elapsed":59597,"build":27880,"raster":31049}}}}
[下午4:55:35] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224134951,"extensionData":{"number":34,"startTime":9326091263,"elapsed":48652,"build":22359,"raster":25578}}}}
[下午4:55:35] [CommandProcesses] [Info] (PROC 4804) devtools 0.2.3
[下午4:55:35] [CommandProcesses] [Info] (PROC 4804)
[下午4:55:35] [CommandProcesses] [Info] (PROC 4804) exited (0, null)
[下午4:55:35] [CommandProcesses] [Info] (PROC 4804) closed (0, null)
[下午4:55:35] [DevTools] [Info] Spawning D:\Flutter\FlutterVer\flutter_v1.12.13\bin\cache\dart-sdk\bin\pub.bat with args ["global","run","devtools","--machine","--enable-notifications","--try-ports","10"]
[下午4:55:35] [DevTools] [Info] ..  with {"toolEnv":{"FLUTTER_HOST":"VSCode","PUB_ENVIRONMENT":"vscode.dart-code"}}
[下午4:55:35] [DevTools] [Info]     PID: 9488
[下午4:55:36] [DevTools] [Error] Could not find a file named "pubspec.yaml" in "C:\Users\johnny\AppData\Roaming\Pub\Cache\hosted\pub.flutter-io.cn\devtools-0.2.3".
[下午4:55:36] [DevTools] [Error] 
[下午4:55:36] [DevTools] [Info] Process terminated! 66, null
[下午4:55:36] [General] [Error] Dart DevTools exited with code 66
[下午4:55:36] [General] [Error] Dart DevTools exited with code 66
[下午4:55:38] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224137647,"extensionData":{"number":35,"startTime":9328749170,"elapsed":40604,"build":14486,"raster":24544}}}}
[下午4:55:38] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224137652,"extensionData":{"number":36,"startTime":9328772254,"elapsed":59910,"build":23948,"raster":34580}}}}
[下午4:55:38] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224137653,"extensionData":{"number":37,"startTime":9328805594,"elapsed":50906,"build":15132,"raster":23385}}}}
[下午4:55:38] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224137655,"extensionData":{"number":38,"startTime":9328838933,"elapsed":55596,"build":31788,"raster":22307}}}}
[下午4:55:38] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224137806,"extensionData":{"number":39,"startTime":9328881437,"elapsed":53830,"build":13994,"raster":39079}}}}
[下午4:55:38] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224137806,"extensionData":{"number":40,"startTime":9328899370,"elapsed":63686,"build":29592,"raster":27070}}}}
[下午4:55:38] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224137807,"extensionData":{"number":41,"startTime":9328935269,"elapsed":55035,"build":14342,"raster":26717}}}}
[下午4:55:38] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224137807,"extensionData":{"number":42,"startTime":9328971151,"elapsed":43573,"build":16479,"raster":24021}}}}
[下午4:55:38] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224137807,"extensionData":{"number":43,"startTime":9329007014,"elapsed":40238,"build":12351,"raster":26572}}}}
[下午4:55:38] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224137938,"extensionData":{"number":44,"startTime":9329024954,"elapsed":62357,"build":15785,"raster":38909}}}}
[下午4:55:38] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224137940,"extensionData":{"number":45,"startTime":9329042905,"elapsed":75534,"build":13356,"raster":30087}}}}
[下午4:55:38] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/331194569002647","name":"main","number":"331194569002647"},"timestamp":1590224137946,"extensionData":{"number":46,"startTime":9329078809,"elapsed":71405,"build":26481,"raster":31247}}}}
Sat May 23 2020 [16:55:39 GMT+0800 (中国标准时间)] Log file ended

**Comment by guoxiaoqiang** [comment]
I just check my C:\Users\johnny\AppData\Roaming\Pub\Cache\hosted, there no "pub.flutter-io.cn" folder, only have one folder "pub.dartlang.org",  and I am using the https://pub.flutter-io.cn mirror

**Comment by DanTup** [comment]
Ok, I think I see what's going on. The issue is that your version of DevTools is broken (there was a bad release a few weeks ago which might be it). We normally check for new versions and try to auto-update, however if you're in China and pub.dartlang.org is blocked, that would prevent is detecting the new version.

So, please run this from your terminal:

```
pub global activate devtools
```

If `pub` is not on your `PATH`, you may need to prefix it with the full path to `pub` in the Flutter SDK, like:

```
/Users/danny/Dev/Flutter/bin/cache/dart-sdk/bin/pub global activate devtools
```

Note: Do not prefix the command with `flutter`, it must be called through `pub` directly.

**Comment by beilly** [comment]
Is dev tools's version mismatch dart? @DanTup

**Comment by DanTup** [comment]
@beilly I believe the issue is that the code we use for checking for updates to DevTools does not work in China, so DevTools is not automatically updated.

I've opened https://github.com/Dart-Code/Dart-Code/issues/2503 to explore some options to improve this.

**Comment by guoxiaoqiang** [comment]
thank you sir, i will try your suggestions.

**Comment by wickedknock** [comment]
did not find cache/dart-sdk/bin/pub , there is no pub in my bin folder for dart-sdk

**Comment by DanTup** [comment]
@wickedknock it's not clear from your comment what the problem is, but this is a very old issue that was closed 4 years ago.

Please open a new issue with a clear description of the issue if you've having problems. Thanks!
