### ISSUE TITLE
Enable assist to ignore lints by default

### ISSUE THREAD

**Issue by bsutton** [Dart-Code/Dart-Code#2487]
When I start working on a new code base one of the first things I tend to do is add the effective dart lints.
This typically yields thousands of errors.
A moderate no. of the lints are not valid.

It would be really convenient if the dart-code offered an 'add ignore' option quick fix for these lints.

**Comment by DanTup** [comment]
This is supported, but you have to enable it with the following setting:

```js
"dart.showIgnoreQuickFixes": true,
```

That should add additional quick-fix entries to ignore. Let me know if you have any issues with it!

**Comment by bsutton** [comment]
OK, so that works.

However this is another one that I think should be on by default.

**Comment by DanTup** [comment]
The implementation of this is slightly hacky - it's done client-side and not in the language server, so it works by looking at errors in the current file and fabricates the assist, then just inserts a comment in the line above. It's possible for some code it might insert incorrectly.

I tend to ship things like that off-by-default to get a little feedback usually from the person that originally asked for it, or my own use). There hasn't been much, but I've used it myself enough that I'm reasonable sure of it, so I'll look at switching it on by default in an upcoming version.

**Comment by bsutton** [comment]
I've used this a couple of times now and it seems to be working fine.

I would be inclined to ship it on by default.
Worst case it inserts it incorrectly and the user just has to ctrl-z to fix the issue.
