### ISSUE TITLE
Bulb menu should open immediately after clicking on the info icon in the problems view

### ISSUE THREAD

**Issue by bsutton** [Dart-Code/Dart-Code#2488]
When working through large no.s of lints I use the quick fix bulb in the 'problems' pane to rapidly fix many trivial errors.

This process is slowed down by how the 'quick fix bulb' appears and then disappears.
The process I used is to apply these fixes is:
click on the line
wait for the bulb to appear
click the bulb
select the action.

The problem is that the bulb will appear and then disappear be for re-appearing.
It also changes color from white to yellow (which I'm sure indicates something but I've not worked it out as yet).
My preferred operation would be:
click line
click 'info' icon.
The code then looks for quick fixes and displays the menu.

This would eliminate the slight delay in having to wait for the bulb to appear.

**Comment by DanTup** [comment]
Are you able to provide an example project and/or log when this happens? When I tested it, the bulb is always yellow and appears very quickly.

![bulb](https://user-images.githubusercontent.com/1078012/82886301-43a69200-9f3e-11ea-9da3-ebcd594564bc.gif)

> click 'info' icon.
> The code then looks for quick fixes and displays the menu.
> 
> This would eliminate the slight delay in having to wait for the bulb to appear.

Changes to how this menu works/appears would have to come from VS Code. The APIs are very limited - VS Code just asks us for quick-fixes and we provide the data for them - we have no control over how the UI behaves.

**Comment by bsutton** [comment]
Sorry the issue in referring to is in the problem view.

Click an error in the problem view and you get the bulb which changes
colour.

**Comment by DanTup** [comment]
Oh, sorry - I see.

It looks like the white bulb is just when that row is selected:

<img width="395" alt="Screenshot 2020-05-26 at 14 34 41" src="https://user-images.githubusercontent.com/1078012/82907085-110c9180-9f5e-11ea-8eb3-880322927dc4.png">

<img width="332" alt="Screenshot 2020-05-26 at 14 34 45" src="https://user-images.githubusercontent.com/1078012/82907092-11a52800-9f5e-11ea-9176-72718516f728.png">

I do have to click twice there to get the menu:

![May-26-2020 14-38-21](https://user-images.githubusercontent.com/1078012/82907572-af98f280-9f5e-11ea-9fe5-9b038493f965.gif)

I think it's a fair request that clicking the icon should open the menu right away, but that would need to be raised with VS Code as it's not something we have any control over.

**Comment by bsutton** [comment]
I've raised here:
https://github.com/microsoft/vscode/issues/98618
