### ISSUE TITLE
Shows warnings in renamed files

### ISSUE THREAD

**Issue by eseidel** [Dart-Code/Dart-Code#249]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|dart-code|DanTup|0.14.9|
|prettify-json|mohsen1|0.0.3|

When I rename a file with errors in it, the errors don't go away until I `killall dart` from the commandline (to force the analyzer server to restart).

![screen shot 2017-01-22 at 8 11 34 am](https://cloud.githubusercontent.com/assets/478541/22183814/7dea8190-e07b-11e6-86a8-aabeeabdaa45.png)

if I click on one of those all I get is this dialog:

![screen shot 2017-01-22 at 8 19 33 am](https://cloud.githubusercontent.com/assets/478541/22183819/8dc8eef8-e07b-11e6-8429-ad03aa9c43df.png)

I would expect that since I used vscode to do the rename, it would explain to the analyzer the file is gone.

**Comment by DanTup** [comment]
That sounds reasonable, but.. for deleted files the analysis server sees the filesystem change and sends us a `flushResults` event (see #55) so I think probably it should be doing the same for renames? @bwilkerson - does this sound reasonable?

**Comment by bwilkerson** [comment]
As far as I can tell by looking at the `WatchEvent` class, a rename would be reported as an addition and removal of a file (the change event claims it is only used when the *content* of a file is changed. So, yes, I would expect server to send a `flushResults` for the old name of the file.

**Comment by DanTup** [comment]
@eseidel I just test this and it actually worked (did what Brian suggested). The file was renamed, the AS sent a flush, and the filename updated in my errors list.

```text
[19:00:11]: <== {"event":"analysis.flushResults","params":{"files":["c:\\Users\\danny\\Desktop\\DartSample\\bin\\main.dart"]}}
```

Can you try and reproduce this with logging enabled? Open User Settings (`CTRL`+`SHIFT`+`P` -> `User Settings`) and create `dart.analyzerLogFile` (note: the IDE will say it's invalid; it's not, it's just not documented) with a full filesystem path for a log file.

**Comment by DanTup** [comment]
@eseidel Can you still repro this? Are you able to get a log?

**Comment by DanTup** [comment]
I can't repro this, please comment back if you can.
