### ISSUE TITLE
Performance on mac, taking up multiple processors in activity monitor

### ISSUE THREAD

**Issue by gerryau** [Dart-Code/Dart-Code#2490]
I've recently noticed that Dart is taking up multiple processors in activity monitor and hogging a lot of memory, any ways to solve this, I am using VSCode.

![Screen Shot 2020-05-23 at 8 16 50 pm](https://user-images.githubusercontent.com/29995627/82728268-b04d4100-9d32-11ea-89b2-acd405eb5cc6.png)

**Comment by DanTup** [comment]
Are you able to get the command lines of any of these processes (eg. `ps -x | grep dart`)?
