### ISSUE TITLE
Closing labels use comment color

### ISSUE THREAD

**Issue by wwmyers** [Dart-Code/Dart-Code#2491]
Issue:
I really like the feature to auto add comments to point out where widgets end, but the selected color throws me off when I scan through my code to find a color that represents a certain feature in programming.

Solution / Request:
Is there a way to make the closing labels use the comment's color from the selected color theme?

**Comment by DanTup** [comment]
You can set the colour to anything you want using `workbench.colorCustomizations`:

```js
"workbench.colorCustomizations": {
    "dart.closingLabels": "#ff0000"
}
```

I don't know if you can easily set it to always be the comment colour for when you change themes though.

Let me know if this doesn't solve your issue!

**Comment by wwmyers** [comment]
That does solve this issue temporarily, but I'll have to update that line each time I change themes. Would still like it auto entered, but if not possible, I'm not going to cry about it lol

**Comment by DanTup** [comment]
I had a look, but unfortunately it doesn't seem like `colorCustomizations` supports reusing another named color. To support this, we'd have to change to using a standard setting, but that would prevent themes from being able to set the colors (which seems worse in other ways).

By default, we use `tab.inactiveForeground` (in the manifest, we *can* use named colors for the default) which was supposed to be something fairly subtle. If this looks particularly bad in any of the default themes, let me know and I'll take a look.

> Is there a way to change the fontStyle to the closingLabels as well?

Not currently. Only the colors support theming in VS Code, so supporting this would also involve using a basic string setting. If there's sufficient demand for it, we could add it - though I'm weary of adding too many settings - we do already have quite a lot!

**Comment by wwmyers** [comment]
cool, thanks a lot for your time. I'll go ahead and close this issue :) happy coding!
