### ISSUE TITLE
How to Show Color strength tooltip in Android Studio?

### ISSUE THREAD

**Issue by ryaninja** [Dart-Code/Dart-Code#2494]
I am following a flutter tutorial that is using Android Studio. When the instructor presses ctrl+q he gets a list of color examples like so: 

[What the instructor sees](https://i.stack.imgur.com/cunHL.jpg)  
[And this is what I see.](https://i.stack.imgur.com/FoMTT.jpgg)

I've searched, and only suggestions I've found suggest:

Preferences>Editor>General>Code Completion>Show the documentation popup
or 
Preferences>General>Other>Show quick documentation on mouse move.

Both are checked and have 500ms and 1000ms in the delay fields respectively but I still don't see the color list. No amount of turning one on and the other off, or changing their ms delay values seems to pop up the box with colors, only the text box. Pressing ctrl+q again simply opens the tooltip up in a tab in Android Studio.

Anyone know what I can do to fix this please?

**Comment by DanTup** [comment]
This repo is for the VS Code extensions. I'm not very familiar with Android Studio/IntelliJ. You could try asking in https://gitter.im/flutter/flutter or raising an issue at https://github.com/flutter/flutter-intellij/issues (my understanding is that Android Studio and IntelliJ use the same plugin).

The source of the previews is the [dartdocs on the colors](https://github.com/flutter/flutter/blob/fabf4e3d0d311181178d2c601d29a2f739ea543a/packages/flutter/lib/src/material/colors.dart#L420-L446), but I'm not sure if you need something in IntelliJ/Android Studio for it to render them.

**Comment by ryaninja** [comment]
Hi @DanTup , thanks for your reply, very much appreciated! Sorry for posting here, I'm very new to flutter/IDEs and coding and I'm still getting used to what bit belongs to what!  

This information you've given me will certainly help me form a more specific and less vague question, and you've pointed me towards a couple of good resources to ask these questions on, so thanks again!

**Comment by DanTup** [comment]
@ryaninja not a problem! It's not always obvious what belongs where (especially when it comes to editor functionality, where much of the editor features are powered by tools in the SDK), so it's not uncommon for issues to start in other repositories and get moved around!

Hope you're able to find the answer!
