### ISSUE TITLE
Intellisense showing private members outside class

### ISSUE THREAD

**Issue by JCKodel** [Dart-Code/Dart-Code#2495]
![image](https://user-images.githubusercontent.com/379339/82848644-db6a9880-9eca-11ea-985a-b7cc992bab91.png)

This should not happen. (It didn't, until last update)

**Comment by DanTup** [comment]
Can you post an example of how this is set up? Variables starting with `_` in Dart are not private to a class, but private to a library - so it's not uncommon for them to show up outside of the class if you're still inside the same library.

Can you also confirm if you're using the LSP preview or not, as there are differences in where the completion list comes from there.

Thanks!

**Comment by JCKodel** [comment]
When the intellisense is for an object that have private members, no private members are listed (as always):

![image](https://user-images.githubusercontent.com/379339/82902842-75b3f600-9f36-11ea-890c-2df66b152913.png)

This behavior is for static members in the last update:

![image](https://user-images.githubusercontent.com/379339/82848644-db6a9880-9eca-11ea-985a-b7cc992bab91.png)

The code is:
```dart
class Data {
  Data._();

  static final Data _instance = Data._();
  static Data get instance => _instance;
}
```

This is the same code from MacOS, on a not updated VSCode:
![image](https://user-images.githubusercontent.com/379339/82903771-d3950d80-9f37-11ea-8494-c98ec461e93e.png)

**Comment by JCKodel** [comment]
When the intellisense is for an object that have private members, no private members are listed (as always):

![image](https://user-images.githubusercontent.com/379339/82902842-75b3f600-9f36-11ea-890c-2df66b152913.png)

The class above have private members:

```dart
/* —————————————————————————————————————————————————————————————————————————— */
class UserModel extends ChangeNotifier {
  UserModel._() {
    FirebaseAuth.instance.onAuthStateChanged.listen((firebaseUser) => _onAuthStateChanged(firebaseUser));
  }

  static final UserModel _instance = UserModel._();
  static UserModel get instance => _instance;

// #region Props

  bool _isReady = false;
  bool get isReady => _isReady;

  User _authenticatedUser;
  User get authenticatedUser => _authenticatedUser;
...
```

This behavior is for static members in the last update (I guess):

![image](https://user-images.githubusercontent.com/379339/82848644-db6a9880-9eca-11ea-985a-b7cc992bab91.png)

The code is:
```dart
class Data {
  Data._();

  static final Data _instance = Data._();
  static Data get instance => _instance;
}
```

I don't remember seeing a private member in intellisense before, but I'm not 100% sure =\

Also, if private members are private for the library, why they don't appear in the variable intellisense? (please, don't "fix" this, private members are NOT welcome in the intellisense, doesn't matter if Dart is duhhh or not about it) =P

**Comment by DanTup** [comment]
The completion all comes from the server, so I don't believe a VS Code/Dart-Code update would change this. A Dart/Flutter SDK surely should though.

However, the behaviour I'm seeing seems consistent with what I'd expect - inside the library, it shows up:

<img width="457" alt="Screenshot 2020-05-26 at 14 19 58" src="https://user-images.githubusercontent.com/1078012/82905686-14068280-9f5c-11ea-99d2-a5db7e56383d.png">

But outside the library it does not:

<img width="423" alt="Screenshot 2020-05-26 at 14 20 32" src="https://user-images.githubusercontent.com/1078012/82905694-1537af80-9f5c-11ea-9f4d-3e33da655b27.png">

Assuming this is the same as you're seeing, it's not feasible to just hide them here, as it's perfectly valid to access them (and a lot of code does).

If you want the field to e private, could you not move the class to its own library?

**Comment by DanTup** [comment]
This came up again, for a pub package class so it's definitely not WAI.

https://twitter.com/luke_pighetti/status/1267495665011228674

**Comment by JCKodel** [comment]
> This came up again, for a pub package class so it's definitely not WAI.
> 
> https://twitter.com/luke_pighetti/status/1267495665011228674

Another behavior that goes against Dart documentation (by the way, I (and the world) don't care about Dart, we do care about Flutter =) ):

```dart
/* —————————————————————————————————————————————————————————————————————————— */
  Future<void> _onAuthStateChanged(FirebaseUser firebaseUser) async {
    if (firebaseUser == null) {
      _authenticatedUserId = null;
      await _onSignOut();
    } else {
      _authenticatedUserId = firebaseUser.uid;
      await _onSignIn(firebaseUser);
    }

    notifyListeners();
  }

/* —————————————————————————————————————————————————————————————————————————— */
  @protected
  Future<void> _onSignOut() async {}

/* —————————————————————————————————————————————————————————————————————————— */
  @protected
  Future<void> _onSignIn(FirebaseUser firebaseUser) async {}
```

If `_` is "public to the library", why this code won't work in the same library?

![image](https://user-images.githubusercontent.com/379339/83432432-3f331b00-a40f-11ea-88b8-71e603f43d8b.png)
(this image is from an inherited class, in the same FOLDER).

So, clearly, as long as Flutter is concerned, `_` is private.

Just reporting as a user point of view. ;-)

**Comment by lukepighetti** [comment]
repro

```dart


import 'package:file_picker/file_picker.dart';

main(){
  var thing = FilePicker.
}
```

<img width="613" alt="Screen Shot 2020-06-01 at 1 02 20 PM" src="https://user-images.githubusercontent.com/666539/83434268-21ae8300-a408-11ea-9f26-03ac806018bd.png">

**Comment by DanTup** [comment]
@JCKodel 

> (this image is from an inherited class, in the same FOLDER).

Just to make sure we're on the same page, a library in Dart is not the same as a package. Usually a library is a single file (though I think things are a little more complicated with `library` and `parts`).

From the discussion above, I believed your report was that this was happening within the same library (eg. file), in which case it's what I would expect. If that wasn't the case, sorry for misunderstanding.

Luke's example is in another *package* so it's definitely wrong, so I'll take a look. The behaviour of code completion must match exactly how the compiler/analyzer behaves. You should never see anything in completion that would result in an error if you selected it, and you should also never not-see something that would be valid to type.

I'll do some digging and post back (I have an idea of what it might be, but need to do some testing).

**Comment by JCKodel** [comment]
> From the discussion above, I believed your report was that this was happening within the same library (eg. file), in which case it's what I would expect. If that wasn't the case, sorry for misunderstanding.
> 

I misunderstood you. You said "library" I read "package". Blame Dart's confusing terms =P

Just to clarify: all my files are in the same Flutter project (no packages folders, nothing, all inside lib folder) and the last screenshot was two files apart in the same folder. The opening issue was the same: I using a class from another folder (but in the same project).

`_` for same folder is OK (stateful widgets are an example of this).

```dart
class Public {
  Public() {
    _Private.something(); // Makes sense
    _Private._privateVar; // Does not make sense, but if it valid, ok
  }
}

class _Private {
  static int _privateVar;

  static void something() {}
}
```

**Comment by DanTup** [comment]
Ok, I think we're all on the same page now :-)

However, I'm unable to repro @lukepighetti's sample here using Flutter 1.19.0-2.0.pre.214:

<img width="599" alt="Screenshot 2020-06-02 at 15 49 58" src="https://user-images.githubusercontent.com/1078012/83534543-e637b580-a4e8-11ea-8c6b-7b08fcf401cd.png">

Can you confirm:

- Exact Dart/Flutter version
- Whether it's a Dart or Flutter project
- Whether you have `previewLsp` enabled or not? (I tried both, but no change for me)

**Comment by JCKodel** [comment]
Case 1: abstract class with private members and concrete class in the same file.
![image](https://user-images.githubusercontent.com/379339/83535833-d6a87480-a4c8-11ea-8d84-448b3fd402c2.png)

```dart
class ConcreteClass extends AbstractClass {
  ConcreteClass() {
    super._privateMember = 5;
  }
}
```

Seems valid and compile without errors.

---

Case 2: concrete class moved to a separate file in the same folder:
![image](https://user-images.githubusercontent.com/379339/83536012-166f5c00-a4c9-11ea-8048-e44a2f515654.png)

(Oh, Dart... you're a little nasty thing)

![image](https://user-images.githubusercontent.com/379339/83536109-3272fd80-a4c9-11ea-9bb4-8907a4b5d220.png)

No private intellisense displayed in this case.

Case 3: (same as 1, but using static members)
![image](https://user-images.githubusercontent.com/379339/83537281-baa5d280-a4ca-11ea-9290-d51ba23c9478.png)

Code is valid as well.

Case 4 (same as 2, but using static members)

![image](https://user-images.githubusercontent.com/379339/83536375-8382f180-a4c9-11ea-9a63-d7c87f09e0b5.png)

Object member (non static) is private, but class member (static) is public.

Ok, Dart, go home. You're drunk.

Case 5:
In the same file as above (separated concrete_class.dart), file_picker gives me this:

![image](https://user-images.githubusercontent.com/379339/83536548-be852500-a4c9-11ea-8a48-e921180e4bfe.png)

But this isn't valid, accordingly to our drunk friend:

![image](https://user-images.githubusercontent.com/379339/83536625-dc528a00-a4c9-11ea-9f3a-2e2367cafe87.png)

My environment:

Windows 10 using VSCode 1.45.1 (user setup)
This is a newly empty project created with `flutter create intellisense`.

> Exact Dart/Flutter version
>
```yaml
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^1.9.0+1
```

Flutter doctor: (using beta because of web support)
```
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Microsoft Windows [Version 10.0.19041.208], locale pt-BR)
    • Flutter version 1.18.0-11.1.pre at C:\flutter
    • Framework revision 2738a1148b (3 weeks ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\jckod\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.45.1)
    • VS Code at C:\Users\jckod\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[✓] Connected device (6 available)
    • XT1033                    • 0423490246      • android-arm    • Android 5.0.2 (API 21)
    • SM J415G                  • 785dd05b        • android-arm    • Android 9 (API 28)
    • ASUS Z00UD                • G7AZB6026545GU7 • android-arm64  • Android 6.0.1 (API 23)
    • Android SDK built for x86 • emulator-5554   • android-x86    • Android 10 (API 29) (emulator)
    • Web Server                • web-server      • web-javascript • Flutter Tools
    • Chrome                    • chrome          • web-javascript • Google Chrome 83.0.4103.61

• No issues found!
```

> Whether it's a Dart or Flutter project
>
There is people who uses Dart by choice? O.o
It's a Flutter project.

> Whether you have previewLsp enabled or not? (I tried both, but no change for me)
>
Never touched this option, so, it is default.

Setting it to `false` and restarting VSCode, the last case remains the same (FilePicker shows private members).

Setting it to `true`, no changes.

**Comment by DanTup** [comment]
Great, thanks! I was able to repro using the version above. It turns out the issue has since been fixed (which is why I couldn't repro on `master`) here:

https://github.com/dart-lang/sdk/commit/3a764b7ae4d90d1fc261e868b4fc909822aa2d0a

So looks like there's nothing to do here, and hopefully the fix will land in the versions you're using soon.
