### ISSUE TITLE
autocomplete to add import

### ISSUE THREAD

**Issue by bsutton** [Dart-Code/Dart-Code#2498]
Imports are one of the my biggest friction points with dart-code.
It occurs to me that part of the problem can be solved via the autocomplete mechanism.

When you initiate an auto complete you select an offered class.
At this point dart-code hopefully knows what the required import is.
It would greatly improve efficiency if the import was automatically added at this point.

**Comment by DanTup** [comment]
I don't entirely understand the request. We do already automatically insert imports when you select classes in code completion that are not already imported - there are some notes on this here:

https://dartcode.org/releases/v2-26/#auto-importing-from-code-completion

Is this not what you see? Classes that are not already imported should *only* show up in code completion if we're going to also auto-import them when you select them. We should never leave you with an unresolved symbol after completing it.

**Comment by bsutton** [comment]
I'm going to have to experiment with this one some more.
Some quick tests confirms your statement that the package is imported but that hasn't been my impression.
One issues is that it always uses the 'package' import.
It would be nice if it checked for the lint 'prefer_relative_imports' and acted accordingly.

**Comment by DanTup** [comment]
Ok, let me know if you manage to repro it not working and I'll take a look.

> One issues is that it always uses the 'package' import.

Yep, that's what was touched on in https://github.com/Dart-Code/Dart-Code/issues/2485#issuecomment-634005505 and is being tracked in https://github.com/dart-lang/sdk/issues/32916.
