### ISSUE TITLE
Dart DevTools exited with code 1

### ISSUE THREAD

**Issue by beilly** [Dart-Code/Dart-Code#2502]
Dart DevTools exited with code 1

Flutter 1.9.1+hotfix.4 • channel unknown • unknown source
Framework • revision cc949a8e8b (8 months ago) • 2019-09-27 15:04:59 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0

dart plugin: 3.10.2
flutter plugin: 3.10.2

**Comment by beilly** [comment]
@DanTup  https://github.com/Dart-Code/Dart-Code/issues/2486#issuecomment-633922985

**Comment by DanTup** [comment]
Great, glad it's sorted! I've opened https://github.com/Dart-Code/Dart-Code/issues/2503 to try and handle this better in future. Thanks!
