### ISSUE TITLE
Users in China do not get automatic updates for DevTools

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#2503]
See #2486 and #2502. If the Pub website is blocked, the API check for versions will also fail, and we'll never update.

Some possible options:

- Call the API on pub.flutter-io.cn (if supported) if the first request fails
- Always try to update DevTools in the background at startup (note: this might mess with people using locally-activated versions)
- Periodically prompt the user to update ("Unable to check for updates, install latest version?" or similar)

**Comment by beilly** [comment]
Give a option setting API on pub.flutter-io.cn, and default pub.dev. Otherwise, always update manually

**Comment by DanTup** [comment]
Looks like we don't need a setting - we can just read `PUB_HOSTED_URL` which should already be set by users in China for Flutter/pub to work correctly (see https://flutter.dev/community/china) :-)
