### ISSUE TITLE
Couldn't find a compatible version of Flutter with this version of Code

### ISSUE THREAD

**Issue by papa0four** [Dart-Code/Dart-Code#2504]
I am trying to install the flutter extension with VSCode and get the following error:
Couldn't find a compatible version of Flutter with this version of Code.

I have tried the following:
Android Studio installed with dart/flutter extensions
Install Dart extension in vscode
Install flutter on windows machine and setup env path to flutter/bin
update vscode to ensure I have most current stable version.

Cannot find a forum that discusses simply not being able to install Flutter, only ones that show a how to, which I follow and when I go to the Flutter extension to install, it simply won't and shows the aforementioned error...

What am I doing wrong?

**Comment by DanTup** [comment]
From the message, it sounds like you have an old version of Code installed that the Flutter extension doesn't work with. Can you copy the version info from Help -> About Code and paste it here?

**Comment by papa0four** [comment]
Says version 1.15.1 --- mine....
so sounds like maybe uninstall code and reinstall new version?

**Comment by DanTup** [comment]
That's definitely a very old version - the current version is 1.45.1.

Usually there's a way to make it auto-update, but if it's really old, maybe it didn't have auto-update. In that case, uninstall/reinstall would be the best thing, yep.

Let me know if it works after upgrading. Thanks!

**Comment by papa0four** [comment]
yup that fixed it I appreciate your help, I thought when I tried to manually update it I worked the first time but apparently not. thanks again!

**Comment by DanTup** [comment]
Great, glad you sorted it!
