### ISSUE TITLE
Flutter Formatting Sometimes Indenting to 4 spaces instead of 2 

### ISSUE THREAD

**Issue by mclean25** [Dart-Code/Dart-Code#2509]
I seem to get inconsistent indentations using the Dart Code formatter:

![image](https://user-images.githubusercontent.com/7105182/83334851-246d7480-a25e-11ea-8ad9-c8ae2c2e21fb.png)

Note how the args for `OutlineInputBorder` go to 4 spaces instead of 2 for some reason. 

My `settings.json` includes:

```
  "[dart]": {
    "editor.tabSize": 2,
    "editor.insertSpaces": true,
    "editor.detectIndentation": true
  },
```

**Comment by mclean25** [comment]
I see now that this is a duplicate of this [issue](https://github.com/Dart-Code/Dart-Code/issues/1962). IMO this is fairly strange.

**Comment by DanTup** [comment]
This is how (non-Flutter) Dart code was usually formatted. Trailing commas were added as a signal to the formatter that the code should be formatted differently (in a way that worked better for Flutter code).

Dart-Code doesn't do any formatting itself, it just uses [the SDK formatter dart_style](https://github.com/dart-lang/dart_style) so it's not simple to change this without first implementing a formatter (something there's [an open issue](https://github.com/Dart-Code/Dart-Code/issues/914) for but isn't being actively worked on).

Hope this makes sense!
