### ISSUE TITLE
You have a breakpoint outside of your workspace... But I don't

### ISSUE THREAD

**Issue by lukepighetti** [Dart-Code/Dart-Code#2512]
Getting the `You have a breakpoint outside of your workspace...` error but I don't appear to have any breakpoints set. Any ideas?

<img width="993" alt="Screen Shot 2020-05-31 at 2 15 22 PM" src="https://user-images.githubusercontent.com/666539/83359603-48f24b00-a349-11ea-9531-2957e7ffffb8.png">

It's possible that I did have one set, then removed it, and the dialog asks at startup?

**Comment by DanTup** [comment]
@lukepighetti what's the `config_state.dart` breakpoint? I notice it has a full path (starting `/Users`) rather than relative - is that outside of the workspace?

**Comment by lukepighetti** [comment]
It's disabled though?

**Comment by DanTup** [comment]
Oh, I see! That's fair :) I think the reminder is still somewhat valid (the breakpoint isn't going to work if you enable it), but delaying it until it's enabled seems a reasonable change. Thanks!

**Comment by lukepighetti** [comment]
Thanks Dan!
