### ISSUE TITLE
[Quick Fixes] Show old Path also

### ISSUE THREAD

**Issue by bounty1342** [Dart-Code/Dart-Code#2517]
![image](https://user-images.githubusercontent.com/6307253/83624810-6581c380-a593-11ea-832f-182f498cfaf6.png)

Quick Fixes show both the new path and the old path (not present anymore).

Probably link to the new move feature. (Move severals files in the same time)

**Comment by DanTup** [comment]
Do you have steps to repro this? I tried moving a file and then opening a quick-fix for importing it but it only had the new path. Thanks!
