### ISSUE TITLE
(--dart-define + restart) isn't working as expected

### ISSUE THREAD

**Issue by macabeus** [Dart-Code/Dart-Code#2521]
Thank your for this awesome plugin, but I think that there is a bug on this plugin (or with Dart, I don't know).

I created three configurations to run my project with different environments:
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Flutter - Local",
      "request": "launch",
      "type": "dart",
      "args": ["--dart-define=APP_ENV=local"]
    },
    {
      "name": "Flutter - Staging",
      "request": "launch",
      "type": "dart",
      "args": ["--dart-define=APP_ENV=staging"]
    },
    {
      "name": "Flutter - Production",
      "request": "launch",
      "type": "dart",
      "args": ["--dart-define=APP_ENV=production"]
    }
  ]
}
```

So I could switch easily between the environments.

But if I run with debug using `Flutter - Staging` or `Flutter - Production` and restart the app, is changed to `local`. But the expected behaviour is keep the same `--dart-define` flags after restart.

In `main()` function I have that:

```
const appEnv = String.fromEnvironment("APP_ENV");
print('Running with environment "$appEnv"');
```

So is printed at the first time:

```
flutter: Running with environment "staging"
```

and after one restart:

```
flutter: Running with environment "local"
```

**Comment by DanTup** [comment]
Thanks for the report! Just to clarify - when you say restart, to you mean using the green Restart arrow (Hot Restart) on the debug toolbar? If you stop the debug session and start a new one, then it does work as expected?

**Comment by macabeus** [comment]
@DanTup Thank you for the quick reply.

> when you say restart, to you mean using the green Restart arrow (Hot Restart) on the debug toolbar?

Yeah, I'm saying about the green button on the debug toolbar.
![image](https://user-images.githubusercontent.com/9501115/83894095-c272aa80-a748-11ea-915f-fb7090414ffb.png)

> If you stop the debug session and start a new one, then it does work as expected?

Yes. If I stop the debug session and start a new one, it'll work as expected.

**Comment by DanTup** [comment]
Thanks - I could repro this, even from the terminal. It sees like something stale is hanging around in Flutter (though I'm not sure why it only appears int he reload). I've filed an issue here:

https://github.com/flutter/flutter/issues/58976

Since it happens from the terminal, I don't think there's anything to do in the VS Code extension, so I close this in favour of that one - subscribe there for updates. Thanks!
