### ISSUE TITLE
autocomplete / compilation errors not functioning for flutter plugin template example

### ISSUE THREAD

**Issue by gaaclarke** [Dart-Code/Dart-Code#2522]
**Description:**
Dart Code isn't providing any of the assistance while editing the dart file for my plugin's example project.  If I open a typical flutter project, like the one created with `flutter create`, the tools function as expected.

**reproduction steps:**
I'm not 100% sure these reproduction steps are complete:

1) `flutter create -t plugin -i objc -a java host_router`
1) `code host_router`
1) open `example/lib/main.dart`, edit it, notice no assistance
1) `code host_router/example`
1) open `lib/main.dart`, edit it, notice no assistance

**code version:**
```
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z (3 wks ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

**flutter version:**
```
[✓] Flutter (Channel master, 1.19.0-4.0.pre.78, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.19.0-4.0.pre.78 at /Users/aaclarke/dev/flutter
    • Framework revision 1e4d9f8502 (42 minutes ago), 2020-06-05 11:01:23 -0700
    • Engine revision e87a05fbba
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 62903873df)
```

**dart code version:** `3.11.0`

**Comment by DanTup** [comment]
I don't seem to be able to repro this using the same version and the instructions above:

<img width="472" alt="Screenshot 2020-06-08 at 10 21 14" src="https://user-images.githubusercontent.com/1078012/84014228-e6650480-a971-11ea-9fad-ed2f35b0010c.png">

Could you check the dev tools (Help -> Toggle Developer Tools -> Console) and see if there are any errors listed there?

An [analysis server log](https://dartcode.org/docs/logging/#analyzer) might be useful to see if the server isn't responding correctly.

We've seen some issues in the past where there were circular symlinks (which I think was plugin related), the server would end up walking over them endlessly. I can't find the original issue, but I found https://github.com/dart-lang/sdk/issues/42079 in the SDK repo which looks like i's describing the same behaviour (though I'm not sure why I'm not seeing it - is there some step missing that generates the symlinks?)

**Comment by DanTup** [comment]
Found the original issue:

https://github.com/dart-lang/sdk/issues/36919

It was fixed in the SDK, and the fix still seems to be there, so I'm not sure why it's happening again.

If you have a `ios/.symlinks` folder hough, we can probably close this as a dupe of https://github.com/dart-lang/sdk/issues/42079 and investigate there.

**Comment by gaaclarke** [comment]
@DanTup 

The errors in the console don't seen apropos:
```
abstractExtensionService.ts:485 Extension 'ms-dotnettools.csharp cannot use PROPOSED API (must started out of dev or enabled via --enable-proposed-api)
updateEnableProposedApi @ abstractExtensionService.ts:485
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.kotlin.
Old grammar file: file:///Users/aaclarke/.vscode/extensions/fwcd.kotlin-0.2.14/resources/syntaxes/Kotlin.tmLanguage.json.
New grammar file: file:///Users/aaclarke/.vscode/extensions/mathiasfrohlich.kotlin-1.7.1/syntaxes/Kotlin.tmLanguage
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope markdown.kotlin.codeblock.
Old grammar file: file:///Users/aaclarke/.vscode/extensions/fwcd.kotlin-0.2.14/resources/syntaxes/codeblock.json.
New grammar file: file:///Users/aaclarke/.vscode/extensions/mathiasfrohlich.kotlin-1.7.1/syntaxes/codeblock.json
register @ TMScopeRegistry.ts:45
console.ts:137 [Extension Host] Failed to connect to provider "No token found for host github.com"
notificationsAlerts.ts:40 The .NET Core SDK cannot be located. .NET Core debugging will not be enabled. Make sure the .NET Core SDK is installed and is on the path.
onDidChangeNotification @ notificationsAlerts.ts:40
log.ts:197   ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
```

I do have a symlinks directory.  I don't see any circular symlinks.

```
aaclarke-macbookpro2:host_router aaclarke$ find example/ios/.symlinks -exec ls -l {} \;
total 0
drwxr-xr-x  3 aaclarke  primarygroup  96 Jun  5 15:32 plugins
total 0
lrwxr-xr-x  1 aaclarke  primarygroup  31 Jun  5 15:32 host_router -> /Users/aaclarke/dev/host_router
lrwxr-xr-x  1 aaclarke  primarygroup  31 Jun  5 15:32 example/ios/.symlinks/plugins/host_router -> /Users/aaclarke/dev/host_router
aaclarke-macbookpro2:host_router aaclarke$ 
```

Here is my server log:
[dartcode.log](https://github.com/Dart-Code/Dart-Code/files/4747886/dartcode.log)

**Comment by DanTup** [comment]
I think this is circular?

```
lrwxr-xr-x  1 aaclarke  primarygroup  31 Jun  5 15:32 host_router -> /Users/aaclarke/dev/host_router
```

It looks like `host_router` goes back up to `../../` which means the server can walk forever:

> /Users/aaclarke/dev/host_router/example/ios/.symlinks/host_router/example/ios/.symlinks/host_router/example/ios/.symlinks/host_router/example/ios/.symlinks/host_router/example/ios/.symlinks/host_router/example/ios/.symlinks

This was fixed in the past (at least, if I understand the issue linked above correctly) so I'm not sure why it's happening again.

Do you know what triggers the creation of `ios/.symlinks`? (though I guess I could just link it manually to debug).

Your log does seem consistent with this - the server starts analyzing and then just never responds anymore (probably because it's stuck in a loop).

**Comment by DanTup** [comment]
Ok, I was able to get the symlink to be created, and it's definitely circular:

```
danny@Dannys-MBP host_router % pwd
/tmp/host_router/example/ios/.symlinks/plugins/host_router/example/ios/.symlinks/plugins/host_router/example/ios/.symlinks/plugins/host_router
```

However, I can open the project and use the server just fine.

Something you could try.. add the following to VS Code settings (be sure to remove them afterwards):

```
  "dart.analyzerAdditionalVmArgs": [
  	"--pause-isolates-on-exit",
  ],
  "dart.analyzerObservatoryPort": 8181,
```

Open the project so it gets stuck, then run the **Dart: Open Observatory** command in VS Code. Then on the Debugger screen, see if you can get a stack trace of the running isolate to see where it is/what it's doing.

**Comment by gaaclarke** [comment]
@DanTup  "Dart: Open Observatory"  isn't an available command to me.

**Comment by DanTup** [comment]
@gaaclarke ugh sorry - what I wrote above wasn't correct. Open Observatory opens observatory for your current debug session, not the analysis server. Because of the auth tokens, you'll need to get the Observatory URL from the log file. So if you also set a log path for the analysis server, like:

```js
"dart.analyzerLogFile": "M:\\Coding\\Applications\\Dart-Code\\analyzer.log",
```

Then open this file once the server has started, there should be a line somewhere like "Observatory is listening at http://127.0.0.1:8181/S0m3T0k3N=" which you can paste into your browser to load Observatory for the analysis server.

Sorry for the confusion!
