### ISSUE TITLE
Visual Studio code does not automatically detect the Android device for debugging

### ISSUE THREAD

**Issue by KBola98** [Dart-Code/Dart-Code#2523]
When I run the command **Flutter run** the app works on the device. But to debug the visual studio does not detect the device automatically.

What can I do for this issue?

**Comment by DanTup** [comment]
> But to debug the visual studio does not detect the device automatically.

Can you clarify exactly what this means? Does the device not show in the status bar, or do you get an error when trying to launch the application?

**Comment by KBola98** [comment]
Everything was fine after updating the Flutter version.

**Comment by DanTup** [comment]
Ok great - if you see it again please do let me know!
