### ISSUE TITLE
Toggle Inspect Widget off

### ISSUE THREAD

**Issue by aayushbisen** [Dart-Code/Dart-Code#2526]
Is there any way to toggle Inspect Widget off from within Visual Studio Code?

**Comment by DanTup** [comment]
There's a **Flutter: Cancel Widget Inspection** command that should become available (in the VS Code command palette) when you're in inspect widget mode. Does this show up for you?

**Comment by aayushbisen** [comment]
Yes, it does! Exactly what I'm looking for. Thanks

**Comment by DanTup** [comment]
Great! 🙂
