### ISSUE TITLE
add preference to show/hide deprecation warnings

### ISSUE THREAD

**Issue by skybrian** [Dart-Code/Dart-Code#253]
It seems like this would be similar to the preference for TODO's.

Justification: a large number of deprecation warnings can show up suddenly due to changes outside your control (in a dependency) and hide other errors.

**Comment by DanTup** [comment]
@devoncarew How do you do this in Atom? For TODOs we can use the `type` property of the `AnalysisError`, but I can't see anything in the spec that would allow us to detect deprecation errors?

**Comment by skybrian** [comment]
Sorry, I misremembered. It's not there in Atom. (Deleted that sentence.) I think I just disabled infos.

In theory you could look for the unique id for deprecation warnings: DEPRECATED_MEMBER_USE. But this could also be disabled in the analysis options file.

**Comment by DanTup** [comment]
If it's possible to disable these using the analysis options file, I'm not sure if it's worth adding an option here. I know the analysis options file can't apply globally, but this seems like the sort of thing you probably want per-project and if we start adding things that can be configured there, we might end up with a load of duplication (and confusion, if you forget it's set in Code user settings there and toggling the options file doesn't seem to work).

So, to keep things simpler I think this should be WontFixed (if TODOs can be controlled in analysis options, I also think maybe we should remove that option) but I'm interested in others thoughts on this! (cc @devoncarew).

I would like to add completion for the options file though I'm not sure if that's best done manually or should be something the analysis server does (I've got #114 about that).

**Comment by skybrian** [comment]
Makes sense. Thanks!

**Comment by devoncarew** [comment]
+1 to relying on the analysis options file here.

Some things we may want to be user preferences rather than commit-to-the-repo settings; perhaps TODOs fit in this category. But generally I'm a fan of having few preferences, so wouldn't complain too much if the todo checkbox went away.

**Comment by DanTup** [comment]
Ok, I'm gonna close this as WontFix as I think the analysis_options file is a better fit. I won't do anything with the TODOs setting for now, but might remove it in the future (esp. if we get completion for the analysis options and it becomes easier to encourage people to use it).
