### ISSUE TITLE
sources not found for async code in web directory

### ISSUE THREAD

**Issue by alanknight-wk** [Dart-Code/Dart-Code#2532]
To reproduce
Take the example in src/test/test_projects/web/hello_world/lib/src/todo_list
modify main.dart so that main looks like 

void main() async {

  runApp(ng.AppComponentNgFactory);
    Future.delayed(Duration(seconds: 1)).then((_) {
      print('doing something later');
    });
}

put a breakpoint on the print. Call stack looks like
![image](https://user-images.githubusercontent.com/63246623/84077002-b84ce800-a9a4-11ea-9c84-e3894ade1dbb.png)

**Comment by DanTup** [comment]
@grouma @jakemac53 this is happening because the path to the script (in the response to `getStack`) is `org-dartlang-app:///`:

```js
"location": {
	"type": "SourceLocation",
	"script": {
		"type": "@Script",
		"id": "1040",
		"uri": "org-dartlang-app:///web/main.dart"
	},
	"tokenPos": 1349
},
```

There was a bit of discussion about this at https://github.com/dart-lang/webdev/issues/350 but it's been a while and I don't really understand the conclusion. Should this be mapped by dwds before sent to the client, or are there still unanswered questions about these paths?

**Comment by grouma** [comment]
I thought we settled on VS Code understanding `org-dartlang-app` URIs? That is these URI's are relative to the workspace root.

**Comment by annagrin** [comment]
Some questions:

- Will making VSCode do the translation repeat the work that is already done somewhere else (asset server, for example), and is it really necessary? 

- Is doing this translation in multiple tools justified (for example, performance, less dependencies, etc)?

- Will VSCode even know how to translate those uris, for example, if the file system is on another machine? 

- Do I understand correctly that the asset server knows how to translate `org-dartlang-app:` Uri to the `file:` uri? And the same for `package:` uris? 

- If we still want VSCode to understand `org-dartlang-app:` and `package:` uris, could we give VSCode access to this translation via calling a debugger API? 
We could hide all the translation work behind some API (DebugInfo) and implement it for different scenarios. In frontend server case, for example, the translation is already known from the asset server APIs and the compiler metadata (work in progress)

**Comment by DanTup** [comment]
> I thought we settled on VS Code understanding `org-dartlang-app` URIs? 

From re-reading https://github.com/dart-lang/webdev/issues/350 I don't think we really came to a conclusion. The last suggestion was using file URIs and adding a human-friendly URI field if I understand correctly (https://github.com/dart-lang/webdev/issues/350#issuecomment-502251311).

I do think it would be better to keep all the translation in one place centrally than require each editor to do it. We've had issues in the past with differences between file/package URIs (for example having to send breakpoints multiple times, once with each URI type) so over time the VM started accepting file URIs everywhere. Supporting `org-dartlang-app:` URIs seems like it might reintroduce some of those issues.

(also - I don't think VM apps send `org-dartlang-app` - isn't it better to be consistent across the runtimes?)
