### ISSUE TITLE
Loop with async operation appears in debugger as recursive calls with async gap

### ISSUE THREAD

**Issue by alanknight-wk** [Dart-Code/Dart-Code#2533]
Create a stagehand simple-web app. Modify main.dart to be

import 'dart:html';
import 'package:new_scratch/stuff.dart';

void main() {
  querySelector('#output').text = 'Your Dart app is running.';
  foo();
}

and add a stuff.dart file with 

foo() async {
  for (var i = 0; i < 20000; i++) {
    await Future.delayed(Duration(seconds: 2));
    print('abc');
  }
}

Put a breakpoint on the print statement and continue through it a few times. The call stack show as 
<img width="495" alt="Screen Shot 2020-06-08 at 4 48 09 PM" src="https://user-images.githubusercontent.com/63246623/84079071-e8e25100-a9a7-11ea-8994-742abe0618e0.png">

**Comment by DanTup** [comment]
I think this is coming from Chrome, as the call stack there also shows the duplicates:

![Screenshot 2020-06-25 at 09 24 11](https://user-images.githubusercontent.com/1078012/85684200-ce0d1d80-b6c5-11ea-993b-2531ded51a73.png)

Perhaps it's related to how V8 handles async loops like this (with some sort of state machine?). The standard VM doesn't do it though, so I'm not sure whether the proxy could/should collapse it.

@grouma @jakemac53 any thoughts on this?

**Comment by grouma** [comment]
`package:dwds` is simply translating what you see from Chrome. @markzipan may have some thoughts on how to change the JS internals.

**Comment by Markzipan** [comment]
AFAIK this is a side effect of how the Timer is implemented on the web and seems consistent with Dart2JS. Timers basically recursively

**Comment by DanTup** [comment]
Ok, sounds like this is expected behaviour. If it could be improved, that'd have to be done in Dart - there's nothing we can do from the VS Code extension.
