### ISSUE TITLE
"Error: Permission denied (publickey)" while pub get Private Github Repo in VS Code Flutter

### ISSUE THREAD

**Issue by vin-fandemand** [Dart-Code/Dart-Code#2543]
I wanted to add a private repo from Github to my dependencies. As per the [https://dart.dev/tools/pub/dependencies#git-packages](https://dart.dev/tools/pub/dependencies#git-packages ) , I added the SSH link from Github in my dependencies. For that 

1. I configured the SSH key and added it to Github as per [Github's guidelines](https://help.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh).
2. I tested the connection  running `ssh -vT git@github.com` and got welcome message
3. My config
```
Host *
 HostName github.com
 User git
 IgnoreUnknown AddKeysToAgent,UseKeychain
 UseKeychain yes
 AddKeysToAgent yes
 IdentityFile ~/.ssh/id_rsa
```
Despite all this, I kept getting "Error: Permission denied (publickey)" in VSCode, when I try to do `pub get`. After a long night and frustration, when I was about to give up, I decided to do `pub get` in `git bash` , and it worked. To me, it seems this is some kind of OS problem and VSCode is looking for the key in some other place. On the other hand, any change to the config file is reflected in VSCode logs.

I have a work around for this now. But one would wish the functionality to work in VSCode as well.

Please let me know if this is the right repository to raise the issue.
[https://github.com/flutter/flutter/issues/59073](https://github.com/flutter/flutter/issues/59073)

**Comment by vin-fandemand** [comment]
It didn't work when I launched VS Code from terminal. It worked when I added a Git bash terminal in VSCode and ran the ssh-add before pub get. I think that is a better work around.

Any thoughts on how to handle this in CI/CD , like say while building in Github Actions?

**Comment by DanTup** [comment]
> It didn't work when I launched VS Code from terminal.

To clarify - you ran the commands so that it worked from the terminal, but when if you launched VS Code from that same terminal, the built-in **Dart: Get Packages** command still failed?

> Any thoughts on how to handle this in CI/CD , like say while building in Github Actions?

It's not something I've done, but this project might be useful (I can't vouch for it though, so do your own research):

https://github.com/webfactory/ssh-agent
