### ISSUE TITLE
Incorrect color on line number

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [Dart-Code/Dart-Code#2545]
![](https://e-six-two.one/i/3btaw94g.png)

This green is here for some reason, no clue why.
Windows 10, latest version of VS Code and Flutter extension as of writing. Removing the comments makes the green go away.

**Comment by DanTup** [comment]
The comment contains `Colors.green` and right now this uses a naive regex.

There's another issue open about this at #2167 so I'll close this as a dupe. Thanks for the report!
