### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by samsheldin** [Dart-Code/Dart-Code#2546]
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `3.11.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.45.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Sam\Dart-Code.dart-code-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by DanTup** [comment]
> ⚠️ Make sure to attach this file from your home-directory:
> ⚠️C:\Users\Sam\Dart-Code.dart-code-unresponsive.cpuprofile.txt

Are you able to attach this file? Thanks!

**Comment by samsheldin** [comment]
[Dart-Code.dart-code-unresponsive.cpuprofile.txt](https://github.com/Dart-Code/Dart-Code/files/4766085/Dart-Code.dart-code-unresponsive.cpuprofile.txt)

**Comment by DanTup** [comment]
Thanks! Unfortunately the profile log only contains around 170ms of data, and over half of that was the garbage collector running. Do you see this often? Is it possible you were low on free RAM when this occurred?

**Comment by samsheldin** [comment]
No Sir, It has occured only once, when 2 different flutter projects (visual
studio )
 a mozilla firefox with 50 tabs and github desktop were open
Best Sam

**Comment by DanTup** [comment]
Is it possible that you had low memory at the time? I think the garbage collector may have caused the code to take much longer than it usually would (which triggered VS Code's warning). There's probably not much we can do if this was the only time/trace you have - but if it happens repeatedly and you can get more profile traces, I'm happy to take a look.

**Comment by samsheldin** [comment]
Most probably you are correct ,This happens when a visual studio update /
windows update happens ,, I'll indeed seek your help next time this pops up,
 I am running on a 5 year old device , i7 6th gen, 8gb ram, amd raedon
graphics
Thanks Sir
Sam

**Comment by DanTup** [comment]
Ok, I'll close this for now - but if you do start seeing this regularly, when you don't think your machine is busy doing other things or low on RAM, please do post the cpu profile traces so I can review them.

Thanks!

**Comment by samsheldin** [comment]
Fine Sir
