### ISSUE TITLE
Vscode running multiple dart processes consuming more memory after latest update (1.46) 

### ISSUE THREAD

**Issue by premrishi** [Dart-Code/Dart-Code#2548]
Vscode version : 1.46
Os version : Windows 10 Home
Ram: 8GB
Processor: intel core i3
Framework: Flutter
Flutter version: 1.17
IDE: vscode
Extension enabled : Flutter, Dart

**Comment by DanTup** [comment]
Can you reproduce this reliably? Are you able to get the full command lines of the processes that are being left around from Task Manager?

**Comment by premrishi** [comment]
After the new system updates, I got the normal working back.
