### ISSUE TITLE
After last update, Tooltip windows doesn't show default values.

### ISSUE THREAD

**Issue by oguzhanaltan** [Dart-Code/Dart-Code#2549]
**Before Update**
(new) IconButton IconButton({Key key, double iconSize **= 24.0**, VisualDensity visualDensity, EdgeInsetsGeometry padding = **const EdgeInsets.all(8.0)**, AlignmentGeometry alignment **= Alignment.center**, double splashRadius, Widget icon, Color color, Color focusColor, Color hoverColor, Color highlightColor, Color splashColor, Color disabledColor, void Function() onPressed, MouseCursor mouseCursor **= SystemMouseCursors.click**, FocusNode focusNode, bool autofocus **= false**, String tooltip, bool enableFeedback **= true**, BoxConstraints constraints})

**After Update;**
(new) IconButton IconButton({Key key, double iconSize, VisualDensity visualDensity, EdgeInsetsGeometry padding, AlignmentGeometry alignment, Widget icon, Color color, Color focusColor, Color hoverColor, Color highlightColor, Color splashColor, Color disabledColor, void Function() onPressed, FocusNode focusNode, bool autofocus, String tooltip, bool enableFeedback, BoxConstraints constraints})

I wrote missing parts as **bold** in Before Update part.

Thanks,

**Comment by DanTup** [comment]
Thanks for the report! This was fixed as part of https://github.com/Dart-Code/Dart-Code/issues/2442 / https://github.com/dart-lang/sdk/issues/41844 and will appear in an upcoming SDK.
