### ISSUE TITLE
VSCode dart analyzer stopped recognizing flutter/dart code

### ISSUE THREAD

**Issue by joeljsv** [Dart-Code/Dart-Code#2550]
I have been using VSCode for flutter development without issue, then today all of a sudden the dart analyzer is complaining that the majority of the classes are undefined, or targets do not exist.
I have restarted VSCode, restarted computer, uninstalled flutter/dart plugins, ran flutter doctor with no issues.

**Comment by DanTup** [comment]
Can you try running the `Dart: Get Packages` or `Flutter: Get Packages` commands from the VS Code command palette and then give it a minute to re-analyze and see if that solves the issue? Usually these types of errors are when the packages don't exist locally (for example this hasn't been run, the `.packages` files has been removed, or the pub cache has been cleared).
