### ISSUE TITLE
prefer_final_fields non-nullable late final modifier ordering is incorrect.

### ISSUE THREAD

**Issue by bsutton** [Dart-Code/Dart-Code#2553]
Running dart 2.9 with non-nullable  enabled.

The lint 'prefer_final_fields' has a quick fix which adds the 'final' keyword.
If the declaration already has the 'late' modifier the quick fix places the 'final' keyword before the 'late' modifier.

```dart
  final late bool _hasPubspecAnnotation = _findPubSpecAnnotation;
```

The correct ordering is:

```dart
 late   final bool _hasPubspecAnnotation = _findPubSpecAnnotation;
```

**Comment by DanTup** [comment]
Thanks - I can repro this - only happens when there are types. It's an SDK issue, but I've opened a possible fix at https://dart-review.googlesource.com/c/sdk/+/151511/.
