### ISSUE TITLE
Command 'Flutter: New Project' resulted in an error (command 'flutter.createProject' not found

### ISSUE THREAD

**Issue by marc-hbo** [Dart-Code/Dart-Code#2555]
I installed Dart, flutter and PATH but when i want to create new flutter project from command palette i have this error "command 'flutter.createProject' not found" Even if i open a ready project the syntax is not working

**Comment by DanTup** [comment]
Can you check if there are any errors in the developer console when this happens? (Click Help -> Toggle Developer Tools -> Console).
