### ISSUE TITLE
Remove code that forces forced spaces and automatically set defaults

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#256]
In the next version of Code the language-specific settings will support tabs/spaces so we no longer need our hack.

Info here: https://github.com/Microsoft/vscode/issues/19511

**Comment by jhirth** [comment]
Language-specific are available in the current stable release. My *settings.json* looks like this:

```javascript
{
    // ...
    "[dart]": {
        "editor.tabSize": 2
    }
}
```

**Comment by wopian** [comment]
@jhirth it is, but the one in your example and 3 others are not respected until the next stable release.

**Comment by DanTup** [comment]
Yeah; I tested it when I saw the release notes and found it didn't work. The [issue linked in my comment](https://github.com/Microsoft/vscode/issues/19511) is specifically about this.

**Comment by jhirth** [comment]
Thanks for the clarification. The 2 spaces by default thing does indeed not work if the plugin isn't running.

By the way, will the plugin automatically add that setting or how is that going to work?

**Comment by DanTup** [comment]
@jhirth I haven't looked yet, but I'm hoping that I can set this automatically. Even if I can't tell Code up-front that Dart should be like this there is now an API to modify a users settings so I think it would be reasonable to automatically inject this into the settings the first time a user runs it (and keep a flag to not repeat it, in case the user explicitly removes it).

**Comment by wopian** [comment]
1.10 adds support for configurable defaults in `package.json`

i.e

```json
"contributes": {
  "configurationDefaults": {
    "[markdown]": {
      "editor.wordWrap": "on"
    }
  }
}
```
