### ISSUE TITLE
Integrated terminal prints large command every run

### ISSUE THREAD

**Issue by mymikemiller** [Dart-Code/Dart-Code#2563]
When I debug a dart file in VSCode's Integrated Terminal, it prints out a large command, polluting the scrollback. Is it possible to have this command not print out?

Here's an example of what prints every time I start the debug or run session:

`cd /Users/mikem/myproject; /usr/local/Cellar/dart/2.8.2/libexec/bin/dart --enable-vm-service=0 --pause_isolates_on_start=true --write-service-info=file:///var/folders/2n/vn59_vz152vg107rrs53ympc0000gn/T/dart-vm-service-ee74.json -DSILENT_OBSERVATORY=true --enable-asserts bin/main.dart`

FYI, this only happens when using the Integrated Terminal. If I set my launch.json to use the Debug Console instead, it prints this instead, without printing the above:

`Connecting to VM Service at ws://127.0.0.1:58210/4yciVJ1NsWE=/ws`

**Comment by DanTup** [comment]
> FYI, this only happens when using the Integrated Terminal.

Unfortunately this is VS Code behaviour when we ask it to run in the terminal - it writes the command out as it invokes it. We're using the [RunInTerminalRequest](https://microsoft.github.io/debug-adapter-protocol/specification#Reverse_Requests_RunInTerminal) of the Debug Adapter Protocol to run this way.

The same thing happens for TypeScript (though its command line is less verbose than the Dart debugging one):

```
danny@Dannys-MBP node_sample %  /usr/local/bin/node --inspect-brk=6018 scripts/simple.js 
Debugger listening on ws://127.0.0.1:6018/453abe68-1da3-4862-8ba4-71d8e3dfd8d6
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
```

Hiding the command would need to be done by VS Code (or some flag provided for us to tell it to hide it) so would need to be raised there (https://github.com/microsoft/vscode).

Thanks!

**Comment by mymikemiller** [comment]
Thanks @DanTup, I'll raise the issue there! Seems like a "silent startup" mode in the Integrated Console would be a desirable feature.

**Comment by mymikemiller** [comment]
VSCode feature request: https://github.com/microsoft/vscode/issues/100522
