### ISSUE TITLE
Cancel "flutter pub get" task，but lockfile still exist 

### ISSUE THREAD

**Issue by boynextq** [Dart-Code/Dart-Code#2564]
I canceled "flutter pub get" task when I realized that I depended on a wrong package ,like "RxDart: ^0.24.1".But the lock is not release.
![0M}_9GP@SHGTDH$EJBTZ ~L](https://user-images.githubusercontent.com/46438697/84866801-cc7f9c00-b0ac-11ea-871d-95568686dd5f.png)

**Comment by DanTup** [comment]
If the other task is definitely still not running in the background, you should be able to manually delete the lock file (`bin/cache/lockfile` in the SDK). Depending on how you terminate a process, it may not give it chance to clean up the lockfile.

Let me know if this doesn't work!

**Comment by boynextq** [comment]
I always delete it manually,but is it possible to automatically delete lockfile?

**Comment by DanTup** [comment]
Flutter should normally delete the lock file itself when the process completes. Are you frequently terminating processes?

**Comment by boynextq** [comment]
yes

**Comment by DanTup** [comment]
@boynextq can you provide more details about why? It's not expected that you should need to terminate Flutter processes, so fixing that will prevent the lock file being left around.

**Comment by chengyuhui** [comment]
Having to terminate the process is fairly common, especially here in China. We constantly have connectivity issues even with mirrors inside China which hangs up the pub process.

**Comment by DanTup** [comment]
When this happens and you cancel the process, if you open up task manager / run `ps` are the processes still hanging around in the background?

Looking at the cancellation code, I don't think it's actually cancelling properly. So I wonder if the reason the log file remains, is that the process is still alive?

**Comment by DanTup** [comment]
I think this is basically a dupe of #2612. Cancellation doesn't work properly, so the process keeps running in the background.
