### ISSUE TITLE
Not able to count properly

### ISSUE THREAD

**Issue by tomasbaran** [Dart-Code/Dart-Code#2567]
```
void main() {
  double a = 0.000004;
  double b = 0.000001;
  double result = a + b;
  print(result);
}
```
## Expected result
0.000005

## Actual result
0.0000049999999999999996

**Comment by DanTup** [comment]
Thanks for the report! This is really a Dart language issue and not related to the VS Code extension, however it is actually working as expected. The `double` type is a floating point type and some numbers can't be accurately represented which leads to small errors like this. You can see this issue with even some fairly simple numbers:

```
print(0.1 + 0.2); // 0.30000000000000004
```

You'll see the same thing in JavaScript too (which uses the same [IEEE 754](https://en.wikipedia.org/wiki/IEEE_754-2008_revision) standard) if you open up the developer tools and type the same expression:

![Screenshot 2020-06-17 at 16 23 12](https://user-images.githubusercontent.com/1078012/84917146-dc9c7900-b0b6-11ea-8834-e9b1a1893338.png)

There's some more info on how these are represented (in binary) on this website here:

https://floating-point-gui.de/
https://floating-point-gui.de/basic/

If you really need precise decimals (and can't work with rounding doubles), there are some pub packages like https://pub.dev/packages/decimal, though I can't vouch for their trustworthiness/reliability.

Hope this helps!
