### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ramuramasani** [Dart-Code/Dart-Code#2570]
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `3.11.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.46.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\ramur\Dart-Code.dart-code-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by DanTup** [comment]
> ⚠️ Make sure to attach this file from your home-directory:
> ⚠️C:\Users\ramur\Dart-Code.dart-code-unresponsive.cpuprofile.txt

Are you able to attach this file? Thanks!
