### ISSUE TITLE
Dart processes get left behind when builds fail

### ISSUE THREAD

**Issue by MarcusTomlinson** [Dart-Code/Dart-Code#2574]
When builds fail (in this particular case, the error being 'unable to generate build files') it leaves the zombie dart processes behind.

After 5 failed build attempts:

<img width="1440" alt="Screenshot 2020-06-18 at 16 04 12" src="https://user-images.githubusercontent.com/7335138/85038050-0a002a00-b17e-11ea-9e70-29afc82ba132.png">

_Originally posted by @MarcusTomlinson in https://github.com/Dart-Code/Dart-Code/issues/2219#issuecomment-646087170_

**Comment by MarcusTomlinson** [comment]
<img width="495" alt="bash" src="https://user-images.githubusercontent.com/7335138/85112405-7f670b80-b20d-11ea-8260-16ca2d842bd6.png">

<img width="505" alt="dart1" src="https://user-images.githubusercontent.com/7335138/85112412-8261fc00-b20d-11ea-818f-f69340fbaf56.png">

<img width="504" alt="dart2" src="https://user-images.githubusercontent.com/7335138/85112427-84c45600-b20d-11ea-85ae-f5e16ed304eb.png">

**Comment by DanTup** [comment]
@MarcusTomlinson does this reproduce from the terminal outside of VS Code? Eg. if you run

```
flutter run --machine -d Linux --track-widget-creation --start-paused
```

Does the process also hang around, or does it only occur when you tried to run from VS Code?

**Comment by MarcusTomlinson** [comment]
So as a test I intensionally removed a semicolon from `linux/main.cc` and ran:

`flutter run --machine -d Linux --track-widget-creation --start-paused`

Output:

```
[{"event":"daemon.connected","params":{"version":"0.5.3","pid":3446}}]
[{"event":"app.start","params":{"appId":"f222f64d-322c-4c4c-9c12-0c889f48128b","deviceId":"linux","directory":"/home/marcustomlinson/Projects/flutter/fifteenpuzzle","supportsRestart":true,"launchMode":"run"}}]
Launching lib/main.dart on Linux desktop in debug mode...
[{"event":"app.progress","params":{"appId":"f222f64d-322c-4c4c-9c12-0c889f48128b","id":"0","progressId":null,"message":"Building Linux application..."}}]
[{"event":"app.progress","params":{"appId":"f222f64d-322c-4c4c-9c12-0c889f48128b","id":"0","progressId":null,"finished":true}}]
[{"event":"app.stop","params":{"appId":"f222f64d-322c-4c4c-9c12-0c889f48128b"}}]
Exception: Build process failed
```

The terminal remains stuck here until I hit Ctrl+C.

**Comment by DanTup** [comment]
Thanks - I was able to reproduce this. It feels like a Flutter issue so I've opened an issue at https://github.com/flutter/flutter/issues/60613 with some notes.

**Comment by DanTup** [comment]
This has been fixed in Flutter - if you can still reproduce it on latest master, please add a note on https://github.com/flutter/flutter/issues/60613. Thanks!
