### ISSUE TITLE
Syntax highlight confusing in unicode string formatting

### ISSUE THREAD

**Issue by tgarm** [Dart-Code/Dart-Code#2575]
When syntax highlight a unicode string, the syntax highlight does not very correct.
For instance, to format a value **val** in string may look like:

- Without bracket
![WeChate216463751653492a1ec45db890cf583](https://user-images.githubusercontent.com/24644183/85241223-ac195e00-b46d-11ea-9173-206e3476fc9d.png)

This seems will format **val世界** instead of **val**.

- With bracket
![WeChat50ebba0060b5bfb3b4adfa2492c7cc74](https://user-images.githubusercontent.com/24644183/85241250-ca7f5980-b46d-11ea-81fb-b51b8ebf2ae0.png)

This shows brackets are not needed.

 It seems confusing how to correctly format **val** in this string in this syntax highlight.

**Comment by DanTup** [comment]
Thanks for the report! There are quite a few issues with the current syntax highlighting. The goal is to fix them when adopting server-provided highlights through LSP (in #2202) since the server will produce reliable highlights using the real Dart parser, rather than using regex.
