### ISSUE TITLE
[Flutter] Invalid version error while trying to debug in VS Code

### ISSUE THREAD

**Issue by 065rsh** [Dart-Code/Dart-Code#2576]
**I don't know how to reproduce this issue, so I'm not able to attach logs!**
> This issue is just feedback!

This error occurs rarely and then I've to restart the VS Code and it gets fixed, What could be the reason for this error and how can I fix it?
Last time it happened when I tried to debug the app using **`f5`** button

![Error snapshot](https://user-images.githubusercontent.com/38327567/85280357-9d4e9d80-b4a5-11ea-9874-52834ed456d9.png)

**Comment by DanTup** [comment]
This message doesn't appear to be coming from the Dart/Flutter extension - we don't have any label like "invalid version" in the code. I think it must be coming from VS Code or another extension. It looks like it may have been raised with VS Code before, but was closed (https://github.com/microsoft/vscode/issues/98151).

If you don't have any other extensions that might be doing anything at debug launch, I'd file a bug with VS Code for assistance (feel free to CC me so it doesn't get closed as an issue here like that one). If you post your list of extensions, I'm happy to have a scan through to see if any of them look like they might be causing this too.

**Comment by 065rsh** [comment]
<details>
<summary>List of extensions</summary>

```
aaron-bond.better-comments
abusaidm.html-snippets
adam-watters.vscode-color-pick    
akhail.save-typing
ansenhuang.vscode-view-readme     
christian-kohler.npm-intellisense 
CoenraadS.bracket-pair-colorizer-2
cssho.vscode-svgviewer
Dart-Code.dart-code
Dart-Code.flutter
dbaeumer.vscode-eslint
DiemasMichiels.emulate
dsznajder.es7-react-js-snippets
eamodio.gitlens
ecmel.vscode-html-css
eg2.vscode-npm-script
Equinusocio.vsc-material-theme
esbenp.prettier-vscode
formulahendry.auto-rename-tag
fwcd.kotlin
jasonlhy.vscode-browser-sync
mathiasfrohlich.Kotlin
mohsen1.prettify-json
ms-mssql.mssql
ms-python.anaconda-extension-pack
ms-python.python
ms-vscode.cpptools
ms-vscode.typescript-javascript-grammar
naumovs.color-highlight
PKief.material-icon-theme
pranaygp.vscode-css-peek
redhat.java
redhat.vscode-yaml
skyran.js-jsx-snippets
VisualStudioExptTeam.vscodeintellicode
vsciot-vscode.vscode-arduino
vscjava.vscode-java-debug
vscjava.vscode-java-dependency
vscjava.vscode-java-pack
vscjava.vscode-java-test
vscjava.vscode-maven
xabikos.JavaScriptSnippets
yzane.markdown-pdf
```
</details>

**Comment by DanTup** [comment]
Nothing in that list stands out. You could try trunning the **Extensions: Open Extensions Folder** in VS Code to find where all the extensions are, then open that folder in VS Code and do a Find across all files for `Invalid version:`. If it's an extension, that might identify which one (otherwise, it could be VS Code - though I did search through its code and couldn't see this).

**Comment by 065rsh** [comment]
But in my case, I can see the throw statement in most of the extensions

![Search result image](https://user-images.githubusercontent.com/38327567/85310670-eae0ff80-b4d1-11ea-94a9-98e9d34d68d8.png)


There are 26 extensions in which I can see this result

**Comment by DanTup** [comment]
Oh yeah - I see - the exception is coming from the semver package, which a lot of extensions (including Dart) use. I guess that doesn't help - the question is who is trying to parse an empty string during debug startup?

I've checked the debug provider for Dart and it doesn't seem to use semver in the debugger startup code, so I don't *think* it's this.

If you can reproduce the issue reliably, I would first try disabling any of the debugger extensions you have and see if the issue goes away. If so, re-enable a few at a time to see if you can figure out which one it is.

Another thing that may be worth checking - is the developer tools (Help -> Toggle Developer Tools -> Console) in VS Code and see if there are any errors/warnings written that might indicate which extension is triggering it.

**Comment by 065rsh** [comment]
Next time I see this error, I'll try to observe and reproduce it. I will also check the console when it happens 👍 

Currently, this is what my console is like on trying to debug!

![Console output image](https://user-images.githubusercontent.com/38327567/85314080-90966d80-b4d6-11ea-9e5c-b23d954fe971.png)

**Comment by 065rsh** [comment]
This issue did not reappear 😄
