### ISSUE TITLE
Default to running Dart CLI apps in checked mode

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#258]
I noticed some stuff about `assert`s in the release notes for the SDK; says that asserts aren't run in production mode. I wondered how I trigger this and it seems the VM is production by default unless you pass `--checked`. Since running from DC is almost certainly development and not production, I think it'd make sense to add this to our default args for `launch.json`.

(cc @devoncarew - does this sound logical to you?)

**Comment by devoncarew** [comment]
Yeah, make sense. `--checked` will catch more things at runtime. I _think_ it's like a 30% runtime penalty, so you wouldn't benchmark with it, but definitely worth it when developing.

**Comment by DanTup** [comment]
I've added it as a new option in `launch.json` (which will be set to true by default for newly-created launch jsons, but not added to existing ones). It seemed to make more sense there than a general debug setting (passed by `getDebugSettings`) as it can be toggled per launch command (I think this'll make it easier in future to let the user switch between Checked/Production in the dropdown on the debug tab).
