### ISSUE TITLE
Can't jump into libraries from integrated terminal stack traces

### ISSUE THREAD

**Issue by mymikemiller** [Dart-Code/Dart-Code#2581]
I'm not sure if this is an issue for the Dart-Code extension or if it's a VSCode thing (or if I just have some setting wrong), but I figured I'd start here.

When I print out a stack trace and click on a file link, VSCode fails to navigate to package files in my pub_cache.

For illustrative purposes in the screenshots, I navigated to the file by jumping to it when debugging. The file does not pop up when cmd+clicking the link.

<img width="1590" alt="before" src="https://user-images.githubusercontent.com/2063229/85453853-8c5f6400-b559-11ea-8aa2-25ea63ceb895.png">
<img width="1586" alt="after" src="https://user-images.githubusercontent.com/2063229/85453875-8ff2eb00-b559-11ea-8b45-03487eceef95.png">

**Comment by mymikemiller** [comment]
Note that searching the workspace for the text of the line *does* show the result, and I can click into the line in the editor.

<img width="1193" alt="Screen Shot 2020-06-23 at 2 55 45 PM" src="https://user-images.githubusercontent.com/2063229/85462415-abaebf00-b562-11ea-9ca1-14e03fa89f5a.png">

**Comment by DanTup** [comment]
This is unfortunately a limitation of VS Code. We have no ability to tell the terminal the terminal about `package:` links so it's unable to detect them and link them. You could raise this as a feature request at https://github.com/microsoft/vscode/issues and if an API was provided that allowed us to handle link detection for the terminal, we could contribute some rules.

Out of interest though - why are you running the app in the terminal?

**Comment by mymikemiller** [comment]
Good to know, thanks.

I'm using the terminal because the debug console doesn't support cursor positioning and I want to print pretty progress bars and stuff. Also the debug console isn't interactive.

**Comment by mymikemiller** [comment]
Filed a VSCode feature request: https://github.com/microsoft/vscode/issues/101041

**Comment by Tyriar** [comment]
The terminal link provider API just hit proposed, still open to feedback and it may change before becoming stable https://github.com/microsoft/vscode/issues/91290

**Comment by DanTup** [comment]
@Tyriar aha! I thought I'd seen it somewhere, but couldn't find it when searching the other day! I'll check it out and see if it does what we'd need. Thanks!
