### ISSUE TITLE
[Suggestion] Make intellisense more "intelli"

### ISSUE THREAD

**Issue by JCKodel** [Dart-Code/Dart-Code#2587]
This example is from Visual Studio (the big brother) and C#.

For most items, the intellisense selects the best candidate for completion, based on Type (for instance, if we're setting an enum variable, the first choice in intellisense is the first value of that Enum type).

![image](https://user-images.githubusercontent.com/379339/85867664-996d9480-b79f-11ea-949f-459cff77e983.png)
**_(the same behavior is observed in VSCode with official C# extension)_**

The same happens for classes as well. In Dart, this would be awesome for, for example, Flutter's padding: When we type `Padding(padding: `, the intellisense just would popup with the EdgeInsets class (because that's what `padding` parameter requires).

Another example would be this:

```dart
Column(mainAxisSize: 
```
Here, MainAxisSize enum should be the first option, but when we fill the mainAxisAlignment, the MainAxisAlignment enum should be the irst selected.

It also have some neat tricks that you only notice when they're missing. For instance:

![image](https://user-images.githubusercontent.com/379339/85868031-20bb0800-b7a0-11ea-91f6-a516b4a34b3b.png)
**_(VSCode does not do that)_**

I don't know exactly how it figures out, but notice how it just knows what we intend (in this case, it automatically shows the correct parameter to the variable, without me having to do nothing).

![image](https://user-images.githubusercontent.com/379339/85868279-71326580-b7a0-11ea-844b-a3e50f136d83.png)
**_(VSCode does not do that)_**

Here it is selecting the last value used (my string variable). I guess this behavior do the next cool trick:

![image](https://user-images.githubusercontent.com/379339/85868381-91622480-b7a0-11ea-90cd-9d852b93c5d3.png)
**_(the same behavior is observed in VSCode with official C# extension)_**

It chooses automatically the pairing variable while copying classes.

As far as I remember, most of this behavior is NOT from IntelliCode (that uses your code and some "AI" to give you the best match for you, but those suggestions are marked with a *):

![image](https://user-images.githubusercontent.com/379339/85869866-acce2f00-b7a2-11ea-80c4-3caefde58cfb.png)

This kind of tricks is what make people choose Visual Studio over Visual Studio Code for C# programming. It helps A lot.

Also, in VSCode, the C# extensions has some very usefull lens:
![image](https://user-images.githubusercontent.com/379339/85869615-5103a600-b7a2-11ea-93dd-a86642675540.png)

**Comment by DanTup** [comment]
Thanks for the detailed report! I think some of this may be covered by https://github.com/dart-lang/sdk/issues/38739. If you have specific examples you think or not, please list them here.

There's an open issue about the references CodeLens you can subscribe to at https://github.com/Dart-Code/Dart-Code/issues/1605. Thanks!
