### ISSUE TITLE
Suggesting too slow

### ISSUE THREAD

**Issue by Kaung-Phyo-Wai** [Dart-Code/Dart-Code#2589]
I am new to flutter. But When I use the flutter extension in vs code, the suggestion are too slow. I thought the error is causing because I am running the simulator while I am developing. But when I use without running the simulator, the problem still remian. Hope It fixed when the updates available.

**Comment by DanTup** [comment]
Do you mean when you press `Ctrl+Space` it takes a long time for the code completion list to appear?

Does it get any faster if you set `"dart.autoImportCompletions": false` in your VS Code user settings and restart?

Does the issue reproduce in a brand new Flutter project (created with **Flutter: New Project**) without any changes too, or only in a specific project?

Thanks!
