### ISSUE TITLE
Debugger protocol updates

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#259]
See https://github.com/JetBrains/intellij-plugins/pull/483

**Comment by DanTup** [comment]
@devoncarew I had a look at the linked PR but I'll be honest, I'm not entirely sure what I'm looking at! I had a scan through [this doc](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md) but can't see any mention of the word "casual" even though that seems to be what you're calling in your code.

I presume this is to improve the call stack shown in the debugger for async code (to join the place the awaiting and async code) though it's not clear to me exactly what the interaction is with observatory is for this.

I guess I need to be able to create some sample code and know exactly what the stack should look like after this change.

Also; do I need to do any version checks here, or will the service return null if the SDK doesn't support this? I say this in your impl:

> if (json.get("asyncCausalFrames") == null) return null;

which I presume is handling this?

**Comment by devoncarew** [comment]
Hey, OOO right now but will comment quickly. I think you need the latest dev SDK for this. Doing the existence check for asynchronous frames sounds right - probably more robust than a protocol version check.

Theres a companion doc to the above - service_dev.md. that'll mention the causal frames APIs.

**Comment by DanTup** [comment]
> Theres a companion doc to the above - service_dev.md. that'll mention the causal frames APIs.

Ah, didn't know about that; though that doesn't seem to contain "casual" on [`master`](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service_dev.md) or [`dev`](https://github.com/dart-lang/sdk/blob/dev/runtime/vm/service/service_dev.md) branches either. It was updated by you recently though; I presume they don't go by another name?

Anyway, no rush if you're OOO. I ended up releasing today without all the stuff in the v1 milestone due to an accidental breaking change in Code (and I didn't realise this was still dev, so no point trying to rush it out).
