### ISSUE TITLE
VS Code has updated (Debug=> Run), the current flutter documentation is misleading

### ISSUE THREAD

**Issue by madhu131313** [Dart-Code/Dart-Code#2591]
In this page
https://flutter.dev/docs/development/tools/vs-code

Debugging can only be seen in New VS Code via window > Run > Debugging, but in the link mentioned it is 

Debug > Start Debugging, so it confused me. 

BTW, the feedback link is redirecting here, but I m wondering if this is the right place to post, as the repo name is Dart-Code

**Comment by DanTup** [comment]
Thanks for the report! This menu item used to be called Debug, but it was renamed to avoid confusion (though it seems to have also caused some!). This is the repo for the Dart/Flutter VS Code extensions, though that page is part of the Flutter website. I'll fix it over there - thanks for the ping!

**Comment by DanTup** [comment]
Forgot to close this - the changes have been made and are live on the website. Thanks!
