### ISSUE TITLE
Build Process Failure

### ISSUE THREAD

**Issue by BootBlock** [Dart-Code/Dart-Code#2594]
### Description
There seems to be an issue with a Flutter application hanging and Dart Code thinking that it's actually in the process of being built, and so will display `Reload already in progress, ignoring request` while attempting to _Hot Reload_. Terminating the debugging session doesn't result in the actual process terminating and any subsequent building will fail with a general error message.

### Reproduction Steps
1. Build and run a Flutter application as normal so VS/Dart Code is displaying the debugging toolbar.
2. Go back to the VS Code text editor and introduce any kind of error; typing random gibberish is fine as long as the project no longer builds.
3. Perform a _Hot Reload_ (`Ctrl+Shift+F5`).
4. Everything appears to get stuck; trying to perform any further _Hot Reloads_ just results in a `Reload already in progress, ignoring request` error. This is regardless of whether the error-inducing gibberish is corrected or not. The Flutter application window contents is entirely black/blank.
5. Clicking Stop on the debugging toolbar results in a delay of a few seconds and then it disappears, indicating that the Flutter project process has exited. A status message within VS Code is displayed with the following `timeout after 1000 ms`.
6. Any attempts to build the project results in the following error:

`Launching lib\main.dart on Windows in debug mode...
Exception: Build process failed. To view the stack trace, please run flutter run -d windows -v.
Exited (sigterm)`

### Debug Output
The most telling line is that the `.exe` couldn't be found; this is seemingly because it is locked by the operating system.

**Verbose Flutter Log**: [DartVerboseLog.txt](https://github.com/Dart-Code/Dart-Code/files/4846795/DartVerboseLog.txt)

### Expected Results
Performing a _Hot Reload_ (with broken code) should display an error within VS Code, as normal. Clicking on _Stop_ within the debug toolbar should completely kill the project executable.

### Environment
**VS Code:** 1.46.1 (user setup)
**Dart Code:** 3.12
**Dart VM:** 2.9.0-13.0.dev.flutter-87c5e3612b (be)
**System:** Windows (windows-x64)
**Flutter:** 1.19.0-5.0.pre

**Comment by DanTup** [comment]
I can't repro this (on macOS with a clean `flutter create` project). The log only includes the Flutter output so doesn't include the daemon response to `hot.reload`. It would be useful to capture a log using **Dart: Capture Logs** that spans the above to examine the responses from Flutter.

(it's also worth testing it on `master` - which might not work for Flame, but should work for a simple counter app)

**Comment by BootBlock** [comment]
I can't seem to reproduce this either, so it appears it may have been fixed in master (1.21).
