### ISSUE TITLE
Wrapping the elements

### ISSUE THREAD

**Issue by Goolpe** [Dart-Code/Dart-Code#2600]
I tried to wrap multiple elements in a column or a raw with `Ctrl + .` and ran into a problem
Let's try combine two elements:

![image](https://user-images.githubusercontent.com/18518522/86216985-8126bc80-bb87-11ea-8d0f-480c913b756b.png) -> ![image](https://user-images.githubusercontent.com/18518522/86217024-8edc4200-bb87-11ea-90e5-c98a3f9ffd81.png)

Elements on the same line, works fine:

![image](https://user-images.githubusercontent.com/18518522/86217099-a7e4f300-bb87-11ea-9ee8-fdf7d1c631f4.png) -> ![image](https://user-images.githubusercontent.com/18518522/86217141-b6330f00-bb87-11ea-892d-8c11bb8afc53.png)

Combine elements in widget (difference in one space selection before elements)

![image](https://user-images.githubusercontent.com/18518522/86216250-6d2e8b00-bb86-11ea-8f4a-94c252790965.png) -> ![image](https://user-images.githubusercontent.com/18518522/86216753-35741300-bb87-11ea-9b48-592128136ed4.png)
![image](https://user-images.githubusercontent.com/18518522/86216548-e0d09800-bb86-11ea-8d29-dca1c805da85.png) -> ![image](https://user-images.githubusercontent.com/18518522/86216680-1bd2cb80-bb87-11ea-8d1a-32392c8aa4c6.png)

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.19.0-4.2.pre, on Linux, locale ru_RU.UTF-8)
    • Flutter version 1.19.0-4.2.pre at /home/ads/flutter
    • Framework revision 9b9b543d92 (9 дней назад), 2020-06-22 12:19:28 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/ads/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /snap/android-studio/84/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /snap/android-studio/84/android-studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at /home/ads/idea
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6911.25

[✓] VS Code (version 1.42.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • ZTE BLADE A0622 • 320376181424 • android-arm    • Android 7.1.1 (API 25)
    • Web Server      • web-server   • web-javascript • Flutter Tools
    • Chrome          • chrome       • web-javascript • Google Chrome 80.0.3987.116

```
</details>

**Comment by DanTup** [comment]
Thanks for the report! This code didn't take into account multi-line selections when calculating the length of the selection (it just did `end.character - start.character`). I've fixed this for the next version. Thanks!
