### ISSUE TITLE
Include "unsupported" devices in the device picker, offer to run "flutter create ." when selected

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#2602]
If a project has no "web" folder we don't show the Chrome device, but it's not always obvious why.

It would be nice if we could still show the unavailable devices somewhere (maybe at the bottom of the device selector, with a note like "- unavailable for project") and offer some instructions on how to "upgrade" the project to support this (if appropriate).

It'd be nice if this behaviour was backed by Flutter so we don't need to hard-code rules directly into VS Code.

@jonahwilliams what to you think about `getSupportedPlatforms` having some flag to include unavailable platforms, but with a flag against them and a `reason` for why they're not available (at least for those that could be enabled - `windows` on `linux` probably doesn't make sense, but `web` would).

**Comment by jonahwilliams** [comment]
Seems like a reasonable update to the API

**Comment by DanTup** [comment]
I came to look at this, and realised that supportedPlatforms always includes platforms based on what's on disk, and not what devices are available. Eg. if I have a `windows` folder on `macOS`, it *is* included in the results for `getSupportedPlatforms`. It's then filtered out because there's no `device` for it.

Therefore, I don't think this actually requires any work in Flutter - I think in VS Code we can consider any device that is available but is not in `supportedPlatforms` is something that can be enabled :-)

**Comment by DanTup** [comment]
Actually, that doesn't address the original issue of how the user enables the missing platforms. But it seems like the answer to that is always "run `flutter create .`" so I think we can show that for each of these.
