### ISSUE TITLE
Refactorings gone

### ISSUE THREAD

**Issue by willhaslett** [Dart-Code/Dart-Code#2603]
I don't know if this is the Dart extension, the Flutter extension, or neither, but the refactoring right-click menu option has disappeared. When I use my keyboard shortcut I get "No refactorings available". 

Versions:
```
Dart extension: 3.12.1
Flutter extension: 3.12.1
```

flutter doctor -v:
```
[✓] Flutter (Channel beta, 1.19.0-4.3.pre, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.19.0-4.3.pre at /Users/wh/flutter
    • Framework revision 8fe7655ed2 (17 hours ago), 2020-07-01 14:31:18 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/wh/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

**Comment by DanTup** [comment]
Can you give a specific example of some code where you're invoking this and which refactor you expect to see? Also, what keybind are you using (and if it's custom, what command/filter is it bound to?). I can still see things like "extract Method" in the lightbulb menu, but I'm not sure if this is the same place you're looking (or the same type of refactor):

<img width="520" alt="Screenshot 2020-07-02 at 15 54 58" src="https://user-images.githubusercontent.com/1078012/86374422-74d05b80-bc7c-11ea-958e-2856612bb311.png">

**Comment by willhaslett** [comment]
My bad. Nothing to see here. Pardon the noise.

**Comment by DanTup** [comment]
No worries, glad you figured it out! :-)

**Comment by pharshdev** [comment]
refactorings are gone suddenly 
<img width="645" alt="image" src="https://user-images.githubusercontent.com/15626305/108345684-93cc2f80-7204-11eb-9da5-90c9093bf44a.png">

also `//TODO: ` doesn't show up in "Problems" tab.

Tried reinstalling dart, flutter extension.
Dart: v3.19.2
Flutter: v3.19.0
OS: Big Sur

**Comment by DanTup** [comment]
@pharshdev I suspect you're seeing https://github.com/Dart-Code/Dart-Code/issues/2885. If you use the standard lightbulb menu (`Cmd+.`) are they listed there? If so, the issue is fixed for an upcoming SDK release.
