### ISSUE TITLE
Possible Bug when creating a method which returns a Future<List<T>>

### ISSUE THREAD

**Issue by ajilo297** [Dart-Code/Dart-Code#2607]
I have been coming across this issue for a while but couldn't figure out exactly how to reproduce it. Just found out today. 

[Dart-Code-Log-2020-06-00 16-31-58.txt](https://github.com/Dart-Code/Dart-Code/files/4874806/Dart-Code-Log-2020-06-00.16-31-58.txt)

Just incase the log file is not clear enough.

The code I'm trying to type is something like this `Future<List<String>> getData() async {}`
Steps to reproduce:
1. I start out by typing `Future<>`
2. Then move cursor back to inside the `<` and `>`
3. Inside I type `List<>`. So the overall code becomes `Future<List<>>`
4. And then I Define the type of list by moving the cursor back inside List and typing in `String`
5. At this point the analyzer has already stopped working and no matter what else I do, the error highlighting doesn't go away unless I restart VS Code

This is the error that comes up in the highlighting

> Methods must have an explicit list of parameters.
Try adding a parameter list.dart(missing_method_parameters)

**NOTE**
* This does not happen if you don't strictly follow the process I am using.
* Eg. if you type `Future<`
* then `List<`
* then `String>>`

BTW, I'm using a Windows machine, but I think I saw the same problem on my Macbook too, but not sure.

**Comment by DanTup** [comment]
Thanks for the report! This seems to be a parser issue - there's an open issue in the SDK repo at https://github.com/dart-lang/sdk/issues/42229.
