### ISSUE TITLE
Invalid override. The type isn't a subtype of ...

### ISSUE THREAD

**Issue by helikopterodaktyl** [Dart-Code/Dart-Code#261]
This code makes Dart-Code show an error (repro is my project/package name):

![image](https://cloud.githubusercontent.com/assets/22717028/23106697/82eaf102-f6f1-11e6-8bb9-5b0d1ccd2a33.png)

![image](https://cloud.githubusercontent.com/assets/22717028/23106722/efccf266-f6f1-11e6-9904-8fe325619380.png)

Removing the "package:" prefixes seems to fix the error. I'd expect it to be a problem with my code, or with Dart SDK, but pub build and dartanalyzer don't seem to report anything. 

![image](https://cloud.githubusercontent.com/assets/22717028/23106730/0e074ed4-f6f2-11e6-93db-3378847d9b7b.png)

**Comment by DanTup** [comment]
Dart Code doesn't actually do any parsing of code itself, it's all handled by the analyzer that ships inside the Dart SDK, so I think this needs to be raised against the SDK repo [here](https://github.com/dart-lang/sdk/issues/new). It is possible Dart Code is doing something wrong; though I can't think of what could cause something like this - @bwilkerson might be able to confirm.

**Comment by helikopterodaktyl** [comment]
Hmm. Unless I'm doing something wrong with the config, I checked with Atom's Dart plugin and it doesn't show any errors there, that'd suggest the issue with Dart Code...

**Comment by DanTup** [comment]
It is very possible; I just can't think of what might be different (esp. if it's fine in Atom).

Can you confirm the version of Dart Code and the SDK you're using and what other options you may have set that might affect this? If I've recreated your repro correctly, I get a different message (a warning):

> The parameter type 'Renderer (m:\Coding\TestStuff\Repro\lib\a.dart)' isn't assignable to 'Renderer (M:\Coding\TestStuff\Repro\lib\a.dart)' as required by the method it is overriding from 'Renderable'.'
at: '7,15'

Can you also confirm you're using the same SDK version in both Atom and Dart Code?

(cc @devoncarew in case you have any ideas?)

**Comment by helikopterodaktyl** [comment]
My Dart version is:

Dart VM version: 1.22.0 (Mon Feb 13 17:39:28 2017) on "windows_x64"

My Dart Code is version 0.15.1

in my settings file in VSCode just to be sure I put:

 "dart.sdkPath": "C:\\Program Files\\Dart\\dart-sdk"

to match my dart settings:

![image](https://cloud.githubusercontent.com/assets/22717028/23136755/6ed7bd78-f79e-11e6-9b2b-93da3a5e4531.png)

but it doesn't change anything.

**Comment by DanTup** [comment]
I don't know why the casing is different (my guess is one is from Windows/Code when I opened the file and the other was constructed by Dart) though I wouldn't expect it to make any difference; FS is case-insensitive on Windows and I'd expect Dart to handle that.

Are you able to zip up your repro folder and attach? You don't have an `analysis_options.yaml` file or anything?

Do you have any `packages` folder on your disk? (I think the default now is *not* to create these, and use the `.packages` file instead - do you have one of them?).

Also, have you tried reloading (either restart Code, re-open folder, run the "Reload Window" command)? (I presume so, but worth checking, to ensure there's nothing hanging around in memory of Dart Code or the Analyzer).

Thanks!

**Comment by helikopterodaktyl** [comment]
Ahh, yes, I do have analysis_options - actually that error shows up in strong mode only. Without strong mode I get the warning you are getting, but still - that looks like a perfectly legal code to me.

**Comment by DanTup** [comment]
Exactly what do you have in `analysis_options.yaml`? Even with strong mode I'm not getting the same error, which is a bit weird.

I agree, it looks like reasonable code to me if circular imports are allowed (I presume so). I'm not sure why it would work any differently in Atom (Dart Code and Atom use the same analysis service; though I don't know if Atom may set some options Dart Code doesn't).

If I can get my repro to work I might be able to do a bit more digging.

**Comment by helikopterodaktyl** [comment]
here's my project:

[repro.zip](https://github.com/Dart-Code/Dart-Code/files/788257/repro.zip)

**Comment by DanTup** [comment]
Apologies for the delay, I've been away this week. Opening your repro I get the same error. I can't see anything Dart Code can be doing to cause this (though I also can't explain why Atom wouldn't show the same), but I've copied the details to the SDK repo as I think it needs input from the Dart Team. You can subscribe to this case to get notifications of updates:

https://github.com/dart-lang/sdk/issues/28895

Of course I'll also update this case when I hear back.

**Comment by DanTup** [comment]
This appears to be fixed by https://github.com/dart-lang/sdk/pull/32133 (normalisation of drive letters on windows, the fix for https://github.com/dart-lang/sdk/issues/32095).

**Comment by DanTup** [comment]
My analyzer PR was merged, so this should be fixed in an upcoming version of the SDK. Thanks for reporting! 👍
