### ISSUE TITLE
"Timeout after 1000ms" when terminated a debug session

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#2611]
1s after clicking Stop on the debug toolbar, there's open a "timeout after 1000ms" notification. This is likely because we wait for the process to end in `terminateRequest` but VS Code assumes that because we didn't respond, that we are not handling the request.

**Comment by bubnenkoff** [comment]
Same issue

**Comment by DanTup** [comment]
It's fixed for the next version, which I'm hoping to make a beta release of later today.
