### ISSUE TITLE
Implement syntax highlighting for pubspec/analysis options files (YAML)

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#262]
Since making these their own languages (to allow us to force 2-space indenting) they won't get the built-in YAML support, so we need to add this back in.

**Comment by Lisenish** [comment]
@DanTup Looks like this was fixed in 1.4

**Comment by DanTup** [comment]
Yep, no longer required now we switched back to the built-in YAML support (since I found I could limit the `pub` commands based on filename rather than just language). Thanks!
