### ISSUE TITLE
Devtools integration

### ISSUE THREAD

**Issue by d-silveira** [Dart-Code/Dart-Code#2621]
Hi,

I was wondering, since vscode is an electron app (effectively a browser), why can't we have open devtools within vscode, instead of having to have another browser open?

Thanks,
Regards,
d-silveira

**Comment by DanTup** [comment]
You can - though this functionality is currently behind a flag. You can find the details in the [latest release notes](https://dartcode.org/releases/v3-12/#preview-embedded-devtools). If you have any issues when running in this mode, please do file issues here.

Thanks!
