### ISSUE TITLE
Add summary of test status/durations to non-leaf nodes

### ISSUE THREAD

**Issue by hashemp206** [Dart-Code/Dart-Code#2623]
Currently In test panel, it shows `test group` and `test name` and `duration` for each test.

**Proposed improvements:**

For each test group display `number of tests`, `number of passed tests`, `accumulated duration of all tests in the group`

```
Project Name +----+ 14 tests total, 8 tests passed, 0.1 seconds

  object_test.dart +-----+ 14 tests total, 8 tests passed, 0.1 seconds

     group_test +-----+ 8 tests total, 8 test passed, 0.05 seconds

     individual_test +------+ 0.003 seconds
```

the goal is have a glimpse on total passed tests and total duration for the whole project, each test file and test group. 
<img width="747" alt="Screen Shot 2020-07-08 at 12 31 16 PM" src="https://user-images.githubusercontent.com/3206748/86935295-e8c5a480-c151-11ea-85b3-7e8253e1ae40.png">

**Comment by hashemp206** [comment]
I got the idea from Xcode test log interface:
<img width="743" alt="Screen Shot 2020-07-08 at 11 18 03 PM" src="https://user-images.githubusercontent.com/3206748/86958399-5a611b00-c171-11ea-839c-dd2e474a8828.png">

**Comment by haashem** [comment]
Hi Thanks for enhancing this extension but after running a few tests, test summary panel gets confused and added previous group tests run counts! I have only three tests in one group.
 
<img width="1217" alt="Screen Shot 2020-11-04 at 8 10 37 PM" src="https://user-images.githubusercontent.com/3206748/98136305-3bce1f00-1eda-11eb-9606-173e42056b47.png">

**Comment by DanTup** [comment]
@haashem yikes! Could you file a new issue, and include details of how you're running the tests (for example whether using F5, or the CodeLens links) and how reproducible it is.

Thanks!
