### ISSUE TITLE
Provide settings to disable snippets in completion lists

### ISSUE THREAD

**Issue by svipas** [Dart-Code/Dart-Code#2625]
As I can see you have this class https://github.com/Dart-Code/Dart-Code/blob/684a3ad5f15529e507139f95b9617240ec20a56a/src/extension/providers/snippet_completion_item_provider.ts which registers snippets to the completion provider. And you're using snippets/dart.json and snippets/flutter.json in here https://github.com/Dart-Code/Dart-Code/blob/b6aac604c02af46d66f99e01650c2b4b50c9edfc/src/extension/extension.ts#L340. In my opinion this is redundant because VS Code handles snippets automatically if you add them into `package.json` file like this:

```
		"snippets": [
			{
				"language": "dart",
				"path": "./snippets/dart.json"
			},
			{
				"language": "dart",
				"path": "./snippets/flutter.json"
			}
		]
```

The issue with registering them inside extension itself by using completion provider removes ability to use [Control Snippets](https://github.com/svipas/vscode-control-snippets) extension which gives ability to disable/enable snippets.

My suggestions is to simply remove SnippetCompletionItemProvider class and also registration in extension.ts for flutter and dart snippets and simply add snippets in package.json as mentioned above. This gives ability to easy control snippets and it uses default VS Code mechanism.

Also, it would be cool to separate snippets for dart and flutter into their repos/extension dirs. Keep `snippets/dart.json` in this repo https://github.com/Dart-Code/Dart-Code and move `snippets/flutter.json` to this repo https://github.com/Dart-Code/Flutter since they are different tools and it gives ability to easily disable/enable snippets for Dart and Flutter separately.

I hope it makes sense, if needed I could provide a PR. Thanks a lot!

**Comment by DanTup** [comment]
That's how things used to be - however the built-in snippets cannot be dynamically filtered, which means once you have the Flutter extension installed, you would always get Flutter snippets in your (non-Flutter) Dart projects. I did request support from VS Code to handle this (https://github.com/Microsoft/vscode/issues/26943) but it was rejected and were told to do it this way.

I don't think it would be a good change to go back to that unless VS code provides some way for us to filter them. Also - FWIW, that extension works by manipulating the package.json file of installed extensions - that's not really an intended extension point and could have unintended side effects, so I'm not sure it makes sense to make changes to support/encourage that.

**Comment by svipas** [comment]
If thats not an option, maybe you could add config which enables/disables these snippets?

**Comment by DanTup** [comment]
Yeah, that seems reasonable enough!

**Comment by svipas** [comment]
Thanks!
