### ISSUE TITLE
unused_field and unused_element errors for private fields in classes

### ISSUE THREAD

**Issue by vin-fandemand** [Dart-Code/Dart-Code#2630]
Consider the following snippet
```
class TestClass {
  final String field;
  String _field;

  TestClass(this.field);

  void method() {
    _field = '';
  }
}
```
The private field `_field` is not detected as being used although it is being used inside one of the methods. I have seen it quite often when I develop in Flutter where I often initialize a private field inside an `initState` method for a `StatefulWidget`. Is this a bug or am I not understanding it correctly?
![image](https://user-images.githubusercontent.com/64597233/87196444-0157cb00-c2c8-11ea-875d-633be2868168.png)

**Comment by DanTup** [comment]
This happens when you don't *read* the value anywhere. A variable that is only set is still considered "unused", since it looks like a mistake if you're set a variable but never done anything with it.

**Comment by vin-fandemand** [comment]
If we remove the field based on the suggestion, the program will fail with an error. So I find the message quite misleading.

**Comment by DanTup** [comment]
The suggestions in the message are only to try to guide you. If you chose to remove the field, you'll need to also remove other references to it (maybe the fix could do this, but I don't know how complicated that would be). The message also suggests you could use (read) the field.

I don't think it would make sense to stop the linter triggering on this code as you'd no longer be alerted to useless variables that you are setting but never using (which could indicate a bug - it doesn't make much sense to assign a variable and never use it).

Both the lint and the fix come from the Dart SDK, so changing these is not something we can do from the VS Code extension. If you have suggestions to improve them, they can be raised at https://github.com/dart-lang/linter (for the lints) and https://github.com/dart-lang/sdk for the quick-fixes.

Thanks!
