### ISSUE TITLE
devcontainer with WSL2 and Docker: unable to debug due to "Exception attempting to connect to the VM Service"

### ISSUE THREAD

**Issue by fhuonder** [Dart-Code/Dart-Code#2640]
Hi,

I have the following Setup:

- Windows 10 with WSL 2 and Docker
- VSCode 1.47.1
- Dart-Code v3.12.2

I have the following devcontainer.json:
```json
{
	"name": "test-app",
	"dockerFile": "Dockerfile",
	"extensions": [
		"dart-code.dart-code",
		"dart-code.flutter",
		"k--kato.intellij-idea-keybindings",
		"abhiagr.logcat",
		"humao.rest-client"
	],
	"settings": {
		"terminal.integrated.shell.linux": "/bin/bash",
		"dart.flutterSdkPath": "/flutter",
		"workbench.editor.enablePreview": false,
		"workbench.editor.enablePreviewFromQuickOpen": false,
		"dart.lineLength": 120,
		"files.associations": {
			"*.arb": "json"
		}
	},
	"containerEnv": {
		"ADB_SERVER_SOCKET": "tcp:host.docker.internal:5037"
	},
	"remoteEnv": {
		"ANDROID_SDK_ROOT": "/android-sdk",
		"ANDROID_HOME": "/android-sdk"
	},
	"postStartCommand": "flutter doctor -v",
	"mounts": [
		"source=/var/run/docker.sock,target=/var/run/docker.sock,type=bind,consistency=delegated"
	],
	"runArgs": [
		"--privileged"
	]
}
```

The following Dockerfile for the container:
```dockerfile
FROM ubuntu:18.04

ARG ANDROID_COMMANDLINE_TOOLS_ARTIFACT=https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
ARG ANDROID_PLATFORM=android-28
ARG ANDROID_BUILD_TOOLS=28.0.3
ARG FLUTTER_ARTIFACT=https://storage.googleapis.com/flutter_infra/releases/dev/linux/flutter_linux_1.20.0-7.1.pre-dev.tar.xz

# Hack to get openjdk to install in a container
RUN mkdir -p /usr/share/man/man1 \
    && mkdir -p /usr/share/man/man7

# Tools
RUN apt-get update && apt-get install -y curl git xz-utils lib32stdc++6 unzip openjdk-8-jdk-headless

# Android SDK
RUN curl -o commandlinetools-linux.zip ${ANDROID_COMMANDLINE_TOOLS_ARTIFACT}
RUN mkdir -p android-sdk/cmdline-tools && unzip /commandlinetools-linux.zip -d android-sdk/cmdline-tools
RUN rm /commandlinetools-linux.zip
ENV PATH="/android-sdk/cmdline-tools/tools/bin:/android-sdk/build-tools:/android-sdk/platform-tools:${PATH}"

# SDK manager
RUN yes | sdkmanager --licenses
RUN sdkmanager "platforms;${ANDROID_PLATFORM}" "platform-tools" "build-tools;${ANDROID_BUILD_TOOLS}"

# Flutter
RUN curl -o flutter.tar.xz ${FLUTTER_ARTIFACT}
RUN tar xf flutter.tar.xz
RUN rm flutter.tar.xz
ENV PATH="/flutter/bin:${PATH}"

RUN flutter config --no-analytics
```

On Windows, I configured ADB with `adb -a -P 5037 nodaemon server`. This way (with the env variable `ADB_SERVER_SOCKET` (see devcontainer.json) adb in the container sees my devices attached via USB (or the emulator running in Windows).

My launch.json
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Demo",
            "program": "demo/lib/main.dart",
            "request": "launch",
            "type": "dart",
        }
    ]
}
```

**The problem**:

When I want to debug my app from vscode the following error occurs:
```
Exception attempting to connect to the VM Service: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 48590
This was attempt #1. Will retry in 0:00:00.100000.
```
This message repeats every minute with a new port. On the device I see a white screen.

I already tried setting 
```
"args": [
    "--host-vmservice-port=9999"
]
```
in the launch.json and 
```
"forwardPorts": [
    9999
]
```
in the devcontainer.json

In that case the log says:
```
Forwarded host port 9999 to device port 46347 for Observatory
Connecting to service protocol: http://127.0.0.1:9999/PH5EDsAqjMw=/
Exception attempting to connect to the VM Service: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 48590
This was attempt #1. Will retry in 0:00:00.100000.
```

Interesting is, when I run `flutter run`, from the CLI (of the container), the application launches on the device. But the same error occurrs.

What am I doing wrong? Can anybody help me out?

Regards,
Florian

**Comment by DanTup** [comment]
I'm not particularly familiar with `adb` so I'm not exactly sure why this doesn't work. If it's happening from `flutter run` in the terminal, I don't think it's related to the VS Code extension.

My guess would be that something is wrong with the port forwarding (it seems like there may be multiple hops here - from the container forwarded to the host, and then the host forwarded to the device?). You could try connecting to the Observatory address in Windows to see if it works there, and also running `adb forward --list` on both Windows and the container to see what the forwarding looks like.

Another thing you might be able to try is using `adb connect` from inside the container with the IP/port of the device so its ADB connects directly to the USB device (you may ned to run `adb tcpip <port>` from Windows first to instruct the phone to listen on that port for adb connections).

Out of interest - why are you running inside WSL and not just natively on Windows?

**Comment by fhuonder** [comment]
Hi Dan,

I am not familiar with adb in detail as well.

I also think that it is a problem of the hops. As I understand it the debugger wants to connect to the observatory service on the device and this does not work. Therefore the exception.
What I see in the logs is that `--host-vmservice-port=9999` results in adb creating a port-forwarding from 9999 to the port of the observatory service on the device. This is on the Windows-side. Means, in Windows, when I open the observatory-URL I get a response.
In my opinion/understanding the problem now is that the container does not connect to port 9999 (despite the forwardPort and the vm property) but to some other port. This other port is even not the same as adb makes the forwarding to. I do not find out where this port comes  from.
I also tried setting `--enable-vm-service=<port>` with port 9999 but this has no effect.

I think `adp tcpip` is not needed because with `adb -a -P 5037 nodaemon server` and `ADB_SERVER_SOCKET` I see the devices with `adb devices` from the container. 

My understanding of the whole topic is not that deep so I don't know where to look further. Any idea?

What do you mean by "why are you running inside WSL and not just natively on Windows?" I am using WSL2 as shell and now I want to make my projects work with the remote containers of vscode. Or what did you mean?

Regards,
Florian

**Comment by DanTup** [comment]
> I think `adp tcpip` is not needed because with `adb -a -P 5037 nodaemon server` and `ADB_SERVER_SOCKET` I see the devices with `adb devices` from the container.

I'm not very familiar with this, but it sounded like this means there are two `adb`s running - one inside the container, and one outside? If so, I wondered if this was breaking the port forwarding. I think by using `adb tcpip` you would be able to have `adb` in the container connect directly to the device over tcpip, so the `adb` on Windows is cut out. This might then simplify the port forwarding (since `adb` in the container would be mapping directly onto the device?).

> What do you mean by "why are you running inside WSL and not just natively on Windows?" I am using WSL2 as shell and now I want to make my projects work with the remote containers of vscode. Or what did you mean?

I'm wondering why you're using WSL2/Docker at all. Why not just open your project directly in VS Code on Windows without any WSL/Docker?

**Comment by fhuonder** [comment]
Ah, I see what you mean with the adb tcpip. I will try that out tomorrow and come back to you.

Why WSL2/Docker:
In our team we have multiple projects with different environments (and different flutter versions). Our idea with WSL2/Docker is to have the development environment for each project bundled with the source code. Further a plus is that all developers have exact the same environment, the same tools etc.

**Comment by fhuonder** [comment]
Hi,

I tried with `adb tcpip` and it works for a real device.
Unfortunately this solution is not entirely satisfactory because
- I cannot connect to an emulator because it is not accessible via network
- I always have to lookup the IP of the connected device and connect to it manually, so the process can hardly be automated

A I understood this is a Flutter issue, so I will open an according issue there.

Thanks a lot for your support...

**Comment by DanTup** [comment]
No worries - sorry I didn't have a working solution. I'm not sure if it's an ADB issue or Flutter issue (or if this is a supported flow for either), but I think starting with a Flutter issue is the best option. Thanks!

**Comment by woprandi** [comment]
I checked code : https://github.com/Dart-Code/Dart-Code/blob/master/src/extension/providers/debug_config_provider.ts#L706-L708
I also tried "vmServicePort": 10388 without success

**Comment by DanTup** [comment]
@woprandi please file a new issue with detailed steps to repro. I'm not sure this is the same, as you're using an emulator but the original issue was about connecting adb inside the container to a physically connected USB device.

It's not clear to me where the emulator is running in your case, or whether in the case that works from the terminal whether you're connecting a debugger to the VM Service.

Thanks!
