### ISSUE TITLE
Flutter support for --dart-define in vscode plugin.

### ISSUE THREAD

**Issue by nvsravank** [Dart-Code/Dart-Code#2641]
Currently the plugin allows additional arguments to be sent to all flutter commands.
While this maybe useful in some cases the utility is diminished when I am trying to use the Dart feature to send defines that can then be utilized to setup the environment correctly. 

The reason for dart define is to utilize compile time variables as discussed in this article.
https://itnext.io/flutter-1-17-no-more-flavors-no-more-ios-schemas-command-argument-that-solves-everything-8b145ed4285d

Now when I add the ---define argument in vccode section for preferences/ settings, the only place to add it is in the 
"Dart: Flutter Additional Args" section.
This breaks all other commands that are super useful like the automatic flutter get.

The request is to separate the --dart-define into its own setting that is they used only for the flutter run command and not for all the other flutter commands

**Comment by DanTup** [comment]
Arguments for `flutter run` can be defined in the `launch.json` file. If you don't already have one, you can create one using the **Debug: Open launch.json** command in VS Code, then selecting **Dart & Flutter**. You can then add an `args` field, like this:

```js
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Dart",
			"program": "lib/main.dart",
			"request": "launch",
			"type": "dart",
			"args":[
				"--dart-define=xyz"
			]
		}
	]
}
```

Having this as a setting makes less sense, as they tend to be quite application-specific. This way you can easily switch between launch configurations (on the Run side bar).

Let me know if you have any issues with this!

**Comment by nvsravank** [comment]
Thank you very much. This is working as I expect it to. These instructions should be in the reader for the vscode flutter. Did not know what options are available in the launch.json even though I opened it in vscode. 


Sent from Yahoo Mail for iPhone


On Wednesday, July 15, 2020, 1:28 PM, Danny Tuppeny <notifications@github.com> wrote:




Arguments for flutter run can be defined in the launch.json file. If you don't already have one, you can create one using the Debug: Open launch.json command in VS Code, then selecting Dart & Flutter. You can then add an args field, like this:
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Dart",
			"program": "lib/main.dart",
			"request": "launch",
			"type": "dart",
			"args":[
				"--dart-define=xyz"
			]
		}
	]
}
Having this as a setting makes less sense, as they tend to be quite application-specific. This way you can easily switch between launch configurations (on the Run side bar).

Let me know if you have any issues with this!

**Comment by DanTup** [comment]
These don't show up in the code completion, as these args are not known to VS Code - you can just pass any arguments that Flutter supports (and VS Code does not have a list of these - they may also change across Flutter versions).

I did experiment with just hard-coding some in completion (see https://github.com/Dart-Code/Dart-Code/issues/2497#issuecomment-634550870), however I'm concerned about maintaining them, and also it makes it look like you cannot enter your own.

I think we should probably have a page in the docs that can easily be found if you search the web for "using --dart-define in VS Code" or similar though, so I'll keep this open for that.

**Comment by Musharaf13** [comment]
Thank you so much it worked.

**Comment by uc-dve** [comment]
> Arguments for `flutter run` can be defined in the `launch.json` file. If you don't already have one, you can create one using the **Debug: Open launch.json** command in VS Code, then selecting **Dart & Flutter**. You can then add an `args` field, like this:
> 
> ```js
> {
> 	"version": "0.2.0",
> 	"configurations": [
> 		{
> 			"name": "Dart",
> 			"program": "lib/main.dart",
> 			"request": "launch",
> 			"type": "dart",
> 			"args":[
> 				"--dart-define=xyz"
> 			]
> 		}
> 	]
> }
> ```
> 
> Having this as a setting makes less sense, as they tend to be quite application-specific. This way you can easily switch between launch configurations (on the Run side bar).
> 
> Let me know if you have any issues with this!

I have tried the above but it did not worked below is the syntax which worked for me

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Flutter",
            "request": "launch",
            "type": "dart",
            "args": [
                "--dart-define", "UC_APP_NAME=Comptia_test",
                "--dart-define", "UC_APP_SUFFIX=.comptia.test",
                "--dart-define", UC_APP_ICON=uc_comptia_test",
            ],
            "console": "debugConsole",
        }
    ]
}
```

**Comment by Hwan-seok** [comment]
official docs:
https://dartcode.org/docs/using-dart-define-in-flutter/

**Comment by HEBOS** [comment]
This doesn't work anymore.

**Comment by DanTup** [comment]
@HEBOS I just tested this and it seems to work correctly for me - could you file a new issue with an example project/code to reproducethe issue you're seeing? Thanks!

![image](https://github.com/user-attachments/assets/6542dba1-3835-4307-a542-72dd83f38a06)

**Comment by bensonarafat** [comment]
I am getting this issue. I have done everything possible but it will return an empty var

**Comment by DanTup** [comment]
@bensonarafat please check you are using `const` as shown above. If it still doesn't work, please file a new issue and include a small sample project that includes both the code that is printing the empty variable, and a copy of the `launch.json` you're using to set it. Thanks!

**Comment by bensonarafat** [comment]
Okay, great, I have been on this all night
