### ISSUE TITLE
code actions (lightbulb) does not show full list of actions

### ISSUE THREAD

**Issue by HawkarShwany** [Dart-Code/Dart-Code#2643]
code actions in visual studio code shows only 3 actions for flutter which are all extracting widgets. How can I show more actions like wrapping widgets, removing widgets, etc. I have changed every setting I found but I still couldn't add them. I have an old windows machine and it has all those actions. I just bought a Macbook and after I configured it for Flutter development, I have this issue. I tried configuring all the settings like my old machine and installed all the extensions but couldn't add those actions. I also tried uninstalling and installing dart code and flutter extensions. still didn’t work.

any Ideas?

**Comment by DanTup** [comment]
Could you provide:

- An exact code sample where you see this issue
- The exact position of your cursor when you're invoking the lightbulb menu
- A specific example of one of the actions that does not appear that you would expect to
- The full output of `flutter --version`

Thanks!

**Comment by HawkarShwany** [comment]
I get this when I hover on the widget, select it, put the cursor before/after the widget.

<img width="956" alt="Screen Shot 2020-07-16 at 1 48 01 PM" src="https://user-images.githubusercontent.com/52130074/87662608-1f5f7880-c76b-11ea-88b9-288312b09b45.png">

this is what I'm expecting to get 

![Capture](https://user-images.githubusercontent.com/52130074/87662752-5766bb80-c76b-11ea-8278-c376cdd8e065.JPG)

Although I know this is related to the settings because I don't have this issue in my other workspaces, I can't find where to change that setting.
I also tried stackoverflow and they pointed me here

Thank you for your help.

**Comment by DanTup** [comment]
Can you provide a full-file example (pasted here, so I can copy it) that has this issue? And also test with the exact same code (and exact same cursor location) on your two machines? I can't think of any settings that would really effect this.

Also, can you confirm:

- The exact Flutter version on each machine
- Whether you have the `dart.previewLsp` setting enabled on either machine
- Whether there are any errors shown if you click Help -> Toggle Developer Tools in VS Code and click the Console tab

Thanks!

**Comment by HawkarShwany** [comment]
This is a simple page where I have this issue with it.

```(dart)
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import '../../pages/product_detail.dart';
import '../../pages/search_page.dart';
import '../../pages/items_page.dart';
import '../../utils/navigator.dart';
import '../../utils/screen.dart';
import '../../utils/theme_notifier.dart';

class CategoryCard extends StatelessWidget {
  const CategoryCard({
    Key key,
    @required this.themeColor,
    @required this.imageUrl,
    @required this.title,
  }) : super(key: key);

  final ThemeNotifier themeColor;
  final String imageUrl;
  final String title;

  @override
  Widget build(BuildContext context) {
    return InkWell(
      onTap: () {
        /*
        * this should show more products or sub categories
        *
        */
        Navigator.push(
            context, MaterialPageRoute(builder: (context) => ItemsPage()));
        // Nav.route(context, ProductDetailPage(
        //   price: 200,
        //   productName: 'gloves',
        //   priceBeforeDiscount: 220,
        //   imgUrl: 'assets/images/gloves.jpg',
        //   description: 'lorem ipsum',
        // ));
      },
      child: Container(
        // width: ScreenUtil.getWidth(context) /2 ,
        // margin: EdgeInsets.only(left: 25, top: 8, right: 12, bottom: 9),
        margin: EdgeInsets.symmetric(vertical: 15, horizontal: 20),
        // margin: EdgeInsets.all(20),
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(8),
        ),
        child: Container(
          // height: 200,
          child: Stack(
            children: <Widget>[
              Container(
                  width: ScreenUtil.getWidth(context),
                  // height: 200,
                  child: ClipRRect(
                    borderRadius: BorderRadius.only(
                      topLeft: Radius.circular(8),
                      topRight: Radius.circular(8),
                      bottomRight: Radius.circular(8),
                      bottomLeft: Radius.circular(8),
                    ),
                    child: Image.asset(
                      "assets/images/gloves.jpg",
                      fit: BoxFit.cover,
                    ),
                  )),

              //lable card
              Align(
                alignment: Alignment.bottomCenter,
                child: Container(
                  decoration: BoxDecoration(
                      color: Colors.white,
                      borderRadius: BorderRadius.only(
                          topLeft: Radius.circular(8),
                          topRight: Radius.circular(8))),
                  width: 140,
                  height: 40,
                  child: Align(
                    alignment: Alignment.center,
                    child: Text(
                      title,
                      style: GoogleFonts.poppins(
                        fontSize: 18,
                        color: themeColor.getColor(),
                        fontWeight: FontWeight.w300,
                      ),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

`Flutter (Channel beta, 1.19.0-4.3.pre, on Mac OS X 10.15.5 19F101, locale en)`
`Flutter (Channel beta, 1.19.0-4.2.pre, on Microsoft Windows [Version 10.0.18363.900], locale en-US`

dart.previewLsp is not enabled on any of them

the developer tools show these
```
[xabikos.JavaScriptSnippets]: Unknown language in `contributes.JavaScriptSnippets.language`. Provided value: vue
_logMessageInConsole @ abstractExtensionService.ts:411
console.ts:137 [Extension Host]% 22222
4log.ts:185  INFO Setting search error: XHR timeout: 5000ms
log.ts:197   ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
```

**Comment by DanTup** [comment]
The code you ave above is different to what's int he screenshot - can you give an example of an exact position in the code you're opening quick-fixes, and example of a quick-fix you expect to see but do not? Thanks!

**Comment by kwaun** [comment]
Maybe this is related...
```
[...]
      body: ListView.builder(),
[...]
```
and if I click on the lightbulb, there is no "Add required argument 'itemBuilder'" option anymore.
 It shows a lot of "Wrap" and "Extract" options actually but not this one.
I use flutter dev channel.

**Comment by DanTup** [comment]
> `body: ListView.builder(),`

That code doesn't seem to exist in the code snippet above. Are you able to give a complete code sample and exact location of where you're not seeing an action (and which one) so I can try to reproduce with the same code here? Thanks!

**Comment by HawkarShwany** [comment]
true, it is not the same code in the screenshot. However, I put this because this is a standalone widget that can be rebuilt without needing any dependency. This also has the same problem as the above screenshots. If I try opening the code actions on any widget I get the list in the first picture, but I expect the list in the second one.

Thanks,

**Comment by kwaun** [comment]
> > `body: ListView.builder(),`
> 
> That code doesn't seem to exist in the code snippet above. Are you able to give a complete code sample and exact location of where you're not seeing an action (and which one) so I can try to reproduce with the same code here? Thanks!

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Test',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: TestPage(),
    );
  }
}

class TestPage extends StatefulWidget {
  @override
  _TestPageState createState() => _TestPageState();
}

class _TestPageState extends State<TestPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Test Page'),
      ),
      body: ListView.builder(), // <<<<==== here
    );
  }
}
```

![github](https://user-images.githubusercontent.com/12612253/88487080-768ef580-cf82-11ea-97de-6f4251be8494.png)

If I put the cursor in "builder" and then I click press CTRL+. there is no "Add required argument 'itemBuilder'" option that it used to show in the context menu.

So sorry for interfering. Maybe I should open a new issue...

**Comment by DanTup** [comment]
@kwaun I can repro that - seems to be an issue with named constructors. I've opened https://github.com/dart-lang/sdk/issues/42843.

@HawkarShwany can you provide some exact code with an exact fix that is not appearing where you expect so I can try to reproduce here and debug? It's difficult to track down without specifics. Thanks!
