### ISSUE TITLE
Analysis Options file reports error everytime vs code launches

### ISSUE THREAD

**Issue by gkrawiec** [Dart-Code/Dart-Code#2644]
The first line of my analysis_options file is in include statement
`include: package:lint/analysis_options.yaml`

the necessary pub is added in pubspec.

Every single time i launch vs code or the workspace this error is reported

`The include file package:lint/analysis_options.yaml in /Users/myuser/Documents/code/flutter/prog/analysis_options.yaml cannot be found.dart(include_file_not_found)`

But all I have to do is open the analysis_options.yaml file and save it for the error to go away. 
Is this a dart code issue?

**Comment by DanTup** [comment]
Hmm, I'm not sure - I'm not able to reproduce this.

I presume you have `lint` listed in your `pubspec.yaml` and have fetched packages? Can you check that `lint` appears in your `.packages` file and also the `.dart_tool/package_config.json` file and has a valid path to the package in your pubspec?

Can you reproduce it in a new clean project? (I created one using **Dart: New Project** and then added the package/include there). If so, could you enable the [server instrumentation log](https://dartcode.org/docs/logging/#analyzer-instrumentation) and then restart VS Code to reproduce the issue (both the error appearing, and then disappearing when you open it).

Thanks!

**Comment by gkrawiec** [comment]
lint IS in the `pubspec.yaml`
packages have been fetched
lint appears in the `.packages` file
lint appears in the ` .dart_tool/package_config.json`

in fact the linting works perfectly including the rules added with this package.

The issue only shows up when starting vscode or reopening the workspace
```
Version: 1.47.1
Commit: 485c41f9460bdb830c4da12c102daff275415b53
Date: 2020-07-13T22:43:02.577Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0
```

and the specific error goes away after saving the `analysis_options.yaml` file a single time. The error does not come back until the next vs code lauch or workspace open.

I tried a new flutter project and was NOT able to reproduce.

Maybe something with my installation or setup. I am emailing you the log file in case you are still interested in figuring out what it is.

The log is basically 1) launch vs code to my previously open workspace 2)wait till the first lint is completed 3) open analysis_options.yaml 4) press command-S to save 5) quit.


thank you.

**Comment by DanTup** [comment]
There's nothing revealing in the log. If this only happens in this project, could you try making a copy of it (with a different path) then see if you can repro there? (you may need to run `pub get` and then restart VS Code to confirm).

If it doesn't repro in a copy, try renaming the `~/.dartServer` folder and see if that fixes the main project (if so, there may be something bad in there).

If it does repro in the copy, could you try clearing out any sensitive code the make a small repro, and then providing a full zip of that file?

**Comment by DanTup** [comment]
Also - maybe worth trying to delete `.dart_tool` and/or `build` folders to see if that changes anything too.

**Comment by gkrawiec** [comment]
It did NOT repro in the copy, so I then deleted `~/.dartServer` and that solved it. Initial linting seems to be going faster too.
thank you!

**Comment by DanTup** [comment]
Thanks for confirming!

@bwilkerson @scheglov FYI - seems like something stale in `.dartServer` was causing an incorrect error to be generated (I guess at some point - perhaps before `pub get` had been run - the error was valid, but after fetching the package, it was no longer).
