### ISSUE TITLE
How to enable experiments?

### ISSUE THREAD

**Issue by RblSb** [Dart-Code/Dart-Code#2645]
After i do `flutter create foo`, changing `sdk:` to `">=2.8.0 <3.0.0"` and creating `<project_root>/analysis_options.yaml` with:
```
analyzer:
  enable-experiment:
    - non-nullable
```
I can write `int? foo = 3;` in `_incrementCounter` method, but if i fix type errors and press F5 with connected android then i get a lot of compiler errors:
`This requires the 'non-nullable' experiment to be enabled.
Try enabling this experiment by adding it to the command line when compiling and running.`
I'm also tries this `.vscode/settings.json`:
```json
{
	"dart.buildRunnerAdditionalArgs": [
			"--enable-experiment=non-nullable"
	],
	"dart.analyzerAdditionalArgs": [
			"--enable-experiment=non-nullable"
	],
	"dart.vmAdditionalArgs": [
			"--enable-experiment=non-nullable"
	],
	"dart.flutterAdditionalArgs": [
			"--dart-define=enable-experiment=non-nullable"
	],
}
```
But first three settings doesn't change things, and latest crash flutter daemon on finding emulators. Some hints how to correctly enable experiments?

**Comment by DanTup** [comment]
My understanding is that this isn't ready for Flutter yet:

https://dart.dev/null-safety

> Because null safety is still in tech preview, *don’t use null safety in production code*. In particular, the Flutter framework doesn’t yet support null safety.

**Comment by RblSb** [comment]
Okay, found solution if someone interested:
Install some Flutter dev build and set `sdk: ">=2.9.0-21.0.dev <3.0.0"`
Create .vscode/launch.json:
```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Flutter",
			"request": "launch",
			"type": "dart",
			"args": [
				"--enable-experiment=non-nullable",
				"--no-sound-null-safety"
			],
		}
	]
}
```
And create `analysis_options.yaml` like above.
In Flutter with Dart 2.8 null safety is not really implemented in compiler, just in analyzer ([as i understand](https://github.com/flutter/flutter/issues/40490#issuecomment-593732921)). That was hard path to make it work...
