### ISSUE TITLE
Add option to create unit test for library

### ISSUE THREAD

**Issue by bsutton** [Dart-Code/Dart-Code#2650]
The eclipse ide has a nice little feature which will create a unit test for a java file.

I was hoping you could add something similar.

I have a file in:

lib/src/docker/images.dart

I open the vscode explorer to the above file and open the context menu for that file.
There is an option 'create unit test'

The option creates a library as per:
test/src/docker/images_test.dart

A nice bonus is that it generates a basic template for a unit test.

**Comment by DanTup** [comment]
We currently have this command that lets you jump between test/implementation (no default keybinding though):

![Screenshot 2020-07-16 at 17 49 28](https://user-images.githubusercontent.com/1078012/87699413-bc7ed900-c78c-11ea-84fe-7de221e3d43e.png)

It currently only shows up when the implementation/test for the open file exists. However I think in the case where you're in an implementation file and the test does not exist, we should still show the command and if you select it, prompt to create:

![Screenshot 2020-07-16 at 17 50 34](https://user-images.githubusercontent.com/1078012/87699510-de785b80-c78c-11ea-90b5-19103e2bd86c.png)

If you agree, it'll create the file (and any required folders along the way) and populate it with a test stub (using `flutter_test` or `test` depending on the open project):

![Screenshot 2020-07-16 at 17 51 07](https://user-images.githubusercontent.com/1078012/87699580-f819a300-c78c-11ea-8442-3237681e40c0.png)

What do you think?

**Comment by DanTup** [comment]
Oh, I forgot to mention - the reason I'm not sure about the context menu is that I don't know if we can add things conditionally based on the paths (if only show the option if it's a test file that has an implementation, or a file inside lib).

I'll have a look though - if we can do that, we could also add this to the context menu without it showing up in places that wouldn't work.

**Comment by bsutton** [comment]
I think that works. The context menu would be nice as it improves interoperability.

**Comment by DanTup** [comment]
I added a context menu to go *to* tests for anything in the `lib` folder:

https://dartcode.org/releases/v3-13/#test-file-creation

Beta is here: https://github.com/Dart-Code/Dart-Code/releases/tag/v3.13.0-beta.3

**Comment by bsutton** [comment]
I've just installed the beta.

Very nice :D

**Comment by bsutton** [comment]
It would be nice if the sample test script used the name of the dart file.

If the original dart file is `certificate.dart`

Currently you generate:

```
void main() {
  test('Test ...', () async {
    
  });
}
```

It would be nicer if it generated:

```
void main() {
  test('Certificate ...', () async {
    
  });
}
```

Also not certain if 'async' should be the default.
Almost non of my unit tests use async but then my usage patterns may not be normal as I build a lot of cli scripts that don't use any futures.

**Comment by bsutton** [comment]
It should also import the original file:

```
import 'package:test/test.dart';
import 'package:mypackage/src/certificate.dart';
```

**Comment by DanTup** [comment]
> It would be nice if the sample test script used the name of the dart file.

Seems reasonable, I'll take a look.

> Also not certain if 'async' should be the default.

I figured there was no disadvantage to having async there if you don't use it, but if you did you'd otherwise need to add it (and for Flutter, I think it's likely you always would - since many of the `tester` methods are async).

> It should also import the original file:

Ah, yes. Though this gets a bit more tricky as we don't have easy access to the package name without parsing the pubspec. For now I might rely on people just using the auto-import completion, and maybe once #1996 is done and we have easier access to a package map, use that.
