### ISSUE TITLE
Format on save done even with "editor.formatOnSave": false,

### ISSUE THREAD

**Issue by a14n** [Dart-Code/Dart-Code#2652]
I'm not sure if the issue is in VSCode or other thing but every time I save a file it is formatted tough my config disables this behaviour.

VSCode: 1.47.1
DartCode: 3.12.2

```
    "editor.formatOnPaste": false,
    "editor.formatOnType": false,
    "editor.formatOnSave": false,
```

**Comment by DanTup** [comment]
Where do you have this config set? It could be set in a few places:

- In VS Code User Settings at the top level
- In VS Code User Settings in a `"[dart]"` block
- In your workspace/folder settings (`.vscode/settings.json` or `.code-workspace` file) at the top level
- In your workspace/folder settings (`.vscode/settings.json` or `.code-workspace` file) in a `"[dart]"` block

If you're looking in the settings UI, it might not be obvious if you have a language-specific override (https://github.com/microsoft/vscode/issues/74195), so you may need to use the JSON views to see the `"[dart]"` blocks (FWIW, the recommended settings offered by the extension will write into a `"[dart]"` section to avoid affecting other languages.

**Comment by a14n** [comment]
Thanks for your help. I actually found `"editor.formatOnSave": true` somewhere under `[dart]`. Not sure how this line landed here.

**Comment by DanTup** [comment]
A recent version of the plugin would pop up asking if you wanted to use recommend settings - I suspect that's where it came from (you can see the recommended settings [here](https://dartcode.org/docs/recommended-settings/)). I was slightly torn about including the format options in there tbh.

FWIW, if you're working on Flutter you can disable i just for the Flutter repo by adding it to folder settings, or if you open only a subset of the Flutter repo using a `.code-workspace` file, you can add it into the workspace file.
