### ISSUE TITLE
Variables in mixin do not appear in Intellisense window

### ISSUE THREAD

**Issue by hasimyerlikaya** [Dart-Code/Dart-Code#2656]
I use VSCode for Flutter. 
I noticed a situation with mixins. 
I cannot access the variables I use in the mix with IntelliSense. 
How can I fix this problem?

![image](https://user-images.githubusercontent.com/7986394/87972968-7dc08a00-cad0-11ea-8785-e492bc81ad39.png)

![image](https://user-images.githubusercontent.com/7986394/87973146-beb89e80-cad0-11ea-8906-0de69a959607.png)

**Comment by DanTup** [comment]
Can you confirm what version of Flutter is shown in the status bar? I tried to reproduce this but it seemed to work:

<img width="547" alt="Screenshot 2020-07-23 at 16 16 18" src="https://user-images.githubusercontent.com/1078012/88304247-eccff580-ccff-11ea-9896-6226f2216849.png">

**Comment by hasimyerlikaya** [comment]
I tested it for Flutter now, the problem seems to have improved. I've been having this problem before.

Actually, I prepared this image in Dart Console application. Now I looked again still not working for Dart Console application.

Dart version: 2.8.4

Thank you.

**Comment by DanTup** [comment]
Ah yes, I can repro in v2.8.4. However I can't repro in a dev v2.9.0 build, so it seems like this has been fixed somewhere between there.

If you see it again when v2.9 of the Dart SDK is released, please let me know. Thanks!
