### ISSUE TITLE
Hard to read exception

### ISSUE THREAD

**Issue by tbm98** [Dart-Code/Dart-Code#2664]
On Android Studio. exception appear, red screen and stackTrace
<img width="1440" alt="Screen Shot 2020-07-23 at 3 41 34 PM" src="https://user-images.githubusercontent.com/52562340/88267641-4e419580-ccfb-11ea-98c6-f369c124b6ce.png">

Same on VSCode, I can't find error
<img width="1440" alt="Screen Shot 2020-07-23 at 3 43 08 PM" src="https://user-images.githubusercontent.com/52562340/88267716-6c0efa80-ccfb-11ea-9091-de77e7830f27.png">

**Comment by DanTup** [comment]
Are you able to reproduce this in code you can share? In the IntelliJ screenshot it looks like the stack includes user code (`FailWidget`), but that doesn't appear in the stack in VS Code which means it's not sure which code to show (by default VS Code is set to "debug my code" which means it will always try to break in user code, rather than SDK code).

**Comment by tbm98** [comment]
So how can I disable 'debug the code'? And show fully of stackTrace like
android studio ?

**Comment by tbm98** [comment]
Hi.
<img width="265" alt="Screen Shot 2020-07-23 at 7 32 47 PM" src="https://user-images.githubusercontent.com/52562340/88286789-7f31c280-cd1b-11ea-936b-e5020091abb8.png">
is there similar to `run` in Android Studio

**Comment by DanTup** [comment]
In the status bar in your screenshot (bottom left) it says "Debug my code". If you click on it, it will cycle between the different debug options ("Debug my code", "Debug my code + packages", "Debug my code + packages + sdk").

This will probably cause the code to break as you'd expect.

However, I'm still curious why there's no use code in your stack. Are the two exceptions shown above (Android Studio and VS Code) the same exception from the same project?

> is there similar to `run` in Android Studio

Yep, the one in your screenshot is the same - "Run without Debugging".

**Comment by tbm98** [comment]
> However, I'm still curious why there's no use code in your stack. Are the two exceptions shown above (Android Studio and VS Code) the same exception from the same project?

Yep, they are same exception from the same project. server is down so `Text` get a null value

**Comment by DanTup** [comment]
If you untick "All exceptions" in VS Code in the bottom left corner and try again, does it then break properly and show the red exception popup?

**Comment by tbm98** [comment]
debug my code


<img width="1440" alt="Screen Shot 2020-07-23 at 9 04 51 PM" src="https://user-images.githubusercontent.com/52562340/88295984-549a3680-cd28-11ea-9b5d-e3097bf04960.png">

debug my code + packages
<img width="1440" alt="Screen Shot 2020-07-23 at 9 02 32 PM" src="https://user-images.githubusercontent.com/52562340/88296014-5e239e80-cd28-11ea-85b7-3a974f4b5f47.png">

debug my code + packages + SDK
<img width="1440" alt="Screen Shot 2020-07-23 at 9 01 25 PM" src="https://user-images.githubusercontent.com/52562340/88296049-67ad0680-cd28-11ea-9dad-0ee7872d3c54.png">

**Comment by DanTup** [comment]
Ok, I think I misunderstood slightly - I thought Android Studio was pausing on the exception, but the text in the screenshot is showing the exception in the debug console.

VS Code should also show the same error text in the debug console, but I think it's currently breaking on an exception that occurs *before* the widget error.

If you "Run without Debugging", do you see the same behaviour as Android Studio (the exception shown in the Debug Console?). If so, I think if you run with debugging, and then click the "Continue" button on the debug toolbar when this first error occurs, you would also then see this error in the debug console?

**Comment by tbm98** [comment]
> VS Code should also show the same error text in the debug console, but I think it's currently breaking on an exception that occurs _before_ the widget error.

Yep, this is Dio error



> If you "Run without Debugging", do you see the same behaviour as Android Studio (the exception shown in the Debug Console?). If so, I think if you run with debugging, and then click the "Continue" button on the debug toolbar when this first error occurs, you would also then see this error in the debug console?

after click the "Continue" it work fine and see error in the debug console look like in Android Studio. Thanks :D

**Comment by DanTup** [comment]
Great! I think the pausing is probably similar to https://github.com/Dart-Code/Dart-Code/issues/2063, where the debugger breaks on an exception that will be caught.

As a workaround, running without debugging (or unticking the option to pause on exceptions) might help.

**Comment by tbm98** [comment]
Yes. I will always use run without debug :D
