### ISSUE TITLE
Help to find out the file containing dart formatter implementation 

### ISSUE THREAD

**Issue by Chetan11-dev** [Dart-Code/Dart-Code#2668]
Hello Sir I am interested in learning how we could convert unformatted text to formatted text. Your extension does that that in an excellent manner. 
It would be great help if you could point out the implementation where the unformatted text is converted to formatted text. I tried my best but reached a dead-end at  src/extension/providers/dart_formatting_edit_provider.ts. 

So the implementation may take a string => string 
eg : 
	const unformattedContent = `   main ( ) {     }${platformEol}`;
	const formattedContent = `main() {}${platformEol}`;

**Comment by DanTup** [comment]
The formatting here is done using the Dart analysis server. This internally uses the [dart_style](https://pub.dev/packages/dart_style) package, which you can use directly either from the command line or API:

- Using dartfmt https://pub.dev/packages/dart_style#using-dartfmt
- Using the dart_style API https://pub.dev/packages/dart_style#using-the-dart_style-api

Hope this helps!

**Comment by Chetan11-dev** [comment]
Thanks, Dan  I have a  question for instance I am developing a vs code extension in which I want to format dart code (string) so is there a command which I could use like vscode.executeCommand() passing in a string as args and get a formatted string back?

**Comment by DanTup** [comment]
There isn't anything currently. It would be possible for us to expose something, however we're close to switching over to LSP and things get a bit more complicated there, as we can't just call the formatter in the same way (formatting is handled via the LSP protocol).

So the best option might be to use your own formatter - for ex. create a Dart project that uses the dart_style API and then ship that in your extension. You could use dart2native to ship a native build (to avoid dependencies on a Dart SDK etc.), and make a basic API (so it runs in a "server mode" to avoid having to start up a new process every time you need to format).

**Comment by Chetan11-dev** [comment]
DanTup Thank you.
I have actually completed by transaltion of Api into Js as you had advised. I am proud to tell it has helped 118 people. 
https://marketplace.visualstudio.com/items?itemName=ChetanJain.flutter-code-generator

One more thing could you explain although it is not related but you are very knowledgable.
I have a basic requirement that say I have the dart code as a text string
```
Column(
children:[
Text('Hello DanTup')]
)
```
and I want to show this in a visual form and but in a javascript enviroment. Is there a way in which I could give this string as input and show the visual element to the user.

**Comment by DanTup** [comment]
@Chetan11-dev glad you got it working! 

> Is there a way in which I could give this string as input and show the visual element to the user.

I'm not sure what you mean by "visual element" here? Do you mean to render the Flutter code and produce an image file? If so, that would be more complicated as you'd need to create a valid Flutter project and run it. There's an existing VS Code extension trying to do something like that here:

https://marketplace.visualstudio.com/items?itemName=jamesblasco.flutter-preview

**Comment by Chetan11-dev** [comment]
Actually, Dan, I am trying to create a drag and drop web builder. There is a project https://github.com/Norbert515/flutter_ide but it is based on Dart. I would like it to be in js. The app will basically generate a string 
```
Column(
children:[
Text('Hello DanTup')]
)


```  
and I want it to be displayed as text with the ''Hello DanTup'' message the caveat is I am in a js environment.
I could generate a desktop Application with the code being outputted in a file but I want it to be a web version. Do you know how could I salve the problem?
Thank You

**Comment by Chetan11-dev** [comment]
Hello Dan I mean you are busy but in case you have a clue will me of mighty help.

**Comment by DanTup** [comment]
@Chetan11-dev Sorry for the delay - I was just typing here as you commented!

I'm not sure I entirely understand the goal. Are you trying to use the Flutter framework to render the code from a string? Are you expecting to get back an image file, or HTML and JavaScript? Are you running in a browser, or in a Node VM? I don't think is going to be an easy task unfortunately.

**Comment by Chetan11-dev** [comment]
Thank you Dan for your reply.

**Comment by DanTup** [comment]
(You didn't answer the questions 🙂  I'm not sure how much I can help, but I might be able to provide some more pointers if you can give a little more context)

**Comment by Chetan11-dev** [comment]
Suppose I make a reactjs application.

There is going to be a part in app which produces dart code as string in js.

What will I want is given a string (js string of course). The application in a screen product the corresponding screen.

In short drag and drop widget editor for flutter build in Js.

**Comment by Chetan11-dev** [comment]
In case you need further clarification or would like to explain we could arrange for Skype call. It will be really great to talk too you Dan!!!

**Comment by Chetan11-dev** [comment]
> (You didn't answer the questions 🙂  I'm not sure how much I can help, but I might be able to provide some more pointers if you can give a little more context)

Actually I was typing the context.

**Comment by Chetan11-dev** [comment]
It will be in a nodevm on browser preferably.

**Comment by Chetan11-dev** [comment]
Consider this project to be javascript version of flutter-ide
 https://github.com/Norbert515/flutter_ide

**Comment by DanTup** [comment]
That project works by running a Flutter app and then hot-reloading the user code into it, so the Flutter framework is doing all of the compilation/rendering:

https://github.com/Norbert515/flutter_ide/blob/master/live_compilation_server/lib/server.dart

I think you'd need to do something similar - have a server that you send the code to, have it write that to disk, and then hot-reload (and then embed the Flutter web app inside an iframe into your browser IDE). It's much easier for that project, because it can just reload the code directly into its own application (so it wouldn't need to iframe it).

**Comment by Chetan11-dev** [comment]
Yes, I am not sure how can a website write to a disk. Also, It would be helpful to have a call so to clarify it efficiently Dan.
Could we have a Skype Call?
https://join.skype.com/invite/r12N2hLbWOoF

**Comment by DanTup** [comment]
I'm happy to answer simple questions here, and provide support for the VS Code extensions - but unfortunately I can't provide general help for building apps (I get a lot of requests via email and DMs and even responding to them takes a lot of time).

The project linked above does exactly what you're asking - it writes a file to disk ([see here](https://github.com/Norbert515/flutter_ide/blob/0374249655a07f24be306b93ba45305384043c11/live_compilation_server/lib/server.dart#L51)). It does this by running a server that listens on a WebSocket that the client app can connect back to, and then sending it commands (though in that case, both are written in Dart).

I think doing what you want from JS will be quite complicated though (or at least limited to hosting the Flutter part inside an iframe).

Hope this helps!

**Comment by Chetan11-dev** [comment]
No worries thanks Dan.

**Comment by DanTup** [comment]
np, good luck with the project!
