### ISSUE TITLE
Handling relative paths inconsistent with Flutter engine. 

### ISSUE THREAD

**Issue by JarrodCColburn** [Dart-Code/Dart-Code#2673]
When using dart.io `File` class with local machine relative paths, flutter from the command line and Extension evaluate paths inconsistently.
This is apparent when running tests.
Flutter begins testing and evaluates all paths relative to `test` folder.
However, Extension begins testing and evaluates all paths relative to project root.

I have created an example repo at https://github.com/JarrodCColburn/vs_code_flutter_test_example with simple steps to reproduce to highlight differences. 

Please let me know if need further clarification.

**Comment by DanTup** [comment]
Thanks for the report! I believe this is an issue in Flutter and is triggered depending on whether you just run `flutter test` or if you provide a file/folder (eg. `flutter test test`). There's an open issue at https://github.com/flutter/flutter/issues/20907 about this.

When running tests from the extension, we always supply the filenames (as when you "run all tests" we run them concurrently).

Hope this makes sense - let me know if you think it's not the same issue!

**Comment by JarrodCColburn** [comment]
Thanks so much @DanTup 
Yep. That looks like the same issue.
Honestly, I feel silly now not having checked flutter repo for that issue, but please forgive me as it was a pretty late night of tracking down my test fails.
I see the flutter/flutter#20907 is open since Aug 2018 and I hate to highlight a problem without trying to help solve it too, so is there anything I can do to assist? 
I'm fairly proficient at using flutter (but not developing/building the SDK) but not VS Code extensions (or typescript).

**Comment by DanTup** [comment]
> Honestly, I feel silly now not having checked flutter repo for that issue, but please forgive me as it was a pretty late night of tracking down my test fails.

Don't worry, it's often hard to know what to search for (or where to look). I've been known to raise duplicates of issues I'd already raised myself in my own project here 😆

> is there anything I can do to assist?

I haven't really dug into the issue so I'm not entirely sure what the fix would be (or which one of the two is "correct"). Howeer if you're interested in contributing, I'm sure a PR to the Flutter repo would be welcomed! There's some notes on contributing at https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md. For a change to the flutter_tools package, you wouldn't need to set up for Engine development and can skip that block. Then there's https://github.com/flutter/flutter/wiki/The-flutter-tool about working on the tool (though it looks IntelliJ focused).

You should read through those docs, but as a TL;DR you can probably get up and running by:

- cloning the git repo
- opening the pkg/flutter_tools folder in VS Code
- create a .vscode/launch.json like this:
  ```js
  {
	"version": "0.2.0",
	"configurations": [
		{
			"name": "flutter_tools",
			"type": "dart",
			"request": "launch",
			"program": "${workspaceFolder}/bin/flutter_tools.dart",
			"cwd": "/path/to/a/flutter/project",
			"args": ["test"]
			// "args": ["test", "test"]
		}
	]
  }
  ```

Then when you press `F5`, it should run the equiv of `flutter test` in the `cwd` you set to a sample project, but through the debugger so you can add breakpoints (for example in `commands/test.dart`) that might help you figure out why the directories are set differently. You can swap the `args` in the `launch.json` to change between running the equiv of `flutter test` and `flutter test test` (which I believe triggers the difference in behaviour).

If you are planning on taking a look, it's worth pinging a note on that issue stating so (to avoid others looking at it), and feel free to ping questions on there and hopefully someone (possible me) might be able to provide pointers. Thanks!

**Comment by DanTup** [comment]
Possibly this line is involved:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/test/runner.dart#L192

**Comment by JarrodCColburn** [comment]
@DanTup  
I'm trying to work on a draft PR at https://github.com/flutter/flutter/pull/62387.
Just moving one line up above an if statement fixed a ton of ailing tests for me.  See photo below of diff for`flutter/packages/flutter_tools/lib/src/commands/test.dart`
![moveGlobals](https://user-images.githubusercontent.com/16673615/88632524-aec92d80-d081-11ea-849f-b7163e6b2781.png)

**Comment by DanTup** [comment]
@JarrodCColburn it's possible the fix is as simple as that. It's probably worth running it by @jonahwilliams. This may be a breaking change though (depending on how people are running the tests, they may be depending on either set of paths) so it may require following Flutter's [breaking change policy](https://flutter.dev/docs/resources/compatibility).

FWIW, the Flutter repo also doesn't use automatic dartfmt formatting. I would disable the VS Code formatter for your Flutter repo (run **Preferences: Open Workspace Settings** and set `"dart.enableSdkFormatter": false`) and revert the formatting changes (this will reduce the chance of having conflicts if others are modifying the lines that were reformatted).

**Comment by JarrodCColburn** [comment]
Thanks, 

I too doubt the fix is that simple overall, but it did fix my VS Code testing issue for my test repo [vs_code_flutter_test_example](https://github.com/JarrodCColburn/vs_code_flutter_test_example).

More importantly though, it fixed the same problem on a `flutter/plugins` package, specifcally [image_piecker_platform_interface](https://github.com/flutter/plugins/tree/master/packages/image_picker/image_picker_platform_interface). Which has a test [picked_file_io_test.dart](https://github.com/flutter/plugins/blob/14608ca5ed0fa54fb6b2abccbd68b120bfe8e283/packages/image_picker/image_picker_platform_interface/test/picked_file_io_test.dart#L16) which uses a local file witht this line...
```dart
final File textFile = File('./assets/hello.txt');
```
Note: Above `./assets` directory references `{projectRoot}/test/assets` (not `{projectRoot}/assets` commonly ref'd in pubspec).

This is what my original issue. I was trying to follow the best practices of the flutter repo and couldn't figure out why I couldn't get their tests to pass in my VS Code testing.

**Comment by JarrodCColburn** [comment]
Sorry, forgot a few things above...

I was trying to run the existing tests for `flutter_tools` but they were failing, maybe it's "my machine".


As such, is there a recommended docker image I can dev/test within? I plan on using VS-Code's `Remote-Containers` extension.

I see that flutter uses Cirrus for CI, would the image on [dockerhub cirrusci/flutter](https://hub.docker.com/r/cirrusci/flutter) be the recommended image to do `dart_tools` dev/testing in?
___
I'll avoid `dartfmt`. And I'll create a new PR without the formatting if I can make progress.

**Comment by DanTup** [comment]
> I was trying to run the existing tests for `flutter_tools` but they were failing, maybe it's "my machine".

Can you give an example of which tests are failing?

It'd be best to try and fix whatever's wrong, but if you do want to use a container, I've just been [using debian:stretch with some extra utils](https://github.com/DanTup/gitpod-flutter-web/blob/master/.gitpod.Dockerfile) for things like Gitpod. I haven't specifically tried to work on flutter_tools in it, but I don't see why it shouldn't work.
