### ISSUE TITLE
Autocompleting starts working too slow after some time.

### ISSUE THREAD

**Issue by SametSahin10** [Dart-Code/Dart-Code#2674]
I'm having problems using autocompletion feature of the extension. At first, everything works pretty normal, suggestions pop up, imports are detected etc. But after some time spent working on the project, a noticeable slowness starts to occur. Sometimes I wait for two seconds for a suggestion to pop up. What could be the problem here?

Below are the logs produced after I've enabled Dart: Capture Logs.

https://paste.ubuntu.com/p/26c2ZPcVq7/

**Comment by DanTup** [comment]
Are you using any extensions that may intercept keystrokes, like VS Code Vim? If so, you may be seeing the issue described at https://github.com/microsoft/vscode/issues/75627.

Either way, could you try enabling the LSP preview (`"dart.previewLsp": true` in our VS Code user settings) and see whether that makes any difference? It moves a lot of the work out of process, and will become the default/only option in future.

Thanks!

**Comment by SametSahin10** [comment]
After enabling `"dart.previewLsp"`: true it seems that it's slightly improved or just the placebo effect. 😄  I still think there's something preventing the extension from working properly. Any other recommendations?

**Comment by DanTup** [comment]
@SametSahin10 are you able to capture logs when using LSP when this happens, and provide the exact details of some code and where you invoked completion to go with it (if you're able to screen-capture the issue and provide a log that matches the screen capture, that would be very helpful). Thanks!

**Comment by SametSahin10** [comment]
> @SametSahin10 are you able to capture logs when using LSP when this happens, and provide the exact details of some code and where you invoked completion to go with it (if you're able to screen-capture the issue and provide a log that matches the screen capture, that would be very helpful). Thanks!

I'll do that as soon as I can. While I'm looking for issues and posts about this problem I'm having, I've come across a [Reddit post](https://www.reddit.com/r/vscode/comments/c9gt0e/typing_lag_in_vs_code/) that its context was similar to mine. At the bottom of the post, the owner of the post says that the issue was due to the Temperature Controlling Software. That is pretty interesting cause I'm as well running a software to control the temperature too. I will shut it down and see if it changes anything. Do you have an idea of why this kind of event would occur just because I'm running an app to control the temperature? [Here](https://crystalidea.com/macs-fan-control)'s the link to the app I'm using to control the temperature if it helps in any way.

**Comment by DanTup** [comment]
> Do you have an idea of why this kind of event would occur just because I'm running an app to control the temperature?

I don't know what the software is doing, but if it's forcing the fans to run more slowly, I would expect the CPU to get hotter and therefore may be throttled to avoid damage. This could have the effect of causing things to run more slowly (why this would seem to affect some things worse than others, I'm not sure - my knowledge of these things is limited).

If turning it off fixes the issue, but the CPU usage doesn't seem high - it may be worth reporting it to the company that make that software to see if they have any insights into why it might cause this.
