### ISSUE TITLE
Screenshot command no longer available in command palette

### ISSUE THREAD

**Issue by maks** [Dart-Code/Dart-Code#2681]
I'm using:
Version: 1.47.2
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:22:15.161Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-42-generic

with DartCode 3.12.2 and the "Flutter: Screenshot" command no longer shows up in the Command Palette. 

It definitely used to be there and worked fine, but not sure at what point it disappeared.

Happy to supply other logs, info if it would help.

**Comment by DanTup** [comment]
Are you in a debug session when you look for it (the debug toolbar should be visible)? It seems to appear for me, though only when running a debug session (this is expected).

<img width="954" alt="Screenshot 2020-07-30 at 09 06 31" src="https://user-images.githubusercontent.com/1078012/88897942-fbf4fd00-d243-11ea-9181-8e120f792397.png">

The only other condition is that you're in a Flutter project:

https://github.com/Dart-Code/Dart-Code/blob/6ad3ce7498b7e25cde03a1c2dff5469c9e87c726/package.json#L787

**Comment by maks** [comment]
Yes @DanTup you're spot on, I wasn't in a debug session. Sorry completely user error on my part.
But I went and looked in the [docs and it looks like the screenshot command is not yet documented](https://dartcode.org/docs/commands/) so I've done [a tiny PR for that](https://github.com/Dart-Code/Website/pull/12) to help future users.
