### ISSUE TITLE
Show full untruncated messages from dart:developer log()

### ISSUE THREAD

**Issue by szotp** [Dart-Code/Dart-Code#2683]
developer.log output is truncated so much that it's almost useless. IMO it would be better to just print entire thing - if I wanted to truncate, I could do it before calling the log method.

```dart
import 'dart:developer';

void main(List<String> arguments) {
  const text1 =
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";

  final text2 =
      Iterable.generate(100, (i) => 'Lorem ipsum dolor sit amet').join('\n');

  log(text1);
  log(text2);
}
```

Outputs:
```
[log] Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut e…
[log] Lorem ipsum dolor sit amet
      Lorem ipsum dolor sit amet
      Lorem ipsum dolor sit amet
      Lorem ipsum dolor sit amet
      Lorem ipsum dolor si…
Exited
```

I suspect that this line needs to be changed:
https://github.com/Dart-Code/Dart-Code/blob/6ad3ce7498b7e25cde03a1c2dff5469c9e87c726/src/debug/dart_debug_impl.ts#L1598

To use fullValueAsString:
https://github.com/Dart-Code/Dart-Code/blob/6ad3ce7498b7e25cde03a1c2dff5469c9e87c726/src/debug/dart_debug_impl.ts#L1605

I'm going to try if it works and submit MR.

I also checked on Android studio and did not have this truncation.

**Comment by DanTup** [comment]
On the surface that seems like a reasonable change to me. There's a test here you might want to extend/copy with a longer message:

https://github.com/Dart-Code/Dart-Code/blob/b3b95550b58d17fdfe741aae20b9fdcb400011bc/src/test/dart_debug/debug/dart_cli.test.ts#L131

Thanks!

**Comment by szotp** [comment]
PR sent #2684
