### ISSUE TITLE
Debugger requires --disable-dart-dev to work

### ISSUE THREAD

**Issue by dcharkes** [Dart-Code/Dart-Code#2685]
When using the debugger with with a locally built SDK the debugger hangs on `Connecting to VM Service at ws://127.0.0.1:39443/eI-Vn8w0gbM=/ws` when not passing 

```json
            "vmAdditionalArgs": [
                "--disable-dart-dev"
            ]
```

cc @bkonyi

**Comment by DanTup** [comment]
There's an open issue in the SDK about this:

https://github.com/dart-lang/sdk/issues/42875

I think there's a race condition that causes VS Code to end up connected to the dartdev process and not the actual app.

@bkonyi disabled DDS for now though in https://github.com/dart-lang/sdk/commit/8dc4833e86b7eaf917eb96494ee7fa5adf2ea76d - do you have that changeset included in your local build?

**Comment by dcharkes** [comment]
I rebased yesterday, not yet today.

Thanks for the quick answer!

(Feel free to close this issue if nothing needs to happen in DartCode. I wanted to post the workaround for if others run into this.)
