### ISSUE TITLE
flutter pub get error 

### ISSUE THREAD

**Issue by Mrwangmingchao** [Dart-Code/Dart-Code#2688]
__MACOSX/flutter_verification_box/._README.md: Truncated tar archive    
tar: Error exit delayed from previous errors.                           
Failed to extract .tar.gz stream to /Library/flutter/.pub-cache/_temp/dircSPn4F (exit code 1).
package:pub/src/io.dart 898:5                extractTarGz               
===== asynchronous gap ===========================                      
package:pub/src/source/hosted.dart 398:11    BoundHostedSource._download
===== asynchronous gap ===========================                      
package:pub/src/source/hosted.dart 264:13    BoundHostedSource.downloadToSystemCache
package:pub/src/entrypoint.dart 407:48       Entrypoint._get.<fn>       
dart:async                                   runZoned                   
package:pub/src/http.dart 279:10             withDependencyType         
package:pub/src/entrypoint.dart 403:12       Entrypoint._get            
dart:async                                   Future.wait                
package:pub/src/entrypoint.dart 252:18       Entrypoint.acquireDependencies
dart:async                                   _completeOnAsyncReturn     
package:pub/src/solver/version_solver.dart   VersionSolver.solve        
dart:async                                   _completeOnAsyncReturn     
package:pub/src/source/hosted.dart           BoundHostedSource.withPrefetching
dart:async                                   _completeOnAsyncReturn     
package:pub/src/rate_limited_scheduler.dart  RateLimitedScheduler.withPrescheduling
dart:async                                   _completeOnAsyncReturn     
package:pub/src/source/hosted.dart           BoundHostedSource.withPrefetching.<fn>
dart:async                                   _completeOnAsyncReturn     
package:pub/src/solver/version_solver.dart   VersionSolver.solve.<fn>   
dart:async                                   _completeOnAsyncReturn     
package:pub/src/solver/version_solver.dart   VersionSolver._result      
This is an unexpected error. Please run                                 
                                                                        
    pub --trace '--verbosity=warning' get --no-precompile               
                                                                        
and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Running "flutter pub get" in express-customer-app...                    
pub get failed (1; and include the logs in an issue on https://github.com/dart-lang/pub/issues/new)

**Comment by DanTup** [comment]
Thanks for the report! This should be raised in the pub issue tracker shown in the message:

> and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

Thanks!
