### ISSUE TITLE
Hot reload broken since the last update if you're not using "Hot Reload On Save"

### ISSUE THREAD

**Issue by larssn** [Dart-Code/Dart-Code#2691]
If you have the setting "Hot Reload On Save" turned off, and try to hot reload manually by clicking ctrl-f5, you'll get the error `Running the contributed command: 'flutter.hotReload' failed.`. Only hot restart seems to work, but it's a pain because it takes too long.

The workaround for now is to turn "hot reload on save" back on.

**Comment by DanTup** [comment]
Ugh, sorry for the bother. I fixed this in one place but apparently not all.

I've published v3.13.1 with a fix for this and added additional tests. Run the **Extensions: Check for Updates** command in the VS Code command palette if VS Code doesn't pick it up automatically.

Thanks!
