### ISSUE TITLE
incorrect formatting at shift+alt+f

### ISSUE THREAD

**Issue by yuredev** [Dart-Code/Dart-Code#2692]
The extension is not formatting correctly 
My code before i press ```SHIFT + ALT + F``` is:

![ISSUE 1](https://user-images.githubusercontent.com/43214648/89110731-0c63ce00-d424-11ea-97c7-0a2bc0f9467a.PNG)

and after formatting it turns this:

![ISSUE 2](https://user-images.githubusercontent.com/43214648/89110741-30271400-d424-11ea-8455-9af79987b89d.PNG)

formatting is a boring thing that takes me time in Flutter. 
I would be very grateful if someone help

**Comment by devorrah** [comment]
I get the same behavior.

**Comment by DanTup** [comment]
You need to add [trailing commas](https://flutter.dev/docs/development/tools/formatting#using-trailing-commas) for the formatter to format as you'd like. The formatter is [dart_style](https://github.com/dart-lang/dart_style) and it tries to keep things on less lines by default. Trailing commas are used to force formatting that works better for Flutter widget code.

If this still doesn't work, please paste in the code you're formatting (so I can easily copy it) and highlight exactly which part of the formatting is not as you'd expect. Thanks!

**Comment by yuredev** [comment]
@DanTup It worked for me, I didn't have the habit of putting trailing commas in the last attribute of an object, Thank you very much!!
