### ISSUE TITLE
Must run pub upgrade twice before recompile happens

### ISSUE THREAD

**Issue by bsutton** [Dart-Code/Dart-Code#2695]
I've been doing a fair bit of package uprading of late.

It would appear that I have to run 'pub upgrade' twice before vscode notices the upgrade and does a recompile.

This seems to happen regardless of whether I run the upgrade from the vscode terminal or from the tool menu (? ctrl-shift-p).

I would expect that running pub upgrade a single time should cause vscode to recompile my dart project.

**Comment by DanTup** [comment]
Could you try capturing an [instrumentation log](https://dartcode.org/docs/logging/#analyzer-instrumentation) of this happening? I haven't seen this (though depending on the project size, it might take a few seconds to rescan the project after the dependencies change).

**Comment by bsutton** [comment]
Instrumentation logs attached.

This is not exactly the scenario originally reported but I suspect it probably has the same source issue.

Here is what I tried:
Clear .pub-cache
Start vscode
run pub ugrade from dart-code terminal
304 compile errors (should be only 7)
No external package in pubspec.yaml are imported.

run pub upgrade from dart-code terminal a second time.
Error perisist.

run pallet pub upgrade
Errors persist

run pallet pub upgrade
errors persist

Restarting vscode cleared the errors.
[dart-code.zip](https://github.com/Dart-Code/Dart-Code/files/5156032/dart-code.zip)

**Comment by bsutton** [comment]
Here is the logs from the orginally described problem.
vscode auto runs pub get but the errors don't clear.
I need to run pub get (from the pallet) manually before the errors clear.
This is from the same dscript project I sent in relation to the single/double quote issue.
So its a small project (on a very fast pc) so I don't believe this is lag.
I'm also waiting a reasonable amount of time before running pub get manually and the clearing of errors is the instant.
I've done this too many times to think the timing is a co-incidence (e.g. its not just a slow reload/refresh).

2nd test.
restart vscode
open project - 7 expected errors.
modified pubspec.yaml to upgrade dependency.
vscode automatically ran pub get.
7 errors remained.
I can see the new dependency has been loaded into .pub-cache
run pub get from pallet
remaining errors cleared.

[dart-code.log.tar.gz](https://github.com/Dart-Code/Dart-Code/files/5156069/dart-code.log.tar.gz)

**Comment by DanTup** [comment]
@bsutton thanks - though these logs are are Dart-Code's own logs, and not the [instrumentation log](https://dartcode.org/docs/logging/#analyzer-instrumentation), which means they don't include the file watcher events. To capture an instrumentation log you need to use the `dart.analyzerInstrumentationLogFile` setting, which sends the path to the server and asks it to do the logging.

It may be useful to leave a short gap (eg. 5-10 seconds) between each action so it's easier to tell in the logs which lines occurred between which actions (and also wait for initial analysis completes before starting, to ensure that's not also spamming to the log).

Thanks!

**Comment by DanTup** [comment]
Also:

> modified pubspec.yaml to upgrade dependency.

To clarify - are you adding a new dependency, or changing the version? (If changing the version, do you have an example of an old/new version that changes the API to affect errors that I could try to test with?)
