### ISSUE TITLE
Remove 'interface' from keywords

### ISSUE THREAD

**Issue by hermanbergwerf** [Dart-Code/Dart-Code#270]
I'd like to use interface as field name without it being highlighted. See line https://github.com/Dart-Code/Dart-Code/blob/69d570366c6c704bb43a0a3c0e5c2443ca2dc4aa/syntaxes/dart.json#L239.

The interface keyword was removed ~5 years ago, see: http://news.dartlang.org/2012/06/proposal-to-eliminate-interface.html.

**Comment by DanTup** [comment]
Thanks for reporting this (and the helpful link to where it needs changin1); I took that file from one of the other editor integrations but didn't check how accurate it was. Will remove this for the next release!

**Comment by DanTup** [comment]
@devoncarew FYI in case you wish to remove from [the Atom version](https://github.com/dart-atom/dartlang/blob/master/grammars/dart.cson#L210).

**Comment by devoncarew** [comment]
Thanks for the heads up!
