### ISSUE TITLE
Please upload Flutter VSCode extension VSIX file for version 3.13.2

### ISSUE THREAD

**Issue by eladcandroid** [Dart-Code/Dart-Code#2705]
https://github.com/Dart-Code/Flutter/releases/

**Comment by DanTup** [comment]
Whoops, missed that. It's available here now:

https://github.com/Dart-Code/Flutter/releases/tag/v3.13.2

(FWIW, there was no change in this version, the version number was increased only to match the Dart version number).

Thanks!
