### ISSUE TITLE
Unable to run any flutter project after dart update 3.13.2

### ISSUE THREAD

**Issue by AbdoZDGaia** [Dart-Code/Dart-Code#2707]
when i try to run my app i instantly get these errors

![image](https://user-images.githubusercontent.com/57171672/89544252-2cb7d200-d802-11ea-8835-2eb10f2d0ffe.png)
![image](https://user-images.githubusercontent.com/57171672/89544270-32adb300-d802-11ea-95c5-aea290e64044.png)

what should i do to be able to run my apps again?

**Comment by DanTup** [comment]
Please see https://github.com/Dart-Code/Dart-Code/issues/2706#issuecomment-669878016.
