### ISSUE TITLE
Errors not being displayed after file move

### ISSUE THREAD

**Issue by JCKodel** [Dart-Code/Dart-Code#2709]
Before the latest version, whenever an error existed in the code, it would appear in the statusbar and in the problems tab.

After the last update, errors are not updating while debugging:

![image](https://user-images.githubusercontent.com/379339/89606247-dd939080-d845-11ea-9ed4-0a11346315db.png)

This happened after I move a dart file from one folder to another. The `import` was not updated in two files and yet those files didn't trigger errors (not in the problems tab and not in the source code, i.e.: there was no red underline error anywhere in the file). I only see the error because it appeared on the debug console (and I were luck to have it open).

**Comment by DanTup** [comment]
Can't reproduce an issue like this, though I'm not sure exactly what steps you performed. Can you reproduce and note the steps, an example of the sort of error (and how/if it relates to the moving of the file) and ideally a captured analysis log file?

Also can you confirm the SDK version you're using? Thanks!
