### ISSUE TITLE
Odd behavior with try/catch inside try/finally in async method

### ISSUE THREAD

**Issue by JCKodel** [Dart-Code/Dart-Code#2710]
Consider this code (this is the real code):

```dart
Future<void> _addPhoto(BuildContext context, ImageSource imageSource) async {
  final progressDialog = ProgressDialog(context, isDismissible: false, showLogs: true, type: ProgressDialogType.Normal);
  PickedFile pickedFile;

  progressDialog.update(message: "Obtendo foto...", progress: 1, maxProgress: 4);
  await progressDialog.show();

  try {
    try {
      pickedFile = await ImagePicker().getImage(source: imageSource, imageQuality: 100);
    } catch (e) {
      _showError(context, imageSource == ImageSource.camera ? "Obter foto da câmera" : "Obter foto da galeria", e);
      return;
    }

// Code here doesn't matter because it is never executed in this scenario

  } finally {
    if (progressDialog.isShowing()) {
      await progressDialog.hide();
    }
  }
}
```

What I'm doing here is showing a spinning loading dialog, then trying to get a picture from the user (camera or gallery), then upload and save it on the database.

As a test, I asked for a gallery image but I have denied access to the external storage (replying to DENY on Android's permissions popup).

That triggered an exception caught by the catch, the exception was logged in my debug console, but the popup won't go away.

So I put a breakpoint in the finally and the breakpoint was never executed! I was filling a bug in the Dart SDK repository because that's not how finally is supposed to work and, while writing a pure Dart example, I could not make it bug (finally IS working).

So, I put a `print` in the `finally` and it was really running (for some reason, the dialog won't go away, but the point is: breakpoint in finally were ignored).

Here's a video showing how misleading this scenario was for such a trivial error (and I still don't know why the spinner dialog is not going away =P)

https://youtu.be/JZQo21kgypc

**Comment by DanTup** [comment]
Are you able to share a project where this happens? I tried to repro like this:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Future<void> _throwIn1Second() async {
    await Future.delayed(Duration(seconds: 1));
    throw 'Oops!';
  }

  Future<void> _doStuff() async {
    try {
      try {
        await _throwIn1Second();
      } catch (e) {
        print('error');
      }
    } finally {
      print('IN FINALLY'); // Breakpoint here
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(child: Text('Click the button to do stuff!')),
      floatingActionButton: FloatingActionButton(
        onPressed: _doStuff,
        tooltip: 'Do Stuff',
        child: Icon(Icons.add),
      ),
    );
  }
}
```

Using current Flutter master, but the breakpoint was hit fine (I tried with break-on-all-exceptions and only with break-on-unhandled-exceptions, but that made no difference).

> and I still don't know why the spinner dialog is not going away =P

I'm not sure if that either, though it's not clear what `isShowing()` returned, or if `hide` completed. It would probably be easier to debug if the breakpoint worked though 😬
