### ISSUE TITLE
Could not find an option or flag "-r" when debugging test on dart 2.10

### ISSUE THREAD

**Issue by knopp** [Dart-Code/Dart-Code#2714]
Not sure if nnbd related. Clicking on "debug" annotation next to test method gives the following error:

```
Could not find an option or flag "-r".

Usage: dart run [arguments] <dart file | package target>
-h, --help 
...
```

`Dart SDK version: 2.10.0-4.0.dev (dev) (Thu Aug 6 15:52:09 2020 +0200) on "macos_x64"`

**Comment by DanTup** [comment]
Thanks for the report! This has been fixed recently in the SDK (https://github.com/dart-lang/sdk/issues/42941). It should be available in a new dev build soon (otherwise you could try [a nightly](http://gsdview.appspot.com/dart-archive/channels/be/raw/latest/sdk/)).
