### ISSUE TITLE
Dart sees, font_awesome_flutter package as an error.

### ISSUE THREAD

**Issue by amanc1248** [Dart-Code/Dart-Code#2715]
### Tried

1. Running flutter pub get
2. Running flutter packages get
3. Restarted the vs code
4. opened the direct folder.

But also gives an error saying,
**Target of URI doesn't exist: ### 'package:font_awesome_flutter/font_awesome_flutter.dart'. Try creating the file referenced by the URI, or Try using a URI for a file that does exist.**
Same issue occurs in vs code as well as in android studio.

### Flutter doctor -v also is also fine.
```[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.19041.388], locale en-US)
    • Flutter version 1.20.1 at C:\src\flutter\flutter
    • Framework revision 2ae34518b8 (3 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\Aman Chaudhary\AppData\Local
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\Aman Chaudhary\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

• No issues found!
PS G:\nikeshoeapp>```



### pubspec.yaml file looks good too.

```dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.8.1
  cupertino_icons: ^0.1.3
```

**Comment by DanTup** [comment]
I'm unable to reproduce this - the import works fine (and also shows up in the code completion). Can you reproduce this in a fresh project created with **Flutter: New Project**? If so, could you zip that folder up (including the hidden/files folders like `.dart_tool` and `.packages`) and attach it (or email it me at logs@dartcode.org)?

Thanks!

**Comment by amanc1248** [comment]
I sent the zip in mentioned email.
Hope I can use font awesome again.
Its bothering me for many days.
Thanks

**Comment by DanTup** [comment]
Nothing looks wrong in the project. I suspect something is up with the pubcache. Can you check this folder:

C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\font_awesome_flutter-8.8.1

and see whether it has the file `lib\font_awesome_flutter.dart`?

It may be worth either running `flutter pub cache repair` (this may re-download a lot of packages in your pub cache, so it may take a little while and transfer a bunch of data). Alternatively, deleting the `font_awesome_flutter-8.8.1` folder and re-running **Flutter: Get Packages** in VS Code to re-download it may achieve the same thing without so many downloads.

**Comment by amanc1248** [comment]
It has no any file named `lib\font_awesome_flutter.dart`.
There are only 3 files and 1 folder inside the folder, font_awesome_flutter-8.8.1. 
![image](https://user-images.githubusercontent.com/63035362/89997797-5d898280-dcac-11ea-9fa6-b8389e58953e.png)
That's why I am trying with Flutter: Get Packages in vs code.

**Comment by DanTup** [comment]
That looks like the issue then. That `lib` file should be a folder full of source code:

<img width="480" alt="Screenshot 2020-08-12 at 10 18 06" src="https://user-images.githubusercontent.com/1078012/89998197-205dca00-dc85-11ea-8718-2742122605c4.png">

You should try the steps above (either `flutter pub cache repair` or deleting the whole `font_awesome_flutter-8.8.1` folder and then re-fetching packages so it's downloaded clean). I'm not sure how it ended up like that though - if you see this occur again, it's probably worth filing an issue in the dart-lang/pub repo.

**Comment by amanc1248** [comment]
I am new to flutter, do help me with the steps.
Should I run `flutter get packages` inside the project folder that I am currently working  or
Should I run `flutter get packages` in the flutter console?
I tried both, neither of them seems to be working.
![image](https://user-images.githubusercontent.com/63035362/89999489-99bde280-dcae-11ea-9ec0-fcee8f01e22f.png)
![image](https://user-images.githubusercontent.com/63035362/89999550-a9d5c200-dcae-11ea-9c50-da01b8414ace.png)

And when I run Flutter: Get Packages in command palate. `flutter pub get` runs but inside the pub.dartlang.org folder is still without font_awesome_flutter folder
![image](https://user-images.githubusercontent.com/63035362/89999608-bc4ffb80-dcae-11ea-8236-55fd1094ba43.png)

**Comment by DanTup** [comment]
@amanc1248 running **Flutter: Get Packages** from the VS Code command palette should be fine. It looks like it may be stuck running in your screenshot though. Could you try:

- Close VS Code
- Open Task Manager and ensure there are no Dart or Flutter processes running (on the Details tab). If there are, select them and click Terminate (this will terminate any running Dart/Flutter apps you may have)
- Re-open VS Code
- Run the **Dart: capture Logs** command from the VS Code command palette (untick **Analysis Server** but leave everything else ticked)
- Run the **Flutter: get Packages** command
- Wait until the progress notification in the bottom right corner disappears (or if it does not, just wait a few minutes)
- Click the **Cancel** button on the logging notification
- Paste the log file here

**Comment by amanc1248** [comment]
!! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.13.2
Flutter extension: 3.13.2 (activated)

App: Visual Studio Code
Version: 1.47.3
Platform: win

Workspace type: Flutter
Analyzer type: DAS
Multi-root?: false

Dart SDK:
    Loc: C:\src\flutter\flutter\bin\cache\dart-sdk
    Ver: 2.9.0
Flutter SDK:
    Loc: C:\src\flutter\flutter
    Ver: 1.20.1

HTTP_PROXY: undefined
NO_PROXY: undefined

Wed Aug 12 2020 [17:55:42 GMT+0545 (Nepal Time)] Log file started
[5:55:48 PM] [CommandProcesses] [Info] (PROC 9172) Spawned C:\src\flutter\flutter\bin\flutter.bat pub get in C:\Users\Aman Chaudhary\Google Drive\Andriodstudioprojects\flutterproviderpackage
[5:55:48 PM] [CommandProcesses] [Info] (PROC 9172) Logging data for process...
[5:55:49 PM] [CommandProcesses] [Info] (PROC 9172) Running "flutter pub get" in flutterproviderpackage...
[5:55:50 PM] [CommandProcesses] [Info] (PROC 9172)     0.6s
[5:55:50 PM] [CommandProcesses] [Info] (PROC 9172)
[5:55:51 PM] [CommandProcesses] [Info] (PROC 9172) exited (0, null)
[5:55:51 PM] [CommandProcesses] [Info] (PROC 9172) closed (0, null)
Wed Aug 12 2020 [18:05:56 GMT+0545 (Nepal Time)] Log file ended

**Comment by DanTup** [comment]
After running this, do you now have the `lib` folder mentioned above? Did you try deleting the existing folder before running it? If you did delete it, and it came back with just a lib *file*, then I think it's worth raising an issue in the pub repo.

**Comment by amanc1248** [comment]
Did not came back the flutter_font_awesome folder.
I even tried `flutter pub cache repair` , it downloaded everything else, but a font-awesome folder.
![image](https://user-images.githubusercontent.com/63035362/90093215-c3c4e280-dd4a-11ea-8800-7079afffbf09.png)

**Comment by DanTup** [comment]
Can you try deleting the `.dart_tool` folder from your project, along with the `.packages` file and `pubspec.lock`, and then re-run **Flutter: Get Packages**. If that doesn't fix it, can you attach a copy of your `pubspec.yaml` and `.packages` after doing that? Thanks!
