### ISSUE TITLE
Error : Dart analyzes pubspec.yaml as a dart file

### ISSUE THREAD

**Issue by sidrao2006** [Dart-Code/Dart-Code#2717]
## Error Description

The extension logs more than 200 errors in pubspec.yaml file. The dart analyzer shows all dart errors which are not applicable for yaml files.

#### `dart --version`

```
Dart SDK version: 2.9.0-21.10.beta (beta) (Tue Jul 21 10:46:30 2020 +0200) on "windows_x64"
```

**Comment by DanTup** [comment]
Thanks for the report! This was raised in https://github.com/Dart-Code/Dart-Code/issues/2629 and was fixed in the Dart SDK:

https://github.com/dart-lang/sdk/commit/da9697feb96364360bfaedbb1c661c20bf7a4cb0

It doesn't look like it's made it to a stable/beta build yet, but it is available in the latest dev build:

https://dart.dev/tools/sdk/archive#dev-channel

**Comment by sidrao2006** [comment]
Ok thanks a lot

**Comment by Valentin-Seehausen** [comment]
Puh, that is really annoying. :-)

Looking forward to it to make it into the stable and flutter version. :-)

**Comment by DanTup** [comment]
The best fix would be to resolve the issue in your code that is generating this fix - so for example, if you have this warning that's triggering the issue:

> The class 'Stream' wasn't exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions.
> Try either importing 'dart:async' or updating the SDK constraints.

You could either import `dart:async` or you could manually update the SDK constraints in your pubspec to be > 2.1. Once the warning is fixed, the quick-fix should no longer be generated, which should stop the pubspec from being incorrectly analyzed as Dart.

**Comment by sidrao2006** [comment]
@DanTup , as soon as I run `flutter pub get`, all the issues clear out.

**Comment by Valentin-Seehausen** [comment]
Thank you for your answer.

I have the sdk at ">=2.1.0 <3.0.0". So do you recommend writing the import statement into my pubspec.yaml? Or where should I import it?

**Comment by DanTup** [comment]
@Valentin-Seehausen do you have any warnings at all in the Problems view (besides those from `pubspec.yaml`) when this happens? The import would go in the Dart file that references the `Stream` class for the example warning above (though there may be others that trigger similar fixes).

**Comment by Valentin-Seehausen** [comment]
Yes, sometimes I have. Sometimes I don't. Usually after `flutter pub get` the warnings disappear, but sometimes the come and go. Most of the time it works, but 1. it is a little annoying, and 2. when I wrote this entry, the warnings would not disappear and I had to restart my editor / macbook to clear them.
