### ISSUE TITLE
Contribute tasks for "flutter build" and other common commands

### ISSUE THREAD

**Issue by sidrao2006** [Dart-Code/Dart-Code#2718]
# Use Case

As available in IntelliJ and Android Studio, the build option will be very useful.
Currently in VS Code, we have to run the command in terminal.

**Comment by DanTup** [comment]
There are quite a few build types and each one has a number of arguments. I'm unsure if it's worth having to maintain those in some quick-pick versus just leaving this as something to run from the terminal. I do generally encourage avoiding the terminal and using built-in commands, but it usually comes at the expensive of only being able to do the most simple form with no arguments.

**Comment by sidrao2006** [comment]
Hi @DanTup thanks for replying.
VS Code does provide an option to configure these settings. So options for building apk, appbundle, ipa can be provided with config.json file to pass parameters for customization

Using the terminal is sometimes really frustrating

**Comment by DanTup** [comment]
> VS Code does provide an option to configure these settings. So options for building apk, appbundle, ipa can be provided with config.json file to pass parameters for customization

That's true, but editing the settings might be more effort than just running it manually.

That said, I think a task provider may work well here. We can contribute default tasks (for example with no arguments) and if you want to customise them you can click the cog icon to copy them into your own `tasks.json`.

**Comment by sidrao2006** [comment]
> > VS Code does provide an option to configure these settings. So options for building apk, appbundle, ipa can be provided with config.json file to pass parameters for customization
> 
> That's true, but editing the settings might be more effort than just running it manually.

@DanTup, editing the settings may require some effort but not as much as the effort need to open the terminal and enter the command with all the arguments just for building the app.

Many a times, I use it for testing purposes as well to determine the smooth ness of the app, *size* and performance. So, this feature could be useful.

> That said, I think a task provider may work well here. We can contribute default tasks (for example with no arguments) and if you want to customise them you can click the cog icon to copy them into your own `tasks.json`.

That's great, I'll be looking forward to it.
