### ISSUE TITLE
No Fluter-Widget-Highlighting in VSC after update 

### ISSUE THREAD

**Issue by masdot** [Dart-Code/Dart-Code#2719]
Since the last update a few days ago, the widget highlighting in Visual Studio Code doesn't work. Just the highlighting of the dart-operators working (e.g. class, import, void).

**Comment by DanTup** [comment]
Can you provide a screenshot of what you're seeing, and also check what VS Code theme you're using? Some themes do not include a lot of colours (for example the "Dark" theme does not, but "Dark+" does).

Thanks!

**Comment by masdot** [comment]
I already found the problem. One of my extensions stopped the highlighting.

**Comment by DanTup** [comment]
Glad you sorted it1 Out of interest, which extension was it? It'd be useful to have noted here in case others have the same issue. Thanks!

**Comment by masdot** [comment]
It should be the material icon theme, but after reinstalling the extension it works fine.
