### ISSUE TITLE
Expose managing analyzer process

### ISSUE THREAD

**Issue by Aetet** [Dart-Code/Dart-Code#272]
Sometimes dart analyzer stuck or something, Is there possibiblity to restart analyzer by hand with restart vs code? This implemented at WStorm and Atom.

**Comment by DanTup** [comment]
If you open the command pallet ('Ctrl+Shift+P`) and run the `Reload Window` command, this will re-open the workspace and relaunch the analyzer.

That said, Dart Code should automatically detect when the analysis server is not responding and offer to reload automatically (db1de78ed67a4871bcbbd9866196ae7781c89e00); are you not seeing this?

**Comment by Aetet** [comment]
Yes. I know that. But Atom plugin addiotionally provide info if analyzer does not do any work and stuck.

**Comment by DanTup** [comment]
I'm not entirely sure what you're asking for, but I believe there are two things that might be related:

1. If the analyzer returns an error, Dart Code will offer to generate an error report for you to post on GitHub (this is the same as Atom)
2. If the analyzer crashes completely, Dart Code will notify you and give a button to reload

If you're hitting an error and those don't seem to be happening, can you provide more details so I can investigate?

**Comment by DanTup** [comment]
I don't think there's anything to do here; but please comment back if you think there is.
