### ISSUE TITLE
dart extension can't update to 3.13.2

### ISSUE THREAD

**Issue by TaleAi** [Dart-Code/Dart-Code#2720]
Issue Type: <b>Bug</b>

dart extension can't update to 3.13.2, when i install dart extension 3.13.2, and after installed, it changes to 3.11.0

Extension version: 3.11.0
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by DanTup** [comment]
Newer versions of the extension require newer versions of VS Code. The current stable version of VS Code is 1.47.3 but you're on 1.45.1. You'll beed to update VS Code before you can install the latest versions of the Dart/Flutter extensions.

Please let me know if you still have issues after updating VS Code. Thanks!
