### ISSUE TITLE
Build Task Warning for build_runner

### ISSUE THREAD

**Issue by Reprevise** [Dart-Code/Dart-Code#2721]
When I press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>B</kbd> to run build tasks in my Flutter project, I receive a warning in my Tasks output with the following message

> The task provider for "pub" tasks unexpectedly provided a task of type "flutter".

I enabled the preview setting `dart.previewBuildRunnerTasks`. 

Are the tasks added every time a user opens the build tasks menu in a Dart file? That would be a likely cause of the warning.

**Comment by DanTup** [comment]
Thanks for the report! This is fixed for the next version by #2660.

> Are the tasks added every time a user opens the build tasks menu in a Dart file?

We provide the tasks whenever VS Code asks for them. I don't know all the circumstances that might happen though (it's an implementation detail that doesn't affect the extension).
