### ISSUE TITLE
Contribute Tasks for "flutter install"

### ISSUE THREAD

**Issue by sidrao2006** [Dart-Code/Dart-Code#2723]
# Use Case

As available in IntelliJ and Android Studio, the install option will be very useful.
Currently in VS Code, we have to run the command in terminal.

A part of #2718

**Comment by BootBlock** [comment]
Duplicate of #226.

**Comment by DanTup** [comment]
This was misunderstood (by me) - `flutter install` is a command to install an app on a device, not about getting the SDK.

**Comment by DanTup** [comment]
These now show up under **Tasks: Run Task** -> **flutter** (same place as the `flutter build` tasks):

![Screenshot 2020-11-11 at 16 25 24](https://user-images.githubusercontent.com/1078012/98837298-b3500100-243a-11eb-9ecb-65fc621bb45b.png)
