### ISSUE TITLE
Please look at the food delivery application problem

### ISSUE THREAD

**Issue by gegak124** [Dart-Code/Dart-Code#2724]
**I purchased a code from https://codecanyon.net
The keyboard was installed correctly
But when I want to try the application in Android Studio, this message appears

What is the solution

Knowing everything is updated in the latest version and I did not understand this problem**

event sent after app closed: {id: 0, progressId: null, message: Running "flutter pub get" in flutter_application...}
`Because markets depends on fluttertoast 4.0.2 which doesn't match any versions, version solving failed.`
event sent after app closed: {id: 0, progressId: null, finished: true}
pub get failed (1; Because markets depends on fluttertoast 4.0.2 which doesn't match any versions, version solving failed.)

**Comment by BootBlock** [comment]
Hi there gegak124,

This repository is for issues with the VS Code extensions for Dart/Flutter; if you are having issues with the code you have purchased, you should contact the author of that code (they may have an updated version, for example).

Based on the error message you received, it seems the code is depending on version `4.0.2` of Fluttertoast - which does not exist on Pub:

https://pub.dev/packages/fluttertoast/versions

You may wish to review the dependency versions in the relevant `pubspecs.yaml` files.
