### ISSUE TITLE
Quick fix does not offer anymore a fix for "Prefer relative imports for files in `lib/`." problems

### ISSUE THREAD

**Issue by johngithubby** [Dart-Code/Dart-Code#2727]
The only action offered is `"ignore lint 'prefer_relative_imports' for this line"`
My analysis_options.yaml content:
`include: package:effective_dart/analysis_options.yaml`

[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G2021, locale en-CA)
[✓] VS Code (version 1.48.0)

**Comment by DanTup** [comment]
I'm unable to repro this, I have a "Convert to relative" fix when I set this up as you describe above:

<img width="497" alt="Screenshot 2020-08-24 at 10 54 34" src="https://user-images.githubusercontent.com/1078012/91031269-3f9b1680-e5f8-11ea-9f91-1f07eb7e34f8.png">

Could you try to reproduce this with a new project created with **Flutter: New Project** and if it repros, attach a zip of the whole folder (including the hidden items like `.packages` and `.dart_tool`)? Thanks!

**Comment by bsutton** [comment]
I'm also seeing this problem.

**Comment by bsutton** [comment]
I've also just noticed that the quick fix to convert a line from double to single quotes is also missing.

**Comment by DanTup** [comment]
Could you try to reproduce this with a new project created with **Flutter: New Project** and if it repros, attach a zip of the whole folder (including the hidden items like .packages and .dart_tool)?

Also - could you confirm your SDK version + whether `dart.previewLsp` is enabled or not? Thanks!

**Comment by bsutton** [comment]
I just created a new project using Flutter: New Project.

The quick change for strings works for a new project.

**Comment by DanTup** [comment]
If you copy your `analysis_options.yaml` over to the new project, does that break it? If not, are you able to try trimming down the project where this happens to something you can share? Thanks!

**Comment by bsutton** [comment]
This project exhibits the problem with tip 'convert to single quotes' missing.
[dscript.zip](https://github.com/Dart-Code/Dart-Code/files/5153793/dscript.zip)

**Comment by DanTup** [comment]
Perfect, thanks! I was able to reduce it to just this:

```dart
void main(List<String> args) {
  var server = "foo";

  print("Using: $server");
}
```

The fix is appearing on the first string, but missing on the interpolated string. There are tests that seem to do exactly the same thing so I'm trying to figure out what's different (in this case, the fix producer is ending up with the `print` token, and therefore produces no fix).

**Comment by bsutton** [comment]
Yes, I concur that its just on interpolated strings.

**Comment by DanTup** [comment]
I've got a potential fix at https://dart-review.googlesource.com/c/sdk/+/161171/.

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/fb0729b35dca3c52913100c1b7baaa0e1fe98e33.
