### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Monisha08** [Dart-Code/Dart-Code#2729]
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `3.13.2`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.48.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\monis\Dart-Code.dart-code-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by BootBlock** [comment]
> ⚠️ Make sure to **attach** this file from your _home_-directory:
> ⚠️`C:\Users\monis\Dart-Code.dart-code-unresponsive.cpuprofile.txt`

Would you be able to attach the specified file? Thanks!
