### ISSUE TITLE
Disallow editing of files in .pub-cache

### ISSUE THREAD

**Issue by bsutton** [Dart-Code/Dart-Code#2734]
I regularly work across multiple projects that are inter-related.

Lets say that I have project A and project B.

Project B depends on project A.

The code for both projects are on my local machine.

To create a release of project B I have to change my pubspec to pull Project A from pub.dev (rather than a local path).

This is fine. 

The problem is if I forget to move the pubspec dependency for Project A back to a local path.

So the scenario is:

I'm working happily in Project B within vscode.
I control-click through a method that is in Project A.
If find a problem in Project A and start editing the code.

The problem is that the code in Project A is being pulled from .pub-cache.

Whilst dart-code does provide a warning about editing in a external folder I ignore this message because I'm assuming that its just due to the local path to project A.

What I would like to see is that if you open a file in .pub-cache then vscode should make the code non-editable and ideally the notification dialog should be in a more aggressive colour such as red.

**Comment by DanTup** [comment]
> Whilst dart-code does provide a warning about editing in a external folder I ignore this message because I'm assuming that its just due to the local path to project A.

This warning shouldn't appear if you open both projects in the same VS Code window (which is the recommended way to work on multiple projects). If you're seeing it there, then we should consider that a bug and fix it. Woking that way, when the warning appears, you know you might be doing something wrong and should stop ignoring it :-)

I don't think there's much more we can do - there was a request for marking files as readonly in VS Code (https://github.com/microsoft/vscode/issues/17670) but it doesn't seem likely to be implemented. I don't want to make the warning red, as it's not really an error and that could also be confusing (I'm also not certain there are *no* instances where it's valid to do this - I've debugged a few packages by adding `print`s into their code in pubspec because it was easiest 😄).

**Comment by bsutton** [comment]
Hmm, I take your point. I too have occasionally hacked the cache to due some crude testing.

The problem is that it causes me grief more often than it helps.

The warning is only appearing if I'm opening files from a folder that isn't currently opened.
I just do this quite a lot :)
So I think its currently behaving as designed.

How about a middle ground.
Leave it blue if its just a normal external folder but make it red if its the cache.
I really do think that editing the cache should be considered a more critical mistake than just editing source from another project.

Playing in the cache will result in code being lost whilst edit source in another project will not normally result in lost code.

**Comment by DanTup** [comment]
> The warning is only appearing if I'm opening files from a folder that isn't currently opened.
> I just do this quite a lot :)

Is there a reason for this? If you're deliberately making changes to the project, it would be much better to add it to your workspace.

> I really do think that editing the cache should be considered a more critical mistake than just editing source from another project.

Sure, but the meaning of "error" suggests something failed or went wrong. If I got an error when editing a file, I would expect the editor did not apply or was rolled back. I think it'd be confusing to use here (it may suggest we blocked you from editing the file you shouldn't edit, but we didn't - so you need to be aware you changed it).

I think it would be better to not have the popup when it's not needed than have two levels of severity. Can you describe the setup when you do this a bit more? Maybe we can improve this - for example, if it's a local `path` dependency, what if the notification had a button "Add to Workspace". That would encourage adding to the workspace when editing, but if you really didn't want to, it would at least give you some indicator of whether it was a pubcache file (eg. the button wouldn't be there?).

**Comment by bsutton** [comment]
So I work on a fair no. of projects.

I have almost 20 of my own projects and I regularly raise prs on third
party projects (I have open prs on four projects at the moment).

I have some directly 'related' projects and for these I add folders to a
workspace.

So for example I maintain the flutter project Sounds which has a companion
project Sounds-common.
I have a workspace for these two related projects.

I have a project called pub_release which automates pushing a release to
pub.dev.
I use pub_release to release the Sounds project however it's not directly
related to Sounds so I don't add it to my workspace.
I also maintain the project dcli (previously dshell) that I use to build
cli apps. Sounds has a couple of tools that use dcli.
I often find bugs in dcli when working on other projects (such a Sounds or
pub_release) and I will habitually click through to the  dcli code and
start making edits.

At any point in time I have a number of outstanding PR's against third
party projects.
I keep an active copy of these third party projects on my system.
As with dcli I might find a bug in one of these third part projects and
click through and start editing.

With the likes of dcli or the third party projects, depending on the state
of the project, they may be active from pub-cache or from my local copy.

The end result is that I often click through an external project and end up
in pub-cache without realising it until I loose the edits.

**Comment by DanTup** [comment]
Ok, I've split the existing warning into two separate warnings - one for editing in pubcache (this is just a crude check on the path), and one for other files outside your workspace. This means there are now two settings that are set with their "Don't warn me" options:

```js
"dart.warnWhenEditingFilesOutsideWorkspace": true,
"dart.warnWhenEditingFilesInPubCache": true,
```

These both default to true, but you can set the first one to false and you'll not be warned for files outside the pub cache (but are outside your workspace). This allows you to only see warnings when you're editing in the pubcache, which will hopefully uncondition you from ignoring the warnings :-)

Hope this seems reasonable enough!
