### ISSUE TITLE
No need implement parseNumber, you can use parseInt directly.

### ISSUE THREAD

**Issue by Nomeleel** [Dart-Code/Dart-Code#2736]
parseNumber In [src/shared/utils/numbers.ts](https://github.com/Dart-Code/Dart-Code/blob/master/src/shared/utils/numbers.ts)

```ts
export function parseNumber(input: string): number {
	return input.toLowerCase().startsWith("0x")
		? parseInt(input.substring(2), 16)
		: parseInt(input, 10);
}
```
We can find the following explanation in the description of [parseInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt) on MDN:

```text
If radix is undefined, 0, or unspecified, JavaScript assumes the following:

1. If the input string begins with "0x" or "0X" (a zero, followed by lowercase or uppercase X), radix is assumed to be 16 and the rest of the string is parsed as a hexidecimal number.
2. If the input string begins with "0" (a zero), radix is assumed to be 8 (octal) or 10 (decimal). Exactly which radix is chosen is implementation-dependent. ECMAScript 5 clarifies that 10 (decimal) should be used, but not all browsers support this yet. For this reason, always specify a radix when using parseInt.
3. If the input string begins with any other value, the radix is 10 (decimal).

```
So we don’t need to judge, we can use parseInt directly

**Comment by DanTup** [comment]
Thanks! I have a lint enabled to always provide `radix` because of the behaviour of `2`, but I tested it in Node (which is where the extension code works) and it's 10 there, so you're right - we can simplify this. Thanks!
