### ISSUE TITLE
Intellisense and analysis not working in tests of some Dart packages

### ISSUE THREAD

**Issue by orestesgaolin** [Dart-Code/Dart-Code#2737]
When opening some Dart packages in VS Code and trying to navigate inside tests I don't see any intellisense suggestions and tests are not detected in files. Also code errors are not detected.

However, tests can be run via task "Dart: Run all tests" and their results are shown in the Test pane.

Example:

| my package | mockito |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/16854239/91028122-4b3d0c00-e5fd-11ea-9972-979a2835051a.png) | ![image](https://user-images.githubusercontent.com/16854239/91031321-b3412180-e600-11ea-8a80-4f9696d5f216.png) |

As you can see there's no way to launch tests within the file. Also when clicking "Go to Definition" an error "No definition found for Transaction" is shown. The same class can be accessed when opening tests in Flutter project.

![image](https://user-images.githubusercontent.com/16854239/91028390-b71f7480-e5fd-11ea-91f9-8e64def0ce2a.png)

Similarly to tests in Flutter apps I would expect inline `Run | Debug` actions be available.

The one difference I can see in the extension logs is following:

my Dart package:

```
[11:44:14] [General] [Info] Extension:Startup timing: 59ms
[11:44:14] [General] [Info] Found 0 folders requiring "pub get":  <--- 0 folders?
[11:44:14] [General] [Info] Analyzer:Startup timing: 348ms
[11:44:15] [General] [Info] Analyzer:FirstAnalysis timing: 576ms
```

mockito:
```
[11:43:47] [General] [Info] Extension:Startup timing: 38ms
[11:43:47] [General] [Info] Found 1 folders requiring "pub get":  <--- 1 folder?
    /Users/dominik/Projects/tmp/mockito
[11:43:47] [General] [Info] Analyzer:Startup timing: 338ms
[11:43:50] [General] [Info] Analyzer:FirstAnalysis timing: 2730ms
[11:46:36] [General] [Info] Pubspec /Users/dominik/Projects/tmp/mockito/pubspec.yaml was modified
[11:46:37] [General] [Info] Found 1 folders requiring "pub get":
    /Users/dominik/Projects/tmp/mockito
[11:47:49] [General] [Info] Pubspec /Users/dominik/Projects/tmp/mockito/pubspec.yaml was modified
[11:47:50] [General] [Info] Found 1 folders requiring "pub get":
    /Users/dominik/Projects/tmp/mockito
[11:47:51] [General] [Info] Pubspec /Users/dominik/Projects/tmp/mockito/pubspec.yaml was modified
[11:47:52] [General] [Info] Found 1 folders requiring "pub get":
    /Users/dominik/Projects/tmp/mockito
```

My package has relative dependencies in pubspec, e.g. `atm` but when trying similar approach with `mockito` it still works:

```
name: user_repository
description: redacted
version: 0.0.1

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  equatable: ^1.2.0
  meta: ^1.1.8
  atm:
    path: ../atm

dev_dependencies:
  effective_dart: ^1.2.0
  mockito: ^4.1.1
  test: ^1.14.2
  test_coverage: ^0.4.1
```

When looking into Dart Analyzer diagnostics I can see that no completions are generated for my package, whereas they are generated for `mockito`:

| my package | mockito |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/16854239/91031169-82f98300-e600-11ea-8e94-27c7063b6eea.png) | ![image](https://user-images.githubusercontent.com/16854239/91031194-8ab92780-e600-11ea-9f1a-8c9bf8c77cfd.png) | 

When I open Developer Console and right click on one class name (e.g. Transaction) and then "Find All References" following errors appear in console:

```
  ERR An unknown error occurred. Please consult the log for more details.   log.ts:197 
```

| screenshot |
| --- |
| ![image](https://user-images.githubusercontent.com/16854239/91032903-e684b000-e602-11ea-8a3e-402e21423d75.png) |

Dart extension and SDK version:

```
Dart extension v3.13.2
Analysis server version: 1.28.0
Dart SDK: 2.9.1 (stable) (Wed Aug 12 12:37:19 2020 +0200) on "macos_x64
```

VS Code:

```
Version: 1.48.1
Commit: 3dd905126b34dcd4de81fa624eb3a8cbe7485f13
Date: 2020-08-19T17:09:41.484Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0
```

Is there any other useful info that I can provide to investigate this issue?

**Comment by DanTup** [comment]
> [11:44:14] [General] [Info] Found 0 folders requiring "pub get":  <--- 0 folders?

I don't think that's related - it's just saying that no projects looks like they had outdated packages (eg. we don't need to run `pub get` for them).

Could you try enabling the [analysis server instrumentation file](https://dartcode.org/docs/logging/#analyzer-instrumentation) and see whether it looks anything interesting?

Can you also check if this happens in a new project created with **Dart: New Project** or does it only happen in this specific project? Thanks!

**Comment by orestesgaolin** [comment]
Issue resolved after recloning the repo. Unfortunately I've done that before reading about the instrumentation file. If it happens again I'll reopen the issue with additional data.

Thanks a lot for your suggestion!

**Comment by orestesgaolin** [comment]
For further reference: I encountered the issue today in tests of a package that was nested inside Flutter project. When I tried to log the analysis server as mentioned above the issue immediately got resolved. I.e. the same moment I enabled `Dart: capture logs` it started to work again

**Comment by DanTup** [comment]
> the same moment I enabled `Dart: capture logs` it started to work again

Could it just have been slow? Capturing logs only collects the output to disk, it shouldn't otherwise change any behaviour.

That said. - the request above was for an [instrumentation log](https://dartcode.org/docs/logging/#analyzer-instrumentation) (which needs to be set in the options, and is not the same as using **Capture Logs**. If you see this again, it's worth enabling that log and then the next time it occurs, grabbing a copy. Thanks!
