### ISSUE TITLE
Add a command to linkify package: links/filenames in selected text

### ISSUE THREAD

**Issue by bsutton** [Dart-Code/Dart-Code#2740]
So Eclipse has this really nice feature where you can paste a stacktrace into a window and then click in the stacktrace to open the source editor.
Its really handy.

So the scenario is:

I run an application in a terminal outside of vscode.
The app crashes with a stack trace.

I would then like to open a window (in the area that has 'problems', 'terminal'....)
Paste the stack trace from the terminal.

And then start clicking in the stacktrace and have vscode open the source coded editor for that file and at the correct line no.
I note that the terminal already has a drop list with different types of terminals.
Perhaps you could add a 'Stacktrace' terminal.

P.S.
I raise a lot of bug/pr requests on vscode which in someways is a negative starting point for a conversatin.

So just let me take a moment to thank you for the work you do on Dartcode.

I love vscode and your implementation of Dartcode. You are always really responsive and take a constructive approach to working through issues.

So thank you for the work!

**Comment by DanTup** [comment]
Is there a reason you don't use the built-in terminal to run this? I think in an upcoming VS Code version we can provide link providers so we could link things properly there.

That said, I often have stack traces elsewhere (for example, a test failure running on the buildbots) so I can see some value in this. Usually I cope/paste the filenames one at a time, then manually jump to the lines. Making this easier had never occurred to me!

I don't know if we can handle pasting into a terminal (we have pseudo-terminals, but we have to handle things like backspace and cursor keys ourself which is really tedious), but we do have access to the clipboard now, so perhaps something like a "parse stack trace from clipboard" command could read from the clipboard, then re-print it (linkified) somewhere (like a pseudo-terminal or similar)?

> I raise a lot of bug/pr requests on vscode which in someways is a negative starting point for a conversatin.
> 
> So just let me take a moment to thank you for the work you do on Dartcode.

Thanks! I don't see bug reports etc. as negative - they help make the product better, so definitely don't feel bad about raising them - I'd *much* rather get bug reports and feature requests than not.

**Comment by bsutton** [comment]
We have several use cases:

I often use the vscode terminal but sometimes I want a full screen edit
view and  a separate terminal window.
Or I'm just running some code that fails unexpectedly.

We have a lot of production cli apps written in  dart.
They are still somewhat immature so they fail sometimes.

As we roll out more production server side code we have a system where the
server code email our developers with a stack trace when an
exception occurs.
Its nice to be able to paste these stack traces into vs code and go
directly to the code.

And no I don't feel bad about raising issues, quite the opposite I see this
as contributing back to the community.

But it doesn't hurt to say thankyou occasionally :)

**Comment by DanTup** [comment]
Makes sense, thanks! I think it would probably work best written to a pseudo-terminal, so I'll take a look at this once https://github.com/microsoft/vscode/issues/91290 ships (which looks like the next VS Code release, likely early next month).

>  it doesn't hurt to say thankyou occasionally :)

Indeed - I appreciate it, thanks! 🙂

**Comment by bsutton** [comment]
pseudo-terminal sounds fine. Just need some where to paste the data and then click on it :)

**Comment by DanTup** [comment]
I've added a command named **Dart: Linkify Selected Editor Text into Terminal** (better name suggestions welcome!) which literally just pastes the selected text into the terminal (where the built-in and the Dart Package link providers will be active):

![Nov-18-2020 16-27-36](https://user-images.githubusercontent.com/1078012/99557877-100f6680-29bb-11eb-8a91-6fc4e9e70459.gif)

Right now, `dart:xxx` packages won't work, though in future that might improve. `package:` links will work as long as you have the project open (or a project with those packages) so we can resolve them to locations on disk.

**Comment by bsutton** [comment]
So my biggest concern is that if I run a command from the cli and get a stack trace I have to open a new file paste it and then linkify it.
I was hoping to just open a special psuedo terminal (or similar) and paste directly into the terminal which would then automatically linkify it.

Where can I get this version to test it?
I'm running 3.16 but it doesn't appear.

**Comment by bsutton** [comment]
sorry, I just saw the 3.17 milestone.

**Comment by DanTup** [comment]
Yeah, this isn't released yet.

I thought a common case may be opening a log file or pasting much more text than just the stack, so it may be convenient to put into an editor. If you wanted to paste directly into a terminal, you could probably do that today (by just prefixing with `echo`). However, pasting in a huge string will result in the string appearing twice (once from your paste, and once from it being echo'd back). I'm not sure if there's a simpler way.
