### ISSUE TITLE
Unverified breakpoint while running tests

### ISSUE THREAD

**Issue by Tregan** [Dart-Code/Dart-Code#2742]
When running a test by clicking on "Debug" above that test, a break point set in the non-test code is seen as unverified and thus is never hit. You can check this by having a *_test.dart file that tests functionality in *.dart. Set a breakpoint in both files, then run the test. The breakpoint in the test itself will be triggered, but the other one won't.

*_test.dart:
![image](https://user-images.githubusercontent.com/1019425/91280742-7d7a7500-e787-11ea-98fe-93ef78c4c5c2.png)

*.dart:
![image](https://user-images.githubusercontent.com/1019425/91280791-8e2aeb00-e787-11ea-9cfa-b94ca5bbd249.png)

I've found 2 workarounds, but I don't really find them all too handy:
1. Set breakpoint in the test and use `step into`. Works fine, but still the breakpoint in the non-test file won't be hit.
2. Add `debugger();` to the non-test file where you want a breakpoint to trigger, but you can't set those on the fly.

**Comment by DanTup** [comment]
I've not been able to reproduce this:

<img width="1136" alt="Screenshot 2020-08-26 at 10 00 10" src="https://user-images.githubusercontent.com/1078012/91283786-f2977b80-e782-11ea-98d1-c828de4fa497.png">

Are you able to attach a small example project that shows it, and also a log file from reproducing?

- Run the **Dart: Capture Logs** command
- Untick **Analysis Server** but leave everything else ticked and click **OK**
- Run the test and hit the first breakpoint
- Press `F5`/**Continue** to attempt to hit the second breakpoint
- Click **Cancel** on the logging notification to stop logging and open the log file

Thanks!

**Comment by Tregan** [comment]
I just made a new Flutter project and that seems to work fine, as you said. If I add 2 new files to my project (*.dart and *_test.dart) that also seems to work as well. The problem occurs when I'm trying to debug an existing file.

I'll do some more research and update you asap. That file has quite a few different things that might be causing issues (async setupall, async setup, methodchannels, mocks), so it might take a while for me to isolate the problem.

I will update you asap.

**Comment by DanTup** [comment]
Right now we don't resolve breakpoints properly - they should all be marked as resolved immediately. This makes me think an error may be occurring when trying to set this breakpoint - so a log file might help.

- Run **Dart: Capture Logs**
- Untick **Analysis Server** but leave everything else ticked and click **OK**
- Try setting the breakpoint
- Click **Cancel** on the logging notification to stop logging and open the log

Maybe there's an error in there?

**Comment by Tregan** [comment]
Yeah there's something very wonky going on.

We have a notification center that's responsible for scheduling notifications and checking permissions etc. This file is in `/lib/notification_center.dart`. The unit test for this is in `/test/unit/notification_center_test.dart`. Setting a breakpoint in notification_center.dart and starting a debug test in notificationh_center_test.dart -> not triggered.

Now the weird part: when I create the file `/lib/breakpoint.dart` and literally copy/paste the contents from notification_center.dart into it, then go to notification_center_test.dart and change the import and set the breakpoint at the same line -> works, breakpoint triggered.

Log where I'm testing notification_center.dart:
[notification_center.txt](https://github.com/Dart-Code/Dart-Code/files/5129413/notification_center.txt)
This file contains a couple of these errors:
```
[13:04:56] [VmService] [Info] [Tests ] <== {"jsonrpc":"2.0", "result":{"type":"Success"},"id":"1657"}
[13:04:56] [VmService] [Info] [Tests ] ==> {"id":"1658","jsonrpc":"2.0","method":"addBreakpointWithScriptUri","params":{"isolateId":"isolates/3958223168666159","scriptUri":"file:///D:/Knowingo/knowingo_flutter/lib/notification_center.dart","line":47}}
[13:04:56] [VmService] [Info] [Tests ] <== {"jsonrpc":"2.0", "error":{"code":102,"message":"Cannot add breakpoint","data":{"request":{"method":"addBreakpointWithScriptUri","params":{"isolateId":"isolates\/3958223168666159","scriptUri":"file:\/\/\/D:\/Knowingo\/knowingo_flutter\/lib\/notification_center.dart","line":"47"}},"details":"addBreakpointWithScriptUri: Cannot add breakpoint at line '47'"}},"id":"1658"}
[13:04:56] [VmService] [Error] [Tests ] Cannot add breakpoint
[13:04:56] [VmService] [Info] [Tests ] ==> {"id":"1659","jsonrpc":"2.0","method":"setExceptionPauseMode","params":{"isolateId":"isolates/3958223168666159","mode":"None"}}
[13:04:56] [VmService] [Info] [Tests ] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"_DebuggerSettingsUpdate","isolate":{"type":"@Isolate","id":"isolates\/3958223168666159","name":"main","number":"3958223168666159"},"timestamp":1598439896771,"_debuggerSettings":{"_exceptions":"none"}}}}
[13:04:56] [VmService] [Info] [Tests ] <== {"jsonrpc":"2.0", "result":{"type":"Success"},"id":"1659"}
[13:04:56] [VmService] [Info] [Tests ] ==> {"id":"1660","jsonrpc":"2.0","method":"resume","params":{"isolateId":"isolates/3958223168666159"}}
[13:04:56] [VmService] [Info] [Tests ] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"Resume","isolate":{"type":"@Isolate","id":"isolates\/3958223168666159","name":"main","number":"3958223168666159"},"timestamp":1598439896801}}}
[13:04:56] [VmService] [Info] [Tests ] <== {"jsonrpc":"2.0", "result":{"type":"Success"},"id":"1660"}
```

Log where I'm testing breakpoint.dart:
[breakpoint.txt](https://github.com/Dart-Code/Dart-Code/files/5129414/breakpoint.txt)

As I said above: both notification_center.dart and breakpoint.dart contain the exact same code. The test is exactly the same for these 2 files, except that the import is changed. Works fine for breakpoint.dart and the breakpoint is triggered.

**Comment by DanTup** [comment]
@Tregan Is it possible you have a mix of imports that use relative paths and `package:` paths? I've seen errors like this before when the VM had the same file loaded twice. I think in Observatory it gives a slightly better error message (you can use the **Open Observatory** command, then using the debugger in there try to set the breakpoint in the console using the path), but it may be easier to just check your imports aren't mismatched.

**Comment by Tregan** [comment]
@DanTup Yep that seems to be exactly what's happening! I use quite a few relative paths for tests to avoid duplicate code and provide helpers etc. I temporarily removed the relative path and declared everything in the test file and that fixes it. I guess I'm going to have to find a way to not use relative paths anymore while still keeping the functionality this provides. I doubt this should be considered an issue in Dart-Code then, so it can probably be closed. Thanks for taking a look at this!

**Comment by DanTup** [comment]
@Tregan you should only need to switch your relative paths for `package:` includes (or vice versa) - you shouldn't need to move anything around. There are some lints you can enable to help avoid using mixed import types depending on your preferences:

- https://dart-lang.github.io/linter/lints/avoid_relative_lib_imports.html
- https://dart-lang.github.io/linter/lints/prefer_relative_imports.html
- https://dart-lang.github.io/linter/lints/always_use_package_imports.html

**Comment by Tregan** [comment]
@DanTup the problem I'm having is that the helpers are only used in tests, and `package:` doesn't seem to work with that, only relative imports.

- lib
- test
  - helpers
  - unit
    - notification_center_test.dart

Where notification_center_test is importing files from helpers.

**Comment by DanTup** [comment]
@Tregan it's fine to have relative imports for things outside of `lib` - as there's no other way to import them. The issue is when you have imports for the same library both as a `package:` URI and relative URI.

My guess is that you have an import that starts `package:` for `notification_center.dart` and also something that imports it without a `package:` URI (for example in a test, importing it as `../lib/notification_center`).

If that doesn't seem to be the case and you can make a small repro you can share, I'd be happy to take a look. You definitely shouldn't need to restructure anything or stop importing your helpers inside lib (and the lints are smart enough to only trigger when you're doing something you can prevent).

**Comment by Tregan** [comment]
@DanTup Double-checked my files and I'm only using relative imports in tests to access helper files. Managed to reproduce it though, start by just creating a new flutter project and add the following files:

`lib/breakpoint.dart`
```
class Breakpoint {
  int breakpoint() {
    final int value = 1;
    return value;
  }
}
```

`test/helpers/helper.dart`
```
import 'package:mockito/mockito.dart';
import 'package:hello_world/breakpoint.dart';

bool someHelperFunction(int value) => true;

class MockBreakpoint extends Mock implements Breakpoint {}
```

`test/unit/breakpoint_test.dart`
```
import 'package:flutter_test/flutter_test.dart';
import 'package:hello_world/breakpoint.dart';

import '../helpers/helper.dart';

void main() {
  Breakpoint instance;

  setUp(() {
    instance = Breakpoint();
  });

  test('breakpoint', () {
    final int actual = instance.breakpoint();
    final bool didSucceed = someHelperFunction(actual);

    expect(didSucceed, isTrue);
  });
}
```

In `pubspec.yaml` add `mockito: ^4.1.1` to `dev_dependencies`.

`Pub get`, set a breakpoint on line 3 in `breakpoint.dart` and then debug the test. Breakpoint won't be hit, test succeeds.
![image](https://user-images.githubusercontent.com/1019425/91319742-0364e300-e7bd-11ea-928f-9b19e11c5b7b.png)

It happens as soon as mockito is added. Commenting out line 7 in helper.dart fixes it.
![image](https://user-images.githubusercontent.com/1019425/91319938-432bca80-e7bd-11ea-8f0a-36b87baea355.png)

**Comment by DanTup** [comment]
Great, thanks for the repro! I can reproduce this and if I try to set the breakpoints via Observatory I get these messages:

```
$ break /Users/danny/Desktop/TestProjects/repro_breakpoint_issue_2742/lib/breakpoint.dart:3
Script '/Users/danny/Desktop/TestProjects/repro_breakpoint_issue_2742/lib/breakpoint.dart' not found
$ break package:repro_breakpoint_issue_2742/breakpoint.dart:3
Script 'package:repro_breakpoint_issue_2742/breakpoint.dart' is ambiguous
```

I can't find a way to list the scripts in Observatory (nor is it implemented in VS Code), but I think this is the message we'd usually see if the script was loaded both ways. This seems like a VM bug to me - I think this should work, so I think it's worth raising at https://github.com/dart-lang/sdk (feel free to CC me when you do in case I can be of any help).

Thanks!

**Comment by Tregan** [comment]
> Great, thanks for the repro! I can reproduce this and if I try to set the breakpoints via Observatory I get these messages:
> 
> ```
> $ break /Users/danny/Desktop/TestProjects/repro_breakpoint_issue_2742/lib/breakpoint.dart:3
> Script '/Users/danny/Desktop/TestProjects/repro_breakpoint_issue_2742/lib/breakpoint.dart' not found
> $ break package:repro_breakpoint_issue_2742/breakpoint.dart:3
> Script 'package:repro_breakpoint_issue_2742/breakpoint.dart' is ambiguous
> ```
> 
> I can't find a way to list the scripts in Observatory (nor is it implemented in VS Code), but I think this is the message we'd usually see if the script was loaded both ways. This seems like a VM bug to me - I think this should work, so I think it's worth raising at https://github.com/dart-lang/sdk (feel free to CC me when you do in case I can be of any help).
> 
> Thanks!
