### ISSUE TITLE
Renaming to private is not possible if item is used elsewhere

### ISSUE THREAD

**Issue by szotp** [Dart-Code/Dart-Code#2745]
1. Have two files, as described below.
2. Attempt to rename foo into _foo.

Got:
Alert appears: `Renamed top level variable will be invisible in ''.`
There is no option to force the rename.

Expected:
Alert appears: `Renamed top level variable will be invisible in main.dart`
Alert has "Force" button that renames anyway - I would like to rename and then fix the errors.

This is especially annoying if given item is used 100x times in one file and 10x in other files, because now you have to find all references of it, remove them, and then attempt the rename again. Overall takes much longer than forced rename which we had before.

Sample files:
```dart
// main.dart
import 'other.dart';

void main(List<String> arguments) {
  print('Hello world! $foo');
}
```
```
// other.dart
var foo = 1;
```

**Comment by DanTup** [comment]
I'm splitting this into two issues, because one is fixed but the other is a bit trickier.

The bad error message is covered by https://github.com/Dart-Code/Dart-Code/issues/2818, and this issue is for being able to force the rename.

**Comment by DanTup** [comment]
Got a fix in progress for LSP at https://dart-review.googlesource.com/c/sdk/+/167621/.

![rename_prompt](https://user-images.githubusercontent.com/1078012/96011978-890b2380-0e3b-11eb-9ce3-098bd440a801.gif)

**Comment by DanTup** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/ece17f73b0b1b15417d07e2dcbe79f4974f90ba0 and should show up in a future SDK release.
