### ISSUE TITLE
"Cannot read property 'thread' of undefined" during debug session end

### ISSUE THREAD

**Issue by pankaj-nayak** [Dart-Code/Dart-Code#2746]
- Issue Type: `Bug`
- Extension Name: `dart-code`
- Extension Version: `3.13.2`
- OS Version: `Darwin x64 19.5.0`
- VSCode version: `1.48.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 85,
		"activateCallTime": 10,
		"activateResolvedTime": 450,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "Dart-Code.dart-code",
				"_lower": "dart-code.dart-code"
			},
			"activationEvent": "workspaceContains:**/pubspec.yaml,**/*.dart"
		}
	},
	"runtimeErrors": [
		{
			"name": "TypeError",
			"message": "Cannot read property 'thread' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'thread' of undefined"
		}
	]
}
```

**Comment by DanTup** [comment]
Thanks - I think this was fixed by b2244fea7ae57708f099cace684c97602e37cbc5 which will be included in the next release. If you still see it after the next release (expected late next week) please let me know!
