### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by lucianodouglasm2** [Dart-Code/Dart-Code#2747]
- Issue Type: `Bug` - Extension Name: `dart-code` - Extension Version: `3.13.2` - OS Version: `Windows_NT x64 10.0.19041` - VSCode version: `1.48.2` :warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by DanTup** [comment]
> ⚠️ We have written the needed data into your clipboard. Please paste! ⚠️

Are you able to provide this data? It's not clear what the issue is with it. Thanks!
