### ISSUE TITLE
Package paths are resolved incorrectly for flutter repo

### ISSUE THREAD

**Issue by abarth** [Dart-Code/Dart-Code#275]
# Steps to reproduce

1. `git clone https://github.com/flutter/flutter.git`
2. `cd flutter`
3. `./bin/flutter update-packages` (This command runs pub for all the packages in this repository)
4. Open this directory in VSCode with Dart-Code plugin.
5. Open `packages/flutter/lib/src/widgets/drag_target.dart` in the editing pane.

# Expected result

The analyzer should be able to find the `package:flutter/xxx.dart` imports at the top of the file and should understand classes like `Velocity` and `Offset`.

# Actual result

The tool seems confused by there being multiple packages open in the same window.  For example, the imports are flagged as errors and `Velocity` and `Offset` also have red underlines.

If you open `packages/flutter` in its own window, then everything works fine.  It's just that there are a dozen or so packages in this repo and I'd like to work with them all in the same window.

**Comment by abarth** [comment]
I'm using version 1.0.2 of Dart-Code.

/cc @devoncarew @eseidelGoogle

**Comment by DanTup** [comment]
I believe the behaviour that handles this in Atom is described [here](https://github.com/dart-atom/dartlang/issues/762#issuecomment-183477067):

> The atom plugin scans recursively for dart projects from the roots (w/ a cut-off depth of 3 levels). We then pass located dart projects to the analysis server as roots; it will scan those for nested dart projects.

This seems like reasonable logic to use.

**Comment by DanTup** [comment]
I believe I've fixed this; however I get this error (both when opening the flutter package directly, and the parent):

> file: 'file:///m%3A/Coding/Applications/flutter/packages/flutter/lib/src/material/user_accounts_drawer_header.dart'
severity: 'Error'
message: 'The name 'debugCheckHasMaterial' is defined in the libraries 'debug.dart' and 'debug.dart'.'
at: '183,12'
source: 'dart'

I don't think this is related (since it happens when opening the filter directly too - possibly something is wrong with my checkout - I did get errors running the update script as referenced above), so I'm gonna push this fix out.

Please give it a try and let me know if you have any other issues!

**Comment by abarth** [comment]
Thanks!

**Comment by devoncarew** [comment]
@DanTup, the logic that Atom uses is a little heavy weight. If I were to re-do it, I would probably just create one analysis context for the opened folder, and let the analysis server figure out all the sub-projects from there.

**Comment by DanTup** [comment]
@devoncarew Aren't you describing how Dart Code originally worked? The AS didn't seem to correctly resolve packages. Now we will create one analyzer, but send each package root that we found in analysis roots (this seems to cause their package resolution to work).

This does feel like something the AS should handle itself IMO (each IDE shouldn't have to work around it), but it didn't seem to (hence this bug, and presumably your original implementation in Atom?).

**Comment by devoncarew** [comment]
I as a little over-careful of how I sent in analysis roots in Atom. The analysis server definitely handles the multiple-sub-projects-in-a-directory thing. I'm not sure of the exact issue but it should be possible to get the same working in VSCode.

**Comment by DanTup** [comment]
Hmmm; then I wonder why it didn't work here. I wonder @bwilkerson might have an idea? Setting the analysis root to the Flutter repo caused code below `packages/flutter/` not to resolve packages properly (at `packages/flutter/.packages` it says that `flutter` maps to `lib`, but the files inside there referencing `package:flutter/xxx.dart` didn't resolve and got squiggles). (Original comment in this case has more details).

Sending each child folder that contains a pubspec instead has solved the problem.

**Comment by bwilkerson** [comment]
I don't know. I would have expected that server would have looked in the subdirectories, found the pubspec.yaml files, and created new context roots in each of those locations.

I just tried this in IntelliJ. I had several errors until I got everything update and configured correctly. It might not all be necessary, but I executed
```
> git pull; git fetch origin
> flutter upgrade
> flutter update-packages
```
After that, everything is analyzing cleanly.

**Comment by DanTup** [comment]
Hmm, strange. Ok, if it seems like the analyzer should handle this, I'm gonna re-open this as a task to migrate back to one-analysis-root and debug further in the process (it'd fix some niggles this change introduced too).

I'll do some digging through the logs/instrumentation file first, but might shout if I get stuck!

**Comment by DanTup** [comment]
I've reverted the changes originally made to fix this because it introduced #280 and based on comments above it shouldn't be necessary. I've opened https://github.com/dart-lang/sdk/issues/29414 with a simple repro for investigation by the analyzer team to see whether this is a bug there or if there's something Dart Code is doing incorrectly.

**Comment by DanTup** [comment]
@abarth This seems to be caused by naming the folder `packages` and it sounds like the analyzer might not be updated to handle this for a while.

Is renaming your folder a possibility? I'd like to revert this workaround (as well as feeling clumsy, it introduced another issue) but if renaming your folder isn't reasonable, I can try and find another workaround that fixes both issues until the analyzer is updated.

**Comment by abarth** [comment]
> Is renaming your folder a possibility?

We've discussed renaming that directory before and decided not to do it.  "packages" is the most accurate name (because the directory contains packages) and there are a number of other things that depend on the name (e.g., `pub` knows about it).

My guess is that the best resolution is for the analyzer to remove its special casing of directories named "packages".  As far as I know, there's no longer any reason for the analyzer to treat that name specially.

**Comment by DanTup** [comment]
Yeah, I think we all agree on that; but I think it might take a while.

> e.g., pub knows about it

If the analyzer stops special-casing this folder, wouldn't it make sense for `pub` to do the same? Aren't they both based on the old behaviour?

**Comment by abarth** [comment]
> Yeah, I think we all agree on that; but I think it might take a while.

I've asked in the other bug what the complexity is.  If it's not too hard, I can try fixing the analyzer myself.

> If the analyzer stops special-casing this folder, wouldn't it make sense for pub to do the same? Aren't they both based on the old behaviour?

`pub` knows about the directory to implement the `sdk` source for Flutter.  When you depend on `package:flutter`, you get it from `source: sdk` rather than from pub.dartlang.org.  `pub` knows where to find your `flutter.git` image and knows how to find the packages inside of it.

We could change that, of course, but we're just being a bit stubborn about not using a worse name for the directory to work around bugs in the analyzer.

> I'd like to revert this workaround (as well as feeling clumsy, it introduced another issue)

If you'd like to revert your workaround, that's fine with me.  It sounds like it will only cause trouble for me personally.  When I filed this issue, I thought it was causing trouble for everyone with multiple packages.

**Comment by DanTup** [comment]
> If you'd like to revert your workaround, that's fine with me. It sounds like it will only cause trouble for me personally. When I filed this issue, I thought it was causing trouble for everyone with multiple packages.

I'd rather not break anyone using Dart Code so I'll see if I can come up with something to handle both (maybe I'll put this behaviour behind a hidden setting you can enable until the analyzer is changed, or detect when something is inside a `packages` folder).

**Comment by devoncarew** [comment]
> My guess is that the best resolution is for the analyzer to remove its special casing of directories named "packages".

Just for some context, the analyzer is implementing the spec for `.packages` files, which has info about how to handle `packages` folders (whether they're symlinks created by pub or regular directories created by users). So I think the options here would be to adjust the spec, or to put a one-off patch into the analysis server to special case the `packages` folder in the flutter repo.

**Comment by devoncarew** [comment]
I _think_ this is the right link for the spec: https://github.com/dart-lang/dart_enhancement_proposals/blob/master/Accepted/0005%20-%20Package%20Specification/DEP-pkgspec.md

**Comment by DanTup** [comment]
Ok, I've made changes to the workaround I added to solve this. Since I couldn't come up with a great way of knowing whether the `packages` folder is an old `--packages-dir`-type folder I just made it trigger the workaround based on a file I can see exists in the flutter repo (`packages/.gitignore`). This is rather disgusting, but it should make the flutter repo useable.

Without that file, we'll just use original behaviour (pass the single root to the analyzer). This will stop issues like #280.

Once https://github.com/dart-lang/sdk/issues/29414 is fixed/released, I'll remove this code (I've raised #284 for that).

I'm just doing some more testing, but I expect to push this out in an update later today. Please test it out and let me know if it's behaving ok.

**Comment by DanTup** [comment]
I've uploaded a dev release here if you'd like to test this is working as expected before I push a release out:

https://github.com/Dart-Code/Dart-Code/releases/tag/v1.2.0-dev-1

**Comment by DanTup** [comment]
v1.2.0 has been published which reverts the workaround made for this issue unless a `packages\.gitignore` file is detected. This should fix the Flutter repo issue until the Analyzer is updated (as long as you keep that file in the packages folder!).

**Comment by yyoon** [comment]
I just hit this issue in our project tree, which also has a directory called `packages` with multiple dart packages in it. As a workaround I added a `.gitignore` file under `packages` directory and it works fine now, but I hope this gets resolved in a better way in the future.

**Comment by DanTup** [comment]
@yyoon Fixing this properly is work in the Dart SDK. There's a case at https://github.com/dart-lang/sdk/issues/29414 which you may wish to subscribe to. Once that's resolved the `.gitignore` trigger won't be required (and [the workaround will be removed](https://github.com/Dart-Code/Dart-Code/issues/284)).
