### ISSUE TITLE
Validate routes and routenames

### ISSUE THREAD

**Issue by sidrao2006** [Dart-Code/Dart-Code#2751]
The extension does not validate route names. If a route is not specified in main.dart, the error is a runtime error and is not shown in editor. Also it doesn't validate whether the routes exist.

The extension should also be able to detect unused as well as duplicate route names.

When a route is absent but is being used, an option to create a route with the given name should be available using quick fix

**Comment by DanTup** [comment]
I don't think there's a feasible way to do this as route names are just strings. You could have dynamic route names, like:

```dart
MaterialApp(
  initialRoute: '/',
  routes: {
    '/': (context) => FirstScreen(),
    '/second': (context) => SecondScreen(),
    '/$someVariable': (context) => VariableScreen(),
  },
);
```

I think a better option would be to use constants for your route names ([see here for an example](https://github.com/flutter/gallery/blob/b0c42143982457eb780533c84db87f8d991ccfd9/lib/studies/starter/app.dart#L15)).

You should get warnings if you define duplicates in your routes though:

<img width="649" alt="Screenshot 2020-08-31 at 10 23 27" src="https://user-images.githubusercontent.com/1078012/91704870-10deec00-eb74-11ea-9ee0-26beda22b3eb.png">

Hope this makes sense - please let me know if anything is unclear.

**Comment by sidrao2006** [comment]
@DanTup thanks a lot for replying
Probably cant use constants but alright. It would have been great to use enums for route names, that way the dart analyzer could easily detect duplicates and unused routes

**Comment by DanTup** [comment]
@sidrao2006 why are you unable to use constants? The sample I listed uses constants.

Using enums or something would need to be a change in Flutter, as the signature takes strings. You should get notification of duplicates like in my screenshot though (even with constants). Detecting unused routes would be very difficult, as you'd need to examine all code (and assume nobody else is depending on this code from outside the current project), and you wouldn't know if someone pushes the route with the name in a non-static way (for example from a variable that can't easily be traced).

If you use constants (you could put them all in a single class/file if you wanted), you could at least find-references on them to see where they're used.

Hope this helps!

**Comment by sidrao2006** [comment]
Ok thanks a lot
