### ISSUE TITLE
Encapsulation is made complicated 

### ISSUE THREAD

**Issue by sidrao2006** [Dart-Code/Dart-Code#2752]
In Dart, encapsulation is achieved by adding an ' _ ' in front of the field. However the extension creates new methods and adds a lot of code, to achieve the same goal, which is not needed.

**Comment by DanTup** [comment]
Adding a `_` to the wrong of a field only makes the field private. The "Encapsulate Field" action is designed to do more than that - it's designed to generate a getter/setter so the field can still be accessed from outside of the class:

```dart
  String _name;

  String get name => _name;

  set name(String name) {
    _name = name;
  }
```

If you only want to make a field private, you should use the "Rename" refactor (press `F2`) and just rename the field to start with an `_`. Encapsulate field is for where you want to expose the value through a getter/setter (for example to do some additional work on the raw value before setting/returning it).

Please let me know if I've misunderstood. Thanks!

**Comment by sidrao2006** [comment]
Thanks a lot for the info @DanTup
