### ISSUE TITLE
Auto import failure

### ISSUE THREAD

**Issue by sidrao2006** [Dart-Code/Dart-Code#2753]
Auto import fails when the file is already imported using show/hide. 
Auto import should also be able to add or remove class names and element names in show list, and remove names from hide list

**Comment by DanTup** [comment]
Thanks for the report! This behaviour is driven by the Dart SDK's analysis server so would need to be implemented/raised at https://github.com/dart-lang/sdk/issues. If you raise it there, please post a link back here for others to find if they come across this issue.

In the meantime, as a slight workaround - if you complete a class and it's not added to the `show` list, there is a quick-fix to add the class to the `show` list.

Thanks!
