### ISSUE TITLE
add support for Eclipse Che

### ISSUE THREAD

**Issue by gattytto** [Dart-Code/Dart-Code#2754]
hello @DanTup I am starting some tests around the extensions you made for both dart and flutter in ms-vscode to see if we can use them in Eclipse Che which is a Theia based web-ide, I leave the links here in case you can help on the testing and maybe you can give me some pointers to have it 100% working

https://github.com/eclipse/che/issues/17731
https://github.com/eclipse/che/issues/17732

**Comment by DanTup** [comment]
Can you clarify what doesn't work? GitPod is based on Theia and things mostly work there (see https://github.com/DanTup/gitpod-flutter-web) however it requires a slightly custom build right now (on a branch at https://github.com/Dart-Code/Dart-Code/tree/temp-gitpod-build) due to Theia missing some recent VS Code APIs.

**Comment by gattytto** [comment]
thank you for the detailed answer and the link @DanTup I will look it up right away. 

to sumarize what works and what doesn't I have uploaded some [screenshots](https://github.com/eclipse/che/issues/17731#issuecomment-683472184) and updated the [first comment](https://github.com/eclipse/che/issues/17731#issue-687411129) with info and stuff I still haven't yet figured out. 

for things that don't work I can see there is a flutter view provided by the dart extension but it seems to be empty (check screenshots), what should go there? .

**Comment by DanTup** [comment]
> Dart extension seems to have the "flutter" view added to vscode, althought flutter has its own ms-vscode extension it seems to pretty much rely on the dart extension

The Flutter extension does rely on the Dart extension. Most of the Flutter work is currently inside the Dart extension, but will be migrated (though there will always be a dependency on the Dart extension, as that will provide all of the language support when working on Flutter apps).

> the redirection for devtools doesn't work outside of the container.

It's not clear how you got to this stage (or which version of the extensions you're using). It looks like you may have run DevTools, but it doesn't look like you're in a debug session. The Dart extension has integration with DevTools, but you shouldn't run it manually - you would start a debug session and then run the **Dart: Open DevTools** command. If you run commands in the built-in terminal they are completely disconnected from the extension and can't interact with the extension in any way.

I would recommend running the extension locally in VS Code (or on GitPod) to get a better feel for how things are supposed to work.
