### ISSUE TITLE
Local packages (using the `path` option in the `pubspec.yaml` file) are ignored by debugger

### ISSUE THREAD

**Issue by shroudedcode** [Dart-Code/Dart-Code#2758]
I have a Flutter project where I'm pulling in a local (non-Flutter-specific) Dart package as a dependency like this:

```yml
dependencies:
  example:
    path: ../example
```

This generally works without any issues, but it turns out that the VS Code debugger seems to ignore all code within this package. There's no way to step into functions from this package when setting a breakpoint and when an exception is thrown inside of it, there's no way to get to its actual source.

Note that I've set the debugger to *Debug my code + packages + SDK*, so I would expect to be able to debug absolutely everything. Am I just missing something here or is this bug?

**Comment by DanTup** [comment]
> Note that I've set the debugger to Debug my code + packages + SDK, so I would expect to be able to debug absolutely everything.

This should work fine if you've set that. Another option would be to just add the other project to the workspace (File -> Add Folder to Workspace) and then it should be debugged regardless of the debug setting.

Could you capture a log (using the [**Dart: Capture Logs** command](https://dartcode.org/docs/logging/#capture-logs-command), untick **Analysis Server** but leave everything else ticked), starting before you launch the debug session and including trying to step into this code?

Thanks!

**Comment by letsar** [comment]
Hi, It also happen to me, but only when I set the breakpoint during the debug session.
I captured some logs, and I have these kind of logs when I add breakpoints:
`[1:25:05 PM] [VmService] [Info] [Flutter (iPhone 11 Pro)] <== {"jsonrpc":"2.0", "result":{"type":"Breakpoint","fixedId":true,"id":"breakpoints\/7","breakpointNumber":7,"resolved":false,"location":{"type":"UnresolvedSourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@20192823\/scripts\/package%3Axxxx%2Fsrc%2Fcore.dart\/174c5020265","uri":"package:xxxx\/src\/core.dart","_kind":"kernel"},"line":128}},"id":"620"}`

**Comment by DanTup** [comment]
@letsar are you able to provide a complete log for the while debug session when reproduce this? (or a small repro project with instructions that I can use to try and repro here?). Thanks!
