### ISSUE TITLE
vscode run flutter command An error

### ISSUE THREAD

**Issue by d1y** [Dart-Code/Dart-Code#2759]
I don't understand why this is happening

```bash
events.js:180
      throw er; // Unhandled 'error' event
      ^

[Error: connect ECONNREFUSED 127.0.0.1:443
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
Emitted 'error' event at:
	at TLSSocket.socketErrorListener (_http_client.js:399:9)
	at TLSSocket.emit (events.js:203:13)
	at emitErrorNT (internal/streams/destroy.js:91:8)
	at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
	at processTicksAndRejections (internal/process/task_queues.js:77:11)] {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 443
}

```

I tried to close all the extensions and just start dart and flutter extensions and it seems to work. It seems to conflict with the VIM plug-in (I don't know if this is the case). What is the reason for this
I don't know if I've described it in enough detail
Thank you for

![wow.gif](https://i.loli.net/2020/09/01/zDq845kyr3ZnP1a.gif)

**Comment by DanTup** [comment]
Could you try setting the [dart.extensionLogFile](https://dartcode.org/docs/logging/#extension) setting in VS Code to enable logging, and grab a copy of the log file after reproducing this? It looks like the extension is not activating correctly though it's not clear why.

There's also an error that shows briefly in your video that you clear that might be related, but it was too quick for me to see.

The second error (the one you pasted above) seems to happen then the extension host terminates - again, it's not clear why that's happening but it might be related.

There should be no issues using the Vim extension with the Dart one, however there may be some performance issues in doing so if not using the LSP preview mode (the `dart.previewLsp` setting). Does the issue only occur when Vim is enabled?

**Comment by d1y** [comment]
> Could you try setting the [dart.extensionLogFile](https://dartcode.org/docs/logging/#extension) setting in VS Code to enable logging, and grab a copy of the log file after reproducing this? It looks like the extension is not activating correctly though it's not clear why.
> 
> There's also an error that shows briefly in your video that you clear that might be related, but it was too quick for me to see.
> 
> The second error (the one you pasted above) seems to happen then the extension host terminates - again, it's not clear why that's happening but it might be related.
> 
> There should be no issues using the Vim extension with the Dart one, however there may be some performance issues in doing so if not using the LSP preview mode (the `dart.previewLsp` setting). Does the issue only occur when Vim is enabled?

It seems to be caused by this plugin

https://marketplace.visualstudio.com/items?itemName=softwaredotcom.swdc-vscode

**Comment by d1y** [comment]
https://github.com/swdotcom/swdc-vscode

I don't quite understand why using this plugin causes this problem

**Comment by DanTup** [comment]
It looks like there is an issue with that extension that's crashing the extension host (which will prevent other extensions from working too):

https://github.com/swdotcom/swdc-vscode/issues/113

I don't think there's anything we can do here - there's only one extension host for all extensions, so if any extension causes it to crash, it will prevent our extension from working. I would make sure you're on the latest version and if so, post any relevant info in their tracker to try and help them track it down.

I hope it gets fixed soon!
