### ISSUE TITLE
Stopping debugging sessions clears alarm manager

### ISSUE THREAD

**Issue by jaripekkala** [Dart-Code/Dart-Code#2760]
Steps to reproduce:
- Start debugging flutter app via vscode plugin on Android in the app
- Schedule some alarms using [AlarmManager](https://developer.android.com/reference/android/app/AlarmManager)
- Confirm alarms are scheduled via `adb shell dumpsys alarm`
- Stop debugging in vscode
-> All scheduled alarms are cancelled. Can be confirmed via the `adb` command or waited until they should be raised.

Note: this is only happening when debugging the app via vscode. Running `flutter run` and stopping the session does NOT cancel the alarms.

**Comment by DanTup** [comment]
I'm not very familiar with AlarmManager, but I had a go at reproducing this following the steps on the AlarmManager package readme, and the alarm still seems to show up in the adb results after stopping a debug session:

<img width="975" alt="Screenshot 2020-09-01 at 11 35 20" src="https://user-images.githubusercontent.com/1078012/91839596-3c7ed680-ec47-11ea-90f6-a33f29f3f399.png">

It only disappeared when I uninstalled the app from the device. Can you provide an example app and exact steps?

**Comment by jaripekkala** [comment]
Example app https://github.com/jaripekkala/alarm_test

The solution is to upgrade flutter version. I don't know in detail why.

1.17.5 is not working (always reproducible)
1.20.3 is working

**Comment by DanTup** [comment]
Great, glad it's sorted in the latest version!
