### ISSUE TITLE
Sort members command deletes comment from import

### ISSUE THREAD

**Issue by gkrawiec** [Dart-Code/Dart-Code#2762]
On a .dart file, the comments to the right of an import get deleted when running the sort members command. 

this is the minimal file with which I was able to reproduce it.
```
import '../a.dart'; //test
import '../b.dart';
```
after I run the `Sort Members` command the comment `//test` gets deleted.

If I only have a single import directive, the comment does NOT disappear. Only happens with 2 or more imports.

```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-US)
 [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc4)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.48.2)
```

Let me know if you need any other info.
thanks.

**Comment by DanTup** [comment]
Thanks for the report! I think this is the same as https://github.com/dart-lang/sdk/issues/42515 but Sort Members and Organize Imports have their own code paths so they need to be consolidated so Sort Members also gets this fix.

**Comment by DanTup** [comment]
Got a fix in progress at https://dart-review.googlesource.com/c/sdk/+/161786/.

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/d3b0979b04f594f93ad49990e51d06314c6ab816. You won't see the fix until you're on an updated SDK that includes that change.
