### ISSUE TITLE
stuck syncing files to device

### ISSUE THREAD

**Issue by gksrb4** [Dart-Code/Dart-Code#2765]
```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.64, on Mac OS X 10.15.6 19G2021, locale ko-KR)
    • Flutter version 1.22.0-10.0.pre.64 at /Users/*/Library/flutter
    • Framework revision 3c9315f9a5 (3 hours ago), 2020-09-02 18:58:34 -0700
    • Engine revision 165abef0a2
    • Dart version 2.10.0 (build 2.10.0-77.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/*/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • SM G950N (mobile) • ce12160cc318c81205                       • android-arm64 • Android 9 (API 28)
    • Dev10 (mobile)    • 7112f7ed6848fa22cc84f0d5688073fb14f849ff • ios           • iOS 13.6.1

• No issues found!
```

I have developed ios/android flutter app. 
But, I have a trouble with debugging my app. 
To connect debug my device, I spend almost 5 minutes. because It stuck in process of "syncing files to device" or "performing hot reload " in many times.
 
so, I checked [#49185](https://github.com/flutter/flutter/issues/49185#issue-552592088) and then changed flutter channel from stable to master.
But, It doesn't work. how can I improve my development environment.

**Comment by DanTup** [comment]
Can you describe exactly the steps you're taking and the behaviour you're seeing?

Does it happen if you create a new project with **Flutter: New Project**? Does it happen when you use the iOS Simulator, Android Emulators and physical devices, or only one of them?

**Comment by gksrb4** [comment]
I have confused it is stuck or it just takes long time. 
syncing files to device (ios device) process passed fast in normal. but sometime too long or stuck.

I have frequently experienced this problem in vscode run debug with 'F5'. but I never experience with `flutter run --debug -v` in terminal.

So, It is helpful to get logs in vscode debug process.

**Comment by DanTup** [comment]
You can use the [**Dart: Capture Logs** command ](https://dartcode.org/docs/logging/#capture-logs-command) to collect logs. For this, you'd want to *untick* **Analysis Server** but *leave everything else ticked* and click OK. This will capture all logs in verbose mode. After reproducing the issue (leaving it on "Syncing files to device" for at least a few minutes), click **Cancel** on the logging notification, and that will open the log file. Hopefully the last few lines may show some indication of what is taking so long.

**Comment by gksrb4** [comment]
`
[   +2 ms] Updating assets
[ +209 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[  +14 ms] Scanning asset files
[   +3 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +1 ms] <- recompile package:TEST/main.dart a10c0db5-edba-4310-9a5a-1a343c2a9ef9
[        ] <- a10c0db5-edba-4310-9a5a-1a343c2a9ef9
[ +130 ms] Updating files
[+238747 ms] Error writing "build/flutter_assets/packages/font_awesome_flutter/lib/fonts/fa-solid-900.ttf" to DevFS: HttpException: , uri = http://localhost:54165
[        ] trying again in a few - 9 more attempts left
[ +532 ms] DevFS: Sync finished
[   +1 ms] Synced 2.1MB.
[   +1 ms] <- accept
[   +3 ms] Connected to _flutterView/0x10a839420.
Connecting to VM Service at ws://localhost:54165/ws
[+1029 ms] flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
`

here is full log file.
[flutter-error-log.log](https://github.com/Dart-Code/Dart-Code/files/5198786/flutter-error-log.log)

**Comment by DanTup** [comment]
Thanks for the log! There's an open issue in Flutter that seems to describe the same behaviour here:

https://github.com/flutter/flutter/issues/65402

There's a suggestion it may be a flaky connection so if you can, I would try a different USB port and/or cable to see if that helps at all.

I'll close this issue in favour of that one, as if there is a bug, it's likely in the upstream tools rather than the VS Code extension. Thanks!

**Comment by xhp281** [comment]
I also encountered this problem. I tried to replace the USB data cable, and the same thing happened after replacing the data cable

**Comment by gksrb4** [comment]
If you use a USB hub, try connecting directly.

**Comment by xhp281** [comment]
> 如果您使用USB集线器，请尝试直接连接。

The effect is the same

**Comment by DanTup** [comment]
There's an open issue about launching on iOS stalling for exactly 4 minutes sometimes:

https://github.com/flutter/flutter/issues/65402

It's possible this may be what some of you are seeing?

**Comment by DanTup** [comment]
Is it really stuck, or does it just stall for 4 minutes? The issue linked above has been coming up more lately (https://github.com/flutter/flutter/issues/65402) so could you be seeing the same thing?

**Comment by gksrb4** [comment]
I have reopened the issue to [fluttercommunity/font_awesome_flutter](https://github.com/fluttercommunity/font_awesome_flutter/issues/120#issuecomment-693741221).
