### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Stanely254** [Dart-Code/Dart-Code#2769]
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `3.14.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.48.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\user\Dart-Code.dart-code-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by DanTup** [comment]
> ⚠️ Make sure to attach this file from your home-directory:
> ⚠️C:\Users\user\Dart-Code.dart-code-unresponsive.cpuprofile.txt

Are you able to attach the referenced file? Thanks!

**Comment by dikatok** [comment]
@DanTup I encountered the performance issue as well with or without LSP, even happens when I am typing code in a large project. It diverts me to use Android Studio temporarily, which I hate so much.

When I checked the analyzer log, there does not seem to be anything special/suspicious. Should I email you the log anyway with additional screen captures? What necessary information do you need?

**Comment by DanTup** [comment]
@dikatok do you mean you're seeing the same high CPU load message with LSP enabled, or something else like stuttering while typing? I wouldn't expect either in LSP mode - did you reload VS Code after enabling it? (we can't cleanly switch in/out of LSP mode without a reload currently).

**Comment by dikatok** [comment]
@DanTup Frankly, it's more about stuttering while typing, but it is usually accompanied by CPU spike as well. And yes, even in LSP (with bunch of restarts). It have only been happening around the past 2 weeks or so, though reinstalling the previous version or insider version (with the same extensions and settings) also produce the same behavior.

**Comment by DanTup** [comment]
@dikatok I think that may be a different issue to what's being reported here (which is VS Code showing a warning abut high CPU) so could you file a new issue? Please include a full list of your installed extensions and the exact version of the Dart/Flutter SDK and Dart extension. Thanks!

**Comment by DanTup** [comment]
Closing this as without the file mentioned above it can't be progressed. Please file new issues if you believe you're having similar issues and include full details. Thanks!
