### ISSUE TITLE
No "Show Fixes" anymore in VSC

### ISSUE THREAD

**Issue by johngithubby** [Dart-Code/Dart-Code#2770]
The "Show Fixes" popup light bulb button is not shown anymore, at all. In a new project, clicking on class name brings it up, and command-. brings up the menu popup ("wrap with widget", etc), but in the existing project I'm working on, nothing. I think this started happening after updating to the latest dart plugin, v3.14.0

[✓] Flutter: is fully installed. (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-CA)
[✓] VS Code: is fully installed. (version 1.48.2)

**Comment by DanTup** [comment]
Did you manage to track down what was causing this? It might be helpful to post here in case others see the same issue and come searching. Thanks!
