### ISSUE TITLE
How to cancel automatic formatting?

### ISSUE THREAD

**Issue by d1y** [Dart-Code/Dart-Code#2771]
This format makes me very uncomfortable. I used to write 'JS'. I'm not used to adding', ', but if I don't add it, it will become this format

![image.png](https://i.loli.net/2020/09/05/EyXeKDaU5hVfoFc.png)

If you do not automatically format? I'm very worried about this problem. If you don't add ',', the code after automatic formatting looks ugly, which makes me very uncomfortable!

I didn't find the relevant settings in the settings. Please let me know. Thank you

**Comment by DanTup** [comment]
The setting to completely disable the formatter is [`dart.enableSdkFormatter`](https://github.com/Dart-Code/Dart-Code/blob/b07c1d3602566c6f15c1c3b1b62e962ddc1daf1b/package.json#L1116), though can also just disable it running automatically on save/type/paste if you prefer (using VS Code's own settings) that would still allow you to run it manually if you wish.

Let me know if you have any issues making these work!
