### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException

### ISSUE THREAD

**Issue by iamaboyeji** [Dart-Code/Dart-Code#2772]
Issue Type: <b>Bug</b>

I tried to debug my app in flutter and then Gradle task assemble debug takes long, then throws this error, 

before now i have also faced gradle wrapper issues but i have solved them and i have successfully been debugging my apps on my emulator, but then this is showing up now.

Below is the full report;

Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: C:\Users\USER\.gradle\wrapper\dists\gradle-5.6.2-all\9st6wgf78h16so49nn74lgtbb\gradle-5.6.2-all.zip
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:61)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: C:\Users\USER\.gradle\wrapper\dists\gradle-5.6.2-all\9st6wgf78h16so49nn74lgtbb\gradle-5.6.2-all.zip
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:61)
	at org.gradle.wrapper.Install.createDist(Install.java:48)

Extension version: 3.14.0
VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

![gradle new issue](https://user-images.githubusercontent.com/65618547/92305032-46704480-ef7b-11ea-93ac-f1edacfb1ecf.jpg)

@DanTup @kevmoo @domesticmouse @343max @ikhwanhayat @stuartmorgan @ikhwanhayat @rkirsling @timsneath

**Comment by hani77979** [comment]
H

**Comment by iamaboyeji** [comment]
> H

is that a solution :), pls i don't understand.

**Comment by stuartmorgan** [comment]
Do not randomly spam people when filing bugs.

**Comment by DanTup** [comment]
There are some things you could try listed here:

https://stackoverflow.com/questions/59316518/gradle-task-assembledebug-failed-with-exit-code-1-runtime-exception

There are also some comments in https://github.com/flutter/flutter/issues/62465 and https://github.com/flutter/flutter/issues/45037 that suggest a slow connection can cause this error. One option could be to [download the file manually](https://stackoverflow.com/a/59625885/25124) and extract it to the right location.

**Comment by iamaboyeji** [comment]
> There are some things you could try listed here:
> 
> https://stackoverflow.com/questions/59316518/gradle-task-assembledebug-failed-with-exit-code-1-runtime-exception
> 
> There are also some comments in [flutter/flutter#62465](https://github.com/flutter/flutter/issues/62465) and [flutter/flutter#45037](https://github.com/flutter/flutter/issues/45037) that suggest a slow connection can cause this error. One option could be to [download the file manually](https://stackoverflow.com/a/59625885/25124) and extract it to the right location.

@DanTup I think it was my internet connection sir, I have tried it again with a good internet connection and it is working fine only that it would take almost forever for gradle assemble debug task to finish, I should close the issue now, but I usually have this same issue most time so hopefully I would not open up another on this same topic.
Thanks @DanTup

**Comment by iamaboyeji** [comment]
> Do not randomly spam people when filing bugs.

sorry, @stuartmorgan if that wasn't right, I needed help.
thank you.

**Comment by DanTup** [comment]
Glad to hear it's working!

It's fine to open issues if you have a problem, but mentioning a lot of random people is not helpful. The issue trackers are all triaged and new issues will be picked up and assigned as appropriate. Adding more notifications to everyones inboxes is only going to slow them down as they try to sort out the ones that are actually relevant to them (and not already being dealt with by others). You also included some *users* of Dart-Code who have simply contributed to the project in the past and do not generally work on the project.

Please don't be put off raising issues in future, but do so sensibly and mindful of others workloads. You may also wish to search the issue tracker and/or StackOverflow first, as often you can find the answers immediately.

Thanks!

**Comment by kanadouglas123** [comment]
we need a solution then ur givings nothing
