### ISSUE TITLE
Dart Analysis - Opening ignored file in editor shows errors/warnings/infos in Problems pane

### ISSUE THREAD

**Issue by samandmoore** [Dart-Code/Dart-Code#2779]
Hi again, thanks for all your hard work on this plug-in ❤️ 

I'm back to report some unexpected behavior with dart analysis in the "Problems" pane.

**Issue**
Analysis-ignored files are appearing in dart analysis problems list when an analysis-ignored file is opened in the editor.

**Expected behavior**
Analysis-ignored files never appear in dart analysis problems list.

**Steps to reproduce**
1. Given an `analysis_options.yaml` file like this:

```yaml
analyzer:
  exclude:
    - "**/*.g.dart"
```

2. Create a file `lib/something.g.dart` and add a violation, for example:

```dart
class SOMETHING {}
```

3. Reload the window.

4. See that the issue does not appear in the analysis problems list.

5. Open `lib/something.g.dart`.

6. See that the issue appears in the analysis problems list.

---

```
$ flutter --version
Flutter 1.20.2 • channel unknown • unknown source
Framework • revision bbfbf1770c (4 weeks ago) • 2020-08-13 08:33:09 -0700
Engine • revision 9d5b21729f
Tools • Dart 2.9.1
```

Dart-Code 3.14.1
Issue appears with LSP and without it

Thank you, let me know if I can provide any other details.

**Comment by DanTup** [comment]
I've recently fixed this (I believe) in https://github.com/dart-lang/sdk/commit/0aed132f4d73503dad79c6f491a993ffe58fd20c, however that change isn't in Dart v2.9 so you don't have it yet.

If you still see this after the next Flutter stable release (or on another channel that already includes a v2.10 Dart SDK), let me know and I'll do some more digging. Thanks!

**Comment by samandmoore** [comment]
Ah great. Thanks!
