### ISSUE TITLE
<evalError>:<collected> on inspecting Map

### ISSUE THREAD

**Issue by ajain-bst** [Dart-Code/Dart-Code#2780]
I just upgraded to Flutter v20 and tried using the new support for `inspect` to print my network call logs.

Sometimes it does work and I can see the inspected Map:
<img width="217" alt="Example of when it works" src="https://user-images.githubusercontent.com/37684378/92493688-6f5e3700-f212-11ea-9b1f-c5409c343eee.png">

But sometimes I see the following printed to the console:
<img width="169" alt="Example of when it does not work" src="https://user-images.githubusercontent.com/37684378/92493797-8ef55f80-f212-11ea-8abb-b727d319a312.png">

Any idea why this is happening?

**Comment by DanTup** [comment]
My guess is that the variable has been garbage-collected prior to you expanding it. Calling `inspect()` won't prevent an object from being collected, and the expansion in the debug console is done lazily. If the variable went out of scope and got collected, there's no way to show its data.

As a workaround if you want to inspect variables that would usually be collected, you could (temporarily) add them to a top-level/static `List` or something (though be sure not to leave that in non-debug code!).

If you can reproduce this on something that you don't think should've been collected, please provide a code sample and I'll try to reproduce. Thanks!

**Comment by ajain-bst** [comment]
Understood! Thanks for the quick response @DanTup  :)
Closing this.

**Comment by amalmohann** [comment]
If you've declared the variable locally inside any block, try to change it to a higher scope. 
I've declared the variable along with other class members and now the issue is gone.
