### ISSUE TITLE
Reduce reliance on variables passed to debug adapters

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#2783]
There are many variables passed into the `launchRequest` like `dartVersion` and `flutterVersion` that are only supplied by VS Code. In order to make the Debug Adapter more reusable, these things should be computed inside the debug adapter. All variables should also have sensible defaults.

**Comment by DanTup** [comment]
@ericdallo FYI - as part of this work, I'm removing `dartPath`, `flutterPath`, `pubSnapshotPath`, `dartVersion`, `flutterVersion` from the launch arguments for the debug adapter, and replacing them with just `dartSdkPath` and `flutterSdkPath`. You're currently setting some of these [here](https://github.com/emacs-lsp/lsp-dart/blob/51d3495846aea706f808e151af066ae918aaefb2/lsp-dart-dap.el#L145-L163).

When most of these were added, VS Code was the only consumer so it was convenient to just pass them in. However, it's made using the debug adapter more complicated when many of the values could be computed by the debug adapter. This should simplify things a little (I'm also reviewing the defaults and making sure most of the values are entirely optional).

(Note: Use of this debug adapter by non-VS Code clients isn't "officially" supported, though I would like to ensure it works and is not too burdensome! 🙂).

**Comment by ericdallo** [comment]
Thank you very much @DanTup, I totally agree!
I''ll update `lsp-dart` and remove the unnecessary variables :)

**Comment by ericdallo** [comment]
Sorry for the delay, I just bumped `lsp-dart` to use `Dart-Code` debugger extension `3.17.0` removing the unused variables replaced by `dartSdkPath` and `flutterSdkPath`, thank you!
https://github.com/emacs-lsp/lsp-dart/commit/a2c30213326cbac11d805e94c770eec76d0e3624
