### ISSUE TITLE
Dart Intellisense/ Autocomplete not working in VS Code.

### ISSUE THREAD

**Issue by Hritvik3** [Dart-Code/Dart-Code#2787]
- Issue Type: `Bug`
- Extension Name: `dart-code`
- Extension Version: `3.14.1`
- OS Version: `Windows_NT x64 10.0.14393`
- VSCode version: `1.49.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by DanTup** [comment]
> ⚠️ We have written the needed data into your clipboard. Please paste! ⚠️

Are you able to paste this data or provide more information on exactly what you're seeing? Thanks!

**Comment by Hritvik3** [comment]
> > ⚠️ We have written the needed data into your clipboard. Please paste! ⚠️
> 
> Are you able to paste this data or provide more information on exactly what you're seeing? Thanks!


Hello sir, I've started out with Flutter development recently on VS code. The problem is the intellisense of Dart extension stops. When I checked the running extensions, it again and again shows Dart extension stopped unexpectedly. 
I reinstalled the extensions, disabled and enabled all the extensions still the problem is not solved.

**Comment by DanTup** [comment]
> it again and again shows Dart extension stopped unexpectedly

Can you provide a screenshot of the exact message that you're seeing?

**Comment by DanTup** [comment]
Please let me know still seeing this and able to provide more info, and we can re-open this. Thanks!

**Comment by Hritvik3** [comment]
> Please let me know still seeing this and able to provide more info, and we can re-open this. Thanks!

Yes sir sorry for late reply. I'll share the screenshots by today evening. I tried some fixes from your comments on similar questions. It now shows autocomplete but it takes like 10 12 seconds.

**Comment by DanTup** [comment]
@Hritvik3 that sounds like a different issue to originally described and may be the same issue described in https://github.com/Dart-Code/Dart-Code/issues/2865. I've added some things to try at https://github.com/Dart-Code/Dart-Code/issues/2865#issuecomment-709371833. If you're still seeing the issue after trying them, please post on that issue. Thanks!

**Comment by VinayGhadigaonkar** [comment]
sir I have facing same problem not intellisese not working please help me .

**Comment by DanTup** [comment]
Please file a new issue with specific details about the issue you're having. Thanks!

**Comment by makayasa** [comment]
the snippet is completly messed up. I usually use control + space on itemBuilder / separatorBuilder to get the snippet. But It only works when i move the builder parameter on the very top (same as separator builder). And I cant use function snippet to create function

<img width="690" alt="Screen Shot 2022-06-08 at 23 31 03" src="https://user-images.githubusercontent.com/52215902/172669383-6439db59-a8a4-43a1-9567-1ced2a8ecad9.png">
<img width="690" alt="Screen Shot 2022-06-08 at 23 31 13" src="https://user-images.githubusercontent.com/52215902/172669386-c3e0f73c-8549-48fb-a7c7-7f2b706b4284.png">
<img width="690" alt="Screen Shot 2022-06-08 at 23 31 24" src="https://user-images.githubusercontent.com/52215902/172669388-3124c3c4-2a1c-4b20-97f2-1cf966d2d90f.png">

<img width="690" alt="Screen Shot 2022-06-08 at 23 30 53" src="https://user-images.githubusercontent.com/52215902/172669358-6b46f886-5437-4ff9-852c-dee2c5aab04e.png">

**Comment by DanTup** [comment]
@makayasa please file a new issue with the details above, along with the output of `flutter doctor -v`. Thanks!
