### ISSUE TITLE
Javascript style dot notation for parsing JSON

### ISSUE THREAD

**Issue by sbairi2421** [Dart-Code/Dart-Code#2788]
Is there an automated way of marshalling a JSON to a built-in dart object so that a Javascript like dot notation can be used? For example, here's an example is w3schools for javascript json parsing:
myObj = {
  "name":"John",
  "age":30,
  "cars": {
    "car1":"Ford",
    "car2":"BMW",
    "car3":"Fiat"
  }
 }

x = myObj.cars.car2;
// or:
x = myObj.cars["car2"];

Its easy to refer to the car2 from the marshalled myObj. 

Since I'm new to dart, I'm not sure if this feature is in the language or not.

**Comment by DanTup** [comment]
I don't think there's anything built-in to the object that would allow you to access a `Map<String, dynamic>` that way. However there are some JSON deserialisation/codegen libraries that would allow you to generate classes to deserialise the JSON into (or to wrap) that would provide strongly-typed access.

You can find some more information on some of the popular choices on the Flutter website here:

https://flutter.dev/docs/development/data-and-backend/json

Here isn't the right place for help choosing one/using them (this issue tracker is for the VS Code extension), but there are many other places (Reddit, StackOverflow, Gitter) that have active Flutter users that probably have opinions and more experience with them than I do.

Hope this helps!

**Comment by sbairi2421** [comment]
Thanks Dan.
