### ISSUE TITLE
Stack traces in test errors are not linkified

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#2794]
See https://github.com/Dart-Code/Dart-Code/issues/2099#issuecomment-692387484

![Screenshot 2020-09-15 at 10 20 16](https://user-images.githubusercontent.com/71999/93150849-9601fd80-f73d-11ea-88c6-3d14c29ce2c8.png)

**Comment by DanTup** [comment]
With this and #2795 fixed, it now looks like this:

![Screenshot 2020-09-15 at 10 28 01](https://user-images.githubusercontent.com/1078012/93192985-35bf8b80-f73e-11ea-8a50-3839cfdccfaa.png)

We can't currently map `dart:async` anywhere so it remains in the message on the left (we can't attach a link that would appear on the right), but I think it's an improvement (ignoring the not-so-friendly async stack traces, but that's not something we can improve in the extension).

**Comment by maks** [comment]
That's awesome @DanTup - thank you for fixing this so quickly! 👍

**Comment by maks** [comment]
@DanTup I installed the v3.15 beta vsix, both reloaded and then restarted vsc for good measure but when running tests I still don't seem to see the test failure relative stack traces being linked?
 
![Screenshot 2020-09-28 at 10 05 53](https://user-images.githubusercontent.com/71999/94379263-8093c700-0172-11eb-8463-847f504fb062.png)

**Comment by DanTup** [comment]
@maks oh, that's a different place again. In [the original screenshot](https://github.com/Dart-Code/Dart-Code/issues/2099#issuecomment-692387484) it was the Debug Console (which we parse the output for and attach location metadata). The other one was the Terminal (where we now detect package: links with a regex, and VS Code does the path links). This one is the Output Pane (which we show if you click back on a test node in the tree). As far as I know, there's no way for us to provide links there (though I think in theory the link provider code would work there if we had a hook - @Tyriar does that seem like a useful feature request?).

I wonder if we could switch to using a pseudo terminal for those results now instead of an Output pane. That would probably get VS Code's normal linking (which I presume includes relative paths) as well as our link provider (for `package:` paths). I've opened https://github.com/Dart-Code/Dart-Code/issues/2825 to have a look at that.

**Comment by Tyriar** [comment]
There's been some talk of sharing terminal link logic with the output panel: https://github.com/microsoft/vscode/issues/107314, https://github.com/microsoft/vscode/issues/53922
