### ISSUE TITLE
Code completion is missing some items

### ISSUE THREAD

**Issue by darkstarx** [Dart-Code/Dart-Code#2797]
![image](https://user-images.githubusercontent.com/3534966/93205014-c35fa300-f75f-11ea-935d-24706e6bf3b4.png)

If I remove the line
`await _pidFile.lock();
`
then code completion works fine.
![image](https://user-images.githubusercontent.com/3534966/93205550-a9729000-f760-11ea-9985-fc64a050f700.png)

So, when I try to insert code between two lines with a reference to the same object, I get the code completion for this object not working.

**Comment by DanTup** [comment]
Could you confirm the versions of:

- VS Code
- Dart extension
- Dart/Flutter SDK
- Whether you have the `dart.previewLsp` setting enabled

Thanks!

**Comment by darkstarx** [comment]
VS Code
```
Version: 1.49.0
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:20:50.359Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.3.0-64-generic
```
Dart `Dart SDK version: 2.9.3 (stable) (Unknown timestamp) on "linux_x64"`
Dart extension `v3.14.1`
Dart extension settings:
```
    "[dart]": {
        "editor.rulers": [
            80
        ],
        "editor.tabSize": 2,
        "editor.insertSpaces": true,
        "editor.detectIndentation": false,
        "editor.suggest.insertMode": "replace"
    }
```
`dart.previewLsp` in settings.json not exists, the setting (by Ctrl+,) is not marked (is switched off).

**Comment by DanTup** [comment]
I was able to reproduce using the following code:

```dart
Future<void> main() async {
  final myString = '';

  myFile. // Complete here

  print(myString);
}
```

However it only works with `previewLsp: true`, it seems fine when LSP is off:

<img width="841" alt="Screenshot 2020-09-16 at 14 20 09" src="https://user-images.githubusercontent.com/1078012/93342856-bc9c6300-f827-11ea-8f21-83efde625e86.png">

Could you test with this code and see whether you can reproduce with LSP disabled? If so, can you capture a log:

- Run the **Dart: Capture Logs** command from the VS Code command palette
- Untick everything except **Analysis Server** and click OK
- Press Ctrl+Space to force completion open at that location
- Click **Cancel** on the logging notification to stop logging and open the log
- Attach the log here

I'll look into why it doesn't work for LSP- but if you're seeing it without LSP there may be another issue too.

**Comment by DanTup** [comment]
The LSP issue I can only repro using v2.9.3 but it's fine in the latest nightly build - so I think this issue may have already been fixed. If you're still able to reliably reproduce the issue without LSP, can you confirm if it still occurs using a more recent build (for example a dev release from https://dart.dev/tools/sdk/archive#dev-channel)?

Thanks!

**Comment by DanTup** [comment]
Let me know if you can still repro this in latest stable Dart or Flutter (my sample above does not) and we can re-open this. Thanks!
