### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by amanpreeto7** [Dart-Code/Dart-Code#2799]
- Issue Type: `Bug`
- Extension Name: `dart-code`
- Extension Version: `3.14.1`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.49.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by DanTup** [comment]
> ⚠️ We have written the needed data into your clipboard. Please paste! ⚠️

Can you provide some more information about the problem, or the data from the clipboard? Thanks!
