### ISSUE TITLE
Ability to collapse commented code chunks with gutter toggle

### ISSUE THREAD

**Issue by enzotar** [Dart-Code/Dart-Code#2800]
**Is your feature request related to a problem? Please describe.**
When refactoring code, I often comment out large sections. This makes for a lot of scrolling to see the working code.

**Describe the solution you'd like**
Similar to how classes and functions have a collapse toggle in the gutter, I would like to collapse blocks of commented code.

**Describe alternatives you've considered**
I sometimes leave the function or class and only comment the content. But sometimes that is not convenient.

**Additional context**
The first line of the commented block could be used as the summary of the collapsed chunk. And with some visual feedback to show the collapse/more lines available

**Comment by DanTup** [comment]
This was implemented in the language server in https://github.com/dart-lang/sdk/commit/b94adb2bc2d53897a727e3ae1dcdf10c74948659. It will automatically show up in VS Code after the next Dart/Flutter SDK releases.
