### ISSUE TITLE
iPhone frequently does not show in VS code unless I restart it

### ISSUE THREAD

**Issue by johanlantz** [Dart-Code/Dart-Code#2802]
**Describe the bug**
There has been at least one other bug on this topic previously so please let me know if this should be posted somewhere else. I am unsure which plugin is responsible for what.

The behaviour is consistent, most of the time if I connect my iPhone when VS Code is open, it does not show up unless I restart VS code (Android devices are always fine). The behaviour is the same with different iPhones and the same thing happens for my colleague on a different computer (both Macbooks).

flutter devices always see the device and so does xCode. Restarting VS Code always works, after restart the iPhone is shown.

**To Reproduce**
Running flutter doctor from the command palette also sees the device.
´´´
[flutter] flutter doctor -v
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.4 19E266, locale en-GB)
    • Flutter version 1.17.4 at /Users/yc00025/flutter
    • Framework revision 1ad9baa8b9 (3 months ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/yc00025/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/yc00025/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • iPhone • xxxx • ios • iOS 13.5.1

! Doctor found issues in 1 category.
exit code 0
´´´

**Versions (please complete the following information):**
 - VS Code version: Version: 1.49.0
 - Dart extension version: 3.14.1
Dart VM version: 2.3.1 (Tue May 21 19:28:38 2019 +0200) on "macos_x64"
Flutter 1.17.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1ad9baa8b9 (3 months ago) • 2020-06-17 14:41:16 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4

**Comment by DanTup** [comment]
This sounds like https://github.com/Dart-Code/Dart-Code/issues/2659 / https://github.com/flutter/flutter/issues/62100. The fix seems to be in Flutter v1.20 but you're still on v1.17. I think if you upgrade the issue should go away.

If not, please let me know!
