### ISSUE TITLE
Hot reload button missing when running from Flutter master channel

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#2803]
The `reloadSources` service doesn't seem to be being registered. Is it be related to DDS changes?

**Comment by sma** [comment]
I just noticed that hot reload vanished for iOS, Android and macOS. For web, the yellow lightning arrow for hot restart is still displayed and still works.

**Comment by DanTup** [comment]
Closing this as a dupe of #2775, as I'm now fairly sure they're all the same. It seems like DDS may have been enabled/disabled a few times, which explains why it may have gone away and then just come back when https://github.com/dart-lang/sdk/commit/c3da025eaa2affb44c2912808ebdb105668d9aed landed.

**Comment by DanTup** [comment]
> For web, the yellow lightning arrow for hot restart is still displayed and still works.

Thanks for the note - this seems to match up with it being DDS, as that's not enabled for web yet.
