### ISSUE TITLE
LSP Preview: forEach not autocompleting fully

### ISSUE THREAD

**Issue by Merrit** [Dart-Code/Dart-Code#2804]
**Describe the bug**
With the LSP Preview enabled:
When selecting the autcomplete for `.forEach` it completes the `forEach` part but not brackets, braces or value.

**To Reproduce**
1. Create a list: `List a = [];`
2. `a.forE` ...
3. Select the `forEach` autcomplete from the popup

**Expected behavior**
Expect completion as: `a.forEach((element) { })`

**Actual behavior**
Completion instead is: `a.forEach`

**Versions (please complete the following information):**
 - VS Code version: 1.48.0
 - Dart extension version: 3.14.1
 - Dart/Flutter SDK version: Dart 2.10.0 / Flutter 1.22.0-12.0.pre • channel dev

I am unsure if this affects other autocomplete options as well, I will keep my eye out and update if I see others.

**Comment by Merrit** [comment]
When creating a test the `expect` does the same.

Should be:
`expect(actual, matcher)`

Is:
`expect`

**Comment by DanTup** [comment]
Thanks for the report - merging this into #2823.
