### ISSUE TITLE
Automatic import of extension methods

### ISSUE THREAD

**Issue by marko** [Dart-Code/Dart-Code#2806]
Whenever I want to use an extension method I have to look up the file path and import it manually. It would be great if there was a way to import them automatically as a Quick Fix.

**Comment by DanTup** [comment]
Thanks for the suggestion! There's an open issue tracking this in the SDK (the completion is handled by the language server):

https://github.com/dart-lang/sdk/issues/38894

In the meantime, if your extension method has a name, you can type that to trigger the auto-import and then use it (see https://github.com/dart-lang/sdk/issues/38894#issuecomment-668099928).

**Comment by marko** [comment]
I guess I'll just have to subscribe to that issue. Thanks for the workaround!

**Comment by DanTup** [comment]
Closing this in favour of https://github.com/dart-lang/sdk/issues/38894. With LSP, all language functionality will come from the server so there's nothing to do here, it'll just show up once it's supported there.
