### ISSUE TITLE
Pausing debugger doesn't show a call stack or  I need a list of non-completed futures.

### ISSUE THREAD

**Issue by bsutton** [Dart-Code/Dart-Code#2810]
So I don't know if this is a feature request or a bug.

When running a flutter app I sometimes pause the debugger by clicking the 'pause' icon in the debug tool bar.

Often  when I pause the debugger it doesn't show a stack trace.

I suspect that in these cases I'm looking for a future which has not completed.

An example is I send an http request and set up a completer which will be marked as complete once the http request returns and the data has been processed.

The http requests returns an error causing an exception to be thrown.
The result is that (due to a bug in my code) the completer is never completed so my code hangs.

I managed to do this on a fairly regular basis :)

Seeing that my code appears to be hanging I then pause the debugger looking for the offending stack trace.
The debugger then shows no stack trace at all.

So there is a chance I'm asking for the wrong thing.

I suspect that when waiting for a future to complete there is actually no active stack or at least the stack is running in native code which doesn't show up in the debugger.

If my above assumptions are correct then I suspect that what I want to see is a list of non-complete futures with the line of code that created the future.
I suspect the no. of non-complete futures may be large so we may need some method to sort / search through them.

**Comment by DanTup** [comment]
I'm not sure why the stack is empty (maybe there's no real code running at the time?) though I'm not sure if it would help here - if your code has already thrown the exception, the stack will have been unwound.

I don't think futures capture the stack when they're created, so even with a list of incomplete futures (which I think would probably be quite large) I'm not sure you'd be able to tie them back to where they were created.

Is your exception not causing the debugger to break, or being printed anywhere? Seems like exceptions shouldn't be swallowed completely silently, but this also feels like something break-on-uncaught-exceptions should catch. I know it has some issues, but even if you generally run it it off, I think toggling it on to debug something would be the best option (it would break you right at the site of the exception, call stack intact). Is there a reason you can't use this or it doesn't work?

**Comment by bsutton** [comment]
The exception scenario was just intended as an example and yes I us the
break on exception option these type of errors.

There are lots of code paths that can end up with  a non-complete future.

I had a bit more of a think about what is going on and I suspect the
largest source of this sort of problems is possibly Completers that I've
failed to complete.

I've now gone and created a CompleterEx class that captures a stacktrace at
the point of creation and dumps the stacktrace if the completer doesn't
complete in 10 seconds.

This may be sufficient to diagnose this sort of problem (assuming its only
Completers that are the source).

If the source of the problem is with futures in general then I would agree
that there are likely to be large no.s of these active.

Let me play for a few days to see if a simple coding solution as above is a
reasonable solution.

**Comment by DanTup** [comment]
I actually have something similar in TS/node for Dart-Code 😄  It's a `watchPromise` function that takes a promise and a textual name, and prints information about its status (and prints after 60 seconds if it never completed, and stops watching).

I'm not sure there's much we can do in the VS Code extension to make things better if that doesn't help, so it may be better to start a discussion in one of the dart-lang repos. Let me know how it goes anyway!

**Comment by DanTup** [comment]
@bsutton any further thoughts on this?

**Comment by bsutton** [comment]
The wrapper I added around the completer solved my problem.

Given the complexity of adding this to the debugger and a viable coding solution I'm inclined to drop the idea.

It would be nice but I think there are other issues that are probably more important.

**Comment by DanTup** [comment]
Yeah, I agree it'd be nice to have *some* solution here - though it may need to come from the SDK (from the extension we can't provide a call stack if the VM doesn't give us one, nor track all the futures), so if it continues to be an issue it may be worth filing an issue in a dart-lang repo to start a discussion. Thanks!
