### ISSUE TITLE
Chrome/ Web device is not appearing

### ISSUE THREAD

**Issue by jamesblasco** [Dart-Code/Dart-Code#2812]
**Describe the bug**
When the extension lets you choose the device, chrome and web server don't appear anymore.
It still appears when running the command flutter devices.

Also we running `flutter run -d chrome` works as expected.

![image](https://user-images.githubusercontent.com/19904063/93860607-a119d800-fcbf-11ea-9eca-9d90de7c429c.png)
 
**Versions (please complete the following information):**
 - VS Code version:  1.49.1
 - Dart extension version: v3.14.1
 - Dart/Flutter SDK version: 1.22.0-12.1.pre

**Comment by DanTup** [comment]
Could you try enabling the [Flutter Daemon](https://dartcode.org/docs/logging/#flutter-daemon) log file, restart VS and reproduce the issue, then attach the log here? Thanks!

**Comment by jamesblasco** [comment]
I restarted my mac but not solved it, restarting later VS did,

I can't manage to reproduce the issue anymore

**Comment by DanTup** [comment]
If it comes back, please try to grab the log mentioned above and we can re-open this. Thanks!
