### ISSUE TITLE
windows7  + vscode 插件 flutter 3.14.1  遇到webview直接闪退. 切换到插件3.13.2旧版是好的

### ISSUE THREAD

**Issue by wellingtonjone** [Dart-Code/Dart-Code#2815]
**Describe the bug**
调试模式下，在webview绘制的页面，例如：有flutter_echarts图表页面。或者自己用webview引入h5页面。app闪退

**To Reproduce**
1. 调试模式启动
2. 其他页面正常，进入webview页面闪退

**Expected behavior**
启动app。进入有webview绘制的页面，app闪退debugger模式lost devices
将app安装在模拟器，真机上是可以展示的

**Screenshots**

**Versions (please complete the following information):**
 - VS Code version:  1.31.0
 - Dart extension version: 3.14.1
 - Dart/Flutter SDK version: 3.14.1

**Comment by DanTup** [comment]
If the Flutter app is crashing, then this should be raised at https://github.com/flutter/flutter/ (this issue tracker is only for the VS Code extension).

Please be sure to include the exact version of Flutter you're using, and some sample code that reproduces the problem. Thanks!
