### ISSUE TITLE
Renaming a symbol adds an extra dot in Dart doc comments, breaks link between symbol and reference

### ISSUE THREAD

**Issue by rmkl** [Dart-Code/Dart-Code#2816]
**Describe the bug**
Renaming a named constructor or a factory results in duplicating the dot in any doc comment that is referencing that symbol. It breaks the link between the symbol and the reference for any subsequent renaming.

**To Reproduce**
1. Create a new class SomeClass
2. Add a named constructor SomeClass.namedConstructor
3. Add a doc comment to the named constructor that includes a Dart doc reference [SomeClass.namedConstructor]
4. Right-click the name of the named constructor in the code
5. Select 'Rename Symbol' (F2)
6. Change the name to 'anotherName'
7. Notice how an extra dot is added to the reference in the doc comment [SomeClass..anotherName]
8. The link between the symbol and the reference is the doc comment is now lost.

- The steps to reproduce the issue for a factory are the same.
- Disabling all extensions, except the Dart extension, does not resolve the problem.

**Versions (please complete the following information):**
 - VS Code version: 1.49.1
 - Dart extension version: 3.14.1
 - Dart/Flutter SDK version: Flutter 1.21.0-9.2.pre • channel beta, Dart SDK version: 2.10.0-7.3.beta

**Comment by bwilkerson** [comment]
> The issue seems to be that the source range for a named constructor returned by `searchEngine.searchReferences` ... does not include the leading period.

That seems appropriate to me. If the search engine is being used to find references to the constructor those ranges will be the range to which the user will navigate, and it seems appropriate that it doesn't include the period.

> Do you know what the expectation is, and which bit is likely incorrect?

I believe that the search engine is correct and that it's the refactoring that needs to be updated.

> I could update rename_constructor to assume there's no dot ...

It isn't quite that simple, unfortunately, because of unnamed constructors. The rename refactoring allows users to rename a named constructor to a named constructor (both have a period so it should be left as is), a named constructor to an unnamed constructor (the period needs to be removed), or an unnamed constructor to a named constructor (the period needs to be added). It sounds like the bug is in the first case.

**Comment by DanTup** [comment]
Ah, good point. Though it does seem like there is some inconsistency in the search engine results. I updated my sample to this:

```dart
class SomeClass {
  /// Docs for [SomeClass.namedConstructor].
  SomeClass.namedConstructor(); // marker

  final instance = SomeClass.namedConstructor();
}
```

Here there are two references to the named constructor (one in the dartdoc, one in a call to the constructor for the `instance` field). When I rename `namedConstructor`, only the dartdoc is updated incorrectly to end up with two periods. If I examine the matches from the search engine, they have different lengths (the constructor call *does* include the period - see the expression eval results at the bottom - one length is 16, one is 17):

<img width="662" alt="Screenshot 2020-10-13 at 17 42 01" src="https://user-images.githubusercontent.com/1078012/95890412-aed0f380-0d7b-11eb-9834-fea6aefa1b35.png">

I don't know if this is expected - should the search engine results be different for these? (I wouldn't have thought so - though if they are, the fix in the refactor would need to account for this difference).

**Comment by bwilkerson** [comment]
I wouldn't have expected them to be different. That might be a bug in the indexer, but @scheglov might know better.

**Comment by DanTup** [comment]
@scheglov do you have any thoughts on the above? Thanks!

**Comment by scheglov** [comment]
Yes, this looks like a bug in the refactoring or the indexer, I can reproduce it in a unit test.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/181260

**Comment by DanTup** [comment]
@scheglov great, thanks!
