### ISSUE TITLE
Integration of Stagehand

### ISSUE THREAD

**Issue by abhi18av** [Dart-Code/Dart-Code#282]
Hey Dart-code team,

This is an awesome plugin!

Is there a way to initiate a new project from within the VsCode environment? If not, I would suggest that Stagehand would prove to be of great help :)

**Comment by DanTup** [comment]
Glad you like it! :-)

Unfortunately VS Code doesn't provide functionality for project templates:

> https://code.visualstudio.com/docs/setup/setup-overview
> **Q: How do I create and run a new project?**
> **A**: VS Code doesn't include a traditional File > New Project dialog or pre-installed project templates. You'll need to add additional components and scaffolders depending on your development interests. With scaffolding tools like Yeoman and the multitude of modules available through the NPM package manager, you're sure to find appropriate templates and tools to create your projects.

It's not something Dart Code can add (VS Code extensions are locked down to very specific APIs).

There is a terminal available inside VS Code however, which you could use to execute Stagehand.

That said, if this every changes and VS Code gets some API that would allow us to integrate this, I'd be happy to revisit this.

**Comment by DanTup** [comment]
I'd like to revisit this. I think we might be able to have a reasonable experience using commands in the command palette, though it might be that we need the extension loaded first (can we contribute commands that are always there and then load the extension?) and whether we can run stagehand to output into an existing folder (or have a good experience asking the user where to create it).
