### ISSUE TITLE
Closing labels are (but should not be) seen by the text editor in Android Studio

### ISSUE THREAD

**Issue by toysonlocation** [Dart-Code/Dart-Code#2820]
Dart closing labels in Android Studio are not ignored by the IDE, and the cursor will place itself after them, as in this screenshot...

![image](https://user-images.githubusercontent.com/39204807/94202424-9e6bde00-fe8b-11ea-8ba0-67b876f5b672.png)

Note the bar-cursor after the MaterialApp closing label. Once you start typing, it does a little jig where the type briefly appears where the caret is (after the closing label), and then the caret and text jump together to the "real" end of the line (before the closing label).

Here is a video of it misbehaving. Note the caret hanging out after the closing labels as down-arrow is pressed, and then how "f" and "g" jump from after the label to where they should be...

https://youtu.be/7fRM7g3R3M4

This is a visually annoying and distracting effect. Please make the editor ignore closing labels

Additionally, it would be nice to style the closing label, even if only the color.

**Comment by DanTup** [comment]
Thanks for the report, though this issue tracker is for the VS Code extension so this isn't fixable here.

@devoncarew where is the correct place for this issue? https://github.com/flutter/flutter-intellij/  or https://youtrack.jetbrains.com/issues/WEB?q=Subsystem:%20Dart?

**Comment by devoncarew** [comment]
Hi @toysonlocation - the closing label feature is provided by the Dart IntelliJ plugin. We're using a platform capability from IntelliJ called inline elements. I think you'll want to file a youtrack feature request against he IntelliJ platform for the editing / navigation improvements you're describing. Thanks!
