### ISSUE TITLE
dart formatter as prettier-plugin-dart

### ISSUE THREAD

**Issue by softmarshmallow** [Dart-Code/Dart-Code#2822]
https://prettier.io/docs/en/plugins.html

separating module only for formatting dart code as prettier-plugin-dart for re-usability and supporting dart formatting on node platfroms.

**Comment by DanTup** [comment]
The formatter used is written in Dart and available here:

https://github.com/dart-lang/dart_style

It currently runs in the Dart VM (within the language server) and isn't compiled to JavaScript. In theory I think that should be possible, but I don't know if anyone has done it.

It seems like a good idea (to allow other uses of prettifier to format Dart, outside of VS Code), but it's not something that really belongs in Dart-Code - which is specifically a VS Code extension for Dart, it feels like it would be its own project.

Hope this makes sense!

**Comment by softmarshmallow** [comment]
i found the official npm package, but not seems to work. https://github.com/dart-lang/dart_style/issues/956

**Comment by DanTup** [comment]
[That npm package](https://www.npmjs.com/package/dart_style) was last published 5 years ago, so I'm not sure it's being maintained (cc @jacob314).

It does suggest it may work compiled to JS though. It looks like the package was created [using the scripts here](https://github.com/dart-lang/dart_style/commit/fd89540f05a0d21b7767ebc3add9db15a7f22623) so you may be able to use the latest code to build a new package and that may work better.

btw, in the code in your linked issue there's a missing semicolon after `return null`. I think the formatter only works on valid code, so correcting that may also help.

**Comment by softmarshmallow** [comment]
@DanTup  that did the magic. thanks. -> was a syntax errr problem.

The package seems to work well, can your team publish the latest version to npm for the community?


``` ts
import { formatCode } from "dart-style"
const raw = "Widget tet(){ return null; }"
const code = formatCode(raw);
console.log(code)
```

> { code: 'Widget tet() {\n  return null;\n}\n' }

**Comment by DanTup** [comment]
Glad to hear!

I think the package may need to be updated by @jacob314 - I don't know who else has access to it (I'm not sure whether it's intended to be official and/or maintained though).

**Comment by DanTup** [comment]
(closing this as I don't think there's nothing to do here for the VS Code extension)
