### ISSUE TITLE
Move test result summary from Output pane to pseudo terminals

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#2825]
See https://github.com/Dart-Code/Dart-Code/issues/2794#issuecomment-699707509. The results are linkified in the Debug Console, but if you then click on the tests to see the results afterwards, they're in the Output pane where we can't add links.

We may be able to use a pseudo terminal instead.

**Comment by maks** [comment]
Thanks so much for following this up @DanTup , I'm sorry it's become such a whack a mole exercise! And yes my mistake,  I forgot I did click on the individual failed test  but I can see that the output in the debug console is correctly linkified so for me that makes this issue more of a "nice to have" as I just need to remember to look at test errors in the debug console.
