### ISSUE TITLE
Debugger output is laggy and janky when scrolling

### ISSUE THREAD

**Issue by acoutts** [Dart-Code/Dart-Code#2829]
**Describe the bug**
When scrolling up on fresh output in the debugging console while running a flutter app, it's very janky and doesn't scroll. After you've "viewed" it at least once then it scrolls up/down fine in the future.

This regression happened sometime recently after upgrading to 1.50.

**To Reproduce**
1. Run any flutter app.
2. Try to scroll on some output in the debugging area.

**Expected behavior**
Shouldn't jump around.

**Screenshots**
https://i.imgur.com/dpMBVl3.mp4

It's also adding lots of whitespace to the end of each line printed so you have to scroll up:
<img width="1270" alt="Screen Shot 2020-09-28 at 5 30 36 PM" src="https://user-images.githubusercontent.com/9597207/94488310-67aa0680-01b0-11eb-8681-6cce849b4197.png">

**Versions (please complete the following information):**
 - VS Code version:
```
Version: 1.50.0-insider
Commit: 772aa0723f7f6b04b710bc3a92b7a904b60ef439
Date: 2020-09-28T05:41:42.988Z (15 hrs ago)
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```
 - Dart extension version:
```
3.14.1
```
 - Dart/Flutter SDK version:
```
Flutter 1.22.0-12.2.pre • channel beta • git://github.com/flutter/flutter.git
Framework • revision 2bafdc8226 (3 days ago) • 2020-09-25 12:48:22 -0700
Engine • revision f763b5b9b9
Tools • Dart 2.10.0 (build 2.10.0-110.5.beta)
```

**Comment by DanTup** [comment]
Thanks for the report! This looks like a VS Code issue and should be raised at https://github.com/microsoft/vscode/issues. The extension debug adapter just sends the text back to VS Code and all rendering/scrolling/buffering is handled by it so there's nothing we can do to influence this behaviour here.

Please post a link back here once raised in VS Code so if others come across this issue they know where to subscribe. Thanks!

**Comment by acoutts** [comment]
Filed https://github.com/microsoft/vscode/issues/107704

**Comment by DanTup** [comment]
Thanks!
