### ISSUE TITLE
WSL: no analysis, syntax highlights & intellisense

### ISSUE THREAD

**Issue by jimmyff** [Dart-Code/Dart-Code#2830]
I'm sure this was working yesterday, however today I have no analysis, syntax highlight or intellisense when using WSL. It's as if the Dart code extension isn't installed.

Version: 1.49.1 (user setup)
Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
Date: 2020-09-16T23:27:51.792Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Using the WSL button at the bottom left and selected 'Remote-WSL: Reopen this folder in Windows' does make it work as expected again but then choosing 'Remote-WSL: Reopen this folder in WSL' reverts me back to no dart-code.

**Comment by DanTup** [comment]
Can you check the Extensions side bar once you're connected, and ensure that the Dart extension is listed as installed for the remote workspace?

If so, check Help -> Toggle Developer Tools to see if there are any errors reported (like "Failed to activate extension").

The syntax highlighting is all declarative (a textmate grammar), so I would expect that to work even if there are exceptions running the extension code, so it does seem consistent with the extension not being installed/loaded correctly.

**Comment by jimmyff** [comment]
Ah, I am so sorry for wasting your time @DanTup , I didn't realise that I needed to install the extensions on the WSL workspace. (I'm very new to Windows!) 

Thanks for your help.

**Comment by DanTup** [comment]
It's been a while since I used it, but I *think* if you put the extension IDs into a devcontainer folder, it will automatically install them in the remote when you connect.

Let me know if you have any trouble getting it working though!
