### ISSUE TITLE
Renamed tests do not disappear from the Test tree until running the whole file

### ISSUE THREAD

**Issue by themisir** [Dart-Code/Dart-Code#2837]
**Is your feature request related to a problem? Please describe.**
For example when I rename a test or remove the item is not disappeared from test tree. Adding clear button would help to reset test tree state.

**Describe the solution you'd like**
A button to clear test tree.

**Describe alternatives you've considered**
Restarting VSCode.

**Comment by DanTup** [comment]
The test tree should update automatically if you re-run the whole file, which should be a little better than restarting VS Code.

I think it'd be better to find a more reliable way to handle this than a clear button though - perhaps we can use the outline data to tell if a node is no longer a possible match for any tests.

It [looks like](https://github.com/dart-lang/test/pull/1332) there may be some changes being made in `package:test` that might make it easier for us to get a list of tests. (@natebosch I'd be interested in knowing a bit more about that when it's at a point it may be useful :-))

**Comment by natebosch** [comment]
If you want to start building prototypes with it and send any feedback you have we can definitely take a look at how it might fit. We likely won't ship a stable version of the API for a while, but any evidence we have that it solves, or doesn't solve, goals like this will help.

**Comment by TheMisir** [comment]
I think this was fixed after plugin update. I'll post an update if it doesn't works as expected.

**Comment by DanTup** [comment]
I don't believe anything has changed that would affect this, and it still seems to occur for me:

![Screenshot 2020-11-03 at 12 25 50](https://user-images.githubusercontent.com/1078012/97985175-ce35cc00-1dcf-11eb-9330-93ae68e29308.png)

However it is a known issue and the current suggestion is to run the whole file if you have made renames and want them to be removed. When you run the whole file, all stale results will be cleared out, but that's not done when you run a single test as it would result in all other tests (not in the test run) vanishing.

I don't think adding a Clear button is a good fix though, I think it's better to remain as-is until there's a reliable fix that just works without button pressing.
