### ISSUE TITLE
editor.action.triggerParameterHints should be executed automatically after method is selected

### ISSUE THREAD

**Issue by HerrNiklasRaab** [Dart-Code/Dart-Code#2838]
Is it possible to execute the command "editor.action.triggerParameterHints", once a method is selected or "(" is typed. So that it i populates automatically, and I don't need to trigger it with "command + shift + space".

![image](https://user-images.githubusercontent.com/28401593/94793238-7542d480-03da-11eb-8f1c-7e1f878b2ebe.png)

Off-topic: Is there a release plan, for when LSP is out of preview?

**Comment by DanTup** [comment]
Yep, this is automatically triggered on pressing `(` for LSP (if you're on a new enough version of the SDK). See #1132.

> Is there a release plan, for when LSP is out of preview?

There are quite a few bug fixes that aren't in a stable Flutter release yet so I've not been pushing it too much. After the next Flutter stable release I'd like to encourage more people to enable it (perhaps through a one-time popup offering to enable it - shown initially to a small number of users and increased over time).

Once I'm happy there aren't likely any significant issues, it will be enabled-by-default based on the SDK version (which might initially be a non-stable release, which would be an easy way to get a gradual rollout of that too).
