### ISSUE TITLE
"Failed to initialize Flutter: Process exited with code 1" after upgrade to Flutter 1.22

### ISSUE THREAD

**Issue by van-8** [Dart-Code/Dart-Code#2843]
### Steps to Reproduce
1. Upgrade to Flutter 1.22 on Stable channel
2. Flutter doctor
3. Open any project in VS Code (1.49.2)
4. Error: "Failed to initialize Flutter: Process exited with code 1."

Restarting, `flutter clean`, uninstall re-install Flutter Extension, all have no effect. Thanks very much for all the hard work! 

### Logs
```
flutter doctor --verbose
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.7 19H2, locale en-CN)
    • Flutter version 1.22.0 at /Users/Orca/flutter/flutter/flutter
    • Framework revision d408d302e2 (2 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/Orca/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.
```

**Comment by DanTup** [comment]
Could you try running the **Dart: Open Extension Log** command from the VS Code command palette after this happens, and see if it includes any error messages?

Thanks!

**Comment by van-8** [comment]
When I run **Dart: Open Extension Log** command from my VS Code command palette, I receive an error:
`Command 'Dart: Open Extension Log' resulted in an error (command 'dart.openExtensionLog' not found)`

### Troubleshooting since last update
1. Uninstalled and reinstalled Dart & Flutter extensions a few times and in different sequences (with system reboots in between), but still have the same error.  
2. Tried reinstalling Flutter itself by switching `flutter channel` > `flutter upgrade` > `flutter doctor` > `flutter clean` with same error.

I don't see anyone else with this problem; perhaps I messed up something with my VS Code settings? 
Will continue to troubleshoot. Thanks so much for helping!

<img width="569" alt="Screen Shot 2020-10-03 at 10 22 10" src="https://user-images.githubusercontent.com/28463475/94981140-5707e080-0562-11eb-82d5-39e63794cc48.png">

**Comment by DanTup** [comment]
Can you try running the **Developer: Open Extension Logs** folder and then look in the Dart-Code folder? It should be the same log the above command would've opened (the reason that command isn't working is that the extension is failing to activate correctly).

Thanks!

**Comment by van-8** [comment]
I've attached the log that has the word "dart" in it. There are 2 other folders created, which I've attached screenshot (don't think its those). LMK if you need those as well. Thanks!

[exthost.log](https://github.com/Dart-Code/Dart-Code/files/5333319/exthost.log)

<img width="800" alt="Screen Shot 2020-10-06 at 19 04 57" src="https://user-images.githubusercontent.com/28463475/95193796-f77e2f00-0806-11eb-9cdf-905716747037.png">

**Comment by DanTup** [comment]
@van-8 sorry, I thought were were logging into that folder by default but perhaps not.

There's a VS Code User Setting named `dart.extensionLogFile` which you can set as a string:

```
"dart.extensionLogFile": "/Users/danny/Desktop/log.txt",
```

If you set that and then reproduce the issue, it should log to that file. Depending on whether Flutter's output is going to stdout or stderr it may or may not be included. If not, I'll make a dev build that has improve logged and provide instructions for running it. Thanks!

**Comment by van-8** [comment]
Worked exactly as you detailed, Dan. The log is attached. Thank you!
[log.txt](https://github.com/Dart-Code/Dart-Code/files/5338430/log.txt)

**Comment by DanTup** [comment]
Can you try running these commands in a terminal and post the output?

```
which flutter
/Users/Orca/flutter config --machine
```

VS Code seems to be finding your Flutter SDK at `/Users/Orca/flutter`, but the `flutter doctor` output above says `/Users/Orca/flutter/flutter/flutter`. It's not clear where the SDK is or why that last path has three `flutter`'s in it.

Thanks!

**Comment by DanTup** [comment]
There's a build here with improved logging:

https://github.com/Dart-Code/Dart-Code/releases/tag/v3.16.0-dev.3

- Download the vsix file from that release
- Run the **Extensions: Install from VSIX** command in VS Code and browse to the vsix
- Click the **Reload** button

Then if you redo the instructions about, the log file should contain the full process output that shows why it exited with an error (if it's not clear from manually running `/Users/Orca/flutter config --machine`).

**Comment by van-8** [comment]
1. The improved logging is excellent. Attached is the new log. 
[log.txt](https://github.com/Dart-Code/Dart-Code/files/5358629/log.txt)

It seems since `Flutter is not initialized, running 'flutter config --machine'...`, then there is `URL using bad/illegal format`. Maybe a Dart SDK China mirror problem?


2. After installing VSIX, running 
```
which flutter
/Users/Orca/flutter config --machine
```
results in `zsh: permission denied: /Users/Orca/flutter`

**Comment by DanTup** [comment]
In the log file it has:

```
Downloading Dart SDK from Flutter engine <<<<<<< HEAD
d1bc06f032f9d6c148ea6b96b48261d6f545004f
=======
5babba6c4d25fa237bbf755ab85c9a0c50b3c6ec
>>>>>>> d408d302e22179d598f467e11da5dd968dbdc9ec...
```

This looks like a merge conflict marker has been read from the file `/Users/Orca/flutter/bin/internal/engine.version`. It may be possible that something has gone wrong when you've tried to upgrade Flutter.

I think you would need to either reset the Flutter SDK back to the branch it's intended to be (either with a `git clean` command, or re-downloading it). Please let me know if that doesn't help!

**Comment by van-8** [comment]
Using `git clean` and `git pull` related commands didn't work, but deleting the flutter folder and downloading a fresh copy of Flutter to install solved the problem. Thanks so much Dan!

At a later time I'll try to get the git version of flutter working.

**Comment by DanTup** [comment]
Great, glad to hear!

**Comment by TasnuvaOshin** [comment]
I Got the Solution For Mac Operating System :
Go to Your Flutter bin folder , where at 1st you had downloaded the flutter ,
then In VS Code , Open that Flutter Project ,
Get All the Package 
then Open Terminal ,
Write 
```
git add .
git commit -m 'problem fixed'
then from the git icon , change branch to main 
```
that it now your problem will be solved.

**Comment by tony123S** [comment]
Please help ! What should I do now?

[2:53:05 PM] [General] [Info]     Found at /home/xxx/Desktop/flutter_linux_1.22.6-stable/flutter
[2:53:05 PM] [General] [Info]     Returning SDK path /home/xxx/Desktop/flutter_linux_1.22.6-stable/flutter for flutter
[2:53:05 PM] [General] [Info] Flutter is not initialized, running 'flutter config --machine'...
[2:53:05 PM] [General] [Info] (PROC 22588) Logging data for process...
[2:53:05 PM] [General] [Info] (PROC 22588) Downloading Dart SDK from Flutter engine <<<<<<< HEAD
2f0af3715217a0c2ada72c717d4ed9178d68f6ed
=======
40441def692f444660a11e20fac37af9050245ab
>>>>>>> c5a4b4029c0798f37c4a39b479d7cb75daa7b05c...
[2:53:05 PM] [General] [Info] (PROC 22588) curl: (3) Illegal cha
[2:53:05 PM] [General] [Info] (PROC 22588) racters found in URL
[2:53:05 PM] [General] [Info] (PROC 22588) 
Failed to retrieve the Dart SDK from: https://storage.googleapis.com/flutter_infra/flutter/<<<<<<< HEAD
2f0af3715217a0c2ada72c717d4ed9178d68f6ed
=======
40441def692f444660a11e20fac37af9050245ab
>>>>>>> c5a4b4029c0798f37c4a39b479d7cb75daa7b05c/dart-sdk-linux-x64.zip
If you're located in China, please see this page:
  https://flutter.dev/community/china
[2:53:05 PM] [General] [Info] (PROC 22588) exited (1, null)

**Comment by DanTup** [comment]
@tony123S it looks like the `engine.version` file in your SDK contains Git conflict markers (this could happen if something tried to merge two Git branches together - though I'm not sure how that would occur).

The easiest way to fix this would be to re-extract the SDK if you got it from a zip. Running `git reset --hard 2.0.1` from the terminal inside your _Flutter SDK_ folder would probably also work (note: this will discard any local modifications in your Flutter SDK, though unless you're contributing to the Flutter SDK I would not expect you to have any).

**Comment by ree1500** [comment]
> 
> 
> Could you try running the **Dart: Open Extension Log** command from the VS Code command palette after this happens, and see if it includes any error messages?
> 
> Thanks!

Sir, I don't have this command in my command pallette.

**Comment by SrilekhaMarthi** [comment]
if you got a merge error delete the .git folder in flutter and use this 
cmd
 **git clone https://github.com/flutter/flutter.git -b stable**
it will produce the fresh .gif folder and move it to the SDK folder and run 
**flutter doctor**

**Comment by fpalacino** [comment]
@DanTup please help me here! having this expection when "failed to initialize flutter" on vscode:

[1:53:27 AM] [General] [Info]     Found at /Users/franciscopalacino/Desktop/1sem_2122/IPM/Projeto/flutter
[1:53:27 AM] [General] [Info]     Returning SDK path /Users/franciscopalacino/Desktop/1sem_2122/IPM/Projeto/flutter for flutter
[1:53:27 AM] [General] [Error] EPERM: operation not permitted, open '/Users/franciscopalacino/Desktop/1sem_2122/IPM/Projeto/flutter/version'
Error: EPERM: operation not permitted, open '/Users/franciscopalacino/Desktop/1sem_2122/IPM/Projeto/flutter/version'
	at Object.openSync (fs.js:476:3)
	at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
	at Object.readFileSync (fs.js:377:35)
	at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8872)
	at getSdkVersion (/Users/franciscopalacino/.vscode/extensions/dart-…
[1:53:27 AM] [General] [Info] Flutter is not initialized, running 'flutter doctor' to force...
[1:53:27 AM] [General] [Info] (PROC 22452) Logging data for process...
[1:53:27 AM] [General] [Info] (PROC 22452) bash: /Users/franciscopalacino/Desktop/1sem_2122/IPM/Projeto/flutter/bin/flutter: Operation not permitted
[1:53:27 AM] [General] [Info] (PROC 22452) exited (126, null)


can u help me ??

**Comment by DanTup** [comment]
It looks like something is wrong with your setup that's preventing Dart-Code from being able to run Flutter:

> bash: /Users/franciscopalacino/Desktop/1sem_2122/IPM/Projeto/flutter/bin/flutter: Operation not permitted

This may be the same issue described in https://github.com/Dart-Code/Dart-Code/issues/2200, so you may want to read through the solution there to see if it helps.

**Comment by fpalacino** [comment]
thanks @DanTup !! that has solved the problem!
