### ISSUE TITLE
Flutter 1.22.0 Stable Channel and 1.23.0 Master Channel - Running Gradle taking too much time around 15 minutes

### ISSUE THREAD

**Issue by MaheshPeri19** [Dart-Code/Dart-Code#2849]
Issue Type: <b>Bug</b>

Flutter 1.22 stable channel and Flutter 1.23.0-8.0.pre.129 master channel has issue with app compile and execution time around 15 minutes. So much time it is stuck at running gradle assembleTask, then after 15mins, it is loading the app.

Extension version: 3.15.0
VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:54:06.165Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|8.00GB (0.14GB free)|
|Process Argv|-psn_0_65552 --crash-reporter-id 3c54c5a5-a762-407f-9c41-cbc8f07c511e|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by DanTup** [comment]
Thanks for the report - though this doesn't sound like an issue in the VS Code extension (or one we can solve). However, if you capture a verbose log we can see if there's anything obvious that make be causing it to take so long.

- Run the **Dart: Capture Logs** command
- Untick **Analysis Server** and click OK
- Run your app and wait for it to complete (this may take 15 minutes based on the description)
- Click **Cancel** on the logging notification to stop logging and open the log file
- Ensure there's nothing sensitive in the log, paste it into [a gist](https://gist.github.com/) and provide the link here

Thanks!
