### ISSUE TITLE
Parenthesis completion quirk

### ISSUE THREAD

**Issue by Skylled** [Dart-Code/Dart-Code#285]
Demonstration: 

![](https://zippy.gfycat.com/GleefulSlightCommongonolek.gif)

As far as I can tell, VS Code is automatically matching my opening parenthesis, and Dart-Code is matching the pattern of foo().

Normally, when pressing return, I'm trying to spread my function or class constructor arguments across a few lines, where current behavior discourages that.

**Comment by DanTup** [comment]
> As far as I can tell, VS Code is automatically matching my opening parenthesis, and Dart-Code is matching the pattern of foo().

VS Code should only do what Dart Code tells it to (either (via the config)[https://github.com/Dart-Code/Dart-Code/blob/master/syntaxes/dart-configuration.json] or the completion). It's possible these two are overlapping though I wouldn't have expected the completion to insert a closing paren.

I'm not currently at a PC but I'll try and take a look this weekend. In case I can't repro, do you have any other extensions or VS Code settings that might be a change from the default behaviour here?

**Comment by Skylled** [comment]
I should've checked that before filing, instead of assuming. I just disabled all my extensions and opened a new VS Code window, and VS Code auto-completes any parenthesis I open, even in a .txt file. I don't remember changing any settings to do that sort of thing. About the only things I've done to my VS Code is make it look nice and add your (awesome) extension.

**Comment by DanTup** [comment]
Even if it's caused by a setting you've enabled, I'd like to see if I can stop it. It's even possible it happens by default - VS Code has this crazy behaviour of completing any old crap from a dictionary (see https://github.com/Microsoft/vscode/issues/10099) which I have turned off, so I wouldn't have noticed if that was causing it.

See if you can spot what's causing it (and whether setting `editor.wordBasedSuggestions: false` stops it) and I'll see if I can do anything to stop it affecting others.

**Comment by Skylled** [comment]
Okay, I fixed this for my own personal taste, by setting
`"editor.acceptSuggestionOnEnter": false`
Which lets me put a newline in the brackets without triggering autocomplete.
(My primary use-case is separating parameters with newlines.)

But the option you're talking about is
`"editor.autoClosingBrackets": false`
Which is default true.

**Comment by DanTup** [comment]
Thanks; I'll try and dig around when I get some time and see if I can make this not happen for people regardless of settings.

**Comment by DanTup** [comment]
Actually, this repros with my normal settings so I consider this a bug in the completion!

**Comment by DanTup** [comment]
Some info for me when I next get time to look at this...

The completion data coming back is below - it comes back as "foo" with a `replacementLength` of 3. The open paren being typed is then causing the completion list to be filtered by VS Code (it is *not* sending another request for completions). This inserts the closing `)` at the end, which then hangs around after our completion inserts.

At first glance, I'd say this is a VS Code bug - it's subtracting the `(` being typed from the start of the completion, but it's not subtracting the `)` it auto-typed off the end (it seems reasonable to expect this).

I'll try and dig further at the weekend and raise an issue with VS Code to see if they'd consider improving this.

```text
[19:04:34]: ==> {"id":"3","method":"analysis.updateContent","params":{"files":{"c:\\Users\\danny\\Desktop\\REPRO2\\main.dart":{"type":"add","content":"import 'dart:async';\r\n\r\nfoo(String a, {String b, String c}) {\r\n  print(\"test\");\r\n}\r\n\r\n\r\n\r\nmain() async {\r\n  fo\r\n}\r\n"}}}}
[19:04:36]: ==> {"id":"10","method":"analysis.updateContent","params":{"files":{"c:\\Users\\danny\\Desktop\\REPRO2\\main.dart":{"type":"change","edits":[{"offset":110,"length":0,"replacement":"o","id":""}]}}}}
[19:04:36]: ==> {"id":"12","method":"completion.getSuggestions","params":{"file":"c:\\Users\\danny\\Desktop\\REPRO2\\main.dart","offset":111}}
[19:04:36]: <== 

{
   "event":"completion.results",
   "params":{
      "id":"0",
      "replacementOffset":108,
      "replacementLength":3,
      "results":[
         {
            "kind":"INVOCATION",
            "relevance":1056,
            "completion":"foo",
            "selectionOffset":3,
            "selectionLength":0,
            "isDeprecated":false,
            "isPotential":false,
            "element":{
               "kind":"FUNCTION",
               "name":"foo",
               "location":{
                  "file":"c:\\Users\\danny\\Desktop\\REPRO2\\main.dart",
                  "offset":24,
                  "length":3,
                  "startLine":0,
                  "startColumn":0
               },
               "flags":0,
               "parameters":"(String a, {String b, String c})",
               "returnType":"dynamic"
            },
            "returnType":"dynamic",
            "parameterNames":[
               "a",
               "b",
               "c"
            ],
            "parameterTypes":[
               "String",
               "String",
               "String"
            ],
            "requiredParameterCount":1,
            "hasNamedParameters":true
         }
      ]
}

[19:04:36]: ==> {"id":"14","method":"analysis.updateContent","params":{"files":{"c:\\Users\\danny\\Desktop\\REPRO2\\main.dart":{"type":"change","edits":[{"offset":111,"length":0,"replacement":"()","id":""}]}}}}
[19:04:40]: ==> {"id":"18","method":"analysis.updateContent","params":{"files":{"c:\\Users\\danny\\Desktop\\REPRO2\\main.dart":{"type":"change","edits":[{"offset":108,"length":4,"replacement":"foo(a)","id":""}]}}}}
```

**Comment by DanTup** [comment]
The repro can be reduced to just this:

```dart
foo() {
}


main() {
  fo
}
```

Typing the opening parent and then invoking the completion item will result in a duplicate close paren. I believe this should be fixed in Code, so I've raised https://github.com/Microsoft/vscode/issues/26012 with the details to see what they think.

**Comment by Skylled** [comment]
Just confirmed that this has been resolved with v1.4

Good job, @DanTup.

**Comment by DanTup** [comment]
Interesting! I think it's a bug in Code but I'm guessing my change to force completion to refresh after you press `(` is causing it to get a new completion list without either paren, which somewhat sidesteps the issue :-)

**Comment by jdneo** [comment]
Hi @DanTup,

I meet the same issue as this. May I ask how you resolve this issue?

**Comment by DanTup** [comment]
@jdneo Based on the comment above I'm not totally sure, but I think we added `(` to the trigger characters for the completion provider (03ea03845657472f62d2681be82fc1cc991ceed9). This means when you type the `(` VS Code will re-request completion (and either not complete the original entry or not insert the matching closing paren).

The better fix is probably to make `(` a commit character on the completion - this is something Dart Code supports but is currently off-by-default because it triggers a lot when we don't want it to, so it needs some refining!

**Comment by jdneo** [comment]
@DanTup Thank you for reaching out! really helpful!
