### ISSUE TITLE
Analyzer reports error - named parameter not defined on SDK upgrade

### ISSUE THREAD

**Issue by sidrao2006** [Dart-Code/Dart-Code#2851]
According to these open issues on the flutter repo, the dart analyzer on flutter v1.22.0 reports errors for the properties colors, transform and stops

- [#67268](https://github.com/flutter/flutter/issues/67268) 
- [#67198](https://github.com/flutter/flutter/issues/67198)
- [#64724](https://github.com/flutter/flutter/issues/64724)
- [#63908](https://github.com/flutter/flutter/issues/63908)

**Comment by AchalYash** [comment]
Invalidating Cache worked for me. You might want to give it a try as well.

**Comment by sidrao2006** [comment]
Hey @AchalYash , I did not face this issue. I am just addressing the many issues which are continuously being opened.

**Comment by DanTup** [comment]
I believe this is the issue described in https://github.com/dart-lang/sdk/issues/43532. You may need to fetch packages and *then* restart the editor as a workaround. If the packages have been fetched prior to the analysis server starting, then the issue should not occur.

If you can reproduce the issue even after fetching packages and then restarting the editor, let me know and I'll do some more digging in case there's another issue too. Thanks!
