### ISSUE TITLE
Closing and re-opening Widget Inspector does not render correctly

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#2852]
- Launch embedded inspector
- Close the tab
- Relaunch inspector

Sometimes this just loads as a blue dot in the middle a black pane:

<img width="712" alt="Screenshot 2020-10-27 at 09 50 58" src="https://user-images.githubusercontent.com/1078012/97285313-f3f42b80-1839-11eb-9e17-f23a6166c6ad.png">

**Comment by DanTup** [comment]
I added some logging, and it seems like DevTools is definitely running correctly when this happens:

![Screenshot 2020-10-27 at 11 10 12](https://user-images.githubusercontent.com/1078012/97293782-0a53b480-1845-11eb-8a1f-d21af097a9e7.png)

However there's no ability to inspect the DOM of the embedded iframe (https://github.com/microsoft/vscode/issues/105370) so it's hard to know what's happening here.

@jacob314 I don't supposed you've ever seen DevTools render like this (without VS Code)? I'm not sure whether that blue square is something from DevTools, something from VS Code, or DevTools being rendered at 1x1 px or something 😬

**Comment by DanTup** [comment]
![Screenshot 2020-10-27 at 11 18 58](https://user-images.githubusercontent.com/1078012/97294718-450a1c80-1846-11eb-8f86-a4d1eb6b975a.png)

Printing the window.body size in the initial JS is the same both when it works and doesn't, so doesn't seem like it thinks it's in a small window either.

**Comment by jacob314** [comment]
I expect we can repro by embedding a generic flutter app in an iframe, manipulating the iframe so it is not displayed, and then displaying the iframe again. If you are not able to repro with a generic Flutter app let me know and we can debug if something is specifically going wrong for the Inspector.

**Comment by DanTup** [comment]
Ah, interesting idea.. Though it's not really hiding/showing the iframe here, the whole thing is just destroyed and recreated.

I tried to repro the opposite - DevTools in an iframe in a simple webpage I was just reloaded, but couldn't get it to occur.

However it did occur to me I can change the colours in DevTools to see whether the rendering is coming from it - and it seems like it is:

<img width="692" alt="Screenshot 2020-10-28 at 16 13 54" src="https://user-images.githubusercontent.com/1078012/97464385-c17d2800-1938-11eb-8148-6beb2621e33e.png">

<img width="1407" alt="Screenshot 2020-10-28 at 16 13 41" src="https://user-images.githubusercontent.com/1078012/97464410-c7730900-1938-11eb-84b8-5f120b3f44de.png">

So I'll hack around at DevTools a little more to see if I can figure out exactly what's being rendered - that might help understand what's happening.

**Comment by DanTup** [comment]
Ok, I did some more digging and have found a difference between when this works/doesn't work... I added logging all around the place, and here's the difference between it working (left) and not (right):

<img width="919" alt="Screenshot 2020-10-28 at 16 44 48" src="https://user-images.githubusercontent.com/1078012/97468273-fee3b480-193c-11eb-897b-005777abbdee.png">

Both times "onConnectionAvailable callback!" is printed, which comes from the initializer, then it calls `setState()`:

<img width="670" alt="Screenshot 2020-10-28 at 16 46 17" src="https://user-images.githubusercontent.com/1078012/97468381-1fac0a00-193d-11eb-99ad-2c9ec3f0e4b0.png">

However the next line, printed at the top of the widgets `build` method is never called in the broken case (nor is didUpdateWidget since that has prints that don't appear, now is the Initializer constructor called again either, as that's also logged).

I think the square is probably the animated spinner - since that's the thing that's usually rendered up until that code runs - though why that isn't animating either, I'm not sure.

**Comment by DanTup** [comment]
I added some logging inside/after the setState and in a catch block, in case it was triggering any of the errors that can be thrown in setState, but nothing (they all printed fine as expected).

I tried removing `FLUTTER_WEB_USE_SKIA=true` from the build too, but that also made no difference.

Oh also, I've removed all rendering of screens so it only renders the spinner or a text:

```dart
return isLoaded
    ? const Text('SCREEN HERE')
    : const Scaffold(
        body: Center(
          child: CircularProgressIndicator(),
        ),
      );
```

So it's not related to anything in the Inspector screen either.

I still don't know whether it's a DevTools issue, or something really breaking in electron/VS Code that's stopping the scripts from running further (although there is JavaScript in the page with timers that does run after this happens, so I guess it can't be completely broken).

**Comment by jacob314** [comment]
Seems like it is a Flutter Web issue given you see the issue with the progress indicator. Can you create a repro of the issue for the issue for the flutter web team to issue that doesn't require using vscode or electron? Perhaps Flutter Web has an issue if you add an iframe to an already running webpage or VSCode is doing some work to keep around the iframe so it isn't a completely new iframe?

**Comment by DanTup** [comment]
I added some prints throughout Flutter, and found that whenever this happens, it's when this code in `scheduleBuildFor` skips over calling `onBuildScheduled`. I don't completely understand how this code works to know whether that's important though.

<img width="652" alt="Screenshot 2020-10-29 at 14 12 35" src="https://user-images.githubusercontent.com/1078012/97585260-db7a4180-19f0-11eb-857a-1e40653a5566.png">

I rigged VS Code to run a debug version of the app (using `flutter run` - since it doesn't seem like we can do `flutter build web --debug`) and was unable to reproduce it at all there (I was slightly hoping it might trigger some asserts that would explain it).

> Perhaps Flutter Web has an issue if you add an iframe to an already running webpage or VSCode is doing some work to keep around the iframe so it isn't a completely new iframe?

The iframes are all above the Flutter app here, and I believe the whole outer frame is being completely destroyed in between these loads (I also hit it once on the first first load, so I think it's likely just a race more than being related to close/re-opening).

I'll do some testing to confirm the whole frame is being destroy, and have another go at reproducing in a browser (I'll nest multiple iframes, as it is in VS Code). The version of Chromium version in electron/VS Code is likely older than the current stable release, so that might also be a factor (whether a bug, or just affecting timing or something).

**Comment by DanTup** [comment]
After many refreshes, I was able to reproduce this outside in Chrome proper.
 
![Screenshot 2020-10-29 at 14 51 41](https://user-images.githubusercontent.com/1078012/97590227-4ed28200-19f6-11eb-8035-f7f602a35883.png)

I'll tidy it up into a standalone folder (currently it's running a hacked version of DevTools from pub) and file an issue with Flutter.

**Comment by jacob314** [comment]
Thanks for creating a clean repro of this issue!

**Comment by DanTup** [comment]
That was still using the DevTools server and a real connection to a VM, though I've now managed to strip it down further and repro with a single-file Flutter app and running with Python's built-in HTTP server (instead of devtools_server):

![Screenshot 2020-10-29 at 16 19 17](https://user-images.githubusercontent.com/1078012/97601923-9d861900-1a02-11eb-8b4b-0ad58cfca905.png)

It seems most reliably reproducible after "Clear app data" (which unregisters the service workers etc.), though it's still quite intermittent so that might be entirely unrelated.

I'm still building it inside the DevTools project though, so I'll lift it out of there and write it up in an issue shortly.

**Comment by jacob314** [comment]
To make sure this isn't a service worker problem you could remove the service worker from your local DevTools build and see if the issue still reproduces in VSCode. The service worker is only there as a performance optimization.

**Comment by DanTup** [comment]
I'll give it a go! In the meantime, I've filed an issue here with full steps to repro (it's just a single file Flutter app run through a local web server):

https://github.com/flutter/flutter/issues/69313

**Comment by DanTup** [comment]
[Still repro's](https://github.com/flutter/flutter/issues/69313#issuecomment-718886654) without the service worker.

**Comment by DanTup** [comment]
Since this repro's without VS Code or DevTools, closing this a an upstream issue at https://github.com/flutter/flutter/issues/69313. Once that's fixed, there shouldn't need to be any changes here.
