### ISSUE TITLE
Color Preview in VSCode is fooled when using custom classes ending with "Colors".

### ISSUE THREAD

**Issue by HosseinYousefi** [Dart-Code/Dart-Code#2857]
**Describe the bug**
If the name of the class finishes with Colors, VSCode shows a preview as if the class name was Colors. (see the screenshot)

**To Reproduce**
You can use this code:
```
import 'dart:ui';

class MyColors {
  static const red = Color(0xff00ff00);
}

class NoColorHere {
  static const red = Color(0xff00ff00);
}

void somefunction() {
  final someOtherColor = NoColorHere.red;
  final someColor = MyColors.red;
}
```

**Expected behavior**
Preferably it should show the actual color in all cases, but a quick fix could be to not show the color preview when the class is not "Colors".

**Screenshots**
<img width="548" alt="Screenshot 2020-10-08 at 10 49 29" src="https://user-images.githubusercontent.com/9751815/95436286-f3135c80-0953-11eb-8869-fca005397b3b.png">

**Versions (please complete the following information):**
 - VS Code version: 1.49.3
 - Dart extension version: 3.15.0
 - Dart/Flutter SDK version: 2.8.4/Flutter 1.17.5

**Comment by DanTup** [comment]
I'll fix this to only allow `Colors`, though I don't think we can make this completely reliably (some colours may not be known statically, and you could also create your own `Colors` class too). In the future this may move into the server (with LSP), so perhaps it will be easier to make it more reliable there (that's #2167).
