### ISSUE TITLE
Dart SDK should be used from local cache folder for Flutter projects

### ISSUE THREAD

**Issue by sethladd** [Dart-Code/Dart-Code#286]
Flutter bundles its own Dart SDK. When I open a Flutter project, I see this error:

![capture](https://cloud.githubusercontent.com/assets/5479/25773873/3574b046-323a-11e7-8af4-ff26049daa4d.PNG)

Ideally:

* VS Code should detect I've opened a Flutter project (probably from pubspec.yaml containing "sdk: flutter"), and then find the Dart SDK that is downloaded by Flutter (inside of FLUTTER_HOME\bin\cache\dart-sdk)

Suggesting that the user "Go to Dart downloads" isn't correct for Flutter. A Flutter user wants the Dart SDK that is in Flutter, not the SDK that is downloaded from dartlang.org

BTW thanks for this plugin. Really nice!

**Comment by DanTup** [comment]
Just to be clear, the flutter-provided SDK should be used for the analysis server too? (I presume so, but since the SDK is used for a couple of things I want to be sure before changing anything!).

> and then find the Dart SDK that is downloaded by Flutter (inside of FLUTTER_HOME\bin\cache\dart-sdk)

Is `FLUTTER_HOME` here a special folder (environment variable?) or do you just mean the workspace root?

The less flutter-specific stuff in Dart Code, the less there is to break/need maintaining. If this is inside the workspace then a rule to just use the SDK from `{workspaceRoot}\bin\cache\dart-sdk` if one exists should be a fairly simple change.

**Comment by DanTup** [comment]
Also - currently you can set any SDK path in the VS Code settings (eg. to test a pre-release version that isn't on your path). How should this behave here? Should the flutter-downloaded version always be used over anything else (this means you'd need to replace that folder if you wanted to test a different version, but I presume if the flutter-provided SDK is not the same as a release version, then using the version on PATH probably never makes sense?).

Btw, are the reasons that Flutter can't use a standard SDK documented somewhere? I'm slightly curious about the decision to have a patched(?) SDK!

**Comment by DanTup** [comment]
Also - can you confirm what the correct steps are if a user opened a project that has `sdk: flutter` but has never set up flutter? (eg. if I clone a Flutter project from GitHub)? Presumably they have no flutter commands yet, so how do they get started?

**Comment by DanTup** [comment]
@sethladd Can you advise of the difference between `FLUTTER_HOME` and `FLUTTER_ROOT`? You mentioned the first, but [this doc](https://flutter.io/upgrading/) references the second.

**Comment by sethladd** [comment]
Sorry, not sure what the canonical env variable is. I don't think I even need to set a env variable when installing Flutter.

**Comment by sethladd** [comment]
If you open a flutter project (sdk: flutter), but don't have Flutter installed, you can direct them to https://flutter.io/setup/

**Comment by DanTup** [comment]
@sethladd The update I pushed out over the weekend should detect flutter from `FLUTTER_ROOT`, `PATH` or at `.\bin\`. I think this handles most cases though if none match the user gets a message about the missing SDK (I'll add a link to that URL in for the next version though).

**Comment by sethladd** [comment]
Thanks! I'll give it a shot :)

As always, really appreciate it.
