### ISSUE TITLE
"Create missing overrides" quick fix works incorrectly for dynamic type parameter

### ISSUE THREAD

**Issue by skybur** [Dart-Code/Dart-Code#2862]
**Describe the bug**
When creating class that implements abstract class with abstract method that returns an object with type parameter and it's dynamic, the quick fix "create missing overrides" did not generate dynamic type parameter. Is this intended?
Sorry if this is duplicate or problem with Flutter/Dart not Dart-Code.

**To Reproduce**
1. Create abstract class with abstract method that returns object with dynamic type parameter. ex `Map<String, dynamic>`
2. Create class that implements previous class and use quick fix "create missing overrides".

**Expected behavior**
dynamic type parameter is generated.

**Screenshots**
![yPagu80ftL](https://user-images.githubusercontent.com/11155424/95551595-48736a80-0a35-11eb-9246-bdaf6e118e02.gif)

**Versions (please complete the following information):**
 - VS Code version: 1.49.3
 - Dart extension version: 3.15.0
 - Dart/Flutter SDK version: 1.17.3
 - Flutter doctor:
```
[flutter] flutter doctor -v
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.7 19H2, locale en-US)
    • Flutter version 1.17.3 at /Users/catalina/Dev/flutter
    • Framework revision b041144f83 (4 months ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/catalina/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/catalina/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
exit code 0
```

**Comment by DanTup** [comment]
Thanks for the report! This code is generated by the analysis server, so this needs to be fixed there. There's already an open issue tracking it here that you can subscribe to for updates:

https://github.com/dart-lang/sdk/issues/33609

Thanks!
