### ISSUE TITLE
Auto-complete for method handlers / builders in VSCode

### ISSUE THREAD

**Issue by esDotDev** [Dart-Code/Dart-Code#2864]
It would be nice when writing Flutter code, if the IDE could take care of writing inline method handlers since the compiler knows the full method signature anyways. 

Apologies if this is not the correct place to ask, I wasn't sure where to post.

Example:
```
class Foo extends StatelessWidget {
   final void function(BuildContext c, int index, bool isEnabled) builder;
}

//
return Foo(
   builder: //autocomplete this --> (BuildContext c, int index, bool isEnabled) {}
 )
```

**Comment by DanTup** [comment]
I think this may already exist, as of https://github.com/dart-lang/sdk/issues/40013#issuecomment-574422203.

It doesn't appear on the named arg, but if you invoke completion for the value, you should see this:

<img width="655" alt="Screenshot 2020-10-12 at 11 52 50" src="https://user-images.githubusercontent.com/1078012/95738684-882e9200-0c81-11eb-8b65-aeb58a78322c.png">

I don't know if this change has made it to a stable version of Flutter, but it's definitely there on master.

Let me know if this doesn't address the request. Thanks!

**Comment by esDotDev** [comment]
Yes thats perfect, thx!

**Comment by i02dipea** [comment]
A mi no me funciona, alguien puede ayudarme?

**Comment by DanTup** [comment]
@i02dipea please file a new issue with a clear description/screenshots of the problem you're having. Thanks!
