### ISSUE TITLE
Dart code stuck on "Analyzing", making every operation take too long

### ISSUE THREAD

**Issue by Dancovich** [Dart-Code/Dart-Code#2865]
After upgrading to Dart Code 3.15 and VSCode to 1.50, Dart Code gets stuck on "Analyzing", making every operation, from coded completion to saving files, take too long.

**To Reproduce**
1. Use Dart Code 3.15 and VSCode 1.50
2. Open any Flutter project
3. Wait for the initial "Analyzing" process to finish
4. Open any Dart file
5. Edit the file, requesting code multiple times
6. VSCode starts "Analyzing" after every code completion request, taking increasingly longer times every time it happens

**Expected behavior**
After doing initial analysis, code completion should take from a few milliseconds up to a few seconds

**Versions (please complete the following information):**
 - 1.50
 - 3.15.0
 - Flutter 1.22

**Output from `flutter doctor -v`**
❯ flutter doctor -v
[√] Flutter (Channel stable, 1.22.0, on Microsoft Windows [versÃ£o 10.0.19041.508], locale pt-BR)
    • Flutter version 1.22.0 at D:\dcvia\Desenvolvimento\Android\flutter
    • Framework revision d408d302e2 (10 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3) 
    • Android SDK at D:\dcvia\Desenvolvimento\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = D:\dcvia\Desenvolvimento\Android\Sdk
    • Java binary at: C:\Users\dcvia\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\dcvia\android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.50.0)
    • VS Code at C:\Users\dcvia\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] Connected device (1 available)
    • SM G950F (mobile) • ce11182b72a0ba3a02 • android-arm64 • Android 9 (API 28)

**Comment by smiLLe** [comment]
Did you find a solution? I experience the same problem and i have to wait about 5-10 seconds just for an autocompletion.

**Comment by DanTup** [comment]
Could you try enabling the [analysis server log](https://dartcode.org/docs/logging/#analyzer) and then reproduce the issue, and provide the log? (note: it may include parts of your open files, so best to reproduce with a clean/new project).

Thanks!

**Comment by campovski** [comment]
Also on a new MacBook Pro, same issue. Dart Code is taking up almost 100% CPU "analyzing" and whole system freezes for few seconds until it finishes. Then after few changes running smoothly, it goes back to "analyzing".

**Comment by DanTup** [comment]
@campovski are you able to capture the log linked above?

**Comment by campovski** [comment]
@DanTup Yes, I managed, [here](https://gist.github.com/campovski/bd3266b3d5293c41650c9a5203d9a7e3) it is.

**Comment by ckt0** [comment]
Same here. Every time I touch the code, it sends RAM usage flying and takes forever to stop analyzing.
Also runs 'pub get' every few minutes for no apparent reason. 

I tried 'flutter clean' but that didn't work.  My project has many files linked through 'part of' directives, maybe that's why?

This is on VS Code 1.49.3 with only the latest Flutter & Dart plugins enabled. 
Previous versions of the plugin worked fine.

**Comment by campovski** [comment]
@ckt0 Shouldn't be, I only have one BLoC using `part` and it is still the same. Probably it would be useful to provide all logs @DanTup ?

**Comment by campovski** [comment]
Another [one](https://gist.github.com/campovski/859bffccbbea6e053385b9e071037355), failing to respond to `⌘ + .`. Also just saving a file sometimes takes ages...

**Comment by DanTup** [comment]
Thanks for the logs - I can definitely see a lot of slowness for some requests, though it's not entirely clear why (the log also doesn't seem to contain any analysis status notifications where I'd expect to see the appear/disappear).

Some things to try:

1. Enable the `dart.previewLsp` setting. This moves more of the work into the server and has some reasonable performance gains (especially when it comes to code completion). LSP will become the default in the near future.

2. If you were running debug sessions when seeing these issues, try [this beta build](https://github.com/Dart-Code/Dart-Code/releases/tag/v3.15.1-beta.1) (v3.15.1 may be released later today, so if you've already been upgraded to v3.15.1 by the time you read this, no need to install the beta). There was a severe performance issue in v3.15.0 that would consume vast amounts of CPU when printing large strings (or large numbers of) while your app was running.

3. Run `code --status` when the CPU is high / stuck analyzing and provide the output here.

If anyone can reproduce this reliably on a public project they can share, that may help me track down what's going on.

**Comment by ckt0** [comment]
> Same here. Every time I touch the code, it sends RAM usage flying and takes forever to stop analyzing.
> Also runs 'pub get' every few minutes for no apparent reason.
> 
> I tried 'flutter clean' but that didn't work. My project has many files linked through 'part of' directives, maybe that's why?
> 
> This is on VS Code 1.49.3 with only the latest Flutter & Dart plugins enabled.
> Previous versions of the plugin worked fine.

Okay... I no longer have this issue and I think I know why. I had 2 `const List<String>` arrays of 10,000 words each, in one of my files. That maybe what caused the analyzer to take so long. I made them load in as runtime assets and everything works fine again.

**Comment by DanTup** [comment]
@ckt0 I tried creating such lists but didn't see any issues. If you can reproduce this in a small sample you can share, please let me know. I don't see any reason why 10k items in a const list should cause any performance issues.

Thanks!

**Comment by ckt0** [comment]
@DanTup I was thinking maybe the plugin was looking for references to elements in these lists throughout the project. I remove the lists and everything is back to normal. 

The only other changes I made were: 
- Updating the plugin & VS Code
- Running **'flutter upgrade'**
- Deleting my **'pubspec.lock'** file and running **'flutter pub get'**

I still feel it was removing the list that made the difference. If I can reproduce the issue I will let you know!

**Comment by freitzzz** [comment]
> Thanks for the logs - I can definitely see a lot of slowness for some requests, though it's not entirely clear why (the log also doesn't seem to contain any analysis status notifications where I'd expect to see the appear/disappear).
> 
> Some things to try:
> 
> 1. Enable the `dart.previewLsp` setting. This moves more of the work into the server and has some reasonable performance gains (especially when it comes to code completion). LSP will become the default in the near future.
> 2. If you were running debug sessions when seeing these issues, try [this beta build](https://github.com/Dart-Code/Dart-Code/releases/tag/v3.15.1-beta.1) (v3.15.1 may be released later today, so if you've already been upgraded to v3.15.1 by the time you read this, no need to install the beta). There was a severe performance issue in v3.15.0 that would consume vast amounts of CPU when printing large strings (or large numbers of) while your app was running.
> 3. Run `code --status` when the CPU is high / stuck analyzing and provide the output here.
> 
> If anyone can reproduce this reliably on a public project they can share, that may help me track down what's going on.

Thank you, enabling `dart.previewLsp` solved the issue for me (at least for now). One question, when you mention that the work is moved the server, does it mean that a service is created for dealing with the analysis which isn't attached to VS Code process?

**Comment by DanTup** [comment]
> Thank you, enabling `dart.previewLsp` solved the issue for me (at least for now)

Glad to hear! I'll close this on the basis that the non-LSP version is going away over the coming releases.

> does it mean that a service is created for dealing with the analysis which isn't attached to VS Code process?

This has always been the case, though the protocol that the VS Code extension uses to communicate with the Dart language server is changing slightly with this (it used to be a custom protocol designed for Dart, but LSP is a standard that many languages/editors use).

It's fairly common for languages to have their own "language servers" that run separately from the editors. This allows sharing a lot of functionality (like code completion and analysis) between editors much more easily (and LSP aims to make this even easier).

Hope this helps!

**Comment by raphael-bmec-co** [comment]
I battled with this for a few hours. In case anyone else is battling with this, in the end I tracked the issue down to a half written line of code:

`  Future<List<>>`

**Comment by DanTup** [comment]
@raphael-bmec-co thanks for tracking this down and posting! I was able to reproduce the same and have filed an SDK issue at https://github.com/dart-lang/sdk/issues/44477.

**Comment by duannl** [comment]
The same issue with `Future<List>` after I used Quick Fix on Visual Studio Code

**Comment by DanTup** [comment]
@duannl if you're able to reproduce this and share a complete code example that triggers it, please file a new issue. Thanks!

**Comment by VinayGhadigaonkar** [comment]
> 1. Enable the `dart.previewLsp`

i have enable the `dart.previewLsp` but does not work for me.

**Comment by DanTup** [comment]
@VinayGhadigaonkar what do you mean by "does not work"? Do you mean it doesn't fix the issue, or that enabling LSP is broken in another way?

Please file a new issue with specific details about your problem. Thanks!

**Comment by duannl** [comment]
> @duannl if you're able to reproduce this and share a complete code example that triggers it, please file a new issue. Thanks!

Sorry for late reply. I enabled the preview Lsp and it works pretty well now. Thanks for your support :)
