### ISSUE TITLE
adobe_xd to flutter code

### ISSUE THREAD

**Issue by likitha2303** [Dart-Code/Dart-Code#2868]
Target of URI doesn't exist: 'package:adobe_xd/pinned.dart as pinned'.
Try creating the file referenced by the URI, or Try using a URI for a file that does exist.
![image](https://user-images.githubusercontent.com/57608814/95676773-57e1e780-0bde-11eb-9400-8764f4079483.png)

i have upgraded the packages, closed and restarted the editor, tried all possible solutions, please help me out.
I am trying to export the code from adobe_xd to flutter, after exporting am getting this error.

**Comment by DanTup** [comment]
The code you have is slightly incorrect. Where you have written:

```dart
import 'package:foo/foo.dart as foo';
```

The alias (`as foo`) should be outside of the single quotes (`'`):

```dart
import 'package:foo/foo.dart' as foo;
```

The value inside the quotes should only be the package name. If you want an alias, you need to put it outside of the string.

Hope this helps!

**Comment by DanTup** [comment]
Also - the casing of your alias must match where you use it. You're using lowercase `pinned` in the alias, but `Pinned` with a capital `P` on line 28.
