### ISSUE TITLE
Flutter Initialization is infinite and no flutter commands work.

### ISSUE THREAD

**Issue by PenCone** [Dart-Code/Dart-Code#2869]
Since updating to v3.15 flutter has permanently been initialising. 
![image](https://user-images.githubusercontent.com/18194488/95736048-9aa6cc80-0c7d-11eb-9a7a-ed068b331a04.png)

I have tried reinstalling the flutter extension, the dart extension, I have tried older versions, restarted VS code and my system. I have tried to run all the flutter commands (doctor, clean, run, pub get), they all end trying to run pub upgrade which ends up crashing for this reason:
> The current Dart SDK version is 2.9.2
> flutter_tools depends on test >=1.16.0-nullsafety which requires SDK version >=2.10.0-0 <2.11.0, version solving failed.

I would assume part of the error would lie in the current Dart SDK not being above 2.10.0, but I can't seem to upgrade it.

The crash log returns this:
[flutter_01.log](https://github.com/Dart-Code/Dart-Code/files/5364547/flutter_01.log)

Which does seem to run flutter doctor okay but still doesn't resolve the issues. 
I have tried deleting the pubspec.lock file and launch.json file as other sites have suggested, nothing has worked. 

Prior to the update I was working on implementing Firebase and had some dependency errors there, but they were resolved shortly before it updated and the application ran fine. Now I can't debug or really do anything. Also not sure how to reproduce the error because it is never ending. I also tried to run a new flutter project but that also had the same issue.

- VS Code version: 1.50.0

Thanks for any help

**Comment by DanTup** [comment]
This looks like the same issue being discussed in https://github.com/Dart-Code/Dart-Code/issues/2843#issuecomment-707050666. It seems like your Flutter install may be broken with merge conflict markers in the file `bin/internal/engine.version`. This is preventing Flutter from downloading the engine, as the file does not contain a valid git hash.

I would recommend reinstalling the SDK, or if you're comfortable using Git, reset the Flutter SDK back to the correct branch and clean any modified files from the Flutter SDK repo.
