### ISSUE TITLE
Refactor directory

### ISSUE THREAD

**Issue by WildOrangutan** [Dart-Code/Dart-Code#2881]
**Describe the solution you'd like**
When you rename directory, it would be nice to update imports accordingly.

**Describe alternatives you've considered**
Using `"dart.updateImportsOnRename": true`, but only works when moving and renaming files.

**Additional context**
Dart-code: 1.15.0
VS Code: 1.50.1

**Comment by DanTup** [comment]
Thanks for the suggestion! There's an open issue tracking this at https://github.com/Dart-Code/Dart-Code/issues/2483. It requires some work in the analysis server to support this so it's not an easy fix, but definitely something I'd like to support. Thanks!

**Comment by WildOrangutan** [comment]
I see, sorry about duplicate 😅

**Comment by DanTup** [comment]
No worries - sometimes I file dupes of my own existing issues 😄
