### ISSUE TITLE
Refactor does not appear on editor context menu when using LSP

### ISSUE THREAD

**Issue by bsutton** [Dart-Code/Dart-Code#2885]
A few weeks ago my refactor menu stopped showing up.

I'm not certain exactly when but it's been a few weeks now (and I generally keep to the latest version of dart-code).

I can still do actions like renaming a file (I assume this built into vscode) but the refactoring of import names does not occur.

When opening the context menu from a widget none of the standard options (e.g. swap with parent) appear. image attached.

I've just tried recreating the workspace by removing the .settings, workspace file, ~/.vscode (and then reinstalled dartcode).

All with no affect.

![context menu](https://user-images.githubusercontent.com/900408/96387262-794d5f80-11ec-11eb-8da4-e721cb77ca2f.png)

Dart-code: v3.15.1
Vs-code: v.50.1

**Comment by DanTup** [comment]
@bsutton is it just the Refactor entry from this menu that's missing, or do they also not show up in the lightbulb?

I can repro them showing up in lightbulb, but no refactor menu here. If you're not seeing them in the lightbulb either, that's likely a different issue.

I'll see if I can figure out what triggers the Refactor menu to appear (and whether it's changed in VS Code recently, which might explain it disappearing).

**Comment by bsutton** [comment]
I hadn't thought about checking the quick fix menu.

And yes all of the expected refactoring operations are available under the
quick fix menu.

It does however look like we have a secondary issue in that renaming an
library doesn't refactor the import statements. I will raise a separate
issue.

**Comment by DanTup** [comment]
This seems to be LSP-related. For non-LSP, our refactor provider provides metadata to VS Code to tell it we have refactors:

https://github.com/Dart-Code/Dart-Code/blob/master/src/extension/providers/refactor_code_action_provider.ts#L21-L23

However in LSP we don't have this - seems like we need to provide them in the `ServerCapabilities`.

**Comment by DanTup** [comment]
Fixed by https://dart-review.googlesource.com/c/sdk/+/169102, though it may take time to show up as it's in the SDK and will need to roll into Flutter etc.
