### ISSUE TITLE
Flutter SDK installed using Snap is not located correctly on Arch Linux

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#2886]
Raised by @teohhanhui at https://github.com/Dart-Code/Dart-Code/issues/2791#issuecomment-709883878.

**Comment by DanTup** [comment]
@MarcusTomlinson I mis-read the code when I posted [here](https://github.com/Dart-Code/Dart-Code/issues/2791#issuecomment-711822315) - we're already looking in "~/snap/flutter/common/flutter". The issue is that we only do this if we find a file at `/snap/flutter/current/flutter.sh`:

https://github.com/Dart-Code/Dart-Code/blob/616ebc19ea897e9895c81a8e9cec70f6deb01ab8/src/extension/sdk/utils.ts#L455

So is the file `/snap/flutter/current/flutter.sh` in a different place on Arch? If I understand correctly, we're using this simple as a check for "does the user have the Flutter snap installed?" so we know whether it's reasonable to run `~/snap/flutter/common/flutter` if it looks like an uninitialised SDK so it'll pass the later checks.

> I wonder how the Android studio extension finds/prioritises SDK path

In the issue you linked, the project was created with `flutter create` then opened. In VS Code the same should work - as we should read the `.packages` file and find the SDK that way. It doesn't help for projects that haven't had the packages restored already though (or in the case where the Snap hasn't been initialised fully).

We could also probably easily add `~/snap/flutter/common/flutter` to the default locations we search for SDKs which would solve this issue *if the Snap was initialised*, but it wouldn't help the case where it's been installed and not initialised.

**Comment by MarcusTomlinson** [comment]
> We could also probably easily add `~/snap/flutter/common/flutter` to the default locations we search for SDKs which would solve this issue _if the Snap was initialised_, but it wouldn't help the case where it's been installed and not initialised.

Right, this is the way forward I believe. Without snap-specific logic in the extension (which we don't want), we have to assume the snap is initialised externally. I don't think it's a totally unfair assumption. Most people are likely to install flutter and run at least one command before using it elsewhere (such as `flutter upgrade` or `flutter doctor`).

**Comment by DanTup** [comment]
Ok cool, I'll do that then. I'll leave the other logic in for now too (that can handle uninitialised Snap - albeit only for Ubuntu and others that use the same path) since it's fairly simple. The main goal was to not *require* Snap-specific implementation for each editor, but that doesn't mean we can't have the additional nice functionality here if it might help simplify getting started.

Thanks!
