### ISSUE TITLE
Extension Issue

### ISSUE THREAD

**Issue by MrHallows** [Dart-Code/Dart-Code#2887]
- Issue Type: `Bug`
- Extension Name: `dart-code`
- Extension Version: `3.15.1`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.51.0-insider`

Error Data:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 1170,
		"activateCallTime": 209,
		"activateResolvedTime": 12692,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "Dart-Code.dart-code",
				"_lower": "dart-code.dart-code"
			},
			"activationEvent": "onLanguage:dart"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Cannot call write after a stream was destroyed"
		},
		{
			"name": "Error",
			"message": "Cannot call write after a stream was destroyed"
		},
		{
			"name": "Error",
			"message": "Cannot call write after a stream was destroyed"
		},
		{
			"name": "Error",
			"message": "Cannot call write after a stream was destroyed"
		},
		{
			"name": "Error",
			"message": "Cannot call write after a stream was destroyed"
		}
	]
}
```

**Comment by DanTup** [comment]
@MrHallows can you give more information about what you were doing and what you saw then this issue occurred?

**Comment by MrHallows** [comment]
> 
> 
> @MrHallows can you give more information about what you were doing and what you saw then this issue occurred?

Of course. I ran the `flutter run` command (using the embedded terminal in Vs Code) and while awaiting the build's completion, the Dart Analyzer crashed. I'm not sure why exactly, but I'm currently scanning the log to see if I can find what the issue was.

**Comment by MrHallows** [comment]
Here's where the error occurred:
```console
[4:14:41 AM] [General] [Info] Analyzer:Startup timing: 1118ms
[4:14:48 AM] [General] [Info] Checking 1 projects for supported platforms
[4:14:49 AM] [General] [Info] Supported platforms for the workspace are ios, android
[4:15:47 AM] [Analyzer] [Error] illegal state - object is disposed
Error: illegal state - object is disposed
```

**Comment by MrHallows** [comment]
@DanTup I'm thinking the crash may have been due to a RAM issue on my end, so I'm closing this issue. I will reopen it if this occurs once again and the source proves to be a direct issue with the extension, but I don't believe that will be necessary. I appreciate your help!
