### ISSUE TITLE
Issue on Website (Commands)

### ISSUE THREAD

**Issue by MrHallows** [Dart-Code/Dart-Code#2888]
I found an issue on http://dartcode.org/docs/commands/.

Nothing crazy, just noticed that in the [Dart: Capture Logs](https://dartcode.org/docs/commands/#dart-capture-logs) section, the hyperlink for `/docs/logging/` is set to this target URL, which leads to a 404 (I'm guessing the page was moved and the link wasn't updated by accident): [https://dartcode.org/docs/commands/logging](https://dartcode.org/docs/commands/logging).

The correct URL ([https://dartcode.org/docs/logging](https://dartcode.org/docs/logging)) loads as expected.

**Comment by DanTup** [comment]
Good catch! Fixed in https://github.com/Dart-Code/Website/commit/677d5f2c07651155aafe3dc22fc6295c96404fde. Thanks!
