### ISSUE TITLE
Dart and Flutter language server runs while opening any project

### ISSUE THREAD

**Issue by NoelJacob** [Dart-Code/Dart-Code#2890]
**Describe the bug**
Flutter language server is always running, for any language, file, and in empty VS Code.

**To Reproduce**
1. Without opening any dart/flutter files
2. Go to 'Help/Open Process Explorer'

**Expected behaviour**
The language server only runs for flutter/dart files.

**Screenshots**
<img src="https://i.imgur.com/0rQqq8C.png">

**Versions (please complete the following information):**
 - VS Code version: 1.50.0-insider
 - Dart extension version: 3.15.1
 - Dart/Flutter SDK version: Flutter version 1.19.0-4.1.pre

**Comment by DanTup** [comment]
This appears to have come in with VS Code 1.50. I've opened https://github.com/microsoft/vscode/issues/108578 and am hoping it's a big that'll be fixed in VS Code, otherwise we'll need to try to find a reasonable way around this.

**Comment by DanTup** [comment]
This has been fixed by VS Code and will be in the Insiders release tomorrow, and presumably the next stable release (in a week or two?). I'll do some testing tomorrow to confirm it's definitely fixed, and if not follow up with them on the issue linked above.
