### ISSUE TITLE
renaming a library fails to refactor imports

### ISSUE THREAD

**Issue by bsutton** [Dart-Code/Dart-Code#2893]
In the vscode file explorer view you can rename a library by selecting the library and the opening the context menu and choosing 'rename'.

Previously once you renamed a library all of the other libraries that imported that library would be updated to use the new library name.

The imports are no longer being updated.

The same goes if you move a library between directories i.e. the imports are no longer updated.

**Comment by DanTup** [comment]
Are you using the LSP preview? That doesn't work in LSP yet, it's blocked on the LSP spec getting support for the necessary events which I've got a PR open for at https://github.com/microsoft/language-server-protocol/pull/1074.

**Comment by bsutton** [comment]
I don't believe so. I've just uninstalled flutter/dart-code and then re-installed the standard flutter extension from the market place which re-installed dart-code.

The same problem persists.

**Comment by DanTup** [comment]
@bsutton could you try capturing a log?

- Run the **Dart: Capture Logs** command (leave everything ticked and just hit OK)
- Rename the file
- Click **Cancel** on the logging dialog

Note: The log may contain parts of your source code. You can mail it to logs@dartcode.org or attach it here.

It's also worth double-checking this option is ticked if you haven't already (though I think it should be by default):

<img width="976" alt="Screenshot 2020-10-26 at 13 52 58" src="https://user-images.githubusercontent.com/1078012/97180925-9b1d8800-1792-11eb-92a5-95bdb9419414.png">
