### ISSUE TITLE
Flutter icon previews don't show up in code completion when using LSP

### ISSUE THREAD

**Issue by BRTZL** [Dart-Code/Dart-Code#2896]
**Describe the bug**
Some icon previews do not appear even tho the original data is not contaminated. That started happening after the 1.20.0 update. Also its not happening in original icons, only happening in outlined, rounded, sharp etc. icons (styled).

Also in last image, after the long time period of coding you can see lps is broken.

**Expected behavior**
Icon data to show up like in first image.

**Screenshots**
<img width="835" alt="Screen Shot 2020-10-21 at 21 56 28" src="https://user-images.githubusercontent.com/35866177/96770642-4a500d00-13e9-11eb-8c84-6f212a8cc02e.png">
<img width="805" alt="Screen Shot 2020-10-21 at 21 56 24" src="https://user-images.githubusercontent.com/35866177/96770650-4cb26700-13e9-11eb-95ec-56c407931fd5.png">
![image](https://user-images.githubusercontent.com/35866177/96770656-4de39400-13e9-11eb-91c7-5b92630fb429.png)

**Versions (please complete the following information):**
 - VS Code version: 1.50.1
 - Dart extension version: 3.15.1
 - Dart/Flutter SDK version: 2.10.2/1.22.2

**Comment by DanTup** [comment]
Thanks for the report - the middle screenshot is currently expected for LSP. We don't have a way to inject the icons on the client like we do pre-LSP. I have some ideas for this, but it's a little complicated.

I'm not sure what's happened in the third screenshot though - are you able to reproduce this? The text in there looks like it's coming from VS Code, but I don't understand why. If you can repro, can you file another issue with steps and I can try to repro. Thanks!

**Comment by BRTZL** [comment]
Hi, I will try to reproduce but not sure that I can, for me it happens randomly.

Thanks for the answer.

**Comment by DanTup** [comment]
Idea: We may be able to handle this using LSP middleware until there's a better solution.
