### ISSUE TITLE
Extension causes high cpu load (dart analyzer slow down my laptop)

### ISSUE THREAD

**Issue by NitelPhyoe** [Dart-Code/Dart-Code#2900]
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `3.15.1`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.50.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\NITELP~1\AppData\Local\Temp\Dart-Code.dart-code-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

[Dart-Code.dart-code-unresponsive.cpuprofile.txt](https://github.com/Dart-Code/Dart-Code/files/5423296/Dart-Code.dart-code-unresponsive.cpuprofile.txt)

**Comment by diver2** [comment]
I'm having the same here. Dart-Code is driving my CPU to huge levels. this is recent.
I was on 3.15.1 - I switched back to 3.13 in the meantime

**Comment by DanTup** [comment]
Thanks for the report. The CPU profile shows a lot of time spent building completion items. Could you try switching to the LSP implementation? That will become default in the future, and should improve the performance for large completion lists.

You can enable it in your VS Code user settings (requires a reload of VS Code afterwards):

<img width="995" alt="Screenshot 2020-10-26 at 09 30 13" src="https://user-images.githubusercontent.com/1078012/97155974-fb4e0300-176d-11eb-94c1-c34831fc8d63.png">

Please let me know if you still have issues when using LSP. Thanks!

**Comment by NitelPhyoe** [comment]
Thanks @DanTup. It seen like fix my problem i currently don't feel any lag while coding .

**Comment by DanTup** [comment]
Glad to hear! That version will soon become the default (and eventually only) option, so I'd recommend sticking on it in the meantime.
