### ISSUE TITLE
Dart terminated

### ISSUE THREAD

**Issue by basha97** [Dart-Code/Dart-Code#2905]
Dart is terminated every couple of minutes in both android studio and vscode after upgrading new flutter version ( Channel stable, 1.20.4 )

**Comment by DanTup** [comment]
Are on you Windows, and does this happen when you run a Flutter app?

If so this is likely the same as https://github.com/Dart-Code/Dart-Code/issues/2814 (which although is in this issue tracker, is an SDK issue so could occur in both editors).

If not, can you let me exactly what you're seeing in both IDEs? In VS Code when the analyzer terminates there should be a "show log" button. The last few lines of that log might be useful to understand what's happened. Thanks!
