### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by BrianMwas** [Dart-Code/Dart-Code#2906]
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `3.15.1`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.50.1

[Dart-Code.dart-code-unresponsive.cpuprofile.txt](https://github.com/Dart-Code/Dart-Code/files/5443858/Dart-Code.dart-code-unresponsive.cpuprofile.txt)

**Comment by DanTup** [comment]
Thanks for the trace! The CPU profile shows a lot of time spent building completion items. Could you try switching to the LSP implementation? That will become default in the future, and should improve the performance for large completion lists.

You can enable it in your VS Code user settings (requires a reload of VS Code afterwards):

<img width="995" alt="Screenshot 2020-10-26 at 09 30 13" src="https://user-images.githubusercontent.com/1078012/97155974-fb4e0300-176d-11eb-94c1-c34831fc8d63.png">

Another option would be to disable the auto-import completions, however using LSP is probably preferable, as that's a nice feature.

Please let me know if you still see the issue when using LSP. Thanks!

**Comment by BrianMwas** [comment]
Hi @DanTup  I apologize for keeping you on wait but I did take your recommendation but apparently, it did not work so I chose to use IntelliJ and it has not failed since.

**Comment by DanTup** [comment]
If you can reproduce the issue with LSP enabled, I'd be interested in a CPU trace again if you can get one. The code in the original trace is not used in LSP, so it's likely not the same issue (unless it was before you restarted - changing the LSP setting does require a reload of VS Code to take affect).

**Comment by aihamhasan** [comment]
Even i had got same problem

**Comment by danielmahon** [comment]
@DanTup Ive been having major performance issues for awhile now too (not sure how long, couple months) but even with everything else disabled, except Flutter, the Dart extension stays at ~80% CPU at idle (without debugger attached) and can go up to 300%+ at times, thats without LSP. With LSP I can't work very long until the analyzer just hangs completely. Let me know what info I can provide to help.

- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `3.17.0`
- Device: `MacBook Pro (15-inch, 2017)`
- Processor: `2.9 GHz Quad-Core Intel Core i7`
- Memory: `16 GB 2133 MHz LPDDR3`
- OS Version: `macOS Big Sur 11.0.1`
- VSCode version: `1.51.1`

```
CPU %	Memory (MB)	PID	Name
0	115	44117	code main
0	49	44120	     gpu-process
0	33	44122	     utility
0	262	44123	     window (settings.json — ctcs (Workspace))
0	0	44409	         /usr/local/bin/bash -l
0	82	44434	         extensionHost
0	49	44846	             /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=44434
80	164	44879	             /Users/daniel/Projects/flutter/bin/cache/dart-sdk/bin/dart /Users/daniel/Projects/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --client-id=VS-Code --client-version=3.17.0 --instrumentation-log-file=/Users/daniel/dartAnalyzerInstrumentation.txt
0	0	44880	             bash /Users/daniel/Projects/flutter/bin/flutter daemon
2	147	44895	                 /Users/daniel/Projects/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev --packages=/Users/daniel/Projects/flutter/packages/flutter_tools/.packages /Users/daniel/Projects/flutter/bin/cache/flutter_tools.snapshot daemon
0	0	44970	                     /usr/bin/script -t 0 /dev/null xcrun xcdevice observe --both
0	33	44972	                         /Applications/Xcode.app/Contents/Developer/usr/bin/xcdevice observe --both
0	33	44688	         watcherService
0	33	44841	         searchService
0	98	44837	     shared-process
0	66	44838	     window (Process Explorer)
0	0	45250	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

**Comment by danielmahon** [comment]
@DanTup Ive been having major performance issues for awhile now too (not sure how long, couple months) but even with everything else disabled, except Flutter, the Dart extension stays at ~80% CPU at idle (without debugger attached) and can go up to 300%+ at times, thats without LSP. With LSP I can't work very long until the analyzer just hangs completely. Let me know what info I can provide to help.

- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `3.17.0`
- Device: `MacBook Pro (15-inch, 2017)`
- Processor: `2.9 GHz Quad-Core Intel Core i7`
- Memory: `16 GB 2133 MHz LPDDR3`
- OS Version: `macOS Big Sur 11.0.1`
- VSCode version: `1.51.1`

```
CPU % Memory (MB) PID Name
0 115 44117 code main
0 49 44120 gpu-process
0 33 44122 utility
0 262 44123 window (settings.json — ctcs (Workspace))
0 0 44409 /usr/local/bin/bash -l
0 82 44434 extensionHost
0 49 44846 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=44434
80 164 44879 /Users/daniel/Projects/flutter/bin/cache/dart-sdk/bin/dart /Users/daniel/Projects/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --client-id=VS-Code --client-version=3.17.0 --instrumentation-log-file=/Users/daniel/dartAnalyzerInstrumentation.txt
0 0 44880 bash /Users/daniel/Projects/flutter/bin/flutter daemon
2 147 44895 /Users/daniel/Projects/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev --packages=/Users/daniel/Projects/flutter/packages/flutter_tools/.packages /Users/daniel/Projects/flutter/bin/cache/flutter_tools.snapshot daemon
0 0 44970 /usr/bin/script -t 0 /dev/null xcrun xcdevice observe --both
0 33 44972 /Applications/Xcode.app/Contents/Developer/usr/bin/xcdevice observe --both
0 33 44688 watcherService
0 33 44841 searchService
0 98 44837 shared-process
0 66 44838 window (Process Explorer)
0 0 45250 /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

**Comment by DanTup** [comment]
@danielmahon let's start a new issue for your issues as they might not be the same (the initial issue reported here shows a lot of time spent in code that doesn't run for LSP, so if you're seeing issues in LSP it's probably not that).

Some things to include in the new issue or try:

- Whether it occurs in all projects or just one specific problem
- A copy of your pubspec
- Enable the [instrumentation log](https://dartcode.org/docs/logging/#analyzer-instrumentation) and see if anything is being logged during that long period (note: this file may get very big, so disabled it once done testing - it will also include parts of your source code, so don't share the whole thing publicly if your project is private)

**Comment by danielmahon** [comment]
@DanTup will do, is there something to visually parse/inspect that log?

**Comment by DanTup** [comment]
> is there something to visually parse/inspect that log?

Afraid not - though in the first case I'm interested in whether anything is being logged during that long period (and if not, what the last few lines before it/first few after, are).
