### ISSUE TITLE
LSP: does not use the dart line length setting when formatting dart files

### ISSUE THREAD

**Issue by maks** [Dart-Code/Dart-Code#2907]
**Describe the bug**
When LSP is enabled code formatting does not use the dart line length setting when formatting dart files and seems to just default to wrapping at 80 chars. Setting both in either or both user and workspace settings didn't seem to have an effect.

**Versions (please complete the following information):**
 - VS Code version: 1.50.1
 - Dart extension version: 3.15.1
 - Dart/Flutter SDK version: 1.20

**Comment by DanTup** [comment]
Could you reproduce this with the [analysis server log](https://dartcode.org/docs/logging/#analyzer) enabled? The log will contain parts of source files (and be much larger for large projects) so it's best to capture using a small sample project (eg. with `flutter create`).

Thanks!

**Comment by maks** [comment]
Sorry @DanTup I dropped the ball on this and only now had a chance to capture the log for you.
I captured the log using a `flutter create` project where I went in edited the main.dart to have one of the Text widgets contain a long string that made that line over 80 chars but less than 120 which is what I have the margin set to.
[analyzerlog1.txt](https://github.com/Dart-Code/Dart-Code/files/5610068/analyzerlog1.txt)

**Comment by DanTup** [comment]
@maks in that log file, it seems to show `lineLength` being sent to the server as `80`:

```js
{
	"id": 1,
	"method": "workspace/configuration",
	"params": {
		"items": [
			{
				"section": "dart"
			}
		]
	},
	"jsonrpc": "2.0"
}

{
	"jsonrpc": "2.0",
	"id": 1,
	"result": [
		{
			// ...
			"lineLength": 80,
			
```

Can you check your settings to see whether you might have it set up multiple times, or if it may be set at the workspace level overriding the user setting?

**Comment by maks** [comment]
Hmm I'm pretty sure I have 120 set as global config, heres my settings.json (with a few settings removed for privacy)
I would expect ` "editor.wordWrapColumn": 120` to be setting the wrap for LSP too? I dont have any per-project settings as this was brand new `flutter create` made project. 

```
{
    "editor.minimap.enabled": false,
    "files.autoSave": "onFocusChange",
    "diffEditor.renderSideBySide": false,
    "explorer.confirmDelete": false,
    "[dart]": {
        "editor.formatOnSave": true,
        "editor.formatOnType": false,
        "editor.rulers": [
            120
        ],
        "editor.selectionHighlight": false,
        "editor.suggest.snippetsPreventQuickSuggestions": false,
        "editor.suggestSelection": "first",
        "editor.tabCompletion": "onlySnippets",
        "editor.wordBasedSuggestions": false
    },
    "diffEditor.ignoreTrimWhitespace": false,
    "git.allowForcePush": true,
    "editor.formatOnSave": true,
    "dart.debugExternalLibraries": true,
    "dart.debugSdkLibraries": true,
    "dart.embedDevTools": false,
    "dart.flutterAndroidX": true,
    "editor.wordWrapColumn": 120,
    "workbench.activityBar.visible": true,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "editor.fontFamily": "'Fira Code', monospace",
    "window.zoomLevel": 0,
    "dart.previewBuildRunnerTasks": true,
    "dart.useKnownChromeOSPorts": false,
    "editor.fontLigatures": true,
    "dart.buildRunnerAdditionalArgs": [
        "--delete-conflicting-outputs"
    ],
    "dart.previewHotReloadOnSaveWatcher": true,
    "dart.previewLsp": true
}
```

Also just in case my versions are:
```
[flutter] flutter doctor -v
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.24.0-10.2.pre at XXXXXXXXXXXXXXXXXXX
    • Framework revision 022b333a08 (11 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)
```

**Comment by DanTup** [comment]
@maks the `dart.lineLength` setting does not seem to be set in the config you pasted. You should be able to add this:

```js
"dart.lineLength": 120,
```

Let me know if this doesn't help!

**Comment by mentoc3000** [comment]
I'm having the same issue. I just enabled the Preview LSP option and my files are being auto formatted to 80 character line lengths even though I have set `dart.lineLength` to 120 in both the user and workspace settings.

[analyzer.txt](https://github.com/Dart-Code/Dart-Code/files/5616270/analyzer.txt)

VS Code version: 1.51.1
Dart extension version: 3.16.0
Dart/Flutter SDK version: 1.20.4

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel unknown, 1.20.4, on Microsoft Windows [Version 10.0.19042.630], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.51.1)
[√] Connected device (1 available)

• No issues found!
```

**Comment by DanTup** [comment]
@mentoc3000 the change to support `dart.lineLength` has not made a stable Flutter build yet. You need to be dev/master (and perhaps beta?) to have it. @maks was using `1.24.0-10.2.pre` in the most recent log file, so I think these are different issues.

**Comment by maks** [comment]
Thanks @DanTup ! And my apologies, I wasn't aware of the `dart.lineLength` setting for LSP, I only was looking at `editor.wordWrapColumn` which I was using pre-LSP.

I just tested with `dart.lineLength` set globally with Flutter SDK Beta channel and it works fine  👍
