### ISSUE TITLE
Sort Members on save

### ISSUE THREAD

**Issue by NatoBoram** [Dart-Code/Dart-Code#2908]
**Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

I want to strictly follow conventions, whatever they might be. One example of such convention is the sorting of members in Dart/Flutter. To follow it, I have to run the "Sort Members" action.

**Describe the solution you'd like**
> A clear and concise description of what you want to happen.

Ideally, I would like this action to be used by my editor whenever I save.

**Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
> Add any other context or screenshots about the feature request here.

In the command palette, there's "Sort Members".

![image](https://user-images.githubusercontent.com/10495562/97378033-bf16c180-1897-11eb-84a4-2171db4ea5c5.png)

**Comment by DanTup** [comment]
If you're using the LSP preview (which if you're not, I would recommend - it's enabled with the `dart.previewLsp` setting then reloading Code - it'll become default in an upcoming release), this is possible!

There's a setting in VS Code called `editor.codeActionsOnSave` that can run code actions whenever you save. The code action that triggers this command is called `source.sortMembers`. So if you add this to your VS Code settings:

```js
"editor.codeActionsOnSave": {
	"source.sortMembers": true,
},
```

Then it should run on every save.

Let me know if you have any problems with this!

**Comment by NatoBoram** [comment]
Thanks, it works!
