### ISSUE TITLE
Publish to open-vsx.org

### ISSUE THREAD

**Issue by Surendrajat** [Dart-Code/Dart-Code#2912]
**Is your feature request related to a problem? Please describe.**
Related to #2254, Since Micro$oft cleverly denies access to its extension marketplace to anything other than its own release of VSCode binaries(How open of you!), [open-vsx](https://open-vsx.org) by eclipse foundation is the alternative extension store for VSCodium and Thea(or self-compiled VSCode). We've been updating Flutter and Dart extensions there, by downloading and uploading manually for a while. But it's a public namespace, anybody can publish a malicious extension too.

**Describe the solution you'd like**
Please [claim the ownership](https://github.com/eclipse/openvsx/wiki/Namespace-Access#how-to-claim-a-namespace) of the namespace Dart-Code and [publish](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) both extensions to open-vsx.org.

**Describe alternatives you've considered**
Downloading .vsix and uploading myself.

**Additional context**

**Comment by DanTup** [comment]
I've [opened an issue](https://github.com/eclipse/open-vsx.org/issues/195) to claim the publisher namespace and will look into publishing future releases there too. Thanks!

**Comment by Surendrajat** [comment]
That'll be awesome. Thank you.

**Comment by DanTup** [comment]
Today's releases have been published to open-vsix. For now this is a manual step, though I've updated the title of #2254 to include publishing as well generating the files.

I'm not sure which (if any) editors use open-vsx for their extensions yet, but if you do have any problems please let me know!

**Comment by Surendrajat** [comment]
[VS Codium](https://vscodium.com/) and [GitPod](https://www.gitpod.io/) are using open-vsx already. [code-server](https://github.com/cdr/code-server) folks are evaluating it.
Anyways nice to see the latest version there. Hope it'll be automated soon.
