### ISSUE TITLE
message is cut off in error dialog: "Could not find a Dart SDK..."

### ISSUE THREAD

**Issue by skybrian** [Dart-Code/Dart-Code#293]
With the VS Code window open to a reasonable width, I see:

```
Could not find a Dart SDK to use. Please set FLUTTER_ROOT, run flutter to download an SDK or configure the 'd...
```

Maybe add some newlines? (Does the error dialog support multiple lines?)

VS Code 1.12.1 Linux.

**Comment by DanTup** [comment]
You need an ultrawide screen! ;)

I'm not sure about newlines, but if not I can reword it. I do have a 21:9 monitor so probably wouldn't have noticed - I'll try to remember this when writing other errors/warnings in future!

**Comment by DanTup** [comment]
This message was simplified as part of #296.
