### ISSUE TITLE
Test Tree shows duplicate nodes after running tests multiple times concurrently

### ISSUE THREAD

**Issue by haashem** [Dart-Code/Dart-Code#2934]
**Describe the bug**
Test summary panel, shows incorrect test groups count after a few run

**To Reproduce**
1. Go to Test Panel
2. Click on Run or Debug buttons rapidly 

**Expected behavior**
Test group count should not change 

**Screenshots**
<img width="1217" alt="Screen Shot 2020-11-04 at 8 10 37 PM" src="https://user-images.githubusercontent.com/3206748/98203406-72914d00-1f4d-11eb-9153-a2a9c4027d0a.png">

**Versions (please complete the following information):**
 - VS Code version: 1.50.1
 - Dart extension version: 3.16
 - Dart/Flutter SDK version: 1.22.2

**Comment by DanTup** [comment]
I'm struggling to reproduce this - can you confirm how you're re-running the test? Which run/debug links? How consistently does it occur?

**Comment by haashem** [comment]
Try to click on group test rapidly, multiple times click on test before previous group test has finished. you will see the strange bug

**Comment by DanTup** [comment]
Aha, got it - I added a delay in my tests to force them to overlap and it happens. I'll take a look, thanks!
