### ISSUE TITLE
Customize position of the constructor when creating constructor for the final fields

### ISSUE THREAD

**Issue by orestesgaolin** [Dart-Code/Dart-Code#2937]
**Is your feature request related to a problem? Please describe.**

Dart Code allows to create constructor for the final fields. It puts it by default below the fields. 

![CleanShot 2020-11-05 at 18 17 22](https://user-images.githubusercontent.com/16854239/98274044-41d40680-1f93-11eb-9d30-7683ac1f8991.gif)

**Describe the solution you'd like**

I would like to be able to customize position of the constructor when it's generated. It could be either set by the analyzer lint rule [sort_constructors_first](https://dart-lang.github.io/linter/lints/sort_constructors_first.html) or by a switch in extension settings.

**Describe alternatives you've considered**

Manually moving constructor to the top of the class.

**Additional context**

There's a popular lint rule [sort_constructors_first](https://dart-lang.github.io/linter/lints/sort_constructors_first.html) that enforces ordering constructor at the top.

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/899654d51574e0fc9d1e7a0f62db9e0cc590d73a. As it's in the language server, it'll show up in a future Dart/Flutter SDK release (not the VS Code extension release).
