### ISSUE TITLE
Support debugOnDevice in subfolders

### ISSUE THREAD

**Issue by HerrNiklasRaab** [Dart-Code/Dart-Code#2938]
I am using the the following code lens configuration, but when want to start the test in the file "dashboard_screen_test.dart" I can't because the test file is in a package and the package doesn't have the TargetPlatform.ios (see the error in the console). The package is in the packages folder of the application instead (see the tree structure)

Should we support some kind of way to support the "deubgOnDevice" codelens in flutter librarys?

![image](https://user-images.githubusercontent.com/28401593/98281600-3d145000-1f9d-11eb-9bd8-a88c2026a002.png)

**Comment by DanTup** [comment]
"Run test on device" just calls `flutter run -t test/foo_test.dart`. I don't think there's any way to run a test on a device unless it's inside a project that has an app (so it can be built and installed on the app). I think support for this would need to come from Flutter.

Have you tried running `flutter create .` inside the library folder to see if that creates enough of the app to be able to run this way?

**Comment by HerrNiklasRaab** [comment]
I am not working on the project, with this setup and it's rather an edge case so I think we can close this. Thanks anyway!
