### ISSUE TITLE
WSL: build_runner watch doesn't trigger on file updates

### ISSUE THREAD

**Issue by jimmyff** [Dart-Code/Dart-Code#2939]
Hey,
When I run my tasks in my WSL project that watch folders like `pub run build_runner watch` they run once but then done get triggered when the files are updated. 

I'm guessing this is probably an issue with WSL rather than dart-code?

Thanks

**Comment by DanTup** [comment]
It sounds like either an issue with WSL or with `build_runner`. If you can repro this by running `pub run build_runner` from the terminal, it doesn't seem likely the VS Code extension is involved.

I'm not sure how to best figure out if it's WSL or build_runner though.

If you file an issue with WSL/build_runner, please do post a link back here for anyone else that comes across this issue that might be having the same problem. Thanks!
