### ISSUE TITLE
Detect flutter SDK from .packages file

### ISSUE THREAD

**Issue by skybrian** [Dart-Code/Dart-Code#294]
FYI, for a newly-generated Flutter project (via `flutter create`), the Dart SDK's location is implicitly recorded in this file:

```
.idea/libraries/Dart_SDK.xml
```

However, parsing the file might not be all that easy to do. Maybe flutter could generate another file for VS Code to use?

@devoncarew

**Comment by DanTup** [comment]
Isn't that folder specific to the IDEA IDE? If so, why does `flutter create` create it?

How common is it for people to have the Flutter SDK set in the `FLUTTER_ROOT` env variable? If that's set, Dart Code will find it automatically.

I'll be honest, I'm really unfamiliar with the flutter workflow.. When I get some time I hope to sit down and create/deploy Hello World so that I understand it a little better. I did look for videos showing this whole workflow but couldn't find anything (if you know of any, please do send links!).

**Comment by DanTup** [comment]
Also; if the flutter SDK is in `PATH` we should also find it?

**Comment by DanTup** [comment]
Also, I can't find any code referencing `Dart_SDK.xml` [in the repo](https://github.com/flutter/flutter/search?utf8=%E2%9C%93&q=%22Dart_SDK.xml%22&type=). Do you know where the code for this is? (I scanned through the `flutter create` command code but couldn't see anything like this either).

**Comment by skybrian** [comment]
Yes, the files in the `.idea` directory are for IDEA. They are generated because the Flutter team and the Flutter plugin team are working together. (I'm working on the Flutter plugin.)

I don't think there's any reason why we can't do something for VS Code too; maybe a simple JSON file with a "dart_sdk" key would be more IDE-independent?

The templates for `flutter create` are at:
 at https://github.com/flutter/flutter/tree/master/packages/flutter_tools/templates/create

You can see the one for `Dart_SDK.xml` in this directory:
https://github.com/flutter/flutter/tree/master/packages/flutter_tools/templates/create/.idea/libraries

Most flutter users have probably not started using Flutter yet :-) But you can probably assume most people will start by either using `flutter create` or by using IDEA, which runs `flutter create` behind the scenes. That's what the [official instructions](https://flutter.io/getting-started/) say, and there are a lot of files in a Flutter project, so it's not that practical to set them up all by hand. (I don't think anyone is setting `FLUTTER_ROOT` since the instructions don't say you should.)

(Another approach might be to look for a `flutter` command in the user's PATH, but it won't work for weird people like me who use an alias instead, and it's not cross-platform.)

*With one exception: Bazel is different; the contents of the Flutter SDK directory are in multiple places. But we can ignore that to start with.

**Comment by DanTup** [comment]
> For VS Code, maybe a simple JSON file with a "dart_sdk" key would be more IDE-independent?

I have no real preference; as long as I can parse it and it's stable, I could read it. I still think it's weird creating an `.idea` folder though - if I'm a flutter use that doesn't use IDEA, why should I have its folder on my disk? :/ It would be better if `flutter create` didn't create *any* IDE-specific stuff?

> An alternate approach might be to look for a flutter command in the user's PATH, but it won't work for weird people like me who use an alias instead, and it's not cross-platform

I already added this in the current release; if it can find `flutter` or `flutter.bat` in your `PATH` it'll get picked. If you don't think this is working, please raise a case. If you can provide details of what you mean by alias I can see if I can handle that too (if it's just a command alias in your shell, probably not; but if you mean a symlink or something, maybe that can work).

How likely is it that users will have `flutter` in their `PATH`? If high (I would've thought so if they expect to be able to run `flutter create` from where they want to create their projects) then maybe the behaviour of the existing version is good enough? 

> Within IDEA we have File->New->Project then choose Flutter. We explicitly ask for the Flutter SDK's location, and then run flutter create behind the scenes. (Perhaps VS Code could do that too?)

VS Code doesn't have any ability to create new projects; it's expected that you'd use command lines like `flutter create`.

**Comment by skybrian** [comment]
I use a bash alias.

```
alias flutter="$HOME/software/flutter/bin/flutter"
```

I guess that's lower priority since it's off the beaten path. The official instructions say to add `flutter/bin` to your path. I don't do that because I use more than one flutter SDK for testing and I want to make sure we don't accidentally start depending on the user's PATH.

I created a bug to discuss config file situation further: https://github.com/flutter/flutter/issues/10096

**Comment by DanTup** [comment]
I don't think it'll be easy to cater for that :(

>  want to make sure we don't accidentally start depending on the user's PATH

I'm not familiar with Linux, but if one of your scripts just called `flutter` with no path, I presume it wouldn't execute your alias and therefore fail? (If so, I think I understand!).

Any reason you don't set `FLUTTER_ROOT`? It still lets you catch if you depend on `PATH` but also gives a way for tooling to know where the SDK is without having a specific file in each project. (I'm not saying you should, I'm just curious why not; the more I understand, the better! :-))

**Comment by skybrian** [comment]
Not an issue for me; I can get it working. At first I didn't realize this was a corner case.

**Comment by DanTup** [comment]
If the idea file is easy for me to parse (I haven't seen it yet) I think it's be worth me just reading as-is. Anything I can to make using Dart Code easier is worth doing. Though it sounds like it points at the Dart SDK inside the Flutter SDK, not the Flutter SDK. Can I make assumptions about the `flutter` command being available a few levels up?

**Comment by skybrian** [comment]
Yes, we do the same in the IDEA plugin.

But the tricky bit is that IDEA sometimes stores "path variables" in the XML. See:
https://www.jetbrains.com/help/idea/2017.1/path-variables-2.html

It might not be possible to calculate the Dart SDK's path in all cases.

**Comment by DanTup** [comment]
I guess I can try to read it (in the case where it was created by `flutter create` it will have a path without variables) and just ignore it if it's nonsense. The more places I can look, the less likely we'll give the user an error instead of just working.

Btw; doesn't using this file have the same issue as if the path was in pubspec.yaml - it won't work across machines, so if this file gets committed it'll confuse other developers? Or is this file generally not committed?

(In VS Code there's a `.vscode` folder that lets you store settings, but it's [often checked in](https://github.com/Dart-Code/Dart-Code/blob/master/.vscode/settings.json) because it can set format settings (etc.) for the project).

**Comment by DanTup** [comment]
Change to this (from https://github.com/flutter/flutter/issues/10096#issuecomment-301890827):

- Current folder (eg. check for `./bin/flutter(.bat)` and `./bin/cache/dart-sdk/bin/dart(.bat)`) 
- `.packages` file; `flutter:` or `sky_engine:`
- `.idea/libraries/Dart_SDK.xml` (if parseable)
- `FLUTTER_ROOT` env variable
- All folders in `PATH`, in order
