### ISSUE TITLE
VS Code Flutter need New Project Offline

### ISSUE THREAD

**Issue by recepozen54** [Dart-Code/Dart-Code#2941]
Hi, I am a Teacher. I have some problems about new Project online because my internet is bad.

I need a new Command in Visual Studio Code. 
Normally 
Flutter: New Project -> making Flutter create <projectname> and pub get
I need
Flutter: New Project offline -> so run this commands when create project. 
flutter create --offline <projectname> and pub get --offline 

Please add this to Flutter plugin. 
sorry for my english ,

**Comment by DanTup** [comment]
Thanks for the request! There's already a setting you can use that will add the `--offline` switch to **Flutter: New Project** which you can find in the VS Code User Settings:

<img width="1010" alt="Screenshot 2020-11-09 at 11 46 41" src="https://user-images.githubusercontent.com/1078012/98537536-50ffd080-2281-11eb-9e0d-5627d49c3350.png">

Please let me know if this doesn't solve the problem. Thanks!
