### ISSUE TITLE
Autocompletion for graphql queries in dart files

### ISSUE THREAD

**Issue by chandu0101** [Dart-Code/Dart-Code#2943]
Auto completion for graphql  queries in dart files.

```dart
dynamic gql(String query) {
}

final getTodos = gql("""
       query myQuery {
       // want autocompletion,error reporting ,..etc 
       }                        
 """
```
similar to https://github.com/graphql/vscode-graphql#gqlgraphql-tagged-template-literal-support-for-tsx-jsx-ts-js

I want to implement this feature but don't know where to start , can you please link me to  some examples/docs ..

**Comment by DanTup** [comment]
> I want to implement this feature but don't know where to start , can you please link me to some examples/docs ..

I'm afraid I don't know much about how that extension works so this would be a better question for their repo. I found this:

https://github.com/graphql/vscode-graphql#simple-example

Though it's not clear if it's as simple as just adding `.dart` to that list, or if their extension needs to understand the syntax of the language. I couldn't find any info in their readme or issue tracker, so I would recommend starting with their repo asking for instructions on how to embed it in another language (that isn't supported out of the box).

**Comment by chandu0101** [comment]
thanks for reply, i think i gave wrong example , the one i am looking for is https://github.com/Quramy/ts-graphql-plugin

**Comment by DanTup** [comment]
It looks like that one is implemented as a plugin to the TypeScript language server. Doing something similar for Dart would likely mean implementing a Dart Analyzer plugin (see https://github.com/dart-lang/sdk/blob/master/pkg/analyzer_plugin/doc/tutorial/tutorial.md), but unless there are existing graphql parsers in Dart, that might be significant effort.

It may be simpler to see if any of the existing VS Code extensions support graphql embedded in other files (for example Dart), as most of the other work (parsing the query, figuring out what to show in completion etc.) is already done.
