### ISSUE TITLE
Migrate "pub get" to "dart pub get"

### ISSUE THREAD

**Issue by jonasfj** [Dart-Code/Dart-Code#2944]
The top-level `pub` command is scheduled for deprecation in favor of `dart pub`.

We added `dart pub` in version `2.10.0`, so it might still be necessary to call `pub get` for some older versions of the Dart SDK.
However, we plan to insert a deprecation warning in the top-level `pub` command, in Dart `2.12.0` (next stable release of the Dart SDK). Hence, to avoid users experiencing a deprecation warning in `pub get` output, it would be preferable to migrate to `dart pub get` now.

See also: https://github.com/dart-lang/pub/issues/2736

**Comment by DanTup** [comment]
@jonasfj will do! I presume it's fine to use "dart pub get" for both Flutter and non-Flutter projects? (right now we have to pick between `pub get` and `flutter pub get` to avoid an error when fetching for Flutter projects).

**Comment by jonasfj** [comment]
@DanTup I think it's best to use `flutter pub get` for flutter projects... It does some setup steps required for  plugins and other things.

**Comment by DanTup** [comment]
Got it - thanks! I wasn't sure if the reason for this change was to consolidate them both.

BTW, I presume this applies to *all* `pub` commands (we also call `pub upgrade`, `pub outdated`, `pub global list`, `pub global run`)?

**Comment by jonasfj** [comment]
Yes, all `pub` commands should use `dart pub` :)

There is also `dart test` now, for running tests.

**Comment by DanTup** [comment]
> There is also `dart test` now, for running tests.

Currently we're running tests by running `dart [pub snapshot path]`. This is to get the same pause-on-start behaviour as when running non-tests on the VM (so we don't need to have separate code to handle this). This isn't ideal, but it seemed better than having to maintain separate code to handle this.

We used to set `DART_VM_OPTIONS=--pause_isolates_on_start=true` but that [had the issue](https://github.com/Dart-Code/Dart-Code/issues/1038) of cascading to child processes too, which can mess up user tests that spawn Dart instances. There's a little discussion about that in https://github.com/dart-lang/pub/issues/1018.

So for now, unless you think there will be breakage, I'll leave the tests as-is but fix up the rest.
