### ISSUE TITLE
Show `showSemanticsDebugger` toggle menu in VS Code command palette

### ISSUE THREAD

**Issue by orestesgaolin** [Dart-Code/Dart-Code#2946]
**Is your feature request related to a problem? Please describe.**
Flutter's `MaterialApp` allows to set `showSemanticsDebugger` to display clean `Semantics` overview of the app. Please see example.

![image](https://user-images.githubusercontent.com/16854239/98608654-f64f8e80-22eb-11eb-84c8-bf39a0b5db42.png)

**Describe the solution you'd like**
It would be great to be able to toggle this option similarly to _Toggle Debug-Mode Banner_ in the VS Code command palette

**Describe alternatives you've considered**
The only alternative is to set it on MaterialApp/WidgetsApp

**Additional context**
It would help make this feature more discoverable by the users

**Comment by DanTup** [comment]
@jacob314 do you know if there's a service toggle for this? I looked but couldn't find one, only the boolean on the app widgets.

**Comment by jacob314** [comment]
I don't think there is currently a toggle for this but there used to be. I'm not sure why it was removed.

**Comment by DanTup** [comment]
@jacob314 do you think it's worthwhile having? I'm not sure what's involved in implementing it (or if it was removed, if there was a reason for it).

**Comment by jacob314** [comment]
I don't think it is worthwhile having. People should just enable talkback/voiceover on their device and test with real a11y services. The semantics debugger risks misleading people that the app is accessible when it isn't. It is better to verify with the real accessibility tools.

**Comment by DanTup** [comment]
Got it - sounds like there's nothing to do here then. Thanks!
