### ISSUE TITLE
Exceptions not showing up in debug console

### ISSUE THREAD

**Issue by nekoto-kun** [Dart-Code/Dart-Code#2947]
**Describe the bug**
When trying to debug a function using breakpoints below a line that contains type casting like below:

```
  1   Future<List<MeModel>> _recentMenuList() async {
  2     final recentList = ...
  3     final extracted = json.decode(recentList ?? '{}') as Map<String, String>;
• 4     var availableMenus = ... ? menus : ... ? menus2 : menus3;  // <-- this line has a breakpoint and is not related to the line above
• 5     availableMenus.retainWhere((element) => extracted.containsKey(element.title)); // <-- this line has a breakpoint as well
  6     return availableMenus; // <-- I want to know the result here
  7   }
```

The breakpoints never touched by debugger, **even line no. 4-6** which should run get skipped as well. The entire function then returning ```null``` value . However, if the type cast removed (```as Map<String, String>```), all breakpoints and codes in that function working as expected.

**Expected behavior**
The breakpoint on the line with type casts should work as it should be.

**Versions (please complete the following information):**
 - Version: 1.51.0 (system setup)
 - Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
 - Date: 2020-11-05T18:18:23.642Z
 - Electron: 9.3.3
 - Chrome: 83.0.4103.122
 - Node.js: 12.14.1
 - V8: 8.3.110.13-electron.0
 - OS: Windows_NT x64 10.0.19041
 - Dart extension version: 2.10.3
 - Dart/Flutter SDK version: 1.22.3

**Comment by DanTup** [comment]
Are you able to working sample code I can test with? I tried to make working code from your example, but when using `jsonDecode` where you have `json.decode` it throws on the cast. If this is happening for you, then this would explain why the breakpoints are not hit (though I would expect you'd see the exception displayed somewhere):

<img width="950" alt="Screenshot 2020-11-10 at 11 16 22" src="https://user-images.githubusercontent.com/1078012/98667335-2deb2480-2346-11eb-9ea0-9f5b6b59b3b1.png">

**Comment by nekoto-kun** [comment]
Okay, now I know why I didn't come across the view like yours in the first place. **I had Breakpoints option on All Exceptions disabled** (my fault here, I'm sorry). This was quite frustrating me yesterday since its type only checked on runtime. I'll close this issue from my side. Thank you for your time. 👋

**Comment by DanTup** [comment]
> I had Breakpoints option on All Exceptions disabled

Ah - got it. By default it's break on "uncaught exceptions", but because the Flutter framework catches exceptions this probably wouldn't have triggered in Fluter (whereas I tested in a pure Dart script).

That said - the error *should* still have been printed to the Debug Console, so if you weren't seeing it there - that might be another bug that should be looked at. If you can reproduce it not being printed anywhere, please let me know!

**Comment by nekoto-kun** [comment]
![image](https://user-images.githubusercontent.com/40553075/98884502-c6a6af00-24c2-11eb-9323-d497598b4aa3.png)

Yep, I can confirm that it's never be printed to debug console, even in verbose mode. I only get the exception after I activate Breakpoints options (All and/or Uncaught).

**Comment by DanTup** [comment]
@nekoto-kun I've not been able to reproduce this in a sample app:

<img width="1059" alt="Screenshot 2020-11-12 at 17 50 54" src="https://user-images.githubusercontent.com/1078012/98976759-a7823e80-250f-11eb-8f77-161a7a42362a.png">

Are you able to repro in a small sample app, or strip your app back to something that can be shared?

Thanks!

**Comment by nekoto-kun** [comment]
This should do. The behavior is same as we've discussed before. I have to note that both using ```json.decode()``` from ```dart:convert``` and ```jsonDecode()```  get the same result.

PS: I come across another similar bug when develop this sample app. (Provided in second app below)

<details>
<summary>1st Sample app</summary>

```
import 'dart:convert';

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Debug Debugger\' Bug',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Debug Debugger\' Bug'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Future<dynamic> _getList() async {
    final data = await Future.delayed(Duration(seconds: 3))
        .then((value) => '{"foo":"one","bar":"two"}');
    var decoded = json.decode(data) as Map<String, String>; // this should throw exception into debugger but nothing printed
    print(decoded.toString());
    return decoded;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: FutureBuilder(
          future: _getList(),
          builder: (_, snapshot) {
            if (snapshot.connectionState == ConnectionState.done) {
              if (snapshot.hasData) {
                return Text(snapshot.data.toString());
              }
              return Text(
                'No data received',
                style: TextStyle(color: Colors.red),
              );
            }
            return Text('Please wait');
          },
        ),
      ),
    );
  }
}
```

</details>

<details>
<summary>2nd sample app</summary>

```
import 'dart:convert';

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Debug Debugger\' Bug',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Debug Debugger\' Bug'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Future<dynamic> _getList() async {
    final data = await Future.delayed(Duration(seconds: 3))
        .whenComplete(() => '{"foo":"one","bar":"two"}'); // root of error cause Future returns null
    var decoded = jsonDecode(data) as Map<String, String>; // this should throw exception into debugger but nothing printed
    print(decoded.toString());
    return decoded;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: FutureBuilder(
          future: _getList(),
          builder: (_, snapshot) {
            if (snapshot.connectionState == ConnectionState.done) {
              if (snapshot.hasData) {
                return Text(snapshot.data.toString());
              }
              return Text(
                'No data received',
                style: TextStyle(color: Colors.red),
              );
            }
            return Text('Please wait');
          },
        ),
      ),
    );
  }
}
```

</details>

**Comment by DanTup** [comment]
I ran the first sample, and found that if I had "break on uncaught exceptions" enabled, it would break:

<img width="1285" alt="Screenshot 2020-11-16 at 13 21 09" src="https://user-images.githubusercontent.com/1078012/99257419-ea455e80-280e-11eb-9f94-c80d07979eab.png">

If I disabled it, I do not see the error - however in this case I believe it's because you're using a `FutureBuilder`, where you're supposed to handle the error yourself. The `snapshot` has a `hasError` property that you can use to check for this:

```dart
if (snapshot.hasData) {
  return Text(snapshot.data.toString());
}
if (snapshot.hasError) { // Handle errors here
  return Text('errored');
}
```

This is why the error is not printed in the debug console, as it's being handled by the `FutureBuilder` and not considered an exception.

Hope this makes sense!

**Comment by nekoto-kun** [comment]
Thanks for the clear explanation! I'm sorry I didn't try to fully understand how the```FutureBuilder``` actually works at the first place. I will close this issue since there is no more issue I encounter. Good day 😊

**Comment by DanTup** [comment]
This is an old issue, but in case anyone comes across this in future, TIL that `FutureBuilder` has a [`debugRethrowError` field](https://api.flutter.dev/flutter/widgets/FutureBuilder/debugRethrowError.html) to prevent swallowing these exceptions to help debug!
