### ISSUE TITLE
Migrate test running to "dart run" for tests

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#2950]
From https://github.com/Dart-Code/Dart-Code/issues/2949#issuecomment-724804960

I tried using `dart test`, though I found that with `--pause_isolates_on_start=true` it would be paused but not print the VM Service URI. If I tried adding `--write-service-info=foo.txt` it also didn't write the VM Service info there. I don't know whether those are complicated or simple things to address though.

**Comment by sigurdm** [comment]
I believe these are bugs to be fixed.

**Comment by DanTup** [comment]
@sigurdm @jonasfj thanks for the call! Switching to `dart run test:test` appears to work perfectly! I've got a PR to revert the previous workaround and make that change for >= v2.12 at https://github.com/Dart-Code/Dart-Code/pull/2956. Thanks!
