### ISSUE TITLE
launch.json args not being passed to program in Windows

### ISSUE THREAD

**Issue by tobega** [Dart-Code/Dart-Code#2952]
**Describe the bug**
The "args" from launch.json are not being passed to main (it gets an empty list) in Windows. Works fine on Mac.

**To Reproduce**
1. Create a new project, generate a simple command line app (hello world)
2. Modify main to print "hello $arg" to each of the command-line arguments, as added to the automatically generated launch.json in the "args" field.

**Expected behavior**
That the command line arguments specified in launch.json get passed in as the main program arguments parameter.

**Versions (please complete the following information):**
 - VS Code version: On mac (working): 1.51.0
 - Dart extension version: On mac (working): 3.16.0
 - Dart/Flutter SDK version: On mac (working) 2.10.3

I don't have access to the Windows setup, coaching somebody online, but everything was downloaded fresh yesterday, 11/11/2020. One thing, the Windows dart sdk is not in the default path but was manually located for the vscode extension.

**Comment by DanTup** [comment]
If I've understood correctly, I don't seem to be able to repro this on Windows:

![blocked](https://user-images.githubusercontent.com/1078012/98810564-57c04c00-2417-11eb-88be-ebe1f8f8d25e.png)

Is it possible you can supply the exact project/files you're using, and a log file (captured with the **Dart: Capture Debugger Logs** command)? Thanks!

**Comment by Nyiern** [comment]
[Dart-Code-Log-2020-10-03 18-01-16.txt](https://github.com/Dart-Code/Dart-Code/files/5525598/Dart-Code-Log-2020-10-03.18-01-16.txt)

**Comment by Nyiern** [comment]
[Ny komprimerad mapp.zip](https://github.com/Dart-Code/Dart-Code/files/5525623/Ny.komprimerad.mapp.zip)

**Comment by tobega** [comment]
So above is the requested info if all went well

**Comment by DanTup** [comment]
Thanks! The project that was attached does not appear to have a `launch.json` file in it, and the log file seems to match that, showing no `args`:

```js
[18:01:24] [General] [Info] Debug session starting...
    {
        "name": "Dart ",
        "noDebug": true,
        "request": "launch",
        "type": "dart",
        "groupId": 0,
        "program": "C:\\Users\\ylva\\OneDrive\\Dokument\\kod001\\bin\\kod001.dart",
        "cwd": "C:\\Users\\ylva\\OneDrive\\Dokument\\kod001",
        "dartVersion": "2.10.3",
        "toolEnv": {
            "FLUTTER_HOST": "VSCode",
            "PUB_ENVIRONMENT": "vscode.dart-code"
        },
        "sendLogsToClient": true,
        "args": [],
        "vmAdditionalArgs": [],
        "vmServicePort": 0,
        "dartPath": "C:\\Users\\ylva\\Downloads\\dartsdk-windows-x64-release\\dart-sdk\\bin\\dart.exe",
        "maxLogLineLength": 2000,
        "pubPath": "C:\\Users\\ylva\\Downloads\\dartsdk-windows-x64-release\\dart-sdk\\bin\\pub.bat",
        "pubSnapshotPath": "C:\\Users\\ylva\\Downloads\\dartsdk-windows-x64-release\\dart-sdk\\bin\\snapshots\\pub.dart.snapshot",
        "debugSdkLibraries": false,
        "debugExternalLibraries": false,
        "showDartDeveloperLogs": true,
        "evaluateGettersInDebugViews": true,
        "evaluateToStringInDebugViews": true,
        "debuggerType": 0
    }
```

Could you confirm that you have the `launch.json` in the correct place? It should be in a `.vscode/` folder in the root of your project (which should also be the folder opened in VS Code.. if you open a folder further up the file system, then your `.vscode/` folder would need to be further up, and the `launch.json` would also need to account for that in its `program`/`cwd` fields).

Thanks!

**Comment by tobega** [comment]
Oh, interesting. We just let vscode create the launch.json file so I have no idea why it would not have ended in the correct place. Will look for that at the next opportunity, but that sounds like a plausible cause. Then I guess the bug might be "vscode did not create the Dart launch.json file in the correct place"

**Comment by DanTup** [comment]
VS Code should create it in the root folder you have open (clicking the Cog icon on the Run side bar should open that file). If you had a folder further up the tree open, it would create it there - however that should not have stopped this from working so I think something else is amiss.

If you can still reproduce this and give details of where the `launch.json` is (and confirm clicking the cog on the Run side bar opens that file), let me know exactly where it is (and if it's inside the project as expected, please provide a copy of the project for me to test with). Thanks!

**Comment by Nyiern** [comment]
For some reason the .vscode folder did not get copied into the zip file. Trying again!
[kod001.zip](https://github.com/Dart-Code/Dart-Code/files/5540430/kod001.zip)

**Comment by tobega** [comment]
OK, mystery partly solved when I reproduced the problem on my Mac.

The "Run" command in the main file, and the run arrow on the top right of the editor section does not get the arguments.

When starting the run from the Run sidebar, the arguments are found just fine.

**Comment by DanTup** [comment]
That makes sense - the Run CodeLens link doesn't use your launch configurations, it just runs an empty "default" config. This is because you can have multiple launch configurations and the CodeLens wouldn't know which one to use (we have no access to the "selected" launch config from the Run side bar).

However, you can create additional Run/Debug links in the CodeLens from your launch configs, there's some documentation about this here:

https://dartcode.org/docs/custom-codelens/

Hope that helps!
