### ISSUE TITLE
Quick action to convert simple StatefullWidget to StatelessWidget

### ISSUE THREAD

**Issue by orestesgaolin** [Dart-Code/Dart-Code#2955]
**Is your feature request related to a problem? Please describe.**
Sometimes we want to convert our simple stateful widgets back to stateless and it involves manual process. It's tedious if there are many occurrences of `widget.field` in the state of the widget.

**Describe the solution you'd like**
Assuming that we have very basic StatefulWidget without any fields in its state, please provide a quick action to convert given widget to StatelessWidget similarly to the "Convert to StatefulWidget"

![image](https://user-images.githubusercontent.com/16854239/98999654-6d796280-2538-11eb-906d-23b533592bad.png)

Potentially if the fields of StatefulWidget are used in state, convert their usages from `widget.field` to `field`, e.g.:

```dart
class BasicStateless extends StatefulWidget {
  const BasicStateless({Key key}) : super(key: key);
  final title = 'Title';

  @override
  _BasicStatelessState createState() => _BasicStatelessState();
}

class _BasicStatelessState extends State<BasicStateless> {
  @override
  Widget build(BuildContext context) {
    return Text(widget.title);
  }
}
```

would become:

```dart
class BasicStateless extends StatelessWidget {
  const BasicStateless({Key key}) : super(key: key);

  final title = 'Title';

  @override
  Widget build(BuildContext context) {
    return Text(title);
  }
}
```

**Describe alternatives you've considered**
Manual process + find and replace.

**Additional context**
n/a

**Comment by DanTup** [comment]
Thanks for the suggestion! These code fixes come from the Dart language server so this would need to be implemented there, so this should be raised at https://github.com/dart-lang/sdk (the original request for the opposite way was https://github.com/dart-lang/sdk/issues/31823).

Thanks!
