### ISSUE TITLE
Icons suggestion preview not work

### ISSUE THREAD

**Issue by woozbooz** [Dart-Code/Dart-Code#2961]
Suggestion window didn't show icons preview.

![dart_icons](https://user-images.githubusercontent.com/37950619/99412428-61592080-28fd-11eb-99fa-702288ab63e0.png)

**Versions**
 - VS Code version: 1.51.1
 - Dart extension version: 3.16.0
 - Dart/Flutter SDK version: 1.22.4

**Comment by woozbooz** [comment]
Oh... i think i found the reason of problem.

**Comment by thegeox** [comment]
> Oh... i think i found the reason of problem.

And could we get to know what was the problem and how did you solve it. Facing the same issue :(

**Comment by DanTup** [comment]
@thegeox it could have been the same as https://github.com/Dart-Code/Dart-Code/issues/2896, however that was fixed in the latest release of Dart Code last week. If you're still seeing missing previews, please file a new issue and we can figure out what's wrong. Thanks!

**Comment by DanTup** [comment]
Also - you may need to press Ctrl+Space to force the right "details" panel open from the completion list.

**Comment by DanTup** [comment]
@Crickash0800 please see the pinned issue at the top of https://github.com/Dart-Code/Dart-Code/issues. Unfortunately this is a VS Code bug.
