### ISSUE TITLE
Add Reference List above method signature

### ISSUE THREAD

**Issue by jaredbaszler** [Dart-Code/Dart-Code#2962]
Please add "# reference(s)" to the method signatures.  Similar to this Typescript example:

![image](https://user-images.githubusercontent.com/9924084/99812297-e2860280-2b0b-11eb-83dc-f60ef7afdb3a.png)

**Comment by DanTup** [comment]
Thanks for the suggestion! There's already an open issue for this at #1605 so I'll close this as a dupe. Thanks!
