### ISSUE TITLE
Add commands to create new Flutter plugin/package/module

### ISSUE THREAD

**Issue by KaungZawHtet** [Dart-Code/Dart-Code#2963]
Can we get smoother experience on mixing c/c++ code in flutter project for dart ffi.

**Comment by KaungZawHtet** [comment]
Microsoft already released c++ and cmake extension for vs code so I think it is not big challenge to make it.

**Comment by DanTup** [comment]
Can you be more specific about the current issues or what you'd like to see improved?

**Comment by KaungZawHtet** [comment]
example, one click to generate ffi dev environment with some boilerplate code at both side (c++ side and dart side )

**Comment by KaungZawHtet** [comment]
and one click build for both of dart and c++ part

**Comment by DanTup** [comment]
@KaungZawHtet apologies - I'm not very familiar with what these projects look like, so it's not clear to me exactly what you're after.

> one click to generate ffi dev environment with some boilerplate code at both side (c++ side and dart side )

Do you just mean a project template (similar to the **Flutter: New Project** command), or something that you would run in an existing project? What it the boilerplate code you're looking for?

> one click build for both of dart and c++ part

For this, do you mean a compound launch configuration (in launch.json) so you can just press `F5` to both compile C++ and then build and launch the Flutter app? So this could be a default `launch.json` in a template (such as mentioned above), or maybe a launch.json snippet to allow this to easily be added to an existing project?

**Comment by KaungZawHtet** [comment]
I think my mensioned wishlist of dart ffi is not much different with embedding c++ code into android proj by the use of android ndk on Android studio. I think you can consider how ndk dev environment works.

**Comment by KaungZawHtet** [comment]
> Do you just mean a project template (similar to the **Flutter: New Project** command), or something that you would run in an existing project? What it the boilerplate code you're looking for?

Yes, like that. I think I used wrong terminology here. According to your words. It can go like this : **Flutter: New dart ffi project**

**Comment by DanTup** [comment]
Are you able to share an example of what you would expect the full project to look like? I'm not very familiar with FFI or what's involved in setting it up in VS Code, so it'd be useful to have a reference to better understand exactly how this would look?

I'm wondering whether a more generic feature that allowed custom templates would work. For example, if there was a setting like:

```
"dart.projectTemplates": {
  "dart-ffi": { description: "A template with Dart FFI builds", source: "/path/to/folder" },
  "dart-ffi-github": { description: "A template with Dart FFI builds", source: "https://github.com/foo/project" },
}
```

Then when you invoke the "New Project" command, we could list these items, and then copy the folders (or make copies from the repo if a GitHub address) to the location you pick. This would be more extensible than adding just this specific project. What do you think?

**Comment by KaungZawHtet** [comment]
Forget dart:ffi for now. We just need 3 new commands: **Flutter: New Application Project** (We have this one), **Flutter: New Plugin Project**, **Flutter: New Package Project**, **Flutter: New Module Project** and I think it's very easy for you to consider it. Reason why I point to different feature request is that according to official docs, new dart:ffi proj should start with **Flutter: New Plugin Project** . This is [link](https://flutter.dev/docs/development/platform-integration/c-interop).
Adding dart:ffi part into existing project can be different story.

Here is how those works in android studio:
<img width="824" alt="Screen Shot 2020-11-30 at 23 46 45" src="https://user-images.githubusercontent.com/15225530/100642613-5ecbe180-3367-11eb-9672-6767a1304259.png">

**Comment by KaungZawHtet** [comment]
So I think considering **Flutter: New Plugin Project** should be first before dart:ffi dev experience.
