### ISSUE TITLE
Hard to copy texts from debug console.

### ISSUE THREAD

**Issue by KaungZawHtet** [Dart-Code/Dart-Code#2967]
When copying text from it, selected part should be colorized.
As a bonus req, I wish the feature of copying whole line on debug console ( Currently we can copy entire text from debug section)

**Comment by DanTup** [comment]
The Debug Console is entirely rendered by VS Code (we only get to send text to it), so both of these features would need to be implemented in VS Code and should be raised at https://github.com/microsoft/vscode.

Thanks!
