### ISSUE TITLE
How to disable the plugin forced line break in VScode?

### ISSUE THREAD

**Issue by yukilzw** [Dart-Code/Dart-Code#2968]
![image](https://user-images.githubusercontent.com/21005519/100460579-63439080-3102-11eb-9e9d-699ab1ffbff0.png)
How to disable the plugin forced line break in VScode?
I want to disable this feature because it disrupts my habits.

**Comment by DanTup** [comment]
There are two related settings here:

1. `dart.lineLength` controls where the code is wrapped
2. `rulers` adds the line that is highlighted in your screenshot

If you want to increase the line length, you probably want to update both of these (so the formatter allows longer lines, and also so the ruler is shown in the new place - or you can remove it entirely if you don't want a line at all).

Hope this helps!

**Comment by S1r-Lanzelot** [comment]
Do people actually like that ruler? I personally don't just interested if other like the ruler in the center of their editor, `"editor.rulers": [80]` is a rather opinionated recommended setting IMO.

**Comment by DanTup** [comment]
I like it, but I'm not sure what the general feeling is. It's definitely opinionated, but it's based on where the formatter wraps. If you're disabling the formatter you'd likely want to disable this, but if you're using it there's some usefulness to knowing where it will wrap.
