### ISSUE TITLE
Bad state: Future already completed

### ISSUE THREAD

**Issue by jclaessens97** [Dart-Code/Dart-Code#2972]
**Describe the bug**
Every flutter command I try to run I get the following exception:

```[12:10:51 AM] [FlutterDaemon] [Error] Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:682:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1102:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1109:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1130:11)
#5    …
```

Inside vscode if I click on run to launch the flutter project, also get the same error as [this issue](https://github.com/flutter/flutter/issues/43063).

**To Reproduce**
Unclear, first time I have it, Installed 2 days ago, could use it 2 days in a row, while putting my pc to sleep inbetween, today after a whole day of working on other things in vscode, this happened.

**Expected behavior**
I expect it to run without error

**Screenshots**
<img width="1904" alt="image" src="https://user-images.githubusercontent.com/10177148/100672945-4cec3d80-336b-11eb-92db-9a4e9e7f3403.png">

**Versions (please complete the following information):**
 - VS Code version: 1.51.1
 - Dart extension version: 3.16.0
 - Dart/Flutter SDK version:  2.10.4/1.22.4
- OSX: 11.0.1 (20B50)

**Comment by DanTup** [comment]
If you close VS Code and just run `flutter doctor` from a terminal, do you also see the error?

Can you also post the output of `flutter --version`?

**Comment by jclaessens97** [comment]
Yes, even if I completely close vscode and try from terminal I get the same error.

<img width="925" alt="image" src="https://user-images.githubusercontent.com/10177148/100757886-93877980-33f7-11eb-826f-a6b27a4f83aa.png">

**Comment by DanTup** [comment]
In that case, this seems like an issue in Flutter that will need solving there, not here in the VS Code extension. It would be best raised at https://github.com/flutter/flutter/.

Before you do - if you have `git` it may be worth running `git status` inside your Flutter SDK folder, just to check you haven't got any corrupt files (I've seen some people end up with badly-merged files after a Flutter upgrade). You can post the output of that here if you're not sure how to interpret it.

Thanks!

**Comment by jclaessens97** [comment]
Hmm alright, I'll create an issue there. 
No changes inside my SDK folder:
<img width="925" alt="image" src="https://user-images.githubusercontent.com/10177148/100769454-bbc9a500-3404-11eb-8c9a-53fb84c9a6ab.png">

**Comment by jclaessens97** [comment]
Apperently AdGuard blocks the flutter request. Once I disabled it it worked again.

**Comment by DanTup** [comment]
Ah, glad to hear you solved it!
