### ISSUE TITLE
Failed to extract manifest from APK: ProcessException: The command failed

### ISSUE THREAD

**Issue by MohiniThakkar1995** [Dart-Code/Dart-Code#2978]
I have just created one project in VS studio for flutter, and when i try to run the project, i'm getting error.
Error : 
Failed to extract manifest from APK: ProcessException: The command failed
  Command: D:\SDK_NEW\sdk\build-tools\29.0.3\aapt dump xmltree E:\button_click_demo\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml.
Exception: Problem building Android application: see above error(s).

I have created flutter project from android studio and got same error, can someone please give me solution for this issue, i'm stuck with this error since last 2 days.

**Comment by MohiniThakkar1995** [comment]
https://prnt.sc/vuxdes
@DanTup please find screenshot

**Comment by DanTup** [comment]
I don't think this is a Dart-Code issue if it also happens in Android Studio, though you can try running

```
flutter run -v
```

to get verbose output to see if there are any more useful errors in there? Also can you post the full output of `flutter --version` and `flutter doctor -v`. Thanks!

**Comment by MohiniThakkar1995** [comment]
https://prnt.sc/vuxijb
Please find screenshot.

**Comment by MohiniThakkar1995** [comment]
Full attached info :
https://prnt.sc/vuxjrp
https://prnt.sc/vuxk3b

**Comment by MohiniThakkar1995** [comment]
Hello @DanTup ,
Can you please check and let me know what can be the issue? i'm stuck in same issue since last 2 days.

**Comment by DanTup** [comment]
@MohiniThakkar1995 can you try running from a terminal with `flutter run -v` (from your project folder) to see if the verbose output captures any additional information? The output will be very large - you could paste it into a [gist](https://gist.github.com/) - please ensure it contains nothing sensitive.

**Comment by MohiniThakkar1995** [comment]
https://prnt.sc/vuyeqj
https://prnt.sc/vuyfpr
@DanTup Not able to run the command successfully

**Comment by DanTup** [comment]
Looks like you don't have `flutter` in your `PATH` environment variable, so you would need to run:

```
E:\flutter_new_sdk\flutter\bin\flutter.bat run -v
```

**Comment by MohiniThakkar1995** [comment]
@DanTup Thanks for specification, i have run that command.
https://prnt.sc/vuyt5y
Please find attachment, it's showing error which i'm getting.
Also please let me know how can i direct fire this command from android studio/vs code.

**Comment by DanTup** [comment]
@MohiniThakkar1995 you need to run that command from the folder where your project is, eg.:

```
cd E:\button_click_demo
E:\flutter_new_sdk\flutter\bin\flutter.bat run -v
```

**Comment by MohiniThakkar1995** [comment]
https://gist.githubusercontent.com/MohiniThakkar1995/3fb5469663c2717f54a429b20e697088/raw/8ec801b706c536ecb64aaf4b2f022ade07f8a8b9/gistfile1.txt

I'm getting this logs after run the command.
can you please check and let me know what is the exact issue?

**Comment by MohiniThakkar1995** [comment]
Hello @DanTup ,
Any update?

**Comment by DanTup** [comment]
In that error, it has:

```
[  +25 ms] No application found for TargetPlatform.android_arm.
           Is your project missing an android\app\src\main\AndroidManifest.xml?
           Consider running "flutter create ." to create one.
```

This suggests there may be files missing from the `android` folder. Please try running:

```
cd E:\button_click_demo
E:\flutter_new_sdk\flutter\bin\flutter.bat create .
```

Then try the original command again:

```
cd E:\button_click_demo
E:\flutter_new_sdk\flutter\bin\flutter.bat run -v
```

**Comment by MohiniThakkar1995** [comment]
I have applied same commands, still i'm getting same error.

**Comment by DanTup** [comment]
Do you have a file at `android\app\src\main\AndroidManifest.xml` in your project?

**Comment by MohiniThakkar1995** [comment]
Yes, it's there. @DanTup 
https://prnt.sc/vuzv0h
Please find Attachment

**Comment by DanTup** [comment]
Otherwise, please try:

```
cd E:\button_click_demo
E:\flutter_new_sdk\flutter\bin\flutter.bat run -v
```

There are a few comments [here](https://stackoverflow.com/questions/59049261/flutter-error-failed-to-extract-manifest-from-apk-exit-code-1073741515) saying that solved it for them.

**Comment by MohiniThakkar1995** [comment]
I have tried all solutions, but none of them are working @DanTup .

**Comment by MohiniThakkar1995** [comment]
When i open android module separate, it's working fine. But when i run as flutter project it's giving me this error.
So can you please provide any other solution which can work in my case? @DanTup

**Comment by DanTup** [comment]
Did you try `clean`? If so, I'm unfortunately out of ideas and you may need to raise an issue at https://github.com/flutter/flutter/, as it seems to be something wrong with the Flutter or Android build and not something that can be fixed by the VS Code extension.

**Comment by MohiniThakkar1995** [comment]
Yes @DanTup , i tried with clean command, but still showing same error. I have tried in both IDE android studio and vs code, but both are giving same error.

**Comment by DanTup** [comment]
Understood. Unfortunately that's not something that can be fixed here (this is the repo for the VS Code extension) as the error is occurring in Flutter/Android build. I would recommend raising an issue in the Flutter repo for help - I unfortunately don't have any further ideas.

**Comment by MohiniThakkar1995** [comment]
okay, Thanks a lot for your quick response.
I'll raise my question over there.
