### ISSUE TITLE
There is no formatter for 'dart' files installed.

### ISSUE THREAD

**Issue by efreibe** [Dart-Code/Dart-Code#2979]
**Describe the bug**
If I enable `previewLsp` and restart vscode, I cannot format .dart files anymore, it shows the message **"There is no formatter for 'dart' files installed."**. When I disable `previewLsp` and restart vscode it works again.

**To Reproduce**
1. Go to User Settings and enable `previewLsp`, restart vscode.
2. Open a .dart file, execute command "Format document", it shows **"There is no formatter for 'dart' files installed."**
3. Go to settings again, set `previewLsp` to false, restart.
4. Try format the document, it works.

**Expected behavior**
Code is formatted.

**Screenshots**
-

**Versions (please complete the following information):**
 - VS Code version: 1.51.1
 - Dart extension version: 3.16.0
 - Dart/Flutter SDK version: Flutter (Channel stable, 1.22.3, on macOS 11.0.1 20B29, locale en-AR)

<hr>

More on this, I've tried to force the formatter in the [Dart] section of vscode to `"editor.defaultFormatter": "Dart-Code.dart-code"` or `"editor.defaultFormatter": "Dart-Code.flutter"` with no success.

**Comment by efreibe** [comment]
Apparently related to https://github.com/Dart-Code/Dart-Code/issues/2524, when LSP is enabled does not honor the workspace setting `dart.analysisExcludedFolders`

**Comment by DanTup** [comment]
It sounds like the server might not be initialising properly. Could you enable the [Analysis Server Log](https://dartcode.org/docs/logging/#analyzer) and restart and reproduce the issue, then provide the log (check there's nothing sensitive in there - it's best to reproduce with a dummy sample project). Thanks!

**Comment by sooxt98** [comment]
@DanTup Im also facing this issue with code-insiders (LSP enabled) on M1

**Comment by DanTup** [comment]
@sooxt98 could you file a new issue, and attach the log file mentioned in my last comment above? Thanks!

**Comment by sooxt98** [comment]
@DanTup i do notice something, if i turn of the settings bellow, the formatter wont work anymore

![image](https://user-images.githubusercontent.com/13378059/107319561-038e3c00-6ada-11eb-9e37-11a6140158ff.png)

![image](https://user-images.githubusercontent.com/13378059/107319630-26205500-6ada-11eb-8641-6bf7d187b1e4.png)

**Comment by DanTup** [comment]
@sooxt98 

> i do notice something, if i turn of the settings bellow, the formatter wont work anymore

That's expected - that setting turns off the formatter. The text looks a little misleading and probably shouldn't have the word "automatic" though. I'll remove that, but you shouldn't turn this setting off if you want the formatter.

**Comment by sooxt98** [comment]
@DanTup But how could i turn off auto formatting when save?

**Comment by DanTup** [comment]
@sooxt98 they're controlled by VS Code settings:

<img width="1044" alt="Screenshot 2021-02-10 at 12 28 40" src="https://user-images.githubusercontent.com/1078012/107510229-8d520e00-6b9b-11eb-80bb-99263c44f72a.png">

If you want to control them only for Dart, you should run the **Preferences: Configure Language-Specific Settings** and then add them into the Dart section:

```js
"[dart]": {
	"editor.formatOnSave": false,
	"editor.formatOnType": false,
	"editor.formatOnPaste": false,
},
```
