### ISSUE TITLE
Add support for code assists (eg. "wrap in widget")

### ISSUE THREAD

**Issue by sethladd** [Dart-Code/Dart-Code#298]
I'm guessing that "wrap in widget" comes from analysis service. If so, did we expose that in the VS Code plugin? If not, is that something that's easy to do?

I'd love to right-click on a widget constructor in my build() and select "wrap in widget".

Thanks!

**Comment by DanTup** [comment]
We currently expose code fixes, but I'm guessing this is a refactor. I think we don't support them yet but I can't remember why (or find any info on it). I'll take a look when I can and see what I can find.

**Comment by sethladd** [comment]
Thanks!

**Comment by DanTup** [comment]
Not sure I didn't implement this before; seems it's done with the CodeActionsProvider which [we already have](https://github.com/Dart-Code/Dart-Code/blob/master/src/providers/dart_code_action_provider.ts) for fixes. We just need to request refactors at the same time as fixes and combine the results; should be relatively easy.

**Comment by sethladd** [comment]
Nice. Thanks for checking

**Comment by DanTup** [comment]
@sethladd Assists (generally, not just this one) are supported for the next version (probably released tomorrow):

![Widget assist](https://cloud.githubusercontent.com/assets/1078012/26222177/f040bffc-3c10-11e7-86c1-6e52df855d9f.png)

However, there seems to be something wrong here - I don't know how this is supposed to work, but it seems to be including `widget` in lowercase so that it doesn't compile. Is this a bug in the assist in the SDK?

**Comment by sethladd** [comment]
Awesome, thank you!

re: widget, I think that's a placeholder. It's meant to be replaced by the developer.

How do I trigger the assist? Right-click?

Love your support. THANK YOU!

**Comment by DanTup** [comment]
@sethladd

> re: widget, I think that's a placeholder. It's meant to be replaced by the developer.

Gotcha, makes sense! It would be good if the analyzer returned it as a selection range so we could pre-select it for the user to just type over. It'd be a breaking API change though (currently we get back a `selection` that is just a single offset, not a range).. think it's worth me raising?

> How do I trigger the assist? Right-click?

Update to v1.4.0 and you'll get lightbulbs in the gutter when your cursor is somewhere with a code assist. You can invoke the menu using `Ctrl` + `.` or by clicking on the lightbulb. Let me know how it works for you!

**Comment by xster** [comment]
I somehow haven't noticed until just now. This is so awesome!!!!!11111oneoneone
