### ISSUE TITLE
Dart analyzer stops being intelligent

### ISSUE THREAD

**Issue by cedvdb** [Dart-Code/Dart-Code#2983]
Every time I run a flutter app the Dart analyzer stops being intelligent. I can't import classes from my project files and packages. It's not the issue with the dart analyzer that stops working though. I just don't have auto completion

I've tried on both visual studio code and android studio, it's the same result. I also reinstalled flutter, same result. I'm not sure which info I can give to resolve the issue, just ask and I'll provide.

```
Flutter 1.22.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1aafb3a8b9 (3 weeks ago) • 2020-11-13 09:59:28 -0800
Engine • revision 2c956a31c0
Tools • Dart 2.10.4
```

It's very annoying because I have to restart my ide every time I run the app to get back intellisens.

**Comment by DanTup** [comment]
This sounds like the same issue as #2973. If you're able to provide a small repro project and steps to reproduce on that issue, that would be appreciated. Thanks!
