### ISSUE TITLE
"Exception: Cannot run program "C:\Android\flutter\bin\flutter.bat" (in directory "F:\Flutterprograms"): CreateProcess error=2, The system cannot find the file specified" is showing during creating a new project  Android studio.

### ISSUE THREAD

**Issue by gunu-mishra** [Dart-Code/Dart-Code#2986]

**Comment by DanTup** [comment]
This repository is for the VS Code extensions for Dart/Flutter. The correct place for bugs with the Android Studio/IntelliJ plugins is here:

https://github.com/flutter/flutter-intellij/issues

Thanks!
