### ISSUE TITLE
Dart Analysis Server Bug

### ISSUE THREAD

**Issue by shasiru** [Dart-Code/Dart-Code#2988]
Issue Type: <b>Bug</b>

I noticed, after the recent flutter extension update, the Dart Analysis Server does not refresh itself after some time. Which means, I need to manually restart the Analysis Server due to showing false errors. 
In other words, the dart analysis server cannot keep up with the source code changes as I type, thus conflicting with the old previous code. 

However, if I restart the server, the issue is fixed. 

Please fix this asap because it's a really annoying bug.. 
Sometimes I spent hours chasing after a false error created by dart analysis server.  

Extension version: 3.17.0
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (5.96GB free)|
|Process Argv|--crash-reporter-id 2d22eade-05c6-447a-8257-f871300910e9|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by DanTup** [comment]
Are you able to reproduce this reliably? Could you provide a sample project and steps? An [analyzer instrumentation file](https://dartcode.org/docs/logging/#analyzer-instrumentation) may also be useful (though this may become very large, so being able to reproduce it early in the session would produce a more useful log).

Thanks!

**Comment by shasiru** [comment]
@DanTup 
I managed to capture the log file as well as to record a short video when this issue has occurred. 

Log file:
[Dart-Code-Log-2020-11-00 20-52-20.txt](https://github.com/Dart-Code/Dart-Code/files/5685162/Dart-Code-Log-2020-11-00.20-52-20.txt)

video - gif converted:
(has to be uploaded to cloud drive due to github's <10MB file restriction)
https://drive.google.com/file/d/1h_4rkkotvJ7y4bQ1b5Pn2mNVvBqIENKZ/view?usp=sharing


note: as you can see in the video(gif), I had to stop the log capturing service at the last moment, otherwise the captured data file won't be saved when I restart dart analysis server.

**Comment by DanTup** [comment]
@shasiru thanks for the log! I think I see the issue:

```
signUp_viewModel.dart
       ^
signUp_ViewModel.dart
       ^
```

This file appears in the log with different casing. Right now, the server treats everything case-sensitively, and it's therefore possible to end up with two instances of the same file in the servers memory if imported using different casing. This could confuse things (and to confuse things further, VS Code will try to detect this and may open the one it thinks is the correct one when we provide it differently-cased files).

Can you check whether the casing of this file is the same as it appears in the file explorer as all imports, and if anything is inconsistent, see if making them the same stops these errors from occurring?

Also - if you're able to make exact steps to reproduce getting into this state, that might help find a way to prevent it. Thanks!
