### ISSUE TITLE
Pre-fill "Create Project" names with an available name in the selected folder

### ISSUE THREAD

**Issue by csells** [Dart-Code/Dart-Code#2989]
**Is your feature request related to a problem? Please describe.**
Most of the projects I create are just throw-away Flutter apps (80%) or Dart Console apps (20%) for a quick test of something. Visual Studio has this feature where it will pick a unique name for a project in a specified folder automatically whereas in VSC, I have to name the project first (I always pick 'foo') and then create a new folder that's unique ('foo1', 'foo2', etc).

**Describe the solution you'd like**
I really just want to have a command called 'Create Dummy Flutter App' and 'Create Dummy Dart App' that drops a new uniquely named project into my temp folder.

**Comment by DanTup** [comment]
Currently we ask for a name before asking for a folder, so the name field is blank. However if we swap the order and ask for the folder first, we could perhaps pre-fill a unique name (like "flutter_application_1" or "dart_application_1" or similar).

This would still leave a step of pressing `<enter>` to accept that name, but perhaps that's better than a "dummy" command as it's discoverable by anyone using the normal command.

What do you think?

**Comment by csells** [comment]
that would be ideal
