### ISSUE TITLE
Failed to load test Compilation failed

### ISSUE THREAD

**Issue by rmargolinross** [Dart-Code/Dart-Code#2993]
**Describe the bug**
I recently upgraded the dart plugin for vs-code and now half of my tests are failing. The error is super generic and gives me no information as to the issue. My tests worked fine on the previous release.

**To Reproduce**
Run all tests with my tests in question.

**Expected behavior**
I expect my tests to pass or at least fail during running but instead get errors on run

**Versions (please complete the following information):**
 - VS Code version: 1.51.1
 - Dart extension version: 3.17.0
 - Dart/Flutter SDK version: 1.22.4

**Comment by DanTup** [comment]
Could you capture a log when reproducing this?

- Run the **Dart: Capture Debugging Logs** command
- Run the test(s) that fail with this error
- Click **Cancel** on the logging notification to stop logging and open the log file

Thanks!

**Comment by rmargolinross** [comment]
Actually, running with the debugging logs helped me find the issue. It is indeed on my side.
Thanks for the help.

**Comment by DanTup** [comment]
Great, glad you solved it!

**Comment by eb-so** [comment]
Having the same issue after I upgraded to futter 2.5.1
How did you solve the issue @rmargolinross
