### ISSUE TITLE
Error not coming through in VS Code debug console

### ISSUE THREAD

**Issue by lextoc** [Dart-Code/Dart-Code#3003]
**Describe the bug**
I was working on an app that needs a QR Code scan, which requires the following key set in `Info.plist`:

```
	<key>NSCameraUsageDescription</key>
	<string>This app needs camera access to scan QR codes</string>
```

I did not know about this and when I opened the screen containing the QR Code scanner the app closes with a simple `Lost connection to device`, whilst in Xcode there is additional info this did not show up in my VS Code debug console:

```
[access] This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data.
```

Is this normal behaviour? I thought everything popped up in the debug console. You can find a related issue here: [https://github.com/juliuscanute/qr_code_scanner/issues/171](https://github.com/juliuscanute/qr_code_scanner/issues/171)

**To Reproduce**
1. Create an app that requires camera access without giving the proper usage description in `Info.plist`,
2. Go to the screen that uses the camera (I was using a connected iPad mini 2 running on `12.4.9`)

**Expected behavior**
The message above about the `NSCameraUsageDescription` key should pop up in the debug console of VS Code.

**Screenshots**

**Versions (please complete the following information):**
 - VS Code version: 1.51.1
 - Dart extension version: 3.17.0 (updated really quickly after I checked so probably one version before :/ )
 - Dart/Flutter SDK version: 1.22.4

**Comment by DanTup** [comment]
Are you able to supply a simple test app I can use to repro this? Or, could you check whether the same is true if you run from the command line using `flutter run`. If it doesn't show up there, that's why it isn't showing up here (we show the output of the `flutter` process in the Debug Console) and will need to be raised in the Flutter repo.

Thanks!
