### ISSUE TITLE
Group first-party imports distinctively when organizing them

### ISSUE THREAD

**Issue by matehat** [Dart-Code/Dart-Code#3008]
**Is your feature request related to a problem? Please describe.**
In our fairly large Dart project, we have a lot of internal packages and use another great deal of third-party packages. Our imports very often look like a huge mess of flutter packages, third-party packages, our own packages, and even references to other files in the same package as the file writing it. So **it's hard to scan.**

**Describe the solution you'd like**
I strongly believe that adding the ability to specify first-party packages in order for them to be grouped below third-party packages would be a plus in term of readability.

**Describe alternatives you've considered**
There's not much alternative in terms of automated organization of imports in Dart, when using VS code. I'm aware there was a discussion about this in #2489, but the issue itself was about something else, which was successfully sorted out (no pun intended).

**Additional context**
For reference, [isort](https://pycqa.github.io/isort/) has this [concept of first-party libraries](https://pycqa.github.io/isort/docs/configuration/options/#known-first-party) in order to group imports using this same rationale. I think that this indicates that there's a desire from the community to easily distinguish when imported libraries are from ourselves or from third-parties. I think there's no need to force that, but at least make that configurable. isort can also automatically be triggered by Microsoft's new and awesome Pylance extension for vscode.

**Comment by DanTup** [comment]
The sorting is implemented in the analysis server so would need to be changed in the SDK. Is this the same request as https://github.com/dart-lang/sdk/issues/37519?

**Comment by matehat** [comment]
It's not the same -- the author is talking about imports from the _same package, whereas I'm talking about imports from packages that would be declared as first-party using some form of configuration. I should file the issue there then?

**Comment by DanTup** [comment]
Oh, I see.

The SDK is definitely the right place for changes to sorting, though whether it's worth coming up with some way to configure what a first-party package is only for sorting, I'm less sure.

I'll close this one anyway and leave it for you to raise there if you think it's worth a discussion. Thanks!
