### ISSUE TITLE
"TODOs" are not displayed in the problem panel when using LSP

### ISSUE THREAD

**Issue by EvyiLdaRkmaN** [Dart-Code/Dart-Code#3010]
After an update, I realize that having true in `dart.previewLsp` the TODO stops showing in the problems panel
I usually use the "TODO" for the pending tasks to be done in the code, so I don't know how it affects keeping: `dart.previewLsp` in false

before
![imagen](https://user-images.githubusercontent.com/26106072/102003332-8312b100-3ccb-11eb-8a66-93654bc988f4.png)

now
![imagen](https://user-images.githubusercontent.com/26106072/102003308-2c0cdc00-3ccb-11eb-94e2-f4affab5bfb3.png)

is there any way to be able to show them again without disabling: `dart.previewLsp`

**Versions (please complete the following information):**
 - VS Code version: 1.52.0
 - Dart extension version: v3.17.1
 - Dart/Flutter SDK version: Flutter 1.22.3 • channel stable

**Comment by DanTup** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/5d2905e8cb79ba5d44b0b005cd65589233603f43.

The change is in the LSP server and will therefore only show up when using a new SDK that includes that change.

**Comment by tapizquent** [comment]
Can you please elaborate a bit more here?

After enabling the Dart-Analysis Server (per VS Code's recommendation), my TODOs are no longer highlighted nor do they appear in the Problems tab. I have changed to the Flutter channel beta, as I assumed it would be update the Dart SDK to the proper one, but that does not seem to be working either.

**Comment by DanTup** [comment]
@tapizquent the current Flutter/[Dart beta](https://github.com/dart-lang/sdk/tree/beta) is at v2.12.0-133.2.beta which looks like it's just before this fix landed. I don't know what the release cycle is, but I suspect the fix would be included in the next beta update.
