### ISSUE TITLE
Caret doesn't move to a new widget when using "Wrap with widget..." command

### ISSUE THREAD

**Issue by kubaprzetakiewicz** [Dart-Code/Dart-Code#3015]
**Describe the bug**
When using the context menu to wrap the widget in another widget, the caret doesn't move to the new parent anymore.

**To Reproduce**
1. Position the caret inside the widget name
2. Open the context menu / Fixes menu via either the bulb or `Cmd + .`
3. Choose `Wrap with widget...`
4. Observe the caret staying at the original place instead of moving to the new `widget` parent - this was super useful for quick selection expansion to cover the whole word.

**Expected behavior**
The caret should move to the new, enclosing widget.

**Screenshots**
![screen recording of the issue](https://media.giphy.com/media/zWD8aDufER6J6cjR58/giphy.gif)

### Versions
VS Code version: 
```
Version: 1.52.0
Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be
Date: 2020-12-10T22:46:53.673Z (5 days ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0
```

Dart extension version:
`dart-code.dart-code` - v3.17.1
`dart-code.flutter` - v3.17.0

Dart/Flutter SDK version:
```
[✓] Flutter (Channel master, 1.25.0-9.0.pre.88, on macOS 11.0.1 20B50 darwin-x64, locale en-GB)
    • Flutter version 1.25.0-9.0.pre.88 at /Users/kubcio/.flutter
    • Framework revision e24e763872 (4 hours ago), 2020-12-16 07:33:03 -0500
    • Engine revision e9f2f0eaea
    • Dart version 2.12.0 (build 2.12.0-157.0.dev)
```

**Comment by chreck** [comment]
I have the same issue with this environment.

**Versions**

VS Code version:

```
Version: 1.52.0
Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be
Date: 2020-12-10T22:46:53.673Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.2.0
```

Dart extension version:
```
dart-code.dart-code - v3.17.1
dart-code.flutter - v3.17.0
```

Dart/Flutter SDK version:
```
Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (6 days ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4
```

**Comment by DanTup** [comment]
In LSP we don't currently have a way to set the selection for a code action. There's an open issue at https://github.com/microsoft/language-server-protocol/issues/724 - please add 👍 's!

**Comment by DanTup** [comment]
This has been fixed:

![Aug-25-2022 16-16-50](https://user-images.githubusercontent.com/1078012/186704190-05a76802-b91e-4a38-87fe-501e6811f9c3.gif)
