### ISSUE TITLE
Code Action: Generate Interface

### ISSUE THREAD

**Issue by KSLiquid** [Dart-Code/Dart-Code#3018]
**Is your feature request related to a problem? Please describe.**
Oftentimes I write some kind of service and afterwards I want to create an abstract class from it, to implement dependency inversion. I always have to manually copy the whole class and delete the function bodies, which is annoying work.

**Describe the solution you'd like**
A code action would be great. Like I can do "extract widget" in flutter, I'm thinking of a code action like "generate Abstract Class" or "generate Interface" when hovering over a dart class. The action should then create an abstract class (and maybe let me chose the name) which acts as an interface.

**Example:**
existing class
`class MyClass {
void helloWorld(){
print("Hello");
}
}`
generated class after code action:
`abstract class MyAbstractClass {
void helloWorld();
}`

**Describe alternatives you've considered**
As an alternative I could write this action myself, but I do not know how to start and do not find a tutorial on how to implement a code action like this.

**Thanks for your great work!**

**Comment by DanTup** [comment]
Sorry for the delay, I missed the notification for this. This would be best raised at https://github.com/dart-lang/sdk as all of the refactors/code actions come from the Dart analysis server (so they work across all editors, not just VS Code).

If you raise it there, please post a link back here in case others find this issue and would like to  👍  it over there.

Thanks!

**Comment by KSLiquid** [comment]
@DanTup Thanks for the info! I posted it here: https://github.com/dart-lang/sdk/issues/44645
