### ISSUE TITLE
Flutter: Rescan devices command

### ISSUE THREAD

**Issue by timsneath** [Dart-Code/Dart-Code#3023]
I think this is an omission? 

I have a project running in VSCode, and I plug in my iPhone. 

`flutter devices` reports the new device:

```
$ flutter devices
3 connected devices:

Tim's iPhone 11 (mobile) • 00008030-00090DD40160802E • ios            • iOS 14.3
macOS (desktop)          • macos                     • darwin-arm64   • macOS 11.1 20C69 darwin-arm
Chrome (web)             • chrome                    • web-javascript • Google Chrome 87.0.4280.88
```

... but VSCode doesn't know it exists:
![image](https://user-images.githubusercontent.com/2319867/102655359-0b0f1580-4127-11eb-881c-e4e8e98ad256.png)

Do we need some kind of `Flutter: Rescan devices` command to update the cache? For example, should there be an entry at the bottom of the list?

Reloading the VSCode window works, of course.

**Comment by DanTup** [comment]
It should happen automatically, no command required. The daemon is long-lived and should tell us when new devices are connected. I'm not sure why it's not working (I don't have a physical iPhone to try).

Could you try this:

- Run `flutter daemon` from a terminal
- Paste in `[{"id":"2","method":"device.enable"}]` and press `<enter>`
- Connect your iPhone

If the device doesn't show up there, something may be wrong in Flutter. Running the daemon with `-v` may give more info. It may be worth switching to another channel (eg. stable) to see if it works there, to see whether it's become broken or whether there might be something specific about your machine/phone causing it.

**Comment by DanTup** [comment]
This actually sounds a bit like an issue that came up earlier in the year:

- https://github.com/flutter/flutter/issues/62100
- https://github.com/flutter/flutter/pull/62225

Although it seems like the fix for that is still in-tact, so maybe coincidence.

**Comment by timsneath** [comment]
Hmm....

```
flutter daemon
[{"event":"daemon.connected","params":{"version":"0.6.0","pid":22545}}]
[{"event":"daemon.logMessage","params":{"level":"status","message":"Starting device daemon..."}}]
[{"id":"2","method":"device.enable"}]
[{"id":"2"}]
[{"event":"device.added","params":{"id":"macos","name":"macOS","platform":"darwin-x64","emulator":false,"category":"desktop","platformType":"macos","ephemeral":false,"emulatorId":null}}]
[{"event":"device.added","params":{"id":"chrome","name":"Chrome","platform":"web-javascript","emulator":false,"category":"web","platformType":"web","ephemeral":false,"emulatorId":null}}]
```
and no entry when I plugged it in.

But then I unplugged and replugged and this popped:
```
[{"event":"device.added","params":{"id":"00008030-00090DD40160802E","name":"Tim's iPhone 11","platform":"ios","emulator":false,"category":"mobile","platformType":"ios","ephemeral":true,"emulatorId":null}}]
```

Seems a little fragile, but I do see it's doing what it should do when it works.

**Comment by timsneath** [comment]
Closing for now, since the feature exists on VSCode. If I can get a consistent repro, I'll file it on the flutter/flutter side, since this seems like a `flutter daemon` issue.
