### ISSUE TITLE
Make the behavior of automatic package import configurable between cupertino and material

### ISSUE THREAD

**Issue by JostSchenck** [Dart-Code/Dart-Code#3031]
I couldn't find this problem discussed in issues, sorry if this exists: When I use a widget, which exists in both cupertino and material, and dart code automatically creates a package import for me, it will always choose cupertino over material (presumably because it's first in the alphabet). I don't develop for Apple right now, so I'd love to be able to change this behavior. When doing a manual quick fix, I can choose in the context menu, which is fine.

A clear and concise description of what you want to happen: I'd love to have a setting "prefer material.dart over cupertino.dart in automatically generated package import statements"

**Comment by DanTup** [comment]
> and dart code automatically creates a package import for me
> When doing a manual quick fix, I can choose in the context menu, which is fine.

I presume you mean when selecting from the code completion list? You should be able to select there too - the item should show in the completion list multiple times with the text "auto-import from (library)" next to it (you can use Cmd+Space to toggle the larger details pane, as it could otherwise be truncted depending on your completion list widget size).

Can you confirm if you're seeing that?

**Comment by JostSchenck** [comment]
> I presume you mean when selecting from the code completion list?

Yes, that's right, I now understand what I did wrong. However, I think the way this is displayed is a little problematic (see screenshot), though I don't know if this is specific to VS Code or the dart extension, as I'm no expert in both: In code completion, it shows me only the selected package and that is cut-off before I can see the interesting part:

![cupertino](https://user-images.githubusercontent.com/12062873/103165548-93717280-4819-11eb-8ba4-f051ebd96f72.PNG)

For me, I know now what to do, and I'm fine if you close this. To make this feature more understandable, a wider context menu, or shortening similar package references with "..." to show the part that actually differs, might be useful, at least for new users.

Thank you very much!

**Comment by DanTup** [comment]
Yep, I agree on the UX. There's an open issue with VS Code about adding support for showing these labels all the time:

https://github.com/microsoft/vscode/issues/39441

If that's implemented, it'll show up. There may also be another way to achieve this as TypeScript is now able to always show filenames - though it seems to be a private API - we may be able to use in future.

Thanks!
