### ISSUE TITLE
Support auto-save without hot reloading on every change

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#3033]
See https://stackoverflow.com/questions/65442649/visual-studio-code-auto-hot-reload-file-changes. Seems like the same as #1427 for hot-reload-on-save. It might be desirable to have this, so it may need a setting to control. To avoid it, we can examine the save reason (similar to the pub get version). It won't work if using the FS watcher though.

**Comment by alx-xlx** [comment]
How exactly will this work ?

**Comment by DanTup** [comment]
This behaviour is controlled by the `dart.hotReloadOnSave` setting (it's changed slightly since this original implementation). When set to `"manual"`, hot-reload-on-save will only trigger for manual saves (not for VS code auto-saves). You can still press Save to manually save (and trigger the reload) even when using auto-save. If set to `"always"`, then hot reload will run for all saves, including those that were triggered automatically by VS Code's auto-save.

**Comment by alx-xlx** [comment]
I have set it to "always" but still it doesn't hot reload upon saving file changes

**Comment by DanTup** [comment]
@alx-xlx are you running your app through the `Run` menu or with `flutter run` in the terminal? The reload can only work when using the VS Code debugger.

If you are using that, could you file a new issue about this, and include you exact versions of VS Code, the extensions, Flutter SDK? Thanks!

**Comment by Taro-Naza** [comment]
It doesn't work for me! I have to start it in debug mode to have hot reload work on save, otherwise it doesn't work at all

**Comment by Taro-Naza** [comment]
> 

It would be great if we can have hot reload when running the app using `flutter run`

**Comment by Taro-Naza** [comment]
> @alx-xlx are you running your app through the `Run` menu or with `flutter run` in the terminal? The reload can only work when using the VS Code debugger.
> 
> If you are using that, could you file a new issue about this, and include you exact versions of VS Code, the extensions, Flutter SDK? Thanks!

It would be great if we can have hot-reload when running the app using `flutter run`

**Comment by DanTup** [comment]
@Taro-Naza 

> It would be great if we can have hot-reload when running the app using `flutter run`

Unfortunately this isn't possible. When you run from the terminal, the VS Code extension knows nothing about that process and cannot interact with it. You need to run from within VS Code using the Run menu (and related features) if you want to use the other features.

If there's a reason you're using `flutter run` and not using the commands in the terminal, I'd be interested to understand that. My goal is that running from the editor (which is usually as simple as pressing `F5`, although may require a `launch.json` if you need to pass additional args) is always the best option, so if there are cases where it's worse hopefully they can be improved.

**Comment by Taro-Naza** [comment]
> @Taro-Naza 
> 
> > It would be great if we can have hot-reload when running the app using `flutter run`
> 
> Unfortunately this isn't possible. When you run from the terminal, the VS Code extension knows nothing about that process and cannot interact with it. You need to run from within VS Code using the Run menu (and related features) if you want to use the other features.
> 
> If there's a reason you're using `flutter run` and not using the commands in the terminal, I'd be interested to understand that. My goal is that running from the editor (which is usually as simple as pressing `F5`, although may require a `launch.json` if you need to pass additional args) is always the best option, so if there are cases where it's worse hopefully they can be improved.

No, I don't have a particular reason to run the app using `flutter run`, I'm new to mobile app development using flutter and I'm just exploring the ecosystem and the tooling available. Thank you for the response and the explanation 🙏🏻
