### ISSUE TITLE
Make it easier to track down "Initializing flutter" that doesn't complete

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#3034]
This has come up a few times now (for ex. https://stackoverflow.com/questions/65344281/initializing-flutter-this-may-take-a-few-minutes-takes-forever-on-vscode). We should handle this better, such as showing the current output after a while, and/or offering some more help.

**Comment by DanTup** [comment]
The full output is always shown now.

**Comment by HariPrakashGolusu** [comment]
How is it solved?

**Comment by DanTup** [comment]
The issue here was usually that the Flutter process was getting stuck and there was text explaining why that was not shown to the user. Now, the output should show in an Output pane, so if this happens, the reason/message should be visible. If you're seeing it getting stuck with no visible output, please file a new issue with a screenshot of exactly what you're seeing so we can dig into it. Thanks!

**Comment by SANKETV4E** [comment]
![image](https://user-images.githubusercontent.com/101256610/227731474-01a257e8-e7b4-4b15-9afa-836f45e3c348.png)

I am unable work on my project as this appears continuously and doesnt allow to upgrade flutter or run any other command in terminal. This is appearing since last 2 days constantly and don't allow to work on any flutter project. please provide solution for my problem

**Comment by DanTup** [comment]
@SANKETV4E can you access https://pub.dev/ in your browser?

**Comment by SANKETV4E** [comment]
@DanTup Yes I am able to access https://pub.dev/ in the browser

**Comment by DanTup** [comment]
@SANKETV4E can you open a new issue about this, and include the full output of running `flutter doctor -v` in a terminal in addition to the screenshot above? Thanks!

**Comment by DanTup** [comment]
@esraaabdrabo if you're having the same issue, please open a new issue as described above with the requested info. Thanks!

**Comment by joji33888** [comment]
same issues

**Comment by DanTup** [comment]
@joji33888 this issue was resolved a long time ago. If you're having problems, please open a new issue and include a clear description of the behaviour you're seeing (screenshots and/or screen recording can be very helpful). Thanks!
