### ISSUE TITLE
Flutter code completion. Invalid closure added for setState() function

### ISSUE THREAD

**Issue by SAnegondhi** [Dart-Code/Dart-Code#3039]
**In VS Code Editor typing set  and choosing `setState` function inserts invalid closure**

In VS Code editor (within a Statefull class), typing set and waiting brings up the code completion menu, choosing setState, results in the following code being inserted at cursor:
```
   setState(() {
        
      });(() { })
```

**To Reproduce**
Steps to reproduce the behavior: self explanatory from above.

**Expected behavior**
Expected behaviour - the follwing code being inserted:
```
   setState(() {
        
      });
```

**Versions:**
 - VS Code version: 1.52.1
 - Dart extension version: 3.18.0
 - Dart/Flutter SDK version: Flutter SDK (LSP) 1.26.0-1.0.pre
 - OS: Ubuntu 20.10

**Comment by SAnegondhi** [comment]
Switching **LSP** off solves this issue.
in `settings`
![image](https://user-images.githubusercontent.com/11058465/103396165-96d96680-4b57-11eb-9018-2dc5d69fbfe4.png)

**Comment by SAnegondhi** [comment]
spelling mistake corrected

**Comment by DanTup** [comment]
Thanks for the report! This came up in #3006 and has been fixed, but the fix likely hasn't reached the channel you're using yet, but should in a future update.
