### ISSUE TITLE
CREATE PROCESSW PROCESS 193 FAILED

### ISSUE THREAD

**Issue by EuvolaGG** [Dart-Code/Dart-Code#3042]
Hello...I created a flutter project and immedaitely ran it to check for issues before  I start writting.I expected the project to ran smoothly since I  have not written anything.Can you help me fix this?All software are up to date and am using flutter channel stable.

THIS WHAT I GOT ON MY VSCODE DEBUG CONSOLE
CreateProcessW failed 193
Failed to extract manifest from APK: ProcessException: %1 is not a valid Win32 application.

  Command: C:\Users\NM\AppData\Local\Android\sdk\build-tools\29.0.2\aapt.EXE dump xmltree C:\Users\NM\Desktop\Repositories\memo\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml.
Exception: Problem building Android application: see above error(s).
Exited (sigterm)

AFTER RUNNING FLUTTER ANALYSE 
PS C:\Users\NM\Desktop\Repositories\memo> flutter analyze        
Analyzing memo...
No issues found! (ran in 4.3s)

ON RUNNING FLUTTER DOCTOR -V
PS C:\Users\NM\Desktop\Repositories\memo> flutter doctor -v
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18363.1256], locale en-US)
    • Flutter version 1.22.5 at C:\flutter
    • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\NM\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\NM\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.0

[√] Connected device (1 available)
    • TECNO CA8 (mobile) • 031281184B002107 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.

THE FLUTTER PLUGIN AND ANDROID PLUGIN IN ANDROID STUDIO WERE INSTALLED AND UPDATE BEFORE I STARTED THE PROJECT.SCREEN SHOT ATTACHED
![image_2021-01-02_133822](https://user-images.githubusercontent.com/68217917/103455650-dba00180-4cff-11eb-8895-dd1f953ca4a6.png)

BUT THE PROJECT CANNOT RUN

**Comment by DanTup** [comment]
This doesn't seem like a VS Code extension issue as it also occurs in Android Studio. It seems like the file `C:\Users\NM\AppData\Local\Android\sdk\build-tools\29.0.2\aapt.EXE` might be corrupt (or something is interfering with running it).

There are some ideas you can try at https://stackoverflow.com/questions/46934040/errorjava-io-ioexception-createprocess-error-193-1-is-not-a-valid-win32-app

You could try updating to the latest version of the Android SDK Build Tools in the Android Studio SDK Manager (Tools tab).

Also - can you confirm if your PC is 32bit or 64bit?

**Comment by EuvolaGG** [comment]
Pc is 64bit @DanTup

**Comment by DanTup** [comment]
@EuvolaGG did you try updating the tools mentioned above?

Can you also check whether the same error occurs if you try to run the app using `flutter run` from a terminal? I suspect it's not a VS Code-specific issue so probably not something that can be fixed here.

**Comment by EuvolaGG** [comment]
I updated them and it worked@Dan Tup

**Comment by DanTup** [comment]
Great! I guess something must've been corrupt in the old versions. I'm not sure how that could happen, but I'm glad it's resolved!
