### ISSUE TITLE
XMLHttpRequest Error with vsCode

### ISSUE THREAD

**Issue by SchabanBo** [Dart-Code/Dart-Code#3043]
**Describe the bug**
Hallo,
I am working with flutter web on vsCode and I am trying to show an image from the web by Image.network()
when I run the code with vsCode in debug mode the image cannot be loaded 
The message : 
```
Access to XMLHttpRequest at 'https://www.vegetables.co.nz/assets/vegetables/_resampled/FillWyI0MDAiLCIzMDAiXQ/eggplant.png' from origin 'http://localhost:59520' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
is showed in my console.
but when I run my code on Android Studio or build a release or on android device it works fines. That happens just on vsCode on Browser.
I don't know if it's here the right place to ask. but I have tried everything. I reinstalled vsCode and flutter and cleared all the cash for both and try it on Edge and Chrome and still not fix. 

**Screenshots**
![image](https://user-images.githubusercontent.com/49782771/103467422-39a80580-4d4f-11eb-95d3-6ee81c68aeea.png)
The windows on the right is from android studio and the one on the left is from vsCode

flutter doctor -v
[√] Flutter (Channel dev, 1.26.0-1.0.pre, on Microsoft Windows [Version 10.0.18363.1256], locale en-GB)
    • Flutter version 1.26.0-1.0.pre at C:\flutter
    • Framework revision 63062a6443 (3 weeks ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Schab\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.52.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.18.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 87.0.664.66

• No issues found!

Thank you

**Comment by DanTup** [comment]
This is a Flutter/CORS issue. Flutter is trying to fetch the image using XMLHttpRequest which is subject to CORS rules (you can't request files from other domains unless they have the correct CORS headers).

There's an open issue about this in Flutter here: https://github.com/flutter/flutter/issues/45955

Please let me know if you think this isn't the same issue. Thanks!
