### ISSUE TITLE
Current SDK setting stored in current project folders .vscode/settings

### ISSUE THREAD

**Issue by maks** [Dart-Code/Dart-Code#3044]
**Describe the bug**

When using the `Dart: Change SDK` command to set a Dart SDK from a list, when choosing a sdk option thats not the auto-detected one, the selection is stored in the current open folders settings, not vscode's user settings.

**To Reproduce**
1. Open command palette
2. enter `Dart: Change SDK` command
3. select non auto selected SDK option
4. note settings .json in current open folder is modified with the newly selected SDK choice, eg. in `.vscode/settings.json`
```
{
    "dart.sdkPath": "/opt/apps/dart-sdk"
}
```

**Expected behavior**
Per [previous comment](https://github.com/Dart-Code/Dart-Code/issues/222#issuecomment-315556211) I had expected that this is a vscode-wide user setting, rather than a per project-folder setting.

The above also applies for the equivalent Flutter SDK choice functionality. 

**Versions (please complete the following information):**
 - VS Code version: 1.52.1
 - Dart extension version: v3.18.0

**Comment by DanTup** [comment]
This was changed in #455 as it seemed more appropriate if you were "quick switching" SDK that's probably a temporary thing for a specific project or testing. I presume it's not as common to want to globally switch SDK, though I'm interested in hearing why you'd prefer it to work that way?

**Comment by maks** [comment]
Ah sorry missed that when I searched through the issues, thanks for the pointer @DanTup !

The reason I wanted to this was that I tend to keep things like launch configs in settings.json so I have it included in git repo and they are not local env specific so I can share the between diff machines Im working on as well as diff devs working with a repo. But this setting for the sdk path is very machine specific so I wouldn't want to have it commited in a repo.

I guess this might be a bit of a niche use case and I can work around it by changing my global SDK setting with links or using something like FVM but it does make the sdk.paths config in Dartcode not as useful for my particular way of working.

**Comment by DanTup** [comment]
Ah, got it. I think really the fix for this is https://github.com/microsoft/vscode/issues/40233 (a highly desired feature for VS Code). I don't know of any other good workarounds, and I'm not sure it makes really sense to revert this to workaround that.

One workaround posted there is to instead script the creation of the settings file, so new checkouts can run that script and then users can customise it further (and do not commit the settings file directly). I don't think it's great though. I'm surprised VS Code still doesn't have a solution to what seems a pretty common case.

**Comment by maks** [comment]
Thanks again @DanTup for that pointer to the vscode issue! 

So the easy workaround for me from reading that issue is just to use a workspace and then the "selected" flutter and dart sdk  path gets set in the `.code-workspace` setting instead of a  "folders" `settings.json` - which works well for me :+1: :tada:

**Comment by DanTup** [comment]
Ah yes, I hadn't considered that it would go there for a `.code-workspace`. That doesn't seem too bad while waiting for VS Code to provide something better (if it ever does) :-)
