### ISSUE TITLE
Test tree shows duplicate tests after discovering tests + running tests when using LSP on Windows

### ISSUE THREAD

**Issue by BootBlock** [Dart-Code/Dart-Code#3052]
There appears to be someplace within the file loading chain that may be normalising file paths to lowercase, while other parts of Dart-Code are not normalising the paths and so paths to files are being seen as being different even though they're in actuality the same.

This results in an issue - and potentially others - of test tree node duplication when running tests as suite keys are specified via file path.

**This only happens when LSP is enabled.**

![image](https://user-images.githubusercontent.com/18527642/103670272-460ba880-4f71-11eb-819b-884872f37917.png)

Note that the passed *another_test.dart* node is a duplication of the grey version below it; they're the same test(s) but seen as different due to casing differences as mentioned above.

**Versions (please complete the following information):**
 - VS Code version: 1.52.1
 - Dart extension version: 3.18
 - Dart/Flutter SDK version: 2.10.4 / 1.26.0-2.0.pre.170

**Comment by DanTup** [comment]
This was less of an issue than I thought it was giong to be - most places we already normalise the driver letter when converting from URIs to Paths (in `fsPath`). However this one is a "URI in a string" and did not.

I had a scan through other places using this, and don't think it should come up anywhere else, but I'll try to get the LSP tests merged into master so there's more coverage of LSP on Windows.
