### ISSUE TITLE
Renaming enum doesn't change type references

### ISSUE THREAD

**Issue by jeiea** [Dart-Code/Dart-Code#3057]
**Describe the bug**
vscode has `Rename Symbol` command. Dart-Code also supports this command and it works well on class, but not on enum.

**To Reproduce**
1. Create the following `code.dart`.
```dart
B fn(B b) {}

enum B {
  BBB,
}
```
2. Press F2 on the position of enum **B**.
3. Type 'C' and press enter.

**Expected behavior**
All `B` should be replaced with `C`.

**Actual behavior**
```dart
B fn(B b) {}

enum C {
  BBB,
}
```

**Versions (please complete the following information):**
 - VS Code version: 1.52.1
 - Dart extension version:3.18.1
 - Dart/Flutter SDK version: 1.22.3

**Comment by DanTup** [comment]
Thanks for the report! I can reproduce this on Flutter 1.22, however it appears to be fixed in Flutter 1.26 (the current master branch). I would therefore expect this issue to go away after the next Flutter release.
