### ISSUE TITLE
The "Run All Tests" command doesn't correctly mark tests as stale/remove them after a run

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#3058]
Given a test file like:

```dart
import 'package:test/test.dart';

void main() {
  test('1', () => expect(true, false));
}
```

If you:

- Run with the **Dart: Run All Tests** command
- Rename the test to `2`
- Re-run with the **Dart: Run All Tests** command

The old result for `1` remains in the test tree. Yet if you run the file with F5 or the Run CodeLens from the `main` function, it correctly is removed.

Possibly this is due to the "is new test run" flag (or the potentially deleted flags) not being set by the Run All Tests command?

**Comment by kentcb** [comment]
Thanks for fixing this! 😍 🎉
