### ISSUE TITLE
Autocomplete not including parenthesis

### ISSUE THREAD

**Issue by punreachrany** [Dart-Code/Dart-Code#3059]
My Flutter autocomplete doesn't work properly.
E.g, When I type the Center Widget, it's supposed to give me `Center()`, but instead it gave me `Center` without the parenthesis.

**Comment by awnigharbia** [comment]
Disable the `LSP` feature and it works fine (VScode version).

**Comment by punreachrany** [comment]
@awnigharbia what is an `LSP` feature? And where can I find this feature setting?

**Comment by awnigharbia** [comment]
Navigate to your vscode settings by `ctrl + , `, then search for `dart: Preview Lsp` -> uncheck it. but this is a hack until the extension maintainers fix it.

**Comment by punreachrany** [comment]
@awnigharbia It's fixed. Anyway, it's a bug in the extension, right?
After the maintainers fix it, should I check `dart: Preview Lsp` again?

**Comment by awnigharbia** [comment]
I think they'll follow up with this issue and give us the right solution.

**Comment by DanTup** [comment]
For LSP there's a setting called "Complete Function Calls" that enables parens/argument placeholders. It's not available in the stable branches of Flutter/Dart yet, [but is available in the dev/nightly builds](https://github.com/Dart-Code/Dart-Code/issues/2823#issuecomment-725630953).

In the future, LSP will become the default (and then only) option, however neither of these will happen until after Complete Function Calls has made it to the stable channels.

Hope this makes sense - shout if you have any questions/issues!

**Comment by punreachrany** [comment]
I see. Thank you very much. This helps a lot.
