### ISSUE TITLE
vs code refactoring not working properly 

### ISSUE THREAD

**Issue by syedassadullahshah** [Dart-Code/Dart-Code#3061]
**Describe the bug**
Flutter extract variable option is not showing and shows only extract method and widget option and by extracting method/widget it doesnot ask for name and give it default name of newmethod/newWidget 

**To Reproduce**
1. Install vscode 
2. Install plugins flutter and dart
3. open any flutter project and try to extract variable or method/widget
4. It will not ask for rename

**Expected behavior**
Previously it was showing option to extract variable and also will ask for name after extracting variable/widget/method name

**ScreenShorts**
![Screenshot from 2021-01-12 17-27-53](https://user-images.githubusercontent.com/67960146/104314688-99df3a00-54fb-11eb-988a-c97e81b85785.png)
![Screenshot from 2021-01-12 17-28-22](https://user-images.githubusercontent.com/67960146/104314698-9cda2a80-54fb-11eb-8375-a5f29995f42a.png)

**Versions (please complete the following information):**
 - VS Code version: 1.52.1
 - Dart extension version: 3.18.1
 - Dart/Flutter SDK version: 1.22.5

**Comment by awnigharbia** [comment]
I have the same problem with the latest version.

**Comment by syedassadullahshah** [comment]
> I have the same problem with the latest version.

I switched to android studio on temporary basis. Its working fine there.

**Comment by awnigharbia** [comment]
I have to disable the `LSP` feature and it works fine on vscode.

**Comment by syedassadullahshah** [comment]
> I have to disable the `LSP` feature and it works fine on vscode.

Can you guide me how did you disable LSP?

**Comment by awnigharbia** [comment]
I think they'll follow up with this issue and give us the right solution.

**Comment by DanTup** [comment]
Thanks for the report! Extract Variable isn't currently available in the LSP version. There's an open issue tracking this at https://github.com/Dart-Code/Dart-Code/issues/2951. Thanks!
