### ISSUE TITLE
Flutter Project in VS code is not cleaning up a process (xcdevice observe --both) after closing the project 

### ISSUE THREAD

**Issue by osaxma** [Dart-Code/Dart-Code#3062]
**Describe the bug**
I noticed that whenever I open a flutter project in VS code and then close everything (vscode &  simulator if running), this process left behind:

```sh
[~]$ ps 
PID TTY           TIME CMD
32920 ttys003    0:00.08 /Applications/Xcode.app/Contents/Developer/usr/bin/xcdevice observe --both
```
 If I open VS code again, another process will be added with the same command. Also if I open a new instance of a different flutter project, another process is added there again... Once I close all the instances, the processes stay there without being closed. 

I noticed this yesterday when I had 5 or 6 of them running (I rarely restart my laptop so I guess they accumulated over few days)... 

**To Reproduce**
1. Open a flutter project in VS code 
2. Wait for a minute or so until the process appear in `ps`
3. close VS code and simulators if they're running
4. repeat or just open new instances of VS code for flutter projects.
5. the processes will add up even when all VS code instances are closed

**Expected behavior**
the process should be terminated once the flutter project in VS code is closed.

**Screenshots**

**Versions (please complete the following information):**
 - VS Code version: 1.52.1
 - Dart extension version: v3.18.1
 - Dart/Flutter SDK version: v3.18.1

**Additional Context** 
- no `flutter` or `dart` processes are left behind. 
- Already communicated with @DanTup  on the discord channel about the issue.

**Comment by DanTup** [comment]
Thanks for the report! I did some digging and think this is a Flutter issue. We're terminated the process with a SIGTERM signal and I believe it should catch that and clean up. I've filed https://github.com/flutter/flutter/issues/73859 and will close this in favour of that one. Thanks!
