### ISSUE TITLE
Feature: option to run analysis on save

### ISSUE THREAD

**Issue by jellyNoone** [Dart-Code/Dart-Code#3068]
**Is your feature request related to a problem? Please describe.**
Ever since I started working with dart again I've been occasionally hitting a 90 ~ 100% CPU usage of a dart process after what I think was an analyzer infinite parse loop. It always happened with incomplete definition of a generic variable.
Quitting vscode did not help I had to close the process through the activity manager.

**Describe the solution you'd like**
I think this could have been avoided if there was an option to only run analysis onSave rather than onType.

I usually know my code is incorrect syntactically or statically while typing and I don't want analysis to bother me until I actually save the document, since by then I was probably able to write at least syntactically correct code.

**Comment by DanTup** [comment]
> what I think was an analyzer infinite parse loop. It always happened with incomplete definition of a generic variable.

This sounds like https://github.com/dart-lang/sdk/issues/42229 which has recently been fixed and should show up in the next SDK release.

> I think this could have been avoided if there was an option to only run analysis onSave rather than onType.

Unfortunately this wouldn't work very well. The analysis server (which get stuck in this loop) is required to power other features like code completion, so if everything was delayed until you saved, you'd also lose things like hovers/code completion/code fixes/refactors until you save (and then as soon as you make a change, they'd all be invalidated again).

Given that (and hopefully issues like this will not occur often - or if they do, they will be fixed quickly) I don't think it there would be a lot of value in this. Hope that makes sense!

**Comment by jellyNoone** [comment]
Makes sense
