### ISSUE TITLE
Autocomplete not showing all the options it could have

### ISSUE THREAD

**Issue by paulononaka** [Dart-Code/Dart-Code#3070]
**Describe the bug**
Autocomplete not showing all the options it could have.

**To Reproduce**
1. `flutter create hello_world`
2. `code hello_world`
3. Open main.dart
4. At line 23 change `Colors.blue` to `Colors.b`
5. It is showing only `Colors.black` in the list.

**Expected behavior**
It should appear a list with `black, blue, etc`

**Screenshots**
![image](https://user-images.githubusercontent.com/449081/104751926-c5009e00-5734-11eb-8c0b-dce1c4fb9e34.png)

**Versions (please complete the following information):**

VS Code version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z (4 wks ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Name: Flutter
Id: dart-code.flutter
Description: Flutter support and debugger for Visual Studio Code.
Version: 3.18.1
Publisher: Dart Code
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

➜  hello_world flutter doctor -v
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-BR)
    • Flutter version 1.22.5 at /Users/paulononaka/fvm/versions/stable
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/paulononaka/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/paulononaka/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode-11.6.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Community Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • 515FE22E-61B4-42DC-8FA5-CCD74633C418 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

! Doctor found issues in 2 categories.

[Dart-Code-Log-2021-00-05 13-17-09.txt](https://github.com/Dart-Code/Dart-Code/files/5821707/Dart-Code-Log-2021-00-05.13-17-09.txt)

**Comment by DanTup** [comment]
I think this might be the size of the completion list has shrunk and needs expanding:

![Jan-18-2021 12-08-03](https://user-images.githubusercontent.com/1078012/104913679-de4c5900-5985-11eb-967e-db6bd0f25a9e.gif)

There was a bug in VS Code where changing the size while only a single item was shown would also store the height (https://github.com/microsoft/vscode/issues/110554).

Let me know if this doesn't seem to solve it. Thanks!

**Comment by paulononaka** [comment]
Wow, that was indeed my issue. I'd never guess that. Thank you!
