### ISSUE TITLE
Failed to register observatory port with mDNS with error -65555.

### ISSUE THREAD

**Issue by lukepighetti** [Dart-Code/Dart-Code#3072]
I don't have a reproduction for this, but I have run into a situation where I can launch with `flutter run` but trying to launch with the VSCode debug button I get this error

```
[VERBOSE-2:FlutterObservatoryPublisher.mm(101)] Failed to register observatory port with mDNS with error -65555.
[VERBOSE-2:FlutterObservatoryPublisher.mm(103)] On iOS 14+, local network broadcast in apps need to be declared in the app's Info.plist. Debug and profile Flutter apps and modules host VM services on the local network to support debugging features such as hot reload and DevTools. To make your Flutter app or module attachable and debuggable, add a '_dartobservatory._tcp' value to the 'NSBonjourServices' key in your Info.plist for the Debug/Profile configurations. For more information, see https://flutter.dev/docs/development/add-to-app/ios/project-setup#local-network-privacy-permissions
[VERBOSE-2:FlutterObservatoryPublisher.mm(101)] Failed to register observatory port with mDNS with error -65555.
[VERBOSE-2:FlutterObservatoryPublisher.mm(103)] On iOS 14+, local network broadcast in apps need to be declared in the app's Info.plist. Debug and profile Flutter apps and modules host VM services on the local network to support debugging features such as hot reload and DevTools. To make your Flutter app or module attachable and debuggable, add a '_dartobservatory._tcp' value to the 'NSBonjourServices' key in your Info.plist for the Debug/Profile configurations. For more information, see https://flutter.dev/docs/development/add-to-app/ios/project-setup#local-network-privacy-permissions
```

**Comment by DanTup** [comment]
I can't think of a reason this would only occur in VS Code, but if it's intermittent maybe that's just coincidence. There's an open issue in Flutter that I think may be related:

https://github.com/flutter/flutter/issues/72161

All of this code is deep within Flutter (there's no real iOS/device-platform specific code in the extension) so I don't think it's something that can be fixed here.

**Comment by lukepighetti** [comment]
Not sure if it's VSCode specific or attaching debugger specific or what. But this is happening consistently for me now. VSCode debug won't launch past the splash screen, but `flutter run` works perfectly fine. It may be upstream?

**Comment by DanTup** [comment]
If it's reliably reproducible only from VS Code, my guess would be something different in the environment. Does it make a difference if you use the terminal in VS Code versus running under the debugger?

**Comment by lukepighetti** [comment]
In both cases I am using the VSCode terminal. IE: success in VSCode terminal, failure with VSCode debug.

**Comment by lukepighetti** [comment]
I can't reproduce this today. I'm going to close this unless it crops up again.

**Comment by alechangbiao** [comment]
I'm facing the same problem on vscode, flutter runs on terminal but not on vscode debug,however everytime when I use an IKEv2 VPN the problem disappears.

**Comment by lukepighetti** [comment]
Yes, I am still having this problem.

**Comment by DanTup** [comment]
Can anyone provide a sample project that triggers this, and a log captured with **Capture Debugging Logs*?

**Comment by DanTup** [comment]
@lukepighetti are you still having this problem? Are you able to repro in a small project and/or capture a full verbose log?

**Comment by lukepighetti** [comment]
Dan I'm going to close this issue because I haven't seen it in the last 30 days. Will reopen if I do.

**Comment by simeonangelov94** [comment]
Hello,

I reproduced the problem. I cannot run the app on the device (White Screen). Please find the link --> https://github.com/flutter/flutter/issues/86418
