### ISSUE TITLE
Migrate from "dartfmt" to "dart format"

### ISSUE THREAD

**Issue by munificent** [Dart-Code/Dart-Code#3073]
Much like the migration from `pub` to `dart pub` (#2944), the `dartfmt` entrypoint in the Dart SDK is deprecated and will eventually go away (https://github.com/dart-lang/dart_style/issues/986). Instead, tools should invoke `dart format`. Note that the new entrypoint has a different (hopefully better!) CLI. Let me know if you want me to walk you through the differences.

If VSCode invokes the formatter, it should do so using `dart format` if the underlying Dart SDK is 2.10.0 or greater. We'll keep the old `dartfmt` entrypoint around for a while, but relatively soon it will start printing a deprecation warning. Let me know if you have any questions. :)

**Comment by DanTup** [comment]
Thanks for the ping! We don't actually ever call `dartfmt` directly here, all formatting is done through the anlaysis server (which is using the API in dart_style), so I don't believe there's anything to do here :-)
