### ISSUE TITLE
ElevatedButton/ any other button not working properly

### ISSUE THREAD

**Issue by Shubham-Agrawal1206** [Dart-Code/Dart-Code#3075]
**Describe the bug**
When I try to use button in flutter project, the property of onpressed and child, and any other property is not working.
It is showing 
The named parameter 'onPressed' isn't defined.
Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'onPressed'.dartundefined_named_parameter

**Screenshots**
If
![image](https://user-images.githubusercontent.com/57083796/104832622-62d0a600-58b8-11eb-8160-595e18236bcf.png)
 
![image](https://user-images.githubusercontent.com/57083796/104832646-8eec2700-58b8-11eb-8f83-feec53a73ac8.png)

**Versions (please complete the following information):**
 - VS Code version: 1.53.0-insider
 - Dart extension version: 3.18.1
 - Dart/Flutter SDK version:  1.25.0-8.3.pre

**Comment by DanTup** [comment]
Can you try running the **Flutter: Get Packages** command and see if that resolves the issue?

**Comment by Shubham-Agrawal1206** [comment]
It resolved this issue.
I will close this issue now.

**Comment by DanTup** [comment]
Glad to hear! I think this is related to https://github.com/flutter/flutter/issues/72807, where the analysis server is parsing with the wrong language version when there's no `.dart_tool/packages_config.json` file which causes it to misinterpret constructors using the `required` keyword.
