### ISSUE TITLE
Japanese string will be tofu on Flutter web only in VSCode debug mode.

### ISSUE THREAD

**Issue by aoisensi** [Dart-Code/Dart-Code#3076]
**Describe the bug**
I coded simple hello code with Flutter.
But, こんにちは will be tofu only launch from VSCode.

![image](https://user-images.githubusercontent.com/1350990/104808846-3ff8b000-582c-11eb-9974-775496ce970d.png)

**To Reproduce**
**Expected behavior**
**Versions (please complete the following information):**
All is here: https://github.com/flutter/flutter/issues/74113

Sorry for bad English.

**Comment by DanTup** [comment]
This appears to be a Flutter issue being tracked in https://github.com/flutter/flutter/issues/73628. For me, it reproduces both inside and outside of VS Code:

<img width="897" alt="Screenshot 2021-01-18 at 11 22 26" src="https://user-images.githubusercontent.com/1078012/104909502-db4e6a00-597f-11eb-9817-f8f717067508.png">

I'm not sure why it doesn't repro for you outside of VS Code though - is it possible you have a different version of Flutter set up on your `PATH` that is used by the terminal compared to configured in VS Code?

**Comment by aoisensi** [comment]
I have only one SDK. And I didn't install starndalone Dart.

**Comment by DanTup** [comment]
Strange - I'm not sure why you'd only see the problem from VS Code. Perhaps there's something different in the environment from the terminal. I do think https://github.com/flutter/flutter/issues/73628 is the correct issue though, I think once it's resolved the problem will go away.

**Comment by DanTup** [comment]
Oh, it looks like the problem only occurs for CanvasKit. So as a workaround, in VS Code you could try selecting the HTML renderer:

<img width="1006" alt="Screenshot 2021-01-19 at 17 26 05" src="https://user-images.githubusercontent.com/1078012/105070600-6f512c00-5a7b-11eb-8f08-9bd04b19578f.png">

VS Code will be using "auto" by default, whereas the terminal may be using HTML.

**Comment by aoisensi** [comment]
Nice
