### ISSUE TITLE
Flutter UI Guides not working properly in VS Code with LSP

### ISSUE THREAD

**Issue by HadyMash** [Dart-Code/Dart-Code#3079]
**Describe the bug**
I have an issue with flutter and visual studio code were the UI Guides don't show when I am writing my code but only show when I go to another file and then go back to the file I was editing. I have the Preview Flutter UI Guides setting on and have tried toggling the Custom Tracking and the problem is still not fixed. I also tried it on a MacOS machine and a Windows machine and the same unexpected behaviour happens. Please let me know if you need anything such as screenshots, screen recordings or any other info.

**To Reproduce**
1. Enable the 'Preview Flutter UI Guides setting
2. Restart VS Code
3. Write anything that would prompt the UI Guides to show up
4. Go to settings without changing anything
5. Go back the file you were editing

**[Screen recording](https://drive.google.com/file/d/1zpXoK8RKl9dGk2aCBtCgK58zwD3xR6cM/view?usp=sharing)**
Please feel free to skim through the video. What the video shows is that the UI Guides don't show on saving or typing but only show when I go to the settings, then back to the document. They even show if I don't save the document but go to the settings page then back.

**Expected behavior**
Similar to the behaviour in android studio, the UI guides should show up in the same window when I type the line, save, etc. I have format on type and format on save on and the issue still occurs.

**Versions (please complete the following information):**
 - VS Code version: 
 - Dart extension version: v3.18.1
 - Dart SDK version: 2.12.0-204.0.dev
 - Flutter SDK version: 1.26.0-2.0.pre.275

**Comment by DanTup** [comment]
Does this still occur if you enable the "LSP Preview" setting? The LSP version will soon become default so if it doesn't happen there, it will be fixed once we move over.

**Comment by HadyMash** [comment]
The "LSP Preview" setting is on. I tried turning it off and it worked perfectly. Might I know what the LSP setting does?

Many thanks!

**Comment by DanTup** [comment]
The LSP setting switches the protocol used to talk to the language server (which provides all of the analysis and language functionality). This might be affecting the timing of startup, or there might be some subtle differences in handling the outlines used to draw these lines - I'll see if I can track it down.

LSP will become default in the future (and eventually the only option), so if that's where the bug is it'll need to be fixed. Thanks!

**Comment by HadyMash** [comment]
Thanks!
I also noticed another issue. I friend of mine also had the same issue and he also had LSP on. After he turned it off, it worked perfectly.

However, when we joined a Live Share session, they didn't appear for him. He left the session and they appeared again. So then I tried joining his live share session and it didn't work. Should I mark this as a new issue or is it fine being here?

Many thanks!!

**Comment by DanTup** [comment]
> However, when we joined a Live Share session, they didn't appear for him. He left the session and they appeared again. So then I tried joining his live share session and it didn't work. Should I mark this as a new issue or is it fine being here?

It's probably the same issue. The issue was that the previews were not being updated correctly if the analysis results (the "Flutter outline" data) arrived while the file was already open because of a bad comparison between filenames/URIs.

I've pushed a fix - though if the issue still occurs once the next release goes out (likely around the end of the month), then do file a new issue to be looked at. Thanks!

**Comment by akshg05** [comment]
This is still happening :(

**Comment by HadyMash** [comment]
Hello @akshg05,
The problem was fixed for me with the update released after this post. Make sure that VS Code, Dart Code code extension are up to date, that might fix the problem.

**Comment by DanTup** [comment]
@akshg05 if you're still seeing issues on the latest versions of everything, please file a new issue with details and I'll take a look. Thanks!

**Comment by akshg05** [comment]
I'll upgrade to the latest version and update. Thanks!

**Comment by LeCongNam** [comment]
![image](https://github.com/user-attachments/assets/c0850868-0c45-46cc-8777-4b646130d441)
In 2024. you can enable in settings line 2
