### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by SharjeelMoqrabKhan** [Dart-Code/Dart-Code#3080]
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `3.18.1`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.52.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\SHARJE~1\AppData\Local\Temp\Dart-Code.dart-code-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by DanTup** [comment]
Are you able to attach the referenced file? Thanks!

> ⚠️ Make sure to attach this file from your home-directory:
> ⚠️c:\Users\SHARJE~1\AppData\Local\Temp\Dart-Code.dart-code-unresponsive.cpuprofile.txt
