### ISSUE TITLE
Errors when hovering over types or enum values

### ISSUE THREAD

**Issue by annagrin** [Dart-Code/Dart-Code#3082]
**Issue**

Errors when hovering over types. I am not sure the issue is in dart-code or webdev, so please let me know if I should redirect it.

**To Reproduce**
1. Install flutter
2. `cd flutter/examples/hello_world`
3. run `code .`
4. put a breakpoint on line containing call to `runApp`
5. debug
6. on breakpoint, hover mouse over any type or enum value (`Center`, `Text`, `Key`, `TextDirection`)
7. Observe `<error>:<getObject: NoSuchMethodError: The getter 'uri' was called on null.>` 

**Expected behavior**

No error - can we show the type information instead?

**Screenshots**

![image](https://user-images.githubusercontent.com/12737689/105099046-dfea4f80-5a5f-11eb-911e-92ad86a38ec5.png)

**Versions (please complete the following information):**
 - VS Code Version: 1.52.1
    Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
    Date: 2020-12-16T16:30:02.420Z
    Electron: 9.3.5
    Chrome: 83.0.4103.122
    Node.js: 12.14.1
    V8: 8.3.110.13-electron.0
    OS: Darwin x64 19.6.0

 - Dart extension version: v3.18.1

 - Dart SDK version: 2.12.0-237.0.dev (dev) (Sun Jan 17 17:49:12 2021 -0800) on "macos_x64"

 - Flutter doctor output:
[✓] Flutter (Channel master, 1.26.0-2.0.pre.403, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Xcode - develop for iOS and macOS
    ! Xcode 11.3.1 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.52.1)
[✓] Connected device (1 available)

**Comment by DanTup** [comment]
This seems to be coming back as an error in response to a `getObject` call.

[Here's the full log](https://github.com/Dart-Code/Dart-Code/files/5842032/web_error.txt)

This is what seems to happen:

- We call `evaluateInFrame` for the enum name (`MainAxisAlignment` in my repro)
- An `@Instance` is returned with an `id` of `"{\"injectedScriptId\":1,\"id\":2683}"`
- We call `getObject` for the object with that `id` (`"{\"injectedScriptId\":1,\"id\":2683}"`)
- The returned object has a `class` with an id `"classes|dart:_runtime|_Type"`
- We call `getObject` for the class with that `id` (`"classes|dart:_runtime|_Type"`)
- The response is an error

```
{
	"jsonrpc": "2.0",
	"error": {
		"code": -32603,
		"message": "
			getObject: NoSuchMethodError: The getter 'uri' was called on null.
			Receiver: null
			Tried calling: uri
		",
		"data": {
			"details": "
				#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
				#1      ClassHelper._constructClass (package:dwds/src/debugging/classes.dart:78:58)
				#2      ClassHelper.forObjectId (package:dwds/src/debugging/classes.dart:67:19)
				<asynchronous suspension>
				#3      AppInspector.getObject (package:dwds/src/debugging/inspector.dart:327:17)
				<asynchronous suspension>
				#4      VmServerConnection._delegateRequest (package:vm_service/src/vm_service.dart:1328:22)
				<asynchronous suspension>
			",
			"request": {
				"id": "38",
				"jsonrpc": "2.0",
				"method": "getObject",
				"params": {
					"isolateId": "1",
					"objectId": "classes|dart:_runtime|_Type"
				}
			}
		}
	},
	"id": "38"
}
```

It looks a bit like https://github.com/dart-lang/webdev/issues/965 though only for enums - is it possible `ClassHelper.forObjectId()` isn't handling enums correctly?

**Comment by DanTup** [comment]
btw if it's useful for you to be able to get the full log yourself when debugging, you can run the **Dart: Capture Debugging Logs** command in VS Code, then repro (eg. hover over the enum), then click **Cancel** on the logging notification. That should open a log with the VM service traffic as shown in the log above.

**Comment by annagrin** [comment]
@DanTup thanks for the trace! The `The getter 'uri' was called on null` error seems to be due to missing library reference for dart:_runtime. I need to dig deeper into it one dwds side, will open an issue there.

**Comment by DanTup** [comment]
np! I don't think there's anything to do here so will close this, but we can re-open if after that's resolved you think there's still something up here. Thanks!
