### ISSUE TITLE
Dont auto-select 1st item during auto complete.

### ISSUE THREAD

**Issue by awebdeveloper** [Dart-Code/Dart-Code#3091]
**Describe the bug**
Dont auto-select 1st item when typing **( )** after a function name. I like to have each property in new line. So after **( )** I press enter to go on a new line but instead 1st property is typed. This isn't desirable..

**To Reproduce**
1. Type any auto completable/ built-in function name
2. Type the ().
3. Notice the first option is auto selected

**Expected behavior**
Just auto complete don't auto select anything. I will manually select things.

**Screenshots**
<img width="751" alt="Screenshot 2021-01-22 at 10 26 58 PM" src="https://user-images.githubusercontent.com/1593429/105520663-fd8a1400-5d00-11eb-877d-1cf2e7f75de6.png">

**Versions (please complete the following information):**
 - VS Code version:

**Comment by DanTup** [comment]
Unfortunately the selection of the completion items is done by VS Code and we have no control over it. There is a setting `editor.suggestSelection` to control _which_ item is selected, but there's no option for not selecting any. Implementing that would need to be done in VS Code.

Some possible solutions:

- Press `esc` before pressing `<enter>` when completing
- Set the `"editor.suggestOnTriggerCharacters": false,` setting, which will prevent completion from automatically opening when you type the `(`
- File a VS Code issue requesting the ability to not have any item selected when completion first opens
- File a VS Code issue for a feature that would allow something like Ctrl+Enter to always insert a newline regardless of whether the completion list is open/selected.

Hope this helps!

**Comment by awebdeveloper** [comment]
thanks DanTup
