### ISSUE TITLE
Intellisense not working as expected

### ISSUE THREAD

**Issue by rooky1979** [Dart-Code/Dart-Code#3092]
Hi Guys,

I have VS Code on a Macbook Pro running VS Code V1.52.1 with the Flutter Extension V3.18.1 with Flutter V 1.22.5 and Dart Extension V3.18.1 Dart V2.10.4

I had to completely reinstall the entire IDE and extensions, etc after I broke it.

Everything works fine, however, on my VS Code, I noticed that when I type something in e.g. 'Text', the code complete box comes up with the options fine and it used to be that it would complete the code along with the parameters needed. E.g. clicking on 'Text(...)' would complete it to be 'Text()'

However, now, when I click on the 'Text(...)' in the code completion box, it doesn't do it and just says 'Text' and doesn't complete the code. For anything at all.

Have you come across this issue before and if so, any idea how to fix it?  I've looked online and the issues they have is that the intellisense isn't working full stop.  I am running the latest Flutter and Dart versions.  I tried an earlier version of Flutter to make sure it wasn't that and the issue is reproducible which it is. It's driving me bats!!!  I can't see anywhere in the settings either where to fix this.  But in preferences/settings, all the intellisense settings are ticked.

I keep seeing things about the settings.json file online and in mine all I have is one line of code in the project.  I am not sure if there is supposed to be more or not:

{
    "editor.codeActionsOnSave": null
}

In the settings.json file after doing a search on my mac I found this one that has this code in it that I found in a folder named 'Code.' I'm assuming it could be something to do with my IDE?

{
    "[dart]": {
        "editor.formatOnSave": true,
        "editor.formatOnType": true,
        "editor.rulers": [
            80
        ],
        "editor.selectionHighlight": false,
        "editor.suggest.snippetsPreventQuickSuggestions": false,
        "editor.suggestSelection": "first",
        "editor.tabCompletion": "onlySnippets",
        "editor.wordBasedSuggestions": false
    },
    "dart.previewLsp": true,
    "window.zoomLevel": 1,
    "kite.showWelcomeNotificationOnStartup": false,
    "C_Cpp.updateChannel": "Insiders"
}

I hope I have produced enough information for someone to help please. I've added a very short video of it too as I can only upload 10MB

Cheers
Matt

<img width="830" alt="Screen Shot 2021-01-22 at 1 35 24 PM" src="https://user-images.githubusercontent.com/74156579/105519768-bafd1300-5cd1-11eb-848b-51993ec194c9.png">

<img width="826" alt="Screen Shot 2021-01-22 at 1 35 33 PM" src="https://user-images.githubusercontent.com/74156579/105519792-c05a5d80-5cd1-11eb-9a88-42db9365b234.png">

https://user-images.githubusercontent.com/74156579/105522123-c140be80-5cd4-11eb-8845-751cd3f059d0.mov

**Comment by rooky1979** [comment]
Ok I fixed the issue

I opened up the settings.json file in the Code folder and went to this website
https://code.visualstudio.com/docs/editor/intellisense#_customizing-intellisense

In there it has the default intellisense settings.  They are different to the ones in my settings.json file

I backed up the settings file and then copied/pasted the default settings code into my settings.json file and VOILA it's now back up and running as it should with intellisense working perfectly.

I have no idea why the settings are different but I'm not experienced enough to know why.  All I know is there is a solution and I hope this helps someone else out in the future.

Cheers

**Comment by DanTup** [comment]
My guess is that when you updated your settings, you removed `"dart.previewLsp": true,`. LSP is a new protocol for the language server, and in order to get the parens/args inserted, you need to also enable the `dart.completeFunctionCalls` setting - however that setting hasn't yet made it to the Flutter stable channel (it will show up in the next major stable release).

FWIW, LSP will become default in a future release (after the next Flutter major stable release).

**Comment by rooky1979** [comment]
Thanks Dan.  Good to know for the future.  Cheers
