### ISSUE TITLE
Extension causes high cpu load on startup

### ISSUE THREAD

**Issue by DattaTarse** [Dart-Code/Dart-Code#3096]
getting Extension causes high cpu load on startup notification when its started.
[salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt](https://github.com/Dart-Code/Dart-Code/files/5864267/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt)

 Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by DanTup** [comment]
The CPU profile attached is for the extension [salesforce.salesforcedx-vscode-core](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode-core). This seems unrelated to Dart and should be raised at https://github.com/forcedotcom/salesforcedx-vscode. Thanks!
