### ISSUE TITLE
Allow names to be supplied for extracted methods/widgets when using LSP

### ISSUE THREAD

**Issue by linxkaa** [Dart-Code/Dart-Code#3103]
**Describe the bug**
Autocomplete on VSCode is not working, usually when i extract widget, there's a suggestion that located above VSCode that says "Enter a name for the widget (Press 'Enter' to confirm or 'Escape' to cancel)" now its just automatically extracted as "NewWidget" also when I want to write for example SizedBox, usually when i click the suggestions, it will include the (), but now when i click SizedB, it didn't autocomplete to 'SizedBox()'.

The same thing when i want to use a function. usually when i had list, then i press .map on suggestion, it will autocomplete to MyList.map((e) => null), but now it only become MyList.map even though i already press the 1st suggestion

**Things i tried to fix the error**
1. Already uninstall VSCode
2. Downgrade Dart & Flutter extensions
3. Restart VSCode
4. Restart my Mac
5. Shutdown my Mac then turn it on again
6. Modify my setting json into this:
```json
"[dart]": {
    "editor.formatOnSave": true,
    "editor.formatOnType": true,
    "editor.rulers": [200],
    "editor.selectionHighlight": false,
    "editor.suggest.snippetsPreventQuickSuggestions": false,
    "editor.suggestSelection": "first",
    "editor.tabCompletion": "onlySnippets",
    "editor.wordBasedSuggestions": false,
    "files.insertFinalNewline": true
  },
```

**Screenshots**
<img width="1036" alt="Screen Shot 2021-01-26 at 10 44 27" src="https://user-images.githubusercontent.com/57997512/105797874-79b37e80-5fc3-11eb-84d2-45dd3f7a9e08.png">
⬆when i tried to extract the widget

<img width="971" alt="Screen Shot 2021-01-26 at 10 45 11" src="https://user-images.githubusercontent.com/57997512/105797931-9485f300-5fc3-11eb-8627-7922168f9cb1.png">
⬆its still showing suggestion, but when i click the 1st suggestion, it will only become SizedBox, not SizedBox()

**Versions:**
 - VS Code version: 1.52.1
 - Dart extension version: 3.18.1
 - Dart/Flutter SDK version: 
    Dart: 2.10.2
    Flutter SDK: 1.22.2

Please help, idk what to do, it really slows my progress to code.

**Comment by linxkaa** [comment]
Fixed! 

```json
"dart.previewLsp": false
```

 in setting.json :)

i'm closing this issues thankyou

**Comment by DanTup** [comment]
Right now for LSP, the extract functions don't allow you to enter a name. This is a limitation of LSP (see https://github.com/microsoft/language-server-protocol/issues/764).

LSP is going to become the default soon, so this issue will crop up more, so I'll see if I can find a workaround in the meantime.
