### ISSUE TITLE
Could not find an option named "run-skipped".

### ISSUE THREAD

**Issue by orestesgaolin** [Dart-Code/Dart-Code#3107]
**Describe the bug**
After the today's update I get following error when trying to debug a widget test:

```
Could not find an option named "run-skipped".
```

The only additional argument passed to test run is `--coverage` and these tests worked before the update (in the morning).

![image](https://user-images.githubusercontent.com/16854239/106305520-15abe700-625d-11eb-9569-a6cdac332dfe.png)

**To Reproduce**
1. Open test file
2. Try to debug a test by clicking code lens label "Debug"
![image](https://user-images.githubusercontent.com/16854239/106305326-d7aec300-625c-11eb-91d6-e3dd40235d64.png)
3. Observe error in the console

**Expected behavior**
Test should be debugged.

**Screenshots**

**Versions (please complete the following information):**
 - VS Code version: Version: 1.52.1
 - Dart extension version: v3.19.0
 - Dart/Flutter SDK version: 1.22.6

**Comment by DanTup** [comment]
Thanks for the report! This seems to have occurred with the new "run skipped" feature. Flutter doesn't seem to support the flag.

I'm testing a fix that removes that feature and will publish a new update soon, and the feature will return in a later release.

**Comment by orestesgaolin** [comment]
Thanks for the extremely quick response, really appreciate that

**Comment by DanTup** [comment]
Please run the **Extensions: Check for updates** command in VS Code, and once you have v3.19.1 this should be resolved (it may take a few minutes to show up, there's a lot of caching in the VS Code marketplace services).

Please let me know if still have any issues. Thanks!

**Comment by orestesgaolin** [comment]
Confirmed, it's fixed now. Thanks again
