### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by KshitijJayakar** [Dart-Code/Dart-Code#3113]
- Issue Type: `Bug`
- Extension Name: `dart-code`
- Extension Version: `3.19.1`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.52.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by DanTup** [comment]
> ⚠️ We have written the needed data into your clipboard. Please paste! ⚠️

Are you able to supply this data? Thanks!
