### ISSUE TITLE
Icon previews are not shown

### ISSUE THREAD

**Issue by olostan** [Dart-Code/Dart-Code#3115]
**Describe the bug**
Icons previews are not shown.

**To Reproduce**
1. Open intellisense for `Icon.<anything>`

**Expected behavior**
Something like
![](https://user-images.githubusercontent.com/1078012/45706869-464fc200-bb75-11e8-8f8f-4b09fa94470d.png)

**Screenshots**
![Screenshot 2021-02-01 18 40 08 - Display 1](https://user-images.githubusercontent.com/459897/106496344-0f1baa80-64bd-11eb-9ff9-d0ffdd5063c2.png)

**Versions (please complete the following information):**
 - VS Code version: 1.52.1
 - Dart extension version: 3.19.1
 - Dart/Flutter SDK version: Flutter 1.26.0-18.0.pre.90

After toggling Developer Tools I don't see any relevant error message. 
Log from Dart-Code extension: https://pastebin.com/Z88cfCQj

**Comment by DanTup** [comment]
In the top screenshot the "details" section is open, but in the bottom screenshot it is closed. You can press Ctrl+Space to toggle the display of that pane when the completion list is open (and the current item has some extra details).

If you press Ctrl+Space does the pane appear with the preview?

**Comment by olostan** [comment]
@DanTup sorry, my bad. I did not know about "double Ctrl+Space" possibility. Closing the issue.

**Comment by DanTup** [comment]
No problem, glad it was an easy solution! :) I don't think that feature is as discoverable as it could be, but unfortunately that's entirely controlled by VS Code so and the extension can't influence it.
