### ISSUE TITLE
Multiline test descriptions not shown completely in test tree

### ISSUE THREAD

**Issue by HerrNiklasRaab** [Dart-Code/Dart-Code#3119]
See the test: "has not been synchronized with a bike, 
              than it should return false when calling isSynchronizedWith"

![image](https://user-images.githubusercontent.com/28401593/106643638-ad2d7480-6592-11eb-9c16-3a48a6058d4c.png)

**Comment by HerrNiklasRaab** [comment]
> It may be better to use adjacent string literals to split the text over two lines, so there's no actual newline and/or indenting in the actual test name?

I agree, but I think it should still work. Either by making the entry in the test tree multiline, or replacing the line breaks with whitespaces.

**Comment by DanTup** [comment]
I ended up tidying the indentation anyway, so they look a little neater.

![Screenshot 2021-02-16 at 18 54 38](https://user-images.githubusercontent.com/1078012/108109014-47a8b000-7089-11eb-80bd-ed7fe47b730b.png)
