### ISSUE TITLE
Debugger Restart button does not work (throws error)

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#312]
Clicking the Restart button doesn't seem to work as expected:

![Restart](https://user-images.githubusercontent.com/1078012/26871995-f08e6ba6-4b6c-11e7-989b-4befe177dbe4.png)

**Comment by DanTup** [comment]
Not sure if we're doing something wrong or if this is a Code bug. Raised https://github.com/Microsoft/vscode/issues/28175

**Comment by DanTup** [comment]
@devoncarew Could you possibly cast your eye over these changes and see if they look good to you (seems to work fine in my simple testing):

https://github.com/Dart-Code/Dart-Code/compare/support-debugger-restart

The original issue was that when we switched to using sessionStartCommand (15f75c1730d204c8ff825dadb1dfb3f949f800f4) to remove some of the "internal" junk from launch.json I didn't notice restart got broken (because Code doesn't re-supply all the extra params on a restart - see https://github.com/Microsoft/vscode/issues/28175). The fix (which doesn't rely on Code being updated) is to handle the restart request directly (which we'll likely do for Flutter anyway), though that means cleanly terminating the process and restarting it, with some niggles to avoid the terminating process terminating the debugger.

I did consider extracting most of this class into another, which could own both the (Dart) process and the Observatory connection, so DartDebugSession just becomes a wrapper than can easily create new processes/debuggers to keep all the state out of here; but it might be overkill just to handle clean restarts.

**Comment by DanTup** [comment]
@devoncarew actually, since MS fixed https://github.com/Microsoft/vscode/issues/28175 I think I'm gonna revert all this. Having Code do the right thing natively seems a better option that all these hacks to avoid the event handlers of the old process interfering with the new one! I'll test it in Insiders when next working on this and if it works, through this away!

**Comment by devoncarew** [comment]
ah, ok, sgtm, and sorry for the delayed response -

**Comment by DanTup** [comment]
From next version, we'll output a nicer message when this occurs:

> Unable to restart debugging. Please try ending the debug session and starting again.

Once the fix in Code is live, this will only occur when a user modifies `launch.json` during a debug session and then hits `Restart`.

**Comment by DanTup** [comment]
Fixed in VS Code. There's a remaining edge case where you edit `launch.json` while debugging and it'll trigger again, but we now detect this and show a nice message instead of crashing.
