### ISSUE TITLE
vscode: Your Dart SDK has been updated

### ISSUE THREAD

**Issue by moodstubos** [Dart-Code/Dart-Code#3125]
while working with vscode I regularly get the following message from the dart extension:

`Your Dart SDK has been updated. Reload using the new SDK?`

my environment:

vscode: 1.53.0
dart extension: 3.19.1
dart binaries comming from flutter stable, 1.22.6

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.746], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.   
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.53.0)
[√] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Comment by readyiman** [comment]
@moodstubos did your VSCode version was 1.53.0 instead of 0.53.0? I have similar issues.
And did you press reload? did anything happens? 
For me, the Flutter's hot reload button on Run buttons group was suddenly missing, and Debug Console auto scroll seems broken. I'm not sure it happens before or after I press the reload button. 
Btw I had filled that bug on VSCode https://github.com/microsoft/vscode/issues/115945

**Comment by DanTup** [comment]
@readyiman 

> For me, the Flutter's hot reload button on Run buttons group was suddenly missing

This sounds like a different problem - please file a new issue and include screenshots of what's not working. Thanks!

**Comment by DanTup** [comment]
@moodstubos please run the **Check for Extension Updates** command in VS Code, and after upgrading to v3.19.2 of the Dart extension, click the **Reload** button. This should resolve the issue, but please let me know if it does not. Thanks!

**Comment by readyiman** [comment]
@DanTup

> This sounds like a different problem - please file a new issue and include screenshots of what's not working. Thanks!

 It seems VSCode bug. I had found the cause of it, and commented there.

> This should resolve the issue, but please let me know if it does not.

It seems resolved for me, I had using it for this few hours without this issue.

**Comment by moodstubos** [comment]
@DanTup
issue has been solved. Thanks a lot.
