### ISSUE TITLE
Flutter channel master VS code colors not correct

### ISSUE THREAD

**Issue by ljmatan** [Dart-Code/Dart-Code#3126]
**Describe the bug**
After switching out my Flutter install version from master to stable and back, my code color formatting is no longer correct.

Right after the switching, I've encountered the following issue: microsoft/vscode#115481

Swapping out the version for beta or stable seems to fix the problem. Please note: where the text is blue it's supposed to be white, I no longer see "symbols" such as \n formatted nicely, etc.

A full reinstall of VS code and it's plugins, and of course multiple changes of the channel did not fix the issue.

**Versions (please complete the following information):**
 - VS Code version: Latest linux, latest linux insider version
 - Dart extension version: 3.19.0
 - Dart/Flutter SDK version: 2.12.0 Dart / latest master Flutter

**Comment by DanTup** [comment]
Can you post details of the theme you're using, or a screenshot of before/after?

The reason for the change is that we're now using "Semantic Tokens" (see https://dartcode.org/releases/v3-19/#lsp-semantic-tokens). There are some differences that are expected, and that includes variables may now be coloured (they went from white to light blue in the Dark+ theme I use), which separates them from things like parens and `=>`.

<img width="700" alt="semantic_tokens" src="https://user-images.githubusercontent.com/1078012/107064279-3cc16600-67d3-11eb-8130-f4690542e9de.png">

If you don't like this, you can disable semantic tokens in your VS Code user settings (either globally, or just for the Dart language by editing the language-scoped settings).

**Comment by ljmatan** [comment]
So in the thread I've linked in my original post you can see an issue is present - @override is not monocolored, as I presume it should be. 

Going  to settings.json in VS Code and setting "dart.previewLsp" to false returned the state to what it was earlier so as far as I'm concerned the issue can be closed.

**Comment by DanTup** [comment]
>  @override is not monocolored, as I presume it should be.

This is actually intended, the `@` for the annotation is coloured one way, but the rest of the annotation is coloured based on whether it's a constructor, getter etc.

> Going to settings.json in VS Code and setting "dart.previewLsp" to false returned the state to what it was earlier so as far as I'm concerned the issue can be closed.

LSP is going to become the default soon, so this issue will come back. Although you could turn off semantic tokens, you'll get back all of the issues it was intended to fix as seen in [the release notes](https://dartcode.org/releases/v3-19/#lsp-semantic-tokens).

**Comment by ljmatan** [comment]
Thank you for the detailed info, Mr. Danny.

**Comment by satyyyaamm** [comment]
> > @override is not monocolored, as I presume it should be.
> 
> This is actually intended, the `@` for the annotation is coloured one way, but the rest of the annotation is coloured based on whether it's a constructor, getter etc.
> 
> > Going to settings.json in VS Code and setting "dart.previewLsp" to false returned the state to what it was earlier so as far as I'm concerned the issue can be closed.
> 
> LSP is going to become the default soon, so this issue will come back. Although you could turn off semantic tokens, you'll get back all of the issues it was intended to fix as seen in [the release notes](https://dartcode.org/releases/v3-19/#lsp-semantic-tokens).

LSP resolved my issue

**Comment by Tasen-pro** [comment]
> Can you post details of the theme you're using, or a screenshot of before/after?
> 
> The reason for the change is that we're now using "Semantic Tokens" (see https://dartcode.org/releases/v3-19/#lsp-semantic-tokens). There are some differences that are expected, and that includes variables may now be coloured (they went from white to light blue in the Dark+ theme I use), which separates them from things like parens and `=>`.
> 
> <img alt="semantic_tokens" width="700" src="https://user-images.githubusercontent.com/1078012/107064279-3cc16600-67d3-11eb-8130-f4690542e9de.png">
> 
> If you don't like this, you can disable semantic tokens in your VS Code user settings (either globally, or just for the Dart language by editing the language-scoped settings).

It would be nice if annotation like @override were back to blue color in stead of light blue which is the same as variable color
