### ISSUE TITLE
Attach to Flutter Process sometimes can't resolve source code locations

### ISSUE THREAD

**Issue by knopp** [Dart-Code/Dart-Code#3128]
The culprit seems to be in `dart_debug_impl.ts`.
```js
if (!this.packageMap) {
     // TODO: There's a race here if the isolate is not yet runnable, it might not have rootLib yet. We don't
     // currently fill this in later.
    if (rootIsolate && rootIsolate.rootLib)
        this.packageMap = PackageMap.load(this.logger, 
             PackageMap.findPackagesFile(this.convertVMUriToSourcePath(rootIsolate.rootLib.uri)));
}
```
I haven't figured out the exact reason, but sometimes `rootIsolate.rootLib.uri` is a package:// Uri, which means we'll end up with `MissingPackageMap`.

**Comment by DanTup** [comment]
It looks like this may have been an issue before, as we allow specifying the package location in the launch config for attach requests:

https://github.com/Dart-Code/Dart-Code/blob/0d30b1a3c102a4b2e71b4fd233130aad1331e14d/src/debug/dart_debug_impl.ts#L298-L310

So I think if you add:

```js
"packages": "/path/to/package-file-or-project-folder"
```

To your launch.json config, that may resolve the issue?

**Comment by knopp** [comment]
@DanTup, that seems to do the trick!
