### ISSUE TITLE
Analyzing forever (LSP Preview enabled)

### ISSUE THREAD

**Issue by Reprevise** [Dart-Code/Dart-Code#3132]
**Describe the bug**
Ever since the latest Dart Code update 3.19.2, the analyzer initially worked fine but now it's constantly analyzing (at least I'm getting the notification that it's analyzing that I can't dismiss).

**Expected behavior**
If this is just a notification issue with the extension then I would expect the notification to go away when it's finished but if the analyzer is actually constantly running then ideally it wouldn't be while I'm not writing any code.

**Versions (please complete the following information):**
 - VS Code version: 1.53.0
 - Dart extension version: 3.19.2
 - Dart/Flutter SDK version: Dart 2.10.5, Flutter 1.22.6

**Comment by DanTup** [comment]
Can you reproduce this in a newly created sample app? If so, could you enable the analysis server log and attach a log?

https://dartcode.org/docs/logging/#analyzer

Note: the log may contain parts of source code, so it's best to reproduce on a small sample project. Thanks!

**Comment by easydo247** [comment]
If a manually run _flutter analyze_ the process does not complete
Analyzing my_project...                                                  
(This is taking an unexpectedly long time.)

**Comment by DanTup** [comment]
@easydo247 if you're seeing that from the command line, that suggests it's not an issue with the VS Code plugin. If you run it with the `-v` flag (`flutter -v analyze`) you should get verbose output that might help understand what's going wrong. It would likely need raising at https://github.com/flutter/flutter/ or https://github.com/dart-lang/sdk depending on the output.
