### ISSUE TITLE
Flutter VSC Extension Requires Save, Even with Auto Save Enabled?

### ISSUE THREAD

**Issue by mprogers** [Dart-Code/Dart-Code#3134]
I could have _sworn_ that if I had Flutter in debug-mode, with auto save turned on in Visual Studio Code, that all I had to do was change the code and the app would update. My students thought it was magical. (as did I). Now, though, I need to save the code first (which is admittedly not a biggie, but still ...). This is with Visual Studio Code 1.53.0, VSC extension v3.19.0, macOS Big Sur 11.3.

Did the behavior change? Or did I break something? Or was I just imagining it (in which case, I'd like to make a feature request ...).

**Comment by DanTup** [comment]
The behaviour did change in the last version. The previous behaviour was unintended and caused some issues, and was fixed as a bug. However, it seems many people were happy with it working that way and had no issues, so in the next version the reload-on-save option will have a new setting (`"always"`) that will cause it to run even for auto saves (see #3110).

Sorry for the inconvenience!
