### ISSUE TITLE
VsCode quick fix "Create File" function failed to Create file successfully

### ISSUE THREAD

**Issue by awagege** [Dart-Code/Dart-Code#3141]
**Describe the bug**
When importing a file that does not exist, using the quick fix "create file" did not automatically create the file, and there was no abnormal prompt

**To Reproduce**
1.Introduce non-existent files in dart code
2.Use "quick fix"
3.Use "create file"

**Expected behavior**
Let "create file" successfully create this file

**Screenshots**

**Versions (please complete the following information):**
 - VS Code version:1.53.2
 - Dart extension version:dart 3.19.2 flutter 3.19.0
 - Dart/Flutter SDK version:dart 2.10   flutter 1.22.6

**Comment by DanTup** [comment]
This is fixed by https://github.com/dart-lang/sdk/commit/c8c49c7cc80d561ff93e17bbd44ada3ccb60582f. The fix is in the analysis server, so will arrive in a future Dart/Flutter SDK update rather than a Dart-Code update.

Thanks for the report!
