### ISSUE TITLE
Running dart fomatter never finishes after 1or 2 hours of coding and a running a flutter app

### ISSUE THREAD

**Issue by IsmailAlamKhan** [Dart-Code/Dart-Code#3144]
**Describe the bug**
'Running dart fomatter' command never ends  after 1/2 hours of coding and running a flutter ap

**To Reproduce**
1. Run and code a flutter app for 1 or 2 hours.

**Expected behavior**
'Running dart fomatter' command should finish its work and not hang there.

**Screenshots**
![image](https://user-images.githubusercontent.com/67656229/108085542-a5e08d80-709f-11eb-8e64-46a1ace40ddf.png)

**Versions (please complete the following information):**
 - VS Code version: 1.53.2
 - Dart extension version: 3.19.2
 - Dart/Flutter SDK version: 1.22.6 (Stable)

**Comment by DanTup** [comment]
@IsmailAlamKhan can you reliably reproduce this? I've seen it once, and had a few reports of it, though never been able to reproduce it to debug.

Reliable steps to trigger this (I've worked on Flutter apps for several hours without seeing it, so I'm not sure it's just as simple as just that) would be appreciated!

**Comment by IsmailAlamKhan** [comment]
@DanTup that issue is random. Sometimes I can work the whole day without getting that. Sometimes I can't even work for 1 hour. B.T.W this mostly happens when VsCode stays idle for some time

**Comment by DanTup** [comment]
Can you confirm if you have the Dart LSP Preview enabled in your VS Code user settings, and which Flutter branch you're on?

One thing that might help, is an analysis server log when this happens. (Note: This log will contain parts of your source code, so don't share the whole log if it's not a public project).

You can [enable the analysis server log](https://dartcode.org/docs/logging/#analyzer) with the `dart.analyzerLogFile` setting. It will cause the traffic to the analysis server to be logged to the filename specified. It may grow large over a long session, but will be overwritten and start from 0 for each new session.

If you leave that log file enabled, then next time you see this issue take a copy of it, then the lines preceding the format request might help identify what the server was doing when it didn't respond to the format request for a long time.

**Comment by IsmailAlamKhan** [comment]
@DanTup no I don't have LSP enabled. I enabled the log setting, will give you the file once I get the issue.

**Comment by IsmailAlamKhan** [comment]
[dartlog.txt](https://github.com/Dart-Code/Dart-Code/files/6009465/dartlog.txt)
@DanTup here is the dartlog.

**Comment by DanTup** [comment]
@IsmailAlamKhan there don't appear to be any Format requests in that log file - did you copy the file after seeing the issue above?

**Comment by IsmailAlamKhan** [comment]
yes. I will send another one if I encounter that issue again. Also some times the code completion stops working.

**Comment by DanTup** [comment]
@IsmailAlamKhan if you can capture a log when it stops working (and a screenshot showing exactly what you see), that may help too. Some people have found completion works better with the LSP preview enabled (which will become default in the future), so you might wish to try that out.

**Comment by IsmailAlamKhan** [comment]
Yes with LSP the overall performance is better. But the only problem is when extracting a widget or method with LSP enabled the name dialog or the popup doesn't appear.

**Comment by DanTup** [comment]
I've actually fixed that recently in https://github.com/Dart-Code/Dart-Code/issues/3103 :) It'll be in the next release of Dart-Code.

**Comment by IsmailAlamKhan** [comment]
I am closing this issue cause turning on the LSP seems to fix my issue.

**Comment by DanTup** [comment]
That's good to hear - LSP will become the default and non-LSP removed in the future.

There's a beta version of the next Dart-Code that includes the Extract Widget/Method name fix if you'd like to try that out before it releases too -> https://github.com/Dart-Code/Dart-Code/releases/tag/v3.20.0-beta.1

**Comment by IsmailAlamKhan** [comment]
@DanTup thank you so much
