### ISSUE TITLE
Speed up the code suggestions and only show relevant suggestion and properties first

### ISSUE THREAD

**Issue by fisforfaheem** [Dart-Code/Dart-Code#3150]
i am tired of getting useless multiple other kind of suggestions in dart why?

**Comment by DanTup** [comment]
Are you able to provide some more specific details, such as how long completions are taking, and some specific examples of where you think the ranking is bad?

There are some open issues about ranking in the SDK (such as https://github.com/dart-lang/sdk/issues/38739 and https://github.com/dart-lang/sdk/issues/43657) but more examples are always useful.

It's also worth bearing in mind that the Dart extension/language server only control the ranking when there is no prefix in your code. Once you start typing (or if you invoke completion in an existing identifier), the ranking is controlled by VS Code (see https://github.com/microsoft/vscode/blob/cb1dce0ef30d48c4259eb7d0a923926b3e6e16af/src/vs/vscode.d.ts#L3855-L3863).

Can you also confirm whether you have the "Dart: Preview LSP" setting enabled in VS Code, as the completion lists are built quite differently depending on that setting (generally I would expect LSP to be faster, and it will soon become the default - however there are still some issues with LSP in the current stable Flutter release).

**Comment by fisforfaheem** [comment]
![image](https://user-images.githubusercontent.com/35878088/108375225-968a4d00-7223-11eb-80ec-2b1e27930858.png)
 this is the settings for it.

**Comment by DanTup** [comment]
@fisforfaheem thanks, looks like you already have LSP enabled (which is good, since that's going to become the default option).

Can you confirm what sort of delays you're seeing on completion and whether this is consistent, or just in certain circumstances, and some examples of where the ranking is bad? Thanks!

**Comment by fisforfaheem** [comment]
When i am working on a project, when i press ctrl+. etc the suggestions take a while to open up etc these kind of slowness...also the suggestions should match the widget properties but sometimes it wont work as it should.

**Comment by DanTup** [comment]
@fisforfaheem do you mean `Ctrl+Space` for completions, or `Ctrl+.` for quick-fix/lightbulb?

Are you able to take a screenshot showing the location where you invoked the completion next time you see it slow?

> also the suggestions should match the widget properties but sometimes it wont work as it should.

Could you also get a screenshot of this, so there's a specific case to look at? I suspect it's something like https://github.com/dart-lang/sdk/issues/38739, but without a concrete example it's hard to be sure.

Thanks!

**Comment by fisforfaheem** [comment]
Ok i will send here, after some screnshoots.

**Comment by fisforfaheem** [comment]
here is one screenshot please see this: it's not the desired suggestion..
![Uploading Screen Shot 2021-02-19 at 7.13.27 PM.png…]()

**Comment by fisforfaheem** [comment]
![Screen Shot 2021-02-19 at 7 13 27 PM](https://user-images.githubusercontent.com/35878088/108515506-f7c72480-72e6-11eb-9dea-5cd54a34ff21.png)
![Uploading Screen Shot 2021-02-19 at 7.13.27 PM.png…]()

**Comment by fisforfaheem** [comment]
![Screen Shot 2021-02-19 at 7 18 27 PM](https://user-images.githubusercontent.com/35878088/108515817-5391ad80-72e7-11eb-98c5-427182073fae.png)

**Comment by fisforfaheem** [comment]
It should show the most immediate and proper suggestions why does it shows useless suggestions first???

![Screen Shot 2021-02-19 at 8 31 00 PM](https://user-images.githubusercontent.com/35878088/108525034-7fb22c00-72f1-11eb-904d-8943eb590fa6.png)

**Comment by DanTup** [comment]
The completion sorting issue is discussed in https://github.com/Dart-Code/Dart-Code/issues/3153.

Can you clarify whether the speed issue you're seeing is when opening completion (`Ctrl+Space`) or quick-fixes (`Ctrl+.`)? It may be a dupe of https://github.com/Dart-Code/Dart-Code/issues/3152.

**Comment by fisforfaheem** [comment]
Yeah Thanks hope the flutter responsible persons will fix it soon! also it's more of  a latency issue... as it takes some time...as compared to VS studio ide which was way too fast

**Comment by DanTup** [comment]
@fisforfaheem can you clarify the question above? Exactly which action is slow? And (approximately) how slow? Does it occur only after specific actions (for example while "analyzing" is showing in the status bar), or always?

**Comment by fisforfaheem** [comment]
when we are writing something...it show suggestions not instantly as
say..VStudio IDE, it takes some time and lags too a bit

**Comment by DanTup** [comment]
@fisforfaheem can you give an idea of how long it's taking? It definitely won't be _instant_ as there's a bit of a round trip (VS Code asynchronously sends a request to the extension, which then sends it to the Dart language server, which computes the list, and then sends it back), however it definitely shouldn't feel slow. 

If you invoke completion a few times, then run the **Dart: Open Aanlyzer Diagnostics** command from the VS Code command palette, it should open a web app with some diagnostics. Click **Code Completion** on the left, and it should give timings for the _servers_ part of completion. I'd be interested to see what sort of numbers you have here:

<img width="980" alt="Screenshot 2021-03-01 at 11 49 59" src="https://user-images.githubusercontent.com/1078012/109493361-46fa1b80-7a84-11eb-8042-4f1ec7c85a4c.png">

**Comment by fisforfaheem** [comment]
Thanks for your response. Will let you soo, currently removing
everything and reinstlaling everything and
