### ISSUE TITLE
Preview LSP Option changing syntax highlighting

### ISSUE THREAD

**Issue by HadyMash** [Dart-Code/Dart-Code#3155]
**Describe the bug**
When the LSP Preview option is enabled, the syntax highlighting gets messed up and anything that was previously white with the OneDark Pro theme (not sure about other themes) becomes red. Turning off Preview LSP fixed the issue.

**To Reproduce**
1. Enable Preview LSP
2. Cmd/Ctrl + Shift + P and then reload window.
3. Let VS Code load a .dart file.

**Expected behavior**
It should be white (One Dark Pro)

**Versions (please complete the following information):**
 - VS Code version: 1.53.2
 - Dart extension version: 3.19.2
 - Dart/Flutter SDK version: 2.12.0-204.0.dev

**Comment by DanTup** [comment]
This appears to be working as expected.

Pre-LSP, the code did not have full semantic tokens. This meant the highlighting left a lot of things uncoloured (white). With LSP and semantic tokens, theming is able to do much more. The theme you have picked has been coded to show variables in red:

<img width="635" alt="Screenshot 2021-02-23 at 15 25 20" src="https://user-images.githubusercontent.com/1078012/108865879-95726a80-75eb-11eb-9126-ee92c8b00b74.png">

Using the "Inspect Editor Tokens and Scopes" command in VS Code, you can see the tokens that are assigned and what colour they're getting from the theme:

![Screenshot 2021-02-23 at 15 24 25](https://user-images.githubusercontent.com/1078012/108865970-ac18c180-75eb-11eb-8859-84111271d8a8.png)

If you open up another language that supports semantic tokens - for example TypeScript - you'll also see the variables are red:

![Screenshot 2021-02-23 at 15 25 44](https://user-images.githubusercontent.com/1078012/108866017-b63ac000-75eb-11eb-9ab7-592df8aca161.png)

So this seems deliberate (or if not, is a bug in the theme). However, you can override the colours assigned by a theme if you'd like. For example adding this to my user settings will force the variables to be green:

```js
"editor.tokenColorCustomizations": {
	"[One Dark Pro]": {
		"variables": "#00FF00"
	}
}
```

![Screenshot 2021-02-23 at 15 29 38](https://user-images.githubusercontent.com/1078012/108866274-f437e400-75eb-11eb-9cd4-bc54938cf9a4.png)

Hope this makes sense!

**Comment by HadyMash** [comment]
> So this seems deliberate (or if not, is a bug in the theme). However, you can override the colours assigned by a theme if you'd like. For example adding this to my user settings will force the variables to be green:
> 
> ```js
> "editor.tokenColorCustomizations": {
> 	"[One Dark Pro]": {
> 		"variables": "#00FF00"
> 	}
> }
> ```
Thank you very much for your help!
Would this work if I paste it inside of the [Dart] settings or would this be universal?

**Comment by HadyMash** [comment]
@DanTup Thank you very much for your help!

I was just wondering if there was any way to make the `@override`be the same colour as the `@`, at the moment, after turning on LSP and using One Dark Pro, the `@` is yellow and `override` is whatever colour variables are. Before turning LSP on, both were pink, I do not mind having it be yellow, just would like it to have one colour.

Thank you for all of your help and sorry for the many questions.

**Comment by DanTup** [comment]
@HadyMash the part after the `@` is coloured based on whether it's a getter/Class/constructor etc., which is why they don't match. For example:

<img width="267" alt="Screenshot 2021-02-24 at 13 17 04" src="https://user-images.githubusercontent.com/1078012/109006101-9b775280-76a2-11eb-9cd5-3f3137c52d24.png">

So there isn't a colour that could be applied to the `@` that would match both.

That said, the color of the `@` probably should be overridable, but right now it seems like it is not. If you want to override it (and are happy with just a single color even though it might not match all annotations) please file an issue specifically for that and I'll take a look - I think it just needs it's token type (`annotation`) registering in the extension. Thanks!

**Comment by HadyMash** [comment]
@DanTup Thank you for your help. I don't think its worth all of this trouble, guess I'll just get used to it, not that big of a deal, just thought it might have a quick and easy fix 🤷‍♂️. 

I cannot thank you enough for your help. Have a fantastic day!

**Comment by DanTup** [comment]
I think it's an easy change, just needs a small modification. It probably should be done (generally you should be able to theme all of the tokens) so feel free to open an issue and I'll ensure it works and give a sample for customising it.

> I cannot thank you enough for your help. Have a fantastic day!

Not a problem, you too!

**Comment by HadyMash** [comment]
@DanTup Alright, I did as you advised and opened a new issue for annotation token.

**Comment by robertpiosik** [comment]
@DanTup It looks like LSP breaks the default theme.

Without LSP:
![image](https://user-images.githubusercontent.com/7120725/120241700-a1616e80-c263-11eb-82f7-2ce0a2b9ee99.png)
With LSP:
![image](https://user-images.githubusercontent.com/7120725/120241780-c524b480-c263-11eb-816c-b65d8a2fbc78.png)

**Comment by DanTup** [comment]
@robertpiosik it's not clear to me exactly what the issue is - can you give an example of which bits you think are wrong?

(Note: it is _intended_ that the colours are different, and that there's much more blue and less white - see https://github.com/Dart-Code/Dart-Code/issues/3168)
