### ISSUE TITLE
Theme annotation token

### ISSUE THREAD

**Issue by HadyMash** [Dart-Code/Dart-Code#3161]
**Is your feature request related to a problem? Please describe.**
There was previously an issue with the Preview LSP option where the UI Guides wouldn't work. When that was fixed, I turned it back on and noticed the syntax highlighting was different. I opened #3155 and I was able to change the colour of the variables. However, the `@` and `override` have different colours and it doesn't match. Prior to turning on Preview LSP, using the One Dark Pro theme the `@override` would be pink. I do not care about what colour it is so long as they have the same colour.

**Describe the solution you'd like**
As advised by @DanTup in the previous issue, I would like to have a token for annotations so the `@` colour can be customised.

**Additional context**
Issue #3155

**Comment by DanTup** [comment]
I've changed annotations to by default be coloured the same as variables:

![Screenshot 2021-02-25 at 11 36 17](https://user-images.githubusercontent.com/1078012/109148138-bfe43500-775d-11eb-9e61-aea99f988617.png)

This won't match perfectly if you use a constructor directly (`@ClassFoo()`) as classes are coloured slightly differently, but I think in most cases annotations are fields/getters.

You can also override the colour of the `@` using the `annotation` token in your settings like:

```js
"editor.semanticTokenColorCustomizations": {
	"rules": {
		"annotation": "#00ff00",
	},
},
```

**Comment by HadyMash** [comment]
Thank you very much for your help @DanTup!
