### ISSUE TITLE
Quick-fix doesn't show for importing package:meta on @required

### ISSUE THREAD

**Issue by pablougaz** [Dart-Code/Dart-Code#3164]
Hi - when I upgraded to the latest version of Dart Code I experienced these two issues that were only fixed by disabling previewLsp:

1 - IntelliSense auto-complete stopped inserting a pre-filled method with stubbed, highlighted parameters, which was very convenient.  Instead it now just completes the method name and doesn't add parentheses.   The other issue w/ this new way of auto-complete is that it shows the Quick Docs automatically when I do enter the first '(' and this covers my code.  I find that I'm always hitting escape to get the docs to go away.  An example would be starting to type 'expect' on a test - the original way would complete the method signature with actual/matcher, now I get quick docs covering my test.

2 - Refactorings also changed behavior.  The most notable is that Extract Method doesn't automatically also allow you to name the extracted method while doing this refactoring.   It names the extracted method newMethod and then I have to do Rename Symbol to change it.  Not the end of the world, but it was nicer before the upgrade.   Another refactoring that I noticed worked better prior to the the upgrade was 'import package'  it would always know and import correctly - not it doesn't show (I'm not sure if this will get fixed by disabling LSP).

This leaves me worried that I'm not using LSP any longer and this is probably not recommended.  What is the recommendation going fwd?

Dart Code  v3.19.2
VS Code v 1.53.2

Thanks,
Pablo

**Comment by DanTup** [comment]
Sorry for the inconvenience! LSP is currently considered "preview" as there were a few features still missing (at least in the current stable Flutter version).

The first issue was resolved as part of https://github.com/Dart-Code/Dart-Code/issues/2823. It's a change in the server so will come via a Flutter/Dart SDK update. It's not in the current Stable version of Flutter, though is in the beta channel (and is expected to be in the next stable release).

The second issue is fixed as part of https://github.com/Dart-Code/Dart-Code/issues/3103 and will be included in the next release of the Dart extension (there's a beta of that [here](https://github.com/Dart-Code/Dart-Code/releases/tag/v3.20.0-beta.1)).

> Another refactoring that I noticed worked better prior to the the upgrade was 'import package' it would always know and import correctly - not it doesn't show (I'm not sure if this will get fixed by disabling LSP).

I'm not familiar with this issue, can you provide exact details and we can re-purpose this issue for fixing that if it's a bug? Thanks!

**Comment by pablougaz** [comment]
Thanks @DanTup, appreciate the update.  I just tried the import issue with and without the LSP preview flag and it seems to be unrelated.  

This is what I did (same behavior after changing LSP flag true/false with VS Code restart):  
1 - comment out 'dart:math' import then go to a line w/ 'Random()' and quick fixes correctly offers to import 'dart:math'
2 - comment out 'package:meta/meta.dart' import, then go to a line w/ an @required named parameter and quick fixes doesn't offer to import the meta package.

I think I just recently tried to add these @required annotation and assumed it was related to the same problem with the suggestions & refactoring.  There may be a valid reason why the meta import isn't being suggested, but that's what I was referring to.

Thanks again Dan.
Pablo

**Comment by DanTup** [comment]
> 2 - comment out 'package:meta/meta.dart' import, then go to a line w/ an @required named parameter and quick fixes doesn't offer to import the meta package.

Can you check you have `meta` listed in your `pubspec.yaml`? It's not correct to import packages that are not declared in `dependencies`, so they won't show up in code completion of get fixes (although if you manually type them, they will work because the package _is_ available via some other package).

The correct fix is to add it to your dependencies - you shouldn't take advantage of a package being included another dependency, as that package may not treat removing a dependency as a breaking change (but it would break you if you weren't depending on `meta` directly).

**Comment by pablougaz** [comment]
Yes, I have the `meta` package under `dependencies` in my `pusbspec.yaml`

**Comment by DanTup** [comment]
@pablougaz I've not been able ti repro, it seems to show up here:

<img width="414" alt="Screenshot 2021-03-03 at 14 22 00" src="https://user-images.githubusercontent.com/1078012/109819359-e1e12a00-7c2b-11eb-90d4-1aa82cca917b.png">

Are you able to repro in a small project that you could share (along with the exact location where you're invoking the fixes and it's not showing up)? Thanks!

**Comment by pablougaz** [comment]
@DanTup I was in the process of creating a small project to share when I figured out the problem... in my `pubspec.yaml` the `meta` entry wasn't indented 2 spaces (yaml!).   So, i was relying on `meta` from another dependency rather than on my on `pubspec`.  Thanks for all the help!

PS any recommendations on a VS Code yaml plugin are welcomed!

**Comment by DanTup** [comment]
> in my `pubspec.yaml` the `meta` entry wasn't indented 2 spaces (yaml!)

Aha! That explains it.

> PS any recommendations on a VS Code yaml plugin are welcomed!

I don't know of any, though it's possible that the YAML you had here was still valid (according to YAML) and wouldn't have reported any issues. I think there are a few open issues in the SDK repo about improving the YAML validation though.

In a future SDK release, there will also be support for some completion of package names here (https://github.com/Dart-Code/Dart-Code/issues/101).
