### ISSUE TITLE
Dart sdk

### ISSUE THREAD

**Issue by Teega** [Dart-Code/Dart-Code#3166]
Please team i have issue on my vscode first it was flutter i resolve that now is "could not find Dart in your flutter SDK run flutter doctor in terminal then reload the project once all issues are resolved"if i try running flutter doctor it shows checking Dart sdk then it closes 
![IMG-20210226-WA0002](https://user-images.githubusercontent.com/79721183/109347677-87b62280-7841-11eb-9fc0-117611988723.jpeg)

**Comment by kawolski** [comment]
Is dart installed in your pc ?
If not you have to install dart package first.

**Comment by DanTup** [comment]
> if i try running flutter doctor it shows checking Dart sdk then it closes

Can you post exactly what output you see when you do this? Can you also confirm how you're running `flutter doctor`? Are you running it in VS Code or an external terminal?

> Is dart installed in your pc ?
> If not you have to install dart package first.

This is not the case - if you're doing Flutter development you only need to install the Flutter SDK. Flutter downloads its own version of the Dart SDK (which is what hasn't happened here, but running `flutter doctor` should trigger).

You only need to install the standalone Dart SDK if you want to work on non-Flutter Dart projects :-)
