### ISSUE TITLE
Allow setting a default value for launch config's "console" field if not explicitly specified

### ISSUE THREAD

**Issue by RandalSchwartz** [Dart-Code/Dart-Code#3169]
**Describe the bug**
As instructed, I set "console" : "terminal" in my launch.json.  I expected that running my command-line app would then send output to the integrated terminal, and accept typing as stdin for the app.

No, the stdout still went to the debug console, and I am unable to provide input.

**To Reproduce**
1. Set launch.json as indicated.
2. Start dart debugging a CLI app that prints to stdout, and reads from stdin.

**Expected behavior**
 I expected that running my command-line app would then send output to the integrated terminal, and accept typing as stdin for the app.

**Screenshots**

**Versions (please complete the following information):**
 - VS Code version: 1.53.2 (mac)
 - Dart extension version: 3.19.2
 - Dart/Flutter SDK version: Dart SDK version: 2.12.0-259.16.beta (beta) (Tue Feb 23 00:10:18 2021 +0100) on "macos_x64"

**Comment by DanTup** [comment]
I've not been able to reproduce this, it seems to work from my testing:

![vziJjAl](https://user-images.githubusercontent.com/1078012/109481040-2fb33200-7a74-11eb-858f-efc06b74d1f7.png)

Could you try capturing a log ("Dart: Capture Debugging Logs") when launching the app?

**Comment by RandalSchwartz** [comment]
Aha.  I see it.  "debug":"console" must be not only *in* a newly created launch.json (aside: why can't I set this globally?), but also doesn't trigger if you select the "debug" option from "run | debug" just above main().

**Comment by DanTup** [comment]
> but also doesn't trigger if you select the "debug" option from "run | debug" just above main()

Ah yes, that's because those are their own launch configurations, they're not the same as using the commands (which run the selected confirmation from the debug side bar).

You can, however, add custom code lens links (see https://dartcode.org/docs/custom-codelens/), so you could have "Run in Terminal". / "Debug in Terminal" links there.

**Comment by DanTup** [comment]
> aside: why can't I set this globally?

Sounds like a fair request - I'll reuse this issue for having an option to set a default, for if it's not specified on the launch config. That would also make the default Run/Debug codelens links use it.
