### ISSUE TITLE
Code completion incorrectly returns results in comments at end of file

### ISSUE THREAD

**Issue by eseidel** [Dart-Code/Dart-Code#3170]
**To Reproduce**
1. Open a new `foo.dart` file.
2. Start typing a comment "// This is a test.<return>"
3. Notice how you end up with "// This is a test.abstract\n".

**Expected behavior**
I would have expected typing return after the period to result in just a new line, not "abstract\n" added.

The autocomplete is just a bit aggressive inside comments (especially with nothing typed after the period).

**Screenshots**
![autocomplete_bug](https://user-images.githubusercontent.com/478541/109394948-93a3f200-78de-11eb-82fb-8ad12c93d73d.png)

**Versions (please complete the following information):**
> flutter doctor -v
[√] Flutter (Channel dev, 1.27.0-8.0.pre, on Microsoft Windows [Version 10.0.19041.804],
    locale en-US)
    • Flutter version 1.27.0-8.0.pre at C:\Users\micro\flutter
    • Framework revision b7d4806243 (8 days ago), 2021-02-19 09:22:45 -0800
    • Engine revision 6993cb229b
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\micro\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

**Comment by DanTup** [comment]
Thanks! I can repro this - it seems to only happen when the comment is the last thing in the file. I suspect [this check](https://github.com/dart-lang/sdk/blob/fd81b73e67051a7ac06669a01ec32082ced0dc4f/pkg/analysis_server/lib/src/services/completion/dart/completion_manager.dart#L110-L113) isn't working right in that case.

It also seems to set the replacement range to the whole comment, so if you invoke completion without the `.` it ends up replacing the whole thing:

<img width="374" alt="Screenshot 2021-02-28 at 11 05 50" src="https://user-images.githubusercontent.com/1078012/109416275-1bf4c680-79b5-11eb-9227-1b6114b7df85.png">

<img width="246" alt="Screenshot 2021-02-28 at 11 05 55" src="https://user-images.githubusercontent.com/1078012/109416276-1c8d5d00-79b5-11eb-8dcc-33dc25339c10.png">

I'll take a look, thanks!

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/f03ec46effd3efee3f1bcba20715a7fe38972470. The fix is in the SDK, so will show up in a future SDK update (rather than a Dart-Code update). Thanks!
