### ISSUE TITLE
Command "editor.action.formatSelection" not working with Dart

### ISSUE THREAD

**Issue by nythrox** [Dart-Code/Dart-Code#3171]
**Describe the bug**
When you try to format a selection of code in VSCode it will silently fail with no exception shown. 
I believe this is a bug and should not be happening since "format selection" is [already supported](https://github.com/dart-lang/sdk/commit/44e680ac539509222c3ac64c96d3054d0b569d95) in the LSP (https://github.com/Dart-Code/Dart-Code/issues/812), and is available for emacs, vim, android studio (with dart), etc.

**To Reproduce**
1. Go to VSCode
2. Open Keyboard Shortcuts (JSON)
3. Add the formatSelection action (keybindings.json)
```json
{ 
        "key": "ctrl+shift+f",
        "command": "editor.action.formatSelection"
}
```
4. Try formatting a selection of code (editor.action.formatSelection will activate but nothing will happen)

**Expected behavior**
Selected code is formatted 

**Versions (please complete the following information):**
 - VS Code version: 1.53.2 622cb03f7e070a9670c94bae1a45d78d7181fbd4 x64
 - Dart extension version: 3.20.0
 - Dart/Flutter SDK version: Flutter 1.22.6 • channel stable  | Dart SDK version: 2.10.5 (stable) windows_x64

**Comment by DanTup** [comment]
@nythrox do you have the LSP Preview enabled? Format selection is _only_ available with LSP enabled. The original protocol doesn't have support for requesting only a selection is formatted, so it's LSP-exclusive.

LSP is going to be the default soon, and non-LSP will not be maintained (and ultimately removed).

If you _are_ using LSP, please can you run **Dart: Capture Analysis Server Logs**, then the format, then click **Cancel** to stop logging and open the log file.

Thanks!

**Comment by nythrox** [comment]
Hey @DanTup
I've got LSP enabled in settings.json (`"dart.previewLsp": true`)

It seems like it didn't run any command although the shortcut is being activated (if you change the command to a different value, it will run or show an error) 
```

!! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.20.0
Flutter extension: 3.20.0 (activated)

App: Visual Studio Code
Version: 1.53.2
Platform: win

Workspace type: Flutter
Analyzer type: LSP
Multi-root?: true

Dart SDK:
    Loc: C:\src\flutter\bin\cache\dart-sdk
    Ver: 2.10.5
Flutter SDK:
    Loc: C:\src\flutter
    Ver: 1.22.6

HTTP_PROXY: undefined
NO_PROXY: undefined

Logging Categories:
    General, Analyzer, CommandProcesses

Mon Mar 01 2021 [20:29:54 GMT-0300 (Brasilia Standard Time)] Log file started
Mon Mar 01 2021 [20:30:00 GMT-0300 (Brasilia Standard Time)] Log file ended

```

**Comment by DanTup** [comment]
@nythrox sorry, I missed your Flutter SDK version. Format Selection was added in the LSP server which ships with the SDK. The change was made in November but there hasn't been a (major) stable version of Flutter since, so this isn't included.

It works on the beta/dev/master channels (and also shows up in the command palette for those versions). I'll be included in the next major Flutter release to stable too.

Hope this helps!
