### ISSUE TITLE
error thrown when typing into, clicking on, or performing any action on dart files in VS Code

### ISSUE THREAD

**Issue by Code-Sage** [Dart-Code/Dart-Code#3172]
I've been having this issue since yesterday. I suspected that it was due to yesterday's Dart extension update but even downgrading to 3.19 didn't help. I've tried disabling and re-enabling extensions, uninstalling and re-installing extensions, uninstalling and re-installing VS Code combined with deleting VS Code's cache of previously installed extensions before re-installation of VS Code. But I keep getting the same errors. Currently I have `Dart and Flutter extensions with version 3.20` and `VS Code 1.53.2`

I've shown error logs generated only for `national_id_ocr.dart` but it gives the same error output for all dart files, the only change being the file path.
```
[Error - 1:20:01 PM] Request textDocument/documentHighlight failed.
  Message: Invalid file path
  Code: -32003 
c:\...\lib\widgets\national_id_ocr.dart
[Error - 1:20:01 PM] Request textDocument/codeAction failed.
  Message: Invalid file path
  Code: -32003 
c:\...\lib\widgets\national_id_ocr.dart

```

**Comment by DanTup** [comment]
Is the path in the error `c:\...\lib\widgets\national_id_ocr.dart` exactly what was generated, or did you just truncate the path for pasting here?

Do you see this only when you first open the project, or all the time while trying to interact with the files?

Can you also confirm your Flutter SDK version? Thanks!

**Comment by Code-Sage** [comment]
> Is the path in the error `c:\...\lib\widgets\national_id_ocr.dart` exactly what was generated, or did you just truncate the path for pasting here?
> 
> Do you see this only when you first open the project, or all the time while trying to interact with the files?
> 
> Can you also confirm your Flutter SDK version? Thanks!

I replaced part of the path with `...` for purposes of secrecy since I'm working for a company. But the `...` are just a path like `Users\user1\Documents\ProjectName` directory. I'm using Flutter SDK 1.20.4.

I see the error message all the time whenever I interact with a dart file in any way.

**Comment by DanTup** [comment]
Can you reproduce this on a small sample project (for example using the ***Dart: New Project** command), or does it only occur in this project? If you can reproduce in a small sample you could enable the [analysis server log](https://dartcode.org/docs/logging/#analyzer) and that may help understand what's happening.

Can you also confirm that you have opened the project folder in VS Code, and are not just opening the files directly (the analyzer will only analyze the folders that are open in the workspace - if you just open a "loose" Dart file, it will not provide full functionality). Thanks!

**Comment by Code-Sage** [comment]
> Can you reproduce this on a small sample project (for example using the ***Dart: New Project** command), or does it only occur in this project? If you can reproduce in a small sample you could enable the [analysis server log](https://dartcode.org/docs/logging/#analyzer) and that may help understand what's happening.
> 
> Can you also confirm that you have opened the project folder in VS Code, and are not just opening the files directly (the analyzer will only analyze the folders that are open in the workspace - if you just open a "loose" Dart file, it will not provide full functionality). Thanks!

I just created a new flutter app [here](https://github.com/Code-Sage/flutter_application_1), and a Dart project using ***Dart: New Project** command; and both are working fine. I ran the Flutter project I shared on a device and confirmed it. So, that means issue is somehow with that particular project of my company?

And yes, I did open the dart files in VS Code that are in the directory of the workspace.

**Comment by Code-Sage** [comment]
This is the complete output I get when the project first loads up. Afterwards, only the error output mentioned above is given.

```
[Error - 4:37:14 PM] An error occurred while handling initialized notification: FormatException: No ':' on line (at offset 13957)
#0      parse (package:package_config/packages_file.dart:64:7)
#1      parseDotPackagesFile (package:analyzer/src/context/packages.dart:48:16)
#2      parsePackagesFile (package:analyzer/src/context/packages.dart:130:12)
#3      ContextManagerImpl._computeFolderDisposition (package:analysis_server/src/context_manager.dart:874:22)
#4      ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:914:9)
#5      ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1004:16)
#6      ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:610:9)
#7      LspAnalysisServer.setAnalysisRoots (package:analysis_server/src/lsp/lsp_analysis_server.dart:496:20)
#8      IntializedMessageHandler.handle (package:analysis_server/src/lsp/handlers/handler_initialized.dart:34:14)
#9      _rootRunUnary (dart:async/zone.dart:1198:47)
#10     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#15     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#16     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#17     LspAnalysisServer.fetchClientConfigurationAndPerformDynamicRegistration (package:analysis_server/src/lsp/lsp_analysis_server.dart)
#18     _rootRunUnary (dart:async/zone.dart:1198:47)
#19     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#23     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#24     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#25     _rootRun (dart:async/zone.dart:1190:13)
#26     _CustomZone.run (dart:async/zone.dart:1093:19)
#27     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#29     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#31     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

[Error - 4:37:14 PM] Request textDocument/documentSymbol failed.
  Message: Invalid file path
  Code: -32003 
c:\Users\user1\ProjectName\lib\widgets\national_id_ocr.dart
[Error - 4:37:14 PM] Request textDocument/codeAction failed.
  Message: Invalid file path
  Code: -32003 
c:\Users\user1\ProjectName\lib\widgets\national_id_ocr.dart
[Error - 4:37:19 PM] Request textDocument/codeAction failed.
  Message: Invalid file path
  Code: -32003 
c:\Users\user1\ProjectName\lib\widgets\national_id_ocr.dart

```

**Comment by DanTup** [comment]
@Code-Sage aha - that final error explains it. The language server is failing to initialize, which means nothing is being analyzed.

Given that this is occurring in `parseDotPackagesFile`, it sounds like your `.packages` file might not be valid. Can you check the contents of that file (specifically at offset 13957)? You could possibly delete it and re-create it by running `get packages`, although it's worth trying to understand what's invalid and how it got into that state in case there's another bug somewhere.

**Comment by Code-Sage** [comment]
@DanTup I've attached the `.packages` file but I doubt its helpful since its not human readable.
[.packages.zip](https://github.com/Dart-Code/Dart-Code/files/6068370/default.packages.zip)
 
When you open it in Notepad++, this is what you see:

![packages_dart file](https://user-images.githubusercontent.com/7098640/109644456-50b07b80-7b77-11eb-8828-3305e619c9a0.PNG)

**Comment by DanTup** [comment]
@Code-Sage I think that's your problem - that file should very much not look like that. I can't even extract the file from the zip as macOS seems to think it's not there.

I'm not sure how the file ended up in that state, but I suspect if you delete it and re-run the Get Packages command in VS Code, then reload VS Code, it may resolve your issue.

For reference, the file should look something like this:

```
# This file is deprecated. Tools should instead consume 
# `.dart_tools/package_config.json`.
# 
# For more info see: https://dart.dev/go/dot-packages-deprecation
# 
# Generated by pub on 2021-03-01 11:14:43.441883.
_fe_analyzer_shared:file:///Users/danny/.pub-cache/hosted/pub.dartlang.org/_fe_analyzer_shared-14.0.0/lib/
analyzer:file:///Users/danny/.pub-cache/hosted/pub.dartlang.org/analyzer-0.41.2/lib/
args:file:///Users/danny/.pub-cache/hosted/pub.dartlang.org/args-2.0.0/lib/
async:file:///Users/danny/.pub-cache/hosted/pub.dartlang.org/async-2.5.0/lib/
boolean_selector:file:///Users/danny/.pub-cache/hosted/pub.dartlang.org/boolean_selector-2.1.0/lib/
charcode:file:///Users/danny/.pub-cache/hosted/pub.dartlang.org/charcode-1.2.0/lib/
cli_util:file:///Users/danny/.pub-cache/hosted/pub.dartlang.org/cli_util-0.3.0/lib/
collection:file:///Users/danny/.pub-cache/hosted/pub.dartlang.org/collection-1.15.0/lib/
convert:file:///Users/danny/.pub-cache/hosted/pub.dartlang.org/convert-3.0.0/lib/
coverage:file:///Users/danny/.pub-cache/hosted/pub.dartlang.org/coverage-0.15.2/lib/
crypto:file:///Users/danny/.pub-cache/hosted/pub.dartlang.org/crypto-3.0.0/lib/
file:file:///Users/danny/.pub-cache/hosted/pub.dartlang.org/file-6.0.0/lib/
glob:file:///Users/danny/.pub-cache/hosted/pub.dartlang.org/glob-2.0.0/lib/
```

**Comment by DanTup** [comment]
Also - FWIW, this file is replaced by `.dart_tool/package_config.json` in the latest versions, but it looks like your Flutter version is quite old (1.20.4 but the current stable is 1.22.6).

**Comment by Code-Sage** [comment]
@DanTup I deleted the `.packages` file and ran `flutter pub get` ; then it gave some error in the `pubspec.lock` file. So I deleted both `.packages` and `pubspec.lock` files and ran `flutter pub get` again, reloaded VS Code, and its working now!

**Comment by DanTup** [comment]
@Code-Sage great, glad to hear! I'm not sure how the file got into that state though - if you see that again it's worth some investigation. I'm glad you managed to resolve it though!
