### ISSUE TITLE
Switch to using "dart create" instead of stagehand for newer SDK versions

### ISSUE THREAD

**Issue by RandalSchwartz** [Dart-Code/Dart-Code#3179]
**Describe the bug**
Stagehand is deprecated.  The new thing is `dart pub create`

**To Reproduce**
1. uninstall the broken stagehand (broken now because `pub` no longer exists):
    dart pub global deactivate stagehand # buh bye broken tool
2. command-window Dart: create project
3. Fails, wanting the now-broken stagehand to be reinstalled.  No way, jose.

**Expected behavior**
`dart pub create` gets run with the proper args

**Screenshots**

**Versions (please complete the following information):**
 - VS Code version: 1.54.1
 - Dart extension version:  3.20.1
 - Dart/Flutter SDK version: 2.0+dev

**Comment by DanTup** [comment]
> uninstall the broken stagehand (broken now because pub no longer exists):

Can you clarify what you're seeing here? I deactivated stagehand and ran **Dart: New Project** but it re-activated and worked as expected. I don't think it's intended that it should have stopped working yet. Are you seeing errors?

**Comment by RandalSchwartz** [comment]
Yes there is a package named stagehand that is now legacy and won't be maintained by the home team, and installs broken because it depends on "pub" existing, which is going away.  "dart pub create" has replaced it, and already diverges on the kinds of templates to use.

**Comment by DanTup** [comment]
> and installs broken because it depends on "pub" existing, which is going away

I'm a little confused - are you saying that this _will_ break, or it _is_ broken?

My understanding is that the `pub` command is not going to disappear anytime soon (that would be quite breaking). The goal is to move to `dart xxx` commands, but that's not something that needs to happen urgently. However if something is _broken today_ then that very much needs fixing right away.

Thanks!

**Comment by RandalSchwartz** [comment]
If today, you install the Flutter distro, and add its one bin to your PATH ($SDK_PATH/bin), you will get the flutter and dart commands, and the fully functional dart SDK, but no pub command.  This is by design.  stagehand is going away, and even "dart global activate" is broken because it writes a bin that includes "pub" instead of "dart pub".  (I haven't tested flutter global activate, because it's broken by installing in a separate directory that's not ~/.pub-cache, but that's a separate issue.)

So, even today, if you start from scratch, and then use pub global, that will fail, and if you use dart pub global, that seems to fail as well.  You should try "dart create" first.

**Comment by DanTup** [comment]
I'm still a little confused about whether there's a bug here, or this is a request to change something for the future.

Dart-Code should never calls `pub` from Flutter's `bin` folder, nor directly from `PATH`. It should always use the _Dart_ SDK's bin folder.

If you can reproduce an error or something broken, please provide exact steps as that's much more urgent to fix than moving over to new commands/templates. Thanks!

**Comment by DanTup** [comment]
I've renamed this as a general issue to support `dart create` for newer SDKs since I don't think there's anything wrong with the existing code, it should just be migrated for the future (see https://github.com/dart-lang/stagehand/issues/671).
