### ISSUE TITLE
vscode takes up too much memory resources

### ISSUE THREAD

**Issue by fangkyi03** [Dart-Code/Dart-Code#3180]
**Describe the bug**
Every time vscode opens the flutter project, it will open three dart processes. Then it opens another flutter project and reopens three dart processes. My m18g memory computer is full of memory after opening several flutter projects without doing anything

**To Reproduce**
Click vscode to open the flutter project

**Expected behavior**
No matter how many flutter projects are opened, only three processes will always be reserved, otherwise it will take up too much resources

**Screenshots**
![image](https://user-images.githubusercontent.com/30390014/110133306-21b03900-7e07-11eb-938d-44b10781dd44.png)

**Versions (please complete the following information):**
 - VS Code version:
 版本: 1.54.0-insider
提交: 42e27fe5cdc58539dad9867970326a297eb8cacf
日期: 2021-03-02T19:14:33.180Z (2 天前)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin arm64 20.4.0
 - Dart extension version:3.20.1
 - Dart/Flutter SDK version:Flutter (Channel master, 2.1.0-11.0.pre.121, on macOS 11.3 20E5196f darwin-arm, locale
    zh-Hans-CN)

**Comment by DanTup** [comment]
> My m18g memory computer is full of memory after opening several flutter projects without doing anything

Do you mean opening multiple Flutter projects within one VS Code window, or opening multiple VS Code windows?

If you're opening multiple VS Code windows, they cannot share the Dart processes, so that will result in more. If you use VS Code's multi-root workspaces (eg. select multiple folders in the Open dialog, or use File -> Add Folder to Workspace to add additional folders) then it should not spawn additional processes.

If you're seeing this many processes when using multi-root workspaces, could you get the full command line for them (eg. using `ps -x | grep dart`)? Thanks!

**Comment by fangkyi03** [comment]
I only develop one Flutter project, but I may have to refer to several projects. For example, the QuickJS project I am working on recently does not have a particularly stable version, so I may need to check several projects to see why some will report errors and others will be normal, which will lead to a lot of resource consumption. Right

**Comment by DanTup** [comment]
@fangkyi03 can you confirm whether you're opening multiple VS Code windows or not, and if so whether the other windows include any Dart projects (no Dart processes should be spawned for a VS Code window that doesn't contain any Dart projects).

Can you also post the output of `ps -x | grep dart` to show the command lines for all of the processes? Thanks!

**Comment by fangkyi03** [comment]
![image](https://user-images.githubusercontent.com/30390014/110402865-184cf800-80b7-11eb-8061-6e5dce6293aa.png)

**Comment by fangkyi03** [comment]
I've looked at some of your code and I remember you guys doing something like VS code completion and that would start a DART process and find the completion data in that way and I was wondering if you could have all of your DART projects in one process and you could click on debug or something like that and start one and that would reduce some memory usage

**Comment by DanTup** [comment]
> I've looked at some of your code and I remember you guys doing something like VS code completion and that would start a DART process and find the completion data in that way

The completion data comes from the Dart analysis server, which is spawned as a separate process. It manages all language features (including go-to-definition, code completion, quick-fixes, hovers, etc.).

> I was wondering if you could have all of your DART projects in one process and you could click on debug or something like that and start one and that would reduce some memory usage

I'm not sure exactly what the suggestion is, but the language server needs to be available all the time - it can't be delayed until a debug session (or require the user to click a button). If you're opening workspaces that do not have Dart/Flutter projects, then we should _not_ be spawning those processes. However if you're opening a Dart/Flutter project, they are required.

The language server protocol does not have support for having multiple clients (eg. multiple VS Code windows) talking to a single instance. Each VS Code window requires its own instance.

Unfortunately there are only real options:

1. Use a single VS Code window to open the multiple projects
2. Use multiple Windows and it will use additional resources

I would recommend the first, as the second results in a lot of duplicated work (for example loading the Flutter SDK into memory inside multiple Dart language servers).

Hope this makes sense!

**Comment by fangkyi03** [comment]
You have said is very reasonable But such words Completely unable to take advantage of many of the screen multiple projects together Very prone to error will can not find the corresponding projects This is my personal opinion If not achieve them I can only shut down the problem In fact, I prefer a smooth as silk low occupancy at the same time Even for part of adopt the local database Such as flutter integrated part of the official This can also reduce a large part of the memory overhead Because the dart need to traverse the things too much If in the dart - the core code next break If you type a letter and you get N answers that are returned by the dart command line every time you type it you can imagine the memory consumption and I wish there was a better way to do that

**Comment by DanTup** [comment]
> Completely unable to take advantage of many of the screen multiple projects together

I understand. Unfortunately there is not a better solution. VS Code will hopefully get support for multiple screens on day, which will make working on multiple screens with a single workspace possible.

In the meantime, the choice is between a single window, or having multiple language servers. This is unfortunately a limitation of VS Code and the LSP protocol and not something that is easily worked around. I previously asked about LSP supporting multiple clients at https://github.com/microsoft/language-server-protocol/issues/1160, but it is not something currently planned.

> Because the dart need to traverse the things too much If in the dart - the core code next break If you type a letter and you get N answers that are returned by the dart command line every time you type it you can imagine the memory consumption

I'm afraid I don't entirely understand what you mean here. If you're asking if code completion code runs on every keypress, that's not quite correct. When you just invoke code completion VS Code will as the language server for the results. As you type more characters, VS Code will filter the list itself, without needing to go back to the language server.

The completion suggestions are computed and sent directly to VS Code and not kept in the Dart analysis servers memory. However it does cache the contents of files, and that does consume memory (which will be duplicated for things like the Flutter SDK if you have multiple windows open).

**Comment by fangkyi03** [comment]
Hopefully one day I'll be able to see the silky smooth effect that I'm looking for
