### ISSUE TITLE
analyzer 100% CPU repro

### ISSUE THREAD

**Issue by dcharkes** [Dart-Code/Dart-Code#3181]
With the following steps I can relatively reliably reproduce the analyzer hanging:

```
$ flutter create --platforms=android,ios,macos,windows,linux --template=plugin foo
$ cd foo/example/
$ flutter run -d macos
# hit q to quit
$ flutter run -d iphone
```

And keep doing `> Developer: Reload Window` on this project while this happens, change a Dart file, wait a couple of seconds, and hit save.

Observed behavior: dart formatting stops working and dart analyzer stops working. 

Edit: the iphone build creates a cyclic symlink `example/ios/.symlinks/plugins/foo`, we need the macos build as well in order to let the analyzer go to 100%. Deleting the symlink (and reloading the window) makes the project unstuck. Rebuilding for macos and iphone does not make the symlink reappear after deleting, but after a flutter clean the symlink reappears after building for iphone.

```
$ ps 69679 -w -w
  PID   TT  STAT      TIME COMMAND
69679   ??  R      2:23.93 /Users/dacoharkes/flt/engine/flutter/bin/cache/dart-sdk/bin/dart /Users/dacoharkes/flt/engine/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --client-id=VS-Code --client-version=3.20.1
```

```
$ flutter --version
Flutter 2.0.0 • channel stable • https://github.com/flutter/flutter
Framework • revision 60bd88df91 (2 days ago) • 2021-03-03 09:13:17 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0
```

```
Version: 1.54.1
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:42:18.719Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0
```

VSCode plugins:
* Flutter: v3.20.0
* Dart: v3.20.1

https://github.com/Dart-Code/Dart-Code/issues/3037 https://github.com/Dart-Code/Dart-Code/issues/1114

@DanTup please let me know if this helps you repro this recurring issue.

**Comment by DanTup** [comment]
@dcharkes I think this might be the same as https://github.com/Dart-Code/Dart-Code/issues/3165, trigged by symlinks that point back further up the tree. That issue appears to have been fixed (although not in stable).

Can you repro on dev/master?

**Comment by dcharkes** [comment]
Ah yes, I just found the symlinks as well.

**Comment by DanTup** [comment]
As a temporary workaround, you _might_ be able to use `dart.analysisExcludeFolders` to exclude the symlink folder, although I'm not certain.
