### ISSUE TITLE
Issue importing 'package:ffi/ffi.dart'. in visual studio

### ISSUE THREAD

**Issue by ir2pid** [Dart-Code/Dart-Code#3184]
**Using flutter latest**
Flutter 2.1.0-11.0.pre.145 • channel master • https://github.com/flutter/flutter.git
Framework • revision a0ba646408 (23 hours ago) • 2021-03-05 22:09:03 -0500
Engine • revision f751d04fa0
Tools • Dart 2.13.0 (build 2.13.0-107.0.dev)

I get an error when adding in ffi dart package. 
`Target of URI doesn't exist: 'package:ffi/ffi.dart'.`

Utf8 class is also not working.
Error: Method not found: 'Utf8.fromUtf8'.     return Utf8.fromUtf8(user);  

**Versions (please complete the following information):**
 - VS Code version: Version: 1.44.2
 - Dart extension version: 2.13.0 (build 2.13.0-107.0.dev)
 - Dart/Flutter SDK version: 2.1.0-11.0.pre.145 • channel all[master/dev/stable]

**Comment by DanTup** [comment]
I believe you should be using `dart:ffi`, as this [ships in the SDK](https://api.dart.dev/stable/2.12.0/dart-ffi/dart-ffi-library.html).

Please let me know if that still doesn't work!

**Comment by timsneath** [comment]
Actually, both `dart:ffi` and `package:ffi/ffi.dart` exist. And this method is indeed in the package. Do you have it in your pubspec `dependencies`, @ir2pid? Have you run `flutter pub get` to make sure the dependency is loaded?

**Comment by DanTup** [comment]
> Actually, both `dart:ffi` and `package:ffi/ffi.dart` exist.

Oh, I see. I thought the package might've been a temporary thing until it shipped in the SDK. What's the difference and when is it correct to use each? (all the examples I saw were using `dart:ffi`)

**Comment by timsneath** [comment]
package:ffi is mostly helper functions these days (e.g. string
conversions), as well as memory allocation functions. In most practical
scenarios, you should import both, but it would be possible to write an
alternative to package:ffi (e.g. to use a custom memory allocator).
