### ISSUE TITLE
Allow starting the emulator with cold boot

### ISSUE THREAD

**Issue by JCKodel** [Dart-Code/Dart-Code#3192]
**Is your feature request related to a problem? Please describe.**
Lately, Android Emulator on Windows is very troublesome. Sometimes it starts, but is frozen. The only way to fix it is to request a cold boot from Android Studio:

![image](https://user-images.githubusercontent.com/379339/110533388-b3b48c00-80fc-11eb-9339-57db3787630a.png)

**Describe the solution you'd like**
An option to do the same on VSCode:

![image](https://user-images.githubusercontent.com/379339/110533482-cd55d380-80fc-11eb-99e8-00fa50089999.png)

i.e.: add the `Flutter: Launch Emulator with cold boot` (just call emulator.exe with `-no-snapshot-load`)

It would be cool if we could configure our emulator settings. Sometimes, we need to start the emulator with some special setting (for instance, `-http-proxy` to start a special session with network sniffing through fiddler).

I guess a new option such `Flutter: Launch Emulator with args` and then asking for the args (perhaps with some autocompletion from emulator -help) would be awesome)

**Comment by DanTup** [comment]
This is a little tricky as VS Code doesn't really know much about emulators, and does not distinguish between Android or iOS emulators (beyond a simple tag that comes back from Flutter).

Do you generally _always_ want to load with this flag? If so, I wonder if using the "custom emulator" functionality (see the second example [here](https://dartcode.org/releases/v3-10/#custom-emulators)) to replace your Android emulator with one with this flag would suffice?

**Comment by JCKodel** [comment]
> This is a little tricky as VS Code doesn't really know much about emulators, and does not distinguish between Android or iOS emulators (beyond a simple tag that comes back from Flutter).
> 
> Do you generally _always_ want to load with this flag? If so, I wonder if using the "custom emulator" functionality (see the second example [here](https://dartcode.org/releases/v3-10/#custom-emulators)) to replace your Android emulator with one with this flag would suffice?

I guess the example provided solves the issue well.

**Comment by DanTup** [comment]
Flutter now has a new flag to cold-boot emulators, so in an upcoming version it might not be necessary to use the custom emulator commands - see #3366.
