### ISSUE TITLE
tasks.json command does not use dart.flutterSdkPath setting

### ISSUE THREAD

**Issue by ultronnet** [Dart-Code/Dart-Code#3199]
It use the system default flutter command when I use tasks.json below

```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "flutter",
			"command": "flutter",
			"args": [
				"build",
				"apk"
			],
			"group": "build",
			"problemMatcher": [],
			"label": "flutter: flutter build apk"
		}
	]
}
```

replace `"command": "flutter",` to `"command": "${config:dart.flutterSdkPath}/bin/flutter",`, it works.

but it reported error "dart.flutterSdkPath not found", when I use `Auto-detect SDK location`

**Comment by DanTup** [comment]
I've not been able to repro this - I set cloned a copy of Flutter to /tmp/flutter and added to settings, then created the task and invoked it (using **Tasks: Run Task**) but it used the configured version:

<img width="1171" alt="Screenshot 2021-03-15 at 13 18 12" src="https://user-images.githubusercontent.com/1078012/111159536-1be9ee80-8591-11eb-8b29-6c7761616980.png">

Are you able to reproduce this in a small sample (set the `flutterSdkPath` in the folder settings so it can be shared) and exact instructions on how you're running the task and verifying the version it's using? Thanks!

**Comment by ultronnet** [comment]
I can't reproduce it now.
