### ISSUE TITLE
Flutter Fix is not working as expected

### ISSUE THREAD

**Issue by raghavan-mookiah** [Dart-Code/Dart-Code#3200]
Issue Type: <b>Bug</b>

Flutter Fix is not working as expected as per below URL 
https://flutter.dev/docs/development/tools/flutter-fix

Extension version: 3.20.1
VS Code version: Code 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:09.783Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|16.00GB (3.38GB free)|
|Process Argv|-psn_0_2716311 --crash-reporter-id 66a79874-c661-4a1a-be11-341da5b11491|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontb:30265425
vspre833:30267464

```

</details>

**Comment by DanTup** [comment]
Can you please provide an exact code sample and description of exactly what you're expected to see and what you do see?

An issue did come up recently where trailing commas could affect some fixes showing up. That's being tracked at https://github.com/dart-lang/sdk/issues/45242. Thanks!
