### ISSUE TITLE
Differentiate dev_dependencies and dependencies

### ISSUE THREAD

**Issue by timsneath** [Dart-Code/Dart-Code#3202]
Related to #3095 a little. 

As a package author, it's important to me that I don't drag in too many dependencies for my consumers. The more packages I need, the more risk of version conflict. On the other hand, during development time, there's no cost to me adding packages. 

It would be great if the Dependencies toolwindow was able to disambiguate these two classes of package dependency. For example, it could be a filter to say "only show runtime dependencies", or perhaps a different icon (although this would be tristate, since some packages may be transitively depended on in both development and runtime scenarios). 

See image below as an example:
![image](https://user-images.githubusercontent.com/2319867/110975062-1e8be000-8314-11eb-89d6-3252914d6e59.png)

**Comment by DanTup** [comment]
Makes sense. Perhaps listing deps at the top level and then the final item is a "dev_dependencies" folder that contains the others?

There's [a PR in progress](https://github.com/dart-lang/pub/pull/2896) to add JSON output as discussed in #3095 which looks to include a `kind` against each dep (of `direct` or `dev`), so it should be easy to handle these both from the same data source.

**Comment by sigurdm** [comment]
Also consider transitive dependencies as a third category.

**Comment by DanTup** [comment]
When using a Dart SDK >= v2.14.0 the dependencies will now be split into folders for direct/dev/transitive dependencies:

<img width="404" alt="Screenshot 2021-05-25 at 11 47 31" src="https://user-images.githubusercontent.com/1078012/119485466-03dfd980-bd4f-11eb-8358-69762c7397ce.png">
