### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by oguchiw** [Dart-Code/Dart-Code#3204]
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `3.20.1`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.54.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\HP\AppData\Local\Temp\Dart-Code.dart-code-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by DanTup** [comment]
> ⚠️ Make sure to attach this file from your home-directory:
> ⚠️c:\Users\HP\AppData\Local\Temp\Dart-Code.dart-code-unresponsive.cpuprofile.txt

Are you able to provide the referenced file? Thanks!
