### ISSUE TITLE
dart pub upgrade --major-versions

### ISSUE THREAD

**Issue by jonasfj** [Dart-Code/Dart-Code#3216]
The  offers a command to run `dart pub upgrade`.

It would be cool to have a `Control + Shift + P` command to do:
 * `dart pub upgrade --major-versions`

Running `dart pub upgrade --major-versions` does mutate the `pubspec.yaml`.

In an ideal world we could perhaps snapshot the `pubspec.yaml` before / after running `dart pub upgrade --major-versions` and present the user with a diff. Or something like that?

Or maybe we open the `pubspec.yaml` and do some tricks to ensure that the on-disk-mutation of `pubspec.yaml` can be reverted using the undo-stack.

Or maybe we simply ask for confirmation before running `dart pub upgrade --major-versions` if the current `pubspec.yaml` haven't been committed to git?

--------

I imagine that this would appear in the `Control + Shift + P` command palette along side `dart pub upgrade`:

![dart-code-pub-upgrade](https://user-images.githubusercontent.com/149732/111358891-24265480-868b-11eb-8205-e26fdf579c08.png)

--------

Just a feature request, to help users discover this feature.

**Comment by DanTup** [comment]
> Or maybe we simply ask for confirmation before running `dart pub upgrade --major-versions` if the current `pubspec.yaml` haven't been committed to git?

I think issuing `git` commands might be a bit unexpected, so perhaps just a prompt the first time you run it that says it will mutate pubspec and you may wish to ensure it's committed before running (and then assuming the user knows for future runs)?

Is the Dart SDK version this is available in known? I'd like to make sure we don't show the command if it won't be available.

**Comment by DanTup** [comment]
I've enabled this for v2.12.0 onwards. The first time you run it you'll get a prompt. If you click "I Understand" it will continue (and not prompt in future), and if you dismiss the notification with the "X" it'll cancel (and prompt you again next time).

![Screenshot 2021-03-25 at 11 38 31](https://user-images.githubusercontent.com/1078012/112467273-c2d34500-8d5e-11eb-9a5c-503170a23d08.png)

The pubspec change is detected by Dart-Code and triggers an automatic `pub get` (I presume this is expected).

**Comment by DanTup** [comment]
It shows up in the same places as "Upgrade Packages", and also is triggered if you alt Alt while clicking the "Upgrade Packages" icon in the toolbar.

![Screenshot 2021-03-25 at 11 41 01](https://user-images.githubusercontent.com/1078012/112467695-47be5e80-8d5f-11eb-9ff8-9eb8d0aa6f7e.png)
![Screenshot 2021-03-25 at 11 42 48](https://user-images.githubusercontent.com/1078012/112467700-48ef8b80-8d5f-11eb-83b2-d797118f916e.png)
![Screenshot 2021-03-25 at 11 42 56](https://user-images.githubusercontent.com/1078012/112467705-4a20b880-8d5f-11eb-9811-08bef44f4f6d.png)
