### ISSUE TITLE
IntelliSense dies when you try to set a field or setter with super from mixin that implements a class

### ISSUE THREAD

**Issue by Dampfwalze** [Dart-Code/Dart-Code#3222]
**Reproduce**
Following code reproduces the Error, simply copy paste it anywhere to kill IntelliSense
```
class MyClass {
  set test(int i) => 0;
}

mixin MyMixin implements MyClass {
  void method() => super.test = ;
}
```
important are 
` super.test = `
`implements`
and a setter or field in `MyClass`

(in this case `implements` is from a functional Point of View not the right keyword anyway, use `on` instead and everything will be fine)

**Error Message**
[Error - 16:51:45] Request textDocument/hover failed.
  Message: Invalid file path
  Code: -32003 

and of course it does not work anymore

**Versions**
 - VSCode 1.54.3
 - Flutter 2.0.1
 - Dart 2.12.0

**Comment by DanTup** [comment]
Thanks for the report! It looks like an error is occurring in the analyzer while parsing this file. I've opened https://github.com/dart-lang/sdk/issues/45411 for it to be fixed there. Thanks!
