### ISSUE TITLE
test file is treated like app

### ISSUE THREAD

**Issue by nt4f04uNd** [Dart-Code/Dart-Code#3223]
i don't have "run | debug" per singular tests and extension tries to run test as application on device

this leads to some unxepected stuff like https://github.com/flutter/flutter/issues/78749, because test is running in non-test environment

**to reproduce**
1. flutter create app
2. rename `widget_test.dart` into `test.dart` or something completely unrelated without `_test` at the end

**expected behavior**
file should be treated like a test

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.192, on Microsoft Windows [Version 10.0.19041.867], locale ru-RU)
    • Flutter version 2.1.0-13.0.pre.192 at c:\dev\src\flutter
    • Framework revision c0bcb4fc16 (2 days ago), 2021-03-19 16:34:57 -0700
    • Engine revision e6db3a275e
    • Dart version 2.13.0 (build 2.13.0-149.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\danya\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0
    ✗ Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.54.3)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.867]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 89.0.774.54

! Doctor found issues in 1 category.
```
</details>

**screenshots**
expected:
![expected](https://user-images.githubusercontent.com/39104740/111926609-98635c80-8abe-11eb-8af0-3e272b425591.png)

actual:
![actual](https://user-images.githubusercontent.com/39104740/111926142-b760ef00-8abc-11eb-8afb-73378446bee4.png)

**Comment by DanTup** [comment]
> rename `widget_test.dart` into test.dart or something completely unrelated without `_test` at the end

Can I ask your reasons for this? Right now, only files that end with `_test.dart` are treated as test files. This is consistent with `dart test` and `flutter test`:

> The test runner considers any file that ends with _test.dart to be a test file. If you don't pass any paths, it will run all the test files in your test/ directory, making it easy to test your entire application at once.

If your file does not end with `_test.dart` it will be treated as a simple Dart script, and run with the Dart VM. Some people have helper scripts inside their `test` folder that should be run with `dart` and not `dart test`.

**Comment by nt4f04uNd** [comment]
ok this makes sense
