### ISSUE TITLE
Code block folding for enum

### ISSUE THREAD

**Issue by Luckey-Elijah** [Dart-Code/Dart-Code#3225]
**Is your feature request related to a problem? Please describe.**
With most code blocks contained in curly braces (`{}`), you are able to collapse/fold them. With an `enum` (that can take up multiple lines with trailing commas or otherwise), you are unable to fold these "blocks".

**Describe the solution you'd like**
I'd like to be able to fold an dart `enum` in VS Code.

```dart
enum LoremIpsum {
  dolor,
  sit,
  amet,
  consectetur,
  adipiscing,
  elit,
  sed,
  eiusmod,
  tempor,
  incididunt,
  ut,
  labore,
}
```

to 

```dart
enum LoremIpsum {...
}
```

**Describe alternatives you've considered**
I've looked around at some settings, but I can't seem to find any obvious rules/settings to enable this behavior.

**Additional context**
In unsaved documents (_Untitled-1_-like) I am able to fold them with Dart language mode on. But once I save them as a `.dart` file, the option is gone. See images below.

> Before saving file:
<img width="301" alt="Before saving file" src="https://user-images.githubusercontent.com/38171761/112035352-d63f9f80-8b15-11eb-8a61-f039adac9224.png">

> Can fold:
<img width="295" alt="Can fold" src="https://user-images.githubusercontent.com/38171761/112035780-42ba9e80-8b16-11eb-969e-6604468386e5.png">

> After saving file:
<img width="346" alt="After saving file" src="https://user-images.githubusercontent.com/38171761/112035449-f2dbd780-8b15-11eb-91f6-e02cba7db915.png">

**Comment by DanTup** [comment]
Done in https://github.com/dart-lang/sdk/commit/bb8b26596b4afeed8736d062366545fa54f12e19.
