### ISSUE TITLE
BUG:  Id does not exist error 

### ISSUE THREAD

**Issue by junhwong** [Dart-Code/Dart-Code#3228]
**To Reproduce**
1. Run the DevTools widget inspector.
2. After modifying the code and hot loading: "Id does not exist" error appears
3. The error may disappear after restarting.

Specific error: 
```bash

Restarted application in 1,161ms.
Reloaded 2 of 785 libraries in 998ms.

[38;5;248m════════ Exception caught by Flutter framework ═════════════════════════════════[39;49m
[38;5;244mThe following assertion was thrown during a service extension callback for "ext.flutter.inspector.getDetailsSubtree":[39;49m
Id does not exist.

[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#0      WidgetInspectorService.toObject[39;49m
[38;5;244m#1      WidgetInspectorService._getDetailsSubtree[39;49m
[38;5;244m#2      WidgetInspectorService.initServiceExtensions.<anonymous closure>[39;49m
[38;5;244m#3      WidgetInspectorService.initServiceExtensions.<anonymous closure>[39;49m
[38;5;244m#4      BindingBase.registerServiceExtension.<anonymous closure>[39;49m
[38;5;244m...[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
Reloaded 2 of 785 libraries in 975ms.

```

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - VS Code version: 1.54.3
 - Dart extension version: 3.20.0/3.20.1
 - Dart/Flutter SDK version: Channel stable, 2.0.2, on Microsoft Windows. Dart version 2.12.1

**Comment by DanTup** [comment]
I think this may be a DevTools or Flutter issue. There's an open issue with the same error at https://github.com/flutter/devtools/issues/2824, so let's fold this into that one for now.

If you're able to provide a sample app that triggers this error, please post it on https://github.com/flutter/devtools/issues/2824. Thanks!
