### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by urbiyan** [Dart-Code/Dart-Code#3230]
- Issue Type: `Bug`
- Extension Name: `dart-code`
- Extension Version: `3.20.1`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.54.3`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by DanTup** [comment]
> ⚠️ We have written the needed data into your clipboard. Please paste! ⚠️

Are you able to provide this information? Thanks!
