### ISSUE TITLE
Dart Analyzer has terminated (crashing unexpectedly)

### ISSUE THREAD

**Issue by Zachariah-Abraham** [Dart-Code/Dart-Code#3231]
**Describe the bug**
When writing dart code, if you have an if condition in the format if(someVar == null or...), the dart analyzer immediately crashes. The analyzer crashes on VSCode whereas if you write this as a separate dart file and try to compile it from the terminal with the dart command, you get "Crash while compiling", with the same errors as in the end of the logs provided later on.

**To Reproduce**
1. Create a dart file on Visual Studio Code
2. Put this code in:
`void main() {
  int val;
  if(val == null or)
`
3. Wait for the dart analyzer to kick in automatically and crash. If yours doesn't crash automatically, try saving the file in this state, and you should see a notification saying "Exception from the Dart analysis server: Null check operator used on a null value". At this point, the analysis server has crashed, and needs to be restarted if you want to continue coding on your IDE with live dart code analysis.

**Expected behavior**
Ideally, the analyzer wouldn't crash. Typing "if(val == null ||" does not cause any issues.

**Screenshots**
**On VSCode when writing Flutter code, where there's live dart code analysis**
![image](https://user-images.githubusercontent.com/24973509/112548453-43875500-8de2-11eb-8487-ca9bbdc9395d.png)
**For an individual dart file on VSCode, where you have to save the file to crash the analyzer**
![image](https://user-images.githubusercontent.com/24973509/112550209-07a1bf00-8de5-11eb-85fb-212a56a8bd6a.png)
As you can see in the above image, once the exception arises, typing gibberish does not raise any errors in the "Problems" tab of VSCode because the analysis server has crashed. 

And in case the logs are required, this is what I have (starts with Flutter tasks): 
[log-68ec.txt](https://github.com/Dart-Code/Dart-Code/files/6208054/log-68ec.txt)

**Versions (please complete the following information):**
 - VS Code version: 1.54.3
 - Dart extension version: v3.20.1
 - Dart/Flutter SDK version: Dart: 2.12.1, Flutter: 2.0.2

**Comment by DanTup** [comment]
Thanks for the detailed report!

This was a bug in the Dart parser that failed when you had `or` instead of `||`. This has been fixed in https://github.com/dart-lang/sdk/issues/44785 and will be included in a future Dart/Flutter SDK release. Thanks!
