### ISSUE TITLE
Inspecting variables crash app and lost connection to device

### ISSUE THREAD

**Issue by rurickdev** [Dart-Code/Dart-Code#3232]
**Describe the bug**
The connection to device is lost when inspecting variable values in debug on vscode on Mac
Most of the time happens on async functions but also happen in minor quantity with sync functions

Some times it breaks when inspecting the first var other at the third or fourth nested

> This works well on linux with vscode, the issue is only on Mac, I haven't tested on Windows
> InteliJ, Android Studio and DartDevTool work well when inspecting var on breaks points on Mac issue only on vscode

**To Reproduce**
1. Create a new project
2. create an async function 
3. add a breakpoint in vscode editor
4. when reaching the breakpoint inspect the variables
5. the app stops running and debug console shows connection to device lost

**Expected behavior**
The app should keep running and let inspect the variables without crashing

**Screenshots**

![ezgif com-gif-maker (9)](https://user-images.githubusercontent.com/6403537/112676597-3c863400-8e2e-11eb-830f-846b5a1d3f22.gif)

**Versions (please complete the following information):**
 - VS Code version: 1.54.3
 - Dart extension version: 3.20.1
 - Dart version
```bash
Dart SDK version: 2.12.2 (stable) (Wed Mar 17 10:30:20 2021 +0100) on "macos_x64" 
```
- Flutter version
```bash
flutter doctor -v
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-MX)
    • Flutter version 2.0.3 at /Users/rurick.maqueo/Development/bins/flutter
    • Framework revision 4d7946a68d (8 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/rurick.maqueo/Library/Android/sdk/
    • Platform android-S, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.7759

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • iPhone 12 mini (mobile) • AEC1F096-5399-4DC5-88BC-64D940EC1EAD • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)         • macos                                • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 89.0.4389.90

• No issues found!
```

---

running with `-v` flag the console throws

```bash
Error handling 'checkPlatformOverride' custom request: method not available: ext.flutter.platformOverride
Error handling 'checkBrightnessOverride' custom request: method not available: ext.flutter.brightnessOverride
Error handling 'serviceExtension' custom request: method not available: ext.flutter.inspector.setPubRootDirectories
Error handling 'checkIsWidgetCreationTracked' custom request: method not available: ext.flutter.inspector.isWidgetCreationTracked
Lost connection to device.
```

> iOS using simulator
[log_ios.log](https://github.com/Dart-Code/Dart-Code/files/6213672/log_ios.log)

> Android using emulator
[log_android_emu.log](https://github.com/Dart-Code/Dart-Code/files/6213674/log_android_emu.log)

> Android using fisical device
[log_android_device.log](https://github.com/Dart-Code/Dart-Code/files/6213677/log_android_device.log)

**Comment by letsar** [comment]
One coworker had also this issue since Flutter 2. I changed my mac, and now I've also this issue.

**Comment by DanTup** [comment]
Thanks for the report! This was a Flutter issue and fixed by https://github.com/flutter/flutter/issues/77728.

It occurs when the debugger tries to evaluate all of the getters in the item. As a workaround, you can disable evaluation of getters until the fix is released with `"dart.evaluateGettersInDebugViews": false` - however the current live Dart-Code has a bug that also hides non-getters (fields) when that setting is disabled (see https://github.com/Dart-Code/Dart-Code/issues/3224). The fix for that is in the next release, which is also available as a beta at https://github.com/Dart-Code/Dart-Code/releases/tag/v3.21.0-beta.2.

Apologies for the inconvenience and bother!
