### ISSUE TITLE
Multiple `debugger();` statements in a codeblock messes up highlighting.

### ISSUE THREAD

**Issue by punkmath** [Dart-Code/Dart-Code#3233]
**Describe the bug**
In a codeblock with multiple `debugger()` statements, the highlighting is inconsistent.

**To Reproduce**
1. create the hello world app with `flutter create`
2. In `main.dart`, replace `_incrementCounter()` with:
```
void _incrementCounter() {
    print(0);
    debugger(); //1
    print(1);
    setState(() {
    print(2);
      debugger(); //2
    print(3);
      _counter++;
    print(4);
    });
    print(5);
    debugger(); //3
    print(6);
  }
```
3. Run (with or without debugging, it doesn't matter)

**Expected behavior**
On pressing the floating action button 
Line with `//1` should be highlighted first (and highlighted), followed by  `//2` and `//3` on continuing twice respectively.

**Screenshots**
### Ran the project(on web):
<img width="695" alt="Screenshot 2021-03-28 at 6 49 42 PM" src="https://user-images.githubusercontent.com/4429609/112753705-5e321780-8ff6-11eb-97e5-8942d34ba346.png">

### Clicked the FAB:
<img width="695" alt="Screenshot 2021-03-28 at 6 49 54 PM" src="https://user-images.githubusercontent.com/4429609/112753711-65f1bc00-8ff6-11eb-83c6-094de58d7299.png">

### Pressed continue:
<img width="695" alt="Screenshot 2021-03-28 at 6 50 54 PM" src="https://user-images.githubusercontent.com/4429609/112753738-87eb3e80-8ff6-11eb-9d58-d03ab08705fc.png">

### Pressed continue:
<img width="695" alt="Screenshot 2021-03-28 at 6 51 05 PM" src="https://user-images.githubusercontent.com/4429609/112753743-8e79b600-8ff6-11eb-8bf5-a5cca24c17d9.png">

**Versions (please complete the following information):**
 - VS Code version: 1.54.3 (Universal)
 - Dart extension version: 3.20.1
 - Dart/Flutter SDK version: Channel stable, 2.0.1, on macOS 11.2.3 20D91 darwin-x64

**Comment by punkmath** [comment]
Turns out, that it doesn't highlight the last `debugger()` in  the codeblock, but in the whole file!

**Comment by punkmath** [comment]
An easy workaround is to have a non-empty `when`, so, for example, use `debugger(when:true)`

**Comment by DanTup** [comment]
Thanks for the report! I can repro this, though only on web - so I think it may be a DWDS issue (it provides the information to understand the location of where the debugger pauses). I've filed this over at https://github.com/dart-lang/webdev/issues/1292 with some additional info from the debugger logs that will hopefully help fix. Please subscribe to that issue if you'd like updates.

Thanks!

**Comment by 4amvim** [comment]
My apologies, I should've mentioned the only web part.

**Comment by DanTup** [comment]
No problem, I suspected it might be web (there's a lot of complicated mapping that goes on for web). Looks like it's not DWDS, the original source map generated by ddc may be wrong, so I've filed https://github.com/dart-lang/sdk/issues/45544 about this.
