### ISSUE TITLE
Flutter Run hangs on installing

### ISSUE THREAD

**Issue by hedhyw** [Dart-Code/Dart-Code#3234]
**Describe the bug**
Application debug launch hangs on installing. If I run `flutter run` from the terminal, all works fine. Sometimes the issue goes away by itself.

**To Reproduce**
1. Open any flutter project.
2. F5 (Run->Start debugging)
3. Wait more than 10 minutes (nothing changes).

**Expected behavior**
Doesn't hang on installing.

**Screenshots**
![Screenshot_20210328_194038](https://user-images.githubusercontent.com/19246753/112760041-4199dd80-8ffe-11eb-8229-85e7e8c02ef0.png)

**Versions (please complete the following information):**
 - VS Code version: 1.54.3
 - Dart extension version: 3.20.1
 - Dart/Flutter SDK version: 2.0.3
 
 **Doctor summary**
 ```
 Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.3, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] VS Code (version 1.54.3)
[✓] Connected device (2 available)
 ```
 
 **Run log**
 ```
[7:48:13 PM]: Spawning /snap/flutter/current/flutter.sh with args ["run","--machine","--target","lib/main.dart","-d","192.168.31.242:5555","--dart-define=flutter.inspector.structuredErrors=true","--start-paused","--web-server-debug-protocol","ws","--web-server-debug-backend-protocol","ws","--web-allow-expose-url","--devtools-server-address","http://127.0.0.1:9100/"]
[7:48:13 PM]: ..  in /home/hedhyw/Development/linza/linza-app-flutter
[7:48:13 PM]: ..  with {"toolEnv":{"FLUTTER_HOST":"VSCode","PUB_ENVIRONMENT":"vscode.dart-code"}}
[7:48:13 PM]: PID: 82597
[7:48:16 PM]: <== [{"event":"daemon.connected","params":{"version":"0.6.0","pid":82628}}]
[7:48:16 PM]: <== [{"event":"app.start","params":{"appId":"6871c88c-9dbd-43cb-bd4d-95374a917807","deviceId":"192.168.31.242:5555","directory":"/home/hedhyw/Development/linza/linza-app-flutter","supportsRestart":true,"launchMode":"run"}}]
[7:48:16 PM]: <== Launching lib/main.dart on vivo 1804 in debug mode...
[7:48:17 PM]: <== [{"event":"app.progress","params":{"appId":"6871c88c-9dbd-43cb-bd4d-95374a917807","id":"0","progressId":null,"message":"Running Gradle task 'assembleDebug'...","finished":false}}]
[7:48:19 PM]: <== [{"event":"app.progress","params":{"appId":"6871c88c-9dbd-43cb-bd4d-95374a917807","id":"0","progressId":null,"finished":true}}]
[7:48:20 PM]: <== ✓ Built build/app/outputs/flutter-apk/app-debug.apk.

 ```

**Comment by DanTup** [comment]
Does this occur if you run the same command from the logs a terminal?

```
/snap/flutter/current/flutter.sh run --machine --target lib/main.dart -d 192.168.31.242:5555 --dart-define=flutter.inspector.structuredErrors=true --start-paused --web-server-debug-protocol ws --web-server-debug-backend-protocol ws --web-allow-expose-url --devtools-server-address http://127.0.0.1:9100/
```

There's not much the VS Code extension is doing here beyond running that process so there shouldn't be much difference (although there may be missing environment variables if you have some set up in terminal startup scripts that wouldn't apply to VS Code).

**Comment by hedhyw** [comment]
Thank you.

I tried this command with verbose flag and found that it got stuck on `"[ ] Waiting for observatory port to be available..."`. I go to https://github.com/flutter/flutter/issues.

**Comment by DanTup** [comment]
Actually, it occurs to me that passing `--web-allow-expose-url` when running from the terminal won't work, as that will try to send a request to VS Code for mapping ports.

Try it without `--web-allow-expose-url` and if it still hangs, I would raise it with Flutter. If it does not, then lets do some more debugging here. Thanks!

**Comment by hedhyw** [comment]
Yes, without `--web-allow-expose-url` it doesn't hung:

```
[        ] DevFS: Sync finished
[{"event":"app.progress","params":{"appId":"07ee9de5-8aaf-4533-a90f-e8c388291652","id":"1","progressId":null,"finished":true}}]
[   +2 ms] Synced 0.0MB.
[   +2 ms] <- accept
[ +494 ms] Connected to _flutterView/0x7752fc8820.
[{"event":"app.started","params":{"appId":"07ee9de5-8aaf-4533-a90f-e8c388291652"}}]
```

but the application only shows a black screen.

**Comment by DanTup** [comment]
Does the issue only occur with a specific app, or also if you create a new app with **Flutter: New Application Project** without making any changes?

If it still occurs, can you capture a log by:

- Run the [**Dart: Capture Debugging Logs** command](https://dartcode.org/docs/logging/#capture-debugging-logs)
- Start Debugging to reproduce the issue
- Click **Cancel** on the logging notification to stop logging and open the log
- Remove anything sensitive from the log
- Attach the log here (or in a gist)

This will capture a verbose log that may include more than you're normally seeing.

Thanks!

**Comment by hedhyw** [comment]
This issue sometimes goes away on its own, but today I was able to reproduce it again. 

I created a new flutter application project and collected logs:
https://gist.github.com/hedhyw/12dd15b4d3bf6c5560355566e9765a04

**Comment by DanTup** [comment]
Thanks - this appears to happening in Flutter and unrelated to the VS Code extension, so this would be best raised in the [Flutter issue tracker](https://github.com/flutter/flutter/issues). There are [some similar open issues](https://github.com/flutter/flutter/search?q=%22Waiting+for+observatory+port+to+be+available%22&type=issues) though I don't know whether any match your issue exactly.

My understanding is that at this point, Flutter is running `adb logcat` and then scanning the output to try and find the VM service URI. Why that's failing, I'm not sure (it could be logcat not working correctly, or could be the app might be crashing). I don't believe it's related to the `--web-expose-url` flag as in your log above it seems to be hanging before it's gotten that far (the logs do not show any request from Flutter to VS Code to call that function).
