### ISSUE TITLE
debugger seems to auto hot reload after hot restart

### ISSUE THREAD

**Issue by tjx666** [Dart-Code/Dart-Code#3235]
**Describe the bug**

Run the follow simple code:

```dart
import 'package:flutter/material.dart';

class TestWidgetLifeCycle extends StatefulWidget {
  TestWidgetLifeCycle({Key key}) : super(key: key);

  @override
  _TestWidgetLifeCycleState createState() => _TestWidgetLifeCycleState();
}

class _TestWidgetLifeCycleState extends State<TestWidgetLifeCycle> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Widget Life Cycle'),
      ),
      body: Column(
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceAround,
            children: [
              ElevatedButton(
                onPressed: () {
                  setState(() {});
                },
                child: Text('setState'),
              )
            ],
          ),
          _TestStatefulWidgetLifeCycle(),
        ],
      ),
    );
  }
}

class _TestStatefulWidgetLifeCycle extends StatefulWidget {
  _TestStatefulWidgetLifeCycle({Key key}) : super(key: key) {
    print('[#${identityHashCode(this)}][stateful widget] call constructor!');
  }

  @override
  StatefulElement createElement() {
    print('[#${identityHashCode(this)}][stateful widget] call createElement!');
    return super.createElement();
  }

  @override
  __TestStatefulWidgetLifeCycleState createState() {
    print('[#${identityHashCode(this)}][stateful widget] call create state!');
    return __TestStatefulWidgetLifeCycleState();
  }
}

class __TestStatefulWidgetLifeCycleState
    extends State<_TestStatefulWidgetLifeCycle> {
  @override
  void initState() {
    super.initState();
    print('[#${identityHashCode(this)}][stateful widget state] init state!');
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    print(
        '[#${identityHashCode(this)}][stateful widget state] call didChangeDependencies!');
  }

  @override
  void didUpdateWidget(covariant _TestStatefulWidgetLifeCycle oldWidget) {
    super.didUpdateWidget(oldWidget);
    print(
        '[#${identityHashCode(this)}][stateful widget state] call didUpdateWidget!');
  }

  @override
  void dispose() {
    print('[#${identityHashCode(this)}][stateful widget state] dispose!');
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      child: Text('stateful widget'),
    );
  }
}
```
The Stateful Widget seems to be updated caused by run command `hot reload`:

![image](https://user-images.githubusercontent.com/41773861/112763490-3adb8c80-9037-11eb-83ae-5ef786691674.png)

If I run hot reload, result in:

![image](https://user-images.githubusercontent.com/41773861/112763537-6cecee80-9037-11eb-8c93-f94d4a2ffc34.png)

**Versions (please complete the following information):**
 - VS Code version: 1.55.0-insider (Universal)
 - Dart extension version: v3.20.1
 - Dart/Flutter SDK version: Flutter 2.0.3, Dart 2.12.2

**Comment by DanTup** [comment]
I'm not able to reproduce this - when I Hot Reload it does not call the constructor/didUpdateWidget:

<img width="640" alt="Screenshot 2021-03-29 at 10 51 48" src="https://user-images.githubusercontent.com/1078012/112819749-ce837c00-907c-11eb-9dd4-2d1690aed1e6.png">

Can you provide a complete code sample? The code above is missing a `main` method so I don't know if I implemented it the same way.

I would also try from the terminal using `flutter run` to see if you see the same behaviour. If so, then it would be better to raise at https://github.com/flutter/flutter/ as it might not be related to the VS Code extension. Thanks!

**Comment by tjx666** [comment]
reproduce repository: https://github.com/tjx666/flutter_study/blob/master/lib/main.dart

If I run in terminal, the hot reload result is right:

![image](https://user-images.githubusercontent.com/41773861/112862502-679bac80-90e8-11eb-9b68-ba1567263282.png)

**Comment by DanTup** [comment]
@tjx666 sorry for the delay. I've not been able to repro using your sample project either on stable or latest master - I get the same output as you from the terminal and no call to didUpdateWidget:

<img width="841" alt="Screenshot 2021-04-12 at 17 02 45" src="https://user-images.githubusercontent.com/1078012/114425427-f8768b80-9bb0-11eb-8672-9f39841dc068.png">

Could you try capturing debugging logs while reproducing this?

- Run the [**Dart: Capture Debugging Logs** command](https://dartcode.org/docs/logging/#capture-debugging-logs)
- Reproduce the issue
- Click **Cancel** on the logging notification to stop logging and open the log
- Remove anything sensitive from the log
- Attach the log here (or in a gist, or email to me at logs@dartcode.org)

Thanks!

**Comment by tjx666** [comment]
This seems to be fixed in latest extension.

**Comment by DanTup** [comment]
I'm not sure what changed to fix it, but glad it seems to be resolved. If it comes back, please let me know. Thanks!
