### ISSUE TITLE
"Get packages" runs "flutter pub get" for Dart package when workspace contains a Flutter package

### ISSUE THREAD

**Issue by isoos** [Dart-Code/Dart-Code#3237]
I've started to use VSCode with WSL2 remote, and I have a mixed set of projects using Dart and Flutter SDKs. (Note: this may have been already implemented, I just don't know where to look for it).

Right now if I open `pubspec.yaml` and click on get packages, I'll always get `flutter pub get` running. Instead, I'd like to control if a subfolder uses only the Dart SDK, and in such cases I'd like to have `dart pub get` running.

**Comment by DanTup** [comment]
This is a bug - it is intended to work as you expected:

https://github.com/Dart-Code/Dart-Code/blob/896e4976b7f9cc36a8ec1b6d1c1c061dea721ab7/src/extension/commands/sdk.ts#L103-L106

But in some places (like that menu bar) it seems to still be calling a Flutter-specific version.
