### ISSUE TITLE
Dart null safety in VS Code in google3

### ISSUE THREAD

**Issue by amirburbea** [Dart-Code/Dart-Code#3239]
Not a common case, but I have a project at google that uses ACX (and as such can not migrate to null safety) but it references a library that I built also in google3 with null safety.

Let's call the acx project "web" and the null safe project "library".  When editing code in "web" I have problems now where vs code's dart linter is telling me I shouldn't check certain variables for null or so because since the parameter to the method is `RouterState` as opposed to `RouterState?` (which I can't even set it as without causing a compile failure)

I tried setting blaze to import dart_project and added `dart_project(null_safety = False)` to no avail.

As an FYI my id at google is doubledown@

**Comment by DanTup** [comment]
Do you know if this can be reproduced outside of google3 code? I'm not very familiar with (and have no access to) google3/Blaze/ACX so if it only occurs there this may need someone else to help debug (fyi @devoncarew @bwilkerson).

Is it possible to open the same project(s) in IntelliJ/Android Studio to see whether the same occurs there? (it sounds like something that might be more analyzer specific than VS Code).
