### ISSUE TITLE
flutter tools accumulates arguments on each debug start

### ISSUE THREAD

**Issue by annagrin** [Dart-Code/Dart-Code#3242]
I printed the arguments from `flutter_tools.dart` executable and found that an extra `--devtools-server-address` argument is added each time I start the debugger:

```
flutter "run" "--machine" "--target" "lib/main.dart" "-d" "chrome" "--dart-define=flutter.inspector.structuredErrors=true" "--start-paused" "--web-server-debug-protocol" "ws" "--web-server-debug-backend-protocol" "ws" "--devtools-server-address" "http://127.0.0.1:9101/" "--devtools-server-address" "http://127.0.0.1:9101/" "--devtools-server-address" "http://127.0.0.1:9101/" "-v" "--web-renderer=auto"
```

**To Reproduce**
1. add `print('flutter ${args.map((x) => '"$x"').join(' ')}');` to `flutter_tools/bin/flutter_tools.dart` before calling `main`
2. Rebuild flutter_tools (I delete `flutter/bin/cache` and run `flutter pub get`)
2. Debug flutter's example/hello_world
2. Debug again
3. Observe the printed command getting longer.

**Comment by DanTup** [comment]
Thanks! This was recently fixed in #3198 and will be included in todays release.
