### ISSUE TITLE
Add an Option for "Auto-insert `//` for additional non-dartdoc comment lines" Feature

### ISSUE THREAD

**Issue by justinStratis** [Dart-Code/Dart-Code#3248]
Thanks for a great extension.

**Is your feature request related to a problem? Please describe.**
This is related to issue #3203, which added the feature of automatic insertion of `//` on the next line when Enter is pressed on a `//`-commented line.

This breaks my expectations of how the editor should work and, AFAIK, isn't consistent with other languages.  IMO, `///` or `/* */` differ from `//` in the context of pressing Enter.  With the former, I'm in the mode of writing documentation (or at least larger) comments.  In contrast, with `//`, I'm usually writing a single-line comment or I've just commented out a block of code.  In either case, automatically adding `//` is undesirable and unexpected.

**Describe the solution you'd like**
An option to control this newly-added feature; preferably, disabled by default.

**Comment by DanTup** [comment]
Here's what I've added - `tripleSlash` will be the default. Feedback welcome!

![Screenshot 2021-04-07 at 12 46 49](https://user-images.githubusercontent.com/1078012/113861652-5c5b1780-979f-11eb-81a6-83f12034c793.png)
