### ISSUE TITLE
Extension triggers VS Code refactor refactoring when not in a dart project when LSP is disabled

### ISSUE THREAD

**Issue by Pluriscient** [Dart-Code/Dart-Code#3250]
**Describe the bug**
The extension tries to apply refactoring when moving files while not in a project that uses any dart files.

**To Reproduce**
1. Open any project 
2. Move a file
3. Get a prompt that Dart wishes to refactor
**Expected behavior**
The extension should not be active when not in a project that uses Dart. 

**Screenshots**

**Versions (please complete the following information):**
 - VS Code version: 1.55.0
 - Dart extension version: 3.21.1
 - Dart/Flutter SDK version:

**Comment by DanTup** [comment]
Thanks - I can repro this when LSP is not enabled.

Although - it suggests that the Dart extension is being activated for your non-Dart project. I'd be interested in understanding why that is - does your open folder have any Dart or pubspec.yaml files in it? Is it a large workspace?
