### ISSUE TITLE
Name non-constant identifiers using lowerCamelCase.

### ISSUE THREAD

**Issue by spacekestrel** [Dart-Code/Dart-Code#3252]
It seems, that there is no way to disable this linting in flutter plugin on VS Code. 
Which for me is if not a bug, but a issue for sure, because i think that i can decide on my own how to name variables. 
And to add every time  " // ignore: non_constant_identifier_names" is not a solution at all.

**Comment by DanTup** [comment]
Flutter ships its own set of default lint rules that are used if you don't have your own `analysis_options.yaml` file. You can find that file here:

https://github.com/flutter/flutter/blob/master/analysis_options.yaml

That list includes `non_constant_identifier_names`.

If you don't want to use Flutters defaults, you would need to create your own `analysis_options.yaml` file (you can copy that one into the root if your project and customise it).

Let me know if you have any problems getting that to work. Thanks!

**Comment by JigarKotak7** [comment]
In your project room there is a file called analysis_options.yaml, in there under rules put below line and it will ignore the rule for your whole project.

// ignore: non_constant_identifier_name
<img width="898" alt="Screen Shot 2021-09-22 at 7 25 34 PM" src="https://user-images.githubusercontent.com/31124960/134357211-6313f0a4-918d-42b4-a9e1-f01eb39ccd04.png">
s

**Comment by DanTup** [comment]
You should comment things out with `#` in YAML, using `// ignore:` is for Dart files.
