### ISSUE TITLE
Single-action quick-fixes could just show one-click buttons?

### ISSUE THREAD

**Issue by eseidel** [Dart-Code/Dart-Code#3254]
Low priority, please feel free to close w/o action.

**Is your feature request related to a problem? Please describe.**
For single-line quick fixes, just showing a button to fix would be nice?
Example:
![Screen Shot 2021-04-05 at 1 20 18 PM](https://user-images.githubusercontent.com/478541/113622449-df4e6780-9611-11eb-944b-0c3a43a31d58.png)

**Describe the solution you'd like**
Imagine two little buttons on the right "remove" "ignore".

**Describe alternatives you've considered**
Maybe "command-.; down-arrow; enter" is already sufficient?

**Comment by DanTup** [comment]
Unfortunately we don't get control over the UI in places like this. VS Code asks us for a list of fixes and we provide them, and it controls the whole UI (which in many ways is good - it ensures consistency across all languages - but in other ways can be limiting).

That said, you can make keybindings that can be filtered based on code action types - eg. you can have something like `cmd+.` that only shows Fixes (no refactors etc.), and you can also set that to automatically apply when there is only one. It would look something like this in your VS Code key bindings file:

```js
{
	"key": "cmd+shift+.",
	"command": "editor.action.codeAction",
	"args": {
		"kind": "quickfix",
		"apply": "ifSingle"
	}
}
```

However, I did just discover that the "add ignore" action is also categorised under `quickfix` which means `ifSingle` won't work (it will always see two fixes), so right now it'll only work properly if you also set `"dart.showIgnoreQuickFixes": false` - however I'm going to change that (I've filed https://github.com/Dart-Code/Dart-Code/issues/3255).

**Comment by DanTup** [comment]
Closing this as I don't think there's anything we can do here (besides make the keybinding work better, which is covered by #3255) but lmk if you think there are other things we should try to explore.

I did also add a note to this VS Code issue https://github.com/microsoft/vscode/issues/98618 which was a request along similar lines to make it easier to apply fixes from here.
