### ISSUE TITLE
Review surroundingPairs in language config

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#3264]
See https://github.com/Dart-Code/Dart-Code/issues/3183#issuecomment-792963300.

**Comment by DanTup** [comment]
After reviewing this and testing again, I'm not sure removing things like parens is the best idea. Other similar languages have these settings, and there is a VS Code user setting that allows changing these. If we remove the parens, users can't add them back - whereas if we leave it as-is, the user can switch to only quotes in the VS Code settings if they want.

So I think the best options are:

- Don't change anything - allow users to just change the Auto Surround setting if they wish
- Don't change the language options, but do override the default for AutoSurround for Dart to only quotes. This would initially have the same behaviour as updating `surroundingPairs`, but it would still allow the user to have the full set (by changing `autoSurround` back to `languageDefined` for `["dart"]`).

@timsneath - any opinions on this (since you noted it at https://github.com/Dart-Code/Dart-Code/issues/3183#issuecomment-792903464)?

**Comment by timsneath** [comment]
I don't have a ton of opinions here -- I trust your judgement! My own experiences were improved considerably when I turned off the experimental settings. 

In general, I find it really useful to have the editor help me when I'm typing a line of code -- for example, when I type the open parenthesis on a new line of code and it sets me up with the parameters I need. But it's really frustrating when I'm editing an existing line of code and tab to complete a method only to have it insert or overwrite the remainder of the line. But perhaps others have either a better intuition for what the editor is about to do than I do...

**Comment by DanTup** [comment]
I think there are two related, but different things here.

For the surroundingPairs (the behaviour when you have a selection and press `(`, `"` etc. which surrounds the text), unless you feel strongly I'm inclined to leave it as-is, since the editor has a setting to override this (and I think based on your other issue you may prefer to have it set to "quotes"):

<img width="865" alt="Screenshot 2021-04-26 at 18 48 43" src="https://user-images.githubusercontent.com/1078012/116127712-10c1cc80-a6c0-11eb-8b8f-96562820f296.png">

I think the other comments relate to completion, and when we insert the parens/argument placeholders automatically - and I agree there's room for improvement there too. There are some cases we try to handle to avoid inserting them when they're already there after the caret, though I'm not sure it covers enough cases (I saw some unwanted parents inserted just today). I've filed #3303 as a reminder to take a look. Thanks!

**Comment by DanTup** [comment]
(I'll close this one and leave as-is, but if it comes up more, I'll consider the second option above, leaving the language to define all of the pairs, but defaulting to `quotes` instead of `languageDefined` so people can change it back).

**Comment by DanTup** [comment]
I just landed a fix for #3303 in https://github.com/dart-lang/sdk/commit/8f2c0e9bb8076225923e86c19fbdf4117dc5d0bb that prevents inserting the parens/arg placeholders when they already exist for the target you're completing.

However, re-reading what you wrote:

> only to have it insert or overwrite the remainder of the line.

I don't know if I misunderstood and there's something else going on here. Perhaps you mean this:

```dart
^foo(bah);
```

You complete at `^` and want to _wrap_ the existing code in a new function call, but it thinks you want to replace `foo` with something else? If so, there's a VS code setting that controls whether to insert or replace by default (we default to replace). Holding down Ctrl or Cmd should change this, it will insert instead (this lets you change per-completion, without having to change the setting). If this is what you meant and that doesn't work for you, let me know.
