### ISSUE TITLE
`part` Directive Quick-fix Should Auto-fill Path of Source File

### ISSUE THREAD

**Issue by Luckey-Elijah** [Dart-Code/Dart-Code#3268]
**Is your feature request related to a problem? Please describe.**
When using `part` directives in Dart, Dart-Code offers one of my favorite quick fix features with `Create file '<path>'`. The file is created as expected, but doesn't populate the `part of ;` directive in the created file.

First file: `foo.dart`
```dart
part 'bar.dart';
```

Created file: `bar.dart`
```dart
part of ; // not filled
```

**Describe the solution you'd like**
When using the 'Create file' quick fix feature, the created file should be populated with the relative path of the source file.

First file: `foo.dart`
```dart
part 'bar.dart';
```

Created file: `bar.dart`
```dart
part of 'bar.dart';
```

**Describe alternatives you've considered**
As far as I've noticed, the feature only produces with the "unfilled" path behavior.

**Additional context**

Current behavior:

<img height="225" alt="Screen Shot 2021-04-09 at 6 48 48 PM" src="https://user-images.githubusercontent.com/38171761/114247867-39c62b80-9964-11eb-90cd-2ce2625c78f5.png"> <img height="225" alt="Screen Shot 2021-04-09 at 6 49 07 PM" src="https://user-images.githubusercontent.com/38171761/114247892-4480c080-9964-11eb-89f9-5158cf2e4eb6.png">

Desired behavior:
<img height="225" alt="Screen Shot 2021-04-09 at 6 48 48 PM" src="https://user-images.githubusercontent.com/38171761/114247867-39c62b80-9964-11eb-90cd-2ce2625c78f5.png"> <img height="225" alt="Screen Shot 2021-04-09 at 6 50 26 PM" src="https://user-images.githubusercontent.com/38171761/114247965-73973200-9964-11eb-81e4-ebd6eb146ce7.png">

**Comment by DanTup** [comment]
This is fixed by https://github.com/dart-lang/sdk/commit/5dbf8992ed1edeef55093f4bac72a4d23ce64f75. With that change, the generated file will always use the URI instead of library name (which is the recommended way now).

Since it's an SDK change, it'll show up in a future SDK release rather than a Dart-Code release. Thanks!
