### ISSUE TITLE
`export` Quick-fix should include `Create file 'path'`

### ISSUE THREAD

**Issue by Luckey-Elijah** [Dart-Code/Dart-Code#3269]
**Is your feature request related to a problem? Please describe.**
With the `part`/`part of ;` directive quick fix feature, I sometimes expect the `export` directive to also have `Create file 'path';` option in its quick fix menu.

**Describe the solution you'd like**
When the target URI doesn't exist (`uri_does_not_exist`) for an export directive, there should be a quick fix option: `Create file 'path'`.

**Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

**Additional context**

No `Create file 'bar.dart;'` in Quick Fix menu.

<img width="606" alt="Screen Shot 2021-04-09 at 7 01 53 PM" src="https://user-images.githubusercontent.com/38171761/114248596-0d131380-9966-11eb-9397-6dd79677e043.png">

But should create a file like: 
<img width="506" alt="Screen Shot 2021-04-09 at 7 04 00 PM" src="https://user-images.githubusercontent.com/38171761/114248709-5a8f8080-9966-11eb-832e-2010694f7b73.png">

**Comment by DanTup** [comment]
@bwilkerson do you see any reason not to support this for `export` as well as `import`? I'm not sure if it's deliberate or accidental (the use of `ImportDirective` [here](https://github.com/dart-lang/sdk/blob/82ea8416ed2a22e40c5c67252cb37bebec3a57e8/pkg/analysis_server/lib/src/services/correction/dart/create_file.dart#L26) versus `NamespaceDirective`).

**Comment by bwilkerson** [comment]
I believe it's an oversight.

**Comment by DanTup** [comment]
This is fixed by https://github.com/dart-lang/sdk/commit/419fd676d2e9bf128b6cb18f057370947e7018a8 which will be included in a future Dart/Flutter SDK release.
