### ISSUE TITLE
dart.updateImportsOnRename not working

### ISSUE THREAD

**Issue by ThorgeL** [Dart-Code/Dart-Code#3271]
**Describe the bug**
I have dart.updateImportsOnRename as true, however if I move a file or rename one no imports are updated.

**Versions (please complete the following information):**
 - VS Code version: v1.55.1
 - Dart extension version: v3.21.1
 - Dart/Flutter SDK version: Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.7), Dart 2.12.2 (stable)

**Comment by ThorgeL** [comment]
Update: Found the error. My bad.

I had the parent folder open in VS Code that contains the .devcontainer and .github files. Everything else worked besides 
dart.updateImportsOnRename. Now that I am in the subfolder everything works fine.

**Comment by DanTup** [comment]
I wouldn't expect opening the parent folder to stop this from working. If you can make a small repro you can share (or exact instructions), I'd be interested in understanding why it failed. Thanks!
