### ISSUE TITLE
Add swap option to ternary operation in vscode extension

### ISSUE THREAD

**Issue by guenth39** [Dart-Code/Dart-Code#3273]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I would like to have Quick Fix to Swap the options of a ternary operation like swap with parent or swap with child.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/29251617/114415494-07107300-9bb0-11eb-8198-923ff930e120.png)

**Comment by DanTup** [comment]
Thanks for the suggestion! These actions actually come from the language server, so this should be raised at https://github.com/dart-lang/sdk. One added to the language server (and you update to an SDK that includes it), the actions will automatically show up in VS Code (and IntelliJ/Android Studio).

Thanks!

**Comment by guenth39** [comment]
I have added an issue there. Here is the link for those who want to follow up.
https://github.com/dart-lang/sdk/issues/45669
