### ISSUE TITLE
Flutter fails to launch iOS simulator when Simulator App is running but Device Window is closed

### ISSUE THREAD

**Issue by osaxma** [Dart-Code/Dart-Code#3277]
### Problem
Flutter fails to open the iOS Simulator when the device window is closed but the Simulator app is actually running (i.e. shown in the dock like in the image below:) 

<p align="center">
<img width="74" alt="Screen Shot 2021-04-12 at 7 26 07 PM" src="https://user-images.githubusercontent.com/46427323/114428484-f0284b80-9bc4-11eb-85e1-febdf70c9617.png"></p>

When the Simulator is in the above state, the following will process run for few minutes before it times out:
<p align="center">
<img width="484" alt="Screen Shot 2021-04-12 at 7 21 27 PM" src="https://user-images.githubusercontent.com/46427323/114428190-8f007800-9bc4-11eb-9a15-f65cc08f6b21.png"></p>

To reproduce:
- open a flutter project with VS Code in MacOS where the project is for both iOS and Web. 
- Open the iOS simulator 
- Close the iOS simulator without quitting it (cmd + w or the 'x' red button). 
- Wait few seconds until VS code switches to Chrome (web-javascript) at the bottom. 
- Try to change the device back to iOS 
- `waiting for iOS simulator to connect` will run for few minutes before it times out saying that it couldn't launch the device.

### Expected Behavior
The device should be shown again. 

If this is an issue with the Simulator App itself, please consider one of those alternatives:
- provide a way to terminate the process (ie `waiting for iOS simulator to connect`).  
- show a message that the simulator app needs to be quitted. 

### Additional Context
This usually happens when I switch between Web and iOS development and I close the simulator instead of quitting it. Even when I realize the situation, there is no way to terminate `waiting for iOS simulator to connect`. 

Versions:
- dart-code extension v3.21.1
- VS Code version v1.55.1
- Flutter Version: 
```
Flutter 2.0.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b1395592de (11 days ago) • 2021-04-01 14:25:01 -0700
Engine • revision 2dce47073a
Tools • Dart 2.12.2
```

**Comment by DanTup** [comment]
Thanks for the report! This looks like it'll need fixing in Flutter (it reproduces using `flutter emulator --launch ios` - which is essentially what VS Code is falling) so should be raised at https://github.com/flutter/flutter/.

Thanks!
