### ISSUE TITLE
auto compete not working in vscode

### ISSUE THREAD

**Issue by mkasaii16** [Dart-Code/Dart-Code#3280]
Issue Type: <b>Performance Issue</b>

hello.
after update dart,auto compete not working.

Extension version: 3.21.0
VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX-8800P Radeon R7, 12 Compute Cores 4C+8G  (4 x 2096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.96GB (3.49GB free)|
|Process Argv|--crash-reporter-id 9a0db8df-6aec-4615-8d0b-fcbf66a715fe|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    58	  2476	code main
    6	    47	  1792	   shared-process
    0	    13	  1396	     ptyHost
    0	     2	  6048	       console-window-host (Windows internal process)
    0	    38	  7632	       "C:\Program Files\PowerShell\7\pwsh.exe"
    0	   190	  1800	   window (home.dart - doodle - Visual Studio Code)
    0	     5	  8264	     watcherService 
    0	     0	 10236	       console-window-host (Windows internal process)
    0	    91	  8552	     extensionHost
    0	     0	  3148	       C:\Windows\system32\cmd.exe /d /s /c ""c:\src\flutter\bin\cache\dart-sdk\bin\pub.bat" "global" "run" "devtools" "--machine" "--try-ports" "10" "--allow-embedding" "--port" "9100""
    0	     6	  6148	         "c:\src\flutter\bin\cache\dart-sdk\bin\dart"   "c:\src\flutter\bin\cache\dart-sdk\bin\snapshots\pub.dart.snapshot" "global" "run" "devtools" "--machine" "--try-ports" "10" "--allow-embedding" "--port" "9100"
    0	     1	 10548	         console-window-host (Windows internal process)
    0	    14	  5320	       G:\Programing\go\bin\gopls.exe -mode=stdio
    0	     1	  5940	         console-window-host (Windows internal process)
    0	   108	  7604	       "C:\Users\Moein\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Moein\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=8552
    0	     0	  7756	       C:\Windows\system32\cmd.exe /d /s /c ""c:\src\flutter\bin\flutter.bat" "daemon""
    0	     1	  5140	         console-window-host (Windows internal process)
    0	    86	  7916	         "c:\src\flutter\bin\cache\dart-sdk\bin\dart.exe"  --disable-dart-dev --packages="c:\src\flutter\packages\flutter_tools\.packages"  "c:\src\flutter\bin\cache\flutter_tools.snapshot" "daemon" 
    2	    89	  6088	   gpu-process
    0	     2	  6780	   crashpad-handler
    0	    16	  9908	   utility
    3	    78	 10740	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (home.dart - doodle - Visual Studio Code)
|    Folder (doodle): 903 files
|      File types: json(108) xml(108) flat(96) png(31) ttf(23) jar(19) bin(12)
|                  properties(8) lock(6) txt(6)
|      Conf files: launch.json(1)
|      Launch Configs: dart(3);
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30281910
pythontb:30283811
openwsldoc:30282072
vspre833:30267464
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30276952
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30286881

```

</details>

**Comment by DanTup** [comment]
> after update dart,auto compete not working.

Can you be more specific about the problem you're seeing? Is the issue that the code completion doesn't appear automatically, or that it has the wrong items, or that it shows "Loading..." forever?

**Comment by mkasaii16** [comment]
yes .code completion doesn't appear automatically
even with CTRL+SPACE doesn't working and remains in loading mode

**Comment by DanTup** [comment]
@mkasaii16 when this occurs, does all language functionality stop working until you restart VS Code, or does it continue working after some time?

Can you hover over the Dart version in the status bar and see whether it says "LSP" or "DAS"?

<img width="294" alt="Screenshot 2021-04-20 at 12 23 42" src="https://user-images.githubusercontent.com/1078012/115388002-46077f80-a1d3-11eb-9671-5b8a6ca575e5.png">

If it says "DAS", can you try setting `"dart.previewLsp": true` in your VS Code user settings and restart VS Code, and see if the issue goes away?

Thanks!
