### ISSUE TITLE
no devices connect

### ISSUE THREAD

**Issue by fredgrott** [Dart-Code/Dart-Code#3285]
It was working just 3 days ago.

dart devtools version 2.1.1.
VSCOde Version Insiders Edition 1.56.0
dart code version 3.21.1
dart code flutter 3.21.0

in the right bottom part of the toolbar bottom usually, the chrome web or ms edge will show up, and clicking it will allow me to either pick the two web browsers or the android emulators.

Now it shows nothing just no devices and when I do attempt an android emulator launch it does not see it connection-wise.

Not sure what the problem is.

I looked in the Code/logs folder and did not find anything obvious.

Well, dart devtools updated on April 6 to 2.1.1

And something else was strange in that when devtools launches in the browser the view inspector panel is missing.

Not immediate as I am wri5tng some dev articles the next two days.

let me know what other info you need to track this down

**Comment by fredgrott** [comment]
for anyone on windows, it's a windows issue with the new features build release. I resolved it by re-installing that features release build. Recommend closing this bug report

**Comment by DanTup** [comment]
> it's a windows issue with the new features build release

Can you clarify exactly what this is? I don't use Windows so I'm a little unsure what it relates to, but if something is preventing Flutter from detecting devices it may be worth trying to improve. Thanks!
