### ISSUE TITLE
Intellisense doesn't recognize return type named parameter in doc comment

### ISSUE THREAD

**Issue by jeiea** [Dart-Code/Dart-Code#3287]
**Describe the bug**
Intellisense emits the following unexpected weak warning on `[b]` usage. But it doesn't complain on `[a]`.
`Only reference in scope identifiers in doc comments.`

**To Reproduce**
1. Create the following dart file.
```
class A {
  /// [a] [b]
  Future<void> Function(int a, {int b})? a;
}
```

**Expected behavior**
No error appears.

**Screenshots**
![image](https://user-images.githubusercontent.com/4188984/115221486-af8c7d00-a144-11eb-838c-d098988d05ac.png)

**Versions (please complete the following information):**
 - VS Code version: 1.55.2
 - Dart extension version: 3.21.1
 - Dart/Flutter SDK version:
```
Flutter 2.0.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b1395592de (3 weeks ago) • 2021-04-01 14:25:01 -0700
Engine • revision 2dce47073a
Tools • Dart 2.12.2
```

**Comment by DanTup** [comment]
I don't think this is specific to it being named, I think the reason `a` works is that's the name of the identifier. If you change that, you'll see the positional parameter also doesn't work.

I don't know if it's something that can/should work, but it would need to be implemented in the language server and/or linter, so should be raised in the SDK repo here:

https://github.com/dart-lang/sdk/issues

Please post back a link here so others that find this issue can follow and add 👍 's there.

Thanks!
