### ISSUE TITLE
Debugging isn't stopped by apk install failure

### ISSUE THREAD

**Issue by Skylled** [Dart-Code/Dart-Code#329]
![Screenshot](http://i.imgur.com/anxmgbC.png)

The debugger is still trying its hardest.

The failure, on Flutter's side, is [here](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_device.dart#L278). My guess is that either a signal is being sent and DC isn't picking it up, or there's no signal being sent here. I'll find time to test the same scenario with IntelliJ to see how it stacks up.

**Comment by Skylled** [comment]
Relevant logs from IntelliJ
```[{"event":"app.progress","params":{"appId":"f58301a2-7c89-48f9-bebb-0ea90965839f","id":"1","progressId":null,"message":"Installing build\\app/outputs/apk/app.apk..."}}]
[      +13 ms] C:\Android\sdk\platform-tools\adb -s LGH9107a67a5fd install -r build\app/outputs/apk/app.apk
[    +1226 ms] Failed to install build\app/outputs/apk/app.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl1076058160.tmp/base.apk using APK Signature Scheme v2: SHA-256 digest of contents did not verify]
[{"event":"app.progress","params":{"appId":"f58301a2-7c89-48f9-bebb-0ea90965839f","id":"1","progressId":null,"finished":true}}]
[       +3 ms] Error: ADB exited with exit code 1
[            ] Warning: Failed to install APK.
[            ] Error launching application on LG H910.
[{"event":"app.stop","params":{"appId":"f58301a2-7c89-48f9-bebb-0ea90965839f"}}]
[{"id":0,"error":"app 'f58301a2-7c89-48f9-bebb-0ea90965839f' not found"}]```

**Comment by DanTup** [comment]
@Skylled Is there an easy way I can repro this sort of failure? I just tested by having no devices attached, but it seemed to handle it fine (`flutter run` terminated, which ends the debug session). Not sure if it's since been fixed or whether it's a different type of failure.

**Comment by Skylled** [comment]
No, I wish. I can't even get a solid repro for the flutter devs. `flutter run` just quits when the problem comes up.

It's an edge case, that I wish I wasn't part of.

**Comment by DanTup** [comment]
I checked the code, and it looks like as long as `flutter run` terminated, we should disconnect fine ([by sending `TeminatedEvent`](https://github.com/Dart-Code/Dart-Code/blob/c4af2fbf4ea19ea1080749a2f29d9b2b4ead3e06/src/debug/dart_debug_impl.ts#L102)). This isn't new code, so I wonder if `flutter run` isn't terminating correctly in this case.

I'll see if I can repro by disconnecting the device during deployment or something.

**Comment by Skylled** [comment]
Okay, so I traced out the error message `Error launching application on {device}` to `runHot` [resident_runner](https://github.com/flutter/flutter/blob/030abfd49a488105174fcf7bded9c38ba2b94048/packages/flutter_tools/lib/src/resident_runner.dart#L249) which is hooked into `run` in [HotRunner](https://github.com/flutter/flutter/blob/2f737cf94ebb075b5e10ba2bace1d6d748b891c0/packages/flutter_tools/lib/src/run_hot.dart#L183), which is called by the [flutter run](https://github.com/flutter/flutter/blob/9adb4a78a6c273f48b13614da0ceb220339c143f/packages/flutter_tools/lib/src/commands/run.dart#L329) command, and in this case should use `throwToolExit` to throw an exception and stop the program.

Maybe it's abruptly ending, and not sending a signal to DC?

**Comment by DanTup** [comment]
We hook when the process exits which should fire in all cases :( I'll see if disconnecting during deployment causes same behavior.. should be easy to fix if so!

**Comment by DanTup** [comment]
Yanking the cable during an install results in same behaviour - debugger doesn't disconnect.

![Repro](https://user-images.githubusercontent.com/1078012/27951939-7e523636-62fe-11e7-90e0-958af86225ab.png)

**Comment by DanTup** [comment]
I've raised https://github.com/flutter/flutter/issues/11103 - seems like `flutter run --machine` is incorrectly (IMO) not terminating after an install failure.

**Comment by DanTup** [comment]
I've added some code to terminate the flutter process when it sends an `app.stop` event in the meantime.
