### ISSUE TITLE
Support fold the function parameters

### ISSUE THREAD

**Issue by tjx666** [Dart-Code/Dart-Code#3297]
Like TypeScript fold code example bellow, I hope dart code also support it to make code looks more clear when folded.

![image](https://user-images.githubusercontent.com/41773861/115835021-6ab85d00-a448-11eb-9137-acebc9109682.png)

![image](https://user-images.githubusercontent.com/41773861/115835084-799f0f80-a448-11eb-87ca-f0887e018a30.png)

**Comment by tjx666** [comment]
Another problem is that I found for loop block is also not support to folded:

![image](https://user-images.githubusercontent.com/41773861/115838802-a0f7db80-a44c-11eb-9c90-dfaa31581bb6.png)

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/d3082bcb3ec640ed9d74194f8144fee7e5ce3fd1. As it's in the language server, it'll show up in a future Dart/Flutter SDK release (not the VS Code extension release).
