### ISSUE TITLE
Request ability to format on save

### ISSUE THREAD

**Issue by sethladd** [Dart-Code/Dart-Code#330]
I looked into the preferences and didn't see an option. I'd love to "format on save", if that's possible.

Thanks!

**Comment by pulyaevskiy** [comment]
It's there, but I also struggled to find it the first time:

```
"editor.formatOnSave": true,
```

**Comment by DanTup** [comment]
Yep, that's the setting you want. It's not Dart-specific so it's not prefixed with `dart.` (it's VS Code behaviour). If you only want it for Dart you can do that, look for the [Language specific settings](https://code.visualstudio.com/docs/getstarted/settings#_language-specific-editor-settings) command which will add `"[dart]" { ... }` to your settings (you can also do this manually).

Dart Code also format-on-type provider so you may want to enable this to have the doc formatted whenever you press certain keys (like `}`):

`editor.formatOnType: true`

Hope this does what you need!

**Comment by sethladd** [comment]
Ah, great! Thanks!
