### ISSUE TITLE
provider command 'select this widget'

### ISSUE THREAD

**Issue by tjx666** [Dart-Code/Dart-Code#3305]
Sometimes I would like to extract part code from one Widget to another Widget. This extension provides the `Extract Widget` refactor command, but not all condition can success do it, like following condition:

![image](https://user-images.githubusercontent.com/41773861/116179814-8d00f200-a74a-11eb-9b29-3b9ba22acc23.png)

So I have to manually select the widget code, but sometime the code would be very long even I need scroll. It is very easy to select wrong code range. I think this extension can exact widget, so it must be had ability to know the range of widget which current cursor related to. As issue tile says, it would be very helpful to provider a command to select widget code.

Thanks for making this wonderful extension!

**Comment by DanTup** [comment]
Sorry for the delay in responding to this, I somehow overlooked it.

The Extract Widget functionality comes from the Dart SDK, so improving this would need to be handled there - please file the issue at https://github.com/dart-lang/sdk. Thanks!

**Comment by DanTup** [comment]
I misread the request - it was really for expanding the range. There's actually already a command that will do this, but it's only recently been implemented so may not work for you yet:

https://github.com/Dart-Code/Dart-Code/issues/3332

The command is VS Code's "expand selection", and if you press it repeatedly, it will select more and more of the code using the AST.

[The change](https://github.com/dart-lang/sdk/commit/cc670855010ac17d246980eb3544e3fee3c63270) is in the Dart analysis server, which means it will show up in a future SDK release. If you want to test it out now, it's available on the Flutter master branch, but you'd need to ensure the `dart.previewLsp` setting is `true`.

(note: the command will still work on older versions of Flutter, but it will not work as reliably without that change).
