### ISSUE TITLE
Add a command to "add package" that alls "pub add"

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#3306]
Pub has both a command for adding new packages, and an API to get all package names for completion. With these, we could add a command palette command to add packages that would avoid having to modify the pubspec directly.

In the past, some issues have been reported that turned out to be subtly-incorrect indentation in pubspec, so handing off the editing to Pub for simple tasks like this might save some of those.

**Comment by tjx666** [comment]
It would be better to override [pubspec-assist](https://github.com/jeroen-meijer/pubspec-assist) features.

**Comment by DanTup** [comment]
I'm not sure what you mean by "override". I don't think it makes sense to interfere with another extensions commands (especially when they're prefixed with the name of the extension). There may be some overlap with this, but it also supports things that might not be added here (for example multiple packages in one go, and sorting the file).

I hope for implementation here to show the list of packages, filtered as you type. It may also be possible to get the descriptions, although https://github.com/microsoft/vscode/issues/75005 might interfere a little with that.
