### ISSUE TITLE
Global evaluation requires a thread to have been loaded

### ISSUE THREAD

**Issue by Aaronn8** [Dart-Code/Dart-Code#3307]
Hi I have been trying to weeks to get this simple readLineSync function to work. 

I keep keep the same error: Global evaluation requires a thread to have been loaded

Future<void> main() async {
  print('please enter a name?');
  // ignore: unused_local_variable
  const String personname = 'Aaron';
  // final String str = personname;

  print('hello $personname');
  print('hello $personname Enter a color');
  //String color = prompt('Enter a color: ');//

  final String color = stdin.readLineSync()!;
  print(color);
  print('So you like the color $color?');
  // ignore: void_checks

  //print('Your colour is, $answer2');//
}

Terminal:
please enter a name?
hello Aaron
hello Aaron Enter a color
blue
Global evaluation requires a thread to have been loaded

Please can I get some assistance. I tried to google it but I cant find any resolution to this. 

Any help will be appreciated.

**Comment by DanTup** [comment]
If you need to read from `stdin`, you'll need to configure your app to run in the Terminal. By default the app runs in a process inside the debug adapter and the Debug Console is intended to be used for evaluating expressions.

Instructions on configuring to run in the terminal can be found here:

https://dartcode.org/docs/running-in-terminal/

If you have any issues getting this to work, please let me know!
