### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by jarsoftSolutions** [Dart-Code/Dart-Code#3309]
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `3.21.1`
- OS Version: `Windows_NT x64 10.0.19041`
- VS Code version: `1.55.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\DELL\AppData\Local\Temp\Dart-Code.dart-code-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by DanTup** [comment]
> ⚠️ Make sure to attach this file from your home-directory:
> ⚠️c:\Users\DELL\AppData\Local\Temp\Dart-Code.dart-code-unresponsive.cpuprofile.txt

Are you able to provide the referenced file? Thanks!
