### ISSUE TITLE
dart extension doesn't respect vscode editor.formatOnSave value

### ISSUE THREAD

**Issue by ebadta81** [Dart-Code/Dart-Code#3310]
**Describe the bug**
I have my "editor.formatOnSave": false, but dart.enableSdkFormatter doesn't respect it. If dart.enableSdkFormatter is true, it formats the documents on save even when editor.formatOnSave is false.
If I disable dart.enableSdkFormatter, the document doesn't get reformatted at save.

**Expected behavior**
I expect, that this extension "Support for format-on-save (editor.formatOnSave)", so if I set  editor.formatOnSave to false it doesn't auto format the document at save. I don't even have a workaround for this, because if I disable dart.enableSdkFormatter I cannot format dart files with the format document command.

**Versions (please complete the following information):**
 - VS Code version: 1.55.2
 - Dart extension version: 2.12.3
 - Dart/Flutter SDK version: 2.0.5
 -  OS: MacOs 11.2.3

**Comment by DanTup** [comment]
My guess is that you're previously applied the [recommended settings](https://dartcode.org/docs/recommended-settings/) which enables `formatOnSave` for Dart specifically, but you're just disabling the default (which does not affect if it's overridden for a specific language). There's an open issue in VS Code to make language-specific settings clearer at https://github.com/microsoft/vscode/issues/74195.

You should be able to fix this by:

- Run the **Preferences: Configure Language Specific Settings** command in VS Code
- Select **Dart**

This should open the JSON, and you'll likely find a `["dart"]` section that has some additional settings that will override the general defaults. Removing `formatOnSave` from there should solve the issue. If not, please let me know!

**Comment by ebadta81** [comment]
I could only get this settings through command palette.

I got this json:

	"[dart]": {
	"editor.formatOnSaveMode": "modifications",
		"editor.formatOnSave": false,
		"editor.formatOnType": true,
		"editor.rulers": [
			80
		],
		"editor.selectionHighlight": false,
		"editor.suggest.snippetsPreventQuickSuggestions": false,
		"editor.suggestSelection": "first",
		"editor.tabCompletion": "onlySnippets",
		"editor.wordBasedSuggestions": false
	},

Now it works as I expected.

Thank You for your help!

**Comment by DanTup** [comment]
Great, glad it was something that didn't mean waiting for a fix/release!

Another way to get it is opening the user settings and then clicking the icon in the top right corner to go to the JSON view, and this should be in that file somewhere.
