### ISSUE TITLE
Allow to easily overwrite the launch config that is used when tests are run in the test folder

### ISSUE THREAD

**Issue by escamoteur** [Dart-Code/Dart-Code#3311]
![image](https://user-images.githubusercontent.com/16635729/116606076-7f0cc600-a930-11eb-9ded-8a0d5cc31d4c.png)

**Comment by DanTup** [comment]
With these changes, you can use "Run" or "Debug" as the title for a CodeLens template (or `${debugType}` which will be set depending on the matched template type) and it will hide the built-in Run/Debug CodeLens.

Here's an example that matches all templates (so will appear for `main` functions on both scripts and tests, and on test/groups functions) that sets an env variable:

```js
{
	"name": "env_foo2",
	"request": "launch",
	"type": "dart",
	"codeLens": {
		"for": [ // Match all templates
			"run-test",
			"run-test-file",
			"run-file",
			"debug-test",
			"debug-test-file",
			"debug-file",
		],
		"title": "${debugType}", // Sets the title to just "Run" or "Debug" depending on which template (above) it matched
	},
	"env": {
		"DANNY": "foo2", // Custom settings can be args, env, etc.
	}
},
```

**Comment by escamoteur** [comment]
awesome!!!

**Comment by DanTup** [comment]
There's a beta version with this change in if you'd like to test it out before release:

https://github.com/Dart-Code/Dart-Code/releases/tag/v3.23.0-beta.1

If anyone doesn't work as expected, please let me know!

**Comment by DanTup** [comment]
> If anyone doesn't work as expected

😬
