### ISSUE TITLE
hide debug toolbar when run code

### ISSUE THREAD

**Issue by tjx666** [Dart-Code/Dart-Code#3312]
The toolbar should only be shown when debug, and hide when run.

![image](https://user-images.githubusercontent.com/41773861/116788924-d5b80280-aade-11eb-871b-66e2af53f917.png)

**Comment by DanTup** [comment]
This was done deliberately, as it allows restarting/terminating the process. It's not the case if you run in the terminal though, as we don't control the process.

If I remember correctly, some of the other languages I tested like TS worked this way.

Is there a reason you think it would be better not to work this way? Thanks!

**Comment by tjx666** [comment]
Ok, It may useful when accessing user input but you may want to terminate it. What about provider user an option to set run code in terminal?

em..., I think user may using the tooltip rarely, we can hide the tooltip but provide a command to pause or terminate like extension [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner). In

In fact, I'm not very care about this issue because I use code runner to execute the  dart code normally. I just feel a little annoy to the tooltip when I just want to run some code.

**Comment by DanTup** [comment]
@tjx666 there's already an option to run in the terminal if you'd prefer that (or need to access stdin):

https://dartcode.org/docs/running-in-terminal/

I'm unsure how that relates to the debug toolbar though (note if you "run" in the terminal, the debug toolbar will disappear immediately, as we have no control over the lifetime of the process in the terminal).

If you think the toolbar should be hidden when _not_ running in the terminal, please can you explain the advantage of this, as it seems to me that it's likely only a cosmetic advantage, but comes with drawbacks (not being able to terminate).

Thanks!
