### ISSUE TITLE
Deleting a file leaves old errors in problem window.

### ISSUE THREAD

**Issue by bsutton** [Dart-Code/Dart-Code#3317]
How to reproduce:

Create a dart library
Add some dart code that includes a compile error.
```
import 'package:test/test.dart';

void main() {
  test('release ...', () async {
    bad thing ehere
  });
}
```

Delete the dart library

The problem window retains the error.

The only way to get rid of the error is to restart vs-code.

Dart-code: v3.21.1

```
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:37:02.931Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.8.0-50-generic snap
```

**Comment by DanTup** [comment]
I'm not able to reproduce this - can you confirm a few things:

- What OS you're seeing this on?
- What version of the SDK are you using (shown in the bottom right status bar)
- Whether you're using LSP (hover over the SDK version in the status bar and see whether the tooltip says "DAS" or "LSP".. if you've not explicitly set this in settings, it could still be either as the default is currently assigned randomly as part of a progressive rollout)

It could also be useful to get an [analysis server instrumentation log](https://dartcode.org/docs/logging/#analyzer-instrumentation) if you can repro this in a small sample (please do this with LSP enabled).

Thanks

**Comment by bsutton** [comment]
I'm running  Ubuntu 20.10
Dart 2.12.14
LSP

Log demonstrating attached.

[dart.analyzerInstrumentationLogFile.txt](https://github.com/Dart-Code/Dart-Code/files/6430891/dart.analyzerInstrumentationLogFile.txt)

**Comment by bsutton** [comment]
I should not that this is hard to reproduce consistently.

**Comment by bsutton** [comment]
hmm, I'm not certain the above analysis file is valid as after I restart code again the file was back.

I"ve not seen this behaviour before and now I can't reproduce the problem.

One thing I will not is that the delete operation says it can't delete to trash so then asks if I want to permanently delete the file.
