### ISSUE TITLE
Observatory connection becomes unresponsive when debugging Flutter apps

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#332]
Since there isn't currently a specific case about this, here's somewhere to keep notes.

When debugging flutter apps, something seems to happen to Observatory (or the connection to it) and it becomes unresponsive. In my testing it seems to happen a few seconds after the app launches; so I can hit a breakpoint and if I hit Step quickly, it will step, however it quickly then becomes unresponsive. Others have reported not being able to hit breakpoints at all (likely this is the same issue with different timing).

Related flutter case: https://github.com/flutter/flutter/issues/10615
Also some info in: https://github.com/Dart-Code/Dart-Code/issues/318

Since this hasn't been repro'd outside of Dart Code the next step is probably to try and write a simple npm script that mimics what Dart Code is doing and see if it happens. If not, we'll need to figure out exactly what's different and if so, it should give a simpler repro to debug further.

**Comment by DanTup** [comment]
From @Skylled:

> I can only seem to get it to repro on early breakpoints. Anything after the initial runApp seems to break correctly.

So if you don't hit a breakpoint really early on, it works as expected? I was expecting the opposite - I figured early breakpoints worked and then after some time it "breaks"

> Yeah, I had a breakpoint in stocks/main.dart at line 68, the standard case for the switch. Putting the breakpoint at 72, which can only happen after initial runApp, it works repeatedly without failure. Unless the observatory disconnect happens after more than a few minutes.

**Comment by DanTup** [comment]
I can repro this behaviour using the lines above. So it seems to only occur if we hit a breakpoint within a short window after launching the app.

**Comment by DanTup** [comment]
I've removed almost all code that sends stuff to Observatory and can still repro this :(

[observatory.txt](https://github.com/Dart-Code/Dart-Code/files/1095555/observatory.txt)

**Comment by DanTup** [comment]
And an even shorter repro..

[observatory.txt](https://github.com/Dart-Code/Dart-Code/files/1095571/observatory.txt)

This is small enough that hopefully won't be hard to extract into a simple script.

**Comment by DanTup** [comment]
I created a script that mimics what Dart Code does and it behaves differently again - the breakpoint never resolves (and therefore never gets hit) despite the logs being identical (except for IDs etc.) >:O(

![Log](https://user-images.githubusercontent.com/1078012/27451760-2613044a-5788-11e7-81d5-25cac4d5df0b.png)

**Comment by DanTup** [comment]
Ok, I can perfectly reproduce this in a script without Dart Code. I send a `Step over` 300ms after every time we pause and it just fails to get responses after a certain amount of time (if I reduce the `300ms` there will be more successful steps before it hangs).

![Repro](https://user-images.githubusercontent.com/1078012/27452372-3ef09de0-578a-11e7-9915-dc179822fdcc.png)

[main.ts](https://github.com/Dart-Code/Dart-Code/files/1095951/main.ts.txt)

I don't think I can progress this any more; if I'm doing something wrong then I need some assistance in knowing what.

**Comment by pulyaevskiy** [comment]
If you can compile and push that script on Github with instructions I can try and run it on my machine (macOS).

Found this: https://github.com/dart-lang/sdk/issues/29568 not sure if relevant, but symptoms look similar:

> So it seems that it gets stuck after approximately 7 and a half seconds, after which is does nothing.

Can also try and summon @devoncarew for help. :)

**Comment by DanTup** [comment]
> So it seems that it gets stuck after approximately 7 and a half seconds, after which is does nothing.

Well that does indeed sounds incredibly similar. I've added some comments linking back here. I wish I'd found that case a fortnight ago! ;-(

**Comment by DanTup** [comment]
@pulyaevskiy 

> If you can compile and push that script on Github with instructions I can try and run it on my machine (macOS).

[Here](https://github.com/Dart-Code/Dart-Code/files/1096063/main.js.txt) is the compiled JS version. You'll need to tweak the paths on line 15 and then just run with `node main.js`. I commented out spitting `flutter run` output to screen to just show Observatory stuff, so it might look like it's doing nothing for a while (while it's compiling, etc.).

If all goes well, you'll see it stepping through a lot of code. If it does what mine does, you'll get one or two steps and then no response to the step command (`==>` are commands being sent to Observatory and it shuld send replies logged with `<==`).

**Comment by DanTup** [comment]
Hmmm, that linked case isn't flutter specific. I was sure when I tested this in a Dart program it always worked fine and I'm only seeing this in Flutter? :/

**Comment by pulyaevskiy** [comment]
It gets stuck for me on the first breakpoint:

```
⋊> ~/P/t/vscode node main.js                                                                                                                                                                     
Press <ENTER> to quit
Connecting to observatory...
==> {"id":"0","method":"streamListen","params":{"streamId":"Debug"}}

==> {"id":"1","method":"getVM"}

<== {"jsonrpc":"2.0","id":"0","result":{"type":"Success"}}
<== {"jsonrpc":"2.0", "result":{"type":"VM","name":"vm","architectureBits"...
==> {"id":"2","method":"getIsolate","params":{"isolateId":"isolates/470669...

<== {"jsonrpc":"2.0", "result":{"type":"Isolate","fixedId":true,"id":"isol...
==> {"id":"3","method":"addBreakpointWithScriptUri","params":{"isolateId":...

<== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug",...
<== {"jsonrpc":"2.0", "result":{"type":"Breakpoint","fixedId":true,"id":"b...
==> {"id":"4","method":"resume","params":{"isolateId":"isolates/470669847"...

<== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug",...
<== {"jsonrpc":"2.0", "result":{"type":"Success"},"id":"4"}
<== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug",...
<== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug",...
### STOPPED AT BREAKPOINT...
### SENDING RESUME...
==> {"id":"5","method":"resume","params":{"isolateId":"isolates/470669847"...
```

Tried a few times.
Changing timeout to 500 msecs results in failure to connect or even start the app for some reason.

**Comment by DanTup** [comment]
Google have been able to repro this with my script now (https://github.com/flutter/flutter/issues/10615#issuecomment-310517129). Sounds like I'm connecting to Observatory too early. I thought I'd tried changing these events but I'll check again since I was trying so many things I might've done something wrong.

I still think this behaviour is a nasty bug (it works, then becomes broken, which is not the expected behaviour from connecting to something too early) but if the fix works that's all I care about for now!

**Comment by DanTup** [comment]
Fixed by not connecting so early.
