### ISSUE TITLE
[LSP] Escaped characters in strings are not highlighted anymore

### ISSUE THREAD

**Issue by acoutts** [Dart-Code/Dart-Code#3329]
**Describe the bug**
Previously, escaped characters within strings were highlighted in a different color (I believe light yellow), to make them more obvious. But after activating LSP this doesn't seem to happen anymore.

**To Reproduce**
```dart
final str = 'this string \nhas an escaped character in it';
```

**Expected behavior**
Escaped characters should be more visible.

**Screenshots**
<img width="200" alt="Screen Shot 2021-05-08 at 8 41 41 AM" src="https://user-images.githubusercontent.com/9597207/117539577-4f695800-afd9-11eb-933b-e7986c657ab4.png">

**Versions (please complete the following information):**
 - VS Code version:
```
1.57.0-insider
Commit: b95b73b7b074f5dddccd57e5e290617f1a767ec1
```
 - Dart extension version: `3.22.0`
 - Dart/Flutter SDK version:
```
Flutter 2.3.0-0.1.pre • channel unknown • unknown source
Framework • revision d72bfb8d07 (12 days ago) • 2021-04-26 06:05:55 -0700
Engine • revision de6e1adf97
Tools • Dart 2.14.0 (build 2.14.0-18.0.dev)
```

**Comment by bwilkerson** [comment]
Yes. Given a `SimpleStringLiteral` named `string`
- The expression `string.value` will return the content of the string with delimiters removed and escapes converted to their actual character values.
- The expression `string.literal.lexeme` will return the unprocessed string literal including delimiters and the raw string marker (`r`) if there is one.

If you want to find escape sequences yourself you'll need to use the second expression and duplicate some of the logic from `pkg/_fe_analyzer_shared/lib/src/parser/quote.dart:136`.

**Comment by DanTup** [comment]
Perfect, thanks! I've had a go at this at https://dart-review.googlesource.com/c/sdk/+/199483 (the parser code didn't seem directly reusable, although the rules seemed pretty simple).

**Comment by DanTup** [comment]
This is fixed, but will require both an updated SDK and updated Dart-Code to apply (server changes mark the escape characters and Dart-Code maps it to the textmate `constant.character.escape` to get the colour from the theme - though you could set this manually in your settings too).

The original version was actually very naive and didn't consider hex/unicode characters correctly, it always just highlighted one character:

![Screenshot 2021-05-13 at 10 04 46](https://user-images.githubusercontent.com/1078012/118104274-d7cd6b80-b3d2-11eb-9d9b-e85991293461.png)

The new one should behave correctly for `\x` and `\u`.

![Screenshot 2021-05-13 at 10 04 52](https://user-images.githubusercontent.com/1078012/118104292-dac85c00-b3d2-11eb-8ccb-5f16ce18251a.png)

(the misplaced squiggles are unrelated - I've filed that at https://github.com/dart-lang/sdk/issues/46005).
