### ISSUE TITLE
Better support for smart selection

### ISSUE THREAD

**Issue by Andreigr0** [Dart-Code/Dart-Code#3332]
When expanding selection with hotkeys it jumps from parenthesises straight to argument name ignoring a class name such as `Column`, `Center`, `Scaffold` while in IntelliJ/Android Studio selection behavior is proper 

<details>
<summary>VSCode</summary>

https://user-images.githubusercontent.com/44437712/117549881-90975180-b045-11eb-8399-84888c8fddb2.mov

</details>

<details>
<summary>Intellij</summary>

https://user-images.githubusercontent.com/44437712/117549798-11098280-b045-11eb-9f2f-6e83118cb0dc.mov

</details>

**Comment by DanTup** [comment]
Thanks for the suggestion! I think this should be possible to implement using LSP's `textDocument/selectionRange`. https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_selectionRange and something on the server that uses the parsed AST.

**Comment by DanTup** [comment]
This is now supported by the LSP server with:

https://github.com/dart-lang/sdk/commit/cc670855010ac17d246980eb3544e3fee3c63270

The change is in the server, so will show up with a future Dart/Flutter release.

**Comment by harkairt** [comment]
long awaited, thank you!! <3
