### ISSUE TITLE
Print statements not showing in debug console

### ISSUE THREAD

**Issue by shane99a** [Dart-Code/Dart-Code#3333]
**Describe the bug**
Print statements not showing in debug console. It used to work but not sure what changed recently. However if I run `flutter logs`, then in that command I do see the print statements showing up.

**To Reproduce**
1. add print statements, for example: `print('Error: $e, $trace');`
2. run app in vscode debugger
3. should not see the print statements

**Expected behavior**
Should see the print statements

**Screenshots**

![image](https://user-images.githubusercontent.com/5408993/117727375-f0146f00-b1b5-11eb-8fbe-551b4d6bae58.png)

**Versions (please complete the following information):**
 - VS Code version: 1.56.0
 - Dart extension version: 3.22.0
 - Dart/Flutter SDK version: 2.0.6

**Comment by DanTup** [comment]
@shane99a did you figure out what this was? It may be useful to note what it was here in case anyone else has the same issue and searches/finds this one. Thanks!
