### ISSUE TITLE
Support activating for workspaces that include virtual folders (like LiveShare) (virtual workspaces will have limited functionality)

### ISSUE THREAD

**Issue by ranjithrd** [Dart-Code/Dart-Code#3340]
Hello!

**Describe the bug**
I've been using this extension in conjunction with VSCode's Liveshare feature. Everything was working fine until a few days ago, since which time this extension does simply not work. I don't see any code highlighting, everything's just grey. I can't do any code navigation, nor can I even use a simple `cmd + /`. Quaintly enough, VSCode live share works perfectly for shared YAML or JSON files. 
On the host's computer, all highlighting works perfectly, but on another editor's computer, the Dart extension simply doesn't work. It displays an error; "This plugin doesn't support virtual workspaces." I commented on the issue regarding support for virtual workspaces, and a maintainer requested me to file a separate issue. 

**To Reproduce**
1. Install the LiveShare extension pack
2. Start a session
3. Join the session from another computer
4. Open any shared `.dart` file. 
5. See error

**Expected behavior**
Code highlighting, code navigation, general working of an extension.

**Screenshots**
![Screenshot 2021-05-13 at 7 35 13 PM](https://user-images.githubusercontent.com/32879598/118137025-5ac9e280-b422-11eb-97de-00e7b6f9877e.png)

**Versions (please complete the following information):**
 - VS Code version: v1.56
 - Dart extension version: v3.22.0
 - Dart/Flutter SDK version: Channel stable, 2.0.4, `>=2.7.0 <3.0.0` in `pubspec.yaml`. Not converted to `null-safe` yet because packages don't support it.

Thank you so much in advance.

**Comment by DanTup** [comment]
I suspect this is a result of VS Code blacklisting many extensions from workspaces with virtual folders by default in the most recent relese:

https://github.com/microsoft/vscode/wiki/Virtual-Workspaces

> Until extensions have adopted the new capability, we came up with an internal list of extensions that we think should be disabled in virtual workspaces. The list can be found [here](https://github.com/microsoft/vscode/issues/122836).

Although there are no immediate plans to support virtual workspaces, we should be able to activate the extension and work for the non-virtual folders in the workspace at least (which would also allow the textmate grammar to be loaded).

**Comment by DanTup** [comment]
I've pushed a fix that will allow the extension to _activate_ in virtual workspaces, although this does not add language support for it. Basic things like syntax highlighting will work.

#3327 is open for investigating better support for virtual workspaces, although it's not clear whether that will be feasible (or if so, to what extend) yet.

**Comment by ranjithrd** [comment]
Thanks a ton, @DanTup ! Just confirming that this will be out on Jun 1 with v3.23.0 right?

**Comment by DanTup** [comment]
Not set in stone, but it _should_ be in the next release somewhere around then. There will likely be a beta release a little in advance if you'd like it sooner.

To re-iterate, this only allows the extension to _activate_, which will fix things like the textmate grammar (syntax highlighting) not being loaded. It doesn't add Dart-language support for virtual workspaces - however with LiveShare they should be proxied over to the host, so you should still see language functionality (though I would also expect that today even without this fix).

**Comment by ranjithrd** [comment]
Alright. Thank you so much for all your help!

**Comment by DanTup** [comment]
There's a beta version here if you'd like to test it out early:

https://github.com/Dart-Code/Dart-Code/releases/tag/v3.23.0-beta.1

If it doesn't work as expected, please let me know so I can fix before release. Thanks!
