### ISSUE TITLE
Breakpoint on libraries not working

### ISSUE THREAD

**Issue by amr-eniou-3r** [Dart-Code/Dart-Code#3349]
**Is your feature request related to a problem? Please describe.**
While working on a Flutter project with several dependencies, I can't add a breakpoint for the dependency project in a different window so I have to add it to the window in which I run the project.
 
**Describe the solution you'd like**
I would like to search for classes on the dependencies and want to show code errors while editing the dependencies.
 
**Describe alternatives you've considered**
Allow breakpoint on a different window than the window in which I run the project.

**Comment by DanTup** [comment]
By "different window" here do you mean a separate VS Code window? If so, that's not possible - VS Code windows are completely seperate processes so the extension in one is isolated from the extension in another.

I'd recommend against using multiple VS Code windows when working on dependent projects (until VS Code gets real multi-window support) as this will result in multiple extensions and multiple language servers being spawned, which will result in higher resource usage (all files will be analyzed twice) and could result in conflicting state if modifying files.

You can add multiple folders to the same VS Code window by clicking File -> Add Folder to Workspace to add more after opening the initial folder.

**Comment by amr-eniou-3r** [comment]
@DanTup Awesome breakpoints, autocomplete and search for classes all works fine on workspaces
Thanks a lot

**Comment by DanTup** [comment]
Great! This is the recommend way to work, so if you find issues you think are a result of using multi-folder workspaces, please do file issues for them. Thanks!

**Comment by amr-eniou-3r** [comment]
@DanTup In workspace indexing is slow, is there a way to increase indexing speed?

**Comment by DanTup** [comment]
Can you be more specific about what you mean by "indexing"? Do you mean when you see "Analyzing..." in the status bar? If so, how long do you see it taking, and how big is the folde ryou have open in VS Code?

**Comment by amr-eniou-3r** [comment]
@DanTup I mean autocomplete or navigate to a specific class reference
sometimes it is stucking. and I have to reopen my vscode

**Comment by DanTup** [comment]
@amr-eniou-3r can you file a new issue with a detailed description of what you're seeing? Please also include your OS, and versions of the Dart/Flutter SDK. Thanks!
