### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by RasyidMF** [Dart-Code/Dart-Code#3350]
- Issue Type: `Bug`
- Extension Name: `dart-code`
- Extension Version: `3.22.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.56.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 535,
		"activateCallTime": 396,
		"activateResolvedTime": 31181,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "Dart-Code.dart-code",
				"_lower": "dart-code.dart-code"
			},
			"activationEvent": "onLanguage:dart"
		}
	},
	"runtimeErrors": []
}
```

**Comment by DanTup** [comment]
> ⚠️ We have written the needed data into your clipboard. Please paste! ⚠️

Was there more information not included in this report? It's not very clear from this what the issue was.

**Comment by RasyidMF** [comment]
Nvm, I fixed it myself by restarting vscode. It happen when my pc having 100% disk usage
