### ISSUE TITLE
serviceInfoFile doesn't seem to work for custom flutter embedders

### ISSUE THREAD

**Issue by knopp** [Dart-Code/Dart-Code#3353]
My flutter application writes a service info file, but when I specify it in the launcher configuration Dart-Code doesn't poll for it.

vmServiceUri with prompt works as expected, but it's not ideal to have to copy and paste the URI on every launch.

 - Dart extension version: dart 3.22.0
 - Dart/Flutter SDK version: current master

**Comment by knopp** [comment]
The application is not built through the `flutter` tool so I can't run it using `flutter run`. `flutter attach` works, but I need to specify `vmServiceUri` on every launch. 

(down the line it would also be nice to have option for Dart-Code to invoke custom executable with --write-service-info), but for now at least `serviceInfoFile` working would be a big quality of life improvement.

**Comment by DanTup** [comment]
> down the line it would also be nice to have option for Dart-Code to launch a custom executable with --write-service-info

You might be able to do this with a `preLaunchTask` (eg. cause the debug config to run a background task that spawns the app before it tries to debug) or a compound config (one that runs a Dart script that sets up the file and spawns your process) - I don't know how messy that would be though.

There is also some support for overriding the Flutter/Dart binaries, but it's aimed at some specific Bazel workspace setups so not something official supported for this, but may be another option to improve things until/unless something better is available:

https://github.com/Dart-Code/Dart-Code/blob/195b1c6462958785bed149a0d3897c737ed93a70/src/shared/utils/workspace.ts#L57-L69

As for the original case - looking at `FlutterDebugSession`, `attachRequest` calls `launchRequest` which calls into `DartDebugSession.launchRequest` so I don't think it should be complicated to fix this - I suspect there are just some bad assumptions somewhere.

**Comment by DanTup** [comment]
Although this works in my testing with simple Flutter, it's not working for @knopp:

```
[1:28:22 PM] [FlutterRun] [Info] [Flutter: Attach to Process] Spawning flutter with args ["attach","--machine","-d","macos","--debug-uri","ws://127.0.0.1:60238/40DHMrlkLa0=/ws","--devtools-server-address","http://127.0.0.1:9100/","-v"]

[ +104 ms] Exception attempting to connect to the VM Service: WebSocketException: Connection to 'http://127.0.0.1:60238/40DHMrlkLa0=/ws/ws#' was not upgraded to websocket
```

The `/ws/ws` looks suspicious - though it's interesting I'm not seeing that (I did see the URL mangled in a different way though, it ended up with `.,/ws` on the end - but it still worked). Perhaps something changed in Flutter (I'm on `master`).
