### ISSUE TITLE
Add debug support for ffi

### ISSUE THREAD

**Issue by bsutton** [Dart-Code/Dart-Code#3360]
I'm writing dart code which calls into the windows registry via calls such as RegGetValue. using ffi.

In order to do this I need to calloc memory and copy values into that memory.

When debugging the code vscode only shows the address of the calloc memroy.

It would be really useful if you could examine the memory so that I can check that I've correctly copied values
into memory or the contents of memory after an ffi call returns.

Ideally this would use the type of the variable to determine how to display the memory (e.g. utf16 vs int16)
It would also be useful if the debugger recognized declared structs so memory could be examined through the lens of the struct.
It would also be useful to be able to select the type used to decode the memory.
An example is that you often calloc memory as utf16 but then convert it to Uint16.
So ideally you want to be able to switch the memory decoder used.

**Comment by DanTup** [comment]
@bkonyi does the VM Service have support anything like this?

**Comment by bkonyi** [comment]
No it doesn't, but it seems like a reasonable request. This should be filed as an issue in the SDK repo and we should bring Daco into the loop.

**Comment by DanTup** [comment]
@bsutton could you file at https://github.com/dart-lang/sdk (and CC dcharkes)? Thanks!

**Comment by DanTup** [comment]
I'll close this on the assumption that if done in the VM/VM Service it would just work here, but we can re-open if that turns out not to be the case and there are new APIs to use (although even in that case it might end up being DAP work in the SDK depending on timeframes).
