### ISSUE TITLE
Factory method's token colour is broken with LSP

### ISSUE THREAD

**Issue by robertpiosik** [Dart-Code/Dart-Code#3374]
**Describe the bug**
Factory method's token colour is broken with LSP.

**To Reproduce**
Use the default theme, enable LSP.

**Expected behavior**
Factory method token should be painted with a colour of a standard method.

**Screenshots**
LSP:
![image](https://user-images.githubusercontent.com/7120725/120309144-3486bc80-c2d5-11eb-8cd2-bd3124acd55d.png)
Without LSP:
![image](https://user-images.githubusercontent.com/7120725/120309261-541de500-c2d5-11eb-9fc1-af33a8c691b3.png)

With LSP:
![image](https://user-images.githubusercontent.com/7120725/120309458-8cbdbe80-c2d5-11eb-843b-fa6327cc9747.png)
Without LSP:
![image](https://user-images.githubusercontent.com/7120725/120309500-97785380-c2d5-11eb-883b-bb5e5451dd5f.png)

Here is how GitHub colours these tokens:

```dart
@freezed
abstract class NoteFormEvent with _$NoteFormEvent {
  const factory NoteFormEvent.initialized(Option<Note> initialNoteOption) =
      _Initialized;
  const factory NoteFormEvent.bodyChanged(String bodyStr) = _BodyChanged;
  const factory NoteFormEvent.colorChanged(Color color) = _ColorChanged;
  const factory NoteFormEvent.todosChanged(KtList<TodoItemPrimitive> todos) =
      _TodosChanged;
  const factory NoteFormEvent.saved() = _Saved;
}
```

```dart
@injectable
class AuthBloc extends Bloc<AuthEvent, AuthState> {
  final IAuthFacade _authFacade;

  AuthBloc(
    this._authFacade,
  ) : super(const AuthState.initial());

  @override
  Stream<AuthState> mapEventToState(
    AuthEvent event,
  ) async* {
    yield* event.map(
      authCheckRequested: (e) async* {
        final userOption = _authFacade.getSignedUser();
        yield userOption.fold(
          () => const AuthState.unauthenticated(),
          (_) => const AuthState.authenticated(),
        );
      },
      signedOut: (e) async* {
        await _authFacade.signOut();
        yield const AuthState.unauthenticated();
      },
    );
  }
}
```

**Versions (please complete the following information):**
 - VS Code version: 1.56.2 (Universal)
 - Dart extension version: 3.22.0
 - Dart/Flutter SDK version: 2.13.0 (stable)

**Comment by DanTup** [comment]
I've got a fix for review at https://dart-review.googlesource.com/c/sdk/+/201831/ that will map constructor names like methods instead of classes:

<img width="821" alt="Screenshot 2021-06-01 at 13 00 43" src="https://user-images.githubusercontent.com/1078012/120319939-77e32a00-c2d9-11eb-8423-4a491757760d.png">

They're also tagged with a custom modifier (`constructor`) to allow customising them different to standard methods if desired.

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/10b83a48827429f30f8848e19ba46e528128818a. Since the change is in the server, it will show up in a future SDK release rather than a Dart-Code release.
