### ISSUE TITLE
IconData preview issue in VSCode

### ISSUE THREAD

**Issue by srinivas-iosdev** [Dart-Code/Dart-Code#3376]
<img width="433" alt="Screenshot 2021-06-01 at 9 30 57 PM" src="https://user-images.githubusercontent.com/76642381/120355128-a9331880-c320-11eb-8da4-2421a64aaba0.png">

Failed to load the Icons preview in VSCode.
Im using the following versions:
1. VSode (v1.56.2)
2. Dart extension (v3.22.0)
3. Flutter extension(v3.22.0)

**Comment by DanTup** [comment]
Thanks for the report! These are new icons that were not included in the previous release. They've been updated recently (https://github.com/Dart-Code/Icons/commit/1321ec33943409df436bfea15af3fded29dcd8d7) so the upcoming release of v3.23.0 will resolve this:

<img width="389" alt="Screenshot 2021-06-01 at 17 38 58" src="https://user-images.githubusercontent.com/1078012/120360073-43cf2f80-c300-11eb-8b4d-fb771093bb83.png">

**Comment by MuhammadUmair786** [comment]
Still i am facing this issue ... ?

**Comment by DanTup** [comment]
@MuhammadUmair786 Please see [the pinned issue](https://github.com/Dart-Code/Dart-Code/issues/3470) about this - it appears to be [a VS Code bug](https://github.com/microsoft/vscode/issues/119786) and unfortunately I've not been able to find a workaround. Please add 👍  to the VS Code issue. Thanks!
