### ISSUE TITLE
VS Code shows errors on import statements in Flutter project

### ISSUE THREAD

**Issue by JoelDjilo** [Dart-Code/Dart-Code#3380]
Bonjour, besoin de vos conseils.
Je suis encore débutant en codage flutter sur VS code
J'ai monté une page d'accueil avec l'outil Flutterflow avec les bouttons de connexion et d'inscription mais le soucis est le suivant:
le code (Dart) qui a été généré à la fin du montage, lorsque je l'importe sur VS code pour pouvoir continuer le taf, les lignes d'importations de méthodes sont highlighted (l'image en dessous).
Quand je navigue dessus, il y a ce message qui s'affiche "_Target of URI doesn't exist: '../flutter_flow/flutter_flow_theme.dart'.
Try creating the file referenced by the URI, or Try using a URI for a file that does exist.darturi_does_not_exist) "_.
j'aimerai savoir comment résoudre ce pb.
j'ai fait des recherches sur ce message en particulier sur le mot URI, j'avoue que je ne comprend rien mais il y a les expressions  "fluttter packages get"; "pub.dev" qui reviennent toujours mais je ne comprends pas.
I need your advices pleases.
![● accueil dart - easytrip - Visual Studio Code 03_06_2021 13_32_52](https://user-images.githubusercontent.com/74889535/120646157-253c7600-c471-11eb-864d-41fc5a3a0cdc.png)

**Comment by DanTup** [comment]
Hi!

These lines appear incorrect:

```
import '../flutter_flow/flutter_flow_theme.dart';
import '../flutter_flow/flutter_flow_widgets.dart';
```

The path (`"../flutter_flow/flutter_flow_theme.dart`") will be resolve relative to the current file (`"lib/accueil.dart"`), so it is looking for the file at `"easytrip/flutter_flow/flutter_flow_xxx.dart"` but it does not look like those files exist. It's not clear to me where the `flutter_flow` files are supposed to come from?

The other issues (on `"package:font_awesome_flutter"` and `"package:google_fonts"`) may be that you have not added those packages to the `dependencies` section of your `pubspec.yaml` (see https://dart.dev/tools/pub/pubspec#dependencies), or you have not run the **Flutter: Get Packages** command in VS Code to fetch those packages yet.

Hope this helps!

**Comment by JoelDjilo** [comment]
J'ai réussi à installer les packages nécessaires pour  " google_fonts et " font_awesome_flutter " mais je fais toujours des recherches pour flutter flow
Merci @DanTup

**Comment by DanTup** [comment]
I'm not familiar with what `flutter_flow` is. As far as I can see, those `import` lines are invalid as you do not have files in a folder named `flutter_flow`. If you copied this code from somewhere, you may be missing some additional files (as far as I can tell, there is now `flutter_flow` package on Pub).
