### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by ShreyasBhaktharam** [Dart-Code/Dart-Code#3382]
- Issue Type: `Bug`
- Extension Name: `dart-code`
- Extension Version: `3.23.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.56.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by ShreyasBhaktharam** [comment]
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 222,
		"activateCallTime": 139,
		"activateResolvedTime": 19639,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "Dart-Code.dart-code",
				"_lower": "dart-code.dart-code"
			},
			"activationEvent": "onLanguage:dart"
		}
	},
	"runtimeErrors": []
}
```

**Comment by DanTup** [comment]
Can you confirm exactly what the problem is you saw? It's not very clear from the report above. Thanks!

**Comment by ShreyasBhaktharam** [comment]
This extension prevents other important extensions to run when vscode starts for the first time. I have also noticed that when I open a big dart file (more than 200 lines of code) the workspace gets laggy and runs normally only if I disable the extension.

**Comment by DanTup** [comment]
> This extension prevents other important extensions to run when vscode starts for the first time.

Can you provide some more info about what you see? Usually if an extension blocks for too long (more than a few seconds) it will generate a CPU profile trace. If you have one of these, it would help understand what's going on.

>  have also noticed that when I open a big dart file (more than 200 lines of code) the workspace gets laggy and runs normally only if I disable the extension.

Can you confirm exactly what you see that's laggy? Do you mean typing, or functionality like code completion/hovers are slow?

Thanks!

**Comment by ShreyasBhaktharam** [comment]
> 
> Can you provide some more info about what you see? Usually if an extension blocks for too long (more than a few seconds) it will generate a CPU profile trace. If you have one of these, it would help understand what's going on.
> 

Unfortunately I haven't been able to capture a CPU profile of the extension loading but in the task manager I've noticed that the CPU load for vscode is very high when it launches. 


> Can you confirm exactly what you see that's laggy? Do you mean typing, or functionality like code completion/hovers are slow?
> 
> Thanks!

Typing mostly. But sometimes I've noticed that code completion takes a few seconds to complete and the same goes for hovers.

**Comment by DanTup** [comment]
> Unfortunately I haven't been able to capture a CPU profile of the extension loading but in the task manager I've noticed that the CPU load for vscode is very high when it launches.

If you're able to capture a profile trace, that would be very helpful. Usually VS Code captures them itself if an extension uses too much CPU, I'm not sure why it didn't here. There are some notes on debugging slow performance on https://github.com/microsoft/vscode/wiki/Performance-Issues#slow-startup (for ex. "Visual Studio Code starts up slowly") that might be helpful.

> Typing mostly. 

Do you have the Vim extension enabled, or anything other extension that might be handling keystrokes? Extensions run in a separate process to the editor so shouldn't usually be able to affect typing, however some extensions force the keystrokes through the extension process (see https://github.com/microsoft/vscode/issues/75627).

If you aren't already using LSP mode, you can enable the `dart.previewLsp` setting which may improve things.

If that doesn't help and you can get a CPU profile or [an analysis logfile](https://dartcode.org/docs/logging/#capture-analysis-server-logs) of things that seem slower than they should be, I can take a look. Thanks!

**Comment by ShreyasBhaktharam** [comment]
> 
> Do you have the Vim extension enabled, or anything other extension that might be handling keystrokes? Extensions run in a separate process to the editor so shouldn't usually be able to affect typing, however some extensions force the keystrokes through the extension process (see [microsoft/vscode#75627](https://github.com/microsoft/vscode/issues/75627)).
> 
> If you aren't already using LSP mode, you can enable the `dart.previewLsp` setting which may improve things.

These two fixes seemed to have improved the performance. Thanks for the help!
