### ISSUE TITLE
Android Studio opening project gradle JDK error

### ISSUE THREAD

**Issue by JoelDjilo** [Dart-Code/Dart-Code#3384]
Bonjour, j'ai un nouveau soucis, lorsque j'ouvre mes projets sur android studio, je reçois un message me renvoyant à la configuration du Gradle JDK
je précise que ne sachant pas vraiment de quoi il s'agit et même en ayant suivi les procédures proposées sur le suite androidstudio.dev et même les tutos sur comment régler les erreures de gradle, j'ai complètement désinstallé Android studio de mon PC (avec tous les repertoires associés) et répris tout à zéro.
Toujours pareil.
Je reçcois ce message d'erreur quand j'ouvre un ancien projet ou quand même je crée un nouveau projet.
Merci pour vos réponses
![Easytripapp 04_06_2021 15_55_51](https://user-images.githubusercontent.com/74889535/120823120-001e3500-c54f-11eb-92f4-c1a7b473b16d.png)

**Comment by DanTup** [comment]
This issue tracker is for the VS Code extensions - I'm afraid I'm not very familiar with Android Studio. The plugins for IntelliJ and Android Studio are in the repo at https://github.com/flutter/flutter-intellij, although there may be some things to try on some of the posts on StackOverflow for this error:

https://stackoverflow.com/questions/30328994/invalid-gradle-jdk-configuration-found

Hope this helps!

**Comment by JoelDjilo** [comment]
Ah merci @DanTup
