### ISSUE TITLE
Autocomplete doesn't automatically trigger when completing "import '';" and using LSP

### ISSUE THREAD

**Issue by hristo-kanchev** [Dart-Code/Dart-Code#3385]
**Describe the bug**
Autocomplete while importing packages doesn't work.

**To Reproduce**
1. Create a dart file in a flutter project.
2. Start typing `import 'package:..'`
3. Autocomplete doesn't show up.

**Expected behavior**
Auto-completion for `import`s should work and list all available packages.

Downgrading to 3.22.0 fixes the issue.

**Screenshots** (same project, same SDK versions,)

- Importing while using `3.23.0` version of the extension:

https://user-images.githubusercontent.com/23095052/120890762-125aaa80-c605-11eb-8877-1d1250e9581d.mp4

- Importing while using `3.22.0` version of the extension (working as expected):

https://user-images.githubusercontent.com/23095052/120890777-2e5e4c00-c605-11eb-9927-c14923e811d3.mp4

**Versions (please complete the following information):**
 - VS Code version: 1.56.2
 - Dart extension version: 3.23.0
 - Dart/Flutter SDK version: 2.13.0/2.2.0
 - OS: Windows 10

**Comment by DanTup** [comment]
@hristo-kanchev is the issue that the completion doesn't contain the right items, or just that it's no opening automatically? If you press `Ctrl`+`Space` does it open with the expected items?

**Comment by hristo-kanchev** [comment]
Hey @DanTup! Hope you are doing well and thank you for coming back to this.

The regression seems to be when you are typing out the packages (as shown in the videos above). 
While _typing_ out the package name you want to import in `v3.23.0`, you don't see anything outcompleted. (first video).

If you press `Ctrl` + `Space` it works as expected for both `v3.23.0` and `v3.22.0`.

**Comment by DanTup** [comment]
Got it, thanks!
