### ISSUE TITLE
Option to remove unused imports but not organize imports

### ISSUE THREAD

**Issue by MuathAmer** [Dart-Code/Dart-Code#3387]
**Is your feature request related to a problem? Please describe.**
I am using the dart package `import_sorter` to sort imports, it is run as a pre-commit git hook in my environment.
The problem is, I can't enable Dart-Code's organize imports on save because it sorts all imports and overrides what `import-sorter` does. 

**Describe the solution you'd like**
I would love to have an option to make Dart-Code remove unused imports, but not sort imports.

**Describe alternatives you've considered**
An alternative is to include `import-sorter` or equivalent functionality within Dart-Code.

**Additional context**
--

**Comment by DanTup** [comment]
Changes to sorting, or being able to remove unused without sorting would need to come from the server so this should be raised at https://github.com/dart-lang/sdk.

> The problem is, I can't enable Dart-Code's organize imports on save because it sorts all imports and overrides what `import-sorter` does.

Out of interest - if you run `import_sorter` as a pre-commit hook, wouldn't it just re-sort them on commit and fix itself?
