### ISSUE TITLE
could you support suffix autocomplete like idea?

### ISSUE THREAD

**Issue by Silentdoer** [Dart-Code/Dart-Code#3391]
in idea, we can:
a+b.var
then ide will tips b or (a+b), choolse (a+b) will generate:
var param = a + b(param is focus, and after naming param, press enter key will jump to b, then we can press; to close the statement)

**Comment by DanTup** [comment]
Thanks for the suggestion! There's already an issue covering this at #1826, although it may require some improvements to the LSP protocol (https://github.com/microsoft/language-server-protocol/issues/92#issuecomment-455797531) to be able to implement.

**Comment by DanTup** [comment]
The open issue for this https://github.com/Dart-Code/Dart-Code/issues/1826 (and https://github.com/dart-lang/sdk/issues/41425). This is not something currently being worked on (nor do I know how well we can do it without [LSP changes](https://github.com/microsoft/language-server-protocol/issues/991), but you should add 👍 s to those issues to help show there's demand for this. Thanks!
