### ISSUE TITLE
How to set up vscode eslint to parse flutter web index.html file?

### ISSUE THREAD

**Issue by sabetAI** [Dart-Code/Dart-Code#3392]
How do I set up javascript linting for flutter web's auto-generated `index.html`? Hard to catch issues like https://github.com/flutter/flutter/issues/83176 otherwise.

**Comment by DanTup** [comment]
I don't know the best way to do this - it's somewhat out-of-scope/unrelated to this extension.

I suspect you'll need [this extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), to install eslint via `npm` and to create a [configuration file](https://eslint.org/docs/7.0.0/user-guide/configuring) that specifies the ECMAScript version you want to target.

The best source of information (and the place to raise issues if it doesn't seem to work right) would be https://github.com/Microsoft/vscode-eslint.

Hope this helps!
