### ISSUE TITLE
Add a CodeActionProvider for code fixes

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#34]
[VSCode doc](https://code.visualstudio.com/docs/extensionAPI/vscode-api#CodeActionProvider)
[Analysis Server doc](https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html#request_edit.getFixes)

**Comment by devoncarew** [comment]
FYI, if you haven't used them, the analysis server's quick fixes are an awesome feature. From my perspective, this is one of the big outstanding features left to implement (once the rename refactor lands).

**Comment by DanTup** [comment]
I've not seen them, but I'm really keen to have them, I use the equiv in C# *loads* (assuming it's same sort of things; like you typed a class without importing its namespace, a fix offers to add the namespace, etc.).

**Comment by jrote1** [comment]
Would definitely be good for importing types that cannot be found.

**Comment by DanTup** [comment]
Started work on this; seems to work really well (even offers to fix typos!), but I hit some snags. Hoping it's something silly I'm doing wrong and easy to fix! https://github.com/Microsoft/vscode/issues/10912

**Comment by DanTup** [comment]
This is done and working. There's a weird issue with the UI not updating if you use the `F8` popup isntead of `Ctrl+.` (lightbulb) menu, but that is as-designed in Code (but I'm hoping maybe they can be convinced to improve!).

**Comment by DanTup** [comment]
Moving to 0.11 so we can ship Debugger + Rename now (Code Actions are very wonky until the Code fix in 1.5 to update them when you apply them).
