### ISSUE TITLE
DevTools not working for Chrome target

### ISSUE THREAD

**Issue by theoribeiro** [Dart-Code/Dart-Code#3400]
**Describe the bug**
Opening DevTools either in browser or in VSCode is not working when the target is a web app. It seems that the uri is pointing to an http endpoint as you can see in the first screen shot, even though the web app dialog shows an ws endpoint.

If I click on "Connect to New App" and paste the debug service address as it shows in the console (like `ws://127.0.0.1:52903/n0Q1uItxsWo=/ws`) it connects properly and all inspectors start working.

**To Reproduce**
1. Create a new flutter 2.2 project in VSCode
2. Start project in Chrome
3. Open Widget Inspector
4. See it is loading forever
5. Open DevTools in browser
6. Connect to new app
7. Paste debug service `websocket` address
8. Profit

**Expected behavior**
DevTools should connect directly to the correct address and show all inspectors.

**Screenshots**
![image](https://user-images.githubusercontent.com/41117224/121435458-eadd4800-c94c-11eb-90f6-1612258413d5.png)
![image](https://user-images.githubusercontent.com/41117224/121435692-56271a00-c94d-11eb-9913-3036015fbe5f.png)
![image](https://user-images.githubusercontent.com/41117224/121435749-6b9c4400-c94d-11eb-803f-02071ec52f2d.png)
![image](https://user-images.githubusercontent.com/41117224/121435795-7d7de700-c94d-11eb-952c-4b8de114efce.png)

**Versions (please complete the following information):**
 - VS Code version: 1.56.2
 - Dart extension version: 3.23.0
 - Dart/Flutter SDK version: 2.2.1

**Comment by DanTup** [comment]
I can repro this, but I don't think it's related to using the HTTP endpoint, as pasting that into the Connect dialog also works. DevTools normalises the URI it's given. It seems like there's an issue when it comes on the query string. I'll see what I can find...

**Comment by DanTup** [comment]
I can repro this without VS Code (and using the ws URL) from the terminal. I suspect it may be a Flutter or DevTools issue. Let's move this over to https://github.com/flutter/devtools/issues/3105 since it's not the VS Code extension.
