### ISSUE TITLE
Does the plugin have quick snippet functionality for didChangeDependencies?

### ISSUE THREAD

**Issue by purezen** [Dart-Code/Dart-Code#3403]
Would like quick snippet functionality for `didChangeDependencies` method, similar to what exists for `initState`

Does it exist?

**Comment by DanTup** [comment]
Can you clarify exactly which functionality you're refering to?

There are a few settings like `dart.completeFunctionCalls` that will affect some of the code completion, but I'm not certain if that's what you're after.
