### ISSUE TITLE
VS Code shows no device while adb in terminal shows it

### ISSUE THREAD

**Issue by harshitsnghl** [Dart-Code/Dart-Code#3404]
This issue occurred after when i installed [autoadb](https://github.com/rom1v/autoadb). During the process of setting an `auto start on login script`, I logged out and logged in many times. Also maybe did a full reboot while flutter run running via vs code. Maybe this caused the issue or may be not. I tried every possible fix listed below.

1. Enabled disabled Dart Extension / Flutter Extension 
2. Deleted and and freshly cloned the project.
3. Reinstalled Android Sdk Platform Tools
4. Revoked USB debugging
5. Restarted VS Code
6. Restarted PC
7. Opened another flutter project folder from VS Code > File > Open Folder
It started showing for other projects but not the main project. / Opened another project folder, then I closed it and re-opened my main project folder.

And many more. But none of them worked. Also tried downgrading extensions version but `No device` was still there on my main project.  

I'm using --no-sound-null-safety to unsound null safety. Workspace is also configured to run with this arg.

Currently I'm working on my project by using an external terminal.
i.e 
```bash
flutter run --no-sound-null-safety
``` 
works perfectly and 
 the output of my adb devices command is 
```bash
adb devices && adb version
```
![TerminalImage](https://user-images.githubusercontent.com/55857650/121953263-f7153b00-cd7a-11eb-9e54-1be8e6dda52d.png)
![TerminalImage](https://user-images.githubusercontent.com/55857650/121953211-e795f200-cd7a-11eb-94ec-16cef4b45076.png)

**Expected behaviour**
I expect VS Code to detect my device.

![image](https://user-images.githubusercontent.com/55857650/121953407-25931600-cd7b-11eb-96e2-b556fa792ad7.png)

**Versions:**
 - VS Code version: 
 1.56.2 054a9295330880ed74ceaedda236253b4f39a335 x64
 - Dart extension version:
 3.23.0
 - Dart/Flutter SDK version:
**Dart SDK version**: 2.13.3 (stable) (Wed Jun 9 12:44:44 2021 +0200) on "linux_x64"
**Flutter SDK version**:Flutter 2.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 02c026b03c (3 weeks ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1

**Comment by DanTup** [comment]
Does the device show up when you run `flutter devices` (not `adb`) from the terminal?

If so, could you enable the [Flutter daemon logfile](https://dartcode.org/docs/logging/#flutter-daemon) and see what it captures?

Thanks!

**Comment by aayushs177** [comment]
Well done
