### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by D-stroyR** [Dart-Code/Dart-Code#3405]
- Issue Type: `Bug`
- Extension Name: `dart-code`
- Extension Version: `3.23.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.57.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by DanTup** [comment]
> ⚠️ We have written the needed data into your clipboard. Please paste! ⚠️

Are you able to provide this info? Can you also give a description of the issue you're seeing? Thanks!
