### ISSUE TITLE
Device list out of sync

### ISSUE THREAD

**Issue by ristiisa** [Dart-Code/Dart-Code#3406]
After some time of usage the device list does not represent the output of `flutter devices`. Worth noting is that the tooltip shows the correct count. The only way to make it work again is to restart VS Code.

![image](https://user-images.githubusercontent.com/514571/122016895-256e3700-cdca-11eb-9815-6dfe786ea174.png)

```
% flutter devices
4 connected devices:

SM N960F (mobile)         • 2a48e1e510037ece                         • android-arm64  • Android 10 (API 29)
Krister’s iPhone (mobile) • 94c516d20a75ea2e12d02bf25e8e13fb8bbcd8cc • ios            • iOS 14.3
iPhone 12 mini (mobile)   • F5954689-236B-4EEE-8908-75D76DD88AFE     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
Chrome (web)              • chrome                                   • web-javascript • Google Chrome 91.0.4472.101

• Error: Ingmar’s iPhone is not connected. Xcode will continue when Ingmar’s iPhone is connected. (code -13)
```

```
 - VS Code version: 1.58.0-insider (The VS Code is running on windows, but using RemoteSSH I'm developing on a mac)
 - Dart extension version: v3.23.0
 - Dart/Flutter SDK version: Flutter (Channel stable, 2.2.2, on macOS 11.2.1 20D74 darwin-x64, locale en-EE)
```

**Comment by DanTup** [comment]
I suspect it may be related to this:

> Error: Ingmar’s iPhone is not connected. Xcode will continue when Ingmar’s iPhone is connected

I'm not sure what causes this, but wonder if the connection is somehow intermittent.

Could you enable the [Flutter Daemon log](https://dartcode.org/docs/logging/#flutter-daemon) and next time it occurs, grab a copy of that file? Thanks!

**Comment by ristiisa** [comment]
> I suspect it may be related to this:
> 
> > Error: Ingmar’s iPhone is not connected. Xcode will continue when Ingmar’s iPhone is connected
> 
> I'm not sure what causes this, but wonder if the connection is somehow intermittent.

This is because I have enabled "wireless" connection from xcode -> devices. but the device was not on network and I guess xcode was not smart enough to understand that. The tooltip showed 4 devices while the dropdown showed only 2.

> Could you enable the [Flutter Daemon log](https://dartcode.org/docs/logging/#flutter-daemon) and next time it occurs, grab a copy of that file? Thanks!

I'm having some issues producing the requested log. I get an "error" when I try to set the variable `This setting cannot be applied in this window. It will be applied when you open a local window.`  But setting it in the target machine (macos) does not produce the log.

When I open the vscode on target machine some extra devices are shown:
![image](https://user-images.githubusercontent.com/514571/122042949-78a0b380-cde3-11eb-8b48-42b3c2433f1f.png)

![image](https://user-images.githubusercontent.com/514571/122043095-9f5eea00-cde3-11eb-8123-8deaab07a1ef.png)

**Comment by DanTup** [comment]
A sorry, I didn't realise the offline device was not the same as the one missing.

I'm not sure why the log setting doesn't work over remotes (I'll take a look shortly), but you could try this instead:

- Run the **Dart: Capture Extension Logs** command
- Disconnect and reconnect the device that's having issues
- Try to launch the app to open the device list (which doesn't include the device as it should)
- Click **Cancel** on the logging notification to stop logging and open the log

Thanks!
