### ISSUE TITLE
Setting to disable automatically adding import statements

### ISSUE THREAD

**Issue by maxwell8888** [Dart-Code/Dart-Code#3408]
**Is your feature request related to a problem? Please describe.**
When I use autocompletion on a class, e.g. `DivEl` -> `DivElement`, an import statement might be automatically added, in this case `import 'dart:html';`. This has caused me confusion a number of times because libraries where imported without me realising, and in some cases might be a mistake if I momentarily autocompleted the wrong class name then changed it.

**Describe the solution you'd like**
I would like to be able to disable this behaviour in the settings.

**Describe alternatives you've considered**
I can't see any other work arounds.

**Additional context**

**Comment by DanTup** [comment]
There's an existing setting (`dart.autoImportCompletions`) that controls this behaviour. If you set it to `false` or untick it (and reload VS Code) you'll no longer see completions for other libraries or have the imports inserted automatically.

<img width="994" alt="Screenshot 2021-06-16 at 14 11 10" src="https://user-images.githubusercontent.com/1078012/122225277-d3eaa880-ceac-11eb-88ff-8fd540efaeff.png">

Slightly related, there's an issue at https://github.com/dart-lang/sdk/issues/41641 about being more intelligent about which libraries can be imported (for example to reduce the chances `dart:html` is imported into Flutter apps).

Hope this helps!
