### ISSUE TITLE
Device not showing up in VSCode

### ISSUE THREAD

**Issue by gireeshp** [Dart-Code/Dart-Code#3409]
This is same as issue #1634. But opening the new issue as suggested by  @DanTup in this [comment](https://github.com/Dart-Code/Dart-Code/issues/1634#issuecomment-814834813). Tried android emulator, IOS simulator and a physical device (iPhone 11) connected. None were detected by VSCode (all were correctly detected by flutter devices command).

Happening with only one project and no other. This project was working fine earlier. Not sure what triggered this behavior or how to reproduce the issue.

Tried the following, but none worked: 
- Disable/re enable flutter extension
- Closed & reopened VSCode
- Disconnected & reconnected devices
- Restarted the MacBook
- Opened another project where VSCode detects devices correctly and reopened the project where it doesn't

**Screenshots**
<img width="1023" alt="Screen Shot 2021-06-16 at 3 42 23 PM" src="https://user-images.githubusercontent.com/4717349/122282863-e4ede680-ceb9-11eb-901f-c774f81020ea.png">

Flutter Doctor:
<img width="962" alt="Screen Shot 2021-06-16 at 3 53 06 PM" src="https://user-images.githubusercontent.com/4717349/122283867-026f8000-cebb-11eb-9790-0bef793f542b.png">

**Versions:**
 - VS Code version: 1.57.0
 - Dart extension version: v3.23.0
 - Dart/Flutter SDK version: 
Flutter 2.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 02c026b03c (3 weeks ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1

**Daemon log:**

> !! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!
> 
> Dart Code extension: 3.23.0
> Flutter extension: 3.23.0 (not activated)
> 
> App: Visual Studio Code
> Version: 1.57.0
> Platform: mac
> 
> HTTP_PROXY: undefined
> NO_PROXY: undefined
> 
> Logging Categories:
>     FlutterDaemon
> 
> Wed Jun 16 2021 [15:58:51 GMT-0400 (Eastern Daylight Time)] Log file started
> [3:58:51 PM] [FlutterDaemon] [Info] Spawning /Users/gireesh/development/flutter/bin/flutter with args ["--no-sound-null-safety","daemon"]
> [3:58:51 PM] [FlutterDaemon] [Info] ..  in /Users/gireesh/development/flutter
> [3:58:51 PM] [FlutterDaemon] [Info] ..  with {"toolEnv":{"FLUTTER_HOST":"VSCode","PUB_ENVIRONMENT":"vscode.dart-code"}}
> [3:58:51 PM] [FlutterDaemon] [Info]     PID: 28787
> [3:58:51 PM] [FlutterDaemon] [Info] ==> [{"id":"1","method":"emulator.getEmulators"}]
> [3:58:52 PM] [FlutterDaemon] [Info] Process terminated! 64, null
> [3:58:58 PM] [FlutterDaemon] [Info] ==> [{"id":"2","method":"emulator.getEmulators"}]
> [3:59:32 PM] [FlutterDaemon] [Info] ==> [{"id":"3","method":"emulator.getEmulators"}]
> [4:01:52 PM] [FlutterDaemon] [Info] ==> [{"id":"4","method":"emulator.getEmulators"}]
> [4:02:05 PM] [FlutterDaemon] [Info] ==> [{"id":"5","method":"emulator.getEmulators"}]
>

**Comment by DanTup** [comment]
It looks like you may have added `--no-sound-null-safety` to the `dart.flutterAdditionalArgs` setting, which is being sent to the Flutter daemon and causing it not to work.

For custom args for your app, you should put them in `args` in the `launch.json`. If you really do need to set it for _all_ apps (something I wouldn't recommend, as at some point you'll probably be migrating to sound null safety and need some apps to run one way and others not) you should use `dart.flutterRunAdditionalArgs` (note the `Run`).

Since this isn't the first time this has come up, I've filed https://github.com/Dart-Code/Dart-Code/issues/3410 to try and add some handling to detect when the daemon doesn't start correctly and show a warning (and an option to open the log).

Let me know if that doesn't solve the issue. Thanks!

**Comment by usalko** [comment]
I have the same issue:
```
!! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.23.1
Flutter extension: 3.23.0 (not activated)

App: Visual Studio Code
Version: 1.57.1
Platform: linux

HTTP_PROXY: undefined
NO_PROXY: undefined

Logging Categories:
    FlutterDaemon

Tue Jun 22 2021 [02:03:36 GMT+0300 (Moscow Standard Time)] Log file started
[2:03:36 AM] [FlutterDaemon] [Info] Spawning /home/ITRANSITION.CORP/i.usalko/flutter/bin/flutter with args [null,"daemon"]
[2:03:36 AM] [FlutterDaemon] [Info] ..  in /home/ITRANSITION.CORP/i.usalko/flutter
[2:03:36 AM] [FlutterDaemon] [Info] ..  with {"toolEnv":{"FLUTTER_HOST":"VSCode","PUB_ENVIRONMENT":"vscode.dart-code"}}
```
I've tried different projects, changes the settings. But It's still the same. No devices at all, nor Linux or chrome nor android emulators. I guess It's after an update to the new Visual Studio Code. But I'm not sure.

**Comment by usalko** [comment]
Amazingly I've found the reason, It's a plugin conflict.
After uninstall "icsharpcode.ilspy-vscode" all devices have appeared.

**Comment by DanTup** [comment]
Is it possible you may have had `flutterAdditionalArgs` set? I don't think that extension should cause this, but I think having something like:

```
"flutterAdditionalArgs": [null]
```

in your setting could. This would cause a null argument to be passed to the Flutter daemon which is what appears in the log `flutter with args [null,"daemon"]`.

In any case, glad to hear you've resolved it!

**Comment by RaulUrtecho** [comment]
I had the same issue VSCode was not recognizing my iPhone so I just remove the settings.json inside my vscode run config folder, then close VSCode and when I open it again it detects my iPhone.
The reason to use a settings.json in my case it was to run on unsound null safety debug mode.
Once VSCode detect my iPhone I re-add the settings.json 👍

**Comment by DanTup** [comment]
@RaulUrtecho it sounds like you've probably added a flag to the `dart.flutterAdditionalArgs` setting that is not valid for the Flutter daemon. You should either add it to `dart.flutterRunAdditionalArgs` (not the `Run` in there) or to your `launch.json` and then you should not need to do this.

**Comment by umermasood** [comment]
I have the same issue with VSCode not recognizing the emulator device, but it detects chrome.

`flutter doctor -v` output:

```
[✓] Flutter (Channel stable, 2.8.0, on Debian GNU/Linux 11 (bullseye) 5.10.0-10-amd64, locale en_US.UTF-8)
    • Flutter version 2.8.0 at /home/keystroke/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (2 weeks ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/keystroke/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /home/keystroke/Android/Sdk
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```

I am running Debian with i3wm. The issue only persists when I use VSCode in i3wm, if I use other DE like Gnome then it detects the emulator device.

Screenshots:
![devices](https://user-images.githubusercontent.com/70061645/147258128-db2e7ef8-ecae-44a8-804e-032badaa5148.jpg)

**Comment by DanTup** [comment]
@umermasood could you enable the [Flutter Daemon log](https://dartcode.org/docs/logging/#flutter-daemon) and restart VS Code to reproduce, then grab the log, then file a new issue with the details and log attached? Thanks!

**Comment by dennymoradiya** [comment]
hello

**Comment by iamthehimansh** [comment]
> It looks like you may have added `--no-sound-null-safety` to the `dart.flutterAdditionalArgs` setting, which is being sent to the Flutter daemon and causing it not to work.
> 
> For custom args for your app, you should put them in `args` in the `launch.json`. If you really do need to set it for _all_ apps (something I wouldn't recommend, as at some point you'll probably be migrating to sound null safety and need some apps to run one way and others not) you should use `dart.flutterRunAdditionalArgs` (note the `Run`).
> 
> Since this isn't the first time this has come up, I've filed #3410 to try and add some handling to detect when the daemon doesn't start correctly and show a warning (and an option to open the log).
> 
> Let me know if that doesn't solve the issue. Thanks!

Thanks @DanTup it works for me

**Comment by louisanb** [comment]
the line i was using was only charging. the device was found with a better cord

**Comment by hansmboron** [comment]
I had this problem and solved it by going to USB debugging in the device settings and disabling and activating it again.
