### ISSUE TITLE
Method calls on unresolved/invalid variables are coloured inconsistently

### ISSUE THREAD

**Issue by ykmnkmi** [Dart-Code/Dart-Code#3412]
**Describe the bug**
Extension method color depends on list type.

**To Reproduce**
```dart
void main() {
  var list = <dynamic>[1, 2, 3];
  list[0].equals(1); // <- blue

  var list2 = <int>[1, 2, 3];
  list2[0].equals(1); // <- yellow
}

extension ExpectExtension on Object? {
  void equals(Object? value) {
    assert(this == value);
  }
}
```
**Expected behavior**
Same colors.

**Screenshots**
![image](https://user-images.githubusercontent.com/53435297/122333625-449bce80-cf5a-11eb-9d1f-0fe77854842e.png)

**Versions (please complete the following information):**
 - VS Code version: 1.57.0
 - Dart extension version: v3.23.0
 - Dart/Flutter SDK version: 2.14.0-152.0.dev

**Comment by DanTup** [comment]
Thanks for the report! This appears to be due to the `dynamic` - all members are coloured as variables even when they're invocations:

<img width="599" alt="Screenshot 2021-06-17 at 11 44 36" src="https://user-images.githubusercontent.com/1078012/122382092-79f7ea80-cf61-11eb-9a8e-4ee4f3d0ce4b.png">

**Comment by DanTup** [comment]
I've a fix out for review at https://dart-review.googlesource.com/c/sdk/+/203940/. With that, it looks like this:

<img width="596" alt="Screenshot 2021-06-17 at 11 47 29" src="https://user-images.githubusercontent.com/1078012/122382759-22a64a00-cf62-11eb-88a2-86c9015f5fc3.png">

The fix is in the Dart SDK, so after merging, it'll show up in a future Dart/Flutter SDK release (rather than a VS Code extension release).

**Comment by DanTup** [comment]
After some back and forth, I'm no longer certain this is a bug (or at least, the originally described bug). There were some weird inconsistencies after making this change when it came to invalid code. Invalid methods are intended not to be coloured. Given the code:

```
int a;
a.foo().foo();
```

The first `foo` is known to be invalid and should be uncoloured. The second `foo` is _unresolved_ (we don't know what type it is). It seems incorrect to colour the second one like a method but the first one uncoloured.

So I think for consistency we should fix both unresolved and invalid members to be uncoloured (this was already sort-of happening for some, but the textmate grammar was filling them in and hiding this). This means methods that are _definitely wrong_ or _might be wrong_ (eg. the compiler can't validate them, and you also can't "jump to definition" etc.) will be uncoloured, like this:

![Screenshot 2021-06-17 at 19 58 03](https://user-images.githubusercontent.com/1078012/122457310-6a4ec500-cfa6-11eb-9389-f1add5274d9e.png)

If there is sufficient desire to colour unknown and unresolved methods like normal resolved methods, this may be something to look at - although it does mean that known invalid methods (eg. you try to call `foo` on an int) would also be coloured - making the highlighting a little less semantic.

**Comment by DanTup** [comment]
I repurposed this slightly to better match the new behaviour - that is, unresolved/invalid types will be left uncoloured (note: this requires an SDK update).

This means dynamic items will still be uncoloured (which was the original complaint), but with semantic tokens I think this makes sense - the compiler is unable to resolve them and leaving them coloured is a good indicator of that.

If you want the original regex-based colouring, you can disable semantic tokens (using the `editor.semanticHighlighting.enabled` setting). Generally, I'd try to avoid using `dynamic` where possible though - it's easy to create code that would be easy to make fail at runtime without any analysis errors.

Hope this makes sense!
