### ISSUE TITLE
Flutter/Dart plugin for VS Code not detecting connected devices

### ISSUE THREAD

**Issue by PHebbar** [Dart-Code/Dart-Code#3416]
Hi,

I am on Ubuntu, using VS Code for Flutter development.

I have 3 connected devices to my development machine. Chrome browser, an emulated device and a physical device. Sometimes everything works as expected and I see all the devices in VSCode. But very often the devices just don't show up in VS Code, even through I see them when  run flutter doctor. 

I have followed most of the workarounds in https://github.com/Dart-Code/Dart-Code/issues/1634 - none of them work.

Here is the output from flutter doctor -v:
[✓] Flutter (Channel beta, 2.2.2, on Linux, locale en_IN)
    • Flutter version 2.2.2 at /home/prasadh/snap/flutter/common/flutter
    • Framework revision d79295af24 (7 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/prasadh/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /home/prasadh/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /home/prasadh/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] VS Code (version 1.57.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • SM G973F (mobile) • RZ8M40EK28A • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome
      91.0.4472.77

• No issues found!

**Comment by DanTup** [comment]
Can you try enabling the daemon log with the [`dart.flutterDaemonLogFile`](https://dartcode.org/docs/logging/#flutter-daemon) setting. After setting the setting, restart VS Code then next time you see this, grab a copy of that file. Also check Help -> Toggle Developer Tools and see if there are any errors listed in the Console tab.

Thanks!

**Comment by PHebbar** [comment]
Hi DanTup,

Here's the log file attached.

Thanks,
[flutter_daemon.log](https://github.com/Dart-Code/Dart-Code/files/6678159/flutter_daemon.log)

**Comment by PHebbar** [comment]
Hi DanTup, 

I did some further research based on the daemon log output. Saw your resolution for https://github.com/flutter/flutter/issues/20326.

I had added --no-sound-null-safety to dart.flutterAdditionalArgs. Now moved it to dart.flutterRunAdditionalArgs and the devices are now visible. Guess the daemon started successfully.

Thanks!

**Comment by DanTup** [comment]
Great, glad you got it sorted! I've opened https://github.com/Dart-Code/Dart-Code/issues/3410 to look at maybe detecting/handling this better, as it seems like quite a few people have done this and it will probably cause some confusion for time to come.

Out of intererest, do you remember why you added it there? Did you follow instructions written somewhere? It might be good to track down and update them (at least to include `Run` in the setting name, but ideally to recommend using `launch.json`) to reduce it too.

Thanks!

**Comment by PHebbar** [comment]
Thanks!

I just searched for additional args in the extension settings, and this was
the first that came up. My miss that I didn't look for the right setting
that comes further down.

Thanks,

**Comment by DanTup** [comment]
> I just searched for additional args in the extension settings, and this was the first that came up

Thanks for confirming! I'll try to make the text clearer on these settings then, and add a note about using `launch.json`. Thanks!
