### ISSUE TITLE
How to enable indent tree like shown in photo in VS CODE ?

### ISSUE THREAD

**Issue by lakshits11** [Dart-Code/Dart-Code#3420]
**Describe the bug**
How to enable this type of indent tree in VS Code where it points to child through an arrow like shown in photo ? Or if this can't be enabled, is there any extension which do so ? In Android Studio, it is present by default.

**Pictures**

Here you can see a line from return to SizedBox and then SizedBox to child...

![flutter_indent_tree](https://user-images.githubusercontent.com/54276661/122703151-90a68600-d26e-11eb-9623-ac2a367fe109.PNG)

**To Reproduce**
1. Only enable dart and flutter extension. And now create a new flutter application project. And see yourself.

**Versions (please complete the following information):**
 - VS Code version: 1.57
 - Dart extension version: 3.23.0
 - Dart/Flutter SDK version: See below

![flutter version](https://user-images.githubusercontent.com/54276661/122703470-4b368880-d26f-11eb-95bf-d3f21f09b314.PNG)

**Comment by DanTup** [comment]
This is controlled by the [`dart.previewFlutterUiGuides` setting](https://dartcode.org/releases/v3-1/#preview-flutter-ui-guides). The feature is a little rough around the edges right now because VS Code has limited APIs for drawing like this (please 👍  [this issue](https://github.com/microsoft/vscode/issues/73780)!) and may not appear correctly for some fonts/line heights so it's not enabled by default.

You may need to restart VS Code after enabling the setting before you see them.

**Comment by lakshits11** [comment]
Thank You Danny !

**Comment by Eileen-34** [comment]
> **Describe the bug** How to enable this type of indent tree in VS Code where it points to child through an arrow like shown in photo ? Or if this can't be enabled, is there any extension which do so ? In Android Studio, it is present by default.
> 
> **Pictures**
> 
> Here you can see a line from return to SizedBox and then SizedBox to child...
> 
> ![flutter_indent_tree](https://user-images.githubusercontent.com/54276661/122703151-90a68600-d26e-11eb-9623-ac2a367fe109.PNG)
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Only enable dart and flutter extension. And now create a new flutter application project. And see yourself.
> 
> **Versions (please complete the following information):**
> 
> * VS Code version: 1.57
> * Dart extension version: 3.23.0
> * Dart/Flutter SDK version: See below
> 
> ![flutter version](https://user-images.githubusercontent.com/54276661/122703470-4b368880-d26f-11eb-95bf-d3f21f09b314.PNG)

how can we activate this default option on Android studio? I see only straight lines on my IDE.

**Comment by DanTup** [comment]
@Eileen-34 I'm not very familiar with Android Studio / IntelliJ (this issue tracker is for VS Code), but there's a related issue at https://github.com/flutter/flutter-intellij/issues/6253#issuecomment-1181635868 that may be relevant. It seems to suggest that the languages set for the Android part of the project might affect whether they work.
