### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by tanharpatel** [Dart-Code/Dart-Code#3425]
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `3.23.1`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.57.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`..\AppData\Local\Temp\Dart-Code.dart-code-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by DanTup** [comment]
> ⚠️ Make sure to attach this file from your home-directory:
> ⚠️..\AppData\Local\Temp\Dart-Code.dart-code-unresponsive.cpuprofile.txt

Are you able to supply this file? Thanks!
