### ISSUE TITLE
Debug toggles like `Toggle Debug Painting` are not restored after hot restart

### ISSUE THREAD

**Issue by tjx666** [Dart-Code/Dart-Code#3426]
**Describe the bug**

When I was debug paint, I run command `Flutter: Toggle Debug Painting`. After I click restart button, I want to debug paint again, but I need execute that command twice, the first time doesn't work. 

**To Reproduce**
1. Go to Flutter Project.
2. Run command `Flutter: Toggle Debug Painting`
3. Click restart button in debug toolbar
4. Run command `Flutter: Toggle Debug Painting`, there is no paint line in application
5. Run command `Flutter: Toggle Debug Painting` again, everything as usual.

**Expected behavior**

After restart and run that command, I can debug painting as usual.

**Versions (please complete the following information):**

```
Version: 1.58.0-insider (Universal)
Commit: 9744231fc12f1aed21089180b3f0394d694bd2a2
Date: 2021-06-23T05:12:16.478Z
Electron: 12.0.11
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0
Dart-Code: v3.23.1
Flutter 2.2.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d79295af24 (12 days ago) • 2021-06-11 08:56:01 -0700
Engine • revision 91c9fc8fe0
Tools • Dart 2.13.3
```

**Comment by DanTup** [comment]
This is supposed to re-enable itself after the hot restart so you don't need to do anything. Looks like it's become broken along the way somewhere though.
