### ISSUE TITLE
Intelissense for the assets folder

### ISSUE THREAD

**Issue by bdlukaa** [Dart-Code/Dart-Code#3433]
**Is your feature request related to a problem? Please describe.**

When working with assets, we often have to check on the `assets/` folder to check the asset name. It makes me unproductive, since my project have a lot of assets. Also, when an asset is renamed, we may forget to update `Image.asset` with the new asset name.

**Describe the solution you'd like**

When working with `Image.asset` or `AssetImage`, it'd be good to have the autocomplete feature for assets. Also, a warning telling you the asset doesn't exist or wasn't declared on `pubspec.yaml`.

**Comment by DanTup** [comment]
This would need to be implemented in the analysis server, since that's where the code completion comes from. I'm filed https://github.com/dart-lang/sdk/issues/46542 with the info from here, please 👍  and/or subscribe there for updates. Thanks!
