### ISSUE TITLE
Possibility to use an external terminal in launch.json for Dart CLI scripts

### ISSUE THREAD

**Issue by Becus25** [Dart-Code/Dart-Code#3434]
Currently the available options for launch.json's "configurations" tag "console" are "terminal" (integrated vscode terminal) or "debugConsole" (integrated vscode debug console).

There should also be the possibility to launch the terminal as an external window to use the systems terminal in a separate window. The integrated terminal in vscode controls a bit fussy and this could improve the workflow for cli apps. 

The option could like "console": "externalTerminal".

**Comment by DanTup** [comment]
For the next version this is supported both in `launch.json` and also the `dart.cliConsole` setting (which controls the default if not defined in launch.json). Thanks!
