### ISSUE TITLE
Links to error documentation do not appear in Problems view/Hovers when using LSP

### ISSUE THREAD

**Issue by tbm98** [Dart-Code/Dart-Code#3442]
on vscode:
<img width="676" alt="Screen Shot 2021-07-01 at 12 18 14" src="https://user-images.githubusercontent.com/52562340/124069943-42139b80-da67-11eb-8f45-b96fb1f5f93a.png">

on android studio
<img width="704" alt="Screen Shot 2021-07-01 at 12 22 37" src="https://user-images.githubusercontent.com/52562340/124069947-43dd5f00-da67-11eb-9172-d614109b1b94.png">

**Comment by DanTup** [comment]
This was missing from the LSP implementation. It wasn't supported when first implemented and was not added back when LSP get support for it.

Once https://dart-review.googlesource.com/c/sdk/+/205642 lands and ships in an SDK, the error codes will become clickable with Ctlr+Click to open the docs (I don't think that's a good UI or particularly discoverable, but unfortunately that's controlled by VS Code so would need to be improved there).

<img width="854" alt="Screenshot 2021-07-01 at 11 38 15" src="https://user-images.githubusercontent.com/1078012/124111655-6d938780-da61-11eb-8bfa-570aaee5ce5f.png">

(I'll keep this issue open until the change lands in the SDK). Thanks!

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/dc66d5df629ce7fabeb90bd3a60e1ea448c51aac. It'll show up in a future SDK release.
