### ISSUE TITLE
extract local variable should define the variable using final/const not var

### ISSUE THREAD

**Issue by tjx666** [Dart-Code/Dart-Code#3443]
**Describe the bug**

![Jul-01-2021 15-53-52](https://user-images.githubusercontent.com/41773861/124087442-95e0ad80-da84-11eb-9308-e94c5a296f6f.gif)

**Expected behavior**

Normally, the express should be defined to final, because they are using only once.
Sometimes, like following example, should be defined to constant:

![image](https://user-images.githubusercontent.com/41773861/124088120-3931c280-da85-11eb-8c5d-91ffee39c689.png)
**Screenshots**

**Versions (please complete the following information):**

```
Version: 1.58.0-insider (Universal)
Commit: 57930758db9e2c83f59b9ee1851400bd16192d32
Date: 2021-06-30T05:13:11.659Z
Electron: 12.0.12
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0
Flutter 2.2.2 • channel stable •
https://github.com/flutter/flutter.git
Framework • revision d79295af24 (3 weeks ago) • 2021-06-11
08:56:01 -0700
Engine • revision 91c9fc8fe0
Tools • Dart 2.13.3
```

**Comment by DanTup** [comment]
Thanks for the suggestion! These edits are created by the analysis server in the SDK, so this should be raised at https://github.com/dart-lang/sdk.

Please post the link back here so others that find this issue are able to follow. Thanks!
