### ISSUE TITLE
Dart analyzer crashes when debug is started

### ISSUE THREAD

**Issue by armandsLa** [Dart-Code/Dart-Code#3444]
**Describe the bug**
Dart analyzer crashes after running "Start Debugging" to launch app on a simulator. Chances for this to happen are 50/50. This can also happen when checking out a different branch.

I'm not entirely sure that it's the analyzer that crashes, but once this happens, auto-complete and lookup are gone. Code highlight still works, though.

This started to happen about 2 weeks ago. Before that I never experienced this issue.

**To Reproduce**
1. Open project
2. Start iOS simulator
3. Go to "Run & Debug"
4. Press "Start Debugging"

**Screenshots**
<img width="589" alt="Screenshot 2021-07-01 at 09 16 01" src="https://user-images.githubusercontent.com/6855713/124089906-0542a700-da5d-11eb-8af0-15ac05e0cde9.png">

**Versions (please complete the following information):**
 - VS Code version: 1.57.1
 - Dart extension version: 3.23.1
 - Flutter 2.2.0 • channel stable • https://github.com/flutter/flutter.git
 - Framework • revision b22742018b (7 weeks ago) • 2021-05-14 19:12:57 -0700
 - Engine • revision a9d88a4d18
 - Tools • Dart 2.13.0

**Comment by DanTup** [comment]
It sounds likely you're seeing https://github.com/dart-lang/sdk/issues/45996 which was hot-fixed in Flutter stable v2.2.2.

Please upgrade and restart VS Code and I think the problem will go away. If not, please let me know. Thanks!
