### ISSUE TITLE
Fix lints on format/save and Fix-all

### ISSUE THREAD

**Issue by rrousselGit** [Dart-Code/Dart-Code#3445]
**Is your feature request related to a problem? Please describe.**
Numerous lints come with an auto-fix option, but we have to apply the fixes almost one by one, which is tedious.

**Describe the solution you'd like**
Since VS code already keeps tracks of the list of issues and offers to fix them, VS code could expose a command for "apply all fixes".

Similarly, we could have an option to, right before executing `dartfmt`, apply fixes for the file.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by DanTup** [comment]
I think this would make sense implemented as a Source CodeAction (`source.fixAll`), which can be added to `editor.codeActionsOnSave`:

https://code.visualstudio.com/updates/v1_32#_fix-all-source-actions

It should follow the guides given by VS Code:

> Fix all actions automatically fix errors that have a clear fix that do not require user input. They should not suppress errors or perform unsafe fixes such as generating new types or classes.

It should be implemented in the server so it's a single request that builds all fixes, and not enumerated on the client as applying fixes for one diagnostic could interfere with others (for example changing offsets, or invalidating some other fixes), and repeated round trips to the server could be slow.

I think the server already has all the parts necessary for this (between `dart fix` and the (experimental) `edit.bulkFixes` call in the original protocol), but I'm not certain if they're stable enough to expose here yet.

**Comment by DanTup** [comment]
https://github.com/dart-lang/sdk/commit/85d455fbad6eb6f567e76a9a3726aa19ec8398d4 adds an implementation for "source.fixAll" which can be run from the command palette (Fix All) or added to `editor.codeActionsOnSave`.

It only fixes the same things that `dart fix`/`flutter fix` will fix (which is not the whole set of fixes available in the lightbulb menu, but those that are deemed safe to fix in an automated way (this work might not be complete, so it may still expand over time)).

**Comment by ViniciusSossela** [comment]
@DanTup  @rrousselGit  I am trying to launch the `Fix All` command, but it doesn't show on the command palette. Am I missing something?

<img width="597" alt="Screen Shot 2021-08-03 at 10 11 21" src="https://user-images.githubusercontent.com/4993276/128021332-2a3bebd6-db63-486d-97b0-1a8683617fc1.png">

<img width="739" alt="Screen Shot 2021-08-03 at 10 13 45" src="https://user-images.githubusercontent.com/4993276/128021512-bff0c371-542a-444a-9bd7-bd936e522a41.png">

```
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (5 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

```

**Comment by DanTup** [comment]
See my reply at https://github.com/Dart-Code/Dart-Code/issues/3469#issuecomment-891838504, thanks!
