### ISSUE TITLE
Add a command to generate a Dart Functions Framework project

### ISSUE THREAD

**Issue by nickmeinhold** [Dart-Code/Dart-Code#3450]
**Is your feature request related to a problem? Please describe.**

The [functions-framework-dart](https://github.com/GoogleCloudPlatform/functions-framework-dart) project includes a `dartfn` package ([repo](https://github.com/GoogleCloudPlatform/functions-framework-dart/tree/main/dartfn) | [pub](https://pub.dev/packages/dartfn)) that provides a CLI tool for generating Dart Functions Framework projects.  Using it as a CLI tool is fine but being able to do the same thing in VS Code with the steps being interactive is even better. 

**Describe the solution you'd like**

An additional command added to Dart-Code that would work in a similar way to how we already use Dart-Code to create Dart and Flutter projects, but that creates a Dart Functions Framework project via `dartfn`. 

**Describe alternatives you've considered**

I've been using a [tasks.json](https://github.com/enspyrco/enspyrco/blob/main/settings/.vscode/tasks.json) that gets most of the way to what I was wanting but is still a little clunky. 

**Additional context**

On Discord Dan said: "it seems like might be better rolled into dart create or similar (so all IDEs just get it for free without their own specific handling of this)" which seems to make a lot of sense. Happy to put an issue up on `functions-framework-dart` or the SDK or wherever if it turns out there's a more appropriate place... thanks! 

EDIT: I also added an [issue](https://github.com/GoogleCloudPlatform/functions-framework-dart/issues/256) on the [functions-framework-dart](https://github.com/GoogleCloudPlatform/functions-framework-dart) repo pointing to this one and asking what they thought.

**Comment by DanTup** [comment]
The VS Code extension calls out to `"dart create"` for creating projects now (it was previously [stagehand](https://pub.dev/packages/stagehand)). I think if this was to be provided by the extension it would have to come from there:

https://github.com/dart-lang/sdk/tree/master/pkg/dartdev/lib/src/templates

So I think the SDK repo would be a better place to file than here, although I'm not sure what the bar is for something to be added there.

Another idea in the meantime (although slightly less editor-centric) could be a GitHub repository marked as a [Template](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/creating-a-repository-from-a-template#about-repository-templates), which lets you easily create a "copy" of it and then clone it.

**Comment by nickmeinhold** [comment]
Sounds great, thanks Dan!
