### ISSUE TITLE
Keep getting error: "Your launch config references a program that does not exist. If you have problems launching, check the "program" field in your ".vscode/launch.json" file."

### ISSUE THREAD

**Issue by Player23man** [Dart-Code/Dart-Code#3452]
I've tried changing the program to go to "lib/main.dart" but that doesn't work.

**Comment by DanTup** [comment]
Please run the **Dart: Capture Debugging Logs** command in the command palette, then try to run your debug session. Then click **Cancel** on the logging notification to stop logging and open the log file.

In the log file somewhere you should see:

> Launch config references non-existant file /foo/path.dart

This should have the absolute path that we're looking for (and found didn't exist). If you're opening a parent folder of your project then your `launch.json` will need to set the `cwd` to a relative path to your project.

Eg. If you've opened `/foo/projects` but your project is in a sub-folder so the entry script is `my_project/lib/main.dart`, then you need to set `"cwd": "my_project"` in the launch.json so it knows which folder to launch from.
