### ISSUE TITLE
slow vscode

### ISSUE THREAD

**Issue by Mahmoud6901** [Dart-Code/Dart-Code#3456]
Issue Type: <b>Bug</b>

occure lag when I scroll down and up, make vscode slow when writing code and when I use android emulator vscode getting more slow

Extension version: 3.24.0
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (23.88GB free)|
|Process Argv|--crash-reporter-id 0f112d45-68ce-4846-80df-9df376e91241|
|Screen Reader|no|
|VM|67%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805:30301674
pythonvspyt200cf:30331938
binariesv615:30325510
vsccppwt:30329788
aatestflightcf:30331712

```

</details>

**Comment by DanTup** [comment]
Can you be more specific about the problem? Do you mean scrolling up and down in the code editor in VS Code is laggy? If so, that sounds like a VS Code issue, or perhaps that your machine is low on resources. What does your CPU/RAM usage look like when this occurs?

**Comment by Mahmoud6901** [comment]
My CPU usage is between 20-30% and RAM usage is 40- 47%

**Comment by DanTup** [comment]
@Mahmoud6901 can you describe the problem in more detail? Is scrolling up and down the editor slow? If so, that may be a VS Code issue. There are some open issues about scrolling lag in the VS Code issue tracker:

https://github.com/microsoft/vscode/issues/123344

**Comment by sno2** [comment]
@Mahmoud6901 Some advise I can offer you from working on a low-spec laptop for a bit is that running the app w/ Flutter web and enabling [dev tools mobile view](https://developer.chrome.com/docs/devtools/device-mode/#viewport) is a lot less hardware intensive than running a mobile emulator in my experience.
