### ISSUE TITLE
Intellisense problem

### ISSUE THREAD

**Issue by mHassan20896** [Dart-Code/Dart-Code#3457]
Issue Type: <b>Bug</b>

Intellisense often doesn't work

Extension version: 3.24.0
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

**Comment by DanTup** [comment]
Can you be more specific about the problem you're seeing? Thanks!

**Comment by thisdarktao** [comment]
I've experienced an issue where intellisense can take up to ~20 seconds to load, the tooltip just shows "Loading..." and nothing happens for a long time. Same issue with holding <kbd>Command</kbd> to "go to" something; it either doesn't underline or a long time, or takes a long time to actually go to the file.

These issues don't occur when editing a React project (TypeScript), so can only assume it's relating to Dart/Flutter plugins?

Version: 1.58.0-insider (Universal)
Commit: 1db97b8c87fb32aa47b58135832733f4950362b4
Date: 2021-07-05T11:04:33.775Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0

**Comment by DanTup** [comment]
@thisdarktao what version of the Flutter SDK are you using? Does the status bar show "Analyzing..." when it's slow like this?

**Comment by thisdarktao** [comment]
@DanTup Yes it does. As soon as it's done it seems like everything is responsive again. However, after a short period or opening other files, the same long "Loading..." times happen again and it analyses again.

```
Л flutter doctor -v
[✓] Flutter (Channel unknown, 1.22.6, on macOS 11.4 20F71 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/adam/Development/flutter
    • Framework revision 9b2d32b605 (6 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
    • Android SDK at /Users/adam/Library/Android/sdk
    • Platform android-30, build-tools 31.0.0-rc5
    • Java binary at: /Users/adam/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.2)
    • Android Studio at /Users/adam/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • 6C63CFDB-0408-48A8-83CB-227FD76A243D • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)

! Doctor found issues in 1 category.
```

I have had to check out `1.22.6` due to project requirements.

**Comment by DanTup** [comment]
@thisdarktao it sounds like you're seeing #3102. It's been fixed but the issue is in the SDK so I'm afraid the only way to get the fix is to upgrade to the latest SDK.

**Comment by DanTup** [comment]
@thisdarktao it sounds like you're seeing #3102. It's been fixed but the issue is in the SDK so I'm afraid the only way to get the fix is to upgrade to the latest SDK.

Edit: Another option would be to disable LSP (`dart.previewLsp: false`), but be aware that in the future LSP will become the only option for the Dart extension (so if you haven't migrated by then, you'd have to stick with an older version of the Dart extension too).
