### ISSUE TITLE
3.24.0 seems to ignore flutterTestAdditionalArgs

### ISSUE THREAD

**Issue by jeiea** [Dart-Code/Dart-Code#3459]
**Describe the bug**
I'm using `--no-sound-null-safety` due to legacy dependency. I can't run test by clicking hovering Run / Debug button above code since 3.24.0 upgrade.

**To Reproduce**
1. Be aware branch. 
```
git clone https://github.com/jeiea/flutter_example.git -b flutter_additional_args
cd flutter_example
flutter pub get
code .
```
2. Open `test/widget_test.dart` and click Run or Debug text button around line 15.

**Expected behavior**
Test execution.

**Screenshots**
![image](https://user-images.githubusercontent.com/4188984/124380998-21fc0a80-dcfb-11eb-9b8c-5cfe0604eccc.png)

**Versions:**
```
➜  code --version
1.57.1
507ce72a4466fbb27b715c3722558bb15afa9f48
x64
➜  code --list-extensions --show-versions | rg Dart
Dart-Code.dart-code@3.24.0
Dart-Code.flutter@3.24.0
➜  flutter --version
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (3 days ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
```

**Comment by DanTup** [comment]
Sorry for the bother! Please run **Extensions: Check for Updates** in VS Code to upgrade to v3.24.1 and this issue should be resolved. Thanks!

**Comment by jeiea** [comment]
Thanks, I checked the issue is resolved. It is a very quick fix!
