### ISSUE TITLE
Saving 'file_name.dart': Running 'Dart' Formatter

### ISSUE THREAD

**Issue by SebghatYusuf** [Dart-Code/Dart-Code#3460]
**Describe the bug**
After running some Debug Run of Flutter application, the VS Code slows down and whenever I'm changing the file and want to save I just see this notification: 
Saving 'filename.dart': Running 'Dart' Formatter
and it will stuck forever, 

**To Reproduce**
1. Create a new Flutter application.
2. Try to do some modifications with the code. 
3. Run the app multiple times, until you see Dart Analyzer is slowing down. 
4. Try to save the file after modified. 

**Expected behavior**
Save the file and run dart analyzer without any freeze or stuck. for fresh Flutter Projects mostly it's not happening but still is very annoying issue. 

**Screenshots**
![Screen Shot 2021-07-04 at 8 26 39 PM](https://user-images.githubusercontent.com/48417629/124391536-4d382700-dd06-11eb-9722-186110e6613b.png)

**Versions (please complete the following information):**
 - VS Code version:  1.57.1
 - Dart extension version: 3.24.1
 - Dart/Flutter SDK version: 2.2.1

**Comment by DanTup** [comment]
Are you on macOS? If so, please upgrade to Flutter v2.2.2 as I suspect what you're seeing is https://github.com/dart-lang/sdk/issues/45996 which was fixed in 2.2.2.

If you're not on macOS, please let me know and we can try to capture a log. Thanks!

**Comment by SebghatYusuf** [comment]
@DanTup, Yeah I'm using macOS, I'll upgrade to Flutter v2.2.2 and will see if the issue is occurring or not.

**Comment by DanTup** [comment]
In that case, I'm pretty certain it's that you're seeing. If you still see it after upgrading (and restarting VS Code), let me know and we can re-open this. Thanks!
