### ISSUE TITLE
Icons preview not loading in the suggestions. 

### ISSUE THREAD

**Issue by dev-yashmathur** [Dart-Code/Dart-Code#3467]
In the suggestions bar im not able to get the icon previews. Instead getting the broken image icon, however once I select it I do get the icon next to the line number.
Side note: the feature does work in android studio
also, previewlsp is set to true.

![image](https://user-images.githubusercontent.com/63182778/125081601-d2935100-e0e3-11eb-9b9b-a1bf3930a45b.png)
![image](https://user-images.githubusercontent.com/63182778/125081607-d45d1480-e0e3-11eb-9a24-4ca2f07bee69.png)

**Comment by ammarisrar28** [comment]
I am facing the same issue.

**Comment by DanTup** [comment]
Thanks for the report. I can reproduce this, and it seems like a regression in VS Code. There's an open issue here:

https://github.com/microsoft/vscode/issues/119786

Unfortunately I don't think there's a way we can workaround this until it's fixed there. Once it is, it should just start working again automatically. Sorry for the inconvenience!
