### ISSUE TITLE
flutter and dart command return nothing in windows 10 powershell

### ISSUE THREAD

**Issue by przbadu** [Dart-Code/Dart-Code#3468]
**Describe the bug**

**To Reproduce**
1. Followed https://flutter.dev/docs/get-started/install/windows installation process. Note that, I downloaded compressed file manually, and extracted it inside Documents folder, set env path variable properly.
2. I also tried with `C:\src>git clone https://github.com/flutter/flutter.git -b stable` created src directory inside c: and clone flutter stable branch. Again remove previously setup directory, updated path env variable. Also tried manually visiting `c:\src\flutter\bin` and running `.\flutter doctor` and `.\dart`, nothing happens

**Expected behavior**

- `flutter` command should print basic information in terminal
- `flutter doctor` should run and print flutter doctor output
- `flutter --version` should print flutter current version

**Screenshots**

![2021-07-11_18-00](https://user-images.githubusercontent.com/4189129/125205476-29468980-e2a2-11eb-88c8-d312cdcb777e.png)
![2021-07-11_17-59](https://user-images.githubusercontent.com/4189129/125205478-2a77b680-e2a2-11eb-8b80-1e7ea054b513.png)

**Versions (please complete the following information):**
 - Dart/Flutter SDK version: 2.2.3

**Comment by DanTup** [comment]
This issue tracker is for the Dart/Flutter extensions for VS Code so this isn't something that can be solved here and may need to be raised in the Dart or Flutter repos.

However I'd start by trying to call `dart.exe` from the embedded Dart SDK directly to see if that works:

```
C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe --version
```

If it does, then something may be going wrong with the `dart.bat` wrapper that Flutter ships in its `bin` folder.

**Comment by przbadu** [comment]
Looks like `cache` directory inside `bin` directory itself is missing in stable branch... I am raising this issue in flutter repo, thanks @DanTup

**Comment by DanTup** [comment]
@przbadu ah, that folder is actually created by `flutter` the first time you run it (it downloads the Dart SDK itself), so if that's missing I guess it's because the `flutter` tool has not run successfully. I'm not sure why this might be failing though (it looks like flutter.bat` calls `bin/internal/shared.bat` which is supposed to do the download).

The Flutter repo is the best place for this though, the devs there have a better understanding of how this works than me.
