### ISSUE TITLE
Icon preview not working in vscode

### ISSUE THREAD

**Issue by al375837** [Dart-Code/Dart-Code#3470]
Icons preview image not showing in live documentation pannel.

Steps to reproduce the behaviour:
1. Write ''Icons.add'' in a '.dart' file where flutter material is imported.
2. Hover with the mouse the variable and press Ctrl + Enter to show live docs.
3. In the live docs it is shown the name of the icon but instead of its image it is only shown the default file not found image.

Before yesterday 11/01/2021 everything worked as intended.

Screenshots:

![image](https://user-images.githubusercontent.com/47150487/125442148-4e0059f3-c4c7-4dfa-b73b-bd255db01971.png)
![image](https://user-images.githubusercontent.com/47150487/125442248-a1ad4067-9735-4fb5-aa74-13c4226376ee.png)

Versions:
 - VS Code version: 1.58
 - Dart extension version: 3.24.2
 - Dart/Flutter SDK version: 3.24.0

**Comment by DanTup** [comment]
Thanks for the report. This seems like a regression in VS Code. There's an open issue here:

https://github.com/microsoft/vscode/issues/119786

Unfortunately I don't think there's a way we can workaround this until it's fixed there. Once it is, it should just start working again automatically. Sorry for the inconvenience!
