### ISSUE TITLE
Auto-completion ignore function name after dollar sign '$'

### ISSUE THREAD

**Issue by GangemiLorenzo** [Dart-Code/Dart-Code#3473]
**Describe the bug**
When calling a function which contains a dollar sign '$' within its name, the intellisense suggest the full name, but at confirm, it actually troncate it at the dollar.
Example: `String test$function() =>'test'` will be autocompleted as `test()`

**To Reproduce**
1. Define a file .dart with a class
2. Define a function within the class, named with a dollar sign somewhere (ex. void test$function(){} )
3. Call that function from somewhere. The Intellisense will provide a suggestion, but if you accept, the result will be truncated at the dollar sign.

**Expected behavior**
I would exept VS Code to autocomplete as `test$function() ` and not `test() `

**Screenshots**
![1](https://user-images.githubusercontent.com/26723808/125589471-8f202f9b-ea35-4fe1-812c-fcabfe3b76a3.PNG)
![2](https://user-images.githubusercontent.com/26723808/125589476-34ad0f6a-726e-4d00-a95d-92ca6340371b.PNG)

**Versions (please complete the following information):**
 - VS Code version: 1.58.1
 - Dart extension version: 3.24.2
 - Dart/Flutter SDK version: Dart SDK version: 2.13.4 / Flutter 2.2.3
 
 
 initially I thought it was a vscode problem, so I opened a report, which was closed: [here](https://github.com/microsoft/vscode/issues/128577)

**Comment by DanTup** [comment]
Thanks for the report! I believe this is fixed by https://github.com/dart-lang/sdk/issues/46019. The change is in the SDK but hasn't made the stable channel yet (it will be in Dart v2.14 and whichever future version of Flutter includes that).

Sorry for the inconvenience!
