### ISSUE TITLE
Ignore Quick Fixes don't show even if enabled

### ISSUE THREAD

**Issue by orestesgaolin** [Dart-Code/Dart-Code#3476]
**Describe the bug**
I used to use Ignore Quick Fixes in tests sometimes e.g. when trying to use final with const widgets. However, for last couple of days I don't see it showing up even though I have it enabled in my VS Code:

**To Reproduce**
1. Add linter rule `prefer_const_constructors`
2. Type `return SizedBox()` in any `build` method.
3. Observe that there's no way to use Ignore Quick Fix

**Expected behavior**
I would like to be able to add ignore statement with quick fix in VS Code.

**Screenshots**

![CleanShot 2021-07-15 at 10 48 26](https://user-images.githubusercontent.com/16854239/125759025-b5272aa7-f8ae-41d1-b42a-d89634dfa396.png)

![CleanShot 2021-07-15 at 10 51 22](https://user-images.githubusercontent.com/16854239/125759278-d4056cde-bcd0-4b3e-80d2-84e3c3aea72d.png)

**Versions (please complete the following information):**

analysis_options.yaml:

```
include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - lib/l10n/*
linter:
  rules:
    public_member_api_docs: false
    require_trailing_commas: true
```

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale pl-PL)
    • Flutter version 2.2.3 at /Users/dominik/fvm/versions/stable
    • Framework revision f4abaa0735 (2 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dominik/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dominik/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.4 20F71 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```

**Comment by DanTup** [comment]
@orestesgaolin due to some changes to move these to the analysis server and support ignore-for-file, they're now only shown when running using LSP mode. If you set the `"dart.previewLsp"` setting to `true` in your settings, you should see them again:

<img width="466" alt="Screenshot 2021-07-15 at 11 52 57" src="https://user-images.githubusercontent.com/1078012/125776718-8e8cd5af-d5eb-4528-b020-2e9afbe239c2.png">

LSP is currently the default for 75% of users and will increase to 100% in next release, so I'd recommend switching to it - the non-LSP mode will be removed at some point in future.

Please let me know if you're still not seeing them with LSP (or if you have issues that are preventing you from enabling LSP). Thanks!

**Comment by orestesgaolin** [comment]
Thanks, it's shown again in LSP mode
