### ISSUE TITLE
Request: more sensible formatting for lists that require custom formatting

### ISSUE THREAD

**Issue by alexobviously** [Dart-Code/Dart-Code#3478]
**Is your feature request related to a problem? Please describe.**
Take for example this list, which needs to be viewed in a square because that's what it represents:
```dart
static const List<int> RAYS = [
     17,  0,  0,  0,  0,  0,  0, 16,  0,  0,  0,  0,  0,  0, 15, 0,
      0, 17,  0,  0,  0,  0,  0, 16,  0,  0,  0,  0,  0, 15,  0, 0,
      0,  0, 17,  0,  0,  0,  0, 16,  0,  0,  0,  0, 15,  0,  0, 0,
      0,  0,  0, 17,  0,  0,  0, 16,  0,  0,  0, 15,  0,  0,  0, 0,
      0,  0,  0,  0, 17,  0,  0, 16,  0,  0, 15,  0,  0,  0,  0, 0,
      0,  0,  0,  0,  0, 17,  0, 16,  0, 15,  0,  0,  0,  0,  0, 0,
      0,  0,  0,  0,  0,  0, 17, 16, 15,  0,  0,  0,  0,  0,  0, 0,
      1,  1,  1,  1,  1,  1,  1,  0, -1, -1,  -1,-1, -1, -1, -1, 0,
      0,  0,  0,  0,  0,  0,-15,-16,-17,  0,  0,  0,  0,  0,  0, 0,
      0,  0,  0,  0,  0,-15,  0,-16,  0,-17,  0,  0,  0,  0,  0, 0,
      0,  0,  0,  0,-15,  0,  0,-16,  0,  0,-17,  0,  0,  0,  0, 0,
      0,  0,  0,-15,  0,  0,  0,-16,  0,  0,  0,-17,  0,  0,  0, 0,
      0,  0,-15,  0,  0,  0,  0,-16,  0,  0,  0,  0,-17,  0,  0, 0,
      0,-15,  0,  0,  0,  0,  0,-16,  0,  0,  0,  0,  0,-17,  0, 0,
    -15,  0,  0,  0,  0,  0,  0,-16,  0,  0,  0,  0,  0,  0,-17
  ];
```

When I save the file in vscode, the formatter changes it to:

```dart
static const List<int> RAYS = [
    17,
    0,
    0,
    0,
    0,
    0,
    0,
    16,
    0,
    0,
    0,
    0,
    0,
    0,
    15,
    0,
    0,
```
and so on.

**Describe the solution you'd like**
Maybe someone has a better solution than this, but what I think would work is that if the formatter detects a list that has already been broken into rows, if any of them has more than 1 item then it understands this was done deliberately and doesn't reformat the list.

**Describe alternatives you've considered**
The only solution I've found so far is to save these lists in some constants.dart, disable the dart formatter while saving it and then turn it back on. Maybe there's another way that I can't find in the settings.

Also related, I have another constant like this:
```dart
static const DEFAULT_BRACKET = [[0]];
```
that gets broken into this:
```dart
static const DEFAULT_BRACKET = [
    [0]
];
```
and this is also not desirable.

**Comment by DanTup** [comment]
Thanks for the suggestion! The formatting is actually done by [dart_style/dartfmt](https://github.com/dart-lang/dart_style) so any changes would need to be made there. There are some notes on the process for changes to the formatter at https://github.com/dart-lang/dart_style/wiki/Change-process (since changes can affect a lot of existing code, changes needs to be made carefully). Thanks!
