### ISSUE TITLE
Icon Preview Image Broken VS Code - Mac

### ISSUE THREAD

**Issue by kmanadkat** [Dart-Code/Dart-Code#3479]
**Describe the bug**
I was able to preview Material Icons before in VS Code auto complete dialog or info dialog. Now it shows broken image. But in the numbers panel the preview is visible, its strange :(

**Info Dialog**

<img width="792" alt="Screenshot 2021-07-16 at 5 13 55 PM" src="https://user-images.githubusercontent.com/25281055/125942781-0f8bf76b-b4cc-481a-a642-df1bac5800d1.png">

**Auto Complete Dialog**

<img width="1413" alt="Screenshot 2021-07-16 at 5 17 12 PM" src="https://user-images.githubusercontent.com/25281055/125942919-20266b06-7173-4f23-8602-fb2bbf1126a3.png">

**Extensions Versions**

<img width="698" alt="Screenshot 2021-07-16 at 5 20 28 PM" src="https://user-images.githubusercontent.com/25281055/125943181-49594a81-89f7-408b-82dc-48936142a608.png">

**Flutter Doctor**

<img width="872" alt="Screenshot 2021-07-16 at 5 22 49 PM" src="https://user-images.githubusercontent.com/25281055/125943420-720061fd-eaab-4e9b-9c1d-10c0243f401b.png">

This started happening since last 2 weeks now. I haven't updated anything in VS Code since last two weeks. I don't know why this is happening.

**To Reproduce**
I am not sure if it is reproducible or how I ended up having this bug :(

**Expected behavior**
Icon preview should be visible in Info dialog (that appears when you hover over Icon name) and Auto complete dialog (that appears when you write few letters of Icon name)

**Screenshots**
I added all of them in description above.

**Versions:**
 - VS Code: 
 Version: 1.58.2
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:09:06.581Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.3.0

 - Dart extension version: v3.24.2
 - Dart/Flutter SDK version: Flutter (Channel stable, 2.2.1, on macOS 11.2.3 20D91 darwin-x64, locale en-IN)

**Stackoverflow & previous issues**
I checked stackoverflow & old issues here if someone else also faced this issue. I got two links:

- https://stackoverflow.com/questions/68345670/flutter-preview-icons-showing-broken-asset-image-on-code-completion
- https://github.com/Dart-Code/Dart-Code/issues/2896

Could not find any solution. If its duplicate of any issue then please excuse me, my bad.

**Comment by DanTup** [comment]
Thanks for the report. This seems like a regression in VS Code. There's an open issue here:

https://github.com/microsoft/vscode/issues/119786

Unfortunately I don't think there's a way we can workaround this until it's fixed there. Once it is, it should just start working again automatically. Sorry for the inconvenience!

**Comment by kmanadkat** [comment]
Thanks :)
