### ISSUE TITLE
Icon previews missing in v3.24.2

### ISSUE THREAD

**Issue by warcayac** [Dart-Code/Dart-Code#3486]
The same problem explained in this [issue](https://github.com/Dart-Code/Dart-Code/issues/2333)

**Comment by DanTup** [comment]
This is unfortunately a VS Code issue and it doesn't appear there's a workaround - see https://github.com/Dart-Code/Dart-Code/issues/3479#issuecomment-881398751.

**Comment by amit0021** [comment]
Still the image preview is not showing. How to fix?

**Comment by DanTup** [comment]
> Still the image preview is not showing. How to fix?

See my comment above - this is unfortunately a VS Code issue and needs to be resolved by VS Code.
