### ISSUE TITLE
Performance Profiler - Method name not readable

### ISSUE THREAD

**Issue by FaFre** [Dart-Code/Dart-Code#3491]
**Describe the bug**
The method name inside the Profiler window is not displayed in the full length when a longer path is displayed. 
There seems to be no way to make it readable somehow. 

**To Reproduce**
Have a long Filepath.

**Expected behavior**
Make Method name appear in full length.

**Screenshots**
![image](https://user-images.githubusercontent.com/59543085/126866822-806940c5-6318-445b-9fad-ba0094da1494.png)

**Versions (please complete the following information):**
 - VS Code version: 1.58.2
 - Dart extension version: v3.24.0
 - Dart/Flutter SDK version: 2.2.3

**Comment by DanTup** [comment]
Thanks for the report! This is something that will need to be handled in DevTools, so should filed at https://github.com/flutter/devtools. It seems similar to https://github.com/flutter/devtools/issues/2779 which affected the timing columns.

If you raise there and post a link back here, anyone that finds this issue will be able to find it. Thanks!
