### ISSUE TITLE
Cpu become continue high when I fixing errors after migration nullable safety

### ISSUE THREAD

**Issue by jerryzhoujw** [Dart-Code/Dart-Code#3495]
It's intermittence cause vscode input hang when I edit.

I have open the Process Explorer, and the make sure memory left is above 1.0G

<img width="1680" alt="Screen Shot 2021-07-26 at 4 06 58 PM" src="https://user-images.githubusercontent.com/6405390/126955884-15c55251-f8c3-418c-b617-8d2aa4877c3e.png">

<details>
<summary>flutter doctor -v</summary>

```shell
jerryzhou@Jerrys-MacBook ~/D/c/f/p/r/robo> flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5 20G71 darwin-x64, locale en-CN)
    • Flutter version 2.2.3 at /Users/jerryzhou/Documents/code/flutter/sdk/flutter
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
    • Android SDK at /Users/jerryzhou/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0-rc1
    • Java binary at: /Users/jerryzhou/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Users/jerryzhou/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✗] Cannot determine if IntelliJ is installed
    ✗ Directory listing failed

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.164
```

</details>

**Comment by DanTup** [comment]
Are you able to reproduce this on a project you can share? How long does the CPU stay high for? Does this occur only after you modify a many files with find/replace or also when just trying to edit in a single file?

**Comment by jerryzhoujw** [comment]
Em, not sure if I can reproduce this in a project that I can share.

You can see the cpu load part. it almost after every time I edit in a single file.

Maybe because there's still lots of errors & warnings in project ? is all this information send to language server when I typing every time?

<img width="194" alt="Screen Shot 2021-07-27 at 10 07 06 AM" src="https://user-images.githubusercontent.com/6405390/127083698-0d73b1c9-1d82-47e2-b509-f994322363c1.png">

**Comment by DanTup** [comment]
It shouldn't be - generally when you edit a file it should send just the changes to the server (usually each key press) and the server will re-analyze that file and send back errors for any files that changed.

There have been issues in the past where the VS Code process would consume lots of CPU for large numbers of errors (it would constantly refresh the Problems view with no debouncing) but it doesn't sound like that's what's happening here if it's the Dart process.

You can capture the traffic to the language server like this:

- Run the **Dart: Capture Analysis Server Logs** command
- Type some characters
- (wait a little while for the CPU to calm down)
- Click **Stop** on the logging notification to stop logging and open the log file

Generally there shouldn't be a huge amount of traffic from simple typing, but it may be interesting to see what you see there.

**Comment by jerryzhoujw** [comment]
There's 2 result I found today:

1. if I select the file from left panel:  File Explorer, there's no hang in VSCode, even cpu is high.
2. if I select the errors from bottom panel: Problems tab, when I select errors, and edit files, there's very high chance that VSCode is hang.

The bellow log is when I found the case of hang, then I start over the logging, and do `Command + Z`  maybe twice, and try to scroll edit area, and wait the hang and till hang go.

I do this with file name: `roomItemDetails.dart`
Duration: [5:22:34 PM] -> [5:22:36 PM]
I found lots of message is not related to the target file, It looks like somehow it trigger other file's Analyzer.

[log2.txt](https://github.com/Dart-Code/Dart-Code/files/6891899/log2.txt)

**Comment by DanTup** [comment]
> there's very high chance that VSCode is hang.

Can you clarify exactly what you mean by this? Is the VS Code editor unresponsive? If so, then I think this may be something VS Code needs to solve. The extensions and language server) run in a different process and should never be able to hang VS Code. If that's happening, it could be something like https://github.com/microsoft/vscode/issues/71165 / https://github.com/microsoft/vscode/issues/109406.

If you hide the bottom panel entirely, does the problem go away? If so, I think it would be worth profiling VS Code (see the link in https://github.com/microsoft/vscode/issues/109406#issuecomment-718691204).

> I found lots of message is not related to the target file, It looks like somehow it trigger other file's Analyzer.

This is not uncommon. Modifying one file can affect the diagnostics in other files (for example if you change a function in `file1.dart` that was called from `file2.dart`, then the diagnostics(errors) of `file2.dart` will also change), which means that changing one file may result in many files being re-analyzed.

**Comment by jerryzhoujw** [comment]
Hang means, I scroll in editor hang for a while.
And I found that there's one Code Helper(Render)  is about 180% in cpu of Activity Monitor when hang happened.

    Code Helper(Render)  180%
    dart 

In the other case I have mentioned above, the

**Comment by DanTup** [comment]
@jerryzhoujw it would be best to capture a VS Code profiling trace and file an issue in VS Code (see https://github.com/microsoft/vscode/issues/109406#issuecomment-718691204). The issue is likely that VS Code is doing some expensive work and it's being triggered too frequently. The best fix may be for that work to be optimised, or debounced to not run so frequently. It seems similar to the other issues I linked above.

If you do profile and file a VS Code issue, please post the link here so others and I can see the status of it. Thanks! :-)
