### ISSUE TITLE
Icons don't appear in vs code popup preview

### ISSUE THREAD

**Issue by ahmednfwela** [Dart-Code/Dart-Code#3497]
**Describe the bug**
Icons don't appear in vs code popup preview, but appear on the line numbers.

**Screenshots**
![image](https://user-images.githubusercontent.com/63286031/127097811-3bd4863b-295f-4843-8c5b-50a8fdef4605.png)
![image](https://user-images.githubusercontent.com/63286031/127097854-2fb8371d-f623-4ae2-8785-55eba9d6fc86.png)

**Versions:**
 - VS Code version: 1.58.2
 - Dart extension version: v3.24.2
 - Flutter SDK version: 2.2.3
 - Dart SDK version: 2.13.4

**Comment by DanTup** [comment]
Thanks for the report. This seems like a regression in VS Code. There's an open issue here:

https://github.com/microsoft/vscode/issues/119786

Unfortunately I don't think there's a way we can workaround this until it's fixed there. Once it is, it should just start working again automatically. Sorry for the inconvenience!
