### ISSUE TITLE
Extension issue startup activitation taking long time

### ISSUE THREAD

**Issue by seneargroup** [Dart-Code/Dart-Code#3499]
- Issue Type: `Bug`
- Extension Name: `dart-code`
- Extension Version: `3.24.2`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.58.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by DanTup** [comment]
> ⚠️ We have written the needed data into your clipboard. Please paste! ⚠️

Are you able to provide this information? Thanks!
