### ISSUE TITLE
Analyzer plugin fixes and assists are not available when using LSP

### ISSUE THREAD

**Issue by dkrutskikh** [Dart-Code/Dart-Code#3502]
Hi! I'm one of the authors of [Dart Code Metrics](https://pub.dev/packages/dart_code_metrics), and we use analyzer plugin API (like sending AnalysisErrorFixes, etc.) to communicate with the analysis server. If I enable LSP preview in VSCode and have the plugin enabled, VSCode starts to display diagnostics without quick fixes. For example,

![image](https://user-images.githubusercontent.com/8401894/127511731-3906e38c-16f0-434a-8030-ca10dabc165b.png)

![image](https://user-images.githubusercontent.com/8401894/127511154-b5ecdf35-ba70-4051-bf45-828cf7f468e4.png)

It works fine when LSP preview is disabled.

![image](https://user-images.githubusercontent.com/8401894/127511249-5a69fb64-25fe-456a-9fbf-24ba5a704370.png)

Could there be a problem with the analysis server?

Dart SDK version: 2.14.0-301.2.beta (beta) (Mon Jul 19 23:53:21 2021 +0200) on "macos_x64"
VSCode version: 1.58.0
Dart extension version: 3.24.2

**Comment by DanTup** [comment]
Are the fixes that are missing from your plugin, or all fixes? Could you try enabling the [analysis servers instrumentation log](https://dartcode.org/docs/logging/#analyzer-instrumentation) to see if any errors are recorded?

If you can provide a small repro I can use (and confirm the exact version of the SDK you're using), that may help too. Thanks!

**Comment by dkrutskikh** [comment]
@DanTup please look at https://github.com/dkrutskikh/dart_lsp_quickfix_problem. Thanks!

**Comment by DanTup** [comment]
Thanks - I can repro this. Looks like plugin code actions were overlooked when implementing LSP. Working on it - sorry for the bother!

**Comment by DanTup** [comment]
I've got a change open to add this to the server: https://dart-review.googlesource.com/c/sdk/+/208404/

![fixesfromplugins](https://user-images.githubusercontent.com/1078012/127537704-af465ec9-2fd5-4a1a-bcd6-c5885cb6298e.gif)

Since it's an SDK change, it will only show up in a future SDK release though (rather than Dart-Code release).

**Comment by dkrutskikh** [comment]
Thank you, please clarify this fix support new command https://dartcode.org/releases/v3-25/#fix-all-command?

**Comment by DanTup** [comment]
@dkrutskikh that new "fix all" command is equivalent to running "dart fix". It doesn't include all fixes, only a subset that have been chosen that are safe to apply together and that are _very likely_ the correct fix for the error.

I don't think it includes plugins (or how feasible it would be) - @bwilkerson may have more information about this than I.

**Comment by dkrutskikh** [comment]
Anyway, thanks a lot!

**Comment by bwilkerson** [comment]
No, we don't currently have support for plugins to contribute to the set of fixes applied by the `dart fix` command. That support does seem like something we should look into adding, though there might be some interesting challenges around the area of conflicting edits. If that's a feature you're plugin would use, please open an issue here: https://github.com/dart-lang/sdk/issues/new.

**Comment by DanTup** [comment]
The issue of plugin fixes not showing up is resolved by https://github.com/dart-lang/sdk/commit/00cc25a28b6c4af5613887256448156e86a654ee. Since the change is in the analysis server, it'll show up in a future SDK release rather than a Dart-Code release.
