### ISSUE TITLE
Leaves all related procceses opened after closing vscode

### ISSUE THREAD

**Issue by cronyakatsuki** [Dart-Code/Dart-Code#3504]
**Describe the bug**
After finishing my first app from the flutter website I closed android emulator and closed vscode but saw that the system felt slow. After opening Task Manager I saw that the ram usage was high because openjdk, adb and some other related processes were left opened. They were also doing some hard disk operations every couple of seconds and in the end I had to restart my system.

**To Reproduce**
Don't have any clear steps

**Expected behavior**
After closing vscode that it also closes all related processes.

**Screenshots**

**Versions (please complete the following information):**
 - VS Code version: 1.58.2
 - Dart extension version: v3.24.2
 - Dart/Flutter SDK version: Stable 2.2.3 Windows

**Comment by DanTup** [comment]
Can you reproduce this?

If so, could you enable the [flutter run logfile](https://dartcode.org/docs/logging/#flutter-run) (you'll need to enable it before starting the debug session), then reproduce the issue and then send the last 10-20 lines of that log file after you've closed VS Code?

Thanks!

**Comment by DanTup** [comment]
@cronyakatsuki did you track down what this was?
