### ISSUE TITLE
Flutter Icon Preview not working instead it is showing corrupt image icon 

### ISSUE THREAD

**Issue by arslankaleem7229** [Dart-Code/Dart-Code#3507]
I am working in VScode but few days back this error is showing which is really worst because of this I can worked properly. When I want to add an icon and preview it shows this corrupt image icon instead of icon. Please help me in this because this is really disturbing
![127750549-979078af-5b0f-4068-a940-bd52c4008e94](https://user-images.githubusercontent.com/49631685/127869601-9aa7fa87-3e08-4173-9e67-20b6cbdbb79f.png)

**Comment by DanTup** [comment]
Thanks for the report! Please see [the pinned issue](https://github.com/Dart-Code/Dart-Code/issues/3470) about this - it appears to be [a VS Code bug](https://github.com/microsoft/vscode/issues/119786) and unfortunately I've not been able to find a workaround. Please add 👍  to the VS Code issue. Thanks!

**Comment by arslankaleem7229** [comment]
I have added this in vscode issue and they said its an dart issue
