### ISSUE TITLE
Hot Reload Stopped Working after Hot Restart

### ISSUE THREAD

**Issue by 2002Bishwajeet** [Dart-Code/Dart-Code#3511]
**Describe the bug**
Flutter Hot Reload function has stopped working in the lastest Dart Code v3.25 extension (you cannot find in debug tools bar anymore)

**Steps to reproduce the behavior:**
1. Create a new Flutter Project
2. Debug your app
3. You can(could) notice hot reload in debug tools bar
4. Hot Reload the app 3-4 more times or make some slight changes in the code

**Wrong behavior**
 Hot Reload disappears from the debug tools bar (Even saving the app does not hot reloads it).
You can Hot reload from DevTools browser though

**Screenshots**
![image](https://user-images.githubusercontent.com/62933155/127991991-d51a2659-4bf5-4cf3-9fe5-a962443ae957.png)

**Versions :**
 - VS Code version: 1.58.2
 - Dart extension version: 3.25
 - Dart SDK version: 2.13.4
 - Flutter SDK version: 2.2.3

**Comment by DanTup** [comment]
I've not been able to reproduce this:

<img width="316" alt="Screenshot 2021-08-03 at 10 47 25" src="https://user-images.githubusercontent.com/1078012/127995471-63def468-fcd2-4f18-8dc8-7e6e54d131a7.png">

Could you try capturing debugging logs while reproducing this?

- Run the [**Dart: Capture Debugging Logs** command](https://dartcode.org/docs/logging/#capture-debugging-logs)
- Wait for the app to completely load and become visible
- Click **Cancel** on the logging notification to stop logging and open the log
- Remove anything sensitive from the log
- Attach the log here (or in a gist, or email to me at logs@dartcode.org)

Thanks!

**Comment by DanTup** [comment]
Actually - I can reproduce - this happens after a Hot Restart.

**Comment by manishcgain** [comment]
Until the issue is resolved, you can downgrade the extension by manually downloading the older version extension file from https://marketplace.visualstudio.com/items?itemName=Dart-Code, and installing with 
```
code --install-extension ~/Downloads/Dart-Code.flutter-3.24.0.vsix  
```
Make sure to uninstall the extension before manually installing it.

**Comment by DanTup** [comment]
You can also do this through the VS Code UI:

<img width="557" alt="Screenshot 2021-08-03 at 11 07 01" src="https://user-images.githubusercontent.com/1078012/127998220-2cc4cba7-32fe-451d-9c1e-040964602e1f.png">

Although FWIW I'm working on a fix, and if it's all good expect to publish a patch in the next few hours. Sorry for the inconvenience!

**Comment by DanTup** [comment]
If you run the **Extensions: Check for Extension Updates** command in VS Code, you should get Dart v3.25.1 that includes the fix.

**Comment by huylethanh** [comment]
I am not sure but after updated the new version, when saving the dart file, the new codes could not be loaded. it will work if there is no issue such as pixel overflow, after the issues happen, the new code no longer reload. I have to stop debug and run debug again.

**Comment by DanTup** [comment]
@huylethanh that doesn't sound related to this issue - could you open a new issue and provide some sample code I can use to reproduce the issue (and also which SDK version you're using and what platform you're running the app on)? Thanks!
