### ISSUE TITLE
Hot Restart hides Hot Reload button in VSCode Debug & Run

### ISSUE THREAD

**Issue by phulengo** [Dart-Code/Dart-Code#3515]
**Describe the bug**
When I "Run & Debug" my code, I realized that when I click on the Restart button, the Hot Reload button will disappear. I can't find the command Hot Reload on Command Pallete (`Cmd + Shift + P`) or elsewhere as well. Thus, I have to terminate the Debug session to enable the Hot Reload function.
This issue was also reported to the VSCode team, but it said that it was from the extension: https://github.com/microsoft/vscode/issues/130007

**To Reproduce**
1. Run or Debug the Dart/Flutter app from the code editor.
2. Click the "Hot Restart" button on debug panel or run `Flutter: Hot Restart` on Command Pallete

**Expected behavior**
Click on the Hot Restart button won't hide the Hot Reload button.

**Screenshots**
1. Run or Debug the Dart/Flutter app.
<img width="1792" alt="1" src="https://user-images.githubusercontent.com/30664920/128232146-cf56e12a-9cd0-48e1-9f7b-83956515c4e6.png">

2. Click the Restart button or run `Flutter: Hot Restart` on Command Pallete.
<img width="1792" alt="2" src="https://user-images.githubusercontent.com/30664920/128232157-1bc4f819-e48b-4b84-9484-be26a49ab335.png">
<img width="1792" alt="2 5" src="https://user-images.githubusercontent.com/30664920/128234413-54e1ba3e-b6dc-4f91-9ca7-43162c305552.png">

3. Hot Reload button is disappeared and can't be found on the command palette.
<img width="1792" alt="3" src="https://user-images.githubusercontent.com/30664920/128232163-32f2b93e-7bce-4ebe-9730-db06578ff0ab.png">

**Versions (please complete the following information):**
 - VS Code version: 1.58.2
 - Dart extension version: v3.25.1
 - Dart/Flutter SDK version: 2.13.4 (stable)

**Comment by DanTup** [comment]
Is it possible you hadn't reloaded VS Code since v3.25.1 of the extension was installed? v3.25.1 was a patch that specifically supposed to fix this issue (see #3511).

**Comment by phulengo** [comment]
> Is it possible you hadn't reloaded VS Code since v3.25.1 of the extension was installed? v3.25.1 was a patch that specifically supposed to fix this issue (see #3511).

Thank you for your notice, I've just tried to relaunch VSCode and I have a new notification about the Dart extension has been updated (v.3.25.1). Everything now works like a charm. Great work Dart-Code team 🔥

**Comment by phulengo** [comment]
@DanTup I also noticed that Hot Restart replaces hot Reload (On save, Hot Reload button on the debug panel, Command palette).

**Comment by DanTup** [comment]
@phulengo this is intended - Flutter does not currently support hot reload for Web (see https://flutter.dev/docs/development/platform-integration/web#does-hot-reload-work-with-a-web-app) and will perform a hot restart. It still registers a Hot Reload service so to VS Code it looks like Hot Reload is supported, which is why it still shows up in the command/toolbar, but when called, Flutter will do a restart.

Hope this makes sense!
