### ISSUE TITLE
Flutter & Dart extension helper stopped working after some time randomly.

### ISSUE THREAD

**Issue by uc-dve** [Dart-Code/Dart-Code#3516]
**Describe the bug**
I am using VS Code for flutter development it was working fine until I have upgraded to flutter 2.2 and vs code.
Now when I run app first time it is ok and works normally, but after some time (there is no specific condition), flutter and dart extension helper stop suggesting and stop showing error.

below is the video link of issue.
https://www.screencast.com/t/R0yRaKYNIpNj

'''
flutter doctor -v

> [✓] Flutter (Channel stable, 2.2.1, on Mac OS X 10.15.6 19G73 darwin-x64, locale en-GB)
>     • Flutter version 2.2.1 at /Users/dhirooverma/flutter
>     • Framework revision 02c026b03c (10 weeks ago), 2021-05-27 12:24:44 -0700
>     • Engine revision 0fdb562ac8
>     • Dart version 2.13.1
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
>     • Android SDK at /Users/dhirooverma/Library/Android/sdk
>     • Platform android-S, build-tools 30.0.3
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.4, Build version 12D4e
>     • CocoaPods version 1.10.1
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 4.0)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
> 
> [✓] VS Code (version 1.58.2)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.24.0
> 
> [✓] Connected device (3 available)
>     • Akshay’s iPhone (mobile) • 00008030-000929963463802E • ios            • iOS 14.4
>     • macOS (desktop)          • macos                     • darwin-x64     • Mac OS X 10.15.6 19G73 darwin-x64
>     • Chrome (web)             • chrome                    • web-javascript • Google Chrome 92.0.4515.131
> 
> • No issues found!

**Comment by DanTup** [comment]
It looks like you're on Flutter 2.2.1. There was an issue with file watching that would cause the analysis server VM to freeze. This was fixed in Flutter 2.2.2 (https://github.com/dart-lang/sdk/issues/45996 / https://github.com/dart-lang/sdk/issues/46249 / https://github.com/dart-lang/sdk/issues/46298).

If you upgrade to the latest stable Flutter and restart VS Code, I believe the issues will be resolved. Thanks!
