### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by AmshenShanu07** [Dart-Code/Dart-Code#3523]
- Issue Type: `Bug`
- Extension Name: `dart-code`
- Extension Version: `3.25.1`
- OS Version: `Linux x64 5.11.0-25-generic`
- VS Code version: `1.59.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by DanTup** [comment]
> ⚠️ We have written the needed data into your clipboard. Please paste! ⚠️

Are you able to provide this data and a description of the issue? Thanks!
