### ISSUE TITLE
Optional random seeding action in testing panel and command palette

### ISSUE THREAD

**Issue by Luckey-Elijah** [Dart-Code/Dart-Code#3529]
**Is your feature request related to a problem? Please describe.**
I like to run flutter/dart tests from the VS Code GUI directly, but when I what to run tests with `--test-randomize-ordering-seed=random` I use the terminal.

**Describe the solution you'd like**
An option to run tests with random seeding from the testing panel in VS Code or in the Command Palette.

**Describe alternatives you've considered**
Continue to execute tests in terminal.

**Additional context**

Possibly a new option would exist here.

<img width="375" alt="testing panel" src="https://user-images.githubusercontent.com/38171761/129229775-d7c80400-fde6-4050-848d-3447ed3422cc.png">

**Comment by DanTup** [comment]
Do you often change between modes, or would adding `--test-randomize-ordering-seed=random` to `dart.flutterTestAdditionalArgs` for the project work?

VS Code has gotten some new testing APIs in the last release and the goal is to move over to them, so a lot of this testing UI (that is custom for Dart) will go away in favour of the standard VS Code testing UI. I'm not sure if that may make it harder to have additional custom buttons like this (though I'll hopefully have a better idea when I start migrating).

**Comment by Luckey-Elijah** [comment]
That's a great idea! I have not used the `dart.flutterTestAdditionalArgs` option before. It does seem to provide what I am looking for in the above problem I provided. Thanks, @DanTup!

---

For others seeing this. I have added the below to my `settings.json`:

```json
{
  "dart.flutterTestAdditionalArgs": [
    "--test-randomize-ordering-seed=random"
  ]
}
```

And now when running tests, I see this output in the _Debug Terminal_:

```output
Shuffling test order with --test-randomize-ordering-seed=1792799059
✓ Test two
✓ Test one
```

**Comment by Luckey-Elijah** [comment]
Feel free to close.

**Comment by DanTup** [comment]
Great, glad that works for you! You should be able to specify it either in User Settings, or at Workspace/WorkspaceFolder level too (eg. if you only want it for some projects and not all).
