### ISSUE TITLE
vs code is not detecting flutter extension

### ISSUE THREAD

**Issue by anilpandey071999** [Dart-Code/Dart-Code#3531]
vs code flutter extension is not able to run app 

[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.662], locale en-IN)
    • Flutter version 2.2.3 at C:\flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\ADMIN\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.59.0)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (2 available)
    • M2101K6P (mobile) • 9396b993 • android-arm64  • Android 11 (API 30)
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 92.0.902.67

! Doctor found issues in 1 category.

![image](https://user-images.githubusercontent.com/31802461/129418783-2a951fca-145c-453d-a5d0-cadcf316692d.png)

**Comment by DanTup** [comment]
Can you include a screenshot of the Extensions tab in VS Code, and also check if Dart/Flutter extensions show up if you run **Developer: Show Running Extensions** from the VS Code command palette? Thanks!
