### ISSUE TITLE
Code formatted up to 80 char boundary on Linux

### ISSUE THREAD

**Issue by ydotmalik** [Dart-Code/Dart-Code#3532]
**Describe the bug**
On the Linux version of VS Code, format on save formats the code to a maximum 80 char column width, regardless of a greater Word Wrap column value.

I don't see this behavior on the Windows version of VS Code.

**To Reproduce**
1. Set 'Editor: Word Wrap Column' to 160
2. Set 'Editor: Word Wrap' to wordWrapColumn
3. Save file

**Expected behavior**
Code should be formatted to fit up to the word wrap column boundary

**Screenshots**

**Versions (please complete the following information):**
 - VS Code version: 1.59 (Linux)
 - Dart extension version: 3.25.1
 - Dart/Flutter SDK version: 2.2.3

**Comment by ydotmalik** [comment]
I compared my Linux settings.json with Windows, and found that I was missing the dart.lineLength parameter in the dart section in Linux.

**Comment by DanTup** [comment]
Sorry for the delay! This is correct, `dart.lineLength` controls the formatting. The Word Wrap value is where VS Code wraps long lines (visible, but not actually altering the file).
