### ISSUE TITLE
@macro annotation auto-completion

### ISSUE THREAD

**Issue by Marco87Developer** [Dart-Code/Dart-Code#3534]
When writing the documentation of a package, I find it very convenient to use the `@template` annotation, and then recall a part of the documentation in various other parts with the `@macro` annotation.

Would it be possible to implement auto-completion when using `@macro`?

Thank you very much!

**Comment by DanTup** [comment]
Thanks for the suggestion! The code completion is all handled by the Dart language server, so this would need implementing there and should be raised at https://github.com/dart-lang/sdk/issues.

Thanks!
