### ISSUE TITLE
`Assign value to new local variable` doesnt  use final when `prefer_final_locals`

### ISSUE THREAD

**Issue by Sunbreak** [Dart-Code/Dart-Code#3542]
**Describe the bug**
`Assign value to new local variable` still makes `var` when `prefer_final_locals` present in lint rules

```dart
var i = 1 + 2 + 3;
```

**To Reproduce**
1. Create project: `dart create my_dart`
2. Add code: `1 + 2 + 3`
3. Refactor code: press keys `CMD + .`

**Expected behavior**
```dart
final i = 1 + 2 + 3;
```

**Screenshots**
<img width="1115" alt="Screen Shot 2021-08-27 at 11 19 43 AM" src="https://user-images.githubusercontent.com/7928961/131067363-aa8efe5b-f363-4701-97cd-90e338953044.png">

**Versions (please complete the following information):**
 - VS Code version: 1.59.1
 - Dart extension version: v3.25.1
 - Dart/Flutter SDK version: flutter-2.2.3

**Comment by DanTup** [comment]
This is fixed in the Dart SDK (https://github.com/dart-lang/sdk/commit/f9db0dd6aa5883944555e88714577db19cb0bf6e). It'll ship in a future SDK release (rather than a Dart-Code release). Thanks!
