### ISSUE TITLE
Support "fix all" for prefer_const_constructors

### ISSUE THREAD

**Issue by jovanap17** [Dart-Code/Dart-Code#3544]
Hello. How to fix this all const warning in VS Code? Wasting time if I fix one by one.
![image](https://user-images.githubusercontent.com/49643347/131257214-aa8e64ef-74fc-47aa-a803-341a5e56b1b7.png)

**Comment by DanTup** [comment]
This has been fixed by https://github.com/dart-lang/sdk/issues/47001 in the SDK. It will show up in a future Dart/Flutter SDK release :-)

**Comment by YazeedAlKhalaf** [comment]
> This has been fixed by [dart-lang/sdk#47001](https://github.com/dart-lang/sdk/issues/47001) in the SDK. It will show up in a future Dart/Flutter SDK release :-)

Can I use it if I upgrade to some unstable version? If yes can you tell me which version I need from dart or flutter?

**Comment by DanTup** [comment]
The fix should be in the Flutter `master` channel, though I'm not sure about `dev` (it's unlikely to be in `beta` yet). I wouldn't recommend using `master`/`dev` for production work, but if you just want to try it out this fix it should work.

**Comment by YazeedAlKhalaf** [comment]
> The fix should be in the Flutter `master` channel, though I'm not sure about `dev` (it's unlikely to be in `beta` yet). I wouldn't recommend using `master`/`dev` for production work, but if you just want to try it out this fix it should work.

Thanks for your reply. Figured it out, the fix is in the master channel of Dart language.

Had to download it as an archive. Bear in mind it is not signed but you can use it.

I tried it yesterday and it is cool 🚀. Solved all 1000+ problems in a breeze.
