### ISSUE TITLE
Request: Implement a feature to take screenshot of device in flutter

### ISSUE THREAD

**Issue by arun28082007** [Dart-Code/Dart-Code#3549]
a am not able to take  device Full screenshot without naitve code , that's a show flutter have no natuve api.

We cant take screenshot using flutter code

**Comment by arun28082007** [comment]
I want to do in my flutter application Not from android studio
Using flutter code

**Comment by DanTup** [comment]
Ah, I see. This repository is for the VS Code extension so this isn't the place for feature requests for Flutter, https://github.com/flutter/flutter/ is the correct place that - although this seems like something that might be left to community plugins to do - there are already some packages at https://pub.dev/packages?q=flutter+screenshot that may do what you need.

Hope this helps!
