### ISSUE TITLE
`Wrap in widget` flutter fix moves cursor to wrong place

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#355]
![Cursor](https://user-images.githubusercontent.com/1078012/27956016-a1629560-630f-11e7-9101-04d7b6c14457.png)

**Comment by DanTup** [comment]
```js
{
	"message": "Wrap with new widget",
	"edits": [
		{
			"file": "m:\\Coding\\Applications\\flutter\\examples\\stocks\\lib\\main.dart",
			"fileStamp": 0,
			"edits": [
				{
					"offset": 86,
					"length": 15,
					"replacement": "new widget(child: new Container())"
				}
			]
		}
	],
	"linkedEditGroups": /*snip*/,
	"selection": {
		"file": "m:\\Coding\\Applications\\flutter\\examples\\stocks\\lib\\main.dart",
		"offset": 120
	}
}
```

This actually looks correct, 120 puts it at the end of the edit (86 + length of text to insert).

**Comment by xster** [comment]
Is it possible to have the new word 'widget' selected at the end of the operation?

**Comment by Skylled** [comment]
@xster Correct me if I'm wrong, but as far as I know, the edits are suggested by the analyzer. So that selection would need to be specified by the analyzer.

**Comment by DanTup** [comment]
It is actually supported by the analyzer, it's just been complicated to map over due to the differences in the APIs.

The work is being done as part of #356 and there's some WIP code in the `code-action-tab-stops` branch.

**Comment by xster** [comment]
Ah got it. Awesome, thanks!
