### ISSUE TITLE
Auto completion a request has failed error

### ISSUE THREAD

**Issue by motazalnuweiri** [Dart-Code/Dart-Code#3553]
**Describe the bug**
I have two files the first one is `user_response.dart` and contains `UserResponse class` and the second one is `token_response.dart` and contains `TokenResponse class` When I type a part of `TokenResponse class` name then select the full name from the auto completion list in Visual Studio Code this error message appear:

```
A request has failed. See the output for more information
Source: Dart (Extension)
```

The output:
```
[Error - 12:06:55 PM] Request completionItem/resolve failed.
  Message: No such element: TokenResponse in package:my_app/responses/user_response.dart
  Code: -32602 
TokenResponse
```

**To Reproduce**
I don't how to reproduce the problem

**Expected behavior**
It should auto complete the class name and insert the import for it.

**Screenshots**

**Versions (please complete the following information):**
 - VS Code version: 1.60.0
 - Dart extension version: 3.26.0
 - Dart/Flutter SDK version: Flutter 2.2.3 • channel stable

**Comment by DanTup** [comment]
Can you reproduce this at all, or did it just happen once? I tried making classes similar to your description but haven't been able to reproduce it. An [analysis server log](https://dartcode.org/docs/logging/#analyzer) would help if you can reproduce this, but be aware that it will contain parts of your source files so it's best to reproduce on a non-private repository. Thanks!

**Comment by motazalnuweiri** [comment]
> 
> 
> Can you reproduce this at all, or did it just happen once? I tried making classes similar to your description but haven't been able to reproduce it. An [analysis server log](https://dartcode.org/docs/logging/#analyzer) would help if you can reproduce this, but be aware that it will contain parts of your source files so it's best to reproduce on a non-private repository. Thanks!

No I can't reproduce the problem and yes it just happen in this project for the two files I mentioned.

Here the analyzer log file:
[analyzer.txt](https://github.com/Dart-Code/Dart-Code/files/7127966/analyzer.txt)

**Comment by DanTup** [comment]
I can't see an obvious cause from the log. If you make a copy of your project and remove everything except those files, does it still occur? If so, could you trim it down to something you can share so I can reproduce it here?

**Comment by motazalnuweiri** [comment]
I created new project added `json_serializable` dependency and copy the two files to it and the same error appeard.

**Comment by DanTup** [comment]
@motazalnuweiri are you able to trim them down to something you can share but still triggers the issue?

**Comment by motazalnuweiri** [comment]
@DanTup I tested the code on another PC and the problem didn't occur, so I think the problem is in `VS Code`, `Dart extension` or `LSP`. Finally I tried to clear the Dart extension cache but no luck,

**Comment by DanTup** [comment]
@motazalnuweiri are the VS Code, Dart-Code and Dart SDK (shown in the status bar) versions all identical? If you hover over the Dart/Flutter version in the status bar, do they both say "LSP" somewhere in the tooltip?

I can't think of any reason it wouldn't be consistent given the same code besides those - though if you can share a small repro that triggers it on your one machine, I can try it here to see if I have any luck.

**Comment by motazalnuweiri** [comment]
@DanTup I fix the problem by deleting this folder `C:\Users\<UserName>\AppData\Local\.dartServer`

**Comment by DanTup** [comment]
@motazalnuweiri glad you managed to resolve it! I'm not sure what may have caused it, but if it comes back it might be worth trying to understand what's wrong with the data in that folder that's causing the issue.

@scheglov what's the best way to get useful information here? Eg. if `.dartServer` is just renamed instead of deleted, and the problem persists - is it easy to get useful information from the old folder (without sharing what I presume is a large amount of data)?

**Comment by scheglov** [comment]
Without repro it is usually hard to use anything from `.analysis-driver`. It might have `ex` sub-directory with information about crashes during analysis, like `exception_20190927_010603_719`. These might be useful, if I will able to glean anything from the exception stack trace and the included code.

**Comment by motazalnuweiri** [comment]
@scheglov I sent you email contain the `ex` folder and I'm so sorry for the delay.

**Comment by SuporteSysrs01** [comment]
I'm having the same issue after removing a `part of` from a Dart file. Every time I trigger auto complete for the class it tries to get it's import from the old file it was a part of, instead of the actual path.
```
Request completionItem/resolve failed.
  Message: No such element: MyClass in package:myapp/old_path_to/the_file_it_was_part_of.dart
```
