### ISSUE TITLE
Double suggestions

### ISSUE THREAD

**Issue by theSharpestTool** [Dart-Code/Dart-Code#3555]
**Describe the bug**
VSCode shows double suggestions

**To Reproduce**
Try to trigger suggestions for any widget you will see that every options displayed twice. I guess it happened when Dart Code extension was updated to 3.26.0

**Expected behavior**
Should seee only one option

**Screenshots**
<img width="540" alt="Screenshot 2021-09-09 at 16 05 38" src="https://user-images.githubusercontent.com/41484688/132691739-84414e4f-71dd-42b7-9096-19c1a0be5cdd.png">

**Versions (please complete the following information):**
 - VS Code version: 1.60.0 (Universal) Mac OS
 - Dart extension version:  3.26.0
 - Dart/Flutter SDK version: Flutter 2.5.0, Dart 2.14.0

**Comment by theSharpestTool** [comment]
Was caused by analysis_options.yaml

**Comment by DanTup** [comment]
@theSharpestTool can you be more specific? I'd be interested to know what caused this to see if it could be handled better. Thanks!

**Comment by theSharpestTool** [comment]
Hi @DanTup it occurred because I added `dart-code-metrics` to my project, but first thought was that something wrong with this dart extension. I created the issue on [dart-code-metrics](https://github.com/dart-code-checker/dart-code-metrics/issues/451) you can review it

**Comment by DanTup** [comment]
Thanks - I can repro and this looks like a bug in the LSP initialisation, I'm taking a look.

**Comment by DanTup** [comment]
This looks like an issue in the LSP initialisation when there are plugins. We register two completion providers:

```
{
	"id": "3",
	"method": "textDocument/completion",
	"registerOptions": {
		"documentSelector": [
			{
				"language": "dart",
				"scheme": "file"
			}
		],
		"triggerCharacters": [
			".",
			"=",
			"(",
			"$",
			"\"",
			"'",
			"{",
			"/",
			":"
		],
		"resolveProvider": true
	}
},
{
	"id": "4",
	"method": "textDocument/completion",
	"registerOptions": {
		"documentSelector": [
			{
				"language": "yaml",
				"scheme": "file",
				"pattern": "**/pubspec.yaml"
			},
			{
				"language": "yaml",
				"scheme": "file",
				"pattern": "**/analysis_options.yaml"
			},
			{
				"language": "yaml",
				"scheme": "file",
				"pattern": "**/lib/fix_data.yaml"
			}
		],
		"resolveProvider": true
	}
},
```

Then when the plugin registers and we need to replace them, we only unregister one of them:

```
{
	"id": "2",
	"method": "textDocument/didChange"
},
// there is no 3!
{
	"id": "4",
	"method": "textDocument/completion"
},
{
	"id": "5",
	"method": "textDocument/hover"
},
```

Then we re-register:

```
{
	"id": "26",
	"method": "textDocument/completion",
	"registerOptions": {
		"documentSelector": [
			{
				"scheme": "file",
				"pattern": "**/*.dart"
			},
			{
				"language": "yaml",
				"scheme": "file",
				"pattern": "**/pubspec.yaml"
			},
			{
				"language": "yaml",
				"scheme": "file",
				"pattern": "**/analysis_options.yaml"
			},
			{
				"language": "yaml",
				"scheme": "file",
				"pattern": "**/lib/fix_data.yaml"
			}
		],
		"resolveProvider": true
	}
},
```

Since registration 3 was not removed, we end up with two Dart registrations, which results in VS Code asking for completions twice and the lists (which are identical) merged.

**Comment by DanTup** [comment]
This is fixed in the SDK by https://github.com/dart-lang/sdk/commit/f9512796e2f3531b177d63f3b75ec3a38c39435d and will show up in a future SDK release.
