### ISSUE TITLE
directives_ordering false positive

### ISSUE THREAD

**Issue by ManuLpz4** [Dart-Code/Dart-Code#3559]
**Describe the bug**
When you have ```package:flutter```and extenal packages the formatter forces you to mix them in a non

**To Reproduce**
Copy and paste the code below and save the file (or ```flutter analyze```to see the warning)
```dart
import 'dart:async';

import 'package:flutter/material.dart';

import 'package:firebase_core/firebase_core.dart';
```
**Expected behavior**
```dart
import 'dart:async';

import 'package:flutter/material.dart';

import 'package:firebase_core/firebase_core.dart';
```
**Result behavior**
```dart
import 'dart:async';

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
```

**Versions (please complete the following information):**
 - VS Code version: 1.60.0
 - Dart extension version: 3.26.0
 - Dart/Flutter SDK version: 2.5.0/2.14.0

**Comment by DanTup** [comment]
I believe this is the intended behaviour. [The lint](https://dart-lang.github.io/linter/lints/directives_ordering.html) says that `dart:` imports come first, then `package:` then path imports.

This is something controlled by the SDK - there's a related issue at https://github.com/dart-lang/sdk/issues/46597 but it sounds like the behaviour is based on the style guide (so the style guide might be the place to start a discussion about this).

Hope this makes sense!
