### ISSUE TITLE
VSCode autocomplete/suggestions/collapse/expand functionnalities missing

### ISSUE THREAD

**Issue by chamartt** [Dart-Code/Dart-Code#3560]
Hi,

I don't have any Dart suggestions when I ctrl+space and I cannot use collapse/expand functionnalities as the "brackets" (on the left of codes) are not even present.

I'm using VSCode 1.60 and Flutter 2.5.0.

When I use Flutter 1.22 with an old project builded with this version, everything it's ok. 
I also can use those functionnalities with this old project on Flutter 2.5.0 ; so the problem seems to come from my new project, which is running perfectly on physical device (except the automatic Hot Reload).

So it seems to be a configuration problem somewhere.

Here there is my user settings, so for all of my projects : 

```
{
    "workbench.startupEditor": "newUntitledFile",
    "update.mode": "none",
    "window.zoomLevel": 0,
    "window.smoothScrollingWorkaround": true,
    "git.autofetch": false,
    "liveshare.featureSet": "insiders",
    "workbench.iconTheme": "vscode-icons",
    "force.allowAnonymousUsageTracking": true,
    "peacock.favoriteColors": [
        {
            "name": "Angular Red",
            "value": "#b52e31"
        },
        {
            "name": "Auth0 Orange",
            "value": "#eb5424"
        },
        {
            "name": "Azure Blue",
            "value": "#007fff"
        },
        {
            "name": "C# Purple",
            "value": "#68217A"
        },
        {
            "name": "Gatsby Purple",
            "value": "#639"
        },
        {
            "name": "Go Cyan",
            "value": "#5dc9e2"
        },
        {
            "name": "Java Blue-Gray",
            "value": "#557c9b"
        },
        {
            "name": "JavaScript Yellow",
            "value": "#f9e64f"
        },
        {
            "name": "Mandalorian Blue",
            "value": "#1857a4"
        },
        {
            "name": "Node Green",
            "value": "#215732"
        },
        {
            "name": "React Blue",
            "value": "#00b3e6"
        },
        {
            "name": "Something Different",
            "value": "#832561"
        },
        {
            "name": "Vue Green",
            "value": "#42b883"
        }
    ],
    "explorer.confirmDelete": false,
    "vsicons.dontShowNewVersionMessage": true,
    "editor.minimap.enabled": false,
    "dart.sdkPath": "C:\\flutter\\bin\\cache\\dart-sdk",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "files.exclude": {
        "**/.classpath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/.factorypath": true
    },
    "git.enableSmartCommit": true,
    "[dart]": {
        "editor.formatOnSave": true,
        "editor.formatOnType": true,
        "editor.selectionHighlight": false,
        "editor.suggest.snippetsPreventQuickSuggestions": false,
        "editor.suggestSelection": "first",
        "editor.tabCompletion": "onlySnippets",
        "editor.wordBasedSuggestions": false
    },
    "dart.debugExternalLibraries": true,
    "dart.debugSdkLibraries": true,
    "files.associations": {
        "*.dart": "dart"
    },
    "dart.lineLength": 200,
    "dart.previewLsp": true,
    "diffEditor.ignoreTrimWhitespace": false,
    "javascript.updateImportsOnFileMove.enabled": "always",
    "editor.quickSuggestions": true,
}
```

Do you have any idea please?

Thank you in advance.

**Screenshots**
![2021-09-13_16h21_50](https://user-images.githubusercontent.com/15814545/133100881-68d55b9d-f04d-4821-950d-8e6bf4ed5b31.png)

**Versions :**
 - VS Code version: 1.60
 - Dart/Flutter SDK version: Flutter 2.5.0

**Comment by chamartt** [comment]
For workaround, I created a new sample project and manually copy/paste content and it works.

But it would be good to understand with is wrong with the initial project !

**Comment by DanTup** [comment]
Could you try enabling the [analyzer log file](https://dartcode.org/docs/logging/#analyzer) then close all VS Code instances, and open just the problematic project, then check if that log file records any errors?

(Don't forget to remove the log file setting afterwards, as it can grow quite large if you leave it enabled).

If that doesn't help, are you able to make a copy of your project and trim it down to something you could share (that still triggers the issue) for me to debug? Thanks!

**Comment by chamartt** [comment]
Hi @DanTup, 

I'm sorry but I removed the project when I resolved my issue.
