### ISSUE TITLE
VSCode on Linux: chrome web example does not work but works on command line

### ISSUE THREAD

**Issue by spicysomtam** [Dart-Code/Dart-Code#3562]
**Describe the bug**
Followed the official Flutter docs for setup (used tar archive and not snap). Followed the VSC example. It works with devices Linux, an android emulated device, but not with chrome. However if I run it from the command line, chrome works.

**To Reproduce**
1. Follow official docs for setup an editor (and then vsc).
2. Follow official docs for the test drive. Instead of using adb and a real andriod device, choose chrome from the bottom bar and then Run without debugging (or Run Start Debugging); both options are the same. 
3. If I open a bash shell in vsc and run from the command line it works perfectly: `flutter run -d console`

**Expected behavior**
VSCode run to be the same as the terminal run.

**Screenshots**

**Versions (please complete the following information):**
 - VS Code version: 1.60.0
 - Dart extension version: 2.14.0
 - Dart/Flutter SDK version: 2.5.0 (stable; tried dev, beta).
 - Linux Mint 20.2 (Ubuntu 20.04).
 - Chrome: 93.0.4577.82
 - Java: 1.8 openjdk

I switched on Dart logging, and got some output (see the screenshot). I have aload of logfiles; let me know any you want.
A screen pops up but suddenly closes.
![Screenshot from 2021-09-14 16-27-10](https://user-images.githubusercontent.com/1140932/133287300-f792cac4-6e93-4fa5-816e-03babd593158.png)

**Comment by DanTup** [comment]
There's an issue tracking this over at:

https://github.com/flutter/flutter/issues/73743

It appears to happen when _VS Code_ is installed via Snap. Installing VS Code from the .deb file seems to work for others. I don't think there's anything going wrong in the VS Code extension, I think it either needs fixing in Snap or Flutter, and then it should just start working.

**Comment by spicysomtam** [comment]
I did install via snap. Then removed the snap install (using 1.7Gb in my home dir!) and switched to the tarball install. It happens with the tarball as well.

**Comment by spicysomtam** [comment]
Update on this: Removed the snap version of vsc and then installed the deb and the issue is fixed. So for anyone else that experiences this vscode AND flutter needs to NOT use snap. Interestingly the deb vscode will setup the apt repo for you so you will get updates vai the channel. Also all you extensions and settings will be retained by the change from snap to deb.

**Comment by DanTup** [comment]
Yep, as noted above it depends on VS Code not just Flutter. I'm not familiar enough with Snap to understand what's going on, but the open Flutter issue above is the one to follow (which includes comments from a dev at Canonical that created some of the Snaps) as I don't believe it's something that can be fixed here (I suspect you'll see the same behaviour running from the built-in terminal in VS Code if installed via Snap, and the Dart-Code extension is not involved at all there). Thanks!
