### ISSUE TITLE
Allow Flutter UI Guides color adjustment

### ISSUE THREAD

**Issue by robertpiosik** [Dart-Code/Dart-Code#3564]
**Is your feature request related to a problem? Please describe.**
When indent lines are also grayish with similar lightness, its hard to distinguish them apart.

**Describe the solution you'd like**
Proper option field would be suitable.

**Comment by DanTup** [comment]
In the next version this colour can be customised through the `workbench.colorCustomizations` setting in VS Code:

```
"workbench.colorCustomizations": {
	"dart.flutterUiGuides": "#ff0000"
},
```

Thanks!
