### ISSUE TITLE
Highlight dart constructors and classes separate from each other.

### ISSUE THREAD

**Issue by tbm98** [Dart-Code/Dart-Code#3565]
in IntelliJ IDEA I can identify `Class` and `Constructor` like below
<img width="987" alt="Screen Shot 2021-09-16 at 09 31 41" src="https://user-images.githubusercontent.com/52562340/133539996-4edfc04b-d875-4aae-9083-18917b35e53a.png">
<img width="981" alt="Screen Shot 2021-09-16 at 09 30 59" src="https://user-images.githubusercontent.com/52562340/133540007-b73e3b64-0e6e-4a5d-b9e5-68052c18e9bd.png">
<img width="703" alt="Screen Shot 2021-09-16 at 09 39 13" src="https://user-images.githubusercontent.com/52562340/133540489-bf0bad47-1545-4de1-920c-546872464031.png">

but in vscode `Class` and `Constructor` have the same identify 
<img width="663" alt="Screen Shot 2021-09-16 at 09 36 45" src="https://user-images.githubusercontent.com/52562340/133540330-648cc301-a5d5-4630-9c86-8bd19de3d7fe.png">
it use 
```
{
			"name": "Types declaration and references",
			"scope": [
				"meta.return-type",
				"support.class",
				"support.type",
				"entity.name.type",
				"entity.name.namespace",
				"entity.other.attribute",
				"entity.name.scope-resolution",
				"entity.name.class",
				"storage.type.numeric.go",
				"storage.type.byte.go",
				"storage.type.boolean.go",
				"storage.type.string.go",
				"storage.type.uintptr.go",
				"storage.type.error.go",
				"storage.type.rune.go",
				"storage.type.cs",
				"storage.type.generic.cs",
				"storage.type.modifier.cs",
				"storage.type.variable.cs",
				"storage.type.annotation.java",
				"storage.type.generic.java",
				"storage.type.java",
				"storage.type.object.array.java",
				"storage.type.primitive.array.java",
				"storage.type.primitive.java",
				"storage.type.token.java",
				"storage.type.groovy",
				"storage.type.annotation.groovy",
				"storage.type.parameters.groovy",
				"storage.type.generic.groovy",
				"storage.type.object.array.groovy",
				"storage.type.primitive.array.groovy",
				"storage.type.primitive.groovy"
			],
			"settings": {
				"foreground": "#a9b7c6"
			}
		},
```

do you know any scope that identifies for `Constructor` or can you create one for it?

**Comment by DanTup** [comment]
To customise these, you'll need to use `editor.semanticTokenColorCustomizations`. For example:

```js
	"editor.semanticTokenColorCustomizations": {
		"rules": {
			"class.constructor": {
				"foreground": "#ff99ff",
			},
			"method.constructor": {
				"foreground": "#ff9999",
			}
		}
	},
```

`class.constructor` is used for the Classname-part of a constructor call, and `method.constructor` is used for constructor names:

<img width="1219" alt="Screenshot 2021-09-16 at 12 12 24" src="https://user-images.githubusercontent.com/1078012/133602206-e110c40b-ff3b-4d35-95a9-0b3c878cfe35.png">

Let me know if you have any issues getting this to work!

**Comment by tbm98** [comment]
Oh thank you. I'll report if have any issues :D

**Comment by tbm98** [comment]
Thanks. It works fine.
