### ISSUE TITLE
Unhandled exception breaks the editing in VS Code

### ISSUE THREAD

**Issue by orestesgaolin** [Dart-Code/Dart-Code#3566]
**Describe the bug**
When unhandled Flutter Exception happens, it breaks the editing capabilities e.g. you cannot delete text, use some shortcuts, and you can only type letters one by one.

**To Reproduce**
1. Cause rendering exception e.g. by putting SizedBox.expand() into SingleChildScrollView
2. Observe Flutter exception
3. Continue execution
4. Try to use [delete], [cmd] + [.] or some other shortcuts, observe they are not working
5. Use arrows, observe that they behave oddly e.g. by going to the left when [arrow up] is pressed

**Expected behavior**
Unhandled exception should not break the editing functionality

**Screenshots and logs**

https://user-images.githubusercontent.com/16854239/133573843-6400b2ff-fefe-4bf6-9f32-40ad8928a0d6.mp4

[flutter_log.txt](https://github.com/Dart-Code/Dart-Code/files/7175913/flutter_log.txt)

**Versions (please complete the following information):**
 - VS Code version: Version: 1.60.1
 - Dart extension version: v3.26.0
 - Dart/Flutter SDK version: 2.5.0
 - OS: macOS Big Sur 11.5.2

VS Code settings related to Dart

```json
{
    "dart.flutterSdkPaths": [
        "/Users/dominik/fvm/versions"
    ],

    "dart.previewFlutterUiGuides": true,

    "dart.previewFlutterUiGuidesCustomTracking": true,
    "dart.flutterSdkPath": "/Users/dominik/fvm/versions/stable",
    "editor.formatOnSave": true,

    "dart.debugExternalLibraries": true,
    "dart.debugSdkLibraries": false,
    "dart.flutterTestAdditionalArgs": [
        "-x presubmit-only"
    ],

    "dart.flutterRunAdditionalArgs": [
        "--vmservice-out-file=detective_connect.txt"
    ],
    "editor.codeActionsOnSave": [],
    "dart.previewLsp": true,

    "dart.debugExternalPackageLibraries": true,
    "dart.previewVsCodeTestRunner": true,
    "editor.bracketPairColorization.enabled": true
}
```

Flutter doctor

```
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-x64, locale pl-PL)
    • Flutter version 2.5.0 at /Users/dominik/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (8 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dominik/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dominik/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.5.2 20G95 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 93.0.4577.82

• No issues found!
```

**Comment by DanTup** [comment]
This seems to be a VS Code bug - extensions have no ability to affect the cursor in the editor and couldn't cause this behaviour even if they tried.

I can't reproduce it, but I've actually seen the behaviour you describe where the Up cursor key goes Left while working on Dart-Code itself. There's an open issue at https://github.com/microsoft/vscode/issues/119508 that I think is the same issue (which I've commented on before). If you ave a reliable repro for this, please check the comments at https://github.com/microsoft/vscode/issues/119508#issuecomment-880983675 from someone on the VS Code for a way to capture some more information that might help track it down.

Thanks!
