### ISSUE TITLE
Flutter Test - Compilation Failed and Error: Getter not found 'main'

### ISSUE THREAD

**Issue by martin-robert-fink** [Dart-Code/Dart-Code#3567]
**Describe the bug**

When I run the unit tests from the VSCode testing menu (Debug/Run in the code), all tests pass with no issues, but when I try to run the tests from the command line, I get the following error stream:

I should note, that if I run `flutter test <this file only>` on the command line, the tests pass fine.

It appears this error only happens when I run `flutter test` or `flutter test <folder with many test files>`

I tried capturing debug logs, but nothing gets captured for command line runs.

```bash
mfink@MacBook-Pro fpga_view % flutter test test/windows/waveform_window
00:08 +0: loading /Users/mfink/Dropbox/Developer/Flutter/fpga_view/test/windows/waveform_window/signals_list_view/signals_list_view_test.dart                                       /var/folders/rz/j5b7hy3j2fb1gqmf9c0l1tc40000gn/T/flutter_tools.yCatAs/flutter_test_listener.V29HgB/listener.dart:20:21: Error: Getter not found: 'main'.
  await Future(test.main);
                    ^^^^
00:09 +0 -1: loading /Users/mfink/Dropbox/Developer/Flutter/fpga_view/test/windows/waveform_window/signals_list_view/signal_list_view_item/signal_list_view_item_details/connections_indicator/connections_indicator_test.dart [E]
  Failed to load "/Users/mfink/Dropbox/Developer/Flutter/fpga_view/test/windows/waveform_window/signals_list_view/signal_list_view_item/signal_list_view_item_details/connections_indicator/connections_indicator_test.dart": Compilation failed for testPath=/Users/mfink/Dropbox/Developer/Flutter/fpga_view/test/windows/waveform_window/signals_list_view/signal_list_view_item/signal_list_view_item_details/connections_indicator/connections_indicator_test.dart
00:09 +0 -2: loading /Users/mfink/Dropbox/Developer/Flutter/fpga_view/test/windows/waveform_window/signals_list_view/signals_list_view_test.dart [E]                                
  Exception: the Dart compiler exited unexpectedly.
  package:flutter_tools/src/base/common.dart 10:3  throwToolExit
  package:flutter_tools/src/compile.dart 778:9     DefaultResidentCompiler._compile.<fn>
  dart:async/zone.dart 1436:47                     _rootRunUnary
  dart:async/zone.dart 1335:19                     _CustomZone.runUnary
  
/var/folders/rz/j5b7hy3j2fb1gqmf9c0l1tc40000gn/T/flutter_tools.yCatAs/flutter_test_listener.uoCeNW/listener.dart:20:21: Error: Getter not found: 'main'.
  await Future(test.main);
                    ^^^^
00:10 +0 -3: loading /Users/mfink/Dropbox/Developer/Flutter/fpga_view/test/windows/waveform_window/signals_list_view/signal_list_view_item/signal_list_view_item_details/connections_indicator/active_connections_number_test.dart [E]
  Failed to load "/Users/mfink/Dropbox/Developer/Flutter/fpga_view/test/windows/waveform_window/signals_list_view/signal_list_view_item/signal_list_view_item_details/connections_indicator/active_connections_number_test.dart": Compilation failed for testPath=/Users/mfink/Dropbox/Developer/Flutter/fpga_view/test/windows/waveform_window/signals_list_view/signal_list_view_item/signal_list_view_item_details/connections_indicator/active_connections_number_test.dart
00:10 +0 -3: loading /Users/mfink/Dropbox/Developer/Flutter/fpga_view/test/windows/waveform_window/signals_list_view/signals_list_view_test.dart [E]                                
  Exception: the Dart compiler exited unexpectedly.
  package:flutter_tools/src/base/common.dart 10:3  throwToolExit
  package:flutter_tools/src/compile.dart 778:9     DefaultResidentCompiler._compile.<fn>
  dart:async/zone.dart 1436:47                     _rootRunUnary
  dart:async/zone.dart 1335:19                     _CustomZone.runUnary
  
00:28 +174 -3: Some tests failed.                                                                                                                                                   
mfink@MacBook-Pro fpga_view % 
```

**To Reproduce**

Difficult for me to provide.  I have a test suite with 770 unit tests and this only happens on some of them.  In the stream above, 3 out of 177 tests fail.

**Expected behavior**

Flutter tests run without these errors

**Screenshots**

**Versions (please complete the following information):**
 - VS Code version:
 - Dart extension version:
 - Dart/Flutter SDK version:

```bash
mfink@MacBook-Pro ~ % flutter doctor -v
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.6 20G165 darwin-arm, locale en-US)
    • Flutter version 2.5.0 at /Users/mfink/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (9 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mfink/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 93.0.4577.82

• No issues found!
```

**Comment by DanTup** [comment]
It's difficult to offer any advice without a repro or code for this (for ex. it's not clear what `test.main` is in the failing code). I would suggest trying to cut it down to a small shareable project that triggers the issue.

That said, if everything works fine through VS Code and this happens at the terminal, it's not going to be possible to fix here (this repo is for the VS Code extension, and that can't affect commands running in the terminal). If there's a bug it will need to be raised/fixed at https://github.com/flutter/flutter/ - though I'd recommend making the small shareable repro first so they can easily debug it. Thanks!

**Comment by martin-robert-fink** [comment]
Hi Danny -

Thanks for looking at this.  I knew that my bug submission was poor in form.  My apologies for that.  I was really looking for ways where I can troubleshoot and isolate.  Since this is happening on 3 of 770 tests, there's almost no way for me to cut this down and figure out a way to duplicate it.  I also can't find a way to run any other troubleshooting or debug tool to isolate either.

I guess I'm going to have to live with it for now, and at some point I may try to re-create the project from scratch, and copy everything over and see if the problem persists.  At least, that's all I can think of.

I don't know if it's related to this issue, but the testing infrastructure refuses to load ANY tests unless I do a `flutter clean` first.  As soon as I build/run my app, the tests will no longer run until I do a `flutter clean`.

Maybe I just have something corrupted somewhere in there.

**Comment by DanTup** [comment]
@martin-robert-fink my suggestion would be to make a copy of your project and then slowly delete code until you have a small repro. If 767 tests do not experience this, I would expect that you could delete them all and still have three that reproduce it. Then you could try deleting as much of the implementation of those tests as you can that still preserve the issue, and ultimately as much of your implementation (non-test) code.

If at some point along the way the issue disappears, you may have found the cause of it (and either know that it's a bug, and how to easily reproduce it, or that it was not a bug and what the problem was in your code). If not, then you should have an easily shareable repro.

Unfortunately it's very difficult to blindly debug a compile error without seeing the code generating the error.

> the testing infrastructure refuses to load ANY tests unless I do a `flutter clean` first. As soon as I build/run my app, the tests will no longer run until I do a `flutter clean`.

I'm not sure if it's related, but that certainly sounds like another issue. Again, if you can reduce it to a repro that you can share then it would be much easier for people to help debug.

Hope this helps!
