### ISSUE TITLE
`part` and `part of` generator

### ISSUE THREAD

**Issue by EhsanAramide** [Dart-Code/Dart-Code#3579]
Hi maintainers!

**actually I didn't find a similar issue if exists sorry for duplication**

I was working on my package which I should have used
```dart
part 'path/to/file.dart';
part of '../../path/to/invoked_lib.dart';
```
many time.
I consider it is very good to add a feature to the extension's code generator part to create `part of` in the part file and has a relation path to the library.

the usage which I have considered about it would be like:
1. write `part 'path/to/file.dart';`
2. then the extension with the use of the quick fix detect the target file and a choice to generate code.
3. and finally after choosing that quick fix choice the extension generate `part of` code for that file

**Example**:
```dart
// this is main lib;
part 'path/to/file.dart';
// then beside of errors provides a quick fix which is `generate part of` or something like this
```
_Aftter choosing quick fix_
```dart
// in the target file
part of '../../main_lib.dart';
// this will generate automatically by extension
```

**Comment by DanTup** [comment]
Can you confirm what version of the SDK you're using? This should already work now:

![Sep-28-2021 14-43-07](https://user-images.githubusercontent.com/1078012/135098886-c3ecd8a5-939a-4f94-882d-3fab90342def.gif)

It was requested at https://github.com/Dart-Code/Dart-Code/issues/3268 and I believe should have been included in the most recent stable releases of the SDKs.

**Comment by EhsanAramide** [comment]
I use dart 2.13.0
Thank you, I think I should upgrade my dart sdk

**Comment by EhsanAramide** [comment]
I updated my SDK.
The only difference between our discussion is you said that it is implemented before and you can use it so I use but it works just for files that don't exist, what I said is that works for existing files too.
Do think this would be a good idea to add another feature to the extension which transforms a file into the `part of` files?

**Comment by DanTup** [comment]
I think it's a fair request. The best place to raise it would be at https://github.com/dart-lang/sdk as the work will need to be done in the analysis server (unlike the change above which was just a simple change, this would likely need to be a new code fix which is a little more involved and would likely be prioritised against other suggestions).

If you do file an issue there, please post the link back here for anyone that finds this issue and wants to go 👍  it. Thanks!
