### ISSUE TITLE
Get rid of const keyword in static widget

### ISSUE THREAD

**Issue by mayura33** [Dart-Code/Dart-Code#3581]
**Getting message "Prefer const literal as parameter of constructor on @Immutable classes**

Create simple widget in flutter getting above warning after upgrade to Flutter 2.5 Update

For above problem I add "prefer_const_constructors : false" in analysis_options.yaml
and run dart fix command from terminal.

**Expected behavior is Should not get above warning**

**Screenshots**
![image](https://user-images.githubusercontent.com/33602207/135065521-7b9edf5d-811d-446b-bca7-14edd171e15c.png)

**Versions (please complete the following information):**
![image](https://user-images.githubusercontent.com/33602207/135065598-6d4d41de-4a8e-4fec-b7aa-ee82fa4ba1a0.png)

**Comment by DanTup** [comment]
@mayura33 does your `analysis_options.yaml` file include `include: package:flutter_lints/flutter.yaml`? If so, you'll be getting the standard Flutter lints, and that includes `prefer_const_constructors_in_immutables` (see https://github.com/flutter/packages/blob/master/packages/flutter_lints/lib/flutter.yaml).

In that case, I believe this is working as expected. If you don't want to use the standard Flutter lints, you can remove the reference to the `flutter_lints` package.

**Comment by mayura33** [comment]
Hello, @DanTup I did changes accordingly you said, and it's working as expected.!
Thanks
