### ISSUE TITLE
feat: hook

### ISSUE THREAD

**Issue by jjangga0214** [Dart-Code/Dart-Code#3587]
**Is your feature request related to a problem? Please describe.**
I want to run custom command(code generation) automatically before debugging.
My vscode configuration is like an example below, and I couldn't find the solution.

```json
    {
      "name": "flutter(main)",
      "request": "launch",
      "type": "dart",
      "flutterMode": "debug",
      "cwd": "frontends/main",
    }
```

**Describe the solution you'd like**
Maybe adding lifecycle hook from configuration?

```json
    {
      "name": "flutter(main)",
      "request": "launch",
      "type": "dart",
      "flutterMode": "debug",
      "cwd": "frontends/main",
      "prebuild" : "bash ./my-code-gen.sh"
    }
```

**Comment by DanTup** [comment]
This is already supported natively by VS Code. You'll need to create a Task for your command (which lets you configure many things, including regexes to detect when it reports errors), for example in `.vscode/tasks.json`:

```js
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "My Task",
			"type": "shell",
			"command": "echo Hello",
			"problemMatcher": []
		}
	]
}
```

Then in `launch.json` use VS Code's built-in `preLaunchTask`:

```js
{
	"configurations": [
		{
			"name": "Dart (bin/tasktest.dart)",
			"type": "dart",
			"request": "launch",
			"program": "bin/tasktest.dart",
			"preLaunchTask": "My Task" // This must match the Label in tasks.json
		}
	]
}
```

Hope this helps!
