### ISSUE TITLE
Stop or Disconnect is not working.

### ISSUE THREAD

**Issue by yahu1031** [Dart-Code/Dart-Code#3588]
**Describe the bug**
Whenever I try to stop/disconnect the process, It shows it was exited in debug console but it still shows a notification stating `Terminating debug session…` forever and the debug tools still show.

**To Reproduce**
1. Create a sample dart console application.
2. config the project with the below `launch.json` code.
```json
{
    "configurations": [
        {
            "name": "Dart",
            "type": "dart",
            "request": "launch",
            "program": "bin/at_bot.dart"
        }
    ]
}
```
3. Write something which will keep listening. Try [nyxx package](https://pub.dev/packages/nyxx) for a sample discord bot.
4. Now try stopping/disconnecting the bot.

**Expected behavior**
The process/launch must disconnect/stop by stating `Exited (1)` in debug console.

**Screenshots**
![image](https://user-images.githubusercontent.com/35523357/135765576-cc649ee9-538e-4e19-a2a7-692cb60904ee.png)

**Versions (please complete the following information):**
 - VS Code version: 
 ```
 Version: 1.60.2 (user setup)
 Commit: 7f6ab5485bbc008386c4386d08766667e155244e
 Date: 2021-09-22T12:00:31.514Z
 Electron: 13.1.8
 Chrome: 91.0.4472.164
 Node.js: 14.16.0
 V8: 9.1.269.39-electron.0
 OS: Windows_NT x64 10.0.22000
 ```

 - Dart extension version:
 ```
 Dart v3.26.0
 ```

 - Dart/Flutter SDK version:
 ```
 Flutter 2.5.2 • channel stable • https://github.com/flutter/flutter.git
 Framework • revision 3595343e20 (3 days ago) • 2021-09-30 12:58:18 -0700 
 Engine • revision 6ac856380f
 Tools • Dart 2.14.3
 ```

**Log Files**
[Dart-Code-Log-2021-09-00 23-17-01.txt](https://github.com/Dart-Code/Dart-Code/files/7274283/Dart-Code-Log-2021-09-00.23-17-01.txt)

**Comment by DanTup** [comment]
I'm not able to reproduce this using the sample code form that project, the session seems to end fine:

<img width="1792" alt="Screenshot 2021-10-04 at 11 03 37" src="https://user-images.githubusercontent.com/1078012/135832623-551c0b18-af21-48b4-9c5a-68b6c5d48976.png">

Can you test with the exact same code I used above (and using v2.0.2 of nyxx) to see whether it's something specific to your project?

Could you also try:

- Disable all VS Code extensions besides Dart/Flutter to see if that changes anything
- Click Help -> Toggle Developer Tools in VS Code, then go to the Console tab to see if there are any errors listed when this occurs

From the log file, it seems that the `terminated` event is being sent to VS Code:

```
{"seq":735,"type":"event","event":"output","body":{"category":"console","output":"Exited (1)\n"}}
{"seq":736,"type":"event","event":"terminated"}
```

This should cause VS Code to end the session and hide the toolbar, and also fire the event that would complete the "Terminated Debug Session..." notification.

**Comment by yahu1031** [comment]
This is fixed with the latest version of the extension I guess now I'm not getting the error.
