### ISSUE TITLE
Unable to figure out how to run all tests

### ISSUE THREAD

**Issue by aiurovet** [Dart-Code/Dart-Code#3590]
**Describe the bug**

I'm unable to figure out how to run all tests with Dart Code 2.37.0

**To Reproduce**

1. Open a folder with Dart project with multiple tests.
2. Click 'Testing' icon
3. See the message 'No tests have been found in this workspace yet' and the button 'Find Test Extensions'
4. If I choose any test file, I can only run tests within that file.

**Expected behavior**

A list of all tests.

**Versions**

 - VS Code: 1.60.2
 - Dart extension: 2.37.0
 - Dart SDK: 2.14.2, then upgraded to 2.14.3
 - Flutter SDK: 2.5.1, then upgraded to 2.5.2 (not used for the current project)

**Comment by dballance** [comment]
I asked in discord - and the short answer is that you should be able to bring up the command panel and select "Dart: Run All Tests" to populate the Test Runner panel. This is functionally the same result from the older testing panel - which ran the tests via dart and used that to populate the test panel.

![image](https://user-images.githubusercontent.com/1234523/136058470-4f5a9d93-f0b6-450d-864a-7d79660899db.png)

This worked for me but the discussion was also about what could be better - so I'm going to file an issue related to test discovery as well.

**Comment by ErkinKurt** [comment]
It works extremely buggy. Widget tests are not executed as well.

**Comment by aiurovet** [comment]
Thanks a lot, @dballance. At least, something. Still, it would be much better not to drop existing features like a dedicated button to run all tests. I hope that the developers will get it back, but bug fixes are obviously the priority.

**Comment by DanTup** [comment]
Sorry for the confusion. The way to run all tests has always been via the **Dart: Run All Tests** command. However in the previous test runner, there was a button at the top of the test runner that invoked this command. VS Code's test runner has a similar button but it only runs the tests VS Code knows about (those that have already been discovered).

There are some open issues (#3591 and #3594) that will improve things in this area. In the meantime, if you'd like to use the old test runner you can switch back with this setting (though note that this setting and the legacy test runner will be completely removed in an upcoming release - though the issues mentioned will be fixed before that happens):

<img width="804" alt="Screenshot 2021-10-06 at 10 29 17" src="https://user-images.githubusercontent.com/1078012/136177222-c57fadc6-7931-4fab-b19b-3c37177fd719.png">


@ErkinKurt 

> It works extremely buggy. Widget tests are not executed as well. Downgraded!

If you're able to file an issue with some more details, I'd love to try and fix the problems you're seeing.


@aiurovet 

>  it would be much better not to drop existing features like a dedicated button to run all tests

Apologies - this was an oversight on my part. I tend to use the command palette myself and overlooked that the "Run Tests" button in the VS Code runner was doing something different (in the new runner, VS Code handles a lot more of the functionality, so many of the commands that were invoked previously are bypassed, so the functionality isn't 100% the same).

Once #3594 is fixed, the "Run Tests" button at the top of the toolbar should work the same as **Dart: Run All Tests** used to.

**Comment by aiurovet** [comment]
Thanks a lot, @DanTup, I'm new to VS Code, so I forgot about the command palette. It's good enough for the time being. Another inconsistency I found today: when clicking or double-clicking any test, it does not open the test source, and I have to do that via right mouse click only. However, I can't run tests if I do right mouse click on any test file in the sidebar, so it feels asymmetric. But again, both of these are nice-to-have features compared to bug fixing.

**Comment by johnnypcc** [comment]
> Another inconsistency I found today: when clicking or double-clicking any test, it does not open the test source, and I have to do that via right mouse click only

Yes, there should be a bug open for this, it is annoying and counterintuitive.

**Comment by aiurovet** [comment]
Thank you, @DanTup, will do that.

**Comment by aiurovet** [comment]
Sorry, it looks like Run All Tests (as well as Debug All Tests) in the command pallette are broken (v3.29.0). When choosing one of those options, only the latest tests are re-run (otherwise, complaining about finding the tests at all). This time, however, when choosing the Unit Tests screen and clicking the double-play button, everything works as expected.

**Comment by DanTup** [comment]
@aiurovet I don't seem to be able to reproduce this, can you give a detailed example of what you're doing and seeing? I ran a single file from the test runner, then ran "Run All Tests" and it ran everything.

Although it's worth noting that Run All Tests is now a built-in command (from VS Code) so we're not handling this directly. It superseded the **Dart: Run All Tests** command and might have slight differences in how it behaves (for example, it might take into account filters or hidden tests in the text runner).

**Comment by johnnypcc** [comment]
@DanTup  I see something similar to what @aiurovet says.
I just loaded a project, the tab of a unit test was active, so I run Test: Run All Tests, and only that test was run.
Then I clicked on the "double play" Run Tests button, and I got an error in the console saying 

`Integration tests and unit tests cannot be run in a single invocation. Use separate invocations of `flutter test` to run integration tests and unit tests.`

Yes, I do have integration tests, but this failure to run when they exist makes this feature pretty useless, I can't use it.

After that, I clicked the "Debug Tests" button (next to the   "double play" Run Tests button) and that started to run tests one by one. Very slowly. When I wanted to stop the execution, clicked the stop button, nothing happened. It looked as if I was just stopping the currently running test, but then the next one was run, etc. I even saw a line saying "Running pod install...                                           2,793ms, Running Xcode build...                                          
Xcode build done.",  clicked the stop button again, it went away.

I miss the 'Dart: Run all tests" command. Can we have it back please?

**Comment by aiurovet** [comment]
@DanTup, @johnnypcc, sorry for the late response. My situation is a bit of the opposite: when clicking a double-play button under the _Unit Tests_ tab, everything works as expected. When using _Command Palette_, I can execute _Test: Run All Tests_, but it does not work (either says it can't find any test or runs the previously executed specific one). However, I do not see the command _Dart: Run All Tests_.

OS version: Kubuntu 21.10 (64-bit)
Dart SDK version: 2.14.4
Flutter is not installed.
VS Code version: 1.62.3
Dart Plugin version: 3.29.0
Flutter Plugin version: 3.29.0 (possibly, bundled with Dart Plugin).

**Comment by DanTup** [comment]
@johnnypcc I'm not sure I completely understand your description - could you file a new issue with clear steps on how I can reproduce the error you're getting so I can take a look?

> I miss the 'Dart: Run all tests" command. Can we have it back please?

There is a built-in command for **Test: Run All Tests** so it doesn't make sense to have our own. If the built-in command is not doing what is expected, then it needs to be fixed. It would be confusing to have two similarly-named commands that do different things (one of which is not what the user expects).

FWIW, I fixed a few testing-related issues today (although I'm not certain any are related to this):

- #3712
- #3713
- #3714

**Comment by DanTup** [comment]
@aiurovet 

> When using Command Palette, I can execute Test: Run All Tests, but it does not work (either says it can't find any test or runs the previously executed specific one). 

I think the first issue (saying it can't find any tests) is #3714 which I've just fixed (but not released). The second sounds a bit like #3708 but that's about the **Re-run last test** command. If you're seeing **Test: Run All Tests** run the wrong tests, can you provide steps to reproduce?

**Comment by DanTup** [comment]
@johnnypcc 

> After that, I clicked the "Debug Tests" button (next to the "double play" Run Tests button) and that started to run tests one by one. Very slowly. When I wanted to stop the execution, clicked the stop button, nothing happened.

There is a limitation that prevents us running multiple tests suites _in debug mode_ in a single session. This means "debug all tests" can be much slower than "run all tests". This has always been the case and the old command doesn't get around this.

I have some thoughts about what might cause the Stop button not to work correctly in this mode, but can you verify the exact steps in a new issue so I can be sure I fix exactly the case you're seeing? Thanks!

**Comment by DanTup** [comment]
If there are still any outstanding issues after the fixes above and the latest release, please file new issues with details. Thanks!
