### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by eben98** [Dart-Code/Dart-Code#3592]
- Issue Type: `Bug`
- Extension Name: `dart-code`
- Extension Version: `3.27.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VS Code version: `1.60.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by DanTup** [comment]
> ⚠️ We have written the needed data into your clipboard. Please paste! ⚠️

Are you able to provide this information? Thanks!
