### ISSUE TITLE
Possible test detection issue

### ISSUE THREAD

**Issue by guidezpl** [Dart-Code/Dart-Code#3610]
As of a few days ago, my tests aren't detected individually, nor are groups. The tests are in a top-level `test` directory

**To Reproduce**
N/A

**Expected behavior**
Tests can be run by group, or individually. Tests can also be run from the Testing pane.

**Screenshots**
<img width="1368" alt="Screen Shot 2021-10-12 at 10 50 18" src="https://user-images.githubusercontent.com/6655696/136979081-8d8574d5-8b7d-475a-b78c-802b8c02d7ab.png">

**Versions (please complete the following information):**
 - VS Code version: 1.61.0 (Universal)
 - Dart extension version: v3.27.2
 - Dart/Flutter SDK version: 2.6.0-12.0.pre.274

**Comment by DanTup** [comment]
Great! If it worked like this before, it was likely accidental. I try to keep the test detection roughly inline with what `dart test` does to avoid confusion with files being mis-detected differently (for example some people have test files outside the test folder, and others have `foo_test.dart` scripts that are just testing code but not actual tests).
