### ISSUE TITLE
While linting, I'm getting an error on excellent code.

### ISSUE THREAD

**Issue by ghost** [Dart-Code/Dart-Code#3612]
Hey, I'm curious as to how this is even feasible.
Is this a bug?

![Screenshot 2021-10-14 112616](https://user-images.githubusercontent.com/16564273/137349071-9706c463-db0e-4d24-a6e7-4274735f16a0.png)

**Comment by bleroux** [comment]
@Prajwal-Koirala 
This lint has been fixed very recently, see https://github.com/dart-lang/linter/pull/3022
DartCode relies on Dart SDK analyzer for those warnings, you can find the corresponding issue there : https://github.com/dart-lang/linter/issues/453

**Comment by DanTup** [comment]
@bleroux thanks!
