### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Ariful-Git** [Dart-Code/Dart-Code#3616]
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `3.27.2`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.61.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\Admin\AppData\Local\Temp\Dart-Code.dart-code-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by DanTup** [comment]
> ⚠️ Make sure to attach this file from your home-directory:
> ⚠️c:\Users\Admin\AppData\Local\Temp\Dart-Code.dart-code-unresponsive.cpuprofile.txt

Are you able to attach this file? Thanks!
