### ISSUE TITLE
Subscribe to analysis.navigation for visible editors and use the results for instant navigation

### ISSUE THREAD

**Issue by JoeyScarr** [Dart-Code/Dart-Code#3620]
In my company's codebase, code navigation is intolerably slow, to the point where most devs just use global find instead of the jump-to-def/find-all-references functionality.

Is there some reason why Dart-Code doesn't subscribe to `analysis.navigation` events from the language server? FWIW Dart for Webstorm does this and uses the results for code navigation, making it instant.

I have a hacked up version of Dart-Code locally that does this and it vastly improves the experience for me. Happy to send a PR if anyone's interested (though it's not very hard to implement).

**Comment by JoeyScarr** [comment]
Thanks for the quick response!

> Also - can you clarify if both of these are slow, or just find-refs? My understanding is that the navigation event only provided the information required for Go-to-Definition, so I wouldn't expect to be able to improve Find-References with it - is that incorrect?

Ah, you're right. It's only Go to Definition that's improved by this.

> By default, Dart-Code now uses LSP and not the original server protocol (if you set dart.previewLsp: false it will use the original protocol, but that will be removed in the future). This means the navigation needs to go via the server.

To provide some context, we're still stuck on Dart 1 for the short-medium term, hence we can't use the LSP yet.

I'll have to get back to you once I figure out how to provide a repro+trace that's both useful and shareable, but another piece of information that might be useful is we have a gencode library that has ~900 parts. It used to be one big file and we recently split it up -- performance was bad before but now it's even worse. It seems like the analysis server is constantly re-analyzing, even though nothing in the giant library is changing.

It's possible that the situation might improve if we split up the gencode into individual pieces that must be imported separately, and/or if we switch to Dart 2 and use newer versions of the analysis server, but both of those are a significant chunk of work. If you have any other ideas for short-term improvement, let me know.

FWIW, my suggested approach in the OP helps mitigate the situation somewhat, but it's still pretty bad as soon as one of the gencode files is opened; it seems that triggers the analyzer to keep analyzing forever.

**Comment by JoeyScarr** [comment]
Sent a PR: https://github.com/Dart-Code/Dart-Code/pull/3649

Not sure if it's the cleanest solution but will leave up to your judgement whether it's mergeable or not.

**Comment by DanTup** [comment]
Fixed by #3649. Thanks!
