### ISSUE TITLE
Support intellisense quick-fix for `unawaited_futures` linter rule from `dart:sync`

### ISSUE THREAD

**Issue by om-ha** [Dart-Code/Dart-Code#3623]
#### Issue summary
- `dart:sync` has `unawaited` keyword. There is a related `unawaited_futures` linter rule that is reported correctly within VSCode.

- The core issue/missing feature is that VSCode intellisense does not support providing a quick-fix (`⌘+.`/`CTRL+.`) for this linter warning.

#### Issue description
- As [`unawaited_futures` linter rule](https://dart-lang.github.io/linter/lints/unawaited_futures.html) explains:

> DO await functions that return a Future inside of an async function body.
> 
> It is easy to forget await in async methods as naming conventions usually don't tell us if a method is sync or async (except for some in dart:io).
> 
> When you really do want to start a fire-and-forget Future, the recommended way is to use unawaited from dart:async. The // ignore and // ignore_for_file comments also work.

#### Issue importance
- This is a very important linter warning, because if a developer forgets to await a future inside an async body call, then unexpected  side-effects happen. This could simply and dangerously be triggered by converting a sync function to an async/Future-returning function within an API implementation. Without this linter rule API users would not notice they need to await this now-async function in their async user functions.

- This linter rule is correctly reported by VSCode but has no accompanying quick-fix.

## **Describe the solution you'd like**
- Provide a quick-fix (`⌘+.`/`CTRL+.` -> `editor.action.quickFix`) for `unawaited_futures` linter rule warning.
- This quick-fix would replace unawaited future expressions like this: `expression` -> `unawaited(expression)`
- Optionally this would work with `editor.action.FixAll / edit.fixAll` and `editor.action.autoFix`

## **Describe alternatives you've considered**
🤷‍♂️

## **Additional context**
- Related issue from `dart-lang/language` [#1652](https://github.com/dart-lang/language/issues/1652#issuecomment-925631485) where I first mentioned lack of quick-fix.
- Add `unawaited_futures` linter rule in `analysis_options.yaml`:
```yaml
linter:
  rules:
    unawaited_futures: true
```
- Observe corresponding warning being correctly reported by VS Code:
![warning](https://user-images.githubusercontent.com/30494124/137738340-26976fc0-ca89-449b-b902-b45c57831c5d.png)
- Observe there is no quick-fix for this warning to resolve it:
![quick_fix](https://user-images.githubusercontent.com/30494124/137738379-ceb9b68f-c36e-4a7a-ab87-962ddb4fb3a7.png)

**Comment by DanTup** [comment]
Thanks for the suggestion! These code actions actually come from the language server so this would need implemented there in SDK. It turns out there's already an open issue about this here you can subscribe to / 👍  :

https://github.com/dart-lang/sdk/issues/34431

> Optionally this would work with editor.action.FixAll / edit.fixAll and editor.action.autoFix

I'm not sure this fix would be suitable for auto-fixing, as it's not clear whether the correct fix is to add `await` or to add `unawaited`, and the Fix All functionality (which is just a wrapper over `dart fix`) tends to only make changes where there's a single obvious fix, but here I think a user would want to review each case and make a decision on the correct fix individually.
