### ISSUE TITLE
Allow customisation of closing label prefix and font/size

### ISSUE THREAD

**Issue by twoco** [Dart-Code/Dart-Code#3628]
Please allow to change the character and / or other styles of the closing labels I see in VS Code. 
Currently they look like comments. This triggers me. 

For example change the `//` slashes to `#` hashtag or `/` single slash or `-` minus, etc..  (just an user input)
Or nothing. I don't think the syntax matters. No need for slashes.
Changing the color and / or opacity would be also great.

Setting: `dart.closingLabels`

![image](https://user-images.githubusercontent.com/53160891/138522493-b016900a-e9bd-46da-8e1a-cf90408f8874.png)

**Comment by infacto** [comment]
The close label indicator feature is great, but it's really annoying that it's hard to distinguish from real comments.

My current workaround is adding this to *settings.json*:

```json
{
  "workbench.colorCustomizations": {
    "dart.closingLabels": "#80808040"
  }
}
```

If we add an option to customize the text, I would suggest prefix and suffix. To allow something like `-- Text` an `(Text)` etc. Or just something like `"dart.closingLabelsString": "/* $1 */"` But only a suffix is also great. Maybe other style can also help. Like font-size? Idk. Just separate from real comments. Or improve Dart / Flutter design making closing labels annotations unnecessary. ...

**Comment by gazialankus** [comment]
> Like font-size? Idk.

YES. See the inlay hints with the small font size? I would love it if I can get these closing labels to look the same. Then my eyes can group them similarly as *not real code but suggestions*. I really like this small font size for the inlay hints, so I'm pretty sure it will work perfectly for me if I can change the font. 
<img width="416" alt="image" src="https://github.com/Dart-Code/Dart-Code/assets/412997/83ad5dce-694a-40f0-982a-47381307117d">

For anyone wondering, here are the settings for the inlay hints: 
```
    "[dart]": {
        "editor.inlayHints.enabled": "on",
        "editor.inlayHints.fontSize": 8,
        "editor.inlayHints.padding": false,
        "editor.inlayHints.fontFamily": "Arial", 
```

**Comment by DanTup** [comment]
I think it's a fair request to be able to customise these further and would accept PRs to do this. The styling is handled here:

https://github.com/Dart-Code/Dart-Code/blob/1ee5959ff4d68510b0c03bbbe1ee971b61d614ca/src/extension/lsp/closing_labels_decorations.ts#L15-L18

And the prefix is handled here:

https://github.com/Dart-Code/Dart-Code/blob/1ee5959ff4d68510b0c03bbbe1ee971b61d614ca/src/extension/lsp/closing_labels_decorations.ts#L78-L86
