### ISSUE TITLE
Support URLs and paths in Add Dependency command

### ISSUE THREAD

**Issue by EhsanAramide** [Dart-Code/Dart-Code#3635]
I am using `v3.27.2` of the extension and I searched for a similar issue but I didn't find anything related.

Currently, the auto-completion about dependencies just works in `pubspec.yaml` but I think it can be better to add the dependencies in import (for tired guys can be the best solution).

At this time the process for using a package is: (expect its kind - local, hosted on pub server or as a dev dep)
1. Adding dependencies in `pubspec.yaml`
2. Runnin `pub get` to fetch the package and other related configs
3. import it and use it

But I suggest a new way (_I am not sure this feature can be implemented in extension or not let me know_).
For example, we want to add a dependency in the `dependency` section in `pubspec.yaml` what we should do is:
1. import the package with this syntax `import 'dep:<package_name | git_remote_repo | local/path/to/package>';` auto completion works as same logic as used in `pubspec.yaml` (with some modification)
2. `crtl + .` click on `fetch package`
3. then `pub add <package_name> --<associated_switch>` will run and do all configurations

Note: as dev dependency we can use `import 'dev:<package_name | git_remote_repo | local/path/to/package>';`

**Comment by DanTup** [comment]
sgtm, I'll do that. Thanks!

**Comment by EhsanAramide** [comment]
Me too. You can cound on me in feature implementation (I am not a TS expert but I can do some stuff with it😅🌹)

**Comment by DanTup** [comment]
You're welcome to have a go if you want :-)

The way I was thinking it would work is that we insert two new items in the picklist, one for URLs and one for paths. Select the path option would open the folder picker and let you browser to the folder, and picking URL would just give an input box that is validated as a URL. Then the results just get passed to `pub add` the same way the package name would.

**Comment by EhsanAramide** [comment]
Thank you a lot for your response I will try to implement it on my forked repository based on contribution guidlines. I just wanted to aware you to avoid conflict.

**Comment by DanTup** [comment]
@EhsanAramide are you still working on this? There's no rush, but if you don't have time I'm happy to try to finish it off for the upcoming release.

**Comment by EhsanAramide** [comment]
Thank you to make me notify, Yes as you said unfortunately I don't have time these days, I am sorry about it.💙🌹🌹

**Comment by DanTup** [comment]
@EhsanAramide it's not problem at all, I understand how things are. I'll work on this for the next release - thank you for your effort in starting this though! :-)
