### ISSUE TITLE
Icons preview not shown on hover 

### ISSUE THREAD

**Issue by maheshmnj** [Dart-Code/Dart-Code#3641]
**Describe the bug**
Hovering on a icon does not show icon Preview

**To Reproduce**
1. Add icon to widget tree in vscode 
2. Hover mouse cursor on the icon

**Expected behavior**
Icon preview should be visible

**Actual behavior**
Icon preview is not shown

**Screenshots**

<img width="507" alt="Screenshot 2021-10-29 at 1 23 28 PM" src="https://user-images.githubusercontent.com/31410839/139397212-8fb250a7-10e4-4ec3-9671-51d25c53e4dc.png">

<img width="711" alt="Screenshot 2021-10-29 at 1 17 22 PM" src="https://user-images.githubusercontent.com/31410839/139396417-2fc694c8-e787-4950-aa8e-87cfaba5f258.png">

**Versions (please complete the following information):**
 - VS code Version: 1.59.1
 - Dart extension version: v3.27.2
 - Dart/Flutter SDK version: 2.6.0

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.478, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.478 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision abecef6ed3 (2 days ago), 2021-10-26 20:31:29 -0700
    • Engine revision 925bae45ee
    • Dart version 2.15.0 (build 2.15.0-250.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 95.0.4638.54

• No issues found!
```
</details>

**Comment by DanTup** [comment]
I don't seem to be able to reproduce this:

<img width="835" alt="Screenshot 2021-11-01 at 13 56 40" src="https://user-images.githubusercontent.com/1078012/139683149-73419bd0-cc6c-4d1c-9dc3-1d80e360d654.png">

The icons are shipped with the extension, so there's no reliance on an internet connection. Could you try:

- Trigger the bug, then click Help -> Toggle Developer Tools -> Console and check if there are any errors/warnings that seem like they may be related to Icons
- Run ` ls ~/.vscode/extensions/dart-code.dart-code-3.27.2/media/doc-icons/material/ac_unit_outlined@2x.png ` in a terminal and see whether it reports the file exists or not

Thanks!

**Comment by maheshmnj** [comment]
@DanTup thanks for taking a look

Here is the requested info

![image](https://user-images.githubusercontent.com/31410839/139705991-5fd51414-ffaf-419e-a7fd-fbb45cab8c0c.png)

looks like the icons are present.

```
mahesh@Maheshs-MacBook-Air-M1 ipa % 
 ls ~/.vscode/extensions/dart-code.dart-code-3.27.2/media/doc-icons/material/ac_unit_outlined@2x.png
/Users/mahesh/.vscode/extensions/dart-code.dart-code-3.27.2/media/doc-icons/material/ac_unit_outlined@2x.png
mahesh@Maheshs-MacBook-Air-M1 ipa % 

```

**Comment by DanTup** [comment]
Ah sorry, I missed your VS Code version. There was a bug in VS Code that was fixed (https://github.com/microsoft/vscode/commit/863eb4d80acf09ad20bfacc76bea5c3f76a18386) in VS Code 1.60.0 but you're on 1.59.1. It should start working again once you upgrade :-)

**Comment by maheshmnj** [comment]
Thanks, it's working with the upgrade.

**Comment by DanTup** [comment]
Great! :-)
