### ISSUE TITLE
Analyser crashes every time I execute build_runner build

### ISSUE THREAD

**Issue by ikbendewilliam** [Dart-Code/Dart-Code#3642]
Every time I execute the command `fvm flutter packages pub run build_runner build --delete-conflicting-outputs`, my analyser stops working and I have to restart it.
I use MacOS VSCode (But my colleague that uses Android studio has the same issue).

I also have the same issue when I build for iOS. After I start building, it just breaks and then I need to completely restart VSCode.
I've had the issue for quite a while now, but I remember that last year everything worked fine. On my Windows 11 I don't have the issue (same setup, my VSCode is synced).

**Steps to reproduce the behaviour:**
Run `fvm flutter packages pub run build_runner build --delete-conflicting-outputs`. Code completion stops working, etc...

**Expected behaviour**
Either the analyser doesn't break or it automatically restarts

**Versions (please complete the following information):**
 - VS Code version:
Version: 1.61.2 (Universal)
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T15:49:28.381Z (1 wk ago)
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
 - Dart extension version: v3.27.2
 - Dart/Flutter SDK version: Dart SDK version: 2.14.2 (stable) (Wed Sep 15 12:32:06 2021 +0200) on "macos_x64"

**Comment by DanTup** [comment]
If this also happens for Android Studio, it won't be fixable here in the VS Code extension so this should be raised at https://github.com/dart-lang/sdk. It may be useful to enable the analyzer logging (see [here](https://dartcode.org/docs/logging/#analyzer) and [here](https://dartcode.org/docs/logging/#analyzer-instrumentation)) and seeind if there are any errors recording in the logs once the server is in the broken state.

**Comment by ikbendewilliam** [comment]
So don't know why, but we recently upgraded to flutter 2.5.3 and everything is fixed. Both brb and building for iOS don't cause issues anymore. The only thing I can think of that changed was the flutter version 🤔

**Comment by DanTup** [comment]
If it was happening with both Android Studio and VS Code, it certainly seems like the problem may have been in the Dart or Flutter SDK, so an SDK update is where I'd expect to see a fix (although I don't know what it might have been).

Glad it's sorted anyway - if you do see it again (and it happens in both editors), I'd suggest filing an issue in the flutter/flutter repo. Thanks!

**Comment by ikbendewilliam** [comment]
Will do, Thank you for your time!
