### ISSUE TITLE
Path weirdness in Testing pane

### ISSUE THREAD

**Issue by timsneath** [Dart-Code/Dart-Code#3643]
**Describe the bug**
See screenshot: note that the path separator is inconsistent between front and backslashes:
![image](https://user-images.githubusercontent.com/2319867/139497837-0c7c757e-acf1-4a70-a7bd-3d6850020c2d.png)

**Versions (please complete the following information):**
 - VS Code version: 1.61.2
 - Dart extension version: 3.27.2
 - Dart/Flutter SDK version: master

**Comment by DanTup** [comment]
For consistency, this was supposed to always use forward slashes like URIs.

I need a lint for this almost-always-incorrect use of `.replace()` that often catches me out :-)

<img width="170" alt="Screenshot 2021-11-01 at 10 48 06" src="https://user-images.githubusercontent.com/1078012/139660304-d14d18d0-d9e4-4386-9e22-f8fc9c79e75f.png">

**Comment by DanTup** [comment]
That said, I'm not sure if using `/` on Windows here was the right call (is it a relative path, or a relative URI?). As someone who uses Windows more than me lately, if you think it may be better as `\` let me know and I'll change. Thanks!

**Comment by DanTup** [comment]
Yeah, sounds reasonable to me, will change before the release. Thanks!
