### ISSUE TITLE
quick fix for package import doesn't work for dev_dependencies

### ISSUE THREAD

**Issue by maks** [Dart-Code/Dart-Code#3644]
If I have a package under `dev_dependencies` (eg storyboard) it does not seem to be available for a quick-fix to "Import library package-name" when I use a symbol (eg. class name) from the package in a file that doesnt yet import that package. If I move the package to be under `dependencies` in my pubspec.yaml it then works fine for quick-fix.

I'm seeing this with current version 3.27.2 and current Flutter Beta channel but I think I've been seeing this for a while now and with Flutter stable channel, though I haven't had a chance to switch and double check. The reason I mention the Flutter channel is I suspect that this may actually be upstream bug from Dart analyzer?

**Comment by DanTup** [comment]
Where is the file you're trying to add it to?

If it's inside the `lib` folder, then I believe this is by design as `dev_dependencies` are for things that are _not_ required by your projects main code, but instead only by things in `tool`/`test`/etc.. There's a note about this here:

https://dart-lang.github.io/linter/lints/depend_on_referenced_packages.html

> Whether this should be a regular dependency or dev_dependency depends on if it is referenced from a public file (one under either `lib` or `bin`), or some other private file.

If it's not working for non-public files, then that might be a bug (and dart-lang/sdk would be the correct place for it, as fixes/code completion content generally comes from the analyzer).

**Comment by maks** [comment]
Sorry for the slow reply @DanTup, long weekend for a horse race here.
 
Yes so where I am running into this is using a package [Storyboard](https://pub.dev/packages/storyboard) which I use to prototype/preview widgets outside of the main application. I have a separate `main_storyboard.dart` for it, which does live in the lib folder, but the reason I put it into `dev_dependencies` is to ensure that it and its dependencies are not shipped in the actual app, as its just for dev-time previewing of widgets, so I think of it as somewhat like code-gen deps that go into `dev_dependencies`.  Hope that makes sense?

That strange thing is though, that when typing in: `import "st" then doing autocomplete, it will find and offer for completion the packages under `dev_dependencies`.

**Comment by DanTup** [comment]
@maks 

> which does live in the lib folder, but the reason I put it into dev_dependencies is to ensure that it and its dependencies are not shipped in the actual app, as its just for dev-time previewing of widgets

I don't think it's a good idea to make it easy to accidentally start depending on `dev_dependencies` in `lib` (it's also something controlled by the analysis server, so would need to get into the SDK). I think it would be better if you can put your code somewhere like the `tool` folder, which is intended for the not-production code.

> That strange thing is though, that when typing in: `import "st"` then doing autocomplete, it will find and offer for completion the packages under `dev_dependencies`.

That's a bug - there's an open issue at https://github.com/dart-lang/sdk/issues/43678 about that.

**Comment by maks** [comment]
Thanks @DanTup that makes very good sense and I didn't know about using `tools` folder. Just switched over to using it instead and now the dev dependencies quick-fix work just fine with my code in `tools` 👍🏻  Thanks again!

**Comment by DanTup** [comment]
Great! :-)
