### ISSUE TITLE
Code Actions Menu is not properly ordered

### ISSUE THREAD

**Issue by larsb24** [Dart-Code/Dart-Code#3646]
**Describe the bug**
The order of the Code Actions Menu should (and did until about a month ago) display "Wrap with Widget" as the first option, but for some time it sorts alphabetically as of recently.

**To Reproduce**
`Ctrl` + `.`

**Expected behavior**
As described in the description, the "Wrap with Widget" option should be first in the list, but instead it sorts alphabetically

**Screenshots**
![image](https://user-images.githubusercontent.com/61460660/139740395-09d6b732-d468-453e-96b9-64b5473a60a5.png)

**Versions (please complete the following information):**
 - VS Code version: 1.61.2
 - Dart extension version: 3.28.0
 - Dart/Flutter SDK version: 2.6.0 (master)

**Comment by PollyGlot** [comment]
Personally, I'd make a submenu for everything with "Wrap with [widget_name]" leaving "Wrap with widget..." independent. This way the list won't look so long.

**Comment by larsb24** [comment]
> Personally, I'd make a submenu for everything with "Wrap with [widget_name]" leaving "Wrap with widget..." on top and independent. This way the list won't look so long.

Yes it does look wrong, that's the problem I described. I want it to be at the top as well, but it suddenly isn't any more

**Comment by DanTup** [comment]
This has been fixed in the SDK and the fix will show up in a future SDK release. Sorry for the bother!

https://github.com/dart-lang/sdk/commit/00ca3283c0e2bb46abe3ebcce66bc1746bbb0e56
