### ISSUE TITLE
VS CODE not detecting flutter (3.28.0) .

### ISSUE THREAD

**Issue by ShimronAlakkal** [Dart-Code/Dart-Code#3651]
VS Code is not able to detect flutter or any flutter commands. 
The code worked just the day before but this happened all of a sudden. Flutter commands work, externally, in a terminal. 
The doctor summary is all good.

 - VS Code version: 1.61.2
 - Dart extension version: 3.28.0
 - Flutter SDK version: 2.6.0-12.0.pre.589  ( master channel )

**Comment by ShimronAlakkal** [comment]
Hi again.
It is a bug, most probably 'cause I was able to fix and work on my projects, again, just after downgrading the extensions to a version that was released 22 days  (or a month) ago

**Comment by DanTup** [comment]
> VS Code is not able to detect flutter or any flutter commands.

Can you be more specific about the issue - are you seeing an error message? Can you provide a screenshot?

Do you mean the extension is reporting that it cannot find the Flutter SDK, you can't run `flutter` commands in the built-in terminal, or some other functionality isn't working?

**Comment by ShimronAlakkal** [comment]
Hey,
The issue is that whenever you try running any flutter command from inside vs code it doesn't work and shows the below error message. The editor is also not able to highlight ( or not able to detect ) the keywords in the code as it did before. This only happened while using the latest dart plugin. 
 
Error: 
![GbA60](https://user-images.githubusercontent.com/60049707/140457414-bd37d185-b0f1-4ddb-b003-b701cee4c99f.png)

Flutter doctor 
![midoO](https://user-images.githubusercontent.com/60049707/140457595-d7ccb5fc-73f9-472f-8cf9-509b3058ef83.png)

Thanks.

**Comment by DanTup** [comment]
Can you click Help -> Toggle Developer Tools and then Console tab in VS Code, and see if there are any errors listed in the console?

Also, you could check whether this command works, and if so whether there are any errors listed in the log:

<img width="417" alt="Screenshot 2021-11-05 at 15 26 35" src="https://user-images.githubusercontent.com/1078012/140535835-104dfd4f-515c-4489-8147-44e646a59e39.png">
