### ISSUE TITLE
Code Completion Appears to be broken after Update

### ISSUE THREAD

**Issue by ObserverMoment** [Dart-Code/Dart-Code#3654]
**Describe the bug**
After VS code updated to 1.62 and Dart-Code to v3.28.0 just now code completion and syntax formatting appears to be broken for Flutter.

Eg. Trying to build a Wrap component - see the auto complete options being suggested.

<img width="805" alt="Screenshot 2021-11-05 at 11 09 41" src="https://user-images.githubusercontent.com/20599210/140501955-c00ce417-fb5b-4682-ac88-be4847666204.png">

I also seem to be just getting a whole load of random behaviour

**To Reproduce**
Update to newest versions - try and write Flutter code (see example screenshot)

**Versions (please complete the following information):**
 - VS Code version: 1.62
 - Dart extension version: v3.28.0
 - Dart/Flutter SDK version: Flutter 2.5.3 / Dart 2.14.4

Here is my preferences file:

```
{
  "workbench.iconTheme": "material-icon-theme",
  "editor.fontSize": 13,
  "javascript.validate.enable": true,
  "explorer.confirmDragAndDrop": false,
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true
  },
  "[javascriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true
  },
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true
  },
  "[graphql]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true
  },
  "[prisma]": {
    "editor.defaultFormatter": "Prisma.prisma",
    "editor.formatOnSave": true
  },
  "emmet.includeLanguages": {
    "javascript": "javascriptreact"
  },
  "emmet.triggerExpansionOnTab": true,
  "workbench.colorTheme": "Darktooth",
  "[html]": {
    "editor.defaultFormatter": "vscode.html-language-features",
    "editor.formatOnSave": true
  },
  "dart.flutterSdkPath": "/Applications/flutter",
  "dart.openDevTools": "flutter",
  "[dart]": {
    "editor.formatOnSave": true,
    "editor.formatOnType": false,
    "editor.rulers": [],
    "editor.selectionHighlight": false,
    "editor.suggest.snippetsPreventQuickSuggestions": false,
    "editor.suggestSelection": "first",
    "editor.tabCompletion": "onlySnippets",
    "editor.wordBasedSuggestions": false,
    "files.insertFinalNewline": true
  },
  "dart.debugSdkLibraries": false,
  "[json]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[jsonc]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "editor.wordWrap": "on",
  "editor.renderWhitespace": "none",

  "files.exclude": {
    "**/.git": false
  },
  "dart.analyzeAngularTemplates": false,
  "[typescriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true,
  },
  "typescript.updateImportsOnFileMove.enabled": "always",
  "vscode-graphql.useSchemaFileDefinitions": true,
  "redhat.telemetry.enabled": true,
  "update.mode": "start",
}

```

**Comment by DanTup** [comment]
Can you reproduce this in a new project created with `flutter create`/**Flutter: New Project**? If so, could you share an _exact_ file and the location you're invoking completions and seeing the wrong thing so I can try to reproduce?

I can't think of anything in the latest update that should affect somethig like this, but you could confirm if it was related to the extension update by reverting to the previous version (v3.27.2) from the VS Code extensions tab. If the issue goes away, then that will help narrow things down.

Thanks!

**Comment by ObserverMoment** [comment]
HI @DanTup,

Ok, so it doesn't reproduce in a new project and it also doesn't reproduce in all files in my active project. Could it be that particular syntax is throwing it off?

Here is the offending code.

```
ListView(
            shrinkWrap: true,
            padding: const EdgeInsets.symmetric(vertical: 8),
            children: _activeWorkoutMove == null
                ? [
                    Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        BorderButton(
                            mini: true,
                            prefix: Icon(
                              CupertinoIcons.arrow_left_right_square,
                              color: context.theme.background,
                              size: 20,
                            ),
                            text: 'Select a move',
                            onPressed: () => _changeTab(0))
                      ],
                    ),
                  ]
                : [
                    Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Flexible(
                            child: MyHeaderText(_activeWorkoutMove!.move.name)),
                        const SizedBox(
                          width: 16,
                        ),
                        BorderButton(
                            mini: true,
                            prefix: const Icon(
                              CupertinoIcons.arrow_left_right,
                              size: 20,
                            ),
                            text: 'Change',
                            onPressed: () => _changeTab(0))
                      ],
                    ),
                    Padding(
                      padding: const EdgeInsets.symmetric(vertical: 24.0),
                      child: Wrap(
                        spacing: 30,
                        runSpacing: 10,
                        alignment: WrapAlignment.spaceEvenly,
                        runAlignment: WrapAlignment.spaceEvenly,
                        children: [
                          if (!widget.ignoreReps &&
                              widget.fixedTimeReps == null)
                            RepPickerDisplay(
                              expandPopup: true,
                              reps: _activeWorkoutMove!.reps,
                              validRepTypes:
                                  _activeWorkoutMove!.move.validRepTypes,
                              repType: _activeWorkoutMove!.repType,
                              updateReps: (reps) =>
                                  _updateWorkoutMove({'reps': reps}),
                              updateRepType: (repType) => _updateWorkoutMove(
                                  {'repType': repType.apiValue}),
                              distanceUnit: _activeWorkoutMove!.distanceUnit,
                              updateDistanceUnit: (distanceUnit) =>
                                  _updateWorkoutMove(
                                      {'distanceUnit': distanceUnit.apiValue}),
                              timeUnit: _activeWorkoutMove!.timeUnit,
                              updateTimeUnit: (timeUnit) => _updateWorkoutMove(
                                  {'timeUnit': timeUnit.apiValue}),
                            ),
                          if (_showLoadPicker())
                            FadeIn(
                              child: LoadPickerDisplay(
                                expandPopup: true,
                                loadAmount: _activeWorkoutMove!.loadAmount,
                                loadUnit: _activeWorkoutMove!.loadUnit,
                                updateLoad: (loadAmount, loadUnit) =>
                                    _updateWorkoutMove({
                                  'loadAmount': loadAmount,
                                  'loadUnit': loadUnit.apiValue
                                }),
                              ),
                            ),
                        ],
                      ),
                    ),
                    if (_activeWorkoutMove!.move.requiredEquipments.isNotEmpty)
                      Column(
                        children: [
                          const MyText('Required'),
                          const SizedBox(height: 10),
                          Wrap(
                            alignment: WrapAlignment.center,
                            spacing: 8,
                            runSpacing: 8,
                            children:
                                _activeWorkoutMove!.move.requiredEquipments
                                    .map((e) => ContentBox(
                                          child: MyText(
                                            e.name,
                                            weight: FontWeight.bold,
                                            size: FONTSIZE.four,
                                          ),
                                        ))
                                    .toList(),
                          )
                        ],
                      ),
                    if (_activeWorkoutMove!
                        .move.selectableEquipments.isNotEmpty)
                      Padding(
                        padding: const EdgeInsets.symmetric(
                            vertical: 16.0, horizontal: 6),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Padding(
                              padding: const EdgeInsets.all(12.0),
                              child: MyText('Select one from...',
                                  color: _activeWorkoutMove?.equipment == null
                                      ? Styles.errorRed
                                      : null,
                                  lineHeight: 1.4),
                            ),
                            Wrap(
                              alignment: WrapAlignment.center,
                              spacing: 6,
                              runSpacing: 6,
                              children: _equipmentsWithBodyWeightFirst(
                                      _activeWorkoutMove!
                                          .move.selectableEquipments)
                                  .map((e) => SizedBox(
                                        height: 86,
                                        width: 86,
                                        child: GestureDetector(
                                            onTap: () => _updateWorkoutMove({
                                                  'Equipment': e.toJson(),
                                                }),
                                            child: EquipmentTile(
                                                showIcon: true,
                                                equipment: e,
                                                withBorder: false,
                                                fontSize: FONTSIZE.two,
                                                isSelected: _activeWorkoutMove!
                                                        .equipment ==
                                                    e)),
                                      ))
                                  .toList(),
                            ),
                          ],
                        ),
                      ),
                  ],
          )
```
Whatever component I add to the <Widget>[] before or after the ternary seems to think that it is inside the ListView - and so suggestions completions from the ListView widget. Manually typing in the code correctly does remove all errors so it seems like the completion lookup is getting confused?

<img width="849" alt="Screenshot 2021-11-05 at 13 41 03" src="https://user-images.githubusercontent.com/20599210/140519465-bb2419b1-c1ae-4ce1-8103-9bf3705a487f.png">

Actually removing the ternary `_activeWorkoutMove == null ? etc` does seem to fix the issue.

Not sure if I am missing something?

If you need any further info just let me know.

Cheers

Rich

**Comment by DanTup** [comment]
I can't reproduce this pasting your code into a new project:

<img width="754" alt="Screenshot 2021-11-05 at 15 01 15" src="https://user-images.githubusercontent.com/1078012/140531817-faa39287-1838-455a-8c87-f8271df7c494.png">

Are you able to construct a complete file that triggers this in a new project that I can test with? If the syntax is valid, I wouldn't expect it to provide the wrong thing (FWIW, maybe that statement would work better as a [collection if](https://dart.dev/guides/language/language-tour#collection-operators)?).

**Comment by amirburbea** [comment]
Getting similar problem in angulardart but on google3 which I makes sharing code impossible, but just wanted you to know this is a real bug.

**Comment by DanTup** [comment]
Can anyone easily verify whether the issue is introduced by a VS Code, Dart-Code, or SDK update?

It may also be useful to run the **Dart: Open Analyzer Diagnostics** command, then go to the Contexts section and check the contents of the file in question:

<img width="808" alt="Screenshot 2021-11-10 at 18 43 29" src="https://user-images.githubusercontent.com/1078012/141174081-6c72f04b-d0e9-437c-aa84-9a3b69e493c7.png">

And see whether this code seems to match up with what's in the editor, or if it seems messed up (such that the offset of where completion was invoked might have different code to what you see in the editor)?

**Comment by DanTup** [comment]
It would also be useful to test whether disabling LSP (using the `dart.useLsp: false` setting in the latest Dart-Code, or `dart.previewLsp: false` in the previous versions) and restarting VS Code makes any difference to this.

**Comment by amirburbea** [comment]
Actually: I'm seeing more a problem with dart not analyzing/popping up tooltips in ssh sessions (or offering GoToDefinition in context menu on code items), but that only started yesterday - when this happens I don't even have any analysis related options in the Command Palette.

If I chrome remote desktop to that linux pc and run vscode locally there, the tooltips do work and GoToDefinition context menu options work just fine.

**Comment by DanTup** [comment]
@amirburbea are you using the standard VS Code Remoting - SSH extension for this or something else (like the old `dart.analyzerSshHost` setting)?

Are you able to try with the previous versions of VS Code/Dart-Code to see whether it's an update of one of them that introduced this?

@ObserverMoment I don't suppose you're seeing this via SSH too?

**Comment by amirburbea** [comment]
Definitely it's the standard SSH, how do I force an old version of the extension from the command pallette or something? I clicked install another version but it didn't autocomplete a list of options available

**Comment by DanTup** [comment]
>  I clicked install another version but it didn't autocomplete a list of options available

Yeah, I've found that to be _super_ slow and I'm not sure why. It does eventually complete, but another option is to grab the VSIX attached to ths release here:

https://github.com/Dart-Code/Dart-Code/releases/tag/v3.27.2

And then install it by running **Extensions: Install from VSIX**, browsing to that file, then clicking reload.

(you don't need to roll the Flutter extension back, that extension contains very little and mostly delegates to the Dart one)

**Comment by ObserverMoment** [comment]
@DanTup, sorry for my lack of knowledge but I'm not sure if I'm using SSH / Remoting...how would I check? I am pretty sure I am using the default settings as suggested by the package.

I've been using VSCode for a few days now since posting the original issue and not been running into problems. Have been steering clear of weird syntax though.

At the time (before posting) I did revert to the previous version of Dart Code and the issue persisted.

**Comment by DanTup** [comment]
@ObserverMoment Using SSH involves installing the "Remoting - SSH" extension and specifically conencting VS Code to another (remote) machine. If you're not familiar with it you're certainly not using it, so it seems unrelated to that.

>  I did revert to the previous version of Dart Code and the issue persisted.

That's interesting to know. Have you updated the Dart/Flutter SDK lately? If not, perhaps it's related to the VS Code update.

If you do see it again, please do post back with any additional info that might be useful. I'm keen to understand what's going on here. An [analysis instrumentation log](https://dartcode.org/docs/logging/#analyzer-instrumentation) could be useful, though be aware that file grows very large and includes parts from your source code (so I would only enable it temporarily when debugging, and ensure it's not a private project when sharing log files).

**Comment by amirburbea** [comment]
I reverted the extension and still got the problem where the analysis options are there when I chrome remote desktop to the local machine but not over SSH from my laptop 

I can't take that instrumentation on my work PC because it's google and I can't upload that code.

I'm going to suggest to setup a Linux VM and SSH to it from Windows and see if you can replicate. But I do recognize that's asking a lot.

**Comment by amirburbea** [comment]
VS Code updated and it appears to be fixed!!!

**Comment by DanTup** [comment]
Ah, great! I did think it sounded like a VS Code issue (if the servers view of the file was out of sync, I would expect all of the analysis errors to be messed up too), and it seemed like it came in with the VS Code update. I had searched their issue tracker and not found anything though (I just had another look and still can't see anything obvious).

@ObserverMoment if you upgrade to the latest VS Code patch, is the issue also fixed for you?

**Comment by ObserverMoment** [comment]
I still seem to be getting the same incorrect suggestions for the wrap component in the original widget in which I noticed the issue.

<img width="680" alt="Screenshot 2021-11-14 at 12 11 37" src="https://user-images.githubusercontent.com/20599210/141680535-012d44a6-df59-4317-aeef-150bb124c517.png">

Tho I have not noticed any VS Code update and 'checking for updates' says that there is nothing to update to.

> Version: 1.62.2 (Universal)
Commit: 3a6960b964327f0e3882ce18fcebd07ed191b316
Date: 2021-11-11T20:59:05.913Z (2 days ago)
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0

That said, I have been using VScode + Dart and have not been noticing similar issues.

Like you say, it could be the non-standard syntax (tho valid) in the widget throwing it off.

I will keep an eye out for a VS code update as maybe its not reached me yet for some reason.

**Comment by DanTup** [comment]
> Like you say, it could be the non-standard syntax (tho valid) in the widget throwing it off.

To be clear, I don't think that's the cause (I couldn't repro with that), but if it was that's absolutely a bug that needs fixing. My mention of that was more of an FYI than an explanation for the behaviour.

I'd definitely like to get to the bottom of this. If you're able to narrow down a project that definitely triggers it or get a log file as described above (note: the log will include parts of your source code), that may help understand what's going wrong.
