### ISSUE TITLE
Group devices in device picker

### ISSUE THREAD

**Issue by guidezpl** [Dart-Code/Dart-Code#3655]
Blocked on https://github.com/microsoft/vscode/issues/74967

**Comment by guidezpl** [comment]
Now available https://code.visualstudio.com/updates/v1_64#_quickpickitem-separators

**Comment by DanTup** [comment]
![Screenshot 2022-02-08 at 11 10 00](https://user-images.githubusercontent.com/1078012/152975603-9f64ef61-b4bf-433c-86e5-f5b0d68e4c50.png)
