### ISSUE TITLE
For multi package projects, total tests run gives total of last run package rather than total of all

### ISSUE THREAD

**Issue by allicaDan** [Dart-Code/Dart-Code#3665]
**Description**
Attached multi package project contains 25 tests. After running either `Dart: Run All Tests` or tapping the test panels' `Run Tests` button, the count of tests shows 12. Which looks like the same count as the last package ran

**To Reproduce**
1. Open attached reproducing project
2. run `Dart: Run All Tests` command
3. See the testing panel output

**Expected behavior**
See the total count of passing tests 25

**Screenshots**
<img width="1082" alt="foldersAlongsideTerminal" src="https://user-images.githubusercontent.com/86519058/141155543-f7ff438d-b09a-433d-a3be-0571709c1a4d.png">

<img width="520" alt="testingPanel" src="https://user-images.githubusercontent.com/86519058/141155551-c3a98174-92ac-4589-b35c-6c12ea3c8f20.png">

https://user-images.githubusercontent.com/86519058/141155819-1e068c54-0bd4-44c1-b4f0-414ee1012789.mov

**Versions (please complete the following information):**
 - VS Code version: 1.62.1
 - Dart extension version: v3.28.0
 - Dart/Flutter SDK version: 2.5.3 stable

Project to reproduce:
[repro_workspace.zip](https://github.com/Dart-Code/Dart-Code/files/7514466/repro_workspace.zip)

**Comment by jeiea** [comment]
I have similar issue with the latest version, but I can't determine whether this is a regression due to extension downgrade is stuck at selecting version to install. It may need a test.

**Comment by DanTup** [comment]
@jeiea running the sample project above still shows 25 tests in the latest version for me. Could you file a new issue and include more details about what you're seeing and how to reproduce?

There's a bug in VS Code which cases the extension version drop-down to populate very slowly for some extensions. If you leave it long enough it should populate (takes a minute or two for me), though you can also download the vsix files from the GitHub releases at https://github.com/Dart-Code/Dart-Code/releases and install them with the **Install from VSIX** command.

**Comment by DanTup** [comment]
(please do file an issue whether the old version works or not though, as sticking on an old version isn't a sustainable solution :-))
