### ISSUE TITLE
Can't found device when using vscode remote ssh

### ISSUE THREAD

**Issue by zhcode-fun** [Dart-Code/Dart-Code#3666]
**Describe the bug**
After VS code updated to 1.62.1. Always "NO DEVICE"  in status bar.

**To Reproduce**
Use latest vscode in windows and connect Linux by ssh-remote .

**Expected behavior**
Display my device in status bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/31911177/141258477-be062f8a-1fd3-4d90-8f8a-9d5a613d3e55.png)

**Versions (please complete the following information):**
 - VS Code version: 1.62.1
 - Dart extension version: 3.28.0
 - Flutter SDK version: 2.5.3
 - Remote - SSH extension version: 0.66.1
 
**Flutter doctor**
```
[✓] Flutter (Channel stable, 2.5.3, on Deepin 20.2.4 5.10.60-amd64-desktop, locale zh_CN.UTF-8)
    • Flutter version 2.5.3 at /home/zhaozh/DevEnv/flutter
    • Upstream repository https://mirrors.tuna.tsinghua.edu.cn/git/flutter-sdk.git
    • Framework revision 18116933e7 (4 周前), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/zhaozh/DevEnv/AndroidSdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /home/zhaozh/DevEnv/AndroidSdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Redmi K30 5G (mobile) • b5eebf64 • android-arm64 • Android 11 (API 30)

! Doctor found issues in 1 category.
```

**Comment by DanTup** [comment]
Can you enable the [Flutter daemon log](https://dartcode.org/docs/logging/#flutter-daemon) and restart VS Code, reproduce the issue and then provide the log here? Thanks!

**Comment by zhcode-fun** [comment]
> Can you enable the [Flutter daemon log](https://dartcode.org/docs/logging/#flutter-daemon) and restart VS Code, reproduce the issue and then provide the log here? Thanks!

I upgraded the vs code to 1.62.2 today. This problem is solved.Thanks!
