### ISSUE TITLE
Completing a method/constructor name with no typed prefix inserts parenthesis even if already present

### ISSUE THREAD

**Issue by caseyryan** [Dart-Code/Dart-Code#3672]
**Describe the bug**
v3.28.0 Places odd braces on autocompletion where there is already an existing pair

**To Reproduce**
Write some code like
```dart
Container(
  child: Padding(
    padding: EdgeInsets.all(8.0),
    child: Column(
      children: [
        
      ],
    ),
  ),
)
```
2) erase "all" constructor name and type, e.g. symm 
3) When it prompts "symmetric" press enter to autocomplete it
4) You will see odd pair of braces like this and the cursor between them
 ```dart
Container(
  child: Padding(
    padding: EdgeInsets.symmetric()(8.0),
    child: Column(
      children: [
        
      ],
    ),
  ),
)
```

**Expected behavior**
No braces added because there is already a pair of them right next to the prompted code
in this case with (8.0) inside

**Screenshots**

https://user-images.githubusercontent.com/4113558/141984413-77aa797b-b13b-4acd-ba5d-55a3a9d9233f.mov

**Versions (please complete the following information):**
 - VS Code version: 1.62.2
 - Dart extension version: v3.28.0
 - Dart/Flutter SDK version: Dart 2.13.4 (stable), Flutter 2.2.3 (stable)

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/327389b86f483a9215804ddb28d3e3a27034f11c.
