### ISSUE TITLE
Feature: Specify shell or executable to use when debugging

### ISSUE THREAD

**Issue by point-source** [Dart-Code/Dart-Code#3674]
**Is your feature request related to a problem? Please describe.**
I am trying to use a secrets management tool (Doppler) to inject secrets before my application launches. For security reasons, I would prefer not to export the secrets to an env file on the filesystem or to the system/user shell.

Per doppler's documentation, applications can be run [via the doppler cli](https://docs.doppler.com/docs/editors-vs-code) or by using a [shell instance that has been pre-populated with env vars](https://docs.doppler.com/docs/accessing-secrets#how-to-export-doppler-secrets-into-the-current-shell).

Unfortunately, the launch config variables for dart do not appear to allow me to specify which executable or shell to use to launch the dart file.

**Describe the solution you'd like**
I would like to be able to configure the vscode debug launcher to start a debug session with `doppler run -- dart /my/dart/file.dart` or by spawning a shell via `doppler run -- sh -c 'sh'` which can then execute `dart /my/dart/file.dart`

**Describe alternatives you've considered**
- Exporting doppler secrets to an .env file: This leaves the secrets on the filesystem if they are not manually removed. It also does not keep the .env file synced with doppler and has to be run when secrets are changed
- Running the dart file manually: This requires manually attached the debugger every time the application is run

**Comment by DanTup** [comment]
I think this is essentially the same as #3656 and can be solved the same way. My thinking is to add a `customTool` field to the launch.json that you could set to `doppler` and then you could include `run -- sh -c 'sh'` in the `toolArgs`.
