### ISSUE TITLE
Update location of Flutter survey JSON to docs.flutter.dev

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#3677]
https://flutter.dev/f/flutter-survey-metadata.json should be updated to https://docs.flutter.dev/f/flutter-survey-metadata.json.

The old URL is currently a 404 due to site changes. @jayoung-lee is trying to get the current survey JSON restored there for existing plugins as a temporary measure, but for future surveys, we need to read from the docs.flutter.dev site.

(cc @kenzieschmoll @stevemessick - DevTools/IntelliJ will need updating too)

**Comment by jayoung-lee** [comment]
For the future DevTools survey, the new URL would be https://dosc.flutter.dev/f/dart-devtools-survey-metadata.json

**Comment by DanTup** [comment]
Looks like there's a DevTools survey live now (https://docs.flutter.dev/f/dart-devtools-survey-metadata.json), so it may be worth copying that one over if possible too (I think DevTools is shipping with SDKs now, so not releasing as frequently as the editor plugins).

**Comment by jayoung-lee** [comment]
That's actually from last year, a one-off survey. :) But yeah, that should
be updated ASAP to be included in the next release.

**Comment by DanTup** [comment]
Whoops, missed the year 😄

**Comment by jayoung-lee** [comment]
It feels like it was yesterday though 😂!
