### ISSUE TITLE
Ignore lint rules autocomplete

### ISSUE THREAD

**Issue by Semvrij** [Dart-Code/Dart-Code#3678]
This addition is not that much of a priority, but would be a nice addition to get autocomplete when ignoring linter rules.
When typing `// ignore: ` or `// ignore_for_file: `, the extension then looks at which linter rules you have activated and returns them as autocomplete. This way you don't have to go back to your analysis_options.yaml file to see what the exact name of the rule is.

**Comment by DanTup** [comment]
There's a Code Action for creating ignores - is there a reason not to just use this instead?

<img width="457" alt="Screenshot 2021-11-22 at 11 43 51" src="https://user-images.githubusercontent.com/1078012/142855984-ebedf8f5-3462-44fc-b291-0d5928c07559.png">

**Comment by Semvrij** [comment]
This feature seems like a good solution to me.
