### ISSUE TITLE
Duplicated suggestions

### ISSUE THREAD

**Issue by johnnyasantoss** [Dart-Code/Dart-Code#3679]
**Describe the bug**
My code Suggestions/AutoComplete/IntelliSense are showing twice for each suggested definition.
For now, I'm still debugging what is going on to see if it's not a side effect of any other extension.

**To Reproduce**
1. After installing the Flutter extension
1. Go to any Dart file in any definition and press the keyboard shortcut to show code suggestions
2. See the duplicated suggestions

**Expected behavior**
Show only one suggestion per type/method.

**Screenshots**
![image](https://user-images.githubusercontent.com/14189387/142644565-c6a4c04f-f016-4d68-a9db-e310988d12c3.png)

**Versions:**
 - VS Code version: `1.62.3`
 - Dart extension version: `3.28.0`
 - Dart/Flutter SDK version: `3.28.0`

**Comment by DanTup** [comment]
Are you using any analysis server plugins? If so, I think you might be seeing https://github.com/Dart-Code/Dart-Code/issues/3555 which has been fixed in the SDK repo and should be included in the next major Dart/Flutter SDK releases.

**Comment by johnnyasantoss** [comment]
@DanTup Yes! I'm using `dart-code-metrics` too. I'm going to take a look in that thread

**Comment by johnnyasantoss** [comment]
Okay. Renaming `analysis_options.yaml` to something else, to disable it, makes the duplicated suggestions go away.

Is there any other workaround until the next sdk release besides disabling analysis server?

**Comment by DanTup** [comment]
You could set `dart.useLsp: false` in your VS Code user settings to disable LSP (where the bug is), but you may lose a few features and have slightly worse performance, as LSP is where all the new work is going (the non-LSP code will be dropped soon).

**Comment by DanTup** [comment]
(Closing this as a dupe, but feel free to ping here with comments/questions!)
