### ISSUE TITLE
Support Flutter full restart

### ISSUE THREAD

**Issue by xster** [Dart-Code/Dart-Code#368]
Would be awesome to also support full restarts as well. 
Hot reload tries to preserve as much app state as possible while swapping out the running logic while full restart restarts all app states in memory. Both have their uses (for instance hot reloads can't reload things initialized at the start of the app).

**Comment by DanTup** [comment]
`app.restart` has a `fullRestart` flag we can use. We can't add new debug toolbar buttons so this will have to go as a new command (which the user can keybind) and passed through to the DA with `customDebugRequest` (similar to 88c5801aa5be3e3d8c0cafd8eaae7b4265174279).

**Comment by DanTup** [comment]
I've implemented this, but it's so fast I'm not sure if I believe it's working right? =)

![Reload](https://user-images.githubusercontent.com/1078012/28498731-74f6397a-6f9c-11e7-9955-15d51ad79697.png)

**Comment by DanTup** [comment]
@xster v2.3.1 is available now with this. It's much faster than I expected (the initial compiles/deployment are super-slow!) so I don't know for certain it's doing what you're expecting, but please let me know.

**Comment by xster** [comment]
Super awesome! I think one tiny tweak is to have the when: inDebugMode pre-filled in the key bindings.

**Comment by DanTup** [comment]
I think that's a VS Code bug (https://github.com/Microsoft/vscode/issues/30778). We list the condition in the `packages.json` but Code only seems to show certain contexts (eg. language) in the `when` column.
