### ISSUE TITLE
Autocomplete options are not shown automatically when filling a parameter of a typedef function 

### ISSUE THREAD

**Issue by osaxma** [Dart-Code/Dart-Code#3682]
**Describe the bug**
I hope that I'm not mistaken but I remember that when filling parameters of a typedef function such as the one in the video below, the autocomplete would show up automatically. 

**Expected Behavior**
In the video below, I had to click <kbd>fn</kbd>+<kbd>control</kbd>+<kbd>space</kbd> to show the autocomplete options but I remember they used to come up on their own after pressing <kbd>tab</kbd> to select the suggested `builder` option. 

https://user-images.githubusercontent.com/46427323/142775177-9b350863-fe96-475b-b067-07b3e3ccd986.mov

**Versions (please complete the following information):**

VS Code version: 1.62.3
Dart extension version: v3.28.0
Dart/Flutter SDK version: Flutter 2.5.3 with Dart 2.14.4
OS: Darwin x64 20.6.0

**Comment by DanTup** [comment]
I'm not sure that this triggered automatically previously (although typing the `:` manually might have), but I think it's a fair request we should try to support after completing the argument names.
