### ISSUE TITLE
Enable dart-code to run on VS Code on the Web

### ISSUE THREAD

**Issue by isidorn** [Dart-Code/Dart-Code#3694]
:wave: @DanTup Isidor here, we recently announced VS Code for the Web at https://vscode.dev/, which provides a free, zero-install Microsoft Visual Studio Code experience running entirely in your browser.  You can learn more [here](https://code.visualstudio.com/docs/editor/vscode-web). 

We'd like to ensure Dart-Code can run in the web, and we have a guide for enabling extensions for the web [here](https://code.visualstudio.com/api/extension-guides/web-extensions). As a couple of highlights:

- In VS Code for the Web, both the UI and extension host run inside the browser.
- A web extension is structured like a regular extension, but with a different main file: it's defined by the `browser` property
- Access to workspace files needs to go through the VS Code file system API accessible at `vscode.workspace.fs`
- There are currently [three ways](https://code.visualstudio.com/api/extension-guides/web-extensions#test-your-web-extension) to test a web extension

I checked your extension and I see there are quite some node dependencies and contributions, so this transition to web might not be trivial or possible. However it would be cool if you could at least contribute `grammars` for web, and using `when` clauses disable all other contributions which can not work on the web.

We are also open to helping here. Let us know what you think. Thanks!

@DanTup I also see the flutter extension does not have this many dependencies, would it make sense to look into that one, or that extension does not make sense without Dart-Code?

**Comment by DanTup** [comment]
We have an issue about this at #3528 (which I've just re-opened as a clearer place to collect 👍 s). Right now there's not a simple path to running the language server in the browser, so there's not a lot of functionality we could provide here.

>  However it would be cool if you could at least contribute `grammars` for web, and using `when` clauses disable all other contributions which can not work on the web.

I hadn't considered that - however VS Code is now shipping a built-in for Dart with our grammar, so presumably that already works without needing the extension?

> I also see the flutter extension does not have this many dependencies, would it make sense to look into that one, or that extension does not make sense without Dart-Code?

That extension doesn't work without Dart-Code. It depends on it, and right now the Flutter extension is mostly a shell that delegates to the Dart extension (although there is stuff we need to migrate from Dart to Flutter, it will never be possible to use Flutter without Dart, as the language support is fundamental to using Flutter).

If you think there's anything we could do that would add more than just the grammar (which I think should already work), let me know, but I think almost all other functionality either requires the language server or the ability to run shel commands (like the package manager), all of which would need some significant work upstream in the SDKs first.

**Comment by isidorn** [comment]
@DanTup I was not aware that we are shipping built-in Dart with a grammar, I just checked and that is indeed the case. Thanks for correcting me!
And thanks for clarifying the relationship between flutter and Dart.
Thanks for reopening that issue, having said all of I do not think this issue is bringing any additional value thus I am closing it. Let's continue the discussion on that issue and I do understand how running the language server in the browser is not possible atm.
