### ISSUE TITLE
Error: Expected a value of type 'xxx', but got one of type 'JavaScriptObject' when debugging dart:html

### ISSUE THREAD

**Issue by technolion** [Dart-Code/Dart-Code#3695]
**Describe the bug**
A flutter web app that uses dart:html runs fine in release mode but fails when debugging with VS Code & Chrome!

We are writing a Flutter app that runs on the web and accepts files dropped to the browser window.
The app listens for `onDrop` events and tries to retrieve the dropped object. In our code we are using typed variables (not `dynamic`)

```
import 'dart:html' as html;

void _onDrop(html.MouseEvent mouseEvent) async {
    mouseEvent.stopImmediatePropagation();
    mouseEvent.preventDefault();

    html.DataTransfer transfer = mouseEvent.dataTransfer;
    if (transfer.items == null || transfer.items!.length == null) return;
    List<html.Entry> entries = [];
    for (int i = 0; i < transfer.items!.length!; i++) {
      entries.add(transfer.items![i].getAsEntry());
    }
}

html.document.body!.onDrop.listen(_onDrop);
```

This code runs fine when building for release and deploying on a web server.

However it fails when running in debug mode in Visual Studio Code with Dart Code extension on Chrome:

```
Uncaught (in promise) Error: Expected a value of type 'Entry', but got one of type 'JavaScriptObject'
    at Object.throw_ [as throw] (errors.dart:251)
    at Object.castError (errors.dart:84)
    at Object.cast [as as] (operations.dart:452)
    at Function.as_C [as as] (classes.dart:633)
    at Array.[dartx.add] (js_array.dart:72)
    at io_html.DropTarget.new._onDrop (io_html.dart:182)
    at _onDrop.next (<anonymous>)
    at runBody (async_patch.dart:84)
    at Object._async [as async] (async_patch.dart:123)
    at io_html.DropTarget.new.[_onDrop] (io_html.dart:173)
    at Object._checkAndCall (operations.dart:334)
    at Object.dcall (operations.dart:339)
    at HTMLBodyElement.<anonymous> (html_dart2js.dart:37308)
```

It seems that using the type `Entry` ([dart API](https://api.dart.dev/stable/2.14.4/dart-html/Entry-class.html)) confuses the debugger because there is no native JavaScript object that matches this name and/or signature.

**Screenshots**
![Bildschirmfoto 2021-11-25 um 12 47 12](https://user-images.githubusercontent.com/1611505/143436703-6249bc76-0b9f-4e18-a410-6d63a6b398b9.png)

**Versions (please complete the following information):**
 - VS Code version: 1.62.3
 - Dart extension version: 3.28.0
 - Dart/Flutter SDK version: Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale de-DE)

**Comment by DanTup** [comment]
I suspect this is a difference in code generated by dart2js (used for release builds) and ddc (used for debug builds). I hit a similar issue in https://github.com/dart-lang/sdk/issues/44692 although I'm not sure if your issue is the same one of just something similar.

I suspect you'll see the same behaviour running a debug (ddc) build from the terminal, so I don't think it's a VS Code extension issue (or fixable here). If it's not exactly the same as https://github.com/dart-lang/sdk/issues/44692 then it's probably best filing a new issue at https://github.com/dart-lang/sdk.

Thanks!

**Comment by technolion** [comment]
You are absolutely right. The problem can also be reproduced when running with `flutter run --debug`  on the console.
Thanks for pushing me into the right direction!
