### ISSUE TITLE
`dart fix` is not detecting auto-fixable problems for Flutter

### ISSUE THREAD

**Issue by osaxma** [Dart-Code/Dart-Code#3696]
_This issue was originally filed at https://github.com/flutter/flutter/issues/94267 but I was instructed to move it here_ 

Most of the undetected problems appear to be for flutter specific lints such as:
- Prefer const with constant constructors. 
- Use key in widget constructors.
- Avoid unnecessary containers.
 
**To reproduce:**
- create a new flutter project
- remove `const` keyword in line 27 (i.e. `home: MyHomePage(title: "Flutter Demo Home Page"),`)
- run `flutter analyze` to see the problem or it'll appear in the IDE problems tab. 
- run `dart fix --dry-run` 
- It'll report `Nothing to fix!` 

**version:**
```
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (6 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4
```

**Comment by DanTup** [comment]
Unfortunately it looks like that comment linked to the wrong repo. This repo is only for the VS Code extension which doesn't cover the `"dart fix"` command - that ships as part of Dart in the SDK. The correct place for issues with `"dart fix"` is https://github.com/dart-lang/sdk.

My understanding is that each fix needs specific support for batch fixing for it to work with `"dart fix"` (and this will only be done for lints where there is a single clear and obvious fix) so it may be worth filing an issue for each specific lint (similar to [this one](https://github.com/dart-lang/sdk/issues/47232) if they don't already exist.

Sorry for the confusion!

**Comment by osaxma** [comment]
Ah no problem --  I just wanted to bring this to attention. I'll file there at least the default ones for a flutter project.

More of a feedback, this weekend I applied `flutter_lints` to an old project and more than 200 problems appeared. Since `dart fix` didn't fix them for me, I had to do a lot of manual fixing and it was time consuming.

Thanks for your support.

**Comment by DanTup** [comment]
> I had to do a lot of manual fixing and it was time consuming

I can imagine! That's exactly the sort of thing "dart fix" (and the "fix all in file" quick-fixes) should really help with so it's definitely worth filing SDK issues when you find things missing (although depending on the age of your SDK, it's very possible some have been fixed for the next SDK release).

Thanks!
