### ISSUE TITLE
"Dart: Sort Members" reorders members but not inline comments

### ISSUE THREAD

**Issue by LeoBound** [Dart-Code/Dart-Code#3697]
**Describe the bug**
soruce.sortMembers reorders variables but not inline comments.

**To Reproduce**
Paste this into a dart file:
```
var variableA; //A
var variableC; //C
var variableB; //B
```

Press CTRL + Shift + P and run Dart: Sort Members.

The same behaviour occurs if you have `"source.sortMembers": true` in your `"editor.codeActionsOnSave"` in your VSCode settings.

**Expected behavior**

```
var variableA; //A
var variableC; //C
var variableB; //B
```

should be sorted to

```
var variableA; //A
var variableB; //B
var variableC; //C
```
 but instead is sorted to
```
var variableA; //A
var variableB; //C
var variableC; //B
```

**Versions (please complete the following information):**
 - VS Code version: 1.62.3
 - Dart extension version: v3.28.0
 - Dart/Flutter SDK version: Dart 2.14.4/ Flutter 2.5.3

**Comment by DanTup** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/e94799ad01e23733f51a033f1b4323e413862053. This change is in the SDK, so the fix will only show up with a future SDK release rather than a Dart-Code release.
