### ISSUE TITLE
Add an option to automatically hot-reload on Save for Flutter projects

### ISSUE THREAD

**Issue by shamrin** [Dart-Code/Dart-Code#370]
It would nice if dart-code would try to invoke flutter hot-reload on save or on save-all. I was surprised that it doesn't work like that. I had this expectation, because web-fronted file system watch-and-build utilities (webpack etc.) work like that. 

FYI, flutter-intellij has recently added experimental option to do just that: https://github.com/flutter/flutter-intellij/pull/1193

**Comment by DanTup** [comment]
We talked about this somewhere, but seems there's no issue for it!

This makes sense, and the linked case has some sensible criteria to check before doing it 👍
