### ISSUE TITLE
Hide members/methods marked as @protected from intellisense

### ISSUE THREAD

**Issue by petrnymsa** [Dart-Code/Dart-Code#3700]
We can annotate class members/methods as `@protected` which can trigger warning if those members are used outside (as public). It would make sense to stop listing those protected members from IntelliSense suggestions.

Example:

```dart
// foo.dart
class Foo {
  bool iAmPublic() => true;

  @protected
  bool iAmProtected() => true;
}
```

```dart
// main.dart
 void main() {
 Foo a = Foo();
 a.iAmProtected();
 }
```
Triggers warning hint
The member 'iAmProtected' can only be used within instance members of subclasses of 

but it is still available in intellisense

![image](https://user-images.githubusercontent.com/21087414/144123774-f34eda91-26c6-4af8-847c-39847e379f79.png)

**Comment by DanTup** [comment]
Thanks for the report! There's an issue tracking this in the SDK (where the language server lives that compiles the completion list for the editor):

https://github.com/dart-lang/sdk/issues/35449
