### ISSUE TITLE
Don't understand peek view for failed tests

### ISSUE THREAD

**Issue by HerrNiklasRaab** [Dart-Code/Dart-Code#3704]
Hello together,

this might be more a question related to VS Code, but I have trouble understanding the peek view for failed tests, with the new native testing experience.

![image](https://user-images.githubusercontent.com/28401593/144407597-cf6183f6-5bf2-46a9-9e4c-d322d76d5f35.png)

This is what I get if one of the tests fails. I have multiple questions here:

- Why does the left part of the peek view show "Test failed. See exception logs above.
The test description was: when recipe has a quanity more than 0 then should show basic ingredients"? This is not helpful at all. I don't need the information about the test description. I know which test has failed, because of where the peek view appeared. Then it says I should see exception logs above. But where should I look to see the logs? I can only see the red inline message, which isn't helpful as well because it just shows what's written in the peek view itself.
- I can find the correct logs on the right side when I look for the most recent test run. But shouldn't this log be in the right part of the peek view?
- The height of peek view is way too small, I always need to resize in order to find the error message.

Am I making something wrong here? I am very confused :D

Best regards,

Niklas

**Comment by DanTup** [comment]
Yeah, I'm not all that happy with this either, but as you guessed - much of it is VS Code's UI. We should try to improve what we can (or raise issues with VS Code) though.

> Why does the left part of the peek view show "Test failed. See exception logs above.
> The test description was: when recipe has a quanity more than 0 then should show basic ingredients"?

That does look slightly odd - how can I cause the same failure you have to look at this? Mine looks slightly more normal, although in the right panel there's an odd extra "Expected: <2>" on the end that isn't in the main log pane 🤔  I'll look into that. Perhaps we're sending it twice, but why it wouldn't then show up twice in the main log I'm not sure.

<img width="1313" alt="Screenshot 2021-12-02 at 11 00 32" src="https://user-images.githubusercontent.com/1078012/144410008-e9f5bb0e-d42d-4cec-a2ed-8d3a95b5d779.png">


> I can find the correct logs on the right side when I look for the most recent test run. But shouldn't this log be in the right part of the peek view?

I'm not sure I understand this question.

> The height of peek view is way too small, I always need to resize in order to find the error message.

Yeah, I find this too. It doesn't seem to remember, and it starts too small. I was sure I'd filed a VS Code issue about this, but can't find it now - do you want to file one there? Even if it doesn't persis the size, I think it should at least be a little bigger by default.

**Comment by DanTup** [comment]
I think some of this weirdness is because of a workaround I put in for https://github.com/microsoft/vscode/issues/136036 which splits the output up into lines on the right (whereas really the block should be a single entry on the right, and you click it to see the multiple lines in the left). I'd like to remove that, but not before https://github.com/microsoft/vscode/issues/136036 is fixed.

**Comment by HerrNiklasRaab** [comment]
> That does look slightly odd - how can I cause the same failure you have to look at this?

Seems like you can reproduce the issue? According to the screenshot here: https://github.com/microsoft/vscode/issues/136036#issue-1038565305

> I can find the correct logs on the right side when I look for the most recent test run. But shouldn't this log be in the right part of the peek view?

Your screenshot clarified it, I was wondering why the output isn't showing in the left part of the peek.

> Yeah, I find this too. It doesn't seem to remember, and it starts too small. I was sure I'd filed a VS Code issue about this, but can't find it now - do you want to file one there? Even if it doesn't persis the size, I think it should at least be a little bigger by default.

Found this, but I don't understand it. Do you? https://github.com/microsoft/vscode/issues/130786

**Comment by DanTup** [comment]
> Seems like you can reproduce the issue? According to the screenshot here: microsoft/vscode#136036 (comment)

Sorry, I wrote that before I did more testing and realised the workaround for the multiline issue was messing this up. Once that VS Code issue is resolved, there will be less entries in the list on the right side, and more of the output should be combined into a single event (shown all at once on the left pane).

> Found this, but I don't understand it. Do you? microsoft/vscode#130786

Looking at the fix, I think a new option was added to open all of the test output in its own pane (so there's more space). Personally I still think there is value in the box being a little bigger though - often you don't need a full screen view of the output, you just want to see more than 5 lines. I would be tempted to file a VS Code issue to see if the height could be increased as well (I would definitely 👍  it).

**Comment by HerrNiklasRaab** [comment]
> Sorry, I wrote that before I did more testing and realised the workaround for the multiline issue was messing this up. Once that VS Code issue is resolved, there will be less entries in the list on the right side, and more of the output should be combined into a single event (shown all at once on the left pane).

Got it!

> I would be tempted to file a VS Code issue to see if the height could be increased as well (I would definitely 👍 it).
Can you link the issue here so people seeing this issue (and myself) can upvote it too!?

**Comment by DanTup** [comment]
Heh, it was a suggestion for you ;) I think [I might raise too many VS Code issues](https://twitter.com/steampipeio/status/1453528550666031116) 😄

I raised it here though, feel free to 👍 !

https://github.com/microsoft/vscode/issues/138347

**Comment by HerrNiklasRaab** [comment]
Ohh, misunderstood. I am sorry! (Upvoted though)

The fact that you raised so many issues, shows that there is still a long way to go :). I am sure they appreciate your feedback, especially because it was already kind of triaged by you!

**Comment by DanTup** [comment]
@HerrNiklasRaab how are things on the latest versions? Is there anything else you think needs addressing, or are things working ok now?

**Comment by DanTup** [comment]
@brianegan I would expect both of those to work. I've filed some specific issues about them:

- https://github.com/Dart-Code/Dart-Code/issues/3962
- https://github.com/Dart-Code/Dart-Code/issues/3963
