### ISSUE TITLE
Copied test doesn't has a test symbly

### ISSUE THREAD

**Issue by HerrNiklasRaab** [Dart-Code/Dart-Code#3709]
If I copy a test it doesn't get the run symbol, even after executing the test once using codelens. Test does appear in the test tree though. 

![image](https://user-images.githubusercontent.com/28401593/144655880-de6eb06c-f479-4cd6-ada2-0362ce26aebd.png)

**Comment by DanTup** [comment]
I suspect this may be the same cause as #3707. When you edit the name of the test, we should detect that there's a new test in the file, but I wonder if we're still somehow attaching it to the same node as the test with the original name.

As a quick workaround when you get into this state, you could run the **Reload Window** command from the palette (it's slightly faster than restarting VS Code) and I expect it'll fix itself. It's possible closing/re-opening the file would too, though I'm less certain about that.

**Comment by DanTup** [comment]
Can you reliably reproduce this? It seems to work as expected for me.. When I clone the test, the gutter icon moves with it (we only support one test per-name now), and then when I rename it so it's unique, I then get one back so there's one for each test:

![Dec-06-2021 11-00-35](https://user-images.githubusercontent.com/1078012/144835101-79ed19ad-cfe7-4da3-a384-19645fd04f14.gif)

If you can share a specific file that's triggering it, that might help. Also check whether there's an ongoing analysis (Analyzing.. in the status bar), as if the server is busy it might take a little longer to update (we need data from the analysis server about where the tests are).

**Comment by DanTup** [comment]
Also, when this occurs, if you click Help -> Toggle Developer Tools are there any errors in the Console tab?

**Comment by DanTup** [comment]
@HerrNiklasRaab can you repro this one? While debugging #3707 I wasn't able to repro this (the symbol always showed up - although while the tests had dupe names, only one of them showed the symbol - that's expected). It's possible the same VS code fix for #3707 will fix whatever happened, but it'd be good to repro and confirm by testing in Insiders. Thanks!
