### ISSUE TITLE
Dart consumes 100% of cpu trying to analyze

### ISSUE THREAD

**Issue by benyaminbeyzaie** [Dart-Code/Dart-Code#3717]
**Describe the bug**
I have this problem some times I open my flutter project in vsCode or android studio the dart analyzer can't analyze the code(suggestions are not working,...) and I can see a process called dart on my activity monitor which consumes near 100% of the cpu and my laptop temperature gets high after few minutes. 

I can solve this problem with deleting the android folder and IOS folder and create flutter project again but it's too hard to do that every time.

I have this problem on Mac, Linux and windows.

I think the cause is a particular library but I don't know which one of them causes the problem and dart can't analyze it!

flutter doctor -v:
```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-arm, locale en)
    • Flutter version 2.5.3 at /Users/beyamin/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (8 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/beyamin/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • SM A505F (mobile) • RZ8M8014BLF • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 96.0.4664.55

• No issues found!
```

**Screenshots**
![image](https://user-images.githubusercontent.com/29250042/145174503-546cb274-3451-4d9f-80fd-098ddde0ea09.png)
**Versions:**
 - VS Code version: 1.62.3 (Universal)

**Comment by DanTup** [comment]
@benyaminbeyzaie could you try enabling the [analyzer instrumentatin log](https://dartcode.org/docs/settings/#dartanalyzerinstrumentationlogfile) in your VS Code settings?

This will log a lot of information (including every request) in and out of the analyzer. It will produce a very large log file, but when this next happens it may be useful to see what the last lines of the log are (for example to see if there is an error, or what the last actions the server performed were before it seemed to get stuck). You'll want to disable the logging again once you've done this.

Can you also run `code --status` in a terminal when you have the project open that you see this problem with, and post the full output here? (you can redact any sensitive paths/etc.)

**Comment by benyaminbeyzaie** [comment]
Just now I deleted the android folder and create flutter again. Next time I will provide logs and open the issue again.
