### ISSUE TITLE
Extend auto lint fixes

### ISSUE THREAD

**Issue by bsutton** [Dart-Code/Dart-Code#3723]
I absolutely love the feature where saving a file automatically applies lints.
This is a huge time saver.

I would like to requests some extensions to this feature.

1) extend it to cover more lints.
Some obvious ones

Unnecessary {} in string.
sort constructors.
use raw string to avoid escapes.
Type annotate public APIs.
Separate the control structure expression from its statement.
Cascade consecutive method invocations on the same reference.
unnecessary_import
sort dependencies in pubspec.yaml
Use => for short members whose body is a single return statement.
Prefer relative imports for files in `lib/`.

Do the following to fixes in one pass - currently you have to save twice.
prefer final
prefer const

2) provide an option to apply this to the entire project in one action.

I probably touch more projects than the average developer and one of my first actions is to apply stronger linting.
I often end up with hundreds of lints that need to be fixed.
I whole of project - just fix them would be a real time saver.

**Comment by DanTup** [comment]
Which fixes are included in auto-fix is controlled by the SDK (it's the same as running `dart fix`), so these should be raised at https://github.com/dart-lang/sdk.

I think there are some general requirements that need to be met before they'd be included though, including that they are they only/obvious fix (eg. not subjective or something where the best fix may vary). Of course, if you've enabled a lint and they are violations of that lint, then that's probably the case.

> provide an option to apply this to the entire project in one action

That one would need to be implemented here (or at least in the LSP server) so warrants its own issue. We could re-use this issue for that, and file SDK issues for the individual things that aren't included in auto-fix but probably should be? I suspect some of them may already have issues open.. there's a bit of work in ensuring the fixes can't produce overlapping edits etc. to do before they're enabled.

**Comment by bsutton** [comment]
I've raised this issue.
https://github.com/dart-lang/sdk/issues/47886
