### ISSUE TITLE
vscode terminal duplicates PATH

### ISSUE THREAD

**Issue by bsutton** [Dart-Code/Dart-Code#3724]
Not certain if this is a vscode or dart code issue and to be honest I'm not certain it has any material impact.

If you open a bash shell (under ubuntu) within the vs-code terminal window the PATH environment variable is duplicated.

e.g.
PATH=/home/me
becomes
PATH=/home/me:/home/me

These paths are coming from .bashrc and .profile so I'm wondering in the terminal is running these twice.

In my normal bash terminal I do not see the same problem.

**Comment by DanTup** [comment]
This sounds like a VS Code issue. I suspect if you open VS Code without a Dart project (such that the Dart extension is not activated), you'll still see the same?

We don't currently do anything with the built-in terminal. I would like to inject the Dart/Flutter SDK paths (based on the SDK you have selected), but I've found many quirks with how VS Code starts the terminal that prevent it working correctly (it's possible some of them are related to your issue).
