### ISSUE TITLE
The quick-fix "Add package to dependencies" in Visual Studio code doesn't work with Dart 3.29.0

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#3728]
Raised by @leRayGorbella at https://github.com/dart-lang/sdk/issues/47906.

---

Hi ! I found that upgrading to the 3.29.0 version of Dart in my Visual Studio Code blocked the use of this quick-fix in visual Studio Code : Add package to dependencies.  

![Capture d’écran 2021-12-11 à 22 33 08](https://user-images.githubusercontent.com/93099788/145696136-8cbd39e5-27fe-4c17-956f-9e8c99446b0f.png)
![Capture d’écran 2021-12-11 à 22 33 21](https://user-images.githubusercontent.com/93099788/145696138-3d5d728a-ca95-4613-af7b-415d6680c1c3.png)

My actual workaround is to downgrade Dart to the previous version 3.28.0. 

Is it intentional or is it truly a bug ? 

Thanks for your time spent on this issue, 
Best regards, 
Adrien

**Comment by DanTup** [comment]
This fix has been included in todays pre-release. If you want to test it out, you can switch to the pre-release version in VS Code:

<img width="1046" alt="Screenshot 2021-12-13 at 18 42 15" src="https://user-images.githubusercontent.com/1078012/145870576-4440552c-2145-475b-a759-e6edc53df2cd.png">

**Comment by leRayGorbella** [comment]
Hi thanks a lot for the fix and the quick response @DanTup ! I will test it tomorrow, I can't tonight ! 

Best regards, 
Adrien
