### ISSUE TITLE
Misleading snippet (initS)

### ISSUE THREAD

**Issue by eli1stark** [Dart-Code/Dart-Code#3732]
I used flutter for a long time and I always thought that code must go before `super.initState();` because of the snippet below.
The right way is to always write code below `super.initState();`  [Explanation](https://stackoverflow.com/a/58400324/12471979)
I think it's misleading to have TODO above `super.initState();` because it's looks like I need to write my code above when it's vice versa.
```dart
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
  }
```

**I suggest to make the  snippet like this:**
```dart
  @override
  void initState() {
    super.initState();
    // TODO: implement initState
  }
```

**Comment by DanTup** [comment]
Thanks for the suggestion! There's an open issue tracking this in the SDK, as the completion for this method is generated there:

https://github.com/dart-lang/sdk/issues/45783

I'll close this one and you can subscribe there for updates. Thanks!
