### ISSUE TITLE
Super class code completion

### ISSUE THREAD

**Issue by cedvdb** [Dart-Code/Dart-Code#3734]
Currently when extending a class it is very tedious to pass each parameters to the super constructor.

This feature https://github.com/dart-lang/language/issues/1855 will resolve most of the verbosity, however code completion should go a step further and be able to generate a constructor with super parameters

```dart
class House {
  final int windows;
  House({required this.windows});
}

class TestHouse extends House {
   // proposed, compiles
   TestHouse({super.windows});
   // alternatively
   TestHouse({int windows}) : super(windows: windows);
   // currently, which does not compile
   TestHouse() : super()
}
```

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/8e407058db84d8b898ce2afbde5bb2c2151f24e3, with https://github.com/dart-lang/sdk/issues/47979 raised about supporting super initializers when available.

Thanks!
