### ISSUE TITLE
Add Dependency should trim package names

### ISSUE THREAD

**Issue by JCKodel** [Dart-Code/Dart-Code#3735]
**Describe the bug**
`Dart: Add Dependency` and `Dart: Add Dev Dependency` don't find the package if there are spaces after the name of the packet, failing silently (it outputs that the package doesn't exist only in the output panel).

**To Reproduce**
1. Go to 'https://pub.dev/packages/awesome_select'
2. Double click on the package name (awesome_select). Notice that the browser automatically selects the space after the package name (at least in Edge).
3. Use the `Dart: Add Dependency` option and paste (it will paste with the trailing space)
4. Package installation fails because it doesn't trim the spaces

**Expected behavior**
Automatically space trimming (to improve productivity: [F1], [Enter], [Ctrl+V], [Enter], we're done, fast fast)
Also, it would be nice a red toast telling me that package was not found.

**Screenshots**
![image](https://user-images.githubusercontent.com/379339/146467089-a557ff3e-6f0a-4a95-9165-9588a044aa44.png)

There is really a space here >.< It should be on the version side, not on the title, but, nothing we can do to change the source.

**Versions (please complete the following information):**
 - VS Code version: 1.63.2
 - Dart extension version: 3.29.0
 - Dart/Flutter SDK version: 2.8.0

**Comment by bean5** [comment]
Awesome!
