### ISSUE TITLE
Extremely slow "Extract method"

### ISSUE THREAD

**Issue by JCKodel** [Dart-Code/Dart-Code#3736]
**Describe the bug**
While using the dot context menu to extract a widget to a new method, it takes about 30 seconds to do so. This particular machine has 64 cores and 256Gb of RAM, running Windows 10.

**To Reproduce**
1. Create a flutter project
2. [Ctrl]+[.] on any widget
3. Choose Extract Method from the context menu

**Expected behavior**
To not take 30 seconds to comply

**Screenshots**
[Vimeo video](https://vimeo.com/657967444/63eff58b8c)

**Versions (please complete the following information):**
- VS Code version: 1.63.2
- Dart extension version: 3.29.0
- Dart/Flutter SDK version: 2.8.0

**Comment by DanTup** [comment]
I suspect this is the same same as #2231, although I'm not able to reproduce it. Can you reproduce this reliably? If not, how often does it occur? I presume it's always only the first time you refactor within a workspace, but is there any other pattern? Is it just after a Flutter upgrade or similar?

I have seen this very infrequently myself, but never been able to trigger it while trying to investigate it.
