### ISSUE TITLE
CRASHED, Failed to Build devtools

### ISSUE THREAD

**Issue by dindasrg** [Dart-Code/Dart-Code#3740]
Run the 'Flutter run' command to launch program in debug mode and encounter this problem (screenshot below). Not sure what cause this to happened, but this never happened before (so I guess maybe because an update/?). This happened both in Android Studio and VS Code.

Here is the screenshot
![image](https://user-images.githubusercontent.com/74523925/146668170-6ec36a2b-b18b-4698-9c82-2ff10363e989.png)

I've try to search a solution before. One of it is to run pub global activate devtools. I run it on C:\Flutter\flutter\bin\cache\dart-sdk\bin, but still got the same issue (screenshot below).

Here is the screenshot
![image](https://user-images.githubusercontent.com/74523925/146668589-3716ec5c-d0a4-489d-84a6-164d88becffc.png)

 - VS Code version: 1.63.0
 - Dart Code extension version: 3.29.0
 - Dart SDK version: 2.14.4
 - Flutter SDK version: 2.5.3

Thanks in advance :)

**Comment by dindasrg** [comment]
Also, here is my flutter doctor (sorry I forgot to attached it)
![image](https://user-images.githubusercontent.com/74523925/146670917-e8aa53a0-0604-4c9b-ad29-270b6204ea44.png)

**Comment by DanTup** [comment]
This repository is for the Dart/Flutter VS Code extensions, but the issues above seem unrelated. I think this should be filed in the Dart SDK repo (https://github.com/dart-lang/sdk) or the Pub repo (https://github.com/dart-lang/pub).

I would first try upgrading to the latest stable Dart/Flutter though (Flutter 2.8 / Dart 2.15) in case it's an issue that's already been fixed.

Thanks!

**Comment by dindasrg** [comment]
Ah, I'm sorry I wasn't really paying attention since I'm not familiar with the community. I was searching for a solution and found this github forum so I directly make a question. Will be careful next time and thank you for the suggestion!

**Comment by DanTup** [comment]
No worries, it's not always obvious where things go (especially as SDK tools power a lot of the functionality inside the VS Code extension). It's better to raise in the wrong place and be redirected than not to raise important issues like this. Thanks! :-)
