### ISSUE TITLE
textDocument/hover fails when browing over an import statement

### ISSUE THREAD

**Issue by timsneath** [Dart-Code/Dart-Code#3742]
```
[Error - 10:51:18 AM] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\timsneath\.vscode\extensions\dart-code.dart-code-3.29.0\out\dist\extension.js:28467:27)
	at Object.dispose (c:\Users\timsneath\.vscode\extensions\dart-code.dart-code-3.29.0\out\dist\extension.js:30618:35)
	at c:\Users\timsneath\.vscode\extensions\dart-code.dart-code-3.29.0\out\dist\extension.js:32865:28
```

**Versions (please complete the following information):**
 - VS Code version: 3.29.0
 - Dart extension version: 1.63.2
 - Dart/Flutter SDK version: Dart SDK version: 2.16.0-118.0.dev (dev) (Thu Dec 16 14:23:20 2021 -0800) on "windows_x64"

**Comment by DanTup** [comment]
@timsneath can you reproduce this? I don't seem to be able to with latest dev. The error is occurring in the VS Code LSP client - when it's disposed (usually when the extension host is shutting down, or we're reloading the extension) it will abort any in-flight requests with this error.

If it happened any other time, perhaps the server crashed/shutdown (the LSP client will try to restart it a few times before giving up, so if it was successful, this might be the only thing you see). I don't have any current theories for what might cause that though.

**Comment by timsneath** [comment]
I do continue to see this -- but I'm so bursty in my usage of VSCode (it's weekends and evenings) that I haven't managed to update the bug. I'll try and capture another instance. Sorry to be flaky.

**Comment by DanTup** [comment]
np, I understand!
