### ISSUE TITLE
Compiler produces a mess after each code change

### ISSUE THREAD

**Issue by sebastianbuechler** [Dart-Code/Dart-Code#3745]
**Describe the bug**
On both my development machines the Flutter compiler seems to get confused after I change even just small pieces of code:
![image](https://user-images.githubusercontent.com/42775578/147486117-15d715ee-4838-4778-ad18-249db56326f0.png)

Suggestions appear multiple times, variable and function names get completely messed up, error under-lining is totally wrong and in general, it finds dozens of errors where there is none. Often it helps to save the file, close and re-open it. Until the next change is done.

**To Reproduce**
1. Open an existing project in VS Code.
2. Make a change to the code.
3. Compiler gets confused

**Versions (please complete the following information):**
 - VS Code version:
 v1.63.2
 - Dart extension version:
 v3.29.0
 - Dart/Flutter SDK version:
 ```dart
$ flutter doctor -v
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19043.1348], locale de-CH)
    • Flutter version 2.5.3 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (2 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
    • Pub download mirror https://pub.dev

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\SebastianBuechler\AppData\Local\Android\sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\SebastianBuechler\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```

**Comment by DanTup** [comment]
I'm not able to reproduce this - although it sounds a little like a race condition I fixed recently that could result in multiple registrations for some language features. The fix is here:

https://github.com/dart-lang/sdk/commit/a3f591f199cd1582e2090dc3fdb8afcceecd5193

I think it only happened if you had analyzer plugins (like `dart_code_metrics` or similar). The fix hasn't made a stable release yet but if you can easily temporarily test a dev release, I'd be interested to know if the issue clears up.

**Comment by sebastianbuechler** [comment]
@DanTup Thanks for the info. Yes, we are using `dart_code_metrics`. 

I don't know how to make sure your fix is running on my system. How can I change from flutter stable to dev with this specific dart commit?

**Comment by DanTup** [comment]
So it turns out my fix hasn't yet made the `dev`/`beta` channels (I also think the `dev` channel might no longer be maintained).  You'll either have to wait for a future update to them to test, or if you really want to test it you could use the `master` channel (although I wouldn't recommend this for general work as it's actively being developed and not had the testing that other channels have had).

If you do want to try, you change channels with [the `flutter channel` command](https://docs.flutter.dev/development/tools/sdk/upgrading#switching-flutter-channels) and then run `flutter upgrade` to sync to the latest version of that channel:

```
flutter channel master
flutter upgrade
```

And to switch back to the stable channel:

```
flutter channel stable
flutter upgrade
```

**Comment by sebastianbuechler** [comment]
@DanTup Thanks, I appreciate your help. 

I wanted to check first the new flutter version 2.8.1 and restarted VS Code. Now I can't reproduce it with the new flutter version for now (although I had this issue for a couple of weeks now and across multiple flutter versions). 

I will test with 2.8.1 for the upcoming days and reopen this ticket if necessary again.

Thanks again!

**Comment by DanTup** [comment]
Ah, interesting. Perhaps something in the newer version alters the timing slightly that makes the race condition less likely to occur. You might be lucky and not see it again, or it might show up again until you ahve the fix above (but that should eliminate it completely). Let me know if you do hit issues again anyway. Thanks!

**Comment by incendial** [comment]
@DanTup could you please tell, was the fix merged into beta? If not, is there an approximate date for that? It's kinda a huge problem for Dart Code Metrics users.

**Comment by DanTup** [comment]
@incendial I'm not involved with Flutters release/branching process so I can't say when things are being merged, however I can see Flutter's beta branch is currently:

```
Flutter 2.10.0-0.2.pre • channel beta • git@github.com:DanTup/flutter.git
Framework • revision 73adb1406a (2 days ago) • 2022-01-19 17:02:56 -0600
Engine • revision 74b74b10ea
Tools • Dart 2.16.0 (build 2.16.0-134.1.beta) • DevTools 2.9.2
```

When looking at the commit at https://github.com/dart-lang/sdk/commit/a3f591f199cd1582e2090dc3fdb8afcceecd5193, I can see the same Dart SDK version in the tags:

<img width="1241" alt="Screenshot 2022-01-21 at 20 58 54" src="https://user-images.githubusercontent.com/1078012/150599288-6d698902-93dc-422d-b145-6320b80ec1a0.png">

So my understanding is that yes, the fix should be in the current Flutter beta branch (be sure to run `flutter upgrade` after switching channels). If you still see the issue there (and are sure you're on the same version as above - specifically the Dart version), then please let me know :-)

**Comment by incendial** [comment]
> I'm not involved with Flutters release/branching process so I can't say when things are being merged

Oh, sorry, I assumed that you might be notified about the branch being merged.

> So my understanding is that yes, the fix should be in the current Flutter beta branch (be sure to run flutter upgrade after switching channels). If you still see the issue there (and are sure you're on the same version as above - specifically the Dart version), then please let me know :-)

Thank you for checking! Sure, I'll ask to recheck the problem, hope it won't reproduce.

**Comment by DanTup** [comment]
I believe it won't, but if it does (and you're ensured you're on the latest `beta`) branch, please do let me know so I can look into why. Thanks!
