### ISSUE TITLE
When completing constructor suggestion, insert parameter list with trailing comma

### ISSUE THREAD

**Issue by dancojocaru2000** [Dart-Code/Dart-Code#3747]
**Is your feature request related to a problem? Please describe.**
When selecting a constructor from the suggested completions, if the constructor has required named parameters, they are inserted inline. 

This makes formatting annoying and makes the completion somewhat useless, since filling parameters by pressing the tab key is canceled when moving the cursor at the end to insert the trailing comma to obtain proper formatting.

**Describe the solution you'd like**
An option to change the completion from:

```dart
ElevatedButton(onTap: null, child: null)
```

To:

```dart
ElevatedButton(
  onTap: null,
  child: null,
)
```

**Comment by DanTup** [comment]
Thanks for the suggestion! This should be filed in the SDK at https://github.com/dart-lang/sdk, as the code completion is generated by the analysis server.

I don't think there's currently an ideal place for settings like this in the server. Some behaviour is influenced by lints (for example, if you have [require_trailing_commas](https://dart-lang.github.io/linter/lints/require_trailing_commas.html) enabled then perhaps this should happen automatically (to avoid generating code that violates the lint), although enabling the lint probably shouldn't be the only way to get this behaviour (and the lint also has some exceptions).

If you file an issue in the SDK, please post the link back here for anyone that finds this issue and wants to go 👍  it/etc.

Thanks!
