### ISSUE TITLE
Debug permission for spawning Processes (Segmentation Fault Error)

### ISSUE THREAD

**Issue by jlnrrg** [Dart-Code/Dart-Code#3748]
**Describe the bug**
This is a follow up issue of this [one](https://github.com/miguelpruivo/flutter_file_picker/issues/903).
It seems that using the vsCode dart debugger (snap) has missing permissions causing a segmentation fault error when spawning the Process `zenity --file-selection`.
When using the vsCode terminal `flutter run` everything works as intended.
When using the vsCode F5 (inhouse) debugger the process will quit with a segmentation fault error.
My question would be which command the `dart` `launch` actually runs and how permissions are handled for it, as there seems to be a difference compared to the terminal.

**To Reproduce**
1. Create an empty flutter project on linux
<details><summary>my version</summary>

```bash
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```
</details>

2. Add the package [flutter_file_picker](https://github.com/miguelpruivo/flutter_file_picker)
3. Press F5 to use the vsCode debugger using this config
<details><summary>launch.json</summary>

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "start",
            "request": "launch",
            "type": "dart"
        },
    ]
}
```
</details>

4. Call `final file = await FilePicker.platform.pickFiles(dialogTitle: 'Test');`

**Expected behavior**
The native file picker should spawn.

**Versions (please complete the following information):**
 - VS Code version: 1.63.2 (Linux x64 5.4.0-91-generic snap)
 - Dart version: 2.15.0
 - Flutter version: 2.8.0

**Comment by DanTup** [comment]
Did you install Flutter via Snap? There are some known issues that if your VS Code and Flutter are not both of the same type (eg. both must be Snap, or not Snap) there are some weird issues (I think related to show things are sandboxed). I don't know enough about Snap to fully understand the issues, but there are some details about this in other issues:

- https://github.com/flutter/flutter/issues/73743
- https://github.com/Dart-Code/Dart-Code/issues/3562

So for now, I'd either install the non-Snap version of Code, or the Snap version of Flutter (and be sure VS Code locates that version, and not the existing non-Snap version).

If you're still seeing issues when using the same types, let me know and I'll try to get a Linux install set up I can try to reproduce/debug on.

Thanks!

**Comment by jlnrrg** [comment]
With the non-snap version installed the issue is resolved.
Thank you a lot for the assist :smile:.
