### ISSUE TITLE
Extend `customToolReplacesArgs` to allow replacing all tool args

### ISSUE THREAD

**Issue by point-source** [Dart-Code/Dart-Code#3749]
This is not working as I expect based on the prior information [in this issue](https://github.com/Dart-Code/Dart-Code/issues/3656). I have created a brand new dart project, a simple cli app. For my launch config, I first tried this:

```
        {
            "name": "toolTest",
            "request": "launch",
            "type": "dart",
            "program": "bin/main.dart",
            "customTool": "echo",
        }
```

Output:
`--enable-asserts --enable-vm-service=0 --pause_isolates_on_start=true --no-serve-devtools --write-service-info=file:///var/folders/h0/y0mhxm317slfr5k149cfxvfr0000gn/T/dart-vm-service-7630.json -DSILENT_OBSERVATORY=true bin/main.dart`

So far so good. I then tried to see if I could remove args:

```
        {
            "name": "toolTest",
            "request": "launch",
            "type": "dart",
            "program": "bin/main.dart",
            "customTool": "echo",
            "customToolReplacesArgs": 2,
        }
````

Output:
`--enable-asserts --enable-vm-service=0 --pause_isolates_on_start=true --no-serve-devtools --write-service-info=file:///var/folders/h0/y0mhxm317slfr5k149cfxvfr0000gn/T/dart-vm-service-6a28.json -DSILENT_OBSERVATORY=true bin/main.dart`

Hmm, that's odd. Nothing got removed. Maybe it need tool args to replace them?
```
        {
            "name": "toolTest",
            "request": "launch",
            "type": "dart",
            "program": "bin/main.dart",
            "customTool": "echo",
            "customToolReplacesArgs": 2,
            "toolArgs": [
                "test",
                "arg"
            ]
        }
```

Output:
`test arg --enable-asserts --enable-vm-service=0 --pause_isolates_on_start=true --no-serve-devtools --write-service-info=file:///var/folders/h0/y0mhxm317slfr5k149cfxvfr0000gn/T/dart-vm-service-6280.json -DSILENT_OBSERVATORY=true bin/main.dart`

So it appears that "echo" replaces "dart" as the tool but customToolReplacesArgs maybe does nothing?

```
        {
            "name": "toolTest",
            "request": "launch",
            "type": "dart",
            "program": "bin/main.dart",
            "customTool": "echo",
            "toolArgs": [
                "test",
                "arg"
            ]
        }
```

Output:
`test arg --enable-asserts --enable-vm-service=0 --pause_isolates_on_start=true --no-serve-devtools --write-service-info=file:///var/folders/h0/y0mhxm317slfr5k149cfxvfr0000gn/T/dart-vm-service-19d2.json -DSILENT_OBSERVATORY=true bin/main.dart`

Same thing. How do I get the arg replacement to work?

Additionally, if I try this with a flutter project, it completely ignores "customTool" and continues running as normal even though I'm using the exact same launch config. How does the extension determine whether it's a flutter project or not and why does it ignore the customTool arg?

_Originally posted by @point-source in https://github.com/Dart-Code/Dart-Code/issues/3656#issuecomment-1002830930_

**Comment by DanTup** [comment]
`customToolReplacesArgs` is only intended to replace the args that are part of the tool invocation itself and not the arguments passed to it. The goal is to allow you to replace `"dart run test: test"` with a custom tool, or `flutter run` with a custom tool.

Replacing the arguments passed _to_ the tool is not possible and would be quite complicated, as these arguments vary depending on a number of things (including SDK version, whether you run with debugging, what you're invoking, etc.) and the order is not guaranteed.

Can you describe what it is you're trying to do, and maybe I can suggest an alternative way?

> Additionally, if I try this with a flutter project, it completely ignores "customTool" and continues running as normal even though I'm using the exact same launch config. How does the extension determine whether it's a flutter project or not and why does it ignore the customTool arg?

If it's not working at all, that sounds like a bug - please file a separate issue with repro steps and I'll take a look.

> How does the extension determine whether it's a flutter project

It uses the presence of the Flutter SDK in pubspec.yaml to decide if a project is Flutter or not.

**Comment by point-source** [comment]
> intended to replace the args that are part of the _tool_ invocation

The original tool or the custom tool?

> args that are _part of_ the tool invocation itself and not the arguments _passed to it_

What is an example of an arg that is part of the tool invocation but is not passed to it? As for args that are passed, do you mean passed via the "toolArgs" array or the "args" array?

Sorry, this is so hard for me to fully grasp. The terminology could mean so many things because we have two sets of tools and two sets of args and so it makes it difficult to discuss here unless we choose very specific terms for each thing. I propose that we consider the following:

"**tool**": The original tool that would have been invoked if "customTool" were not set (essentially either "dart" or "flutter" in this case)
"**customTool**": The tool that will be invoked instead of the original tool ("echo" in this case)

"**nativeArgs**"?: Guessing these are args that are somehow built into the invocation and not generally modifiable?
"**args**"?: Args pass to the tool by the extension but not by the launch.config (things like `--enable-vm-service=0`)
"**passedArgs**"?: Args provided by the user in the launch.config's "args" array (intended for the original tool)
"**toolArgs**"?: Args provided by the user in the launch.config's "toolArgs" array (intended for the customTool)

Do I have that terminology roughly correct? Can you edit it as necessary to clarify?

Anyway, what I was expecting is that by setting that value to "1", it would change the output of my test from:
`--enable-asserts --enable-vm-service=0 --pause_isolates_on_start=true --no-serve-devtools --write-service-info=file:///var/folders/h0/y0mhxm317slfr5k149cfxvfr0000gn/T/dart-vm-service-6a28.json -DSILENT_OBSERVATORY=true bin/main.dart`

to:
`--enable-vm-service=0 --pause_isolates_on_start=true --no-serve-devtools --write-service-info=file:///var/folders/h0/y0mhxm317slfr5k149cfxvfr0000gn/T/dart-vm-service-6a28.json -DSILENT_OBSERVATORY=true bin/main.dart`

Note that the first arg `--enable-asserts` is removed. This would allow me to manually replace that arg with one of my own. If that's not what this is for, can you give me an example of which part of the tool invocation would get removed?

**Comment by DanTup** [comment]
It turns out the implementations have not been consistent between the Dart-Code DAP and the SDK DAP, so one of them needs to change.

Thinking more about this, I think allowing `customToolReplacesArgs` to replace all of the built-in args (eg. in `dart test --enable-asserts foo.dart` allow `--enable-asserts` to be included, and not only `test`) probably makes the most sense (and is what the new SDK DAP is already doing).

So, I think the change I'm going to make is probably what you'd like - allowing `customToolReplacesArgs` to replace things like `--enable-asserts`. However, be mindful that the order of these arguments is not guaranteed, so if you need to just remove one of them (for example the third one), that might not be possible.

**Comment by DanTup** [comment]
A slight correction from above.. `customToolReplacesArgs` will replace all built-in tool args _added by the debug adapter_. The example I gave above `--enable-asserts` is not one of these, as it is added by the client. That can be removed by setting `enableAsserts: false` in the launch config. The other debug adapter-added flags (--start-paused, etc.) are all now replacable.

**Comment by point-source** [comment]
DanTup,

Thanks for taking a look and working on this so quickly. To be clear, my use case doesn't necessarily need that specific functionality. I was mostly just trying to conceptualize the operation of the tool so I had my head wrapped around it and could use it in a predictable manner going forward.

That said, the changes you made appear to extend functionality in a useful way. My only concern is that it is still rather opaque in what it is doing. I know this was mentioned in the original feature request and the conclusion was that using documentation and the "echo" tool, one could discover the operation.

I just wanted to throw it out there that we could perhaps just do an exclude list of args rather than a iteration based removal. That way, even though discovery remains opaque, the implementation on the config side is explicit and users can see exactly which args are being removed. This also solves the position problem.

Something like:
```
"excludeArgs": [
    "--start-paused"
]
```

**Comment by DanTup** [comment]
@point-source yeah, that had crossed my mind recently too, but I don't want this to get too complicated without a solid use case/example. Generally if you want to put a tool in place of Dart/Flutter, it should be _very_ compatible with them, so the best thing is for them to implement the same interface.

The changes made above were a fairly simple extension of existing behaviour that's necessary for internal Bazel workspaces and I think will solve most use cases (even if you have to set the number high to remove everything, then just add things back in `toolArgs`), but if you have a concrete use where this isn't sufficient please do file a new issue with the details.

Dart-Code will soon move over to an SDK-shipped debug adapter, which means functionality like this needs to be also implemented there, and will be shared by other editors too (and thus becomes harder to change, as we need to consider compatibility) so there will likely be a higher bar for implementing things than when the debug adapter just lived here (and could be changed at the same time as the only editor using it).
