### ISSUE TITLE
Linter for flutter/dart broken: Undefined class 'StreamSubscription'. 

### ISSUE THREAD

**Issue by nathantew14** [Dart-Code/Dart-Code#3753]
Issue Type: <b>Bug</b>

1. Create a new, blank .dart file with Dart extension enabled.
2. Create a blank method/class/function then type, letter by letter, without autocomplete, "StreamSubscription".
3. The linter labels it as an Undefined class.
4. video demo of it happening: [https://streamable.com/s4e9d7](url)

Extension version: 3.29.0
VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.24GB free)|
|Process Argv|--crash-reporter-id abd0c248-37a5-4c50-8a26-d9a89124c0c8|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vscop341:30404997
vsrem710:30416614
py55gd98:30411514
vscexrecpromp3t1:30407762

```

</details>

**Comment by DanTup** [comment]
This seems to be expected behaviour to me - can you explain why you think it should not produce an error? If you type the class manually, you are not importing `dart:async` so the class is undefined. If you select from the code completion, it will automatically add the `import` and therefore you won't get the error.

**Comment by nathantew14** [comment]
@DanTup oh, I was under the false impression that `dart:async` doesn't have to be imported anymore at all because you didn't need to for `async` functions and `await`, and I also didn't notice the import line being added... sorry.

**Comment by DanTup** [comment]
np! `async` and `await` are language keywords so don't need a library to be imported. There are some classes (like `Future`) that are also always available without importing `dart:async`, however that's not the case for all classes in the `dart:async` library.
