### ISSUE TITLE
Make it easier to switch between package:build custom configurations

### ISSUE THREAD

**Issue by soumyamahunt** [Dart-Code/Dart-Code#3754]
**Is your feature request related to a problem? Please describe.**
With [custom configurations](https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-build-with-multiple-configurations) it becomes a chore when switching between configurations as we have to modify command line argument.

**Describe the solution you'd like**
Provide widget in VSCode status bar indicating the configuration currently selected and allow user to switch to different configuration by clicking on it(similar to how simulator selection works).

**Describe alternatives you've considered**
Manually modifying tool `toolArgs` field in `launch.json`.

**Comment by DanTup** [comment]
I think this may be better handled by adding an additional `launch.json` entry. It can then be switched between on the Debug side bar, or the existing status entry for debug configs:

<img width="299" alt="Screenshot 2022-01-04 at 15 28 50" src="https://user-images.githubusercontent.com/1078012/148082752-339c6c15-0746-478b-9865-b9d8ccbcacde.png">

This would avoid having to build package:build-specific functionality into the extension and adding more entries to the status bar (which is something VS Code is trying to reduce with some [upcoming changes](https://github.com/microsoft/vscode/issues/129037)).

Is there a reason why you think this doesn't work well enough?

**Comment by soumyamahunt** [comment]
@DanTup I added custom configurations:
```json
{
    "configurations": [
        {
            "name": "Example",
            "type": "dart",
            "request": "launch",
            "program": "lib/main.dart"
        },
        {
            "name": "Example-Debug",
            "type": "dart",
            "request": "launch",
            "program": "lib/main.dart",
            "args": [
                "--config",
                "debug"
            ]
        },
        {
            "name": "Example-Staging",
            "type": "dart",
            "request": "launch",
            "program": "lib/main.dart",
            "args": [
                "--config",
                "staging"
            ]
        },
        {
            "name": "Example-Production",
            "type": "dart",
            "request": "launch",
            "program": "lib/main.dart",
            "args": [
                "--config",
                "production"
            ]
        }
    ]
}
```
as build [docs](https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-build-with-multiple-configurations) suggest:
> If you need other configurations in addition to dev and release, you can define multiple build.yaml files. For instance if you have a build.debug.yaml file you can build with --config debug and this file will be used instead of the default build.yaml. The dev and release flavors still apply. dart run build_runner serve --config debug will use the dev_options in build.debug.yaml, while dart run build_runner build --config debug --release will use the release_options in build.debug.yaml.

Add on running those custom configurations I see error from vscode:
> Could not find an option named "config".
> Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
> Exited (64)

**Comment by DanTup** [comment]
@soumyamahunt those docs/flags are for `build_runner`, but the debugger runs `flutter`.

You previous mentioned you had this working using `toolArgs`, but I'm not sure why that would've produced a different result. Can you clarify how you had it set up before when it worked (but required modifying `toolArgs` to change config)?
