### ISSUE TITLE
very slow evaluation of variables when hovering over it

### ISSUE THREAD

**Issue by jamesdixon** [Dart-Code/Dart-Code#3755]
**Describe the bug**
When hovering over/evaluating an expression in the debug console, it takes a very long time to see the result of that evaluation.

**To Reproduce**
Unfortunately, I'm not 100% sure on the steps to get the environment into a state where this happens. I have tried uninstalling both the Dart/Flutter extensions.

**Expected behavior**
I expect that when I hover over a variable after hitting a breakpoint or evaluating an expression in the console, I see the value/result of that expression immediately rather than waiting up to 10 seconds.

**Screenshots**
Here's a video showing the issue: https://share.getcloudapp.com/GGuE8oeY

**Versions (please complete the following information):**
 - VS Code version: 1.63.2
 - Dart extension version: 3.29.0
 - Dart/Flutter SDK version: 2.5.3

**Comment by DanTup** [comment]
Thanks for the detailed report/video!

Are you able to share a project where you're seeing this?

If not, could you try:

- See if setting the `dart.evaluateGettersInDebugViews` setting to `false` speeds things up (this will disable evaluation of getters in the list which I suspect is what's taking the time)
- Once ready to repro, run the **Dart: Capture Debugging Logs** command to start capturing logs, then hover over and wait for the hover box to appear, and then click **Cancel** on the logging notification to stop logging and open the log file (which will hopefully show the timings, and requests being sent for evaluating the getters)

Thanks!
