### ISSUE TITLE
Disable peek for failed tests

### ISSUE THREAD

**Issue by Hannnes1** [Dart-Code/Dart-Code#3757]
This feature was introduced not too long ago; a popup that shows up when a test fails. I find the feature quite annoying, mostly because I can already see almost the exact same thing in the debug console. I would therefore like a way to disable the feature.

I have looked around to see if there is a way to do this already, but I couldn't find anything. So if there is a setting or similar, I would be glad if someone pointed me in the right direction.

To be clear this is the feature I am talking about:
![bild](https://user-images.githubusercontent.com/47989573/147829887-d6a18ff8-a0cd-478c-b020-72c833d7e4b8.png)

**Comment by DanTup** [comment]
This feature is actually from VS Code and not the extension. It looks like there are a few settings in VS Code to control its behaviour:

<img width="831" alt="Screenshot 2022-01-02 at 12 38 59" src="https://user-images.githubusercontent.com/1078012/147875968-1bcd24fe-c721-4925-9126-2b99b3b1784f.png">

Hope this helps!

**Comment by Hannnes1** [comment]
Ah, thank you! I wasn't sure if it was a VS Code feature or not, since it was introduced in an update of this extension.
