### ISSUE TITLE
vscode: flutter outline commands is not working on windows

### ISSUE THREAD

**Issue by garawaa** [Dart-Code/Dart-Code#3758]
When right click on widget and select a command from context menu, anything is not working.

**Comment by DanTup** [comment]
Can you provide some sample code, and a specific widget/command you're trying so I can try to reproduce?

**Comment by garawaa** [comment]
Steps
1. Just create a new flutter  project for example counter app.  
2. Open it in vscode
3. Open flutter outline
4. Choose a widget
5. Right click choose command from context menu.
My flutter sdk version 2.8.1 os windows10 intel i7 7700 ram16gb vs version: latest version

**Comment by DanTup** [comment]
Ah, got it - I can reproduce. Thanks!
