### ISSUE TITLE
Failed to start DevTools 

### ISSUE THREAD

**Issue by zerowu49** [Dart-Code/Dart-Code#3763]
**Describe the bug**
When opened the VSCode with Dart plugin updated, got error like this.

**To Reproduce**
1. Open the VSCode with Dart plugin enabled
2.  Error shown in bottom right

**Expected behavior**
I haven't experienced this error before.

**Screenshots**
<img width="662" alt="Screen Shot 2022-01-03 at 20 35 01" src="https://user-images.githubusercontent.com/22422143/147936570-698f5f4c-9431-4dec-9359-43814022c9e4.png">

**Versions (please complete the following information):**
 - VS Code version: 1.63.2 (Universal) Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
 - Dart extension version: v3.32.0
 - Dart/Flutter SDK version: v2.2.3

**Comment by DanTup** [comment]
There was a broken version of DevTools published recently which was retracted, but if you're not on the latest version of the Dart/Flutter SDKs, it does not understand package retraction (see https://github.com/flutter/devtools/issues/3549#issuecomment-1003962841).

Until a new version of DevTools is published, the available fixes are:

- Update to the latest stable Dart/Flutter SDK
- [Disable the automatic updating of DevTools in VS Code](https://user-images.githubusercontent.com/1078012/147755389-8db3e5c2-c926-4fcb-9e8c-3533b370c156.png), then run `dart pub global activate devtools 2.8.0` then restart VS Code.

Let me know if you still have issues after this. Thanks!

**Comment by DanTup** [comment]
A new version of DevTools has been published that fixes this, so it's no longer necessary to disable updates in the VS Code settings. Just run `dart pub global activate devtools` and leave the setting ticked and everything should be good.
