### ISSUE TITLE
Unexpected LF symbols in test output

### ISSUE THREAD

**Issue by timsneath** [Dart-Code/Dart-Code#3765]
**Describe the bug**
Unexpected LF symbols in test output

**To Reproduce**
Run tests from https://github.com/timsneath/advent-of-code-2021/tree/3ee7779f735cdaa9e66d547bf9485c2211dcdff2

**Expected behavior**
Cleaner output

**Screenshots**
![image](https://user-images.githubusercontent.com/2319867/148110679-ac11e15d-6ca0-4cfc-a930-0e0c43b07d52.png)

**Versions (please complete the following information):**
 - VS Code version: Version: 1.63.2 (Universal)
 - Dart extension version: 3.32.0
 - Dart/Flutter SDK version: Dart SDK version: 2.16.0-134.0.dev (dev) (Thu Dec 23 21:23:33 2021 -0800) on "macos_x64"

**Comment by DanTup** [comment]
This text comes form VS Code - I raised it at https://github.com/microsoft/vscode/issues/138336 and it has been fixed, but not yet released (they'll just be replaced with spaces). Thanks!

**Comment by DanTup** [comment]
This seems to be happening again. The VS Code regex looks like it might only do a `\r` before a `\n` so perhaps we're somehow ending up with additional `\r` on their own.

**Comment by DanTup** [comment]
This turned out to be the same issue. The fix in VS Code was a JavaScript regex that only replaces the first instance (missing `/g` - something I've never done 😆). I guess by fluke I only tested it with a string with a single newline.

I've re-raised with VS Code at https://github.com/microsoft/vscode/issues/145320.

**Comment by DanTup** [comment]
This has been fixed in VS Code now. Screenshot from Insiders:

<img width="974" alt="Screenshot 2022-03-21 at 10 01 21" src="https://user-images.githubusercontent.com/1078012/159239559-51bdf21f-1666-48cb-b11c-e4d503cceb97.png">
