### ISSUE TITLE
Show value of static const strings when hovered over

### ISSUE THREAD

**Issue by petrnymsa** [Dart-Code/Dart-Code#3766]
It would be nice (if possible) upon hovering over `const / static` string variables to show which value they contain so I am not forced to jump between definition and it's usage. 

E.g.

```
static const FOO = 'bar'
```

somewhere else 

```dart
final local = FOO;
```
Suppose that we hover on "FOO" - in that case it will show `String FOO` and on second line `package:name....`. 

Extend it to something like

```
String FOO
"bar"
package:name
````

**Comment by DanTup** [comment]
If you hold down `Cmd`/`Ctrl` while hovering something, VS Code should show a preview of the declaration. This works for everything, not just consts - but for consts it allows you to see the values:

<img width="511" alt="Screenshot 2022-01-18 at 10 51 30" src="https://user-images.githubusercontent.com/1078012/149923662-26bb747c-44db-473d-adac-61563b0910eb.png">

Is this sufficient for your needs?

**Comment by petrnymsa** [comment]
> If you hold down `Cmd`/`Ctrl` while hovering something, VS Code should show a preview of the declaration. This works for everything, not just consts - but for consts it allows you to see the values:
> 
> <img alt="Screenshot 2022-01-18 at 10 51 30" width="511" src="https://user-images.githubusercontent.com/1078012/149923662-26bb747c-44db-473d-adac-61563b0910eb.png">
> 
> Is this sufficient for your needs?

Didn't know about this and yes this is enough 👍 Closing issue as VSCode itself handle this. Thank you.
