### ISSUE TITLE
When hovering over error show error before api doc.

### ISSUE THREAD

**Issue by bsutton** [Dart-Code/Dart-Code#3772]
So this one is very much a personal preference thing but I suspect other devs may have the same experience.

When I have a line of code which contains a lint or an error I typically hover over the line to see the error.

The problem is that dart-code displays the api doco and then the error.
The result is that I often need to scroll down to see the error or lint.

My proposal is that if a line contains an error or a lint then that should be displayed followed by the documentation.
So the reverse of what occurs now.

As a second issue the errors seem to be displayed in the wrong order (from least useful to most useful).
The source error always appears to be the last one in the list.
It would be better if they we reversed.

**Comment by DanTup** [comment]
Yep, this would be sensible - but unfortunately it's controlled by VS Code and not the extension :( There's an open issue here (although it's been open for 3 years so doesn't seem like a high priority):

https://github.com/microsoft/vscode/issues/73120
