### ISSUE TITLE
Add quick fix to doc references.

### ISSUE THREAD

**Issue by bsutton** [Dart-Code/Dart-Code#3773]
If I have a doc reference in my code:

/// Throws a [DCliException]

and DCliException isn't imported I'm not offered a quick fix to import the necessary library/package.

Instead I see:
Only reference in scope identifiers in doc comments.dart comment_references

and no quick fix.

can we add a quick fix to import then necessary library/package.

**Comment by DanTup** [comment]
That sounds reasonable to me, although it'd need to be implemented in the server. Could you file at https://github.com/dart-lang/sdk? Thanks!
