### ISSUE TITLE
Instant `[Run|Debug]` are unavailable on arm64 macOS

### ISSUE THREAD

**Issue by Sunbreak** [Dart-Code/Dart-Code#3775]
**Describe the bug**
Instant `[Run|Debug]` are unavailable on arm64 macOS
![image](https://user-images.githubusercontent.com/7928961/148871826-afc79661-c0cf-475d-8dc0-941cf22d6a77.png)

**To Reproduce**
1. Configue `dart.flutterSdkPath` or `dart.sdkPath` in `.vscode/settings.json`
```json
{
    // "dart.flutterSdkPath": "~/google/flutter-2.8.x"
    "dart.sdkPath": "~/google/dart-2.15.x"
}
```
2. Open a dart file with `main` entry point

**Expected behavior**
Instant `[Run|Debug]` are available
![image](https://user-images.githubusercontent.com/7928961/148871806-4c77afcb-4724-4e14-a781-0765e1473f3f.png)

**Screenshots**
...

**Versions (please complete the following information):**
 - VS Code version: 1.63.2 (Universal)
 - Dart extension version: v3.32.0
 - Dart/Flutter SDK version: Flutter 2.5.3/2.8.1，Dart 2.15.1

**Comment by DanTup** [comment]
I don't seem to be able to reproduce this (using the ARM download on an M1 Macbook), although I noticed the server starts up a lot faster and think I may see a race condition... If you modify the file in some way (eg. add a new method), do the links then appear?

**Comment by Sunbreak** [comment]
The code complete has some little problem as well. Something related or another problem?

BTW: x64 is `macOS 11.6.2`, arm64 is `macOS 12.1`

![image](https://user-images.githubusercontent.com/7928961/148971680-414d896c-3081-4c54-ac32-19504a9b1362.png)

**Comment by DanTup** [comment]
Could you also post the full output of running `code --status` when you have only this project open in VS Code? Thanks!

**Comment by Sunbreak** [comment]
> It seems like your analysis server hasn't started up correctly (which will prevent almost all language functionality from working).
> 
> Can you click Help -> Toggle Developer Tools in VS Code, then click on the Console tab and see if you have any errors listed?

![image](https://user-images.githubusercontent.com/7928961/149042563-87e9299a-2b3e-41df-9457-8938b46b9409.png)

```
workbench.desktop.main.js:sourcemap:2982 [twxs.cmake]: Cannot register 'cmake.cmakePath'. This property is already registered.
_logMessageInConsole @ workbench.desktop.main.js:sourcemap:2982
workbench.desktop.main.js:sourcemap:577   ERR Error received from starting extension host (kind: LocalProcess)
workbench.desktop.main.js:sourcemap:577   ERR Error: The value of "err" is out of range. It must be a negative integer. Received 1
workbench.desktop.main.js:sourcemap:1720 Overwriting grammar scope name to file mapping for scope source.dart.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/dart/syntaxes/dart.tmLanguage.json.
New grammar file: file:///Users/wangkun42/.vscode/extensions/dart-code.dart-code-3.32.0/syntaxes/dart.json
register @ workbench.desktop.main.js:sourcemap:1720
workbench.desktop.main.js:sourcemap:577   ERR undefined
workbench.desktop.main.js:sourcemap:577  WARN Settings Sync: Accounts are not initialized
```

**Comment by Sunbreak** [comment]
> Could you also post the full output of running `code --status` when you have only this project open in VS Code? Thanks!

```sh
wangkun42@wangkun42s-MacBook-Pro logic_conf.dart % code --status

Version:          Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS Version:       Darwin arm64 21.2.0
CPUs:             Apple M1 (8 x 24)
Memory (System):  16.00GB (0.07GB free)
Load (avg):       1, 2, 1
VM:               0%
Screen Reader:    no
Process Argv:     . --crash-reporter-id f74568b7-ccc3-471c-ba92-a8ecd4fd11fc
GPU Status:       2d_canvas:                  enabled
                  gpu_compositing:            enabled
                  metal:                      disabled_off
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          enabled
                  opengl:                     enabled_on
                  rasterization:              enabled
                  skia_renderer:              disabled_off_ok
                  video_decode:               enabled
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %	Mem MB	   PID	Process
    0	   164	  5567	code main
    0	    66	  5570	   gpu-process
    1	    16	  5572	   utility-network-service
    0	    82	  5583	   shared-process
    0	    16	  5595	     ptyHost
    0	    33	 20204	     watcherServiceParcelSharedProcess
    0	   246	 20202	   window (k380_conf.dart — logic_conf.dart)
    0	   115	 20211	   window (undefined)

Workspace Stats:
|  Window (k380_conf.dart — logic_conf.dart)
|    Folder (logic_conf.dart): 62 files
|      File types: dart(15) yaml(9) h(7) json(2) md(2) snapshot(1) dill(1)
|                  yml(1) gitignore(1) packages(1)
|      Conf files: github-actions(1) settings.json(1)
```

**Comment by DanTup** [comment]
Hmm, there's nothing obvious there. Could you try running the **Dart: Open Extension Log** command to see whether there's anything interesting in that log?

<img width="664" alt="Screenshot 2022-01-12 at 11 01 48" src="https://user-images.githubusercontent.com/1078012/149128277-0aa469af-a625-4515-af46-0bbfad1c1068.png">

It's possible the command will fail if the extension isn't properly activated, in which case try running the **Developer: Show Running Extensions** command and see whether Dart is listed, and whether it shows any error or anything there.

**Comment by Sunbreak** [comment]
I think it is something wrong with `VS Code` itself.

<img width="729" alt="Screen Shot 2022-01-12 at 7 33 37 PM" src="https://user-images.githubusercontent.com/7928961/149133079-94ad021c-65a5-48c9-a4c8-bb7f13ccede9.png">

---

Git module wouldn't work as well

<img width="804" alt="Screen Shot 2022-01-12 at 7 35 39 PM" src="https://user-images.githubusercontent.com/7928961/149285823-ff5dcbf3-601e-4913-b942-564d2fc93ddf.png">

**Comment by Sunbreak** [comment]
Restart `VS Code` solves the problem. I'd like to close it for now

**Comment by DanTup** [comment]
Ah, glad to hear it's sorted. I wonder if the extension host crashed somehow. If you see it again and it's affecting more than just Dart, it may be worth filing an issue in the VS code repo.

And ofc, if you see issues that seem related to only Dart, please do let me know. Thanks!
