### ISSUE TITLE
"Attempted to insert a duplicate test item ID" when modifying tests after running them using testGoldens from golden_toolkit

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#3776]
```dart
import 'package:golden_toolkit/golden_toolkit.dart';
import 'package:test/test.dart';

void main() {
  group('foo', () {
    testGoldens('test 1', (tester) async {});
  });
}
```

Then **Test: Run All Tests**, wait for results, then try to modify the file (eg. add a new linebreak):

<img width="1260" alt="Screenshot 2022-01-11 at 15 16 43" src="https://user-images.githubusercontent.com/1078012/148969607-480e6c49-c802-4605-882c-b7298284d33d.png">

**Comment by DanTup** [comment]
This looks like it's caused by `@isTestGroup` on the `testGoldens` function. We get a test group from the discovered that uses the outline, and a test with the same name from the results.

The package should be updated, but we should not crash in this case. We could use ID formats for groups/tests to avoid colliding like this.

**Comment by DanTup** [comment]
Looks like this method used to create a group, but was changed in https://github.com/eBay/flutter_glove_box/commit/f1d486c77853fe3b17276455a94fec083bc2b6c8.

I've filed a PR for the annotation at https://github.com/eBay/flutter_glove_box/pull/140.

**Comment by moonytoes29** [comment]
@DanTup  - even without the golden tests being inside the group, we get some console errors.
Perhaps the overall number of `testGoldens` I have in our work project is what's causing the testing status, code lens and test count to be flaky or for the most part wrong?

I've just tested my work code after commenting out all the `testGolden` calls. All 229 of them. And ran the tests a number of times. The count appears to pick up the tests. No errors are coming up on the console. All seems a lot better.

So I think this might be promising. :)

**Comment by DanTup** [comment]
@moonytoes29 a new version of golden_toolkit [was published with the annotation fix](https://github.com/eBay/flutter_glove_box/pull/140#issuecomment-1010417030). If you can upgrade to that, everything should be good now :-)

**Comment by moonytoes29** [comment]
> @moonytoes29 a new version of golden_toolkit [was published with the annotation fix](https://github.com/eBay/flutter_glove_box/pull/140#issuecomment-1010417030). If you can upgrade to that, everything should be good now :-)

Wish I could. But alongside your simple fix, they've now made that latest version dependent on having SDK >=2.15. Which my project is not!.

So I'll have to do a fork to apply just your fix for now. Then look to migrate sooner rather than later.

**Comment by DanTup** [comment]
Ah, that's a shame. Although if it's just you and not a team, I'd probably just modify the file in the pub cache to have `@isTest`. I don't think that's likely to change anything except fix this (otherwise, if you use the pre-release extension, it at least won't stop you running tests, you'll just have some repeated nodes in the tree).
