### ISSUE TITLE
Autocomplete is triggered while writing a comment

### ISSUE THREAD

**Issue by osaxma** [Dart-Code/Dart-Code#3783]
**Describe the bug**

https://user-images.githubusercontent.com/46427323/149633868-8616eb92-a25c-4c9a-a7e2-1a7656d9985b.mov

**To Reproduce**
I tried to isolate the issue in a separate file but I couldn't reproduce it even using the same set of imports. It's happening only in the file where the recording was taken. 

**Expected behavior**
Autocomplete shouldn't be triggered when typing within a comment.

**Versions:**
 - VS Code version: `1.63.2`
 - Dart extension version: `3.32.0`
 - Dart/Flutter SDK version:
  ```
  Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
  Framework • revision 77d935af4d (4 weeks ago) • 2021-12-16 08:37:33 -0800
  Engine • revision 890a5fca2e
  Tools • Dart 2.15.1
  ```

**Comment by DanTup** [comment]
Is there any more content after the comment shown here? Any other differences you can see (line endings, trailing newlines, etc.?)

There is code that's supposed to prevent completion in comments, although there have been some edge cases with how comments at the end of the file are represented in the AST before.

If you make an exact copy of this file (not the content, but the file on disk) in a new project, does it occur there?

**Comment by osaxma** [comment]
This should reproduce:

```dart
// <type here>

/// some doc comments
class SomeClass {}
```

I guess because the comment is followed by a documentation comment (if removed, no issue).

**Comment by DanTup** [comment]
I can repro, thanks!

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/5455047ed0732e7198711c2a1d2b47d336d4e4b0. It's an SDK change so will show up in a future SDK release rather than a Dart-Code release.
