### ISSUE TITLE
Port forward when running from remote

### ISSUE THREAD

**Issue by MatiasLGonzalez** [Dart-Code/Dart-Code#3786]
**Is your feature request related to a problem? Please describe.**
Similarly to how the [Live server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) extension port forwards when you are connected to a host via SSH, it would be helpful if when I'm debugging the web app the Flutter VS Code extension automatically forwards it to the client's web browser.

**Describe the solution you'd like**
When I press F5, if I'm remoting to a server via SSH, the extension should forward the web app to the client's browser.

**Comment by DanTup** [comment]
Can you clarify exactly what your app/setup is. This should already be working for Flutter apps when running on the web (via the web-server or Chrome devices), but it's not clear if that's what you're using.

**Comment by MatiasLGonzalez** [comment]
Sure! I store my code on a Linux server which I remote to via SSH on VS Code on my Windows machine, when developing i.e. JavaScript, I use the [Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) extension to serve the html file from the Linux server to my Windows machine, from what I understand it forwards the Windows machine localhost:random-port to the Linux server and it serves the html file which I can view on my browser on my Windows machine. Currently the `flutter doctor` warns you if you don't have Chrome installed (which doesn't make much sense in a server). Since I installed Chrome on the server to pass the `flutter doctor` checks, and when I try to run the webpage it attempts to open Chrome on the server instead of on my Windows machine. I could just forward Chrome to Xming on my Windows but I don't believe this is ideal long term since the Live Server can achieve this for a similar problem.

**Comment by DanTup** [comment]
@MatiasLGonzalez for a remote SSH setup, you should use the web-server device instead of Chrome (you do not need to install Chrome on the remote machine, and can ignore the `doctor` warnings in this case).

Using the web-server device should automatically forward the ports and open your local Chrome (or default browser) at the mapped URL. You should be able to select it by clicking on the device in the status bar (bottom right) and then clicking Web Server.

Please let me know if you don't see this, or it doesn't seem to work as expected.

**Comment by MatiasLGonzalez** [comment]
I see! I was trying to run it manually with `flutter run -d web-server --web-hostname=windows-ip --web-port=some-port` with no avail, I missed the option was available in VS Code, it works now though sadly it seems like hot reload and other options are not available on firefox 😕

**Comment by DanTup** [comment]
> I was trying to run it manually with `flutter run`

Ah, when you run things in the terminal the extension is not involved at all. We have no ability to interact with anything run that way. You need to run using the Run menu (or similar commands) so the extension can communicate with the Flutter process to map the ports (it also allows debugging, etc.).

> sadly it seems like hot reload and other options are not available on firefox

Yeah, I think right now running in debug mode using the web-server device requires the Dart Debug extension. This is to allow control of the debugging in the browser. Normally, when you run using Chrome locally, Flutter launches it with some flags to allow it to connect and debug. However when using the web-server device that isn't possible, so a Chrome extension is used to proxy to the Chrome debugger APIs.
