### ISSUE TITLE
Vs Code locks up on M1 Mac

### ISSUE THREAD

**Issue by BenjaminFarquhar** [Dart-Code/Dart-Code#3790]
My vs code locks up constantly for about 5 seconds. I used [vs code extension bisect](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) to identify the extension causing the problem, and unfortunately, it was this one.

**To Reproduce**
1. Delete some code
2. use ctrl + z, ctrl + shift + z continuously to undelete the code and redelete the code.

**Expected behavior**
It redo's and undo's the code deletes and stays responsive

**Actual behavior**
The environment locks up for 5ish seconds

**Versions (please complete the following information):**
 - VS Code version: 1.63.2
 - Dart extension version: 3.32.0
 - Dart/Flutter SDK version: 2.8.1
 
OS: MacOS Moterey Version 12.1(21C52) 

Vs Code:
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:38:17.605Z (1 mo ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.2.0

**Comment by DanTup** [comment]
I don't seem to be able to reproduce this. Can you confirm exactly what you mean by "locks up"? If you mean VS Code itself (it's UI) is locking up, then there's likely a VS Code issue here. The extension code all runs in a separate process from VS Code deliberately so an extension can never hang the editor - if that's happening (even if it's triggered by an extension) I'm certain the VS Code team would like to fix it.

Could you also try capturing a log with **Dart: Capture Analysis Server Logs** when reproducing this to see whether there's anything interesting in there?

- Run the [**Dart: Capture Analysis Server Logs** command](https://dartcode.org/docs/logging/#capture-analysis-server-logs)
- Reproduce the issue
- Click **Cancel** on the logging notification to stop logging and open the log
- Remove anything sensitive from the log (it will include parts of your source code, so best to reproduce on a new empty project)
- Attach the log here (or in a gist)

Thanks!

**Comment by BenjaminFarquhar** [comment]
@DanTup yes it hangs. I will post that when I get some time.

**Comment by ShimronAlakkal** [comment]
I had somewhat of a similar problem(on the same device), but, fortunately I now don't face any issues.

I just cleared the cache of vs code and then uninstalled and re-installed the extension. I also got vs code updated. I haven't faced any issues then. I guess it was some corrupt files.

Have you had any macOS updates?

**Comment by BenjaminFarquhar** [comment]
@ShimronAlakkal @DanTup 

Yes I did that too, I fixed it by doing these terminal commands:

```
- ~/.vscode
- ~/Library/Application Support/Code
- ~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.microsoft.vscode.sfl*
- ~/Library/Caches/com.microsoft.VSCode.ShipIt
- ~/Library/Caches/com.microsoft.VSCode
- ~/Library/Preferences/ByHost/com.microsoft.VSCode.ShipIt.*.plist
- ~/Library/Preferences/com.microsoft.VSCode.helper.plist
- ~/Library/Preferences/com.microsoft.VSCode.plist
- ~/Library/Saved Application State/com.microsoft.VSCode.savedState
```

Then reinstalled all my vs code extensions. I haven't faced the issue since. So yeah it was not this extension. Cheers for looking into it.

**Comment by DanTup** [comment]
Great, glad you sorted it. If you see it come back, it may be worth filing a VS Code issue for them to investigate.
