### ISSUE TITLE
a dot in the lower right corner on flutter toggle debug painting 

### ISSUE THREAD

**Issue by ottomossei** [Dart-Code/Dart-Code#3792]
When I run "flutter toggle debug painting" in vscode, I see a dot in the lower right corner, is this a bug?

**Screenshots**
<img width="378" alt="screen" src="https://user-images.githubusercontent.com/62988022/150286812-b3e3e697-1951-40d5-8495-bf9b2e3e1189.png">

main.dart
```main.dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        backgroundColor: Colors.black,
        body: Container(),
      ),
    );
  }
}
```

**Versions **
vscode version: 1.63.2
vscode extension (Flutter v3.32.0)
Flutter 2.8.1
Dart 2.15.1

**Comment by DanTup** [comment]
I'm not sure if this is a bug - it does look odd though. The debug painting isn't done by the VS Code extension, but rather by Flutter itself. The extension just exposes a command that gets passed on to Flutter to turn it on, so this would be better raised at https://github.com/flutter/flutter/issues. Thanks!
