### ISSUE TITLE
'await' applied to 'Future<UserCredential> Function()', which is not a 'Future'

### ISSUE THREAD

**Issue by afzl-wtu** [Dart-Code/Dart-Code#3797]
I am using latest version of Dart Flutter extension. I am using Firebase_auth library which contains a function called signInAnonymously and ofcourse it is Future function. But my VS COde exteinsion is giving me warning when I use await infront of it:
![image](https://user-images.githubusercontent.com/64379149/150527778-6ba4d067-2c79-4828-90e2-c59fbe7dc5b9.png)

and when I hover upon it:
![image](https://user-images.githubusercontent.com/64379149/150527986-972769a9-10bf-414d-9fe6-9e6cf61041fb.png)

Update if I use in full form it works and accepts it as future: You can see both lines here:
![image](https://user-images.githubusercontent.com/64379149/150572440-33023824-7dce-4994-b7ed-5e51404f8245.png)

![Screenshot (22)](https://user-images.githubusercontent.com/64379149/150573416-e53a9068-c11c-4165-b944-6983fe9ca981.png)

Steps to reproduce:
Use below code:
import 'package:firebase_auth/firebase_auth.dart';

class AuthClass {
  FirebaseAuth _auth = FirebaseAuth.instance;

// Signing in Annonymously
  Future<String?>? guest() async {
    try {
      final a = await _auth.signInAnonymously;
      UserCredential userCredential = await FirebaseAuth.instance.signInAnonymously();
    } catch (e) {
      return 'Error Ocured';
    }
  }
}

**Comment by DanTup** [comment]
The message is correct. `_auth.signInAnonymously` is a function that _returns_ a `Future`, but you are not calling the function (you do not have parenthesis `()` on the end). So here you are trying to `await` the _function_. In the message it says the type is `Future<UserCredential> Function()` (note the `Function()` on the end indicating it's a function that returns a Future).

If you add the parens (as you have on the similar code in the next line), the error should go away.

**Comment by afzl-wtu** [comment]
Oh sorry.

**Comment by afzl-wtu** [comment]
Big Mistake. Sometime it happens, It would be great if you add support for missing paranthesis.

**Comment by DanTup** [comment]
np!

> It would be great if you add support for missing paranthesis.

It's not clear to me what this would look like. Do you mean an improved error message (for example adding "Try adding parenthesis if you intended to call the function"), or something different?

**Comment by afzl-wtu** [comment]
Exactly what you have said. "Try adding parenthesis if you intended to call the function"
