### ISSUE TITLE
Creating a new dart project results an error

### ISSUE THREAD

**Issue by yahu1031** [Dart-Code/Dart-Code#3805]
**Describe the bug**
When I try to create a new dart project I get `Command 'Dart: New Project' resulted in an error (command 'dart.createProject' not found)` prompt.

**To Reproduce**
1. Open VSCode without any workspace.
2. Press `F1` and search for `Dart: New Project`.
3. Hit enter.

**Expected behavior**
Must continue with further options generally the extension provides.

**Screenshots**
![image](https://user-images.githubusercontent.com/35523357/151672500-d2daf40e-a6fb-4c2c-b820-8626323b70fc.png)

**Versions:**
  - VSCode Version: 1.63.2
  - OS: Darwin arm64 21.3.0
  - Dart extension version: v3.32.0(Stable)
  - Dart/Flutter SDK version: 2.15.1(Dart)/2.8.1(Flutter)

**Comment by DanTup** [comment]
Could you try clicking Help -> Toggle Developer Tools in VS Code and then on the Console tab, and see if you see any errors/warnings listed there after this happens? Thanks!

**Comment by yahu1031** [comment]
It is working now. You could close this issue and I will post the info about this if I get it again. IDK why it is working. I don't restart the VSCode or system. But it is working.

**Comment by DanTup** [comment]
Sure, please let me know if you see it again. Thanks!
