### ISSUE TITLE
Dart analyzer crashes on MacOS

### ISSUE THREAD

**Issue by GP4cK** [Dart-Code/Dart-Code#3806]
**Describe the bug**
After coding for a while, as I'm typing, the linter will display that I have a syntax error (because I haven't finished typing). However even after I'm done typing, the error is still displayed. The only way out is to restart the analysis server.
I didn't have this issue with 3.27.2 and 3.27.0.

**To Reproduce**
Unfortunately, I'm not able to reproduce consistently. It just seems to happen after a while.

**Screenshots**
![image](https://user-images.githubusercontent.com/2680243/151688323-a9719e18-8455-49f6-a658-621e7d0652e9.png)

**Versions (please complete the following information):**
- Issue Type: `Bug`
- Extension Name: `dart-code`
- Extension Version: `3.32.0`
- OS Version: `Darwin x64 20.6.0`
- VS Code version: `1.63.2`

**Comment by DanTup** [comment]
@GP4cK do you happen to be using the dart_code_metrics or another similar analyzer plugin?

If so, I think this may be the same as #3745 which has been fixed in the server and will show up in an upcoming Dart/Flutter SDK release.

**Comment by GP4cK** [comment]
Yes I'm using dart_code_metrics.
I'll close this then. Sorry for the duplicate.

**Comment by DanTup** [comment]
np, thanks for confirming!
