### ISSUE TITLE
Dart '@override' token take two different syntax colors.

### ISSUE THREAD

**Issue by safield** [Dart-Code/Dart-Code#3807]
The '@override' keyword is two different colors. One fore the '@' character and one the the 'override' string.

Reproduced with the following theme as a minimal example.

{
    "type": "dark",
    "$schema": "vscode://schemas/color-theme",
    "name": "Test Theme",
    "semanticHighlighting": true,
    "colors": {
    },
    "tokenColors": [
        {
            "name": "Types declaration and references",
            "scope": [
                "support.type",
            ],
            "settings": {
                "foreground": "#ff3333"
            }
        },
        {
            "name":"Annotations",
            "scope":"storage.type.annotation.dart",
            "settings": {
                "foreground": "#3333ff"
            }
        }
    ],
}

**Comment by DanTup** [comment]
This is currently working as intended. Annotations can be getters or Constructors and coloured like those. Eg. `@deprecator` will color `deprecated` as a getter and `@Deprecated()` colors it like a constructor.

It is possible to customise this if you're prefer them all one way though - see https://github.com/Dart-Code/Dart-Code/issues/3621#issuecomment-951001007 for an example of how to do this.

**Comment by safield** [comment]
> This is currently working as intended. Annotations can be getters or Constructors and coloured like those. Eg. `@deprecator` will color `deprecated` as a getter and `@Deprecated()` colors it like a constructor.
> 
> It is possible to customise this if you're prefer them all one way though - see [#3621 (comment)](https://github.com/Dart-Code/Dart-Code/issues/3621#issuecomment-951001007) for an example of how to do this.

We might not be on the same page. You mentioned that the strings 'deprecated' and "@Deprecated()' will be colored differently.

What I am reporting is one string being colored two different colors. So "@Deprecated()" has the '@' colored differently than the rest of the string.
