### ISSUE TITLE
Add Dart "Open Observatory" and Flutter "Open Observatory Timeline" commands

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#381]
@devoncarew I saw this in the IntelliJ source but it isn't using Flutter Daemon though it doesn't depend on flutter Daemon - is it useful for non-flutter apps?

**Comment by devoncarew** [comment]
The timeline view is likely not super useful for non-flutter apps. The general observatory may be; perhaps just a command to open that?
