### ISSUE TITLE
VSCode - Debug logs are not consistent between platforms

### ISSUE THREAD

**Issue by ValentinVignal** [Dart-Code/Dart-Code#3812]
**Describe the bug**
I'm working with VSCode on macOS, when running an app through the VSCode debugger, the logs are not consistent between platforms.

**To Reproduce**
1. run `flutter create my_app`
2. `cd my_app`

add the file `.vscode/launch.json` : 
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Run",
      "request": "launch",
      "type": "dart",
      "program": "lib/main.dart"
    },
  ]
}
```

Then for iOS, macOS, and chrome, press `F5` to run the application with VSCode. The logs are not consistent. For example, `"💪 Running with sound null safety 💪"` log is only visible on chrome

**Chrome:**

<details>

<summary>VSCode launch</summary>

```
Launching lib[/main.dart]() on Chrome in debug mode...
lib/main.dart:1
This app is linked to the debug service: ws://127.0.0.1:53511[/ozhDRx6xrqM]()%3D[/ws]()
Debug service listening on ws://127.0.0.1:53511[/ozhDRx6xrqM]()=[/ws]()
💪 Running with sound null safety 💪
Connecting to VM Service at ws://127.0.0.1:53511[/ozhDRx6xrqM]()=[/ws]()
```

</details>

<details>

<summary>Command line</summary>

Running with `flutter run lib/main.dart`

```
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             16.1s
This app is linked to the debug service: ws://127.0.0.1:54213/a29Uqn05_vY=/ws
Debug service listening on ws://127.0.0.1:54213/a29Uqn05_vY=/ws

💪 Running with sound null safety 💪

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:54213/a29Uqn05_vY=
The Flutter DevTools debugger and profiler on Chrome is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:54213/a29Uqn05_vY=
```

</details>

**iOS:**

<details>

<summary>VSCode launch</summary>

```
Launching lib[/main.dart]() on iPhone 12 Pro Max in debug mode...
lib/main.dart:1
Xcode build done.                                            8.1s
Connecting to VM Service at ws://127.0.0.1:54344[/4nX6XeDauZg]()=[/ws]()
```

</details>

<details>

<summary>Command line</summary>

Running with `flutter run lib/main.dart`

```
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running Xcode build...                                                  
 └─Compiling, linking and signing...                      2,328ms
Xcode build done.                                            8.0s
Syncing files to device iPhone 12 Pro Max...                        91ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on iPhone 12 Pro Max is available at:
http://127.0.0.1:54468/GF1QrQ6IbsE=/
The Flutter DevTools debugger and profiler on iPhone 12 Pro Max is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:54468/GF1QrQ6IbsE=/
```

</details>

**macOS:**

<details>

<summary>VSCode launch</summary>

```
Launching lib[/main.dart]() on macOS in debug mode...
lib/main.dart:1
Connecting to VM Service at ws://127.0.0.1:54540[/cAD_JOHmRow]()=[/ws]()
```

</details>

<details>

<summary>Command line</summary>

Running with `flutter run lib/main.dart`

```
Launching lib/main.dart on macOS in debug mode...
Building macOS application...                                           
Syncing files to device macOS...                                   104ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on macOS is available at: http://127.0.0.1:53306/4qNSLtaDOHU=/
The Flutter DevTools debugger and profiler on macOS is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:53306/4qNSLtaDOHU=/
```

</details>

Because of that, I spent quite some time trying to find why my app was not running null-safely on macOS and iOS (it was not the same code). But from this issue, I believe it is running null-safely but it is only not logged?

**Expected behavior**
The logs should be consistent between the platforms.

**Screenshots**

**Versions (please complete the following information):**
 - VS Code version: `1.63.2`
 - Dart extension version: `v3.27.2`
 - Flutter extension version: `v3.27.0`
 - Dart/Flutter SDK version: 
Running `flutter --version` :
```
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (7 weeks ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1
```

**Comment by DanTup** [comment]
This seems to be a difference in Flutter behaviour, so should be filed at https://github.com/flutter/flutter/.

For non-web, the line is printed here:

https://github.com/flutter/flutter/blob/d7688ca0930fe80d162361be30405a15c929ada9/packages/flutter_tools/lib/src/run_hot.dart#L1012

This is part of `printHelp()`, so it only appears when Flutter prints the shortcut keys for using the terminal. When running from the IDE (which runs `flutter run --machine`), this code is not called, so the message is not printed.

However for Web, it looks like both the standard and `--machine` versions go through a different path and into `resident_web_runner` which always prints the message:

https://github.com/flutter/flutter/blob/61a0add2865c51bfee33939c1820709d1115c77d/packages/flutter_tools/lib/src/isolated/resident_web_runner.dart#L638

I suspect the best fix will be to move the message in `run_hot.dart` to somewhere called in both modes so that the message is always printed for all types (it seems like useful info to have in the IDE output too).

If you raise in Flutter, please post the link back here. Thanks!

**Comment by ValentinVignal** [comment]
Thank you @DanTup I opened an issue on the flutter repo https://github.com/flutter/flutter/issues/97754

**Comment by ValentinVignal** [comment]
Hi @DanTup https://github.com/flutter/flutter/issues/97754 was closed in favour of this issue because the issues comes from the logs on VSCode.

**Comment by DanTup** [comment]
@ValentinVignal sorry for inconvenience. I've re-opened the Flutter issue and added my notes from above so it's clearer why the issue occurs and why it needs to be fixed in Flutter. I'll close this one as there's nothing to do here, and will follow up on that issue if necessary. Thanks!
