### ISSUE TITLE
Add commands for easier running in Release mode

### ISSUE THREAD

**Issue by peekpt** [Dart-Code/Dart-Code#3815]
![Captura de ecrã 2022-02-04, às 14 12 31](https://user-images.githubusercontent.com/222385/152543758-c98325ee-db50-4425-9f8f-5bbab6a99a18.png)

It would be nice to have by default this Flutter modes in launch.json:
Run,
Profile
Debug
Release

and in  the main file: Run | Debug | Profile | Release
![Captura de ecrã 2022-02-04, às 14 24 58](https://user-images.githubusercontent.com/222385/152545480-77139d44-07a7-443b-ae58-db6963275a62.png)

Maybe also add something for building all the modes like: flutter build --split-per-abi  

Build (apk)
Build (apk splitted)
Build (release)
Build (iOS)
Build (web)
Build (Win)
...

**Comment by DanTup** [comment]
These values come from the `launch.json` so we can't directly contribute them here. We could change the defaults/snippets that go into launch.json. It probably doesn't make sense to have Run/Debug in there, as that's controlled by whether you use `Run -> Debug` or `Run -> Run Without Debugging` (or use `F5`/`Ctrl`+`F5`). Adding an option to run Release builds may make sense though.


> Maybe also add something for building all the modes like: flutter build --split-per-abi

I don't think `build` makes sense here, as this is for launching a debug session. Build already exists under the **Run Build Task** command, although we probably don't have all of these variations.
