### ISSUE TITLE
Dart Code gives a syntax error on the correct code

### ISSUE THREAD

**Issue by aeb-dev** [Dart-Code/Dart-Code#3828]
**Describe the bug**
`dart run` runs the code but VS Code tells me there is an error on the code.

**To Reproduce**
use the following code
```
import "dart:ffi";

import 'package:ffi/ffi.dart';

@FfiNative<
    Handle Function(
        Handle,
        Pointer<
            NativeFunction<
                Pointer<Void> Function(
                    Pointer<Utf8>, IntPtr)>>)>("myFunc")
external Object myFunc(Object x,
    Pointer<NativeFunction<Pointer<Void> Function(Pointer<Utf8>, IntPtr)>> y);

Pointer<Void> call(Pointer<Utf8> x, int y) {
  print(y.toDartString());
  return nullptr;
}

void main() {
  myFunc("aa", Pointer.fromFunction(call));
}
```

You should see this error on the VS Code
![image](https://user-images.githubusercontent.com/11612804/153771628-55c8a37a-c66a-4e40-a95e-65b4096abab2.png)

error as text:
```
Only classes extending NativeFieldWrapperClass1 can be passed as Pointer.
Pass as Handle instead.dart(ffi_native_only_classes_extending_nativefieldwrapperclass1_can_be_pointer)
```

As a result when I hit f5 it says `Build error exist in you project`
![image](https://user-images.githubusercontent.com/11612804/153771699-a50c26d7-179a-4228-88a9-034e366b2441.png)

However if run the code with `dart run` it runs instead of reporting a syntax error.

Note that the run result will result in an exception, ignore it.

**Expected behavior**
VS Code should not report and error.

**Versions (please complete the following information):**
 - VS Code version: Version: 1.65.0-insider (user setup)
Commit: 921264bfe3ffbbfe5ec8c4b08214b88e2148fa3e
Date: 2022-02-04T05:16:29.546Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

also tested on 
- Version: 1.65.0-insider (user setup)
Commit: bb221a61d29deabd99ee9431736d04f2175cb596
Date: 2022-02-11T05:19:13.554Z
Electron: 16.0.8
Chromium: 96.0.4664.110
Node.js: 16.9.1
V8: 9.6.180.21-electron.0
OS: Windows_NT x64 10.0.19042

 - Dart extension version: v3.34.0
 - Dart/Flutter SDK version: Dart SDK version: 2.16.0 (stable) (Mon Jan 31 15:28:59 2022 +0100) on "windows_x64"

**Comment by DanTup** [comment]
Thanks for the report! I'm not familiar enough with FFI to understand the reason for the warning being produced here, but the it comes from the Dart analyzer which ships in the SDK (you'll see the same error running `dart analyze` on the file).

If you file this at https://github.com/dart-lang/sdk, someone there more familiar with this should be able to provide an explanation (or if required, a fix).

Thanks!
