### ISSUE TITLE
Breakpoints are active after their deletion

### ISSUE THREAD

**Issue by doradsoft** [Dart-Code/Dart-Code#3829]
**Describe the bug**
Breakpoints are active after their deletion.

**To Reproduce**
It reproduces in my PC like this:
1. add breakpoint.
2. let code to reach it.
3. delete breakpoint.
4. let code to reach it again.
Tell me what else to attach and I do so.

**Expected behavior**
Breakpoints shouldn't be active after deletion.

**Screenshots**
![image](https://user-images.githubusercontent.com/5598420/153810926-a83dcc93-e678-44ef-a9a5-02795497f201.png)

**Versions (please complete the following information):**
 - VS Code version: 1.64.2
 - Dart extension version: v3.34.0
 - Dart/Flutter SDK version: 2.10.1

**Comment by DanTup** [comment]
I'm having trouble reproducing this. I tried like this:

```dart
Future<void> main() async {
  for (int i = 0; i < 10; i++) {
    print(i); // Breakpoint here
    await Future.delayed(const Duration(seconds: 1));
  }
}
```

I hit the breakpoint, removed it, then clicked Resume. The app ran to completion without any more breaking.

Can you reproduce with this? If not, can you provide a small sample you can reproduce with?

Could you also try capturing some logs:

- Run the [**Dart: Capture Debugging Logs** command](https://dartcode.org/docs/logging/#capture-debugging-logs)
- Reproduce the issue
- Click **Cancel** on the logging notification to stop logging and open the log
- Remove anything sensitive from the log
- Attach the log here (or in a gist)

Thanks!

**Comment by doradsoft** [comment]
It's been like that for about a week until I found time to open this issue.
I tried your minimal snippet and it wasn't reproduced. Then I tried again in the real project with the capturing and it just fixed.
I don't know how to explain this 😯. Nevertheless, as long as it doesn't reproduce I assume this issue is useless. If it happens again I'll reopen.

**Comment by doradsoft** [comment]
Fortunately (🙄hmmm...) it reproduces. I didn't find the exact factors, but it sure happens. This time I am armed with a log capturing it. It's not [DanTup](https://github.com/DanTup)'s minimal reproduce but I made mine as minimal as I could:
```
class SomeState extends State<Some>
    with TickerProviderStateMixin, AutomaticKeepAliveClientMixin<Some> {
  @override
  Widget build(BuildContext context) {
    return Material(child: GestureDetector(onHorizontalDragEnd: _onDragEnd));
  }

  void _onDragEnd(DragEndDetails details) {
    // last time it happened my breakpoint was (wasn't...) here
  }
}
```
There is a bit noise at the log beginning, but at least I shut the capturing down immediately after reproducing.
[Dart-Code-Log-2022-01-01 16-24-58.txt](https://github.com/Dart-Code/Dart-Code/files/8061568/Dart-Code-Log-2022-01-01.16-24-58.txt)

**Comment by doradsoft** [comment]
Thanks @DanTup, it seems so, yes. Now it reproduces consistently.
If and only if I remove the breakpoint while hot restart is happening it reproduces.
Is any further info needed?

**Comment by DanTup** [comment]
Can you confirm exactly what steps you're using? I did try to remove the breakpoint during a restart without any luck. Perhaps if you can tell me exactly what you're doing, it will help. For example:

- Are you clicking restart or using reload-on-save?
- Are you clearing the breakpoint before you trigger the restart or immediately after?
- How long is the restart taking? (I was testing with a small app, which perhaps was restarting faster?)

Can you also confirm what platform you're on?

**Comment by doradsoft** [comment]
Steps:
1. Add a breakpoint
2. Press Ctrl+Save ("Hot restart")
3. Remove BP
4. Reach code
Reload takes about 5s~
I'm done for today. Thanks for your pleasant support and let me know if something else is needed.

**Comment by DanTup** [comment]
@doradsoft please file a new issue and include details and steps to reproduce the issue you're seeing. Thanks!

**Comment by gachuigachui** [comment]
Happens to me a lot.

![Image](https://github.com/user-attachments/assets/2997a062-26f1-488d-b3a7-bee2313543a3)
