### ISSUE TITLE
VS Code / Dart - Variable inspector shows error string

### ISSUE THREAD

**Issue by sunilguptasg** [Dart-Code/Dart-Code#3836]
**Describe the bug**
I am unable to inspect variables. Only see "<function errorString(error) {>"

**To Reproduce**
The method that is causing the issue is here:

```dart
  dynamic sendRequest(String remoteFileName, String method, XFile file, int length) async {
    final uri = Uri(path: baseURL + '/' + nameOfZone + '/' + Uri.encodeFull(remoteFileName));
    final req = http.MultipartRequest(method, uri);

    var s = await file.readAsBytes();
    String baseName = basename(file.path);

    final multipartFile = http.MultipartFile('picture', http.ByteStream.fromBytes(s), length, filename: baseName);

    req.files.add(multipartFile);

    req.fields['User-Agent'] = 'Java-BCDN-Client-' + version;
    req.fields['AccessKey'] = apiKey;
    req.fields['Content-Type'] = 'application/octet-stream';

    switch (method) {
      case "PUT":
        final res = await req.send();
        await for (var value in res.stream.transform(utf8.decoder)) {
          debugPrint(value);
        }
        break;
    }
  }
```

**Expected behavior**
I should be able to inspect the variables

**Screenshots**
![Screenshot 2022-02-18_17-48-34-534](https://user-images.githubusercontent.com/93675025/154685741-68b5c3a2-7e05-4c23-9c43-2e346165c748.png)

**Versions (please complete the following information):**
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.1 21C52 darwin-arm, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.64.2)

**Comment by DanTup** [comment]
Thanks! This looks like a dwds issue so I've filed it at https://github.com/dart-lang/webdev/issues/1519. If it turns out not to be, I'll re-open here (or file in the relevant place).
