### ISSUE TITLE
Icon previews in hovers are broken for icons that start with numbers

### ISSUE THREAD

**Issue by Rishaba-Jain** [Dart-Code/Dart-Code#3843]
**Describe the bug**
I was working with icons and found that: 

1. Few icons are not previewed while hovering but are previewed near line numbers (checked the location where the icons are stored and it seems that there might be a mismatch in the mapping of names - screenshots attached)
2. Few icons are not previewed while hovering nor near the line numbers (checked the location where the icons are stored and it seems that the icons are not there)

**To Reproduce**
1. Please try to preview the icons in VSCode

**Expected behavior**
The icons must be previewed while hovering, near the line numbers.

**Screenshots**
![Screenshot (1)](https://user-images.githubusercontent.com/71686718/155660963-5dd4ccf4-ff4a-4134-8cb9-01afde40289d.png)
![Screenshot (2)](https://user-images.githubusercontent.com/71686718/155660966-14ec81b8-8ed9-4ed7-803d-187100e2fc45.png)
![Screenshot (3)](https://user-images.githubusercontent.com/71686718/155660970-8083737d-8518-43d9-91e4-b209938abf0c.png)
![Screenshot (4)](https://user-images.githubusercontent.com/71686718/155660973-fe47f7f6-73fa-4c62-ac88-02a0641e9bf4.png)
![Screenshot (5)](https://user-images.githubusercontent.com/71686718/155660958-beb2b35c-4457-4641-ac08-254609306c9b.png)
![Screenshot (6)](https://user-images.githubusercontent.com/71686718/155661508-fde7cc4e-8ae3-49aa-a315-3a95542152c9.png)

**Versions (please complete the following information):**

 - VS Code **Insiders** version:
          Version: 1.65.0-insider (user setup)
          Commit: 3112460dc48ce7e557ea9feeaae04b912164b48b
          Date: 2022-02-24T05:15:20.989Z
          Electron: 16.0.9
          Chromium: 96.0.4664.174
          Node.js: 16.9.1
          V8: 9.6.180.23-electron.0
          OS: Windows_NT x64 10.0.19042
 - Dart extension version:
           Dart v3.35.20220222 Pre-Release
 - Flutter extension version:
           Flutter v3.35.20220201 Pre-Release 
 - Dart/Flutter SDK version:
 ```
C:\Users\NEW>flutter --version
Flutter 2.10.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 097d3313d8 (6 days ago) • 2022-02-18 19:33:08 -0600
Engine • revision a83ed0e5e3
Tools • Dart 2.16.1 • DevTools 2.9.2

C:\Users\NEW>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.19042.1526], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2020.3)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.

C:\Users\NEW>dart --version
Dart SDK version: 2.16.1 (stable) (Tue Feb 8 12:02:33 2022 +0100) on "windows_x64"
```

I am happy to contribute.

Please let me know if any further information is required.

Thanks for this wonderful plugin !!

**Comment by DanTup** [comment]
> Thanks for this wonderful plugin !!

Thanks, glad you like it!

> I am happy to contribute.

Thanks for the offer, although this turned out to be a little fiddly. There are actually two issues:

1. The icons we ship are missing the latest icons added to Flutter. We get these from https://github.com/flutter/tools_metadata so I have a PR out to update this (https://github.com/flutter/tools_metadata/pull/30)
2. Some icons that have CSS classnames that start with digits do not match the on-disk filenames (for example "3g" vs "threeg") and these need mapping (similar to https://github.com/flutter/flutter/blob/504e66920005937b6ffbc3ccd6b59d594b0e98c4/dev/tools/update_icons.dart#L44-L77). I'm working on handling this now.

**Comment by DanTup** [comment]
3. apparently there is another issue too, because even those that aren't affected by the issues above don't seem to work for me right now..

**Comment by DanTup** [comment]
Nope, that one was just me testing it badly. Looks good now:

![Screenshot 2022-02-28 at 19 05 55](https://user-images.githubusercontent.com/1078012/156043258-21c50dea-029a-4c54-a2c6-585eb3225bf1.png)

Thanks!

**Comment by guidezpl** [comment]
This won't work for a small set of icons which use a different for of rewrites (e.g. try_sms_star). I recommend using https://github.com/flutter/flutter/blob/504e66920005937b6ffbc3ccd6b59d594b0e98c4/dev/tools/update_icons.dart#L500, which handles both cases

**Comment by DanTup** [comment]
Missed this before - I've opened https://github.com/Dart-Code/Dart-Code/issues/3913 about that. I can copy the exceptions from there, although they'll need to be maintained. I wonder if there's a better way that won't need so much maintenance (or if we could at least push some of this logic to https://github.com/flutter/tools_metadata.
