### ISSUE TITLE
Convert Getter to Method doesn't work for extensions

### ISSUE THREAD

**Issue by Merrit** [Dart-Code/Dart-Code#3846]
**Describe the bug**
Using the refactor feature to convert a getter to a method doesn't work if said getter is part of an extension.

**To Reproduce**
1. Add a getter to an extension
2. Right click getter name -> Refactor -> Convert Getter to Method

**Expected behavior**
Getter should be changed to a method.

Example:

```dart
enum Category {
  metal,
  wood,
  glass,
}

extension ExtraEnumFuntionality on Category {
  String get someValue => 'returnValue'; // FAIL
}

class SomeClass {
  String get aValue => 'aReturnValue'; // SUCCESS
}

extension ExtraClassFunctionality on SomeClass {
  String get someValue => 'returnValue'; // FAIL
}
```

**Versions (please complete the following information):**
 - VS Code version: 1.64.2
 - Dart extension version: 3.34.0
 - Dart/Flutter SDK version: Flutter 2.11.0-0.1.pre, Dart 2.17.0

**Comment by DanTup** [comment]
Thanks! I have a fix for review at https://dart-review.googlesource.com/c/sdk/+/234600/. The change is in the Dart SDK so would ship with an upcoming Dart/Flutter SDK rather than a Dart-Code release. I'll keep this issue open until the change has passed review and landed.

Thanks!

**Comment by DanTup** [comment]
This fix has landed in https://github.com/dart-lang/sdk/commit/0359628ca45cb8bae76c4218b31d62793304b8be.

**Comment by Merrit** [comment]
Well that was quick! Thank you :)
