### ISSUE TITLE
Cannot run Flutter repo code samples

### ISSUE THREAD

**Issue by guidezpl** [Dart-Code/Dart-Code#3850]
**Describe the bug**
I'm trying to run code samples located in the Flutter repo, e.g. https://github.com/guidezpl/flutter/blob/6d5fc420b66874458d7a2abc170682be6bc79666/examples/api/lib/material/scaffold/scaffold_messenger_state.show_material_banner.0.dart

**To Reproduce**
1. Wait for analysis to complete
2. Press Run, Debug, or Profile above the `main` function

**Expected behavior**
App launches or get a stack trace.

Instead, the "Launching..." toast is display for a second, and then nothing. No errors or stacks traces in `OUTPUT` or `DEBUG CONSOLE`.

**Versions (please complete the following information):**
 - VS Code version: 1.64.2 (Universal)
 - Dart extension version: v3.34.0
 - Dart/Flutter SDK version: 2.11.0-0.0.pre.482

**Comment by guidezpl** [comment]
When trying to run manually,

```
The current Dart SDK version is 2.16.1.

Because flutter_api_samples requires SDK version >=2.17.0 <3.0.0, version solving failed.
Running "flutter pub get" in api...                                     
pub get failed (1; Because flutter_api_samples requires SDK version >=2.17.0 <3.0.0, version solving
failed.)
```

So probably just a matter of surfacing this error

**Comment by DanTup** [comment]
How did you reproduce this? The SDK constraint in https://github.com/flutter/flutter/blob/master/examples/api/pubspec.yaml is:

```
  sdk: ">=2.14.0-383.0.dev <3.0.0"
  flutter: ">=2.5.0-6.0.pre.30 <3.0.0"
```

But in your message it says 2.17.0. I tried to simulate this by cloning `master` then increasing the `sdk` constraint to `2.18.0`, however running this showed the message in the debug console when I tried running:

<img width="1009" alt="Screenshot 2022-03-01 at 15 47 05" src="https://user-images.githubusercontent.com/1078012/156201007-44cfe401-f206-4dc8-8be9-6ec0d5b1493a.png">

This happens when Flutter decides it needs to run `flutter pub get`, so I wonder if you've somehow got into a situation where Flutter thinks the packages are up-to-date and skips this, but then fails to build?

As well as steps that might help me repro, a log file could be useful:

- Run **Dart: capture Debugging Logs**
- Try to run the project
- Wait until the loading toast/debug bar has disappeared, then click **Cancel** on the logging notification to open the log

**Comment by guidezpl** [comment]
Can't repro anymore 🤷‍♂️. Probably something to do with having two flutter installations, and switching versions a lot. I'll report back if it crops up again

**Comment by reiko-dev** [comment]
I was facing the same "bug" today on a project created on the last 2 weeks. I was trying to upgrade the dart sdk from _>=2.16.2_ to >= _2.17.0_, but i was always getting the same error as yours @guidezpl. It was partially "fixed" after i runned:
1. flutter clean
2. flutter pub upgrade

_After (2) the terminal said:_

> The current Dart SDK version is 2.17.0-266.8.beta.
> Because my_project requires SDK version >=2.17.0 <3.0.0, version solving failed

So i changed the dart version in the pubspec to 
">=2.17.0-266.8.beta <3.0.0"

And now it's all good, but i couldn't use the _2.17.0_ version.

<details>
  <summary>Flutter doctor -v</summary>
 

>  [√] Flutter (Channel beta, 2.13.0-0.4.pre, on Microsoft Windows [versÆo 10.0.19044.1645], locale pt-BR)
>     • Flutter version 2.13.0-0.4.pre at C:\src\flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 25caf1461b (8 days ago), 2022-05-05 14:23:09 -0700
>     • Engine revision c5caf749fe
>     • Dart version 2.17.0 (build 2.17.0-266.8.beta)
>     • DevTools version 2.12.2
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc1)
>     • Android SDK at C:\Users\lukas\AppData\Local\Android\sdk
>     • Platform android-31, build-tools 31.0.0-rc1
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
>     • All Android licenses accepted.
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
> 
> [√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.1)
>     • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
>     • Visual Studio Community 2019 version 16.10.31402.337
>     • Windows 10 SDK version 10.0.19041.0
> 
> [√] Android Studio (version 4.0)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> 
> [√] VS Code (version 1.67.1)
>     • VS Code at C:\Users\lukas\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.40.0
> 
> [√] Connected device (3 available)
>     • Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÆo 10.0.19044.1645]
>     • Chrome (web)      • chrome  • web-javascript • Google Chrome 101.0.4951.67
>     • Edge (web)        • edge    • web-javascript • Microsoft Edge 96.0.1054.43
> 
> [√] HTTP Host Availability
>     • All required HTTP hosts are available
> 
> • No issues found!

</details>
