### ISSUE TITLE
Support different launch.json default configs for test runner when Running/Debugging

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#3854]
There may have to be some caveats around:

- names must be Run/Debug
- paths might be ignored (or required to null, `test` or `integration_test`)

Reverting bac9c3d5fa35a6879fb96acaf2bf25d0ec8eb45b makes this work in some cases, but we don't want to revert everything, we just need to selectively allow the test runner to read non-"default" (`templateFor`) templates.

**Comment by DanTup** [comment]
@evanweible-wf @alanknight-wk I changed my mind on this a little - rather than making `CodeLens` apply directly to the TestRunner, I made `templateFor` a little more customisable. If you include an _explicit_ `noDebug` flag in the launch config, it will be selected by a matching Run/Debug invocation from the test runner.

```js
		{
			"name": "Run Tests",
			"type": "dart",
			"request": "launch",
			"noDebug": true,
			"env": { "FOO": "used for Running tests" },
			"templateFor": ""
		},
		{
			"name": "Debug Tests",
			"type": "dart",
			"request": "launch",
			"noDebug": false,
			"env": { "FOO": "used for Debugging tests" },
			"templateFor": ""
		},
		{
			"name": "Run Tests",
			"type": "dart",
			"request": "launch",
			"env": { "FOO": "used by default if either of the above are removed" },
			"templateFor": ""
		}
```

This change was included in a new pre-release version. If you want to test it out without waiting for the next stable version, you can switch to the pre-release versions of the extensions in VS Code using the buttons shown in the screenshot below.

<img src="https://user-images.githubusercontent.com/1078012/155162164-d81940cb-9576-4468-8c03-a4bc2fd599c9.png" alt="Dart/Flutter pre-release versions" width="570" height="330" />

Please let me know if you hit any issues. Thanks!

**Comment by evanweible-wf** [comment]
Thanks Dan, that worked great for running tests! I'm having trouble with debugging, the tests being run seem to timeout while waiting for them to load:

```
Retrying load of test[/unit/http/utils_test.dart]() in 1s (2 remaining)
Retrying load of test[/unit/http/utils_test.dart]() in 1s (1 remaining)
Retrying load of test[/unit/http/utils_test.dart]() in 1s (0 remaining)
```

but that might be related to the fact that the parent process is `dart run dart_dev test` which itself starts a subprocess to run `build_runner test`, I'm not sure.

**Comment by DanTup** [comment]
@evanweible-wf are you able to share a small repro I can test with? (it's worth filing a new issue since it's not strictly related to this one)

A log file captured with **Dart: Capture Debugging Logs** may also be useful. Thanks!
