### ISSUE TITLE
Testing: The command line is too long.

### ISSUE THREAD

**Issue by lloydrichards** [Dart-Code/Dart-Code#3855]
**Describe the bug**
When trying to run all tests, I get a message in the debug console
```
The command line is too long.
Exited (1)
```

**To Reproduce**
1.  Have over 400 tests
2.  Click the Testing tab in VSCode
3.  Click the Run Tests button
4.  Watch the emulator spin up, then close and see message

**Expected behavior**
Until yesterday it was running as expected, but since my last batch of tests this has started happening.

**Screenshots**
![image](https://user-images.githubusercontent.com/59728961/156544349-e2223b0a-85ef-42cc-aefd-85b09206534c.png)

**Versions (please complete the following information):**
 - VS Code version: 1.64.2
 - Dart extension version: v3.37.20220301
 - Dart/Flutter SDK version: 2.16.1/2.10.2

**Comment by DanTup** [comment]
I've made a new pre-release extension build that includes a fix for this. If you want to try it out without waiting for the next stable version, you can switch to the pre-release versions of the extensions in VS Code using the buttons shown in the screenshot below.

<img src="https://user-images.githubusercontent.com/1078012/155162164-d81940cb-9576-4468-8c03-a4bc2fd599c9.png" alt="Dart/Flutter pre-release versions" width="570" height="330" />

Please let me know if you hit any issues. Thanks!

**Comment by DanTup** [comment]
Great, glad to hear! No problem, thanks for the report (and sorry for the inconvenience!) :-)
