### ISSUE TITLE
Android emulator launched from vscode dart-code does not use GPU acceleration.

### ISSUE THREAD

**Issue by safield** [Dart-Code/Dart-Code#3862]
When I launch my avd using the emulator command...

`emulator -avd pixel_5_android_10`

The emulator launches with GPU acceleration turned on.

When I launch the same avd using the flutter extension, the emulator launches without hardware acceleration.

This could be because the extension is providing --gpu argument to the emulator with incorrect args.

**Comment by DanTup** [comment]
The extension doesn't explicitly pass `--gpu` by default (it just calls `flutter emulator --launch pixel_5_android_10`). I wonder if something else is affecting this. If you launch it using `flutter` as above, do you see the same?

**Comment by DanTup** [comment]
Closing this as a dupe of https://github.com/flutter/flutter/issues/100317, as I don't think there's anything unexpected going on here in the extension.
