### ISSUE TITLE
Android emulator launched using "Flutter: Select Device" launches in two separate Windows on Ubuntu 21.10.

### ISSUE THREAD

**Issue by safield** [Dart-Code/Dart-Code#3865]
I am using Ubuntu 21.10.

When I launch an Android emulator instance from with VSCode using "Flutter: Select Device", the emulator launches in two different windows. One window for the emulator, and one window for the control panel. Both windows are listed in the task switcher as being VSCode windows (vscode has three windows -> the editor, the emulator and the emulator controls).

This problem does not exist if launched from the command line. If I run 'emulator -avd my_avd' from the cli, and single window is created  for the emulator view and the emulator control panel.

Can dart-code extension just launch the same way the CLI does, as a separate (non vscode) window?

**Comment by DanTup** [comment]
Do you see the same behaviour if you run `flutter emulators --launch my_avd`?

The VS Code extension just calls that command, which in-turn just calls `emulator --avd my_avd` (https://github.com/flutter/flutter/blob/b460d0ee34fe3d5c9fe3cd711d269551705d0699/packages/flutter_tools/lib/src/android/android_emulator.dart#L156) so I'm not sure why there's a difference here.

**Comment by Lereena** [comment]
Hi @DanTup. I have the same Ubuntu version and the same problem. If I use `flutter emulators --launch my_avd`, emulator and its control panel are launched as two separate windows too (for example if I move emulator to another workspace, control panel stays on the current workspace).

**Comment by DanTup** [comment]
If it occurs when running `flutter emulators --launch my_avd` too, then it's probably not fixable here (in the VS Code extension) since that's all we're calling here. Out of interest, is that the same whether you use the VS Code built-in terminal or an external terminal?

All of the options for the `emulator` command are documented here, but I can't se any that seem like they would be related to this:

https://developer.android.com/studio/run/emulator-commandline

**Comment by Lereena** [comment]
Yes, the behavior is the same regardless of the terminal type

**Comment by DanTup** [comment]
Thanks for confirming - I wanted to be sure VS Code wasn't setting some env variables that might be affecting it.

In that case, I think it's best to raise this at https://github.com/flutter/flutter/issues/ as it seems to be specific to `flutter` launching it (although I'm not sure what's different - all it's really doing is wrapping `emulator`). Perhaps someone there has ideas about what might be wrong or how to debug.

It would probably be useful to include screenshots of launching both via `flutter emulator` and the Android SDK's `emulator` too. Thanks!

**Comment by safield** [comment]
There are lots of issues with the emulator control bar being treated as a separate window on Ubuntu (Gnome).

When I launch and emulator by any mean, and then switch the emulator to a different workspace, the control bar does not go with it. So this is probably and emulator issue and nothing to do with flutter.

One issue, that is sepcific to flutter vscode tools is that the grouping of the windows in the dock is different when launch through "Flutter: Select Device" in vscode.

If I launch from the command line (using flutter or emulator commands), a single entry will be created in the dock open applications icons (it will have the emulator icon). 

If I launch using "Flutter: Select Device", the vscode icon/entry in the dock gains two new windows (represented as two new orange dots). If I click on the vscode icon in dock to view the thumbnails, there are two separate thumbnails for the emulator main view, and the control bar.

This issue does not arrise when not launching from vscode dart extension.

It quite a trivial difference, and probably just another pecularity of the larger issue, which is that the emulator does not seem to play nice with gnome.

**Comment by DanTup** [comment]
I'm a little confused. The [comment above](https://github.com/Dart-Code/Dart-Code/issues/3865#issuecomment-1068871307) from @Lereena suggests that the same behaviour occurs using `flutter emulators --launch`, but the comment above this one from @safield suggests that it only occurs when launching via the VS Code extension.

Are you both seeing different behaviour? Can you be sure to check both terminals inside VS Code and outside, as they might have different environment variables that perhaps could be affecting the behaviour.

**Comment by safield** [comment]
**Launched From "Flutter: Select Device"**

- emulator displays as a single window in the alt+tab task switcher with a vscode icon displayed over it in task switcher
- in the dock it displays as two separate windows (in total there are three vscode windows in the dock - the main vscode window, the emulator main view, and the emulator control panel). Specifically, the dock displays three separate thumbnails when clicking on the vscode dock icon.
- on the desktop it can be dragged around as if it is a single window.

**Launched From any CLI command**

- emulator displays as a single window in the alt+tab task switcher with the default emulator icon displayed over it in task switcher.
- in the dock it displays as a single window using the default emulator icon
- on the desktop it can be dragged around as if it is a single window.

In all scenario's, if I switch emulator to a different virtual desktop, only the main window moves, and the two windows are broke apart as two in the task switcher and the dock.

**Comment by DanTup** [comment]
@safield just to be clear, are you saying that there's a single window when launching from the CLI in _all_ of these cases?

- running `flutter emulators --launch my_avd` in the built-in VS Code terminal
- running `flutter emulators --launch my_avd` in an external terminal
- running `emulator --avd my_avd` in the built-in VS Code terminal
- running `emulator --avd my_avd` in an external terminal

@Lereena can you confirm if this is different to what you're seeing? Your [comment above](https://github.com/Dart-Code/Dart-Code/issues/3865#issuecomment-1068871307) suggests `flutter emulators --launch` behaves the same as VS Code.

All the Dart-Code extension does is asks the Flutter device daemon to launch the emulator (which takes the same code path as calling `flutter emulators`), so the only thing I can think of that would be different when launching from the extension is the environment variables and parent process from VS Code (although, I'd expect these to mostly be the same when using the built-in terminal too).
