### ISSUE TITLE
"Extract Method" should run checks before asking for a method name

### ISSUE THREAD

**Issue by chrisnorman7** [Dart-Code/Dart-Code#3872]
When choosing the "Extract Method" option from the refacturing menu, you are asked for the name before the plugin checks if the closure can be extracted.

It would seem more ergonomic to perform checks before asking for the name, so that the plugin isn't offering to let you do something that will ultimately fail.

**Comment by DanTup** [comment]
This isn't done yet - it needs an SDK change to match.

**Comment by DanTup** [comment]
SDK work landed in https://github.com/dart-lang/sdk/commit/f4b273e782cb02424b975329e54fb9eba9d360cf.

**Comment by chrisnorman7** [comment]
Great stuff, thank you for all your hard work.

Take care,

Chris Norman

**Comment by DanTup** [comment]
np, thanks for the report!

To get the fix, you'll need the new version of Dart-Code (hopefully shipping today) and also a Dart SDK with the change above (and its version number must be at least 2.17.0). I don't know when the SDKs will next ship, but it'll just automatically start working once you have all the relevant versions.

**Comment by chrisnorman7** [comment]
Great stuff, thank you again.

Take care,

Chris Norman
