### ISSUE TITLE
Code completion for zero-argument functions should position the text cursor after the completion

### ISSUE THREAD

**Issue by jamesderlin** [Dart-Code/Dart-Code#3873]
**To Reproduce**
1. In VS Code, type: `var s = 'HELLO WORLD'.toL`.  Completion suggests the `.toLowerCase()` method.
2. Press Tab.

Result:
VS Code completes `.toLowerCase()` but positions the text cursor between the parentheses.

**Expected behavior**
Since the completed method is known to take zero arguments, positioning the text cursor between the parentheses seems pointless.  I instead expected the text cursor to be *after* `.toLowerCase()`.  After completion, I quickly typed `;` and the `Enter` key before realizing what happened, and undoing the damage took additional effort.

I'm not sure if this is something that the Dart extension can do something about or if it's how code completion works in VS Code in general.

**Versions (please complete the following information):**
 - VS Code version: 1.65.1 on Linux x64
 - Dart extension version: 3.36.0
 - Dart/Flutter SDK version: 2.17.0

**Comment by DanTup** [comment]
Yep, this comes from the LSP server. I've got a fix at https://dart-review.googlesource.com/c/sdk/+/238088/.

Since it's in the LSP Server, it'll show up in an SDK update rather than a VS Code extension update.

I'll close this once the change lands. Thanks!

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/13593b9ab40592b249899043b926ef744b23e79d.
