### ISSUE TITLE
Format on save not being respected

### ISSUE THREAD

**Issue by guidezpl** [Dart-Code/Dart-Code#3876]
**Describe the bug**
I have format on save set to false for both the user and workspace. Yet, today I saved a file and it reformatted the whole thing. I tried a few things (quitting, re-opening, re-saving, toggling the setting on-off) and it still gets formatted.

Not sure how to reproduce, this just started occurring today.

**Versions (please complete the following information):**
 - VS Code version: 1.65.2 
 - Dart extension version: v3.36.0
 - Dart/Flutter SDK version: Flutter version 2.13.0-0.0.pre.5, Dart version 2.17.0

**Comment by guidezpl** [comment]
Ah, the [dart] section was the culprit, thanks!

**Comment by DanTup** [comment]
Great! There's an open issue in VS Code about making language-specific settings more obvious, it is a bit confusing right now.
