### ISSUE TITLE
Annotate unit/widget tests for running in groups

### ISSUE THREAD

**Issue by lloydrichards** [Dart-Code/Dart-Code#3878]
**Is your feature request related to a problem? Please describe.**
Currently, I'm running TDD (TestDrivenDevelopment) on our companies App and after several months of development and rapidly approaching 1000 tests.   With the workflow now, and CI/CD I have these tests continuously being run to check the coverage, validate merge requests and generally check on project status.  As the tests have grown this has gone from a few seconds to now several minutes and in my CI this can be even longer with slow linux machines in GitLab.
```
PS C:\Users\lr\Documents\GitHub\hive-manager> flutter test --coverage
08:06 +793: All tests passed!
```
![image](https://user-images.githubusercontent.com/59728961/159022829-87b19cb7-9567-4ea5-a9c7-a50521cb31ac.png)

**Describe the solution you'd like**
What I would love would be a way to group these tests when running `flutter test` so that I can scope how tests are run during my CI as well as during TDD.  For example if I have the core set of tests, such as navigation, auth flow, adding content then I would like to exclude these from my TDD coverage and status testing and leave them for specific CI tasks.  And then for features and bugs that I'm working on, be able to tag or scope those to be use and update coverage accordingly.

For example, in the Test you could mark it with a tag:
```
@TestGroup("core")  <-- using annotation?
void main(){
...
}

@TestGroup("develop")  <-- using annotation?
void main(){
...
}
```
and then when calling `flutter test --coverage --group=develop` it would only call those with that annotation.

**Describe alternatives you've considered**
An alternative would be to have some kind of directory system where I would specify which tests to run based on where they are.  so something like:

`flutter test --coverage dir=test/core`

so at least in my CI I could break these up a bit to reduce on my CI minutes.

**Additional context**
Im absolutely loving the DX of building with Flutter so take these suggestions as just things that would make my overall quality better (and development costs lower) so that I can continue to push flutter and TDD onto other developers 😄

**Comment by DanTup** [comment]
If I understand correctly, I think this is a request for Flutter, not for the VS Code extension. Anything implemented here will not affect running `flutter test` from the command line - the `flutter` tool is part of the Flutter SDK (https://github.com/flutter/flutter/).

That said, I think what you're asking for already exists in the form of tags - see https://github.com/flutter/flutter/pull/55152.

You can run `flutter test --tags foo` and annotate your test with `@Tags(['foo'])`. See https://pub.dev/packages/test#tagging-tests for more info on tags.

**Comment by lloydrichards** [comment]
Oh! It certainly helps to know the terminology when looking for answers 😅
thanks so much, this is exactly what I needed.
