### ISSUE TITLE
Auto generate switch statement based on enum

### ISSUE THREAD

**Issue by safield** [Dart-Code/Dart-Code#3880]
I think it would be really cool if there was a refactoring command that would auto-fill a switch statement, when the switch statement is based on a enum.

So I have the following code...

```
enum MyEnum {
  val1,
  val2,
  val3,
}
```
Then I could type the following...
```
var myEnum = MyEnum.values.first; // get some assigned enum instance
// type and empty switch
switch(myEnum) {
}
```
Then hit a refactoring command 'complete enum switch', and you would end up with...
```
var myEnum = MyEnum.values.first; // get some assigned enum instance
// type and empty switch
switch(myEnum) {
  case MyEnum.val1:
    break;
  case MyEnum.val2:
    break;
  case MyEnum.val3:
    break;
}
```

**Comment by DanTup** [comment]
When I enter your code, I see an existing assist to add all missing causes - do you not see this?

![Mar-24-2022 15-15-53](https://user-images.githubusercontent.com/1078012/159949045-808dcf4f-861d-4805-ba83-98c7f92e1283.gif)

**Comment by safield** [comment]
It does work for me. I was just looking in the wrong place!
