### ISSUE TITLE
Support dart format -i (--indent) as an extension setting

### ISSUE THREAD

**Issue by weenzeel** [Dart-Code/Dart-Code#3883]
Running dart format -h -v tells us that the Dart formatter supports an option to control the indentation of a formatted file.

Could the indentation parameter be exposed as an extension setting? We can allready control the formatter line length.

Thanks!

**Comment by DanTup** [comment]
@weenzeel are you trying to change indentation from spaces to tabs? If so, I think you may have misunderstood that flag - it just lets you add additional indent levels to the code, see the test here:

https://github.com/dart-lang/dart_style/blob/d7b73536a8079331c888b7da539b80e6825270ea/test/command_line_test.dart#L262

If that's what you're expecting, can you describe how you'd expect to use this in the editor? It seems to me like it's really only useful when formatting a block of code that would be embedded somewhere that already has some levels of indenting and you need the formatted code to reflect that.

**Comment by weenzeel** [comment]
My understanding would be as you describe it. Add initial spaces to each row.

Except one or two things (that drive me crazy) I like that the Dart formatter is opiniated and don't have a lot of configuration options. But since line length and indentation are the two leviers that the formatter allows, it would be nice to be able to pull on them straight from within visual studio code. :)

It's of course a balance act. The purpose of a opinionated formatter is to have a global consistent code-base. Adding formatting options takes away from that goal. I personally like wide lines and wide indentation. It may not be for everyone.

On the other hand, i saw comments in this repo that people are turning of the Dart formatter because of the 2 vs 4 spaces preference. Allowing variation in indentation may be a small price to pay to keep as many develoeprs on the formatter as possible!

**Comment by DanTup** [comment]
> My understanding would be as you describe it. Add initial spaces to each row.

> On the other hand, i saw comments in this repo that people are turning of the Dart formatter because of the 2 vs 4 spaces preference. Allowing variation in indentation may be a small price to pay to keep as many develoeprs on the formatter as possible!

I don't think these things are the same. The functionality adds fixed indenting to every line. This is not the same as being able to use 4 spaces instead of 2. If you use `-i 2` all nested code would still only indented by two spaces, but every line would have an _additional_ 2 spaces at the start.

Example:

`dart format foo.dart`

```dart
void main() {
  if (true) {
    if (true) {
      print('');
    }
  }
}
```

`dart format foo.dart -i 2`

```dart
  void main() {
    if (true) {
      if (true) {
        print('');
      }
    }
  }
```

The code is still indented using two spaces, but now you have two spaces at the start of every line. This doesn't seem like it would be useful to me - if that's what you're hoping for, can you describe your use case in more detail? Thanks!

**Comment by weenzeel** [comment]
Ah ok! Sorry, I missunderstod the functionality then.
I don't have a use-case for added indentation of that type.

Closing!

**Comment by DanTup** [comment]
Got it, thanks! 

FWIW, I made the same mistake when I first saw `-i` and thought it would address some requests here 🙃
