### ISSUE TITLE
Order local vars in debug window alphabetically

### ISSUE THREAD

**Issue by nickmeinhold** [Dart-Code/Dart-Code#3884]
**Is your feature request related to a problem? Please describe.**

I am porting a JS lib to Dart and noticed the local vars are ordered alphabetically in the Node debug window 

<img width="272" alt="Screen Shot 2022-03-23 at 15 40 07" src="https://user-images.githubusercontent.com/1059276/159625506-61d7223c-c0df-4f0d-9a8e-9eff3895845e.png">

but are not ordered in the Dart debug window

<img width="291" alt="Screen Shot 2022-03-23 at 15 39 58" src="https://user-images.githubusercontent.com/1059276/159625548-07c42c59-0368-48a2-8006-228fdab8dee5.png">

**Describe the solution you'd like**

Have the Dart debug window list the local vars in alphabetical order.

Thanks!

**Comment by DanTup** [comment]
Thanks, fixed! I'd apparently already done this in the new SDK DAPs, but since it'll take a little while to fully switch over, I've fixed in the current.legacy DAP too.

**Comment by nickmeinhold** [comment]
Amazing, thank you! 🙂
