### ISSUE TITLE
Null cast functions are not given the correct 'function' semantic token.

### ISSUE THREAD

**Issue by safield** [Dart-Code/Dart-Code#3888]
If you use the null cast '!' operator on a nullable function, that function call is not colored with the proper syntax coloring for a function.

```
class Test {
  Function? function;
  void foo() {
    function!();
  }
}
```

**Comment by DanTup** [comment]
@safield can you provide a screenshot of what you're seeing, and confirm what VS Code Theme you're using and what version of Dart/Flutter? The colours seem to appear ok for me with the Dark+ theme on latest SDKs:

![Screenshot 2022-03-28 at 14 28 16](https://user-images.githubusercontent.com/1078012/160408224-3d427c18-6b7f-4c57-9b8e-c84982d6c5e5.png)

**Comment by safield** [comment]
@DanTup Can you confirm the semantic token are the same? I think mine were different tokens. It might be that that theme conicidently has the same color assigned to different tokens.

**Comment by DanTup** [comment]
Yep, they're both the same for me (instance properties).

![Screenshot 2022-03-28 at 14 33 13](https://user-images.githubusercontent.com/1078012/160409129-1e3b9bac-631e-4385-bb5f-974306705050.png)
![Screenshot 2022-03-28 at 14 33 18](https://user-images.githubusercontent.com/1078012/160409131-c8af007d-fc1b-4b15-8922-c8045a17df3b.png)

**Comment by DanTup** [comment]
FWIW I see differences if I _disable_ semantic tokens, but that's because the Textmate grammar is somewhat restricted (which is why we have semantic tokens).

**Comment by DanTup** [comment]
Yeah, I guess that theme doesn't map semantic tokens (or at least these ones).

I've tweaked the textmate grammar so `1` and `?` can appear optionally in front of `(` and still be treated as a function identifier.

![Screenshot 2022-03-28 at 18 48 42](https://user-images.githubusercontent.com/1078012/160457160-134b3e0f-e9ba-4296-aa9c-1dd4384af353.png)
![Screenshot 2022-03-28 at 18 48 57](https://user-images.githubusercontent.com/1078012/160457168-4089e59e-7365-4ab3-a2b9-6c13bc051a08.png)
