### ISSUE TITLE
Typed objects are not recognised and shown as dynamic

### ISSUE THREAD

**Issue by CassiusPacheco** [Dart-Code/Dart-Code#3890]
**Describe the bug**
Sometimes when pulling other people's code from origin VSCode won't recognise new object types and starts to set everything as dynamic, which then causes the lint to raise [avoid_dynamic_calls](https://dart-lang.github.io/linter/lints/avoid_dynamic_calls.html) as well as [override_on_non_overriding_member](https://dart.dev/tools/diagnostic-messages#override_on_non_overriding_member) when using interfaces and they are not being recognised.

When running the code it actually works, the app is launched, no problems there, but the syntax highlighter complains that the types won't match.

Weirdly enough, if I rename the methods and instances it recognises the types again. But just by deleting and recreating the same name won't work.

I've tried VScode "Clear Editor History", deleting `flutter/bin/cache`, disabling and re-enabling the extensions, quitting VScode multiple times, restarting my mac, deleting pubspec.lockfile, flutter clean, going to every single class and re-saving the file to give VSCode a chance to reload it.

None of the above work consistently. I cant remember what I did to fix it last time. Not sure if it went away eventually or what. I'm open to suggestions!

This has happened to other teammates as well in previous versions of flutter and dart too.

**To Reproduce**
Unknown. It happens occasionally. 

**Screenshots**
![Screen Shot 2022-03-28 at 11 24 56 am](https://user-images.githubusercontent.com/662062/160308056-3534af94-443f-4743-97ac-3bfe1f34aa83.png)

**Versions (please complete the following information):**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.2 21D49 darwin-arm, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.65.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

macOS Monterey 12.2, Macbook Pro M1 Pro 2021. (It has happened to me in an older Intel Mac as well)

**Comment by DanTup** [comment]
@CassiusPacheco if nothing else works, I suspect closing VS Code and deleting the `~/.dartServer` folder will help (although it doesn't help understand down what's going on). If you delete this folder, your next analysis may be slower than usual.

@bwilkerson @scheglov have you seen any other reports like this?

The change at https://github.com/dart-lang/sdk/commit/650b9627b7a7c05d9d2a489a23b2eae98c9aef95 fixes an issue where watcher events might be dropped during context rebuilds (which could easily occur during branch changes), although if that was the only issue I would expect restarting VS Code to fix it.

Is there anything that might help track it down besides having the instrumentation log file enabled all the time (which could get quite large if the issue isn't reliably reproducible).

**Comment by DanTup** [comment]
Out of interest (since I'm not very familiar with them), if I was to modify some files while my IDE was closed and then open them, what triggers the summaries to be rebuilt? Does it use a hash of the file or something, or just a timestamp? (I ask, because if it was a hash, I would have expected restarting the editor to fix issues caused by missed watch events - for example).

**Comment by CassiusPacheco** [comment]
> @CassiusPacheco if nothing else works, I suspect closing VS Code and deleting the `~/.dartServer` folder will help (although it doesn't help understand down what's going on). If you delete this folder, your next analysis may be slower than usual.

This did it for me. At least now I know how to work around it, thank you!

**Comment by CassiusPacheco** [comment]
I'm starting to notice this issue coming up more often as I pull code from git remote and switch git branches. For context, it's a monorepo with four different apps and around six packages in the root folder. One of the developers uses Android Studio, but we don't commit any build folder or anything weird, the remainder use VSCode.

I obviously can't share the source code, but let me know if there's anything else I can do to help debug this further. Thanks!

**Comment by DanTup** [comment]
@scheglov Would it be useful if this happened, if the `.dartServer` folder was renamed, the project re-analyzed (fixing the issue), and then (without any modifications to the source), the old/new folders compared (for files that differ, ignoring all those that weren't yet created in the new folder)?

**Comment by scheglov** [comment]
Most probably not, I don't know what to do with this data. What would really help is a repro case, even if it happens only with some probability.

**Comment by DanTup** [comment]
@CassiusPacheco how often are you seeing it? Is it possible you could detail the exact project layout (including which folder you open, and where any `pubspec.yaml`/`analysis_options.yaml` files are)? How are you changing git branches (through VS Code, cli?) and do you know if the switches that trigger it tend to modify none/some/all of the `pubspec.yaml` files?
