### ISSUE TITLE
Programs launched via launch.json not receiving environment variables

### ISSUE THREAD

**Issue by btrautmann** [Dart-Code/Dart-Code#3891]
**Describe the bug**
I began noticing on `Dart Code 3.36.0` (though this may also be happening on previous versions) that programs launched via `launch.json` with `args` supplied from environment variables don't seem to actually receive them. However, building the same program and passing in the variables via `dart-define` on the CLI works fine.

**To Reproduce**
1. Create Flutter app and define it's launch behavior in `launch.json` as follows (assuming you've defined and environment variable `MY_VARIABLE` with some value and restarted VSCode):
```json
{
    "name": "example (dev)",
    "program": "lib/main.dart",
    "request": "launch",
    "flutterMode": "debug",
    "type": "dart",
    "args": [
        "--dart-define",
        "MY_VARIABLE=${env:$MY_VARIABLE}",
    ]
}
```
2. Run program via `launch.json`
3. Note that calls to `String.fromEnvironment('MY_VARIABLE')` return an empty `String`

#### I've put together a reproduction example [here](https://github.com/btrautmann/vscode-env-repro/tree/main/env_repro) which assumes you've set an environment variable `MY_VARIABLE`. In my case, I used the string `testing` and launching via `launch.json` produced the following:

<img src="https://user-images.githubusercontent.com/8343465/160409111-b4c34ce5-2824-4ee0-8cf8-6147d0978fac.png" width="300"/>

But launching via CLI with the following: `flutter run --dart-define MY_VARIABLE=$MY_VARIABLE` produced the expected content:

<img src="https://user-images.githubusercontent.com/8343465/160408683-5408dbc9-f229-4415-a53c-adc03658f103.png" width="300"/>

**Expected behavior**
`String.fromEnvironment` should produce the non-empty String.

**Screenshots**
See above ☝️ 

**Versions (please complete the following information):**
 - VS Code version:
![Screen Shot 2022-03-28 at 09 35 12](https://user-images.githubusercontent.com/8343465/160409459-4f4034a6-a385-4cbf-b8c1-813a29031014.png)

 - Dart extension version:
![Screen Shot 2022-03-28 at 09 35 32](https://user-images.githubusercontent.com/8343465/160409525-8807451b-1d39-4ec3-8cfe-8869455a9bc3.png)

 - Dart/Flutter SDK version:
 ```console
Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7e9793dee1 (4 weeks ago) • 2022-03-02 11:23:12 -0600
Engine • revision bd539267b4
Tools • Dart 2.16.1 • DevTools 2.9.2
```

**Comment by DanTup** [comment]
```
    "args": [
        "--dart-define",
        "MY_VARIABLE=${env:$MY_VARIABLE}",
    ]
```

The issue seems to be the `$` in front of `MY_VARIABLE`. It should instead be:

```
    "args": [
        "--dart-define",
        "MY_VARIABLE=${env:MY_VARIABLE}",
    ]
```

See https://code.visualstudio.com/docs/editor/variables-reference#_environment-variables.

Please let me know if this still doesn't work for you.

**Comment by btrautmann** [comment]
Ah shoot, you're totally right. That fixed the issue, thank you!!
