### ISSUE TITLE
Is there an option to not pause on uncaught exceptions?

### ISSUE THREAD

**Issue by joshpetit** [Dart-Code/Dart-Code#3897]
Hey! Dart-code is awesome, and I've been using it for a while. One problem I have though is that it always pauses on uncaught exceptions. I'm using dart-code with nvim-dap, and I was wondering if there's a configuration option to not pause on uncaught exceptions. 

Looking at the full list of configurations [here](https://dartcode.org/docs/settings/) it doesn't list an option, but in #2063 there's a button that can toggle pausing on uncaught exceptions so help finding this as a configuration would be appreciated! Thanks!

**Comment by DanTup** [comment]
You should be able to control this at the bottom of the Debug panel. You might not see this panel until after you start a debug session though, as VS Code needs to talk to the debugger to find out what the options are.

<img width="466" alt="Screenshot 2022-03-31 at 15 50 41" src="https://user-images.githubusercontent.com/1078012/161084550-b3fcb9b4-a3c3-42ac-96d0-6c6c31117361.png">

Let me know if this doesn't work for you!

**Comment by joshpetit** [comment]
I'm not using vscode 😅. I'm using [nvim-dap](https://github.com/mfussenegger/nvim-dap).

Is there a configuration for it in the launch.json?

**Comment by DanTup** [comment]
Sorry, I totally scanned over that in your message 😄

These options are sent from the debug adapter to the client in its capabilities (the `exceptionBreakpointFilters` field). Your debug adapter client (nvim-dap) will need to process them and give you some option to set them (it should then call `setExceptionBreakpoints` with your selection).

 Unfortunately I'm not a user of that plugin so I can't provide any guidance on setting this up (if it's supported), but if you file an issue with them about this, feel free to CC me if my input might be useful. Thanks!

**Comment by DanTup** [comment]
If you can't figure it out, it's probably worth posting a question in their issue tracker. If it's not something already supported, it seems like something worth adding support for.

I don't think there's anything to do here, so closing this - but feel free to ping me (here, or in other issues) if I can help.

By the way, if you're using the debug adapters from Dart-Code, you might want to check out the new SDK-shipped DAPs:

https://github.com/dart-lang/sdk/blob/main/pkg/dds/tool/dap/README.md
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/debug_adapters/README.md

They're not entirely complete in the current stable versions of Dart/Flutter, but the next stable releases they should be reasonable complete. Using this will avoid having to check out/build the Dart-Code sources, and will be better supported going forwards (Dart-Code will migrate to them soon).

**Comment by joshpetit** [comment]
This is how to stop pausing on uncaught exceptions in nvim dap: https://github.com/mfussenegger/nvim-dap/blob/9915c3a94e04b872ce6310f28fb33d0b5f41a292/doc/dap.txt#L705

Just clear the minibuffer when prompted.

**Comment by lucaSartore** [comment]
I admit this is a bit of shameless self promotion, however I made a plugin that allow to use that feature in nvim more easily, you can find it here: [https://github.com/lucaSartore/nvim-dap-exception-breakpoints](https://github.com/lucaSartore/nvim-dap-exception-breakpoints)
