### ISSUE TITLE
debugger does not seem to stop/break at the breakpoint location but at some arbitrary location

### ISSUE THREAD

**Issue by vaibhav891** [Dart-Code/Dart-Code#3898]
## Steps to Reproduce

- create a basic flutter app
- place a breakpoint anywhere in the _MyHomePageState's build method.
- run the application in chrome in debug mode
- notice the IDE (both android studio & VSCode) debugger stops at some other location

## additional notes
The debugger works fine when run on Android.

<img width="1440" alt="Screenshot 2022-03-31 at 11 17 53 PM" src="https://user-images.githubusercontent.com/62712068/161118215-a8038a26-46cf-49de-a2ca-2a96ff8379b7.png">

## Version info

[✓] Flutter (Channel stable, 2.8.1, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 2.8.1 at /Users/vaibhavsultania/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 months ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/vaibhavsultania/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.65.2)
    • VS Code at /Users/vaibhavsultania/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 31) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 100.0.4896.60

• No issues found!

**Comment by AnasDORBANI** [comment]
The most common cause of the debugger pausing at a place where you didn't set a breakpoint is the throwing of an exception.

**Comment by vaibhav891** [comment]
I do not think that is the case here. I am able to reproduce the issue in the flutter basic counter application. Also, I do not see any exceptions in the variables or call stack or any other place.

**Comment by AnasDORBANI** [comment]
Some exceptions crash the program, which is where you get the red highlight in the debugger. Some exceptions don't crash the program. In those cases the debugger highlights the exception breakpoint in green.

If the debugger pauses your program with a green highlight, click the Continue Execution button (it's the third button from the left in the group of debugging buttons).

**Comment by vaibhav891** [comment]
The same application breaks correctly at the breakpoint when running and debugging as an android application using emulator.
Also the debugger does not pause with green highlight. It pauses with orange highlight as shared in the image above.

**Comment by DanTup** [comment]
Thanks for the report - this definitely seems like a bug. I believe the issue may be in `dwds` (the proxy that emulates the Dart VM for Chrome). I've filed an issue at https://github.com/dart-lang/webdev/issues/1553.

If it turns out to be the wrong place, I'll re-open this (or re-raise somewhere appropriate). Thanks!

**Comment by prabinlamsal19** [comment]
I switched to NVIM because I couldn't make the VSCode debugger work.

**Comment by DanTup** [comment]
@prabinlamsal19 if you're having trouble, please file issues with the details so we can take a look.

FWIW, if you're debugging in nvim, there's a good chance you're using the same debug adapters that Dart-Code is using that come from the Dart/Flutter SDKs :-)
