### ISSUE TITLE
Lost connection to desktop app on Windows

### ISSUE THREAD

**Issue by talamaska** [Dart-Code/Dart-Code#3901]
**Describe the bug**
The debug process is terminated after certain time from couple of second to couple of minutes. The App is running, but the VS code says - Lost connection to device and the debugger is stopped. This doesn't appear in Android Studio.

**To Reproduce**
1. Using VS Code, to run a Flutter Windows app.

**Expected behavior**
The debug process to stay connected until I close the app or click stop button.

**Versions (please complete the following information):**
 - VS Code version: 1.66.0, but valid from at least 6 months
 - Dart extension version: Flutter v3.36.0, Dart 3.36.0
 - Dart/Flutter SDK version: This happens from 2.5.0

**Comment by DanTup** [comment]
I don't seem to be able to reproduce this. After how long does it happen for you? (I waited over 15 minutes).

Can you post the full output of `flutter doctor -v`?

I found a similar report at https://github.com/flutter/flutter/issues/101015 that mentions upgrading their Windows SDK resolved the issue (see https://github.com/flutter/flutter/issues/101015#issuecomment-1083166430) which may be worth trying.

**Comment by talamaska** [comment]
The windows SDK version was it, I had 3 different version installed and left only the one that is mentioned in the issue.

**Comment by DanTup** [comment]
Ah, good to hear it's solved - thanks for confirming!
