### ISSUE TITLE
Name source files using `lowercase_with_underscores` for "app_assets.dart"

### ISSUE THREAD

**Issue by riyoua** [Dart-Code/Dart-Code#3909]
Issue Type: <b>Bug</b>

the file which dart linting is pointing as if it was named using a wrong way is : "app_assets.dart"  , i can't get ride of this error which is showing appearntly for no reason . 

Extension version: 3.38.0
VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.79GB free)|
|Process Argv|--crash-reporter-id 52f79ef7-a048-43a9-8970-2ca714277465|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30466690
pynewfile477:30463512

```

</details>

**Comment by riyoua** [comment]
I was wrong about the file which dart linting was pointing at , the error was shown on the editor above next to my import for "app_assets.dart" , but when I click on the error / hint message from the problem panel , it highlight another file which is : 
"on_boardingPage.dart" , I changed the name to "on_boarding_page.dart" , and every thing works just fine .

**Comment by DanTup** [comment]
Glad you sorted it. FWIW, there are some quirks with the handling of this lint because VS Code persists the original file case for the API even if you rename it - there's some info about that in #3236 along with a setting you can enable if you hit it (although there's a performance cost to that setting):

https://github.com/Dart-Code/Dart-Code/issues/3236#issuecomment-913644182
