### ISSUE TITLE
v3.38.1 breaks debugging in VSCode

### ISSUE THREAD

**Issue by longtimedeveloper** [Dart-Code/Dart-Code#3911]
**Describe the bug**
After  VS CODE updated the Flutter and Dart extension to version v3.38.1, debugging is broken.  

I can set breakpoints.  When the debugger hits a breakpoint the debug window shows a message that it stopped at a breakpoint, but the line of code where the breakpoint is is not highlighted like it used to be.  At the breakpoint, I can no longer watch any variables.

I have tried rolling back the Dart Extension, and Flutter Extension to v3.36.0 but I'm still getting this very strange behavior at debug time.   Previously, when VS Code hit a breakpoint, it automatically navigated to the file and line of code when the breakpoint is.  It is no longer doing this. In fact, when the editor says it is at a breakpoint, I can't use the Watch window to view the value of any variables.  It's like the debugger is stopped in another location.

I'm an American in Ukraine and Moldova working on anti-trafficking software.  Everything was fine with my system, then today, I'm seeing these issues.  I checked all extensions, and none of them have been updated for two or more months, except the Dart and Flutter extensions.  Anything you can do to help me is greatly appreciated.

Yesterday, I updated Visual Studio 2022 to Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.1.3  Not sure if this can cause problems with VS Code.

I've closed all apps, deleted user and windows temp files, rebooted, and still the same behavior.

**To Reproduce**
Open VS Code, and insure the v3.38.1 extension is installed.
Open a Flutter project.
Set a breakpoint.
Start debugging.

**Expected behavior**
When the debugger hits the breakpoint, the line of code should be highlighted.

**Screenshots**
![image](https://user-images.githubusercontent.com/79998776/161921049-9cbdcff1-c4b4-4cdf-bd22-1ea77c63e4ad.png)

In this screenshot, you can see the value of licensePlate "HELLOFLUTTER" printed in the console, but the watch window does not show the value.
![image](https://user-images.githubusercontent.com/79998776/161935000-74d89271-4dd4-44ed-98c4-32d17be3aaa4.png)

**Versions (please complete the following information):**
 - VS Code version:   1.66.0
 - Dart extension version:  v3.38.1
 - Dart/Flutter SDK version:   Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.19044.1586], locale en-US)

Version: 1.66.0 (user setup)
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:14.623Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19044

C:\Users\church>flutter doctor -v
[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.19044.1586], locale en-US)
    • Flutter version 2.10.4 at C:\Users\church\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (12 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\church\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32328.378
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.66.0)
    • VS Code at C:\Users\church\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (4 available)
    • Pixel (mobile)    • FA72A0300998 • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows      • windows-x64    • Microsoft Windows [Version 10.0.19044.1586]
    • Chrome (web)      • chrome       • web-javascript • Google Chrome 100.0.4896.75
    • Edge (web)        • edge         • web-javascript • Microsoft Edge 100.0.1185.29

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by DanTup** [comment]
If this is only happening for the Chrome device, I think it's likely https://github.com/dart-lang/webdev/issues/1557 which has started occurring when Chrome updated to v100. There was an API change that affects dwds (which is the Dart proxy used to emulate the Dart VM for JavaScript/Chrome).

If you're able to downgrade Chrome to v99, that might resolve the issue while a fix is being worked on.

If you still see issues on Chrome 99, please let me know and I'll re-open this and do some more digging. Thanks!

**Comment by longtimedeveloper** [comment]
@DanTup trying to downgrade Chrome now.

**Comment by longtimedeveloper** [comment]
@DanTup it was a train wreck.  Unable to downgrade chrome.  Google Chrome really needs a much better experience.

**Comment by longtimedeveloper** [comment]
@DanTup  why is this issue and the other one you pointed to above closed?  I don't understand why these would be closed as this issue effects all Flutter web developers in the world.

**Comment by DanTup** [comment]
@longtimedeveloper https://github.com/dart-lang/webdev/issues/1557 was closed yesterday by a fix being merged: (https://github.com/dart-lang/webdev/pull/1559).

I'm afraid I don't know what release the fix will be in (it's not something I'm involved in), although the issue is marked P1 and since the fix landed, [v13.0 of dwds was published to Pub](https://pub.dev/packages/dwds) which includes the fix, so it does look like it's being worked on.

**Comment by DanTup** [comment]
This issue in Dart-Code was closed because there's no work to do here in the VS Code extension (the fix will arrive via a Flutter SDK update), and there was another issue tracking the issue. I usually try to avoid keeping duplicate issues open, or those that are to be fixed in other projects, to keep management of the issues here easier.

**Comment by longtimedeveloper** [comment]
@DanTup  thank you for taking the time to explain the process and where we are.  I can imagine the Flutter and Dart engineers are working at lightning speed to sort this out.  

So when I get the Flutter notification that there is an upgrade, I assume that is how I'll know it has been corrected.

**Comment by DanTup** [comment]
I can't say for certain that the fix will be in any specific Flutter update (it's not something I'm involved in), although given the severity there's probably a good chance it'll be in the next one. If you do get a Flutter upgrade and it doesn't seem to solve the issue, feel free to ping back here and I can check whether it was expected to have been included.

**Comment by longtimedeveloper** [comment]
@DanTup thank you very much for your outstanding assistance and patience.  Much appreciated, have a blessed day, Karl

**Comment by longtimedeveloper** [comment]
@DanTup I just got a VS Code Dart update to v3.38.2.  **However, debugging is still broken.**  Not sure if I was supposed to start working now or if we are waiting for a new release of Flutter.

**Comment by DanTup** [comment]
@longtimedeveloper Unfortunately not, the fix needs to come in a Flutter update, not an update to the VS Code extension.

The issue to track is https://github.com/dart-lang/webdev/issues/1557. It was previously closed and I thought it had been fixed, however it's since been re-opened, so I think there's still work to do.

**Comment by longtimedeveloper** [comment]
@DanTup thank you for explaining.  I'll be sure to follow the above issue.  Blessings, Karl

**Comment by DanTup** [comment]
My understanding is that this issue has been fixed for the Chrome device in Flutter 2.10.5 (see https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel#2105-april-18-2022), though there's still some outstanding work to fix it for the Web Server device.
