### ISSUE TITLE
bug: strange behavior on test in console

### ISSUE THREAD

**Issue by yeikel16** [Dart-Code/Dart-Code#3915]
**Describe the bug**
When running the tests through the RUN access found in the code, there is no problem, it passes, and it runs normally. The strange behavior is that when you run this same test on the console through the command `flutter test -j 1 --plain-name='Flutter'` it fails. Issue [#353](https://github.com/VeryGoodOpenSource/very_good_cli/issues/353) in [very_good_cli](https://github.com/VeryGoodOpenSource/very_good_cli/)

Steps To Reproduce

1- Clone the repo [very_good_cli](https://github.com/VeryGoodOpenSource/very_good_cli/) to a Windows 10 PC.
2- Run flutter pub get in the proyect.
3- Run `flutter test -j 1 --plain-name='Flutter'`.
4- See tests fail.

**Expected Behavior**
It should pass all the tests, since they run on both Linux and MacOS, they only fail on Windows.

**Additional Context**
Edition Windows 10 Pro
Version 21H1
OS Compilation 19043.1586

**Screenshots**
![Captura](https://user-images.githubusercontent.com/26438532/162124604-0f5bef47-dc23-4989-bd17-25827536914d.PNG)

**Versions:**
 - VS Code version: 1.66.0
 - Dart extension version: v3.36.0
 - Dart/Flutter SDK version: Dart 2.16.1/Flutter 2.10.3

**Comment by DanTup** [comment]
This either seems like a bug in the tests, or that they don't support being run with `flutter test`. The difference when running from VS Code is that this project is not a Flutter project so we run the tests with `dart`. If you run the test like this, then it passes from the terminal:

```
dart run --no-serve-devtools test:test --name "^Flutter .test throws when process fails" 
```

I don't know why the test doesn't work under `flutter test`, but I can see it's spawning its own `flutter` processes as part of the test, so it's something that would need to be debugged by the project authors.

Hope this helps!
