### ISSUE TITLE
Android emulator running under different user is shown as an available device.

### ISSUE THREAD

**Issue by safield** [Dart-Code/Dart-Code#3923]
note: I swear I created this issue before but I cannot find it :S

Observed on Ubuntu 21.10 with SDK installed using official snap package.

Start an an emulator running a specific AVD, under one user session. Switch user sessions, and with in Vscode command pallete, run dart-code command 'Select Device'. Observe that the device instance running under the other user is shown as an available device to use.

I would expect it only to show emulator who UI is running in the current session.

**Comment by DanTup** [comment]
I don't have easy access to Ubuntu to test this, but I suspect if you run `flutter devices`, it also shows up there? VS Code gets the devices via Flutter, so I think this would need to be raised in Flutter (https://github.com/flutter/flutter/).

If you do, please post a link back here for anyone else that finds this issue looking for the answer.

Thanks!

**Comment by safield** [comment]
https://github.com/flutter/flutter/issues/101792
