### ISSUE TITLE
Add a setting to run "pub get" with "--offline"

### ISSUE THREAD

**Issue by jellynoone** [Dart-Code/Dart-Code#3924]
**Is your feature request related to a problem? Please describe.**
Personally, I more or less work offline, and with a constant set of external dependencies or path defined. Currently, if I save the pubspec.yaml file it runs `dart pub get` which fails because there is no network access, however all of my dependencies are already on disk and manually running `dart pub get --offline` works just fine.

**Describe the solution you'd like**
The plugin could:
1. Offer a setting where you could configure to run `dart pub get --offline` by default
2. Check the internet connection when saving the `pubspec.yaml` file, and if there is no connection, run the offline variant. And possibly show an info / warning message if fetching --offline.

Personally, the second option makes the most sense to me and would fit my use case the best.

**Describe alternatives you've considered**
Using the command line, but if I save the pubspec.yaml file the command has already begun running.

**Comment by DanTup** [comment]
I don't know if there's a great way for us to reliably detect if we're offline across all platforms, although there's an existing setting to use `--offline` with `Flutter: New Project` so I think making that setting more generic and using it for both probably makes sense.

**Comment by jellynoone** [comment]
Aha, makes sense!

Thank you for addressing this so quickly!
