### ISSUE TITLE
Quick Question: How to Disable Auto-Adding of Braces in String Interpolation

### ISSUE THREAD

**Issue by jeffmikels** [Dart-Code/Dart-Code#3935]
When typing in a string, if I enter a `$`, the plugin adds curly braces automatically making it `${}`. This is convenient for writing expressions, but I'm usually just referencing a variable (i.e. `$myVar` ) and the dart linter recommends omitting the braces in that case.

Is there a way to disable the automatic curly braces when inside a string?

**Comment by DanTup** [comment]
> When typing in a string, if I enter a `$`, the plugin adds curly braces automatically making it `${}`. 

I agree this doesn't sound like good default behaviour, although I'm unable to reproduce it. Are you doing anything more than just typing `$`? Here I'm typing `test $test` in a string:

![Apr-20-2022 15-39-24](https://user-images.githubusercontent.com/1078012/164256176-edd10a0c-e51b-4ff9-b126-f449044610dc.gif)

**Comment by DanTup** [comment]
VS Code has a "Bisect Extension" command that might be helpful if it's coming from an extension. I'd also check your own local snippets (both general, and Dart-specific).

If it does seem to only occur with this extension enabled, let me know and I may be able to come up with some suggestions to track it down. Thanks!

**Comment by jeffmikels** [comment]
It happens for me exactly the same way as when I'm editing a JavaScript file and use the template literals. I'll do some extension pruning... it's probably time for that anyway.
