### ISSUE TITLE
Include device names in generated launch configs for Select & Start Debugging

### ISSUE THREAD

**Issue by guidezpl** [Dart-Code/Dart-Code#3937]
**Is your feature request related to a problem? Please describe.**
Currently, when running multiple instances (e.g. on multiple devices), they are simply numbered, making it hard to identify which one is which.

**Describe the solution you'd like**
Specify the device name in parens such that it shows up in the running instance selector.

<img width="339" alt="Screen Shot 2022-04-21 at 13 14 34" src="https://user-images.githubusercontent.com/6655696/164446586-ec666032-2689-46e0-96a7-29a4cfd68f7b.png">

**Comment by DanTup** [comment]
How are you starting the debug sessions? Do you have a `launch.json`?

Without a `launch.json`, starting with `F5` or the `Run` menu, the device ID should already be added:

<img width="223" alt="Screenshot 2022-04-21 at 14 41 07" src="https://user-images.githubusercontent.com/1078012/164470851-d3140767-7be4-4b7d-9d96-01ddfbf78d2a.png">

If you have a `launch.json` or launch through another means, things may be a little different. I'm not sure it would make sense to overwrite the name supplied in a `launch.json`. We could perhaps support some variable `$deviceName` or something, although it would show literally as the variable in many places in VS Code's UI (like the sidebar) where it's not been replaced as part of launching a debug session 🤔

**Comment by guidezpl** [comment]
Oh, neat I didn't know it was already working in some cases. 

I don't have a `launch.json`, I'm selecting "Select and start debug configuration" in the bottom bar and then selecting Flutter
<img width="623" alt="Screen Shot 2022-04-21 at 16 34 50" src="https://user-images.githubusercontent.com/6655696/164482005-cf9108ad-1814-4381-afb8-4d0720a0d7d5.png">

**Comment by guidezpl** [comment]
Sweet, thanks!

**Comment by guidezpl** [comment]
Ack.
