### ISSUE TITLE
Show color previews in code completion

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#3941]
See https://github.com/dart-lang/sdk/issues/48870#issuecomment-1109617492.

**Comment by DanTup** [comment]
Blocked by https://github.com/microsoft/vscode/issues/66606.

**Comment by RedCMD** [comment]
You could get away with having the label being the hex colour and then the colour name in the `detail` section

![image](https://github.com/Dart-Code/Dart-Code/assets/33529441/fccd03d7-9c28-4835-ae5e-e02f0540aef0)

```ts
const label1: vscode.CompletionItemLabel = {
	label: '#FF0000',
	description: 'Colour',
	detail: ' Red',
};
const completionItem1: vscode.CompletionItem = {
	label: label1,
	range: cursorRange,
	kind: vscode.CompletionItemKind.Color,
	filterText: "red",
	sortText: "red",
	documentation: 'Some text about colours being used for stuff',
	detail: 'Colour ',
};
completionItems.push(completionItem1);

const label2: vscode.CompletionItemLabel = {
	label: '#FF0000',
	description: 'description',
	detail: '1st detail',
};
const completionItem2: vscode.CompletionItem = {
	label: label2,
	range: cursorRange,
	kind: vscode.CompletionItemKind.Color,
	filterText: "red",
	sortText: "red",
	documentation: 'documentation',
	detail: '2nd detail',
	
};
completionItems.push(completionItem2);

const label3: vscode.CompletionItemLabel = {
	label: 'Red',
	description: 'description',
	detail: '1st detail',
};
const completionItem3: vscode.CompletionItem = {
	label: label3,
	range: cursorRange,
	kind: vscode.CompletionItemKind.Color,
	filterText: "red",
	sortText: "red",
	documentation: '#FF0000',
	detail: '2nd detail',
};
completionItems.push(completionItem3);
```

**Comment by DanTup** [comment]
I think this would be really confusing. If you're typing `Colors.red` and after pressing `.` I don't think it's obvious that the item with label "**#ff0000** _red_" is the item you want to select to insert `red`.

**Comment by RedCMD** [comment]
I've just noticed that the code had been updated in VSCode
https://github.com/microsoft/vscode/blob/9962e85fc9e739f33379fea40affadc49f832dac/src/vs/editor/contrib/suggest/browser/suggestWidgetRenderer.ts#L44

you can now use the `detail` field in the documentation section

![image](https://github.com/Dart-Code/Dart-Code/assets/33529441/270de248-a15b-48ca-90bc-572b7505cc7a)

```ts
const label1: vscode.CompletionItemLabel = {
	label: '#FF0000',
	description: 'description',
	detail: '1st detail',
};
const completionItem1: vscode.CompletionItem = {
	label: label1,
	range: cursorRange,
	kind: vscode.CompletionItemKind.Color,
	filterText: "red",
	sortText: "red",
	documentation: 'documentation',
	detail: '2nd detail',
};
completionItems.push(completionItem1);
const label2: vscode.CompletionItemLabel = {
	label: 'Red',
	description: 'description',
	detail: '1st detail',
};
const completionItem2: vscode.CompletionItem = {
	label: label2,
	range: cursorRange,
	kind: vscode.CompletionItemKind.Color,
	documentation: '#FF0000',
	detail: '2nd detail',
};
completionItems.push(completionItem2);
const label3: vscode.CompletionItemLabel = {
	label: 'Red',
	description: 'description',
	detail: '#FF0000',
};
const completionItem3: vscode.CompletionItem = {
	label: label3,
	range: cursorRange,
	kind: vscode.CompletionItemKind.Color,
	documentation: 'documentation',
	detail: '2nd detail',
};
completionItems.push(completionItem3);
const label4: vscode.CompletionItemLabel = {
	label: 'Red',
	description: 'description',
	detail: '1st detail',
};
const completionItem4: vscode.CompletionItem = {
	label: label4,
	range: cursorRange,
	kind: vscode.CompletionItemKind.Color,
	documentation: 'documentation',
	detail: '#FF0000',
};
completionItems.push(completionItem4);
```

**Comment by DanTup** [comment]
> I've just noticed that the code had been updated in VSCode

Oh, good spot - it also looks like maybe it uses a more relaxed (substring) regex in documentation?

https://github.com/microsoft/vscode/blob/9962e85fc9e739f33379fea40affadc49f832dac/src/vs/editor/contrib/suggest/browser/suggestWidgetRenderer.ts#L54

Some changes were made via https://github.com/microsoft/vscode/issues/174496

I will do some testing, thanks!

**Comment by RedCMD** [comment]
> regex is more relaxed, it still checks for start/end

it checks if the hex code is at the very beginning or the very end
so you can still put documentation there

> The detail field currently contains the type which can be useful to know

the 1st `detail` field doesn't work
only the 2nd one in the expandable documentation section does

**Comment by DanTup** [comment]
> it checks if the hex code is at the very beginning or the very end

Oops, I didn't read the condition correctly. I'll take a look, thanks :)

**Comment by DanTup** [comment]
Looks like this works, thank you!

![image](https://github.com/user-attachments/assets/d6b01999-797a-4f45-ad47-6d92fd8c34eb)

**Comment by DanTup** [comment]
This was implemented in https://github.com/dart-lang/sdk/commit/d8376f191ebb0d8b7f60ae0f4517b3541c876ee0. It's a change in the analysis server so it'll show up in a future SDK release (not a Dart-Code release).
