### ISSUE TITLE
Output pane auto-focused on workspace/executeCommand failures

### ISSUE THREAD

**Issue by ronba** [Dart-Code/Dart-Code#3946]
**Describe the bug**
The VSCode output pane is focused automatically whenever workspace/executeCommand fails.  
This is similar to #2280.

**To Reproduce**
1. Move the Output pane to the sidebar or anywhere else where it is out of focus and switch to a different tab.  
2. Create a dart file with an error that would trigger the 'Go to output' notification. For example, this content would work: 
```
class SomeClass {
}
}
```

3. Now when saving the file a dialog like the below should pop up.
![image](https://user-images.githubusercontent.com/10216856/165902678-b66a5e2e-1642-40f0-b037-28aaa39645ef.png)

At the same time the output pane automatically gets focused - **without pressing "Go to output"**.

**Expected behavior**
The output pane should only become focused if 'Go to output' is clicked.

**Analysis**
Looking at the code bundled with the Dart-Code extension - I think the reason is the following change: https://github.com/microsoft/vscode-languageserver-node/commit/a1d9d1a1047923f66606bc9ff36c2495d1045803 which was made available in version 8 of the language client (while it looks like the [extension is still using 7](https://github.com/Dart-Code/Dart-Code/blob/8b09f57a8d95d7a5d7873a13a5deb6be1550364f/package.json#L2644)?

**Workaround**
For now I've just been patching the Dart-Code extension manually :)

**Please complete the following information:**
 - Dart extension version: v3.39.20220411
 - Dart/Flutter SDK version: 2.10.5

**Comment by DanTup** [comment]
> I think the reason is the following change: https://github.com/microsoft/vscode-languageserver-node/commit/a1d9d1a1047923f66606bc9ff36c2495d1045803 which was made available in version 8 of the language client (while it looks like the [extension is still using 7](https://github.com/Dart-Code/Dart-Code/blob/8b09f57a8d95d7a5d7873a13a5deb6be1550364f/package.json#L2644)?

You're right - the next version has not been published as a stable release yet, but I'm expecting it in the coming weeks (it forms part of the LSP 3.17 release). I'll keep this issue open until that's done.

Although, generally I would hope that this message does not pop up very often, as it means something has failed on the server. You mention creating a file with invalid Dart code and pressing Save, but that certainly should not ordinarily trigger this issue. Are you perhaps running some code actions on-save that require valid files?

**Comment by ronba** [comment]
Thanks for the quick reply @DanTup - sounds good! For now I'm just using a tiny patch for the extension code which looks like this:

```
33171c33171
<             this.outputChannel.show(true);
---
>             this.outputChannel.show(items.includes('Go to output'));
```

Based on my output logs the setting that most commonly triggers the popup is `"source.sortMembers": true,` as I manually save my files frequently while working on them.

**Comment by DanTup** [comment]
Ah, thanks for confirming. I think we can handle the error there now (so we fail silently when it's invoked automatically). I've filed #3950 about that and will keep this open to test the other issue after updating the LSP client.

**Comment by DanTup** [comment]
We're now using v8 of the LSP client (fc16c6bb702e0abd740d334afa6df11a73791f72).
