### ISSUE TITLE
Support for "#region-#endregion" in comments

### ISSUE THREAD

**Issue by zuboje** [Dart-Code/Dart-Code#3947]
**Is your feature request related to a problem? Please describe.**
Many programming languages support regions to put together a part of the class or function into segments. It would be nice if dart would support something like this

**Describe the solution you'd like**
When I enter in comments #region #endregion or anything similar it will fold any code between two syntaxes (https://code.visualstudio.com/docs/editor/codebasics#_folding)

**Describe alternatives you've considered**
I can wrap parts of code into "container" and fold that widget but I don't want to add widget just so I can fold code it is unnecessary container.

**Additional context**
This functionality would improve productivity for developers where you can focus on specific code and hide what you don't need. This is especially helpful in flutter screens where this code file can have a lot of lines.

**Comment by DanTup** [comment]
Thanks for the suggestion. This functionality would need to come from the Dart analysis server. There's an open issue tracking it at https://github.com/dart-lang/sdk/issues/34795.
