### ISSUE TITLE
Automatic task for generation of the l10n from the .arb files

### ISSUE THREAD

**Issue by TiffaaMC** [Dart-Code/Dart-Code#3949]
**Is your feature request related to a problem? Please describe.**
We always have to manually generate/regenerate the `.arb` files with a command in the terminal whenever we edit them, or we clone/pull a project.

**Describe the solution you'd like**
Like the task in `pubspec.yaml` that auto runs the command `flutter pub get` when we save it, I'd like to auto run the command `flutter gen-l10n` every time I save my `.arb` files. And probably also an icon at the top right of `.arb` files that does the same, again like the `pubspec.yaml`. Also, running this command whenever we clone/pull a project (like it does with `flutter pub get`) would be nice.

**Describe alternatives you've considered**
Using the command `flutter gen-l10n` in the terminal everytime we edit `.arb` files, or clone/pull a project.

**Additional context**
None.

**Comment by DanTup** [comment]
I've added a new Task and Command (**Flutter: Generate Localizations**) for this. It'll also show up in the context menu for `.arb` files (in both explorer and the editor) and in the menu bar when editing a `.arb` file.

I haven't yet added support to run it on-save, I've split that into #3993.

**Comment by hyungtaecf** [comment]
I added the Run On Save plugin on VS Code, and then added the following settings to VS Code's settings.json:

```
"emeraldwalk.runonsave": {
    "commands": [
      {
        "match": "\\.arb$",
        "cmd": "flutter gen-l10n"
      }
    ]
  },
```

It works perfectly. 👍
