### ISSUE TITLE
 dart version

### ISSUE THREAD

**Issue by marekredon** [Dart-Code/Dart-Code#3951]
Hello everyone, 
i'm maybe a newbie, but, i don't understand my dart's version (2.16.2 upgraded 2 weeks ago) and the actual (v3.40).
Why such a difference ?

**Comment by DanTup** [comment]
v3.40 is the version of the VS Code extension, which provides support for editing Dart in VS Code and is developed in this repository and published to [the VS Code marketplace](https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code).

v2.16 is the version of the Dart SDK which is developed at https://github.com/dart-lang/sdk and is published to https://dart.dev/.

These things are not tied together, as it's possible to download the Dart SDK and use it with other editors. It's also possible to use the latest VS Code extension (3.40) with a number of different Dart SDK versions.

Hope this makes sense!
