### ISSUE TITLE
Snipets not working in dart extension 3.40.0

### ISSUE THREAD

**Issue by Ansmi592** [Dart-Code/Dart-Code#3955]
Re-installed VS code, added extensions for flutter and dart-both versions 3.40.0. Snipets are not working on this version. Changed back to previous one-everything works perfectly fine

**Comment by DanTup** [comment]
@Ansmi592 can you confirm your Dart/Flutter versions and the value of your `dart.useLsp` setting?

I did find a bug today (#3954) but it should only occur if LSP has been explicitly disabled. If you have disabled LSP, do you recall why?

**Comment by Ansmi592** [comment]
Right now I have DART 3.38.2 and Flutter 3.38.1. dart.useLsp ir TRUE.

**Comment by DanTup** [comment]
@Ansmi592 Could you confirm which Dart/Flutter SDK versions you're using?

Could you also provide a screenshot of the exact location you're trying to use a snippet where it's not showing up? Thanks!
