### ISSUE TITLE
Intellisense not working inside some folders

### ISSUE THREAD

**Issue by smsimone** [Dart-Code/Dart-Code#3958]
**Describe the bug**
When editing files under a different folder like `integration_tests` the linter doesn't work. It works only under `test/` and `lib/` folders.

![telegram-cloud-photo-size-4-6048381789468212148-x](https://user-images.githubusercontent.com/64575218/168297740-fbd9c567-84fa-4ad1-9f7b-c395face2b1e.jpg)

As you can see in the screenshot, the `FlutterDriver` object has a `dynamic` type instead of its real one.

**Please complete the following information:**
 - Operating System and version: Monterey 12.3.1
 - VS Code version: 1.67.1
 - Dart extension version: 3.40.0
 - Dart/Flutter SDK version: Flutter 3.0.0 - Dart 2.17.0

**Comment by DanTup** [comment]
I don't seem to be able to reproduce this:

<img width="550" alt="Screenshot 2022-05-16 at 10 40 59" src="https://user-images.githubusercontent.com/1078012/168564724-01b64b7c-4039-4658-bc49-6ea4e1ea2deb.png">

Can you confirm whether analysis has completed when you see this (eg. "Analyzing..." is not still visible on the lower left status bar), and if so, are you able to zip up a complete copy of a sample project (including all the `.dart_tool`, `.packages` etc.) that you can reproduce this with?

Thanks!

**Comment by smsimone** [comment]
I tried to generate a new Flutter project to reproduce it, but it's working correctly. The only project on which this happens is my work's one.

I tried to open the same project on a computer with Ubuntu and it worked correctly, I found this happening only on MacOS

Anyway, my setup is this:

<details><summary>> Flutter doctor</summary><blockquote>
  <details><summary>[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-arm, locale it)
    • Flutter version 3.0.0 at /Users/smaso/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (6 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/smaso/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Users/smaso/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8309675/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Users/smaso/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8309675/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Android Studio (version 2021.1)
    • Android Studio at /Users/smaso/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8193401/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • smasophone (mobile) • 00008110-001470AE34F3801E • ios            • iOS 15.4.1 19E258
    • macOS (desktop)     • macos                     • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)        • chrome                    • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!</summary><blockquote>
  </blockquote></details>
</blockquote></details>


And the extension's logs during while I was trying to pick the definition of `FlutterDriver` class: [Dart extension logs](https://github.com/Dart-Code/Dart-Code/files/8699151/Dart.extension.logs.txt)

**Comment by DanTup** [comment]
@smsimone do you have any additional `analysis_options.yaml`, `pubspec.yaml`, `.dart_tool` folders outside of the root of your project that could be interfering with this?

If not, could you try making a copy of your project (presumably it will still occur there) and then strip out anything sensitive until you either find out what triggers the issue, or you have a small repro that you're able to share? Thanks!

**Comment by smsimone** [comment]
Just found out that in my `analysis_options.yaml` I had:
```yaml
analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*_stories.dart"
    - "**/*.mocks.dart"
    - "**/*.reflectable.dart"
    - "integration_test/**/*.dart"
```

Removing the line `- "integration_test/**/*.dart"` solves the issue

**Comment by DanTup** [comment]
Ah, glad you found it. I believe that's expected behaviour - the files need to be analysed to provide some of this functionality.
