### ISSUE TITLE
Add flutter pub run build_runner build Command in F1

### ISSUE THREAD

**Issue by MinuteReversal** [Dart-Code/Dart-Code#3960]
1. There are multiple versions of flutter sdk (1.25.0-4.0.pre, flutter_windows_2.10.3-stable, flutter_windows_3.0.0-stable) on my computer.
2. Because different projects depend on different flutter sdk. Automated builds also depend on different versions.
3. I don't want to go back and forth to set the flutter version in my computer's environment variables and restart the computer. I want to configure the version of flutter in the settings.json of vscode.
4. Please add the flutter pub run build_runner build command to the extension component

**Comment by DanTup** [comment]
This command should already be runnable via the **Run Task** option.

If you set the `flutter.sdkPath` or `flutter.sdkPaths` options, you should be able to easily switch between different Flutter SDK versions per-project. Running tasks through the command above should use the currently selected version of the SDK.

Does this handle your requirements?

**Comment by MinuteReversal** [comment]
@DanTup Thanks for your answer, but my problem still exists.
My settings.json configuration in vscode is as follows
```json
{
	"dart.flutterSdkPath": "C:\\flutter\\1.25.0-4.0.pre\\bin",
	"dart.flutterSdkPaths": [
		"C:\\flutter\\1.25.0-4.0.pre\\bin",
		"C:\\flutter\\flutter_windows_2.10.3-stable\\bin",
		"C:\\flutter\\flutter_windows_3.0.0-stable\\bin"
	],
	"dart.sdkPath": "C:\flutter\\1.25.0-4.0.pre\\bin\\cache\\dart-sdk\bin",
}
```
The path setting in the windows environment variable is `C:\flutter\flutter_windows_2.10.3-stable\bin`
<kbd>ctrl</kbd>+<kbd>`</kbd>Enter the following command in the terminal
```
dart --version
```
The terminal still returns the flutter version set in my environment variable
```
Dart SDK version: 2.16.2 (stable) (Tue Mar 22 13:15:13 2022 +0100) on "windows_x64"
```
But the C:\flutter\1.25.0-4.0.pre\bin version I configured in vs code should be as follows
```
Dart SDK version: 2.12.0-76.0.dev (dev) (Wed Nov 25 05:22:28 2020 -0800) on "windows_x64"
```

**Comment by DanTup** [comment]
@MinuteReversal unfortunately commands run in the built-in terminal are not affected by the sdk path settings. VS Code has some APIs to support this, but they do not work correctly on macOS so for now I have not shipped it (see https://github.com/microsoft/vscode/issues/99878).

However, commands run via the **Run Task** command/`tasks.json` _should_ use the configured paths. If they do not, I consider that a bug. If you do `F1` -> `Run Task` -> `Flutter` -> `build runner ...`, does that use the configured version?

**Comment by MinuteReversal** [comment]
@DanTup Thanks for your answer.  
What I'm currently experiencing is `F1`->`Run Task`->`flutter`->`No flutter tasks found.Go back⏎`.
 `F1`->`Run Task`->`dart`->`dart:dart pub get` or `dart:dart pub upgrade` or `dart:dartdoc.` or `Go back⏎`
I don't see an option for `build runner ...`

**Comment by DanTup** [comment]
@MinuteReversal do you have `build_runner` in your `pubspec.yaml`, or are you running it from a global activation? If the latter, does listing it explicitly in `pubspec.yaml` temporarily cause it to appear (and if so, does it work correctly)?

**Comment by MinuteReversal** [comment]
@DanTup Thank you for your answer.The problem is solved.
There is indeed a dependency of bulid_runner in pubspec.yaml. `F1`=>`Tasks:Run Task`=>`dart`=>`dart:dart pub run build_runder build`.
I found `dart: dart pub run build_runder build` option.
Thank you very much for your patient answer.

**Comment by DanTup** [comment]
Great, glad you sorted it!
