### ISSUE TITLE
Allow "emulator management" handling to be disabled

### ISSUE THREAD

**Issue by ZaLiTHkA** [Dart-Code/Dart-Code#3968]
**Is your feature request related to a problem? Please describe.**

in a way, yes.. I work on numerous different projects, from standard web projects to hybrid-mobile projects, and I've now added Flutter projects to my environment as well.

I've already been using ["Android iOS Emulator"](https://marketplace.visualstudio.com/items?itemName=DiemasMichiels.emulate) for ages to manage my emulators, which is particularly handy since it does not rely on the currently open project being any specific "mobile" project type.

this Flutter extension now adds an additional "launch emulator" option, but **only** when I have a Flutter project open, resulting in multiple ways to do the "same" thing.

**Describe the solution you'd like**

I would like to be able to disable the "emulator" management features of this Flutter extension.

**Describe alternatives you've considered**

I've considered _not_ using the "Android iOS Emulator" extension, but then I lose my ability to launch an emulator from VSCode to develop my Ionic projects.

I've considered _not_ using this "Flutter" extension, but.. well.. I kinda need it.

**Comment by DanTup** [comment]
> this Flutter extension now adds an additional "launch emulator" option, but only when I have a Flutter project open, resulting in multiple ways to do the "same" thing

Can you clarify exactly what you're asking to be disabled? What/where do things show up that you would prefer did not?

**Comment by ZaLiTHkA** [comment]
no problem, I think this easiest way to do that is with screenshots..

when I open the VSCode Command Palette and type `emulator`, I get the following options with an Ionic Framework project open:

![image](https://user-images.githubusercontent.com/2149312/169010942-6265c490-a069-41c7-80c2-f52bd230be99.png)

but then I get the following options with a Flutter project open:

![image](https://user-images.githubusercontent.com/2149312/169010757-2aa49979-aa57-4143-8ebf-db715bdfd20a.png)

---

I would like to remove the "Flutter: Launch Emulator" action, simply because inconsistency like this in my IDE interactions cause headaches.

**Comment by ZaLiTHkA** [comment]
that's awesome, thank you @DanTup. :)
