### ISSUE TITLE
Snippets aren't showing up

### ISSUE THREAD

**Issue by lukepighetti** [Dart-Code/Dart-Code#3973]
<img width="658" alt="Screen Shot 2022-05-19 at 9 08 12 AM" src="https://user-images.githubusercontent.com/666539/169300748-146fedbb-6a50-45cf-8b35-7575d37fc9fa.png">

```
% flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.2.1 21D62 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.67.2)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

• No issues found!
```

<img width="692" alt="Screen Shot 2022-05-19 at 9 08 57 AM" src="https://user-images.githubusercontent.com/666539/169300879-d3806852-9a36-451b-b565-a4f7943dc499.png">

Workspace has newly generated flutter project as root

**Comment by DanTup** [comment]
@lukepighetti if you type `stf` then cancel code completion (with `escape`) and then re-trigger with `ctrl+space`, does it show up?

If so I think you're seeing https://github.com/Dart-Code/Dart-Code/issues/3969.

A workaround until the next release goes out is to add this to your VS Code settings:

```js
"dart.maxCompletionItems": 100000
```

I had set the default to a number I thought was high enough not to truncate these, but apparently not. In the next SDK release, unranked completion items like snippets will be exempt from the truncation (which is the proper fix and should already be in `master` etc.).

**Comment by warcayac** [comment]
I have similar problem, all your snippets (for Dart and Flutter) are being ignored by VSCode, however it shows some snippets and I don't know where they are from, I've tested for all your snippets with same result. Your snippets were working fine before the recent updates of VSCode/Flutter/Dart.

![ignored](https://raw.githubusercontent.com/warcayac/assets/main/dart_snippets_ignored.png)

**Comment by warcayac** [comment]
**Confirmed**: this is a problem of latest version of this extension, I installed v3.8.2 and snippets are working again.

**Comment by DanTup** [comment]
@warcayac can you try the setting noted above in https://github.com/Dart-Code/Dart-Code/issues/3973#issuecomment-1131711599?

**Comment by warcayac** [comment]
> @warcayac can you try the setting noted above in [#3973 (comment)](https://github.com/Dart-Code/Dart-Code/issues/3973#issuecomment-1131711599)?

It's not working after several releases... any idea about the problem?

**Comment by DanTup** [comment]
@warcayac can you file a new issue and include:

- Your Dart/Flutter SDK Versions (as shown in the bottom right status bar)
- Your VS Code version
- Your Dart extension version
- A screenshot of exactly what you're seeing when the snippet you want isn't showing (including what you've typed)

Thanks!

**Comment by Underemployed** [comment]
Dart SDK version: 3.3.3 (stable) (Tue Mar 26 14:21:33 2024 +0000) on "windows_x64"
![image](https://github.com/Dart-Code/Dart-Code/assets/116073306/637fbc93-f072-4301-bfe6-7b3251057571)
flutter
Flutter 3.19.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 300451adae (10 days ago) • 2024-03-27 21:54:07 -0500
Engine • revision e76c956498
Tools • Dart 3.3.3 • DevTools 2.31.1
![image](https://github.com/Dart-Code/Dart-Code/assets/116073306/aac40914-1cdd-4a17-9676-71359e00e9d8)
![image](https://github.com/Dart-Code/Dart-Code/assets/116073306/f68cd932-7556-4e9d-9bf1-4855a6b13261)

its isnt working pls help

**Comment by DanTup** [comment]
@Underemployed please file a new issue about this, and include a log file captured by:

- Run the [**Dart: Capture Analysis Server Logs** command](https://dartcode.org/docs/logging/#capture-analysis-server-logs)
- Reproduce the issue
- Click **Cancel** on the logging notification to stop logging and open the log
- Remove anything sensitive from the log
- Attach the log to the new issue (perhaps via a [gist](https://gist.github.com/), or email to me at logs@dartcode.org.

Please also include a copy of your `pubspec.yaml`.

Thanks!

**Comment by Underemployed** [comment]
guys i fixed it

i just re extracted and pasted a new flutter 
if that didnt help also try completely removing vscode
