### ISSUE TITLE
Dart Auto Completion Didn't Work As Expectation

### ISSUE THREAD

**Issue by onion108** [Dart-Code/Dart-Code#3978]
**Describe the bug**
I found that the completion list didn't pop-up unless I type `:`.

**To Reproduce**
1. Type anything but `:`

**Expected behavior**
It should pop-up a list, but it didn't

**Screenshots**
That's what it behaves when typing a character that isn't `:`:
<img width="1148" alt="スクリーンショット 2022-05-21 10 55 18" src="https://user-images.githubusercontent.com/57032603/169632332-3e48cc85-fb26-4610-87da-431080a352ef.png">
That's what it behaves when typing `:`:
<img width="1148" alt="スクリーンショット 2022-05-21 10 56 19" src="https://user-images.githubusercontent.com/57032603/169632614-024d923f-1267-48e2-b8c4-297e73c3e1ff.png">

 - Operating System and version: macOS 12.0.1
 - VS Code version: v1.67.0
 - Dart extension version: v3.41.20220516
 - Dart/Flutter SDK version: `dart[v2.17.0]` and `flutter[v3.0.0]`
 - Target device (if the issue relates to Flutter debugging): `nil`

**Comment by onion108** [comment]
P.S. Here is my settings.json file content if needed
```json
{
    "workbench.editorAssociations": {
        "*.ttf": "default"
    },
    "terminal.integrated.tabs.enabled": true,
    "[dart]": {
		// Automatically format code on save and during typing of certain characters
		// (like `;` and `}`).
		"editor.formatOnSave": true,
		"editor.formatOnType": true,

		// Draw a guide line at 80 characters, where Dart's formatting will wrap code.
		"editor.rulers": [80],

		// Disables built-in highlighting of words that match your selection. Without
		// this, all instances of the selected text will be highlighted, interfering
		// with Dart's ability to highlight only exact references to the selected variable.
		"editor.selectionHighlight": false,

		// By default, VS Code prevents code completion from popping open when in
		// "snippet mode" (editing placeholders in inserted code). Setting this option
		// to `false` stops that and allows completion to open as normal, as if you
		// weren't in a snippet placeholder.
		"editor.suggest.snippetsPreventQuickSuggestions": false,

		// By default, VS Code will pre-select the most recently used item from code
		// completion. This is usually not the most relevant item.
		//
		// "first" will always select top item
		// "recentlyUsedByPrefix" will filter the recently used items based on the
		//     text immediately preceding where completion was invoked.
		"editor.suggestSelection": "first",

		// Allows pressing <TAB> to complete snippets such as `for` even when the
		// completion list is not visible.
		"editor.tabCompletion": "onlySnippets",

		// By default, VS Code will populate code completion with words found in the
		// current file when a language service does not provide its own completions.
		// This results in code completion suggesting words when editing comments and
		// strings. This setting will prevent that.
		"editor.wordBasedSuggestions": false,
	},
    "code-runner.executorMapByGlob": {
        "pom.xml": "cd $dir && mvn clean package"
    },
    "editor.fontFamily": "'JetBrains Mono',Fira Code,Menlo, Monaco, 'Courier New', monospace",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "editor.fontLigatures": true,
    "[javascript]": {
        "editor.defaultFormatter": "HookyQR.beautify"
    },
    "tabnine.experimentalAutoImports": true,
    "cmake.configureOnOpen": true,
    "C_Cpp.default.cppStandard": "c++17",
    "C_Cpp.default.cStandard": "c11",
    "C_Cpp.default.intelliSenseMode": "macos-clang-arm64",
    "c-cpp-compile-run.c-flags": "-Wall -Wextra -std=c17",
    "c-cpp-compile-run.cpp-flags": "-Wall -Wextra -std=c++17",
    "C_Cpp.default.compilerArgs": [
        "-std=c++17",
        "-g",
        "${file}"
    ],
    "C_Cpp.default.compilerPath": "g++",
    "clang.cxxflags": [
        "-std=c++17"
    ],
    "background.customImages": [
        "/Users/harrypotter/Pictures/Wolfys Nebell.jpeg"
    ],
    "background.useDefault": false,
    "background.style": {
        "content": "''",
        "pointer-events": "none",
        "position": "absolute",
        "z-index": "1",
        "width": "100%",
        "height": "100%",
        "background-position": "100% 100%",
        // "background-repeat": "repeat",
        "background-size": "contain",
        "opacity": 0.2
    },
    "diffEditor.ignoreTrimWhitespace": false,
    "svg.preview.mode": "svg",
    "files.exclude": {
        "**/.classpath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/.factorypath": true
    },
    "editor.unicodeHighlight.allowedCharacters": {
        "　": true,
        "：": true,
        "！": true
    },
    "[cpp]": {
        "editor.defaultFormatter": "xoanis.clion-formatter"
    },
    "window.autoDetectColorScheme": true,
    "C_Cpp.formatting": "vcFormat",
    "C_Cpp.vcFormat.newLine.beforeElse": false,
    "C_Cpp.vcFormat.newLine.beforeCatch": false,
    "C_Cpp.vcFormat.newLine.beforeOpenBrace.function": "sameLine",
    "C_Cpp.vcFormat.newLine.beforeOpenBrace.block": "sameLine",
    "C_Cpp.vcFormat.newLine.beforeOpenBrace.lambda": "sameLine",
    "C_Cpp.vcFormat.newLine.beforeOpenBrace.namespace": "sameLine",
    "C_Cpp.vcFormat.newLine.beforeOpenBrace.type": "sameLine",
    "C_Cpp.vcFormat.indent.caseLabels": true,
    "C_Cpp.vcFormat.indent.caseContentsWhenBlock": true,
    "C_Cpp.default.includePath": [
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/**",
        "/usr/local/include",
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1",
        "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include",
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include",
        "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include"
    ],
    "c-cpp-flylint.cppcheck.includePaths": [
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/**",
        "/usr/local/include",
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1",
        "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include",
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include",
        "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include"
    ],
    "c-cpp-flylint.clang.includePaths": [
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/**",
        "/usr/local/include",
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1",
        "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include",
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include",
        "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include"
    ],
    "c-cpp-flylint.includePaths": [
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/**",
        "/usr/local/include",
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1",
        "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include",
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include",
        "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include"
    ],
    "editor.unicodeHighlight.allowedLocales": {
        "zh-hans": true
    },
    "editor.accessibilitySupport": "off",
    "C_Cpp.default.systemIncludePath": [
        "/usr/X11/include/**",
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/**"
    ],
    "settingsSync.ignoredSettings": [
        "-C_Cpp.default.intelliSenseMode",
        "-C_Cpp.default.includePath",
        "-C_Cpp.default.forcedInclude"
    ],
    "go.toolsManagement.autoUpdate": true,
    "python.defaultInterpreterPath": "python3",
    "git.enableSmartCommit": true,
    "workbench.iconTheme": "material-icon-theme",
    "workbench.colorTheme": "Material Night",
    "workbench.preferredDarkColorTheme": "Material",
    "workbench.preferredLightColorTheme": "Material Night",
    "kotlin.java.home": "/Library/Java/JavaVirtualMachines/jdk-17.0.1.jdk/Contents/Home",
}
```

**Comment by DanTup** [comment]
Does this happen for other types of files (like `.ts` for TypeScript) or only Dart?

The functionality that opens completion automatically when you type is not controlled by Dart, but by VS Code. It's usually controlled by this setting:

<img width="584" alt="Screenshot 2022-05-21 at 10 42 00" src="https://user-images.githubusercontent.com/1078012/169645744-7b848b4b-46b7-4f85-9efb-84df33ee0797.png">

```
	"editor.quickSuggestions": {
		"other": "on",
		"comments": "off",
		"strings": "off"
	},
```

The default settings are shown above, and `"other": "on"` is what causes it to be shown automatically when not inside a string or comment.

Can you check your _Workspace_ settings as well as user settings to see if this is set?

If it's not that, could you try temporarily disabling all extensions except Dart and see if that makes any difference?

**Comment by onion108** [comment]
> 

I tried 

> Does this happen for other types of files (like `.ts` for TypeScript) or only Dart?
> 
> The functionality that opens completion automatically when you type is not controlled by Dart, but by VS Code. It's usually controlled by this setting:
> 
> <img alt="Screenshot 2022-05-21 at 10 42 00" width="584" src="https://user-images.githubusercontent.com/1078012/169645744-7b848b4b-46b7-4f85-9efb-84df33ee0797.png">
> 
> ```
> 	"editor.quickSuggestions": {
> 		"other": "on",
> 		"comments": "off",
> 		"strings": "off"
> 	},
> ```
> 
> The default settings are shown above, and `"other": "on"` is what causes it to be shown automatically when not inside a string or comment.
> 
> Can you check your _Workspace_ settings as well as user settings to see if this is set?
> 
> If it's not that, could you try temporarily disabling all extensions except Dart and see if that makes any difference?

Thanks for your reply. I just found that the problem is because of `"editor.quickSuggestions": false` in my workspace's `settings.json`. (But I don't know who added this... The project directory is newly generated by `flutter create` and I haven't edited the workspace's setting.json yet. What's more, I can say that no one will edit that file 'cause it's my personal project. That's really strange.)

**Comment by onion108** [comment]
> > 
> 
> I tried
> 
> > Does this happen for other types of files (like `.ts` for TypeScript) or only Dart?
> > The functionality that opens completion automatically when you type is not controlled by Dart, but by VS Code. It's usually controlled by this setting:
> > <img alt="Screenshot 2022-05-21 at 10 42 00" width="584" src="https://user-images.githubusercontent.com/1078012/169645744-7b848b4b-46b7-4f85-9efb-84df33ee0797.png">
> > ```
> > 	"editor.quickSuggestions": {
> > 		"other": "on",
> > 		"comments": "off",
> > 		"strings": "off"
> > 	},
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The default settings are shown above, and `"other": "on"` is what causes it to be shown automatically when not inside a string or comment.
> > Can you check your _Workspace_ settings as well as user settings to see if this is set?
> > If it's not that, could you try temporarily disabling all extensions except Dart and see if that makes any difference?
> 
> Thanks for your reply. I just found that the problem is because of `"editor.quickSuggestions": false` in my workspace's `settings.json`. (But I don't know who added this... The project directory is newly generated by `flutter create` and I haven't edited the workspace's setting.json yet. What's more, I can say that no one will edit that file 'cause it's my personal project. That's really strange.)

P.S. The first "I tried" is that I want to say your solution didn't work, but soon I realized that I haven't checked my workspace's `settings.json` yet LMAO

**Comment by DanTup** [comment]
Great, glad you sorted it!
