### ISSUE TITLE
Update README with feature list, shortcut keys, link to contributing, link to chat

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#4]

**Comment by devoncarew** [comment]
done?

**Comment by DanTup** [comment]
This was really just a placeholder to review what's in the readme for v1 and tidy it up (I might re-do/replace some of the animations, and might squash the release notes etc.) to improve the marketplace (and in-app) info.

I'm also hoping for a response from MS about https://github.com/Microsoft/vscode/issues/10485 as it seems like the GH readme has to be compromised to give the best marketplace experience (I had comments about why my GH readme didn't make it obvious what this was). Eg. I'd also like the build stats badges on the GH readme, but don't think they make sense in the marketplace!

**Comment by DanTup** [comment]
Not sure there's really much value in this case now... It was meant to be a reminder to update the readme for v1 (properly - screenshots/animations/etc., which I stripped out while lots was changing) but I'm not sure 's really adding anything.

**Comment by DanTup** [comment]
Re-opening this; it's not been updated in a while and isn't really a great marketing effort!
