### ISSUE TITLE
Hovering over type name during debugging shows "_Type" as tooltip

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#400]
This seems a bit wonky?

<img width="382" alt="screen shot 2017-08-01 at 18 30 54" src="https://user-images.githubusercontent.com/1078012/28838215-9c6e0558-76e7-11e7-8779-3a8ed1a1f7a2.png">

**Comment by Skylled** [comment]
I guess it's reporting the type of the type, and instead should report maybe the class docs?

**Comment by DanTup** [comment]
My guess is that this is because the hover is being handled by the debugger (an attempt to show you values) and it's giving this wonky result; whereas in this case we'd expect it to be handled by the analyzer.

**Comment by DanTup** [comment]
The way this works is that Code gives us the word under the cursor as `expression` and then we send it for evaluation (using `evaluateInFrame`). Hovering `String` while debugging results in this:

```js
{
   "id":"151",
   "method":"evaluateInFrame",
   "params":{
      "isolateId":"isolates/336819639",
      "frameIndex":0,
      "expression":"String"
   }
}

{
   "jsonrpc":"2.0",
   "result":{
      "type":"@Instance",
      "_vmType":"Type",
      "class":{
         "type":"@Class",
         "fixedId":true,
         "id":"classes\/42",
         "name":"_Type",
         "_vmName":"_Type@0150898"
      },
      "kind":"Type",
      "fixedId":true,
      "id":"classes\/135\/types\/0",
      "typeClass":{
         "type":"@Class",
         "fixedId":true,
         "id":"classes\/135",
         "name":"String"
      },
      "name":"String"
   },
   "id":"151"
}
```

So I guess we should detect that this is a nonsense reply (it's not a value the user would be interested in) and not send back info for a tooltip. I'm not sure how best to do this - the response says the Type is `@Instance` but it's not really an instance, it's just a type name.

@devoncarew How do other IDEs handle this - how do you make sure the debug tooltips only render useful info (and don't block the analyzer tooltips otherwise)? I tried reading through the IntelliJ plugin but couldn't find anything obvious being done (though navigating Java on GitHub probably isn't the easiest way to find it!).

**Comment by DanTup** [comment]
@devoncarew Would checking `result.kind == "Type"` be reasonable? or `result.class.type == "@Class"`?

**Comment by DanTup** [comment]
Ugh, not that simple... When I hover `print` in `print(a);` I get `_Closure`!

And to make things more annoying; not sending the request doesn't seem to cause Code to fall back to the normal hover provider anyway; so at best we're rmeoving the useless tooltips but not providing the dartdocs. Need to investigate that too!

**Comment by devoncarew** [comment]
Not sure I know the best solution here (and AFAIK the IntelliJ plugin doesn't do any special handling here).

Filtering on the return value might be problematic as it could legitimately be an expression that returns a Type or Closure. Perhaps just black-listing a few known strings? (`int`, `String`, `print`, ...).

**Comment by DanTup** [comment]
Black-listing them doesn't help with the users custom classes though; eg given:

```dart
MyClass danny = new MyClass();
```

When I over `danny` I expect it to be satisfied by the debugger, but `MyClass` I expect the analyser. I don't know whether there's currently enough info to make this happen. I'll try comparing some more responses when next working on this and see if things that are not really instances/values can be reliably detected. I don't think there's any value at all in using debugger-provided info when hovering something like `MyClass`; so even if I can't get Code to fall back to the analyser, it shouldn't render a tooltip.

I'm curious though - in a debug session in IntelliJ, what do you see when you hover a class name? Is it something as weird as in the screenshot at the top here?

**Comment by devoncarew** [comment]
Here's for a `print` call:

<img width="496" alt="screen shot 2017-10-03 at 8 18 45 am" src="https://user-images.githubusercontent.com/1269969/31133234-be33526c-a813-11e7-8374-7539dda5c032.png">

In IntelliJ there are separate gestures for tooltips vs hover help, so this may not be as much as issue there (a debugging tooltip shows up on hover, and a dartdoc one generally requires an explicit F1).

> I don't think there's any value at all in using debugger-provided info when hovering something like MyClass

Agree it's pretty low value. It is at least consistent through - if when debugging, a hover always tries to evaluate, and when not a hover always shows dartdoc.

**Comment by DanTup** [comment]
Thanks for the info! I think the behaviour in DC is kinda bad, since the class tooltips suppress the useful ones. Sounds like this isn't an issue for IntelliJ.

I'll see if I can find a way to reliably detect when it's a "useless" tooltip (eg. the thing behind hovered is not an instance of something, such that the runtime debugging version isn't giving any value) to hide it. If I can't get it to fall back to the analyzer hover in that case, I'll raise an issue against Code to see if they can improve it. I don't think we should have to lose all the dartdocs for debug sessions.

**Comment by DanTup** [comment]
Ok, consider this fixed because:

a) the display looks better now; it has no leading underscores (I don't know why :))
b) I think VS Code is getting a feature to show standard hovers during debugging too - I've got an outstanding question but if it works I'm going to set it up for Dart by default.
