### ISSUE TITLE
[LSP] keyword `set` highlighting is not contextual

### ISSUE THREAD

**Issue by lukepighetti** [Dart-Code/Dart-Code#4004]
<img width="374" alt="Screen Shot 2022-06-02 at 10 19 07 AM" src="https://user-images.githubusercontent.com/666539/171650744-ff4d6ef7-ecba-4ae5-a9da-846886b952d5.png">

In the first example,`set` should match the highlighting color of `_foo` because it is a member name, not a keyword (?). I expected LSP to provide this distinction to the syntax highlighter.

**Comment by DanTup** [comment]
@lukepighetti can you confirm what theme you're using? Is it possible it doesn't support (or you have disabled) Semantic Tokens? You need semantic tokens to get correct colors for this. Here's how it looks in the Dark+ theme:

<img width="305" alt="Screenshot 2022-06-02 at 18 29 57" src="https://user-images.githubusercontent.com/1078012/171689011-82379fa1-9bb5-4ee4-8902-6e7a06f8f97a.png">

**Comment by lukepighetti** [comment]
That's it. Thanks.
