### ISSUE TITLE
Coding Flutter Shows White Text

### ISSUE THREAD

**Issue by Ofirfr** [Dart-Code/Dart-Code#4005]
Issue Type: <b>Bug</b>

While coding my app with flutter, I had a good time coding with vs code when one time I opened the editor and it stopped working for Flutter. All I see when I am coding flutter is white text of code and nothing happens when hovering over key words, as if I was using notepad.

Extension version: 3.42.1
VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.11GB free)|
|Process Argv|--crash-reporter-id 31a1abd9-dc15-4ad2-92f5-9814712c5e53|
|Screen Reader|no|
|VM|36%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by DanTup** [comment]
Could you click Help -> Toggle Developer Tools in VS Code, and then click the Console tab, and see if there are any errors listed?

**Comment by Ofirfr** [comment]
Yes they are some issues:
![image](https://user-images.githubusercontent.com/56976381/171824882-96a5f400-14cc-4e1f-b746-e1ec2624affe.png)

**Comment by DanTup** [comment]
It looks like something may be corrupt. Could you attach the following two files here for me to look at?

C:\Users\Ofir\.vscode\extensions\dart-code.dart-code.3.42.1\syntaxes\dart-language-configuration.json
C:\Users\Ofir\.vscode\extensions\dart-code.dart-code.3.42.1\syntaxes\dart.json

I think if you uninstall the Dart extension, then delete the folder:

C:\Users\Ofir\.vscode\extensions\dart-code.dart-code.3.42.1\

Then reinstall the Dart extension, it will likely solve the issue - although I'd like to see the contents of those files to understand what happened.

This has come up before at https://github.com/microsoft/vscode/issues/73134, but it's not clear what's causing it. (@sandy081 FYI - I think this has come up on Discord recently too).

**Comment by Ofirfr** [comment]
Here are the files you asked for:
[dart-language-configuration.zip](https://github.com/Dart-Code/Dart-Code/files/8831351/dart-language-configuration.zip)
I tried to delete the folder and re-install, it worked! 
Thank you very much!

**Comment by sandy081** [comment]
I have not seen this before and also unsure how this can happen unless it can be reproducible. Sorry for not being helpful.

**Comment by DanTup** [comment]
@sandy081 np! I thought it worth mentioning in case it had come up (and if not, if it comes up in future, some info on it reoccurring).
