### ISSUE TITLE
apppppp

### ISSUE THREAD

**Issue by Farrux45** [Dart-Code/Dart-Code#4006]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - Operating System and version:
 - VS Code version:
 - Dart extension version:
 - Dart/Flutter SDK version:
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
@Farrux45 if you're having issues, are you able to provide more details? Thanks!
