### ISSUE TITLE
No tests match regular expression " test & exit /B 0".

### ISSUE THREAD

**Issue by DarkHeros09** [Dart-Code/Dart-Code#4007]
Hi 

vscode is having a problem running tests with a multi-line string description.

How to reproduce:

This will pass:
```dart
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('''test''', (tester) async {});
}
```
This will not pass:
```dart
import 'package:flutter_test/flutter_test.dart';

void main() {

    testWidgets('''
        test
        ''', (tester) async {});

}
```

keep in mind that the later test will pass if run through void main.

```
[√] VS Code (version 1.67.2)
    • VS Code at C:\Users\m_ben\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.42.0
```

**Comment by DanTup** [comment]
I don't seem to be able to repro this:

![Screenshot 2022-06-07 at 10 31 09](https://user-images.githubusercontent.com/1078012/172347195-fd436c56-ae0b-426f-ac5e-4ec2e2e096f9.png)

Could you try capturing some logs?

- Run the [**Dart: Capture Debugging Logs** command](https://dartcode.org/docs/logging/#capture-debugging-logs)
- Run the test and reproduce the failure
- Click **Cancel** on the logging notification to stop logging and open the log
- Remove anything sensitive from the log
- Attach the log here (or in a gist)

Thanks!

**Comment by DanTup** [comment]
Actually, I can repro on Windows.

**Comment by jeff9315** [comment]
I am still having this problem on 3.46.1 using Windows 11. Multiline comments of 3 or more lines fail with this error message when run individually but work when run from a group or from main() in the test file.

**Comment by DarkHeros09** [comment]
yes i can confirm this too on my win10 machine.
```[✓] VS Code (version 1.70.2)
    • VS Code at C:\Users\m_ben\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0```

**Comment by DanTup** [comment]
The original test case above seems to work for me, but the test case in #4125 does not, so I think there's something else giong on. Let's use #4125 instead of re-opening this, since the case reported above does seem fixed.
