### ISSUE TITLE
Embedded DevTools window is empty with "Not found" message

### ISSUE THREAD

**Issue by Ruzo** [Dart-Code/Dart-Code#4008]
When `Dev Tools Location` is set to `beside` or `active`, the embedded DevTools window is empty with only a "Not found" message.

**Steps to reproduce the behavior:**
1. In settings, choose `beside` or `active` as the `Dev Tools Location` option.
2. Start debugging

**Expected behavior**
An embedded DevTools window containing widget trees information.

**Screenshots**
![DevTools_WidgetInspector_issue](https://user-images.githubusercontent.com/1992115/172236063-b40c6c2e-c8bc-40d0-8abe-f71d3d7781be.png)

**Please complete the following information:**
 - Operating System and version: macOs Monterey - version 12.4
 - VS Code version: 1.68.0-insider
 - Dart extension version: v3.42.1
 - Dart/Flutter SDK version: Channel beta, 3.1.0
 - Target device (if the issue relates to Flutter debugging): Any

**Comment by Ruzo** [comment]
This issue was created as per @DanTup's request.

The workaround Dan provided was to add a custom `Dev Tools Port` that is not in the range `9100-9110` (for example, `9199`)

**Comment by DanTup** [comment]
I suspect once https://github.com/flutter/devtools/issues/3896 is solved this problem may go away, but I'll keep this open for now to collect info in case there's some additional going on when embedded in VS Code.

**Comment by DanTup** [comment]
In https://github.com/flutter/devtools/issues/4417, @Noahbanderson reported that after upgrading the Flutter 3.3 the issue didn't come back even after removing the port number. I wonder whether something that changed that bypassed the old cache. I'd be interested to know if the same is true for you.

**Comment by Ruzo** [comment]
> 

Hi @DanTup, I've been using 3.3 since beta and I'm on `Flutter 3.3.0-0.5.pre • channel beta` right now. I've just tried removing the port number and it seems to be working perfectly without it.

**Comment by DanTup** [comment]
Great! I suspect some of the caching changes made in DevTools have probably resolved this particular issue then. I'll close this, but if you (or anyone else) sees this again on >= Flutter 3.3 / Dart 2.18, please let me know.
