### ISSUE TITLE
Support showing properties in debugger tooltips/watch

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#401]
There are loads of properties shown in this completion list; yet the debug tooltip only shows a few. Not sure if this is expected (before I investigate this, do you know if this is a bug @devoncarew?) but it seems confusing to me.

<img width="477" alt="screen shot 2017-08-01 at 18 35 48" src="https://user-images.githubusercontent.com/1078012/28838544-920c7792-76e8-11e7-8632-4d8c6cbde55b.png">
<img width="596" alt="screen shot 2017-08-01 at 18 36 18" src="https://user-images.githubusercontent.com/1078012/28838543-91ff17a0-76e8-11e7-882d-e50c4ce9cbd0.png">

**Comment by DanTup** [comment]
Ok, so this turns out to be that the debugger isn't calling getters.

This seems kinda crazy to me; there's data on these objects that I can't see using the debugger (yet can with print!)! It seems to have come up a few times:

https://github.com/dart-lang/sdk/issues/14668
https://github.com/dart-lang/sdk/issues/19506
https://github.com/dart-archive/eclipse3/issues/25
https://github.com/dart-lang/sdk/issues/10270

In C# the debugger invokes getters by default (assuming it's unlikely to have negative side-effects) and it doesn't seem to be an issue (though there's [an option to disable it](https://i.stack.imgur.com/jJ8LK.jpg)).

I'd like to investigate if we can change this (either giving the user an option, or letting them expand the value to fetch it lazily). Getters are really common (for example in the analyzer AST classes above) and this seems to make debugging much more complicated than it could be.

@devoncarew - you made a comment [here](https://github.com/dart-archive/eclipse3/issues/25#issuecomment-128520525) that reads like it should be possible for me to get these, but I can't figure it out - I can't see `accessorPropertiesOnly` or `getProperties` in the service doc. Is it possible for me to get properties via Observatory here?

**Comment by devoncarew** [comment]
@DanTup - you're right - the vm is returning info for the fields. For the getters, we'd need to look at the description of the class (and it's parents), collect all the getters, eval them ,and then show them as properties on the object.

Given the amount of expr. evaluation that would trigger, it would be worth exploring whether we could delay that expr evaluation until the user expressed interest in a specific value (selected it in the debugger?).

The class hierarchy and field definitions may not be exposed in the typescript service protocol library, but that info is there (and doc'd in the spec). Showing the getters would be a pretty cool addition :)

**Comment by DanTup** [comment]
Cool, I'll see what capability Code has for letting the user invoke these (full VS does it fit C# iterators, so I can't imagine Code had overlooked it) and see if I can wire it up :-)

**Comment by DanTup** [comment]
Might not be able to do this well without some support from Code:

https://github.com/Microsoft/vscode/issues/31995

Though maybe in the meantime if we completion in the debugger console it'll go some way towards solving the same issue (difficulty in examining objects during debugging):

https://github.com/Dart-Code/Dart-Code/issues/169

**Comment by DanTup** [comment]
Seems like there's not much interest in extending Code, so I'm not sure how best to proceed. I'd be interested in some opinions and have posted on dart-misc here:

https://groups.google.com/a/dartlang.org/forum/#!topic/misc/XoGTbBe21Yc

@devoncarew to your knowledge, do any of the other IDEs show getters? It's been a real pain for me debugging analyzer changes, but seems unlikely that the debugging story is bad like this for everyone?

**Comment by devoncarew** [comment]
None of them do; when I do need info from getters (when I'm doing debugging), I'm able to use expression evaluation manually to get the info.

Generally though, I think we do want to show info from getters, I'd just be concerned w/ lots of automatic expression evaluation.

**Comment by DanTup** [comment]
> None of them do; when I do need info from getters (when I'm doing debugging), I'm able to use expression evaluation manually to get the info.

Yeah, I think if I can get completion working in the debug console it'll make this much easier.

> Generally though, I think we do want to show info from getters, I'd just be concerned w/ lots of automatic expression evaluation.

Because of side-effects, or performance?

With no support from Code here, I don't know if we could do it on user action without making it look like a sub-object in the UI (so it needs to be expanded). So it might come down to one of:

- No getters in tooltips/watch, only in debug console
- Fake objects you need to expand to see the values (I don't know if we could make these look obviously different, need to have a play)
- Automatic getter invocation (all of them on the object in one go) with a setting to disable

None seem ideal; not sure which would be the least bad!

**Comment by devoncarew** [comment]
> Automatic getter invocation (all of them on the object in one go) with a setting to disable

interesting idea!

> Because of side-effects, or performance?

I'm mostly thinking of side-effects. Things like getters and toString() are supposed to be side-effect free, but user code may or may not follow that.

**Comment by DanTup** [comment]
Yeah, that's why in Visual Studio/C# there's an option to disable it, but it's on by default. Personally I think it would be great to copy this (I want to just see all the values in the debugger tooltip without clicking every single one), but I've not written/read enough Dart to know how safe it is.

Since Code's settings can also be set at the workspace level, it would also allow opting-out at a project level if you did have something specific that had side effects so you didn't want to call the getters during debugging.

There's always the option of doing this, and shipping it opt-in and getting some feedback. If it's good, the default could be flipped (possibly even with a prompt like the debug-my-code setting) and see how things go.

I've only worked on one codebase where there were side-effects in getters and that was a pain to debug even without that (and there were many bugs that stemmed from it!).

**Comment by devoncarew** [comment]
> Yeah, that's why in Visual Studio/C# there's an option to disable it, but it's on by default. 

That sounds like a pretty reasonable way to go :) Evaluating just on selection (or some other way of expressing interest) would mean you wouldn't have to have a preference, but sounds like it's not possible in VSCode.

**Comment by DanTup** [comment]
I'm working on the analyzer code again and rediscovering how frustrating this is. Stopped at a debugger trying to examine an AST node to see where the data I need is, and I can't find it. And the types can't be `json.encode()d` so there's no quick way to see all of the data (as far as I can tell, at least).

I'm surprised people don't have pitchforks out; it's super frustrating. Maybe people don't use getters so much? Anyway, I might have a shot at this in the not-too-distant future; even if only for my own selfish benefit 😁

**Comment by devoncarew** [comment]
> I might have a shot at this in the not-too-distant future

👍 awesome, I think this would be super useful

**Comment by DanTup** [comment]
Got this working; though it resulted in quite a few calls to the VM (we have to call to get the functions for each class up the hierarchy, and then evaluate each one of them), but I think it's still useful enough to default on and let people opt-out if they want.

<img width="918" alt="screen shot 2018-05-21 at 3 14 15 pm" src="https://user-images.githubusercontent.com/1078012/40312098-c82eef46-5d09-11e8-889e-54042815c74c.png">

I'm gonna add a few more tests, but I might merge this in for the next v2.13 beta since it seems reasonably safe.

**Comment by DanTup** [comment]
Done by #924.
