### ISSUE TITLE
A `super` modifier in the constructor causes a parsing error

### ISSUE THREAD

**Issue by myConsciousness** [Dart-Code/Dart-Code#4012]
**Describe the bug**

A `super` modifier in the constructor causes a parsing error.

```bash
The argument type 'Includes? (where Includes is defined in /Users/katoshinya/twitter-api-v2/lib/src/service/common/includes.dart)' can't be assigned to the parameter type 'Includes? (where Includes is defined in /Users/katoshinya/twitter-api-v2/lib/src/service/includes.dart)'.dart[argument_type_not_assignable](https://dart.dev/diagnostics/argument_type_not_assignable)
includes.dart(19, 7): Includes is defined in /Users/katoshinya/twitter-api-v2/lib/src/service/common/includes.dart
```

**To Reproduce**

**Expected behavior**

**Screenshots**

<img width="1123" alt="スクリーンショット 2022-06-09 10 10 49" src="https://user-images.githubusercontent.com/13072231/172743136-04873a02-39ae-406b-8d60-983f7af1dd5e.png">

<img width="807" alt="スクリーンショット 2022-06-09 10 11 16" src="https://user-images.githubusercontent.com/13072231/172743176-895b12d7-c58a-498f-9768-d4b2241ca6bb.png">

**Please complete the following information:**
 - Operating System and version:
     - M1 macOS Monterey
 - VS Code version:
     - 1.67.2
 - Dart extension version:
     - v3.42.1
 - Dart/Flutter SDK version:
     - Flutter 3.0.1
     - Dart 2.17.1
 - Target device (if the issue relates to Flutter debugging):
 - Repository
     - https://github.com/twitter-dart/twitter-api-v2

**Comment by myConsciousness** [comment]
And error codes:

```bash
[Error - 10:11:04 AM] Request textDocument/codeAction failed.
  Message: Analysis failed for file
  Code: -32013 
/Users/katoshinya/twitter-api-v2/lib/src/service/tweets/tweets_service.dart
[Error - 10:11:04 AM] Request textDocument/documentColor failed.
  Message: Analysis failed for file
  Code: -32013 
/Users/katoshinya/twitter-api-v2/lib/src/service/tweets/tweets_service.dart
[Error - 10:11:04 AM] Request textDocument/documentSymbol failed.
  Message: Analysis failed for file
  Code: -32013 
/Users/katoshinya/twitter-api-v2/lib/src/service/tweets/tweets_service.dart
[Error - 10:11:04 AM] Request textDocument/codeAction failed.
  Message: Analysis failed for file
  Code: -32013 
/Users/katoshinya/twitter-api-v2/lib/src/service/tweets/tweets_service.dart
[Error - 10:11:04 AM] Request textDocument/hover failed.
  Message: Analysis failed for file
  Code: -32013 
/Users/katoshinya/twitter-api-v2/lib/src/service/tweets/tweets_service.dart
[Error - 10:11:05 AM] Request textDocument/hover failed.
  Message: Analysis failed for file
  Code: -32013 
/Users/katoshinya/twitter-api-v2/lib/src/service/tweets/tweets_service.dart
[Error - 10:11:05 AM] Request textDocument/codeAction failed.
  Message: Analysis failed for file
  Code: -32013 
/Users/katoshinya/twitter-api-v2/lib/src/service/tweets/tweets_service.dart
[Error - 10:11:06 AM] Request textDocument/hover failed.
  Message: Analysis failed for file
  Code: -32013 
/Users/katoshinya/twitter-api-v2/lib/src/service/tweets/tweets_service.dart
[Error - 10:11:17 AM] Request textDocument/hover failed.
  Message: Analysis failed for file
  Code: -32013 
/Users/katoshinya/twitter-api-v2/lib/src/service/tweets/tweets_service.dart
[Error - 10:12:25 AM] Request textDocument/hover failed.
  Message: Analysis failed for file
  Code: -32013 
/Users/katoshinya/twitter-api-v2/lib/src/service/tweets/tweets_service.dart
[Error - 10:12:25 AM] Request textDocument/hover failed.
  Message: Analysis failed for file
  Code: -32013 
/Users/katoshinya/twitter-api-v2/lib/src/service/tweets/tweets_service.dart
```

**Comment by DanTup** [comment]
@myConsciousness are you able to share a small project that reproduces this that I can test with? I tried to do something similar but couldn't trigger the issue:

<img width="639" alt="Screenshot 2022-06-09 at 10 54 28" src="https://user-images.githubusercontent.com/1078012/172820316-2b0c6d8c-a179-4674-9c32-bcd797c10b2e.png">

I tried with both my SDK min constraint set to 2.17 (to enable super-params) and also 2.12 (to disable super-params). Neither triggered the "Analysis failed" issue you're seeing, so I think there may be something else different.

Something that does seem odd in your screenshot, is the `unused_import` error seems to reference a different import to the one in your file? It says `"common/includes.dart"` but the line says `"tweets/matching_rule.dart"`. Have you renamed these files recently?

Also, the error:

> The argument type 'Includes? (where Includes is defined in /Users/katoshinya/twitter-api-v2/lib/src/service/common/includes.dart)' can't be assigned to the parameter type 'Includes? (where Includes is defined in /Users/katoshinya/twitter-api-v2/lib/src/service/includes.dart)'.dart[argument_type_not_assignable](https://dart.dev/diagnostics/argument_type_not_assignable)
includes.dart(19, 7): Includes is defined in /Users/katoshinya/twitter-api-v2/lib/src/service/common/includes.dart

suggests you may have two definitions of `Includes` (one in `src/service/common/includes.dart` and one in `src/service/includes.dart`). If you don't, perhaps the server is somehow out of sync? Or does VS Code have additional open unsaved files that might cause this?
