### ISSUE TITLE
Completion for itemBuilder functions differs when itemBuilder is not the first argument

### ISSUE THREAD

**Issue by makayasa** [Dart-Code/Dart-Code#4013]
- macOS Monterey
- VS code version 1.67.2
- Dart extension Version : 3.42.1
- Flutter extension : 3.42.0

Some of the Snippet like fun to create function is missing. Autocomplete for itemBuilder / separatorBuilder is also not work properly, it only work when you move the parameter to the very top. Been uninstall the VScode with AppCleaner and reinstall it seems not working.

<img width="690" alt="Screen Shot 2022-06-08 at 23 30 53" src="https://user-images.githubusercontent.com/52215902/172752462-0183b192-6912-4fa5-a0b2-a2e6d8e13cf8.png">
<img width="690" alt="Screen Shot 2022-06-08 at 23 31 03" src="https://user-images.githubusercontent.com/52215902/172752480-4d651e34-7933-4957-be16-979bed4bb844.png">
<img width="690" alt="Screen Shot 2022-06-08 at 23 31 13" src="https://user-images.githubusercontent.com/52215902/172752484-e919b64b-45c9-4a02-b426-2b87f116b387.png">
<img width="690" alt="Screen Shot 2022-06-08 at 23 31 24" src="https://user-images.githubusercontent.com/52215902/172752491-bda2decf-9cf2-4a4d-b0a9-14871a76230f.png">
<img width="865" alt="Screen Shot 2022-06-09 at 09 32 46" src="https://user-images.githubusercontent.com/52215902/172752492-bcc6bfcb-9c3b-49bb-8777-55d8bd0bf105.png">

**Comment by DanTup** [comment]
Thanks - it seems like there are two issues here:

1. Completion for `(context, index) => ` is not showing up correctly when itemBuilder is the first arg
2. The function snippet ("fun") is missing

Since these are different issues, I've opened #4017 about the missing snippet, and will use this issue for the first one.

**Comment by DanTup** [comment]
Looks like the closure issue has already been fixed. In Flutter's `master` channel I now see it show up:

<img width="577" alt="Screenshot 2022-06-09 at 11 54 45" src="https://user-images.githubusercontent.com/1078012/172830992-04289e96-47a2-4385-a100-60e722f5a127.png">

So nothing is required here, that fix will show up in the next major Flutter release automatically.

I'll follow up on #4017 about the `fun` snippet issue. Thanks!
