### ISSUE TITLE
"fun" snippet to create functions are missing 

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#4017]
Split from #4013. When moving snippets to the server, the "fun" snippet was lost.

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/5b3bfe413716a6121008f160d39966d53ca3ec0a. Ships in the server, so will show up in the next major SDK release(s).

**Comment by cemccccc** [comment]
we are waiting for it
