### ISSUE TITLE
Detecting/Recognizing generated test files

### ISSUE THREAD

**Issue by KaDokta** [Dart-Code/Dart-Code#4018]
**Is your feature request related to a problem? Please describe.**
I wrote a small builder that automatically generates tests based on methods of a class via `source_gen`. However, since the generated files always have the ending "_test.g.dart", they are not recognized by Dart as test files, since Dart expects them in the format of "_test.dart".

I've already looked around, but haven't found a straightforward solution to the problem, since the test name seems to be not configurable. Please let me know if I am wrong in that regard, maybe I just missed it.

**Describe the solution you'd like**
Allow the Dart test runner to also recognize generated test files, e.g. files that end with "_test.g.dart". 

**Describe alternatives you've considered**
Renaming every automatically generated file, which somewhat defeats the purpose of having automatically generated tests. I also thought about automating the renaming, but haven't found a good way to do that yet.

**Comment by KaDokta** [comment]
I've found a solution that is suitable for me now (creating my own builder that ignores the file extension constraints of source_gen and creates "_test.dart" files). Therefore, the feature is not necessary anymore.

**Comment by DanTup** [comment]
@KaDokta I think the original request is reasonable and shouldn't be difficult to support, so if you hit any issues with the way you've done it and think it should be looked at, please do feel free to re-open. Thanks!
