### ISSUE TITLE
Flutter dependencies are not detected when using Flatpak install of VS Code

### ISSUE THREAD

**Issue by Ridhubharan** [Dart-Code/Dart-Code#4019]
VSCode flatpak not able to detect installed libraries
I installed flutter with all its dependencies on my system. I ran flutter doctor and everything was good. Then I installed vscode through flathub. I also installed the Flutter extension from the store. When i ran flutter doctor form the IDE, it shows some dependencies are not there.

Screenshots:
![](https://user-images.githubusercontent.com/41824719/173233340-e1707c99-4e8b-4b78-831f-f906262ca095.png)

Desktop:
OS: Fedora 36 (Workstation)
Installed through: Flatpak

**Comment by DanTup** [comment]
Can you try spawning VS Code from the terminal where things work (eg. running `code`) and see if that changes the results?

If so, my guess is that the things that are missing are being found at the terminal using environment variables (for example `ANDROID_HOME` or `ANDROID_SDK_ROOT` for the Android SDK), but those variables are being set in terminal startup scripts, so the the VS Code process does not inherit them.

If so, you can handle the Android SDK using the command shown in the output (`flutter config --android-sdk`).

For `clang++`, it doesn't seem like there's a way to tell Flutter where to find it, so you might need to ensure it's available on the `PATH` that VS Code inherits (if you run the **Dart: Open Extension Log** command and search for `[General] [Info] Environment PATH:` you should be able to see the path VS Code got), and not only added to `PATH` in a terminal startup script.

If this doesn't resolve the issue, please let me know!

**Comment by Ridhubharan** [comment]
I launched VS Code from terminal and it was able to detect the "Android SDK", but couldn't detect java installed on my system.
![image](https://user-images.githubusercontent.com/41824719/173499089-59bfc5f6-ecb1-4753-a379-1193ee09242b.png)

I tried searching for a way to make clang++ available, but it seems that the directory "/usr/bin/" is blacklisted by flatpak. I sadly couldn't find a workaround.

**Comment by DanTup** [comment]
Just to confirm - if you run `flutter doctor` from the terminal, both Java and `clang++` are detected, but if you launch Code from the same terminal and then run the **Flutter: Run Flutter Doctor** command from that instance of VS Code, they're not detected?

Can you check you closed all VS Code instances before launching it from the terminal (in case it is reusing existing processes)?

**Comment by Ridhubharan** [comment]
> Just to confirm - if you run flutter doctor from the terminal, both Java and clang++ are detected, but if you launch Code from the same terminal and then run the Flutter: Run Flutter Doctor command from that instance of VS Code, they're not detected?
Yes, that's correct.

> Can you check you closed all VS Code instances before launching it from the terminal (in case it is reusing existing processes)?
I terminated all instances and tried, but it didn't help. I even restarted my system, but it didn't work.

**Comment by Ridhubharan** [comment]
Some seem to be missing.
The output of the **echo $PATH** from terminal is:
`/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/lowkey/Development/flutter/bin:/home/lowkey/Development/Android/cmdline-tools/latest/bin/:/home/lowkey/Development/Android/emulator/:/home/lowkey/Development/Android/platform-tools/`

And the log from **Dart: Open Extension Log** is:
[dart-code-startup-log-4a2e.txt](https://github.com/Dart-Code/Dart-Code/files/8901199/dart-code-startup-log-4a2e.txt)

**Comment by DanTup** [comment]
Thanks - I had a quick search and it seems like Flatpak might be deliberately sandboxing applications?

https://docs.flatpak.org/en/latest/sandbox-permissions.html

> No access to any host files except the runtime, the app, `~/.var/app/$FLATPAK_ID`, and `$XDG_RUNTIME_DIR/app/$FLATPAK_ID`. Only the latter two being writable.

So I think this is probably working as Flatpak intends (at least by default), with the VS Code installation is isolated from everything else. There's some info in their docs linked above (and [here](https://docs.flatpak.org/en/latest/manifests.html#finishing)) that might help you configure it so these things can be accessed by VS Code, but it's not something I'm at all familiar with I'm afraid.

**Comment by Ridhubharan** [comment]
I tried running vscode with `flatpak run --filesystem=/usr/bin/ com.vscodium.codium`, but couldn't get vscode to detect clang++ located in "/usr/bin/"

**Comment by DanTup** [comment]
Does running `/usr/bin/clang++` from the VS Code embedded terminal work? If so, then it's like a `PATH` issue and you need to ensure Flatpak passes the `PATH` env variable. It's possible that [something like `--env=PATH=$PATH` to `flatpak run`](https://unix.stackexchange.com/questions/559129/how-do-i-permanently-set-an-environment-variable-for-a-specific-flatpak-applicat) might work, but if Flatpak is overwriting the `PATH` then I'm not sure.

If `/usr/bin/clang++` does not work from the built-in terminal, then perhaps something else is wrong. I would suggest asking somewhere that there are Flatpak users that may be able to advise. It's unfortunately not something I'm familiar with nor set up to test.

**Comment by Ridhubharan** [comment]
I tried `flatpak override --user --env=PATH=$PATH com.vscodium.codium` but i got this error `bwrap: execvp codium: No such file or directory`

**Comment by DanTup** [comment]
I'm afraid I don't know enough about Flatpak to know what's wrong (or whether this is the best/correct/even working way to set the `PATH`). You'd be better asking somewhere with Flatpak users, as they may know what you need to do so VS Code can access the requires locations (and have them on `PATH`). Alternatively, if you can install VS Code outside of Flatpak, perhaps that would also work?

**Comment by Ridhubharan** [comment]
## Solution Found!!
After a lot of research, I have found a way to make "Flutter Extension" work with flatpak version of vscode.

### Steps:
1. flatpak install org.freedesktop.Sdk.Extension.llvm14
2. flatpak install org.freedesktop.Sdk.Extension.openjdk11/x86_64/21.08 (or desired arch and version)
3. Add env variables ANDROID_HOME=/home/lowkey/Development/Android FLATPAK_ENABLE_SDK_EXT=* to vscode (I used Flatseal to add the variables)
![image](https://user-images.githubusercontent.com/41824719/174088545-734a9614-6edf-4aa6-a0cf-7a3a4b27fd1d.png)

After this close all instances of vscode and restart. Vola! Everything works as expected.
