### ISSUE TITLE
Ctrl+Click on constructor declarations does not find references, but the same on method declarations does

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#4020]
```dart
void main() {
  A.named().foo();
  A.named().foo();
}

class A {
  A.named() {} // Ctrl+Click on named does nothing
  void foo() {} // Ctrl+Click on foo finds the references above
}
```

It seems like VS Code may be sending requests for both definition+references in the case that works, but only definition in the case that doesn't (perhaps the response to definition being empty is suppressing the later?).

**Comment by scheglov** [comment]
My opinion:
1. `new A.named()`: from `A` to `class A`, from `named` to `named` in `A.named` declaration.
2. `new A()`: from `A` to the unnamed `A()` constructor declaration.
3. `A.named()` declaration: from `A` to `class A`, from `named` - nothing.
4. `A()` declaration: form `A` to `class A`.

I think navigation from a declaration name to the declaration name is useless, and exists as only an artifact of the way navigation is implemented - go down to `SimpleIdentifier` and then blindly get its element, sometimes look for special cases, and build navigation. First of all, the declaration should not use `SimpleIdentifier` as its "name". It is not an expression, there is no meaning for its type and element. The declaration might declare an element, which might be used to construct a type. But the name - no. And navigation is useless - we already there.

**Comment by DanTup** [comment]
> My opinion:

Thanks! I think this way is my preference too, so I'll go that way and update the existing tests.


> I think navigation from a declaration name to the declaration name is useless, and exists as only an artifact of the way navigation is implemented

VS Code is actually using this as a signal to support the functionality described above. If it asks for a Definition and the result is the same location where it was invoked, it will immediately perform Find References instead:

<img width="667" alt="Screenshot 2022-06-14 at 17 37 33" src="https://user-images.githubusercontent.com/1078012/173630376-434ad0e4-68b9-4050-87a2-88e82dedfa95.png">

So if there's reason to remove it for non-LSP, we should probably either have a flag to include it, or handle it in the LSP handler.

**Comment by bwilkerson** [comment]
> 3. `A.named()` declaration: from `A` to `class A`, from `named` - nothing.
> 4. `A()` declaration: form `A` to class `A`.

I don't have a strong objection, but it doesn't seem useful to me to be able to navigate from the declaration of a constructor to the top of the class in which the constructor is defined.

I think I'd rather have Find References work in those locations.

> So if there's reason to remove it for non-LSP, we should probably either have a flag to include it, or handle it in the LSP handler.

I might be wrong, but I don't think we have enough information in the LSP handler. I'm fine with just changing the behavior everywhere and see whether it causes a problem for our IntelliJ / AS users.

**Comment by DanTup** [comment]
> I don't have a strong objection, but it doesn't seem useful to me to be able to navigate from the declaration of a constructor to the top of the class in which the constructor is defined.

Yeah, I'm not sure it's _very_ useful, but the constructor name can still be used for references. It feels more predictable if the declaration + call sites work the same (and if we have call sites also treat the class name as part of the constructor, that makes them inconsistent with static methods - which are often used in place of constructors). 

I think having a rule of "Class name is always a reference to the class, unless it's obvious the default constructor" is simpler than having additional exceptions.


> I might be wrong, but I don't think we have enough information in the LSP handler

I guess I meant if the navigator returned no results, we could just look at the node at the offset ourselves and see if it's a declaration (or use some other API that may exist). I didn't think long about it though, as it didn't sound like there was a compelling reason to change this right now (and if we do in future, the new tests I'm adding for LSP will make it clear we need to add something for it).

**Comment by scheglov** [comment]
Well, I have to correct myself. Navigation from `A()` declaration to `class A` would be inconsistent with searching constructor references. We don't want to search class references instead, and forcing users to write `A.new()` declaration is not an option :-)

So, maybe no navigation from `A()` at all.

**Comment by DanTup** [comment]
I've opened https://dart-review.googlesource.com/c/sdk/+/248581/ with the changes described above (treating the class name as a reference to the class unless it is an unnamed constructor, where it is a reference to the constructor).

If any of the changes in the existing tests don't match what you expected/preferred from the above, please let me know!

**Comment by scheglov** [comment]
> > So if there's reason to remove it for non-LSP, we should probably either have a flag to include it, or handle it in the LSP handler.
> 
> I might be wrong, but I don't think we have enough information in the LSP handler. I'm fine with just changing the behavior everywhere and see whether it causes a problem for our IntelliJ / AS users.

It seems that IntelliJ also sends `search.findElementReferences` when I ask to "navigate" from a declaration name. So, apparently users like it.
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/384794/174106269-761356fd-c16e-4fad-8d38-f86d143f5d3b.png">

**Comment by DanTup** [comment]
Ah nice. I guess it probably makes sense leaving it as-is this way in the navigation computer then :)

Fix has landed in https://github.com/dart-lang/sdk/commit/a2f9ad4ba71b967a1378e1f5d89a2dd9e62019d0.
