### ISSUE TITLE
Code Action "Add curly braces" adds a backslash before the closing curly brace

### ISSUE THREAD

**Issue by Ruzo** [Dart-Code/Dart-Code#4022]
**Describe the bug**
When the Code Action "Add curly braces" or "Add curly braces everywhere in file" is applied, a backslash is added right before the closing curly brace(s).

**To Reproduce**
1. Write an `if` or `if...else` statement without curly braces.
2. Click on lightbulb and choose the "Add curly braces" or "Add curly braces everywhere in file".

**Expected behavior**
Opening and closing curly braces are added without any extra character.

**Screenshots**
![add_curly_braces_issue](https://user-images.githubusercontent.com/1992115/174124239-c7d71fed-75f0-4802-a72f-02f71aaf26ed.jpg)

**Please complete the following information:**
 - Operating System and version: macOS Monterey 12.4
 - VS Code version: Version: 1.69.0-insider
 - Dart extension version: v3.42.1
 - Dart/Flutter SDK version: Flutter 3.0.2 • channel stable / Tools • Dart 2.17.3 • DevTools 2.12.2
 - Target device (if the issue relates to Flutter debugging): N/A

**Comment by DanTup** [comment]
I don't seem to be able to reproduce this:

![Jun-17-2022 12-15-25](https://user-images.githubusercontent.com/1078012/174288061-d744bda8-a93d-4461-ab4b-f356ba5d9a7d.gif)

Could you confirm if it happens in a branch new project (created with  **Dart: New Project** or **Flutter: New Project**) for you?

If not, could you share a small repro project it _does_ occur in that I can test with?
If it does occur in a new project for you, could you capture a log:

- Run the **Dart: Capture Analysis Server Logs** command
- Move the cursor away from the `if` statement and then move it back
- Use the lightbulb menu to apply the edit

Can you also confirm whether you see "LSP" or "DAS" in the tooltip if you hover over the SDK version in the status bar?

Thanks!

**Comment by Ruzo** [comment]
It is fixed after the last update: Version: 1.69.0-insider / Commit: fbf1cf3832d43088e27837dbb68d24ab65a098c1

I think it had to do with a vscode issue: https://github.com/microsoft/vscode/issues/152395

**Comment by DanTup** [comment]
Ah, good find. I didn't notice you were using Insiders and had assumed it would be my issue as there's an open bug with snippet escaping. Thanks for the update!
