### ISSUE TITLE
undefined name 'debugCheckElevationsEnabled'

### ISSUE THREAD

**Issue by kenaitian** [Dart-Code/Dart-Code#4025]
**Describe the bug**

undefined name 'debugCheckElevationsEnabled'

**To Reproduce**
**1. Add the following import package inside main.dart: https://api.flutter.dev/flutter/rendering/rendering-library.html**
 import 'package:flutter/rendering.dart';

**2. Add the debug flag and some of its functions but only the debugCheckElevationsEnabled which is set to false gets the squiggly red line:**
 Widget build(BuildContext context) {
debugPaintSizeEnabled = true;
debugPaintBaselinesEnabled = false;
debugPaintLayerBordersEnabled = false;
debugRepaintRainbowEnabled = false;
debugRepaintTextRainbowEnabled = false;
# debugCheckElevationsEnabled = false;
debugDisableClipLayers = false;
debugDisablePhysicalShapeLayers = false;
debugDisableOpacityLayers = false;

**3. Flutter run**
**4. Receives this**
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
Error: Invalid package URI 'package:/flutter/rendering.dart':
  Invalid argument (packageUri): Package URIs must not start with a '/': Instance of '_Uri'.
lib/main.dart:60:8: Error: Not found: 'package:/flutter/rendering.dart'
import 'package:/flutter/rendering.dart';
       ^
lib/main.dart:87:5: Error: The setter 'debugPaintSizeEnabled' isn't defined for the class 'MyApp'.
 - 'MyApp' is from 'package:lessimp/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'debugPaintSizeEnabled'.
    debugPaintSizeEnabled = true;
    ^^^^^^^^^^^^^^^^^^^^^
lib/main.dart:88:5: Error: The setter 'debugPaintBaselinesEnabled' isn't defined for the class 'MyApp'.
 - 'MyApp' is from 'package:lessimp/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'debugPaintBaselinesEnabled'.
    debugPaintBaselinesEnabled = true;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/main.dart:89:5: Error: The setter 'debugPaintLayerBordersEnabled' isn't defined for the class 'MyApp'.
 - 'MyApp' is from 'package:lessimp/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'debugPaintLayerBordersEnabled'.
    debugPaintLayerBordersEnabled = true;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/main.dart:90:5: Error: The setter 'debugRepaintRainbowEnabled' isn't defined for the class 'MyApp'.
 - 'MyApp' is from 'package:lessimp/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'debugRepaintRainbowEnabled'.
    debugRepaintRainbowEnabled = true;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/main.dart:91:5: Error: The setter 'debugRepaintTextRainbowEnabled' isn't defined for the class 'MyApp'.
 - 'MyApp' is from 'package:lessimp/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'debugRepaintTextRainbowEnabled'.
    debugRepaintTextRainbowEnabled = true;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/main.dart:92:5: Error: The setter 'debugCheckElevationsEnabled' isn't defined for the class 'MyApp'.
 - 'MyApp' is from 'package:lessimp/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'debugCheckElevationsEnabled'.
    debugCheckElevationsEnabled = false;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/main.dart:93:5: Error: The setter 'debugDisableClipLayers' isn't defined for the class 'MyApp'.
 - 'MyApp' is from 'package:lessimp/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'debugDisableClipLayers'.
    debugDisableClipLayers = false;
    ^^^^^^^^^^^^^^^^^^^^^^
lib/main.dart:94:5: Error: The setter 'debugDisablePhysicalShapeLayers' isn't defined for the class 'MyApp'.
 - 'MyApp' is from 'package:lessimp/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'debugDisablePhysicalShapeLayers'.
    debugDisablePhysicalShapeLayers = false;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/main.dart:95:5: Error: The setter 'debugDisableOpacityLayers' isn't defined for the class 'MyApp'.
 - 'MyApp' is from 'package:lessimp/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'debugDisableOpacityLayers'.
    debugDisableOpacityLayers = false;
    ^^^^^^^^^^^^^^^^^^^^^^^^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:package%3A%2Fflutter%2Frendering.dart; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34:7)
#1      asFileUri (package:vm/kernel_front_end.dart:652:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:792:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (file:///opt/s/w/ir/cache/builder/sdk/pkg/frontend_server/lib/frontend_server.dart:615:9)
<asynchronous suspension>
#4      starter (file:///opt/s/w/ir/cache/builder/sdk/pkg/frontend_server/lib/frontend_server.dart:1433:12)
<asynchronous suspension>
#5      main (file:///opt/s/w/ir/cache/builder/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:10:14)
<asynchronous suspension>

FAILURE: Build failed with an exception.

* Where:
Script '/Users/ken/Development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1156

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/ken/Development/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 59s
Exception: Gradle task assembleDebug failed with exit code 1

**Expected behavior**

No squiggly red line

**Screenshots**

<img width="1279" alt="Screen Shot 2022-06-20 at 11 11 10 PM" src="https://user-images.githubusercontent.com/63857624/174708698-fea831f0-d5d8-4688-a88a-e2a9e104d22f.png">

**Please complete the following information:**
 - Operating System and version: macOS Monterey
 - VS Code version: N/A
 - Android Studio version: Android Studio Chipmunk | 2021.2.1 Patch 1 (Build #AI-212.5712.43.2112.8609683, built on May 18, 2022
 - Dart extension version: 2.17.3
 - Dart/Flutter SDK version: Flutter version 3.0.2
 - Target device (if the issue relates to Flutter debugging): Android SDK built for x86 (mobile) * emulator-5554 * android-x86 * Android 10 (API 29) (emulator)

**Comment by DanTup** [comment]
`debugCheckElevationsEnabled` was removed from Flutter via https://github.com/flutter/flutter/pull/86837 with the comment:

> The flutter runner no longer uses the elevation to determine how to position Flutter layers. This makes Z fighting impossible, and removes the need for a dedicated debug functionality

So I believe you can just delete that line.

Btw, I noticed in your screenshot you're using Android Studio. This repository is for the VS Code extension. The repository for the Android Studio plugin is at https://github.com/flutter/flutter-intellij/issues (although this issue turns out not to be IDE-specific).

Hope this helps!

**Comment by DanTup** [comment]
It also looks like you might have an invalid import from this error:

> Error: Invalid package URI 'package:/flutter/rendering.dart':

There should not be a slash after `package:`.
