### ISSUE TITLE
'_dart.startDebugSession' not found when try to start Debugger for Flutter Mobile App or Dart command line app

### ISSUE THREAD

**Issue by kosiew** [Dart-Code/Dart-Code#403]
![image](https://user-images.githubusercontent.com/29057562/28904576-87e62b3a-783e-11e7-92fe-69666d8812d3.png)

Is there additional set up required in Visual Studio Code ?

**Comment by DanTup** [comment]
There shouldn't be :(

Can you:

- click Help - Show Developer Tools (?) and see if there are any additional errors shown in the console?
- grab a screenshot of the bottom-right corner of status bar
- try opening a .dart file in the editor and then press F5 again

Looks to me like maybe the extension isn't activating correctly.

**Comment by kosiew** [comment]
"maybe the extension isn't activating correctly"

I uninstalled and installed the extension. This fixed the problem.
Thanks

**Comment by DanTup** [comment]
It's great that it's fixed, though I'm not sure why! I suspected it might be throwing an error during activation (which should show up in the developer console) but it's hard to say.

If this comes back, please do let me know (and try the steps above); I'd really like to understand the issue to avoid it happening again (or for others) in future. Thanks!
