### ISSUE TITLE
Flutter dart analyzer disable after few seconds and loading indicator is visible continuously

### ISSUE THREAD

**Issue by imnarendrasingh** [Dart-Code/Dart-Code#4030]

**Comment by DanTup** [comment]
@imnarendrasingh could you provide some more details about the problem, including:

- Version of VS Code, Dart/Flutter extensions and the Flutter SDK
- A screenshot of what you're seeing (which loading indicator?)
- What do you mean by "disables after a few seconds"? What do you see?
- Whether this happens on a newly created project with `flutter create`, or only on a specific project/folder

Thanks!
