### ISSUE TITLE
Go-to-Definition on this/super params does not navigate

### ISSUE THREAD

**Issue by guidezpl** [Dart-Code/Dart-Code#4031]
**Is your feature request related to a problem? Please describe.**
Control+clicking typically goes looking for references (e.g. a constructor parameter). But in cases where it's unused (e.g. `super.key`, Ctrl+click "key"), no feedback is provided.

**Describe the solution you'd like**
Provide some indication that no references were found

**Describe alternatives you've considered**
Could also, in this specific instance, fallback to another reasonable action, such as going to the super constructor param.

https://user-images.githubusercontent.com/6655696/175777830-617bf2a4-5f05-4878-8874-b7b293bcb0c2.mp4

**Comment by DanTup** [comment]
We can't actually provide any feeback here, the interactions are controlled by VS Code. But, wouldn't it make more sense for Ctrl+Click here to jump to the definition of `key` in the super classes constructor?

**Comment by DanTup** [comment]
Turns out the server already did this, but an optimisation in the LSP layer was causing it not to work correctly. Working on a fix at https://dart-review.googlesource.com/c/sdk/+/251108/.

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/d887dc8f2e861e120f464c84a10ba8a8254a82cc. Since it's an SDK change, it'll ship as part of a Dart/Flutter SDK release rather than Dart-Code release.
