### ISSUE TITLE
Flutter analyzer infinitely hangs, even in bare new project

### ISSUE THREAD

**Issue by Omar-Cuenca** [Dart-Code/Dart-Code#4037]
Flutter analyzer infinitely hangs in another project I'm working on.
Created a bare new project with **flutter create dart_test** to check if it happened on a simpler project. And indeed it infinitely hangs as well.

1. In the terminal type **flutter create <project>**
2. Using VSCode command palette, open recently created workspace.

I was expecting the analyzer to run for maybe 20s, so that I could continue working normally.

I've been waiting for like 10 min now on a bare bones project, and it still hasn't finished.
Reading some of the other bugs this seems to be a common issue according to issue #2865 

I've LSP enabled and I'm up to date on the versions. 
I tried changing to a pre-release and previous versions of the extension, unfortunately it didn't work.

Here is a link to the log file, I captured, idk if it is enough though.
[Dart-Code-Log-2022-05-03 10-38-44.txt](https://github.com/Dart-Code/Dart-Code/files/9012115/Dart-Code-Log-2022-05-03.10-38-44.txt)

 - Operating System and version: macOS Monterey version 12.3
 - VS Code version: 1.68.1
 - Dart Code extension: 3.43.20220628
 - Flutter extension: 3.43.20220621 (activated)
 - Dart/Flutter SDK version: 2.10.5

**Comment by Omar-Cuenca** [comment]
Not even a clean install of VSCode and the plugins seems to do the trick

**Comment by DanTup** [comment]
How did you capture the attached log? The requests seem to start with `id:1`, but there are a lot of requests that should occur at startup (like `initialize`) that are missing (the first request is for `textDocument/documentColor`).

Could you try capturing logs using the [`dart.analyzerLogFile` setting](https://dartcode.org/docs/logging/#analyzer) with a test project, and attach that? It should be more complete, including the spawning of the language server which might help understand what's happening.

Please also click Help -> Toggle Developer Tools in VS Code and then check the Console tab to see if there are any warnings/errors printed that might be relevant.

Thanks!

**Comment by DanTup** [comment]
Thanks! There's nothing obvious in the logs, and it turns out the ID normally starts at `0` which explains `1` being used for a non-initialize request.

I can see that analysis is starting and not completing, although it's not clear why. Is it possible you could capture an analysis server instrumentation log (this one is generated by the server and is a bit more detailed) to see if that shows anything more?

https://dartcode.org/docs/logging/#analyzer-instrumentation

Could you also click Help -> Toggle Developer Tools in VS Code and then check the Console tab to see if there are any warnings/errors printed that might be relevant.

**Comment by Omar-Cuenca** [comment]
Here is the other file you asked for
[dart_server_instrumental.log](https://github.com/Dart-Code/Dart-Code/files/9013271/dart_server_instrumental.log)

Also added a screenshot of the console in dev tools.
Unfortunately nothing is showing there.
![Screen Shot 2022-06-29 at 13 46 24](https://user-images.githubusercontent.com/98343802/176513019-b75488db-60e0-4ebc-ac08-783866e15c04.png)

**Comment by DanTup** [comment]
@Omar-Cuenca thanks! This log appears more helpful:

> 1656528365636:Ex:Bad state:: Suspected cycle. [(uri:: dart::nativewrappers, path:: /Users/cuencaomar/.sdk/flutter/bin/cache/pkg/sky_engine/lib/_empty.dart), (uri:: dart::nativewrappers/functions, path:: /Users/cuencaomar/.sdk/flutter/bin/cache/pkg/sky_engine/lib/functions), (uri:: dart::nativewrappers/functions/, path:: /Users/cuencaomar/.sdk/flutter/bin/cache/pkg/sky_engine/lib/functions/), (uri:: dart::nativewrappers/functions/functions, path:: /Users/cuencaomar/.sdk/flutter/bin/cache/pkg/sky_engine/lib/functions/functions), (uri:: dart::nativewrappers/functions/functions/, path:: /Users/cuencaomar/.sdk/flutter/bin/cache/pkg/sky_engine/lib/functions/functions/), (uri:: dart::nativewrappers/functions/functions/functions, path:: /Users/cuencaomar/.sdk/flutter/bin/cache/pkg/sky_engine/lib/functions/functions/functions), (uri:: dart::nativewrappers/functions/functions/functions/, path:: /Users/cuencaomar/.sdk/flutter/bin/cache/pkg/sky_engine/lib/functions/functions/functions/), (uri:: dart::nativewrappers/functions/functions/functions/functions, path:: /Users/cuencaomar/.sdk/flutter/bin/cache/pkg/sky_engine/lib/functions/functions/functions/functions), (uri:: dart::nativewrappers/functions/functions/functions/functions/, path:: /Users/cuencaomar/.sdk/flutter/bin/cache/pkg/sky_engine/lib/functions/functions/functions/functions/), (uri:: dart::nativewrappers/functions/functions/functions/functions/functions, path:: /Users/cuencaomar/.sdk/flutter/bin/cache/pkg/sky_engine/lib/functions/functions/functions/functions/functions), (uri:: dart::nativewrappers/functions/functions/functions/functions/functions/, path:: /Users/cuencaomar/.sdk/flutter/bin/cache/pkg/sky_engine/lib/functions/functions/functions/functions/functions/), (uri:: dart::nativewrappers/functions/functions/functions/functions/functions/functions, path:: /Users/cuencaomar/.sdk/flutter/bin/cache/pkg/sky_engine/lib/functions/functions/functions/functions/functions/functions), (uri:: dart::nativewrappers/functions/functions/functions/functions/functions/functions/, path:: /Users/cuencaomar/.sdk/flutter/bin/cache/pkg/sky_engine/lib/functions/functions/functions/functions/functions/functions/), (uri:: dart::nativewrappers/functions/functions/functions/functions/functions/functions/functions, path:: /Users/cuencaomar/.sdk/flutter/bin/cache/pkg/sky_engine/lib/functions/functions/functions/functions/functions/functions/functions), (uri:: dart::nativewrappers/functions/functions/functions/functions/functions/functions/functions/, path:: /Users/cuencaomar/.sdk/flutter/bin/cache/pkg/sky_engine/lib/functions/functions/functions/functions/functions/functions/functions/), (uri:: dart::nativewrappers/functions/functions/functions/functions/functions/functions/functions/functions, path:: /Users/cuencaomar/.sdk/flutter/bin/cache/pkg/sky_engine/lib/functions/functions/functions/functions/functions/functions/functions/functions), (uri:: dart::nativewrappers/functions/functions/functions/functions/functions/functions/functions/functions/, path:: /Users/cuencaomar/.sdk/flutter/bin/cache/pkg/sky_engine/lib/functions/functions/functions/functions/functions/functions/functions/functions/), (uri:: dart::nativewrappers/functions/functions/functions/functions/functions/functions/functions/functions/functions, path:: /Users/cuencaomar/.sdk/flutter/bin/cache/pkg/sky_engine/lib/functions/functions/functions/functions/functions/functions/functions/functions/functions), (uri:: dart::nativewrappers/functions/functions/functions/functions/functions/functions/functions/functions/functions/, path:: /Users/cuencaomar/.sdk/flutter/bin/cache/pkg/sky_engine/lib/functions/functions/functions/functions/functions/functions/functions/functions/functions/), (uri:: dart::nativewrappers/functions/functions/functions/functions/functions/functions/functions/functions/functions/functions, path:: /Users/cuencaomar/.sdk/flutter/bin/cache/pkg/sky_engine/lib/functions/functions/functions/functions/functions/functions/functions/functions/functions/functions), (uri:: dart::nativewrappers/functions/functions/functions/functions/functions/functions/functions/functions/functions/functions/, path:: /Users/cuencaomar/.sdk/flutter/bin/cache/pkg/sky_engine/lib/functions/functions/functions/functions/functions/functions/functions/functions/functions/functions/), (uri:: dart::nativewrappers/functions/functions/functions/functions/functions/functions/functions/functions/functions/functions/functions, path:: /

@scheglov I'm not sure how to interpret this (the first path in the message `/Users/cuencaomar/.sdk/flutter/bin/cache/pkg/sky_engine/lib/_empty.dart` seems like an empty file - at least in my Flutter SDK) and `/functions` seems to be being appended onto a lot of different paths in the message (such as `dart::nativewrappers/functions/functions/` and `/Users/cuencaomar/.sdk/flutter/bin/cache/pkg/sky_engine/lib/functions/functions/functions/functions/`).

**Comment by scheglov** [comment]
It looks that there is an infinite loop in `/Users/cuencaomar/.sdk/flutter/bin/cache/pkg/sky_engine/lib/functions`, possibly a link that points at itself.

**Comment by DanTup** [comment]
Ah, I thought something in the server was building this path. Makes sense now.

@Omar-Cuenca can you check if you have a symlink at the location above? I don't seem to have any `functions` entry in my `pkg/sky_engine/lib` folder, so if you have one you should be able to just delete it.

**Comment by Omar-Cuenca** [comment]
I'm sorry
but it doesn't seem that directory exists in my files

![image](https://user-images.githubusercontent.com/98343802/176559134-04c67f1f-f115-4684-9048-1e4fa7c63789.png)

**Comment by scheglov** [comment]
Yes, I also don't see it here. Theoretically `dart:nativewrappers` should be `html/dartium/nativewrappers.dart`. Maybe something in there or around? I see from code that throws an exception that it happens in when we go through part files.

**Comment by Omar-Cuenca** [comment]
Tried testing with your newest release. No luck, unfortunately.

Also tried upgrading to flutter 3, and doing a clean install of the flutter sdk.

Unfortunately, nothing has worked so far.

**Comment by DanTup** [comment]
Thanks - I don't see any unusual symlinks in your output, that seems to match mine.

Have you tried creating a fresh project with `flutter create`/**Flutter: New Project** since upgrading to v3? I don't know that it'll make a difference, but perhaps worth a try.

Otherwise, I wonder if @scheglov has any other ideas? The start of the error makes it seem like `pkg/sky_engine/lib/_empty.dart` might be importing `dart:nativewrappers/functions`, but if the file is empty I'm not sure how that would happen.

> [(uri:: dart::nativewrappers, path:: /Users/cuencaomar/.sdk/flutter/bin/cache/pkg/sky_engine/lib/_empty.dart), (uri:: dart::nativewrappers/functions, path:: /Users/cuencaomar/.sdk/flutter/bin/cache/pkg/sky_engine/lib/functions)

**Comment by scheglov** [comment]
I don't know :-(

**Comment by Omar-Cuenca** [comment]
Fixed it!

Basically I had to 💣  nuke 💣 most of the flutter related things in my computer.
I think what might have happened is that I modified something in cache or something. It affected how the extension behaved and that caused it to loop infinitely.

- First I uninstalled the extensions from my VSCode. 
- Then I proceeded to delete every trace of cache in my laptop regarding the extensions. To make it much of a fresh install as possible.
  - Of course I leave a sorta detailed guide of what did I delete in order for the extension to get back to a stable state.
I leave a [history output file](https://github.com/Dart-Code/Dart-Code/files/9075727/history_output.txt), which holds the history logs of what did I delete.

- I rebooted my laptop once I made sure all the deleting was done successfully, for good measure.
- After the laptop rebooted, I reinstalled from scratch flutter
- Ran `flutter doctor` to make sure everything was fine.
- Created a new project `flutter create dart_test`
- Opened VSCode
- Reinstalled the extensions
- Ran perfectly in bare new project.
- Checked on previously created projects, also run perfectly.

I also leave the logs of the extension, post nuke in [this file](https://github.com/Dart-Code/Dart-Code/files/9075733/dart_server_instrumental.log), if anyone want to verify correct behavior.

Maybe it was some migration problem during version switching, maybe it was my fault during editing of a file, idk.
Honestly I'm just glad extension is working perfectly.

Thanks @DanTup & @scheglov for your support!

**Comment by DanTup** [comment]
Glad you sorted it. I'm not really sure what has caused it - the things you deleted included the `~/.dartServer` folder which contains some cached information about analyzed files.. if the issue wasn't in the Flutter SDK `bin/cache` folder then I suspect it might have been `~/.dartServer` (although I'm not super familiar with the implementation of what's in there).

If you happen to see the issue again, please do post back.
