### ISSUE TITLE
Weird autocomplete list (text overlap)

### ISSUE THREAD

**Issue by gnudles** [Dart-Code/Dart-Code#4040]
Hi, using version v3.42.1
See for yourself...
![Screenshot from 2022-06-30 20-40-21](https://user-images.githubusercontent.com/12647462/176742988-5358e243-df2f-46c7-925a-dddca76f0d31.png)

**Comment by DanTup** [comment]
This looks like a VS Code issue. All rendering of this list is handled by VS Code (we just give it a list of completion items). There's nothing the extension can do that would allow the items to be overlapped like that.

Have you installed any extensions that might mess with VS Code's internal CSS? (I've seen a few extensions that do this recently, and it seems dangerous to me).

If not, please file an issue at https://github.com/microsoft/vscode and post the link back here in case anyone else has the same issue.

Thanks!

**Comment by gnudles** [comment]
Thanks, I disabled many extensions at once, and it seems to be fixed. I wonder which one was the culprit.

**Comment by DanTup** [comment]
Odd. If an extension modified the CSS, I would've thought disabling it would still leave the modifications.

You can use VS Code's "extension bisect" to track down which extensions cause issues:

https://code.visualstudio.com/blogs/2021/02/16/extension-bisect

It enables/disables them and asks you to test different combinations (a binary search) until it finds the culprit.

**Comment by gnudles** [comment]
Wow, I enabled them all again, but now things looks Ok.
When the bug occurred I could see this phenomena again and again.
I was triggered when I created a new folder, and unlike I am used to, I did the dart imports with relative path to the folder above, not as usual that I import by absolute path. Maybe the reload did it? I will keep an eye on that, and if I see it again, I will activate the bisect.
