### ISSUE TITLE
Stless snippet importing foundations libraries instead of material package in VSCode

### ISSUE THREAD

**Issue by lucas404x** [Dart-Code/Dart-Code#4043]
**Describe the bug**
In early versions of this extension, the "stless" snippet created the widget class with material package. Today it's importing from foundations libraries, what doesn't make any sense because the analyzer itself complains about it

**To Reproduce**
1. Create a empty file.dart
2. Type "stless" and select the snippet suggestion

**Expected behavior**
Create a widget class with dependencies from material package.

**Screenshots**
![image](https://user-images.githubusercontent.com/42918677/176946219-43d0e49c-2535-46fa-b548-c9160f99d911.png)

**flutter doctor -v**
[✓] Flutter (Channel stable, 3.0.2, on Microsoft Windows [Version 10.0.22000.739], locale en-US)
    • Flutter version 3.0.2 at C:\Users\Desktop\fvm\versions\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (3 weeks ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at C:\Users\Desktop\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.15)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32510.428
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.68.1)
    • VS Code at C:\Users\Desktop\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.42.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.739]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 102.0.5005.115
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 103.0.1264.37

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by DanTup** [comment]
Thanks! There's an open issue about this at https://github.com/dart-lang/sdk/issues/49081, it's something that needs solving in the analysis server.
