### ISSUE TITLE
Slowness in autocomplete/lint report in dart/flutter extension in VS code(MAC)

### ISSUE THREAD

**Issue by vishnuguhan** [Dart-Code/Dart-Code#4044]
Hello guys,

I am using flutter&dart extension in VSCode version 1.68 in macOS Monterey ,where facing the trouble of much slowness in autocomplete/lint etc. so when I type something, it makes me wait for few seconds to populate lint and autocomplete suggestions.

**Comment by DanTup** [comment]
Does this occur for a brand new project created with **Flutter: New Project**, or only for some specific projects?

Can you confirm your:

- Version of VS Code
- Version of the Dart and Flutter extensions for VS Code
- Version of the Dart/Flutter SDK

Could you also post the full output of running `code --status` in a terminal while VS Code is open with a project that shows this behaviour.

And finally, could you capture a log by opening your project and waiting for initial analysis to complete. Please do this on a freshly-created project because the log will contain some of your source code:

- Run the **Dart: Capture Analysis Logs** command to start logging
- Reproduce the issue (by typing some characters and waiting for the completion/analysis results)
- Click **Cancel** on the logging notification to stop logging and open the log file
- Attach the log here (or paste into a [gist](https://gist.github.com/) and paste the link here)

If you're able to capture a recording showing the issue, that could be useful to.

Thanks!

**Comment by vishnuguhan** [comment]
@DanTup, have attached the dart analysis log, for which I just created a new flutter application and edited a class name and waited for lint to show error. There was a delay. 

And also have attached code --status logs.

VS code info as follows : 

Version: 1.68.1 (Universal)
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:52:13.188Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 21.5.0

[code_status.txt](https://github.com/Dart-Code/Dart-Code/files/9053996/code_status.txt)
[dart_log.txt](https://github.com/Dart-Code/Dart-Code/files/9053997/dart_log.txt)

Thanks !

**Comment by vishnuguhan** [comment]
Dart SDK version: 2.16.2 
Flutter 2.10.5 
Dart extension v3.44.0
Flutter extension v3.44.0

Hoping this information helps.

**Comment by DanTup** [comment]
> Memory (System):  8.00GB (0.07GB free)

I'm not certain, but the performance issues may be related to having no free RAM. Please try running Activity Monitor and check the Memory tab to see if you have any applications consuming a lot of memory that you could close, and see if that makes a difference:

![Screenshot 2022-07-06 at 12 30 21](https://user-images.githubusercontent.com/1078012/177540534-c72df165-7af5-4f8d-bf48-7e7c58b9a16e.png)

**Comment by vishnuguhan** [comment]
Hi @DanTup , 

Yeah understood. But In most cases, only VS Code(flutter) and Safari are kept open. Could any thing be done from plugin side.

<img width="934" alt="Screenshot 2022-07-13 at 12 12 45 PM" src="https://user-images.githubusercontent.com/20523733/178668212-f996b974-78dd-4eac-b25c-a18dec6bb4c3.png">

Thanks.

**Comment by DanTup** [comment]
I don't think there's really a lot we can do if the system is running low on memory. The VS Code extension itself doesn't use much memory and the Dart server in this screenshot is using around 600MB, which doesn't seem particularly high.

Just to confirm it's a memory problem, if you close Safari (and all the other websites listed there, like sprints.zoho, github, google, stackoverflow, developer.android) and confirm you have some free memory, is the performance better?

**Comment by vishnuguhan** [comment]
@DanTup , 

Even immediately after restarting and only VS Code is opened, facing the same delay. I am using Windows PC as well, where I am not facing any such. 

And Under Activity Monitor, Memory pressure is green.

**Comment by vishnuguhan** [comment]
Windows logs.
[code_wind.log](https://github.com/Dart-Code/Dart-Code/files/9140037/code_wind.log)
[Dart-code-Log.txt](https://github.com/Dart-Code/Dart-Code/files/9140038/Dart-code-Log.txt)

**Comment by vishnuguhan** [comment]
Mac

[dart-code-log-mac.txt](https://github.com/Dart-Code/Dart-Code/files/9140047/dart-code-log-mac.txt)
[status.log](https://github.com/Dart-Code/Dart-Code/files/9140062/status.log)

**Comment by vishnuguhan** [comment]
@DanTup,

Have attached both systems logs. :) 

Thanks.

**Comment by DanTup** [comment]
@vishnuguhan can you confirm exactly which operations are slow? In the Windows analysis server log I found two calls for code completion, and both are 1 second or less (and both happened immediately after the file modification was received by the server):

```
[3:44:27 pm] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":62,"method":"textDocument/completion
[3:44:28 pm] [Analyzer] [Info] <== {"id":62,"jsonrpc":"2.0","result

[3:44:30 pm] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":76,"method":"textDocument/completion
[3:44:31 pm] [Analyzer] [Info] <== {"id":76,"jsonrpc":"2.0","result
```

**Comment by DanTup** [comment]
Also - it looks like you may have two copies of the Dart language server running ("app" and frontend"). Do you have these open in separate VS Code windows? You may find the performance is better if you have just a single window (you can add multiple folders using File -> Add Folder to Workspace). It will almost half the resources being used (currently you have two language servers, two Flutter device daemons, two copies of DevTools etc. all running).

**Comment by vishnuguhan** [comment]
Yeah, In Windows, I am not facing any trouble, code completion is immediately responding And in Mac, it does not respond in such way. As you mentioned, I closed the other project but that is not making any difference.

**Comment by DanTup** [comment]
Sorry, I misunderstood and thought you had the same on Windows.

I think the issue is likely due to the lack of free RAM on the Mac. In your screenshot, a lot of memory was used by Safari (and some websites like google, stackoverflow, developer.android, sprints.zoho). If you close _all_ of these and run `code --status` to confirm you have more free memory, is the performance any better?

**Comment by vishnuguhan** [comment]
@DanTup ,

Being 0.50GB free after quitting safari and other applications, Still behavior is there. Just to clarify, The issue is about the code completion response and linting.

Even if problem can't be resolved, curious to know what's the reason behind this, whether Dart/MAC M1.

Thanks.

**Comment by DanTup** [comment]
@vishnuguhan are you able to capture the same two logs from above (`code --status` and the analyzer log) when you have 0.5GB free RAM? Can you also confirm _a single specific_ operation that was slow while capturing the log file (for example, if completion, where you invoked completion and approximately how long it took). If you're able to make a screen recording ([you can do this with built-in Quicktime on macOS](https://support.apple.com/en-gb/guide/quicktime-player/qtp97b08e666/mac)) that may help too.

In your last Mac logs above, I only see one completion request and the recorded timings show less than 1 second, so I'm not yet sure where the time is going. If we can figure out whether the code is being spent on the client or the server, we can figure out how to narrow it down.

Thanks!
