### ISSUE TITLE
flutter is not run on vscode dont no why 

### ISSUE THREAD

**Issue by AFAQ5553** [Dart-Code/Dart-Code#4048]
- Issue Type: `Bug`
- Extension Name: `dart-code`
- Extension Version: `3.44.0`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.68.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by DanTup** [comment]
This appear to be the same as #4047. Please don't open multiple issues for the same problem, and please include a detailed description of the issue.
