### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Nialixus** [Dart-Code/Dart-Code#4049]
- Issue Type: `Bug`
- Extension Name: `dart-code`
- Extension Version: `3.44.0`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.68.1`

when i check 'Show Running Extension' in vscode, Dart is `Unresponsive`, and i can't even load Intellisense smoothly.

**Comment by DanTup** [comment]
> ⚠️ We have written the needed data into your clipboard. Please paste! ⚠️

Is there additional information in your clipboard you can paste?

**Comment by Nialixus** [comment]
sorry but there is none. I didn't get any error issue, only slow performance on displaying Intellisense, the tooltip shows 'loading' all the time, and i can't even use Ctrl + Click to navigate through dart variable

**Comment by Nialixus** [comment]
here, kind sir

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 752,
		"activateCallTime": 84,
		"activateResolvedTime": 714,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "Dart-Code.dart-code",
				"_lower": "dart-code.dart-code"
			},
			"activationEvent": "onLanguage:dart"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

this time, it doesn't show `unresponsive` tag, but the performance is slow as yesterday

**Comment by DanTup** [comment]
Thanks - unfortunately that doesn't include much useful.

Could you post the full output from running `code --status` in a terminal window _while VS Code is open_ with the slow project?

**Comment by DanTup** [comment]
Either is fine. If you think the issue will re-occur we can leave this open, and if there's no update in 30 days the bot will comment on it (and later close it). If you think it was just a one-off and may be completely resolved, feel free to close it.

Ofc, it can always be re-opened it closed and the issue comes back.
