### ISSUE TITLE
select debug device

### ISSUE THREAD

**Issue by zantoku** [Dart-Code/Dart-Code#405]
I haven't been able to figure out how to select the device on which to run/debug the app. Is there an option I can set in the launch.json?

**Comment by DanTup** [comment]
If you click on the device in the status bar it should open a down at the top of the even to change it (same as changing language/indent settings/etc).

It's only clickable when more than one device is connected.

Let me know if this doesn't seem to work!

**Comment by zantoku** [comment]
That works! Sorry, I didn't think to click there, feeling a little stupid now. :) Thanks!

**Comment by DanTup** [comment]
No probs! I think it's slightly weird too, bit it seems to match the other things in Code so I hope it's something most people will be familiar with (out at least appreciate the consistency). I did also think about allowing it to be invoked via a palette command, but can't remember if I did that yet!

**Comment by zantoku** [comment]
I'm new to VS Code, but yes, it does seem consistent. With Dart-Code, I think I already prefer it over IntelliJ as a Flutter IDE - it seems a lot more focused! Great work.

**Comment by DanTup** [comment]
Thanks; glad it's working for you. Please do keep sending feedback if you have any issues or ideas!
