### ISSUE TITLE
Extract method refactors widget with async callback incorrectly

### ISSUE THREAD

**Issue by omarelb** [Dart-Code/Dart-Code#4053]
**Describe the bug**
In a build function, when calling _extract method_ on a widget such as a button with an asynchronous callback (e.g. async `onPressed` method), the newly created method itself is marked as an `async` function, which is incorrect (at least in all the cases that I've used it). While the callback is asynchronous, the function that is returning the widget should not be.  

**To Reproduce**
1. Create a widget such as a button with an asynchronous callback. For example:
```dart
ListTile(
  title: "Hi",
  suffixIcon: IconButton(
    onPressed: () async {
       await asyncFunction()
    },
    icon: Icon(Icons.arrow_forward),
  )
)
```

2. Place your cursor on `IconButton`, bring up the context menu, press `extract method`, and name the new function.

3. The `IconButton` will have been replaced by your new method, but it has an `await` keyword before it that should not be there.

**Expected behavior**
The new function is added in place of the `IconButton` without an `await` in front of the function call. The new function does not return a `Future<Widget>` but just a `Widget`. The new method is not an `async` method.

**Please complete the following information:**
 - Operating System and version: macOS Monterey 12.2, M1 Chip
 - VS Code version: 1.68.1
 - Dart extension version: v3.44.0
 - Dart/Flutter SDK version: Flutter 2.10.4, Dart 2.16.2

**Comment by DanTup** [comment]
Thanks, I can repro this. A smaller example without the Flutter dependency is:

```dart
void f() {
  g(() {
    return Future.value(null);
  });
  g(() async {
    await null;
  });
}

void g(Future<void> Function() func) {}
```

Extracting the first call to `g` is fine, but the second one gets the unwanted `await`.

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/97fa3ca9fc695207f82c352ada053a298fcb933f. The fix is in the Dart SDK, so will show up in a Future SDK release (and not a VS Code extension update).
