### ISSUE TITLE
VSCode Extension Error : Activating extension 'Dart-Code.dart-code' failed: spawn EPERM.

### ISSUE THREAD

**Issue by raonlast** [Dart-Code/Dart-Code#4054]
At some point, the flutter extension started to fail in VSCode. Due to this error, all operations related to flutter through VSCode are not progressing. It seems to be a matter of authority, but we still haven't found a solution. I would appreciate it if you could solve the error.

![image](https://user-images.githubusercontent.com/57239678/178384520-755d5b34-dc26-4005-9fc3-b023d0bdc7d1.png)

**Comment by DanTup** [comment]
This seems like a permissions issue. I would guess that something that the Dart extension is trying to spawn (like `dart` or `flutter`) is failing due to permissions.

It might be useful to configure an extension log (https://dartcode.org/docs/logging/#extension) to see if it logs what's being spawned just before this fails.

**Comment by raonlast** [comment]
> This seems like a permissions issue. I would guess that something that the Dart extension is trying to spawn (like `dart` or `flutter`) is failing due to permissions.
> 
> It might be useful to configure an extension log (https://dartcode.org/docs/logging/#extension) to see if it logs what's being spawned just before this fails.

First of all, thank you for your help!
I sent an email referring to the link you told me, and I am waiting for your reply.
Do you know any solutions related to VSCode's authority? Currently, I deleted it, downloaded it again, and tried to run it as an administrator, but it has not been resolved.

**Comment by iiiok** [comment]
My case: I install the VC-code in /download/ path (Mac).
1. try to update you VS-code, if it returns permission error,
maybe that is the case.
2. re-run the vscode, the flutter extension is back~~
