### ISSUE TITLE
Multiline comment is getting separated on empty line

### ISSUE THREAD

**Issue by yeasin50** [Dart-Code/Dart-Code#4065]
Multiline comment breaking into several parts based on empty line.

**To Reproduce**
1. Create a dart file and paste this code.
```
class Test extends StatefulWidget {
  const Test({Key? key}) : super(key: key);

  @override
  State<Test> createState() => _TestState();
}

class _TestState extends State<Test> {
  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```
2. Select all code from `class` to the end.
3. Press `ctrl+/` 

**Expected behavior**
I think it would be better all lines get commented on single section and can be use `v` or `>` to close and open all comment section. 

**Screenshots**
![Screenrecorder-2022-07-20-11-06-02-40_1](https://user-images.githubusercontent.com/46500228/180195924-5379bc81-4882-4982-995e-94ea08774cd4.gif)

**Please complete the following information:**
 - Operating System and version: Windows 10
 - VS Code version: 1.69.2
 - Dart extension version: v3.44.0
 - Dart/Flutter SDK version: Flutter 3.0.1/Dart 2.17.1

**Comment by DanTup** [comment]
This functionality is handled by VS Code, but there's an existing setting that you can disable to make it work how you'd like:

<img width="934" alt="Screenshot 2022-07-21 at 14 33 53" src="https://user-images.githubusercontent.com/1078012/180226520-c02eb1c5-e781-4cb8-9fae-da9127354fef.png">

Ticked is the default behaviour, unticked will add the comment markers to the blank lines too.
