### ISSUE TITLE
Fix all on save setting does not work

### ISSUE THREAD

**Issue by CengizhanParlak** [Dart-Code/Dart-Code#4069]
**Describe the bug**
`source.fixAll` option does not fix any (fixable) linter warnings in Flutter projects.

My settings.json file has this key-value pair for dart:
```json
"editor.codeActionsOnSave": {
      "source.fixAll": true,
      "source.organizeImports": true
},
```

Although the `source.organizeImports` setting works as expected, I couldn't seem to make `source.fixAll` work. For instance, I witnessed that it adds a _const_ modifier to widgets and variables if they conform to the const requirements.

If I run the `dart fix --apply` command from the console, it works as expected so I was wondering if it even runs? Are there any ways to check which commands are working in VSCode after saving a file? Maybe that can produce some insights on the bug.

**To Reproduce**
\-

**Expected behavior**
`"source.fixAll": true,` option should fix auto-fixable issues on file save.

**Screenshots**
\-

**Please complete the following information:**
 - Operating System and version: 
```txt
Edition Windows 10 Pro 21H2
OS build 19044.1826
```
 - VS Code version: 1.69.2 (user setup)
 - Dart extension version: v3.44.0
 - Dart/Flutter SDK version:
 ```txt
Flutter 3.0.0 • channel stable •
https://github.com/flutter/flutter.git
Framework • revision ee4e09cce0 (3 months ago) • 2022-05-09
16:45:18 -0700
Engine • revision d1b9a6938a
Tools • Dart 2.17.0 • DevTools 2.12.2
```
 - Target device (if the issue relates to Flutter debugging): \-

**Comment by DanTup** [comment]
I tried to repro with these steps:

- Checkout Flutter stable (3.0.5)
- Create a new project with **Flutter: New Project**
- Deleted the `const` keyword in `home: MyHomePage(title: 'Flutter Demo Home Page'),`
- Opened setting (**Preferences: Open Workspace Settings (JSON)**) and pasted in your settings
- Pressed save

This correctly re-inserted the `const` keyword. If you perform the same steps, does it work?

Things that may help to test:

- Does the **Fix All** command from the command palette work?
- Are you testing with `const` or something different? (not all fixes can currently be applied in batch, but since you specifically mentioned it working from `dart fix` I presume you're testing with one that is - `dart fix` and `fix all` should perform the same fixes)
- Run the **Dart: Capture Analysis Server Logs** command before saving, then click **Cancel** to stop logging and open the log

The log file should include:

```
// A 'textDocument/codeAction' request from the client to the server
[10:50:51 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":28,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///Users/danny/Desktop/dart_samples/dartcode_flutter_4096/lib/main.dart"},"range":{"start":{"line":0,"character":0},"end":{"line":115,"character":0}},"context":{"diagnostics":[{"range":{"start":{"line":26,"character":12},"end":{"line":26,"character":55}},"message":"Prefer const with constant constructors.","code":"prefer_const_constructors","codeDescription":{"href":"file:///linter/lints/prefer_const_constructors.html"},"severity":3,"source":"dart"}],"only":["source.fixAll"],"triggerKind":2}},"clientRequestTime":1658742651321}

// A response from the server that includes the "Fix All" action
[10:50:51 AM] [Analyzer] [Info] <== {"id":28,"jsonrpc":"2.0","result":[{"title":"Fix All","kind":"source.fixAll","command":{"title":"Fix All","command":"edit.fixAll","arguments":["/Users/danny/Desktop/dart_samples/dartcode_flutter_4096/lib/main.dart"]}}]}

// A request from the client to execute the 'edit.fixAll' command that was attached to the command:
[10:50:51 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":29,"method":"workspace/executeCommand","params":{"command":"edit.fixAll","arguments":["/Users/danny/Desktop/dart_samples/dartcode_flutter_4096/lib/main.dart"]},"clientRequestTime":1658742651334}

// A reverse request from the server to the client asking it to apply edits that fix the issues:
[10:50:51 AM] [Analyzer] [Info] <== {"id":8,"method":"workspace/applyEdit","params":{"label":"Fix All","edit":{"documentChanges":[{"textDocument":{"version":3,"uri":"file:///Users/danny/Desktop/dart_samples/dartcode_flutter_4096/lib/main.dart"},"edits":[{"range":{"start":{"line":26,"character":12},"end":{"line":26,"character":12}},"newText":"const "}]}]}},"jsonrpc":"2.0"}
```

**Comment by CengizhanParlak** [comment]
Hey again, sorry for the late reply.

I've tried the same steps as you:
- Checkout Flutter stable (3.0.5)
- Create a new project with Flutter: New Project
- Deleted the const keyword in home: MyHomePage(title: 'Flutter Demo Home Page'),
- Opened setting (Preferences: Open Workspace Settings (JSON)) and added my two settings
- Pressed save

It didn't work again. 

But then, I disabled all the extensions except Flutter & Dart to see if problem occurred from something else, but there was no luck again. Finally, I deleted all the setting keys from `settings.json` and added only those 2 options; luckily, it worked! The problem was the `useLsp` setting of `dart` key, specifically because it was set to `false`. Commenting out or setting it to true fixes the problem in 3.0.0

Thanks a ton!

**Comment by DanTup** [comment]
> The problem was the `useLsp` setting of dart key, specifically because it was set to `false`. 

Do you happen to know why you had disabled LSP? LSP is what everyone should be using now (the ability to disable it is for compatibility and troubleshooting, and will eventually go away - it's already not receiving new features that LSP is). If there are things that don't work correctly in LSP that are causing people to disable it, I'd very much like to get to the bottom of them.

Thanks!

**Comment by CengizhanParlak** [comment]
I am currently using a lower version of Flutter SDK on a project and LSP option—to be more accurate: it being set to true was slowing down suggestions/go-to definition actions. So, I disabled it with also `autoImportCompletions` set to false as you described [here](https://github.com/Dart-Code/Dart-Code/issues/3102#issuecomment-813576808)

**Comment by DanTup** [comment]
> I am currently using a lower version of Flutter SDK (2.0.1) 

Ah, got it. Thanks for the info!

**Comment by CengizhanParlak** [comment]
Glad I could help!

**Comment by Uuttssaavv** [comment]
@CengizhanParlak 
Did you get any solution for this?
I am facing the same issue.
Flutter 3.10.5 
Dart 3.0.5

**Comment by DanTup** [comment]
@Uuttssaavv what is the issue you're having? If the issue is that Fix-All-on-Save doesn't work when using the legacy protocol, the fix is to disable the legacy protocol. If you're having a different problem, please file a new issue with details. Thanks!

**Comment by Uuttssaavv** [comment]
The issue was `Fix-All-on-Save` was not working. I disabled the `dart.useLegacyAnalyzerProtocol` and it worked for me
Thank you @DanTup 
:)

**Comment by DanTup** [comment]
@Uuttssaavv do you recall the reason why you had switched to the legacy protocol? If there are things that do not work correctly unless using the legacy protocol, please do open additional issues. The legacy protocol will be removed in a future update, so it's important if there are issues with the new protocol that they are resolved. Thanks!

**Comment by Uuttssaavv** [comment]
Sure. If I find any issues then I will surely report.
Thanks @DanTup for your response
