### ISSUE TITLE
Can I exclude the Flutter source files from the "Go to Symbol in Workspace" search?

### ISSUE THREAD

**Issue by avicularian** [Dart-Code/Dart-Code#4072]
Hiya,

I love the extension, but I find it hard to navigate in my project because when I use the VSCode feature "Go to Symbol in Workspace", all Flutter source directories are searched in addition to my project files.

![too many shapes](https://user-images.githubusercontent.com/108077970/180993741-3a82cb3b-4650-478d-ad3e-7c68fa328cdd.png)

I want to use this feature to jump around quickly within my project. But if I look for a symbol name that clashes with an extant symbol in the Flutter source—or if I try to use the fuzzy search in any way—then the search takes an excruciatingly long time to finish, and simply returns a massive list of symbols from the Flutter source.

There are other complaints about the Go to Symbol search being slow, but this is not a duplicate. I know for sure that searching would be quick if only my tiny little project folder was getting indexed.

I've **never added the Flutter source files to my project**, so I can't figure out how VSCode is even indexing them. Someone told me this was a "feature" added by the Dart/Flutter extension.

I want to use this editor functionality to jump exclusively to symbols in my own project, not outside of it, not in the Flutter source code, and (hell, no!) not in `node_modules` (which I've also dealt with)—all the other devs I've consulted with have agreed with me.

By the way, if this comment thread evolves, **I'd like to cut all the Dart-Code developers some slack**, because the ability to exclude folders from the VSCode project search has been requested many years ago, but been continually pushed back! (and seemingly, due to the sheer beaucratic inertia of making any kind of change to old code). It seems fair, in the meantime, to request a boolean option (or something similar) in the Dart-Code settings to make up for it.

## Describe the solution you'd like 

The ability to write `"dart.indexFlutterSourceFilesInGotos": false` in my settings.json.

## Describe alternatives you've considered
Maybe there's a way to do this already—in which case, please try and give a detailed answer so future reader of this thread is left hanging, and let it stand as a beacon to other lost users in the Google search results!

## Additional context
I remember many, many years ago I made the leap to using Sublime Text specifically because of the wonderful project navigation features. Now VSCode has emerged as a successor, but many of the functionalities that ought to be available seem to have regressed. At least the language server capabilities have come on leaps and bounds, for which I'm grateful!

**Comment by DanTup** [comment]
> The ability to write `"dart.indexFlutterSourceFilesInGotos": false` in my settings.json.

Is it specifically Flutter you're trying to exclude, or would a generally setting that searched "only my open projects" be sufficient? It feels slightly odd to me to _specifically_ exclude Flutter (but not other packages, or the Dart SDK), but restricting it to your own code feels like a more natural boundary.

**Comment by DanTup** [comment]
Assuming the suggestion above is sufficient, this will be available as part of an upcoming setting added for https://github.com/Dart-Code/Dart-Code/issues/1903. Subscribe there for updates on when this is implemented.

**Comment by avicularian** [comment]
Thanks, Dan.

I didn't reply because I had a rather busy period of work and I seemed to be locked out of the comment process.

The new setting / feature is absolutely terrific! And you didn't even have to reply to this issue—thanks for doing so.

Now, if only the VSCode devs themselves could show the same level of care about their product!

**Comment by liugangnhm** [comment]
i didn't see any changes in latest version

**Comment by DanTup** [comment]
@liugangnhm there haven't been any changes recently, this is an old issue. The resolution here was to add a new setting:

![Image](https://github.com/user-attachments/assets/90640067-04bc-45b8-8aa8-06f212694e01)

However the default did not change, so you'll need to untick this if you don't want them included.
