### ISSUE TITLE
VSCode auto-imports for widget snippets include src files

### ISSUE THREAD

**Issue by bryanoltman** [Dart-Code/Dart-Code#4075]
## Details

When using the `StatefulWidget`/`StatelessWidget`/`Widget with Animation Controller` snippets provided by the VS Code Flutter plugin, imports from `package:flutter/src/widgets` are used instead of `package:flutter/material.dart` or `package:flutter/widgets.dart`.

## To Reproduce

1. Create a new Dart file in VS Code.
2. Type 's' to show the Flutter Widget snippets provided by the plugin.
3. Select any one of the Flutter Widget snippets.

### Expected Behavior

Non-src files (material.dart or widgets.dart) are added as imports.

### Actual Behavior

Files from the src directory (`package:flutter/src/widgets/container.dart`, `package:flutter/src/widgets/framework.dart`) are added as imports.

 - Operating System and version: macOS 12.5
 - VS Code version: 1.69.2
 - Dart extension version: v3.44.0
 - Dart/Flutter SDK version: 
   - Dart: 2.19.0
   - Flutter: 3.1.0
 - Target device (if the issue relates to Flutter debugging): N/A

**Comment by DanTup** [comment]
Thanks for the report! This is a known issue being tracked at https://github.com/dart-lang/sdk/issues/49081. We recently switched snippets to coming from the analysis server which supports automatically adding imports, but right now it doesn't know how to compute the best import to use, and just uses the one that actually defines the types.
