### ISSUE TITLE
Plans for extracting scripts for dart local dev server sdk (go monorepo?)

### ISSUE THREAD

**Issue by softmarshmallow** [Dart-Code/Dart-Code#4085]
This project contains tons of capabilities for dart & flutter dev with vscode, yet lots of scripts seems modular and can run independently. In fact, I was trying to extract some scripts to build my own local dev server which connects to my own web IDE, yet  I found this was very hard to since lots of entry files are dedicated to vscode env.

I'm curious if you guys have plans for extracting some features as packages so others can utilize it?
😭

My case is for..
Run flutter app on web via local dev server. (I'm currently using [dart-services](https://www.npmjs.com/package/dart-services) powered by dartpad, but this does not utilize the hot-reloading and layout debugger, ... and so on.

**Comment by DanTup** [comment]
Can you be more specific with what you're building and what you're trying to reuse?

Most of the code here is quite specific to VS Code APIs, so it's not easily reusable outside of VS Code. However if you're building your own IDE, you can already use a lot of the same tools that this extension uses:

- The [LSP Server](https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/tool/lsp_spec/README.md) provides all of the language support
- The DAP debug adapters ([dart](https://github.com/dart-lang/sdk/blob/master/pkg/dds/tool/dap/README.md)/[flutter](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/debug_adapters/README.md)) provide debugging capabilities
- Flutter has a [device daemon](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/doc/daemon.md) for listing/launching emulators and devices
- `package:test` has [a JSON mode](https://github.com/dart-lang/test/blob/master/pkgs/test/doc/json_reporter.md) for running tests and receiving results

If there is code here that would be beneficial to other tools/IDEs, it would definitely be nice to extract it into something they can use - but generally I try to avoid having much of that. The purpose of things like LSP and DAP is to try to reduce the amount of IDE-specific work that needs doing and push it into shared tooling (like the Dart analysis server and `flutter` tool).

**Comment by DanTup** [comment]
> My case is for..
> Run flutter app on web via local dev server. (I'm currently using [dart-services](https://www.npmjs.com/package/dart-services) powered by dartpad, but this does not utilize the hot-reloading and layout debugger, ... and so on.

It's not clear what sort of UI you have, but for very simple uses you could probably just run `flutter run --machine -d web-server` and then interact with the daemon protocol to send reloads. If you have something more complex (like a full UI for debugging/breakpoints) then using the Flutter DAP adapter would probably make sense (although, to work with Web you'd also need to have the Dart Debug extension).

**Comment by softmarshmallow** [comment]
> 

Thanks for such quick response. I used `flutter run --machine -d web-server` for the prototype but it seems it only supports re-start rather than re-load. and also it should be done via sending `r` key event to the child process. 

perhaps I'm wrong about the key event part. but found out that this project somehow handles the reloading part elegantly. spent some hours to understand the full architecture and all, frankly it's quite overwhelming for me.. 🥲

Thank you!

**Comment by DanTup** [comment]
> Thanks for such quick response. I used `flutter run --machine -d web-server` for the prototype but it seems it only supports re-start rather than re-load. and also it should be done via sending r key event to the child process.

It definitely supports both, this is what VS Code is using :)

It's done by sending an `app.restart` message over stdin:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/doc/daemon.md#apprestart

You set `fullRestart: false` if you just want a hot reload.

FWIW, you can capture the traffic VS Code sends to `flutter run` (and more) using the **Dart: Capture Logs** commands in VS Code. That command lets you choose what to log, but you can also use **Dart: capture Debugging Logs** to get a pre-filtered set of the debugging traffic. More info about logging is at https://dartcode.org/docs/logging/#capture-logs-commands.

> perhaps I'm wrong about the key event part. but found out that this project somehow handles the reloading part elegantly.

We do have some additional handling like hot-reload-on-save, but it's quite specific to the VS Code APIs so not really something that can be extracted (but it's also not much code).

If there's anything specific you're trying to do that seems like it would require rewriting a load of code that's here, feel free to post questions here and I'm happy to answer. Although there's a lot of code in this repo, we're currently supporting the analysis server without LSP, and our own implementations of the DAPs (moving them to the SDK is still a work in progress). A lot of this code could be deleted in the future (as the general trend is to move more into the shared Dart/Flutter SDKs).

**Comment by softmarshmallow** [comment]
Ah. Thank you 🙏 

> It's done by sending an app.restart message over stdin:

This must be what i was looking for. Thanks again ;)
