### ISSUE TITLE
Running "flutter run -t <path_to_test>" from launch.json fails with "when using --start-paused, you must specify a single test file to run" after first run

### ISSUE THREAD

**Issue by antholeole** [Dart-Code/Dart-Code#4086]
**Describe the bug**
I have a `launch.json` that's running a test on the device (because I want to see what's going on). When I run it the first time, it runs as expected. When I stop the run, it fails with: 

```
When using --start-paused, you must specify a single test file to run.
Exited (1)
```

**To Reproduce**
1. Create a `launch.json` and a sample dart app.
2. add the following configuration:

```json
    {
        "name": "Flutter (test)",
        "type": "dart",
        "request": "launch",
        "args": ["run", "-t", "test/counter_test.dart"]
    }
```
3. Launch it and let the test run (the test must run. If you exit during compilation it works as intended)
4. Stop the debugger and then relaunch. The launch should fail with the error I previously mentioned.

**Expected behavior**
I would expect launching the debugger has idempotence

**Please complete the following information:**
 - Operating System and version: macOS Monetery v12.5 (gMac)
 - VS Code version: 1.69.2
 - Dart extension version: v3.46.0 for the flutter plugin, v3.46.1 for dart
 - Dart/Flutter SDK version: v2.17.3 for dart, flutter master
 - Target device (if the issue relates to Flutter debugging): iOS simulator

**Comment by antholeole** [comment]
It actually seems this doesn't repro on a basic app. Let me try to diff what's causing it in my real app vs why it works fine in the counter app. I have a rather complex setup (multiroot workspace) so this may take sometime. Closing for now

**Comment by DanTup** [comment]
>  "args": ["run", "-t", "test/counter_test.dart"]

FWIW, it's not really valid to put `run` in `args` like this. The tool will be invoked with `run` or `test` already included, so this will result in `flutter run run` or `flutter test run`.

You may want to look at the `runTestsOnDevice` setting (or using Flutter's integration tests, which also run on a device).

**Comment by antholeole** [comment]
Ah thanks for pointing that out! Whatever the problem was, it got fixed by setting a proper launch config.

```json
    {
        "name": "Flutter (test)",
        "type": "dart",
        "request": "launch",
        "cwd": "/Users/oleina/Projects/bug",
        "program": "test/blah_test.dart",
        "runTestsOnDevice": true,
    },
```

Thanks! Sorry for the miss-issue

**Comment by DanTup** [comment]
np, glad you sorted it! Btw, you can use relative paths in `cwd` which might be a little better if you might move things around (or might be committing this to a repo).
