### ISSUE TITLE
Add missing cases quick fix adds enum attribute

### ISSUE THREAD

**Issue by gruvw** [Dart-Code/Dart-Code#4090]
Using `Add missing cases clauses` quick fix on a switch statement over an enumerated type adds an attribute as a switch clause.

**To Reproduce**
Use the following code snippet:
```dart
enum ErrorEnum {
  first,
  second;

  final int n;
  const ErrorEnum({this.n = 2});
}

void main(List<String> args) {
  ErrorEnum t = ErrorEnum.first;

  switch (t) {
    case ErrorEnum.first:
      break;
  }
}
```
1. Go to line 12 on `switch`
2. Use VSCode quick fix (`Ctrl+.`)
3. Click on `Add missing cases clauses`

**Expected behavior**
```dart
switch (t) {
  case ErrorEnum.first:
    break;
  case ErrorEnum.second:
    // TODO: Handle this case.
    break;
}
```

**Actual behavior**
```dart
switch (t) {
  case ErrorEnum.first:
    break;
  case ErrorEnum.second:
    // TODO: Handle this case.
    break;
  case ErrorEnum.n:
    // TODO: Handle this case.
    break;
}
```
Produces the following error: `Instance member 'n' can't be accessed using static access.` (line 18).

**Environment details**
 - Operating System and version: Ubuntu 22.04 LTS
 - VS Code version: 1.69.2
 - Dart extension version: v3.46.1
 - Dart/Flutter SDK version: Dart SDK version: 2.17.5, Flutter 3.0.4

**Comment by DanTup** [comment]
Thanks for the report! This has been fixed via https://github.com/dart-lang/sdk/issues/49003. I would expect it to show up in the next (non-hotfix) stable release.
