### ISSUE TITLE
Takes too much time to load

### ISSUE THREAD

**Issue by Anish-guragain** [Dart-Code/Dart-Code#4092]
Type: <b>Performance Issue</b>

The dart extension takes too much time to load everytime I open VS code. I can't fix this issue at all. It literally takes around 3 to 4 minutes. The extension is loaded but the features will be not available like showing error, auto format on save, autocompletion not working, and many more how do I fix this plz help.

Extension version: 3.46.1
VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:16.462Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.74GB free)|
|Process Argv|-n --crash-reporter-id bcd3a3f3-c457-4269-b6af-84c802073dd2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   113	 19320	code main
    0	    40	   176	   utility-network-service
    1	    90	  6032	   issue-reporter
    0	   177	  8164	   extensionHost
    0	     5	   632	     C:\WINDOWS\system32\cmd.exe /d /s /c ""D:\flutter_windows_3.0.5-stable\flutter\bin\flutter.bat" "daemon""
    0	   161	  1568	       "D:\flutter_windows_3.0.5-stable\flutter\bin\cache\dart-sdk\bin\dart.exe"  --disable-dart-dev --packages="D:\flutter_windows_3.0.5-stable\flutter\packages\flutter_tools\.packages"  "D:\flutter_windows_3.0.5-stable\flutter\bin\cache\flutter_tools.snapshot" "daemon" 
    0	    10	  9280	       console-window-host (Windows internal process)
    0	     5	  9300	     C:\WINDOWS\system32\cmd.exe /d /s /c ""D:\flutter_windows_3.0.5-stable\flutter\bin\cache\dart-sdk\bin\dart.exe" "devtools" "--machine" "--try-ports" "10" "--allow-embedding""
    0	    76	  3480	       "D:\flutter_windows_3.0.5-stable\flutter\bin\cache\dart-sdk\bin\dart.exe"  "devtools" "--machine" "--try-ports" "10" "--allow-embedding"
    0	    10	 16676	       console-window-host (Windows internal process)
    0	     5	 11080	     C:\WINDOWS\system32\cmd.exe /d /s /c ""D:\flutter_windows_3.0.5-stable\flutter\bin\cache\dart-sdk\bin\dart.exe" "language-server" "--protocol=lsp" "--client-id=VS-Code" "--client-version=3.46.1""
    0	    10	 10432	       console-window-host (Windows internal process)
    0	   451	 17112	       "D:\flutter_windows_3.0.5-stable\flutter\bin\cache\dart-sdk\bin\dart.exe"  "language-server" "--protocol=lsp" "--client-id=VS-Code" "--client-version=3.46.1"
    0	    26	 12028	   crashpad-handler
    0	   330	 13724	   "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --single-argument http://127.0.0.1:9100/
    0	    49	  4292	     window (undefined)
    0	   133	  4864	     window (undefined)
    0	    48	  8176	     window (undefined)
    0	   371	  9572	     gpu-process
    0	    18	 11180	     utility
    0	    62	 12000	     window (undefined)
    0	    32	 12184	     window (undefined)
    0	   149	 12472	     window (undefined)
    0	   170	 12600	     window (undefined)
    0	    29	 12604	     utility
    0	    50	 13056	     window (undefined)
    0	    60	 13152	     window (undefined)
    0	    20	 13384	     utility
    0	    42	 15724	     utility-network-service
    0	    69	 17756	     window (undefined)
    0	    98	 17816	     window (undefined)
    0	     8	 18756	     crashpad-handler
    0	   105	 13900	   shared-process
    0	    73	  7308	     ptyHost
    0	    84	 18940	     fileWatcher
    0	   153	 16684	   gpu-process
    0	   206	 17064	   window (SignUpPage.dart - Untitled (Workspace) - Visual Studio Code)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (SignUpPage.dart - Untitled (Workspace) - Visual Studio Code)
|    Folder (todoproject): 1433 files
|      File types: json(120) xml(116) flat(96) class(56) png(35) len(32)
|                  jar(29) txt(23) bin(22) properties(13)
|      Conf files: cmake(3)
|    Folder (TiktokGifters-1): 9 files
|      File types: png(2) prettierrc(1) html(1) md(1) css(1) js(1)
|      Conf files:
|    Folder (IT project): 43 files
|      File types: js(14) json(7) sol(2) png(2) babelrc(1) gitignore(1) txt(1)
|                  ico(1) html(1) css(1)
|      Conf files: package.json(1)
|    Folder (Final year project): 37 files
|      File types: js(14) json(5) sol(2) png(2) babelrc(1) gitignore(1) ico(1)
|                  html(1) css(1) jpg(1)
|      Conf files: package.json(1);
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912:30529769
vsclangdf:30486550
c4g48928:30535728
hb751961:30541207
dsvsc012cf:30540253

```

</details>

**Comment by DanTup** [comment]
Does this happen on all projects or just one? If it happens on a simple sample project, could you try enabling the [analysis server instrumentation log](https://dartcode.org/docs/logging/#analyzer-instrumentation) log:

- Press `F1` to open the command palette
- Run the **Preferences: Open Workspace Settings (JSON)**
- Add `"dart.analyzerInstrumentationLogFile": "analysis_server_log.txt"` to the JSON
- The analysis server will automatically restart. You'll see "Analyzing..." appear in the status bar soon after
- Wait until "Analyzing..." disappears from the status bar (this should correspond to when code completion etc. starts working again)
- Grab a copy of that log file and attach here (or email to me at logs@dartcode.org)

Note: This log will contain parts of your source code, which is why you should reproduce it on a sample/public project and not something private/sensitive.

Thanks!

**Comment by ff-hash** [comment]
Love you🫶
