### ISSUE TITLE
Add a version of the Flutter: Inspect Widget command that auto-cancels on selection

### ISSUE THREAD

**Issue by maks** [Dart-Code/Dart-Code#4093]
I often want to click on a UI element and see the line of widget code where its defined.

Currently this is eminently doable but involves the following steps: 
* click "open devtools" button in debug bar
* in Devtools click on "select widget mode" button
* click on the widget I'm interested in the Flutter running app 
* switch back to VSCode window (I run Devtools not in embedded mode)
* Remember to go back to Devtools to un-toggle  "select widget mode" button
* close devtools tab in web browser

It would be really nice if there was a single VSCode command palette command that I could use to do all of the above in one go, ie. select the cmd in the cmd palette, click on the widget I'm interested in the running app and then VSCode jumps to the relevant code line and exists out of  "select widget mode".

**Comment by DanTup** [comment]
There are already commands for toggling this without needing DevTools:

<img width="655" alt="Screenshot 2022-08-08 at 15 13 07" src="https://user-images.githubusercontent.com/1078012/183438494-cc0abd6a-15d0-4310-8902-313f1121a959.png">

<img width="742" alt="Screenshot 2022-08-08 at 15 27 11" src="https://user-images.githubusercontent.com/1078012/183441599-b9ec7b17-8fc0-40e8-9c18-5dbd96c7e4c7.png">

I think that reduces this to two steps (plus clicking a widget). Adding an additional command that auto-cancels on the first selection doesn't seem like a bad idea though.

**Comment by maks** [comment]
Ok wow, @DanTup, I think I need to spend more time looking through all the commands provided by DartCode! as I completely missed this one! But yes having a setting that cancels on first selection would be *perfect* 🙏🏻  Thanks for updating the title, that pretty much is exactly what I'm after 👍🏻

**Comment by DanTup** [comment]
I discovered the new DAPs don't support Inspect Widget correctly (that is, they don't navigate in the editor) so it makes sense to fix that (#4193) before tackling this, since it's possible the mechanism used for navigating will change a bit.

**Comment by DanTup** [comment]
There's a new command "Flutter: Inspect Widget (Auto-Cancel after Selection)" that will cancel the widget selection mode 1s after you click a widget (the delay is because it will also remove the visible selection of the widget on the app, and it looks buggy to have it disappear immediately when you tap).

**Comment by maks** [comment]
Awesome! Thanks again @DanTup !
