### ISSUE TITLE
From the terminal, clicking on a filename within a stacktrace should redirect to the proper line/column within that file

### ISSUE THREAD

**Issue by rrousselGit** [Dart-Code/Dart-Code#4100]
Hello!

**Is your feature request related to a problem? Please describe.**
Consider the following stacktrace:

```
  test/providers/state_provider/state_provider_test.dart 89:15  main.<fn>
```

Currently, clicking on the filename correctly opens the corresponding file. But it's opened at line/column 1:1.
It is seemingly ignoring the associated 89:15 present in the stacktrace

**Describe the solution you'd like**

Either VScode should support the format `file/path.dart line:col` or the stacktrace format should be changed to `file/path.dart:line:col` (which is already supported by VScode)

A simple way to reproduce:

```
echo   "test/providers/state_provider/state_provider_test.dart 89:15  main.<fn>"
```

vs 

```
echo   "test/providers/state_provider/state_provider_test.dart:89:15  main.<fn>"
```

**Comment by DanTup** [comment]
This seems to work ok for me:

![Aug-10-2022 18-03-20](https://user-images.githubusercontent.com/1078012/183973306-b17d5a01-5ae7-4cc2-8579-df8ceab4ce99.gif)

Is the relative path exact from your open workspace root? This link detection is done by VS Code and I think it will only work if the printed paths exactly match the relative path in your workspace.

**Comment by rrousselGit** [comment]
Ah I didn't consider this case.
In my case, the relative test path is indeed different from the relative-to-workspace path.

I'm in a mono-repo, so the actual relative path to the test file is:

```
packages/riverpod/test/providers/state_provider/state_provider_test.dart
```

**Comment by DanTup** [comment]
Gotcha. It may be worth filing an issue against VS Code about that, although it might be looking for exact matches to avoid too many false positives.

**Comment by rrousselGit** [comment]
No problem.

It's weird that changing the path to "path:line:col" fixes this though.

**Comment by DanTup** [comment]
I suspect it's just because that's more specific and would have less false positives. I'm just guessing though - there are quite a few issues with the built-in link detection (see https://github.com/microsoft/vscode/issues/34026 and https://github.com/microsoft/vscode/issues/108660) 😞

**Comment by DanTup** [comment]
Closing this as an upstream issue. I've subscribed to the VS Code issue in case I can provide any additional info to help move it along. Thanks!
