### ISSUE TITLE
Full Reload vs. Hot Reload

### ISSUE THREAD

**Issue by zantoku** [Dart-Code/Dart-Code#411]
Hi! I was wondering if there is a way to trigger the full App Reload from Dart-Code, same as when pressing capital-'R' in a terminal where `flutter run` is being run? Hot reload is obviously great, but sometimes you need to throw away the app state, and full reload is a lot faster than quitting and re-starting the debug session.

**Comment by DanTup** [comment]
When in a Flutter debug session, there will be a "Full Restart" command available in the command palette (added in #368). You can also keybind it from the Keybinding editor in Code.
Let me know if you have any issues with it!

**Comment by DanTup** [comment]
Duplicate of #368

**Comment by zantoku** [comment]
Works perfectly. Thanks, and sorry to bother you with the question.

**Comment by DanTup** [comment]
Not a problem! It's actually good to know which things might not be as discoverable as they should; maybe we can improve this (like maybe giving a notification telling you how to do this the first time you debug or something) :-)

**Comment by Victory886** [comment]
Flutter attach 的时候总是 Waiting for a connection from Flutter on iPhone 8 ...

**Comment by Victory886** [comment]
Flutter attach的时候总是等待iPhone 8上的Flutter连接...
我的Flutter 版本是 1.16.3的，请问怎么设置才能使用这个命令去hot reload 呢？
希望 Flutter 团队能给我解决方法，没有这个功能调试太慢慢了。
谢谢！

**Comment by DanTup** [comment]
@Victory886 if you're having issues please open a new issue rather than commenting on the end of an old closed issue. But please first upgrade to the latest stable version of Flutter to ensure the issue hasn't already been fixed. Thanks!
