### ISSUE TITLE
Add "Prompt" option to "Run Pub Get on Pubspec Changes"

### ISSUE THREAD

**Issue by rlipscombe** [Dart-Code/Dart-Code#4110]
When I'm doing an interactive rebase (on Windows, if that makes a difference), and VS Code is open, changes to `pubspec.yaml` (as the commits are replayed) cause the VS Code extension to re-run `pub get`. This occasionally causes git to fail the rebase, because `pubspec.lock` has changed while it's attempting to replay the changes.

Ideally, the extension would hold off running `pub get` until the rebase had finished, but I have no idea how you'd do that.

As a compromise, it would be useful if the "Run Pub Get on Pubspec Changes" was changed from a boolean to a tri-state: "Always | Prompt | Never".

**Comment by DanTup** [comment]
I think detecting an in-progress rebase (and then when it finishes) might be tricky (and/or unreliable), but I think having an option to always prompt is reasonable (we already have a prompt for when you open a project and we detect the files are out of sync).
