### ISSUE TITLE
Tooltip delay ? Does anyone sometimes have trouble to grab the tip with the mouse ?

### ISSUE THREAD

**Issue by nicolasmol** [Dart-Code/Dart-Code#4113]
Hi

I looked briefly on this board if I'm alone to feel bothered by this little inconvenience but I found nothing and I am surprised.

I often find it difficult to catch the toolstip as you can see in this capture.

![Peek 22-08-2022 16-15](https://user-images.githubusercontent.com/61077647/185970794-4d8b4aa7-8d04-478a-899d-aa57cfeeb13d.gif)

Wouldn't it be wise to have a few milliseconds delay when moving the cursor out of box before closing tit?

**Comment by DanTup** [comment]
This would need to be improved in VS Code itself. We only provide the data for the tooltip and don't control any of the on-screen rendering or UI interaction.

Please file an issue at https://github.com/microsoft/vscode, and post the link back here so I can 👍  it. Thanks!
