### ISSUE TITLE
Debugger won't stop at manually reactivated breakpoints after having toggled "off" all of them at once

### ISSUE THREAD

**Issue by nicolasmol** [Dart-Code/Dart-Code#4118]
- VS Code Version: 1.70.2
- OS Version: Linux Mint 20.3

Steps to Reproduce:

1. Define some breakpoints in the code
2. Run in Debug mode an app in  Android Emulator
3. In VScode,  do a right-click in "breakpoints" window, select "Deactivate all breakpoints"
4. Toggle "on" only one breakpoint in the code 

= Result: debugger won't stop at this breakpoint.

I ensured myself before that it's not a vscode's bug doing the same steps in a "php" code ...but not any other type, sorry.

**Comment by DanTup** [comment]
Can you confirm how you're "toggling on only one breakpoint"? I can't find any option to re-enable a breakpoint after deactivating them all (the context menu still has "disabled breakpoint" and toggling the tickbox in the Breakpoints list seems to re-enable them all).

I tried a few different things, but all seemed to work as expected. Can you reproduce this in a new sample app (created with the **Flutter: New Project** command)? If so, could you capture a log:

- Run the app and get ready to reproduce, with zero breakpoints
- Run the [**Dart: Capture Debugging Logs** command](https://dartcode.org/docs/logging/#capture-debugging-logs) to begin capturing logs
- Create multiple breakpoints and confirm they can be hit
- Deactivate all breakpoints
- Re-enable one breakpoint
- Trigger the code that should hit the breakpoint (but is not)
- Click **Cancel** on the logging notification to stop logging and open the log
- Attach the log here (or in a gist)

Thanks!

**Comment by nicolasmol** [comment]
Sorry I forgot to give an important precision :
Toggling ON a single breakpoint by clicking  the gray dot in the gutter

**Comment by DanTup** [comment]
When I click on a grey breakpoint, it just removes it. I can click again to re-add it, but this action re-enables all breakpoints, and they seem to function (sorry for poor quality capture):

https://user-images.githubusercontent.com/1078012/186639043-21784c3f-25e9-4de7-8ee1-2815da858f6d.mp4

Could you confirm the issue repros on a new sample project, and capture a log using the instructions above? Thanks!

**Comment by nicolasmol** [comment]
You're right...I can't reproduce at this moment.
I think I was struggling with the well-known issue "linux breakpoints don't work with symlinked path".
However at the time I reported this bug I was convince that I already copied the project into a solid path.
Maybe not.
I hope this "linux symlinks issue" will be soon fixed.
For now I close this report.
Sorry for annoyances

**Comment by DanTup** [comment]
Thanks for confirming. I presume the symlink issue you have is https://github.com/Dart-Code/Dart-Code/issues/3896?

**Comment by nicolasmol** [comment]
I think yes.
Thanks  support
