### ISSUE TITLE
Need an option to disable the documentation section on hover

### ISSUE THREAD

**Issue by blastrock** [Dart-Code/Dart-Code#4119]
**Is your feature request related to a problem? Please describe.**
When I hover some symbol on Dart, I get a documentation section on hover:

![image](https://user-images.githubusercontent.com/1370530/186607482-33fdde48-e173-4008-bd23-9a356239c0be.png)

I couldn't find a way to disable that section. Note that I don't want to disable the whole popup (which can be done at vscode level), I still need the build errors, the debugger inspections, and even the function prototype. I just want to remove the documentation.

**Describe the solution you'd like**
A lot of other plugins have an option for that, like:

```
  "rust-analyzer.hover.documentation.enable": false,
  "html.hover.documentation": false,
  "csharp.referencesCodeLens.enabled": false,
```

As an example, here's what my config looks like in C#, there's only the full type and a short description appearing:

![image](https://user-images.githubusercontent.com/1370530/186609674-c2a3ef4b-fde5-46cf-b52f-b12a4eae92de.png)

Is there an option in the Dart extension that I missed? Can you implement one?

**Comment by DanTup** [comment]
There's not currently an option for this, the hovers always include full docs.

Perhaps we should have a tri-state option for this: `"Full", "Summary", "None"`. There's a [long-standing VS Code issue](https://github.com/microsoft/vscode/issues/73120) about errors being tagged onto the end of the scrolling docs, which means long docs result in a lot of scrolling to see errors when hovering over squiggles so being able to see just the summary might be useful if you don't want to lose the whole doc.

**Comment by DanTup** [comment]
Server work is in https://github.com/dart-lang/sdk/commit/09c1722044177743b705d0faf5b26260a04c71df. We'll need to add the new setting to the `package.json` so it shows up in the UI.
