### ISSUE TITLE
Hovering over constructor's parameters shows an oversized font for the type

### ISSUE THREAD

**Issue by osaxma** [Dart-Code/Dart-Code#4120]
**Describe the bug**

Hovering over constructor parameters (named or unnamed) shows an oversized font for the type. The same oversized appears when hovering over the name of an argument of a constructor with named parameters as seen below:

<img width="845" alt="Screen Shot 2022-08-25 at 11 42 49 AM" src="https://user-images.githubusercontent.com/46427323/186618476-9a86ea86-64bd-4ae6-bf28-0c6184fae176.png">

It gets a bit wild when the type is multiple `typedef`s (e.g. shelf's `Middleware` type)

<img width="898" alt="Screen Shot 2022-08-25 at 11 47 11 AM" src="https://user-images.githubusercontent.com/46427323/186619501-715c9c91-1cb3-4455-a484-733f77fb00f8.png">

**Expected behavior**
I would expect the same font size as when hovering over the member definition (this is a wide screenshot so it looks smaller)

<img width="1219" alt="Screen Shot 2022-08-25 at 11 45 24 AM" src="https://user-images.githubusercontent.com/46427323/186619088-fc532a3d-ca7c-4126-89c7-9f9bc72189aa.png">

**Please complete the following information:**
- VS Code version: Version: 1.70.1
- Dart extension version: v3.46.1
- Dart/Flutter SDK version: Dart SDK version: 2.17.6 (stable) (Tue Jul 12 12:54:37 2022 +0200) on "macos_x64"

**Comment by DanTup** [comment]
Thanks, I can repro.

```dart
class A {
  /// aaa
  final String aaa; // hover over aaa

  A({required this.aaa}); // hover over aaa
}
```

There's no obvious difference in the response from the server:

```
{"id":653,"jsonrpc":"2.0","result":{"contents":{"kind":"markdown","value":"```dart\nString aaa\n```\nType: `String`\n*package:dartcode_flutter_4118/main.dart*\n\n---\naaa"},"range":{"end":{"character":18,"line":4},"start":{"character":15,"line":4}}}}
{"id":654,"jsonrpc":"2.0","result":{"contents":{"kind":"markdown","value":"```dart\n{required String aaa}\n```\nType: `String`\n---\naaa"},"range":{"end":{"character":22,"line":6},"start":{"character":19,"line":6}}}}
```

**Comment by DanTup** [comment]
So I think there are two issues here:

1. We need two newlines before `---` for it to be rendered as a horizontal line. Otherwise it's being interpreted to mean the line before is a header. This needs fixing in the server.
2. The missing newline before `package:` in the rendering may be a VS Code issue - it's rendering differently to I would expect (or GitHub does) so I've filed https://github.com/microsoft/vscode/issues/159161.

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/8bf496e5a7e4d00cf85f753181da8c1a7684539f. It's an SDK change, so will show up in a future SDK release.
