### ISSUE TITLE
Accepting suggestions occasionally deletes trailing characters

### ISSUE THREAD

**Issue by Merrit** [Dart-Code/Dart-Code#4123]
**Describe the bug**
Sometimes - I don't know why - accepting a suggestion will delete trailing characters.

I am unable to reproduce the issue reliably, but it happens to me several times a day. I am unsure of how to troubleshoot. The issue has been ongoing for I believe months now.

**To Reproduce**

1. Have a line you'd like to accept a suggestion for, like so:

```dart
void main(List<String> args) {
  args.singleWhere((element) => element.con)
}
```

2. Accept suggestion for "contains"

Occasionally it will delete trailing characters, like so:

```dart
void main(List<String> args) {
  args.singleWhere((element) => element.contains(other
}
```

**Expected behavior**

The suggestion should be inputted without removing existing characters, like so:

```dart
void main(List<String> args) {
  args.singleWhere((element) => element.contains(other))
}
```

**Please complete the following information:**
 - Operating System and version: Linux: Fedora 36
 - VS Code version: 1.70.2
 - Dart extension version: 3.46.1
 - Dart/Flutter SDK version: Dart 2.17.6 / Flutter 3.0.5 stable

**Comment by DanTup** [comment]
I believe this is the same issue as #3892. I've made a change to the analysis server that I believe will fix this, but it's not made a stable Dart/Flutter SDK release yet. If you still see this after the next stable releases, please ping on #3892 and I'll re-open and take another look.

Thanks!
