### ISSUE TITLE
Tests with more than one newlines in names are not runnable from CodeLens links

### ISSUE THREAD

**Issue by jeff9315** [Dart-Code/Dart-Code#4125]
No tests match regular expression " test & exit /B 0". #4007
https://github.com/Dart-Code/Dart-Code/issues/4007

This fails in Windows 11 using Dart Code 3.46.1

```
 test('''
    Given formType is signIn
    When signInWithEmailAndPassword succeeds
    Then return true
    And state is AsyncData
    ''', () async {
```

This succeeds

```
test('''
    Given formType is signIn When signInWithEmailAndPassword succeeds Then return true And state is AsyncData
    ''', () async {
```

The error is
> No tests match regular expression "submit     Given formType is signIn\n    When signInWithEmailAndPassword succeeds & exit /B 0".

**Comment by DanTup** [comment]
Thanks. I think there's something slightly different going on here, as if I use the original case from that issue things still work, but the case above does not:

```dart
  // This one fails
  test('''
    Given formType is signIn
    When signInWithEmailAndPassword succeeds
    Then return true
    And state is AsyncData
    ''', () async {});
  // This one works
  testWidgets('''
        test
        ''', (tester) async {});
```

So let's keep this issue open and use it for this rather than re-open that one.

**Comment by DanTup** [comment]
This turned out to be the same issue but when there was more than one newline. It was a bad regex escape that only replaced the first:

```ts
.replace("\n", "\\n") // bad
.replace(/\n/g, "\\n") // good
```

Not the first time I've had a bug like that, perhaps I need a lint :-)

**Comment by jeff9315** [comment]
Ironic that this bug was in the testing module :-)
