### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by alimaherofficial** [Dart-Code/Dart-Code#4135]
- Issue Type: `Bug`
- Extension Name: `dart-code`
- Extension Version: `3.46.1`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.70.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by DanTup** [comment]
> ⚠️ We have written the needed data into your clipboard. Please paste! ⚠️

Are you able to paste this information and provide a description of what's wrong?

Thanks!
