### ISSUE TITLE
There are 2 definitions of Classes after file rename

### ISSUE THREAD

**Issue by AliFathi** [Dart-Code/Dart-Code#4137]
Type: <b>Bug</b>

I'm a Dart noob, and after installing Flutter extension, was playing around basic features and syntax. I created 2 classes in 2 different files:
Team class in `Team.dart`, and Coach class in `Coatch.dart`. 
but after reading Dart docs about code style, I renamed files as lower-cased:
`Team.dart` --> `team.dart`
`Coatch.dart` --> `coatch.dart`
and problem arose: now IntelliSence shows me 2 different definitions of each class, and they conflict each other. albeit, despite error messages, the code runs successfully.

![team_conflict_1](https://user-images.githubusercontent.com/14835655/188247737-af6ea7e6-0392-47ee-aca2-d80f35da68e1.png)
![team_conflict_2](https://user-images.githubusercontent.com/14835655/188247738-deabc050-ce9e-4fb6-8d88-72409178451f.png)

I tried "Clear Editor History", and also renaming the parent folder, and restarting VS Code, all failed.

Extension version: 3.48.0
VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

**Comment by AliFathi** [comment]
`import` was updated automatically, but nothing changes. clearing and rewriting them also had no benefits.
closing all files and restarting solved the issue :)

**Comment by DanTup** [comment]
Great, glad it's sorted. I suspect it was probably an open file causing VS Code to trigger an additional overlay in the server.

Right now, support in the server for case-insensitive files is a little patchy, so you can sometimes end up with two open files that have different casing when they're actually the same.

Please let me know if this comes up again and you're unable to resolve it.
