### ISSUE TITLE
DartDocs are missing from auto-import extension members

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#4144]
Related to https://github.com/Dart-Code/Dart-Code/issues/4143, we're not finding the element to look up the docs.

<img width="1018" alt="Screenshot 2022-09-05 at 17 37 33" src="https://user-images.githubusercontent.com/1078012/188490386-80c73147-3ba9-4982-a8b5-7f317179b102.png">

**Comment by robertherber** [comment]
Need this badly! :) What do we need to do to enable this? Docs would be great but probably this should be default behaviour?

**Comment by DanTup** [comment]
@robertherber this title might have been a little ambiguous. This wasn't about documenting how to use this, the problem is that the DartDocs are missing from the auto-import extension members. Auto-imports of extension members is enabled by default, however they'll only show up in SDKs that include the fix at https://github.com/dart-lang/sdk/commit/1c8bb855c3a501639f2229614439834924151a2f (which is not the current stable releases, although it's likely in the current beta releases). I would expect the next major stable releases of Dart/Flutter include that, so they should show up automatically (although, without dartdocs in the details pane until I've fixed this issue).

**Comment by robertherber** [comment]
Aah, gotcha 👍 Being used to the smoothness of TypeScript I feel so handicapped without this. Thanks for your work on it!

**Comment by DanTup** [comment]
This was fixed along with https://github.com/Dart-Code/Dart-Code/issues/3787 in https://github.com/dart-lang/sdk/commit/fc9581d758f537f80435602040ac014f69629f33:

<img width="1058" alt="Screenshot 2022-11-28 at 12 57 00" src="https://user-images.githubusercontent.com/1078012/204283381-c89f4e07-ee52-4b9a-b239-f850624cf13d.png">

Requires an SDK release to show up.
