### ISSUE TITLE
hotkeys do not work in the cmd + . menu 

### ISSUE THREAD

**Issue by d-khomenko** [Dart-Code/Dart-Code#4145]
**Describe the bug**
Hotkeys do not work in the "cmd" + "."  menu. 
Previously, by clicking on the first letter you could select the appropriate menu item. 

**To Reproduce**
<img width="275" alt="image" src="https://user-images.githubusercontent.com/45741736/188516149-d7115826-114d-4e3b-a257-0610119453ba.png">

Click on "R" 

**Expected behavior**
Select "Remove Widget" from the menu
**what's going on** -> nothing

**Comment by juskek** [comment]
Same issue here. Is there any way to revert back to the old refactoring menu temporarily?

**Comment by d-khomenko** [comment]
Got it, thanks for the answer!
