### ISSUE TITLE
how to detect finished successful  build_runner ?

### ISSUE THREAD

**Issue by esmaeil-ahmadipour** [Dart-Code/Dart-Code#4148]
We need to be notified of the successful completion (or failure to re-run) of build_runner.
 I need to call its command in a bash file, but the program
It does not close after the operation completes (successfully or unsuccessfully).

I want to use it in build automation steps (ci/cd).

Please help on this particular issue thanks.

**Comment by DanTup** [comment]
I'm not sure I understand the request. If you're looking for something to run on CI servers, I think this is the wrong place to raise it. This issue tracker is for the VS Code extension, and presumably you're not running `build_runner` through VS Code for your CI.

I would expect `build_runner` to exit once it's completed though (as long as you're using [`build` and not `watch`](https://pub.dev/packages/build_runner#built-in-commands) - `build` says "`build`: Runs a single build and exits."). If that's not what you're seeing, I was going to suggest filing an issue at https://github.com/dart-lang/build/issues, but I noticed you've already opened https://github.com/dart-lang/build/issues/3362.

I'll close this one, as I don't think there's anything to do here.
