### ISSUE TITLE
Support hovers on type inlay hints

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#4156]
As part of #4154 we'll be showing types as inlay hints:

![Screenshot 2022-09-13 at 11 16 34](https://user-images.githubusercontent.com/1078012/189876376-9d2a7c13-0a5d-42df-9624-c2a992e77e63.png)

It would be nice if you could hover over these and also get the dartdoc for that type. It looks like inlay hints support tooltips, and we could include an element reference string in the `data` and stitch this in via `resolve` (which we don't currently support, but could).

**Comment by DanTup** [comment]
Done in https://github.com/dart-lang/sdk/commit/18acd0e44c9fa8213f721ca6fbaaf550ac4665d5.

**Comment by AlexV525** [comment]
Hi @DanTup do we have an IntelliJ issue targeting the same feature as you know?

**Comment by DanTup** [comment]
@AlexV525 I think https://youtrack.jetbrains.com/issue/WEB-53819/Add-Inlay-Hints-to-Dart-code-variable-type-parameter-name-and-more. is the issue for this for IntelliJ.

**Comment by AlexV525** [comment]
Thanks, but it seems outdated, I'll submit a new one to GitHub then.
