### ISSUE TITLE
Find References doesn't work when selection covers an entire symbol

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#4157]
Double-clicking on a method name then pressing Shift+F12 doesn't find anything:

<img width="746" alt="Screenshot 2022-09-14 at 15 20 54" src="https://user-images.githubusercontent.com/1078012/190180747-cf600e58-f00a-41bf-91f6-b87be85b4a59.png">

(same goes for putting the caret at the end of the name, which is likely the same offset for this selection).

**Comment by DanTup** [comment]
@bwilkerson I'm trying to debug this and found that NodeLocator() is locating the argument list here in the case where the caret is in front of it (which seems reasonable and maybe should be handled specially). However, I noticed that when the caret is in the name, we don't locate the name, but rather the whole member declaration. This seemed odd to me so I wanted to check this is correct before making any changes.

For example, if I run this test code:

```dart
@soloTest
  void test_danny() async {
    await resolveTestCode('''
void aaa() {}
''');
    result.unit.accept(MyVisitor());
  }
```

Where `MyVisitor` looks like this:

```dart
class MyVisitor extends UnifyingAstVisitor<void> {
  @override
  void visitNode(AstNode node) {
    print('Visiting (${node.offset}) $node');
    super.visitNode(node);
  }
}
```

I get the following output:

```
Visiting (0) void aaa() {}
Visiting (0) void aaa() {}
Visiting (0) void
Visiting (0) void
Visiting (8) () {}
Visiting (8) ()
Visiting (11) {}
Visiting (11) {}
```

What seems off to me here is that there is no visit of the `aaa` token the starts at offset 5, but I was expecting one. Does this seem like a bug? (anecdotally, I was sure the behaviour in this issue worked in the past, I feel like I do this all the time, but there are no tests with the caret at the end of the identifier so I may be misremembering 😄).

**Comment by DanTup** [comment]
Testing the original behaviour up top with stable 2.18.0, it definitely does work, so I think something has changed. I'll try to bisect this tomorrow to figure out what changed (assuming nothing stands out and you might know what it is already).

**Comment by DanTup** [comment]
Aah, you warned me that was coming, makes sense now.

It's possible this affects more than just Navigation then - previously the offset between name and args (`foo^(`) would have located the name node but now it locates the argument list. Anything that doesn't handle this specifically might fail in this case (when double-clicking a symbol to select it, VS Code uses the end as the offset for requests like this).

I'll fix navigation and check other functionality for similar issues. Thanks!

**Comment by bwilkerson** [comment]
> It's possible this affects more than just Navigation then ...

Yes, lots of code might potentially be broken. We relied heavily on test cases to catch breakage, but tests can't provide complete coverage.

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/d83cb4e621d5b53b7222a6d70a4958fdbf65f64f.
