### ISSUE TITLE
Inlay Hints appear in the wrong place when a method has a dart doc comment.

### ISSUE THREAD

**Issue by nshahan** [Dart-Code/Dart-Code#4160]
**Describe the bug**
Inlay Hints for the return type of a method appear in the wrong place when a method has a dart doc comment. It appears to happen to getters and setters as well if they don't explicitly have their types written in the source code.

**To Reproduce**
Enable Inlay Hints and look at a method with doc comments where the there is no static type in the source code.

**Expected behavior**
The Inlay Hint showing the type should always appear after the doc comment and before the method name.

**Screenshots**
<img width="338" alt="Screen Shot 2022-09-15 at 2 54 40 PM" src="https://user-images.githubusercontent.com/2498387/190515672-153ba4ba-d0e4-49dd-a5ac-4744d4cc9c48.png">

**Please complete the following information:**
 - Operating System and version: Mac OS 12.5.1
 - VS Code version: 1.71.2
 - Dart extension version: v3.48.3
 - Dart/Flutter SDK version: 2.19.0-edge.b5fe11142c67ceb7012681f2cea720ec556e2af6

**Comment by DanTup** [comment]
😬

Thanks! Got a fix at https://dart-review.googlesource.com/c/sdk/+/259584/. Will keep this open until it lands.

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/c841c33482c4436572085b452b4d3a8edc3d9836 (ships with an SDK update, not Dart-Code).
