### ISSUE TITLE
"Remove widget" is not available when it's from a library imported with an alias

### ISSUE THREAD

**Issue by ValentinVignal** [Dart-Code/Dart-Code#4169]
**Describe the bug**

When a library is imported with an alias (ex: `import 'package:flutter/material.dart' as material;`), the option "Remove widget" is not available on the widget from this library (ex: `material.Center()`).

**To Reproduce**
1. Copy this code 
  ```dart
  import 'package:flutter/material.dart';
  import 'package:flutter/material.dart' as material;
  
  class MyWidget extends StatelessWidget {
    const MyWidget({Key? key}) : super(key: key);
  
    // This widget is the root of your application.
    @override
    Widget build(BuildContext context) {
      return const Center(
        child: material.Center(
          child: Text('Flutter'),
        ),
      );
    }
  }
  ```
  Or check out https://github.com/ValentinVignal/flutter_app_stable/tree/flutter-vscode/remove-widget.
2. Toggle the code actions on `Center` and then on `material.Center`.
3. Notice that the code action "Remove widget" is available for `Center` but not for `material.Center`.

**Expected behavior**

I expected to be able to remove `Center` and `material.Center`

**Screenshots**

On `Center`:

![image](https://user-images.githubusercontent.com/32538273/191638213-5c32c99f-71ec-41c7-9ec0-13dc27c7cd53.png)

On `material.Center`: 

![image](https://user-images.githubusercontent.com/32538273/191638272-54b86024-eb42-4864-9425-71db04092157.png)

**Please complete the following information:**
 - Operating System and version: macOS Big Sur, version 11.6.8
 - VS Code version: 1.71.2
 - Dart extension version: v3.48.4, Flutter extension version: v3.48.0
 - Dart/Flutter SDK version: 
  ```
  Flutter 3.3.2 • channel stable • https://github.com/flutter/flutter.git
  Framework • revision e3c29ec00c (8 days ago) • 2022-09-14 08:46:55 -0500
  Engine • revision a4ff2c53d8
  Tools • Dart 2.18.1 • DevTools 2.15.0
  ```
 - Target device (if the issue relates to Flutter debugging): NA

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/3e9a99df6a864ffd65969cc580fb4ecc7fa3f7fd. The change is in the Dart SDK, so the fix will show up with a future SDK release (rather than a VS Code extension release).
