### ISSUE TITLE
"Load all stack frames" should be "Load more stack frames" in debugger

### ISSUE THREAD

**Issue by gspencergoog** [Dart-Code/Dart-Code#4170]
This is a minor thing, but when in the debugger view, if there are a lot of things on the stack, then it shows a "Load all stack frames" button at the bottom of the list.

The only thing is, if you click that, it just loads some more, maybe ten more frames, but not *all* of them.

It should probably read "more" instead of "all", or, if we don't have control over that string, then the Dart debugger should actually respond with all of the frames instead of just a few more.

<details>
<summary>Version info</summary>
<pre>
[!] Flutter (Channel menu_bar_v, 3.4.0-19.0.pre.485, on Debian GNU/Linux rodete 5.18.16-1rodete1-amd64, locale en_US.UTF-8)
    • Flutter version 3.4.0-19.0.pre.485 on channel menu_bar_v
    ! Upstream repository git@github.com:gspencergoog/flutter.git is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to git@github.com:gspencergoog/flutter.git to dismiss this error.
    • Framework revision 33241ebd8b (14 minutes ago), 2022-09-22 10:37:04 -0700
    • Engine revision ac6cb9f244
    • Dart version 2.19.0 (build 2.19.0-228.0.dev)
    • DevTools version 2.17.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.
</pre>

VSCode:
<pre>
Version: 1.71.2
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:12:14.256Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.18.16-1rodete1-amd64
Sandboxed: No
</pre>

VSCode plugins:
Dart: v3.48.4
Flutter: v3.48.0
</details>

**Comment by DanTup** [comment]
@isidorn is there any way to control this "Load All Stack Frames" text? For performance reasons we're currently "paging" in stack frames (there's some discussion about this in https://github.com/microsoft/vscode/issues/31851#issuecomment-734258782), but it makes this text incorrect. I think in the past it said "Load more stack frames" but I can't find any way to control this.

**Comment by isidorn** [comment]
This is not controllable right now.
fyi @roblourens who now owns the debug UI on the VS Code side.

**Comment by roblourens** [comment]
Here, we changed "Load more" to "Load all" and request all frames from the DA when you click that button. https://github.com/microsoft/vscode/issues/102048

But I think DAs can return fewer frames if they wish and that is what @DanTup is doing right?

I can change the text back to "Load more", "more" will often be "all" but not always, it seems fine to me

**Comment by DanTup** [comment]
@roblourens yep, that's right. Dart is returning a fixed number of frames for performance reasons (because getting the whole call stack can be expensive is some environments). This is discussed a little at https://github.com/microsoft/vscode/issues/31851#issuecomment-734258782 (the last bullet point).

I think "more" is more accurate given DAs may behave differently (both a subset of frames and the full set of frames is "more"), although if there's some compelling reason to show the text "All" in the cases where it will fetch all, perhaps there should be some flag a DA can set to say whether it provides all or a slice (feels like that might be overkill though).

**Comment by roblourens** [comment]
Yeah, sounds reasonable to me, I filed https://github.com/microsoft/vscode/issues/161884 for next month

**Comment by DanTup** [comment]
Perfect, thanks! I'll close this one then as there's nothing to do here.
