### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by benjamintumwesigye** [Dart-Code/Dart-Code#4175]
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `3.48.4`
- OS Version: `Darwin x64 19.6.0`
- VS Code version: `1.71.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///var/folders/h2/j9tqqsb95g971q4xyh6k3jxc0000gn/T/Dart-Code.dart-code-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by badaszszsz** [comment]
Dear @benjamintumwesigye , have you some logs/description about problems you face?

Best regards.

**Comment by DanTup** [comment]
@benjamintumwesigye 

> ⚠️ Make sure to attach this file from your home-directory:
> ⚠️file:///var/folders/h2/j9tqqsb95g971q4xyh6k3jxc0000gn/T/Dart-Code.dart-code-unresponsive.cpuprofile.txt

Are you able to attach this file?

**Comment by benjamintumwesigye** [comment]
I didn`t get the file, I will open a new issue with the file once it happens again 

Thanks to you all;
