### ISSUE TITLE
Initial analysis takes > 10 minutes

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#4180]
Raised by @CoderUni in https://github.com/Dart-Code/Dart-Code/issues/4115#issuecomment-1255287962. Moving here because it seems different to the original problem in that issue.

```
[12:44:42 PM] [General] [Info] Analyzer:FirstAnalysis timing: 139489ms
```

**Comment by DanTup** [comment]
@CoderUni does this problem occur only for this one specific project, or all projects you create?

**Comment by CoderUni** [comment]
> @CoderUni does this problem occur only for this one specific project, or all projects you create?

It only occurs for one specific project.

Thanks for your help. I sent the logs to `logs@dartcode.org`. Hopefully it pops up in your email this time :)

**Comment by DanTup** [comment]
@CoderUni thanks. There's nothing obvious in what you sent. It's odd that it only occurs in this one project though. I would suggest trying the following:

- Make an exact copy of your project folder and open that to see if it occurs there
- If it does, if you have a repository, re-clone to a new folder and see if it occurs there (a clean checkout will get rid of any `build`, `.dart_tool` etc. folders that could be related)
- If it still repros from a clean checkout, that suggests there is something in those files causing it. I would try removing anything sensitive code to try and get it to a point where you can share the project as a repro for further debugging

**Comment by CoderUni** [comment]
Thanks @DanTup :) That did the trick. I tried deleting the build and .dart_tool output but it didn't work. I'm not sure which files or folder is causing the issue but the problem is fixed :)

**Comment by DanTup** [comment]
Glad it's fixed, although I'm not sure what might have caused it. It you see it again, maybe it's worth copying the folder and trying to poke around to see which folders are causing it. Circular symlinks have caused issues in the past, but usually they would just fail (because the paths ultimately get too long) and not just start working after some several minutes.

I'll close this because I don't think there's anything we can currently investigate without a repro, but please do post back if you see it again and we can try to do some more troubleshooting. Thanks!
