### ISSUE TITLE
"See code in" example links incorrectly group multiple examples, don't linkify entire path

### ISSUE THREAD

**Issue by gspencergoog** [Dart-Code/Dart-Code#4181]
When navigating to an example in the Flutter repo source code in the form of:

```dart
/// {@tool dartpad}
/// This example shows various [ClipRRect]s applied to containers.
///
/// ** See code in examples/api/lib/widgets/basic/clip_rrect.0.dart **
/// {@end-tool}
/// ...
/// {@tool dartpad}
/// This example shows a [ClipRRect] that adds round corners to an image.
///
/// ** See code in examples/api/lib/widgets/basic/clip_rrect.1.dart **
/// {@end-tool}
```

If there are multiple examples in the comment then it says that there are two possible "definitions" for the destination, when the analyzer [should be supplying the full path](https://dart.googlesource.com/sdk/+/refs/heads/main/pkg/analyzer_plugin/lib/utilities/navigation/navigation_dart.dart#226) to the destination under the pointer, and so VSCode should be linkifying the entire path, not just the path element.

![Screenshot from 2022-09-26 16-26-33](https://user-images.githubusercontent.com/8867023/192398582-46f2d5f5-4f61-4595-bdc4-f2451115787c.png)

If there is only one example in the dartdoc block, then it more correctly links to just the link under the pointer:

![Screenshot from 2022-09-26 16-27-08](https://user-images.githubusercontent.com/8867023/192398709-cb2109db-7cf5-4086-9fe2-7e1b41b785c6.png)

However, it seems to me that VSCode should be rendering the links in another color (the "link" color that is used by symbol refs in brackets) so that users even know that they can click on them. It's not very discoverable to have to ctrl-click on the path in a comment, since it's not expected that it is a symbol.

It also seems like in that screenshot that the tooltip/hover text is showing an empty tip, which also shouldn't happen.

**To Reproduce**
1. Open `flutter/packages/flutter/lib/src/widgets/basic.dart` in the Flutter repo.
2. Point at the path in the "See code in" marker in the dartdoc block for `ClipRRect`.
3. If you press Ctrl/Cmd while pointing at parts of the path, it will only highlight that part of the path, and will think there are two destinations.

**Expected behavior**
1. Draw the link in the "link" color, even when not pointing at it.
2. When pointing at it with Ctrl/Cmd down, linkify the entire path, not just the component under the pointer.
3. When clicking on the path, it should just navigate without having to disambiguate, even if there are multiple examples.
4. When pointing at a link, don't show an empty tooltip.

**Please complete the following information:**
 - Operating System and version: Debian GNU/Linux rodete 5.18.16-1rodete1-amd64
 - VS Code version: 1.71.2
 - Dart extension version: v3.48.4
 - Flutter extension version: v3.48.0
 - Dart/Flutter SDK version: Dart version 2.19.0 (build 2.19.0-229.0.dev)/Flutter version 3.4.0-29.0.pre.111

**Comment by DanTup** [comment]
1. Wrong highlight range when there are multiple results
  This one seems to be a VS Code but (I've verified the ranges the server returns are correct) - https://github.com/microsoft/vscode/issues/160958
2. Highlight links before hovering/holding ctrl
  I've split this to https://github.com/Dart-Code/Dart-Code/issues/4186
3. Shouldn't need to disambiguate between links in the same dartdoc when you're hovering on a specific one
  Got a fix open at https://dart-review.googlesource.com/c/sdk/+/261365/.
4. Empty tooltips
  I've split this to https://github.com/Dart-Code/Dart-Code/issues/4187

I'll use this issue for (3) above, since the others have their own issues and that seems like the biggest issue.

**Comment by DanTup** [comment]
https://github.com/dart-lang/sdk/commit/dd12cfd073550989fd1499eead9c996c4a0748b8 fixes the issue with multiple results being returned instead of only the one at the location requested. It's an SDK change, so will show up based on your SDK version (not Dart-Code version).
