### ISSUE TITLE
Wrong indentation on save

### ISSUE THREAD

**Issue by dartat** [Dart-Code/Dart-Code#4183]
**Describe the bug**
Wrong indentation when using then/catchError

**To Reproduce**
1. Open a new dart file
2. Paste this code 
```dart
import 'package:flutter/src/widgets/framework.dart';
import 'package:flutter/src/widgets/container.dart';
import 'package:http/http.dart' as http;

class MyWidget extends StatelessWidget {
  const MyWidget({super.key});

  void test() {
    final url = Uri.https(
      'https://google.com',
      '/test.json',
    );
    http.post(
      url,
      body: 'a',
    )
    .then((response) {
      //do something
    });
  }

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

```
3. Press CTRL+S to save

**Expected behavior**
The indentation shouldn't be broken like in the following screenshot

**Screenshots**
![image](https://user-images.githubusercontent.com/114478313/192486340-03587987-9fab-4cf2-875e-951a5a9164dd.png)

**Please complete the following information:**
 - Operating System and version: Win 10
 - VS Code version: 1.71.2
 - Dart extension version: v3.48.0
 - Dart/Flutter SDK version:  sdk: ">=2.17.6 <3.0.0"

**Comment by DanTup** [comment]
Formatting is handled by [dart_style](https://github.com/dart-lang/dart_style) so any bugs/improvements would need to be made there.

I think your example is the same one noted here though:

https://github.com/dart-lang/dart_style/issues/1121#issuecomment-1184224140

So I would add 👍  to that issue. Thanks!
