### ISSUE TITLE
LSP server is not handling errors in plugins correctly

### ISSUE THREAD

**Issue by Tanthus** [Dart-Code/Dart-Code#4189]
**Describe the bug**
The VSCode dart LSP analyzer just continues to spin.  

It will start working normally by checking the "Dart: use legacy protocol" checkbox.   The problem started mid-summer

**To Reproduce**
When opening VSCode just let the Analyzer run.   It continues to process and never gives any feedback.  It looks like it is getting stuck somewhere but not sure where as it never returns an error, just keeps spinning.

Tried clearing caches and even starting fresh with a copy of the problematic project, but only using the legacy protocol fixes the issue.

Willing to run and provide some logs or other details if you let me know how to produce them or what files you might need.

**Expected behavior**
Should complete and reveal problems with the code.  No problems ever show up even though they exist in the code.

**Please complete the following information:**
 - Operating System and version: Windows 10
 - VS Code version: 1.71.2
 - Dart extension version: 3.49.20220929 pre-release and also the latest regular version
 - Dart/Flutter SDK version: Flutter 3.3.3, Dart 2.18.2, DevTools 2.15.0
 - Target device (if the issue relates to Flutter debugging): N/A

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.3, on Microsoft Windows [Version 10.0.19043.2006], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.5)
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.71.2)
[√] Connected device (3 available)
[√] HTTP Host Availability
• No issues found!

**Comment by DanTup** [comment]
@Tanthus sorry for the delay. Could you try enabling the [analyzer log file](https://dartcode.org/docs/logging/#analyzer) and see what's recorded?

Can you also check whether this happens in a new project created with `flutter create`, or if it's specific to this project?

Thanks!

**Comment by Tanthus** [comment]
@DanTup, thank you for your help.   With the help of the log, I was able to figure out the issue.   I did create a new project with `flutter create`, and the analyzer worked.   I also enabled the analyzer log file which pointed to the "drift_dev" library as causing the exit.  

I attached the full log but the area that appeared to cause the analyzer to stop was:
```
FileSystemException: No file found, path = 'c:\proj\prolific-app-flutter\app\web\pubspec.yaml': 
#0      _fromPackageDir (package:build_config/src/build_config.dart:199:3)
<asynchronous suspension>
#1      BuildConfig.fromPackageDir (package:build_config/src/build_config.dart:31:21)
<asynchronous suspension>
#2      fromRootDir (package:drift_dev/src/utils/options_reader.dart:6:19)
<asynchronous suspension>
#3      MoorDriver.tryToLoadOptions (package:drift_dev/src/backends/common/driver.dart:95:22)
<asynchronous suspension>
```

I was able to eventually trace this problem back to somehow having a misplaced copy of `analyis_options.yaml` in the `web/` directory.   Removing that file fixed the issue.

Anyway, I'm including the log file for completeness.     I'll leave it for you to close in case you wanted to put checks in the code, but I can say that the problem occurred because of user error.
[analyzer_001.txt](https://github.com/Dart-Code/Dart-Code/files/9718162/analyzer_001.txt)

**Comment by DanTup** [comment]
@Tanthus thanks for the investigation! If I'm reading correctly, I think there is an analyzer plugin being loaded that is leading to this.

My understanding is that even badly-behaved plugins should not bring down the server, so I'll keep this open and try to repro. It's likely there need to be some server fixes here (as well as possible fixes in the plugin being loaded).

**Comment by DanTup** [comment]
@Tanthus I haven't been able to reproduce this - are you able to share a small sample project that triggers it? I can see the plugin being loaded, but I tried putting some analysis_options in a few different folders, but nothing seems to trigger the crash you had in your log.

**Comment by DanTup** [comment]
@Tanthus please let me know if you have a repro for this. It does seem like a bug, but unfortunately I can't debug any further without more specific steps to reproduce.
