### ISSUE TITLE
Invalid error "A project with the name android already exists"

### ISSUE THREAD

**Issue by kinex** [Dart-Code/Dart-Code#4190]
In my VS Code workspace I have a Flutter app project and several Flutter plugin projects. After a quite recent Flutter or VS Code/Dart-Code update I started getting these errors in the Problems-tab:

```
A project with the name android already exists.
The supplied phased action failed with an exception.
Duplicate root element android
Could not run phased build action using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-6.7-all.zip'.
The specified initialization script 'C:\\Users\\me\\AppData\\Local\\Temp\\init17435518505816795338.gradle' does not exist.
```
I get these same errors for all my 4 plugin projects in the workspace. The error "Could not run phased build action..." is shown also for my app project.

There are actually two errors "A project with the name android already exists." and "Could not run phased build action..." which are probably unrelated but they both appeared at the same time after upgrading Flutter and/or VS Code/Dart-Code. I have not made any related changes to my plugin projects and there was not these issues earlier.

All my plugin projects have a folder "example/android" created by the Flutter tooling. The folder names are shown in red color in the VS Code Explorer indicating some error.

The errors do not prevent building or running the app, so this is mainly a cosmetic problem. Anyway, to errors are still annoying making to find any real errors more difficult.

**Expected behavior**
Those errors should not be shown. There are not issues.

**Please complete the following information:**
 - Operating System and version: Windows 10
 - VS Code version: 1.71.2
 - Dart extension version: 3.48.4
 - Dart/Flutter SDK version: Flutter 3.3.3

**Comment by DanTup** [comment]
When do you see this error? When starting to run/debug the app (eg. pressing `F5`)?

Do you see the same thing if you run the same project with `flutter run` from the terminal?

**Comment by kinex** [comment]
I only open the project in VS Code, no need to run/debug it. But I just noticed disabling the extension "Language Support for Java(TM) by Red Hat" fixes the issue. So this has nothing to do with Dart-Code. Sorry about the wrong report! I have no idea when and why I have installed that extension, maybe I have pressed by accident some "Yes" button when VS Code has suggested to install a new extension as it often does when e.g. opening some Flutter/Android/Java files for viewing. I seem to have several other Java related extensions installed too, maybe for the same reason.

**Comment by DanTup** [comment]
Ah, glad you tracked it down. I think I disabled recommendations in VS Code because it was often suggesting extensions I really didn't need 😄
