### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by abidwali** [Dart-Code/Dart-Code#4192]
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `3.48.4`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.71.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/abidw/AppData/Local/Temp/Dart-Code.dart-code-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by DanTup** [comment]
> ⚠️ Make sure to attach this file from your home-directory:
> ⚠️file:///c%3A/Users/abidw/AppData/Local/Temp/Dart-Code.dart-code-unresponsive.cpuprofile.txt

Are you able to attach this file? Thanks!
