### ISSUE TITLE
Code formatting issues

### ISSUE THREAD

**Issue by sgon00** [Dart-Code/Dart-Code#420]
# First Issue

__PLEASE IGNORE THE FIRST ISSUE. I FOUND OUT THE CODE IS INCORRECT AND HAS A UNBALANCED ')'. I DON'T FIND THIS MISTAKE UNTIL I RUN THE CODE__

The following code can not be formatted properly:

```dart
void main() {
List<int> list = [1, 2, 3];
Map<String, int> map = new Map.fromIterable(list,
    key: (item) => item.toString(),
    value: (item) => item * item));
}
```

By pressing "Ctrl+Shift+I" in linux, it does nothing. expected result should look like:

```dart
void main() {
  List<int> list = [1, 2, 3];
  Map<String, int> map = new Map.fromIterable(list,
      key: (item) => item.toString(),
      value: (item) => item * item));
}
```

# Second Issue

When the code can be formatted properly by pressing "Ctrl+Shift+i" in linux, whenever I press the format shortcut, it adds `}` char in the end of the code. why? Is this an expected feature? I am new to dart, so I am not sure. 

```dart
void main() {
  var x;
}
}
}
}
}
}
}
}
```

Note: `}` is created every time when I press "Ctrl+Shift+i" to format the document.

**Comment by DanTup** [comment]
Unfortunately I can't repro this issue on Windows or Mac (I don't have Linux set up currently).

If your code has syntax errors, then format won't do anything, so after the first `}` is inserted the format command then shouldn't do anything.

Do you have any other extensions that might interfere with this?

If not, could you try enabling the `dart.analyzerLogFile` (see [here](https://github.com/Dart-Code/Dart-Code/blob/master/CONTRIBUTING.md#enable-logging)) and then reproducing the issue, and find the relevant parts (the `edit.format` request and response) and attach them here?

Thanks!

**Comment by DanTup** [comment]
I'm tidying up open issues that I can't repro and need more info. If you still have this issue and can provide the info above then please post back and I'll re-open and investigate this.
