### ISSUE TITLE
Snippets import implementation files which dartfmt says not to do

### ISSUE THREAD

**Issue by satvikpendem** [Dart-Code/Dart-Code#4201]
**Describe the bug**
When I use a snippet like `stless`, the snippet is generated but then dartfmt complains, "_Don't import implementation files from another package. dart([implementation_imports](https://dart-lang.github.io/linter/lints/implementation_imports.html))_"

**To Reproduce**
1. Go to a Dart file in VSCode
2. Type `stless` and press enter. A snippet should expand into code.
3. At the top or in the Problems panel, notice that Dart shows the above warning.

**Expected behavior**
I would expect that the snippet imports `material.dart` or `widgets.dart` rather than internal implementation files.

**Screenshots**
![image](https://user-images.githubusercontent.com/42670561/194058640-c816315b-e35d-4fd7-aa27-64176ea6d947.png)

**Please complete the following information:**
 - Operating System and version: Windows 11
 - VS Code version: 1.71.2
 - Dart extension version: 3.50.0
 - Dart/Flutter SDK version: 3.3.3
 - Target device (if the issue relates to Flutter debugging): NA

**Comment by DanTup** [comment]
Thanks for the report! This is a known issue being tracked at https://github.com/dart-lang/sdk/issues/49081.
