### ISSUE TITLE
debugging session unusable if local variable is too large

### ISSUE THREAD

**Issue by woprandi** [Dart-Code/Dart-Code#4205]
**Describe the bug**
When trying to debug app, if a local variable representing a very long list (list of 100M file bytes), the debugging session is not usable and often crash 

**To Reproduce**
1. Create a local big file (on Linux : `dd if=/dev/zero of=my_big_file bs=100M count=1`)
2. Create a small dart app to read this file : 

```dart
import 'dart:io';

void main() async {
  final bytes = await File('my_big_file').readAsBytes();
  final myVar = "foo";
  final myVar2 = "bar";
  final myVar3 =  "";
}
```

3. Add breakpoint on line 5 or 6
4. Run app in debug mode

On left side, it's not possible to see local variables (infinite loading) or go to next line. The session will crash few seconds later. 
```
Connecting to VM Service at http://127.0.0.1:37661/g8bL_J7yzYI=/
Exited (sigint)
```

Due to  its size, the `bytes` variable prevent debug next lines.

**Expected behavior**

Have a usable debugging session

**Screenshots**

**Please complete the following information:**
 - Operating System and version: Fedora 36
 - VS Code version: 1.71.2
 - Dart extension version: v3.50.0
 - Dart/Flutter SDK version: Flutter 3.3.3 / Dart 2.18.2
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
This fix is in the SDK so it'll show up in a future SDK release. It's also limited to the new debug adapters (currently behind a flag `dart:previewNewSdkDaps`, but will hopefully be progressively rolled out after the next SDK release).
