### ISSUE TITLE
Jump to widget creation location when clicking on widget in inspector

### ISSUE THREAD

**Issue by blaugold** [Dart-Code/Dart-Code#4210]
**Is your feature request related to a problem? Please describe.**
Clicking on a widget in the widget inspector of the devtools also moves the focus of the editor to the creation location of the widget in Android Studio.

**Describe the solution you'd like**

https://user-images.githubusercontent.com/5929595/194718499-cefeca82-83f6-4c4c-98e5-477a15f5a41f.mov

Please ignore that the focus jumps between `Center` and what looks like the method `padding` on `Text`. I just came across this issue while working on a feature to extend widget tracking.

**Comment by blaugold** [comment]
OK, so this feature already exists, it just seems not to work on the channels other than stable. I tried it with the beta and master channel, both with the pre-release (`v3.51.20221003`) and the stable release (`v3.50.0`) of Dart-Code.

**Comment by blaugold** [comment]
🤦 Closing as duplicate of #4193.

**Comment by DanTup** [comment]
You're right, this is the same as #4193. This functionality was unfortunately missed from the new debug adapters, which are now enabled on the Flutter pre-release channels.

If you'd like to use a pre-release channel but not hit this, you can disable the new debug adapters by adding `"dart.previewSdkDaps": false` to your VS Code settings.

You can subscribe to #4193 for updates when this is resolved in the new adapters. Sorry for the bother!

**Comment by blaugold** [comment]
Oh, no problem. I should have searched the issues properly!

And thanks for the workaround.
