### ISSUE TITLE
Include type arguments in Type Hierarchy

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#4217]
```dart
class A extends B<String> {}
class B<T> {}
```

When browsing the hierarchy from A, we see a node for `B` but it doesn't include `<String>` (or `<T>`).

**Comment by dupuchba** [comment]
Is there anyway I can help ? I've worked quite a lot with the analyzer API

**Comment by DanTup** [comment]
Right now this is blocked on me finishing https://dart-review.googlesource.com/c/sdk/+/264300 (which is blocked on another change I'm working on). I'm hoping to get them done fairly soon, though.

**Comment by DanTup** [comment]
@bwilkerson with the ability to round-trip element locations, I had a look at this. Including the type arguments for the "next level" works fine because from an element when we get its supertypes/subtypes we have the type arguments (in an `InterfaceType`).

However, since we then only round-trip an element reference, those type args are lost in subsequent hops:

![Screenshot 2022-10-20 at 14 57 34](https://user-images.githubusercontent.com/1078012/196970682-5021e29e-6879-466a-b513-b43c776f767a.png)

I guess it turns out that really I wanted to tround-trip the `InterfaceType` rather than the `Element`. Is there anything existing that might help with this, or do you have any suggestions for what might be a reasonable way? (I may still send what I've got so far in the meantime since I think this behaviour is probably still an improvement over not showing any type args at all).

**Comment by DanTup** [comment]
> If the list of supertypes is stable then the path could just be the indexes into the lists of children.

Interesting idea. I don't think we can guarantee they're stable (the type hierarchy nodes are long-lived on the client) but we could compare the new type we arrive at with the element location and ensure they still match up. If they don't, we could fall back to just showing the elements type parameters (as in the example above), but I think that will be an edge case (there's a Refresh button the user can use to re-sync the type hierarchy if they make changes that are likely to have affected its navigation, so having it sometimes go awry after changes is not unexpected).

I'll give it a go and see how it works.

**Comment by dupuchba** [comment]
ultra reactive ! I've been sick all day, I am feeling better and I'll take a look tomorrow

**Comment by DanTup** [comment]
This changed landed in https://github.com/dart-lang/sdk/commit/27ba8fce6c73f23e221d8437529c73716938ce94. It's part of the SDK so will show up in a future Dart/Flutter SDK release.
