### ISSUE TITLE
Refactor Preview panel is always showed when renaming files

### ISSUE THREAD

**Issue by warcayac** [Dart-Code/Dart-Code#4219]
**Describe the bug**
When renaming any Dart file on *Folders* panel in VSCode, I get the *Refactor Preview* panel being showed to confirm changes to occur even when *editor.rename.enablePreview* is set to *False*.

**To Reproduce**
1. Open a Dart/Flutter project
2. Go to *Folders* panel 
3. Right click on any Dart file
4. Select ***Rename...* option
5. Rename the file without altering file extension by pressing *Enter* key
6. *Refactor Preview* panel is showed at bottom by requesting a confirmation to apply changes onto other files importing the Dart file being renamed

These values are set in my **settings.json**:
```
  "[dart]": {
    "editor.rename.enablePreview": false,
  },
  "editor.rename.enablePreview": false,

```
This behavior does not occur when renaming any symbol for some Dart file. Moreover I've disabled other extensions in VSCode.

**Expected behavior**
Changes are applied automatically.

**Screenshots**
![output2](https://user-images.githubusercontent.com/7342885/195969035-77348d36-fd7a-426e-8638-cdd4b75abe77.gif)

**Please complete the following information:**
 - Operating System and version: EndeavourOS Linux x86_64, Kernel: 6.0.1-zen1-1-zen
 - VS Code version: 1.72.2
 - Dart extension version: 3.50.0
 - Dart/Flutter SDK version: Flutter 3.3.4, Dart 2.18.2
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
This behaviour is controlled by VS Code and not the extension. I believe the setting you're using is only for symbol renames, and all other refactors (which seems to include file renames/moves) have their own option (which oddly is not exposed as a setting). My guess is that you once clicked "Don't ask again" on this dialog and then Show Preview:

![image](https://user-images.githubusercontent.com/1078012/195981737-451d9e56-95f3-430e-8b54-6c87052bde68.png)

You can reset this by running the following code from the command palette:

![image](https://user-images.githubusercontent.com/1078012/195981792-792abdb5-cc3f-45d8-92ab-0f3c4152b20b.png)

Then you should be prompted with the dialog above again, and you can tick "Don't ask again" and click "OK" and then you shouldn't see this again.

Please let me know if that isn't the case (and if you think there should be a more obvious setting like there is for rename, I would file a VS Code issue requesting that, and post the link back here for others that discover this issue to go add their 👍 s). Thanks!
