### ISSUE TITLE
Vscode refactoring: Convert Getter to Method applied to "widget", applies also to all flutter SDK & pub cache files

### ISSUE THREAD

**Issue by nicolasmol** [Dart-Code/Dart-Code#4221]
Quite big warning, since doing this has opened hundreds of files from SDK/pub cache, in my Vscode, and (I don't which mistake I made) saved and corrupted all of them

![image](https://user-images.githubusercontent.com/61077647/195983625-4ce687f0-ec07-4d39-aec5-a7210a9bfb3e.png)

----
Linux mint 20.3
VS Code version: 1.72.2
Dart SDK version: 2.18.2 (stable) (Tue Sep 27 13:24:11 2022 +0200) on "linux_x64"
Flutter 3.3.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision eb6d86ee27 (il y a 10 jours) • 2022-10-04 22:31:45 -0700
Engine • revision c08d7d5efc
Tools • Dart 2.18.2 • DevTools 2.15.0

**Comment by DanTup** [comment]
Sorry for the hassle. I think VS Code should still allow you to "undo" changes made by refactors like that (if it doesn't, please file an issue so I can investigate).

Can you confirm exactly where you invoked this refactor? I can't see a code selection/caret in your screenshot and I can't get this refactor to show up in a similar location myself. I can see the server has some special handling to prevent _renaming_ items that are not defined inside your own workspace, but it looks like it might not cover other types of refactors.

**Comment by nicolasmol** [comment]
@DanTup over the "widget" word, in the "State" widget of a "StatefulWidget" one

**Comment by DanTup** [comment]
Working on a fix at https://dart-review.googlesource.com/c/sdk/+/264480.

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/ffe4a8c864a22b8f3fcf7bd983bc8280ce00c61f. The fix ships in the SDK so will show up as part of an SDK release rather than a Dart-Code release.
