### ISSUE TITLE
Implement type parameters in type hierarchy 

### ISSUE THREAD

**Issue by dupuchba** [Dart-Code/Dart-Code#4226]
hey, thanks awesome for this awesome library, below the problem we are trying to solve.

Context: I am one of the core maintainer of the ClojureDart compiler, we are running our own analyzer (to generate better code) using the analyzer API and we are switching to the LSP protocol (I could explain reasons here but it's not important for my question).

Basically you recently added the `typeHierarchy/supertypes` method and it's very good for our use case but I can't find how to retrieve typeParams informations.

for example  
![image](https://user-images.githubusercontent.com/911705/196746185-f0cf5ce1-3331-4584-9bb0-912c909993ce.png)

here there is no way to know that `MyMap` has inverted its type params with `MapBase`.
Do you know the process for me to bring it to the Dart SDK ?

Thanks a lot for your help

Baptiste

**Comment by DanTup** [comment]
Hey!

This is a limitation of the current Type Hierarchy. We're currently using the `name` label to re-locate the element back on the server as you expand nodes and it doesn't handle the type arguments.

I plan to fix this (it's being tracked in #4217), but I need to improve the way we locate elements on the server to disconnect it from the name (that way we can include specific type arguments in the label but still locate the "real" class).

Please subscribe to #4217 for updates, I will close that issue once this has been done. Thanks!

**Comment by dupuchba** [comment]
Thanks for your time
