### ISSUE TITLE
Typed characters sometimes appear behind closing labels

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#423]
Raised by @xster at https://github.com/Dart-Code/Dart-Code/issues/383#issuecomment-324431272

Minor UI issue: noticed it was possible to momentarily type text behind the labels.

![labels](https://user-images.githubusercontent.com/156888/29633236-7793b0ba-87fa-11e7-9313-8f654fe49c16.gif)

**Comment by DanTup** [comment]
I think this is going to need Code support... The idea of just attaching the label to the last character on the line is kinda flawed because the user can type there!

Opened https://github.com/Microsoft/vscode/issues/34441

**Comment by devoncarew** [comment]
Hey - just to provide some feedback about how IntelliJ / the Dart plugin there solves this:
- we can attach Inlays to the end of an offset, so typing chars will just push the Inlay to the right (Inlays are the IntelliJ mechanism for inserted synthetic text)
- in the Dart plugin, we ignore notifications for closing labels if we have unsent changes for that file (so, chars typed but not yet sent to the analysis server). Those unsent chars will be sent, processed by the analysis server, and we'll receive a new closing label notification for the file w/ correct offsets, so the system will catch up naturally w/ typing changes

**Comment by DanTup** [comment]
> we can attach Inlays to the end of an offset

In Code, if we attach to the end of the range, the labels appear there (eg. inline - like the original prototype did). This was considered undesirable so we wanted to anchor to the "end of the line", but Code doesn't support that so we had to anchor to the end of the character-currently-at-the-end-of-the-line - but this allows a user to type behind it :(

That said, I wonder if `DecorationRangeBehavior.ClosedOpen` would fix this - maybe new characters typed directly at the end would then extend the range instead. I'll try and test this!

> in the Dart plugin, we ignore notifications for closing labels if we have unsent changes for that file

In Dart Code we do something similar, but basically add a delay and throw away any notifications if another arrives within that period. I don't know if your solution might still have races - eg. if the server prepares some closing labels but before they're processed by you, the user types another key which then gets transmitted - then you receive the stale result? Possibly your buffering of keys introduces some delays that offsets this (similar to our delay). I think the best fix for that is https://github.com/dart-lang/sdk/issues/30301 though it might be a lot of effort for a few edge cases.

**Comment by devoncarew** [comment]
>  This was considered undesirable so we wanted to anchor to the "end of the line"

Yup, for my comment I meant that we were anchoring to the offset of the last char in a line.

In terms of buffering, I'm not certain that there aren't any race conditions, but we haven't seen any in practice, and they would be things that worked themselves out w/ the next analyzer notification.
