### ISSUE TITLE
Seems the analyzer doesn't work on MacOS Ventura

### ISSUE THREAD

**Issue by larssn** [Dart-Code/Dart-Code#4235]
**Describe the bug**
After updating to MacOS Ventura, VSCode seems to be stuck in "Analyzing...", and never finishes.

I've checked various Flutter projects, and they all have the same problem.

Anyone else seeing this?

**To Reproduce**
1. Update to MacOS Ventura
2. Open a Flutter project

**Expected behavior**
I expect the analyzer to finish.

**Please complete the following information:**
 - MacOS Ventura (13.0)
 - VS Code version: 1.72.2 (Universal)
 - Dart extension version: v3.51.20221010
 - Dart/Flutter SDK version: v2.10.0/3.0.5
 - Target device (if the issue relates to Flutter debugging):

**Comment by larssn** [comment]
Seems to be related to the Flutter version (we're behind - 3.0.5) and the contents of ~/.dartServer.
Deleting `.dartServer` makes the analyzer work again.

Doing a `flutter upgrade` breaks it again, until I once again delete `.dartServer`.

**Comment by DanTup** [comment]
Sorry for the delay, I've been out of the office. Am I right in thinking this is unrelated to the OS version then?

I did the following (on an Intel Mac, Monterey 12.6) but was unable to reproduce:

- deleted `~/.dartServer`
- `git checkout stable && git reset --hard 3.0.5 && flutter doctor` in the Flutter SDK
- `mkdir /tmp/dc4235 && cd /tmp/dc4235 && flutter create my_app && code my_app`
- ensured everything analyzed correctly and I could interact with server
- `flutter upgrade && code my_app` (this upgraded to 3.3.6)
- analysis seemed to work fine still, interactions with server worked

Are there any other steps I'm missing? Also, could you enable the [analyzer log](https://dartcode.org/docs/logging/#analyzer) and see whether there's any exception or similar in it when the analysis server seems to stop responding?

In case it is OS version related, I'll try to upgrade my personal macbook in the next few days to ensure it's not totally bust before doing my work one (although, the personal one is an M1 and this is Intel so it's not totally like-for-like - I'm not sure which yours is?)

**Comment by larssn** [comment]
It could be OS related yes, since it only started after upgrading to Ventura.

I usually use `flutter downgrade 3.0.5`, but your approach might work too. 🙂

There was an update for the `analyzer` today, which "might?" have fixed it, because I tried upgrading to 3.3.6, and this time I didn't need to delete `.dartServer`.

Guess we can close in a few days if everything is peachy.

**Comment by DanTup** [comment]
I guess you mean an update for Flutter? I can't see anything in [3.3.5 -> 3.3.6](https://github.com/flutter/flutter/compare/3.3.5...3.3.6) that should affect this so I suspect if you can't reproduce it it's just intermittent. If you happen to see it again and are able to get a log, please do let me know!

**Comment by larssn** [comment]
No I mean the analyzer as a transitive dependency. Flutter 3.0 depended on version 4 of the analyzer.

```
analyzer:
    dependency: transitive
    description:
      name: analyzer
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.2.0"
```

Anyway, I won't take anymore of your time.

**Comment by DanTup** [comment]
> No I mean the analyzer as a transitive dependency. Flutter 3.0 depended on version 4 of the analyzer.

Oh, I see. That won't affect the analyzer used by VS Code - it will always use the `dart language_server` command which is the same for a given SDK version regardless of versions in your project (or the `flutter` tool).


> Anyway, I won't take anymore of your time.

My time is there to be taken if there may be issues :-) If you do see it again or can repro, do let me know. I've updated my M1 MacBook to Ventura now so if you're able to repro and can provide exact steps I'm happy to do some testing to see if I can track down what happened. Thanks!
