### ISSUE TITLE
Launch  a specific  project with releaseMode  in a workspace by hitting ctrl+shift+b

### ISSUE THREAD

**Issue by dbsxdbsx** [Dart-Code/Dart-Code#4245]
**Is your feature request related to a problem? Please describe.**
When There is  only 1 project, with such `launch.json` (no tasks.json):
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "My_App",
            "request": "launch",
            "type": "dart",
            "cwd": "${workspaceFolder}",
        },
        {
            "name": "My_App(release mode)",
            "request": "launch",
            "type": "dart",
            "flutterMode": "release",
            "cwd": "${workspaceFolder}",
        }
    ]
}
```
The dart/flutter project can be run in debug mode with `F5` and release mode with  `ctrl+shift+b`.
But if there are multiple projects in a workspace( some others may not be dart projects),  though the specific dart project can be run in debug mode by hitting `F5` with specifying the corresponding launch file in `Run and Debug Explorer`, it can't be run in the release mode by hitting  `ctrl+shift+b`--- vscode would just run another project which has a complete `tasks.json` file.

**Describe the solution you'd like**
I hope there is a command that could generate all acquired files (maybe the missing tasks.json?) for any dart/flutter project, in which specified at least debug and release tasks. So that even in a workspace, users can easily doing debug and release building by easily hitting `F5` and  `ctrl+shift+b` after choosing the specified launch file.

**Describe alternatives you've considered**
I've tried to build `tasks.json` manually but failed.  Because I don't know how to add "device" in the command, be the Os is windows or Linux.

**Comment by DanTup** [comment]
> The dart/flutter project can be run in debug mode with `F5` and release mode with `ctrl+shift+b`.

Actually, pressing `Ctrl+Shift+B` is not a shortcut for running release mode that I know of. Ctrl+Shift+B is a shortcut for the "Run Build Task" in VS Code. If I press this in a single-project workspace then I'm just prompted to select a build task:

<img width="671" alt="Screenshot 2022-11-07 at 11 57 09" src="https://user-images.githubusercontent.com/1078012/200304535-07b3e0a4-de2b-4164-807a-38af2763467c.png">

There is a command to run in release mode in the palette:

<img width="464" alt="Screenshot 2022-11-07 at 11 58 12" src="https://user-images.githubusercontent.com/1078012/200304735-4455cd1c-e69a-458d-824a-1547dbcef958.png">

You could add your own keybinding to that, and it should run the project for the current open file when you invoke it.

To me, tasks (which are invoked with `Ctrl`+`Shift`+`B` by default) are not the correct way to start _Debug_ sessions. Debugging and tasks are very different things in VS Code - tasks can run commands (either short-live or long-lived) but they do not (typically) start debug sessions.

So I guess I have two questions:

1. Why does `Ctrl`+`Shift`+`B` seem to start a release mode debug session for you?
2. Does adding a key-binding for the **Run App in Release Mode** command address your need?

**Comment by dbsxdbsx** [comment]
> 

Sorry for the late reply.  

For Q1:
Currently, `Ctrl`+`Shift`+`B` is left by default in vscode, which is used for "Tasks: Run Build Task".  And generally, I would manually create `tasks.json` and `launch.json` for easy running under both debug and release modes.

For example, in a  project made by rust, some part of `tasks.json` is like this:
```json
 {
            "label": "runBuiltProgram",
            "type": "shell",
            "command": "cd ./target/release/; ./xiangqi_engine",
  }
```
With this, the binary program would be built and launched in release mode with `Ctrl`+`Shift`+`B`.  And if I just want to debug, `F5` is enough.   

For Q2:
Yes, after adding for command "Run App in Release Mode" it does run the flutter/dart project in release mode, but if the keybinding is  `Ctrl`+`Shift`+`B`, then it would override the default command.

Hopefully, the debug/release build behavior could be consistent over dart/flutter and other projects.

**Comment by DanTup** [comment]
Sorry, I'm a little confused about the request/issue.

In the first post it sounded like `Ctrl`+`Shift`+`B` was already launching in release mode for you, but only if there's just a single project (and not if there are multiple).

However I can't reproduce this and the latest comment makes it seem like this is a request to support setting up tasks to do this, as you can in Rust. Although I believe the same thing you have for Rust should be possible in Flutter (by using `flutter build` and/or `flutter run` in tasks).

However there is a fairly significant difference between tasks and "running" and I don't think providing built-in tasks to _run_ Flutter apps makes a lot of sense as there is already _Run_ functionality specifically for running apps (which the command I noted above uses). Tasks are intended for general execution of commands and in particular, the build task is for building (and not running).

Do you know of any other types of projects besides Rust that use Tasks for running project?

**Comment by dbsxdbsx** [comment]
> Sorry, I'm a little confused about the request/issue.
> 
> In the first post it sounded like `Ctrl`+`Shift`+`B` was already launching in release mode for you, but only if there's just a single project (and not if there are multiple).
> 
> However I can't reproduce this and the latest comment makes it seem like this is a request to support setting up tasks to do this, as you can in Rust. Although I believe the same thing you have for Rust should be possible in Flutter (by using `flutter build` and/or `flutter run` in tasks).
> 
> However there is a fairly significant difference between tasks and "running" and I don't think providing built-in tasks to _run_ Flutter apps makes a lot of sense as there is already _Run_ functionality specifically for running apps (which the command I noted above uses). Tasks are intended for general execution of commands and in particular, the build task is for building (and not running).
> 
> Do you know of any other types of projects besides Rust that use Tasks for running project?

For the rust, I made the build task myself, not by any extension.  Before, I also running project by tasks in C++ project.  

And sorry for the confusing part, it is not command "Run App in Release Mode" when hitting  `Ctrl`+`Shift`+`B`, but several commands like :"flutter: flutter build windows/aar.....".

Now, I think the best way to build flutter/dart project in release mode is  by the command "flutter: flutter build windows/aar.....", or  I could manually build it in shell with the command "flutter run --release", and then manually choose the target platform. It would be better if only the choice behavior could be put into `tasks.json`. But I didn't find it.

**Comment by DanTup** [comment]
If you use the "Run Task" command and select Flutter, you should be able to click the cog icon on the right to copy that item to `tasks.json`:

<img width="698" alt="Screenshot 2022-11-09 at 13 26 59" src="https://user-images.githubusercontent.com/1078012/200842525-4c997025-81ea-44fd-8eaf-afbfbaaa7856.png">

There should be a `build` task for each platform that's valid. You should then be able to set it as a build task (or I think if you press `Ctrl`+`Shift`+`B` without a build task set, it will ask you which one). Does this do what you're looking for? If not, or it doesn't work as you'd expect, please let me know and we can try to improve it.

**Comment by dbsxdbsx** [comment]
@DanTup, thanks for your advice.  I tried, and find it convenient to build in release mode by  `Ctrl`+`Shift`+`B`, without setting any hotkey.  But this only happened  with a single project.  If there is more than 1 project in a workspace and with more than 1 `tasks.json`,   vscode would still trigger other task by `Ctrl`+`Shift`+`B`.

**Comment by DanTup** [comment]
@dbsxdbsx can you clarify exactly what happens when you press `Ctrl`+`Shift`+`B` with a single project open? I see this:

<img width="644" alt="Screenshot 2022-11-14 at 17 23 11" src="https://user-images.githubusercontent.com/1078012/201725391-3fe15c2c-fe41-4a2c-a02f-149c68464eda.png">

And if I do the same with multiple workspace folders, I see this:

<img width="671" alt="Screenshot 2022-11-14 at 17 24 30" src="https://user-images.githubusercontent.com/1078012/201725650-faf8dfc5-4eb9-4ae7-a335-85e3e9603ea5.png">

These seem to be functioning the same to me (although it looks awkward that VS Code is adding `(1)`, `(2)` on the end where the names are duplicated for the different projects).

I presume you are seeing something different - can you explain/record what you see?

**Comment by dbsxdbsx** [comment]
> @dbsxdbsx can you clarify exactly what happens when you press `Ctrl`+`Shift`+`B` with a single project open? I see this:
> 
> <img alt="Screenshot 2022-11-14 at 17 23 11" width="644" src="https://user-images.githubusercontent.com/1078012/201725391-3fe15c2c-fe41-4a2c-a02f-149c68464eda.png">
> 
> And if I do the same with multiple workspace folders, I see this:
> 
> <img alt="Screenshot 2022-11-14 at 17 24 30" width="671" src="https://user-images.githubusercontent.com/1078012/201725650-faf8dfc5-4eb9-4ae7-a335-85e3e9603ea5.png">
> 
> These seem to be functioning the same to me (although it looks awkward that VS Code is adding `(1)`, `(2)` on the end where the names are duplicated for the different projects).
> 
> I presume you are seeing something different - can you explain/record what you see?

When there is only 1 flutter project, I see this:
![1 DART](https://user-images.githubusercontent.com/17372655/201815089-e8ddd621-5e4b-43e8-84c9-543ca58d5675.png)

When there is 1 flutter project with 1 rust project, I see this:
![MULTI_DART](https://user-images.githubusercontent.com/17372655/201815156-84d3b3f3-6dbe-428b-9ccd-c7e82fbc5a47.png)

The flutter project contains only `launch.json`, which is generated by flutter extension:
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "My_App",
            "request": "launch",
            "type": "dart",
            "cwd": "${workspaceFolder}",
        },
        {
            "name": "My_App(release mode)",
            "request": "launch",
            "type": "dart",
            "flutterMode": "release",
            "cwd": "${workspaceFolder}",
        }
    ]
}
```
While the rust project contains both `launch.json` and `tasks.json`, which I wrote manually.
The `launch.json` looks like this:
```json
{
    "version": "0.2.0",
    "configurations": [{
        "preLaunchTask": "DebugBuild",
        "requireExactSource": false,
        "name": "(Windows) Debug",
        "type": "cppvsdbg",
        "request": "launch",
        "program": "${workspaceFolder}/target/debug/xiangqi_engine",
        "args": [],
        "stopAtEntry": false,
        "cwd": "${fileDirname}",
        "environment": [],
        "console": "integratedTerminal",
        //"logging": {
        //    "trace": true,
        //    "traceResponse": true,
        //    "engineLogging": true
        //}
        // "postDebugTask": "Terminate All Tasks"
    }]
}
```

**Comment by dbsxdbsx** [comment]
> @dbsxdbsx thanks for clarifying
> 
> > When there is 1 flutter project with 1 rust project, I see this:
> 
> My understanding is that what's happening here is VS Code functionality and not something Dart/Flutter can influence. In the first case (just Flutter project), you have no "build tasks" configured, so VS Code is asking all extensions for tasks, and then showing you a list of the results to see which to run.
> 
> In the second case with your first project, you have _explicitly_ configured tasks and VS Code assumes you want to run those so it doesn't present you with a list of Dart/Flutter tasks. This is not something that the Dart/Flutter extension can change - all we can do is provide tasks when VS Code asks for them, we do not control what happens when you press `Ctrl`+`Shift`+`B`.
> 
> I think the best thing you can do is create a keybinding for the standard "Run Task" command, which I think will prompt you always to select a task. I don't think you can achieve what you want using the "Run Build Task" command (which is what `Ctrl`+`Shift`+`B` is bound to). Alternatively, you could create explicit tasks for the Flutter builds you want, and if they're also marked as _build_ tasks, VS Code will perhaps let you pick between those when you invoke the build task command.
> 
> Hope this makes sense!

Yes, both 2 approaches should be workable, and I prefer the latter approach. Thank you for your advice.

**Comment by dbsxdbsx** [comment]
@DanTup, Oh~ Just one thing to mention.  Even I added `tasks.json` for the flutter project:
```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "flutter",
			"command": "flutter",
			"args": [
				"build",
				"windows"
			],
			"group": "build",
			"problemMatcher": [],
			"label": "flutter: flutter build windows",
			"detail": ""
		}
	]
}
```
In the workspace of multi projects,   pressing `ctrl`+`shift`+`b` would still launch the rust project, with no asking.

**Comment by dbsxdbsx** [comment]
@DanTup, thanks for your experiment.   Now after testing myself, I got same result your `tasks.json`, And I also realize that the issue is from this `tasks.json`:
```json
{
    "version": "2.0.0",
    "tasks": [
        //task for debug
        {
            "label": "DebugBuild",
            "dependsOn": [
                "checkIfBuildFolderExists",
                "DebugBuildTask"
            ],
            "dependsOrder": "sequence",
        },
        //task for release
        {
            "label": "ReleaseBuild",
            "dependsOn": [
                "checkIfBuildFolderExists",
                "ReleaseBuildTask",
                "runBuiltProgram"
            ],
            "dependsOrder": "sequence",
            "group": {
                "kind": "build",
                "isDefault": true
            },
        },
        //
        //the below is subtask
        {
            "label": "checkIfBuildFolderExists",
            "type": "shell",
            "windows": {
                "command": "cmd",
                "args": [
                    "/C",
                    "if not exist .\target mkdir .\target",
                ],
            },
            "linux": {
                "command": "mkdir -p target",
            },
            "presentation": {
                "reveal": "silent",
                "close": false
            },
        },
        {
            "label": "DebugBuildTask",
            "type": "shell",
            "command": "cargo build",
            "presentation": {
                "reveal": "always",
                "close": false
            },
        },
        {
            "label": "ReleaseBuildTask",
            "type": "shell",
            "command": "cargo build --release",
            "presentation": {
                "reveal": "always",
                "close": false
            },
            // "problemMatcher":
        },
        {
            "label": "runBuiltProgram",
            "type": "shell",
            "windows": {
                "command": "cd ./target/Release/; ./test_rust",
                "options": {
                    "shell": {
                        "executable": "powershell",
                    }
                }
            },
            "linux": {
                "command": "cd ./target/Release/ && ./test_rust",
            },
        }
    ]
}
```
Could you plz test it within `.vscode` of ANY project? I guess you would find that this task overrides other projects in a workspace.

**Comment by dbsxdbsx** [comment]
@DanTup, Oh~ I got it. The reason is that in my special `tasks.json`: it marked `"isDefault": true`, that is why it would override other tasks.

**Comment by DanTup** [comment]
> The reason is that in my special `tasks.json`: it marked `"isDefault": true`

Ah, that makes sense. I presume when you remove that everything is working as you'd like?

**Comment by dbsxdbsx** [comment]
> presume

Yes. And if there are more than 1 marked `"isDefault": true`, then vscode would ask which task to choose.

**Comment by DanTup** [comment]
Ah, perfect :-)
