### ISSUE TITLE
Disable override of inlay hints setting

### ISSUE THREAD

**Issue by Zekfad** [Dart-Code/Dart-Code#4247]
**Describe the bug**
Due to override (#4162) you can't change behavior of that setting at all.

**To Reproduce**
1. Change Inline Hints setting
2. Changes ignored due to override

**Expected behavior**
I expect this setting to follow user choice.

**Please complete the following information:**
 - Operating System and version: Microsoft Windows [Version 10.0.19044.2130]
 - VS Code version: 1.73.0 8fa188b2b301d36553cbc9ce1b0a146ccb93351f x64
 - Dart extension version: v3.53.20221102
 - Dart/Flutter SDK version: Dart 2.19.0 (build 2.19.0-372.0.dev) / Flutter 3.5.0-12.0.pre.111

**Comment by DanTup** [comment]
You can still override this, but you need to do it at the language level:

```js
"[dart]": {
		"editor.inlayHints.enabled": "off",
}
```

Unfortunately VS Code does not provide a way for extensions to provide defaults that are overwritten by any user preference, they can only be overridden with a language-specific config.

Hope this helps - please let me know if you still have issues. Thanks!
