### ISSUE TITLE
Add support for multi-root workspaces

### ISSUE THREAD

**Issue by Aetet** [Dart-Code/Dart-Code#425]
Is there any support for multi-root workspaces:
https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs
for dart code? 

I use dart code across 5-8 projects at the same time. It would be useful to execute refactorings, go to code inside all of them at once.

**Comment by DanTup** [comment]
It's not supported yet, but I do plan to look into it.

To be sure I understand - are you using the multiroot feature in insiders and things like cross-project go-to-def doesn't work correctly?

If you open as a single workspace (eg the parent folder of they're siblings) does this work?

I need to find some time to test out how it works and decide how best to handle it - if been waiting for it to be a bit more stable before doing so, but seems like it's getting there in the latest update!

**Comment by Aetet** [comment]
@DanTup I'm not using multi root actually. But plan this after it'll be stable. Thanks.

**Comment by DanTup** [comment]
@Aetet Ok, for now if you open a workspace with multiple projects inside it then it *should* just do what you want (though unlike with the upcoming multi-root support, obviously your projects need to all be alongside each other). Have you tried this; have you had anything not work?

(When multiroot support goes stable, I do plan to add good support for that too, but there are still a bunch of questions about how it should work - such as whether Dart Code should host multiple instances of the analysis server, or just one, etc.!).

**Comment by DanTup** [comment]
I've moved this to #453 since it's going to be much more work than I expected, so the issues/notes are going to become somewhat large!
