### ISSUE TITLE
Vs code Dart/Flutter program auto exit

### ISSUE THREAD

**Issue by josercc** [Dart-Code/Dart-Code#4251]
VS code running Dart Command app will automatically exit in Debug, and running Flutter app will also exit in Hot reload

**Comment by DanTup** [comment]
Can you provide a small code sample of the Dart program you're running that is exiting?

Could you also capture a log:

- Press `F1` to open the VS Code command palette
- Search for the **Dart: Capture Debugging Logs** command and press `<enter>`
- Run the Dart command app and wait for it to exit
- Click **Cancel** on the logging notification to stop logging and open the log file
- Attach the log file here or in a Gist

Be sure to remove anything sensitive from the log before sharing.

Thanks!

**Comment by josercc** [comment]
@DanTup 

Yes, this is not easy to reproduce. Before that, VSCode would reproduce every time, but it would not run in Android Studio. I reinstalled the VSCode version. The plug-in only keeps Flutter and Dart plug-ins running the same code. I haven't encountered it yet. I will provide useful information if I encounter it later. Before Dart command line, the code was analyzed through Analyzer. When Debug prints object information, it often exits.

**Comment by DanTup** [comment]
If you're able to reproduce this while capturing a log as described above, that might help understand why it quits.

Can you also confirm the exact version of Dart/Flutter you're using? (running the **Flutter: Run Flutter Doctor** command from the VS Code command palette (`F1`) is the best way, as it ensures you get the version VS Code is using, and not only the one on `PATH`).

**Comment by josercc** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.5 21G72 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.74.0-insider)
[✓] VS Code (version 1.74.0-insider)

**Comment by DanTup** [comment]
Thanks! I don't know if it's related to your issue, but there have been a few releases since version 2.10.5 that you're using. The current stable version of Flutter is v3.3. It's possible that your issue has been fixed in the SDK already, so I would recommend trying to upgrade to a newer version of Flutter when it's convenient. Issues that cause debug sessions to terminate are often caused by the Dart VM terminating, and often the fix for those is inside the Dart SDK itself.

Do let me know if the issue does come back and you still experience it on the current stable SDKs. A log file as described above may help track down the issue.

Thanks!

**Comment by josercc** [comment]
At present, our project has not been upgraded to 3.3 because it was found that many dependent databases have not been adapted to 3.3, so it cannot be upgraded. Since the VS Code plug-in installed previously was deleted recently, there has been no crash. The AS will not crash again. It may be due to the impact of other plug-ins or other reasons

**Comment by DanTup** [comment]
Understood. Please let me know if the issue comes back and you're able to capture a log and we can re-open this. Thanks!

**Comment by josercc** [comment]
@DanTup The crash happened again, and it was over. I do this. After running the Flutter program, I want to press Command+on the following method body Perform the refactoring, and then crash and exit.

<img width="926" alt="image" src="https://user-images.githubusercontent.com/4713847/203460594-0a32af91-e8d0-41f0-bdff-ca9d3ac49a66.png">

The crash log captured below

[Dart-Code-Log-2022-10-03 10-43-14.txt](https://github.com/Dart-Code/Dart-Code/files/10072525/Dart-Code-Log-2022-10-03.10-43-14.txt)

**Comment by DanTup** [comment]
@josercc can you reliably reproduce this? There's nothing unusual in the log - it actually looks like VS Code sent a request to terminate the debug session:

<img width="903" alt="Screenshot 2022-11-23 at 11 47 09" src="https://user-images.githubusercontent.com/1078012/203539230-d8cacdd1-5414-40be-8ac0-74be2059c608.png">

There were some `Flutter.Frame` events up until 10:43:54 and then nothing until 10:44:08 when it appears that VS Code sent a terminate request.

Since you mention navigating in the editor, if you can reliably reproduce this it might be useful to capture a log that includes the non-debugger parts too:

- Run the app and get to the point you're ready to reproduce the issue
- Run the **Dart: Capture Logs** command
- Leave *everything* ticked and click OK
- Trigger the crash
- Click **Cancel** on the logging notification to stop logging and open the log file

Note: This log file may contain parts of your source code in the analyzer traffic.

**Comment by josercc** [comment]
@DanTup

I downloaded the VSCode InSiders version without crashing, but it must appear in the Release version. At present, I have developed in VSCode InSiders. According to this phenomenon, I feel it has something to do with VSCode

**Comment by DanTup** [comment]
@josercc so can you reliably reproduce it in the stable version? Do you have any differences in extensions between the two? It certainly seems odd that the logs suggest VS Code was asking for the session to be ended.

It's also worth clicking Help -> Toggle Developer Tools in VS Code, then going to the Console tab and seeing if any errors are listed there when this happens.

**Comment by josercc** [comment]
@DanTup 


I'll come in tomorrow and look at the reconstruction and see if there's any error logs

**Comment by josercc** [comment]
@DanTup 

<img width="760" alt="image" src="https://user-images.githubusercontent.com/4713847/203668070-2db03e59-c5a6-4894-ac03-9fd6086c18b5.png">

There are so many logs in the VSCode developer tool from running to crashing

**Comment by DanTup** [comment]
> There are so many logs in the VSCode developer tool from running to crashing

More than just those in your screenshot? Could you provide a screenshot of all of those that happened in a short period before the crash so I can see if they might be related?

**Comment by josercc** [comment]
@DanTup The screenshot above is all the information before the crash

**Comment by josercc** [comment]
[Dart-Code-Log-2022-10-01 19-47-44.txt](https://github.com/Dart-Code/Dart-Code/files/10103313/Dart-Code-Log-2022-10-01.19-47-44.txt)

The above log information exits after the breakpoint during debugging

**Comment by DanTup** [comment]
@josercc that last log seems different to the previous one. In the previous one it appeared that VS Code asked the debugger to terminate the session, but in this one it seems like the process terminated with a sigkill while trying to evaluate an expression:

```
[7:47:58 PM] [DAP] [Info] <== {"command":"evaluate","arguments":{"expression":"templateCode","frameId":1,"context":"hover"},"type":"request","seq":14}
[7:47:58 PM] [DAP] [Info] ==> {"seq":1634,"type":"event","event":"dart.log","body":{"message":"==> {\"id\":\"784\",\"jsonrpc\":\"2.0\",\"method\":\"evaluateInFrame\",\"params\":{\"disableBreakpoints\":true,\"expression\":\"templateCode\",\"frameIndex\":0,\"isolateId\":\"isolates/2882066305390979\"}}\n","severity":0,"category":11}}
[7:47:58 PM] [VmService] [Info] [test parser] ==> {"id":"784","jsonrpc":"2.0","method":"evaluateInFrame","params":{"disableBreakpoints":true,"expression":"templateCode","frameIndex":0,"isolateId":"isolates/2882066305390979"}}
[7:47:58 PM] [DAP] [Info] ==> {"seq":1635,"type":"event","event":"dart.log","body":{"message":"Process exited (sigill)","severity":0,"category":11}}
[7:47:58 PM] [DAP] [Info] ==> {"seq":1636,"type":"event","event":"output","body":{"category":"console","output":"Exited (sigill)\n"}}
[7:47:58 PM] [DAP] [Info] ==> {"seq":1637,"type":"event","event":"terminated"}
[7:47:58 PM] [VmService] [Info] [test parser] Process exited (sigill)
```

This appears to have happened when you hovered over `templateCode` in the editor and we tried to evaluate its value. Can you reproduce this issue in a small sample project that you can share? I presume this issue still occurs in Insiders too?

**Comment by josercc** [comment]
@DanTup 

[winner_model_parse.zip](https://github.com/Dart-Code/Dart-Code/files/10108639/winner_model_parse.zip)


You can run the test crash program. The screenshot breakpoint below

<img width="1108" alt="image" src="https://user-images.githubusercontent.com/4713847/204408818-fd1ddc39-c3cc-4e73-93c0-6beb0d2fd487.png">


Hover over the variable above the breakpoint to exit abnormally

**Comment by DanTup** [comment]
@josercc it seems like this project depends on some other packages that aren't available to me (ide_plugin, winner_ide_config, etc.)

Are you able to to trim this down to something smaller that I can run? Thanks!

**Comment by josercc** [comment]
> @josercc it seems like this project depends on some other packages that aren't available to me (ide_plugin, winner_ide_config, etc.)
> 
> Are you able to to trim this down to something smaller that I can run? Thanks!

[winner_model_parse.zip](https://github.com/Dart-Code/Dart-Code/files/10128254/winner_model_parse.zip)

**Comment by josercc** [comment]
> I had t modify some paths to get the code to run, but I wasn't able to reproduce the crash - hovering over those variables seems to work:
> 
> <img alt="Screenshot 2022-12-01 at 15 05 14" width="613" src="https://user-images.githubusercontent.com/1078012/205087458-efa945c4-7334-4485-9c79-d3b8694633af.png">
> 
> <img alt="Screenshot 2022-12-01 at 15 05 26" width="617" src="https://user-images.githubusercontent.com/1078012/205087465-ab3ef47b-5453-4a12-8e59-c359a4ac4562.png">
> 
> However, I noticed you're on Flutter 2.10 and there have been many fixes between that and the current stable version (v3.3.9). I wonder if perhaps this issue has been fixed since - are you able to test if you can still reproduce it using the latest stable version?

I use fvm use 3.3.2 - f After using Flutter 3.3.2, the crash is the same as before

**Comment by josercc** [comment]
I will use the project I sent you to run a direct command line program without any real machine or simulator

**Comment by josercc** [comment]
Now we also found a problem in adding Realm dependencies to a Dart Command program. Realm requires Flutter 3.0 to run. I set `fvm global 3.3.2` execute `dart run bin/realm_manager.dart` can run。

But I report an error when running through the vscode configuration
```dart
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "realm_manager",
            "request": "launch",
            "type": "dart",
            "program": "bin/realm_manager.dart"
        }
    ]
}
```

```shell
Null check operator used on a null value
#0      BinaryPrinter._getVariableIndex (package:kernel/binary/ast_to_binary.dart:83:17)
#1      BinaryPrinter.visitVariableGet (package:kernel/binary/ast_to_binary.dart:1497:17)
#2      VariableGet.accept (package:kernel/ast.dart:4137:44)
#3      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:430:10)
#4      BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:340:7)
#5      BinaryPrinter.visitArguments (package:kernel/binary/ast_to_binary.dart:1751:5)
#6      Arguments.accept (package:kernel/ast.dart:5119:38)
#7      BinaryPrinter.writeArgumentsNode (package:kernel/binary/ast_to_binary.dart:444:10)
#8      BinaryPrinter.visitStaticInvocation (package:kernel/binary/ast_to_binary.dart:1734:5)
#9      StaticInvocation.accept (package:kernel/ast.dart:6289:44)
#10     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:430:10)
#11     BinaryPrinter.visitExpressionStatement (package:kernel/binary/ast_to_binary.dart:2052:5)
#12     ExpressionStatement.accept (package:kernel/ast.dart:8829:43)
#13     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:430:10)
#14     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:340:7)

```

Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.5 21G72 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.73.1)
[✓] VS Code (version 1.74.0-insider)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by DanTup** [comment]
@josercc

> Now we also found a problem in adding Realm dependencies to a Dart Command program

that sounds like a different issue - I would file that at https://github.com/dart-lang/sdk with repro instructions.


> I will use the project I sent you to run a direct command line program without any real machine or simulator

Are you able to provide a repro I can run without modifications (or describe exactly what modifications I should make)? I had to make changes to your previous repro to make it work (because it contains several paths that didn't exist) and I don't know if I made them correctly.

**Comment by josercc** [comment]
@DanTup 

My local operation is also the same as the project just mentioned The library under the switch directory is a bit strange. When I use Android Studio, whether the current crash or adding Realm does not exist, it can run normally. However, the values of variables viewed in the Debug mode by Android Studio are not as comprehensive as VSCode.

**Comment by DanTup** [comment]
@josercc here is some changes I had to make to make the application run, but I don't know if the files I changed them too would trigger the issue (it wasn't clear to me which files were supposed to be used).

<img width="969" alt="Screenshot 2022-12-07 at 13 17 01" src="https://user-images.githubusercontent.com/1078012/206189128-60c1a51e-5e4b-43be-9c3a-a22a1a424871.png">

With those changes, I still was unable to reproduce the issue so have not been able to debug.


If the realm_manager issue only occurs from VS Code, please file an additional issue in this repo (https://github.com/Dart-Code/Dart-Code/issues/new/choose) and include exact steps to reproduce this. I don't think it's the same issue as this crash, but if it's only occurring from VS Code then it makes sense for me to take a look before sending to the SDK repository. Thanks!

**Comment by josercc** [comment]
> @josercc here is some changes I had to make to make the application run, but I don't know if the files I changed them too would trigger the issue (it wasn't clear to me which files were supposed to be used).
> 
> <img alt="Screenshot 2022-12-07 at 13 17 01" width="969" src="https://user-images.githubusercontent.com/1078012/206189128-60c1a51e-5e4b-43be-9c3a-a22a1a424871.png">
> 
> With those changes, I still was unable to reproduce the issue so have not been able to debug.
> 
> If the realm_manager issue only occurs from VS Code, please file an additional issue in this repo (https://github.com/Dart-Code/Dart-Code/issues/new/choose) and include exact steps to reproduce this. I don't think it's the same issue as this crash, but if it's only occurring from VS Code then it makes sense for me to take a look before sending to the SDK repository. Thanks!

I have modified the code inside, and it should be able to run without modification. The crash is still checking the debug variable, and it will exit immediately

[winner_model_parse.zip](https://github.com/Dart-Code/Dart-Code/files/10181171/winner_model_parse.zip)

**Comment by josercc** [comment]
@DanTup 

https://github.com/Dart-Code/Dart-Code/issues/4301#issuecomment-1343912151

After the above steps, the project will not crash during debugging

**Comment by josercc** [comment]
@DanTup press command + . crash still exit

After pressing, the log during VSCode debug exit is as follows
```
[+13495 ms] DevFS: Deleting filesystem on the device (file:///Users/king/Library/Developer/CoreSimulator/Devices/0E3648E7-5A63-41DA-A767-FB908BA7B4CA/data/Containers/Data/Application/CA3D7A3B-C88F-487A-B922-0016C63715BF/tmp/guilin_latex_pdavFkgW9/guilin_latex_pda/)
[   +5 ms] DevFS: Deleted filesystem on the device (file:///Users/king/Library/Developer/CoreSimulator/Devices/0E3648E7-5A63-41DA-A767-FB908BA7B4CA/data/Containers/Data/Application/CA3D7A3B-C88F-487A-B922-0016C63715BF/tmp/guilin_latex_pdavFkgW9/guilin_latex_pda/)
[   +1 ms] Application finished.
```

**Comment by josercc** [comment]
> @DanTup press command + . crash still exit
> 
> After pressing, the log during VSCode debug exit is as follows
> 
> ```
> [+13495 ms] DevFS: Deleting filesystem on the device (file:///Users/king/Library/Developer/CoreSimulator/Devices/0E3648E7-5A63-41DA-A767-FB908BA7B4CA/data/Containers/Data/Application/CA3D7A3B-C88F-487A-B922-0016C63715BF/tmp/guilin_latex_pdavFkgW9/guilin_latex_pda/)
> [   +5 ms] DevFS: Deleted filesystem on the device (file:///Users/king/Library/Developer/CoreSimulator/Devices/0E3648E7-5A63-41DA-A767-FB908BA7B4CA/data/Containers/Data/Application/CA3D7A3B-C88F-487A-B922-0016C63715BF/tmp/guilin_latex_pdavFkgW9/guilin_latex_pda/)
> [   +1 ms] Application finished.
> ```

Sorry, I found it on the shortcut key. I don't know when this key combination will be modified to exit debugging

<img width="1354" alt="image" src="https://user-images.githubusercontent.com/4713847/207238134-434ffadf-f482-4715-a3ec-fca06d7a549e.png">

**Comment by DanTup** [comment]
@josercc sorry for the delay.

> Sorry, I found it on the shortcut key. I don't know when this key combination will be modified to exit debugging

Ah, glad you tracked it down. I presume the issue is resolved and will close this, but please let me know if there's still an issue that needs looking at. Thanks!
