### ISSUE TITLE
Since Code 1.16, Hovers do not display for items that do not have dartdocs

### ISSUE THREAD

**Issue by bergwerf** [Dart-Code/Dart-Code#426]
I used to be able to hover a variable name in my code to see what type is was. I used this to double check if my assumptions about the code are correct. However, it seems like this is no longer working and although I cannot remember exactly, it might have been introduced with the last update of VSCode. I'm really missing this feature now.

VScode commit `27492b6bf3acb0775d82d2f87b25a93490673c6d` (v1.16.1)
DartCode version 2.4.0
Dart SDK version 1.25.0-dev.16.4

**Comment by DanTup** [comment]
Strange! On my PC I just tested this and it worked:

![Hovers](https://user-images.githubusercontent.com/1078012/30514263-559bdb28-9b09-11e7-8a63-7d24832f227d.png)

However I got a prompt to update Code, which I accepted, and now I don't get the tooltip. Seems like something has changed in Code 1.16.

**Comment by bergwerf** [comment]
Ok, good to hear it is reproducible :-)

**Comment by DanTup** [comment]
Seems to be a breaking change in Code - not sure if accidental or not. I'll push a fix soon, but I'm hoping they'll fix it, it was convenient the old way!

I raised at https://github.com/Microsoft/vscode/issues/34520

**Comment by DanTup** [comment]
I've updated the title, since based on the code I think it's the lack of a dartdoc causing it.

**Comment by DanTup** [comment]
@bergwerf Please upgrade to v2.4.1 and this issue should be resolved. Thanks for the report!

**Comment by bergwerf** [comment]
It is working for me, thanks for the quick fix!

Op za 16 sep. 2017 om 19:39 schreef Danny Tuppeny <notifications@github.com

**Comment by DanTup** [comment]
Great; thanks for confirming!
