### ISSUE TITLE
Issue on website (Modifying Files Outside Workspace)

### ISSUE THREAD

**Issue by workingfordev** [Dart-Code/Dart-Code#4264]
I found an issue on http://dartcode.org/docs/modifying-files-outside-workspace/
i modified and now am faacing errors 

can i get the original file ofthat please

**Comment by DanTup** [comment]
@workingfordev can you provide more details about the issue you're having? It's not very clear what sort of errors you're seeing.

I'm also unsure what you mean by the "original file".. That page has not changed recently and just describes how to disable the warning about modifying files outside of your workspace (although, usually that's not what you want to do - I would recommend having any files you're modifying within your workspace).
