### ISSUE TITLE
I am seeing this error message.

### ISSUE THREAD

**Issue by tarzan00123** [Dart-Code/Dart-Code#4265]
how do i fix it
Dart DevTools exited with code -4058. Would you like to try reactivating DevTools?
<img width="343" alt="image" src="https://user-images.githubusercontent.com/118049170/201468505-8b4be763-3296-4141-b883-5bda7f05933c.png">
<img width="720" alt="image" src="https://user-images.githubusercontent.com/118049170/201604905-81345aeb-eece-41b0-b6fc-abf159a6e220.png">

**Comment by DanTup** [comment]
Can you try running the **Dart: Open Extension Log** command from the VS Code command palette (`F1`) immediately after getting this message to see if there are any warnings/errors recorded when it tried to spawn DevTools?

Can you also post the full output of running the **Flutter: Run Flutter Doctor** command from the same VS Code command palette (note: this is not exactly the same as running it from the terminal, so please run it using this command).

**Comment by tarzan00123** [comment]
<img width="720" alt="image" src="https://user-images.githubusercontent.com/118049170/201604656-e3fc2b7b-999c-4688-a6bf-ebb71ff51968.png">

**Comment by tarzan00123** [comment]
how can i do this?
<img width="626" alt="image" src="https://user-images.githubusercontent.com/118049170/201605170-29450a5e-d0d3-4659-b139-7b756af24903.png">

**Comment by DanTup** [comment]
@tarzan00123 I think you ran a different command that has a similar name. The one starting "Dart" is the one you want:

<img width="639" alt="Screenshot 2022-11-14 at 11 35 38" src="https://user-images.githubusercontent.com/1078012/201650310-c37efc42-0f06-44d8-a6a1-bebe7608f455.png">

It should immediately open a log file inside VS Code.

**Comment by tarzan00123** [comment]
I can't see that 
<img width="577" alt="image" src="https://user-images.githubusercontent.com/118049170/201655722-3e06eb0c-4bb3-4aed-840f-bb2e6ab8db96.png">

**Comment by DanTup** [comment]
@tarzan00123 you need to have a Dart project open (so that the Dart extension is active) for it to show up. Is it possible you didn't when you tried this?

**Comment by tarzan00123** [comment]
I open and got this.
<img width="853" alt="image" src="https://user-images.githubusercontent.com/118049170/201667875-e691014c-0954-4f59-adb8-c70a6e7c5bee.png">

**Comment by DanTup** [comment]
@tarzan00123 that's right. If you search through that file, there may be some errors reported when it tried to start DevTools. If you search in the file for "DevTools" you should be able to find where it tries to start the DevTool server.

You can also post the full log here, or email it to me at logs@dartcode.org if you want me to check it. Please ensure it does not contain anything sensitive/confidential first.

**Comment by DanTup** [comment]
@tarzan00123 thanks - I got your email, but it looks like nothing was logged to the main log. Can you try this:

- Open a Flutter project that triggers the error
- Run the **Preferences: Open Workspace Settings (JSON)** command from the command palette (`F1`)
- Paste `"dart.devToolsLogFile": "logs/devtools.txt",` into the JSON file (taking care to put it between the `{` and `}` so it is valid JSON) and Save the file
- Run the **Developer: Reload Window** command from the command palette (`F1`)
- Wait for the error to appear again
- Open the file `logs/devtools.txt` that should have been created inside your project
- Send that file to me (you can attach the file or copy/paste the contents into the email instead of screenshots)

Thanks!

**Comment by DanTup** [comment]
@tarzan00123 thanks for the email, the log you sent was the one I was after. It shows:

```
[13:32:12] [DevTools] [Info] Spawning C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe with args ["devtools","--machine","--try-ports","10","--allow-embedding"]
[13:32:12] [DevTools] [Info] ..  with {"toolEnv":{"FLUTTER_HOST":"VSCode","PUB_ENVIRONMENT":"vscode.dart-code"}}
[13:32:12] [DevTools] [Info]     PID: 16536
[13:32:12] [DevTools] [Info] Process errored! Error: spawn "C:\Windows\System32\cmd.exe" ENOENT
[13:32:12] [General] [Error] Dart DevTools exited with code -4058.
```

It seems that when trying to start DevTools, this error is being thrown by NodeJS:

> Error: spawn "C:\Windows\System32\cmd.exe" ENOENT


I found some similar reports of this at https://stackoverflow.com/questions/38458118/nodejs-error-spawn-c-windows-system32-cmd-exe-enoent, although it's not clear if any of the solutions there are related. One that does seem possible is a bad `cwd`. To check that, can you try the following:

- Open a Command Prompt or PowerShell terminal
- Change directory to your desktop (`cd C:\Users\Admin\Desktop` - you may need to tweak this path to make sure it's right)
- Run `flutter create my_flutter_app` to create a sample app on your desktop
- Run `cd my_flutter_app` to change into that directory
- Run `code` to launch VS Code
- See whether you get the same error or not

**Comment by tarzan00123** [comment]
thank you for help me, I'm glad you came to help me.

**Comment by DanTup** [comment]
@tarzan00123 did that work? Or do you get the same error?

**Comment by tarzan00123** [comment]
yes that work, I don't see error, I edited as you suggested and the similar reports you provided.

**Comment by DanTup** [comment]
@tarzan00123 did you only follow my instructions above, or also something else on that page?

I'd like to understand what fixed it, in case there are improvements I can make to the extension to prevent this in future. If the issue was the working directory, then I can update the extension to always supply a working directory.

**Comment by tarzan00123** [comment]
I followed the instructions you suggested and the example you attached, I set the parts 
<img width="443" alt="image" src="https://user-images.githubusercontent.com/118049170/201917828-38b79bde-7bc5-405a-824b-bccb35475909.png">
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/118049170/201917888-89295e28-bbd8-4c45-a14f-317f74866735.png">

**Comment by DanTup** [comment]
@tarzan00123 did you actually change anything in the Environment variables? Were they set to something different? (I know on StackOverflow someone had a semicolon `;` on the end, but that was inside their error message whereas yours was not).

If you launch VS Code the normal way (not via the terminal), does it still work, or does it fail with the error message again? (If it fails, then I think I know how to fix this now).

**Comment by tarzan00123** [comment]
I edited the `" "` in my part. 
<img width="405" alt="image" src="https://user-images.githubusercontent.com/118049170/202120937-97e87e6b-0b52-4c80-bf5c-31ce01152b81.png">
I lunch VS Code the normal way, I'm Lunch as I've studied.

**Comment by DanTup** [comment]
Ah, sounds like it's sorted then. Let me know if the problem comes back. Thanks!
