### ISSUE TITLE
Server crash: Bad state: Expected to link dart:core and dart:async together: [dart:core/duration.dart, dart:core]

### ISSUE THREAD

**Issue by kenzieschmoll** [Dart-Code/Dart-Code#4267]
This will happen in the middle of my development often - not sure what is causing it, but a file will just all of a sudden drop syntax highlighting and look like this. Sometimes closing the file and reopening solves the problem, but not often.

![Screen Shot 2022-11-14 at 5 03 55 PM](https://user-images.githubusercontent.com/43759233/201801187-01100a09-eff8-4c51-ad14-f5db235a9028.png)

**Comment by DanTup** [comment]
@kenzieschmoll can you confirm which VS Code colour theme you're using (this can influence whether Semantic Tokens are used for highlights or not)?

Next time you see this and re-opening a file does not seem to fix it, could you try saving all files and then running the **Developer: Reload Window** command (or restarting VS Code) and see whether it comes back? (this will restart the anaysis server - I'm wondering whether there's something just broken in the current state of things, or whether maybe there's something specific about the content of your file(s) that is triggering it - which may make it easier to share something to repro this).

**Comment by DanTup** [comment]
There's an open VS code issue with some complaints about textmate grammars not working, though this may be unrelated (there certainly don't seem _many_ reports like this):

https://github.com/microsoft/vscode/issues/165225

Some additional things to check:

1. When this happens, Dart is still shown in the status bar as the active language 
  <img width="490" alt="Screenshot 2022-11-15 at 10 34 27" src="https://user-images.githubusercontent.com/1078012/201898044-6f2201b5-dc72-4735-84e6-cbffc69968e7.png">
2. Run the **Developer: Inspect Tokens and Scopes** command from the palette (`F1`) and move the cursor to a location where an item that should be coloured is not (for ex. a keyword) and post a screenshot of what the popup looks like here
3. Click Help -> Toggle Developer Tools and check the Console tab for any warnings/errors
4. Can you post (or send me) a list of all extensions you have installed in case there might be something not playing nicely between them

**Comment by kenzieschmoll** [comment]
When the syntax highlighting drops, a message pops up and says Dart Analysis Server terminated. Here is the exception in the log:

```
[9:54:11 AM] [Analyzer] [Error] Unhandled exception:
Bad state: Expected to link dart:core and dart:async together: [dart:core/duration.dart, dart:core]
#0      LinkedElementFactory.removeLibraries (package:analyzer/src/summary2/linked_element_factory.dart:246:9)
#1      LibraryContext.remove (package:analyzer/src/dart/analysis/library_context.dart:265:20)
#2      AnalysisDriver._removePotentiallyAffectedLibraries (package:analyzer/src/dart/analysis/driver.dart:1649:22)
#3      AnalysisDriver._applyPendingFileChanges (package:…
[9:54:11 AM] [Analyzer] [Info] Spawning /Users/kenzieschmoll/develop/flutter/bin/cache/dart-sdk/bin/dart with args ["language-server","--protocol=lsp","--client-id=VS-Code","--client-version=3.53.20221107"]
[9:54:11 AM] [Analyzer] [Info]     PID: 47869
```

**Comment by DanTup** [comment]
Ah, that's interesting. How often do you see this? It's very similar to https://github.com/dart-lang/sdk/issues/48051 although the message is slightly different. I don't suppose you've noticed any pattern to the steps you've performed just before this happens?

(@scheglov FYI)

**Comment by DanTup** [comment]
@kenzieschmoll could you confirm the SDK version you're using too? (I presume you're on a recent dev or something, and not stable, but it may be interesting to know whether it's a version that includes https://github.com/dart-lang/sdk/commit/0add39a68e145329a38fc215b99e1c468440d765).

**Comment by kenzieschmoll** [comment]
I am seeing this a few times per hour. The only pattern I notice is that I'm always in the middle of typing, but I can't say that I'm typing something in particular. I'll try to monitor this and look for logs each time it happens. This is my flutter and dart version:

Flutter 3.6.0-2.0.pre • channel flutter-3.6-candidate.2 • git@github.com:flutter/flutter.git
Framework • revision fa94a3c10e (2 days ago) • 2022-11-13 17:53:26 -0500
Engine • revision b63e6cf558
Tools • Dart 2.19.0 (build 2.19.0-394.0.dev) • DevTools 2.19.0

**Comment by DanTup** [comment]
Thanks - that version definitely includes my change above. Often that previous error was triggered by Ctrl+Clicking on SDK symbols. Before clicking, while holding Ctrl over the symbol, VS Code sends an open event immediately followed by a close event which seemed to be triggering the issue because it triggered analysis. My change should stop triggering that re-analysis when files are opened if the contents are the same as on disk, but if you think it might be occurring after ctrl+hover/click that would be interesting to know too.

Also - when this occurs, I would expect you to see a notification in the bottom right informing you the server has terminated and offering to restart - if you don't think that's happening please let me know too.

**Comment by amal-khailtash** [comment]
I am not sure if this is related to this https://github.com/microsoft/vscode/issues/165225 or not, but all my languages syntax highlighting are gone!

**Comment by amal-khailtash** [comment]
#https://github.com/microsoft/vscode/issues/165225

**Comment by Tetrapak0** [comment]
Try installing an older version of the dart code plugin

**Comment by DanTup** [comment]
> Try installing an older version of the dart code plugin

This is unlikely to help. The error above is occurring in the language server which is based on the SDK version, so it could happen with any version of the VS Code extension (it _might_ be restricted to LSP, but I wouldn't recommend disabling LSP at this point, as many features are only supported with LSP and the non-LSP support will eventually be dropped).

@kenzieschmoll I'm not sure which logs you already have enabled, but the [server instrumentation log](https://dartcode.org/docs/logging/#analyzer-instrumentation) might be a useful one to enable here. The files may get large (and will rotate) but it logs both the communication with the server and some additional internal info from the server. The last lines before this exception occurs might help understand what requests were happening in the server prior to this.

**Comment by DanTup** [comment]
@kenzieschmoll are you still seeing this much? Have you been able to capture an instrumentation log noted above?

**Comment by kenzieschmoll** [comment]
I haven't seen this recently. will reopen if I run into this again and can capture a log.
