### ISSUE TITLE
Add support for creating an "empty" project

### ISSUE THREAD

**Issue by gspencergoog** [Dart-Code/Dart-Code#4268]
Flutter recently added an option to `flutter create` to create an empty project that doesn't have any comments, the code is just a hello world instead of the counter app, and there's no test directory.  The flag is `--empty`.

It would be nice to add the option to the VSCode extension to allow people to create an empty project instead of one that has the counter app in it.  I'm not sure how that should manifest, it could either be an option setting that modifies the "Flutter: New Project" command, or an additional "Flutter: New Empty Project" command, I'm not sure which is more appropriate (maybe the latter?).

For context, see [this comment](https://github.com/flutter/flutter/issues/111118#issuecomment-1315816702), the PR that added the flag: https://github.com/flutter/flutter/pull/113873, and the [related IntelliJ feature request](https://github.com/flutter/flutter-intellij/issues/6402).

**Comment by DanTup** [comment]
Looks like this - let me know if you want any tweaks to it. It'll only show up for a Flutter SDK >= `3.6.0-3` (the current version I just pulled).

![Screenshot 2022-11-16 at 10 54 13](https://user-images.githubusercontent.com/1078012/202162062-8b5ecdc1-2b18-4ba6-969b-611d1edb0bcf.png)

Btw, right now `flutter create` creates folders for all platforms (if you don't pass them explicitly), even _Windows_ when I'm on macOS - is that expected?

**Comment by DanTup** [comment]
I just realised you noted:

> or an additional "Flutter: New Empty Project" command, I'm not sure which is more appropriate (maybe the latter?).

We can do that, although I think it would be better to have a single command (there's no confusion of multiple commands, and we can show this additional descriptive text shown above). If you think this is the one people will use most, we could push it to the top (and perhaps rename from "Application" vs "Application (empty)" to something like "Empty Application" and "(Sample?) Counter Application" or something?)

**Comment by gspencergoog** [comment]
What you have works for me.
