### ISSUE TITLE
How to hot reload/restart from REPL?

### ISSUE THREAD

**Issue by joshpetit** [Dart-Code/Dart-Code#4270]
Hey! This is more of a question, but I'm using this project alongside nvim-dap, and I was wondering if there was a way to trigger a hot reload/restart from the REPL? If not, could you point me in the direction of a way to signal to the `debug.js` file that it should hotreload or restart? I'd appreciate the help, thanks!

**Comment by DanTup** [comment]
I'm afraid don't know of a way to do this. The correct way for a DAP client to reload is to just send a custom request to the debug adapter.

FWIW, the `debug.js` file is the legacy debug adapter that is being phased out. I would recommend other editors use the `flutter debug_adapter` command (which is essentially the same thing, but ported to Dart and shipped in the SDK). There's some documentation about it here:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/debug_adapters/README.md

This would avoid you needing to clone Dart-Code and compile it (and the new SDK DAP doesn't make so many assumptions about the client being VS Code, as the legacy Dart-Code DAP has).

It it's useful, you can use the **Dart: Capture Debugging Logs** command ([see here](https://dartcode.org/docs/logging/#capture-logs-commands)) in VS Code to capture DAP traffic that might help understand what it's doing when trying to reproduce that in other editors.

**Comment by joshpetit** [comment]
Ok awesome thanks! Great to see this being shipped with flutter, I see that to debug dart files it's `dart debug_adapter` and for debugging flutter files it's `flutter debug-adapter` by the way. Thanks for the info, if I try looking into this more and figure it out I'll come back and update this thread and add some documentation on the nvim-dap page, thanks again :)

**Comment by DanTup** [comment]
Yep, you need to select the right debug adapter for your needs (both between `dart`/`flutter` and include `--test` when trying to run tests). I think `flutter` has an alias for `debug_adapter` (to match Dart).. Dart was done first but the command wasn't consistent with Flutter's conventions.

Feel free to post back any questions - or, if anything in the doc linked above (or the Dart version) is unclear, requests to expand it. Thanks!
