### ISSUE TITLE
CompletionSuggestion auto-imports don't work for plugin-contributed completions

### ISSUE THREAD

**Issue by zmtzawqlp** [Dart-Code/Dart-Code#4275]
I'm making a plugin base on [analyzer_plugin](https://github.com/dart-lang/sdk/tree/master/pkg/analyzer_plugin)  and follow the doc https://github.com/dart-lang/sdk/blob/master/pkg/analyzer_plugin/doc/tutorial/completion.md

The problem is that `libraryUri` is set and  `isNotImported` is set to true, but it still has not 'auto import from xxx' in completion. 

``` dart
  /// This field is omitted if getSuggestions was used rather than
  /// getSuggestions2.
  ///
  /// This field is omitted if this suggestion corresponds to a locally
  /// declared element.
  ///
  /// If this suggestion corresponds to an already imported element, then this
  /// field is the URI of a library that provides this element, not the URI of
  /// the library where the element is declared.
  ///
  /// If this suggestion corresponds to an element from a not yet imported
  /// library, this field is the URI of a library that could be imported to
  /// make this suggestion accessible in the file where completion was
  /// requested, such as package:foo/bar.dart or
  /// file:///home/me/workspace/foo/test/bar_test.dart.
  String? libraryUri;

  /// True if the suggestion is for an element from a not yet imported library.
  /// This field is omitted if the element is declared locally, or is from
  /// library is already imported, so that the suggestion can be inserted as
  /// is, or if getSuggestions was used rather than getSuggestions2.
  bool? isNotImported;
```

i found the comment at 
https://github.com/dart-lang/sdk/issues/38894#issuecomment-1193877946.  it's only happen in vscode, have any update for this? thanks.

**Comment by DanTup** [comment]
I have a fix for review at https://dart-review.googlesource.com/c/sdk/+/271701.

This change is in the Dart SDK so (once merged) the fix will only show up in a future Dart SDK release (and not a VS Code extension release).

**Comment by DanTup** [comment]
This is fixed by https://github.com/dart-lang/sdk/commit/019fb7a21488f55d616a8d26e921ed2b28750b81 and will ship in a future release of the Dart SDK. If you need to test this sooner, you could use a dev SDK from https://dart.dev/get-dart/archive#dev-channel once the release date shown is newer than todays date.
