### ISSUE TITLE
Toggling "off" debug break on "(All) Exceptions" persists behaving as "on" until completely restart debugging (reload not enough) 

### ISSUE THREAD

**Issue by nicolasmol** [Dart-Code/Dart-Code#4282]
Toggling "off" debug break on "'(All) Exceptions" persists behaving as "on" until completely restart debugging (reload not enough) 

At least it has been like this here,  right now on my configuration (hope it's not a a mistake of me)

Flutter 3.3.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision e99c9c7cd9 (il y a 3 semaines) • 2022-11-01 16:59:00 -0700
Engine • revision 857bd6b74c
Tools • Dart 2.18.4 • DevTools 2.15.0
Vscode:  1.73.1
OS: Linux Mint 20.3 x86_64 Kenel 5.15.0-53-generic

**Comment by DanTup** [comment]
I don't seem to be able to reproduce this. I'm using a freshly-created `flutter create` counter app. I added a caught exception to `_incrementCounter`:

```dart
void _incrementCounter() {
  setState(() {
    _counter++;
    try {
      throw 'test';
    } catch (e) {
      //
    }
  });
}
```

I ticked "All Exceptions" and ran the app. Clicked the `+` button and confirmed the debugger paused. I resumed, unticked "All Exceptions" and then clicked the `+` again, and it no longer pauses.

Can you try the same steps with a new counter app and see if you see the same behaviour?

If it fails in the counter app too, can you capture a log (while using the counter app):

- Run the [**Dart: Capture Debugging Logs** command](https://dartcode.org/docs/logging/#capture-debugging-logs)
- Run the app and reproduce the issue (first hit an exception with it enabled, then disable it and try again so it breaks unexpectedly)
- Click **Cancel** on the logging notification to stop logging and open the log
- Remove anything sensitive from the log
- Attach the log here (or in a gist)


If it _doesn't_ occur in the sample app and it seems specific to your project, can you confirm if your app contains anything that might be significantly different from the counter app (such as using multiple isolates, codegen, etc.)? Thanks!

**Comment by nicolasmol** [comment]
Your scenario is ok and works fine. However it was not the case in my actual project.
It seems to have been a very specific case. The two main differences with you senario were:

1) tuning on/off was made WHILE the app is already running in debug mode
2) the unhanded exception came from external package (firestore)

I'll come later with additional info when possible.

BUT I could say that globally sometimes and in any flutter project, even with no symlinks matter, it feels like adding/removing breakpoints (WHILE the app is already running in debug but) doesn't always work properly and requires stop/restart the app...

No ? 
Am I alone to feel so ?

Maybe linux ??

**Comment by DanTup** [comment]
> BUT I could say that globally sometimes and in any flutter project, even with no symlinks matter, it feels like adding/removing breakpoints (WHILE the app is already running in debug but) doesn't always work properly

I don't know of any reason this shouldn't work, but if you can get reliable repros I can take a look. I don't use Linux so can't say if there's a difference across platforms (usually behaviour for this is consistent, but I have definitely seen some Linux-specific bugs before).

There are also a few known issues with web due to how DWDS simulates isolates, but I'm not sure if you're using web?
