### ISSUE TITLE
Debugger views include private getters which always fail if the current stack frame is from in the library that declares them

### ISSUE THREAD

**Issue by Technorocker** [Dart-Code/Dart-Code#4296]
**Describe the bug**
I am using VSCode to debug my flutter app. This may have been doing it for a long time. I'm new to debugging. but I noticed as im steeping through the code every variable has a property called _identityHashCode and instead of a value if I hover over it it says this.
```
<error: org-dartlang-debug:synthetic_debug_expression:1:1: Error: The getter '_identityHashCode' isn't defined for the class 'MethodChannelFirebase'.
 - 'MethodChannelFirebase' is from 'package:firebase_core_platform_interface/firebase_core_platform_interface.dart' ('/C:/Users/andre.viau/AppData/Local/Pub/Cache/hosted/pub.dev/firebase_core_platform_interface-4.5.2/lib/firebase_core_platform_interface.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named '_identityHashCode'.
_identityHashCode
^^^^^^^^^^^^^^^^^>
```
It says this for every variable it shows in the debug window. This isnt causing any crashes or anything that I am aware of yet.

**To Reproduce**
1. Click on Run on the top bar and choose Start Debugging
2. Go to the run and debug tab on the side of vscode and expand the "This":  section to show the _identityHashCode property.
3. Step through the code to show different variables. 

**Expected behavior**

**Screenshots**
I have added a screenshot of the area this is showing me

**Please complete the following information:**
 - Operating System and version: Win 10 21H2
 - VS Code version: 1.73.1
 - Dart extension version: v3.54.1
 - Dart/Flutter SDK version: 2.19.0-374.0.dev
 - Target device (if the issue relates to Flutter debugging): android S10
![dart error](https://user-images.githubusercontent.com/35610201/205392315-77d121ae-b689-48bc-96b6-aa3a5ee13824.png)

**Comment by DanTup** [comment]
Private getters will be filtered from this list from a future update (via https://github.com/dart-lang/sdk/commit/c53f70509c34db8ecc69cf1bfa015d78889c2777). The change is in the SDK so it'll show up in a future SDK update (rather than a Dart-Code update).
