### ISSUE TITLE
Add refactor "Extract Parameter"

### ISSUE THREAD

**Issue by mosuem** [Dart-Code/Dart-Code#4302]
**Is your feature request related to a problem? Please describe.**
A situation which occurs quite often is that I extract a method so that
```
int i = getMyIndex(MyEnum.Value);
```
becomes
```
int i = newMethod();
...
int newMethod(){
  return getMyIndex(MyEnum.Value);
}
```
but in most cases I would actually want to have `MyEnum.Value` to be a parameter of this method.
**Describe the solution you'd like**
A refactor "Extract to Parameter" next to extract to local variable if the context is a method.

**Describe alternatives you've considered**
I could extract to local variable before extracting to method, so this
```
int i = getMyIndex(MyEnum.Value);
```
becomes
```
MyEnum v = MyEnum.Value;
int i = getMyIndex(v);
```
and then extract only the second line to a method; but that is unfortunately not how my brain works.

This also doesn't help in most cases where the method was written some time ago - now I am stuck with extracting the parameter by hand, oftentimes going up a chain of several methods.

I hope this is not a duplicate, if so, just consider it a thumbs-up.

**Comment by DanTup** [comment]
Yeah, this would be good. It would be done in the server and there's an existing issue at https://github.com/dart-lang/sdk/issues/49577 you can 👍  :-)
