### ISSUE TITLE
Unable to build Linux desktop apps when VS Code is installed via Flatpak

### ISSUE THREAD

**Issue by Karnor** [Dart-Code/Dart-Code#4309]
**Describe the bug**

I created the test application which counts the number of times you press a button, using the VSCode flutter extension. Then I pressed **F5** to build and run the project and get this error

```
CMake Error at CMakeLists.txt:3 (project):
  The CMAKE_CXX_COMPILER:

    /usr/bin/clang++  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

Exception: Unable to generate build files
```

Yet if I go to the project folder in a bash shell and type **flutter run -d linux**

I get this output and the project runs fine.

```
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           
Syncing files to device Linux...                                   100ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪
An Observatory debugger and profiler on Linux is available at: http://127.0.0.1:38865/EcLD24T3ZEI=/
The Flutter DevTools debugger and profiler on Linux is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:38865/EcLD24T3ZEI=/
```

**To Reproduce**

### To get the VSCode build error
1. press `<CTRL> + <SHIFT> + <P>` to bring up the VSCode task runner
2. select **Flutter: New Project**
3. select a project folder
4. give an application name
5. press **F5**

### Then to get the successful run in bash

1. open bash terminal external to VSCode
2. change working folder to the flutter test project folder
3. execute **flutter run -d linux**

**Expected behavior**

I expect the test application to build and run in VSCode just as it does in the bash shell.

**Screenshots**

**Please complete the following information:**
 - Operating System and version: Kubuntu 22.10
 - VS Code version: 1.74.1
 - Dart extension version: Dart SDK version: 2.18.6 (stable)
 - Dart/Flutter SDK version: 3.3.10 • channel stable • https://github.com/flutter/flutter.git
 - Target device (if the issue relates to Flutter debugging): linux

**Comment by DanTup** [comment]
@Karnor is it possible you have set one of the environment variables described in the error via a terminal script like `.bashrc`? If so, this won't be visible to VS Code unless you started VS Code from the terminal.

If that's the case (which you can verify by starting Code from the terminal with `code` and then testing), you could try moving the `export` statement that sets that env variable into `.bash_profile`/`.zprofile`/etc.) or by adding it to the `dart.env` VS Code user setting:

```js
"dart.env": {
  "CMAKE_CXX_COMPILER": "/path/to/compiler"
}
```
(see https://github.com/Dart-Code/Dart-Code/issues/4305 for a little more info about this kind of issue)

If this doesn't seem to be the problem, please let me know.

**Comment by Karnor** [comment]
> @Karnor is it possible you have set one of the environment variables described in the error via a terminal script like `.bashrc`? If so, this won't be visible to VS Code unless you started VS Code from the terminal.

No that's the first thing I checked, this is what I get if I test those variables in bash

```
Freedom:~/Projects/flutter/dungle$ echo $CXX

Freedom:~/Projects/flutter/dungle$ echo $CMAKE_CXX_COMPILER

Freedom:~/Projects/flutter/dungle$ 
```

As you can see the environment variables do not exist.

But in the cmake file in the project the compiler is set correctly as you can see here

```
//CXX compiler
CMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++
```

So according to that error message from VSCode the project should build because the cache is set.

**Comment by DanTup** [comment]
@Karnor what happens if you run `flutter run` from the embedded terminal in VS Code?

Is it possible there's a trailing slash on the path? In the error it seems like there could be an extra space between the path and the message:

```
    /usr/bin/clang++  is not a full path to an existing compiler tool.
                    ^^
```

A similar issue at https://stackoverflow.com/questions/46004925/cmake-cmake-c-compiler-is-not-a-full-path-to-an-existing-compiler-tool seems to have been caused by an unexpected newline on the end.

If neither of those help, can you try running the **Dart: Capture Debugging Logs** command in VS Code before trying to launch. This will force Flutter into verbose mode, and once the error appears you can click the **Cancel** button on the logging notification to get the full log.

You could compare this to running `flutter run -v -d linux` from the terminal to see if there are any obvious differences that might be leading to this.

**Comment by DanTup** [comment]
Oh, could it be that your build isn't going to `flutter` at all? Do you have a `launch.json` file in the workspace? Or do you have a native C++ file open when you press `F5`?

If you try clicking the `Run` CodeLens link above the `main()` function inside `lib/main.dart`, does that change anything?

**Comment by Karnor** [comment]
This may be where I start to get lost in VSCode, I am not an expert by any means with VSCode.

When I try to run flutter in VSCode terminal I get this
```
sh-5.1$ flutter run
sh: flutter: command not found
sh-5.1$ 
```

Assuming the workspace is the project folder then no, there is no launch.json file in there, as can be seen here
```
Freedom:~/Projects/flutter/dungle$ find . -type f | grep launch
./android/app/src/main/res/mipmap-hdpi/ic_launcher.png
./android/app/src/main/res/drawable/launch_background.xml
./android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
./android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
./android/app/src/main/res/drawable-v21/launch_background.xml
./android/app/src/main/res/mipmap-mdpi/ic_launcher.png
./android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
Freedom:~/Projects/flutter/dungle$
``` 

So I'll go generate the verbose logging and compare them as you suggested.

**Comment by DanTup** [comment]
> When I try to run flutter in VSCode terminal I get this

That's odd. But it works from an external shell? How did you install Flutter? Do you know how it gets into your `PATH` for the terminal?

You could try running `which flutter` from the external terminal to get the full path, and then run `/full/path/to/bin/flutter run` from the VS Code terminal.

First, I would try running from the `Run` CodeLens above the `main` function in `lib/main.dart` though. If that works, it suggests that pressing `F5` might be trying to run using the wrong extension (for example via a `C++` extension and not the Flutter extension).

**Comment by Karnor** [comment]
Oh as for the **run** code lens, I see a progress bar in the bottom right of VSCode with the message _Launching_ and _Building linux application_ but nothing happens, i.e. no application launches on my screen and there is no output in the **Problems**, **Output** tabs but the **Debug Console** tab has the same error messages.

**Comment by DanTup** [comment]
Ah, that rules out it going to the wrong extension then. In that case I would try from the embedded terminal (by getting the full path to Flutter using `which flutter` in the external terminal that works, and then running it using the full path in the VS Code terminal), and also comparing full verbose logs (`-v`) from the external terminal and from VS Code (either the embedded terminal if it has the same issue, or using the **Dart: Capture Debugging Logs** command otherwise).

**Comment by Karnor** [comment]
I installed flutter from the [flutter site at this link](https://docs.flutter.dev/get-started/install/linux) specified in the **Install Flutter manually** section as I don't have _snap_.

Full path to flutter is
```
Freedom:~/Projects/flutter/dungle$ which flutter
/home/username/Development/flutter/bin/flutter
```

The path is set in my _.profile_ script.

**Comment by Karnor** [comment]
grrr, running with the full pathname in terminal gives the same build errors.

**Comment by DanTup** [comment]
@Karnor do you mean you get the errors when running it from the VS Code embedded terminal?

If so, that means you could try `/path/to/bin/flutter run -v -d linux` in both embedded and external terminals to compare the verbose log output. This might be slightly easier to diff than using the **Dart: Capture Debugging Logs** command, as its output will be prefixed with timestamps and stuff.

There may be something different in the outputs that help understand what's different.

I would also try:

- running `printenv` in both embedded and external terminals, and diff them to see what differences there are
- disabling other extensions (for example if you have C++ extension) and restarting VS Code to see whether that changes anything

**Comment by DanTup** [comment]
@Karnor any differences in the output of `printenv` in both embedded/external terminals?

**Comment by Karnor** [comment]
Yes there are lots of differences, I dumped the outputs to **printenv-bash.txt** and  **printenv-embedded.txt** then ran this diff
`diff printenv-bash.txt printenv-embedded.txt > printenv-diff.txt`
and attached the out
[printenv-diff.txt](https://github.com/Dart-Code/Dart-Code/files/10260784/printenv-diff.txt)
put for you.

**Comment by Karnor** [comment]
Oh btw the VSCode editor is installed via flatpak

**Comment by Karnor** [comment]
omg as you were typing that I was busy deleting the flatpak version and installing from the repo as I suddenly remembered that on my other kubuntu system I was doing exactly that.

The trigger for that memory was when I wrote my comment about vscode being installed via flatpak.

So it seems the flatpak version of vscode leaves a lot to be desired.

I came back here to say the problem is now resolved having installed from the repo.

Sorry for wasting your time, I should have realized the problem straight away, but that's what you get when you build a new installation having been awake around 36 hours I guess mb

But at least now we know the flatpak build is broken, and that might be the first question you should ask linux users when they say things don't work lol

Again, really sorry for wasting your time, and tyvm for being patient with me.

**Comment by DanTup** [comment]
Great, glad you've up and running! I'll update the title, and hopefully will remember this in future. Perhaps it's also worth detecting this from the VS Code extension and recording it in the log somewhere (or finding a way to surface it to the user if things seem to be failing). I'll make a note to think more about this (since a similar issue exists with Snap).
