### ISSUE TITLE
Command "add final field formal parameters" added all not initialized fields to constructor.

### ISSUE THREAD

**Issue by Cododoc** [Dart-Code/Dart-Code#431]
Example:
```
class MyTestClass {
  String id;

  final IdGenerator _idGenerator;
}
```

Step 1 - Create constructor for final fields:
Set cursor to the _idGenerator line. Press Ctr+. and select "Create constructor for final fields". You get:
```
class MyTestClass {
  String id;

  final IdGenerator _idGenerator;

  MyTestClass(this._idGenerator);
}
```

Step 2 - Add new final field.
```
class MyTestClass {
  String id;

  final IdGenerator _idGenerator;
  final IdGenerator _idGenerator2; // <-- new final field

  MyTestClass(this._idGenerator);
}
```

Step 3 - add final field formal parameters.
Set cursor on constructor line. Press Ctrl+. and select "add final field formal parameters". You get:
```
class MyTestClass {
  String id;

  final IdGenerator _idGenerator;
  final IdGenerator _idGenerator2; // <-- new final field

  MyTestClass(this._idGenerator, this.id, this._idGenerator2);
}
```
## Problem
**this.id** was added, but should not. It is not final field.

As workaround you can set null to id. Then command "add final field formal parameters" will work fine.

**Comment by Skylled** [comment]
If memory serves, this is actually an Analyzer problem. All of the light-bulb suggestions are given by the Analyzer. I suggest filing [here](https://github.com/dart-lang/sdk/issues).

To confirm that, you could reproduce the same issue on IntelliJ.

**Comment by DanTup** [comment]
Yep, Kyle is correct - these lightbulb actions actually come from the analysis server which ships inside the SDK - Dart Code delegates to it. So in theory, this issue exists in other IDEs like IntelliJ too. I've pasted your report at https://github.com/dart-lang/sdk/issues/31026 to be looked at by the analyzer team.

**Comment by DanTup** [comment]
This has been fixed and should be in a future Dart SDK release (it does not require any Dart Code update, it'll just work when Dart Code uses the new SDK). Thanks for the report!
