### ISSUE TITLE
Disable Flutter SDK DAP pending a fix for bug

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#4313]
See https://github.com/dart-lang/sdk/issues/50802. This is the top crash in the current Flutter beta.

We should bump the version number for enabling the new SDK DAP by default until this issue is fixed. We can always bring it back down, but since there can be some delay for users updating, it seems better to be on the side of caution.

**Comment by fisforfaheem** [comment]
please explain

**Comment by DanTup** [comment]
@fisforfaheem the "DAP" is the debug adapter used to connect VS Code to the Dart runtime while debugging.

There are two implementations of this - one written in TypeScript that lives inside this repository, and a newer one written in Dart that lives inside the Dart/Flutter SDKs.

We're in the process of migrating from the old TypeScript versions to the new Dart versions, but an issue was found (linked above) that needs to be fixed. Until it's fixed (and the fix is shipped), I have disabled the rollout of the new Dart DAPs, so everyone will get the older TypeScript versions (unless they have explicitly opted into the new ones with the `dart.previewSdkDaps` setting).

This generally won't affect users. For the most part, both DAPs behave the same. Going forwards, all new work will be in the new Dart versions though (and once this bug is fixed, we will resume the migration).

Hope this makes sense!
