### ISSUE TITLE
Re-enable Flutter SDK DAP for new versions

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#4314]
- [x] https://github.com/dart-lang/sdk/issues/50802 / https://github.com/Dart-Code/Dart-Code/issues/4313
- [x] https://github.com/Dart-Code/Dart-Code/issues/4193

**Comment by DanTup** [comment]
@christopherfujino FYI, I'm re-enabling the SDK DAP experiment for Flutter >= 3.8.0-16.

This means:

- _all_ Flutter pre-release users on >= 3.8.0-16 (which is the version I just got today) will begin using the SDK DAPs again
- if/when 3.8.0 (or later) goes stable, 10% of users will begin using the SDK DAPs (this number will begin increasing after the next stable release as long as there aren't significant issues reported) 

Please let me know if you hear of any issues that may be related. Ideally if there are any remaining issues that would affect enabling this for stable users, pre-release users will find them in time to be fixed before the next stable branch.

**Comment by christopherfujino** [comment]
> @christopherfujino FYI, I'm re-enabling the SDK DAP experiment for Flutter >= 3.8.0-16.
> 
> This means:
> 
> * _all_ Flutter pre-release users on >= 3.8.0-16 (which is the version I just got today) will begin using the SDK DAPs again
> * if/when 3.8.0 (or later) goes stable, 10% of users will begin using the SDK DAPs (this number will begin increasing after the next stable release as long as there aren't significant issues reported)
> 
> Please let me know if you hear of any issues that may be related. Ideally if there are any remaining issues that would affect enabling this for stable users, pre-release users will find them in time to be fixed before the next stable branch.

SGTM, thanks for the heads up!

**Comment by DanTup** [comment]
FYI, I'm reverting the above and bumping it back a bit more because of https://github.com/Dart-Code/Dart-Code/issues/4413 (the new `ToolEvent` stream isn't supported by DWDS meaning there are issues with web).

I'm re-opening this to re-do once that's fixed.
