### ISSUE TITLE
Error: Not found: 'dart:ui' when trying to run a Flutter project

### ISSUE THREAD

**Issue by Maaiz-Shaikh** [Dart-Code/Dart-Code#4315]
**Describe the bug**
As mention by @DanTup while explaining to @Chetan34123456 I was also facing the same issue. I am attaching Debug Console log for the same.

@Chetan34123456 the two most common cases of this are:

Project is not detected as a Flutter project. You can tell if this is the case because it was show a Dart SDK version ("Dart x.y.z") in the status bar, or the words "Dart from Flutter". If it shows "Flutter x.y.z" in the status bar, then this is not the problem. If this is the problem, it's usually caused by not opening the Flutter projects folder correctly, or not having Flutter correctly referenced in the pubspec.yaml.
Clicking the Run buttons contributed by the Code Runner extension. Code Runner does not understand Flutter projects and tries to run everything with Dart. If this is the problem you should just launch the app using F5 or the "other" run button, or the Run menu.
If it's neither of these, please run the Dart: Capture Debugging Logs command from the command palette (F1), try to run the app (to generate the error), then click Cancel on the logging notification to stop logging and open the log file, then file a new issue with the log attached.

Note: The log will contain parts of your source, so best to repro in a clean project (created with the Flutter: New Project command).

** Debug Console log **
[Debug log console.txt](https://github.com/Dart-Code/Dart-Code/files/10279083/Debug.log.console.txt)

**Comment by DanTup** [comment]
@Maaiz-Shaikh can you describe in detail exactly what the issue you're having is? In the subject of this issue it says "Not found: 'dart:ui'", but in the log you've attached is a different error:

```
[+9327 ms] Exception: Unable to find suitable Visual Studio toolchain. Please run `flutter doctor` for more details.
Exited (sigterm)
```

Can you describe exactly what you're seeing (screenshots are always helpful), and exactly what you steps you took that resulted in the error? Thanks!

**Comment by Maaiz-Shaikh** [comment]
> @Maaiz-Shaikh can you describe in detail exactly what the issue you're having is? In the subject of this issue it says "Not found: 'dart:ui'", but in the log you've attached is a different error:
> 
> ```
> [+9327 ms] Exception: Unable to find suitable Visual Studio toolchain. Please run `flutter doctor` for more details.
> Exited (sigterm)
> ```
> 
> Can you describe exactly what you're seeing (screenshots are always helpful), and exactly what you steps you took that resulted in the error? Thanks!

Actually, I was trying to run my flutter project on web but it was not running and showing error as "Error: Not found: 'dart:ui'". But today when I run it, it give corrrect output.

I don't know what happened, but my problem get resolved automatically.
Thanks for your quick reply and willing to resolve my problem.

As my problem get resolved, I am closing this issue.
