### ISSUE TITLE
Breakpoints in flutter/web project does not work

### ISSUE THREAD

**Issue by radvansky-tomas** [Dart-Code/Dart-Code#4316]
Issue described here https://github.com/flutter/flutter/issues/117490

**Comment by DanTup** [comment]
> Switching to BETA does NOT resolve it. I worked fine 2-3 days ago, its most likely related to new vscode plugin?

I can't think of any reason why this would change, but could you try rolling back to the previous extension version and see if that solves the issue?

<img width="429" alt="Screenshot 2022-12-21 at 21 46 25" src="https://user-images.githubusercontent.com/1078012/209008261-a6059501-4847-419f-9830-539d4b3fa94b.png">

Can you also confirm if you're able to reproduce this on a newly created Flutter app and post the full output of `flutter doctor -v`? Thanks!

**Comment by radvansky-tomas** [comment]
```
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.6 21G115 darwin-arm, locale en-NZ)
    • Flutter version 3.3.10 on channel stable at /Users/tomasradvansky/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (6 days ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc3)
    • Android SDK at /Users/tomasradvansky/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.2.4
    • Dart plugin version 213.7227

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 108.0.5359.124
    ! Error: iPhone is busy: Waiting to connect and unlock the device. Xcode will continue when iPhone is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by radvansky-tomas** [comment]
Switching to older version of flutter & dart extensions did NOT fix the problem :(

I also did `flutter clean`

Will try to provide info about new project later in the day

**Comment by DanTup** [comment]
> Switching to older version of flutter & dart extensions did NOT fix the problem :(

I suspected that might be the case (since I don't think anything in the update would really have changed anything here). It's possible there's an issue in DWDS.. this error has come up before in some situations:

- https://github.com/dart-lang/webdev/issues/1271
- https://github.com/dart-lang/webdev/issues/1842
- https://github.com/dart-lang/webdev/issues/874#issuecomment-578204898

If you're able to build a small repro project that triggers this, that would help with debugging.
