### ISSUE TITLE
Bad syntax highlighting in comments with list items

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#4317]
At 24:53 in [this stream](https://youtu.be/WGE4p6y2r_k?t=1493), the syntax highlighting is bad on the `PaymentItemType` enum. As well as the items being coloured differently, the first slash and the second/third are not the same colour:

<img width="987" alt="Screenshot 2022-12-22 at 19 19 20" src="https://user-images.githubusercontent.com/1078012/209210511-7d508a75-d984-4933-94c8-43db5fdb233b.png">

My guess is that this theme doesn't support semantic tokens and it's coming from the textmate grammar.

@craiglabenz can you confirm which colour theme you're using here?

**Comment by DanTup** [comment]
Don't seem to be able to repro this...

With semantic tokens:

<img width="672" alt="Screenshot 2023-01-17 at 14 33 29" src="https://user-images.githubusercontent.com/1078012/212926166-c984c30d-1231-4433-91f2-571a382e4fec.png">

Without:

<img width="652" alt="Screenshot 2023-01-17 at 14 33 37" src="https://user-images.githubusercontent.com/1078012/212926172-c65f04ea-387f-4f9b-90b2-e19abd59a058.png">

**Comment by DanTup** [comment]
If I inspect tokens, it's the same token for the whole line. I wonder if there's another extension installed that might be conflicting with this?

@craiglabenz if you can still repro this I'd be interested in knowing what extensions you have, or what you see if you run the **Developer: Inspect Tokens and Scopes** command from the palette and then put the cursor in the wrongly-coloured `// * [` text.

**Comment by craiglabenz** [comment]
Apologies for the slow response - my color theme is Synthwave '84. Can't think of any other plugins I use that might get in the way here, but happy to collaboratively investigate after Flutter Forward :)

**Comment by DanTup** [comment]
Thanks! With that theme mine looks more like yours, but still doesn't show the issue:

<img width="665" alt="Screenshot 2023-01-19 at 11 59 43" src="https://user-images.githubusercontent.com/1078012/213437607-3874194f-dd6b-467d-a348-2ce4f68754d2.png">

No rush, but when you're not busy with FF stuff if you could ping me a list of your extensions or run the **Developer: Inspector Tokens and Scopes** command then put your cursor in the mis-coloured text and let me know what it shows (or ping me) that would be great.

This is what I see when the cursr is in front of `*` in `/// * [item]`:

<img width="1045" alt="Screenshot 2023-01-19 at 12 01 29" src="https://user-images.githubusercontent.com/1078012/213437937-4c44e8e2-9232-40ce-ad91-6ffcde99a966.png">

**Comment by DanTup** [comment]
@craiglabenz ping :-) Is it possible you could a) check whether you still see this issue and b) send me a list of all extensions you have installed? (you can run `code --list-extensions` to get a list easily).
