### ISSUE TITLE
Invalid analysis errors for just one of my projects when opening parent folder

### ISSUE THREAD

**Issue by jakemac53** [Dart-Code/Dart-Code#432]
For the `build` package (https://github.com/dart-lang/build) we have a few packages all under a top level directory. I can open that top level directory and things work generally, except for one of the directories `e2e_example`. This one always shows a ton of analysis errors (but `dartanalyzer .` doesn't complain).

You can repro by checking out the repo (https://github.com/dart-lang/build) and opening the root folder up in vscode.

**Comment by DanTup** [comment]
Sounds strange! I'll try and take a look this week. I presume you haven't seen this same issue in other editors (like Atom or IntelliJ) for the same project?

**Comment by jakemac53** [comment]
Well that is interesting, intellij is giving the exact same behavior! That makes me think it is an analysis server bug.

**Comment by DanTup** [comment]
Yep, sounds like it if it repros in IntelliJ. If you raise an issue there, please post the link back here in case anyone comes across it looking for solutions to similar issues :-)

**Comment by jakemac53** [comment]
Filed https://github.com/dart-lang/sdk/issues/31126

**Comment by jakemac53** [comment]
Closing as it looks like this is really just user error with a confusing result :)

**Comment by DanTup** [comment]
Great, glad you sorted it. I don't totally understand the behaviour in the other case, but there are improvements to be made I guess they'd need to be in the analyzer rather than Dart Code.
