### ISSUE TITLE
Catch block parameters are not highlighted

### ISSUE THREAD

**Issue by navaronbracke** [Dart-Code/Dart-Code#4320]
**Describe the bug**
Syntax highlighting for the catch block parameters is broken.

**To Reproduce**
1. Create a new file, i.e. catch.dart and paste in the code sample
```
try {
 // do something
} catch (error, stackTrace) {
 // handle error
}
```
2. Open the file in VSCode
3. The `error` and `stackTrace` arguments are not highlighted, so they look the same as a `dynamic foo = 42;` variable would look.
4. Type inference does not work either when hovering over either `error` or `stackTrace`, even though we know that `error` is an `Object` and `stackTrace` is a `StackTrace` 

**Expected behavior**
I expect that the `error` and `stackTrace` arguments get highlighted in blue. When hovering over either `error` or `stackTrace`, the tooltip should display the proper type.

**Screenshots**
![Screenshot 2022-12-23 at 19 47 30](https://user-images.githubusercontent.com/23480364/209394160-14b7ea95-4686-4b76-b337-d73f2b95a701.png)

**Please complete the following information:**
 - Operating System and version: macOS 12.2.1 21D62 darwin-x64
 - VS Code version: 1.74.1
 - Dart extension version: v3.56.0
 - Dart/Flutter SDK version: Dart 2.19.0-444.1.beta | Flutter 3.7.0-1.1.pre (beta)
 - Target device (if the issue relates to Flutter debugging): N/A

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/792aedec74591193eab098be4346dafcfb69ab0f. This change is in the Dart analysis server so will ship with a future Dart/Flutter SDK release rather than show up in the VS Code extension release.
