### ISSUE TITLE
Flutter sdk version not shown in statusbar

### ISSUE THREAD

**Issue by maheshmnj** [Dart-Code/Dart-Code#4321]
**Describe the bug**

The flutter SDK version is not shown in the Status bar, I am quite not sure if it's a bug or if it was removed intentionally. This is specifically important when you have multiple flutter SDKs installed to quickly switch between flutter versions and also to know at a glance what version is being used. I understand that I can switch between SDKs from the command palette (cmd+shift+p -> change Flutter SDK) But changing versions from the status bar would be pretty handy.

**To Reproduce**
1. Open any flutter project
2. Notice flutter SDK version is not shown on status bar

**Expected behavior**
The current flutter SDK version must be shown

![image](https://user-images.githubusercontent.com/31410839/209394039-09371c2f-d18a-4f8f-826d-87990ff0f44e.png)

**Actual behavior**

SDK version not visible, I also checked the status bar options to see if it was disabled (But there is no such option)

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/31410839/209394106-a8b123af-0588-4471-a855-ad30135697d7.png">

**Please complete the following information:**
 - Operating System and version: Mac 13.1
 - VS Code version: Version: 1.74.1
 - Dart extension version: v3.56.0

**Comment by DanTup** [comment]
@maheshmnj many of the status bar items were moved in a [recent release](https://dartcode.org/releases/v3-54/#improved-status-bar-information) to the "language status" area:

![image](https://user-images.githubusercontent.com/1078012/209429558-9cec73de-8925-4c78-920e-a3bcb80509a2.png)

This appears as a `{}` icon next to the language name, however I can't see it in your screenshot. Can you confirm you're on a recent version of VS Code, and also see if you have a "language status" (or similar) entry when you right-click on the status bar that might be unticked?

**Comment by maheshmnj** [comment]
Thanks I updated vscode and I had language editor feature disabled I guess now I see it 

<img width="666" alt="image" src="https://user-images.githubusercontent.com/31410839/209436107-f0c01540-8923-4005-862d-95e734339b95.png">


Closing as resolved.
