### ISSUE TITLE
FLUTTER NOT INSTALLING ON VSCODE

### ISSUE THREAD

**Issue by davetobby** [Dart-Code/Dart-Code#4327]
I search for Flutter under extension in VS Code which came up, it was clicked on from the suggestions.
i clicked on install and i keep getting 'Error while installing 'Flutter' extension. Please check the [log](command:workbench.action.showWindowLog) for more details.'
I also tried downloading it manually and i clicked on installed from VSIX but still did not worked.
![Uploading Screenshot 2022-12-30 at 1.33.27 PM.png…]()
Kindly help out.
Thank you.

**Comment by DanTup** [comment]
The installation process is handled by VS Code and not something the extensions are involved in themselves, so this will need fixing/troubleshooting by VS Code.

I can see a few open issues recently that look similar, so I would try following the instructions posted there to capture logs and post them to get help from the VS Code team:

- https://github.com/microsoft/vscode/issues/170102
- https://github.com/microsoft/vscode/issues/170211
- https://github.com/microsoft/vscode/issues/169918

Please let me know if you don't manage to get a resolution to this there. Thanks!
