### ISSUE TITLE
Parameter auto-template sometimes works, sometimes doesn't

### ISSUE THREAD

**Issue by xster** [Dart-Code/Dart-Code#433]
Love the feature that auto inserts `children: <Widget>[|]` when choosing the `children` named parameter during autocomplete (where | is the cursor position after the template drop).

But it seems like it doesn't work everywhere. For instance, doing it on Flutter's Row object's children works but doing it on Flutter's CustomScrollView's slivers which also takes a list of <Widget> doesn't.

**Comment by DanTup** [comment]
Sorry for the delay in looking at this, especially now I suspect it's an SDK issue :(

I can't take credit for this feature, it's coming from the analyzer. The completion for `children` looks like this:

```js
{
  "kind":"NAMED_ARGUMENT",
  "relevance":1060,
  "completion":"children: <Widget>[],",
  "selectionOffset":19,
  "selectionLength":0
}
```

This tells us what to complete, and also where to put the cursor/selection :)

For whatever reason, the same doesn't happen for Slivers:

```js
{
  "kind":"NAMED_ARGUMENT",
  "relevance":1060,
  "completion":"slivers: ,",
  "selectionOffset":9,
  "selectionLength":0
}
```

I don't know where the info comes from that makes this work (eg. analysis server or something about the source flutter types) though maybe @bwilkerson can provide a pointer.

**Comment by bwilkerson** [comment]
The info for this is coming from server. Specifically, the completion suggestions are being computed by the class `ArgListContributor` (defined in https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/lib/src/services/completion/dart/arglist_contributor.dart).

I don't know what the reasoning was, but it appears that the method `_addNamedParameterSuggestion` limits this kind of completion to the `children` parameter (https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/lib/src/services/completion/dart/arglist_contributor.dart#L243). Seems like generally useful behavior to me (not just for Flutter widgets).

**Comment by DanTup** [comment]
@bwilkerson Thanks for the info! Looks like it came from https://github.com/flutter/flutter-intellij/issues/463

@xster You'll need to raise over in the SDK/Flutter repos (or just fix it ;-)) since I can't fix it from Dart Code (or at least, I shouldn't, since it'll be a hack and other IDEs won't benefit!).

**Comment by devoncarew** [comment]
Should be fixed by https://dart-review.googlesource.com/c/sdk/+/21880.

**Comment by DanTup** [comment]
Thanks! 👍
