### ISSUE TITLE
visual studio.

### ISSUE THREAD

**Issue by shahmeerkhan12** [Dart-Code/Dart-Code#4344]
I have installed visual studio but when I run 'flutter doctor' it responds that it is not installed, it is necessary for windows development..I am attaching a screenshot so it will be clear.
![bug](https://user-images.githubusercontent.com/100615405/212528488-3f9b74fc-8255-40ce-9a73-8646b80559f5.png)

**Comment by Skye10da** [comment]
check your visual studio installation properly, you run vs_build tools to install Desktop development workload

**Comment by DanTup** [comment]
@shahmeerkhan12 are you seeing this only inside VS Code, or also when run from an external terminal?

If also when running from an external terminal, then it's not something that can be fixed here (this repository is for the VS Code extensions only).

That said, I could check you selected the "Desktop development with c++ workload" option during installation as noted above. You may also be able to get some additional info by running `flutter doctor -v` (`-v` is verbose mode).
