### ISSUE TITLE
stlss and stful autocompletes import from flutter/src/widgets instead of flutter/material.dart

### ISSUE THREAD

**Issue by juskek** [Dart-Code/Dart-Code#4346]
**Describe the bug**
The `stlss` and `stful` template shortcuts shown [here](https://github.com/dart-lang/dart-pad/issues/1278) used to auto-complete with the following import: 

```dart
import 'package:flutter/material.dart';
```

However, now the autocomplete imports the following files:

```dart
import 'package:flutter/src/widgets/container.dart';
import 'package:flutter/src/widgets/framework.dart';
```

**To Reproduce**
1. Type `stlss` in a dart file in VSCode

**Expected behavior**
Dart file autocomplete output:

```dart
import 'package:flutter/material.dart';

class MyWidget extends StatelessWidget {
  const MyWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

**Actual behaviour**
Dart file autocomplete output:
```dart
import 'package:flutter/src/widgets/container.dart';
import 'package:flutter/src/widgets/framework.dart';

class MyWidget extends StatelessWidget {
  const MyWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

**Please complete the following information:**
 - Operating System and version: MacOS Ventura 13.1
 - VS Code version: 
 ```
Version: 1.74.3 (Universal)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T17:07:18.579Z (6 days ago)
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 22.2.0
Sandboxed: No
```
 - Dart extension version: v3.56.0
 - Dart/Flutter SDK version:
```
Flutter 3.3.10 • channel stable •
https://github.com/flutter/flutter.git
Framework • revision 135454af32 (5 weeks
ago) • 2022-12-15 07:36:55 -0800
Engine • revision 3316dd8728
Tools • Dart 2.18.6 • DevTools 2.15.0
```
 - Target device (if the issue relates to Flutter debugging): NA

**Comment by DanTup** [comment]
Thanks for the report. This was recently fixed (via https://github.com/dart-lang/sdk/issues/49081), but the fix is in the Dart SDK so it will show up in a future Dart SDK release (rather than a Dart-Code release).
