### ISSUE TITLE
The debugger is stepping into SDK code even when the setting is off

### ISSUE THREAD

**Issue by muddi900** [Dart-Code/Dart-Code#4348]
**Describe the bug**
I am trying to debug my code but the debugger keeps stepping into the SDK code, taking forever and crowding my tab bar.

**To Reproduce**
1. Run an app in debug mode.
2. Set a breakpoint.

**Expected behavior**
It should just step through my project code

**Screenshots**
*The Debugging Session*
![Screenshot (60)](https://user-images.githubusercontent.com/37051110/212823716-78454edb-1439-4a20-8c4c-47b750bf547c.png)
![Screenshot (85)](https://user-images.githubusercontent.com/37051110/212823733-bd28cdbb-c40b-4b7f-8bd0-a2e065bd6ceb.png)

*The Settings*
![Screenshot (87)](https://user-images.githubusercontent.com/37051110/212823987-ee36c348-397c-4c13-82fd-a15ce9d85c45.png)

**Please complete the following information:**
 - Operating System and version: Windows 11 Build 22621.963
 - VS Code version: 1.74.3
 - Dart extension version: 3.56
 - Dart/Flutter SDK version: 3.3.10
 - Target device (if the issue relates to Flutter debugging): Chrome

**Comment by DanTup** [comment]
These debug settings are not currently supported for web. Web debugging uses DWDS (a proxy that translates between the Dart VM Service protocol and the Chrome debugger, so that VS Code only needs to use a single protocol whether running on the VM or as compiled JS in Chrome) which does not currently support `setLibraryDebuggable`.

There's a tracking issue for this at https://github.com/dart-lang/webdev/issues/606.

I'll keep this open to track this issue here, but it'll depend on DWDS support.

**Comment by muddi900** [comment]
@DanTup Well the issue is still happening on android.

current versions

Please complete the following information:

    Operating System and version: Windows 11 Build 22621.1265
    VS Code version: 1.75.1
    Dart extension version: 3.58
    Dart/Flutter SDK version: 3.7.3
    Target device (if the issue relates to Flutter debugging): Android Emulator

**Comment by DanTup** [comment]
I'm also failing to reproduce this (on either debug adapter). Does it happen for you if you create a new counter app, put a breakpoint on `setState` in `_incrementCounter` and then click Step In?

If so, can you capture a log (using the counter app):

- Run the [**Dart: Capture Debugging Logs** command](https://dartcode.org/docs/logging/#capture-debugging-logs)
- Start the debug session
- Reproduce the issue
- Click **Cancel** on the logging notification to stop logging and open the log
- Remove anything sensitive from the log
- Attach the log here, in a [gist](https://gist.github.com/), or email to me at logs@dartcode.org.

Thanks!

**Comment by muddi900** [comment]
It happened again on. Here are the logs.
[Dart-Code-Log-2023-01-01 11-35-50.txt](https://github.com/Dart-Code/Dart-Code/files/10842955/Dart-Code-Log-2023-01-01.11-35-50.txt)
