### ISSUE TITLE
indent size doesn't work

### ISSUE THREAD

**Issue by Zhoucheng133** [Dart-Code/Dart-Code#4357]
I like the indent with 4 spaces but when I change the extension setting: 
```json
"[dart]": {
    "editor.tabSize": 4,
},
```
It doesn't work, and still use 2 spaces instead of 4 space.
If extension itself can't change indent, I hope it can change in the future version.

**Comment by DanTup** [comment]
Formatting is handled by the Dart SDK formatter which currently only supports formatting with 2 spaces. There's an open issue about this at #914, although right now there aren't any current plans for working on this.

It is possible to disable the built-in formatter (using the `"dart.enableSdkFormatter": false,` setting) so you can manually format in the meantime (or if someone was to build an alternative formatter as a VS Code extension, to use that instead).
