### ISSUE TITLE
Dart Reformatting support in VSCode

### ISSUE THREAD

**Issue by hooramin** [Dart-Code/Dart-Code#436]
hello
I wanna know is reformatting supported in VSCode or not ?
If no , will it support in future ?

**Comment by DanTup** [comment]
Yep, Format Document works, as does format-on-save 🙂

If you have any issues with them, please do raise issues so I can investigate!

**Comment by varora1406** [comment]
How does Dart reformatting work in visual studio code?
When 
![image](https://user-images.githubusercontent.com/24986539/35481168-61bd6d28-0444-11e8-9b49-94eae88dcf4f.png) this image appear if try try to format code

**Comment by DanTup** [comment]
@varora1406 Can you confirm which version of Dart Code you have installed? It should just work.

Also - can you open the developer console (Help -> Toggle Developer Tools) to see if there are any errors listed, and also include a screenshot that shows the right half of the status bar across the bottom of the screen?

**Comment by varora1406** [comment]
![image](https://user-images.githubusercontent.com/24986539/35481596-c616f962-044c-11e8-922e-9d68f033fb19.png)

Is this error related to formatting?

**Comment by varora1406** [comment]
ok wait, can you help me telling error in 
![image](https://user-images.githubusercontent.com/24986539/35481622-1e104e34-044d-11e8-90fb-1eb5c973f809.png) ?

**Comment by varora1406** [comment]
okay, I got it solved (y)

**Comment by DanTup** [comment]
> Is this error related to formatting?

It's correct that the formatter will not format an invalid document, however your original error (about there not being a formatter available) will have been because of the SDK not being found (#510).
