### ISSUE TITLE
Inlay Hints as "on" doesn't work

### ISSUE THREAD

**Issue by lucas404x** [Dart-Code/Dart-Code#4362]
The hints appears only when I'm holding ctrl + alt even if the option selected is "on".

![image](https://user-images.githubusercontent.com/42918677/214646098-5878f14c-c58e-4531-bd6d-be70d8c4e177.png)
![image](https://user-images.githubusercontent.com/42918677/214646176-6fcc6f26-d9ba-4136-bf26-96c395363c37.png)

But when I hold ctrl + alt:
![image](https://user-images.githubusercontent.com/42918677/214646399-f14bce51-0eeb-49e4-9868-25ae03facbe4.png)

Dart extension version: v3.58.0

[✓] Flutter (Channel stable, 3.7.0, on Microsoft Windows [Version 10.0.22623.1180], locale en-US)
    • Flutter version 3.7.0 on channel stable at C:\Users\Desktop\fvm\versions\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (2 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at C:\Users\Desktop\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.18)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32802.440
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.74.3)
    • VS Code at C:\Users\Desktop\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22623.1180]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 109.0.5414.75
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 109.0.1518.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by DanTup** [comment]
To change this, you need to set this setting explicitly for Dart, see:

https://dartcode.org/releases/#:~:text=You%20can%20change%20the%20behaviour%20with%20the

The reason for this is that we override the default (for Dart only) to `offUnlessPressed` because we feel it's a better default for Dart than always on (which is VS Code's default), but global settings in VS Code do not override language-specific defaults.

Unfortunately the VS Code UI doesn't do a very good job making this clear (it's what the "Modified Elsewhere" tag you see next to this setting is trying to indicate).

Hope this helps!
