### ISSUE TITLE
Pause on pause unexpectedly and unable to resume

### ISSUE THREAD

**Issue by Cat-sushi** [Dart-Code/Dart-Code#4371]
Dart Code v3.58.0
Dart SDK version: 3.0.0-179.0.dev (dev) (Unknown timestamp) on "linux_x64"

I'm not sure this is an issue of Dart Code or Dart VM.
After the pause, Isolates should be spauwned.

![Screenshot from 2023-02-01 16-42-34](https://user-images.githubusercontent.com/10280770/215984546-64c3011f-c5f3-45bb-898a-acb86c99972b.png)

From terminal, the program can run.

```terminal
$ dart --observe run bin/wserver.dart 
The Dart VM service is listening on http://127.0.0.1:8181/h2tlrxy6fK4=/
The Dart DevTools debugger and profiler is available at: http://127.0.0.1:8181/h2tlrxy6fK4=/devtools?uri=ws://127.0.0.1:8181/h2tlrxy6fK4=/ws
IDb.read : 1831
Db.fromIDb : 281
Servers started: 2023-02-01 16:49:31.086807
Server listening on port 4049
```

**Comment by Cat-sushi** [comment]
There should be 4 isolates named `Client.serverMain`.

![Screenshot from 2023-02-01 17-12-51](https://user-images.githubusercontent.com/10280770/215987239-768951fe-e03b-46e7-b2d8-87167a579bab.png)

**Comment by Cat-sushi** [comment]
The log is here.
https://gist.github.com/Cat-sushi/ff3bac66c00a05b4dec459c6787e7108

And the application is here
https://github.com/Cat-sushi/fmatch

Don't mind the AGPLv3 license.
You can use the code freely for reproduction of this issue.
This message is the second license.

`wserver.dart` is the entry point.

**Comment by Cat-sushi** [comment]
The number of isolate of `Client.serverMain` is depend on the number of cpu cores.
If you want to fixed number of isolates, run `dart bin/wserver -s4`, for example.

**Comment by DanTup** [comment]
Thanks for the log - from this I can see that the isolates are pause-on-exit. It looks like this is the same issue that came up in https://github.com/Dart-Code/Dart-Code/issues/4368 very recently.

The new debug adapters run the application with `--pause-isolates-on-exit` to avoid some race conditions. They should be automatically resumed once some async work completes. However, the VM does not correctly handle resuming these paused-on-exit isolates.

So as a quick workaround, please add this to your VS Code User Settings JSON:

```
// Disable new SDK DAPs - https://github.com/Dart-Code/Dart-Code/issues/4368
"dart.previewSdkDaps": false,
```

And in the future when you have a newer Dart SDK that includes the fix made in https://github.com/dart-lang/sdk/issues/51164, you'll be able to remove this (or probably the setting will be removed at some point anyway) and the new debug adapters won't have this issue.

Please let me know if that doesn't solve the issue.

**Comment by Cat-sushi** [comment]
@DanTup 
For your information, the isolates named `Client.serverMain` are resident, and don't exit.

**Comment by Cat-sushi** [comment]
With `"dart.previewSdkDaps": false,`, an error occurred.
It seems a bug of Dart VM, but strangely, the app can run  with debug options from terminal.

```terminal
Connecting to VM Service at http://127.0.0.1:32881/ObcXiWSPUw8=/
IDb.read : 1889
Db.fromIDb : 275
Unhandled exception:
IsolateSpawnException: Unable to spawn isolate: Failed to deserialize the passed arguments to the new isolate.
Exited (255)
```

**Comment by DanTup** [comment]
I see that same exception running with the new DAPs, although only when breaking on exceptions - it doesn't seem to be printed to the console (which may be related to the isolate not resuming correctly, I'm not sure).

It seems to only occur when running from the terminal if you pass `--enable-asserts` (which the debugger does by default):

```
dart --enable-asserts bin/wserver.dart 

IDb.read : 500
Db.fromIDb : 93
Unhandled exception:
IsolateSpawnException: Unable to spawn isolate: Failed to deserialize the passed arguments to the new isolate.
```

If I create a `.vscode/launch.json` and disable asserts, then that exception is not seen:

```js
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "fmatch",
			"request": "launch",
			"type": "dart",
			"enableAsserts": false,
		}
	]
}
```

Between those two things (disabling asserts and using the legacy DAPs), the server seems to start up correctly.

**Comment by Cat-sushi** [comment]
With `"enableAsserts": false` the server started.
