### ISSUE TITLE
Android emulator error on vscode

### ISSUE THREAD

**Issue by alijamal6459** [Dart-Code/Dart-Code#4375]
**Describe the bug**
Whenever i run an app on vscode, the emulator randomly loses connection. it works fine on android studio but for some reason it loses connection randomly or on hot reload/restart on vscode.

**To Reproduce**
Running app flutter app including the default counter app

**Please complete the following information:**
 - Operating System and version: win11
 - VS Code version: 1.75
 - Dart extension version: 3.58
 - Dart/Flutter SDK version: 3.7.1
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
Could you try capturing debugging logs while reproducing this?

- Run the [**Dart: Capture Debugging Logs** command](https://dartcode.org/docs/logging/#capture-debugging-logs)
- Reproduce the issue
- Click **Cancel** on the logging notification to stop logging and open the log
- Remove anything sensitive from the log
- Attach the log here, in a [gist](https://gist.github.com/), or email to me at logs@dartcode.org.

Thanks!
