### ISSUE TITLE
Selecting type name does not highlight references

### ISSUE THREAD

**Issue by blaugold** [Dart-Code/Dart-Code#4376]
**Describe the bug**

Selecting a type name does not highlight references to the type in the current file.

**To Reproduce**

See video.

**Expected behavior**

I feel like selecting a type name did at some point cause references to be highlighted like it is the case for constructors in the included video, but I'm not sure anymore :)

**Screenshots**

https://user-images.githubusercontent.com/5929595/216793327-84dc758e-6fb3-4d7a-9105-674f689aa5f0.mov

**Please complete the following information:**
 - Operating System and version: macOS 13.1 (22C65)
 - VS Code version: 1.75.0 
 - Dart extension version: 3.58.0
 - Dart/Flutter SDK version: Flutter 3.7.1 Dart 2.19.1
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
Fixed by https://dart-review.googlesource.com/c/sdk/+/281182.

This change is in the Dart analysis server so will ship with a future Dart/Flutter SDK release rather than show up in the VS Code extension release.
