### ISSUE TITLE
feat: Generate test files

### ISSUE THREAD

**Issue by patricktcoakley** [Dart-Code/Dart-Code#4382]
**Is your feature request related to a problem? Please describe.**
Currently it seems the only way to generate a test file is to use the 'Go to Test/Implementation File' command, which will scaffold a very basic test file.

**Describe the solution you'd like**
It would be great if we were able to generate test files contextually around classes, functions, or methods inside of a source file, similar to some other language extensions. An example of this is the Go extension.

**Describe alternatives you've considered**
As a first step, even just having a more straightforward command to generate the existing test file using keyboard shortcuts that explicitly was for generating test files would be nice.

**Comment by DanTup** [comment]
Do you have some examples of exactly what you'd like to be generated here? For example, given an example class, function and method, what file (name + contents) would you expect/like to be created?

**Comment by patricktcoakley** [comment]
So I spent some time looking at other projects as well as playing with extensions that have desired behavior. There doesn't seem to be a common convention for how folks are writing their Dart tests, so I just decided to find a common ground. I think a basic layout could consist of something like:

Given a Dart file of `my_class.dart`
```dart
class MyClass {
  int add(int a, int b) {
    return a + b;
  }

  bool validate(String input) {
    return input == 'mystring';
  }
}
```

the desired output of `my_class_test.dart` might be something like:

```dart 
import 'package:test/test.dart';

void main() {
  setUp(() async {

  });
  tearDown(() async {

  });

  group('MyClass', () {
    test('.add', () async {

    });

    test('.validate', () async {

    });
  });
}
```
where the command could prompt you to generate tests per method in a prompt with checkboxes in the same way the Java extension for VSCode works:

<img width="613" alt="Screenshot 2023-02-16 at 5 09 38 PM" src="https://user-images.githubusercontent.com/4954180/219498374-ccc3e770-e76f-452f-88cf-a5152ca9312b.png">

I'm open to other styles as well but I think this could work as a starting point. For top-level functions I guess you could do a similar prompt and just generate `test`s:

```dart
import 'package:test/test.dart';

void main() {
  setUp(() async {

  });

  tearDown(() async {

  });

  test('add', () async {

  });

  test('validate', () async {
    
  });
}
```

I'm not sure how many people use `setup` and `tearDown` regularly but maybe that could also be in the prompt? Otherwise it's easy enough to delete as a default.

**Comment by DanTup** [comment]
> There doesn't seem to be a common convention for how folks are writing their Dart tests, so I just decided to find a common ground. 

Yeah, this was my worry. If people don't structure things the same way, this feature might not be used by many. The conventions above seem reasonable to me, but it would be good to collect some feedback (and 👍 's) here. I also wonder whether Flutter projects might have different conventions?

Implementing something like this would need the bulk of the work done in the Dart analysis server (because the extension doesn't parse code so can't reliable find out the class/methods itself) so we'd need to meet the bar to get into the SDK with anything done here.

(if you know others that may be interested in this, please encourage them to add feedback and/or 👍 s!)
