### ISSUE TITLE
Code actions are not showing

### ISSUE THREAD

**Issue by incendial** [Dart-Code/Dart-Code#4385]
**Describe the bug**
VS Code does not show code actions and display an infinite loader which usually ends with "no code actions".

**To Reproduce**
For me it's usually: 1) create a file 2) copy some code into it

**Expected behavior**
The actions will be shown.

**Screenshots**
Please pay attention to the progress indicator on top of the file (sorry for the low quality, GitHub has a pretty strict limit on video size).

https://user-images.githubusercontent.com/21116742/218468343-28001be8-95f5-4382-b547-798c246c1562.mov

https://user-images.githubusercontent.com/21116742/218468360-08e9285b-da8d-41b2-97a9-2f2fc1239fef.mov

**Please complete the following information:**
- Operating System and version: macOS 12.6
- VS Code version: 1.75.1
- Dart extension version: 3.58
- Dart/Flutter SDK version: Dart SDK version: 2.19.0 (stable) (Mon Jan 23 11:29:09 2023 -0800) on "macos_x64"
- Target device (if the issue relates to Flutter debugging): -

**Comment by DanTup** [comment]
Can you reproduce this reliably? Does it ever complete if you leave it?

I'd expect to see this if the server was busy (for example you'd just opened the project and it was performing initial analysis), but not just after copying a file. If you have any exact steps that might help me repro this, that would really help. Thanks!

**Comment by incendial** [comment]
> Can you reproduce this reliably? Does it ever complete if you leave it?

Yes, it appears quite reliably and often and no, it does not complete 😞

But I've noticed that if I move the cursor to another position on the line (which is not highlighted), it instantly shows the suggestion to import. Considering that I also have DCM extension enabled I have a slight impression that it might be a VS Code bug.

**Comment by DanTup** [comment]
Next time you see this, could you try the following:

- Run the **Dart: Open Analyzer Diagnostics** command from the palette
- Click **Timings** on the left
- Look for a `textDocument/codeAction` request that has a large time recorded
- Click on the time
- Copy/paste the breakdown here

You should get something like:

```
Request 'textDocument/codeAction'
Request latency: 0 ms.
Request start time: 2023-02-21T10:37:33.194822.

(name: request, count: 1, elapsed: 0:00:00.063567, elapsedSelf: 0:00:00.049320)
  (name: ServerDartActionsComputer.getSourceActions, count: 1, elapsed: 0:00:00.000023, elapsedSelf: 0:00:00.000023)
  (name: PluginActionsComputer.getSourceActions, count: 1, elapsed: 0:00:00.000001, elapsedSelf: 0:00:00.000001)
  (name: ServerDartActionsComputer.getFixActions, count: 1, elapsed: 0:00:00.000026, elapsedSelf: 0:00:00.000026)
  (name: PluginActionsComputer.getFixActions, count: 1, elapsed: 0:00:00.000019, elapsedSelf: 0:00:00.000019)
  (name: ServerDartActionsComputer.getAssistActions, count: 1, elapsed: 0:00:00.005273, elapsedSelf: 0:00:00.005273)
  (name: PluginActionsComputer.getAssistActions, count: 1, elapsed: 0:00:00.000018, elapsedSelf: 0:00:00.000018)
  (name: ServerDartActionsComputer.getRefactorActions, count: 1, elapsed: 0:00:00.008877, elapsedSelf: 0:00:00.008877)
  (name: PluginActionsComputer.getRefactorActions, count: 1, elapsed: 0:00:00.000010, elapsedSelf: 0:00:00.000010)
```

These numbers might help understand where the time is going, although it might onyl be useful if the request actually completed.

Can you also confirm whether it's a public/open source project you're seeing this in, or a private codebase?

**Comment by incendial** [comment]
I have finally found the problem and it was me 😅 I occasionally introduced a bug in DCM 🤦‍♂️
Thank you for your help!

**Comment by DanTup** [comment]
Ah, glad you figured it out :-)
