### ISSUE TITLE
Remember/restore imports when code is copied/pasted

### ISSUE THREAD

**Issue by lukehutch** [Dart-Code/Dart-Code#4393]
**Is your feature request related to a problem? Please describe.**

In Eclipse, if you copy Java code from one source file and paste into another, the imports used by the copied code are recorded in clipboard metadata, and then when the code is pasted, any required imports that are not already present are automatically inserted into the header.

VS Code does not do this, at least with Flutter code. This means that when you paste code into a new file, you have to manually add all the required imports.

**Describe the solution you'd like**

Please have the VS Code Flutter plugin record which imports each symbol depends upon on copy, and restore these if necessary on paste.

**Comment by DanTup** [comment]
There's an open issue for this at #351. Unfortunately it's currently blocked on VS Code not providing APIs for copy/paste (https://github.com/microsoft/vscode/issues/30066). Please add 👍  to that VS Code issue if this is something you'd like to see added (it seems like they've started on this, but it keeps being pushed back).

Thanks!

**Comment by lukehutch** [comment]
Will do. Sorry for the dup, I didn't spot that issue. Thanks!

**Comment by DanTup** [comment]
np! The GitHub search isn't great (and it's not always obvious what to search for). I'd much rather have duplicate issues than miss bugs/feature requests :-)
