### ISSUE TITLE
Image Picker

### ISSUE THREAD

**Issue by MumtazAli123** [Dart-Code/Dart-Code#4395]
I get the  problem  in image picker on ios simulator  or on  physical  device so guide how can i get permission

**Comment by DanTup** [comment]
Can you confirm which image picker you mean? This repository is for the VS Code extension but I think your issue might be related to a Flutter widget/API/package?

**Comment by MumtazAli123** [comment]
Yes Sir i get issue in a flutter app on android studio on mac

**Comment by DanTup** [comment]
This repository is for the Dart/Flutter extensions for VS Code, not for asking general Flutter questions. I would suggest asking for help on StackOverflow/Discord/etc. There are some links to various communities for these sorts of questions here:

https://flutter.dev/community#:~:text=Get%20involved%20and%20ask%20questions

Hope this helps!
