### ISSUE TITLE
Silent Disconnection

### ISSUE THREAD

**Issue by riccardocescon** [Dart-Code/Dart-Code#4399]
**Describe the bug**
After hot restarting during an exception the connected device got disconnected without any warning

**To Reproduce**
- set `"dart.previewSdkDaps": true,`
- check `All Exceptions` Breakpoint
- set any Exception on button click (i used Unimplemented)
- press the button
- see the debugger stop you on the exception
- hot restart
- after a few seconds your device got disconnected without writing Disconnected Device or killing the app

**Expected behavior**
After the hot restart the device should be connected

**Please complete the following information:**
 - Operating System and version: Windows 10
 - VS Code version: 1.75.1
 - Dart extension version: 2.19.2
 - Dart/Flutter SDK version: 3.7.3
 - Target device: Pixel 6, Android 13

**Comment by DanTup** [comment]
I haven't been able to repro this on `stable` or `master`, using either iOS simulator or Android emulator.

Could you:

- check if it only happens on a physical device or also an emulator?
- check if you can you reproduce it in a newly-created counter app (with `throw UnimplementedError()` in `_incrementCounter`)
- capture a log as described below

To capture a log, run the **Dart: Capture Debugging Logs** command from the VS command palette, then start the debug session and reproduce the issue. Then click **Cancel** on the logging notification to stop logging and open the file. There may be an error recorded near the end of the log that might explain the disconnection.

You can mail logs to me at logs@dartcode.org. Please ensure there's nothing sensitive in them (ideally, capture logs using the counter app if it repros there).

Thanks!

**Comment by riccardocescon** [comment]
Sadly i wasn't able to reproduce the issue on an empty app.
The issue happened on the android emulator too but with the project i am working on.
I think that the issue is the same as "dart.previewSdkDaps": false, where if it's disabled simply the log won't be shown but the hot restart works, if that's enabled when it should stop logging it just crashes.
I sent you the crash log i got from my project to you email.

Can i help you more?

**Comment by DanTup** [comment]
Thanks - unfortunately there's nothing obvious in the logs. If it doesn't repro in an empty app, there may be something specific in your app or dependencies triggering it. Would it be difficult for you to make a copy of your app and strip it down to something that still triggers the issue but that you can share?

Or is there anything you can think of that's significantly different between your app and the empty app? (things like Isolates, plugins, any code running at startup in `main()` besides `runApp`?).

**Comment by riccardocescon** [comment]
I tried to reproduce the main on a sample app without any success, on a new project i cannot make the device disconnect during a hot restart.
But i found out something interesting:
on my main i have wrapped the runApp with the `runZonedGuarded`. On the `onError` callback i am showing an error snackbar such as: `showErrorSnackBar(NavigationService.navigatorKey.currentContext!);`.
The showSnackbar function looks like this:
```dart
ScaffoldMessenger.of(receivedContext).showSnackBar(
    SnackBar(
      behavior: SnackBarBehavior.floating,
      content: GestureDetector(
        onTap: () {
          onTap?.call();
        },
        child: AwesomeSnackbarContent(
          title: _snackbarTitle[contentType] ?? "Info",
          message: message,
          contentType: contentType,
          color: _snackbarColor[contentType],
        ),
      ),
      padding: const EdgeInsets.only(top: 20, bottom: 10, left: 20, right: 20),
      backgroundColor: Colors.transparent,
      elevation: 0,
      duration: duration ?? const Duration(seconds: 5),
    ),
  );
  ```
  I noticed that if i comment out this function, or i simply remove the AwesomeSnackbarContent and use a Text widget, the issue won't happen.
 Still i could not be able to reproduce this on the counter app.
 May it be that my project is much more larger than the counter app so the issue happens with something related to hot restart timing?

**Comment by DanTup** [comment]
> May it be that my project is much more larger than the counter app so the issue happens with something related to hot restart timing?

It could be. Is it possible you can modify https://github.com/flutter/gallery to behave the same way your app does, and trigger the same kind of error to see if it repros there? (The gallery isn't huge, but it is much bigger than the counter app).

**Comment by riccardocescon** [comment]
I tried multiple times to trigger the same error on the gallery app without success, but i found out something new.
On my project i switched from `Stable `channel to `Master (3.8.0-15.0.pre.26)`.
On the master channel, if i enable `"dart.previewSdkDaps": true,` there is no issue, i can hot restart multiple times when it crashes and the device won't disconnect and the logger will just work.
    By disabling that feature the device won't disconnect but simply the logger will stop working.
    So that's what i found out:

- `Stable without previewSdkDaps` ---> Logger won't work after hot restart during an exception
- `Stable with previewSdkDaps` ---> Device got disconnected after hot restart during an exception
- `Master without previewSdkDaps` ---> Logger won't work after hot restart during an exception
- `Master with previewSdkDaps` ---> Everything works as expected

Is there anything i can do in order to help you find what's happening?

**Comment by riccardocescon** [comment]
I am using the Master with preview from a week and everything is working without any issue, so i think this issue can be closed.
Thank you!

**Comment by DanTup** [comment]
sgtm - do let me know if you see the issue again on that combination though!
