### ISSUE TITLE
Add separate overrides for Fuchsia and Flutter SDKs (+ tidy search logic)

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#440]
Flutter and Fuchsia require specific versions (or patched) SDKs so using the same override doesn't really make sense (though was added in #437 as a short-term fix).

We should add equiv options to userDefinedSdkPath for these, and also probably userDefinedSdkPaths (and do #441).

**Comment by DanTup** [comment]
@yyoon @devoncarew Ok, I documented all of the current search paths and it turned out that it's rather complicated! I've added new overrides in for all SDKs for all project types and the list is below (marked with **NEW**). The settings are individual, so the Flutter SDK override is different to the Fuchsia Flutter SDK override - I'm assuming that if you're doing both Flutter and Fuchsia dev (for ex.) and you choose to override the Flutter SDK path for Flutter dev, it might not be appropriate to use that for Fuchsia. For the same reason, we don't currently fall back to searching the other paths (for example, if for Fuchsia we can't find a Dart SDK in the override or the local Fuchsia folder, we will not start searching PATH, etc.; since again, I don't know if it's appropriate to have use the generic SDKs). I don't know if this idea is sound.

**Dart project**
- Dart SDK
  1. `userDefinedSdkPath`
  1. `[%PATH%]`

**Flutter project**
- Flutter SDK
  1. `userDefinedFlutterSdkPath` (**NEW**)
  1. workspace root
  1. extract from packages file
  1. `%FLUTTER_ROOT%`
  1. `[%PATH%]`
- Dart SDK
  1. `userDefinedFlutterDartSdkPath` (**NEW**)
  1. `(Flutter SDK)/bin/cache/dart-sdk`

**Fuchsia project**
- Fuchsia SDK
  1. `userDefinedFuchsiaSdkPath` (**NEW**)
  1. workspace root (walking up looking for .jiri_root)
- Flutter SDK
  1. `userDefinedFuchsiaFlutterSdkPath` (**NEW**)
  1. `(Fuchsia SDK)/third_party/dart-pkg/git/flutter`
- Dart SDK
  1. `userDefinedFuchsiaDartSdkPath` (**NEW**)
  1. `(Fuchsia SDK)/third_party/dart/tools/sdks/(platform)/dart-sdk`

Does this all sounds like the best way to go (as an aside, if all IDEs are having to do all of this, probably it could be simplified or at least made consistent across the different project types)?

I want to expand the `sdkContainer`/quick switching feature (which I incorrectly referred to as userDefinedSdkPaths yesterday) support to handle all of these too to allow for fast switching, though given the number of override options above, it looks like it'd mean 6 of them (so in total, 12 options for SDK paths across 3 project types). Before I embark on this, I want to be sure it makes sense to you two.

**Comment by devoncarew** [comment]
Hmm, I don't understand all the above. This is for auto-detection of SDKs, or auto-detection and explicit configuration, or both?

It may be useful to try and simplify the above, if only to minimize bugs and make the sdk used a bit more predictable for the user. Perhaps have arbitrary auto-magic detection if there's no sdk set, but once one is found, automatically set the sdk config setting for the user (and notify them that we did)?

I'm less familiar w/ why there's a separate fuchsiaFlutterSdkPath / fuchsiaDartSdkPath path. In IntelliJ, we do have a separate 'flutter sdk' config setting. That's mostly for easy discoverability for the user though. When you set that setting, it'll automatically set the dart sdk setting (based on the flutter sdk and bin/cache/dart-sdk). We do support per project values for the sdk setting, and remember all the ones globally, in order to have a good set of values to choose from for new projects. We do still have issues w/ the overall sdk setting logic - esp. with new project creation - so improvements and ideas for the process definitely welcome :)

**Comment by DanTup** [comment]
@devoncarew 

> Hmm, I don't understand all the above. This is for auto-detection of SDKs, or auto-detection and explicit configuration, or both?

It's the list of places we'll search for each SDK at startup. If you ignore the ones marked NEW then it's what we already do today. Some of them don't have overrides and that's an issue for this scenario [described by](https://github.com/Dart-Code/Dart-Code/pull/437#issuecomment-344336935) @yyoon:

> Occasionally, there could be some gap between when a fuchsia-change is made and when it gets shipped in the new version of SDK. That's when we need to temporarily switch to the locally built Dart SDK instead of the prebuilt one, to make the Dart analysis work correctly.

So there needs to be a way to override the Dart SDK for a Fuchsia project. The current fix uses `dart.sdkPath` but this doesn't seem ideal - if this is a Fuchsia-specific (or even just unstable) SDK you might want to use it for Fuchsia, but not Dart (or Flutter) projects. So, per-project-type overrides seem to make sense. However because the number of SDKs is large (1 for Dart, 2 for Flutter, 3 for Fuchsia) it makes the lists quite long!

> It may be useful to try and simplify the above, if only to minimize bugs and make the sdk used a bit more predictable for the user.

That's kinda what I'm trying to do... currently this isn't documented anywhere so I was trying to build a list so it can at least be seen by the user (I also hope to simplify the code so it looks just like a list, rather than a bunch of code with conditionals). A lot of the complexity comes from there not being standard places for the SDKs or ways of detecting them.

> Perhaps have arbitrary auto-magic detection if there's no sdk set, but once one is found, automatically set the sdk config setting for the user (and notify them that we did)?

I'm concerned that if we stamp the setting based on the result of the search, we might end up doing the wrong thing (eg. if a Flutter SDK lives inside a project folder, it doesn't make sense to make that projects version the one used for all Flutter projects). It's also something for the user to then maintain - if we can auto-detect it (eg. from PATH) it seems to just make sense to do it every time (for ex. if the user changes PATH to point at a different SDK, it'll still work).

> I'm less familiar w/ why there's a separate fuchsiaFlutterSdkPath / fuchsiaDartSdkPath path.

This is for the comment quoted above - Fuchsia sometimes needs to use a locally built Dart SDK (I don't know if Flutter has a similar issue - if the Flutter team were using VS Code for core Flutter dev and needed to make changes to the Dart SDK, how could they get those changes immediately without waiting for a dev Dart SDK build?).

> We do still have issues w/ the overall sdk setting logic - esp. with new project creation - so improvements and ideas for the process definitely welcome :)

I don't think what we have listed above is that bad, there are just a few weird things:

1. Flutter SDK using FLUTTER_HOME and extracting from packages seems strange; however I think these are necessary for new projects unless it becomes common for Flutter in be in PATH (which on the surface seems like a good idea to me, rather than having project-local copies, but I'm sure it's not that simple)
2. Fuchsia SDK walking up looking for `.jiri_root` feels like a hack
3. Dart SDK for Fuchsia has platform in the search path

If those things were eliminated, I think the search paths would actually be pretty simple. There might still be some slight confusion over Fuchsia and Flutter having "their own" versions of the Dart SDK which may need their own overrides, but at least it'd be easy to document and explain the search path to uses if we don't find something.

**Comment by yyoon** [comment]
Sorry for my late reply. Your proposal seems okay and I don't mind it too much, but overall it also feels overly complicated to me, when looking at the entire sdk path configurations outlined here.

The auto-detection is great, because in normal situations you don't even have to worry about setting the sdk path. However, I still think that sdk path override could be done per project, in their Workspace Settings. When overriding the sdk path, you probably know what you're doing, and it's going to be a one-time thing to do.

Another point against adding project-specific overrides is that it might confuse users more than helping them. I could imagine someone on Flutter or Fuchsia project mistakenly setting the `dart.sdkPath` instead of the project-specific ones, and being confused as to why the setting is not taking effect.

**Comment by DanTup** [comment]
@yyoon I did think about that - overriding the SDK in the workspace would allow the same setting to be used because it'd already be scoped to the Dart/Flutter/Fuchsia project.

The only problem is that if you do set it globally (as I often do, using the quick SDK switcher) then you could get an incorrect one. There's also a question of whether the SDK switcher should then edit the workspace or user setting.

That said; most of my testing of different SDKs is in a simple trivial sample app I use for testing/reproing, so maybe just making the switcher work at the workspace level all the time wouldn't make much different to me, and then all the above would work.

We'd still end up with three overrides, but it would eliminate FuchsiaFlutter, FuchsiaDart and FlutterDart override options.

A downside of doing this though would be that you can't really commit the workspace settings (it has paths in that are likely local to your machine). I suspect this is fairly common (Dart Code has this committed for example).

I'll think about this a little more, but I think maybe you've convinced me.

**Comment by DanTup** [comment]
Ok, made good progress on this and much happier with it now. I've flattened all the old methods (which were somewhat inconsistent - some took paths and only searched there, while others also searched PATH etc.). Code looks much simpler now:

```js
const flutterSdkSearchPaths = [
	// TODO: config.flutterSdkPath,
	fuchsiaRoot && path.join(fuchsiaRoot, "lib/flutter"),
	fuchsiaRoot && path.join(fuchsiaRoot, "third_party/dart-pkg/git/flutter"),
	flutterProject,
	flutterProject && extractFlutterSdkPathFromPackagesFile(path.join(flutterProject, ".packages")),
	process.env.FLUTTER_ROOT
].concat(paths);

const dartSdkSearchPaths = [
	config.userDefinedSdkPath,
	fuchsiaRoot && path.join(fuchsiaRoot, "third_party/dart/tools/sdks", platformName, "dart-sdk"),
	fuchsiaRoot && path.join(fuchsiaRoot, "dart/tools/sdks", platformName, "dart-sdk"),
	flutterSdkPath && path.join(flutterSdkPath, "bin/cache/dart-sdk")
].concat(paths);
```

It's not perfect (all the `xxx &&` is to handle where they're not appropriate, without having to write `if` statements to conditionally push onto the array) but much easier to understand than previously being split across a load of methods (and it not being clear when which options worked).

The Dart SDK override does always still come first (I've compared the results of the new code to the old and ensured the results are all the same) and I will add an override for flutter to handle the remaining case.

For now there won't be a Fuchsia override, since it doesn't look like we actually use the Fuchsia path for anything except finding Flutter/Dart. That means just two overrides, not 6 :-) I'll add a flutter override before closing this case.

**Comment by DanTup** [comment]
`dart.flutterSdkPath` now exists so the logic is as posted above with the TODO uncommented.

**Comment by yyoon** [comment]
Looks good to me! Much nicer than the original proposal.
