### ISSUE TITLE
Add ability to insert all required arguments at once

### ISSUE THREAD

**Issue by charafau** [Dart-Code/Dart-Code#4402]
Currently when adding required fields to the constructor, quick fix suggests to insert fields one by one. 
It would be nice to be able to insert all required fields at once and then jump from one field to another with tab key.

![image](https://user-images.githubusercontent.com/1143994/220898361-8d3b8443-5c1d-4cc9-aa82-1c41b6017308.png)

Basically add "Add all required fields" option

**Comment by DanTup** [comment]
Sorry I didn't reply to this earlier - I somehow missed the notification.

This would need implementing in the Dart analysis server and there's an open issue tracking this here:

https://github.com/dart-lang/sdk/issues/46915

You can subscribe to that issue for updates. Thanks!

**Comment by charafau** [comment]
thank you, subscribed!
