### ISSUE TITLE
Cannot launch from VS code but can launch from CLI because CocoaPods is not found

### ISSUE THREAD

**Issue by kenzieschmoll** [Dart-Code/Dart-Code#4404]
Attempting to run DevTools on the macos target from VS code:
Launch config:
```
        {
            "name": "devtools",
            "request": "launch",
            "type": "dart",
            "program": "devtools_app/lib/main.dart",
        },
```
```
Launching lib/main.dart on macOS in debug mode...
main.dart:1
Warning: CocoaPods not installed. Skipping pod install.
  CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
  Without CocoaPods, plugins will not work on iOS or macOS.
  For more info, see https://flutter.dev/platform-plugins
To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

Exception: CocoaPods not installed or not in valid state.
Exited
```

App runs successfully from CLI
```
flutter run -d macos
Launching lib/main.dart on macOS in debug mode...
Running pod install...                                           2,839ms
Building macOS application...
flutter: DevTools version 2.22.2-dev.2.
Syncing files to device macOS...                                   321ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

An Observatory debugger and profiler on macOS is available at:
http://127.0.0.1:57411/V8S16NafUMk=/
The Flutter DevTools debugger and profiler on macOS is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:57411/V8S16NafUMk=/
```

**Comment by DanTup** [comment]
This came up before in #4305. My feeling is that this is `PATH` related, and the Ruby `bin` folder isn't in the `PATH` that VS Code is getting.

In https://github.com/Dart-Code/Dart-Code/issues/4305#issuecomment-1344729009 I noted that I had mine set in `~/.zprofile` which _seems_ to apply to the whole session, inc. VS Code. If you have it set in something else (like `.bashrc`) that might only apply to terminals, and not apps launched from the Dock (etc.).

**Comment by kenzieschmoll** [comment]
I don't have a `.bashrc` file on my mac at all. Neither my `.bash_profile` nor `.zprofile` have anything related to ruby in them. Typing `which ruby` on my machine shows `/usr/bin/ruby`

I'm a bit confused why cocoa pods has anything to do with ruby? Are the two related?

**Comment by DanTup** [comment]
> I'm a bit confused why cocoa pods has anything to do with ruby? Are the two related?

Cocoapods is a Ruby gem. If I type `where pod`, I get:

```
/Users/danny/.gem/ruby/2.6.0/bin/pod
```

I don't see a Ruby bin folder like that in your working log though. What happens if you type `where pod`? If it prints a path that is in your second log above, but not the first, then that's likely the issue. In which case the question is who is adding it to `PATH` for your terminal, but not for VS Code? Is it in the output of running `/usr/libexec/path_helper`?

**Comment by kenzieschmoll** [comment]
`where pod` ==> `/usr/local/bin/pod`

here is the output of path_helper:

`PATH="/usr/local/git/git-google/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/Users/kenzieschmoll/develop/flutter/bin:/Users/kenzieschmoll/develop/:/Users/kenzieschmoll/.pub-cache/bin:/Users/kenzieschmoll/develop/depot_tools:/Users/kenzieschmoll/develop/flutter/bin/cache/dart-sdk/bin"; export PATH;`

**Comment by DanTup** [comment]
@kenzieschmoll do you know where `/usr/local/bin` is being added to your `PATH`? Is it in one of the terminal scripts mentioned above (`.bashrc`, etc.)?

**Comment by kenzieschmoll** [comment]
In my `.zshrc` file, this line is actually commented out: `# export PATH=$HOME/bin:/usr/local/bin:$PATH`.

It is not added in my `.bash_profile` either. I checked all the bash and zsh config files and couldn't find this. I looked at several files in `/etc/` as well and didn't see it. Where should I put `/usr/local/bin` on my PATH so that VS code will pick it up?

**Comment by DanTup** [comment]
I would try adding it to `.zprofile` or `.bash_profile` (they may be shell-specific, so you may want to try both).

It might also work in `/etc/paths` or a file inside `/etc/paths.d/`, although since it's already in the output of `path_helper` I'm not sure.

I wish there was a better way for us to handle this - it's something that comes up a fair bit (because adding things to `PATH` in a way that only applies to terminals is apparently easy / the most common way on both macOS and Linux), but I haven't been able to come up with anything. In the case of this one, the VS Code extension doesn't really know what things `flutter` will try to locate from `PATH` so it's hard to even know when this is happening.

I wonder if `flutter` might be able to get more info when this condition occurs.. for example if it fails to find a toool on `PATH`, is it possible it could spawn `echo $PATH` through a shell (in a way that would run the scripts setting `PATH`) and compare that to its own `PATH` and print a more specific message. It might be more effort than it's worth though. @christopherfujino any thoughts?

**Comment by christopherfujino** [comment]
> I wonder if `flutter` might be able to get more info when this condition occurs.. for example if it fails to find a toool on `PATH`, is it possible it could spawn `echo $PATH` through a shell (in a way that would run the scripts setting `PATH`) and compare that to its own `PATH` and print a more specific message. It might be more effort than it's worth though. @christopherfujino any thoughts?

Would calling `echo $PATH` in a shell even yield the same search path for the tool that is spawned by VS Code? Isn't the problem here that the path when spawned by the extension is different from that in the shell config?

I will admit, I spend all my time in shell/terminal, so I don't fully understand what's going on here :)

**Comment by christopherfujino** [comment]
Or just the $PATH env var? https://github.com/google/process.dart/blob/master/lib/src/interface/common.dart#L86

**Comment by DanTup** [comment]
> Would calling `echo $PATH` in a shell even yield the same search path for the tool that is spawned by VS Code?

I'm not sure, but not being the same is what we want. If a user has changes to `PATH` in shell profile scripts which only apply to a terminal, would spawning a shell to run `echo $PATH` and capturing the output let us see the `PATH` a user has in their terminal and that they assume VS Code(/`flutter` inside VS Code) would see?

> Isn't the problem here that the path when spawned by the extension is different from that in the shell config?

Correct. Although it's not so much processes "spawned by the extension" that are missing these extra paths, it's the VS Code process itself (eg. spawned from a dock/launcher), and all the child processes just inherit that.

I'm not familiar with all of these terminal startup/login scripts though, it's entirely possible that executing a process in one non-interactively would also bypass those scripts, and we'd only see the same `PATH` we already had ourselves. I could do some testing of this, and maybe if it works we can discuss whether it's worth the extra work to try and detect this.

Perhaps we could actually do this in the extension (if it works). If we can spawn a shell and get the "users expected PATH", we could append that to the `PATH` we already have when we spawn _any_ processes. I'll try and do some testing, to see whether it is possible.

**Comment by DanTup** [comment]
> Or just the $PATH env var? https://github.com/google/process.dart/blob/master/lib/src/interface/common.dart#L86

This is just reading the current `PATH` we already have though (which is missing things that are set in some of the shell profile scripts, when the IDE was launched outside of the terminal).

**Comment by christopherfujino** [comment]
> I'm not sure, but not being the same is what we want. If a user has changes to `PATH` in shell profile scripts which only apply to a terminal, would spawning a shell to run `echo $PATH` and capturing the output let us see the `PATH` a user has in their terminal and that they assume VS Code(/`flutter` inside VS Code) would see?

Right, I missed the point that you want to show a different path than the one active.

**Comment by christopherfujino** [comment]
> Perhaps we could actually do this in the extension (if it works). If we can spawn a shell and get the "users expected PATH", we could append that to the `PATH` we already have when we spawn _any_ processes. I'll try and do some testing, to see whether it is possible.

Having just spent way too long configuring a non-zsh shell on my new macbook, please make sure you're checking the user's configured shell, looks like via `dscl`? https://stackoverflow.com/a/41553295

**Comment by DanTup** [comment]
Doing a bit more reading, it seems like the difference between files noted above is that some are run for _non-interactive_ sessions and some for _interactive_ sessions. Even if it's possible, I think it's probably not a good idea to execute things a user has put in their _interactive_ shell login scripts (what if they start `tmux` or something?).

I think probably we just need to guide users that are setting `PATH` in files that won't apply to use `.profile`/`.zprofile`.

That said, it's not clear from above that this is @kenzieschmoll's issue. If adding to `.zprofile`/`.profile` (depending on shell) fixes the issue, then we're probably good (although it's still not clear who was adding it to `PATH` in the interactive terminals).

**Comment by christopherfujino** [comment]
> Doing a bit more reading, it seems like the difference between files noted above is that some are run for _non-interactive_ sessions and some for _interactive_ sessions. Even if it's possible, I think it's probably not a good idea to execute things a user has put in their _interactive_ shell login scripts (what if they start `tmux` or something?).
> 
> I think probably we just need to guide users that are setting `PATH` in files that won't apply to use `.profile`/`.zprofile`.
> 
> That said, it's not clear from above that this is @kenzieschmoll's issue. If adding to `.zprofile`/`.profile` (depending on shell) fixes the issue, then we're probably good (although it's still not clear who was adding it to `PATH` in the interactive terminals).

So the tool already has a [config JSON file](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/config.dart#L16) where the user can optionally provide an Android Studio and/or Android SDK path. Maybe we should extend this for other tools we depend on that the user may have installed via some ad hoc package manager (or downloaded to some arbitrary directory). Then, if (for example with `pod install`) the tool fails to find one of these packages, we can hint to the user if they know it's already installed to add that path via `flutter config --cocoa-pods-dir=/path/to/pod`.

@DanTup WDYT?

**Comment by DanTup** [comment]
@christopherfujino I like that idea! Maybe Flutter could even store "last known" paths for these to use as hints?

Eg. if you run `flutter doctor` from the terminal and it finds `pod`, could it store this somewhere (like `flutter config` would) and if it's not on `PATH` later, look there? It might be odd if it just always wrote it to the main config whenever if found it, although maybe not? 🤔

**Comment by christopherfujino** [comment]
> @christopherfujino I like that idea! Maybe Flutter could even store "last known" paths for these to use as hints?
> 
> Eg. if you run `flutter doctor` from the terminal and it finds `pod`, could it store this somewhere (like `flutter config` would) and if it's not on `PATH` later, look there? It might be odd if it just always wrote it to the main config whenever if found it, although maybe not? thinking

Is this specifically to catch the case where the user changed their PATH? Or where their interactive terminal has the path we need, but the VSCode process doesn't?

**Comment by kenzieschmoll** [comment]
I have added `export PATH=/usr/local/bin:$PATH` to my `.zprofile`. I will comment if I see this issue again even after this change.

**Comment by christopherfujino** [comment]
Filed tool tracking issue: https://github.com/flutter/flutter/issues/122035

**Comment by DanTup** [comment]
@christopherfujino 

> Is this specifically to catch the case where the user changed their PATH? Or where their interactive terminal has the path we need, but the VSCode process doesn't?

It was to avoid the user needing to get an error and a message to run `flutter config` :-)

@kenzieschmoll sgtm. The bot will close this after a while if there are no comments, but feel free to close sooner if you feel like it's resolved.

**Comment by christopherfujino** [comment]
> @christopherfujino
> 
> > Is this specifically to catch the case where the user changed their PATH? Or where their interactive terminal has the path we need, but the VSCode process doesn't?
> 
> It was to avoid the user needing to get an error and a message to run `flutter config` :-)

I meant, in what situation would the tool detect cocoapods on Monday but not find it on Tuesday.

**Comment by DanTup** [comment]
> I meant, in what situation would the tool detect cocoapods on Monday but not find it on Tuesday.

User ran `flutter doctor` in a terminal on Monday and used VS Code on Tuesday :-)

**Comment by christopherfujino** [comment]
> > I meant, in what situation would the tool detect cocoapods on Monday but not find it on Tuesday.
> 
> User ran `flutter doctor` in a terminal on Monday (when they installed it) and used VS Code on Tuesday (because everyone ends up using VS Code, eventually :-P )

acknowledged. This seems it would magically work and do the right thing in 90-99% of situations. I'll note it as a suggestion on https://github.com/flutter/flutter/issues/122035

**Comment by yeikel16** [comment]
Hello, I having the same issue when launch my app from the VSCode (Run/Start Debugging), however from the command-line using the `flutter run ./main_dev.dart` not have any error.

```sh

yeikel@MacBook-Pro-de-Yeikel my_app % flutter doctor -v
[✓] Flutter (Channel stable, 3.7.6, on macOS 13.1 22C65 darwin-arm64, locale es-US)
    • Flutter version 3.7.6 on channel stable at /Users/yeikel/fvm/versions/3.7.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12cb4eb7a0 (3 weeks ago), 2023-03-01 10:29:26 -0800
    • Engine revision ada363ee93
    • Dart version 2.19.3
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/yeikel/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/yeikel/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio 2020.3.1.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.76.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • 86FF0D31-D568-4FEB-95D7-565F2555B3F7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 111.0.5563.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

This is the error:

```sh
Launching lib/main_dev.dart on iPhone 12 in debug mode...
main_dev.dart:1
Xcode build done.                                            3.1s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/pq/pw1s__m93bddspkkmq6x7c_h0000gn/T/flutter_tools.w1oQG1/flutter_ios_build_temp_dir3oHoT0/temporary_xcresult_bundle
    note: Building targets in dependency order
    warning: Unable to read contents of XCFileList '/Target Support Files/Pods-Runner/Pods-Runner-frameworks-Debug-dev-output-files.xcfilelist' (in target 'Runner' from project 'Runner')
    warning: Unable to read contents of XCFileList '/Target Support Files/Pods-Runner/Pods-Runner-resources-Debug-dev-output-files.xcfilelist' (in target 'Runner' from project 'Runner')
    note: Run script build phase 'Run Script' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
    note: Run script build phase 'Thin Binary' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
    error: Unable to load contents of file list: '/Target Support Files/Pods-Runner/Pods-Runner-resources-Debug-dev-input-files.xcfilelist' (in target 'Runner' from project 'Runner')
    error: Unable to load contents of file list: '/Target Support Files/Pods-Runner/Pods-Runner-resources-Debug-dev-output-files.xcfilelist' (in target 'Runner' from project 'Runner')
    error: Unable to load contents of file list: '/Target Support Files/Pods-Runner/Pods-Runner-frameworks-Debug-dev-input-files.xcfilelist' (in target 'Runner' from project 'Runner')
    error: Unable to load contents of file list: '/Target Support Files/Pods-Runner/Pods-Runner-frameworks-Debug-dev-output-files.xcfilelist' (in target 'Runner' from project 'Runner')
    warning: Run script build phase '[CP] Embed Pods Frameworks' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
    warning: Run script build phase '[CP] Copy Pods Resources' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
    Result bundle written to path:
    	/var/folders/pq/pw1s__m93bddspkkmq6x7c_h0000gn/T/flutter_tools.w1oQG1/flutter_ios_build_temp_dir3oHoT0/temporary_xcresult_bundle
Error (Xcode): Unable to load contents of file list: '/Target Support Files/Pods-Runner/Pods-Runner-resources-Debug-dev-input-files.xcfilelist'

Error (Xcode): Unable to load contents of file list: '/Target Support Files/Pods-Runner/Pods-Runner-resources-Debug-dev-output-files.xcfilelist'

Error (Xcode): Unable to load contents of file list: '/Target Support Files/Pods-Runner/Pods-Runner-frameworks-Debug-dev-input-files.xcfilelist'

Error (Xcode): Unable to load contents of file list: '/Target Support Files/Pods-Runner/Pods-Runner-frameworks-Debug-dev-output-files.xcfilelist'

Could not build the application for the simulator.
Error launching application on iPhone 12.
Exited
```

When I run the command `where pod`:
```sh
/opt/homebrew/bin/pod
/usr/local/bin/pod
/opt/homebrew/bin/pod
```

**Comment by DanTup** [comment]
@yeikel16 could you open a new issue - I think this is a different cause. Can you also include *both* the full output of running `flutter doctor -v` in a terminal where it works, and the output of running the **Flutter: Run Flutter Doctor** command from the VS Code command palette (not the built-in terminal).

Thanks!

**Comment by DanTup** [comment]
@kenzieschmoll have you seen this issue since you posted [this comment](https://github.com/Dart-Code/Dart-Code/issues/4404#issuecomment-1456804499)?

**Comment by kenzieschmoll** [comment]
I don't think I have. I remember having a different CocoaPods issue a couple weeks ago but I don't think it was the same one as here.

**Comment by kenzieschmoll** [comment]
I am seeing this issue again. Re-opening.

**Comment by DanTup** [comment]
@kenzieschmoll was it a one-off, or can you still repro?

If you can repro, run the **Developer: Reload Window** command in VS Code to restart the extension and then run the **Dart: Open Extension Log** command. At the top you'll see something like:

```
[12:08:42 PM] [General] [Info] Searching for SDKs...
[12:08:42 PM] [General] [Info] Environment PATH:
```

Following those lines, it'll list everything on `PATH`. Check whether `/usr/local/bin` is listed (which is what you added to `.zprofile` further up). If it's not listed, then it seems like VS Code was launched in a way that didn't inherit this `PATH`. I don't think there's a lot we can do about that (besides implementing https://github.com/flutter/flutter/issues/122035 in Flutter so it can locate it based on previous runs or some default paths).

**Comment by kenzieschmoll** [comment]
```
[3:38:07 PM] [General] [Info] Environment PATH:
[3:38:07 PM] [General] [Info]     /usr/bin
[3:38:07 PM] [General] [Info]     /bin
[3:38:07 PM] [General] [Info]     /usr/sbin
[3:38:07 PM] [General] [Info]     /sbin
```

is what I see. Is there something I can do to at least make sure my local development environment is set up properly? even if we can't fix this at the extension level?

**Comment by kenzieschmoll** [comment]
Actually I figured out if I start VS code from my MacOs terminal, the proper paths are applied. That is a fine workaround for now. Closing.

**Comment by DanTup** [comment]
> Actually I figured out if I start VS code from my MacOs terminal, the proper paths are applied.

Yeah, this seems like what was noted a little further up (https://github.com/Dart-Code/Dart-Code/issues/4404#issuecomment-1454130438). Adding things to `PATH` in a terminal startup script that only applies to terminals (and not the whole logon session) will result in them not being visible if you launch VS Code outside of the terminal.

On my Mac, I always add paths via `/etc/paths.d/` and that seems to apply everywhere, but it also feels slightly weird because that's not user-specific (it doesn't matter because I'm the only user, but it doesn't feel like the right solution either).
