### ISSUE TITLE
Debugger: Step-Out action works just like Step-in action.

### ISSUE THREAD

**Issue by muddi900** [Dart-Code/Dart-Code#4405]
**Describe the bug**
The step-out action in the debugger is expected to step-out of the current execution scope and move on to the next. Instead here, the action acts exactly like the Step-in action.

This wouldn't be that big of an issue if not for #4348. Actually stepping through every step on the SDK causes takes a long time, making debugging impossible.

**To Reproduce**
1. Debug an app.
2. Set a breakpoint.
3. Click on the Step-out action when code execution pauses.

**Expected behavior**
Step out of the current execution.

**Screenshots**
This video demonstrates the issue quite clearly:
https://youtu.be/rURXG7TDWzI

**Please complete the following information:**

-  Operating System and version: Windows 11 Build 22621.1265
- VS Code version: 1.75.1
- Dart extension version: 3.58
- Dart/Flutter SDK version: 3.7.3
- Target device (if the issue relates to Flutter debugging): Android Emulator

**Comment by DanTup** [comment]
I don't seem to be able to reproduce this (I've tried with both the old and new debug adapters):

![Feb-27-2023 11-10-03](https://user-images.githubusercontent.com/1078012/221548658-2aa78ac2-8f85-4b7b-a851-fb3a80ab798f.gif)

Can you reproduce this in a sample project you can share?

**Comment by muddi900** [comment]
The issue only seems to occur when the debugger steps-in to Matrix4.

**Comment by DanTup** [comment]
@muddi900 I still don't seem to be able to repro this (on either new or old debug adapter):

![Feb-27-2023 11-55-48](https://user-images.githubusercontent.com/1078012/221557659-c11d57e2-2a99-4ad2-bc69-b5ff052fd45b.gif)

Is it possible you can share a complete code sample that definitely triggers this for you so I can test with exactly the same? If you can repro in a small sample app then capturing a log (see https://github.com/Dart-Code/Dart-Code/issues/4348#issuecomment-1446151089) may also be useful to understand what's happening.

Thanks!

**Comment by DanTup** [comment]
I also tried breaking inside `Matrix4.multiply()` which I see is where you were, but Step Out is still behaving as expected for me.

**Comment by DanTup** [comment]
Although, I'm curious how you ended up inside `Matrix4.multiply()` since your status bar says "Debug my Code". I had to enable debugging packages to be able to step in there.

**Comment by muddi900** [comment]
That is due to #4348

**Comment by DanTup** [comment]
Oops, I should've realised that 🤦‍♂️

I tried simulating this by setting "Debug my Code + SDK + packages" and stepping into `Matrix4.multiply`, then I changed do "Debug my Code" and performed a Step Out, but it also worked as expected.

Are you able to test this in a small sample project that you can share in its entirety, so I can be sure I'm using exactly the same code and SDK?

(Just noticed you're on Windows, so I'll give it a test there in case it's platform-specific and post back shortly).

**Comment by DanTup** [comment]
No joy on Windows either. IF you can repro this in a sample app you can share, and capture a debugging log, that would really help.

Thanks!
