### ISSUE TITLE
Inlay hints with inner generics

### ISSUE THREAD

**Issue by Zekfad** [Dart-Code/Dart-Code#4406]
**Is your feature request related to a problem? Please describe.**
Currently Inlay hints can show generics and their inferred types, but inner types are not clickable.

**Describe the solution you'd like**
 Make inner generics interactive.

**Describe alternatives you've considered**
\-

**Additional context**
<details>
<summary>Current behavior</summary>

![image](https://user-images.githubusercontent.com/8970959/221232148-3ec0750e-719e-4873-9c6c-67b627debc8b.png)

</details>

**Comment by DanTup** [comment]
I've got a change open at https://dart-review.googlesource.com/c/sdk/+/285625 for this.

![Feb-27-2023 13-10-56](https://user-images.githubusercontent.com/1078012/221572631-a6b245b4-f978-4a5c-9fa1-605195f40886.gif)

(note: there's some weirdness with navigation not always working in VS Code - I've filed https://github.com/microsoft/vscode/issues/174912 to try and get to the bottom of that).

**Comment by DanTup** [comment]
Also note: this change is in the SDK, so the fix will show up with a future Dart/Flutter SDK release rather than a VS Code extension update.

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/88d277a5341fa3e55ffd0c95cd60b945e8c2f6f2.
