### ISSUE TITLE
Show Flutter and Fuchsia SDK versions in status bar

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#442]

**Comment by DanTup** [comment]
@devoncarew Does Flutter actually have version numbers I could show? I had a quick look and it has an `engine.version` file but looks like it's a hash, which I guess makes sense since I'm running from a checked out version of the repo (I presume that gets updated when flutter runs and it rebuilds?).

Is this currently the only way to use Flutter (with a checked out copy of the repo)? Or is there a way to set up a Flutter project starting without it? (I presume not, since you can't run `flutter packages get` without having a `flutter` command).

If so, maybe this issue makes no sense (at least for now).

**Comment by devoncarew** [comment]
There is a `VERSION` file in the root of the repo, but we're not really at a point where it's meaningful to the user. When reporting issues, the doctor output is the best value, with the git hash and branch.

Depending on how much space you have, the revision and age (from flutter --version) might also work:

```
Flutter • channel master • https://github.com/flutter/flutter
Framework • revision 928d2cc764 (2 days ago) • 2017-11-17 15:45:27 -0800
Engine • revision 4733e33737
Tools • Dart 1.25.0-dev.11.0
```

But yeah, I wouldn't necessarily work to hard to show a flutter version to the user at this point -

**Comment by DanTup** [comment]
Thanks - I'll leave this for the future then!

**Comment by DanTup** [comment]
Considering this a dupe of #597
