### ISSUE TITLE
Dart 32bit

### ISSUE THREAD

**Issue by dasaintgray** [Dart-Code/Dart-Code#4426]
Even I change the Dartk SDK into 32bit but the flutter doesn't allow to change the SDK

**Comment by DanTup** [comment]
Can you clarify exactly what you're trying to do? It's not possible to change the Dart SDK used when working on a Flutter project, it will always use the one that is included with the Flutter SDK.

My understanding from https://github.com/flutter/flutter/issues/14925 is that Flutter doesn't support 32bit.

If you're working on a Dart project (without Flutter), then you can choose any Dart SDK.

**Comment by dasaintgray** [comment]
I'm working on a project that consumes the 32-bit DLL (3rd Party Windows Library). I downloaded the 32-bit Dart SDK, and from that I can consume the DLL, but when I'm trying to use it in a UI (Flutter) I got an error code 193.

**Comment by DanTup** [comment]
I don't believe it's possible to use Windows 32bit for Flutter development. There are some open issues about this here:

- https://github.com/flutter/flutter/issues/33862 (developing _on_ Windows 32bit)
- https://github.com/flutter/flutter/issues/37777 (targeting Windows 32bit)

I don't think there's anything the VS Code extension can do here, it would need to be supported by Flutter itself. If Flutter supported it, it should work here without any further changes.

**Comment by ashra951** [comment]
if i have hp tablet windows 10 32 bit and two giga rams and i want to install windows flutter app on it .i got that this app can't run on your pc to find a version for your pc check with the software publisher there is any solution ??

**Comment by DanTup** [comment]
@ashra951 Unfortunately Flutter does not appear to support 32bit Windows as a target - see https://github.com/flutter/flutter/issues/37777 noted above.
