### ISSUE TITLE
Set FLUTTER_TOOL automatically to simplify running flutter_tools tests

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#4427]
Currently you may have to set the `FLUTTER_TOOL` variable manually in `launch.config`/`dart.env` when running flutter_tools tests.

Since we know where the SDK is, perhaps we could just always set this when starting the Flutter debug adapters, as long as there isn't already one defined?

@christopherfujino can you see any cases where this wouldn't do the right thing?

**Comment by christopherfujino** [comment]
> @christopherfujino can you see any cases where this wouldn't do the right thing?

Can't think of anything wrong with this. To clarify, my understanding is that Dart-Code tracks an absolute path to the Flutter SDK checkout, and it invokes the `flutter` tool by absolute path? In this case, I think it would be safe (and ideal) to always provide `FLUTTER_ROOT=ABSOLUTE_FLUTTER_SDK_PATH` when invoking the tool.

**Comment by christopherfujino** [comment]
Cool, you merged it already :)

**Comment by DanTup** [comment]
> To clarify, my understanding is that Dart-Code tracks an absolute path to the Flutter SDK checkout

Not specifically to the checkout, but to the SDK it found (via PATH, settings, whatever).

I didn't want to set it too aggressively in case it might impact things (for example what if you have a Flutter SDK that isn't the one you're hacking on), so I decided to set it only in the case where you have an open folder that is also inside the SDK that we detected (so if you open the repo root, or flutter_tools, etc., and there is no other FLUTTER_ROOT set).

I've pushed a new pre-release build of the Dart extension so if you're using that, you can remove any dart.env or launch.json value you have for this and see if it's all good. If so, we could simplify https://github.com/flutter/flutter/wiki/The-flutter-tool#debugging-the-flutter-command-line-tool-in-vs-code.
