### ISSUE TITLE
pub get interaction with fvm

### ISSUE THREAD

**Issue by johanlantz** [Dart-Code/Dart-Code#4428]
**Describe the bug**
Not sure what to expect here but am using fvm to switch between flutter versions. So, when moving between Flutter 2 and Flutter 3, there appears to be some difference in what pub get does.

Running *fvm flutter pub get* from the terminal is fine and the fvm version of flutter is used. However, when saving the pubspec.yaml, it uses the default pub get, not respecting fvm.

I know this is the dart plugin but I did not find any pub settings for the flutter vscode plugin so I guess this is the one doing pub get when saving pubspec.yaml?

**To Reproduce**
- Enable fvm
- Save pubspec.yaml from vscode

**Expected behavior**
I think there should be some way to setup the plugin to work fvm. So instead of just running pub get when saving the file, it would do *fvm flutter pub get*. Unless this is already possible or I am missing something, I guess having a custom command line in the plugin settings for pub get could work. So it would default to just running pub get but I could change it to run fvm flutter pub get. Or even better, if a fvm_config is present, the default behavior would be to use the fvm shell?

**Please complete the following information:**
 - MacOS Ventura
 - VS Code version: 1.75.1
 - Dart extension version: 3.56.0
 - Dart/Flutter SDK version: 2.10.5 and 3.7.0

**Comment by DanTup** [comment]
> I know this is the dart plugin but I did not find any pub settings for the flutter vscode plugin so I guess this is the one doing pub get when saving pubspec.yaml?

Correct. This repo also covers both Dart + Flutter extensions.


> However, when saving the `pubspec.yaml`, it uses the default `pub get`, not respecting `fvm`.

You're right, these extensions know nothing about `fvm`. The version of `pub` that is run is the one from the SDK that is currently being used in the workspace.


If you're changing the path of the Flutter SDK you want to use during a workspace session, I think you'll run into more problems than just saving `pubspec.yaml` running the "wrong" version. There are long-lived processes running in the background (`dart language_server`, `flutter daemon`) that will also be from the workspaces SDK and not the one you've set `fvm` to. Starting a debug session will also use the one from that SDK (and when breaking/stepping into SDK sources, those will also be mapped to this SDK).

If you want to change the path to your SDK, you need to do it in a way that the extension understands - that is by setting the `dart.flutterSdkPath` setting or having the correct SDK in `PATH` (or in one of the well-known locations the extension looks for). This will then apply to everything (the language server, the device daemon, debugging sessions, automatic `pub` invocations).

If you have multiple SDKs and want a quick way to switch between them, you can use the `dart.flutterSdkPaths` (note the trailing `s`) setting (see https://dartcode.org/docs/quickly-switching-between-sdk-versions/). With the latest version, the SDK you select here can also be applied to the terminal by enabling the `dart.addSdkToTerminalPath` setting.


Let me know if you don't think these address all of the issues.
