### ISSUE TITLE
Quick Debug/Launch button missing when renaming lib folder

### ISSUE THREAD

**Issue by TheLordDrake** [Dart-Code/Dart-Code#4429]
**Describe the bug**

The quick debug/launch button in the upper right of VSCode window disappears when renaming the lib folder.

**To Reproduce**

1. Create a new Flutter Project
2. Rename `lib/` to something else, e.g. `src/`

**Expected behavior**

Quick debug/launch button should still be accessible.

**Screenshots**

Button visible with standard `lib/` name
![image](https://user-images.githubusercontent.com/24683014/223907127-3a8e394c-560d-4c63-9275-c73ff81f00b7.png)

Button missing after renaming directory to `src/`
![image](https://user-images.githubusercontent.com/24683014/223907272-be4655fd-364b-4502-8339-549e7685374b.png)

**Please complete the following information:**
 - Operating System and version: Windows 11 Home - 22621.1265
 - VS Code version: 1.76.0
 - Dart extension version: 3.60.1
 - Dart/Flutter SDK version: 3.7.6
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
@christopherfujino @jacob314 is there any requirement to have Flutter entry points inside `lib/`? I thought there was (maybe that something was using `package:` internally and that's where the package root is), but with a quick test, having the file in `src/` _seems_ to launch fine on Web and macOS and I can't find any docs backing up that `lib/` is a requirement.

**Comment by DanTup** [comment]
@christopherfujino @jacob314 friendly ping - do either of you know the answer to this, or where I might find it?

**Comment by christopherfujino** [comment]
> @christopherfujino @jacob314 is there any requirement to have Flutter entry points inside `lib/`? I thought there was (maybe that something was using `package:` internally and that's where the package root is), but with a quick test, having the file in `src/` _seems_ to launch fine on Web and macOS and I can't find any docs backing up that `lib/` is a requirement.

Sorry I missed this original ping. There is nothing that I know of that would require the entrypoint to be under `lib/`. AFAIK, as long as the Dart compiler can resolve package imports, everything should work.

**Comment by DanTup** [comment]
Got it, thanks!
