### ISSUE TITLE
Color picker can corrupt code when `const` auto-added on save

### ISSUE THREAD

**Issue by lukehutch** [Dart-Code/Dart-Code#4432]
**Describe the bug**

If you have VSCode set up to auto-add `const` where needed, on Save, then the following minor code corruption issue can happen:

**To Reproduce**

1. Use a non-`const` color like `Colors.blueGrey.shade100`:

![image](https://user-images.githubusercontent.com/811305/224444974-9727014a-e6d9-4ea8-a5d8-709d39c8c7d0.png)

2. Tap on the color, and change it by dragging inside the color picker.

![image](https://user-images.githubusercontent.com/811305/224445051-659f22bd-5059-4780-bc3f-007a29399548.png)

3. Hit Ctrl+S, and `const` will be auto-added, without the color picker closing.

![image](https://user-images.githubusercontent.com/811305/224445095-99751272-823c-4d97-ae14-8d8ed76138b0.png)

4. Drag within the color picker again, and the original text range will be edited, not the text range of the new color expression after `const` was added:

![image](https://user-images.githubusercontent.com/811305/224445169-b4b2ca3a-4621-46bb-abef-de0bef6ca9a7.png)

**Expected behavior**

After Save, the color picker should re-establish what the correct text range is for the color (or the color dialog could simply be closed on Save, that would "solve the problem" in the simplest way possible).

**Please complete the following information:**
 - Operating System and version: Fedora Linux 34
 - VS Code version: 1.76.0
 - Dart extension version:
 - Dart/Flutter SDK version: 2.19.2
 - Target device (if the issue relates to Flutter debugging):

**Comment by lukehutch** [comment]
PS ignore the unexpected changes in numbers (e.g. 230 -> 242 in between the 3rd and 4th screenshot), I had to re-open the color picker and choose again after each screenshot.

**Comment by DanTup** [comment]
There seems to be a VS Code bug here, I can repro the same with CSS. I've filed https://github.com/microsoft/vscode/issues/176959.

I'll keep this open until that's fixed to verify there's nothing else going on too.

**Comment by DanTup** [comment]
This was fixed in VS Code - the color picker now closes when the editor is modified.
