### ISSUE TITLE
"character must be non-negative" in inlay hints

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#4436]
Hit by @incendial at https://github.com/Dart-Code/Dart-Code/issues/4421#issuecomment-1464907624

```text
workbench.desktop.main.js:615   ERR Illegal argument: character must be non-negative: Error: Illegal argument: character must be non-negative
	at w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:7:1267)
	at new p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:13423)
	at new n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:14913)
	at asRange (/Users/dimannich/.vscode/extensions/dart-code.dart-code-3.61.20230307/out/dist/extension.js:39344:24)
	at asLocation (/Users/dimannich/.vscode/extensions/dart-code.dart-code-3.61.20230307/out/dist/extension.js:39675:66)
	at asInlayHintLabelPart (/Users/dimannich/.vscode/extensions/dart-code.dart-code-3.61.20230307/out/dist/extension.js:40113:31)
	at convertBatch (/Users/dimannich/.vscode/extensions/dart-code.dart-code-3.61.20230307/out/dist/extension.js:41685:25)
	at Object.map (/Users/dimannich/.vscode/extensions/dart-code.dart-code-3.61.20230307/out/dist/extension.js:41694:17)
	at asInlayHint (/Users/dimannich/.vscode/extensions/dart-code.dart-code-3.61.20230307/out/dist/extension.js:40088:27)
	at convertBatch (/Users/dimannich/.vscode/extensions/dart-code.dart-code-3.61.20230307/out/dist/extension.js:41717:31)
	at async Object.mapAsync (/Users/dimannich/.vscode/extensions/dart-code.dart-code-3.61.20230307/out/dist/extension.js:41725:17)
	at async ee.provideInlayHints (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:49977)
```

**Comment by DanTup** [comment]
@incendial how often do you see this? If you could run with the instrumentation log enabled for a while and trigger this, you could find the offending response by searching for `"character"::-1` in the log, and that line might help understand what's happening.

My feeling is that we're trying to get the location of a synthetic element, but I looking through the code I've not been able to come up with any scenarios that would cause this.

**Comment by incendial** [comment]
Only saw this one day, I'll get back when I see it again

**Comment by incendial** [comment]
I also sometimes see inlay hints blinking when I open source control changes comparison. So it might be connected, coz I don't have them enabled, actually.

**Comment by incendial** [comment]
> source control changes comparison
<img width="333" alt="Screenshot 2023-03-13 at 16 28 33" src="https://user-images.githubusercontent.com/21116742/224702013-41fb70b2-5bff-486c-b731-6252af8b2971.png">

**Comment by DanTup** [comment]
> I also sometimes see inlay hints blinking when I open source control changes comparison. So it might be connected, coz I don't have them enabled, actually.

Can you clarify what you mean by clicking, and that they're not enabled? They show up by default while you're holding Ctrl+Option (Ctrl+Alt?), so if you're pressing some keybinding that includes those keys, you'll see them show up.

You can completely disable them with:

```
"[dart]": {
	"editor.inlayHints.enabled": "off",
},
```

(we override the default for Dart to `offUnlessPressed` because the global VS Code default is `on`)

**Comment by incendial** [comment]
> Can you clarify what you mean by clicking,

You mean blinking?

**Comment by incendial** [comment]
> Are you able to capture a GIF/video of this? 

Will try, but there are no stable repro, although I see them quite a few times a day.

> I don't believe I've ever seen them, and it sounds like a VS Code bug if they're showing up without being triggered

Yeah, been thinking about that too

**Comment by DanTup** [comment]
Oh, I see. I can repro that in the Peek References window. I opened https://github.com/microsoft/vscode/issues/177059 with your video and some additional notes. Definitely feels like a VS Code bug to me (perhaps when the peek editor is created it's not set to Dart language, so inherits the default of always showing, and then quickly changes? Don't see why it should be that way though).

**Comment by incendial** [comment]
And I have the same behavior when opening a file in source changes comparison. It's harder to record, but looks the same

**Comment by incendial** [comment]
Another case, but also probably VS Code issue:

https://user-images.githubusercontent.com/21116742/225044681-6c191244-4fdb-477d-9ff1-ce23eb94045c.mov

**Comment by incendial** [comment]
<img width="517" alt="Screenshot 2023-03-20 at 00 21 17" src="https://user-images.githubusercontent.com/21116742/226206762-adf21a5c-037d-46d3-b7ea-c76d875fe7eb.png">

Got 29 of them in like 4 hours. Can you add any useful for you logs to the prerelease version or we'll wait for VS Code to fix the hints display (note: I also started to see them just when a file is being opened, but not often though)?

**Comment by DanTup** [comment]
> Another case, but also probably a VS Code issue:

Yeah, I think so - I would add these cases to https://github.com/microsoft/vscode/issues/177059.

> Can you add any useful for you logs to the prerelease version or we'll wait for VS Code to fix the hints display (note: I also started to see them just when a file is being opened, but not often though)?

I'll add some logging today. VS Code fixing the flicker won't really fix this issue, as there's still a bug that we're producing invalid Inlay Hints, even if in this case you didn't really want them.

**Comment by DanTup** [comment]
@incendial I've published a pre-release version (v3.61.20230320) that includes logs to the normal console when there are invalid InlayHints.

The log will look like:

```
Got invalid InlayHint from server: $documentUri, $viewport, $json
```

In the JSON, there will be two useful things - a _Position_, which is where the Inlay Hint is being rendered, and also a collection of _Labels_ which each include a _Range_. I believe you'll find a `-1` in the Range of one of the Positions.

Hopefully given the location of where the hint is appearing, and the element it's trying to link to, you should be able to see what kind of code is causing it (it's likely that something in the label references a synthetic element that's not actually in the source), which will hopefully help me fix. Thanks!

**Comment by incendial** [comment]
Great, thank you. Don't see the update though (currently have 3.61.20230307).

**Comment by DanTup** [comment]
It often takes 10-20 mins for the update to show up (sorry, should've mentioned that). Running the **Extensions: Check for Extension Updates** command might help, but it's never seemed to do anything for me :D

**Comment by incendial** [comment]
> Running the Extensions: Check for Extension Updates command might help, but it's never seemed to do anything for me :D

It worked 😅.

**Comment by incendial** [comment]
Guess who forgot to reload the IDE after the update 🤦‍♂️
But I might now have a clue how to repro

**Comment by incendial** [comment]
I don't see any additional logs, but here is the repro. I don't press any additional buttons, just type

https://user-images.githubusercontent.com/21116742/226353907-139e977f-33d5-43c6-8fa0-f0731cba8cc1.mov

**Comment by DanTup** [comment]
@incendial can you check in the developer console (Help -> Toggle Developer Tools) for the extra output?

I tried some similar code to yours, but I don't seem to be able to trigger it. It also seems odd that the editor is even requesting Inlay Hints when you're typing here, given you don't have them visible - I thought they'd be fetched on-demand 🤔

If nothing shows in the console, are you able to try and extract a repro that you can share that might help me trigger it here? Thanks!

**Comment by incendial** [comment]
Can you try it here? https://github.com/dart-code-checker/dart-code-metrics/blob/187b3cd05cc98b45b61483950774c1a4d8e0bbf6/lib/src/analyzers/lint_analyzer/rules/rules_factory.dart#L168

I just removed 3 last lines and started to type `Tag` and got the issue 3 times. And no console output...
![Uploading Screenshot 2023-03-21 at 21.51.25.png…]()

**Comment by incendial** [comment]
Well, nice screenshot, GitHub! 🤦‍♂️

**Comment by incendial** [comment]
<img width="633" alt="Screenshot 2023-03-21 at 21 52 42" src="https://user-images.githubusercontent.com/21116742/226698448-a4b4b0c0-0aa7-4b8f-8603-5d68bcca800a.png">

**Comment by DanTup** [comment]
Thanks! I don't know why the additional logging isn't working, but I can repro. Taking a look, thanks!

**Comment by DanTup** [comment]
Well that's very odd.. I reproduced it twice, but when I started logging the issue stopped occurring. Even after a reload...

Although I did spot another issue with weird ranges coming back (filed #4454) and I wonder if they're related (both are in some ways due to invalid locations).

**Comment by DanTup** [comment]
Ah, it seems to only happen right after typing. If I type some additional characters and then press Ctrl+Option, it triggers.

```
{
	"kind": 2,
	"label": [
		{
			"location": {
				"range": {
					"end": {
						"character": -1,
						"line": 0
					},
					"start": {
						"character": -1,
						"line": 0
					}
				},
				"uri": "file:///Users/danny/Dev/TestStuff/dart-code-metrics/lib/src/analyzers/lint_analyzer/rules/rules_factory.dart"
			},
			"value": ":"
		}
	],
	"paddingRight": true,
	"position": {
		"character": 50,
		"line": 180
	}
},
```

Not only is the location bad, but showing an inlay hint containing only a colon also doesn't seem right.

**Comment by DanTup** [comment]
Ok, I see what's happening. While typing here, the map contains invalid entries, and that means at the end of the file where this function invocation is, we fail to get a valid parameter (name or location):

![Screenshot 2023-03-23 at 10 18 15](https://user-images.githubusercontent.com/1078012/227173512-62292995-b7d2-4b5e-92f4-7c4a2a998db6.png)

I should be able to repro this in a test and get a fix now. Thanks for the repro steps!

**Comment by DanTup** [comment]
Two slightly related issues:

```dart
void f(void Function(int) a) => a(1);
```

In this code, we'd also insert an empty `:` label before the `1`, because there was no parameter name. The original case above is essentially the same (it would insert an invalid `:` hint), but we also didn't have a valid `Element` to find the location, and ended up trying to use the `-1` from it's `nameOffset`.

Opened a fix at https://dart-review.googlesource.com/c/sdk/+/290762

**Comment by incendial** [comment]
> Thanks for the repro steps!

No problem, happy to help and thank you for looking into it!

**Comment by DanTup** [comment]
Yeah 😄 Fortunately most of them are very fast (especially given the resolved result is cached for open files). I suspect there's some level of debouncing when you're typing too :-)

**Comment by DanTup** [comment]
Fix landed in the SDK in https://github.com/dart-lang/sdk/commit/443d6d32007400ae4bbd72ff25945db750df645f.
