### ISSUE TITLE
Dart test process leaked after being stopped

### ISSUE THREAD

**Issue by incendial** [Dart-Code/Dart-Code#4438]
**Describe the bug**
After stopping a test in VS Code noticed high CPU usage by dart process.

<img width="422" alt="Screenshot 2023-03-14 at 22 25 05" src="https://user-images.githubusercontent.com/21116742/225102019-e5ec4322-006f-4459-a3ab-826aa7d2f511.png">
<img width="350" alt="Screenshot 2023-03-14 at 22 25 12" src="https://user-images.githubusercontent.com/21116742/225102051-e601783b-d1ec-4bd6-ade5-048c7861aade.png">

Dart info output:
```text
dimannich@MacBook-Air-Dmitrij packages % dart info

If providing this information as part of reporting a bug, please review the information below to ensure it only contains things
you're comfortable posting publicly.

#### General info

- Dart 2.19.4 (stable) (Tue Mar 7 09:58:46 2023 +0000) on "macos_x64"
- on macos / Version 12.6 (Build 21G115)
- locale is en-GB

#### Process info

| Memory |   CPU | Elapsed time | Command line                                                                               |
| -----: | ----: | -----------: | ------------------------------------------------------------------------------------------ |
| 567 MB |  0.0% |     04:12:06 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.61.20230307     |
|   0 MB | 59.4% |        24:40 | dart run --no-serve-devtools test:test -r json -j1 --name ^UnnecessaryNullableAnalyzer run analysis should analyze nullable class parameters( \(variant: .*\))?$ --run-skipped test<path>/unnecessary_nullable_analyzer_test.dart |
```
**To Reproduce**
No steps yet.

**Expected behavior**
The process should be killed after the test is stopped.

**Comment by incendial** [comment]
After VS Code is reloaded the process is still alive:
```
#### Process info

| Memory |   CPU | Elapsed time | Command line                                                                               |
| -----: | ----: | -----------: | ------------------------------------------------------------------------------------------ |
| 312 MB | 43.2% |        00:29 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.61.20230307     |
|   0 MB | 19.0% |        26:50 | dart run --no-serve-devtools test:test -r json -j1 --name ^UnnecessaryNullableAnalyzer run analysis should analyze nullable class parameters( \(variant: .*\))?$ --run-skipped test<path>/unnecessary_nullable_analyzer_test.dart |
```

**Comment by incendial** [comment]
> how are you stopping the test? If you're clicking the "Stop" button twice, then this might be unavoidable.

Actually, yes 😅. I remember switching to the Dart 3.0.0 and this button stopped working for me if I press it only once (some error was thrown coz of timeout), so I started to double press it since then.

> A log captured with Dart: Capture Debugging Logs may help understand what's happening (and ofc if you can find steps to reproduce, that too).

I only experienced it once, will try to collect more info if it happens again.

> (btw, is the high CPU just because the test is still running, or is this CPU higher than you would have expected even if the test process had become orphaned?)

The test was probably not running at this point (I don't have any long tests). I'd not expect any process to take 60% (from dart info) / 90% (from the monitor) of CPU. My mac has fans / coolers (don't know what is the proper name) and it really easy to say when something goes wrong coz it starts to make the noise like it gonna fly away from me any moment 😁.

**Comment by DanTup** [comment]
> Actually, yes 😅. I remember switching to the Dart 3.0.0 and this button stopped working for me if I press it only once (some error was thrown coz of timeout), so I started to double press it since then.

There's an open issue about the timeout that's popping up at https://github.com/microsoft/vscode/issues/172284. It seems like a VS Code issue and the timeout will be removed, but there hasn't been much activity (although another extension author seems interested in fixing it now).

> The test was probably not running at this point (I don't have any long tests). I'd not expect any process to take 60% (from dart info) / 90% (from the monitor) of CPU. 

If you're able to reproduce this (even by hitting the stop button twice) I'd be interested in details. Even if we orphan processes, we shouldn't cause them to do anything other than just continue as they would have (eg. finish the test and exit).
