### ISSUE TITLE
I’d love to write Dart code on vscode.dev

### ISSUE THREAD

**Issue by csells** [Dart-Code/Dart-Code#4449]
**Is your feature request related to a problem? Please describe.**
When I go to install the Dart extension for VSCode on vscode.dev, I’m unable to do so.

**Describe the solution you'd like**
I’d love to be able to write and run Dart code on vscode.dev. Ideally this would include Flutter support but even if it doesn’t, I’d like to be able to build and run CLI and server-side Dart code online.

**Describe alternatives you've considered**
Unfortunately there’s no way to write Dart code on my iPad today. Ideally I’d be able to solve that problem with vscode.dev running in Safari on iPadOS.

**Additional context**
I’m curious what holds us back here, @DanTup. And hey! I hope you’re doing well. Long time!

**Comment by Salakar** [comment]
> * the Dart anlaysis server (for analysis / language support)
> * pub (to run "pub get" to fetch/resolve packages)
> * dart2js (or WASM) to be able to "compile" your project into something that can also run in the browser

zapp.run has all 3 of these running in browser, with analyzer in LSP mode too - perhaps we should chat sometime 😅
