### ISSUE TITLE
Issue with dart define

### ISSUE THREAD

**Issue by Mastersam07** [Dart-Code/Dart-Code#4453]
I am aware of passing environment variables via --dart-define and --dart-define-from-file. However, the former works in my lauch.json config but the later fails.

```
{
      "name": "app",
      "request": "launch",
      "type": "dart",
      "toolsArgs": ["--dart-define",
              "MAP_KEY=someKey",
              "--dart-define-from-file",
              "config.json",
},
```

From my flutter code, I am only able to access the variable **MAP_KEY** by doing `String.fromEnvironment()` however, it seems dart-define-from-file fails as i cant get any key from it.

**Comment by Mastersam07** [comment]
Thank you.

I am using `toolArgs` with flutter 3.7.3 via fvm. Passing `--dart-define-from-file=config.json` via the terminal works as expected. However, it fails when passed from the launch configuration. Here is what my config.json looks like:

```
{
    "MAP_KEY": "aVeryLongKey",
    "BASE_URL": "aBaseUrl"
}
```

**Comment by DanTup** [comment]
Are you able to share a small sample project that reproduces the issue? I tested this here but it seems to work as expected:

<img width="1716" alt="Screenshot 2023-03-23 at 10 56 02" src="https://user-images.githubusercontent.com/1078012/227182490-2c711bb7-3cd7-4ae5-8403-bfdcb76eb056.png">

My `config.json` looks like:

```js
{
    "danny": "this value is in config.json!"
}
```

My `.vscode/launch.json` looks like:

```js
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "flutter_dart_define_file",
			"request": "launch",
			"type": "dart",
			"toolArgs": [
				"--dart-define-from-file=config.json"
			]
		}
	]
}
```

And my counter app includes this extra widget:

```dart
const Text(
  'The value of String.fromEnvironment("danny") is ${const String.fromEnvironment('danny')}',
  ),
```

**Comment by Mastersam07** [comment]
Works now. Apparently, the issue was with the flutter SDK path referenced in my settings.json.

Thanks.

**Comment by DanTup** [comment]
> Apparently, the issue was with the flutter SDK path referenced in my settings.json.

Do you mean it was pointing to an older Flutter SDK? If so, that would explain it. If it's pointing to a 3.7 version then this should work fine (I have a path set in mine) so if that's the case let me know and we can do some more troubleshooting.

Thanks!

**Comment by Mastersam07** [comment]
> > Apparently, the issue was with the flutter SDK path referenced in my settings.json.
> 
> Do you mean it was pointing to an older Flutter SDK? If so, that would explain it. If it's pointing to a 3.7 version then this should work fine (I have a path set in mine) so if that's the case let me know and we can do some more troubleshooting.
> 
> Thanks!

Yes. It was pointing to an older Flutter SDK. I already updated it to point to the correct SDK.

Thanks for your help.

**Comment by camposFabio** [comment]
Hello. I having the same issue with dart-define-from-file and I have an question. Where should I put my config.json on the project tree?
I'm using arch linux.

**Comment by DanTup** [comment]
I would expect you can put it anywhere, as long as the argument that's passed is relative to the working directory. If this doesn't seem to be working, please open a new issue and include enough information to repro (for ex. including your `launch.json` and where the project lives relative to the folder opened in VS Code).
