### ISSUE TITLE
Unexpected suggestions for `.forEach`

### ISSUE THREAD

**Issue by incendial** [Dart-Code/Dart-Code#4459]
**Describe the bug**
When typing `forEach` suggestions significantly change after `for` part is entered. But this is the exact moment when a suggestion can be accepted via enter.
Video:

https://user-images.githubusercontent.com/21116742/227616363-879f3bd9-1ca3-4f97-9c9e-3e4104f9f309.mov

\
**To Reproduce**
1. create an iterable
2. start typing `forEach` and stop on `for`

**Expected behavior**
Suggestion would still show collection methods instead of suggesting a `for` statement and some classes.

**Comment by DanTup** [comment]
Thanks for the report - there's an existing issue covering this at https://github.com/dart-lang/sdk/issues/48883. Code completion doesn't properly handle when the typed prefix is a keyword.
