### ISSUE TITLE
Code actions menu is no available when the cursor is inside the highlighted zone 

### ISSUE THREAD

**Issue by incendial** [Dart-Code/Dart-Code#4462]
**Describe the bug**
Noticed that the code actions menu does not appear neither on the shortcut, nor via the button.
It can only be called via the diagnostic tooltip or if the cursor in on the first line (where the method signature is):

https://user-images.githubusercontent.com/21116742/227795251-781d58c1-4ca4-4a58-b8f9-5d48c2a74aa0.mov

**To Reproduce**
1. enable `prefer_expression_function_bodies`
2. create a method with a single return statement 
3. try to call the code actions menu

**Expected behavior**
Code actions menu appears.

**Comment by DanTup** [comment]
Good catch. We show quick-fixes for the whole line of a diagnostic (for convenience), but apparently only looked at the first line (which is the one with the `{`) and not the whole range.

Fix open at https://dart-review.googlesource.com/c/sdk/+/291281.

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/7ce6c20fb8803a6389d9509027cd08d467575b66, ships in the SDK :-)
