### ISSUE TITLE
Flutter theme inspector

### ISSUE THREAD

**Issue by leighajarett** [Dart-Code/Dart-Code#4465]
When using themes with Flutter, it's sometimes difficult to know where inherited properties are coming from. Additionally, changing the theme requires a hot restart which means that it can take a while for developers to troubleshoot on their own. 

It would be great to have some visual way to see property inheritance. We could do something similar to the chrome devtools approach, or we could explore a more graphical interface.

**Comment by jacob314** [comment]
This should probably be moved to the DevTools issue tracker. Even if the UI is surfaced in VSCode it should definitely be implemented in DevTools.

**Comment by DanTup** [comment]
Makes sense to me - I've moved this over to https://github.com/flutter/devtools/issues/5688.
