### ISSUE TITLE
vscode extension: intellisense window doesnt' filter correctly when typing based on available options

### ISSUE THREAD

**Issue by mhamri** [Dart-Code/Dart-Code#4471]
Type: <b>Bug</b>

Pressing ctrl+space shows the correct input, and when I'm typing, the autocomplete won't be narrowed down. correct behavior is to narrow down what the autocomplete is suggesting

But what is happening instead the autocomplete is destroyed, and wrong set of suggestions appears 

![Code_AFdI8RAFYH](https://user-images.githubusercontent.com/8991783/226996597-5db5c94d-bf7b-4783-8a2a-838d2acdcb68.gif)

you can replicate it with this repo 
https://github.com/mhamri/vscode-dart-bug/blob/main/lib/main.dart

I already reported this on vscode and they mention it's caused by extension so I move it here 
https://github.com/microsoft/vscode/issues/178049

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
flutter-snippets|ale|3.0.0
color-info|bie|0.7.2
dart-code|Dar|3.58.0
flutter|Dar|3.58.0
vscode-new-file|dku|4.0.2
copilot|Git|1.74.8955
json-to-dart|hir|3.5.8
pubspec-assist|jer|2.3.2
firebase-explorer|jsa|0.3.3
remote-containers|ms-|0.275.1
vscode-versionlens|pfl|1.5.0
material-icon-theme|PKi|4.24.0
remove-comments|pli|1.2.2
dart-data-class-tools|ric|0.5.7
flutter-riverpod-snippets|rob|1.2.1
code-spell-checker|str|2.17.1
code-spell-checker-persian|str|1.0.0
errorlens|use|3.7.0

(1 theme extensions excluded)

</details>

**Comment by DanTup** [comment]
This is unfortunately a VS Code ranking issue. When you start typing, VS Code re-ranks the items in the completion list and we have no influence over that.

There are some related issues in the VS Code repo here:

- https://github.com/microsoft/vscode/issues/79516
- https://github.com/microsoft/vscode/issues/127516

I don't believe this is something VS Code intends to change. I'll add a note on the VS Code issue.
