### ISSUE TITLE
Windows left open after runnning all tests

### ISSUE THREAD

**Issue by WorikQCI** [Dart-Code/Dart-Code#4478]
**Describe the bug**

When running tests in batches from inside VS Code, many windows are left open when tests finish.

The windows stay open when VS Code is exited.  ` ps x|grep flutter | wc -l` is seven.

(Interestingly, and probably unrelated, `killall flutter` has error `No matching processes belonging to you were found`.  They all belong to me)

This does not happen when tests are run one at a time from inside VS Code

It does not happen when tests are run using: `flutter test` from the command line

**To Reproduce**

Not easy.

I suspect that the fault is due to some interaction with `WidgetsFlutterBinding.ensureInitialized` and `TestWidgetsFlutterBinding.ensureInitialized`

There are seven files of test code in the set of tests I am running that include those calls.

There are four files, with six occurrences of `TestWidgetsFlutterBinding.ensureInitialized`, three files and occurrences of `WidgetsFlutterBinding.ensureInitialized` and one of `IntegrationTestWidgetsFlutterBinding.ensureInitialized`

(I am starting my journey into the deeply complex world of flutter, and dart, tests.  I will am unsure of the differences between those calls as I write, only I need them for several important aspects of testing.  Not relevant but the flutter test suite is a mess)

**Expected behavior**

I do not expect to have to manually close windows after running the testsuite.

**Please complete the following information:**
 - Operating System and version:
 ```
Apple M1 Max
13.1 (22C65)
```
 - VS Code version:
 ```
 Version: 1.73.0 (Universal)
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
```

- Dart extension version:
3.60.1

 - Dart/Flutter SDK version:

```
Flutter 3.7.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 90c64ed42b (12 days ago) • 2023-03-21 11:27:08 -0500
Engine • revision 9aa7816315
Tools • Dart 2.19.5 • DevTools 2.20.1
```
 - Target device (if the issue relates to Flutter debugging):
 
MacOS desktop

I have not tried this on windows.  I will follow up.

**Comment by DanTup** [comment]
@WorikQCI are you able to trim this down to a sample project you can share that triggers the issue?

**Comment by WorikQCI** [comment]
Not easily, or in an amount of time that I have available.

I was hoping that I was doing something obviously silly and well known....  

Next time I start a flutter app I will go straight to this stage.  For now it is not serious enough

**Comment by DanTup** [comment]
Nothing stands out, but it's hard to say without more info or a repro.

If you're able to construct a repro that triggers it, it'll be much easier for me to debug.

It might also be useful to try capturing a log (run the **Dart: Capture Debugging Logs** command from the command palette `F1`, then run the tests, then click **Cancel** on the logging notification to stop logging and open the log). Maybe there are errors or something in there around the end of the run that is leading to it not being cleaned up properly?

**Comment by WorikQCI** [comment]
> It might also be useful to try capturing a log (run the Dart: Capture Debugging Logs command from the command palette F1, then run the tests, 

That sounds useful.  I am looking at that.    I did not know that existed.

Thank you
