### ISSUE TITLE
pubspec.yaml not syntax higlighted

### ISSUE THREAD

**Issue by oliverjanik** [Dart-Code/Dart-Code#448]
![image](https://user-images.githubusercontent.com/2280140/33017511-ba2e75d0-ce46-11e7-96e8-56f6ea7e1002.png)

**Comment by DanTup** [comment]
Weird! I've just tested here with latest Code and Dart Code and they coloured ok.

Can you confirm that in the bottom-right corner of Code (in the status bar) the language shows YAML?
 Could you also try disabling Dart Code and re-launching to see if it goes away?

Dart Code doesn't actually provide any YAML stuff anymore, the syntax highlighting comes from the built-in data in Code. My guess is for some reason Code has decided this file is a different language (not YAML).

If it persists with Dart Code disabled and the language is showing as YAML, check whether any other extensions you have might be trying to provide YAML support.

**Comment by oliverjanik** [comment]
You are very correct, sir! It was API Elements extension.

**Comment by DanTup** [comment]
Cool; thanks for confirming! :)
