### ISSUE TITLE
Adding dependency through vscode is not providing the latest version.

### ISSUE THREAD

**Issue by Uvais-Mohammad** [Dart-Code/Dart-Code#4483]
**Describe the bug**
Adding dependencies in vs code through command palette is not putting latest version in pubspec.yaml file. 

**To Reproduce**
1. Open a flutter project in vscode
2. Press cmd+shift+p and select 'Dart:Add Dependency'
3. Type 'flutter_local_notifications' and then press enter
4. Open pubspec.yaml
5. There will be the dependency 'flutter_local_notificatons' with version ^8.2.0

**Expected behavior**

After adding the dependency, we expect the latest version. ie, 13.0.0

**Screenshots**
![ezgif-4-aa2c66e8eb](https://user-images.githubusercontent.com/63300484/230016394-4baab4a9-d03a-4894-b178-28ceb22322ef.gif)

![Screenshot 2023-04-05 at 1 21 58 PM](https://user-images.githubusercontent.com/63300484/230016853-84e11306-43e2-4474-a48e-620f4924f36f.png)
**Please complete the following information:**
 - Operating System and version: Mac OS
 - VS Code version: 1.77.0
 - Dart extension version: v3.62.0
 - Dart/Flutter SDK version: v3.62.0

**Comment by DanTup** [comment]
When I do this in a new project, I get `flutter_local_notifications: ^13.0.0`.

Can you share your `pubspec.yaml` file in the project where you're seeing this problem?

**Comment by DanTup** [comment]
Can you also provide your exact Flutter version (you can get this from the output of running the **Flutter: Run Flutter Doctor** command from the VS Code command palette (`F1`))?
