### ISSUE TITLE
"Organize imports" crashes VS Code

### ISSUE THREAD

**Issue by FairSuspect** [Dart-Code/Dart-Code#4486]
**Describe the bug**
When attempting to sort exports alphabetically, where two of them are written in the same line, VS Code freezes and crashes after 30 seconds with error 133 'crashed'.

If you remove some of the first exports from the example, the crash does not occur.

**To Reproduce**
1. Create a Dart project.
2. Create any dart file with following content:
```
export 'interior_material_selector.dart';
export 'mileage_selector.dart';
export 'owners_selector.dart';
export 'price_selector.dart';
export 'seat_count_selector.dart';
export 'year_selector.dart';
export 'winter_options_selector.dart';export 'camera_selector.dart';
```
Creating these files is not necessary.
3. Run 'Organize Imports' command (via command palette or Quick Fix with linter rule 'directives_ordering' enabled).
4. Wait for crush.

 

**Expected behavior**
Imports should be organized.

**Screenshots**
![photo_2023-04-05_14-17-48](https://user-images.githubusercontent.com/49846058/230069794-d01b5be8-7c15-4c90-8814-9c46888cef49.jpg)
**Please complete the following information:**
 - Operating System and version: Ubuntu 22.04.2 LTS
 - VS Code version: 1.77.0
 - Dart extension version: 3.62.0
 - Dart/Flutter SDK version: Dart 2.19.5, Flutter 3.7.8 stable
 - Target device (if the issue relates to Flutter debugging): dart issue

I've tried to capture [extension logs](https://github.com/Dart-Code/Dart-Code/files/11158113/Dart-Code-Log-2023-03-03.14-08-03.txt) but haven't capture any actions.
Fortunately, [exthost.log](https://github.com/Dart-Code/Dart-Code/files/11158092/exthost.log) did catch some exceptions with stack traces.

**Comment by DanTup** [comment]
Thanks, I can reproduce this. I suspect the crash is a VS Code bug (an extension shouldn't be able it crash it like this), but I'll try to narrow down what's triggering it and file an issue there.

**Comment by DanTup** [comment]
I've opened https://github.com/microsoft/vscode/issues/179268 with a crash dump from VS Code. I haven't managed to figure out what the trigger is yet, but disabling semantic tokens in the server seems to prevent it, so I wonder if it's something related to that.

**Comment by DanTup** [comment]
This has been fixed in VS Code (https://github.com/microsoft/vscode/issues/179268). I've tested it in Insiders and the crash no longer occurs. Thanks for reporting it!
