### ISSUE TITLE
Hot Restart and FlutterEngineGroup

### ISSUE THREAD

**Issue by dballance** [Dart-Code/Dart-Code#4489]
**Describe the bug**
When utilizing `FlutterEngineGroup` to start a secondary engine - both engines are started in a single `IsolateGroup` as verified by the observatory. However, upon restart, the Isolates are now in separate `IsolateGroup`s - and can no longer pass Dart objects via `Sendport` communication.

Also - hot reloads just hang.

**I really don't think this falls on the Dart-Code repo - but unsure where in `dart-sdk` or `flutter` is the appropriate place to file a directed issue aimed at resolving this restarts/reloads when running via a `FlutterEngineGroup`. Would appreciate any help here in aiming this the proper direction.** 

**To Reproduce**
1. Setup two flutter engines much like the `flutter/samples/multiple_flutters`. In my instance, I add a `FlutterEngineGroup` via `App.kt` and then provide two flutter engines. One in my `FlutterActivity` via `provideFlutterEngine` and another in a foreground service (effectively running the isolate "headless"
2. Run the app via vscode OR `flutter run`
3. Observe that there is a single `IsolateGroup` in the VM Observatory
3. Click "restart" in vscode or `ctrl-shift-r` if running via `flutter run`
4. Observe that there are now two `IsolateGroup`s in the VM Observatory (the once grouped Isolates are now running in separate groups)

**Expected behavior**
Using a `FlutterEngineGroup` shouldn't reduce DX by completely preventing hot-restarts and hot-reloads.

**Please complete the following information:**
 - Operating System and version: Linux Mint 20.3 
 - VS Code version: 1.77.1
 - Dart extension version: 3.62.0
 - Dart/Flutter SDK version: 
 ```
Flutter 3.9.0-22.0.pre.100 • channel master •
https://github.com/flutter/flutter.git
Framework • revision 9f98f63585 (29 hours ago) • 2023-04-08 01:02:14 +0200
Engine • revision 1f5433d4e4
Tools • Dart 3.0.0 (build 3.0.0-417.0.dev) • DevTools 2.23.1
```
 - Target device (if the issue relates to Flutter debugging): Android
 
 
 ### Basic Repro
 Adapted from the `flutter/samples/mutliple_flutters` sample. 
 
 main.dart
```dart
@pragma('vm:entry-point')
void main() {
   print('Main running');
   runApp(const MyApp(color: Colors.green));
}

@pragma('vm:entry-point')
void serviceMain() {
   print('Service running'); 
}
```

App.kt
```kotlin
class App : Application() {
    lateinit var engines: FlutterEngineGroup

    override fun onCreate() {
        super.onCreate()
        engines = FlutterEngineGroup(this)
    }
}
```
MainActivity.kt
```kotlin
class MainActivity: FlutterActivity() {

  override fun provideFlutterEngine(context: Context): FlutterEngine? {
    return (applicationContext as App).engines.createAndRunDefaultEngine(context);
  }


  override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
    GeneratedPluginRegister.registerGeneratedPlugins(flutterEngine)
    
    // Start foreground service and isolate
    ForegroundService.startService(this@MainActivity)

  }
}
```

ForegroundService.kt
```kotlin
/// Somewhere in the Foreground Service
val appBundlePath =
            FlutterInjector.instance().flutterLoader().findAppBundlePath()

val entryPoint = DartExecutor.DartEntrypoint(appBundlePath, "package:multiple_flutter_module/main.dart", "serviceMain")

flutterEngine = (applicationContext as App).engines.createAndRunEngine(this, entryPoint)
```

**Comment by DanTup** [comment]
> I really don't think this falls on the Dart-Code repo - but unsure where in `dart-sdk` or `flutter` is the appropriate place to file a directed issue aimed at resolving this restarts/reloads when running via a `FlutterEngineGroup`. Would appreciate any help here in aiming this the proper direction.

I'm also not sure which is correct because I don't know a huge amount about this area. Since the issue is showing up when using `FlutterEngineGroup` I would probably file this in `flutter/flutter`. Issues are often fixed across repos, so it's probably not a big deal if it's wrong.

Please post a link back here after filing it so anyone that discovers this issue having the same problem is able to follow.

Thanks!
