### ISSUE TITLE
Include device name in run process / default `launch.json`

### ISSUE THREAD

**Issue by guidezpl** [Dart-Code/Dart-Code#4491]
**Is your feature request related to a problem? Please describe.**

When running the same app on multiple devices (in this case, using the default generated `launch.json`), it's impossible to distinguish between the different instances
<img width="578" alt="image" src="https://user-images.githubusercontent.com/6655696/231721517-3cf7b144-e901-470e-a166-8aa478429930.png">
In addition, after selecting another device, and running, VS Code complains about an existing app with the same name
<img width="261" alt="image" src="https://user-images.githubusercontent.com/6655696/231722106-975510af-70d2-4a0e-8b01-0d385c7782e4.png">

**Describe the solution you'd like**
The name of the running app to reflect the device.

**Describe alternatives you've considered**
N/A

**Comment by DanTup** [comment]
> in this case, using the default generated `launch.json`

Can you confirm what you mean by "generated" here? There's no `launch.json` created by default (you can run apps without one), but there are a few ways you can trigger them to be created. Device names should be included automatically in at least some of those places (eg. #3937).

**Comment by DanTup** [comment]
Fixed by ae5b6ed9.

**Comment by guidezpl** [comment]
Sweet, thanks!
