### ISSUE TITLE
Flutter DAP not responding during initialization

### ISSUE THREAD

**Issue by K4ntemir** [Dart-Code/Dart-Code#4493]
**Describe the bug**
When starting debug with Neovim using [nvim-dap](https://github.com/mfussenegger/nvim-dap) following command window displayed and nothing happens after (application not starting).

![image](https://user-images.githubusercontent.com/103727953/232157568-4e50bf48-4d55-4e4a-90a4-7b7a0818bb0e.png)

Following message is displayed in Neovim:
``Debug adapter didn't respond. Either the adapter is slow (then wait and ignore this) or there is a problem with your adapter or `dart` configuration. Check the logs for errors (:help dap.set_log_level)``
Log output:
![image](https://user-images.githubusercontent.com/103727953/232159350-a9b12110-2c57-48ff-97a5-f18a9569e99a.png)

Session is not initialized:
`lua= require('dap').session().initialized` outputs `false`.

Here is configuration in `init.lua` :
```
dap = require('dap')
dap.set_log_level('TRACE')

local flutterBin = vim.fn.resolve(vim.fn.exepath('flutter.bat'))
local flutterSdk = vim.fn.fnamemodify(flutterBin, ":h:h")
local dartSdk = flutterSdk .. '\\bin\\cache\\dart-sdk'

dap.adapters.dart = {
  type = 'executable',
  command = flutterBin,
  args = { '-v', 'debug-adapter' },
}

dap.configurations.dart = {
  {
    type = 'dart',
    request = 'launch',
    name = "Launch Flutter",
    dartSdkPath = dartSdk,
    flutterSdkPath = flutterSdk,
    program = "${workspaceFolder}\\lib\\main.dart",
    cwd = '${workspaceFolder}',
    toolArgs = { '-d', 'windows' },
    sendLogsToClient = true,
  },
}
```

I also tried using [flutter-tools.nvim](https://github.com/akinsho/flutter-tools.nvim) (which also uses nvim-dap) to see if there was a problem with my configuration, and same window shows (but without logs, because no `-v` option was there).
Configuration in `init.lua` with flutter-tools.nvim:
```
require('dap').set_log_level('TRACE')
require("flutter-tools").setup {
debugger = { -- integrate with nvim dap + install dart code debugger
   enabled = true,
   run_via_dap = true, -- use dap instead of a plenary job to run flutter apps
 },
}
```

**Please complete the following information:**
 - Operating System and version: Windows 10 Pro 22H2 (OS Build 19045.2846)
 - VS Code version: 1.77.3
 - Dart extension version: 3.62.0
 - Dart/Flutter SDK version: Flutter (Channel stable, 3.7.11) / Dart  2.19.6 (stable)
 - Target device (if the issue relates to Flutter debugging): Tried on Windows and Android device
 - NVIM v0.8.3

CC @DanTup

**Comment by K4ntemir** [comment]
#4164

**Comment by DanTup** [comment]
@K4ntemir I think the issue could be the `-v` flag:

```
args = { '-v', 'debug-adapter' },
```

This may be causing `flutter` to output content to `stdout` that is not part of the DAP spec. Does the same happen if you remove it?

**Comment by K4ntemir** [comment]
Same happens without `-v` flag. I just added it after to see logs in command window shown in first screenshot.
Before that was same window but empty, without any logs.

**Comment by DanTup** [comment]
@K4ntemir are you able to capture the `stdout` and `stderr` streams of the debug adapter process? If you manually run `flutter.bat debug-adapter` in a terminal, is there any output printed? (the expectation is that there is not)

**Comment by K4ntemir** [comment]
When I run `flutter.bat debug-adapter` there is no output.

I've been testing with dart console application as well and noticed that when `dart.bat` is used from flutter sdk folder I get the same window and debug not starting and I get the same hanging window.
`command = 'C:\\src\\flutter\\bin\\dart.bat'`
But when path to `dart.exe` is used debug is starting and breakpoint works:
`command = 'C:\\src\\flutter\\bin\\cache\\dart-sdk\\bin\\dart.exe'`

I've been trying to change [dart.bat](https://github.com/flutter/flutter/blob/53f31c7c06f8dcd6aefd2708479416fadf8fda5a/bin/dart.bat#L36) file so it would start `dart.exe`, event commented everything out except `dart.exe` reference on last line, but couldn't start debug using .bat file.

**Comment by DanTup** [comment]
Do you know how the process is being spawned? `.bat` files can only run in a shell on Windows. When executing them from Node, we have to set the `shell` flag to run them:

https://nodejs.org/api/child_process.html#spawning-bat-and-cmd-files-on-windows

I wonder if your clients are trying to spawn them without a shell, which is causing Windows to open them as _seperate processes_, which is why you're seeing this window, and the DAP client is unable to communicate with them.

I had a look around the nvim-dap code and think it's being spawned here:

https://github.com/mfussenegger/nvim-dap/blob/debd7c2f80eaf20c5f5df25db8d8c1b9b18f4421/lua/dap/session.lua#L1147

But I wasn't able to find the docs for this `spawn` function.. I ended up at http://docs.libuv.org/en/v1.x/process.html?highlight=spawn#c.uv_process_options_t but I'm not sure if that's the right place, and I couldn't find any mention of using shells. Perhap it's worth opening an issue with nvim-dap - maybe they'd understand this better (you can CC me in case I can be of any help).

**Comment by K4ntemir** [comment]
I didn't find libuv documentation but there is [nvim documentation](https://neovim.io/doc/user/luvref.html#luv-process-handle).
I did try calling cmd.exe and passing .bat file as argument which `shell` flag seems to be doing, but with same result.

May be I can try to use `dart.exe` with same arguments from `flutter.bat` file, and open issue there if this doesn't work.
Thank you.

**Comment by K4ntemir** [comment]
> I wonder if your clients are trying to spawn them without a shell, which is causing Windows to open them as _seperate processes_, which is why you're seeing this window, and the DAP client is unable to communicate with them.

Thank you! This helped, nvim-dap detached option is on by default, and it seems to run as separate process, so after
launching with `cmd.exe` and setting `detached` to `false` it worked.
```
dap.adapters.dart = {
  type = 'executable',
  command = vim.fn.exepath('cmd.exe'),
  args = { '/c', flutterBin, 'debug_adapter' },
  options = {
      detached = false,
  }
}
```

**Comment by DanTup** [comment]
Ah, glad you sorted it. I did see `detached` and wonder if it was related, but it seemed like the opposite of what you wanted. I didn't consider it might have been the default :-)
