### ISSUE TITLE
Add `getter` modifier to getter `declaration` and it's `call`.

### ISSUE THREAD

**Issue by shujaatak** [Dart-Code/Dart-Code#4496]
**[Screenshots attached below]**
Getters usually are used to do a lot in the background but from the getter's call it looks like they are just properties, so to differentiate property from getter, it would be so awesome if you please add getter modifier so that I can set different color to it.

Getter Declaration:

![image](https://user-images.githubusercontent.com/14161646/232339897-7b5a6b73-ed15-44d9-bcb3-6b2b7706a31d.png)

Getter Call:

![image](https://user-images.githubusercontent.com/14161646/232339989-7b6633ee-dc83-491d-b688-abc6184fd480.png)

**Comment by DanTup** [comment]
We could add this, but I'm not sure it will work the way you're expecting based on the current semantics. Dart creates implicit getters/setters around instance variables:

https://dart.dev/language/classes#instance-variables:~:text=All%20instance%20variables%20generate%20an%20implicit%20getter%20method

So in this code:

```dart
class MyClass {
  String myField = 'FieldVal';
}

void f() {
  final a = MyClass();
  print(a.myField); // <--
}
```

The code `a.myField` is a getter.

It's also possible that something declared as an instance variable is overridden by a getter in a subclass, so something that appears to be an instance variable based on the static type is not necessarily that way in the types that will be used at runtime:

```dart
class A {
  String a = '';
}

class B extends A {
  @override
  String get a => 'AAA' * 1000;
}

void f() {
  A b = B();
  b.a; // static type suggests this is an instance variable (`A.a`), but at runtime it's the getter in `B.a`
}
```

@bwilkerson I thought this had come up before and there might have been a prior discussion I could link to, but I can't find one. I can see the appeal of having this information (using the static type and pretending the implied getters/setters don't exist). Do you have any thoughts/opinion?

**Comment by shujaatak** [comment]
> void f() {
>   A **b** = B();
>   b.**a**; // static type suggests this is an instance variable (`A.a`), but at runtime it's the getter in `B.a`
> }

In this case, I think the parser should be able see that **b** is actually instance of **B** so it somehow should be able to figure out that **a** is the **getter** rather than the **instance variable**. 

If somehow this distinction feature between **instance variable** and **getter** is added, it will greatly increase the readability of the code.

**Comment by bwilkerson** [comment]
I don't remember whether there has been a discussion in an issue, but I can give you my opinion.

In Dart, no code ever references a field directly. A field declaration of the form
```
class A {
  String a = '';
}
```
is equivalent to
```
class A {
  String $a = '';
  String get a => $a;
  set a(_a) {$a = _a;}
}
```
for some unique and unwritable identifier `$a`. (I couldn't find a decent looking character to stick in the identifier that was illegal but not confusing.)

When you write `b.a`, you are invoking the getter `a`. Period. You're never referencing (directly accessing) the unwritable field `$a`. Similarly, when you write `b.a = '';`, you're invoking the setter `a=`.

I think that users are better served by representing any invocation of a getter (setter) as an invocation of a getter (setter), not by sometimes coloring it as if it were a direct access of a field. I think it's important for users to remember that fields can't be directly accessed and that any getter (setter) can be overridden in a subclass, and that they can't count on the value of the field being returned by the getter invocation.

To give a concrete example, I think that not remembering this is one of the reasons that users are confused when type promotion doesn't work on (what they think of as) fields. It's reasonable to assume that type promotion would work on fields, but it's fairly clear to most users that type promotion won't work on a method invocation. If you remember that getters are (semantically) methods, then it becomes clear why promotion doesn't work for a getter invocation.

**Comment by DanTup** [comment]
Thanks for the extra info! On this basis, I feel like we shouldn't try to do this - if anything it will just add to the confusion around implicit getters/setters.

We could ofc still add getter/setter modifiers to things that _are_ getters/setters, but I'm not sure if that adds any value over the existing `property` type since it would end up on all of them. If there's value in colouring getters and setters differently from each other, that could be an argument to do that though.

@shujaatak hope this makes sense - let me know if anything is unclear.
