### ISSUE TITLE
Sidebar from "Find all implementations" and "go to implementations" doesn't show class names

### ISSUE THREAD

**Issue by stereotype441** [Dart-Code/Dart-Code#4500]
**Describe the bug**
The sidebar produced by "Find all implementations" shows filenames and the first line of each override, but it doesn't show the name of the overriding class.  Since the first line of an override is almost always just the signature of the override, that's not actually useful information.  It would be much more useful to show the name of the overriding class.

**To Reproduce**
Start with this file:
```dart
abstract class A {
  void foo();
}

class B extends A {
  @override
  void foo() {
    print('In B.foo()');
  }
}

class C extends A {
  @override
  void foo() {
    print('In C.foo()');
  }
}
```
Right click on the token `foo` inside class `A` and select "Find all implementations".  Look at the resulting navigation sidebar.

**Expected behavior**
It should be easy to see from the sidebar which implementation is from class `B` and which is from class `C`.

**Screenshots**
This is what I see instead:
![Screenshot from 2023-04-20 08-49-04](https://user-images.githubusercontent.com/306375/233420148-db6db972-d98f-410d-81b1-61ad0ea38e27.png)

**Please complete the following information:**
 - Operating System and version: Debian GNU/Linux rodete, version 12
 - VS Code version: 1.76.2
 - Dart extension version: v3.62.0
 - Dart/Flutter SDK version: Dart bleeding edge as of fa3a72fa7e5818e15118044ddd68a2c2ad2dfcd0

**Comment by DanTup** [comment]
This seems to be a VS Code limitation. The only information we can provide it when it asks for implementations is a range, which it uses to chose a snippet of source code.

I've opened https://github.com/microsoft/vscode/issues/180806 to see if they could extend this to allow more information.

**Comment by DanTup** [comment]
Unfortunately the VS Code issue has been closed because it didn't get 20 👍 's in 60 days.

There's unfortunately no way to work around this in the Dart extension/LSP because we can't provide the text that's shown, only a range in the document.
