### ISSUE TITLE
Code folding for `switch` statements

### ISSUE THREAD

**Issue by stereotype441** [Dart-Code/Dart-Code#4506]
With the addition of patterns to the Dart language, it would be nice if code folding could be used on `switch` statements, much as it can be used for other control flow such as `if` statements.

For example, given the code:
```dart
switch (expr) {
  case 0:
    statement;
    statement;
    statement;
  case 1:
    statement;
    statement;
    statement;
}
```
It would be nice to be able to collapse individual cases, e.g.
```dart
switch (expr) {
  case 0: …
  case 1:
    statement;
    statement;
    statement;
}
```
Or to collapse the entire switch statement:
```dart
switch (expr) {…
}
```

**Comment by DanTup** [comment]
This landed in https://github.com/dart-lang/sdk/commit/528c75acd2741229ef8b649571e4b12fc15a11f1. It's entirely a language server change so will show up with a new SDK release and doesn't require an extension update.

**Comment by DanTup** [comment]
@Fernandomr88 the change was made after the branch for the last SDK (Dart 3.0), so it will show up in a future SDK release (3.1, etc.). It should be available on beta/dev/master channels already.

**Comment by Fernandomr88** [comment]
> @Fernandomr88 the change was made after the branch for the last SDK (Dart 3.0), so it will show up in a future SDK release (3.1, etc.). It should be available on beta/dev/master channels already.

sorry for my mistake @DanTup, hadn't noticed that "tiny" detail lol, looking forward for that release

**Comment by DanTup** [comment]
np! FWIW I did just test it in latest code to verify, and it does seem to work as you'd expect :)

<img width="440" alt="Screenshot 2023-06-02 at 15 10 20" src="https://github.com/Dart-Code/Dart-Code/assets/1078012/fc45ad87-e3bc-4a0d-9aee-437b9f03a0d6">

**Comment by DanTup** [comment]
@Fernandomr88 this change shipped in Dart 3.1 / Flutter 3.13. It seems to work in my testing:

https://github.com/Dart-Code/Dart-Code/assets/1078012/86beb01a-fe10-40b2-944c-740682e14223

If you have code where it doesn't work, could you file a new issue with an explicit (complete) code sample so I can test with it? Please also include your exact SDK version.

Thanks!

**Comment by Fernandomr88** [comment]
> @Fernandomr88 this change shipped in Dart 3.1 / Flutter 3.13. It seems to work in my testing:
> 
>  folding.mp4 
> If you have code where it doesn't work, could you file a new issue with an explicit (complete) code sample so I can test with it? Please also include your exact SDK version.
> 
> Thanks!

Hey @DanTup , it worked indeed. Sorry for the mess, I was commuting and remembered this and asked 🫠

**Comment by DanTup** [comment]
Great, thanks for confirming :-)

**Comment by Fernandomr88** [comment]
@DanTup should I open an issue for this case too? or is it meant to be like this?
There's no folding on these cases:

![image](https://github.com/Dart-Code/Dart-Code/assets/14304128/f1ede756-03b9-4d8f-8ff8-a404a157e50b)
