### ISSUE TITLE
Is the Anaylzer supposed to cache the result for next time a project is opened?

### ISSUE THREAD

**Issue by roblframpton** [Dart-Code/Dart-Code#4507]
This is either a question or a feature request, depending on whether the behavior on my machine is the expected behavior or not.

Every time I open my Flutter project in VS Code, the analyzer runs for about 5 - 10 minutes before I am able to get code completions or formatting.  After that the performance is pretty good, but when I close VS Code and reopen, the analyzer runs again.  This surprises me, as I thought it would cache the analysis results on disk so I can start working immediately.

Is this the expected behavior?  If not, then why might this be hapenning for me?  Or, if it is the expected behaviour, would it be a possible future feature to cache the analysis and avoid such a slow process before I can start work?

**Comment by DanTup** [comment]
I do believe there is caching (into the `~/.dartServer` folder), though there is some work to validate the files on disk still match what the results were cached for.

Can you confirm a few things?

- Rough specs of the machine you're using (OS, RAM, CPU, is it an SSD or a mechanical drive)
- How big is the folder(s) you're opening in VS Code (is it a single project? multiple projects?)
- Post the full output of running `code --status` at a terminal during this slow initial analysis
- Post a copy of your `pubspec.yaml` and `analysis_options.yaml`

Of course, remove anything sensitive before sharing here.

Thanks!
