### ISSUE TITLE
Is it possible to turn off the appended trailing commas (and colons) when completing a prop name?

### ISSUE THREAD

**Issue by textzenith** [Dart-Code/Dart-Code#4512]
If I create a Container object and type `co`, the server completes that to `color: |,` (| indicates position of cursor)

I'd just like to complete the word, and enter punctuation by myself.

Rationale:

I have a somewhat barebones Vim setup where I use the Ctrl-X, Ctrl-O shortcut to enter LSP completion — very little is automatic. I don't use snippets and just complete the odd word here and there. The added syntactic shrapnel throws me every time, and inevitably I have to spend a few seconds figuring out what I am doing.

Additionally: 1) The completion function is basic and doesn't actually reposition the cursor — I have to either delete the comma or go out of insert mode and backtrack, and 2) The completion pop-up doesn't actually display the colon and comma ahead of time, which is the reason it keeps jolting me out of my flow!

Causes:

I think the comma is added by this part of the analysis server. I might just not be used to looking at TypeScript, but I don't see a way I can actually get inside the private functions here and turn it off.

https://dart.googlesource.com/sdk/+/refs/tags/3.1.0-48.0.dev/pkg/analysis_server/lib/src/services/completion/dart/arglist_contributor.dart

Acknowledgements:

Thanks for the hard work — half the success of Flutter, in my opinion, is down to the utility of the Dart language server.

Hopefully it won't take too long for someone to look at my issue here and offer a simple yes / no answer. Failing this, perhaps there's a much quicker way to clear out any unwanted punctuation in my Vim completion function.

**Comment by DanTup** [comment]
Thanks for the report. I think this is covered by #4111. Right now there's not a good way for users to express opinions about code formatting to control this (see https://github.com/Dart-Code/Dart-Code/issues/4111#issuecomment-1224170606). Ideally that should be something that's not VS Code specific, since VS Code is not the only user of the Dart analysis server.

**Comment by DanTup** [comment]
> Additionally: 1) The completion function is basic and doesn't actually reposition the cursor 

Could you clarify exactly what you mean here? Where are you seeing the cursor being left?
