### ISSUE TITLE
Import suggestions include non-Dart files

### ISSUE THREAD

**Issue by matanlurey** [Dart-Code/Dart-Code#452]
Simple reproduction is type `import 'package:flutter/`, and wait for auto-complete.

<img width="596" alt="screen shot 2017-11-23 at 2 10 26 pm" src="https://user-images.githubusercontent.com/168174/33189520-49cf06ec-d058-11e7-99cd-675fd9d96845.png">

... I imagine anything but a `.dart` file will never succeed, so why suggest it?

(Let me know if I should push this to analysis server instead)

**Comment by DanTup** [comment]
Weird, I've not seen this before.. as you guessed though, it's direct from the analysis server so should be raised against the SDK repo.

**Comment by matanlurey** [comment]
Moved to https://github.com/dart-lang/sdk/issues/31448.
