### ISSUE TITLE
iterated variable in for..in loops no longer highlighted

### ISSUE THREAD

**Issue by jason-downs** [Dart-Code/Dart-Code#4521]
Until a couple months or so ago, if you had something like:

`for (final element in listOfStuff) {....}`

when the cursor is on `element`, all instances of that in the loop are highlighted, as vscode normally highlights variables. But recently it has stopped. If the cursor is on `listOfStuff`, the highlighting still works as expected, but nothing is highlighted when it's on `element`. See screenshot:

<img width="396" alt="Screenshot 2023-05-04 at 11 38 35 AM" src="https://user-images.githubusercontent.com/31083702/236269444-7a0389a4-bbfc-43c1-81d0-41a8451aae6d.png">

What used to happen (and I think what is supposed to still happen?) is that `element` should be highlighted, including where the cursor currently is, along with the two places it's used inside the loop. But you can see that's not happening.

Additionally, if you do put the cursor on one of them inside the loop, both instances inside the loop are highlighted (as expected) but the one in the 'for-in' line still is not highlighted.

<img width="367" alt="Screenshot 2023-05-04 at 11 38 54 AM" src="https://user-images.githubusercontent.com/31083702/236269929-23403aca-149a-46c0-8eb3-d02ad0ef4c0b.png">

I don't know if this is even a dart code extensions problem, or something with vscode itself, or something where a default setting was changed that I need to change in settings json, but no amount of googling has helped. I have depended on this code highlighting a ton previously so this change is really throwing me off.

 - Operating System and version: macOS Ventura 13.3.1
 - VS Code version: 1.78.0
 - Dart extension version: 3.62.0
 - Dart/Flutter SDK version: Dart v.2.19.6, Flutter v.3.7.12
 - Target device (if the issue relates to Flutter debugging): n/a

**Comment by DanTup** [comment]
I can reproduce this. Works in Dart 2.18 but does not in Dart 2.19.

The issue is likely in the analysis server, but I can take a look to save moving the issue. Thanks!
