### ISSUE TITLE
Auto Complete not working on extension methods

### ISSUE THREAD

**Issue by bsutton** [Dart-Code/Dart-Code#4524]
**Describe the bug**
When extending a class such as Platform, I'm expecting auto-complete to show the extension methods as well as the core methods.

```dart

extension MorePlatform on Platform {
    void foo() {}
}


int doIt() {
   /// typing <tab> after the below dot shows a list of the Platform methods. 
  /// However if fails to show the extension method 'foo'.
  print(Platform.)
}
````

Platform
Dart version:   2.19.6                             

OS:             linux                              
OS version:     Linux 5.19.0-41-generic #42~22.04.1

Vs-code: v3.62.0

**Comment by vsmenon** [comment]
This is working as intended.  `Platform.foo` isn't a validate symbol in the example above.  `Platform.executable` is.

**Comment by bsutton** [comment]
apologies, my mistake.

The code should have been :

```
print(Platform().eol();
```

This however works.
