### ISSUE TITLE
The default project name for a Dart package should be `dart_package_x`

### ISSUE THREAD

**Issue by csells** [Dart-Code/Dart-Code#4527]
If I create a new Dart package project, the default project name is `dart_application_x` instead of `dart_package_x`. It should really be the latter.

**Comment by csells** [comment]
Great. Thanks, @DanTup!

**Comment by DanTup** [comment]
np!

If you're not already on the pre-release channel, I'd recommend it. I haven't pushed this yet, but I tend to push a few pre-releases each month so you'll get it sooner (and pre-releases should be pretty stable, but having some additional people using it is always good to help me find issues 😄)

<img width="703" alt="Dart pre-release versions" src="https://user-images.githubusercontent.com/1078012/218796750-90a70b0b-4957-468c-8eb4-688095cde112.png">
