### ISSUE TITLE
Run build_runner for specific module Flutter

### ISSUE THREAD

**Issue by pdax-shan** [Dart-Code/Dart-Code#4528]
hi i just wonder if there is any chance to create script to `build_runner` for the specific module
currently i got this script in my project :
`flutter clean flutter`
`flutter clean`
`flutter run build runner build --delete-conflicting-outputs`

ex: in my project i got apple , banana, mango and i add another module which is `dragon_fruit` and i just want to run `build_runner` only for `dragon_fruit` module and not to rebuild the whole project, rebuilding the whole project is really time consuming especially if you got plenty of modules already in your project, i hope you get my idea any response will be appreciated.

**Comment by DanTup** [comment]
I'm not sure I understand the request here. What do you mean by `module`s here - are they separate Flutter projects (with their own `pubspec.yaml`s) or something else?

Are you asking for some integration with VS Code, or just how to use `build_runner` from a terminal/terminal script?

**Comment by pdax-shan** [comment]
thanks for response @DanTup , `modules` means `Features` sorry for the terms ,  just asking if there is a way to use `build_runner` in terminal using script that can specify which feature of the project that the dev wants to rebuild 

ex: i got multiple features in project and you add another 1 feature and you just want to rebuild the newly created feature and not the whole features in the project.

**Comment by jakemac53** [comment]
https://github.com/dart-lang/build/blob/master/docs/partial_builds.md This is the doc for the `--build-filter` feature which is how you can build specific outputs (note you need to list the outputs you want to build and not the inputs).

But yes, it already does incremental builds. In practice though it is easy to create a pattern which causes any change to have to re-run most builders, since we have to consider all transitive imports as inputs for a given Dart file.

**Comment by DanTup** [comment]
@jakemac53 thanks!

@pdax-shan does this address your need?

**Comment by pdax-shan** [comment]
hi @DanTup , @jakemac53 , sorry for late response, thank you guys this is info or documents that i really need thanks for the help really appreciated guys

**Comment by pdax-shan** [comment]
@DanTup , yes correct what my script do is every changes for the specific `feature` example api related i need to add another endpoint  then i will run `build_runner` it will rebuild the whole project and it's really time consuming in my end i just want to speed up my development and i got curious if there is another way to specify which `feature` or specific part of the project to point the rebuild and not the whole features in the project

**Comment by DanTup** [comment]
np, happy to help! :-)
