### ISSUE TITLE
Filename completion doesn't work for conditional imports

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#4530]
Filed by @mosuem at #4529. Splitting it up because the issues may be fixed separately.

> 2. There is no code completion for source file paths in conditional imports.

**Comment by bwilkerson** [comment]
It will probably be easier to fix in the design I've proposed, but they key here is to notice when we're completing in an `ImportDirective`, the offset is inside a configuration, and the offset is after a synthetic string and before a synthetic semicolon (or something like that, there's probably other structures produced if it's followed by another configuration).

Unfortunately, with code completion, there's generally nothing easier than trying all of the possible inputs you can think of and figuring out what structure you're looking at, and it's sometimes the case that the structure doesn't match what the user has in mind at all.

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/dd726828156c3ecf2c6bcae9bc96e6e362826fec (an SDK change, so it'll show up in an SDK release rather than a Dart-Code release).
