### ISSUE TITLE
Dragging multiple files/folders are once does not update import statements

### ISSUE THREAD

**Issue by lukehutch** [Dart-Code/Dart-Code#4533]
**Describe the bug**

If I drag a dart file from one folder to another in VSCode with Dart-Code, the imports of other dart files that depend upon that file are not updated (i.e. the imports end up broken).

**Expected behavior**

Import paths should be updated when files are moved.

**Please complete the following information:**
 - Operating System and version: Linux
 - VS Code version: code-1.78.0-1683145689.el7.x86_64
 - Dart extension version: Latest
 - Dart/Flutter SDK version: Dart SDK version: 2.19.4 (stable) (Tue Mar 7 09:58:46 2023 +0000) on "linux_x64"
 - Target device (if the issue relates to Flutter debugging):

**Comment by lukehutch** [comment]
Correction: sometimes imports are updated, sometimes they are not. I haven't figured out under what circumstances the imports are not updated.

**Comment by DanTup** [comment]
@lukehutch is it when you're dragging multiple items at once? Currently we only support moving a single "item" at a time.

**Comment by lukehutch** [comment]
Yes, it was while moving multiple items. I couldn't reproduce it later because I was moving a single item at a time.

**Comment by DanTup** [comment]
Thanks for confirming. This is a known limitation of the rename. I thought there was an issue already open tracking this but I can't find one (here or in the SDK) so I'll keep this open for that. Unfortunately it's not a trivial fix.

**Comment by DanTup** [comment]
This is fixed by https://github.com/dart-lang/sdk/commit/09f3eb0c8b811a6753e01c3f8fff06caab7e1ae8 and will ship in a future SDK release.
