### ISSUE TITLE
Go to references of Widget property only search in same file with Flutter 3.7+

### ISSUE THREAD

**Issue by quyenvsp** [Dart-Code/Dart-Code#4535]
**Describe the bug**
On newer Flutter version 3.7+ Go to References of Widget property only find in same file.
Old version 3.3.2 working fine.
Go to References of function property work fine on both

**To Reproduce**
1. Clone https://github.com/noncheat/flutter_gotoreferences
2. Using Flutter 3.3.2, right click `required this.problemReferences,` lib/test.dart:6 > Go to References
3. Result will show `main.dart` and `test.dart`
4. Using Flutter 3.10.0 repeat step 2
5. Result only show `test.dart`

**Expected behavior**
Flutter 3.7+ when use `Go to References` of Widget property should find in all files.

**Screenshots**
Working - Go to References of Widget property in Flutter 3.3.2
![](https://github.com/noncheat/flutter_gotoreferences/raw/master/3.3.2_work.png)

Problem - Go to References of Widget property in Flutter 3.10.0
![](https://github.com/noncheat/flutter_gotoreferences/raw/master/3.10.0_problem.png)

Working - Go to References of function property in Flutter 3.10.0
![](https://github.com/noncheat/flutter_gotoreferences/raw/master/3.10.0_work_function.png)

**Please complete the following information:**
 - Operating System and version: Windows 11
 - VS Code version: 1.78.1
 - Dart extension version: v3.62.0
 - Dart/Flutter SDK version: Dart 3.0.0 / Flutter 3.10.0

**Comment by DanTup** [comment]
Thanks - I can repro this. I think it may be specific to using `this.` on the parameters. A smaller repro:

```dart
class AAA {
  final String? aaa;
  const AAA({this.aaa}); // Find reference on aaa here doesn't find the below
}

const a = AAA(aaa: ''); // Go-to-Definition on aaa here works
```

**Comment by DanTup** [comment]
This is fixed by https://github.com/dart-lang/sdk/commit/2d43bc319d3dd00b9cd878597e14e8da61dfb2a5.

The change is in the Dart analysis server so it'll show up in a future SDK release (rather than a Dart-Code release).
