### ISSUE TITLE
Invalid argument(s): Windows paths with drive letter must be absolute the Dart compiler exited unexpectedly.

### ISSUE THREAD

**Issue by IYakRiyadh** [Dart-Code/Dart-Code#4537]
Unhandled exception:
Invalid argument(s): Windows paths with drive letter must be absolute
#0      _Uri._makeWindowsFileUrl (dart:core/uri.dart:1899:9)
#1      new _Uri.file (dart:core/uri.dart:1809:11)
#2      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:592:54)
#3      listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1308:26)
#4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#7      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#8      _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#9      _StringAdapterSink.add (dart:convert/string_conversion.dart:228:11)
#10     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:164:13)
#11     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:131:7)
#12     StringConversionSink.add (dart:convert/string_conversion.dart:39:5)
#13     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#14     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#17     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#18     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#19     _StringAdapterSink.add (dart:convert/string_conversion.dart:228:11)
#20     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:233:7)
#21     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:307:20)
#22     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300:5)
#23     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
#24     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#25     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#28     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#29     _StreamController._add (dart:async/stream_controller.dart:650:7)
#30     _StreamController.add (dart:async/stream_controller.dart:598:5)
#31     _Socket._onData (dart:io-patch/socket_patch.dart:2368:41)
#32     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#33     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#34     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#35     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#36     _StreamController._add (dart:async/stream_controller.dart:650:7)
#37     _StreamController.add (dart:async/stream_controller.dart:598:5)
#38     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1886:33)
#39     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1343:14)
#40     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#41     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#42     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
#43     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:190:5)
the Dart compiler exited unexpectedly.
Waiting for connection from debug service on Chrome...              3.9s
Failed to compile application. 

please try many but is still like this.

**Comment by DanTup** [comment]
Are you able to provide some details about what you did that resulted in this error?
