### ISSUE TITLE
Support multi-root workspaces - SDK paths

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#454]
Splitting this from #453 because it may result in much discussion!

Currently we have some flags that say whether we're a Flutter/Fuchsia project and we use them to influence the search paths for SDKs. With multi-roots, we might have a Flutter and a standard Dart project loaded (or even multiple of each). This raises some interesting questions... If I open a project that has three workspace folders like this:

- Dart frontend website
- Flutter mobile app
- Dart web server app (used as API for mobile app and website)

What do we do to pick the SDK location? Do we just pick the "best" (eg. in this case, Flutter wants a specific SDK so we use that for the Dart projects too?). Is it safe to just have a preference like this? If we end up with a Fuchsia and Flutter project, is it safe to use either of those for the other?

If this isn't safe and we decide that we should use multiple SDKs (spawning multiple analysers), what about places that need to know the SDK that don't have the context of a folder (for example the user initiates `pub get` from the command palette)? Would spawning multiple analysers introduce other issues (not being able to navigate between them or excessive resource usage?)

What about if there are multiple Flutter projects? How do we get a device list? Where do we run Flutter from? Is it reasonable to just refuse to load multiple Flutter projects? What about if people have two related apps and want to work on them together?

Probably we don't need to worry about Fuchsia + Flutter projects for now so probably we can just refuse to load Fuchsia in the presence of another Flutter app (this might not be reasonable in the future, but until more is known about Fuchsia I have no idea).

**Comment by DanTup** [comment]
@devoncarew Any opinions on the above? Code supports opening multiple folders now so I'm trying to figure out the best way to handle these. I'd really like to just use a single analyser and provide all the folders to it, but Flutter having its own SDK kinda complicates this.

How common is it for people to work with Flutter+other Dart projects in one IDE window? Do other IDEs handle this reasonably?

**Comment by Skylled** [comment]
My understanding of Fuchsia is that it uses Flutter in its own way, so I imagine any multi-root project related to Fuchsia would use the Fuchsia SDK for all roots. So goes my limited understanding.

As for a Dart + Flutter multi-root, I don't know what's more idiomatic: to use Flutter's cached SDK directly, or use a standard SDK.

I know my poor laptop's 6GB of RAM would not be able to handle a second analyzer instance running, so if I were to multi-root, I'd only want one instance. But I'm definitely not the end user of this example.

Two flutter projects should be simpler. The device list would be identical for both, so `launch.json` could be made to look like:
```
        {
            "name": "{Workspace 0 Root Dir Name}",
            "type": "flutter",
            "request": "launch",
            "workspace": 0,
        },
        {
            "name": "{Workspace 1 Root Dir Name}",
            "type": "flutter",
            "request": "launch",
            "workspace": 1,
        }
```
If something like that is possible. Then it's always clear which project is hooked to F5, from the status bar indicator/switcher.

I'm just not sure how well the single analyzer would handle both projects simultaneously.

**Comment by DanTup** [comment]
> My understanding of Fuchsia is that it uses Flutter in its own way, so I imagine any multi-root project related to Fuchsia would use the Fuchsia SDK for all roots.

I somewhat forgot when I wrote this that Fuchsia has a Flutter SDK inside it, so maybe this one isn't as complicated as I thought.

If we assume Fuchsia SDK is a superset of Flutter SDK which is a superset of Dart SDK, then maybe we can just work through that chain and pick the first one.

> As for a Dart + Flutter multi-root, I don't know what's more idiomatic: to use Flutter's cached SDK directly, or use a standard SDK.

Likewise, I'm not sure. I hope that using the Flutter SDK's Dart SDK for the analyser would be good (including executing the programs and running the debugger from it) though it does mean that people might end up running Dart apps in an unstable SDK more (but if you're working on a Flutter project, this probably isn't a concern, you're already doing it).

> I know my poor laptop's 6GB of RAM would not be able to handle a second analyzer instance running

That's my big concern with not sharing the server; we're already running Electron/Node/etc. and it's quite fat - I don't want to limit Dart Code to small toy projects because of resource usage.

> so if I were to multi-root, I'd only want one instance. But I'm definitely not the end user of this example.

I don't think multi-root is going to be that uncommon. If I was working on a flutter app, it'd probably have a web API to run on the server - having them both open seems like a really basic need (at least if you're developing the API/App together).

**Comment by DanTup** [comment]
> Two flutter projects should be simpler. The device list would be identical for both

I just checked, and `flutter daemon` *seems* to work outside of a project folder; so I think this actually will be easy too - I can just run it from whichever SDK we settled on and not have to worry about it being per-project :-)

> I'm just not sure how well the single analyzer would handle both projects simultaneously.

I'm not sure what you mean here - I think the analyser works fine for multiple projects (I can provide it an array of roots; though it also already walks down figuring out which folders inside those may be their own roots - with [one exception](https://github.com/dart-lang/sdk/issues/29414)).

**Comment by DanTup** [comment]
So, after all that, I'm now wondering if there's anything complicated here at all!

- If there are *any* Fuchsia projects, use the first ones SDKs (Fuchsia/Flutter/Dart) for everything
- Else, if there are any Flutter projects, use the first ones SDKs (Flutter/Dart) for everything
- Else, do normal Dart stuff

For workspaces, we'll push the SDK override paths up to the workspace settings (not the folder settings, which were previously called workspace settings).

Hopefully @devoncarew or @yyoon can confirm if they know of anything weird that might happen if we try to use Flutter's Dart SDK for standard Dart dev (or same for using Fuchsia's Flutter/Dart SDKs for the same) but if not, I'll try and take a crack at it soon.

**Comment by DanTup** [comment]
In a quick test, this seems to be working OK, so I'm consider this decided :-)

**Comment by devoncarew** [comment]
Hey - just to chime in here - using one analysis server instance per window makes sense to me. The analysis server will be able to handle analyzing multiple projects just fine, and one-server-per window is easy for the user to reason about.

**Comment by DanTup** [comment]
@devoncarew Thanks! This is what I've done and it seems to be working. There's the possibility of strange things happening if you open multiple project types together (eg. Fuchsia + Flutter) and you have something relying on a specific version (eg. your Flutter project needs latest Flutter but Fuchsia is shipping an older version) but I think that's an edge case we probably don't need to worry about (the probability of the few people using DC for Fuchsia also working on a mobile Flutter app and need bleeding edge seems very low!).
