### ISSUE TITLE
Embedded DevTools is blocked from using clipboard APIs

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#4540]
See https://github.com/flutter/devtools/issues/5775

We likely need to add an `allow` attribute to the iframe we use for embedding DevTools.

**Comment by DanTup** [comment]
I'm apparently unable to make this work. Although clipboard access works inside the main VS Code iframe, it doesn't seem to work for other origins.

I modified the VS Code webview sample to have a button that copies to the clipboard, and also iframe a page that has a button the same:

Webview:

```htm
return `<!DOCTYPE html>
	<html lang="en">
	<head>
		<meta http-equiv="Content-Security-Policy" content="default-src ${webview.cspSource} https: 'unsafe-inline'; frame-src ${webview.cspSource} https://gist.githubusercontent.com http://localhost:8000/ https;">
	</head>
	<body bgcolor="blue">
		<button onclick="window.navigator.clipboard.writeText('test');">Copy "test" to clipboard</button>

		<iframe src="http://localhost:8000/index.htm"  allow="clipboard-write" />
	</body>
	</html>`;
```

And the `index.html`:

```html
<html>
<body style="background-color: white !important;">
    <h1>My Frame</h1>

    <button onclick="window.navigator.clipboard.writeText('test2222');">Copy "test2222" to clipboard</button>
</body>
</html>
```

Clicking the button in the outer frame works fine, but the inner frame fails:

```
Uncaught (in promise) DOMException: Write permission denied.
```

We've reported another VS Code clipboard issue that may be related (https://github.com/microsoft/vscode/issues/129178). In there, it was noted:

> Interestingly, we cannot access `navigator.clipboard` inside the child iframe in the webview even if we add `allow="clipboard-read; clipboard-write;"` to the iframe tag in the parent webview. This might be related to the following issue:
> 
> - https://bugs.chromium.org/p/chromium/issues/detail?id=1074489

However, that bug was apparently fixed. The are comments saying it doesn't work for deeply nested frames:

https://bugs.chromium.org/p/chromium/issues/detail?id=1074489#c40

But a contributor said it works (unfortunately the sample site is no longer available).

https://bugs.chromium.org/p/chromium/issues/detail?id=1074489#c42

Needs some more debugging...

**Comment by DanTup** [comment]
This might be the answer:

https://stackoverflow.com/a/69741484/25124

It seems like because we're cross-origin, the parent `allow="clipboard-write"` on the VS Code iframe might not pass permissions to us unless it lists our domain. However, editing this in the developer tools doesn't help (but I don't know whether that applies immediately).

**Comment by DanTup** [comment]
Since this same setup seems to work outside of VS Code (nested iframes crossing origins with `allow=clipboard-wite`) I've opened https://github.com/microsoft/vscode/issues/182642 about this to see if the VS Code devs might consider this a VS Code bug.

**Comment by DanTup** [comment]
Fixed by https://github.com/Dart-Code/Dart-Code/pull/4814, but requires the related change in DevTools

**Comment by kenzieschmoll** [comment]
Seeing this issue again when trying to call `Clipboard.setData` from DevTools, which falls back to calling the VS Code workaround
```
  window.parent?.postMessage(
    {
      'command': 'clipboard-write',
      'data': data,
    }.jsify(),
    '*'.toJS,
  );
```
which also fails:
```
copy is not successful NotAllowedError: Failed to execute 'writeText' on 'Clipboard': Document is not focused.
main.dart.js:50566 Copy failed. This may be as a result of a known bug in VS Code. See https://github.com/Dart-Code/Dart-Code/issues/4540 for more information. Now attempting to use a fallback method of copying the that is a workaround for VS Code only.
VM7:49 Uncaught (in promise) DOMException: Failed to execute 'writeText' on 'Clipboard': Document is not focused.
    at <anonymous>:49:24
```

**Comment by DanTup** [comment]
This looks like a ifferent problem so I've moved to https://github.com/Dart-Code/Dart-Code/issues/5209
