### ISSUE TITLE
Provider tab not available in devtools

### ISSUE THREAD

**Issue by Maxim-Filimonov** [Dart-Code/Dart-Code#4558]
**Is your feature request related to a problem? Please describe.**
Hi, I noticed that in the flutter web devtools there is provider tab which is not accessible with vscode flutter extensions.
![CleanShot 2023-05-20 at 22 47 06](https://github.com/Dart-Code/Dart-Code/assets/360645/3afe7863-980f-4023-a9e7-32ac4fff8b98)

**Describe the solution you'd like**
Would be great to be able to access provider view without switching to chrome.

**Describe alternatives you've considered**
Continue using chrome 

**Additional context**

**Comment by DanTup** [comment]
This is a known limitation right now. We only support a fixed set of tabs that are known in advance.

There are some potential changes being discussed about how DevTools is extended (for packages like provider) that might change this and make it easier to support additional DevTools extensions more generally, so it makes sense to wait until it's clear what direction that will go in before doing anything here.

**Comment by DanTup** [comment]
DevTools extensions can be launched from the Flutter sidebar now and can be loaded embedded:

https://github.com/user-attachments/assets/90a8c471-0a38-401b-91f3-f2ddee472e1b
