### ISSUE TITLE
Nested multi-line comments do not colour properly

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#456]
<img width="299" alt="screen shot 2017-11-26 at 16 15 52" src="https://user-images.githubusercontent.com/1078012/33241958-3ac030e4-d2c5-11e7-8e34-bdc311394b6f.png">

I dunno how easy it'll be to fix this given the current highlighting is regex. Seems like Atom, GitHub, StackOverflow etc. also don't handle this correctly so we're in good company =)

**Comment by DanTup** [comment]
Gonna consider this blocked by https://github.com/Microsoft/vscode/issues/585

**Comment by apaatsio** [comment]
I think this should be reopened. I'm still experiencing this.

![vscode_dart_nested_comments_highlighting](https://user-images.githubusercontent.com/195210/53682639-04b46d00-3cf8-11e9-8074-07b77c3e6586.png)

Dart Code: 2.24.0
Dart VM version: 2.1.2-dev.0.0.flutter-0a7dcf17eb (Tue Feb 12 01:59:15 2019 +0000) on "linux_x64"
VSCode: 1.31.1

**Comment by DanTup** [comment]
@apaatsio Thanks, looks like this one only fixed them when they start with `/**`. I've opened https://github.com/Dart-Code/Dart-Code/issues/1498 to cover this (I prefer new issues to re-opening if a fix has already shipped, so the issues/milestones still match up).

Thanks!
