### ISSUE TITLE
200000000

### ISSUE THREAD

**Issue by Novalkrsn** [Dart-Code/Dart-Code#4562]
**Describe the bug**

**To Reproduce**
1. Go to '083837075730...'
2. Click on 'PERMATA BANK....'

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - Operating System and version:
 - VS Code version:
 - Dart extension version:
 - Dart/Flutter SDK version:
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
This doesn't appear to be a valid bug report/feature request. If it was intended to be, please add additional information.
