### ISSUE TITLE
Don't show Run/Debug button for files that don't have a main function

### ISSUE THREAD

**Issue by suranjum** [Dart-Code/Dart-Code#4563]
Type: <b>Bug</b>

The Run button used be active only on main.dart. After an update (note sure which on), the Run button is now active on all .dart extension file, which gives error main entry not found. Either the Run button should be active only on main.dart or the extension should locate and run main.dart automatically.

Extension version: 3.64.0
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:47:05.613Z)
OS version: Linux x64 5.15.0-72-generic
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 1|
|Memory (System)|15.52GB (10.32GB free)|
|Process Argv|--unity-launch --crash-reporter-id 1852884f-79c8-474c-9f62-50a1ce6988de|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by DanTup** [comment]
This is expected. There is no requirement for your entry point to be `lib/main.dart` so in https://github.com/Dart-Code/Dart-Code/issues/4429 the restrictions on when this button should show up were removed.

The button is designed to "run the current file" so it would be confusing to run a different file. There should be no loss of functionality from before, the button simple appears in more places - it will still always behave the same when clicked in a file where it used to appear.

I would recommend using `F5`, the `Run` menu, or the buttons on the Debug Sidebar if you want the usual heuristics of which file to run (which takes the open file into account, but will look for a `lib/main.dart` if it's not a `bin`/`tool`/`test` file.

**Comment by mindnect** [comment]
@DanTup 
I accidentally clicked the run button several times. I'm new to Flutter, so I spent few hours without knowing why. I ended up hiding the button. 

Shouldn't the run button only appear when there is a main function? If I run it on a file without a main function, I get "Could not prepare isolate." error anyway. This change just confuses the user. I'm wondering I'm missing somthing.

Thank you.

**Comment by DanTup** [comment]
For the original set of files (`lib/main.dart`, `tool/*`, `bin/*`) we'll continue to always show the buttons. But for other files (the ones that only recently started showing the buttons) we'll now only show it if there's a `main` function:

![May-30-2023 10-46-57](https://github.com/Dart-Code/Dart-Code/assets/1078012/063bfb58-b2c2-4edb-9346-d3d8a9220ec0)
