### ISSUE TITLE
flutter outline view

### ISSUE THREAD

**Issue by fredgrott** [Dart-Code/Dart-Code#4565]
Not sure if it's a dart code plugin bug or an actual VSCode bug.

While one sees two outlines with one being the Flutter outline view. Both the VSCode outline view and the dart plugin outline view get hidden by the same hide command resulting in not being able to hide VSCode outline view so that one can get the only flutter outline view in the 2nd sidebar.

**Comment by DanTup** [comment]
Can you clarify what you mean by "hidden by the same hide command"?

I tried hiding the built-in Outline from VS Code here:

<img width="372" alt="Screenshot 2023-05-28 at 14 50 09" src="https://github.com/Dart-Code/Dart-Code/assets/1078012/ebb4ac3b-4ebc-4687-aa43-28c2b5a0d0fc">

But it didn't affect the Flutter Outline on its own tab:

<img width="268" alt="Screenshot 2023-05-28 at 14 51 05" src="https://github.com/Dart-Code/Dart-Code/assets/1078012/9d7c4ce6-12a8-4f86-85eb-a99df915e1f9">
