### ISSUE TITLE
iOS native logs not showing up

### ISSUE THREAD

**Issue by Wolfikus** [Dart-Code/Dart-Code#4568]
**Describe the bug**
When debugging the project with VSCode - all print/logs from Dart are logged in properly into Debug Console, but logs from native platform are missing (for root project/plugins)

**To Reproduce**
1. Put `print("1")` in AppDelegate.swift `didFinishLaunchingWithOptions` before `return` statement
2. Run the application with VSCode
3. Observe, that `"1"` not printed out into Debug Console

**Expected behavior**
Both types of log messages should be reported properly into Debug Console

**Please complete the following information:**
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.2.1 22D68 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.78.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

Dart extension version - v.3.64.0

**Comment by DanTup** [comment]
Do these show up if you run from the command line with `flutter run`? If not, then this would need implementing in Flutter itself (https://github.com/flutter/flutter/).

I did try to test this, but I don't have a `didFinishLaunchingWithOptions` in my generated `AppDelegate.swift` so I'm not sure where to add the `print` (I've never used Swift unfortunately!).

**Comment by cg-tester** [comment]
@Wolfikus 
I am having same issue now, how did you resolve?
