### ISSUE TITLE
Latest version of Flutter / Dart (3.66.0) destroyed my Monokai-Vibrant Theme in VSCode

### ISSUE THREAD

**Issue by rr-appadaptive** [Dart-Code/Dart-Code#4569]
After the update of Flutter/Dart to version 3.66.0, the color scheme I use in VSCode (Monokai-Vibrant) does no longer show widget-properties and function variables / parameters in dark-orange as before. Everthing is white now which makes coding quite difficult. This behaviour now happens with any VSCode-Theme but only in Flutter and Dart.

**Comment by DanTup** [comment]
Can you provide a screenshot of what you're seeing?

Can you also click Help -> Toggle Developer Tools  and then check the Console tab to see if there are any errors listed?

**Comment by rr-appadaptive** [comment]
Thank you for the very prompt reaction.
In the meantime I restarted VSCode several times and after that had no effect, I rebooted my Mac (MacOs-Ventura). Now everything seems to be as before. I've no idea why, but the main thing is, that it works again.

**Comment by rr-appadaptive** [comment]
P. S.: maybe I should always reboot my machine before sending an issue....

**Comment by DanTup** [comment]
Did you have multiple VS Code windows open? White text usually means the extension hasn't loaded correctly (or is corrupt). If the extension was being installed by one window as another tried to load it, it's possible it failed to load the extension. I would've expected restarting VS code to have cleaned that up though. I can't think of why a reboot would be different to restarting, unless there were some stuck processes in the background.

Updating of the extension is all handled by VS Code so I'm not too familiar with it - though we've had some reports of corrupt extensions before (and uninstalling them does not delete them from disk, you need to do this manually in `~/.vscode/extensions`) but it's fairly infrequent.

In any case, I'm glad it's sorted itself out, but please do let me know if you see it gain (and provide screenshots and info from the console noted above in case useful).

Thanks!
