### ISSUE TITLE
Non exaustively matched switch doesn't offer fix anymore

### ISSUE THREAD

**Issue by JCKodel** [Dart-Code/Dart-Code#4570]
**Describe the bug**
Before Dart 3.0, when we had some `switch` on an enum with missing values, there was a warning (The type 'EnumSomething' is not exhaustively matched by the switch cases since it doesn't match 'EnumSomething.value') and, at least in VSCode, a `^.` would offer a fix. When the fix was applied, all enum cases were inserted automatically.

After Dart 3.0, the same thing only offers to convert it to a switch expression (which doesn't even make sense, since that old switch isn't an expression).

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an enum with 2 or 3 values
2. Type a `switch(Enum)` empty block
3. Type `^.` or the 💡 to bring the quick-fix menu

**Expected behaviour**

The old switch fix should be enabled and the convert to switch expression should not be shown, because it is not a valid place for it.

**Screenshots**
![image](https://github.com/Dart-Code/Dart-Code/assets/379339/4cfc0bfa-4cb2-4d71-8cbc-2fd42edc74a1)

**Please complete the following information:**
 - Operating System and version: Windows 11 22H2 (22621.1702)
 - VS Code version: 1.78.2
 - Dart extension version: 3.66.0
 - Dart/Flutter SDK version: Dart 3.0.2, Flutter 3.10.2
 - Target device (if the issue relates to Flutter debugging): n/a

**Comment by DanTup** [comment]
Thanks - there's an SDK issue open tracking this at https://github.com/dart-lang/sdk/issues/51985. From the comments it seems that some fixes have landed since the stable was branched, but there may be further improvements to be made.
