### ISSUE TITLE
Flutter structured errors aren't formatted well when using SDK DAPs

### ISSUE THREAD

**Issue by waleedf112** [Dart-Code/Dart-Code#4571]
The console doesn't show the exceptions correctly, links are in red, not clickable, 

[Dart-Code-Log-2023-05-05 19-17-57.txt](https://github.com/Dart-Code/Dart-Code/files/11637349/Dart-Code-Log-2023-05-05.19-17-57.txt)

_______
**with legacy DAPs:**
start of the exception:
![image](https://github.com/Dart-Code/Dart-Code/assets/44902066/b5c6bd35-b7a4-45b8-a132-0d22d0ff0cea)
middle:
![image](https://github.com/Dart-Code/Dart-Code/assets/44902066/7685d151-9718-4d64-acdb-03e4722126dd)
end:
![image](https://github.com/Dart-Code/Dart-Code/assets/44902066/6ac4ff8e-8f2a-42ce-8ce2-7e4fa0f790dc)

_______
**currently:** all of the console log looks like this with nothing clickable and not clear stacktrace.
![image](https://github.com/Dart-Code/Dart-Code/assets/44902066/1f863d1d-6f78-4ffc-abee-e6ad129ecbc6)

**Comment by DanTup** [comment]
Here's a small repro with the `Flutter.Error` event JSON and how each adapter looks:

- [main.dart](https://github.com/Dart-Code/Dart-Code/files/11818941/main.dart.txt)
- [error_event.json](https://github.com/Dart-Code/Dart-Code/files/11818942/error_event.json.txt)
- [error_legacy_dap.txt](https://github.com/Dart-Code/Dart-Code/files/11818947/error_legacy_dap.txt)
- [error_sdk_dap.txt](https://github.com/Dart-Code/Dart-Code/files/11818950/error_sdk_dap.txt)

## Legacy:
![error_legacy_dap](https://github.com/Dart-Code/Dart-Code/assets/1078012/e197817a-5546-4962-a8c8-2fdeddf8e014)

## SDK:
![error_sdk_dap](https://github.com/Dart-Code/Dart-Code/assets/1078012/135a3fee-9380-4e99-81f7-ca6414e6a049)

**Comment by DanTup** [comment]
Improvements to this have landed in the latest Flutter master and will, ship in a future SDK.
