### ISSUE TITLE
Question: Implement Solution Explorer

### ISSUE THREAD

**Issue by JCKodel** [Dart-Code/Dart-Code#4580]
I don't even know if this is possible, but... let's try =)

Usually, when using Visual Studio (the big brother) in a C# project, we have a "Solution" that has *n* "Projects" inside it. Each project can import other projects (adding a reference) and you have a default project, which will be the entry point when you hit Run or Debug.

Often, we work in Flutter with some libraries that we build (not present in pub.dev) or even some public packages with local sources (either by importing the package by `git` or `path`).

For instance, this project has 9 libraries not published to pub.dev, which are shared amongst many other projects:

![image](https://github.com/Dart-Code/Dart-Code/assets/379339/b9547774-a29d-454b-ac6d-8adb3822799c)

Usually, this is done by adding a git submodule inside my project, so I can change those libraries while using them (after all, they are not complete package-in-a-box, at least not yet). Sometimes, you grab a package that you need, but it has a bug or some dependency issue so you are forced to download a fork and make changes so it work, you know the drill. The problem with submodules is that `import` will point to files as they were part of the project (and not by `package:library/library.dart`), so when you finally publish that package or change projects, all imports will need work.

Recently, Microsoft has published a beta version of C# DevKit, which brings a Solution Explorer to VSCode (with almost all things Visual Studio can do, translated to CLI commands). It's not perfect as Visual Studio, but it works A LOT better than the "open folder all in one" current C# style.

So, I wondered:

There is any possibility to make Dart work with this kind of organization? I mean, get Dart projects in different folders and organize them as a solution (so we don't have to maintain submodules inside our project).

Perhaps with some clever pubspec.yaml `dependency_overrides` and some tinkering here and there in imports, we could somehow simulate this solution behavior for Dart projects?

**Comment by DanTup** [comment]
I'm not sure I understand exactly what's being asked for.

>  The problem with submodules is that import will point to files as they were part of the project (and not by `package:library/library.dart`), so when you finally publish that package or change projects, all imports will need work.

Isn't this what dependency_overrides is supposed to prevent? You clone a fork, use dependency_overrides to point at your local version. I'm not sure why the imports need changing.


Could you give a more detailed description of the workflow without/with this, or what functionality it would have that isn't available today?
