### ISSUE TITLE
Flutter Extension | Network Error When run Flutter: Run Flutter Doctor in VSC

### ISSUE THREAD

**Issue by VovaSv** [Dart-Code/Dart-Code#4595]
**Describe the bug**
Get an error below when run **Flutter: Run Flutter Doctor** in VSC.
No error when run **flutter doctor -v** command in VSC terminal  (Note! In terminal proxy was set **export https_proxy=**)

Error:
```
[!] Network resources
    ✗ A network error occurred while checking "https://pub.dev/": Failed host lookup: 'pub.dev'
    ✗ A network error occurred while checking "https://storage.googleapis.com/": Operation timed out
    ✗ A network error occurred while checking "https://maven.google.com/": Failed host lookup: 'maven.google.com'
    ✗ A network error occurred while checking "https://cocoapods.org/": Failed host lookup: 'cocoapods.org'
    ✗ A network error occurred while checking "https://github.com/": Failed host lookup: 'github.com'
```

**To Reproduce**
1. Run **Flutter: Run Flutter Doctor** via Flutter VSC extenssion

**Expected behavior**
```
[✓] Network resources
    • All expected network resources are available.
```

**Screenshots**
```
[!] Network resources
    ✗ A network error occurred while checking "https://pub.dev/": Failed host lookup: 'pub.dev'
    ✗ A network error occurred while checking "https://storage.googleapis.com/": Operation timed out
    ✗ A network error occurred while checking "https://maven.google.com/": Failed host lookup: 'maven.google.com'
    ✗ A network error occurred while checking "https://cocoapods.org/": Failed host lookup: 'cocoapods.org'
    ✗ A network error occurred while checking "https://github.com/": Failed host lookup: 'github.com'
```

**Please complete the following information:**
 - Operating System and version: macOS
 - VS Code version: 1.63.2
 - Dart extension version: v3.36.0
 - Dart/Flutter SDK version: 3.0.5
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
My guess is that you have set `https_proxy` in a terminal script which only applies to terminals. Code executed by VS Code (if VS Code was not spawned from within the terminal) will not be able to see that value.

You can apply environment variables to processes started by the Dart/Flutter extension using the `dart.env` VS Code User Setting. For example:

```js
{
    "dart.env": {
        "HTTPS_PROXY":  "...",
    }
}
```

Please let me know if this doesn't work.

**Comment by Zain123alimohammed** [comment]
PS C:\Users\Admin23\StudioProjects\appmm> flutter doctor
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.0, on Microsoft Windows [Version 10.0.19045.4412], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.13.6)
[√] Android Studio (version 2022.2)
[√] VS Code (version 1.103.2)
[√] Connected device (3 available)
[!] Network resources
    X A network error occurred while checking "https://pub.flutter-io.cn": Failed host lookup: 'pub.flutter-io.cn'
    X A network error occurred while checking "https://storage.flutter-io.cn": Failed host lookup:
      'storage.flutter-io.cn'
    X A network error occurred while checking "https://cocoapods.org/": Failed host lookup: 'cocoapods.org'
    X A network error occurred while checking "https://github.com/": Failed host lookup: 'github.com'

**Comment by DanTup** [comment]
@Zain123alimohammed this is an old issue, please open a new one if you're having problems.

But it looks like you're on a fairly old version of Flutter (July 2024) so I would try upgrading to the latest version of Flutter first.
