### ISSUE TITLE
add a command to invoke the analyzer's reanalyze source command

### ISSUE THREAD

**Issue by devoncarew** [Dart-Code/Dart-Code#46]
For cases where analysis gets off-track.

**Comment by DanTup** [comment]
It feels a bit naff to expect the user to know about/understand this so if there are things that we think might cause it maybe we can mitigate it?

Have you seen it happen? Do you know what causes it?

**Comment by devoncarew** [comment]
It's useful periodically; we'll hopefully drive down the need to reanalyze sources. We can close this for now -

**Comment by DanTup** [comment]
I'm not against having this; though it might be worth only adding as a last resort. If we teach users to use this they might never report if they do end up with issues.

Maybe we should re-discuss on the first report/instance of seeing this happen. We certainly don't want to end up in a bad state feeding the user useless errors (which I saw before I fixed the 0/1-based issue!).

Although if we can detect it programatically (eg. we get back an error for something, or a position that doesn't match up) we could always kick it off (though we might need to consider if we should clear all file buffers and re-send all dirty files too?)

**Comment by devoncarew** [comment]
I'm not sure it's something that we can detect automatically. I thought I saw it once w/ the vscode extension (which is why I filed this bug) - it turned out to be user error.

The user can always call the `reload window` command, which would act similarly.

**Comment by DanTup** [comment]
If we do add this we could log uses of this (a count in the persistent state passed in ExtensionContext and an Analytic event) and if it hits a threshold maybe prompt the user to provide info or report a bug.

I'll mark as Post-V1 for now and if we're sure it's happening or see reports we can bring it forwards.

**Comment by DanTup** [comment]
@devoncarew Look what just happened to me in the TS editor:

https://github.com/Microsoft/vscode/issues/10306

While making some suggestions (since re-opening a file didn't fix it!) it made me wonder whether reanalyze would actually fix the same issue here - if the overlays are bad, wouldn't it just re-send bad stuff?

I don't think we'd suffer from the same issue as the TS one, as it seems they're not re-sending the file when it's opened (we remove overlays on close and re-send on open - which I think is wasteful, but the analyzer seems to require).

**Comment by DanTup** [comment]
@devoncarew In the time you've had this, have you ever hit an issue where this would be useful?

If not, I think we should ditch this? If you have, do you still think it's worth having its own command instead of just using Reload Window?

**Comment by devoncarew** [comment]
I've just been using `reload window` in place of this; sounds good to close :)

**Comment by DanTup** [comment]
Ok; I'd still be interested in understanding the reasons for using it (if they're obvious) and the frequency in case we can do things to improve (for example, we could ping the AS periodically and re-load if we think it crashed).
