### ISSUE TITLE
Formatting of test report is broken

### ISSUE THREAD

**Issue by DFelten** [Dart-Code/Dart-Code#4602]
Type: <b>Bug</b>

Currently the formatting of the test report popup is broken. The line does not start on the left, but in the middle.

I've created this issue in the VSCode repo, but it seems to be an issue of the Flutter extension: https://github.com/microsoft/vscode/issues/185778

<img width="1311" alt="CleanShot 2023-06-21 at 16 40 01@2x" src="https://github.com/microsoft/vscode/assets/1169185/cdfbd146-d33d-49f9-82a6-a55a47f96eb6">

VS Code version: Code - Insiders 1.80.0-insider (636dbcff557af8aa088ae118b1a094dce6632ce7, 2023-06-21T08:21:53.800Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|32.00GB (1.19GB free)|
|Process Argv|--crash-reporter-id 511166e9-0c5e-4225-a6af-efd2d90c3f8d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (81)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
vscode-m3u|af4|1.0.0
TabOut|alb|0.2.2
Bookmarks|ale|13.3.1
project-manager|ale|12.7.0
flutter-snippets|ale|3.0.0
toggle-excluded-files|amo|2.0.0
clipboard-history|Anj|1.0.7
melos-code|bla|1.0.1
vscode-intelephense-client|bme|1.9.5
ccs-flutter-color|cir|1.0.2
gitignore|cod|0.9.0
vscode-mysql-client2|cwe|6.5.5
vscode-mac-color-picker|dae|1.1.0
markdown-table-prettify|dar|3.6.0
dart-code|Dar|3.67.20230619
flutter|Dar|3.67.20230601
vscode-markdownlint|Dav|0.51.0
githistory|don|0.6.20
gitlens|eam|14.0.1
bloc|Fel|6.6.3
mason|Fel|0.1.10
flutter-coverage|flu|0.0.4
shell-format|fox|7.2.5
copilot-chat|Git|0.3.2023062101
copilot-labs|Git|0.14.884
copilot-nightly|Git|1.90.175
vscode-github-actions|git|0.25.8
vscode-pull-request-github|Git|0.66.1
gitlab-workflow|Git|3.67.0
todo-tree|Gru|0.0.226
terraform|has|2.26.1
json-to-dart|hir|3.5.8
rest-client|hum|0.25.1
monkey-patch|ioc|0.1.23
pubspec-assist|jer|2.3.2
shortcut-menu-bar|jer|3.0.4
intellij-idea-keybindings|k--|1.5.9
indent-to-bracket|LAK|1.2.2
flutter-intl|loc|1.19.2
syntax-project-pbxproj|mar|0.1.3
flutter-snippets|Mar|1.0.5
Kotlin|mat|1.7.1
rainbow-csv|mec|3.7.0
git-graph|mhu|1.30.0
dart-barrel-file-generator|miq|6.1.1
diff-merge|mos|0.7.0
vscode-docker|ms-|1.25.1
vscode-language-pack-de|MS-|1.80.2023062109
remote-containers|ms-|0.296.0
live-server|ms-|0.4.8
vsliveshare|ms-|1.0.5873
vsliveshare-pack|ms-|0.4.0
vscode-flutter-freezed-helper|mth|0.1.0
sqltools|mtx|0.27.1
sqltools-driver-mysql|mtx|0.5.1
awesome-flutter-snippets|Nas|4.0.1
vscode-streamdeck|nic|4.1.6
vscode-yaml-sort|Pas|6.5.3
vscode-versionlens|pfl|1.5.0
material-icon-theme|PKi|4.28.0
remove-comments|pli|1.2.2
vscode-thunder-client|ran|2.7.7
vscode-yaml|red|1.13.0
vscode-sort-json|ric|1.20.0
command-variable|rio|1.53.0
flutter-riverpod-snippets|rob|1.2.2
vscode-coverage-gutters|rya|2.11.0
lcov-lang|Ser|1.0.1
swift-lang|ssw|1.3.0
freezed-model-gen|Sus|1.0.1
better-search|tra|0.0.6
errorlens|use|3.11.1
vscode-lldb|vad|1.9.2
vscode-wakatime|Wak|24.0.14
vscode-todo-highlight|way|1.0.5
php-debug|xde|1.32.1
vscode-surround|yat|1.5.0
markdown-all-in-one|yzh|3.5.1
material-theme|zhu|3.15.17

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vslsvsres303:30308271
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
showlangstatbar:30737417
pythonms35:30671666
03d35959:30757351
ecj1e332:30687743
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
showindicator:30766888
pythongtdpath:30726887
gsof1:30771514
dh2dc718:30770000
pythonidxpt:30768918
pythondjangots:30768917
pythonnocebcf:30766856
copilotsettingc:30767685
e537b577:30772214

```

</details>

**Comment by DanTup** [comment]
I don't seem to be able to reproduce this. Can you provide an exact code sample that triggers this, and confirm the exact version of Flutter you're using? Thanks!

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/8eeec3fa-4664-44b9-9b66-ef7a49741272)

**Comment by DanTup** [comment]
Actually, I can repro this but only in Insiders. I'm pretty sure this is a VS Code issue - I'll ping there.

**Comment by DanTup** [comment]
I found the cause - seems like the handling of `\n` (without a `\r`) in the end of tests is handled differently now. I suspect it's deliberate though, so I'm going to fix it here.
