### ISSUE TITLE
hola

### ISSUE THREAD

**Issue by apprentablejb** [Dart-Code/Dart-Code#4605]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - Operating System and version:
 - VS Code version:
 - Dart extension version:
 - Dart/Flutter SDK version:
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
If you're having problems, you'll need to provide more details - this appears to just be a submission of the default template (I also had an email from you to logs@dartcode.org, but it's completely blank).
