### ISSUE TITLE
Hover documentation does not render SVG

### ISSUE THREAD

**Issue by Spooky12** [Dart-Code/Dart-Code#4609]
**Describe the bug**
SVG images inside documentation comments are not shown in hover documentation and code completion.
![image](https://github.com/Dart-Code/Dart-Code/assets/12486611/6025585d-9725-40dd-a8bd-2de0eb9592d4)

**To Reproduce**
Sample code in the image above can be used to reproduce the issue:
```dart
class Foo {
  /// <img src="https://raw.githubusercontent.com/Dart-Code/Dart-Code/master/media/icons/flutter_widget.svg" alt="FlutterWidget">
  ///
  /// ![](https://raw.githubusercontent.com/Dart-Code/Dart-Code/master/media/icons/flutter_widget.svg)
  static const String bar = 'fooBar';
}
````

**Expected behavior**
SVG icons should be shown in hover documentation and code completion.

**Please complete the following information:**
 - Operating System and version: macOS 12.5.1
 - VS Code version: 1.70.2
 - Dart extension version: 3.60.1
 - Dart/Flutter SDK version: 3.10.5

**Comment by Spooky12** [comment]
Yes I'm only seeing it with my own markdown and when I try with local SVGs it works fine.
So yes, it's just VS Code blocking SVGs from remote sources.

Thank you for your help

**Comment by DanTup** [comment]
Gotcha, in that case unfortunately there's nothing we can do here.  If possible, I would try to use another format for anything in doc comments.
