### ISSUE TITLE
wrap-with-widget ends up with weird cursor location

### ISSUE THREAD

**Issue by RandalSchwartz** [Dart-Code/Dart-Code#4614]
**Describe the bug**

**To Reproduce**
1. select a text widget
2. use lightbulb to "wrap with widget"
3. cursor ends up in middle of Text name, not highlighting "widget" for replacement.

**Expected behavior**
It should highlight the widget name for instant replacement

**Screenshots**

https://github.com/Dart-Code/Dart-Code/assets/6342/705945fb-3cfa-44e8-bbdb-acce0d619ab6

[dart.log](https://github.com/Dart-Code/Dart-Code/files/11891356/dart.log)

**Please complete the following information:**
 - Operating System and version:
 - VS Code version:
 - Dart extension version:
 - Dart/Flutter SDK version:
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
Seems like snippets aren't enabled in your log.. Need to figure out why...

Your log:

```js
"edits": [
	{
		"newText": "widget(child: Center(child: Text('hello')))",
	}
],
```

My log:

```js
"edits": [
	{
		"insertTextFormat": 2,
		"newText": "${1:widget}(${2:child}: const Placeholder())",
	}
],
```

**Comment by DanTup** [comment]
Ok, I think you might have `"dart.lspSnippetTextEdits": false` in your settings?

LSP doesn't support snippets here so this is an "unofficial extension" designed by the Rust team, but it should be on by default. Can you check if it's disabled, and if so do you recall why you might have disabled it?

**Comment by DanTup** [comment]
Confirmed via discord the setting was disabled and enabling it fixes it.

Please let me know if you find a reason you might have disabled it, so we can investigate fixing whatever that is in a different way.

Thanks!
