### ISSUE TITLE
Opening Flutter repo root results in analysis errors caused by incorrect package path resolution

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#462]
When opening the flutter Git repo, it's not detected as a Flutter project, so the wrong SDK is loaded.

**Comment by DanTup** [comment]
This seems to be caused by the deletion of a `gitignore` in the flutter repo. Details at https://github.com/flutter/flutter/pull/13002#issuecomment-350238151.

**Comment by xster** [comment]
I don't really know how it works, but as a complete hack, aren't all pub caches in some place like ~/.pub-cache? Perhaps apply the workaround to everything named `packages` outside that directory?

**Comment by DanTup** [comment]
@xster Sounds like a lot of effort; presumably I'd have to enumerate all the things in packages and see if they're all symlinks to the pub cache (which can be moved, and varies per platform).

Maybe I should just add a setting that can be set by users explicitly to apply it (I don't think it affects many - only Flutter + Fuchsia repos have reported it to me) until the analyzer is updated. It might man if anyone on the Flutter team is using Dart Code they want to commit a `.vscode\settings.json` though!

**Comment by xster** [comment]
Adding a line to settings.json seems fine to me as a quick and easy fix. Everyone should gitignore .vscode anyway

**Comment by DanTup** [comment]
Actually, I think committing `.vscode` isn't that unusual (for formatting, etc.). Though tbh, that would be preferable - I'd rather if another dev working on Flutter wanted to use Dart Code, they didn't need to figure out what's wrong and how to fix it - I think the setting is my fallback :(

I'll have a look at the packages folders in flutter/fuchsia and ones from `packages-dir` and see if I can find a reasonable way to guess which category a packages folder falls into (maybe with the option as an override in case we guess wrong). Some possible options:

1. Is the folder mostly symlinks?
2. Is the folder gitignore'd?

**Comment by DanTup** [comment]
I added a slightly better workaround - we now scan the `packages` folder and apply the workaround if it contains any real (non-symlink'd) folders.
