### ISSUE TITLE
Inlay hints for patterns

### ISSUE THREAD

**Issue by Zekfad** [Dart-Code/Dart-Code#4624]
**Is your feature request related to a problem? Please describe.**
It would be helpful to easily see (and navigate) to inferred types for patterns (switch, if-case, destructuring, etc.)
For now it's only possible to see inferred type from hover popup.

**Describe the solution you'd like**
Make inlay hints for patterns behave like for generics (like #4366)

**Describe alternatives you've considered**
Not really.

**Additional context**
Also inferred patterns are not navigable, in example hint `Box<int>` allows to navigate to `int`, but `Box<(int, int)>` both `int`s are not navigable.
And probably inferred single element pattern should be `(Type,)` instead of `(Type)`.

```dart
final class Box<T> {
  const Box(this.value);
  final T value;
}
void main() {
  {
    { // actual
      final (i, j) = (1, 2);
    }
    { // expected
      final (int i, int j) = (1, 2);
    }
  }
  {
    final pattern = (test: (10,), 2);
    { // actual
      if (pattern case final p) {}

      final (_, :test,) = pattern;

      final Null _switch = switch (pattern) {
        (:final test, var i) => null,
      };
    }
    { // expected
      if (pattern case final (int, {(int,) test}) p) {}

      final (_, :(int,) test,) = pattern;

      final Null _switch = switch (pattern) {
        (:final (int,) test, var /*int*/ i) => null,
      };
    }
  }
  {
    const simple = Box(2);
    const pattern = Box((1,2));

    { // actual
      if (simple case Box(:final value)) {}
      if (pattern case Box(:final value)) {}
      if (pattern case Box(value: final test)) {}
    }
    { // expected
      if (simple case Box<int>(:final int value)) {}
      if (pattern case Box<(int, int)>(:final (int, int) value)) {}
      if (pattern case Box<(int, int)>(value: final (int, int) test)) {}
    }
  }
}
```

<details>
<summary>Screenshot of current behavior</summary>

![image](https://github.com/Dart-Code/Dart-Code/assets/8970959/e8ca95db-2d2e-40b1-b864-21400a73d993)

</details>

**Comment by bwilkerson** [comment]
Yes, if we're displaying a record type with a single field, then I believe we should include a trailing comma because that's the syntax used by the language, and being consistent will be less confusing.

**Comment by DanTup** [comment]
Thanks!

The inlay hints changes landed in https://github.com/dart-lang/sdk/commit/08353751eae804838d2e94b89d948cb8ced1d57b. I've opened a CL for trailing commas at https://dart-review.googlesource.com/c/sdk/+/312421.

With both changes, the example above looks like this:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/087f388b-e4f9-4a10-a24d-1769269c91f4)

And the types within records are split up to support individual navigation:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/9506bdb3-2437-4b3c-9450-76e2c9415d3b)

**Comment by Zekfad** [comment]
That is great! Thank you for fast work, now it would be much easier to inspect pattern switches!

**Comment by DanTup** [comment]
np! I forgot to mention here (and it's not always obvious).. These changes are in the language server so they'll show up in an future SDK release (and not a Dart VS Code extension release).
