### ISSUE TITLE
For loop variable can't be renamed

### ISSUE THREAD

**Issue by lukehutch** [Dart-Code/Dart-Code#4626]
**Describe the bug**

Given the following code, placing the cursor by the first `x` and hitting F2 shows "The element can't be renamed".

Placing the cursor by the second `x` and hitting F2 allows the variable to be renamed.

```code
    for (final x in []) {
      print(x);
    }
```

**Please complete the following information:**
 - Operating System and version: Fedora Linux
 - VS Code version: 1.79.2
 - Dart extension version: 3.68.0
 - Dart/Flutter SDK version: Dart 3.0.5 / Flutter 3.10.5
 - Target device (if the issue relates to Flutter debugging): N/A

**Comment by DanTup** [comment]
This one has already been fixed via https://github.com/dart-lang/sdk/issues/52149 and should show up in the next SDK release.

**Comment by lukehutch** [comment]
Thanks, Dan!
