### ISSUE TITLE
Go to Definition jump to wrong place for first time

### ISSUE THREAD

**Issue by fehernyul** [Dart-Code/Dart-Code#4628]
**Describe the bug**
When I hover over a method/variable I want to find and press F12 (Go-To-Definition), VSCode successfully figures out which file contains the variable I'm looking for and opens it, but the cursor doesn't jump to specifically to position, but remains at the beginning of the file.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - Operating System and version: Windows 8.1
 - VS Code version: 1.79.2
 - Dart extension version:
 - Dart/Flutter SDK version: Dart 3.0.5/ Flutter 3.10.5
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
Are you able to capture a log file while reproducing this?

- Open a project
- Run the [**Dart: Capture Analysis Server Logs** command](https://dartcode.org/docs/logging/#capture-debugging-logs)
- Ctrl+Click to navigate to the wrong place
- Click **Cancel** on the logging notification to stop logging and open the log
- Remove anything sensitive from the log
- Attach the log here, in a [gist](https://gist.github.com/), or email to me at logs@dartcode.org.

Please also attach a screenshot of exactly where you were taken to in the file (taken for the same test as the log is captured for).

Thanks!
