### ISSUE TITLE
Wait for iOS device to be unlocked

### ISSUE THREAD

**Issue by simplenotezy** [Dart-Code/Dart-Code#4629]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have been waiting for my vs code extension to build my app so I can debug it (which sometimes takes minutes), only to come back to see that my iPhone went to lock screen as it does after some time of inactivity, and I have to restart the process and wait.

**Describe the solution you'd like**
VSCode should show up, even if in background, and show a prompt for me to unlock my iPhone, instead of simply stopping the whole process.

**Describe alternatives you've considered**
At least it should keep waiting for phone to be unlocked, or even better, prevent the phone from going to sleep when debugging have been started

**Additional context**
XCode have this feature, so I guess it should be somehow possible

**Comment by DanTup** [comment]
This would need to be handled by Flutter itself, as VS Code doesn't really know anything about the devices (Flutter abstracts everything away).

There's an existing issue tracking this at https://github.com/flutter/flutter/issues/34817 - please add your 👍 !
