### ISSUE TITLE
Cannot differentiate two devices of the same type in the device selector

### ISSUE THREAD

**Issue by vammex** [Dart-Code/Dart-Code#4632]
Type: <b>Bug</b>

i have two same phones. when i connect both to computer, vs code shows their names in "select device to use" and they are same. cannot understand what is what.
it is a name of phone model, so it cannot be fixed manually at the settings. it is a hardware phone name. 
vs code does not allow me to choose how, by which name i  want to see list of devices

Extension version: 3.66.0
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.68GB (8.59GB free)|
|Process Argv|--crash-reporter-id ed28006d-76f3-4ab1-ac8a-b9e18a52c2cc|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30776702
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
pythongtdpath:30769146
i26e3531:30780429
pythonnosm12tcf:30779713
pythonidxptcf:30772540
pythonnoceb:30776495

```

</details>

**Comment by DanTup** [comment]
Could you post the output of running `flutter devices --machine` in a terminal when both devices are connected? Thanks!

**Comment by vammex** [comment]
[
  {
    "name": "VNE AN00",
    "id": "A6QUCP2C05400813",
    "isSupported": true,
    "targetPlatform": "android-arm64",
    "emulator": false,
    "sdk": "Android 11 (API 30)",
    "capabilities": {
      "hotReload": true,
      "hotRestart": true,
      "screenshot": true,
      "fastStart": true,
      "flutterExit": true,
      "hardwareRendering": false,
      "startPaused": true
    }
  },
  {
    "name": "VNE AN00",
    "id": "A6QUCP2C26403181",
    "isSupported": true,
    "targetPlatform": "android-arm64",
    "emulator": false,
    "sdk": "Android 12 (API 31)",
    "capabilities": {
      "hotReload": true,
      "hotRestart": true,
      "screenshot": true,
      "fastStart": true,
      "flutterExit": true,
      "hardwareRendering": false,
      "startPaused": true
    }
  },
  ]
  
 their ID are different and android studio for example does show me a difference between two devices

**Comment by DanTup** [comment]
Is Android Studio just showing the raw ID (`A6QUCP2C26403181` and `A6QUCP2C05400813`)?  I think we should be able to include that here fairly easily.

**Comment by vammex** [comment]
> Is Android Studio just showing the raw ID (`A6QUCP2C26403181` and `A6QUCP2C05400813`)? I think we should be able to include that here fairly easily.

yes it may be enough. how to do it?

**Comment by DanTup** [comment]
I've made a change that will add the ID to the device selector like this.

### Before

![Screenshot 2023-07-04 151459](https://github.com/Dart-Code/Dart-Code/assets/1078012/4b311d9e-371c-4c18-88ec-2ef287ad0838)

### After

![Screenshot 2023-07-04 151436](https://github.com/Dart-Code/Dart-Code/assets/1078012/ce40a807-1876-4a3f-a5e4-e77747faff93)

Will this solve the issue for you?

**Comment by vammex** [comment]
> I've made a change that will add the ID to the device selector like this.
> 
> ### Before
> ![Screenshot 2023-07-04 151459](https://user-images.githubusercontent.com/1078012/250926873-4b311d9e-371c-4c18-88ec-2ef287ad0838.png)
> 
> ### After
> ![Screenshot 2023-07-04 151436](https://user-images.githubusercontent.com/1078012/250926894-ce40a807-1876-4a3f-a5e4-e77747faff93.png)
> 
> Will this solve the issue for you?

if it will look like VNE AN00 - A6QUCP2C05400813
it's good

**Comment by DanTup** [comment]
Yep! The brightest text will be "VNE AN00" (eg. where mine says "Mi A2"), and the ID "A6QUCP2C05400813" will be the first part of the next text (where mine says "33aa844").

**Comment by vammex** [comment]
> Yep! The brightest text will be "VNE AN00" (eg. where mine says "Mi A2"), and the ID "A6QUCP2C05400813" will be the first part of the next text (where mine says "33aa844").

I do not understand, you do not plan to tell me HOW to make it?

**Comment by vammex** [comment]
> The change is in the Dart extension code. I have made that change, but you will need a new version of the Dart extension to see it.
> 
> I will publish a pre-release version later this week, and you can switch to that if you would like to get the update before the next stable release.

oh you are the developer? I have not got it.
so please show me a screenshot with your real phone names details?

**Comment by DanTup** [comment]
Yes, I'm a developer on the Dart extension.

The image from above included my test phone - the name is "Mi A2" and the ID is "33aa844". Before the change, the ID was not shown, but now it is:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/97c5bef1-80b5-4f01-aed0-6b6e31c0516e)

I will push a pre-release version tomorrow and provide instructions so you can update and test it out.

**Comment by vammex** [comment]
> Yes, I'm a developer on the Dart extension.
> 
> The image from above included my test phone - the name is "Mi A2" and the ID is "33aa844". Before the change, the ID was not shown, but now it is:
> 
> ![image](https://user-images.githubusercontent.com/1078012/251219060-97c5bef1-80b5-4f01-aed0-6b6e31c0516e.png)
> 
> I will push a pre-release version tomorrow and provide instructions so you can update and test it out.

👍

**Comment by vammex** [comment]
version 38 is out. is there smth?

**Comment by DanTup** [comment]
> version 38 is out. is there smth?

I'm not sure what version 38 you're referring to. The current extension version is 3.68.

Anyway, I have published pre-release versions of the extensions. Please click the "Switch to Pre-Release" buttons for Dart + Flutter extensions and then click the "Reload" buttons once they have finished installing:

<img src="https://user-images.githubusercontent.com/1078012/155162164-d81940cb-9576-4468-8c03-a4bc2fd599c9.png" alt="Dart/Flutter pre-release versions" width="570" height="330" />

These include the updates, and you should be able to see the IDs in the device picker. Please let me know if this doesn't work for you.

Thanks!

**Comment by vammex** [comment]
![photo_2023-07-06_17-56-54](https://github.com/Dart-Code/Dart-Code/assets/19187347/997d7e77-1982-4fa6-9270-9f41170e2af1)
genius

right for now, it is good enough.
in future, will it be possible to set some name to devices? cannot figure out now which logic do i mean, whether vs code will remember commonly connected devices, or else to set a name every time after connecting

**Comment by DanTup** [comment]
> in future, will it be possible to set some name to devices?

Please file a new issue requesting this. If people add 👍 s and it seems useful to many, we could consider it. Thanks!

**Comment by vammex** [comment]
> > in future, will it be possible to set some name to devices?
> 
> Please file a new issue requesting this. If people add 👍 s and it seems useful to many, we could consider it. Thanks!

ok. oh i have been suffered this issue since February and I did not know I can just solve it that easy by writing an issue report )

**Comment by DanTup** [comment]
> I did not know I can just solve it that easy by writing an issue report )

It's not guaranteed everything raised gets fixed quickly, but things are definitely more likely to be addressed if they have been raised, because otherwise I might not know about the issues :-)

If you find bugs or have suggestions, _please do_ open issues!
