### ISSUE TITLE
Support global evaluation in SDK DAPs

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#4636]
In the old DAPs we supported some basic global evaluation using the root library and the first available isolate. We should support the same in the new SDK DAPs, but ideally use the current open file rather than the root library.

**Comment by jacob314** [comment]
What will it take to support evaluating in the context of the library of the currently open file and/or adding some affordance in the UI to select the library to use?

**Comment by DanTup** [comment]
> What will it take to support evaluating in the context of the library of the currently open file

That's actually what we do :) The comment above didn't mention it, but we pass through the active file in the `context` (it's non-standard, but all we have for now):

https://github.com/Dart-Code/Dart-Code/blob/7389b2c40b07b51e3deb2534074ed71a04c52965/src/extension/providers/debug_adapter_global_evaluation_context_factory.ts#L34-L39

And then in the debug adapter, we read this and find the relevant library for that script:

https://github.com/dart-lang/sdk/blob/80a6670d5d081bf6542036979791a8f666adfc1d/pkg/dds/lib/src/dap/adapters/dart.dart#L975

There's no UI to allow you to select, it just uses the current file. We could change this, although I don't know how nice the UI would be - but you can always open a specific file if you want to use that library.

What we don't support though is a way to choose the isolate.
