### ISSUE TITLE
[Vscode Flutter Plugin] don't think final and get are equivalent

### ISSUE THREAD

**Issue by au-top** [Dart-Code/Dart-Code#4643]
### Steps to reproduce

1. Create an abstract class
2. Abstract class has `abstract final GlobalKey widgetKey`
3. extends abstract class
4. use vscode flutter plugins quick fix code generate code `GlobalKey get widgetKey => throw  xxxx`

I don't think 'final' and 'get' are equivalent

The tool should generate a 'final' for '@override' instead of 'get'`

`get' is similar to 'function '

`abstract final 'is a variable in a block of memory space

### Expected results

generate `final GlobalKey widgetKey;`

### Actual results

 `GlobalKey get widgetKey => throw  xxxx`

**Please complete the following information:**
 - Operating System and version: Win10
 - Dart/Flutter SDK version: 3.10.5

**Comment by DanTup** [comment]
My understanding is that all field access goes through getters and setters, so from outside a class, a final field and a getter are indistinguishable. For example both of these are valid:

```dart
abstract class Foo {
  abstract final String foo;
}

class Bar extends Foo {
  @override
  final String foo = ''; // valid
}

class Baz extends Foo {
  @override
  String get foo => ''; // valid
}
```

@bwilkerson is this accurate? Are there any implications of using one over the other? (I notice you can declare the member as `abstract final String foo;` or `String get foo;` and assume they are equivalent, but I'm not certain and I couldn't spot these specifically mentioned in the spec).

**Comment by au-top** [comment]
check @DanTup 
```
abstract class Foo {
  abstract final GlobalKey foo;
}

class Bar extends Foo {
  @override
  final GlobalKey foo = ''; // valid
}

class Baz extends Foo {
  @override
  GlobalKey get foo => ''; // valid
}
```

**Comment by DanTup** [comment]
@au-top I'm not sure I understand what you're sample is showing, can you explain?

**Comment by bwilkerson** [comment]
I don't know what an abstract field is, so I'll defer to @eernstg, and probably learn something.

**Comment by au-top** [comment]
@DanTup 
```
class A{
  
  A(){
    print('create a New A');
  }
}

abstract class Foo {
  abstract final A foo;
}

class Bar extends Foo {
  @override
  final A foo = A(); // valid
}

class Baz extends Foo {
  @override
  A get foo => A(); // valid
}

void main() {
  final a=Bar();
  final b=Baz();
  
  
  print("this is a [final]");
  print([a.foo,1]);
  print([a.foo,2]);

  print("---");
  
  print("this is a [get]");
  print([b.foo,1]);
  print([b.foo,2]);
}

```


out

```

create a New A
this is a [final]
[Instance of 'A', 1]
[Instance of 'A', 2]
---
this is a [get]
create a New A
[Instance of 'A', 1]
create a New A
[Instance of 'A', 2]

```

**Comment by bwilkerson** [comment]
It is true that `final` and `get` are not the same. This is true whether the keyword `abstract` is present or absent.

The `final A foo = A();` is introducing a field with an initializer. The initializer is run once and the value is assigned to the field. Any access of the field returns that value assigned to the field.

The `A get foo => A();` is introducing a getter (a method with no arguments) with an expression body. The getter you wrote is equivalent to
```
A get foo {
  return A();
}
```

Every time the getter is invoked, the body of the getter is executed, resulting in the creation of a new instance of `A` on each invocation.

I was assuming that you understood this and that the question was about what the modifier `abstract` meant, but your second post caused me to question that assumption, hence the longer explanation.

But I think your real question is whether the fix ought to be creating a getter or a field when providing a concrete implementation of an `abstract` field. In order to answer that question I need to understand more about the semantics of an `abstract` field.

In any case, I don't think this issue is about the Dart-Code, but is instead a question about the analysis server that actually provides the fix, so it might be better to move the conversation to https://github.com/dart-lang/sdk, where Erik is more likely to see the `@` mention.

**Comment by eernstg** [comment]
(Sorry about the delayed response, I just came back from vacation ;-)

Abstract and external variables are specified here: https://github.com/dart-lang/language/blob/main/accepted/2.12/abstract-external-fields/feature-specification.md. This update was enabled in 2.12 together with the null safety updates, and it hasn't yet been integrated into the language specification.

The basic idea is that an abstract instance variable is just an abstract version of the corresponding non-abstract instance variable declaration: An `abstract final` declaration declares the implicitly induced getter with the usual return type, but abstract; an `abstract` declaration which is not `final` declares the getter as well, but also an abstract setter, with the usual parameter type. No storage is allocated in the object layout.

(Similarly, an `external` variable declaration is just an abbreviated form that declares the corresponding getter and, if not `final`, the corresponding setter as external. External variables can be top-level, static, or instance variables.)

There might be pragmatic reasons for treating `abstract final T x;` as somehow different from `T get x;` (e.g., a quick fix could generate different declarations when overriding each of those), but I don't see anything wrong with an approach where those two declarations are given exactly the same treatment. Similarly for `abstract T x;` vs. the pair `T get x;` and `set x(T t);`.

In that sense it's fair to say that an `abstract final` instance variable declaration and an abstract `get` instance declaration are equivalent.

@au-top wrote:
> Calling call will create a new object every time
>
> however
>
> Fianl will always use the first created object

It is true that the invocation of an instance getter (or any getter, but we're talking about `abstract` variables here, and they are always instance variables) will run the body every time, and a final instance variable with an initializer will evaluate that initializer when the enclosing object is created (if non-`late`) or when the implicitly induced getter is invoked for the first time (if `late`).

However, those behaviors are associated with getters: With the variable, it's the behavior of the implicitly induced getter, and with the explicitly declared getter it's the behavior of the explicitly written body. So this is a real distinction, but it is not a distinction between "final and get", it's a distinction between getters.

This matters when we consider overriding declarations: In relation to overriding relations and run-time behavior it does not matter whether a given getter was implicitly induced by a variable declaration or it was declared explicitly using the keyword `get`. In particular, it's perfectly well-defined and OK to override the getter of a `final` or non-`final` variable by a `get` declaration, and vice versa.

@bwilkerson wrote:
> But I think your real question is whether the fix ought to be creating a getter or a field when providing a concrete implementation of an abstract field.

That was my understanding as well. Couldn't we offer both, for any override of a getter?

**Comment by DanTup** [comment]
@eernstg thanks for the details!

> Couldn't we offer both, for any override of a getter?

There might be places where we could provide both of these options, but I think here the "Create missing overrides" fix was being used:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/ba071aea-fcb9-4cf8-87d4-ddb8a5bb01f4)

Since the action isn't specific to any individual field, I don't know if there's a nice way to describe multiple actions here. "Creating missing overrides using getters" and "Create missing overrides using variables" may work, but it might not be obvious why you have both of these options (since where the cursor is there isn't much context for what fields/getters there are).

**Comment by eernstg** [comment]
Sounds like it could make sense to let `abstract final T x;` be overridden by `final T x;`, `abstract T x;` by `T x;`, and `T get x;` by `T get x => throw xxxx;`, assuming that the abstract variable is commonly expected to be implemented as a variable.

(Or, if override inference is taken seriously, `T` could be omitted in all the overriding declarations.)

**Comment by bwilkerson** [comment]
For the "Create missing overrides" case, I think it would be reasonable to assume that if a user has declared an abstract field then it's probably more common to override it with a concrete field.

For the fix case, it seems reasonable to have both options (if we don't already).

**Comment by au-top** [comment]
> It is true that `final` and `get` are not the same. This is true whether the keyword `abstract` is present or absent.
> 
> The `final A foo = A();` is introducing a field with an initializer. The initializer is run once and the value is assigned to the field. Any access of the field returns that value assigned to the field.
> 
> The `A get foo => A();` is introducing a getter (a method with no arguments) with an expression body. The getter you wrote is equivalent to
> 
> ```
> A get foo {
>   return A();
> }
> ```
> 
> Every time the getter is invoked, the body of the getter is executed, resulting in the creation of a new instance of `A` on each invocation.
> 
> I was assuming that you understood this and that the question was about what the modifier `abstract` meant, but your second post caused me to question that assumption, hence the longer explanation.
> 
> But I think your real question is whether the fix ought to be creating a getter or a field when providing a concrete implementation of an `abstract` field. In order to answer that question I need to understand more about the semantics of an `abstract` field.
> 
> In any case, I don't think this issue is about the Dart-Code, but is instead a question about the analysis server that actually provides the fix, so it might be better to move the conversation to https://github.com/dart-lang/sdk, where Erik is more likely to see the `@` mention.

yes!  the is my question. 

about use code fix  should create `final or var` instead of  `get`

**Comment by DanTup** [comment]
Thanks for filing https://github.com/dart-lang/sdk/issues/53143, I'll close this in favour of that, since the work would be done in the SDK.

Thanks!
