### ISSUE TITLE
link detection do not work in debug console

### ISSUE THREAD

**Issue by altynbek132** [Dart-Code/Dart-Code#4647]
**Description**
In terminal and test results tab link detection works, but not in debug console

**Expected behavior**
Link detection should work same as in terminal

**Screenshots**

https://github.com/Dart-Code/Dart-Code/assets/48729942/b45a6621-1f98-4652-9ab7-84a9b7d5647a

**Please complete the following information:**
 - Operating System and version: windows 11, build: 22621.1848
 - VS Code version: 1.80.1
 - Dart extension version: v3.68.1
 - Dart/Flutter SDK version: 
Flutter 3.10.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 796c8ef792 (5 weeks ago) • 2023-06-13 15:51:02 -0700
Engine • revision 45f6e00911
Tools • Dart 3.0.5 • DevTools 2.23.1

**Comment by DanTup** [comment]
@altynbek132 did you resolve this?

**Comment by altynbek132** [comment]
@DanTup no, i think this issue refers to https://github.com/microsoft/vscode/issues/34026

**Comment by DanTup** [comment]
Ah yes, I think you're right. VS Code runs our own link providers for the terminal/output where we can map package: URIs. However it seems like it doesn't yet support that for Debug Console, so it only detects the obvious file: links that VS Code natively knows how to handle.
