### ISSUE TITLE
"find all references" on initializing formals only finds references to the field, not the constructor parameter

### ISSUE THREAD

**Issue by Dieterbe** [Dart-Code/Dart-Code#4649]
Hello!
Consider this code:
```
void main() {
  runApp(const MyApp());
  final p1 = Point(x: 1, y: 2);
  final p2 = Point2(x: 1, y: 2);
}

class Point {
  Point({num? x, num? y}) {
    this.x = x;
    this.y = y;
  }
  num? x, y;
}

class Point2 {
  Point2({this.x, this.y});
  num? x, y;
}
```
When you, find all references on the 'x' constructor parameter of class Point, you find the line where p1 is being created inside of main(). this is desired.

![image](https://github.com/Dart-Code/Dart-Code/assets/20774/bd7454b2-f566-4b94-97e2-ef52e891c1af)

However, when you use the "initializing formals" syntax, which is promoted by the plugin, and you find all references on the 'x' constructor parameter of the Point2 class, you no longer get the line where p2 is being created inside main().  You only see references to where the field is being used inside the class. This seems like a problem. See screenshot:

![image](https://github.com/Dart-Code/Dart-Code/assets/20774/4fa67509-4d20-4c65-8b04-da8e20ba9d90)

 - Operating System and version: arch linux (latest updates)
 - VS Code version: 1.79.2
 - Dart extension: Dart Code extension: 3.68.1, Flutter extension: 3.68.0 (not activated) 
 - Dart SDK version: 3.0.5 (stable) (Mon Jun 12 18:31:49 2023 +0000) on "linux_x64"
 - Flutter 3.10.5 • channel stable • ssh://git@github.com/flutter/flutter.git

Thank you for your consideration, and for a pretty great experience overall!

**Comment by DanTup** [comment]
Thanks for the report. This came up previously in https://github.com/Dart-Code/Dart-Code/issues/4535 and has been fixed. The fixed is in the language server, so it'll show up in a future Dart/Flutter SDK release.

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/d6058dc7-75d7-4827-8e36-dade34797c05)

Thanks!

**Comment by Dieterbe** [comment]
Cheers @DanTup have a great day!
