### ISSUE TITLE
Renaming dart files retains a copy of the old dart file

### ISSUE THREAD

**Issue by Cozmeh** [Dart-Code/Dart-Code#4653]
**Describe the bug**
So I got this warning "**the file name 'Example.dart' isn't a snake_case identifier**"
to keep everything clean I decided to change the file name, so I renamed it to '`example. dart`' but the file was still '`Example.dart`' so I renamed it again, and the changes got reflected.
But When I tried to change the constructor of a class that was being used in 2 different classes (dart files) the changes were only reflected in only one of the 2 classes 

**To Reproduce**
Not exactly sure how to reproduce it but, I found out about the issue later in the project 
This is what I did :
 * Added one extra `required this.something` in the constructor which was being used in 2 different classes
 * one file in which this was being used showed an error that the parameter is required 
 * but another file in which the same constructor was being used didn't show any error (which was odd)
 * After checking the code complete suggestions(ctrl+spacebar in vs code), I realised that 2 constructors exist in the same file with the same name but different parameters and when I clrl+click the 2 different constructors it takes me to the same location and also the file name jumps from '`example.dart`' to '`Example.dart`' depending upon which constructor I ctrl+click ,I am not sure what is happening.

**Expected behavior**
Im not really sure what is the expected behaviour 

**Screenshots**
NA

**Please complete the following information:**
 - Operating System and version: Windows 10 Pro 22H2
 - VS Code version: 1.80.1
 - Dart extension version: v3.68.1
 - Dart/Flutter SDK version: 3.10.5
 - Target device (if the issue relates to Flutter debugging): NA

**Comment by DanTup** [comment]
I believe this is the issue described in https://github.com/Dart-Code/Dart-Code/issues/3236.

When you rename a file by only casing, VS Code continues to use the old casing (https://github.com/microsoft/vscode/issues/121106) which causes problems. There's a setting you can enable to work around this:

```js
"dart.normalizeFileCasing": true,
```

There's a slight performance penalty to enabling this, because we have to verify the casing of files on-disk for each request.

Some users have also reported that renaming the file to something different (rename by more than just case), then restarting VS Code, and then renaming it back also fixes the issue, although I'm not sure that's 100% reliable.

Hope this helps!

**Comment by Cozmeh** [comment]
Thanks a lot!, but what exactly will be the performance penalty if I turn this setting on ?

**Comment by DanTup** [comment]
It requires that for each LSP request to the language server, we have to check the disk to see the casing of a file. It's probably such a small overhead you couldn't measure it, but I'm mentioning it just in case :-)

**Comment by Cozmeh** [comment]
Ahh, got it! I hope this gets resolved soon. Once again, thanks for reaching out!

**Comment by DanTup** [comment]
I'm not sure if there will ever be a proper fix here - VS Code seems reluctant to change this even though I think the current behaviour makes no sense. Running with this flag enabled shouldn't do any harm, but the other workaround posted above might allow you to fix this for specific instances without needing to enable the flag.

If VS Code does get updated, ofc I'll ensure things work correctly without needing either.

**Comment by Cozmeh** [comment]
> I'm not sure if there will ever be a proper fix here - VS Code seems reluctant to change this even though I think the current behaviour makes no sense. Running with this flag enabled shouldn't do any harm, but the other workaround posted above might allow you to fix this for specific instances without needing to enable the flag.
> 
> If VS Code does get updated, ofc I'll ensure things work correctly without needing either.

Yeah, I totally understand and agree that the current behaviour makes no sense, and also I'm not the only one who raised an issue upon this, so I guess a fix(default behaviour) will be helpful but again the workaround does the job...
also the snake_case thing, do we actually need that convention?
> sorry for stretching the conversation :)

**Comment by Cozmeh** [comment]
Got it, thank you very much!

**Comment by Cozmeh** [comment]
> This is a lint that you can turn on and off. I suspect you're getting it by default from the [Dart core lints](https://github.com/dart-lang/lints/blob/1e0245ea8ef8f702621eb7842ebd5342b1192c6b/lib/core.yaml#L20), but if you don't want it you could disable it via `analysis_options.yaml`.

Got it, thank you very much!

**Comment by sanba-anass** [comment]
ah it's so frasturating
