### ISSUE TITLE
flutter doctor -v error 

### ISSUE THREAD

**Issue by allanurbayramgeldiyev209** [Dart-Code/Dart-Code#4661]
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      _DefaultPub._runWithStdioInherited (package:flutter_tools/src/dart/pub.dart:447:7)
<asynchronous suspension>
#2      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:323:5)
<asynchronous suspension>
#3      PubDependencies.update (package:flutter_tools/src/flutter_cache.dart:126:5)
<asynchronous suspension>
#4      Cache.updateAll (package:flutter_tools/src/cache.dart:677:9)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1518:7)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>

**Comment by DanTup** [comment]
Also - is there any output above this? Looking at the code in https://github.com/flutter/flutter/blob/9690ef58cfe10f0282d78729de860eb0d21d6cf1/packages/flutter_tools/lib/src/dart/pub.dart#L777 there may be error messages printed above this stack trace.

**Comment by allanurbayramgeldiyev209** [comment]
Yes run manually on terminal

**Comment by allanurbayramgeldiyev209** [comment]
I'm not sure but the fault might be rosetta - danda

**Comment by DanTup** [comment]
Only inside the VS Code terminal, or also from an external terminal?

Can you post the full output, including anything that appears before `throwToolExit`?

**Comment by allanurbayramgeldiyev209** [comment]
Could this error be caused by rosetta - not fully uploaded?

**Comment by DanTup** [comment]
@allanurbayramgeldiyev209 this repository is for the VS Code extension so if this also occurs outside of VS Code, it would be better filed at https://github.com/flutter/flutter/.

That said, the code appears to write the error prior to the code you've posted, so if you file an issue there, please include the full output (or a screenshot of what you're seeing if you don't see any output before the error). Thanks!

**Comment by DanTup** [comment]
> Could this error be caused by rosetta - not fully uploaded?

I don't know - the original error message might help understand the cause.
