### ISSUE TITLE
Language server not currently working on Windows for latest Flutter master

### ISSUE THREAD

**Issue by snehilhbtu** [Dart-Code/Dart-Code#4662]
As soon as VS code starts , the output log shows error 
**[error] [Dart-Code.dart-code] provider FAILED
[error] Error: File is not being analyzed**
the extension even after being installed and uninstalled several times stays the same, i even installed VS code several times, after completely uninstalling and deleting _.vscode_ and _Code_ folder 

the extension and vscode are updated with dart and flutter already.
**flutter doctor shows no issue.**
the development is working fine with Android studio.

**Expected behavior**
i just want dart sdk to show error and suggestion, which is happening on other systems but not mine

**Screenshots**
i am adding screenshot of :-

1. flutter doctor
![fluter doctor](https://github.com/Dart-Code/Dart-Code/assets/139740986/611d9e23-bbce-4169-8089-0360be42509c)
2. local environment variables (flutter is installed in C:\flutter)
![env variables](https://github.com/Dart-Code/Dart-Code/assets/139740986/e5ddc0b5-e51d-4d27-98d6-9cef70ba43bc)
3. settings.json
![settings](https://github.com/Dart-Code/Dart-Code/assets/139740986/b835697c-00c0-417c-8ebf-7b26e8873626)
4. error log of extension
![dart error log](https://github.com/Dart-Code/Dart-Code/assets/139740986/45b40f36-0c29-4cfd-8ad6-718434a00702)

**Please complete the following information:**
 - Windows 10 22H2
 - VS Code version: 1.80.1
 - Dart extension version:3.68.1
 - Dart SDK version:3.1.0 (build 3.1.0-333.0.dev)
 - Flutter SDK version: 3.13.0-8.0.pre.33

**Comment by DanTup** [comment]
I believe you're hitting https://github.com/dart-lang/sdk/issues/53000. There was a bug on Windows that stopped the server starting up correctly. The issue has been fixed in the Dart SDK, but Dart SDK rolls into Flutter have been delayed due to other unrelated issues.

I expect a fix will land in Flutter master soon, but in the meantime you can use Stable or Beta, neither of which are affected by the issue.

**Comment by snehilhbtu** [comment]
yes i switched to stable version and its working

**Comment by DanTup** [comment]
FWIW the Dart->Flutter roll was unblocked and the fix has now landed in Flutter master :-)
