### ISSUE TITLE
Allow promptToRunPubGet to be disabled via setting

### ISSUE THREAD

**Issue by aamirki** [Dart-Code/Dart-Code#4663]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the promptToRunPubGet is shown and there is no way to disable it. Especially when just changing branches in my project I don't need this prompt to appear, it is just annoying that it covers part of my terminal until I close it.

**Describe the solution you'd like**
Add a setting to disable showing this prompt

**Additional context**
<img width="505" alt="Screenshot 2023-07-25 at 2 32 22 PM" src="https://github.com/Dart-Code/Dart-Code/assets/32246677/4f514746-268d-4fe7-b259-64579eb87521">

**Comment by DanTup** [comment]
There's an existing setting that I would expect to do what you want - have you tried changing this to "never"?

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/08924428-ea6e-4538-a319-64f5276bc165)

This should cover all cases where pubspec changes - although it may still leave the prompt when you first open the project. If you're seeing prompts when you open the project that you think are unwarranted, please run the **Dart: Open Extension Log** command after you see it, and the log should contain the reasons the extension thinks it needs to be run. If the check is not working correctly, I would prefer to fix the check than add a setting to just disable it.

Thanks!

**Comment by aamirki** [comment]
@DanTup Yes that seems to work! Thank you, I combed through the code and didn't see that
