### ISSUE TITLE
Debugging flutter web project with dart debugging extension in Chrome not possible

### ISSUE THREAD

**Issue by srmncnk** [Dart-Code/Dart-Code#4664]
**Describe the bug**
Debugging is not possible using an existing Chrome window and the Dart debug extension.

**To Reproduce**
1. flutter create test_web
2. flutter run -d web-server (use this in the launch.json and run with debugger)
3. put a breakpoint somewhere in main.dart
4. Everything stopps, then a message appears in console, saying "Debugger: Target crashed!", afterwards Chrome crashes

**Expected behavior**
A breakpoint is hit and you can debug your code.

**Screenshots**
![image](https://github.com/Dart-Code/Dart-Code/assets/25658970/40c414c4-7600-469f-968f-c859d45e812d)

**Please complete the following information:**
 - Operating System and version: Ubuntu 22.04
 - VS Code version: 1.80.1
 - Dart extension version: 1.34
 - Dart/Flutter SDK version: flutter 3.10.6
 - Target device (if the issue relates to Flutter debugging): web

**Comment by DanTup** [comment]
I don't seem to be able to reproduce this (at least on Windows - I don't have easy access to Linux, although I don't think that should matter). I tried both stable and master using both the legacy and SDK debug adapters:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/b1938f62-466d-482d-92c2-c0d9282efe98)

Is it possible you could capture a log while reproducing this that might help understand what's failing?

- Run the [**Dart: Capture Debugging Logs** command](https://dartcode.org/docs/logging/#capture-debugging-logs)
- Press `F5` to run the app and reproduce the issue
- Click **Cancel** on the logging notification to stop logging and open the log
- Remove anything sensitive from the log
- Attach the log here, in a [gist](https://gist.github.com/), or email to me at logs@dartcode.org.

Please reproduce in the newly created project so the logs don't contain anything sensitive and so I can test with the exact same project.

Thanks!

**Comment by DanTup** [comment]
Thanks! Unfortunately there's nothing obvious in the log. There are a few errors calling `_setStreamIncludePrivateMembers` and `_setStreamIncludePrivateMembers` but as far as I can see, these are both errors that can be expected and are handled/ignored.

@elliette have you seen this before? I recall you mentioning breakpoints crashing on a new version of Chrome - was that a stable release, and did the crash look like this? (I couldn't find an issue in https://github.com/dart-lang/webdev about that to compare with).

**Comment by elliette** [comment]
Hi @srmncnk  - are you on Chrome version 115? There is a regression in Chrome 115 where any Chrome extension using the `chrome.debugger` APIs to to pause an app will cause the app to crash. The Chrome team is working on a fix, in the meantime if you downgrade to Chrome 114 or 113 you should be able to debug your app. 

Sorry for the inconvenience, and I will report back here when there is a fix in Chrome.

**Comment by srmncnk** [comment]
@elliette I'm on: Version 115.0.5790.102 (Official Build) (64-bit)

Thanks for getting back to me and for the confirmation, I'll track it further and confirm when it is resolved. I figured it was something with Chrome as well. Do you happen to have a issue here this is being tracked? Many thanks.

**Comment by elliette** [comment]
There is a Chrome bug for this, but unfortunately it is Googler-restricted view only

**Comment by quyenvsp** [comment]
@srmncnk for me this seem fixed with Chrome 116.0.5845.97, can you confirm it?

**Comment by srmncnk** [comment]
@quyenvsp Can confirm, works like a charm!

BTW, had to manually update Chrome on my 22.04 though for whatever reason (was on Version 115.0.5790.102 (Official Build) (64-bit) before). Previously auto update always happened, not sure if relevant.

Closing, thanks for all the help. @DanTup @elliette

**Comment by DanTup** [comment]
Thanks for confirming Chrome 116 solved this.

> BTW, had to manually update Chrome on my 22.04 though for whatever reason (was on Version 115.0.5790.102 (Official Build) (64-bit) before). Previously auto update always happened, not sure if relevant.

I'm still only on 115 - I suspect it's just because [the rollout is gradual](https://chromereleases.googleblog.com/2023/08/stable-channel-update-for-desktop_15.html#:~:text=will%20roll%20out%20over%20the%20coming%20days/weeks).

**Comment by elliette** [comment]
Yes, the underlying issue has been fixed in Chrome 116 (currently rolling out to stable)

**Comment by FinestMaximus** [comment]
just dont run it as admin.. ie. `fvm flutter run -d chrome` and it works fine
`git config --global --add safe.directory $fvm_dir/version/xx` to make those runnable by non admins (if you installed it as admin)
