### ISSUE TITLE
The dart analyzer has terminated

### ISSUE THREAD

**Issue by MarsadMaqsood** [Dart-Code/Dart-Code#4666]
**Describe the bug**
The dart analyzer has terminated
The Dart analyzer stopped working in some cases
 - When adding certain keywords
 - When running an app on a physical device using wireless debugging

**To Reproduce**
1. Open Vs Code
2. Add the `const` keyword to the constructor and also return something [Code](https://github.com/MarsadMaqsood/stylish_bottom_bar/blob/f22b3239772c11b92069b0a105746782306adf48/lib/src/bottom_bar.dart#L59)

3. This also happens if you connect your device using wireless debugging and run the app (I tested on different flutter projects and every time it says dart analyzer ...)

**Expected behavior**
There should be a warning message, not the dart analyzer to stop working.

**Screenshots**
<details>
<summary>
Screenshot 1
</summary>

![SC 1](https://i.imgur.com/ycKdaPZ.png)
</details>

<details>
<summary>
Screenshot 2 (With Issue)
</summary>

![SC 2](https://i.imgur.com/Nd44Xjs.png)
</details>

**Please complete the following information:**
 - Operating System and version:
 - VS Code version: 1.80.1
 - Dart extension version: 3.68.1
 - Dart/Flutter SDK version: 3.10.6
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
Thanks for the excellent repro - I can trigger this on current stable:

```
[12:12:14 PM] [Analyzer] [Error] Unhandled exception:
Exception: Missing implementation of visitFunctionExpression
#0      ThrowingAstVisitor._throw (package:analyzer/dart/ast/visitor.dart:2842:5)
#1      ThrowingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:2514:58)
#2      FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6124:50)
#3      AstBinaryWriter._writeNodeList (package:analyzer/src/summary2/ast_binary_writer.dart:939:19)
#4      AstBinaryWriter.visitArgumentList …
```

**Comment by DanTup** [comment]
I was able to reduce this to:

```dart
class StylishBottomBar  {
  const StylishBottomBar({
    List<String?> items,
  }) : assert(items.every((String? item) => item != null));
}
```

It seems to be a Dart analyzer issue so I've moved this to https://github.com/dart-lang/sdk/issues/53075 and it'll be fixed (and ship) in a future Dart/Flutter SDK release.

Thanks!
