### ISSUE TITLE
`dart format` doesn't always indent correctly

### ISSUE THREAD

**Issue by lukehutch** [Dart-Code/Dart-Code#4669]
**Describe the bug**

VS Code formats the following code as:

```dart
    // Renumber higher-numbered images to have lower index
    final photos =
        await FileOwnership.find(session, where: (t) => t.id.equals(userId));
    await Future.wait(
      photos
          .where((row) =>
              row.profilePhotoIndex != null &&
              row.profilePhotoIndex! > profilePhotoIndex)
          .map(
        (row) {  // (*)
          row.profilePhotoIndex = row.profilePhotoIndex! - 1;
          return FileOwnership.update(session, row);
        },
      ),  // (**)
    );
```

The entire `(row) {...}` lambda marked `(*)` is two levels shallower in indentation than it should be.

Worse, the closing paren for `.map(...)`, marked `(**)`, is also two levels shallower than it should be.

**To Reproduce**

Try formatting the code above.

**Please complete the following information:**
 - Operating System and version: Linux
 - VS Code version: latest
 - Dart extension version: latest
 - Dart/Flutter SDK version: latest
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
Formatting is handled by [dart_style](https://github.com/dart-lang/dart_style) so any improvements would have to be made there.

I'm not certain, but it might be the same issue described at https://github.com/dart-lang/dart_style/issues/1175.

**Comment by lukehutch** [comment]
@DanTup thanks for directing me to `dart_style`, I wasn't sure what the formatter project was. And I think you found a couple of dups that explain the issue!
