### ISSUE TITLE
Debug console only reads first line of expression to be evaluated

### ISSUE THREAD

**Issue by miDeb** [Dart-Code/Dart-Code#4672]
**Describe the bug**
When writing an expression in the debug console that spans multiple lines (for example by copying in something from your code), only the first line is evaluated. This obviously causes an error if the first line alone is not a syntactically correct expression.

**To Reproduce**
1. Launch a flutter app (probably not related to flutter, but that's what I was running)
2. Open the debug console
3. Type an expression that spans multiple lines
e.g:
(1, fails)
```dart
1+
1
```
or
(2, prints `1`)
```dart
1
+
1
```

**Expected behavior**
The expression is evaluated as a whole, printing `2`.

**Please complete the following information:**
 - Operating System and version: windows
 - VS Code version: 1.80.2
 - Dart extension version: v3.70.0
 - Dart/Flutter SDK version: Dart SDK version: 3.0.6 (stable) (Tue Jul 11 18:49:07 2023 +0000) on "windows_x64"
 - Target device (if the issue relates to Flutter debugging): Probably irrelevant, was running on windows desktop (host machine)

**Comment by DanTup** [comment]
This is an issue with how Flutter compiles expressions - there's an open issue tracking this at https://github.com/flutter/flutter/issues/55731.

Once it's fixed in Flutter (and released), there shouldn't need to be any changes here, it should just start working.

Thanks!
