### ISSUE TITLE
`Dart: Open Observatory` not opening in VS Code for Flutter

### ISSUE THREAD

**Issue by hpelitebook745G2** [Dart-Code/Dart-Code#4679]
**Describe the bug**
When I run flutter run -d macos, both URLs below:
```
A Dart VM Service on macOS is available at: <URL>
The Flutter DevTools debugger and profiler on macOS is available at: <URL>
```

it opens to Performance tab by default:
<img width="1328" alt="258595792-7cf1ad19-5b96-4c8a-9a32-776efb285965" src="https://github.com/Dart-Code/Dart-Code/assets/27658429/78f8bec4-b553-4c32-b580-36ec36f8a2ae">

And in the Memory tab:
<img width="1325" alt="258595842-3b7df01e-aad5-4e7c-9deb-d70c6054ed2e" src="https://github.com/Dart-Code/Dart-Code/assets/27658429/df8069de-17fb-4974-8975-c7431780e0d4">

Currently, it doesn't have these 2 anymore:
1. current memory
2. peak memory

Is this not available in the latest Dart Devtools anymore? Where can I find the `current memory` and `peak memory`?

**To Reproduce:**
1. Create a new Flutter project
2. Run the app for Desktop or mobile, doesn't matter
3. In the VS Code, press cmd + shift + P and type Dart: Open Observatory and enter
<img width="512" alt="258595614-729e486d-1fd5-4d57-bf32-ca7096a2e618" src="https://github.com/Dart-Code/Dart-Code/assets/27658429/cb81c80d-b4b1-4abb-a6a7-988a004483a0">

4. Doesn't open or do anything

**Expected behavior**
I want to observe the memory consumption of my Flutter Desktop app.

I noticed that the older version of the Dart Devtools has this `Observatory Homepage`:
<img width="1312" alt="258595667-5a87f557-c4af-4703-9be2-0184a17c70d0" src="https://github.com/Dart-Code/Dart-Code/assets/27658429/e0396085-3e65-4c79-bc64-54626c15e84c">
I saw this from different Youtube - Flutter performance videos 1-3 years ago...

**Please complete the following information:**
 - Operating System and version: macOS 13.5 (22G74) Ventura
 - VS Code version: 1.80.2 (Universal)
 - Dart extension version: v3.70.0
 - Dart/Flutter SDK version: 

`
    
      Flutter 3.13.0-14.0.pre.6 • channel master • https://github.com/flutter/flutter.git
      Framework • revision 46f83ce636 (8 days ago) • 2023-07-30 22:31:35 -0400
      Engine • revision b84c936016
      Tools • Dart 3.2.0 (build 3.2.0-15.0.dev) • DevTools 2.25.0
`

 - Target device (if the issue relates to Flutter debugging): macOS (Darwin)

**Comment by DanTup** [comment]
Observatory is now disabled by default (see [this comment](https://github.com/dart-lang/sdk/issues/50233#issuecomment-1584848678)). You should be able to use `--serve-observatory` in `toolArgs` in your launch configuration to force it to be served - however be aware that this flag is only available temporarily and will eventually be removed.

If there are things that are missing from DevTools that were in Observatory, please file an issue at https://github.com/flutter/devtools/ (if there isn't already one tracking this). Thanks!
