### ISSUE TITLE
"The Dart Analyzer has terminated" at startup when Dart on PATH is a symlink

### ISSUE THREAD

**Issue by ts95** [Dart-Code/Dart-Code#468]
Suddenly out of the blue I started getting the "The Dart Analyzer has terminated. Save your changes then reload the project to resume." error in Visual Studio Code.
![image](https://user-images.githubusercontent.com/1880556/33799339-cd7639b0-dd29-11e7-91d4-eb9039bcdff7.png)

It appears whenever I open or type in a Dart file.

I've tried the following thus far:
* Reloading the project
* Reinstalling the Dart Code plugin
* Rebooting my computer
* Clearing the cache of VSC

And I still get the error

**Comment by DanTup** [comment]
Yikes, sorry about this. I have pushed out an update, but it shouldn't cause analyzer crashes. It does change the SDK search behaviour slightly though; so maybe it's picking a different SDK to usual?

Could you try clicking Help -> Toggle Developer Tools and see whether there's a full error/stack?

Also, could you confirm whether you've set any of the SDK override settings?

You could also try turning on analysis server logging (see [https://github.com/Dart-Code/Dart-Code/blob/master/CONTRIBUTING.md#enable-logging](here)). If the analyzer is starting correctly (I suspect not) then there might be useful logs there.

Also; can you confirm which OS you're on, and that you're on VS Code 1.18 and Dart Code 2.6.0?

**Comment by ts95** [comment]
macOS High Sierra 10.13.1
Visual Studio Code 1.18.1
Dart Code 2.6.0

![image](https://user-images.githubusercontent.com/1880556/33800396-65dba7ca-dd3f-11e7-85eb-57f193fcf62f.png)

I haven't set any SDK override settings.

I enabled `dart.analyzerLogFile` and this was the output I got:
```
[00:20:01]: ==> {"id":"1","method":"server.setSubscriptions","params":{"subscriptions":["STATUS"]}}
[00:20:01]: ==> {"id":"2","method":"analysis.setAnalysisRoots","params":{"included":["/Users/tonisucic/Web Projects/dart_playground"],"excluded":[]}}
[00:20:04]: ==> {"id":"3","method":"analysis.updateContent","params":{"files":{"/Users/tonisucic/Web Projects/dart_playground/main.dart":{"type":"add","content":"import 'package:jsonx/jsonx.dart';\n\nenum Format { ebook, paperback }\n\nclass Book extends Model {\n  String isbn;\n  String title;\n  List<String> authors;\n  Format format;\n  int year;\n\n  @override\n  String toString() {\n    return 'Book{title=$title}';\n  }\n}\n\nvoid main() {\n  final book = new Book()\n    ..isbn = '95-0443-843-0'\n    ..title = 'Do Androids Dream of Electric Sheep?'\n    ..authors = ['Philip K. Dick']\n    ..format = Format.paperback\n    ..year = 1968;\n\n  final json =\n      '{\"isbn\":\"95-0443-843-0\",\"title\":\"Do Androids Dream of Electric Sheep?\",\"authors\":[\"Philip K. Dick\"],\"format\":1,\"year\":1968}';\n}\n"}}}}
[00:20:04]: ==> {"id":"4","method":"edit.getFixes","params":{"file":"/Users/tonisucic/Web Projects/dart_playground/main.dart","offset":0}}
[00:20:04]: ==> {"id":"5","method":"edit.getAssists","params":{"file":"/Users/tonisucic/Web Projects/dart_playground/main.dart","offset":0,"length":0}}
[00:20:05]: ==> {"id":"6","method":"analysis.getHover","params":{"file":"/Users/tonisucic/Web Projects/dart_playground/main.dart","offset":433}}
[00:20:05]: ==> {"id":"7","method":"edit.getFixes","params":{"file":"/Users/tonisucic/Web Projects/dart_playground/main.dart","offset":614}}
[00:20:05]: ==> {"id":"8","method":"edit.getAssists","params":{"file":"/Users/tonisucic/Web Projects/dart_playground/main.dart","offset":614,"length":0}}
```

**Comment by DanTup** [comment]
The log suggests the analysis server definitely isn't starting correctly; as I'd expect to see something like this in the logs:

```text
[20:48:51]: <== {"event":"server.connected","params":{"version":"1.18.0","pid":446,"sessionId":""}}
```

Could you try starting the analyzer from a command line and see what happens? First locate where your dart exectuable is, eg:

```bash
> type dart
```

should output something like:

```text
dart is /Users/danny/Dev/dart/latest/bin/dart
```

Then run dart with a path to the analyzer snapshot (which lives in the snapshots folder alongside it):

```bash
> dart /Users/danny/Dev/dart/latest/bin/snapshots/analysis_server.dart.snapshot 
```

This should output something like:

```js
{"event":"server.connected","params":{"version":"1.18.0","pid":518,"sessionId":""}}
```

However, I suspect it might crash. If it does, then there might be something wrong with your SDK, and if it doesn't, then Dart Code must be calling it incorrectly.

Some other things to confirm:

- If you run `dart --version` what do you get?
- What is the path to your SDK (does it contain any spaces, symbols, etc.)

Thanks!

**Comment by ts95** [comment]
```
> type dart
dart is /usr/local/bin/dart
```

```
> dart /usr/local/bin/snapshots/analysis_server.dart.snapshot
Unhandled exception:
Could not load "file:///usr/local/bin/snapshots/analysis_server.dart.snapshot": FileSystemException: Cannot open file, path = '/usr/local/bin/snapshots/analysis_server.dart.snapshot' (OS Error: No such file or directory, errno = 2)
null
```

```
> dart --version
Dart VM version: 1.24.2 (Thu Jun 22 08:42:17 2017) on "macos_x64"
```
I installed the Dart SDK with `brew`. The SDK path is `/usr/local/opt/dart/libexec` where `/usr/local` is the brew prefix.

**Comment by DanTup** [comment]
Thanks for the info, I think I know what's happened. I guess `/usr/local/bin/dart` is a symlink and somewhere during the SDK Path changes in v2.6.0 we stopped resolving the symlink to its real path, which means we're looking in the wrong place for analyzer!

As a workaround, you might be able to set `dart.sdkPath` to the folder containing the SDK (without `bin` on the end) that reload.

I'll try and get a fix out today though. Apologies for the inconvenience! :(

**Comment by ts95** [comment]
Update: I found the `analysis_server.dart.snapshot` file.

![image](https://user-images.githubusercontent.com/1880556/33803894-a632ad90-dd9a-11e7-83e4-17dd7ffe4b9e.png)

```
> dart /usr/local/Cellar/dart/1.24.2/libexec/bin/snapshots/analysis_server.dart.snapshot
{"event":"server.connected","params":{"version":"1.18.0","pid":4154,"sessionId":""}}
```

**Comment by ts95** [comment]
Setting `dart.sdkPath` to the SDK path solved the issue. Thanks!

**Comment by DanTup** [comment]
@ts95 so setting `dart.sdkPath: "/usr/local/opt/dart/libexec"` in your Code user settings should fix things until the fix is out (will likely be this afternoon).

**Comment by DanTup** [comment]
Great! Thanks for the report; it's a silly but that will probably affect many, glad it was found and reported before the working week!

**Comment by Tygrak** [comment]
Happens to me on Linux too, thanks for finding the problem so fast! Workaround for now: set `dart.sdkPath` in vs code preferences to `/usr/lib/dart/` (or where `type dart` points to, without bin/dart at the end) - exactly as DanTup said.

**Comment by DanTup** [comment]
Turns out, I still had the symlink resolving code, but I had inadvertently made it run on the containing folder and not the executable!

v2.6.1 is live now and fixes this issue, as well as reporting a better message in the case where the analysis server is missing (rather than suggesting it terminated).

Please give it a try and let me know!

**Comment by ts95** [comment]
I just installed v2.6.1 and now it's working flawlessly 👏

**Comment by DanTup** [comment]
Excellent, thanks for letting me know (and taking time to report it)! 👍

**Comment by ptrwis** [comment]
I have the same problem now on Windows 7 (64bit). 
I set dart.sdkPath = "C:\\dart-sdk"

C:\dart-sdk\bin is on the system path

>dart --version
Dart VM version: 2.0.0-dev.30.0 (Thu Feb 22 14:08:47 2018 +0100) on "windows_x64"
(dart is also 64-bit version)

>dart analysis_server.dart.snapshot
{"event":"server.connected","params":{"version":"1.18.6","pid":8404,"sessionId":""}}

Dart Analyzer crashes all the time, immediately after starting and reloading the project.

Any ideas?

**Comment by DanTup** [comment]
@ptrwis This sounds like a different problem to me (since you've posted output from the analysis server, so it's definitely starting up).

Could you raise a new issue? Click Help -> Show Developer Tools and if there are any more detailed errors in there, please include them.

If Dart is on your path, you shouldn't need to set `dart.sdkPath` at all.
