### ISSUE TITLE
Test failures in tearDownAll are attributed to the correct line but wrong file

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#4681]
Moved from https://github.com/flutter/flutter/issues/131681. I thought this was just a request for https://github.com/dart-lang/test/issues/1851, however looking at the JSON we do get the location of the `tearDownAll` method, but we seem to record the line/col from that event in the file.

Here, "Go to Test" on "(tearDownAll)" is navigating to line 33 of the left file, instead of the right one. The test I ran was on line 26 of the left file.

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/8f157dd4-44ab-459c-902f-7b45a6ec9ac2)

The test event looks like:

```js
 {
	"test": {
		"id": 5,
		"name": "(tearDownAll)",
		"suiteID": 0,
		"groupIDs": [
			2
		],
		"metadata": {
			"skip": false,
			"skipReason": null
		},
///////////////////////////////////////// 👇 This info looks correct 
		"line": 33,
		"column": 3,
		"url": "file:///C:/Dev/Google/leak_tracker/pkgs/leak_tracker_flutter_test/test/tests/end_to_end/leak_tracking_config_test/flutter_test_config.dart"
	},
	"type": "testStart",
	"time": 1072
},
```

**Comment by DanTup** [comment]
With fix:

https://github.com/Dart-Code/Dart-Code/assets/1078012/ef151c10-2a38-4f5b-b7d2-9ed03c61e78c

**Comment by DanTup** [comment]
Turns out this will only work in Flutter because of [`testExecutable`](https://api.flutter.dev/flutter/flutter_test/flutter_test-library.html) because it allows the `setUpAll` and `tearDownAll` functions to be called without the test suite file in the stack.

If you trigger calling `setUpAll()` and `tearDownAll()` from inside the suite (as you'd need to without `testExecutable`) then `package:test` provides root locations that match the test file:

```
"line": 4,
"column": 3,
"url": "file:///C:/Dev/Test%20Projects/test_setup_diff_file/test/utils.dart",
"root_line": 7,
"root_column": 3,
"root_url": "file:///C:/Dev/Test%20Projects/test_setup_diff_file/test/test_setup_diff_file_test.dart"
```

I think we can handle this by special-casing these methods and looking at `line`/`col`/`url` for these "tests", although we currently have to do that based on the names. The reason we don't normally use these fields is that if a user calls a `test` wrapper (like `testWithWidgets`) we do want the call back from the main suite.

**Comment by DanTup** [comment]
We now treat setup/teardown specially and attribute them to their actual locations and not the call in the suite. This means a setup/teardown might be recorded against multiple suites in the tree - right-clicking on the icon will let you select which suite to jump to in the tree (seems VS Code already had good handling of this).

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/4b9a79c6-0349-4e22-ac74-7eec15afd6b9)

**Comment by polina-c** [comment]
thank you!!!! it is must have thing for leak_tracker, because analysis is happening in tearDownAll
