### ISSUE TITLE
Flutter Daemon Fails

### ISSUE THREAD

**Issue by marslanaras** [Dart-Code/Dart-Code#4683]
**Describe the bug**
The Flutter Daemon failed to start  ---->>> Source:Dart(Extensions)
I can not select or see any devices.  

**To Reproduce**
https://github.com/Dart-Code/Dart-Code/issues/4517
i checked this link but this link dosnt solve my problem

**Expected behavior**

**Screenshots**
<img width="1440" alt="Screenshot 2023-08-10 at 17 09 10" src="https://github.com/Dart-Code/Dart-Code/assets/116804893/68056ae5-ce58-4893-a998-e64966ae1be5">
<img width="1440" alt="Screenshot 2023-08-10 at 17 09 16" src="https://github.com/Dart-Code/Dart-Code/assets/116804893/cf801c3f-e793-4fce-a0e8-2cb51715b478">
<img width="1440" alt="Screenshot 2023-08-10 at 17 09 29" src="https://github.com/Dart-Code/Dart-Code/assets/116804893/a94443f2-c140-42d0-89cc-8e0b0c4b9e0e">
<img width="1440" alt="Screenshot 2023-08-10 at 17 09 35" src="https://github.com/Dart-Code/Dart-Code/assets/116804893/14143301-14ea-47f4-92b1-1a9d2247de21">
<img width="1440" alt="Screenshot 2023-08-10 at 17 09 40" src="https://github.com/Dart-Code/Dart-Code/assets/116804893/71a3f0a4-640e-4132-8b95-328f90e2dbe4">
<img width="1440" alt="Screenshot 2023-08-10 at 17 09 55" src="https://github.com/Dart-Code/Dart-Code/assets/116804893/c3c39b68-89f9-4a67-8fbe-0e6ba46419a7">
<img width="1440" alt="Screenshot 2023-08-10 at 17 09 59" src="https://github.com/Dart-Code/Dart-Code/assets/116804893/62d6b537-7185-4d44-969f-f5245e
<img width="1440" alt="Screenshot 2023-08-10 at 17 10 04" src="https://github.com/Dart-Code/Dart-Code/assets/116804893/a61299e4-cd3b-4012-a519-ab05aa9e5913">
f5c7a8">

**Please complete the following information:**
 - Operating System and version: macOS Ventura 13.4.1 macbook m1
 - VS Code version: (version 1.81.0)
 - Dart extension version:  i couldnt find it (i wrote dart--version in terminal, it doesnt give answer.  zsh: command not found: dart--version

 - Dart/Flutter SDK version:  v3.70.0
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
It appears there's something wrong with your `PATH` environment variable:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/4ddb72df-fa49-4bc7-9f89-77e602b9dc22)

There are a lot of system paths missing from here. Have you tried to add Flutter to your `PATH`? If so, can you describe how you did it and post any code you're using?

This could happen if you overwrote your PATH rather than appended to it, for example doing something like:

```
export PATH=/foo
```

instead of something like:

```
export PATH=$PATH:/foo
```

**Comment by marslanaras** [comment]
> It appears there's something wrong with your `PATH` environment variable:
> 
> ![image](https://user-images.githubusercontent.com/1078012/259785607-4ddb72df-fa49-4bc7-9f89-77e602b9dc22.png)
> 
> There are a lot of system paths missing from here. Have you tried to add Flutter to your `PATH`? If so, can you describe how you did it and post any code you're using?
> 
> This could happen if you overwrote your PATH rather than appended to it, for example doing something like:
> 
> ```
> export PATH=/foo
> ```
> 
> instead of something like:
> 
> ```
> export PATH=$PATH:/foo
> ```

I used this path.
export PATH="$PATH:/User/mehmedaras/FlutterDev/flutter/bin"


Also when i reopen terminal and type flutter doctor it does not give response.  zsh: no such file or directory: ...... says like that.  PATH=/bin:/usr/bin:/usr/local/bin:/sbin:${PATH}
export PATH
after i paste this and it works but everytime \curl -sSL https://get.rvm.io | bash -s stable

source ~/.rvm/scripts/rvm

rvm install 2.7.0
i paste this codes to for cocoapods.  It happens  whenever i close terminal

**Comment by DanTup** [comment]
What happens if you open your terminal and immediately run:

```
echo $PATH
```

?

**Comment by marslanaras** [comment]
Today, I think i delete path for flutter.  


<img width="565" alt="Screenshot 2023-08-11 at 19 42 11" src="https://github.com/Dart-Code/Dart-Code/assets/116804893/84d9bf17-ef7b-41b4-b46f-fd0dde87916a">

**Comment by DanTup** [comment]
So if you open VS Code (without running any other commands), do you still have the original problem, or does it work?

**Comment by marslanaras** [comment]
what do you mean about original problem. i did not try to open flutter today actually.
