### ISSUE TITLE
Ability to stop a debug session started with sudo

### ISSUE THREAD

**Issue by sschmitz41** [Dart-Code/Dart-Code#4687]
This is a follow-up to issue #4539.  I use a wrapper script in the customTool setting to launch a dart debug session with sudo (the app being launched is a long running service that normally runs as superuser).  The issue is that I cannot terminate the debug session (or similarly use Hot Reload).  Presumably, this is because VS Code is not running as superuser and therefore cannot kill a superuser process.  I have to manually hunt down the process ID and kill the process myself.

Would it be possible to add a complementary setting such as customKill to provide a 'sudo kill' wrapper?

Running VS Code as superuser doesn't seem like a great idea (if it would even work).

**Comment by DanTup** [comment]
>  The issue is that I cannot terminate the debug session (or similarly use Hot Reload). Presumably, this is because VS Code is not running as superuser and therefore cannot kill a superuser process.

When you terminate a debug session, initially we just send a message to the Flutter process asking it to quit. Similarly, Hot Reload is just another message.

Having a `customKill` doesn't feel like the right answer (and wouldn't affect hot reload) so I'd like to better understand what's failing here.

Can you describe exactly the steps you're taking and the behaviour you're seeing? (note: we will try to kill the process if you click Stop a second time, but you should only do that if the first stop doesn't work gracefully).

Could you also try capturing debugging logs while reproducing this?

- Run the [**Dart: Capture Debugging Logs** command](https://dartcode.org/docs/logging/#capture-debugging-logs)
- Try to stop the debug session
- Click **Cancel** on the logging notification to stop logging and open the log
- Remove anything sensitive from the log
- Attach the log here, in a [gist](https://gist.github.com/), or email to me at logs@dartcode.org.

Thanks!

**Comment by sschmitz41** [comment]
Sorry, I should clarify.  The debug session does stop when clicking the Stop button in VS Code.  However, the underlying process is still running after the debug session is stopped.  That is why I had the theory that whatever the method DartCode is using the kill the process, it is silently failing because it does not have superuser privileges.  I emailed a debug capture, Dart-Code-Log-2023-07-01 10-35-16.txt, that spans starting and stopping the debug session.  No mods were made to the log.

Note, the app is a service that spins up a long running web server.  I confirm the service is still running after the debug session is stopped by running 'sudo netstat -ltnup | grep <port_number>'  where port_number is where the web server is listening.  If I kill the process ID that is displayed, I can then start a new debug session.  Otherwise, exceptions will be thrown because the port number is still in use.

As you can see from the log, the customTool setting runs 'sudodart.sh'.  The contents of that script are simply:
#!/bin/bash
sudo dart $@

Interesting that you mention clicking the 'Stop' a second time.  A few months ago when I posted issue 4539 when debugging macOS, I was seeing that behavior...Pressing 'Stop' would perpetually display 'Terminating debug session...' and I could press Stop again to kill the debug session, but ultimately the underlying process would still be running.  Somewhere along the line, a VS Code and/or Dart Code update changed that behavior.  Pressing 'Stop' once always kills the debug session.  I'm seeing the same behavior on Linux which I transitioned to a couple weeks ago.

**Comment by DanTup** [comment]
> Interesting that you mention clicking the 'Stop' a second time. A few months ago when I posted issue 4539 when debugging macOS, I was seeing that behavior...Pressing 'Stop' would perpetually display 'Terminating debug session...' and I could press Stop again to kill the debug session, but ultimately the underlying process would still be running. Somewhere along the line, a VS Code and/or Dart Code update changed that behavior. Pressing 'Stop' once always kills the debug session. I'm seeing the same behavior on Linux which I transitioned to a couple weeks ago.

The original behaviour was that the first time you clicked Stop, VS Code sent a request to gracefully stop. If you clicked it again, it would send a "please terminate immediate" request (which could result in orphaned processes). This was very confusing to me (and others), and I think someone proposed changing the icon to make this clearer to users (although I'm not sure if that has shipped yet).

If you see the first click terminating and leaving orphaned processes (without any customTool), that definitely seems like a bug.


> The debug session does stop when clicking the Stop button in VS Code. However, the underlying process is still running after the debug session is stopped.

Can you clarify which process is still running? Are you able to make a small (but complete) repro you can share that triggers the issue that I can test with? (it's not clear to me exactly what your Dart app is doing, so some exact instructions I can follow to ensure I'm doing exactly the same would really help).

FWIW, in the log it appears that the process terminates normally after the initial `terminate` (graceful) request:

```
// This is the graceful request VS Code sends
[10:35:47 AM] [DAP] [Info] ==> {"command":"terminate","arguments":{"restart":false},"type":"request","seq":8}

// This confirms the debug adapter believes the process it spawned exited
[10:35:47 AM] [DAP] [Info] <== {"seq":173,"type":"event","body":{"output":"\nExited (-15)."},"event":"output"}
[10:35:47 AM] [DAP] [Info] <== {"seq":174,"type":"event","body":{},"event":"terminated"}

// This is a response to VS Code for the terminate request
[10:35:47 AM] [DAP] [Info] <== {"seq":175,"type":"response","command":"terminate","request_seq":8,"success":true}

// This is VS Code requesting a complete (non-graceful) termination.. although at this point, clean termination appears to have
// already happened, so it's a no-op
[10:35:47 AM] [DAP] [Info] ==> {"command":"disconnect","arguments":{"restart":false},"type":"request","seq":9}
[10:35:47 AM] [DAP] [Info] <== {"seq":176,"type":"response","command":"disconnect","request_seq":9,"success":true}
```

The terminate/disconnect terminology is very confusing, but `terminate` is a request to exit gracefully and `disconnect` is a request to immediately stop.

**Comment by sschmitz41** [comment]
I sent a test project to logs@dartcode.org.  Instructions are in the email to reproduce.

**Comment by sschmitz41** [comment]
The short answer is yes, but I had to evolve the script a bit.  The '$!' gives the process ID of sudo which is indeed what needs to be waited for.  However, there is a separate process for dart:main.dart where the web server is running.  So, instead of killing the sudo process, we need to kill the dart process.  My final script, which works on macOS and Linux is:

```
#!/bin/bash

_term() {
  echo "Terminating child process $CHILD"
  sudo kill -TERM "$CHILD" 2>/dev/null
}

trap _term SIGTERM

sudo dart $@ &
PARENT=$!
CHILD=

while [ "$CHILD" == "" ]; do
    CHILD=$(pgrep -P $PARENT | xargs)
done

echo "Waiting for parent process $PARENT with child $CHILD"
wait "$PARENT"
```

Thanks for all your help on this.

**Comment by DanTup** [comment]
Odd - the script seemed to work as-is for me. I am on MacOS though, I'm not sure if it differs at all on Linux. I won't pretend to understand the inner workings of this, but I'm glad you have a working solution anyway! :-)
