### ISSUE TITLE
flutter_tester processes not terminating on beta channel

### ISSUE THREAD

**Issue by tomgilder** [Dart-Code/Dart-Code#4690]
On the current Flutter beta channel (3.13.0-0.3.pre), flutter_tester processes aren't terminating when stopping debugging:

https://github.com/Dart-Code/Dart-Code/assets/756862/af55eb04-3b71-4026-8242-405863c50a56

This only happens when manually stopping debugging (it's fine if the test completes successfully).

This can result in a load of flutter_tester processes eating CPU if the process was doing something silly (not that my code ever would 😁).

Also happens on master. They correctly terminate on stable for me.

I'm assuming this is an issue in Flutter itself, but I don't know how to reproduce it through the CLI.

Flutter 3.13.0-0.3.pre
VSCode 1.81.1
DartCode 3.70.0,

**Comment by DanTup** [comment]
I think this is a Flutter issue - I can repro from the command line (at least here on Windows) by running:

```
flutter test .\test\widget_test.dart
```

and then hitting Ctrl+C and saying Yes to terminate. If I repeat this a few times, they keep building up (they don't always remain, seems to be if you terminate it in some specific window).

Do you want to re-file in flutter/flutter, or do you want me to?
