### ISSUE TITLE
Debugging (F5): cannot go beyond "Installing build\......\appdebug.apk..."

### ISSUE THREAD

**Issue by andynewman10** [Dart-Code/Dart-Code#4694]
**Describe the bug**

Visual Studio Code fails to start debugging a Flutter application when you press the debug button (or hit F5).

However the application is launched successfully when I issue `flutter run --verbose` on the command line.

I am using the following launch configuration (don't know if this matters):

```
        {
            "name": "Launch Flutter",
            "request": "launch",
            "type": "dart",
            "args": [
              "--dart-define",
              "MYAPI=https://www.something.com/nice/"
            ]
        },        

```

**To Reproduce**
1. Start Android 6.0.1 on a Samsung S5 Mini (SM-G800F) device, freshly reinstalled, without any installed extra application, with developer mode and USB debugging enabled and authorized (I confirm the device's name is displayed in the VS Code status bar).
2. Hit F5
3. The following text appears in the bottom right corner of VS Code:
```
Launching...
Running Gradle task 'assembleDebug'...
Installing build\......\appdebug.apk...
```
Meanwhile, the VS console shows:
```
Launching lib\main.dart on SM G800F in debug mode... (main.dart:1)
√  Built build\app\outputs\flutter-apk\app-debug.apk.
```
About 1 minute after this, I get a white screen on the phone, suggesting the application is being launched (?) and I get this in the console:
```
D/FlutterGeolocator(14167): Attaching Geolocator to activity
D/FlutterGeolocator(14167): Creating service.
D/FlutterGeolocator(14167): Binding to location service.
D/FlutterGeolocator(14167): Geolocator foreground service connected
D/FlutterGeolocator(14167): Initializing Geolocator services
D/FlutterGeolocator(14167): Flutter engine connected. Connected engine count 1
```
At that point, the phone's screen remains white forever and the situation doesn't change.

Under normal circumstances, eg. on my Xperia device, where F5 debugging behaves fine, the next console line is:
```
Connecting to VM Service at ws://127.0.0.1:50631/...
```
and the application starts normally.

❓Is there anything I could do to investigate this issue?

**Expected behavior**

Debugging should be able to start normally when pressing F5.

**Please complete the following information:**
 - Operating System and version: Windows 11 21H2 (22000.2295)
 - VS Code version: 1.81.1
 - Dart extension version: 3.70.0 (Flutter extension)
 - Dart/Flutter SDK version: 3.10.6 (also happens with 3.13.0)
 - Target device (if the issue relates to Flutter debugging): Samsung SM-G800F, Android 6.0.1, USB debugging

I have no problem whatsoever with another device, a Sony Xperia running Android 7.1.1.

**Comment by DanTup** [comment]
Can you confirm if this happens with only this project, or also if you create a new project with **Flutter: New Project**?

Then can you try capturing debugging logs while reproducing it (please use the new project if it reproduces there)?

- Run the [**Dart: Capture Debugging Logs** command](https://dartcode.org/docs/logging/#capture-debugging-logs)
- Reproduce the issue by trying to run the app
- Click **Cancel** on the logging notification to stop logging and open the log
- Remove anything sensitive from the log
- Attach the log here, in a [gist](https://gist.github.com/), or email to me at logs@dartcode.org.

Thanks!

**Comment by andynewman10** [comment]
Unfortunately Android 6.0.1 is the last OS version available for this device.

`flutter run --verbose` works fine.

I could finally tried on a Mac this afternoon, running Ventura 13.4.1, same setup, and it works. Weird.

**Comment by andynewman10** [comment]
On Windows, using the problematic device (Samsung S5 Mini SM-G800F), with the simple application that can be debugged fine, I always get the following error
```
Error connecting to the service protocol: failed to connect to http://127.0.0.1:57987/...
```
after 1 successful debug session, no matter what.
I have to reboot the device for the application to enter another debug session successfully.

On the Mac, I can run as many sessions as I want without rebooting the device.

**Comment by andynewman10** [comment]
> (I presume you see the same issue if you try to debug from Android Studio too? You may need to specifically Debug as just Running without debugging might not do quite the same things).

@DanTup Debugging from Android Studio works fine.

**Comment by DanTup** [comment]
> after 1 successful debug session, no matter what.
> I have to reboot the device for the application to enter another debug session successfully.
> On the Mac, I can run as many sessions as I want without rebooting the device.

How are you ending the debug session on Windows? If you close VS Code and re-open it, does that "fix" it? If not, after closing VS Code, are there any Dart or Flutter processes left around in task manager?

**Comment by DanTup** [comment]
@ShilpiSharmaJadaun can you provide more details? What device/Android version are you using? Could you also answer the questions at https://github.com/Dart-Code/Dart-Code/issues/4694#issuecomment-1697175149. Thanks!

**Comment by andynewman10** [comment]
I currently have another priority but I will get back with more information on this issue as soon as I can.

**Comment by andynewman10** [comment]
I resumed my testing, performed a factory reset of the G800F. Visual Studio Code 1.83, Flutter 3.13.6

When I start USB debugging, the following happens (I am not too worried about the first few lines, I assume Google+ is shut down by the OS to free up some memory):

```
Launching lib\main.dart on SM G800F in debug mode...
main.dart:1
E/AndroidRuntime(10499): FATAL EXCEPTION: IntentService[MandatorySyncService]
E/AndroidRuntime(10499): Process: com.google.android.apps.plus, PID: 10499
E/AndroidRuntime(10499): java.lang.NullPointerException: Attempt to read from field 'pvx pvv.b' on a null object reference
E/AndroidRuntime(10499): 	at kfe.a(PG:3143)
E/AndroidRuntime(10499): 	at ked.a(PG:359)
E/AndroidRuntime(10499): 	at kea.b(PG:531)
E/AndroidRuntime(10499): 	at kea.b(PG:215)
E/AndroidRuntime(10499): 	at kea.a(PG:188)
E/AndroidRuntime(10499): 	at com.google.android.apps.plus.service.EsSyncAdapterService.g(PG:481)
E/AndroidRuntime(10499): 	at com.google.android.apps.plus.service.EsSyncAdapterService$MandatorySyncService.onHandleIntent(PG:455)
E/AndroidRuntime(10499): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
E/AndroidRuntime(10499): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(10499): 	at android.os.Looper.loop(Looper.java:148)
E/AndroidRuntime(10499): 	at android.os.HandlerThread.run(HandlerThread.java:61)
√  Built build\app\outputs\flutter-apk\app-debug.apk.
D/FlutterGeolocator(17796): Attaching Geolocator to activity
D/FlutterGeolocator(17796): Creating service.
D/FlutterGeolocator(17796): Binding to location service.
D/FlutterGeolocator(17796): Geolocator foreground service connected
D/FlutterGeolocator(17796): Initializing Geolocator services
D/FlutterGeolocator(17796): Flutter engine connected. Connected engine count 1
```
At that point, things are completely stuck (30+ minutes waiting), however the flash screen of my Flutter app did show up (I use flutter_native_splash).
When I finally decide to press the stop button on the VS debug tool bar, the debugger does stop but the splash screen does not disappear on the device.
After manually closing the application, I can see the application icon.
If I attempt to start a new debug session, the same things happen.

Now, if I manually start the application from the device, without debugging, it starts OK.

**Comment by andynewman10** [comment]
If I do

Dart: Capture Debugging Logs

and start again, here is the tail of the log:

```
[   +9 ms] executing: C:\Users\andy\AppData\Local\Android\sdk\platform-tools\adb.exe -s 320410f6099051f1 shell am start -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x20000000 --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true --ez start-paused true com.XXXXX.application/com.XXXXX.application.MainActivity
[+2151 ms] Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x20000000 cmp=com.XXXXX.application/.MainActivity (has extras) }
[        ] Waiting for VM Service port to be available...
[+1055 ms] D/FlutterGeolocator(25496): Attaching Geolocator to activity
[ +547 ms] D/FlutterGeolocator(25496): Creating service.
[        ] D/FlutterGeolocator(25496): Binding to location service.
[ +196 ms] D/FlutterGeolocator(25496): Geolocator foreground service connected
[        ] D/FlutterGeolocator(25496): Initializing Geolocator services
[        ] D/FlutterGeolocator(25496): Flutter engine connected. Connected engine count 1
```
At this point, things are indefinitely waiting.

**Comment by andynewman10** [comment]
> How are you ending the debug session on Windows? If you close VS Code and re-open it, does that "fix" it? If not, after closing VS Code, are there any Dart or Flutter processes left around in task manager?

@DanTup I am debugging an application everyday on two devices (Android 7 and 13) and this never - ever - happens. Only with this device.

**Comment by andynewman10** [comment]
While the debugger is indefinitely waiting, if I close the application from the device side (this time), the debugger does not react to that. It would seem that somehow the device and the debugger are no longer connected.
Note that I am using the same cable as I'm using for my Android 7 device.

**Comment by andynewman10** [comment]
I am using Android Studio Electric Eel 2022.1.1.
When I go to Tools > SDK Manager > SDK Tools, it says I have Android SDK Build-Tools 34 Installed

adb.exe --help shows:

```
Android Debug Bridge version 1.0.41
Version 34.0.3-10161052
```

**Comment by andynewman10** [comment]
When trying to debug on Android Studio, today I'm getting:
```
10/11 22:39:48: Launching 'app' on samsung SM-G800F.
Timed out waiting for process (com.XXXXX.application) to appear on samsung-sm_g800f-320410f6099051f1.
```
This might be because my application is very big at the moment (~1GB) because of excessive bundled resources that I need for debugging purposes. (I had been waiting for 30 minutes earlier, could it be that USB software installation would be incredibly slow? I doubt it)

I can try upgrading Android Studio. Is Android Studio Giraffe supported by VS code (to perform debugging with)? I can try again later this week, with less resources.
I would like to avoid installing an unsupported Android Studio version and be on the safe side.

**Comment by DanTup** [comment]
Thanks for the additional info. Unfortunately I don't have many great ideas but it certainly sounds worth trying to remove some resources to see whether it's affected by the app size. If not, and since you can't repro this on a small sample app, it could be worth taking a copy of your app and stripping it down as much as possible and test as you go to see if you can find the trigger. If it happens in this app and doesn't happen in a small sample app, presumably somewhere along the route of making one of them the same as the other, you'd find the cause.

> Is Android Studio Giraffe supported by VS code (to perform debugging with)?
> I would like to avoid installing an unsupported Android Studio version and be on the safe side.

We don't depend on Android Studio directly in the VS Code extension, all of the Android stuff is abstracted by Flutter. So the real question here is whether Flutter supports that version of Android Studio (or more specifically, the Android SDK). I can't find it written anywhere, but I'm pretty sure Flutter always supports the latest stable versions of Android/SDK so this should be fine.

I'll update my copy though (I'm only on Flamingo) and have a quick test on the latest version of AS/Android SDK though.

**Comment by DanTup** [comment]
I upgrade to Giraffe and upgrade all the SDK bits to latest, created a new app with `flutter create` and verified I can run and debug it (multiple times) on a physical Android device (a Mi A2).

So while I don't know if it'll solve your issue, I certainly don't think it'll cause any additional compatibility issues :-)

**Comment by andynewman10** [comment]
Thanks for your investigation. I went all the way and upgraded the NDK to version 26, and Flutter as well since 3.13.7 was released today.

I have reduced the application size to ~100MB.

Still not working.

The VS code situation remains unchanged.

On the Android Studio Giraffe side, I get:

```
2023-10-12 17:57:05.322 13444-13444 ActivityThread          com.XXXX.application           W  Application com.XXXX.application is waiting for the debugger on port 8100...
2023-10-12 17:57:05.332 13444-13444 System.out              com.XXXX.application           I  Sending WAIT chunk
```
on the device side I get the splash screen, then a dialog is shown saying

```
title: "Waiting for the debugger".
body: "Application XXXX (process com.XXXX.application) is waiting for the debugger to attach"
Button: "Force close".
```
Like you, I think there is a package (maybe geolocator) disturbing the debugger. It indeed seems to be a Flutter bug to me, and I have to yet a workaround for it.

**Comment by DanTup** [comment]
Yep, I'd agree that seems mostly likely. If you're able to reproduce it in an app you can share (eg. by copying your project and removing everything sensitive and stripping it down to the minimum that still reproduces it), that would likely make it much easier to track down.

Unfortunately this is a bit out of my area of knowledge as Flutter abstracts all of the platform-specific stuff away from VS Code.

**Comment by andynewman10** [comment]
I understand, I am closing this bug, hopefully I'll find the courage sometime to file an issue on the Flutter repository.

**Comment by andynewman10** [comment]
Just a final quick message to write somewhere down the fact that I have also tried wireless debugging - just in case - and it produces the same result.

**Comment by DanTup** [comment]
@andynewman10 it's certainly worth trying. If it changes the behaviour that gives us an extra clue.

You define it in your VS Code user settings or workspace settings (eg. `.vscode/settings.json`) not the launch configuration.

> the value is `false` by default, right?

The default value is actually null/undefined, and which option you get depends on experiment (we're currently migrating people slowly). I can't tell which option you're getting from your log snippets above, but you could try both values or capture logs and search for "sdk dap" and it should log whether it's using the SDK DAPs (in which case you want to try setting `false` to disable that) or not (in which case you want to try setting `true` to enable them).

**Comment by DanTup** [comment]
Yeah, there will be some small differences between the two (the original adapter was written in TypeScript and the SDK one is a re-write in Dart) but hopefully nothing that would cause issues like this (since Flutter abstracts away this kind of thing, and all the code there is the same).

If you file a Flutter issue, feel free from CC me in case I can help troubleshoot (or avoid it being sent back here because it _seems_ like a VS Code-specific issue).
