### ISSUE TITLE
Clicking two "Accept incoming changes" within 1 second causes second change to fail

### ISSUE THREAD

**Issue by lukehutch** [Dart-Code/Dart-Code#4699]
**Describe the bug**

If you have two changes close together in your document, like this:

![image](https://github.com/Dart-Code/Dart-Code/assets/811305/6e0d2202-70ad-42f9-ac9f-0c42cab1152c)

and you click "Accept incoming changes" on both of them, less than 1 second apart, then the second change fails:

![image](https://github.com/Dart-Code/Dart-Code/assets/811305/e50860e7-3002-4380-91fe-61b2adb7e4f1)

**To Reproduce**
1. As described above

**Please complete the following information:**
 - Operating System and version: Fedora 38
 - VS Code version: code-1.81.1-1691620770.el7.x86_64
 - Dart extension version: latest
 - Dart/Flutter SDK version: 3.1.0
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
The merge codelens are all VS Code functionality and don't involve the VS Code extension - could you re-file this at https://github.com/microsoft/vscode?

Thanks!

**Comment by lukehutch** [comment]
Will do!

**Comment by lukehutch** [comment]
Filed at https://github.com/microsoft/vscode/issues/191038
