### ISSUE TITLE
dart.flutterSdkPath setting in vscode's settings.json is a user specific absolute path causing the file to become unsharable

### ISSUE THREAD

**Issue by Joren-Thijs-KasparSolutions** [Dart-Code/Dart-Code#4703]
**Is your feature request related to a problem? Please describe.**
I'm dissapointed that when i configure my chosen flutter sdk with vs-code it puts an absolute path in the settings.json file.
This causes this file to become unsharable across our team.

To illustrate some use cases where this becomes a problem:
- Our team is comprised of full-stack developers who do both flutter and backend work. Often times we put our app and backend for frontend code into one repository for simplicity. Extensions for backend code also put settings here, but these are not user specific and need to be shared.
- Cross platfrom development. I for example do flutter development on both Windows and MacOS so the start of the paths are not going to be compatible "/" vs "C:\\"

**Describe the solution you'd like**
I would like this setting to not be stored in a way that is user specific. I think there are multiple options to handle this, some are listed below with some being beter then others. A completely differnt solution is also acceptable. As long as it means i can check settings.json into git and use it across my team and across operating systems.

### Home Directory
You can make a soft rule that all flutter sdks need to be installed in the users home directory. Teams can then decide on a structure for example ~/flutter-sdks where the sdk's are stored like:
- ~/flutter-sdks/flutter-sdk-3.3.10
- ~/flutter-sdks/flutter-sdk-3.7.12
- ~/flutter-sdks/flutter-sdk-3.10.5

the settings.json file would then look like this
```json
{
"dart.flutterSdkPath" : "flutter-sdks"
}
```
Downside is that you become very limited on where you might want to store you sdks. Many people like to install them in the root of the file system for example.

### Only store sdk version
Only store the flutter sdk version you want to store in the settings.json. This way only the important thing is shared. It's the up to the user to provide VS-code with a path to his flutter sdks just like it is now. 

Possible downside is you don't want to store a absolute path in user settings either since these can be synced across devices and then you run into the Windows vs Mac issue again.
```json
{
"dart.flutterSdkVersion" : "3.7.12"
}
```

### Store the current setting in a different file
instead of saving 
```json
{
"dart.flutterSdkPath": "/Users/jorenthijs/Developer/tools/flutter-sdks/flutter_3.7.12"
}
```
in vs-code settings.json you could create a new .vs-code folder file that is meant to be user specific and that can then be added to .gitignore.
For example ".vs-code/dart-sdk-user-settings.json"

The only downside here being there will be no way to share a setting for which flutter version your app uses across your team.

**Describe alternatives you've considered**
I considered and tried third party solutions like [FVM](https://github.com/fluttertools/fvm) but these did not work properly and required to many workarounds.

**Additional context**
For additional context here is one of my current settings.json files from a repository that contains both flutter and C# code. As you can see the C# code extension also puts directory related settings in here but these are relative to the repository and thus work cross platform and cross team.
<img width="713" alt="image" src="https://github.com/Dart-Code/Dart-Code/assets/93926934/13708b46-65dd-4ada-8608-8c9697ab3c04">

**Comment by DanTup** [comment]
> You can make a soft rule that all flutter sdks need to be installed in the users home directory.
> ...
> the settings.json file would then look like this
> 
>   ```js
>   {
>   "dart.flutterSdkPath" : "flutter-sdks"
>   }
>   ```

You can do this today by using `~/flutter-sdk`. Both relative paths and using `~` to mean home dir are supported. You can use `/` as a path separator on both Windows and Mac.



> Store the current setting in a different file

If you only have one SDK, you can set it in `PATH` or your VS Code User Settings. If it needs to be project-specific, you could create a personal .code-workspace file (which you can store outside of the project) that contains user-specific settings. I do this so when working on DevTools I can use the local SDK version the project is pinned to without having to commit that setting to the repo (because other devs don't necessarily use it this way):

```js
{
	"folders": [
		{
			"path": "../devtools/packages"
		}
	],
	"settings": {
		"dart.flutterSdkPath": "../tool/flutter-sdk",
	}
}
```

I agree it would be nice if we could have user-specific workspace settings, but that needs to be implemented by VS Code. It would be very confusing for each extension to have a parallel settings file that doesn't show up in the VS Code settings UI/files/settings sync, etc. There's an open issue tracking that at https://github.com/microsoft/vscode/issues/40233.


FWIW in the last extension release there was a new setting added `dart.sdkSwitchingTarget` that lets you set the SDK switcher to change your User Setting instead of Workspace Setting which might suit you better depending on how you're using this.

Let me know if you don't feel any of these solutions will work (and if not, why). Thanks!

**Comment by Joren-Thijs-KasparSolutions** [comment]
Thanks for the comprehensive answer Dan! I'll take these options for a spin and see if they help. I've never used the VS-code workspace feature since i always just open the repository folder so i'm curious to try.

I'll try to keep you posted. if you don't hear back from me in two weeks feel free to close this issue👍

Thanks!

**Comment by Joren-Thijs-KasparSolutions** [comment]
Hey Dan quick followup:

I modified my vs-code settings to us the home directory instead of an absolute path
```json
"dart.flutterSdkPaths": [
    "~/Developer/tools/flutter-sdks"
  ],
```
I removed the current dart.flutterSdkPath entry from the projects settings .json
I then restarted VS-code but when i set my flutter sdk it still puts an absolute path insde settings.json.

Am i doing something wrong? I'm currently using MacOS.
![image](https://github.com/Dart-Code/Dart-Code/assets/93926934/4725f366-7930-4790-904c-3c4dd88fe82b)
![image](https://github.com/Dart-Code/Dart-Code/assets/93926934/25d4d6ce-5f5d-484f-a9a0-46318bcd5526)

**Comment by Joren-Thijs-KasparSolutions** [comment]
To be honest Dan i don't know what i want exactly😅. I've only been a flutter dev for the past 8 months. Comming from .NET where you install a set of fixed verion sdks and your project targets a fixed version. If you update a .NET project to a higher SDK everybody pulls that change in and either continues working with the new SDK or get an error telling them to go install the new sdk. Coming from that i'm still getting used to flutter and it's rolling release model. 

I guess what i want is for it to be easy to have different projects on my machine that target different flutter versions.
**use case:**
For example one is a greenfield project and can just be on the latest version. While another has been around for a while, has lots of packages and takes a while to update. 

And I want to either pin a project to a version and have that be part of the code. Or I want something like [NVM](https://github.com/nvm-sh/nvm) where I say what verion i'm using on my machine and the code and my coworkers feel 0 impact from it. There's a tool that tries to do this for flutter called [FVM](https://github.com/fluttertools/fvm) but it's not as elegant and requires workarounds that impact other team members that don't want to use it. But then these wishes are outside the scope of a VS-code plugin. Thanks for your help.

I'll have a look at your workspace idea since that does sound like the best option for now.

Thanks!

**Comment by DanTup** [comment]
> Comming from .NET where you install a set of fixed verion sdks and your project targets a fixed version. If you update a .NET project to a higher SDK everybody pulls that change in and either continues working with the new SDK or get an error telling them to go install the new sdk. Coming from that i'm still getting used to flutter and it's rolling release model.

Ah, thanks for the context - I understand this now. Unfortunately things are a little different here because unlike .NET where the versions are system-wide and fixed, with Flutter you could easily have multiple copies of the same version, or copies where the version number changes over time (if you're using `beta` or `master`, this will be common).

I think your idea of having your team all put versioned folders in the same folder relative to their home directory and using `~/flutter-sdks/v1.2.3` in the `dart.flutterSdkPath` setting could be a good route - and we just need to update the extension to support writing home-directory-relative paths into that setting instead of always absolute paths. It's not a big change so I can make that change if that works for you.

`.code-workspace` files may work too, but it means each person on the team would have their own file (usually stored outside of the repo), and if one of you changes the version it wouldn't change for others. It sounds like that might not be what you want?

**Comment by Joren-Thijs-KasparSolutions** [comment]
Hi Dan

I think updating the VS-code plugin to write home dirtectory based paths (when a home directory relative path is configured) on both Windows, Mac and Linux would be a good improvement. And indeed enable a somewhat familiar workflow for cross functional teams who come from a .NET/Java background. It would also alow me to check the settings.json file back into git😃

I haven't had time to look into the workspace idea yet🫤

**Comment by DanTup** [comment]
I've opened https://github.com/Dart-Code/Dart-Code/issues/4708 to track doing that specifically.

**Comment by DanTup** [comment]
@Joren-Thijs-KasparSolutions the fix I made for https://github.com/Dart-Code/Dart-Code/issues/4708 has shipped in the extension - we'll no longer write absolute paths when it's inside your homedir.

Please let me know if that solves your entire problem, or if you still think there are things to look at here. Thanks!

**Comment by Joren-Thijs-KasparSolutions** [comment]
Hey Dan

I have the updated extension (v3.72.0) installed which according to the [changelog](https://dartcode.org/releases/v3-72/) should contain the change. But when i change my home directory it is not writing a ~ into the path. I also double checked that the setting for my sdk folder contains a ~.
(I manually checked for updates, and fully rebooted VS-Code)

Am i missing something? I'm using an M2 Macbook.

Screenshots:
<img width="971" alt="image" src="https://github.com/Dart-Code/Dart-Code/assets/93926934/5e7f7a46-8ca4-4708-9f1c-c961ac97eae0">
<img width="613" alt="image" src="https://github.com/Dart-Code/Dart-Code/assets/93926934/65c8ff70-67d0-487b-a4cb-ffa7decb5c62">
<img width="714" alt="image" src="https://github.com/Dart-Code/Dart-Code/assets/93926934/7dcbf4c2-8506-4e42-b215-5d2ab407106d">
<img width="274" alt="image" src="https://github.com/Dart-Code/Dart-Code/assets/93926934/94b6bb52-8507-4970-a0b2-5e1091e9977b">

**Comment by Joren-Thijs-KasparSolutions** [comment]
Hi Dan

I tried the prerelease version of the Dart extension and it works now👍
![image](https://github.com/Dart-Code/Dart-Code/assets/93926934/4be76cf0-83cd-48c3-9405-1823a38264ad)


Thank you!

**Comment by DanTup** [comment]
Great, sorry for the bother.

Does this solve all your issues? Shall I close this one as resolved by https://github.com/Dart-Code/Dart-Code/issues/4708?

**Comment by Joren-Thijs-KasparSolutions** [comment]
Yes you may close this issue. Thank you for all your help and advice!

**Comment by DanTup** [comment]
No problem - please do file additional issues of other things come up. Thanks!
