### ISSUE TITLE
Expose a minimals APIs for `readFile`, `writeFile`, and `listDirectories`

### ISSUE THREAD

**Issue by kenzieschmoll** [Dart-Code/Dart-Code#4704]
We will need to be careful that these APIs are not overwhelmed by requests or asked to read / write huge files since that would overload the Dart-Code extension with synchronous file access.

@DanTup please feel free to add any other considerations that we should be aware of or that we discussed earlier.

CC @vlidholt, since this request spawned from our conversation around DevTools extensions. In your `serverpod` developer tool, what is the size of the files that you are reading / writing currently using `dart:io`?

**Comment by DanTup** [comment]
> `listDirectories`

Is the goal here to list directories of another directory, or to list all children (including files) of a directory?

It would be useful to understand the intended use case a bit more - for example if it's being used to search a tree for files, would it be better by doing the search in the extension instead and returning a set of matching files?

**Comment by kenzieschmoll** [comment]
> Is the goal here to list directories of another directory, or to list all children (including files) of a directory?
>
> It would be useful to understand the intended use case a bit more - for example if it's being used to search a tree for files, would it be better by doing the search in the extension instead and returning a set of matching files?

@vlidholt, would you mind adding some info with your use cases for these File IO apis? Thanks!

**Comment by vlidholt** [comment]
@kenzieschmoll Sorry, I saw this justnow. The files we are reading and writing are small. I'd say less than 100kb.

@DanTup Our use case is to be able to read and write configuration files and passwords. In our Serverpod tooling we need to connect to the live server and need to know how to do so. We are also handling database migrations, which require us to read and write protocol files and sql code from the server project.

**Comment by kenzieschmoll** [comment]
There is a design under review to expose these APIs from the Dart Tooling Daemon when it ships: [flutter.dev/go/file-system-access-from-devtools](http://flutter.dev/go/file-system-access-from-devtools)

**Comment by DanTup** [comment]
@kenzieschmoll are Dart-Code APIs still required here, or is the plan to do this in Dart/DTD via the disk now?

**Comment by kenzieschmoll** [comment]
We can close this, as this is proceeded by the DTD-based API
