### ISSUE TITLE
Add logic for VS code to promote other VS code extensions 

### ISSUE THREAD

**Issue by kenzieschmoll** [Dart-Code/Dart-Code#4705]
As part of the broader effort to support dart ecosystem extensions, we've designed a mechanism for a pub package to provide extension information as part of its package. For DevTools, this is the precompiled flutter web app that DevTools will embed. For VS Code extensions, the pub package can include a `config.yaml` file that tells the Dart-Code promotion which extension should be promoted:
```
my_package/
   lib/
      ...
   extension/
      vs_code/
          # contains meta data that VS code needs to point to another
          # extension on the VS code marketplace
         config.yaml
```

[package:extension_discovery](https://pub.dev/packages/extension_discovery) has logic to detect available extensions for a given `.dart_tool/package_config.json` file. Since this package is written in Dart, it cannot be used by the Dart-Code extension directly, so it will need to be called into from the Dart-Code extension by proxy of some other Dart service. Eventually, this would be a great fit for the [Dart Tooling Daemon](https://docs.google.com/document/d/1qJNwgg1e_4KzY_fSU3rmSj9CXqtpGC5GmQb0cXkUGfo/edit), but since this does not exist yet, we can use the DevTools server in the interim.

We can add an API to DevTools server that the Dart-Code extension can call, and the devtools_server will call `findExtensions('vs_code', <path/to/package_config.json>)` from [package:extension_discovery](https://pub.dev/packages/extension_discovery) on the Dart-Code extension's behalf.

**Open Question**
The element we still need to figure out is how to handle a monorepo workspace, where there are multiple `package_config.json` files available. 

Related: [Flutter DevTools Extensions](https://docs.google.com/document/d/189A-T-pcHPuds8pOtbzLS8Wl6Hr0AIAIl0aRTPvLKec/edit)

**Comment by DanTup** [comment]
@anderdobo @mosuem FYI - I wonder whether there's value in trying to use this for arb-editor (eg. have the Flutter/intl packages provide the recommendation)? It might need something extra (only show the recommendation if an arb file is opened?), but it might work out better than special handling for one extension?

**Comment by mosuem** [comment]
To recap an offline discussion: We will go with implementing the suggestion the extension itself for now, see https://github.com/Dart-Code/Dart-Code/issues/4719. We will possibly migrate to using this new feature. At the moment, the lack of a file filter ("only show the recommendation on opening `.arb` files") would result in too much noise for Flutter users.

**Comment by DanTup** [comment]
I made a start on this at https://github.com/Dart-Code/Dart-Code/pull/4847 (and some SDK work in the DevTools server that needs tests before uploading).

@kenzieschmoll @anderdobo Jacob asked me today whether this includes transitive dependencies or only direct dependencies. It's using [package:extension_discovery](https://pub.dev/packages/extension_discovery) which I think reads the `.dart_tool/package_config.json` and might therefore include transitive dependencies -although I'm not sure whether that's the behaviour we want?

**Comment by kenzieschmoll** [comment]
Right now, `package:extension_discovery` includes transitive dependencies. @jonasf if I remember correctly, there is not currently a way to distinguish between transitive and direct deps based on the `package_config.json` file, right? 

If we did only want to include direct dependencies, I think this would be easy to do by modifying the `extension_discovery` package so that it has a parameter `includeTransitiveDependencies`, and when false, it could only return extensions whose parent package has an entry in the `pubspec.yaml` file at the project root that is passed in to the `findExtensions` method.

**Comment by DanTup** [comment]
@anderdobo @jacob314 are you happy with how this displays in [my current PR](https://github.com/Dart-Code/Dart-Code/pull/4847)?

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/ce9f7f64-ef91-4844-9a55-0ae7dbcac130)

In particular, we need to be sure the user is aware they are installing third-party code that is not owned/reviewed by the Flutter team.

@kenzieschmoll @jacob314

1. we discussed using a whitelist for initial testing of this. Do we have any extensions in mind, or should we land this with an empty whitelist?
2. did we conclude whether or not we're happy for this to look all (inc. transitive) dependencies, or do we need to update extension_discovery to handle only top-level dependencies (and if so, should it be only `dependencies` or also `dev_dependencies`?)

**Comment by kenzieschmoll** [comment]
> 1. we discussed using a whitelist for initial testing of this. Do we have any extensions in mind, or should we land this with an empty whitelist?

`serverpod` is a good first candidate. What do you need for the whitelist? just the package name? @vidholt can you confirm that `serverpod` is the correct serverpod package that you would like to promote your VS code extension from?

> 2. Did we conclude whether or not we're happy for this to look all (inc. transitive) dependencies, or do we need to update extension_discovery to handle only top-level dependencies (and if so, should it be only dependencies or also dev_dependencies?)

Since we are using a whitelist for now, I think that including transitive deps is okay. I do think we should update `extension_discovery` package to take a parameter `includeTransitive` in the `findExtensions` method though. (CC @jonasfj). We do want to include dev dependencies, IMO. For example, someone may provide a package solely for developer tooling (this package could contain a devtools extension and may promote a paired vs code extension too).

**Comment by DanTup** [comment]
>  What do you need for the whitelist? just the package name

I guess we could do it either by package name or extension identifier. There's probably not a lot of difference. If we have the right package name(s) I'll use them.

**Comment by kenzieschmoll** [comment]
Extension identifier might be better since the package could arbitrarily change the VS code extension it is asking to promote, and then we really don't have control over the VS code extension whitelist.

**Comment by jonasfj** [comment]
I think we can let findExtensions return a field indicating whether it's a direct or transitive dependency.

Please file an issue on repository, then let's discuss that separately.

Correct: the information is not in package_config.json, so we'll need to read pubspec.yaml

**Comment by anderdobo** [comment]
> @anderdobo @jacob314 are you happy with how this displays in [my current PR](https://github.com/Dart-Code/Dart-Code/pull/4847)?
> 
> ![image](https://private-user-images.githubusercontent.com/1078012/287778690-ce9f7f64-ef91-4844-9a55-0ae7dbcac130.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MjAzNjksIm5iZiI6MTcwMTcyMDA2OSwicGF0aCI6Ii8xMDc4MDEyLzI4Nzc3ODY5MC1jZTlmN2Y2NC1lZjkxLTQ4NDQtOWE1NS0wYWU3ZGJjYWMxMzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDRUMjAwMTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzdmM2I4ZjEzNjVhZjJjZjAyOTFkNGZlNTg0MTRlZTE3ZDZiZDhjYWNhOWJjYjEwY2I1ZGJiZTk5OGViNDc3MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Z7Z7zw-jxszrFtHRF7YwXaOchH-Qnw_RgPjuRjSvT5s)
> 
> In particular, we need to be sure the user is aware they are installing third-party code that is not owned/reviewed by the Flutter team.
> 
> @kenzieschmoll @jacob314
> 
> 1. we discussed using a whitelist for initial testing of this. Do we have any extensions in mind, or should we land this with an empty whitelist?
> 2. did we conclude whether or not we're happy for this to look all (inc. transitive) dependencies, or do we need to update extension_discovery to handle only top-level dependencies (and if so, should it be only `dependencies` or also `dev_dependencies`?)

@DanTup the notification and language LGTM. Is this ready to be used to promote [ARB Editor](https://marketplace.visualstudio.com/items?itemName=Google.arb-editor)? If so, we should.

**Comment by DanTup** [comment]
> Is this ready to be used to promote [ARB Editor](https://marketplace.visualstudio.com/items?itemName=Google.arb-editor)? If so, we should.

I think we'll have a different codepath for the ARB editor because it won't be driven by a package (but rather opening arb files), but I do plan to look at that shortly too (there's an issue at https://github.com/Dart-Code/Dart-Code/issues/4719 tracking that).

**Comment by jacob314** [comment]
LGTM as long as the initial whitelisted packages aren't ones where the transitive dependency case is a concern. I'm not concerned about Serverpod as odds of it only being a transitive dependency seem very low (why are your dependencies using serverpod if you aren't running serverpod?).
On the other hand, you really wouldn't want to show Freezed (e.g. you depend on a package that is using Freezed for its internal serialization but you have no idea what it is) unless they were direct dependencies because none or your app is using the functionality.
