### ISSUE TITLE
Inlay hints for nested patterns

### ISSUE THREAD

**Issue by Zekfad** [Dart-Code/Dart-Code#4712]
**Is your feature request related to a problem? Please describe.**
It would be helpful to easily see (and navigate) to inferred types for nested patterns (switch, if-case, destructuring, etc.)
For now it's only possible to navigate to most inner inferred type.

**Describe the solution you'd like**
Make inlay hints for nested patterns behave like for generics (like #4366)

**Describe alternatives you've considered**
Not really.

**Additional context**
Addition to #4624

```dart
final class Box<T> {
  const Box(this.value);
  final T value;
}
void main() {
  {
    const boxedBox = Box(Box((1,2)));
    const boxedList = Box([1,2]);

    { // actual (notice that inner pattern is augmented correctly)
      if (boxedBox case Box(value: Box(:final (int, int) value))) {}
      if (boxedList case Box(value: List(:final int length)) when length > 0) {}
    }
    { // expected
      if (boxedBox case Box<Box<(int, int)>>(value: Box<(int, int)>(:final (int, int) value))) {}
      if (boxedList case Box<List<int>>(value: List<int>(:final int length)) when length > 0) {}
    }
  }
}

```

**Comment by DanTup** [comment]
@Zekfad I'm not sure I understand the code sample (specifically, which parts of the code are intended to be code, and which parts are intended to be hints). I don't see any hints in either the "actual" or "expected" code because they already have explicit types.

Could you provide the code where you want to see hints _without_ the hints (or with the hints in comments) so I can understand what you'd like? Thanks!

**Comment by Zekfad** [comment]
Thank you for response, I'll clarify:
in this line:
```dart
if (boxedBox case Box(value: Box(:final (int, int) value))) {}
```
First `Box` and second `Box` should be augmented like so (`Box<Box<(int, int)>>` and `Box<(int, int)>` respectively):
```dart
if (boxedBox case Box<Box<(int, int)>>(value: Box<(int, int)>(:final (int, int) value))) {}
```

Same for `Box` and `List` pairs from the 2nd line of examples.

**Comment by DanTup** [comment]
Oh gotcha, thanks!

**Comment by Zekfad** [comment]
Thank you for your work, these hits makes it really easy to play aground switch cases!

**Comment by DanTup** [comment]
Working on a fix at https://dart-review.googlesource.com/c/sdk/+/332960. With the fix looks like this:

![Screenshot 2023-10-31 104940](https://github.com/Dart-Code/Dart-Code/assets/1078012/342eed96-7bde-45e1-9b3c-e696f9356aea)

![Screenshot 2023-10-31 104954](https://github.com/Dart-Code/Dart-Code/assets/1078012/1fc7d990-56b7-4e0c-8c11-85a991566e3a)

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/939e081d43174f0dfcdffd90020dce07d7acf6f3. It ships in the analysis server so will show up in a future Dart/Flutter SDK release rather than a Dart-Code release.

**Comment by Zekfad** [comment]
Thank you for your awesome work, this helps a lot!
