### ISSUE TITLE
"Add missing switch cases" adds only one switch case

### ISSUE THREAD

**Issue by lukehutch** [Dart-Code/Dart-Code#4714]
**Describe the bug**

When selecting the quick fix "Add missing switch cases", only one switch case is added each time. You have to select that action as many times as you have missing switch cases.

**To Reproduce**

![image](https://github.com/Dart-Code/Dart-Code/assets/811305/528cc5f8-e122-4fb5-87ee-ea98047cab46)

![image](https://github.com/Dart-Code/Dart-Code/assets/811305/5776290c-a485-4203-8334-05bdf725bc95)

![image](https://github.com/Dart-Code/Dart-Code/assets/811305/4dbd4e3d-dc4f-448b-8e05-355346ca2506)

![image](https://github.com/Dart-Code/Dart-Code/assets/811305/c2daafa5-6a1c-4690-a42f-35323f229c77)

![image](https://github.com/Dart-Code/Dart-Code/assets/811305/3166c240-85ed-45c8-89cc-9c52492c04c5)

![image](https://github.com/Dart-Code/Dart-Code/assets/811305/ab3085a8-bb63-429c-af52-51c6c551080b)

etc.

**Expected behavior**

All cases should be added in a single action, especially because "cases" is plural in the quick fix menu...

**Please complete the following information:**
 - Operating System and version: Linux
 - VS Code version: Latest released
 - Dart extension version: Latest released
 - Dart/Flutter SDK version: Latest released
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
This is unfortunately a known issue with recent versions of Dart. There's an issue tracking this at https://github.com/dart-lang/sdk/issues/52180.
