### ISSUE TITLE
Please provide command for fetching version info, to make it easier to file bug reports

### ISSUE THREAD

**Issue by lukehutch** [Dart-Code/Dart-Code#4716]
The bug report template requests the following info:

> **Please complete the following information:**
>  - Operating System and version: 
> - VS Code version: 
> - Dart extension version: 
> - Dart/Flutter SDK version: 
> - Target device (if the issue relates to Flutter debugging):

You have to fish around in several different places to find all this info. It would be great if Dart-Code could provide a command similar to `flutter doctor -v` that would look up and produce all this info for the user, so they can just paste it into a bug report easily.

**Comment by DanTup** [comment]
Makes sense. A lot of this info is in the extension log (**Dart: Open Extension Log** and all other log headers), but it's not very obvious and those files are full of other things too.

I think we should have some kind of "Dart: Gather Diagnostic Info" command which can include:

- All of the info above (version numbers etc.)
- Workspace information (Dart/Flutter, remotes, etc.)
- A summary of SDK path search (eg. https://github.com/Dart-Code/Dart-Code/issues/4665#issuecomment-1653892383)
- The output of `flutter doctor -v`
- The output of `dart info`

That info in the bug template could then mostly be replaced by an instruction to run that command and copy the output (and remove anything sensitive).

**Comment by lukehutch** [comment]
> That info in the bug template could then mostly be replaced by an instruction to run that command and copy the output (and remove anything sensitive).

Exactly. Thanks!

**Comment by DanTup** [comment]
New command is this:

![Screenshot 2023-09-07 122659](https://github.com/Dart-Code/Dart-Code/assets/1078012/50aa375b-edff-45c7-af4f-620a426ce531)

It generates a file that contains the below. After this ships, I'll update the instructions to ask to copy/paste the results.


---



**!! ⚠️ PLEASE REVIEW THIS REPORT FOR SENSITIVE INFORMATION BEFORE SHARING ⚠️ !!**

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.74.0-dev
Flutter extension: 3.73.20230904 (not activated)

App: Visual Studio Code
App Host: desktop
Version: win 1.81.1

Workspace type: Flutter (LSP)

Dart (3.2.0-134.0.dev): C:\Dev\Google\flutter\bin\cache\dart-sdk
Flutter (undefined): C:\Dev\Google\flutter

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`C:\Dev\Google\flutter\bin\cache\dart-sdk\bin\dart.exe info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.2.0-134.0.dev (dev) (Mon Sep 4 13:06:39 2023 -0700) on "windows_x64"
- on windows / "Windows 10 Pro" 10.0 (Build 22621)
- locale is en-GB

#### Project info

- sdk constraint: '>=3.0.0 <4.0.0'
- dependencies: cupertino_icons, flutter, url_launcher
- dev_dependencies: flutter_lints, flutter_test

#### Process info

| Memory | CPU | Elapsed time | Command line |
| -----: | --: | -----------: | ------------ |
| 137 MB |  -- |              | dart.exe     |
|  82 MB |  -- |              | dart.exe     |
|  73 MB |  -- |              | dart.exe     |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`C:\Dev\Google\flutter\bin\flutter.bat doctor -v`

```text
[!] Flutter (Channel master, 3.14.0-14.0.pre.116, on Microsoft Windows [Version 10.0.22621.1848], locale en-GB)
    • Flutter version 3.14.0-14.0.pre.116 on channel master at C:\Dev\Google\flutter
    ! Warning: `dart` on your path resolves to C:\Dev\Tools\Dart\Stable\bin\dart.exe, which is not inside your current Flutter SDK checkout at C:\Dev\Google\flutter. Consider adding C:\Dev\Google\flutter\bin to the front of your path.
    ! Upstream repository git@github.com:DanTup/flutter.git is not the same as FLUTTER_GIT_URL
    • FLUTTER_GIT_URL = https://github.com/DanTup/flutter.git
    • Framework revision 3e65d04cfb (29 hours ago), 2023-09-06 02:45:33 -0400
    • Engine revision bace539bb6
    • Dart version 3.2.0 (build 3.2.0-134.0.dev)
    • DevTools version 2.27.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\danny\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33829.357
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.81.1)
    • VS Code at C:\Users\danny\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.73.20230904

[√] VS Code (version 1.82.0-insider)
    • VS Code at C:\Users\danny\AppData\Local\Programs\Microsoft VS Code Insiders
    • Flutter extension version 3.73.20230904

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1848]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 116.0.5845.141
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 116.0.1938.62

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by lukehutch** [comment]
Nice! You put that together quickly, thanks!
