### ISSUE TITLE
No code prompt

### ISSUE THREAD

**Issue by zhuyuanz** [Dart-Code/Dart-Code#4717]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - Operating System and version:
 - VS Code version:
 - Dart extension version:
 - Dart/Flutter SDK version:
 - Target device (if the issue relates to Flutter debugging):

**Comment by zhuyuanz** [comment]
![20230905082423](https://github.com/Dart-Code/Dart-Code/assets/90753710/fe0c64de-1263-4632-b77a-1ecc598dc3a1)

**Comment by zhuyuanz** [comment]
发现了，需要重新引入相关dart文件

**Comment by DanTup** [comment]
@zhuyuanz do I understand your last message correctly, that you have resolved the issue and this can be closed?
