### ISSUE TITLE
Suggest installing the ARB extension when editing arb files

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#4719]
The [ARB editor](https://marketplace.visualstudio.com/items?itemName=Google.arb-editor) extension provides language support for ARB files used for translating Flutter apps.

Since VS Code [has removed recommending extensions](https://github.com/microsoft/vscode/issues/188467) based on file extension we should consider showing a notification when a Flutter developer opens an ARB file offering to install the extension.

Something like:

> The ARB Editor extension can help with editing '.arb' files
> [Install Extension]   [Don't Show Again]

If the user does not interact with the notification at all (because they might not have noticed it and VS Code hides it after ~10s) we could re-show it only after some snooze period.

It should be shown:

- only if the extension is not already installed
- only if we have detected a Dart or Flutter project ~~(Dart doesn't currently use ARB files? @mosuem)~~

Questions:

- How long should we snooze before showing it again if not interacted with?
- Should we show it some maximum number of times and then give up (eg. if a user keeps ignoring it, perhaps they expect us to stop asking?)

(cc @jacob314 @anderdobo)

**Comment by mosuem** [comment]
> only if we have detected a Flutter project (Dart doesn't currently use ARB files?)

It does, for example using [package:intl_translation](https://github.com/dart-lang/i18n/tree/main/pkgs/intl_translation). `Dart-Code` has mechanisms for detecting if the workspace contains a Dart project I assume?

**Comment by DanTup** [comment]
Ah, in that case we should show it for either project type. Dart-Code detects all projects and determines whether each is plain Dart or Flutter.

**Comment by DanTup** [comment]
I've added this:

https://github.com/Dart-Code/Dart-Code/assets/1078012/bd8e4d37-75ae-4cce-b054-f9a17d64228b

It's using the same rules as other extension recommendations (via DevTools server). If the user clicks "No Thanks" we will not prompt again (I don't think we should just snooze, I think it will feel spammy).

If they _ignore_ the prompt, we will show it again, but not in the same session.

@mosuem @anderdobo @jacob314 let me know if you want any tweaks to this (the wording, or the behaviour).

**Comment by jacob314** [comment]
Looks great! Thanks for adding this.

**Comment by mosuem** [comment]
Wow, thanks so much for adding this @DanTup!
