### ISSUE TITLE
Set FLUTTER_ROOT for external tool processes like "dart devtools"

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#4722]
When running `dart` from `flutter-sdk/bin/dart`, the `FLUTTER_ROOT` variable is set (the same is true for `flutter`).

DevTools [sometimes needs to call Flutter commands](https://github.com/flutter/devtools/pull/6089#discussion_r1306200951) but in the extension we always run the `dart` executable directly (not through the shell script) so this isn't set. We should set it for all tools we spawn (when we are in Flutter mode, with a Flutter SDK) to make it easier for them to locate the same Flutter version the IDE is using.

**Comment by chunhtai** [comment]
What's the resolution of this issue?

**Comment by DanTup** [comment]
@chunhtai this has been implemented for the next extension release. The change is already in the pre-release version if you want to switch to that to test (it should be pretty stable):

<img width="703" alt="Dart pre-release versions" src="https://user-images.githubusercontent.com/1078012/218796750-90a70b0b-4957-468c-8eb4-688095cde112.png">
