### ISSUE TITLE
Unable to run tests with "Run" button in VSCode (but run fine from command line)

### ISSUE THREAD

**Issue by gspencergoog** [Dart-Code/Dart-Code#4724]
Today (but not on Friday) I'm having trouble getting tests to run in VSCode. It is basically telling me that all the symbols in dart:ui aren't defined (Offset, Size, etc.), or the Flutter SDK isn't available.  The test runs fine from the command line, and `flutter doctor` isn't giving me anything actionable.

I've tried clicking the "Run" link on several tests, and they either have massive errors because of undefined symbols that are definitely defined (I can even command-click on them!), or they simply say "The Flutter SDK is not available. Exited (255)." when I click the "Run" link in VSCode.

By contrast, running them on the command line works fine:

```
> cd packages/flutter
> flutter test test/material/page_test.dart
Resolving dependencies... 
  file 6.1.4 (7.0.0 available)
  material_color_utilities 0.5.0 (0.8.0 available)
  platform 3.1.1 (3.1.2 available)
  process 4.2.4 (5.0.0 available)
  webkit_inspection_protocol 1.2.0 (1.2.1 available)
Got dependencies!
5 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
00:08 +34: All tests passed!  
```

<details>
<summary>flutter doctor -v</summary>
<pre>
> flutter doctor -v
[✓] Flutter (Channel main, 3.14.0-14.0.pre.108, on macOS 13.5.1 22G90 darwin-arm64, locale en)
    • Flutter version 3.14.0-14.0.pre.108 on channel main at /Users/gspencer/code/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 6c5642167f (80 minutes ago), 2023-09-05 16:48:50 -0500
    • Engine revision f4975e04f3
    • Dart version 3.2.0 (build 3.2.0-134.0.dev)
    • DevTools version 2.27.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/gspencer/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/gspencer/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/gspencer/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2022.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.4
    • Dart plugin version 221.5921.27

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.5.1 22G90 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.140

[✓] Network resources
    • All expected network resources are available.

• No issues found!
</pre>
</details>

<details>
<summary>flutter doctor (run by the IDE, in output pane)</summary>
<pre>
[!] Flutter (Channel main, 3.14.0-14.0.pre.108, on macOS 13.5.1 22G90 darwin-arm64, locale en)
    • Flutter version 3.14.0-14.0.pre.108 on channel main at /Users/gspencer/code/flutter
    ! The flutter binary is not on your path. Consider adding /Users/gspencer/code/flutter/bin to your path.
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.18.6/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/gspencer/code/flutter. Consider adding /Users/gspencer/code/flutter/bin to the front of your path.
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 6c5642167f (68 minutes ago), 2023-09-05 16:48:50 -0500
    • Engine revision f4975e04f3
    • Dart version 3.2.0 (build 3.2.0-134.0.dev)
    • DevTools version 2.27.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/gspencer/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/gspencer/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/gspencer/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2022.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.4
    • Dart plugin version 221.5921.27

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.5.1 22G90 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.140

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
</pre>
</details>

Here are my dart settings in `settings.json`:
```json
    "dart.flutterSdkPath": "/Users/gspencer/code/flutter",
    "dart.debugSdkLibraries": true,
    "dart.debugExternalPackageLibraries": true,
    "dart.env": {
        "FLUTTER_ROOT": "/Users/gspencer/code/flutter"
    },
    "dart.flutterCreateOrganization": "dev.flutter",
    "dart.lineLength": 120,
    "dart.openTestView": [
        "testRunStart"
    ],
    "dart.debugExternalLibraries": true,
    "dart.previewLsp": true,
    "dart.flutterSdkPaths": [
        "/Users/gspencer/code/flutter"
    ],
    "[dart]": {
        "editor.codeActionsOnSave": {
            "source.fixAll": true
        },
        "editor.formatOnSave": false,
        "editor.formatOnType": false,
        "editor.rulers": [
            80,
            100
        ],
        "editor.selectionHighlight": false,
        "editor.suggest.snippetsPreventQuickSuggestions": false,
        "editor.suggestSelection": "first",
        "editor.tabCompletion": "onlySnippets",
        "editor.wordBasedSuggestions": false
    },
    "dart.promptToGetPackages": false,
    "dart.runPubGetOnPubspecChanges": "never",
```

I've tried doing all the paranoid things:

 - Sync to HEAD
 - reload VSCode
 - `git clean -dxf`
 - `rm -rf ~/.pub-cache`
 - `rm -rf ~/.dartServer`
 - reboot the machine

and it's still happening.

**Comment by DanTup** [comment]
I can repro this. The issue seems to be that we're using the Dart debug adapter instead of Flutter:

```
[11:00:57 AM] [General] [Info] Project (C:\Dev\Google\flutter\packages\flutter\test\material\page_test.dart) not recognised as Flutter or Web, will use Dart debugger
[11:00:57 AM] [General] [Info] Detected launch project as Dart
```

In the last release (published Monday) we changed how we detect whether a project is Flutter to properly parse the `pubspec.yaml` (instead of doing a basic string check which often had false positives). Obviously Flutter doesn't reference itself, so we're failing this check. The previous string check would find `sdk: flutter` from one of the other dependencies (`flutter_test`, `flutter_goldens`).

We should probably either detect any dependency with `sdk: flutter`, or include `sky_engine` in the check in addition to `flutter`.

**Comment by DanTup** [comment]
I've published updated extensions with the fix for this issue (both stable v3.72.2 and pre-release v3.73.20230906 channels). Please update and let me know if you still see any issues.

btw, from your settings:

- `FLUTTER_ROOT` - I don't think you should need to set this explicitly any more (since https://github.com/Dart-Code/Dart-Code/issues/4427)
- `dart.debugExternalLibraries` - this is unused - it was renamed to `dart.debugExternalPackageLibraries` (which you already have)
- `dart.previewLsp` - this is unused (LSP is the default now and that flag was removed)
- `dart.flutterSdkPaths` - unless you have multiple SDKs in this path, this isn't doing anything - the plural form of this setting is for the [SDK switcher](https://dartcode.org/docs/quickly-switching-between-sdk-versions/) and not used to locate the SDK to use

I also don't know if you added the `pub get` settings at the bottom because of bugs, or you just don't want to see them. If you think there are bugs (eg. you're being prompted/`pub get` is running when it shouldn't), do let me know so I can take a look :-)

**Comment by gspencergoog** [comment]
Thanks for the debug of all my ancient settings!  I'll remove the stuff I don't need.

The `FLUTTER_ROOT` setting is there because I sometimes run the CI scripts in debug mode, and wanted to make sure that FLUTTER_ROOT was set. If it gets set automatically, so much the better.  I'll try removing that and see if I still need it.

> I also don't know if you added the pub get settings at the bottom because of bugs, or you just don't want to see them. If you think there are bugs (eg. you're being prompted/pub get is running when it shouldn't), do let me know so I can take a look :-)

I added the "never" because I'm often working from the bus, which can have spotty internet access. If it tries to do a pub get every time I save, sometimes it gets stuck.  Also, since the `dart` script in `flutter/bin` checks to make sure that the `flutter` tool is built, if I'm merging or doing something else to the git repo at the time it tries to do the pub get, then it can start trying to download the dart SDK again, which is also super slow on the bus, and probably not what I want anyhow, since I could be in an intermediate state that will choke anyhow. None of this probably affects people who don't work on the framework. I just hit the `pub get` button manually when I need to, so it's no big deal.

**Comment by DanTup** [comment]
> The `FLUTTER_ROOT` setting is there because I sometimes run the CI scripts in debug mode, and wanted to make sure that `FLUTTER_ROOT` was set. If it gets set automatically, so much the better. I'll try removing that and see if I still need it.

I suspect this is covered by the change above - but if not, then it's almost certainly covered by https://github.com/Dart-Code/Dart-Code/issues/4722 (which I just landed but hasn't shipped yet), which will now set FLUTTER_ROOT for all downstream tool invocations when we're in Flutter mode.

If you find do see places where it seems you need it though, do let me know!


> I added the "never" because I'm often working from the bus, which can have spotty internet access.

Ah, gotcha. That all makes sense - just wanted to check you weren't working around something that was either fixed, or I didn't know about. Thanks! :-)
