### ISSUE TITLE
Dart-Code does not watch files in unversioned dependencies

### ISSUE THREAD

**Issue by lukehutch** [Dart-Code/Dart-Code#4725]
**Describe the bug**

In `pubspec.yaml`, it is possible to depend upon projects by path, e.g.:

```yaml
dependencies: 
  serverpod_client:
    path: ../vendor/serverpod/packages/serverpod_client
```

The files in a dependency like this are not monitored for changes by Dart-Code. Consequently, whenever you make changes in the dependency project, you have to go Ctrl+Shift+P > "Developer: Reload Window" and then wait for all the dependencies to be scanned.

**To Reproduce**

1. Add a project by `path`
2. Write code that calls a method in the dependency project
3. Change the method in the dependency project
4. Observe that your code that calls that method breaks, until you reload the window.

**Expected behavior**

All depended-upon files in `path:` dependencies should be watched for changes, just like files in the main project.

**Please complete the following information:**
 - Operating System and version: Linux
 - VS Code version: Latest public release
 - Dart extension version: Latest public release
 - Dart/Flutter SDK version: Latest public release
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
> Observe that your code that calls that method breaks,

Do you mean you get analysis errors, or it fails at runtime?

Is the project you're depending on (`../vendor/serverpod/packages/serverpod_client`) also in your workspace, or are you modifying it outside of this VS Code window?

**Comment by lukehutch** [comment]
It's outside my workspace, I believe, since various code features don't work when I hit F12 to jump to the source of dependencies.

The key point I'm making is that versioned dependencies (and even `git:` dependencies) can't technically change without a `flutter pub upgrade` (with a `git:` dependency that may check out a new commit, but then the "version" is different, just like a versioned upgrade). However `path:` dependencies should probably be treated as within the workspace, because those files can be edited at will, and often are.

**Comment by lukehutch** [comment]
I filed the dup: https://github.com/dart-lang/sdk/issues/53536

F12 does work -- there are other features that don't fully work when a Dart source file is not in your workspace (I don't remember which ones).

Thanks!
