### ISSUE TITLE
Dart-Code is not always able to parse stacktraces

### ISSUE THREAD

**Issue by lukehutch** [Dart-Code/Dart-Code#4727]
**Describe the bug**

Sometimes when a Dart stacktrace is printed to the debug console, it is not parsed properly by VS Code. For example:

```console
#0      ProfileInfoEndpoint._getAllUserInfo (package:click_server/src/endpoints/profile_endpoint.dart:29:7)
<asynchronous suspension>
#1      ProfileInfoEndpoint.updateProfile (package:click_server/src/endpoints/profile_endpoint.dart:49:9)
<asynchronous suspension>
#2      EndpointDispatch.handleUriCall (package:serverpod/src/server/endpoint_dispatch.dart:111:20)
<asynchronous suspension>
#3      Server._handleRequest (package:serverpod/src/server/server.dart:243:18)
<asynchronous suspension>
```

For this stacktrace, the filename and line numbers are not identified and linked in the debug console by VS Code. They are treated simply as text.

In this stacktrace, also from the debug console, some of the lines are correctly linked back to source (shown indented on a new line here, but shown as right-justified links in the debug console window in VS Code), and some are not:

```console
E/flutter (10117): #0      List.[] (dart:core-patch/growable_array.dart:264:36)
E/flutter (10117): #1      _ProfilePhotoEditorListState._editCaption
        profile_photo_editor_list.dart:246
E/flutter (10117): #2      _ProfilePhotoEditorListState._addPhoto.<anonymous closure>.<anonymous closure>
        profile_photo_editor_list.dart:234
E/flutter (10117): #3      showPhotoCropper.<anonymous closure>.<anonymous closure>
        photo_cropper_widget.dart:40
E/flutter (10117): #4      new Future.delayed.<anonymous closure> (dart:async/future.dart:427:39)
E/flutter (10117): #5      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (10117): #6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter (10117): #7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter (10117): #8      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```

**Please complete the following information:**
 - Operating System and version: Fedora 38
 - VS Code version: 1.81.1
 - Dart extension version: 3.72.1
 - Dart/Flutter SDK version: 3.10.0
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
@lukehutch can you easily include a screenshot of what you're seeing here? Are the lines that aren't linked correctly the ones that wrap and/or don't have full `dart:` or `package:` URIs?

**Comment by lukehutch** [comment]
I'll try to add a screenshot next time this happens.

**Comment by lukehutch** [comment]
OK, here is an example screenshot, where the filenames and line numbers are not parsed out and made linkable. They appear in the console as plaintext:

![image](https://github.com/Dart-Code/Dart-Code/assets/811305/b4a81ebb-e981-4d75-8200-0e9f742a1773)

**Comment by DanTup** [comment]
@lukehutch was this exception something you caught and then `print`ed, or was it unhandled/caught only by Flutter? Is it the entire call stack that's not linked, or only some lines?

Thanks!

**Comment by lukehutch** [comment]
This was an uncaught exception. In this case, it was the entire stack trace that was unlinked. In other cases, it's just a few stack frames that are unlinked, sometimes in the middle of the stack trace.

**Comment by DanTup** [comment]
Are you able to reproduce this in a small project you can share? There are some issues I know about in this area - one of them is fixed for the next SDKs but was Flutter-specific (https://github.com/Dart-Code/Dart-Code/issues/4571) and it's not clear if you hit this in Flutter, and the other only occurs when stack traces are printed (and not unhandled).

If you can share a repo, I can check whether there's another issue or this is one of those (and whether it's fixed or not for next release).

Thanks!

**Comment by lukehutch** [comment]
It doesn't seem to happen with any rhyme or reason, so I don't know that I can even produce a reproducer testcase for it. But I think there is something to be learned from the second stacktrace I gave in the original bug report: frame #0 and #4-#8 were not linked, but frames #1-#3 were linked. So it can even be some frames but not others in a single stacktrace that don't get linked. Therefore, it's not being caused by something like printing a stacktrace manually.

**Comment by lukehutch** [comment]
I got a video of this, although I don't know how to minimally reproduce this...

The whole stacktrace appears as a single entry in the console (the whole thing highlights on mouse-over). The individual source files are not clickable.

https://github.com/Dart-Code/Dart-Code/assets/811305/76a1757a-0281-4634-a016-595058ff1dce

**Comment by DanTup** [comment]
@lukehutch are you certain this is an unhandled exception printed to `stderr` and not an exception that was caught and `print()`ed? I would expect it to be red if it was stderr. If it's coming via stdout when I think this is probably a dupe of https://github.com/Dart-Code/Dart-Code/issues/4711?

**Comment by lukehutch** [comment]
If somebody printed this, it wasn't me :-D  Honestly I have no idea which IO channel this was printed to.

I think this is in fact a dup of #4711, so I'll close in favor of that issue. Thanks!

**Comment by DanTup** [comment]
Maybe something in serverpod? I found this code here:

https://github.com/serverpod/serverpod/blob/2fb4093d4d0d90670b829ac1ce3505c956d1e3c8/packages/serverpod/lib/src/server/server.dart#L451

However that seems to write to stderr, so I would still expect it to have been parsed. If you're able to breakpoint there and confirm that's the code being triggered here, I can do some more digging (or, if you can make a repro that would certainly be helpful) :-)

**Comment by lukehutch** [comment]
@DanTup I just remembered something, which makes me think this has nothing to do with stderr vs stdout:

Look at the second example I showed in the original report. Stack frames 1, 2, and 3 are linked, whereas 0 and 4-8 are not linked. This is within a single backtrace. Therefore, there has to be something wrong with how stacktraces are being parsed.

**Comment by lukehutch** [comment]
Here's a reproducer:

```dart
import 'dart:async';

import 'package:flutter/material.dart';

void main(List<String> args) {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: SafeArea(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                ElevatedButton(
                  onPressed: () => Timer(Duration.zero, () {
                    showDialog(
                        context: context,
                        builder: (context) {
                          throw 'error';
                        });
                  }),
                  child: const Text('Click me'),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

Screenshot (none of the stack frames are linked):

![image](https://github.com/Dart-Code/Dart-Code/assets/811305/638d7de2-6849-45f4-9605-d91c027eb555)

**Comment by DanTup** [comment]
Sorry for the delay - I can repro this on current beta:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/04b82051-06d2-4570-a029-653e167a1851)

**Comment by DanTup** [comment]
However, it looks like this on `master`:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/c6eb0c63-beb8-43af-bf6e-b448974f3a8f)

So I think this could just be https://github.com/Dart-Code/Dart-Code/issues/4571.

@lukehutch are you able to repro any missing links on `master`?

**Comment by lukehutch** [comment]
#4571 seems to deal with the same sort of issue in red text (stderror?).

Even the screenshot you show on master has unlinked frames (4-7), so I assume I would see the same thing on master myself (I'm away from my computer right now).

**Comment by DanTup** [comment]
Those last lines are runtime patch libraries and we're unable to map those, so that's expected.

**Comment by lukehutch** [comment]
Ah, OK. Then I will switch to master, and I'll comment here if I see it again.

However, in general, I suggest putting `(runtime patch library)` on the end of those lines, so that it is obvious that an effort was made to link those lines, but it was not possible.

**Comment by lukehutch** [comment]
@DanTup Actually I was already on the "Pre-Release Version" in the VS Code Extensions view. Is this the version you want me to test?

**Comment by DanTup** [comment]
> I suggest putting (`runtime patch library`) on the end of those lines

Unfortunately we don't have that control here. All we can do is attach (or not) some location metadata to the events, and VS Code decides how to render that in the debug console.


> Actually I was already on the "Pre-Release Version" in the VS Code Extensions view. Is this the version you want me to test?

Sorry for the confusion - this work is done by the debug adapter which lives inside the SDK. It was the Flutter master channel I was referring to :-)

**Comment by lukehutch** [comment]
Ah, I was on the Flutter master channel a few times lately, but there was some breakage (I don't remember what), so I backed off, and I'm on beta now.

**Comment by lukehutch** [comment]
I tracked down the cause of one case where stacktraces are not auto-linked: this happens when the user calls `stdout.writeln('$stackTrace')`, which I think is the bug you linked previously.

This doesn't account for some of the cases though where some frames are linked and some are not, within a single stacktrace, even though all code is in the same project.

**Comment by DanTup** [comment]
@lukehutch are you testing with Flutter `master`? Do you have an example of unlinked frames that aren't a) printed via stdout and b) a `_patch` file? (those are both known issues.. the former needs to be fixed, the latter is not currently fixable).

**Comment by DanTup** [comment]
I think the only issue not solved here is the patch files. I don't know if we can handle this (because I don't know if we can compute paths, and there may be multiple patch files for different platforms).

But I'll keep this open to look at and at least figure out exactly what those issues are.

**Comment by lukehutch** [comment]
I found one more area where code is not linked as it could/should be. This time, this is for output sent to stdout, and it's not stacktraces, it's the list of compilation errors that are given when you try to run code that has errors in it. The error lines are not linked:

![image](https://github.com/Dart-Code/Dart-Code/assets/811305/c4a58733-2797-4066-bb04-0ab52f05312b)

It would be really helpful to have these lines linked.

**Comment by DanTup** [comment]
@lukehutch thanks! Could you file a new issue for that one? I'm not sure how easily we can handle these ones, but it'll be a very different fix to the patch files. Thanks!

**Comment by lukehutch** [comment]
@DanTup I created #4853 for this. Thanks!

**Comment by DanTup** [comment]
This was fixed recently, the frames are clickable - including `_patch` files:

![Image](https://github.com/user-attachments/assets/f6f16c35-b460-4886-acac-415811b5f0ff)
