### ISSUE TITLE
"Push down negation" support, using De Morgan's laws

### ISSUE THREAD

**Issue by lukehutch** [Dart-Code/Dart-Code#4728]
**Is your feature request related to a problem? Please describe.**

Eclipse can push unary negation down into the following parenthetical expression, using De Morgan's laws. It would be great if Dart-Code could do this too.

Before:

```dart
if ((a || b || c) && !(a && b && c))
```

Insert the cursor right before or after '!' to initiate the "Push Down Negation" action.

After:

```dart
if ((a || b || c) && (!a || !b || !c))
```

In some cases, the parentheses will be needed after the transformation; in some cases, the parentheses won't be needed (it depends on precedence). (On a broader note, it would be nice if the Dart linter recognized unnecessary parentheses, but I digress...)

The reverse should also be possible: Any expression should be able to be selected, and an "Double-negate" action should be available, that parenthesizes and negates the selected expression, again using De Morgan's:

Before:

```dart
if (a || b || c) 
```

Select `b || c` and select the "Double-negate" action.

After:

```dart
if (a || !(!b && !c))
```

Although some thought will have to be given to this to respect precedence, for example if the expression was `if (a && b || c)` and `b || c` was selected for double-negation, this would violate precedence.

(Also maybe a better name than "Double-negate" should be chosen -- "Pull up negation" to mirror "Push down negation"?)

**Comment by DanTup** [comment]
This is one for https://github.com/dart-lang/sdk/issues. It would need to be implemented in the Dart language server. VS Code calls things on the lightbulb menu "Code Actions", though in the Dart language server these kinds of things are called Assists. Thanks!

**Comment by lukehutch** [comment]
Thanks, filed as https://github.com/dart-lang/sdk/issues/53620
