### ISSUE TITLE
Debugger "Copy Value", Watch window and Debug Console should show untruncated values in SDK DAPs

### ISSUE THREAD

**Issue by brizaldi** [Dart-Code/Dart-Code#4730]
**Describe the bug**
The debug variable, specifically a String, is not displaying all of its values. It only shows a portion of it and is then truncated with the '...' symbol.

**To Reproduce**
1. On your code, create a String variable with a very long size (>1000 characters should be enough).
2. Create a breakpoint below that variable.
3. Run the program with debugging.
4. Go to 'Run and Debug' on the sidebar.
5. Check that String variable value.

**Expected behavior**
When inspecting the debug variable, it should be able to display the entire content of its value.

**Screenshots**
![image](https://github.com/Dart-Code/Dart-Code/assets/41714881/40d09c59-fec4-47bc-ba17-6e4239ac17a2)

**Please complete the following information:**
 - Operating System and version: Windows 11 22H2 Build 22621.2215
 - VS Code version: 1.81.1
 - Dart extension version: 3.72.2
 - Dart/Flutter SDK version: Dart 3.1.0 / Flutter 3.13.2

**Comment by DanTup** [comment]
It's expected that the values here are truncated, because sending untruncated data for all variables could be a lot of data.

However, right-clicking and choosing "Copy Value" or evaluating in the Debug Console/Watch window directly _should_ include the full value - but that appears to not be working in the new debug adapters. I'll tweak this issue to be for fixing those.

**Comment by DanTup** [comment]
Working on a fix at https://dart-review.googlesource.com/c/sdk/+/326642

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/59294606cf8c5d07d98c9beac4eff43dbf609f11, but this is a change in the SDK so it'll show up in a future SDK release rather than a VS Code extension release.

**Comment by mmohamedbh** [comment]
I think its broken again.

Extension version: 3.88.1
Dart SDK version: 3.2.5

Get the same value when clicking on "Copy value"

![image](https://github.com/Dart-Code/Dart-Code/assets/156440324/851583bf-4329-4b51-892b-4fbc7d655183)

**Comment by DanTup** [comment]
@mmohamedbh this fix is in the SDK so you need to update your Dart/Flutter SDK to get the fix,

**Comment by mmohamedbh** [comment]
> @mmohamedbh this fix is in the SDK so you need to update your Dart/Flutter SDK to get the fix,

I thought it was the extension. I just update the the SDK to the last version and now it works 👍. Thanks!

**Comment by DanTup** [comment]
Great, thanks for confirming!
