### ISSUE TITLE
Use a lower maxCompletionItems when running in a remote workspace

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#4731]
Similar to https://github.com/Dart-Code/Dart-Code/issues/4729, we should reduce `maxCompletionItems` to reduce payload sizes in remote workspaces. Ideally we'd reduce it for all sessions but it's not completely clear what the impact of ranking issues (such as https://github.com/Dart-Code/Dart-Code/issues/4618) would be, so trying it out in remote workspaces (a small portion of sessions) might help highlight any issues there.

**Comment by fadel1411** [comment]
Great work DanTup
