### ISSUE TITLE
Can't set environment variables using launch.js in Visual Studio Code

### ISSUE THREAD

**Issue by DanBaDo** [Dart-Code/Dart-Code#4736]
I'm need to access some environment variables from my code. I'm trying to test it following the extension instructions but I can't get it working. Instead getting environment variables values, I get empty strings.

This is the documentation I'm reading: https://dartcode.org/docs/using-define-in-dart/

![image](https://github.com/Dart-Code/Dart-Code/assets/85959254/7e2227a6-a79d-4a03-b7e9-7df64780fedc)
![image](https://github.com/Dart-Code/Dart-Code/assets/85959254/4f950764-6ef2-4e3a-800a-70ad38c4e573)

I'v tried to split "--define" and his arguments with the same results.

When I run my code like `dart run --define=MAILJET_KEY=AAAAAAAAAAAAAAAAAAAAA test/mailjet_test.dart`it works fine, so it looks like the problem is in the extension.

I'm running it in Ubuntu 22.04.3 LTS 64bits.
VSCode 1.82.0
3.72.2 extension version
Dart SDK 3.1.0

Discord conversation: https://discord.com/channels/615553440969392147/615553440969392151/1149629142350958723

**Comment by DanTup** [comment]
Apparently I reproduced this when we were chatting, but I can't find my test project and now I seem unable to reproduce this:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/cf2fc4af-5b44-444d-bd7f-c1ce6eb72297)

I'm on Windows now and may have been on a MacBook at the time, so I'll try again on Mac later.

**Comment by DanTup** [comment]
Also seems to be working fine on my MacBook:

<img width="1236" alt="Screenshot 2023-09-12 at 12 46 02" src="https://github.com/Dart-Code/Dart-Code/assets/1078012/76ac0649-2daa-4b14-8973-1abf56a7f082">

@DanBaDo are you able to create a small project that definitely reproduces this issue and share it (along with the `pubspec.yaml`, `.vscode/launch.json` etc.)? Thanks!

**Comment by DanBaDo** [comment]
Hi.
I create this project that reproduces the issue BUT I found that it doesn't fails when running using `Run and Debug` VSCode or pressing F5 but fails running from inline buttons and from tab bar launcher. It fails too when launching from `Testing`tool.
https://github.com/DanBaDo/dart-code-extension-4736-test
![img](https://github.com/Dart-Code/Dart-Code/assets/85959254/5d3da0b7-a13c-444c-ab7e-018515aca87a)
![img1](https://github.com/Dart-Code/Dart-Code/assets/85959254/ffebfb3a-251c-48e8-abe5-6320b714df9e)

**Comment by DanTup** [comment]
Aaaah, then this is expected. Those Run/Debug links are just shortcuts to run the current file/test/whatever and are unrelated to the launch configurations (because you might have 20 launch configurations and we wouldn't want them all showing here).

However, you can mark launch configurations as being templates which should solve your problem - see [these docs](https://dartcode.org/docs/launch-configuration/) and search for `templateFor`.

By using an empty string, you can mark them as the template for the entire workspace:

```
"toolArgs": [
  // ...
],
// An empty string means make this a template for Run/Debug in CodeLens and the Test Runner
// https://dartcode.org/docs/launch-configuration/#:~:text=templateFor
"templateFor": "",
```

**Comment by DanBaDo** [comment]
That's ok.
It works for every cases except tests, but it's because `dart test` doesn't supports `--define` modifier.
May be documentation must be updated for reflecting this solution.
