### ISSUE TITLE
Debug console does not show evaluation results after a test is restarted

### ISSUE THREAD

**Issue by incendial** [Dart-Code/Dart-Code#4737]
**Describe the bug**

https://github.com/Dart-Code/Dart-Code/assets/21116742/899c1836-2548-4092-a30a-96ff5ad683d9

**Please complete the following information:**
 - Operating System and version: MacOS
 - VS Code version: 1.82.0
 - Dart extension version: 3.72.2
 - Dart/Flutter SDK version: 3.2.0-42.2.beta (beta) (Wed Aug 30 10:44:12 2023 +0000) on "macos_x64"
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
I can repro this, but it seems to be a VS Code issue - the results are coming back from the debug adapter correctly.

There's an issue open at https://github.com/microsoft/vscode/issues/192653, apparently it happens in other languages. I'll close this as I think there's nothing to do in the extension here.
