### ISSUE TITLE
Add flutter snippets

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#474]
See #350, #473.

**Comment by DanTup** [comment]
@devoncarew @mit-mit Is there a good source of snippets for flutter? If not, do the two in 3b028c3 look good? Any more to add?

**Comment by DanTup** [comment]
Oh, btw - I tweaked the conditions so that if you have a multi-root workspace that has multiple flutter and multiple Dart projects, the flutter widgets will still only show when editing files inside the flutter projects - this seems logical. However it's based on the "if the pubspec.yaml references the flutter SDK" logic, so if there's the possibility of a shared flutter library that *doesn't* reference the SDK in its pubspec, this might be bad - please lmk if that's the case.

**Comment by mit-mit** [comment]
See https://github.com/flutter/flutter-intellij/blob/master/resources/liveTemplates/flutter_miscellaneous.xml

**Comment by DanTup** [comment]
@mit-mit Perfect, thanks!

**Comment by devoncarew** [comment]
(@stevemessick for fyi)
