### ISSUE TITLE
In VS Code, when running a release build using the 'Run and Debug' option, if I close the Flutter/Dart application, the stop button on the debug toolbar is still enabled. 

### ISSUE THREAD

**Issue by sohrab-niche** [Dart-Code/Dart-Code#4742]
**Describe the bug**
In VS Code, when running a release build using the 'Run and Debug' option, if I close the Flutter/Dart application, the stop button on the debug toolbar is still enabled. I spent the entire day trying to understand this and finally believe that the application has really shut down and is not in a zombie state; rather it is the debug toolbar that should have at least polled the system to check whether the exe is still running and if not, updated the buttons accordingly. 

**To Reproduce**
1. Go to the 'Run and Debug' option in the left-hand-side toolbar. The Run and Debug window opens docked on the left, after the toolbar. 
2. Click on the dropdown at the top of the Run and Debug window and select the release mode for the Flutter project to be run in release mode.
3. Click the '|>' button to the left of the dropdown. This will launch the Flutter application.
4. Close the Flutter application by closing its main window. Observe the debug toolbar. The halt icon-button remains enabled even though we can verify via the Task manager that the Flutter application has indeed exited.

**Expected behavior**
The stop button and all other widgets that should be disabled/hidden when the Flutter application is closed, must be disabled/hidden accordingly.

**Screenshots**

**Please complete the following information:**
 - Operating System and version: Windows 11 
 - VS Code version: 1.82,1
 - Dart extension version: v3.73.20230904
 - Dart/Flutter SDK version:  flutter --version
Flutter 3.13.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2524052335 (7 days ago) • 2023-09-06 14:32:31 -0700
Engine • revision b8d35810e9
Tools • Dart 3.1.1 • DevTools 2.25.0
 - Target device (if the issue relates to Flutter debugging): windows desktop

**Comment by DanTup** [comment]
Sorry for the delay.

This appears to be a Flutter issue - I can reproduce it outside of VS Code:

- run `flutter run --release -d windows`
- close the app

The Flutter process remains active in the terminal, and doesn't quit when the app was closed.

I've raised this as https://github.com/flutter/flutter/issues/135019, please subscribe there for updates. Thanks!
