### ISSUE TITLE
Add a prompt for Extract local variable

### ISSUE THREAD

**Issue by lsaudon** [Dart-Code/Dart-Code#4749]
**Is your feature request related to a problem? Please describe.**
I'd like to see a prompt for `Extract local variable` as well as for `Extract method`.

**Describe the solution you'd like**
Add a prompt after select `Extract local variable`.

**Describe alternatives you've considered**
After extract, trigger `Rename symbol` vscode.

**Comment by DanTup** [comment]
The way this was implemented (prompting for a name like Extract Method) has resulted in losing the server-generated name and I think that's made this much worse. I'm going to revert this for now, and try to find a better way to rename (such as triggering the rename automatically if it's possible).

Issue tracking the revert is https://github.com/Dart-Code/Dart-Code/issues/4786, and I'll re-open this to track a new solution.

**Comment by lsaudon** [comment]
Also, why do I have this ?

```dart
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
      ),
    );
  }
```
I can't extract `AppBar()` with name `appBar` ? I have this message `The name 'appBar' is already used in the scope.`.
Likewise, I can rename with `appBar` after extract.

**Comment by DanTup** [comment]
@lsaudon I'm not sure - could you file a new issue about that with exact instructions of what you're selecting and invoking? Thanks!

**Comment by DanTup** [comment]
I believe this is still outstanding and worthwhile, is there a reason you closed it @lsaudon ?

**Comment by DanTup** [comment]
@lsaudon what do you see now?

**Comment by DanTup** [comment]
Oh, was your complaint that it was generating a bad variable name, rather than not prompting for it in advance?

I would like to automatically trigger rename after generating, but there's no great way to do this right now within standard LSP.

**Comment by DanTup** [comment]
Gotcha, thanks. In that case I'll re-close this, and we can hope to fix it by triggering the rename functionality directly after the refactor if VS Code/LSP get that capability.
