### ISSUE TITLE
[flutter_tooling] Refactor `EdgeInsets.all()` & `EdgeInsets.symmetric()` to `EdgeInsets.only()` & `EdgeInsets.symmetric()`

### ISSUE THREAD

**Issue by dickermoshe** [Dart-Code/Dart-Code#4752]
### Problem

While programming it is very common that users will create a padding in all direction, and then later decide that in one direction it should be different. You then need to manually change all to only and manually fill in `top`, `bottom`, `left`, `right`.
The refactor tooling that adds a padding automatically uses `EdgeInsets.all()` by default, so it's very common when you want to add padding in one direction, you have to manually change the named constructor and set the correct variables. 

https://github.com/flutter/flutter/assets/75931499/00cf5c2e-6e99-4c43-870b-ea40bcc71f41

### Proposal

A refactor option built into the flutter tooling that would provide the options to refactor:

- `EdgeInsets.all(10)`

to

- `EdgeInsets.symmetric(vertical: 10.0, horizontal: 10)`
- `EdgeInsets.only(right: 10, left: 10,top: 10,bottom: 10)`

&

- `EdgeInsets.symmetric(vertical: 10.0, horizontal: 10)`

to

- `EdgeInsets.only(right: 10, left: 10,top: 10,bottom: 10)`   

  
There aren't any known shortcuts to refactor this.

**Comment by DanTup** [comment]
Sorry for the delay. I missed a bunch of GH notifications and apparently didn't look back for enough in the issue tracker when catching up.

These refactors come from the Dart analysis server so this would need to be implemented there. Would you mind filing the issue in https://github.com/dart-lang/sdk? Thanks!
