### ISSUE TITLE
Make code complete ignore '_' for private variables/functions/members when order the list

### ISSUE THREAD

**Issue by zhxst** [Dart-Code/Dart-Code#4753]
**Is your feature request related to a problem? Please describe.**
Say I have a variable `var _privateVar = 100;`
When I want to use this var later, I try to input `pri`.
But the code complete will not show `_privateVar`, because it's start with underline `_`. 
Or maybe it's after all the names without `_`?
Then I have to delete `pri` and input `_pri` or even `_privateVar`.

**Describe the solution you'd like**
When input like `pri`, the auto compete will show `_privateVar`.
And the auto complete could sort the names of private one like the public one, which means it ignoring the prefix underline `_` when sort the names.

**Describe alternatives you've considered**
Another way is to allow private one like `privateVar_`.
But that maybe a big change to dart, and even a breaking change.

**Additional context**
If there is a better place for this feature request, please let me know. Thanks.

I have tested. VSCode has this issue, when Android Studio has not.

** Screenshots**
<img width="516" alt="image" src="https://github.com/Dart-Code/Dart-Code/assets/11647836/4e77031d-a901-4549-9c62-99d8246849b9">
<img width="499" alt="image" src="https://github.com/Dart-Code/Dart-Code/assets/11647836/93bbff16-4507-4abe-a331-4cf538634dd8">
<img width="577" alt="image" src="https://github.com/Dart-Code/Dart-Code/assets/11647836/9b674918-74fc-4def-89e3-2578b5c2c046">

**Comment by DanTup** [comment]
Sorry for the delay, I missed the notification for this. 

I did some testing but wasn't able to reproduce the issue you're seeing - private variables (top level, class member and local variable) all seem to show up in completion for me:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/3f629c18-fb43-41b1-99d8-aaf161e932a7)

I wonder if the issue you're seeing is just one of _ranking_ (that is, they're in the list but much further down). Are you able to provide screenshots or ideally a small example that illustrates the issue?

Thanks!

**Comment by zhxst** [comment]
Screenshots updated.
Maybe the title should be changed.
`_isLoading` is a private field inside class. but it's after all the names outside the class, even outside the file and outside the package.
And it seems your screenshot showing a different result.🤔️
Is there any configuration could have affect this?

**Comment by zhxst** [comment]
And I think the better solution, is make the list order ignore the '_' . Because it's a constraint for private member. It's a kind of keyword than a part of name.

**Comment by DanTup** [comment]
Thanks for clarifying, this seems like a ranking issue.

Once you start typing characters, the ranking is handled by VS Code and not the language extension (see https://github.com/microsoft/vscode/issues/79516) so this can only be changed by VS Code.

That said, I think this is deliberate because the items shown at the top (starting with "is") are a closer match to what you're typing (exact prefixes are weighted higher than substring matches).

Perhaps there's an argument that leading underscores should be ignored, but this would need to be done in VS Code so should be raised at https://github.com/microsoft/vscode.

Hope this makes sense!

**Comment by zhxst** [comment]
Thank you very much. I guess you did spend a lot of time deal with these VSCode issues 😂
