### ISSUE TITLE
Overhaul of the refactoring actions

### ISSUE THREAD

**Issue by ppasieka** [Dart-Code/Dart-Code#4754]
With 15+ years of development experience (mainly in C#), I've used numerous tools to improve my coding efficiency. The Dart extension falls short in this regard, as it often promotes less efficient practices.

### Example

For instance, let's consider the refactoring action: `Add a named parameter to the existing constructor`. It doesn't align well with common Dart practices. Typically, one would want to create a `final` field along with `this.fieldname` in the constructor. However, the extension adds a typed named-parameter and suggests a second refactoring to produce a backing field. To make things worse, the second refactoring uses `var` instead of `final`.

Manually adding a named parameter is quicker than using the refactoring action provided, defeating the purpose of an automated tool designed to speed up development.

### My general feeling about the extension

It appears the Dart extension was built more to fill a gap in the ecosystem rather than provide genuinely useful or efficient refactoring options.

**Comment by DanTup** [comment]
Sorry for the long delay in responding here - I somehow missed the notification and just found the issue looking through the tracker.

I wasn't able to reproduce exactly what you described (it wasn't clear to me exactly what code you had or where you were invoking refactors/fixes), although I do agree refactors could do with some improvement. The refactors all come from the Dart analysis server so requests for new refactors/fixes should be filed at https://github.com/dart-lang/sdk/. Please try to include as much detail as possible (such as a code sample, where you'd like to invoke the refactor, and exactly the resulting code should be).

While trying to repro what you described, I did notice some awkwardness adding new final fields to a class and opened my own issue at https://github.com/dart-lang/sdk/issues/53707 with a suggestion that might make new fields a little easier.

If you do file issues, please post the link back here for others that may discover this issue (or me!) that might like to add 👍 's to them. Thanks!
