### ISSUE TITLE
Feature request: report unused parameters

### ISSUE THREAD

**Issue by stephane-archer** [Dart-Code/Dart-Code#4756]
**Is your feature request related to a problem? Please describe.**
This extension doesn't report unused parameters in a function.

**Describe the solution you'd like**
I would like this to be reported so I can stop sending useless data to my fonction

**Comment by DanTup** [comment]
Thanks for the suggestion - there's an existing open issue at https://github.com/dart-lang/linter/issues/2204 about adding a lint for this. Please subscribe there for updates!
