### ISSUE TITLE
"wrap with widget" wraps the entire switch expression instead of the current branch

### ISSUE THREAD

**Issue by woprandi** [Dart-Code/Dart-Code#4758]
**Describe the bug**
"wrap with widget" wraps the entire switch expression instead of the current branch

**To Reproduce**
```dart
enum MyEnum {a, b}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return switch(get()) {
        MyEnum.a =>  const Text('a'),
        MyEnum.b =>  const Text('b'),
    };
  }
}

MyEnum get() {
// ...
}

```
Move your cursor to `Text('a')` and do a `"Wrap with widget..."` (or anything else)

**Expected behavior**
The new widget should be parent of the `Text('a')`  branch and not of the entire switch expression

**Screenshots**

**Please complete the following information:**
 - Operating System and version: Fedora 38 
 - VS Code version: 1.82.2
 - Dart extension version: 3.72.2
 - Dart/Flutter SDK version: 3.1.2 / 3.13.5
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
Thanks - I can reproduce this. Working on a fix at https://dart-review.googlesource.com/c/sdk/+/327883.

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/2d0bebfb22b15f1efe898c9f584a237c71eea7a3. The change is in the language server, so the fix will show up in a future SDK release (not a Dart-Code extension release).
