### ISSUE TITLE
Code completion should automatically appear in strings when typing $ or ${

### ISSUE THREAD

**Issue by mit-mit** [Dart-Code/Dart-Code#476]
Assume a class foo:

```
class foo {
   static const var1 = 42;

   void bar() {
      print('foobar: ');
   }
}
```

Now try to extend the string inside print from `'foobar: '` to `'foobar: $var1'`.

After typing `$v` I would expect to be able to code complete to `$var1`, but that does seem to happen.

**Comment by DanTup** [comment]
@mit-mit Seemed to work ok here:

<img width="906" alt="screen shot 2017-12-19 at 18 58 29" src="https://user-images.githubusercontent.com/1078012/34173819-a9c57c98-e4ee-11e7-9c7d-2a7bec76d107.png">

Could you try these two things:

1. Open dev tools (Help -> Toggle Developer Tools) to see if there are any warnings/errors reported
2. [Turn on analysis server logging](https://github.com/Dart-Code/Dart-Code/blob/master/CONTRIBUTING.md#enable-logging) by setting `dart.analyzerLogFile` to a filename for logging (the containing folder must exist) and repro and attach the relevant part of the log

Also, which version of the SDK are you using? (it's shown in the status bar bottom right). I presume you're on latest stable Code + Dart Code?

Ta!

**Comment by mit-mit** [comment]
I'm using vscode 1.19.0, dart-code 2.6.2 and flutter on the master channel from a few days ago (which is on Dart version 1.25.0-dev.11.0).

![screen shot 2017-12-20 at 11 51 30](https://user-images.githubusercontent.com/13644170/34203619-2583ca50-e57c-11e7-929b-e805446164c6.png)

![screen shot 2017-12-20 at 11 51 46](https://user-images.githubusercontent.com/13644170/34203638-2f9f0d06-e57c-11e7-9d1e-32ce343d5838.png)

**Comment by DanTup** [comment]
Aha, I think I understand the issue. You were expecting the completion to open automatically, but I was manually invoking it!

It seems this is a default setting in VS Code that does not automatically invoke completion when inside strings. You can fix this in your User Settings for VS Code:

```js
"editor.quickSuggestions": {
  "other": true,
  "comments": false,
  "strings": true // This defaults to false
}
```

I found this [here](https://github.com/Microsoft/vscode/issues/23962#issuecomment-292079416), linked from [here](https://github.com/Microsoft/vscode/issues/24196).

Please let me know if this is the issue. We could possibly consider defaulting this on for Dart files in Dart Code, but we'd have to do some testing to ensure the user is still able to override it.

**Comment by mit-mit** [comment]
Yes, I can confirm that settings gives me my expected behaviour.

Yes, I think we should default to that. I think that is generally what developers expect, and it would be consistent with our other IDEs.

**Comment by Skylled** [comment]
My $.02 would be to see if it's possible to trigger auto-complete with the `$` instead of globally enabling. Does Dart-Code tell VSC what is and isn't a string?

**Comment by mit-mit** [comment]
Oh, good point, I didn't try it without. I agree it it would be best if auto-completion was gated on using `$` / `${}`.

**Comment by DanTup** [comment]
Seems to work well with no negatives in my testing; so I've added those chars.
