### ISSUE TITLE
Assist for inlining file-local, constants, variables, and functions

### ISSUE THREAD

**Issue by lukehutch** [Dart-Code/Dart-Code#4763]
**Is your feature request related to a problem? Please describe.**

Currently Dart-Code has an assist "Inline local variable". However, this does not work for top-level variables or constants that are file-local (start with an underscore). It also does not work for functions (which I appreciate would have a higher level of complexity to implement).

**Describe the solution you'd like**

There should be the ability to inline constants and toplevel variables, at the very least if their name starts with an underscore. It would be awesome if this could be done for any variable, whether it starts with an underscore or not, but I would be happy even just with local changes, since that is the most common case for inlining toplevel variables.

I would also love to be able to inline functions, including toplevel functions, static class methods, and even object methods (although removing an object method after inlining is more complicated, because it changes the object's prototype).

**Comment by DanTup** [comment]
Sounds reasonable to me - though they'd need implementing in the analysis server. Would you mind filing at https://github.com/dart-lang/sdk?

Thanks! :)
