### ISSUE TITLE
Please provide assist for converting arguments between positional and named

### ISSUE THREAD

**Issue by lukehutch** [Dart-Code/Dart-Code#4764]
**Is your feature request related to a problem? Please describe.**

Given this code:

![image](https://github.com/Dart-Code/Dart-Code/assets/811305/c3acfb56-958a-49e2-bf0f-c9b8e6074267)

I want to be able to hit Ctrl-Space on the `e` argument, and select `Convert to required named parameter`, yielding this:

![image](https://github.com/Dart-Code/Dart-Code/assets/811305/d49f064a-3bf2-4d3d-bfc0-42caf24cddd6)

For non-nullable types, there should be only a required named parameter option, but for nullable types, there should be two options, to convert to a required or a non-required named parameter.

There should also be an assist that takes a named parameter, and converts it to a positional parameter (probably tacking it on the end of the list). This should also offer to convert to an optional positional parameter (in square brackets) as an option, for nullable types.

**Comment by DanTup** [comment]
There's an existing issue for converting to named parameters at https://github.com/dart-lang/sdk/issues/45675 which looks like it had some progress recently :)

> There should also be an assist that takes a named parameter, and converts it to a positional parameter 

Could you file an issue for that in https://github.com/dart-lang/sdk? These assists come from the server, so it'll need to be implemented there. Thanks!
