### ISSUE TITLE
autocomplete `teardown*` and `setup*` appear as if they were deprecated 

### ISSUE THREAD

**Issue by osaxma** [Dart-Code/Dart-Code#4766]
**Describe the bug**
autocomplete  for `tearDown`/`tearDownAll` and `setUp`/`setUpAll` appear as if they were deprecated  but they aren't:

<img width="479" alt="Screen Shot 2023-10-02 at 7 29 40 PM" src="https://github.com/Dart-Code/Dart-Code/assets/46427323/fcc7d95a-c3f6-400b-af46-6135cdb3b7e1">

<img width="484" alt="Screen Shot 2023-10-02 at 7 29 34 PM" src="https://github.com/Dart-Code/Dart-Code/assets/46427323/c9b8b182-c5b5-4f3e-a1b2-7302e9a518a1">

**To Reproduce**
The screenshots where from the main function of a `_test.dart` file .

 - Operating System and version: 12.6 (21G115) 
 - VS Code version:  1.82.2
 - Dart extension version: v3.74.0
 - Dart/Flutter SDK version: Dart SDK version: 3.1.2 (stable) (Tue Sep 12 16:26:23 2023 +0000) on "macos_x64"

**Comment by DanTup** [comment]
What version of the `test` package do you have in your `.dart_tool/package_config.json` file? I would've expected this to be solved by https://github.com/dart-lang/test/issues/1990. You might need to run `pub upgrade` to update the version of the package you're using (or if you have narrow constraints in your pubspec, you might need to modify them).

**Comment by osaxma** [comment]
I seem to be on the latest version:

```json
    {
      "name": "test",
      "rootUri": "file:///Users/osaxma/.pub-cache/hosted/pub.dev/test-1.24.6",
      "packageUri": "lib/",
      "languageVersion": "3.0"
    },
```

I also ran `dart pub upgrade --major-versions` to make sure everything is up to date and the issue persists. 

Both `test` and `group` show as deprecated in autocomplete.

**Comment by DanTup** [comment]
You're right - seems like there are still issues. I've opened https://github.com/dart-lang/test/issues/2111 with some details.

Closing this as the fix will be entirely in `package:test`. Thanks!
