### ISSUE TITLE
Can't run/debug app

### ISSUE THREAD

**Issue by mit-mit** [Dart-Code/Dart-Code#477]
Suddenly I can no longer run apps from code. I just get this error when I try:

```
Unable to restart debugging. Please try ending the debug session and starting again.
```

It was working a few days ago, and I'm not aware of making any other changes than updating flutter to the latest master build. I tried to fully remove vscode, and the reinstall it, but still get the issue.

I'm on macOS, using code Version 1.19.0 (1.19.0). `flutter doctor` is clean, and `flutter devices` enumerates devices as expected.

**Comment by DanTup** [comment]
This happens when the debugger doesn't receive arguments, a path to the SDK or a path the entry point.

Are you running something public I can test with, and also could you provide the contents of your `.vscode/launch.json` file?

**Comment by DanTup** [comment]
Looking at the code, both the SDK path and entry point are given defaults, so it's strange you're seeing this. I think there was some issue with Code not supplying the args when you restarted debugging (which is why we added this message, to catch it), but if you're starting a clean debug session it shouldn't be that.

I'll do some digging and see if I can repro.

**Comment by DanTup** [comment]
Also - can you confirm if you hover over the Dart version in the status bar that it says "(Flutter)" and not "(Fuchsia)" (we don't support debugging Fuchsia apps, so if we're mis-detecting your app as Fuchsia then that might cause strange things).

**Comment by DanTup** [comment]
Ok, I can repro this - but, only if I try to start debugging within a few seconds of opening the project. If I wait a little, then it works. Is this what you're seeing? Does it only happen for a short period (a few seconds in my testing; but if your project is large maybe it's a little longer).

**Comment by mit-mit** [comment]
This was just happening on one of my machines, and found the cause in dev tools: It said the extension 2.6.2 version was being overridden by an old beta version of dart-code. After deleting that old beta version, and restarting everything works as expected!

**Comment by DanTup** [comment]
Aha! In previous versions of Code, the beta versions were handled quite badly and din't upgrade. In new versions, betas installed via vsix will just be treated similar to from the marketplace and upgrade cleanly once the next stable version goes out (I need to do some testing of this, but it's what the Code team have said).

So, I think that's a problem that won't occur going forwards and will only affect people that installed the old flutter beta vsix and didn't uninstall it. Hopefully this isn't many!

**Comment by DanTup** [comment]
Also - the issue I repro'd I think might be specific to the extension dev host (I had an issue about this in the past), but I'll try again today and if can repro in a normal Code instance, will raise a separate issue about that.
