### ISSUE TITLE
Imports are not updated automatically when moving a file

### ISSUE THREAD

**Issue by sue71** [Dart-Code/Dart-Code#4771]
**Describe the bug**

Import path does not changed even though we change rename / move a file.

**To Reproduce**
1. Create new flutter project
2. Create directory files like bellow
<img width="308" alt="image" src="https://github.com/Dart-Code/Dart-Code/assets/2591432/7d7a46fc-6a5d-47b2-b189-269db85acc76">

4. Import lib_a.dart from main.dart
5. Move lib_a.dart into `libs` directory
<img width="329" alt="image" src="https://github.com/Dart-Code/Dart-Code/assets/2591432/f6bc9d92-9048-4658-aa29-440d0c861481">

6. The import path of lib_a.dart is not updated
<img width="447" alt="image" src="https://github.com/Dart-Code/Dart-Code/assets/2591432/a19f7fc6-1a00-4637-9495-8cbe08eccc32">

**Expected behavior**

The import path should be updated to new path.

**Screenshots**

See the repro

**Please complete the following information:**

 - Operating System and version:
   - Apple M2 Max, macOS 13.5
 - VS Code version: 
   - Version: mac 1.82.2
 - Dart extension version:
   - Dart Code extension: 3.74.0
   - Flutter extension: 3.74.0 (activated)
 - Dart/Flutter SDK version: 
   - Dart (3.1.2): /Applications/flutter/bin/cache/dart-sdk
   - Flutter (3.13.4): /Applications/flutter
 - Target device (if the issue relates to Flutter debugging): n/a

[Dart-Code-Log-2023-09-04 15-54-19.txt](https://github.com/Dart-Code/Dart-Code/files/12813414/Dart-Code-Log-2023-09-04.15-54-19.txt)

**Comment by sue71** [comment]
@DanTup The permission for file movement is reconfirmed, but the Refactoring confirmation dialog does not appear.

<img width="302" alt="image" src="https://github.com/Dart-Code/Dart-Code/assets/2591432/59067460-4b58-4d2b-8993-19d1992a2ed7">

**Comment by DanTup** [comment]
That's odd - do you know if this works for any other of your languages? In your log file, there was no indication that VS Code called the Dart server for the rename so if this feels like a VS Code bug if you're not prompted after resetting.

If you create a temporary profile in VS Code and then test it in there, do you get any different behaviour? The temporary profile will have its own data store so won't be affected by any existing settings or dialogs you've clicked.

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/1a1dc9b3-bff5-4484-a3a4-e76b3c1bedf6)
