### ISSUE TITLE
Autocomplete suggests private fields from other files that cannot be accessed by the language rules

### ISSUE THREAD

**Issue by incendial** [Dart-Code/Dart-Code#4772]
**Describe the bug**
<img width="582" alt="Screenshot 2023-10-05 at 15 37 25" src="https://github.com/Dart-Code/Dart-Code/assets/21116742/32dabea5-ebbe-40f0-bb71-51d9c551cb58">

<img width="803" alt="Screenshot 2023-10-05 at 15 40 06" src="https://github.com/Dart-Code/Dart-Code/assets/21116742/3ab94c4f-81e6-4bfc-88d0-932bb2216c77">

**To Reproduce**
1. Create 2 classes (each in its own file) with static const fields that have the same name
2. Start typing the name of this field in one of the files

**Workspace Environment**

```text
Dart Code extension: 3.74.0

App: Visual Studio Code
App Host: desktop
Version: mac 1.82.3

Workspace type: Dart (LSP)

Dart (3.2.0-134.1.beta): /Users/dimannich/Desktop/flutter/bin/cache/dart-sdk
Flutter (3.15.0-15.2.pre): /Users/dimannich/Desktop/flutter

```

</details>

**Comment by DanTup** [comment]
I don't seem to be able to repro this - can you provide a code sample that causes it, or some more information about how these items are declared that might help me trigger it? Thanks!

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/363770a5-9e48-48e0-b0eb-7d9db4c11d7b)

**Comment by DanTup** [comment]
nm, I missed the word `static` 😁

**Comment by DanTup** [comment]
https://dart-review.googlesource.com/c/sdk/+/329605

**Comment by DanTup** [comment]
Fixed via https://github.com/dart-lang/sdk/commit/ae78a3d8e59907332ef682bd5dcf8b34612b2abc

The fix is in the Dart analysis server so it'll ship in a future Dart/Flutter SDK (not Dart-Code update).
