### ISSUE TITLE
Test results panel is broken

### ISSUE THREAD

**Issue by incendial** [Dart-Code/Dart-Code#4777]
**Describe the bug**
Not sure whether it's a VS Code bug or not and I found it by a missclick on the "run tests" button.

https://github.com/Dart-Code/Dart-Code/assets/21116742/168cfc03-dc06-4b68-8f43-f0c9b6c7d703

**Workspace Environment**

```text
Dart Code extension: 3.74.0

App: Visual Studio Code
App Host: desktop
Version: mac 1.83.0

Workspace type: Dart (LSP)

Dart (3.2.0-134.1.beta): /Users/dimannich/Desktop/flutter/bin/cache/dart-sdk
Flutter (3.15.0-15.2.pre): /Users/dimannich/Desktop/flutter

```

**Comment by DanTup** [comment]
This panel is normally in a peek popup, or at the bottom. The left side is where the output shows for the selected test:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/ce4eb349-51d8-4dac-bdca-798412ec171e)

I think the confusion here is just because it's been moved to the sidebar?

**Comment by DanTup** [comment]
@incendial let me know if you think there's anything to do here. I feel like the panel is just in a bad place and the VS Code UI isn't great when it's this narrow. I don't think anything is actually broken, or there's anything Dart-Code can do about this?

**Comment by incendial** [comment]
@DanTup sure, if you don't control the content of this panel (ex. can't react to the size of the container) or can't allow it to be only in the horizontal mode, then looks like nothing can be done here.

**Comment by DanTup** [comment]
That's correct - we have zero influence (or knowledge) of this panel - we just record VS Code test results (and output) via an API and all the UI is built by VS Code from that data.
