### ISSUE TITLE
The Flutter Daemon failed to start.

### ISSUE THREAD

**Issue by IgorGomesFATEC** [Dart-Code/Dart-Code#4779]
When I start flutter or open a flutter project with visual studio code, the flutter daemon does not start. And my devices won't charge

normally it already checks when starting VSCODE

![image](https://github.com/Dart-Code/Dart-Code/assets/43591315/350833f3-7f97-4bad-a8bc-c522a5cd451a)
![image](https://github.com/Dart-Code/Dart-Code/assets/43591315/fa50e142-de85-4c93-b317-b6c8c7d0e282)

**Comment by DanTup** [comment]
Can you post the contents of the file that opens when you click "Show Log"? Thanks!
