### ISSUE TITLE
No device is detected.

### ISSUE THREAD

**Issue by moqsien** [Dart-Code/Dart-Code#4781]
**Describe the bug**
No device is detected.
However, "flutter doctor -v" works perfectly.

```bash
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[!] Flutter (Channel @upstream, 3.10.6, on Microsoft Windows [版本 10.0.22621.2283], locale zh-CN)
    • Flutter version 3.10.6 on channel @upstream at C:\Users\moqsien\.gvc\flutter_files\flutter
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    • FLUTTER_GIT_URL = https://mirrors.tuna.tsinghua.edu.cn/git/flutter-sdk.git
    • Framework revision f468f3366c (3 months ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\moqsien\.gvc\flutter_files\android_home
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\moqsien\.gvc\flutter_files\android_home
    • Java binary at: C:\Users\moqsien\.gvc\java_files\java\bin\java
    • Java version Java(TM) SE Runtime Environment (build 17.0.4.1+1-LTS-2)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33627.172
    • Windows 10 SDK version 10.0.22000.0
    ✗ Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.83.0)
    • VS Code at C:\Users\moqsien\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.74.0

[✓] Connected device (4 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • Windows (desktop)          • windows       • windows-x64    • Microsoft Windows [版本 10.0.22621.2283]
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 117.0.5938.134
    • Edge (web)                 • edge          • web-javascript • Microsoft Edge 117.0.2045.60

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

**To Reproduce**
1. Install Flutter
2. Install android sdk
3. Create an AVD
4. Check the vscode status bar

**Expected behavior**
Flutter devices should be found on status bar.
But actually nothing happened.

**Screenshots**
![flutter_bugs](https://github.com/Dart-Code/Dart-Code/assets/34511192/97e74867-14c2-4a11-981e-b95bd587e47c)

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

 - Operating System and version: Windows11
 - VS Code version: 1.83.0
 - Dart extension version: 3.0.6
 - Dart/Flutter SDK version: 3.10.6
 - Target device (if the issue relates to Flutter debugging): android emulator
 
**I also tried the latest version of Dart/Flutter SDK(3.13.6), but nothing worked.**

**Comment by DanTup** [comment]
Can you try:

1. First, run the **Flutter: Run Flutter Doctor** command from the VS Code command palette (`F1`) and post the output (note: this might behave slightly differently to running in the terminal)
2. Second, close all instances of VS Code and re-launch VS Code from a terminal (with the `code` command) and confirm whether the devices are detected or not when launched from there

**Comment by moqsien** [comment]
> Can you try:
> 
> 1. First, run the **Flutter: Run Flutter Doctor** command from the VS Code command palette (`F1`) and post the output (note: this might behave slightly differently to running in the terminal)
> 2. Second, close all instances of VS Code and re-launch VS Code from a terminal (with the `code` command) and confirm whether the devices are detected or not when launched from there

Thank you very much for the suggestions.
I've just found the problem solved after enable the Hyper-V feature for windows.
