### ISSUE TITLE
Debug toolbar icons don't render correctly since last VS Code update

### ISSUE THREAD

**Issue by ucpritam** [Dart-Code/Dart-Code#4782]
Suddenly I am noticing that hot reload icon on debug control panel is broken. 

![Screenshot 2023-10-09 at 3 17 27 PM](https://github.com/Dart-Code/Dart-Code/assets/54333597/fb7d559a-e6d5-4092-8de7-2cf711100db8)

**Comment by DanTup** [comment]
This appears to be a VS Code bug - please add 👍 's to https://github.com/microsoft/vscode/issues/194710

**Comment by Reprevise** [comment]
@DanTup is that VS Code issue also causing the icons in pubspec.yaml to appear enlarged?
![image](https://github.com/Dart-Code/Dart-Code/assets/25782944/8168db13-cc91-4d19-82a4-1dd2d8020bf9)

**Comment by DanTup** [comment]
@Reprevise I expect so - because of the mask, anything that was previously a feathered edge is now solid so things look thicker.

**Comment by DanTup** [comment]
VS Code 1.83.1 has shipped with a fix for this:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/70f8cf99-7823-4b3d-8bd7-2d6146155396)

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/82eff6e4-50d6-4718-ab6e-ddf404c543c4)

**Comment by Reprevise** [comment]
I know this was an issue but I did enjoy having the pubspec buttons being the same color as the built-in ones so if that's possible to have in the future it'd be great.
![image](https://github.com/Dart-Code/Dart-Code/assets/25782944/2cd3492a-2ee2-450c-8744-9f6a796e0c31)

**Comment by DanTup** [comment]
>  I did enjoy having the pubspec buttons being the same color as the built-in ones 

It might be in future. That was kind-of the problem - they were trying to apply the theme colour to them. Hopefully in future we can use the theme colour inside the SVG without a) it being forced upon us or b) used as a mask that messes up the icon :-)
