### ISSUE TITLE
The move to a file new feature sometimes breaks the lsp.

### ISSUE THREAD

**Issue by HoussemBousmaha** [Dart-Code/Dart-Code#4783]
In Flutter, Creating a Simple Stateless widget and then moving it to its own file. sometimes breaks the lsp (or dart analyzer something). and have to restart vscode for fix it.

**Comment by DanTup** [comment]
> sometimes breaks the lsp (or dart analyzer something)

Can you provide more details about the problem you're seeing? Is there an error message? If so, does it have a "Show Log" button that might include more information about the error?
