### ISSUE TITLE
Renaming files does not update `part` or `part of` URIs

### ISSUE THREAD

**Issue by BenedictWilkins** [Dart-Code/Dart-Code#4784]
I am using `build_runner` to generate some dart code. It produces `.part` files which should be included in a given dart file with the `part` directive. 

For example I have a file `main.dart`, and a generated file `main.logger.g.part`.

In `main.dart` I must include the line: `part main.logger.g.part`

and in `main.logger.g.part` I must include the line: `part of main.dart`.

Unlike with the `import` directive, these lines are not changed upon renaming `main.dart`. 
This would be a very useful feature for anyone using `build_runner` or `source_gen` or who is otherwise using the `part` directive.

**Comment by DanTup** [comment]
Can you provide a sample project set up this way where you're seeing this issue? The move file refactor is expected to update `part` and `part of` (and there are [some tests](https://github.com/dart-lang/sdk/blob/2cbb5eabca94ef7a2397bcd7844abad8ba9ca679/pkg/analysis_server/test/services/refactoring/legacy/move_file_test.dart#L23) that include them) so you might be hitting some specific case where this isn't handled.

Thanks!
