### ISSUE TITLE
When extract locale variable, can't name with same name of parameter

### ISSUE THREAD

**Issue by lsaudon** [Dart-Code/Dart-Code#4787]
**Describe the bug**
When extract locale variable, can't name with same name of parameter

**To Reproduce**
1. With this code:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
      ),
    );
  }
}
```
2. Extract locale variable for `AppBar()`
3. The variable is `appBar2` or with prompt if I set `appBar`, I have this error `The name 'appBar' is already used in the scope.`

**Expected behavior**
I want name variable `appBar`

**Please complete the following information:**

 - Operating System and version: macOS 14.0
 - VS Code version: 1.83.0
 - Dart extension version: 3.74.0
 - Dart/Flutter SDK version: Dart 3.1.3/Fluttter 3.13.6

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/209483da72f7c63f7135a6a064bb76986c6f2e05.

The fix is in the Dart analysis server which is included in the SDK, so the fix will show up in a future SDK update rather than a Dart VS Code extension update.
