### ISSUE TITLE
Type label in autocomplete is not displayed for record fields

### ISSUE THREAD

**Issue by incendial** [Dart-Code/Dart-Code#4788]
**Describe the bug**
When typing a record field in the editor, the autocomplete menu does not show the type of suggest fields:
![image](https://github.com/Dart-Code/Dart-Code/assets/21116742/893c6452-3f03-476f-b2a4-a33154b50f1c)

**Please complete the following information:**

Dart Code extension: 3.74.0

App: Visual Studio Code
App Host: desktop
Version: mac 1.83.0

Workspace type: Dart (LSP)

Dart (3.2.0-134.1.beta): /Users/dimannich/Desktop/flutter/bin/cache/dart-sdk
Flutter (3.15.0-15.2.pre): /Users/dimannich/Desktop/flutter

**Comment by DanTup** [comment]
Good spot - fix open at https://dart-review.googlesource.com/c/sdk/+/330107. Ships in the SDK. Thanks!

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/9e753794cbeb2aa8b1ef6ff1298097c4c5372a0a. The fix is in the Dart analysis server so will ship in a future Dart/Flutter SDK (not a Dart-Code update).
