### ISSUE TITLE
XHR EROR

### ISSUE THREAD

**Issue by AnggaH15** [Dart-Code/Dart-Code#4791]
Type: <b>Bug</b>

Eror while fetching extensions.XHR failed

Extension version: 3.74.0
VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz (4 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|3.77GB (0.36GB free)|
|Process Argv|--crash-reporter-id 12a78f2a-e7be-4fc5-b0e0-4c64ccdbcfe5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontb:30265425
vspre833cf:30267465
vsfjg287:30275553

```

</details>

**Comment by DanTup** [comment]
> Eror while fetching extensions
> XHR failed

This seems like a VS Code issue. Fetching of extensions is all done by VS Code itself and not by extensions. There's an open issue at https://github.com/Microsoft/vscode/issues/34385 that seems to match this - please try some of the suggestions posted in there.
