### ISSUE TITLE
Make it easy to navigate to Flutter Web Documentation 

### ISSUE THREAD

**Issue by osaxma** [Dart-Code/Dart-Code#4793]
**Is your feature request related to a problem? Please describe.**
Flutter uses documentation macros quite heavily. Some of these macros are rendered by the VS Code extension, while others are not possible to render (e.g. DartPad embedding and YouTube Video). 

**Describe the solution you'd like**
Whenever flutter presents such macros that aren't possible to render, provide a URL to navigate to the web documentation.

**Describe alternatives you've considered**
I have to search for manually search for the documentation.

**Additional context**
Here's an example documentation for InteractiveViewer:
1- Web Version -> https://api.flutter.dev/flutter/widgets/InteractiveViewer-class.html
2- Raw Version: 
  ```dart
  /// A widget that enables pan and zoom interactions with its child.
  ///
  /// {@youtube 560 315 https://www.youtube.com/watch?v=zrn7V3bMJvg}
  ///
  /// The user can transform the child by dragging to pan or pinching to zoom.
  ///
  /// By default, InteractiveViewer clips its child using [Clip.hardEdge].
  /// To prevent this behavior, consider setting [clipBehavior] to [Clip.none].
  /// When [clipBehavior] is [Clip.none], InteractiveViewer may draw outside of
  /// its original area of the screen, such as when a child is zoomed in and
  /// increases in size. However, it will not receive gestures outside of its original area.
  /// To prevent dead areas where InteractiveViewer does not receive gestures,
  /// don't set [clipBehavior] or be sure that the InteractiveViewer widget is the
  /// size of the area that should be interactive.
  ///
  /// The [child] must not be null.
  ///
  /// See also:
  ///   * The [Flutter Gallery's transformations demo](https://github.com/flutter/gallery/blob/master/lib/demos/reference/transformations_demo.dart),
  ///     which includes the use of InteractiveViewer.
  ///   * The [flutter-go demo](https://github.com/justinmc/flutter-go), which includes robust positioning of an InteractiveViewer child
  ///     that works for all screen sizes and child sizes.
  ///   * The [Lazy Flutter Performance Session](https://www.youtube.com/watch?v=qax_nOpgz7E), which includes the use of an InteractiveViewer to
  ///     performantly view subsets of a large set of widgets using the builder constructor.
  ///
  /// {@tool dartpad}
  /// This example shows a simple Container that can be panned and zoomed.
  ///
  /// ** See code in examples/api/lib/widgets/interactive_viewer/interactive_viewer.0.dart **
  /// {@end-tool}
  ```
3- VS Code Hover:
<img width="870" alt="Screen Shot 2023-10-16 at 2 22 42 AM" src="https://github.com/Dart-Code/Dart-Code/assets/46427323/9d50dcc4-2a1e-4fcb-8320-8224921eb9b5">

I just realized that the `@youtube` macro is already replaced by a YouTube link. It would be handy if something similar can be done to `{@tool dartpad}` and others. A link to the web docs there would be ideal.

... or a generic link on all hovers somewhere with something like: `view on flutter.dev` as another idea in case there are many edge cases for parsing macros.

**Comment by DanTup** [comment]
I agree we could do better here, although there's not an obvious way to figure out the URL of the docs for what you're looking at. I suspect special casing just Dart and Flutter SDKs would probably still be a good step though.

There's an existing issue at https://github.com/Dart-Code/Dart-Code/issues/1571 so let's close this in in favour of that.
