### ISSUE TITLE
Autocomplete doesn't work properly with enums when using named imports

### ISSUE THREAD

**Issue by osaxma** [Dart-Code/Dart-Code#4794]
**Describe the bug**

When using named imports, auto completing enum doesn't show the value but prompt to insert a switch condition as shown below: 

**To Reproduce**

<img width="1014" alt="Screen Shot 2023-10-16 at 7 11 11 PM" src="https://github.com/Dart-Code/Dart-Code/assets/46427323/899686cf-9b72-4461-a0f8-4f17c99890e5">

```dart
import 'dart:ui' as ui;

void main() {
  final x = ui.BlendMod  // <~~ auto complete here
}
```

**Expected behavior**

I expect the enum values to be shown 

**Please complete the following information:**
Extension version: v3.74.0
VS Code version: 1.83.1
Flutter 3.13.6 • channel stable • 
Dart 3.1.3 • DevTools 2.25.0

**Comment by DanTup** [comment]
One of these is easier to fix than the other, so splitting the switch expression part out to https://github.com/Dart-Code/Dart-Code/issues/4795.

**Comment by jamesderlin** [comment]
Also see https://stackoverflow.com/q/77873381/ which describes a similar problem for `static` methods when using named imports.

**Comment by DanTup** [comment]
It appears that this has been resolved now:

![image](https://github.com/user-attachments/assets/6deb6c0e-2355-4cc2-9371-01535a5fe01e)

![image](https://github.com/user-attachments/assets/7149fc24-62b2-4c80-82e1-536e68d6d9f2)
