### ISSUE TITLE
Breakpoints in Packages are not always hit

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#481]

**Comment by DanTup** [comment]
Possibly related: https://github.com/Microsoft/vscode/issues/40662

**Comment by DanTup** [comment]
SDK ones are not working due to leading slashes when setting breakpoints (`/dart:core/print`) and packages are not working because of a string comparison on paths (`startsWith`) that is case-sensitive on Windows (and we have upper vs lowercase drive letters depending on where they came from).

**Comment by DanTup** [comment]
There are still issues depending on how you set the breakpoing (F12 to open definition via analyzer versus doing it at debug time).

This is because if you F12 into a file then add a breakpoint, Code records it as the file system path. If we step into it at runtime, then the debugger reports it as `dart:core`, `package:whatever`.

I think the sensible thing is for is to never give things like `dart:core` and `package:test` to Code, but always map to fs paths, except for the display name in the call stack. Otherwise, Code will never know that `dart:core/print.dart` is the same as `M:\Dart\Latest\blah\print` are the same? That said, how will this place with source downloaded from the VM? @devoncarew - any thoughts on this? I've found there are many bugs in breakpoints/stacks right now (there are many permutations -> #480!)

**Comment by escamoteur** [comment]
This is an extremely annoying problem especially if you develop packages yourself and you try them in a separate project.

**Comment by DanTup** [comment]
@escamoteur I'm going to try and fix this for packages in the next version (after v2.12). If you can provide a good repro I can use it'd help. I've split SDK breakpoints out to #281 so this case is just for packages (which I believe should be easy to fix, it's SDK sources that are complicated).

**Comment by DanTup** [comment]
@escamoteur Are you able to easily repro this?

**Comment by escamoteur** [comment]
Last I tried it seemed to be fixed. Will observe

**Comment by DanTup** [comment]
Closing this was not-repro; but if you see it again let me know. I do now have some basic tests that breakingpoints and stepping work correctly in packages, but I can extend them if we find further issues.
