### ISSUE TITLE
Add feature to search for named parameters of constructor with go to referenecs

### ISSUE THREAD

**Issue by nero-angela** [Dart-Code/Dart-Code#4810]
### Background
Naming parameters implemented as `this` in the constructor are not searchable in `Go to references`.
Therefore, in order to check whether a specific property is being passed through the constructor or not, one must check all constructor functions directly.

### Example1
If the initial value of a property is passed as `this` in the named parameter of a constructor function, the named parameter of the external constructor will not be searched when searching for the property with `go to references`. (Please refer to the image below.)
```dart
class Person {
  final int? age;

  const Person({
    this.age, // 👈 this
  });

  @override
  String toString() => '$age';
}
```
<img width="1091" alt="image" src="https://github.com/Dart-Code/Dart-Code/assets/26322627/c0505607-6e43-4667-b051-6359e40e83cf">

### Example2
If a constructor named parameter is passed to a property without using `this` as shown below, when calling `go to references` on the constructor naming parameter, the naming parameter passed from the external constructor is also searched.
```dart
class Human {
  final int? age;

  const Human({
    int? age, // 👈 new variable
  }) : age = age ?? 1;

  @override
  String toString() => '$age';
}
```
<img width="1263" alt="image" src="https://github.com/Dart-Code/Dart-Code/assets/26322627/3b711a66-21b3-43c3-a9c1-e81c145a59d5">

### Request
If the Example2 method is used, searching with `Go to references` is possible, but the Example1 code is much shorter and simpler and is often used.

Is it possible to use `Go to references` in example1’s code?

### Sample Code
- `person.dart`
  ```dart
  class Person {
    final int? age;
  
    const Person({
      this.age,
    });
  
    @override
    String toString() => '$age';
  }
  
  class Human {
    final int? age;
  
    const Human({
      int? age,
    }) : age = age ?? 1;
  
    @override
    String toString() => '$age';
  }
  ```

- `main.dart`
  ```dart
  import 'person.dart';
  
  void main() {
    /// 🔴 Go to references
    Person(age: 1);

   /// 🟢 Go to references
   Human(age: 1);
  }
  ```

### Test Environment
```
Flutter 3.13.8 • channel [user-branch] • unknown source
Framework • revision 6c4930c4ac (6 days ago) • 2023-10-18 10:57:55 -0500
Engine • revision 767d8c75e8
Tools • Dart 3.1.4 • DevTools 2.25.0
```

**Comment by DanTup** [comment]
In the second example, you're performing "Go to References" on the constructor parameter, not on the field. If you do the same for the first example it also includes the constructor calls.

Here, I invoked Go to References on `age` on line 4 and it showed the calls on line 8 + 9. This seems to match the behaviour of your second example:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/eff0e7db-8f02-4f1a-9695-b688acde6afb)

In the first example you invoked the command on the field and not the constructor parameter, but the constructor calls do not have references to the _fields_, only to the parameters in the constructor (although using the `this` syntax makes this distinction a little less clear).

It's worth noting when I was testing this, I found some odd behaviour where references wouldn't work correctly on some constructor calls - I've filed https://github.com/dart-lang/sdk/issues/53839. I don't know if you were also seeing the effects of this though.

Please let me know if anything isn't clear or you still think there's an issue here.

**Comment by nero-angela** [comment]
Due to a VSCode custom shortcut issue, `Go to definition` was executed instead of `Go to references` in case 1, so I mistook the problem. Since there is no problem, I will close the issue. thanks!

**Comment by nero-angela** [comment]
Additionally, the above problem occurs in Flutter 3.10.7, but confirmed that it works without a problem in Flutter 3.13.8 👍
