### ISSUE TITLE
Fix all does not work on part of files.

### ISSUE THREAD

**Issue by nero-angela** [Dart-Code/Dart-Code#4813]
## Reproduce
1. Turn on the fix all option when saving in VSCode.
2. Create the `main.dart` file and `sub.dart` file using dart’s `part` & `part of` syntax as follows.
    - main.dart
    ```dart
    import 'package:flutter/material.dart';
    
    part 'sub.dart';
    
    void main() {
      runApp(const Sub());
    }
    ```
    - sub.dart
    ```dart
    part of 'main.dart';
    
    class Sub extends StatelessWidget {
      const Sub({super.key});
    
      @override
      Widget build(BuildContext context) {
        return Column(
          children: [
            SizedBox(), /// 👈 Use 'const' with the constructor to improve performance.
          ],
        );
      }
    }
    ```
3. Even if you save in the `sub.dart` file, fix all does not work, so `const` is not added before `SizedBox()`.
4. If you save in the `main.dart` file, fix all will work in the sub.dart file.

## Expected
I think even if saved in the `sub.dart` file, `const` must be added in front of `SizedBox()`.

## Video
https://github.com/Dart-Code/Dart-Code/assets/26322627/14a06d70-01dc-41e1-9969-4712cd8fddd0

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/28456ae71633376f1f1eed2b619f578bb8d8c536

The change is in the Dart analysis server so will show up in a future Dart/Flutter SDK release (not a VS Code extension release).

**Comment by whesse** [comment]
Does this fix also fix this error in Flutter tests?
```
Error from the analysis server: Exception while getting bulk fixes: type 'NotLibraryButPartResult' is not a subtype of type 'ParsedLibraryResult' in type cast
| #0      BulkFixProcessor._computeChangesToPubspec (package:analysis_server/src/services/correction/bulk_fix_processor.dart:373:13)
| #1      BulkFixProcessor.fixPubspec (package:analysis_server/src/services/correction/bulk_fix_processor.dart:284:7)
| #2      EditBulkFixes.handle (package:analysis_server/src/handler/legacy/edit_bulk_fixes.dart:56:38)
| #3      LegacyAnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/legacy_analysis_server.dart:559:25)
```
https://github.com/flutter/flutter/issues/137298
