### ISSUE TITLE
"Open DevTools in browser" doesn't work

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#4832]
While working on #4821 I found that the browser window isn't actually opening. It's not just from the sidebar, the same happens when running the "Open DevTools" command then selected "Open in External Browser".

**Comment by DanTup** [comment]
Cannot reproduce after a restart :/

**Comment by DanTup** [comment]
The sidebar is showing up as a connected client, but it's marked as not embedded so we're trying to reuse it. 

We are passing it on the querystring, so it must not be being passed through somewhere.

```js
{
	"event": "client.launch",
	"params": {
		"reused": true,
		"notified": true,
		"pid": null,
		"extra": {
			"reusableClient": {
				"currentPage": "simple",
				"embedded": false, // This is wrong
				"hasConnection": false,
				"vmServiceUri": null
			}
		}
	}
}
```

**Comment by DanTup** [comment]
There's something odd happening here - when we load the sidebar, it appears that DevTools is creating the not-found page also. If I log the registration of the client to the server, it sends a not-found as the page:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/5b6c53c9-d6c2-43b7-ab8a-4ad47584ae6f)

**Comment by DanTup** [comment]
@kenzieschmoll FYI in case you have any ideas about what might be happening here that might save me some debugging.

Seems like there's something weird when loading standalon screens.. If I run DevTools from source and navigate to the sidebar (eg. "http://localhost:55987/vsCodeFlutterPanel") I can trigger a breakpoint on the not-found widget above. The stack trace isn't very helpful but it seems like we go via `DevToolsRouterDelegate -> build -> _getPage()` to end up doing this. I can't figure out how we're building a not-found page that isn't being rendered anywhere though.

(my original issue is that this not-found page is being registered with the server without its embed flag so I can probably fix that so the embed flag is working correctly, but it feels like something is wrong that we're generating this page)

**Comment by kenzieschmoll** [comment]
I think this is a race condition and the first load of the routing logic is happening before the router is completely set up. I wonder if there is something else we can check here to prevent us from reaching the "not found" page: https://github.com/flutter/devtools/blob/master/packages/devtools_app/lib/src/app.dart/#L207

**Comment by DanTup** [comment]
Turns out there were a few different issues here:

1. Rendering not-found initially - fix is in https://github.com/flutter/devtools/pull/6724
2. Standalone screens not sending a `currentPage` event, so once (1) is fixed, the clients connect to the server but never tell it whether they're embedded or not (because that's sent in the `currentPage` request) - TODO added in https://github.com/flutter/devtools/pull/6724
3. The DevTools server treated newly-connected clients as reusable when we'd never been sent an `embedded` flag - fix is in https://dart-review.googlesource.com/c/sdk/+/336041 which adds a flag to indicate whether we've ever been sent a page

**Comment by DanTup** [comment]
This was fixed in DevTools and the SDK by https://github.com/dart-lang/sdk/commit/c74ea634cb5d82d699edb2c7adde4cc2d516022d and https://github.com/dart-lang/sdk/commit/c74ea634cb5d82d699edb2c7adde4cc2d516022d
