### ISSUE TITLE
`required` keyword on lambda suggestion

### ISSUE THREAD

**Issue by FMorschel** [Dart-Code/Dart-Code#4834]
**Is your feature request related to a problem? Please describe.**
I have the following class in my Flutter project:

```dart
class DataRowCubit<T> extends Cubit<List<DataRow>> {
  DataRowCubit({
    required DataRow Function({
      required bool selected,
      required T data,
      required int index,
      // ignore: avoid_positional_boolean_parameters, single parameter
      required void Function(bool?) onSelectionChanged,
    }) dataRow,
    void Function({
      required bool? selection,
      required int index,
      required List<bool> list,
    })? onSelectionChanged,
    List<T>? list,
  })
//...
```
But when I write down the constructor to create a new instance, the suggested fillings for the lambdas are the following:

![image](https://github.com/Dart-Code/Dart-Code/assets/52160996/c3983ed7-b34b-4ad5-8990-3eb4f706081f)

This creates a minor inconvenience that I then need to write down the `required`s myself in all of the non-null parameters:

![image](https://github.com/Dart-Code/Dart-Code/assets/52160996/c1c43df3-04c4-4e7d-a099-d4803f539cb7)

**Describe the solution you'd like**
I would like for the suggested code to follow the `required` keyword.

**Comment by DanTup** [comment]
Working on a fix at https://dart-review.googlesource.com/c/sdk/+/336021 

https://github.com/Dart-Code/Dart-Code/assets/1078012/5b038668-dedb-4dc4-a22e-8e50c45aee87

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/4dddc98fc6bce8c332f77572044814f19d2012f5 - will in a future SDK (not Dart-Code) release.
