### ISSUE TITLE
Support opening DevTools extensions from the sidebar

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#4835]
In the past we've had a lot of assumptions about which pages we can open and I'm not sure where they still exist. We need to be able to open extensions in DevTools which will have IDs unknown to us (see https://github.com/flutter/devtools/pull/6709).

There might be nothing to do, but it'll definitely need some testing and reviewing of the code.

- [ ] If changes are required, add a capability so DevTools/sidebar knows it can do this.

**Comment by kenzieschmoll** [comment]
Closing this, since the code to show extension screens in the sidebar has landed. I filed a new issue to track supporting opening extensions as embedded views instead of only in the browser: https://github.com/Dart-Code/Dart-Code/issues/4952
