### ISSUE TITLE
`Use imported library with prefix` quick fix puts the prefix at the wrong position

### ISSUE THREAD

**Issue by mosuem** [Dart-Code/Dart-Code#4836]
**Describe the bug**
`Use imported library with prefix` quick fix puts the prefix at the wrong position.

**To Reproduce**
1. Create new project
2. Insert `import 'dart:ffi' as ffi;`
3. Type `@Native`
4. Get the quickfix `Use imported library 'dart:ffi' with prefix 'ffi'`
5. The prefix `ffi.` is placed _before_ the `@`, resulting in a syntax error

**Expected behavior**
5. Should be placed _after_ the `@`

**Please complete the following information:**

```text
Dart Code extension: 3.77.20231111
Flutter extension: 3.76.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: linux 1.82.2

Workspace type: Dart (LSP)

Dart (3.3.0-edge.de9494ae0703ba877e967cf8c6f1083b0b3d5d60): /home/mosum/dart-sdk/sdk/out/ReleaseX64/dart-sdk
```

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/467bd633c488ff7092d0d5108839e9572b13f6cd. Ships in the SDK!
