### ISSUE TITLE
Completion does not suggest function structure Flutter 3.16

### ISSUE THREAD

**Issue by quyenvsp** [Dart-Code/Dart-Code#4845]
**Describe the bug**
Completion does not suggest function structure Flutter 3.16, on Flutter 3.13 working fine.

**To Reproduce**
1. Write `LayoutBuilder(builder: )`

**Expected behavior**
Function structure `(context, constraints) => ` should in first place.

**Screenshots**
Flutter 3.16 not working
![2023-11-20_163626](https://github.com/Dart-Code/Dart-Code/assets/35319492/e5930759-7abf-4666-b18b-fd19a5b08d93)

Flutter 3.13 working
![2023-11-20_163554](https://github.com/Dart-Code/Dart-Code/assets/35319492/0db4a2f2-afdc-4858-9bd9-40e268525abe)

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

 - Operating System and version: windows 11
 - VS Code version: 1.84.2
 - Dart extension version: v3.76.1
 - Dart/Flutter SDK version: 3.2.0 / 3.16.0

**Comment by DanTup** [comment]
Thanks for the report! This is the same issue as https://github.com/Dart-Code/Dart-Code/issues/4837 which has been fixed recently.

**Comment by quyenvsp** [comment]
I am writing this for future if need or other people who want build dart sdk yourself

https://github.com/dart-lang/sdk/wiki/Building#dependencies

Windows

```
mkdir dart-sdk
cd dart-sdk
# On Windows, this SHOULD NOT to be run in a shell with Administrator rights.
fetch dart

cd sdk
git checkout 3.2.0
git cherry-pick 28d9ac0
gclient sync

python3 .\tools\build.py --no-goma --mode release --arch x64 create_sdk

mv .\out\ReleaseX64\dart-sdk\bin\snapshots\analysis_server.dart.snapshot %FLUTTER_HOME%\bin\cache\dart-sdk\bin\snapshots\
```
