### ISSUE TITLE
In the new version vscode auto complete stopped working

### ISSUE THREAD

**Issue by eduardohr-muniz** [Dart-Code/Dart-Code#4846]
With the new version of flutter, vscode suggestions stopped working, as shown in the examples below

**OLD VERSION**
![Imagem do WhatsApp de 2023-11-20 à(s) 10 30 27_72679e90](https://github.com/Dart-Code/Dart-Code/assets/90477293/cfdb0f33-7e5e-45be-8df8-8c2343303287)
----------------------------------------------------
**NEW VERSION**
![image](https://github.com/Dart-Code/Dart-Code/assets/90477293/24459732-ff74-48aa-ab19-07988a4dac0f)

**Comment by DanTup** [comment]
Thanks for the report! This is the same issue as https://github.com/Dart-Code/Dart-Code/issues/4837 which has been fixed recently.

**Comment by eduardohr-muniz** [comment]
I didn't understand very well, has it already been corrected?

If it was, it still has the bug, the print is from today

**Comment by DanTup** [comment]
@eduardohr-muniz sorry, I didn't explain very well. I committed a fix to the Dart SDK recently, but it won't ship until the next Dart/Flutter SDK release.

Unfortunately I don't have a quick workaround.

**Comment by quyenvsp** [comment]
@eduardohr-muniz you can simple build analysis_server yourself https://github.com/dart-lang/sdk/wiki/Building#dependencies

```
git checkout 3.2.0
git cherry-pick 28d9ac0
```
then build and replace `analysis_server.dart.snapshot` at [flutter_folder]\bin\cache\dart-sdk\bin\snapshots\
tried and all working fine.

**Comment by U-MINDERS-TECH** [comment]
bro i don't understand can you contact me on whatsapp 03369353308
