### ISSUE TITLE
VS code auto completion for function not working

### ISSUE THREAD

**Issue by Shreemanarjun** [Dart-Code/Dart-Code#4848]
**Describe the bug**
Auto completion is not working after upgrading to flutter 3.16 or dart 3.2 in VS code. But in android studio it is working good.

**To Reproduce**

1. Create a call back function
2. Try to auto complete by ctrl + space bar
3. It will show widgets not the completion with function with parameters in it

**Expected behavior**
Auto complete for functions should show function signature as required with all the paramters

**Screenshots**
<img width="644" alt="Screenshot 2023-11-20 at 11 30 45 PM" src="https://github.com/Dart-Code/Dart-Code/assets/24736211/95d2fad0-2938-40d1-98be-c47cec3a3cf0">
<img width="710" alt="Screenshot 2023-11-20 at 11 30 56 PM" src="https://github.com/Dart-Code/Dart-Code/assets/24736211/313f0db9-b9a9-4dc4-8c59-b6a7f6da4db2">

**Please complete the following information:**
**!! ⚠️ PLEASE REVIEW THIS REPORT FOR SENSITIVE INFORMATION BEFORE SHARING ⚠️ !!**

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.76.1
Flutter extension: 3.76.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: mac 1.84.2

Workspace type: Flutter (LSP)

Dart (3.2.0): /Users/***/fvm/versions/stable/bin/cache/dart-sdk
Flutter (3.16.0): /Users/***/fvm/versions/stable (macOS (darwin/macos))

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`/Users/***/fvm/versions/stable/bin/cache/dart-sdk/bin/dart info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.2.0 (stable) (Tue Nov 14 18:26:59 2023 +0000) on "macos_arm64"
- on macos / Version 14.1.1 (Build 23B81)
- locale is en-IN

#### Project info

- sdk constraint: '>=3.0.0 <4.0.0'
- dependencies: appinio_swiper, auto_route, auto_size_text, cached_network_image, device_preview, device_preview_screenshot, dio, dio_smart_retry, duration, equatable, flash, flex_color_scheme, flutter, flutter_animate, flutter_displaymode, flutter_form_builder, flutter_localizations, flutter_riverpod, flutter_secure_storage, form_builder_extra_fields, form_builder_validators, gap, hive_flutter, image_picker, internet_connection_checker_plus, intl, intl_phone_field, multiple_result, path_provider, pin_code_fields, platform_info, responsive_framework, talker_dio_logger, talker_flutter, velocity_x
- dev_dependencies: auto_route_generator, build_runner, custom_lint, flutter_lints, flutter_test, mocktail, package_rename, riverpod_lint, riverpod_test, very_good_analysis
- elided dependencies: 1

#### Process info

|  Memory |  CPU | Elapsed time | Command line                                                                    |
| ------: | ---: | -----------: | ------------------------------------------------------------------------------- |
| 1019 MB | 0.0% |        04:43 | dart --enable-vm-service=0 lib/custom_lint_client.dart ::1 51450                |
|   64 MB | 0.0% |        04:51 | dart devtools --machine --try-ports 10 --allow-embedding                        |
| 1285 MB | 0.0% |        04:51 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.76.1 |
|  133 MB | 0.4% |        04:51 | flutter_tools.snapshot daemon                                                   |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`/Users/***/fvm/versions/stable/bin/flutter doctor -v`

```text
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1.1 23B81 darwin-arm64, locale en-IN)
    • Flutter version 3.16.0 on channel stable at /Users/***/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (5 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/***/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • ANDROID_HOME = /Users/***/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.77.20231101

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.1.1 23B81 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 117.0.5938.132

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by DanTup** [comment]
Thanks for the report! There's an existing issue for this at https://github.com/Dart-Code/Dart-Code/issues/4837. The issue has been fixed recently but will require an SDK release.
