### ISSUE TITLE
code completion not available

### ISSUE THREAD

**Issue by stern0** [Dart-Code/Dart-Code#485]
I have started  using this extension with vscode but doesn't give the code completion feature intelliJ give, it actually gives none even after setting `editor.quickSuggestions` to:

```
   "editor.quickSuggestions": {
      "other": true,
      "comments": false,
      "strings": true // This defaults to false
    },
```

**Comment by DanTup** [comment]
Can you try opening the dev tools (Help -> Toggle Developer Tools) and see if there are any errors?

Also, if you [enable logging](https://github.com/Dart-Code/Dart-Code/blob/master/CONTRIBUTING.md#enable-logging) with the `dart.analyzerLogFile` setting, does it log anything useful?

**Comment by stern0** [comment]
I have enabled logging but that shows nothing.

The developer Tools shows an error of not finding the dart-sdk but I have given it the path to the dart-sdk in flutter `"/Users/apple/flutter/bin/cache/dart-sdk"`

**Comment by stern0** [comment]
it seems it was an issue of not finding the sdk, although I had both the official installer from homebrew and flutter.

**Comment by DanTup** [comment]
@stern0 Are you able to provide more details so I can try to improve this? I presume this is a flutter project that's not inside the Flutter repo? Dp you have `flutter` in your PATH or the `FLUTTER_HOME` environment variable set? If not, we will try to find `flutter` from the `.packages` file, so possible if you had not updated packages yet we would have run out of places to search.

If you think any of the above *should* have applied and we should've found it and you can repro this, I'd love to fix :-)
