### ISSUE TITLE
flutter suggestion problem

### ISSUE THREAD

**Issue by U-MINDERS-TECH** [Dart-Code/Dart-Code#4850]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

 - Operating System and version:
 - VS Code version:
 - Dart extension version:
 - Dart/Flutter SDK version:
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
@U-MINDERS-TECH can you provide some more details about the problem? Is it possible you intended to report https://github.com/Dart-Code/Dart-Code/issues/4837 with closures not appearing in code completion?

**Comment by U-MINDERS-TECH** [comment]
i have if i call the widget  like listview builder then i have not getting any suggestion to continue code its take more time so if you have any solution plz help me .
thank you 
![issue](https://github.com/Dart-Code/Dart-Code/assets/121817325/7438b709-5b22-4a57-ab96-8be598481e45)

**Comment by DanTup** [comment]
This is the same issue described in https://github.com/Dart-Code/Dart-Code/issues/4837.

It has recently been fixed but requires an SDK release. There is a cherry-pick request at https://github.com/dart-lang/sdk/issues/54112.

**Comment by U-MINDERS-TECH** [comment]
its mean you fix already this issue 
but what is the main issue i mean this issue by flutter extension

**Comment by DanTup** [comment]
> its mean you fix already this issue

Sorry, I wasn't very clear. I have made change in the Dart analyzer code to resolve the issue. However, that change is not yet released.


> but what is the main issue i mean this issue by flutter extension

The bug was not in the VS Code extension itself, but rather in the Dart analyzer (which the VS Code extension uses to get code completions). The Dart analyzer is part of the Dart/Flutter SDKs. So it requires a new Dart/Flutter SDK release for the fix to be available to you.

Hope this makes sense!

**Comment by U-MINDERS-TECH** [comment]
oky sir thank you so much for giving information 
but how much time will take to solve this isue

**Comment by DanTup** [comment]
If the cherry-pick request at https://github.com/dart-lang/sdk/issues/54112 is accepted, then the fix will come in a hotfix release of the Flutter SDK. I don't know how long that takes (I'm not involved in the releases), but I would guess maybe a few weeks.
