### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by HDC83** [Dart-Code/Dart-Code#4851]
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `3.60.1`
- OS Version: `Darwin arm64 22.3.0`
- VS Code version: `1.68.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///var/folders/db/f14c9kyx2216s3lhf2x8dxjm0000gn/T/Dart-Code.dart-code-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by DanTup** [comment]
> ⚠️ Make sure to attach this file from your home-directory:
> ⚠️file:///var/folders/db/f14c9kyx2216s3lhf2x8dxjm0000gn/T/Dart-Code.dart-code-unresponsive.cpuprofile.txt

Are you able to attach this file?

Thanks!

**Comment by DanTup** [comment]
> Extension Version: 3.60.1

FYI you're also on a 6-month old version of VS Code and the Dart extension - I'd recommend upgrading to the latest of both.
