### ISSUE TITLE
Stopping on breakpoint, but debugger shows "Unknown Source"

### ISSUE THREAD

**Issue by lukehutch** [Dart-Code/Dart-Code#4852]
**Describe the bug**

I am trying to debug an interaction with the `RefreshIndicator` class in Flutter. I went to where I was using this class in my code, and hit F12 to go to the definition (which worked fine). I set a breakpoint in a method in that class, which is shown as red / confirmed.

However, now the debugger stops on that line, but the call stack shows "Unknown source" for the location of many of the stackframes, and clicking on those stackframes does nothing.

![image](https://github.com/Dart-Code/Dart-Code/assets/811305/dde8bdc6-4c7e-45ec-a8ff-2c956e1f26a8)

**Comment by lukehutch** [comment]
```console
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.16.0, on Fedora Linux 38 (Workstation Edition) 6.5.10-200.fc38.x86_64, locale en_US.utf8)
    • Flutter version 3.16.0 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (6 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/luke/Android/Sdk
    • Platform android-UpsideDownCake, build-tools 33.0.1
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.6 (Fedora 16.0.6-3.fc38)
    • cmake version 3.27.7
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[✓] Android Studio (version 2022.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 73.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.84.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.77.20231101

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Linux (desktop)            • linux         • linux-x64      • Fedora Linux 38 (Workstation Edition) 6.5.10-200.fc38.x86_64
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 119.0.6045.159

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by lukehutch** [comment]
Upgrading to the beta channel fixed the issue.

**Comment by DanTup** [comment]
Can you confirm what version you saw this on? I switched to stable and couldn't repro:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/0c358e11-8582-402e-8e5e-f53f86f32e14)

However I noticed that in your screenshot the line numbers don't match up with what's on stable. In your screenshot the breakpoint is on line 363 but the version I have and the version in the Flutter repository have that line at 351:

https://github.com/flutter/flutter/blob/stable/packages/flutter/lib/src/material/refresh_indicator.dart#L351

**Comment by lukehutch** [comment]
The version is in the Flutter doctor output... 3.16.0.

Oh, the line numbers probably don't line up, because ei tried tweaking some things and saving, (and then changed them back and saved again), and that caused a reformat.

**Comment by DanTup** [comment]
@lukehutch gotcha. Does it reproduce for you with a new project using the exact code I did?

https://gist.github.com/DanTup/3686b320c4d0e329c72208db6e0f8a5e

If so, can you capture a log (by running **Dart: Capture Debugging Logs** before starting the app) reproducing the issue with that same test project?

If it doesn't repro in a new project, can you see whether there's any obvious difference in your package and the test project? Thanks!

**Comment by lukehutch** [comment]
@DanTup I can't repro with your code sample (thanks for coming up with that though) -- in fact I can't even repro with the original problem case, when I switch back to stable from beta.

I guess that means that something was screwed up in my Flutter install, and switching channels to beta and back fixed the problem.

I'll go ahead and close this, since I don't think I can be of further help, and you surely don't have enough info to do anything with this. Thanks for giving this a look!

**Comment by DanTup** [comment]
Files missing from `cache/bin/dart-sdk/` could lead to this (since we check the files exist before we mark them as available), although I'd expect a lot to be broken if random files were missing out of there.

If it comes up again, let me know and we can dig further. Thanks!
