### ISSUE TITLE
Suggestions related to current function parameters are not shown

### ISSUE THREAD

**Issue by warcayac** [Dart-Code/Dart-Code#4856]
**Describe the bug**
Suggestions related to current function parameters are not shown when pressing CTRL+Space on VSCode

**To Reproduce**
1. Type any function which receives a function as a named parameter: FutureBuilder, BlocBuilder, StatefulBuilder, etc.,
2. Locate on the position to input a value for that named parameter,
3. Press CTRL+Space to show suggestions about the format of the function to be accepted as the value of the named parameter, but unrelated suggestions are shown instead.

**Expected behavior**
Example: for function `BlocBuilder<SearchMoviesCubit,GeneralState>()`, the **builder** parameter should show these suggestions: `(context, state) =>` or `(context, state) {}` which are valid formats to be accepted for this parameter

**Screenshots**

Suggestions unrelated to **builder** parameter are shown (_This image corresponds to when VSCode extensions were disabled but Dart/Flutter extensions_)

![Screenshot_20231125_104748](https://github.com/Dart-Code/Dart-Code/assets/7342885/12fcad66-2c9a-47ca-bafc-afd13545734d)

Valid format for function to be accepted for that value:

![Screenshot_20231125_152446](https://github.com/Dart-Code/Dart-Code/assets/7342885/a174a5dc-3eaf-471e-a5ca-7bac181bc12e)

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.77.20231116
Flutter extension: 3.76.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: linux 1.84.2

Workspace type: Flutter (LSP)

Dart (3.2.0): /home/warcayac/Applications/flutter/bin/cache/dart-sdk
Flutter (3.16.0): /home/warcayac/Applications/flutter (No device)

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`/home/warcayac/Applications/flutter/bin/cache/dart-sdk/bin/dart info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.2.0 (stable) (Tue Nov 14 18:26:59 2023 +0000) on "linux_x64"
- on linux / Linux 6.6.1-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Wed, 08 Nov 2023 16:05:16 +0000
- locale is en_US.UTF-8

#### Project info

- sdk constraint: '>=3.2.0 <4.0.0'
- dependencies: auto_route, cached_network_image, cupertino_icons, dio, fast_immutable_collections, flutter, flutter_bloc, flutter_dotenv, freezed_annotation, hydrated_bloc, json_annotation, oxidized, palette_generator, path_provider, provider
- dev_dependencies: auto_route_generator, build_runner, flutter_gen_runner, flutter_lints, flutter_test, freezed, json_serializable

#### Process info

| Memory |  CPU | Elapsed time | Command line                                                                           |
| -----: | ---: | -----------: | -------------------------------------------------------------------------------------- |
|  59 MB | 0.0% |     01:17:05 | dart devtools --machine --allow-embedding                                              |
| 700 MB | 0.5% |     01:17:05 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.77.20231116 |
|  80 MB | 0.1% |     01:17:05 | flutter_tools.snapshot daemon                                                          |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`/home/warcayac/Applications/flutter/bin/flutter doctor -v`

```text
[!] Flutter (Channel stable, 3.16.0, on EndeavourOS 6.6.1-zen1-1-zen, locale en_US.UTF-8)
    • Flutter version 3.16.0 on channel stable at /home/warcayac/Applications/flutter
    ! The flutter binary is not on your path. Consider adding /home/warcayac/Applications/flutter/bin to your path.
    ! The dart binary is not on your path. Consider adding /home/warcayac/Applications/flutter/bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (10 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/warcayac/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /bin/google-chrome-stable

[✓] Android Studio (version 2022.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 119.0.6045.159

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by DanTup** [comment]
Thanks for the report - there's an existing issue with a summary of the issue/fix at https://github.com/Dart-Code/Dart-Code/issues/4837#issuecomment-1826426306. Thanks!
