### ISSUE TITLE
Format document sometimes adds blank newlines between every line

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#4865]
I've seen this a couple of times in the last few days:

https://github.com/Dart-Code/Dart-Code/assets/1078012/4cbe6c12-36ae-4b86-bd0f-d846fe0936c1

My feeling is that it's related to having a document that is mostly LF but then you add some CRLF (for example during a merge conflict or pasting).

Here's a (zipped, to reduce the chance of anything messing with it) copy of the file from the video in the state that triggers it.

[handler_execute_command.zip](https://github.com/Dart-Code/Dart-Code/files/13515343/handler_execute_command.zip)

And as I hit save, I reload VS Code to ensure it still occurs, but it does not. So probably there is some state involved and it's not just the file on disk. It's unclear if the issue is on the server or the client side.

**Comment by BeezBeez** [comment]
It's been a while (some months) I encounter this problem too. The quickest fix I have found is to execute the command : Reload Window.

**Comment by BeezBeez** [comment]
I have just tested and switching the files to CRLF prevent the bug from happening but switching back to LF and the bug come back.

**Comment by DanTup** [comment]
@BeezBeez do you know of any steps to reliably reproduce it?

**Comment by DanTup** [comment]
Scratch that - I think I have a repro. I switched to the latest bleeding-edge Dart SDK (not stable) and it seems to trigger in my `lf.dart`. I'll debug :)

**Comment by DanTup** [comment]
Dart fix is open at https://dart-review.googlesource.com/c/sdk/+/340220 and I've opened https://github.com/microsoft/vscode/issues/200157 about the weird VS Code behaviour that resulted in the attempt to change LF to CRLF resulting in actual blank lines.
