### ISSUE TITLE
Suggestions seems not fitting (e.g. when a function is expected as input, it isn't suggested as such)

### ISSUE THREAD

**Issue by lydiawho** [Dart-Code/Dart-Code#4870]
**Describe the bug**

**To Reproduce**
Create an object where an anonymous function is expected within its constructor. Hit CTRL + Space when curser is after the colon.

**Expected behavior**
Previously I was always getting well formed anon functions as suggestions - I could even chose whether to have it with { } or =>.

**Screenshots**
Here an example creating a GroupedListView (from package grouped_list)
![image](https://github.com/Dart-Code/Dart-Code/assets/82318169/c2db16e3-a7e3-4b6c-8c8e-78140fee10b3)

**Please complete the following information:**

Dart Code extension: 3.78.0
Flutter extension: 3.78.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: win 1.84.2

Workspace type: Dart, Flutter (LSP)

Dart (3.2.1)
Flutter (3.16.1)

**Comment by DanTup** [comment]
Thanks for the report! Please see https://github.com/Dart-Code/Dart-Code/issues/4837#issuecomment-1826426306 - this was hotfixed into the latest SDKs - you'll need to update to Dart 3.2.2 / Flutter 3.16.2 for the fix.
