### ISSUE TITLE
Inspector navigation doesn't work in noDebug mode with the SDK DAPs

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#4878]
It might not be obvious to users (especially as it changed with the new adapters) that they should run using Debug mode to get some functionality from the inspector (navigating to files as they select widgets).

https://github.com/Dart-Code/Dart-Code/issues/4876 is for deciding (and documenting) the differences between Run/Debug (which should probably be based on specific features rather than arbitrarily what comes over the VM Service) but in the short-term we should do something to avoid confusion from users that don't realise navigation only works in Debug mode.

As a minimum, we should warn users opening the inspector that they should use Debug mode, but we should also evaluate other options (such as a hotfix that connects the VM Service for noDebug mode, or forcing noDebug mode `off` in the extension and intercepting breakpoints/pause-on-exception requests).

**Comment by DanTup** [comment]
Some options:

- 1. Handle ToolEvent inside the extension (similar to how DTD will probably work)
  https://github.com/Dart-Code/Dart-Code/tree/handle-tool-events-in-extension - this might not work for google3 where the URIs need mapping (unless we also handle that mapping in the extension)
- 2. Warn users when the open inspector if they're in noDebug mode that they should run in Debug mode
  Could we have a button to re-start the session for them? (similar to re-run last session)
- 3. Force all runs through debug mode and intercept breakpoints
  This will make Run "slower" because it'll trigger pause-on-start which it didn't before

**Comment by DanTup** [comment]
@jacob314 @jwren I've tested some possible fixes that don't require SDK releases/hot-fixes. I'm interested in your opinions. The details of each fix is above. I haven't implemented any SDK changes yet because I think the changes there will be too risky for a hotfix so will have to wait for the next SDK release.

At first I thought (1) would be a good fix (and would be implemented in the extension where we'll ultimately connect to DTD). However, after implementing it I realised it was missing URI mappings (required for google3) and although we could add that, it'll make the solution more complicated.

My feeling is that we should ship (3) which feels like the simplest/least risky change. We rewrite the `noDebug` flag on the way to the debug adapter, which results in putting it into debug mode. However because Code now automatically skips breakpoints/exception settings for noDebug mode we don't even need to intercept the breakpoint requests as I'd expected. The only slightly odd thing (but this applied to the legacy DAP in noDebug mode for Flutter) is that `debugger()` will still break.

While (2) works, it also may teach users that they need to use Debug mode for this functionality, and if we decide that's not the long-term behaviour we want, that's a little odd (I've opened https://github.com/Dart-Code/Dart-Code/issues/4876 about determining exactly what we want the difference between Run/Debug to be).

**Comment by jwren** [comment]
@DanTup Thanks for articulating the current situation, yes option (3) looks to be the most pragmatic.

**Comment by DanTup** [comment]
Great - I'll add some tests tomorrow with a simulated navigate ToolEvent and ensure we handle it in both debug + noDebug mode, and then I'll push this out in the pre-release version of the extension. I'd like to leave it there at least a few days / a week before doing a stable hotfix just to ensure there aren't any unexpected consequences I didn't find in my own testing.

I'll also think a bit more about https://github.com/Dart-Code/Dart-Code/issues/4876 so we can try plan a "proper" fix (for example one that won't cause noDebug sessions to use --start-pause which might slow down startup a little).

**Comment by DanTup** [comment]
I've merged the fix for this and published a pre-release version. If nothing comes up for the rest of the week, I'll push a stable patch out for this.

**Comment by DanTup** [comment]
The new tests I added here will post a navigation event:

https://github.com/Dart-Code/Dart-Code/blob/da36c47db73d4394e9630d721a5f277810368bb8/src/test/test_projects/flutter_hello_world/lib/navigate_to.dart#L14-L23

And the tests will verify that file is actually opened:

https://github.com/Dart-Code/Dart-Code/blob/da36c47db73d4394e9630d721a5f277810368bb8/src/test/flutter_debug/flutter_run.test.ts#L270-L274

Wrapping up the `postEvent` into a function that is called both by the inspector and this test app would improve things further (because the current test relies on that code matching the event the inspector actually sends).

We can't respond directly to this event (because it's a stream of events and not a request, and there could in theory be multiple or zero connected IDEs) so I'm not sure how worthwhile it is changing how this works if we have tests at both sides (verifying Flutter sends the event, and verifying IDEs given an event perform the navigation).

**Comment by DanTup** [comment]
This issue is resolved in the stable v3.78.2 of the Dart extension.

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/eab7282f-0bcc-435b-8e27-b2a321a2d221)

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/8149c83d-08fd-4644-b0c9-f4afc7c328cb)
