### ISSUE TITLE
"Find All References" acting weird

### ISSUE THREAD

**Issue by khaven** [Dart-Code/Dart-Code#4879]
I have a variable called "_isCancelled" and when i do a "Find All References" on it where it was declared, it show 3 references but when i do a "Find All References" on same variable inside a function it shows 2 references. I have other variables on other files doing same thing. Is this a new feature? This is very confusing. I have to do a text search to find all references now. 

 - Operating System and version:
 - VS Code version:1.84.2
 - Dart extension version:3.78.0
 - Dart/Flutter SDK version:
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
> when i do a "Find All References" on it where it was declared, it show 3 references but when i do a "Find All References" on same variable inside a function it shows 2 references

I don't seem to be able to reproduce this from your description - can you give a code sample that triggers the issue you're seeing?
