### ISSUE TITLE
Autocomplete for named constructors of an enum

### ISSUE THREAD

**Issue by Marco87Developer** [Dart-Code/Dart-Code#4883]
I would like the named constructors of an enum to be included in the autocompletion. I’d like that when writing `MyEnum.` the named constructors also appeared in the autocompletion.

Congratulations for your excellent work and thank you very much!

**Comment by DanTup** [comment]
@Marco87Developer sorry for the delay. I've moved this to https://github.com/dart-lang/sdk/issues/55014 since this will need addressing in the analysis server. Thanks!

**Comment by Marco87Developer** [comment]
> @Marco87Developer sorry for the delay. I've moved this to [dart-lang/sdk#55014](https://github.com/dart-lang/sdk/issues/55014) since this will need addressing in the analysis server. Thanks!

@DanTup, no problem. Thanks to you!
