### ISSUE TITLE
Can't rename variable in "for in" loops

### ISSUE THREAD

**Issue by larssn** [Dart-Code/Dart-Code#4887]
**Describe the bug**
Can't rename the variable in a "for-in" loop.

```dart
final books = [];
for (final book in books) {
}
```

Here `book` can't be renamed by placing the cursor on it, and pressing F2.
The error is `This element can't be renamed`.

**To Reproduce**
1. Try the above.

**Please complete the following information:**
 - Operating System and version: MacOS Version 14.1.2 (Build 23B92)
 - Dart Code extension: 3.78.0
 - Flutter extension: 3.78.0 (activated)
 - VS Code version: 1.84.2
 - Dart (2.19.6)
 - Flutter (3.7.12)

**Comment by DanTup** [comment]
This was fixed in https://github.com/dart-lang/sdk/issues/52149, but it appears you're on an old SDK version. If you update to latest, it should be fixed (I just tested current stable and it worked) :-)

**Comment by larssn** [comment]
Yeah we're stuck with Flutter 3.7.12 for now.

Good to know it's fixed! 😊
