### ISSUE TITLE
Display inline parameter names in argument lists

### ISSUE THREAD

**Issue by dcharkes** [Dart-Code/Dart-Code#4890]
**Is your feature request related to a problem? Please describe.**
When calling functions with positional parameters, it might not be obvious at the call site what the parameters mean.

```dart
void main() {
  eatBananas(true, false, 123);
}
```

**Describe the solution you'd like**

DartCode displays `<param-name>:` in light gray before the parameter, unless the expression passed in is a variable name with exactly the parameter name.

```dart
void main() {
  // these are _not_ named parameters, but VSCode displays them as is with light gray!
  eatBananas(peelFirst: true, hidePeels: false, numberOfBananas: 123);
}
```

Example from the cpp editor in VSCode, see `name:`:
<img width="543" alt="image" src="https://github.com/dart-lang/language/assets/3601775/d3026b60-3752-464a-aa01-ef2c7bcbd660">

**Describe alternatives you've considered**

* Using named parameters in my code.
* https://github.com/dart-lang/language/issues/3502

**Comment by dcharkes** [comment]
Way ahead of me!

Apparently I didn't know what to search for! https://dartcode.org/releases/v3-58/

Thanks @DanTup keep up the great work! 🚀

**Comment by dcharkes** [comment]
Can we hide the inlay hints if the param name is exactly the same as the argument?

<img width="242" alt="image" src="https://github.com/Dart-Code/Dart-Code/assets/3601775/3d0452a6-8716-4302-942f-50fe0d100b07">

**Comment by DanTup** [comment]
We could, but I'm not sure if it would be obvious to users what's happening there. Since we don't display these by default, we've so far always been very explicit with them (often showing redundant information for consistency).

**Comment by dcharkes** [comment]
Type hints are redundant if a constructor is called immediately:
<img width="339" alt="image" src="https://github.com/Dart-Code/Dart-Code/assets/3601775/10b0d373-9c1b-4b95-a255-bbc92f0f05dd">

**Comment by dcharkes** [comment]
> My concern here is that it might not always be obvious to a user why a hint is missing and that could be confusing.

It seems there's a trade-off between not being noisy and being consistent.
My experience in the C++ editor where 'obvious' duplicate information is omitted, is not confusing (to me).

> For example a static method might look the same as a constructor, but only one would get hints.

Maybe static methods that return the same type as the surrounding class should maybe also not get a hint. Maybe they should. Not sure what is the right answer here.

> A mix of parameters where some of the names match and some don't would also look inconsistent.

This doesn't seem to bother me in the C++ editor.

> I feel like these hints are always going to be too noisy to reasonably have them enabled all the time (which is why we default to only showing them while the key is held down), and so if they're only shown temporarily then being consistent may be better than being terse.

I feel like aiming for them not being so noisy that they can always be on is a better design goal. But that is my subjective opinion.

Would it technically be possible to make what inlay hints are available configurable?

clangd makes them configurable in the `.clangd` file:

```
InlayHints:
  Enabled: Yes
  ParameterNames: Yes
  DeducedTypes: No
```

We could do something similar in the DartCode extension settings in vscode possibly?
```json
		"[dart]": {
			// 'off' - never show
			// 'on' - always show
			// 'offUnlessPressed' - show only while shortcut keys are held down (default)
			// 'onUnlessPressed' - show, but hide while shortcut keys are held down
			"editor.inlayHints.enabled": "on",
			"editor.inlayHints.parameterNames": "on", // or "off", or "terse"
		},
```

> That said - I also don't use these that often, so perhaps my opinion shouldn't hold much weight. Perhaps we should leave this issue to collect some opinions (or 👍 👎 votes) before deciding.

I guess I'm going to have to upvote my own issue? 😆 

If we want to get some insight on this, we could request a user study. @mit-mit Who is the right person to ask about something like this? (For a user study it might be nice to already have the configurable options already.)

**Comment by DanTup** [comment]
> I guess I'm going to have to upvote my own issue? 😆

heh, I often upvote my own in the VS Code tracker - it makes it less clicks for others to add theirs 😄

We could certainly add settings to control this (although we can't put them in `editor.inlayHints`, they'd have to be `dart.*`), although it would ofcourse be simpler if we just had one set of rules.

Perhaps it would be useful to collect a specific list of suggestions so it's clearer how it might look? I just looked at a few files with them one one thing that struck me is how different things are depending on whether you already use explicitly types (like Flutter). If you already write things like:

```dart
String s = getString();
```

Which is common in the Flutter rep, then things are a lot less noisy than if you have:

```dart
var s = getString();
```

Because with the latter, you end up with `var String` (which is more verbose than writing it verbosely). It's possible that having it always on would be much more reasonable if you'r ein the former camp than the latter (I'm in the latter :) ).

**Comment by DanTup** [comment]
We recently added some config to control where inlay hints appear:

- https://github.com/dart-lang/sdk/issues/60326
- https://github.com/Dart-Code/Dart-Code/issues/5600

This includes support for showing only parameter names where the values are literals and not identifiers.

Closing this as a dupe of that, but if there are still things missing we should file additional issues (probably in the Dart SDK) for them.

**Comment by dcharkes** [comment]
Awesome!

I read through the related issues, but I couldn't figure out if `suppressWhenArgumentMatchesName` made it in.

**Comment by DanTup** [comment]
@dcharkes unfortunately that's one thing we didn't do yet. We support hiding for literals, but we didn't agree the specifics of what ignoring the "obvious" names should be. I don't think we kept an issue open about that though, so if it's something you'd like - do you want to file an SDK issue about it (and perhaps include what kind of rules you would expect in such functionality).
