### ISSUE TITLE
Contradictory Suggestions by Dart Analysis Tool

### ISSUE THREAD

**Issue by rukiddy70** [Dart-Code/Dart-Code#4895]
Type: Bug

```dart
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

bool _isButtonASelected = false;
bool _isButtonBSelected = false;

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'my_app',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  State createState() => _MyHomePageState();
}

class _MyHomePageState extends State {
  DateTime? _selectedDate;

  Future _selectDate() async {
    final DateTime? pickedDate = await showDatePicker(
      context: context,
      initialDate: DateTime.now(),
      firstDate: DateTime(1900),
      lastDate: DateTime(2100),
    );
    if (pickedDate != null && pickedDate != _selectedDate) {
      setState(() {
        _selectedDate = pickedDate;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Date Picker Form'),
      ),
      body: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
// Add your form fields and other widgets here
              Text('Select Date:',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              _selectedDate != null
                  ? Text('${DateFormat('dd/MM/yyyy').format(_selectedDate!)}')
                  : Text('No date selected'),
              SizedBox(width: 16),
              ElevatedButton(
                onPressed: _selectDate,
                child: Text('Pick Date'),
              ),
            ],
          ),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text('Shift Number',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              SizedBox(width: 16),
              ElevatedButton(
                child: Text('A'),
                onPressed: () {
                  setState(() {
                    _isButtonASelected = true;
                    _isButtonBSelected = false;
                  });
                },
                style: ElevatedButton.styleFrom(
                  backgroundColor:
                      _isButtonASelected ? Colors.blue : Colors.grey,
                ),
              ),
              SizedBox(width: 16),
              ElevatedButton(
                child: Text('B'),
                onPressed: () {
                  setState(() {
                    _isButtonASelected = false;
                    _isButtonBSelected = true;
                  });
                },
                style: ElevatedButton.styleFrom(
                    backgroundColor:
                        _isButtonBSelected ? Colors.blue : Colors.grey),
              ),
            ],
          )),
    );
  }
}
```

Error reported by Dart Analysis Tool:

"Positional arguments must occur before named arguments.
Try moving all of the positional arguments before the named arguments." Ln 64, Col 9
Suggestion by DAT: convert to a named argument by wrapping Row () under child ().
Error: it then shows another error :
The argument for the named parameter 'child' was already specified.
Try removing one of the named arguments, or correcting one of the names to reference a different named parameter. Ln 64, Col 9
"Too many positional arguments: 0 expected, but 1 found.
Try removing the extra positional arguments, or specifying the name for named arguments." Ln 64, Col 9
Suggestions by DAT: convert to named argument.
After implementing it, the tool shows the below error:
"The argument for the named parameter 'child' was already specified.
Try removing one of the named arguments, or correcting one of the names to reference a different named parameter."
Ln 64, Col 9
VS Code version: Code 1.85.0 (https://github.com/microsoft/vscode/commit/af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T20:48:09.019Z)
OS version: Windows_NT x64 10.0.19045
Modes:

System Info
Extensions (22)
A/B Experiments

**Comment by DanTup** [comment]
Can you clarify the exact steps you're taking? I was able to follow the first part:

1. Error: Too many positional arguments: 0 expected, but 1 found.
2. Apply fix: Convert to named arguments
3. Error: The argument for the named parameter 'child' was already specified.

However, there is no fix associated with that last error. The problem here is that you already have a `child:` for `Padding()`, so while the first fix assumed you wanted the `Row` to be a child, it did not check that there was already a child.

The real issue here is that you're trying to add two children (two `Row`s) as a child of the main `Padding`, but `Padding` only supports a single child. Here is a smaller example of your code:

```dart
import 'package:flutter/material.dart';

const a = Padding(
  padding: EdgeInsets.all(16.0),
  child: Row(),
  Row(),
);
```

Perhaps the original fix ("convert to named arguments") shouldn't appear if it will use argument names that have already been used. @bwilkerson - any thoughts? Here's what the issue looks like:

https://github.com/Dart-Code/Dart-Code/assets/1078012/ec9a3b3f-4240-4593-bff9-dba28adc5002

**Comment by bwilkerson** [comment]
I agree, "convert to named arguments" shouldn't propose converting to using a name that's already used. Doing so is guaranteed to just replace one diagnostic with another, which generally isn't helpful.

**Comment by DanTup** [comment]
I've opened https://github.com/dart-lang/sdk/issues/54336 in the SDK for this.

Closing this one as I don't think there's anything else to do here, but @rukiddy70 please let me know if you think there are other things to address here too. Thanks!
