### ISSUE TITLE
Auto-linked paths don't match parent dir `..`

### ISSUE THREAD

**Issue by lukehutch** [Dart-Code/Dart-Code#4898]
**Describe the bug**

If a path appears in stderr text, you can Ctrl+click on the path to open it in the editor. However, this only matches `.`, not `..`.

It's a bit hard to see in the screenshot, but only the second `.` is underlined:

![image](https://github.com/Dart-Code/Dart-Code/assets/811305/593c8abe-b09a-492d-9bb2-810c30b96e90)

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.79.20231206
Flutter extension: 3.79.20231130 (activated)

App: Visual Studio Code
App Host: desktop
Version: linux 1.85.1

Workspace type: Dart, Flutter (LSP) (Multiroot)

Dart (3.3.0-174.3.beta): /opt/flutter/bin/cache/dart-sdk
Flutter (3.18.0-0.2.pre): /opt/flutter (Chrome (web-javascript/web))

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`/opt/flutter/bin/cache/dart-sdk/bin/dart info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.3.0-174.3.beta (beta) (Tue Dec 12 14:49:22 2023 +0000) on "linux_x64"
- on linux / Linux 6.5.12-300.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Nov 20 22:44:24 UTC 2023
- locale is en_US.utf8

#### Project info

- sdk constraint: '>=3.1.5 <4.0.0'
- dependencies: auto_size_text, boxy, cached_network_image, carousel_slider, collection, cross_file, cupertino_icons, device_info_plus, email_validator, exif, extended_image, flutter, flutter_cache_manager, flutter_email_sender, flutter_fgbg, flutter_image_utilities, flutter_localizations, flutter_persistent_value_notifier, flutter_svg, fluttericon, fluttertoast, geocoding, geolocator, getwidget, google_fonts, google_mlkit_face_detection, http, image_picker, intl, jiffy, line_awesome_flutter, logging, material_dialogs, package_info_plus, path_provider, persistent_bottom_nav_bar_v2, provider, random_string, share_plus, shared_preferences, url_launcher
- dev_dependencies: flutter_launcher_icons, flutter_lints, flutter_test, lints
- elided dependencies: 11

#### Process info

|  Memory |  CPU | Elapsed time | Command line                                                                               |
| ------: | ---: | -----------: | ------------------------------------------------------------------------------------------ |
|  539 MB | 0.1% |     05:21:47 | dart --enable-vm-service=0 --pause_isolates_on_start --disable-dart-dev -DSILENT_VM_SERVICE=true --write-service-info=file:<path>/vm.json --pause_isolates_on_exit --enable-asserts <path>/main.dart |
|  687 MB | 6.6% |        08:02 | dart ..<path>/serverpod_cli.dart generate --watch                                          |
|   75 MB | 0.0% |     05:21:47 | dart debug_adapter                                                                         |
|   60 MB | 0.0% |     09:33:07 | dart devtools --machine --allow-embedding                                                  |
|   59 MB | 0.0% |     09:33:00 | dart devtools --machine --allow-embedding                                                  |
| 2222 MB | 2.7% |     09:33:07 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.79.20231206     |
| 1537 MB | 0.3% |     09:33:00 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.79.20231206     |
|   90 MB | 0.0% |     09:33:07 | flutter_tools.snapshot daemon                                                              |
|   90 MB | 0.0% |     09:33:00 | flutter_tools.snapshot daemon                                                              |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`/opt/flutter/bin/flutter doctor -v`

```text
[✓] Flutter (Channel beta, 3.18.0-0.2.pre, on Fedora Linux 39 (Workstation Edition) 6.5.12-300.fc39.x86_64, locale en_US.utf8)
    • Flutter version 3.18.0-0.2.pre on channel beta at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fed06b31d9 (2 days ago), 2023-12-13 14:53:33 -0800
    • Engine revision 39c6dc9bdd
    • Dart version 3.3.0 (build 3.3.0-174.3.beta)
    • DevTools version 2.30.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/luke/Android/Sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 17.0.4 (Fedora 17.0.4-1.fc39)
    • cmake version 3.27.7
    • ninja version 1.11.1
    • pkg-config version 1.9.5

[✓] Android Studio (version 2022.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 73.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.85.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.79.20231130

[✓] VS Code (version 1.86.0-insider)
    • VS Code at /usr/share/code-insiders
    • Flutter extension version 3.79.20231130

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Linux (desktop)            • linux         • linux-x64      • Fedora Linux 39 (Workstation Edition) 6.5.12-300.fc39.x86_64
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 119.0.6045.159

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by lukehutch** [comment]
Sorry if this is mis-filed, I have no idea if this is a VS Code issue or a Dart-Code issue...

**Comment by Bharatjaat04** [comment]
https://github.com/flutter/flutter.git

**Comment by DanTup** [comment]
This is a VS Code issue - it provides the link detection on text in the Debug Console like that (the links we provide in the Debug Console appear aligned to the right side).

Unfortunately link detection in VS Code is a bit of a mess, and there are many implementations used in different places. There's an open issue here:

https://github.com/microsoft/vscode/issues/34026

For example, in the Terminal, those same `..` links work fine:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/667cf25c-b3c5-4223-a1d8-a2647e3e7fd6)

**Comment by FMorschel** [comment]
That issue got closed =D. It'll probably land on stable in June's release.
