### ISSUE TITLE
Ability to launch Android and iOS emulators like IntelliJ plugin for Flutter

### ISSUE THREAD

**Issue by aubykhan** [Dart-Code/Dart-Code#490]
In IntelliJ, the Flutter extension allows to launch iOS and Android emulators directly without opening AVD manager etc. 

This feature is missing from Dart Code right now and it becomes cumbersome to launch the emulators through terminal or other ways.

**Comment by DanTup** [comment]
Great idea! I've actually got some terminal aliases for launching iOS and Android emulators because they're a pain but it would be much nicer to have something built-in to Dart Code for everyone to use.

It seems like the plan [might be](https://github.com/flutter/flutter-intellij/pull/1129#issuecomment-311456173) to add support to the Flutter tooling which would simplify things a lot for the implementation but that might be a while off. If so, it may make sense adding something directly in Dart Code.

It'd be nice to list not-running emulators in the device picker opened from the status bar but I don't think the AVD names will match up with the names from Flutter so we'd probably end up with dupes.

I'll have a think and see what I can come up with. Thanks!

**Comment by DanTup** [comment]
Related: https://github.com/flutter/flutter-intellij/issues/1244

**Comment by DanTup** [comment]
@devoncarew What do you think is the best way handle this? We could do it entirely in Dart Code (probably what other IDEs do) but it means duplicated code across editors. If implemented in Flutter, where should it sit (`flutter daemon`? `flutter run`? across both - daemon for getting list, run for launching?).

Is there anything in particular that already exists that you think would be a good place to look at to try and base this on?

**Comment by devoncarew** [comment]
We do do it internally in the IntelliJ plugin; that was a pragmatic solution - there was already code in there to help locate and manage the android sdk.

Definitely a better solution would be to have this in flutter_tools and available to all IDEs.

Assuming we have some sort of emulator management cli (in `flutter device`, or another new command), I think we'd want:
- to be able to enumerate existing emulators (existing definitions of them, not running instances)
- start an emulator
- create a new emulator definition

It would be great if this worked across ios and android. The ios implementaion should be pretty straightforward. The Android impl. will likely be most tricky for the creation flow - I believe it takes a lot of parameters to create an emulator, and its not always clear what the best flags are for any one host machine.

This would be a big task, so we should find ways to chop it into smaller, easier pieces.

**Comment by DanTup** [comment]
Opened https://github.com/flutter/flutter/issues/14822 for the flutter tools work.

**Comment by vogella** [comment]
Cooool. Thanks a bunch.

**Comment by DanTup** [comment]
I've just published a new beta of v2.13 that includes this:

https://github.com/Dart-Code/Dart-Code/releases/tag/v2.13.0-beta.3

You need to install that from the vsix and be on latest flutter master (as of about 45 minutes ago). It's not in the release notes yet, but will be shortly. You can launch the emulator by hitting `F5`/Start without a device connected, clicking "0 connected devices" in the status bar or running the "Launch Emulator" command from the palette.

Please try it out and send feedback/issues! :)

**Comment by nmfisher** [comment]
I'm still new to VS Code/Dart/Flutter but this seems to be working great for me.

From my brief review of the source,  and it seems there's no way to set command line parameters (e.g. emulator -avd Android -dns-server 8.8.8.8). Would this be considered?

**Comment by DanTup** [comment]
@nmfisher you're correct that it's not currently possible. Are you hoping to set the additional args the same for all emulator launches, or for specific emulators?

We currently launch emulators through Flutter, so one route would be to extend flutter (relevant code [here](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/emulators.dart)), though I wonder if this might be a bit specific (the `flutter emulator` work is deliberately very simple). I'm wondering whether this could be made a little more generic to potentially support any arbitrary command to launch emulators, eg. something like:

```
"dart.customEmulators": [
  {
    "id": "foo",
    "name": "My Foo Emulator",
    "command": "emulator -avd xxx -other -args ..."
  }
]
```

`foo` would then always appear in the emulator list alongside those listed from Flutter, and it'd just invoke your custom command. If the ID you give it overlaps with a Flutter-returned emulator, we'll just replace it (eg. allowing you to "override" the launch commands for emulators returned by Flutter).

I think something along those lines might support emulators that aren't from the Android SDK - for example there are services like [Genymotion Cloud](https://www.genymotion.com/cloud/) which I know very little of, but seems like they would not appear as local emulators, however they do have ADB compatibility. In theory it seems like this could support launching a remote emulator (assuming once it boots, that it appears as a device in adb). It'd need some testing, but maybe it's a good way of achieving what you want while also adding support for other emulators in the process.

**Comment by nmfisher** [comment]
@DanTup I don't have experience with non-Android SDK emulators, but your suggestion to allow customizing the launch command makes sense (given that emulators are simply another command-line switch).

**Comment by DanTup** [comment]
@nmfisher Thanks, I've opened https://github.com/Dart-Code/Dart-Code/issues/1553.
