### ISSUE TITLE
Divder over persistentFooterButtons 

### ISSUE THREAD

**Issue by vikasmohan202** [Dart-Code/Dart-Code#4905]
sometimes we do not want this divider line and i am not getting the option to remove this line(just above persistentFooterButtons )
![Screenshot from 2023-12-19 05-43-17](https://github.com/Dart-Code/Dart-Code/assets/109174572/d71d77b1-ac57-4191-96b3-52eec48a5229)

**Comment by DanTup** [comment]
This repository is for the VS Code extension. The repository for issues/requests for Flutter is https://github.com/flutter/flutter/

Thanks!
