### ISSUE TITLE
Record fields are not syntax highlighted

### ISSUE THREAD

**Issue by navaronbracke** [Dart-Code/Dart-Code#4908]
**Is your feature request related to a problem? Please describe.**
Currently, when using records with named fields, the names of the fields are not highlighted like regular field accessors.

Consider the sample: 

```dart
void foo() {
  const ({bool someField}) rec = (someField: false);

  final bool myBool = rec.someField;
}
```

![image](https://github.com/Dart-Code/Dart-Code/assets/23480364/63b1126c-5e44-4b8d-b2ca-c2c2dda69dd3)

**Describe the solution you'd like**
Have named fields of records highlighted the same way as fields / local variables.
Since named fields in methods and constructors get highlighted in blue, I propose we do the following:

1) Highlight the named fields of records at the declaration site (LHS of the code sample).
This brings it in line with named fields for methods/constructors.

2) Highlight the named field access when using the field.
This brings it in line with regular usage of class fields and (local) variables.

**Describe alternatives you've considered**
N/A

**Additional context**
Dart-Code v3.78.2
Flutter (Channel stable, 3.16.0, on Microsoft Windows [Version 10.0.19045.3803], locale nl-BE)
    • Flutter version 3.16.0 on channel stable at E:\Documenten\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (5 weeks ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/0d6dd73877d439dd46075117f8e4ea93965baf53. The change ships inside the Dart/Flutter SDKs, so it'll show up in a future SDK release (not a Dart-Code extension release).

Thanks!
