### ISSUE TITLE
Debugging Flutter CLI via VS Code for a Flutter project stopped working in v3.78.0

### ISSUE THREAD

**Issue by vashworth** [Dart-Code/Dart-Code#4910]
**Describe the bug**
Debugging the Flutter CLI in VS Code stopped working in v3.78.0 and is also broken in v3.78.2. If I install v3.76.1 it works as expected.

It seems to me that if `cwd` is defined in launch config, it doesn't use the first item in `args` as the command. If `cwd` is not defined, it does use the first item in `args` as the command. Previously, it would always use the first item in `args` as the command.

**To Reproduce**
1. Follow these instructions to setup VS Code to debug Flutter CLI: https://github.com/flutter/flutter/wiki/The-flutter-tool#debugging-the-flutter-command-line-tool-in-vs-code

Here's an example of what my config looks like:
```json
{
            "name": "flutter_tools",
            "request": "launch",
            "type": "dart",
            "program": "${workspaceFolder}/packages/flutter_tools/bin/flutter_tools.dart",
            "cwd": "/path/to/a/flutter/project",
            "args": ["doctor"],
},
```

2. In VS Code, with `flutter_tools (flutter)` selected in Debug tab, start debugger. 

**Expected behavior**
I would expect `flutter doctor` to run.

Instead it seems to be doing `flutter run`. I get this output:
```
Launching /Users/vashworth/Development/flutter/packages/flutter_tools/bin/flutter_tools.dart on iPhone 15 in debug mode...
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
Xcode build done.                                            7.7s
Failed to build iOS app
...
```

**Screenshots**
N/A

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

 - Operating System and version: macOS 13.6.3
 - VS Code version: mac 1.85.1
 - Dart extension version: 3.78.2
 - Dart/Flutter SDK version: 3.3.0-244.0.dev / 3.18.0-14.0.pre.32
 - Target device (if the issue relates to Flutter debugging):

**Comment by vashworth** [comment]
Actually I think this is a duplicate of https://github.com/Dart-Code/Dart-Code/issues/4867. Looks like it was fixed in pre release.

**Comment by DanTup** [comment]
Yep, you're right. This version will be released next week but for now you can use the pre-release. Sorry for the bother!
