### ISSUE TITLE
restart stack from missing from call stack when debugging.

### ISSUE THREAD

**Issue by bsutton** [Dart-Code/Dart-Code#4911]
**Describe the bug**
Previously in vs-code, when debugging, you could right click on the second to last call stack entry and see an option 'restart frame' (at least from memory that is what I believed it was called).

I refer to this issue for reference:
https://github.com/dart-lang/sdk/issues/47885

**To Reproduce**
Run the debugger.
Pause on a break point.
Right click any call frame (except the top one) in the debug call stack.
'restart frame' option is missing.

**Expected behavior**
The 'restart frame' options should be visible and when you click it it should rewind the stack frame.

**Screenshots**
[Screencast from 21-12-23 11:10:47.webm](https://github.com/Dart-Code/Dart-Code/assets/900408/a1084d4c-0277-4db2-93a2-7c6dee5236e3)

**Please complete the following information:**

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.78.2
Flutter extension: 3.78.0 (not activated)

App: Visual Studio Code
App Host: desktop
Version: linux 1.85.1

Workspace type: Dart (LSP)

Dart (3.2.3): /home/bsutton/.dswitch/channels/stable/versions/3.2.3/dart-sdk
Flutter (3.13.7): /home/bsutton/snap/flutter/common/flutter (No device)

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`/home/bsutton/.dswitch/channels/stable/versions/3.2.3/dart-sdk/bin/dart info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.2.3 (stable) (Tue Dec 5 17:58:33 2023 +0000) on "linux_x64"
- on linux / Linux 6.2.0-39-generic #40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 10:53:04 UTC 2
- locale is en_AU.UTF-8

#### Project info

- sdk constraint: '>=3.0.0 <4.0.0'
- dependencies: _fe_analyzer_shared, analyzer, ansi, args, cli_spin, dcli, dcli_core, equatable, glob, io, logging, meta, path, pubspec_manager, quiver, source_span, stack_trace, strings
- dev_dependencies: lint_hard, test
- elided dependencies: 1

#### Process info

| Memory |  CPU | Elapsed time | Command line                                                                               |
| -----: | ---: | -----------: | ------------------------------------------------------------------------------------------ |
| 581 MB | 0.8% |     02:33:52 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.78.2 --instrumentation-log-file=<path>/dart.analyzerInstrumentationLogFile |

</details>

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

 - Operating System and version:
 - VS Code version:
 - Dart extension version:
 - Dart/Flutter SDK version:
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
Can you confirm your SDK version and include a screenshot of the stack trace?

This was missing from the new SDK DAPs and I implemented it recently (https://github.com/Dart-Code/Dart-Code/issues/4359) but it probably missed the last stable.

But it's worth noting that we only support this up to the first async boundary - we do not support restarting to a frame beyond an async boundary because those frames are not the real stack frames (they are synthetic frames designed to make async code easier to understand).

**Comment by bsutton** [comment]
apologies for the delay:

sdk: 3.2.1

![image](https://github.com/Dart-Code/Dart-Code/assets/900408/9987a745-0acb-43a2-aa8a-b88a55e06b32)

**Comment by bsutton** [comment]
The above stack trace shows a sync call to parseDeployTarget.

right clicking on the either main or parseDeployTarget in the stack trace offers one option 'copy call stack'.

**Comment by bsutton** [comment]
I've just tried this with dart 3.2.4 with the same result (no option to drop to frame).

Running dart code 3.80.0

Ubuntu: 22.04

**Comment by bsutton** [comment]
Just tried the dart-code pre-release version v3.81.20231227 with the same result (no option to drop to frame).

**Comment by DanTup** [comment]
Thanks - looks like this missed the last stable. In Dart 3.2 I see this:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/dddb863c-514a-45d1-b0ff-f88c7960ec55)

But in the latest code (and presumably latest betas), I see this:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/fd6bef82-24c8-47bd-a7e5-08a2354389ca)

So this is indeed fixed and will show up in the next SDK release. Thanks!
