### ISSUE TITLE
Updating IntelliJ does not update Flutter SDK. Updating SDK then invalidates plugin. Plugin update needs to update SDK too.

### ISSUE THREAD

**Issue by AMDphreak** [Dart-Code/Dart-Code#4912]
**Describe the bug**
> Plugin 'Dart' (version '233.13135.65') is not compatible with the current version of the IDE, because it requires build 233.13135 or newer but the current build is IC-232.10227.8 Plugin 'Package Search' (version '233.11799.196') is not compatible with the current version of the IDE, because it requires build 233.11799 or newer but the current build is IC-232.10227.8 Plugin 'Flutter' (version '77.0.1') is not compatible with the current version of the IDE, because it requires build 233.11799.196 or newer but the current build is IC-232.10227.8

Can't enable Flutter plugin (infinite loop). Dart plugin error on IntelliJ start. Possible version mismatch. No longer can launch Dart update and Flutter update from IDE.

**To Reproduce**
1. Open outdated IntelliJ
2. Update IntelliJ, and the plugins, via the dialog (does both in same update process)
3. Restart IntelliJ, observe plugins work. Go to Tools > Flutter > Flutter Upgrade, finish process, reboot IntelliJ, observe errors.

**Expected behavior**
Update IntelliJ and plugins, plugin updates Flutter SDK during its update process. Needs to check target IntelliJ update version, cross-reference with Flutter doctor, then upgrade Flutter before upgrading plugin.

**Screenshots**
First shows an error message for Dart plugin.
![image](https://github.com/Dart-Code/Dart-Code/assets/1058978/2ff4ab9f-50eb-4452-9781-1d85e1f2bbf0)
Then a few seconds later, shows a non-error message (but still really an error) saying Flutter plugin is not installed. Clicking "Enable plugin" doesn't enable anything. Just causes reboot and shows the same 2 error messages afterward.
![image](https://github.com/Dart-Code/Dart-Code/assets/1058978/0ad0b304-2eaf-4464-9159-e7fbf015b10b)

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

 - Operating System and version: None of this is necessary. I know the pattern. You just need to fix the the update process. You have the wrong assumptions about how it should work.
 - VS Code version:
 - Dart extension version:
 - Dart/Flutter SDK version:
 - Target device (if the issue relates to Flutter debugging):

**Comment by AMDphreak** [comment]
This is a bug and an enhancement. Fixing poor assumptions is not what I would call a feature upgrade. It's debugging the human programmer.

**Comment by DanTup** [comment]
This issue tracker is for the VS Code extension and unrelated to IntelliJ or Android Studio. The issue tracker for the Flutter IntelliJ plugin is at https://github.com/flutter/flutter-intellij and for the Dart plugin is at https://youtrack.jetbrains.com/issues/IDEA.

Thanks!
