### ISSUE TITLE
quick fix autocompletion for callbacks stopped working

### ISSUE THREAD

**Issue by arthurbcd** [Dart-Code/Dart-Code#4913]
**Describe the bug**
Normally when pressing "option + ." or "control + space" in Mac vscode with flutter and dart extension, it opens a context menu with autocomplete suggestions. It was extremely useful for autocompleting template of callbacks. It's either gone or stopped to work.

**To Reproduce**
```dart
TextField(
  decoration: // pressing 'option + .' opens a context menu with a suggestion to use InputDecoration() ✅
  onChanged: // pressing 'option + .' opens a context menu suggesting Null as input template. ❌
),
```

**Expected behavior**
```dart
TextField(
  decoration: // inputs InputDecoration(...) ✅
  onChanged: // inputs (value) { ... } ✅, but actually returning Null ❌
),
```

**Screenshots**
![image](https://github.com/Dart-Code/Dart-Code/assets/60884977/11988a71-1f6b-4365-8e05-1cd866272d7b)

**Please complete the following information:**
 - Operating System and version: mac 1.85.1
 - VS Code version: 1.85.1
 - Dart extension version: v3.78.2
 - Dart/Flutter SDK version: Dart 3.2.0, Flutter 3.16.0

**Comment by DanTup** [comment]
This issue has been recently fixed. If you run `flutter upgrade` to get the latest version of Flutter, the issue should be resolved :-)

**Comment by arthurbcd** [comment]
Omg, yes! It is indeed!

Thank for the fast response! Amazing.

Happy holidays!
