### ISSUE TITLE
Breakpoint never hits

### ISSUE THREAD

**Issue by JCKodel** [Dart-Code/Dart-Code#4915]
**Describe the bug**
Most breakpoints are not working

**To Reproduce**
```dart
import 'dart:developer';

import 'package:flutter/material.dart';

import '../../shared/presentation/streamer.dart';

import 'theme_repository.dart';
import 'theme_settings.dart';

final class ThemeProvider extends StatelessWidget {
  const ThemeProvider({required this.child, super.key});

  final Widget child;

  static ThemeProviderData of(BuildContext context) {
    return context.dependOnInheritedWidgetOfExactType<ThemeProviderData>()!;
  }

  @override
  Widget build(BuildContext context) {
    return Streamer(
      stream: ThemeRepository.currentThemeSettings(),
      builder: (context, themeSettings) {
        log("Building ThemeProviderData using ${themeSettings}");

        return ThemeProviderData._(themeSettings: themeSettings, child: child);
      },
    );
  }
}

final class ThemeProviderData extends InheritedWidget {
  const ThemeProviderData._({
    required this.themeSettings,
    required super.child,
  });

  final ThemeSettings themeSettings;

  ThemeData get currentTheme => ThemeData.light();

  @override
  bool updateShouldNotify(ThemeProviderData oldWidget) {
    log("Updating children: ${oldWidget.themeSettings != themeSettings}");
    return oldWidget.themeSettings != themeSettings;
  }
}

```

In the code above, if you put a breakpoint on line 24 (`log("Building ThemeProviderData using ${themeSettings}");`), it hits.

Put a breakpoint on line 44 (`log("Updating children: ${oldWidget.themeSettings != themeSettings}");`), it stays grey forever ("unverified breakpoint").

This happens A LOT, in many places. The above is only one example.

**Expected behavior**
The breakpoint should hit when the code is run.

**Please complete the following information:**

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.78.2
Flutter extension: 3.78.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: win 1.85.1

Workspace type: Flutter (LSP)

Dart (3.2.3): C:\Users\jckod\fvm\versions\3.16.5\bin\cache\dart-sdk
Flutter (3.16.5): C:\Users\jckod\fvm\versions\3.16.5 (sdk gphone64 x86 64 (android-x64/android))

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`C:\Users\jckod\fvm\versions\3.16.5\bin\cache\dart-sdk\bin\dart.exe info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.2.3 (stable) (Tue Dec 5 17:58:33 2023 +0000) on "windows_x64"
- on windows / "Windows 10 Pro" 10.0 (Build 22631)
- locale is pt-BR

#### Project info

- sdk constraint: '>=3.2.3 <4.0.0'
- dependencies: cupertino_icons, dart_mappable, firebase_analytics, firebase_auth, firebase_core, firebase_crashlytics, flutter, flutter_localizations, google_sign_in, ksuid, local_auth, markdown_viewer, material_symbols_icons, sign_in_with_apple, slide_indexed_stack, url_launcher
- dev_dependencies: build_runner, dart_mappable_builder, flutter_launcher_icons, flutter_lints, flutter_native_splash

#### Process info

| Memory | CPU | Elapsed time | Command line |
| -----: | --: | -----------: | ------------ |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`C:\Users\jckod\fvm\versions\3.16.5\bin\flutter.bat doctor -v`

```text
[√] Flutter (Channel stable, 3.16.5, on Microsoft Windows [Version 10.0.22631.2861], locale pt-BR)
    • Flutter version 3.16.5 on channel stable at C:\Users\jckod\fvm\versions\3.16.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (4 days ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\jckod\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34330.188
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] VS Code (version 1.85.1)
    • VS Code at C:\Users\jckod\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.78.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22631.2861]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 120.0.6099.111
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 120.0.2210.77

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by DanTup** [comment]
Sorry for the delay. Do you have a repro I can run? I tried to use this code, but it uses classes that aren't included. Thanks!

**Comment by JCKodel** [comment]
Recently that is not happening anymore (I mean: breakpoints are still a mess, the red point is not set in the gutter, but it breaks, red points in one line are moved to some arbitrary line, especially in closures, it is not possible to add a breakpoint by mouse when the gutter has other indications (such as a warning icon by using `print`, for example), but it works).

Since I threw that project away and started a full refactory, this issue disappeared =\ I think it was some cache (the workspace is the same now, so no configuration changed).

I found that `print` and `debugger(message: "Hi, Mark")` are Dart's best friend (I assume you rely on poor Dart behavior to control breakpoints and there isn't much to do in this regard).

Thank you, anyway.

**Comment by DanTup** [comment]
> I mean: breakpoints are still a mess
> the red point is not set in the gutter, but it breaks

That sounds like https://github.com/Dart-Code/Dart-Code/issues/4734. There's a fix in progress but it's not complete yet.


> red points in one line are moved to some arbitrary line, especially in closures

Do you have a repro for this? I had an issue where things break on the wrong line at https://github.com/dart-lang/sdk/issues/54100 but it's not clear that's what you're seeing. I'd like to try and resolve any issues like this, but I need reports/repros to investigate.

> it is not possible to add a breakpoint by mouse when the gutter has other indications (such as a warning icon by using print, for example), but it works

This sounds like a VS Code issue. There have been some improvements (like https://github.com/microsoft/vscode/issues/5923) but there are still some open issues (like https://github.com/microsoft/vscode/issues/179725).

**Comment by JCKodel** [comment]
About the breakpoint appearing in other locations, I don't have a exact repro. Sometimes, in the same code, it doesn't happen =\

Just yesterday I put a breakpoint in one line, the red dot appeared some 5, 6 lines above, then disappeared, but the breakpoint hit the correct line anyway.

I can't see a pattern or a reason for this to happen, so, it is hard to give you repro or more detais (and we all understand that is even harder for you to fix something in this circustances, or even figure out if it is a dart-code issue, a dart or a vscode issue).

**Comment by DanTup** [comment]
It's hard to say with limited info, but even if you don't have repros, screenshots and explanations of the code can be useful. Sometimes they'll be enough to understand what might have happened and get a repro.

**Comment by JCKodel** [comment]
It's hard to say, since we're messing with code, so it is mutable. I can't really be sure if this was the case but:

![image](https://github.com/Dart-Code/Dart-Code/assets/379339/9e105a8f-3e7b-4c85-8d2c-2565f72e98e7)

I asked for a breakpoint in line 185, but the red dot appeared on line 176 before vanishing a couple of seconds later.

I'm not sure if that has something to do with Dart huge mess that is async/await (I don't know if dart code compilation/parser is called on breakpoint definitions). There is a huge bug in Dart where the code completes when it should not.

Let me show an example of what I'm saying:

```dart
final repository = SomeRepositoryClass();

try {
  final data = await repository.fetchSomeData();
  // At this point, SomeRepositoryClass has a `_db` variable with a SQLite connection opened

  final otherFetch = await repository.fetchSomeOtherData();
  // Sometimes, that `_db` is closed here, so an exception is thrown

  return otherFetch;
} finally {
  repository.dispose(); // Here we have a `_db.close()` inside that class
}
```

There is no async code called without await, the repository methods are all very simple and are correct (basically a `return await _db.query("SELECT BLA")`).

In some circustances (and, again, I don't catch a pattern here to repro it), the `dispose` is called before the second await runs (at the moment the _db is closed and the program crashes).

Everytime something goes wrong with breakpoints or nullability, async code is present.

Nulability bugs such as:

```dart
if(something == null) {
  return;
}

print(something.property); // This line doesn't compile without ! operator on something
```

I'm not sure if Dart parser/compiler has anything to do with defining breakpoints, but, those things are always present when that happens.

**Comment by DanTup** [comment]
@JCKodel unfortunately it's very difficult to investigate or provide any useful response without concrete repos.

> In some circustances (and, again, I don't catch a pattern here to repro it), the dispose is called before the second await runs (at the moment the _db is closed and the program crashes).

This definitely sounds wrong, but without a repro it's difficult to debug. I understand it might be difficult to produce a repro, but it's also very difficult to debug with this little info.


> Nulability bugs such as:
> 
> ```
> if(something == null) {
>  return;
> }
> 
> 
> print(something.property); // This line doesn't compile without ! operator on something
> ```

Again, it's hard to say without a repro, but this sounds like an analysis error and is probably not related to debugging or breakpoints. Usually this happens if `something` is a class field or getter, because the value returned could be different each time you call `something`. For example:

```
String? get something => _rnd.next() == 1 ? "STRING" : null;
```

Even if it's just a field, it could be overridden by a getter in a subclass.

You can avoid this with a pattern that checks for null and shadows the field with a copy (this avoids multiple reads of the getter). For example:

```dart
class A {
  String? foo;

  void bar() {
    if (foo != null) {
      print(foo.isEmpty); // error because calling `foo` a second time could return a different value if overridden by a getter
    }

    if (foo case var foo?) {
      print(foo.isEmpty); // no error because `foo` here is a reference to the previous invocation of `foo` and does not call it again
    }
  }
}

```
