### ISSUE TITLE
Dart runtime issue in vs code but OK via CMD

### ISSUE THREAD

**Issue by ozzie786** [Dart-Code/Dart-Code#4916]
VS Code Version:

Version: 1.85.1 (user setup)
Commit: https://github.com/microsoft/vscode/commit/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

OS Version: Windows 10

Steps to Reproduce:
Run this Dart code in VS CODE:

import 'dart:io';

void main() {
var isLoopContinue = true;
var attempts = 0;

while (isLoopContinue == true) {
stdout.writeln("Enter email:");
var email = stdin.readLineSync();
stdout.writeln("Enter password:");
var password = stdin.readLineSync();
if (email == '[admin@gmail.com](mailto:admin@gmail.com)' && password == "123456") {
print("Login successfully");
isLoopContinue = false;
} else {
attempts++;
if (attempts > 3) {
isLoopContinue = false;
print('Your account has been blocked!');
} else {
print('Invalid credentials. Please try again.');
}
}
}
}

Output:
Enter email:
"HERE IS THE EMAIL INPUT , WE WROTE" //AND THEN ERRORS BELOW
Unknown evaluation response type: null
#0 DartDebugAdapter.evaluateRequest (package:dds/src/dap/adapters/dart.dart:1076:7)
https://github.com/microsoft/vscode/issues/1 BaseDebugAdapter.handle (package:dds/src/dap/base_debug_adapter.dart:141:20)
https://github.com/microsoft/vscode/issues/2 BaseDebugAdapter.handleIncomingRequest (package:dds/src/dap/base_debug_adapter.dart:447:7)
https://github.com/microsoft/vscode/issues/3 BaseDebugAdapter._handleIncomingMessage (package:dds/src/dap/base_debug_adapter.dart:295:7)
https://github.com/microsoft/vscode/issues/4 ByteStreamServerChannel._readMessage (package:dds/src/dap/protocol_stream.dart:82:18)
https://github.com/microsoft/vscode/issues/5 ByteStreamServerChannel.listen. (package:dds/src/dap/protocol_stream.dart:53:24)
https://github.com/microsoft/vscode/issues/6 _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
https://github.com/microsoft/vscode/issues/7 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
https://github.com/microsoft/vscode/issues/8 _DelayedData.perform (dart:async/stream_impl.dart:515:14)
https://github.com/microsoft/vscode/issues/9 _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
https://github.com/microsoft/vscode/issues/10 _PendingEvents.schedule. (dart:async/stream_impl.dart:591:7)
https://github.com/microsoft/vscode/pull/11 _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
https://github.com/microsoft/vscode/issues/12 _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
https://github.com/microsoft/vscode/issues/13 _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
https://github.com/microsoft/vscode/issues/14 _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
---------------------------------------------------------------------------------------------------------
Code RUNS OK  when we run this code via CMD by running this command "dart run filename.dart"

**Comment by DanTup** [comment]
By default, the application runs without a terminal. The "Debug Console" where you're typing is a REPL that evaluates expressions and prints the results.

If you need to read from stdin, you need to tell the extension you want to run inside a terminal instead. There may be reduced functionality in that mode as the debugger will have less access to the output from the process.

There are two ways to run in the terminal - one is with the `console` field in a `launch.json` and the other is using the `dart.cliConsole` setting that can be set in your VS Code User Settings or Workspace Setting (depending on whether you want it to apply to all projects or just this one).

More info can be found here: https://dartcode.org/docs/running-in-terminal/
