### ISSUE TITLE
Syntax highlighting issue when using an inline comment with TODO 

### ISSUE THREAD

**Issue by osaxma** [Dart-Code/Dart-Code#4918]
**Describe the bug**
Using an inline comment with TODO causes the code after the comment to be highlighted as a comment:

<img width="401" alt="Screen Shot 2023-12-27 at 7 27 21 PM" src="https://github.com/Dart-Code/Dart-Code/assets/46427323/07a7a8f7-5707-41ec-a160-860bac8158b6">

**To Reproduce**
Sample code: 
```dart
abstract class SomeClass {
  void someMmethod(/* TODO */ String arg);
  void anotherMethod(/* NOT-TODO */ String arg);
}
```

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.80.0
Flutter extension: 3.80.0 (not activated)

App: Visual Studio Code
App Host: desktop
Version: mac 1.85.1

Workspace type: Dart (LSP)

Dart (3.2.0): /Users/osaxma/fvm/versions/stable/bin/cache/dart-sdk
Flutter (3.16.0): /Users/osaxma/fvm/versions/stable (No device)

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`/Users/osaxma/fvm/versions/stable/bin/cache/dart-sdk/bin/dart info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.2.0 (stable) (Tue Nov 14 18:26:59 2023 +0000) on "macos_x64"
- on macos / Version 12.7 (Build 21G816)
- locale is en

#### Project info

- sdk constraint: '^3.2.0'
- dependencies: 
- dev_dependencies: lints, test

#### Process info

| Memory |  CPU | Elapsed time | Command line                                                                    |
| -----: | ---: | -----------: | ------------------------------------------------------------------------------- |
|  51 MB | 0.0% |        15:22 | dart devtools --machine --allow-embedding --port 9100                           |
| 565 MB | 0.0% |        15:22 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.78.2 |
| 377 MB | 0.0% |        01:40 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.80.0 |
| 128 MB | 1.5% |        15:22 | flutter_tools.snapshot daemon                                                   |

</details>

**Comment by DanTup** [comment]
I don't seem to be able to repro this:

### Without semantic tokens:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/5af90d03-007c-4866-960d-491db56f58cc)


### With semantic tokens:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/864f8b88-7111-4b72-9c3f-fb0e04a428b4)

Could you confirm which theme you're using, and what other extensions you have installed? (do you have any TODO-related extensions or anything that may change styling in any way?)

**Comment by osaxma** [comment]
> Do you have any TODO-related extensions or anything that may change styling in any way?

Apparently, yes I have Todo Tree: 
https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree

disabling it fixed the issue. Should I re-file there?

**Comment by DanTup** [comment]
Yep, I would. My guess is that they're just assuming all TODOs are in line comments (which go to the end of the line). They'd probably need to make some assumptions about the comment markers of each file to know where they really end.

(although, it's also not clear to me why they're affecting the colouring at all, unless they normally would be changing the colour of the TODOs?)
