### ISSUE TITLE
Weird font rendering issue in console on failed test

### ISSUE THREAD

**Issue by lukehutch** [Dart-Code/Dart-Code#4919]
**Describe the bug**

When a test fails, while running an individual test in the Flutter framework, the console font gets rendered with metrics twice what they should be. Additionally, text selection weirdly selects two regions. See video below.

**To Reproduce**

* Check out the Flutter source code
* Run a test inside `packages/flutter`, e.g. one in `packages/flutter/test/material/refresh_indicator_test.dart`
* Change the test so that it fails, and run it again
* Observe the broken console behavior.

**Screenshots**

https://github.com/Dart-Code/Dart-Code/assets/811305/5ede2fbb-30de-4bb2-ad60-bac3f543708b

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.81.20231227
Flutter extension: 3.81.20231227 (activated)

App: Visual Studio Code
App Host: desktop
Version: linux 1.85.1

Workspace type: Dart, Flutter (LSP)

Dart (3.3.0-174.3.beta): /opt/flutter/bin/cache/dart-sdk
Flutter (3.18.0-0.2.pre): /opt/flutter (sdk gphone x86 64 (android-x64/android))

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`/opt/flutter/bin/cache/dart-sdk/bin/dart info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.3.0-174.3.beta (beta) (Tue Dec 12 14:49:22 2023 +0000) on "linux_x64"
- on linux / Linux 6.5.12-300.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Nov 20 22:44:24 UTC 2023
- locale is en_US.utf8

#### Process info

|  Memory |   CPU | Elapsed time | Command line                                                                               |
| ------: | ----: | -----------: | ------------------------------------------------------------------------------------------ |
|  556 MB |  0.0% |   9-00:37:39 | dart --enable-vm-service=0 --pause_isolates_on_start --disable-dart-dev -DSILENT_VM_SERVICE=true --write-service-info=file:<path>/vm.json --pause_isolates_on_exit --enable-asserts <path>/main.dart |
|  722 MB |  0.0% |   9-00:49:01 | dart ..<path>/serverpod_cli.dart generate --watch                                          |
|   81 MB |  0.0% |   9-00:37:39 | dart debug_adapter                                                                         |
|   64 MB |  0.0% |  12-23:58:38 | dart devtools --machine --allow-embedding                                                  |
|   63 MB |  0.0% |  12-23:58:30 | dart devtools --machine --allow-embedding                                                  |
|   68 MB |  0.0% |        11:58 | dart devtools --machine --allow-embedding                                                  |
| 3229 MB |  0.2% |  12-23:58:38 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.79.20231206     |
| 1724 MB |  0.0% |  12-23:58:30 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.79.20231206     |
| 1969 MB | 23.2% |        11:58 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.81.20231227     |
|   95 MB |  0.0% |  12-23:58:38 | flutter_tools.snapshot daemon                                                              |
|   95 MB |  0.0% |  12-23:58:30 | flutter_tools.snapshot daemon                                                              |
|   82 MB |  0.2% |        11:58 | flutter_tools.snapshot daemon                                                              |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`/opt/flutter/bin/flutter doctor -v`

```text
[✓] Flutter (Channel beta, 3.18.0-0.2.pre, on Fedora Linux 39 (Workstation Edition) 6.5.12-300.fc39.x86_64, locale en_US.utf8)
    • Flutter version 3.18.0-0.2.pre on channel beta at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fed06b31d9 (2 weeks ago), 2023-12-13 14:53:33 -0800
    • Engine revision 39c6dc9bdd
    • Dart version 3.3.0 (build 3.3.0-174.3.beta)
    • DevTools version 2.30.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/luke/Android/Sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 17.0.4 (Fedora 17.0.4-1.fc39)
    • cmake version 3.27.7
    • ninja version 1.11.1
    • pkg-config version 1.9.5

[✓] Android Studio (version 2022.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 73.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.85.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.81.20231227

[✓] VS Code (version 1.86.0-insider)
    • VS Code at /usr/share/code-insiders
    • Flutter extension version 3.79.20231130

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Linux (desktop)            • linux         • linux-x64      • Fedora Linux 39 (Workstation Edition) 6.5.12-300.fc39.x86_64
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 119.0.6045.159

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by lukehutch** [comment]
Actually this seems to be only a problem with the "TEST RESULTS" tab, and it is consistently broken on ever test run.

**Comment by lukehutch** [comment]
The metrics are not consistently doubled.

![image](https://github.com/Dart-Code/Dart-Code/assets/811305/076d1385-bed0-44e3-9d42-78d7a5174336)

**Comment by DanTup** [comment]
Sorry for the delay. This appears to be a VS Code issue (because it's the same content shown in both the error popup and the test results pane).

There are some existing issues here:

- https://github.com/microsoft/vscode/issues/200703
- https://github.com/microsoft/vscode/issues/194156
