### ISSUE TITLE
The fix for ignoring a lint places the `ignore: <lint>` in a wrong place for an annotated members

### ISSUE THREAD

**Issue by osaxma** [Dart-Code/Dart-Code#4921]
**Describe the bug**

For annotated members, an `ignore: <lint>` comment should be placed between the annotation and the member, but the fix places it above the annotation as shown here:

https://github.com/Dart-Code/Dart-Code/assets/46427323/eb3f751c-a052-4d2a-92c4-790ded3f2551

**To Reproduce**
Sample code: 

```dart
class A {
  void x() {}
}

class B extends A{
  // <~~~ the fix places `ignore` here
  @override
  // <~~~ though it's supposed to be here to work
  void x() => super.x();
}
```

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.80.0
Flutter extension: 3.80.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: mac 1.85.1

Workspace type: Flutter (LSP)

Dart (3.2.3): /Users/osaxma/fvm/versions/stable/bin/cache/dart-sdk
Flutter (3.16.5): /Users/osaxma/fvm/versions/stable (macOS (darwin/macos))

```

</details>

**Comment by DanTup** [comment]
Thanks - it's possible this was fixed as part of https://github.com/Dart-Code/Dart-Code/issues/4775 (https://github.com/dart-lang/sdk/commit/260b9b18f55a7e0e2ee88eb38ff613dfd1fbb706), but I'll have to test with latest code to check.

**Comment by DanTup** [comment]
Yep, I can repro on stable but it's working correctly on a bleeding-edge SDK:

https://github.com/Dart-Code/Dart-Code/assets/1078012/85090722-f1c9-4bdb-85f4-fa5eba102cfc
