### ISSUE TITLE
dart in VSCode telling me to add const modifier when it shouldn't be

### ISSUE THREAD

**Issue by vatlnetwork** [Dart-Code/Dart-Code#4922]
In VSCode, I am getting a warning from dart saying that I should add const to the beginning of my array. When I add const my app throws an error because the functions cannot be const. I suspect it has something to do with the if statements being there. I am not sure if this is a bug, or If I just don't know how to do this right. See attached screenshot.
![image](https://github.com/Dart-Code/Dart-Code/assets/72619693/6fc8fab5-bb1d-42f4-b8be-dd9c15c30407)

**Comment by DanTup** [comment]
Are you able to provide a small code sample I can test with that triggers this? I tried something similar to the code in your screenshot but I wasn't able to trigger the `prefer_const_literals_to_create_immutables` diagnostic that you have.

Thanks!

**Comment by vatlnetwork** [comment]
`import 'package:firebase_ui_auth/firebase_ui_auth.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class TopBar {
  AppBar appBar(BuildContext context) {
    return AppBar(
      actions: [
        if (kIsWeb) _deliveriesButton(context),
        if (kIsWeb) _subscriptionsButton(context),
        if (kIsWeb) _discoverButton(context),
        const SignOutButton(),
      ],
    );
  }

  Widget _deliveriesButton(BuildContext context) {
    return Container();
  }

  Widget _subscriptionsButton(BuildContext context) {
    return Container();
  }

  Widget _discoverButton(BuildContext context) {
    return Container();
  }
}`

This code causes that issue to arise for me. I have never seen this issue anywhere except in this file, so maybe this is a special case or something. It could also just be something to do with my environment. I am running Linux (Fedora 39) with the latest stable version of VSCode from snap and the latest dart / flutter extensions for VSCode.

**Comment by DanTup** [comment]
Thanks - assuming the compiler is correct, this seems like a linter issue so I've opened https://github.com/dart-lang/linter/issues/4844.
