### ISSUE TITLE
Customize closing labels

### ISSUE THREAD

**Issue by jpenna** [Dart-Code/Dart-Code#4923]
Hello,

I don't like closing labels being prefixed by `//` (comment notation), since they are not comments. Could I send a PR to configure the notation I'd like to use with it? In my case, I think I'd prefer setting `--`.

The comment below also mentions the same issue:
@gspencergoog in https://github.com/Dart-Code/Dart-Code/issues/445#issuecomment-410079886

**Comment by DanTup** [comment]
There's an existing issue at #3628 requesting this, but also some comments about allowing more customisation of the colour/font/size. It probably makes sense to tackle them together.
