### ISSUE TITLE
Extending a sealed class in current library but in another file

### ISSUE THREAD

**Issue by pavlov061356** [Dart-Code/Dart-Code#4928]
Hello. i would report an issue with dart analyser. It is related to dart 3.0 feature of sealed classes. I have a project with library structure which defines some models for my app. There is a model called BaseModel which is marked sealed. and a model called Model which extends BaseModel, but when I structure files to separate directories analyes shows me an error `The class 'BaseModel' can't be extended, implemented, or mixed in outside of its library because it's a sealed class`. Wheter both of these classes are in the same library.

1. Clone the repository: `https://github.com/pavlov061356/sealed_class_with_library`
2. Wait for the analyser
3. See the error

**Expected behavior**
Since it Model and BaseModel are int the same library I want to extend BaseModel, but i can`t.

**Please complete the following information:**

 - Ubuntu 22.04.3 LTS x86_64 - 
 - VS Code version: 1.80.0-1688479026
 - Dart extension version: v3.80.0
 - Dart SDK version: 3.1.5 (stable) (Tue Oct 24 04:57:17 2023 +0000) on "linux_x64"

**Comment by DanTup** [comment]
It doesn't appear that these classes are in the same library. By default, each file is its own library. You can split libraries across files by using `part` and `part of`, however these are [recommended against](https://dart.dev/guides/libraries/create-packages#:~:text=avoid%20using%20part%20and%20create%20mini%20libraries%20instead).

So I think you'll either need to use `part`/`part of` to make them the same library (not recommended) or put them in the same file (or, unseal the class).

Hope this helps!
