### ISSUE TITLE
Cant get Flutter working in VS Code

### ISSUE THREAD

**Issue by PaulPetersenAtTheAA** [Dart-Code/Dart-Code#4929]
Cannot create a "Flutter:New Project" in VS Code

**To Reproduce**
1. Install VS Code
2. Install Flutter Extension
3. Follow instructions to create a new project https://docs.flutter.dev/get-started/install/windows/web#troubleshoot-flutter-doctor-issues
4. Flutter: New Project gives a popup alert "Could not find Dart in your Flutter SDK. Please run 'flutter doctor' in the terminal then reload the project once all issues are resolved."
5. Go to terminal and run 'flutter doctor'
6. PS C:\Users\PETERSEP> flutter doctor
flutter : The term 'flutter' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct 
and try again.
At line:1 char:1
+ flutter doctor
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (flutter:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
7 Raise an issue and start googling about bin folders and PATH environment variable
8 :-(

**Expected behavior**
Install Flutter Extension
follow instructions for a new project
Have a working flutter project

**Screenshots**
![image](https://github.com/Dart-Code/Dart-Code/assets/45359836/d8a913b3-8b22-4ee3-8c8f-4160d181c4a3)

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

PS C:\Users\PETERSEP> Dart: Collect Diagnostic Information
Dart: : The term 'Dart:' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and 
try again.
At line:1 char:1
+ Dart: Collect Diagnostic Information
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (Dart::String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

why so difficult 👎

**Comment by PaulPetersenAtTheAA** [comment]
when I restart it is talking about "uanble to find git in your PATH

![image](https://github.com/Dart-Code/Dart-Code/assets/45359836/64350b62-17f1-4e92-8247-814999061e35)

confirm I have git

![image](https://github.com/Dart-Code/Dart-Code/assets/45359836/d96ca86d-de2d-4f16-8d8c-1e2097fd1fbe)

**Comment by DanTup** [comment]
Hi,

The reason `flutter` doesn't work in your terminal yet is that the terminal was created before Flutter was installed. VS Code doesn't allow us to add to the `PATH` of existing terminals so it shows a warning here:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/2cc91722-5b14-40e0-a594-bb76e231ec76)

If you hover over that, it should tell you that the Dart extension wants to update the `PATH` and you need to recreate the terminal


The second issue you posted appears to be that Git is not installed or not in your PATH. This is listed as a requirement here:

https://docs.flutter.dev/get-started/install/windows/web#software-requirements

You may have to reboot after installing Git for it to apply to `PATH` correctly.

**Comment by DanTup** [comment]
> confirm I have git

GitHub Desktop is not the same as having Git on your command line. Although GitHub desktop does ship with its own internal version of Git, it does not get added to `PATH` and does not have a stable folder name for you to add it yourself, unfortunately.

**Comment by PaulPetersenAtTheAA** [comment]
Thanks for the quick response Dan, Ive done the New Project a few times - something more seems to be happening now but no code created

Checking Dart SDK version... 
Downloading Dart SDK from Flutter engine ... 
Expanding downloaded archive with PowerShell...
Building flutter tool... 
Running pub upgrade... 
Resolving dependencies...
Got dependencies.
Downloading Material fonts...                                      713ms
Downloading Gradle Wrapper...                                       32ms
Downloading package sky_engine...                                  146ms
Downloading flutter_patched_sdk tools...                           393ms
Downloading flutter_patched_sdk_product tools...                   337ms
Downloading windows-x64 tools...                                    3.8s
Downloading windows-x64/font-subset tools...                       257ms
[!] Flutter (Channel stable, 3.16.5, on Microsoft Windows [Version 10.0.19045.3693], locale en-GB)
    • Flutter version 3.16.5 on channel stable at C:\Users\PETERSEP\.vscode\extensions\dart-code.flutter-3.80.0\flutter
    ! The flutter binary is not on your path. Consider adding C:\Users\PETERSEP\.vscode\extensions\dart-code.flutter-3.80.0\flutter\bin to your path.
    ! The dart binary is not on your path. Consider adding C:\Users\PETERSEP\.vscode\extensions\dart-code.flutter-3.80.0\flutter\bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (3 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\PETERSEP\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Enterprise 2022 17.4.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Enterprise
    • Visual Studio Enterprise 2022 version 17.4.33110.190
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.85.1)
    • VS Code at C:\Users\PETERSEP\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.80.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.3693]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 109.0.5414.120
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 120.0.2210.121

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
exit code 0

**Comment by PaulPetersenAtTheAA** [comment]
Oh there was a prompt at the top of VS Code waiting for me to choose a template

**Comment by PaulPetersenAtTheAA** [comment]
I chose one and now have code... and it runs

![image](https://github.com/Dart-Code/Dart-Code/assets/45359836/e2c4240e-4a42-46ca-b0a0-2d94c51b8012)

**Comment by PaulPetersenAtTheAA** [comment]
Thanks Dan, that powershell thing didnt come back after restarting VS Code, I have been trying to get this working on and off for a day now so perhaps the instructions arent clear, I did check the prerequisites so I'd suggest having ways of checking and a few more screenshots. Searching the internet tells me Im not the only "user error" ;-)

**Comment by DanTup** [comment]
> Oh there was a prompt at the top of VS Code waiting for me to choose a template

Yeah, unfortunately some of these UI elements in VS Code are not as obvious as I'd like them to be, but unfortunately we don't have much control over the UI (or how we can ask for input).

There may be some changes to how New Project works in the future that might help here, but nothing has been started yet.
