### ISSUE TITLE
Dart: Sort Members - Account for sort_constructors_first lint

### ISSUE THREAD

**Issue by Number-3434** [Dart-Code/Dart-Code#4934]
The <kbd><kbd>Dart</kbd> > <kbd>Sort Members</kbd></kbd> command should take into account [sort_constructors_first](https://dart.dev/tools/linter-rules/sort_constructors_first).

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/97dafd74f51b8f8885dd8dfbef44db3e99a449aa

Because the change is in the Dart SDK, it'll ship in a future SDK release.
