### ISSUE TITLE
Documentation Comments: Render Table Lines

### ISSUE THREAD

**Issue by Number-3434** [Dart-Code/Dart-Code#4937]
Render table lines in documentation comments.

E.g.

Foo | Bar
--- | ---
foo | bar

**Comment by DanTup** [comment]
Assuming you mean in the editor hovers, we unfortunately have no control over the Markdown rendering - that's all done by VS Code (we just return the raw markdown and it converts it to HTML).

**Comment by Number-3434** [comment]
Yeah, I had a feeling I may need to transfer this issue to the markdown engine. I just wasn't too sure whether it was actually there or here

**Comment by DanTup** [comment]
To be clear, the markdown rendering is done by VS Code, not the Dart markdown package. You'd need to raise an issue at https://github.com/microsoft/vscode for something like this.

Closing this as I don't think there's anything to do here (in the VS Code extension), but let me know if you think I've misunderstood something. Thanks!
