### ISSUE TITLE
Destructured record fields are not shown in the completion

### ISSUE THREAD

**Issue by incendial** [Dart-Code/Dart-Code#4940]
Hi, for some reason completion stops working for destructured records. (I guess it has something to do with `ForEachPartsWithPattern`)
```dart
void main() {
  final list = [1, 2, 3];

  for (final (index, item) in list.indexed) {
    item // <-- try typing
  }
}
```

Expected:
<img width="320" alt="Screenshot 2024-01-15 at 14 45 35" src="https://github.com/Dart-Code/Dart-Code/assets/21116742/7bb114d7-dfb6-46b1-bed6-ffbca14a006f">

Actual (with destructuring):
<img width="397" alt="Screenshot 2024-01-15 at 14 46 18" src="https://github.com/Dart-Code/Dart-Code/assets/21116742/df28c298-2628-4bca-a0ea-4160fa696cac">

**Please complete the following information:**

```text
Dart Code extension: 3.80.0

App: Visual Studio Code
App Host: desktop
Version: mac 1.85.1

Workspace type: Dart (LSP)

Dart (3.3.0-174.3.beta): /Users/dimannich/Desktop/flutter/bin/cache/dart-sdk
Flutter (3.18.0-0.2.pre): /Users/dimannich/Desktop/flutter (No device)

```

**Comment by incendial** [comment]
@DanTup hm, my actual dart version is `Dart SDK version: 3.2.4 (stable) (Thu Dec 21 19:13:53 2023 +0000) on "macos_x64"`

Is there a bug with caching?

**Comment by DanTup** [comment]
I see the same bug (on a recent bleeding edge build):

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/3814829b-6595-4b06-899f-f3a8577a9345)

This seems like a server issue (and one I'm not sure of the correct fix for) - could you file with the example above at https://github.com/dart-lang/sdk? Thanks!

**Comment by incendial** [comment]
> Do you have multiple versions

No. Both flutter and dart version point out to the flutter SDK.

I think the case was that I opened VS Code, updated the Flutter SDK via `flutter upgrade` in a macos terminal and then collected diagnostics without restarting the IDE. So if VS Code has any caching involved, that might be it.

I'll open another issue if I eventually notice this.
