### ISSUE TITLE
Show Why Xcode Build Failed

### ISSUE THREAD

**Issue by Number-3434** [Dart-Code/Dart-Code#4941]
**Is your feature request related to a problem? Please describe.**
It would be useful to show the actual error message if a build fails.

**Describe the solution you'd like**
Debug / show in some the way why the build failed.

**Comment by DanTup** [comment]
Can you give an example of this? (for example a way I can simulate a failure that is not showing the correct output)

I would have expected that build failures already show up (I do see build failures on Windows, for example).

**Comment by Number-3434** [comment]
A common cause of failure for me (I'm using Mac btw) is if dependencies couldn't be found

For example, if you add a dependency that can't be found to the `pubspec.yaml` file, the build will fail without any warning.

**Comment by DanTup** [comment]
> For example, if you add a dependency that can't be found to the pubspec.yaml file, the build will fail without any warning.

Thanks, I'll try that out when next on the Mac and see if I can reproduce.

**Comment by DanTup** [comment]
@Number-3434 I wasn't able to reproduce this.. If I add an invalid package name to my pubspec and try to run, I see an error like this:

![Screenshot 2024-05-09 at 15 16 24](https://github.com/Dart-Code/Dart-Code/assets/1078012/fcd5a570-d622-41d1-ba57-fedcf8831409)

Are you able to show a screenshot of what your Debug Console looks like when you have this issue? Thanks!
