### ISSUE TITLE
Formatting issues after moving widget up/down

### ISSUE THREAD

**Issue by xster** [Dart-Code/Dart-Code#495]
Might be a dart analyzer problem. I'm not sure.

![screen shot 2018-01-08 at 9 01 32 pm](https://user-images.githubusercontent.com/156888/34705856-52739b80-f4b8-11e7-9a88-8f64f5c6e1ca.png)

From here, swapping `Padding` up with `Container`

![screen shot 2018-01-08 at 9 01 43 pm](https://user-images.githubusercontent.com/156888/34705869-64e4ce06-f4b8-11e7-81a1-31ac1f0ec275.png)

**Comment by DanTup** [comment]
When you saw "swapping", do you mean you're just replacing the class names manually? Does the bad formatting persist if you explicitly format the file, or is it just wrong briefly after the edit?

Also; do you have `editor.formatOnType` set to true or false?

**Comment by xster** [comment]
`formatOnType` was false.

By swapping, I meant using the contextual command+. show fixes and then move widget up/down mechanism. 

Formatting the file explicitly leaves a saner output.

**Comment by DanTup** [comment]
Ah, didn't realise there was one. I'll take a look soon, thanks!

(btw, format-on-type is quite good :-)

**Comment by mit-mit** [comment]
cc @DanTup I'd like to nominate this for the current milestone

**Comment by DanTup** [comment]
@xster Do you have some sample code I can repro this with? Tried it in Stocks sample (stock_row.dart) and everything looks correctly formatted.

Otherwise, if you [enable analysis server logging](https://github.com/Dart-Code/Dart-Code/blob/master/CONTRIBUTING.md#enable-logging) you might be able to confirm whether the formatting is bad in the response from the analysis server.

**Comment by DanTup** [comment]
I can't repro this and also suspect it needs fixing in the analyser, so I don't think I can currently progress. @xster if you're able to repro and provide more info (or a log) it should be easy to tell. @mit-mit is this something that might already be being looked at (I think you said @scheglov may be looking at some of these refactorings?)

**Comment by mit-mit** [comment]
I can't repro this anymore either...

**Comment by DanTup** [comment]
Weird - I had a look at the code I think does this ([here](https://github.com/dart-lang/sdk/blame/c9c9e10432d109801ab6087c1a9435c004895e8e/pkg/analysis_server/lib/src/services/correction/assist_internal.dart#L2616)) and doesn't look like it's changed in months.

I'm happy to leave this open for a while to see if anyone can repro and get some logs.

**Comment by scheglov** [comment]
Yes, I think this is an issue in Dart Analysis Server.
Accidentally I was looking for this assist yesterday and so the same problem.

```dart
import 'package:flutter/material.dart';

main() {
  new Column(
    children: [
      new Column(
        children: [
          new Padding(
            padding: new EdgeInsets.all(16.0),
            child: new SliverToBoxAdapter(
              child: new Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: <Widget>[],
              ),
            ),
          ),
        ],
      ),
    ],
  );
}
```

When you try to `Move widget up` on `new SliverToBoxAdapter`, it gives wrongly formatted code.
```dart
import 'package:flutter/material.dart';

main() {
  new Column(
    children: [
      new Column(
        children: [
          new SliverToBoxAdapter(
   child: new Padding(
                       padding: new EdgeInsets.all(16.0),
              child: new Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: <Widget>[],
              ),
            ),
 ),
        ],
      ),
    ],
  );
}
```

https://dart-review.googlesource.com/c/sdk/+/39841 should fix this.

**Comment by DanTup** [comment]
Awesome, thanks! 👍

**Comment by xster** [comment]
I anecdotally confirm too that I haven't seen this issue happen again. Likely just happening on swaps one level next to widgets with children like @scheglov pointed out.
