### ISSUE TITLE
Cannot Scroll in Symbol Preview

### ISSUE THREAD

**Issue by Number-3434** [Dart-Code/Dart-Code#4950]
It is not currently possible to scroll in the symbol preview (accessible by holding down <kbd>Cmd</kbd> and moving the cursor over a symbol).

To reproduce, hold down <kbd>Cmd</kbd>, and move the cursor on top of any locally declared method with a body more than e.g. 10 lines.

---

P.S. Sorry, I forgot to add this as a bug. This should be marked with "is bug" and not "is enhancement".

**Comment by DanTup** [comment]
Do you mean this preview shown in the hover?

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/92302869-4f87-42e2-9089-3b9b6c4f8f71)

If so, this is something controlled by VS Code. When you hold Cmd/Ctrl and Hover, it fetches the definition of the of the symbol at that location. We return the full range of the symbol like this:

```
"targetRange": {
	"end": {
		"character": 1,
		"line": 880
	},
	"start": {
		"character": 0,
		"line": 119
	}
},
```

It seems that VS Code is hard-coded to show only 8 lines from the preview here:

https://github.com/microsoft/vscode/blob/dca6f399d32b5ead87efc32fb2ada736ce9596c3/src/vs/editor/contrib/gotoSymbol/browser/link/goToDefinitionAtPosition.ts#L38

Changing this would need to be a request for VS Code.

**Comment by Number-3434** [comment]
Okay, thanks!
