### ISSUE TITLE
Support DevTools extensions embedded inside VS Code

### ISSUE THREAD

**Issue by kenzieschmoll** [Dart-Code/Dart-Code#4952]
As of https://github.com/flutter/devtools/commit/0fba4006fe0cf21681b0d6ef810366fe9366cd19, DevTools extensions are now shown in the debug session DevTools menu: 
![Screenshot 2024-01-17 at 2 20 53 PM](https://github.com/Dart-Code/Dart-Code/assets/43759233/75f5b310-4a99-4172-8540-e4e6a532552d)

This extension screens open by default in the browser. What will it take to enable extension screens to be opened inside VS code like other devtools screens are?

**Comment by DanTup** [comment]
@kenzieschmoll is there anything special I need to do for this to show up? I'm on latest DevTools and I see my extension when I click "Open in Browser" from the sidebar, but it doesn't show up in the menu itself:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/f3e31d10-adeb-4282-a6ed-c7546a8e7257)

I had a look through https://github.com/flutter/devtools/commit/0fba4006fe0cf21681b0d6ef810366fe9366cd19 but didn't spot any obvious reason for this.

**Comment by DanTup** [comment]
https://github.com/Dart-Code/Dart-Code/assets/1078012/aa024387-627f-4b76-95aa-3b6b25366cec

**Comment by DanTup** [comment]
@kenzieschmoll this is in today's pre-release (3.81.20240130) if you want to try it out.

It inherits the default setting from `dart.devToolsLocation` but 
because of #4387 you can control it individually:

```js
"dart.devToolsLocation": {
	"default": "beside", // default for unlisted pages
	"inspector": "active", // built-in page
	"danny_library_ext": "external", // extension page
}
```
