### ISSUE TITLE
Provide Inline `const` Completions

### ISSUE THREAD

**Issue by Number-3434** [Dart-Code/Dart-Code#4964]
## The Issue

It is cumbersome to constantly have to manually insert the `const` keyword, and it would be much easier if it automatically suggested `const`, and you could just click it to insert.

## Proposal

Add inline `const` keyword suggestions.

These will be shown at the start of a region that triggers [prefer_const_constructors](https://dart.dev/tools/linter-rules/prefer_const_constructors).

Inline `const` suggestions should be in the same place the `const` keyword would normally be expected.

For example, the below code:

```dart
@override
Widget build(context) {
  return IgnorePointer();
}
```

...should have an inline `const` suggestion like:

```dart
@override
Widget build(context) {
  return const IgnorePointer();
}
```

The `const` keyword above should actually be an inline suggestion.

Clicking the inline `const` should insert it.

Note that the inline `const` suggestions should ideally be independant from the `editor.inlayHints.enabled` setting.

**Comment by DanTup** [comment]
It's difficult to use Inlay Hints for anything other than types/parameters right now because there's no way to control the styling (see https://github.com/microsoft/vscode/issues/151920).

That said, I worry that showing an inline "const" where there is _not_ one, would make it seem like it is an _implied_ `const` when it is not. The type/param hints are both showing things that are implied.

Is there an advantage to the way suggested above versus just using something like fix-on-save to automatically add them? That avoids any ambiguity over whether the inlay hint is showing that `const` is implied or not.

**Comment by Number-3434** [comment]
Yeah, fix-on-save specifically for `const`s would be nice, I just don't use fix-on-save as it incurs a lag.

**Comment by DanTup** [comment]
> I just don't use fix-on-save as it incurs a lag.

Do you see this only after you've just opened the project (where initial analysis is still in progress), or more frequently?

**Comment by Number-3434** [comment]
More frequently. The lag is only slight (~400ms), but every time I save a file, it also formats it (10-700ms), and also the lag is very inconsistent.

**Comment by DanTup** [comment]
@Number-3434 any info on the above?

>  I don't suppose you've noticed any patterns to it occurring (for example is it on particular projects, or after other specific actions that might have triggered extra work in the server)?

**Comment by DanTup** [comment]
> I think it may have been part of a separate bug in which formatting only the parts that have changed in a file is much slower than formatting the entire document in one go.

Ah, interesting - if you can repro this I would be interesting in a bug report with some details for me to test with. I don't think the LSP server has an API for doing multiple ranges so I wonder if VS Code is sending a repeated set of requests or something. If you can help me repro, I can take a look.

Shall we close this one and file new issues about the performance if that was the real motivation here?

**Comment by Number-3434** [comment]
Yeah
