### ISSUE TITLE
Unable to run dart application

### ISSUE THREAD

**Issue by ZheTaoGuo** [Dart-Code/Dart-Code#4965]
**Describe the bug**
Encountered this error even though flutter doctor states all installation is fine 

![Screenshot 2024-01-30 at 12 48 45 AM](https://github.com/Dart-Code/Dart-Code/assets/32319081/1e616334-a954-4d25-8e57-cc42f2b6469f)
![Screenshot 2024-01-30 at 12 49 45 AM](https://github.com/Dart-Code/Dart-Code/assets/32319081/bcbb01a3-7171-4a01-ac54-8c5ceb1e8a48)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

 - Operating System and version: M1 Pro MacOS Sonoma 14.2.1
 - VS Code version: 1.85.2
 - Dart extension version: 3.80.0
 - Dart/Flutter SDK version:3.2.6 
 - Target device (if the issue relates to Flutter debugging): Chrome

**Comment by DanTup** [comment]
Can you post a copy of your `pubspec.yaml`? Thanks!

**Comment by DanTup** [comment]
Oh, also please check if you have Code Runner installed and are trying to start the application using its button. The Code Runner extension will always try to run the app using `dart` (because it doesn't understand Flutter). There's some more info about this here:
    - https://github.com/Dart-Code/Dart-Code/issues/4323
    - https://github.com/formulahendry/vscode-code-runner/issues/674
