### ISSUE TITLE
Global `search.exclude` setting not respected 

### ISSUE THREAD

**Issue by JulindM** [Dart-Code/Dart-Code#4969]
Setting the `files.exclude` in the `setting.json` in vscode makes `search.exclude` to inherit the values and exlude the glob patterned files defined there.

For example adding the following excludes:
```json
"files.exclude": {
    ...
    "**/build/": true,
    "**/dart_tool/": true,
    "**/flutter/": true,
    "**/pub.dev/": true,
    "**/fvm/": true,
    "**/.pub-cache/": true
    ...
}
```
I expect when calling quick open, with the setting to include symbols turned on, **to not show results from these folders**.

![Screenshot 2024-01-31 at 13 13 08](https://github.com/Dart-Code/Dart-Code/assets/11739524/ad691cf1-9262-4abb-b4a0-cdb87e4e6aa8)

This is an example of the unwanted population I encounter. The packages fill the quick open list so much the project files which I am most interested in are shoved down below and I am forced to be much more precise in my search queries.

I am also using `fvm` for my flutter version management, but files from `~/.pub-cache` show up there as well.

---

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.80.0
Flutter extension: 3.80.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: mac 1.85.2

Workspace type: Flutter (LSP) (Multiroot)

Dart (3.2.3): /Users/julind/fvm/versions/3.16.5/bin/cache/dart-sdk
Flutter (3.16.5): /Users/julind/fvm/versions/3.16.5 (Chrome (web-javascript/web))

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`/Users/julind/fvm/versions/3.16.5/bin/cache/dart-sdk/bin/dart info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.2.3 (stable) (Tue Dec 5 17:58:33 2023 +0000) on "macos_arm64"
- on macos / Version 14.3 (Build 23D56)
- locale is en-DE

#### Project info

- sdk constraint: '>=3.2.3 <3.3.0'
- dependencies: cloud_firestore, collection, cupertino_icons, dio, dotted_line, email_validator, file_picker, firebase_app_check, firebase_auth, firebase_core, firebase_storage, firebase_storage_web, fl_chart, flutter, flutter_form_builder, flutter_image_slideshow, flutter_json_viewer, flutter_redux, fluttertoast, form_builder_validators, google_fonts, google_maps_flutter, google_maps_flutter_web, http, image, intersperse, intl, material_color_generator, multi_dropdown, multi_select_flutter, number_inc_dec, numeric_keyboard, overlay_dialog, patterns_canvas, pointer_interceptor, qr_flutter, quiver, redux, redux_persist, redux_persist_flutter, redux_thunk, rxdart, tuple, url_launcher, uuid
- dev_dependencies: flutter_lints, flutter_test
- elided dependencies: 4

#### Process info

| Memory |  CPU | Elapsed time | Command line                                                                    |
| -----: | ---: | -----------: | ------------------------------------------------------------------------------- |
|  65 MB | 0.0% |        16:17 | dart devtools --machine --allow-embedding                                       |
| 956 MB | 0.0% |        16:17 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.80.0 |
| 139 MB | 1.3% |        16:17 | flutter_tools.snapshot daemon                                                   |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`/Users/julind/fvm/versions/3.16.5/bin/flutter doctor -v`

```text
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.3 23D56 darwin-arm64, locale en-DE)
    • Flutter version 3.16.5 on channel stable at /Users/julind/fvm/versions/3.16.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (6 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /opt/homebrew/share/android-commandlinetools
    • Platform android-34, build-tools 33.0.2
    • ANDROID_HOME = /opt/homebrew/share/android-commandlinetools
    • Java binary at: /opt/homebrew/opt/openjdk@17/bin/java
    • Java version OpenJDK Runtime Environment Homebrew (build 17.0.9+0)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Chromium.app/Contents/MacOS/Chromium

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2023.3.2)
    • IntelliJ at /Users/julind/Applications/IntelliJ IDEA Community Edition.app
    • Flutter plugin version 77.0.1
    • Dart plugin version 233.13135.65

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (3 available)
    • Julind's iPhone (mobile) • 00008110-0002601E0269801E • ios            • iOS 17.3 21D50
    • macOS (desktop)          • macos                     • darwin-arm64   • macOS 14.3 23D56 darwin-arm64
    • Chrome (web)             • chrome                    • web-javascript • Chromium 121.0.6167.85

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by DanTup** [comment]
This is a VS Code setting and doesn't apply to Go to Symbol. The text for the setting notes:

> Search: Exclude
> Configure glob patterns for excluding files and folders in fulltext searches and quick open.

Both fulltext searches and Quick Open are VS Code functionality (quick-open is the file picker to jump to a file). There are some relevant comments in https://github.com/microsoft/vscode/issues/46718 from the VS Code team:

- https://github.com/microsoft/vscode/issues/46718#issuecomment-376957636
- https://github.com/microsoft/vscode/issues/46718#issuecomment-443908944
- https://github.com/microsoft/vscode/issues/46718#issuecomment-607083859
- https://github.com/microsoft/vscode/issues/46718#issuecomment-625638488

In particular:

> Ok - thanks for clarifying. If you ask me what a language extension should do, then I would recommend to rely on a project config, not on vs code config, esp in the name of LSP and potentially different front ends

The search is handled by the Dart LSP server which is written to be generic and not specific to VS Code. It should not depend on VS Code-specific settings.

However, we do have a setting `"dart.includeDependenciesInWorkspaceSymbols"` that you can use to exclude _all_ files that are not in your current workspace. I personally prefer this, but some prefer being able to jump to classes from the Flutter framework, etc.

**Comment by JulindM** [comment]
Thank you a lot, `"dart.includeDependenciesInWorkspaceSymbols"` did the trick!
