### ISSUE TITLE
VS Code theme changes do not apply to embedded DevTools until the window is reloaded/recreated

### ISSUE THREAD

**Issue by kenzieschmoll** [Dart-Code/Dart-Code#4971]
DevTools screens (static and runtime) will stay in the theme (dark or light) that they were opened in. So when changing the IDE theme in VS code, these are the wrong color.

<img width="1258" alt="Screenshot 2024-01-31 at 9 28 42 AM" src="https://github.com/Dart-Code/Dart-Code/assets/43759233/02f4747e-d5e6-4d99-b676-96923de6b49a">

**Comment by DanTup** [comment]
Does this persist if you reload VS Code? I think right now we only set the theme as the windows are open and don't update live, however Nancy had a theme issue I couldn't repro (see comments at https://github.com/flutter/devtools/issues/6563#issuecomment-1792658724).

**Comment by kenzieschmoll** [comment]
> Does this persist if you reload VS Code?

No, reloading the IDE loads the correct theme.

**Comment by DanTup** [comment]
@kenzieschmoll I think we have two options here:

1. We reload all embedded Windows with the new theme on the querystring
2. We have some API to update the theme

The first is easiest, but it means you'll lose any state of what's in the window. The second (assuming DevTools is able to update the theme on the fly) would look much better, but would need an API. We already have some postMessage API for embedded DevTools (to handle copying to clipboard and opening URLs), although they're all DevTools -> VS Code, and this would go the other way.

**Comment by kenzieschmoll** [comment]
Option 2 would be better. Maybe we should wait for DTD to be hooked up so that DevTools can register a method on DTD 'updateTheme', that the IDEs can call on theme changes. We would need to make sure that the theme update only happens when we are in embedded mode though. I think it would be strange to have DevTools open in the browser and see the DevTools theme change because you changed your IDE theme.

**Comment by DanTup** [comment]
Maybe some of these things should live outside DTD? For example DevTools posts keypresses up to VS Code so you can still open the command palette when an embedded window has focus. It also has some handling to trigger clipboard writes. Those things probably don't make sense to go via DTD, so maybe we should continue with a small postMessage API where the messages are very specific for the embedded case? 🤔

**Comment by DanTup** [comment]
Splitting sidebar into its own issue at https://github.com/Dart-Code/Dart-Code/issues/5071 since that has a simple fix - we can just refresh it because it doesn't have much state and everything except the open menus will fix itself backup as part of initialisation. If we switch to a DTD API we can do it more natively.

For embedded windows, refreshing is potentially destructive and I don't think we should just refresh.

**Comment by kenzieschmoll** [comment]
@DanTup can VS Code register a stream on DTD 'IdeThemeChanged' or similar that DevTools can listen to? Then IntelliJ could do something similar since we have the same issue there @helin24

**Comment by kenzieschmoll** [comment]
Or maybe even a more general event IdeNotify with a field in the event payload to specify the type `IdeThemeChange`. This way we can use the same stream for more use cases where the IDE might want to notify DevTools of something.

**Comment by DanTup** [comment]
Yeah, I think something along those lines. There are some slightly awkward things here though... In VS Code, we can't access information about the theme from the extension (it's a long-standing request I'm not sure will ever be implemented - see https://github.com/microsoft/vscode/issues/32813), but in the webview there are some CSS variables and class names we can read.

So we can detect the theme change _inside the webview_ (which is what my current sidebar fix for https://github.com/Dart-Code/Dart-Code/issues/5071 does using a MutationObserver and then refreshes the frame) and we could post it back up to the extension to then forward over DTD. We'd need to ensure we handle 0, 1 and >1 webviews being loaded at the time the theme changes (possibly it'll "just work").

**Comment by DanTup** [comment]
Latest version of Dart-Code/Flutter master will use DTD for the sidebar. We should look at defining an event for the Editor stream for the theme changing (and documenting it at https://github.com/dart-lang/sdk/blob/main/pkg/dtd_impl/dtd_common_services_editor.md).

Then, the DTD version of the sidebar can listen for this event and do whatever it needs to do apply the theme change without any reload.

**Comment by kenzieschmoll** [comment]
SGTM. This would also fix https://github.com/flutter/flutter-intellij/issues/7626

**Comment by helin24** [comment]
@DanTup are you working on defining the event already? If so I'll wait for the change and then add it to IJ.

**Comment by DanTup** [comment]
I hadn't got to it yet, but I had planned. Unfortunately, as with many things, it's complicated in VS Code 😄

We get an event to tell us when the theme changes, but it only tells us that it's light/dark, we can't get at the actual colours. We can only do that inside a webview (which is where we usually read them before passing them on the querystring). So, the theme might change when there are no webviews visible and although we could send an event to dTD, we'd be missing the exact background color etc.

So I think for VS Code we'll only be able to send the event when a webview is visible (and if the theme changes before it's visible, then making it visible will trigger the event).

I'll open a change to document the event first anyway, that can be done without the implementation.

**Comment by DanTup** [comment]
While documenting this, I realised that there are some more nuances to this... In VS Code we have two different background colors - the sidebar is slightly lighter than the editor background. We use both of these colors - the embedded DevTools will use the same one as the editors, and the Flutter sidebar will use the sidebar one:

![image](https://github.com/user-attachments/assets/9a539509-2af4-411d-a553-a4cc7269446a)

So now I'm wondering if DTD is the correct way for this 🤔

**Comment by DanTup** [comment]
To capture some offline discussion:

- we'll support theme changes as an event over DTD and an equiv event over postMessage
- VS Code will use postMessage and provide the correct color for where the page is embedded
- IntelliJ will use DTD
- DevTools will listen for the event in both places, and call shared code (with the same args) to trigger the theme update

**Comment by DanTup** [comment]
I've some PRs in progress that will fix this (including updating the sidebar to no longer refresh, but use the new method, and having different colors for the sidebar/editor to match the surrounding VS Code):

https://github.com/user-attachments/assets/621ae48d-41f4-465d-8881-6238eb4b90c3

- https://github.com/flutter/devtools/pull/8387
- https://github.com/Dart-Code/Dart-Code/pull/5297

**Comment by DanTup** [comment]
This needs the Dart-Code changes to land too.
