### ISSUE TITLE
`title` gets auto-renamed to `label` on save, if there is an error

### ISSUE THREAD

**Issue by lukehutch** [Dart-Code/Dart-Code#4973]
**Describe the bug**

The "before" state of the code:

(after adding `if (title != null)` -- the error on `title` is `The argument type 'String?' can't be assigned to the parameter type 'String'.`):

![image](https://github.com/Dart-Code/Dart-Code/assets/811305/3b6a1103-1deb-49b2-98b9-5f4e5bf9f1c3)

The "after" state of the code:

(after hitting Save -- code is correctly indented, but `title` now becomes `label`, which doesn't even exist in the namespace):

![image](https://github.com/Dart-Code/Dart-Code/assets/811305/aaf433a7-40b3-4d81-baf2-944ec13544e9)

**Please complete the following information:**

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.81.20240131
Flutter extension: 3.81.20231227 (activated)

App: Visual Studio Code
App Host: desktop
Version: linux 1.85.2

Workspace type: Dart, Flutter (LSP) (Multiroot)

Dart (3.3.0-279.0.dev): /opt/flutter/bin/cache/dart-sdk
Flutter (3.19.0-0.1.pre): /opt/flutter (sdk gphone x86 64 (android-x64/android))

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`/opt/flutter/bin/cache/dart-sdk/bin/dart info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.3.0-279.0.dev (dev) (Thu Jan 4 06:34:46 2024 -0800) on "linux_x64"
- on linux / Linux 6.6.9-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Jan  1 20:05:54 UTC 2024
- locale is en_US.utf8

#### Project info

- sdk constraint: '>=3.1.5 <4.0.0'
- dependencies: auto_size_text, boxy, cached_network_image, carousel_slider, collection, cross_file, cupertino_icons, delayed_display, device_info_plus, email_validator, exif, extended_image, flutter, flutter_cache_manager, flutter_email_sender, flutter_localizations, flutter_persistent_value_notifier, flutter_svg, fluttericon, fluttertoast, geocoding, geolocator, getwidget, google_fonts, http, image_picker, intl, jiffy, line_awesome_flutter, logging, material_dialogs, package_info_plus, path_provider, persistent_bottom_nav_bar_v2, provider, random_string, share_plus, shared_preferences, url_launcher
- dev_dependencies: flutter_launcher_icons, flutter_lints, flutter_test, lints
- elided dependencies: 11

#### Process info

|  Memory |  CPU | Elapsed time | Command line                                                                               |
| ------: | ---: | -----------: | ------------------------------------------------------------------------------------------ |
|  527 MB | 0.0% |     07:06:44 | dart --enable-vm-service=0 --pause_isolates_on_start --disable-dart-dev -DSILENT_VM_SERVICE=true --write-service-info=file:<path>/vm.json --pause_isolates_on_exit --enable-asserts <path>/main.dart |
|  712 MB | 0.0% |   3-06:05:08 | dart ..<path>/serverpod_cli.dart generate --watch                                          |
|   82 MB | 0.0% |     07:06:44 | dart debug_adapter                                                                         |
|   73 MB | 0.0% |     16:04:44 | dart devtools --machine --allow-embedding                                                  |
|   71 MB | 0.0% |     15:43:45 | dart devtools --machine --allow-embedding                                                  |
|   78 MB | 0.0% |   7-23:21:07 | dart devtools --machine --allow-embedding --port 9100                                      |
| 2308 MB | 0.1% |   7-23:21:07 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.81.20240117     |
|  411 MB | 0.0% |     16:04:44 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.81.20240131     |
| 2367 MB | 0.8% |     15:43:45 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.81.20240131     |
|   98 MB | 0.0% |     16:04:44 | flutter_tools.snapshot daemon                                                              |
|  124 MB | 0.1% |     15:43:45 | flutter_tools.snapshot daemon                                                              |
|  106 MB | 0.0% |   7-23:21:07 | flutter_tools.snapshot daemon                                                              |
|   91 MB | 0.0% |     13:50:20 | flutter_tools.snapshot debug_adapter                                                       |
|  197 MB | 0.1% |     13:50:20 | flutter_tools.snapshot run --machine --start-paused -d emulator-5554 --devtools-server-address http:<path>/ --target <path>/main.dart |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`/opt/flutter/bin/flutter doctor -v`

```text
[✓] Flutter (Channel beta, 3.19.0-0.1.pre, on Fedora Linux 39 (Workstation Edition) 6.6.9-200.fc39.x86_64, locale en_US.utf8)
    • Flutter version 3.19.0-0.1.pre on channel beta at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1a9a60d044 (3 weeks ago), 2024-01-10 13:38:09 -0800
    • Engine revision bbebee1465
    • Dart version 3.3.0 (build 3.3.0-279.0.dev)
    • DevTools version 2.31.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/luke/Android/Sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 17.0.6 (Fedora 17.0.6-1.fc39)
    • cmake version 3.27.7
    • ninja version 1.11.1
    • pkg-config version 1.9.5

[✓] Android Studio (version 2022.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 73.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.85.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.81.20231227

[✓] VS Code (version 1.86.0-insider)
    • VS Code at /usr/share/code-insiders
    • Flutter extension version 3.79.20231130

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Linux (desktop)            • linux         • linux-x64      • Fedora Linux 39 (Workstation Edition) 6.6.9-200.fc39.x86_64
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 120.0.6099.216

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by DanTup** [comment]
Thanks! There's an existing issue tracking this in the SDK at https://github.com/dart-lang/sdk/issues/54730.

**Comment by lukehutch** [comment]
Oh, oops! I knew I had reported auto-renaming bugs before, but I though this was a different/new one. Thanks.
