### ISSUE TITLE
Causing performence issue

### ISSUE THREAD

**Issue by saksham-81** [Dart-Code/Dart-Code#4977]
Type: <b>Bug</b>

it is taking about 400-800MB of RAM in windows 11

Extension version: 3.82.0
VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:28:19.990Z)
OS version: Windows_NT x64 10.0.22631
Modes: Unsupported

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (1.04GB free)|
|Process Argv|--crash-reporter-id 514bbf8d-6913-4c07-8d4f-6c616dc30e4c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30951796
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019b:30953937
7j2b6412:30949929
ccp2r6:30958158

```

</details>

**Comment by DanTup** [comment]
> it is taking about 400-800MB of RAM in windows 11

Can you confirm exactly what is taking up this RAM?

Are you able to post the full output of running `code --status` when you see this problem?

**Comment by saksham-81** [comment]
![dart](https://github.com/Dart-Code/Dart-Code/assets/157354265/f661a23d-8242-4dff-bd99-3d316943cf30)
only dart and flutter extension enabled and it is consuming this much ram

**Comment by saksham-81** [comment]
and this is when all extension are disabled
![Uploading disabled.png…]()

**Comment by saksham-81** [comment]
and this is when all extensions are disabled
![disabled](https://github.com/Dart-Code/Dart-Code/assets/157354265/e7b6728d-8bc5-4287-92c8-e65101e15f0f)

**Comment by saksham-81** [comment]
and this is with all the other extensions enabled except Dart and Flutter.
![except dart and flutter](https://github.com/Dart-Code/Dart-Code/assets/157354265/de0b5a02-d046-46c1-905e-a085fe70ce9f)

**Comment by DanTup** [comment]
Thanks! The process using 400MB of RAM is the Dart language server (`"C:\Users\chhab\AppData\Local\flutter\bin\cache\dart-sdk\bin\dart.exe"  "language-server"`) which powers the language functionality in the editor (such as Problems, code completion, navigation).

There is some ongoing work to reduce the memory usage of the Dart language server (such as https://github.com/dart-lang/sdk/issues/53874) , but that's mostly for large workspaces with multiple projects and I'm not sure if it will change much here. In my experience, 400MB isn't a lot of memory for the server to use - I see about ~320MB if I create an template Dart project and open it in VS Code.

For comparison, I see similar amounts used by the TypeScript language services when I open the Dart-Code codebase:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/54ed9e92-84ce-4626-b4a0-000a23a1478d)

@bwilkerson @jacob314 may correct me if I'm wrong, but I think this is probably about what's expected and I don't know if there will be much scope to reduce this (at least not without trade-offs that might hurt server performance).
