### ISSUE TITLE
Go to Tests Implementation not working 

### ISSUE THREAD

**Issue by MaurizioSodano** [Dart-Code/Dart-Code#4983]
**Describe the bug**
When I click the context menu "Go To Tests" for a flie that doesn't have one yet, it doesn't show the popup to create a new test file.

However, If the test has been created manually, than the editor shows correctly the test file.

**To Reproduce**

**Expected behavior**
I expect the following popup

**Screenshots**

![dart_test](https://github.com/Dart-Code/Dart-Code/assets/16557320/569855fe-be7f-485e-addb-2bfeaca1068e)

**Please complete the following information:**

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.82.0
Flutter extension: 3.82.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: win 1.86.1

Workspace type: Flutter (LSP)

Dart (3.2.6): C:\Users\Utente\dev\flutter\bin\cache\dart-sdk
Flutter (3.16.9): C:\Users\Utente\dev\flutter (Chrome (web-javascript/web))

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`C:\Users\Utente\dev\flutter\bin\cache\dart-sdk\bin\dart.exe info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.2.6 (stable) (Wed Jan 24 13:41:58 2024 +0000) on "windows_x64"
- on windows / "Windows 10 Pro" 10.0 (Build 22631)
- locale is it-IT

#### Process info

| Memory | CPU | Elapsed time | Command line |
| -----: | --: | -----------: | ------------ |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`C:\Users\Utente\dev\flutter\bin\flutter.bat doctor -v`

```text
[√] Flutter (Channel stable, 3.16.9, on Microsoft Windows [Versione 10.0.22631.3085], locale it-IT)
    • Flutter version 3.16.9 on channel stable at C:\Users\Utente\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (3 weeks ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Utente\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34330.188
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] VS Code (version 1.86.1)
    • VS Code at C:\Users\Utente\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.82.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Versione 10.0.22631.3085]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 121.0.6167.161
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 121.0.2277.112

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by DanTup** [comment]
I'm still seeing this popup:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/d2e085d8-67df-479e-bd16-92f7df671aff)

Can you post a screenshot showing exactly how you're invoking this command (you mention context menu, but as far as I see it's only available in the command palette), and also right-click on the tab for the open file and choose "Copy Relative Path" and paste it here so I can be sure I'm testing with an equivalent path?

Thanks!

**Comment by MaurizioSodano** [comment]
Hi, you can dowload my repo [326b93200c93f7b03691f94131a0cd12e8d8cc5d](https://github.com/MaurizioSodano/flutter_ecommerce_course_2024/tree/326b93200c93f7b03691f94131a0cd12e8d8cc5d)

If you see in the video below, after clicking to "Go To Tests" it doesn't show the popup dialog to create a new onw
https://github.com/Dart-Code/Dart-Code/assets/16557320/294709c6-ea6d-4570-a0e0-dd5fe9055209

If the test already exists intead, it goes to it as expected
https://github.com/Dart-Code/Dart-Code/assets/16557320/854d9c53-d7cb-4493-b1c4-6b5ab62461e1

**Comment by DanTup** [comment]
@MaurizioSodano the file you used as an example doesn't appear to be in the repo. I tested with some other files and it appears to work:


https://github.com/Dart-Code/Dart-Code/assets/1078012/b20a76db-f78c-47d3-9445-e9f7c50e4b7e

Can you check whether it works on the file I used here so we can see if it's specific to the file or not. If that file works, please can you provide an example file where it doesn't work that is in the repo.

**Comment by DanTup** [comment]
Oh, I just noticed there's a line through the notification bell in the bottom right corner of your status bar - it appears that you might be in Do-not-Disturb mode, which will suppress any of these prompts?

**Comment by MaurizioSodano** [comment]
Yes @DanTup, I was going crazy!!!. I had to reanable the notifications.

Many thanks for your time
