### ISSUE TITLE
Add support for spawning the Dart Tooling Daemon and providing the URI to DevTools

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#4984]
- [x] Remove check for devtools_tool after https://github.com/flutter/devtools/pull/7191 lands

**Comment by DanTup** [comment]
@kenzieschmoll @CoderDake this is essentially done (at least, starting the daemon, setting the IDE roots, and passing the URI to DevTools.. I'm not sure if there's more VS Code needs to do at this point?).

I'll push it out in a pre-release of the extension soon - but I'd like https://github.com/flutter/devtools/pull/7191 to land first, just to avoid any issues if using a local custom DevTools with it enabled.

For now, it's behind a flag because I'd like some additional testing beyond my own before we enable it.

**Comment by CoderDake** [comment]
Tested myself and LGTM!
Also looked at the PR that added the changes and it looks right on to me :D

**Comment by DanTup** [comment]
Thanks - do you want me to remove the experimental flag (so from the next release, everyone on master will be spawning the daemon), or do you want me to leave it until there's been more work done (like testing it over longer sessions) first?

(part of me thinks the sooner we enable it the sooner we'll find issues, but part of me also worries about unleashing crashing bugs because so far it's had very limited testing 😄)

**Comment by CoderDake** [comment]
@DanTup 
DTD is pretty low surface area, so even if we have issues with it crashing, it should effect any vital behaviours.
Right now the only behaviours would be in development for extensions being created. :)

So I think we are ok to expose it :)

**Comment by DanTup** [comment]
Today's pre-release (v3.83.20240228) removes the flag from this. Please upgrade and let me know if you spot any issues (a stable release with this is likely later in the week).
