### ISSUE TITLE
no devices are shown in vs code

### ISSUE THREAD

**Issue by muradab** [Dart-Code/Dart-Code#4992]
**Describe the bug**
flutter extension says 'No device ' in vs code but when I run the command flutter doctor devices 
its showing 
```PS F:\A2SV\A2SV Core dev\AfroChat\afrochat_mobile> flutter doctor devices
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.0, on Microsoft Windows [Version 10.0.18363.1556], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.1.4)
[√] Android Studio (version 2023.1)
[√] VS Code (version 1.86.2)
[√] Connected device (4 available)
[√] Network resources
``` 

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/Dart-Code/Dart-Code/assets/50866469/0054ab5b-dc94-47a1-b03d-727a02999561)

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

**!! ⚠️ PLEASE REVIEW THIS REPORT FOR SENSITIVE INFORMATION BEFORE SHARING ⚠️ !!**

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.82.0
Flutter extension: 3.82.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: win 1.86.2

Workspace type: Flutter (LSP)

Dart (3.3.0): C:\dev\flutter\bin\cache\dart-sdk
Flutter (3.19.0): C:\dev\flutter (No device)

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`C:\dev\flutter\bin\cache\dart-sdk\bin\dart.exe info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.3.0 (stable) (Tue Feb 13 10:25:19 2024 +0000) on "windows_x64"
- on windows / "Windows 10 Pro" 10.0 (Build 18363)
- locale is en-US

#### Project info

- sdk constraint: '>=3.0.5 <4.0.0'
- dependencies: animated_splash_screen, animated_text_kit, badges, bloc, cached_network_image, chat_bubbles, cloudinary, connectivity_plus, cupertino_icons, dartz, dio, dotted_border, equatable, firebase_analytics, firebase_core, flutter, flutter_bloc, flutter_inappwebview, flutter_markdown, flutter_media_downloader, flutter_secure_storage, flutter_slidable, flutter_staggered_grid_view, flutter_svg, fluttertoast, focused_menu, get_it, go_router, google_fonts, google_sign_in, group_button, http, image_picker, internet_connection_checker, intl, intl_phone_number_input, loading_animation_widget, path, path_provider, provider, responsive_sizer, share_plus, shared_preferences, shimmer, smooth_page_indicator, sticky_headers, url_launcher, webview_flutter
- dev_dependencies: flutter_launcher_icons, flutter_lints, flutter_native_splash, flutter_test

#### Process info

| Memory | CPU | Elapsed time | Command line |
| -----: | --: | -----------: | ------------ |
| 494 MB |  -- |              | dart.exe     |
| 110 MB |  -- |              | dart.exe     |
|  96 MB |  -- |              | dart.exe     |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`C:\dev\flutter\bin\flutter.bat doctor -v`

```text
[√] Flutter (Channel stable, 3.19.0, on Microsoft Windows [Version 10.0.18363.1556], locale en-US)
    • Flutter version 3.19.0 on channel stable at C:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (3 days ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\user\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.1.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32407.343
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] VS Code (version 1.86.2)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.82.0

[√] Connected device (4 available)
    • SM M135FU (mobile) • RZ8W405BJWM • android-arm    • Android 13 (API 33)
    • Windows (desktop)  • windows     • windows-x64    • Microsoft Windows [Version 10.0.18363.1556]
    • Chrome (web)       • chrome      • web-javascript • Google Chrome 121.0.6167.185
    • Edge (web)         • edge        • web-javascript • Microsoft Edge 121.0.2277.112

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

 - Operating System and version:
 - VS Code version:
 - Dart extension version:
 - Dart/Flutter SDK version:
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
@muradab did you resolve this? If not, can you post the output from clicking the "Show Log" button? Thanks!

**Comment by muradab** [comment]
@DanTup I already  resolved the issue. Thanks

**Comment by muradab** [comment]
@DanTup I'm still not exactly sure how it got resolved. But I believe removing no-sound-null-safety from workspace configurations and restarting vs code worked

**Comment by DanTup** [comment]
Ah, it sounds like maybe you added options to `dart.flutterAdditionalArgs`? You should only add them to `dart.flutterRunAdditionalArgs` (note the `Run`) and/or `flutterTestAdditionalArgs` if they are options that only work for `flutter run` and `flutter test`. Adding them to the global arguments would try to pass them to things like `flutter daemon` that is used for devices.
