### ISSUE TITLE
Debug `toString()` evaluates 11 values instead of 100

### ISSUE THREAD

**Issue by pattobrien** [Dart-Code/Dart-Code#4995]
**Describe the bug**
When running a program in debug mode, `toString()` only evaluates the first 11 values, rather than 100 as specified in the docs.

**To Reproduce**
1. Override `toString()` with a custom toString method on a custom class (e.g. `Token` class)
2. Create a list of 100 instances of `Token` and pause the debugger while the list of tokens are in scope.

**Expected behavior**
All 100 instances show the evaluated `toString()` value next to the list of each `Token` in the debugger.

**Screenshots**

![Screenshot 2024-02-19 at 2 24 52 PM](https://github.com/Dart-Code/Dart-Code/assets/12474318/565ffe7d-88b9-4740-b98c-d4bf417175a0)

**Environment info**

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.83.20240207
Flutter extension: 3.83.20240201 (activated)

App: Visual Studio Code
App Host: desktop
Version: mac 1.86.2

Workspace type: Dart (LSP)

Dart (3.3.0): /Users/pattobrien/.fvm/versions/stable/bin/cache/dart-sdk
Flutter (3.19.0): /Users/pattobrien/.fvm/versions/stable (No device)

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`/Users/pattobrien/.fvm/versions/stable/bin/cache/dart-sdk/bin/dart info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.3.0 (stable) (Tue Feb 13 10:25:19 2024 +0000) on "macos_arm64"
- on macos / Version 13.5.2 (Build 22G91)
- locale is en-US

#### Project info

- sdk constraint: '^3.3.0'
- dependencies: antlr4, code_builder, collection, dart_style, dio, file, petitparser
- dev_dependencies: lints, test
- elided dependencies: 1

#### Process info

| Memory |  CPU | Elapsed time | Command line                                                                               |
| -----: | ---: | -----------: | ------------------------------------------------------------------------------------------ |
|  34 MB | 0.0% |        34:31 | dart --enable-vm-service=0 --pause_isolates_on_start --disable-dart-dev -DSILENT_VM_SERVICE=true --write-service-info=file:<path>/vm.json --pause_isolates_on_exit --enable-asserts <path>/main_custom_scanner.dart |
|  24 MB | 0.0% |        34:31 | dart debug_adapter                                                                         |
| 312 MB | 0.0% |        36:13 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.83.20240207     |
|   6 MB | 0.0% |  06-20:05:43 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.83.20240207     |
|   8 MB | 0.0% |  06-20:04:39 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.83.20240207     |
| 249 MB | 0.0% |        10:25 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.83.20240207     |
| 236 MB | 0.0% |        38:53 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.83.20240207     |

</details>

**Comment by DanTup** [comment]
Fix at https://dart-review.googlesource.com/c/sdk/+/353104, but it'll require an SDK release to show up.

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/30b9238561a420ec33db9b7c757081ef7e78e06e, ships in a future SDK release.
