### ISSUE TITLE
Formatter - Trailing Commas Setting

### ISSUE THREAD

**Issue by Number-3434** [Dart-Code/Dart-Code#4996]
## Proposal

Please add a `trailingCommas` setting to the formatter.

---

## Motivation

I have OCD, and I like compacting down the code.

It would therefore be useful if there was a setting to automatically do this for you.

For example, given the following:

```dart
const unnecessarilyLongNameForThePurposeOfCausingOverflow = Text("Some Text", style: TextStyle(color: Colors.white, fontSize: 20));
```

...this would be regarded as "too long", and would be formatted thus:

```dart
const unnecessarilyLongNameForThePurposeOfCausingOverflow =
  Text(
    "Some Text",
    style: TextStyle(
      color: Colors.white, fontSize: 20));
```

However, I would prefer trailing commas in this instance:

```dart
const unnecessarilyLongNameForThePurposeOfCausingOverflow =
  Text(
    "Some Text",
    style: TextStyle(
      color: Colors.white, fontSize: 20
    ),
  );
```

If I were to change this to be more compact however...

```dart
const unnecessarilyLongNameForThePurposeOfCausingOverflow =
  Text(
    "Some Text",
    style: TextStyle(
      color: Colors.white,
    ),
  );
```

...I would like the commas to be removed if can be compacted.

```dart
const unnecessarilyLongNameForThePurposeOfCausingOverflow =
  Text("Some Text", style: TextStyle(color: Colors.white));
```

---

## Remarks

I acknowledge that there's already an open issue about having a customisable formatter:
- #914

---

## Settings

Name | Type | Description | Default
:-:|:-:|:-:|:-:
<samp><kbd>"dart.insertTrailingCommas"</kbd></samp> | <samp><kbd>bool</kbd></samp> | <samp>Insert trailing commas if the closing bracket is on a different line than the opening bracket.</samp> | <samp><kbd>false</kbd></samp>
<samp><kbd>"dart.trailingCommaTolerance"</kbd></samp> | <samp><kbd>int</kbd></samp> | <samp>The maximum line difference between brackets before trailing commas are removed or addded.</samp> | <samp><kbd>1</kbd></samp>
<samp><kbd>"dart.removeUnecessaryTrailingCommas"</kbd></samp> | <samp><kbd>bool</kbd></samp> | <samp>Remove unecessary trailing commas, if they are on the same line.</samp> | <samp><kbd>false</kbd></samp>

**Comment by DanTup** [comment]
There are only really two ways to changing the formatting - one is by changing [dart_style](https://github.com/dart-lang/dart_style) (existing SDK formatter), or implementing a new formatter (which is https://github.com/Dart-Code/Dart-Code/issues/914 was about, but not something being actively worked on).

There is an open proposal/experiment that changes the formatter that might be to the kind of format you'd prefer - see https://github.com/dart-lang/dart_style/issues/1253. I would encourage trying that out and posting feedback on that thread.

I'll close this as I don't think there's anything else to do here - the required changes need to be part a formatter to work reliably, it's not something the VS Code extension can do.

Thanks!
