### ISSUE TITLE
How to move a widget down in a list of children

### ISSUE THREAD

**Issue by mit-mit** [Dart-Code/Dart-Code#501]
I was expecting 'move down' to be used for moving a child down below it's sibling, i.e. 'move down' on 1 below, would reorder 1,2,3 to 2,1,3:

```
A(
   children: <Widget>[
      1
      2
      3
    ]
)
```

Maybe 'move down' really is 'swap with child', i.e, here it swaps A and B?

```
A(
  child: B(
      child: C()
   )
)
```

**Comment by DanTup** [comment]
This functionality is coming from the analysis server so is best raised over at the sdk project. I'm afraid I don't know exactly what the intention is.

**Comment by mit-mit** [comment]
Tracking in https://github.com/flutter/flutter-intellij/issues/1638

**Comment by DanTup** [comment]
@mit-mit Thanks! (btw, that project looks intelli-j specific, but isn't this an issue/request for the flutter plugin for the analyzer?)

**Comment by mit-mit** [comment]
(yup, but we try to track issues where they surface to the user; we will likely end up opening an analyzer specific one in addition though)

**Comment by DanTup** [comment]
Makes sense! :-)

**Comment by DanTup** [comment]
Like #495, I think this might be being handled in the analysis server. Let me know if there's anything I can/should be doing at this end.

**Comment by DanTup** [comment]
Considering this fixed in https://github.com/flutter/flutter-intellij/issues/1638
