### ISSUE TITLE
Add a way to copy the DTD uri

### ISSUE THREAD

**Issue by kenzieschmoll** [Dart-Code/Dart-Code#5013]
Context https://github.com/dart-lang/sdk/issues/55002#issuecomment-1964741479

**Comment by DanTup** [comment]
This is now available from the command palette and the language status area:

![Screenshot 2024-02-28 114847](https://github.com/Dart-Code/Dart-Code/assets/1078012/ac0aa4b9-8a61-406b-883d-d81c7544f3ab)

![Screenshot 2024-02-28 114857](https://github.com/Dart-Code/Dart-Code/assets/1078012/231caa2b-d05c-442f-921a-94ca2c1afbc5)

**Comment by DanTup** [comment]
This was included in a pre-release today (v3.83.20240228)
