### ISSUE TITLE
Issue on website (Upstream Issues) - an issue on the list is closed, should be removed.

### ISSUE THREAD

**Issue by whesse** [Dart-Code/Dart-Code#5016]
I found an issue on http://dartcode.org/upstream-issues/

At least one of the issues on that list (https://github.com/microsoft/vscode/issues/165840) is closed because it didn't have enough upvotes. Should we remove closed issues from the list, since there is no useful way to upvote them?

**Comment by DanTup** [comment]
Yep, that makes sense. I've removed the closed items and added a script that'll scrape the URIs and check the status to simplify this (probably it should just remove them for me.. maybe another day 😄).

It's a shame many are closed as not implemented, but it's not useful to direct users there if they can't do anything.

Thanks!
