### ISSUE TITLE
Unable to select Android emulator after first debug session

### ISSUE THREAD

**Issue by Psyk0Path** [Dart-Code/Dart-Code#5019]
Whe i start debugging mode, in the first attempt vscode ask to me which device to open. when i close and reoper de debug mode the device mode disappear and open the debug mode only in webbmode or windows mode

**Comment by DanTup** [comment]
Are you able to post a screenshot of the entire VS Code window both when you _do_ see your device, and when you do not see your device?

Can you also run the **Dart: Collect Diagnostic Information** command from the command palette (`F1`) and include the full output?

Thanks!

**Comment by Psyk0Path** [comment]
First debug mode
![Screenshot 2024-03-10 100037](https://github.com/Dart-Code/Dart-Code/assets/86132396/00a6f1f7-f3a3-4801-b167-3e5df0fc9e3a)
The android emulator start

Second Time

![Screenshot 2024-03-10 100226](https://github.com/Dart-Code/Dart-Code/assets/86132396/eb91786b-0c36-4b12-bd9c-bba1aecb0518)
![Screenshot 2024-03-10 100317](https://github.com/Dart-Code/Dart-Code/assets/86132396/4f731f4a-1abe-47da-98b4-4824cf63ae66)

**Comment by DanTup** [comment]
The devices shown in the first screenshot are emulators that have not been started up yet. Can you confirm what happens when you select one? You should see an emulator start up but it's not clear if you are.

If not, can you try running `flutter emulators` from a terminal, and then try to launch one by running `flutter emulators --launch <emulator id>` (where `<emulator id>` is copied from the list of emulators from the first command) and see whether that starts the emulator successfully or not.

Thanks!

**Comment by Psyk0Path** [comment]
The first time both the emulator and the app launch. The second time only the Windows or WEB emulator starts without giving me the possibility to choose the first Android emulator I chose

**Comment by DanTup** [comment]
Could you try enabling the Flutter device daemon log by adding the following to your VS Code settings?

```js
"dart.flutterDaemonLogFile": "C:\\Logs\\flutter_daemon.txt",
```

Replace this with an appropriate path for your machine.

Then restart VS Code and reproduce the issue (first launching an app successfully, then triggering the issue with the device missing) and then attach a copy of the log file here.

Thanks!

**Comment by Psyk0Path** [comment]
[flutter_daemon.txt](https://github.com/Dart-Code/Dart-Code/files/14606261/flutter_daemon.txt)

**Comment by DanTup** [comment]
@Psyk0Path thanks - it looks like ADB reports that the emulator doesn't exist when Flutter tries to query some parameters:

```
// Request to start emulator

[6:40:47 PM] [FlutterDaemon] [Info] ==> [{"id":"6","method":"emulator.launch","params":{"emulatorId":"Pixel_3a_API_34_extension_level_7_x86_64","coldBoot":false}}]
[6:40:51 PM] [FlutterDaemon] [Info] <== [{"id":"6"}]

// Emulator boots up and shows as a device
[6:40:56 PM] [FlutterDaemon] [Info] <== [{"event":"device.added","params":{"id":"emulator-5554","name":"sdk gphone64 x86 64","platform":"android-x64","emulator":true,"category":"mobile","platformType":"android","ephemeral":true,"emulatorId":"Pixel_3a_API_34_extension_level_7_x86_64","sdk":"Android 14 (API 34)","capabilities":{"hotReload":true,"hotRestart":true,"screenshot":true,"fastStart":true,"flutterExit":true,"hardwareRendering":true,"startPaused":true}}}]

// adb error
[6:57:11 PM] [FlutterDaemon] [Info] <== [{"event":"daemon.logMessage","params":{"level":"error","message":"Error 1 retrieving device properties for sdk gphone64 x86 64:"}}]
[6:57:11 PM] [FlutterDaemon] [Info] <== [{"event":"daemon.logMessage","params":{"level":"error","message":"adb.exe: device 'emulator-5554' not found\r\n"}}]
```

Can you check whether the device shows up in `flutter devices` after this has happened? (eg. when you are unable to select the emulator inside VS Code, does `flutter devices` at the terminal also no longer show it?)

**Comment by Psyk0Path** [comment]
The thevice still there.

I try to resume how i start debugger
1. Click StartDebugger, Select the android device.
2. The device open and flutter star
3. i close the device and stop the debugger
4. i start the debugger
5. vs code automaticly select chrome/windows mode
6. Checked in Palette Flutter Device and the device still there but if i don't start manualy didn't start

anyway, Tnx for helping me

**Comment by DanTup** [comment]
Oh, I think this is working as expected.

You can only use _active_ devices when starting to debug. If your emulator is closed, it is not considered an _active_ device. You can _launch_ the emulator from the device manager, but it needs to already be running to be selected as the "current" device.

If you're going to be launching more debug sessions, I would say don't close the emulator, just stop the debug session in VS Code, and leave the emulator open. That way it will be available for the next debug session.

Let me know if you think I have misunderstood. Thanks!
