### ISSUE TITLE
Debugging a Dart web app may result in errors displayed in the console

### ISSUE THREAD

**Issue by andynewman10** [Dart-Code/Dart-Code#5027]
**Describe the bug**

Debugging Dart web may result in errors displayed in the console (see below).

**To Reproduce**

1. Create a new dart project with `dart create -t web dartwebapp`
2. Add and `meta` and `google_maps` to the dependencies, then follow the [instructions](https://pub.dev/packages/google_maps) on how to set the code up for Google Maps. Warning: this requires an API key. I am not completely sure the problem is raised because of this package. The problem sometimes happen and sometimes does not happen.
3. Launch a debug session

**Expected behavior**

The debug session should be launched with no error.

**Actual behavior**

The code is successfully run, however, see the console output at the bottom of this post.

**Please complete the following information:**

 - Operating System and version: Windows 11
 - VS Code version: 1.87.0
 - Dart extension version: 3.84.0
 - Dart/Flutter SDK version: 3.19.2
 - Target device (if the issue relates to Flutter debugging): Chrome
 
**Console output**

```
[INFO] Connecting to the build daemon...
[INFO] Generating build script...
[INFO] Generating build script completed, took 672ms
[INFO]
[INFO] Starting daemon...
[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 415ms
[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 1.5s
[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 415ms
[INFO]
[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 1.5s
[INFO]
[INFO] Setting up file watchers...
[INFO] Setting up file watchers completed, took 6ms
[INFO]
[INFO] Registering build targets...
[INFO] Starting initial build...
[INFO] Starting resource servers...
[INFO] Serving DevTools at http://127.0.0.1:55932
[INFO] Serving `web` on http://127.0.0.1:55920
[INFO] Starting chrome with user data directory: null
[INFO] About to build [web]...
[INFO] Running build...
[INFO] Running build completed, took 852ms
[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 941ms
[INFO] Succeeded after 1.8s with 0 outputs (0 actions)
[INFO] ------------------------------------------------------------------------
[INFO] Received request for entrypoint at http://127.0.0.1:55920/main.dart.bootstrap.js
[INFO] Loading debug metadata...
[INFO] Loaded debug metadata (sound null safety)
[INFO] Injected debugging metadata for entrypoint at http://127.0.0.1:55920/main.dart.bootstrap.js
[INFO] Initializing expression compiler for main.dart.bootstrap.js with sound null safety: true
[INFO] Starting...
[INFO] Debug service listening on ws://127.0.0.1:55955/iC3VAmS6uoA=/ws
Connecting to VM Service at ws://127.0.0.1:55955/iC3VAmS6uoA=/ws
[INFO] Updating dependencies...
ERROR - 2024-03-08 09:47:01.315781
HEAD /packages/google_maps/google_maps.ddc.dill
Error thrown by handler.
Write failed
serveRequests.<fn>.<fn>
shelf_io.dart:91
===== asynchronous gap ===========================
serveRequests
shelf_io.dart:89
package:webdev/src/util.dart 22:5                  serveHttpRequests.<fn>
package:stack_trace                                Chain.capture
package:webdev/src/util.dart 21:16                 serveHttpRequests
package:webdev/src/serve/webdev_server.dart 213:5  WebDevServer.start
2

ERROR - 2024-03-08 09:47:01.399875
GET /packages/meta/meta.ddc.dill
Error thrown by handler.
Write failed
serveRequests.<fn>.<fn>
shelf_io.dart:91
===== asynchronous gap ===========================
serveRequests
package:webdev/src/util.dart 22:5                  serveHttpRequests.<fn>
package:stack_trace                                Chain.capture
package:webdev/src/util.dart 21:16                 serveHttpRequests
package:webdev/src/serve/webdev_server.dart 213:5  WebDevServer.start
2

ERROR - 2024-03-08 09:47:01.419822
GET /packages/meta/meta_meta.ddc.dill
Error thrown by handler.
Write failed
serveRequests.<fn>.<fn>
shelf_io.dart:91
===== asynchronous gap ===========================
serveRequests
shelf_io.dart:89
package:webdev/src/util.dart 22:5                  serveHttpRequests.<fn>
package:stack_trace                                Chain.capture
package:webdev/src/util.dart 21:16                 serveHttpRequests
package:webdev/src/serve/webdev_server.dart 213:5  WebDevServer.start
2

[INFO] Updated dependencies.
[INFO] Stopped debug service on ws://127.0.0.1:44456
Lost connection to device.
Exited (sigterm)
```

**Comment by DanTup** [comment]
Does this happen if you use `webdev serve` from the command line? From the error, I don't _think_ this is related to the VS Code extension.

I would also check with `dart pub global list` and ensure that `webdev` is on the latest version (3.4.0). If not, run `dart pub global activate webdev` to update it.

**Comment by andynewman10** [comment]
`webdev serve` is not a recognized command.

`dart pub global list`  lists `webdev 3.4.0` (and only that).

**Comment by andynewman10** [comment]
When I opened (or launched for the first time?) this dart web app in VS code, VS code had immediately reacted and had proposed to install `webdev`, which I had agreed with.

**Comment by DanTup** [comment]
Ah, if it's not on `PATH` you would need to run `dart pub global run webdev serve`.

**Comment by andynewman10** [comment]
Thank you. All from the VS terminal, I did:

- `dart pub global run webdev serve`
- no issues in the console, 'Injecting ....' is eventually displayed...
- opened a browser window, played a bit with my web page (all good), then closed it
- Ctrl+C from the VS prompt to stop serving
- this time, I click on 'Debug'
- a debug session is launched by VS code
- I get the same errors as described at the top of this issue

**Comment by DanTup** [comment]
Thanks for testing. I verified I can also reproduce from within VS Code but not from the console. I feel like it's a webdev or dwds issue though.

I found https://github.com/dart-lang/webdev/issues/1520 and have added some comments there to see if the webdev/dwds devs have any ideas/suggestions.
