### ISSUE TITLE
"dart.env" settings do not respect VSCode Built-In Variables

### ISSUE THREAD

**Issue by violen** [Dart-Code/Dart-Code#5028]
**Describe the bug**
By setting PUB_CACHE via `dart.env` in `settings.json` it does not respect the built-in VSCode variables like `${workspaceFolder}` or `${/}` (Pathseparator Shorthand).
Changes to pubspec.yaml or launching the App via launch configuration finds the PUB_CACHE variable but
instead of using the cached files it creates a weird folder and redownloads all dependencies to the root project and module folders.

The sample here is with using `fvm` but it applies also if you do not use it and want the cached dependency close to your project.

**To Reproduce**
1. Have a Dart / Flutter Project open in VSCode
3. Create a -your_project_folder-/.vscode/settings.json with
```json
{
  "dart.flutterSdkPath": ".fvm${/}flutter_sdk",
  "search.exclude": {
    "**/.fvm": true
  },
  "files.watcherExclude": {
    "**/.fvm": true
  },
  "dart.env": {
    "PUB_CACHE": "${workspaceFolder}${/}.fvm${/}flutter_sdk${/}.pub-cache",
  }
}
```
3. Change dependencies in your pubspec.yaml and / or start your application via launch configuration. With other words let VSCode or the DartCode extension handle the `pub get` and `run` commands.

**Expected behavior**
Changes to pubspec.yaml or launching the App via launch configuration shall use the PUB_CACHE path correctly.

**Screenshots**
![grafik](https://github.com/Dart-Code/Dart-Code/assets/5476301/7980d123-2843-4bba-8937-378e83f5898c)

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

 - Operating System and version: Win 11 Pro 23H2
 - VS Code version: 1.87.0
 - Dart extension version: 3.84.0
 - Dart/Flutter SDK version: 
 ```shell
Flutter 3.16.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2e9cb0aa71 (3 months ago) • 2023-12-11 14:35:13 -0700
Engine • revision 54a7145303
Tools • Dart 3.2.3 • DevTools 2.28.4
```
 - Target device (if the issue relates to Flutter debugging): Android Emulator / Hardware device

**Comment by DanTup** [comment]
This is unfortunately expected. There's no API for us to resolve those variables so supporting any of them would basically be re-implementing VS Code's behaviour (which we'd have to maintain and keep up-to-date as VS Code changes them or risk deviating) which is not a good idea.

There's some prior discussion about this in https://github.com/Dart-Code/Dart-Code/issues/4613.

This should be supported by VS Code - there's a quest for it here: https://github.com/microsoft/vscode/issues/2809. There's also a request for [local workspace settings](https://github.com/microsoft/vscode/issues/40233) that may also help (you'd have the paths in another file that you don't commit to Git), but that also is not implemented unfortunately.

Hope this helps!
