### ISSUE TITLE
Close Embedded Widget Inspector Window on Debug Session End

### ISSUE THREAD

**Issue by beattizzle** [Dart-Code/Dart-Code#5029]
I find it slightly annoying that I have to manually exit out of the embedded widget window when I'm done with a debug session to get back to the view I was in prior to starting the debug session.  I would like to propose a new settings flag that controls whether the debug window closes automatically upon debug session end or not.

I think a solution to this problem would be to add a Dart->DevTools settings flag similar to 'Dart: Dev Tools Reuse Windows' which would then control whether or not this happens on debug session end. Then, in handleDebugSessionEnd() or a more appropriate location, add code to call DevToolsEmbeddedView.dispose() (currently set to private) for the embedded view associated with the session.  

Included is a screenshot with some pseudocode I wrote as a proposed solution.  Thanks for your consideration.

![proposedChange](https://github.com/Dart-Code/Dart-Code/assets/36205786/d333012e-9030-410f-93e2-4b8224f5a2ac)

**Comment by DanTup** [comment]
New setting looks like this, let's you pick whether to automatically close all embedded DevTools, or only those that were automatically opened.

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/54955399-cb65-410c-a6e4-cdd6290171cd)
