### ISSUE TITLE
Please support hot reload for certain assets 

### ISSUE THREAD

**Issue by sma** [Dart-Code/Dart-Code#5031]
I've a Flutter app that contains a lot of markdown files as assets and needs to display them.

Changing such a file doesn't automatically trigger a hot reload so I have to manually press the yellow lightening button to verify whether my changes to those files look good. It would improve _quality of life_ if this could happen automatically.

Hence, it would be nice if the plugin would use the `pubspec` file to find all assets and then optionally also hot reload if those assets are changed. Or just add `md` to the list of watched files in the  `shouldHotReloadFor` function :)

**Comment by DanTup** [comment]
I think this should be opt-in because it might be unexpected if you're editing a README or something and it triggers reload (not to mention that the use case for `.md` is equally applicable to other assets).

**Comment by DanTup** [comment]
This fix was included in a new pre-release version. If you want to test it out without waiting for the next stable version, you can switch to the pre-release versions of the extensions in VS Code using the button shown in the screenshot below.

<img width="703" alt="Dart pre-release versions" src="https://user-images.githubusercontent.com/1078012/218796750-90a70b0b-4957-468c-8eb4-688095cde112.png">

Please let me know if you hit any issues. Thanks!

**Comment by sma** [comment]
At first, I used `"assets/**"` as pattern which didn't work but when I added the `**/` prefix, it worked like a charm. I added the configuration as a workspace setting to my project so it gets only activated for my wiki project. Thanks.

**Comment by DanTup** [comment]
Yeah, the pattern is matched against the full path:

> The pattern is matched against the absolute path of the file. Use `**/assets/**` to trigger reloading for everything in the assets directory.

There was something odd when we didn't do it this way but I don't recall what off the top off my head (this use of globs was copied from a similar legacy setting we had for formatting).

Glad it's working :)

**Comment by jacob314** [comment]
If this works well it is probably worth specifying in pubspec.yaml
