### ISSUE TITLE
Stuck in "Starting debug session..."  state forever with new SDK debug adapters

### ISSUE THREAD

**Issue by sunflash** [Dart-Code/Dart-Code#5037]
**Describe the bug**
I updated my projects to Flutter version 3.16 and later 3.19 recently, and the debugger stopped working on my Linux desktop.
It stuck on the "Starting debug session..." state and nothing happened. 
And VS code "DEBUG CONSOLE" is empty without any output, and the status bar doesn't turn orange as it used to.

After some trial and error, and reinstalling vs code and extensions.
I narrowed down the issue to the "new SDK debug adapters", on release v3.78 and onwards.

I got it working again either by downgrading the dart extension manually to 3.76.0. 
Or in vs code user setting by applying ` "dart.useLegacyDebugAdapters": true`

I use a similar setup and config on my Mac and don't encounter the same issue there.
I tried to build projects in Android Studio and `flutter run` from the command line in the same Linux environments, and both work fine without issues.

Right now I use ` "dart.useLegacyDebugAdapters": true`  flag to get it working.
It's not sustainable in the long run if the "LegacyDebugAdapters" option is removed, and the "new SDK debug adapters" become the new default and don't work with linux.
 
**Expected behavior**

The "new SDK debug adapters" should work on Linux as legacy debug adapters did.
And don't stuck in the "Starting debug session.." state on 3.78.0+

 - Operating System and version: openSUSE Tumbleweed distrobox (openSuse Aeon host)
 - VS Code version: 1.87.2
 - Dart extension version:  3.84.0
 - Dart/Flutter SDK version: Dart 3.3.0 Flutter 3.19.2
 - Target device (if the issue relates to Flutter debugging): Linux desktop, Android emulator (Pixel 2 API 24)

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.84.0
Flutter extension: 3.84.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: linux 1.87.2

Workspace type: Dart, Flutter (LSP)

Dart (3.3.0): /home/mojo/.asdf/installs/flutter/3.19.2-stable/bin/cache/dart-sdk
Flutter (3.19.2): /home/mojo/.asdf/installs/flutter/3.19.2-stable (Linux (linux-x64/linux))

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`/home/mojo/.asdf/installs/flutter/3.19.2-stable/bin/cache/dart-sdk/bin/dart info`

#### General info

- Dart 3.3.0 (stable) (Tue Feb 13 10:25:19 2024 +0000) on "linux_x64"
- on linux / Linux 6.7.7-1-default SMP PREEMPT_DYNAMIC Fri Mar  1 13:51:21 UTC 2024 (1ff84c5)
- locale is en_US.UTF-8

#### Process info

| Memory |  CPU | Elapsed time | Command line                                                                    |
| -----: | ---: | -----------: | ------------------------------------------------------------------------------- |
|  66 MB | 0.1% |        07:26 | dart devtools --machine --allow-embedding                                       |
| 523 MB | 1.7% |        07:26 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.84.0 |
|  77 MB | 0.2% |        07:26 | flutter_tools.snapshot daemon                                                   |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`/home/mojo/.asdf/installs/flutter/3.19.2-stable/bin/flutter doctor -v`

```text
[✓] Flutter (Channel stable, 3.19.2, on openSUSE Tumbleweed 6.7.7-1-default, locale en_US.UTF-8)
    • Flutter version 3.19.2 on channel stable at /home/mojo/.asdf/installs/flutter/3.19.2-stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7482962148 (2 weeks ago), 2024-02-27 16:51:22 -0500
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc1)
    • Android SDK at /home/mojo/Android/Sdk
    • Platform android-34, build-tools 35.0.0-rc1
    • ANDROID_HOME = /home/mojo/Android/Sdk
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /home/mojo/.local/share/flatpak/app/com.google.Chrome/x86_64/stable/active/export/bin/com.google.Chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 17.0.6
    • cmake version 3.28.3
    • ninja version 1.11.1
    • pkg-config version 2.1.1

[✓] Android Studio (version 2023.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 78.2.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.87.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.84.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • openSUSE Tumbleweed 6.7.7-1-default
    • Chrome (web)    • chrome • web-javascript • unknown

[✓] Network resources
    • All expected network resources are available.

```

</details>

**Comment by DanTup** [comment]
Does this reproduce in a brand new project created with `flutter create` / **Flutter: New Project**?

Assuming so, can you capture a log (for that new project) using the **Dart: Capture Debugging Logs** command on the machine where you're having problems?

- Run the command from the palette (`F1`)
- Try to run the app and wait for it to get stuck
- Wait at least another 60 seconds just to ensure the logs are complete and nothing is in progress
- Click **Cancel** on the logging notification to stop logging and open the log
- Attach the log here/in a gist

Thanks!

**Comment by DanTup** [comment]
Hmm, something doesn't seem right here - the log should include a lot of information when the debug session starts. Can you confirm that you started capturing logs _before_ starting the debug session? If so, are you able to capture a screen recording of exactly what you're seeing when you start capturing and then try to launch?

When I start capturing logs and then start a debug session, I see things like this in the log:

```
Thu Mar 14 2024 [16:04:44 GMT+0000 (Greenwich Mean Time)] Log file started
[4:04:46 PM] [General] [Info] Starting debug session...
[4:04:46 PM] [General] [Info]     workspace: C:\Dev\Test Projects\flutter_counter
[4:04:46 PM] [General] [Info] Setting cwd based on active workspace folder: C:\Dev\Test Projects\flutter_counter
[4:04:46 PM] [General] [Info] Using found common entry point: C:\Dev\Test Projects\flutter_counter\lib\main.dart
[4:04:46 PM] [General] [Info] Using workspace as cwd: C:\Dev\Test Projects\flutter_counter
[4:04:46 PM] [General] [Info] Detected launch project as Flutter
[4:04:46 PM] [General] [Info] Using Flutter debug adapter for this session
...
```

**Comment by sunflash** [comment]
Sorry, did it in reversed order, started the debug session then turned on the logging.
Here is a new log with more info

<details>
  <summary>Debugging logs</summary>

```text
Dart Code extension: 3.84.0
Flutter extension: 3.84.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: linux 1.87.2

Workspace type: Flutter (LSP)

Dart (3.3.0): /home/mojo/.asdf/installs/flutter/3.19.2-stable/bin/cache/dart-sdk
Flutter (3.19.2): /home/mojo/.asdf/installs/flutter/3.19.2-stable (No device)


Logging Categories:
    General, AnalyzerTiming, CommandProcesses, DartTest, DartToolingDaemon, DAP, VmService, DevTools, FlutterDaemon, FlutterRun, FlutterTest, WebDaemon

Thu Mar 14 2024 [21:36:46 GMT+0100 (Central European Standard Time)] Log file started
[9:37:04 PM] [General] [Info] Starting debug session...
[9:37:04 PM] [General] [Info]     workspace: /home/mojo/Projects/test
[9:37:04 PM] [General] [Info] Setting cwd based on likely entry point: /home/mojo/Projects/test
[9:37:04 PM] [General] [Info] Using open file as entry point: /home/mojo/Projects/test/lib/main.dart
[9:37:04 PM] [General] [Info] Using workspace as cwd: /home/mojo/Projects/test
[9:37:04 PM] [General] [Info] Detected launch project as Flutter
[9:37:04 PM] [General] [Info] Using Flutter debug adapter for this session
[9:37:04 PM] [FlutterDaemon] [Info] ==> [{"id":"4","method":"daemon.getSupportedPlatforms","params":{"projectRoot":"/home/mojo/Projects/test"}}]
[9:37:04 PM] [FlutterDaemon] [Info] <== [{"id":"4","result":{"platforms":["web","android","ios","linux","macos","windows"],"platformTypes":{"web":{"isSupported":true},"android":{"isSupported":true},"ios":{"isSupported":true},"linux":{"isSupported":true},"macos":{"isSupported":true},"windows":{"isSupported":true},"fuchsia":{"isSupported":false,"reasons":[{"reasonText":"the Fuchsia feature is not enabled","fixText":"Run \"flutter config --enable-fuchsia\"","fixCode":"config"},{"reasonText":"the Fuchsia platform is not enabled for this project","fixText":"Run \"flutter create --platforms=fuchsia .\" in your application directory","fixCode":"create"}]},"custom":{"isSupported":false,"reasons":[{"reasonText":"the custom devices feature is not enabled","fixText":"Run \"flutter config --enable-custom-devices\"","fixCode":"config"}]},"windowsPreview":{"isSupported":false,"reasons":[{"reasonText":"the Preview Device feature is not enabled","fixText":"Run \"flutter config --enable-flutter-preview","fixCode":"config"}]}}}}]
[9:37:04 PM] [FlutterDaemon] [Info] ==> [{"id":"5","method":"daemon.getSupportedPlatforms","params":{"projectRoot":"/home/mojo/Projects/test"}}]
[9:37:04 PM] [FlutterDaemon] [Info] <== [{"id":"5","result":{"platforms":["web","android","ios","linux","macos","windows"],"platformTypes":{"web":{"isSupported":true},"android":{"isSupported":true},"ios":{"isSupported":true},"linux":{"isSupported":true},"macos":{"isSupported":true},"windows":{"isSupported":true},"fuchsia":{"isSupported":false,"reasons":[{"reasonText":"the Fuchsia feature is not enabled","fixText":"Run \"flutter config --enable-fuchsia\"","fixCode":"config"},{"reasonText":"the Fuchsia platform is not enabled for this project","fixText":"Run \"flutter create --platforms=fuchsia .\" in your application directory","fixCode":"create"}]},"custom":{"isSupported":false,"reasons":[{"reasonText":"the custom devices feature is not enabled","fixText":"Run \"flutter config --enable-custom-devices\"","fixCode":"config"}]},"windowsPreview":{"isSupported":false,"reasons":[{"reasonText":"the Preview Device feature is not enabled","fixText":"Run \"flutter config --enable-flutter-preview","fixCode":"config"}]}}}}]
[9:37:04 PM] [General] [Info] Getting DevTools server address to pass to Flutter...
[9:37:04 PM] [General] [Info] Checking for errors before launching
[9:37:04 PM] [General] [Info] Debug session starting...
    {
        "dartCodeDebugSessionID": "session-1053b",
        "type": "dart",
        "request": "launch",
        "program": "/home/mojo/Projects/test/lib/main.dart",
        "projectRootPath": "/home/mojo/Projects/test",
        "cwd": "/home/mojo/Projects/test",
        "name": "Flutter (Linux)",
        "deviceId": "linux",
        "deviceName": "Linux (linux-x64)",
        "toolEnv": {
            "FLUTTER_HOST": "VSCode",
            "PUB_ENVIRONMENT": "vscode.dart-code",
            "FLUTTER_ROOT": "/home/mojo/.asdf/installs/flutter/3.19.2-stable"
        },
        "sendLogsToClient": true,
        "sendCustomProgressEvents": true,
        "allowAnsiColorOutput": true,
        "additionalProjectPaths": [
            "/home/mojo/Projects/test"
        ],
        "args": [],
        "vmAdditionalArgs": [],
        "toolArgs": [
            "-d",
            "linux",
            "--devtools-server-address",
            "http://127.0.0.1:9100/",
            "-v"
        ],
        "vmServicePort": 0,
        "dartSdkPath": "/home/mojo/.asdf/installs/flutter/3.19.2-stable/bin/cache/dart-sdk",
        "maxLogLineLength": 2000,
        "debugSdkLibraries": false,
        "debugExternalPackageLibraries": true,
        "showDartDeveloperLogs": true,
        "evaluateGettersInDebugViews": true,
        "showGettersInDebugViews": true,
        "evaluateToStringInDebugViews": true,
        "flutterSdkPath": "/home/mojo/.asdf/installs/flutter/3.19.2-stable",
        "useInspectorNotificationsForWidgetErrors": true,
        "showMemoryUsage": false,
        "debuggerType": 2
    }
[9:37:04 PM] [General] [Info] Using flutter debugger for Flutter
[9:37:04 PM] [General] [Info] SDK DAP setting is true, set by sdkDaps experiment
[9:37:04 PM] [General] [Info] Running SDK DAP Dart VM in undefined: /home/mojo/.asdf/installs/flutter/3.19.2-stable/bin/flutter debug_adapter and options {"env":{"FLUTTER_HOST":"VSCode","PUB_ENVIRONMENT":"vscode.dart-code","FLUTTER_ROOT":"/home/mojo/.asdf/installs/flutter/3.19.2-stable"}}
[9:37:04 PM] [DAP] [Info] Starting debug session f8f4114b-f009-45fd-b48e-2aaefafa38fb
[9:37:04 PM] [DAP] [Info] ==> {"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"dart","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en","supportsProgressReporting":true,"supportsInvalidatedEvent":true,"supportsMemoryReferences":true,"supportsArgsCanBeInterpretedByShell":true,"supportsMemoryEvent":true,"supportsStartDebuggingRequest":true},"type":"request","seq":1}
Thu Mar 14 2024 [21:39:32 GMT+0100 (Central European Standard Time)] Log file ended
```
</details>

**Comment by DanTup** [comment]
Thanks for the log. Unfortunately it doesn't reveal much.. VS Code sends an `initialize` request to the debug adapter but it never appears to respond (but also appears to not error).

Do all of the devices show up correctly inside VS Code (eg. if you connect/disconnect an Android device/emulator, does it appear/disappear from the list of devices inside VS Code)?

Can you tell whether the `flutter debug_adapter` process is still running when it's stuck like this (and has not terminated)?

**Comment by sunflash** [comment]
All devices show up correctly inside the VS Code, including the Android emulator and Android phone connect and disconnect with USB debugging enabled.

If  I use the old debug adapter. I can see `electron-nodejs (debug.js)` is running, and everything works as expected.
![Screenshot from 2024-03-22 14-17-44](https://github.com/Dart-Code/Dart-Code/assets/4181292/3bcdf6c5-96d1-4657-95e6-fdbcc4a19a95)

If I use the new debug adapter. Nothing happens, no  `electron-nodejs (debug.js)` session in vs code process explore.
Empty "Debug Console", no orange status bar, and "Starting debug session" notice continue and nothing happens.
![Screenshot from 2024-03-22 14-19-30](https://github.com/Dart-Code/Dart-Code/assets/4181292/6473e6a9-52b6-4991-b424-2ce1e04cfd54)

**Comment by DanTup** [comment]
> If I use the new debug adapter. No `electron-nodejs (debug.js)` session in vs code process explore.

This is correct, the new debug adapters are Dart programs and should show up as `dart debug_adapter` processes. However I don't see that either, so I wonder if the process terminated but wasn't recorded in the log properly.

If you click Help -> Toggle Developer Tools in VS Code and then click on the "Console" tab, are there any errors there?

If you create a simple Dart (non-Flutter) script in a `bin/` or `tool/` folder, something like:

```
void main() {
  print('Hello');
}
```

Does that work successfully with the new debug adapters?

**Comment by sunflash** [comment]
> If you click Help -> Toggle Developer Tools in VS Code and then click on the "Console" tab, are there any errors there?

I tried to look for errors inside the Eletron Chrome debug console, but nothing there related to dart or flutter.  

> If you click Help -> Toggle Developer Tools in VS Code and then click on the "Console" tab, are there any errors there? Does that work successfully with the new debug adapters?

Yes, for a simple dart console/cli app, the `new debug adapters` work fine without issues, and I can start it from vs code and set a breakpoint, and it works!  So the issue must be some flutter-related.

**Comment by DanTup** [comment]
Do you get any output if you run `/home/mojo/.asdf/installs/flutter/3.19.2-stable/bin/flutter debug_adapter` from a terminal?

**Comment by sunflash** [comment]
> Do you get any output if you run /home/mojo/.asdf/installs/flutter/3.19.2-stable/bin/flutter debug_adapter from a terminal?

No, I don't get any output when running `flutter debug_adapter` from the terminal. No output and it doesn't exit either, I need to Ctrl+C to exit.

**Comment by DanTup** [comment]
Thanks for checking - that's expected behaviour. I just wanted to check there wasn't some `stderr` output that maybe the log wasn't capturing.

Is it possible you could try cloning using Git and then setting the `dart.flutterSdkPath` variable to point at that folder, to see whether the issue might be specific to using Flutter through `asdf`?

**Comment by sunflash** [comment]
> Is it possible you could try cloning using Git and then setting the dart.flutterSdkPath variable to point at that folder, to see whether the issue might be specific to using Flutter through asdf?

Did try that, doesn't change the behavior. Test with the latest flutter 3.19.5 without asdf and dart/flutter vs code plugin 3.86.0. Same as before, don't work with new debug adapter,  only work with ` "dart.useLegacyDebugAdapters": true`.  asdf is not the issue.

I also use asdf on my mac dart/flutter setup, there both old and new debug adapter works.

**Comment by DanTup** [comment]
@sunflash ok, I tried this out in a VM but unfortunately was unable to repro. I was able to run the app without any problems:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/bc287766-d541-4cb4-b547-321cba57418e)

Here's the steps I followed:

- Install openSUSE Tumbleweed into a Hyper-V VM (choose the Plasma option, since it wasn't clear if that made a difference)
- Run `sudo zypper install clang cmake ninja gtk3-devel` (for Linux desktop support)
- Restart
- Install VS Code from the built-in "Discover" software center
  - This turned out to be a mistake, because it came from flatpak and couldn't find clang++ etc. on the system. So I reinstalled using the steps at https://code.visualstudio.com/docs/setup/linux#_opensuse-and-slebased-distributions to get a non-flatpak version
- Install the Flutter extension
- Run the "Flutter: New Project" command
- When prompted that there's no SDK, click "Download SDK"
- Select a folder and wait for the SDK to be cloned
- Continue creating an empty application
- Click "Yes, I trust" for VS Code prompts
- Press `F5` to run the app
- Select Linux Desktop device

The debug session seems to have launched fine.

Is there anything different about your setup that might be relevant? Anything you can do to help me reproduce the issue locally would really help. Thanks!

**Comment by sunflash** [comment]
> apologies, I missed your comment above until the bot just commented. Do you have easy access to another Linux machine to see whether it's specific to openSUSE Tumbleweed?
> Is there anything different about your setup that might be relevant? Anything you can do to help me reproduce the issue locally would really help. Thanks!

![Screenshot from 2024-05-01 21-29-37](https://github.com/Dart-Code/Dart-Code/assets/4181292/78ff924c-a55f-422a-9671-960bdc363d97)

No need to apologize, guess you were busy, and I was occupied with other stuff.
I don't have any spare desktop/laptop to install other Linux distro to test it off, without having to repartition the drive and wipe the existing Windows testing rig.

asdf wasn't the issue. And I have configured Ubuntu 22.04 in another distro box to test it out on the same machine.
Fedora "toolbox" and "Distrobox" can run the same or different Linux distro inside a docker or podman container, it's much more lightweight than VM, and way more flexible, portable, and shared with teams.

I experienced the same issue with Ubuntu 22.04, the old debug adapter works and the new one doesn't. So I think the issue is related to running the new flutter debug adapter inside a Distrobox container.

I use an immutable/atomic distro as a base, in my case OpenSUSE MicroOS, another best-known atomic distro is Fedora Silverblue (or any Fedora Atomic desktop variants), technically SteamOS too but depends on people's definition of immutable.  So messing around with the base system is not doable or recommended. So every app and dev setup needs to either run as Flatpak or inside a "toobox/distrobox".

 I created an Ubuntu with the command `distrobox-create -i quay.io/toolbx/ubuntu-toolbox:latest -n ubuntu_22`
https://github.com/89luca89/distrobox/blob/main/docs/compatibility.md#host-distros

Follow Flutter's own Linux instructions for Ubuntu setup, and then install VSCode
https://docs.flutter.dev/get-started/install/linux/desktop
https://code.visualstudio.com/docs/setup/linux

So the most likely cause is that my dev tools setup runs inside Distrobox with Podman as a container engine, the environment is probably slightly different than running Linux distro the old way.

The packages to install after the tumbleweed distrobox were created, inside the tumbleweed distro container.

```bash
sudo zypper in libstdc++6-32bit zlib-devel-32bit libncurses5-32bit libbz2-1-32bit 
sudo zypper in libXtst6 xdg-utils gtk3-devel git cmake clang ninja 

## qemu, pulseaudio for android emulator
## libsecrect for vscode account sync
sudo zypper in qemu-kvm pulseaudio libsecret-1-0

## All in one line
sudo zypper in libstdc++6-32bit zlib-devel-32bit libncurses5-32bit libbz2-1-32bit libXtst6 xdg-utils gtk3-devel git cmake clang ninja qemu-kvm pulseaudio  libsecret-1-0

## VS Code
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo zypper addrepo https://packages.microsoft.com/yumrepos/vscode vscode
sudo zypper install code

sudo zypper ref && sudo zypper dup
```

**Comment by DanTup** [comment]
@sunflash how did you install Flutter?

In the VM from above, I tried the following (I don't know if I did this right because some of this stuff is unknown to me)

- `sudo zypper install distrobox`
- `sudo service docker start`
- `distrobox-create --root`
- `distrobox enter --root tumbleweed`
- all of the commands from your script above
- `code`

This opened VS Code, but I don't know if it's the version from the distrobox or not. I opened the test application I previously picked (and it picked up Flutter that I had installed directly in the VM before distrobox) and still everything worked.

My feeling is that maybe I'm running the VS Code from the outer main VM, but I don't know to verify (`which code` shows `/usr/bin/code` in the distrobox terminal).

**Comment by sunflash** [comment]
I use Podman instead for Docker which doesn't require root permission, but it shouldn't matter which container engine is used. Creating a new box doesn't normally require root permission to work with "--root".

If you are running "code" from the command line after you enter the box you created, then it's VS Code from the box that is running, or if you make a desktop shortcut to the desktop environment by runner `distrobox-export -a code`

Otherwise, if you run code directly from the terminal without entering the box you created first, then it's code from the VM that is running and not the version inside the box. 

I don't have a version of code installation outside the VM or physical installation, and using root is prohibited with immutable/atomic distros, as base distro should not be tampered with in a few rare use cases.  So all apps are either installed as flatpack or inside a box.

**Comment by DanTup** [comment]
Sorry, I missed the notification from your previous message.

> If you are running "code" from the command line after you enter the box you created, then it's VS Code from the box that is running

Yes, this is what I did. My console shows "danny@tumbleweed" (not "danny@localhost") when I run `code`, but still I couldn't reproduce the issue.

Do you have any ability to build a fresh VM or something to test this in, and if it repros that you could share in its entirety? It's hard to know all the things that might be different between our environments that might cause us to see different behaviour.

**Comment by sunflash** [comment]
I will look into it when I have more time. 
If I run the Flutter app from **the command line or Android Studio inside the container**, I don't encounter any issues there. So I don't think setup or configuration is the issue here, otherwise build/run from either the command line or Android studio won't work.

**Comment by DanTup** [comment]
> So I don't think setup or configuration is the issue here

I've been unable to reproduce the issue so there must be _something_ different between our setups. It's difficult for me to debug without some kind of repro. A VM seems like a certain way for me to reproduce (because it's entirely self-contained), however if you have other suggestions I'm happy to try them :)

**Comment by sunflash** [comment]
> Thanks for the update! It'd be nice to figure out what's different between these that's causing the problem, but it's difficult to do without being able to repro myself where I can hack about at the code.

It's coming down to Linux distro image(docker/podman) difference, likely some libraries or commands work slightly differently. Tumbleweed/Fedora/Arch image is the leading edge and contains the newest version of any libraries, it can behave a bit differently than slow LTS Debian/Ubuntu/Red Hat.  Hard to know without digging further down, and spending a significant amount of time.

Ubuntu/Debian LTS is a more safe bet. As debian/ubuntu is running inside the Distrobox as the container, doesn't limit choose of host distro.
