### ISSUE TITLE
Extension methods on `Null` are not discoverable

### ISSUE THREAD

**Issue by HosseinYousefi** [Dart-Code/Dart-Code#5039]
For example an extension method like `Foo`:

```dart
extension Foo on Null {
  void foo() {}
}
```

Allows us to write `null.foo()`, however VSCode seems not to suggest `foo` as one of the auto-completion options when writing `null.`.

<img width="380" alt="Screenshot 2024-03-17 at 20 40 35" src="https://github.com/Dart-Code/Dart-Code/assets/9751815/a63a62bc-786f-4e4a-b46f-a77709e0dff9">

```text
Dart Code extension: 3.84.0
Flutter extension: 3.84.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: mac 1.87.1

Workspace type: Flutter (LSP)

Dart (3.4.0-233.0.dev): /Users/yousefi/Developer/flutter/bin/cache/dart-sdk
Flutter (undefined): /Users/yousefi/Developer/flutter (sdk gphone64 arm64 (android-arm64/android))

```

**Comment by DanTup** [comment]
Thanks for the report - I've moved this to https://github.com/dart-lang/sdk/issues/55224 since it'll need resolving in the Dart analysis server.
