### ISSUE TITLE
Code completion appears when typing `{` outside of strings

### ISSUE THREAD

**Issue by xster** [Dart-Code/Dart-Code#504]
Start typing:
```dart
bool something() {
```
on a new .dart file.

Pressing enter after `{` will insert some autocompleted new statement.

**Comment by xqwzts** [comment]
Removing the curly braces completion trigger in extension.ts [.vscode/extensions/Dart-Code.dart-code/out/src/extension.js] resolves this - i.e: reversing https://github.com/Dart-Code/Dart-Code/commit/9c408b72090168363caaa047e72d256ab12da692

But then we lose completion on string interpolation triggered by `${`

**Comment by xqwzts** [comment]
Quick gif of the issue:

![dart-code-completion](https://user-images.githubusercontent.com/798935/35304558-96ecbe8a-009e-11e8-97df-294157a4188d.gif)

**Comment by xster** [comment]
Seems like `registerCompletionItemProvider` takes only single characters instead of sequences. I guess if I had to choose, I'd be ok not auto triggering autocompletes on `${`.

**Comment by xqwzts** [comment]
It looks like vscode recently added [`CompletionContext`](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-namecompletioncontextaspan-classcodeitem-id873completioncontextspan) to `provideCompletionItems`. This gives us the character and action that triggered a completion.

We can use this to ignore completions from `{` unless preceded by `$`, something like:

```ts
public provideCompletionItems(
  document: TextDocument, position: Position, token: CancellationToken,
  context: CompletionContext):  Thenable<CompletionList> {
    if (context.triggerKind == CompletionTriggerKind.TriggerCharacter && context.triggerCharacter == '{') {
      // not a manual trigger on {
      if (document.getText(new Range(position.translate(0, -2), position)) != '${') {
        // ignore '{' not preceded by '$'
        return;
      }
    }
    return new Promise<CompletionList>((resolve, reject) => {
      this.analyzer.completionGetSuggestionsResults({
        file: document.fileName,
        offset: document.offsetAt(position),
      }).then((resp) => {
        resolve(new CompletionList(resp.results.map((r) => this.convertResult(document, resp, r))));
      },
       () => reject(),
      );
    });
}
```

**Comment by DanTup** [comment]
@xqwzts Awesome; thanks for the investigation! Will correct this for the next release :)
