### ISSUE TITLE
Incorrect lightbulb colour shown for versions with a + 

### ISSUE THREAD

**Issue by jonmountjoy** [Dart-Code/Dart-Code#5041]
**Describe the bug**
When viewing a `pubspec.yaml`, different colour lightbulbs are shown allowing one to upgrade individual packages to later versions.  An incorrect colour (and text) is shown for versions that contain a + build number (which is allowed by pubspec).

For example:
<img width="228" alt="image" src="https://github.com/Dart-Code/Dart-Code/assets/545244/a5d1c077-5c88-4053-af72-06c7ba44feb2">

This should simply be a green lightbulb, with the words:
"latest: 2.0.10+1"

Instead, it's showing:
"satisfies 2.0.10 | latest: 2.0.10+1"

If you click on "latest" it does nothing, because it is already on the latest.

**To Reproduce**
Use any package in pubspec that has a build number.  Today, those include:

*  flutter_svg: ^2.0.10+1
* file_picker: ^8.0.0+1

etc. 

**Expected behavior**

Since the package is the latest version of the package, it should be a green lightbulb, without the "latest" version and promo.

I think that whatever code is doing the version comparison, is ignoring the build number.  But I couldn't find the code in the repo, nor do I find the word "satisfies" - so I don't quite know where this is taking place

**Comment by DanTup** [comment]
These icons/CodeLens are not coming from this extension - I suspect you have another extension installed that is providing these.

If you can't find it, please post the output of running `code --list-extensions`.
