### ISSUE TITLE
Widget Inspector not displaying correctly

### ISSUE THREAD

**Issue by renal31** [Dart-Code/Dart-Code#5043]
**Describe the bug**
Widget Inspector display incorrectly in VSCode.
It looks like everything is here, but colors are messed up. (see screenshot below)

**To Reproduce**
1. Run any Flutter app in debug mode (tested on Android and Web platforms)
2. Widget inspectors tab opens automatically but is empty
3. Click on "Open DevTools Widget Inspector Page" in debug tool bar   => Page is refresehed and displays the tree structure lines
4. Click anywhere on invisible tree items => item layout is displayed but lots of data not visible

Additional info: 
* I tried to reinstalled Flutter extension, change theme in Dart extension settings but cannot get it to work properly.
* Everything displays and works fine when opening the devtools in a Chrome browser.

**Expected behavior**
The widget inspector displays correctly

**Screenshots**
![image](https://github.com/Dart-Code/Dart-Code/assets/18248600/e01b520e-56b5-4520-832a-b98d5fa725fe)

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

[log-c2c3.md](https://github.com/Dart-Code/Dart-Code/files/14711560/log-c2c3.md)

 - Operating System and version: Fedora 39
 - VS Code version:
```txt
Version: 1.87.2
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:14:59.643Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 6.7.9-200.fc39.x86_64
```
 - Dart extension version: 3.84.0
 - Dart/Flutter SDK version: 3.3.1 / 3.19.3
 - Target device (if the issue relates to Flutter debugging): Android + Web

**Comment by DanTup** [comment]
Can you click Help -> Toggle Developer Tools in VS Code and see if there are any errors in the console?

This looks a lot like https://github.com/Dart-Code/Dart-Code/issues/4855 which was believed to have been fixed in VS Code.

(cc @lukehutch - I presume this hasn't come back for you?)

**Comment by lukehutch** [comment]
That is definitely the same issue I raised in #4855, but it is resolved for me in:

* code-1.87.2-1709912288.el8.x86_64 (Fedora Linux)
* dart-code v3.85.20240318 (pre-release)

**Comment by lukehutch** [comment]
It's a shader issue, so perhaps there is still a GPU-specific issue here? My GPU is:

* VGA compatible controller: NVIDIA Corporation GP107 [GeForce GTX 1050 Ti] (rev a1)
* driver: nvidia-driver-545.29.06-3.fc39.x86_64

**Comment by renal31** [comment]
Thanks for your feedback.
Here is the issue VS code devevolper tools console log containing lots of errors: [vscode-app-1711143427753-failure.log](https://github.com/Dart-Code/Dart-Code/files/14728770/vscode-app-1711143427753-failure.log)

It also displayed correctly one only time today...
I don't think I made anything differently, but here is the log for this successful display: [vscode-app-1711143092251-success.log](https://github.com/Dart-Code/Dart-Code/files/14728775/vscode-app-1711143092251-success.log)

As you stated it is probably a shader issue (and the logs seem to agree with you), I made a few tests. I have 2 GPUs on my laptop:
* Integrated GPU: VGA compatible controller: Intel Corporation Raptor Lake-P [Iris Xe Graphics] (rev 04)
* Discret card:       3D controller: NVIDIA Corporation GA107M [GeForce RTX 3050 4GB Laptop GPU] (rev a1)

I always use VS code with the Intel **integrated GPU**, and Widget Inspector displays **badly** 99% of the times.
But, today I tested to launch it with the **discret card GPU** many times (`switcherooctl launch code`), and doing so the Widget Inspector always displays **correctly** !

> _Note_: not sure it is related, but when launching using integrated GPU, I often get `Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..` error message while launching *Widget Inspector* window. When it happens, I must close and reopen VSCode to get the Widget Inspector displayed but incorrectly anyway...

**Comment by DanTup** [comment]
Thanks for testing. Based on this, I don't think there's anything we can do in the Dart-Code extension here to improve this. We're abstracted quite far from GPUs. I don't know exactly where the issues lies though (between GPU, drivers, Code/Electron or Flutter/canvaskit)!

(fyi @jacob314 @kenzieschmoll)


> I often get Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state

I see this sometimes too. It seems to be a VS Code issue (it affects other extensions, not only DevTools in Dart-Code):

https://github.com/microsoft/vscode/issues/125993

It's been around for a long time as you noted, requires a full VS Code restart to clear.

**Comment by lukehutch** [comment]
@renal31 this is how I guessed it was a shader bug. This may give you some further leads, and/or you could file upstream:

https://github.com/flutter/devtools/issues/6835#issuecomment-1828876262

**Comment by renal31** [comment]
Thanks @DanTup & @lukehutch for your help & feedback.
I think I'll live with the workaround for instance. ;)

Shall I close this bug ?

**Comment by DanTup** [comment]
Yeah, I'll close - I don't think there's anything for Dart-Code here.
