### ISSUE TITLE
3 packages from my project stopped working

### ISSUE THREAD

**Issue by SrNorton** [Dart-Code/Dart-Code#5044]
The packages are these:    circular_progress_stack: ^0.0.3             msh_checkbox: ^2.0.1.        flutter_dismissible_tile: ^1.0.2

My application was working normally, I was almost finishing my project. After an update it stopped working

**Comment by DanTup** [comment]
Can you provide more details about what stopped working, and what you updated?

Are there error messages? Does the app not start? Does the app look different? It's difficult to diagnose without more information about the problem.

Thanks!

**Comment by SrNorton** [comment]
all these packages are related to a screen animation. msh_checkbox marks a task as complete, flutter_dismissible_tile allows me to drag a tile and delete the task, and circular_progress_stack shows me the percentage of tasks completed in real time. All these features and animations stopped working, only msh_checkbox works on the android emulator, but does not work on ios

**Comment by DanTup** [comment]
@SrNorton it's not very clear to me what "All these features and animations stopped working" means. Are you able to provide a repro and instructions so that I can reproduce the issue and debug?

Thanks!
