### ISSUE TITLE
FLUTTER:OUTLINE is not shown for files from included packages & flutter core files.

### ISSUE THREAD

**Issue by vaibhav891** [Dart-Code/Dart-Code#5045]
**Describe the bug**
Flutter:Outline is available for dart files in my project but not for dart files in included libraries. See attachment.

**To Reproduce**
1. Create a new flutter project.
2. Open in VS Code.
3. Open a dart file in the project and see flutter outline.
4. Open a dart file from flutter core and see flutter outline.

**Expected behavior**
Flutter outline should be shown for both the files.

**Screenshots**
<img width="1280" alt="Screenshot 2024-03-22 at 4 32 08 PM" src="https://github.com/Dart-Code/Dart-Code/assets/62712068/d859554d-bcbc-4e9d-9e5e-8ce24cad5589">

<img width="1280" alt="Screenshot 2024-03-22 at 4 32 28 PM" src="https://github.com/Dart-Code/Dart-Code/assets/62712068/d1fa0331-6417-4d40-8f7b-4690dbc18eff">

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

 - Operating System and version: macos / Version 14.1 (Build 23B74)
 - VS Code version: mac 1.87.2
 - Dart extension version: 3.84.0
 - Dart/Flutter SDK version:
         Dart (3.1.5): /Users/vaibhav/fvm/versions/3.13.9/bin/cache/dart-sdk
         Flutter (3.13.9): /Users/vaibhav/fvm/versions/3.13.9 (My Iphone 12 (ios/ios))
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
This is fixed by https://github.com/dart-lang/sdk/commit/0c9f4054d885673ca8ccee282f4ae4341b596d60. The change is in the SDK (not the Dart-Code extension itself) so the change will show up in a future SDK release.
