### ISSUE TITLE
Sidebar does not load on current Flutter master

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#5049]
This isn't loading today, not sure what changed yet.

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/a929e140-4d6d-49ec-bf0c-c6f52b48992c)

**Comment by DanTup** [comment]
@kenzieschmoll @jacob314 FYI... I haven't tracked down what this is yet (the error isn't very useful and doesn't tell me _what_ frame it tried to access), but I tested with stable and it doesn't occur there, so it seems like something different in Flutter and/or DevTools and not VS Code or Dart-Code.

We do have CSP rules set on the iframe, but from the error I'm not sure this is a CSP issue (usually the error is quite clear for them).

**Comment by DanTup** [comment]
Here's the stack as text:

```
Error: Blocked a frame with origin "http://127.0.0.1:9100" from accessing a cross-origin frame.
    at Object.getNativeInterceptor (http://127.0.0.1:9100/main.dart.js:234:24)
    at Object.getInterceptor$ (http://127.0.0.1:9100/main.dart.js:404:16)
    at Rti._isTestViaProperty [as _is] (http://127.0.0.1:9100/main.dart.js:9227:18)
    at Rti._generalNullableIsTestImplementation [as _is] (http://127.0.0.1:9100/main.dart.js:9218:28)
    at Rti._generalNullableAsCheckImplementation [as _as] (http://127.0.0.1:9100/main.dart.js:9255:24)
    at DartToolingApiImpl_DartToolingApiImpl$postMessage_closure.call$1 (http://127.0.0.1:9100/main.dart.js:196557:48)
    at StaticClosure._rootRunUnary (http://127.0.0.1:9100/main.dart.js:11263:18)
    at _CustomZone.runUnary$2$2 (http://127.0.0.1:9100/main.dart.js:110937:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://127.0.0.1:9100/main.dart.js:110870:14)
    at _ControllerSubscription._sendData$1 (http://127.0.0.1:9100/main.dart.js:109990:19)
```

Based on `DartToolingApiImpl_DartToolingApiImpl$postMessage_closure` I suspect this might be DTD related - though it says "from accessing a cross-origin frame"... does DTD integration in DevTools make use of frames?

**Comment by DanTup** [comment]
Looks like this might be https://github.com/dart-lang/sdk/issues/54938

**Comment by srujzs** [comment]
Following up from our discussion there (thanks for the code btw!), I think the culprit is the type check on the result of `parent` (which is the cross-frame object I believe):

```dart
var t1 = type$.nullable_JavaScriptObject._as(type$.JavaScriptObject._as(self.window).parent);
```

I actually don't see this on master for some reason, but I believe that's because there are some optimization flags eliding the type checks. From a convo with @sigmundch, it seems like there may have been a recent change in the optimization flags (from `-O4` to `-O1`) with devtools. If changing it back or using profile mode is possible, I believe this issue would go away.

Alternatively, if we can't, we can try out some dart2js pragmas here to unsafely cast and avoid the above issue. For example,

```dart
@pragma('dart2js:tryInline')
@pragma('dart2js:as:trust')
T unsafeCast<T>(Object? o) => o as T;

...

final parent = unsafeCast<JSObject>(window.getProperty<JSAny?>('parent'.toJS));
parent.callMethod('postMessage', ...);
```

**Comment by DanTup** [comment]
> From a convo with @sigmundch, it seems like there may have been a recent change in the optimization flags (from `-O4` to `-O1`) with devtools. If changing it back or using profile mode is possible, I believe this issue would go away.

I don't know the answer to this - I presume the change you refer to is https://github.com/flutter/devtools/commit/4208a6213f8a8ac9d730ae5bfee13828d280721e which based on comments at https://github.com/flutter/devtools/pull/7335 may have been done to improve things like stack traces when there are errors in the wild?

@elliette @kenzieschmoll do you have any thoughts on this? It sounds like changing the optimization back might be a nicer change than https://github.com/flutter/devtools/pull/7476 to avoid this issue for now, but it might make debugging issues from users more difficult.

Otherwise, we can try something like the code above (assuming that's better than putting `dart:html` back in).

**Comment by srujzs** [comment]
Yes I believe that's the one. If minification is the issue, we can disable minification but still keep the other optimizations.

Putting `dart:html` will likely affect the Wasm story here, so I'd prefer using the suggestion in the above comment if adding back optimizations isn't viable. (note that none of this addresses the long-term issue of dealing with cross-origin objects, that still requires work on my part)

**Comment by DanTup** [comment]
> Yes I believe that's the one. If minification is the issue, we can disable minification but still keep the other optimizations.

I presume this would be done by removing `-O1` and just adding `--no-minify`?

I can test that in the morning and if it works update my PR (assuming Elliott/Kenzie don't see any reason not to fix it that way).

Thanks!

**Comment by DanTup** [comment]
Oh, looks like there's some related discussion in https://github.com/flutter/devtools/issues/7392 too

**Comment by elliette** [comment]
Just chatted with @kenzieschmoll -  I'm going to open up a PR to switch to building with `--profile`  and we will get that into the release

**Comment by elliette** [comment]
Here's the PR: https://github.com/flutter/devtools/pull/7485

Confirmed it fixes the infinite spinner

**Comment by DanTup** [comment]
@elliette awesome, thank you!

**Comment by sigmundch** [comment]
Thanks all for connecting the various threads together!

**Comment by elliette** [comment]
We missed the branch alignment cut-off by 30 minutes, but I've opened a cherry-pick request for it: https://github.com/dart-lang/sdk/issues/55327

**Comment by DanTup** [comment]
This was fixed - verified on the current Flutter beta (to test the cherry-pick):

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/30625b72-22e1-44c9-81ad-5bf8e4ec8865)
