### ISSUE TITLE
Add a 'go to super method' navigation

### ISSUE THREAD

**Issue by xster** [Dart-Code/Dart-Code#505]
Seems like it's available in IntelliJ. 

```dart
class A {
  void blah() {}
}

class B extends A {
  @override
  void blah() { /* cursor here */ }
}
```

From the cursor position, press a hotkey or execute a command, move to `A.blah()`

**Comment by DanTup** [comment]
@xster FWIW we have a command in the palette called "Show Type Hierarchy". It's not exactly the same as what you're asking for here but it's quite similar - do you think it satisfies this need, or an explicit command you can bind (rather than getting the picklist) more useful?

**Comment by xster** [comment]
The type hierarchy definitely alleviates the friction. Though an exact command like https://www.jetbrains.com/help/idea/navigating-to-super-method-or-implementation.html would be super nice. 

It turns a 2.5 step operation (
1- type hierarchy, go to super
2- cmd-shift-o, look for the same symbol (anecdotally, the operation seems to take anywhere between 1s - 5s for the list to show up)
2.5- disambiguate if say the method exists inside multiple classes in the same file
) into a 1 step operation.

**Comment by xster** [comment]
As a minor extra quality of life difference with class hierarchy, it would be nice if C extends B and B extends A to go straight from C to A if A has a method that B doesn't override but that C does.

**Comment by DanTup** [comment]
I think the analysis server's `overrides` notifications might provide what we need here; though I'm not sure if VS Code has any built-in provider/keybind for it.

https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html#notification_analysis.overrides

**Comment by DanTup** [comment]
@bwilkerson I was going to implement using `getTypeHeirarchy` with `upserOnly: true` however I found that it doesn't seem to work for the example given at the top of this issue. If you invoke it on the method name (or class) it seems to be ok, but inside the body of `blah` seems to return zero items.

Is this expected? If so, what's the best way to implement what's being asked for?

**Comment by DanTup** [comment]
We don't currently hold the outline anywhere, though our legacy symbol provider uses it. Our use of data like this is a bit clunky currently, as we need to send empty edits to force notifications to get the data, or stash them somewhere in a global that each provider/command can access (there is an open request to have request/response for outlines, which would address this https://github.com/dart-lang/sdk/issues/27064).

For now, maybe we should just track things like outlines in our `OpenFileTracker`.. It knows what files are open and when they close (it handles `setPriorityFiles`) so is well placed to keep track and throw away data when it's not needed to avoid leaking over time. We'd have to expose some global method to access the data, but probably isn't a big deal (and in future if we get request/response for some of these notifications it's an easy swap).

**Comment by scheglov** [comment]
Yes, you need to provide the offset of a reference to the method you need hierarchy for. Even if you are inside of a method, you still need to go to its name and invoke hierarchy from there.

Yes, the Dart plugin for IntelliJ (and the Eclipse plugin before it) stores data it receives from Analysis Server while the file is open. https://github.com/JetBrains/intellij-plugins/blob/59af3b8e3ecb215013e6963ae34201e145df8c61/Dart/src/com/jetbrains/lang/dart/analyzer/DartServerData.java

**Comment by DanTup** [comment]
Great, thanks for the info. I'll have a look at stashing this data somewhere so it can be access as necessary.

**Comment by DanTup** [comment]
Got this in #777 though I need to fix some tests before merging.

> As a minor extra quality of life difference with class hierarchy, it would be nice if C extends B and B extends A to go straight from C to A if A has a method that B doesn't override but that C does.

This works, since we wouldn't really have anywhere to take you in B :)

https://github.com/Dart-Code/Dart-Code/blob/ddd021b16c3991aa5313ee743bf5b8882fbc10dd/test/dart_only/commands/go_to_super_method.test.ts#L28-L38
