### ISSUE TITLE
avdmanager is missing from the Android SDK

### ISSUE THREAD

**Issue by ejosephrogo** [Dart-Code/Dart-Code#5054]
am getting this error while trying to create new emulator device on vs code "avdmanager is missing from the Android SDK"

**Comment by DanTup** [comment]
Which platform are you on? This suggests you are missing components from your Android SDK. For Windows, avdmanager should exist in `cmdline-tools\latest\bin` in the Android SDK. For example for me it is at:

```
C:\Users\danny\AppData\Local\Android\Sdk\cmdline-tools\latest\bin\avdmanager.bat
```

If you are missing it, please ensure you have the command line tools installed through Android Studio's SDK manager:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/9b27ecee-f37b-4d50-b27b-f79654e3d19c)

You should also run `flutter doctor -v` and fix any issues listed there.

**Comment by ejosephrogo** [comment]
> Which platform are you on? This suggests you are missing components from your Android SDK. For Windows, avdmanager should exist in `cmdline-tools\latest\bin` in the Android SDK. For example for me it is at:
> 
> ```
> C:\Users\danny\AppData\Local\Android\Sdk\cmdline-tools\latest\bin\avdmanager.bat
> ```
> 
> If you are missing it, please ensure you have the command line tools installed through Android Studio's SDK manager:
> 
> ![image](https://private-user-images.githubusercontent.com/1078012/318728088-9b27ecee-f37b-4d50-b27b-f79654e3d19c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNDExODksIm5iZiI6MTcxMjE0MDg4OSwicGF0aCI6Ii8xMDc4MDEyLzMxODcyODA4OC05YjI3ZWNlZS1mMzdiLTRkNTAtYjI3Yi1mNzk2NTRlM2QxOWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDNUMTA0MTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OThkOTM1MGUyYTE1YjM4NWI0MDc4NDc2ZjVkYTY0MTYwMzJhMzgwYjQzZDdmNGRiYjJlMzBhOWI0ODljYmUyMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.N8EtkmMXyx7GmUIcTLKSy3VyGcsq2Nhxzs-lotDT68M)
> 
> You should also run `flutter doctor -v` and fix any issues listed there.

Thanks alot... The emulator can be seen on Vs code now but I have new issues, I get this error

`Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: C:\Users\Joseph Ejomah\.gradle\wrapper\dists\gradle-7.6.3-all\aocdy2d2z8kodnny3rsumj8i8\gradle-7.6.3-all.zip
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:61)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[!] Gradle threw an error while downloading artifacts from the network.`


On my debug console when I try running the app on emulator but it works fine on browsers

**Comment by DanTup** [comment]
First thing I would try is a reboot. The error sounds like some process has an exclusive lock on a file that it's trying to write. You could try to identify the process but it's probably easier to just reboot to clear everything.

**Comment by bdboygoodboy24** [comment]
ok now

**Comment by DMS-Menula** [comment]
hello/
