### ISSUE TITLE
Missing Hot Reload button in debug toolbar

### ISSUE THREAD

**Issue by iqfareez** [Dart-Code/Dart-Code#5055]
**Describe the bug**

Hot Reload ⚡ button is missing from debug toolbar.

**To Reproduce**
1. Go to 'main.dart' in Flutter project
2. Click on <kbd>Run</kbd> above the `main()`
3. Debug toolbar appears, but with missing Hot Reload :zap:

https://github.com/Dart-Code/Dart-Code/assets/60868965/d22b96b2-a804-4ba9-8806-6bc7af9a9318

**Expected behavior**

:zap:

![Screenshot 2024-04-03 at 6 42 50 AM](https://github.com/Dart-Code/Dart-Code/assets/60868965/14fef3ec-2449-4841-962f-8e43179af165)

p/s: I was able to bring back the hot reload temporarily by changing the "debug.toolBarLocation" in vscode settings.

**Screenshots**

![Screenshot 2024-04-03 at 6 40 25 AM](https://github.com/Dart-Code/Dart-Code/assets/60868965/cb7e6cbb-cb90-4e67-bdf4-7014fdef7ad2)

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.86.0
Flutter extension: 3.86.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: mac 1.87.2

Workspace type: Flutter (LSP)

Dart (3.3.1): /Users/iqmal/Development/flutter/bin/cache/dart-sdk
Flutter (3.19.3): /Users/iqmal/Development/flutter (sdk gphone64 arm64 (android-arm64/android))

```

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`/Users/iqmal/Development/flutter/bin/flutter doctor -v`

```text
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.1.2 23B92 darwin-arm64, locale en-GB)
    • Flutter version 3.19.3 on channel stable at /Users/iqmal/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (4 weeks ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/iqmal/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/iqmal/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-15.0.0.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 14.1.2 23B92 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 123.0.6312.87

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by DanTup** [comment]
The Hot Reload button only appears once the app is up and running. It's not clear from your video whether that's occurred yet or not. Can you confirm that once the app is up and running (and which device you're running on) whether it's still not there?

Can you also clarify what you mean by changing `debug.toolBarLocation` causing it to appear. If that is the only difference, then this may be a VS Code issue because we have no control over the rendering of the debug toolbar, we only tell VS Code to add the button and changes to that setting are all entirely handled by VS Code.

Thanks!

**Comment by iqfareez** [comment]
> Can you confirm that once the app is up and running (and which device you're running on) whether it's still not there?

The app is running, the the hot reload button still doesn't appear.

<img width="1440" alt="Screenshot 2024-04-03 at 11 07 09 PM" src="https://github.com/Dart-Code/Dart-Code/assets/60868965/3ce70f3b-6505-4e34-8701-ee5c9106a5d4">

Hot reload via Ctrl + S still works.

> Can you also clarify what you mean by changing debug.toolBarLocation causing it to appear.

It just a workaround I found to brings back the hot reload button

Here: 


https://github.com/Dart-Code/Dart-Code/assets/60868965/7b0e17ef-d900-4171-8017-54b69711e8d1

> we only tell VS Code to add the button and changes to that setting are all entirely handled by VS Code.

I see. Perhaps a regression from vscode 🤔

**Comment by DanTup** [comment]
Ah, thanks for the info. That does seem like a VS Code issue then - the buttons are all declared up-front and changing the toolbar location doesn't involve the Dart extension at all, the rendering is all handled by VS Code.

I tried searching the VS Code issue tracker but can't see any similar reports - could you file an issue there including your video above and CC me?

Thanks!

**Comment by iqfareez** [comment]
> could you file an issue there including your video above and CC me?

Will do
