### ISSUE TITLE
Consider implementing VSCode's new Test Coverage API

### ISSUE THREAD

**Issue by mark-dropbear** [Dart-Code/Dart-Code#5057]
VSCode now has a native test coverage API that might be worth implementing. Details are available here: 
- https://code.visualstudio.com/api/extension-guides/testing#test-coverage
- https://code.visualstudio.com/updates/v1_88#_test-coverage

**Comment by DanTup** [comment]
There's an existing issue for this at https://github.com/Dart-Code/Dart-Code/issues/2860. Thanks!
