### ISSUE TITLE
Intellisense seems pretty broken with the new VSCode (1.88)

### ISSUE THREAD

**Issue by larssn** [Dart-Code/Dart-Code#5059]
After updating to VSCode 1.88 intellisense is acting weird or not working at all.
I've tried restarting VSCode obviously.

Can anyone verify, or is it just me?

**Comment by DanTup** [comment]
In a quick test I'm not seeing any issues - can you provide more details about exactly the issue you're seeing? Thanks!

**Comment by larssn** [comment]
Most are random, sometimes it works, sometimes it doesn't:
Variables either not getting detected as variables (VSCode's default "guess" variables comes up).
Files getting flagged with warnings due to unused imports (which I've just removed).
Variables not getting detected at all, until you close the file, and reopen them.

Overall, it feels like it's lagging behind or something.
The problem started today.

Here my Flutter doctor:
```
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4.1 23E224 darwin-arm64, locale en-US)
    • Flutter version 3.19.5 on channel stable at /Users/lars/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (8 days ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/lars/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/lars/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.88.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (2 available)
    • macOS (desktop)  • macos            • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 123.0.6312.107

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by DanTup** [comment]
@larssn are you able to produce some examples and/or screen recordings?

You can check whether there's high latency on the server by running the **Dart: Open Analyzer Diagnostics** command and then checking the **Timing** page.

Can you also confirm whether you're using any analyzer plugins? There were a few comments in https://github.com/dart-lang/sdk/issues/55281#issuecomment-2027028048 about older versions of custom_lint causing high CPU and slow responses.

**Comment by larssn** [comment]
Seems to have gone away on its own for now; odd. Your theory about another analyzer plugin hogging all the CPU might have been accurate.

Can we keep the issue open for a few days? In case it comes back?

**Comment by DanTup** [comment]
Are you using analyzer plugins?

Sure, happy to keep it open. The bot will ping if there's no response for a while.

**Comment by DanTup** [comment]
Oh, I meant analyzer_plugins but I think you meant other VS Code extensions?

It is also possible that other VS Code extensions are tying up the extension host (it's single threaded), but the comments I noted above were about custom_lint which is an analyzer plugin (that runs inside the Dart analyzer).

In any case, if it comes back - please try to grab some screenshots of the Timing window noted above (and ideally a recording or detailed description of exactly what you're seeing). Thanks!

**Comment by larssn** [comment]
> Oh, I meant analyzer_plugins

Ah, none of those 😅

**Comment by freemansoft** [comment]
We're seeing something similar with a recent update.

## Organization
Mono repo with maybe 10 apps in it and 10 reusable non published packages that are included in the apps via relative references "../....."

## Expected Results
Intellisense and type checking should work when referencing code in the included packages.

This worked correctly for the last 8 months.

## Actual Results
Type checking no longer works across the packages (mostly).  We don't find type checking errors until we run the app or tests.

**Comment by DanTup** [comment]
@freemansoft how reliably can you reproduce this? Does it only occur for this one project (which I presume is internal/private)?

Can you provide more details about exactly the behaviour you're seeing? It's not very clear exactly what you're seeing. Anything you can do to help me reproduce the issue would help. Thanks!

**Comment by freemansoft** [comment]
Yes, it is an internal project.  I can try and create a submittable example.  

Please disregard my previous comment for issue management purposes. I will submit a new one if I can create a failing example. 

Did see it today in a swarm session and got excited we had an example before realizing it was because they were using dynamic as a return type so it could match anything. 

.
