### ISSUE TITLE
Adopt VSCode 1.20's new CodeAction type

### ISSUE THREAD

**Issue by mjbvz** [Dart-Code/Dart-Code#506]
VS Code 1.20 adds a new [`CodeAction`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L1921) type that attaches additional metadata to code actions. This additional information is already used in a few places:

* `CodeAction.kind` describes the kind of a code action (extract refactoring, quickfix, ...) Kinds are used for VS Code's new `refactor` command, and they are used to [setup keybindings for specific code actions](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_20.md#keybindings-for-quick-fixes-and-code-actions)

* `CodeAction.diagnostics` tells which errors a quickfix addresses. This is used to order quickfixes by severity

Once VS Code 1.20 is released, I suggest that you migrate this extension's `CodeActionProvider` to use the new `CodeAction` type in order to enable support for these new features

Please let me know if you have any question or concerns about the CodeAction API

**Comment by DanTup** [comment]
@mjbvz Thanks for the heads up! Am I right in thinking 1.20 will go stable around the first week of Feb?

Btw, are there any more docs on the kinds? Eg. I'm not sure exactly what the difference with these two are:

```ts
		/**
		 * Base kind for refactoring inline actions.
		 */
		static readonly RefactorInline: CodeActionKind;

		/**
		 * Base kind for refactoring rewite actions.
		 */
		static readonly RefactorRewrite: CodeActionKind;
```

(also: typo - `rewite`)

**Comment by mjbvz** [comment]
We are planning to ship 1.20 in early February, not sure of the exact date yet

Thanks for the feedback. I've added some examples of each of those kinds in the docs. In general `RefactorInline` is for actions that replace references to a value with the value itself, while `RefactorRewrite` is for general code transformations.

The base kinds are what we consider to be the general classes of CodeActions shared across languages. Building off them allows users to setup an "inline" keybinding and have it just work for C# and Dart for example.

I recommend that your extension tracks on more specific information to these base kinds, such as:

```js
const inlineVariableKind = vscode.CodeActionKind.RefactorInline.append('variable')
```

This lets users setup keybindings for "inline variable" specifically. We leave these more specific kinds up to extension authors since they are usually language specific

**Comment by DanTup** [comment]
Cool; thanks. I presume to set a keybinding for "inline variable" if I did what you posted above, the user would need to know exactly what the refactors have been named, it's not something that's easily discoverable to them?

Btw, is there any way for an extension to influence the ordering of code actions (when not tied to diagnostics)? (I don't have a need for it yet, just wondering)

**Comment by mjbvz** [comment]
Yes, I suggest documenting this currently. If you do create a keybinding for `refactor.extract`, `refactor.extract.inline` will also show up however, so users may not need to know specific names. An extensions could also contribute its own keybindings for the `editor.action.codeAction` command

Currently only quick fixes are sorted. Otherwise we maintain the order of code actions that extensions return to us.

**Comment by DanTup** [comment]
This has shipped now, release notes here:
https://code.visualstudio.com/updates/v1_20#_keybindings-for-quick-fixes-and-code-actions

Seems like a simple change that would be quite useful so I'll take a look for v2.9.

**Comment by DanTup** [comment]
> `CodeAction.diagnostics`

Am I right in thinking these don't need to be the same instance, but the values are compared? I do have access to the list of errors a code action is intended to fix, but it's from a different request to the diagnostics provider so the references won't match.

(Actually, now I think about it; are you even comparing them at all, or just reading the severity to sort? If so, why take the whole diagnostic?)

**Comment by DanTup** [comment]
This is done for vNext; though we don't currently implement all refactors, only fixes and what Dart analysis server calls "assists" (single-file input-less refactors). We don't get any useful IDs for these, so they just all get their kind set to QuickFix or Refactor, but I've raised the question of whether we can get specific IDs (and when we come to implement the refactors, we will be able to do this).

**Comment by DanTup** [comment]
@mjbvz I looked at implementing our refactors, but I'm not convinced they fit well in the lightbulb menu - seems like we'd end up with lightbulbs active all the time. I think they'd better on a sub-menu of the context menu (which it seems we can't do yet https://github.com/Microsoft/vscode/issues/9827).

Do you know if many other languages are all putting all refactors into code actions?

**Comment by mjbvz** [comment]
Yes, JS/TS  puts all refactorings and quick fixes in the lightbulb menu. We've discussed introducing a `Refcatoring` context menu as well that would only show refactorings

JS/TS only shows refactorings when you have an active text selection and the selected text is refactorable. Would that also work for your refactorings?

**Comment by DanTup** [comment]
@mjbvz It could do; I'm just worried about those that apply always (for example our language server has a "move file" which is always available).

Maybe I should go through them and handle them differently depending on how they work - for ex. making a palette command for "move file" and add all those that use selections into this list.
