### ISSUE TITLE
RainbowBrackets bug with `Map`/`Set` inside string interpolation.

### ISSUE THREAD

**Issue by FMorschel** [Dart-Code/Dart-Code#5061]
**Describe the bug**
As I have already created an issue [here](https://github.com/microsoft/vscode/issues/209435) which directed me to create this one.

If there is a Dart string interpolation that shows an explicit map/set.

The first opening bracket is showing red and the second to last one (the last one on line 3) is showing blank.

This also happens (without the need for a restart) if you call a method in the explicit map:
![Visual bug](https://github.com/Dart-Code/Dart-Code/assets/52160996/37d6718f-454b-4f46-a29c-d3b8472d8cd4)
And even removing the call for the method does not restore the previous colours.

**To Reproduce**

- Clean VSCode install (or at least uninstall `dart-code.dart-code` it and restart vscode) 
- Install the latest pre-release (v3.87.20240402) or the latest release (v3.86.0)
- Add this to a .dart file:

```
class A {
  @override
  String toString() => '${ {} }';
}
```

- See that everything works
![Code without bug](https://github.com/Dart-Code/Dart-Code/assets/52160996/b3d73df2-24cb-4406-bfd6-62b2029544cd)
- Restart vscode
- See bug: 
![Code with visual bug](https://github.com/Dart-Code/Dart-Code/assets/52160996/8b8b8a39-5210-4d9a-aeea-6e1c028e993c)

**Expected behavior**
Even after restarting vscode there should be no visual bugs with rainbow brackets.

**Please complete the following information:**

### Release
<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.86.0

App: Visual Studio Code - Insiders
App Host: desktop
Version: win 1.89.0-insider

Workspace type: Dart (LSP)

Dart (3.3.3): C:\Users\usuario\.puro\shared\caches\e76c956498841e1ab458577d3892003e553e4f3c\dart-sdk
Flutter (undefined): C:\Users\usuario\.puro\envs\stable\flutter (No device)

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`C:\Users\usuario\.puro\shared\caches\e76c956498841e1ab458577d3892003e553e4f3c\dart-sdk\bin\dart.exe info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.3.3 (stable) (Tue Mar 26 14:21:33 2024 +0000) on "windows_x64"
- on windows / "Windows 10 Pro" 10.0 (Build 22631)
- locale is en-GB

#### Process info

| Memory | CPU | Elapsed time | Command line |
| -----: | --: | -----------: | ------------ |
| 331 MB |  -- |              | dart.exe     |
|  96 MB |  -- |              | dart.exe     |

</details>

### Pre-release

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.87.20240402

App: Visual Studio Code - Insiders
App Host: desktop
Version: win 1.89.0-insider

Workspace type: Dart (LSP)

Dart (3.3.3): C:\Users\usuario\.puro\shared\caches\e76c956498841e1ab458577d3892003e553e4f3c\dart-sdk
Flutter (undefined): C:\Users\usuario\.puro\envs\stable\flutter (No device)

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`C:\Users\usuario\.puro\shared\caches\e76c956498841e1ab458577d3892003e553e4f3c\dart-sdk\bin\dart.exe info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.3.3 (stable) (Tue Mar 26 14:21:33 2024 +0000) on "windows_x64"
- on windows / "Windows 10 Pro" 10.0 (Build 22631)
- locale is en-GB

#### Process info

| Memory | CPU | Elapsed time | Command line |
| -----: | --: | -----------: | ------------ |
| 243 MB |  -- |              | dart.exe     |
|  96 MB |  -- |              | dart.exe     |

</details>

**Comment by DanTup** [comment]
Here's how the original sample looks now:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/331ce5e7-b87e-43ce-8035-1bf2a6301f52)
