### ISSUE TITLE
Open online interactive sample leads to 404 for non-classes (mixins, extension types)

### ISSUE THREAD

**Issue by PurplePolyhedron** [Dart-Code/Dart-Code#5062]
**Describe the bug**
Open online interactive sample of `RestorationMixin` leads to 404 for 

**To Reproduce**
Go to `RestorationMixin` 
tap Open online interactive sample for RestorationMixin

**Expected behavior**
It should open https://api.flutter.dev/flutter/widgets/RestorationMixin-mixin.html
but it opens https://api.flutter.dev/flutter/widgets/RestorationMixin-class.html , which don't exist

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

Dart Code extension: 3.87.20240402
Flutter extension: 3.87.20240402 (activated)

App: Visual Studio Code
App Host: desktop
Version: mac 1.88.0

Flutter version: Flutter (Channel master, 3.22.0-5.0.pre.59, )

**Comment by DanTup** [comment]
Good catch - looks like mixins and extension types have their own suffixes in URLs and we always assumed `-class`. Fixed for the next release.
