### ISSUE TITLE
Color picker should const if it is originally const

### ISSUE THREAD

**Issue by normidar** [Dart-Code/Dart-Code#5068]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when used color picker.

**Describe the solution you'd like**
After pick color, make color const if it is originally const.

**Describe alternatives you've considered**
Maybe close to #4978 

**Additional context**

My class:

```dart
class ColorList {
  const ColorList({
    this.color = const Color.fromARGB(255, 182, 134, 153), // The default value of an optional parameter must be constant.
  });
}
```

**Comment by normidar** [comment]
My version: v3.86.0

**Comment by DanTup** [comment]
Thanks for the report - working on a fix at https://dart-review.googlesource.com/c/sdk/+/362801

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/e067bf7815e94a59c18e42fb90d1663ae5c53c86. The fix is in the Dart analysis server so will show up in a future Flutter SDK release (not a Dart-Code extension release).
