### ISSUE TITLE
Analysis error is not cleared until file is modified again

### ISSUE THREAD

**Issue by orestesgaolin** [Dart-Code/Dart-Code#5073]
**Describe the bug**
When analysis error occurs (e.g. type is not found despite import being present), the only way to get rid of the error is to modify the file again and save.

**To Reproduce**
1. Add usage of new type (in my case `BluetoothDeviceRepository`)
2. Add necessary import and save file
3. Observe the error as on the screen recording
4. Modify the file, e.g. add newline and save the file
5. Observer the error to disappear

**Expected behavior**

Error should disappear on first file save.

**Screenshots**

https://github.com/Dart-Code/Dart-Code/assets/16854239/d09351d9-a335-4f78-bc92-b604b7e68382

**Please complete the following information:**

Dart-Code log below

[Dart-Code-Log-2024-03-02 12-03-00.txt](https://github.com/Dart-Code/Dart-Code/files/14995213/Dart-Code-Log-2024-03-02.12-03-00.txt)

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.86.0
Flutter extension: 3.86.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: mac 1.88.1

Workspace type: Dart, Flutter (LSP)

Dart (3.2.6): /Users/dominik/fvm/versions/3.16.9/bin/cache/dart-sdk
Flutter (3.16.9): /Users/dominik/fvm/versions/3.16.9 (iPhone 12 mini (ios/ios))

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`/Users/dominik/fvm/versions/3.16.9/bin/cache/dart-sdk/bin/dart info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.2.6 (stable) (Wed Jan 24 13:41:58 2024 +0000) on "macos_arm64"
- on macos / Version 13.5.2 (Build 22G91)
- locale is pl-PL

#### Project info

- sdk constraint: '>=3.0.0 <4.0.0'
- dependencies: android_intent_plus, app_settings, bloc, collection, device_info_plus, dotted_border, drift, equatable, file, firebase_auth, firebase_core, firebase_crashlytics, firebase_messaging, flutter, flutter_animate, flutter_bloc, flutter_blue_plus, flutter_localizations, flutter_markdown, flutter_svg, formz, google_sign_in, http, hydrated_bloc, in_app_review, intl, json_annotation, modal_bottom_sheet, path, path_provider, provider, rive, rxdart, scidart, share_plus, simple_date, stack_trace, timeago, tuple, url_launcher, video_player, wakelock_plus, webview_flutter, workmanager
- dev_dependencies: bloc_test, build_runner, drift_dev, flutter_test, intl_utils, json_serializable, mocktail, very_good_analysis
- elided dependencies: 29

#### Process info

| Memory |  CPU | Elapsed time | Command line                                                                               |
| -----: | ---: | -----------: | ------------------------------------------------------------------------------------------ |
|  14 MB | 0.0% |     19:54:08 | dart devtools --machine --allow-embedding                                                  |
| 430 MB | 0.0% |     19:54:08 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.86.0            |
|  46 MB | 0.0% |     19:54:08 | flutter_tools.snapshot daemon                                                              |
| 212 MB | 8.7% |        29:00 | flutter_tools.snapshot debug_adapter                                                       |
| 222 MB | 5.5% |        29:00 | flutter_tools.snapshot run --machine --start-paused --vmservice-out-file=detective_connect.txt -d 00008101-0001510C3CF0001E --devtools-server-address http:<path>/ --target <path>/main_tst.dart --flavor tst |
| 410 MB | 0.0% |        28:55 | frontend_server.dart.snapshot --sdk-root <path>/ --incremental --target=flutter --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true -DFLUTTER_WEB_CANVASKIT_URL=https:<path>/ -DFLUTTER_APP_FLAVOR=tst --output-dill <path>/app.dill --packages <path>/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/7ef1c01d4f00f08f4dbb0791e75ec020.cache.dill.track.dill --source file:<path>/dart_plugin_registrant.dart --source package:flutter<path>/dart_plugin_registrant.dart -Dflutter.dart_plugin_registrant=file:<path>/dart_plugin_registrant.dart --verbosity=error --enable-experiment=alternative-invalidation-strategy |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`/Users/dominik/fvm/versions/3.16.9/bin/flutter doctor -v`

```text
[!] Flutter (Channel stable, 3.16.9, on macOS 13.5.2 22G91 darwin-arm64, locale pl-PL)
    • Flutter version 3.16.9 on channel stable at /Users/dominik/fvm/versions/3.16.9
    ! Warning: `flutter` on your path resolves to /Users/dominik/fvm/versions/stable/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/dominik/fvm/versions/3.16.9. Consider adding /Users/dominik/fvm/versions/3.16.9/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.2.0/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/dominik/fvm/versions/3.16.9. Consider adding /Users/dominik/fvm/versions/3.16.9/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (3 months ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/dominik/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (3 available)
    • iPhone 12 mini (mobile) • 00008101-0001510C3CF0001E • ios            • iOS 17.4.1 21E236
    • macOS (desktop)         • macos                     • darwin-arm64   • macOS 13.5.2 22G91 darwin-arm64
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 123.0.6312.124

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by DanTup** [comment]
@orestesgaolin so you have steps to get to the point of the error showing? The logs files here are started once things are already in a bad state (eg. there are diagnostics showing that are bogus).

I tried following your steps (referencing a new class, then adding the import) but I wasn't able to reproduce - the diagnostic vanished when I added the import.

Thanks!

**Comment by DanTup** [comment]
How frequently does this happen? You could have the logs capturing all the time (using the `dart.analyzerInstrumentationLogFile` setting or `dart.analyzerLogFile` setting) and grab a copy when you next see this. They can get quite large though so you'd need to keep an eye on them (and probably you'd only want to set them in the Workspace settings for the project you most see this one, to avoid other projects overwriting the same log file).

**Comment by orestesgaolin** [comment]
Couldn't reproduce it again on the newest version. Imho it can be closed now.

**Comment by DanTup** [comment]
Thanks - please let me know if you do start seeing it again :)
