### ISSUE TITLE
Add support for show performance data (Rebuild stats) like IntelliJ or Android Studio

### ISSUE THREAD

**Issue by MiniSuperDev** [Dart-Code/Dart-Code#5075]
https://docs.flutter.dev/tools/android-studio#fast-edit-and-refresh-development-cycle

![image](https://github.com/Dart-Code/Dart-Code/assets/105388540/aaece5f8-063d-4228-981f-543903d1854e)

Thanks

**Comment by DanTup** [comment]
@kenzieschmoll I can see a screenshot of this in DevTools at https://github.com/flutter/devtools/issues/4886, and I can see some related code at https://github.com/flutter/devtools/blob/27fad16081132e164583ac6612235d9e63a2c230/packages/devtools_app/lib/src/screens/performance/panes/rebuild_stats/rebuild_stats.dart#L129, however I've not been able to figure out how to get to this in the Performance view embedded inside VS Code (I tried both debug and profile mode).

From the code, it seems like I might need to enable "track rebuild widgets" but I can't find a way to do that.

**Comment by kenzieschmoll** [comment]
There is a DevTools [experiment flag](https://github.com/flutter/devtools/blob/master/packages/devtools_app/lib/src/shared/feature_flags.dart/#L57) for this feature, and it also requires patching the changes on https://github.com/jacob314/flutter/tree/rebuild_indicators. @jacob314 did some work for this over a year ago now, but this work needs to be pushed across the finish line for us to remove the experiment flag in DevTools.

The tracking issue for the widget rebuild stats feature is https://github.com/flutter/devtools/issues/4564.

**Comment by DanTup** [comment]
Ah, thanks! I failed to find that because I was using the wrong words.

Closing this in favour of https://github.com/flutter/devtools/issues/4564 then.
