### ISSUE TITLE
how to enable source.addMissingImports or any other auto imports?

### ISSUE THREAD

**Issue by altynbek132** [Dart-Code/Dart-Code#5078]
is there any feature that fixes all "not imported" errors by importing imports?
any ideas how to do it?

**Comment by DanTup** [comment]
This is not currently possible - there's an open issue about supporting this (in the Dart analysis server) at https://github.com/dart-lang/sdk/issues/30296.

There's also https://github.com/Dart-Code/Dart-Code/issues/351 which is about bringing imports automatically when you copy/paste code between files. Unfortunately that's blocked on a VS Code API that has not been finalized (https://github.com/microsoft/vscode/issues/30066).
