### ISSUE TITLE
Better equality checks

### ISSUE THREAD

**Issue by Priyantha-Kingslake** [Dart-Code/Dart-Code#5080]
There are times when we have to chain a list of equality checks. Eg:
```
if(o.num == null || o.num == 0 || o.num == 100)
```
Could be better if these chains of conditional checks can be written in a compact method

A possible solution, something that I always wonder why its not already implemented in code is as follows,
```
if(o.num == (null || 0 || 100))
```

I don't know if there are any limitations preventing this. Surely, someone else should have gone through this idea before, right?
It really is just Syntactic sugar, but if anything, syntactic sugar does make life easier

**Comment by DanTup** [comment]
This repository is just for the VS Code extension. Ideas for changes to the Dart language itself should be filed at https://github.com/dart-lang/language

Thanks!
