### ISSUE TITLE
CrnoMace

### ISSUE THREAD

**Issue by mzlatko8219** [Dart-Code/Dart-Code#5081]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

 - Operating System and version:
 - VS Code version:
 - Dart extension version:
 - Dart/Flutter SDK version:
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
@mzlatko8219 did you open this in error? If not, are you able to provide some more details about the issue you're having? Thanks!
