### ISSUE TITLE
Default opening DevTools to the home screen when a page is not specified

### ISSUE THREAD

**Issue by kenzieschmoll** [Dart-Code/Dart-Code#5083]
What should happen is that there should be no page specified, so then it would default to opening the first tab (which is the home screen).

![Screenshot 2024-04-24 at 11 16 19 AM](https://github.com/Dart-Code/Dart-Code/assets/43759233/80d56706-3e15-4b8a-a9d0-afa52429d5db)

**Comment by DanTup** [comment]
There was some reason we had to set a default screen in Dart-Code (maybe to avoid showing the connection screen?), so I think I just picked the first.

The home screen was added in https://github.com/flutter/devtools/pull/6010, we should default to that when using an appropriate SDK version.
