### ISSUE TITLE
Where is $dart-build_runner problem matcher defined?

### ISSUE THREAD

**Issue by Rodsevich** [Dart-Code/Dart-Code#5085]
It's just that, Danny. I'm wondering where it is defined for VSCode for I'm trying to write the problem matcher for serverpod and I'm not finding an example nor a way of debugging what I've already done. Any ideas on those topics with which you can help me?

**Comment by DanTup** [comment]
Problem matches are declared in `package.json` here:

https://github.com/Dart-Code/Dart-Code/blob/a4cc006b73972b5a113367bea73e0fa521845a89/package.json#L3187-L3193

Unfortunately I don't know of a good way to debug them besides just manual testing (or applying the patterns yourself to sample output).

**Comment by Rodsevich** [comment]
Thank you so much, Danny!
