### ISSUE TITLE
Add common Angular Dart Snippets

### ISSUE THREAD

**Issue by varora1406** [Dart-Code/Dart-Code#509]

**Comment by DanTup** [comment]
Until #68 is done, we don't really have the concept of a Dart web app so it'd make most sense then. The work in #474 will allow project-type-specific snippets.

For now, you can have your own snippets as described here:

https://code.visualstudio.com/docs/editor/userdefinedsnippets

(btw @bwilkerson - have you thought about having snippets provided by the analyzer? It occurs to me that there would be consistency (and less work) across editors if they were just built-in to the code completion)

**Comment by varora1406** [comment]
I will work on this further and if a good bunch of snippets got prepared at my end.
Then, will propose same for community.

**Comment by bwilkerson** [comment]
> ... have you thought about having snippets provided by the analyzer?

Yes, and I'd love to see that happen. We just haven't had the time so far to design the right API for it.

**Comment by DanTup** [comment]
There's an open issue about having snippets in the analysis server (https://github.com/dart-lang/sdk/issues/37831) so I don't think it makes to pursue this here. Snippets declared inside this extension aren't context-sensitive so show up in places you wouldn't want them (like inside strings, comments, import statements) so I'd like to ultimately reduce the number of them defined here.
