### ISSUE TITLE
Flutter gradle builder is not using correct JDK

### ISSUE THREAD

**Issue by lukehutch** [Dart-Code/Dart-Code#5091]
I get this error at the top of my `android/app/build.gradle`:

> The supplied phased action failed with an exception.
> A problem occurred configuring root project 'android'.
> A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
> Build file '/home/luke/Work/click/click_flutter/android/app/build.gradle' line: 2
> An exception occurred applying plugin request [id: 'com.android.application']
> Failed to apply plugin 'com.android.internal.application'.
> Android Gradle plugin requires Java 17 to run. You are currently using Java 11.
>  Your current JDK is located in /usr/lib/jvm/jdk-11-oracle-x64
>  You can try some of the following options:
>   - changing the IDE settings.
>   - changing the JAVA_HOME environment variable.
>   - changing `org.gradle.java.home` in `gradle.properties`.

`compileOptions` and `kotlinOptions` are both set to use JDK 17.

![image](https://github.com/Dart-Code/Dart-Code/assets/811305/71e64559-eb44-4091-9bd8-459a568e10ce)

The VS Code `Java > Import > Gradle > Java: Home` setting is correctly set to `/usr/java/jdk-17`:

![image](https://github.com/Dart-Code/Dart-Code/assets/811305/8ffe81b7-6263-4bf2-899a-fd35a91725e7)

My JAVA_HOME is set to point to JDK 17, and the `java` bin is also running version 17:

![image](https://github.com/Dart-Code/Dart-Code/assets/811305/9e815d93-a489-4a8f-a8eb-1133e68aef4d)

`grep -r jdk-11 .` does not find any references in the project to JDK 11.

I tried putting `org.gradle.java.home=/usr/java/jdk-17` in `gradle.properties`, but it didn't solve the problem.

What else can I try?

**Comment by lukehutch** [comment]
I deleted `~/.gradle`, killed all gradle server processes, reloaded the window -- no luck so far.

**Comment by DanTup** [comment]
Does this only occur in VS Code, or also from the terminal?

If it works in the terminal, and then you launch VS Code _from the terminal_, does it then work in VS Code?

If it doesn't work in the terminal, then I don't think the issue is related to the VS Code extension and unfortunately I know almost zero about Java/Gradle.

One other potential thing to try if you haven't customised the android app though is deleting the `android` folder and re-running `flutter create .` to get it back.

**Comment by lukehutch** [comment]
Building works in the terminal, and I always launch VS Code from the terminal. Running the app works in VS Code.

I have too many customizations in my android sub-project to delete it, but I created a new project (which built fine) and compared every file manually. I couldn't see any meaningful differences in the project files themselves.

**Comment by lukehutch** [comment]
It appears that when an Android project is first opened in VS Code, the JDK path is stored in `~/.config/Code/User/workspaceStorage`, e.g. in `~/.config/Code/User/workspaceStorage/5d85350e60ec33217eabcc96b0878a81/redhat.java/ss_ws/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.jdt.launching.prefs` (and other locations).

No matter how you change your Java settings in VS Code after that, the Eclipse JDT plugin that is used to run JVM code (including Gradle) is stuck on that JVM.

Killing VS Code, Dart, and all Java processes, including the language server, then deleting `~/.config/Code/User/workspaceStorage` and restarting VS Code, seems to fix the issue. Took me forever to figure this out!

Since this is not a Dart issue, I will close this. Thanks!
