### ISSUE TITLE
chose

### ISSUE THREAD

**Issue by Eco5sdefi** [Dart-Code/Dart-Code#5095]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

 - Operating System and version:
 - VS Code version:
 - Dart extension version:
 - Dart/Flutter SDK version:
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
I think this issue was created in error, but if you have a problem or a feature suggestion, please open a new issue or edit the title here and ping me a comment. Thanks!
