### ISSUE TITLE
Remove use of page= query param for DevTools embeddings

### ISSUE THREAD

**Issue by kenzieschmoll** [Dart-Code/Dart-Code#5098]
There is a [TODO](https://github.com/flutter/devtools/blob/master/packages/devtools_app/lib/src/app.dart/#L249-L254) in the DevTools codebase to stop using the `page` query parameter from IDEs.

@DanTup can you confirm that we do not use this from VS Code? If we do not use this, this issue can be closed. If we do, we should migrate to use the path based routing, which has been the DevTools standard for a number of years now.

**Comment by DanTup** [comment]
Correct, we stopped using page= in https://github.com/Dart-Code/Dart-Code/issues/3800 for new SDKs.

You might need to update the DevTools server's implementation of launchDevTools along with removing it though (and any other places in Dart/Flutter that might be building these URLs):

https://github.com/dart-lang/sdk/blob/6bec589f00d1009199912eceb327294c72934b7b/pkg/dds/lib/devtools_server.dart#L714
