### ISSUE TITLE
Could not find a Dart sdk to use

### ISSUE THREAD

**Issue by varora1406** [Dart-Code/Dart-Code#510]
![image](https://user-images.githubusercontent.com/24986539/35481252-214b7ba2-0446-11e8-97ba-fc9f08202ab7.png)

In Visual Studio code on my Windows machine, I am getting this error and I guess due to this I am unable to many formatting features of your plugin.

Apart from this, I checked and PATH variables have Dart and I am able to use 'pub' command and run project as well.

**Comment by DanTup** [comment]
Sorry for the bother! A few questions to help me investigate:

Have you restarted VS Code since adding Dart to your PATH? Is it in the system path or your user PATH?

If you open up your Code user settings and set `dart.sdkPath` to the correct folder, does it still fail or work?

Are you able to paste your full paths (redact anything sensitive)?

**Comment by varora1406** [comment]
User and System variables, both have path to my dart sdk.
I have restarted my visual studio code multiple times.

But now after your recommendation, I have overridden Code user settings and it worked.

**Comment by varora1406** [comment]
One thing lemme tell you for sure, Path variable(User & System variable) has a long string including path to many things.

**Comment by varora1406** [comment]
My problem is resolved but actual problem still exists that it is unable to get Path from User/System variables of system.

**Comment by varora1406** [comment]
Should I log a separate ticket for Dart path which is unable to found directly?

**Comment by DanTup** [comment]
Adding it to settings wasn't a proposed fix, it was part of troubleshooting (and a short-term fix for you). I understand that PATHs can be very long.

This is the code we use to get all of the paths:

```js
(process.env.PATH as string).split(path.delimiter);
```

We add the user setting to the front of that array and then enumerate those values checking if any are a Dart SDK. What you're reporting suggests that we can detect the SDK when you add the path directly, but not from PATH. This suggests something is wrong with the path parsing.

Do you have nodejs? Can you evaluate `process.env.PATH` in it and see whether your Dart SDK path is in the results?

**Comment by DanTup** [comment]
> Should I log a separate ticket for Dart path which is unable to found directly

I'm not sure I understand - that's what this ticket is about?

**Comment by varora1406** [comment]
Yes I am able to find Dart SDK path in results
![image](https://user-images.githubusercontent.com/24986539/35481830-c60d69ec-0451-11e8-88c3-b849b18d7e18.png)

**Comment by DanTup** [comment]
Hmm, I'm not sure what's going on here. Are you able to try and debug it a little?

To do so, you would:

- Clone this repo
- Open the repo folder in VS Code
- Open `src/utils.ts` and add a breakpoint around line 85 where we try to find the Dart SDK
- Press F5 - this will launch a new instance of VS Code that is running the extension
- In the new version of Code (labelled the "extension development host") open up a Dart project
- When it flips back to the original Code window and hits the breakpoint, step through the code and see if you can figure out why the folder from PATH is not being detect as a valid Dart SDK

If you can't get anywhere with that, let me know and I can try and extract the code here into a small JS script you can run via nodejs to test more easily.

**Comment by DanTup** [comment]
Based on #511 I think something is wrong and Code doesn't have your PATH correctly. Did you only recently install Dart? Could you try rebooting to see if that solves the issue?
