### ISSUE TITLE
`ctrl + alt` shows inferred types (inlay hints) with no option to disable

### ISSUE THREAD

**Issue by joeriddles** [Dart-Code/Dart-Code#5102]
**Describe the bug**
Pressing the `ctrl + alt` key combination shows inferred types with no ability to change or disable the behavior.

**To Reproduce**

```dart
// hello.dart
const string = "hello world";
```

1. Create and open the above file in VS Code
2. Press `ctrl + alt`
3. See the inferred type, `String`

**Expected behavior**
I want to be able to reassign the keyboard shortcut or disable it to not interfere with other keyboard shortcuts that use `ctrl + alt`.

**Screenshots**

https://github.com/Dart-Code/Dart-Code/assets/19392916/458c1bdf-01fa-4f21-94fa-3eb15112271a

---

**Please complete the following information:**

Dart Code extension: 3.88.0
Flutter extension: 3.88.0 (not activated)

App: Visual Studio Code
App Host: desktop
Version: mac 1.89.0

Workspace type: Flutter (LSP)

Dart (3.3.4): /Users/.../tools/flutter/bin/cache/dart-sdk
Flutter (3.19.6): /Users/.../tools/flutter (Chrome (web-javascript/web))

**Comment by DanTup** [comment]
Hi!

This feature is called "Inlay Hints" and it's VS Code that controls when they are shown/hidden. To change the settings, please do the following:

- Press `F1` to open the command palette
- Run the **Preferences: Open User Settings** command
- Paste `@lang:dart inlay hint` into the search box
- Change the **Editor -> Inlay Hints** setting to `off`

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/1fbe1111-bc11-468a-98cc-09becf278c66)

Please let me know if this does not solve the problem. Thanks!

**Comment by joeriddles** [comment]
Thanks @DanTup! That worked.
