### ISSUE TITLE
No code folding for`for` statements in VSCode

### ISSUE THREAD

**Issue by lowski** [Dart-Code/Dart-Code#5107]
**Describe the bug**
There is no folding option for `for` statements when using VSCode.

**To Reproduce**
Open a new file and add a `for` statement.

**Expected behavior**
As for other control statements such as `if`, `while`, `switch`, ..., there should be an option to fold `for` statements.

**Screenshots**
![image](https://github.com/Dart-Code/Dart-Code/assets/37808546/8caa2105-68bb-4d21-9b26-10bb875cb18b)

**Please complete the following information:**
 - Operating System and version: macos / Version 14.2
 - VS Code version: mac 1.90.0-insider
 - Dart extension version: 3.88.1
 - Dart/Flutter SDK version: 3.3.1 (Dart) / 3.19.3 (Flutter)

**Comment by DanTup** [comment]
This has been fixed (via https://github.com/Dart-Code/Dart-Code/issues/4780) and shipped in the latest Dart/Flutter SDKs. Please run `flutter upgrade` to get the latest version which includes the fix:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/1215e9dd-2fb2-47e8-bf18-8eef861a5fb9)
