### ISSUE TITLE
Add "See in pub.dev" in Codelens above each package in pubspec.yaml

### ISSUE THREAD

**Issue by MiniSuperDev** [Dart-Code/Dart-Code#5108]
![image](https://github.com/Dart-Code/Dart-Code/assets/105388540/f290bbac-bb52-4d88-8c8b-aaf30f21bf54)
When you click on "See in pub.dev" it opens the corresponding page in the browser.
In this case https://pub.dev/packages/freezed_annotation

There is a [similar extension](https://marketplace.visualstudio.com/items?itemName=everettjf.pubspec-dependency-search) with 111,789 installs that do that. But it not open the corresponding page, and is outdated.

Thanks.

**Comment by DanTup** [comment]
Thanks - there's an existing issue for something like this at https://github.com/Dart-Code/Dart-Code/issues/2785
