### ISSUE TITLE
Support autocompletion / intellisense in the Debug Console input (Debug Console REPL) like in TypeScript

### ISSUE THREAD

**Issue by MiniSuperDev** [Dart-Code/Dart-Code#5109]
Hello

https://code.visualstudio.com/docs/editor/debugging#_debug-console-repl

In TypeScript it show autocomplete for all variables in the scope:

![image](https://github.com/Dart-Code/Dart-Code/assets/105388540/9a53e1de-e0a0-4690-9b20-2710294a2059)

And also autocomplete for the methods and properties of the variable.

![image](https://github.com/Dart-Code/Dart-Code/assets/105388540/9fafbd85-2f27-4c97-ba02-694286da2761)

in Dart it doesn't show anything

![image](https://github.com/Dart-Code/Dart-Code/assets/105388540/a2b16b6c-8058-4e6b-a0e5-558ec00cab33)
![image](https://github.com/Dart-Code/Dart-Code/assets/105388540/a30c1cdc-b193-468d-8c42-7bb359ea49a3)

```ts
function hello(): void {
  const text: String = "hello world";
  console.log(text);
}

hello();
```

```dart
void main() {
  final String text = "hello world";
  print(text);
}
```

**Comment by DanTup** [comment]
There's an existing issue about this at https://github.com/Dart-Code/Dart-Code/issues/169

So far it has no 👍 's so I don't know how much demand there is for it. I think DevTools has some code to provide this there, so it might give a starting point (or be something we could easily move into the debug adapters now they're in Dart).
