### ISSUE TITLE
VS Code Terminal window is not recognizing 'pub' commands. Terminal Window outside VS is able to get 'pub' commands. Is this resolvable?

### ISSUE THREAD

**Issue by varora1406** [Dart-Code/Dart-Code#511]
VS:
![image](https://user-images.githubusercontent.com/24986539/35481870-563ce2cc-0452-11e8-80a3-db31b69bddfa.png)

Window Terminal outside VS:
![image](https://user-images.githubusercontent.com/24986539/35481875-6672eb0a-0452-11e8-876e-b92b5cf0053c.png)

**Comment by DanTup** [comment]
This isn't something Dart Code has influence over; the Terminal in Code is entirely Codes. It seems to me like Code is not inheriting your path correctly.

Did you only recently install Dart? Could you try rebooting to see if that solves the issue? I think whatever is wrong here is also what's causing #510.

**Comment by varora1406** [comment]
Gotcha, System restart resolved this issue as well as #510 too

**Comment by DanTup** [comment]
Cool; seems like VS Code had a stale path. I would've expected a restart of just VS Code to fix that, but I have had weird issues with PATHs not updating until reboot in other apps before. Glad you got it sorted :-)
