### ISSUE TITLE
Server diagnostics can reappear for deleted/moved files if analyzer plugins generate new diagnostics (even if empty)

### ISSUE THREAD

**Issue by Coin-ai** [Dart-Code/Dart-Code#5113]
**Describe the bug**
Moved, renamed or deleted file analysis warnings and lints don't dissapear
From https://github.com/Dart-Code/Dart-Code/issues/4658
dart_code_metrics - third party

**To Reproduce**
<details>
<summary>pubspec.yaml</summary>

```
name: 'test'
description: test
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.0.5<4.0.0'
  flutter: '>=3.13.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  dart_code_metrics: ^5.7.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
```
</details>

<details>
<summary>analysis_options.yaml</summary>

```
analyzer:
  plugins:
    - dart_code_metrics
include:
    package:lints/recommended.yaml
```

</details>

copy paste main.dart  -> (need wait some time. check video) 

**Video**
![Code_cBnW1Pym8g](https://github.com/Dart-Code/Dart-Code/assets/58988648/063e1b31-1fe0-4027-a9fa-a0c2a63291a1)

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.88.1
Flutter extension: 3.88.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: win 1.89.1

Workspace type: Flutter (LSP)

Dart (3.4.0): C:\flutter\bin\cache\dart-sdk
Flutter (3.22.0): C:\flutter (Chrome (web-javascript/web))

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`C:\flutter\bin\cache\dart-sdk\bin\dart.exe info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.4.0 (stable) (Mon May 6 07:59:58 2024 -0700) on "windows_x64"
- on windows / "Windows 10 Pro" 10.0 (Build 19045)
- locale is ru-RU

#### Project info

- sdk constraint: '>=3.0.5<4.0.0'
- dependencies: flutter
- dev_dependencies: dart_code_metrics, flutter_lints, flutter_test

#### Process info

| Memory | CPU | Elapsed time | Command line |
| -----: | --: | -----------: | ------------ |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`C:\flutter\bin\flutter.bat doctor -v`

```text
[√] Flutter (Channel stable, 3.22.0, on Microsoft Windows [Version 10.0.19045.4412], locale ru-RU)
    • Flutter version 3.22.0 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (10 days ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at G:\DB\soft_db\Android\Sdk\
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = G:\DB\soft_db\Android\Sdk\
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2023.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)

[√] VS Code (version 1.89.1)
    • VS Code at C:\Users\ooovid\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 125.0.6422.60
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 124.0.2478.80

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by DanTup** [comment]
@Coin-ai I haven't been able to reproduce this following your steps. Is it possible you could try to capture a log while reproducing the issue?

- Press `F1` to open the command palette
- Run the **Preferences: Open Workspace Settings (JSON)** command
- Add `"dart.analyzerInstrumentationLogFile": "logs/analyzer.txt",` to the JSON and press save
- Wait for the analyzer to restart
- Reproduce the issue
- Take a copy of the `logs/analyzer.txt` file and attach it here

Thanks!

**Comment by Coin-ai** [comment]
[analyzer.txt](https://github.com/Dart-Code/Dart-Code/files/15396753/analyzer.txt)
stay in console: main copy 4.dart, main copy 2.dart ...

**Comment by DanTup** [comment]
@Coin-ai when you captured this log, which error remained in the Problems list for `main copy 4`? Was it a compile error, or "The file name 'main copy 4.dart' isn't a lower_case_with_underscores identifier"?

In the log, I can only see that error, but no other - I'm trying to understand if that's the issue of there's something else going on?

It would be very useful if you could capture a video/GIF at the same time as the log file, so I can match the log file to what's seen on screen.

**Comment by DanTup** [comment]
Looking at the code, my theory is that when a file is removed, we directly flush the diagnostics on the server, but we don't go through `recordAnalysisErrors`, which means we don't call `notificationManager.recordAnalysisErrors` which means we don't clear the servers diagnostics from the `ResultCollector`. Thjis means if the plugin subsequently sends us errors, we may merge them with the last set of errors from the server and then send them to the client.

If this is the case, the server should be _recording_ an empty set of errors for the server instead of only flushing the errors on the client when a file is removed.

I'll try to repro in a test.

**Comment by DanTup** [comment]
I could reproduce this as described above. Working on a fix at https://dart-review.googlesource.com/c/sdk/+/367321.

**Comment by DanTup** [comment]
This is fixed by https://github.com/dart-lang/sdk/commit/f3be14c3b0108ff8b9d8366047225bd51912bf24. The change is in the Dart SDK so will ship in a future Dart/Flutter SDK release (not a Dart-Code extension release).

Thanks for the report and the log!
