### ISSUE TITLE
Macro not detected when importing from a package

### ISSUE THREAD

**Issue by felangel** [Dart-Code/Dart-Code#5114]
**Describe the bug**
When importing a macro package, VSCode does not detect the macro and/or show the augmentation (seems closely related to https://github.com/Dart-Code/Dart-Code/issues/5110)

**To Reproduce**

1. Create a new Dart project
1. Add `data_class_macro` to the pubspec.yaml
  `dart pub add data_class_macro`
1. Update `main.dart` to use the macro:
    ```dart
    import 'package:data_class_macro/data_class_macro.dart';
    
    @Data()
    class Person {
      final String name;
    }
    
    void main() {
      print(Person(name: 'Dash'));
    }
    ```

**Expected behavior**
I expect the jump to augmentation to be visible and for no analysis errors to appear.

The code runs fine though:

```
dart --enable-experiment=macros run lib/main.dart 
Person(name: Dash)
```

**Screenshots**
![Screenshot_2024-05-20_at_12 32 16_PM](https://github.com/Dart-Code/Dart-Code/assets/8855632/3b8c5460-1fde-4578-a7ff-3273828c4e7b)

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.88.1
Flutter extension: 3.88.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: mac 1.89.1

Workspace type: Flutter (LSP)

Dart (3.5.0-169.0.dev): flutter/flutter/bin/cache/dart-sdk
Flutter (undefined): flutter/flutter (macOS (darwin/macos))

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`flutter/flutter/bin/cache/dart-sdk/bin/dart info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.5.0-169.0.dev (dev) (Fri May 17 13:01:58 2024 -0700) on "macos_arm64"
- on macos / Version 14.0 (Build 23A344)
- locale is en-US

#### Project info

- sdk constraint: '>=3.5.0-169.0.dev <4.0.0'
- dependencies: data_class_macro, flutter
- dev_dependencies: flutter_test

#### Process info

|  Memory |  CPU | Elapsed time | Command line                                                                    |
| ------: | ---: | -----------: | ------------------------------------------------------------------------------- |
| 3142 MB | 0.0% |     01:23:12 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.88.1 |
| 1065 MB | 0.0% |        06:58 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.88.1 |
|   82 MB | 0.0% |     01:23:12 | dart tooling-daemon --machine                                                   |
|   82 MB | 0.0% |        06:58 | dart tooling-daemon --machine                                                   |
|  114 MB | 0.0% |        06:58 | flutter_tools.snapshot daemon                                                   |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`flutter/flutter/bin/flutter doctor -v`

```text
[✓] Flutter (Channel master, 3.22.0-36.0.pre.61, on macOS 14.0 23A344 darwin-arm64, locale en-US)
    • Flutter version 3.22.0-36.0.pre.61 on channel master at flutter/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 333c076e53 (19 minutes ago), 2024-05-20 10:17:55 -0700
    • Engine revision c6fecf65fb
    • Dart version 3.5.0 (build 3.5.0-169.0.dev)
    • DevTools version 2.36.0-dev.10

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/felix/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 125.0.6422.60

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by wolfenrain** [comment]
I have faced the same issues with my own macros, they work fine within an example directory but the moment I use them as a dependency in a different project (with the correct dart version and analyzer experiments enabled) it does not detect them

It however does correctly compile and run.

**Comment by DanTup** [comment]
There's an issue about this at https://github.com/dart-lang/sdk/issues/55670. I believe the issue is that the analyzer experiments are not applied from for packages outside of the analysis roots.
