### ISSUE TITLE
Can't install Flutter SDK - Stuck on "Checking for git"

### ISSUE THREAD

**Issue by Popanna** [Dart-Code/Dart-Code#5119]
Hello. I am trying to install Flutter, and have the most recent version of both Visual Studio and Git. I am stuck on the message "checking for git". It's my first time on VS. I am on Windows 11. Any help would be so very much appreciated. Thanks.

**Comment by aNOOBisTheGod** [comment]
I had the same issue. Checked the console, found this: 
![image](https://github.com/Dart-Code/Dart-Code/assets/69043738/8152bd26-a9f2-4900-8815-b5e6b2e1e9bc)
I assume that the first one is because flutter SDK is not installed and this error somehow was handled by VS Code so it asks if I want to download Flutter SDK
Figured out that VS code might try to install Flutter to your flash-drive somehow so I have ejected mine to successfully clone flutter. Hope this will help

**Comment by DanTup** [comment]
@aNOOBisTheGod did the text in that error not also show up in the bottom right corner as a toast notification? It should do, but VS Code might hide/collapse it into the bell icon after around 10s. The notification should have a button for "Download" that would try to perform the download via Git.

If you're not seeing that, I'd be interested in more info (a video of what you see would be ideal) so I can investigate what's going on. Thanks!

**Comment by aNOOBisTheGod** [comment]
> @aNOOBisTheGod did the text in that error not also show up in the bottom right corner as a toast notification? It should do, but VS Code might hide/collapse it into the bell icon after around 10s. The notification should have a button for "Download" that would try to perform the download via Git.
> 
> If you're not seeing that, I'd be interested in more info (a video of what you see would be ideal) so I can investigate what's going on. Thanks!

Actually, no, I can't see the second error in the bottom. Just "Checking for git" label

**Comment by DanTup** [comment]
@aNOOBisTheGod I just did some testing, and I think the notification is appearing.. we don't see to check for Git until after I click "Download SDK":

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/061db796-cf8f-496c-a613-c6d60b1b704f)

Is that the same behaviour you see? And then it gets stuck on "Checking for git"?

**Comment by DanTup** [comment]
I've committed a fix for this. The issue occurred when we couldn't find `git` (either through the VS Code Git extension, or on `PATH`). This type of error wasn't handled and we waited forever for the Git process (that never started) to end.

With the fix, the code will correctly continue and instead show a message:

> Unable to clone Flutter because Git was not found. Please clone or download the Flutter SDK manually.

With a **Setup Instructions** button that links to https://flutter.dev/setup/. You can either follow the instructions there, or you could ensure you have Git installed and on your `PATH` variable (you may need to reboot after adding it) and then try again through VS Code.

Please let me know if those don't work. The fix will ship in the next version of the VS Code extension.

Thanks!
