### ISSUE TITLE
Automatically open completion when typing import statements

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#512]
Splitting this from #320. The request is to have completion automatically open when typing an import:

```dart
import '
```

Currently you have to manually invoke it (and several users have expressed that they didn't know the shotrcut to do that, and were mainly relying on auto triggering).

**Comment by DanTup** [comment]
(fyi @pulyaevskiy)

We register "trigger characters" with the completion provider, which are characters that cause the completion to open automatically, for example see 9c408b72090168363caaa047e72d256ab12da692 where we added `$` and `{`.

In this instance, you'd want to add the apostrophe `'` and double quote `"` to get the behaviour you want (start completing after you've typed `import '`. However, this would then cause it to pop open on all instances of those (for example also when you typed the closing quote at the end of the import) which would be unwanted.

To fix that, we need to know if the user is actually in an import statement. We could possibly get that from some AST-like data, but it just occurred to me that we could look back at the characters before the completion was invoked (which is how we fixed it for `{` as seen in 95cc828c42e32232577035a20bafcd74df343110 in `shouldAllowCompletion`).

So, maybe a fix is:

- Add `"` and `'` to trigger characters
- Update `shouldAllowCompletion` to return false when the trigger character is `"` or `'` and the trigger kind is `TriggerCharacter` and the preceding text is not `import `.

It wouldn't be foolproof (eg. if you typed `import "` inside a string it'd still fire) but I think it'd be reasonable enough.

**Comment by DanTup** [comment]
Seems that [MS are basically doing the same](https://twitter.com/mattbierner/status/957729115129262080) for TypeScript:

> See https://github.com/Microsoft/vscode/blob/8ebbc4c255b4199f511ad54a66850558d3afa36a/extensions/typescript/src/features/completionItemProvider.ts#L254. Typescript uses " as a trigger char but then checks to make sure we only really trigger for " in import statements

So I'm gonna refactor `shouldAllowCompletion` slightly to make it easier to add more exceptions like this :)

**Comment by pulyaevskiy** [comment]
Nice! Thanks a lot, you already did all the research. :-)

**Comment by DanTup** [comment]
Reopening so we can handle the snippet case.

**Comment by DanTup** [comment]
@pulyaevskiy Gave this a quick test and it works really well! Thanks for both bringing it up and the implementation :-)

I want to clean up a bunch of little things in the 2.8 milestone this weekend/next week, so likely this'll go out sometime next week.

**Comment by pulyaevskiy** [comment]
Nice! No rush, `^Space` helps out a bit. :) It was a nice exercise for me too, thanks to your hints. Also debugging extensions in VSCode is really easy.
