### ISSUE TITLE
have searched on the goolge but can't find niof fix about Launch.json. I put "program": "lib/main.dart" but it still doesn't work. I would like to be able to help you how to fix "Your launch config refers to a program that does not exist. If you have problems launching, check the "program" field in your ".vscode/launch.json" file ."

### ISSUE THREAD

**Issue by Herbert88Hinsbeeck** [Dart-Code/Dart-Code#5120]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

 - Operating System and version:
 - VS Code version:
 - Dart extension version:
 - Dart/Flutter SDK version:
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
Can you provide a screenshot of VS Code with:

- your `.vscode/launch.json` file open
- the Explorer sidebar visible, with the `lib` folder expanded

The `program` in `launch.json` needs to be a path to the script to run when you start debugging. So if you have `lib/main.dart` then the folder you have open in VS Code needs to have a `lib/main.dart` file. If your project is nested inside a folder called `my_app`, then `launch.json` would also need to have `"cwd": "my_app"` to set the working directory to the right folder.

In many cases you don't need a `launch.json` at all - however it's hard to advise without some more information about the project/folder/workspace structure.

**Comment by Herbert88Hinsbeeck** [comment]
There are still not work.
