### ISSUE TITLE
Error: Dart library 'dart:ui' is not available on this platform

### ISSUE THREAD

**Issue by naidu199** [Dart-Code/Dart-Code#5122]
I encountered an error when trying to run my Flutter application. The error message indicates that the Dart library 'dart:ui' is not available on this platform.

### Error Message
```
Error: Dart library 'dart:ui' is not available on this platform.
import 'dart:ui' as ui show Canvas, Paint, Path, lerpDouble;
       ^
Context: The unavailable library 'dart:ui' is imported through these packages:

    package:my_app => package:flutter => dart:ui
    ...
import 'dart:ui' show lerpDouble;
```
### Flutter Doctor Report
  
![flutter  doctor](https://github.com/Dart-Code/Dart-Code/assets/141550407/1f58c8cb-7bac-43a3-b259-461c2762ed6a)
- version:
 - Dart extension version: 3.4.1
 - Dart/Flutter SDK version: 3.22.1

**Comment by DanTup** [comment]
> I encountered an error when trying to run my Flutter application.

Can you describe how you're trying to run your application (what button/menu/keyboard shortcut are you pressing), and a full screenshot of VS Code when you see this error?

Some common causes of this error are:

- Flutter is not listed in the `pubspec.yaml`
- Using another extension like Code Runner to try and run Flutter applications (see https://github.com/formulahendry/vscode-code-runner/issues/674)
Thanks!

**Comment by naidu199** [comment]
I'm running my application with command flutter run

**Comment by DanTup** [comment]
@naidu199 can you provide a screenshot?

This repository is for the VS Code extension so if you're running from the terminal it might not be something I can help with here, however if you provide a screenshot it might help me better understand where this could be coming from. Thanks!

**Comment by zangkai233** [comment]
I have a same question
<img width="1352" alt="Screenshot 2024-06-12 at 11 08 51 AM" src="https://github.com/Dart-Code/Dart-Code/assets/172519103/80d641f9-f736-41e7-8052-8f2b73c149c2">

**Comment by DanTup** [comment]
@zangkai233 how are you trying to run the application? What button are you clicking/key are you pressing/command are you running?

**Comment by zangkai233** [comment]
@DanTup On the right top, I'm a high school student and this is my first time to download vs code and flutter
![Image 2024-06-12 at 11 11 AM](https://github.com/Dart-Code/Dart-Code/assets/172519103/fc7eecad-a7ba-4c50-a1d8-35d490271801)

**Comment by DanTup** [comment]
@zangkai233 do you have the "Code Runner" extension installed? If so, I think you are clicking its button, and it does not work with Flutter. If you click the little dropdown arrow next to it, you should see a Run and a Debug button contributed by the Dart extension.

I filed an issue with Code Runner to hide their button for Dart, but unfortunately there hasn't been a response -> https://github.com/formulahendry/vscode-code-runner/issues/674

**Comment by naidu199** [comment]
> ![Image 2024-06-12 at 5 14 PM](https://github.com/Dart-Code/Dart-Code/assets/172519103/00aa4647-26bb-4d79-95a3-7897e438fd7a)
> 

I think you can clear your pub 

Do 
- flutter pub clean 
- flutter pub get 
I think it will work out

**Comment by DanTup** [comment]
@zangkai233 assuming you haven't customised the `ios` folder, I would try deleting the `ios` folder from the project and then running `flutter create --platforms=ios .` to regenerate the native iOS parts.

If that doesn't work, it would be best to file an issue at https://github.com/flutter/flutter/ since it's a different issue to here (and seems unrelated to the VS Code extension). Thanks!
