### ISSUE TITLE
Dart extension doesn't start analyzer

### ISSUE THREAD

**Issue by FMorschel** [Dart-Code/Dart-Code#5125]
### EDIT

When updating my Dart extension for vsCode my analyzer just would not start from the IDE.

This is after more than 5 minutes of restarting extensions.
![image](https://github.com/Dart-Code/Dart-Code/assets/52160996/fc208fb3-b5fd-4440-9683-93efa85934c2)

This Flutter project was running the analyzer just fine when in the previous version of the extension and when reinstalling it, it does work again.

<details>

<summary> Old description </summary>

**Describe the bug**
After updating to vscode Dart extension v3.90.0, my project analyzer just stopped. Not even capitalized words were painted differently. Going back to v3.80.0 returned things to normal. 

**To Reproduce**
I had a Flutter project opened and v3.80.0 installed, just updated it.

**Expected behavior**
That the analyzer started normally and the "Dart: Restart Analysis Server" command returned (or at least some explanation).

**Screenshots**

This is after more than 5 minutes of restarting extensions.
![image](https://github.com/Dart-Code/Dart-Code/assets/52160996/fc208fb3-b5fd-4440-9683-93efa85934c2)

![image](https://github.com/Dart-Code/Dart-Code/assets/52160996/1b9cbb12-32a5-4d0f-b4a6-2362794ed732)

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

 - Operating System and version: Windows 11 - 23H2
 - VS Code version: 1.89.1
 - Dart extension version: v3.90.0
 - Dart/Flutter SDK version: 
   - Dart: 3.3.4
   - Flutter: 3.3.4

![image](https://github.com/Dart-Code/Dart-Code/assets/52160996/578123e5-5c47-4f9b-863f-9f7f8be4165e)

</details>

**Comment by FMorschel** [comment]
The solution was pointed out to me by @DanTup at https://discord.gg/xSTPEqm, help chat.

When opening "Toggle Developer Tools" this was my output:

<details>

<summary> Open to see the photo </summary>

![image](https://github.com/Dart-Code/Dart-Code/assets/52160996/31dba2c1-4b26-44fc-99e1-2b5f8321e40f)

</details>

As suggested by DanTup, I tried to open the vscode file mentioned inside `.vscode/extensions/dart-code.dart-code-3.90.0` (the extension folder) and it was corrupted.

## Solution

Deleting the extension folder for the corrupted version download and reinstalling it.

**Comment by DanTup** [comment]
Thanks for posting the fix instructions here! The issue is likely a VS Code bug - it comes up now and then, but the extension has no involvement in its own install process, so something is likely going wrong as VS Code extracts the extension. There are a couple of open issues in the VS Code issue tracker about extension installation fails, so I suspect it's known about.
