### ISSUE TITLE
Add an option to auto open DevTools in browser on start debugging

### ISSUE THREAD

**Issue by nullskill** [Dart-Code/Dart-Code#5131]
It would be of great convenience to have an option of auto opening `DevTools` in browser
 on start debugging.
I.e. in `VS Code` there are settings:
- `"dart.openDevTools"` with valid values: `"never"`, `"flutter"`, `"always"`.
- `"dart.devToolsBrowser"`  with valid values: `"chrome"`, `"default"`.

But DevTools always open only inside `VS Code` even if settings set like this:
  `"dart.openDevTools"`: `"always"`,
  `"dart.devToolsBrowser"`: `"chrome"`,
  
I assume that the logic of these options independant from each other and `"dart.openDevTools": "always"` means "**always in IDE**" while `"dart.devToolsBrowser": "chrome"` means "**open in chrome when 'Open DevTools in Web Browser' choosed**". Though it's a bit confusing but nevertheless the semantics of these it would be convenient to give developers the opportunity to open `DevTools` in browser on start debugging. Why do I think so? Because `DevTools` occupy only a part of the IDE window by default and it's ok if you mostly use it to inspect some widgets from time to time. But if most of the time you inspect widgets, network calls, performance, logging, providers and what not it is not fairly enough to have such a small space of the window. Yes, I know there's a possibility to move `DevTools` tabs into new window in `VS Code` but it's an unnecessary extra motion,  plus it is still not perfect if we compare it with the fullscreen tab in browser with all the `DevTools` tabs open at hand. Yes, I am aware there's another possibility to open `DevTools` in browser by hand using command after debugging has started but still this is not what I prefer to do every time I run my app in debug mode.

**Comment by DanTup** [comment]
The setting to control whether DevTools opens embedded or externally is `dart.devToolsLocation`. You can set it to `"external"` for individual DevTools tools, or as "default" for them all.

For example, if you add this to your settings:

```js
"dart.openDevTools": "flutter",
"dart.devToolsLocation": {
	"default": "external"
},
```

It will result in DevTools automatically opening in the browser for any launched Flutter debug sessions. Note: We can't automatically close external browser windows though, so the recently-added `dart.closeDevTools` setting will not work for external windows.

Please let me know if this isn't working for you. Thanks!
