### ISSUE TITLE
Clean install on windows 11 using Visual Studio fails

### ISSUE THREAD

**Issue by thaigertech** [Dart-Code/Dart-Code#5136]
**Describe the bug**
After installing the Flutter extension any New app or Flutter doctor from Cntrl Shift P will go in an endless loop
**To Reproduce**
1. Go to Ctrl Shift P. Flutter Doctor
[flutter] flutter doctor -v
Building flutter tool... 
Running pub upgrade... 
Resolving dependencies...
Downloading packages...
Got dependencies.
../../Pub/Cache/hosted/pub.dev/webdriver-3.0.3/lib/src/async/target_locator.dart:21:9: Error: Type 'WebDriver' not found.
  final WebDriver _driver;
        ^^^^^^^^^
../../Pub/Cache/hosted/pub.dev/webdriver-3.0.3/lib/src/async/target_locator.dart:62:23: Error: Type 'Window' not found.
  Future<void> window(Window window) => window.setAsActive();
                      ^^^^^^
../../Pub/Cache/hosted/pub.dev/webdriver-3.0.3/lib/src/async/target_locator.dart:68:3: Error: Type 'Alert' not found.
  Alert get alert => Alert(_client, _handler);
  ^^^^^
../../Pub/Cache/hosted/pub.dev/webdriver-3.0.3/lib/src/common/webdriver_handler.dart:214:45: Error: Type 'By' not found.
  WebDriverRequest buildFindElementsRequest(By by, [String? contextId]);
                                            ^^
../../Pub/Cache/hosted/pub.dev/webdriver-3.0.3/lib/src/common/webdriver_handler.dart:220:44: Error: Type 'By' not found.
  WebDriverRequest buildFindElementRequest(By by, [String? contextId]);
                                           ^^
../../Pub/Cache/hosted/pub.dev/webdriver-3.0.3/lib/src/common/webdriver_handler.dart:255:8: Error: Type 'MouseButton' not found.
      [MouseButton button = MouseButton.primary]);
       ^^^^^^^^^^^
../../Pub/Cache/hosted/pub.dev/webdriver-3.0.3/lib/src/common/webdriver_handler.dart:261:38: Error: Type 'MouseButton' not found.
  WebDriverRequest buildDownRequest([MouseButton button = MouseButton.primary]);
                                     ^^^^^^^^^^^
../../Pub/Cache/hosted/pub.dev/webdriver-3.0.3/lib/src/common/webdriver_handler.dart:267:36: Error: Type 'MouseButton' not found.
  WebDriverRequest buildUpRequest([MouseButton button = MouseButton.primary]);
                                   ^^^^^^^^^^^
../../Pub/Cache/hosted/pub.dev/webdriver-3.0.3/lib/src/common/webdriver_handler.dart:450:42: Error: Type 'Cookie' not found.
  WebDriverRequest buildAddCookieRequest(Cookie cookie);
                                         ^^^^^^
../../Pub/Cache/hosted/pub.dev/webdriver-3.0.3/lib/src/common/webdriver_handler.dart:473:3: Error: Type 'Cookie' not found.
  Cookie parseGetCookieResponse(WebDriverResponse response, String name);
  ^^^^^^
Error: Unable to create dart snapshot for flutter tool. 
Building flutter tool... 
Running pub upgrade... 
Resolving dependencies...
Downloading packages...
Got dependencies.
-- for shortness I only copied a single loop. It has been an hour and well over 300 repeats.
**Expected behavior**
It would be so lovely if Flutter just allows a seasoned programmer who is entirely new on Flutter to actually get to start.
I thought Flutter and Dart were a serious replacement for my native android and Rust skills. It appears not

**Comment by DanTup** [comment]
Can you confirm how you installed Flutter? I suspect this isn't a VS Code issue (and you'd see the same running `flutter doctor` from the terminal), but it seems like either something may be wrong with your Flutter install (or there have been breaking changes in a Pub package that weren't versioned correctly).

Can you also try running `git status` from within your Flutter SDK folder (the root folder) and post the output here? Thanks!
