### ISSUE TITLE
[Feature request] Make multi-line string literals foldable

### ISSUE THREAD

**Issue by andrewkolos** [Dart-Code/Dart-Code#5139]
Consider a multi-line string in a .dart file:

```dart
final bigString = '''
I am a multiline string.
I might be really long.
For example, I could be an entire Android manifest (the XML you would find in an AndroidManifest.xml file)
that's defined in a test file.
'''
```

It would be nice if I could fold this. This is something I can do with multi-line string literals in JS/TS:

![image](https://github.com/Dart-Code/Dart-Code/assets/9027551/3ea86868-820f-4173-ab51-e6a354aa08c7)

![image](https://github.com/Dart-Code/Dart-Code/assets/9027551/96943237-f886-4a75-b7ec-7f1fbaa0037d)

**Describe alternatives you've considered**
The user can manually create folding regions using the "Create Folding Range from Selection", but it's generally not worth the time to do this.

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/4f36252fd3f647fd93f07067b73dadcea6319d70. The fix is in the Dart analysis server so will show up in a future SDK release (not Dart-Code release).

**Comment by andrewkolos** [comment]
Thank you for your continued work on folding!
