### ISSUE TITLE
Document testing & release procedure

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#514]
The procedure for testing a release and deploying it to the VS Marketplace needs to be documented. Access to the GH org and VS Publishers should also be granted to some others (@devoncarew & @mit-mit?) to allow for releases in my absence and to reduce bus factor.

**Comment by mit-mit** [comment]
Starting with access for Devon and myself SGTM

**Comment by DanTup** [comment]
@devoncarew @mit-mit I've added some notes about testing/releasing to the [CONTRIBUTING](https://github.com/Dart-Code/Dart-Code/blob/master/CONTRIBUTING.md#release-procedure) file. Please proof-read and we can walk through them in a future release from one of your machines to ensure they're good.

Ideally there would be more automated testing and less manual, hopefully we'll get there in time. I haven't gone into great detail with manual testing (just basics) because there isn't a great plan; often the releases are fairly small so it's easier to just focus in the areas around the changes.

**Comment by devoncarew** [comment]
👍 looks great!
