### ISSUE TITLE
When writing Flutter code in VSCode, there is no automatic indentation when breaking lines within the brackets {}

### ISSUE THREAD

**Issue by 826327700** [Dart-Code/Dart-Code#5141]
### Steps to reproduce

vscode v1.90.0
dart extension v3.90.0
flutter extension v3.90.0

### Actual results

flutter:

https://github.com/flutter/flutter/assets/23014381/b11e6667-dd67-4f9e-88ea-a352db93b0d4

javascript:

https://github.com/flutter/flutter/assets/23014381/2e2e55c3-6797-484d-ab38-2a664d10cb7f

This is really frustrating and significantly affects my coding efficiency. Can anyone tell me how to solve this problem?

### Flutter Doctor output

flutter doctor -v
[✓] Flutter (Channel beta, 3.23.0-0.1.pre, on macOS 14.4.1 23E224 darwin-arm64,
    locale zh-Hans-CN)
    • Flutter version 3.23.0-0.1.pre on channel beta at /Users/xiaobaozi/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • FLUTTER_GIT_URL = https://github.com/flutter/flutter.git
    • Framework revision 2feea7a407 (7 days ago), 2024-06-06 10:19:10 +0700
    • Engine revision bb10c54666
    • Dart version 3.5.0 (build 3.5.0-180.3.beta)
    • DevTools version 2.36.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✗] Android toolchain - develop for Android devices
    ✗ ANDROID_HOME = /Users/xiaobaozi/Library/Android/sdk
      but Android SDK not found at this location.

[!] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    ! CocoaPods 1.12.1 out of date (1.13.0 is recommended).
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To update CocoaPods, see
      https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] VS Code (version 1.90.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (4 available)            
    • iPhone 15 Pro (mobile)          • 95377193-8FAB-4A6D-8C21-59346014C776 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   •
      macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         •
      macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript •
      Google Chrome 125.0.6422.144
    ! Error: Browsing on the local area network for 小包子的iPhone. Ensure the device is unlocked
      and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.

**Comment by DanTup** [comment]
I don't seem to be able to reproduce this, it works as you'd like:

https://github.com/Dart-Code/Dart-Code/assets/1078012/8327a412-621f-438f-a7e5-5bc753196950

Can you confirm what have this setting set to?

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/93701694-bda7-4b7a-b5cb-1377296b171e)

If it says "Also modified elsewhere", please hover over that text and take a screenshot of that too:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/d0850cd9-564d-4c3a-a40a-b07c20a9871e)

**Comment by 826327700** [comment]
> 我似乎无法重现这一点，但它的工作方式正如你所希望的那样：
> 
>  缩进.mp4 
> 您能确认这个设置是什么吗？
> 
> ![图像](https://private-user-images.githubusercontent.com/1078012/339304608-93701694-bda7-4b7a-b5cb-1377296b171e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzE1NDMsIm5iZiI6MTcxODI3MTI0MywicGF0aCI6Ii8xMDc4MDEyLzMzOTMwNDYwOC05MzcwMTY5NC1iZGE3LTRiN2EtYjVjYi0xMzc3Mjk2YjE3MWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTNUMDkzNDAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2Y0NWNhYjc2YTZhYTRhYjdkMmI1YTE2ZTI0YjZlYjI5NjE5OWRmYTJhZTY1NzIzYjc2NDUxODEzMjBjMTFkMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2ntniltAIpZw7qbj9sb1zkexqgndihq-00PHtsswdSA)
> 
> 如果显示“也在其他地方修改”，请将鼠标悬停在该文本上并截取屏幕截图：
> 
> ![图像](https://private-user-images.githubusercontent.com/1078012/339304814-d0850cd9-564d-4c3a-a40a-b07c20a9871e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzE1NDMsIm5iZiI6MTcxODI3MTI0MywicGF0aCI6Ii8xMDc4MDEyLzMzOTMwNDgxNC1kMDg1MGNkOS01NjRkLTRjM2EtYTQwYS1iMDdjMjBhOTg3MWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTNUMDkzNDAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmIzOGE3OGJhYzRiNDM5NTY5MmY4NTE4YmRjNGM5ODUxZjU5YTg1N2NiZDhjMjRjMDRjMDFkNjljNTI3NTAwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0vl1EoTfe2SwiRfd4ZKse7zg2sddIdL1pAzLOWsW0T4)

This is my setting:
![image](https://github.com/Dart-Code/Dart-Code/assets/23014381/e6d420f8-d9c6-48fb-87d2-ffe3084e7ad8)

**Comment by DanTup** [comment]
Strange, I'm not sure what's different between our machines that's causing this.

I found another issue that looks like someone reporting the same problem:

https://github.com/microsoft/vscode/issues/165153

I will try commenting on there to see if someone on the VS Code team may have ideas of what might impact this.

**Comment by 826327700** [comment]
I found the solution to the problem，in vscode setting.json:
// "editor.language.brackets": [],--->delete this row

**Comment by DanTup** [comment]
Ah, that makes sense - the behaviour is based on VS Code knowing that these are brackets. Do you know why you might have changed that setting? Maybe there's another way to achieve what you wanted without doing that.
