### ISSUE TITLE
Add custom web server response headers when debugging a Flutter web app on VS code

### ISSUE THREAD

**Issue by andynewman10** [Dart-Code/Dart-Code#5143]
**Describe the solution you'd like**

I have a Flutter web application that uses the [SharedArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer) object. I am using Chrome to debug my application.

SharedArrayBuffer requires specific web response headers, as specified in the link above.

Because I am using the built-in VS code web server for debugging my Flutter web application, I have (to my knowledge) no control over the response headers that are sent by the web server.

I would like to be able to tell the web server to add response headers when issuing .js resources.

**Describe alternatives you've considered**

No alternative that I know of.

**Comment by DanTup** [comment]
> Because I am using the built-in VS code web server for debugging my Flutter web application, 

The web server here isn't from VS Code, but from `flutter run` (ultimately the debug adapter is running `flutter run -d chrome` with some additional flags for debugging).

So the question here is whether you can set this headers when using `flutter run`. If you can, then you can add the same arguments to your a `.vscode/launch.json` to have them passed through when we start debugging. If there is not an existing way, then this would first need to be filed as a feature request (if there isn't already one) at https://github.com/flutter/flutter.

**Comment by andynewman10** [comment]
Thank you. Sorry, I am often mistaken between flutter and dart-code.

I could get it to work by using `--enable-features=SharedArrayBuffer` in launch.json, as suggested in the starred paragraph at the bottom of [this](https://web.dev/articles/cross-origin-isolation-guide#enable_cross-origin_isolation) documentation section.

**Comment by DanTup** [comment]
No problem, glad to hear there was already an option and it was just a simple tweak!

**Comment by andynewman10** [comment]
Special care needs to be taken when declaring the option in launch.json:
```
"args": [
                "--web-browser-flag --enable-features=SharedArrayBuffer"
            ]
```
Have a good day!
