### ISSUE TITLE
Dart/Flutter processes left orphaned after IDE was closed 

### ISSUE THREAD

**Issue by FMorschel** [Dart-Code/Dart-Code#5155]
**Describe the bug**
Dart daemon was left hanging when IDE was closed.

**To Reproduce**
1. In the terminal, I ran `flutter build appbundle`.
2. While it was loading, I started a debug session of my Flutter app.
3. Building completed from the terminal.
4. After waiting longer than usual, "Running gradle assemble debug" message would not leave and at the debug console it got stuck with "Launching lib\main.dart on PHONE in debug mode..." even when the app on my phone had already started and I was able to use it completely fine.
5. I tried to terminate the debug session with multiple clicks to the stop button, no use because of some bug.
6. Closed the IDE instead.
7. Opened Task Manager and saw that `dart.exe daemon` was still running.

**Expected behavior**
No `dart.exe` left running.

**Please complete the following information:**

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.90.0
Flutter extension: 3.91.20240529 (activated)

App: Visual Studio Code
App Host: desktop
Version: win 1.90.2

Workspace type: Flutter (LSP)

Dart (3.4.3): C:\Users\user\.puro\shared\caches\edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4\dart-sdk
Flutter (3.22.2): C:\Users\user\.puro\envs\stable\flutter (SM G780F (android-arm64/android))

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`C:\Users\user\.puro\shared\caches\edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4\dart-sdk\bin\dart.exe info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.4.3 (stable) (Tue Jun 4 19:51:39 2024 +0000) on "windows_x64"
- on windows / "Windows 10 Pro" 10.0 (Build 22631)
- locale is pt-BR

#### Process info

| Memory | CPU | Elapsed time | Command line |
| -----: | --: | -----------: | ------------ |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`C:\Users\user\.puro\envs\stable\flutter\bin\flutter.bat doctor -v`

```text
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22631.3737], locale pt-BR)
    • Flutter version 3.22.2 on channel stable at C:\Users\user\.puro\envs\stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (3 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Users\user\AppData\Local\Programs\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33403.182
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2024.1)
    • Android Studio at C:\Users\user\AppData\Local\Programs\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)

[√] VS Code (version 1.90.2)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.86.0

[√] VS Code (version 1.88.0-insider)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders
    • Flutter extension version 3.64.0

[√] Connected device (4 available)
    • SM G780F (mobile) • 192.168.200.50:45967 • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows              • windows-x64    • Microsoft Windows [Version 10.0.22631.3737]
    • Chrome (web)      • chrome               • web-javascript • Google Chrome 126.0.6478.115
    • Edge (web)        • edge                 • web-javascript • Microsoft Edge 125.0.2535.85
    ! Device 192.168.200.50:37835 is offline.

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Aditional info**

Not completely sure, but I've seen a similar behaviour with a `dart.exe` (not sure it was the daemon) left hanging after the IDE got closed. Most of the time I saw this when opening two different Dart projects in two different instances of VSCode.

I was advised in Discord to enable the log for the daemon (and others) in VSCode. Will do and update this issue if that happens again. 

Maybe it has something to do with concurrent analysers or something along these lines?

**Comment by DanTup** [comment]
In some quick testing, I wasn't able to reproduce this. I tried various combinations of terminating VS Code with and without debug sessions running.

I'm going to review all of the dispose paths for this though to ensure we're not disposing anything in an async loop where one process shutting down slowly might delay another (because there's probably a limit to how long VS Code will wait for us to shut things down before just terminating the extension host).

**Comment by DanTup** [comment]
> I'm going to review all of the dispose paths for this though to ensure we're not disposing anything in an async loop

We're not - it looks like there is a clear sync path (and all other disposables have try/catch around them) to ensure the tooling daemon is terminated when VS Code disposes the `vscode.ExtensionContext`.

I wonder if maybe the extension host crashed or became unresponsive (which might also explain why the Stop button on the debug toolbar stopped working). It might be difficult to track this down without a good way to repro.

**Comment by FMorschel** [comment]
One thing I can think of that is different is me using `puro` as we discussed. I know that the project has been set to use stable and my flutter keyword in path is set to be the same but maybe something is going on between calling it with `puro flutter` and only `flutter`? I'll take a look as soon as possible and let you know what I find here.

**Comment by FMorschel** [comment]
Still haven't tested anything related to the above comment but it did happen again with lots of log files now, just this time the same daemon was left hanging with the two instances opened.

One of them was already in debug, the other was simply opened to edit some files (but no debug session or anything). Once the first instance was down and needed to restart the debug session and connection to the device, the same behaviour happened as described above from point 4 forward.

<details>

<summary> Here are the logs </summary>

- [analyzer.txt](https://github.com/user-attachments/files/16007725/analyzer.txt)
- [daemon.txt](https://github.com/user-attachments/files/16007726/daemon.txt)
- [dap.txt](https://github.com/user-attachments/files/16007727/dap.txt)
- [flutter_daemon.txt](https://github.com/user-attachments/files/16007729/flutter_daemon.txt)
- [InstrumentationLog.txt](https://github.com/user-attachments/files/16007731/InstrumentationLog.txt)
- [InstrumentationLog.txt.1](https://github.com/user-attachments/files/16007736/InstrumentationLog1.txt)
- [InstrumentationLog.txt.2](https://quickshare.samsungcloud.com/9GCsFoUkPEEX) (had to sent via quick share because the file size exceeded 25MB)
- [InstrumentationLog.txt.3](https://quickshare.samsungcloud.com/nXxcqUY8qpWI) (had to sent via quick share because the file size exceeded 25MB)
- [InstrumentationLog.txt.4](https://github.com/user-attachments/files/16007737/InstrumentationLog4.txt)

</details>

**Comment by DanTup** [comment]
@FMorschel thanks - unfortunately there's nothing that helpful in the daemon log. Could you try enabling the [general extension log](https://dartcode.org/docs/logging/#extension) (`dart.extensionLogFile`)?

Btw, some of the files you attached above are from the analyzer and may includes parts of code from your open files - if there might be anything sensitive in them you should delete them (if GH won't let you remove them, I believe I can delete the comment).

**Comment by FMorschel** [comment]
Alright. Happened again. Two instances opened, only one running.

Now three hanging daemons and one `dart run` that was stopped. After closing all VSCodes, and waiting a bit, the `dart run` instance vanished by itself. 

Also, one of the hanging daemons was using like 30% of the CPU.

<details>

<summary> Here are the new logs (all from another project) </summary>

- [daemon.txt](https://github.com/user-attachments/files/16014854/daemon.txt)
- [dap.txt](https://github.com/user-attachments/files/16014857/dap.txt)
- [extension.txt](https://github.com/user-attachments/files/16014861/extension.txt) (new)
- [flutter_daemon.txt](https://github.com/user-attachments/files/16014862/flutter_daemon.txt)
- [InstrumentationLog.txt](https://github.com/user-attachments/files/16014864/InstrumentationLog.txt)
- [InstrumentationLog.txt.1](https://github.com/user-attachments/files/16014869/InstrumentationLog1.txt)
- [InstrumentationLog.txt.3](https://github.com/user-attachments/files/16014871/InstrumentationLog3.txt)
- [InstrumentationLog.txt.4](https://github.com/user-attachments/files/16014873/InstrumentationLog4.txt)
- [InstrumentationLog.txt.5](https://github.com/user-attachments/files/16014875/InstrumentationLog5.txt)

</details>

**Comment by DanTup** [comment]
Thanks - unfortunately there's nothing useful there. I've pushed a new pre-release of the Dart extension (v3.93.20240703) which has some additional logging when services are shutting down. It would be useful to see the tooling daemon log with this change, to see whether we're actually trying to shut the process down.

I don't _think_ Puro is the issue here, but it would be useful to know what the target of the symlink at `C:\Users\felip_0vh5fa6\.puro\shared\caches\edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4\dart-sdk\bin\dart.exe` is.

Thanks!

**Comment by FMorschel** [comment]
The full cli for the dart.exe that hangs (there is no easy way to copy the cli so maybe something is written wrong, but I did try my best):

```
C:\Users\felip_0vh5fa6\.puro\envs\stable\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev --packages=C:\Users\felip_0vh5fa6\.puro\envs\stable\flutter\packages\flutter_tools\.dart_tool\package_config.json C:\Users\felip_0vh5fa6\.puro\shared\flutter_tools\761747bfc538b5af34aa0d3fac380f1bc331ec49\flutter_tools.snapshot daemon
```

Your question above: _stable_/_default_.

See this log file I made with `dir /AL /S . > log.txt` at `C:\Users\felip_0vh5fa6\.puro\envs`: [log.txt](https://github.com/user-attachments/files/16109087/log.txt)

Logs:
- [analyzer.txt](https://quickshare.samsungcloud.com/y24Kcr0Y7xUe)
- [daemon.txt](https://github.com/user-attachments/files/16109127/daemon.txt)
- [dap.txt](https://github.com/user-attachments/files/16109130/dap.txt)
- [extension.txt](https://github.com/user-attachments/files/16109125/extension.txt)
- [flutter_daemon.txt](https://github.com/user-attachments/files/16109134/flutter_daemon.txt)
- [InstrumentationLog.txt](https://quickshare.samsungcloud.com/gdZo5tl8vLll)
- [InstrumentationLog1.txt](https://quickshare.samsungcloud.com/7d1WNIkc6NIl)
- [InstrumentationLog2.txt](https://github.com/user-attachments/files/16109144/InstrumentationLog2.txt)
- [InstrumentationLog3.txt](https://quickshare.samsungcloud.com/kBcoIVMo2nwH)
- [InstrumentationLog4.txt](https://github.com/user-attachments/files/16109146/InstrumentationLog4.txt)
- [InstrumentationLog5.txt](https://github.com/user-attachments/files/16109147/InstrumentationLog5.txt)

**Comment by DanTup** [comment]
> ```dart.exe [...]flutter_tools.snapshot daemon`

Ah, turns out this is the Flutted device daemon, not the Dart Tooling Daemon. I'd been looking in the wrong log :)

So the log above for flutter_daemon includes this:

```
[08:17:05] [FlutterDaemon] [Info] ==> [{"id":"10","method":"daemon.shutdown"}]
[08:17:05] [FlutterDaemon] [Info] Process C:\Users\felip_0vh5fa6\.puro\envs\stable\flutter\bin\flutter.bat is being disposed
[08:17:05] [FlutterDaemon] [Info] Process C:\Users\felip_0vh5fa6\.puro\envs\stable\flutter\bin\flutter.bat is terminating process 165568
[08:17:05] [FlutterDaemon] [Info] Process C:\Users\felip_0vh5fa6\.puro\envs\stable\flutter\bin\flutter.bat is terminating the main process
[08:17:05] [FlutterDaemon] [Info] Process C:\Users\felip_0vh5fa6\.puro\envs\stable\flutter\bin\flutter.bat terminated! null, SIGTERM
```

"terminating process 165568" looks like it's sending a signal to terminate the main daemon process (we terminate this directly because terminating just the `.bat` wrapper might not terminate the real executable running inside it).

This makes me wonder if a) the terminate did not work, or b) this log file did not match the process that was hanging around (for example it was from a previous VS Code session).

Is it possible you can try to reproduce with just a single instance of VS Code, and then verify the PID of the process that is left running versus the one that shows up in flutter_daemon log?

Thanks!

**Comment by DanTup** [comment]
hmm, in the flutter_daemon.txt you sent it has:

```
[10:36:13] [FlutterDaemon] [Info] <== [{"event":"daemon.connected","params":{"version":"0.6.1","pid":118136}}]
```

This is the PID you mention was left running. The end of the log file does not contain anything suggesting we attempted to terminate the process, the last line is:

```
[13:14:55] [FlutterDaemon] [Info] <== [{"id":"12","result":{"platforms":["web","android","ios","linux","macos","windows"],"platformTypes": /// ...
```

So it seems like either VS Code didn't ask us to shut down (did not call our `deactivate`), or it did and we for some reason did not get that signal to the other services.

I'm going to add some more logging in the extensions `deactivate` which should confirm which is the case.

**Comment by FMorschel** [comment]
Just another info. This time, only one VSCode with (obviously) a Flutter project opened. 

What happened was that my app on my Android device was running before it even showed on my debug console that it was installing. 

After that happened, I terminated the running process and closed the app (in this order). 

Tryied to run again, same error, tried to terminate the debug session but was unable to do it, even after I'd closed the app on my phone.

Closed vsCode and got the PIDs and logs for you.

**Comment by FMorschel** [comment]
Just a little update.

Today this happened again with another project. Although I had not yet set the log for any project with https://github.com/Dart-Code/Dart-Code/issues/5154 (which I did now), I did manage to take a screenshot of the other `dart.exe` that was left hanging but got closed last time.

```
C:\Users\felip_0vh5fa6\.puro\envs\stable\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev --packages=C:\Users\felip_0vh5fa6\.puro\envs\stable\flutter\packages\flutter_tools\.dart_tool\package_config.json C:\Users\felip_0vh5fa6\.puro\shared\flutter_tools\761747bfc538b5af34aa0d3fac380f1bc331ec49\flutter_tools.snapshot run --machine --dart-define=flutter.inspector.structuredErrors=false -d _MY_DEVICE_IP_HERE_ --profile --devtools-server-address http://127.0.0.1:9101/ --target "_MY_PROJECT_PATH_HERE_"
```

As I told you before, this is the other `dart.exe` that was left hanging but finished itself (or got finished) before I could write it down here.

This time I simply opened the project and changed the debug configuration for the profile configuration in the launch options, after some time passed, my project was already running on my device but no connection to the debug console. 

I wonder if maybe there is a problem here (with this linking) and this is why sometimes it leaves some flutter daemons hanging.

Anyway, as I said before, small update. Whenever this happens again with any project I'll now be able to give you the logs.

**Comment by FMorschel** [comment]
Here are the latest two instances it happened:

<details>

<summary> Project 1 </summary>

- PID: 18404
- [daemon.txt](https://github.com/user-attachments/files/16248771/daemon.txt)
- [dap.txt](https://github.com/user-attachments/files/16248829/dap.txt)
- [extension.txt](https://github.com/user-attachments/files/16248831/extension.txt)
- [flutter_daemon.txt](https://github.com/user-attachments/files/16248832/flutter_daemon.txt)
- [InstrumentationLog.txt](https://github.com/user-attachments/files/16248834/InstrumentationLog.txt)
- [InstrumentationLog1.txt](https://github.com/user-attachments/files/16248836/InstrumentationLog1.txt)
- [InstrumentationLog2.zip](https://github.com/user-attachments/files/16248843/InstrumentationLog2.zip)
- [InstrumentationLog3.txt](https://github.com/user-attachments/files/16248844/InstrumentationLog3.txt)
- [InstrumentationLog4.zip](https://github.com/user-attachments/files/16248850/InstrumentationLog4.zip)
- [InstrumentationLog5.zip](https://github.com/user-attachments/files/16248857/InstrumentationLog5.zip)

</details>

<details>

<summary> Project 2 </summary>

- PID: 19480
- [daemon.txt](https://github.com/user-attachments/files/16248913/daemon.txt)
- [dap.txt](https://github.com/user-attachments/files/16248914/dap.txt)
- [extension.txt](https://github.com/user-attachments/files/16248915/extension.txt)
- [flutter_daemon.txt](https://github.com/user-attachments/files/16248917/flutter_daemon.txt)
- [InstrumentationLog.zip](https://github.com/user-attachments/files/16248928/InstrumentationLog.zip)
- [InstrumentationLog1.txt](https://github.com/user-attachments/files/16248931/InstrumentationLog1.txt)

</details>

I also had a third instance where it happened but unfortunately, I reopened vsCode before making a backup of the log files by mistake.

One thing I did, in that case, was to take screenshots of all hanging CLIs. One I noticed that was different was `dartaotruntime.exe` which got closed when I closed the flutter daemon.

Here is its full (I think, not sure because It was _really_ long) CLI:

```
C:\Users\felip_0vh5fa6\.puro\envs\stable\flutter\bin\cache\dart-sdk\bin\dartaotruntime.exe --disable-dart-dev C:\Users\felip_0vh5fa6\.puro\envs\stable\flutter\bin\cache\dart-sdk\bin\snapshots\forntend_server_aot.dart.snapshot --sdk-root C:\Users\felip_0vh5fa6\.puro\envs\stable\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --experimental-emit-debug-metadata -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/edd8546116457dbf1c5bdfb13ec9463d2bb5ed4/ --output-dill C:\Users\FELIP_~1\AppData\Local\Temp\flutter_tools.ed6508b\flutter_tool.780ffa07\app.dill --packages "_MY_PROJECT_PATH\.dart_tool\package_config.json" -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root--initialize-from-dill build\574fc2377ef17b67df2769d9e7907272.cache.dill.track.dill --source file:///C:/Users/felip_0vh5fa6/SUNSIG/trunk/Delphi
```

**Comment by DanTup** [comment]
> I did manage to take a screenshot of the other dart.exe that was left hanging but got closed last time.
> 
> `C:\Users\felip_0vh5fa6\.puro\envs\stable\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev --packages=C:\Users\felip_0vh5fa6\.puro\envs\stable\flutter\packages\flutter_tools\.dart_tool\package_config.json C:\Users\felip_0vh5fa6\.puro\shared\flutter_tools\761747bfc538b5af34aa0d3fac380f1bc331ec49\flutter_tools.snapshot run --machine --dart-define=flutter.inspector.structuredErrors=false -d _MY_DEVICE_IP_HERE_ --profile --devtools-server-address http://127.0.0.1:9101/ --target "_MY_PROJECT_PATH_HERE_"`

So this one looks different. This is `flutter run`. This is a process that could be orphaned if VS Code doesn't let us gracefully shut down. This could certainly be caused by the "Invalid debug adapter"-style issues noted above (it can also be caused by clicking the Stop button on the debug toolbar a second time if it didn't shut down gracefully fast enough).

The DAP log could be useful for that kind of issue, although if communication with the extension host is broken it's possible it would be incomplete.

> Here are the latest two instances it happened:
> Project 1

Both the daemon and extension log files here do not show any record of being shut down. This makes me think something is going wrong and VS Code is just terminating the extension host without calling `deactivate`. It's not clear to me why this would happen... one possibility is that something is severely broken (VS Code is failing to communicate with the extension host), another is that an extension (possibly us, possibly another) is blocking the single thread (for example stuck in an endless loop or just doing expensive sync work).

One thing that _might_ be useful, is running the **Developer: Open Extensions Log** command in VS Code, which will open a folder something like:

C:\Users\danny\AppData\Roaming\Code\logs\20240717T145824\window1\exthost

This path contains a folder with a timestamp for when the session was started. If you find the one that corresponds with the session that we think shut down uncleanly (maybe around `Tue Jul 16 2024 [07:47:04 GMT-0300 (Horário Padrão de Brasília)]` for the example above), then the `window1\exthost\exthost.log` file might have helpful logs. A clean session of mine ends like:

```
2024-07-17 15:22:00.790 [info] Extension host terminating: renderer closed the MessagePort
2024-07-17 15:22:00.811 [info] Extension host with pid 11632 exiting with code 0
```

It'd be interesting to know if this matches yours (in particularly, whether it's an exit code of 0).

**Comment by FMorschel** [comment]
This time I had two vsCode instances opened and I got three `dart.exe` (one `flutter run`, two `flutter daemon`s and one `dartaotruntime.exe`):

Flutter daemon 1: 49812
Flutter daemon 2: 42828
Flutter run: 71396
Dartaotruntime: 71096

This time, after a while, both `flutter run` and `dartaotruntime` closed themselves with no need for me to do anything.

Here are the logs for both projects that were opened:

<details>

<summary> Project 1 (the one I could not terminate even when the app was running on my device already but had no response on vsCode - this instance was another flutter project before, I did <code>CTRL+K</code> + <code>CTRL+O</code>) </summary>

- [daemon.txt](https://github.com/user-attachments/files/16273052/daemon.txt)
- [dap.txt](https://github.com/user-attachments/files/16273057/dap.txt)
- [extension.txt](https://github.com/user-attachments/files/16273058/extension.txt)
- [flutter_daemon.txt](https://github.com/user-attachments/files/16273060/flutter_daemon.txt)
- [InstrumentationLog.txt](https://github.com/user-attachments/files/16273067/InstrumentationLog.txt)
- InstrumentationLog.txt.2 (if you need it, please ask, way too big for me to send here)
- [InstrumentationLog3.txt](https://github.com/user-attachments/files/16273075/InstrumentationLog3.txt)
- [InstrumentationLog4.txt](https://github.com/user-attachments/files/16273076/InstrumentationLog4.txt)
- [InstrumentationLog5.txt](https://github.com/user-attachments/files/16273079/InstrumentationLog5.txt)


</details>

<details>

<summary> Project 2 (the project I was already working on previously and intended to go back soon) </summary>

- [daemon.txt](https://github.com/user-attachments/files/16273093/daemon.txt)
- [dap.txt](https://github.com/user-attachments/files/16273096/dap.txt)
- [extension.txt](https://github.com/user-attachments/files/16273098/extension.txt)
- [flutter_daemon.txt](https://github.com/user-attachments/files/16273099/flutter_daemon.txt)
- [InstrumentationLog.txt](https://github.com/user-attachments/files/16273101/InstrumentationLog.txt)
- [InstrumentationLog1.txt](https://github.com/user-attachments/files/16273111/InstrumentationLog1.txt)
- InstrumentationLog.txt.2 (if you need it, please ask, way too big for me to send here)
- [InstrumentationLog3.zip](https://github.com/user-attachments/files/16273163/InstrumentationLog3.zip)
- [InstrumentationLog4.zip](https://github.com/user-attachments/files/16273164/InstrumentationLog4.zip)

</details>

Here is the zip for [the log folder](https://quickshare.samsungcloud.com/sWNuN4iFdjdG) you asked.

Unfortunatelly I did not had the logs for yesterday morning anymore. Hope this ones help.

**Comment by DanTup** [comment]
Sorry for the delay. I think this log shows the problem:

```
2024-07-17 13:14:16.907 [error] Canceled: Canceled
    at new I (c:\Users\felip_0vh5fa6\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:34990)
    at S.U (c:\Users\felip_0vh5fa6\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:6023)
    at Proxy.z.<computed>.F.charCodeAt.T.CharCode.DollarSign.z.<computed> (c:\Users\felip_0vh5fa6\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:3107)
    at f.g (c:\Users\felip_0vh5fa6\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:154:203861)
    at f.executeCommand (c:\Users\felip_0vh5fa6\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:154:203299)
    at A.registerCommand.description (c:\Users\felip_0vh5fa6\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:154:202623)
    at f.h (c:\Users\felip_0vh5fa6\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:154:204400)
    at f.g (c:\Users\felip_0vh5fa6\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:154:203392)
    at f.executeCommand (c:\Users\felip_0vh5fa6\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:154:203299)
    at Object.executeCommand (c:\Users\felip_0vh5fa6\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:164:23051)
    at setCommandVisiblity (c:\Users\felip_0vh5fa6\.vscode\extensions\dart-code.dart-code-3.93.20240711\out\dist\extension.js:14130:22)
    at Object.deactivate (c:\Users\felip_0vh5fa6\.vscode\extensions\dart-code.dart-code-3.93.20240711\out\dist\extension.js:14104:9)
```

It seems that the first thing we do during shutdown is to call `void vs.commands.executeCommand("setContext", ...)` and that appears to be throwing exceptions. If those are synchronous (I can't tell from the stack trace), I think that would cause the rest of the shutdown to be skipped.

I'm not sure why this isn't happening for me or affecting a large number of people - perhaps there is a timing aspect to it (the extension host is shared, so maybe you have other extensions that are delaying Dart-Code's deactivate call just enough that these calls fail, but for others/me they do not).

I will make this code more resilient and push a new pre-release shortly for you to try out.

**Comment by DanTup** [comment]
@FMorschel I've published an updated pre-release of the extension (v3.93.20240723). Could you try updating to that  (note there was a pre-release yesterday with a similar version number ending in 22, you need 23), close all VS Code instances and terminate any orphaned processes (if any) from the old version, and then let me know if the issue is resolved?

Thanks!

**Comment by FMorschel** [comment]
Not even showing (the version ending in 22). Will do that and let you know.

![image](https://github.com/user-attachments/assets/a7d036a9-92e1-497b-a99d-42dc5963752f)

**Comment by DanTup** [comment]
Ugh, apparently I typo'd the version number yesterday and published with 2022 where the year should be (it's the 6th one down in your screenshot), so it was considered older. Doh!

![image](https://github.com/user-attachments/assets/aa2bed7e-e0d0-47d2-9a02-d825b431ccea)

But anyway, the latest one is what you want now anyway. Thanks!

**Comment by FMorschel** [comment]
As we've talked over on Discord, this issue doesn't appear to be happening anymore! I'll go ahead and close this. If this ever becomes a problem in the future and someone finds this issue, please file a new one (as I will) and feel free to reference this as your starting point for others to see anything related as well.
