### ISSUE TITLE
"URI scheme 'c' is not supported" error using analyzer plugins with Dart 3.5 pre-release

### ISSUE THREAD

**Issue by ChrisCRCB** [Dart-Code/Dart-Code#5156]
Hi,
Whenever I'm editing Dart code in a Flutter project in VS code, I get the following persistent notification:

```shell
Socket error: Invalid argument (uri): URI scheme 'c' is not supported. Allowed schemes are 'file', 'dart-macro+file'.: Socket error: Invalid argument (uri): URI scheme 'c' is not supported. Allowed schemes are 'file', 'dart-macro+file'.: "c:/Users/chris/src/ai_halls/lib/main.dart"
```

This does not happen with regular dart projects.

Cheers,

Chris

**Comment by DanTup** [comment]
Can you provide a screenshot of exactly where/how this is appearing? Is there any more information (such as a stack trace) either there, or if you click Help -> Toggle Developer Tools -> Console?


Can you also confirm the following:

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

 - Operating System and version:
 - VS Code version:
 - Dart extension version:
 - Dart/Flutter SDK version:
 - Target device (if the issue relates to Flutter debugging):

**Comment by ChrisCRCB** [comment]
**!! ⚠️ PLEASE REVIEW THIS REPORT FOR SENSITIVE INFORMATION BEFORE SHARING ⚠️ !!**

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.90.0
Flutter extension: 3.90.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: win 1.90.2

Workspace type: Flutter (LSP)

Dart (3.5.0-180.3.beta): C:\Users\chris\flutter\bin\cache\dart-sdk
Flutter (3.23.0-0.1.pre): C:\Users\chris\flutter (Windows (windows-x64/windows))

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`C:\Users\chris\flutter\bin\cache\dart-sdk\bin\dart.exe info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.5.0-180.3.beta (beta) (Wed Jun 5 15:06:15 2024 +0000) on "windows_x64"
- on windows / "Windows 10 Home" 10.0 (Build 22631)
- locale is en-GB

#### Project info

- sdk constraint: '>=3.5.0-180.3.beta <4.0.0'
- dependencies: backstreets_widgets, cupertino_icons, dart_openai, drift, drift_editors, flutter, flutter_riverpod, flutter_soloud, flutter_tts, json_annotation, path, path_provider, riverpod_annotation, shared_preferences, sqlite3, sqlite3_flutter_libs, url_launcher
- dev_dependencies: build_runner, custom_lint, drift_dev, flutter_lints, flutter_test, json_serializable, riverpod_generator, riverpod_lint

#### Process info

| Memory | CPU | Elapsed time | Command line |
| -----: | --: | -----------: | ------------ |
| 115 MB |  -- |              | dart.exe     |
| 542 MB |  -- |              | dart.exe     |
|  92 MB |  -- |              | dart.exe     |
|  94 MB |  -- |              | dart.exe     |
|  99 MB |  -- |              | dart.exe     |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`C:\Users\chris\flutter\bin\flutter.bat doctor -v`

```text
[√] Flutter (Channel beta, 3.23.0-0.1.pre, on Microsoft Windows [Version 10.0.22631.3737], locale en-GB)
    • Flutter version 3.23.0-0.1.pre on channel beta at C:\Users\chris\flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision 2feea7a407 (3 weeks ago), 2024-06-06 10:19:10 +0700
    • Engine revision bb10c54666
    • Dart version 3.5.0 (build 3.5.0-180.3.beta)
    • DevTools version 2.36.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\chris\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34322.80
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code, 64-bit edition (version 1.90.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.90.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3737]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 126.0.6478.126
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 125.0.2535.92

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

Interestingly, I don't get it with a clean project. Unless you can see something useful in these data, I'll remove dependencies one by one to see which (if any) are causing the problem. The error shows whether or not I'm running `build_runner`.

I can't see my screen, and am accessing VS Code with the NVDA screen reader. I can't show you a screenshot because I'm at work, and I can't guarantee that nothing sensitive (by which I mean work related) has made it sway into the screenshot.

I'm as sure as I can be that the debug tree is empty. The `Copy All` command from the console tree's context menu doesn't do anything.

Is there any more information I can give you?

Thank you for all your hard work. It is very much appreciated.

**Comment by DanTup** [comment]
@ChrisCRCB are you using `custom_lint` as an analyzer plugin? (it'll be listed in `analysis_options.yaml`). If so, could you try disabling that and restarting VS Code (or running the "Developer: Reload Window" command) and see if that changes anything?

Also - do you have any other Dart-related VS Code extensions installed?

On the surface, the error seems like something is passing a file path where a URI was expected (eg. it should start with `file:///` but does not).

An analyzer log could help but it might be difficult to ensure there's nothing sensitive in it if this only occurs on a work project. If we can figure out a way to repro in an isolate project that would be best.

Thanks!

**Comment by rrousselGit** [comment]
I've never seen this before. But it could be a custom_lint bug. Although it sounds like a windows issue.

Some way to reproduce this would be great.

**Comment by ChrisCRCB** [comment]
Hi,
If you run `flutter create something`, then `cd` into the directly, simply installing and activating `custom_lint` has no effect. Do `dart pub add dev:riverpod_lint` and the socket error happens when typing.

I wanted to find some other packages which use `custom_lint` to see if the bug lies in `riverpod_lint`, but there don't seem to be any others like `riverpod_lint` for comparison. I shall keep looking, unless you have any further ideas?

**Comment by rrousselGit** [comment]
Consider making an issue on Riverpod for this then :)

**Comment by DanTup** [comment]
@ChrisCRCB thank you! I was able to repro with this.

I'm not yet sure this isn't a Dart analysis server bug. It looks like it happens when the plugin triggers diagnostics:

```

1719407047113:PluginNoti:{"event"::"analysis.errors","params"::{"file"::"C::\\Dev\\Test Projects\\dartcode_5156\\lib\\main.dart","errors"::[{"severity"::"INFO","type"::"LINT","location"::{"file"::"C::\\Dev\\Test Projects\\dartcode_5156\\lib\\main.dart","offset"::60,"length"::6,"startLine"::4,"startColumn"::3,"endLine"::4,"endColumn"::9},"message"::"Flutter applications should have a ProviderScope widget at the top of the widget tree.","code"::"missing_provider_scope"}]}}:file::///C::/Users/danny/AppData/Local/.dartServer/.plugin_manager/87271fa197c6c85b743e1974d76d84a8/analyzer_plugin/bin/plugin.dart::
1719407047116:Res:{"jsonrpc"::"2.0","method"::"window/showMessage","params"::{"message"::"Socket error:: Invalid argument (uri):: URI scheme 'c' is not supported. Allowed schemes are 'file', 'dart-macro+file'.:: \"c::/Dev/Test%20Projects/dartcode_5156/lib/main.dart\"","type"::1}}
```

On the surface, the errors from the plugin look reasonable. I'll do some debugging later and post back. Thanks!

**Comment by DanTup** [comment]
I think this is a server issue. With support for macros, we started using URIs everywhere in the protocol classes (because it's the only way we can communicate supporting macro-generated content). I think here, we're getting messages from plugins that are using paths but we use the same deserialisation code and assume URIs.

```
Invalid argument (uri):: URI scheme 'c' is not supported. Allowed schemes are 'file', 'dart-macro+file'.:: \"c::/Dev/Test%20Projects/dartcode_5156/lib/main.dart\"

#0      _VirtualFileClientUriConverter.fromClientUri (package::analyzer_plugin/src/utilities/client_uri_converter.dart::106::7)
#1      _VirtualFileClientUriConverter.fromClientFilePath (package::analyzer_plugin/src/utilities/client_uri_converter.dart::91::7)
#2      new Location.fromJson (package::analyzer_plugin/protocol/protocol_common.dart::2801::35)
#3      new AnalysisError.fromJson (package::analyzer_plugin/protocol/protocol_common.dart::155::29)
#4      new AnalysisErrorsParams.fromJson.<anonymous closure> (package::analyzer_plugin/protocol/protocol_generated.dart::122::31)
#5      JsonDecoder.decodeList (package::analyzer_plugin/src/protocol/protocol_internal.dart::347::27)
#6      new AnalysisErrorsParams.fromJson (package::analyzer_plugin/protocol/protocol_generated.dart::118::30)
#7      new AnalysisErrorsParams.fromNotification (package::analyzer_plugin/protocol/protocol_generated.dart::133::33)
#8      AbstractNotificationManager.handlePluginNotification (package::analysis_server/src/plugin/notification_manager.dart::85::50)
#9      PluginSession.handleNotification (package::analysis_server/src/plugin/plugin_manager.dart::887::10)
```

I feel like this is something we discussed but I don't recall the details so I'll have to do a little more digging.

**Comment by ChrisCRCB** [comment]
@DanTup Thank you for continuing to look into this.

I don't know how distracting the messages are visually, but with a screen reader they cause a lot of unnecessary chatter that I can only suppress by turning off notifications for the Dart Code plugin.

Thanks again.

**Comment by DanTup** [comment]
The visual notifications aren't great, but significantly less distracting than they probably are for you. I understand this is a significant regression and am looking at the options for fixing.

I think the issue should only occur for Dart 3.5 pre-releases (which is where the macro functionality is currently enabled) and not the stable Flutter branch, but if that's different to what you see please let me know. Thanks!

**Comment by ChrisCRCB** [comment]
I can confirm that with Flutter stable there is no problem.

Thanks for looking into this.

**Comment by DanTup** [comment]
I have a fix in progress for this at https://dart-review.googlesource.com/c/sdk/+/373745.

**Comment by ChrisCRCB** [comment]
This is great news. Thank you so much.

Take care,
Chris Norman
Service Development Officer and Volunteer Coordinator
Coventry Resource Centre for the Blind
⠠⠉⠕⠧⠢⠞⠗⠽ ⠠⠗⠑⠎⠳⠗⠉⠑ ⠠⠉⠢⠞⠗⠑ ⠿ ⠮ ⠠⠃⠇
T: 024 7671 7522<tel:02476717522>
E: ***@***.******@***.***?subject=Reaching%20Out>
W: https://coventryblind.org.uk/
My normal working hours are 08:30-16:30 on Tuesdays, Thursdays, and Fridays. Please feel free to email or leave a telephone message when I am out of the office.

[Logo of Coventry Resource Centre for the Blind with the badge of the Queen's Award for Voluntary Service]
[CRCB is proud to be one of the charities supported by Lord Mayor Councillor Jaswant Singh Birdi and Mrs Krishna Kaur Birdi. To find out more please click here. Picture shows the Lord Mayor in full regalia seated next to the Lady Mayoress.]<https://www.coventry.gov.uk/lord-mayor/lord-mayor-coventry/3>

[To make a referral to CRCB please click here]<https://forms.office.com/e/a2QxeaaCv4>   [To volunteer for Coventry Resource Centre for the Blind, please click here] <https://forms.office.com/e/ghSwpmyRym>
[To make a donation to Coventry Resource Centre for the Blind, please click here]<https://www.justgiving.com/c-r-c-b>
