### ISSUE TITLE
After flutter upgrade I now get "Waiting for connection from debug service on Chrome" 

### ISSUE THREAD

**Issue by pcdavis** [Dart-Code/Dart-Code#5160]
**Describe the bug**
After upgrading to Flutter version 3.22.2 / Dart version 3.4.3, I am unable to run flutter run -d chrome without getting an empty browser window and a VS Code message that says "Waiting for connection from debug service on Chrome.." Stackoverflow has a solution that says downgrade the Flutter and Dart extensions, which I tried, but no joy. I don't want to downgrade Flutter because one of my dependencies requires the latest version.

**To Reproduce**

**Expected behavior**
My Flutter web app should open in the browser and display the home page.

**Screenshots**

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** 
**!! ⚠️ PLEASE REVIEW THIS REPORT FOR SENSITIVE INFORMATION BEFORE SHARING ⚠️ !!**

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.90.0
Flutter extension: 3.56.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: win 1.90.2

Workspace type: Flutter (LSP)

Dart (3.4.3): C:\Users\Local_Office\Desktop\flutterSDK\flutter\bin\cache\dart-sdk
Flutter (3.22.2): C:\Users\Local_Office\Desktop\flutterSDK\flutter (Edge (web-javascript/web))

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`C:\Users\Local_Office\Desktop\flutterSDK\flutter\bin\cache\dart-sdk\bin\dart.exe info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.4.3 (stable) (Tue Jun 4 19:51:39 2024 +0000) on "windows_x64"
- on windows / "Windows 10 Pro" 10.0 (Build 19045)
- locale is en-US

#### Project info

- sdk constraint: '>=3.3.3 <4.0.0'
- dependencies: audioplayers, auto_size_text, bloc_concurrency, chewie, cloud_firestore, connectivity_plus, csv, cupertino_icons, data_table_2, equatable, file_picker, firebase_auth, firebase_core, firebase_crashlytics, firebase_storage, firebase_ui_auth, firebase_ui_firestore, firebase_ui_oauth, flutter, flutter_bloc, flutter_dotenv, flutter_google_street_view, flutter_image_compress, flutter_secure_storage, flutter_stripe, flutter_stripe_web, flutter_svg, font_awesome_flutter, geolocator, get, get_it, google_fonts, google_maps_flutter, google_maps_flutter_web, http, image_picker, just_audio, maps_launcher, panorama_viewer, path_provider, photo_view, pointer_interceptor, provider, rxdart, universal_platform, url_launcher, uuid, video_player
- dev_dependencies: flutter_lints, flutter_test

#### Process info

|  Memory | CPU | Elapsed time | Command line |
| ------: | --: | -----------: | ------------ |
|  111 MB |  -- |              | dart.exe     |
|  590 MB |  -- |              | dart.exe     |
|  105 MB |  -- |              | dart.exe     |
|  107 MB |  -- |              | dart.exe     |
| 1887 MB |  -- |              | dart.exe     |
|  114 MB |  -- |              | dart.exe     |
|  111 MB |  -- |              | dart.exe     |
|  547 MB |  -- |              | dart.exe     |
|  100 MB |  -- |              | dart.exe     |
|  103 MB |  -- |              | dart.exe     |
|   95 MB |  -- |              | dart.exe     |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`C:\Users\Local_Office\Desktop\flutterSDK\flutter\bin\flutter.bat doctor -v`

```text
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.19045.4529], locale en-US)
    • Flutter version 3.22.2 on channel stable at C:\Users\Local_Office\Desktop\flutterSDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (3 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Local_Office\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.34)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.34601.136
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.4529]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 126.0.6478.127
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 126.0.2592.68

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

 - Operating System and version: Windows 10 Pro 19045.4529
 - VS Code version: 1,90,2
 - Dart extension version: 3.90.0 (I have also tried using v3.58.0 and others in between)
 - Dart/Flutter SDK version: Dart v3.4.3 / Flutter v3.2.2
 - Target device (if the issue relates to Flutter debugging): (Chrome and Edge browsers)

**Comment by DanTup** [comment]
> `flutter run -d chrome`

Can you clarify whether you're running this command manually, or you mean starting a debug session via VS Code?

If you run directly from the terminal, VS Code will not automatically connect to it (we don't know about processes launched externally).

If you are launching through VS Code, could you try first running the **Dart: Capture Debugging Logs** command from the command palette, then reproduce the issue (and allow it a few minutes just to be certain there's nothing going to time out), before clicming **cancel** on the logging notification to stop logging and open the log file.

Thanks!
