### ISSUE TITLE
Autocomplete/IntelliSense does not work for functions that return a record with named fields when using an expression body.

### ISSUE THREAD

**Issue by GiancarloCante** [Dart-Code/Dart-Code#5162]
**Describe the bug**
Autocomplete/IntelliSense does not work for functions that return a record with named fields when using an expression body.

Expression body:
![image](https://github.com/Dart-Code/Dart-Code/assets/172334239/4d5513d2-57fb-4a09-b3b4-518b8c40235b)
Block body:
![image](https://github.com/Dart-Code/Dart-Code/assets/172334239/84d3ac53-e6d2-4716-bae7-552e5359936a)

**To Reproduce**
```dart
void fun(({int anInt}) Function() callback) {}

void main() {
  fun(() => ());

  fun(() {
    return ();
  });
}
```
Trigger the autocompletion inside the returned record and you can see that only show the suggestions in the block body, and not in expression body.

**Expected behavior**
Should show the named fields suggestions.

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

Dart Code extension: 3.90.0
Flutter extension: 3.90.0
Dart: 3.4.1
Flutter: 3.22.1

**Comment by DanTup** [comment]
Working on a fix at https://dart-review.googlesource.com/c/sdk/+/374600

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/96a7c6ab245f89bc8b04e595653acf4bf3a601cc. The change is in the Dart analysis server so will show up in a Future Dart SDK release (not a Dart-Code release).
