### ISSUE TITLE
Error: Did not find a Dart VM Service advertised for xxx

### ISSUE THREAD

**Issue by hugaveme** [Dart-Code/Dart-Code#5170]
The Dart VM Service was not discovered after 60 seconds. This is taking much longer than expected...
Open the Xcode window the project is opened in to ensure the app is running. If the app is not running, try selecting "Product > Run" to fix the problem.
Error: Did not find a Dart VM Service advertised for xxx

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

 - Operating System and version:
 - VS Code version:
 - Dart extension version:
 - Dart/Flutter SDK version:
 - Target device (if the issue relates to Flutter debugging):

**Comment by hugaveme** [comment]
My version environment information is as follows：
Apple M3 Pro
MacOS：14.5 (23F79)

Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

 Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale
    zh-Hans-CN)
    • Flutter version 3.22.2 on channel stable at /Users/22hu/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (4 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3
Steps:
flutter run -v
log：
The Dart VM Service was not discovered after 60 seconds. This is taking much longer than expected...
Open the Xcode window the project is opened in to ensure the app is running. If the app is not running, try selecting "Product > Run" to fix the problem.
then：Error: Did not find a Dart VM Service advertised for xxx

When I run the project with xcode, it works.

**Comment by hugaveme** [comment]
other log
[   +5 ms] Checking for advertised Dart VM Services...
[+1994 ms] Checking for available port on
com.example.vmcs._dartVmService._tcp.local
[+5005 ms] Checking for available port on
com.example.vmcs._dartVmService._tcp.local
[+5004 ms] Unexpectedly found more than one Dart VM Service report for
                    com.example.vmcs._dartVmService._tcp.local - using first one
(54292).
[   +3 ms] Checking for available port on
com.example.vmcs._dartVmService._tcp.local
[        ] Checking for available port on
com.example.vmcs._dartVmService._tcp.local
[        ] Checking for available port on
com.example.vmcs._dartVmService._tcp.local
[        ] Checking for available port on
com.example.vmcs._dartVmService._tcp.local
[        ] Checking for available port on
com.example.vmcs._dartVmService._tcp.local
[        ] Checking for available port on
com.example.vmcs._dartVmService._tcp.local
[        ] Checking for available port on
com.example.vmcs._dartVmService._tcp.local
[        ] Checking for available port on
com.example.vmcs._dartVmService._tcp.local
[+3348 ms] Checking for available port on
com.example.vmcs._dartVmService._tcp.local
[   +4 ms] Checking for available port on
com.example.vmcs._dartVmService._tcp.local
[+44636 ms] The Dart VM Service was not discovered after 60 seconds. This is
taking much
                     longer than expected...
[   +1 ms] Open the Xcode window the project is opened in to ensure the app is
running. If
           the app is not running, try selecting "Product > Run" to fix the
problem.
[        ] No path provided for Symbols directory.

**Comment by hugaveme** [comment]
[   +1 ms] "flutter run" took 613,236ms.
[   +4 ms] 
           #0      throwToolExit
(package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand
           (package:flutter_tools/src/commands/run.dart:840:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand
(package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure>
           (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>
           
           
[ +254 ms] ensureAnalyticsSent: 252ms
[        ] Running 1 shutdown hook
[   +2 ms] Shutdown hooks complete
[  +23 ms] exiting with code 1

**Comment by hugaveme** [comment]
mobile：iOS 17.3 21D50

**Comment by DanTup** [comment]
If you're seeing this issue when running `flutter run` from the terminal, then this will need to be filed at https://github.com/flutter/flutter/. This repository is only for the VS Code extension so if the problem affects `flutter run` it isn't something that can be fixed here.

Please file an issue at https://github.com/flutter/flutter/issues/new/choose and include all of the information above and details of what kind of device you're running the app on.

Thanks!
