### ISSUE TITLE
Optimize Dart Extension: On-Demand Semantic Analysis to Reduce Memory Usage

### ISSUE THREAD

**Issue by iCandang** [Dart-Code/Dart-Code#5172]
**Problem Description:**
I'm always frustrated when the Dart extension for Visual Studio Code performs semantic analysis on all files, regardless of the file's language. This behavior leads to excessive memory usage, which can slow down my overall development experience, especially when I'm working with languages other than Dart.

**Proposed Solution:**
I would like the Dart extension to include a feature that allows semantic analysis to be performed only on Dart files. This could be implemented as a setting within the extension that users can toggle on or off. Alternatively, the extension could automatically detect the file language and enable semantic analysis only for Dart files.

**Alternatives Considered:**
1. Temporarily disabling the Dart extension when not working with Dart files, but this is inconvenient as I need to re-enable it each time I switch contexts.
2. Using a different IDE or editor that has better language-specific performance management, but this would require learning new tools and potentially losing the benefits of VSCode's ecosystem.
3. Manually closing and reopening files to trigger or halt semantic analysis, but this is not a scalable solution and interrupts the workflow.

**Additional Context:**
The Dart extension is a valuable tool for Dart development, but its current behavior of analyzing all files indiscriminately is not optimal for multi-language projects. I believe that adding a language-specific analysis setting or an intelligent detection system would greatly enhance the performance and usability of the extension. This would also align with VSCode's philosophy of providing a customizable and efficient development environment.

I have not encountered any specific error messages or issues that could be directly linked to this problem, but the performance impact is noticeable, particularly on systems with limited resources. If possible, providing a screenshot or a performance monitoring log could help illustrate the issue, but at this stage, I believe the description is sufficient to convey the problem and the desired solution.

**Comment by DanTup** [comment]
> I'm always frustrated when the Dart extension for Visual Studio Code performs semantic analysis on all files, regardless of the file's language

Can you clarify what behaviour you're seeing that makes it seem like this is happening? The server does analyze a couple of extra non-Dart files (like `pubspec.yaml` and `analysis_options.yaml`), but it doesn't analyze all files.

> If possible, providing a screenshot or a performance monitoring log could help illustrate the issue, but at this stage, I believe the description is sufficient to convey the problem and the desired solution.

Unfortunately I don't think the description is enough - the Dart server does not analyze all files (and if using LSP then only Dart + analysis options should even be sent to the server as you're making changes). If you're able to provide more information, screenshots, timings and some details about the size of your project (such as the output of `code --status` when you have this project open), that might help understand.

Thanks!
