### ISSUE TITLE
Warning unchecked_use_of_nullable_value also when null check exists

### ISSUE THREAD

**Issue by caiocinel** [Dart-Code/Dart-Code#5173]
**Describe the bug**
When using nullable fields in code, the extension marks warning with dart(unchecked_use_of_nullable_value) also when a null check occours before the access. The code keeps compiling and running without any problems.

**Expected behavior**
When make a null check in context the warning can't be shown

**Screenshots**
![image](https://github.com/Dart-Code/Dart-Code/assets/60858720/5bca85da-33db-4ffa-904e-922e422efa19)

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.92.0
Flutter extension: 3.92.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: win 1.91.0

Workspace type: Flutter (LSP) (Multiroot)

Dart (3.4.0): C:\FlutterSDK\flutter\bin\cache\dart-sdk
Flutter (3.22.0): C:\FlutterSDK\flutter (Windows (windows-x64/windows))

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`C:\FlutterSDK\flutter\bin\cache\dart-sdk\bin\dart.exe info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.4.0 (stable) (Mon May 6 07:59:58 2024 -0700) on "windows_x64"
- on windows / "Windows 10 Pro" 10.0 (Build 22631)
- locale is pt-BR

#### Project info

- sdk constraint: '>=3.3.0 <4.0.0'
- dependencies: brasil_fields, cupertino_icons, flutter, flutter_facebook_auth, flutter_map, flutter_map_cancellable_tile_provider, geolocator, google_sign_in, http, intl, latlong2, mask_text_input_formatter, otp_text_field, path, shared_preferences, simple_icons, sqflite, sqflite_common_ffi
- dev_dependencies: flutter_lints, flutter_test

#### Process info

| Memory | CPU | Elapsed time | Command line |
| -----: | --: | -----------: | ------------ |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`C:\FlutterSDK\flutter\bin\flutter.bat doctor -v`

```text
[!] Flutter (Channel stable, 3.22.0, on Microsoft Windows [versÆo 10.0.22631.3810], locale pt-BR)
    • Flutter version 3.22.0 on channel stable at C:\FlutterSDK\flutter
    ! The flutter binary is not on your path. Consider adding C:\FlutterSDK\flutter\bin to your path.
    ! The dart binary is not on your path. Consider adding C:\FlutterSDK\flutter\bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (8 weeks ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34322.80
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.91.0)
    • VS Code at C:\Users\caioc\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.92.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÆo 10.0.22631.3810]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 126.0.6478.127
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 126.0.2592.87

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by DanTup** [comment]
This is intended behaviour. On line 52, you're not accessing a field, but rather a _getter_. That getter could be overridden in a subclass. For example, consider this code:

```
import 'dart:math';

class A {
  String? foo;

  void f() {
    if (foo != null) {
      print(foo.length);
    }
  }
}

class B {
  final random = Random();
  String? get foo => random.nextBool() ? null : 'string';
}
```

In this code, instances of `B` would randomly return null/null-null when you access `foo` because it's a getter and not a field.

While it might be the case that in your code this never happens, it would not be sound for Dart to assume the value returned by the getter on line 43 is the same as the value when it accesses the getter on line 52.

What you can do, is capture the value into a new variable so it can't change:

```
if (event case final event?) {
  // Here, `event` is a new variable guaranteed to not be null
}
```

Here, there `case final event?` assigns the value of `event` to a new shadowed variable named `event`, but the `?` means it only matches if it's not null. You could also write it as `if (event case String event)` which checks that it's a String (not a nullable String).

There are some proposals in Dart (such as one for [stable getters](https://github.com/dart-lang/language/issues/1518/)) to try to improve some of these cases because it's not always obvious why the null can't be discounted, but I don't know if any have been agreed yet.

Hope this helps!
