### ISSUE TITLE
Hover tooltip gets in the way now

### ISSUE THREAD

**Issue by Reprevise** [Dart-Code/Dart-Code#5177]
**Describe the bug**
I swear this didn't used to happen unless I'm going crazy. When I'm hovering over the closing bracket of a list literal, the tooltip goes over the "content" of the list which makes it hard to select the items in the list. I've attached a GIF of the problem below.

**To Reproduce**
1. Make a list literal and put something in it.
2. Hover over the closing bracket of the list literal.
3. Tooltip appears

**Expected behavior**
I don't actually remember the old behavior but I know I wasn't having this issue otherwise I would've made an issue about it here.

**Screenshots**

![Code_dJuub15GE0](https://github.com/Dart-Code/Dart-Code/assets/25782944/92c997bb-887f-46e2-a4bb-102a1e2e96e7)

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.92.0
Flutter extension: 3.92.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: win 1.91.0

Workspace type: Flutter (LSP)

Dart (3.4.3): C:\Users\bscho\.puro\shared\caches\edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4\dart-sdk
Flutter (3.22.2): C:\Users\bscho\.puro\envs\stable\flutter (No device)

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`C:\Users\bscho\.puro\shared\caches\edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4\dart-sdk\bin\dart.exe info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.4.3 (stable) (Tue Jun 4 19:51:39 2024 +0000) on "windows_x64"
- on windows / "Windows 10 Home" 10.0 (Build 22631)
- locale is en-US

#### Project info

- sdk constraint: '^3.4.0'
- dependencies: async_button_builder, auto_route, background_fetch, collection, custom_refresh_indicator, dart_date, dio, duration, equatable, expandable_page_view, extended_nested_scroll_view, fast_immutable_collections, firebase_analytics, firebase_app_check, firebase_core, firebase_crashlytics, firebase_messaging, firebase_remote_config, flutter, flutter_animate, flutter_hooks, flutter_local_notifications, flutter_localizations, flutter_markdown, flutter_rating_stars, flutter_riverpod, flutter_secure_storage, flutter_svg, freezed_annotation, google_mobile_ads, grouped_list, hive, hive_flutter, home_widget, hooks_riverpod, html, http, image_picker, in_app_purchase, in_app_purchase_android, in_app_purchase_storekit, in_app_review, infinite_scroll_pagination, internet_connection_checker, intl, json_annotation, linked_scroll_controller, mask_text_input_formatter, native_dio_adapter, oauth2, path, posthog_flutter, pretty_qr_code, readmore, riverpod, riverpod_annotation, screenshot, sensors_plus, share_plus, shimmer, sliver_tools, snap_scroll_physics, socket_io_client, sticky_and_expandable_list, super_context_menu, syncfusion_flutter_charts, syncfusion_flutter_core, talker_flutter, timeago, two_dimensional_scrollables, url_launcher, video_player, visibility_detector, webview_flutter, worker_manager
- dev_dependencies: auto_route_generator, build_runner, flutter_lints, flutter_native_splash, freezed, hive_generator, json_serializable, riverpod_generator, test
- elided dependencies: 1

#### Process info

|  Memory | CPU | Elapsed time | Command line |
| ------: | --: | -----------: | ------------ |
|   12 MB |  -- |              | dart.exe     |
| 3778 MB |  -- |              | dart.exe     |
|   32 MB |  -- |              | dart.exe     |
|   13 MB |  -- |              | dart.exe     |
|   15 MB |  -- |              | dart.exe     |
|   21 MB |  -- |              | dart.exe     |
|   35 MB |  -- |              | dart.exe     |
|   15 MB |  -- |              | dart.exe     |
|   18 MB |  -- |              | dart.exe     |
|  101 MB |  -- |              | dart.exe     |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`C:\Users\bscho\.puro\envs\stable\flutter\bin\flutter.bat doctor -v`

```text
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22631.3810], locale en-US)
    • Flutter version 3.22.2 on channel stable at C:\Users\bscho\.puro\envs\stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (5 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\bscho\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34330.188
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.91.0)
    • VS Code at C:\Users\bscho\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.92.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3810]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 126.0.2592.87

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by DanTup** [comment]
I don't believe anything has changed here (at least from Dart's perspective - though we have no control over the rendering of the hover). However, there is this setting which I have set to `false` in my settings (suggesting the default is `true`):

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/1ad3af74-a48e-4a5e-bcee-306b8fe8691e)

Is it possible you also had this set to `false` at some point, but it's been reverted to its default?

**Comment by Reprevise** [comment]
I guess its possible though I don't remember that setting at all. I'll close this issue for now as setting that to false solves the issue.
