### ISSUE TITLE
Socket error: Invalid argument (uri): URI is not a valid file:// URI: "/Users/<username>/repo/<repo_name>/lib/main.dart"

### ISSUE THREAD

**Issue by PharrellWANG** [Dart-Code/Dart-Code#5179]
**Describe the bug**
After the vscode flutter and dart extension have been installed, I keep receiving error ``Socket error: Invalid argument (uri): URI is not a valid file:// URI: "/Users/<username>/repo/<repo_name>/lib/main.dart"`` after I close it again and again.

**To Reproduce**
Just install flutter and dart extension, use vscode to open a flutter project.

**Expected behavior**
No such error should pop up.

**Screenshots**

![CleanShot 2024-07-10 at 13 01 01@2x](https://github.com/Dart-Code/Dart-Code/assets/22740944/48ae9910-a731-47c8-94f0-67206d55eb97)

**Comment by DanTup** [comment]
There's an existing issue for this at https://github.com/Dart-Code/Dart-Code/issues/5156

There's a bug in the current Dart 3.5 pre-release SDK that causes this error when communicating with analyzer plugins. A fix has been landed and cherry-picked for the next beta. If you subscribe to the issue above, I'll post in there once the fix makes it to a released beta.
