### ISSUE TITLE
Incorrect warning in Intellesense regarding nullability with optional paths

### ISSUE THREAD

**Issue by Guru-Zachw** [Dart-Code/Dart-Code#5181]
**Describe the bug**
There is a bug in the intellesense which improperly warns that a null check is not needed because the variable cannot be null.

**To Reproduce**
Put this code in a VSCode window with the language mode set to dart
```
void thing() {
  int? nullableThing;
  if(false) {
    nullableThing = 1;
  }

  if (nullableThing != null) {
    // Warning here that nullableThing cannot be null
    print(nullableThing);
  }
}
```

**Expected behavior**
I don't expect there to be a warning

**Screenshots**
![image](https://github.com/Dart-Code/Dart-Code/assets/95657952/6dcef360-5476-4152-86f3-2972243d06f5)
on Hover
```
The operand can't be null, so the condition is always 'false'.
Try removing the condition, an enclosing condition, or the whole conditional statement.dart[unnecessary_null_comparison](https://dart.dev/diagnostics/unnecessary_null_comparison)
int? nullableThing
```

**!! ⚠️ PLEASE REVIEW THIS REPORT FOR SENSITIVE INFORMATION BEFORE SHARING ⚠️ !!**

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.92.0
Flutter extension: 3.92.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: linux 1.91.0

Workspace type: Flutter (LSP)

Dart (3.4.3): /home/zachw/bin/flutter/bin/cache/dart-sdk
Flutter (3.22.2): /home/zachw/bin/flutter (Pixel 7 (android-arm64/android))

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`/home/zachw/bin/flutter/bin/cache/dart-sdk/bin/dart info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.4.3 (stable) (Tue Jun 4 19:51:39 2024 +0000) on "linux_x64"
- on linux / Linux 5.4.0-189-generic #209-Ubuntu SMP Fri Jun 7 14:05:13 UTC 2024
- locale is en_US.UTF-8

#### Project info

- sdk constraint: '>=3.4.1 <4.0.0'
- dependencies: collection, device_info_plus, dio, firebase_analytics, firebase_core, fl_chart, flutter, flutter_colorpicker, flutter_facebook_auth, flutter_multi_formatter, flutter_riverpod, flutter_web_plugins, freezed_annotation, go_router, google_sign_in, google_sign_in_web, image, image_cropper, image_picker, infinite_scroll_pagination, intl, json_annotation, linked_scroll_controller, material_symbols_icons, path_provider, pinput, riverpod, riverpod_annotation, shared_preferences, sign_in_with_apple, table_calendar, timezone, us_states, webview_flutter
- dev_dependencies: build_runner, custom_lint, flutter_launcher_icons, flutter_lints, flutter_native_splash, flutter_test, freezed, json_serializable, riverpod_generator, riverpod_lint
- elided dependencies: 1

#### Process info

|  Memory |  CPU | Elapsed time | Command line                                                                    |
| ------: | ---: | -----------: | ------------------------------------------------------------------------------- |
|   51 MB | 0.0% |   1-01:55:09 | dart devtools --machine --allow-embedding --dtd-uri ws:<path>/rDJ5ZuCXT0LYuxW8  |
| 2262 MB | 1.8% |   1-01:55:09 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.92.0 |
|  257 MB | 0.0% |   1-01:55:04 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.92.0 |
| 1135 MB | 5.1% |   1-01:54:57 | dart lib/custom_lint_client.dart ::1 38737                                      |
|   55 MB | 0.0% |   1-01:55:09 | dart tooling-daemon --machine                                                   |
|   56 MB | 0.0% |   1-01:55:04 | dart tooling-daemon --machine                                                   |
|   83 MB | 0.1% |   1-01:55:09 | flutter_tools.snapshot daemon                                                   |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`/home/zachw/bin/flutter/bin/flutter doctor -v`

```text
[✓] Flutter (Channel stable, 3.22.2, on Linux Mint 20.2 5.4.0-189-generic, locale en_US.UTF-8)
    • Flutter version 3.22.2 on channel stable at /home/zachw/bin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (5 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /home/zachw/Android/Sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_SDK_ROOT = /home/zachw/Android/Sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.23+9-post-Ubuntu-1ubuntu120.04.2)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.91.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.92.0

[✓] Connected device (3 available)
    • Pixel 7 (mobile) • 10.22.3.93:5555 • android-arm64  • Android 14 (API 34)
    • Linux (desktop)  • linux           • linux-x64      • Linux Mint 20.2 5.4.0-189-generic
    • Chrome (web)     • chrome          • web-javascript • Google Chrome 126.0.6478.126

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by DanTup** [comment]
I think the text in the diagnostic is wrong here, but I think the fact that it's firing is correct.

The greyed out code in your screenshot is dead code - it can never execute because it's gaurded with `is (false)` and the analyze knows this. Therefore, the variable is _always_ null, and therefore the condition is _always_ `false`.

If you change your `if (false)` to something that isn't guaranteed to be `false`, then the diagnostic will go away.

There's https://github.com/dart-lang/sdk/issues/53860 covering the bad text (it should say the it's _always_ `null` and therefore the condition is always `false`).

**Comment by Guru-Zachw** [comment]
You are correct. This is my bad.  I figured out what the confusion was. I had something more similar to this:
```

void thing(bool condition) {
  int? nullableThing;
  if (condition) {
    int nullableThing = 1;
    nullableThing = nullableThing.clamp(1, 2);
  }

  if (nullableThing != null) {
    // Warning here that nullableThing cannot be null
    print(nullableThing);
  }
}
```

The same variable being created within a difference scoping layer caused what looked like a bug, but was certainly not a bug.

This is not a bug. Appologies. Thank you for your time

**Comment by DanTup** [comment]
No problem, glad you found the issue!
