### ISSUE TITLE
The editor could not be opened because the file was not found. Breakpoints "All Exceptions" socket_patch.dart.

### ISSUE THREAD

**Issue by equescodebelike** [Dart-Code/Dart-Code#5182]
**Describe the bug**
Launch Debug Session with "All Exceptions" and "Uncaught Exceptions" leads to socket_patch.dart flutter/bin/cache/pkg/sky_engine/lib/_internal/vm/bin/socket_patch.dart but The editor could not be opened because the file was not found. IDE VS Code.

**To Reproduce**
1. Go to Run and Debug.
2. Choose Breakpoints "All Exceptions", "Uncaught Exceptions".
3. Launch Debug Session.

**Expected behavior**
Found such file with description of the error.

**Screenshots**
![image](https://github.com/user-attachments/assets/a4223a28-a411-4921-99ee-3558140e7389)

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.92.0
Flutter extension: 3.92.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: win 1.91.0

Workspace type: Flutter (LSP)

Dart (3.4.1): C:\flutter\bin\cache\dart-sdk
Flutter (3.22.1): C:\flutter (sdk gphone64 x86 64 (android-x64/android))

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`C:\flutter\bin\cache\dart-sdk\bin\dart.exe info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.4.1 (stable) (Tue May 21 15:46:25 2024 +0000) on "windows_x64"
- on windows / "Windows 10 Pro" 10.0 (Build 22621)
- locale is ru-RU

#### Project info

- sdk constraint: '>=3.3.1 <4.0.0'
- dependencies: analyzer, appmetrica_plugin, auto_route, barcode_widget, cached_network_image, collection, decimal, device_info, dio, dismissible_page, firebase_analytics, firebase_core, firebase_crashlytics, firebase_messaging, flutter, flutter_native_splash, flutter_rating_bar, flutter_svg, flutter_swiper_null_safety, freezed, get_it, hive, injectable, intl, json_annotation, json_serializable, logger, lottie, onesignal_flutter, package_info, path_provider, permission_handler, pretty_dio_logger, provider, pub_semver, retrofit_generator, rxdart, share_plus, shared_preferences, shimmer_animation, smooth_page_indicator, store_redirect, uni_links, url_launcher, uuid, video_player, visibility_detector, webview_flutter
- dev_dependencies: auto_route_generator, build_runner, injectable_generator
- elided dependencies: 76

#### Process info

| Memory | CPU | Elapsed time | Command line |
| -----: | --: | -----------: | ------------ |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`C:\flutter\bin\flutter.bat doctor -v`

```text
[√] Flutter (Channel stable, 3.22.1, on Microsoft Windows [Version 10.0.22621.525], locale ru-RU)
    • Flutter version 3.22.1 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (7 weeks ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\nep36\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Users\nep36\AppData\Local\CentBrowser\Application\chrome.exe

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.91.0)
    • VS Code at C:\Users\nep36\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.92.0

[√] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • unknown
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 125.0.2535.85

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by DanTup** [comment]
Thanks for the report - there's an open issue tracking this at https://github.com/flutter/flutter/issues/151171

**Comment by raufzer** [comment]
any solution ?

**Comment by raufzer** [comment]
![image](https://github.com/user-attachments/assets/f9b0ccc2-7d9f-4432-9b8d-40f8d234b47c)
got the same problem

**Comment by raufzer** [comment]
> ![image](https://private-user-images.githubusercontent.com/112574242/365408795-f9b0ccc2-7d9f-4432-9b8d-40f8d234b47c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3OTUyMjYsIm5iZiI6MTcyNTc5NDkyNiwicGF0aCI6Ii8xMTI1NzQyNDIvMzY1NDA4Nzk1LWY5YjBjY2MyLTdkOWYtNDQzMi05YjhkLTQwZjhkMjM0YjQ3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQxMTI4NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTc4NjMzZjUyNzllZmVmNTZkOTE4ZTRmMzI5NDE2MGE0ZDQ2YTRiNTFlZWQxMzk2OTQ0NDE0YzM1MjRiNmMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CwRRFKkanSRB9KKjsMK1lKfesxrsNAAn3EEAWhLQ4Go) got the same problem

update : everytime i do the : flutter upgrade --force command , it works properly .

**Comment by DanTup** [comment]
Unfortunately not, this is still an open issue in Flutter - see my comment directly above yours.

> update : everytime i do the : flutter upgrade --force command , it works properly .

I'm not sure why this would fix it - can you confirm the version of the Dart extension you have installed, and provide a screenshot of what you see when this works, including the breadcrumb that shows the full path of where the socket_patch file is being opened from?

**Comment by moinkhan780** [comment]
Same issue for me also till now not solve i don't know why. VS code in windows 11 SUCKS

**Comment by DanTup** [comment]
https://github.com/flutter/flutter/issues/151171 has recently been fixed and will ship in a future release of the Flutter SDK.
