### ISSUE TITLE
Supporting enabling the VM Service traffic when the session is already running

### ISSUE THREAD

**Issue by FMorschel** [Dart-Code/Dart-Code#5197]
**Is your feature request related to a problem? Please describe.**
As @DanTup told me on Discord, I do agree with the following:

> It's annoying to have a repro but already have the session running and have to hope you can repro after restarting.

**Describe the solution you'd like**
> Supporting enabling the VM Service traffic when the session is already running.

**Describe alternatives you've considered**
Having the [**Dart: Capture Debugging Logs** command](https://dartcode.org/docs/logging/#capture-debugging-logs) running at all times.

**Additional context**
None.

**Comment by DanTup** [comment]
The Dart-Code parts of this are in https://github.com/Dart-Code/Dart-Code/commit/071d19e64cfbec0860e006d60363678089dd1a72, but it also requires some SDK DAP changes which I've got a change open for in https://dart-review.googlesource.com/c/sdk/+/377222.

I'll close this once the SDK changes land, but it won't begin working until a future Dart/Flutter SDK release.

**Comment by DanTup** [comment]
This is fixed by https://github.com/dart-lang/sdk/commit/ef0e0ee2b6bd309ee0bc26867a82bfa248d14be8. This is a fix in the language server that ships as part of the SDK, so the fix will show up in a future SDK release (not a Dart-Code release).
