### ISSUE TITLE
Displaying numbers as hex in debugger does not apply to dart:typed_data lists like Uint8List

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#5199]
Reported by @NeariX67 at https://github.com/Dart-Code/Dart-Code/issues/3940#issuecomment-2247394431

```dart
import 'dart:developer';
import 'dart:typed_data';

void main(List<String> arguments) {
  var a = 1;
  var b = [1, 2, 3];
  var c = Uint8List.fromList(b);
  debugger();
}
```

![image](https://github.com/user-attachments/assets/50a0865a-a653-48b1-b344-cb9cd24109cd)

**Comment by DanTup** [comment]
Got a fix on the way at https://dart-review.googlesource.com/c/sdk/+/377423. It's part of the debugger adapter that ships in the SDK, so it'll show up in a future SDK release (not a Dart-Code release).

I'll close this issue once that change lands.

![image](https://github.com/user-attachments/assets/8a7b11b1-1684-45dc-9dcf-823dc5b88404)

**Comment by NeariX67** [comment]
Wunderful. Appreciate your fast response to this issue.

**Comment by DanTup** [comment]
Fix landed in https://github.com/dart-lang/sdk/commit/8ab91cd9db316db7998f0dc576e4978886050e44. It's in the SDK, so it will show up in a future SDK release (not a Dart-Code extension release).
