### ISSUE TITLE
"Don't show again" option for "Project contains issues that can be fixed by dart fix" prompt does not persist

### ISSUE THREAD

**Issue by JCKodel** [Dart-Code/Dart-Code#5202]
**Describe the bug**

![image](https://github.com/user-attachments/assets/1129a5bd-2ce7-4bae-b104-30a4d3cebdc5)

`Don't Show Again" does nothing.

**To Reproduce**
Not entirely sure what triggers this notification, but, currently, I have:

![image](https://github.com/user-attachments/assets/bd0b28d5-6faf-4dcd-93c0-ce456a96a78f)

**Expected behavior**
Once I click Don't Show Again, I don't want it to be shown again.

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.92.0
Flutter extension: 3.92.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: win 1.91.1

Workspace type: Flutter (LSP)

Dart (3.4.4): C:\Users\jckod\flutter\bin\cache\dart-sdk
Flutter (3.22.3): C:\Users\jckod\flutter (moto g 6 plus (android-arm64/android))

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`C:\Users\jckod\flutter\bin\cache\dart-sdk\bin\dart.exe info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.4.4 (stable) (Wed Jun 12 15:54:31 2024 +0000) on "windows_x64"
- on windows / "Windows 10 Pro" 10.0 (Build 22631)
- locale is en-GB

#### Project info

- sdk constraint: '>=3.4.4 <4.0.0'
- dependencies: flutter, flutter_native_splash, flutter_secure_storage, gap, hugeicons, nhost_dart, scrollable_positioned_list, system_theme, vector_graphics
- dev_dependencies: flutter_lints, vector_graphics_compiler

#### Process info

| Memory | CPU | Elapsed time | Command line |
| -----: | --: | -----------: | ------------ |
| 110 MB |  -- |              | dart.exe     |
| 523 MB |  -- |              | dart.exe     |
| 100 MB |  -- |              | dart.exe     |
| 102 MB |  -- |              | dart.exe     |
|  94 MB |  -- |              | dart.exe     |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`C:\Users\jckod\flutter\bin\flutter.bat doctor -v`

```text
[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.22631.3880], locale en-GB)
    • Flutter version 3.22.3 on channel stable at C:\Users\jckod\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (13 days ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Limitless credit card number 374068277391038
    • Dart version 3.4.4
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\jckod\AppData\Local\Android\sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.10.35027.167
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[√] VS Code (version 1.91.1)
    • VS Code at C:\Users\jckod\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.92.0

[√] Connected device (4 available)
    • moto g 6 plus (mobile) • 0048659732 • android-arm64  • Android 9 (API 28)
    • Windows (desktop)      • windows    • windows-x64    • Microsoft Windows [Version 10.0.22631.3880]
    • Chrome (web)           • chrome     • web-javascript • Google Chrome 126.0.6478.185
    • Edge (web)             • edge       • web-javascript • Microsoft Edge 127.0.2651.74

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by DanTup** [comment]
Thanks - I can reproduce this.. Clicking "Don't show Again" used to write a JSON file into this folder with the preference, however it appears to not be there even after I've clicked the button.

![image](https://github.com/user-attachments/assets/a664eb07-6caf-4f54-9977-e23710d1cc71)

```
1722287092233:Res:{"id"::5,"jsonrpc"::"2.0","method"::"window/showMessageRequest","params"::{"actions"::[{"title"::"Preview Fixes"},{"title"::"Apply Fixes"},{"title"::"Don't Show Again"}],"message"::"Your project contains issues that can be fixed automatically.","type"::3}}
1722287094384:Req:{"jsonrpc"::"2.0","id"::5,"result"::{"title"::"Don't Show Again"},"clientRequestTime"::1722287094383}
```

**Comment by DanTup** [comment]
Working on a fix at https://dart-review.googlesource.com/c/sdk/+/377940

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/c18b84d6d22a5537460f8e788ca06609a7c8b9f4. The fix in the analysis server so will ship in a future SDK release.
