### ISSUE TITLE
Unable to open static DevTools extensions on current Flutter beta

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#5208]
Using the current Flutter beta and opening the [app_that_uses_foo](https://github.com/flutter/devtools/tree/master/packages/devtools_extensions/example/app_that_uses_foo) project, the sidebar shows the extension but fails to launch if there is not debug session.

This is because the `requiresDebugSession` flag defaults to true (sidebar does not currently pass it) unless we _know_ that the target is a static page (which we only do for 1p pages, because they are hard-coded into Dart-Code).

As a workaround until sidebar is passing the flags, we should:

- if the target page is an `_ext` page and neither `requiresDebugSession` or `prefersDebugSession` are explicitly set
- downgrade from `requiresDebugSession` to `prefersDebugSession`

This fixes the issue, but there are some side-effects or doing this:

1. Attempting to launch a static tool when there are > 1 debug sessions active will prompt the user to select one (even though the tool won't use it)
2. Attempting to launch a runtime tool when there are no active sessions will launch the tool without a connection (instead of doing nothing)

Discussing with @kenzieschmoll, the first is acceptable and the second should not generally happen because the sidebar disables the runtime tool buttons when it knows there are no active debug sessions.

**Comment by DanTup** [comment]
Another minor consequence of this is that trying to launch the static tool _while a debug session is start_ will result in this:

![image](https://github.com/user-attachments/assets/170fe970-70d6-4617-97cb-2459ed30e916)

Because with `prefersDebugSession` we will select the debug session but can't proceed if we don't have the VM Service URI yet. I think this is an edge case we'll have to life with (once the flags are set explicitly, this is all moot).

**Comment by DanTup** [comment]
With this fix, all the buttons in the sidebar seem to work as we would expect (using current Flutter beta, and the current extension code from master which which will ship in todays release).

**Comment by kenzieschmoll** [comment]
> Another minor consequence of this is that trying to launch the static tool _while a debug session is start_ will result in this:
> 
> ![image](https://private-user-images.githubusercontent.com/1078012/354176742-170fe970-70d6-4617-97cb-2459ed30e916.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MjcyMjQsIm5iZiI6MTcyMjUyNjkyNCwicGF0aCI6Ii8xMDc4MDEyLzM1NDE3Njc0Mi0xNzBmZTk3MC03MGQ2LTQ2MTctOTdjYi0yNDU5ZWQzMGU5MTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDFUMTU0MjA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmI5Yzg4NThjZDkxMmQ3Yjc0MzZjZDNkYWI0MTIyZjBlNWJiNDc3OGQwNzIyNzA5MDY2MjdlNGY4YjJjMWQ0YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Hy2Tojx7sHLtgv5bOIVPav7QxBlsflayzLnmi_uMHKU)
> 
> Because with `prefersDebugSession` we will select the debug session but can't proceed if we don't have the VM Service URI yet. I think this is an edge case we'll have to life with (once the flags are set explicitly, this is all moot).

It seems like we should still launch the tool as if there are no debug sessions even when there is one that is in the process of stating up.

**Comment by DanTup** [comment]
> It seems like we should still launch the tool as if there are no debug sessions even when there is one that is in the process of stating up.

I feel like this could be unexpected or confusing. To users it might not be clear that when they start a debug session there is some time (eg. compilation) where we can't access the VM Service URI. If they start a debug session and then while it's building try to open something like CPU Profiler ready (or expect to profile startup), we would open an unconnected version of it without any obvious way to connect it to their app once it loads.

I think if they're trying to open a tool while a debug session is starting, then probably they're expecting to use it for that debug session?
