### ISSUE TITLE
Unable to copy using buttons in DevTools

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#5209]
Reported by @kenzieschmoll at https://github.com/Dart-Code/Dart-Code/issues/4540#issuecomment-2260923319

Seeing this issue again when trying to call `Clipboard.setData` from DevTools, which falls back to calling the VS Code workaround
```
  window.parent?.postMessage(
    {
      'command': 'clipboard-write',
      'data': data,
    }.jsify(),
    '*'.toJS,
  );
```
which also fails:
```
copy is not successful NotAllowedError: Failed to execute 'writeText' on 'Clipboard': Document is not focused.
main.dart.js:50566 Copy failed. This may be as a result of a known bug in VS Code. See https://github.com/Dart-Code/Dart-Code/issues/4540 for more information. Now attempting to use a fallback method of copying the that is a workaround for VS Code only.
VM7:49 Uncaught (in promise) DOMException: Failed to execute 'writeText' on 'Clipboard': Document is not focused.
    at <anonymous>:49:24
```

**Comment by DanTup** [comment]
@kenzieschmoll I don't seem to be able to repro this on Windows or Mac - can you confirm if these are the same steps you're doing?

I click in the text editor and copy some text so we know this editor has focus. Then I click directly on the Copy button in DevTools. Then I paste back into the editor and the text appears to have been copied correctly.

https://github.com/user-attachments/assets/dcb2f690-3024-40b8-ae98-31a6448e06ea

**Comment by DanTup** [comment]
I see we do still write a warning to indicate we're using the fallback, but there's no error from using that for me.

![Screenshot 2024-08-01 at 11 40 45](https://github.com/user-attachments/assets/4f5fec30-1a7b-43c8-a633-41d8c358f198)

I'm on latest stable VS Code (on both PC + Mac) and latest Flutter beta (`3.24.0-0.2.pre`).

**Comment by kenzieschmoll** [comment]
In your video, where is the text coming from that is getting pasted? this doesn't appear to be from DevTools. I would have expected the pasted output to be "flutter: test" if the copy was successful from DevTools.

**Comment by DanTup** [comment]
@kenzieschmoll "flutter: test" is what is pasted, although it has a newline on the end so the remainder of the comment after the word I pasted over gets pushed onto the next line.

**Comment by DanTup** [comment]
@kenzieschmoll can you still repro this? Do you have precise steps I can try (I presume on macOS?)

**Comment by DanTup** [comment]
@kenzieschmoll can you still repro this and get precise steps?
