### ISSUE TITLE
Unnecessary closing labels appearing

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#521]
@devoncarew I've seen a couple of instances of labels where I don't think they should be recently (including a couple during Matt & Emily's flutter demo at DartConf). I'll try and add examples I can find here and we can review at some point to see if we can improve the rules.

<img width="708" alt="screen shot 2018-02-02 at 13 31 40" src="https://user-images.githubusercontent.com/1078012/35735683-84dbf770-081d-11e8-8e02-de919819407e.png">

**Comment by devoncarew** [comment]
Sounds good! We tweaked the heuristics for it. I believe that currently:
- it only displays if there are at least two widgets
- we don't display labels for items that start and end on the same line

For the above, you're thinking of doing something like requiring a greater spread in the start and end lines?

**Comment by DanTup** [comment]
Yeah, I think so. I thought we already had a threshold so it didn't do adjacent lines but it's been a while. I'll review the DartConf video soon and see whether it was the same thing there that looked weird and get screenshots and then propose some changes.

**Comment by DanTup** [comment]
Possibly even two lines apart is overkill? I think AppBar here may be unwanted?

<img width="694" alt="screen shot 2018-02-02 at 16 42 19" src="https://user-images.githubusercontent.com/1078012/35744375-1f5749de-0838-11e8-9f16-c969a1e2a8a7.png">

And ThemeData?

<img width="501" alt="screen shot 2018-02-02 at 16 43 15" src="https://user-images.githubusercontent.com/1078012/35744428-4259a9ea-0838-11e8-8837-4d77f32b999d.png">

And setState?

<img width="218" alt="screen shot 2018-02-02 at 16 44 19" src="https://user-images.githubusercontent.com/1078012/35744466-5a891e7e-0838-11e8-967c-db29e5a30be3.png">

And then? (I'm sensing maybe all the ones I don't like are the same kinda thing!)

<img width="286" alt="screen shot 2018-02-02 at 16 47 06" src="https://user-images.githubusercontent.com/1078012/35744638-c3964b4e-0838-11e8-98ef-91c0a52a9353.png">


Possibly it's not as simple as just counting the lines between though, as I suspect we can find examples where they are useful like that - we might need to consider other factors?

**Comment by devoncarew** [comment]
I don't think `then` should be showing up - I'd thought we'd removed the method contributions. I could be misremembering?

**Comment by devoncarew** [comment]
(/cc @bwilkerson for closing label ux)

**Comment by DanTup** [comment]
@devoncarew possibly the line numbers changed here:

https://github.com/dart-lang/sdk/commit/6a19e794b1136da58c855ace4663f9455be112ba#diff-1048ea126d724ec4762a4a2619eb3e42L28-L32

Used to have ` .where((l) => l.any((cl) => cl.spannedLines >= 2))` but after changes is `if (spannedLines < 1) return;` - not sure if that was delivery or a mistake during the changes.

Looks like methods invocations were removed here:

https://github.com/dart-lang/sdk/commit/fd4528fffbb6c0652505077332caf6d87cd115ad#diff-1048ea126d724ec4762a4a2619eb3e42L80

IIRC they were using a fairly old version of Flutter for their demo on stage, so my guess is that those last few are actually already fixed (I think I discussed this with Matt on twitter and then forgot when I was grabbing those screenshots earlier!).

**Comment by DanTup** [comment]
I deleted the screenshots from the demo as I think they're all out of date and misleading. I think the original issue at the top is the result of the `spannedLines` change mentioned in the comment above. If you think this was a mistake it should be as easy fix (`if (spannedLines < 2)`) though if it was because the labels were not appearing somewhere they should, it might need more thought!

**Comment by devoncarew** [comment]
> not sure if that was delivery or a mistake during the changes

We were iterating on the look a bunch locally; I'm not sure the removal of `spannedLines < 2` was _fully_ intentional, but may have been an effort to balance having closing labels be too verbose and providing consistency about where and when we display closing labels (so its easy to reason about for users).

I think we could add back in a filter at `List<ClosingLabel> compute()` for labels that span less than 2 lines, and see how that looks locally; if it's a general improvement - labels are less noisy but still easy to reason about for the user in terms of when they appear.

**Comment by DanTup** [comment]
I can make that change locally here and test it, but since it seemed ok to me that way originally I'm not sure that's enough to make a call - it might be better you tweaking it and reviewing in the way you did previously (Dart Code does support running the analyzer from source for easy testing (`dart.analyzerPath` should be a path to `pkg/analysis_server/bin/server.dart`)?

FWIW, I don't feel strongly about changing this - it seems unnecessary in the screenshot at the top but if we can't fix that without negatively impacting something else (or making it harder for the user to understand) it may be better this way.

**Comment by DanTup** [comment]
Closing this since nobody has complained about this and I'm kinda used to it now. It should probably also be raised in the SDK repo for discussion if there are any requests to review it.
