### ISSUE TITLE
Go to file keyboard binding doesn't work

### ISSUE THREAD

**Issue by akshaybabloo** [Dart-Code/Dart-Code#5212]
**Describe the bug**

When in a `*.dart` file, doing <kbd>Ctrl</kbd>+<kbd>P</kbd> doesn't seem to work.

**To Reproduce**

1. Open a `*.dart` file
2. From your keyboard, do - <kbd>Ctrl</kbd>+<kbd>P</kbd> 

**Expected behavior**

It should open a pop-up to search by file name

**Screenshots**

N/A

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

- VSCode information
    ```
    Version: 1.92.0 (user setup)
    Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
    Date: 2024-07-31T23:26:45.634Z
    Electron: 30.1.2
    ElectronBuildId: 9870757
    Chromium: 124.0.6367.243
    Node.js: 20.14.0
    V8: 12.4.254.20-electron.0
    OS: Windows_NT x64 10.0.19045
    ```
- Dart extension version: v3.94.0
- Dart/Flutter SDK version: Dart 3.4.4/Flutter 3.22.3

**Comment by DanTup** [comment]
I'm afraid I can't reproduce this:

https://github.com/user-attachments/assets/fa7ceb5e-2d09-4eb5-b3fb-f1877322c676

Do you definitely have something like a Dart file focused and not something else (for example DevTools with an embedded webview requires some workarounds for this to work).

If it really is a Dart file, I would check your keybindings to see if there is anything obviously wrong there. When an editor has focus and you press Ctrl+P, there is no involvement of the Dart extension, the keybinding is handled entirely by VS Code.

**Comment by akshaybabloo** [comment]
Found the issue. A different package was using it, removed it. All good now.
