### ISSUE TITLE
ui guide not working in android studio

### ISSUE THREAD

**Issue by juwowa09** [Dart-Code/Dart-Code#5214]
ui guide doesn't seem to be working fine in Android studio. It seems to work fine in vscode, but did I miss some setup in Androys studio..?

1. in android studio
<img width="958" alt="image" src="https://github.com/user-attachments/assets/f13492e0-2dff-4c8b-9d37-454e1fad4f76">
<img width="528" alt="스크린샷 2024-08-03 오전 12 33 25" src="https://github.com/user-attachments/assets/400f4e68-d5c8-4eec-8b14-379d30a6f159">

2. vscode
<img width="347" alt="image" src="https://github.com/user-attachments/assets/b1779309-4e25-41df-901a-4ad44be32777">

**Comment by DanTup** [comment]
This repository is only for the VS Code extension - the one for the IntelliJ/Android Studio extension is https://github.com/flutter/flutter-intellij. Please file the issue there. Thanks!
