### ISSUE TITLE
Possibility to filter internal debug log

### ISSUE THREAD

**Issue by SamuelGadiel** [Dart-Code/Dart-Code#5215]
Is it possible to filter this log in the VSCode?

![image](https://github.com/user-attachments/assets/ee7f6de4-a303-4f57-8ee3-0f074c5abc77)

Currently I add them to the debug filter, but this raises some other problems
Don't seem to be the best solution.
Is there any settings or parameter I can define to hide these internal logs?

**To Reproduce**
Run a Flutter project with the VSCode debugger.

**Expected behavior**
Only show the I/flutter information, which contains the desired log

![image](https://github.com/user-attachments/assets/9e8c5553-316a-4bb4-af73-7d56a4e7816f)

**Additional information:**

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.94.0
Flutter extension: 3.94.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: mac 1.92.0

Workspace type: Flutter (LSP)
Workspace name: b2b_app

Dart (3.4.4): /Users/samuelavila/fvm/versions/3.22.3/bin/cache/dart-sdk
Flutter (3.22.3): /Users/samuelavila/fvm/versions/3.22.3 (sdk gphone64 x86 64 (android-x64/android))

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`/Users/samuelavila/fvm/versions/3.22.3/bin/cache/dart-sdk/bin/dart info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.4.4 (stable) (Wed Jun 12 15:54:31 2024 +0000) on "macos_x64"
- on macos / Version 13.6.1 (Build 22G313)
- locale is pt-BR

#### Project info

- sdk constraint: '^3.4.4'
- dependencies: cached_network_image, collection, crypto, flutter, flutter_html, flutter_localizations, flutter_modular, flutter_svg, icons_plus, intl, package_info_plus, url_launcher
- dev_dependencies: flutter_launcher_icons, flutter_test, rename
- elided dependencies: 2

#### Process info

| Memory |  CPU | Elapsed time | Command line                                                                               |
| -----: | ---: | -----------: | ------------------------------------------------------------------------------------------ |
|  18 MB | 0.0% |     02:18:47 | dart devtools --machine --allow-embedding                                                  |
|  21 MB | 0.0% |     02:18:41 | dart devtools --machine --allow-embedding --dtd-uri ws:<path>/BxfyhqmH074QixA1             |
|  19 MB | 0.0% |     02:18:42 | dart devtools --machine --allow-embedding --dtd-uri ws:<path>/lHpHRNk7gJqwfox1             |
|  42 MB | 0.0% |     02:18:47 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.94.0            |
|  56 MB | 0.0% |     02:18:46 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.94.0            |
|  73 MB | 0.0% |     02:18:44 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.94.0            |
|  20 MB | 0.0% |     02:19:53 | dart tooling-daemon --machine                                                              |
|  21 MB | 0.0% |     02:18:46 | dart tooling-daemon --machine                                                              |
|  21 MB | 0.0% |     02:18:44 | dart tooling-daemon --machine                                                              |
|  40 MB | 0.0% |     02:18:47 | flutter_tools.snapshot daemon                                                              |
|  58 MB | 0.0% |     02:18:46 | flutter_tools.snapshot daemon                                                              |
|  41 MB | 0.0% |     02:18:44 | flutter_tools.snapshot daemon                                                              |
|  25 MB | 0.0% |     02:07:33 | flutter_tools.snapshot debug_adapter                                                       |
|  52 MB | 0.0% |     02:07:33 | flutter_tools.snapshot run --machine --start-paused -d emulator-5554 --devtools-server-address http:<path>/ --target <path>/main.dart |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`/Users/samuelavila/fvm/versions/3.22.3/bin/flutter doctor -v`

```text
[!] Flutter (Channel stable, 3.22.3, on macOS 13.6.1 22G313 darwin-x64, locale pt-BR)
    • Flutter version 3.22.3 on channel stable at /Users/samuelavila/fvm/versions/3.22.3
    ! Warning: `flutter` on your path resolves to /Users/samuelavila/fvm/versions/3.22.0/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/samuelavila/fvm/versions/3.22.3. Consider adding /Users/samuelavila/fvm/versions/3.22.3/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/samuelavila/fvm/versions/3.22.0/bin/dart, which is not inside your current Flutter SDK checkout at /Users/samuelavila/fvm/versions/3.22.3. Consider adding /Users/samuelavila/fvm/versions/3.22.3/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (3 weeks ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/samuelavila/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] IntelliJ IDEA Community Edition (version 2023.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.92.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 15 (API 35) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • macOS 13.6.1 22G313 darwin-x64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 127.0.6533.89

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by DanTup** [comment]
Unfortunately this isn't currently possible. There are some existing related issues:

- https://github.com/flutter/flutter/issues/120711
- https://github.com/Dart-Code/Dart-Code/issues/4391
- https://github.com/flutter/devtools/issues/5259

I'll close this as a dupe since we have https://github.com/Dart-Code/Dart-Code/issues/4391, but my feeling is that this should be supported by Flutter itself (rather than filtering it out in the client). Although, I'm also not completely sure if the existing filtering works correctly (for ex. see https://github.com/flutter/flutter/issues/120711#issuecomment-1467157182).
