### ISSUE TITLE
Flutter daemon left orphaned after IDE was closed

### ISSUE THREAD

**Issue by FMorschel** [Dart-Code/Dart-Code#5216]
Following up on https://github.com/Dart-Code/Dart-Code/issues/5155.

It happened again on that exact project I was working on. Both of the times I realized something was weird when debugging from inside the IDE was buggy in some way. 

The first case happened after opening the project, trying to debug but after getting the "Starting debugging session" message, nothing seemed to happen for way longer than usual. I then double-clicked the terminate button and after waiting for also way longer then I would, I saw the "Exited" message on the Debug console.

[Logs zip](https://quickshare.samsungcloud.com/wdylZvJSsiyc)

For the second case, after restarting the IDE from the first case I was able to sebug everything normally. After some time, while no other session was running I ran `flutter run --profile` on the terminal. After I was done with the profile mode review, I quitted the process there and tried to run a new debug session on my IDE. The blue loading bar would show at the top of the debug side tab and the buttons for debugging would appear but only with "restart" and "terminate" being active. Not even an indication like the above "Starting debugging session" message, nothing. I then closed the IDE and there was another daemon left there.

[Logs zip](https://quickshare.samsungcloud.com/8MFGnXbb0Yyw)

---

### P.S.

First, the logs are complete, so they have a limit of time to download. If you ever get to this and need the logs again, please ask so I can reupload them or send them via email or something.

My thoughts on the first case: Maybe there is something not being linked correctly in the daemon and my project has something that activates it (recently I worked on a newer project and had no problems like this).

My thoughts on the second case: maybe after the daemon couldn't be closed it was still trying to communicate with it but something was missing? Not sure what the daemon does, just a guess.

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.95.20240801
Flutter extension: 3.95.20240801 (activated)

App: Visual Studio Code
App Host: desktop
Version: win 1.92.0

Workspace type: Flutter (LSP)
Workspace name: wms_sunsoft

Dart (3.3.4): C:\Users\felip_0vh5fa6\.puro\shared\caches\c4cd48e186460b32d44585ce3c103271ab676355\dart-sdk
Flutter (3.19.6): C:\Users\felip_0vh5fa6\.puro\envs\wms\flutter (PM451 (android-arm64/android))

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`C:\Users\felip_0vh5fa6\.puro\shared\caches\c4cd48e186460b32d44585ce3c103271ab676355\dart-sdk\bin\dart.exe info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.3.4 (stable) (Tue Apr 16 19:56:12 2024 +0000) on "windows_x64"
- on windows / "Windows 10 Pro" 10.0 (Build 22631)
- locale is pt-BR

#### Project info

- sdk constraint: '>=3.0.0 <4.0.0'
- dependencies: async, bloc, cloud_firestore, collection, equatable, expandable_page_view, firebase_analytics, firebase_auth, firebase_core, firebase_crashlytics, firebase_messaging, firebase_remote_config, flutter, flutter_easyloading, flutter_localizations, flutter_offline, flutter_signin_button, flutter_spinkit, google_sign_in, grouped_list, intl, logging, material_design_icons_flutter, provider, shared_preferences, soundpool, time, url_launcher, validators
- dev_dependencies: dart_code_metrics, flutter_launcher_icons, flutter_lints, flutter_test, linter
- elided dependencies: 14

#### Process info

| Memory | CPU | Elapsed time | Command line |
| -----: | --: | -----------: | ------------ |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`C:\Users\felip_0vh5fa6\.puro\envs\wms\flutter\bin\flutter.bat doctor -v`

```text
[!] Flutter (Channel stable, 3.19.6, on Microsoft Windows [Version 10.0.22631.3880], locale pt-BR)
    • Flutter version 3.19.6 on channel stable at C:\Users\felip_0vh5fa6\.puro\envs\wms\flutter
    ! Warning: `flutter` on your path resolves to C:\Users\felip_0vh5fa6\.puro\envs\stable\flutter\bin\flutter, which is not inside your current Flutter SDK checkout at C:\Users\felip_0vh5fa6\.puro\envs\wms\flutter. Consider adding C:\Users\felip_0vh5fa6\.puro\envs\wms\flutter\bin to the front of your path.
    ! Warning: `dart` on your path resolves to C:\Users\felip_0vh5fa6\.puro\envs\stable\flutter\bin\dart, which is not inside your current Flutter SDK checkout at C:\Users\felip_0vh5fa6\.puro\envs\wms\flutter. Consider adding C:\Users\felip_0vh5fa6\.puro\envs\wms\flutter\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (4 months ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\felip_0vh5fa6\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Users\felip_0vh5fa6\AppData\Local\Programs\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.10.35122.118
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2024.1)
    • Android Studio at C:\Users\felip_0vh5fa6\AppData\Local\Programs\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)

[√] VS Code (version 1.92.0)
    • VS Code at C:\Users\felip_0vh5fa6\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.92.0

[√] VS Code (version 1.88.0-insider)
    • VS Code at C:\Users\felip_0vh5fa6\AppData\Local\Programs\Microsoft VS Code Insiders
    • Flutter extension version 3.64.0

[√] Connected device (4 available)
    • PM451 (mobile)    • 2131310644 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.22631.3880]
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 127.0.6533.89
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 126.0.2592.102

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by DanTup** [comment]
Thanks for the logs. There's not much in the Dart-Code logs, but I think I know why - I think the extension host is either crashing, or becoming unresponsive (and therefore not running any more code). The VS Code logs are full of messages about forcefully terminating the extension host (which means none of our cleanup code will run):

![image](https://github.com/user-attachments/assets/f1e35150-4758-4abe-8538-9745d9f09da0)

Based on the comment in the VS Code code here:

https://github.com/microsoft/vscode/blob/559107b7a92be2cfda116e3a0667f1b1ac9bf78b/src/vs/platform/extensions/electron-main/extensionHostStarter.ts#L85

It could be something like an infinite loop, although I also see this:

```
2024-08-06 13:19:39.559 [info] Extension host (LocalProcess pid: 165072) is unresponsive.
2024-08-06 13:19:42.038 [info] UNRESPONSIVE extension host: starting to profile NOW
2024-08-06 13:19:42.287 [info] Extension host (LocalProcess pid: 165072) is responsive.
2024-08-06 13:19:42.288 [info] UNRESPONSIVE extension host: received responsive event and cancelling profiling session
2024-08-06 13:19:49.562 [info] Extension host (LocalProcess pid: 165072) is unresponsive.
2024-08-06 13:19:54.533 [info] UNRESPONSIVE extension host: starting to profile NOW
2024-08-06 13:20:03.487 [info] Extension host (LocalProcess pid: 165072) is responsive.
2024-08-06 13:20:08.295 [error] [Extension Host] (node:165072) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
2024-08-06 13:20:12.615 [info] Extension host (LocalProcess pid: 165072) is unresponsive.
2024-08-06 13:20:15.871 [info] UNRESPONSIVE extension host: starting to profile NOW
2024-08-06 13:20:23.661 [error] Error: Aborted onWillSaveTextDocument-event after 1750ms
```

This looks like the extension host become unresponsive, then as VS Code starts to profile it, it responds and the profiling is cancelled. It's not clear to me if these things are related or not though. One thing that could be worth doing the next time you see something acting odd, is to profile the extension host (based on the log, even if it's stopping/starting, it seems like it continues to occur). There are instructions here:

https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions

This will help identify what code is running during the periods where the extension host is not responsive.

**Comment by FMorschel** [comment]
Will do. 

Just one thing so I'm certain I'm getting this right. This profiling of the extension host process, what will it get exactly, that could help?

- Say it is an infinite loop, will it show us something about it while it is there? 
- What if it is not exactly that but an async process with no timeout that never returns or something like that?
- Or any other strange thing that is causing this behaviour.

I'm more concerned with "when" to start recording with the extension profiling tool to help. In the first case I presented above, I only knew it was bad after waiting for several minutes for my debug session to start and trying to terminate it was not working so would it help? Since I can't even terminate the session to start a new one and "reproduce" what caused the problem.

**Comment by DanTup** [comment]
> This profiling of the extension host process, what will it get exactly, that could help?

It will give us data about what javascript code is executing inside the extension host. However, I'm not sure if it requires executing any code in the extension host to start/stop profiling. If it does, then capturing an infinite loop might be hard, however the logs suggest that something might be using lots of CPU without being in a loop (and _maybe_ they are related).

> What if it is not exactly that but an async process with no timeout that never returns or something like that?

This would not result in an unresponsive extension host. If something is async, it is not tying up the (single) thread, and VS Code's heartbeat (which I presume it's using to detect responsiveness) would continue to beat. It would only be synchronous code (eg. a long-running loop) or synchronous blocking (eg. reading a file from disk using sync APIs) that would trigger this.


> I'm more concerned with "when" to start recording with the extension profiling tool to help

Yeah, unfortunately it will be hard. But, based on the log it seems that when this happens, VS Code often terminates the extension host and starts another, and then it happens again (there are a few close together in the log snippet above), so it's possible if you see weird behaviour and start profiling, _maybe_ you'll capture it. Unfortunately it's not guaranteed, but I don't have many other suggests currently (besides filing a VS Code issue asking for better help in tracking down a terminating extension host like this).

**Comment by FMorschel** [comment]
Okay, I will try and do that. If it doesn't show us anything on the first go, I can start recording every time I _begin_ a new debug session (harder to remember) while also creating an issue there asking for help. If everything works just fine when starting the debug session I can simply discard the recording.

**Comment by FMorschel** [comment]
Here it is:

PID 12556 - https://quickshare.samsungcloud.com/ppy2PEKZLdQa

Inside this zip file, there is the profiling with 10 seconds of duration after I started a debug session that would never start nor terminate.

**Comment by DanTup** [comment]
The CPU profile appears to show something spawning processes constantly, which may be consuming a large amount of CPU:

![image](https://github.com/user-attachments/assets/431bef9e-f4f5-4dd7-9ebe-48f10dd0ec43)

However because the CPU profiles have all file paths stripped, it's hard to tell what it is - but there is an `svn.js` in there and I see you have two SVN-related extensions installed. I would try running running `code --status` from the terminal and see if you can figure out which svn extension is constantly spawning processes, then I would try disabling it for a while and see whether it stops the extension host from crashing or becoming unresponsive.

**Comment by DanTup** [comment]
I downloaded `eliean.vscode-svn` and the stack traces match up with the `svn-spawn` library it is using, so I would try disabling that for a bit.

My guess is that it's running an SVN command to check the status very frequently (I can see it does it on a file watcher, although it's not clear to me why files on your disk could be changing constantly like that). I don't know if it's customisable, but the repository linked from https://marketplace.visualstudio.com/items?itemName=eliean.vscode-svn seems to be a 404 now, so I can't locate the issue tracker.

**Comment by FMorschel** [comment]
Thank you a lot! Will try that and let you know.

**Comment by FMorschel** [comment]
It does seem like this was finally solved! Thanks a lot for your help! Do you think I should create an issue under vscode so they could maybe do something about it? Like detecting in some way all of those spawns or anything to try and mitigate this? Or would this not be something they could handle? 

Whenever you answer here you can close this issue. Just left it open while waiting for this response.

**Comment by DanTup** [comment]
> Do you think I should create an issue under vscode so they could maybe do something about it? Like detecting in some way all of those spawns or anything to try and mitigate this? Or would this not be something they could handle?

I suspect they wouldn't do this just because there's nothing inherently wrong with spawning lots of processes if they're quick and don't consumer vast amounts of CPU. They do already have things to detect this _kind_ of issue by detecting an unresponsive extension host and taking a profile, however it seems like this extension was doing small expensive spikes that were short enough to not trigger that, but still enough to cause problems. Maybe they could do something more, but I'm not sure.

I would probably file an issue against the SVN extension about the issue though, maybe there is room for optimizing the status checks that were causing this.

I'll close this since there's nothing to do here, but I'll still get notifications of comments here if there's more discussion to be had.
