### ISSUE TITLE
Move to file not moving to existing file even after agreeing to replace it

### ISSUE THREAD

**Issue by FMorschel** [Dart-Code/Dart-Code#5218]
With this code sample:

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MaterialApp(home: Home()));

class Home extends StatefulWidget {
  const Home({super.key});

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  Widget build(BuildContext context) {
    return const Scaffold();
  }
}
```

Place the cursor under either `Home` or `_HomeState` and with the quick-fix to "Move [it] to file" move it to a new file say `a.dart`.

After that, place the cursor in the second class and do the same (same file). It will (currently) tell you that the file already exists and ask if you want to replace it. After pressing "yes", it does nothing.

[logs.zip](https://github.com/user-attachments/files/16522994/logs.zip)

**Comment by DanTup** [comment]
I don't seem to be able to reproduce this, however in the log you provided I see a suspicious error just after the attempt to do the refactor:

```
1723028564646:Req:{"jsonrpc"::"2.0","id"::117,"method"::"workspace/executeCommand","params"::{"command"::"dart.refactor.move_top_level_to_file","arguments"::[{"filePath"::"C::\\Users\\felip_0vh5fa6\\Documents\\Projects\\flutter\\bug\\lib\\main.dart","selectionOffset"::107,"selectionLength"::0,"arguments"::["file::///c%3A/Users/felip_0vh5fa6/Documents/Projects/flutter/bug/lib/home.dart"]}]},"clientRequestTime"::1723028564625}
1723028564651:Res:{"id"::13,"jsonrpc"::"2.0","method"::"window/workDoneProgress/create","params"::{"token"::"ANALYZING"}}
1723028564677:Ex:Exception while using a EolAtEndOfFile to visit a CompilationUnitImpl
PathNotFoundException(path=c::\Users\felip_0vh5fa6\Documents\Projects\flutter\bug\lib\home.dart; message=Cannot retrieve modification time)
#0      _PhysicalFile.modificationStamp (package::analyzer/file_system/physical_file_system.dart::124::7)
#1      _OverlayFile.modificationStamp (package::analyzer/file_system/overlay_file_system.dart::149::18)
#2      FileSource.contentsFromFile (package::analyzer/source/file_source.dart::67::12)
#3      FileSource.contents (package::analyzer/source/file_source.dart::54::12)
#4      _Visitor.visitCompilationUnit (package::linter/src/rules/eol_at_end_of_file.dart::60::48)
#5      CompilationUnitImpl.accept (package::analyzer/src/dart/ast/ast.dart::3607::50)
#6      LinterVisitor._runSubscriptions (package::analyzer/src/lint/linter_visitor.dart::1096::14)
#7      LinterVisitor.visitCompilationUnit (package::analyzer/src/lint/linter_visitor.dart::188::5)
#8      CompilationUnitImpl.accept (package::analyzer/src/dart/ast/ast.dart::3607::50)
#9      LibraryAnalyzer._computeLints (package::analyzer/src/dart/analysis/library_analyzer.dart::398::12)
#10     LibraryAnalyzer._computeDiagnostics (package::analyzer/src/dart/analysis/library_analyzer.dart::323::7)
#11     LibraryAnalyzer.analyze (package::analyzer/src/dart/analysis/library_analyzer.dart::108::5)
#12     AnalysisDriver._analyzeFileImpl.<anonymous closure> (package::analyzer/src/dart/analysis/driver.dart::1394::11)
```

From the error, I was thinking maybe the destination file you'd picked was empty or just a newline or something, however I can't reproduce like that.

Can you confirm what's in your `a.dart`? (trailing newlines etc. may be significant).

Can you also confirm the exact version of the SDK you're using? I tried both `master` and `stable`, although stable may have changed since you raised this.

**Comment by FMorschel** [comment]
Tested today with version 3.5.0.

I also thought it might be because when moving either `Home` or `_HomeState` one of them has an error because of the private class but in the same file I added both `class A{}` and `class B{}` and once Ive moved one, the second could not be moved.

Tested moving `class A{}` first and the only line inside the new file is that one. Not even an import since nothing is needed.

Do you need any other log for tracking this?

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.95.20240821
Flutter extension: 3.95.20240801 (activated)

App: Visual Studio Code
App Host: desktop
Version: win 1.92.2

Workspace type: Flutter (LSP)
Workspace name: bug

Dart (3.5.0): C:\Users\felip_0vh5fa6\.puro\shared\caches\b8800d88be4866db1b15f8b954ab2573bba9960f\dart-sdk
Flutter (3.24.0): C:\Users\felip_0vh5fa6\.puro\envs\stable\flutter (Windows (windows-x64/windows))

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`C:\Users\felip_0vh5fa6\.puro\shared\caches\b8800d88be4866db1b15f8b954ab2573bba9960f\dart-sdk\bin\dart.exe info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.5.0 (stable) (Tue Jul 30 02:17:59 2024 -0700) on "windows_x64"
- on windows / "Windows 10 Pro" 10.0 (Build 22631)
- locale is pt-BR

#### Project info

- sdk constraint: '>=3.0.0 <4.0.0'
- dependencies: drift, drift_flutter, flutter
- dev_dependencies: build_runner, drift_dev, flutter_lints

#### Process info

| Memory | CPU | Elapsed time | Command line |
| -----: | --: | -----------: | ------------ |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`C:\Users\felip_0vh5fa6\.puro\envs\stable\flutter\bin\flutter.bat doctor -v`

```text
[√] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.22631.4037], locale pt-BR)
    • Flutter version 3.24.0 on channel stable at C:\Users\felip_0vh5fa6\.puro\envs\stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (3 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\felip_0vh5fa6\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Users\felip_0vh5fa6\AppData\Local\Programs\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.10.35201.131
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2024.1)
    • Android Studio at C:\Users\felip_0vh5fa6\AppData\Local\Programs\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)

[√] VS Code (version 1.92.2)
    • VS Code at C:\Users\felip_0vh5fa6\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.92.0

[√] VS Code (version 1.88.0-insider)
    • VS Code at C:\Users\felip_0vh5fa6\AppData\Local\Programs\Microsoft VS Code Insiders
    • Flutter extension version 3.64.0

[√] Connected device (4 available)
    • SM G780F (mobile) • 192.168.200.50:43987 • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows              • windows-x64    • Microsoft Windows [Version 10.0.22631.4037]
    • Chrome (web)      • chrome               • web-javascript • Google Chrome 127.0.6533.120
    • Edge (web)        • edge                 • web-javascript • Microsoft Edge 126.0.2592.102

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by DanTup** [comment]
@FMorschel are you able to get a folder into the state where this can be repro'd and zip up the folder and attach it here? I tried enabling that lint and putting a single line in so I had the diagnostic, but still couldn't repro.

**Comment by FMorschel** [comment]
Yes, [here](https://quickshare.samsungcloud.com/uSfMcHtRNoDD) it is.

**Comment by DanTup** [comment]
That link shows me "Files are still being uploaded by the sender. Tap Refresh to check when they're ready to download." though since you commented 2 hours ago, I'm a little suspicious that something may have gone wrong?

**Comment by FMorschel** [comment]
Yep, something does seem to be wrong. Is there an email where I can send this to you or something? 831MB can't be uploaded here.

**Comment by DanTup** [comment]
831MB? Is this just the new sample project above? If so, you can delete folders like `build/` and `.dart_tool/` so it should be quite small - it's only really the `.dart`, `pubspec`. `analysis_options` I was after.

**Comment by FMorschel** [comment]
Yep, my build folder was really big because I~d built for windows, web and android from this project already. 

All of the Flutter folders for those builds were deleted here as well since you can run 'dart create .'

[bug.zip](https://github.com/user-attachments/files/16714147/bug.zip)

**Comment by DanTup** [comment]
Can you confirm the steps you're taking with this? I opened your project, accepted the request to run `pub get` to fix all the squiggles, then tried to move `B` into `a.dart`, but it didn't fail (and I don't get the same error in the log):

https://github.com/user-attachments/assets/ee10c423-c689-454f-b852-b685fee60da1

I tried both with `master` and 3.24.1. There was a short delay if I did it right after opening the project, but it still always occurred.

Is there anything else you can think that might differ between our projects? Does it repro for you if you start from the downloaded zip?

**Comment by FMorschel** [comment]
After using the downloaded zip and running `flutter create .`. When I do select to move `B` it does take some seconds but it completes. Before it would not do that. Not sure what to look for here. If you think this should be closed then by all means, do so. 

This bug occurred when I was creating a repro for https://github.com/dart-lang/sdk/issues/56392. I guess it could be a one-off. This was a fairly old project in my machine, so maybe something broke (as the zip name suggests, I use this project to test if what I found is a bug or is something I've done wrong).

**Comment by FMorschel** [comment]
Wait. Could there be an indication for the running process somewhere? So that IF I was simply not waiting long enough that could be seen?

**Comment by FMorschel** [comment]
Hey. Just tested it. I can get a video in a second. Please:

- Move `A` to `main.dart` manually. 
- Reopen the project folder.
- Move `A` to `a.dart` with the quick-fix.
- Try to move `B` to that same file without reopening the IDE.

For me I have done that and I've been waiting for like four minutes now for it to move `B`. Nothing.

**Comment by FMorschel** [comment]
https://github.com/user-attachments/assets/4b2c3d28-1133-4f66-a151-d098d2e8e500

Here it is. And if `a.dart` already exists when I open my project folder, that works without issue.

[logs.zip](https://github.com/user-attachments/files/16714753/logs.zip)

**Comment by FMorschel** [comment]
If there is any other log I could fetch to help please let me know. We could probably also add a new issue after this to tell the user when the operation is running and if it failed anyway. That would help to narrow down these errors a bit, I believe.

> if for no other reason than to be given a _reason_ when this happens

Yes, I believe this issue should be created anyway.

**Comment by DanTup** [comment]
Ok, I went through the log in detail and annotated it:

```


# Client opens main.dart, version 1
==> {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///C%3A/Users/felip_0vh5fa6/Documents/Projects/flutter/bug/lib/main.dart","languageId":"dart","version":1,"text":"import 'package:flutter/material.dart';\nimport 'ext.dart';\n\nvoid main() => runApp(const MaterialApp(home: Home()));\n\nclass Home extends StatefulWidget {\n  const Home({super.key});\n\n  @override\n  State<Home> createState() => _HomeState();\n}\n\nclass _HomeState extends State<Home> {\n  List<int> i = [];\n  @override\n  Widget build(BuildContext context) {\n    i.foo<num>();\n    i.bar<Object>();\n    return const Scaffold();\n  }\n}\n\nclass A {}\n\nclass B {}\n\nextension E2<T> on List<T> {\n  List<R> bar<R>() => cast<R>();\n}\n"}},"clientRequestTime":1724342820962}


# Client requests move_top_level_to_file to move class A to file a.dart
==> {"jsonrpc":"2.0","id":33,"method":"workspace/executeCommand","params":{"command":"dart.refactor.move_top_level_to_file","arguments":[{"filePath":"C:\\Users\\felip_0vh5fa6\\Documents\\Projects\\flutter\\bug\\lib\\main.dart","selectionOffset":433,"selectionLength":0,"arguments":["file:///c%3A/Users/felip_0vh5fa6/Documents/Projects/flutter/bug/lib/a.dart"]}]},"clientRequestTime":1724342866705}

    # Server sends applyEdit request that modifies a.dart (version null, unopened) and main.dart (version 1)
    <== {"id":10,"jsonrpc":"2.0","method":"workspace/applyEdit","params":{"edit":{"documentChanges":[{"kind":"create","uri":"file:///c:/Users/felip_0vh5fa6/Documents/Projects/flutter/bug/lib/a.dart"},{"edits":[{"newText":"class A {}\n","range":{"end":{"character":0,"line":0},"start":{"character":0,"line":0}}}],"textDocument":{"uri":"file:///c:/Users/felip_0vh5fa6/Documents/Projects/flutter/bug/lib/a.dart","version":null}},{"edits":[{"newText":"","range":{"end":{"character":0,"line":23},"start":{"character":0,"line":21}}}],"textDocument":{"uri":"file:///C:/Users/felip_0vh5fa6/Documents/Projects/flutter/bug/lib/main.dart","version":1}}]},"label":"dart.refactor.move_top_level_to_file"}}

    # VS Code opens a.dart (previously unopened, now version 1)
    ==> {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///C%3A/Users/felip_0vh5fa6/Documents/Projects/flutter/bug/lib/a.dart","languageId":"dart","version":1,"text":""}},"clientRequestTime":1724342870478}

    # VS Code modifies main.dart (now version 2)
    ==> {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"uri":"file:///C%3A/Users/felip_0vh5fa6/Documents/Projects/flutter/bug/lib/main.dart","version":2},"contentChanges":[{"range":{"start":{"line":21,"character":0},"end":{"line":23,"character":0}},"rangeLength":12,"text":""}]},"clientRequestTime":1724342870490}

    # VS Code modifies a.dart (now version 2)
    ==> {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"uri":"file:///C%3A/Users/felip_0vh5fa6/Documents/Projects/flutter/bug/lib/a.dart","version":2},"contentChanges":[{"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}},"rangeLength":0,"text":"class A {}\r\n"}]},"clientRequestTime":1724342870495}

    # VS Code confirms edits are applied
    ==> {"jsonrpc":"2.0","id":10,"result":{"applied":true},"clientRequestTime":1724342870495}

# Server responds to refactor request
<== {"id":33,"jsonrpc":"2.0","result":null}

# VS Code closes a.dart
==> {"jsonrpc":"2.0","method":"textDocument/didClose","params":{"textDocument":{"uri":"file:///C%3A/Users/felip_0vh5fa6/Documents/Projects/flutter/bug/lib/a.dart"}},"clientRequestTime":1724342871518}

# VS Code re-opens a.dart (still version 2)
==> {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///C%3A/Users/felip_0vh5fa6/Documents/Projects/flutter/bug/lib/a.dart","languageId":"dart","version":2,"text":"class A {}\r\n"}},"clientRequestTime":1724342874843}




# Client requests move_top_level_to_file to move class B to file a.dart
==> {"jsonrpc":"2.0","id":72,"method":"workspace/executeCommand","params":{"command":"dart.refactor.move_top_level_to_file","arguments":[{"filePath":"C:\\Users\\felip_0vh5fa6\\Documents\\Projects\\flutter\\bug\\lib\\main.dart","selectionOffset":433,"selectionLength":0,"arguments":["file:///c%3A/Users/felip_0vh5fa6/Documents/Projects/flutter/bug/lib/a.dart"]}]},"clientRequestTime":1724342885756}

    # Server sends applyEdit request that modifies version null of a.dart, version 2 of main.dart
    <== {"id":20,"jsonrpc":"2.0","method":"workspace/applyEdit","params":{"edit":{"documentChanges":[{"kind":"create","uri":"file:///c:/Users/felip_0vh5fa6/Documents/Projects/flutter/bug/lib/a.dart"},{"edits":[{"newText":"\nclass B {}\n","range":{"end":{"character":12,"line":0},"start":{"character":12,"line":0}}}],"textDocument":{"uri":"file:///c:/Users/felip_0vh5fa6/Documents/Projects/flutter/bug/lib/a.dart","version":null}},{"edits":[{"newText":"","range":{"end":{"character":0,"line":23},"start":{"character":0,"line":21}}}],"textDocument":{"uri":"file:///C:/Users/felip_0vh5fa6/Documents/Projects/flutter/bug/lib/main.dart","version":2}}]},"label":"dart.refactor.move_top_level_to_file"}}

    # VS Code fails to apply
    ==> {"jsonrpc":"2.0","id":20,"result":{"applied":false},"clientRequestTime":1724342885796}

# Server responds to refactor request
<== {"id":72,"jsonrpc":"2.0","result":null}
```

I believe I see the issue. At one point, VS Code closed and re-opened `a.dart`. When closed, it becomes version `null` and when re-opened, it's version `2`. However, when we send the second refactor edit, we try to modify version `null` of `a.dart`:

```js
"textDocument": {
	"uri": "file:///c:/Users/felip_0vh5fa6/Documents/Projects/flutter/bug/lib/a.dart",
	"version": null
}
```

This is incorrect - VS Code has informed us we're working with version 2.

I will try again to repro this, and if not, I'll just review the code to see if I can figure out how this could happen (possibly a race somewhere 🤷‍♂️).

**Comment by DanTup** [comment]
I've opened https://github.com/microsoft/vscode/issues/226746 about getting better reasons too - it would've saved some debugging here (and also I'm not yet certain this is the issue until I can repro... although it seems very likely).

**Comment by FMorschel** [comment]
Would there be any logs from VSCode itself for this?

**Comment by FMorschel** [comment]
Can't you forcefully replace the value in debug mode to see if that fails at least?

**Comment by DanTup** [comment]
Looking back at the log, we don't only have the missing version, we actively try to create the file even though it already exists:

```
{"kind":"create","uri":"file:///c:/Users/felip_0vh5fa6/Documents/Projects/flutter/bug/lib/a.dart"}
```

So for some reason, the server believes that `a.dart` does not exist at this point.

**Comment by FMorschel** [comment]
That would explain why whenever I already have the file there, it does work as it should.

**Comment by DanTup** [comment]
Oh, I just realised I'd been looking at the client-side log for the analyzer, but you also gave me the instrumentation log. Looking in there, I again see this:

```
1724342866720:Ex:Exception while using a EolAtEndOfFile to visit a CompilationUnitImpl
PathNotFoundException(path=c::\Users\felip_0vh5fa6\Documents\Projects\flutter\bug\lib\a.dart; message=Cannot retrieve modification time)
#0      _PhysicalFile.modificationStamp (package::analyzer/file_system/physical_file_system.dart::124::7)
#1      _OverlayFile.modificationStamp (package::analyzer/file_system/overlay_file_system.dart::149::18)
#2      FileSource.contentsFromFile (package::analyzer/source/file_source.dart::67::12)
#3      FileSource.contents (package::analyzer/source/file_source.dart::54::12)
#4      _Visitor.visitCompilationUnit (package::linter/src/rules/eol_at_end_of_file.dart::60::48)
#5      CompilationUnitImpl.accept (package::analyzer/src/dart/ast/ast.dart::3607::50)
#6      LinterVisitor._runSubscriptions (package::analyzer/src/lint/linter_visitor.dart::1096::14)
#7      LinterVisitor.visitCompilationUnit (package::analyzer/src/lint/linter_visitor.dart::188::5)
#8      CompilationUnitImpl.accept (package::analyzer/src/dart/ast/ast.dart::3607::50)
#9      LibraryAnalyzer._computeLints (package::analyzer/src/dart/analysis/library_analyzer.dart::398::12)
#10     LibraryAnalyzer._computeDiagnostics (package::analyzer/src/dart/analysis/library_analyzer.dart::323::7)
#11     LibraryAnalyzer.analyze (package::analyzer/src/dart/analysis/library_analyzer.dart::108::5)
#12     AnalysisDriver._analyzeFileImpl.<anonymous closure> (package::analyzer/src/dart/analysis/driver.dart::1394::11)
```

I think this is the real issue here - that exception occurs and seems to result in a `PathNotFoundException` so it's no surprise we then treat the file as missing.

I need to trace through this code more and try to understand why this is happening to you and not to me.

**Comment by DanTup** [comment]
I was able to repro this, and I think I got to the bottom of it... It's (another) drive letter casing issue:

```
1724767638093:Info:Opening file::///C%3A/Dev/Test%20Projects/dartcode_5218/lib/a.dart (3 - adding version)
1724767643744:Info:Checking c::\Dev\Test Projects\dartcode_5218\lib\a.dart (-1, null)
```

Right now, a whole lot of the server is case-sensitive with paths. VS Code normalises drive letter casing to uppercase in some places and lowercase in others... we've standardised on normalizing to uppercase, but we have some lowercase creeping through here, and so we think `a.dart` doesn't exist when it really does.

I'll find a way to repro in tests and work on a fix.

**Comment by DanTup** [comment]
The fix for this was included in a pre-release version of the extension today (v3.95.20240827), please let me know if you still see issues after updating (and restarting).

**Comment by FMorschel** [comment]
Just tested it and it's working now!

There should be an update on the vscode issue as well to let them know this was really the problem.

Also, WDYT about creating a small toast event for "moving the class to the new file"? Should I create a new issue for that? Or is it not worth the time?

**Comment by DanTup** [comment]
> Also, WDYT about creating a small toast event for "moving the class to the new file"?

I actually thought we already had this (a generic "Performing refactor..." notification that the server sent for all refactors), but I wonder if it doesn't cover this one because of how it uses a command. I do think it's worth filing an issue and we should add it - there are many reasons why a refactor like this might take a little while, and it's always better if it's clear to the user something is happening rather than them wondering (and potentially accidentally cancelling it by modifying a file or something).
