### ISSUE TITLE
VideoPlayerController Does not send headers when Ran from Web on a request requiring CORS

### ISSUE THREAD

**Issue by sk8ermeb** [Dart-Code/Dart-Code#5219]
**Describe the bug**
When using a Video player controller and setting the headers
```
VideoPlayerController controller = VideoPlayerController.networkUrl(
              Uri.parse(
                "https://myurlwithdata?mediaid=${mediaids[i]}",
              ),
            
              httpHeaders: {
                'Authorization': 'Bearer12343rfds',
                "myheader": "asdf"
              },
            );
```

If the target requires CORS, it seems the headers aren't sent, in fact the OPTIONS pre flight from cors never happens. Contrast with CachedNetworkImage
```
CachedNetworkImage(
                imageUrl:
                    "https://myurl?mediaid=${mediaids[i]}",
                httpHeaders: {"myheader": auth},
                placeholder: (context, url) => CircularProgressIndicator(),
                errorWidget: (context, url, error) => Icon(Icons.error),
                imageRenderMethodForWeb: ImageRenderMethodForWeb.HttpGet));
```
to make that work you must use ImageRenderMethodForWeb.HttpGet to have it use CORS on web. The video doesn't have that. So the behavior is the same as when that argument is omited. The end results is there is no possible way to make an authenticated CORS request to request video. 

**To Reproduce**
to reproduce you only need the above snippet of code for the video player and a backend to download video or image files from. 

**Expected behavior**
If CORS is needed i would expect it to happen automatically, or have an argument to allow it to happen. But I do not expect the header argument to just completely be ignored. 

**Screenshots**
If you want a backend to debug, I wrote a simple low level wsgi interface with python that can output the raw header information including the preflight CORS request

```
def application(env, start_response):
        request_headers = {key: value for key, value in env.items() if key.startswith('HTTP_')}
        reqhead = "\n".join(f"{key}: {value}" for key, value in request_headers.items())

        method = env["REQUEST_METHOD"]
        origin = env.get("HTTP_ORIGIN")
        cookie = env.get("HTTP_COOKIE", "N/A")
        cors = origin
        preflight = cors and method == "OPTIONS"

        headers = [("Content-Type", "text/plain")]
        if cors:
            headers.extend([
                ("Access-Control-Allow-Origin", origin),
                ("Access-Control-Allow-Credentials", "true")
            ])
            if preflight:
                headers.extend([
                    ('Access-Control-Allow-Methods', 'GET, POST, OPTIONS'),
                    ('Access-Control-Allow-Headers', 'Content-Type, Authorization, myheader')
                ])
        else:
            headers.append(("Set-Cookie", "auth=fnd"))

        if method == "OPTIONS":
            start_response("204 No Content", headers)
            return [b'']
```

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

Dart Code extension: 3.94.0
Flutter extension: 3.94.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: win 1.92.1

Workspace type: Flutter (LSP)
Workspace name: test_drive

Dart (3.4.3): C:\Dev\flutter\bin\cache\dart-sdk
Flutter (3.22.2): C:\Dev\flutter (Edge (web-javascript/web))

 - Operating System and version:- 
 - Dart 3.4.3 (stable) (Tue Jun 4 19:51:39 2024 +0000) on "windows_x64"
- on windows / "Windows 10 Pro" 10.0 (Build 22631) (this is what the report is but I am definitely on windows 11??)
- locale is en-US
 - VS Code version:
         VS Code (version 1.92.1)

 - Target device (if the issue relates to Flutter debugging): chrome

**Comment by DanTup** [comment]
This repo is just for the VS Code extension. If you think there's a bug in Flutter (including the development web server used when running with `flutter run` - which is what the VS Code extension uses), this should be filed at https://github.com/flutter/flutter.

Thanks!
