### ISSUE TITLE
CTRL + Click `part of 'file.dart';` directive doesn't work without `part` directive

### ISSUE THREAD

**Issue by FMorschel** [Dart-Code/Dart-Code#5221]
**Describe the bug**
_CTRL + Click_ `part of 'file.dart';` directive doesn't work without `part` directive.

**To Reproduce**
1. Run `dart create bug`
2. Replace the content of `bin/bug.dart` with:

```dart
part 'foo.dart';
```

3. Hold _CTRL + Click_ over `foo.dart` or use the assist to create the new file
4. Manually create a new file under `bin` called `bar.dart`
5. Add the following to inside of the file:

```dart
part of 'bug.dart';
```

**Expected behavior**
Currently, if you open `foo.dart` and _CTRL + Click_ the `bug.dart` string, it will take you (open) that file.
If you do the same under `bar.dart` it will not do anything.  

It should do the same as the other _CTRL + Click_ actions.

**Please complete the following information:**

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.95.20240801
Flutter extension: 3.95.20240801 (activated)

App: Visual Studio Code
App Host: desktop
Version: win 1.92.1

Workspace type: Dart (LSP)
Workspace name: bug

Dart (3.6.0-116.0.dev): C:\Users\felip_0vh5fa6\.puro\shared\caches\7fc38bef4775b7fe77de40b3c30536a94e294d0a\dart-sdk
Flutter (undefined): C:\Users\felip_0vh5fa6\.puro\envs\master\flutter (No device)

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`C:\Users\felip_0vh5fa6\.puro\shared\caches\7fc38bef4775b7fe77de40b3c30536a94e294d0a\dart-sdk\bin\dart.exe info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.6.0-116.0.dev (dev) (Mon Aug 5 09:07:37 2024 -0700) on "windows_x64"
- on windows / "Windows 10 Pro" 10.0 (Build 22631)
- locale is pt-BR

#### Project info

- sdk constraint: '>=3.3.0 <4.0.0'
- dependencies: test
- dev_dependencies: dart_code_metrics, lints

#### Process info

| Memory | CPU | Elapsed time | Command line |
| -----: | --: | -----------: | ------------ |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |

</details>

**Comment by DanTup** [comment]
I can repro this. Looking at the code, we use the `element` of a `PartOfDirective` to get the parent file and generate a navigation region to it.

However, in the case where that parent file does not have a corresponding "part" directive pointing back at it, the `element` instead points to itself.

@bwilkerson I'm not sure if this is a bug or intended. On the left side here, the source file has `part of 'destination.dart';` and destination has `part 'source.dart'` (a two-way link). The `PartOfDirective`'s element is `destination.dart` (the file that it references). However on the right, the destination file is empty (it doesn't have the matching `part`) and the `PartOfDirective`'s element instead references itself instead.

![Screenshot 2024-08-21 121200](https://github.com/user-attachments/assets/6dd62723-c988-4e83-a08d-11c65c862bc5)

The navigation computer currently creates regions using `Element`s but I can't see an obvious way to get the `Element` for the "target" file in this case. We could perhaps extract the URI and find it manually, although I think getting the unit element is an async operation and all of the navigation computation is currently sync. Is there an existing way to follow a `part of` derective to its target even when it's not complete/valid?

**Comment by bwilkerson** [comment]
I'm not entirely sure what's happening here, but my guess is that when the analyzer analyzes the library and doesn't find a `part` directive it decides that the file containing the `part of` directive isn't part of the library. It probably then analyzes the file containing the `part of` directive as a separate library and hence doesn't make the connection back to the mentioned file because it has no element available to it for that file.

It's possible that we could improve the behavior here, but I think at this point we'd want to do so as part of, or maybe after, implementing the enhanced-parts language feature. Anything we do now is likely to be overridden by that work anyway.

But we ought to capture the request in the [sdk issue tracker](https://github.com/dart-lang/sdk/issues/new/choose).

**Comment by FMorschel** [comment]
> But we ought to capture the request in the sdk issue tracker.

I created https://github.com/dart-lang/sdk/issues/56541.

**Comment by DanTup** [comment]
Makes sense to me - thanks both, will close this in favour of https://github.com/dart-lang/sdk/issues/56541 :)
