### ISSUE TITLE
Improve discoverability of additional args for testing

### ISSUE THREAD

**Issue by gaaclarke** [Dart-Code/Dart-Code#5224]
## Is your feature request related to a problem? Please describe.

Yes, I'd like to execute the dart framework tests with a locally built engine.

## Describe the solution you'd like

I'd like an entry in the `Testing` settings for DartCode that allows me to specify the arguments to make flutter use a local engine.

## Describe alternatives you've considered

This would be the easiest solution.

## Additional context

Here is how I invoke the test the way I want from the command line:
```
flutter --local-engine=host_debug_unopt_arm64 \
  --local-engine-host=host_debug_unopt_arm64 \
  --local-engine-src-path=/Users/aaclarke/dev/engine/src/ test \
  --name="Cupertino.*focusable\sand" \
  test/material/switch_test.dart 
```

**Comment by DanTup** [comment]
Does the `dart.flutterTestAdditionalArgs` do what you want?

![image](https://github.com/user-attachments/assets/48ca3ee9-aae6-48ef-8916-ee9bfa2961ce)

**Comment by gaaclarke** [comment]
> Does the dart.flutterTestAdditionalArgs do what you want?

Yes, that does!  Thanks, I wish I had asked earlier.  This is going to be really helpful.  I was worried they would get added at the wrong part of the invocation but works like a charm.

I did look for something like this.  I'm not sure if there is anything we could do to make it more findable.  I was thrown off a bit about looking under the "Dart" settings but knowing I wanted "Flutter" settings.

We can't add something to the testing UI directly for it can we?

**Comment by gaaclarke** [comment]
> I'm not sure what you mean by "testing UI"

This is where I was talking about and where I would expect to find the option to modify the arguments for running tests.  Probably under some ellipsis menu since it isn't the most common thing.  I don't know if we have the ability to add anything there or if vscode just supplies the UI without modification.

<img width="734" alt="Screenshot 2024-08-19 at 9 25 22 AM" src="https://github.com/user-attachments/assets/fa133ab9-1129-4755-aee1-91afdd376b8b">

**Comment by DanTup** [comment]
Ah, gotcha. I think we can contribute some commands there, although it's not clear to me what they would do. We could perhaps open the settings UI that I posted a screenshot of above, although we actually have have a `dart.testAdditionalArgs` that could be applicable if your workspace contains Dart + Flutter.

Generally, these kinds of settings may be better in a `launch.json` or in a Code-Workspace that you can save outside of the project, since if you commit `.vscode/settings.json` it might affect others using the the project.

**Comment by gaaclarke** [comment]
Opening the settings page and highlighting that variable would be an improvement.  Editing the settings directly after interacting with a modal UI would be too.  That's what happens when we use things like `Tasks: Configure Default Build Task`, but that's editing `launch.json`...

I know UX design and having contextual options is a better design, but you know vscode better than me so I defer to you about what we can do with vscode =)

**Comment by DanTup** [comment]
Let's re-open this and I'll try  adding some items to that overflow for menu for something like "Edit 'dart test' args" and "Edit 'flutter test' args" that jump to those settings and see how it feels.

**Comment by DanTup** [comment]
I've added these:

https://github.com/user-attachments/assets/411839c5-f166-4d88-aa76-90dbe3b7bf72

However, they always default to the "User" settings and I think most users would prefer to set them as the "Workspace" level. I've filed https://github.com/microsoft/vscode/issues/226071 to find out if there's a way to do this (or if not, hopefully have it implemented) and will update in future if that's supported. Please add your 👍 to that issue if you'd like to see that.

Thanks!
