### ISSUE TITLE
Switch to the DTD sidebar when using a new enough SDK

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#5225]
- DevTools work done in https://github.com/flutter/devtools/commit/faeb2a3e0d49a01301ed85dd9bba989a88b4b762
- DevTools change tagged as 2.39.0-dev.0 in https://github.com/flutter/devtools/commit/fc9d4d87fac0968af984ae3a80520e7ff6933044
- ~~As of today, SDK currently only has 2.38.0 https://github.com/dart-lang/sdk/blame/main/DEPS#L105~~
- DevTools was rolled into the SDK in https://github.com/dart-lang/sdk/commit/428e52e00c3d15dbe8096b0c1428d238c46759c3
- Dart SDK was sinced tagged as 3.6.0-160.0.dev in https://github.com/dart-lang/sdk/commits/618abb61c237ea197c521809c50ab63b6d3d34bf/

**Comment by DanTup** [comment]
The latest Flutter `master` version includes Dart 3.6.0-164.0.dev which includes the DTD sidebar, so this is now testable using Flutter master and the pre-release version of Dart-Code published today. Currently, this is behind a preview flag.

To test:

- Upgrade to latest Flutter master
- Open a Flutter project and open your _workspace_ settings
- Add the following:
  ```
    "dart.previewDtdSidebar": true, // Enables the DTD version of sidebar
    "dart.toolingDaemonLogFile": "logs/dtd.txt", // Enables DTD log to verify it's the DTD version
  ```
- Run the **Developer: Reload Window** command to restart
- Open the Flutter sidebar

The sidebar should function the same as before, but looking in `logs/dtd.txt` you should see entries when interacting with the sidebar, such as when changing the selected device:

```
// The incoming request from the sidebar
[2:25:30 PM] [DartToolingDaemon] [Info] <== {"jsonrpc":"2.0","method":"Editor.selectDevice","id":3,"params":{"deviceId":"chrome"}}
// The event Dart-Code broadcasts because the device changed
[2:25:30 PM] [DartToolingDaemon] [Info] ==> {"jsonrpc":"2.0","method":"postEvent","params":{"eventData":{"deviceId":"chrome"},"eventKind":"deviceSelected","streamId":"Editor"}}
// Dart-Code's response to the original selectDevice request
[2:25:30 PM] [DartToolingDaemon] [Info] ==> {"id":3,"jsonrpc":"2.0","result":{"type":"Success"}}
```

@kenzieschmoll I've done some testing of this and it all looks good. I will probably remove the preview flag closer to the end of the month (so that those using Flutter master will automatically be using this version). If you get chance to test before then, another set of eyes would be appreciated :-)

@jwren @helin24 FYI - if the goal is to also embed this in IntelliJ, this also means that work could start against latest Flutter master (IntelliJ would need to provide the services listed in https://github.com/dart-lang/sdk/blob/main/pkg/dtd_impl/dtd_common_services_editor.md over DTD).

**Comment by kenzieschmoll** [comment]
I tested this out today and did not see any issues.

**Comment by jwren** [comment]
Ditto -- LGTM @DanTup

**Comment by DanTup** [comment]
Great, thanks for testing! I'll remove the flag so from the next release, it'll use the DTD version by default for new-enough SDKs.

**Comment by DanTup** [comment]
I've also pushed a new pre-release (3.95.20240824) so once you're on that, you can remove the flag and still get the DTD version (mainly to get some additional coverage for pre-release users on Flutter master before the end of month release).
