### ISSUE TITLE
Facilitate Exception handling by exposing all Exception that could be thrown or bubble up when calling a fucntion

### ISSUE THREAD

**Issue by Driky** [Dart-Code/Dart-Code#5228]
**Is your feature request related to a problem? Please describe.**
Either due to low code quality or high complexity as a dev you can end-up calling a function that can end-up throwing a multitude of _Exception_. 

Unless the code you are calling comes with high quality _documentation_ or _comments doc_ you will have to start a descent to hell (digging into the code until you are sure to have explored all lines possibly called) to find what you possibly have to catch and handle.

**Describe the solution you'd like**
When calling a function susceptible to throw or that let an exception bubble up, the code editor will:

- warn you that specific _Exception_  are not handled
- offer as an alternative to generate a _try catch block_ with all _Exception_ handled by type (similar to what is offered when generating an exhaustive switch on an enum or sealed class as the value switched on):

```dart
try {
    doServerCall();
  } on ExceptionA catch (e) {
    log(e);
  } on ExceptionB catch (e) {
    log(e);
  } on ExceptionC catch (e) {
    log(e);
  }
```

**Comment by DanTup** [comment]
This would require knowledge of the exceptions that can occur in the method (both explicitly thrown, or as a result of other code). This is not something the editor can know on its own and would require support from the Dart SDK.

There's an existing request for this at https://github.com/dart-lang/language/issues/984 which contains some interesting discussion about the request, but it was [ultimately rejected](https://github.com/dart-lang/language/issues/984#issuecomment-814510862) as not a good fit for Dart.

Unfortunately if you have existing code throwing a lot of exceptions that not documented, there's not a great way to find out what they all are. If it's code you could refactor, there are some ideas for alternatives in https://github.com/dart-lang/language/issues/984#issuecomment-814510862.

I'm sorry this isn't the response you hoped for, but I hope this makes sense. Thanks!
