### ISSUE TITLE
In a monorepo, when you select the debug session and select "Dart & Flutter...", all projects are shown, but all with the root folder name instead of the project name.

### ISSUE THREAD

**Issue by MiniSuperDev** [Dart-Code/Dart-Code#5232]
In a monorepo, when you select the debug session and select "Dart & Flutter...", all projects are shown, but all with the root folder name instead of the project name.

It should show the project name (name in pubspec.yaml)

![image](https://github.com/user-attachments/assets/320f18ff-a67e-4dc6-870e-96d6d98b4e4f)

Thanks

**Comment by DanTup** [comment]
Looks like we lost the name in https://github.com/Dart-Code/Dart-Code/commit/b683901b1a336e3cde20d4d956dcb09cc3ef7c12 - there's a variable for it it and it was there before, but it was removed. I don't know if there was a reason for it, but it doesn't seem like a good change so I will add it back.
