### ISSUE TITLE
Issue on website (Launch Configuration)

### ISSUE THREAD

**Issue by mvolpato** [Dart-Code/Dart-Code#5243]
I found an issue on http://dartcode.org/docs/launch-configuration/

The link https://github.com/dart-lang/sdk/tree/master/pkg/dds/tool/dap#readme in the code snippet leads to 404.

**Comment by DanTup** [comment]
Thanks! This document moved to https://github.com/dart-lang/sdk/blob/main/third_party/pkg/dap/tool/README.md. I've updated the link.
