### ISSUE TITLE
Automated Detection of Unused Assets, Files, and Dependencies in Flutter Projects

### ISSUE THREAD

**Issue by itsamit108** [Dart-Code/Dart-Code#5246]
**Is your feature request related to a problem? Please describe.**
Yes, as a Flutter developer, I often struggle with keeping my projects clean and optimized. Over time, unused assets, files, and dependencies accumulate, making the project larger and harder to maintain. Manually identifying these unused elements is time-consuming and prone to errors.

**Describe the solution you'd like**
I would like to see an official feature in the Dart/Flutter VS Code extension that can automatically detect and list unused assets, files, and dependencies. This tool would analyze the project and provide a report or option to remove these unused elements directly.

**Describe alternatives you've considered**
Currently, there are third-party tools and extensions like vscode-flutter-unused, but integrating this feature directly into the official Flutter extension would provide a more seamless and reliable experience. Another alternative is manually searching and removing unused items, but this is inefficient and risks accidentally deleting necessary components.

**Additional context**
This feature would significantly enhance the development experience by helping maintain clean and efficient projects, especially in larger apps where unused dependencies and assets can become a burden.

**Comment by DanTup** [comment]
This is something that would be better implemented in Flutter itself and then exposed for the IDEs to call. Doing this reliably will require parsing code and understanding how assets can be loaded and the Dart-Code extension itself doesn't do this kind of work, it's all delegated to the `flutter` tool and the Dart language server (from the Dart SDK).

Could you file this request at https://github.com/flutter/flutter/issues and post a link back here? I did have a quick search but couldn't find any existing open issue for this, but I think it's a fair feature request (and I think Dart/Flutter might already do some of this work as part of tree shaking and building?).

Thanks!

**Comment by utsavtulsyan** [comment]
@DanTup @itsamit108 I built a little vscode extension, it works in conjunction with the Dart-Code to do the analysis, I'd love to hear your feedback on this.
https://marketplace.visualstudio.com/items?itemName=utsavtulsyan.dart-unused-code

**Comment by DanTup** [comment]
@utsavtulsyan this looks interesting - though by fetching references on each method, I wonder if this could get very slow for large codebases. I wonder if it might be better if this code was written in Dart using the `analyzer` package (or perhaps as an analysis server plugin?) which would give it more direct access without having to go through multiple layers/processes communicating by serializing/deserializing JSON.

**Comment by utsavtulsyan** [comment]
You're right, that would be a great optimisation for this use case, I initially explored those and found to be more complicated when working with a vscode extension that has to be written in typescript. I'd love to connect with you to discuss approaches and come up with a better design and implementation plan if you're open to it. In any case, I appreciate your response, my future focus will be on optimisation and expanding features as a I get some more user feedback.
