### ISSUE TITLE
`@annotation super.` appears parsed differently than `@annotation this.`

### ISSUE THREAD

**Issue by matanlurey** [Dart-Code/Dart-Code#5247]
I'm guessing the grammar change was not reflected the same way, ... or something :)

```dart
import 'package:meta/meta.dart';

final class Base {
  const Base(@mustBeConst this.code);
  final int code;
}

final class Super extends Base {
  const Super(@mustBeConst super.code);
}
```

Real example:

![Screenshot 2024-09-03 at 11 47 26 PM](https://github.com/user-attachments/assets/47bdfb67-93a0-460e-95c6-e3ae6c5809a7)

**Comment by DanTup** [comment]
Yeah, I can repro this - what's odd is that unlike most of this kind of issue, it seems to be the semantic tokens. If I disable semantic highlighting so the textmate grammar is used, it's consistent:

![image](https://github.com/user-attachments/assets/439aa337-05dd-4c06-8a94-bda4de7f6837)

But with semantic tokens enabled, it's inconsistent:

![image](https://github.com/user-attachments/assets/4be8d8f8-46c7-4022-b990-eb8285516cc5)

It appears we don't have any semantic token on the super version.

**Comment by DanTup** [comment]
This is fixed by https://github.com/dart-lang/sdk/commit/40b9153fab199163fcd7fbe74569a275cb79e013

The change is in the analysis server so will show up in an SDK update (not a Dart-Code update).

**Comment by stan-at-work** [comment]
@DanTup What type of documentation is this ?

![image](https://github.com/user-attachments/assets/3e91bf19-f8c7-44fe-b5e2-7113605cb96b)

**Comment by DanTup** [comment]
@stan-at-work it's something built in to VS Code to help debug syntax highlighting. You can enable it with this command:

<img width="651" alt="Screenshot 2024-10-01 at 08 51 11" src="https://github.com/user-attachments/assets/212a1890-acc3-4dae-89b7-a8bd9aad9c87">
