### ISSUE TITLE
Support wildcards for configuring "codeLens. path"

### ISSUE THREAD

**Issue by zhujiageng** [Dart-Code/Dart-Code#5253]
I manage a monorepo with VSCode, which includes many Flutter apps and libraries. However, I have only one launch.json. Some test files require the --dart-define-from-file flag when running. When they fail, I need to debug these tests, but the default "Debug" codeLens does not include --dart-define-from-file. Therefore, I have defined a new set of codeLenses named Run(TestDefines) and Debug(TestDefines), and I pass the --dart-define-from-file parameter in the args of these codeLenses. But this results in these new codeLenses appearing on all test files, which is not very nice. So I want to enable these codeLenses only in the specific dart_defines_test.dart file. If codeLens.path supported wildcards, I could easily enable these codeLenses only in the required files.

**Comment by DanTup** [comment]
> So I want to enable these codeLenses only in the specific dart_defines_test.dart file

Is there only one `dart_defines_test.dart` file, or multiple? If only one, you can enter the whole (relative) path to it in `codeLens.path`.

But if you have multiple, I presume you'd like something like "**/dart_defines_test.dart"?

**Comment by zhujiageng** [comment]
@DanTup Yes, I have multiple "dart_defines_test.dart" files. I would indeed like to support something like "**/dart_defines_test.dart".
