### ISSUE TITLE
Breakpoint sometimes cannot be set in Flutter

### ISSUE THREAD

**Issue by spyingcoder** [Dart-Code/Dart-Code#5255]
**Describe the bug**
Breakpoints sometimes cannot be set in Flutter

**To Reproduce**

1. Run your Flutter Application
2. Try to set breakpoints on any function.

**Expected behavior**
Breakpoints should be set and work when the instance of code reach there while running.

**Screenshots**
Not available

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

 - Operating System and version: Mac OS version 14.1
 - VS Code version: 1.93.0(Universal)
 - Dart extension version: 3.96.0
 - Dart/Flutter SDK version: Any
 - Target device (if the issue relates to Flutter debugging): Any

**Comment by DanTup** [comment]
> Try to set breakpoints on any function.
> Dart/Flutter SDK version: Any
> Target device: Any

I'm afraid you'll need to provide some more specific information to help me reproduce this issue. I haven't seen the issues you describe and I use breakpoints in Flutter daily, so there must be some specific things causing your issue that we'll need to narrow down.

Please provide a code sample and a specific location where breakpoints are definitely not working for you, along with the specific SDK version you're running and which device (macOS, iOS simulator, physical iOS device) to help me try to reproduce.

Please also try reproducing the issue in a new sample project (created with the **Flutter: New Project** command) and capture a log file:

- Create a new sample project
- Set up the code and breakpoint ready to reproduce the issue
- Run the [**Dart: Capture Debugging Logs** command](https://dartcode.org/docs/logging/#capture-debugging-logs)
- Run the app and trigger the code where the breakpoint does not work
- Click **Cancel** on the logging notification to stop logging and open the log
- Remove anything sensitive from the log
- Attach the log here, in a [gist](https://gist.github.com/), or email to me at logs@dartcode.org.

Thanks!
