### ISSUE TITLE
Dart pub get does not respect VSCode env variables

### ISSUE THREAD

**Issue by cpirtea-bun** [Dart-Code/Dart-Code#5258]
**Describe the bug**
I have defined VSCode environment variables in "terminal.integrated.env" sections and they work if I run dart pub get in the terminal window however when the plugin runs pub get on pubspec.yaml saving it does not use the same env so it runs the wrong PUB_HOSTED_URL.

**To Reproduce**
1. Set PUB_HOSTED_URL to something other than pub.dev in VSCode workspace settings.
2. Run dart pub get
3. Save pubspec.yaml file
4. Wait for dart plugin to finish running dart pub get
5. Observe the different source used for packages

**Expected behavior**
Dart plugin should use the environment defined for the VSCode terminal so it can have the same environment variables or allow defining PUB_HOSTED_URL for the plugin.

**Screenshots**

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

 - Operating System and version: Windows 11
 - VS Code version: 1.93.0
 - Dart extension version: 3.96.0
 - Dart/Flutter SDK version: 3.5.2/3.24.2
 - Target device (if the issue relates to Flutter debugging): N/A

**Comment by cpirtea-bun** [comment]
Found out how to do it. Sorry.

**Comment by DanTup** [comment]
The `"terminal.integrated.env"` setting is specific to the terminal which is why it doesn't work here.

Seems like you already found it, but for future readers, `dart.env` is the setting you want to apply env variables to all processes started by this extension (this should work either in Workspace Settings or User Settings).
