### ISSUE TITLE
yellow bulb 

### ISSUE THREAD

**Issue by Abinandhan-Shanmugasundaram** [Dart-Code/Dart-Code#5262]
The yellow bulb doesn't show many options 

 - Operating System and version:
 - VS Code version:1.93.0
 - Dart extension version:3.96.0
 - Dart/Flutter SDK version:3.5.2
<img width="639" alt="image" src="https://github.com/user-attachments/assets/6561e891-1019-4ed7-beee-27b280a9f264">

Other wrap options are not showing

**Comment by DanTup** [comment]
It's hard to be sure without more info, but from the screenshot it looks like your selection is in `suffixIcon` which is a parameter name, and those wrap options are not supported there, only on the widget expression.

For example here you can see the wrap options when my cursor is in `Column`, but not in `child`:

https://github.com/user-attachments/assets/c5912808-1bac-48b1-b382-2b2cfe0550d3
