### ISSUE TITLE
Dart.exe Eating All Memory

### ISSUE THREAD

**Issue by AbdulkadirBastug** [Dart-Code/Dart-Code#5264]
**Describe the bug**
When i write this code, which helps to get data from the internet, in ONE line Dart.exe eats all memory.

**To Reproduce**
1. Run your flutter application.

![step1](https://github.com/user-attachments/assets/a3a4a88a-cb8d-4004-831d-70c2fa71e091)

2. Go to your pubspec.yaml file and add the http dependency

![step2](https://github.com/user-attachments/assets/ea0c18f4-1f17-40cd-b5fc-856a9ad98316)

3. import 'package:http/http.dart' as http;

![step3](https://github.com/user-attachments/assets/11c5b46b-68a2-47cb-be36-0c68396326a7)
4. Start the device and run the app.

![step4](https://github.com/user-attachments/assets/3adad898-739b-414c-a383-741007f2baa5)
![step5](https://github.com/user-attachments/assets/60f03917-a6fa-4f10-8f6d-e99eb6277f4e)

5. Write this method while the app is running (do not copy paste).
 
![step 6](https://github.com/user-attachments/assets/3091a5df-797d-47dc-89e1-7270b4c9bb55)

**Screenshots**

![Untitled3](https://github.com/user-attachments/assets/32b1f38b-152e-406b-9375-41fe527e506e)

**Please complete the following information:**

 -  Operating System and version: Windows 11 Education N Version 23H2
 -  VS Code version: 1.93.0
 -  Dart extension version: 3.96.0
 - Dart/Flutter SDK version: 3.24.2
 - Target device (if the issue relates to Flutter debugging): Pıxel 8 Pro API 35

**Comment by DanTup** [comment]
I don't seem to be able to reproduce this, however it's not clear to me whether you've just written the code in the IDE and then issue occurred, or if you are running the app (in which case, how/when you're calling this method may be important).

Please provide more detailed steps to help reproduce this issue, including answering the questions from the template such as the versions you're using:

> VS Code version: any
> Dart extension version: any

**Comment by AbdulkadirBastug** [comment]
> I don't seem to be able to reproduce this, however it's not clear to me whether you've just written the code in the IDE and then issue occurred, or if you are running the app (in which case, how/when you're calling this method may be important).
> 
> Please provide more detailed steps to help reproduce this issue, including answering the questions from the template such as the versions you're using:
> 
> > VS Code version: any
> > Dart extension version: any

Write the code while the app is running then save the code.

**Comment by AbdulkadirBastug** [comment]
> @AbdulkadirBastug please provide exact steps that I can follow. I don't know what else is in your app, or what versions of the extensions/SDKs you are using.
> 
> I would create a new project with **Flutter: New Project** and verify you can still produce the problem there, and then provide the exact steps so that I can reproduce it. Thanks!

I updated the ıssue. Could you check again ?

**Comment by DanTup** [comment]
@AbdulkadirBastug thank you - that looks much clearer. Although it looks like you're using Android Studio and this issue tracker is for VS Code - does the same issue occur in VS Code?

**Comment by AbdulkadirBastug** [comment]
@DanTup actually i don't know. I didn't try and i didn't know this is for VS Code. Sorry, my bad!

**Comment by DanTup** [comment]
If you're able to test in VS Code and it reproduces there, I can try to reproduce. Although I would first ensure you've closed all other IDEs and that the existing high-memory process has gone, to be sure you're not seeing an old process that isn't started by VS Code.

Otherwise, if it doesn't repro there, I would check the details of that `dart.exe` process to see what the full command line is (you may have to switch to the Details tab in Task Manager), as that might help understand where the bug should be filed.

Thanks!
