### ISSUE TITLE
VSCode Auto-Import-Complete broken, too many import suggestions

### ISSUE THREAD

**Issue by mfrischbutter** [Dart-Code/Dart-Code#5266]
**Describe the bug**
The code completion shows me files to import where the file I want to import has already been imported. 

**To Reproduce**
Unfortunately, I don't know how to reproduce this. I only have it in this project. I have already tried to load old versions of the code or restart the Dart server.

**Expected behavior**
I expect only one import to be displayed, namely the source file. The other files are surplus and when I import them, it doesn't work either.

**Screenshots**
<img width="461" alt="Screenshot 2024-09-14 at 21 40 44" src="https://github.com/user-attachments/assets/f1104938-9f18-47ac-8aa7-efe2efa1d957">

**Please complete the following information:**

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.96.0
Flutter extension: 3.96.0 (activated)

App: Cursor
App Host: desktop
Version: mac 1.91.1

Workspace type: Flutter (LSP)
Workspace name: stable_buddy_app

Dart (3.5.3): /Users/mfrischbutter/tools/flutter/bin/cache/dart-sdk
Flutter (3.24.3): /Users/mfrischbutter/tools/flutter (iPhone 15 (ios/ios))

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`/Users/mfrischbutter/tools/flutter/bin/cache/dart-sdk/bin/dart info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.5.3 (stable) (Wed Sep 11 16:22:47 2024 +0000) on "macos_arm64"
- on macos / Version 14.3.1 (Build 23D60)
- locale is en-DE

#### Project info

- sdk constraint: '>=3.2.3 <4.0.0'
- dependencies: animated_digit, animations, cached_network_image, collection, confetti, cupertino_icons, dio, dotted_border, drift, easy_date_timeline, fl_chart, flash, flutter, flutter_custom_clippers, flutter_dotenv, flutter_hooks, flutter_image_compress, flutter_localizations, flutter_svg, font_awesome_flutter, form_validator, freezed_annotation, geolocator, go_router, google_maps_flutter, hooks_riverpod, image_cropper, image_picker, intl, json_annotation, logger, mixpanel_flutter, modal_bottom_sheet, path, path_provider, powersync, powersync_attachments_helper, riverpod_annotation, rxdart, sentry_flutter, shared_preferences, skeletonizer, slang, slang_flutter, smooth_page_indicator, sqlite3_flutter_libs, supabase, supabase_flutter, syncfusion_flutter_sliders, table_calendar, url_launcher
- dev_dependencies: build_runner, custom_lint, drift_dev, flutter_gen_runner, flutter_launcher_icons, flutter_lints, flutter_test, freezed, go_router_builder, json_serializable, riverpod_generator, riverpod_lint, slang_build_runner, very_good_analysis

#### Process info

| Memory |  CPU | Elapsed time | Command line                                                                               |
| -----: | ---: | -----------: | ------------------------------------------------------------------------------------------ |
| 757 MB | 0.0% |        11:31 | dart --enable-vm-service=0 lib/custom_lint_client.dart ::1 64217                           |
|  39 MB | 0.0% |        11:31 | dart development-service --vm-service-uri=http:<path>/ --bind-address=localhost --bind-port=0 --serve-devtools |
|  26 MB | 0.0% |        19:27 | dart devtools --machine --allow-embedding --dtd-uri ws:<path>/FcNYOmdvWbrJkd7S             |
|  12 MB | 0.0% |  02-02:08:08 | dart devtools --machine --allow-embedding --dtd-uri ws:<path>/VD1aluSCEHpIHQ6Y             |
|  28 MB | 0.0% |        22:14 | dart devtools --machine --allow-embedding --dtd-uri ws:<path>/x4rRaxM8sCn6PJFY             |
| 100 MB | 0.0% |        22:14 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.96.0            |
| 659 MB | 0.0% |        19:27 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.96.0            |
|  17 MB | 0.0% |  02-02:08:08 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.96.0            |
|  28 MB | 0.0% |        22:14 | dart tooling-daemon --machine                                                              |
|  28 MB | 0.0% |        19:27 | dart tooling-daemon --machine                                                              |
|  10 MB | 0.0% |  02-02:08:08 | dart tooling-daemon --machine                                                              |
|  68 MB | 0.6% |        22:14 | flutter_tools.snapshot daemon                                                              |
|  68 MB | 0.0% |        19:27 | flutter_tools.snapshot daemon                                                              |
|  52 MB | 0.2% |  02-02:08:08 | flutter_tools.snapshot daemon                                                              |
|  33 MB | 0.0% |  01-07:39:38 | flutter_tools.snapshot debug_adapter                                                       |
|  31 MB | 0.0% |  01-07:39:38 | flutter_tools.snapshot run --machine --start-paused -d FA7FDD8A-08B6-4C1F-89AA-D835665986DC --devtools-server-address http:<path>/ --target <path>/main_production.dart --flavor production |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`/Users/mfrischbutter/tools/flutter/bin/flutter doctor -v`

```text
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.3.1 23D60 darwin-arm64, locale en-DE)
    • Flutter version 3.24.3 on channel stable at /Users/mfrischbutter/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (3 days ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mfrischbutter/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.93.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (4 available)
    • iPhone 15 (mobile)              • 27F26BF3-F172-4CE5-B25D-099E03F6443D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.3.1 23D60 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 128.0.6613.120

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by DanTup** [comment]
Thanks for the report! I actually fixed this issue fairly recently (see https://github.com/dart-lang/sdk/issues/56320). The issue was that the server was including extensions for any file that _imported_ them, rather than only those that declared/_exported_ them.

The fix is in the Dart analysis server, so it will be included in a future Dart/Flutter SDK release rather than a Dart extension update.
