### ISSUE TITLE
m

### ISSUE THREAD

**Issue by mohammad2002akh** [Dart-Code/Dart-Code#5274]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

 - Operating System and version:
 - VS Code version:
 - Dart extension version:
 - Dart/Flutter SDK version:
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
I think this was created in error, but if not, please provide more details.
