### ISSUE TITLE
[DevTools] Add toggle for showSemanticsDebugger

### ISSUE THREAD

**Issue by lsaudon** [Dart-Code/Dart-Code#5278]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a button like `Slow Animations, Show Guidelines...` to activate or deactivate accessibility debugger.

**Comment by DanTup** [comment]
@lsaudon I'm not sure if you mean a command in the command palette, or a button in the DevTools web app. If the former, here is the correct repo for it, but for DevTools it should be filed at https://github.com/flutter/devtools/.

That said, I'm not sure if Flutter currently exposes a service for this so it might need a Flutter change first. The other things we expose (like toggle repaint rainbow, slow animations) have service extensions (see https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/service_extensions.dart). @goderbauer do you know if there is a service extension for toggling the semantics debugger? I'm not sure if it might go by another name (although I shouldn't find any code that seems to modify the `showSemanticsDebugger` flag that I see in code).
