### ISSUE TITLE
Extension host terminated unexpectedly 3 times within the last 5 minutes

### ISSUE THREAD

**Issue by BlueAgateSupport** [Dart-Code/Dart-Code#5292]
**Describe the bug**
Since Friday 2024-09-27 afternoon, the dart analytics server on one of my projects is terminating upon opening VSCode.

**To Reproduce**
1. Open Flutter project in VSCode

**Expected behavior**
The analytics server to load in order to proceed with work.

**Screenshots**
<img width="1365" alt="Screenshot 2024-09-30 at 16 36 37 (2)" src="https://github.com/user-attachments/assets/8184dd97-521c-4786-9f31-24f54f8576e4">

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

 - Operating System and version: MacOs Sequoia 15.0 (24A335)
 - VS Code version: 1.93.1 (Universal)
 - Dart extension version: Dart SDK version: 3.3.4 (stable) (Tue Apr 16 19:56:12 2024 +0000) on "macos_arm64"
 - Dart/Flutter SDK version: Flutter 3.19.6 • channel stable • https://github.com/flutter/flutter.git 
Framework • revision 54e66469a9 (6 months ago) • 2024-04-17 13:08:03 -0700
Engine • revision c4cd48e186
Tools • Dart 3.3.4 • DevTools 2.31.1
 - Target device (if the issue relates to Flutter debugging): Cannot run debugger

**Comment by DanTup** [comment]
The error message here shows that the extension host terminated, which is different to the Dart analysis server (I presume you meant analysis server, not analytics server). The first thing would be to confirm which extension is causing this by clicking the "Start Extension Bisect" button. This will perform a binary search on all of your extensions to confirm which one is causing the extension host to terminate (all of your extensions run in the same extension host).

Please try this out and let me know the results. Thanks!

**Comment by BlueAgateSupport** [comment]
@DanTup Apologies, yes, the analysis server and thank you, I have isolated the GitLive extension as the problem.
