### ISSUE TITLE
Be able to exclude connected devices from choice lists

### ISSUE THREAD

**Issue by lsaudon** [Dart-Code/Dart-Code#5298]
**Is your feature request related to a problem? Please describe.**
My application only contains Android and iOS.
I don't want to see Chrome or Mac devices.

**Describe the solution you'd like**
```json
"dart.flutterSelectDeviceExcluded": {
  "chrome": true,
  "mac-designed-for-ipad": true,
  "macos": true
}
```
or
```json
"dart.flutterSelectDeviceExcluded": {
  "web": true,
  "desktop": true
}
```

**Additional context**
![image](https://github.com/user-attachments/assets/04beb9a9-a8bd-454a-88df-e10082e8614f)

**Comment by DanTup** [comment]
It is possible today to remove the web/desktop devices by just deleting the particular platforms folders (eg. if you remove the `web` folder and the `macos` folder, those devices will become unavailable). They will still be shown at the bottom of the list with an "Enable web"/"Enable macos" option (to make it easier to add them back if you do want to add them).

**Comment by DanTup** [comment]
@lsaudon does the above address your request?
