### ISSUE TITLE
Typo in grammar "Line Length" description

### ISSUE THREAD

**Issue by mkorbel1** [Dart-Code/Dart-Code#5300]
**Describe the bug**
There's a typo in the description in VS code settings:
> **Dart: Line Length**
> The maximum length of a line of code. This is used by the document formatter. If you change this value, you may wish to update editor.rulers (which draws vertical lines in the editor) in the ["dart"] section if your settings to match.

"if your settings to match" should probably be "if you wish your settings to match" (for example)

**To Reproduce**
Enter settings UI with VS code, find the dart line length description.

**Expected behavior**
Correct grammar 

**Screenshots**

![image](https://github.com/user-attachments/assets/99c565a2-0531-4523-8e86-131595da8ac7)

**Please complete the following information:**

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.98.0

App: Visual Studio Code
App Host: desktop
Remote: wsl
Host Kind: wsl
Version: linux 1.93.1

Workspace type: Dart (LSP)

Dart (3.5.3): /usr/lib/dart
Flutter (undefined): undefined (No device)
```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`/usr/lib/dart/bin/dart info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.5.3 (stable) (None) on "linux_x64"
- on linux / Linux 5.15.153.1-microsoft-standard-WSL2
- locale is C.UTF-8

#### Project info

- sdk constraint: '^3.4.0'
- dependencies: collection, meta, quiver, rohd, rohd_hcl, rohd_vf
- dev_dependencies: lints, test

</details>

**Comment by DanTup** [comment]
Thanks! Looks like `if` should've been `of`.
