### ISSUE TITLE
Flutter icon not appearing on LHS in VSC on MacOS Sequoia

### ISSUE THREAD

**Issue by gwhizofss** [Dart-Code/Dart-Code#5301]
**Describe the bug**
The Flutter icon is not appearing on LHS Icon Nav Bar in VSC on MacOS Sequoia
**To Reproduce**
Open Flutter on an Sequoia Mac at the root of your repo with "code ."
See that the Flutter Icon is missing.
Check that both Dart and Flutter plugins are installed.

**Expected behavior**
Usually I can click on the FLutter icon to open the side panel for Flutter.

**Screenshots**
<img width="1277" alt="Screenshot 2024-10-05 at 1 35 41 PM" src="https://github.com/user-attachments/assets/17d1951d-7c3a-4667-9b7a-39c75d3cecc8">

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.
Strangely, that command doesn't seem to be available in VSC:
<img width="969" alt="Screenshot 2024-10-05 at 1 45 06 PM" src="https://github.com/user-attachments/assets/76cbced8-5cea-4744-8028-5e6c6f603f30">

 - Operating System and version: MacOs Sequoia 
 - VS Code version: 
 - Version: 1.94.0 (Universal)
**Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
Date: 2024-10-02T13:08:12.626Z (3 days ago)
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0**
 - Dart extension version:
     - 3.98.0
 - Dart/Flutter SDK version:
 -     ios % flutter --version
Flutter 3.24.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2663184aa7 (3 weeks ago) • 2024-09-11 16:27:48 -0500
Engine • revision 36335019a8
Tools • Dart 3.5.3 • DevTools 2.37.3
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
@gwhizofss the sidebar only appears when you have a Flutter project open - it's not clear if that's the case from the screenshot. Can you check this? (or post a screenshot showing a Dart/Flutter editor open).

Another thing to check is whether Flutter extension has been unticked if you right-click in the list of sidebar icons:
 
<img width="357" alt="Screenshot 2024-10-05 at 21 57 30" src="https://github.com/user-attachments/assets/18a8ecf6-430b-4d3e-8d52-12ae6f08ce21">

And also turn on the secondary sidebar to see whether it may have been moved to there:
 
<img width="520" alt="Screenshot 2024-10-05 at 21 58 38" src="https://github.com/user-attachments/assets/bd9fc9c1-c26e-4ac9-b158-d061ed901427">

**Comment by gwhizofss** [comment]
Thank you @DanTup for responding so quickly!
<img width="1599" alt="Screenshot 2024-10-05 at 2 08 11 PM" src="https://github.com/user-attachments/assets/902f6fa8-2615-4c37-9075-36c970fd9f10">
Here, I'm in pubspec.yaml. The 2ndary sidebar seems to have nothing. Extensions are checked.

**Comment by DanTup** [comment]
Can you try running the **Show Running Extensions** command and see whether the Dart extension reports any errors activating? Could you also right-click on the status bar at the bottom and post a screenshot of its context menu? I would expect to see the language status indicator (`{}`) next to "YAML" in the status bar but I don't know whether it's just hidden, or this indicates the extension isn't activated correctly.

You could also check the console (Help -> Toggle Developer Tools -> Console) to see if there are any errors about the extension not activating.
