### ISSUE TITLE
Dependencies tree doesn't show any nodes if the packages name in pubspec.yaml does not match the folders name

### ISSUE THREAD

**Issue by doreille** [Dart-Code/Dart-Code#5307]
**Describe the bug**
On some flutter projects with many dependencies, the dependencies panel is completely empty (no  
On the same Linux account, some other flutter projects have a working dependencies panel.  

**To Reproduce**
This is reproducible on my account.

1. git clone https://github.com/minaxorg/flutter_intro.git
2. cd flutter_intro/example/
3. flutter pub get
4. code .
5. open the "DEPENDENCIES" panel

**Expected behavior**
The VScode primary side bar dependencies panel must contains
  - direct dependencies
  - dev dependencies
  - transitive dependencies

**Screenshots**
![image](https://github.com/user-attachments/assets/3ecea215-32aa-47ab-a9a4-1516d1c5ce05)

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

 - Operating System and version:
  Linux Fedora 40 
 - VS Code version:
  1.94.1 (rpm -q code: code-1.94.1-1728111464.el8.x86_64)
 - Dart extension version:
   Dart Code extension: 3.98.1
   Flutter extension: 3.98.0 (activated)
 - Dart/Flutter SDK version:
   Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on Fedora Linux 40 (Workstation Edition) 6.10.11-200.fc40.x86_64, locale en_GB.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] VS Code (version 1.94.1)
[✓] Connected device (2 available)
[✓] Network resources
! Doctor found issues in 1 category.
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
Thanks, I can repro this. The issue is that the project name does not match the name of the folder it's in (`example` vs `intro`). There are some assumptions about these matching in the code that maybe we can get rid of.

**Comment by doreille** [comment]
Thanks, it works now after renaming the project. I searched for a long time why it didn't work anymore but I understand now because I had renamed this project.

**Comment by DanTup** [comment]
It's also very possible this became broken in the recent release - the way that we get these dependencies changed slightly recently to support the upcoming Pub Workspaces feature. Before those changes, probably this would've worked fine too.

I've fixed the issue now anyway, so from the next release it will work even if the names don't match. Thank you for the report!
