### ISSUE TITLE
Dart Formatter Not Working on Macro Classes in VS Code with Experimental Flag

### ISSUE THREAD

**Issue by albinpk** [Dart-Code/Dart-Code#5309]
**Describe the bug**
When using the Dart extension in VS Code, the formatter does not work for macro classes. However, running the `dart format` command directly from the terminal with the experimental flag (`--enable-experiment=macros`) works as expected.

**To Reproduce**

1. Create a Dart project and define a `macro class`.
2. Run `dart format . --enable-experiment=macros` from the terminal—formatting works.
3. Add the experimental flag for Dart Analyzer in VS Code settings (`"dart.analyzerAdditionalArgs": ["--enable-experiment=macros"]`).
4. Try to format the code in VS Code—formatting does not work.

**Expected behavior**
The Dart formatter in VS Code should correctly format the code for macro classes when the experimental flag is enabled.

**VS Code settings**
```json
{
  "dart.flutterSdkPath": ".fvm/versions/3.26.0-0.1.pre",
  "editor.formatOnSave": true,
  "dart.analyzerAdditionalArgs": [
    "--enable-experiment=macros"
  ],
}
```

**analysis_options.yaml**
```yaml
include: package:flutter_lints/flutter.yaml

analyzer:
  enable-experiment:
    - macros
```

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.99.20241007
Flutter extension: 3.99.20240930 (activated)

App: Visual Studio Code
App Host: desktop
Version: linux 1.94.2

Workspace type: Flutter (LSP)
Workspace name: macro_bug

Dart (3.6.0-216.1.beta): /home/albin/fvm/versions/3.26.0-0.1.pre/bin/cache/dart-sdk
Flutter (3.26.0-0.1.pre): /home/albin/fvm/versions/3.26.0-0.1.pre (No device)

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`/home/albin/fvm/versions/3.26.0-0.1.pre/bin/cache/dart-sdk/bin/dart info`

#### General info

- Dart 3.6.0-216.1.beta (beta) (Wed Sep 4 14:34:46 2024 -0700) on "linux_x64"
- on linux / Linux 6.1.111-1-MANJARO # 1 SMP PREEMPT_DYNAMIC Wed Sep 18 21:01:06 UTC 2024
- locale is en_US.UTF-8

#### Project info

- sdk constraint: '^3.6.0-216.1.beta'
- dependencies: flutter, macros
- dev_dependencies: flutter_lints, flutter_test

#### Process info

| Memory |  CPU | Elapsed time | Command line                                                                               |
| -----: | ---: | -----------: | ------------------------------------------------------------------------------------------ |
| 339 MB | 1.5% |        04:56 | dart --enable-experiment=macros language-server --protocol=lsp --client-id=VS-Code --client-version=3.99.20241007 --enable-experiment=macros |
|  65 MB | 0.1% |        04:56 | dart devtools --machine --allow-embedding --dtd-uri ws:<path>/s3YQ6bJHn754CdDq             |
| 290 MB | 1.8% |        02:54 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.99.20241007     |
|  81 MB | 0.1% |        04:56 | dart tooling-daemon --machine                                                              |
|  82 MB | 0.3% |        02:54 | dart tooling-daemon --machine                                                              |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`/home/albin/fvm/versions/3.26.0-0.1.pre/bin/flutter doctor -v`

```text
[✓] Flutter (Channel beta, 3.26.0-0.1.pre, on Manjaro Linux 6.1.111-1-MANJARO, locale en_US.UTF-8)
    • Flutter version 3.26.0-0.1.pre on channel beta at /home/albin/fvm/versions/3.26.0-0.1.pre
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee624bc4fd (5 weeks ago), 2024-09-10 17:41:06 -0500
    • Engine revision 059e4e6d8f
    • Dart version 3.6.0 (build 3.6.0-216.1.beta)
    • DevTools version 2.39.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/albin/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/brave

[✓] Linux toolchain - develop for Linux desktop
    • clang version 18.1.8
    • cmake version 3.30.3
    • ninja version 1.12.1
    • pkg-config version 2.1.1

[✓] Android Studio (version 2024.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 81.0.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[✓] IntelliJ IDEA Community Edition (version 2024.2)
    • IntelliJ at /home/albin/IntelliJ/idea-IC-242.20224.387
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Manjaro Linux 6.1.111-1-MANJARO
    • Chrome (web)    • chrome • web-javascript • Brave Browser 129.1.70.123

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by DanTup** [comment]
Currently the analysis server does not support passing experiments to the formatter, so it does not enable macro support when formatting.

There's an open issue about this at https://github.com/dart-lang/sdk/issues/55125. Once that's resolved (or macros is controlled by a language version rather than an experiment flag) this will work as expected.
