### ISSUE TITLE
Inlay hints initially displayed when vscode is launched with dart file as active tab.

### ISSUE THREAD

**Issue by woprandi** [Dart-Code/Dart-Code#5313]
**Describe the bug**
When opening VSCode with a dart file as last active tab, the "Inlay hints" (inferred type) are always displayed initially  until  another tab get active. 

**To Reproduce**
1. Close vscode with a opened dart file
2. Re-Open vscode
3. Inlay hints are displayed on the active dart file
4. Open another tab (file or settings)
5. Inlay hints disappears

**Expected behavior**
Inlay hints should not appear initially 

**Screenshots**
[Capture vidéo du 2024-10-16 10-20-26.webm](https://github.com/user-attachments/assets/a4c902e6-7653-4016-8768-eee48ec7c3e6)

**Please complete the following information:**

 - Operating System and version: Fedora 40 
 - VS Code version: 1.94.2
 - Dart extension version: 3.98.1
 - Dart/Flutter SDK version: 
 

> Flutter 3.26.0-0.1.pre • channel beta • https://github.com/flutter/flutter.git
> Framework • revision ee624bc4fd (il y a 5 semaines) • 2024-09-10 17:41:06 -0500
> Engine • revision 059e4e6d8f
> Tools • Dart 3.6.0 (build 3.6.0-216.1.beta) • DevTools 2.39.0

 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
Thanks for the report! This appears to be a VS Code bug - the display of Inlay Hints is controlled entirely by VS Code, we simply supply the data for it when requested. There's an open issue at https://github.com/microsoft/vscode/issues/230498 you should add a 👍 too. Thanks!

**Comment by woprandi** [comment]
@DanTup Ok sorry for the mistake

**Comment by DanTup** [comment]
No problem, it's often very difficult to know where the bug lies. I'd rather get additional reports here than potentially miss out on bug reports, so please do continue to file issues here if you're not sure :-)

**Comment by FMorschel** [comment]
The VSCode issue was closed today and the latest Insiders build has the fix. Should probably be fixed on the next stable release too.
