### ISSUE TITLE
visual studio code F5 gets exception, shift-F5 doesn't

### ISSUE THREAD

**Issue by brucer42** [Dart-Code/Dart-Code#5315]
**Describe the bug**
flutter firebase initializeApp run w/ F5 in visual studio code gets exception firebase_core_web/src/interop/core.dart line 60

**To Reproduce**

**Expected behavior**
I expect code to succeed as it does from CLI or using shift-F5

main.dart:

import 'package:flutter/material.dart';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';

import 'firebase_options.dart';

import 'routes/firebaseloginroute.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(MyApp()); <<<<----- never gets here
}
...

**Screenshots**

** Call stack from exception **
app$ (/Users/brucer42/.pub-cache/hosted/pub.dev/firebase_core_web-2.18.1/lib/src/interop/core.dart:60)
initializeApp (/Users/brucer42/.pub-cache/hosted/pub.dev/firebase_core_web-2.18.1/lib/src/firebase_core_web.dart:262)
<asynchronous gap> (Unknown Source:0)
<closure> (/Users/brucer42/.pub-cache/hosted/pub.dev/firebase_core_web-2.18.1/lib/src/firebase_core_web.dart:167)
<asynchronous gap> (Unknown Source:0)
injectSrcScript (/Users/brucer42/.pub-cache/hosted/pub.dev/firebase_core_web-2.18.1/lib/src/firebase_core_web.dart:162)
injectSrcScript (/Users/brucer42/.pub-cache/hosted/pub.dev/firebase_core_web-2.18.1/lib/src/firebase_core_web.dart:110)
<closure> (/Users/brucer42/.pub-cache/hosted/pub.dev/firebase_core_web-2.18.1/lib/src/firebase_core_web.dart:192)
_initializeCore (/Users/brucer42/.pub-cache/hosted/pub.dev/firebase_core_web-2.18.1/lib/src/firebase_core_web.dart:186)
_initializeCore (/Users/brucer42/.pub-cache/hosted/pub.dev/firebase_core_web-2.18.1/lib/src/firebase_core_web.dart:176)
initializeApp (/Users/brucer42/.pub-cache/hosted/pub.dev/firebase_core_web-2.18.1/lib/src/firebase_core_web.dart:225)
initializeApp (/Users/brucer42/.pub-cache/hosted/pub.dev/firebase_core_web-2.18.1/lib/src/firebase_core_web.dart:221)
initializeApp (/Users/brucer42/.pub-cache/hosted/pub.dev/firebase_core-3.6.0/lib/src/firebase.dart:66)
initializeApp (/Users/brucer42/.pub-cache/hosted/pub.dev/firebase_core-3.6.0/lib/src/firebase.dart:39)
main$ (/Users/brucer42/git/bdfd/lib/main.dart:15)
main$ (/Users/brucer42/git/bdfd/lib/main.dart:13)
<closure> (/Users/brucer42/git/bdfd/web_entrypoint.dart:24)
<asynchronous gap> (Unknown Source:0)
main (/Users/brucer42/git/bdfd/web_entrypoint.dart:19)
main$ (/Users/brucer42/git/bdfd/web_entrypoint.dart:18)
**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

 **!! ⚠️ PLEASE REVIEW THIS REPORT FOR SENSITIVE INFORMATION BEFORE SHARING ⚠️ !!**

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.99.20241007
Flutter extension: 3.99.20240930 (activated)

App: Visual Studio Code
App Host: desktop
Version: mac 1.94.2

Workspace type: Flutter (LSP)
Workspace name: bdfd

Dart (3.5.3): /Users/brucer42/Downloads/flutter/bin/cache/dart-sdk
Flutter (3.24.3): /Users/brucer42/Downloads/flutter (Chrome (web-javascript/web))

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`/Users/brucer42/Downloads/flutter/bin/cache/dart-sdk/bin/dart info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.5.3 (stable) (Wed Sep 11 16:22:47 2024 +0000) on "macos_x64"
- on macos / Version 12.7.6 (Build 21H1320)
- locale is en-US

#### Project info

- sdk constraint: '>=3.0.0-322.0.dev <4.0.0'
- dependencies: cupertino_icons, firebase_auth, firebase_core, flutter, flutter_easyloading, flutter_search_bar, google_maps_flutter, google_maps_flutter_web, google_sign_in, http, provider, universal_html, url_launcher
- dev_dependencies: flutter_lints, flutter_test

#### Process info

| Memory |  CPU | Elapsed time | Command line                                                                               |
| -----: | ---: | -----------: | ------------------------------------------------------------------------------------------ |
|  23 MB | 0.0% |        11:01 | dart devtools --machine --allow-embedding --dtd-uri ws:<path>/1K0jBByyShkrcRQ0             |
|  23 MB | 0.0% |        14:39 | dart devtools --no-launch-browser                                                          |
| 186 MB | 0.0% |        11:03 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.99.20241007     |
|  32 MB | 0.0% |        11:03 | dart tooling-daemon --machine                                                              |
|  50 MB | 0.0% |        11:03 | flutter_tools.snapshot daemon                                                              |
|  56 MB | 0.0% |        10:24 | flutter_tools.snapshot debug_adapter                                                       |
|  77 MB | 0.7% |        10:23 | flutter_tools.snapshot run --machine --start-paused -d chrome --devtools-server-address http:<path>/ --target <path>/main.dart |
| 122 MB | 0.5% |        15:23 | flutter_tools.snapshot run -d chrome                                                       |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`/Users/brucer42/Downloads/flutter/bin/flutter doctor -v`

```text
[✓] Flutter (Channel stable, 3.24.3, on macOS 12.7.6 21H1320 darwin-x64, locale en-US)
    • Flutter version 3.24.3 on channel stable at /Users/brucer42/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (5 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/brucer42/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    ! Flutter recommends a minimum Xcode version of 15.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.94.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.7.6 21H1320 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 129.0.6668.101
    ! Error: Failed to prepare the device for development. This operation can fail if the version of the OS on the device is incompatible with the installed version of Xcode. You may also need to restart your Mac and device in order to correctly detect compatibility. (code 806)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by DanTup** [comment]
@brucer42 are you able to provide a complete code sample that triggers this? The code above references some files that don't exist (`firebase_options.dart` and `routes/firebaseloginroute.dart`). Thanks!
