### ISSUE TITLE
VSCode does not report errors in Dart files, even though diagnostics appears to be returning them

### ISSUE THREAD

**Issue by schdck** [Dart-Code/Dart-Code#5316]
## **Describe the bug**
Visual Studio Code won't highlight errors, even though the Analyzer logs indicate they are being returned.

For example, I had a class with a named constructor called `withLoadDataError`, which expects a required parameter called `currentFilter`. If I call that constructor without providing the parameter, VSCode does not highlight any errors at all. If I hover the method, it correctly shows the signature (which includes the required parameter), but no errors. Quick actions is also empty. I attached an screenshot that shows what I just described.

I followed [these steps](https://dartcode.org/docs/logging/#analyzer-instrumentation) to get logs and can see the one entry containing 3 problems (which are all valid), but none of them is reported in VSCode UI. The log entry is attached at the end of this post.

If I try to start a debug session, the Debug Console correctly reports the errors, but they still don't show in the file itself or in the project's "problems" tab in VSCode:

> Failed to build iOS app
Error (Xcode): .../bloc_initialization.dart:20:48: Error: Required named parameter 'currentFilter' must be provided.
Could not build the application for the simulator.
Error launching application on iPhone 15.

If I modify things as the class name, IntelliSense will get completely lost and start reporting some weird errors. I attached a video to this post to show the full behavior. I captured logs while recording the video, also attaching them to the post.

## **To Reproduce**
I did not find a reliable way to reproduce yet, but it appears to be related to copying an entire folder and start modifying it. The Flutter app was in debug mode, not sure if it changes anything.

In this case, it is a Flutter app and I have one folder per screen. I copied one of the folders and started modifying the files in it, and suddently IntelliSense does not report errors.

## **Expected behavior**
I expected VSCode to report the error on those lines.

## **Screenshots**

<img width="855" alt="Screenshot 2024-10-18 at 22 46 50" src="https://github.com/user-attachments/assets/2ab63e74-b250-48e0-9352-3aa8613802b9">

## **Please complete the following information:**

```
Dart Code extension: 3.98.1
Flutter extension: 3.98.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: mac 1.94.2

Workspace type: Dart, Flutter (LSP)
Workspace name: mobile-flutter

Dart (3.5.3): /Users/mauricioschmaedeck/Dev/flutter/bin/cache/dart-sdk
Flutter (3.24.3): /Users/mauricioschmaedeck/Dev/flutter (iPhone 15 (ios/ios))
```

## **Entry in captured logs**:

```
{
    "jsonrpc": "2.0",
    "method": "textDocument/publishDiagnostics",
    "params": {
        "diagnostics": [
            {
                "code": "invalid_constant",
                "message": "Invalid constant value.",
                "range": {
                    "end": {
                        "character": 29,
                        "line": 7
                    },
                    "start": {
                        "character": 9,
                        "line": 7
                    }
                },
                "relatedInformation": [
                    {
                        "location": {
                            "range": {
                                "end": {
                                    "character": 12,
                                    "line": 0
                                },
                                "start": {
                                    "character": -1,
                                    "line": 0
                                }
                            },
                            "uri": "file:///.../state.dart"
                        },
                        "message": "The error is in the super constructor invocation of 'LoadingState', and occurs here."
                    }
                ],
                "severity": 1,
                "source": "dart"
            },
            {
                "code": "missing_required_argument",
                "codeDescription": {
                    "href": "https://dart.dev/diagnostics/missing_required_argument"
                },
                "message": "The named parameter 'currentFilter' is required, but there's no corresponding argument.\nTry adding the required argument.",
                "range": {
                    "end": {
                        "character": 27,
                        "line": 7
                    },
                    "start": {
                        "character": 15,
                        "line": 7
                    }
                },
                "severity": 1,
                "source": "dart"
            },
            {
                "code": "missing_required_argument",
                "codeDescription": {
                    "href": "https://dart.dev/diagnostics/missing_required_argument"
                },
                "message": "The named parameter 'currentFilter' is required, but there's no corresponding argument.\nTry adding the required argument.",
                "range": {
                    "end": {
                        "character": 22,
                        "line": 13
                    },
                    "start": {
                        "character": 11,
                        "line": 13
                    }
                },
                "severity": 1,
                "source": "dart"
            }
        ],
        "uri": "file:///.../bloc_initialization.dart"
    }
}
```

## Captured video

[video_capture_logs.txt](https://github.com/user-attachments/files/17442189/video_capture_logs.txt)

https://github.com/user-attachments/assets/4ace82bf-6b00-498a-9fcf-0f6ed6869f6e

**Comment by DanTup** [comment]
@schdck are you able to reproduce this in a project you can share?

**Comment by schdck** [comment]
@DanTup sorry, I don't. I haven't found a 100% reliable way of reproducing this even in the project I'm frequently working on, it is intermittent. Appears to be related to copying folders/files around, but haven't figured out what exactly triggers this
