### ISSUE TITLE
widget inspector

### ISSUE THREAD

**Issue by saksham-81** [Dart-Code/Dart-Code#5317]
**Describe the bug**
the widget inspector looks so magnified

**Expected behavior**
it should look normal and everything should be visible

**Screenshots**
![image](https://github.com/user-attachments/assets/b62c58e1-225d-4e35-98ac-9bd54255e587)

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

 - Operating System and version:
 - VS Code version:
 - Dart extension version:
 - Dart/Flutter SDK version:
 - Target device (if the issue relates to Flutter debugging):
**!! ⚠️ PLEASE REVIEW THIS REPORT FOR SENSITIVE INFORMATION BEFORE SHARING ⚠️ !!**

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.98.1
Flutter extension: 3.98.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: win 1.94.2

Workspace type: Flutter (LSP)
Workspace name: employee-app

Dart (3.4.4): C:\Users\chhab\AppData\Local\flutter\bin\cache\dart-sdk
Flutter (3.22.3): C:\Users\chhab\AppData\Local\flutter (Redmi Note 8 Pro (android-arm64/android))

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`C:\Users\chhab\AppData\Local\flutter\bin\cache\dart-sdk\bin\dart.exe info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.4.4 (stable) (Wed Jun 12 15:54:31 2024 +0000) on "windows_x64"
- on windows / "Windows 10 Home Single Language" 10.0 (Build 22631)
- locale is en-IN

#### Project info

- sdk constraint: '>=3.1.3 <4.0.0'
- dependencies: auto_size_text, cached_network_image, cupertino_icons, dartz, dio, dropdown_button2, equatable, file_picker, firebase_core, firebase_messaging, fl_chart, flash, flextras, flutter, flutter_bloc, flutter_dotenv, flutter_hooks, flutter_image_compress, flutter_screenutil, flutter_svg, flutter_widget_from_html, get_it, go_router, google_fonts, graphql, image_picker, infinite_scroll_pagination, internet_connection_checker, intl, just_audio, logger, lottie, matrix2d, moengage_flutter, multi_dropdown, objectbox, objectbox_flutter_libs, package_info_plus, path, path_provider, permission_handler, photo_view, pie_chart, pin_code_fields, record, rxdart, shared_preferences, stream_chat_flutter, stream_chat_persistence, timeline_tile, uuid, video_thumbnail, wc_form_validators
- dev_dependencies: build_runner, flutter_lints, flutter_test, objectbox_generator

#### Process info

| Memory | CPU | Elapsed time | Command line |
| -----: | --: | -----------: | ------------ |
|  11 MB |  -- |              | dart.exe     |
|  26 MB |  -- |              | dart.exe     |
| 161 MB |  -- |              | dart.exe     |
|  45 MB |  -- |              | dart.exe     |
| 254 MB |  -- |              | dart.exe     |
| 216 MB |  -- |              | dart.exe     |
|  96 MB |  -- |              | dart.exe     |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`C:\Users\chhab\AppData\Local\flutter\bin\flutter.bat doctor -v`

```text
[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.22631.4317], locale en-IN)
    • Flutter version 3.22.3 on channel stable at C:\Users\chhab\AppData\Local\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (3 months ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\chhab\AppData\Local\Android\sdk
    • Platform android-34, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] VS Code (version 1.94.2)
    • VS Code at C:\Users\chhab\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.98.0

[√] Connected device (5 available)
    • Redmi Note 8 Pro (mobile) • aeofemhiheqsibu4     • android-arm64  • Android 11 (API 30)
    • Redmi Note 8 Pro (mobile) • 192.168.29.212:55555 • android-arm64  • Android 11 (API 30)
    • Windows (desktop)         • windows              • windows-x64    • Microsoft Windows [Version 10.0.22631.4317]
    • Chrome (web)              • chrome               • web-javascript • Google Chrome 129.0.6668.90
    • Edge (web)                • edge                 • web-javascript • Microsoft Edge 130.0.2849.46

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by DanTup** [comment]
Thanks for the report - there's an existing issue about this at https://github.com/Dart-Code/Dart-Code/issues/5276 so I'll close this one as a dupe.
