### ISSUE TITLE
Remove allowlist for recommended extensions

### ISSUE THREAD

**Issue by incendial** [Dart-Code/Dart-Code#5321]
Hi, given the Dart VS Code extension supports suggesting VS Code extensions based on the installed packages, it would be great to either remove [the allow list](https://github.com/Dart-Code/Dart-Code/blob/master/src/extension/sdk/dev_tools/manager.ts#L550) or have a clear process of how a new extension can be added there.

For DCM, we have a presets package https://github.com/CQLabs/dart-code-metrics-presets that clearly indicates that the project uses DCM and therefore the user would benefit from such a notification if the DCM extension is not installed.

Also, if the required configuration is not documented anywhere, it would be great to have documentation for it as well.

**Comment by jwren** [comment]
Sounds good to me, include this issue in the comments with the change for documentation prosperity.  We can always change our mind in the future with other information.

**Comment by kenzieschmoll** [comment]
Removing the allowlist sgtm. I filed an issue to create docs on contributing to tooling on flutter.dev: https://github.com/flutter/website/issues/11339
