### ISSUE TITLE
Dart code in vscode semantic token type seems wired.

### ISSUE THREAD

**Issue by allnan** [Dart-Code/Dart-Code#5324]
Hello there，
 there are some issues when custom my vscode code hightlight.
![image](https://github.com/user-attachments/assets/f46084f5-e95e-4c86-8dd3-0e72775461dd)

I think both key1 and key2 are parameter.label , but why doesn't key1 have modifiers? How can I fix this, thank you.

environment:
Dart Code extension: 3.98.1
Flutter extension: 3.98.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: win 1.94.2

**Comment by DanTup** [comment]
I'm not sure why the modifier is missing, I'll take a look.

Something else that is odd in your screenshot is that the left `key1` screenshot doesn't show a semantic token type at all. Can you reproduce this and copy/paste the exact code? For me, it seems to have a semantic token type of parameter still:

![image](https://github.com/user-attachments/assets/b832d2c7-50ce-4290-9956-830ac260af08)

**Comment by DanTup** [comment]
https://dart-review.googlesource.com/c/sdk/+/392582 will fix the issue of modifiers not being included on `dynamic` parameters. It's a fix in the Dart SDK, so it'll show up in a future Dart/Flutter SDK release.

I'll keep this issue open until the fix is merged.

**Comment by DanTup** [comment]
The fix was merged in https://github.com/dart-lang/sdk/commit/37af167cc5625c48663af1f20799e234cdd53c55.

**Comment by DanTup** [comment]
I forgot to close this when the fix merged. This ships in a future Dart/Flutter SDK.
