### ISSUE TITLE
Still No ANSI Colors in VSCode 1.94+ in Flutter debugger when debugging IOS target device

### ISSUE THREAD

**Issue by timmaffett** [Dart-Code/Dart-Code#5332]
**Describe the bug**
The issue with broken ANSI output in VSCode on OSX still exists when debugging target IOS/IPhone Simulator apps
(see previous issue https://github.com/Dart-Code/Dart-Code/issues/5302  - the PR that resolved #5302 did not fix the IOS device output)

**To Reproduce**

On OSX go to terminal, and create a new flutter project

```
flutter create ansitest
cd ansitest
code .
```

modify main() as follows:
```
void main() {

  print("\u001b[1;31m Red message");
  print("\u001b[1;32m Green message");
  print("\u001b[1;33m Yellow message");
  print("\u001b[1;34m Blue message");
  print("\u001b[1;35m Purple message");
  print("\u001b[1;36m Cyan message");

  runApp(const MyApp());
}
```

Select MacOS - mac os descktop - Run and see that output is correctly colored

Select IPhone Simulator as target device - Run and see that output is broken, showing escape sequences and no color.

**Expected behavior**
The print statements in the main() function are printed to the debug console in their respective colors:
(Setting target device to `MacOS (darwin)`)
![Screenshot 2024-11-08 at 1 14 37 PM](https://github.com/user-attachments/assets/c16ebc2d-54e0-4646-bd97-6c860db280c3)

**Screenshots**

Setting target device to `iPhone 15 Pro (ios simulator)`
[
![Screenshot 2024-11-08 at 1 08 12 PM](https://github.com/user-attachments/assets/f9633923-b8fe-493e-aebb-1628bff6ed12)
](url)

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

 - Operating System and version:
 `MacOSX Sequoia 15.1`
 
 - VS Code version:
 ```
Version: 1.95.1 (Universal)
Commit: 65edc4939843c90c34d61f4ce11704f09d3e5cb6
Date: 2024-10-31T05:14:54.222Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.1.0
```

 - Dart extension version:
 ```
Dart v3.101.20241031 (pre-release)
Flutter v3.101.20241031 (pre-release)
```

 - Dart/Flutter SDK version:
```
% flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.27.0-1.0.pre.402, on macOS 15.1 24B83 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.95.1)
[✓] Connected device (4 available)
[✓] Network resources
• No issues found!
```

 - Target device (if the issue relates to Flutter debugging):
`iPhone 15 Pro (ios simulator)`

works correctly if target device is `Mac OS (darwin)`  (as illustrated in first screen shot)

**Comment by DanTup** [comment]
Ansi colours do not current work in iOS, the recent issue was related to Android only.

There are open issues for this in the Flutter repo:

- https://github.com/flutter/flutter/issues/20663
- https://github.com/flutter/flutter/issues/64491

Once supported in Flutter, it should work automatically here.
