### ISSUE TITLE
VS Code did not show expected list of AVDs after changing Android SDK and AVD path

### ISSUE THREAD

**Issue by ahmadshiddiqn** [Dart-Code/Dart-Code#5336]
**Describe the bug**
I changed the SDK path and AVD path to a new directory which were `D:\.android\Sdk` and `D:\.android\avd` respectively. On Android Studio, the list was correct and when I add new AVD it was created in the new directory. But when I try launching the AVD from VS Code, the list of AVDs were empty, and when I tried to create new emulator, it was created in the old directory (which was `C:\users\<user>\.android\avd`. I already add the new `ANDROID_AVD_HOME` env variables both in my Environment Variables and Path Variables in Android Studio. I tried running the emulator through adding using emulator custom path, but it still did not work (I tried running the emulator from terminal using `emulator -avd "Emulator_ID"`, it run fine, but this is another problem). I already run `fultter doctor -v` to check whether Android SDK was detected in the new path, and it was OK.

**To Reproduce**
1. Change Android SDK path in Android Studio to `D:\.android\Sdk`
2. Add ANDROID_AVD_HOME path in Android Studio that refers `D:\.android\avd`. Add it also in Environment Variables
3. Change Android SDK path in VS Code to `D:\.android\Sdk`
4. Restart Android Studio and VS Code (if it was running)
5. See the change

**Expected behavior**
The AVDs list in Android Studio and VS Code should be the same

**Screenshots**
![image](https://github.com/user-attachments/assets/20c296bc-d301-4d4f-8e46-0616bd166988)
![image](https://github.com/user-attachments/assets/e66e3aa1-4dc7-4c9e-8722-15ad58dcb6e2)
![image](https://github.com/user-attachments/assets/8238b10a-f1e9-47d5-8154-17e379bfd169)
![image](https://github.com/user-attachments/assets/6a9c3cc9-f67f-45a5-92e7-a76a1d562819)
![image](https://github.com/user-attachments/assets/ce8c2d00-0c07-44d6-93e0-d3631a28e504)
![image](https://github.com/user-attachments/assets/4f562c45-59c7-420a-a7ed-a6e5b3df7557)
![image](https://github.com/user-attachments/assets/144b3f70-8d5c-45ef-88c4-7b282d9f54c1)
![image](https://github.com/user-attachments/assets/e63f7aa4-48f1-41d1-9442-115f2d0dd0aa)
![image](https://github.com/user-attachments/assets/a927b838-6d7b-4db1-a8b9-f2b1b2524e7f)

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

 - Operating System and version: Windows 10 64-bit Pro 22H2 19045.5011 (Windows_NT x64 10.0.19045)
 - VS Code version: 1.95.2
 - Dart Code extension: 3.100.0
 - Flutter extension: 3.100.0
![image](https://github.com/user-attachments/assets/6e721aae-c5a2-4813-96ed-72096ced4453)

**Comment by ahmadshiddiqn** [comment]
I simply restart my computer, even though I had already restarted the VS Code many times. I thought restarting VS Code should do the justice, but after seeing the difference behavior from terminal I opened in VS Code and terminal I opened from outside of VS Code, I decided to just restart the computer. It is fixed now

**Comment by DanTup** [comment]
Environment variables are inherited from parent processes, so if you change the environment variables but have an existing terminal open, then launching new processes from that terminal will still use the old environment variables.

Windows also sometimes seem to launch apps from the start menu using stale environment variables. My advice when changing environment variables if something doesn't work is always to reboot, as it often resolves issues like this.

Glad you've got it working now!
