### ISSUE TITLE
flutter icon not showen suddenly and the emulation not showen too

### ISSUE THREAD

**Issue by Youssef2793** [Dart-Code/Dart-Code#5339]
Type: <b>Feature Request</b>

i was working on project on visual studio on flutter and suddenly flutter plugin icon disappeared and i was emulating my mobile and now the button on the status bar called "no device" now is not Showen again and it give me error every time i emulate 
 

Extension version: 3.100.0
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by DanTup** [comment]
It sounds like the extension might not have activated correctly. Can you try:

1. Run the "Show Running Extensions" command from the command palette (`F1`) and check whether the extensions show as activated:
    ![image](https://github.com/user-attachments/assets/52177160-9953-414f-9d18-839c669e5223)
2. Click Help -> Toggle Developer Tools and then click on the Console tab, and see if there are any errors like "Failed to activate" that might indicate that the Dart/Flutter extensions failed to activate correctly

Thanks!
