### ISSUE TITLE
Analyzer path settings shows different message and missing description info

### ISSUE THREAD

**Issue by FMorschel** [Dart-Code/Dart-Code#5345]
After setting `analyzerPath` for the first time I got:

```console
Could not find a Dart Analysis Server at C:\Users\felip_0vh5fa6\Documents\Projects\dart\bug\C:serselip_0vh5fa6ocumentsrojectslonesart-sdk2dkkgnalysis_serverinerver.dart
```

The current project path:

```
C:\Users\felip_0vh5fa6\Documents\Projects\dart\bug\
```

And this is what I've placed on the variable:

```json
"dart.analyzerPath": "C:/Users/felip_0vh5fa6/Documents/Projects/clones/dart-sdk2/sdk/pkg/analysis_server/bin/server.dart"
```

After some talk on Discord. I'd like to request that it shows a similar message as when the SDK path is not valid. Not displaying the full output. Or doing so for the other path settings.

---

Also, I'd like to request that these paths that accept the use of `~/path/to/something` also say so in the description. Similar to the description for the log files.

**Comment by DanTup** [comment]
![image](https://github.com/user-attachments/assets/11f359ea-123d-4284-a47e-7cc8c8452fae)

**Comment by FMorschel** [comment]
Looking at the diff, you've not added to the description that they accept ~ for home? Should I open a new issue to ask for this?

**Comment by FMorschel** [comment]
Missed it, sorry! I thought it was a PR about this you made, not another issue. Thanks!
