### ISSUE TITLE
Quick fix doesn't work for classes extending a generic

### ISSUE THREAD

**Issue by HosseinYousefi** [Dart-Code/Dart-Code#5349]
Consider this:

```dart
abstract class Bar<T> {}
class Foo extends Bar<void> {
  final int a;
}
```

When trying to use quick fix to generate a constructor, it does not show anything. It does work when extending non-generic classes.

https://github.com/user-attachments/assets/cf5bcbab-14ab-4e64-9880-2db7d8ba5b19

```text
Dart Code extension: 3.100.0
Flutter extension: 3.100.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: mac 1.95.3

Workspace type: Dart, Flutter (LSP)

Dart (3.7.0-47.0.dev)
Flutter (3.27.0-1.0.pre.157)
```

**Comment by DanTup** [comment]
What version of Dart/Flutter SDKs are you using? I tried to repro on both stable and latest master, but the quick fix shows up:

![image](https://github.com/user-attachments/assets/ca6fc597-95ec-4a62-ae09-26f385c05efb)

I see you have another extension contributing some code actions (Wrap with BlocBuilder etc.) - could you try temporarily disabling those extensions (and reloading VS Code) to see if they are affecting this at all? Thanks!

**Comment by HosseinYousefi** [comment]
Seems to fixed on the lastest master! Thanks.
