### ISSUE TITLE
Analyser reports missing case in switch when all cases are accounted for.

### ISSUE THREAD

**Issue by klukshu** [Dart-Code/Dart-Code#5366]
**Describe the bug**
I am trying to use a sealed class to define the attributes of a user profile. It is not known at compile time what data will be in each profile, so I used a switch to return the widget that needs to be displayed. Using the suggested actions I added all the cases, but the analyzer still reports that they are missing. I have confirmed all the cases are present, and in fact the Quick fix will suggest adding duplicates. Flutter analyze reports the same error, and a server restart does not change anything.

This is the code that is producing the bug, the error is in profile view:
https://github.com/klukshu/sealed_class_switch_always_reporting_missing_case

**Expected behavior**

When all the sub classes are present I would expect the analyzer would not report that some are missing.

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.102.0
Flutter extension: 3.102.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: linux 1.95.3

Workspace type: Flutter (LSP)
Workspace name: sealed_class_switch_always_reporting_missing_case

Dart (3.5.1): /home/graham/development/flutter/bin/cache/dart-sdk
Flutter (3.24.1): /home/graham/development/flutter (No device)

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`/home/graham/development/flutter/bin/cache/dart-sdk/bin/dart info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.5.1 (stable) (Tue Aug 13 21:02:17 2024 +0000) on "linux_x64"
- on linux / Linux 6.8.0-49-generic #49-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov  4 02:06:24 UTC 2024
- locale is en_CA.UTF-8

#### Project info

- sdk constraint: '^3.5.1'
- dependencies: flutter
- dev_dependencies: flutter_lints, flutter_test

#### Process info

| Memory |  CPU | Elapsed time | Command line                                                                     |
| -----: | ---: | -----------: | -------------------------------------------------------------------------------- |
|  70 MB | 0.0% |        21:03 | dart devtools --machine --allow-embedding --dtd-uri ws:<path>/TOCqUhIfqYBQrM2p   |
|  70 MB | 0.0% |        35:50 | dart devtools --machine --allow-embedding --dtd-uri ws:<path>/fkivtWtsPsipZOSc   |
| 542 MB | 0.3% |        35:50 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.102.0 |
| 526 MB | 0.4% |        21:03 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.102.0 |
|  82 MB | 0.0% |        35:50 | dart tooling-daemon --machine                                                    |
|  82 MB | 0.0% |        21:04 | dart tooling-daemon --machine                                                    |
| 116 MB | 0.1% |        35:50 | flutter_tools.snapshot daemon                                                    |
| 105 MB | 0.1% |        21:04 | flutter_tools.snapshot daemon                                                    |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

```text
[✓] Flutter (Channel stable, 3.24.1, on Linux Mint 22 6.8.0-49-generic, locale en_CA.UTF-8)
    • Flutter version 3.24.1 on channel stable at REDACTED
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (4 months ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /home/graham/Android/Sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /home/graham/Android/Sdk
    • Java binary at: /usr/local/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    • pkg-config version 1.8.1
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)

[✓] Android Studio (version 2024.1)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.95.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.102.0

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux Mint 22 6.8.0-49-generic

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by DanTup** [comment]
@klukshu you're right that there is a bug here in that the fix adds a duplicate, but it also adds `ProfileSexualOrientation` which is currently missing. If I remove the dupe, the warning goes away.

So I think the issue here is that the quick-fix adds a duplicate case rather than the error mis-firing.

**Comment by DanTup** [comment]
Actually, it's not a duplicate - the first entry here `ProfileName()` is a reference to a class in the same file (`class ProfileName extends StatelessWidget`), and not the `ProfileAttribute` class.

So I think the bug here is that the quick-fix doesn't account for naming collisions where some of the entries it adds are not valid to just reference by name.

I've opened https://github.com/dart-lang/sdk/issues/59701 about this, since it would need to be changed in analysis server.
