### ISSUE TITLE
Miss on highlight

### ISSUE THREAD

**Issue by FMorschel** [Dart-Code/Dart-Code#5369]
**Describe the bug**
If you ask for a highlight it shows every occurrence of that word.

**To Reproduce**
1. Clone https://github.com/FMorschel/sdk/
2. Go to [26241c9e8676b9bff7cef168de49a08b939ea800](https://github.com/FMorschel/sdk/commit/26241c9e8676b9bff7cef168de49a08b939ea800)
3. Open `pkg/analysis_server/lib/src/lsp/handlers/handler_completion.dart`
4. Leave the cursor at the first `element` (the new var) on line 481.

**Expected behavior**
For the highlight to be contained to a single variable (or to not show).
`element` on 506 and 507 as well as at the end of 481 should not be highlighted.

**Screenshots**
![image](https://github.com/user-attachments/assets/3601a466-d225-4741-a121-978f8dde4c33)

**Please complete the following information:**

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.103.20241211
Flutter extension: 3.103.20241202 (activated)

App: Visual Studio Code
App Host: desktop
Version: win 1.96.0

Workspace type: Dart (LSP) (Multiroot)
Workspace name: server2 (Workspace)

Dart (3.7.0-edge.d76f568f0e2280a59b3378bec95a00fee3f4ecbf): C:\Users\felip_0vh5fa6\dart
Flutter (3.27.0): C:\Users\felip_0vh5fa6\.puro\envs\stable\flutter (No device)

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`C:\Users\felip_0vh5fa6\dart\bin\dart.exe info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.7.0-edge.d76f568f0e2280a59b3378bec95a00fee3f4ecbf (main) (Fri Dec 13 06:29:44 2024 -0800) on "windows_x64"
- on windows / "Windows 11 Pro" 10.0 (Build 22631)
- locale is pt-BR

#### Project info

- sdk constraint: '>=3.7.0-edge <4.0.0'
- dependencies: _fe_analyzer_shared, analysis_server_plugin, analyzer, analyzer_plugin, args, collection, convert, crypto, dart_style, dtd, http, json_rpc_2, language_server_protocol, linter, matcher, memory_usage, meta, path, pub_semver, stream_channel, telemetry, unified_analytics, vm_service, watcher, yaml, yaml_edit
- dev_dependencies: analyzer_utilities, cli_util, lints, logging, test, test_descriptor, test_reflective_loader, web_socket_channel

#### Process info

| Memory | CPU | Elapsed time | Command line |
| -----: | --: | -----------: | ------------ |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |

</details>

**Comment by DanTup** [comment]
Seems like we're throwing an error here:

```
[3:38:50 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":107,"method":"textDocument/documentHighlight","params":{"textDocument":{"uri":"file:///D%3A/Dev/Google/dart-sdk/sdk/pkg/analysis_server/lib/src/lsp/handlers/handler_completion.dart"},"position":{"line":505,"character":33}},"clientRequestTime":1734363530728}
[3:38:50 PM] [Analyzer] [Info] <== {"id":107,"jsonrpc":"2.0","error":{"code":-32001,"message":"An error occurred while handling textDocument/documentHighlight request"}}
```

**Comment by DanTup** [comment]
This is fixed by https://github.com/dart-lang/sdk/commit/9820487a3c4d7e16615c2605f2844c6bd56b150e:

![image](https://github.com/user-attachments/assets/0dcd10ce-5969-40cc-af8c-4ba4fc8b4c31)

(Fix ships in a future SDK release, not Dart-Code!)

**Comment by FMorschel** [comment]
Just as a reference, we also have https://github.com/Dart-Code/Dart-Code/issues/4454 about highlights to fix.
