### ISSUE TITLE
Invalid constant value error when extracting a widget with a const TextStyle parameter

### ISSUE THREAD

**Issue by stephane-archer** [Dart-Code/Dart-Code#5374]
``` Dart
import 'package:flutter/material.dart';

class A extends StatelessWidget {
  const A({super.key});

  @override
  Widget build(BuildContext context) {
    const TextStyle h1 = TextStyle(color: Colors.red);
    return const Text("hello world", style: h1);
  }
}
```
extract widget `Text("hello world", style: h1);`
# result:
``` Dart
import 'package:flutter/material.dart';

class A extends StatelessWidget {
  const A({super.key});

  @override
  Widget build(BuildContext context) {
    const TextStyle h1 = TextStyle(color: Colors.red);
    return ExtractedWidget(h1: h1);
  }
}

class ExtractedWidget extends StatelessWidget {
  const ExtractedWidget({
    super.key,
    required this.h1,
  });

  final TextStyle h1;

  @override
  Widget build(BuildContext context) {
    return const Text("hello world", style: h1);
  }
}
```
There is an error regarding `h1` `Invalid constant value.`

# expected result
Here is the correct code (the const keyword is not at the right place):
``` Dart
import 'package:flutter/material.dart';

class A extends StatelessWidget {
  const A({super.key});

  @override
  Widget build(BuildContext context) {
    const TextStyle h1 = TextStyle(color: Colors.red);
    return const ExtractedWidget(h1: h1);
  }
}

class ExtractedWidget extends StatelessWidget {
  const ExtractedWidget({
    super.key,
    required this.h1,
  });

  final TextStyle h1;

  @override
  Widget build(BuildContext context) {
    return Text("hello world", style: h1);
  }
}
```

**Comment by FMorschel** [comment]
Just to be clear @stephane-archer, these errors with refactors/assists/fixes are all under the SDK analyzer/analysis server or similar (commenting to you since I've seen some issues you opened there). We probably can fix them here but it'll still only come to the users in a new SDK release.

**Comment by FMorschel** [comment]
> Would you like me to move it there instead?

I'd say it's up to you or @DanTup which I don't think would mind having it here. But there are always more eyes there to possibly take a try on the fix.

If you move it, you can (and I'd suggest) always link to this one so we know where it came from and people who end up here know where this conversation moved to.
