### ISSUE TITLE
Implement refactor: Convert getter to method/method to getter in LSP

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#542]

**Comment by DanTup** [comment]
I don't think putting refactors on the lightbulb is a good idea, as they show up so frequently that there will just be bulbs everywhere always. I suggest these go on the context menu:

https://github.com/Microsoft/vscode/issues/9827

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/094e4fea1a738aac793bd96a6d345995a37df31c.

**Comment by 0833347379** [comment]
$$$
