### ISSUE TITLE
Implement refactor: Inline local variable

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#545]

**Comment by DanTup** [comment]
I don't think putting refactors on the lightbulb is a good idea, as they show up so frequently that there will just be bulbs everywhere always. I suggest these go on the context menu:

https://github.com/Microsoft/vscode/issues/9827

**Comment by svarlet** [comment]
Hi @DanTup , what's the status on this one?

**Comment by DanTup** [comment]
No progress, although I wonder if it might no longer be blocked by the Dart issue above for LSP. I'll assign to this milestone to have a look to see if that's the case (though no guarantees).

**Comment by DanTup** [comment]
Done in https://github.com/dart-lang/sdk/commit/8ae2eb94ff9d35af139677fe4458fd2493cb02c9.
