### ISSUE TITLE
Implement refactor: Inline method

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#547]

**Comment by DanTup** [comment]
I don't think putting refactors on the lightbulb is a good idea, as they show up so frequently that there will just be bulbs everywhere always. I suggest these go on the context menu:

https://github.com/Microsoft/vscode/issues/9827

**Comment by svarlet** [comment]
Hi @DanTup !
I just noticed the completion of the similar issue about inlining variables. What's the status on this issue? Inlining methods is an even more useful refactoring 😍

**Comment by DanTup** [comment]
@svarlet hoping to look at this shortly too :-)

**Comment by DanTup** [comment]
I've got a change open for this at https://dart-review.googlesource.com/c/sdk/+/197380/.

**Comment by DanTup** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/a89fccb482cb5d263ebbe0191dbd201f7af2603a.
