### ISSUE TITLE
Legacy debug handlers appear in dropdown

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#553]
Had two projects open in the workspace (flutter), a launch.json as active editor, then used the debug dropdown to add new config for one of them (Hello World) and this appeared:

Node2 isn't appearing, so why are our legacy ones?

<img width="673" alt="screen shot 2018-02-09 at 10 16 20" src="https://user-images.githubusercontent.com/1078012/36022907-9b0a478a-0d82-11e8-9721-22e9b39a4932.png">

**Comment by DanTup** [comment]
Here's a pic of Node2 being loaded but not appearing in the list.

![node2](https://user-images.githubusercontent.com/1078012/36089498-2ccb7cf4-0fd4-11e8-876c-00f2beb30176.png)

**Comment by DanTup** [comment]
I've asked @weinand about this here https://github.com/Microsoft/vscode/issues/43101#issuecomment-364865881 but I'm kinda tempted to just delete the legacy adapters. We do have an upgrade routine to fix the `launch.json`s (which has been reliable in my testing), the only complication is if people are sharing code and on different versions of Code/Dart Code (however that's kinda complicated anyway if the person on the newer version commits the launch.json change).

**Comment by weinand** [comment]
@DanTup when building the debug environment QuickPick list we only use those debug extensions that either contribute a static set of initial launch configs in their package.json or implement the corresponding method on their DebugConfigurationProvider.

**Comment by DanTup** [comment]
Aha! I was pointing them at the same DebugConfigurationProvider because without one it gave errors; I'll give it a try with a dummy one then. Cheers!

**Comment by weinand** [comment]
Maybe you don't need a DebugConfigurationProvider at all for your legacy DA?

**Comment by DanTup** [comment]
@weinand If I don't have one at all then people with the old ID in `launch.json` will get errors launching (I do have an upgrade to fix `launch.json` but want to still handle this for a little while).

I tried returning an empty array from `provideDebugConfigurations` and I *think* that's done the trick. I still need to handle the `resolve` case (which will update the ID to the new one) but I think I can just subclass the real provider override the `provide` method.

I'll give it a good test and shout if I get stuck!

**Comment by weinand** [comment]
Don't return an empty array, just don't implement  "provideDebugConfigurations". This method is optional and if it is not implemented VS Code will detect this.

**Comment by DanTup** [comment]
Seems to work perfectly, thanks! :D
