### ISSUE TITLE
add the ability to run dart CLI apps

### ISSUE THREAD

**Issue by devoncarew** [Dart-Code/Dart-Code#56]

**Comment by devoncarew** [comment]
@DanTup, heads up as per https://github.com/DanTup/Dart-Code/blob/master/CONTRIBUTING.md,  I may take a look at this -

**Comment by DanTup** [comment]
Awesome :)

I was thinking about this a little (function, not implementation), but I don't know anything about how this stuff works in Code. I guess a Dart project can have many entry points:

- many `.dart` files in `bin` folder
- many `.html` files in `web` folder(?)

Currently it looks like launching stuff goes into `launch.json`(?) but it seems a bit weird to tell users to go and configure lots of stuff there so they can just press `F5`. Is there a better way? Eg. let's say a user clones a program with two HTML files in `web` and two Dart files in `bin` and hits `F5`; what's the experience?

Also, for web stuff (I know this is very separate to running Dart CLI progs), I think it'd be nice to run Dart2JS/DDC(?) in the background when the user hits F5 (they do incremental compile, right?) so the user could make a change in Code, hit Save, then just Refresh in their browser. This seems to be how TS works (first time you hit F5/Build it starts a `Task` which runs and watches for future changes).

Interested to know your thoughts/plan on this; as if you're just doing the CLI stuff maybe I can investigate the web stuff. I guess the web stuff has no debugging (you'd do that in the browser) and is therefore easy?

(Actually, I'm thinking about DDC and using the browser to debug, but I guess Dartium is still a thing - should we be using that or is DDC+rela browser the expected way forwards?)

**Comment by devoncarew** [comment]
Yeah, I was just scoping this to think about dart cli apps :) It's great to think about web aps as well.

I think the current state of the art in vscode is for the user to edit their launch.json file (except for the first launch perhaps, where it's created automatically from the launch info). It would be great to  think about making this easier - perhaps a context menu item to run, or offer to create a launch.json entry?

Re: web, it's probably best to think about a DDC based flow; DDC's really where we see the future of dart for the web. It will leverage existing web workflows as much as possible - it's just generating ES6 modules, and can be consumed in any JS gulp/grunt/browserify/webpack workflows. For debugging, it emits sourcemaps, so you can use the regular devtools debugging. Though I think there is a vscode plugin to let you debug chrome w/ sourcemaps.

**Comment by devoncarew** [comment]
> Interested to know your thoughts/plan on this; as if you're just doing the CLI stuff maybe I can investigate the web stuff.

Sounds good; I'll scope this issue to just Dart cli.

**Comment by DanTup** [comment]
> It would be great to think about making this easier - perhaps a context menu item to run, or offer to create a launch.json entry?

I think there might be something here already - pressing F5 has asked me some questions in the past (but maybe it was just asking which of the things in launch.json to run?).

I've not much Dart experience - how likely is it a user will have several dart files in `bin` and want to frequently switch between them? What about changing args? Would these make launch.json a pain? Would it be better to try and get something in the command pallete? (eg. a Run command which when selected lists all the dart entry points and allows adding args to the end?).

> it's probably best to think about a DDC based flow

Ok, so if we use DDC and do nothing with dart2js or Dartium, you don't think that'd be a problem? (long-term; I'm less concerned if people are using Dartium or dart2js today if that's likely to change over time). Personally I like the idea of testing in a real browser and just making changes and hitting F5; but I don't know if others prefer debugging the real Dart in Dartium over the running-same-code-as-production benefits.

**Comment by DanTup** [comment]
I've created #68 for web stuff.

**Comment by DanTup** [comment]
@devoncarew Just a thought.. do we need to worry about transformers? There's a `pub run` which says it executes transformers and then the app. I don't know how common this is, but might people be using them and expect them to be run when pressing `F5`?

**Comment by devoncarew** [comment]
Generally, we're moving away from using transformers in dart apps. Many of them require whole program analysis to work, so don't scale well when apps get very large (you want more modular compilation in order to scale). We'll probably move to a system that's based more on the `build` and `source_gen` packages.

So, we probably don't need to worry about transformers too much :)
