### ISSUE TITLE
Packages get fails after misspelling a package name

### ISSUE THREAD

**Issue by mit-mit** [Dart-Code/Dart-Code#560]
Repro steps:

1. Create a new project
1. Open in Code
1. Open `pubspec.yaml`
1. Add a new dependency `sshare:`, and hit save
=> packages get starts

1. Notice it was misspelled, change `sshare` to `share`, and hit save
=> Get error `Waiting for another flutter command to release the startup lock...`

**Comment by mit-mit** [comment]
cc @DanTup

**Comment by DanTup** [comment]
@mit-mit The message makes it sounds like it's just waiting and will complete once the other one completes - does that not seem to be the case?

**Comment by mit-mit** [comment]
It does, but it takes a while. I think we should cancel any previous requests (if that's possible) when issuing a new request. Related, if you hit save multiple times while it's waiting you end up with several `packages get`

**Comment by DanTup** [comment]
Sounds reasonable; though I don't know if terminating it could break things.

@devoncarew Are they any consequences of terminating a flutter process (for example mid-package update)? In this case it's fine if their actions aren't atomic (eg. it leaves things in a broken state) as long as then re-running the command fixes everything.

(I did think we could put a small delay in, but for it to work it's have to be quite long and that'd just make the common case frustrating)

**Comment by devoncarew** [comment]
Not sure that I would terminate the previous request, so much as just batch up (one) additional request, but there shouldn't be any consequences of terminating the process.

**Comment by DanTup** [comment]
I should be able to make it not queue up multiple, but I don't think that solves the original issue (where there were only two requests - a bad one and then a good one). I've hit this a few times myself and it is kinda annoying because the package fetch is kinda slow even when there's an invalid package (I wonder if this could be improved with a step to validate all IDs before it starts doing expensive version solving?).

Otherwise, I wonder if we should just terminate. If the user did this at the console they'd likely hit Ctrl+C and then do it again, so maybe we shouldn't treat this any differently? We could possibly tweak it not to clear the console in this case (I think we should already do that to handle the new package-restore prompt which currently clears between projects so you lose history) and we could write a warning to make it clear we terminated the previous one?

**Comment by DanTup** [comment]
Slight tangent - currently we create a channel named `pub` and one named `flutter` in the output pane and that's where we show the output of these commands.

If you open a workspace with both Dart and Flutter projects and say yes to the "Restore packages?" prompt, it'll run `pub get` and `flutter packages get` for each require folder. This means output is split between two panes (eg. if you have three dart projects, two flutter, you'll have the output of three in one pane and two in the other). Does this feel wonky? Should we use a single output channel?

**Comment by DanTup** [comment]
Ok, I've pushed changes for terminating the process. It seems to work well in my testing. When terminating, it will suppress clearing the output window and write that it's terminating, and then once the process exited, it'll run again. For example (I ran with verbose just to get more output while testing):

```text
[stocks] flutter packages get --verbose
flutter packages get --verbose was already running; terminating...
exit code null

[stocks] flutter packages get --verbose
[  +36 ms] [M:\Coding\Applications\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +91 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] [M:\Coding\Applications\flutter\] git rev-parse --abbrev-ref HEAD
[  +46 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[        ] [M:\Coding\Applications\flutter\] git ls-remote --get-url origin
[  +44 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/DanTup/flutter.git
[        ] [M:\Coding\Applications\flutter\] git log -n 1 --pretty=format:%H
[  +53 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 3723ec0383f79420486bb4ee5acf06ebd190b5cf
[        ] [M:\Coding\Applications\flutter\] git log -n 1 --pretty=format:%ar
[  +54 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 4 hours ago
[        ] [M:\Coding\Applications\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +87 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.1.1-8-g3723ec038
[ +164 ms] Running "flutter packages get" in stocks...
[   +4 ms] [m:\Coding\Applications\flutter\examples\stocks\] M:\Coding\Applications\flutter\bin\cache\dart-sdk\bin\pub.bat --verbosity=warning get --no-precompile
[ +928 ms] "flutter get" took 981ms.
[  +32 ms] ensureAnalyticsSent: 29ms
[   +5 ms] exiting with code 0
exit code 0
```

Gonna push a beta/rc vsix at the start of next week so you can test it out a little before end of the month (if we deem it doesn't work reliably enough we can revert).
