### ISSUE TITLE
Improve journey of new Flutter user creating first project and running on simulator/device

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#565]

**Comment by DanTup** [comment]
1. Install prerequisites
2. Install Code
3. Install Dart Code (this can be done from a button on the website or inside code)
4. Restart Code to load extension (?)
5. Create a project
   - Either: `flutter create` in your own terminal window then `code (foldername)` to open in Code
   - Or: open Code, show terminal, `flutter create`, then open that folder

It might be nice if we could contribute a `Flutter: New project` command (that is visible even without the extension activated) which prompts for a folder, creates a project there, then opens it (or if you're already in a workspace, adds it as a new folder to that existing workspace)?

**Comment by DanTup** [comment]
We can make commands visible before the extension is activated:

![Command before extension activated](https://user-images.githubusercontent.com/1078012/36164026-0296e0b2-10e3-11e8-8988-74cf2c223d23.png)

**Comment by DanTup** [comment]
@mit-mit @devoncarew FWIW, this is one of the few places that would benefit from extension separation. If we create a "Flutter: New project" command that's visible without a project open it will show up for all Dart Code users even those not doing flutter.

Since the interface is simple ("invoke this command") it's something I think we could put the deceleration for into another extension but then handle it here (I believe extensions can listen for each others commands without us needed an interface for them to communicate).

**Comment by DanTup** [comment]
I had a quick go at this and managed to get something I think works reasonably well:

![flutter_create](https://user-images.githubusercontent.com/1078012/36214249-e336757a-11a0-11e8-9d6c-a8f194c27ecd.gif)

The command is visible in the palette before we're loaded and invoking it will activate the extension and invoke the command. We prompt for a name (validating using `^[a-z][a-z0-9_]*$`) and a folder and then kick off `flutter create`. Once complete, we open that folder.

In order to do this we need to search for flutter SDKs on activation even if you're not in a flutter project (since we need to know where flutter is to run `flutter create`) but I don't think that's a big deal. If we don't find one (eg. you installed Dart Code but without a flutter SDK!) we'll detect and show the usual error with a link to the download page.

Some things I want to add:

- If you have a folder/workspace open, default the Open dialog to the parent folder of the first project
- Open `lib/main.dart` automatically after opening the folder (not sure if this will be possible, it might be that Code terminates our command to reload the window when we tell it to open the folder)
- If you already had a workspace open, add the folder to it instead of opening it directly (this will make it useful to add flutter projects to existing windows)
- Ensure errors are handled well (eg. if flutter create fails)

**Comment by DanTup** [comment]
@mit-mit See above and lmk if you have any suggestions. I think we may require some changes from Code for some of the points below, but I'll keep digging. It'd be cool to include in v2.9 but I don't want to ship it if it was quirks.

**Comment by DanTup** [comment]
I think this works pretty well now, except for the issue if you already have a workspace open we can't add to it. I've raised https://github.com/Microsoft/vscode/issues/43674 about this - would appreciate thumbs ups!

**Comment by mit-mit** [comment]
This looks quite promising!

In the case where you have an open workspace, can we open the freshly created project in a new window?

**Comment by DanTup** [comment]
@mit-mit I think so, though might seem a bit weird? I think it's better than nothing for now though, so I might stick that in while we await a response on the Code issue above.

**Comment by DanTup** [comment]
Well that works; but introduces another quirk! ;( The context variable we use to trigger the "open `lib/main.dart` and show the user a helpful message" isn't available in the new window (presumably because it gets a new instance of the extension but the existing window hasn't shut down, so that data hadn't persisted anywhere).

Not a deal breaker, but still a minor annoyance!
