### ISSUE TITLE
restore flutter framework toggles after an app restart

### ISSUE THREAD

**Issue by devoncarew** [Dart-Code/Dart-Code#567]
@DanTup, to follow up on our in-person discussion:

Some of the flutter framework toggles (like debug draw, and the performance overlay) may be worth restoring after an app restart. For IntelliJ, we restore some across a 'full' restart, and fewer between separate app sessions. We have persistent UI for the state of the toggles however (in the form of toolbar icons). Since the vscode plugin doesn't have this persistent UI, it may not need the settings persisted quite as much.

Here's what we expose in IntelliJ currently:
- `ext.flutter.debugPaint` (restored across separate app sessions)
- `ext.flutter.showPerformanceOverlay` (restored across separate app sessions)
- `ext.flutter.repaintRainbow` (restored across separate app sessions)
- `ext.flutter.debugAllowBanner` (restored across separate app sessions)
- `ext.flutter.debugPaintBaselinesEnabled` (restored across separate app sessions)
- `ext.flutter.timeDilation` (restored across full restarts)
- `ext.flutter.debugWidgetInspector` (not restored - a restart will clear the inspector)

What might make sense in VSCode is to restore the top 5 items above (the UI settings related ones) across full restarts (but not app sessions). Thoughts?

When restoring a value after a restart, the VM won't be ready to accept any service protocol calls until the isolate is sufficiently booted up. In IntelliJ, we wait until we receive the first `Flutter.Frame` over the wire before we try and restore any values.

**Comment by DanTup** [comment]
Sounds reasonable to me. We can always look at persisting across sessions (I presume this just means a real stop/start within a single editor session?) based on how it feels or feedback later.

**Comment by devoncarew** [comment]
> I presume this just means a real stop/start within a single editor session?

Yup.

Some iteration here makes sense; just based on what the toggles do, users may expect some to be stickier than others.

**Comment by DanTup** [comment]
Based on the text above am I right in thinking we're talking about persisting all 6 settings (we don't have the widget inspector one) across full restarts (where "full restart" means the command in the palette). If you click the Stop button and then start debugging again, they will be reset?

**Comment by DanTup** [comment]
@devoncarew I kinda have this working, but I see a crash when re-sending the value. It may be related to your comment above:

> When restoring a value after a restart, the VM won't be ready to accept any service protocol calls until the isolate is sufficiently booted up.

However it's different to the error I get if I just sent it right away (which complains about the extension not existing) and looks like it's crashing in Flutter code, so I'm not sure. I raised https://github.com/flutter/flutter/issues/14885 about this, but if you think we need to change the event we wait for, let me know (I don't think we currently get the frame event you mentioned, so I was trying to use something we had and that seemed logical - in this case the `ServiceExtensionAdded` event).

**Comment by devoncarew** [comment]
> thinking we're talking about persisting all 6 settings

sounds good!

> but I see a crash when re-sending the value

I do think we want to wait for the first frame event. Not sure why you're not seeing it. Is the plugin indicating interest in the `Extension` event kinds? (`streamListen("Extension")`)

**Comment by DanTup** [comment]
Aha, no - we only subscribe to Debug/Isolate.

Ok, I can see that now - and there's even a `Flutter.FirstFrame` we can use to aavoid having to route all frame messages back from the debug adapter to the UI.

How much extra data is this going to add - is it every frame rendered (eg. potentially 60fps)?

**Comment by DanTup** [comment]
Seems to work fine. I'm just re-sending all toggles on `Flutter.FirstFrame` (this happens at first startup, but they'll all be false).

The only thing not persisted is Platform - it wasn't in the list above and it's a bit more complicated (we don't know it's value, we always handle that as a toggle in the debug adapter by sending a request and then flipping it). If that needs handling we will need to route the value back to the UI.

**Comment by DanTup** [comment]
> `Flutter.FirstFrame` would happen after a restart, but not after a reload, if that's important to you.

Doesn't seem to be, it seems a hot reload doesn't drop any of these toggles so this works fine (though if you think that's not right and you use `Frame` in IntelliJ lmk!)

> I would guess that this won't present much of an issue, but no hard numbers for it

We're only routing the FirstFrame back to the UI and most people don't have logging turned on like me, so maybe it won't be an issue. I'll keep my eyes on the log files next time I'm doing something around there.
