### ISSUE TITLE
Show spinner when commands are running or analysis is in progress

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#571]
When working on the flutter create, there was a noticable stall when packages were fetched. It'd be good if we had something in the status bar to make it more obvious something is running (even if it's just turning text on and hiding it at the end - I think it'll feel better).

**Comment by xster** [comment]
Might be the same issue when pressing F5. There's no UI feedback for a while until the run configuration dropdown menu shows up

**Comment by DanTup** [comment]
There's some wonkyness in Code that makes this tricky for debug start/end, however I've fixed up the pub/flutter commands and analysis to now have a spinner.

Will see what the response is to https://github.com/Microsoft/vscode/issues/43752 before decided whether to put a workaround in so we can have it for debug launches too.

**Comment by DanTup** [comment]
Raised #593 for the debug session (it needs a Code update); closing this as done for analysis + commands.
