### ISSUE TITLE
Don't move the cursor around for editing assists

### ISSUE THREAD

**Issue by mit-mit** [Dart-Code/Dart-Code#573]
When using editing assists in code, the cursor seems to move around a lot. Here is the similar behaviour  in IntelliJ where the cursor stays where it was, which seems more natural:

![edit1](https://user-images.githubusercontent.com/13644170/36257114-e839008c-1255-11e8-9f9b-936c008b5091.gif)

**Comment by DanTup** [comment]
@bwilkerson Any ideas on this? We're using the `selection` that comes back with the assist, but it seems to be at the end of the inserted text.

Example:

```dart
import 'package:flutter/material.dart';

class Danny extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const Center(child: const Text('test'));
  }
}
```

I put my cursor in the middle of the word `Center` (position 155) and invoke "Add widget padding":

```js
{"id":"15","method":"edit.getAssists","params":{"file":"m:\\Coding\\Applications\\flutter\\examples\\stocks\\lib\\danny.dart","length":0,"offset":155}}
```

The assist comes back like this:

```js
{
	"message": "Add widget padding",
	"edits": [
		{
			"file": "m:\\Coding\\Applications\\flutter\\examples\\stocks\\lib\\danny.dart",
			"fileStamp": 0,
			"edits": [
				{
					"offset": 146,
					"length": 39,
					"replacement": "new Padding(\r\n      padding: const EdgeInsets.all(8.0),\r\n      child: const Center(child: const Text('test')),\r\n    )"
				}
			]
		}
	],
	"linkedEditGroups": [],
	"selection": {
		"file": "m:\\Coding\\Applications\\flutter\\examples\\stocks\\lib\\danny.dart",
		"offset": 263
	}
}
```

The final doc looks like this:

```dart
import 'package:flutter/material.dart';

class Danny extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Padding(
      padding: const EdgeInsets.all(8.0),
      child: const Center(child: const Text('test')),
    );
  }
}
```

The selection given was 263, which is where the `);` is but we would expect it to remain in the middle of the word `Center` (225/226?). It feels like it must be my bug since it's working in IntelliJ but I can't see anything obvious I'm doing wrong.

**Comment by DanTup** [comment]
I just watched the animation at the top again, and I think IntelliJ actually isn't moving the cursor at all. When the widget is surrounded, the cursor remains in the same spot (it doesn't move with the text).

So, we could do this in Code (just ignore the selection that comes back) though obviously it'd be better if we did something more intelligent.

**Comment by bwilkerson** [comment]
Yeah, it definitely looks like the selection point is off.

**Comment by DanTup** [comment]
Ok, I'll raise an issue in the SDK repo.

**Comment by DanTup** [comment]
I've opened at https://github.com/dart-lang/sdk/issues/32184

**Comment by DanTup** [comment]
This was fixed in https://github.com/dart-lang/sdk/issues/32184. We'll no longer get `selection`s back for these fixes so the cursor should not move.
