### ISSUE TITLE
Auto-completion inserts named-argument placeholders when values already exist

### ISSUE THREAD

**Issue by pulyaevskiy** [Dart-Code/Dart-Code#575]
![kapture 2018-02-15 at 9 34 07](https://user-images.githubusercontent.com/441756/36271500-a340e9da-1233-11e8-811f-7739f59e6578.gif)

**Comment by DanTup** [comment]
Won't get chance to look at this for a few days; can you confirm which SDK version you're using and post the full signature of the constructor?

**Comment by pulyaevskiy** [comment]
```bash
$ dart --version
Dart VM version: 2.0.0-dev.22.0 (Thu Feb 8 18:55:13 2018 +0100) on "macos_x64"
```

Constructor ([source](https://github.com/pulyaevskiy/node-interop/blob/master/node_interop/lib/stream.dart#L52)):

```dart
@JS()
@anonymous
abstract class WritableOptions {
  external factory WritableOptions({
    int highWaterMark,
    bool decodeStrings,
    bool objectMode,
    Function write,
    Function writev,
    Function destroy,
  });
}
```

**Comment by DanTup** [comment]
I think this existed before the beta! We now do something similar to how we suppress the arguments when the next char is a paren. Here, if the next char is a colon, we suppress the placeholder insertion.

Will probably push a `beta 2` once I've finished tidying up these remaining few issues.
