### ISSUE TITLE
Auto-completion does not insert `()` for constructors with named arguments [2.9.1-beta]

### ISSUE THREAD

**Issue by pulyaevskiy** [Dart-Code/Dart-Code#576]
In this example `ReadableOptions` constructor contains only named arguments, and `Readable` doesn't even have a constructor declared.

```
Dart VM version: 2.0.0-dev.22.0 (Thu Feb 8 18:55:13 2018 +0100) on "macos_x64"
```

![kapture 2018-02-15 at 9 55 16](https://user-images.githubusercontent.com/441756/36272604-dbdea8b0-1236-11e8-9129-f6fa3127f75d.gif)

**Comment by pulyaevskiy** [comment]
Constructors with all optional arguments seems to be affected as well.

**Comment by pulyaevskiy** [comment]
Just confirming that completion works much better now. Haven't noticed any issues so far. Thanks!

**Comment by DanTup** [comment]
Awesome; thanks 👍
