### ISSUE TITLE
'Go to Definition' doesn't work without new/const

### ISSUE THREAD

**Issue by mit-mit** [Dart-Code/Dart-Code#580]
Repro steps:

1. Enable Dart2 preview mode
1. Create a new project
1. Remove new/const keywords
1. Invoke 'Go to Declaration' on one of the widgets (e.g. `Center`)

=> 'No Definition found for Center'

**Comment by mit-mit** [comment]
cc @DanTup, I'm wondering if this is a code issue or an analyzer issue? cc @devoncarew does the same set of steps work in IDEA?

**Comment by DanTup** [comment]
Seems to be an analyzer issue; I've opened https://github.com/dart-lang/sdk/issues/32215.

**Comment by DanTup** [comment]
This seems to be fixed in latest.
