### ISSUE TITLE
Warn users when (/make it hard to) edit an external file (SDK, package)

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#592]
We're removing the read-only-ness because it has issues, so we should consider adding a warning when users start typing into external files.

**Comment by DanTup** [comment]
Probably should consider when files that shouldn't be edited actually look like they're in the users project:

> `M:\Coding\Applications\flutter\bin\cache\pkg\sky_engine\lib\core\string.dart`

**Comment by DanTup** [comment]
@pq I've added a warning if you start typing inside a file that's not part of your workspace (for ex. a pub package of the flutter framework code). It'll only prompt once-per-file-per-session, is non-modal (they vanish after around 10 secs, but remain in the notification list if you open it) and can be disable with a setting.

I have a vague recollection that when you mentioned this to me, there was something more to it than just this. Do you remember?

**Comment by pq** [comment]
Wracking my brain bu I can't recall!  I'll let you know if anything occurs to me though.

Thanks @DanTup!
