### ISSUE TITLE
Show flutter version in status bar

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#597]
Possibly for Flutter projects we should show the Flutter version and relegate the Dart SDK version to the tooltip.

Need to see how we can get this version without calling flutter in a way that might go and download an SDK!

**Comment by DanTup** [comment]
@devoncarew the version in the `VERSION` file written today for my Flutter checkout says `0.1.6-pre.9`. This is also in the first line of the `flutter --version` output. Does this seem like a good (/the correct) thing to replace trhe SDK version in the status bar?

**Comment by devoncarew** [comment]
Yes, this is likely most meaning number to the user now. Depending on available space, perhaps prefix w/ `Flutter `?

**Comment by DanTup** [comment]
Once this is done, we should consider #646. Seems weird to change the SDK version for Dart when in a Flutter project - would make much more sense if this let you jump between master/beta branches.

**Comment by DanTup** [comment]
Ok, just displaying the version now. Not currently showing channel, but may add that with #646.
