### ISSUE TITLE
Offer code assist for constructing new arguments

### ISSUE THREAD

**Issue by xster** [Dart-Code/Dart-Code#604]
The autocomplete to fill in the <Widget>[] list literal on children parameters is super awesome. 

I wonder if we can apply it to all parameters by checking against the analyzer. 

Consider I'm starting to type
```dart
return new PageRouteBuilder(
  pageBuilder: <highlight>pageBuilder</highlight>
)
```

Now it's a huge pain to actually fill out my selected value with a new instance of what `pageBuilder` the parameter wants unless I already have an instance. 

Would be nice for the code assist on the selected string to offer the construction of the type the parameter wants. In this case, a function with a long list of input parameters that would autocomplete to:
```dart
return new PageRouteBuilder(
  pageBuilder: (BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation) {
    return <highlight></highlight>
  },
)
```

Here the parameter takes a function that can only be constructed one way but it would be nice for the code assist to offer all the constructors. 

So on a `children` parameter, it can offer a <Widget> list literal or offer new List, new List.filled, new List.from etc from all the factories correctly parametrized.

**Comment by DanTup** [comment]
It would be hard to do this directly in Dart Code - we do insert arg placeholders and could put it there, but you'd end up deleting it if you had an instance. I think ideally after the `:` the code completion would include this stub as one of the completion items, but I don't know how well it'd fit in the list (being long, potentially multiple lines, etc.).

@bwilkerson @devoncarew thoughts on this?

**Comment by xster** [comment]
I'd leave the argument placeholder there. Turning a placeholder (referring to a variable that doesn't exist) into a constructor template via ctrl-space or ctrl-. is the feature I'm requesting.

**Comment by bwilkerson** [comment]
I don't know VS Code, so I don't know whether they have support for such a feature, but other IDEs that I've used don't. The work-around that I've used before is to double click the identifier, back space, and request code completions.

That said, server doesn't currently propose closures when completing a function-valued argument, but it could. It could also be made to propose list and map literals when appropriate. I think both are worth considering.

**Comment by DanTup** [comment]
We're already pre-selecting the placeholder value so you shouldn't need to double-click it.

Possibly when completing a named arg (since it'll always say `name: name`) we should skip the placeholder and just put the cursor there see if we can invoke completion?

@xster 

>  server doesn't currently propose closures when completing a function-valued argument, but it could. It could also be made to propose list and map literals when appropriate. I think both are worth considering.

Do you want to raise this in the sdk repo?

**Comment by bwilkerson** [comment]
See https://github.com/dart-lang/sdk/issues/31885.

**Comment by xster** [comment]
I don't have too strong of a preference between autocompleting into `name: name`, pressing backspace then manually triggering a next autocomplete or autocompleting into `name:` only. Though it would be nice if autocompleting into `name: ` kept the autocomplete dropdown present but now autocompleting contextually relevant statements that fulfills the argument now.

 I totally forgot I raised dart-lang/sdk#31885. Though maybe now I would generalize it to be able to auto-template instantiate any contextually appropriate parameter needed whether it's a factory, an inline function, a literal map etc.

**Comment by DanTup** [comment]
@xster Does this analyzer issue cover this now, or is there something to do in Dart Code?

**Comment by xster** [comment]
Nothing extra from Dart Code. Just the analyzer option to offer all construction options.

**Comment by DanTup** [comment]
Closing this since I think it's all analyzer work (https://github.com/dart-lang/sdk/issues/31885). We can revisit if anything gets implemented that needs additional support in Dart Code though.
