### ISSUE TITLE
Support previewDart2 in non-Flutter apps

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#610]

**Comment by aemino** [comment]
It would be great if `--preview-dart-2` was also supported for the VM. 👍

**Comment by rrousselGit** [comment]
I don't have problem with non-flutter app using previewDart2. What is this issue about ?

**Comment by bergwerf** [comment]
I want to debug some errors that arise from down casting in Dart 2. These are already implemented in dartdevc now causing this code to fail. However I would like to debug using the dart VM, so I would have to debug with this flag.
Perhaps it is possible just for flexibility to allow passing custom flags in the debug configuration?

**Comment by DanTup** [comment]
Glad you managed to workaround it. I do plan to fix this (and also add `dart.dartAdditionalArgs` to pass custom flags to the VM - see #655) for vNext.

For now, if you want to avoid having to run in the dev host, if you run `vsce package` in the `Dart-Code` folder it'll build a `.vsix` file that you can then install with `Install extension from vsix` into your main Code instance. If doing this, I suggest a) pulling latest and b) maybe setting the version in `package.json` prior to building as a reminder you're on a custom version.

**Comment by lukef** [comment]
It would be great if you could override this in the launch.json as you may be working on Dart 1.x and Dart 2 projects in the same IDE and it is a bit annoying to have to change this setting if you switch between projects (agency person here! :P). 

Maybe a `vmargs` or `sdkargs` option?

**Comment by DanTup** [comment]
@lukef You can set settings at the folder/workspace level, so anywhere you can have a `launch.json` you can also have a `settings.json`. You can either run the `open workspace settings` command, or when you run the user one, there's tabs at the top to switch between user and workspace (and if you choose workspace, you can select which folder).

BTW, if you're switching between Dart 1 & 2, you'll probably be interesting in `dart.sdkPaths` which is an array of SDKs that you can use to quickly switch SDK versions from the status bar - and it persists in the workspace settings (mentioned above) so is local to that folder/workspace and persists :-)

> Maybe a `vmargs` or `sdkargs` option?

I think this is #655?

**Comment by lukef** [comment]
I don't know how I didn't know of any of this until now. Game changer! #655 would work for me!

**Comment by DanTup** [comment]
vNext will support both :-)
