### ISSUE TITLE
Hot Reload "coverage" markers

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#611]
Some things left over from notes in the PR (which has merged for preview):

- [ ] Ensure we don't send requests for coverage if another is already in progress
- [ ] Handle errors better
- [ ] Add automated tests

**Comment by rrousselGit** [comment]
What is this about ? I'm thinking to contribute to have an easier testing in dart. 

But as far as I know, Dart Code does nothing yet ? Especially about coverage ?

**Comment by DanTup** [comment]
This is unrelated to testing; it's about looking at ways to better show a user code that was re-executed (or not) during a reload - the same as https://github.com/flutter/flutter-intellij/issues/1690. There's not much info here as it's still just an idea, I was just making sure it's in my list as a reminder for prioritising work in the coming weeks.

You're right that Dart Code doesn't do testing well yet, the related issues are #87 and #499. That said, I have been using F5 to run tests on the analyzer recently - I'll add some notes to #87 about this now in case it's useful.

**Comment by DanTup** [comment]
I thought we might be able to draw colours in the butter similar to VS Code does for Git status markers, however it seems to be using internal classes/APIs that aren't exposed:

https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/scm/electron-browser/dirtydiffDecorator.ts

So we may be limited to standard decorations and/or icons in the gutter.

**Comment by DanTup** [comment]
@devoncarew @mit-mit I had a quick look at the decoration APIs and seems that we easily can add background colours with opacity and also some tooltips (I couldn't get a screenshot because they disappear when I press a key, but their text basically gets inserted above the existing tooltips, so if you hover a class, you'll see "This code was modified but not reloaded w/e" and then underneath it the rest of the usual tooltip). We can also add icons in the gutter, however they get repeated for every line (it doesn't seem like we can make them only appear for the first line of a block).

![screen shot 2018-04-02 at 10 20 56 2](https://user-images.githubusercontent.com/1078012/38191290-0dfd1050-3660-11e8-840a-285dcbbf44c2.png)

**Comment by devoncarew** [comment]
I did some experimentation in IntelliJ as well, and looked into some of the APIs available. A braindump:
- I think we'll need a new flag into the `getSourceReport()` API from the VM's service protocol, so that we can specify the coverage info since the last reload; this would only return coverage for changed methods
- we'd call that once after the reassemble completes
- lines that are not covered we could draw people's eyes to a bit more
- I'm not sure that we want in-editor decorations - that may distract too much from the code - be we can experiment to see; if we do use it, perhaps just for uncovered lines

<img width="253" alt="screen shot 2018-04-02 at 7 46 36 am" src="https://user-images.githubusercontent.com/1269969/38200657-0f65d762-364a-11e8-972b-4e4e3c47563c.png">

Show live coverage - auto-updating as the app runs - would be some follow on work. We'd be trying to map coverage info for the version of the file that the VM has, but the user would likely have edits to that file after a while - so we'd have to have logic to map the older VM positions into the newer user code (until the next reload resets everything).

/cc @InMatrix

**Comment by devoncarew** [comment]
And, /cc'ing @rmacnak-google

**Comment by devoncarew** [comment]
I filed https://github.com/dart-lang/sdk/issues/32736 to track any API work.

**Comment by DanTup** [comment]
> I'm not sure that we want in-editor decorations

Do you mean the BG colours? Without them, we're suck to icons for VS Code. We could possible make an Icon that is just a coloured strip to make it look like your example. Not sure what VSCode does when there are multiple icons added by different extensions to the gutter though!

**Comment by devoncarew** [comment]
Yeah, I think we should:
- have a small, vertical bar icon used to show covered / uncovered
- be careful about using the background color for that info - as that's a big visual change; we'd want to make sure it works

**Comment by DanTup** [comment]
I found it while doing column breakpoints, but https://github.com/dart-lang/sdk/issues/32734 might need looking at to be able to deliver this - the token positions don't seem to match up with the source as expected.

**Comment by DanTup** [comment]
@devoncarew In your code you're currently setting `forceCompile: true` when fetching source reports, but the docs suggest this could cause the app to terminate. Your comment suggests it's only needed for uncovered code, but since I'm only interested in covered (I'm subtracting covered code from our list), does it seem reasonable to leave as false?

**Comment by devoncarew** [comment]
My understanding is that that flag will let us know about any executable but uncovered lines in methods that weren't executed. I'm not 100% sure its hooked up in a CFE world, but I think you're correct in that we don't need to call it (since we only care about covered code).

**Comment by DanTup** [comment]
@devoncarew Two things I'm kinda stuck on:

1. How do we get lengths of tokens from the `tokenPosTable`? It seems like it's just lineNumber/columns?
2. How can we map the line/column from the coverage data back to the file if the user has modified it since? Should we revert all "reloaded but not run" markers back to "edited but not reloaded" markers for a file on edit?

**Comment by devoncarew** [comment]
From an off-line discussion:
- we won't be able to get spans for tokens, just line and columns
- a close approximation would be to convert from a token to a line, assume the whole line is executed, and subtract that line from the set of edited but not executed lines

> How can we map the line/column from the coverage data back to the file if the user has modified it since?

We'll need to see how the UX feels in practice, but once the user has modified the file, we should no longer request new coverage info from the VM. We can either choose to clear out all older markers, and start tracking new changed lines, or retain changed-but-not-executed markers, converting them to just changed markers. My guess is that the former solution will work best, but we'll have to see.

**Comment by devoncarew** [comment]
I used Frame events and debugger resumed events (and don't specifically poll); that seemed to work well.

**Comment by DanTup** [comment]
Sounds good. I guess `step` makes sense too, so as a user is stepping (without fully resuming) we'll clear the markers out too. I'll try it out and see how it works.

**Comment by DanTup** [comment]
This is somewhat working now; but there are still many edge cases and I think I made a bad call to track ranges instead of lines (for ex., ranges mean every key press adds a new range, so the number of ranges grows quickly with lots of adjacent/overlaps). I was hoping to trim whitespace from the ranges and also merge adjacent ones; however these somewhat interfere with each other (if I drop the whitespace too early, the ranges won't be adjacent so merging them then needs to take into account if they're only separated by whitespace)/

I guess I was thinking about lambdas when I decided to use ranges:

```dart
var thing = things.where((t) => t.someThing);
```

But now I'm not so sure that tracking this makes much sense, especially as the user wouldn't see it once we move indicators to the gutter anyway.

So, I think I may change back to line numbers; it should simplify a bunch of stuff.

@devoncarew One issue I'm not sure how to fix yet, is "unexecutable" code, for example comments above a method. These never get "hit" so get highlighted forever. Can you think of a good way to tell what code I should just strip from the ranges? I was wondering whether the `PossibleBreakpoints` or `misses` (which we don't use now) might help identify code that couldn't be hit?

**Comment by DanTup** [comment]
@devoncarew I've switched over to line numbers and I think that's improved some things. I'm going to also try to intelligently ignore lines that are uninteresting (whitespace, comments, braces).

However, I found another issue... Given this code:

```dart

  ThemeData get theme {
    switch (_configuration.stockMode) {
      //
      case StockMode.optimistic: //
        return new ThemeData(
            //
            brightness: Brightness.light,
            primarySwatch: Colors.blue); //
      case StockMode.pessimistic:
        return new ThemeData(
            //
            brightness: Brightness.dark,
            accentColor: Colors.yellow); //
    }
    assert(_configuration.stockMode != null);
    return null;
  }
```

The lines with `returns` and the few lines after them are all grouped together, so I only get a hit for the `return` line (I guess since it's the only place to add a breakpoint, those on the next few lines would snap to the `return` line). This means the lines with the colours on never get taken out of the list (which somewhat breaks the whole thing).

Is this a good way to handle this (or are we going to have to map tokenPos's back to entire spans?).

**Comment by devoncarew** [comment]
> Can you think of a good way to tell what code I should just strip from the ranges? I was wondering whether the PossibleBreakpoints or misses (which we don't use now) might help identify code that couldn't be hit?

and 

> so I only get a hit for the return line (I guess since it's the only place to add a breakpoint, those on the next few lines would snap to the return line). This means the lines with the colours on never get taken out of the lis

Perhaps the fix here is related? I was thinking that we should use a whitespace / comment heuristic to remove changed but not executable lines. This won't handle the switch statement case above however. So, perhaps moving to just displaying as orange the intersection of changed lines, executable lines, and non-executed lines, where 'executable lines' is determined by what the vm returns as missed and `PossibleBreakpoints`? I'd worry that what the VM returns as `PossibleBreakpoints` won't cover everything that the user can change but that won't run on a reload, but it at least seems like a good place to iterate from.

**Comment by DanTup** [comment]
In the case from above, wouldn't this mean only the `return` line gets highlighted though? Although it'd stop highlights on lines that were executed, I'm not sure it'd look that good to the user if we're only highlighting the return line?

What I was wondering was whether using PossiblyBreakpoints (or misses) we could assume a token runs all the way until the next one? If there's a PossibleBreakpoint/miss at the start of the `return` and then the next one is after the semicolon, is it reliable to assume we can clear out all lines in between when the starting one is hit?

**Comment by DanTup** [comment]
In the editor we have access to things like the Outline data; but since it updates on changes it might be hard to know we have the correct data for the version of the code running in the VM at a given time.

**Comment by devoncarew** [comment]
We may have a bit of a disconnect between edited lines and the tokens positions the VM returns for executable / executed locations. I'm not sure there are clear solutions for what to do in all cases - sounds like there are a lot of corner cases. Hopefully some iteration will clarify things; with good use cases, we can also try to add more data to the information returned by the VM.

> In the editor we have access to things like the Outline data

Yeah, I'm not sure we should mix in analyzer information here as well, but more use the modified text locations, and try and iterate on information we can get from the runtime.

**Comment by DanTup** [comment]
> sounds like there are a lot of corner cases

I think it's more than just edge cases though.. Flutter prefers argument-per-line, so consider this code:

```dart
    final ThemeData a = new ThemeData(
      brightness: Brightness.light,
      primarySwatch: Colors.blue,
    );
```

Changing `Colors.blue` doesn't get a `hit` back for that line in the coverage data, only the `final ThemeData a =` line. It feels rather broken like this (I'm surprised I got this far without spotting that!). I'm not sure from the data I have I can tell that line 3 should be erased by hits on line 1.

That said, I'm now thinking; how could you even make a standard coverage report like this? Surely there must be data somewhere to indicate all four lines had been hit? Maybe I've just missed something somewhere?

**Comment by devoncarew** [comment]
@cbracken has more detailed knowledge of how Dart's coverage tooling has handled this.

/cc @rmacnak-google @a-siva and @aam fyi, for some potential difficulties mapping executed token positions up to user edited lines

**Comment by DanTup** [comment]
Ok, here's how this looks now:

![reload_markers](https://user-images.githubusercontent.com/1078012/41027498-1cdd8d88-696f-11e8-8a2d-88c75faaa3ce.gif)

It kinda works, but I think there are some serious issues:

1. It seems like we can't get tooltips on the gutter icons, so the user has no idea what these markings are
2. There are all sorts of lines (imports, annotations, class def) that get highlighted that will never receive coverage hits and our current filtering is really naive (takes out lines that are `{`, `}`, start with `//` etc.). I think to do this reliable we need to be using Outline data or something.

It does currently rely on a change I haven't committed to this branch because it might break other stuff (just waiting for tests to run on another branch to see), but I can send a build if anyone wants to play around and provide feedback (@devoncarew @mit-mit @InMatrix).

**Comment by devoncarew** [comment]
This is great progress!

> It seems like we can't get tooltips on the gutter icons, so the user has no idea what these markings are

Tooltips would be nice, but I'd hope that users will gain understanding of what the markers mean over time, as they use the tool.

> There are all sorts of lines (imports, annotations, class def) that get highlighted that will never receive coverage hits and our current filtering is really naive (takes out lines that are {, }, start with // etc.). 

For some of the specialized cases (imports, annotations) I'd hope that the user either understands what the markers mean enough to know to ignore them at those locations, or is generally changing code and reloading within a method body (the happy path for us). If we capture those 80% use cases well I think that would be success.

**Comment by DanTup** [comment]
This is no longer relevant - the work was removed (after only shipping behind a preview flag). We can open new issues if we do something similar/resurrect in future.
