### ISSUE TITLE
Hosted file uris when clicking to definition and debugging don't match up, so breakpoints don't work

### ISSUE THREAD

**Issue by jakemac53** [Dart-Code/Dart-Code#613]
If I navigate to the definition of something in one of my dependencies, the uri I get is the full absolute uri inside my pub cache. When debugging it starts at `~/` and then is a relative path from there.

That means if I click to definition and set a breakpoint it won't get hit, I have to start from some point in my main app and navigate to files by stepping into calls, and then set a breakpoint once I get to the file that way.

**Comment by DanTup** [comment]
We do have some issues around breakpoints, but I think what you're doing should work (we actually send your breakpoints to the VM in several forms (see [here](https://github.com/Dart-Code/Dart-Code/blob/master/src/debug/dart_debug_impl.ts#L248-L268)) to cover these things. It's possible that resolving `~` is something we've missed though!

Could you enable observatory logging (see https://github.com/Dart-Code/Dart-Code/blob/master/CONTRIBUTING.md#enable-logging), set a breakpoint in a dependency and then add something like `throw "blah"` to the next line (so after it misses the breakpoint, it throws and pauses on the exception) and then attach (or email me) the log? Be sure to review for anything sensitive.

Also; can you include the line from `.packages` that relates to the dependency in question?

**Comment by DanTup** [comment]
Also, can you confirm which platform you're on and which version of Dart Code (v2.9 had some breakpoint fixes in it).

**Comment by jakemac53** [comment]
I am on linux, and version 2.5.1 of DartCode, so updating may just solve the issue. I can enable logging etc tomorrow.

**Comment by DanTup** [comment]
2.5.1 is quite a few months old (I guess you don't have auto-update enabled?) so it's definitely worth updating to see if that fixes it first. If not, grab a log and I'll take a look.

**Comment by DanTup** [comment]
@jakemac53 Did you get chance to look at this?

**Comment by jakemac53** [comment]
not yet, I will try soon though

**Comment by DanTup** [comment]
@jakemac53 Ping! :)

**Comment by DanTup** [comment]
Gonna close this since I can't currently progress, but shout if you can still repro and provide some more info!

**Comment by DanTup** [comment]
Np, I know what it's like :) Just trying to tidy up so it's easier for me to find things to work on, it's easy enough to re-open if things still need looking at!
