### ISSUE TITLE
Discuss UI for full restart

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#623]
We've hijacked the Restart button on the debug toolbar for Hot Reload but now it's not so obvious to a user how to do a full restart. The status bar hint helps a little, but only after they've already failed to reload (and only if the hint triggers). Sometimes a user might know they need to do a full restart and if you don't set up a keybind, it's currently quite long winded.

We have no control over the debug toolbar so we can't support Shift+Click or add tooltips or anything.

Now that we support hot-reload-on-save maybe the restart button on the debug toolbar could be a full restart? Is it likely anyone will want to trigger a hot reload manually?

**Comment by chances** [comment]
I support the hot-reload-on-save, full restart via debug toolbar idea.

**Comment by xster** [comment]
I just always use F6/Shift-F6. Can we show a tooltip or something for hotkeys?

**Comment by DanTup** [comment]
On my Mac here it says `F6` is `pause`?

We can't add tooltips or customise the debug toolbar in any way. There's also not any other "restart" functionality built into Code so a completely custom command (which can be keybound, either by the user, or we can set a default).

(cc @mit-mit @devoncarew for more opinions)

My concern with mapping the restart button on the toolbar because we already hot-reload-on-save is that I still tend to click it after saving (because I'm totally not used to hot reload on save and it's not super obvious that the reload is happening, only the status bar) and this would mean I was doing full restarts (whereas currently I just get a rejected hot reload message).

**Comment by rrousselGit** [comment]
Big +1 for hot-reload-on-save and full restart via toolbar (or ctrl/command + shift + f5). 

I don't see any reason not to use hot-reload on save, as it's fast and never break your workflow in any way.

**Comment by DanTup** [comment]
FWIW, you can still keybind Full Restart from the VS Code keybind page (just search for the `flutter.fullRestart` command) regardless of this :-)

**Comment by Skylled** [comment]
Unpopular opinion: I actually dislike hot-reload on save, and have it disabled. A lot of times, I want to make changes in a few different files before I'm ready to restart.

Has an issue been filed with VSCode for toolbar customization? Then we could just slap on an extra 🔥 button for hot reload.

**Comment by DanTup** [comment]
> Unpopular opinion: I actually dislike hot-reload on save, and have it disabled. A lot of times, I want to make changes in a few different files before I'm ready to restart.

It doesn't surprise me that everyone doesn't use it, that's why I think addressing this is a little tricky (we could make the button do a hot reload if you don't have `hotReloadOnSave` and otherwise a full restart but I think that's confusing).

> Has an issue been filed with VSCode for toolbar customization?

I assumed someone would have, but apparently not. I have now - please 👍 it! :)

https://github.com/Microsoft/vscode/issues/45116

**Comment by csga5000** [comment]
+1 I really think we need capital R support.  Do to this and a few other quirks, I generally just use the vscode terminal to debug manually using flutter run. But I'd much rather it be more practical to use vscode's UI.

Reload on save does bother me a bit too, but I don't disable it, so I would be satisfied w/ save to reload, and restart on debug button.  But ideally there'd be some other way (even if it's just a way to send console commands like R to flutter)

**Comment by DanTup** [comment]
My preferred fix here is to get an extra button on the toolbar so we can have both and not have to make compromises! I opened an issue in the Code issue tracker and it's in the on "On Deck" milestone, so maybe with enough 👍 votes it'll make it.

So, if you want to see improvements here, the best way to help would be to 👍 on this issue -> https://github.com/Microsoft/vscode/issues/45116 :)

**Comment by DanTup** [comment]
> +1 I really think we need capital R support

I wasn't really sure what this meant when you first posted it, but I see it's what you use in the command line. In the last Dart Code update we bound `Ctrl`+`F5` to `Full Restart` so you can easily do it from the keyboard without modifying keybindings yourself.

**Comment by DanTup** [comment]
I don't think it's likely we'll change anything here until VS Code allows us to add a new button (changing this now would confuse a lot of people). There is the new shortcut for `Hot Restart` mentioned above which I think helps a lot.

**Comment by DanTup** [comment]
This came up again:

https://github.com/Dart-Code/Dart-Code/issues/1338

The request is for s setting to control whether the restart button does a Restart or Reload. If VS Code isn't going to allow us to add an extra button anytime soon, I think maybe we should do it (feel free to 👍 on that issue if you think it should be done!).

**Comment by DanTup** [comment]
I added an option for this wjhich will ship in vNext (https://github.com/Dart-Code/Dart-Code/issues/1338).
