### ISSUE TITLE
Could not find a Flutter SDK. Please ensure flutter is installed and in your PATH (you may need to restart).

### ISSUE THREAD

**Issue by astannard** [Dart-Code/Dart-Code#627]
Running windows 10, 
I downloaded the flutter SDK and ran doctor, the doctor states all is good.
When trying to run the dart code Flutter: New Project command it gives the following error:
Could not find a Flutter SDK. Please ensure flutter is installed and in your PATH (you may need to restart).

I can confirm flutter is on my path, and I have restarted. After digging through your repo I also tried adding a FLUTTER_ROOT to my environment variables but this made no difference. 

flutter is working from the command line

**Comment by PromoFaux** [comment]
Can confirm

![image](https://user-images.githubusercontent.com/1998970/36788936-bc58a274-1c87-11e8-877c-b62e9b2a42c0.png)

**Comment by DanTup** [comment]
Sorry about this - I believe you're hitting #624 and/or #630. Please upgrade to v2.9.2 and try again and let me know if you see the same issues.

Note: Windows seems bad about updating PATHs, so if you've added to your path and launch Code from explorer without rebooting, it's possible it won't be given to us, so if you still see issues with v2.9.2 after restarting Code, try a reboot (sorry!).

**Comment by DanTup** [comment]
Note: With the fixes, you should only need `flutter` in your path, you shouldn't need FLUTTER_ROOT or any VS Code settings set explicitly. Let me know how it goes!

**Comment by PromoFaux** [comment]
![image](https://user-images.githubusercontent.com/1998970/36790730-aee1faae-1c8d-11e8-8318-6974fd3be7bf.png)

🎉

**Comment by FBloembergen** [comment]
Fixed it for me @DanTup !

**Comment by DanTup** [comment]
Excellent, thanks for confirming!

@PromoFaux Feel free to raise another issue (or grab me in [Gitter](https://gitter.im/dart-code/Dart-Code) and we can try to debug. It's worth also trying to run with `flutter run` from the terminal to see whether it gives any more info (I think there's a `--verbose` flag that may help).

**Comment by wilk3ns** [comment]
Same here on Ubuntu 17.10! Path is set, dart extension version is 2.9.2 but couldn't find SDK!

**Comment by DanTup** [comment]
@wilk3ns Can you confirm which SDK the message mentions (Dart or Flutter)? Can you try launching code from the terminal immediately after running `flutter` to show it on `PATH`?

As a quick fix, you can set the `dart.flutterSdkPath` path to your Flutter SDK.

In an upcoming version we'll provide some logging of the search paths, but it's most likely that the `PATH` being sent to Code is stale and doesn't include flutter. You should try rebooting if you haven't already.

**Comment by DanTup** [comment]
Another option to debug this is to clone this repo, open it in VS Code, put a breakpoint in the `findSdks` function in `utils.ts` and then press `F5` and try to open a Flutter project (or run `Flutter: Create New`). You can then examine `process.env.PATH` and see exactly what `PATH` has been passed into Code.

**Comment by astannard** [comment]
All working now thanks!! Great tool thank you!

**Comment by DanTup** [comment]
Good to hear!

For vNext I'm gonna update the error message to have a "Locate SDK" button that will let you just browser to the SDK in a folder picker. This should make it easier for people than figuring out why their PATH updates aren't working (it seems to be a bit of a minefield). See #628.

**Comment by DanTup** [comment]
For anyone still having path issues, please try [v2.10.0 Beta 1 of Dart Code](https://github.com/Dart-Code/Dart-Code/releases/tag/v2.10.0-beta.1) and it should now allow you to easily select the SDK folder from the error message.

**Comment by wilk3ns** [comment]
@DanTup  Thanks! launching code directly after adding path looks to be working. Was able to create project and deploy. But unfortunately no other command is available in command palette but "Flutter: New Project"

**Comment by wilk3ns** [comment]
@DanTup thank you for quick response! now i figured out path somehow failed to be saved in bashrc, added manually and now it works every time

**Comment by rayjadore** [comment]
flutter commands dont work on my ubuntu terminals have tried to confugure .bashrc and .zshrc but to no avail

**Comment by DanTup** [comment]
@rayjadore If you're getting the message about the SDK not being found, please click the "View Log" button and review the places being searched. It's possible that how you're setting PATH is not a way that's visible to Code.

If you're seeing something different, please open a new issue with more details.

**Comment by Wellvergton** [comment]
Following what @DanTup said works on Ubuntu 18.04.

**Comment by locomuco** [comment]
same issue still happening on:

ubuntu 19.04
vscode 1.37.1
dart/flutter 3.3.0

workaround:
add to user settings.json

"dart.flutterSdkPath": "<path to sdk>/flutter/bin"

**Comment by DanTup** [comment]
This issue is very old, so I'm not sure what exactly is still happening. There is a bug in the current live version that stops the "Locate SDK" button saving correctly - that's fixed for vNext. If you're having issues other than that, please open a new issue with specific details and I'll take a look. Thanks!
