### ISSUE TITLE
Dart Code can't find flutter sdk 

### ISSUE THREAD

**Issue by Sprinting** [Dart-Code/Dart-Code#633]
Dart Code can not find flutter sdk, even though it is in path and I can run from the command line (Using windows)
Here is the output from `flutter doctor -v`
```
[√] Flutter (on Microsoft Windows [Version 10.0.16299.192], locale en-IN, channel beta)
    • Flutter version 0.1.4 at C:\flutter\flutter
    • Framework revision f914e701c5 (10 days ago), 2018-02-19 21:12:17 +0000
    • Engine revision 13cf22c284
    • Dart version 2.0.0-dev.27.0-flutter-0d5cf900b0

[√] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at C:\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = C:\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] VS Code (version 1.20.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.9.2

[√] Connected devices
    • F1f • 7080e4ac • android-arm64 • Android 5.1.1 (API 22)

• No issues found!

```

![image](https://user-images.githubusercontent.com/16353379/36838874-5cf77582-1d66-11e8-8384-b86c443af6f7.png)

**Comment by DanTup** [comment]
@Sprinting Can you try rebooting to see if that helps? Several people (including myself) have had issues with Code having a stale `PATH` until after a reboot :(

**Comment by Sprinting** [comment]
Yes, rebooting seems to have solved it. Thanks!

**Comment by DanTup** [comment]
Great, thanks for confirming!

**Comment by bramses** [comment]
Restarting didn't work for me still seeing the same error. Flutter doctor is working fine in BASH though ```
Brams-MacBook-Pro :: ~ » flutter doctor
/Users/macbookpro/flutter/bin/flutter: line 75: [: !=: unary operator expected
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13.3 17D47, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 2.3)
[✓] VS Code (version 1.20.1)
```

**Comment by DanTup** [comment]
@bramses

How did you set `PATH`. IIRC setting it in a bash profile doesn't apply to things launched outside of the terminal? I remember I had to set the path somewhere weird on Mac OS but don't remember how now :(

Some possible help:

https://apple.stackexchange.com/questions/51677/how-to-set-path-for-finder-launched-applications

My PATH contains flutter, but I don't know where from as it's not in my bash profile. It might be from setting with `launchctl` but I'm a bit of a Mac newbie so I don't know for sure (cc @mit-mit @devoncarew any ideas where PATH should be set?!).

**Comment by bramses** [comment]
@DanTup thank you for the great tips, apologies for not responding. I've solved my issue, but basically I needed to resource and reboot my computer (I recently switched from oh my zsh to bash). I did end up adding it in the ~/.bash_profile. Thank you again!

**Comment by DanTup** [comment]
Glad you got it sorted. If you have any other issues, do shout!

**Comment by DanTup** [comment]
For anyone still having path issues, please try [v2.10.0 Beta 1 of Dart Code](https://github.com/Dart-Code/Dart-Code/releases/tag/v2.10.0-beta.1) and it should now allow you to easily select the SDK folder from the error message.

**Comment by thilakks** [comment]
HI all ,Iam alway getting this issue,I tried lot in my MacBook using VS>
Could not find a Dart SDK. Please ensure dart is installed and in your PATH (you may need to restart)

**Comment by DanTup** [comment]
@thilakks Is Dart/Flutter in your `PATH`? When you get that message there should be an `Open Log` button which will list the paths being searched for the SDK. Please review whether the paths you expect are being searched.

Alternatively, just click the `Locate` button and manually browse to it.

(If you're opening a Flutter project but the notification says Dart, it suggests that we haven't correctly detected the project as Flutter, so we'll need to figure that out - the same log may have clues for this).

**Comment by alphadead** [comment]
@DanTup I have added flutter to path but still in my vs it's showing sdk not found, I've been using it with no errors from the last 4-5 months and I don't knnow how it started showing this today

**Comment by alphadead** [comment]
![Untitled](https://user-images.githubusercontent.com/59703099/120303737-c0581300-c2ec-11eb-848e-074a0fce8f69.png)

**Comment by DanTup** [comment]
@alphadead if you click "Show Log" the log will include the search paths. If you're on Widows, you may need to reboot after setting your `PATH`. If you're on Mac/Linux then you may have set your `PATH` in a location that does not apply to the VS Code process (for example setting `PATH` in a terminal script may not apply to a VS Code process launched from the dock).

The easiest fix is to just click "Locate SDK" and manually locate it, then it should be recoded in your VS Code User Settings and located automatically next time.
