### ISSUE TITLE
Add exception to variables window

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#634]
Split from #616. We should inject a fake local when we're stopped for an exception so the user can inspect it.

**Comment by DanTup** [comment]
@devoncarew Does this implementation seem reasonable (4df44befec4419e1d584733945a363ff087aaa83 - it's relatively small!)? I'm still a bit nervous with this code!

Basically in the handlePaused/handleResume I stash/clear the exception reference (same as the `atAsyncSuspension` var) and then when asked for scopes I add one called "Exception" if there's a reference. This basically walks the exception like any other variable in `getVariables` so it just shows all the fields:

![exc](https://user-images.githubusercontent.com/1078012/37035455-85381524-2144-11e8-91b7-54bb273df004.png)

**Comment by devoncarew** [comment]
Yup, looks great! This gives the user an easy way to investigate non-trivial exception objects.
