### ISSUE TITLE
Should code assist invocations show a busy indicator?

### ISSUE THREAD

**Issue by xster** [Dart-Code/Dart-Code#641]
<anecdotal/feel free to close as unactionable>
I can't reproduce this but I tried to invoke a code assist (to turn a stateless widget to a stateful one). It took a good 5s for the popup to show up but I had no idea it was doing something asynchronous. So I kept pressing cmd-.

Eventually the popup appeared after I left the VSCode window. 
</>

**Comment by DanTup** [comment]
Normally the only time this is slow is while it's still analyzing, and there should be an analyzing spinner in the status bar? If this is the case, I'm not sure adding another note to the status bar would help much, and we can't render anything in-screen as it's all handled by Code (I think it's a deliberate choice to not show anything until it gets responses in case it starts drawing something and then there are 0 results).

If you have any suggestions though, let me know!

**Comment by xster** [comment]
Nop, I don't have a better suggesting. A spinner next to the text cursor or the mouse cursor would help but it sounds impossible. 

Closing.

**Comment by DanTup** [comment]
If you think this is happening frequently, let me know. If it's normally the case that it either responds fast, or it's kinda slow, we could display a progress indicator after x milliseconds (so normally it wouldn't show, but if it seems like it's being slow it will).

Also - if it's always tied to initial first analysis (eg. the server doesn't respond quick while it's still parsing) I was considering adding a more obvious progress notification (using the new toast popups I just implemented for long running tasks on a branch) for the first analysis (so you'd see it when you open a new project, to see that it's doing it's initial parsing). LMK if you think it's a good idea.
