### ISSUE TITLE
UX of flutter refactoring can be improved

### ISSUE THREAD

**Issue by rrousselGit** [Dart-Code/Dart-Code#644]
<img width="330" alt="screen shot 2018-03-04 at 3 43 21 pm" src="https://user-images.githubusercontent.com/20165741/36946801-d1028fd0-1fc2-11e8-807c-61b451056cbe.png">

Refactoring options for widgets are redundant. Some options do the same thing with only a small variation :
- Wrap with new Widget
- Add padding
- Wrap with Column
- Wrap with Row
- Center widget

We can merge all of these into two options :
- Insert single child Widget
- Insert multi child Widget

At the same time, these 2 options should be at the top of the list. Since they are the most commonly used.

Finally, the ability to assign these options to a keybind would be appreciated. As we can use `Wrap`/`Remove` quite often.

**Comment by DanTup** [comment]
Which branch are you on? There have been some changes to this list/ordering recently so not sure if this is the latest (if you're on `master`, it probably is, but I think `beta` might not be).

cc @mit-mit @devoncarew for opinions (this may be better in the SDK or Flutter repo, not sure?).

> Finally, the ability to assign these options to a keybind would be appreciated. As we can use `Wrap`/`Remove` quite often.

This is planned - you can subscribe to #561 for updates.

**Comment by rrousselGit** [comment]
> Which branch are you on?

Currently using the latest (2.9.2)

> This is planned - you can subscribe to #561 for updates.

Thanks ! Missed that one.

**Comment by DanTup** [comment]
Sorry, I meant which Flutter branch (`master` or `beta`) since the refactors come from the SDK. The `maste.r` branch is more likely to have the latest changes (though is bleeding edge code so could also be less stable)
