### ISSUE TITLE
Local variables only show when at top of stack

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#652]

**Comment by DanTup** [comment]
Actually, this seems to work as expected. I think the frames I looked at didn't have any (or were private code or something). I can actually see locals from several layers in testing.

**Comment by kinex** [comment]
I noticed that local variables are not shown below the first "asynchronous gap" in the call stack. Tooltips won't work and "Variables" view does not show local variables. This makes the callstack much less useful  as those "asynchronous gaps" are common and being able to see e.g. parameter values in callstack would be important.

**Comment by DanTup** [comment]
@kinex Could you open a new issue and include a screenshot of what you're seeing (and if possible, [a log for Observatory](https://dartcode.org/docs/logging/#capture-logs-command)). Thanks!

**Comment by kinex** [comment]
@DanTup  https://github.com/Dart-Code/Dart-Code/issues/1507 I added a sample code, should be easy to reproduce. Let me know if you need more info.
