### ISSUE TITLE
Document symbol list includes constructor invocations

### ISSUE THREAD

**Issue by xster** [Dart-Code/Dart-Code#656]
Low prio question:

![screen shot 2018-03-06 at 2 10 34 pm](https://user-images.githubusercontent.com/156888/37062428-457dce90-214b-11e8-80b7-1e45bb6466ca.png)

The new cmd-T cmd-shift-O speeds are aaaaaaaweeeeeeesome!!!!!!!

Just curious semantically what made this come up while trying.

The file I ran this cmd-shift-O on was https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/cupertino/picker.dart. 

On a bit more testing, it seems like it's not that it's listing local variable declarations. 

Is in normal that all constructor invocations are listed in cmd-shift-O? It doesn't seem like constructor invocations are returned in cmd-T.

**Comment by DanTup** [comment]
> The new cmd-T cmd-shift-O speeds are aaaaaaaweeeeeeesome!!!!!!!

FWIW, the new API is only used for Workspace-symbol search (`Ctrl+T`) so the `Ctrl+Shit+O` behaviour is unchanged :-)

> Just curious semantically what made this come up while trying.

Interesting! In this case we're giving all symbols to Code and it's filtering them itself. We've decided for some reason that `build.Stack` is a useful way to refer to the local `result` variable in that method. This seems kinda bogus to me.

> On a bit more testing, it seems like it's not that it's listing local variable declarations.

I think it's naming them badly - I think it's using the type name where it should have a variable name (as `build.Stack` should actually say `result` and have `_CupertinoPickerState.build()` as its container name?

> Is in normal that all constructor invocations are listed in cmd-shift-O?

I don't think so, but I think this is also the same as above (it's actually showing the variables, but naming them badly?).

**Comment by DanTup** [comment]
Now I look at this, I wonder if we're even using the right API here. The outline we have for what you're looking at is `CONSTRUCTOR_INVOCATION` and it seems totally bogus to be listing that in the document symbol list.

@scheglov this feature is a document-specific version of the search you added `getDecelerations` for (and it gets filtered client-side by Code so we don't need to search it). Is `OUTLINE` a bad choice for the source data for this?

If there's nothing more appropriate, would you object to adding a `file` to `getDeclerations` so we could use that for this one too?

**Comment by xster** [comment]
Ya, I'm not sure it's listing local variables and naming them poorly. On declarations of local variables that are doubles or bools or some such, they don't end up appearing. It's constructor invocations like you're pointing out.

**Comment by DanTup** [comment]
Yeah, my original comment was well off the mark - I realised when I had a quick test. It seems super-broken - I'm not sure how nobody (including me when I did this) noticed this. I'll see what @scheglov thinks.. it might be nice to use the same API as for the workspace one; then we can share the code and the presentation and results will be the same.

**Comment by DanTup** [comment]
Looking at the screenshots in PR this was sent in (#45) I wonder if something changed since - there's no invocations shown there (though also no local variables).

I'm now thinking maybe local variables is overkill, so maybe we could fix by just filtering out the constructors?

**Comment by DanTup** [comment]
Aha, maybe CONSTRUCTOR_INVOCATION is new in the outnline.

https://github.com/dart-lang/sdk/commit/47a861ca85275da9358443fcab10c48ab780ada9

I'll have a look at filtering these out for now. @xster does that solve your issue - is it just that constructor invocations are showing up, or do we need to do anything else?

**Comment by xster** [comment]
ya, merging the backends and removing these constructors would be good

**Comment by DanTup** [comment]
Merging the backends will need work in the analyzer (and won't need the filter).

I'll filter them out for now and if `getDeclerations` is extended to include a path in future I'll switch over to it.

**Comment by DanTup** [comment]
Moved the request for search.getDeclerations change to -> https://github.com/dart-lang/sdk/issues/32461

**Comment by DanTup** [comment]
Hmmm, this is weird. I created a test script that has constructor calls in it and I don't see them (either on 1.24 stable or 2-dev32):

![whaaa](https://user-images.githubusercontent.com/1078012/37167529-147f066e-22fa-11e8-8a66-1b929768f81e.png)

I wouldn't have expected it to be Flutter-specific, but I'll do some more testing...

**Comment by DanTup** [comment]
By the way, I think the display above is wonky - I think `MyClass` should be at the end ("container name"), with get/set dropped off, so the left hand edge is all the symbol names directly.

WDYT?

**Comment by DanTup** [comment]
Yeah, those invocations show up in the Flutter one - not sure exactly what the trigger is. I'll work on some improvements and post back screenshots for your opinion (maybe next week now).

![flutter](https://user-images.githubusercontent.com/1078012/37167781-ce5adc0c-22fa-11e8-9aa4-e753301bba60.png)

**Comment by DanTup** [comment]
Sweet, we can share the code now -> https://github.com/dart-lang/sdk/issues/32461 :-)

**Comment by DanTup** [comment]
Ok, I'm fixing up the legacy provider for those on older SDKs (I'll work on the new one this week). The above Code I posted (non-Flutter) looks like this after changes:

<img width="445" alt="screen shot 2018-03-10 at 17 09 11" src="https://user-images.githubusercontent.com/1078012/37244796-f2ee4acc-2485-11e8-9e25-49856c49db91.png">

I think this is much better than the one that has `MyClass.` prefixes (this is actually how it looks if I just don't do anything massaging of the data that comes back from the server, which is always reassuring).

I'll filter the constructors out in Flutter too, though it's less likely anyone will see that since by the time this ships (end of month) even the beta might've rolled to something that'll support the new one version I'll write.

**Comment by DanTup** [comment]
Fixed this by filtering out `CONSTRUCTOR_INVOCATION` and `FUNCTION_INVOCATION` plus added tests. Opened #675 for adding a new version that re-uses same `search.getDeclerations` as the workspace one (which won't really make any noticeable different to anyone).
