### ISSUE TITLE
Request: Implement a `Flutter: Screenshot` command

### ISSUE THREAD

**Issue by Phrohdoh** [Dart-Code/Dart-Code#657]
This should match the `flutter run` CLI `s` command.

**Comment by DanTup** [comment]
@devoncarew I can't see this in the `daemon` docs - is it exposed to editors?

**Comment by DanTup** [comment]
I just noticed that you can run `flutter screenshot` anywhere and it'll take a screenshot and dump it to that folder. So how about:

- Add a new `Flutter: Save Screenshot` command
- Read the path from settings
- If not path, prompt the user for a Folder to save to (and save it into workspace settings - as a relative path if possible - need to check how this will work from a workspace file)
- If folder doesn't exist (eg. was read from settings and has since been deleted), create it
- Invoke `flutter screenshot` in that folder

**Comment by timsneath** [comment]
Taking a look at this one, as a way to get more familiar with the Dart-Code extension. Started hacking something up in the flutter-screenshot branch of my fork.

**Comment by DanTup** [comment]
Cool, let me know if you need any assistance or when you want feedback 👍

**Comment by Ramalus** [comment]
> I just noticed that you can run flutter screenshot anywhere and it'll take a screenshot and dump it to that folder. So how about:
> 
> Add a new Flutter: Save Screenshot command
> Read the path from settings
> If no path, prompt the user for a Folder to save to (and save it into a variable so we don't prompt again for this session)
> If folder doesn't exist (eg. was read from settings and has since been deleted), create it
> Invoke flutter screenshot in that folder
 

@DanTup and @timsneath maybe this could be something more platform specific. At least for the Mac. On macs the default saving location for screenshots is the `~/Desktop` folder.

Then it should be possible to add a path config if one wants to change the default behaviour. (something like we used to do with dart code's logs, for instance).

I'm not sure what the default behaviour for screenshots is on windows and I'm pretty sure different Linux desktop environments use different default locations, but at least for mac (and probably windows) it could follow the system's default.

Just a suggestion, of course. :)

**Comment by DanTup** [comment]
@Ramalus The plan is to include a setting for you to set a folder, and prompt the first-time-per-session if it's not set. I don't know about shipping defaults without the user choosing them though. On Windows, PrtScreen copies to clipboard but I don't think there's a built-in way that saves anywhere by default.

@timsneath FYI, I might merge and finish this off and include in v2.15; trying to clear out branches and PRs to reduce effort resolving merges later.

**Comment by timsneath** [comment]
Would you give me until the weekend to have one more go? Have a bit more bandwidth and a long flight home from Beijing on Friday now that Flutter RP1 is out the door.

On Wed, Jun 20, 2018, 11:38 PM Danny Tuppeny <notifications@github.com<mailto:notifications@github.com>> wrote:

@Ramalus<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRamalus&data=02%7C01%7C%7Ce8cd4a3743fb4c5f077708d5d741aa31%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636651599375073203&sdata=5eQi06If76vmEOd0pFQsO3d4MARww3ArxUFrfnJQbdo%3D&reserved=0> The plan is to include a setting for you to set a folder, and prompt the first-time-per-session if it's not set. I don't know about shipping defaults without the user choosing them though. On Windows, PrtScreen copies to clipboard but I don't think there's a built-in way that saves anywhere by default.

@timsneath<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftimsneath&data=02%7C01%7C%7Ce8cd4a3743fb4c5f077708d5d741aa31%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636651599375073203&sdata=yGSPidW6w01DgHQ%2F%2F2PJazdrTqcjvt49aNDw%2FHuX%2FCM%3D&reserved=0> FYI, I might merge and finish this off and include in v2.15; trying to clear out branches and PRs to reduce effort resolving merges later.

**Comment by DanTup** [comment]
@timsneath Sure! 👍

**Comment by DanTup** [comment]
This has been merged for v2.17. There's no keybinding by default, but it's in the command palette and you can bind you're own. It'll prompt you for a folder the first time and save screenshots there. You can also set `dart.flutterScreenshotPath` to always default there and not be prompted.

Thanks @timsneath and @Ramalus!
