### ISSUE TITLE
Option to include SDK types in search results

### ISSUE THREAD

**Issue by pulyaevskiy** [Dart-Code/Dart-Code#659]
For instance, searching for `Future` in Dart SDK or `SliverList` in Flutter SDK to be able to quickly jump to the source code and documentation (especially for Flutter as there is a lot of useful information in doc comments).

**Comment by pulyaevskiy** [comment]
Duplicating part of my reply in the SDK issue which is more relevant to Code.

---

Here is how UX for this feature works in Intellij:

![kapture 2018-03-07 at 9 56 52](https://user-images.githubusercontent.com/441756/37109187-10261358-21ee-11e8-8117-aa3a091c0024.gif)

Hot key is `Cmd+O`, hitting it again while the dialog is open toggles "Include non-project dependencies" checkbox, which I find really convenient.

**Comment by DanTup** [comment]
Go raise a case with Code for that tickbox and then we wouldn't need to stick it in a setting :)

**Comment by pulyaevskiy** [comment]
I can do that (though I suspect it's not gonna get a lot attention). I'm not really attached to this particular checkbox, just wanted to provide one example how they did it in JetBrains.

One thing it solves though - expensive lookups are always on demand and easily controlled by the user.

**Comment by DanTup** [comment]
Someone asked for a similar checkbox on the "open file" dialog and they didn't seem to interested in it (suggesting we were asking for them to scan your entire hard drive). It feels more appropriate here, though based on the UI it probably would need to be another keybind (search workspace + external libraries).

It'd be useful for others too (eg. in typescript you could use it to search in the type declarations/node_modules there) :-)

**Comment by DanTup** [comment]
This was fixed in https://github.com/dart-lang/sdk/issues/32446.
