### ISSUE TITLE
Add a default keybind for Full Restart

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#678]
Maybe Ctrl+F5? We could use a context to only apply while debugging, so we don't overwrite the Run-without-debugging key.

**Comment by Phrohdoh** [comment]
I'd like to tackle this.

**Comment by DanTup** [comment]
The keybinds are delcared in `package.json` where the command is declared. The `when` property can be used to restrict it to specific context. There's already a context in code named `inDebugMode`.

Looks like Ctrl+F5 is not bound to anything in debug mode, the existing binding is specifically not debug mode, so should work great:

<img width="759" alt="screen shot 2018-03-10 at 21 21 03" src="https://user-images.githubusercontent.com/1078012/37246848-048667f6-24a9-11e8-883d-0675f8c632ed.png">

**Comment by RandalSchwartz** [comment]
TIL how to add a keybinding in VSC!  And the difference between restart and stop/start thanks to Wm.
