### ISSUE TITLE
Running `pub` or `flutter` commands from palette should automatically call to the other if appropriate for the current project

### ISSUE THREAD

**Issue by Phrohdoh** [Dart-Code/Dart-Code#681]
In Flutter projects we should run `flutter packages get` instead of `pub get`.

---

Considerations:

Should we create a different setting for this?
Should we rename the existing setting to `getPackagesOnPubspecChanges` to be more generic?

**Comment by DanTup** [comment]
This should happen already if your project is detected as Flutter. Can you repro it not working?

> Should we rename the existing setting to getPackagesOnPubspecChanges to be more generic?

Probably, though people might be using it. We could write an upgrade to automatically do it for them, but if they commit and their colleagues haven't updated, it'll get lost. If we really want to update it, we should probably

1. Add the new setting, but fall back to the old one
2. In the next release, upgrade both as workspace + user settings
3. In the next release, remove the old setting

**Comment by DanTup** [comment]
That should be handling the switch already is here:

https://github.com/Dart-Code/Dart-Code/blob/655ab9acabdfe643b761a487344ed943a82901be/src/commands/sdk.ts#L30-L37

**Comment by DanTup** [comment]
And the code that should trigger it:

https://github.com/Dart-Code/Dart-Code/blob/master/src/commands/sdk.ts#L68-L71

**Comment by Phrohdoh** [comment]
I must have been in the wrong directory.

**Comment by DanTup** [comment]
Actually, running `pub get` from the command palette does the wrong thing.

**Comment by DanTup** [comment]
Made a bunch of changes here - both the `Gets` and `Upgrades` should now call each other, even if invoked from the palette.
