### ISSUE TITLE
Suggest symbol rename for `Name non-constant identifiers using lowerCamelCase` diagnostic

### ISSUE THREAD

**Issue by Phrohdoh** [Dart-Code/Dart-Code#682]
Currently the only suggests are as follows:

<img width="302" alt="screen shot 2018-03-10 at 5 50 55 pm" src="https://user-images.githubusercontent.com/4861023/37248610-a1cc861c-248b-11e8-8b4f-d328419e2ca5.png">

It would be good to suggest something like...

> Rename to `apiQuote`

If we can generate the label dynamically.

If not:

> Rename using lowerCamelCase

**Comment by DanTup** [comment]
These all come straight from the analysis server, so I've moved to https://github.com/dart-lang/sdk/issues/32488.
