### ISSUE TITLE
Filter out non-unique suggestions

### ISSUE THREAD

**Issue by Phrohdoh** [Dart-Code/Dart-Code#688]
These suggests are probably unique (in that they target different spans) but to the user they are duplicates.

Given the following code:

```dart
import 'package:flutter/widgets.dart';

class _MyCustomPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    var rect = Offset.zero & size;
    var gradient = LinearGradient(
      colors: [Colors.green, Colors.red, Colors.blue],
      stops: [0.4, 0.5, 0.6],
    );
    canvas.drawRect(rect, Paint()..shader = gradient.createShader(rect));
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) => false;
}
```

I get these suggestions:

<img width="550" alt="screen shot 2018-03-12 at 5 08 32 pm" src="https://user-images.githubusercontent.com/4861023/37315701-39c7ac84-2618-11e8-9acb-6837c76fd726.png">

Now if I move two of the `Color`s onto their own line I get 2 suggestions on that line (and 1 on the previous):

<img width="546" alt="screen shot 2018-03-12 at 5 08 44 pm" src="https://user-images.githubusercontent.com/4861023/37315703-39e3d6a2-2618-11e8-8c4a-fb2fdccc6ddf.png">

### Versions

```
Dart-Code: 2.10.0

Flutter 0.1.5 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 3ea4d06340 (3 weeks ago) • 2018-02-22 11:12:39 -0800
Engine • revision ead227f118
Tools • Dart 2.0.0-dev.28.0.flutter-0b4f01f759
```

**Comment by DanTup** [comment]
We get back the actual edits with the fixes, so we should be able to disregard them based on them being the same edit rather than having to do anything like checking ranges.
