### ISSUE TITLE
Can only create new flutter projects that support Obj-C and java.

### ISSUE THREAD

**Issue by Nicholaistp** [Dart-Code/Dart-Code#695]
Not sure if there is an option for swift and/or kotlin support when creating a project but I've found nothing anywhere on how to do this from vs code and creating a project in IDEA or from terminal with those support options and opening it in vs code gets kind of annoying. Am i missing something or should this issue be marked as an enhancement?

**Comment by DanTup** [comment]
We don't currently support anything other than the defaults. We do have #618 with some requests for more - please add comments and 👍 that issue for consideration!
