### ISSUE TITLE
Review CompletionKind mapping.

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#7]
See [TODO](https://github.com/DanTup/Dart-Code/blob/c1b0fa6f3061a2e691e8d81611c75f54a4a85872/src/dart_completion_item_provider.ts#L52).

**Comment by devoncarew** [comment]
I think fixed here: https://github.com/Dart-Code/Dart-Code/pull/115.

**Comment by DanTup** [comment]
Yup, ta!
