### ISSUE TITLE
The 'Create method' helper results in incorrect indentation

### ISSUE THREAD

**Issue by xqwzts** [Dart-Code/Dart-Code#700]
![create_method_indent_s](https://user-images.githubusercontent.com/798935/37557688-1c2641de-2a11-11e8-8b7d-2967eda3c97c.gif)

`Create method` [and `Create function`] completions will append the new method at the end of the current class, and incorrectly indent everything between the current cursor and the end.

[possible dupe of #584 ?]

**Comment by DanTup** [comment]
Ugh. Could be a dupe (and therefore could be a Code bug) but I'll do some testing.

**Comment by DanTup** [comment]
I think this is the same issue so I've added more notes to https://github.com/Microsoft/vscode/issues/44200 (though nothing seems to have happened with it yet). I don't know why indenting is being messed with even if `autoIndent` is set to `false` :(

**Comment by DanTup** [comment]
Closing this as a dupe to make the issue list more manageable. Subscribe to #584 or https://github.com/Microsoft/vscode/issues/44200 for updates (and please 👍 the VS Code issue if it affects you!)
