### ISSUE TITLE
IntelliSense not selecting the first item in completion list

### ISSUE THREAD

**Issue by xqwzts** [Dart-Code/Dart-Code#703]
![completion](https://user-images.githubusercontent.com/798935/37559882-63ddc86a-2a36-11e8-9e32-d5d065b9f42b.gif)

Hitting Ctrl+Space to bring up the IntelliSense completion list occasionally sets the cursor at the middle of the list, and not at the first item, I end up with a lot of StatefulWidget snippet/Undo combinations :)

The behavior here is inconsistent [unless there's some rule it follows that I can't quite figure out], so here's my attempt at explaining what I've seen:

For the following bit of code:
```dart
new Container(
          width: 300.0,
          height: 100.0,
          child: sparkline,
),
```

- Hitting return after `child: sparkline` and then ctrl+space to trigger a completion: `Flutter stateful widget` is selected.
- Moving up the list manually and selecting `color` then hitting return to complete it works as expected.
- Hitting return after this new `color` entry: `Flutter stateful widget` is selected.
- Selecting the previously entered `color` line and hitting backspace to clear it - then hitting `ctrl+space` to bring up intellisense: `color` is selected.

It seems to me that it always defaults to `Flutter stateful widget` the very first time the completion list is brought up for this class.

**Comment by xqwzts** [comment]
Oh and the actual expected behavior would be to just default to first item in the list [since those are the ones the analyzer has given us for this context].

**Comment by DanTup** [comment]
Thanks for raising - I've seen this a few times and never investigated. I believe the wonkiness is from Code pre-selecting the last thing you used. I've raised this case saying I think it should never use the remembered value when there is no prefix:

https://github.com/Microsoft/vscode/issues/46047

I suspect they may say to switch to `recentlyUsedByPrefix` in your settings though (which I don't like, because it means either our users will be frustrated, or we'll have to change the default for Dart on them, neither of which are good).

**Comment by DanTup** [comment]
Actually, based on https://github.com/Microsoft/vscode/issues/41060#issuecomment-364284879 I think this is exactly as it's intended; but maybe it should only happen with `.` prefixes and not indenting!

**Comment by DanTup** [comment]
Also slightly related: https://github.com/Microsoft/vscode/issues/35551

**Comment by DanTup** [comment]
This should be fixed in Code, but looks like it won't ship until the April release (which is over a month away):

https://github.com/Microsoft/vscode/issues/43429

**Comment by dodas** [comment]
Sorry guys but I really haven't found answer.
What should I do to have interface properties shown at the top of the list when hitting ctrl+space without prefix?

**Comment by Anas-Alhariri** [comment]
I found the solution:

The `**"editor.snippetSuggestions":** ` is set to `**inline**`  by default in the `**defaultSettings.json**` (the default settings of VS code).
It seems that other VS code extensions that provide additional completion options; change this from `inline` to 'top' or something other than the default.

I went to my user settings of VSCode `settings.json` and changed it back to `inline` and everything works as expected.
As a result, the original VSCode completion options came back to the top of the list and you may use Tab or Enter to select them.

Hope that my answer helps you 👍
