### ISSUE TITLE
DartCode isn't compatible with Flutter that has Dart 2 by default

### ISSUE THREAD

**Issue by mit-mit** [Dart-Code/Dart-Code#704]
## Steps to Reproduce

1. Change to master channel and upgrade to latest build (this has Dart 2 by default as of Friday):
    ```
    flutter channel master
    flutter upgrade
    ```

1. `flutter create foobar`

1. In `foobar/lib/main.dart`, change:
    ```
      return new MaterialApp(
          title: 'Flutter Demo',
          theme: new ThemeData(
    ```
    to:
    ```
      return MaterialApp(
          title: 'Flutter Demo',
          theme: ThemeData(
    ```

1. Validate that analysis passes: `cd foobar`, `flutter analyze`:
    ```
    Analyzing /Users/mit/tmp/foobar...
    No issues found!
    Ran in 6.0s
    ```

1. Open project in vsCode:
    ```
    'MaterialApp' isn't a function.
    'ThemeData' isn't a function.
    ```

**Comment by mit-mit** [comment]
cc @DanTup

**Comment by DanTup** [comment]
I can repro, however I see the same if I run `dartanalyzer` from the embedded Dart SDK:

```text
Dannys-MacBook:hello_world danny$ ../../bin/cache/dart-sdk/bin/dartanalyzer .
Analyzing hello_world...
  error • The function 'Center' isn't defined at lib/main.dart:7:23 • undefined_function
1 error found.
```

Is it possible that the analyzer shipped inside isn't yet enabling this by default?

**Comment by mit-mit** [comment]
cc @devoncarew, not sure what is going on here, Android Studio has the same issue (https://github.com/flutter/flutter-intellij/issues/1931), but IntelliJ doesn't...

**Comment by DanTup** [comment]
I assumed that when we talked about the default changing, it involved all tools at the same time (including the analyzer), but I don't know if that was correct. It's possible the plan was that Flutter changed default and the editor should tell the analyzer what it thinks the setting is (though I think that may be more error prone).

I'll wait for clarification from @devoncarew before changing anything. In the meantime, setting `previewDart2: true` should at least get things back in sync if it's blocking anyone.

**Comment by mit-mit** [comment]
We are going to have a mix of SDKs with different opinions of what the default is, so yes I agree that this should somehow come from the SDK.

**Comment by DanTup** [comment]
In the next version of Dart Code my plan was to have three ways of setting the option:

- false - sends `--no-preview-dart-2`
- true - sends `--preview-dart-2`
- `null`/`undefined` (default) - doesn't send anything (lets tools have their own default)

However, if the tools aren't in-sync, this is kinda flawed. I could ditch null/undefined and default to true, but then we'd be sending the flag to SDKs that might not support it (for ex. the `dart` in my `path` is the stable v1.24 which chokes if you send it a flag). We could maybe do that only for Flutter, but we'd still know when to ship that behaviour (people using beta would want it to activate when the upgrade beta, but people using master would want it as of Friday).

Ideally, the Dart SDK inside flutter would always mirror the setting in Flutter as a default. If this isn't possible, I think we need a reliable way to tell from the `version` file inside Flutter and Dart SDKs whether the flags are supported and what their defaults are.

**Comment by devoncarew** [comment]
The dart sdk has not yet changed it's default to `--preview-dart-2` on. That is planned very shortly, and will be necessary to fix this issue. That will mean that the analysis server will default to preview dart 2.

With the beta at the end of the month, the preview dart 2 defaults for the dart sdk and the flutter sdk will both be on, so things will be in sync for the next release.

/cc @bwilkerson, who's working on flipped the analyzer default

**Comment by devoncarew** [comment]
see https://github.com/dart-lang/sdk/issues/32566

**Comment by devoncarew** [comment]
This has landed (https://dart-review.googlesource.com/c/sdk/+/47122) and is being rolled into Flutter.

**Comment by DanTup** [comment]
@devoncarew @mit-mit I've just updated `master` but still seeing an error when I removed `new` in the stocks app. If I run `dartanalyze` from the bundled SDK it reports the same (last error in the list):

```text
PS M:\Coding\Applications\flutter\examples\stocks> flutter --version
Flutter 0.2.4-pre.66 • channel master • https://github.com/DanTup/flutter.git
Framework • revision d9e3715620 (2 hours ago) • 2018-03-20 08:14:08 -0700
Engine • revision c3ab0c9143
Tools • Dart 2.0.0-dev.39.0.flutter-f1ebe2bd5c
PS M:\Coding\Applications\flutter\examples\stocks> ..\..\bin\cache\dart-sdk\bin\dartanalyzer.bat .
Analyzing stocks...
  error - Missing type arguments for generic type 'Future<dynamic>' at lib\i18n\stock_messages_all.dart:17:19 - strong_mode_implicit_dynamic_type
  error - Missing type arguments for generic type 'Future<dynamic>' at lib\i18n\stock_messages_all.dart:18:19 - strong_mode_implicit_dynamic_type
  error - Missing parameter type for 'localeName' at lib\i18n\stock_messages_all.dart:21:35 - strong_mode_implicit_dynamic_parameter
  error - Missing parameter type for 'locale' at lib\i18n\stock_messages_all.dart:36:6 - strong_mode_implicit_dynamic_parameter
  error - Missing parameter type for '_' at lib\i18n\stock_messages_all.dart:37:17 - strong_mode_implicit_dynamic_parameter
  error - Missing parameter type for 'locale' at lib\i18n\stock_messages_all.dart:56:50 - strong_mode_implicit_dynamic_parameter
  error - Missing parameter type for '_' at lib\i18n\stock_messages_all.dart:58:19 - strong_mode_implicit_dynamic_parameter
  error - Missing return type for '_notInlinedMessages' at lib\i18n\stock_messages_en.dart:21:3 - strong_mode_implicit_dynamic_return
  error - Missing parameter type for '_' at lib\i18n\stock_messages_en.dart:21:30 - strong_mode_implicit_dynamic_parameter
  error - Missing return type for '_notInlinedMessages' at lib\i18n\stock_messages_es.dart:21:3 - strong_mode_implicit_dynamic_return
  error - Missing parameter type for '_' at lib\i18n\stock_messages_es.dart:21:30 - strong_mode_implicit_dynamic_parameter
  error - 'AlertDialog' isn't a function at lib\stock_home.dart:27:12 - invocation_of_non_function
```

The `version` file in the SDK has a commit hash from 11 days ago, though the one output by `dart --version` says 5 days ago. The change only landed in SDK in the last 2 days?

**Comment by devoncarew** [comment]
`dartanalyze` hans't toggled its default. The analysis server has, but that may not yet have quite reached flutter (it is in progress). `flutter analyze` has flipped its flag

**Comment by DanTup** [comment]
@devoncarew Do we know when the analysis server change will make it to `master`? I'd like to do a "real" test that everything lines up and the opt-out works (we also need to make sure that if this default change is in the next beta that it gets cut from a changeset after this change has made it through).

**Comment by devoncarew** [comment]
I don't know the eta, but the change has landed in the dart sdk roll into the flutter engine. The next step would be for an engine roll into flutter.

**Comment by DanTup** [comment]
Ok, I'll keep an eye on it over the next few days, thanks!
