### ISSUE TITLE
Pressing reload during flutter test crashes

### ISSUE THREAD

**Issue by xster** [Dart-Code/Dart-Code#712]
Go to a flutter test file, F5 with a breakpoint or an exception.
On the breakpoint, press:
![screen shot 2018-03-19 at 12 10 36 pm](https://user-images.githubusercontent.com/156888/37618814-a245a1ce-2b74-11e8-9a3e-f1649ca5482c.png)

Debugger crashes trying to refer to dart:ui from in a widget tester

**Comment by DanTup** [comment]
Figured this out - when we restat, Code was giving us back a full debug config (which is good), but we were then skipping over the workaround for being given the wrong config (assuming the debug config came from the user in launch.json) and falling back to the Flutter debugger.

I'll aim to release an updated Beta when I'm through more of the fixes (possibly tomorrow).
