### ISSUE TITLE
Better breakpoint stack on async function

### ISSUE THREAD

**Issue by xster** [Dart-Code/Dart-Code#713]
Feel free to close and pass on to dart sdk, might be a rehash of https://github.com/dart-lang/sdk/issues/31447 and its variants on the dart repo. 

It would be nice to get rid of all the async boilerplates from the stack when debugging async functions. 

Also would be nice to have a togglable filter to show only workspace code or give them special visual treatment in the breakpoint callstack list.

**Comment by DanTup** [comment]
Do you know a way I can reproduce a bad stack trace like this so I can examine the data to see if we can detect it? (I suspect not, but we do have some code relating to async stack frames that might be trying to handle this).

**Comment by DanTup** [comment]
@xster Ping! :)

**Comment by DanTup** [comment]
I've been trying a few things and the worst stack I could come up with was like this:

<img width="736" alt="screen shot 2018-05-03 at 2 40 35 pm" src="https://user-images.githubusercontent.com/1078012/39580006-fd013b80-4edf-11e8-9710-a61617cebfd7.png">

Is this the sort of thing you're talking about? The async gaps are squished behind `<asynchronous gap>`, though there's a lot of framework code here. We could possibly squish non-user code (similar to how we step over it if you have debugSdkLibraries and debugExternalLibraries).

Need some more info to totally understand what's being requested though.

**Comment by DanTup** [comment]
I've made a slight tweak so that async gaps now render differently (centered, without "unknown source") but I think we need VS Code support to do anything more. I've opened https://github.com/Microsoft/vscode/issues/50334 as a request for some sort of collapsing here (I'd love to hide all the internal stuff in a single subtle row that when clicked expands into the full list).

**Comment by DanTup** [comment]
Actually, I managed another small improvement. If a source is "not debuggable" (eg. if it's in a `dart:_` library, or is in a `dart:` library and you have `debugSdkLibraries: false` (the default) or it's an external package and you have `debugExternalLibraries: false` (the default)) then the frame will be greyed out. You can still click on it and jump to the source, but it gives a distinction between the code the user has chosen to be debuggable and not.

There's also an argument to always make SDK/external package code greyed, even if the user has set their preferences to debug them. I tend to have them non-debuggable, so it will work that way for me anyway so I'm open to others opinions (@xster @devoncarew @mit-mit @matanlurey).

Here's a screenshot with the defaults (both SDK and Packages are not-debuggable):

![screen shot 2018-05-23 at 11 11 04 am](https://user-images.githubusercontent.com/1078012/40418638-d129caea-5e7a-11e8-8a6c-b3155d5f96da.png)

And here's it if you've enabled `dart.debugExternalLibraries`:

![screen shot 2018-05-23 at 11 12 30 am](https://user-images.githubusercontent.com/1078012/40418658-dc204dfc-5e7a-11e8-8b49-92c2372316d0.png)

**Comment by DanTup** [comment]
@xster What are your thoughts on this now? Changes to show some stack frames greyed out shipped a while ago; do you think we still need to do more?

**Comment by DanTup** [comment]
Ok; do shout if you think there's still room for improvement (though I think what we've done might be the limit of what we can do directly in Dart Code without either SDK support or https://github.com/Microsoft/vscode/issues/50334).

**Comment by DanTup** [comment]
FWIW, when you have the next version of Dart Code and VS Code, "non-debuggable" code (based on your settings for `dart.debugSdkLibraries` and `dart.debugExternalLibraries`) will be collapsed by default :-)

![screen shot 2018-10-31 at 2 35 07 pm](https://user-images.githubusercontent.com/1078012/47795983-58e41c00-dd1b-11e8-9f35-e384b75047b0.png)
