### ISSUE TITLE
Flutter processes sometimes not being terminated correctly

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#722]
Reported by @xster in Gitter. Need to check these are being terminated correctly.

**Comment by DanTup** [comment]
@xster I can't repro this; I've tried running tests a bunch of times but the only processes remaining are `daemon` and the analyzer.

Can you let me know if you see this again and/or can repro reliably?

**Comment by xster** [comment]
I'd close this for now. I don't have a way to repro it. I ended up with 3 instances of it but it was in the mist of a bunch of other issues that it must be some combination effect.

**Comment by DanTup** [comment]
Ok, do post back if you see it again; don't want to leave processes around!

**Comment by DanTup** [comment]
Not flutter test, but I've just found this (I was seeing startup lock issues) after closing all Code instances.

<img width="1151" alt="screen shot 2018-03-22 at 10 51 53" src="https://user-images.githubusercontent.com/1078012/37766539-1c139924-2dbf-11e8-89db-7742125ca9b0.png">

**Comment by DanTup** [comment]
Of course, I cannot repro this at all :(

**Comment by DanTup** [comment]
I think the original report here may be same as #772 however I've updated the branch with the fix for that to also do the same thing for `daemon` which should fix some more of these issues.

After these ship in v2.14, if anyone has dangling processes still, I'll do more investigation (it may require similar fixes, with the `pid`s being exposed - we can figure this out based on which processes they are).
