### ISSUE TITLE
Let dart/flutter commands be cancelable

### ISSUE THREAD

**Issue by xster** [Dart-Code/Dart-Code#724]
Open a pubspec.yaml, insert a dependency url that's valid-ish but not reachable. 

Auto-runned pub get / flutter packages get will try to update packages and retry unsuccessfully and can't be terminated from inside VSCode. This also locks other attempts to use flutter.

**Comment by DanTup** [comment]
This'll go well with #723 which will result in little toast popups (like the new notifications) while these things are in progress (I think it has a cancel button, whereas without it we'd have to come up with our own way to allow cancellation).

**Comment by DanTup** [comment]
I've done this in #726, but:

1. It can't be merged until Code v1.22 ships (early next month)
2. Calling `kill` on the process for a package fetch doesn't seem to always terminate immediately; sometimes it just carries on anyway :/
