### ISSUE TITLE
Flutter: Extract part of the widget tree into its own widget class 

### ISSUE THREAD

**Issue by escamoteur** [Dart-Code/Dart-Code#731]
A common workflow with Flutter when creating a UI is starting with one Widget Tree that get's more and more complex and the you start splitting it in several of your own widgets.

So it would be awesome if I could just select any widget and get an refactoring option to wrap it in a new WidgetClass in it's own file.

**Comment by DanTup** [comment]
Looks like the server already has support for this:

https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html
