### ISSUE TITLE
Switching SDK version should be reflected in terminal ("dart.addSdkToTerminalPath" setting)

### ISSUE THREAD

**Issue by jimmyff** [Dart-Code/Dart-Code#737]
When I switch my SDK version using the status bar and then I open a terminal I don't see the new version when I run `dart --version`.

This could maybe be set in to the path when a new terminal is created?

**Comment by DanTup** [comment]
Seems like we don't have any control over the terminal creation, so I think the best we can probably do is to read from the terminals env settings.

Some info here:

https://github.com/Microsoft/vscode/issues/34337

So the user would set something like:

```js
{
  "terminal.integrated.env.windows": {
    "PATH": "${env:PATH};C:\bin"
  }
}
```

Ugh, except I tried it and we just get that literal string, not the resolved value. We could parse it manually but it's getting hacky.

I've opened https://github.com/Microsoft/vscode/issues/46696 to see if they can suggest a better way.

**Comment by DanTup** [comment]
Currently blocked on https://github.com/microsoft/vscode/issues/99878.

**Comment by DanTup** [comment]
The VS Code issue has been resolved for macOS, so we should be able to do this after the next stable VS Code release.

WIP is at https://github.com/Dart-Code/Dart-Code/tree/add-sdk-path-to-env-path, but there needs to be a setting to opt-out.
