### ISSUE TITLE
Show Memory usage during Flutter debug sessions

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#739]
Similar to https://github.com/flutter/flutter-intellij/pull/2006 though we'll be limited to text in the status bar for now. To avoid polluting the status bar too much, we may wish to consider adding this into the device-picker status bar label.

- [x] Show memory usage
- [x] Maybe only show in profile mode to avoid misleading info in debug mode?
- [ ] Subscribe to GC events

**Comment by DanTup** [comment]
Notes from reviewing IntelliJ source (looking at just memory for now)

- Wait for a performance listener to be added (I think this is happening when the panel is rendered - for us, this will just be always since we're writing to status bar)
- Set a timer that runs every 1 second that does:
  - Call `getVM()`
  - Enumerate Isolates in response
    - Call `getIsolate()`
    - Add `heap.used` and `heap.external` to `current`
    - Add `heap.total` and `heap.external` to `total`
  - Render `current of total`

Additionally it seems to subscribe to GC events but I can't figure out exactly what it's doing there (seems like it's updating the graph, but I can't see how that differs to what's being done in the polling). @devoncarew Do I need this bit?

**Comment by DanTup** [comment]
@devoncarew Is it correct that I'm reading `_heaps` (with an underscore!) to get this info?

In the doc [here](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#types) it shows `heaps` without an underscore (however there's no other information in the doc about this).

**Comment by devoncarew** [comment]
Yes, the underscore convention in the service protocol means undocumented, and not public API - `_heaps` is correct.

Re: the GC events - we get those per isolate when a GC happens. We add that into the data from the polling in order to have a slightly high frequency view of the data. We don't have new info for the heaps for the other isolates, but do for that isolate.

**Comment by DanTup** [comment]
Split FPS into #804 to avoid tying these together.

**Comment by DanTup** [comment]
@devoncarew 

> Re: the GC events - we get those per isolate when a GC happens. We add that into the data from the polling in order to have a slightly high frequency view of the data. 

We're currently already polling every second, so is there much value in this?

**Comment by devoncarew** [comment]
Some value - you'll get slightly more granular data - but not in any way a deal breaker. I have a bug open to get the before data in the GC event. That would let us graph the two data points for each GC event and know exactly what the high and low were.

**Comment by DanTup** [comment]
Ok, since we're showing a much simpler view I'm gonna skip this for now, and if we find a better way to show more info (like a graph) where the specific GC info is more useful we can add it in. I'm gonna put this behind a preview setting (so it's opt-in) for now and merge as-is so it can go into an upcoming beta build of v2.12.
