### ISSUE TITLE
Workspace symbol-search should not show private items outside of your project

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#74]
I think we should only include public-API for things in packages.

**Comment by DanTup** [comment]
See comments in #91.

**Comment by DanTup** [comment]
@devoncarew I opened that project but I couldn't actually repro.. only one result for "dir" and no privates for "di".

![Search](https://cloud.githubusercontent.com/assets/1078012/17673347/8eb979b2-6318-11e6-9ea7-0888049d03fa.png)

I've be interested to know if you can repro this (ideally on current master).

**Comment by devoncarew** [comment]
Looks fixed to me:

<img width="620" alt="screen shot 2016-08-15 at 5 52 53 pm" src="https://cloud.githubusercontent.com/assets/1269969/17684519/4cd309ac-6311-11e6-8fa9-9e9fdc96c29b.png">

<img width="617" alt="screen shot 2016-08-15 at 5 53 01 pm" src="https://cloud.githubusercontent.com/assets/1269969/17684520/4cdf0c66-6311-11e6-9068-5f9981bbd172.png">

**Comment by DanTup** [comment]
I pushed another fix last night; I was checking parent names for underscores so `_Thing.thing` would still appear which I figured wasn't expected (though now I'm wondering why you're start a class with `_` vs putting inside the `src` folder?)

**Comment by devoncarew** [comment]
I `_` class would be library private. `src/` is more of an informal convention - it's not enforced. The access for underscores is enforced by the runtime.

**Comment by DanTup** [comment]
Gotcha!
