### ISSUE TITLE
Update the name of the slow mode banner

### ISSUE THREAD

**Issue by devoncarew** [Dart-Code/Dart-Code#741]
The `slow mode` banner has been updated to `Debug`.

**Comment by DanTup** [comment]
I guess the command should be updated too! Since it's very unlikely anyone has key-bound it, I'll rename the command's ID for consistency too.

**Comment by DanTup** [comment]
@devoncarew What's the best thing to call this now? I was going to call it "Debug Mode Banner" but in code it seems to be referred to as "Checked Mode Banner"?

https://docs.flutter.io/flutter/material/MaterialApp/debugShowCheckedModeBanner.html

**Comment by devoncarew** [comment]
I would go with `debug mode` instead of checked, as that's how its presented to users in other contexts.
