### ISSUE TITLE
Honor the `ReferenceContext` in `provideReferences`

### ISSUE THREAD

**Issue by natebosch** [Dart-Code/Dart-Code#745]
https://github.com/Dart-Code/Dart-Code/blob/adfd7fb831dfcbe37dee6d98ae825f8754b19e3b/src/providers/dart_reference_provider.ts#L15

The `context` argument is ignored.

**Comment by natebosch** [comment]
In `dart_language_server` the `includeDeclaration` argument decides whether to [also search for navigation](https://github.com/natebosch/dart_language_server/blob/0c61378cfe04164a6dcbfa1b132b43f34893e084/lib/src/shim.dart#L232-L235).

Though this is also a little string since the "navigation" varies depending on where it's called from while we'd expect references to be consistent no matter where it's called from. From an `@Override` it navigates to itself. From a call site it navigates to the super class definition for the member.

**Comment by DanTup** [comment]
From the description I don't totally understand what this does... When would Code pass `true`/`false` for it?

**Comment by natebosch** [comment]
From my understanding the "Find all references" command will pass true and some other code lens context will pass false.

**Comment by DanTup** [comment]
Ok, seems like Code passes true, but it's been added to allow for things that might not want it in future.

I'm slightly unsure why a) you'd want this when you can just Go-to-Definition and b) why Code doesn't just call the definition provider, but I've added it in anyway :-)

**Comment by DanTup** [comment]
Heh, I should refresh before commenting :-)
