### ISSUE TITLE
Offer auto-fix for @mustCallSuper

### ISSUE THREAD

**Issue by xster** [Dart-Code/Dart-Code#746]
Don't know how generalizable it is to expand to all linter warnings, but would be nice for the analyzer server to return easy fixes. 

For instance, @mustCallSuper tagged methods can just have its sub class implementations auto add a line for `super.x()`

**Comment by DanTup** [comment]
This would need to come from the analysis server so best requested in the [sdk repo](https://github.com/dart-lang/sdk).

Slightly-related, I think it gets inserted automatically when using completion for overriding methods (https://github.com/flutter/flutter-intellij/issues/1110#issuecomment-365954768).

**Comment by DanTup** [comment]
I've opened an SDK issue for this at https://github.com/dart-lang/sdk/issues/33985.
