### ISSUE TITLE
High CPU when typing in Dart files

### ISSUE THREAD

**Issue by bergwerf** [Dart-Code/Dart-Code#757]
My laptop CPU gets hot a bit fast, and it seems like the frequent execution of the analyzer is increasing that (causing annoying fan noise). In top i can see quite high spikes of dart programs while typing my code. I see a few solutions that might improve the situation for me:

1. Temporarily turn off analysis while designing code, and turn it on again when debugging (could not find this option)
2. Refresh analyzer warnings manually (I would be fine pressing a function button do to this while debugging, being in control of that might actually feel nice)
3. Throttle how much CPU the analyzer takes (this is a bit of a complex solution, and probably not preferred)
4. Run the analyzer less frequent (I think this is annoying when you need it, and is not really solving the issue).

I would really appreciate option 1 and/or 2 :-)

**Comment by DanTup** [comment]
We don't actually "run the analyzer" frequently, we run the analysis server in the background as a service. It powers a large part Dart Code's functionality including code completion, so we can't just turn it off/disable it without seriously affecting its functionality.

As such, I don't think any of your suggestions will work well; however if the total CPU usage is too high then we need to look at that (I'll edit the title here to be more generally about high CPU). We can't throttle the CPU because it'll just stop things working.

> In top i can see quite high spikes of dart programs while typing

Are you seeing more than one process? There should only be one for the analysis server (though in flutter you may have a second for the daemon).

Is the high CPU generally caused only be editing and not other operations? We currently send every document edit to the server directly so there may be room to put some buffering in here. I'll do some testing.

**Comment by bergwerf** [comment]
I couldn't figure out a better way to get stats, so I added a screencast of what happens when I repeatedly undo/redo a small change. The screencasting process is getting a bit in the way but the analysis server still shows up at the top most of the time. The same thing happens without screencast. This could of course also be a problem with my laptop or setup (Firefox also frequently causes CPU spikes, especially watching videos). If you have suggestions on what I should diagnose I can try it.
And maybe one of these days I should try reinstalling my OS :-P

[vokoscreen-2018-04-02_12-27-59.mkv.tar.gz](https://github.com/Dart-Code/Dart-Code/files/1867862/vokoscreen-2018-04-02_12-27-59.mkv.tar.gz)

**Comment by DanTup** [comment]
I just gave this a go myself... I typed a random key then hit backspace repeatedly (randomly different keys to ensure there was nothing clever going on). I did it pretty fast and the CPU of the Dart process seemed to sit around 10-12%. I went and did the same thing in TypeScript and the Code Helper process (presumably where it's doing it's work) averaged around 40%!

We could definitely add some throttling to the updates we send to the server, but I'm a little concerned about adding the complexity (we need to ensure we never send operations that result in us overwriting code, like formats, while there is an unflushed buffer) if the gains won't be worth it.

Out of interest, could you enable [analysis server logging](https://dartcode.org/docs/logging/#analyzer) so we can see how much traffic is coming back? We get quite a few notifications from the server for various things, so it might be worth reviewing if we're getting more than we need for anything too.

Also, could you confirm which SDK version you're using? The latest stable version is pretty old now, and there have been significant internal changes in v2 devs (I was testing with a v2 dev).

**Comment by bergwerf** [comment]
I understand. I don't know what is wrong with my setup, the CPU is a 
bit too heavy for my laptop and overheats quickly, but I don't 
understand why it has such high spikes. I am using dev versions of 
Dart, currently `Dart VM version: 2.0.0-dev.39.0 (Unknown timestamp) on 
"linux_x64"`

I did enable logging via the settings in vscode, and this was produced 
after typing two lines with some random stuff: 
https://pastebin.com/rckcA5eu (I don't believe there is anything too 
sensitive in there, my project is not top-secret ;-P). The log looks 
quite normal. By the way under gnome when I view the activity of the 
dart process under the system monitor It stays around 10% as well, I 
think this program is averaging over all cores. I think the problem is 
probably that my CPU is just overheating at the slightest load (causing 
the fan to run faster).

**Comment by DanTup** [comment]
We seem to be sending a lot of empty edits for the same file concurrently here:

```text

[4:07:24 PM]: ==> {"id":"134","method":"analysis.updateContent","params":{"files":{"/home/herman/repos/qedb/expr/lib/src/misc/detect.dart":{"edits":[{"id":"","length":0,"offset":3065,"replacement":"a"}],"type":"change"}}}}
[4:07:24 PM]: ==> {"id":"135","method":"analysis.updateContent","params":{"files":{"/home/herman/repos/qedb/expr/lib/src/misc/detect.dart":{"edits":[{"id":"","length":0,"offset":3066,"replacement":"r"}],"type":"change"}}}}
[4:07:24 PM]: ==> {"id":"136","method":"analysis.updateContent","params":{"files":{"/home/herman/repos/qedb/expr/lib/src/misc/detect.dart":{"edits":[{"id":"","length":0,"offset":3067,"replacement":"s"}],"type":"change"}}}}
[4:07:24 PM]: ==> {"id":"137","method":"analysis.updateContent","params":{"files":{"/home/herman/repos/qedb/expr/lib/src/misc/detect.dart":{"edits":[{"id":"","length":0,"offset":3068,"replacement":"o"}],"type":"change"}}}}
[4:07:24 PM]: ==> {"id":"138","method":"analysis.updateContent","params":{"files":{"/home/herman/repos/qedb/expr/lib/src/misc/detect.dart":{"edits":[{"id":"","length":0,"offset":3069,"replacement":"i"}],"type":"change"}}}}
[4:07:24 PM]: ==> {"id":"139","method":"analysis.updateContent","params":{"files":{"/home/herman/repos/qedb/expr/lib/src/misc/detect.dart":{"edits":[{"id":"","length":0,"offset":3070,"replacement":"t"}],"type":"change"}}}}
[4:07:24 PM]: ==> {"id":"140","method":"analysis.updateContent","params":{"files":{"/home/herman/repos/qedb/expr/lib/src/misc/detect.dart":{"edits":[{"id":"","length":0,"offset":3071,"replacement":"e"}],"type":"change"}}}}
```

I don't know if we still need these - we send them to force the analysis server to provide us with data (a workaround for a bug). Even with the workaround we shouldn't send them repeatedly like this, but if we can remove them then we don't need to figure out why that is.

(It's possible it'll have no effect if the server realises there are no changes, however).

There's also some completion results in there, which can be pretty huge. Maybe we should log the sizes of responses in there (we just truncate currently with no indication of size) since that might not be helping.

How familiar are you with Observatory? If you set the `dart.analyzerObservatoryPort` you can connect to Observatory for the analysis server. You could then get a profile trace for a short period while you're typing, and that might show us which work it's doing is most expensive. If you don't know how to do this, let me know and I can figure it out (I've not done it either :)) and write some instructions.

cc @bwilkerson/@scheglov - maybe you have opinions on whether sending every key press is insane? If so, would buffering in the server make more sense (to avoid all clients a) having to do it and b) having to ensure they flush before requesting any edits)?

**Comment by devoncarew** [comment]
I do think we should rate limit updateContent calls into the analysis server. I've used different techniques for different clients, but even just a small timer that you reset as you get file changes works well. You do then need to be careful to flush it when you request a change that requires the latest file info to work on (or, flush on every call).

Some (older) code to do something similar is here: https://github.com/dart-atom/dart/blob/master/lib/analysis/buffer_observer.dart

**Comment by bergwerf** [comment]
It seems I cannot export CPU profiles in the observatory: https://github.com/dart-lang/sdk/issues/30067. But I opened it, and typed a bit, and got these results:

Peak memory: 4.4GB (after a bit over eight minutes, that is a bit shocking to me, I guess this might have something to do with the fact that the observatory is active)
Current memory: 4.3GB

![screenshot from 2018-04-02 17-32-13](https://user-images.githubusercontent.com/4458965/38202404-d1a7eeea-369b-11e8-95af-61db4e9f2488.png)

**Comment by devoncarew** [comment]
We did have a similar CPU usage issue in the atom, plugin, and solved it by introducing (the above) small buffer.

**Comment by bwilkerson** [comment]
The ExceptionHandlingDelegatingAstVisitor class is only used by the linter, so it's possible that one of more of the lint rules is causing this misbehavior. It would be useful to try an experiment of disabling all of the lints (by commenting them out in analysis_options.yaml) and see whether the behavior persists. If not, perhaps a binary elimination process might help us narrow down to a specific lint. But even without that, just knowing whether lints are causing a problem would be useful.

But I agree with Devon, sending updates on every character is probably unnecessary and potentially harmful.

**Comment by DanTup** [comment]
> The ExceptionHandlingDelegatingAstVisitor class is only used by the linter

Aha; that could explain why it seemed much lower for me.

> But I agree with Devon, sending updates on every character is probably unnecessary and potentially harmful.

If this is the case, wouldn't it make more sense to buffer in the server (or at least allow opting-in)? It seems like the sort of thing that's easy to get wrong and would be easy to end up with the server having a different idea of the contents of a file to the editor (eg. if you managed to issue a format document with unflushed changes, you would lose that work). It's also potentially allow the server to be more selective with it's throttling - eg. have some info updated always (for ex. syntax colouring) while others on a throttle (eg. outlines)?

**Comment by bwilkerson** [comment]
I'd be happy to let server do the work if it's the same for all clients, but there are some unknowns (at least unknown to me).

First, I'm not sure whether there's a universal approach that would work well for all clients. IIRC, Eclipse sent the delta after each significant pause in typing (I don't remember the actual duration it used) _or_ some number of milliseconds after the last update in cases where the user was able to sustain a high typing rate. But it seems quite likely that different clients would want different rules about when to process a sequence of changes.

Also, server can't get UI interaction times as easily as clients (if at all), so if the best (for users) rules are based on actual UI events, server wouldn't be able to implement those rules.

**Comment by scheglov** [comment]
I agree, it is up to the client to perform some buffering. That said, Analysis Server already de-facto has its own buffering. When you send many change requests for the same file, the server will remember all of them and handle one by one. Its handles by updating the overlay for the file, so the file get new content (just a single string value now), and by notifying Analysis Driver that the file has been changed. The Analysis Driver then schedules this file for analysis by adding to the set of changed files. So, if the file is already in the set, nothing changes. The scheduler for Analysis Driver will then process all changed file, i.e. just one file, just once.

It is more likely that analysis itself is expensive, as you noticed lints take more time than it is reasonable.

The amount of memory worries me too. Unless you have quite big project, you should not use so much memory. The fact that you have Observatory enabled should not affect the heap size, it affects it very little. I would go to "allocation profile" first, checked the biggest objects. Then "heap snapshot" could give some insides too, but it requires investigative approach and I cannot explain what exactly look for a priori.

**Comment by DanTup** [comment]
@bwilkerson Fair points. In that case, it may be worth adding some guidelines to the API spec about this since there are some things that could easily be done wrong (for example not flushing before sending a request that gets edits). For ex., should a client queue all non-edit requests behind a flush of edits, or only those that return edits? Could this information be encoded in the API so we can include it in the code-gen'd code?

@scheglov

> When you send many change requests for the same file, the server will remember all of them and handle one by one. Its handles by updating the overlay for the file, so the file get new content (just a single string value now), and by notifying Analysis Driver that the file has been changed. 

Is this across multiple requests? If so, what's the timing based on? Is there a delay between receiving an updateContent and the processing starting?

**Comment by DanTup** [comment]
@scheglov Understood, thanks! 2ms is pretty low so I don't think it offsets the value of buffering edits. I've opened #768 specifically for that work since I don't think it's the main culprit in this particular case.

**Comment by bergwerf** [comment]
I can look at the linting options, that would make sense, I have enabled quite a lot. I could try to narrow it down but currently I do not have time for that. As for the memory, it seemed to be steeply increasing over time. I can try to gather some more statistics later. In principle I think I should be able to reproduce this with another project. So we could pick one dart project as a 'constant' and measure from there (with the additional linting options).

These are my linting options:
```
analyzer:
  strong-mode: true
linter:
  rules:

  ##############
  # Error rules
  ##############

  - avoid_empty_else
  - avoid_slow_async_io
  - cancel_subscriptions
  - close_sinks
  - comment_references
  - control_flow_in_finally
  - empty_statements
  - hash_and_equals
  - invariant_booleans
  - iterable_contains_unrelated_type
  - list_remove_unrelated_type
  - literal_only_boolean_expressions
  - no_adjacent_strings_in_list
  - no_duplicate_case_values
  - test_types_in_equals
  - throw_in_finally
  - unnecessary_statements
  - unrelated_type_equality_checks
  - valid_regexps

  ##############
  # Style rules
  ##############

  - always_declare_return_types
  - always_put_control_body_on_new_line
  - always_require_non_null_named_parameters
  - always_put_required_named_parameters_first

  # Infer types when possible.
  #- always_specify_types

  - annotate_overrides
  - avoid_annotating_with_dynamic
  - avoid_as
  - avoid_catches_without_on_clauses
  - avoid_catching_errors
  - avoid_classes_with_only_static_members
  - avoid_function_literals_in_foreach_calls
  - avoid_init_to_null
  - avoid_null_checks_in_equality_operators

  # Too restricting
  #- avoid_positional_boolean_parameters

  - avoid_return_types_on_setters
  - avoid_returning_null
  - avoid_returning_this
  - avoid_setters_without_getters

  # For convenience we might assume a certain type even if it is dynamic.
  #- avoid_types_on_closure_parameters

  - await_only_futures
  - camel_case_types
  
  # Cascade on constructor is ugly.
  #- cascade_invocations

  - constant_identifier_names

  # I prefer sorting blocks based on visual appearance (short to long)
  # (I do sort import types in blocks)
  #- directives_ordering

  - empty_catches
  - empty_constructor_bodies
  - implementation_imports

  # Seems anti-pattern.
  #- join_return_with_assignment
 
  - library_names
  - library_prefixes
  - non_constant_identifier_names
  - omit_local_variable_types
  - one_member_abstracts
  - only_throw_errors
  - overridden_fields
  - package_api_docs
  - package_prefixed_library_names
  - parameter_assignments
  - prefer_adjacent_string_concatenation
  - prefer_asserts_in_initializer_lists
  - prefer_bool_in_asserts

  # I prefer using the class constructor to create empty instances.
  #- prefer_collection_literals

  - prefer_conditional_assignment
  - prefer_const_constructors
  - prefer_const_constructors_in_immutables
  - prefer_const_declarations
  - prefer_const_literals_to_create_immutables
  - prefer_constructors_over_static_methods
  - prefer_contains

  # In some cases this simply looks ugly and less readably.
  #- prefer_expression_function_bodies

  - prefer_final_fields
  - prefer_final_locals
  - prefer_foreach
  - prefer_function_declarations_over_variables
  - prefer_initializing_formals
  - prefer_interpolation_to_compose_strings
  - prefer_is_empty
  - prefer_is_not_empty
  - prefer_single_quotes

  # Do not add docs when there is nothing to be documented (e.g. constructors).
  #- public_member_api_docs

  - recursive_getters
  - slash_for_doc_comments
  - sort_constructors_first
  - sort_unnamed_constructors_first
  - super_goes_last

  # Infer types as much as possible, for example from a base class.
  #- type_annotate_public_apis

  - type_init_formals
  - unawaited_futures
  - unnecessary_brace_in_string_interps
  - unnecessary_getters_setters
  - unnecessary_lambdas
  - unnecessary_null_aware_assignments
  - unnecessary_null_in_if_null_operators
  - unnecessary_overrides
  - unnecessary_this
  - use_rethrow_when_possible
  - use_setters_to_change_properties
  - use_string_buffers
  - use_to_and_as_if_applicable

  ############
  # Pub rules
  ############

  - package_names
```

**Comment by scheglov** [comment]
I also see very high CPU usage by lints, about `13%` after full analysis, and up to `25%` in the middle. I don't know yet which lint causes this.

**Comment by scheglov** [comment]
OK, I have more information.
I set these lints and analyzed Flutter repo.
![image](https://user-images.githubusercontent.com/384794/38224223-f0cdc62a-36a3-11e8-8c4b-8e7da0ee65a7.png)

On the next picture don't pay much attention to absolute values, they are not consistent with the previous statistics. But take note of relative cost.
![image](https://user-images.githubusercontent.com/384794/38224258-1ff4509a-36a4-11e8-9952-8bf1a047455d.png)
FYI, all other lints cost `190 - 160 ms` each.
I suspect that in many cases we pay cost of megamorphic invocation for a lot of nodes and linter visitors.

**Comment by scheglov** [comment]
Sorry, this lints stuff is long, and probably is not the main issue.
It takes some time, but it would not matter if amount of code to analyze is reasonable.

It actually boils down to the structure of your project, dependencies between libraries and what you are changing. If you change something on what a lot of code depends directly or indirectly, all this code should be reanalyzed.

**Comment by DanTup** [comment]
> If you change something on what a lot of code depends directly or indirectly, all this code should be reanalyzed.

If you're typing inside the body of a method without changing it's public signature/interface, does that require all code that calls the method be re-analyzed?

I'm not sure from your last comment whether `invariant_booleans` is really expensive or not though.

**Comment by bwilkerson** [comment]
Yes, `invariant_booleans` is expensive (2.5 - 3 times more expensive than the next slowest). Most rules make a single pass over the AST, but `invariant_booleans` makes multiple passes over the AST. It needs to be re-written, but the most performant implementation requires a change to the lint framework.

**Comment by bergwerf** [comment]
Yes, disabling this lint does make a significant difference (although CPU usage of both the dart process and VScode is still quite high unfortunately). I think it would be a good idea to improve the performance of `invariant_booleans` but it seems this is not so straightforward from the comment of @bwilkerson 

I will disable this lint for now since it doesn't make much difference for me. @bwilkerson perhaps you could open an appropriate issue in the SDK and link it here?

**Comment by bergwerf** [comment]
I noticed the analysis server CPU is high also when just when moving the cursor (even when moving through comments!). This obviously is something that happens a lot while programming. Perhaps a topic for a separate issue?

**Comment by DanTup** [comment]
@bergwerf Yeah, please raise a specific issue for that. If possible, please include an [analysis server log](https://dartcode.org/docs/logging/#analyzer) and a note of which process is using the CPU.

**Comment by DanTup** [comment]
@bwilkerson If lints are generally expensive and a user may have a lot turned on, is there value in making them run less frequently? Even if I buffer edits for say 300ms, they're still going to run a lot. If they ran after a second or two I think it's massively cut down on resources while still providing a good enough experience (I guess this is what I was getting at with buffering inside the server above).

**Comment by bwilkerson** [comment]
> If lints are generally expensive and a user may have a lot turned on, is there value in making them run less frequently?

Possibly. But I don't believe that there's any reason why lints should be inherently expensive, so I'd prefer to try to solve the performance issue more directly rather than by running them less often. Of course, if that doesn't work ...

**Comment by DanTup** [comment]
@bergwerf Is there anything more to do on Dart Code (that isn't already covered by #768) here - do you think there are still issues not solved by #768 and #786)?

Also, is there (or does there need to be) an issue about the lints in the sdk repo?

I'd like to close this one if there's nothing to do (in Dart Code).

**Comment by bergwerf** [comment]
Of course I cannot be sure, but I think edit buffering, and the bug (?) with cursor movement were the main causes for the observed performance difference between atom and code. I'm really glad you implemented this so swiftly!

The issue with the invariant booleans lint is not really a bug. But @bwilkerson pointed out it can be implemented more efficiently. I don't know if this is already on the agenda of the SDK team, but I don't really feel like it's my position to open an issue on that (having no additional knowledge).

It seems like more and more lints are being added, and I really like that. But of course this will come at a performance cost. Perhaps an alternative (more durable) solution for the performance when writing code is to temporarily disable some lints. I have now manually disabled the invariant booleans because it doesn't do much for me, although in principle I would enable it since I don't think there should be any occurrence of this in my code. There are only a few lints that matter for me when writing code (such as variable naming). But on the other hand I can imagine this is time consuming to implement (and adds new complexity).

A solution might be to request lint updates less frequently than other things, or even have an internal list of lint rules by performance, and only request some less frequently (if that is at all possible). But maybe that goes a bit too far. Perhaps @devoncarew knows if there are other optimizations in Atom that could be copied to this plugin.

**Comment by DanTup** [comment]
Buffering the edits will reduce the frequency the lints run (which I think Atom does). I don't know how expensive they are (the lint mentioned above is 2-3 times slower than others, but I don't know whether that's still a significant amount overall).

I've been somewhat avoiding buffering edits because it feels risky (the server not having the latest representation of the code)/easy to mess up and few people have complained about the performance. It might be that this is a more sensible fix than trying to micro-optimise the lints though. If you think CPU usage is still higher than it outta be (or you feel you're disabling lints unnecessarily), add a note to the buffered-edits case and maybe I'll look at putting something in on a branch and find a good way to measure it's impact.
