### ISSUE TITLE
Copying a long string from the variables window should get the full (untruncated) string

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#760]

**Comment by DanTup** [comment]
@devoncarew Looks like this is truncated in the VM (we get back `valueAsStringIsTruncated: true`). I can't find any option to configure or disable this, so if someone does `Copy Value` from the variables window, it's truncated (and not at a particularly long length). Do you know if we can increase somehow?

**Comment by devoncarew** [comment]
We can't increase the preview that comes back, but we can request the full string. That's via the `getObject()` call; you can request the offset and length I believe, so that if the string is _very_ long, you can page through it.

**Comment by DanTup** [comment]
This was fixed a while back for Variables window and the Watch window is tracked in #1101 (it required a fix in Dart Code and also in VS Code).
