### ISSUE TITLE
Make it easier to find/run Flutter apps in profile mode

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#765]

**Comment by DanTup** [comment]
Seems like we probably can't do this without new APIs, as we can't launch the "currently selected debug config" nor provide extra arguments.

Opened https://github.com/Microsoft/vscode/issues/47122 requesting help (or a new feature).

**Comment by InMatrix** [comment]
Any news about this issue? We just had a user complain about the difficulty of switching to a profile build in VS Code.

**Comment by DanTup** [comment]
There's not a great way to do this right now (at least as I'd like), though perhaps we could do something more basic.

What I'd like to do:

- Have a command: "Flutter: Run in Profile Mode" (or similar) that will use your active debug config (selected on the debug sidebar) but with `"flutterMode": "profile"` set. This means the `args` and other settings in your `launch.config` would be honoured.

Doing that requires that we can identify the selected launch config (https://github.com/microsoft/vscode/issues/47122).

Without that, what we could do:

- Have a command: "Flutter: Run in Profile Mode" that runs the Flutter app _detected from your _open file_ and _ignoring any custom launch config in your launch.json_.

This makes things a little different to when you hit `F5` (for example if you have multiple apps in your workspace, we might launch a different one to what pressing `F5` would do), although for the majority of users (anyone without a launch.json at all, or that hasn't customised it) it would _probably_ be approximately the same.

We could also add an additional "Profile" CodeLens link (next to Run/Debug on the main method) that would do the same, although for Flutter apps it's probably not that common for users to launch from there (it's probably not that often you're inside your `lib/main.dart` for a real app).

Thoughts?

**Comment by InMatrix** [comment]
For the specific user I mentioned above, he did have some environmental variables in his launch config, so supporting your first option is needed. 

However, I agree with you that most Flutter projects probably don't have an existing launch.config. Having the IDE create a default launch.config for building the app in profile mode would be convenient. Maybe the following logic would be reasonable when the user issues the command "Flutter: Run in Profile Mode":

- If the project doesn't have `launch.config`, then create a `launch.config` with both debug and profile modes included and run the app in profile mode.
- If the project already has a `launch.config` for debug mode, then show a message about how to add profile mode to the existing `launch.config`.

What do you think?

**Comment by DanTup** [comment]
I think creating the launch.json is a little awkward - depending on the type of workspace open it could go into different places (for example in a multi-root workspace, the configs may go into the workspace file, or any of the individual folders). VS Code already has some UI to help create them that I think may be better to guide people towards:

<img width="394" alt="Screenshot 2021-05-24 at 12 17 02" src="https://user-images.githubusercontent.com/1078012/119340187-180dd300-bc8a-11eb-963a-d4d1d5ef2a83.png">

Clicking the "Create a launch.json file" link creates the file (and in a multi-root workspace lets the user choose which folder or whether to add to workspace config). Clicking "Show all automatic debug configurations" lets you pick a debug config and run it without the file (and we get to choose which ones go there).

So two things that I think would help (though I'm not sure they go far enough) would be:

1. Add a specific profile-mode template to the completion here:

<img width="707" alt="Screenshot 2021-05-24 at 12 19 46" src="https://user-images.githubusercontent.com/1078012/119340382-599e7e00-bc8a-11eb-85a9-b50db8d474cc.png">


2. Add an automatic debug config for Flutter apps (accessed with the bottom link in the VS Code Debug sidebar screenshot above, or using the **Debug: Select and Start Debugging** command):

<img width="677" alt="Screenshot 2021-05-24 at 12 20 40" src="https://user-images.githubusercontent.com/1078012/119340480-79ce3d00-bc8a-11eb-8326-0d60092311b9.png">

Note: Clicking the cog icon on the right would instead copy that config into launch.json for you to customise.

Perhaps we could still add a command, but simplify it slightly to not try to create the file:

- If there's no launch.json, just run a synthetic one that would be the same as pressing F5, but with `flutterMode: profile`
- If there is, show a message (perhaps linking to [this page](https://dartcode.org/docs/running-flutter-apps-in-profile-or-release-modes/) and updating it to reflect how the side bar looks now).

**Comment by DanTup** [comment]
I've done some of the things mentioned above because I think they make sense with or without a command:

1. Added a snippet for when editing launch.configs:
    ![Screenshot 2021-05-24 at 12 42 48](https://user-images.githubusercontent.com/1078012/119342860-928c2200-bc8d-11eb-9706-45df0c6c9341.png)
2. Changed the default config provided to VS Code when clicking "Create a launch.json" to now always include a profile config (it's easily deleted if you don't want it, but I think guiding people towards using profile mode more is probably not a bad thing):
    ![Screenshot 2021-05-24 at 12 44 12](https://user-images.githubusercontent.com/1078012/119343016-c404ed80-bc8d-11eb-9d76-500335f7ba9a.png)
3. Added profile mode to the automatic configs (accessed from the bottom link in the side bar, and the **Debug: Select and Start** command):
    ![Screenshot 2021-05-24 at 12 45 02](https://user-images.githubusercontent.com/1078012/119343088-e0a12580-bc8d-11eb-97eb-b06a95dc53e9.png)

The remaining question is whether to have a command like **Debug: Run Flutter app in Profile mode** and how it would behave (it occurs to me now, that just checking for a `launch.json` is also not reliable, as there could be launch configurations added by the workspace too). Perhaps trying to run a default configuration with just `flutterMode: profile` is the best we can do, and if users have env variables set we rely on them using the other options above?

**Comment by DanTup** [comment]
In the interest of improved visibility (even if it's a less common way to run your Flutter app), I also added a CodeLens link for the main method of Flutter projects. Like Run/Debug this will always run a default empty config (the same as the Run config, but with `"flutterMode": "profile").

<img width="223" alt="Screenshot 2021-05-24 at 12 56 01" src="https://user-images.githubusercontent.com/1078012/119344658-d41dcc80-bc8f-11eb-8670-68a050df71d2.png">

**Comment by InMatrix** [comment]
> Perhaps trying to run a default configuration with just flutterMode: profile is the best we can do, and if users have env variables set we rely on them using the other options above?

This sounds reasonable. I do believe increasing the visibility of profile mode is very important. Both providing a command in the palette and a CodeLens link will be helpful. When Dart Code runs a profile build with the default configuration, would it make sense to show a message such as "Running the app in profile mode with a default configuration. To customize it, create or edit `launch.json`."?

> Changed the default config provided to VS Code when clicking "Create a launch.json" to now always include a profile config

I like this idea. The caveat is that this could be the first time someone heard of "profile mode". Maybe we can add an inline comment to explain it briefly and link to documentation, if that's possible in `launch.json`?

**Comment by DanTup** [comment]
There's a beta version with the changes in here if you'd like to test it out before release:

https://github.com/Dart-Code/Dart-Code/releases/tag/v3.23.0-beta.1

If anything doesn't work as expected, please let me know!
