### ISSUE TITLE
Buffer edits and sending to analysis server periodically

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#768]
To reduce resource usage, we should buffer the edits being made and just send them to the server periodically (maybe after a few hundred ms). We need to be sure to wait for them all to be flushed before sending requests that return edits.

- How long to buffer for? Or wait for pause in typing?
- Which requests require the buffers flushing?

**Comment by bwilkerson** [comment]
If we aren't seeing a need for this (current or future), and it sounds like we aren't, then I would advise not doing it.

**Comment by DanTup** [comment]
I don't know of any complaints, though it's hard to say for sure whether we're burning more CPU on VS Code users than others (probably we are, though given everything is running in Chromium and using JavaScript, people might have lower expectations of performance!).

We can always re-open this, so I'm gonna abandon it for now. I think if we do decide it needs looking at we'll probably need to consider doing something that can run on the server anyway (so we can handle it for LSP) and we can try to come up with something that works for both (or if we switch to LSP for VS Code, just handle it there once).

**Comment by jamesderlin** [comment]
I'm trying to edit a moderately large package (~100K lines of code across 600 files with ~10K analysis complaints).  The files all live on a remote file system (CitC/SrcFS), and I get an annoying delay with every edit I make.  I would greatly prefer an option to buffer edits and not send them to the analysis server until I save the file; I don't see much point to sending half-typed identifiers to the analysis server.

(I suspect that running the analysis server remotely also might help, but I can't seem to find any documentation for how to use `dart.analyzerSshHost`.)

**Comment by DanTup** [comment]
> The files all live on a remote file system (CitC/SrcFS), and I get an annoying delay with every edit I make

Can you clarify where you're seeing a delay? Sending updates to the server should be asynchronous and should not affect typing.

>  I would greatly prefer an option to buffer edits and not send them to the analysis server until I save the file; I don't see much point to sending half-typed identifiers to the analysis server.

Buffering edits like this would not work at all well. Things like code completion, formatting, hovers, go-to-definition all rely on the server having an up-to-date view of the code in your editor. If the changes were not sent to the server until you saved, it would not be able to provide any language support because all of the offsets sent in requests would not point to the correct code.

I think it would be better to understand the performance issues you're seeing and find a way to improve them.

> I suspect that running the analysis server remotely also might help, but I can't seem to find any documentation for how to use `dart.analyzerSshHost`

I would definitely recommend running the server where the files are. The `dart.analyzerSshHost` setting is quite old - there's actually a much better way to do this today, with the [VS Code Remoting - SSH extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh). You'll need to have Dart installed on the remote machine, but otherwise it should be fairly straightforward and seamless. You use the VS Code Remoting extension to connect over SSH, and it will run the extension host in the remote machine and just the UI locally.

**Comment by DanTup** [comment]
I just remembered a previous issue that came up where VS Code was hanging during typing. It was the updating of the Problems view in the UI thread. I wonder if you might be seeing something similar? The original issue is here:

https://github.com/microsoft/vscode/issues/109406

It was fixed with some performance optimisations (debouncing updates to the problems view) in VS Code. I guess it's possible it's regressed, or there is some other part of the VS Code UI being updated that's expensive. If you're seeing the editor stalling, it may be worth capturing a profile trace for the VS Code UI (see https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process).

**Comment by jamesderlin** [comment]
> Can you clarify where you're seeing a delay? Sending updates to the server should be asynchronous and should not affect typing.

I type a `?` to change a type from non-nullable to nullable (to try to fix one of the 10K analysis errors...) and there's a pause before pressing the down arrow navigates to the next line.

> Buffering edits until saving would not work well. Things like code completion, formatting, hovers, go-to-definition all rely on the server having an up-to-date view of the code in your editor. 

I'm aware.  I am perfectly fine with all of those things using an out-of-date version of the code instead of what's in my buffer.

> there's actually a much better way to do this today, with the VS Code Remoting - SSH extension. 

Okay.  I actually already am using that.  I wasn't sure if the analysis server was still somehow running locally in that situation.

**Comment by DanTup** [comment]
> I type a `?` to change a type from non-nullable to nullable (to try to fix one of the 10K analysis errors...) and there's a pause before pressing the down arrow navigates to the next line.

I don't think this is caused by sending edits to the server frequently - that's all async and should never impact the editor. My suspicion is that this is either a performance issue in VS Code, or an extension forcing keypresses through the extension host (for example VIM - see https://github.com/microsoft/vscode/issues/75627) - do you know if you have any doing that?

> Okay. I actually already am using that. I wasn't sure if the analysis server was still somehow running locally in that situation.

As long as it's working correctly, it should not be - it should be running on the server. An easy way to verify is run the **Dart: Capture Logs** command and then immediately cancel, and review the headers in the log file. If running remotely, it should include a line that starts with `"Remote: "`.

> When my editor stalls, I do see CPU usage spikes on my local laptop (and its CPU fan spins up).

If it's running remotely, this does sound like an issue similar to the Problems issue I mentioned above. I would recommend capturing a profile trace using the instructions linked above. Since you mentioned having a large number of errors, I would also check whether hiding the Problems view (switch to Debug Console/Terminal) makes any difference (it did in the original issue, helping track it down to the Problems widget).

**Comment by jamesderlin** [comment]
> I type a `?` to change a type from non-nullable to nullable (to try to fix one of the 10K analysis errors...) and there's a pause before pressing the down arrow navigates to the next line.

Actually, after I make an edit, the UI is responsive for another second or so, but then it becomes unresponsive for ~5s.

I ran the profiler.

![Screenshot from 2021-03-22 03-43-39](https://user-images.githubusercontent.com/17391434/111978902-ac5c8d80-8ac1-11eb-8b81-094d43d0f928.png)

I seem to be spending an inordinate amount of time in some anonymous function in `/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:52`. The line is a gigantic blob of minified JavaScript that I can't make any sense of. (I'm using VS Code 1.53.2, commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4.)

**Comment by DanTup** [comment]
> Actually, after I make an edit, the UI is responsive for another second or so, but then it becomes unresponsive for ~5s.

This is similar to the behaviour seen in with the Problems issue linked above - since it took a little time for the problems to get back from the server to VS Code, then VS Code spent a lot of time updating the Problems view.

> I seem to be spending an inordinate amount of time in some anonymous function in `/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:52`

I'm not sure what that is either - although it's definitely in VS Code UI code. I would recommend filing an issue (and including the profiling file if possible) in the VS Code issue tracker. Feel free to tag me in it so I can help if possible.

**Comment by DanTup** [comment]
Out of interest - do you have 10k analysis errors because you're refactoring something, or at a lot of them junk files you're not interested in? You can use the `"dart.analysisExcludedFolders": []` setting to exclude folders from analysis, which - if the problem is caused by VS Code updating the problems list - might make a difference (it may be worth testing this even if just to confirm if it's related to the problems list count).

**Comment by jamesderlin** [comment]
I have 10K analysis errors because I'm trying to migrate a moderately large package to null-safety.  Since this particular package defines a bunch of abstract base types that are implemented in other packages, I also need to include their source trees in my workspace for `Find All Implementations` to work.

(For various reasons, the migration tool is not well-suited for the task, so I'm trying an alternative approach of just turning on null-safety and fixing all of the analysis errors.)  I'll try excluding the `test/` trees to see if that helps.

**Comment by DanTup** [comment]
I did some tested with the SDK repo - opening the entire folder produced > 150k errors (and still going), and I can repro a little stuttering. It gets worse when there's a filter applied, and the problem goes away completely if I close the whole bottom pane (so that neither the Problems list, nor its badge count, are visible).

After a while VS Code completely hung - although I think I was close to 300k errors and still analyzing 😬

It's probably worth filing a VS Code issue - I think it should probably handle this better, such as increasing the debounce delay if there list is huge (I also wonder if it's possible it's counting/filtering the whole error set on each update even if only a single files errors change?).
