### ISSUE TITLE
expose organize directives

### ISSUE THREAD

**Issue by devoncarew** [Dart-Code/Dart-Code#78]
There's an analysis server command for organizing directives; I'd love to have it available - I use it all the time in other tools.

**Comment by DanTup** [comment]
I looked for this and didn't find it; I guess I was looking for "Sort" or similar!

In C#, I normally have it set to do both "Remove and Sort Usings" and "Format Document". Does it seem reasonable to have some options for similar things:

- `dart.formatOnSave` - Formats the document automatically upon save
- `dart.organiseDirectivesOnFormat` - Automatically sorts (and removes unused) directives when formatting the document

I think we could default the second one to try and it wouldn't upset anyone; though auto-formatting should probably be off (I've seen what it did to my code! if you're not expecting it and don't have source control (some don't, I know!) you might get mad if we trash your perfectly formatted file).

**Comment by devoncarew** [comment]
- format on save makes sense, 👍 
- organize on format also would make sense; I have run into some situations where organize directives doesn't do a great job w/ the code. Perhaps is some items are commented out? In any case, for myself, it'd probably remain an explicit user action.

**Comment by DanTup** [comment]
> I have run into some situations where organize directives doesn't do a great job w/ the code. Perhaps is some items are commented out?

I wonder if these are things that could be handled better in the analyzer?
