### ISSUE TITLE
Add IntelliSense for project dart files (even if not imported yet)

### ISSUE THREAD

**Issue by csga5000** [Dart-Code/Dart-Code#780]
Is it possible to make intellisense show for code in other not yet imported project files, and if you select an option and press "enter" it will import that file in your current file as well as complete your typing?  This would be very convenient..

I could have sworn there was some things that did behave this way, but I just tried getting intellisense to autocomplete HashMap (for a dart package), StatelessWidget (for a flutter package), and ReviewsService (for a class defined in my project) and none of those showed (without importing the correct package/file first).

**Comment by DanTup** [comment]
I agree this would be great functionality, but I don't think it exists. It would need implementing in the analysis server (which Dart Code uses for its completion) so the [SDK repo](https://github.com/dart-lang/sdk) is the best place for it. I had a quick search and found this:

https://github.com/dart-lang/sdk/issues/25820

It's worth putting a 👍 on it and subscribing for updates.

**Comment by csga5000** [comment]
Makes sense, thanks.  Since I thought this had worked at some point I thought it may be in dart code rather than dependent on the dart sdk.  I +1'd that repo.

**Comment by DanTup** [comment]
I'll keep this open as a reminder about it (I think it's a great idea) and since we may need to do some work to insert the import statements if/when it is implemented.

**Comment by csga5000** [comment]
Sounds good.  Thanks for your attentiveness, you've been great to work with

**Comment by DanTup** [comment]
Seems I opened another issue to cover this, so this is the same as #1060. The work is in progress :-)
