### ISSUE TITLE
Analyzer not updating when working on multi-root-workspaces monorepo

### ISSUE THREAD

**Issue by rrousselGit** [Dart-Code/Dart-Code#789]
I have the following setup :

```
myWorkspace/
    myLib/
    myProject/
```

where both `myProject` and `myLib` are dart packages. And `myProject` has `myLib` as dependency.
Where that dependency is done using a `path` import like this :

```
name: my_project
dependencies:
  my_lib:
    path: ../myLib
```

The thing is, when updating the code of `myLib`, `myProject` isn't aware of the changes.
Running `Reload Window` command fix things. So this is most likely a problem with `Dart code`. 

This problems occurs both with and without ` "dart.debugSdkLibraries": true, "dart.debugExternalLibraries": true,"`
 

visual example : (left file correspond to `myProject` and right file to `myLib`)

![image](https://user-images.githubusercontent.com/20165741/38426030-c87d031a-39b5-11e8-9ba0-9c4c3ec7da06.png)

**Comment by DanTup** [comment]
Are you on Windows by any chance? If so, I think you're hitting this:

https://github.com/dart-lang/sdk/issues/32766

**Comment by DanTup** [comment]
Please try turning on [`dart.previewExperimentalWindowsDriveLetterHandling`](https://dartcode.org/releases/v2-12/#preview-better-handling-of-windows-paths). If you have any issues with it, please open new cases - it will become the default in an upcoming version.
