### ISSUE TITLE
Formatting deletes newline before comments

### ISSUE THREAD

**Issue by NatoBoram** [Dart-Code/Dart-Code#797]
Let's say I have a nicely formatted function : 

```Dart
/// Send a packet and register the callback
void send(String action, Map<String, Object> data) {
  
  // Create callback
  int cback = new DateTime.now().millisecondsSinceEpoch;

  ...
}
```

Now, I'll write code somewhere else in the document, and then it'll need to be formatted. Obviously, I'll run the "Format Document" shortcut, but then the first comment of every functions receives some undesired sexual advances from the formatter.

```Dart
/// Send a packet and register the callback
void send(String action, Map<String, Object> data) {
  // Create callback
  int cback = new DateTime.now().millisecondsSinceEpoch;

  ...
}
```

So, yeah. If the formatter didn't abuse my project's readability, that'd be great.

**Comment by DanTup** [comment]
Dart Code just uses the standard Dart formatter so we can't control this. Info on the formatter is here:

https://github.com/dart-lang/dart_style

It is deliberately opinionated and doesn't have (many) options for controlling output.

I'm not a huge fan of it myself, I think it somewhat undervalues readability (I think [this comment in the flutter style guide](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#in-defense-of-the-extra-work-that-hand-formatting-entails) describes it well), but it's currently the only option in Dart Code.

If you think it's doing something bad/incorrectly, it would be best raised at the repo above - it's unfortunately not something I can change from the Dart Code side (without implementing a custom formatter anyway, but that doesn't currently seem like a good investment).

**Comment by NatoBoram** [comment]
Thanks! I shall be reporting this absurdity upstream!
