### ISSUE TITLE
Support "format selection" [LSP]

### ISSUE THREAD

**Issue by partounian** [Dart-Code/Dart-Code#812]
When I use the vim command `=`, it throws the error `There is no formatter for 'dart'-files installed.`

VSCode Version 1.22.2 (1.22.2)
Dart Code Version 2.11.2

**Comment by DanTup** [comment]
I can't find any information on what the vim command `=` is supposed to do - can you provide more info about this? (I think a VsCodeVim extension, but I can't find any docs suggesting that `=` is related to formatting).

If you click `Format Document` in the context menu, does that work? If so, my guesses are:

1. Something is buggy with the vim extension
2. It's trying to format a selection, which isn't supported by Dart (requires https://github.com/dart-lang/dart_style/issues/92)

**Comment by partounian** [comment]
`=` if used in vim for formatting though it is required to choose a selection (the selection can be the entire file with `gg=G` [go to top of file, format until bottom]). Format document does work, so it is safe to assume this is related to dart-lang/dart_style#92 .

**Comment by DanTup** [comment]
Seems like we actually don't have an open issue about this as a reminder, so I'm re-opening this and re-purposing it. If/when the above case is done, we will implement this (and in the meantime, this case can serve as a reminder of something we want to do but are blocked on).

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/44e680ac539509222c3ac64c96d3054d0b569d95.
