### ISSUE TITLE
Blank screen when running via vs code

### ISSUE THREAD

**Issue by swuphoto** [Dart-Code/Dart-Code#813]
I am new to Flutter/DartCode, and I see similar issues reported but closed.  My environment works fine last week when I set it up.  Today I capture the log, hope to find a solution.

[flutterdaemon.txt](https://github.com/Dart-Code/Dart-Code/files/1921672/flutterdaemon.txt)

**Comment by DanTup** [comment]
@swuphoto The log you attached is an analysis server log, is it possible you could reproduce with a `flutter run` log and `Observatory` log? Info on these is here:

- [Flutter Run Logging](https://dartcode.org/docs/logging/#flutter-run)
- [Observatory (Debugger) Logging](https://dartcode.org/docs/logging/#observatory)

**Comment by swuphoto** [comment]
Hi - I rebooted my mac and the problem is gone.  I think that's probably why others also can't reproduce it. 

My mac has not been rebooted for a long time and it's network switched between Corporate WIFI and hotspot every day, I suspect this symptom is related to netowork although I don't have any proof.  If it happened again I will report here.  thanks!

**Comment by DanTup** [comment]
Ok, please do - it keeps coming so I'd love to fix it!
