### ISSUE TITLE
Review process interaction with debug window

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#82]
Current implementation has `stdout` go to the debug window (there's no visible process window). This differs to what a cli app in Visual Studio would do and surprised me.

We should review some other plugins and see what they do; if this is normal in Code then we should follow.

@devoncarew What happens currently if you read from `stdin`?

**Comment by devoncarew** [comment]
> what happens currently if you read from stdin?

I don't know, but can investigate -

**Comment by DanTup** [comment]
Some testing below. I could only find three Microsoft-provided extensions for languages and one was `C/C++` which I skipped because I'm a noob.

### C# (.NET Core)

Embeds in the debug window but appears to:

- Hang on `Console.ReadLine` (typing into the debug window always behaves like a REPL, so you can't provide any input to `ReadLine`!!)
- Exception thrown on `Console.ReadKey`: `'System.InvalidOperationException' in System.Console.dll`

### PowerShell

Also embeds in debug window and `Read-Host` works! The input box works as a REPL when the process is suspended/at a breakpoint but otherwise gets written to STDIN. However, reading a single key does not work (though that's done a bit weird in PoSh - `$Host.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown')`). `Write-Progress` doesn't fail, but doesn't show progress (the host doesn't support it, but it doesn't crash because it's a nice wrapper that already handles the host support, unlike the `Host.UI.RawUI` above).

### Conclusion

I'm not really sure what the conclusion is. The C# behaviour appears to be totally poor. PoSh is slightly better. Neither seem ideal (in that they stop things you would expect to work from working; like "press any key to continue"), but neither work the way I expected/wanted :(

Not sure where to go now :'(

**Comment by DanTup** [comment]
I've raised https://github.com/Microsoft/vscode/issues/10514 to see if MS can give any details on expected behaviour.

**Comment by DanTup** [comment]
I had a quick test of this with current code:

```
import "dart:io";

main() {
  print("What is your name?");
  var name  = stdin.readLineSync();
  print("Hello $name!");
}
```

It just hangs on the `readLineSync()`. If you type into the debug window and press enter, nothing at all happens, but when you terminate then you'll see it appear in the debug window with `not available` message :frowning:

**Comment by devoncarew** [comment]
Thanks for surveying the other plugins! The net-net sounds like:

- plugins use the debug window for console launches
- stdin is not supported? Or, supported when the process is running, and multiplexed to a REPL at a breakpoint?

**Comment by DanTup** [comment]
That seems to be what's out there, but it seems really crazy to me that running your program from an IDE stops you being able to use functionality (for example, .NET has a `Console.ReadLine` and a `Console.ReadKey` and they just don't work?).

Not sure how to progress; shipping with broken stdin support seems poor (even if MS did it!). Maybe see if we get a response to that case in the next day or two to see whether we're missing something, or if they might at least give us an idea of where they think we should go.

**Comment by DanTup** [comment]
@devoncarew Response here: https://github.com/Microsoft/vscode/issues/10514#issuecomment-239763495

What do you think? I think no support for stdin is bad, but I don't know how complicated it is to support (on Windows I guess we can just call `cmd.exe` and pass the details, but I've no idea about Linux/Mac OS; is there a way to launch a command in the users shell (I guess they don't have a standard one!))

**Comment by devoncarew** [comment]
Personally, I'm fine w/ not supporting stdin for a while; few apps I've written actually need it. It sounds like VSCode will eventually support launching into their built-in terminal, and that running there will support stdin.

**Comment by DanTup** [comment]
My concern is that the user experience is  abit crap... you write some Dart you expect to work and it just seems to hang and there's nothing to help you understand why :(

That said; we're still pre-v1, we can call it out in the release notes, and it looks like MS are going to start work on this *this month* which makes me feel better :)

**Comment by DanTup** [comment]
Ok; considering this resolved. We'll ship as-is and hope MS might add their integration soon.

A decision on this was the main thing holding off a 0.8 release, so once I've been through the other issues and PRs in that milestone I'll push a build (if rename doesn't seem ready, I'll bump it to 0.9).
