### ISSUE TITLE
Manually added sub-projects don't run flutter on F5

### ISSUE THREAD

**Issue by xster** [Dart-Code/Dart-Code#822]
To repro:
- Open the whole Flutter repo
- Manually select Add Folder to Workspace...
- Select a Flutter package like examples/flutter_gallery
- Open a file in flutter_gallery
- Press F5
- Dart-Code seems to be attempting to run dart instead of flutter

**Comment by xster** [comment]
Ya that was totally it. Works perfectly now. Don't really know how those launch.json keeps getting recreated. 

Thanks!

**Comment by DanTup** [comment]
It used to be that when you hit F5 it'd create one, but that generally shouldn't happen now (it will if you're not in a Flutter project, but hopefully we're not mis-categorising them).

I'll close this for now, but if you continue to see it and think something isn't right, shout!
