### ISSUE TITLE
Named constructors do not appear in completion list when not using new/const keyword

### ISSUE THREAD

**Issue by bramvbilsen** [Dart-Code/Dart-Code#823]
When using the Dart 2 preview in VS Code, there are no auto fill options named constructors.
For example trying to auto fill
```
new ListView.
```
presents me with all the named constructors for this class.
Using 
```
ListView.
```
does not present any auto fill options.

I'm using Dart Code: 2.11.2.
And Dart version: Dart 2.0.0-dev.48.0.flutter-fe606f890b

**Comment by DanTup** [comment]
This is likely an analyzer issue, could you raise at [dart-lang/sdk](https://github.com/dart-lang/sdk)?

**Comment by bramvbilsen** [comment]
Will do!

**Comment by DanTup** [comment]
SDK case: https://github.com/dart-lang/sdk/issues/32947
