### ISSUE TITLE
`dart.previewExperimentalWindowsDriveLetterHandling` option breaks error reporting

### ISSUE THREAD

**Issue by jakemac53** [Dart-Code/Dart-Code#824]
This option does fix issues with files not under lib not getting updated analysis results from package imports, but it causes a separate issue where problems in the file are not reported in the "problems" pane, and you don't get red squiggly lines either. You do however get the fix it hints/dialogs with the lightbulb icon still next to any errors.

**Comment by DanTup** [comment]
@jakemac53 I can't repro this, when I enable the setting the unexpected errors disappear, but I do still get the expected errors:

![no repro](https://user-images.githubusercontent.com/1078012/39114051-8868e3b6-46d5-11e8-8676-08468fb1bee4.png)

Could you try [enabling the analysis server logging](https://dartcode.org/docs/logging/#analyzer) and repro the issue and send a log? (you can email to logs@dartcode.org if you don't want to post here).

Note: currently when you change that setting, you currently to reload, but in the next build it'll automatically restart the analysis for you.

**Comment by jakemac53** [comment]
Oh - I don't think I actually reloaded VsCode so that would do it.... lol. Since other things like autocomplete started working when I added the line I assumed the setting had switched properly? I can check tonight when I get home.

**Comment by DanTup** [comment]
Aha; if you didn't restart then some things would've had the old (lowercase) drive letter and some things would get new (we read the config value live, don't cache at startup).

I'll keep this open for now, but let me know if a restart fixes it. In the next build, it'll automatically reload silently when you edit this setting.

**Comment by jakemac53** [comment]
Alright I just remoted in really quick and confirmed a restart fixes things, thanks!

**Comment by DanTup** [comment]
Excellent! I'm gonna merge this into master then (it'll still be off by default and behind this flag, just more widely available). With the next build, you won't (*shouldn't*) need to restart after changing it.
