### ISSUE TITLE
Move Organize Directives to Source Code Action (Requires Code v1.23)

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#836]
Microsoft/vscode#47621
Microsoft/vscode#47702

- [ ] Remove `Dart: Organize Directives` info from website

**Comment by DanTup** [comment]
@devoncarew How do you feel about us renaming "Organize Directives" to "Organize Imports"? Code is gaining knowledge of a consistent "organise imports" action so it works the same across languages (rather than us all implementing our own commands).

Based on https://github.com/Microsoft/vscode/pull/47702#issuecomment-384103096 it's going to show as `Organize Imports` in the command palette even if we call it something different in the Source context menu. I think it'll be confusing to users if the name in the context menu isn't found in the command palette, so I'm wondering whether just calling it `Organize Imports` everywhere would be better (we're lucky that Dart uses the word `import`, C# uses `using` so I think it's going to be wonky there whatever).

**Comment by devoncarew** [comment]
Yeah, 'Organize Imports' sounds good to me - sounds like it'll align with VS Code UI better, and probably be a bit easier for users to understand, in terms of the term 'imports' vs 'directives'.
