### ISSUE TITLE
Show Workspace Symbols should show symbols from dependencies

### ISSUE THREAD

**Issue by a14n** [Dart-Code/Dart-Code#840]
_Dart Code 2.11.2_ and _dart-2.0.0-dev.47.0_

I'd like to be able to navigate to a given symbol that exists in a dependency (even a package private one). Today I only see symbols from my project. 

I'd like to use that to discover classes from dependencies and to navigate to elements that are pointed out by a stacktrace.

**Comment by DanTup** [comment]
This will require analyzer support. There's an open case about it at https://github.com/dart-lang/sdk/issues/32446, feel free to add comments/support :-)

**Comment by DanTup** [comment]
This was fixed in the SDK https://github.com/dart-lang/sdk/issues/32446.

**Comment by a14n** [comment]
Awesome! Thanks
