### ISSUE TITLE
[macos] Command "flutter doctor" does not give the same output as integrated terminal

### ISSUE THREAD

**Issue by TheSirC** [Dart-Code/Dart-Code#852]
Hello !

I would like to thank you for your amazing work and dedication to provide this wonderful tool !

I have a strange bug which is that when I run the command `flutter doctor` via the plugin I do not get the same output as the integrated terminal. Both outputs are given below. On _both_ instances both the iOS simulator and the Android emulator are open.
Moreover, when press <kbd>F5</kbd> , or invoke Debug>Start Debugging with both the Android emulator and the iOS simulator only the iOS build is done. 

I am pretty sure that solving the first problem will solve the second.

<details>
<summary>(integrated or not) Terminal output</summary>
<p>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.3.1, on Mac OS X 10.13.4 17E199, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
[✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.22.2)
[✓] Connected devices (2 available)
```

</p>
</details>

<details>
<summary>Command via plugin output</summary>
<p> 

```
[flutter] flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.3.1, on Mac OS X 10.13.4 17E199, locale fr-FR)
[✗] Android toolchain - develop for Android devices
    ✗ ANDROID_HOME = /usr/local/share/android-sdk
      but Android SDK not found at this location.
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
[✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.22.2)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.
exit code 0
```
</p>
</details>

**Comment by DanTup** [comment]
Thanks! :)

Can you run `flutter doctor -v` in the built-in terminal and post the full output?

My guess is that you have something in your shell profile scripts which are applying to the built-in terminal that are not applying to when we run `flutter doctor` from the plugin.

> Moreover, when press F5 , or invoke Debug>Start Debugging with both the Android emulator and the iOS simulator only the iOS build is done.

Currently we only support running on one device, which you can select in the bottom right corner (in the status bar). If all is working well when you click on the device listed there, it'll give you a pick-list of all detect devices. We have #622 about supporting running on multiple devices together, but it's not done yet (though we were discussing it just yesterday, trying to decide the most appropriate place to implement it).

**Comment by TheSirC** [comment]
Sure ! Thanks for taking the time to answer me !
Here is the output :
```
[✓] Flutter (Channel beta, v0.3.1, on Mac OS X 10.13.4 17E199, locale fr-FR)
    • Flutter version 0.3.1 at /Users/sirc/flutter
    • Framework revision 12bbaba9ae (8 days ago), 2018-04-19 23:36:15 -0700
    • Engine revision 09d05a3891
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/sirc/Library/Android/sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/sirc/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.22.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.12.0

[✓] Connected devices (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 8.1.0 (API 27) (emulator)
    • iPhone X                  • 13BD1E89-B789-49BC-A925-7DD3CB04FCDE • ios         • iOS 11.3 (simulator)

• No issues found!
```


> Currently we only support running on one device, which you can select in the bottom right corner (in the status bar).

Okay at least I do not have to take care of that now 😄

**Comment by DanTup** [comment]
Ok, so in the terminal you have this:

```
ANDROID_HOME = /Users/sirc/Library/Android/sdk/
```

Yet when Dart Code runs `flutter doctor` it has this:

```
✗ ANDROID_HOME = /usr/local/share/android-sdk
```

So the issue is likely that your `ANDROID_HOME` environment variable is wrong at the system level but then fixed in your terminal startup scripts, so it works in terminals but is wrong outside of them (eg. for Code).

I guess you should be able to fix it by running `launchctl setenv ANDROID_HOME /Users/sirc/Library/Android/sdk` which should set the variable in a way that'll work for Dart Code (maybe if you run `launchctl getenv ANDROID_HOME` first, it'll show the wrong value?).

**Comment by TheSirC** [comment]
Interestingly launching `launchctl getenv ANDROID_HOME` sended back nothing 🤔 
But by curiosity I still executed `launchctl setenv ANDROID_HOME /Users/sirc/Library/Android/sdk`, closed Visual Studio Code and relaunched it and the "bug" is still here...

**Comment by DanTup** [comment]
So when you run the `Flutter Doctor` command from VS Code now, what does it show `ANDROID_HOME` as? It's possible you'll need to restart for it to apply properly, I'm not sure. If it still shows `/usr/local/share/android-sdk` then this must be being set somewhere else; but I'm not familiar with all the places you can set env vars on macOS :(

**Comment by DanTup** [comment]
@TheSirC Maybe worth trying `flutter clean` and/or deleting the `build` directory in case the path was cached anywhere in there (I'm not very familiar with the build process though; it's a bit of a stab in the dark).

**Comment by TheSirC** [comment]
Thanks for the suggestion!
