### ISSUE TITLE
Support vmAdditionalArgs in launch.json configuration

### ISSUE THREAD

**Issue by algor** [Dart-Code/Dart-Code#857]
First of all, thanks a lot for the great plugin!
Is there a chance to add vm arguments parameters specific for a launch configuration cause the arguments probably belong to the launch configuration anyway? It would be very useful, for example, in order to specify packages resolution file with using --packages=<path>. In its current state it has a limited application due to variance of the vm arguments per a launch configuration.
Also, the two other useful parameters for the launch configuration would be:
'env' parameter to specify environment variables to be set for the spawned process (like the one for C/C++ plugin).
'launcher' parameter to specify executable to be used to "wrap" dart vm for the launch (like vglrun https://wiki.archlinux.org/index.php/VirtualGL) so that the application could be launched like:
 vglrun dart <vm args> <app args> 
I know I am asking a lot. If you believe such changes make sense I would be glad to create a pull request for them. Thanks!

**Comment by DanTup** [comment]
@algor they should actually work in the `launch.json` but for some reason they are named `vmArgs` (they also do not appear in completion/validation)!

Let me know if this works, and I'll use this case for documenting them and ensuring they appear in completion.

**Comment by DanTup** [comment]
In next major version this will appear in the completion for `launch.json` and be called `vmAdditionalArgs`. For now, you can call it `vmArgs` and it'll work (though that'll break when you upgrade, you'll need to rename).

**Comment by algor** [comment]
vmArgs arguments work. Thanks!
Do you think the other too parameters I am asking about in the initial comment make sense?
"env" - environment variables set for the spawned process environment
"launcher" - wrapper around dart executable which actually starts dart vm with the given arguments (use case - vglrun)?
Thanks again!

**Comment by DanTup** [comment]
@algor Whoops, I guess I didn't read the email properly! =)

Supporting `env` is definitely very reasonable; the other one I think depends on how complex the solution is (it doesn't seem like it'd be complicated, but we have some open issues about leaving processes around because of spawning shell scripts that don't pass on kill signals correctly). If you raise two separate issues for them we can discuss them there :-)

**Comment by algor** [comment]
Will do. Thanks!
