### ISSUE TITLE
Factories don't autocomplete with Dart 2

### ISSUE THREAD

**Issue by xster** [Dart-Code/Dart-Code#869]
Consider

```dart 
class A {
  A.b() { blah }
}
```

`new A.` shows an autocomplet with .b but just `A` dart 2 style doesn't bring up any autocompletes with the factory.

**Comment by DanTup** [comment]
I think this is same as #823 / https://github.com/dart-lang/sdk/issues/32947. From the comment on the SDK case, this might be deliberate.
