### ISSUE TITLE
Add pub test runner/debugger [Preview]

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#87]

**Comment by DanTup** [comment]
I added this in the same way that `pub get`/`pub upgrade` work, though not particularly happy that this will appear for all projects. Then I discovered that Code has a `Run Test Task` command already which seems like a much better fit (we could even have a one that runs in watch mode, like TS has for builds)... But, it's not clear how to use it... Raised https://github.com/Microsoft/vscode/issues/10742

**Comment by pulyaevskiy** [comment]
Just curious if this still requires external change?
I see in mentioned issue there seems to be a solution now?

**Comment by DanTup** [comment]
Which solution are you referring to? MS are working on improving the task runner system (see https://github.com/Microsoft/vscode/issues/15179) which I believe they're hoping to finish this month. I still don't know how well it'll support tests (no comments on https://github.com/Microsoft/vscode/issues/10742 for a while) but I guess we'll find out when all the docs/API is available.

**Comment by Rasarts** [comment]
Very simple to use outline for test like that extention: https://marketplace.visualstudio.com/items?itemName=RomanPeshkov.go-test-outline
![giphy](https://user-images.githubusercontent.com/910917/28134203-ed8b5e6a-674a-11e7-8a2a-bf98c30b9036.gif)

**Comment by DanTup** [comment]
Cool; looks like we've got what is needed to do a reasonable job here. Not sure if we could show a list without executing them though (or easily let you run a single test) because of how tests work in Dart, but I'll take a look when I find some time!

**Comment by DanTup** [comment]
Sadly it seems like VS Code isn't getting any test APIs in 2018, so we're definitely on our own.

https://github.com/Microsoft/vscode/issues/9505#issuecomment-364868707

**Comment by DanTup** [comment]
FWIW, I've been using this as my `launch.json` while hacking on the analysis server lately:

```js
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Analysis server tests",
			"program": "${file}",
			"request": "launch",
			"type": "dart"
		}
	]
}
```

Setting `program` to `${file}` means it will run the current file in the editor when I hit `F5`. It's not perfect because I often jump into implementation code and then hit `F5` and it fails (no main method) but it's better than manually running from the terminal each time. There's a case with some related discussion at #538.

(cc @rrousselGit)

**Comment by rrousselGit** [comment]
I'm personally not a huge fan of how `vscode go` handles tests.

I prefer much more [`jest vscode`](https://github.com/jest-community/vscode-jest/)'s approach 

![image](https://github.com/jest-community/vscode-jest/raw/master/images/vscode-jest.gif)

Basically it runs tests in background on every changes. And add a `problem` on vscode pointing to the failing test with some explanations on what's happening. 


Ideally we should be able to output test coverages at the same time. But may be tricky https://github.com/dart-lang/test/issues/36

**Comment by rrousselGit** [comment]
But the question in the end is : 
How would we implement compatibility between angular, flutter, and simple dart ?

Because they all have different command line to run tests.
Especially angular which depending on it's version have different commands.

**Comment by DanTup** [comment]
@rrousselGit You can add multiple configurations into `launch.json` and switch between them with a dropdown on the debug sidebar. Note: I'm not saying this is the solution (or even a good one), but it might be useful between now and us implementing something good :-)

**Comment by rrousselGit** [comment]
@DanTup yeah I know, that's what I currently do. 

In fact, I have a `test/all_tests.dart` and run in my terminal `watch "pub run test test/all_tests.dart " lib test` as I explained [here](https://stackoverflow.com/questions/49004259/hot-reload-during-unit-testing).


But my comment here was definitely about the `us implementing something good :-)`

**Comment by DanTup** [comment]
@rrousselGit I somehow missed your earlier comment about `jest`. That looks really good and is somewhat what I hope #499 will achieve (VS Code supports "problem matches" that parse the output of commands and create diagnostics).

It doesn't address being able to see a list of your tests (though in Dart this is a bit woolly anyway, since I don't think they're really declared) but it's definitely a great start.

**Comment by rrousselGit** [comment]
No problem ~ 😃  

But like I hinted above in my 
> How would we implement compatibility between angular, flutter, and simple dart ?
Because they all have different command line to run tests.
Especially angular which depending on it's version have different commands.

Using the commands to run tests is a thing. But how should we handle all dart frameworks simultaneously ?

In fact, is testing really in the scope of `Dart Code` to begin with ? Shouldn't we have another extension that works specifically for one and only one command line ?

So in the end 3 extensions for 3 cases :

- `flutter test`
- `pub run angular-test`
- `pub test`

**Comment by DanTup** [comment]
@rrousselGit I don't really understand. You can have multiple configs in `launch.json` and multiple tasks in `tasks.json`. Them being different commands shouldn't make any difference?

> In fact, is testing really in the scope of `Dart Code` to begin with ?

In my opinion, it is. The purpose of Dart Code is to provide you with the tools you need to write Dart code productively. If testing isn't easy/possible then people are less likely to do it, and I think encouraging tests is important :)

> Shouldn't we have another extension that works specifically for one and only one command line ?

I don't think things should be split into extensions just because they have different cli entry points. Dart Code already uses `pub`, `flutter` and `dart`. I think it makes sense for Dart Code to support testing for the things it supports debugging. Whether Dart Code should actually be split up (eg. a separate Flutter extension) is an open topic we need to think more about and have #508 open for.

**Comment by rrousselGit** [comment]
> I don't really understand. You can have multiple configs in launch.json and multiple tasks in tasks.json. Them being different commands shouldn't make any difference?

But what would your `launch.json` looks like then ?

Because currently to run the project, we have strictly the same command on both cli and flutter. With angular not being implemented.
We'd most likely have Dart Code run the command by itself with custom arguments for debug purpose.


My biggest concern is that we want Dart Code to work with Angular too.
But with the coming v5, Angular commands will change.
Do we really want to test angular version to know which command should we run ?

**Comment by DanTup** [comment]
> But what would your `launch.json` looks like then ?

It's hard to answer this since we don't actually have support for non-CLI tests. In my example above you can copy/paste the `Analysis server tests` object and tweak it and put in other paths, and you can create composite launch configs to launch many at the same time.

However, I think tasks might be a better fit for it, so they'd be declared in `tasks.json`. I don't know the specifics because I haven't dug into it yet, but `tasks.json` basically lets you just put in a bunch of commands/args and run them from the command palette/keybindings (inc. setting them up in `watch` mode if appropriate).

> Because currently to run the project, we have strictly the same command on both cli and flutter. With angular not being implemented.

I think that flutter testing has its own command `flutter test` but I haven't used it so don't know a lot about it yet.

> My biggest concern is that we want Dart Code to work with Angular too.
> But with the coming v5, Angular commands will change.
> Do we really want to test angular version to know which command should we run ?

I don't know how the integration with Angular will work yet (it's some way off) but checking versions is not a problem, we already have to do this for many things - Dart Code doesn't include an SDK and all of the analysis services are powered by a server shipped inside the SDK, so we need to behave differently depending on the capabilities of the server.

That said, hopefully we'll have reasonable abstractions/APIs to protect editor integrations from too much of the changing implementation.

There are definitely a lot of questions around how this will work and it needs some thought that I haven't been able to give it so far, but I hope it's not too far away - it is moving its way up my list :-)

**Comment by DanTup** [comment]
VS Code now has a standard "Test" side bar, so tests can be rendered outside of the Explorer one:

<img src="https://user-images.githubusercontent.com/10746682/39261226-2455ccac-48bc-11e8-8235-09e1f49561c5.png" />

It's not a nice test API, but it's at least something more consistent for extensions to target, so it might be worth revisiting this soon.

**Comment by DanTup** [comment]
Splitting Dart/Flutter here because there are some complications with getting the non-Flutter ones working. Flutter will be done first, as #980.

**Comment by DanTup** [comment]
@grouma @jakemac53 Trying to wire this up but I don't think `--pause-after-load` is doing what I want. For all our other debuggers (Dart VM execution, Flutter Run and Flutter Test) the isolates start paused and we unpause them after sending breakpoints etc. using the VM service API. It seems like using `pub run test` this isn't the case; and that the isolate is not paused - I'm guessing it wants us to unpause at the start of each suite using the JSON command.

This makes it more difficult to just reuse all our existing debugger code (the logic for unpausing is complicated, because we normally wait for several async things to happen). Is there any way to make this work the same as `flutter test`?

**Comment by DanTup** [comment]
Hmmm, going back to `--pause_isolates_on_start=true --enable-vm-service=0` behaves exactly as I want. I think I'll do this for now and maybe tackle changing how this works later (such as when there's web support). The debug adapters need a lot of refactoring that'll make this easier, but I don't want to start on that until I can run all my debugger tests reliably (many are blocked on Flutter issues right now).

**Comment by DanTup** [comment]
Shipping in v2.15 as a preview. You need to set `config.previewTestRunnerForDart: true` to use this. It will only be used when there's a `pubspec.yaml` and a `.packages` file in your project (this is to avoid trying to `pub run test` for repos like the SDK where it isn't supported).

I plan to enable this by default in the following version so please try it out.

Note: The test runner is also shipping for Flutter in v2.15 and this is *not* behind a flag, it's enabled for all.
