### ISSUE TITLE
Include `PUB_ENVIRONMENT` when invoking pub command

### ISSUE THREAD

**Issue by kevmoo** [Dart-Code/Dart-Code#877]
https://github.com/Dart-Code/Dart-Code/blob/5b97e7a66251917d121f3cde591f737b0248a602/src/commands/sdk.ts#L142

When invoking pub, please set the `PUB_ENVIRONMENT` environment variable to `vscode.dart-code`.

This helps us track how pub is being invoked.

See an example here: https://github.com/dart-lang/sdk/blob/332dc7f3e90babd370fe4342603f5d74d8518a23/pkg/analysis_server/lib/src/plugin/plugin_manager.dart#L846-L861

A couple of notes:

- [ ] If `PUB_ENVIRONMENT` is already set, please amend your value w/ a `:`. So `existing.value:vscode.dart-code`

- [ ] When running tests, pass in a environment variable so we can know any hits to the pub site or via a test. Our convention is to use `bot` in the value. So for you `dart-code.test.bot`

Yes, I'd love the same model for invoking pub via flutter – so any call to `flutter packages`. I'll file a separate bug at https://github.com/Dart-Code/Flutter

**Comment by DanTup** [comment]
Makes sense; we already do something similar for flutter commands (`FLUTTER_HOST = "VSCode";`).

For tests; I presume you mean Dart Code's tests running on Travis/AppVeyor and not the end users tests in the IDE?
