### ISSUE TITLE
Support for `dartfmt`?

### ISSUE THREAD

**Issue by seenickcode** [Dart-Code/Dart-Code#878]
Hello, does this extension support `dartfmt`?  I ask because if I run `dartfmt` alone it gives me different output than simply saving a .dart file with this extension installed. Thanks.

**Comment by DanTup** [comment]
Saving in the extension essentially does the same thing (the analysis
server - which uses the same code as dartfmt - provides the edits for us to
apply in the editor).

My guess would be that there's a difference in versions or something. Can
you provide an example of the difference in formatting as well as confirm
the versions - the one the extension is using is shown in the status bar
and "dart --version" on the terminal you're running dartfmt from should
give that version.

**Comment by seenickcode** [comment]
@DanTup thanks again for the quick reply.

Here's my code file. Note the deliberate overly indented Map values:
```
import 'dart:core';

class CalColor {
  String name;
  String hex;

  Map foobar = {
          'hi': 'there',
          'we': 'care',
          'over': 'there',
        };
}
```
I save the file and nothing happens.

Here's the output of `dartfmt`:

```
dartfmt --version
1.0.10
```

```
➜  dartfmt lib/models/cal_color.dart
import 'dart:core';

class CalColor {
  String name;
  String hex;

  Map foobar = {
    'hi': 'there',
    'we': 'care',
    'over': 'there',
  };
}
```

**Comment by seenickcode** [comment]
...another example:

Code:
```
import 'dart:core';

class CalColor {
  String name;
  String hex;

  Map foobar = {
          'hi': 'there'
        };
}
```
Output:
```
dartfmt lib/models/cal_color.dart
import 'dart:core';

class CalColor {
  String name;
  String hex;

  Map foobar = {'hi': 'there'};
}
```

**Comment by DanTup** [comment]
If I paste your first sample in to a file and hit save, it gets formatted (the extra indents disappear).

Have you enabled `editor.formatOnSave`? I can't remember if it's on by default, but worth checking your settings.

If you open dev tools (Help -> Toggle Dev Tools) and repro, are there any errors/warnings written?

If none of those help, can you try enabling the analysis server logging and attach or email the file to me? https://dartcode.org/docs/logging/#analyzer

**Comment by seenickcode** [comment]
Ugh I'm such an idiot - didn't even think of trying that setting.  

It works now with `editor.formatOnSave`. 

Thanks for helping with an awesome IDE for Flutter.

**Comment by DanTup** [comment]
No worries; maybe it's not obvious enough :)

I've started a "Recommended Settings" page for [the website](https://dartcode.org/) because there are a couple of things in VS Code that I think are bad defaults (but I don't wanna just force them on people in the extension!). Hopefully can finish it soon :-)

**Comment by seenickcode** [comment]
Awesome sounds good.

**Comment by seenickcode** [comment]
Sounds good. That'd be nice actually.
