### ISSUE TITLE
Debugging single .dart file?

### ISSUE THREAD

**Issue by seenickcode** [Dart-Code/Dart-Code#881]
Hello,

I'd like to debug a single dart test that I have in a Flutter project via the `dart:developer`'s `debugger()` function. While I can run it fine via the command line (like so `flutter test --start-paused test/example_test.dart`), I'd like to get it to work right from the VSCode IDE via `launch.json` configuration like so:

```
        {
            "name": "Flutter tests",
            "request": "launch",
            "type":"dart",
            "program": "/usr/local/flutter/bin/flutter",
            "args": ["--start-paused", "${workspaceFolder}/test/example_test.dart"],
            "internalConsoleOptions":"openOnSessionStart"
        },
```
When I run the debugger with this configuration, I see the error: 

```
No connected devices.
Exited (1)
```

Any ideas?

**Comment by DanTup** [comment]
I'm not sure why it'd give you this message, but having the flutter binary in the `program` field isn't correct; it should be your Dart script. You shouldn't need to manually configure things like `--start-paused`, it's all handled for you by Dart Code.

My recommendation would just be to delete your `launch.json`, open your `test/example_test.dart` file in the editor and press `F5` and it should do exactly what you want.

If for some reason you do need a `launch.json` to customise something, you should only need something like this:

```js
        {
            "name": "Flutter tests",
            "request": "launch",
            "type":"dart",
            "program": "${workspaceFolder}/test/example_test.dart"
        },
```

In vNext, you won't need the `${workspaceFolder}` prefix, as I've fixed relative paths to work correctly.

**Comment by seenickcode** [comment]
Hi @DanTup , thank you for the reply.  

F5 indeed works.

Using the custom `launch.json` example you gave above didn't seem to catch any breakpoints after running that configuration directly, but I'm happy with the F5 route.

Thank you.

**Comment by DanTup** [comment]
Having a `launch.json` like the above should work too. Could you reproduce it and send me [Flutter Run](https://dartcode.org/docs/logging/#flutter-run) and [Observatory] logs to take a look? (FWIW, pressing F5 when you have a `launch.json` just runs the selected (on the Debug sidebar) launch config from it. Only when you don't have a `launch.json` will F5 do something different (which is basically just pick some sane defaults).

**Comment by seenickcode** [comment]
Hey there Danny, I basically just use F5 now and everything works
perfectly. Thanks!
