### ISSUE TITLE
Debugger should show complex keys in maps in variables/watch

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#882]
Splitting from #879; when a map's key is a complex object, we only show it's string representation in the name field. It should be possible to expand the key and examine its properties like the value.

**Comment by tfriem** [comment]
I would give it a try today and report back if I have any problems with it.

**Comment by DanTup** [comment]
Ok cool; feel free to [shout me in Gitter](https://gitter.im/dart-code/Dart-Code) if you get stuck and need help.

**Comment by tfriem** [comment]
I got a first version running:

![map](https://user-images.githubusercontent.com/4568372/39727283-624af5ba-5252-11e8-9804-dd97a27979a1.PNG)

Still needs a bit polishing (mainly error handling and tests). I plan to finish it by end of the week.

**Comment by DanTup** [comment]
Excellent! 😄

**Comment by DanTup** [comment]
Fixed in #892.
