### ISSUE TITLE
Add quick-fixes to insert lint-ignore comments

### ISSUE THREAD

**Issue by csga5000** [Dart-Code/Dart-Code#890]
IN some cases users want to ignore warnings (For example a function used only in testing that isn't called).  

You can do so using:
```
//ignore: unused_element
void _testingOnlyFunc() {}
```

But if you don't already know what "key" to ignore, you have to use flutter analyze to see what the key is. 

Can we make either the "Problems" tab specify that key, or add a right click in problems or option in the show fixes light-bulb to choose "suppress warning" which adds the //ignore for you?

I think users of the dart code plugin would benefit from any way to ignore without having to use the command line if they're trying to ignore some obscure warning they don't know the "key" for.  I'm not oppinionated how that's done.

**Comment by DanTup** [comment]
There's a setting named `dart.showLintNames` that you can set to get these in the error message:

<img width="618" alt="screen shot 2018-05-10 at 7 44 54 am" src="https://user-images.githubusercontent.com/1078012/39855993-217bd6b4-5426-11e8-8a40-94728f574b29.png">

That said, having a quick-fix to ignore doesn't seem like a bad idea - tslint has something similar:

<img width="444" alt="screen shot 2018-05-10 at 7 42 01 am" src="https://user-images.githubusercontent.com/1078012/39855902-a7f22f50-5425-11e8-92cc-da04917c3636.png">

So, I'm taking this case as a request for the UI, but hopefully the above setting will help you in the meantime.

**Comment by csga5000** [comment]
Ah, I didn't know about that option.  Sounds good

**Comment by csga5000** [comment]
Just shout out to you Dan, I like to make issues when something takes more time for me to work out than I think it should and I think there's an easy way to improve tooling (unless it's just plane me being dumb) cause I figure it'll save all the developers time.  In this case I was trying to google the lint names and figure out that lint name and I checked for a "fix it" suppression thing like I would see in intellij or eclipse, without knowing flutter analyze would display the key.  Then I eventually thought to try it, but if vscode had a fixit or displayed keys it would have saved me time (and hopefully others).  It's a pretty small thing, and many of my requests are little things, but you always do an awesome job of thoughtfully following up.  Great work man.

**Comment by DanTup** [comment]
Thanks! The little things matter to me, so do keep raising them :-)

It seems like maybe this one might be fixed in the server, so it'll just show up in future without Dart Code needing any work. If it seems like they won't make it into the server, I'll consider putting something in directly.
