### ISSUE TITLE
Extend attach-to-process to support Flutter functionality

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#905]
Currently attach-to-process doesn't support all Flutter functionality (since it uses the Dart debugger, not the Flutter one; and we have no `flutter run --machine` process to talk to); we should figure out what it'd take to address this.

**Comment by DanTup** [comment]
@devoncarew There's a bunch of things we have in the Flutter debugger that currently rely on having launched via `flutter run`, such as:

- Getting devices paths for mapping breakpoints etc. (you said this might be going away?)
- Hot reload (inc. getting feedback for them)
- Hot Restart
- Debugging commands (change platform, toggle debug painting, etc.)

I'm not sure whether it's possible to route these through Observatory (if so, we could merge the Dart + Flutter debug adapters, and support all Flutter functionality when attaching).

Is it possible? If not, should it be? How useful is this?

**Comment by DanTup** [comment]
> in dart 2 the paths we get are the paths were the sources were compiled (on the host machine)

Is this true for everything (breakpoints we send, locations when the VM breaks; locations in stacks, including after hot reloads)? If so, I can delete some nasty code and it'll simplify the breakpoint issues I'm trying to fix too :-)

> The app would have to have been run from flutter_tools. flutter_tools then advertises the service to the service protocol

Where can we find info on the protocol for this? (even if it's source code)? Is there anything else already using it that can be looked at?

**Comment by devoncarew** [comment]
> Is this true for everything (breakpoints we send, locations when the VM breaks; locations in stacks, including after hot reloads)? If so, I can delete some nasty code and it'll simplify the breakpoint issues I'm trying to fix too :-)

Yes, I believe so, but we should write some end-to-end tests (flutter_tester integration tests, and iOS+Android device lab integration tests) before we delete the other code paths

> Where can we find info on the protocol for this?

Here's where flutter_tools registers the service: https://github.com/flutter/flutter/blob/89cb5d268d2fc939f180dcee29df7a729fd051ef/packages/flutter_tools/lib/src/vmservice.dart#L136

And I _believe_ that you'd then have a `reloadSources` service protocol call available. You can register for notification of new services via the `_Service` event.

**Comment by DanTup** [comment]
@stuartmorgan I don't know if this works for your needs but I've got a basic implementation of `flutter attach` (new flutter command) working at https://github.com/Dart-Code/Dart-Code/issues/1056. If this becomes the way to attach to all types of flutter apps then possibly this issue is superseded by that one.

**Comment by stuartmorgan** [comment]
It looks like `flutter attach` expects connected devices to be available even when given a port, so at first glance I don't think it'll currently work for the desktop use case. I'll have to investigate further.

**Comment by DanTup** [comment]
This case (as described in the title) is addressed by https://github.com/Dart-Code/Dart-Code/pull/1061 which should ship in this weeks release.

As for the desktop case, I don't think we use the device for much more than just watching logs to get the observatory port and forward ports. I think I added a no-op forwarder for flutter-tester recently so making it work might be fairly simple (in fact, maybe using `flutter-tester` as the device ID will just work out of the box?).

How simple is it to get the desktop stuff working on macOS with some sample app?

**Comment by DanTup** [comment]
Ok, had a quick test:

1. Cloned your repo
2. Opened the macOS/example project in Xcode and clicked run
3. Opened VS Code at the flutter_example folder
4. Created a `launch.json` with `flutter-tester` as the device (see below) and the Observatory URI from the Xcode output
5. Pressed F5
6. 🎉

launch.json:
```js
{
	"name": "Flutter",
	"request": "attach",
	"deviceId": "flutter-tester",
	"observatoryUri": "http://127.0.0.1:52919/",
	"type": "dart"
}
```

![screen shot 2018-10-02 at 11 09 16 am](https://user-images.githubusercontent.com/1078012/46342818-ac3b4f80-c633-11e8-9dbc-1cdd284c0bde.png)
![screen shot 2018-10-02 at 11 09 27 am](https://user-images.githubusercontent.com/1078012/46342822-afced680-c633-11e8-8c25-700825d59c50.png)
![screen shot 2018-10-02 at 11 09 34 am](https://user-images.githubusercontent.com/1078012/46342830-b2313080-c633-11e8-9936-5908a6354784.png)

I'm sure there's things we can tidy up (for ex. Flutter configs won't prompt to paste an Observatory URI in, so you need to put it in the launch.json) but I think it's a good start.

**Comment by clarkezone** [comment]
Attempting to try this approach on Linux, I’m getting 

> Property deviceId is not allowed

 when editing the launch.json.

**Comment by stuartmorgan** [comment]
I see that as well on macOS, but it still works. IIRC that just means it's not registered as a supported property in the configuration definition. You should be able to ignore the warning; it'll still be available in the dictionary.

**Comment by DanTup** [comment]
Thanks, I'll fix that for vNext. As Stuart says, it'll still work, but I didn't declare it in the manifest, so the JSON validator/completion doesn't know about it.

**Comment by clarkezone** [comment]
OK I'm working now on Linux and Windows with the limitation that all of the stepping functions appear to not work i.e. step over / step into appear to behave like continue.  Is this known?

**Comment by DanTup** [comment]
@clarkezone Not known to me. Could you open a new issue about it with a log file?

- Run the `Dart: Capture Logs` command
- Select `Flutter Run` and `Debugger (Observatory)` categories
- Launch the app and attach to it
- Reproduce the issue (try stepping, or whatever)
- Click Stop Logging

You could either attach the log to the new issue or email it to me (dantup @ google) including the issue number.

Thanks!
