### ISSUE TITLE
Support global expression evaluation inc. while not paused

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#906]
This was less useful for Dart, but for Flutter it could be useful to interact with an app while it's not paused on a breakpoint.

**Comment by DanTup** [comment]
https://github.com/flutter/flutter/issues/18678#issuecomment-403876847

**Comment by DanTup** [comment]
We need to send a library (or class) for evaluation, and the debug adapter doesn't have one - to do that we'd need to let the debugger ask the editor where the user is - starting to feel messy. Will come back to this..

**Comment by AndreVNP** [comment]
Still not working

![image](https://user-images.githubusercontent.com/39059585/73389610-4efcf000-42b3-11ea-88d8-2d8cd2007544.png)

**Comment by Gowtham-mg** [comment]
@AndreVNP me too facing the same issue..Please post the solution, if you have solved this issue

**Comment by sonah86** [comment]
I have the same problem in Visual Studio Code using Dart.. 
Please Help

**Comment by DanTup** [comment]
This is not currently possible. To evaluate expressions, you'll need to be stopped at a breakpoint for now.

**Comment by judexes** [comment]
Any solution yet?
did anyone solve this?

**Comment by DanTup** [comment]
Next version will partially support this... The global evaluations will always be scoped to the "root library" on the root isolate (this will usually be your `main.dart`). I've opened a separate issue (#2446) for having it scoped to the active file in the editor, but that's a little more tricky (since the debug adapter does not know which file is active in the editor).

![Screenshot 2020-05-12 at 10 09 06](https://user-images.githubusercontent.com/1078012/81665481-a83ef880-9438-11ea-83f2-f1001be5aa07.png)

Hopefully this handles most use cases, though I'm not completely familiar with what everyone is trying to use this for, so feel free to post your requirements here and I'll try to cover those I can.

Thanks!

**Comment by judexes** [comment]
> Next version will partially support this... The global evaluations will always be scoped to the "root library" on the root isolate (this will usually be your `main.dart`). I've opened a separate issue (#2446) for having it scoped to the active file in the editor, but that's a little more tricky (since the debug adapter does not know which file is active in the editor).
> 
> ![Screenshot 2020-05-12 at 10 09 06](https://user-images.githubusercontent.com/1078012/81665481-a83ef880-9438-11ea-83f2-f1001be5aa07.png)
> 
> Hopefully this handles most use cases, though I'm not completely familiar with what everyone is trying to use this for, so feel free to post your requirements here and I'll try to cover those I can.
> 
> Thanks!

Thanks a bunch for looking into this.
is there a beta version with a fix we could support ourselves with while its not yet ready for release?

**Comment by DanTup** [comment]
There's a preview build here:

https://github.com/Dart-Code/Dart-Code/releases/tag/v3.11.0-beta.1

Install by downloading the attached `vsix` file and running the **Extensions: Install from VSIX** command from the VS Code Command Palette to select the vsix file and then reload VS Code.

**Comment by sarthak260** [comment]
It is still not working..
can anyone please help me out to get some solution on this!

![image](https://user-images.githubusercontent.com/34007828/82124815-2f84c700-97bf-11ea-9a4c-3e8cfb05bf16.png)

**Comment by DanTup** [comment]
@sarthak260 you're typing into the evaluation console here. If you want to accept input from the user for your Dart program, you need to configure your launch configuration to run in the terminal .- please see https://dartcode.org/releases/v3-9/#dart-cli-terminal-improvements

**Comment by temizmustafa** [comment]
@DanTup you are right.  In launch.json file, "Console" : "Terminal", it is working.
https://dartcode.org/releases/v3-9/#dart-cli-terminal-improvements

**Comment by Aung-Thiha112** [comment]
but what does I need to put in my main.dart in order to prevent by terminating the output

**Comment by DanTup** [comment]
@Aung-Thiha112 if you're running a standard Dart script, you're likely better just adding a breakpoint. Flutter apps don't quit at the end of running the entry point, so that's where this request mostly came up.

**Comment by Sormox** [comment]
> @sarthak260 you're typing into the evaluation console here. If you want to accept input from the user for your Dart program, you need to configure your launch configuration to run in the terminal .- please see https://dartcode.org/releases/v3-9/#dart-cli-terminal-improvements

I add in launch.json file --> "console" : "terminal" . don't work dart version  3.19.2

**Comment by DanTup** [comment]
@Sormox could you file a new issue, and provide a detailed description of what you mean by it not working? Thanks!

**Comment by Rafieaydin** [comment]
im using dart 3.20.1 "console" : "terminal" dint work and still same erorr why? im using vscode extention

**Comment by DanTup** [comment]
@Rafieaydin it's not clear what what the issue is - the note about using `terminal` is for accepting input from user, not for global evaluation. If you file a new issue with a detailed description of what you're doing/seeing, I'll take a look. Thanks!
