### ISSUE TITLE
Terminating the debug session does not correctly terminate the VM process on Windows

### ISSUE THREAD

**Issue by sepisoad** [Dart-Code/Dart-Code#907]
When trying to debug my Dart sever code I have this nasty problem that after stopping the debugger 
 VSCode would not close open port held by dart VM and leaves the dart process alive, therefore I have to kill dart process manually which is very frustrating.

I wrote some test server code using the frameworks below and they all have this problem:
    Angle
    Jaguar
    Aqueduct
which makes me believe the problem is within VSCode dart plugin

**Comment by DanTup** [comment]
@sepisoad Are you able to provide some sample code? Ideally just a small single Dart script that has the same issue.

**Comment by sepisoad** [comment]
ok take the following code as example.


```dart
import 'dart:io';
import 'package:angel_common/angel_common.dart';

main() async {
  Angel app = new Angel();

  app.get("/", "Hello, world!");

  var server = await app.startServer('0.0.0.0', 8000);
  print("Angel server listening on port ${server.port}");
}
```

1) try launching it via debugger 
2) stop the debugger
3) launch it via debugger one more time and BOOM, you'll get busy port exception

**Comment by DanTup** [comment]
I can't repro this on Dart v1.24.3 or v2.0.0; it launches fine each time (note: I had to put `new InternetAddress()` around the IP). Which version of Dart are you using, and what platform are you on? (and I guess, what version of Angel are you using?).

Also, can you repro with just a built-in Dart listener?

**Comment by sepisoad** [comment]
dart version: 2.0.0-dev.53.0.flutter-e6d7d67f4b (Thu May 3 21:11:44 2018 +0000) on "windows_x64"

**Comment by DanTup** [comment]
What version of Angel are you using?

Can you repro with just a built-in Dart listener?

**Comment by sepisoad** [comment]
Angel CLI version: 1.2.0+5

excuse me, what do you mean by :

> Can you repro with just a built-in Dart listener?

but i can give you this screenshot:

[![err.png](https://s7.postimg.cc/jn29bqbnv/err.png)](https://postimg.cc/image/voxn5vkw7/)

**Comment by sepisoad** [comment]
i'm new to dart, sorry for making unclear comment :(

**Comment by DanTup** [comment]
@sepisoad I was trying to eliminate the possibility of an issue with the Angel framework. There's some sample code here that creates a web server using only Dart:

https://www.dartlang.org/tutorials/dart-vm/httpserver#a-quick-glance-at-the-code

I wondered whether you see the same behaviour using code like that (to eliminate Angel from the issue).

**Comment by sepisoad** [comment]
the issue persists with [the code](https://www.dartlang.org/tutorials/dart-vm/httpserver#a-quick-glance-at-the-code) you mentioned.
As told earlier I tested other frameworks as well and the same problem happened again.
So I guess this is something to do with VSCode dart plugin. maybe the cleaning up is not happening correctly

**Comment by DanTup** [comment]
@sepisoad Thanks for the extra info (apologies, I missed that'd you'd tried with other frameworks). I'll have a go on Windows with the same versions of everything and see if I can repro there (it's a MacBook where I tried and failed previously). Is it Windows 10 you're on?

**Comment by sepisoad** [comment]
nevermind ;)

I'm running Windows 10 Enterprise x64  [10.0.16299 Build 16299]

**Comment by aemino** [comment]
Hello, I'm experiencing this on Windows as well.  I'm using my own code, which starts a WebSocket and essentially listens to events forever until the program is stopped.  However, when clicking the stop button in the debugger, the process isn't actually killed.  Let me know if I can provide any more information!

Dart version: 2.0.0-dev.54.0
Dart Code version: 2.13.0-beta.2 (using `"previewDart2": true`)

**Comment by DanTup** [comment]
Oh, I just noticed this in the Observatory `getVM` response:

```js
"pid":1909
```

I think we could stash this `pid` and terminate that first when quitting, and then terminate the process we have (or even just replace our process reference to this one, and assume the shell will exit cleanly when we kill the VM anyway).

@devoncarew Maybe there's an easier fix for the Flutter issue (https://github.com/flutter/flutter/issues/16183) here too. If we could surface the `pid` of the `flutter run --machine` process immediately, maybe we can get a good kill signal to terminate it that'll work as well as Ctrl+C does from the command line.

I'll see if I can repro this (VM socket) issue on Windows tomorrow. If I can, and doing this fixes it; I may see if I can rig something in `flutter run` to provide the `pid` there and test that too.

**Comment by DanTup** [comment]
Please try v2.13.0 Beta 3 and let me know if this issue is solved or not:

https://github.com/Dart-Code/Dart-Code/releases/tag/v2.13.0-beta.3

**Comment by giohappy** [comment]
@DanTup I still have the reported issue with dart SDK 2.13.4 from flutter 2.2.3 on Windows 10.
In my case I'm binding and listening to a `RawDatagramSocket`. 

I can catch a Ctrl+C (SIGINT) using the `ProcessSignal.sigint.watch().listen` method and close the socket inside the callback, but the vscode debugger terminates the application with an `exit(1)` and no useful signal. The end result is that the socketis not closed and the dart process doesn't terminate.

**Comment by DanTup** [comment]
@giohappy could you open a new issue and include a small repro project I can use for testing? Thanks!

**Comment by giohappy** [comment]
@DanTup curiously I cannot reproduce it anymore after your reply! I've spent hours yesterday on this issue, but now it doesn't happen anymore. Maybe vscode restarts? In case it happens again I will file a new issue.

**Comment by DanTup** [comment]
@giohappy heh, that's always the way. If you haven't updated anything, I suspect it'll be back at some point, so do file a new issue when you have more info and we'll go from there. Thanks!
