### ISSUE TITLE
Using rename symbol on named parameters modifies the object's Class property name.

### ISSUE THREAD

**Issue by samueldaviddelacruz** [Dart-Code/Dart-Code#915]
using the rename symbol helper on VS code on a named parameter modifies the original property name of the object's class, this can lead to undesired behavior since the constructor still keeps the old name while the property name changes, which leads to code not compiling, , it shouldn't go to the class and change it that way, it shouldn't work upwards imo.

**Comment by DanTup** [comment]
@samueldaviddelacruz Can you give an example in Code?

I just tried this:

```dart
class Person {
  String name;
  Person({String name}) {
    this.name = name;
  }
}

void main() {
  var a = new Person(name: "Danny");
}
```

When I invoked rename on `name:` it renamed only the constructor argument (which I think is expected?).

So I tried when the constructor references the field directly, like this:

```dart
class Person {
  String name;
  Person({this.name});
}

void main() {
  var a = new Person(name: "Danny");
  print(a.name);
}
```

Here, it does rename the field; but it also renames all references to it, so there are no compile errors (again, I somewhat expect this, and you can avoid it by changing the constructor to do `this.name = name` before renaming if you won't want the field to be renamed).

I can't come up with anything that results in a compile error though.

**Comment by samueldaviddelacruz** [comment]
Here is an example, i'm using flutter at the moment and i used rename symbol on a named parameter of the Switch object from the material design package: ![Rename symbol](https://i.imgur.com/yxK7DiE.gif)

**Comment by DanTup** [comment]
Oh, I see. Do you have the Flutter folder open as part of your workspace?

If not, this does seem like a bug to me - I don't think any rename operations should modify source files that aren't part of the analysis roots (@bwilkerson - would you agree?).

That said, if you don't have it open, what are you expecting to happen when you perform the rename? If the above is a bug, the fix will likely just result in an error/rejection (I'm not sure if that's what you want, or if you actually wanted to achieve something with the rename?).

**Comment by samueldaviddelacruz** [comment]
i dont have the flutter folder open, just my project folder open, it goes out of its way and renames it over there, i think a rejection for files outside of the scope of the project should be the right behavior.

funny thing is that i found the rename bug by mistake while trying to rename something, then it lead me to that bug.

**Comment by DanTup** [comment]
@samueldaviddelacruz Cool, thanks for clarifying. I wanted to be sure you weren't expecting the rename to do something useful; if you expect it to reject, that seems sensible to me.

I'll wait for @bwilkerson's input, but suspect this will need a fix in the SDK repo.

**Comment by bwilkerson** [comment]
I agree. We ought to not modify code that the user doesn't control. This sounds like a bug in server.

**Comment by DanTup** [comment]
Ok, I've raised this over at https://github.com/dart-lang/sdk/issues/33181 then. Thanks!
