### ISSUE TITLE
Hot reload is not triggered on save

### ISSUE THREAD

**Issue by Ramalus** [Dart-Code/Dart-Code#918]
**Steps to reproduce**
- On a brand new project from `flutter create`
- Hit *F5*
- After project runs on device or emulator, change the default project's `primarySwatch` from `Colors.blue` to `Colors.red`.
- Hit save

**Expected outcome:**
- Hot reload should be triggered and the application `primarySwatch` colour should be changed from blue to red.

**Actual outcome:**
- Hot reload doesn't seem to have been triggered (no message in the bottom debug bar)
- Application colour is still blue.

**Observations:**
- When triggering the green "restart" button on the debug floating bar, the application reloads the expected changes.
- When triggering from the command pallet, hot reload is also not triggered.
<img width="604" alt="screen shot 2018-05-20 at 17 06 47" src="https://user-images.githubusercontent.com/2881382/40283245-9557af08-5c51-11e8-848a-e9e8f0d4a636.png">
<img width="1300" alt="screen shot 2018-05-20 at 17 19 22" src="https://user-images.githubusercontent.com/2881382/40283279-24eaf6a2-5c52-11e8-85fd-547744b71deb.png">

**Log Files:**
[flutterRunLog.txt](https://github.com/Dart-Code/Dart-Code/files/2020665/flutterRunLog.txt)
[flutterObservatoryLogging.txt](https://github.com/Dart-Code/Dart-Code/files/2020672/flutterObservatoryLogging.txt)

**Comment by DanTup** [comment]
@Ramalus Could you try a few things for me?

1. Create a launch.json file (click the Cog on the Debug sidebar, then use the code-completion to pick the Dart/Flutter app) and add `args: ["--verbose"]` to the launch config. This should result in more verbose logging for `flutter run`
1. After reloading from the command palette a few times, click the Stop button (to terminate the debug session), and then get a copy of the logs (the current Flutter Run log seems to just stop, and it's not clear if it's because there was no more logging, or it was just not flushed - by stopping the process, it should give us some disconnect logging)

After you've done that, you can delete the launch.json and comment out the log settings. Thanks!

**Comment by Ramalus** [comment]
Done @DanTup 

The flutter run log seems to have only a couple of bytes. Not sure if thats normal after disconnecting. But here it goes.

Anything else just let me know.

[flutterObservatoryLogging.txt](https://github.com/Dart-Code/Dart-Code/files/2020698/flutterObservatoryLogging.txt)
[flutterRunLog.txt](https://github.com/Dart-Code/Dart-Code/files/2020699/flutterRunLog.txt)

**Comment by DanTup** [comment]
@Ramalus Hmmm, no, that's not expected. It should be bigger than the first one. Did you restart the debugging session and capture the full session? If so, it's possible there's something wrong with the `--verbose`, so you could try deleting your launch.json (or removing the args) and trying again. We should get a log at least the same as your first one, but that includes the disconnect/app.stop at the end.

Thanks!

**Comment by Ramalus** [comment]
I did restart it. I also found it odd. 

I'll send it in a bit.

**Comment by Ramalus** [comment]
Without `"args": ["--verbose"]`

[flutterObservatoryLogging.txt](https://github.com/Dart-Code/Dart-Code/files/2020741/flutterObservatoryLogging.txt)
[flutterRunLog.txt](https://github.com/Dart-Code/Dart-Code/files/2020742/flutterRunLog.txt)

**Comment by Ramalus** [comment]
With `--verbose` but without stopping the debug session.

[flutterObservatoryLogging.txt](https://github.com/Dart-Code/Dart-Code/files/2020743/flutterObservatoryLogging.txt)
[flutterRunLog.txt](https://github.com/Dart-Code/Dart-Code/files/2020744/flutterRunLog.txt)

**Comment by Ramalus** [comment]
After stopping the debug session (same session as comment above)

[flutterObservatoryLogging.txt](https://github.com/Dart-Code/Dart-Code/files/2020745/flutterObservatoryLogging.txt)
[flutterRunLog.txt](https://github.com/Dart-Code/Dart-Code/files/2020746/flutterRunLog.txt)

**Comment by DanTup** [comment]
@Ramalus I presume you're editing a single project, with no compound launch configurations/multi-root workspace or anything unusual? All just the defaults?

When you captured your logs, did you run the command, or click save?

Would you be able to try running Dart Code from the source code and put a breakpoint in to see what might be happening? It's fairly simple; you'll need nodejs/npm, there's info here:

https://github.com/Dart-Code/Dart-Code/blob/master/CONTRIBUTING.md#cloning-and-running-dart-code

It's basically just clone, run `npm install`, open it in VS Code then press `F5`. It'll launch a "copy" of VS Code with the extension installed. In that new version, you can open your Flutter project and press `F5` to launch.

If (back in the original version of Code, which has the Dart Code source open) you search for `registerCommand("flutter.hotReload"` in `src/commands/debug.ts` and put a breakpoint inside that handler, you could step through and see whether it's bailing out anywhere.

If it gets as far as calling `this.currentDebugSession.customRequest` then you want to put a breakpoint inside `src/debug/flutter_debug_impl.ts` in the `customRequest` method and then continue stepping to see where it goes. Based on your logs, it seems like it's not getting into the `performReload` method in there; but I can't see any obvious reason why that might be.

Failing that, I may have to give you a build with a bunch of debug logging that might help indicate where it's going bad.

**Comment by Ramalus** [comment]
Answering your questions:

*I presume you're editing a single project, with no compound launch configurations/multi-root workspace or anything unusual? All just the defaults?*
**No custom launch configurations, all defaults and brand new `flutter create` project**

*When you captured your logs, did you run the command, or click save?*
**I did both, several times.**

I'll try running the instructions you mentioned.

**Comment by DanTup** [comment]
@Ramalus Ok thanks, let me know how you get on. If you have any issues, I'll just make a build that has some extra logging in; just ping me here or in Gitter if that works out best for you.

**Comment by Ramalus** [comment]
Hi @DanTup,

I just tested your instructions.
```javascript
context.subscriptions.push(vs.commands.registerCommand("flutter.hotReload", () => {
	if (!this.currentDebugSession)
		return;
	this.reloadStatus.hide();
	this.sendCustomFlutterDebugCommand("hotReload");
	analytics.logDebuggerHotReload();
}));
```

It returns on that `if(!this.currentDebugSession)` since `this.currentDebugSession` is `Undefined`.

**Comment by Ramalus** [comment]
@DanTup I got it!

So it turns out the type of `s` in the snippet you provided is being set as `vslsShare` which is being caused by the preview of the VS Live Share extension.

<img width="1021" alt="screen shot 2018-05-27 at 13 41 30" src="https://user-images.githubusercontent.com/2881382/40588476-f14bdf7a-61b3-11e8-8723-e97a4fe455f6.png">

<img width="685" alt="screen shot 2018-05-27 at 13 43 00" src="https://user-images.githubusercontent.com/2881382/40588472-ed2e9522-61b3-11e8-96e1-146027c7fcc4.png">

After I disable the extension, the type property of `s` goes back to `dart` and everything works as expected.

**Comment by DanTup** [comment]
@Ramalus Thanks for the investigation! Someone previously had mentioned this extension was breaking things, but I don't think I got specific details. I'll do a little testing and see if I can find somewhere to raise an issue (at least we should be able to workaround it, but really having their extension installed should not just break other peoples debuggers!).

**Comment by DanTup** [comment]
I've opened https://github.com/MicrosoftDocs/live-share/issues/465 to try and get some info on how we're supposed to deal with this. The node-debug extension does the same thing we're doing, so I don't think it's unusual.

**Comment by DanTup** [comment]
I've implemented their workaround on a branch, but still having issues. Hoping with their help we can get a fix into v2.13.

**Comment by DanTup** [comment]
I've merged in the workaround, but this also needs a fix in VSLS which I believe they're intending to ship tomorrow (I've tested with a build they linked and it was good).

For now you can disable their extension for any Dart workspaces; but hopefully at the end of the week we'll both have shipped fixes/workarounds.

Thanks for the effort tracking it down!

**Comment by Ramalus** [comment]
No problem @DanTup. Glad to help.

Thank you for the quick input!

**Comment by ianldgs** [comment]
I'm getting the same problem, but I don't have VSLS extension

**Comment by DanTup** [comment]
@ianldgs Can you open a new issue and attach Flutter Run and Observatory logs? Info on getting logs is here:

https://dartcode.org/docs/logging/

Also see the note [here](https://github.com/Dart-Code/Dart-Code/issues/918#issuecomment-395993116) about enabling Verbose mode.

**Comment by DanTup** [comment]
@ianldgs That is strange; since there's not really any difference between saving a Dart file and a Java file :/ The logs may help though; I don't think it's the same issue reported here, so if you open an issue with logs I'll do some investigation.

**Comment by LBroy** [comment]
I also got this problem. And I don't have VSLS installed as well.

**Comment by DanTup** [comment]
@LBroy Would you mind capturing a log (see https://github.com/Dart-Code/Dart-Code/issues/918#issuecomment-396001595) and opening a new issue with them attached? Thanks!
