### ISSUE TITLE
Provide "Open in Android Studio" option

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#923]
Similar to https://github.com/flutter/flutter-intellij/issues/1063

**Comment by DanTup** [comment]
@pq @devoncarew Is it valid to just open the project root folder in Android Studio? I tried passing the iml file when I opened it, but it just shows that file as XML in the editor. I'm not sure if when opening in AS whether people want the whole flutter project, the `android` sub folder, or what (the `iml` files are in the root, not inside the android folder).

**Comment by pq** [comment]
Hmmm, to be honest, I'm not sure.  @stevemessick should know though. 👍

**Comment by stevemessick** [comment]
You should give Android Studio the path to the `android` module for apps. For plugins, give it the `android` module in the example app. For more detail, see:
https://github.com/flutter/flutter-intellij/blob/a3a80b7fc1684bdfa3cedf1ec5e2f608f76b71f8/src/io/flutter/actions/OpenInAndroidStudioAction.java#L98

**Comment by DanTup** [comment]
If I'm reading that correctly; it's opening the `android` folder (which in the case of a plug is at `example/android`)?

I'm adding this as a context-menu entry to folders named `android` so I think in this case I can just pass that folder as an argument to Android Studio and not have to worry about the iml files at all?

I'm not exactly how the project should look in Android Studio, so I wouldn't know whether I've just "open a folder" that has some code in it, or whether it's opened in the correct way for whatever the users workflow is (I've not done anything outside of the Dart code in Flutter).

I'll go with this for now, and update it if anyone corrects me or raises issues. Thanks! 👍
