### ISSUE TITLE
Make getters more obvious in debug views

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#928]
See https://github.com/Dart-Code/Dart-Code/pull/924#pullrequestreview-122224527

There's a presentation hint which I'm not sure how it renders, but we could also tweak the text label as Devon suggests.

**Comment by DanTup** [comment]
For now, I'm sticking `(get)` on the end. I tried putting just `get ` in front, but it looked a bit weird (and made the sorting look wonky). It's not perfect, but if we get a better way to render this in future, we can change.

![screen shot 2018-05-23 at 10 27 41 am](https://user-images.githubusercontent.com/1078012/40415965-13828794-5e74-11e8-9632-30103d8e125f.png)

cc @devoncarew in case you have any better ideas... adding `()` or `=>` on the end looks weird because one makes it look like a method and the other has a `:` after it. Here's screenshots for completeness:

![screen shot 2018-05-23 at 10 30 12 am](https://user-images.githubusercontent.com/1078012/40416114-63d6799e-5e74-11e8-8963-41d61f33499d.png)
![screen shot 2018-05-23 at 10 30 36 am](https://user-images.githubusercontent.com/1078012/40416116-64045d96-5e74-11e8-8652-9e207812f9d4.png)

**Comment by devoncarew** [comment]
I don't know that any one of the above is necessarily better than the others. It's useful for the user to know that there's a bit more expression eval to display these values, but perhaps not critical.

**Comment by DanTup** [comment]
@devoncarew I tried the get-prefix (mentioned above), but it looked wonky. I forgot to include a screenshot though:

![screen shot 2018-05-23 at 3 05 28 pm](https://user-images.githubusercontent.com/1078012/40429503-c22349de-5e9a-11e8-931f-6ecf0fada39f.png)

And we can't remove the colon (to replace with just `=>`, it's added by Code) :(

I have no real preference here. I think `(get)` looks a bit wonky, but I don't know having nothing is worse. If you have any preference out of any of them, I'm happy to go with it.

**Comment by devoncarew** [comment]
Of all of them, perhaps `get foo`, or no indication at all? There's also the option of `foo (getter)`. ¯\_(ツ)_/¯

**Comment by DanTup** [comment]
> `get foo`, or no indication at all

If you consider these about the same, I'm gonna go with no indicator for now, as I think `get foo` looks a bit wonky (esp. as in a lot of code from the outside there's no real difference between the two, I don't think they should look *that* different).

We can always revisit in future though (I'm hoping MS give us some better presentation options - there's a bug structure of presentation hints that seems to do absolutely nothing so far!).
