### ISSUE TITLE
Unable to copy exception text from variables window

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#934]
Not sure if we can fix this without being able to have an `evaluateName`?

![screen shot 2018-05-23 at 2 20 16 pm](https://user-images.githubusercontent.com/1078012/40427071-90230ac4-5e94-11e8-9ac4-cac47ecb0cf7.png)

**Comment by DanTup** [comment]
@devoncarew I'm fixing this by introducing a fake variable named `$e` which when evaluated returns the current exception. If you use `$e.x` when we use `evaluate` instead of `evaluateInFrame` and target the exception to evaluate `x`.

If IntelliJ has any convention for exceptions (eg. to add to the watch window), we could align this with it.

I don't expect users to really use (or even notice) the `$e`, but I needed to be able to give an evaluate expression to VS Code in order to allow it to let the user copy the value (since the value for display could be truncated, they send an evaluation for the full variable during copy).

**Comment by devoncarew** [comment]
We do display the exception as a live watch variable named `exception`. It shows up as a std. object - if it has fields you can explore into it, but it wouldn't participate in any eval namespace.

Would the `e` name be user-facing?

**Comment by DanTup** [comment]
In the Variables window it appears as in the screenshot up top (in a section named `Exception`). The `$e` would only be visible to the user if they right-clicked on the exception and did `Add to Watch` which would allow them to customise the expression in the watch window.

**Comment by DanTup** [comment]
Gonna consider this done for now; but let me know if you think we should make changes. Not assigning a name to it (like `$e`) prevents us from letting the user copy things like the `message` property which feels a bit limiting.
