### ISSUE TITLE
Make Document symbol search results look like workspace symbol results

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#94]
@devoncarew Pulling this out of #91 so I can merge it and we don't forget.

> DT: Do you think we need to make the document symbol list (Ctrl+Shift+O) look more like this?
> 
> DC: Possibly just to convert it to Class.member style? We really wouldn't use the containerName fields much at all then
>
> DT: Yeah, probably. It did look good as-is, but I think being consistent is probably better. What do you think?

I think we should probably do it, but since I'm a noob and not a big user of them I can be swayed if you think it's better as-is.

**Comment by devoncarew** [comment]
I _think_ `Class.member` format would look better, but would need to try it to be sure :)

**Comment by DanTup** [comment]
![symbols](https://cloud.githubusercontent.com/assets/1078012/17676759/d224f9e2-6327-11e6-82f9-2f200e12ec40.png)
?

**Comment by devoncarew** [comment]
👍

**Comment by DanTup** [comment]
Does that mean you prefer the right one?

**Comment by devoncarew** [comment]
Yup, I think that's a bit easier for people to parse.

**Comment by DanTup** [comment]
Cool, I've merged in.
