### ISSUE TITLE
@override autocomplete not appearing

### ISSUE THREAD

**Issue by xster** [Dart-Code/Dart-Code#943]
It seems like my issue from https://github.com/Dart-Code/Dart-Code/issues/307, https://github.com/Dart-Code/Dart-Code/issues/574 reappeared

Logging here for the record

![may-25-2018 14-52-20](https://user-images.githubusercontent.com/156888/40567703-58655a7c-602b-11e8-9139-e779e0e18874.gif)

**Comment by xster** [comment]
[vsdart.log](https://github.com/Dart-Code/Dart-Code/files/2040951/vsdart.log)

ok, this time the problem didn't disappear after adding logging

I attached it here. It ended up recognizing the override after it says 'This method overrides a method annotated as @mustCallSuper in 'State'' but it wouldn't autocomplete before

**Comment by DanTup** [comment]
I believe this is the same as the issue above. There are weird things with the override completions depending on where you invoke completion:

![screen shot 2018-06-13 at 4 12 12 pm](https://user-images.githubusercontent.com/1078012/41360449-b7e27824-6f24-11e8-94db-397e6c10d58a.png)

![screen shot 2018-06-13 at 4 12 30 pm](https://user-images.githubusercontent.com/1078012/41360461-be438d16-6f24-11e8-8433-fa4190e64c10.png)

**Comment by DanTup** [comment]
Closing this since it's not fixable in Dart Code and there's an upstream bug link above - subscribe there for updates.
