### ISSUE TITLE
Silent extension restarts lose reference to debug session, breaking functionality like hot reload (and other flutter extension calls)

### ISSUE THREAD

**Issue by xster** [Dart-Code/Dart-Code#944]
Kind of an edge case but I thought it was curious

I had a debug session, then went into settings.json and added `"dart.closingLabels": false`, saved that. 

Went back to the file I was editing. Made some small changes and pressed save. No auto hot reload. 

Though pressing F5 still does hot reload

**Comment by DanTup** [comment]
v2.13 is close to shipping so this fix is going into v2.14, but I'll probably make an early build of that next week.
