### ISSUE TITLE
seeing strange analysis issues when I have the git diff view open for a file

### ISSUE THREAD

**Issue by devoncarew** [Dart-Code/Dart-Code#950]
When I have the git diff view of a dart file open, I see strange analysis issues (indicating not well-formed dart files). This generally happens after I edit the file from within the diff view. These don't clear up until I either 1) close and re-open VS Code, or 2) close the open regular file, and then close the open diff view of the file.

I think that we're sending in analysis overlays for the diff view of the file, and that the source it reports might be incorrect in some way. We likely either shouldn't sent in overlays for diff editors, or if we do ensure that the view of the source we're sending in is correct.

**Comment by DanTup** [comment]
> I think that we're sending in analysis overlays for the diff view of the file

Yep :(

This is actually a result of the same thing I mentioned in #946, the change to `isUntitled` in VS's TextDocument. It was raised in #901 but already fixed as part of the other change.

It's worth updating to the [beta](https://github.com/Dart-Code/Dart-Code/releases/tag/v2.13.0-beta.4) which has fixes for these issues; though should be released to stable this week.
