### ISSUE TITLE
Missing Extract Method refactoring

### ISSUE THREAD

**Issue by mit-mit** [Dart-Code/Dart-Code#959]
Start code:
https://gist.github.com/mit-mit/45ecd1781d6ece05b96668f940318cd5

Place the cursor on the `new` keyword in line 43.

Invoke Refactor

Expected result: See the Extract Method refactoring + Flutter specific refactorings.
Actual result: Just see the Flutter build specific refactorings

**Comment by mit-mit** [comment]
Same steps work OK in IntelliJ.

**Comment by DanTup** [comment]
If I highlight the `e` in `new` then I get `EXTRACT_METHOD` back from `getAvailableRefactorings`, however if I don't select anything then I don't. This suggests that `EXTRACT_METHOD` only comes back for a selection (non-zero length).

I'm not sure if this is intended? If we made the user select the code they wanted to extract then I think this would make sense, but the fact that I can highlight the `e` and extract method and it works (it expands to the block) suggests that we're not forcing the user to make that selection.

@scheglov do you think this should be changed in the server?

**Comment by DanTup** [comment]
```js
[
	{
		"id": "39",
		"method": "edit.getAvailableRefactorings",
		"params": {
			"file": "/Users/dantup/Desktop/extract_method_repro/lib/main.dart",
			"length": 0,
			"offset": 1077
		}
	},
	{
		"id": "39",
		"result": {
			"kinds": [
				"EXTRACT_WIDGET",
				"RENAME"
			]
		}
	}
]
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/57060 will fix `edit.getAvailableRefactorings` so that it sometimes returns `EXTRACT_LOCAL_VARIABLE` and `EXTRACT_METHOD` even with zero length selection.

**Comment by DanTup** [comment]
@scheglov Great, thanks!

@mit-mit It'll take a while for this to make its way to Flutter. I could make it always appear in the list for now but that would result in it appearing where it's not valid too (this isn't terrible, it'd give the user an error message if they invoked it). Let me know if you have a preference.

**Comment by mit-mit** [comment]
Happy to see this fixed! Danny, no need to do anything additional, we can wait until this comes over naturally.

**Comment by DanTup** [comment]
Ok, great :-)
