### ISSUE TITLE
Add option to organise directives on save

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#96]

**Comment by DanTup** [comment]
Struggling to find a clean way to do this... Requested some advice at https://github.com/Microsoft/vscode/issues/10741

**Comment by DanTup** [comment]
This is a common request, in the Code backlog: https://github.com/Microsoft/vscode/issues/239

**Comment by devoncarew** [comment]
Note: as of vscode `1.6` (the latest stable) format on save is available as a general option (`editor.formatOnSave`).

**Comment by DanTup** [comment]
Yep! Changing this to just be for doing organise directives on format then and we can do that without any external changes.

**Comment by DanTup** [comment]
This is less easy than I expected.. Code wants us to return the edits from the DocumentFormattingEditProvider rather than apply them; so if we send requests for both organizeDirectives and formatting, we might get back edits that can't be applied sequentially (since they share the same base document).

**Comment by DanTup** [comment]
Changing this to be organise-on-save since I think we can do that, but I don't think we can do it on format. In most cases people probably use format-on-save so it'll work out the same anyway, but the APIs play together this way.
