### ISSUE TITLE
New code folding logic is missing some folds

### ISSUE THREAD

**Issue by Skylled** [Dart-Code/Dart-Code#966]
Here's the same snippet in latest stable and beta

![v2.12 Stable](https://i.imgur.com/r1ZHa5q.png)

![v2.13 Beta 4](https://i.imgur.com/LdPsFEI.png)

Things I've found that do not fold:
- Class constructors
- Lists
- Maps

**Comment by DanTup** [comment]
Ah, I see what you mean by constructors now - the calls to them, not their definitions.

@bwilkerson these seem reasonable to me (especially in Flutter code where function/constructors end to be spread over many lines), WDYT?

**Comment by bwilkerson** [comment]
Well, I never use code folding at all, so I might not be the best person to ask :-), but yeah, it seems reasonable. I'd probably fold these structures when the code would get an end-of-structure decoration (that's not the right term, but I mean the "// Padding" decorations that get added). That would feel consistent to me, but again, take that with a grain of salt.

**Comment by DanTup** [comment]
I think closing labels logic was simplified to be anything that spans lines; which is what we do for folds too (we don't show a fold for anything on a single line), so I *think* they'd just match by adding these in. I'll take a look soon.

**Comment by DanTup** [comment]
@bwilkerson I think we need to add new FoldingKinds for this. Any preferences on names (INVOCATION, LIST, MAP? Is there a reasonable way to describe both Lists+Maps in one kind?).

**Comment by bwilkerson** [comment]
The name INVOCATION is very general. Do we expect to provide folding for all constructor, method and function invocations? If so, then it's probably appropriate to be general.

The names LIST and MAP could be LITERAL, but that might be too general. Would we want to fold string literals that are more than one line long (either multi-line strings or even large numbers of adjacent strings)? Would clients ever want to fold one without the other? If we start supporting set literals, would we want them to be in the same folding kind? (I'm guessing that LITERAL would be sufficient, but we need to consider the implications.)

**Comment by DanTup** [comment]
> The name INVOCATION is very general. Do we expect to provide folding for all constructor, method and function invocations

I think this probably makes sense when they're spanning multiple lines. It might mean we end up with them starting on a lot of consecutive lines in Flutter code, but I don't think it's unreasonable to want to collapse any section of a build method given they tend to get quit deeply-nested easily.

> The names LIST and MAP could be LITERAL, but that might be too general

Yeah, I thought that was a bit general too. Though now you mention strings etc. could be useful I think maybe it makes sense to put these together. Whether users might want to control them individually, I'm not sure - it's possible, but I don't think there's a huge difference between them in terms of navigating around your code, so I think lumping them together would be fine.

So, unless there are any objections before I pick this up, I'll go with INVOCATION and LITERAL for now and implement for constructor/method/function invocations and list+map literals (where they span multiple lines, ofc).

**Comment by bwilkerson** [comment]
Sounds good to me. Thanks!

**Comment by DanTup** [comment]
https://dart-review.googlesource.com/c/sdk/+/58740

![screen shot 2018-06-06 at 4 27 14 pm](https://user-images.githubusercontent.com/1078012/41048541-d57dd49c-69a6-11e8-942e-12779adc6454.png)

The folds look slightly weird in the screenshot because VS Code hides all the way to the end of the line that the fold closes on - as you can see from the tests, the range ends on the inside of the closing bracket/paren. I would prefer them to replace the folded region with `[...]` so you'd see:

```dart
myFunction(`[...]`);
```

But I think maybe they don't want to have a line which contains characters from two actual lines in the doc :(

**Comment by DanTup** [comment]
https://dart-review.googlesource.com/c/sdk/+/58740 has landed so this will be fixed in an upcoming release. (https://dart-review.googlesource.com/c/sdk/+/59061 is still open for function expressions, but shouldn't be far behind).
