### ISSUE TITLE
If you try to launch when there are errors, prompt the user (preview)

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#982]
TypeScript seems to do this, you get a dialog offering to show errors or "debug anyway".

**Comment by DanTup** [comment]
Maybe blocked by https://github.com/Microsoft/vscode/issues/51341.

**Comment by DanTup** [comment]
We now have the ability to cancel launches silently, so we can implement our own handling of this (since VS Code isn't going to get native support for this -> https://github.com/Microsoft/vscode/issues/51341#event-1858122274)

**Comment by devoncarew** [comment]
I'd have to check what we do in intellij, but I think it's something like warning if there are any analysis errors in the folder containing the app entry point (and the lib/ folder?)? I believe our implementation explictly didn't want to check any test/ folders, or referenced packages.

**Comment by DanTup** [comment]
Ah ok, so if IntelliJ is already doing this (eg. it'll ignore errors in related projects) then it doesn't seem so crazy to do the same here. If you can check (or point me at where to find it - I did look, but I fail at navigating Java) I'll follow the same rules.

**Comment by devoncarew** [comment]
Suer; there's some logic here: https://github.com/flutter/flutter-intellij/blob/8711dbba1ffbacb408a387410377704f3bb6720e/src/io/flutter/run/FlutterReloadManager.java

Essentially, we use the errors reported by the analysis server, we scope to the current project the app is running from, and we filter out any issues reported from a `test/` directory.

**Comment by DanTup** [comment]
@devoncarew That code looks like Hot Reload, but this issue was just about the general launch with F5. I'm assuming the same logic is sensible so I'm going to try it and see how it feels.

FWIW though, our reload-on-save code is only checking for files in the saved files (the way it works, it'll actually reload as long as one of the saved files has no errors in the case of save-all). I'm not sure if this should be more clever, though so far nobody has complained it's triggering too much.
