### ISSUE TITLE
Support targeting different terminals for running/debugging

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#99]
@devoncarew Looks like this is going into September release, so probably around 6 weeks away:

https://github.com/Microsoft/vscode/issues/10574

The initial terminal API is marked for August.

We need to check whether we can require that version of Code when it happens, else we'll have to make this conditional.

Marking as v1 because I'd love to have it, but it's probably wishful. If we end up wanting to ship a v1 before this is usable, we'll bump it back.

**Comment by DanTup** [comment]
Seems that MS have done debug support for integrated terminal; I've asked if they might ship it in the August release but we should branch this from `debugger` for now just in case it doesn't.

Feature info: https://github.com/Microsoft/vscode/issues/10574
Implementation in the Node debugger:  https://github.com/Microsoft/vscode-node-debug/issues/85

We'll need to bump our code version to 1.5 for this and the debug adapter/protocol versions too. I believe it'll work in Insiders builds from Monday.

**Comment by DanTup** [comment]
@devoncarew I had a quick look at this to see how complicated it could be. I've pushed a minor change to a branch as a WIP. It seems to work! There are some issues:

1. Can't get stdout when launching, so we need to set the observatory port up-front (I'm currently leaving it as default, but we'll probably have to randomly generate? Need to check if MS do something better in their node one)
2. If you launch "without debugger", Code doesn't know when it terminates and so appears to be stuck "running" even when it terminates (there's some dirty hack in their node sample that polls for the process; wonder if we could do something better?)
3. I've left the original code as `runStandalone` but if we can confirm that Code `>=1.5` always sends `supportsRunInTerminal=true` and the constraint changes will disallow installing in 1.4, we could ditch all that.

Interested in your thoughts! Feel free to make changes if you want; it's unlikely I'll get any more time on this before late Friday.

**Comment by DanTup** [comment]
Seems like this debug feature is being shipped disabled in 1.5, so bumping this to later. I really want to ship rename/codefixes/basic debugging in the next week or so.

**Comment by DanTup** [comment]
Insiders now supports targetting external terminals too. I think it might make sense to support all these options and let the user configure (and pick a good default).

**Comment by DanTup** [comment]
If Code gives us a pid, we might be able to use SIGQUIT to get the port instead of hard-coding:

https://dart-lang.github.io/observatory/get-started.html

```text
$ ps ax | grep dart
<pid> pts/61   Sl+    0:01 dart example.dart
$ kill -s SIGQUIT <pid>
Observatory listening on http://127.0.0.1:<port>
```

**Comment by devoncarew** [comment]
The sigquit response gets written to stdout, so tough to get ahold of if you don't already have access to stdout (and if you do, scrapping for the `Observatory listening on` message is pretty reliable, and lets the port we bind to float).

**Comment by DanTup** [comment]
> The sigquit response gets written to stdout, so tough to get ahold of if you don't already have access to stdout

Ah, good point :( I'll have to have a play around and see what I can figure out when it's working. Been really busy last week or so so haven't made much progress. Hopefully will get more time later this week!

**Comment by DanTup** [comment]
Another thought: even if we could get stdout, I don't think it's reasonable to spew stuff to the users stdout.

I think we'd be best randomly picking a port number and sending it (and either hoping it's not already bound or finding a way to check that won't leave it locked).

**Comment by DanTup** [comment]
@devoncarew Getting back to this now.. There are three ways to launch:

1. Map output to debug output (live implementation)
2. Use integrated terminal
3. Use external terminal

Ignoring the issues above (Observatory port, detecting process end) all three of these work. I'm trying to figure out whether we should support all of these or not... I think 1 may be best replaced by 2 or 3 - there are weird restrictions (STDIN doesn't work, our debug output and STDOUT mixed together). I *think* that all >= 1.6 Codes will support the terminal so I don't think dropping support for 1 is a problem if we're already forcing Code 1.6 soon anyway.

Personally I also think 2 is a bit naff too (the integrated terminal has weird quirks) but I can see the appeal if you have Code full-screen and don't want to be switching windows all the time.

What do you think? Does ditching 1 seem reasonable? If we keep 2+3 how should we let the user pick between them - a normal user setting (which could be set globally by the user or overridden in a local project) or an explicit setting in `launch.json`? (I think the user-setting is most flexible; people using the non-default option don't have to keep changing it).

**Comment by DanTup** [comment]
@devoncarew What do you mean by the first option - in the debug output? What do you think this does better than the integrated terminal? (As far as I can see, it breaks STDIN and mixes user output with outs; but I presume I'm overlooking a benefit you see!)

I think the debug window is a bad default, because it's not obvious to beginners why their application just hung if they're making an interactive script. At the expense of asking the user too many questions, maybe we should prompt them on first run which they prefer (leaving all three) and add to analytics too?

**Comment by Rodsevich** [comment]
Please add this!! :pray:

**Comment by DanTup** [comment]
Another option that might help here, is the new Terminal API in Code:

https://code.visualstudio.com/updates/v1_39#_extension-terminal-api

This would allow us to run as we do today, but target the terminal window with a fake process - and when the user types into it, we can pass that to the real stdin of the process.

**Comment by Aung-Thiha112** [comment]
I can not still satisfied because my terminal is exist running the code within 3s and I did not even notice what was the output. can someone explain this to me?

**Comment by DanTup** [comment]
@Aung-Thiha112 Do you mean the output is disappearing? The Terminal should remain available after the application finishes - is that not what you see? If not, please file a new issue with details.

**Comment by DanTup** [comment]
@kyrosle it's not possible because of the way Flutter works. That setting is to tell VS Code to execute the script so you can use things like `stdin.readline()`. In Flutter, this isn't possible because a) the program may be running on another device where you can't access stdin and b) the debugger has to interact with the `flutter` tool over stdin/stdout (which it can't do if it's running in a terminal it has no access to).

Can you explain what it is you're trying to do?

**Comment by kyrosle** [comment]
my project has lots of log, info, warn, debug and error, i used to writing code in vscode and running the program in jetbrain android studio, but recently i want to make all development in vscode, and then i found that the vscode debug consle is so hard to watch the log message. vscode debug console only support filter the log message... 
  i think i could using the intergate terminal instead of the debug console, cos of, the intergate terminal support the searching text, or i can watch the log message in the output window, btw, it is possible that similar with jb debug console by open a new window to show the flutter output?

**Comment by DanTup** [comment]
Thanks for the info. Unfortunately I don't know a great way to do this - it sounds like it might be worth filing a VS Code issue for being able to Find (not filter) in the Debug Console.

As a workaround, you could use `flutter run` to run your application in the terminal, but you would lose debug functionality. You could get some of this back by then running **Debug: Attach to Flutter** to attach the debugger to the instance you're running from the terminal, but it's a little clunky.

**Comment by kyrosle** [comment]
is any possible to access it by this way? https://github.com/microsoft/vscode/issues/4338#issuecomment-1784061229

**Comment by DanTup** [comment]
@kyrosle yes, that's an existing feature request for Find in the Debug Console. I thought there was already an issue but hadn't been able to find it when I wrote the comment above. Please add your 👍 to that issue.
