### ISSUE TITLE
Dart Code analysis shows error on valid line

### ISSUE THREAD

**Issue by keenedge** [Dart-Code/Dart-Code#992]
OK. I admit.  I don;t know how to tell if this is Dart, or Dart Code.  But I see the problem through Dart code so I am starting here.

Dart code show several errors on my own Dart object.   However, flutter /Dart compile the project with out any errors.

The full text of the error is:
`The argument type 'Stream<List<Tag>> (C:\software\portable\flutter\bin\cache\pkg\sky_engine\lib\async\stream.dart)' can't be assigned to the parameter type 'Stream<List<Tag>> (C:\software\portable\flutter\bin\cache\pkg\sky_engine\lib\async\stream.dart)'.
`
Both types appear to be exactly the same but it is highlighted as an error as shown in the screen shot below. 

![image](https://user-images.githubusercontent.com/531085/41107721-3418c170-6a73-11e8-90a4-8abb154e3f88.png)

**Comment by DanTup** [comment]
Can you try setting

```js
"dart.previewExperimentalWindowsDriveLetterHandling": true
```

in your User Settings and restart and see if that fixes it? This setting will default to on in the next update; it performs some normalisation of drive letters because there are some issues in Dart with case-sensitive paths on Windows.

**Comment by keenedge** [comment]
That was too easy.. and sooo very fast.  Thanks for the quick fix.  works like a charm.

**Comment by DanTup** [comment]
Awesome, thanks for confirming :-)

In the next version you might start seeing a warning that this option no longer exists (because it's been renamed). When you do, you can just remove it from your settings and it'll be on by default.

**Comment by DanTup** [comment]
Btw, I think as part of https://github.com/Dart-Code/Dart-Code/issues/798 Dart Code should've shown a warning about the casing mismatching at startup - do you know if it did? That was supposed to be our hint to the user that something was up!

**Comment by keenedge** [comment]
I'm not exactly sure what I should have seen but, I don't believe I've seen any warnings about path case mismatch.

**Comment by DanTup** [comment]
It should've been a warning notification in the bottom right corner. I think VS Code auto-hides them after a while though!

**Comment by keenedge** [comment]
I just undid     "dart.previewExperimentalWindowsDriveLetterHandling": true

and reloaded.  I don't see any warning about paths or case sensitivity.

**Comment by DanTup** [comment]
Doh! I'll take a look when next on Windows then. Thanks for checking! :-)

**Comment by keenedge** [comment]
Sure... happy to test more when you are ready.

**Comment by DanTup** [comment]
Oh, I figured out what this is - it doesn't trigger for drive letters because it's a different issue - the prompt is for when the casing doesn't match the underlying file-system, whereas this is the path going to the analysis server is not the drive letter it expects. So, all working as expected, and in v2.14 (of which you can get a beta [here](https://github.com/Dart-Code/Dart-Code/releases/tag/v2.14.0-beta.2)) the default settings will work, you won't need the one you set above.
