### ISSUE TITLE
VS Code erroneously claims that there are "No Devices" for running a Flutter app

### ISSUE THREAD

**Issue by johrpan** [Dart-Code/Dart-Code#996]
Running `flutter devices` and `flutter run` from a terminal works as expected. The error message I get is: `DEBUG: no domain for method: emulator.getEmulators`

![flutter_vscode_no_devices](https://user-images.githubusercontent.com/35040923/41189254-282d4814-6bcb-11e8-8bfe-07abd909e934.png)

I'm on Linux (Solus) and unfortunately I can't remember, when I ran into that problem first.

**Comment by DanTup** [comment]
Which version of Dart Code are you using? That error is normal if you're running a debug build and using a version of Flutter that doesn't support emulators; though it shouldn't affect the daemon otherwise.

Can you also enabled [Flutter Deamon logging](https://dartcode.org/docs/logging/#flutter-daemon) and attach the log?

**Comment by johrpan** [comment]
I'm running the flutter version which you get by following the standard installation procedure. These are the contents of the requested log file:

```
[11:54:43]: Spawning /home/johrpan/.FlutterSdk/bin/flutter with args ["daemon"]
[11:54:43]: ..  in /home/johrpan/.FlutterSdk
[11:54:43]: ==> [{"id":"1","method":"device.enable"}]
[11:54:46]: <== Starting device daemon...
[11:54:47]: <== [{"event":"daemon.showMessage","params":{"level":"warning","title":"Unable to list devices","message":"Unable to discover Android devices. Please run \"flutter doctor\" to diagnose potential issues"}}]
[11:54:47]: <== [{"id":"1"}]
[11:54:49]: ==> [{"id":"2","method":"emulator.getEmulators"}]
[11:54:49]: <== [{"id":"2","error":"no domain for method: emulator.getEmulators"}]
```

The `showMessage` line (note that I didn't see that message anywhere before) lead me to the following: I always used the VS Code's integrated terminal emulator to run `flutter doctor` and this was my output:

```
[flutter] flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.4.4, on Linux, locale de_DE.utf8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✗] Android Studio (not installed)
[✓] IntelliJ IDEA Community Edition (version 2018.1)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.
exit code 0
```
But now I tried to run `flutter doctor` using the provided command, and I got this:

```
[flutter] flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.4.4, on Linux, locale de_DE.utf8)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.
[✗] Android Studio (not installed)
[✓] IntelliJ IDEA Community Edition (version 2018.1)
[!] Connected devices
    ! No devices available

! Doctor found issues in 3 categories.
exit code 0
```

I'm pretty sure that I'm setting `ANDROID_HOME` correctly as it works in IntelliJ IDEA and in the terminal. Is it possible that VS Code somehow doesn't correctly inherit environment variables on Linux? Is there a workaround by manually setting the Android SDK path somewhere?

**Comment by DanTup** [comment]
I think this depends how you set your environment variables. If you're setting them in a terminal script that only runs when you start that terminal, then they won't be available if you launch Code outside of the terminal.

You should try and find a way to set the environment variable such that it applies globally. How to do this will likely depend on which distro etc. you're using (unfortunately I'm not all that familiar with any of them!).

Although we could probably add a setting in Dart Code; there are many environment variables that affect Flutter and having to special-case them all in the Dart Code settings feels like a bit of a burden, so it'd be best to exhaust other options first.

If you do figure it out, it'd be good to update [this page](https://dartcode.org/docs/configuring-path-and-environment-variables/) some some notes for whichever distro it is, so do ping me if you figure it out :-)

(as a workaround, you might be able to put a symlink in the default install location for the Android SDK into where you actually have it?)

**Comment by bjconlan** [comment]
@DanTup This was very much the case for me (Using `.bashrc` for storing android & flutter path properties) Resulted in the plugin reporting a device error but as you stated, moving this into `.profile` resolved the problem. (using ubuntu 18.04)

**Comment by DanTup** [comment]
Good to know! It seems quite common for people to set them in places they don't work, and how to set them globally seems to vary wildly across Linux distro's so it's hard to compile guidelines :( Glad you sorted it anyway! 👍
