### ISSUE TITLE
Running Dart

### ISSUE THREAD

**Issue by acidblue** [Dart-Code/Dart-Code#997]
Issue Type: <b>Bug</b>

When executing a dart console program I get the following error:
Cannot read property 'uri' of undefined
Program runs fine from cmd prompt, just not in visual studio.
Using WIN 7.

Extension version: 2.13.2
VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Athlon(tm) II X2 B24 Processor (2 x 2992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|12.00GB (6.73GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by DanTup** [comment]
Where are you seeing this message? Is there any more info like a stack trace?

Could you try enabling [Observatory Logging](https://dartcode.org/docs/logging/#observatory) to see if there's anything helpful in there?

**Comment by DanTup** [comment]
Also - do you have a folder open, or just a single `.dart` file?

**Comment by acidblue** [comment]
After some digging I discovered my Java Path wasn't set correctly, this appears to fix things.
In case any one else has the same problem:
Right click--Computer on the start menu go to 'Properties'--click 'Advance System Settings' --click 'Environment Variables' and in the System Settings make sure 'PATH' has the correct path to the jdk, on my Win 7 system it was C:\Program Files\Java\jdk-10.0.1\bin

**Comment by DanTup** [comment]
I'd still be interested in a full error/stack if you can get one so we can handle this better. Dart Code doesn't use Java directly, but I wonder if something went wrong with the build.
